### ISSUE TITLE
Items evaporate when picking up partial stacks

### ISSUE THREAD

**Issue by ZirconiumWit** [CleverRaven/Cataclysm-DDA#64756] opened 2023-04-01 14:56 UTC
### Describe the bug

When picking up partial stacks of items, the game subtracts double from the pile and the character receives the amount requested.  For example, when pulling a full stack of 5.56 NATO M855 out of the drawer next to my character in attached save, I get that full stack of ammunition.  If I pull, say, 400 bullets out of that stack, however, it subtracts 800 from the stack, and I only get 400 bullets in my inventory, the remaining 400 bullets simply evaporate.  Same goes for other stacked items, as well.  It did not matter if I was picking an item up from advanced inventory manager or just the regular Pickup menu.  Interestingly, it looks as though I can use the advanced inventory manager to MOVE a partial stack of items from the stack they're in and onto an adjacent tile and pick up that full stack without losing any items, so there are some workarounds, and the glitch only applies when moving a partial stack into the character inventory.  

### Attach save file

[Big Island-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11129775/Big.Island-trimmed.tar.gz)

### Steps to reproduce

1. Make a character
2. Try to pick up a portion of a stacked item, such as ammunition.  

### Expected behavior

Generally, items don't disappear into thin air when trying to just take some of them.

### Screenshots

![image](https://user-images.githubusercontent.com/59771903/229296149-8608f027-2ddf-4f30-8ee5-816e9b29bfa4.png)
![image](https://user-images.githubusercontent.com/59771903/229296227-918e1e13-b24e-4ff4-bd3e-b1d1216e62db.png)
![image](https://user-images.githubusercontent.com/59771903/229296265-13fa22a0-f181-497d-b25e-51917a510f8d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 41d1f50 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11129821/Save.zip)

It's my first report for this project, so apologies if I've erred. I spent a few minutes looking for similar issues but did not see any, so further apologies if I'm blind.

**Comment by AcidAntOnAMinefield** [comment] 2023-04-01 20:38
Can confirm this happened to me as well. 

Seems to be related to  #64588 and others.

**Comment by showervic** [comment] 2023-04-02 23:30
Able to reproduce in debug mode with stack of nails. And not only when moving to inventory, also when dropping
Steps to reproduce:
- spawn 3,000 nails
- wield 3,000 nails
- drop 1,000 nails
- now wielding 1,000 nails, should be 2,000

Also seen reverse behavior in game when dropped part of stack will not appear on tile ground but x2 amount will not be subtracted

**Comment by SurFlurer** [comment] 2023-04-04 11:16
Has this been fixed by #64634 ?

**Comment by ZirconiumWit** [comment] 2023-04-05 03:46
Issue appears fixed in latest experimental when testing for both picking up and dropping partial stacks of 5.56 Nato M855 and nails.

Thanks!

**Comment by SurFlurer** [comment] 2023-04-05 10:53
If you believe the issue has been fixed, you can close the issue. Thanks!

**Closed** 2023-04-05 11:29 UTC
Labels: (S1 - Need confirmation)
