### ISSUE TITLE
Spears incorrectly display as unrepairable in vanilla.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#36148] opened 2019-12-16 02:41 UTC
# Describe the bug

At least two spears, the wooden spear and steel spear, have the message "This item is not repairable" in their item description, when in fact they can be repaired in vanilla with a misc repair kit.

# Steps To Reproduce

1. Make a world with no mods.
2. Make/spawn a wooden spear, misc repair kit and duct tape.
3. Successfully repair wooden spear with misc repair kit.

# Expected behavior
The items should display "This item can be repaired with: Misc Repair Kit"

# Screenshots
https://cdn.discordapp.com/attachments/252368987210514433/655960387967254528/unknown.png

https://cdn.discordapp.com/attachments/252368987210514433/655962155899682861/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10157-gcf1dc76 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by PhilippGrosenick** [comment] 2019-12-16 03:59
Can confirm, all spears including the halberd, glaive and naginata show as non-repairable.

**Comment by ZhilkinSerg** [comment] 2019-12-16 12:56
Looks like resurfaced duplicate of #21573

**Closed** 2019-12-18 02:59 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface
