### ISSUE TITLE
Hostile Forge Demon sometime spawn outside of caged area in Forge Of Wonders from Magiclysm Mod.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#55370] opened 2022-02-14 11:10 UTC
### Describe the bug

Hostile Forge Demon will very rarely spawn outside of their supposed designated area when first arrived/ forge of wonder first time generated.

### Steps to reproduce

1. Use debug to reveal map and find a Forge Of Wonders location ( or spawn one ).
2. Hope that they spawn out of sheer luck in the open floor and burn your character with fire.

### Expected behavior

I expected them Forge Demons to stay where are, for the benefits of both me and them.

### Versions and configuration

- OS: Windows
    - OS Version: Win7 [64-bit]
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by TealcOneill** [comment] 2022-02-14 19:15
Duplicate of  #48785

**Closed** 2022-02-14 20:07 UTC
Labels: (S3 - Duplicate)
