### ISSUE TITLE
[ImGui] "Yes" is the default option

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#73023] opened 2024-04-14 12:20 UTC
### Describe the bug

The previous UI always had the default option as "no" (be it for giving up on a character, saving, etc.), and this change makes it so the default is now "yes", which makes it annoying and in some cases, actually dangerous. 

e.g.: accidentally hitting the key to give up on a character, and muscle memory pressing enter on "yes" when the expected behaviour would be for it to be on "no".

### Attach save file

N/A

### Steps to reproduce

1. Create a character.
2. "Q"uit that character. 
3. See that the default selection is "yes", instead of "no".
4. Wonder why this was changed in the first place. 

### Expected behavior

I would expect the default options in every situation to be "No".

### Screenshots

N/A

### Versions and configuration

Linux
Standard dda. 
954bacc build.

### Additional context

There is already an issue for the fact the font is different than that the player has set, and it's honestly very unpleasant to look at given how it clashes with the game's style itself, especially if one is using a tileset such as NeoDays. 

Please consider bringing back an option to keep the old UI - if anything for accessibility's sake, because the font and the way it is displayed is legitimately very offputting.

**Comment by NetSysFire** [comment] 2024-04-14 13:20
Duplicate of #72961

**Closed by NetSysFire** 2024-04-14 13:20 UTC
Labels: (S1 - Need confirmation)
