### ISSUE TITLE
'Could not find source vehicle for liquid transfer' (world save attached)

### ISSUE THREAD

**Issue by zacklucky7** [CleverRaven/Cataclysm-DDA#28214] opened 2019-02-15 19:26 UTC
**Describe the bug**  

When trying to siphon the gasoline from a vehicle, I am given the following error message:
```

 DEBUG    : error in activity data: "could not find source vehicle for liquid transfer"
 
 FUNCTION : void activity_handlers::fill_liquid_do_turn(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 1323
```

This does not happen with all vehicles. I was able to siphon from a different vehicle without issue.

**To Reproduce**  
1. [Download the world save (version 8522, only vanilla mods)](https://www.dropbox.com/s/lmzklx34tr02nbl/West%20Laurel.7z?dl=0)
2. Attempt to siphon from the vehicle directly south of the player character.

**Expected behavior**  
I expected to be able to siphon gas without issue, since I could siphon gas without issue from other vehicles.

**Screenshots**  
[Screenshot of vehicle screen ](https://i.imgur.com/vc53sya.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 Professional
 - Game Version: 0.C-37448-ga7144d2
 - Graphics version: Tiles
 - Mods loaded: All mods are included with the vanilla game.

1. "dda",
2. "dda-lua",
3.  "realguns",
4.  "growable-pots",
5.  "ew_pack",
6.  "makeshift",
7. "Medieval_Stuff",
8. "More_Survival_Tools",
9.  "nw_pack",
10.  "modular_turrets",
11. "Salvaged_Robots",
12.  "more_locations",
13.  "FujiStruct",
14.  "oa_additional_buildings_mod",
15.  "Urban_Development",
16.  "boats",
17.  "deoxymod",
18.  "blazemod",
19.  "Tanks",
20.  "necromancy",
21.  "filthy_morale",
22.  "no_reviving_zombies",
23.  "sleepdeprivation",
24.  "StatsThroughSkills"

**Additional context**  
[Download the world save (version 8522, only vanilla mods)](https://www.dropbox.com/s/lmzklx34tr02nbl/West%20Laurel.7z?dl=0)
[Screenshot of vehicle screen ](https://i.imgur.com/vc53sya.png)

I did see other (closed) issues for this issue when creating it.

**Comment by Night-Pryanik** [comment] 2020-04-13 16:49
Closing as non-confirmed for more than a year.

**Comment by l29ah** [comment] 2020-04-13 16:52
I can confirm it with the following save file while siphoning fuel from the semi truck: 
[2019.07.20-28214.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4470573/2019.07.20-28214.zip)

**Comment by l29ah** [comment] 2020-12-15 23:13
Now cataclysm crashes when i try to load the save.

**Comment by int-ua** [comment] 2021-01-14 03:32
Were both saves generated in an experimental build?

**Comment by OliveChukar** [comment] 2021-01-21 16:53
Tested in ver 0.E-9072-g1bb53ba-dirty with core content pack dark days ahead only. Was not able to load save in report or the one from Apr 13, 2020. Tried spawning a truck and damaging it to match the screenshot nothing odd happened with siphoning to or from this truck with either another vehicle or a container. Need more detail or a working save to test.

**Comment by int-ua** [comment] 2021-01-21 16:58
@zacklucky7, @l29ah, I believe you _were_ having this issue but it looks like fixed now, please comment if it's still relevant and I'll reopen.

**Comment by Aerotinge** [comment] 2021-05-08 07:44
I can have this issue with the current stable release 0.E-3.
`
 DEBUG    : error in activity data: "could not find source vehicle for liquid transfer"

 FUNCTION : void activity_handlers::fill_liquid_do_turn(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 1632
`
**Versions and configuration(please complete the following information):**
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    [dda],
    [no_npc_food],
    [sees_player_retro]
]
**Additional context**
[Savefile ](https://up.labstack.com/kFUVXKGb)(Ellison-3)

**Comment by l29ah** [comment] 2021-11-20 08:08
Got "could not find target vehicle for liquid transfer" on 47cbf6852d: 
[2021.11.18.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7570501/2021.11.18.zip)

**Comment by cecilgol** [comment] 2021-12-07 02:41
@l29ah try moving the vehicle - the error is caused by a null position value. i was able to reset it by moving it one tile.

**Closed** 2022-08-29 02:58 UTC
Labels: <Bug>, Vehicles
