### ISSUE TITLE
Migration support to convert charges to copies

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#54376] opened 2022-01-13 19:08 UTC
### Is your feature request related to a problem? Please describe.

Working down the chain of tasks on the tailoring audit #53436, it's been decided that the fabrics should migrate from ammo to generic. I was attempting this in #54308, and the work on genericizing them is done, but the migration is blocking approval for the merge. When the item types are changed to generic, their charges are removed, so cotton sheet (1500) becomes 1 cotton sheet.

I'd do it myself, but after two days of trying to figure this out, I'm going to admit that this is beyond my skillset and knowledge of C++.

### Solution you would like.

a 1:1 charge to item conversion

savegame_json.cpp could possibly be modified to catch this in the io<Archive> function. [This if block](https://github.com/CleverRaven/Cataclysm-DDA/blob/9f2940aebb0813529c50b78dbfc0f357cf8b81b3/src/savegame_json.cpp#L2898) already checks for items with charges that shouldn't have them, and will throw an error if the items isn't in the charge obsoletion file, before setting charges to zero.

Adding an else to the end of that check on 2901 would be a good place to have the charge removed and then spawn in copies equal to the number of charges, but I'm not exactly clear on how to handle that part.

### Describe alternatives you have considered.

a more elegant solution would be being able to specify the conversion ratio in an obsoletion file

**Comment by mqrause** [comment] 2022-01-13 19:57
> [This if block](https://github.com/CleverRaven/Cataclysm-DDA/blob/9f2940aebb0813529c50b78dbfc0f357cf8b81b3/src/savegame_json.cpp#L2898) already checks for items with charges that shouldn't have them, and will throw an error if the items isn't in the charge obsoletion file, before setting charges to zero.
> 
> Adding an else to the end of that check on 2901 would be a good place to have the charge removed and then spawn in copies equal to the number of charges, but I'm not exactly clear on how to handle that part.

As far as I understand that, it isn't possible to handle it there because that `Archive` can only be a single item, see `item::deserialize`. It's only able to do sanity checks of item properties, like remove charges if it can't have any.

**Comment by a-chancey** [comment] 2022-01-13 20:30
good to know. I'm a C# guy by day so reading CPP is like trying to read Dutch as an American. It looks familiar but wait what the hell does that mean?

**Comment by kevingranade** [comment] 2022-01-13 23:54
I just had a kind of crazy idea, at the point you identified, you could change the item being handled from a rag to a "bundle of rags", and insert the appropriate number of items into it based on the charges.

**Comment by PatrikLundell** [comment] 2022-01-14 08:42
Not ideal to force the player to manually dissemble the bundles generated, but certainly better than crushing stacks down to a single item. It would probably be confusing for players to find that they don't have any tailoring material after a migration, as all of it is suddenly locked up in bundles. Bonus points for creative thinking, but I think a proper migration is needed.

**Comment by anothersimulacrum** [comment] 2022-01-14 13:33
I think these 'bundles' would be bags of rags/patches, not the proper bundle items, because migrating to the bundle item won't fix this (bundle items are of fixed size, we need to migrate to arbitrary size)

**Closed** 2022-01-28 06:07 UTC
Labels: [C++], Items / Item Actions / Item Qualities, 0.G suggested release blocker

**Comment by mqrause** [comment] 2022-01-28 14:32
They should also have copies in their migration pocket, but you need to pick them up for them to fall out.

**Comment by a-chancey** [comment] 2022-01-28 16:23
Oh yeah, I see that now, my bad. I missed the migration blacklist step initially.

did notice an issue or two so far - I migrated all the fabric scraps, and cotton scraps (50) gave me cotton scrap > 49 cotton scraps as expected. I then tried to pick up 1 (pressing 1 then l to select by quantity) and the game hung. Picking up the bundle broke it out into separate items, so that seems to work fine

**Comment by mqrause** [comment] 2022-01-28 16:57
> I then tried to pick up 1 (pressing 1 then l to select by quantity) and the game hung

I'm not sure what you mean there? I did notice menus being slow to open with lots of items (~1000 in my test) in migration pockets, but after that everything went as usual. Items in the migration pocket shouldn't be directly accessible anyway.

**Comment by a-chancey** [comment] 2022-01-28 16:59
the game actually crashed completely and closed without giving an error message. i'd need to fire it up via visual studio to see what the error was.

**Comment by a-chancey** [comment] 2022-01-28 17:43
Ok other than the crash when trying to access individual items from the bundle, this works. Not sure how to deal with that, but yeah, picking them up breaks them apart and the ones in my inventory broke apart in one turn. I’ll get the fabric genericizing done today so I can get the rest of the tailoring stuff done. 

Thanks for your hard work!

**Comment by mqrause** [comment] 2022-01-28 17:49
I'll check the crash out later. That really shouldn't happen.

**Comment by mqrause** [comment] 2022-01-29 20:17
I can't reproduce your crash. Pressing 1 (or any number) and then select just selects the one item here, because the ones in the pocket aren't accessible.
![grafik](https://user-images.githubusercontent.com/38702195/151676219-ad489413-c0b5-4e3f-9045-5633ffcb8d0c.png)

**Comment by a-chancey** [comment] 2022-01-29 23:45
Alright I’ll see if I can reproduce it later. It could have just been this weird inventory item selection bug I only have when running it in debug.
