### ISSUE TITLE
Visual issues with Chesthole tileset

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#21100] opened 2017-05-23 18:03 UTC
Strawberry and other bushes appear to have berries when out of season.

Wooden doors are visually inconsistent. Outside doors appear to be a recolored metal door, while also having an anomalous top-down perspective, while interior doors seem to properly resemble doors.

Hellfire stave and veinreaver (from Arcana and Magic Items mod) are represented by what appear to be vehicle rams.

Pinging @Chezzo as it is their tileset. I would submit a pull request to alter these, but I am uncertain how they would prefer these to be handled.

**Comment by Chezzo** [comment] 2017-05-23 20:58
I'm not sure what you mean with the door thing. Can you provide a screenshot?

**Comment by DangerNoodle** [comment] 2017-05-23 21:08
To provide examples, these are all using the same external door, before applying a crowbar, afterward, and then after closing the now unlocked door.

![1](https://cloud.githubusercontent.com/assets/22048567/26376392/f7147214-3fd1-11e7-96ea-6ddb8e9c2332.png)

![2](https://cloud.githubusercontent.com/assets/22048567/26376409/008ce222-3fd2-11e7-877d-8984689bec12.png)

![3](https://cloud.githubusercontent.com/assets/22048567/26376422/08eb839c-3fd2-11e7-8a2d-ecca93f6cdbb.png)

**Comment by Chezzo** [comment] 2017-05-23 21:17
I teleported to lots of doors with a crowbar, and I am unable to reproduce this. Do you know what the tile_id of the resulting doors are?

**Comment by DangerNoodle** [comment] 2017-05-23 21:25
Strange. Has this been fixed somewhat recently? This is in build 0-C-22346-g141eb46668 (build number 6442).

Further testing led me to find several doors that do not exibhit this. Double checked and it would appear that the affected door is the "door with peephole" variant.

**Comment by DangerNoodle** [comment] 2017-05-23 21:38
Another anomaly observed.

`t_door_metal_pickable` (the locked metal doors players can pick):
![6](https://cloud.githubusercontent.com/assets/22048567/26377498/34202848-3fd6-11e7-920a-646e0cb91a4d.png)

`t_door_metal_c` (the resulting closed, unlocked metal door):
![7](https://cloud.githubusercontent.com/assets/22048567/26377500/36fd3362-3fd6-11e7-8d8a-d525c52134ea.png)

`t_door_metal_o` (unlocked metal door, opened):
![8](https://cloud.githubusercontent.com/assets/22048567/26377505/3ae50112-3fd6-11e7-9d8e-d7be9bfe41f1.png)

**Comment by ZenZen2** [comment] 2017-05-25 01:55
Your ID's for the external vehicle tanks are outdated.
Copy this into your Tiles and they will display again.

```

        {
          "id": "vp_external_tank_small",
          "fg": 3275,
          "rotates": true,
          "multitile": true,
          "additional_tiles": [
            {
              "id": "broken",
              "fg": 3277
            }
      ]
        },
        {
          "id": "vp_external_tank",
          "fg": 2678,
          "rotates": true,
          "multitile": true,
          "additional_tiles": [
            {
              "id": "broken",
              "fg": 3062
            }
      ]
        },

```

**Comment by DangerNoodle** [comment] 2017-05-25 04:30
Issue also exists with the MShock series if I recall.

**Comment by Chezzo** [comment] 2017-05-30 14:42
Awesome, I have all this stuff fixed now. I will pr it soon.

**Closed** 2017-05-31 05:47 UTC
Labels: Tiles
