### ISSUE TITLE
No way to tell hunger/thirst/fatigue/time when working on a vehicle

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#19856] opened 2016-12-26 22:02 UTC
Not sure when this changed, but it used to drop you out of the vehicle GUI for a few seconds when you modified a vehicle and now it doesn't. Which means you have to remember to exit the vehicle GUI every so often to check manually while working otherwise you can easily spend all day working on a vehicle without realizing it, and having no clue that you're overly hungry or thirsty. It will pull you back when you hit a critical level, like dead tired, but that is it.

Ideally the vehicle GUI should be like the inventory GUI is now, as in not full screen. The problem is it really does need the screen real estate. Lacking that, there should be *some* tie to the outside reality because it really doesn't feel like time is passing. You work on 4 separate parts and 3 hours pass outside, but since it took you seconds each you may not realize it. So you keep working and now 3 minutes of real time work in the vehicle GUI means 16 hours has passed in game.

**Comment by ZenZen2** [comment] 2016-12-27 04:50
Display refresh bug.

duplicate of #19317

**Closed** 2017-01-04 07:50 UTC
