### ISSUE TITLE
Alonso Quest Error

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69806] opened 2023-11-27 22:05 UTC
### Describe the bug

When one says “I’ll do it” to accept Alonso’s quest to find his special pants, an error will Occur.

### Attach save file

N/A-Doesn’t work on Mac :(

### Steps to reproduce

1. Go to Ref Center 
2. Talk to Alonso
3. Attempt to start quest
4. Error!

### Expected behavior

The quest being able to fire

### Versions and configuration

OS: Mac OS Big Sur
Version: da41ccb
Mods: Standard, with Bionic Professions and Stats through skills

### Additional context

DEBUG    : Unable to find and assign mission target cs_sex_shop.

 FUNCTION : std::optional<tripoint_abs_omt> find_or_create_om_terrain(const tripoint_abs_omt &, const mission_target_params &, dialogue &)
 FILE     : src/mission_util.cpp
 LINE     : 258
 VERSION  : da41ccb

**Comment by l29ah** [comment] 2024-08-31 02:17
/confirmed
I just hit it as well.

**Comment by l29ah** [comment] 2024-08-31 02:40
Reproducing save: 
[2024.08.21.zip](https://github.com/user-attachments/files/16823209/2024.08.21.zip)

**Comment by Night-Pryanik** [comment] 2024-11-14 16:48
Duplicate of #48029.

**Closed by Night-Pryanik** 2024-11-14 16:48 UTC
Labels: (S2 - Confirmed)
