### ISSUE TITLE
Xedra Evolved Vampire Stage 2 Questline Bugged

### ISSUE THREAD

**Issue by Xeno-Le-Morph** [CleverRaven/Cataclysm-DDA#75247] opened 2024-07-25 23:34 UTC
### Describe the bug

A series of bugs that will make this a bit annoying to further take apart
1. It is possible to get the Kill your Best Friend Quest multiple times by asking the vampire NPC in the cathedral about becoming a stronger vampire (Note: the quest doesnt say who gave it to you)
2. If you use Debug to increase trust on a NPC you will not be able to ask them how they feel about you
3. You can gain the quest to find a specific book for a NPC when asking how they feel about you, but completeing it has no effect and can also be gained multiple times (The Quest doesnt say who its from)

### Attach save file

[Nezperce-trimmed.tar.gz](https://github.com/user-attachments/files/16384448/Nezperce-trimmed.tar.gz)

### Steps to reproduce

1. Teleport to Xedra cathedral when properly infected with the vampire virus
2. ask him how to become a stronger vampire
3. stop talking to him
4. ask him again

1. Use Debug to make a npc obey you or simply complete a quest and have them like you
2. Use debug to increase trust by ten (this will result in the option to ask their opinion about you no longer being avaliable)
3. use debug to lower trust by ten to undo the bug
4. ask them for their opinion about you multiple times to get the quest to retrieve a book multiple times
5. Aquire books (if spawned in drop them and then pick them up) to complete the quest. Notice nothing changed with the NPC

### Expected behavior

The quest should work

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: b0aae89 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved]
]

**Comment by SariusSkelrets** [comment] 2024-07-26 00:20
I can confirm the third. Will adjust the first while I'm here

1. I'll add a check for if you already have the mission. The quest doesn't say who gave it because this is unneeded to complete it

2. Cannot confirm. Been using debug mind control for my testings and I haven't encountered issues on that side

3. I made the fix in my current vampire PR a few hours ago

**Comment by Xeno-Le-Morph** [comment] 2024-07-26 03:47
Im assuming the Pr your talking about is the tier 5 Vamp one? 
I just like to keep up to date on features i like

**Comment by Maleclypse** [comment] 2024-07-26 04:11
Sidenote: `If you use Debug to increase trust on a NPC you will not be able to ask them how they feel about you` isn't a problem to be bugfixed. Debug breaks all kinds of things.

**Comment by SariusSkelrets** [comment] 2024-07-26 15:00
> Im assuming the Pr your talking about is the tier 5 Vamp one?
Yes it's that one

**Comment by Maleclypse** [comment] 2024-07-28 22:12
I believe this was closed by Sarius' recent PR.  Ping me if this needs to reopen.

**Closed by Maleclypse** 2024-07-28 22:12 UTC
Labels: (S1 - Need confirmation)
