### ISSUE TITLE
Peeking down stairs teleports me to the middle of the room

### ISSUE THREAD

**Issue by dbabbc** [CleverRaven/Cataclysm-DDA#54076] opened 2022-01-05 19:34 UTC
### Describe the bug

I have only seen this happen in a bunker base. When peeking down the stairs, I peek as if the stairs were in the middle of the room, instead of where they actually are. Going down them normally does not put me in the middle of the room. 

No mods except the default ones enabled. 

![image](https://user-images.githubusercontent.com/97192509/148277415-6fdbe3e5-78c0-48c7-9eeb-b6b8eabe577c.png)

![image](https://user-images.githubusercontent.com/97192509/148277445-7df2bc89-16f6-4310-af06-f66d89d7cbff.png)

![image](https://user-images.githubusercontent.com/97192509/148277464-bb78c8e4-dc71-4929-a48c-699b6476a202.png)

### Steps to reproduce

1. Get on top of the stairs to the bunker base
2. Peek down the stairs

### Expected behavior

I expect my player to peek down the stairs and be in the position of the stairs, not in the middle of the room. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a1f0736 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Michael1993** [comment] 2022-01-05 20:10
I've seen this happen with caves too.

**Comment by dbabbc** [comment] 2022-01-05 21:39
Addendum to the issue. Also seems to happen on LMOE shelters, and not just peeking down stairs, but also up. 

![image](https://user-images.githubusercontent.com/97192509/148293152-57ca70b7-7094-468e-8b26-b2a819a2cdac.png)

![image](https://user-images.githubusercontent.com/97192509/148293204-cd937826-25f2-4d1c-886f-dc827c96110c.png)

![image](https://user-images.githubusercontent.com/97192509/148293245-13415d1a-bf7b-4841-aa6c-1b12b7b9ae51.png)

![image](https://user-images.githubusercontent.com/97192509/148293273-d92264d8-cb92-48ed-8b71-1fa8cd6861c7.png)

**Comment by Terrorforge** [comment] 2022-01-05 22:00
It happens in (old) labs as well, although frequently you simply won't be allowed to peek at all. I've been told this is due to the stairs on each level not being aligned.

**Comment by ZhilkinSerg** [comment] 2022-01-05 23:20
Duplicate of #53388

**Comment by LeahLuong** [comment] 2022-01-06 03:59
@ZhilkinSerg Pretty sure this issue has come up before but I think you chose the wrong 1. In the 1 you reference, the char _**moves**_ to a different stair after peeking. Here, the peeking action simply causes the player's perspective to shift a Z-lvl while maintaining coords.

In addition to this effect, light cast from a higher Z-lvl will show up @ the peeked-from location instead of the stairs you come down.

**Comment by GoLoT** [comment] 2022-01-13 11:08
Related / duplicate: #52379

**Closed** 2022-06-19 23:47 UTC
Labels: <Bug>, (S3 - Duplicate), Map / Mapgen, Z-levels
