### ISSUE TITLE
Unable to play world on latest build

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#31450] opened 2019-06-15 06:34 UTC
![image](https://user-images.githubusercontent.com/44106380/59547928-587e5580-8f79-11e9-887d-3284d83532fb.png)

I've updated to the latest build 9157.
Since then i still can't load my game and had to revert to build 9140 for the second time.

**Comment by LaVeyanFiend** [comment] 2019-06-15 06:42
Duplicate of #31399. Should be fixed once once #31442 gets merged.

**Closed** 2019-06-15 18:34 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
