### ISSUE TITLE
Corrupted appliance take down results in crash

### ISSUE THREAD

**Issue by Nattfarinn** [CleverRaven/Cataclysm-DDA#67971] opened 2023-09-01 01:21 UTC
### Describe the bug

Somehow my appliances got corrupted. I can't take down 3 solar panels and battery (option to do that is grayed out). When I instead try to place new solar panel, my current appliances teleport few tiles to the left and taking any of them down results in crash.

Cross issue (maybe related due to save corruption): I have two large squares of eternal darkness near base. 

### Attach save file

[Circle Pines-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12491903/Circle.Pines-trimmed.tar.gz)

### Steps to reproduce

Not sure how to reproduce without save file. But with save loaded:
1. Try to take down appliance, solar panel or battery.
2. Not possible, option grayed out,
3. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`),
4. Previous appliances teleport few tiles to the left,
5. Try to take down *teleported* appliance,
6. Game crashes.

I've been able to make it work without crash and "decorrupt" appliances doing:
1. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`),
2. Previous appliances teleport few tiles to the left,
3. Take down this new solar panel,
4. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`) again,
5. Now I've been able to take down everything without crash.

But I am not sure if my save isn't still corrupted in less apparent way.

### Expected behavior

I would expect I'll be able to take down my appliances without crash.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 2e4ad5f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12491940/debug.log)
[Circle Pines.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12491945/Circle.Pines.zip)

`crash.log` does not exist.

**Comment by Kamayana** [comment] 2023-09-04 22:08
Can reproduce. For some reason the battery+panels get their mount points all mixed up, and it then crashes here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/94f58ea90aae5e022bf1398d3d599c42dd37bae9/src/vehicle.cpp#L1990-L1991
`handler.removed` isn't set up to handle a vp_idx of -1, which `index_of_part` returns when given an invalid part, and it's invalid because it's looking for a mount of 3,1 rather than 0,0 like it should always be for appliances. While this crash could be fixed by checking for the -1, it still causes problems outside of that because it doesn't actually remove the part it's trying to.

**Comment by Kamayana** [comment] 2023-09-04 22:32
This is the line that's moving the vehicle over:

https://github.com/CleverRaven/Cataclysm-DDA/blob/94f58ea90aae5e022bf1398d3d599c42dd37bae9/src/vehicle.cpp#L1832

The pivots are getting offset for some reason. It looks like #60681 might be involved here.

**Closed** 2024-03-26 08:45 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), [C++], Appliance/Power Grid, Help Wanted
