### ISSUE TITLE
Surrounded start spawns monsters in midair

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55994] opened 2022-03-10 09:08 UTC
### Describe the bug

The surrounded start scenario flag spawns monsters in open air tiles if the start location is not on the ground floor.

I removed the flag for large building starts in #55809 to avoid this issue, but in hindsight the proper fix would be to either find valid locations for the monster to spawn, or always have them spawn on the ground floor regardless of the player z level.

### Steps to reproduce

Start in a scenario that has the surrounded start flag and the spawn location is not on the ground floor (haven't checked to see if any starts still meet these criteria by default anymore). Observe flying monsters. Take a step and observe their transition to (un)graceful falling.

### Expected behavior

Monsters spawn on valid floor tiles, or on the ground floor.

### Versions and configuration

N/A

**Comment by Night-Pryanik** [comment] 2022-03-10 09:57
Duplicate of #46861.

**Closed by Night-Pryanik** 2022-03-10 09:57 UTC
Labels: <Bug>, Spawn, [C++]
