### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40693] opened 2020-05-19 11:18 UTC
'r'eading/'a'ctivating maps does nothing. 

All that comes up is "reading in progress press 5 or . to stop early" or something similar.

**Comment by wapcaplet** [comment] 2020-05-22 23:41
Appears to be a duplicate of #40724 (now resolved and closed).

**Comment by Night-Pryanik** [comment] 2020-06-07 11:03
Closing until reconfirmed.

**Closed by Night-Pryanik** 2020-06-07 11:03 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
