### ISSUE TITLE
spear strap material mismatch

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#54980] opened 2022-01-31 23:15 UTC
### Describe the bug

spear straps material is leather but based on the crafting recipe it should be cotton.

### Steps to reproduce

look at the crafting recipe for a spear strap

### Expected behavior

cotton should be at least one of the materials for spear straps.

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/151888154-62c95361-be19-409c-a5a8-711813849d65.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 372311f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Hope [no_hope],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

 this can affect gameplay when/if you need to repair it (it's how i noticed it).

**Comment by coyo7e** [comment] 2022-02-01 01:15
FWIW this seems to only be in the items' overall "material" summary. I can make spear straps from cotton and/or string, and taking the item apart results in the same type of items I crafted it from despite the "MATERIALS: " legend always saying "LEATHER". I thought it used to be able to use some leather patches for the recipe though, did that change?

![image](https://user-images.githubusercontent.com/80022377/151898790-f727c158-b376-499f-a97f-26a8ff7f29c4.png)

**Comment by robotic-gamer** [comment] 2022-02-01 11:20
you can use leather patches as an alternative to a bit of cordage or thread. But I can't think of a non-contrived case where that's the best option (anywhere rural short cordage piece is best, urban you can use 1 short string).

**Comment by Night-Pryanik** [comment] 2022-02-05 15:29
Duplicate of #50822.

**Closed by Night-Pryanik** 2022-02-05 15:29 UTC
