### ISSUE TITLE
AR-15 is no longer a valid Krav Maga weapon

### ISSUE THREAD

**Issue by Zyzarda** [CleverRaven/Cataclysm-DDA#68520] opened 2023-10-06 03:52 UTC
### Describe the bug

When I use my AR-15 rifle and try to use Krav Maga, it tells me its not a valid weapon for it. I even tried removing the medium length barrel and sling and without any mods it is still not a valid weapon.

### Attach save file

N/A, easily replicable using any current version experimental branch.

### Steps to reproduce

Use debug to spawn an AR-15 and unlock the Krav Maga style
Attempt to use Krav Maga with it.

### Expected behavior

I'd imagine it'd become unusable with a longer barrel, but it doesn't work at any level.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ce83cf9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by NetSysFire** [comment] 2023-10-06 06:46
I do not know which version you are coming from but it looks like this happens because the AR-15 does not have any category at all set, so it does not match the following:

https://github.com/CleverRaven/Cataclysm-DDA/blob/eeb6868627e34f1b4ba9a9fda9095d997e34ce19/data/json/martialarts.json#L779

I am woefully inexperienced with martial arts and guns in particular, so I do not know if this was nerfed on purpose or accidentally broken in a complex PR.

**Comment by NetSysFire** [comment] 2023-10-06 07:43
Appears to be a regression, apparently the old AR-15 has it but the new one does not.

**Comment by ZhilkinSerg** [comment] 2023-10-06 09:30
Duplicate of #67600

**Closed by ZhilkinSerg** 2023-10-06 09:30 UTC
Labels: Good First Issue, (S2 - Confirmed), [JSON], Items: Ammo / Guns, Martial Arts
