### ISSUE TITLE
Candle mishap <Bug>

### ISSUE THREAD

**Issue by Katanasoul91** [CleverRaven/Cataclysm-DDA#41051] opened 2020-06-03 17:52 UTC
# Describe the bug
The candles only last for twenty minutes in-game before popping a window asking "Light where? (Direction button)"

# Steps To Reproduce
1 Get/spawn a candle (not lit)
2 Activate it.

# Expected behavior
If you spawn a lit candle it lasts for much longer than the activated ones.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-2805-g2e524a6

# Additional context
![Candle fire](https://user-images.githubusercontent.com/62341576/83670428-87864080-a5a9-11ea-9290-b94ebeb201b3.png)

**Comment by TheMasterGear** [comment] 2020-06-06 19:49
Yeah, this also a problem on my end as well. It seems like the fuel of the candle might be bugged.

 OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2919-g000ecc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Pixel's Various Fuckery [Pix's Shit],
    Pneumatic Guns [pneumatic],
    Ricky's Future Armory [futurearmory],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex]
]

**Comment by Jerimee** [comment] 2020-06-11 02:28
Might not be related, but my entire game crashes if I:

- light a candle
- drop it on a table
- read a book in the tile immediately adjacent

This happened twice in row this evening.  Attached are debug.log and crash.log

Mods are:

- Dark Days Ahead [dda],
- Disable NPC Needs [no_npc_food],
- No fungal monsters


[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4762204/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4762205/crash.log)

**Comment by hexagonrecursion** [comment] 2020-06-23 15:46
duplicate of: https://github.com/CleverRaven/Cataclysm-DDA/issues/40858

**Closed** 2020-06-23 16:15 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
