### ISSUE TITLE
Graphic settings are not saved 

### ISSUE THREAD

**Issue by IvanGovnov** [CleverRaven/Cataclysm-DDA#35674] opened 2019-11-23 12:16 UTC
1. go to the game settings
2.try changing the screen resolution
3. exit the settings
4. the game does not ask whether it is necessary to save the changes and does not save them
OC: Android 9
Game Version: 0.D-9617-g342f101
Graphics Version: Tileset, RetroDays
Mods loaded: I have no third-party mods.

**Comment by AMurkin** [comment] 2019-11-23 12:19
Duplicate of the #35631

**Closed** 2019-11-23 12:23 UTC
