### ISSUE TITLE
Practising Computers (Beginner) Impossible in the Dark

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54660] opened 2022-01-22 03:05 UTC
### Describe the bug

You cannot practise computer skill in the dark. I haven't checked the higher level computer skills, just noticed this on the beginner one for now but I'd assume they're all the same.

Smartphones and laptops both have backlit screens so I see no reason why this would be more than a mild inconvenience at best since you can easily type by the light of your computer screen, and tablets/smartphones don't need light at all to use, since their "keyboards" are in the backlit screen (unless you are still using a Blackberry, you monster!) 

I bet someone's even reading this post in the dark  on their phone/computer right now.

### Steps to reproduce

1. Select Computers (beginner).
2. Note that it says "Impossible" to practise in the dark.
3. Profit!

### Expected behavior

Expected to be able to save candles/etc by practising computers in the dark until my character got tired and could go to sleep.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/150622507-61ae8fc0-2971-4c26-900d-5d2221394330.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a3d494f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment] 2022-01-22 03:44
Dupe of #51412. Please do a basic search before posting issues you think no 1 else has encountered. Not only has this been encountered, efforts were made to address it & the multiple threads generated would have made a basic search that much easier to conduct.

**Comment by Leland** [comment] 2022-01-24 02:05
Duplicate of #51412 per above, closing.

Thanks for filing, @coyo7e! I can confirm I am reading this in the dark on my computer :smile:

**Closed by Leland** 2022-01-24 02:05 UTC
