### ISSUE TITLE
Dissecting Gigantic Molerats grants burntout Bionic

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#52948] opened 2021-11-21 21:00 UTC
### Describe the bug

Unsure whether this iss intended or not, but i wanted to try to get some samples from molerats ... and i assumed you get samples by disecting then ( it appears i was wrong)

anyway i got burnt out bionics instead which seem weird for molerats kinda

### Steps To Reproduce

Find Molerat underground
kill Molerat
Dissect Dead Molerat

### Expected behavior

No burnt out bionics from Molerats, maybe even some samples for mutation but thats secondary

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/142778618-ab2b706b-2840-43a4-b7fd-233180dfdf5b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 03f9cc1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Terrorforge** [comment] 2021-11-21 21:52
It's a known issue. You get burnt out bionics specifically because the samples piggyback on the cbm dissection infrastructure. It's being worked on.

You are supposed to be getting samples, the odds just aren't great. Though that's an issue all on its own. Molerats are rare to begin with, and you don't get the samples very often, so even getting 3 for a single dose of mutagen is a challenge, and actually breaching the Troglobite threshold is practically impossible.

**Comment by wapcaplet** [comment] 2021-11-22 02:16
Yeah, mole rats dropping bionics is definitely a bug. This can be considered a duplicate of #52318.

**Closed** 2021-11-22 02:17 UTC
Labels: (S3 - Duplicate)
