### ISSUE TITLE
Finished charcoal kiln has unexpected advanced inventory behavior

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#38398] opened 2020-02-27 09:43 UTC
# Describe the bug

When a charcoal kiln is done burning, in advanced inventory, it acts like an untouchable square and you don't see that it has any contents until you (e)xamine it.

# Steps To Reproduce

Burn wood in a charcoal kiln.
After the burn is done, approach the kiln. You will notice that no items are visible in the kiln on the map.
Next to the kiln, use /advanced inventory.
You will not see the contents of the kiln, or be able to access them; the kiln square is red and gives you a message "you can't put items there" if you try to access it in advanced inventory using the direction of the kiln.
Exit advanced inventory and (e)xamine the kiln.
Immediately, charcoal becomes visible on the map in the kiln, and you see the charcoal.
Use /advanced inventory.
You can now select the kiln and see the contained charcoal and move it.

# Expected behavior

After the kiln is done burning, the charcoal is visible and you can use advanced inventory to move the charcoal without first (e)xamining the kiln.

# Screenshots

![sc001371](https://user-images.githubusercontent.com/1361701/75431393-eb90db80-59a0-11ea-927b-4f67bc5aabbc.png)
Advanced inventory next to a kiln that is done burning; the kiln is in the 8 square but can't be selected and the charcoal is not visible.

![sc001372](https://user-images.githubusercontent.com/1361701/75431419-f3508000-59a0-11ea-88c7-353bcfc9c0f6.png)
Quitting advanced inventory and (e)xamining, the charcoal becomes immediately visible (previously, it looked like an empty kiln).

![sc001373](https://user-images.githubusercontent.com/1361701/75431447-f9def780-59a0-11ea-8243-e39ef4edd544.png)
In advanced inventory, the kiln is now selectable and shows its contents.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12430-g142295b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

# Additional context

There are some general inconsistency issues with delayed-action items like the smoking rack and charcoal smokers and how the player is expected to interact with them. This one seems like isolated low-hanging fruit.

**Comment by Night-Pryanik** [comment] 2022-08-29 16:49
I don't think it's a _bug_, but rather a feature of implementation of kiln's mechanics: game adds charcoal when examining the kiln. I'd close this issue.

**Comment by RenechCDDA** [comment] 2023-10-20 09:52
Yes, this is working as intended.

**Closed by RenechCDDA** 2023-10-20 09:52 UTC
Labels: <Bug>, Crafting / Construction / Recipes, [C++]
