### ISSUE TITLE
Syphoning any amount of fuel between vehicles fills gastank to the brim

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#40900] opened 2020-05-27 18:14 UTC
When syphoning fuel between two vehicles via rubber hose, no matter the amount of fuel transfered, the receiving tank will be filled to the full capacity (60 liter tank will have 60 liters of gas, even when only 1.2 liters was syponed and less than 58.8 was already inside).

# Steps To Reproduce

1. Get a Rubber Hose item
2. (a) use it on a vehicle with small amount of fuel in its tank
3. Choose to transfer fuel to another vehicle nearby

# Expected behavior

Should transfer as much fuel as the targeted vehicle actually contained.

 - OS: Win 7
 - Game Version: 0.E 2532-gf4bb830
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC Needs, Blaze Ind., Magiclysm, No Rail Stations, Graphical Overmap, Graph. Overmap Magiclysm, No Fungal Monsters, Stats Through Skills

**Comment by hexagonrecursion** [comment] 2020-05-27 18:27
Duplicate of #40369

**Closed** 2020-05-28 04:16 UTC
