### ISSUE TITLE
Using first aid kits on NPCs doesnt use a kit, but heals them anyway.

### ISSUE THREAD

**Issue by Autastic** [CleverRaven/Cataclysm-DDA#20490] opened 2017-03-08 07:23 UTC
had two first aid kits in inventory, used them on an npc. version 6256. dont want to brick my save so can someone please confirm on latest?

**Comment by kolsurma** [comment] 2017-03-08 07:43
Thanks for the bug report!

This is a duplicate of #20090, closed in #20332. Merged into master in version 6259.

**Closed** 2017-03-13 04:49 UTC
