### ISSUE TITLE
Lab Challenge - Science ID Card does not work with Card Reader

### ISSUE THREAD

**Issue by bussr** [CleverRaven/Cataclysm-DDA#60494] opened 2022-08-27 17:27 UTC
### Describe the bug

The Card Reader controlling the exit doors to a Lab (Lab Challenge start) does not function. Character has a Science ID Card in inventory. Card Reader upon (e)xamine says "The console doesn't display anything coherent."

### Steps to reproduce

1. Lab Challenge Start
2. Grab Science ID Card
3. Try to exit lab.
4. Card Reader at top floor exit does not consume Science ID and unlock the door.

### Expected behavior

I expected the Card Reader at the lab exit to consume the Science ID Card and unlock the metal door.

### Screenshots

![Hilary Edgar __17-05-18_Pacific Standard Time](https://user-images.githubusercontent.com/1424477/187041160-f3a06051-2aea-42fe-88b5-1921e7d456a7.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Zipped the whole save file:
[LabChallenge-SciIDFailsToOpenCardReader.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9438396/LabChallenge-SciIDFailsToOpenCardReader.zip)

**Comment by Hirmuolio** [comment] 2022-08-28 07:38
Works in latest experimentals.

**Comment by PatrikLundell** [comment] 2022-08-28 09:18
/confirmed

The issue here is that there is both a card reader AND a terminal at the tile, and for some reason the console blocks the access to the card reader. I tried the save with what I compiled a few days ago, and found that I couldn't access the card reader, downloaded the latest Master (as of a few minutes ago), compiled, and tried again with the same result.
Debug removing the terminal (replacing it with nothing) allowed the card reader to be accessed.

It can be noted that actions resulted in strange error reports about 72.0000 or whatever whenever the character moved both before and after recompilation, but I haven't investigated that further.

**Comment by Hirmuolio** [comment] 2022-08-28 10:13
Do different lab variants have different surface room? The one I spawned in had working card reader.

**Comment by PatrikLundell** [comment] 2022-08-28 10:20
I used the save, and the room in that save was clearly incorrectly generated. One possible reason for it being incorrect would be issues with rotations, while another, as suggested, might be different layouts. A third possibility is that there's a percentage furniture generation that occasionally generated a console on top of the card reader, in which case you might have to generate the room a lot of times to get the erroneous situation.
I haven't tried to locate the JSON files involved, though.

**Comment by Marcos6226** [comment] 2022-08-28 20:15
> [...] I haven't tried to locate the JSON files involved, though.

Yeah, trying to find a specific place in the immense ocean of mapgen files is sure a pain in the ass.

**Comment by PatrikLundell** [comment] 2022-08-29 08:30
I've mustered some energy to go searching, and I think I've found the reason:
DinoMod overrides basement_lab_stairs.json, specifically basement_hidden_lab_stairs, and, for whatever reason, uses '6' rather than '!' for the card reader, with the terrain section specifying '6' rather than '!' to identify the reader. Unfortunately, the lab_palette is unchanged, and it defines '6' as being f_console, resulting in both a reader and a console being defined for that position (which is what we see).

Thus, this is a DinoMod specific bug that presumably (I'm not going to try, leaving that for those who maintain that mod) can be fixed by changing the DinoMod override to use '!' instead of '6' like the base game version does. I guess the reason for the override is to be able to place a mod specific monster on the map.
Obviously, the person doing the bug fix ought to look for similar bugs in related overriding files.

**Closed** 2022-09-11 07:23 UTC
Labels: Good First Issue, (S2 - Confirmed), [JSON], Map / Mapgen, Fields / Furniture / Terrain / Traps, Mods: Dinomod

**Comment by PatrikLundell** [comment] 2022-09-11 07:35
@ZhilkinSerg & @LyleSY : Does this really gets fixed by #60906?
Removing the basement will cause it not to appear and cause trouble for new players, but won't the removal cause issues for those who already have the basement as there's no longer any JSON definition for it?
If that's correct, the full solution should involve correcting the broken basement and move it to an obsolete sub directory/file so it can still be accessed in a corrected fashion by games that have generated it.
