### ISSUE TITLE
Tin can bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40729] opened 2020-05-21 02:26 UTC
Cant stash small and medium tin cans, they require you to spill contents first.
Large tin cans work fine.

![small tin](https://user-images.githubusercontent.com/62628815/82516409-fef5b200-9b5d-11ea-8d38-4dcd22b2bfe8.png)

![medium tin](https://user-images.githubusercontent.com/62628815/82516418-04eb9300-9b5e-11ea-8b01-6af0654823ea.png)

![large tin in inventory](https://user-images.githubusercontent.com/62628815/82516398-f3a28680-9b5d-11ea-9b31-a9241ea7c909.png)

Build: 10682

**Comment by buildfailedforallplatforms** [comment] 2020-05-21 02:28
Also beer cans

![beer can](https://user-images.githubusercontent.com/62628815/82516610-93f8ab00-9b5e-11ea-88c6-ee44c82c8973.png)

**Comment by KorGgenT** [comment] 2020-05-22 19:44
Duplicate of #40127

**Closed by KorGgenT** 2020-05-22 19:44 UTC
