### ISSUE TITLE
[cmake] FindCurses.cmake ignores CURSES_NEED_WIDE , can't compile with ncursesw

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#39053] opened 2020-03-27 08:07 UTC
Until now I didn't use the provided Makefile but generated it with cmake. Building TILES version worked just fine, but when I tried building CURSES version, I noticed it is linked with libncurses.so , instead of libncursesw.so  

There is a placeholder variable in CMakeLists.txt (CURSES_NEED_WIDE), but later on it is ignored in CMakeModules/FindCurses.cmake

**Comment by Jookia** [comment] 2020-04-09 06:13
I accidentally reproduced this in #39361 where it compiled fine but broke at runtime. This is because CMAKE_MODULE_PATH prefers the FindCurses shipped with the source code instead of the system-wide FindCurses which works fine. FindCurses should be updated to search for ncursesw now that the game depends on it.

**Comment by rumly111** [comment] 2020-04-09 07:57
> I accidentally reproduced this in #39361 where it compiled fine but broke at runtime. This is because CMAKE_MODULE_PATH prefers the FindCurses shipped with the source code instead of the system-wide FindCurses which works fine. FindCurses should be updated to search for ncursesw now that the game depends on it.

I looked into my /usr/share/cmake-3.5/Modules/FindCurses.cmake , but there is no ncursesw in it. So we can't depend on it.

**Comment by Jookia** [comment] 2020-04-09 08:05
Maybe the latest CMake FindCurses should be copied to this tree.
I'm unsure how to test it with older CMake versions or verify it works
with CMake 3.1 which is what CMakeLists.txt specifies it though.

**Comment by rumly111** [comment] 2020-04-09 08:11
> Maybe the latest CMake FindCurses should be copied to this tree. I'm unsure how to test it with older CMake versions or verify it works with CMake 3.1 which is what CMakeLists.txt specifies it though.

Maybe try installing Ubuntu 14.04 in a virtual machine or docker? I use Ubuntu 16.04, and it comes with CMake 3.5 . I wonder if simply copying can be a solution.

**Comment by Jookia** [comment] 2020-04-09 08:30
Simply copying it and a dependency worked on my machine on Debian 10.
I could do this as a WIP PR and if someone with a Ubuntu 14.04 container
setup wants to test it. I don't have a setup that can do containers at
the moment.

**Comment by anothersimulacrum** [comment] 2020-06-08 16:48
This means that people can't use curses when building in certain ways, this should be fixed.

**Comment by kevingranade** [comment] 2020-07-21 12:19
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/strange-text-troubles/24209/5

**Closed** 2022-02-04 00:08 UTC
Labels: <Bug>, (S2 - Confirmed), Code: Build
