### ISSUE TITLE
Wind mills produce huge amounts of flour

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#68826] opened 2023-10-23 08:37 UTC
### Describe the bug

I used a {wind mill} to process barley. When I executed the "Remove products from mill" action.
The game stopped responding, but did not crash. After a while, it started running on its own and refused my inputs, until about 14 hours of in-game time had passed. During this time, nearby creatures were moving freely, but my character could not be controlled.

My character was forced to work from 02:00 to 16:00, during which I couldn't issue any commands. Therefore, my character couldn’t stop, rest, or eat. If threatened by enemies, he couldn’t fight back either.

There was also an auto-save which prevents me from loading to an earlier point. At 16:15, the work finished, and I obtained (48,600) flour [4096] from processing 80 barleys (the actual number might be higher as nearby animals were active and ate some of them).

### Attach save file

[帕洛阿尔托-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13067929/-trimmed.tar.gz)

### Steps to reproduce

Place 80 barleys in the wind mill
Start processing
Wait for 6 hours
Execute "Remove products from mill" action

### Expected behavior

Produce a reasonable amount of flour.

### Screenshots

<img width="320" alt="bug_fresh" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/1281487/f05a6750-73a5-4453-afde-691add478b61">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 446e59e [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    神话武术 [MMA]
]

Everything was normal in earlier versions (such as cdda-windows-tiles-x64-msvc-2023-09-26-1337). I encountered this problem in the two versions that followed.

cdda-windows-tiles-x64-2023-10-20-1323 ee51041
cdda-windows-tiles-x64-2023-10-23-0451 446e59e

**Comment by RenechCDDA** [comment] 2023-10-23 10:36
Duplicate of #68701

**Closed by RenechCDDA** 2023-10-23 10:36 UTC
Labels: (S1 - Need confirmation)
