### ISSUE TITLE
Sensory Dulling CBM with Autodoc causes Addiction

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#37632] opened 2020-02-01 22:43 UTC
# Describe the bug

My character has withdrawl after installing a few CBMS. I didn't take any drugs.

# Steps To Reproduce

1. Have Sensory Dulling Installed
2. Install a few other bionics
3. Be addicted, and then get withdrawal.

# Expected behavior

You dont get an addiction or withdrawal.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10802-g072ff2f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

**Comment by Fris0uman** [comment] 2020-02-01 23:38
I can't reproduce this, and I don't see anything in the code that would give addiction from using the sensory dulling CBM.

**Comment by GGgatherer** [comment] 2020-02-02 08:06
When I was fighting mi-gos I've found myself affected by painkillers. Never used any but had Sensory Dulling on all the time. I suspect Sensory Dulling works under the hood by pumping you full of virtual painkillers, and something happened in latest builds so they now can cause addiction.

**Comment by Orange01gaming** [comment] 2020-02-02 08:07
Oh it might be the adderall my character was also taking during the
operation.

**Comment by Night-Pryanik** [comment] 2020-02-02 14:39
Closing then?

**Comment by Orange01gaming** [comment] 2020-02-02 18:04
Yeah

**Closed** 2020-02-02 20:42 UTC
