### ISSUE TITLE
WorldGen- using a random Initial Day DOES advance rot and evolution

### ISSUE THREAD

**Issue by OneThousandResets** [CleverRaven/Cataclysm-DDA#49526] opened 2021-07-02 12:33 UTC
At worldgen, using the value Initial Day -1 (random initial day) and getting a late winter day creates a world where perishable food is already rotten and zombies are found well into evolution, **even if Spawn Delay is set to zero** (The cataclysm takes place the same day the story begins)

![cataSpawnDelay Bug](https://user-images.githubusercontent.com/86806985/124274879-19ac9f80-db42-11eb-8f7b-213e71ce6f52.png)

build type: windows-tiles-x64
build number: 2021-06-30-1605
commit sha: 5861984305ed72f020673f8baefd1273941ed513
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/5861984305ed72f020673f8baefd1273941ed513

Godspeed

**Comment by Hirmuolio** [comment] 2021-07-02 14:14
#47372 should fix it.

IIRC the problem is that with random start day the start of game and start of cataclysm will each roll their own random dates separately.

**Comment by actual-nh** [comment] 2021-08-01 02:20
Please check if this is now fixed (by #47372).

**Closed** 2021-09-11 13:52 UTC
Labels: (S1 - Need confirmation), Spawn, Time / Turns / Duration / Date
