### ISSUE TITLE
Bow Hunter spawns with two hats instead of one

### ISSUE THREAD

**Issue by TheLightTwist** [CleverRaven/Cataclysm-DDA#53257] opened 2021-12-07 13:54 UTC
### Describe the bug

When I'm starting with Bow Hunter, I see in cloth menu that character wearing two hats instead of one

### Steps to reproduce

1) Create a world;
2) Make character as Bow Hunter;
3) See the bug.

### Expected behavior

Well, he should spawn with only one hat, I guess.

### Versions and configuration

OS: Arch Linux with kernel 5.15.5-zen1-1-zen x64
Game Version: 0.F.2-1
Graphics: Tiles
Ingame Language: Russian
Mods: Alternative Map Symbols, Blaze Industries

**Comment by Lamberthassel** [comment] 2021-12-07 16:07
I cannot reproduce the bug locally. Could you attach the screenshot, please?

**Comment by TheLightTwist** [comment] 2021-12-07 16:40
> I cannot reproduce the bug locally. Could you attach the screenshot please?

![image](https://user-images.githubusercontent.com/63810245/145069743-bf344e66-9e4d-4cc9-a2dc-19151c167964.png)
Created new world and new character, and even didn't enabled any mods

**Comment by Lamberthassel** [comment] 2021-12-07 16:45
Ah, you took a wool allergy trait, aren't you?

**Comment by TheLightTwist** [comment] 2021-12-07 16:46
> Ah, you took a wool allergy trait, aren't you?

Yep

**Comment by Lamberthassel** [comment] 2021-12-07 16:56
> Yep. But that's still, like, a bug?

It looks like it is a bug, I've just created a PR to fix it so hopefully, it will be fixed soon.

**Closed** 2021-12-09 06:46 UTC
Labels: <Bug>, (S2 - Confirmed), Mutations / Traits / Professions/ Hobbies, Character / World Generation
