### ISSUE TITLE
Make following companions to use food and water when available nearby on tiles.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#20729] opened 2017-03-29 09:03 UTC
It's tiresome to micro-manage 6+ followers with food and water via inventory. Make them use liquids and food when on tiles nearby via option or dialogue.

**Comment by Chezzo** [comment] 2017-03-29 16:37
I let my npc followers pick up what they want and that makes them use water and food correctly. You can even do it when in a grocery and turn it off when you leave if you like your long strings.

**Comment by 1skandar** [comment] 2017-03-30 02:22
That said, an option for "picking up stuff to satisfy needs" would be a nice feature. Semi autonomy to pick up food and water as needed, bandages and such if they are injured, and ammo for their weapons without turning them fully loose  to loot your supplies would go a long way to make NPC followers a lot less of a hassle.

**Comment by Coolthulhu** [comment] 2017-03-30 10:36
The problem is, I'd have to redesign the NPC pickup feature for that.
I'd like to do it eventually, but it will have to wait because it's big.
For example, NPCs scanning nearby area for items take a looooong time (in CPU time) because they scan every single thing in their view in radius 6 distance.

**Comment by Parahacker** [comment] 2017-04-02 04:22
How about adding a 'pick up food' rules preset to the pickup rules? Does using the custom pickup rules option trigger the cpu load you're talking about? Is it possible to use a more limited list than just 'food/water' to apply to npc's that would save on load, or would that not really matter?

NPC's already scan and pick up junk if allowed to and it doesn't seem to slow things down much, so how would adding a blacklist/whitelist as per the pickup rules change that?

Sorry if these questions seem ignorant :/

**Comment by Parahacker** [comment] 2017-04-02 04:24
For that matter, I'd prefer it if NPC's didn't gobble up all the candy nearby, since it doesn't feed them much and I use that stuff for morale during study sessions. So maybe a couple different presets, like 'eats anything', 'eats only filling foodstuffs', 'sweet tooth/carnivore/vegan' etc. would be cool.

**Comment by Coolthulhu** [comment] 2017-04-02 04:33
> How about adding a 'pick up food' rules preset to the pickup rules?

I think that would be doable. The problem would be writing something like "pick up food only if hungry" or "don't actually pick up food, just eat" so that they don't grab all nearby food and then have no space for drinks etc.

> NPC's already scan and pick up junk if allowed to and it doesn't seem to slow things down much, so how would adding a blacklist/whitelist as per the pickup rules change that?

It's the black/white lists which slow things down. Each item in range needs to be matched against those.
Fixing that won't be easy, but I'll need to do it some day.

**Comment by 1skandar** [comment] 2017-04-02 06:46
Hmm, could you limit how much they pick up? As in, only 2 food items and 1 drink to that preset? That way they'll always keep some food on them, but won't grab everything in sight.

**Comment by AMurkin** [comment] 2017-04-02 10:08
May be useful adding flag to zones, which will forbid companions to pikup.

**Comment by jzambo** [comment] 2017-07-02 12:50
Sorry, I referenced this issue in another by mistake and it seems to persist after correction.

**Comment by Night-Pryanik** [comment] 2018-07-22 15:09
Closing as per lack of discussion.

**Closed by Night-Pryanik** 2018-07-22 15:09 UTC
Labels: <Enhancement / Feature>, <Suggestion / Discussion>, NPC
