### ISSUE TITLE
Character sorts lab as if there are destination zones

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53906] opened 2021-12-30 22:35 UTC
### Describe the bug

I lost my RM232 somewhere in or around one of those giant labs with the red carpet, and in an attempt to find it I defined a massive "Loot: Unsorted" zone over most of it, and a custom zone with the filter "RM232".

To my surprise, my character started moving a bunch of the lab junk around, picking up and dropping lye, ID cards and other random things, both zombie loot and stuff spawned in the lab, putting it in seemingly random places, including various spots on the floor.

### Steps to reproduce

1. Define a "Loot: Unsorted" zone in one of these labs
2. "Sort out loot"

### Expected behavior

Only items with user-defined destination zones should be moved.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/147792095-82773549-c9f3-4e06-8668-3dc5f94739fb.png)
![image](https://user-images.githubusercontent.com/5107449/147792032-aacd8a83-428c-42a8-91c4-b9b77d38bb92.png)
![image](https://user-images.githubusercontent.com/5107449/147792232-00859371-c567-4414-9c31-be3cce2462f5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d6fecb3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Terrorforge** [comment] 2021-12-30 22:37
Actually, I think what she's doing is emptying every container? Which, hmm.

**Comment by GoLoT** [comment] 2021-12-31 01:48
@bombasticSlacks could it be a corner case from #53346? It sounds like the contents are being unloaded without checking if there is a target zone for them first.

**Comment by bombasticSlacks** [comment] 2021-12-31 02:09
Everything should be getting dumped that is the intended new default behavior of #53346. 

If they are moving stuff around after unloading it (without a destination) that is incorrect.

Regrettably someone needs to add in the ability to configure an unsorted zone to have unloading be optional for the use case of "find a needle in a haystack".

**Comment by GoLoT** [comment] 2021-12-31 02:53
Maybe as a new action in the O menu. Rename the current one as "Sort and empty containers" and add a new "Sort only" action with the old behavior. I haven't looked at the code but it should be possible to only dump items that have a target zone defined, that way the "sort only" action can still be used to find items in containers.

**Comment by bombasticSlacks** [comment] 2021-12-31 03:56
I think that does need to be added but 2 things to keep in mind. 

1. Currently things that have a destination zone are not dumped. So as an example if you have a filter for first aid kits they would be moved without being dumped. However if you didn't you dump the contents since their might be meds or something inside you want/do filter for.

2. The desire is for looking for stuff to take your character time, so to get rid of situations where you have x-ray vision. So even if such an option is added keep in mind you're character will still be taking the time to look through the containers even if they aren't dumping them. 

I guess an additional option could be added for "shallow search" where you don't consider containers at all. However it would really only be useful in this situation where you've dropped an item.

**Comment by Terrorforge** [comment] 2021-12-31 10:02
> If they are moving stuff around after unloading it (without a destination) that is incorrect.

I don't think so, seems she was just dumping things on the spot. I was just confused by the movement and the log messages saying she "put the blank on the blank"

**Comment by bombasticSlacks** [comment] 2021-12-31 12:00
Okay. I'm not saying your use case isn't valid either! Just explaining where things are currently.

**Comment by Terrorforge** [comment] 2021-12-31 14:40
Honestly I didn't even expect it to work, I mostly reported this because I thought someone had accidentally given the lab invisible loot zones. By the time I remembered you implemented emptying containers, it was late and couldn't decide if I still considered this a bug or not so I just left a comment and went to sleep.

But some kind of "sort without emptying" option would solve this, and would also have other use cases. E.g. I tend to implement sorting zones piecemeal, and I'd be a little miffed if I just wanted to pull all the guns out of my loot pile and ended up accidentally unpacking all my MREs

**Comment by bombasticSlacks** [comment] 2021-12-31 14:55
fwiw sealed items are ignored but I do get your point

**Comment by Maleclypse** [comment] 2022-01-03 05:00
I'm going to close this because I think it's not a bug and if there is a change desired I'm not clear on what it should be.  Let me know if I need to reopen this and label it.

**Closed by Maleclypse** 2022-01-03 05:00 UTC
