### ISSUE TITLE
milspec turrets and deafness

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19181] opened 2016-11-05 18:50 UTC
Version: 0.C-19534-gec2b8d9 (tiles)
Build: 5839
OS: Windows 7 Professional x64 SP1

Savegame here:
https://mega.nz/#!RkJn2AxR!nWoCJiw9RQhhgyzlai_kiP_aoht1ZqfHTiXjcE5BNT8
mods.json says:
[
    "ew_pack",
    "Medieval_Stuff",
    "makeshift",
    "More_Survival_Tools",
    "boats",
    "deoxymod",
    "blazemod",
    "Tanks",
    "novitamins",
    "StatsThroughSkills"
]

Load the game, remove ear plugs, step out of the car, stand in front of the car, and become deaf.

I'm not sure if the milspec turrets are shooting rockets or if it there's multiple high explosives going off in the military outpost.

I'm almost half a screen away and I become deaf due to the multiple explosions taking place southwest of my position. The sound damage in this case seems to be a bit over the top.

<a href='https://postimg.org/image/4gobsdj8d/' target='_blank'><img src='https://s6.postimg.org/43wxm70yp/Deaf_1.png' border='0' alt='Deaf 1'/><br />

**Comment by Leland** [comment] 2017-05-24 14:50
Can someone check if this happens on a vanilla game? E.g. spawn a milspec turret and see how much noise it actually produces. They only use a [M4A1](https://github.com/CleverRaven/Cataclysm-DDA/blob/67668987fee36729cac0c24d9d7c99e8a29063a8/tools/format/examples/monster.json#L61) so the noise shouldn't be that crazy.

**Comment by Chezzo** [comment] 2017-05-24 16:11
I threw a smoke grenade, spawned a milspec turret, spawned 8 zombies to surround it, made sure I was next to them, hit 5, and all it did make my ears ring. Spawning one zombie next to it does not make my ears ring.

**Comment by Leland** [comment] 2017-05-24 16:17
I have a feeling that @Nhatorama's specific issue was due to other factors – there are many explosions taking place in that screenshot. @Chezzo the difference in sound volume you experienced _is_ strange, but definitely not to the degree of what OP was saying. Feel free to make another issue for that discrepancy if you want – closing this one.

Also, for future people: _please_ provide a savefile if you encounter this! These things can be difficult to reproduce.

**Closed by Leland** 2017-05-24 16:17 UTC
Labels: Bug, Confirmation Needed, Other

**Comment by Chezzo** [comment] 2017-05-24 16:25
(They did provide a savefile.) 

> Savegame here:
https://mega.nz/#!RkJn2AxR!nWoCJiw9RQhhgyzlai_kiP_aoht1ZqfHTiXjcE5BNT8
