### ISSUE TITLE
Anomalous Artifact Report being too anomalous

### ISSUE THREAD

**Issue by Chroniclerope** [CleverRaven/Cataclysm-DDA#48184] opened 2021-03-22 18:47 UTC
# Bug Description

Saving and reloading with the artifact report in inventory causes a pocket size exception, spawns artifact on ground.

# Steps To Reproduce

1. Acquire report
2. Place it in a small pocket
3. Save and Quit
4. Reload save
5. Artifact has spawned on the ground

# Expected behavior

Anomalous reports to not be anomalies themselves.

# Screenshots

![image](https://user-images.githubusercontent.com/81186721/112041294-9c25cc00-8b1c-11eb-8ad2-33406bc9bbcc.png)
![image](https://user-images.githubusercontent.com/81186721/112041426-c6778980-8b1c-11eb-907c-14645accb541.png)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-10003-g48f45e8
 - Graphics version: Ultica
 - Ingame language: English
 - Mods loaded: [dda, Disabel NPC Needs, Bionic PRofessions, Blaze industries, C.R.I.T., DinoMod, Graphical Overmap]
 

# Additional context
 DEBUG    : error: item art_spiral cannot fit into pocket while loading: item too big

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 335

**Comment by hexagonrecursion** [comment] 2021-08-12 12:42
I can reproduce this bug. I saved with Anomalous Artifact Report in my hands and it turned into a winding, flexible rod when I loaded the save. Could this be caused by migration code?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: cb86201 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

This code is suspect:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a5362dfba2cd33aed2cf3f65c0f075c1ecaf79a/src/savegame_json.cpp#L2679-L2696
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a5362dfba2cd33aed2cf3f65c0f075c1ecaf79a/src/savegame_json.cpp#L2709-L2719

**Comment by RenechCDDA** [comment] 2023-11-15 11:14
Appears to have been resolved by #63975

**Closed by RenechCDDA** 2023-11-15 11:14 UTC
Labels: <Bug>, Spawn, <Exploit>, Artifacts
