### ISSUE TITLE
Timed Recipies mature based on the date created. For persistent worlds, this leads to insanity.

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#14812] opened 2016-01-12 09:09 UTC
Crops and most timed crafting in cataclysm matures on a specific date from when it is set up. This can lead to some insane occurrences, such as plants who don't mature for 5 game years, etc.

Reproduction:
1. Create a character, Debug to two years.
2. Plant some crops, tan some hide and prepare some whiskey to brew.
3. Sacrifice yourself to the horde.
4. Create a new character. Settle near the items.
5. Wait.(The tanned hide will never mature until after 2 years and so on days.)

Solution:
Place a built in sanity check when the item is loaded. Any timer item would have a time to create in the recipe. If over that, then the item is adjusted to a more sane time scale.

**Comment by SeanMirrsen** [comment] 2016-01-12 12:35
I'm not sure it's fair to classify it as a bug, since you're using the debug console to produce the effects, and in absence of proper time-travel tracking the game does its best to actually keep track of when a given item will have been done.

However, if the same happens with successive characters, it might lead to confusion, despite technically being correct. Maybe a better solution would be to advance the world clock instead of forcing the characters to start at the same world time, in successive playthroughs.

**Comment by BevapDin** [comment] 2016-01-12 13:32
This came up before, it's a duplicate of #11700, see explanation there.

**Comment by SeanMirrsen** [comment] 2016-01-12 14:36
Wouldn't it make more sense to comment on the issue here? Or are all commented-on issues visible to the active developers?

Anyways, why not simply do the Dwarf Fortress thing and keep the world going between characters, instead of rewinding time and creating temporal paradoxes? The world state is constantly saved anyway. Make every successive character start later in the world. Sure, worlds tend to deteriorate much quicker in CDDA than in DF, but then again worldgen doesn't take ages in CDDA either.

**Comment by Coolthulhu** [comment] 2016-01-12 14:48
> Anyways, why not simply do the Dwarf Fortress thing and keep the world going between characters, instead of rewinding time and creating temporal paradoxes?

Do we still have that shared world thing? It would make the whole thing impossible.
And even disregarding shared world, consider 2 characters played on the same world:
* Character A saves game in winter surrounded by food
* Character B exists for a season and saves the game
* Character A "wakes up" in spring or summer surrounded by rotten food, regardless of whether B got anywhere near A's base or not

**Comment by SeanMirrsen** [comment] 2016-01-12 14:50
The current system of casual time-travel doesn't make any more sense than that, though.

**Comment by Coolthulhu** [comment] 2016-01-12 14:56
Current system scrambles local results but leaves global ones unaffected.
"Summed time" would advance everything.

The most important value affected would be zombie evolution.

**Comment by BevapDin** [comment] 2016-01-12 15:01
> Wouldn't it make more sense to comment on the issue here? Or are all commented-on issues visible to the active developers?

All issues are visible all everyone, as far as I know.

**Comment by chaosvolt** [comment] 2016-01-12 17:32
I was almost assuming this to be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/14675 nstead. But instead this seems to be legitimate time fuckery, not merely the illusion of it. >.>

**Comment by SeanMirrsen** [comment] 2016-01-12 17:46
>The most important value affected would be zombie evolution.

Which is not a problem. It would make *more* sense to have the world's zombie population retain its new "upgrades" between successive characters. As I said earlier, worlds may degrade faster in CDDA, but worldgen doesn't take any significant time, and since every world is effectively always "more of the same in every direction", procedurally generated on the fly as the player moves, deleting a world to start from scratch is not a big issue.

The big issue is handling simultaneous active characters, which I didn't think about, and which DF sidesteps by not having the option of more than one active character in a world. The problem of casual timetravel works both ways, because in the current system a "fresh" character could obtain things a "late" character can't (fresh meat from hunting non-zombie animals, as an example), and leave it for the "late" character to collect, thanks to the magic of casual timetravel.

The simultaneous-character issue could, possibly, be handled, but perhaps it doesn't need to? Characters left inactive would effectively end up "logged off", like you would in an MMO. So the character that ends up surrounded with rotted food after another character spent a few seasons loitering about elsewhere, *hasn't been eating or drinking during those few seasons*. There is, in effect, little net loss - the food would have rotted anyway, if it were not consumed by then, but the character would still be healthy and fed.

**Comment by kevingranade** [comment] 2016-01-12 22:06
So then you have a contradiction, the food has rotted, but the player
hasn't experienced the passage of time.
It would be more sensical to say we don't support multiple active
characters per world either, but we also don't forbid it. It would be
reasonable to say the same about successive characters in the same world,
it does and will lead to contradictions, but in practice it's usually fine.
If inconsistencies like that are a problem for you, don't play simultaneous
or successive games in the same world.
If someone wants to start their game with the clock rolled forward, there's
an option for that as well.
I could see a game mode where you control a settlement, with npcs
performing various actions while the active player is doing thibgs, and the
player switching control to a new character either at will or at death.
Other than something like that, I don't see any benefit to trying to
rationalize multiple character worlds.

**Comment by chaosvolt** [comment] 2016-01-12 22:11
I almost wish we had the option to distinguish between a game that has "started" in spring and *started* in a later season (the way it works now), and the option of the Cataclysm itself starting at a desired season.

But that would need more involved simulated events besides rot and monster evolution (NPC looting, conflicts between hostile factions of monsters/NPCs, etc).

But that would ALSO lead to new and exciting ways to cause time fuckery like this.

**Comment by LlubNek** [comment] 2016-01-12 23:26
> * Character A saves game in winter surrounded by food
> * Character B exists for a season and saves the game
> * Character A "wakes up" in spring or summer surrounded by rotten food, regardless of whether B got anywhere near A's base or not

I don't see a problem with this.  The world was active, so time advanced.  If you want to play the same world without affecting another player, recreate the world or copy the save folder, otherwise what you do __should__ affect other players.

**Comment by chaosvolt** [comment] 2016-01-13 02:49
Except for character A existing in stasis while character B was active. Even barring time fuckery, this is a state of affairs where inconsistent behavior is inevitable. :V

**Comment by ejseto** [comment] 2016-01-14 23:31
How about we set the start time for the world to the current turn each time the last surviving player in that world dies? We can at least remove this one particular inconsistency, even if we can't fundamentally remove them all.

**Comment by kevingranade** [comment] 2016-01-15 02:18
Someone can feel free to add that as an option in character creation, but
that's a terrible default, people are not going to expect successive games
in the same world to keep getting harder.

**Comment by SeanMirrsen** [comment] 2016-01-15 03:11
World creation, not character creation. It'd be a per-world setting.

**Comment by kevingranade** [comment] 2016-01-15 04:32
That doesn't make any sense, if you want it to keep happening you can just
keep selecting it, but if it's set on the world you can't change your mind.

**Comment by SeanMirrsen** [comment] 2016-01-15 04:59
...indeed. There is enough time-screwing going on as it is. Changing systems in-world is just going to be a clusterflump.
If you want to change your mind, you can make a new world.

**Comment by SeanMirrsen** [comment] 2016-01-15 06:26
It makes even more sense to have it per-world if you think of it as a difficulty setting. 

>Dynamic Time: If enabled, this world's time will continuously advance as long as any character in it is active. Subsequent characters will start where the previous ones left off. Food spoilage and monster evolutions will accumulate between playthroughs.

**Comment by kevingranade** [comment] 2016-01-15 08:31
I don't though, because it isn't.  It is literally, "do you want your next
character to start at the date when your previous character died?".  There
is no reason to force people to keep playing like that indefinitely just
because they wanted to do it once.
Also I have no interest in messing with spoilation time or monster
evolution to try and make things "consistent", it's a fools errand because
literally everything is inconsistent already.  The only mechanism I've come
up with to enforce consistency is to spawn new characters far enough away
from old characters that they can't interact until after the new
character's timeline has caught up.

**Comment by kevingranade** [comment] 2016-01-17 07:36
Feel free to continue the discussion on the forums, but as for the crop issue, it's more consistent the way it is now than the alternative where successively loading different characters causes items to age instantly.

**Closed by kevingranade** 2016-01-17 07:36 UTC
Labels: wontfix
