### ISSUE TITLE
Morale "Bad Tempered" is inconsistent after drinking purifier

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38611] opened 2020-03-07 04:47 UTC
# Describe the bug

Had the 'bad tempered' mutation. Drank some purifier, which removed it. The next turn, I got a backtrace with `Morale "Bad Tempered" is inconsistent.`

Besides from the error, everything else seems fine. My new morale *is* consistent with not having Bad Tempered any more.

# Steps To Reproduce

1. Have a character with Bad Tempered
1. Drink some purifier
1. Do any action.

# Expected behavior

No error thrown, because everything is fine.

# Versions and configuration

Game version is 6bb5b9dc81 with custom patches applied.

```
20:46:44.936 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.5 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.D-12918-gb6f3a3b7e5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
]
```

# Additional context

Backtrace:

```
    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    DebugLog(DebugLevel, DebugClass)
    ??:?
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    ??:?
    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
    ??:?
    player_morale::consistent_with(player_morale const&) const::$_4::operator()(player_morale const&, player_morale const&) const
    morale.cpp:?
    player_morale::consistent_with(player_morale const&) const
    ??:?
    Character::check_and_recover_morale()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325
    _start
    ??:?
Backtrace emission took 1 seconds.
src/morale.cpp:621 [auto player_morale::consistent_with(const player_morale &)::(anonymous class)::operator()(const player_morale &, const player_morale &) const] Morale "Bad Tempered" is inconsistent.
```

**Comment by jkraybill** [comment] 2020-03-08 04:50
FWIW, I could not repro this issue by using debug to mutate in "Bad Temper" and then drink purifier. I even tried changing the code so that it was running the morale consistency check every turn:

```
    //if( calendar::once_every( 9_turns ) ) {
        u.check_and_recover_morale();
    //}

```

So not sure here. I think from looking at the code it's possible that this only occurs if both the once per minute morale update AND the once-every-9-turn morale check happen in the turn directly following the purifier step? I mutated and purified about 30 times, so my test was not exhaustive. I suspect this is an issue that's just really hard to replicate so I'm going to leave this one to someone more familiar with this part of the code!

**Comment by pjf** [comment] 2020-03-08 04:59
Well gosh, I'm glad I have that stack backtrace as evidence I wasn't
entirely making it up. Thank you so much for the testing!

**Comment by jkraybill** [comment] 2020-03-09 04:03
This similar error was reported on Discord, seems related. No context for reproduction though.

![unknown](https://user-images.githubusercontent.com/1361701/76181974-2dc6e200-6217-11ea-895b-1b09128131df.png)

**Comment by jkraybill** [comment] 2020-03-09 06:12
Per @misterprimus on Discord, the "stylish is inconsistent" issue was encountered upon game start. I could not reproduce that with a new character with Stylish. Below is a template provided by @misterprimus that may help in reproduction.

[helicrash.template.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/4304894/helicrash.template.txt)

**Comment by molkero** [comment] 2020-03-09 14:59
Didn't get the error on game start, saving game and then loading gives me the error every time.

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 19.0.2; Codename: Kyria; 
- Game Version: 0.D-12997-gdfd736e7ea [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4307295/Test.zip)

**Comment by wapcaplet** [comment] 2020-03-09 22:48
I could not reproduce the error in 0.D-13003-gd59d380027 compiled today, either by creating a new character with the "Stylish" trait, or by saving and loading from the Test.zip save game provided by @molkero.

I've been reading and researching the related code - it originated in a commit back in 2016 that introduced the consistency-check, and a `check_and_recover_morale` to reset when an inconsistency is detected: https://github.com/CleverRaven/Cataclysm-DDA/commit/fb0a2a8e4182cb90b73c95e5cfffdff488d8d3df

So I guess the idea of the debugging message was to bring attention to the inconsistency while still allowing the game to recover. The explicit recovery handling suggests that the inconsistency is a "known problem" of sorts - but unfortunately it doesn't help me understand how it became inconsistent. @codemime was the author of this commit, so perhaps they can weigh in with some clues.

**Comment by molkero** [comment] 2020-03-17 17:45
@wapcaplet I can still reproduce in 0.D-13228-g9b06414479, new game with stylish. Doesn't happen before I save & quit no matter the time spent, after loading and spending a few seconds I get the error about morale::stylish being inconsistent.

**Comment by wapcaplet** [comment] 2020-03-22 23:02
I was finally able to reproduce the issue following the steps in #38951 

- Create a new character with the "Stylish" trait
- Save the game
- Load the game

Save game: [StylishSave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4366508/StylishSave.zip)

**Comment by kevingranade** [comment] 2020-03-23 05:58
Ok, well IDK about the drinking purifier case, but on game load, the stylish cache variable isn't set.  I thought I had traced through that code and it looked ok, but maybe not.  Once this warning is hit it's set though and everything is good from then on.

The simple fix is contrive to have the bool set on game load, the less simple fix is figure out why the existing mechanisms don't seem to be working.

**Comment by kevingranade** [comment] 2020-03-23 06:08
Ok after further digging, it looks like there was simply no mechanism for this, player::on_mutation_gain() was never called during save load to apply side effects of mutations, and it's possible it was never called on purifier use either.

**Comment by wapcaplet** [comment] 2020-03-27 03:02
This exact use case came up in my current game, but unfortunately it is from a few revisions *before* #38965 was merged, so I can't say whether it would have been fixed by it.

Anyway I was ready for it and screenshotted:

![image](https://user-images.githubusercontent.com/238395/77716972-f1301000-6fa4-11ea-8965-8ac194e5dd03.png)

Just like it says, I had "Bad Tempered", drank some purifier, lost "Bad Tempered" and immediately got the "inconsistent" message.

**Closed** 2020-04-14 05:09 UTC
Labels: <Bug>, Mechanics: Character / Player, Mutations / Traits / Professions
