### ISSUE TITLE
Torch disappears

### ISSUE THREAD

**Issue by AngularFruit** [CleverRaven/Cataclysm-DDA#48590] opened 2021-04-19 22:41 UTC
When a crafted torch is lit, it instantly disappears.

When you attempt to light a crafted wooden torch, it disappears from the game.

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. make a torch from pine boughs
2. Light the torch
3. Watch the torch poof out of existence.

# Expected behavior

The torch is lit and stays lit until it burns out or you extinguish it.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10395-g4525b4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    Generic Guns - UndeadPeople Tileset [Generic_GunsUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP]
]

**Comment by casswedson** [comment] 2021-04-19 22:55
Duplicate of #48464

**Closed** 2021-04-19 23:03 UTC
Labels: (S3 - Duplicate)
