### ISSUE TITLE
Smartphone doesn't give me statuses while in padded leather pants pockets

### ISSUE THREAD

**Issue by trytryty1** [CleverRaven/Cataclysm-DDA#69280] opened 2023-11-11 20:39 UTC
### Describe the bug

My smartphone will not tell me about the time, my calories, or nutrients while in the pockets of my padded leather pants. I can still activate it from the pants.

### Attach save file

Trivial to reproduce

### Steps to reproduce

1. Make a player wear padded leather pants
2. Put smartphone in pocket
3. Have no other phones/wallets in your inventory

### Expected behavior

I should be able to see time/calories.

### Versions and configuration

- OS: Windows 11
- Version: Newest experimental version
- Mods loaded: MoM, Bombastic Perks

**Comment by Termineitor244** [comment] 2023-11-11 21:03
/Duplicate of #69258, which is by itself a duplicate of #68075

**Closed** 2023-11-12 08:11 UTC
Labels: (S3 - Duplicate)
