### ISSUE TITLE
Dropping items into closed display case.

### ISSUE THREAD

**Issue by omegaGreeNya** [CleverRaven/Cataclysm-DDA#50112] opened 2021-07-21 12:23 UTC
### Describe the bug

**0.F Frank (Stable)**

Items can be thrown into closed display case (e.g. in case Zombie stand on it).
Also if something died while standing on display case, it will drop into display case.

### Steps To Reproduce

1.Lure Zombie (or another entity) on display case.
2.Kill it on this tile.
3.All loot would be dropped into display case

### Expected behavior

Items dropped on tile with display case, should be countain as on the floor. Same happens the you trying to drop items over cappacity of vehicle countainer, items would be dropped on the ground. And if you try to pick up something from that tile, you will encounter context menu with choose of kind of pick up -> from the container/ground.

### Screenshots

![image](https://user-images.githubusercontent.com/86734901/126487375-5f1c9bab-b188-4716-b782-9170b91b2f74.png)

### Versions and configuration

OS: Windows 8 x64
Game Version: bc28921
Graphics version: Tiles
Ingame language: Russian
Mods loaded: dda, no npc food, alt map key, StatsThroughSkills

**Comment by actual-nh** [comment] 2021-07-21 16:38
This is a known problem with the furniture implementation, IIRC.

**Comment by wapcaplet** [comment] 2022-01-16 05:52
Possible duplicate of #38379

**Comment by Night-Pryanik** [comment] 2022-02-07 13:31
Duplicate of #49312.

**Closed by Night-Pryanik** 2022-02-07 13:31 UTC
Labels: <Bug>, (S3 - Duplicate), Fields / Furniture / Terrain / Traps, Items: Containers
