### ISSUE TITLE
Due to a recent update of the sound engine certain noises seem to now have a high pitched whine to them with @'s soundpack

### ISSUE THREAD

**Issue by Alexalmighty502** [CleverRaven/Cataclysm-DDA#49642] opened 2021-07-06 19:55 UTC
CDDA Build: 2021-07-04-0559
Soundpack build: Latest as of 7/6/2021

Apparently, a few SDL libraries were apperently updated (Mark#9561 on discord said this) and due to this update, certain noises (in my case the wood/concrete footstep noise and gas engine car humm) now have a high-pitched "whine" to them.

# Steps To Reproduce

Play with @'s soundpack and do certain actions (see above for the affected noises in my case) and notice it has a high pitched "whine" to it

I guess that a change with those libraries messed with the "reverb(maybe?)" inadvertently breaking it

# Expected behavior

The sounds to play without the whine 

# Screenshots

N/A But here's a short video showing this issue
https://www.youtube.com/watch?v=OHZxzCxulaI

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ee1873d [64-bit]
- Graphics Version: Tiles
- Game Language: System language [ENG]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Animatronic Monsters - UndeadPeople Tileset [AnimatronicsUDP],
    C.R.I.T Expansion Mod [crt_expansion]
]

# Additional context

I created a bug report for the soundpack's GitHub too but because the soundpack itself hasn't been updated in quite a long time and due to the fact there was no change with the soundtrack between it working in pre O.F and it breaking post O.F I felt like it would be advisable to report it here as well

Soundchip: Realtek ALC1220 
Speaker Setup: 5.1

**Comment by Alexalmighty502** [comment] 2021-07-06 20:40
Updated with a snippet of video showing the most extreme example

**Comment by ZhilkinSerg** [comment] 2021-07-06 20:41
Duplicate of #48192

**Comment by hexagonrecursion** [comment] 2022-01-04 18:43
Since this is a duplicate the "Need confirmation" tag should probably be removed.

**Closed** 2022-01-04 19:04 UTC
Labels: (S3 - Duplicate), SDL: Tiles / Sound
