### ISSUE TITLE
Overmap pool error

### ISSUE THREAD

**Issue by Fearen-sm** [CleverRaven/Cataclysm-DDA#30290] opened 2019-05-07 03:55 UTC
Crush in Tileset version of the game when move close to in-world pool. This error starting to occur after Build #8915 - Mon May 6 16:52:51 2019 (UTC+0300). It can be specific only to my save, because world was generated week or two ago.

1. Go near the pool.

Versions and configuration:
 - OS: Windows 10
 - Game Version: 0.D-2633-g664be36
 - Graphics version: Tiles
 - Mods loaded: 
[
  "dda",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "hydroponics",
  "mutant_npcs",
  "more_locations",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "more_classes_scenarios",
  "StatsThroughSkills",
  "modular_turrets",
  "Salvaged_Robots"
]

Crush logs:

 DEBUG    : invalid overmap terrain id "pool_north"
 
 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 383

 DEBUG    : In overmap special "pool", terrain "pool_north" is invalid.
 
 FUNCTION : void overmap_special::check() const
 FILE     : src/overmap.cpp
 LINE     : 953

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2604-ge169df3
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5630B5[cataclysm-tiles.exe+0x1630B5]
    @0x563B82[cataclysm-tiles.exe+0x163B82]
    SMPEG_error+0x4B034@0xE515A0[cataclysm-tiles.exe+0xA515A0]
    _C_specific_handler+0x98@0x7FF963A77C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FF96645F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FF9663CD856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FF96645E70E[ntdll.dll+0x9E70E]
    @0xACC25A[cataclysm-tiles.exe+0x6CC25A]
    @0xAD56B6[cataclysm-tiles.exe+0x6D56B6]
    @0xAD611E[cataclysm-tiles.exe+0x6D611E]
    @0xADA602[cataclysm-tiles.exe+0x6DA602]
    @0xADA8D9[cataclysm-tiles.exe+0x6DA8D9]
    @0xADA6AF[cataclysm-tiles.exe+0x6DA6AF]
    @0xADA6ED[cataclysm-tiles.exe+0x6DA6ED]
    @0xADA6ED[cataclysm-tiles.exe+0x6DA6ED]
    @0xADAD90[cataclysm-tiles.exe+0x6DAD90]
    @0xAE7EB6[cataclysm-tiles.exe+0x6E7EB6]
    @0xAE9139[cataclysm-tiles.exe+0x6E9139]
    @0xAE937D[cataclysm-tiles.exe+0x6E937D]
    @0xAE95F2[cataclysm-tiles.exe+0x6E95F2]
    @0xB0BEEC[cataclysm-tiles.exe+0x70BEEC]
    @0xB0FC31[cataclysm-tiles.exe+0x70FC31]
    @0xD7FBE3[cataclysm-tiles.exe+0x97FBE3]
    @0xD43280[cataclysm-tiles.exe+0x943280]
    @0xD46D3A[cataclysm-tiles.exe+0x946D3A]
    @0x68B36B[cataclysm-tiles.exe+0x28B36B]
    IMG_LoadWEBP_RW+0x4FE268@0x1441678[cataclysm-tiles.exe+0x1041678]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF963944034[KERNEL32.DLL+0x14034]
    RtlUserThreadStart+0x21@0x7FF966433691[ntdll.dll+0x73691]

**Comment by Night-Pryanik** [comment] 2019-05-07 05:28
I think that's a duplicate of #30279.

**Closed by Night-Pryanik** 2019-05-07 05:28 UTC
