### ISSUE TITLE
On creating a vehicle welding rig the used tool for welding "makeshift welder" consumes itself

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25291] opened 2018-09-01 01:53 UTC
**Describe the bug**  
The makeshift welder which was used as the welding tool for the recipe used itself in the recipe. It´s leftover batteries where in the inventory alone by themselfes. One of the two makeshift welders which where prepared for the recipe was not touched and stayed in the adjacent cargo space.

I can´t tell if the makeshift lost it´s designated letter in inventory. The testing for the other bug juggled things around. But if a tool with a designated letter uses itself up, this would be like ultra annoying.

**To Reproduce**  
1. Have the ingredients for the vehicle welding rig ready. Use 2x makeshift welders readied up in a tile north of the character instead of 1x welder.
2. For the welding tool use a 3rd makeshift welder running on batteries.
3. Build the rig.

**Expected behavior**  
The makeshift welder used as tool stays in inventory with the leftover charge in it. The makeshift welders in the adjacent tiles are used for the recipe.

**Comment by Night-Pryanik** [comment] 2018-09-01 14:29
Duplicate of #18710.

**Closed by Night-Pryanik** 2018-09-01 14:29 UTC
