### ISSUE TITLE
Making NPC unequip clothing in a way that drops it creates "none" item

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23524] opened 2018-04-18 06:52 UTC
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Making companion NPC unequip equipped item through 'e'xamine - 'sort armor' makes the NPC unequip and possibly drop just the item in question.

### Actual behavior
NPC unequips/drop the item, but also drops "none" item. Attempts to pick up "none" crashes the game. Saving and loading the game deletes "none" 90% of the time. At times a debug message is shown:

	debug: did not found item none to remove it!
	function: item Character::i_rem(const item*)
	file: src/character.cpp
	line: 829

...which creates "none" item that can be picked up as well as replicates some default items NPC spawned with (NPC in question, despite having those items taken from it and stashed elsewhere, dropped "none" together with a few refillable lighters and packs of firecrackers it had in the beginning of the game).

### Steps to reproduce the behavior
Equip NPC with various items, disrobe the NPC later

**Comment by notafed** [comment] 2018-04-20 16:16
Can confirm. However, in my experience, doffing a storage item (backpack, jacket) from an npc doesn't drop a "none", it simply crashes the game.

I've only seen it drop the "none" item, when I removed a jacket or bag from my own character which would cause me to drop excess items normally. And sometimes it removes unrelated clothing which were already equipped (gloves, shirts, etc.).

**Comment by gastamper** [comment] 2018-04-21 11:07
I've seen it happen in my games but I normally don't have NPCs on.  Does cause a crash when messing with the 'none' objects too much.

**Comment by RadHazard** [comment] 2018-04-21 22:25
I've seen this as well.  I can also confirm that there's a crash bug in there somewhere as well, though I don't think it's tied to storage items.

I asked an NPC to remove a keffiyeh and the game immediately crashed.  After reloading the latest autosave and trying to get him to remove it again, it worked but created a None.  I got another crash later while trying to give the same NPC a long-sleeved shirt

**Comment by Zireael07** [comment] 2018-04-23 16:38
Possibly related/due to #23586

**Comment by RadHazard** [comment] 2018-05-05 18:07
After running Valgrind and digging through the code, I'm strongly suspecting #23242 to be the cause of both this and #23586.

It looks like the drop() function queues up an activity that also happens to take off the item. Previously, if the item was dropped due to lack of space, the code would bail immediately and let the drop function take care of it. The PR for 23242 changed that behavior so that it continues to the function and drops the item again.

**Comment by AMurkin** [comment] 2018-05-30 05:59
Can be closed after #23663?

**Comment by ZhilkinSerg** [comment] 2018-05-30 08:19
Fixed by #23663.

**Closed by ZhilkinSerg** 2018-05-30 08:19 UTC
Labels: (S2 - Confirmed), <Bug>, Items / Item Actions, NPC
