### ISSUE TITLE
Saw mon_pseudo_dormant_zombie in game (0.H)

### ISSUE THREAD

**Issue by MatthewTromp** [CleverRaven/Cataclysm-DDA#78097] opened 2024-11-23 18:09 UTC
### Describe the bug

I saw a zombie whose description read "Fake zombie used for spawning dormant zombies.  If you see this, open an issue on github." I am therefore opening an issue on github.

### Attach save file

[New Birdland-trimmed.tar.gz](https://github.com/user-attachments/files/17882079/New.Birdland-trimmed.tar.gz)

### Steps to reproduce

Two tiles south and one tile east of the player in the save there is one such zombie. 

### Expected behavior

I don't expect to see such zombies

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 0.H-398-ga7334d2533 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment] 2024-11-25 07:15
Duplicate of #78097

**Closed by RenechCDDA** 2024-11-25 07:15 UTC
Labels: (S1 - Need confirmation)
