### ISSUE TITLE
Armor UI needs update after unequipping item

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#22212] opened 2017-10-20 12:57 UTC
Game version:
0.C-24623-gb397f39 (tiles)

Operating system:
Win10

Tiles or curses:
Tiles

Mods active:
NONE

### Expected behavior
Blanket should disappear from armor UI after unequipping it.

### Actual behavior
Blanket doesn't disappear.

![2](https://user-images.githubusercontent.com/11627131/31821852-c59530ac-b5a6-11e7-9a66-45337ca785e4.PNG)

### Steps to reproduce the behavior

1. Make sure the item you want to unequip doesn't fit into your inventory
2. Open armor UI
3. Select item and unequip it
4. game warns you that your inventory is full and asks wether you want to drop it -> Yes
5. Item is dropped, cursor jumps to a different item, but the item you dropped is still visible in the armor UI

**Comment by Night-Pryanik** [comment] 2017-10-20 15:14
Duplicate of #21210.

**Closed by Night-Pryanik** 2017-10-20 15:14 UTC
Labels: Information / Interface, Inventory / AIM
