### ISSUE TITLE
Recurrence of #32060 "Taking items from broken/inaccessible location" in 0.E

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#39451] opened 2020-04-10 20:54 UTC
# Describe the bug
I'm getting the "Tried removing item from object which did not contain it" error in 0.E and subsequent experimental releases (though began in 0.E proper).  However, the character in question has not even encountered a vehicle - I suspect the cause may be destroyed display cases in the mall structure.  Error message now occurs about 4 times per in-game day at random.  The full message is as follows:
DEBUG: Tried removing item from object which did not contain it
FUNCTION: item visitable<T> ; ; remove_item(item&) [with T = item]
FILE: src/visitable.cpp
LINE: 528

# Steps To Reproduce

Only a suspicion here, but it may be the following:
1. Enter a mall
2. Smash a display case or allow an enemy to do so
3. Swipe item from case.

# Expected behavior

Vuvuzela music

# Screenshots

N/A

# Versions and configuration

 - OS: Win7 Pro SP1 x64
 - Game Version: 0.E-439-gdf00ef1
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC Needs, Crazy Cataclysm, Mythical Martial Arts, DinoMod, Graphical Overmap, sees-player icon retrodays, Fuji's Military Profession Pack, SpeedyDex, Stats Through Kills, Stats Through Skills

# Additional context

[log & save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4463390/log.save.zip)

 - Issue occurred while resting just prior to this save.  Since it's unpredictable it's hard to grab one beforehand.

**Comment by KorGgenT** [comment] 2020-04-11 05:20
possibly a duplicate of #39402

**Comment by Hirmuolio** [comment] 2020-04-11 08:40
Another trigger for this error message is if any item is removed from the map druing its processing.

For example when zombies revive and the corpse is removed.

**Comment by kevingranade** [comment] 2020-04-28 21:08
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/experimental-crashes-tried-removing-item-from-object-which-did-not-contain-it/23447/2

**Comment by Night-Pryanik** [comment] 2020-04-30 19:45
Closing as duplicate.

**Closed by Night-Pryanik** 2020-04-30 19:45 UTC
