### ISSUE TITLE
Gas Mask (100/100) Unload fails and leaves broken "none" item.

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#40308] opened 2020-05-07 21:08 UTC
DEBUG    : cannot determine reload cost as none is neither ammo or magazine

 FUNCTION : int player::item_reload_cost(const item&, const item&, int) const
 FILE     : src/player.cpp
 LINE     : 2860

# Steps To Reproduce
1. Take a Gas Mask (100/100) item
2. Unload it
3.get error message above
4. find "none" item in the "other" category in inventory

# Expected behavior

It should provide a gas mask filter cartridge with 100 charges.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by enaantd** [comment] 2020-05-07 21:24
can confirm, just had the same bug.

**Comment by ZhilkinSerg** [comment] 2020-05-07 21:45
Duplicate of #40158

**Closed by ZhilkinSerg** 2020-05-07 21:45 UTC
Labels: (S3 - Duplicate)
