### ISSUE TITLE
Turning car wrong telefrags enemies into car wall

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36659] opened 2020-01-03 01:21 UTC
If you turn a vehicle such that a tile which was previously empty becomes occupied by a enemy, the enemy remains in that tile. When the vehicle moves, they take damage from the frame. They are free to move out of the frame and into the inside of the car.

**Comment by Soup-de-Loop** [comment] 2020-01-03 02:10
This is an ancient issue and the only thing to alleviate it until the enormous and arduous task of reworking inside vs outside or reshaping vehicles occurs, is to double-wall your vehicle. This problem primarily occurs because of the gaps that appear when the vehicle is diagonal, and the monsters being able to transition through without colliding with a board. Besides that, low-speed collisions with enemies are also good to avoid, as is turning at high speeds.

**Comment by Fris0uman** [comment] 2020-01-03 08:46
Duplicate of #5684

**Comment by Unrepentant-Atheist** [comment] 2020-01-03 10:07
That's a "bug"? I though it was a feature of how this system was set up.

**Comment by 1n17** [comment] 2020-01-03 14:11
Wow, that is still a thing? Let me check old forks. I've found relatively sufficient crutch for that ages ago (at least monsters walking into angled car part, I suppose you could still 'telefrag' them inside by turning), try this out
```
--- a/src/monmove.cpp
+++ b/src/monmove.cpp
@@ -221,6 +221,16 @@ bool monster::can_move_to( const tripoint &p ) const
         }
     }
 
+    // guard for unitialized pos() in map::spawn_monsters_submap_group
+    if( position.z != -500 ) {
+        // prevent creatures going diagonally trough vehicle walls
+        const optional_vpart_position vp_from = g->m.veh_at( pos() );
+        const optional_vpart_position vp_to = g->m.veh_at( p );
+        if( ( !vp_to && vp_from && vp_from->is_inside() ) || ( !vp_from && vp_to && vp_to->is_inside() ) ) {
+            return false;
+        }
+    }
+
     return true;
 }
 
```

**Comment by Night-Pryanik** [comment] 2020-01-05 06:25
Closing as duplicate.

**Closed by Night-Pryanik** 2020-01-05 06:25 UTC
