### ISSUE TITLE
Overlapped overmaps?

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20429] opened 2017-03-03 12:47 UTC
I've run into two overlapped 2 story motels in build 6290. Didn't caught anything similar to this earlier. Could it be somthing in #20232?

<img width="730" alt="2storymotel" src="https://cloud.githubusercontent.com/assets/16213433/23551565/5602b658-0028-11e7-9b1d-c295c8a64f25.png">
<img width="730" alt="2storymotel_2" src="https://cloud.githubusercontent.com/assets/16213433/23551566/5604b7be-0028-11e7-83fe-046e4aad5072.png">

**Comment by ZhilkinSerg** [comment] 2017-03-04 12:06
School + 2 StoryMote

<img width="730" alt="school_motel" src="https://cloud.githubusercontent.com/assets/16213433/23578608/2711196a-00ec-11e7-9488-b0797119ce88.png">

**Comment by codemime** [comment] 2017-03-08 22:20
They really do overlap occasionally.

**Comment by Coolthulhu** [comment] 2017-04-11 22:11
Except the coords aren't at overmap edges.

I found something better: "land" location allows all terrains except road and river. Buildings are neither roads nor rivers.

**Comment by Coolthulhu** [comment] 2017-04-11 22:19
By the way, do we need the excluded special types at all? They are blocking my idea for optimization and I don't see much use for them - only blob pits and craters should really replace things.

**Comment by ZhilkinSerg** [comment] 2017-09-05 10:32
> I found something better: "land" location allows all terrains except road and river. Buildings are neither roads nor rivers.

So, there is no flag/property that tells location is occupied.

**Comment by codemime** [comment] 2018-02-24 09:36
> I found something better: "land" location allows all terrains except road and river. Buildings are neither roads nor rivers.

`"land"` now allows only: `"forest"`, `"forest_thick"`, `"forest_water"`, and `"field"`.

> By the way, do we need the excluded special types at all? They are blocking my idea for optimization and I don't see much use for them - only blob pits and craters should really replace things.

Prohibitions were removed in #22724.

The bug has probably gone by now (assuming this was the cause), but I'd leave this open for a short while, Justin Case.

**Comment by ZhilkinSerg** [comment] 2018-02-24 09:43
I can confirm I didn't see overlapped specials in a while.

**Comment by Leland** [comment] 2018-02-26 02:25
Closing

**Closed by Leland** 2018-02-26 02:25 UTC
Labels: Bug, Confirmation Needed, Mapgen
