### ISSUE TITLE
Autopickup doesn't pickup items from zombie corpses

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#56021] opened 2022-03-11 11:57 UTC
### Describe the bug

Autopickup fails to pickup items from killed zombies.
Zombie corpses are now containers that can only have items taken from them, logically this should mean that they are valid targets for autopickup as they only exist to be looted.

### Steps to reproduce

1. Set autopickup to any zombie dropped item
2. Walk past zombie corpses
3. Items are never picked up

### Expected behavior

Autopickup taking items from zombies. Not having to manually go over every single zombie with multiple button presses just to do myself what autopickup does.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 6ca3ef2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I realize that this might be "intended" behavior or lack of a feature, but it introduces so much user overhead in form of required button presses just to do an action that already has an automated system implemented in the game. I've found myself completely ignoring zombie dropped loot and just waiting for their corpses to despawn from rot just to avoid the tedium.

**Comment by NetSysFire** [comment] 2022-03-11 12:31
Duplicate of #53425. Make sure your game is updated to the latest experimental and re-open this issue if it still persists.

**Closed by NetSysFire** 2022-03-11 12:31 UTC

**Comment by Tommy-os** [comment] 2022-03-11 13:08
Whoops, turns out my launcher was throwing an error and didn't want to update.

Issue does not persist in latest experimental.
