### ISSUE TITLE
Batch Crafting Charcoal Water Purifier Seems Funky

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54087] opened 2022-01-06 05:58 UTC
### Describe the bug

I chose the recipe for 2x & it only gave me 1x. The resulting item had 150 charcoal in it but the recipe only called for 75 (per purifier). The disassembly option says it'll return a rag & jug but it consumed 2 jugs & 8 rags, I believe.

I did notice #50005 before posting this. Raising the charcoal cost to 150 for this recipe should have applied in 0.F-3, no?? The previous issue was a "0.F Backport Candidate" but IDK what that means.

Anyway, my issue seems to be that batch crafting eats resources scaled to the batch but only returns a single item.

### Steps to reproduce

1. Pay for the cow.
2. Do not receive the milk.
3. Do NOT pass "GO!"
4. DO NOT PROFIT!!!

### Expected behavior

I expected that charcoal water purifier level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by hexagonrecursion** [comment] 2022-01-06 07:19
I am sorry, but I could not reproduce this bug. Note that the two water purifiers might end up in different locations (e.g. one - in your hands, the other - under your feet)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment] 2022-01-06 11:07
If it is not reproducible on latest experimental it can be closed. We are unlikely to backport anything else to `0.F` and there will be no `0.F-4`.

**Comment by LeahLuong** [comment] 2022-01-06 17:47
My bad! I was tired & missed that the 2nd purifier fell thru the bottom of my vehicle. Then, I came on & made a tired bug report. I'll try to avoid doing that in the future.

The purifier disassembles for 1 jug & 4 rags. #50083 gave these purifiers a NO_UNLOAD tag & presumably raised the charcoal cost to 150; this work was supposedly done on Jul 21, prior to the release of 0.F-3. I'm still able to unload he purifier & the charcoal cost is only 75. Did this fix not make the cutoff for the latest stable release??

**Comment by ZhilkinSerg** [comment] 2022-01-06 17:55
Latest stable release is [0.F](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F) from July, 3rd. Anything merged to `master` branch after that date won't be included to `0.F` unless it was backported and included to one of point releases ([0.F-1](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-1), [0.F-2](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-2) or [0.F-3](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-3)).

**Comment by LeahLuong** [comment] 2022-01-06 18:20
Thanks for the explanation. I noticed actual-nh had made this a backport candidate but you removed that tag after the fix was completed. I'm curious as to why. Is backporting not a simple, automatic process of compiling the new code or does some1 have to do something more arduous??

**Closed** 2022-01-20 02:03 UTC
Labels: (S1 - Need confirmation), Crafting / Construction / Recipes
