### ISSUE TITLE
Hard crash when attempting to open advanced inventory

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#62587] opened 2022-12-05 17:30 UTC
### Describe the bug

Going along my business, i attempted to open the advanced inventory to move three piles of planks and nails.  Immediately the game crashed with a segmentation fault.

### Steps to reproduce

Unsure of exact steps.  Loading the recent save again, I followed the same steps but it didn't crash (steps: disassemble the 3 benches below the character, hit key for advanced inventory).

### Expected behavior

I expect the advanced inventory to open as normal.

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 11.3.1; Build: 20E241; 
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I am using an older build of Frank, and a recently downloaded UltiCa tileset (though I was using Moxotto at the time of the crash).

[Archive.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10156462/Archive.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10156463/save.zip)

**Comment by busterbogheart** [comment] 2022-12-05 17:37
Here's the system dialog that came up after Cataclysm quit:

[apple-crash.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/10156532/apple-crash.txt)

**Comment by andrei8l** [comment] 2022-12-05 17:43
Based on the crash log, this looks like a duplicate of #51348. Either way, I can't reproduce it with 6d064b002275b21df5f26f8ea76e6e9a527224e5, but it could be a MacOS-specific issue.

**Comment by TealcOneill** [comment] 2024-05-16 05:57
@GuardianDll This was is probably fixed by #62560. There's been no recent updates to this and searching through issues reveals no new issues on this subject.

**Closed** 2024-05-16 06:50 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation), Inventory / AIM / Zones
