### ISSUE TITLE
Inserting a liquid into a wielded container can bypass seals

### ISSUE THREAD

**Issue by TGWeaver** [CleverRaven/Cataclysm-DDA#43412] opened 2020-09-03 01:46 UTC
# Describe the bug
Wielding a watertight container (like a canteen or plastic bottle) will allow you to insert liquids -- even if that liquid is currently in a sealed container. You'll get a warning that you're spilling a liquid and may not be able to put it back.  If you choose to continue anyway, you'll move the liquid from the sealed container to the wielded one _without unsealing the original container._ You can use this to empty a soda can without even opening it.
If you then wield the empty sealed container, you can insert the liquid right back in, whereupon it will be preserved once more and no longer spoil. At no point will the container unseal.

# Steps To Reproduce
1. Spawn a new character.
2. Spawn an empty plastic bottle and (for example) a sealed aluminum can of cream soda.
3. Select the bottle and choose (i)nsert. Notice that the liquid cream soda is not listed, and can't be moved to the bottle.
4. Wield the empty plastic bottle.
5. Select the bottle, choose (i)nsert, Notice the liquid cream soda **is** listed now, and can be moved to the bottle.
6. Move the cream soda to the bottle. Confirm the warning. The bottle now contains the cream soda, but the empty aluminum can is still not opened.
7. Wield the empty but sealed can. Insert the cream soda back in. Alternately, insert anything else in. The seal remains intact.

# Expected behavior
Wielded and non-wielded containers that aren't flagged as open top should behave the same way when inserting items and fluids. In both cases, sealed fluids should not show up on the list of items to insert.

# Screenshots
![sealed can](https://user-images.githubusercontent.com/45330325/92061702-cca64400-ed4b-11ea-857a-e4e5953f2b38.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5555-gfe42c59 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [Dark Days Ahead [dda]

# Additional context
This may be a result of wielded containers reacting differently because of "open" containers which need to be wielded to safely contain liquids, as I can't imagine why else wielding a container changes the items it can access, but clearly this was not an intended side effect.

**Comment by wapcaplet** [comment] 2020-09-04 21:27
Confirmed in 0.E-5679-g446c750473 using steps in issue description.

Wielding an empty container (sealed can, tupperware with lid, or spillable bottle or bucket), I can `i`nsert liquids from sealed containers, and neither container will become unsealed in the process. I can transfer soda between sealed cans undetected, or even replace a sealed soda can with something more nefarious. Behold, the sealed aluminum can of vinegar:

![image](https://user-images.githubusercontent.com/238395/92286028-17969780-eec3-11ea-93d8-8151f17e6d16.png)

**Comment by aerrant** [comment] 2021-02-26 23:49
This issue no longer reproduces since Qrox specifically addressed containers unsealing with his PR #46520.

**Comment by wapcaplet** [comment] 2021-02-27 01:36
Confirmed fixed in 0.E-9857-gf777f179d0c

**Closed** 2021-02-27 01:36 UTC
Labels: (S2 - Confirmed), <Bug>, Items: Containers
