### ISSUE TITLE
Blazemod has duplicate Start Vehicle Construction command, causes failures

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#19160] opened 2016-11-04 21:18 UTC
Blazemod has a duplicate Start Vehicle Construction command in blaze_override.json that causes a duplicate stage to appear in SVC in-game. Trying to execute said command with a foldable-light frame results in an error about not having the proper ingredients in inventory, no vehicle appearing on the ground, but a dialog appearing to name it anyway.

Deleting the duplicate command from blaze_override.json enables the vehicle to be constructed properly, and the blazemod blob frames still appear as options for it, which seems to be a clean fix for the issue, unless theres' a reason for the override that isn't obvious.

**Comment by illi-kun** [comment] 2016-11-04 21:21
This is a duplicate of existing issue report.

**Comment by illi-kun** [comment] 2016-11-04 21:23
Closing as a duplicate of #18372.

**Closed by illi-kun** 2016-11-04 21:23 UTC
Labels: Bug, Duplicate, Mods
