### ISSUE TITLE
Construction: "Fill Pit With Soil" won't work due to trap

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#33882] opened 2019-09-08 02:22 UTC
# Describe the bug

You can't fill a pit with soil in the build menu since it counts as a trap, but a similar issue with pit traps was resolved with #31838, this one was probably unknown at the time.

# Steps To Reproduce

1. Make a player with any tools with 2 and upper digging quality.
2. Dig a deep pit.
3. Open Construction menu, go to the line "Fill Pit With Dirt"

# Expected behavior

Pit is filled and dirt is consumed.

# Versions and configuration

- OS: Windows 10
- Game Version: 0.D-7375-g1fbbe0a
- Graphics version: Tiles
- Mods loaded: DDA, Magiclysm, No Rail Stations, Bionic Slots, Disable NPC Needs, SpeedyDex, Stats Through Kills

# Additional context

- #32400 had the same issue, but for some reason the poster closed it before it could be fixed.
- You can activate a digging tool and fill the pit but it won't consume any soil.
- Constructing a Glass Pit works normally

**Comment by starytroll** [comment] 2019-09-08 14:03
I would like to add that in my case I can fill the pit with earth using action on shovel (and I think w/o soil items around, but not sure here), but I cannot do that using the construction panel (that uses the soil).

**Comment by Senteth** [comment] 2020-02-03 12:18
Just ran into this issue myself with the current version and looked up the construction recipe: 
(found in cdda\data\json\construction.json)

`  {
    "type": "construction",
    "id": "constr_fill_pot",
    "description": "Fill Pit With Dirt",
    "//": "Fills a deep pit with dirt.",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 0 ] ],
    "time": "40 m",
    "qualities": [ [ { "id": "DIG", "level": 1 } ] ],
    "components": [ [ [ "material_soil", 200 ] ] ],
    "pre_special": "check_empty",
    "pre_terrain": "t_pit",
    "post_terrain": "t_dirt"
  },`

After a little experimentation, I determined that the "pre_special": "check_empty", line was causing the issue. Removing it allows you to fill in pits. (tested it and I didn't notice any adverse effects when trying to build the construction with items inside the pit- they just get pushed aside)

I also upped the soil cost for filling in the pits since you typically get ~400 soil from digging them in the first place, so it'd make sense that you'd need just as much dirt in order to fill them again afterward: 

`  {
    "type": "construction",
    "id": "constr_fill_pot",
    "description": "Fill Pit With Dirt",
    "//": "Fills a deep pit with dirt.",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 0 ] ],
    "time": "40 m",
    "qualities": [ [ { "id": "DIG", "level": 1 } ] ],
    "components": [ [ [ "material_soil", 400 ] ] ],
    "pre_terrain": "t_pit",
    "post_terrain": "t_dirt"
  },`

Unfortunately I'm not sure how to submit the fix for merging with the game. (github confuses me)

**Comment by Night-Pryanik** [comment] 2021-04-11 03:07
Can't confirm on latest experimental as of April 11, 2021.  Dug a deep pit (`t_pit`) with a shovel, debug-spawned 200 soil and placed it nearby. Successfully filled the pit with the soil.
Closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-11 03:07 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Fields / Furniture / Terrain / Traps
