### ISSUE TITLE
Spider box bug

### ISSUE THREAD

**Issue by Edreym11** [CleverRaven/Cataclysm-DDA#37156] opened 2020-01-17 17:31 UTC
# Describe the bug

The artifact "spider box" it's not making any thread even after a week.

# Steps To Reproduce

1.Find the artifact.
2.Let time pass.
3.No changes on the quantity of thread.

# Expected behavior

Fabrication of new thread from the box like the description of the object implies.

# Versions and configuration

 - OS: Windows 10
 - Game Version: version 0.D-11335-gcd00378
 - Graphics version: Tiles
 - Mods loaded: dda, boats, magiclysm , vehicles additions pack , tanks and other vehicles ,folding parts pack , disable npc needs , roadheader and other mining vehicles, mutants npc's.

# Additional context

<!-- Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

**Comment by foulman** [comment] 2020-01-18 17:35
> 
> # Describe the bug
> 
> The artifact "spider box" it's not making any thread even after a week.
> # Steps To Reproduce
> 
> 1.Find the artifact.
> 2.Let time pass.
> 3.No changes on the quantity of thread.
> # Expected behavior
> 
> Fabrication of new thread from the box like the description of the object implies.
I just tested this, it works fine, it generates 1 thread per hour, and what I suspect is that your spider box is currently full. 
It holds 1000 thread, and you need to 'U'nload it to make room for more thread. The capacity is stated on the item description. 
Please check on this and get back to me.

**Comment by azraneth** [comment] 2020-01-18 17:35
Could not reproduce in the latest version.
- Game Version: 0.D-11440-g82a2eb2 [64-bit]

**Comment by Edreym11** [comment] 2020-01-19 22:29
I used lastest version and yeah now it works fine

**Comment by anothersimulacrum** [comment] 2020-01-19 22:35
Could you close this issue then?

**Closed** 2020-01-20 04:12 UTC
Labels: (S1 - Need confirmation), <Bug>, Artifacts, Mods: Magiclysm, [JSON]
