### ISSUE TITLE
[Suggestion] Remove the Zombie dancer easter egg / make it into a mod

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#15297] opened 2016-02-08 01:23 UTC
As the title states, remove the Zombie dancer easter egg or make it into a mod. There is a difference between facing a funny rare smoker bear and an army of invincible zombies that turns into hulks. Just no, who even thought it would make sense to be added to the game?

Edit: Also, I am aware of the "no joke-monsters" mod, but this really feels like one of the things that shouldn't be added to the game by default..

**Comment by Malkeus** [comment] 2016-02-08 02:23
There is a mod for this: no joke monsters mod. Run it on every world, you
won't miss anything it blacklists.

**Comment by kevingranade** [comment] 2016-02-08 03:50
Duplicate of #15246

**Closed by kevingranade** 2016-02-08 03:50 UTC
Labels: Duplicate

**Comment by harald921** [comment] 2016-02-09 20:17
@kevingranade This is in no way a duplicate of that. In absolutely no way apart from both being about the Zombie dancers.

@Malkeus If you actually read through what I said you'd see that I am well aware of that.

Jesus guys, you didn't even read through my suggestion.

**Comment by kevingranade** [comment] 2016-02-09 22:32
Yes I did, the only difference between this issue and that one is you have
a specific suggestion for what to do about it, the underlying issue seems
to be the same for both, which is, "I don't want zombie dancers appearing
in my game, or at least not very early".
Is there any way it helps to have two issues for this? I don't see one, but
I might be missing something.

**Comment by Malkeus** [comment] 2016-02-09 23:18
I read at and I fail to see the difference between blacklisting dancers and
making dancers a mod only monster. If you wish to only blacklist dancers,
the no joke monsters mod has everything you need to create a No Dancers
Mod.
