### ISSUE TITLE
Text does not display with latest updates

### ISSUE THREAD

**Issue by hafnhaf** [CleverRaven/Cataclysm-DDA#52089] opened 2021-10-04 02:38 UTC
### Describe the bug

The last series of updates causes the text not to display in game. I'm unable to see any text at all, though the game does run.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7275120/debug.log)

### Steps To Reproduce

Update to 71ec59b
Launch the game from the Launcher

### Expected behavior

Expected game to start as normal at the menu screen.

### Screenshots

![2021-10-03](https://user-images.githubusercontent.com/91858983/135785023-34d91b1a-d918-4648-b09a-f1bf5e9b9399.png)
![2021-10-03 (1)](https://user-images.githubusercontent.com/91858983/135785190-3b317322-197a-4d7e-9889-2473df915448.png)

### Versions and configuration

Windows 10 
English

Unable to get much more since no text is visible in game.

### Additional context

I did disable all the mods just in case and that did not solve the problem.

**Comment by TealcOneill** [comment] 2021-10-04 02:40
duplicate of #52046

**Closed** 2021-10-04 02:47 UTC
