### ISSUE TITLE
Canteen Refill Aberrant Behavior

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46091] opened 2020-12-17 04:07 UTC
# Describe the bug

Game errored, but didn't crash, while trying to refill my canteen.

```
22:56:35.359 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x6a21d6[cataclysm-tiles.exe+0x2a21d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x6a21d6),
    (libbacktrace: 0x6a21d6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6a2c16[cataclysm-tiles.exe+0x2a2c16]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x2f6@0x6a2c16),
    (libbacktrace: 0x6a2c16    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6a7960[cataclysm-tiles.exe+0x2a7960]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x50@0x6a7960),
    (libbacktrace: 0x6a7960    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x930328[cataclysm-tiles.exe+0x530328]), 
    (libbacktrace: ZN4item9fill_withERKS_i+0x408@0x930328),
    (libbacktrace: 0x930328    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x943120[cataclysm-tiles.exe+0x543120]), 
    (libbacktrace: ZN4item6reloadER9Character13item_locationi+0x750@0x943120),
    (libbacktrace: 0x943120    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x434007[cataclysm-tiles.exe+0x34007]), 
    (libbacktrace: ZN21reload_activity_actor6finishER15player_activityR9Character+0x127@0x434007),
    (libbacktrace: 0x434007    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0xed1d69[cataclysm-tiles.exe+0xad1d69]), 
    (libbacktrace: ZN15player_activity7do_turnER6player+0xdd9@0xed1d69),
    (libbacktrace: 0xed1d69    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x797818[cataclysm-tiles.exe+0x397818]), 
    (libbacktrace: ZN4game16process_activityEv+0x58@0x797818),
    (libbacktrace: 0x797818    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ec54a[cataclysm-tiles.exe+0x3ec54a]), 
    (libbacktrace: ZN4game7do_turnEv+0x30a@0x7ec54a),
    (libbacktrace: 0x7ec54a    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: IMG_LoadWEBP_RW+0x7c4a99@0x1b130f9[cataclysm-tiles.exe+0x17130f9]), 
    (libbacktrace: main+0x1239@0x1b130f9),
    (libbacktrace: 0x1b130f9    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #11
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #12
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffdb7187034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #13
    (dbghelp: RtlUserThreadStart+0x21@0x7ffdb8cdd0d1[ntdll.dll+0x4d0d1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/item.cpp:8784 [int item::fill_with(const item&, int)] tried to put an item (water_clean, amount 1) in a container (canteen) that cannot contain it
```

# Steps To Reproduce

1. Wear a plastic canteen with 5 units of clean water.
2. Attempt to (r)eload the canteen from a gallon jug of clean water, doesn't matter which.
3. Observe error.
4. Become sad.

# Expected behavior

I expected the game to pour one unit of clean water into the canteen, topping it off.

If I empty the canteen, I can refill it from 0 to 6 units from the same gallon jug.

# Screenshots

None applicable.

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

# Additional context

[Water Bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5706924/Water.Bug.zip)

**Comment by Svankensen** [comment] 2020-12-17 06:21
Was the water in the gallonjugs hot by chance? I've noticed similar but less dramatic errors while mixing hot or cold liquids.

**Comment by PaulBlay** [comment] 2020-12-17 08:01
I know this one, and it's not to do with temperature. 'clean water' that you make yourself by crafting (boiling or water purification tablets) has different flags applied than clean water generated in loot drops, found in maps, or made by using the FOODCO food station purification system.

I'm sure it's mentioned in a bug issue. I'm not sure said bug issue is very clear about what the problem was, the spurious flag thing turned up in the comments IIRC.

**Comment by ToxiClay** [comment] 2020-12-17 09:00
> Was the water in the gallonjugs hot by chance? I've noticed similar but less dramatic errors while mixing hot or cold liquids.

I eventually figured that one out when it cropped up, so thankfully I wasn't that derpy this time. :)

> [link snip]

Well, that is bizarre behavior. I don't think this is as it should be. I understand the technical limitations behind not mixing hot water with not-hot water, but clean water should be clean water. Maybe it's as simple as removing the references to uncrafting from certain things, like liquids.

**Comment by ToxiClay** [comment] 2020-12-17 17:20
So, I've found a change to item.cpp that should be allowing hot clean water and regular clean water to mix.

```
if( combine_liquid && has_temperature() && made_of_from_type( phase_id::LIQUID ) ) {

        //we can combine liquids of same type and different temperatures
        if( !equal_ignoring_elements( rhs.get_flags(), get_flags(),
        { flag_COLD, flag_FROZEN, flag_HOT } ) ) {
            return false;
        }
```

I think this check is missing a flag for "water has no particular temperature." Anyone know what that is?

I'm also struggling to find in the source where the crafting issue might be hiding...

**Comment by wapcaplet** [comment] 2020-12-18 01:26
I can reproduce this in 0.E-8226-g0f48ccd485 using your attached save file, but I don't think it has anything to do with tags/flags or temperature.

By enabling debug mode (set a keybinding for "Toggle Debug Mode" first), you will see extra info for the "clean water" item, in particular the "tags:" is where hot/cold status and other flags would be found. The tags are empty for the clean waters in your save game:

![image](https://user-images.githubusercontent.com/238395/102562101-9212ae00-4093-11eb-8011-64207fd0dd9d.png)

> I think this check is missing a flag for "water has no particular temperature." Anyone know what that is?

There is no flag for that - they would appear with no tags, as debug mode shows.

> EDIT: I've found this in item_test.cpp; anyone know how to try combining items to see if I can combine clean water with hot clean water?

You could define a liquid with no specific temperature at the top of the test case, like:

```cpp
item liquid_tepid( "test_liquid" );
```

Then in the "liquids at different temperature can be combined" section, check that they can combine with hot or cold:

```cpp
CHECK( liquid_tepid.can_combine( liquid_hot ) );
CHECK( liquid_tepid.can_combine( liquid_cold ) );
```

I am not convinced that's what's happening here, since I can reproduce it in your save with liquids that are neither cold nor hot, but am interested to know if you learn anything from adding this test.

**Comment by ToxiClay** [comment] 2020-12-18 01:50
Unfortunately, that's a bit beyond my skill level. I don't have a compilation environment for CDDA, and I'm only a novice codesmith. I can poke the game as it exists, and (sort of) read static code, but I'm afraid I won't be much help in fabricating new code.

> By enabling debug mode (set a keybinding for "Toggle Debug Mode" first),

OK, how do I do this? I've got two offending Clean Water items that should logically be stacking, but aren't. Checking the debug data might point me in the right direction.

**Comment by anothersimulacrum** [comment] 2020-12-18 01:58
Just show the item info normally, it'll now contain data about flags and item vars.

**Comment by ToxiClay** [comment] 2020-12-18 02:02
I'm not seeing it when I press Enter on the item out of the inventory screen. Debug Menu is bound to the back-tick. It should be right with the other information, right?

**Comment by wapcaplet** [comment] 2020-12-18 03:51
There are two debug-related keybindings - "Debug Menu" allows you to spawn items or monsters and lots of other debugging actions, but "Toggle Debug Mode" is what I was referring to - this is what turns on visibility for item tags (also called flags):

![image](https://user-images.githubusercontent.com/238395/102572309-f55b0b00-40a8-11eb-99db-ce42bc9fdfa3.png)

Bind that, toggle it on, then look at the info for the water item (not the container).

I didn't see any tags on the clean waters in your game, so I don't think that is what is preventing you from refilling. Something else is going on here.

**Comment by ToxiClay** [comment] 2020-12-18 06:51
OK, now we're cooking.

As my save showed, I have two water items: 1 unit in my canteen, and eight units in a gallon jug.

I can confirm that I cannot refill the canteen from the jug, even though I should be able to.

.......I think I found out that the problem is something far stranger. The game is not letting me refill a partially-filled canteen from a gallon jug.

I can refill an _empty_ canteen from a gallon jug, and I can refill a _partially-filled_ canteen from a plastic bottle, but refilling a partially-filled canteen from a gallon jug is a no-go.

What actually?

**Comment by PaulBlay** [comment] 2020-12-18 07:43
It's the source of the water.  I don't know what, or why. 

Your eight units in the gallon jug were probably some you crafted yourself, right? The one unit in the canteen was probably left from clean water you found in it when it was dropped by a zombie soldier.

If you make clean water using a FOODCO station water purifier then you will be able to use it to refill the canteen, but not to top up the gallon jug.

**Comment by ToxiClay** [comment] 2020-12-18 09:07
> Your eight units in the gallon jug were probably some you crafted yourself, right? The one unit in the canteen was probably left from clean water you found in it when it was dropped by a zombie soldier.

Not so. I tried that. I filled the canteen from the gallon jug, took a swig from the canteen, then tried to refill the canteen _from the same gallon jug._ No go.

**Comment by PaulBlay** [comment] 2020-12-18 09:29
Hmm, ... where did the original water in the gallon jug come from?

**Comment by ToxiClay** [comment] 2020-12-18 18:36
Huh. Because it was in a gallon jug, my thinking is that I crafted it myself.

I have re-prepared the save file with the precise conditions necessary to replicate the bug. I am holding a 15-unit gallon jug and an empty canteen.

1. Refill canteen from jug.
2. Drink from canteen.
3. Attempt to refill canteen.

This save should let you reproduce:

[Water Bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5717499/Water.Bug.zip)

**Comment by PaulBlay** [comment] 2020-12-18 19:00
> This save should let you reproduce:

Nope. Does not reproduce in #11268 on my computer.

**Comment by ToxiClay** [comment] 2020-12-18 19:13
> Have you checked that saving and reloading doesn't 'fix' the bug?

It doesn't; I've repeated the issue a couple of times across a couple of save/quit/reloads.

> > This save should let you reproduce:
> 
> Nope. Does not reproduce in #11268 on my computer.

That is..... very, _very_ bizarre. I have access to build 11268; let me see if that repaired the issue.

11268 broke my game, so I cannot verify that the problem doesn't exist.

I'll open a new issue for that while I walk through the build history to find one that doesn't fail to try to reproduce.

**Comment by PaulBlay** [comment] 2020-12-18 19:21
> 11268 broke my game, so I cannot verify that the problem doesn't exist.
Can you reproduce the bug as per 

1 Refill canteen from jug.
2 Drink from canteen.
3 Attempt to refill canteen.

In your current (not 11268) build from a new game with only default mods? 

If you can, then you could try a new game, only default mods, in 11268 and see if it still happens to you.

**Comment by ToxiClay** [comment] 2020-12-18 19:24
> P.S. MSX++UnDeadPeopleEdition is broken in 11268, but Ultica should work fine. Don't know if that was your problem.

Oh! Let me verify this real quick.

> In your current (not 11268) build from a new game with only default mods?

How would I go about verifying which mods are "default mods," and yanking out the ones that aren't?

**Comment by PaulBlay** [comment] 2020-12-18 19:28
> How would I go about verifying which mods are "default mods," and yanking out the ones that aren't?

Just start a new world and accept whatever it suggests for settings. Or to be sure you have default everything you can download a fresh copy of the game and unzip,

**Comment by ToxiClay** [comment] 2020-12-18 19:41
Ah, and then use the debug menu to verify behavior. OK, will try that and report back.

...No, it doesn't. Steps:

1. Deleted entire CDDA directory, including the launcher.
2. Downloaded a new copy of the launcher.
3. Downloaded Build 11259. Game report follows:
```
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8214-ga69de80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

```
4. Attempted to reproduce bug using spawned-in hotplate, battery, pot, jug, and drawing water from a nearby river.
5. The bug is still present! The partially-filled canteen will not reload from the jug.

At this point I'm starting to think I'm just cursed.

[Appomattox.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5717743/Appomattox.zip)

**Comment by PaulBlay** [comment] 2020-12-18 19:57
Well, congratulations, you aren't insane. 

I CAN verify that on a fresh copy of #11259 Windows x64 tiles and running Windows 8.1 that save does reproduce the bug you've been talking about.

**Comment by ToxiClay** [comment] 2020-12-18 20:08
> The water in the Jug has "item_tags": [ "COOKED" ],
> The water in the canteen does NOT.

Actually. I think the problem lies with the canteen.

Now that you mention that, here's something else to noodle on: when you first create clean water by boiling, it has the `(hot)` tag on it, right?

But once you pour it into the canteen, that `(hot)` tag goes away.

I think, somehow, the canteen is altering the water after it's poured in.

**Comment by PaulBlay** [comment] 2020-12-18 20:20
OK, I found the 'what' I don't know the 'why'.

In the save file the jug has 

"components": [ { "typeid": "water", "charges": 1, "bday": 5212841, "active": true, "last_temp_check": 5212848, "item_tags": [ "COOKED" ], "specific_energy": 92740464, "temperature": 27759446, "relic_data": null, "contents": { "contents": [ { "pocket_type": 4, "contents": [  ], "_sealed": false }, { "pocket_type": 3, "contents": [  ], "_sealed": false }, { "pocket_type": 6, "contents": [  ], "_sealed": false } ] } } ],

Delete that part and you can fill up the canteen from the jug.

I think when you cook food that can have variable ingredients it records what it was made from for nutrition information. You probably can't (haven't checked) pour fruit juice made from apples into fruit juice made from peaches.

For _some reason_ it is recording 'clean water' as having been 'cooked' from 'water' but losing that information (sometimes?) from some containers at some point. And then you can't mix them.

**Comment by ToxiClay** [comment] 2020-12-18 20:29
_Huh._ How utterly bizarre.

I think that might also explain the animal oil bug someone mentioned in the other issue. It's weird that the canteen erases that information _sometimes_ but not others (the fresh tag for example, won't be erased).

@anothersimulacrum -- what might a good fix be? Deleting the cook record for certain products where it's illogical to keep it around?

**Comment by wapcaplet** [comment] 2020-12-18 20:31
@ToxiClay I cannot reproduce the error with your second .zip file, but can still reproduce it with the original save you attached. A few other curiosities I noticed in both saves:

- Reloading your canteen from a water bottle (2) instead of a gallon jug - it will say "You refill the `|\` plastic canteen > clean water", but no liquid is transferred
- Pick up the gallon jug that only has (5) units in it, and try reloading it from another jug, or from one of the water bottles - again it will say it was reloaded, but no liquid is transferred
- Try to reload the same gallon jug from the plastic canteen - get an error `tried to put an item (water_clean, amount 1) in a container (jug_plastic) that cannot contain it` (yet the canteen will still be emptied)

So far I have not been able to reproduce these behaviors in a new save game. @PaulBlay you might be onto something with the cooked ingredients - would love to know if you are able to confirm that theory.

I am taking a closer look at the code where the error is raised, and will see if I can determine what's going wrong.

**Comment by anothersimulacrum** [comment] 2020-12-19 07:12
A recipe or item flag saying to ignore components would probably work, but feels a little band-aidy and fragile to me.
I'm not quite sure what a very fix would look like.

**Comment by PaulBlay** [comment] 2020-12-19 08:04
> A recipe or item flag saying to ignore components would probably work, but feels a little band-aidy and fragile to me.

I think there are a few separate problems here. 

1.  That component information is being lost, sometimes.
2.  That  liquids with differing components cannot be combined when combining them should be of trivial significance.
3.  That there is no explanation to the player as to why he cannot combine liquids with differing components.

Perhaps it would be easier if considered one by one? The first is clearly a bug. Component information should only be discarded intentionally, if / when it makes sense to do so.

For the second you need to consider what makes combination of trivial significance and how to handle it. I think there are cases where effects of combination may be safely ignored. For example, when you are combining liquids that are never going to be fit for consumption. If you combine diesel made in two different ways then the vitamin content of diesel produced is not going to be important. Diesel, lamp oil, bleach ... I think component information of all those should be promptly discarded if it would prove a hindrance to combining liquids into one container. The other case, slightly different, is when one of the liquids being combined has no component information and the other does. It may not be perfect, but I think the best solution would be that when combining a 'generic' or 'sourceless' liquid with a 'specific' liquid (one with known components) you could just keep the component information from the liquid that has it and apply it to the combined liquid. Mixing animal cooking oil from tainted fat with cooking oil from a shop drop would produce tainted cooking oil.

The third is at once trivial and tricky. Trivial because you could just list invalid destination containers 'greyed out' so players can see they exist and (when selected) show a message like "You feel uneasy about mixing liquids made in different ways". It at least gives an explanation, but is immersion breaking.

I've got to go walk the dog now. I still have more thoughts. :P

**Comment by ToxiClay** [comment] 2020-12-19 08:44
> Mixing animal cooking oil from tainted fat with cooking oil from a shop drop would produce tainted cooking oil.

This makes real-world sense, too. Combining something that you made from an unhealthy source with something that you mean to make food with _should_ taint the entire lot; you don't know what's good and what's bad.

> It at least gives an explanation, but is immersion breaking.

This is a noble goal, but there are points at which trying to break immersion as little as possible has to give way to a good game experience. Visible battery charges, as an example. I can't look at a CR2032 and say "Oh, this has a fifth of its battery power," but in CDDA I _can_ look at an ultra-light disposable and say "Hey, this has 20/100 charges left."

Ultimately, I like your proposed solution: it's intrinsically simple, it's algorithmically straightforward, and it seems relatively easy to program (Hello, Dunning-Kruger!).

**Comment by wapcaplet** [comment] 2020-12-31 17:03
I just ran into related (possibly duplicate) issue #45471 again in 0.E-8292-g00db780b75. This attached save: [CleanWaterNotMixing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5757793/CleanWaterNotMixing.zip) has 2 gallon jugs of clean water (one of them hot) that should be possible to combine, but they cannot be combined using `U`nload or `i`nsert. Using `r`eload, they appear to combine (message printed) but no liquid is transferred - much like was happening above with your canteens.

**Comment by BrettDong** [comment] 2021-01-02 18:13
This is the same issue as in #44791.

**Closed by BrettDong** 2021-01-02 18:13 UTC
Labels: (S2 - Confirmed), <Bug>, Items: Containers
