### ISSUE TITLE
String error instead of volume and weight inventory

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#34163] opened 2019-09-22 00:29 UTC
# Describe the bug

Everything seems to work fine, but at the top of the inventory screen this happens instead of showing my volume and weight.

# Steps To Reproduce

Load save in build 0.D-7800
see pictured error when one opens inventory

# Expected behavior
don't see error string, see inventory volume and weight
# Screenshots
![image](https://user-images.githubusercontent.com/40927483/65380682-9383e800-dd23-11e9-9901-2076c2f61c55.png)
# Versions and configuration
Windows, tiles, x64
0.D-7800 22/09/2019 (GMT11+)
Mods:
`[
  "dda",
  "Tolerate_This",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "modular_turrets",
  "Salvaged_Robots",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "DP_REMIX_INDICATORS",
  "sees_player_retro",
  "cbm_slots",
  "sleepdeprivation",
  "No_Rail_Stations",
  "no_npc_food"
]`

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3639207/save.zip)

**Comment by anothersimulacrum** [comment] 2019-09-22 00:43
Fixed by #34160

**Closed** 2019-09-22 01:25 UTC

**Comment by ZhilkinSerg** [comment] 2019-09-22 14:47
Duplicate of #34159
