### ISSUE TITLE
Welder bug

### ISSUE THREAD

**Issue by Leon9621** [CleverRaven/Cataclysm-DDA#23211] opened 2018-03-15 04:08 UTC
Game version: 0.C-26655-g8266f3d

Operating system: Windows 8

Tiles or curses: Tiles

Mods active: More Survival Tools, StatsThroughSkills, Vehicle Additions Pack, Tanks And Other Vehicles, Makeshift Items Mod, More Locations, Disable NPC Needs, Prevent Zombie Revivification, Simplified Nutrition

### Steps to reproduce the behavior Place an empty welder into a vehicle storage compartment, in this case a cargo space, press r to reload it from the cargo space, and begin repairing.

**Comment by ZhilkinSerg** [comment] 2018-03-15 06:55
Duplicate of #22789.

**Closed by ZhilkinSerg** 2018-03-15 06:55 UTC
