### ISSUE TITLE
u_has_items and u_sell_item do not recognize anesthetic in an anesthesia kit

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#55918] opened 2022-03-07 03:42 UTC
### Describe the bug

The anesthesia kit uses "ammo" instead of count or charges and is therefore not recognized by either `u_has_items` or `u_sell_item` in dialogue conditions/effects. This probably affects other items that use ammo as well, but I haven't tested anything else.

### Steps to reproduce

1. Change a dialogue's condition to: `"condition": { "u_has_items": { "item": "anesthetic", "count": 3000 } }` and effect to `"effect": { "u_sell_item": "anesthetic", "count": 3000 }`
2. Talk to npc, dialogue will not appear
3. Spawn enough anesthetic in another container or unload the kit into another container
4. Talk to npc, dialogue will appear and work correctly

I'm testing this on a new mission, so I don't believe there are any existing missions that do this.

### Expected behavior

Anesthetic should be recognized in dialogue conditions and effects when it's in an anesthesia kit, just the same as in any other liquid container.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1526 (21H2)
- Game Version: 0.F-6540-g158330a8a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment] 2022-03-08 02:52
I think the problem is pretty widespread. Merchants (&, by proxy, mission-givers, I imagine) have difficulty w/ nested containers & containers w/ charges. Try selling a mag-using gun both un- & loaded. Try selling them the clip w/ bullets in or out. I found it best to always 'U'nload everything for merchants in order to obtain max value.

#51704 fixed a few things but I'm playing on 0.F-3. You could prob model a fix for this issue based on something in that PR.

**Comment by haveric** [comment] 2022-03-08 03:09
This issue is targeted specifically at dialogue/mission interaction. Anything outside of that (trading) is outside the scope of this issue and should be brought up as its own issue if it isn't already.

**Closed** 2022-03-25 01:04 UTC
Labels: NPC / Factions, Mechanics: Effects / Skills / Stats
