### ISSUE TITLE
Shelter computer option 3 fails to find a refugee center at high city spacing and high city size

### ISSUE THREAD

**Issue by mding9** [CleverRaven/Cataclysm-DDA#38993] opened 2020-03-24 15:21 UTC
# Describe the bug

The starting shelters have a computer that can be accessed to find a refugee center. However, when I play with my preferred setting of large and widely spaced cities, the computer often ends up giving up.

# Steps To Reproduce

1. load a world with city spacing 8 and city size 16
2. default start
3. access computer
4. choose "contact us" option
5. More often than not, you will get something like

```
DEBUG    : Unable to find and assign mission target refctr_S3e.

 FUNCTION : cata::optional<tripoint> find_or_create_om_terrain(const tripoint&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 240
```

The mission will still appear on your missions list, but it won't have any coordinates.
You will also get the messages "Unable to place all configured specials, some missions may fail to initialize" and "you have no idea where the address might be..." in the normal game message log.

# Expected behavior

I think that all allowed map settings should be able to generate the required mission specials.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: [Windows 10]
 - Game Version: [0.D-13348-g7f3a4a4]
 - Graphics version: [Tiles]
 - Ingame language: [English]
 - Mods loaded: [dda,disable NPC needs]

**Comment by ZomgPonies** [comment] 2020-04-11 23:04
I'm getting the same error regularly at default sizes: city size 8, city spacing 4.

**Comment by ZomgPonies** [comment] 2020-04-18 02:14
@mding9 Were you by any chance running Days of the Dead? It doesn't load the refugee center because it is not considered a CLASSIC location, hence the bug. I am working on fixing this and replacing any special zombies in the questlines there with classic ones when this mod is active.

**Comment by mding9** [comment] 2020-04-18 05:37
Well, when I created this post, I could create a world with nothing except the core content pack and the Disable NPC Needs mod and the error would occur.

**Comment by eltank** [comment] 2021-06-21 07:28
Using a game binary built at 1d56719c I generated 6 worlds using city spacing 8 and city size 16, no mods.
I was not able to reproduce this bug. The evac shelter console took a long time to find the refugee center and the log had a message that made it seem like it failed, but it actually succeeded every time (though the center was ~5 overmaps away). I teleported there to make sure the building actually spawned.

![message](https://user-images.githubusercontent.com/8000047/122722945-30d8bc80-d227-11eb-964d-4433ca8d16eb.png)
![map](https://user-images.githubusercontent.com/8000047/122722946-32a28000-d227-11eb-9639-1443a9a9777d.png)

With the classic_zombies mod, it fails every time. I believe that's a separate issue that's tracked in #49285 and will be fixed by #49391.

**Comment by Night-Pryanik** [comment] 2021-06-21 09:03
Ok, closing until reconfirmed.

**Comment by alfuken** [comment] 2021-07-14 17:28
@Night-Pryanik Confirming with build of 2021-07-14-0726 (e021315) — enabling "Days of the Dead" prevents Refugee Center from spawning. Disabling this mod fixes the issue.

@eltank
> I also believe this is an unreasonable expectation: "I think that all allowed map settings should be able to generate the required mission specials".

I think that all the default mods provided along with the game should not break such a basic and important functionality as refugee center, unless explicitly intended by the mod lore, like "Aftershock" or "Dark Skies Above".

**Comment by eltank** [comment] 2021-07-15 02:16
@alfuken See #49391 and the reply from the author of "Dark Days of the Dead". That mod is not supposed to spawn a Refugee Center due to the mod's lore:

> This is actually an intentional omission. For one thing there are quests and dialogue that refer to or require vanilla cataclysm, but maybe more importantly, I'd like to replace it with a new in-lore faction center

**Closed** 2021-07-15 02:35 UTC
Labels: (S2 - Confirmed), <Bug>, Map / Mapgen, Missions
