### ISSUE TITLE
Smoking Rack does not progress while outside the reality bubble

### ISSUE THREAD

**Issue by TempestMaiden** [CleverRaven/Cataclysm-DDA#26475] opened 2018-10-31 20:57 UTC
**Describe the bug**  
An active smoking rack only ticks down time-to-completion while within the reality bubble.

**To Reproduce**  
1. Build a smoking rack next to a house with a basement.
2. Load the smoking rack with meat and charcoal, then start it.
3. Examine the rack to see how much in-game time is expected to pass until it finishes.
4. Enter the house's basement and go to sleep or otherwise pass several hours.
5. Return to the smoking rack and examine it to see how much time is expected to pass before it completes.

**Expected behavior**  
I expected the smoking rack to have finished its job overnight as my character slept, same as the charcoal kiln works.

**Versions and configuration(please complete the following information):**
 - Windows 10
 - Game Version 0.C-33651-gbabb58f
 - Tiles version
 - Used default world creation

**Additional context**  
[Camp Houston.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2536361/Camp.Houston.zip)

**Comment by mlangsdorf** [comment] 2018-11-01 20:59
I've seen this behavior, super annoying.
@nexusmrsep, if you don't want to handle this, just tell me and I'll remove the assignment.

**Comment by sphdj** [comment] 2018-11-03 07:10
Did you have experimental z-levels on? If it was off, the behavior you're experiencing is likely due to surface levels not being active while you sleep. Several other objects in the game have similar mechanics where if the tile the instrument is (ex. a smoking rack) is not active due to a players presence, so I wouldn't be surprised if that relates to the problem. It's been a minor issue for a while I think.

**Comment by woutershep** [comment] 2018-11-03 11:05
@sphdj i think its important to note that in his setup it is only reproducable with z-levels off. but the issue itself is not related to z-levels the way i understand it. it would still manifest with z-levels on when instead of 'going to the basement' you would 'go to another town'. it should probably just be solved by retroactively applying the ticks when it re-enters the reality bubble just like solar panels and funnels do.

**Comment by mlangsdorf** [comment] 2018-11-03 13:18
I have z-levels on and my smoking rack is on the same level as my main base.  If I drop some meat in the rack, light the rack, and then go out to loot stuff, I come back 8 hours later to find the meat still smoking.

**Comment by ifreund** [comment] 2019-02-19 09:01
Fixed by #27902.

**Closed** 2019-02-19 09:01 UTC
Labels: (S2 - Confirmed), <Bug>, Fields / Furniture / Terrain / Traps
