### ISSUE TITLE
Error when accepting Back Bay Mission

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#53928] opened 2021-12-31 17:36 UTC
### Describe the bug

The following error occurs when accepting the Back Bay mission in the refugee center.
``` DEBUG    : loading non-main map at (698,342,0) which overlaps with main map (abs_sub = (690,335,0)) is not supported

 FUNCTION : void map::load(const tripoint_abs_sm&, bool, bool)
 FILE     : src/map.cpp
 LINE     : 6626
 VERSION  : 14aa061
```
I went back to the back bay and all the zombies were there including the leader zombie.  I killed the leader but I'm not sure if the mission completed or not as the shock field killed my debug character after that because I forgot to debug invincibility after seeing the error message.  Not sure if this error messes with the mission at all.

### Steps to reproduce

Create character,
Teleport to Refugee center
talk to smokes
ask for job
Accept Job 
see error message

### Expected behavior

No error message.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment] 2021-12-31 17:39
Second error upon completion of mission.
```
 DEBUG    : loading non-main map at (316,212,0) which overlaps with main map (abs_sub = (313,205,0)) is not supported

 FUNCTION : void map::load(const tripoint_abs_sm&, bool, bool)
 FILE     : src/map.cpp
 LINE     : 6626
 VERSION  : 14aa061
```

**Comment by Maleclypse** [comment] 2021-12-31 17:40
Same error as #53869

**Comment by wapcaplet** [comment] 2022-01-02 21:56
Confirmed by player on discord.

**Comment by Inglonias** [comment] 2022-07-08 19:13
Unable to reproduce this issue in the most recent experimental. Suggest closing.

**Closed** 2022-07-08 20:03 UTC
Labels: <Bug>, NPC / Factions, (S2 - Confirmed), Map / Mapgen
