### ISSUE TITLE
Disassembly Search: Find things that can be disassembled/cut/deconstructed/butchered to yield a certain item

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27678] opened 2019-01-17 10:34 UTC
**Is your feature request related to a problem? Please describe.**  
I've spent almost all of my current game session struggling to get enough thread for tailoring. Apparently thread can be obtained from cotton balls, but where do I get them without peeking into source code?
**ENTER MOTHERFUCKING PILLOWS.**

**THOSE COMFY FUCKS ARE MORE USEFUL THAN YOU THINK.**

**Describe the solution you'd like**  
An additional menu that allows you to enter a thing you want to get and it displays all things that can be devolved into this item.

**Describe alternatives you've considered**  
N/A

**Why**  
This should make crafting system go in cycle and allow you to get a certain set of items you're looking for for your next project. You'll still have to go find those things first though, but at least you won't need to blindly stumble around trying to figure out where thermometers are.

**Comment by paulenka-aleh** [comment] 2019-01-17 10:44
I'm 100% for having a way to look for disassembly results. I'd even like to include furniture.

But to be honest it doesn't require code diving. Never did so myself ever. You can apply creative thinking and use trial-and-error method to get what you want. Where would you get thread should real cataclysm happen?

**Comment by DeltaEpsilon7787** [comment] 2019-01-17 10:47
Well, yes and no. Most things are rather obvious, but when it comes to more obscure stuff, like electronic scrap, tinted glasses, high quality lenses and all that, it's a shot in the dark for more obvious ones.

**Comment by l29ah** [comment] 2019-01-17 16:16
It's easier to disassemble curtain strings or seatbelts in fact :P

**Comment by thebunanna** [comment] 2019-01-17 18:31
I solved this by pressing the disassemble key ('(' I think) and use the filter ('/') and typing 'd:' and whatever I need.

**Comment by DeltaEpsilon7787** [comment] 2019-01-17 18:58
> 
> 
> I solved this by pressing the disassemble key ('(' I think) and use the filter ('/') and typing 'd:' and whatever I need.

That's a completely different thing. Read the description, will you. This suggestion deals with a way to know **what items in general** can be disassembled for something, not what you have at the moment.

**Comment by thebunanna** [comment] 2019-01-17 20:12
> > I solved this by pressing the disassemble key ('(' I think) and use the filter ('/') and typing 'd:' and whatever I need.
> 
> That's a completely different thing. Read the description, will you. This suggestion deals with a way to know **what items in general** can be disassembled for something, not what you have at the moment.

Ah my apologies, it seems like I had misunderstood you.

In any case, I do think that this feature would be quite helpful in the crafting window, where one could search for 'thread' and below the general description would be a list of items that can be disassembled from. However, with the current system of jsons, I would assume that this search might be very slow at times due to basically having to search through every item to see if the resulting disassembly has 'thread.'

**Comment by DSeyka** [comment] 2019-01-17 22:19
We'd have to scale for potential 9001 mods which add items and crafting recipes.

**Comment by GoLoT** [comment] 2019-01-18 01:52
Wouldn't this expose information to the player that their character shouldn't have access to? I mean, right now crafting recipes are hidden until you learn them. This function would act as a workaround to find any items in the game (that can be disassembled, which most craftables are) and the materials needed to craft them.

It might be just me but I prefer that information to be something you have to discover by playing the game. Why should you be able to tell what something is made of without even knowing that such a thing exists? An alternative would be to only show components from items you found during the playthrough, but keeping track of them could be a problem.

**Comment by thebunanna** [comment] 2019-01-18 04:59
> An alternative would be to only show components from items you found during the playthrough, but keeping track of them could be a problem.

Well, to keep track of the items found would only be a bit more difficult than managing a set and inserting items as found.  However, if there was an inclusion of many more items, this may be very inefficient.

**Comment by kevingranade** [comment] 2019-01-18 06:52
A seen set is not particularly inefficient, it should have minimal overhead if that's what we want to do.

**Comment by DeltaEpsilon7787** [comment] 2019-01-18 08:09
> 
> 
> Wouldn't this expose information to the player that their character shouldn't have access to? I mean, right now crafting recipes are hidden until you learn them. This function would act as a workaround to find any items in the game (that can be disassembled, which most craftables are) and the materials needed to craft them.
> 
> It might be just me but I prefer that information to be something you have to discover by playing the game. Why should you be able to tell what something is made of without even knowing that such a thing exists? An alternative would be to only show components from items you found during the playthrough, but keeping track of them could be a problem.

On another hand, the player should know that there's something he's missing.
So I suggest a mixed solution: you output items to disassemble that you've seen before and also add some mark if they're craftable or not [to distinguish from trivial cases since a lot of crafts disassemble into their materials and are not really interesting]. Then, you also add something like, "There are 576 more things that may work", but you don't display them until the character sees them.

**Comment by kevingranade** [comment] 2019-08-15 05:53
Duplicate of #25945

**Closed by kevingranade** 2019-08-15 05:53 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>, Crafting / Construction / Recipes, Info / User Interface, Quality of Life
