### ISSUE TITLE
Metal Pots Can't Hold Liquid

### ISSUE THREAD

**Issue by GrandpuhTy** [CleverRaven/Cataclysm-DDA#30511] opened 2019-05-14 15:01 UTC
# Describe the bug

Metal pots do not hold water when held or place on the ground.

stock pot
pot
generic cook pot
cast iron pot
copper pot

# Steps To Reproduce

1. Generate new basic vanilla world.
2. Generate new random character, spawn in, wish for any metal pot.
3. Hold pot or place on ground.
4. Attempt to full pot with water and fail.

# Expected behavior

Clay pots hold water, teapots are the metal exception along with opened cans. Expected behavior is that metal pots do the same.

# Screenshots

[Holding pot](https://i.imgur.com/BurGjVg.png)

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-2935-g4da9158
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Garden Pots [growable-pots]

# Additional context

#30331

**Comment by Night-Pryanik** [comment] 2019-05-14 15:52
Closing in favor of #30331 along with your reproduction steps copied to that issue.

**Closed by Night-Pryanik** 2019-05-14 15:52 UTC

**Comment by Zombiemanpig** [comment] 2019-06-01 00:09
> Closing in favor of #30331 along with your reproduction steps copied to that issue.

Why was this closed when it is not fixed?

**Comment by Feuerhai** [comment] 2019-06-01 13:55
> Why was this closed when it is not fixed?

We only need one issue per problem and there already was another one open.
The referenced issue was closed because a fix has been merged, sadly it was it wasn't noticed immidiatly that it wasn't a complete fix.
It is probably fixed now with #31032
