### ISSUE TITLE
tamed animals stops following when near other non hostile animals

### ISSUE THREAD

**Issue by nullptr98** [CleverRaven/Cataclysm-DDA#36393] opened 2019-12-24 01:27 UTC
# Describe the bug
taming an animal(a) and walking into another animal(b) stops ur tamed animal(a) from following you, untill u tame/kill the other animal(b)                                                            
 

# Steps To Reproduce

1. tame an animal
2. go near another animal

# Expected behavior

your tamed animals should keep following when near other non hostile creatures.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10636-g1c67f59 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ymber** [comment] 2019-12-24 08:35
Duplicate of #36372.

**Closed by ymber** 2019-12-24 08:35 UTC
