### ISSUE TITLE
Curses version invisible debug messages

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#20649] opened 2017-03-24 00:01 UTC
Currently, I encounter invisible debug messages on the curses version.
For example, debug message about exceeding maximum of mandatory overmap specials is invisible on the curses version while SDL version displays the message correctly.
This might be confusing for those using curses and not knowing about the message.
The message can still be skipped despite being invisible, but I doubt that it was intended to be invisible on curses while being visible on SDL on the same settings.
I am using latest experimental build 6354 from Jenkins with custom fonts, if that matters.

**Comment by Leland** [comment] 2017-05-08 03:39
Duplicate of #20061

**Closed by Leland** 2017-05-08 03:39 UTC
Labels: Bug, Confirmation Needed
