### ISSUE TITLE
Base Traits and Bionics

### ISSUE THREAD

**Issue by TheJinxleet** [CleverRaven/Cataclysm-DDA#54649] opened 2022-01-22 00:57 UTC
### Describe the bug

If you have thick-skinned as a base trait selected from character creation it is impossible to install Alloy Plating CBMs. Usually you can remove thick-skinned as a mutation but because it is considered a base trait the purifier serum ignores it and it becomes impossible to remove it or use alloy plating CBMs.

### Steps to reproduce

1. Create a character with thick-skinned as a base trait from character creation 
2. Try to install any Alloy Plating CBM
3. Attempt to remove the thick-skinned base trait

### Expected behavior

Because thick skinned is one of the few traits that can be selected from character creation, I thought there wouldn't be any incompatible bionics with any of those traits, not to mention all of those traits have the base trait....tag? so they can't be removed accidentally with a purifier serum and to differentiate them with mutations as just being natural genetics to that particular character. I'd suggest either removing thick-skinned from the character creation or to remove the thick-skinned traits incompatibility or any other potential character creation traits from any CBM incompatibility to prevent the issue to begin with.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3a0641e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by anoobindisguise** [comment] 2022-01-22 01:51
Thick-skinned and thin-skinned were already removed as starting traits.

**Comment by LeahLuong** [comment] 2022-01-22 03:19
Dupe of #53891. Please close this issue.

**Closed** 2022-01-22 07:32 UTC
