### ISSUE TITLE
Bug with item damage?

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#18966] opened 2016-10-25 02:45 UTC
Playing on the most recent version, I stabbed a wolf spider with a rapier, and got a message saying that my weapon was damaged by the force of the blow, but it appears to still be fully reinforced.

Possibly worth noting that I first obtained and reinforced this weapon in a build around 10 days old, and updated recently.

Screenshot attached.
![image](https://cloud.githubusercontent.com/assets/19789267/19671262/1ac89faa-9aa0-11e6-924b-550399363a4d.png)

**Comment by Oskar636** [comment] 2016-11-08 20:59
It will be hard to reproduce without a save, does anyone know an item that can be reinforced and is easily damaged to test this?

**Comment by Leland** [comment] 2017-05-24 00:31
Closing due to lack of reproduction. If anyone else encounters this, please make a new issue.

**Closed by Leland** 2017-05-24 00:31 UTC
Labels: Bug
