### ISSUE TITLE
Segfault on 0.D-1168-g3fe32b0

### ISSUE THREAD

**Issue by Crunchepillar** [CleverRaven/Cataclysm-DDA#29125] opened 2019-03-29 23:14 UTC
**To Reproduce**  
Load included save and move to the north and then west around the refugee shelter. Hug the wall tight as you go west and it segfaults. Think it might have something to do with the zombies making noise or something, but who knows?

![image](https://user-images.githubusercontent.com/4098225/55267132-695add00-524e-11e9-9700-69eb23b8ded4.png)
You want to be around here. Sometimes the crash is an "arithmetic error" rather than segfault, strange.

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-1168-g3fe32b0
 - Graphics version: Tiles
 - Mods loaded: DDA, Filthy_Morale, No_NPC_Food

**Additional context**  
[Coles.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3024825/Coles.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3024828/crash.log)

**Comment by Crunchepillar** [comment] 2019-03-29 23:17
Possibly related #29102

**Comment by ZhilkinSerg** [comment] 2019-03-30 08:47
Duplicate of #29043

**Closed by ZhilkinSerg** 2019-03-30 08:47 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
