### ISSUE TITLE
Weird issue in hospital with beds being vehicles ramming everything

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44289] opened 2020-09-20 12:28 UTC
There's some sort of problem with hospitals beds being vehicles and they just keep ramming walls and everything around them and the place seems like there's a party of juggernauts in there

# Steps To Reproduce

Just load the save I provide and you'll see
SAVE ON MEGA CANT UPLOAD RAR HERE https://mega.nz/file/l2xAiIiQ#1I0Z_EYFP92q5sKVzeMBEoYQ8sk247uy0GjJv9BKAts

# Expected behavior

Well I expected a deserted hospital not to be so noisy

# Screenshots
[](https://i.imgur.com/3DRmaWc.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6018-g1371f96 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key]

**Comment by wapcaplet** [comment] 2020-10-22 02:49
Possible duplicate of #44265

**Comment by ZhilkinSerg** [comment] 2020-11-08 18:55
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/44265

**Closed by ZhilkinSerg** 2020-11-08 18:55 UTC
Labels: <Bug>, Map / Mapgen
