### ISSUE TITLE
Crash in is_food after fixing a gray minifridge installed in a vehicle

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29683] opened 2019-04-18 16:54 UTC
**Describe the bug**  
in my modded RV. Maybe it has something to do with the fact the minifridge was filled with various stuff before getting devoured by zombies?
```
VERSION: 0.D-1878-g5819d39de4-dirty
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	cataclysm(_Z21debug_write_backtraceRSo+0x38) [0x55bfdb22d408]
	cataclysm(+0x557952) [0x55bfdb216952]
	cataclysm(+0x557db8) [0x55bfdb216db8]
	/lib64/libc.so.6(+0x396b0) [0x7f8c9a2ee6b0]
	cataclysm(_ZNK12Item_factory13find_templateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2d) [0x55bfdb4ad29d]
	cataclysm(_ZNK4item7is_foodEv+0x20) [0x55bfdb436bd0]
	cataclysm(_ZN3map24process_items_in_vehicleER7vehicleR6submapiPFbR10item_stackRSt14_List_iteratorI4itemERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEifESK_+0x705) [0x55bfdb5baa55]
	cataclysm(_ZN3map25process_items_in_vehiclesER6submapiPFbR10item_stackRSt14_List_iteratorI4itemERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEifESI_+0x10a) [0x55bfdb5bb45a]
	cataclysm(_ZN3map13process_itemsEbPFbR10item_stackRSt14_List_iteratorI4itemERK8tripointRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEifESG_+0xb3) [0x55bfdb5c5f73]
	cataclysm(_ZN3map20process_active_itemsEv+0x43) [0x55bfdb5c60e3]
	cataclysm(_ZN4game7do_turnEv+0x7cf) [0x55bfdb36241f]
	cataclysm(main+0xd11) [0x55bfdb043271]
	/lib64/libc.so.6(__libc_start_main+0xeb) [0x7f8c9a2d8ecb]
	cataclysm(_start+0x2a) [0x55bfdb074d2a]

	Attempting to repeat stack trace using debug symbols...
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(addr2line) failed
```

 - Mods loaded: boats, bright nights, aftershock

**Comment by ipcyborg** [comment] 2019-08-02 09:08
Can't reproduce on 0.D-6072-g4add125.
Steps:
1. Spawn an RV.
2. Spawn 10 pemmican. Put them into then RV minifridge.
3. Spawn homewrecker. Smash the RV minifridge completely (to gray).
4. Observe 10 pemmican dropped from the RV minifridge to the ground.
5. Spawn 1 minifridge.
6. Repair gray the RV minifridge with the new one. 

No crash.

**Comment by ZhilkinSerg** [comment] 2019-09-18 18:46
Closing as non-reproducible.

**Closed by ZhilkinSerg** 2019-09-18 18:46 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Vehicles
