### ISSUE TITLE
Gunsmith / Firearm Repair Kits not working with UPS attachment

### ISSUE THREAD

**Issue by dreukrag** [CleverRaven/Cataclysm-DDA#33972] opened 2019-09-11 19:42 UTC
**Game version**: 0.D 9435

**Operating system:** Windows

**Tiles or curses:** Tiles

**Mods active:**

-  "dda",
-   "no_npc_food",
-   "aftershock",
-   "crt_expansion",
-   "magiclysm",
-   "craftgp",
-   "FIC_Weapons",
-   "growable-pots",
-   "ew_pack",
-   "makeshift",
-   "Medieval_Stuff",
-   "More_Survival_Tools",
-   "nw_pack",
-   "modular_turrets",
-   "Salvaged_Robots",
-   "crazy_cataclysm",
-   "fast_healing",
-   "hydroponics",
-   "mutant_npcs",
-   "national_guard_camp",
-   "more_locations",
-   "FujiStruct",
-   "mapgen_demo",
-   "Urban_Development",
-   "deoxymod",
-   "blazemod",
-   "Tanks",
-   "necromancy",
-   "stamina_regen_buff"

### **Expected behavior**
After applying the UPS attachment to a Gunsmith / Firearm repair kit and having a charged UPS with enough charges in the inventory when activating the repair kit and selecting repair a weapon it should allow me to select a weapon and repair it.

### **Actual behavior**
The repair kit allows me to select a weapon for repair but does nothing upon activation

### **Steps to reproduce the behavior**
- Spawn an UPS and load a heavy battery onto it
- Spawn a UPS attachment mod
- Attach mod to Firearm / Gunsmith repair kit
- Use gunsmith / Firearm repair kit
- Select weapon

**Comment by Night-Pryanik** [comment] 2019-12-08 13:57
Duplicate of #33968.

**Closed by Night-Pryanik** 2019-12-08 13:57 UTC
Labels: <Bug>, Battery / UPS, Gunmod / Toolmod
