### ISSUE TITLE
When NPC uses his/her CBM as ranged weapon you can buy pseudo item

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#45947] opened 2020-12-09 21:23 UTC
# Describe the bug

I was looking for clues about #45865 (another NPC bug).
My NPC has combat rules "use ranged weapons", "reserve 50% of bionic power".
She switched to ranged and was welding finger laser pseudo item. I bought it, used a few times and it didn't consume any power.
**EDIT**. Just checked. It has TRADER_AVOID already.
Possibly overwritten by friendly NPCs giving you free access to their inventory?

# Steps To Reproduce

Get NPC
Install it with power storage and a ranged weapon CBM that works by giving it pseudo item (e.g. Finger Laser CBM).
Wait till NPC uses it (NPC behavior settings)
Trade with NPC, it will have this fake item as wielded item in trade menu
Buy item

# Expected behavior

~~All pseudo items should have TRADER_AVOID.~~
Impossible to receive pseudo items from friendly NPC.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/101688993-19956700-3a6d-11eb-8620-dc244de8e330.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by emptytriangle** [comment] 2020-12-10 04:45
I ran into an npc who dropped her finger laser on the ground

**Comment by satheon49** [comment] 2020-12-10 10:21
The finger laser lacks the NO_UNWIELD flag though I am not sure it is as easy as adding that flag. Though having that flag will prevent trading, the NPC will no longer unequip/deactivate the laser either and since it has a ridiculously high weapon rating you can't coerce your NPC buddy to use anything else.

I have not dug too deep into the code but it seems that finger laser behave differently for NPCs because they activate them and then do not deactivate them again while for the player weapon cbms are activated from the bionics menu and immediately deactivated after use if they have the NO_UNWIELD flag.

**Comment by Mrzjadacz** [comment] 2021-01-03 21:30
Surgical scalpels fake item has the following flags:
 "TRADER_AVOID", "NO_UNWIELD", "UNBREAKABLE_MELEE"
 Someone would need to check whether adding no_unwield would still let NPC disable those bionics. They can use some CBMs like toolset, but not sure whether they deploy fake_item normally.

**Comment by int-ua** [comment] 2021-01-14 01:43
Please expand the steps to reproduce.

> Get NPC with ranged weapon CBM that has pseudo item (Finger Laser CBM).

How can I do it with debug menu quickly?

**Comment by Mrzjadacz** [comment] 2021-01-14 12:42
> Please expand the steps to reproduce.

Done.
Not sure if you can use debug to install CBM on NPC.
I can post save, but not today.

**Comment by int-ua** [comment] 2021-01-14 14:06
> Get NPC
> Install it with power storage and a ranged weapon CBM

Is it possible from the debug menu?

**Comment by Night-Pryanik** [comment] 2021-01-14 15:09
> Is it possible from the debug menu?

No, it's not.

**Comment by Mrzjadacz** [comment] 2021-01-24 20:29
Possibly fixed by #46919

**Closed** 2021-06-24 22:52 UTC
Labels: (S1 - Need confirmation), NPC / Factions
