### ISSUE TITLE
Animist Rune only lasts 2 turns even though it is flagged as permanent

### ISSUE THREAD

**Issue by Claidheahm** [CleverRaven/Cataclysm-DDA#66459] opened 2023-06-25 20:32 UTC
### Describe the bug

Casting the spell create_rune_animist creates a rune_animist, but it only lasts 2 rounds.
This spell is worded identically to all the other create_rune spells, but the created rune should be permanent as noted by the flag Permanent

The only difference I see in the JSON is that the Animist rune uses HP as the energy_source

### Attach save file

[Magiclysm-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11860731/Magiclysm-trimmed.tar.gz)

### Steps to reproduce

1. Start a new game as Necromancer so you start with Animist Rune spell
2. Cast Animist Rune
3. Wail a turn, and your rune will disappear

### Expected behavior

The rune should be permanent as all the other runes, and as the JSON indicates.

### Versions and configuration

- OS Windows 10
- Game version 00a5498
- Tiles
- English

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6107791/f03786a0-4c93-4aae-aecb-bf4e0fe09ba0)

**Comment by RenechCDDA** [comment] 2023-06-25 23:44
Having an HP component probably causes the duration to be interpreted as if it was a damaging spell, although I haven't plumbed the depths to tell you exactly where that's happening.

**Comment by RenechCDDA** [comment] 2023-06-26 00:15
Er, okay. Actually this appears to be working as designed? The spell isn't max level, so `PERMANENT` is not... permanent. Specifically:
https://github.com/CleverRaven/Cataclysm-DDA/blob/00a54988c6150052503cac32346003290545a5a1/src/magic_spell_effect.cpp#L1086
(Ethereal then is checked by item::process_internal which sees that it's not supposed to stick around so it yeets it.)

 For it to be permanent it'd need to be `PERMANENT_ALL_LEVELS`.

This should be the case for *all* runes after #65418. Doubt that it's working as **intended**, but that's a simple json flag switch.

**Comment by GuardianDll** [comment] 2023-06-26 09:34
I wonder why runes got +2 levels in 65418 at the first place
@Light-Wave can you explain please?

**Comment by Light-Wave** [comment] 2023-06-26 09:45
Okay, so I noticed that when you learn a rune spell, you gain it at level 2 despite having a max level of 0, as detailed in issue #65417. This caused some strange visual issues in my pull request, as it would lower the caster level down to 0 and make it look like you had a -2 caster level modifier from somewhere.
I didn't manage to find out what the issue was, so I just increased the maximum caster level to the level I thought everyone was getting them at. Apparently I was wrong about that.
I also didn't want to lower the caster level down lower than intentional since I noticed I had a fair spell failure chance when they were at level 0, and I didn't want to be the cause of runes having higher failure chance. But that could have been because I forgot to give my debug character levels in spellcraft, come to think of it.

**Comment by GuardianDll** [comment] 2023-06-26 10:15
idk why it could obtain rune spell level 2, but what i know is that class mutation, for some reason, give you a rune spell with spell level 1 (spell level count starts from `0`, also `-1` level exist, and represent "you don't know this spell")
https://github.com/CleverRaven/Cataclysm-DDA/blob/81a5897df5e9e739693ce27aea79e83342788c49/data/mods/Magiclysm/traits/classes.json#L24C43-L24C43
Maybe that's the reason it shows -2 levels?

**Comment by Light-Wave** [comment] 2023-06-26 10:35
I'm still confused why I got it at level 2 instead of 1, and why I got level 2 but others got it at a lower level. But setting that number to 0 seems to work as intended. I'll push up a fix for this in a moment.

**Closed** 2023-06-27 15:50 UTC
Labels: (S2 - Confirmed), Mods: Magiclysm
