### ISSUE TITLE
Segfault when attempting to use side mount

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#56887] opened 2022-04-17 22:57 UTC
### Describe the bug

Game crashes when clicking on the 'side mount' mod when a compatible gun is present.

### Steps to reproduce

1. Get side mount and a gun, and try to attach the gunmod. If the gun is incompatible, no crash occurs. If the gun is compatible, ~no~ crash.
2. (Save file character is standing over a bunch of guns and has side mount in inventory.)

### Expected behavior

No crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 2b38de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[Ronni Magnusson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8502594/Ronni.Magnusson.zip)

**Comment by andrei8l** [comment] 2022-04-18 02:27
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56827

**Comment by Sutremaine** [comment] 2022-04-18 03:44
I saw that one but wasn't sure if it was the same root cause.

**Closed** 2022-04-18 18:16 UTC
