### ISSUE TITLE
Zone corruption on loading save

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#49438] opened 2021-06-24 23:57 UTC
# Describe the bug

With #49423 applied, various zones get corrupted when loading [this save](https://github.com/CleverRaven/Cataclysm-DDA/files/6712430/zone_manager_49423.zip), which makes extensive use zones, including custom zones. Explicit errors are thrown:

```
08:21:51.412 ERROR : src/clzones.cpp:1148 [void zone_manager::deserialize(JsonIn &)] Invalid zone type: LOOT_CLOTHING
08:21:56.637 ERROR : src/clzones.cpp:1148 [void zone_manager::deserialize(JsonIn &)] Invalid zone type: LOOT_FOOD
```

The vehicle zones are on an RV outside the reality bubble, and do not show on this save either with or without this PR applied, and have not been tested.

# Steps to reproduce:

1. Load attached save
2. See the errors thrown
3. Hit 'Y' to show zones
4. Select the option to view remote zones.
5. Observe some of the zones are marked as unknown and have lost their type.

# Expected behavior

Zones on existing saves remain as-is, no errors thrown.

# Versions and configuration

Linux, 134c7d636433e23a5b180924ddf91eda28630e72 (cdda-experimental-2021-06-24-1943) with UndeadPeople tileset applied.

**Comment by actual-nh** [comment] 2021-06-25 00:00
Ping: @schauveau?

**Comment by schauveau** [comment] 2021-06-25 07:29
I can reproduce on his save and also on my current game where I do not have the error but most of the loot zones are missing in the 'add loot' menu. The ones that are still available are the 'special' ones hardcoded in the source file. The prime suspect is of course that my zone reset is somehow removing some loot types.  
The strange thing is that they are still missing after commenting out my reset code and then creating a new game in a new world.

**Comment by schauveau** [comment] 2021-06-25 08:45
I think that I understand. The `zone_manager` reset is called too early before the zone types are loaded from the global json files. The reset must be delayed until after the global json files are loaded (or when leaving a game?). It is probably best to revert by PR until I fix the issue.
I did not see it in my tests because that only happens during the 1st game. If so a temporary workaround could be to create (or load) another game before loading the game with the corruption.

**Comment by Jan-Blasiak** [comment] 2021-06-25 12:47
I have the same thing, ALL of the sort zones were corrupted, and ALL of the sort zones disappeared from the zone menu. Even the custom zone or "unsorted" zone.

**Comment by schauveau** [comment] 2021-06-25 12:58
@Jan-Blasiak  I hope that my pull-request for that issue will be merged soon. Meanwhile, you could try the workaround I mentioned previously. That is: create another game and load it before your real game. That should initialize the loot types and all further games should load properly (until you restart the program).

**Closed** 2021-06-25 23:21 UTC
Labels: <Bug>, Inventory / AIM / Zones
