### ISSUE TITLE
Cooking dehydrated meat with smoking rack cause error message

### ISSUE THREAD

**Issue by WhelpCub** [CleverRaven/Cataclysm-DDA#43098] opened 2020-08-21 14:25 UTC
# Describe the bug

When cooking dehydrated meat and using smoking rack as tool, will display error message.

DEBUG: can't set ammo null in smoking rack as it is not an ammo

FUNCTION: item& item::ammo_set(const itype_id8, int)
FILE: src/item.cpp
LINE: 605

# Steps To Reproduce

1. Construct (*) a smoking rack.
2. Cook (&) dehydrated meat, using smoking rack as tool.

# Versions and configuration

- OS: Windows 10
- Game Version: 0.E-5228-g8731f05 [32-bit]
- Graphics version: Tiles
- Ingame language: Chinese (Traditional)
- Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
C.R.I.T Expansion [crt_expansion],
Magiclysm [magiclysm],
Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
Crazy Cataclysm [crazy_cataclysm],
C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP]
Stats Through Kills [stats_through_kills]
]

**Comment by starytroll** [comment] 2020-08-27 16:08
The problem is more general. Similar thing is the case for other recipes using smoking rack or for the rock forge (https://github.com/CleverRaven/Cataclysm-DDA/issues/42033)

**Comment by wapcaplet** [comment] 2020-09-01 01:02
Confirmed in 0.E-5499-g801b7869d6 - I will look into fixing this.

**Comment by anothersimulacrum** [comment] 2020-11-28 18:58
Fixed in #45414

**Closed by anothersimulacrum** 2020-11-28 18:58 UTC
Labels: (S2 - Confirmed), <Bug>
