### ISSUE TITLE
Picking up items no longer shows how many you have in inventory

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#22027] opened 2017-09-29 16:40 UTC
Windows tiles, appeared in experimental somewhere between 6422 and 6486.

Used to be, when you picked something up that you already had a stock of, like nails, it would say:

You pick up: x nails (y)[z]

Where x is the amount you picked up, y is the amount you already had in your inventory, and z is the letter to which it was assigned.

But now when you pick things up, it says:

You pick up: x nails [z]

**Comment by AncientSion** [comment] 2017-09-29 17:00
Maybe related ?

https://github.com/CleverRaven/Cataclysm-DDA/commit/f1d16830193b8f6af368afb1cb92ea5a18b6e8b3

**Comment by OzoneH3** [comment] 2017-10-03 11:06
Are you sure? I went back in the logs to 2014 and the pickup line hasen't changed since then.

```
You pick up: %d %s [%c]
```

**Comment by BevapDin** [comment] 2017-10-03 14:53
For what it's worth: this was change in 002a44148159d27858adb05751c9bf3f4e9354c7 - the code used to call `item::display_name`, which return a string that contained the charges (if counted by charges, e.g. for nails). After that commit it only calls `item::tname` (which does not include the charges).

@Qrox maybe we should revert that commit?

**Comment by Qrox** [comment] 2017-10-04 08:29
I thought the second number was duplicate of the first number. If it is actually the count in inventory, then I doubt the behavior is intended (IIRC for items not containing charges, no "total count in inventory" is displayed). Anyway, if that change is not desired I totally agree to revert the commit (Or, implement the behavior properly for both items containing charge and not containing charge).

**Comment by BevapDin** [comment] 2017-10-04 15:21
> I thought the second number was duplicate of the first number. If it is actually the count in inventory, then I doubt the behavior is intended (IIRC for items not containing charges, no "total count in inventory" is displayed).

It was the total charges *after* picked items had been added. This seems like a nice to have information.

**Closed** 2017-10-12 21:16 UTC
Labels: Information / Interface, Inventory / AIM
