### ISSUE TITLE
Incapable of installing Full Storage Batteries

### ISSUE THREAD

**Issue by gustavoghe** [CleverRaven/Cataclysm-DDA#38173] opened 2020-02-20 02:11 UTC
# Describe the bug

I cant install storage batteries in vehicles with swappable storage battery case, if the battery is full. If its empty it will accept it.

# Steps To Reproduce

Other people have tried and they are not having trouble. But to reproduce:

1- Start a vehicle from scratch
2 - Install casters
3 - Install Swappable storage case
5 - Try to install Full storage batteries

# Expected behavior

Ideally, we should be able to swap batteries. Empty ones for full ones.

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12390-g06f72d2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    EZ-Mode Medical [fast_healing],
    Craftable EMP grenade [craftEMP]
]

**Comment by wapcaplet** [comment] 2020-02-20 05:37
Sounds like a duplicate of #38148 and fixed by #38146

**Comment by ZhilkinSerg** [comment] 2020-02-20 06:56
You are playing build 10340. Update to build 10343 or above and see that issue is resolved. Report here if it is not.

**Closed by ZhilkinSerg** 2020-02-20 06:56 UTC
