### ISSUE TITLE
Fertilizer Bomb doesn't ever go off.

### ISSUE THREAD

**Issue by Victaria90** [CleverRaven/Cataclysm-DDA#32936] opened 2019-08-05 12:53 UTC
Most recent build.

Explosive - Fertilizer Bomb.

Once lit bomb shows active and 10 turn countdown. The timer only counted down while I was holding the bomb, once I threw it the bomb sat (lit) never exploding. 

The timer of the bomb was the same time from when it was thrown after 1hr of waiting in game.

**Comment by BaumgeistOne** [comment] 2019-08-06 17:47
Happened to me too, with an EMP granade, but only when the granade was not on the same overmap tile as my character.

**Comment by Edgar-cy-Lee** [comment] 2019-08-07 03:03
Sounds like issue is related to #32133. But it was fixed?

**Comment by BaumgeistOne** [comment] 2019-08-07 04:49
Strange. This happened to me just a few days ago, and I am pretty sure that I was not on a version from 24+ days ago, but I can't seem to be able to reproduce it now.

**Comment by jeremyshannon** [comment] 2019-08-07 21:11
Might be a dupe of #32276

**Comment by l29ah** [comment] 2019-08-16 12:28
I've observed the same with an EMP grenade in a lab setting today. After saving and reloading, the grenade detonated.

**Comment by l29ah** [comment] 2019-09-05 03:11
This bug makes ANFO charges useless: they tick only when you're in the blast zone.

**Comment by Nerezza** [comment] 2019-11-06 07:04
I'm here to confirm that as of this latest Jenkins builds this is still a bug. I had this happen during an extensive lab clearing, despite using EMP 4 grenades with no problem before encountering the bug.

**Comment by davidpwbrown** [comment] 2019-11-21 12:09
Can anyone provide a save where this is reproducible? Ive been thowing around fertilizer bombs for ages in-game, and cannot reproduce anymore ( although I know Ive seen it before personally )

**Comment by davidpwbrown** [comment] 2019-11-30 19:26
> Can anyone provide a save where this is reproducible? Ive been thowing around fertilizer bombs for ages in-game, and cannot reproduce anymore ( although I know Ive seen it before personally )

Never mind this actually, a reproducible save is useless, as loading a savegame immediately fixes the issue .. :(

**Closed** 2019-12-11 10:39 UTC
Labels: (S1 - Need confirmation), <Bug>, Items / Item Actions / Item Qualities, Time / Turns / Duration / Date
