### ISSUE TITLE
No low stamina sfx!

### ISSUE THREAD

**Issue by Brody2505** [CleverRaven/Cataclysm-DDA#73619] opened 2024-05-10 06:44 UTC
### Describe the bug

there's no heartbeat/low Stamina sound affects

### Attach save file

[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15270846/Test-trimmed.tar.gz)

### Steps to reproduce

1. run around until your breath gives out. 2. hear no heartbeat/low stamina sfx.

### Expected behavior

I expected there to be low stamina sfx.

### Screenshots

I can't screenshot something you can only hear

### Versions and configuration

OS: Windows 10 - Game Version: [cdda-experimental-2024-05-10-0048 1aca3eb] Graphics: [UltiCa] - Ingame Language: English - Mods: Default 

### Additional context

Im using that weird Kitten CDDA launcher, if that matters

**Comment by EternalLaughter** [comment] 2024-05-10 10:46
Yepp, it's an issue.
Duplicate of #73038

**Comment by GuardianDll** [comment] 2024-05-10 10:50
Closing as duplicate

**Closed by GuardianDll** 2024-05-10 10:50 UTC
Labels: (S1 - Need confirmation)
