### ISSUE TITLE
Getting training from an NPC advances Quest

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20548] opened 2017-03-14 16:58 UTC
If you get a quest from an NPC, and then ask for training, and succeed, you get an error message, and then when you ask the NPC about the job, you get a new job. The quest remains in the quest list, but can't be completed.

**Comment by ynemo** [comment] 2017-03-15 08:58
same here

**Comment by Lazasar** [comment] 2017-05-15 02:31
Error message has gone away, but the behavior remains

**Comment by ZenZen2** [comment] 2017-05-17 08:13
Duplicate of #21027 , the other one has more information.

**Closed by ZenZen2** 2017-05-17 08:14 UTC
Labels: Mission, NPC
