### ISSUE TITLE
Labrador mutts don't want dog food

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#49722] opened 2021-07-07 21:05 UTC
# Describe the bug

So, I just started playing the 0.F stable, and right off the bat, there are four Labrador mutts right outside of the starting shelter. Being that I am not even remotely above using the Debug Menu to save every doggo and kitty I come across, I immediately debug spawned some wet dog food, and went over to on of them and tried to use it to befriend the dog.

... Only, it didn't work. Apparently, "The Labrador mutt doesn't want that kind of food."

I then debug spawned in some dry dog food, and tried that. Same thing. Just to see if it would somehow work, I then tried both types of cat food, and even bird food. None of them have worked.

Just to see how far this problem went, I debug spawned in other dog breeds, and tried the food with them - and it worked! Figuring that maybe it was possible a problem with how the original four Labrador mutts spawned, I debug spawned in another Labrador mutt... and it didn't work on the spawned lab.

So, I thought that maybe it had something to do with the fact that the Labrador mutt was the first dog breed in CDDA, and that became a problem somehow? I tested this by spawning in a shorthair cat, and giving it cat food, and lo and behold, it worked.

I'm now looking in mammal.json, and seeing if maybe there's a problem with the flags on Labrador mutts specifically, and I'm finding absolutely nothing to indicate anything of the sort. They still have the "DOGFOOD" tag, like every other dog breed.

# Steps To Reproduce

1. Find or debug spawn a Labrador mutt
2. Find or debug spawn either wet dog food or dry dog food
3. Try to activate and place the dog food on the Labrador Mutt
4. Watch as the Labrador mutt doesn't become friendly, and read the message log to find that it doesn't want the food
5. Be sad

# Expected behavior

I expect the Labrador mutt to accept the dog food, become friendly so I can put it in a pet carrier, bring it to safety, and release it into a wide, open (but simultaneously walled-off for protection) area to run around in like I did in the save I had in 0.E.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Bootleg Walkers [Bootleg_Walkers],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]

# Additional context

**Comment by ToxiClay** [comment] 2021-07-07 23:23
I cannot reproduce your error. I spawned a Labrador puppy and a Labrador mutt, and fed one type of food to each.
![image](https://user-images.githubusercontent.com/13796683/124840328-b616dd80-df58-11eb-9f25-4ea4d4c52ac9.png)

**Comment by AmarinReyny** [comment] 2021-07-07 23:31
> I cannot reproduce your error. I spawned a Labrador puppy and a Labrador mutt, and fed one type of food to each.
> ![image](https://user-images.githubusercontent.com/13796683/124840328-b616dd80-df58-11eb-9f25-4ea4d4c52ac9.png)

Yeah, someone on Reddit also said that they didn't have the same problem. I'm trying to look through the various files of the mods I'm using, to see if they're causing the issue, but I'm not having any luck with that. I'll try to create new worlds with some of the mods removed, in order to see if I can narrow the problem down to any one mod.

**Comment by ToxiClay** [comment] 2021-07-07 23:33
I've found where the `"doesn't want that kind of food"` message is emitted, though, which might provide clues. If the dog does not have the `food_flag` set, it will emit that message. Gonna try to trace down what conditions cause the flag to not be set.

```
static int feedpet( player &p, monster &mon, item &it, m_flag food_flag, const char *message )
{
    if( mon.has_flag( food_flag ) ) {
        p.add_msg_if_player( m_good, message, mon.get_name() );
        mon.friendly = -1;
        mon.add_effect( effect_pet, 1_turns, true );
        p.consume_charges( it, 1 );
        return 0;
    } else {
        p.add_msg_if_player( _( "The %s doesn't want that kind of food." ), mon.get_name() );
        return 0;
    }
}
```

**Comment by anothersimulacrum** [comment] 2021-07-07 23:34
The `food_flag` is something like `CATTLEFODDER` or `CATFOOD` or `DOGFOOD`.

**Comment by ToxiClay** [comment] 2021-07-07 23:37
Yeah, that function is *only* called by `static cata::optional<int> petfood( player &p, item &it, Petfood animal_food_type )`...

and it seems to be set to `true` if you're feeding the right animal the right kind of food. I imagine if I tried to feed a Labrador puppy cat food, I would get that message.

And lo, I do.
![image](https://user-images.githubusercontent.com/13796683/124841254-d34cab80-df5a-11eb-973b-309d56c9db52.png)

**Comment by ToxiClay** [comment] 2021-07-07 23:39
At a glance, I can't identify any mods in your mod load that scream "I caused this issue." :(

**Comment by AmarinReyny** [comment] 2021-07-07 23:50
> At a glance, I can't identify any mods in your mod load that scream "I caused this issue." :(

Well, I've confirmed one thing so far: it does seem to be caused by a mod. I started with the first of what will probably be quite a few new worlds created for the sole purpose of figuring out where the problem is coming from, and this world had no mods. The labrador mutt I spawned was willing to eat the dog food my survivor gave it in this world. I'll create more worlds to test further, and figure out which mod it is. Thank you for the testing you've done on your end!

**Comment by AmarinReyny** [comment] 2021-07-07 23:55
So, after creating worlds with mods from the aforementioned list added in groups of 5, I've so far narrowed it down to Bootleg Walkers, Gun Cotton, DinoMod, PK's Rebalancing, and Youkai Enemies. I'll now test each one individually to see which mod is causing the problem.

**Comment by AmarinReyny** [comment] 2021-07-07 23:58
It seems to be caused by PK's Rebalancing. Any ideas where I should start with editing files?

**Comment by actual-nh** [comment] 2021-07-08 00:00
Submit an issue report for that mod? Not having it, I have no idea.

**Comment by AmarinReyny** [comment] 2021-07-08 00:00
> Submit an issue report for that mod? Not having it, I have no idea.

Fair enough. I'll do that, now. Thank you for the help!

**Comment by Night-Pryanik** [comment] 2022-02-07 08:26
Since it's caused by a third-party mod, I'm closing this issue.

**Closed by Night-Pryanik** 2022-02-07 08:26 UTC
Labels: Mods, Items: Food / Vitamins, Monsters
