### ISSUE TITLE
Overmap gets stuck moving on a south-east direction. [OS:Android 9]

### ISSUE THREAD

**Issue by cargo94** [CleverRaven/Cataclysm-DDA#33936] opened 2019-09-10 08:47 UTC
# Describe the bug

When using the overmap, using the joystick to pan right and down-right makes it get stuck to the down-right direction, necessitating a game restart to use the map again.

# Steps To Reproduce

1. Spawn in the game
2. (Possibly necessary) Reveal several overmap tiles.
3. Use the movement joystick on the over[m]ap, especially moving towards the right, and lower-right.

# Expected behavior

The map moves only when the command is given via joystick or other means.

# Versions and configuration

- OS: Android
- OS Version: Manufacturer: Xiaomi; Model: Redmi Note 7; Release: 9; Incremental: V10.3.6.0.PFGEUXM; (version of Android 9)
- Game Version: Build 9610 (0.D-7431-g0d20828 [32-bit])
- Graphics Version: Tiles
- Mods loaded: [Dark Days Ahead [dda],
 C.R.I.T Expansion Mod [crt_expansion],
 Aftershock [aftershock],
 Craftable Gun Pack [craftgp],
 DeadLeaves' Fictional Guns [FIC_Weapons],
 Garden Pots [growable-pots], Icecoon's Arsenal [ew_pack],
 Makeshift Items Mod [makeshift], Medieval and Historic Classes and Shields [Medieval_Stuff], More Survival Tools [More_Survival_Tools],
 Mythological Replicas [nw_pack], DinoMod [DinoMod],
 Modular Turrets [modular_turrets],
 Salvaged Robots [Salvaged_Robots],
 Hydroponics [hydroponics], Mutant NPCs [mutant_npcs], Mythical Martial Arts [MMA],
 Beta National Guard Camp [national_guard_camp], More Locations [more_locations], Fuji's More Buildings [FujiStruct],
 Mapgen Demo [mapgen_demo], Urban Development [Urban_Development], Folding Parts pack [deoxymod], Vehicle Additions Pack [blazemod],
 Tanks and Other Vehicles [Tanks],
 Necromancy [necromancy],
 Classes and Scenarios Mod [more_classes_scenarios],
 Classic Roguelike Classes [RL_Classes], Stats Through Skills [StatsThroughSkills]]

# Additional context

The same bug also happens occasionally when [t]rowing grenades, and firing a weapon, rendering those methods of combat unusable until the game is restarted.

Versions in which it happens: build 9591, build 9607, and build 9610. Didn't encounter it in a build downloaded in mid-august.

**Comment by AMurkin** [comment] 2019-09-10 09:20
Cannot reproduce it with the same build on the Xiaomi Redmi 3, Android 5.1.
Is the virtual joystick in the upper left corner for you? Not where you touch a screen.

**Comment by ZhilkinSerg** [comment] 2019-09-10 09:40
Possibly related to #29559

**Comment by cargo94** [comment] 2019-09-10 09:52
The virtual joystick appears where I touch the screen, and functions normally otherwise.

For further details. I haven't encountered the bug with movement or inventory management, only very occassionally when throwing and firing (once that I can remember), and consistently only in overmap. amount of revealed map could have something to do, because I found it to be worse after a long exploration trip, but after reverting the save, it still happens consistently in my terminal.

It also didn't happen once during the lab escape portion of this playthrough, but at the time I was in an older build, from mid-august. This issue started once I was back home and updated.

And while I'm at it, I'll expand on the behavior. It happens only on overmap, and it doesn't transfer to regular play, so it's possible to move, craft, and fight normally after it happens, it's just the overmap that's unusable, as the perspective when opening the overmap again goes extremely quickly in a south-east direction.

**Comment by cargo94** [comment] 2019-09-10 10:20
I also can't reproduce the bug in a remi note 4, seems it's either exclusive to newer android devices, or newer versions of MIUI.

OS details below.

OS Version: Manufacturer: Xiaomi; Model: Redmi Note 4; Release: 7.0; Incremental: V10.2.3.0.NCFMIXM; (version of Android 7)
Game Version: Build 9610 (0.D-7431-g0d20828 [32-bit])

**Comment by Night-Pryanik** [comment] 2022-12-25 04:45
Should be fixed by #42982.

**Closed by Night-Pryanik** 2022-12-25 04:45 UTC
Labels: <Bug>, Info / User Interface, (S2 - Confirmed), Map / Mapgen, SDL: Tiles / Sound, Controls / Input, OS: Android
