### ISSUE TITLE
crash when pick up flower 

### ISSUE THREAD

**Issue by fredaudy** [CleverRaven/Cataclysm-DDA#41251] opened 2020-06-12 15:24 UTC
# Describe the bug

got a "segmentation fault" crash, when i pick up any kind of flower (except dandelion !!!)

# Steps To Reproduce

1- examine a flower (but not a dandelion)
![image](https://user-images.githubusercontent.com/8089058/84518086-71c2fa80-acd0-11ea-8b93-ce4918b97192.png)

2- answer 'yes' to pickup the flower
![image](https://user-images.githubusercontent.com/8089058/84518117-856e6100-acd0-11ea-90fb-b5b7d6862492.png)

then crash
![image](https://user-images.githubusercontent.com/8089058/84518146-8ef7c900-acd0-11ea-858e-c12ddd1ad7db.png)

# Expected behavior

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3104-g67830ad (tiles)
 - Graphics version: Tiles 
 - Ingame language: French
 - Mods loaded: dda

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4771610/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4771611/debug.log)

[testWord.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4771636/testWord.zip)

**Comment by anothersimulacrum** [comment] 2020-06-12 19:25
Duplicate of #41227

**Closed by anothersimulacrum** 2020-06-12 19:25 UTC
Labels: (S3 - Duplicate)
