### ISSUE TITLE
Weapons can lose durability when the attack misses

### ISSUE THREAD

**Issue by ggttttggggtt** [CleverRaven/Cataclysm-DDA#59780] opened 2022-07-31 06:33 UTC
### Describe the bug

When I miss an attack, the weapon can still lose durability.

### Steps to reproduce

1. Make a character with low dex and no melee skill
2. Get a weapon with low to-hit and low durability
3. Fight an enemy with high dodge
4. Eventually one of the misses will still tick down durability

### Expected behavior

Since the weapon is not hitting anything, it shouldn't degrade.

### Screenshots

![image](https://user-images.githubusercontent.com/87790164/182013093-fc74837e-4ce3-47fe-bf9f-239dba6161ba.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 330becb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment] 2022-07-31 06:43
Duplicate of #53527 and #52803.

**Closed by Night-Pryanik** 2022-07-31 06:43 UTC
Labels: (S1 - Need confirmation)
