### ISSUE TITLE
DEBUG:Out of bounds add_vehicle t=none d=90 p=12,-1,0 (Cutting up clothing) (PR 8831)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29866] opened 2019-04-23 16:23 UTC
**Describe the bug**  
 FUNCTION : vehicle* map::add_vehicle(const vproto_id&, const tripoint&, int, int, int, bool)
 FILE     : src/mapgen.cpp
 LINE     : 7164

**To Reproduce**  
Attempting to cut up a stack of clean clothing has a crash-to-black screen with this error. Attached screenshot of layout and nearby vehicle when error occurs.

EDIT: Error disappears temporarily when moving about or performing other actions but appears intermittently, same CTD post clearance.

**Screenshots**  
Attached screenshots of nearby deployed vehicle and stack of clothing attempting to cut up when error occurs.
![clothing stack](https://user-images.githubusercontent.com/43046067/56596903-64741980-65bf-11e9-91e4-fab9438d16d1.png)
![vehicle](https://user-images.githubusercontent.com/43046067/56596921-6b9b2780-65bf-11e9-8dc1-9dfd68f5c96c.png)

**Versions and configuration(please complete the following information):**
PR 8831

[Mutant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3134856/Mutant.zip)

**Comment by l29ah** [comment] 2019-04-25 21:49
Got this as well, i believe when nearby zombies were mauling some wreckages.

**Comment by evankimori** [comment] 2019-04-25 22:18
Could be right. I opened the door of the area I was in at the time and some zeds we're wrecking a vehicle outside now that you mention it. Character is deaf so I didn't hear anything until I did open the door. 

Might be a 'reality bubble' issue you're thinking?

**Comment by HeadstrongCatgirl** [comment] 2019-04-26 19:21
I also am experiencing crashes related to splitting vehicles.

**Comment by neitsa** [comment] 2019-04-27 12:36
Thank you for your bug report! A save file would definitely help for an easier repro.

**Comment by evankimori** [comment] 2019-04-27 12:53
Swore I attached the file. :/ I'll get it done on Monday. My apologies. :(

**Comment by neitsa** [comment] 2019-04-27 13:29
No problem and no rush :+1: :)

**Comment by evankimori** [comment] 2019-05-01 14:58
@neitsa - uploading Savegame now. Save is "Mushroom Dragon" and player is standing in front of problematic stairs when this issue appeared. 2nd save in zip file is normal but error has not appeared for some time.

**Comment by neitsa** [comment] 2019-05-01 15:35
Thanks a lot, that will be really helpful! I'll give it a look before the end of the week.

**Comment by evankimori** [comment] 2019-05-01 15:47
@neitsa - Please keep me informed if you need any additional info or testing from my end! :)

**Comment by neitsa** [comment] 2019-05-02 10:02
I just clicked that we have multiple times the same bug;

Duplicate of #28156

**Comment by ifreund** [comment] 2019-05-02 11:22
>I just clicked that we have multiple times the same bug;

Alright, lets centralize all the discussion there then

**Closed by ifreund** 2019-05-02 11:22 UTC
Labels: <Bug>, <Crash / Freeze>, Mapgen
