### ISSUE TITLE
Large mouth bass (and potentially other fish) yield nonsensically small amounts of meat compared to their weight

### ISSUE THREAD

**Issue by primuspaul** [CleverRaven/Cataclysm-DDA#27333] opened 2018-12-27 05:29 UTC
**Describe the bug**  
Large mouth bass (and potentially other fish) yield nonsensically small amounts of meat compared to their weight

**To Reproduce**  
1. Spawn large mouth bass.
2. Kill large mouth bass.
3. Butcher large mouth bass.

**Expected behavior**  
All butchered corpses should yield proportional substances unless there is a specific reason against this (failure, worthless parts).

**Screenshots**  
N/A
**Versions and configuration(please complete the following information):**
 - OS: Win 7 x64
 - Game Version [from the main menu, e.g. 0.C-35441-ga7f35af]
 - Graphics version [Tiles]
 - Mods loaded [none]

**Comment by anothersimulacrum** [comment] 2018-12-27 05:45
Duplicate of #25751

**Closed** 2018-12-27 06:19 UTC
