### ISSUE TITLE
Instant crash on dropping anything via multidrop. 

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#49222] opened 2021-06-07 22:42 UTC
# Describe the bug

Whenever I drop anything via normal multidrop (by presssing "d"), game instantly crashes.

# Steps To Reproduce

1. press "d"
2. select something to drop and press "enter"
3. the game crashes

# Expected behavior

Drop item(s) instead of crashing the game.

# Screenshots

Last game-state before the crash
![before _multidrop_crash](https://user-images.githubusercontent.com/61312205/121096274-8f02aa00-c7fa-11eb-9c33-8963089c3bb4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 099e4a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Rural-Only Mapgen [ruralbiome],
    Bionic Slots [cbm_slots]
]

# Additional context

Advanced inventory management allows you to drop stuff just fine.
It also works fine if you are prompted to drop an item for some other reason.

**Comment by ZhilkinSerg** [comment] 2021-06-07 23:06
Duplicate of #49050

**Comment by anothersimulacrum** [comment] 2021-06-08 00:05
Your version is before https://github.com/CleverRaven/Cataclysm-DDA/commit/deb761881fc4979db1e87f79289990bfb28f571a , which appears to fix this crash. Please update and if it persists, I will reopen this issue.

**Closed by anothersimulacrum** 2021-06-08 00:05 UTC

**Comment by Tamiore** [comment] 2021-06-08 10:02
@anothersimulacrum 
I've been a bit out of loot as of late.
Where exactly **IS** the latest compiled experimental these days? 
On https://cataclysmdda.org/experimental/ the build I'm getting the crash with is the latest...

**Comment by anothersimulacrum** [comment] 2021-06-08 13:28
https://github.com/CleverRaven/Cataclysm-DDA/releases

**Comment by Tamiore** [comment] 2021-06-08 18:03
Yes, it's fixed in newer experimentals. Thanks.
