### ISSUE TITLE
Crossbow trap bug

### ISSUE THREAD

**Issue by Priapism** [CleverRaven/Cataclysm-DDA#14705] opened 2016-01-04 04:04 UTC
When I create a crossbow trap, it also creates wooden crossbow bolt (0). I'm using a steel crossbow bolt to create the trap, so the empty stack of wooden appear from nowhere.

**Comment by illi-kun** [comment] 2016-01-10 22:14
I accidentally reproduced that bug but only once and I still don't get how to reproduce it accurately.

**Comment by Oskar636** [comment] 2016-11-10 09:59
How did you guys reproduce this?

**Comment by Night-Pryanik** [comment] 2017-03-31 18:34
Can't reproduce on 0.C-6368, Win 10 x64, curses.

**Comment by kevingranade** [comment] 2017-04-01 01:02
Closing until we can get a repeatable reproduction case.

**Closed by kevingranade** 2017-04-01 01:02 UTC
Labels: Bug
