### ISSUE TITLE
different kinds of flour mixed in a bag.

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#44529] opened 2020-09-30 14:25 UTC
# Describe the bug

different kinds of flour mixed in a bag.

# Steps To Reproduce

make flour from starch.
make flour from barley.
put the barley flour into a bag.
put the starch flour into the bag.
see now the bag contains only one stack of flour. it is made from barley and its number is the sum.

# Expected behavior

should be two stack of flour in the bag.
or
cannot put two kinds of powder in one bag.
or
one stack of a kind of mixed/inferior/default flour in the bag.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6389-g6b0ba7e [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    恐龙世界 [DinoMod],
    神话武术 [MMA],
    技能提升属性 [StatsThroughSkills],
    禁用NPC需求 [no_npc_food],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    生化插件槽位 [cbm_slots],
    Fuji的军事职业Mod [fuji_mpp]
]

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-09-30 14:56
Flour made using different recipes is the same item right now.

**Comment by wapcaplet** [comment] 2020-10-01 02:57
We would need to have different kinds of flour before we could have any way to prevent them from mixing together. As ZS said, there is only one kind of flour in the game, no matter what you make it from:

![image](https://user-images.githubusercontent.com/238395/94760324-7125a100-035f-11eb-84a4-64afdea4eba8.png)

I will tag this as a feature request.

**Comment by Qrox** [comment] 2020-10-01 05:19
I guess the problem is not that they mix together, but that the mixed stack takes the components and nutrient values of only one of the source item, causing the nutrient values to effectively change after stacking?

**Comment by lcy03406** [comment] 2020-10-01 05:42
> I guess the problem is not that they mix together, but that the mixed stack takes the components and nutrient values of only one of the source item, causing the nutrient values to effectively change after stacking?

Yes. It is a bug that you can make barley flour (38kcal) from starch as starch flour is 34 kcal.

**Comment by lcy03406** [comment] 2020-10-01 05:48
> We would need to have different kinds of flour before we could have any way to prevent them from mixing together. As ZS said, there is only one kind of flour in the game, no matter what you make it from:
> 
> ![image](https://user-images.githubusercontent.com/238395/94760324-7125a100-035f-11eb-84a4-64afdea4eba8.png)
> 
> I will tag this as a feature request.

It is a bug , not a  feature request.

The game already have the features:
Flour items made from different Ingredients have different properties.
Such different flour items clearly state what they are made from.
They do not stack in inventory.

But here is the BUG:
They do stack up in a bag. I mean a container.

**Comment by lcy03406** [comment] 2020-10-01 12:25
@wapcaplet could you review #44539 ?

**Comment by wapcaplet** [comment] 2020-10-01 20:34
@lcy03406 You are right, I did not realize the recipe results included the different origin materials.

> They do not stack in inventory.
> But here is the BUG:
> They do stack up in a bag. I mean a container.

All inventory (except what you are wearing or wielding) is made up of containers. It appears the flours stack in any container, which means they also stack in inventory, whenever they are in the same container. But I see that they do *not* stack when placed on the ground.

![image](https://user-images.githubusercontent.com/238395/94859963-9d3e3200-03f2-11eb-8a21-cf493606c655.png)

I will take a look at your PR later tonight. Thanks!

**Comment by wapcaplet** [comment] 2020-10-02 01:50
The same phenomenon occurs when picking up and combining "dehydrated fruit" made from different fruits into the same container (like a backpack). Here I have two stacks of dehydrated fruit on the floor, one made from huckleberries, the other from blackberries:

![image](https://user-images.githubusercontent.com/238395/94880053-2ec39900-041f-11eb-8d5b-dbe04d04bba8.png)

When I pick them up, and they combine in my backpack, it's just a stack of 12, only "blackberries":

![image](https://user-images.githubusercontent.com/238395/94880113-56b2fc80-041f-11eb-9a0b-cf91d7701277.png)
![image](https://user-images.githubusercontent.com/238395/94880134-66cadc00-041f-11eb-81d0-63b6d0b21d3b.png)

**Comment by esotericist** [comment] 2020-10-03 12:49
to be clear as to why i put this in the 0.F planning project:

this is an outright regression in behavior compared to 0.E (and i did load up 0.E to verify); you could have multiple types of wheat in the same freshness/temperature band in your inventory without them merging.

![image](https://user-images.githubusercontent.com/1569754/94992036-11d0b800-053c-11eb-891b-0e851a5d5936.png)

these were made with barley and wheat, and they retain their original properties accordingly:
![image](https://media.discordapp.net/attachments/511623330227421184/761931625742729226/unknown.png)

**Comment by wapcaplet** [comment] 2020-10-16 00:35
Fixed by #44539 - tested OK
![image](https://user-images.githubusercontent.com/238395/96199587-1cfcee00-0f15-11eb-9bba-2df007efb3b0.png)

**Closed by wapcaplet** 2020-10-16 00:35 UTC
Labels: (S2 - Confirmed), <Bug>, Crafting / Construction / Recipes
