### ISSUE TITLE
Segmentation fault - random crash when walking around 

### ISSUE THREAD

**Issue by DartDev** [CleverRaven/Cataclysm-DDA#35015] opened 2019-10-25 05:23 UTC
# Describe the bug

The bug is a random crash without a clear cause, but seems to be related to seeing or walking in certain areas of the map. So far happened twice (two reproducible instances) - once inside the Lab and once in the attached save, although the last (current) instance I could only reproduce twice in a row.

# Steps To Reproduce

Steps to reproduce the behavior in the specific attached save:
1. Exit the car towards North and walk around in the vicinity of the car.
2. Crash happens at some random moment.

# Expected behavior

No random crashing.
Because it would be really nice.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8739-g3c1831f
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, More Survival Tools, Makeshift Items Mod, Modular Turrets, Salvaged Robots, Mutant NPCs, Alternative Map Key, Vehicle Additions Pack, Tanks and Other Vehicles, Safe Autodoc, Prevent Zombie Revivication, Classes and Scenarios Mod, Simplified Nutrition, Bionic Slots, More Locations, Fuji's More Buildings, C.R.I.T Expansion Mod, Medieval and Historic Classes, No Fungal Monsters, No Explosive Zombies, DeadLeaves' Fictional Guns.

# Additional context

Save: [segfault1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3770455/segfault1.zip)
Log: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3770450/crash.log)

**Comment by ZhilkinSerg** [comment] 2019-10-25 07:30
Duplicate of #34994

**Closed** 2019-10-25 07:30 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
