### ISSUE TITLE
Character does not use firewood source to keep fire going while standing on the source

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#61340] opened 2022-09-29 00:47 UTC
### Describe the bug

Issue similar to #47008, however is only present while the avatar is standing on the firewood source tile.

### Steps to reproduce

Reproduction steps as per original issue, but have the character stand on the firewood source.

Quoiting #47008:

    Get a brazier, or find a fireplace or oven
    Use the construction menu to mark a firewood source next to it
    Get 2 planks and put them on the firewood source
    Light a fire in the brazier - 1 plank is used to start it
    Wait a couple hours - the fire goes out, with 1 plank still unused in the firewood pile

Using splintered wood is a quicker way to reproduce the issue, since those burn out much faster.

### Expected behavior

Expected avatar to add wood to the fire when necessary to keep it burning regardless of positioning.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: bf9ca7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Dark Days of the Dead [classic_zombies]
]

**Comment by Night-Pryanik** [comment] 2022-09-29 02:49
Duplicate of #42080.

**Closed by Night-Pryanik** 2022-09-29 02:49 UTC
Labels: (S1 - Need confirmation)
