### ISSUE TITLE
Repeatable turn-in quests can be completed infinitely with one set of materials

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13875] opened 2015-11-02 09:39 UTC
For example, the final outpost foreman quest requests 30 sheets of glass. If you give him 30 sheets of glass and then, without leaving conversation, immediately take the same quest, stay in conversation by choosing option a) and then ask "about that job...", you can turn in the quest again, even though you no longer have the required materials. You can repeat this infinitely until you leave conversation.

**Comment by Midaychi** [comment] 2015-11-02 12:24
He also takes 20 sheets instead of 30, btw.

**Comment by ejseto** [comment] 2015-11-02 12:31
No, he takes 30, *btw*. He *asks* for 20 but the mission log says 30 and he won't *accept* 20.

**Comment by Midaychi** [comment] 2015-11-02 12:36
That's weird. When I was doing it, he was asking for 30 and only took 20. 100% sure

**Comment by ejseto** [comment] 2015-11-02 13:04
I tested it before I posted that. Did you?

**Comment by Midaychi** [comment] 2015-11-02 13:46
Ah that's it. The mission is *called* collect 30 glass sheets, but he talks about 20 sheets in the dialogue.

mission.cpp,

return _("Although we are an agricultural outpost, we are restricted to growing plants that are compatible "
                     "with the New England climate during the warmer months.  The easiest way to work around that is to "
                     "build green houses to supplement our external fields.  There isn't going to be an easy way to "
                     "build these, we are going to need a massive number of glass sheets to enclose the frames.  The "
                     "first house will need 20 sheets of glass if you are still interested.");

**Comment by Leland** [comment] 2017-05-08 15:17
Duplicate of #13875. The mission shouldn't be repeatable – that's a bug.

**Closed by Leland** 2017-05-08 15:17 UTC
Labels: Bug, Confirmation Needed, Mission

**Comment by Night-Pryanik** [comment] 2017-05-08 15:23
> Duplicate of #13875.

@Leland you are referencing this issue.

**Comment by Leland** [comment] 2017-05-08 15:27
@Night-Pryanik this is a duplicate of itself, duh. Fixed.
