### ISSUE TITLE
"Halfway down, the way down becomes blocked off" text shows up instead of the usual prompt

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#70809] opened 2024-01-09 21:35 UTC
### Describe the bug

The text popped up whenever i go down (>) while im at the bottom of the stairs. I couldve sworn it used to be just "You cant go down there" text on the log.

### Attach save file

n/A

### Steps to reproduce

1. Stand on a stairs that goes up or (presumably) any terrain that has the GOES_UP flag
2. go down (>)
3. aforementioned text popped up

### Expected behavior

It telling me that you cant go down there.

### Screenshots

![Screenshot_2024-01-10_04-23-57_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/138754a8-f7d7-4308-9fc1-6502959a5d96)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 7b2ac96 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Aftershock [aftershock],
    LuckySlotmachine [luckyslotmachine],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff]
]

**Comment by ZhilkinSerg** [comment] 2024-01-09 21:41
Duplicate of #70802

**Closed** 2024-01-11 04:36 UTC
Labels: (S1 - Need confirmation)
