### ISSUE TITLE
place_loot spawns corpse of corpse

### ISSUE THREAD

**Issue by egomassive** [CleverRaven/Cataclysm-DDA#19670] opened 2016-12-07 16:38 UTC
With this code:
`"place_loot": [
        { "item": "corpse", "x": [ 10, 12 ], "y": [ 5, 7 ], "chance": 50, "repeat": [ 0, 2 ] }
      ]`
I get "human corpse of human corpse" in game. It's putting a corpse inside of another corpse.

**Comment by mugling** [comment] 2016-12-07 16:39
> I get "human corpse of human corpse" in game. It's putting a corpse inside of another corpse.

Not quite - it's just a naming issue

**Comment by DangerNoodle** [comment] 2016-12-07 22:28
I vaguely recall one old placement method also caused this, while another would not. One was 'add' placing corpses directly, while another was 'place_items' citing either the item or a group containing it. At least one of those methods was functional.

Have you tested whether creating an item group containing just a corpse, then spawning it via place_loot, produices this?

**Comment by sethsimon** [comment] 2016-12-08 02:24
I happen to be working on that part of the code, and reproduced it on the first try in master. Even something as simple as this is enough to cause it:
```
"place_loot": [
    { "item": "corpse", "x": 4, "y": 4 }
]
```
But on the branch in #19658, I couldn't reproduce it, whether using the form in this post or the form in the original post.

**Comment by sethsimon** [comment] 2016-12-09 20:58
However, I could reproduce it by searching for "corpse" in the "Debug- wish for an item" menu.

**Comment by codemime** [comment] 2016-12-09 21:22
> However, I could reproduce it by searching for "corpse" in the "Debug- wish for an item" menu.

Yes, the `"corpse"` item appears like this when it's not initialized with species. As pointed out by mugling, it's just a naming issue.

**Comment by codemime** [comment] 2016-12-09 21:26
I'm about to write a quick fix for this.

**Closed** 2016-12-10 22:14 UTC
