### ISSUE TITLE
deploying solar suitcases and then undeploying them ends up duplicating the item.

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#74986] opened 2024-07-12 00:01 UTC
### Describe the bug

if you are to deploy a solar suitcase, and then take it down, you gain an additional solar suitcase.

### Attach save file

N/A

### Steps to reproduce

1: Get a Solar Suitcase.
2: Deploy it.
3: Take it Down.
4: Viola! you now have two solar suitcases!

### Expected behavior

I expected to have only one solar suitcase, not two, unless this is a buy one get one free kinda thing (heehee!)

### Versions and configuration

Latest version of experimental.

**Comment by Void-Seeker** [comment] 2024-07-12 12:50
Duplicate of #73976

**Closed** 2024-07-13 16:08 UTC
Labels: (S1 - Need confirmation)
