### ISSUE TITLE
Z-level problems inside TCL

### ISSUE THREAD

**Issue by remuluson2** [CleverRaven/Cataclysm-DDA#55019] opened 2022-02-02 14:37 UTC
### Describe the bug

There is a problem inside one area of TCL that triggers z-levels to blink you between two levels(without visible change but you can see enemies that aren't near you, fall from ledges which are on a z-level above you).

### Steps to reproduce

1. Spawn in TCL (I dont know if rotation of the zone matters.)
2. Go to research zone, place shown on the screenshot.
3. walk around back and forth in this room
4. you start falling from the ledge

To see non-existent enemies:
1. Go to the recreation rooms with bedrooms upstrairs.
2. walk around the middle of the room and from time to time you can see enemy robots that aren't anywhere near you (not even behind hidden doors

### Expected behavior

Ledges shouldn't trigger when I am on totally different Z-level.
I shouldn't see enemies that aren't on my z-level.

### Screenshots

![image](https://user-images.githubusercontent.com/17945738/152173277-ce11f30c-8793-4f2f-9ae8-6f3319b921b0.png)

In-between the turns I can see enemies in that spot through walls.
It will also interrupt activities as if you seen them.
You can see them in the compass menu.
![image](https://user-images.githubusercontent.com/17945738/152176253-b04191ee-9b98-4b10-b8e0-6343f9c8fb6e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 689dfa5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by ElfLeaderMike** [comment] 2022-02-02 16:54
Confirmed I actually ran into this just yesterday, got a ledge trigger and took a bunch a damage after stepping on one of the tiles in the research area.

**Comment by anoobindisguise** [comment] 2022-02-02 18:51
Anecdotally I have also had an issue with being constantly randomly teleported on the floor with the main armory and the MTF whenever I step near the door to the stairwell. Haven't had the opportunity to reproduce that though.

**Comment by remuluson2** [comment] 2022-02-02 18:57
The same issue strikes again, this time in a random spot between maintenance and living rooms and with absolutely deadly result.
![image](https://user-images.githubusercontent.com/17945738/152219382-0552eca3-bdd8-481b-904d-c096ab76b219.png)

**Comment by coyo7e** [comment] 2022-02-02 22:29
I recall that someone made an issue report about the ceiling lights in TCL labs being so burly that it wrecks vehicles and stuff as well. Might just be that whomever created them missed some basic stuff and it maybe needs to be checked for basic faults like these weird floors and teleportation problems etc.

**Comment by bombasticSlacks** [comment] 2022-02-03 04:19
This is probably caused by a mapgen update and fixed by #55021

**Comment by LeahLuong** [comment] 2022-02-03 04:53
This does resemble the mapgen update errors popping up in other recent threads but what is causing the updates in TCL?? From the reports here, it seems to be trigered by walking on specific tiles. Are those tied to lighting changes or something??

**Comment by bombasticSlacks** [comment] 2022-02-03 04:58
The TCL has mapgen updates to trigger overhead lights and security IIRC

**Comment by ElfLeaderMike** [comment] 2022-02-03 05:16
Managed to find a clip of when it happened to me if the video context helps at all.
[Clip](https://clips.twitch.tv/GracefulGiantBaboonJebaited-KKift2f3R9BLo1ba)

**Comment by remuluson2** [comment] 2022-02-03 10:13
> This does resemble the mapgen update errors popping up in other recent threads but what is causing the updates in TCL?? From the reports here, it seems to be trigered by walking on specific tiles. Are those tied to lighting changes or something??

I do believe it might be areas which trigger trap doors which let out security bots.

**Comment by misterprimus** [comment] 2022-02-24 03:35
Still happening. Attaches save in case anyone wants to test it out
[Temple Terrace.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8129448/Temple.Terrace.zip)
.

**Comment by remuluson2** [comment] 2022-03-29 09:41
Currently testing TCL some more. Seems fine so far but I will give it a few more runs to make sure nothing slips by.

**Comment by andrei8l** [comment] 2022-06-29 08:43
I'm pretty sure I've fixed this properly in #58546. Can anyone please confirm? I'm interested in the vision bug in particular.

**Comment by remuluson2** [comment] 2022-06-29 08:45
I will try to test it this week and we will see.

**Comment by ehughsbaird** [comment] 2022-10-15 16:20
I cannot reproduce either bug on 74abea8db3dd071c52dbf04b9baf71a28301f902.

**Comment by Night-Pryanik** [comment] 2022-10-29 13:34
Can't confirm on 0.F-12178.

**Closed by Night-Pryanik** 2022-10-29 13:34 UTC
Labels: (S1 - Need confirmation), Map / Mapgen, Z-levels
