### ISSUE TITLE
Peeking in a particular basements is working as not intended

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#54357] opened 2022-01-13 11:03 UTC
### Describe the bug

Found a house with a basement which work strange with peeking in it. If I peek in it, it looks like the entrance to it located in the center, while if I actually go there, it looks normal.

### Steps to reproduce

1. Some houses have it, some are not, so I don`t know how to find a specific building with it. Just look for it.
2. Find basement in the house.
2. Try peeking in the downstairs.
3. Actually enter the basement.

### Expected behavior

Peeking and entering must lead to one location, not two different.

### Screenshots

![cataclysm-tiles_njYgZvuz4l](https://user-images.githubusercontent.com/30211338/149318137-5ced2b7d-3c21-4272-bfbb-3cd517117a27.png)
![cataclysm-tiles_hASZRSNz1G](https://user-images.githubusercontent.com/30211338/149318143-f8a84f0e-a990-4bb1-a402-36d4fbef6998.png)
![cataclysm-tiles_rOXLGb4O3r](https://user-images.githubusercontent.com/30211338/149318144-d2081ea1-39ab-4866-bc6c-0ee4380ae0ec.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 73825af [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod]
]

**Comment by GoLoT** [comment] 2022-01-13 11:07
Duplicate of #54076

**Comment by wapcaplet** [comment] 2022-01-14 13:47
There are several very similar issues regarding this bug, but I agree this one looks like a duplicate of #49162 and possibly also #52379 or #54076. I'm closing this one so we have fewer to keep track of.

**Closed by wapcaplet** 2022-01-14 13:48 UTC
