### ISSUE TITLE
CROWS II turret is firing through ballistic glass at me

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#52963] opened 2021-11-22 21:17 UTC
### Describe the bug

I am in a TCL lab and somehow a CROWS II turret is hitting me through ballistic glass. It's doing very little damage to me, but it is hitting me. Not sure if this is intentional or not.

### Steps To Reproduce

1. Load [Roger.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7584444/Roger.zip) as your save file.
2. Observe.

### Expected behavior

The ballistic glass should stop the bullet completely, right?

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/142936510-ff6e3dca-37aa-4eab-bdcd-128640317bf6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e5992d2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ZhilkinSerg** [comment] 2021-11-22 22:25
#33374

**Comment by Photoloss** [comment] 2021-11-22 22:34
If this is the one I think it is the issue isn't really bullets going through glass, but rather that the turret has line of sight (through said glass) of the only terminal which can deactivate it. Player challenges aside that is absolutely ridiculous facility design.

**Comment by Night-Pryanik** [comment] 2021-11-23 04:13
Closing as duplicate.

**Closed by Night-Pryanik** 2021-11-23 04:13 UTC
Labels: Fields / Furniture / Terrain / Traps, Ranged
