### ISSUE TITLE
Refilling containers from vehicle throws "Could not find source vehicle for liquid transfer" error

### ISSUE THREAD

**Issue by Sintua** [CleverRaven/Cataclysm-DDA#24382] opened 2018-07-19 22:51 UTC
Game version:
7586
Operating system:
Windows 10
Tiles or curses:
Chesthole
Mods active:
Many, all from the Launcher listing.
### Expected behavior
Refilling a container with water from the vehicle's kitchen unit should work.
### Actual behavior
![image](https://user-images.githubusercontent.com/11258851/42973564-2b3f58bc-8b79-11e8-8cc0-a3f16be01b47.png)
### Steps to reproduce the behavior
attempt to refill a partial or empty container from a vehicle with a tank full of clean water. Note you can still drink directly from a kitchen unit, but not refill containers.

**Comment by DracoGriffin** [comment] 2018-07-19 22:59
Possible duplicate of #22784 -- if so, need to switch tag to confirmed bug.

**Comment by Sintua** [comment] 2018-07-19 23:31
Looks like it's definitely related, if not just a duplicate.

**Comment by Amariithynar** [comment] 2018-07-21 04:36
Another related error is that trying to refill an empty or partially filled container on the ground from others (for example, wanting to pour all of several bottles bought from a vending machine into a container) throws an error. You keep getting "some items tumble to the ground" followed by "Can't reload the [liquid]". Can freely (U)nload the container on the ground with a liquid into the container you're trying to (r)eload.

**Comment by Night-Pryanik** [comment] 2018-07-21 04:42
Dupe of #22784.

**Closed by Night-Pryanik** 2018-07-21 04:42 UTC
