### ISSUE TITLE
Item health not shown

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#27631] opened 2019-01-15 06:23 UTC
Item health bars/damaged status text not shown.

 - OS: Manjaro Linux 4.19.13-1-MANJARO
 - Game Version: 0.C-36489-g3cec9b8c91
 - Graphics version: Tiles

**Comment by Night-Pryanik** [comment] 2019-01-15 07:19
Could you please provide a screenshot?

**Comment by Quintovir** [comment] 2019-01-15 11:33
- OS: Manjaro Linux 64-bit
 - Game Version 0.C-36458-g59a72789a6-dirty
 - Graphics version Tiles

clothing from zombies and what should be my ++ reinforced_gear_name
<a href="https://postimg.cc/V59fPk23" target="_blank"><img src="https://i.postimg.cc/V59fPk23/clothing-from-zombies.png" alt="clothing-from-zombies"/></a><br/><br/>

freshly pulped zombie corpses
<a href="https://postimg.cc/VdYYfc85" target="_blank"><img src="https://i.postimg.cc/VdYYfc85/freshly-pulped-zombie-corpses.png" alt="freshly-pulped-zombie-corpses"/></a><br/><br/>

**Comment by Barhandar** [comment] 2019-01-15 11:53
You can upload images directly to Github you know.

Can confirm on `0.C-36502-g59a72789a6-dirty`, item names do not show damage, but their descriptions do have the "protection is reduced by damage, you could repair this item" thing.

**Comment by CoroNaut** [comment] 2019-01-15 17:06
Are you sure you have the "Options->Interface->Show item health bars" set to true?

**Comment by Quintovir** [comment] 2019-01-15 18:43
> Are you sure you have the "Options->Interface->Show item health bars" set to true?

Yes.
I even set it for the first time to false to see if anything changed. No change.

**Comment by DavidEdwards** [comment] 2019-01-15 20:38
I can confirm this issue. I compiled the latest version tonight due to Ubuntu ncurses library issues.

I was confused to see my items have no health on them. Item health bars are true in the config.

I walked into a horde of zombies, items registered no damage. I went through them with the welder to repair them. Some needed repairs.

![image](https://user-images.githubusercontent.com/1585923/51208361-c0b70580-190d-11e9-8088-f0cb4093c17f.png)

**Comment by Barhandar** [comment] 2019-01-15 20:42
Okay, so after manually checking the most obvious visual change, 8421 does not have [cleanup of sidebar UI ](https://github.com/CleverRaven/Cataclysm-DDA/commit/76eb7aa0145cb674ecdfc68db1f7f7a3194af68f)yet, while 8422 does, so somewhere around that commit is the breakage.

**Comment by Solusphere** [comment] 2019-01-16 01:03
Just noting that in case this is still needing confirmation, there are quite a few people asking why item health isn't showing on the discord. I'm just showing them this issue for ow.

**Comment by nsklaus** [comment] 2019-01-16 03:21
i think i might be responsible for that.
```
item.h:312 
std::string tname( unsigned int quantity = 1, bool with_prefix = false ) const;
```

**Comment by nsklaus** [comment] 2019-01-16 11:30
just a quick note:
am i supposed to do something about it now that the pull request have been merged ?
what is the usual course of action in this kind of case, beside helping here by pointing the cause of the problem in the sources ?

**Comment by DavidEdwards** [comment] 2019-01-16 11:40
I don't know how it goes in this repository, but usually the person who made the PR originally has "ownership" of the changes. So they make additional PRs to fix bugs relating to it.

Usually this makes sense, because that person understands what changes they made and why they made them.

**Comment by nsklaus** [comment] 2019-01-16 11:55
done: [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/27661/)
@DavidEdwards : thanks for letting me know.

**Closed** 2019-01-16 21:49 UTC
Labels: (S1 - Need confirmation), <Bug>, Info / User Interface
