### ISSUE TITLE
Error: No TURRET an (-3, 1) of Armored Car!

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21766] opened 2017-09-02 01:11 UTC
![noturretonarmoredcar](https://user-images.githubusercontent.com/10506520/29991684-ac2418ae-8f59-11e7-880e-9ef51daa2691.png)

I had just spawned and was running around when this message showed up. I have the tank and vehicle additions mods running so it could be one of them

**Comment by CoroNaut** [comment] 2017-09-02 03:20
This is a thing that happens to me without any mods.

**Comment by ZhilkinSerg** [comment] 2017-09-02 06:37
Duplicate of #17931

**Closed** 2017-09-02 07:00 UTC
Labels: Mods, Vehicle
