### ISSUE TITLE
No morale boost from fun books

### ISSUE THREAD

**Issue by Dansiman** [CleverRaven/Cataclysm-DDA#27557] opened 2019-01-11 20:10 UTC
**Describe the bug**  
Reading books with "Reading this book affects your morale by **X**' actually produces no morale effect.

**To Reproduce**  
1. Read a book with the "Just for fun" descriptor.
2. Check morale screen.
3. The effect from reading the book is not present.

**Expected behavior**  
Morale screen shows a boost from reading the fun book.

**Screenshots**  
![image](https://user-images.githubusercontent.com/19188912/51056770-5ae31a80-15a9-11e9-89e8-dca400257d29.png)
Here, I read the fantasy novel (supposed to improve morale by 4) four times in a row, but got no morale boost from it.

**Versions and configuration(please complete the following information):**
 - OS: Kubuntu 18.10
 - Game Version: 0.C-36170-gddb2ed9
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Filithy Clothing, Simplified Nutrition, Craftable Gun Pack, Safe Autodoc, Bright Nights, DeadLeaves' Fictional Guns, Icecoon's Arsenal, Makeshift Items Mod, More Survival Tools, Mythological Replicas, Alternative Map Key, Crazy Cataclysm, More Locations, Fuji's More Buildings, Oa's Additional Buildings mod, Urban Development, Boats, Folding Parts Pack, Vehicle Additions Pack, (DP_RP) Chesthole Indicators

**Additional context**
This worked correctly in the version of the game that I played previously - 0.C+git20180520.620a1f9 - which was downloaded through the Discover app.

**Comment by swofle** [comment] 2019-01-12 03:31
This issue was fixed in #27522. Build #8399 (9th Jan) and later would have the fix.

**Comment by Night-Pryanik** [comment] 2019-01-12 06:58
Please retest the latest experimental and check if this is still an issue.

**Comment by Inglonias** [comment] 2019-01-12 18:31
Could not reproduce in build 8402. (Version is 0.C-36316-g3dfa1c6 (tiles))

![image](https://user-images.githubusercontent.com/2125926/51077020-5b91b480-166e-11e9-9bc6-1cb2796957a7.png)

**Comment by Night-Pryanik** [comment] 2019-01-12 19:51
I guess this could be closed then.

**Closed by Night-Pryanik** 2019-01-12 19:51 UTC

**Comment by Dansiman** [comment] 2019-01-13 16:12
Sorry, everyone! I tested and confirmed, but I forgot to come back and close the issue. Thanks!
