### ISSUE TITLE
Your total volume is increased when picking up nails as if it's normal, but in fact it's not

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16035] opened 2016-04-03 09:35 UTC
![2222](https://cloud.githubusercontent.com/assets/11132525/14231749/03f239f4-f9a0-11e5-8757-bc8055d7af10.png)
I have some nails in inventory and trying to pick up some more. UI says that after picking them up I'll have 61 volume, but when I look into inventory, UI says that volume is still 60.
This is also the case for some other items that stacks in X (casings, for example).

Win 10 x64, tiles, 0.C-4626.

**Comment by illi-kun** [comment] 2016-04-03 09:40
I guess it's a duplicate of #15728.

**Comment by illi-kun** [comment] 2016-04-16 09:00
Closing as a duplicate.

**Closed by illi-kun** 2016-04-16 09:00 UTC
