### ISSUE TITLE
Cash Cards, Lighters, and Matches in Binary (all-or-none) state

### ISSUE THREAD

**Issue by indigorain** [CleverRaven/Cataclysm-DDA#19237] opened 2016-11-11 06:37 UTC
For the last few builds, I have been updating daily in hopes this issue would be fixed, matches, lighters, and cash cards have yielded either the maximum charges or zero charges. Before a recent update (last 24 hours or so) it was giving me maximum amounts for everything. The first cash card I found had 2 million dollars on it, and I knew at this point I should make clean, git pull, and re make,

0.C-19584-g16a73f3

At this point, lighters and matches dropped from freshly killed Zeds provide full chargers (100/20 respectively) but all cash cards have been completely empty (0).

**Comment by Zireael07** [comment] 2016-11-11 09:41
Duplicate of #16885

**Closed** 2016-11-11 11:01 UTC
