### ISSUE TITLE
weird glitch

### ISSUE THREAD

**Issue by foxymacko-real** [CleverRaven/Cataclysm-DDA#68323] opened 2023-09-25 18:19 UTC
### Describe the bug

Latest Experimental has a very weird bug (25/09/2023)
this doesnt seem to be mod related at all

the bugs gets worser the deeper you go too, if i am in Z level -4 or deeper my character tile sometimes glitches into a portal storm glitch out of nowhere

im bad at explaining, see steps to reproduce instead

### Attach save file

[Bumpus Mills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12718279/Bumpus.Mills.zip)

### Steps to reproduce

steps to reproduce:
press play now (default scenario)
spawn in
go underground or really anywhere that you havent been to (havent seen the area/tiles) in a line for 5-10 tiles
the game lags for a milisec and then
(see screenshots)
a random area/tiles gets revealed infront of you?

### Expected behavior

i expect that random areas/tiles i cant see dont get revealed for me out of nowhere

### Screenshots

![Screenshot_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/79454795/f4120711-62ad-47ed-ab7f-6b60ba603f2e)

### Versions and configuration

OS:win 10
game ver: cdda-windows-tiles-sounds-x64-2023-09-25-1540
tiles
ingame language: english
mods loaded: 
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth"

**Comment by yamil-90** [comment] 2023-09-25 18:58
im having the same problem, it happens a lot when moving diagonally. its like the view changes its origin to a couple of tiles on the direction you are moving for a couple of frames and the area around that point gets revealed, but then it resets to the char point of view (which leaves the revealed area in sepia). it is most noticiable underground where you reveal a solid rock area. 
not sure why this happens 
im using the linux version

**Comment by GuardianDll** [comment] 2023-09-25 19:01
duplicate of #68121

**Comment by foxymacko-real** [comment] 2023-09-25 19:13
> duplicate of #68121

sorry TwT

**Closed** 2023-09-25 21:49 UTC
Labels: (S3 - Duplicate)
