### ISSUE TITLE
Save, Alt+F4 and load bug

### ISSUE THREAD

**Issue by moontheto** [CleverRaven/Cataclysm-DDA#20944] opened 2017-05-04 18:02 UTC
#bug before I die, alt+f4 and load and still alive, but my vehicle or my corpse still there

**Comment by Zireael07** [comment] 2017-05-04 18:11
That's what happens when you attempt to circumvent death.

Duplicate of #12602.

Not a bug.

**Closed by Zireael07** 2017-05-04 18:11 UTC
