### ISSUE TITLE
Cutting a funnel returns more plastic chunk than those used to make it

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#47166] opened 2021-02-01 08:08 UTC
# Describe the bug

Infinite materials from funnels
# Steps To Reproduce

1. Craft a funnel with 3 plastic chunks
![immagine](https://user-images.githubusercontent.com/31773561/106430849-b1f80880-646c-11eb-9516-7be387f92d38.png)
2. Cut the funnel
3. Now you have 12 plastic chunks
![immagine](https://user-images.githubusercontent.com/31773561/106430930-d5bb4e80-646c-11eb-9dc7-7c84d20143d1.png)

# Expected behavior

I expected 3 plastic chunks

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-9311-gc4139e0-dirty
 - Graphics version: Tiles
 - Ingame language: english
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "No_Rail_Stations",
  "No_Fungi",
  "stats_through_kills",
  "speedydex",
  "AftershockUDP",
  "Graphical_Overmap",
  "Graphical_Overmap_SDG"
# Additional context

**Comment by PaulBlay** [comment] 2021-02-01 08:34
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/46801

**Comment by shahezad96** [comment] 2021-02-01 08:45
![funnel_weight](https://user-images.githubusercontent.com/10199441/106434569-bd145e00-6497-11eb-8b27-c2fa10e5303f.JPG)

**Closed** 2021-02-01 15:33 UTC
Labels: (S3 - Duplicate)
