### ISSUE TITLE
Bandaging applies better quality than said

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73336] opened 2024-04-27 18:58 UTC
### Describe the bug

before applying:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/49a32d4f-b56e-432a-a7c6-d026f734ee16)

after:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/9205db50-a76f-4caf-976d-92355e33b535)

It says it will be average, but it will actually be good.

This is a problem, because I might not want to use the bandage, when I don't know what I am getting.

### Attach save file

[Game-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15139522/Game-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. apply `makeshift boiled bandage` from inventory
3. It says it will be average quality when applied on left arm
4. apply
5. Observe the quality is good, not just average

### Expected behavior

It does what it says

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9005-g6700088ca4-dirty [64-bit] master was 2e32db95af
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by casswedson** [comment] 2024-04-27 21:31
probably a duplicate of #64339

**Closed** 2024-04-30 01:14 UTC
Labels: (S1 - Need confirmation)
