### ISSUE TITLE
Bike Rack functionality breaking under some circumstances

### ISSUE THREAD

**Issue by Caiggas** [CleverRaven/Cataclysm-DDA#52005] opened 2021-09-30 17:42 UTC
### Describe the bug

Under certain circumstances vehicles attached by bike racks will permanently become part of the parent vehicle. When this bug triggers it also sometimes causes other bike racks on the same parent vehicle to stop working entirely. 

I have had trouble narrowing down EXACTLY what circumstances trigger the bug, but in the "Steps to Reproduce" section I'll detail the specific method I used. I don't know for sure if entirely different steps will produce the bug as well.

### Steps To Reproduce

1: Make a vehicle with at least 3 adjacent bike racks.
2: Make a single tile vehicle for each bike rack.
_NOTE: For some reason the bug triggers far more consistently if one of these vehicles has a welding rig installed. I do not know why._
3:Attach each single tile vehicle to one of the bike racks such that each single tile vehicle is directly adjacent to each other.
4: Now, unload one of the three vehicles from the bike rack. 
5: Attempt to reload the vehicle you just removed.

Now, if the bug triggers several things will happen:
     A: The bike rack you just used will not work. Nothing will be able to connect to it even though you can interact with it.
     A: One of the other two single tile vehicles will permanently merge with the parent vehicle. If one of them has a welding rig on it then is is always the one that does this. (At least in my testing)
     C: The last bike rack will work as normal.

### Expected behavior

The vehicles should be able to be loaded or unloaded consistently from their bike racks.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bea0650 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

### Additional context

I tried to attach my save, but it wanted a specific file rather than the entire world folder. I guess I don't really understand how to put my save on here. The replication steps work in a fresh world, but I have a save I backed up with my test vehicles already set up and ready to reproduce the bug.

**Comment by PatrikLundell** [comment] 2021-10-01 07:29
This issue has been reported before as #50215, which itself is thought to be a duplicate of #48154.

**Comment by Caiggas** [comment] 2021-10-01 12:14
> This issue has been reported before as #50215, which itself is thought to be a duplicate of #48154.
> 
> To upload a save you need to zip up the folder containing the save/world (not the whole "save" folder containing all the saves) and upload that single file.

I am sorry, I didn't even think to look if it was a previous issue. I know I should have, but I guess I forgot. Should I close this issue so that there is not a duplicate?

**Comment by PatrikLundell** [comment] 2021-10-01 13:04
I'd let the the maintainers decide (or tell you). If you've got a save to go with the reproduction description I'd upload it. The intention with my comment was to make it easier for them to link the different reports together. They haven't closed mine, which is newer than the previous one.

**Comment by ProfoundDarkness** [comment] 2021-10-03 17:41
[Test_BikeRack.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7274239/Test_BikeRack.zip)

From the included save:
1. Examine the nearby bike rack on the vehicle and attach all 3 vehicles to the racks (1 at a time).
2. Now detach the welding rig
3. Now examine the rack and try to attach/remove a vehicle.  Note that the welding rig is no longer an option to attach, one of the carts is an option.  Go ahead and detach the only option.
4. Observe that the cart closest to the player is now permanently connected.

As a variation in step 2 can opt to detach the laundry cart, then when attaching/detaching (step 3) the welding rig is no longer an option to detach.

After some goofing around some I ended up with an error, going to put that up as a separate issue since I don't know if it's relevant.  I'll mention this issue in it just in case it's related.

**Comment by hexagonrecursion** [comment] 2022-01-04 13:32
> From the included save:
> 
>     1. Examine the nearby bike rack on the vehicle and attach all 3 vehicles to the racks (1 at a time).
> 
>     2. Now detach the welding rig
> 
>     3. Now examine the rack and try to attach/remove a vehicle.  Note that the welding rig is no longer an option to attach, one of the carts is an option.  Go ahead and detach the only option.
> 
>     4. Observe that the cart closest to the player is now permanently connected.

Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by wapcaplet** [comment] 2022-01-16 05:57
Closing as duplicate of #48154

**Closed by wapcaplet** 2022-01-16 05:57 UTC
Labels: (S3 - Duplicate), (S2 - Confirmed), Vehicles
