### ISSUE TITLE
``D`` opens the drop menu twice

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#64145] opened 2023-03-11 13:17 UTC
### Describe the bug

As in the title. ``D`` opens the menu twice, and in order to do anything you need to do it... twice. Not necessarily, actually. But to close it you need to close it twice. If you want to drop something you need to select this item twice or select it once and then exit the menu. I have not attempted to select two different sets of items in each menu.

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10948597/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

Press ``D`` and try to drop something. If I am not going insane this should be all.

### Expected behavior

I'd love to not have to do more clicking because that's really annoying

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 4508944 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mqrause** [comment] 2023-03-11 13:19
Duplicate of #64135

**Comment by Karol1223** [comment] 2023-03-11 13:21
Whoops. Didn't see that one, alright, closing this.

**Closed** 2023-03-11 13:21 UTC
Labels: (S1 - Need confirmation)
