### ISSUE TITLE
Weird road mapgen

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22113] opened 2017-10-09 04:06 UTC
![default](https://user-images.githubusercontent.com/11132525/31324922-48538128-acc0-11e7-9453-2575246f780d.png)

**Comment by ZhilkinSerg** [comment] 2017-10-09 04:42
I believe `Necropolis` overmap special was put over existing map tiles and overritten the road.

![default](https://user-images.githubusercontent.com/16213433/31325371-d9a059ea-acc4-11e7-9cc1-2003897c936e.png)

Probably need some road polishing after placing specials with roads or maybe tune connection point settings?

**Comment by vache** [comment] 2017-10-09 04:45
The mapgen roads don't recognize the roads that are a part of the special as "roads", so they don't know they need to connect to them.

**Comment by ZhilkinSerg** [comment] 2017-10-09 06:18
> The mapgen roads don't recognize the roads that are a part of the special as "roads", so they don't know they need to connect to them.

Is it? Ranch and necropolis tiles are defined as road location: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap_locations.json#L57-L67

**Comment by vache** [comment] 2017-10-09 15:21
I think that is only used for placing overmap specials, not for the road connecting.

**Comment by Leland** [comment] 2018-02-19 17:38
Since this is a one-off incident it'll be tough to replicate. Closing.

Have a feeling it's a dupe of #22358, which was fixed in #22723.

**Closed by Leland** 2018-02-19 17:38 UTC
Labels: Mapgen
