### ISSUE TITLE
Broken Follow Sarcophagus Team Mission

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#18348] opened 2016-09-15 02:15 UTC
Windows 7
Playing with Tilesets
Build 5498/0.C-18338-gee310f0 (tiles) according to CDDA Launcher

<a href="http://imgur.com/5V1jRYJ"><img src="http://i.imgur.com/5V1jRYJ.png" title="source: imgur.com" /></a>

The "Follow Sarcophagus Team" doesn't seem completable. You cannot find a military team or anything important to the quest in the bottom the Sarcophagus, just a useless computer, a ton of zombies, and some loot like mutagens.

<a href="http://imgur.com/07gP1vW"><img src="http://i.imgur.com/07gP1vW.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/qwjr654"><img src="http://i.imgur.com/qwjr654.png" title="source: imgur.com" /></a>

Using the "SEAL SCRF" option (Only available on the ground level computer, not the underground one) blows up the entire ground level area of the sarcophagus, but doesn't complete the quest, nor does it actually affect the underground area of the sarcophagus (If you debug teleport into it after exploding everything)

**Comment by illi-kun** [comment] 2016-09-15 19:54
Thanks for the report. I need to note that "Find a Book" part of issue is a dupe of #17630. Please exclude it from the description of current report (and try to avoid merging a few issues in one report in future).

**Comment by Xelat84** [comment] 2018-08-21 06:31
Almost two years later this mission is still broken. May be add it to 0.D or completely remove from game, until it fixed? It looks completely lost.

**Closed** 2021-09-13 10:30 UTC
Labels: <Bug>, (S2 - Confirmed), Missions
