### ISSUE TITLE
Look around cursor does not appear in the center of the game window

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#30514] opened 2019-05-14 17:45 UTC
# Describe the bug

When looking around (';' or 'x' by default), the cursor appears in the upper left corner, rather than starting at the player.

Probably related to #29825.

# Steps To Reproduce

1. Make a character.
2. Press ';' (or whatever your look around binding is)
3. The cursor appears in the upper left. The right panel shows information about the tile in the upper left corner.

# Expected behavior

Yesterday, look around began centered at the player.

# Screenshots

![image](https://user-images.githubusercontent.com/19257672/57719674-4776b780-764e-11e9-9807-77445ffd3448.png)

# Versions and configuration

- OS: Windows 10 [64-bit]
- Game Version: 0.D-2935-g4da9158
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by dom4op** [comment] 2019-05-14 17:46
Yep, same here

**Comment by gr0mazeka** [comment] 2019-05-14 18:17
Yes, same here

**Comment by esotericist** [comment] 2019-05-14 20:49
I'm having a dickens of a time reproducing this. :(

**Comment by esotericist** [comment] 2019-05-14 21:04
Could I have one of you guys throw your `options.json` file up for me?

**Comment by dsmky117** [comment] 2019-05-14 23:27
Pardon my github illiteracy, it doesn't seem to like .json files, so I've uploaded as a .txt.

[options.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3180261/options.txt)

**Comment by esotericist** [comment] 2019-05-14 23:35
> Pardon my github illiteracy, it doesn't seem to like .json files, so I've uploaded as a .txt.
> 
> [options.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3180261/options.txt)

worked well enough. I would have also accepted pastbin or gist.github.com.

aggravatingly, this still isn't enough for me to replicate the problem in my windows VM with the same version of the game as you. :( I was really hoping there'd be something in the config settings that could be at fault.

Out of curiosity, if you try playing the game windowed instead of full screen, does it make a difference?

**Comment by overlord624** [comment] 2019-05-15 01:08
Same problem on Windows 7. No difference between fullscreen and windowed.

I notice that whenever the cursor is activated, it momentarily appears over the character and it's immediately re-positioned at the top leftmost tile.

Setting "Edge Scrolling" in the interface options to disabled will cause the cursor to behave normally.

**Comment by dsmky117** [comment] 2019-05-15 04:46
Yup, went back to normal behavior by changing Settings > Interface > 40: Edge Scrolling (the last option) to disabled.

**Comment by gr0mazeka** [comment] 2019-05-15 05:13
When this option Edge Scrolling is disabled, the cursor works as it should (windows 10 x64).

**Comment by esotericist** [comment] 2019-05-15 20:37
> When this option Edge Scrolling is disabled, the cursor works as it should (windows 10 x64), but flashing does not work on the map

Aghl. I can't reproduce this either.

**Comment by esotericist** [comment] 2019-05-15 20:43
@dsmky117 @dom4op Do either of you have problems with the minimap not cycling with edge scroll disabled?

And @gr0mazeka just to be absolutely sure, you haven't inadvertantly set `Enemy beacon blink speed` to 0 in the Graphics tab, have you?

**Comment by gr0mazeka** [comment] 2019-05-15 20:47
Enemy beacon blink speed = 10

**Comment by esotericist** [comment] 2019-05-15 20:51
This is going to drive me mad. The fact I can't replicate these problems in any of my test rigs makes it exceptionally hard to troubleshoot.

But here's some bonus questions: do you have any difference in the problematic behavior if you change "Renderer"? I know dsmky117 is using direct3d from the provided options file. Do any of you get anything different behavior-wise using "software", "opengl" or "direct3d11" ?

Also do any of you have multiple monitors? If so, does the game behave differently for these issues if it's told to run on a different monitor?

**Comment by gr0mazeka** [comment] 2019-05-15 20:55
render no difference

**Comment by esotericist** [comment] 2019-05-15 20:55
> render no difference

I hate to ask this, but you restarted the game after changing the renderer setting, right?

**Comment by gr0mazeka** [comment] 2019-05-15 20:58
opengl good work

**Comment by dsmky117** [comment] 2019-05-15 21:36
@esotericist I can confirm that my map cursor did stop blinking when I disabled edge scrolling. The cursor "blinks" when I move it. If I hold down a direction, it blinks normally. Pressing a directional key once causes the brackets to appear/disappear.

I tried all of the different renderers (with restarts) and found no difference to the look cursor or minimap blinking issue.

If it helps, I'm on Windows 10.0.17134. I'm using the launcher, but running cataclysm-tiles.exe directly doesn't make a difference.

This might be grasping at straws, but here is my dxdiag results:
![image](https://user-images.githubusercontent.com/19257672/57811154-86346c80-7737-11e9-8890-a2922a7bafd1.png)
![image](https://user-images.githubusercontent.com/19257672/57811190-a19f7780-7737-11e9-81de-e663f6c64c76.png)

**Comment by esotericist** [comment] 2019-05-16 00:09
> I can confirm that my map cursor did stop blinking when I disabled edge scrolling. The cursor "blinks" when I move it. If I hold down a direction, it blinks normally. Pressing a directional key once causes the brackets to appear/disappear.

OH! *overmap* cursor! I thought we were talking about the *minimap* enemy indicator for some reason

Now I have something I can replicate (I see the problem now) and try to fix!!

I still don't understand what's going on with the "look around" cursor for you folks, but I think I can at least fix the cursor blinking problem on the overmap (`m` screen).

**Comment by esotericist** [comment] 2019-05-16 01:06
Silly question: does the cursor you guys see in the top left when you hit `x` to look around... well, move if you move the mouse?

**Comment by overlord624** [comment] 2019-05-16 01:28
> 
> 
> Silly question: does the cursor you guys see in the top left when you hit `x` to look around... well, move if you move the mouse?

Yes, it follows the mouse cursor.

**Comment by esotericist** [comment] 2019-05-16 02:30
Okay. I *might* have found a possible cause of this problem, but I can't be 100% sure, since I still can't reproduce the problem myself. I'll do what I can.

**Comment by gr0mazeka** [comment] 2019-05-16 04:17
build 8972 last one that works correctly for me. https://youtu.be/Ci7IJgbzt4I

**Comment by esotericist** [comment] 2019-05-16 05:02
Yeah, I know which PR introduced the problem, I'm just trying to figure out how to fix it, while
a) not being able to reproduce it myself (and thus know if I've fixed it)
b) not backing out the new features of the PR

**Comment by gr0mazeka** [comment] 2019-05-16 10:41
thanks, it works...

**Comment by esotericist** [comment] 2019-05-16 11:26
To be clear, what works now? 

I'm confident I fixed the map blinking as of build 8989, but since I never managed to replicate the cursor issue, I had to stab at it blindly. Is that fixed as well, with edge scroll enabled?

**Comment by gr0mazeka** [comment] 2019-05-16 11:39
yes

**Comment by dsmky117** [comment] 2019-05-16 13:32
Edge scrolling enabled: The look around cursor appears centered at the player, this appears to be fixed.

Edge scrolling disabled: The overmap cursor blinks normally, also fixed.

**Comment by Night-Pryanik** [comment] 2019-05-16 14:35
Closing then.

**Closed by Night-Pryanik** 2019-05-16 14:35 UTC
Labels: <Bug>, Info / User Interface
