### ISSUE TITLE
Imgui 1.89.6: User cannot resize the first column when ScrollY is enabled.

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#72341] opened 2024-03-12 19:33 UTC
### Describe the bug

With Imgui 1.89.6, user cannot resize the first column when ScrollY is enabled.

See:
https://github.com/ocornut/imgui/issues/6503

It could be fixed by merging new ImGui into CDDA, but I expect that to be a lot of work... Or not @katemonster33? I have no expectation of you fixing this, it is not that important anyway. I just want your estimate.

ImGui was merged just 2 weeks ago in #65709.

### Attach save file

N/A

### Steps to reproduce

See the issue

### Expected behavior

Can resize any column. I can double-click the column for it to find it's smallest possible size.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.G-7935-g210b6c5d63-dirty [64-bit] (actually on master 3ccc5fab00 )
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by katemonster33** [comment] 2024-03-12 22:25
This should be pretty doable. My ImGui branch is here https://github.com/katemonster33/imgui but it needs to be updated and rebased with the latest code from cataclysm. Maybe I could look at this in the next few days

**Comment by katemonster33** [comment] 2024-03-15 15:13
https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 i'm not going to make a PR since I don't have time to do regression testing, but let me know if this behaves any better for you

**Comment by Brambor** [comment] 2024-03-16 09:35
> https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 i'm not going to make a PR since I don't have time to do regression testing, but let me know if this behaves any better for you

This does resolve my issue! I will try to make a concise example soon™

**Comment by Brambor** [comment] 2024-03-16 09:58
I didn't bother making a minimal reproducible example.

I made a branch https://github.com/Brambor/Cataclysm-DDA/tree/imgui-1.90-solve-resize

Which is my project in progress implementing #69831. The last (three) commits should show the difference.

OLD https://github.com/CleverRaven/Cataclysm-DDA/commit/a202e0866077c17ea92a40bdd5bbe6db6d4d55a1 is the broken version.

NEW https://github.com/CleverRaven/Cataclysm-DDA/commit/24adf0bbc7ef0b61c6eb4ff179bd1363332e9e97 is the fixed version.


To reproduce the issue:
1. Compile on one of the commits.
2. Launch the game and load any save.
3. Go to keybindings and look for "Acquire graph" keybinding and bind it to some KEY.
4. Press KEY, it brings up a menu with a table.
5. The table has SEPARATORS as seen in the image.
 ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/d3628f94-fedd-48d6-9f0d-19b95373f985)
6. You can double-click them to resize to optimal size in both versions.
7. In the NEW version you can drag to resize any SEPARATOR.
8. In the OLD version you cannot drag to resize the first SEPARATOR.



The NEW version:
https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/dd2de796-556c-41a3-b910-0d86f3b90318

**Comment by Brambor** [comment] 2024-03-16 11:46
> https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 i'm not going to make a PR since I don't have time to do regression testing, but let me know if this behaves any better for you

Anyway, I like it. I will take it as the ImGui base for now. My project has a long way to go anyway.

**Comment by katemonster33** [comment] 2024-04-15 13:59
@Brambor what is your status on your project? do you need this new ImGui version soon?

**Comment by Brambor** [comment] 2024-04-15 18:26
It will take about month or more, probably.

**Comment by Brambor** [comment] 2024-05-21 21:18
> @Brambor what is your status on your project? do you need this new ImGui version soon?

It would be nice to have. I might change inventory_selector to use ImGui, then resizing could be useful.

**Comment by katemonster33** [comment] 2024-05-23 15:54
ok i can try and update my imgui version then

**Comment by Brambor** [comment] 2024-07-22 00:44
https://github.com/Brambor/Cataclysm-DDA/tree/new-imgui

Merged master and fixed (newly merged) usage of renamed ActivateItemByID

**Comment by Maleclypse** [comment] 2024-11-28 12:12
Fixed by #78144

**Closed by Maleclypse** 2024-11-28 12:12 UTC
Labels: <Bug>, (S1 - Need confirmation), (P4 - Low)
