### ISSUE TITLE
Not seeing tiles where should (only black space)

### ISSUE THREAD

**Issue by WolfhunterHUN** [CleverRaven/Cataclysm-DDA#70365] opened 2023-12-22 21:22 UTC
### Describe the bug

When I zoom in or out, I don't see tiles (black space is shown) previous version I had no such problem (currently playing. When I click X to look around, i see objects highlighted but physically cannot see them. It seems to be when I press X otherwise it loads normally. 

### Attach save file

N/A unfortunately I don't seem to be able to upload this for some reason.

### Steps to reproduce

Zoom in and press X to see this happen again.

### Expected behavior

You should not see outside a small box of vision whatever the case, even though your character can actually see thing there as normal.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68955000/2cad5dd6-0205-4e63-b9e9-84de0260360e)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68955000/35f84745-4e15-4286-9eb1-5a577c1bd722)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68955000/50d0b206-0f1e-4a8d-943d-248b0e3c96c5)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68955000/c6aa76a2-3e62-4b77-abdd-93942a66fa56)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68955000/10a12e9f-d845-4b93-b2a9-0681fe1bfb9f)

### Versions and configuration

2023-12-22-1957

**Comment by NetSysFire** [comment] 2023-12-22 21:28
Duplicate of #70351.

**Closed by NetSysFire** 2023-12-22 21:28 UTC
Labels: (S1 - Need confirmation)
