### ISSUE TITLE
Infinite portal storm in innawood mod

### ISSUE THREAD

**Issue by Yeeeho** [CleverRaven/Cataclysm-DDA#65786] opened 2023-05-21 20:20 UTC
### Describe the bug

 Portal storm is intended to linger around few hours and go away. But in my case, It lasted like it would nerver going to end. The starting message that appears when portal storm first occurs, is temporarily gone when few hours passes. And suddenly I got the Portal storm ending message and the portal storm starting message at the same time. And portal storm goes on. Also 'center of the storm' mission is not ending too.

 I am playing Innawood mod and I wonder this mod is causing the problem. I also saw similar topic in the reddit.

### Attach save file

[Antlus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11525485/Antlus-trimmed.tar.gz)

### Steps to reproduce

1. I save quit the game and loaded the game
2. The portal storm lasted
3. I waited about a day in in-game hour but it lasted anyway
4. It seems like the portal storm is never ending.

### Expected behavior

I expected storm to be ended.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: 35b0807 [64-bit]
- Graphics Version: Tiles
- Game Language: 시스템 언어 []
- Mods loaded: [
    어두운 미래 [dda],
    NPC 욕구 제거 [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    숲 속에서 [innawood],
    공룡 모드 [DinoMod],
    메가파우나 [megafauna],
    괴물 제거 [Only_Wildlife],
    살해 수 반영 능력 성장  [stats_through_kills]
]

**Comment by WreckingAbandon** [comment] 2023-05-22 15:51
Can confirm this.

**Comment by Light-Wave** [comment] 2023-05-22 17:18
Did you update the game after you created the world?

**Comment by WreckingAbandon** [comment] 2023-05-22 17:31
> Did you update the game after you created the world?

If you're asking me then I've only updated now, can't play it yet though due to the startup crash.

**Comment by Light-Wave** [comment] 2023-05-22 18:54
This is a duplicate of #65522. That thread has some workarounds that might work. I would welcome the two of you to post the modlists you use when you encounter this problem in that thread.

**Closed** 2023-06-05 12:55 UTC
Labels: (S1 - Need confirmation)
