### ISSUE TITLE
Get Content from First Aid Kit causes crash

### ISSUE THREAD

**Issue by CrowbarZef** [CleverRaven/Cataclysm-DDA#35692] opened 2019-11-24 05:57 UTC
Game crashes when I "Get content" from a first aid kit on the ground. It works if I'm holding it or it is in my inventory

# Steps To Reproduce

1. Get content
2. Crash

# Expected behavior

The Game not to crash

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9621-g1a06c34 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Filthy Clothing [no_filthy_clothing],
    Stats Through Skills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

CRASH LOG FILE: config/crash.log
VERSION: 0.D-9621-g1a06c34
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D76A5[cataclysm-tiles.exe+0x1D76A5]
    @0x5D8172[cataclysm-tiles.exe+0x1D8172]
    SMPEG_error+0x4B034@0xFCDAD0[cataclysm-tiles.exe+0xBCDAD0]
    _C_specific_handler+0x98@0x7FFD8AD48048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FFD8CC611FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FFD8CC2A289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FFD8CC5FE6E[ntdll.dll+0x9FE6E]
    @0x7D0342[cataclysm-tiles.exe+0x3D0342]
    @0xCC7983[cataclysm-tiles.exe+0x8C7983]
    @0x4B49F3[cataclysm-tiles.exe+0xB49F3]
    @0x4B4B91[cataclysm-tiles.exe+0xB4B91]
    @0x7372F2[cataclysm-tiles.exe+0x3372F2]
    @0x71289D[cataclysm-tiles.exe+0x31289D]
    IMG_LoadWEBP_RW+0x6360CC@0x16F5A0C[cataclysm-tiles.exe+0x12F5A0C]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFD8C767BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFD8CC2CED1[ntdll.dll+0x6CED1]

[Chilson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3883258/Chilson.zip)

**Comment by Funguss** [comment] 2019-11-24 06:01
Duplicate of #35682

**Comment by ZhilkinSerg** [comment] 2019-11-24 06:57
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/35673

**Closed by ZhilkinSerg** 2019-11-24 06:57 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Items / Item Actions / Item Qualities
