### ISSUE TITLE
In progress items disappear when crafting with a table

### ISSUE THREAD

**Issue by sevenandone** [CleverRaven/Cataclysm-DDA#36481] opened 2019-12-27 01:01 UTC
# Describe the bug

Crafting items when next to a table makes the in progress item disappear, making you unable to craft or get the items back.

# Steps To Reproduce

1. Stand next to a table
2. Craft something
3. "You put the in progress [item] (0%) on the table." "You start working on the in progress [item] (0%)." "You no longer have the in progress craft in your possession. You stop crafting. Reactive the in progress craft to continue crafting."

# Expected behavior

In progress item should not disappear when placed on table/workbench.

# Screenshots

![cdda bug](https://user-images.githubusercontent.com/59268981/71495142-50ea1400-281a-11ea-8257-47a776912c54.PNG)

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10660-g5f963d1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Acid Zombies [No_Acid_Zombies],
    No Ants [No_Anthills],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies]
]

**Comment by BenlyAZ** [comment] 2019-12-27 01:16
When I got that I always assumed my dogs were eating whatever I was working on. Was I unfairly blaming the poor beagles?

**Comment by ZhilkinSerg** [comment] 2019-12-27 10:37
Please report game version.

**Comment by BevapDin** [comment] 2019-12-27 12:26
This looks like a side effect of #36407 (the in progress item does not fit on the table). Please check with a current build and report the version.

**Comment by dsmky117** [comment] 2020-01-07 16:20
Could not reproduce on 10137. I'm not sure what else to do without knowing @sevenandone's version/config.

![image](https://user-images.githubusercontent.com/19257672/71910080-39c2f480-313f-11ea-9199-e757a67e4a15.png)

**Comment by ZhilkinSerg** [comment] 2020-01-07 17:07
We'll close it for now then.

**Closed by ZhilkinSerg** 2020-01-07 17:07 UTC
Labels: (S4 - Invalid), <Bug>, Crafting / Construction / Recipes
