### ISSUE TITLE
[Suggestion] Vehicle-deconstruction mechanics requirements need some revising

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#20582] opened 2017-03-18 05:34 UTC
One requires the same level of mechanics to saw a vehicle part off with a hacksaw as one needs to repair it with a welder.  This does not make a lot of sense, and also means salvaging metal from ruined vehicles with a low-level character requires an unnecessary amount of uneducational (and noisy) smashing.

Also, I tried to use jumper cables to start an RV off the battery of an asphalt roller, but was apparently too dumb to know how to take the cables off?  Should at least fix that one.  [Edit: this one just did get fixed (#20550), so nevermind that part.]

**Comment by Salganos** [comment] 2017-03-18 07:19
Hmm, the ":difficulty" values in the json file for each part appear to be one less than the actual requirement in-game.  Is this intended?

**Comment by RightInfinity** [comment] 2017-03-19 02:39
I think the deconstruction requirements are primarily there for complex parts that would be damaged by inexperienced characters. You wouldn't really have the knowledge off the bat to remove a security system without damaging the components of the system and rewiring the car to start without it.

**Comment by Salganos** [comment] 2017-03-19 04:38
The security system makes some sense in that context, but I don't think it makes sense for simple metal boards.  Maybe one should be able to remove most parts with with some damage going between it and the thing its attached to if not skilled enough?  That might even work for the security system (vehicle controls break), but it's a bit more involved.

My main gripe here was the inability to saw already broken parts off of vehicle wrecks to get at the occasionally intact frames beneath them.  I'm not sure even wheels should have their normal requirements if they've already lost all structural integrity.

**Comment by Coolthulhu** [comment] 2017-03-19 04:45
> Maybe one should be able to remove most parts with with some damage going between it and the thing its attached to if not skilled enough?

That would work, but it would require some measure of damage depending on skill.
ie. low skill characters being unable to remove things, mid skill damaging them, mid-high scratching them, high doing no damage. Preferably in such a way that a character who damages something by removing it can't repair it with soldering iron at current skill.

**Comment by Salganos** [comment] 2017-03-19 04:46
There's also a learning angle to this: lengthy vehicle autopsies and dissections should probably be a valid means of getting mechanics xp, as soon as one can cut apart metal without accidentally losing fingers (which, if going by the vehicle frame requirements, is at mechanics 1; should that be higher instead?).

**Comment by Salganos** [comment] 2017-03-19 04:48
Maybe if one can't remove something the game might want to

**Comment by Salganos** [comment] 2017-03-19 04:48
Whoops.

**Comment by Leland** [comment] 2017-05-08 21:18
Duplicate of closed issue #19935, in which quite a few people seemed to feel that removal of parts should still take mechanical/technical skill.

**Closed by Leland** 2017-05-08 21:18 UTC
Labels: Suggestion (Discuss)

**Comment by Salganos** [comment] 2017-05-08 22:38
It's not _quite_ the same issue, but close enough, so okay.

My main problem was with things like boards and frames, which appear to be welded on, and seemingly _sawed_ off.  And those jumper cables.
