### ISSUE TITLE
More Cowboy Problems

### ISSUE THREAD

**Issue by Dendygaar** [CleverRaven/Cataclysm-DDA#40823] opened 2020-05-25 07:39 UTC
Cowboy Reenactor broken, doesn't spawn with revolver (uberti cattleman) anymore, bandolier just says .45 Colt JHP, doesn't hold bullets at all

Spawn as cowboy reenactor class. Any skills or anything will do. 
Description and earlier use of the class reveals it should be using uberti cattleman revolver. This usually spawns in the quick draw holster, and the bandolier usually holds all spare bullets

# Versions and configuration

# Additional context

**Comment by ymber** [comment] 2020-05-25 18:05
Closing as duplicate of #40456.

**Closed by ymber** 2020-05-25 18:05 UTC
