### ISSUE TITLE
Encoding conversion for CJK characters not working correctly

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#49295] opened 2021-06-14 08:47 UTC
# Describe the bug
I was trying to create a new world, but there was no new world created after the "are you sure you're finished" message box. It just return to the mainmenu and that's all. This wasn't happening long time ago, before the long period when I am not playing this game.
After a series of investigation, I found what's suspicious.
My system language is Chinese, so automatically typed in name was Chinese. Seems like there is something wrong about character set. I renamed my world with purely English name, the bug didn't happen again. I then tried with different ASCII compatible names, they were all fine.
Through further digging, eventually I got the code where this fault happens exactly.
In screenshot0, it's shown that due to the enabled setting "ENCODING_CONV", instead of just using orginal UTF-8 encoding, the string was coverted to something else, which couldn't make `assure_dir_exist( folder_path() ) ` true, as shown in screenshot1.
folder_path() is defined as follow:
```
std::string WORLD::folder_path() const
{
    return PATH_INFO::savedir() + utf8_to_native( world_name );
}
```
I turned "Experimental path name encoding conversion" off, world was successfully created and a folder under \save directory was created, but the folder's name is unreadable characters.

# Steps To Reproduce
1. Start the game.
2. Goto World, then Create World.
3. Press Tab three times, then choose yes for the poped up message box.
4. The game returned to main menu with no new world created.
5. Goto settings->options->debug, turn off "Experimental path name encoding conversion"
6. Repeate step 2 and 3.
7. World creation done successfully.

# Expected behavior
There should be a new world created just like how it used to be.

# Screenshots
screenshot0
![屏幕截图 2021-06-14 150220](https://user-images.githubusercontent.com/53336429/121852304-de2c6b80-cd21-11eb-9f93-3ab55378e9c0.jpg)
screenshot1
![屏幕截图 2021-06-14 164505](https://user-images.githubusercontent.com/53336429/121864847-e8556680-cd2f-11eb-9310-367fe945d75c.jpg)

# Versions and configuration
This didn't occur in game so I am writing it manually.
 - OS: Windows 10 Home 21H1
 - Game Version: ca3589f
 - Graphics version: Tiles
 - Ingame language: for the built game I downloaded its Chinese (Simplified), the game built by my visual studio shows English even it has same language setting (system language, the default one), but randomly generated names are in Chinese.

**Comment by actual-nh** [comment] 2021-06-14 12:17
Ping: @BrettDong?

**Comment by BrettDong** [comment] 2021-06-14 13:27
> Ingame language: for the built game I downloaded its Chinese (Simplified), the game built by my visual studio shows English even it has same language setting (system language, the default one),

In regard to this problem, you'll need to compile translation files so the program can load them. If you have Bash and gettext installed then you can run `lang/compile_mo.sh` in repo directory.

**Comment by BrettDong** [comment] 2021-06-19 16:37
I downloaded Windows x64 version from https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-06-19-1321 and cannot reproduce the issue.

When "Experimental path name encoding conversion" is turned on (by default), creating worlds with Chinese characters works normally:
![ON](https://user-images.githubusercontent.com/21075502/122649150-205d0f00-d15f-11eb-94ff-76b6916d26ba.png)

If "Experimental path name encoding conversion" is turned off, after creating a world with Chinese characters in game, the folder actually created in the file system has its name corrupted:
![OFF](https://user-images.githubusercontent.com/21075502/122649189-569a8e80-d15f-11eb-84a3-4cd217a9962e.png)

That is why "Experimental path name encoding conversion" is necessary and is turned on by default.

Operating system is Windows 10 version 1909. System language is Simplified Chinese (China PRC):
![OS](https://user-images.githubusercontent.com/21075502/122649271-a4af9200-d15f-11eb-9dee-245ed833fdb8.png)

**Comment by anothersimulacrum** [comment] 2021-09-15 19:58
No reproduction, and changes in the area since https://github.com/CleverRaven/Cataclysm-DDA/pull/51263 - I'm going to close this unless someone can reproduce it.

**Closed by anothersimulacrum** 2021-09-15 19:58 UTC
Labels: (S1 - Need confirmation), Translation, OS: Windows, Character / World Generation
