### ISSUE TITLE
Can't open windshield curtain with (o)pen command.

### ISSUE THREAD

**Issue by skoormit** [CleverRaven/Cataclysm-DDA#50158] opened 2021-07-23 12:44 UTC
### Describe the bug

I have a vehicle with 3 windshield tiles adjacent to the driver's seat.
Each windshield tile has a curtain installed.
A door is also adjacent to the driver's seat.
The door also has a curtain installed.
The door is not adjacent to any of the windshield tiles.
No other tile adjacent to the driver's seat contains a vehicle part that can be opened or closed.

While in the driver's seat, the (c)lose command shows me 4 selectable tiles--the door tile and all 3 windshield tiles.
This works as expected. Selecting a windshield tile closes all of the windshield curtains. Selecting the door tile closes the door (if the door is open) or the curtain (if the door is already closed).

However, while in the driver's seat, the (o)pen command never gives me the option to open the windshield curtains.
Instead, the (o)pen command will either open the door curtain (if the door curtain is closed) or the door (if the door curtain is open and the door is closed) or will log the message "There is nothing that can be opened nearby" (if the door is already open).

As a result, the only way to open the windshield curtains is to issue a move command in the direction of a windshield tile.
This is a problem for two reasons.
First, I can't issue a move command while driving. I must first let go of the controls.
Second, even after having let go of the controls, if the car is moving, issuing a move command in the direction of a windshield tile will only log the message "That part of the vehicle is currently unsafe."
Which means that the only way to open the windshield curtains is to first bring the vehicle to a stop, then let go of the controls (or stop driving), then issue a move command in the direction of a windshield tile.

### Steps To Reproduce

Put curtains on a windshield.
Move adjacent to the windshield.
Close the curtains.
Try to (o)pen the curtains.

### Expected behavior

I should be able to open windshield curtains with the (o)pen command.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Vendidurt** [comment] 2021-07-23 19:00
I can confirm. When i put curtains on each window, like when i played an albino, sometimes this wont work. I can mitigate it sometimes by driving diagonally and it will then let me pick the correct tile, under some circumstances.
I get around this by installing motors on each curtain, but those get annoying to make and replace every time i run into something.

**Comment by RenechCDDA** [comment] 2023-07-01 12:53
Duplicate of #48276

**Closed by RenechCDDA** 2023-07-01 12:53 UTC
Labels: <Bug>, Vehicles, Controls / Input
