### ISSUE TITLE
Milspec turrets cause game crash

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#31631] opened 2019-06-19 16:30 UTC
# Describe the bug

When this kind of turret tries to shoot in something game crashes

# Steps To Reproduce

1. Find milspec turret
2. Wait till it shoot or just approach it
3. You will get a crash

# Expected behavior

Milspec turret shoots something and dont cause crashes

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-4661-gd23e06a  [#9180]
 - Graphics version: Tiles
 - Mods loaded: Aftershock

# Screenshots
This is what i get when it crashes:
![Screenshot_9](https://user-images.githubusercontent.com/30211338/59783342-9e645200-92c8-11e9-9559-6471cf674250.png)

**Comment by Regularitee** [comment] 2019-06-19 19:18
Duplicate of #31530 ; crashing when a rifle-equipped enemy fires.

**Closed** 2019-06-20 06:46 UTC
Labels: <Crash / Freeze>, Monsters
