### ISSUE TITLE
Clicking on overmap tiles selects the tile to the left instead of the tile being clicked

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#51876] opened 2021-09-25 12:45 UTC
### Describe the bug

When viewing the overmap and clicking on tiles to look at them, instead of centering on the tile being clicked on, it centers on the tile immediately to the left of the tile being clicked on.

### Steps To Reproduce

1. Open the overmap
2. Click on a tile
3. Observe that the tile which is now being centered on is the one immediately to the left of the one you just clicked on
4.  (Optional) Click on the centered tile and observe that the tile to the left of it is now selected

### Expected behavior

I expected that clicking on a tile in the overmap would select that tile, and not the one immediately to the left of it.

### Versions and configuration

- OS: Windows
    - OS Version: Windows 8.1 Pro
- Game Version: ccf5e15 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Gun Cotton [guncotton],
    DinoMod [DinoMod],
    Youkai Enemies [Youkai_Disco],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Compatible Nimian Manufacture Guns [NM_wpns],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    Portable Autodoc [portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters],
    Arcana and Magic Items [Arcana],
    return_the_nut [return_the_nut],
    Hydroponics [hydroponics],
    Cooler Versatility [coolervers],
    Chris K's Knives [ChrisKsKnives],
    Custom Spells [Custom_Spells],
    Reproduction mod [perverts],
    Custom Bionics [custom_bionics],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune],
    Deconstruction Plus [Deconstruction_plus],
    Core Data Changes [core_data_changes],
    Arcadia Mapgen [custom_arcadia_mapgen]

**Comment by ZhilkinSerg** [comment] 2021-09-25 12:46
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50059

**Closed** 2021-09-27 16:21 UTC
Labels: (S3 - Duplicate)
