### ISSUE TITLE
Segfault after [e]xamine any natually spawned vehicle with reactor that has plutonium in it

### ISSUE THREAD

**Issue by MikuMiddo** [CleverRaven/Cataclysm-DDA#41072] opened 2020-06-04 12:38 UTC
# Describe the bug
The game will crash after you examine any natually spawned vehicle with reactor that has plutonium in it.It will also happens when you install a new reactor in vehicle and want you fill it,or empty the cheat spawned vehicle's reactor.

# Steps To Reproduce
There are three ways to reproduce the bug.
First way:
1.cheat spawn a car which has a reactor
2.examine(the game won't crash now) the car
3.empty the reactor
4.examine the car again(now the game will crash)
Second way:
1.cheat spawn a car without a reactor
2.installed it with a reactor
3.examine the car and fill the reactor(now the game will crash)
Third way:
1.find a natually spawned car with reactor and it should has plutonium in it
2.examine it(now the game will crash)

# Expected behavior
The crash should not happen in any sence,shouldn't it?

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2844-gede5ff2 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4729990/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4729991/debug.log)
[TESTVAIL.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4730005/TESTVAIL.zip)

**Comment by anothersimulacrum** [comment] 2020-06-04 14:56
Thanks for the report! Sounds like a duplicate of #40843.

**Closed by anothersimulacrum** 2020-06-04 14:56 UTC
