### ISSUE TITLE
Pointless (?) prompt to stop wielding something when putting an item on

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#45311] opened 2020-11-08 21:36 UTC
# Describe the bug
When wearing an item while you have something in your hands, it will ask if you want to stop wielding your wielded item, if you don't have space to store the thing you are trying to wear in your inventory. You can just press escape to ignore the prompt and wear the item without putting the thing in your hands down, so I don't understand what purpose it has.

# Steps To Reproduce

1. Wield anything.
2. Try to wear an item you can't fit in your inventory.
3. Observe the pointless (?) prompt.

# Expected behavior

To wear the item without being asked if you want to drop the thing in your hands.

# Screenshots

![image](https://user-images.githubusercontent.com/48835780/98484860-56590e80-21e0-11eb-83f3-cb012a88b1ef.png)

# Additional context

I've always wondered what this is about since I started playing with nested inventory. If it's not a bug, and there's some purpose to it (maybe having something wielded slows wearing down? I don't know), then that should be made clearer.

**Comment by anothersimulacrum** [comment] 2020-11-08 22:16
Thanks for the report! Duplicate of #42525
It's either a bug, or we should just ditch the prompt.

**Closed by anothersimulacrum** 2020-11-08 22:16 UTC
