### ISSUE TITLE
Misleading message: car "too heavy" when engines lack fuel/battery

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18983] opened 2016-10-26 21:06 UTC
I'm getting a "your car is too heavy for it's engine" on a 4L v6 Diesel engine when my car is under 3k lbs.

Is this realistic?  I thought an engine like this should be able to drive with quite a bit more weight.

And if this is indeed as it should be, it's not reflected anywhere on the interface, so I have no way of knowing how to compute the actual weight limit.

![image](https://cloud.githubusercontent.com/assets/12039454/19745145/4d43d57c-9b85-11e6-8732-5d726d44644c.png)

**Comment by Xpyder** [comment] 2016-10-26 21:07
also I just realized I have no alternator installed, whoops.  Guess that's why my battery keeps dying.

**Comment by Xpyder** [comment] 2016-10-26 21:13
Yep, seems like it was the battery dying.  So maybe the message for an engine running out of battery should be changed?

**Comment by Coolthulhu** [comment] 2016-10-29 03:48
The problem is just the display, I'll edit the title.

**Comment by mugling** [comment] 2016-11-27 00:23
Should be fixed in `master` - please reopen if reproducible

**Closed by mugling** 2016-11-27 00:23 UTC
Labels: Information / Interface, Vehicle
