### ISSUE TITLE
Anthill generation can overwrite parts of OMT specials, removing stair destinations

### ISSUE THREAD

**Issue by halfahermit** [CleverRaven/Cataclysm-DDA#27195] opened 2018-12-20 15:22 UTC
**Describe the bug**  
If I try to take a one-way downstair, I get a confirmation warning about a "sheer drop". If I take a one-way upstair, there is no warning and I am trapped on the destination level.

One case where this happens: If an ant tunnel is generated over an underground subway station, the subway stairs are apparently overwritten by the ant tunnel's terrain. The tunnel on z=-1 can be entered via subway stairs from z=0 or z=-2, but there is no stairway back up or down, so the player is trapped on z=-1.

**To Reproduce**  
1. Use the map editor to spawn an upstair with no connecting downstair
1b. Or, generate maps until an ant tunnel and subway station exist at the same x,y
2. Use the lower stair

**Expected behavior**  
It seems like a working upstair should always have a connecting downstair. At least, there should be a warning if there's no return stair.

**Versions and configuration(please complete the following information):**
 - OS: OS X 10.13
 - Game Version: 0.C-35084-g22396d2494
 - Graphics version: Tiles
 - Mods loaded: DDA, Tall Buildings, More Locations, Fuji's More Buildings, Dorf Life
 - World settings: z-levels and aligned stairs are both "False"

**Additional context**  
I can link a savefile if it's needed.

Thank you all for the game.

**Comment by Leland** [comment] 2018-12-20 17:34
Could have sworn that there was a previous issue regarding this but my search skills aren't turning up anything. At any rate, if you can provide a save file of a _naturally-occurring_ example of this that would be great.

> Steps to reproduce the behavior:
> * Use the map editor to spawn an upstair with no connecting downstairs

Updating the map editor to automatically place corresponding stairs would be great, but is probably something for another issue

**Comment by halfahermit** [comment] 2018-12-20 21:03
Here's the game where this occurred due to an ant tunnel running through a subway station. The overmap coordinates are -2, 0'114, 0'91. I dug a downstair from z=-1 to -2, and unfortunately don't have a save from before that.

https://www.dropbox.com/s/czuotz3b9dpsxcn/halfahermit_stairs_bug.tar.gz?dl=0

**Comment by Meuka** [comment] 2018-12-20 22:38
Can confirm, this happened to me while trying to go up from a subway up into a city and ended up in an ant tunnel with no way back down. Had to use the debug menu to get back to my cart down in the tunnels.

**Comment by Leland** [comment] 2018-12-21 05:17
Updated title as #27207 has been merged

**Comment by halfahermit** [comment] 2019-02-04 14:15
Another case where downstairs sometimes don't spawn is lab basements.

**Comment by paulenka-aleh** [comment] 2019-04-26 10:45
As for the ants... I's kida odd they're completely overridingthe tile. Assuming giant anhills appeared after all human buildings and tunnels they would rather take tge space over and probably destroy some additional terrain and furniture, probably build something. But it still would be stairs to subway, recognizable basement, sewer tunnel with ant tunnel connection... Don't think though game can support something alike at this stage.

**Comment by esotericist** [comment] 2020-01-04 06:13
@I-am-Erk @kevingranade 

Considering the rather thorough lack of movement on this issue, and the probable invasiveness of likely solutions, and the lack of any actual proposed solutions, do we still think this should be on the list for 0.E?

We're kind of in what looks like the home stretch here, and I'm not seeing a solid plan for how this should be addressed.

**Comment by esotericist** [comment] 2020-01-04 06:24
Went ahead and edited the title to more closely reflect the actual problems being primarily discussed

**Comment by ralreegorganon** [comment] 2020-01-04 06:26
If someone wants to address the ants stomping over existing terrains, they just need to update <https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap.cpp#L3208> to have better checks for acceptable targets.

Right now, it considers it valid as long as it's not already an ant terrain and is inbounds--a trivial check would be to only allow it to place over solid rock (which is basically the empty underground terrain). 

The more sophisticated approach would be to allow it to place over other types and place appropriate (and currently non-existent) overlapping variants (e.g. ant tunnel + subway tunnel), but I think that's a feature and not a bug fix.

**Closed** 2020-01-05 01:38 UTC
Labels: (S2 - Confirmed), <Bug>, Fields / Furniture / Terrain / Traps, Mapgen, Z-levels
