### ISSUE TITLE
NPCs told to wait in a vehicle abandon it after moving away

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23728] opened 2018-05-14 10:24 UTC
Game version: Currently 0.C-27777

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
When an NPC is set to wait/guard a location inside a vehicle, it stays in the vehicle even when the vehicle moves.

### Actual behavior
NPC is drawn to the location of the ground under vehicle.
Should the vehicle move, NPC will jump out - even if it may cause the NPC harm - and run to the spot where the vehicle was.

### Steps to reproduce the behavior
Enter a vehicle with an NPC, tell NPC to stay at the location ("Guard this position"), drive away a bit.

**Comment by ZhilkinSerg** [comment] 2018-05-14 17:42
> When an NPC is set to wait/guard a location inside a vehicle, it stays in the vehicle even when the vehicle moves.

I guess we need `Guard this vehicle` command.

**Comment by FulcrumA** [comment] 2018-05-15 05:37
Frankly, I'd be okay with simply making NPCs to take vehicles into consideration when bound to location - if someone wants NPC to stay in the area and not the vehicle in particular, rarely said vehicle is big enough that you cannot simply order them to stand guard a few tiles away from their current position.

**Comment by Night-Pryanik** [comment] 2018-05-21 17:16
Duplicate of #13782.

**Closed by Night-Pryanik** 2018-05-21 17:16 UTC
Labels: <Enhancement / Feature>, NPC, Vehicles
