### ISSUE TITLE
Liquids inside containers have negative trade value

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#45436] opened 2020-11-15 14:48 UTC
# Describe the bug

When trading with NPCs, if they own a liquid in container, the container's cost is positive but the cost of the liquid inside - which have its own record/line in trade interface (liquid, not cost ;))- is negative.

# Steps To Reproduce

Find an NPC with a can of a drink and try trading.

# Expected behavior

First and foremost, I'm not sure if it applies only to liquids in sealed containers (only observed such) or to any liquid.
If the bug is for sealed containers only then quick fix would be just forbidding selling liquids from inside sealed containers (i.e. remove liquids in such containers from the list).
If it applies to any contained liquid, well... then the cost should be adjusted, I guess?

# Screenshots
![cataclysm-tiles_2020_11_15_21_45_48_535](https://user-images.githubusercontent.com/56833396/99187925-08b64600-278c-11eb-985d-10590ee985d8.png)

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-7557-g64b8950 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ultica cursor replacement [ultest],
    Hauling space revived [hspace]
]

**Comment by thomasrwisneski** [comment] 2020-11-26 02:46
I'm guessing this is due to the following lines in npc.cpp:
`if( it.is_dangerous() || ( it.has_flag( flag_BOMB ) && it.active ) ||
        it.made_of( phase_id::LIQUID ) ) {
        // NPCs won't be interested in buying active explosives or spilled liquids
        return -1000;
    }`

**Comment by kevingranade** [comment] 2020-11-30 13:16
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/saw-voice-i-want-to-play-a-game/25430/3

**Comment by pjf** [comment] 2021-06-25 06:11
This appears to be a duplicate of #43239, but this issue has more information regarding probable cause.

**Comment by wapcaplet** [comment] 2021-11-14 14:35
This still occurs with the new trading UI as well.

**Comment by wapcaplet** [comment] 2021-11-14 14:41
Closing as a duplicate. I have commented on the original with the lines from `npc.cpp` mentioned above where a hard-coded negative value is returned.

**Closed by wapcaplet** 2021-11-14 14:41 UTC
Labels: <Bug>, NPC / Factions, <Exploit>
