### ISSUE TITLE
Excessively long repair times

### ISSUE THREAD

**Issue by wiredhuman** [CleverRaven/Cataclysm-DDA#18677] opened 2016-10-07 12:35 UTC
it took me 2 seasons to dismantle a fifth of an MBT
after a scouting stroll through the offroad I need 3 days to repair my 7x11 vehicle, and thats only the red and missing parts, or 2 hours real time
hitting 1 zombie with a ram at 64km/h puts the entire front part of the vehicle, that is 3 rows of heavy chassis, into yellow or purple

the way it stands vehicles are fragile as glass and doing anything with them that is not slowly driving on the road, that is anything fun, is just not worth the hassle
except the player is ofcourse forced to use vehicles anyway so NOT using vehicles is also out of the question

so please either make the vehicle part more durable or reduce repair times, 4 hours ingame to repair a single part of the vehicle is absolutely excessive

**Comment by Coolthulhu** [comment] 2016-10-07 13:30
Duplicate of #18595

**Closed by Coolthulhu** 2016-10-07 13:30 UTC
