### ISSUE TITLE
(Android) Controls are not working

### ISSUE THREAD

**Issue by Hentilador** [CleverRaven/Cataclysm-DDA#48632] opened 2021-04-24 04:20 UTC
This is on android 11. Any swipe or tap does not work, pressing back still opens keyboard tho.

https://user-images.githubusercontent.com/59157281/115946995-69923900-a4f7-11eb-8def-def17a052954.mp4

**Comment by BrettDong** [comment] 2021-04-24 04:24
* What is your phone model?
* Does the same problem occur on latest experimental version?
* Could you upload `config/debug.log` in the game installation directory (commonly `/Android/Data/com.cleverraven.cataclysmdda`)?

**Comment by Hentilador** [comment] 2021-04-24 04:36
It's a Vivo Y11 (2019) It happens on both stable and experimental. checked the folders and I can't find any debug.log files

**Comment by BrettDong** [comment] 2021-04-24 04:45
Possibly a duplicate of #45876.

**Comment by BrettDong** [comment] 2021-04-24 05:31
Does disabling all accessibility features in phone settings help?

**Comment by Hentilador** [comment] 2021-04-24 06:18
Thank you! I have tried disabling all the accessibility services one by one and the culprit is from an auto clicker app that I use.
Here is a screenshot of the accessibility service
![Screenshot_20210424_141634](https://user-images.githubusercontent.com/59157281/115949475-fd6c0100-a507-11eb-88a7-11e70750194d.jpg)

**Closed** 2021-05-18 22:12 UTC
Labels: (S4 - Invalid), Controls / Input, OS: Android
