### ISSUE TITLE
Slingshot, blowgun, self bow, and sling, unusable

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#15686] opened 2016-03-07 07:11 UTC
0.C-11723-g5c30dca
Jenkins Windows Graphical x64
Windows 10 x64

### When wielding a slingshot and pressing F to fire

If I have no ammo I get "out of ammo"

if I have one type of ammo I get no message

if I have two types of ammo I get an ammo selection screen.  If I make a selection. The selection screen goes away and I am back to square one.
http://imgur.com/EOPfvIM

Turning debug on doesn't give any messages.

**Comment by WizardOfOoo** [comment] 2016-03-07 07:15
With ammo: Tried blowgun and sling, nothing happens when I hit F
No ammo: "out of ammo"

**Comment by mugling** [comment] 2016-03-07 09:47
Can reproduce. It's difficult to test-case due to the interactive nature of the action but I'll look into a fix.

**Comment by NickGrease** [comment] 2016-03-07 13:04
I'm not sure if the Atlatl is a special case, but it does nothing when (f)ired, says it doesn't need to be (r)eloaded, but shows the reload menu if a javlin is on the ground _and_ in my inventory.

**Comment by mugling** [comment] 2016-03-07 13:09
@NickGrease should also be resolved by #15687

**Comment by NickGrease** [comment] 2016-03-07 13:28
Thanks, that did indeed work :)

**Closed** 2016-03-07 16:29 UTC
Labels: Bug
