### ISSUE TITLE
[Bug?] Sometimes all numbers (numpad and number keys) stops responding

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#16713] opened 2016-05-16 18:32 UTC
Version: 0.C-14084-gd5f8f59 (tiles)

Sometimes numbers stops working. I am yet to find what triggers this. (This has been around for a few weeks at least?) It seem to have happened twice when I started driving a vehicle though, cannot 100% confirm it didn't start before it though. 

Workaround: Restart entirely fixes the problem

**Comment by codemime** [comment] 2016-05-16 19:10
What's your OS?

**Comment by Labtop-215** [comment] 2016-05-16 19:37
This could be a shot in the dark, but do you have multiple keyboard layouts?  I live in Canada, and I always install my OS with Canadian multilingual, and I found that sometimes a key combination would change the keyboard layout from U.S. to Canadian Multilingual.  If you have a standard keyboard, it should probably read U.S.

**Comment by mugling** [comment] 2016-05-16 21:02
By any chance did you switch from fullscreen to desktop as this can trigger such a bug...

**Comment by Hague** [comment] 2016-05-16 23:01
I get this sometimes too. I think it happens when I fullscreen a video stream and back and then swap to Cata via alt+tab. It happens very sporadically.

**Comment by harald921** [comment] 2016-05-17 02:58
OS: Windows 10
Languages: Swedish and English
No changes in fullscreen,and no alt tabbing

I will test and report back after my next play session!

**Comment by harald921** [comment] 2016-05-17 03:29
Update: 
Changing language: no effect
Changing between fullscreen and such: no effect
Fullscreening video in the background: no effect, 
Alt Tabbing: no effect

Will be updating if I have any more information

**Comment by DLaboratory** [comment] 2016-06-25 12:25
Can confirm, but not on my current computer.

OS: Windows 7 Ultimate 32-bit with Service Pack 1.
MinGW tiles builds obtained from `dev.narc.ro`.

At some time, all numbers aren't responding. Language is English at the moment. Switch to another application then switch back (`Alt+Tab` twice) can fix the problem. But some moments later, the problem reappears.

But the problem has never appeared on my current computer (Windows 10, Macbook Air).

**Comment by BevapDin** [comment] 2016-06-25 12:43
If it happens again, press the Alt key once (press and release, not together with another key, only the Alt key). Sometimes the game does not recognize the Alt key was released and thinks it's still hold down. And in that state you can enter Unicode characters directly via their number on the number pad - this prevents the normal behavior of the key pad.

**Comment by Leland** [comment] 2017-05-04 14:27
Closing due to no validation or updates in about a year. Feel free to let me know if this needs to be reopened if anyone _does_ reproduce this – or just make a new issue.

**Comment by sTiKyt** [comment] 2021-04-27 16:02
Issue still there

**Comment by actual-nh** [comment] 2021-04-27 21:08
> Issue still there

What OS and version? Thanks!

**Comment by sTiKyt** [comment] 2021-04-29 21:10
@actual-nh latest stable (cataclysm-dda 0.E.3)
Arch Linux

**Comment by actual-nh** [comment] 2021-04-29 21:12
Linux? Odd; I'm not sure if it's the same bug, then.

**Comment by sTiKyt** [comment] 2021-05-01 12:52
It was NumLock #facepalm
epic fail to be honest, but i don't have any indicators for that so i didn't even think about it, you can close it...

**Closed** 2021-05-01 14:01 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Info / User Interface
