### ISSUE TITLE
NPC no longer can doing constraction while player on different Z-level

### ISSUE THREAD

**Issue by nik-ovchin** [CleverRaven/Cataclysm-DDA#59245] opened 2022-07-13 22:10 UTC
### Describe the bug

My companion unable to find unfinished construction while main character underground. When I go out from cave he continue working.

### Steps to reproduce

1. Give NPC task
2. Ensure what he begin it
3. Go to undeground cave (maybe roof of shelter in standart start)
4. See spam in log about unable to find unfinished construction
5. Go back to NPC
6. See that NPC continue working

### Expected behavior

Yesterday it was working fine.
Maybe #59187 related?

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 704a963 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment] 2022-07-13 22:16
Potential fix:
```diff
diff --git a/src/map.cpp b/src/map.cpp
index 8578f8732d..cf09d64cce 100644
--- a/src/map.cpp
+++ b/src/map.cpp
@@ -8673,7 +8673,7 @@ tripoint map::getabs( const tripoint &p ) const
 
 tripoint map::getabs( const tripoint_bub_ms &p ) const
 {
-    return ( project_to<coords::ms>( abs_sub ) + p.raw() ).raw();
+    return ( project_to<coords::ms>( abs_sub ).xy() + p.raw() ).raw();
 }
 
 tripoint_abs_ms map::getglobal( const tripoint &p ) const
@@ -8706,7 +8706,7 @@ tripoint_bub_ms map::bub_from_abs( const tripoint &p ) const
 
 tripoint_bub_ms map::bub_from_abs( const tripoint_abs_ms &p ) const
 {
-    return tripoint_bub_ms() + ( p - project_to<coords::ms>( abs_sub ) );
+    return tripoint_bub_ms() + ( p - project_to<coords::ms>( abs_sub ).xy() );
 }
 
 void map::set_abs_sub( const tripoint_abs_sm &p )
```

**Comment by Stadler76** [comment] 2022-07-14 00:34
That's a duplicate of #59242

**Comment by jbytheway** [comment] 2022-07-14 01:12
> Potential fix:

Thanks; that fix looks very promising.  I totally forgot that `abs_sub` has a z coordinate when I was writing that code.

**Closed** 2022-07-14 17:32 UTC
Labels: (S1 - Need confirmation)
