### ISSUE TITLE
stratoscomm relay station roof (aftershock)

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61002] opened 2022-09-14 15:51 UTC
### Describe the bug

apparently the roof of the relay was not designed properly (see image)

### Steps to reproduce

teleport yourself to the roof of any stratoscomm relay station.

### Expected behavior

there not being grass tiles above everything

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/190201717-2e84c60a-8fd5-4914-97b3-4408aaf96369.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: aa80ff7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    No Hope [no_hope]
]

**Comment by NetSysFire** [comment] 2022-09-14 16:39
Duplicate of #60470

**Closed by NetSysFire** 2022-09-14 16:39 UTC
Labels: (S1 - Need confirmation)
