### ISSUE TITLE
Chopping tree down breaks walls in underground z-levels

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#34170] opened 2019-09-22 09:54 UTC
# Describe the bug

Chopping down a tree breaks walls (and presumably anything else destroyable by falling trees) that are underground.

# Steps To Reproduce

1. Make sure experimental z-levels are on.
2. Fell tree next to LMOE shelter.
3. "From the northwest and below you hear metal screeching!"
4. Go down stairs to find destroyed metal wall.

# Expected behavior

Felling trees above ground shouldn't destroy metal walls below ground.
I would assume the reason why this is working like this is because certain kinds of building destruction go through z-levels, and this is perhaps an unintended consequence of that?

# Screenshots

![1](https://user-images.githubusercontent.com/35230199/65385355-c62ee000-dd25-11e9-95c9-ca3fbd3d9bc4.png)
![2](https://user-images.githubusercontent.com/35230199/65385357-c7f8a380-dd25-11e9-971d-e12f49b0fdb6.png)
![3](https://user-images.githubusercontent.com/35230199/65385360-c929d080-dd25-11e9-8ba6-28e952d4ca3c.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7542-ga5d33f6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Hair aka Rainbow [Hairs]
]

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3639581/save.zip)

Note: Ignore the bio-operator in the cage, he's z-slaved. The shocker is not though, but I lured him down into the room below, so just don't open that particular door.

**Comment by ZhilkinSerg** [comment] 2019-09-22 12:07
Duplicate of #14117

**Closed by ZhilkinSerg** 2019-09-22 12:07 UTC
