### ISSUE TITLE
Sewing kit takes thread when reloaded but does not get any new charges.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#40156] opened 2020-05-04 22:18 UTC
# Describe the bug
I tried to reload my sewing kit in the new experimental but the charges seem to have vanished to a distant land, perhaps all the way to nevada. This happened with sinew and after making new thread as well. 

Trying to unload didn't yield the items.
I couldn't use it after this problem, but i could before.

# Steps To Reproduce
1. Try to reload items who use charges.
2. Get disappointed.

It is very similar to #40152

**Comment by FuelType-Memes** [comment] 2020-05-04 22:25
Might be a duplicate of #40125

**Comment by romanpogosov-usa** [comment] 2020-05-05 05:44
duplicate of 40125

**Comment by lbnesquik** [comment] 2020-05-05 11:35
We could maybe close it given how similar it is, or leave it for visibility given 'big' of a problem it is.

**Comment by ZhilkinSerg** [comment] 2020-05-07 16:58
Duplicate of #40125

**Closed by ZhilkinSerg** 2020-05-07 16:58 UTC
Labels: (S3 - Duplicate)
