### ISSUE TITLE
Game crashes while talking with the scrapper

### ISSUE THREAD

**Issue by AColtre** [CleverRaven/Cataclysm-DDA#68421] opened 2023-09-30 18:15 UTC
### Describe the bug

Game crashed with the message "SIGSEGV: Segmentation fault" after talking with the scrapper NPC. i'm attaching a screenshot and the log file

### Attach save file

[Saint Francis.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12775293/Saint.Francis.zip)

### Steps to reproduce

1. talk to scrapper
2. ask to trade
3. when he asks: anything else? select option b

### Expected behavior

continuation of dialogue?

### Screenshots

![crash](https://github.com/CleverRaven/Cataclysm-DDA/assets/66138747/bf811042-aff3-4eb0-9788-f0ff7db2baab)

### Versions and configuration

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12775295/config.zip)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12775296/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12775297/debug.log)

**Comment by gettingusedto** [comment] 2023-09-30 18:18
Duplicate of #68346

**Comment by oosyrag** [comment] 2023-10-01 16:07
Thanks for the report, it will be investigated as part of the existing issue.

**Closed by oosyrag** 2023-10-01 16:07 UTC
Labels: (S1 - Need confirmation)
