### ISSUE TITLE
Ranged targeting not attacking selected target

### ISSUE THREAD

**Issue by Nanothaniel** [CleverRaven/Cataclysm-DDA#17811] opened 2016-07-27 01:07 UTC
Playing on version 5300 when there are multiple enemies the game often directs my shot towards an enemy other than the one I selected. Also, on subsequent shots it frequently selects a target other than the one I selected the previous turn. It seems more likely to occur when I have allies nearby, for example I was trying to shoot a zombie near an allied NPC and instead my shots fired in the exact opposite direction at a zombie approaching from behind.

**Comment by Zireael07** [comment] 2016-07-27 13:41
Aha, I think I am experiencing the same. Two Zs in sight, wasted 50+ pebbles trying to hit one of them with a sling, throwing level 8 :/

**Comment by mugling** [comment] 2016-07-30 11:33
Can you determine the specific steps to reproduce and I'll look into this

**Comment by Zireael07** [comment] 2016-07-30 12:12
1) Have more than one target on screen, press f to fire, press enter. (I don't use aiming at all since my skill is so high) 

2) See the shot anim going in a wildly different direction to expected.

**Comment by mugling** [comment] 2016-07-30 12:19
I'm going to merge  #17848 as it's a one-line fix for a segfault bug @Coolthulhu marked as `priority`. Once Jenkins has rebuilt can you confirm if this bug persists?

**Comment by Zireael07** [comment] 2016-07-30 13:27
I am not able to update for the next week, sorry (sucky net and not my computer - I play from an USB drive)

**Comment by woutershep** [comment] 2016-08-03 12:09
Seems to still be present as of today. (1081de303000b0524756f0bb28796ad0ba03e3c3). Atleast i think it just happened shooting my accurized fusion blaster rifle at a enemy, a second enemy was out of range and it shot and exploded at the maximum range in that direction instead of hitting the target.

**Comment by Nanothaniel** [comment] 2016-08-04 02:46
I've had it happen a few more times since updating. Every time it occurs I have selected a target other than the one it defaults to, after firing the shots go towards the default target even if it's 180 degrees away from where I meant to aim. It doesn't happen every time, but maybe 10%. Sometimes when the glitch occurs I see the targetting square blipping about rapidly over several squares after firing as if it's trying to locate a target.

**Comment by mugling** [comment] 2016-08-11 12:07
Still exists in `master`

**Closed** 2016-08-20 10:31 UTC
Labels: validated
