### ISSUE TITLE
segfault on loading game/starting new game

### ISSUE THREAD

**Issue by eskoONE** [CleverRaven/Cataclysm-DDA#52012] opened 2021-09-30 22:48 UTC
### Describe the bug

game crashed on loading or starting a new game. 

the windows version wasnt building after version 1513 for a day or two. since the windows builds are back, im getting a seg fault.

here is the log

```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: c4a7f2e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x6fab16[cataclysm-tiles.exe+0x2fab16]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x56@0x6fab16),
    (libbacktrace: 0x6fab16    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6d2ce6[cataclysm-tiles.exe+0x2d2ce6]), 
    (libbacktrace: log_crash+0x526@0x6d2ce6),
    (libbacktrace: 0x6d2ce6    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6d4002[cataclysm-tiles.exe+0x2d4002]), 
    (libbacktrace: signal_handler+0x32@0x6d4002),
    (libbacktrace: 0x6d4002    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x137efc0[cataclysm-tiles.exe+0xf7efc0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x137efc0),
    (libbacktrace: 0x137efc0    /usr/lib/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.5.0.build_/mingw-w64-v8.0.0/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff898a87ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ff8999f20cf[ntdll.dll+0xa20cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ff8999a1454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff8999f0bfe[ntdll.dll+0xa0bfe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x1b11940[cataclysm-tiles.exe+0x1711940]), 
    (libbacktrace: std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x50@0x1b11940),
    (libbacktrace: 0x1b11940    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0xb19e9d[cataclysm-tiles.exe+0x719e9d]), 
    (libbacktrace: JsonObject::verify_position(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const+0x1d@0xb19e9d),
    (libbacktrace: 0xb19e9d    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0xb1e82f[cataclysm-tiles.exe+0x71e82f]), 
    (libbacktrace: JsonObject::get_array(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x1f@0xb1e82f),
    (libbacktrace: 0xb1e82f    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x1293ded[cataclysm-tiles.exe+0xe93ded]), 
    (libbacktrace: weakpoint::load(JsonObject const&)+0x4dd@0x1293ded),
    (libbacktrace: 0x1293ded    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x1295b34[cataclysm-tiles.exe+0xe95b34]), 
    (libbacktrace: weakpoints::load(JsonArray const&)+0x364@0x1295b34),
    (libbacktrace: 0x1295b34    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0xd7f6a0[cataclysm-tiles.exe+0x97f6a0]), 
    (libbacktrace: mtype::load(JsonObject const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe80@0xd7f6a0),
    (libbacktrace: 0xd7f6a0    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x1809c5e[cataclysm-tiles.exe+0x1409c5e]), 
    (libbacktrace: generic_factory<mtype>::load(JsonObject const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xfe@0x1809c5e),
    (libbacktrace: 0x1809c5e    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x923b21[cataclysm-tiles.exe+0x523b21]), 
    (libbacktrace: DynamicDataLoader::load_object(JsonObject const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x161@0x923b21),
    (libbacktrace: 0x923b21    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x92a7e6[cataclysm-tiles.exe+0x52a7e6]), 
    (libbacktrace: DynamicDataLoader::load_all_from_json(JsonIn&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, loading_ui&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x186@0x92a7e6),
    (libbacktrace: 0x92a7e6    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x92ac46[cataclysm-tiles.exe+0x52ac46]), 
    (libbacktrace: DynamicDataLoader::load_data_from_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, loading_ui&)+0x326@0x92ac46),
    (libbacktrace: 0x92ac46    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x82851f[cataclysm-tiles.exe+0x42851f]), 
    (libbacktrace: game::load_packs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<string_id<MOD_INFORMATION>, std::allocator<string_id<MOD_INFORMATION> > > const&, loading_ui&)+0x25f@0x82851f),
    (libbacktrace: 0x82851f    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x828e76[cataclysm-tiles.exe+0x428e76]), 
    (libbacktrace: game::load_world_modfiles(loading_ui&)+0x2a6@0x828e76),
    (libbacktrace: 0x828e76    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x859b76[cataclysm-tiles.exe+0x459b76]), 
    (libbacktrace: game::setup()+0xc6@0x859b76),
    (libbacktrace: 0x859b76    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0xb7a220[cataclysm-tiles.exe+0x77a220]), 
    (libbacktrace: main_menu::new_character_tab()+0xd40@0xb7a220),
    (libbacktrace: 0xb7a220    [unknown src]:0    [unknown func]),
  #22
    (dbghelp: @0xb810a5[cataclysm-tiles.exe+0x7810a5]), 
    (libbacktrace: main_menu::opening_screen()+0xe85@0xb810a5),
    (libbacktrace: 0xb810a5    [unknown src]:0    [unknown func]),
  #23
    (dbghelp: @0x1f25489[cataclysm-tiles.exe+0x1b25489]), 
    (libbacktrace: main+0x1679@0x1f25489),
    (libbacktrace: 0x1f25489    [unknown src]:0    [unknown func]),
  #24
    (dbghelp: @0x4013bd[cataclysm-tiles.exe+0x13bd]), 
    (libbacktrace: _tmainCRTStartup+0x22d@0x4013bd),
    (libbacktrace: 0x4013bd    /usr/lib/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.5.0.build_/mingw-w64-v8.0.0/mingw-w64-crt/crt/crtexe.c:335    __tmainCRTStartup),
  #25
    (dbghelp: @0x4014c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x4014c6),
    (libbacktrace: 0x4014c6    /usr/lib/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.5.0.build_/mingw-w64-v8.0.0/mingw-w64-crt/crt/crtexe.c:188    WinMainCRTStartup),
  #26
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff8995d7034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #27
    (dbghelp: RtlUserThreadStart+0x21@0x7ff8999a2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
```

### Steps To Reproduce

start up game. load or start a new game.

### Expected behavior

game to start without a segfault.

### Screenshots

https://i.imgur.com/EWhFnCt.png

### Versions and configuration

os: win10
game version: 2123

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7262900/crash.log)

**Comment by ZhilkinSerg** [comment] 2021-09-30 23:47
Duplicate of #51991

**Comment by BrettDong** [comment] 2021-10-01 02:03
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2021-09-30-2338

**Closed** 2021-10-01 02:04 UTC
