### ISSUE TITLE
Vehicle collides with errors in movement code

### ISSUE THREAD

**Issue by Vane79** [CleverRaven/Cataclysm-DDA#23000] opened 2018-02-20 06:59 UTC
Game version: Build 7126

Operating system: Win 10 x64

Mods active: folding parts pack
 
2-tiles foldable bike
![cataclysm-tiles_2018-02-20_13-57-06](https://user-images.githubusercontent.com/36656584/36410918-f38410fa-1645-11e8-860e-a0605a9c55c1.png)
![cataclysm-tiles_2018-02-20_13-57-01](https://user-images.githubusercontent.com/36656584/36410919-f3a8d958-1645-11e8-85ff-2ab49a7fd44a.png)

### Steps to reproduce the behavior

Bike wielded
![cataclysm-tiles_2018-02-20_13-55-19](https://user-images.githubusercontent.com/36656584/36410937-1007ae6c-1646-11e8-9ce1-31ca5a944081.png)
Shift+A to unfold
![cataclysm-tiles_2018-02-20_13-55-31](https://user-images.githubusercontent.com/36656584/36410938-102c0104-1646-11e8-8b64-07225c63e391.png)
Grab tile to the left
![cataclysm-tiles_2018-02-20_13-55-38](https://user-images.githubusercontent.com/36656584/36410939-1056db90-1646-11e8-9283-080fdcb1d1ae.png)
Move one tile to the right
![cataclysm-tiles_2018-02-20_13-55-46](https://user-images.githubusercontent.com/36656584/36410940-107a9094-1646-11e8-9799-35ea0bd50d49.png)
Move one tile to the left
![cataclysm-tiles_2018-02-20_13-55-51](https://user-images.githubusercontent.com/36656584/36410941-109e2626-1646-11e8-82e9-aad0d06fdb79.png)

To clarify - I can't move through the basket. If I may guess, character tries to push it, and vehicle flips funnily.

**Comment by Night-Pryanik** [comment] 2018-02-20 16:08
Duplicate of #20640, though this one has better steps to reproduce.

**Comment by sniperm13** [comment] 2018-02-21 20:04
Havent run into this problem since build 7040. Based on your screenshot, you grabbed the saddle which is likely the cause for the error since it cant flip the vehicle since the character is too far from the 'front' of the bike...

**Comment by Feniks-Gaming** [comment] 2019-08-23 17:54
![bike](https://user-images.githubusercontent.com/30668026/63612906-58cd4980-c5d7-11e9-9a04-f095ba7422ce.png)

I also have this problem in latest experimental 9535 with quadbike

**Comment by Night-Pryanik** [comment] 2019-09-17 17:28
Quote from #33994

> I attached my bike to my solar car with bike racks and drove it really far. When I arrived at my destination I tried taking my bike off the rack and moving it. I initially grabbed the front of the bike and tried pulling it toward the front of the vehicle and getting "The bike collides with errors in movement code." I got this same error pulling it SW and S. Then I tried grabbing the saddle and pulling it S and SW and got the same error. It worked fine when I grabbed the back wheel and pulled it E.

**Comment by theguruofreason** [comment] 2019-12-29 07:04
Game version: Build 7126

Operating system: Win 10 x64

Mods Active:
![mods](https://user-images.githubusercontent.com/3497875/71553544-318fea00-29c6-11ea-89f6-f9626caf0141.png)

Happened to me with an untouched motorcycle. I was able to grab the motorcycle's back tire and move it, strangely, towards me while I was on top of it. After the initial move, I no longer collided with error.
![motorbike_in_question](https://user-images.githubusercontent.com/3497875/71553554-54ba9980-29c6-11ea-916d-a6ab005bbaa4.png)
![collide_with_error](https://user-images.githubusercontent.com/3497875/71553556-5be1a780-29c6-11ea-9ccf-ffaf6780e568.png)

**Comment by l29ah** [comment] 2020-02-15 13:37
[2020.02.14.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4208520/2020.02.14.zip)
another repro

**Comment by DalenTalas** [comment] 2021-05-25 13:48
Recreated when dragging vendor carts, see attached save file.
[TEST WORLD.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6539780/TEST.WORLD.zip)

**Comment by Qrox** [comment] 2021-07-28 15:14
It seems if you construct a new vehicle and add a new frame before the root part, you can drag/push it with no problem, but if you add a new part behind the root part instead, dragging it from the front or pushing from the behind all result in collision with errors. Dragging it in some other way seems to clear whatever error it has and you can drag/push it with no problem afterwards.

**Comment by RoyBerube** [comment] 2021-09-25 04:04
I believe this has been fixed by #51385

**Comment by Night-Pryanik** [comment] 2021-09-25 04:36
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2021-09-25 04:36 UTC
Labels: <Bug>, (S2 - Confirmed), Vehicles
