### ISSUE TITLE
Near-sighted appears when mutating, even though having Telescopic Eyes CBM installed

### ISSUE THREAD

**Issue by e-kato2** [CleverRaven/Cataclysm-DDA#28456] opened 2019-03-02 11:34 UTC
**Describe the bug**  
The near-sighted mutation reappears when having Telescopic Eyes installed and mutating.

**To Reproduce**  
1. Install Telescopic Eyes CBM.
2. Try to mutate Near-Sighted.
3. The mutation appears.

**Expected behavior**  
The mutation doesn't appear, since Telescopic Eyes cures near-sightedness and far-sightedness.

**Versions and configuration(please complete the following information):**
 - OS: NixOS 18.09
 - Game Version: f5ecd34-dirty
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by Night-Pryanik** [comment] 2019-03-02 11:52
Duplicate of #21407.

**Closed by Night-Pryanik** 2019-03-02 11:52 UTC
