### ISSUE TITLE
Butchering animals causes a crash

### ISSUE THREAD

**Issue by Escamado** [CleverRaven/Cataclysm-DDA#43196] opened 2020-08-24 22:39 UTC
# Describe the bug

Game crashes the moment you butcher any animal

# Steps To Reproduce

1. Spawn a butchering knife
2.Spawn animal
3.Kill it
4.Butcher it
5.Game looses it's shit

# Expected behavior

The butchering of the animal without the game crashing

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-5336-gd3cb7ff
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda,nonpcfood

# Additional context

Crash logs:

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5120519/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5120521/debug.log)

Save:

[Painter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5120531/Painter.zip)

**Comment by DoctorVanGogh** [comment] 2020-08-25 00:00
Duplicate of #43125

Should be fixed in build 10949 onward.

**Comment by anothersimulacrum** [comment] 2020-08-25 00:03
This is from a build before the fix.

**Closed by anothersimulacrum** 2020-08-25 00:03 UTC
Labels: <Crash / Freeze>
