### ISSUE TITLE
Unload Fermenting Vat error-crash (8daffcd)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#66560] opened 2023-06-30 19:29 UTC
### Describe the bug

Finishing a Fermenting Vat of Vinegar causes the below error crash:

```
 DEBUG    : fvat_full was empty!

 FUNCTION : void iexamine::fvat_full(Character&, const tripoint&)
 FILE     : src/iexamine.cpp
 LINE     : 3452
 VERSION  : 8daffcd
```

### Attach save file

[Aplington 2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11919916/Aplington.2-trimmed.tar.gz)

### Steps to reproduce

Constructed FV does not allow finishing of Vinegar product as once the error appears: the finished 'Vinegar' is destroyed.

Deconstructing and rebuilding the FV solves the error SOMETIMES but usually does not. Test in this instance was Innawoods and only one FV was present in the reality bubble.

### Expected behavior

Not.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: 8daffcd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood],
    Bionic Professions [package_bionic_professions],
    Rural-Only Mapgen [ruralbiome],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots]
]

**Comment by RenechCDDA** [comment] 2023-07-01 09:30
Not able to reproduce on 

- OS: Windows
    - OS Version: 10
- Game Version: c94dc03 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood],
    Bionic Professions [package_bionic_professions],
    Rural-Only Mapgen [ruralbiome],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots]
]


You don't appear to have any vinegar fermenting in your save?

**Comment by evankimori** [comment] 2023-07-01 09:44
Well that's odd. The save most likely happened post-error. 

Unable to replicate using my same save? Ugh. Because it happens again even if I load, add another set of UV and wait it out. What am I doing differently?

**Comment by RenechCDDA** [comment] 2023-07-01 09:56
Try uploading another save before you take it out of the vat?

**Comment by esavier** [comment] 2023-09-15 16:22
had (maybe the same) an issue with git build on 
38e387c65d4b4b2da6e9c7de239ac78d292904e1
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12621737/crash.log)

interacting with fully loaded vat of whiskey wort crashed the game
only one change is to json to shorten the duration from 7 days to 1,

possibly related to :
https://github.com/CleverRaven/Cataclysm-DDA/issues/67937

**Comment by evankimori** [comment] 2024-03-13 19:05
Issue is still occurring in 22a7030. 

Problem seems to be due to the Innawoods(?) Wooden Fermenting Vat VS (Vanilla) Fermenting Vat if that ma be of help. Been testing this a few times with marking amounts on it with Survival Marker before starting fermenting process and it's a near guaranteed crash with the IW appliance even with using Admin Edit for Furniture placement.

Not sure if Admin VS player-built structure has effect on cause.

**Comment by evankimori** [comment] 2024-03-13 19:06
Current error code:

 DEBUG    : fvat_full was empty!

 FUNCTION : void iexamine::fvat_full(Character&, const tripoint&)
 FILE     : src/iexamine.cpp
 LINE     : 3586
 VERSION  : 22a7030

**Comment by RenechCDDA** [comment] 2024-03-18 20:20
> Issue is still occurring in [22a7030](https://github.com/CleverRaven/Cataclysm-DDA/commit/22a70300586627d522e7406034a26dd9edb6575e).
> 
> Problem seems to be due to the Innawoods(?) Wooden Fermenting Vat VS (Vanilla) Fermenting Vat if that ma be of help. Been testing this a few times with marking amounts on it with Survival Marker before starting fermenting process and it's a near guaranteed crash with the IW appliance even with using Admin Edit for Furniture placement.
> 
> Not sure if Admin VS player-built structure has effect on cause.

Yes, using the debug menu can absolutely cause your game to crash.

I dismissed that part of the crash log when it was originally posted as I assumed you triggered that crash after experiencing the original crash, and your crash log was overwritten.

We cannot accept bug reports caused by abusing the debug menu.

If there was a crash here it was almost certainly resolved by #68193. Closing as invalid, most likely caused by the debug menu.

**Closed by RenechCDDA** 2024-03-18 20:20 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation), Fields / Furniture / Terrain / Traps, Items: Containers

**Comment by RenechCDDA** [comment] 2024-03-18 20:22
To specify, without editing my closing message:

Yes, I tested this again. No, still couldn't crash it despite quite a few attempts. No, I didn't try using the debug menu to erroneously set the furniture state, nor am I going to.

**Comment by evankimori** [comment] 2024-03-19 03:03
We'll see. Thanks for your assist. Hope it doesn't come back.
