### ISSUE TITLE
Generates -11 level in a central lab

### ISSUE THREAD

**Issue by 9tale** [CleverRaven/Cataclysm-DDA#48679] opened 2021-04-27 14:23 UTC
# Describe the bug

Generates a map with -11 or lower z-level at the central lab.
Therefore an error occurs that I tried to move outside allowed range of z-levels when I try to decend stairs.

# Steps To Reproduce

1. Go downstairs at the central lab.
2. If the lab ends in -10 z-level, make a new character and do 1.
3. If you reach -10 level and try to go downstair, error occurs and cannot go further.

# Expected behavior

 DEBUG    : Tried to move outside allowed range of z-levels

 FUNCTION : void game::vertical_move(int, bool, bool)
 FILE     : src/game.cpp
 LINE     : 10351

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 67f6d22 [64-bit]
- Graphics Version: Tiles
- Game Language: 한국어 [ko]
- Mods loaded: [
    어두운 미래 [dda],
    총기 제조 팩 [craftgp],
    Mythical Martial Arts [MMA],
    지도 기호 수정 [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    NPC 욕구 제거 [no_npc_food]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6385244/debug.log)

[Neutopia-Simplified.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6385259/Neutopia-Simplified.zip)

**Comment by Night-Pryanik** [comment] 2021-04-27 15:54
Duplicate of #38597.

**Closed by Night-Pryanik** 2021-04-27 15:54 UTC
Labels: (S1 - Need confirmation), Map / Mapgen, Z-levels

**Comment by 9tale** [comment] 2021-04-28 10:21
> Duplicate of #38597.

Thanks.
