### ISSUE TITLE
In Progress Items Require All Of Starting Ingredients Despite Progress Made

### ISSUE THREAD

**Issue by Catalyst2114** [CleverRaven/Cataclysm-DDA#31086] opened 2019-06-02 19:19 UTC
In progress items should only require the remaining inputs to finish. In the case of a 34/40 rags, 30/30 threads duffel bag, it should only require 6 more rags to be present to finish but requires the whole 40 rags to be present and no more threads are required because it correctly understands that the threads input is satisfied but incorrectly views the rags as wholly incomplete and consumes another 40 rags.

1. Make a duffel bag and fail to complete due to input loss during the crafting process
2. Collect the remaining material needed, but not the amount needed to create another, separate duffel bag
3. Fail to even be allowed to begin crafting and in the presence of 40 rags, consumes all 40

# Expected behavior

Be able to finish crafting without needing another 40 rags because 34/40 is already present.

Screenshots
![image](https://user-images.githubusercontent.com/40281351/58766181-86ab7080-8549-11e9-8283-e6dcae58ef0f.png)

![image](https://user-images.githubusercontent.com/40281351/58766184-94f98c80-8549-11e9-80fe-207129d240e1.png)

![image](https://user-images.githubusercontent.com/40281351/58766187-9f1b8b00-8549-11e9-9e67-72d9c7488858.png)

 Versions and configuration

 - OS:  Windows 10 
 - Game Version: 0.D-3875-g7dae187
 - Graphics version: Tiles 
 -Mods: DDA

**Comment by LeeMartin77** [comment] 2019-11-17 00:18
I just tried to reproduce this and was unable to - jumping over the code in question, it looks like it was updated a few days after this bug was raised, and would have fixed this issue. See pull request #31163 

I'd propose closing this one.

**Comment by Night-Pryanik** [comment] 2019-11-17 05:18
Ok, closing until re-confirmed.

**Closed by Night-Pryanik** 2019-11-17 05:18 UTC
Labels: <Bug>, Crafting / Construction / Recipes
