### ISSUE TITLE
Temple Fire Corridor stops being fiery after 1 turn

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#18040] opened 2016-08-15 18:01 UTC
In the Strange Temple, the Fire Corridor level only generates fire fields for a single turn when you first enter it. It then stops generating fire fields, all the existing fire fields disappear, and is perfectly safe to walk down.

**Comment by pisskop** [comment] 2016-08-19 15:08
I imagine it was done with the fire nerfs/rebalancing.

**Comment by Leland** [comment] 2017-05-25 01:24
Dupe of #11046

**Closed by Leland** 2017-05-25 01:24 UTC
Labels: Bug
