### ISSUE TITLE
Npc become hostile after sending for menial job

### ISSUE THREAD

**Issue by Thogsloc** [CleverRaven/Cataclysm-DDA#29109] opened 2019-03-29 11:59 UTC
**Describe the bug**  
Npc become hostile but still following me after sending for menial job in BASE CAMP MISSION and cannot chat with.If I save the game while npc is doing the job he would be stuck when I open the save next time.

**To Reproduce**  
1. Start a basecamp.
2. Set sort zones and send npc for menial job.
3. Save and quit and get in or wait for the job done.

**Expected behavior**  
The npc should be able to chat with.
There's some bugs with npc's status.

**Screenshots**  
No screenshots.

**Versions and configuration(please complete the following information):**
 - OS: [Windows-10-10.0.17134 (64-bit)]
 - Game Version: [0.D-1143-g962863d]
 - Graphics version: [Tiles]
 - Mods loaded: [a lot]

**Additional context**  
My gamesave:
https://www.dropbox.com/s/w2a1y5ibmzhqg4y/Hammer%20x.rar?dl=0

**Comment by Tharn** [comment] 2019-03-29 13:13
I am getting "NPC is hostile!" on all three of my followers too, even though I did not anger them. This just happened with today's build. They were fine before.

**Comment by davidpwbrown** [comment] 2019-03-29 14:09
Already fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/29106 as is duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/29105

**Comment by Tharn** [comment] 2019-03-29 15:56
Confirmed fixed.

**Closed** 2019-03-29 17:58 UTC
Labels: <Bug>, NPC / Factions
