### ISSUE TITLE
Crash while Sewing

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#57500] opened 2022-05-07 02:31 UTC
### Describe the bug

I was sewing, and the game suddenly crashed due to a 'segmentation fault.' I've attached the  [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8644278/crash.log) here. I think that's all i can do to help. 
 

### Steps to reproduce

Sew something : 
- Break your drop pouches
- See the game crash.

What a harsh penality for my craftsmanship. 

### Expected behavior

.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment] 2023-10-20 11:00
Unable to reproduce on  078a7b43be36c11f2431bf52f5f00d2d41c9a53a and unfortunately the provided crash log has no stack trace, so closing this as presumably fixed.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/e415faa1-5dd0-4255-bbe7-2876cb4f4716)

**Closed by RenechCDDA** 2023-10-20 11:00 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
