### ISSUE TITLE
Advanced nomad jumpsuit dont work

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#64941] opened 2023-04-08 15:13 UTC
### Describe the bug

Advanced nomad jumpsuit dont work, When you are trying to activate it - you will recive "your internal reservoir is empty", even if you have few power storages in you

### Attach save file

N/A

### Steps to reproduce

Start as a cyborg class, as example, scenario "High tech, low life", take "Bionic monster" - you will have power storage inserted in you
Spawn advanced nomad jumpsuit with debug menu, equip, try to turn it on - "your internal reservoir is empty"
I think, problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/63978 , because before this update all works as intented

### Expected behavior

Advanced nomad jumpsuit working

### Screenshots

![image](https://user-images.githubusercontent.com/102726167/230728794-bffcf398-42c7-46e9-994a-2b1f849b27c9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 7e48693 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by KHeket** [comment] 2023-04-08 15:13
@Hirmuolio can you check pls?

**Comment by andrei8l** [comment] 2023-04-09 05:57
/confirmed

Caused by this new check here https://github.com/CleverRaven/Cataclysm-DDA/blob/e33e1cfd8cd35b6cd912ab71f16f05a1cd068bc3/src/item.cpp#L10280

Easily fixed in JSON
```diff
diff --git a/data/json/items/armor/bespoke_armor/custom_bodysuits.json b/data/json/items/armor/bespoke_armor/custom_bodysuits.json
index 1edaabcce0..3fc7704ad9 100644
--- a/data/json/items/armor/bespoke_armor/custom_bodysuits.json
+++ b/data/json/items/armor/bespoke_armor/custom_bodysuits.json
@@ -64,6 +64,7 @@
     "symbol": "[",
     "looks_like": "touring_suit",
     "color": "light_red",
+    "ammo": "battery",
     "armor": [
       {
         "material": [
```

**Closed** 2023-04-10 15:00 UTC
Labels: (S2 - Confirmed)
