### ISSUE TITLE
The Long Tail mutation should allow knee-pads, shin guards and similar items.

### ISSUE THREAD

**Issue by PUBDR** [CleverRaven/Cataclysm-DDA#54810] opened 2022-01-26 17:54 UTC
### Is your feature request related to a problem? Please describe.

I think it would make sense if having a tail didn't hinder your ability to wear certain gear.

### Solution you would like.

Knee pads, shin guards, plates and similar items don't obstruct the tail's physicality so I believe that these items should be allowed to be used in conjunction with the long tail mutation.

**Comment by hjk321** [comment] 2022-01-26 19:00
I just took a quick look at the tail mutations. As it stands right now, most tails restrict leg gear not considered "soft" (fabric pants for example are allowed). However, there's a flag called `ALLOWS_TAIL` which can override this. I'm going to go ahead and **add the flag for knee pads and shin guards** really quick, but please clarify exactly what you mean by "plates".

By the way, this fix should work for all tails as well, not just long tail. Thanks for reporting this!

**Comment by NetSysFire** [comment] 2022-01-26 19:03
Reminds me of #53288

**Comment by hjk321** [comment] 2022-01-26 19:11
This looks like a duplicate of #45793 which was fixed in #45898.

**Comment by NetSysFire** [comment] 2022-01-26 19:18
Good catch, but if @PUBDR is still running 0.F stable it might not have been backported. Nonetheless this really does look like a duplicate and putting on knee pads with a long tail works in experimental.

**Closed by NetSysFire** 2022-01-26 19:18 UTC

**Comment by Jarewill** [comment] 2022-01-28 20:27
With the new bodypart specification feature, wouldn't it be better to make mutations only disallow equipment if it covers a certain area?
For instance tails would only prevent non-fabric items that cover the hips. (and maybe the thighs?)
The current solution works, but it causes issues if an item lacks the specific flag, like the Hub 01 greaves which cannot be worn with tails currently, despite only covering the lower legs and knees.

**Comment by hjk321** [comment] 2022-01-28 21:08
@Jarewill That makes sense but since that's more an improvement/overhaul of the existing system rather than a bugfix, it probably should go into its own issue.

**Comment by Jarewill** [comment] 2022-01-28 21:13
@hjk321 Oh, so I should open a new issue then?
Then I apologize for posting here.
