### ISSUE TITLE
Can no longer load game after latest update

### ISSUE THREAD

**Issue by Esin12** [CleverRaven/Cataclysm-DDA#19447] opened 2016-11-25 02:40 UTC
Basically as the title says, after the latest set of updates (#5938), I can no longer load my save files. I receive the following error screens upon loading. 

![image](https://cloud.githubusercontent.com/assets/23725850/20613089/ff418578-b285-11e6-8fb3-3fdb1b5ba7da.png)

Then, after pressing "i," I get the following: 

![image](https://cloud.githubusercontent.com/assets/23725850/20613096/115818da-b286-11e6-8c20-ecb3098cb500.png)

Any possible help would be appreciated. Thanks!

**Comment by mutability** [comment] 2016-11-25 04:01
What was the last version that worked?
What was the firsts version that stopped working?
Where is the save?

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-25 04:15
@Esin12 you just accidentally confused Jenkins version numbers with PR numbers; due to several PRs being closed for various reasons and other points of divergence, the PR numbers are higher.  The PR you intended to refer to is #19442.

**Comment by codemime** [comment] 2016-11-25 11:25
Looks like a dupe of #19404.

> Any possible help would be appreciated. Thanks!

Try [this advice](https://github.com/CleverRaven/Cataclysm-DDA/issues/19385#issuecomment-262220644).

**Comment by Esin12** [comment] 2016-11-25 15:26
Thanks for the responses! To be honest, I'm pretty ignorant as to how I go about doing and locating most things that you're asking about. First, I was looking for my save file in the "saves" folder, and couldn't really figure out which file was the right one. BorkBork, is there a way I can see which specific mods I'm using for the world I generated? I'm using a good amount of them, and can't quite remember all of the ones I've chosen specifically. Codemime, thanks for the suggestion! Unfortunately, I'm not really sure how to go about implementing these changes. Could you provide some further feedback as to how I go about this?

Thanks again, and I apologize for being pretty bad with all of this.

**Comment by Tharn** [comment] 2016-11-25 17:00
In the save directory, open **mods.json** with a text editor and delete the line that reads

`"dda",`

**Comment by Esin12** [comment] 2016-11-25 17:29
Awesome, thanks! That worked. There were like 9 lines that read that, so that must've been the issue.

**Comment by mugling** [comment] 2016-11-27 00:18
> Looks like a dupe of #19404.

**Closed by mugling** 2016-11-27 00:18 UTC
Labels: Duplicate
