### ISSUE TITLE
Washing stacked item requires more resources than it should

### ISSUE THREAD

**Issue by ArcanErasmus** [CleverRaven/Cataclysm-DDA#35211] opened 2019-10-31 22:00 UTC
# Describe the bug
When trying to wash something that stacks, like thread, the game calculates the requirements for the whole stack, then multiplies it by the amount of the stack.

# Steps To Reproduce

1. Load up my save, you will have 6240 filthy thread
2. Activate the washboard, and select all the thread
3. See that it requires an amount of water to wash equal to over 3000 cubic feet, and a similarly ludicrous amount of detergent.

# Expected behavior

Water requirement is defined as the volume divided by 0.125L, rounded up. 6240 thread has a volume of 7.80L, which rounds up to 63 units of water.

# Screenshots

![image](https://user-images.githubusercontent.com/8963206/67988995-f5c7e680-fc07-11e9-91d6-9a61ab9a6b2f.png)

![image](https://user-images.githubusercontent.com/8963206/67989008-fceef480-fc07-11e9-9896-9a1c321f93ee.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9019-gdfc081c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Roadheader and other mining vehicles [Heavy miners],
    Disable Religious Texts [no_religious_Texts],
    No Flaming Weapons [no_flaming_weapons],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    sees-player icon, -attitude [sees_player_less_attitude],
    CGPersonal [cgpersonal]
]

# Additional context

[compressed save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3795978/compressed.save.zip)

63 * 6240 = the big number shown in the screenshot.

Also, CGPersonal is my own rebalance mod, which only tweaks a couple things. The only possibly relevant one would be that it changes the uncraft time of rags to 5 minutes (to stop the perpetual Quest For Thread).

Link to the repo for my mod (README is way out of date): https://github.com/ArcanErasmus/CGPersonal

**Comment by ArcanErasmus** [comment] 2019-10-31 22:01
I'm currently working on making my save file small enough to upload.

**Comment by ArcanErasmus** [comment] 2019-10-31 22:11
Added save file.

**Comment by Zourin2** [comment] 2019-11-04 00:54
Mostly duplicate of [https://github.com/CleverRaven/Cataclysm-DDA/issues/32800](#32800)

**Closed** 2019-11-04 18:31 UTC
Labels: <Bug>, Character / Player, Items / Item Actions / Item Qualities
