### ISSUE TITLE
weird unusable bridge generation

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64791] opened 2023-04-02 19:37 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/71761521/229374990-264e76a4-695f-4683-8dcc-1d3f12501740.png)

### Attach save file

[Depths Of Jupiter-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11133154/Depths.Of.Jupiter-trimmed.tar.gz)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 2adbbc9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by ZhilkinSerg** [comment] 2023-04-02 19:41
Duplicate of #46844

**Closed by ZhilkinSerg** 2023-04-02 19:41 UTC
Labels: (S1 - Need confirmation)
