### ISSUE TITLE
patchwork synthetic fabric clothing parts and synthetic fabric sheets are uncraftable.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#57257] opened 2022-04-29 15:12 UTC
### Describe the bug

Yep, that's it. What the title said.

### Steps to reproduce

1. Open debug mode and unlock all recipes.
2. Search for "synthetic fabric" in crafting menu.
3. void

### Expected behavior

Would have expected to be able to put synthetic fabric together into sheets and patchwork clothing parts.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 3e81ac1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Zireael07** [comment] 2022-04-29 16:49
dupe of #52391  and #52882

**Comment by NetSysFire** [comment] 2022-04-29 22:11
Closing as duplicate.

**Closed by NetSysFire** 2022-04-29 22:11 UTC
Labels: (S1 - Need confirmation)
