### ISSUE TITLE
Smashing Cars out of Existance Causes Hang

### ISSUE THREAD

**Issue by WhiteHusky** [CleverRaven/Cataclysm-DDA#24041] opened 2018-06-18 08:07 UTC
Game version: 0.C-28368-g930b6e2

Operating system: Win10

Tiles or curses: Tiles

Mods active:
![](https://i.imgur.com/WowwT2A.png)
![](https://i.imgur.com/acpfgzQ.png)

### Expected behavior
Smashing into a vehicle into nothing shouldn't cause the game to hang for a few seconds.
### Actual behavior
Game hangs for a few seconds and null parts are being struck
![](https://i.imgur.com/OPmbYpH.png)
### Steps to reproduce the behavior
Find a big enough vehicle and smash it against a smaller vehicle, attempting to destroy all parts.
[Like so.](https://streamable.com/1c4h6)

**Comment by mlangsdorf** [comment] 2018-08-17 18:37
I can't really reproduce this on my system. I've driven a couple of MBTs into the ground and destroyed various vehicles by ramming, and the system was responsive.

I also suspect the fix for #23189 is going to affect this issue, because things are not going to speed up when vehicles start falling apart as they take damage.

**Comment by mlangsdorf** [comment] 2018-09-27 17:43
So the hang seems to happen at the same time the collision is involving null parts. Not a lot of insight there but it's something to investigate.

**Comment by Inglonias** [comment] 2018-12-23 19:01
Has the status of this issue changed since vehicle splitting became a thing?

**Comment by kevingranade** [comment] 2019-02-16 07:24
I'm not seeing a reproduction case here, @mlangsdorf  if you have some insight into how to reproduce this I'm all ears, but unless that's forthcomig I'm moving it off the 0.D blockers.

**Comment by mlangsdorf** [comment] 2019-02-16 19:01
I can't get a consistent reproducer.  I've seen it happen but it's rare enough that we can live with it until we get a better reproducer.

**Comment by Night-Pryanik** [comment] 2019-02-17 10:40
Guess we can close it then.

**Closed by Night-Pryanik** 2019-02-17 10:40 UTC
Labels: (S2 - Confirmed), <Bug>, Vehicles
