### ISSUE TITLE
Debug message upon NPC skill training

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#18782] opened 2016-10-13 19:45 UTC
As of experimental 5685, at least, I received the following debug message when attempting to train:

> src/npctalk.cpp:3054 [void talk_function::clear_mission(npc&)] clear_mission: mission_selected not in assigned

What missions have to do with it, I'm not sure. I still have the starting Find Relic mission uncompleted. The training finished without crashing the game, and this is the first instance of the bug after several training sessions.

EDIT: Incidentally, it might have a lot to do with it. Come to think of it, the NPC stopped asking about the mission status a while ago, and there was no 'About that job...' talk option, only the 'Can I do anything for you' line. When I selected it, it skipped right to the next mission.

**Comment by Leland** [comment] 2017-05-08 20:26
Stalled for >6 months. Closing due to lack of confirmation. @railmonkey if you can find a way to reproduce this, please let me know and I'll reopen.

**Closed by Leland** 2017-05-08 20:26 UTC
Labels: Bug, Mission, NPC
