### ISSUE TITLE
Getting opened aluminum or tin cans (i.e. crafting oil lamp)

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#41298] opened 2020-06-14 07:03 UTC
# Describe the bug

To craft an oil lamp, opened aluminum or tin cans can be used as components. However, when the food inside one of these cans is consumed, the by-product is not "opened". The only way to get them is finding them already opened.

# Steps To Reproduce

1. Get an aluminum can of root beer.
2. Drink the content.
3. An "aluminum can" is left in the inventory (not an "opened aluminum can").

# Expected behavior

To craft certain items, like an oil lamp, an "opened" can is needed. So either the by-product of consuming a can should be "opened" or the recipe ingredient changed.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3159-g3f48507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by wapcaplet** [comment] 2020-06-14 13:01
The general problems with cans have been known for a while (#40127, #40658, #40742), but your issue report looks like the first clear description of this particular facet of it - that their state is not correctly changed from "closed" to "opened". This issue is not a duplicate of those issues, since the symptom and use cases are different, but the root cause(s) are likely to be related.

**Comment by anothersimulacrum** [comment] 2020-06-15 01:05
To my knowledge, the opened variants of those cans are deprecated, and the pockets of the sealed versions are supposed to transition between sealed and unsealed.
As such, to fix this, you'd just need to change the cans used in those recipes.

**Closed** 2020-06-18 20:05 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Good First Issue, [JSON]
