### ISSUE TITLE
Ammo belt Unload bug

### ISSUE THREAD

**Issue by Andrej27** [CleverRaven/Cataclysm-DDA#20237] opened 2017-02-09 14:47 UTC
(U)nloading ammo belts, including grenade belts, placed on ground causes debug message and leaves and empty ammo belt on the ground. It still gives belt linkage and ammo as normal. Possibly trying to remove the empty ammo belt from player inventory (instead of ground).
Windows 7 64 bit, CDDA tiles cataclysmdda-0.C-6175.
![image](https://cloud.githubusercontent.com/assets/25665339/22788042/ac7e35ee-eede-11e6-998b-266052635fc4.png)
![image](https://cloud.githubusercontent.com/assets/25665339/22788097/d65d7f3c-eede-11e6-884c-d4c516150415.png)
![image](https://cloud.githubusercontent.com/assets/25665339/22788129/f857f6ee-eede-11e6-8a61-b66f46dab79a.png)

**Comment by keyspace** [comment] 2017-02-09 16:16
Duplicate of:  #19700

**Comment by keyspace** [comment] 2017-02-09 16:18
This issue provides version info, screenshots, and possible cause. #19700 doesn't, but mentions that the belt is unusable afterwards.

**Closed** 2017-02-12 16:54 UTC
