### ISSUE TITLE
Holster dissapearance

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#58475] opened 2022-06-16 22:41 UTC
### Describe the bug

Upgrading a pistol with a suppressor while inside a holster causes warnings, the pistol then disappears.

### Steps to reproduce

1.Wear a 'holster' item.
2. Insert unmodded Glock20 into holster
3. Install "Compact Suppressor" mod onto Glock 20
4. Wait or walk for ~100 turns
5. Check inventory to find missing Glock 20

### Expected behavior

One of three things might be appropriate:
1. Guns are automatically wielded/dropped when modded
or
2. A check is performed to see if the pocket the gun is in is large enough to incorporate the mod, and fails the mod attempt if not
or
3. after modding, a check is performed to determine if player pockets contain invalid items, invalid items are dropped.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: c992d94 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment] 2022-06-17 06:57
Seems to be related to #58078, which will be probably be fixed by #58266.

**Comment by hexagonrecursion** [comment] 2022-07-03 15:01
I can not reproduce the bug: my character wields the gun before attaching mods

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Closed** 2022-11-13 13:58 UTC
Labels: (S1 - Need confirmation)
