### ISSUE TITLE
(Windows SDL/Sound?) Memory leak from saving and reloading game repeatedly.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#14046] opened 2015-11-15 17:42 UTC
I compiled using MinGW 64bit, my initial memory usage was around 500 MB, it gains another 350 MB every time I save and reload the same game. I passed 2 GB of memory usage repeatedly saving and reloading.

I noticed something similar on someone's stream of the game, their tileset failed to load because they were out of memory, which is probably related to this memory leak.

**Comment by CliffsDover** [comment] 2015-11-17 01:45
I don't know if it is related but #13715 will increase memory usage since the gray scale and night vision images are created on the fly and stored in the memory.

**Comment by kevingranade** [comment] 2015-11-23 03:30
Weird, I'm not seeing anything like that on linux with tiles.
BevapDin says he has a fix though, I'll need confirmation after merging it that it fixes the situation for you.

**Comment by DanmakuDan** [comment] 2015-11-23 03:40
It looks like the sound effects loader only clears the loaded effects list on closing the game, but will reload sounds every time a save is loaded.

**Comment by kevingranade** [comment] 2015-11-23 06:20
ok, I'll try that, I didn't have sound support enabled.

**Comment by mugling** [comment] 2016-09-21 16:13
Closed as unconfirmed

**Closed by mugling** 2016-09-21 16:13 UTC
Labels: Bug, Confirmation Needed, Windows
