### ISSUE TITLE
'Tough' trait has broken description

### ISSUE THREAD

**Issue by AnonymousCaptain** [CleverRaven/Cataclysm-DDA#25904] opened 2018-09-30 06:47 UTC
When creating your character, the trait 'tough' shows the wrong description, showing "basic_string::substr: __pos (which is 50) > this ->size() (which is 3)" instead of the actual description.

1. Go to 'New Game'
2. Select 'Random Character'
3. Go to 'Traits'
4. Go down the list until finding the 'Tough' Trait

 - OS: Windows 10
 - Game Version: 0.C-32701-gdd4bc7c
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Simplified Nutrition, More Locations, Fuji's More Buildings, Boats, Vehicle Additions Pack, Tanks and Other Vehicles, NPC traits, Mutant NPCs, Alternative Map Key, Makeshift Items Mod, Medieval and Historic Content, More Survival Tools, Classes and Scenarios Mod, Classic Roguelike Classes, Manual Bionic Installation, Safe Autodoc, StatsThroughSkills

**Comment by gynoidgearhead** [comment] 2018-09-30 08:17
Duplicate of #25892.

**Closed** 2018-09-30 10:40 UTC
