### ISSUE TITLE
Vechicle controls - options to control electronics missing - lights, UPS, etc.

### ISSUE THREAD

**Issue by Denniz-Dal** [CleverRaven/Cataclysm-DDA#24620] opened 2018-08-03 20:37 UTC
Game version: 7645

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:

### Expected behavior
Options to turn on lights, cameras, ups, etc

### Actual behavior
Options missing

### Steps to reproduce the behavior
Activate vehicle controls

**Comment by Night-Pryanik** [comment] 2018-08-03 20:44
I suppose all vehicles must be extremely fast updated with the newly added electronics control unit.

**Comment by DracoGriffin** [comment] 2018-08-03 20:46
Without more information, this is probably working as intended due to the way vehicles are working now via #24594 per issue #15807.

If your vehicle is missing a dashboard, you won't have those options.

>I suppose all vehicles must be extremely fast updated with the newly added electronics control unit.

No, they just require dashboard and vehicle controls which was already added in #23175.

**Comment by Night-Pryanik** [comment] 2018-08-03 20:58
Yeah, I was wrong. Then it's a bug only if some pre-generated vehicle prototype doesn't have a dashboard.

**Comment by Denniz-Dal** [comment] 2018-08-03 23:10
This was a save from before the change. I can probably enough skill to add a dashboard. Thanks

**Comment by Night-Pryanik** [comment] 2018-08-04 06:27
Ok, closing for now.

**Closed by Night-Pryanik** 2018-08-04 06:27 UTC
Labels: <Bug>, Vehicles
