### ISSUE TITLE
Outfit Choices on Character Creation

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#68392] opened 2023-09-29 15:53 UTC
### Is your feature request related to a problem? Please describe.

When we start as an average Joe in an evac shelter, we always start with a long-sleeved shirt and a pair of jeans. But what if we could choose what our average joe is wearing, other than a long-sleeved shirt and a pair of jeans? Something like a hoodie, or a trenchcoat.

### Solution you would like.

Ability to choose clothings in character creation menu.

**Comment by Rabadash94** [comment] 2023-09-29 16:03
It's a good idea, although I suppose it will need to be clothing that offers the same protection and cargo space as what the character is wearing by default.

**Comment by ZhilkinSerg** [comment] 2023-09-29 16:44
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/54113

**Closed by ZhilkinSerg** 2023-09-29 16:44 UTC
Labels: <Suggestion / Discussion>
