### ISSUE TITLE
Crash(SIGSEGV) 0.D-119-g15b91d1(Linux) Tying to feed NPC with smoked meat

### ISSUE THREAD

**Issue by GrigorijGlukhov** [CleverRaven/Cataclysm-DDA#28647] opened 2019-03-11 16:38 UTC
**Describe the bug**  
Crash SIGSEGV on Linux/Ubuntu version 0.D-119-g15b91d1 
One of my NPCs asks me for food. I gave her one smoked meat - all fine, but when I gave her second smoked meat - crash.

**To Reproduce**  
1. Prepare some Smoked Meat
2. make NPC very hungry
3. give to NPC some smoked meat by NPC Talk main dialog menu - key 'g'

**Expected behavior**  
Return to dialog main menu. 

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 16.04.5 LTS (Xenial Xerus)]
 - Game Version: [0.D-119-g15b91d1]
 - Graphics version: [Tiles]
 - Mods loaded: ["dda", "filthy_morale", "realguns", "makeshift", "More_Survival_Tools",     "modular_turrets", "Salvaged_Robots", "more_locations", "FujiStruct", "Urban_Development",      "boats", "deoxymod", "blazemod", "Tanks", "DP_REMIX_INDICATORS"]

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2953201/crash.log)

**Comment by LyleSY** [comment] 2020-04-12 22:55
Couldn't reproduce on newest experimental on Mac running vanilla NPC needs enabled and tiles. I'm guessing it's related to one of those mods there.

**Comment by Night-Pryanik** [comment] 2020-04-13 18:23
Closing as non-confirmed for more than a year.

**Closed by Night-Pryanik** 2020-04-13 18:23 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, NPC / Factions
