### ISSUE TITLE
Magiclysm--Iron Golem's Hazy Cloud Ignores Active Filter Mask

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#37182] opened 2020-01-18 16:26 UTC
# Describe the bug

With Magiclysm active and a worn filter mask, stepping into a Hazy Cloud generated by a Iron Golem causes poison. No charge is consumed by the mask, leading me to believe that it's simply not checked rather than the cloud being too toxic to filter

# Steps To Reproduce

Find a iron golem, Wait for it to use it's special attack which looks like a explosion. Step into one of the tiles now covered by 'hazy cloud'. It will say 'You feel sick from inhaling the hazy cloud'.

# Expected behavior
Either not inhaling the hazy cloud with a filter mask on, or a note saying that the mask was unable to protect you.

**Comment by foulman** [comment] 2020-01-18 16:39
Not a bug. At least not one related to Magiclysm.

fd_toxic_gas is a mainline field, not magiclysm content. 

The filter mask only provides 7 points of environmental protection when active, the fd_toxic_gas field states it require at least 15 points of env protection to stop that. 

The filter mask is intended, I think, for more industrial use. Not battlefield gas attacks, which explains why the actual gask mask provides env protection of 16 when active, enough to defeat the gas field.

**Comment by Grubleafeater** [comment] 2020-01-18 16:54
Ah. In that case, it should probably have some kind of indicator that your filter mask is insufficient rather than simply saying you 'inhale' it.

**Comment by foulman** [comment] 2020-01-18 16:56
> 
> 
> Ah. In that case, it should probably have some kind of indicator that your filter mask is insufficient rather than simply saying you 'inhale' it.

I concur, there probably should be a stated reason that your mask is ineffectual.

**Comment by KorGgenT** [comment] 2020-01-18 22:19
closing as it's not a bug

**Closed by KorGgenT** 2020-01-18 22:19 UTC
