### ISSUE TITLE
Large Boxes Delete contained Items when deployed on the ground.[bug]

### ISSUE THREAD

**Issue by HighTyrol** [CleverRaven/Cataclysm-DDA#45791] opened 2020-12-03 15:02 UTC
# Steps To Reproduce
1. Make a player with a large cardboard box and some stuff.
2. Partially fill the bow with stuff.
3. Activate the box to have it act as a barrier/hiding place.
4.Check to see that the items are gone in location.
5. Pickup the box and verify theyare still missing.
# Expected behavior

I expected the items in the box to remain in the box when activated as a barrier. Or at least tumble out of the box if not allowing activated boxes to hold things is intended.
# Versions and configuration
 
- OS Version: 10.0 2004
- Game Version: 0.E-7497-g48b6f14 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [](English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

Also Tested with a smaller mod list on tiles:
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex]
]
#Screenshots:
![CardboardBoxBugscreenshot](https://user-images.githubusercontent.com/68160224/101061829-8b921b80-3556-11eb-9dce-e11e1851bc25.PNG)

![CardboardBoxresult](https://user-images.githubusercontent.com/68160224/101062119-dd3aa600-3556-11eb-9917-07af0fb34ce4.PNG)

# Additional context
I had a decent number of sci-fi type mods installed, so I plan on checking to see if the bug is also on a more vanilla setup too(tested now). I went to download the most recent experimental and it appeared to have the same version code, so I am pretty sure this was up to date.

**Comment by andrei8l** [comment] 2020-12-03 19:35
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45651. Can't reproduce with the newest (linux) build.

**Closed** 2020-12-03 19:36 UTC
Labels: (S3 - Duplicate), <Bug>, Items / Item Actions / Item Qualities, Items: Containers
