### ISSUE TITLE
Pulped/butchered corpses should be visually distinct from non-pulped/butchered corpses

### ISSUE THREAD

**Issue by bleaky** [CleverRaven/Cataclysm-DDA#33129] opened 2019-08-11 00:54 UTC
**Is your feature request related to a problem? Please describe.**  
I find that after a big battle in town, I often catch myself looking through the pile of corpses twice over, three times over in order to make sure I got everyone. Even so, I miss a corpse here and there sometimes, which is obviously not ideal and avoidable through clearer messaging. Furthermore, this would optimize for minimum amount of keystrokes post-battle, by removing the need to break out the V menu to search for corpses.

**Describe the solution you'd like**  
Simply to display pulped/butchered corpses with a different tile than non-pulped/butchered ones. Perhaps not even a new tile, but a recolor of the existing corpse tiles?

**Describe alternatives you've considered**  
I've also considered a "can see you"-style indicator for this but ultimately ruled it out since that semantic space is used for something wildly different and could cause confusion.

**Comment by esotericist** [comment] 2019-08-11 01:16
I think this is an excellent thing to have as visual information, but I have some thoughts on implementation as follows.

As I mentioned in a discussion on the official dev discord, my intuition is that the right thing to do is actually an overlay attached to the tile, rather than anything specific to the corpse asset or tinting the tile.

Reasons are as follows:
*  Tinting the tile in our current tech requires essentially making a duplicate of every terrain and furniture asset with the new tinting (this is why deadpeople takes an inordinate amount of ram), and repurposing one of our existing tinting types would generate confusion
*  Even if we had the ability to do on-demand tile tinting (which I hope we can address at some point), it's possible for a simple tinting approach to confuse with things like alternate carpet colors, painted terrain, etc, making visibility of revivable-corpses being potentially hidden in certain environments.
*  Overlays are, conceptually, the layer at which this kind of information generally resides. While most tilesets don't make use of overlays extensively, the DeadPeople tileset demonstrates how this can be effective. Plus overlays don't have fixed size or positioning relative the tiles; a tileset author can do quite a lot with this. (see: how deadpeople handles trees and large monsters).
*  An overlay can be specified per-tileset, and if necessary overridden in a tileset mod, making it possible for a tileset author to match their aesthetic, and also possible for a player to do something else if they disagree.

That said, I'm perfectly willing to acknowledge the possibility I've overlooked something, and that there might be another option, or factors that complicate things.

On the internal side: I don't know offhand if revivable corpses are currently a thing that already gets cached. I would hope they are (given NPC performance issues in the past looking for possible corpses to pulp), but if they aren't this could get tricky.

**Comment by Azumgi** [comment] 2019-09-26 08:36
I'm on it

**Closed** 2019-10-08 14:21 UTC
Labels: (P4 - Low), <Enhancement / Feature>, Info / User Interface, Items / Item Actions / Item Qualities, Monsters, SDL: Tiles / Sound
