### ISSUE TITLE
Sigsev fault

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#54405] opened 2022-01-14 19:31 UTC
### Describe the bug

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7872722/crash.log)
See attached crash log. Game crashes when leaving industry lab entrance.

### Steps to reproduce

Save can be found [here](https://drive.google.com/file/d/1gKthcsW6MAvY__eLI222-qQbbvIMCree/view?usp=sharing)

1. Load save. Leave industry entrance by way of traveling NW
2. Game crashes when approaching where vehicle is parked.

### Expected behavior

No crash.

### Versions and configuration

Version 9f2940a

**Comment by OptimisticNihlist** [comment] 2022-01-14 20:03
Upon further testing, changing the weather from "Portal Storm" seems to resolve this issue.

**Comment by RenechCDDA** [comment] 2023-07-01 14:28
Also cannot reproduce on https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0 , closing as can't reproduce.

**Closed by RenechCDDA** 2023-07-01 14:28 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation), Mechanics: Weather
