### ISSUE TITLE
Error just after I died, doing nothing special

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#21634] opened 2017-08-15 01:47 UTC
Using this pre-built version on a 64bit Linux :

http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Tiles/cataclysmdda-0.C-6680.tar.gz

I get this error just after dying, right after having written my last words:

![localhost_5901__root_s_x_desktop__1540e2ca60a1_1___-_vnc_viewer](https://user-images.githubusercontent.com/1076726/29299053-0bf9d5bc-813a-11e7-966c-1cdf9b6d0467.png)

I am not sure I can reproduce this one.

**Comment by pierredavidbelanger** [comment] 2017-08-15 02:04
I was able to reproduce this one, on a custom version compiled on OSX based on this latest commit 5d856482862728b7743d07a17e7d39720f13a9d1

This time I was only starting a fire with a fire drill.

It was the same message, same file, class, method and line

**Comment by pierredavidbelanger** [comment] 2017-08-15 02:08
I was able to hit `i` to ignore the repeating messages and continue to play.

But something was not right, in the log it says "You successfully light a fire", but the fire is not lit.

**Comment by pierredavidbelanger** [comment] 2017-08-15 03:06
I hope it can helps , in the code, I commented the `debugmsg` line, and returned `def_c_pink` instead of `def_c_unset` in `color_manager::color_to_id`.

Now, I cant see my brazier on the map, except when I look at it (with `x`), it is now black with a pink background:

![cataclysm__dark_days_ahead_-_0_c-23394-gd01f446](https://user-images.githubusercontent.com/1076726/29300691-04dd8a8e-8145-11e7-8a27-9163b740362a.png)

Some other things have pink background too.

**Comment by ZhilkinSerg** [comment] 2017-08-15 03:56
Same as #21618?

**Comment by pierredavidbelanger** [comment] 2017-08-15 13:55
The problem seems to be related to the highlighting of a map cell.

Here is a `bt` while breaking on [color.cpp:109](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/color.cpp#L109)

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
  * frame #0: 0x000000010031bd6c cataclysm-tiles`color_manager::color_to_id(this=0x0000000101f52768, color=0) const at color.cpp:109
    frame #1: 0x000000010031dbc2 cataclysm-tiles`color_manager::get_highlight(this=0x0000000101f52768, color=0, bg=HL_BLUE) const at color.cpp:164
    frame #2: 0x000000010032a45d cataclysm-tiles`hilite(c=0) at color.cpp:460
    frame #3: 0x0000000100d8b55b cataclysm-tiles`map::draw_maptile(this=0x000000012b21f330, w=0x000000012b3d44b0, u=0x0000000104818e00, p=0x00007fff5fbf46a0, curr_maptile=0x00007fff5fbf4638, invert=false, show_items=true, view_center=0x00007fff5fbf4a60, low_light=false, bright_light=true, inorder=true) const at map.cpp:6072
    frame #4: 0x0000000100d8a50d cataclysm-tiles`map::draw(this=0x000000012b21f330, w=0x000000012b3d44b0, center=0x00007fff5fbf4a60) at map.cpp:5870
    frame #5: 0x00000001006f06e6 cataclysm-tiles`game::draw_ter(this=0x000000012b21ef10, center=0x00007fff5fbf4a60, looking=false, draw_sounds=true) at game.cpp:5038
    frame #6: 0x0000000100696f69 cataclysm-tiles`game::draw_ter(this=0x000000012b21ef10, draw_sounds=true) at game.cpp:5021
    frame #7: 0x000000010066e27f cataclysm-tiles`game::draw(this=0x000000012b21ef10) at game.cpp:4820
    frame #8: 0x00000001006e3cb7 cataclysm-tiles`game::load(this=0x000000012b21ef10, worldname="Yoder", name=0x0000000129bb8d10) at game.cpp:3732
    frame #9: 0x0000000100d31d97 cataclysm-tiles`main_menu::load_character_tab(this=0x00007fff5fbfdc30) at main_menu.cpp:841
    frame #10: 0x0000000100d27b0a cataclysm-tiles`main_menu::opening_screen(this=0x00007fff5fbfdc30) at main_menu.cpp:396
    frame #11: 0x0000000100cfcdf6 cataclysm-tiles`main(argc=0, argv=0x00007fff5fbfebb0) at main.cpp:480
    frame #12: 0x00007fff9f2fc235 libdyld.dylib`start + 1
    frame #13: 0x00007fff9f2fc235 libdyld.dylib`start + 1
```

**Comment by BevapDin** [comment] 2017-08-15 15:07
Duplicate of #21618.

**Closed by BevapDin** 2017-08-15 15:07 UTC
