### ISSUE TITLE
Crash in build 8195 on loading

### ISSUE THREAD

**Issue by ActuallyUlysses** [CleverRaven/Cataclysm-DDA#26780] opened 2018-11-20 13:52 UTC
**Describe the bug**
After updating from 8192>8195 game crashes after loading all assets (CTD), right before it should display game world

**To Reproduce**
1. Attempt to load the game
2. Observe CTD

**Expected behavior**
The game world should load... duh

**Screenshots**  
n/a

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version 0.C-34714-g771c9e4
 - Graphics version Tiles (SomeDeadGuy)
 - Mods loaded 
  "dda",
  "filthy_morale",
  "npc_traits",
  "mutant_npcs",
  "zets_hair_extensions",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "FujiStruct",
  "boats",
  "TATTOOMOD",
  "WHALEYCASSETTE",
  "sleepdeprivation",
  "offspring",
  "add_ebook"

**Additional context**  
I am pretty sure it has to do something with lighting changes. My character is in the lab and while I cannot see any lamps, they are definitely loaded and some tiles that they are lighting up are visible.

Also, just IMAGINE how many threads about this issue would pop up on reddit if only it was not on strike because GDPR or smth (... GDPR expert btw).

**Comment by GoLoT** [comment] 2018-11-20 13:59
Duplicate of #26777

**Closed** 2018-11-20 14:20 UTC
