### ISSUE TITLE
This character has been... Dead. on. Arrival.

### ISSUE THREAD

**Issue by Kanexan** [CleverRaven/Cataclysm-DDA#36487] opened 2019-12-27 06:52 UTC
# Describe the bug

When starting a new game using the Helicopter Crash scenario, the player immediately has all limbs break, and head and torso are automatically at zero.

# Steps To Reproduce

To reproduce:
1. Start new game with a character utilizing the Helicopter Crash scenario.
2. Character will die immediately.
3. If "Yes" is selected at "Watch the last moments of your life?", game will crash.

# Expected behavior

The player character to spawn without dying on the spot, and the "Watch" action to not crash the game.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-10722-ge794893
 - Graphics version: Tiles
 - Mods loaded: No NPC Needs

# Additional context

I would include a save file and game report, but the character's death is quite literally instantaneous upon starting.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4004487/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4004488/debug.log)

**Comment by anothersimulacrum** [comment] 2019-12-27 07:00
I can't reproduce this locally, but talking with someone who could, we narrowed it down to #36470 as the cause.

**Comment by Kanexan** [comment] 2019-12-27 07:07
Okay, so it turns out that at least for me, this bug actually extends to starting any character in any scenario. They are all dying in the exact same manner on the moment of the game's start.

**Comment by kevingranade** [comment] 2019-12-27 09:56
Alternately, working as intended, you need to make a hundred thousand characters before you find one that didn't die immediately.

**Comment by kevingranade** [comment] 2019-12-27 09:57
Fixed by #36489

**Closed by kevingranade** 2019-12-27 09:57 UTC
Labels: <Bug>, Character / World Generation, Scenarios
