### ISSUE TITLE
Picking up Cattle Fodder duplicates it.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#40757] opened 2020-05-22 20:29 UTC
When picking up Cattle Fodder pick up a single piece of it, the pickup 2nd piece in two separate actions. When you pick-up 2nd piece it will ask you to hold second piece in your had as if you had run out of volume. If you choose to cancel picking up the 2nd piece it will create a copy of it in your bag, while also having original on the ground.

![image](https://user-images.githubusercontent.com/430076/82706597-7f550980-9c69-11ea-999c-c12e6b0f5ef7.png)

This is the character equipment:
![image](https://user-images.githubusercontent.com/430076/82706696-d4911b00-9c69-11ea-987e-a64a654b134b.png)

I am using latest git pull on master branch at the time of writing this.

**Comment by KorGgenT** [comment] 2020-05-24 18:49
Duplicate of #40444

**Closed by KorGgenT** 2020-05-24 18:49 UTC
