### ISSUE TITLE
Foot Encumbrance affecting stats not associated with it, while torso Encumbrance does nothing.

### ISSUE THREAD

**Issue by Beatdotroot** [CleverRaven/Cataclysm-DDA#52418] opened 2021-10-24 04:49 UTC
### Describe the bug

Torso Encumbrance currently does not affect the Melee attack rolls modifier and Melee and thrown attack movement point modifier. However, said modifiers are directly affected by foot encumbrance instead.

### Steps To Reproduce

1: Wear several heavily encumbering torso articles.
2: Check torso in encumbrance tab: see the unaffected modifiers.
3: Wear any type of encumbering footwear
4: Check torso in encumbrance tab: see the modifiers being changed.

### Expected behavior

I expected that torso encumbrance would affect the modifiers in the torso tab, not foot encumbrance.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2c5d673 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod]
]

**Comment by wapcaplet** [comment] 2021-11-24 17:20
Maybe related to or duplicate of #52109 and/or #50915

**Comment by Inglonias** [comment] 2021-12-03 15:26
This is fixed by #53070. Can we close it?

**Closed** 2021-12-03 20:37 UTC
Labels: <Bug>, Info / User Interface, (S2 - Confirmed), (P2 - High), Mechanics: Character / Player
