### ISSUE TITLE
Black box after specified popup windows.

### ISSUE THREAD

**Issue by mutt3x** [CleverRaven/Cataclysm-DDA#15486] opened 2016-02-19 22:54 UTC
64bit, win-tiles (no tiles), build 4438 no mods, the issue is around for some time now.

**Note that i am having problems reproducing this since its not a constant/direct bug. It happens here and there, othertimes not but its definitely something about thouse popup screens.**

**Reproducing:**
Kill a zombie.
Try to butcher his body while another zombie is inside a house making noises.
**This appears:**
![popup1](http://i.imgur.com/mD9brjt.png)
Press (I)gnore or whatever and this black box is left behind:
![bug1](http://i.imgur.com/AKxUwvq.png)

For me the issue mostly appears on that popup.
The main problem here is that the black box stays on the screen while you move unless you clear it by simply opening and closing the inventory.

It happens sometimes (more rarely) on these popups as well:
![popup2](http://i.imgur.com/tLFQ4DQ.png)
...and screenshot of the bug after closing the window. Thouse dots inside the black box where refreshed by rain lol:
![bug2](http://i.imgur.com/5oZQxxU.png)

There was a similar issue that got fixed regarding another window. Almost the same thing, just cant find it.

EDIT: This happens in tiles as well, not just the tiles turned off mode.

_phew_

**Comment by DanmakuDan** [comment] 2016-02-22 19:02
The problem should only be a missing screen refresh after those prompts.

**Comment by kevingranade** [comment] 2017-06-19 04:32
I can't reproduce, but it seems to be because map::pl_sees() is returning the wrong value.  My guess is that the map cache is invalid at the point when sound processing occurs.

**Comment by Leland** [comment] 2017-08-24 03:02
Cannot reproduce. Closing. @kevingranade obviously feel free to reopen if you want to track that code issue here.

**Closed by Leland** 2017-08-24 03:02 UTC
Labels: Information / Interface
