### ISSUE TITLE
Can't compile on raspberry pi 2

### ISSUE THREAD

**Issue by comword** [CleverRaven/Cataclysm-DDA#14540] opened 2015-12-21 06:50 UTC
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os -Wall -Wextra   -Werror --std=c++11 -MMD -I/usr/include/lua5.2  -DLUA -I/usr/include/ncursesw -c src/catacharset.cpp -o obj/catacharset.o
In file included from src/catacharset.cpp:5:
src/wcwidth.h:76:11: error: comparison of integers of different signs: 'wchar_t' and 'const int' [-Werror,-Wsign-compare]
  if (ucs < table[0].first || ucs > table[max].last)
      ~~~ ^ ~~~~~~~~~~~~~~
src/wcwidth.h:76:35: error: comparison of integers of different signs: 'wchar_t' and 'const int' [-Werror,-Wsign-compare]
  if (ucs < table[0].first || ucs > table[max].last)
                              ~~~ ^ ~~~~~~~~~~~~~~~
src/wcwidth.h:80:13: error: comparison of integers of different signs: 'wchar_t' and 'const int' [-Werror,-Wsign-compare]
    if (ucs > table[mid].last)
        ~~~ ^ ~~~~~~~~~~~~~~~
src/wcwidth.h:82:18: error: comparison of integers of different signs: 'wchar_t' and 'const int' [-Werror,-Wsign-compare]
    else if (ucs < table[mid].first)
             ~~~ ^ ~~~~~~~~~~~~~~~~
4 errors generated.
Makefile:541: recipe for target 'obj/catacharset.o' failed
make: *** [obj/catacharset.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by sparr** [comment] 2015-12-21 09:09
Good find! The standard doesn't specify that wchar_t is signed, and apparently it's not in your environment. Do a non-release compile (to disable -Werror) and post here all such warnings so we can fix them in one pass?

**Comment by comword** [comment] 2015-12-21 14:06
/usr/include/ncursesw -c src/defense.cpp -o obj/defense.o
CCACHE_CPP2=1 ccache clang++  -DGIT_VERSION -DLOCALIZE -ffast-math -O0 -Wall
-Wextra -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD -I/usr/include/lua5.2  -DLUA -I
/usr/include/ncursesw -c src/mapbuffer.cpp -o obj/mapbuffer.o
CCACHE_CPP2=1 ccache clang++  -DGIT_VERSION -DLOCALIZE -ffast-math -O0 -Wall
-Wextra -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD -I/usr/include/lua5.2  -DLUA -I
/usr/include/ncursesw -c src/weather.cpp -o obj/weather.o
^CMakefile:541: recipe for target 'obj/defense.o' failed
make: *** [obj/defense.o] Interrupt
Makefile:541: recipe for target 'obj/weather.o' failed
make: *** [obj/weather.o] Interrupt
Makefile:541: recipe for target 'obj/game.o' failed
make: *** [obj/game.o] Interrupt
Makefile:541: recipe for target 'obj/mapbuffer.o' failed
make: *** [obj/mapbuffer.o] Interrupt
 
henorvell@raspberrypi ~/Cataclysm-DDA $
-Wextra -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD -I/usr/include/lua5.2  -DLUA -I
/usr/include/ncursesw -c src/weather.cpp -o obj/weather.o
    if (ucs > table[mid].last)-DGIT_VERSION -DLOCALIZE -ffast-math -O0 -Wall
        ~~~ ^ ~~~~~~~~~~~~~~~--std=c++11 -MMD -I/usr/include/lua5.2  -DLUA -I

**Comment by comword** [comment] 2015-12-21 14:16
In file included from src/catacharset.cpp:5:
src/wcwidth.h:76:11: warning: comparison of integers of different signs: 'wchar_t' and 'const int' [-Wsign-compare]
  if (ucs < table[0].first || ucs > table[max].last)
      ~~~ ^ ~~~~~~~~~~~~~~
src/wcwidth.h:76:35: warning: comparison of integers of different signs: 'wchar_t' and 'const int' [-Wsign-compare]
  if (ucs < table[0].first || ucs > table[max].last)
                              ~~~ ^ ~~~~~~~~~~~~~~~
src/wcwidth.h:80:13: warning: comparison of integers of different signs: 'wchar_t' and 'const int' [-Wsign-compare]
    if (ucs > table[mid].last)
        ~~~ ^ ~~~~~~~~~~~~~~~
src/wcwidth.h:82:18: warning: comparison of integers of different signs: 'wchar_t' and 'const int' [-Wsign-compare]
    else if (ucs < table[mid].first)
             ~~~ ^ ~~~~~~~~~~~~~~~~
4 warnings generated.

**Comment by comword** [comment] 2015-12-21 14:45
Another issue:
compling cata_test drained 1GB memory.
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
Makefile:519: recipe for target 'cataclysm' failed

**Comment by kevingranade** [comment] 2015-12-21 17:43
Not much we can do about that one I'm afraid, cata is just a really big
application.

**Comment by sparr** [comment] 2015-12-21 18:12
@comword those four are the only warnings? great, super easy fix.

**Comment by comword** [comment] 2015-12-22 06:20
@sparr Thanks.

**Comment by illi-kun** [comment] 2015-12-22 20:30
Is it duplicate of #14161?

**Comment by sparr** [comment] 2015-12-22 20:33
duplicate of #14161

**Closed by sparr** 2015-12-22 20:33 UTC
