### ISSUE TITLE
Entire area is filled with aphids

### ISSUE THREAD

**Issue by Lyrcanrolf** [CleverRaven/Cataclysm-DDA#69610] opened 2023-11-21 12:46 UTC
### Describe the bug

During a portal storm, my entire location has become populated by a thousand aphids which bogs the game down greatly. No errors message popped up during the entire scenario which made their abrupt appearance to be a rather confusing event.

### Attach save file

[Encinal-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13426306/Encinal-trimmed.tar.gz)

### Steps to reproduce

I truly have no clue about how this situation came to be, so the steps in reproducing this behaviour is unknown.

### Expected behavior

Not having the aphids suddenly appear.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/143777503/9a87286a-11bc-48e3-9451-7740633a5efe)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3693 (21H2)
- Game Version: 8e02002 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter]
]

**Comment by fairyarmadillo** [comment] 2023-11-21 13:36
I am away from my PC for the next week. If this needs an emergency revert then go for it, but if someone wants to troubleshoot:

In monster.cpp

Line 3217: I added a check that lets monsters breed on screen. It has a one in 30000 chance to happen every second, so it should not reliably be firing more than three times a day or so.

Line 555: All I really changed in try_reproduce was line 603, which changes the breeding chance from 50% to 33% if the animal is underfed.

I didn't test aphid breeding specifically, but I did test roaches, goats, and cows and they weren't laying tons of eggs. Cockroaches have a shorter baby timer than aphids, even.

Any thoughts?

**Comment by fairyarmadillo** [comment] 2023-11-21 13:40
The changes to baby_timer stuff were originally made in #66294 and only pushed out to other animals when I saw that it didn't break roaches, so checking the diffs in monster.cpp there might shed some light.

**Comment by fairyarmadillo** [comment] 2023-11-21 22:08
Just an update in case anyone was looking at this: someone has mentioned that changing 
if( *baby_timer > calendar::turn )
to 
if( !baby_timer || *baby_timer > calendar::turn )
in monster.cpp appears to fix the problem. I think they might PR it but they seem a little busy at the moment.

**Comment by RenechCDDA** [comment] 2023-11-22 01:02
I'll try to take a longer look at it today. We had a few contributors poking it in the development discord, but not a ton of progress.

**Comment by fairyarmadillo** [comment] 2023-11-22 01:28
> I'll try to take a longer look at it today. We had a few contributors poking it in the development discord, but not a ton of progress.

The issue seems to be that baby_timer isn't initialized anywhere, which is why the above code fixes it.

**Comment by akrieger** [comment] 2023-11-23 04:31
Pretty sure I separately ran into this same issue with baby_timer being nullopt and forgot to PR it. I'll take care of it now.

**Comment by CoroNaut** [comment] 2023-11-23 18:25
I also have issue with tons of aphids lol
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/9d35c82d-1193-44e9-b718-211ace4d45a1)
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5c2611d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by akrieger** [comment] 2023-11-23 23:46
After my fix youll have to kill or debug kill them but they shouldn't spawn out of control after.

**Comment by LyleSY** [comment] 2023-11-26 14:53
Fixed by #69665

**Closed by LyleSY** 2023-11-26 14:53 UTC
Labels: (S2 - Confirmed), [C++], Monsters
