### ISSUE TITLE
Running an engine until it dies from lack of fuel does not properly delete the phantom fuel

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46755] opened 2021-01-15 02:58 UTC
# Describe the bug

~An engine with 0.0L of fuel in it cannot be drained without causing an error. It cannot be refilled, either, because I do not have JP8 fuel.~

More precisely, running an engine, diesel or gas, with any type of fuel until its fuel is depleted will leave the engine in an in-between state with 0.0L of fuel shown as remaining. Saving/quitting and resuming will cause the display to update to 0.3L, and allow it to be siphoned and cleared.

Additionally, while the engine is in the in-between state, infinite fuel may be siphoned under particular circumstances, 250mL at a time.

# Steps To Reproduce

Big ups to @int-ua for doing more legwork to nail down more-easily reproducible steps.

> Confirmed on build 11360. Please update the steps to reproduce:
> 
> 1. Spawn undamaged portable generator vehicle.
> 2. (optional) siphon fuel until only a small amount is left.
> 3. Run it.
> 4. (maybe optional) Remove the battery.
> 5. Wait until the fuel reaches volume 0.
> 6. Observe that the engine didn't die and there is an invalid amount of fuel, 0.
> 7. Try siphoning fuel into a container and on the ground.
> 8. **If you do it near a bathtub you get the free infinite fuel.**

~1. Load attached save.~
~2. Attempt to do anything with the 0.0L of JP8 in the power grid's engine.~

# Expected behavior

I expected it to show no fuel type, or let me remove the fuel that's there.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-8965-gad0e7ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

```
DEBUG    : Tried to drain something without any liquid: <color_c_light_green>||</color> vehicle tank (20L) amount: 0 ammo: 0

FUNCTION : int vehicle::drain(int, int)
FILE     : src/vehicle.cpp
LINE     : 3408
```

```
DEBUG    : Tried to drain something without any liquid: <color_c_light_green>||</color> vehicle tank (20L) amount: 250 ammo: 0

FUNCTION : int vehicle::drain(int, int)
FILE     : src/vehicle.cpp
LINE     : 3408
```

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5818124/Woodcock.zip)

**Comment by BrettDong** [comment] 2021-01-15 03:19
I loaded your save, and "power grid" shows there is 0.3L JP8 fuel left in vehicle tank. I can drain and refill JP8 fuel from/into the vehicle tank without any problem.

**Comment by ToxiClay** [comment] 2021-01-15 03:20
That's very weird, because it definitely didn't work for me. One sec, let me reload my save????

After a complicated dance involving the debug menu, musical bottles, and three goats, I was able to clear it, but it was weird, because it was definitely acting strange.

**Comment by ToxiClay** [comment] 2021-01-15 03:23
OK...on a reload, *now* I'm seeing 0.3L. What the hell happened? Here's the full stack backtrace from when the errors were ocurring, if it helps. Swear to God, it was happening; I'm not crazy.


[StackTrace.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5818238/StackTrace.txt)

**Comment by ToxiClay** [comment] 2021-01-15 09:03
It happened to me again just now. @BrettDong -- if you could, reload the attached save, replace the JP8 fuel with diesel, and let it run to exhaustion. Then you should be able to replicate what I saw.

**Comment by Svankensen** [comment] 2021-01-15 12:31
It's happened to me too. Engine wouldn't even turn on. In my case it was with dirty gas too, so it was a diferent mess.

**Comment by int-ua** [comment] 2021-01-15 13:38
I suggest we collect such cases in #27681

**Comment by ToxiClay** [comment] 2021-01-16 03:13
Here is a video demonstrating the core bug.

https://user-images.githubusercontent.com/13796683/104795780-d40c3e00-577e-11eb-9d99-39d7bd790031.mp4

**Comment by ToxiClay** [comment] 2021-01-16 03:58
```
vehicle.cpp:4962
if( engine_epower < 0 ) {
            // Not enough epower to run gas engine ignition system
            engine_on = false;
            if( player_in_control( player_character ) || player_character.sees( global_pos3() ) ) {
                add_msg( _( "The %s's engine dies!" ), name );
            }
        }
```
Because this is the part of the code that handles an engine being out of fuel (and thus unable to generate `engine_epower`), I suspect this will end up being the right place to put a sneaky code patch once we determine what it should look like.

**Comment by int-ua** [comment] 2021-01-16 04:03
Confirmed on build 11360. Please update the steps to reproduce:

1. Spawn undamaged portable generator vehicle.
2. (optional) siphon fuel until only a small amount is left.
3. Run it.
3. (maybe optional) Remove the battery.
4. Wait until the fuel reaches volume 0.
5. Observe that the engine didn't die and there is an invalid amount of fuel, 0.

**Comment by ToxiClay** [comment] 2021-01-16 04:05
From `veh_interact.cpp:1949`, I suspect `veh->drain( idx, liq_charges - liquid.charges )` might be the appropriate patch to use, assuming it can be massaged to "drain" 0 fuel into a phantom container and then delete itself.

**Comment by olanti-p** [comment] 2021-07-14 08:02
Possible fix:
https://github.com/cataclysmbnteam/Cataclysm-BN/commit/4e72346f1ed6e71f09b7d5551fac6d0aa158d93f

**Comment by hexagonrecursion** [comment] 2021-08-12 14:22
> Confirmed on build 11360. Please update the steps to reproduce:
> 
>     1. Spawn undamaged portable generator vehicle.
> 
>     2. (optional) siphon fuel until only a small amount is left.
> 
>     3. Run it.
> 
>     4. (maybe optional) Remove the battery.
> 
>     5. Wait until the fuel reaches volume 0.
> 
>     6. Observe that the engine didn't die and there is an invalid amount of fuel, 0.
> 
>     7. Try siphoning fuel into a container and on the ground.
> 
>     8. **If you do it near a bathtub you get the free infinite fuel.**

Could not reproduce. Probably fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/50000

![0L](https://user-images.githubusercontent.com/52621858/129213717-161a9e03-b2b7-4e7b-9223-bd23d847a5dd.png)
![die](https://user-images.githubusercontent.com/52621858/129213724-67037fd2-5d52-4359-ae41-5ba10e5c559d.png)

**Closed** 2021-08-12 15:02 UTC
Labels: (S1 - Need confirmation), Vehicles
