### ISSUE TITLE
interactable menus collapsing 

### ISSUE THREAD

**Issue by tw1st31337** [CleverRaven/Cataclysm-DDA#77191] opened 2024-10-20 11:38 UTC
### Describe the bug

menu collapses, for example you cant see how you can interact with an item (because it also keeps spazzing out)

### Attach save file

N/A

### Steps to reproduce

go into inventory
press enter on an item
:(

### Expected behavior

i expect the menu to show me all the interactions

### Screenshots

![image](https://github.com/user-attachments/assets/a5d9a220-ca28-4a3e-ba95-cd7819538154)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 74e77cc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Dark Days of the Dead [classic_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No filthy clothes [idon'twanttoclean]
]

### Additional context

very sad :(

**Comment by tw1st31337** [comment] 2024-10-20 11:43
(btw it happened RANDOMLY, idk why)

**Comment by Brambor** [comment] 2024-10-20 14:57
If you (or anyone) reproduce it, please share the reproduction steps!

Nobody can do anything except for bug hunting or putting it to the back of their head.

**Comment by tw1st31337** [comment] 2024-10-20 15:29
yeah i tried slamming my keyboard and checking out the options but nothing reverted it or anything

**Comment by Nebnis** [comment] 2024-10-20 15:48
I can confirm this happening to me too, unfortunately i cant reproduce because restarting the game does not fix it. It is permanently stuck this way

**Comment by tw1st31337** [comment] 2024-10-20 16:02
> [mord0d](/mord0d)

yeah, what i mean is it happened randomly and now it wont go away so i cant do anything if i dont know all the keybinds by memory

**Comment by Faalagorn** [comment] 2024-10-20 20:25
It seems to be the same issue for me

**Comment by IdleSol** [comment] 2024-10-20 21:07
cdda-windows-tiles-x64-2024-10-20-0346 bug free.
Next version: cdda-windows-tiles-x64-2024-10-20-0906 with bug

**Comment by dik1337** [comment] 2024-10-20 21:49
I'm also having this bug on 2024-10-20-1406.

**Comment by Brambor** [comment] 2024-10-21 02:01
I will look into this. Once the game compiles...

**Comment by Brambor** [comment] 2024-10-21 03:30
Workaround / The bug:

The wrong category is selected, when I press RIGHT arrow, it goes from this
![image](https://github.com/user-attachments/assets/83d45bb6-d296-4b3d-9037-0e80f90e9381)

To this
![image](https://github.com/user-attachments/assets/48d3535f-1dbf-463e-9e44-31272cb59a45)

**Comment by db48x** [comment] 2024-10-21 03:31
Oh, fun. Let me take a look as well.

**Comment by Brambor** [comment] 2024-10-21 03:33
I will leave it up to you then, since you know the ins and outs of this code :)

**Comment by db48x** [comment] 2024-10-21 03:34
No! Don’t stop! You have the advantage of being able to reproduce it. What keys are you pressing to get into this state? I opened my inventory and hit enter to select and item, and it looks fine to me…

**Comment by Brambor** [comment] 2024-10-21 03:36
You need to:
1. open AIM
2. examine item

Does this reproduce it for you?

**Comment by db48x** [comment] 2024-10-21 03:37
No :(

**Comment by Brambor** [comment] 2024-10-21 03:38
Huh, I wonder why. I am on 74e77cc63d

**Comment by db48x** [comment] 2024-10-21 03:39
Let me try that specific commit.

**Comment by Brambor** [comment] 2024-10-21 03:41
What were you trying? Master? Maybe it mysteriously fixed itself? Let me know, I will try it out.

**Comment by db48x** [comment] 2024-10-21 03:41
I was on my commit from before it was merged into master.

**Comment by db48x** [comment] 2024-10-21 03:42
8b126eb5ef

**Comment by db48x** [comment] 2024-10-21 03:44
Aha! Now I can reproduce it.

**Comment by Brambor** [comment] 2024-10-21 03:47
I will look at another bug and leave this up to you then. I would hate to duplicate the work :)

**Comment by db48x** [comment] 2024-10-21 03:47
Thank you!

**Comment by db48x** [comment] 2024-10-21 04:13
Heh, oops.

**Comment by db48x** [comment] 2024-10-21 04:27
Much better:

https://github.com/user-attachments/assets/463fb11e-12ec-454f-b588-b397dda797ba

**Comment by tw1st31337** [comment] 2024-10-21 14:25
id like to say that this is still not fixed for me 
![image](https://github.com/user-attachments/assets/0601d406-6235-4ebf-9577-41c67de6a514)
same exact thing as in the original report    ^^

**Comment by Brambor** [comment] 2024-10-22 01:00
It should be fixed since 2024-10-21-1656 @tw1st31337

**Comment by tw1st31337** [comment] 2024-10-24 15:03
guys, guess what, it was fixed and now its broken again
![image](https://github.com/user-attachments/assets/e77a105b-4e7c-416d-9ce6-c98430792307)

**Comment by db48x** [comment] 2024-10-25 03:20
Yep. Last night I got as far as making sure that it was a regression, and doing a bisection. b4838b3a9f21192e244d36dd2628a2f41be3694f definitely fixed the bug, and it was definitely broken afterwards. Unfortunately the bisection was a bit wonky because there are commits that don’t build so I haven’t figured yet out which commit actually broke it. Now that I’ve slept and eaten I may be able to figure it out.

**Comment by Brambor** [comment] 2024-10-25 03:27
It might be different cause, but it is the same issue. Good luck!

**Comment by dik1337** [comment] 2024-10-25 03:36
> Yep. Last night I got as far as making sure that it was a regression, and doing a bisection. [b4838b3](https://github.com/CleverRaven/Cataclysm-DDA/commit/b4838b3a9f21192e244d36dd2628a2f41be3694f) definitely fixed the bug, and it was definitely broken afterwards. Unfortunately the bisection was a bit wonky because there are commits that don’t build so I haven’t figured yet out which commit actually broke it. Now that I’ve slept and eaten I may be able to figure it out.

Thank you for your hard work! This is an annoying bug, to be sure.

**Closed** 2024-10-25 14:49 UTC
Labels: Info / User Interface, (S2 - Confirmed)

**Comment by db48x** [comment] 2024-10-26 01:33
Thank you, but those are different bugs. Wrapping is already filed as #76513.
