### ISSUE TITLE
Light sources inside pockets should not work

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#49188] opened 2021-06-05 17:03 UTC
# Is your feature request related to a problem? Please describe.
Currently light sources like flashlights can shine through your pockets, providing 100% of intended light.

# Describe the solution you'd like
Pockets/bags containing working light source should block passing of light, unless translucent.

# Describe alternatives you've considered
Make light sources prive light only when held or piece of clothing you are wearing. 
Making lamps and flashlights into pieces of clothing which restrict using both hands similarly to a swag bag, to simulate holding it in your other hand.

# Additional context
This should provide more realism and make equipment like headlamps and light amp goggles
 more viable.

**Comment by anothersimulacrum** [comment] 2021-06-05 21:03
The problem with this is that your character can only hold one thing at a time, and I think this is a better state than it would be otherwise until a character can hold multiple things.

**Comment by Igryn** [comment] 2021-06-05 22:05
> The problem with this is that your character can only hold one thing at a time, and I think this is a better state than it would be otherwise until a character can hold multiple things.

I might be wrong, but i think that holding multiple things is not intended according to project leaders. 
Simplest and best solution, i think, is to make them emit light only when dropped on a tile, held and/or worn in your palm like said swag bag, so they occupy your second grasping limb in that way.

**Comment by Theawesomeboophis** [comment] 2021-06-05 22:05
I think it would be better to have light only partially be available when in a pocket, I think some light would be seeable while in at least a pants pocket ( not sure, I've never shoved a flashlight into my pocket before), but it definetly should not show all light when contained.

**Comment by Theawesomeboophis** [comment] 2021-06-05 22:11
Nevermind, just tested IRL, it shouldn't show any light at all in a pocket.

**Comment by Maleclypse** [comment] 2021-06-06 02:35
> > The problem with this is that your character can only hold one thing at a time, and I think this is a better state than it would be otherwise until a character can hold multiple things.
> 
> I might be wrong, but i think that holding multiple things is not intended according to project leaders.
> Simplest and best solution, i think, is to make them emit light only when dropped on a tile, held and/or worn in your palm like said swag bag, so they occupy your second grasping limb in that way.

anothersimulacrum is on the dev team and I've seen several conversations where this state has been agreed to be acceptable until two independent hands exist and we can differentiate between two handed weapons and a one handed weapon with a flashlight in the other hand.

**Comment by eltank** [comment] 2021-06-06 02:58
Given that wearable lights (headlamps / mining helmets) are extremely easy to craft or loot and don't impact the character's fighting ability at all, I don't see why we would need to break realism in order to allow flashlights stored in a backpack or jacket pocket to shine through. Not to mention the fact that taking 3 turns to activate a flashlight from inventory in the middle of combat could result in injury/death (e.g. due to a shady brute).
I don't think I've played a single run of CDDA in which I didn't have a headlamp (normal / survivor / atomic / CBM variants) permanently equipped.

**Comment by KittyTac** [comment] 2021-06-09 11:37
I think it represents carrying the flashlight in your off-hand. I'm fine with this until an off-hand is implemented.

**Comment by anothersimulacrum** [comment] 2021-09-15 20:15
Duplicate of  #16461

**Closed by anothersimulacrum** 2021-09-15 20:15 UTC
Labels: (S3 - Duplicate), <Enhancement / Feature>, Game: Balance, <Exploit>, Items / Item Actions / Item Qualities, Items: Containers
