### ISSUE TITLE
Canned items are spawning opened again

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#40127] opened 2020-05-04 06:41 UTC
# Describe the bug

Canned items are spawning opened rather than sealed. 

# Steps To Reproduce

1. Create a new world. Spawn a character.
2a. Teleport around until you find somewhere with canned goods. (I looked at both an evac shelter and a house.)
2b. Alternatively, use debug spawn to spawn a canned item. The can spawns opened.
3. Optionally, accelerate time to confirm that the items do rot.

# Expected behavior

Canned goods should spawn sealed, rather than opened as if some passive aggressive survivor had been through the area prior.
This bug also prevents storing canned goods in clothes, since they must be sealed for that to be possible.

# Screenshots

![image](https://media.discordapp.net/attachments/598523535169945607/706753817269633084/unknown.png)
![image](https://media.discordapp.net/attachments/598523535169945607/706754140210200687/unknown.png) after 20 days 
![image](https://media.discordapp.net/attachments/598523535169945607/706755603342819428/unknown.png)

# Versions and configuration

OS: Windows 10
Version: 0.E-1713-gd15c896
Graphics: Tiles
Language: English
Mods: 
![image](https://user-images.githubusercontent.com/42950339/80941517-8211bc80-8d97-11ea-8003-87f89763e89f.png)

# Additional context

None

**Comment by Kanexan** [comment] 2020-05-04 17:26
From what I've seen, this is only the case for medium tin cans for some reason. I've been able to pick up large tin cans without needing to unload them, and they're still considered sealed as well.

**Comment by TheMurderUnicorn** [comment] 2020-05-05 00:07
Naw, also an issue with small cans.  Can't stow them, presumably because they're 'open'.  
![image](https://user-images.githubusercontent.com/41651793/81024884-cad27f80-8e42-11ea-9b54-b6aaca86fb48.png)

**Comment by Resok** [comment] 2020-05-05 05:35
I found this issue also - 

https://github.com/CleverRaven/Cataclysm-DDA/issues/40180

If I use the debug menu to spawn in a container it seems to remain sealed but any items that were sealed previously are flagged as unsealed.

I believe this is related to the pockets change -

![image](https://user-images.githubusercontent.com/5217673/81036446-00339900-8e54-11ea-8a8e-41b07c6bf5f6.png)

**Comment by Emotions211** [comment] 2020-05-16 00:41
A workaround for not being able to pickup items and immediately store them automatically is to (w)eild the item, open your (i)nventory and (i)nsert it into a pocket. However this takes a few turns to accomplish. However I'm only having this issue with canned drinks like Energy Drinks and Sodas. Spilling them also gives you a frozen liquid that can only be dropped. Thawing it spills it onto the ground with no dialogue for choosing what to do with it.

**Comment by Elpyfo** [comment] 2020-05-21 16:18
Issue #40658 contains a save file in case for this  issue in case it helps.

**Comment by DillonSimeone** [comment] 2020-05-24 04:23
Running around.

![image](https://user-images.githubusercontent.com/21962421/82745603-353c5880-9d3b-11ea-8a1a-09627ee026e9.png)

![image](https://user-images.githubusercontent.com/21962421/82745619-69177e00-9d3b-11ea-9aaf-e1d46467c704.png)

![image](https://user-images.githubusercontent.com/21962421/82745635-8e0bf100-9d3b-11ea-91f9-ed13641ad0f9.png)

![image](https://user-images.githubusercontent.com/21962421/82745642-a8de6580-9d3b-11ea-90f8-e61ed9d80b77.png)


All seems to be well. Spotted canned stuff in houses too, no issues with those.

**Comment by DillonSimeone** [comment] 2020-05-24 05:10
Turns out that this happens with `Can of x drink`, not canned foods/soup. 

You can reproduce this bug with the overmap editior as shown below:

Placing house_01 on the overmap in ungenerated areas then teleporting over.
![image](https://user-images.githubusercontent.com/21962421/82745928-b3e6c500-9d3e-11ea-8281-736c80f401af.png)

![image](https://user-images.githubusercontent.com/21962421/82745948-f3adac80-9d3e-11ea-80ee-46d7643580d2.png)

Walk into a placed house with a fridge AND cans in it, then attempt to pick up a can...
![image](https://user-images.githubusercontent.com/21962421/82745961-1e980080-9d3f-11ea-9b0f-1478df407de9.png)

![image](https://user-images.githubusercontent.com/21962421/82745954-0fb14e00-9d3f-11ea-96b6-38c3d8b59f4b.png)

Double check that I'm in the houses I placed...

![image](https://user-images.githubusercontent.com/21962421/82745970-33749400-9d3f-11ea-97fb-541a885aeadd.png)

**Comment by kevingranade** [comment] 2020-06-22 00:34
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-store-cans-and-some-other-items-in-my-inventory/23996/12

**Comment by EpicMarble** [comment] 2020-06-22 10:49
Based on limited testing, I've noticed that cans of beer will spawn opened in homes, but closed in bars and grocery stores.

![2020-06-22-1000-6884](https://user-images.githubusercontent.com/8071670/85279470-bf84f300-b486-11ea-936e-f8bdc87a5049.png)

![2020-06-22-1000-6885](https://user-images.githubusercontent.com/8071670/85279491-cad81e80-b486-11ea-9c5b-d56df664026b.png)

**Comment by olanti-p** [comment] 2020-06-26 14:12
Another way to reproduce is to debug spawn NPCs.
For every dozen NPCs there are 1-2 popups of `What to do with the chocolate drink (1)?`
The dialogue spam may be a bit annoying, but that's solved with a pair of ear plugs

**Closed** 2020-07-02 23:16 UTC
Labels: <Bug>, Inventory / AIM / Zones, Items: Containers
