### ISSUE TITLE
Zones get saved to file immediately on creation

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#57443] opened 2022-05-05 13:26 UTC
### Describe the bug

When you add zones, they get saved immediately to the save file, instead of waiting for a regular save. As far as I'm aware, nothing else gets saved immediately like this, so zones shouldn't either.

I'm fairly certain this is happening for mapgen placed zones as well, which should not exist at the time I am loading my saves.

### Steps to reproduce

1. Save game
2. Shift+Y to open the zone manager.
3. A to add a zone. Select zone points to confirm zone placement.
4. Press escape and confirm saving of zones.
5. Kill the game (Alt+F4)
6. Load save from 1. See zones existing.

### Expected behavior

Zones should wait to save with everything else to prevent weird scenarios of zones existing from future states of the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 0.F-8083-g1293340378-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment] 2022-05-05 13:27
/confirmed

This is quite annoying when debugging but irrelevant for regular play since savescumming is not supported

**Comment by haveric** [comment] 2022-05-05 13:30
> This is quite annoying when debugging but irrelevant for regular play since savescumming is not supported

Agreed, but I've definitely had games crash due to unknown bugs and had to reload a save, which could expose this as well.

**Comment by ZaricaDemoni** [comment] 2022-05-06 02:06
While savescumming may not be supported I do have to agree with Haveric here, as someone who tends to play on experimental (as in regular play), having a bug crash me and then reloading my game due to said crash, this does end up showing up.

**Comment by I-am-Erk** [comment] 2022-05-06 05:40
I wonder if we can just serialize zones to a temp file than then is merged with the save at save time?

**Closed** 2022-05-15 18:15 UTC
Labels: (S2 - Confirmed)
