### ISSUE TITLE
NPC Trade UI: `?` inspect produces wonky output for items with long info strings

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#23522] opened 2018-04-17 23:30 UTC
Game version: 0.C-26948-gbbcf229

### Expected behavior

Inspect should produce consistent behavior for all items.

### Actual behavior
Inspect on guns/toolbox/etc (other items with long info strings) produces corrupted layout 

### Steps to reproduce the behavior
Have gun (or toolbox)/have NPC have gun (or toolbox), talk to NPC, open trade, use `?` to inspect gun (or toolbox):

![image](https://user-images.githubusercontent.com/324067/38903979-e9afe85e-42a7-11e8-9c61-8cee66a42d4d.png)
![image](https://user-images.githubusercontent.com/324067/38904008-0d4564b0-42a8-11e8-9f96-02a0e9c70da0.png)

**Comment by Night-Pryanik** [comment] 2020-02-03 08:19
Can't reproduce on 0.D-11860:
![изображение](https://user-images.githubusercontent.com/11132525/73636346-14ae9c80-467f-11ea-91c6-c67e2bc7249d.png)
![изображение](https://user-images.githubusercontent.com/11132525/73636357-1e380480-467f-11ea-9b8f-96d2605cef90.png)

**Comment by Night-Pryanik** [comment] 2020-02-03 08:20
Oh, I think I got it. The text inside the examine window is corrupted when there isn't enough available space in it:
![изображение](https://user-images.githubusercontent.com/11132525/73636562-91da1180-467f-11ea-83c3-667053030fd9.png)

**Comment by wapcaplet** [comment] 2021-11-15 01:24
Possibly resolved by #52572

**Closed** 2021-11-15 01:34 UTC
Labels: NPC / Factions, Info / User Interface, Items / Item Actions / Item Qualities, Controls / Input
