### ISSUE TITLE
Character forgets books and combat stance after existing and reloading.

### ISSUE THREAD

**Issue by Confusum** [CleverRaven/Cataclysm-DDA#30769] opened 2019-05-23 00:15 UTC
# Describe the bug

Whenever I quit from the game and reload, I've noticed that my character forgets what books he's read (they turn red again) and switches to no style combat stance. This gets really annoying for the purpose of recipes as it means you have to read the same book over and over to 'remember' recipes your character hasn't memorized.

# Steps To Reproduce

1.Read some books in game and select a martial art. 
2. Quit the game, preferably with some books and a martial art selected for convenience. 
3. Reload and observe.

# Expected behavior

I would hope my character would remember what books he had read and that he was using Krav Maga before I left him.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3344-gf3049e5
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Bright Nights [brightnights],
    Extended Realistic Guns [realguns],
    Icecoon's Arsenal [ew_pack],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Medieval and Historic Content [Medieval_Stuff],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills]
]
# Additional context

You will have to read some books and select a martial arts style yourself to observe the bug, as the nature of this bug makes it so it will be already 'triggered' the first time you load in. My character has a few books and martial arts styles already on him for your convenience.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3209790/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3209793/save.zip)

**Comment by Ker-Nes** [comment] 2019-05-23 00:37
Worse yet, non memorized recipes in the books that turned red? Can't be used until you recheck the books. If you keep a sizeable library near your crafting station you better reread every single book every time you reload and want to craft something that you have not memorized.

**Comment by Randonx** [comment] 2019-05-23 00:43
Also having this issue.

**Comment by Inglonias** [comment] 2019-05-23 00:57
Duplicate of #30744

**Closed** 2019-05-23 03:30 UTC
