### ISSUE TITLE
Re-Layering UI closes after removing second piece of clothing

### ISSUE THREAD

**Issue by CodeRage2** [CleverRaven/Cataclysm-DDA#21199] opened 2017-06-07 15:35 UTC
When using the "u" key to remove clothing in the "+" re-layering UI it will sometimes close the UI and sometimes not. Very annoying when trying to remove multiple items and you don't know which will or will not close the menu.

**Comment by kolsurma** [comment] 2017-06-09 11:55
Can confirm, after (limited) testing, this always occurs after the second item is removed.

**Comment by kevingranade** [comment] 2017-09-19 07:55
This might be because it exits the menu if you use up your moves, you can test this with the time dialation CBM since it gives you an extrordinarally long turn.

**Comment by int-ua** [comment] 2021-01-26 01:38
Cannot reproduce on relatively fresh experimental, closing.

**Closed by int-ua** 2021-01-26 01:38 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface
