### ISSUE TITLE
cooked burrito much lower calories than advertised

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#28391] opened 2019-02-26 03:39 UTC
**Describe the bug**  
Found uncooked burrito
Located "cooked burrito" recipe in crafting menu: 425 cal, -12 quench, 7 joy

Cooked it. End result: 121 cal, -12 quench, +7 joy

**To Reproduce**  
1. Find an uncooked burrito
2. Complete "cooked burrito" recipe

**Expected behavior**  
Obtain burrito with 425 calories

**Screenshots**  
![burrito_recipe](https://user-images.githubusercontent.com/19255442/53385906-1a1f4500-394e-11e9-8e96-9c34bf4f1546.PNG)

![cooked_end_result](https://user-images.githubusercontent.com/19255442/53385918-21dee980-394e-11e9-9ca4-489f0dc98071.PNG)

**Versions and configuration(please complete the following information):**
 - OS: win 10
 - Game Version: 0.C-37566-g60ad484
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, simplified nutrition

**Comment by int-ua** [comment] 2019-02-26 07:33
Quick workaround: add `"flags": [ "NUTRIENT_OVERRIDE" ],` to the recipe.

**Comment by int-ua** [comment] 2019-02-26 07:36
Looks like #28180 
See this comment also: https://github.com/CleverRaven/Cataclysm-DDA/issues/28180#issuecomment-464930612

**Comment by kevingranade** [comment] 2019-05-07 17:53
Duplicate of #28180

**Comment by kevingranade** [comment] 2019-05-07 18:04
Actually my mistake, the problem here is that there's a frozen burrito that has lower calories than the cooked burrito, that's not how this works, especially since this is pre-cooked frozen.

Frankly, we don't need a frozen burrito item, it's going to stop being frozen over a matter of hours, which at game time 0 has already happened.  If it's cold enough to remain frozen, the temperature adjustments to spoilage should be sufficient to make the spoilage come out ok.

Possible solutions:
Set frozen burrito nutrition to match regular burrito.  This is just a band-aid, but will make things slightly more consistent and technically will resolve this issue.
Remove the frozen burrito item, and replace all instances of it with the regular burrito.

This should be done for any other items that have this frozen/thawed duality as well.

There MIGHT be some other goal being met by having these be seperate items, but I'm skeptical that it's worthwhile considering how irrelevant frozen foods would be as sources of scavengable food after the cataclysm.

**Closed** 2019-06-17 21:42 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Food / Vitamins, Good First Issue
