### ISSUE TITLE
Lab Staff + Medical Resident characters can have an impossible start

### ISSUE THREAD

**Issue by UriyaBA** [CleverRaven/Cataclysm-DDA#51811] opened 2021-09-22 23:40 UTC
### Describe the bug

Sometimes when generating a Lab Staff + Medical Resident character, this happens:
![image](https://user-images.githubusercontent.com/44501176/134435639-c226a8e0-d8f6-41ee-b85d-1be304b2a410.png)

### Steps To Reproduce

1. Make a character with the scenario "Challenge - Lab Staff" and profession "Medical Resident".
2. Repeat until an "impossible start" generates (it only does so every so often).

### Expected behavior

I expect to be able to move my character at the start of the game and not be forced to stay on just one tile.

### Screenshots

![image](https://user-images.githubusercontent.com/44501176/134435639-c226a8e0-d8f6-41ee-b85d-1be304b2a410.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 7a786ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment] 2022-01-05 16:40
I tried this start about a dozen times and could not reproduce the issue.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by hexagonrecursion** [comment] 2022-01-18 21:46
@wapcaplet could not reproduce

**Comment by LeahLuong** [comment] 2022-01-19 00:33
Gotta love that opening lore:

"You were deemed non-essential and made to stay behind during the lab evacuation. Find a way to escape or starve to death."

Starvation speedrun incoming??

**Comment by Night-Pryanik** [comment] 2022-02-03 06:26
Closing as unconfirmed. If this still happens, ping me and I'll reopen the issue.

**Closed by Night-Pryanik** 2022-02-03 06:26 UTC
Labels: (S1 - Need confirmation), Scenarios, Character / World Generation
