### ISSUE TITLE
Brightness is broken on furniture and on long distance travel

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31045] opened 2019-06-01 16:37 UTC
First of all (but the same as #30732) brightness breaks when you travel long distances. It can be fixed by reloading the save. However after I reloaded I noticed there were still some strange things that might not be related to #30732. 

When I reloaded in the brightness was kinda fixed but some spots were still bright (furniture seems to be one)

# Steps To Reproduce

1. Travel a long distance from your starting spot.
2. Notice everything indoors is bright when it shouldn't be.
3. Quit out and reload. Find new weird brightness issues.

# Expected behavior

For light to work like it did like last stable (0.D)

# Screenshots

![image](https://user-images.githubusercontent.com/47362783/58751212-cdc23480-8469-11e9-9e87-d4c4f342f027.png)

In the above picture the table, chairs, and bathroom are lit bright when they shouldn't be. I think it makes sense if the window curtains are bright.

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 9084
 - Graphics version: Tiles
 - Mods loaded:
![image](https://user-images.githubusercontent.com/47362783/58751225-f4806b00-8469-11e9-8591-a972ba96876e.png)

![image](https://user-images.githubusercontent.com/47362783/58751227-fd713c80-8469-11e9-912a-8a7014652f91.png)

# Additional context

Let me know if you want a save or something.

**Comment by Zombiemanpig** [comment] 2019-06-02 15:40
OK so it happened again but it only became bright indoors after I slept (after a bit of traveling) and reloading reset the indoors to being dark like they should be.

**Comment by molkero** [comment] 2019-06-10 20:05
I get dark at nights like it's supposed to, during the day houses are bright without the save & reload. Doesn't seem to affect z-level buildings like the school or houses with specificly added roofs, like the bar, grocery store, even the pool booths.

**Comment by ZhilkinSerg** [comment] 2019-10-08 09:03
Possibly duplicate of #34451

**Closed by ZhilkinSerg** 2019-10-08 09:03 UTC
Labels: <Bug>
