### ISSUE TITLE
Game crashes when harvesting pine tree

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#41285] opened 2020-06-13 16:04 UTC
# Describe the bug

When harvesting a pine tree, the game crashes.

# Steps To Reproduce

1. Create a new game.
2. Go near a pine tree.
3. \<e\>xamine it. Select \<y\>es.
4. Game crashes.

# Expected behavior

Game should not crash.

# Screenshots

![Screen 1](https://user-images.githubusercontent.com/66877699/84573139-f11eff80-ad9e-11ea-88f3-af828005070c.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3159-g3f48507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
A similar crash happened also when picking poppy flowers.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4774909/crash.log)

**Comment by olanti-p** [comment] 2020-06-13 16:25
Looks like a duplicate of #41227 and should be fixed by #41284

**Closed** 2020-06-13 16:52 UTC
