### ISSUE TITLE
You can pick up water even if it's not frozen

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33354] opened 2019-08-19 01:54 UTC
# Describe the bug

You can pick up liquid water.(tho it will immediately leak onto the ground again, u can still move dirty water to somewhere else.)

Besides, if you try to haul water on the ground, there will be a 0 water carried with you and it will cause a game crash if you examine it.

# Steps To Reproduce

1. Make a player with a bottle of water.
2. Pour the water onto the ground.
3. Try to pick up water with 'e' or 'g' or ',', or try to haul water with '\\'.
4. You can pick up dirty water for an instance, or you will create a 0 volume water.

# Expected behavior

Liquid water shouldn't be picked up or carried just as in the former versions. 

# Screenshots

![image](https://user-images.githubusercontent.com/44523519/63234204-e7a03600-c266-11e9-9955-6fdc6b3e910c.png)
↑Try to haul water with the player
![image](https://user-images.githubusercontent.com/44523519/63234221-f8e94280-c266-11e9-9e1a-b3ebc5e701db.png)
↑Try to pick up water

# Versions and configuration

 - Game Version: [0.d-6621-gd201308  or 0.D-9505]

**Comment by EddiTheBambi** [comment] 2019-08-19 16:08
The problem with advanced inventory and hauling is a tough nut to crack. You should need to go through `crush_froxen_liquid( item_location )` to handle frozen liquids via advanced inventory but I haven't found a good way of getting an item_location from any convenient context related to it. I've played with the idea of disabling frozen liquid handling through advanced inventory for now until a better solution can be found.

**Comment by RedShakespeare** [comment] 2019-08-20 08:08
It may be a choice to add a function in map_item_stack.cpp which goes thru all items and checks out if there are liquid or frozen liquid in a tile. Much bothering and may cause other problems like horrible optimization,tho...

**Comment by Ramza13** [comment] 2020-02-16 02:18
Could not reproduce this issue.

**Comment by Saicchi** [comment] 2021-04-03 02:44
Can not reproduce in `0.E-10134-g9b256f63cd [64-bit]`. Trying to pick up the spilled water gives the *Try a mop instead* message.

**Comment by Night-Pryanik** [comment] 2021-04-03 03:14
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-03 03:14 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
