### ISSUE TITLE
Aiming problem with any weapon with friendly npc nearby

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#27322] opened 2018-12-26 16:50 UTC
**Describe the bug**  
Aim is set to wrong value after shooting
(Similar issue: #27321)

**To Reproduce**  
1. Aim (presumably) any weapon with a friendly NPC in range at anything but the NPC.
2. Notice that the aim is 30 in the exact direction of the NPC

**Expected behavior**  
Aim is 30 in the direction you actually fired.

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version 0.C-35549-g07569da
 - Graphics version Tile
 - Mods loaded None

**Comment by Night-Pryanik** [comment] 2019-01-12 07:42
Guess this was fixed not so long ago. Closing for now, ping me if this is still an issue.

**Comment by CoroNaut** [comment] 2019-03-03 15:30
@Night-Pryanik  This issue still persists in 0.C-37575-gf07c447 with my steps listed.
Also, #27321 still persists as well, i provided screenshots in a comment there.

**Comment by CoroNaut** [comment] 2020-01-10 18:49
Figured I would check up on this issue, it still persists as of
- Game Version: 0.D-10922-gb1541cd [32-bit]

**Comment by Ramza13** [comment] 2020-02-16 02:16
Could not reproduce this.

**Comment by Night-Pryanik** [comment] 2020-02-16 05:32
Closing once again. If this is still an issue, ping me.

**Comment by CoroNaut** [comment] 2020-02-22 08:32
@Night-Pryanik 
This issue is very similar to #27321 as previously stated for reminder, and still persists as of
- Game Version: 0.D-12476-gfef327b [64-bit]

The mentioned issue outlines how you can fire at any tile (without auto-targeted enemy nearby) after aiming and firing at any tile not perfectly east of your character, and the aim after firing will act as though you shot perfectly east, when you did not.

This issue here is when you fire at any tile (WITH auto-targeted enemy (hostile npc in this case) nearby). So, you have auto-targeted enemy but decide to aim and shoot at some random tile not perfectly towards the npc, and after firing, the aiming menu will act as though you shot at the npc. This is extremely noticeable with weapons that have little to no recoil, like fusion blaster rifle.

There are pictures in the mentioned issue and here are pictures outlining this issue, which are very similar:

Picture showing aiming menu when aiming at enemy npc (auto-targeted)
![Capture1](https://user-images.githubusercontent.com/24307650/75089052-d2140d80-5522-11ea-9b61-0ea00ff8f3d6.PNG)

Picture showing aiming menu when aiming at some random tile away from npc
![Capture2](https://user-images.githubusercontent.com/24307650/75089060-f243cc80-5522-11ea-9edf-800036ac666b.PNG)

Picture after shooting the fusion blaster rifle in some random direction, and the game re-auto-targeting the enemy npc showing that the aim is minimal as though I actually did shoot in the exact direction of the npc (but I clearly did not)
![Capture3](https://user-images.githubusercontent.com/24307650/75089075-10a9c800-5523-11ea-8bf1-70445a682adc.PNG)

Final picture showing the aim in the exact direction that I actually fired in, which is not minimal as it should be.
![Capture4](https://user-images.githubusercontent.com/24307650/75089086-359e3b00-5523-11ea-8ede-7d14b1f81176.PNG)

This should not be happening. When I shoot at a random tile, I expect that the game would keep my aim at the random tile instead of acting as though I shot at a nearby enemy. 

If there is any confusion, please elaborate.

**Comment by kevingranade** [comment] 2020-03-17 01:17
Confirmed, looks like the variable that tracks the player's aim point is getting reset without resetting recoil when firing at an empty tile, and then when it auto-updates to "the nearest valid target" it also doesn't reset recoil.

**Closed** 2020-03-17 19:10 UTC
Labels: <Bug>, Mechanics: Aiming
