### ISSUE TITLE
Firewood source does not actually feed a fire

### ISSUE THREAD

**Issue by mikt4743thesecond** [CleverRaven/Cataclysm-DDA#47173] opened 2021-02-01 13:35 UTC
# Describe the bug
Firewood source does not keep a fire active during crafts that require a fire or during reading by firelight

# Steps To Reproduce

1. Make a firewood source, fill with firewood
2. Light a  fire, this works for lighting the fire, and craft something that requires a fire that takes a while
3. The fire will not stay fed during the craft and may go out depending on original feed

# Expected behavior

Firewood source should feed firewood, like it used to

# Screenshots

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-9336-gdfd58b5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    Makeshift Items Mod [makeshift],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

 -

# Additional context

**Comment by PaulBlay** [comment] 2021-02-01 13:41
I'm sure I've seen this bug reported already. I can't find it, though.

**Comment by Zireael07** [comment] 2021-02-01 14:06
Dupe of #47008 fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/47092?

**Closed** 2021-02-01 15:35 UTC
