### ISSUE TITLE
Crazy Cataclysm: Mr. Skeltal tries to produce too many minions, which leads to error messages.

### ISSUE THREAD

**Issue by HeadstrongCatgirl** [CleverRaven/Cataclysm-DDA#29868] opened 2019-04-23 16:55 UTC
**Describe the bug**  
Whenever there's a mr.skeltal in my reality bubble I get error messages saying that the game is unable to spawn a zombie. 'I' works for a while, but then those messages return. Can we somehow limit the amount of minions?

**To Reproduce**  
1. Be near mr. skeltal for a few days.
2. Get a ton of error messages.

**Expected behavior**  
No error messages.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Debian stable
 - Game Version: 0.D-2092-gdf6c61ec29
 - Graphics version: curses
 - Mods loaded: Crazy Cataclysm

**Comment by neitsa** [comment] 2019-04-24 15:30
Is the message `There's already a monster at <location>`? if yes it's a duplicate of #29146

**Comment by BevapDin** [comment] 2019-09-28 14:03
Fixed by #32210.

**Closed by BevapDin** 2019-09-28 14:03 UTC
Labels: <Bug>, Mods, Spawn
