### ISSUE TITLE
Incorrect text position in menu [ImGUI]

### ISSUE THREAD

**Issue by LeSHi4** [CleverRaven/Cataclysm-DDA#77297] opened 2024-10-24 15:31 UTC
### Describe the bug

I open item description and text trying to hide for me.
I try to make fully clean game without old saves and config files and have same situation.

### Attach save file

N/A

### Steps to reproduce

1) Start the game
2) Open inventory (i)
3) (e) Open item description 

### Expected behavior

Can read and text not trying to escape :)

### Screenshots

![info 1](https://github.com/user-attachments/assets/d9ee3031-6061-41b4-99d5-f8f14e91396c)
![info 2](https://github.com/user-attachments/assets/4cd8c50e-fb4d-40c0-97c9-c2346a8094e7)
![info 3](https://github.com/user-attachments/assets/142db551-1c33-48ab-8b7b-538c70d05c66)
![info 4](https://github.com/user-attachments/assets/1a5d5075-931b-4060-99f8-3d4f5cb1bd42)

### Versions and configuration

Windows 10 24H2
cdda-experemental-2024-10-24-1253 2d90bfe 
English, Russian
Default mod configuration

**Comment by mqrause** [comment] 2024-10-24 15:56
Only gave it a cursory glance, but it looks like #76529 changed it so the font is set only after the wrap width is calculated. That means it's calculated for the wrong font and thus wrapping in the wrong place.

**Comment by yamil-90** [comment] 2024-10-26 17:43
a lot of the text boxes look off 
the gravestone that appears when your character dies got all messed up since it was ascii art
![image](https://github.com/user-attachments/assets/7f14570b-1f26-4ce2-9afe-f6234f22f849)

when studying or doing some long activity the boxes also are not rendered properly
![image](https://github.com/user-attachments/assets/d892a71a-a41a-497d-a071-02ab4fa98889)

**Comment by ampersand55** [comment] 2024-10-27 19:21
A temporary fix is to switch ImGui font to terminus.

https://old.reddit.com/r/cataclysmdda/comments/1gdgwyx/guide_how_to_fix_item_descriptions_menu_being_cut/

**Comment by svakob** [comment] 2024-10-28 20:41
How to return the old font?

**Comment by db48x** [comment] 2024-10-31 23:28
#76513 fixes the wrapping. Fixing the gravestone will be easy enough; we have a monospaced font for just that purpose.

**Comment by Abalieno** [comment] 2024-11-02 09:36
While I personally dislike the move to ImGui, at the very least it needs a load option to set the font size.

It uses the same font size of the standard font for the ImGui font, that in almost all cases produces very blurry and very badly scaled fonts in all ImGui panels.

**Comment by db48x** [comment] 2024-11-02 14:14
> that in almost all cases produces very blurry and very badly scaled fonts in all ImGui panels.

I don’t think that’s true. If it is, file a bug report of your own and show us your configuration, screenshots, etc.

**Comment by ampersand55** [comment] 2024-11-02 14:25
> This is especially a mess because the main game takes bitmap fonts that aren't easily converted to truetype fonts. And truetype fonts look terrible without a very precise scaling that matches the bitmap.

This might be fixed by setting font blending to true in Settings > Graphics > font settings.

**Comment by Abalieno** [comment] 2024-11-02 15:54
I don't think font blending affects ImGui, and I had it disabled anyway.

This is a quick test. Take for example an "official" screenshot from here: https://github.com/ocornut/imgui/blob/master/docs/FONTS.md

![prog1](https://github.com/user-attachments/assets/a5d77626-562c-47a5-acc6-a5cd6caa20aa)

As you can see it's very sharp, and it's loaded at size 13

This is how the same font looks in Cataclysm (name of the font is different, but the source is the same, I just changed the name to switch faster configs):

![tujuk](https://github.com/user-attachments/assets/da50d6bd-14af-40d7-b78e-07d5e8a467d5)

But it's the same even for the currently embedded fonts. This is is using Unifont:

![ykyik](https://github.com/user-attachments/assets/2b02ac27-d56b-4199-b3e8-e9086584d5b8)

And it is indeed crisp. But if you change the size...

![yukyukr](https://github.com/user-attachments/assets/83755ed4-8337-4c64-837d-317954b3155e)

At size 18 it exhibits some corruption.

As I said, truetype fonts will only look fine at certain sizes, there needs to be a way to be able to give them a size different from the main game font, since the two follow different rules.

**Comment by ampersand55** [comment] 2024-11-02 16:46
I think that's an issue with the version of unifont shipped with the game (v.12). I get the same bad rendering at 18px even in other applications.

I get a better result with ([OpenType unifont v16 ](https://unifoundry.com/unifont/)).

Truetype unifont v12:

![image](https://github.com/user-attachments/assets/166f18f8-e98b-4519-9a22-b0dd11e68c09)

Opentype unifont v16:

![image](https://github.com/user-attachments/assets/7d81dccf-7bd9-4867-bf71-ee057f8d8d11)

**Comment by db48x** [comment] 2024-11-02 17:05
Two things: file a separate bug report for font stuff, because it has nothing to do with this bug!

Secondly, you should not care how unifont looks. The goal of unifont is to have a glyph for every character in Unicode, not for the glyphs to look good. It doesn’t have hinting tables, or ligatures, or shaping tables, or anything. Just one glyph per character. It is only intended as a fallback.

You should pick a font that you actually like at your chosen font size. We can add more control over size, hinting, anti–aliasing, and so on at a later date, but fundamentally you just need to pick a nicer font.

**Comment by Abalieno** [comment] 2024-11-03 00:01
No, it's not related to the font. Different fonts, depending on how they are originally built, look well at their native resolution and poorly when scaled. 

And yes, I COULD pick a font I actually like at the size I need, or just load the font at the size I need, which was the original request that makes the most logical sense.

But if you can find a monospace font that is rendered correctly at size 16, then tell me. I spent a few hours without luck.

Using a non monospace font for a grid-based UI is not going to work unless you really enjoy having everything misaligned.

![en2](https://github.com/user-attachments/assets/4bebc022-e284-409c-8157-5f9b4f58157c)![en1](https://github.com/user-attachments/assets/33786358-cd87-42e0-8565-acea05f77284)

See the t of throw or r of reload all shoved to the left. You either have a sensible eye to the correctness of good UI design and alignment or not. Some people I guess won't even notice.

But I think everyone at a glance will agree that the first example looks a lot better and is easier to read.

**Comment by db48x** [comment] 2024-11-03 00:12
> Different fonts, depending on how they are originally built, look well at their native resolution and poorly when scaled.

This is simply not true. TrueType fonts are vector fonts, and will look just as good at any size (above a sensible minimum font size; nothing looks good when 2px high). If the font you’re using doesn’t look good at 16px or whatever, then choose a different one.

> Using a non monospace font for a grid-based UI

We’re not doing that. The ASCII art remains monospaced. We can right–align that column of shortcuts if you want, or use monospace for that column. Or we can challenge ourselves to think of an even better UI.

**Comment by Abalieno** [comment] 2024-11-03 00:18
If the font you’re using doesn’t look good at 16px or whatever, then choose a different one.

Before replying to this issue I already had spent a few hours trying to find a solution. I tried more than 20 fonts. I tried converting fonts, I tried editing them in FontForge.

As I said, if you have a monospace font that looks good, then I gladly accepts suggestions.

But if I can, I'd rather use the same good looking font everywhere, as long I can load the correct size.

**Comment by 0xToast** [comment] 2024-11-04 16:59
I can report the same thing in the latest version of CDDA (experimental build 2024-11-03-2221), however it also affecting the way that the action bar on the top of the screen renders, as illustrated below:

![Screenshot 2024-11-03 155950](https://github.com/user-attachments/assets/1b00ef3d-8fad-4cbe-b318-db80dc4db716).

When moving the mouse whilst the action bar is rendered, it fixes itself temporarily until another action is repeated that renders the same action bar.

![Screenshot 2024-11-03 160001](https://github.com/user-attachments/assets/b1e8ecd4-0f32-44a6-9b7b-7a4572c740a9)

I can confirm that using "gui_typeface" within fonts.json resolves the issue with the font being cut off but only works with the terminus font currently:
```
{
    "gui_typeface": [
                     "data/font/Terminus.ttf",
                     "data/font/unifont.ttf"
    ]
}
```

So far I can see the bug was introduced sometime after experimental build 2024-10-24-0244, as I rolled back to this version and the text renders find with other fonts. Not sure if that is helpful.

**Comment by 0xToast** [comment] 2024-11-07 16:09
> As already mentioned, there is already a pull request that fixes the text wrapping.

Thanks mate, sorry I only saw the PR after your comment. 

I do see that the merge got blocked due to checks failing on the Text Changes Analyzer with Error: Process completed with exit code 1.

Pretty sure you know about this already, but thought I would mention it.

**Closed** 2024-11-09 16:08 UTC
Labels: (S2 - Confirmed), (P2 - High), SDL: Tiles / Sound, ImGui
