### ISSUE TITLE
Improve turret warning system

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#35378] opened 2019-11-07 15:10 UTC
**Is your feature request related to a problem? Please describe.**  
Turrets, especially BMG, have extreme range and high damage, leading to one-shot-kills with effectively no warnings.

**Describe the solution you'd like**  
Please improve turret warning system. `Something something ominous beeping` when you're in their detection range [50 tiles]
Also something like `'A red dot appears over you, the laser seems to be coming from <direction>' `for a round before it shoots. 
Most importantly, the shot warning should trigger safe mode.

**Describe alternatives you've considered**  
N/A (the current status quo is not good, to say the least, see #35377 for instance)

**Additional context** 
https://github.com/CleverRaven/Cataclysm-DDA/pull/34426#issuecomment-538773666

**Comment by Night-Pryanik** [comment] 2019-11-07 15:19
> effectively no warnings.

That's not true. Turrets make a "Hostile detected" sound prior to firing.

> how much is it again?

All turrets have detection range of 50.

**Comment by Nerezza** [comment] 2019-11-07 19:32
In the current builds the turrets say "Hostile detected" when they have a potential target in LoS, though I don't think they have to have visual contact with the target to trigger that line. I've had a turret announce its presence like that in a dark military shelter despite neither of us being able to see eachother.

Either Modular Turrets or Salvaged Robots seems to disable that though. If you have those mods enabled, the turrets become silent+deadly, which is one of the reasons I ended up removing those mods from my game despite the errors that results from it losing like a hundred item definitions in my saves :P

**Comment by Zireael07** [comment] 2019-11-07 19:49
> Modular Turrets or Salvaged Robots
Ah, the last time I played I had Salvaged Robots on. That's a real nasty bug.

Even if vanilla turrets say Hostile detected, adding a second message and making it trigger safemode wouldn't hurt, considering how dangerous turrets are.

**Comment by SirPendrak** [comment] 2019-11-07 20:26
Trigerring ON safemode like for tank or chickenwalker lasertarget seems good idea. 
Anyway, now turets have longer range than tanks, Cwalkers and National Guard Camp robots, but theese lack targetting time, unless I missed something. Maybe their range needs to be adjusted, same their aiming time, i guess some more dangerous bots could get lower targeting time, like 150 or 100 moves.

**Comment by Night-Pryanik** [comment] 2019-11-08 05:25
> but theese lack targetting time, unless I missed something.

Turrets need more than 2 turns (more clearly, 240 moves) to target.

**Comment by kevingranade** [comment] 2019-11-09 19:03
Invalid premise, they do not have effectively no warning, they have both an audible beep and a significant delay before firing.

**Comment by Zireael07** [comment] 2019-11-09 19:28
Considering how many players recently have complained about being killed by turrets, they need more warnings.

**Comment by RDru** [comment] 2019-11-09 19:29
> Modular Turrets or Salvaged Robots 
Yes, those mods do more bad than good atm. And their have nice good descriptions so many players will use them

**Comment by kevingranade** [comment] 2019-11-10 00:18
The answer is still no.

**Comment by Destragon** [comment] 2019-11-10 10:07
This deserves to be re-reopened, because there are still at least 2 major issues with turret warnings:
1: The turrets have longer range than it's possible to hear their "Hostile detected!" warning sound. If you walk up to them from 50 tiles away, you will get shot before you get any sort of warning.
2: The "Hostile detected!" sound does not trigger safe mode even though it should, like laser pointers do.

Both of these issues were caused by removing the laser pointer from turrets. I think the easiest solution would be to just give them back the laser pointer. I don't know why a warning sound is more realistic than a laser pointer anyway.
But alternatively, it could be solved by adding a loudspeaker to every overworld location where turrets spawn (roadblocks, restricted areas, etc), which continuously broadcasts a message like "This is a restricted area. Move away or you will be shot." that can be heard from 60+ or so tiles and should also trigger safe mode.

**Comment by Night-Pryanik** [comment] 2019-11-10 10:55
> removing the laser pointer from turrets.

Visible lasers are convenient only for human eyes. Turrets' targeting modules are working in IR range, why should they use visible lasers which are less perfect for aiming purposes?

>The "Hostile detected!" sound does not trigger safe mode even though it should, like laser pointers do.

Currently neither sound doesn't activate safe mode. Safe mode is activated only when noticing monsters.

> I don't know why a warning sound is more realistic than a laser pointer anyway.

Because most people (especially civilians) almost for sure don't know what this laser dot means and won't consider it as a sign of some danger.

**Comment by Destragon** [comment] 2019-11-10 14:47
>Turrets' targeting modules are working in IR range, why should they use visible lasers which are less perfect for aiming purposes?

If they are using IF, then why do they have no night vision? I'm not saying that they should get night vision, but that it seems more like they are only using normal vision cameras and then it's not unreasonable for them to have a visible laser pointer.

>Currently neither sound doesn't activate safe mode. Safe mode is activated only when noticing monsters.

Yes, it doesn't have to do with the actual safe mode (though maybe it should), but it behaves in the same way and that was the point. The game prevents you from moving if you're being laser targeted. The same should be happening with the turret's warnings.

>Because most people (especially civilians) almost for sure don't know what this laser dot means and won't consider it as a sign of some danger.

Your response is from the point of view that the turrets are actively trying to warn people, instead of it just being a warning hint for the actual player.
In the last issue, you said that turrets aren't illuminated, because they were designed to kill intelligent beings. I understood that as you thinking that they should not be giving any warnings to people. Why is it okay for them to have a warning sound, but being illuminated as a warning is not okay?

**Comment by RDru** [comment] 2019-11-10 14:56
I agree that there is no point for laser pointers for targeting system using either normal or IR cameras.

I fail to see how this is a big issue when either turrets are in rooms meaning they are withing vision range or they are in special places like outposts meaning you can just check your map and choose to not go close to those places.

But there could be some warning sings in game for normally restricted places.

**Comment by Zireael07** [comment] 2019-11-10 15:23
@RDru: Not true, there are roadblock turrets which are difficult to avoid.

However, warning signs are a good idea too.

**Comment by Destragon** [comment] 2019-11-10 15:38
Certain locations have turrets around their perimeter on the outside. I'm guessing the 50 range turrets can spawn there, too.

**Comment by Night-Pryanik** [comment] 2019-11-10 15:43
> If they are using IF, then why do they have no night vision?

Maybe then they really should have night vision. It might be a simple oversight.

> Why is it okay for them to have a warning sound

In fact "Hostile detected!" ain't no warning sound at all. At least it doesn't warn _player_. It was intended to inform nearby turret operators and soldiers about hostiles. It shouldn't warn _hostiles_ about them being detected.

**Comment by Destragon** [comment] 2019-11-10 18:11
>Maybe then they really should have night vision. It might be a simple oversight.

Well, I knew you were gonna say it and I hope you're joking, unless you want to inevitably piss off countless players with cheap deaths.

>It was intended to inform nearby turret operators and soldiers about hostiles.

I dunno, it sounds like a bad excuse. Would operators even be standing in proximity to the turret? A turret shouting "Hostile detected!" feels like a very video-gamey thing to me, which I really don't see as a bad thing though, as long as it serves a purpose.
Seeing it as an actually intended warning makes a bit more sense to me. I mean surely the military would put warnings up in the areas where they placed their infinite-ammo killing machines, right? They aren't intentionally killing civilians, are they?

As for warnings, I think a loudspeaker works for the roadblock type locations, but it makes a little less sense for actual restricted areas outside of cities. They should probably just be fenced in with a "keep out" sign. I don't remember if there already are fences around those or not.

**Comment by anothersimulacrum** [comment] 2019-11-10 18:59
> 1: The turrets have longer range than it's possible to hear their "Hostile detected!" warning sound. If you walk up to them from 50 tiles away, you will get shot before you get any sort of warning.

This is not true, I've tried and *always* get a warning before being shot.

**Comment by Night-Pryanik** [comment] 2019-11-10 19:09
> Would operators even be standing in proximity to the turret?

Yes they were. At least I imagine operators standing behind the turrets (crouching behind the sandbags or in pillboxes).

> A turret shouting "Hostile detected!" feels like a very video-gamey thing to me

The same for me. The ONLY reasons turret could ever be shouting such things would be either warning _operators_ about the hostiles, or warning _players_ about some badass enemy up ahead. And if we're discarding "operators" reason, then the only one that remains is a "gamey" reason, which I personally quite don't like in this game. So I'd remove this shouting at all.

> I mean surely the military would put warnings up in the areas where they placed their infinite-ammo killing machines, right? They aren't intentionally killing civilians, are they?

In the last days before the Cataclysm the military reprogrammed turrets to be much more aggressive, they actually gave a green light to "fire at will at all moving targets" command. So, no more warnings, just shooting to death.

> As for warnings, I think a loudspeaker works for the roadblock type locations,

I like the idea. Because it doesn't involve making some silly things to the turrets itselves (like illuminating them or making them warn their targets about starting a fire) which no adequate military would ever do to their own war equipment.

**Comment by Zireael07** [comment] 2019-11-10 19:55
Loudspeakers, lasers, beeping, whatever - the fluff doesn't really matter.

> The ONLY reasons turret could ever be shouting such things would be either warning operators about the hostiles [..] And if we're discarding "operators" reason,

As you said, it makes perfect sense for the turret to be warning operators. And the turret's electronics does not know all the operators are dead or hostile, so it continues emitting warnings even after the cataclysm.

**Comment by Destragon** [comment] 2019-11-11 17:55
>This is not true, I've tried and always get a warning before being shot.

Were you 50 tiles away from the turret @anothersimulacrum?
In my testing, whenever I approached a turret at 50 tiles away, it would start shooting me without warning. I didn't have any impaired hearing and it was clear weather.
![Image](https://cdn.discordapp.com/attachments/504754524079259678/643466213703417856/unknown.png)

>then the only one that remains is a "gamey" reason, which I personally quite don't like in this game. So I'd remove this shouting at all.

I know CDDA has a huge focus on realism, but I think not even CDDA should put realism over gameplay experience in unforseen instant death situations like this.

>So, no more warnings, just shooting to death.

I understand that they'd make their targetting AI more aggressive, because it wasn't able to differentiate people from monsters, but that doesn't mean they wouldn't also at least put up some warnings, especially because doing that is a moral justification for their desperate actions.

>Because it doesn't involve making some silly things to the turrets itselves (like illuminating them or making them warn their targets about starting a fire) which no adequate military would ever do to their own war equipment.

I still definitely disagree on it being silly to illuminate the turret. This isn't war. They are containing the spread of seemlingly non-intelligent monsters. Of course they would attach some cheap LED lights to the turrets to warn the remaining sane civilians not to blindly run into a firing squad.

**Comment by Night-Pryanik** [comment] 2019-11-11 18:29
> I understand that they'd make their targetting AI more aggressive, because it wasn't able to differentiate people from monsters, but that doesn't mean they wouldn't also at least put up some warnings, especially because doing that is a moral justification for their desperate actions.

When almost everyone around is an enemy, are warnings needed (esp. for the enemy)?

> They are containing the spread of seemlingly non-intelligent monsters.

Quoting myself from https://github.com/CleverRaven/Cataclysm-DDA/issues/35377#issuecomment-551048909:
> They [turrets] were designed to kill living (intelligent) people who will try their best to locate and destroy turrets before turrets destroy them. That's why they ain't illuminated. It's not turrets' fault that most of Earth population are zombies.

I grow tired of this fruitless discussion, and taking the fact of that this issue was closed by project manager into account, I cease my participation in this discussion.

**Comment by Zireael07** [comment] 2019-11-11 18:55
As I mentioned earlier, turrets were made before everyone around became and enemy.

**Comment by Destragon** [comment] 2019-11-11 20:28
>When almost everyone around is an enemy, are warnings needed (esp. for the enemy)?

In my opinion? Obviously they are. They don't know how many survivors there are. Like I said before, it wouldn't be morally justifiable to do this without making the danger obvious to normal human beings.
"The enemy" are basic zombies and triffids. Nothing that they'd need to hide the turrets from. Mi-Gos maybe, but they are rare anyway.

>As I mentioned earlier, turrets were made before everyone around became and enemy.

Even if they were made before, they could still just easily slap LED lights, speakers or whatever else on them.

>I grow tired of this fruitless discussion

All I'm saying is that warnings are not just good for player experience, because they prevent cheap deaths, but that they could be explained fairly easily to fit into the realism argument.
There is no right and wrong here. I was just talking about how the feature COULD be explained.

>this issue was closed by project manager

The reason Kevin gave for closing the issue was "Invalid premise, they do not have effectively no warning", he seemed to just have a problem with the wording of the issue. I think you could just rename it from "add a warning system to turrets" to " improve the warning system of turrets". See my first post on this issue for the actual problems with the current warning system.

**Comment by Zireael07** [comment] 2019-11-12 07:29
Changed the issue title to reflect that some warnings exist, but are not enough.

**Closed** 2019-11-12 08:03 UTC
Labels: (S4 - Invalid), <Suggestion / Discussion>, Game: Balance, Monsters

**Comment by Zireael07** [comment] 2019-11-12 08:44
At least one other person has confirmed that the warnings are not enough and that he was being shot without them. Either there is a bug with existing warnings not being seen or there needs to be more warnings.

**Comment by esotericist** [comment] 2019-11-14 23:54
> At least one other person has confirmed that the warnings are not enough and that he was being shot without them. Either there is a bug with existing warnings not being seen or there needs to be more warnings.

if you're referring to #35377 the problem there was they opened fire first.

Once you open fire, you are no longer a civilian to be warned away, you are an *enemy combatant*. Enemy combatants do not get warnings, they get shot at until they stop being a threat.

If you're going to continue on this path, you really need to demonstrate there's a problem with the warnings for survivors which do not initiate hostilities. I'm not seeing an actual demonstration of a real problem.
