### ISSUE TITLE
All bullets reflect off NPCs

### ISSUE THREAD

**Issue by bumpkindda** [CleverRaven/Cataclysm-DDA#17188] opened 2016-06-15 06:58 UTC
- Start new game
- Debug skills to 10
- Spawn a Barrett .50 with AP ammo
- Shoot NPC
- Get wrecked by their nail bat

**Comment by mugling** [comment] 2016-06-15 20:08
Can reproduce in `master`

**Comment by Coolthulhu** [comment] 2016-06-15 20:27
Can't reproduce here, could be an unspecified behavior kind of a thing.

**Comment by CapitalistShrub** [comment] 2016-06-17 14:29
Using unmodded 5062 (15449-gf8f5cd1) I was unable to damage any npc using a Mosin Nagant, a Beretta M9, a Marlin, a Scout Rifle or the Fusion Blaster Arm cbm initial impact (though the fire does kill); shots were taken at various distances, but all were either critical hits or headshots and resulted in "The shot reflects off of" messages.

![image](https://cloud.githubusercontent.com/assets/13109908/16153828/af5aaaa8-346d-11e6-8135-39dbf582d843.png)

**Comment by CapitalistShrub** [comment] 2016-06-17 18:21
A quick update - it looks like NPC's are currently extremely resistant to cutting damage (as in, effectively taking almost none), not only from firearms.

A diamond nodachi on a character with 20 in all stats and 10 in all skills is hitting for 10's and 15's against an npc in light clothing:

![image](https://cloud.githubusercontent.com/assets/13109908/16160446/d0bc8c14-348d-11e6-955e-d2e2859107fe.png)

That same character using a sledgehammer was able to apply the full damage against an NPC:

![image](https://cloud.githubusercontent.com/assets/13109908/16160532/538c65ec-348e-11e6-906a-e7d428f3bb5e.png)

**Comment by CapitalistShrub** [comment] 2016-06-17 22:29
Cutting damage affects NPC's and the player in build 5032, but does not affect either in 5047. Build 5033 seems the most likely offender due to the changes made to NPC's and damage types, but I'll readily admit that I'm not very familiar with the codebase yet.

My assumption is that either the NPC's and Player are somehow being incorrectly flagged as cut immune, perhaps due to fallback to a default value, or cut damage is being incorrectly zeroed upon application somehow.

**Comment by Coolthulhu** [comment] 2016-06-18 10:06
> DanmakuDan_ and I found the issue to not be present in the x64 wintiles, but could confirm it in the 32 bit version.

That sounds like bad news, because it most likely means that an `enum` or `bitset` goes out of its allowed range and wraps back.
Or that an invalid cast is being made.

**Comment by mugling** [comment] 2016-06-20 12:49
Can reproduce in 64-bit tiles. Presume undefined behavior.

**Comment by Coolthulhu** [comment] 2016-06-20 14:52
I think it may be caused by unset values in `std::array` in `resistances`.

If this is the case, #17243 would fix it, since it explicitly sets the array to zero.

**Comment by mugling** [comment] 2016-06-24 17:42
Indeed fixed by #17243

**Closed by mugling** 2016-06-24 17:42 UTC
Labels: Bug, NPC, validated
