### ISSUE TITLE
Issues with high resolution on Android

### ISSUE THREAD

**Issue by Vanya78** [CleverRaven/Cataclysm-DDA#54520] opened 2022-01-17 18:39 UTC
### Describe the bug

On Android, when the terminal and font sizes are set for a high resolution screen (2960x1440 for me), a large black bar will cut off part of the screen for menus and the tileset in that area wont clear after save and quit

### Steps to reproduce

Launch on an android device with 2960x1440 screen resolution.
Settings- terminal height: 42, terminal width: 185, font width: 16, font height: 32, font size: 32, shortcuts overlap screen: false, shortcut height: 96
Restart
A black bar blocks the bottom third of the screen

### Expected behavior

I expected to be able to see the menus

### Screenshots

![Screenshot_20220117-130855_Cataclysm DDA](https://user-images.githubusercontent.com/97910772/149822392-b9a448d1-4de0-41df-8125-fe849799538c.jpg)
![Screenshot_20220117-130923_Cataclysm DDA](https://user-images.githubusercontent.com/97910772/149822399-ead72192-9a82-48aa-b1b5-7e8220a1ed92.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-N960U; Release: 10; Incremental: N960USQU9FUK1; 
- Game Version: 0.F-3 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by BrettDong** [comment] 2022-01-17 18:43
Duplicate of #54329

**Closed** 2022-01-28 14:10 UTC
Labels: OS: Android
