### ISSUE TITLE
Aim at enemy cause game crash

### ISSUE THREAD

**Issue by Anodrose** [CleverRaven/Cataclysm-DDA#74309] opened 2024-06-04 10:25 UTC
### Describe the bug

Steady your aim at enemy cause game crash.

### Attach save file

I used the tutorial game to test. Open that save file may cause other problems.

Here is a new game with the player holding a rifle. Press f to target the NPC, try to steady your aim.

[Metter.zip](https://github.com/user-attachments/files/15546382/Metter.zip)

### Steps to reproduce

1. Make a player with gun and ammo (I have tried some handguns and rifles).
2. Find an enemy or just  NPC.
3. Fire wielded item (press f by default).
4. If the enemy or NPC is already targeted, steady your aim (press any of ., a, c, p by default).

### Expected behavior

Game will crash now.

### Screenshots

Game just aborted.

### Versions and configuration

OS:
  - Linux version 6.9.3-arch1-1
  - HarmonyOS 4.0.0
 
Game Version: 2024-0604-0517

Graphics version:
 - Linux x64 curses
 - Linux x64 tiles
 - Android x64 tiles

Ingame language:
  - English
  - Chinese
 
Mods loaded: Default setting

### Additional context

On Linux no crash.log was produced. Here is crash.log for Android version

[crash.log](https://github.com/user-attachments/files/15546537/crash.log)

**Comment by Anodrose** [comment] 2024-06-04 11:10
This issue is duplicated. See "Crash when steadying up aim. #74308"

**Comment by harakka** [comment] 2024-06-04 16:46
Closed as duplicate of #74308

**Closed by harakka** 2024-06-04 16:46 UTC
Labels: (S1 - Need confirmation)
