### ISSUE TITLE
Proposal for new inventory system

### ISSUE THREAD

**Issue by dodomorandi** [CleverRaven/Cataclysm-DDA#10821] opened 2015-01-10 20:06 UTC
I know that what I am proposing could need a big overhaul of the inventory system, but I think it could add more fun, realism and challenge to the game.
It could be great if objects could be assigned to specific containers instead of just occupying volumetric units. This would change the gameplay in different ways:
 - If I have a heavy backpack with encumberance value of 2 or 3 and I see a Z, I would put it in the floor before go fighting. Now you have to select lots of things to drop with the container. With the new system you would have to put down just a container item. And, naturally, the content could not be seen from the distance.
 - If have 2 pockets in a pair of jeans with 1 volume each, I cannot take a single object with volume higher than 1. With the actual system is, naturally, possible.
 - Containers could also be orgainzed in LIFO mode. Therefore if I need a knife on the bottom of my backpack it would take much more time than taking it from the top. In this way big inventories could give lots of problems if not well organized. However, I understand that tweaking this feature could be not easy at all.

I know that this feature could be difficult to implement, but what do you think about it? Is it possible?

**Comment by Shoes01** [comment] 2015-01-10 20:44
I think the first two points you mentioned are things the devs also want to see in the game, but it does require a lot of work behind the scenes to get working properly. The third point I haven't seen brought up a lot, but I imagine once things start being put into backpacks, it would be quite easy to track which was put first and which was put last. I think that would also organically promote the use of a holster so that your gun isn't at he bottom of your bag.

**Comment by Snaaty** [comment] 2015-01-11 01:32
Hm, no offense, but this is probably one of the most ancient ideas that comes up every now and then. 

Personally, I don't really see the problem with cddas inventory management system. If you look at other, "high-end" games like e.g. Skyrim, no one gives a flying duck where you actually store your 50 broadswords or what. 
I believe that because the inventory system in cdda is more realistic and therefore more limiting than the systems in other games, people tend to notice it quickly and try to "improve" it. 
Also, as shoes has already hinted, the things you propose are not really in proportion to the gain. 
All in all, if you have time to add the container-based inventory system yourself, noone is (probably) going to stop you, but as I said it's just not worth it. 
Your third point is intersting but seems to be more annoying to players than challenging. You'd have to stop after each house you raided in order to optimally rearange your stuff to get the important stuff on top, etc. That sounds rather tedious to me.

**Comment by kevingranade** [comment] 2015-01-11 02:38
Duplicate of #3671

**Closed by kevingranade** 2015-01-11 02:38 UTC
Labels: Duplicate
