### ISSUE TITLE
[MoM] Raising Physical Enhancement from 9 to 10 exhausts player and slows UI 

### ISSUE THREAD

**Issue by goibnus** [CleverRaven/Cataclysm-DDA#73186] opened 2024-04-22 06:17 UTC
### Describe the bug

2024-04-21-1937 Experimental
When I activate Biokinetic: Physical Enhancement and it levels from 9 to 10, the game breaks in two ways.  First, the character becomes permanently exhausted, and second, the UI becomes extremely slow both during play and during the save process (maybe 2 seconds per move).  This carries over between save/load, restarts, and a https://github.com/mlange-42/cdda-tools character world transfer.  I have fixed this by hand by removing both the power and the exhaustion though save file edits, but when Physical Enhancement hits 10 again the bug repeats.

### Attach save file

[Meadowbrook-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15058299/Meadowbrook-trimmed.tar.gz)

### Steps to reproduce

1. Activate Physical Enhancement in the attached save.

### Expected behavior

1. I expected the UI to continue to function and for my characters weariness not to bottom out.  :)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/167591127/8f853101-54cb-4bed-86c5-e1a871c203bc)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/167591127/832e015d-656c-4389-aabb-c7d0e1ef7278)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 9ebd717 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills]
]

**Comment by Icantthinkofanameforthis** [comment] 2024-04-22 12:20
i tried the attached save and had no issue but note that i dont actually have the arcana mod cause its not part of the catapult launcher stuff so maybe it has something to do with that

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/b7b37ea7-9f3a-4da7-9e51-18b2524fc62a)

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 6797b1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No name () [],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills]
]

**Comment by Icantthinkofanameforthis** [comment] 2024-04-22 12:50
mmk tried the attached save and yup it lags like heck and does the extreme weariness

turns out its something to do with the trait 'Very Heat Dependent' like removing it stops the lagging and if you remove the trait before lvling up physical enhancement it doesnt do the extreme weariness like using heat dependent is fine its just the very heat dependent stage for whatever reason

should note i dont have the arcana mod cause its not part of the catapult launcher stuff so who knows if that will make a difference to your results

**Comment by goibnus** [comment] 2024-04-22 21:53
There might be something else going on here, as well.  I am having a ton of trouble keeping myself fed.  I'm playing with new Vitakinetic abilities, Coagulate and Healthy Glow, and my weight is plummeting insanely quickly.  I'm going to quit using those abilities and see if I can keep myself fed.

**Comment by goibnus** [comment] 2024-04-23 03:43
I ate my way through an apartment building and never managed to get above Emaciated, but as soon as I purified away Very Heat Dependent / Heat Dependent the issue went away, the weight came back, and I could do things other than eat and obtain food.  I'm aware of the calorie costs of MoM powers, but this felt like a lot more than that.

**Comment by GuardianDll** [comment] 2024-05-08 09:05
duplicate of #72781
I'll try to resolve it soon

**Closed by GuardianDll** 2024-05-08 09:05 UTC
Labels: (S1 - Need confirmation)
