### ISSUE TITLE
Wood Axe is only 14cm

### ISSUE THREAD

**Issue by cosmo-naut** [CleverRaven/Cataclysm-DDA#43010] opened 2020-08-18 10:41 UTC
# Describe the bug

The wood axe item is only listed as being 14 centimetres long, allowing it to fit into backpacks very easily

# Steps To Reproduce

1. Create a new character
2. Spawn a wood axe

# Expected behavior

Looking at the length of axes online, even smaller 'hatchet' varieties are around 30+cm in length.
As there is already a hatchet item, and the wood axe item is predominantly used for cutting down trees, the length seems like an oversight.
Browsing the website of a local hardware store, it seems like axes of the size I believe the Wood Axe is intended to be range between 600mm to 800mm

**Comment by feinorgh** [comment] 2020-08-18 11:35
This is related to  #41621, which is ongoing.

**Comment by ZhilkinSerg** [comment] 2020-08-18 16:11
Duplicate of #41621

**Closed by ZhilkinSerg** 2020-08-18 16:11 UTC
