### ISSUE TITLE
Crash when using the Zone Organize feature

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#33657] opened 2019-08-29 18:28 UTC
# Describe the bug

Game entered a loop when trying to organize loot via the Zone Manager feature. Loot was the basic items found inside the Evacuation Shelter in the default start. One of the items (Frisbee) did not have an appropriate zone set for it, but instead of skipping the item, game entered a loop where it moved onto the frisbee, Southwest one step, and then repeated indefinitely. Action could not be cancelled by any means and eventually the entire computer crashed. No crash logs were available as a full restart was necessary.

# Steps To Reproduce

I do not remember the exact items I had, but it was only items that had been found inside the Evac Shelter. The zones that were set up were: Unsorted, Tools, S. Parts, V. Parts, Other, Wood, Food, Drink, P. Food, P. Drink. As mentioned above, item that caused the loop was Frisbee, although I was unable to verify if that was the last item to be sorted, or whether there were other "sorteable" items left in the Unsorted zone. All items were placed in a single pile, in the basement of the Evac Shelter.

# Expected behavior

I believe the default behavior for this would be to skip the item and leave all non-sorted items where they were originally. That has been the behavior the game displayed since I began playing.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-7085-g6831dd6
 - Graphics version: Tiles
 - Mods loaded: Alternative Map Key, PKs Rebalancing (as downloaded from https://github.com/dissociativity/PKs_Rebalancing/releases/tag/5.7.2i_UO)

**Comment by Zombiemanpig** [comment] 2019-08-29 19:42
Encountering this same issue, it's easy to replicate, I am autosaving before each time I try to sort stuff now.

Not sure what is causing it. I am having this happen with different items depending on minor changes I make beforehand...

**Comment by Nick8876** [comment] 2019-08-30 08:25
I am also having a similar problem. While sorting, my character get's stuck in an infinite loop that crashes the game. My guess it was PR #32730 that is causing this crash as when I reverted back to build 9550 (0.D-7000-gd2e35e5) prior to the merge, sorting worked fine. While on build 9552 (0.D-7009-gd8f806f), where the PR was merged, the infinite loop crash is present.

**Comment by davidpwbrown** [comment] 2019-08-30 10:15
Duplicate of #33581 
will be fixed by #33598

**Closed by davidpwbrown** 2019-08-30 10:15 UTC
