### ISSUE TITLE
Assorted UI/QoL problems

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19930] opened 2017-01-03 18:22 UTC
- There should be a "Show foldable parts only" option in vehicle menu.

- Charcoal kiln should be placeable and interactive, not a weird multi-step process involving crafting, activation, disassembly.

- "D" and "G" keys do not work when choosing which tank to refill for no identifiable reason

- Tailor's Kit is only reloadable with thread, but not sinew/plant fiber/yarn/etc

- Disassemble everything(and once) does not show "too dark to craft" message

- Move view should have no keybindings, it feels like a bug if you hit it by accident and then notice your cursor in view mode is offset.

- Keypresses should not be queued while (auto)saving the game

- Display product amount in crafting UI, e.g. x50, as well as side-products

- Add a search flag for product description in crafting menu

- Armor layering screen does not respect item labels

- There is no notification of any kind about finishing construction

- "You accurize your ..." message is displayed /before/ the process is done.

- Gun repairing/accurizing cannot be interrupted

- Cancel option on jumper cable prompts to choose target anyway

- Display warning before doing something extremely slow, such as attacking with a full barrel

- Allow overmap search to find notes, vehicles, and NPC

- Expand search systems of crafting and construction menu to use the same system as adv inv

- Mark locations such as spider nests, minefields, wreckages, etc. on the map once discovered from up close

- Assigned inventory letters sometimes bug out when equipping/unequipping active items, I couldn't figure out how to reliably reproduce

- There is no warning about going to sleep while the L-stick is on

- There should be inventory categories for containers and seeds

- Artifact category has no caption

- There needs to be a prompt to stop putting weapon in inventory(or performing other actions) while standing in acid and melting away. I felt beyond stupid dying to this

- Crafting bonus from stat is not shown in character creation, only on the character menu

- Reading menu shows "martial arts" label before skimming a book

- When installing parts, display capacity in chosen units

- Door motor interface needs improvements - don't close on individual toggle, close/open all options

- Don't start the engine immediately when controlling vehicle, it sucks having to move off the seat to turn on aisle/atomic lights

**Comment by sethsimon** [comment] 2017-01-05 00:01
>Don't start the engine immediately when controlling vehicle, it sucks having to move off the seat to turn on aisle/atomic lights

You can do this by [e]xamining the tile where the controls are (1-9, `.` can be used instead of 5) then selecting the `control vehicle` option.

>Keypresses should not be queued while (auto)saving the game

Why?

**Comment by Asmageddon** [comment] 2017-01-05 08:22
Because you intuitively press a key again when nothing happen, I've gotten into a crappy situation more than once this way.

**Comment by Coolthulhu** [comment] 2017-01-05 08:51
Github is for individual issues. If you have a list, it's better to post it on the forum.

**Comment by Asmageddon** [comment] 2017-01-05 11:14
Eh, I just didn't want to spam the repo with dozens of issues n.n I feel like if I post a collection of issues on forums it'll just be forgotten. I'd much rather leave it here so people can pick individual ones out and make issues for when they fix them or something.

**Comment by mutability** [comment] 2017-01-05 11:28
There are two main problems with a big list of stuff in an issue:

* you can't sensibly use the open/closed status of the issue (either the issue is eternally open or closed prematurely). If a commit is merged that says it fixes an item from the list, this issue is likely to get auto-closed.
* discussion of 20 different items in a single thread is never going to work well

**Comment by Leland** [comment] 2017-05-02 05:13
I'm closing this against my better judgement.

This is a big issue comprised of multiple suggestions - that really compromises GitHub's usefulness here.

I'd _highly_ recommend you create an issue for each of these. I know creating a lot of issues feels weird, but you  have so many good notes and ideas here that I really hope you do.

**Closed by Leland** 2017-05-02 05:13 UTC

**Comment by Asmageddon** [comment] 2017-05-02 08:22
I would... but this was a good while ago, and I feel like without the context of having played in a while(and the latest versions), I'm prone to goofing up... I'm sorry :(

**Comment by Leland** [comment] 2017-10-27 15:47
PS @OzoneH3 I know you like to resolve UI/UX issues; this issue is full of really good candidates. If any of these scream out at you, you could just make a new issue for them.
