### ISSUE TITLE
Firearm mods cannot be removed unless the weapon is loaded

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#50314] opened 2021-07-30 02:02 UTC
### Describe the bug

(a)ctivating a firearm in order to remove mods is impossible unless the weapon is loaded. Messages are:

- From the (a)ctivation menu: "Needs at least 1 charge".
- From the item menu: "Your $WEAPONNAME has 0 charges, but needs 1."

### Steps To Reproduce

1. Create a character with a rifle, a full mag, and a rifle sing.
2. Unload the rifle.
3. (a)ctivate the sling to attach it to the rifle.
4. Attempt to (a)ctivate the rifle to remove the sling.
5. Reload the rifle and attempt step 4 again.

### Expected behavior

Removing attachments should not depend on whether the firearm is loaded. Furthermore, having the weapon unloaded (and verified as such) for this purpose is a good firearms safety practice.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by actual-nh** [comment] 2021-07-30 02:23
Duplicate of #50157.

**Closed by actual-nh** 2021-07-30 02:23 UTC
