### ISSUE TITLE
When using the advanced inventory management menu (/) to discard items, clothes you wear will be discarded<Bug>

### ISSUE THREAD

**Issue by ochnan** [CleverRaven/Cataclysm-DDA#40881] opened 2020-05-27 01:32 UTC
# Describe the bug

- When using the advanced inventory management menu (/) to discard items, clothes you wear will be discarded

# Steps To Reproduce

1. Create a new character，Use the advanced inventory management menu (The shortcut key is“/”) 
2. Select backpack ”i” on one side and ground “5” on the other.
3. When you press “enter” to discard any item from your backpack “i”, the clothes you wear will be thrown to the ground instead of the items you want to throw away.

# Expected behavior

If you do the above operation, you should put the items you want to throw away at your feet, but what you throw away is the clothes you wear. I think there is a part of overlap or other bugs between the backpack（“i”） menu and the wearing menu（“w”） in the Advanced inventory management menu（“/”）, which will cause you to throw away the clothes in the same high position when you throw the items in the backpack.

# Versions and configuration

 - OS: [Windows 10 64bit]
 - Game Version: [0.E-2133-g9bb14f6、0.E-2453-g39c98b0、0.E-2491-g0f66604]
（This bug still exists in the previous version 2020/5/27/9:00）
 - Graphics version: [Tiles or Terminal]
 - Ingame language: [Chinese (Simplified) or English]
 - Mods loaded: [none]

**Comment by KorGgenT** [comment] 2020-05-27 02:14
Duplicate of #40610

**Closed** 2020-05-27 02:14 UTC
