### ISSUE TITLE
segfault crash when pressing ; to show only available recipes

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#71211] opened 2024-01-24 03:18 UTC
### Describe the bug

Segmentation Fault crash on build menu

### Attach save file

[Ishi-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14032179/Ishi-trimmed.tar.gz)

### Steps to reproduce

from attached save, open the building menu, press ';'

### Expected behavior

No crash when disassemble

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/72b9de31-e99f-4fed-aed0-f79f0aa91d26)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: da26ab2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14032185/crash.zip)

**Comment by andrei8l** [comment] 2024-01-24 03:22
/duplicate of #71164. Needs a msvc dev

**Closed** 2024-01-24 03:40 UTC
Labels: (S1 - Need confirmation)
