### ISSUE TITLE
SIGSEGV: Segmentation Fault Error on New World First Load

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#40911] opened 2020-05-28 05:05 UTC
Generated a new world in 10702 and on load am getting a Segmentation fault crash.

# Steps To Reproduce

Generate a new world in 10702 using the mods and such I've used
Create new character in said world
...
Profit

# Expected behavior

World generates/loads normally

# Screenshots

# Versions and configuration

 - OS: Win10
 - Game Version: 0.E-2570-gb8bc6f1 (10702)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Blaze, CRIT, Magiclysm, Zetsuke's Better Hair, MMA, Graphical Overmap, Graphical Overmap for Magiclysm, Military Profs, SpeedyDex, Stats through Kills, Stats through Skills

# Additional context

Possibly related to #40899

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4693356/crash.log)
[Farmington Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4693357/Farmington.Hills.zip)

**Comment by anothersimulacrum** [comment] 2020-05-28 05:08
This is indeed the same crash as #40899, so it's a duplicate of that.

**Closed** 2020-05-29 17:29 UTC
