### ISSUE TITLE
Linux Tiles release missing from 0.F-3

### ISSUE THREAD

**Issue by Elinvynia** [CleverRaven/Cataclysm-DDA#55745] opened 2022-02-28 07:35 UTC
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-3

All other stable releases include a Linux Tiles version, except this one. While it's still possible to compile it from the source code in that release, this makes it much harder for launchers like Catapult to support it.

### Steps to reproduce

n\a

### Expected behavior

n\a

### Versions and configuration

n\a

**Comment by NetSysFire** [comment] 2022-02-28 08:17
Duplicate of #53369

**Closed by NetSysFire** 2022-02-28 08:17 UTC

**Comment by Elinvynia** [comment] 2022-02-28 08:31
Sorry, wasn't able to find it via searching :(
