### ISSUE TITLE
SmashButton ISO map Broken On Android

### ISSUE THREAD

**Issue by MundaneRaven** [CleverRaven/Cataclysm-DDA#60169] opened 2022-08-15 05:01 UTC
### Describe the bug

The map used by SmashButton ISO tileset is broken. It is off center and can't be used to navegate. 

### Steps to reproduce

Start the game, change the tileset to SmashButton ISO, enter a save and use the map. 

### Expected behavior

The map is centered and the navegation works as intended. 

### Screenshots

![Screenshot_20220814-215634](https://user-images.githubusercontent.com/85593040/184578876-a53f31a1-2868-4f2f-8733-482c64264a1f.png)

### Versions and configuration

OS(android) 
Version(cdda-android-x64-2022-08-10-2037.apk
No idea on the rest.

**Comment by snipercup** [comment] 2022-08-15 09:15
Duplicate of #58951

**Closed** 2022-08-29 03:21 UTC
Labels: (S3 - Duplicate)
