### ISSUE TITLE
Vehicle UI behaves strangely

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#21085] opened 2017-05-22 06:08 UTC
If you mount more than a certain number of storage tanks or batteries (At 1600 by 900 it's about 20 and may depend on the size of your window) the vehicle UI starts to behave very strangely. Text gets jumbled, weapons aren't listed, and other issues.

It may be simpler to either give it a up/down scroll or compress it to categories. EG: Battery 10 storage batteries 25%, gasoline 4 tanks, 14% etc

Naturally this is of course another RMMC excessive construction situation but it's a bug none the less. Encountered it in version 0.c 22223-gdfe12f4099

**Comment by AMurkin** [comment] 2017-05-22 06:27
Could you provide a screenshot(s) for clarity?

**Comment by EkarusRyndren** [comment] 2017-05-22 06:36
Hopefully this makes it a bit more clear.
![new canvas 2](https://cloud.githubusercontent.com/assets/5553443/26295358/82484d1a-3e97-11e7-9f6a-4f0ac9cb42b8.jpg)

**Comment by ZenZen2** [comment] 2017-05-22 10:36
Once its full, the more you build in to the car the more disappear from the window overview.
I suggest: remove the free space below the type description and add scroll function.

**Comment by Zireael07** [comment] 2017-05-22 11:41
It looks like the scroll is a must.

**Comment by AMurkin** [comment] 2017-05-22 11:47
Also note #19887

**Comment by Zilenan91** [comment] 2017-05-22 17:54
How do you even scroll in most menus? I have never been able to figure it out.

The only one I've seen it work with is the kill count menu with I believe the arrow keys scrolling up and down, but trying to use the same keys for other scroll buttons just closes the menu.

**Comment by Zireael07** [comment] 2017-05-22 18:05
PgUp/PageDown is the usual for scrolling e.g. in keybinding or item descriptions or recipe descriptions.

**Comment by atealein** [comment] 2017-10-21 09:04
This is still an open problem, not only for late game players, but for ones that want to develop their vehicle as soon as they can - and because of the order of items in the medium column Engines > Tanks > Batteries > Turrets > Seats, very soon one is not able to see how much ammo is left in a turret of if everything is operating properly. 

Suggestion for the OP: can you maybe edit the title of the issue so it becames a bit clearer what the problem is? "behaves strangely" doesn't really have a ring of urgency or problem, really.

**Comment by Night-Pryanik** [comment] 2017-10-21 09:19
We need a total rework for the vehicle UI so it can seamlessly incorporate all the changes from the times it was originally designed. I think it should be post-0.D thing, though.

**Comment by atealein** [comment] 2017-11-10 11:15
Not only one can't see the ammo in the turrets, but also the plutonium left in the minireactors (which are listed below most things). This issue is not just a cosmetic problem :s And I understand that reworking the entire UI might be too large of a task at the moment, but is there a possibility that at least a workaround is applied, something similar to the "m" button for crafting which allows for scrolling down in the contents of very long recipes?

**Comment by mlangsdorf** [comment] 2018-08-25 03:52
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/25055

**Closed** 2018-08-25 04:13 UTC
Labels: <Bug>, Info / User Interface, Vehicles
