### ISSUE TITLE
crash/segfault when portal storm ends

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64532] opened 2023-03-24 19:43 UTC
### Describe the bug

title

### Attach save file

see additional context

### Steps to reproduce

1.wait out the portal storm (use the provided save)
2.game segfaults

### Expected behavior

N/A

### Versions and configuration

OS: Windows
        OS Version: 10.0.19044.2728 (21H2)
    Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/199ac9b7c590e7110c4026997bb145918cdab098 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife]
    ]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11066055/crash.log)
[Depths Of Jupiter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11066061/Depths.Of.Jupiter.zip)

**Comment by gettingusedto** [comment] 2023-03-24 21:18
possibly duplicate of #64466?

**Comment by Devengel** [comment] 2023-03-24 21:34
Nope, i opened my achievements before the portal storm happened. just in-case, then repeated this procedure a second time. Still crashes

**Comment by Ramza13** [comment] 2023-03-24 21:34
> possibly duplicate of #64466?

Nope it seems to be the result of an absence attacking a zombie miner.  I'm tracking it down now.

**Closed** 2023-03-26 03:33 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed)
