### ISSUE TITLE
Roadside foodcart in the middle of the road

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17476] opened 2016-07-02 01:44 UTC
On the left side:
![bug_roadside_foodcart_blocking_road](https://cloud.githubusercontent.com/assets/16765166/16537585/a7b842e8-3fd4-11e6-9c62-6f5f9ac93dc8.png)

It probably shouldn't try to spawn next to bridges.

**Comment by Oskar636** [comment] 2016-11-09 03:53
This needs the mapgen label.

**Comment by illi-kun** [comment] 2016-11-09 07:14
@Oskar636 thank you for help!

**Comment by Oskar636** [comment] 2016-11-09 07:18
Just trying to help with the 1000 issues :P.

**Comment by Leland** [comment] 2018-03-22 03:35
Marking as confirmed due to #19533, but closing as well due to lack of repro for devs. Been playing a lot and have literally never encountered this. These issues are also seriously old.

If anyone hits this again, please make a new issue with savefile included.

**Closed by Leland** 2018-03-22 03:35 UTC
Labels: Bug, Confirmed, Mapgen
