### ISSUE TITLE
Cooking/recipe addition. Ability to walk away from stove.

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#58309] opened 2022-06-09 18:26 UTC
### Is your feature request related to a problem? Please describe.

Cooking in CDDA is time consuming. IRL boiling and baking do not require full focus and we can make a sandwich or clean our room while we boil water.

I'd love to see some overhaul allowing us to manage our time while cooking, and cook multiple recipes at once if we have the space and ware.

### Solution you would like.

Add the ability to leave food cooking and perform other actions. This only applies to some recipes. Here are the main additions needed:

-New "Engagement" parameter for recipes with the following levels: "Full engagement" and "Can walk away".

-Add steps to recipes. Steps can have different engagement requirements. Baked goods may require "Full engagement" for the first part but "Can walk away" for the final baking step.

-Add a prompt when starting a recipe or step allowing the player to walk away - "Focus and complete" or "Leave unattended".
"Focus and complete" - the character will work on the recipe until it is completed. This functions like current crafting.
"Leave unattended" -  the player is able to resume normal gameplay while the recipe or recipe step carries on in real time.

-Something currently boiling or cooking can be examined at any time and the player can choose to "Focus and complete" or "Leave unattended". They should also be able to stop the procedure entirely.

-Water left boiling after it's required time should begin boiling away until it is gone. Food left cooking or baking too long should turn into ash/garbage/etc. There should be a possible fire hazard with this as well.

A message log of "The food smells done" and "The water is boiling" or similar could be used to indicate something has finished. The player could use an in game timer possibly as well. 

### Describe alternatives you have considered.

Instead of the engagement parameter, "Full engagement" is just the default, and a special tag for "Can walk away" is added for recipes with this and is displayed for only those recipes on the crafting screen.

Add additional engagement levels like "Some free time" and "Some attention needed" Where periodically during the process you will have to spend 30 seconds or a minute on the craft and then have free time again. This seems tedious, and with multiple steps for recipes either being free to walk away or requiring attention, i think it's unnecessary for now.

Different names for any of these parameters.

### Additional context

I had many thoughts on cooking stations. Adding 4 stovetop burners and 1 oven compartment to standard ovens, along with a whole lot of other ideas. It should probably be addressed separately. The main focus here should probably be just the ability to leave cooking unattended.

**Comment by Zireael07** [comment] 2022-06-09 18:39
Related/dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/55643 which would be partially fixed by https://github.com/CleverRaven/Cataclysm-DDA/issues/46775 ?

**Comment by chrispikula** [comment] 2022-06-09 20:03
What is old is new again.  This is something intended within routines, iirc.
#42556

**Comment by liminalRoar** [comment] 2022-06-09 20:15
Well, sorry folks, i hadn't seen that this has been addressed before and these are just my own thoughts. But it is nice to know others have had similar thoughts.

Thanks for posting these related threads!

**Comment by NetSysFire** [comment] 2022-06-09 20:57
Closing as duplicate.

**Closed by NetSysFire** 2022-06-09 20:57 UTC
Labels: <Suggestion / Discussion>
