### ISSUE TITLE
Bandit camp mission error.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#21451] opened 2017-07-20 04:12 UTC
Expected: The bandit NPCs should spawn in the bandit camp when the missions to become marshal is accepted in the refugee center by the old guard representative.

Issue: Bandits spawn in the refugee center itself and generate this error message: 
https://cdn.discordapp.com/attachments/166715724432277504/337449135060025344/unknown.png

How to reproduce: Accept the mission from the old guard representative to kill the bandit leader.

Additional notes: 
-Debugging shows that the camp did spawn despite the error but the NPCs still showed up in the refugee center instead.
-Teleporting to the spawn location and back, thus ensuring the map has been loaded up, didn't fix this either.

**Comment by Tharn** [comment] 2017-07-20 14:01
Yep, same thing here with two separate missions failing to spawn their locales and dropping the bandits right on top of me.

**Comment by aka-azrad** [comment] 2017-07-24 07:33
When that happens, there also seems to be a second effect of spawning land mines where the bandits get spawned in the refugee center. Saw one that spawned in a window.

**Comment by Leland** [comment] 2017-08-16 03:08
@Noctifer-de-Mortem can you retest this? #21212 should fix it.

**Comment by Coolthulhu** [comment] 2017-11-08 01:36
Does it still happen?

**Comment by Night-Pryanik** [comment] 2017-11-08 05:27
>Does it still happen?

Yes, it does.

**Comment by sxmichaels** [comment] 2017-11-30 08:20
It looks like this is fundamentally the same bug as #20758. Having just done some testing, it occurs in the current version (`4f691a95a3`) using the save file provided in that post, but newly-generated maps spawned the bandits properly. Pending evidence that this issue still exists in worlds generated by recent versions, should we close it for now?

**Comment by Night-Pryanik** [comment] 2017-11-30 08:32
Closing for now. If this issue still occurs, feel free to ping me so I reopen it.

**Comment by Night-Pryanik** [comment] 2017-12-03 11:56
Tested right now on latest experimental with a new world. The bug still exist.

**Comment by sxmichaels** [comment] 2017-12-05 08:08
Weird. Given that it only happens sporadically — and that the other bug I mentioned mentions the game freezing — I suspect it has to do with the mapgen code not finding a bandit camp in the vicinity. [`place_bandit_cabin()` in `mission_start.cpp:258`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mission_start.cpp#L258) looks for a tile of type `bandit_cabin` via `target_om_ter_random()`, which defaults to returning the user's current overmap tile if it can't find anything:

```
    auto places = overmap_buffer.find_all( g->u.global_omt_location(), omter, range, must_see );
    if( places.size() == 0 ) {
        debugmsg( "Couldn't find %s", omter.c_str() );
        return g->u.global_omt_location();
    }
```

Strictly speaking, the issue is in the mapgen code, but I've not worked with it yet and I have no idea how difficult it would be to guarantee that a certain tile spawns within a given radius at the mapgen stage. Would it be feasible, in the case where no `bandit_camp` tile is found, to just _create_ one in a nearby location the player hasn't visited yet?

**Comment by Night-Pryanik** [comment] 2017-12-05 10:11
>Would it be feasible, in the case where no bandit_cabin tile is found, to just create one in a nearby location the player hasn't visited yet? 

I find this a good way to resolve the issue.

**Comment by kevingranade** [comment] 2017-12-05 17:43
> Would it be feasible, in the case where no bandit_cabin tile is found, to just create one in a nearby location the player hasn't visited yet?

I agree, this is a totally reasonable solution.

**Closed** 2017-12-07 05:24 UTC
Labels: Bug, Confirmed, Mission
