### ISSUE TITLE
Uncanny dodge can no longer dodge bullets. Intended feature?

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#22825] opened 2018-01-29 03:53 UTC
I remember the ability could dodge bullets, but this doesnt happen anymore. Did it lose this functionality on accident or was the change made on purpose?

**Comment by Leland** [comment] 2018-01-29 15:26
Duplicate of #15078

Looks like it's been an issue for a long while – at least a couple years.

**Closed by Leland** 2018-01-29 15:26 UTC
