### ISSUE TITLE
Performance in Refugee Center is sub-optimal

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#32232] opened 2019-07-07 13:01 UTC
# Describe the bug
Crafting, sleeping or anything else that requires time to pass is very, very slow.

Playing with Z-Levels on

Latest experimentals

**Comment by esotericist** [comment] 2019-07-07 13:10
Duplicate of #30045

**Comment by esotericist** [comment] 2019-07-07 13:11
For what it's worth, this is an active area of focus for optimization right now.

**Closed by esotericist** 2019-07-07 13:10 UTC
