### ISSUE TITLE
Game crash when loading game

### ISSUE THREAD

**Issue by Ithilrandir** [CleverRaven/Cataclysm-DDA#55090] opened 2022-02-04 10:27 UTC
### Describe the bug

The game crashes when attempting to load any save. This includes fresh saves.

### Steps to reproduce

Start the game a lot of mods enabled: bionic professions, blaze, crit, magiclysm, dinomod, crazy cataclysm, extra mutated scenarios, mythical martial arts, speedydex, stat through kills and stat through skills.

Save a game and immediately exit and attempt to load

### Expected behavior

Game will load until the last step then ctd

### Versions and configuration

Cataclysm-DDA experimental build 2022-02-04-0647

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8002002/crash.log)

**Comment by Leland** [comment] 2022-02-04 14:30
I have a favor to ask ☺️ Could you try going through and loading saves with no mods enabled?

If a vanilla save works, it would be fantastic if you’d then try making a couple more saves, flipping on mods and trying to perhaps narrow down if this is caused by a specific one!

**Comment by Ithilrandir** [comment] 2022-02-04 15:25
I tested with 0 mods and it still crashed.

**Comment by Ithilrandir** [comment] 2022-02-04 15:26
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8004182/crash.log)

**Comment by BrettDong** [comment] 2022-02-04 15:34
Duplicate of #55075

**Comment by wapcaplet** [comment] 2022-02-05 02:10
Closing as duplicate.

**Closed by wapcaplet** 2022-02-05 02:10 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
