### ISSUE TITLE
Crash with an unclear cause

### ISSUE THREAD

**Issue by fartknuckle** [CleverRaven/Cataclysm-DDA#69403] opened 2023-11-15 07:33 UTC
### Describe the bug

I wish I could be more precise with this report but at present I cannot find anything that causes it. It appears to be a random crash that occurs within 5 minutes of creating a new world or character.

### Attach save file

[Barbourville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13361574/Barbourville-trimmed.tar.gz)

### Steps to reproduce

1. Make a character.
2. Pass enough turns to crash.

### Expected behavior

For a crash to not occur - failing that, a crash with a noticeable cause.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 9bb111f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Mind Over Matter [mindovermatter],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13361608/config.zip)
The Defense Mode error at the end of the debug.log only shows up upon exiting the game normally.

**Comment by andrei8l** [comment] 2023-11-15 07:40
Duplicate of #69396

**Comment by RenechCDDA** [comment] 2023-11-15 07:52
Duplicate of #69396

**Closed by RenechCDDA** 2023-11-15 07:52 UTC
Labels: (S1 - Need confirmation)
