### ISSUE TITLE
Electric vehicles are underpowered compared to gas/diesel

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20411] opened 2017-02-28 11:35 UTC
Old problem. Would be good to fix it for 0.D.

**Comment by kevingranade** [comment] 2017-02-28 23:17
Need a definition of underpowered, and a rationale for why that is a bad
thing.

Irl electric vehicles are reasonable because we have ubiquitous, cheap
electricity.

Post cataclysm electricity loses both of these properties, so of course
electric vehicles would suffer.

**Comment by kolsurma** [comment] 2017-03-01 00:30
But the engines are generally from vehicles that are pre-cataclysm, they would be just as powerful and / or efficient as they used to be. Things like the electric SUV & electric car shouldn't exist at all if they're as inefficient as they are post-cataclysm.

It may just be that they need more batteries to bring them to the same level as gas/diesel. The built in storage battery just doesn't allow the same range as even a 10 liter tank of gas/diesel.

**Comment by Tharn** [comment] 2017-03-01 01:21
Somewhere, the equation is a bit off. If you have a vehicle with 12 storage batteries and 40ish solar panels (my APC), it still does take them a long time to recharge all those batteries. And they don't even get very far with that many batteries. If you're keeping the charge to mileage ratio, then solar panels could be beefed up. If not, you could lessen the power draw so electric cars can at least get somewhere before being forced out of commission for days at a time. I prefer the second option.

I'm not advocating electric cars to be as good as gas or diesel counterparts. Just for the frustration to be eased a bit. Is the ability to drive long distances really that precious? Where are you gonna go? The map spawns a whole variety of stuff pretty much on your doorstep, and you can get a lot of toys within the travel radius of a bicycle. Oh also.. gas and diesel aren't precious either. They're found everywhere. Either make vehicle fuels hard to come by across the board and leave electric cars as they are, or ease the boot off electric cars a bit, I'd say.

**Comment by Coolthulhu** [comment] 2017-03-01 08:01
> Need a definition of underpowered, and a rationale for why that is a bad thing.

Underpowered would be "worse than some alternative in almost every situation".
In this case, "worse" means:
* Lower mileage per weight of fuel (tank vs battery)
* Lower power output
* Harder to recharge in most cases

The recent changes did improve the ratio a lot (though more by nerfing gas than buffing batteries) - car and an electric car moving at safe speeds have comparable mileage (gas car has 35% more).
But then, as soon as we add stops every 5 turns, the extra mass of electric car makes it drop efficiency to 0. Ironically, IRL one of the advantages of electric vehicles is their seamless starting and stopping.

Electric vehicles have their niche, but it is pushed way too late in the endgame. To properly use them, player needs to mount a whole rack of solars on top of the vehicle and turn it into a "roller" rather than "car".

Now that I think about it, I remembered a good gimmick to handle both start/stop problems and mileage:
Regenerative braking
Y/N?

**Comment by tinukedaya** [comment] 2017-03-01 11:28
I tend to agree here with this statement...
>Post cataclysm electricity loses both of these properties, so of course
electric vehicles would suffer.

Yes batteries are heavy and mileage sucks, but that is kinda the thing about electric cars nowdays either and I do not see that getting much better anytime soon. 


Now, if you add
>Now that I think about it, I remembered a good gimmick to handle both start/stop problems and mileage:
>Regenerative braking

that will help a lot and makes sense. Any other buffs to pure electrocars should really be just minor.

What I would like to see is the ability to create real hydrid car. Have an gas/diesel engine installed on a car that will not be connected to the powertrain but you can run is as generator to fill up the batteries. Even IRL this is IMHO the optimal way to do it.

Last time I got that far in car management in DDA I had electric Military truck with secondary gas/diesel engine and when I run out of batteries I switched to it to recharge.

**Comment by glenmack** [comment] 2017-03-02 09:55
Regenerative Braking would be an excellent addition to bring electric cars more in line with combustion counterparts. At current top tier racing levels regenerative braking systems can produce as much power as a small petrol engine. (160hp/120kW)

https://www.motorsport.com/f1/news/technique-the-mgu-k-and-mgu-h-explained-791187/

Though this is hybrid and the power is used to make the combustion engine more efficient.

The recovery of energy is more difficult to find info on but Tesla systems the energy recovery is around 64%.

https://www.tesla.com/blog/magic-tesla-roadster-regenerative-braking

As Coolthulu said

> said The recent changes did improve the ratio a lot (though more by nerfing gas than buffing batteries) - car and an electric car moving at safe speeds have comparable mileage (gas car has 35% more).
But then, as soon as we add stops every 5 turns, the extra mass of electric car makes it drop efficiency to 0. Ironically, IRL one of the advantages of electric vehicles is their seamless starting and stopping.

So a regenerative braking system that brings electric engines to within 5-10% of the efficiency of combustion counterparts in the C:DDA future seems reasonable. I would still have it be less efficient, but then we have balance.

To keep them late game, I would suggest having a regenerative braking system that was uncraftable, and irremovable with an electronics skill of less than 8, maybe 9 (I think going from 8 to 9 with practical crafting of upgraded solar panels would ensure "practical knowledge"). They should only be repairable with an electronics + mechanics skill of above 6 on both counts and very easily damaged. This would ensure self sustaining bases remain a late game option only.

**Comment by Coolthulhu** [comment] 2017-03-02 10:03
> To keep them late game, I would suggest having a regenerative braking system that was uncraftable, and irremovable with an electronics skill of less than 8, maybe 9 (I think going from 8 to 9 with practical crafting of upgraded solar panels would ensure "practical knowledge").

They will stay in late game by the fact that the fuel for them isn't stored as well - tanks are much more efficient at their job than batteries.

Isn't regenerative braking in the most common configuration achievable with the engine alone? From what I recall, the electric engine will essentially function as an alternator in overdrive to provide the braking.

**Comment by glenmack** [comment] 2017-03-02 10:19
> Isn't regenerative braking in the most common configuration achievable with the engine alone? From what I recall, the electric engine will essentially function as an alternator in overdrive to provide the braking.

Yes, but I think it depends on how deep the person wants to go with developing it.

I think the best and simplest implementation is to only have it function when only electric motors are being used in the vehicle and have it be an alternator that functions at 20-30% of the main electric engine's epower consumption.

**Comment by kevingranade** [comment] 2017-03-02 18:00
On Mar 2, 2017 2:19 AM, "glenmack" <notifications@github.com> wrote:

I think the best and simplest implementation is to only have it function
when only electric motors are being used in the vehicle and have it be an
alternator that functions at 20-30% of the main electric engine's epower
consumption.

The simplest implementation is to assume it's being used and just increase
the efficiency of electric engines. We only need to explicitly add it if we
want the *behavior* of regenerative braking.  Of course this needs to be
documented so people don't repeat the process and ratchet up effective
efficiency of electric engines.

**Comment by 1skandar** [comment] 2017-03-02 21:53
I would also like to add that most electric cars are using large electric motors currently. It might be worth testing if moving to just electric motors still gives decent safe speed.

As well, it might be worthwhile to give them their own niche. Make them very efficient compared to gas, but give them next to no ability to handle excess weight. You want a light, agile car for scouting, fine. But creep up to doom machine levels and you'll quickly end up stationary. This will also pretty much stop the ability to just load an arbitrary amount of solar panels on an electric car to make it have infinite range.

**Comment by WizardOfOoo** [comment] 2017-03-02 23:06
A given electric version should have the same or slightly less range than the gasoline version.

**Comment by Wad67** [comment] 2017-03-03 05:24
I'd like to draw your attention to a real life example of a homemade electric vehicle. 
[http://www.thebackshed.com/basiclynatural/EVConversion.asp](url)

**Comment by spacenookie** [comment] 2017-03-04 12:10
how about internal furnace for cars, you could forage 2x4s and tires to recharge your car

**Comment by WizardOfOoo** [comment] 2017-03-04 14:27
That is a thing!

https://en.wikipedia.org/wiki/Wood_gas#Internal_combustion_engine

**Comment by Coolthulhu** [comment] 2017-03-05 12:44
OK, tests are all wrong and the problem is much worse than I made it look above:
I just did a "manual" test doing the exact same thing as the automatic test was supposed to do and found that crossing an overmap of dirt uses up 12.5% of electric car's capacity, but only 5% of regular car's. Electric car has better offroading capacity, so that can't be the problem here.

**Comment by glenmack** [comment] 2017-03-05 14:59
> OK, tests are all wrong and the problem is much worse than I made it look above:
I just did a "manual" test doing the exact same thing as the automatic test was supposed to do and found that crossing an overmap of dirt uses up 12.5% of electric car's capacity, but only 5% of regular car's. Electric car has better offroading capacity, so that can't be the problem here.

To be honest, that's not a bad thing if you can add in a regenerative breaking system that brings that down to like 8% of an electric car battery.

The difference between electric and petrol cars as we forward in the future isn't going to be range, but maintenance. Electric cars are going to be harder to maintain and I think a very fragile regenerative braking system differentiates between combustion and gas nicely.

You can build a huge electric deathmobile, but the moment you use it to ram things, the efficiency would drop hugely as the regenerative braking system fails. That gives you a more direct gameplay trade-off than waiting for solar panel charge, which is the only significant difference now. (And a pretty poor gameplay mechanic, no matter the realism involved.)

**Comment by Coolthulhu** [comment] 2017-03-05 15:27
Part damage isn't implemented well enough for anything like this to matter.
For now the only meaningful comparison is to assume all parts are in perfect working order.

**Comment by WizardOfOoo** [comment] 2017-03-05 16:06
Electric cars are much easier to maintain than conventional.

**Comment by glenmack** [comment] 2017-03-05 16:57
> Electric cars are much easier to maintain than conventional.

I'm not talking about day to day maintenance. I'm talking about replacement parts/diagnosing problems/battery performance issues. As they get more complex they will require more specialised equipment to fix. Which is the only way it should relate to C:DDA

**Comment by Coolthulhu** [comment] 2017-03-05 17:14
> I'm talking about replacement parts/diagnosing problems/battery performance issues. As they get more complex they will require more specialised equipment to fix. Which is the only way it should relate to C:DDA

The problem is, to make that work, all spawned engines would need to be broken. And the equipment would only need to be gathered once to make them work.
A quest for parts for sci-fi electric superengine could be pretty cool, but it wouldn't be a lasting balance factor - you get it and then you have it.

That's the most sensible balancing factor I see that includes any form of maintenance. Other ideas I can think of - for example, having engines wear down and break - would be so utterly anti-fun and needlessly tedious that I shouldn't need to even explain why.

**Comment by glenmack** [comment] 2017-03-05 18:53
> That's the most sensible balancing factor I see that includes any form of maintenance. Other ideas I can think of - for example, having engines wear down and break - would be so utterly anti-fun and needlessly tedious that I shouldn't need to even explain why.

That's because, as you said, the part damage system for collisions isn't up to snuff for having wear down and breakage be directly linked to player action.

The balance point should be player vehicle design and player action oriented.

Just like light armor has an encumbrance trade-off the current trade off is waiting for battery charge. Also anti-fun and needlessly tedious. Waiting isn't fun, but as things stand "scavenging" for petrol isn't particularly well balanced.

Ultimately you can knock down any idea if you reduce it to scavenging and repeating. But that is the entire gameplay loop. Could the regenerative braking system's damage be linked to vehicle status? How is vehicle collision detected and could you bypass the transfer of energy to simply saying 1 collision above 20mph equals 50% damage to the system?

**Comment by 1skandar** [comment] 2017-03-05 20:06
Actually, an electric motor, at its core, is a much simpler system than an internal combustion engine. A coil of wire with a magnet inside, provide electrical current and the magnet spins. And, unlike a IC engine, there is no need of gearing, no need of a transmission. While it isn't done routinely for cars, it is a fairly routine DIY project to convert a motorcycle over to electric from gas.

Oh, and about the whole maintenance thing, Pfft. Parts would be harder to come by, but overall an electric engine is more durable than an IC engine since it isn't being driven by, ya know, tiny explosions under high heat. That means that an electric engine doesn't need an elaborate cooling system or engine oil, for starters. 

Pretty much an electric car beats the snot out of an IC car in pretty much all ways...minus one big one. Range. And, well, refilling the "tank". While those issues are being solved, batteries are *still* heavy and refilling them takes a few hours.

**Comment by Coolthulhu** [comment] 2017-03-05 20:49
> Just like light armor has an encumbrance trade-off the current trade off is waiting for battery charge. Also anti-fun and needlessly tedious.

I'm open to suggestions on how to make battery charging only needfully tedious.
Necessary evil that happens offscreen is not the same grade of evil as manual maintenance.

**Comment by 1skandar** [comment] 2017-03-05 20:59
I don't find charging to be be *that* bad. The only real issue really is the current efficiency. Under normal use you should get about 6 to 8 hours of use out of a set of batteries, and you really don't get that currently. It's not horribly unbalanced, but bumping things up a bit would likely fix things.

**Comment by glenmack** [comment] 2017-03-05 21:02
> Actually, an electric motor, at its core, is a much simpler system than an internal combustion engine. A coil of wire with a magnet inside, provide electrical current and the magnet spins. And, unlike a IC engine, there is no need of gearing, no need of a transmission. While it isn't done routinely for cars, it is a fairly routine DIY project to convert a motorcycle over to electric from gas.

Great. Pity I'm not talking about an electric engine in isolation though. Or a simple DIY project. I'm talking about proprietary electrical propulsion technologies like the Tesla, I'm talking about all the things working in concert to make a vehicle run in an apocalypse.

My friend owns a Tesla. It has spent 7 of the 18 months he's owned it in the Tesla garages. How many local mechanics do you know that would offer to fix a Tesla?

You're right that parts would be harder to come by. Especially for all the things that give it range... Like a regenerative braking system... Like Torque management controls, like all the things that have gone wrong with my mates car. (including those two specific things.)

And like I said, I'm not asking for "automatic" maintenance. I'm asking for maintenance forced by player action. Use the vehicle off-road, or over-stressing the engine, or ramming into things. These should cause wear and tear. Moreso on an electric vehicles RANGE systems specifically. (which we currently don't have.)

**Comment by WizardOfOoo** [comment] 2017-03-05 21:08
Which tesla is it?

**Comment by glenmack** [comment] 2017-03-05 21:11
I think it's a 2015 model S? Could text him to find out but it's pretty late here.

**Comment by 1skandar** [comment] 2017-03-05 21:15
Regenerative braking isn't that complex. It's an electric motor in reverse, as in a magnet spins causing a copper wire coil to generate electricity. The rest of it is computer controlled, and computer problems aren't going to be unique to an electric car. 

At any rate, since we *don't* have maintenance yet I still think the better balance point should be weight. An electric car should be much more efficient that an IC vehicle at low weight. However, the speed should quickly fall off past a certain rather light weight. That would give electric cars their own niche without making them the be all and end all for vehicle construction. It would also serve to make electric vehicles more fragile overall simply because there wouldn't be weight available for heavy duty parts nor armor.

**Comment by Coolthulhu** [comment] 2017-03-05 21:26
> I'm asking for maintenance forced by player action. Use the vehicle off-road, or over-stressing the engine, or ramming into things.

So, avoiding every shrub and every collision not to have to deal with tedium. Sounds like one of "those" additions to me.
If you want expensive fuel engine for which you need to scavenge, it would be better to have a sci-fi engine that uses up rare fuel than to force tedious management on engine type pretty much defined by its low maintenance (no fuel, just waiting).

> At any rate, since we don't have maintenance yet I still think the better balance point should be weight. An electric car should be much more efficient that an IC vehicle at low weight.

This would prohibit it form being effectively used for deathrollers and general transport vehicles, though.
And the batteries themselves are heavy.
The reverse could make more sense: electric vehicles being forced by battery weight to be heavy duty (or full solar mode - those would be light).

**Comment by WizardOfOoo** [comment] 2017-03-05 21:45
The model S is a high-performance sports car.  it goes 0–60 mph (0–97 km/h) in 2.28 seconds.  It's on the edge of the performance envelope for production electric cars.  Anything like that is going to have increased maintenance requirements.  The electric cars that a survivor would build would not be anywhere close to that fast or complicated, thus much-reduced maintenance requirements.

**Comment by 1skandar** [comment] 2017-03-05 21:50
> This would prohibit it form being effectively used for deathrollers and general transport vehicles, though.

Which is kinda the point. If you want to cut down on "free" power, this is a good spot to do it. A way to balance unlimited energy versus the more limited fuels. And yes, batteries are going to be heavy, as they should be. Battery weight is actually one of the biggest limitations of current electric vehicles, so it would make sense that trend should continue into the future.

**Comment by Coolthulhu** [comment] 2017-03-05 21:55
> If you want to cut down on "free" power, this is a good spot to do it.

No, it's the opposite of what actually has to be done: it would hurt the only consumer of electric energy that doesn't need to be nerfed, while leaving all the others untouched.
The whole problem with vehicle energy is that tools and engines are on a different scale. Making engines use more power can't help here at all.

**Comment by glenmack** [comment] 2017-03-05 22:02
Wow

> The model S is a high-performance sports car. it goes 0–60 mph (0–97 km/h) in 2.28 seconds. It's on the edge of the performance envelope for production electric cars. Anything like that is going to have increased maintenance requirements. The electric cars that a survivor would build would not be anywhere close to that fast or complicated, thus much-reduced maintenance requirements compared to an IC car.

Yes. And you know what? It has regenerative braking, complicated traction control, cutting edge computers.

You know why? To get the most range out of batteries. Because batteries are terrible and are very likely to be terrible for the foreseeable future. Which is why it is entirely relevant. Keep focusing on tiny details and you miss the entire point. We're talking about how to balance range vs. IC engines in a game heavily reliant on a realistic universe. In a near future where electric cars are 40/60 with IC ones, they are all going to have these systems if batteries are as terrible as they are in game.

> So, avoiding every shrub and every collision not to have to deal with tedium. Sounds like one of "those" additions to me.

No, you don't install the parts that extend range, you won't have to avoid any collisions. You could build an electric deathroller, it would just have terrible range and horrible power consumption like it currently does. Giving it balance against IC engines. It would make Electric engines more suitable for mobile bases but less suitable for deathrollers.

**Comment by kevingranade** [comment] 2017-03-06 05:52
> Actually, an electric motor, at its core, is a much simpler system than an internal combustion engine. A coil of wire with a magnet inside, provide electrical current and the magnet spins. And, unlike a IC engine, there is no need of gearing, no need of a transmission. While it isn't done routinely for cars, it is a fairly routine DIY project to convert a motorcycle over to electric from gas.

You're massively underestimating how complicated these things are.  I guarantee it's extremely rare to convert a motorcycle or anything else to use a handmade motor. They're not just a wire coil (not to mention the bushings, which get extremely difficult to make robust and efficient at very high loads), high-output motors have extremely tight tolerances and very sophisticated design to handle a lot of electrical issues that don't come up unless you're pushing the involved materials to their limits.

Back on topic, this:
> car and an electric car moving at safe speeds have comparable mileage (gas car has 35% more).

Isn't actually contradicted by this:
> crossing an overmap of dirt uses up 12.5% of electric car's capacity, but only 5% of regular car's.

So it's not clear what the actual extent of the problem is.
Again, we need a good definition of the goal state, in terms of maximum range for standard vehicles (mostly a realism benchmark, but it's a decent starting point) or range per unit of fuel (requires some kind of equivalence for fuel units), or some synthetic measure like range per fillup action (for electric it would be some combination of solar performance per time plus lootable battery sources, for fuel it would be something related to density of lootable petroleum products).  We could also have some invariants around power/weight ratios just to lock down one aspect of performance.

**Comment by 1skandar** [comment] 2017-03-06 06:21
> You're massively underestimating how complicated these things are. I guarantee it's extremely rare to convert a motorcycle or anything else to use a handmade motor. They're not just a wire coil (not to mention the bushings, which get extremely difficult to make robust and efficient at very high loads), high-output motors have extremely tight tolerances and very sophisticated design to handle a lot of electrical issues that don't come up unless you're pushing the involved materials to their limits.

Well, yes I did massively simplify but it doesn't change the fact an electric motor is much, much simpler in design than an IC engine, which is my point. And I never said anything about *handmade* electric motors, just that people do, fairly commonly, convert a motorcycle to electric. Not meaning to stray from the topic too much, I was just trying to dispel the notion that an electric vehicle would be this high maintenance futuristic thing. In reality, it is the IC engines that would be more prone to break down and needing hard to perform maintenance in a Cata type situation.

>Again, we need a good definition of the goal state, in terms of maximum range for standard vehicles (mostly a realism benchmark, but it's a decent starting point)

Well, since we want to avoid tying tiles to any set length (something I agree with) it is easiest to do so via time  between fill ups. I'd say for IC engines cruising around an average of 30 to 40  mph (which is about where I set my vehicles in game) 8 hours is about right? That would give a range around 240 to 320 miles per tank, which is fairly close to real world standards.

**Comment by glenmack** [comment] 2017-03-06 11:55
**Kevin Granade**

> So it's not clear what the actual extent of the problem is.

The problem is that it's completely arbitrary where the equivalencies are drawn.

Currently electric cars represent less than 1% of all cars on the road. C:DDA presents a world where Electric cars are only slightly less numerous than cars with IC engines. So if you're going to say there's no problem with them having significantly less range than IC engines, then make them appear less than 1% of the time as well. If realism is the only point then gameplay is irrelevant.

Range and charging time are the two main reasons they don't have widespread adoption currently. Which is presumably why Coolthulu started this thread in the first place. Both of those things are significantly game-play relevant when it comes to vehicles.

If we're going to have widespread adoption of Electric vehicles in C:DDA, there needs to be a C:DDA based logic as to why they are so equivalent. They need to be in some way, at least on road, roughly the same as IC engines. Otherwise their poor range and terrible efficiency makes no sense compared to how numerous they are.

**Comment by kevingranade** [comment] 2017-03-06 17:33
The frequency of electric cars isn't some statement about how well electric
cars work in CDDA world. Just assume present day realities and remove
petroleum subsidies, nothing about technology changes but all of a sudden
electric cars would be far more desireable.

**Comment by WizardOfOoo** [comment] 2017-03-06 18:40
>OK, tests are all wrong and the problem is much worse than I made it look above:
I just did a "manual" test doing the exact same thing as the automatic test was supposed to do and found that crossing an overmap of dirt uses up 12.5% of electric car's capacity, but only 5% of regular car's. Electric car has better offroading capacity, so that can't be the problem here.

The 2017 Chevy bolt goes 238 miles on one charge.  That's an all electric car that weighs 3500lbs (~1580 kg)
https://en.wikipedia.org/wiki/Chevrolet_Bolt#Range_and_efficiency

**Comment by glenmack** [comment] 2017-03-06 20:27
> The frequency of electric cars isn't some statement about how well electric cars work in CDDA world. Just assume present day realities and remove petroleum subsidies, nothing about technology changes but all of a sudden electric cars would be far more desireable.

Ok, assumption made. The game still lacks all of the secondary and tertiary systems that make real life electric cars as viable as they are. If you want them to be assumed the same, you need to make them the same.

**Comment by kevingranade** [comment] 2017-03-10 03:18
Considering that we don't have as much as a clear definition of the problem, I'm taking this off the list of 0.D blockers.

**Comment by Coolthulhu** [comment] 2017-03-10 03:22
Well, 1/4 of a storage battery per overmap on dirt is tolerable. Not good, but not a huge immediate alarm.

**Comment by kevingranade** [comment] 2017-09-08 00:12
Half a year later, and still no clear problem statement, closing.

**Closed by kevingranade** 2017-09-08 00:12 UTC
Labels: Balance, Vehicle
