### ISSUE TITLE
Add sensible defaults to reload menu

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15555] opened 2016-02-25 16:41 UTC
Current reload menu gets tedious when used a lot, as it requires setting inventory letters to ammo and doesn't offer good defaults. Makes using RELOAD_AND_SHOOT and one shot weapons a pain.

I see those solutions:
- Allow selecting default option with the same keybind as the last used one (fire or reload), unless there is an item in this menu using that exact inventory letter already. Make repeating the fire/reload command always select some correct option, no matter the keybinds and inventory letters. Preferably select the last option, so that it doesn't alternate or anything like that (possibly with an exception for magazines with more capacity than ammo in last selected option).
- Add some sort of ammo type marking/linking system that would allow, for example, selecting an arrow type and location for a bow and then always re-using ammo with matching type and location for as long as possible. Preferably automatic, so that it links to the last type/location used, with an option to unlink manually (for example, to alternate arrow/shot types).
- Ugly hack: when an item with some (explicitly manually set) inventory letter can be selected, select it and don't present the menu at all

**Comment by kevingranade** [comment] 2016-02-25 17:14
On Feb 25, 2016 8:41 AM, "Coolthulhu" <notifications@github.com> wrote:
>
> I see those solutions:
>
> Allow selecting default option with the same keybind as the last used one
(fire or reload), unless there is an item in this menu using that exact
inventory letter already.

We could blacklist ammo items from being assigned to the fire and reload
keybinds.

> Add some sort of ammo type marking/linking system that would allow, for
example, selecting an arrow type and location for a bow and then always
re-using ammo with matching type and location for as long as possible.
Preferably automatic, so that it links to the last type/location used, with
an option to unlink manually (for example, to alternate arrow/shot types).

The only way this makes sense to me is if it's a separate, "fire with
previous ammo" action. If it's the default people might have trouble
figuring out how to switch ammo types.

> Ugly hack: when an item with some (explicitly manually set) inventory
letter can be selected, select it and don't present the menu at all

I don't like tying actions together with inventory letters, instead there
could be an action to mark ammo as "only use this instance of this ammo
type" (which supresses the menu when fire or reload is invoked on a
compatible item) and/or "don't use this ammo" (which reduces the list of
valid alternatives, if the list is one long we bypass the menu).

**Comment by mugling** [comment] 2016-02-25 22:49
> Allow selecting default option with the same keybind as the last used one (fire or reload), unless there is an item in this menu using that exact inventory letter already

As of #15413 this was the intended behavior but there also appears to be a temporary regression in the assignment of hotkeys and also the sort ordering which I'm looking into.

**Comment by mugling** [comment] 2016-02-26 22:46
> instead there could be an action to mark ammo as "only use this instance of this ammo type" (which supresses the menu when fire or reload is invoked on a compatible item) and/or "don't use this ammo" (which reduces the list of valid alternatives, if the list is one long we bypass the menu).

This could work well and I'm going to prototype an implementation now

**Comment by mugling** [comment] 2016-03-09 17:21
@Coolthulhu excluding #15566 is there anything else outstanding for this issue?

**Comment by Coolthulhu** [comment] 2016-03-09 17:33
Will have to test with recent changes and bows. Bows are usually the most problematic case here.

**Comment by mugling** [comment] 2016-03-09 17:35
Sure. I'm trying to consolidate the remaining interface issue to determine what remains outstanding.

**Comment by Coolthulhu** [comment] 2016-03-09 20:09
I tested it and it doesn't really look as it solves the issue with bows:
* Quivers don't pass their invlets to ammo inside, meaning that having a quiver under 'f' won't make 'f'->'f' work
* Confirming firing with 'f' or 'r' doesn't work unless there are compatible items under those invlets. Setting invlets can't be required when we're talking about defaults.

#15566 could solve it if it remembered the last used ammo and allowed un-setting it in relatively intuitive way.

Maybe integrate ammo selection into aiming menu somehow?

**Closed** 2017-03-12 22:57 UTC
Labels: Information / Interface
