### ISSUE TITLE
Big Chunk of Overmap Exploration lost and Notes/Explored tiles reset

### ISSUE THREAD

**Issue by chance-m** [CleverRaven/Cataclysm-DDA#51522] opened 2021-09-11 06:19 UTC
### Describe the bug

I loaded into my game and opened the Overmap to find that a huge chunk that I had explored got reset and all the notes I had within the chunk were deleted. Also, all of the buildings I had explored and marked as such were reset to unexplored. I should also point out that all vehicles that I remembered are still there, but not roads discovered from maps. Last point, I used the debug/cheat menu to reveal the map. Then I saved and exited and reopened and the same square section was reset again. 

### Steps To Reproduce

1. Start game via CDDA Launcher.
2. Load most recent save.
3. Open Overmap. 

### Expected behavior

Expected the large amount of progress I had made to stay on the Overmap, as well as the notes I created and buildings I marked as explored to stay that way. It only seems to be affecting a square portion of the map (see screen shots).

### Screenshots

![OvermapReset2](https://user-images.githubusercontent.com/55067201/132938437-e561372e-4a4e-42d3-a83b-c5abd72b042e.PNG)

- I highlighted the area that was reset. 

![OvermapReset3](https://user-images.githubusercontent.com/55067201/132938439-61e191cd-f7af-46f8-8b81-7f3c3df2af7f.PNG)

- Just a reference to other parts of the map and you can see the notes and other things. 

![OvermapReset](https://user-images.githubusercontent.com/55067201/132938442-306fc83a-7b90-43bd-8de9-c67ab4621760.PNG)

- You can see the two cars I had remembered in the reset portion of the map. 

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental fbd0d6b (tiles), build: 2021-09-11-0205
- Ingame language: English
- Mods:   
  dda,
  no_npc_food,
  package_bionic_professions,
  magiclysm,
  Graphical_Overmap,
  Graphical_Overmap_Magiclysm,
  MagiclysmUDP,
  No_Rail_Stations,
  cbm_slots,
  speedydex,
  StatsThroughSkills,
  stats_through_kills,
  No_Fungi

### Additional context

Save file: https://www.dropbox.com/s/gwd16l4fsxnxfk6/Haven.zip?dl=0

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7147312/debug.log)

**Comment by ZhilkinSerg** [comment] 2021-09-11 11:49
Make sure account under which you are running CDDA under has write permissions to CDDA savegame location.

**Comment by jiornojiovanni** [comment] 2021-09-11 12:45
Same issue

**Comment by ProfoundDarkness** [comment] 2021-09-11 12:58
Hmm... I've had something similar happen.  Assumed it had something to do with the recent overmap code refactoring that lead to failure to compile for windows.

I've got a relatively new game where I've only explored a small area, smaller than what that block in the screenshot is.  I've just noticed that newly explored areas are not being kept between sessions.  Permissions are not an issue (unless the game changed them).  Going to start testing under which scenarios this is happening...

**Comment by StStep** [comment] 2021-09-11 13:11
Ooph yeah, this is easy to reproduce. Just make a new evacuee character, note the overmap, save and quit and then load them. If you're near a chunk edge you'll see the discontinuity, otherwise you'll see how your initial map view shrunk.

**Comment by jiornojiovanni** [comment] 2021-09-11 13:15
I tested a bit and I think build **2021-09-10-0418** introduced the bug. Previous one works correctly.

**Comment by StStep** [comment] 2021-09-11 13:55
I'm not yet convinced  **2021-09-10-0418** introduced the bug (JSON only changes?) But it is definitely somewhere in **2021-09-09-0327** to **2021-09-10-141**3. Unfortunately, the launcher can't easily load that range because they are unavailable.

**Comment by ProfoundDarkness** [comment] 2021-09-11 15:08
OK, did a bisect... unless I goofed something up the bisect seems to indicate the problem is from Decouple save file name from Character::name (#51466)
"f0c2c3b123ae44f3b2a6d5d29fc18350be0c4dfd is the first bad commit"

cdc6843e4dd983da45d2aece75ecb0abd3d483a0 doesn't demonstrate the problem, f0c2c3b123ae44f3b2a6d5d29fc18350be0c4dfd does.

Also (possibly aside, possibly related?) loading an older save produces some errors that don't come up after saving.  In debug log.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7148071/debug.log)

**Comment by chance-m** [comment] 2021-09-11 18:09
Update, I tested the most recent build 2021-09-11-1713. Problem still persists.

**Comment by IrukandjiIchyouiyxl** [comment] 2021-09-11 18:49
Same issue

**Comment by morthein** [comment] 2021-09-11 21:58
You know what's funny, my guy has 'forgetful' so i thought it was a cool side effect for spending the whole winter indoors.  I didn't know it was a bug 💩

**Comment by actual-nh** [comment] 2021-09-11 23:44
Ping: @eltank? (I have trouble seeing how that PR would have done that, admittedly.)

**Comment by IrukandjiIchyouiyxl** [comment] 2021-09-12 00:54
Issue still persists in new build 2021-09-11-2357.

**Comment by eltank** [comment] 2021-09-12 01:14
> Ping: @eltank? (I have trouble seeing how that PR would have done that, admittedly.)

Sure, I'll do some debugging today.

**Comment by eltank** [comment] 2021-09-12 02:16
Alright, I found the bug. It will be fixed shortly.

**Comment by eltank** [comment] 2021-09-12 02:33
Sorry about this, I should have caught it when testing #51466.
Thanks to @ProfoundDarkness for running the bisection and helping to narrow down the cause faster.

**Comment by chance-m** [comment] 2021-09-12 02:50
This is my first time posting on here so I really appreciate the insanely fast replies. Especially the fix @eltank and @ProfoundDarkness. So is this something I should close now?

**Comment by eltank** [comment] 2021-09-12 02:52
> So is this something I should close now?

It will be closed automatically when the fix is merged. Thanks for reporting the issue!

**Comment by GordanGeeko** [comment] 2021-09-12 04:23
I have the same issue. I created a different bug report #51548.

**Closed** 2021-09-12 05:33 UTC
Labels: <Bug>, Map / Mapgen, (P1 - Critical), Mechanics: Map Memory

**Comment by kevingranade** [comment] 2021-09-14 00:50
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/overmap-notes-disppear-everday/27033/2
