### ISSUE TITLE
Lockers,benches in start shelter WONT break with rock

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#14390] opened 2015-12-11 17:20 UTC
Hi all details are

cataclysmdda-0.C-4018.zip 64bit
win 7 64bit
tiles yes Chezzo x32

Ok the issue is
I ALWAYS grab a rock and run back into start shelter then bash the lockers for crowbar and lock picks but I have hit all the lockers at least 60 times and nothing nadda :(

Even the benches will NOT break.

The window I hit on the other hand did so not sure whats going on here.

I have rock in hand
Stamina is high (I rest then try again)

etc etc

Deffo some sort of bug here

**Comment by stk2008** [comment] 2015-12-11 17:26
Ok further testing

Created new char and every thing works as it should

I forgot to say the issue I originaly reported was using a template char I always use.
I created a new world using same char template and issue is still not fixed but as soon as I create a new char it all works.

Some thing aint working with my cahr template

**Comment by Coolthulhu** [comment] 2015-12-11 17:26
Duplicate of #14375

**Comment by stk2008** [comment] 2015-12-11 17:42
OK scrub that even with new char it seems to not always work even bashing lockers etc 100 times.

**Closed** 2015-12-11 19:27 UTC
