### ISSUE TITLE
Add ability to lock vehicle doors

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#48902] opened 2021-05-16 21:07 UTC
# Is your feature request related to a problem? Please describe.
Feral humans can open doors and you cant counter it 

# Describe the solution you'd like
Being able to lock vehicle doors

# Additional context
Lock malfintions can also be added so you wont be able to lock and/or unlock door utill you **M**end it.

**Comment by Igryn** [comment] 2021-05-17 10:18
If some vehicles will spawn locked it also would add some gameplay variety. So you should chose to either smah the door glass to get in, ignore it or pick the lock risking to set off alarms

**Comment by Saicchi** [comment] 2021-05-19 23:11
Duplicate of #46160 ?

**Closed** 2021-05-19 23:14 UTC
Labels: (S3 - Duplicate), <Enhancement / Feature>, Quality of Life, Vehicles
