### ISSUE TITLE
3D Vision - Viewing higher Z-levels reveals floors out of sight

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#67528] opened 2023-08-08 15:40 UTC
### Describe the bug

The current 3D vision implementation limits what you can see or tiles revealed based on angle to obsticals. 
This works when viewing from the ground up however will reveal tiles that are hidden from view, when viewing that tile from a floor above. 
In the example I have, the roof of the building is not visible looking from the ground to Zlevel 1, however when viewing from Zlevel 2, any tile visible from your vantage point on the ground will also reveal the lower floor that is out of sight. 

### Attach save file

[Waitsburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12293223/Waitsburg-trimmed.tar.gz)

### Steps to reproduce

Create a character in the Sheltered start
Walk outside, use the look mode using ;
Move up 1 Z level and note you cant see the roof
Move up 2 more Z levels
Move back down 2 Z levels
See part of the roof

### Expected behavior

When showing an open air tile, the tile below should be checked to see if it too is visible from your current position.
If not it should not be revealed.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/79c8a05d-958d-4a98-9a33-4424c0a813b1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 4de6b26 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Pixel's Various Fuckery [Pix's Shit],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by NetSysFire** [comment] 2023-08-08 16:14
Duplicate of #66040.

**Closed by NetSysFire** 2023-08-08 16:14 UTC
Labels: (S1 - Need confirmation)
