### ISSUE TITLE
[BUG][CRASH] MinGW runtime assertion

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#17057] opened 2016-06-05 08:52 UTC
Windows 0.C-14948-gd6f956e (tiles)

Walking through the forest towards a military base.
The text "From the east you hear P-p-p-pow! x 13" had just appeared, followed by a window appearing with the title "MinGW Runtime Assertion" and the following text :

Assertion failed!
Program: E:\download\cdda\cataclysm-tiles.exe
File: src/line.cpp, Line 321

Expression: !line.Empty() && line.front() != line.back()

**Comment by Zireael07** [comment] 2016-06-05 08:55
Dupe of #17043

**Closed** 2016-06-05 17:08 UTC
