### ISSUE TITLE
MRE Matchbook comes with 0 charges

### ISSUE THREAD

**Issue by jkoudys** [CleverRaven/Cataclysm-DDA#41948] opened 2020-07-08 18:49 UTC
# Describe the bug

I unpack my MRE, and the matchbook inside has 0 charges.

# Steps To Reproduce

1. Find an MRE
2. Use it
3. Cry when you didn't get any matches

# Expected behavior

There'd be matches.

# Screenshots

<img width="405" alt="Screen Shot 2020-07-08 at 14 47 50" src="https://user-images.githubusercontent.com/586985/86958338-01ba5f80-c12a-11ea-9d9b-d112bcd00578.png">

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: OSX 10.15
-----------------------------------------
13:05:57.628 : Starting log.
13:05:57.629 INFO : Cataclysm DDA version 0.E-3369-gc738dee8ad
13:05:57.649 INFO : [main] C locale set to en_CA.UTF-8
13:05:57.649 INFO : [main] C++ locale set to 
13:05:57.690 INFO : [options] C locale set to en_CA.UTF-8
13:05:57.690 INFO : [options] C++ locale set to 
13:05:58.349 WARNING : opendir [./mods/] failed with "No such file or directory".
13:06:06.380 WARNING : opendir [./save/Place/mods] failed with "No such file or directory".
13:06:12.024 ERROR : (error message will follow backtrace)
    0   cataclysm                           0x0000000106189480 _Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 57
    1   cataclysm                           0x00000001061889dc _Z8DebugLog10DebugLevel10DebugClass + 626
...

**Comment by Duck13Tales** [comment] 2020-07-09 00:38
I have find over 20 and ALL of them had 0 matches.

**Comment by hexagonrecursion** [comment] 2020-07-09 05:03
duplicate of  #41875

**Closed** 2020-07-09 08:36 UTC
