### ISSUE TITLE
Cursor invisible while aiming/looking and not centring on position

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#22867] opened 2018-02-03 13:04 UTC
Game version:#7099

Operating system: Windows 7 64bit

Mods active:None 

I believe the usual targeting cursor isn't functioning as intended as it is now impossible to get the camera to focus on where the player is aiming/looking along with the usual yellow cursor being invisible.
Making my usual style of aiming extremely difficult 
 
Te replicate simply aim in the latest build and see the results

**Comment by Zireael07** [comment] 2018-02-03 13:10
Duplicate of #22855?

**Comment by TheLyca0n** [comment] 2018-02-03 13:45
Shit sorry

**Closed** 2018-02-03 14:29 UTC
Labels: Duplicate
