### ISSUE TITLE
Translate msgid "battery" bug in all *.po files in 4fa18e9 commit

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#23561] opened 2018-04-21 10:38 UTC
Game version:
4fa18e9 and higher

### Expected behavior
`battery` in russian like `батарея`

### Actual behavior
`battery` shown like `99d8b20cf7042be43c3855ac670d4ec2_pl_0`
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/38557723/39083101-437762ae-4578-11e8-83f9-7e05a40dd8a5.png">
<img width="430" alt="2" src="https://user-images.githubusercontent.com/38557723/39083102-4588696c-4578-11e8-9bed-4459529e0494.png">
<img width="580" alt="3" src="https://user-images.githubusercontent.com/38557723/39083103-46a3e330-4578-11e8-8a82-6f6c3b2dad5e.png">
### Steps to reproduce the behavior
Try to run some no english version of game. In all `*.po` files:
```
#: lang/json/AMMO_from_json.py
msgid "battery"
msgid_plural "batteries"
msgstr[0] "99d8b20cf7042be43c3855ac670d4ec2_pl_0"
msgstr[1] "99d8b20cf7042be43c3855ac670d4ec2_pl_1"
msgstr[2] "99d8b20cf7042be43c3855ac670d4ec2_pl_2"
msgstr[3] "99d8b20cf7042be43c3855ac670d4ec2_pl_3"
```
### Steps to fix
For `ru.po`:
```
#: lang/json/AMMO_from_json.py
msgid "battery"
msgid_plural "batteries"
msgstr[0] "батарея"
msgstr[1] "батареи"
msgstr[2] "батарей"
msgstr[3] "батарея"
```

**Comment by gastamper** [comment] 2018-04-21 10:57
If someone adds translations for other languages I'll include them in the PR but unfortunately only know Russian and Japanese for sure at the moment.

**Comment by Wuzzy2** [comment] 2018-04-21 19:28
I can show to you we can blame Transifex for that one. The faulty string comes from a bad export from Transifex. I have noticed this bug in my daily manual PO export from Transifex. That was *before* the routine Transifex pull done by the repository on April 20.
Editing the PO files by hand will not help you they will just be overwritten in the next routine pull.

For the proof, just go to Transifex and request a PO file to be exported for a language. Then look inside for the “battery” string.

Also note that in Transifex, if you try to edit the battery string, Transifex, for some reason, always edits all plural forms at once. Something seems to be very wrong with Transifex here.

### How to export the PO file from Transifex (because it's not obvious)
1. Go to the Dashboard: https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/dashboard/
2. Select a language (e.g.) German, click “View Resources”
3. Select `master-cataclysm-dda`
4. Click “Download for use”

**Comment by gastamper** [comment] 2018-04-21 22:36
Looks like this probably requires someone with the Reviewer status on Transifex to fix, I sure can't do anything to change the string or otherwise play around to try to troubleshoot why it isn't exporting properly.

**Comment by Wuzzy2** [comment] 2018-04-22 07:02
The affected string is not reviewed so it can be updated by any translator.

**Comment by gastamper** [comment] 2018-04-22 12:39
Yeah I hadn't even tried to change the string since it was correct, just revert previous changes (which didn't work).

You are right that this is a problem with Transifex and not the translation or CDDA source it seems so hopefully you having contacted them will resolve it.

**Comment by Wuzzy2** [comment] 2018-04-25 19:18
I got a reply from Transifex Support on April 23 which I like to quote here:

> Regarding your case, after further looking into this, I found out that
>on 2016-12-16, the following PO entry was created in Transifex:
>
>	msgid "battery" msgstr "battery"
>and on 2018-04-13 23:21:07, this entry was converted to a pluralized
>string as follows:
>
>	msgid "battery" msgid_plural "batteries" msgstr[0] "battery"
>msgstr[1] "batteries" 
>In the old version of our parser (v=1), if a PO entry that was hosted
>in Transifex was a non-pluralized string and in an updated version of
>your source file, you converted this to a pluralized one (the msgid
>remained the same), then the parser was getting confused. As a result:
>-- The plural forms in the translation box area were not available (as
>it is happening in your case). As a result, you could not apply a
>different translation to each form.
>-- While exporting your translation file from Transifex, the hash was
>included in the file instead of the translatable text (e.g.
>99d8b20cf7042be43c3855ac670d4ec2_pl_0)
>
>However, in the new version of our PO parser (v=2), this issue is no
>longer present. **So, in order to fix this, you need to upload this file
>as a new resource to Transifex** so that the content will be parsed by
>the v=2 PO parser.

(emphasis by me)

Can whoever is the manager of the Cataclysm-DDA project on Transifex do as suggested above, please? (I don't know who manages the project).
Please be careful not to destroy existing translations.

**Comment by BrettDong** [comment] 2018-04-26 15:31
In case of inconsistency, translations are temporarily suspended. #23610 will be imported to Transifex after the technical issues are solved.

**Comment by korick** [comment] 2018-04-29 19:35
about this ERROR: in 'ru' translations - in this string `RM13 combat armor` - **delete ru translations**, add translations later
some like this:
````
msgid "RM13 combat armor"
msgid_plural "RM13 combat armors"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""
````
Notify or Alert when solved or find other solution

**Comment by Wuzzy2** [comment] 2018-04-30 09:40
@BrettDong: How's the progress on the Transifex update going?

**Comment by BrettDong** [comment] 2018-04-30 11:50
The issue of 'incomplete plural forms' I commented above was solved, but I'm now getting HTTP 500 error when pushing French, Italian, Spanish and Korean (however other languages are fine). I wrote an email to Transifex, but they haven't replied yet.

**Comment by korick** [comment] 2018-05-01 10:51
in transifex, po-file strange or bad uploading
when translating in transifex i use not-fully manually construct po-file with only string when i translate and success upload on server transifex
try this solution
manually correct structure po-file for different languages (fr, it, sp, kr etc) use some like this Notepad++
[head] - only this section manually correct, with this head (bottom), po-file correctly uploading
[structure string English] - don't touch
[structure string translate] - don't touch

some like this
````
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: lang/json/BIONIC_ITEM_from_json.py
msgid "EMP Projector CBM"
msgid_plural "EMP Projector CBMs"
msgstr[0] "КБМ: ЭМИ излучатель"
msgstr[1] "КБМ: ЭМИ излучатель"
msgstr[2] "КБМ: ЭМИ излучатель"
msgstr[3] "КБМ: ЭМИ излучатель"
````

**Comment by Wuzzy2** [comment] 2018-05-09 21:54
@BrettDong: Still no reply from the Transifex people? Because the resources are still locked.

@korick: FYI: It's HTTP error 500 … That means the bug is on the server-side, i.e. Transifex.

**Comment by BrettDong** [comment] 2018-05-10 11:25
Their tech support said that they were able to reproduce the behavior and
they were investigating the issue.

**Comment by BrettDong** [comment] 2018-05-27 13:59
@Wuzzy2 is this issue addressed in the latest master branch?

**Comment by Wuzzy2** [comment] 2018-05-27 15:55
Yes.
However, you have destroyed the “Reviewed” status of all strings in Transifex. xD (but this is a different issue).

This issue can now be closed.

**Closed** 2018-05-27 16:01 UTC
Labels: Translation

**Comment by BrettDong** [comment] 2018-05-29 13:51
Hadn't I migrated the resource, the review status would also be lost when implementing #23434 .

**Comment by Wuzzy2** [comment] 2018-05-29 14:05
Yeah, that's true. Meh, maybe this is a neccessary evil.
