### ISSUE TITLE
Insect Wings mutation permanently active without associated cost

### ISSUE THREAD

**Issue by Lloydles** [CleverRaven/Cataclysm-DDA#51359] opened 2021-09-04 12:34 UTC
### Describe the bug

Ever since my character mutated Insect Wings, my movement cost has been significantly lower without incurring the active cost of the mutation. Turning the mutation on through the mutation menu activates the drain, but does not make my character faster. Turning it back off again does not remove the movement cost reduction, meaning it is effectively permanently active without costing anything.

My regular movement cost on the character in question is 105 with Insect Wings (on **or** off), and when I remove the mutation through debug, it shoots up to 141.

### Steps To Reproduce

1. Make any player character
2. Make a move and write down the cost (107 orthogonal on a default start)
3. Mutate Insect Wings through any means
4. Make a move, the cost should be significantly lower (80 orthogonal on a default start with debugged Insect Wings)

5. Activate Insect Wings through the mutation menu. Moving will now drain resources, but the movement cost remains the same as in 4 (80 orthogonal).
6. Deactivate Insect Wings through the mutation menu. Moving will now no longer drain resources, but the movement cost still remains the same as in 4 (80 orthogonal).

### Expected behavior

I expect that the Insect Wings mutation would only reduce my movement cost while activated and draining resources.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b67e505 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Manual Bionic Installation [manualbionicinstall]
]

**Comment by hexagonrecursion** [comment] 2022-01-04 09:23
Confirmed

1. I have created a char with 100 base move cost.
2. I mutated insect wings. This caused the base move cost to drop to 75.
3. Activating the wings caused rapid thirst and an increase in wearines, but the base move cost remained at 75

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment] 2022-02-26 03:09
Looks like this is a dupe of #42596. The other thread posits this issue applies to all movement-related mutations.

**Comment by Night-Pryanik** [comment] 2022-02-26 03:49
Yeah, closing as duplicate.

**Closed by Night-Pryanik** 2022-02-26 03:49 UTC
Labels: <Bug>, (S2 - Confirmed), Mutations / Traits / Professions/ Hobbies, <Exploit>
