### ISSUE TITLE
Move lit items such as cigars and joints from the inventory to a free hand when lit. 

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#51788] opened 2021-09-22 03:15 UTC
# Is your feature request related to a problem? 

Smokable items remain in the pocket when lit and will ignite the container and contents if the container with the smouldering item inside is dropped.

Additionally, it is unrealistic to expect a survivor to smoke a cigarette when it is still inside a pocket.

# Describe the solution you'd like

Moving the lit item (cigars, cigarettes, joints and refillable lighters) from the pocket to a free hand would avoid the problem of packs igniting when dropped, and would add additional realism to the game.

Not having a free hand could either prevent lighting any items or add hand encumbrance.

# Describe alternatives you've considered
It can be left as is and players can blacklist smokables and refillable lighters so they aren't stored inside packs.

# Additional context
NA

**Comment by Entity-y** [comment] 2021-09-22 05:04
Free hand or transferred to the mouth

**Comment by sharkfinsouperman** [comment] 2021-09-22 07:52
The issue is partially addressed by #51635, but it it doesn't solve the issue of lit-up refillable lighters, so I'll leave this open until one of the higher-ups decides to close it.

**Comment by Zireael07** [comment] 2022-04-28 07:24
dupe of #50936

**Closed** 2022-10-17 07:07 UTC
Labels: <Enhancement / Feature>, Items / Item Actions / Item Qualities
