### ISSUE TITLE
Frozen water/liquid in a bottle/other can't be put in inventory without spilling water/liquid on a floor

### ISSUE THREAD

**Issue by tatikman** [CleverRaven/Cataclysm-DDA#44873] opened 2020-10-15 12:35 UTC
# Describe the bug

Frozen water/liquid in a bottle/other can't be put in inventory without spilling water/liquid on a floor
First I start think this cause I install some mods.
I start new game without any special mods.
I wait until water in a bottle will freeze, after this I try to put bottle with frozen water in my inventory, but all liquid/water spill on a floor, and I get just empty bottle.
With warm and unfreezeable liquid all works just fine and don't spill on a floor during putting in my inventory.

# Steps To Reproduce

1. Freeze a water/liquid in a bottle/other.
2. Try to put it in your inventory.
3. Great job, you spill all water/liquid on a floor.

# Expected behavior

Bottle/other with frozen water/liquid must put in inventory without spilling on a floor.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-6823-g214e756
 - Graphics version: DEADPEOPLE
 - Ingame language: Russian
 - Mods loaded: DDA, no_npc_food, package_bionic_professions

Odmen ples fix dis.

**Comment by EirenexTheDragon** [comment] 2020-10-15 17:37
duplicate of #44792

**Comment by tatikman** [comment] 2020-10-15 18:17
> duplicate of #44792

Yes, didn't notice.

**Comment by wapcaplet** [comment] 2020-10-17 01:05
Thanks for reporting. Even duplicate reports are appreciated since they add info. With so many issues open, it can be hard to find existing ones.

**Closed by wapcaplet** 2020-10-17 01:05 UTC
Labels: (S3 - Duplicate)
