### ISSUE TITLE
High speed view shift won't go back to normal

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#13993] opened 2015-11-12 18:13 UTC
I have an option to shift view automatically when driving enabled. It works okay when I speed up and slow down gradually. But when I ride fast for awhile (144 kph, for example) and then stop as fast as I can and dismount (to kill something) my view won't go back to normal automatically. So I walk around with my view point shifted by half a screen. Using a vehicle again doesn't seem to fix it, only reloading a save does.

**Comment by chaosvolt** [comment] 2015-11-12 23:18
I've had it occur a few times before, not sure of the cause.

However, have you tried hitting the view reset key, ":" (colon) by default?

**Comment by Nandorianen** [comment] 2015-11-13 04:38
Yeah, that works. But it's still a bug, however minor.

**Comment by BevapDin** [comment] 2015-11-13 13:46
I fail to reproduce this. It takes only a few turns (about 3) to get back to the center. Are you using the curses or the tiles version? What is the actual dimensions of your display (console rows and columns)?

**Comment by Nandorianen** [comment] 2015-11-13 14:21
I am playing win-tiles version with no graphics. My dimensions are 159 by 56.
I get this reliably if I go to 150+ speed, wait for the game to shift view all the way it wants to shift it, then dropping speed to 0. Vehicle stops in 3-4 turns, but view needs about 10 more turns without me releasing controls to get centered again.

**Comment by chaosvolt** [comment] 2015-11-13 14:55
Ah right. In most cases it should correct itself in a few turns, if not immediately. :V

So long as it doesn't stay that way when you start walking, it's more of an inconsistency than anything else.

**Comment by Nandorianen** [comment] 2015-11-13 15:05
As I said in OP, it does stay this way if I dismount before it goes back to normal. And then you walk around with your view shifted half a screen to the side. Manually pressing "center view" or reloading the save fixes it. Starting to drive again doesn't.

**Comment by chaosvolt** [comment] 2015-11-13 15:06
And that specific part would be the part that's a full-on bug, rather than inconsistent. ;w;

**Comment by Oskar636** [comment] 2016-11-10 18:25
Cannot reproduce in build 5864 windows 64bit tiles.

**Comment by BrettDong** [comment] 2016-11-19 08:50
Can confirm. macOS 10.12.1, ncurses.
![2016-11-19 4 41 41](https://cloud.githubusercontent.com/assets/21075502/20454301/95385e0c-ae77-11e6-8894-0c9f8f23a605.png)
I built a sports car which could run at very high speed. I was backing my car at about 200 kph, and I stopped, then though I pressed _._ to wait for a few turns, the view didn't go center.

**Comment by BrettDong** [comment] 2016-11-19 08:52
But this isn't 100% reproducible. I tried a number of times, the issue happened only once.

**Comment by mugling** [comment] 2016-12-04 18:17
This definitely still exists in `master`

**Comment by Night-Pryanik** [comment] 2019-09-27 15:11
Cannot confirm on latest experimental as of September 27, 2019.

**Comment by Night-Pryanik** [comment] 2020-02-03 09:11
Closing until reconfirmed.

**Closed by Night-Pryanik** 2020-02-03 09:11 UTC
Labels: (S1 - Need confirmation), <Bug>, Info / User Interface, Vehicles
