### ISSUE TITLE
Debug messages about harvest_list

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#21196] opened 2017-06-07 11:39 UTC
Build 6504. windows.
Debug message when look around and view extended description.
![dbg_harvest](https://user-images.githubusercontent.com/1931904/26876416-ba6c63d0-4b8e-11e7-8faf-132143529acc.png)
* In curses - **invisible** messages, and black screen.

To reproduce:

- load or create world
- press 'x' - look around
- [shift with arrow keys]
- press 'e' - view extended description
- [press 't' - describe terrain if there is a creature description displayed]

**Comment by Leland** [comment] 2017-06-07 18:09
Similar to, but not a duplicate of, https://github.com/CleverRaven/Cataclysm-DDA/issues/19472

**Comment by Coolthulhu** [comment] 2017-06-07 20:01
Any mods that add critters and/or harvest drops?

**Comment by AMurkin** [comment] 2017-06-07 23:24
No, "dda" only.

**Comment by AMurkin** [comment] 2017-06-08 19:49
Message displayed 4 times when evaluating lambda in [src/descriptions.cpp:125](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/descriptions.cpp#L125)

**Closed** 2017-07-06 15:44 UTC
Labels: Bug, Confirmation Needed, Information / Interface
