### ISSUE TITLE
Trading inhaler for NPC having Asthma attack breaks NPC.

### ISSUE THREAD

**Issue by DarkendTheMighty** [CleverRaven/Cataclysm-DDA#40738] opened 2020-05-21 21:29 UTC
Giving an NPC having an Asthma attack an inhaler (I can't tell them to directly use it so I have to trade it) causes them to go into stasis.

# Steps To Reproduce

I put them out of stasis, waited for their Asthma attack to finish, then used the debug menu to cause them to have another asthma attack and gave them an inhaler. Same message.
![Inhale](https://user-images.githubusercontent.com/45152594/82607861-a1765b00-9b87-11ea-82cc-a645ea521ee7.png)

# Expected behavior

NPC would use inhaler normally, ending the Asthma attack.

# Screenshots

![Inhale](https://user-images.githubusercontent.com/45152594/82607936-c2d74700-9b87-11ea-9812-ad702ce07a88.png)

Debug info dumped into in-game log, not sure how to turn if off...
![QorcYte](https://user-images.githubusercontent.com/45152594/82607964-d4b8ea00-9b87-11ea-9639-88ea312cc348.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-2203-g30952d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Nechronica Redux [Nechronica_Redux],
    Mutant NPCs B10492 [mutant_npcs_10492],
    Psychiclysm [psychiclysm],
    Whaleys Collectables [collectablemod],
    Graphical Overmap [Graphical_Overmap],
    MSX Hide DEBUG [UDP_No_Debug_Tile],
    PKs Rebalancing [PK_REBALANCE],
    Vehicle Additions Pack [blazemod],
    Faster Stamina Regen [stamina_regen_buff],
    Larger Stamina Pool [stamina_pool_buff],
    Shrub it off [shrub_mod],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Whaleys Hair Mod [WHALEYHAIR1],
    Toki's silly classes [toki_sillyclasses],
    THRESHOLD [add_mutant],
    Makeshift Items Mod [makeshift],
    Mythical Martial Arts [MMA],
    NPC Recruitment Options [recruitment_options],
    Jury-Rigged Robots [jury_rigged_robots],
    Hair aka Rainbow [Hairs],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots_10511],
    PRM++ Patch [noctpk],
    Stats Through Kills [stats_through_kills],
    Tiered Evolution [Tiered_Evolution],
    Vehicle Additions Additions [blaze_extension_M],
    M.A.G. Armory Mod [M.A.G.Armory],
    Engineering essentials [EngineeringEssentials],
    Malkeus' Preferences [Malkeus_Enhancement_Mod],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Tankmod: Revived [Tankmod_Revived]

# Additional context

**Comment by Fris0uman** [comment] 2020-05-21 21:50
can this be reproduced without that many mods?

**Comment by DarkendTheMighty** [comment] 2020-05-21 21:51
> 
> 
> can this be reproduced without that many mods?

Let me check.

**Comment by anothersimulacrum** [comment] 2020-05-21 21:52
Yes, I just did it. I got an `NPC tried to self but has no healing item debugmsg`, then the NPC went into stasis.

**Comment by DarkendTheMighty** [comment] 2020-05-21 21:55
Yep, same here.  DEBUG    : Towanda 'Crescendo' Lindquist tried to heal self but has no healing item

 FUNCTION : void npc::heal_self()
 FILE     : src/npcmove.cpp
 LINE     : 3640

**Comment by DarkendTheMighty** [comment] 2020-05-21 21:57
Also worth noting that random items would spawn on me whenever I got hungry or thirsty. The game randomly told me if I wanted to eat a mushroom soup that I didn't have when I got hungry...I'll make another issue for that later.

**Comment by Insineer** [comment] 2021-01-06 04:36
I can't reproduce this now. Seems like this issue was fixed with #42157

> Trade a loaded inhaler to the NPC then give them an asthma attack. Wait 5 minutes and confirm that they used the inhaler. Repeat with an emergency oxygen bottle

**Closed** 2021-01-30 18:43 UTC
Labels: <Bug>, NPC / Factions
