### ISSUE TITLE
Chickens can only be released from container at z-level it was caught in

### ISSUE THREAD

**Issue by LynLynLang** [CleverRaven/Cataclysm-DDA#35457] opened 2019-11-10 19:59 UTC
# Describe the bug

1. Chickens can only be released from container at z-level it was caught in
2. any container(pet carrier, chicken cage) holding chicken has a weight of 0

# Steps To Reproduce

1. Catch a chicken at a rooftop with any container
2. Go down to ground level
3. Try and release the chicken

# Expected behavior

Chicken will be released from container regardless of z-level

# Screenshots

N/A

"Additional context" -->

# Versions and configuration

 - OS: win10
 - Game Version: 9886
 - Graphics version: Tiles
 - Mods loaded: STK, Magiclysm

# Additional context

N/A

**Comment by xsyntryk** [comment] 2019-11-13 21:57
I'm having this happen as well.

**Comment by new02DAY** [comment] 2019-11-23 00:55
I want to add that this also happens with lambs (and posssibly/probably anything caught in pet carriers) as recently as 0.D-9539-g4b261b5.

**Comment by Fris0uman** [comment] 2020-01-13 19:20
For some reason ` g.critter_at<Character>( p )` line 4615 in game.cpp returns true whe ntrying to release the animal on another z-level thant the one it was captured on which makes the relese fail.

**Comment by wapcaplet** [comment] 2020-01-15 21:33
I have the same behavior with my pet cat. I captured the cat in a pet carrier at ground level.

When I try to release the cat, success varies by Z-level:

- Ground level, outdoors or inside any building or vehicle: OK, cat released
- Evac shelter roof, Evac shelter basement, or LMOE basement: "You cannot place the cat there!"

Furthermore:

- Release friendly cat at ground level in evac shelter
- Go to basement and wait for cat to follow
- Capture cat in pet carrier
- Go back upstairs
- Try to release the cat: "You cannot place the cat there!"

**Comment by BevapDin** [comment] 2020-01-16 06:48
AFAIK  this is caused by the check for `mon.can_move_to( p )` in `can_place_monster`, called from `game::place_monster_at`. That check should prevent creatures from spawning in impossible places (like solid walls, air, dangerous terrain, ...).

However, it also checks whether moving from the current position of the monster to the desired point is possible. But it only checks the z-component for that, so placing it at the same z-level is possible, but placing it on another z-level is not possible as the monster can not fly / there is a roof that prevents flying.

**Comment by davidpwbrown** [comment] 2020-01-16 15:55
So the monsters position is stored when its captured. This means as bevapdin says, it fails the check for moving to another z-level.

Can't set the monsters position to the current z-level before its released, because the critter tracker complains that its not on the map.

So without restructuring can_move_to() or changing the checks to use something similar and duplicate code, all I can think of is passing a parameter down the chain for `bool ignore_z` or `bool is_release_check` to ignore the z-level difference check, is that a suitable fix?

**Closed** 2020-01-16 18:59 UTC
Labels: <Bug>, Monsters, Z-levels
