### ISSUE TITLE
Trying to craft sock mittens from a pair of filthy socks and got an error 

### ISSUE THREAD

**Issue by RegalDreamer** [CleverRaven/Cataclysm-DDA#51014] opened 2021-08-23 06:05 UTC
### Describe the bug

 DEBUG    : Attempted a recipe with no available components!

 FUNCTION : comp_selection<item_comp> Character::select_item_component(const std::vector<item_comp>&, int, read_only_visitable&, bool, const std::function<bool(const item&)>&, bool)
 FILE     : src/crafting.cpp
 LINE     : 1617
 VERSION  : 0.F-1

### Steps To Reproduce

Not sure how to reproduce, but as far as I can remember:
1. Kill zombie
1.1 (I had saved and quit after this, loading the game later)
2. Take their filthy socks
3. Try to make sock mittens

### Expected behavior

Sock mittens should get crafted, but actually an error popped up saying there are no ingredients. 
The in progress mittens have fallen on the floor.

### Versions and configuration

- OS: Windows 
    - OS Version: 10.0 2009
- Game Version: 0.F-1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by RandDenner** [comment] 2021-08-23 06:58
Just tested on Windows10 tiles experimental 8051d7d.
Could not replicate the error in that version, but I found some other oddities:

1) recipe will **not** accept socks labelled (poor fit) as valid components. That's weird. How they fit on your feet shouldn't matter.

2) recipe converts filthy socks into clean sock mitts somehow.

Will test more and on 0.F-1 tomorrow if nobody else does first.

**Comment by WashingMachinae** [comment] 2021-08-23 07:17
Yeah it only happened once to me, haven't tried to reproduce it, just started playing the game anyhow.

**Comment by hexagonrecursion** [comment] 2021-08-23 18:25
> 1. recipe will **not** accept socks labelled (poor fit) as valid components. That's weird. How they fit on your feet shouldn't matter.
> 
> 2. recipe converts filthy socks into clean sock mitts somehow.

Does not match my observations.

1. I was able to craft a pair of sock mitts out of a pair of socks (poor fit)
2. The required components were red until I washed the socks.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 8051d7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment] 2021-08-23 18:37
Could not reproduce the debug assertion above in 0.F-1
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by RandDenner** [comment] 2021-08-23 18:52
@hexagonrecursion yeah, I forgot about the six square crafting radius, so I got confused with the sock mitts.
It works like I would expect.
Doesn't work with filthy clothing, doesn't care about poor fit.

**Comment by hexagonrecursion** [comment] 2022-01-11 05:43
> @hexagonrecursion yeah, I forgot about the six square crafting radius, so I got confused with the sock mitts. It works like I would expect. Doesn't work with filthy clothing, doesn't care about poor fit. Although there is still some weirdness:
> 
>     1. created sock mitts are fully repaired, even if components were nearly destroyed
> 
>     2. poor fit quality remains if the original component had it.
>        Again, who cares about the fit on your feet if you're making sock mitts?
> 
>     3. wool socks cannot be used. Seems like an oversight.

All of those are separate from the original issue. I have split them into dedicated threads to help track the progress of fixing the issues. IMHO this thread can now be closed.

**Comment by wapcaplet** [comment] 2022-01-17 03:37
Thanks again for splitting this up for easier tracking. Closing now.

**Closed by wapcaplet** 2022-01-17 03:37 UTC
Labels: (S1 - Need confirmation)
