### ISSUE TITLE
I cannot end my game and I got soflock.

### ISSUE THREAD

**Issue by BoruMaboru** [CleverRaven/Cataclysm-DDA#77678] opened 2024-11-08 16:50 UTC
### Describe the bug

Suddenly I cannot end my game after I died, cannot write my last words and also cannot quit normally either. It had to be force close then reset manually through world.

### Attach save file

N/A

### Steps to reproduce

start game and die.

### Expected behavior

let me quit

### Screenshots

![cannot end](https://github.com/user-attachments/assets/5df5c765-cd1b-4e38-ab53-11ae9e564f08)

### Versions and configuration

cdda-windows-tiles-x64-msvc-2024-11-03-2221

**Comment by RenechCDDA** [comment] 2024-11-08 16:52
Duplicate of #77636

**Closed by RenechCDDA** 2024-11-08 16:52 UTC
Labels: (S1 - Need confirmation)
