### ISSUE TITLE
Gluten free bread becomes gluten containing sandwich

### ISSUE THREAD

**Issue by Anandar83** [CleverRaven/Cataclysm-DDA#44386] opened 2020-09-24 13:10 UTC
# Describe the bug

Using cornbread and lunchmeat together created meat sandwich with gluten tag but both are non gluten items

# Steps To Reproduce

1. Create character with gluten intolerance
2. Spawn in 2x meat (i used lunch meat) and 2x cornbread, enter the crafting menu and craft meat sandwich.
3. Eat sandwich get notified about allergy

# Expected behavior

Using corn bread i was expecting the sandwich not to have gluten as cornbread is not tagged with gluten before the sandwich was made

# Screenshots

# Versions and configuration

Originally found in 0.e windows x64 tiles b10946
All items used for crafting were found in the gane world a number of mainlined mods used undeadpeople tileset in use
Retested in 0.e windows x64 tiles 11032
Items were spawned in via debug no mods and ultica tileset used with same result

# Additional context

**Comment by wapcaplet** [comment] 2020-09-25 22:07
Duplicate of #21872

**Closed** 2020-09-25 22:08 UTC
Labels: (S3 - Duplicate), <Bug>, Items: Food / Vitamins
