### ISSUE TITLE
Cannot fill tanks in vehicles

### ISSUE THREAD

**Issue by Cratelord** [CleverRaven/Cataclysm-DDA#41469] opened 2020-06-20 08:28 UTC
# Describe the bug
When attempting to 'f'ill a tank in a vehicle, the only option is to fill batteries. If no batteries are present, then you cannot fill at all.

# Steps To Reproduce
1. Find any vehicle with a tank or tanks.
2. Attempt to fill.

# Expected behavior
Expected to be able to fill tank with gasoline, but cannot refuel cars at all, unless they are powered by electricity. 

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Caches [P_Caches],
    Mythical Martial Arts [MMA],
    Mining Mod [Mining_Mod],
    Crazy Cataclysm [crazy_cataclysm],
    Cataclysm++ [Cata++],
    No Freeze [no_freeze],
    Bootleg Walkers [Bootleg_Walkers],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Song of Shinigami [shinigamimod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by GGgatherer** [comment] 2020-06-20 12:59
Yep, happening to me too on 0.E-3373-gcf80ae0 (b10775). 
Also, option to refill the vehicle doesn't appear in menu if you try siphoning appropriate fuel from nearby vehicle.

**Comment by fluffysnowcap** [comment] 2020-06-20 18:23
I can confirm that the bug was introduced in build (10768) as 10767 is the most recent build without the filling bug.

**Comment by Pulsares** [comment] 2020-06-21 16:32
Same problem

**Comment by heebejeebes** [comment] 2020-06-21 19:34
Any workaround for this currently?

**Comment by Pulsares** [comment] 2020-06-21 21:54
> Any workaround for this currently?

The liquid (water / gasoline / diesel) cannot be poured into the tank at all; it is impossible to isolate them (tanks). On electricity only travel.

**Comment by hexob** [comment] 2020-06-21 23:40
i just finished my best death mobile yet and now i cannot even use it because of this bug

i am sad :(

**Comment by RafeHaab** [comment] 2020-06-21 23:43
Dudes, fix this issue already; the game is unplayable as it is right now.

**Comment by bloodraven983** [comment] 2020-06-22 11:39
> Dudes, fix this issue already; the game is unplayable as it is right now.

not unplayable, it's just a forced wayfarer or you can drive as long as you have juice in the car

or you can use bikes or rollerblades

**Comment by PlatoSoft** [comment] 2020-06-22 12:30
If I've understood it correctly, this PR should fix this: #41391 but it hasn't been merged yet

**Comment by PlatoSoft** [comment] 2020-06-22 12:30
If I've understood it correctly, this pr should fix it: #41439 but it hasn't been merged yet

**Comment by heebejeebes** [comment] 2020-06-22 14:32
> > Dudes, fix this issue already; the game is unplayable as it is right now.
> 
> not unplayable, it's just a forced wayfarer or you can drive as long as you have juice in the car
> 
> or you can use bikes or rollerblades

You can revert back to version 10767 without too much issue from what small amount of testing I have done. If you really need a gas-powered vehicle that may be the only recourse until this is fixed.

**Comment by heebejeebes** [comment] 2020-06-23 17:05
This issue appears fixed in latest build

**Comment by zebbs** [comment] 2020-06-23 17:40
> This issue appears fixed in latest build(10781)

The latest on the website is 10777.

**Comment by zebbs** [comment] 2020-06-23 17:41
So, testing in 10777 since that's the latest that's available, I have found another problem that only arises when you load both Aftershock and Blaze Industries at the same time.

Vanilla: can siphon, cannot fill
Blaze: can siphon, cannot fill
Aftershock: can siphon, cannot fill
Aftershock + Blaze: **cannot siphon**. cannot fill.

**Comment by anothersimulacrum** [comment] 2020-06-23 17:42
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b10781
Closing as resolved.

**Closed by anothersimulacrum** 2020-06-23 17:42 UTC
Labels: <Bug>, Vehicles
