### ISSUE TITLE
Remove (or significantly tone down) the "dead soldiers" spawn

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53245] opened 2021-12-06 16:54 UTC
### Is your feature request related to a problem? Please describe.

We all know and love that special spawn with a handful of guns and soldier zombies, but the more I play, the less I love it. The fundamental problem is just that this spawn makes it way too easy to get weapons that are way too powerful, way too early, way too often, but here is a more granular list of issues:

- It's nominally guarded by a gaggle of somewhat threatening zombie soldiers, but it's trivial to lure them away, and most of the time you don't even need to because they spawn with a kreck or gracken or something that they end up chasing everywhere.
- It's way too common. If you do any amount of exploring, you'll find one on day one.
- Finding one allows you to skip immediately to the midgame, invalidating any early-game activities like crafting improvised weapons.
- Similarly, it's by far the easiest way to get a gun, and the guns you get are really strong, meaning you rarely have to even think about alternatives like raiding gun stores.
- They give way too much ammo, especially in combination with how common they are. It's easy to find two or three and end up with several hundred rounds of ammo, enough to assault just about anything.
- It exacerbates the issue of turrets dropping huge amounts of ammo. The turret drops wouldn't be such a problem if it wasn't also trivial to find a gun that can use the ammo, and conversely, the gun drops wouldn't be such a problem if it wasn't also trivial to find lots of ammo for them.
- Finding military hardware should be a treat. The fact that between the guns and the zombies it's not unusual to be fully kitted out with an assault rifle, ballitic vest, helmet, combat knife, grenades and several hundred rounds of 5.56 in the first few days devalues not just the spawns themselves, but also stuff that's supposed to be a bigger reward, like military bases and bunkers.

### Solution you would like.

Delete them from the game. I would be quite happy if the only way to get access to grenades and assault rifles was to raid military installations or get lucky with the occasional random zombie soldier.

But at least crank the odds on them spawning way the hell down to make finding a pile of assault rifles as exciting as it should be. It's so consistent that most of the time you can't help but stumble on them, and if you actually go looking it's super easy to find several.

### Additional context

I understand this is probably a controversial suggestion, so I would like to open the floor to debate. Do you like this spawn? What do you think it adds? I personally struggle to see any upsides that outweigh the fact that it essentially means there's no reason to ever both with like 80% of the weapons in the game.

**Comment by Inglonias** [comment] 2021-12-06 18:13
I have been starting a number of new games recently, and yes, this is definitely trivializing early game starts in my experience. They provide absolutely everything you need in the early game, all in one place. Simply lure the soldiers away, or wait for the creature that spawns near them to do it for you, grab one of their guns, and kill the soldiers with it. You now have:

- Armor
- Ammo
- Magazines
- Grenades
- Food and water
- Very good melee weapons in the form of combat knives, and lots of them.
- Guns. So many guns that when one breaks, (which happens almost never), you just toss it and go to the next one. Not only that, but you can also find sniper rifles that make taking down those auto-turrets trivial.

I would be all for reducing the spawn rate of these map extras, and bumping up the other clusters of dead humans to compensate.

**Comment by Inglonias** [comment] 2021-12-06 18:44
I ran the numbers on this to determine overall chance of finding this map extra:

| Terrain Type | Chance for any extra | Chance that extra is military |Final probability|
|-|-|-|-|
|Forest|5%|0.33%|0.17%|
|Forest_Thick| 5% | 0.27%|0.14%|
|Forest_Water| 5% |2.57%|0.13%|
|Field|16.6%|0.19%|0.32%|
|Road|1.33%| 3.8%|0.05%|
|Building|1.1%|1.81%|0.02%|
|Subway|1.33%|15.63%|0.21%|
|Lab subway|4%|19.23%|0.77%|
|Research facility parking lot|33.3%|10.4%|3.46%|
|Research facility interior|50%|0.83%|0.415%|

An overmap has 180 * 180 tiles on it: 32400 tiles. I'll be super basic and say that half of that overmap is going to be fields and forests. The average chance of finding a squad in any of those is 0.19%.

Given these numbers, **you can expect the average overmap region to contain roughly thirty squads of soldiers**, with fresh guns ready for you to take them. And that's just in the fields and forests. If a quarter of that overmap is fields and forests, cut that number in half - 15 squads.

Someone feel free to check my math, but I can believe that number given what I see in-game.

**Comment by Terrorforge** [comment] 2021-12-06 18:59
I guess it's technically a separate issue, but the combat knife really is the icing on the cake for me, because it is literally just unreasonably good. It is (with some allowance for preference and character build) _the_ best knife in the game. Why on earth does this short utility knife/bayonet deal more damage than dedicated fighting weapons like the baselard?

But more relevantly to this discussion, it's another example of this particular map extra just dumping a best-in-class piece of gear in your lap practically for free.

**Comment by Inglonias** [comment] 2021-12-06 19:01
[extracalc.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/7662921/extracalc.xlsx)
Here's a calculator excel sheet for determining numbers. Use the numbers in regional_map_settings.json for any given terrain type, and use best judgement for the fraction of the overmap you think the terrain takes up.

**Comment by estebandellasilva** [comment] 2021-12-06 19:21
While i agree the spawn rate should be lowered - Would the opinion change if the guns were damaged like near breaking or if the guns werent dropped? so that you acutally had to kill the zombies?

**Comment by Inglonias** [comment] 2021-12-06 19:24
The guns being damaged would solve the early game problem of "free gun", and also prevent a player from just trivializing the whole encounter by using them. It doesn't solve the ammo problem, though. Still, it would be a good start.

**Comment by Alex-Folts** [comment] 2021-12-06 19:29
In US, where you can find gun under every rock, having available guns should not be an issue, maybe not assault riffles and machineguns, but some civilian guns should roll in cars/houses/farms, and ammo for them nearby.


> * They give way too much ammo, especially in combination with how common they are. It's easy to find two or three and end up with several hundred rounds of ammo, enough to assault just about anything.

Still there is more threats out there than ammo, i found 1 farm around which: slime pit, bee hive, pile with zombies, mount of dirt and wasps nest. And more you wandering searching for soldiers, more you generating all kind of nastiness.

You can't enforce everyone to play through craft and primitive weapons(not mention that craft system, due to proficiency, greatly slowed down this days), its just one of ways you can play, another way is find vehicle in first day and solve all your problems ramming them with vehicle, ramming zombies, migos, graken, turrets, breaking walls/fences/closed doors - again cheating? Finding gun and shoot things is a one of ways, and those soldiers is the only reliable source of weapon atm.

Make more sources of civilian guns, and reduce spawn of soldiers should be more sensible way of solving this. "I found hunting rifle and handful of bullets on farm" - more probable story, than: "I created from almost scratch workshop and crafted flintlock rifle", both realistic, but first one is more probable in our setting.

**Comment by Inglonias** [comment] 2021-12-06 19:45
> You can't enforce everyone to play through craft and primitive weapons(not mention that craft system, due to proficiency, greatly slowed down this days), its just one of ways you can play, another way is find vehicle in first day and solve all your problems ramming them with vehicle, ramming zombies, migos, graken, turrets, breaking walls/fences/closed doors - again cheating? Finding gun and shoot things is a one of ways, and those soldiers is the only reliable source of weapon atm.

Have you been to a gun store in game recently? Assuming it hasn't been looted, lockpicking is all you need to get a huge amount of ammo and guns. The problem is not that guns are easy to get. The problem is that you can easily find military-grade hardware literally lying on the ground on day 1, with very little effort.

**Comment by Alex-Folts** [comment] 2021-12-06 22:59
> Have you been to a gun store in game recently? 

Prefer avoiding cities and towns because of zombie crowds there.

On second thought maybe you right, reduce chance of spawn at least in clear field would make sense considering how easy traverse fields.

**Comment by LeahLuong** [comment] 2021-12-07 01:43
YouTuber Vormithrax has mentioned that future implementations of the game will have a significantly reduced military presence. I believe he gleaned this info from following dev discussions on the future direction of the game. This should help w/ addressing this thread's topic as well as char progression issues w/ regards to the crafting system & general item balance.

**Comment by Inglonias** [comment] 2021-12-07 01:47
That's not really how this works. In the case of Cataclysm, we **are** the developers. It doesn't happen until someone merges the change.

**Comment by estebandellasilva** [comment] 2021-12-07 06:48
What i dont exactly understand is why on a bodysite the guns are the only thing laying on the ground - if the soldiers where dead all of their items should be on the ground as this is normal behaviour currently. if not then the soldiers shouldnt have dropped their guns

**Comment by Photoloss** [comment] 2021-12-07 07:27
Disagree with removing it, agree with damaging the items. Substantial and chaotic military deployment was part of the prelude to the Cataclysm.

But let's look at how this situation would *actually* play out: if the soldiers encountered a larger number of hostiles they will have dumped pretty much all their ammo into them, *especially* AoE weapons like grenades or full auto. Once overwhelmed their gear would have been torn to shreds, the guns left lying in the blood-soaked dirt. I don't fully understand why every *other* zombie drops greatly damaged filthy gear without exception but this scenario definitely calls for the gear being in such a bad condition. There is no particular reason for the nether mobs to stick around such a site without *doing* anything with it e.g. devouring corpses or taking trophies, especially since the gracken don't care to investigate any other locations.

The other possibility is that the soldiers were ambushed and cut down without much of a fight. That might leave a decent amount of ammo, even some grenades or the like, but it also implies that whatever killed them understands ambush hunting and worse, *might still be there waiting for the next victim.*

Of course in a few rare cases we'd get the current spawn, a group of soldiers suddenly getting killed by portal distortions or the like with a curious gracken standing there to investigate. But considering what "the other side" of those portals is supposed to be like most of the time this is not the most likely outcome by far.

**Comment by PatrikLundell** [comment] 2021-12-07 10:42
I certainly agree these groups would be spiced up a little by not having the guns (etc.) dropped on the ground, but being part of the items dropped when they are defeated. I assume that would require them to form a new group of critters that have different drop tables than others. Also, it differs from other group you encounter which also have their items dropped on the ground (drug addicts, scientists, etc.), which might result in a consistency issue.

In general, I'd prefer zombies to continue to wear their items when they revive so you actually have to pick them off their corpses, but that would change the loot drop system and require zombies to actually have inventories (and wear actual armor items, resulting in a need to re-balance things). However, it wouldn't be unreasonable for held items to be dropped as there's no reason for a revived zombie to grab what the former human held, which makes it a bit problematic, but I wouldn't cry if the zombies continued to grab whatever the humans carried (resulting in zombies using guns and and filled grocery bags as "clubs" (which might render them almost completely ineffective at times).

**Comment by Zireael07** [comment] 2021-12-07 10:58
> In general, I'd prefer zombies to continue to wear their items when they revive so you actually have to pick them off their corpses,

IIRC a PR to that effect was just merged in today?

**Comment by Terrorforge** [comment] 2021-12-07 11:37
I don't think making the zombies carry the guns solves the fundamental problems. It helps with the "literally day one with zero effort" aspect, but zombie soldiers are still not _that_ hard to kill. I'm also not sure how much impact making the guns filthy and damaged would have. Admittedly I don't have much experience with really grody guns, because they basically don't exist, but I've never had a problem with damaged firearms except the very occasional misfire.

Maybe if they carried the guns, _and_ the guns were fouled and damaged, _and_ they had very little ammunition... but that would still leave us with a situation where the only thing standing between you and a full set of military gear is the ability to clobber what amounts to  handful of tough zombies. You'd still need to crank down the spawn chance at the minimum.

**Comment by estebandellasilva** [comment] 2021-12-07 12:02
> a

+ It takes the problem from no effort to get guns because you either could lead them away or they were lead a way, to some effort because it is not desireable that the zombie soldiers charge after some kind of monster or anything + you still have to kill them.

Is it  the be all end all solution? No, but you have to start somewhere

**Comment by Photoloss** [comment] 2021-12-07 12:03
> but that would still leave us with a situation where the only thing standing between you and a full set of military gear is the ability to clobber what amounts to handful of tough zombies.

Doesn't it take Tailoring 6 or so to repair though? Highly damaged armour does jack all and for clothing/utility it isn't all that powerful. Guns require a special kit to repair.

Ultimately if most soldier groups are changed to spawn low ammo and damaged weapons+tools the immediate value of these sites becomes *lower* than houses at the edge of town with their leather and DIY tool closets.

**Comment by Terrorforge** [comment] 2021-12-07 14:37
> Is it the be all end all solution? No, but you have to start somewhere
I'd just prefer to start at the other end. I'd rather see them removed from the game than undernerfed.


> Doesn't it take Tailoring 6 or so to repair though? Highly damaged armour does jack all and for clothing/utility it isn't all that powerful. 
Tailoring 6 isn't _that_ hard to get, and sometimes they spawn as high as yellow. But yes, it is at least more than literally no effort.

> Guns require a special kit to repair.
How much does that actually matter? I really don't have a lot of experience with damaged guns. I think the worst I've ever used was something that only had one pip, and all I remember that doing was that I stopped using it to break down doors.

> Ultimately if most soldier groups are changed to spawn low ammo and damaged weapons+tools the immediate value of these sites becomes _lower_ than houses at the edge of town with their leather and DIY tool closets.
There's still the issue that it's pretty easy to find ammo elsewhere. I also just fundamentally dislike the fact that you always end up using combat knife ballistic vest yada yada because they're just laying about, even if you did have to repair them. Clearly the consensus disagrees with my feeling that we might as well nuke the encounter entirely, but even so I think that even with all these proposed changes, we could really stand to dial down the odds of it significantly. Like I said at the top, finding a pile of dead soldiers should be a treat, not something you count on seeing in the first days of every run.

**Comment by Photoloss** [comment] 2021-12-07 15:21
> Sure. I'd just prefer to start at the other end. I'd rather see them removed from the game than undernerfed.

Hard disagree. Removal is dumb and easy. Merely re-adding the original version takes a lot more work, and if it's just *gone* there is nothing to make incremental progress on. Dead soldiers in a field are not so lore- or game-breakingly bad that they absolutely *need* to go without any chance of return.

**Comment by Alex-Folts** [comment] 2021-12-07 16:00
> What i dont exactly understand is why on a bodysite the guns are the only thing laying on the ground - if the soldiers where dead all of their items should be on the ground as this is normal behaviour currently. if not then the soldiers shouldnt have dropped their guns

I think assumed that soldiers carried guns in hands when become zombies, so after they just drop guns, while clothes/armor strapped/attached to them.

**Comment by Inglonias** [comment] 2021-12-07 16:07
If I had to guess it was done that way to avoid having to make another item group for zombie soldiers at the map extra. The soldiers don't typically drop rifles and shotguns.

**Comment by estebandellasilva** [comment] 2021-12-07 16:49
> > What i dont exactly understand is why on a bodysite the guns are the only thing laying on the ground - if the soldiers where dead all of their items should be on the ground as this is normal behaviour currently. if not then the soldiers shouldnt have dropped their guns
> 
> I think assumed that soldiers carried guns in hands when become zombie, so after they just drop guns, while clothes/armor strapped/attached to them.

You may be right, but that leaves the question why no other soldier zombies are found near their guns - because i assume that a rifle is a basic soldier equipment. Its only the body sites where there are guns - but you can find a soldier in nearly every town and military base and so on - but those nearly never have guns laying around.

**Comment by PatrikLundell** [comment] 2021-12-07 17:11
Well, the soldier zombies in other places would have dropped the hand held guns wherever they revived, which isn't modeled and may be a bit away from where you encounter them if they've drifted around due to things they're drawn towards. If you wanted to model separate drop of hand held stuff (which I doubt is worth the trouble) places with lots of zombies (that aren't hordes) would have dropped stuff that were used as weapons by the people taken down by the earlier zombie waves during the cataclysm. I guess that would be things like broken bottles, bricks, bent umbrellas, planks, and whatever else they could lay their hands on, as well as stuff carried when trying to run away (microwave ovens, cash, jewelry, huge packages of toilet paper, ...).

**Comment by estebandellasilva** [comment] 2021-12-07 17:36
> Well, the soldier zombies in other places would have dropped the hand held guns wherever they revived, which isn't modeled and may be a bit away from where you encounter them if they've drifted around due to things they're drawn towards. If you wanted to model separate drop of hand held stuff (which I doubt is worth the trouble) places with lots of zombies (that aren't hordes) would have dropped stuff that were used as weapons by the people taken down by the earlier zombie waves during the cataclysm. I guess that would be things like broken bottles, bricks, bent umbrellas, planks, and whatever else they could lay their hands on, as well as stuff carried when trying to run away (microwave ovens, cash, jewelry, huge packages of toilet paper, ...).

Again iam not denying that what you say is true - but in military bases you dont see random guns laying around so this does not count kinda. On the other hand if what you said is true - technically you should be able find random guns laying around on the ground somewhere - which also does not happen.

**Comment by PatrikLundell** [comment] 2021-12-07 17:57
Well, only the themed zombie groups seem to have drops on the ground added to them, while I would guess plopping down a mob doesn't generate such things on the ground, so the difference would come down to how different groups are placed in different locations technically rather than a deliberate choice to make them different. I'm not sure there's any logic available to place drops based on what kind of zombies the RNG decided to place in a location, in which case doing this for generic locations becomes tricky (you'd basically have to have the zombie group selected determine which loot list to use, and then place loot from that list on the locations available for loot placement on that specific map, rather than having zombie group and loot placement have no connection).

A military base definitely could have loot drop lists that dropped common weapons randomly, assuming they were dropped by the soldiers as they died. However, moving in the opposite direction and have stuff carried by zombies with rather few things dropped on the ground by the map generation is a better choice in my view.

**Comment by Inglonias** [comment] 2021-12-07 19:04
The extra gun spawns are handled by hardcoded logic specific to the military squad map extra. Soldiers in other locations don't drop carbines.

**Comment by anoobindisguise** [comment] 2021-12-07 20:06
I agree that it's fairly unrealistic soldiers have lots of ammo left to give you, it's hard to die to zombies when you still have bullets especially in the early stages where nothing is a hulk yet. Soldiers should give you carbines and empty mags galore but actually getting .223 should be a lot rarer. If we are to assume the soldiers did a lot of fighting giving their guns faults like fouling and durability loss would be good too.
Also, making most of their bullet loot 9mm from sidearms would do nicely for the very 223-skewed weapon balance, more 9mm is something I definitely want to see because the round is almost useless when there is practically more 223 than you can use. 
Alternatively the sites could be better guarded with more hordes of undead giving a reason for their death rather than them being inexplicably all dead with a gracken nearby.

**Comment by epsimpson** [comment] 2021-12-07 21:16
> Again iam not denying that what you say is true - but in military bases you dont see random guns laying around so this does not count kinda. On the other hand if what you said is true - technically you should be able find random guns laying around on the ground somewhere - which also does not happen.

I think a big difference is soldiers during wartime, which this was, carry their weapons into the field with them, so if an entire patrol gets wiped out and nobody can come looking for them, then you will find several great weapons.  It would be a great find and it REALLY should exist.  However, little if any ammo should be left, and evidence of rifles used as clubs should be there as well.  Really, their weapons should not even be on them as zombies, because if they were overrun they would have been using every one they could to the end, but I think it is a better game mechanic to have them on the soldiers, which makes their chasing a gracken a good thing -  it disperses at least some of the soldiers.  It should be increasingly rare to find such a site unlooted, including the zombie soldiers themselves, but the chances really should be highest early on.  

Soldiers on a base, though, don't generally carry their weapons around with them, even in a combat zone, unless there is a specific reason for them to do so, and more soldiers make an orderly withdrawal more possible, taking their equipment with them (Afghanistan is an insane counter-example of massive abandonment of material, and should not be copied in-game).

**Comment by estebandellasilva** [comment] 2021-12-07 21:27
> > Again iam not denying that what you say is true - but in military bases you dont see random guns laying around so this does not count kinda. On the other hand if what you said is true - technically you should be able find random guns laying around on the ground somewhere - which also does not happen.
> 
> I think a big difference is soldiers during wartime, which this was, carry their weapons into the field with them, so if an entire patrol gets wiped out and nobody can come looking for them, then you will find several great weapons. It would be a great find and it REALLY should exist. However, little if any ammo should be left, and evidence of rifles used as clubs should be there as well. Really, their weapons should not even be on them as zombies, because if they were overrun they would have been using every one they could to the end, but I think it is a better game mechanic to have them on the soldiers, which makes their chasing a gracken a good thing - it disperses at least some of the soldiers. It should be increasingly rare to find such a site unlooted, including the zombie soldiers themselves, but the chances really should be highest early on.
> 
> Soldiers on a base, though, don't generally carry their weapons around with them, even in a combat zone, unless there is a specific reason for them to do so, and more soldiers make an orderly withdrawal more possible, taking their equipment with them (Afghanistan is an insane counter-example of massive abandonment of material, and should not be copied in-game).

The reason i mention it - there aren't any encounter i met that replicate this szenario in the game except this one. This feels off especially when compared to other body sites where you find the full corpses, with their full stuff dropped (well not anymore but i havent played today)
In this regard its a unique encounter that does not make any sense no matter how you look at it - the longer we talk the more appearent it becomes. (i am talking about the dropped guns part)

In Germany the People who are on guard duty carry their gun with them so this point, would probably also be true in the US. 

Also if the People were overrun - for example in a military base - it would make even more sense that you could find a gun on the ground. But there are none from what i have seen.

**Comment by Terrorforge** [comment] 2021-12-09 00:06
I don't think the ammo is affected by item spawn rate. I'm on 0.5 and it's been a while since I did 1.0, but I don't recall seeing much of a difference. I do agree that cutting down on it would help, but it's still quite easy to acquire large amounts of 5.56. So having these very easy to access drops is still invalidating basically all other firearms. I mean, as others have mentioned, part of the problem is that guns actually _aren't_ everywhere. Other than military installations, the only place you can reliably find any is gun stores, and they're way harder to get to. The soldier spawns would be less overshadowing if you could reliably find shotguns and hunting rifles in farms and such.

The combat knife thing isn't really a problem with this spawn, it's a problem with combat knives being better than they have any right to be. If I could be bothered, I'd submit a PR to knock like four points of damage off them.

**Comment by Inglonias** [comment] 2021-12-12 17:48
[Fewer_Soldiers.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7699262/Fewer_Soldiers.zip)
Here's a quick'n'dirty mod that roughly cuts in half the number of military map extras that spawn in fields, forests, and roads.

**Comment by I-am-Erk** [comment] 2021-12-14 02:40
So, this is a heck of a lot of conversation and I admit I did not read it all. The correct solution to this problem is:
1. Tone down the "dead soldiers" map extra, which has very little in the way of emergent flavour. How did these soldiers die? how did they get here? etc.
2. Add more map extras depicting fragments of failed military activity, eg. a crashed humvee overrun with zombies.
3. add some random map specials along these lines as well.

**Comment by hexagonrecursion** [comment] 2022-02-17 20:14
I agree - we should reduce the weight of this map extra.

Here are the current settings:

name | map_extra_percent | total map extra weight | mx_military weight | mx_military_ratio
-|-|-|-|-
forest | 20 | 3118 | 8 | 0.0025657472738935213
forest_thick | 20 | 3069 | 8 | 0.002606712284131639
forest_water | 20 | 1537 | 25 | 0.01626545217957059
field | 6 | 1045 | 2 | 0.0019138755980861245
road | 75 | 653 | 25 | 0.03828483920367534
build | 90 | 275 | 5 | 0.01818181818181818
subway | 75 | 32 | 5 | 0.15625
lab_subway | 25 | 26 | 5 | 0.19230769230769232
research_facility_lot | 3 | 623 | 65 | 0.1043338683788122
research_facility_interior | 2 | 601 | 5 | 0.008319467554076539

```sh
jq -r '
.[]
| .map_extras
| to_entries
| .[]
| select(.value.extras | has("mx_military"))
| {
	name: .key,
	map_extra_percent: .value.chance,
	mx_total: ( [.value.extras[]] | add ),
	mx_military: .value.extras.mx_military,
}
| .mx_military_ratio = .mx_military / .mx_total
| "\(.name) | \(.map_extra_percent) | \(.mx_total) | \(.mx_military) | \(.mx_military_ratio)"
' data/json/regional_map_settings.json
```

**Comment by Fosheze** [comment] 2022-02-18 04:57
If the main problem is easy early game access to military gear then adding a "feral soldier" to the group as well would increase the risk greatly. Players aren't likely to go sprinting towards a feral armed with a fairly long range rifle and/or grenades. This doesn't eliminate the possibility of the player simply mowing down the entire group with a car to get the guns but that at least requires access to a car and is a problem in most areas of the game anyways.

**Comment by KurzedMetal** [comment] 2022-03-08 02:09
I think this issue will be covered by #55790 and #55908 soon.

**Closed** 2022-03-19 18:44 UTC
Labels: <Suggestion / Discussion>, Spawn
