### ISSUE TITLE
Map searches should search more than just the current overmap

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#21686] opened 2017-08-20 18:33 UTC
### Expected Behavior
Searching on the map will search across all revealed tiles.

### Actual behavior
Searches are seemingly only run across tiles on the overmap the cursor is on. It may be even less than the current overmap - not positive. This was noticed in #19997.

### Steps to reproduce the behavior
This can be easily reproduced by locating the refugee center found on the computer at the beginning of the Evacuee start.

![screen recording 2017-08-20 at 02 29 pm](https://user-images.githubusercontent.com/714017/29497337-2036023e-85b4-11e7-9fae-36ace16ff2d4.gif)

**Comment by OzoneH3** [comment] 2017-08-22 14:12
Seems like it was intended to be that way.

Quote from the code:
```
// This is on purpose only the current overmap, otherwise
// it would contain way to many entries
overmap &om = overmap_buffer.get_om_global(point(curs.x, curs.y));
```

**Comment by Coolthulhu** [comment] 2017-08-22 15:57
Searching current overmap is way too "internal".
Should probably be changed into radius around current point or something like that.

**Comment by kevingranade** [comment] 2017-08-22 16:05
I was intentional, but we can certainly revisit that decision and see if it's feasible to remove or change the limitation.

**Comment by Leland** [comment] 2017-08-22 16:10
> Seems like it was intended to be that way.

Good find, updated the title to make this a suggestion.

If removing the limitation isn't possible, I think that at the very least search should include all overmap specials, regardless of overmap (or distance from current point). That might be difficult from a code perspective but there's just no guarantee that a given overmap special would be nearby, so a player would have to currently move their cursor across the map and repeat their search until they've re-found it.

**Comment by OzoneH3** [comment] 2017-08-23 14:26
I tried to change it to scan not the overmap you are on but the size of an overmap around the cursor. (Which in total is always parts of 4 overmaps)

It's just not working and I don't know why really. Seems like changing the overmap outside the current cursor overmap messes things up?! I'm gonna leave it at that for now. If someone finds the problem be my guest and make a PR.
```
std::vector<point> locations;
overmap &om = overmap_buffer.get_om_global( point( curs.x, curs.y ) );
point last_overmap = point( INT_MIN, INT_MIN );

for( int x = curs.x - OMAPX/2; x < curs.x + OMAPX/2; x++ ) {
    for( int y = curs.y - OMAPY/2; y < curs.y + OMAPY/2; y++ ) {
        int om_x = x;
        int om_y = y;

        point this_overmap = omt_to_om_remain( om_x, om_y );

        if( this_overmap != last_overmap ) {
            last_overmap = this_overmap;
            om = overmap_buffer.get_om_global( point( x, y ) );
            std::vector<point> locations = om.find_notes( curs.z, term );
            locations.insert( locations.end(), locations.begin(), locations.end() );
        }

        if( om.seen( om_x, om_y, curs.z ) && lcmatch( om.ter(om_x, om_y, curs.z)->get_name(), term ) ) {
            locations.push_back( om.global_base_point() + point( om_x, om_y ) );
        }
    }
}
```

**Comment by BevapDin** [comment] 2017-08-23 17:01
```C++
om = overmap_buffer.get_om_global( point( x, y ) );
```
This calls the assignment operator because `om` is a reference. You probably don't want that. Maybe you meant to use a pointer to the overmap, which can be reassigned?

**Comment by OzoneH3** [comment] 2017-08-23 19:53
Updated the above post, it works now, but it takes ages the first time it loads the other three overmaps...

**Comment by CoroNaut** [comment] 2017-08-25 02:44
If you can make the search distance in overmap tiles into an options setting, then each individual player can set it how they like, it can go higher for better computers and lower for computers that cant handle the searches.

**Comment by BevapDin** [comment] 2017-08-25 04:30
> but it takes ages the first time it loads the other three overmaps...

Well, it *needs* to load the overmap from the filesystem, and that takes some time. I think we have an issue for that. And note that `overmabuffer::get` creates the overmap if it does not already exist (which can be very slow as well).

Consider calling `overmbap_buffer::get_existing`, which will oly load the overmap (if needed), but not create a new one. And that function also has a cache build-in, so you don't need to re-implement that.

**Comment by OzoneH3** [comment] 2017-08-25 08:49
>Consider calling overmbap_buffer::get_existing, which will oly load the overmap (if needed), but not create a new one.

Thanks, that was it. PR is up.

**Closed** 2017-09-09 18:59 UTC
Labels: Enhancement, Information / Interface, Suggestion (Discuss)
