### ISSUE TITLE
Shooting through laminated glass and doors without damaging them

### ISSUE THREAD

**Issue by L-3-on** [CleverRaven/Cataclysm-DDA#59050] opened 2022-07-07 21:22 UTC
### Describe the bug

Like the title says, you can shoot through laminated glass and doors made out of this material withour damaging them. Dridlicious (a Twitch streamer) found this out by accident and is using it now constantly while raiding a mall. ;) You can see it in his current vids (https://www.twitch.tv/dridlicious). He isn't using any mods besides the one that get normally preselected when creating a world (Disable NPC Needs, No Fungal Growth, Bionic Professions).

### Steps to reproduce

1) Pick up a gun
2) Aim at a zombie behind an intact laminated glass wall
3) Shoot
4) Zombie gets hit, laminated glass wall is totally fine

### Expected behavior

1) Pick up a gun
2) Aim at a zombie behind an intact laminated glass wall
3) Shoot
4) EITHER the zombie doesn't get hit and the glass wall is fine OR the zombie gets hit (with reduced damage probably) and the wall is damaged or destroyed

### Screenshots

https://www.twitch.tv/dridlicious

### Versions and configuration

Since I don't have access to his game and have no gun in my current game, I can only manually fill this section:

- Windows 10
- An experimental version from yesterday (06. July 2022)
- Tiles
- English
- Disable NPC Needs, No Fungal Growth, Bionic Professions

### Additional context

---

**Comment by RoyBerube** [comment] 2022-07-08 00:02
Try the same thing with a .50 cal rifle. The glass will break within a few shots, if not the first.

**Comment by anothersimulacrum** [comment] 2022-07-08 01:27
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33374

**Closed by anothersimulacrum** 2022-07-08 01:27 UTC
Labels: (S3 - Duplicate)
