### ISSUE TITLE
NPC teach other skills instead of fighting styles.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19968] opened 2017-01-07 13:27 UTC
I've had an NPC train my tailoring up to 7 instead of teaching me Brawling, all while her own tailoring skill level was 2.

**Comment by BevapDin** [comment] 2017-01-07 19:30
Duplicate of #18642.

**Closed by BevapDin** 2017-01-07 19:30 UTC

**Comment by Asmageddon** [comment] 2017-01-07 19:59
I need to use the search feature more than one time in three x.x
