### ISSUE TITLE
Debug: no TURRET at (-1, 1) of Humvee!

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#18364] opened 2016-09-16 21:46 UTC
Just right after Starting a new game (a small town, cars nearby):

Debug: no TURRET at (-1, 1) of Humvee!
FUNCTION : void vehicle::place_spawn_items()
FILE : src/vehicle.cpp
LINE : 4929

after spacebar the game continues to work.

version: 5507
mods: (all from ingame)

medieval
PK Reimagining
npc dont eat/sleep
filthy clothes
no Z revival

**Comment by pisskop** [comment] 2016-09-16 23:45
Turrets have no business being activated and automated in the first place.

**Comment by illi-kun** [comment] 2016-09-17 09:15
Duplicate of #17931.

**Closed by illi-kun** 2016-09-17 09:15 UTC
Labels: Bug
