### ISSUE TITLE
Game gets dramatically slower the longer the game goes on

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#21141] opened 2017-05-29 03:36 UTC
Not entirely certain what the cause of this is but the best way I can describe it the longer you survive on a particular save, the longer the game takes to perform actions. My save is under 40 MB, but I'm more than a hundred days in.
Performing any task that takes longer than an hour seems to dramatically increase how long it takes in real time. Sleeping through the night, making a batch of Vodka, constructing large batches (20) of steel plating to replace damaged armor, all these actions take at least ten minutes of real time.

I am by no means running a weak computer, and Cataclysm doesn't appear to be maxing out any of my specs so I'm not sure what's causing this. For what it's worth:
16 GB of RAM, 4.4 Ghz Quad Core Processor, I'm using an SSD for both my Operating system and the drive Cataclysm itself is on, and for whatever it's worth I'm using a NiVIDIA GeForce GTX 960 graphics card.

Taking a blind shot in the dark, I can only assume the problem stems from hording massive amounts of objects in my vehicle. 2952.9 Liters worth of Volume in stuff stored in various containers, a good number of that is "tiny" stuff that I have _a lot_ of (Batteries, thread, shell casings, etc)

I'm experiencing this problem is both the graphical build and console build. (0.c 22223-gdfe12f4099 and 0.c-22496-g99235b0 respectively)

**Comment by Night-Pryanik** [comment] 2017-05-29 03:57
You could upload your world, so someone could check that by themself.

**Comment by EkarusRyndren** [comment] 2017-05-29 03:59
Sure thing, compressed a ZIP for it... Game sure does compress well.
[Picture Rocks.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1034801/Picture.Rocks.zip)

**Comment by sniperm13** [comment] 2017-05-29 04:52
had a similar problem in an older build (5kish) and i had found that the ups batteries were charging beyond their limit which was causing the slowdown.  same deal, doing extended actions were excruciatingly slow.

ended up using non-ups batteries instead which wasnt a solution but then it got fixed in a later build. perhaps this is something similar. a bugged item...

**Comment by ZenZen2** [comment] 2017-05-29 08:31
I am running an old windows xp computer.

The more items around me the slower the game gets. But even in endgame with around 3000 Liters of items around me, it is still playable with one exception.
Multiple drop menu is not realy usable anymore, the scrolling there gets extremly slow, have to work with adv inventory to avoid it. After saving its faster, but not for long.

Is it possible that this is caused by some memory leak?

**Comment by int-ua** [comment] 2017-05-29 22:16
Are there any followers with picking rules? Try disallowing item gathering for all of them, maybe?

**Comment by spacenookie** [comment] 2017-05-30 07:24
Picture Rocks.zip has a 10x26 mega vehicle with no followers. I can confirm the slowdown on ubuntu 14.04 and it appears to be related to automatic turret targeting because if you switch the turrets to manual targeting the slowdown disappears.

**Comment by Tharn** [comment] 2017-05-31 16:33
Have not noticed slowdown in a game with a ton of items all gathered up in a vehicle and nearby 3x3 ground piles totaling an extra 4000L. The only time I notice slowdown is when I use advanced inventory and the search function (i.e. when it has to comb through the lists). So I assume slowdowns are related to special cases and not item bloat.

Autopickup on this massive pile does incur a delay, but it also incurs a delay out in the field with relatively few items all around.

**Comment by CoroNaut** [comment] 2017-06-07 14:27
My save game is 251,002,880 bytes or 239MB as of this moment and I have no performance issues with running the game long periods of time. Perhaps if you accumulate a large stockpile of items at your base of operations, then I could see a performance drop.

**Comment by somot** [comment] 2017-06-26 16:59
I've opened your save and walking alone doesn't seem to take a lot of time. Worth of noting is that I was doing that on a VM with 5 CPU cores assigned and 5120 MB RAM, so it didn't reflect my machine's full power. Here are the specifications:
GA-78LMT-USB3 Ultra Durable series motherboard
AMD FX-8320 CPU (was 3.5 GHz @1.275 V, reduced to 3.0 GHz@1.15 V due to stability issues)
8 GB DDR3 800 MHz RAM 
Nvidia GeForce GTX 650 Ti BOOST graphics card with 2 GB GDDR5
Western Digital Caviar Blue 1 TB SATA III 3.5" 7200 RPM HDD

**Comment by Aivean** [comment] 2021-01-16 20:03
Loaded the savefile in the latest experimental, added some debug mutation to avoid monsters and waited for several hours:
![image](https://user-images.githubusercontent.com/2865203/104821730-bd9fca00-57f2-11eb-873c-8169992af64e.png)

Seems that the issue is fixed.

**Closed by Aivean** 2021-01-16 20:03 UTC
Labels: Code: Performance
