### ISSUE TITLE
Game crashes when I try to refuel any vehicle 

### ISSUE THREAD

**Issue by pblp** [CleverRaven/Cataclysm-DDA#28731] opened 2019-03-15 12:19 UTC
Game version: 0.D-8616

Operating system: macOS 10.13.6 (17G4015)

Tiles or curses: Tiles

Mods active: Disable NPC Needs
Filthy Clothing
Modular Turrets
Alternative Map Key
Beta National Guard Camp
Vehicle Additions Pack
Tanks and Other Vehicles
Safe Autodoc
Manual Bionic Installation

### Expected behavior
Game doesn't crash when I fill any vehicle

### Actual behavior
Game crashes

### Steps to reproduce the behavior
1. Try to fill any vehicle several times
2. Game crashes
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2970952/crash.log)

**Comment by Hirmuolio** [comment] 2019-03-15 12:45
Are you sure you are on 0.D-8616? 

As far I know #28700 fixed this.

If you are not on 8616 I would recommend not updating yet because #28700 caused even worse bug that is fixed by #28732.

Try ignore the error until the error message goes away. I think it is trying to set the fuel temperature but fails. At least the previous case could resume normal gameplay after 6 ignored errors.

**Comment by pblp** [comment] 2019-03-15 13:04
Yes, I'm sure that my version is 8616 because I downloaded it today and re-checked it in main menu
I can't ignore the error because game crashes after this error

**Comment by Hirmuolio** [comment] 2019-03-15 13:18
You don't get a popup with choices to "abort" "retry" or "ignore"?

Does the crash happen with fresh fuel (from debug menu) or with an untouched car?

Handling fuel is kind of broken currently but I haven't seen any crashes.  Hopefully it is just some odd interaction with the bug I know and #28732 will fix it.

**Comment by pblp** [comment] 2019-03-15 13:24
I didn't get a popup witch options, game crashed and closed.
This crash happen several times when I tried to fill a tank(a vehicle) from a security van with a rubber hose.
After this crash happened 2 or 3 times,  I tried to test it.
I dismantled a tank from a security van and tried to fill the tank, so crash happened again.

**Comment by Hirmuolio** [comment] 2019-03-15 13:28
Does it also happen with fresh fuel (spawn with debug menu)?

Or on a new car (spawn with debug menu)?

Or could you pack the save folder in place where the crash happens and upload it to somewhere?

**Comment by Tharn** [comment] 2019-03-15 17:50
Also note that I ignored some errors with moving liquids, which resulted in me being unable to 'U'nload the containers where I ignored errors. Would not recommend doing this.

**Comment by Hirmuolio** [comment] 2019-03-15 17:53
Yeah that will add some temperature attributes to items that should not have them. In best case the item will just not stack with other items. I suspect this crashing is the worst case but I can't reproduce.

**Comment by Tharn** [comment] 2019-03-19 05:01
Are y'all still getting the crash?

**Comment by ZhilkinSerg** [comment] 2019-03-30 08:53
Should be fixed after #28700 and #28732 were merged.

Doesn't reproduce for me now, but please inform us if it is still crashing now.

**Closed by ZhilkinSerg** 2019-03-30 08:53 UTC
Labels: <Crash / Freeze>, Vehicles
