### ISSUE TITLE
Some tilesets center map and place sidebar incorrectly.

### ISSUE THREAD

**Issue by Prezombie** [CleverRaven/Cataclysm-DDA#6902] opened 2014-03-25 12:18 UTC
CDDA-sdlcurrent 0.a, windows version.

http://i.imgur.com/jejTTzH.jpg

It looks like that when I load http://www.nexusmods.com/cataclysmdarkdaysahead/mods/1/? 

Similarly, All the tilesets here, with the exception of the 16x and 20x act in identical ways. 

http://smf.cataclysmdda.com/index.php?topic=5621.0

I have no idea why.

**Comment by mugling** [comment] 2016-03-13 09:35
Cannot reproduce so closing at 6 months without confirmation. @Prezombie if you are still having the issue please re-open including details as to which version and any mods.

**Closed by mugling** 2016-03-13 09:35 UTC
Labels: Bug, Confirmation Needed
