### ISSUE TITLE
"Wreckage" vehicle related crash on road mapgen

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#28674] opened 2019-03-13 08:02 UTC
**Describe the bug**  
Rarely game crashes during game start when doing road mapgen when adding/smashing "Wreckage" vehicle.

**To Reproduce**  
Steps to reproduce the behavior are unknown yet.

**Screenshots**  

![image](https://user-images.githubusercontent.com/16213433/54261898-fd098980-457d-11e9-833d-58f42648d0ec.png)

![image](https://user-images.githubusercontent.com/16213433/54262472-4a3a2b00-457f-11e9-8a78-a5184d1253ab.png)

**Versions and configuration(please complete the following information):**

 - OS: Windows 10 (under VS debugger)
 - Game Version: latest `master`
 - Graphics version: Tiles
 - Mods loaded:

```JSON
[
  "dda",
  "no_npc_food",
  "generic_guns",
  "Medieval_Stuff",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "boats",
  "deoxymod",
  "blazemod",
  "No_Fungi",
  "No_Explosive_Zombies",
  "No_Big_Zombies",
  "Mundane_Zombies",
  "No_Anthills",
  "No_Bees",
  "manualbionicinstall",
  "safeautodoc",
  "novitamins",
  "StatsThroughSkills"
]
```

**Additional context**  

World settings, list of enabled mods and game version are probably irrelevant if it is at least `0.D`.

World options:
```JSON
[{"info":"A number determining how far apart cities are.  Warning, small numbers lead to very slow mapgen.","default":"Default: 4 - Min: 0, Max: 8","name":"CITY_SPACING","value":"4"},{"info":"Set base NPC healing rate per turn. Default: 0.01","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"NPC_HEALING_RATE","value":"0.00"},{"info":"Flat penalty of dispersion per point of skill under max.","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"GUN_DISPERSION_FLAT_PENALTY_PER_SKILL","value":"0.00"},{"info":"A scaling factor that determines density of monster spawns.","default":"Default: 1.00 - Min: 0.00, Max: 50.00","name":"SPAWN_DENSITY","value":"1.00"},{"info":"Disables tracking food, thirst and ( partially ) fatigue for NPCs. If true, NPCs won't need to eat or drink and will only get tired enough to sleep, not to get penalties.","default":"Default: False","name":"NO_NPC_FOOD","value":"false"},{"info":"( WIP feature ) Determines terrain, shops, plants, and more.","default":"Default: default - Values: default, desert_test","name":"DEFAULT_REGION","value":"default"},{"info":"A scaling factor that determines how often creatures spawn from rotting material.","default":"Default: 100 - Min: 0, Max: 1000","name":"CARRION_SPAWNRATE","value":"100%"},{"info":"Set base thirst rate per 5 minutes. Default: 1.0","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"PLAYER_THIRST_RATE","value":"0.00"},{"info":"Permits manual self-installation of bionics.","default":"Default: False","name":"MANUAL_BIONIC_INSTALLATION","value":"false"},{"info":"Set base hunger rate per 5 minutes. Default: 1.0","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"PLAYER_HUNGER_RATE","value":"0.00"},{"info":"If true, downstairs will be placed directly above upstairs, even if this results in uglier maps.","default":"Default: False","name":"ALIGN_STAIRS","value":"false"},{"info":"Value that divides total weapon dipsersion. 15 means that weapons became 15 times more acurate than default.","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"GUN_DISPERSION_DIVIDER","value":"0.00"},{"info":"Morale penalty for filthy clothing.  If true, wearing filthy clothing will cause morale penalties.","default":"Default: False","name":"FILTHY_MORALE","value":"false"},{"info":"A scaling factor that determines the time between monster upgrades.  A higher number means slower evolution.  Set to 0.00 to turn off monster upgrades.","default":"Default: 4.00 - Min: 0.00, Max: 100.00","name":"MONSTER_UPGRADE_FACTOR","value":"4.00"},{"info":"Determines the movement rate of monsters.  A higher value increases monster speed and a lower reduces it.  Requires world reset.","default":"Default: 100 - Min: 1, Max: 1000","name":"MONSTER_SPEED","value":"100%"},{"info":"Controls what migrations are applied for legacy worlds","default":"Default: 6 - Min: 1, Max: 6","name":"CORE_VERSION","value":"6"},{"info":"Allowed point pools for character generation.","default":"Default: any - Values: any, multi_pool, no_freeform","name":"CHARACTER_POINT_POOLS","value":"any"},{"info":"Handling of game world when last character dies.","default":"Default: keep - Values: keep, reset, delete, query","name":"WORLD_END","value":"keep"},{"info":"A number determining how large cities are.  0 disables cities, roads and any scenario requiring a city start.","default":"Default: 8 - Min: 0, Max: 16","name":"CITY_SIZE","value":"8"},{"info":"Disables tracking vitamins in food items.  If true, disables vitamin tracking and vitamin disorders.","default":"Default: False","name":"NO_VITAMINS","value":"false"},{"info":"A scaling factor that determines density of item spawns.","default":"Default: 1.00 - Min: 0.01, Max: 10.00","name":"ITEM_SPAWNRATE","value":"1.00"},{"info":"A scaling factor that determines density of dynamic NPC spawns.","default":"Default: 0.10 - Min: 0.00, Max: 100.00","name":"NPC_DENSITY","value":"0.10"},{"info":"Determines how much damage monsters can take.  A higher value makes monsters more resilient and a lower makes them more flimsy.  Requires world reset.","default":"Default: 100 - Min: 1, Max: 1000","name":"MONSTER_RESILIENCE","value":"100%"},{"info":"Season length, in days.  Warning: Very little other than the duration of seasons scales with this value, so adjusting it may cause nonsensical results.","default":"Default: 91 - Min: 14, Max: 127","name":"SEASON_LENGTH","value":"91"},{"info":"Initial starting time of day on character generation.","default":"Default: 8 - Min: 0, Max: 23","name":"INITIAL_TIME","value":"8"},{"info":"Season the player starts in.  Options other than the default delay spawn of the character, so food decay and monster spawns will have advanced.","default":"Default: spring - Values: spring, summer, autumn, winter","name":"INITIAL_SEASON","value":"spring"},{"info":"Skill threshold. Before used GUN_DISPERSION_MULT_PRE_SKILL_THRESHOLD + GUN_DISPERSION_MULT_POST_SKILL_THRESHOLD. After - only GUN_DISPERSION_MULT_POST_THRESHOLD.","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"GUN_DISPERSION_SKILL_THRESHOLD","value":"0.00"},{"info":"Sets the time of construction in percents.  '50' is two times faster than default, '200' is two times longer.  '0' automatically scales construction time to match the world's season length.","default":"Default: 100 - Min: 0, Max: 1000","name":"CONSTRUCTION_SCALING","value":"100"},{"info":"Value that adds to weapon dispersion per weapon damage value.","default":"Default: 0 - Min: -2147483648, Max: 2147483647","name":"DISPERSION_PER_GUN_DAMAGE","value":""},{"info":"Keep the initial season for ever.","default":"Default: False","name":"ETERNAL_SEASON","value":"false"},{"info":"Emulation of zombie hordes.  Zombie spawn points wander around cities and may go to noise.  Must reset world directory after changing for it to take effect.","default":"Default: False","name":"WANDER_SPAWNS","value":"true"},{"info":"Only spawn classic zombies and natural wildlife.  Requires a reset of save folder to take effect.  This disables certain buildings.","default":"Default: False","name":"CLASSIC_ZOMBIES","value":"false"},{"info":"If true, spawn zombies at shelters.  Makes the starting game a lot harder.","default":"Default: False","name":"BLACK_ROAD","value":"false"},{"info":"If true, static NPCs will spawn at pre-defined locations. Requires world reset.","default":"Default: False","name":"STATIC_NPC","value":"true"},{"info":"Determines whether starting NPCs should spawn, and if they do, how exactly.","default":"Default: scenario - Values: never, always, scenario","name":"STARTING_NPC","value":"scenario"},{"info":"If true, the game will randomly spawn NPCs during gameplay.","default":"Default: False","name":"RANDOM_NPC","value":"true"},{"info":"If true, radiation causes the player to mutate.","default":"Default: True","name":"RAD_MUTATION","value":"true"},{"info":"If true, experimental z-level maps will be enabled.  This feature is not finished yet and turning it on will only slow the game down.","default":"Default: False","name":"ZLEVELS","value":"false"},{"info":"Gun dispersion multiplier for lack of skill before threshold. GUN_DISPERSION_MULT_POST_SKILL_THRESHOLD will be added on top of it. GUN_DISPERSION_MULT_POST_SKILL_THRESHOLD=3.75 GUN_DISPERSION_MULT_POST_SKILL_THRESHOLD=1.25 means that zero skill character gets 3.75 + 1.25 = 5 extra weapon diseprsion multiplier.","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"GUN_DISPERSION_MULT_PRE_SKILL_THRESHOLD","value":"0.00"},{"info":"Gun dispersion multiplier for lack of skill after threshold. 1.25 means that character with skill level 5 gets 1.25 extra weapon dispersion multiplier.","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"GUN_DISPERSION_MULT_POST_SKILL_THRESHOLD","value":"0.00"},{"info":"Infected wounds from filthy clothing.  If true, getting hit in a body part covered in filthy clothing may cause infections.","default":"Default: False","name":"FILTHY_WOUNDS","value":"false"},{"info":"Sets max stamina value of the player.","default":"Default: 0 - Min: -2147483648, Max: 2147483647","name":"PLAYER_MAX_STAMINA","value":""},{"info":"Enables CBM slots mechanics. If true CBM slots are enabled.","default":"Default: False","name":"CBM_SLOTS_ENABLED","value":"false"},{"info":"Set base fatigue rate per 5 minutes. Default: 1.0","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"PLAYER_FATIGUE_RATE","value":"0.00"},{"info":"Set base player healing rate per turn. Default: 0.01","default":"Default: 0.00 - Min: -2147483648.00, Max: 2147483648.00","name":"PLAYER_HEALING_RATE","value":"0.00"},{"info":"Disables vehicle part faults.  If true, disables vehicle part faults, vehicle parts will be totally reliable unless destroyed, and can only be repaired via replacement.","default":"Default: False","name":"NO_FAULTS","value":"false"},{"info":"Makes autodoc operations completely safe, independent of the players skill.","default":"Default: False","name":"SAFE_AUTODOC","value":"false"},{"info":"Enables sleep deprivation mechanics. If true, stimulants will only help you so far, and you might have to enforce proper sleep hygiene for a while.","default":"Default: False","name":"SLEEP_DEPRIVATION","value":"false"}]
```

**Comment by BevapDin** [comment] 2019-09-23 04:26
Probably also a duplicate of #34028.

**Closed by BevapDin** 2019-09-23 04:26 UTC
Labels: <Crash / Freeze>, Mapgen, Vehicles, [C++]
