### ISSUE TITLE
Attempt to grab an item from damaging field may cause you grab another thing

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#8978] opened 2014-09-13 21:42 UTC
say, if you want to grab something from fire/acid tile,if the item is destroyed before you take it, you will grab another thing instead. While fighting with bare hands, trying to grab something from acid pool may cause you wield an acid zombie corpse instead, and this is very annoying.
##

**Comment by Leland** [comment] 2017-08-24 00:34
Super old bug (that was considered old in 2014, phew) – can anyone confirm this is still around?

**Comment by Coolthulhu** [comment] 2017-08-24 02:07
It is.
The items are still addressed by their position in item vector.
There is no way to fix it without either being able to confirm that the item is the one we want, or tracking all instances of "wanted" items.

**Comment by wapcaplet** [comment] 2021-02-19 02:36
Could not reproduce in 0.E-9737-g511ddcb179 using the gasoline/brandy case mentioned above (liquids cannot be picked up), or using splintered wood or tinder. It has been several years since this was confirmed, so I am setting it back to "Need confirmation". Please provide steps if anyone can still reproduce it.

**Comment by actual-nh** [comment] 2021-02-19 03:18
Should the "Bug" label be removed?

**Comment by wapcaplet** [comment] 2021-02-19 04:03
> Should the "Bug" label be removed?

I think it should probably still be considered a bug, if it can be reproduced. I thought about simply closing it, but I am not confident that I tested thoroughly enough to rule out the possibility that it's still valid.

**Comment by anothersimulacrum** [comment] 2021-02-19 04:25
I'm going to remove the bug label, so stalebot gives us a reminder to revisit this in 30 days or so.

**Comment by Night-Pryanik** [comment] 2021-06-16 06:46
Seems like stalebot forgot about this. Closing for now.

**Closed by Night-Pryanik** 2021-06-16 06:46 UTC
Labels: (S1 - Need confirmation), Info / User Interface
