### ISSUE TITLE
No warnings while waiting 

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#31626] opened 2019-06-19 14:48 UTC
# Describe the bug

While waiting, there is no interrupt or warning message for hearing, spotting, or being attacked.  All potential alerts are ignored until damage is received

# Steps To Reproduce

Walk into an area with roaming zombies, wait for 5 minutes

# Expected behavior

A warning message should appear "You heard X, continue waiting? You see X approaching, continue waiting?  You dodged an attack, continue waiting?"

# Screenshots

No screenshot, but [a video showing 2 times this has occurred](https://www.youtube.com/watch?v=6hSrNlRJ3CI).  Both instances ignore sound, visual and even attack evasion

# Versions and configuration

OS: Windows 10.0 1809
Game: 0.D-4578-gf477339 [64-bit]
Graphics: Tiles
Mods:  Dark Days Ahead [dda],  Disable NPC Needs [no_npc_food]

**Comment by stopple** [comment] 2019-06-21 17:08
Just had the same experience while reading Top Gear magazine

Sitting in the open, full light and visibility.  Zombie walks up, grabs, I break the grab, then bitten.  Reading continues uninterrupted until damage is taken.

![book_bit](https://user-images.githubusercontent.com/19255442/59939300-8eae5000-9425-11e9-8594-d68be790fae6.PNG)

**Comment by Canivir** [comment] 2019-07-02 13:53
I have been having a seemingly similar problem, and managed to get a save where this happens reliably.
A zombie is behind the corner and can't be seen by the player:
![bug1](https://user-images.githubusercontent.com/42702533/60517407-ef6c4100-9cdf-11e9-819a-1d863bb69d92.PNG)
Of note, zombie speed is 100%, and there is no way a standard zombie should be able to walk next to and attack me before I see him in this scenario,  yet if I wait 5m, the first message that breaks me out of the wait is that I was attacked:
![bug2](https://user-images.githubusercontent.com/42702533/60517727-74575a80-9ce0-11e9-9389-7fbea05de945.png)
And this is where he's now standing:
![Bug3](https://user-images.githubusercontent.com/42702533/60517778-876a2a80-9ce0-11e9-9214-10bb40291f0a.PNG)

On another note, not stopping gives "zombie is dangerously close" warnings as well, and here and in my other experiences with the bug, I seem to never get the "Zombie is approaching" warning.
This also happens (less reliably, it seems) with zombies you see and get warned about with "see X, stop?" and then you get hit before you get the "approaching" warning.

Save: 
[Thousand Palms.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3350375/Thousand.Palms.zip)


Debug:
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-5172-g0d99a68 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Prevent Zombie Revivication [no_reviving_zombies],
    StatsThroughSkills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Vehicle Additions Pack [blazemod]
]

**Comment by esotericist** [comment] 2019-07-02 14:17
I've also experienced this, but I haven't been in a position to attempt to chase down the cause as of yet.

**Comment by esotericist** [comment] 2019-07-09 06:13
As an update, I believe I've found the cause of this, but fixing it is going to be non-trivial.

**Comment by l29ah** [comment] 2019-07-28 02:12
Couldn't reproduce at 0.D-5919-gd1fe239a08-dirty
Probably fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/32281

**Closed** 2019-07-28 04:12 UTC
Labels: (S2 - Confirmed), <Bug>, Character / Player
