### ISSUE TITLE
CDDA experemental bug

### ISSUE THREAD

**Issue by glaminator** [CleverRaven/Cataclysm-DDA#52566] opened 2021-10-31 18:11 UTC
### Describe the bug

the joystick does not work and does not appear and the buttons do not work

### Steps To Reproduce

1.launched the game 2.tried to use the in-game joystick  3. poked buttons 4.nothing happens

### Expected behavior

I expected some kind of response from the game

### Versions and configuration

OC: redmi 8
version: 212b6d8
laguage: russian

**Comment by ZhilkinSerg** [comment] 2021-10-31 21:54
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/48632

Disable any accessibility apps/features you might have enabled - autoclickers, click/swipe assist, etc.

**Comment by glaminator** [comment] 2021-11-01 04:52
I don’t have one and it still doesn’t work

**Comment by glaminator** [comment] 2021-11-01 05:35
wait ... I don't know how, but the game is working!

**Comment by ZhilkinSerg** [comment] 2021-11-01 16:15
Closing then.

**Closed** 2021-11-01 16:15 UTC
Labels: (S3 - Duplicate), Controls / Input, OS: Android
