### ISSUE TITLE
Game crash at the end of character creation

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#32196] opened 2019-07-06 17:26 UTC
# Describe the bug
Game crash at the end of character creation (last tab and Yes to start the game).

# Steps To Reproduce
Unknown

# Expected behavior
No crash

# Screenshots
Here is the console msg:
user@user:~$ The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x25) [0x841ee6]
	./cataclysm-tiles() [0x8344d7]
	./cataclysm-tiles() [0x8346d8]
	/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fca7ab4bf20]
	./cataclysm-tiles(_ZNK3map20has_flag_ter_or_furnERKSsRK8tripoint+0x59) [0xa39493]
	./cataclysm-tiles() [0xa39e2b]
	./cataclysm-tiles(_ZN3map19add_item_or_chargesERK8tripoint4itemb+0x7c) [0xa3e0c2]
	./cataclysm-tiles() [0xd769d3]
	./cataclysm-tiles(_ZN7vehicle11remove_partEi+0x263) [0xd75c83]
	./cataclysm-tiles(_ZN7vehicle5smashEfff5pointf+0x26c) [0xd7679a]
	./cataclysm-tiles(_ZN3map18add_vehicle_to_mapESt10unique_ptrI7vehicleSt14default_deleteIS1_EEb+0x51e) [0xa6bb34]
	./cataclysm-tiles(_ZN3map11add_vehicleERK9string_idI17vehicle_prototypeERK8tripointiiib+0x26b) [0xa78a13]
	./cataclysm-tiles(_ZN20VehicleSpawnFunction18builtin_parkinglotER3mapRKSs+0x132) [0xd8a3c0]
	./cataclysm-tiles(_Z18mapgen_parking_lotP3map6int_idI6oter_tE10mapgendataRK10time_pointf+0xf5) [0xaafccc]
	./cataclysm-tiles(_ZN23mapgen_function_builtin8generateEP3mapRK6int_idI6oter_tERK10mapgendataRK10time_pointf+0x4c) [0xa6c484]
	./cataclysm-tiles(_ZN3map8draw_mapERK6int_idI6oter_tES4_S4_S4_S4_S4_S4_S4_S4_S4_S4_RK10time_pointfiPK17regional_settings+0x36c) [0xa78ef4]
	./cataclysm-tiles(_ZN3map8generateEiiiRK10time_point+0x420) [0xa9688c]
	./cataclysm-tiles(_ZN3map5loadnEiiib+0x3e7) [0xa48067]
	./cataclysm-tiles(_ZN3map5loadnEiib+0x35) [0xa489c9]
	./cataclysm-tiles(_ZN3map4loadEiiib+0x5a) [0xa48a64]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	??:?
	log_crash
	crash.cpp:?
	signal_handler
	crash.cpp:?
	??
	??:0
	map::has_flag_ter_or_furn(std::string const&, tripoint const&) const
	??:?
	map::add_item_or_charges(tripoint const&, item, bool)::{lambda(tripoint const&)#1}::operator()(tripoint const&) const
	map.cpp:?
	map::add_item_or_charges(tripoint const&, item, bool)
	??:?
	vehicle::remove_part(int)::{lambda(std::string const&, std::string const&)#1}::operator()(std::string const&, std::string const&) const
	vehicle.cpp:?
	vehicle::remove_part(int)
	??:?
	vehicle::smash(float, float, float, point, float)
	??:?
	map::add_vehicle_to_map(std::unique_ptr<vehicle, std::default_delete<vehicle> >, bool)
	??:?
	map::add_vehicle(string_id<vehicle_prototype> const&, tripoint const&, int, int, int, bool)
	??:?
	VehicleSpawnFunction::builtin_parkinglot(map&, std::string const&)
	??:?
	mapgen_parking_lot(map*, int_id<oter_t>, mapgendata, time_point const&, float)
	??:?
	mapgen_function_builtin::generate(map*, int_id<oter_t> const&, mapgendata const&, time_point const&, float)
	??:?
	map::draw_map(int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, time_point const&, float, int, regional_settings const*)
	??:?
	map::generate(int, int, int, time_point const&)
	??:?
	map::loadn(int, int, int, bool)
	??:?
	map::loadn(int, int, bool)
	??:?
	map::load(int, int, int, bool)
	??:?

# Versions and configuration
Ubuntu 18.04
Version 0.D 

# Additional context

[crash-cdda-OD.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3364885/crash-cdda-OD.zip)

**Comment by BevapDin** [comment] 2019-09-23 04:22
I'm closing this duplicate of #34028.

**Closed by BevapDin** 2019-09-23 04:22 UTC
Labels: <Crash / Freeze>, Character / World Generation
