### ISSUE TITLE
NPCs have no carrying capacity

### ISSUE THREAD

**Issue by SolidMilk19** [CleverRaven/Cataclysm-DDA#42839] opened 2020-08-10 02:13 UTC
# Describe the bug

NPCs, even when carrying some kind of container in their inventory (a backpack, a hoodie or cargo pants for example) have no storage capacity in them. Their Volume gets displayed at 0,00 L and so they're stuck with whatever they got in their hands or the stuff they originally spawned with. Very frustrating if they need to use ammo or you want them to carry bandages.

# Steps To Reproduce

1. Start a new file with the Evacuee scenario.
2. Initiate a trade with the NPC there. Try giving them something relatively small while they're already wielding an item.

# Expected behavior

The NPC should put said item into their inventory, either their bag or the pockets of a piece of clothing they're wearing.

# Screenshots

![Capture](https://user-images.githubusercontent.com/68878873/89747520-6832f480-dabf-11ea-809b-bb72e1c29bcc.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-4943-ge0136e2
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food

**Comment by Enderlordalatreon** [comment] 2020-11-28 07:17
I think until the issue is fixed, you can give them the trait "Debug Carry Capacity" and the debug pocket universe item.

**Comment by wapcaplet** [comment] 2021-11-14 05:35
This was fixed by #52261.

**Closed by wapcaplet** 2021-11-14 05:35 UTC
Labels: <Bug>, NPC / Factions
