### ISSUE TITLE
Cannot disassemble large damaged tent

### ISSUE THREAD

**Issue by banyenbkk** [CleverRaven/Cataclysm-DDA#51467] opened 2021-09-08 11:06 UTC
### Describe the bug

There is no way to disassemble damaged tents with a cutting tool of quality 1 or 2 as stated by https://cdda-trunk.chezzo.com/largebroketent/disassemble

### Steps To Reproduce

1. Find a damaged tent
2. Have a tool with cutting quality of 1 (or 2)
3. Try to disassemble

https://cdda-trunk.chezzo.com/largebroketent/disassemble

### Expected behavior

I expect to be able to cut up a tent with a cutting tool.  

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Found this issue while attempting to get plastic sheets.  Seems there are few sources of them and disassembling damaged tents seemed to be the most readily available method.

**Comment by Termineitor244** [comment] 2021-09-09 07:37
I tried to reproduce this, but I couldn't, I spawned some broken tents, normal size and large, and a pair of scissors, but I could start disassembling both without problems.

What I did notice was that you cannot disassemble the normal (non damaged) tents, so those items need a disassemble recipe added to them.

**Comment by PatrikLundell** [comment] 2021-09-09 08:49
It may be a matter of how tents are damaged. I've encountered a few tents that couldn't be taken down (note that this isn't disassembling, though: it produced damaged tents), probably because the central tile you examine to take them down was missing. It may well be that there's a similar issue with disassembly.

**Comment by hexagonrecursion** [comment] 2022-01-04 19:56
I could not reproduce the issue either

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: e7cd5fb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Night-Pryanik** [comment] 2022-02-03 13:56
Can't confirm either. Closing as unconfirmed.

**Closed by Night-Pryanik** 2022-02-03 13:56 UTC
Labels: (S1 - Need confirmation), Crafting / Construction / Recipes, Fields / Furniture / Terrain / Traps
