### ISSUE TITLE
Possible to get an infinite single point pool at character create

### ISSUE THREAD

**Issue by A-lxe** [CleverRaven/Cataclysm-DDA#31742] opened 2019-06-22 17:40 UTC
# Describe the bug

It's possible to add arbitrarily many points to the single point pool at character create. This can be confusing if you accidentally do the steps that add points, leading you to use a larger point pool without realizing it.

# Steps To Reproduce

Here's how I did it:
1. Start creating a custom character with a single point pool
2. Select Challenge-Island Prison Break
3. Select Death Row Convict - the Killer Drive trait becomes selected without costing points
4. Select Convict - the Killer Drive trait stays selected, points don't change
5. Deselect Killer Drive - gain two points
6. Repeat from 3 for as many extra points as you want

# Expected behavior

Maybe Death Row Convict should cost two more points than Convict?

Or at least Killer Drive should deselect when selecting Convict from Death Row Convict.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Debian Buster
 - Game Version: 0.D-4800-g678b0b0 build 9202
 - Graphics version: Tiles
 - Mods loaded: default

**Comment by Deak1113** [comment] 2019-06-22 18:12
can confirm it in fact works, but only in island break scenario, if you will have for example 30 points in it, and then change the scenario, point pool will reset.

**Comment by Deak1113** [comment] 2019-06-22 18:12
(and in works in other prison break scenarios too)

**Comment by Night-Pryanik** [comment] 2019-06-22 18:34
Duplicate of #23851.

**Closed by Night-Pryanik** 2019-06-22 18:34 UTC
Labels: (S1 - Need confirmation), <Exploit>, Character / World Generation
