### ISSUE TITLE
Hitting ESC while in dialog should exit dialog

### ISSUE THREAD

**Issue by justn6** [CleverRaven/Cataclysm-DDA#50106] opened 2021-07-21 03:05 UTC
# Is your feature request related to a problem? Please describe.
Currently the key press to exit dialog is dynamic and based on how many entries are in the menu. There should be a set keypress to exit dialog.

# Describe the solution you'd like
Hitting ESC while in dialog should exit dialog

# Describe alternatives you've considered
Memorizing which layer of dialog I'm on and knowing how far down that option is has always been an option, but not very intuitive and feels bad.

# Additional context
Solely a QoL request. Current system is fine but would be a nice addition.

**Comment by Night-Pryanik** [comment] 2021-07-21 03:14
Duplicate of #31185.

**Closed by Night-Pryanik** 2021-07-21 03:14 UTC
