### ISSUE TITLE
Game crashes when NPC is farming in survival camp

### ISSUE THREAD

**Issue by Twzork** [CleverRaven/Cataclysm-DDA#35526] opened 2019-11-14 18:02 UTC
# Description
The game crashes after a few ingame minutes if the NPC (Darrell) is farming. The crop that's already in the map I did it myself.

# Steps To Reproduce
Use "Wait a while" feature and the game crashes after a few minutes.
Message me in discord if you can't reproduce the bug for some reason. Kodapa#8419

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9360-ge71ad4f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Secronom [secronom],
    Cataclysm++ [Cata++],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi]
]

# Additional context

CRASH LOG FILE: config/crash.log
VERSION: 0.D-9360-ge71ad4f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D45D5[cataclysm-tiles.exe+0x1D45D5]
    @0x5D50A2[cataclysm-tiles.exe+0x1D50A2]
    SMPEG_error+0x4B034@0xFB9D10[cataclysm-tiles.exe+0xBB9D10]
    _C_specific_handler+0x98@0x7FF80DFF8048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FF80E8811FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FF80E84A289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FF80E87FE6E[ntdll.dll+0x9FE6E]
    SDL_LogCritical+0x12FD6@0xFDA5E6[cataclysm-tiles.exe+0xBDA5E6]
    @0x4F9A30[cataclysm-tiles.exe+0xF9A30]
    @0xDB5D09[cataclysm-tiles.exe+0x9B5D09]
    initterm_e+0x1BB@0x7FF80E00A82B[msvcrt.dll+0x3A82B]
    @0x5D518C[cataclysm-tiles.exe+0x1D518C]
    IMG_LoadWEBP_RW+0x1A1BE8@0x124D768[cataclysm-tiles.exe+0xE4D768]
    IMG_LoadWEBP_RW+0x598DA3@0x1644923[cataclysm-tiles.exe+0x1244923]
    IMG_LoadWEBP_RW+0x5A08AE@0x164C42E[cataclysm-tiles.exe+0x124C42E]
    IMG_LoadWEBP_RW+0x5A0192@0x164BD12[cataclysm-tiles.exe+0x124BD12]
    @0x43D297[cataclysm-tiles.exe+0x3D297]
    @0x44E96A[cataclysm-tiles.exe+0x4E96A]
    @0x45276C[cataclysm-tiles.exe+0x5276C]
    @0xCCECAB[cataclysm-tiles.exe+0x8CECAB]
    @0xB8449D[cataclysm-tiles.exe+0x78449D]
    @0xB97C04[cataclysm-tiles.exe+0x797C04]
    @0xB9B6A1[cataclysm-tiles.exe+0x79B6A1]
    @0x70D1C2[cataclysm-tiles.exe+0x30D1C2]
    @0x70E95C[cataclysm-tiles.exe+0x30E95C]
    IMG_LoadWEBP_RW+0x6278D8@0x16D3458[cataclysm-tiles.exe+0x12D3458]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF80E2C7BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FF80E84CED1[ntdll.dll+0x6CED1]

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3847928/save.zip)

**Comment by davidpwbrown** [comment] 2019-11-24 14:00
Cant reproduce.

**Comment by davidpwbrown** [comment] 2019-11-24 17:51
OP confirms cant reproduce anymore on latest master anymore ( in the Dev Discord ) closing.

**Closed by davidpwbrown** 2019-11-24 17:51 UTC
Labels: <Bug>, NPC / Factions, Player Faction Base / Camp, [C++]
