### ISSUE TITLE
Base camp missions

### ISSUE THREAD

**Issue by Thogsloc** [CleverRaven/Cataclysm-DDA#28910] opened 2019-03-22 11:37 UTC
**Describe the bug**  
My game version is 8636
1. I send my mate for the harvest mission of a WEST farm expansion and I cannot call him back and finish the task. 
2. I start a new blacksmith expansion on NORTH and after it finished it replaced my base camp on BASE MENU. And I cant call back my mate from its mission. 
3. I cant upgrade my expansion part of camp.

**To Reproduce**  
1. Start a camp.
2. Send a NPC for new expansion.
3. Send a NPC for expansion's task.

**Expected behavior**  
The missions should be finished and I could call back my mates.

**Screenshots**  
No screenshots

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10 64x]
 - Game Version: [from the main menu, e.g. 0.D-786-g078bf41]
 - Graphics version: [Tiles]

**Additional context**  
My savegame:
https://www.dropbox.com/s/vjx2klgyqcz0xs6/Hammer.rar?dl=0
If there is any problem in showing the names, my game is Chinese.

**Comment by davidpwbrown** [comment] 2019-03-22 13:37
duplicate of #28868

**Comment by Melodeiro** [comment] 2019-03-22 15:35
Seems more like #28901

**Closed** 2019-03-22 17:32 UTC
