### ISSUE TITLE
The bicycle collides with errors in movement code.

### ISSUE THREAD

**Issue by sniperm13** [CleverRaven/Cataclysm-DDA#20640] opened 2017-03-22 21:17 UTC
tried 'G'rabbing a bicycle with broken foot pedals back to base but that message pops up when doing soon as i try to move. reloaded save, same message. fairly sure its unintentional so i thought better to report it. cdda v. 6348.

**Comment by Chezzo** [comment] 2017-03-22 22:19
Do you have a save file, and a screenshot of the error, friend?

**Comment by sniperm13** [comment] 2017-03-22 23:14
![cdda6348](https://cloud.githubusercontent.com/assets/24485010/24224837/99234c08-0f1a-11e7-9979-8d5054cec1c5.jpg)

**Comment by sniperm13** [comment] 2017-03-22 23:15
sorry, kinda new. hope that worked. only got inet on the phone. :/

**Comment by Toothspit** [comment] 2017-03-23 03:23
Repro steps:

1. Default world options, new world, debug spawn bicycle (bottom of the list).
2. From the front of the bicycle (opposite side of basket), `G`rab it. Above screenie is in the right spot.
3. Attempt to move away from the bicycle. Bicycle will collide with errors in the movement code.

Trying to move any other direction drags the bike diagonally as normal, after which it can be dragged normally, like this never happened.

Relevant bit might be grab.cpp L116?

**Comment by sniperm13** [comment] 2017-03-23 03:58
sounds about right as far as getting the error goes. soon after you try to move after 'G'rabbing, it pops up. couldnt make sense of that code tho. Xd

**Comment by Night-Pryanik** [comment] 2018-02-20 16:09
Closing in favor of #23000 due to the better steps to reproduce.

**Closed by Night-Pryanik** 2018-02-20 16:09 UTC
Labels: Bug, Vehicle
