### ISSUE TITLE
Zombies somehow quantum tunnel through ceilings into basements. No Probability travel/Quantum Tunnel CBM drop on dissection.

### ISSUE THREAD

**Issue by EldritchSigma** [CleverRaven/Cataclysm-DDA#35605] opened 2019-11-19 17:25 UTC
# Describe the bug

When hiding in a basement and making a noise then start reading a book or anything that skips time fast. You get interrupted by sound or foodsteps in your vicinity. When checking its zombies. Somehow  zombies manage to quantum tunnel through the ceiling. When the zombies are butchered they do not drop probability travel CBM (only in one instance and admittedly that was a bio operator I think and would make sense considering they still operate their bionics.). There were no portals or other means of teleportation nearby. This is either A) incredibly immersion ruining, quantum tunneling zombies should either drop the quantum tunneling CBM on death or the teleportation CBM with sufficient power storage provided your relevant skills are high enough (they are in this instance) or and more likely B) Downright not intended.

# Steps To Reproduce

1. **Make character with tons of first aid, electronics and mechanic skill**
2. **Go into your weebs basement/any basement.**
3. **Make an obnoxious ammount of noise**, e.g. priming firecrackers, detonating several grenades, building a deathmobile and simply using its horn to honk. The doors to the surface are closed and even barricaded 
4. **Go read a book, craft some shit, boil a batch of water** or raise moral via usage of the massage stick you either debug spawn or occassionally find in those stores where you can also find fuel for fires, other stress relief tools, lots of dyed leather clothing or catgirl stuff for whatever reason.
5. **Get interrupted in your learning sesssion** of reading SICP or Bioweapon production via a regular zombie who has no way in but knows you are below him cause you made an obnoxious amount of noise from honking your clown horn while building your deathmobile.
6. **Kill said zombie** only to be interrupted by another zombie
7. **Dissect zombie and wonder why you cant find any quantum tunneling cbms.**
8. Make a bug report that has a total of 13 instances of the word quantum tunneling in it.
9. (Optional) Go back ingame and realize you cannot get your death mobile out of the basement.

# Expected behavior

Either that zombies that quantum tunnel drop the quantum tunnel CBM on dissection or that they do not quantum tunnel through ceilings when there is no way to quantum tunnel through the ceiling.

# Screenshots

None available. Very simple to reproduce however.

# Versions and configuration
Build 9915,
Win 7, 
Tileset (Dead People), 
Current mods: Pretty much all functional mods that add content (apart from generic guns, stats through skills and the dinosaur mod), but the bug is also reproduceable without mods. 

# Additional context

None, except standing in a basement full of the corpses of the now permanently killed zombies.

Seriously though guys, love the game, love the work you do on it. If I had more time outside of work I'd fix this myself and get acquainted with the games code.

# Trivia:

The term "quantum tunneling" or "quantum tunnel" was used for a total of 13 times in this report including topic and one sentence where the term "quantum tunneling" was used 4 times. Unless I counted wrong of course. Which will then be blamed on standard deviation or something.

**Comment by EldritchSigma** [comment] 2019-11-19 17:26
Oh yeah one more important thing: Experimental Z-Levels must be turned on obviously.

**Comment by Funguss** [comment] 2019-11-19 20:19
I do believe this issue is due to stairs not matching up. Rather than appearing at the staircase at the next level they get their X coordinate shifted up or down depending on the staircase. This can result in the kind of situation you're experiencing, or zombies materialising out of thin air in the middle of a house or some such.

**Comment by anothersimulacrum** [comment] 2019-11-19 22:55
The issue you're thinking of was closed because a fix was merged recently

**Comment by Funguss** [comment] 2019-11-20 01:16
In regard build number, OP: A convenient way to get it (and all other system info that may be needed, for future reference) is to enter the debug menu at the bottom of the main menu (accessed via your 'escape' key), 'i' for info, 'r' for generate game report. This will copy the system information required to the clipboard, including version string.

**Comment by MrOlaf** [comment] 2019-11-20 08:19
Are you using wander spawns? I am having the same issue and I think it may be the game dropping in the wanderspawn z Z into your location. I also had 1 zombie dog suddenly become 6 zombie dogs out of nowhere.

This may be connected to the other issue: remember position of your vehicle underground like a folding cart and you'll see it on lvl0 on the overmap instead of the -1 or -2 zlvl where you left it.

**Comment by Amoebka** [comment] 2019-11-20 18:20
The recent fix doesn't seem to be working as intended. Zombies still teleport between Z-levels in builds that have it.

**Comment by int-ua** [comment] 2021-01-14 04:15
Sorry, this needs a better steps to reproduce and/or verification on a recent version.

**Closed by int-ua** 2021-01-14 04:15 UTC
Labels: (S1 - Need confirmation), <Bug>, Monsters, Z-levels
