### ISSUE TITLE
Asthmatic NPS doesn't receive his inhaler on the inhaler quest completion

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31773] opened 2019-06-23 18:44 UTC
# Describe the bug

It just vanishes from the player's inventory, leaving the poor guy with his fate.

# Expected behavior

NPC getting the inhaler in his inventory for later use.

# Versions and configuration

 - Game Version: 0.D-4881-ge4218458ba-dirty

**Comment by l29ah** [comment] 2019-06-30 15:12
Also if an NPC is experiencing an asthma attack and is given an inhaler, he won't use it.

**Comment by wapcaplet** [comment] 2020-01-25 00:41
I experienced the same behavior:
- Got inhaler quest from NPC (luckily I already had one with me)
- Talked to NPC again and completed quest
- Asked NPC to travel with me, and she accepted
- A few minutes later she has an asthma attack
- Talked to NPC and asked to trade - no inhaler in her inventory

**Comment by wapcaplet** [comment] 2020-01-28 02:05
I took a crack at fixing this today, and was stymied by an oddity in the mission handling, plus what looks like a bug in inventory transfer for the inhaler (and possibly other charged items). I got it mostly working, but tagged it WIP in the hopes someone can think of a better workaround to the issues I've described in the PR message:

https://github.com/CleverRaven/Cataclysm-DDA/pull/37454

**Comment by Night-Pryanik** [comment] 2021-04-10 17:17
@wapcaplet is this fixed by #37454?

**Comment by wapcaplet** [comment] 2021-04-10 21:46
@Night-Pryanik Yes, I believe it was. Thanks for bringing it to my attention. I tested it again in 0.E-10373 and can no longer reproduce it, so I am closing it now.

**Closed by wapcaplet** 2021-04-10 21:46 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Missions
