### ISSUE TITLE
Game crashes as i walk down hall in Lab

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#34996] opened 2019-10-24 12:46 UTC
# Describe the bug

I walk down a hall in the lab and I get a crash msg

# Steps To Reproduce

1. Walk down the hall to the right

# Expected behavior
Ideally, No crashing as I move around the Lab

# Versions and configuration
 - OS: Windows 10
 - Game Version: 
0.D-8761-g923c311 (Tiles)
 - Graphics version: 
Tiles
 - Mods loaded:
Dark days Ahead
Medieval and Historic Classes
More Survival Tools
Classic roguelike Classes
Stats Through Skills 
Vehicle Additions Pack
Tanks and other Vehicles
Boats
Folding parts pack
Filthy clothing
Makeshift Items Mod
Classes and Scenarios Mod
Mutant NPCS
Necromancy
Mythological Replicas
Magiclysm
Stats Through Kills
SpeedyDex
# Additional context
![Screenshot (1)](https://user-images.githubusercontent.com/31796878/67486174-8a937880-f639-11e9-9cee-aaaed5c8e76d.png)

**Comment by ZhilkinSerg** [comment] 2019-10-25 07:30
Duplicate of #34994

**Closed by ZhilkinSerg** 2019-10-25 07:30 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
