### ISSUE TITLE
Allow NPCs to guard a vehicle instead of the ground it is on

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#25395] opened 2018-09-06 06:50 UTC
**Is your feature request related to a problem? Please describe.**  
When you tell an NPC follower to guard a position inside a vehicle then start driving the vehicle, the NPC will try to stay in the position they were guarding on the map, ignoring the fact that they are in a moving vehicle. This usually results in damage to both NPC and vehicle. 

**Describe the solution you'd like**  
If an NPC is in a vehicle when you tell them to guard a position, they should stay in the vehicle when it is moving. 

**Describe alternatives you've considered**  
Another possibility is an option in the NPC menu to 'Guard this vehicle'. Maybe, that option would have them actually 'guard' the vehicle from attackers too, rather than them just standing there.

**Comment by AMurkin** [comment] 2018-09-06 07:00
Related or duplicate of #13782

**Closed** 2018-09-06 08:06 UTC
