### ISSUE TITLE
Initial Day setting does not stop evolution from occurring

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#31286] opened 2019-06-09 19:50 UTC
# Describe the bug
Zombies spawn evolved when initial day setting is advanced.

# Steps To Reproduce
1. Create a world where initial day is 999
2. See evolved zombies everywhere

# Expected behavior
That zombies do not evolve, but the date changes

# Screenshots
![image](https://user-images.githubusercontent.com/2125926/59163361-30e94200-8ace-11e9-8f12-2d960c2e220d.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4123-g37a6167 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]
# Additional context
Tested after looking at #31173

**Comment by l29ah** [comment] 2019-06-09 19:54
Yeah, if your scenario has a winter start, you're doomed because of all those monstrosities walking around.

**Comment by esotericist** [comment] 2019-06-10 17:13
Duplicate of #30224

**Closed** 2019-06-10 17:14 UTC
Labels: <Bug>, Time / Turns / Duration / Date
