### ISSUE TITLE
Bike Rack - Racking task failed

### ISSUE THREAD

**Issue by SpeedyDoggo** [CleverRaven/Cataclysm-DDA#53118] opened 2021-11-30 04:57 UTC
### Describe the bug

While trying to recreate [ #53066](https://github.com/CleverRaven/Cataclysm-DDA/issues/53066) to try and find a pattern, got this error while trying to load a swivel chair onto a very damaged cube van with a bike rack placed on the bottom left tile, and [I]gnoring all other distractions.

This is probably a really niche error but may as well document it. I can retrieve the exact status of the vehicle parts as needed; I'll be making a copy of this save before I keep testing.

### Steps to reproduce

1. Spawn cube van.
2. Install bike rack onto back left corner.
3. Go hit some stuff to heavily damage the vehicle.
4. Park the van within view of a zombie.
5. Attempt to load swivel chair onto a bike rack.
6. When the prompt to continue or stop the task with the zombie near, choose [I]gnore
7. Bug occurs and you can't mount the swivel chair onto the bike rack.

### Expected behavior

Expected to mount the swivel chair onto the bike rack, since the bike rack was still functional.

### Screenshots

![thatshimofficer](https://user-images.githubusercontent.com/18247905/143987755-60c94c3c-58f4-45df-9f4d-51047cdcef3d.PNG)
![poorfuck](https://user-images.githubusercontent.com/18247905/143987816-c7011b75-be1e-4b00-bf8a-82f47b800c58.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fa91686 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extra Mutated Scenarios [extra_mut_scens],
    Generic Guns [generic_guns],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

 DEBUG    : Racking task failed.  Parent-Vehicle:Cube Van; Found parts size:1

 FUNCTION : virtual void bikerack_racking_activity_actor::finish(player_activity&, Character&)
 FILE     : src/activity_actor.cpp
 LINE     : 1250
 VERSION  : fa91686
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7623004/debug.log)

**Comment by PatrikLundell** [comment] 2021-11-30 09:57
Have you checked whether the vehicle orientation has any effect? With non orthogonal orientations the weird morphing causes vehicle part locations to move around (not saying there's not a bug: I'm only looking for additional possible clues).

**Comment by wapcaplet** [comment] 2022-01-16 17:16
Closing as duplicate of #52079

**Closed by wapcaplet** 2022-01-16 17:16 UTC
Labels: <Bug>, (S3 - Duplicate), Vehicles
