### ISSUE TITLE
Input Handling - Conflict between mouse and keyboard

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62430] opened 2022-11-27 16:58 UTC
### Describe the bug

Mouse and keyboard input handling seem to be in conflict and mouse input handling overall seems overly sensitive.

User reports that moving the cursor w/ mouse and pressing a key to do an action such as examine the object fails to register the keypress.

User reports the game to be registering slight movements of his mouse due to typing etc.

User reports that moving the character with keyboard while moving the mouse causes very slow @ movement.

Confirmation by me that typing on an unstable surface will be enough to register the mouse movement. 

### Steps to reproduce

Ensure you have  the mouse cursor enabled. 
Enable edge scrolling if it is not - I am not sure if this is part of the bug or not, just part of a work-around I did some time ago and forgot about.

Move the mouse (keep your hand on it) and examine an item.
Jiggle your desk a bit as you type, etc.

### Expected behavior

Mouse movements that aren't enough to move to another tile should return asap and not poll so fast that they cause a system slowdown.

Keyboard input should not be blocked at all due to mouse input.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12406-gc7d375c903 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment] 2022-11-27 16:59
Looks like a duplicate of #61984

**Closed** 2022-11-27 17:17 UTC
Labels: (S1 - Need confirmation)
