### ISSUE TITLE
Inhaler starting empty for asthmatic characters

### ISSUE THREAD

**Issue by Guldane2** [CleverRaven/Cataclysm-DDA#41136] opened 2020-06-07 14:29 UTC
# Describe the bug

When creating a new character with asthmatic on build 10735, the inhaler they start with has 0/100 charges.

# Steps To Reproduce

1. Make a character with asthmatic
2. Check charges of inhaler

# Expected behavior

Asthmatic characters should start with a full inhaler

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2927-g08d6792 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi]
]

**Comment by anothersimulacrum** [comment] 2020-06-07 15:26
Duplicate of #40819

**Closed by anothersimulacrum** 2020-06-07 15:26 UTC
