### ISSUE TITLE
UNCANNY_DODGE + Spell Effect SEGFAULT

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66100] opened 2023-06-10 00:39 UTC
### Describe the bug

When the character has the uncanny dodge effect, such as through the BIOTEK attunement from Magiclysm, any spells that buff the character, such as restoration or ogre's strength, cause an immediate SEGFAULT.

### Attach save file

N/A

### Steps to reproduce

1. Install Magiclysm
2. Debug BIOTEK attunement with Mutation menu
3. Debug Ogre's Strength spell
4. Cast Spell, crash.

### Expected behavior

No SEGFAULT

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: f9dc830 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Magiclysm [magiclysm]
]

### Additional context

Even without the UNCANNY_DODGE flag enabled, the character still tries to dodge spell effects, visible via the dodge message as well as reduced stamina.  These don't cause SEGFAULTS, however, but the character shouldn't be dodging their own buff spells / effects.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11710836/crash.log)

**Comment by RenechCDDA** [comment] 2023-06-10 13:16
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/50f12c68-99ab-4d04-9a9d-7b766eeac4e8)

I get a feeling this is related :)

**Comment by RenechCDDA** [comment] 2023-07-06 07:51
Aight so, potential patch:
https://github.com/CleverRaven/Cataclysm-DDA/commit/8f65eadd7232225f898abed9d38a84a4788147b1

After this, it's still *literally dodging* the spell effect (moving!) your character, which seems to have been much of the root cause of the issue (tripoint is invalid because of order of function execution ---> creature_at returns nullptr ---> crash!).

Going to have to ask someone with a bigger brain than me how this should be fully resolved. Obviously, should not be dodging in response to self-buff spells. I also make no claim that this perfectly replicates old functionality. I don't work in the spells department(usually)!

**Comment by AmarinReyny** [comment] 2023-07-11 20:02
Until the proposed patch is finished and merged, would anyone happen to know if it's possible to make spells just ignore any possibility of dodging, to the point where uncanny dodge wouldn't even apply, through json editing?

**Comment by AmarinReyny** [comment] 2023-07-15 20:21
Has anyone notified @KorGgenT  about this? If not, I kinda feel like he should be aware.

**Comment by Dimasw99** [comment] 2023-07-16 11:37
I have the same issue with the enchanted parabolan wool blouse which also gives uncanny_dodge. The crash itself being triggered by a boomer exploding next to me.

**Comment by AmarinReyny** [comment] 2023-07-16 16:59
> I have the same issue with the enchanted parabolan wool blouse which also gives uncanny_dodge. The crash itself being triggered by a boomer exploding next to me.

I probably should have mentioned this before, but I've also been having the same issue with spells since updating to the latest (at the time) experimental from some 0.F about a week ago. I was going to try to test it with non-Magiclysm spells like monster attacks, as well as explosives, but it looks like you beat me to it with the former.

**Comment by deepvelocity** [comment] 2023-07-19 03:20
Same issue with boomers: when you kill boomer, he tries to explode and segfault happens.

**Comment by AmarinReyny** [comment] 2023-07-21 21:57
Has anyone been able to identify the change in code that made this bug happen in the first place? I mean, it seems pretty clear that _something_ has changed either how dodging works, how spells work, or both, that made it go from "dodging does not apply to spells" to "dodging does apply to spells," and did so in a way that doesn't functionally allow spells to be dodged, which is why the "conserve stamina" message appears when a character without Uncanny Dodge is targeted by a spell, and why the game crashes when a character _with_ Uncanny Dodge is targeted.

If someone can identify when and how that change happened, it would probably make solving this problem a lot easier.

**Comment by AmarinReyny** [comment] 2023-07-26 13:58
Is anyone actively working on this?

**Comment by deepvelocity** [comment] 2023-07-27 00:59
Looking into it now.

**Comment by AmarinReyny** [comment] 2023-07-27 01:02
> Looking into it now.

Excellent! Thank you.

**Comment by deepvelocity** [comment] 2023-07-27 04:54
WIP update:
It appears that the issue lies within **magic_spell_effect.cpp** ( cr->dodge_check( spell_accuracy ) )  https://github.com/CleverRaven/Cataclysm-DDA/blob/e30b6ef3eb73036df03c63cb972cc21981e0e9b9/src/magic_spell_effect.cpp#L546

This check is intended to reduce the damage dealt using spell accuracy as hit roll and dodge value as reduction modifier. I tried commenting out the portion of the code and no crash occurred. I assume it has something to do with the change of the position during code evaluation, which would explain why @RenechCDDA's fix worked.

**Comment by deepvelocity** [comment] 2023-07-27 05:16
I think there are two separate issues: 
1. Attempting to dodge a spell that cannot be dodged (e.g. some non-physical attack or a neutral/positive spell or an instant spell like boomer explosion). 
2. Adding effects to an actual target instead of a tripoint (needs more research, maybe there's a reason for this design). Currently, there are no moves involved in uncanny dodge, so this might lead to some weird behavior, so maybe we could just revert the calculation and invoke on_try_dodge() to consume stamina.

**Closed** 2023-07-30 17:24 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), (P2 - High), [C++], Mechanics: Enchantments / Spells, Help Wanted
