### ISSUE TITLE
You hurt your hands trying to smash the nothing.

### ISSUE THREAD

**Issue by friendfrog** [CleverRaven/Cataclysm-DDA#41620] opened 2020-06-27 00:22 UTC
# Describe the bug

With a fresh install of the latest experimental (10788) whenever I try smashing without gloves  I hurt my hands. The problem here is that whether I'm smashing roads or a wall or cars a message appears that says "You hurt your hands trying to smash the nothing."

Some objects such as large rocks, benches, cupboards, and lockers do correctly identify themselves but other objects such as walls, doors, roads, wooden floors, bushes, and trees are labeled as nothing.

# Steps To Reproduce

1. Create a new character
2. Try smashing the road, cars, walls, furniture, or other things that I haven't tried whacking.
3. Hurt yourself smashing nothing.

# Expected behavior

Whenever you smash things it should tell you what you are smashing.

# Screenshots
![Untitled](https://user-images.githubusercontent.com/55005591/85909493-19f7b980-b7cf-11ea-9e11-15f681354019.png)

# Versions and configuration

 - OS: Windows 10 Build 18362
 - Game Version: 0.E-3531-gff1ff7e
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC Needs

# Additional context

I checked in PRs and Issues before posting but there's a chance I've missed it, hope this helps!
It might be related to [ #40596](https://github.com/CleverRaven/Cataclysm-DDA/pull/40956) but I am not sure.

**Comment by ZhilkinSerg** [comment] 2020-06-27 06:17
Need to check if it would be fixed by #41280.

**Comment by Maleclypse** [comment] 2020-06-30 03:49
Possibly related you also hurt your hands when smashing things while wielding Stonefist's from Magiclysm.

**Comment by wapcaplet** [comment] 2021-02-14 00:59
Cannot reproduce in 0.E-9603-g42468f6cab. Smashing pavement, walls, furniture, and vehicles all give appropriate messages like "You kick down the pavement, smashing it." or "There's nothing there to smash!"

**Closed** 2021-02-14 01:00 UTC
Labels: <Bug>, Fields / Furniture / Terrain / Traps, Info / User Interface, [C++]
