### ISSUE TITLE
Dragging furniture is busted

### ISSUE THREAD

**Issue by mikt4743thesecond** [CleverRaven/Cataclysm-DDA#47339] opened 2021-02-08 17:26 UTC
# Describe the bug

Dragging furniture whenever moved says in the text box : The (furniture) you were moving is destroyed! and stops dragging it

# Steps To Reproduce

Drag a piece of furniture

# Expected behavior

You'd drag the furniture

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9526-g599c1ea-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Makeshift Items Mod [makeshift],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Night-Pryanik** [comment] 2021-02-08 17:58
Duplicate of #47304.

**Closed by Night-Pryanik** 2021-02-08 17:58 UTC
