### ISSUE TITLE
Cannot aim turret in remote-controlled vehicle

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#36574] opened 2019-12-30 20:53 UTC
# Describe the bug

When remote-controlling a simple single-tile vehicle with a mounted turret, selecting the (T) "Aim individual turret" command gives this error:

> An error has occurred! Written below is the error report:
> DEBUG : Tried to aim turret while outside vehicle
> FUNCTION : int draw_turret_aim(const player&, const catacurses::window&, int, const tripoint&)
> FILE : src/ranged.cpp
> LINE : 1083

I can recover from the error, but cannot aim the turret.

# Steps To Reproduce

1. Build a vehicle with "drive by wire controls", and a weapon mounted on a turret
2. Build "remote vehicle controls" and put a battery in them
3. Get in range, press `a` to activate remote vehicle controls, and control the vehicle
4. Select `^` then `T` to aim the turret

# Expected behavior

Turret can be aimed with remote control, the same as if I were in the vehicle.

# Screenshots

Remote vehicle is a single tile with this configuration:

![image](https://user-images.githubusercontent.com/238395/71599990-6efd9000-2b0a-11ea-9364-e7585e66ffdb.png)

![image](https://user-images.githubusercontent.com/238395/71600248-5fcb1200-2b0b-11ea-9fda-b1fd12140dbe.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-10780-ga7409c5a0b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DinoMod [DinoMod],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Mythical Martial Arts [MMA],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    More Survival Tools [More_Survival_Tools]
]

# Additional context

I have several world mods enabled, but I think all the components here are from the base game. Remote vehicle controller and drive by wire controls were learned from regular skill leveling, not from a book. Piloting the vehicle remotely works as expected.

**Comment by Night-Pryanik** [comment] 2019-12-31 04:15
Duplicate of #23902.

**Closed by Night-Pryanik** 2019-12-31 04:15 UTC
