### ISSUE TITLE
NPC seems to slow down reading/crafting

### ISSUE THREAD

**Issue by JohnnyRocketFingers** [CleverRaven/Cataclysm-DDA#22345] opened 2017-11-04 07:01 UTC
Game version: 0.C-24810-g7e56bbe

Operating system: Windows 7

Tiles or curses: NPC seems to slow down reading/crafting

Mods active:
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Bionics Systems Mod
Craftable Gun Pack
Generic Guns
Makeshift Items Mod
More Survival Tools
More Buildings
Boats
Vehicle Additions Pack
Tanks and Other Vehicles
Necromancy

### Expected behavior
Normal/quick time progression while reading or crafting.

### Actual behavior
When npc is awake, reading and crafting take quite a while to complete , about 10x slower on my pc.
When npc is sleeping speeds go back to normal.
Restarting the game brings things back to normal for a while.

### Steps to reproduce the behavior
I have an NPC with me in a closed room inside a mansion , if they are awake and idle reading and crafting take much longer to complete.

**Comment by Coolthulhu** [comment] 2017-11-04 14:43
Does the NPC have item pickup enabled? It's notoriously slow at the moment, because the NPCs scan their surroundings literally every turn.

**Comment by JohnnyRocketFingers** [comment] 2017-11-04 15:40
yes , and ive got a metric ton of items in that room. When it happens again ill turn off autopickup and see if that is the issue.

**Comment by JohnnyRocketFingers** [comment] 2017-11-06 21:20
Yeah that seems to be the cause , after disabling item pickup there is no more slowdown.

**Comment by BrettDong** [comment] 2017-11-07 10:15
Probably a duplicate of #19240.

**Closed** 2019-09-10 20:20 UTC
Labels: Code: Performance, NPC / Factions
