### ISSUE TITLE
Scalpel "sheath"

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36782] opened 2020-01-07 11:39 UTC
There are many sheathes and holsters to keep vital tools at hand, but nothing for the scalpel which I ALWAYS forget to bring with me after dumping loot.

I don't entirely understand how the holster system works, but no current sheathes work. I imagine I would just keep it in a pocket protector like thing and clip it to my bag/coat in the Cataclysm, but any wearable "sheath" for the scalpel would be greatly appreciated.

**Comment by Amoebka** [comment] 2020-01-07 12:41
Sheathes serve two purposes: allowing you to quickly draw a blade and saving on inventory volume. Neither is needed for scalpels - they take up 0.01 L and you never care about drawing them because they are worse weapons than plain fists.
"I forget to bring it along" is really more of an issue with your memory/attention than with the game. I doubt a lot of other players would use a scalpel sheath over more generally useful strapped leg accessories. For every item in the game you can find a player who forgets to bring it with them, that doesn't imply we should have a 100 different sheathes for every possible item.
And, of course, scalpel sheathes don't exactly exist IRL for obvious reasons.

**Comment by glenmack** [comment] 2020-01-07 13:54
The point never was to use it as a weapon, and stuff like the thing I am suggesting already exists in the game. e.g. The survivor utility belt. It's not about memory, it's about ease of use, for a tool with only one use.

Scalpel sheathes don't exist IRL because people don't have to field dissect corpses on a regular basis to find CBMs. Don't conflate IRL needs with Cataclysm related needs.

**Comment by Brian-Otten** [comment] 2020-01-07 17:08
Perhaps use the favorite item function on the scalpel to not dump it so easily? Get the "scalpel" cbm  so its built in to your body? Accept the lower dissecting value that comes from your sheathed knife you do have on you? I feel like a scalpel sheath is the wrong solution to the "forgetting my scalpel" problem.

**Comment by Kilvoctu** [comment] 2020-01-07 17:20
> I don't entirely understand how the holster system works, but no current sheathes work. I imagine I would just keep it in a pocket protector like thing and clip it to my bag/coat in the Cataclysm, but any wearable "sheath" for the scalpel would be greatly appreciated.

Scalpel doesn't have the flag `"SHEATH_KNIFE"`, so it can't be sheathed. Even so, I believe it's too small, as every sheath I know of has a minimum volume limit of .25 L.

> Accept the lower dissecting value that comes from your sheathed knife you do have on you? 

If only an X-Acto knife could be sheathed... Quite unusual considering it's a "knife" and unusually large at .25 L.

**Comment by glenmack** [comment] 2020-01-07 17:59
> Perhaps use the favorite item function on the scalpel to not dump it so easily? Get the "scalpel" cbm so its built in to your body? Accept the lower dissecting value that comes from your sheathed knife you do have on you? I feel like a scalpel sheath is the wrong solution to the "forgetting my scalpel" problem.

1. I'm halfway through a Central lab, have killed 179 scientists, have dissected most of them with a scalpel, and have seen 0. Auto scalpels so hardly a reliable solution.
2. CBM removal is utterly ridiculously dependent on maximising your numbers and tool value is a huge part of that, so no you shouldn't use anything but a scalpel if you access to one.

Why can no-one see the god damn quotes around sheath? Do you not get that I just mean wearable scalpel? I thought sheathe might be easier for people to understand and others might find more use out of being able to remove it from the clothing. Adding to favorites is broken and does not prevent dropping or items being used in crafting.

**Comment by Kilvoctu** [comment] 2020-01-07 18:23
> Why can no-one see the god damn quotes around sheath? Do you not get that I just mean wearable scalpel? I thought sheathe might be easier for people to understand and others might find more use out of being able to remove it from the clothing.

I agreed enough to mod in this functionality to my game via a new item, but I guess I'm "no-one". :man_shrugging: 
![test](https://user-images.githubusercontent.com/2993060/71918639-56aff580-3148-11ea-9180-f4be31aefa91.png)

**Comment by glenmack** [comment] 2020-01-07 18:32
> > Why can no-one see the god damn quotes around sheath? Do you not get that I just mean wearable scalpel? I thought sheathe might be easier for people to understand and others might find more use out of being able to remove it from the clothing.
> 
> I agreed enough to mod in this functionality to my game via a new item, but I guess I'm "no-one". 🤷‍♂
> ![test](https://user-images.githubusercontent.com/2993060/71918639-56aff580-3148-11ea-9180-f4be31aefa91.png)

You didn't actually say you agreed, you just poited out that the sheathes didn't work, which also wasn't entirely the point, and people seem to be getting hung up on it.

**Comment by Kilvoctu** [comment] 2020-01-07 18:41
No need to quote me. I know what I said.

My first post was providing a solution to the issue. You need to add `"sheath_knife"` flag to the scalpel. You will then need to make it sheathable in a practical sense by either making an item that it can fit in (as I did), or bringing it up to the standard knife size of 250 ml.
One may infer that I agreed with the proposition because that was the primary reason I took the time to find out the cause and solution to the topic, as opposed to doing nothing and ignoring this thread.

**Comment by glenmack** [comment] 2020-01-07 19:22
If your first post was a solution, then so was my OP. I outlined the fact that scalpels didn't work with sheathes, and even though I know that the tag would be required, there are certain fields within the holster JSON I don't understand, and honestly, I don't think a sheath is the right option anyway. A craftable armor item with 0 coverage on an outer layer, with the scalpel cutting quality is highly preferable. Something like a plastic chunk, plus hairpin, plus scalpel. Give it scalpel properties and done.

**Comment by Brian-Otten** [comment] 2020-01-07 22:51
Yes you could trivially make a wearable scalpel, but then you start to wonder why we don't have wearable toolboxes, drills, lockpicks, bandages, etc. Inventory management is a part of cataclysm, and making everything wearable for possible convenience reasons would bloat the crafting menus / item lists. Modding it in because you want it yourself is as always perfectly viable and a great idea if it enhances your fun. Having a mod in the launcher which adds more wearable tools would also be great. But i feel it's place is not merged with the main branch.

**Comment by glenmack** [comment] 2020-01-08 09:13
> Yes you could trivially make a wearable scalpel, but then you start to wonder why we don't have wearable toolboxes, drills, lockpicks, bandages, etc. Inventory management is a part of cataclysm, and making everything wearable for possible convenience reasons would bloat the crafting menus / item lists. Modding it in because you want it yourself is as always perfectly viable and a great idea if it enhances your fun. Having a mod in the launcher which adds more wearable tools would also be great. But i feel its place is not merged with the main branch.

We do have have a wearable toolbox... It's the survivor utility belt. I think there absolutely should be a hiking pack version with a toolbox, scalpel, and other useful tools, but not consumables, built in, but with less storage volume (amounting to the volume of the tools). Until such time as the inventory system has a pocket or container system that works, which I don't see happening ever, these are the compromises. The reason Vormithrax crafts a utility belt on almost every single run, is because he doesn't want to have to think "where are my tools" much as I don't want to think "where is my scalpel". So he can concentrate on tactical movement and other important stuff. He's already made the decision to carry that weight and encumbrance, so now he can concentrate on what to do with his remaining volume and weight capacity.

There is no functional difference in inventory management between having a toolbox in a backpack and using the rest of the space vs. having a toolbox being built into a backpack and using the space in a backpack minus the volume of a toolbox. You know what the difference is?

Keystrokes.

If you are carrying something, drop a backpack to fight, you have to go through the extra step of picking up everything you dropped. If the tools are built in and your inventory is otherwise empty, you can just wear the backpack straight from the ground.

The crafting menu is already bloated with lots of stuff that has no practical use. Unitards AND Leotards? Manganese dioxide? Horse rain sheet? I could go on for HOURS. What are these things doing in the main branch? Nothing. No one crafts 90% of the craftable items except MAYBE as a stepping stone for bootstrapping skills. Your arguments make no sense. I could pear down the entire crafting menu to the 50 items and weapons that everyone actually uses, plus an item in each skill that confers skill ups for every level. That's all the game NEEDS. Right? According to you.

**Comment by TechyBen** [comment] 2020-01-08 13:37
> Yes you could trivially make a wearable scalpel, but then you start to wonder why we don't have wearable toolboxes, drills, lockpicks, bandages, etc. Inventory management is a part of cataclysm, and making everything wearable for possible convenience reasons would bloat the crafting menus / item lists. Modding it in because you want it yourself is as always perfectly viable and a great idea if it enhances your fun. Having a mod in the launcher which adds more wearable tools would also be great. But i feel its place is not merged with the main branch.

If I ever get the time to get back into modding... this is a partially j/k mod I have an idea for. Steampunk makeshift power armor all the way! :D

**Comment by anothersimulacrum** [comment] 2020-01-08 14:42
I think you should learn how to use the favorite system to have loadout of items you always keep on you.

**Comment by I-am-Erk** [comment] 2020-01-08 15:06
I'm going to close this, because it really isn't something we need in mainline, and it's going to be solved in a bit when we have nested containers anyway. Glenmack, I'd suggest taking criticism with less intensity. It's a collaborative project, people have to discuss things for it to work.

**Closed by I-am-Erk** 2020-01-08 15:06 UTC
Labels: <Suggestion / Discussion>, Items / Item Actions / Item Qualities

**Comment by Ezsk** [comment] 2020-01-08 21:28
I'm not dislike his passion for the scalpel though.
