### ISSUE TITLE
Item disappears when inserted into container which does not have space for the extra volume.

### ISSUE THREAD

**Issue by Erozaxx** [CleverRaven/Cataclysm-DDA#40133] opened 2020-05-04 10:46 UTC
Game version: 0E-1726-g0c4d9b2 (tiles)

Build: 10621

Operating system: Win10 (64 bit)

Tiles or curses: UNDEAD_PEOPLE

Mods active: DDA, Disable NPC Needs, Rural-Onlky Mapgen, No Rail stations, No Fungal Monsters, SpeedyDex

### Expected behavior
The item of certain volume is either inserted into container, or player is informed, container is full and would not fit the extra volume.

### Actual behavior
The item disappears.

### Steps to reproduce the behavior
1: Have item with higher volume than free volume in a partially filled backpack container
2: Open inventory and select backpack
3: Hit "i" and choose the item with volume higher, than the remaining space in backpack container
4: Check inventory - item is not in container and has dissapeared
5: Check advanced inventory with [A] to see if it lays somewhere around - negative
6: Check "wore" items if it was equipped instead - negative
[Heavenlands.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4574135/Heavenlands.zip)

**Comment by Erozaxx** [comment] 2020-05-04 11:09
I am sorry, I did not find how to properly tag the issue with the appropirate tags. It's my first issue openned on GitHub

**Comment by Erozaxx** [comment] 2020-05-04 13:01
Ok, so the root cause is not probably unwielding of the item - I am renaming the main issue and I think, it could be related to this issue: [https://github.com/CleverRaven/Cataclysm-DDA/issues/40115#issue-611541832]

The root-cause is, that I am trying to insert the Duffelbag with some items into the Backpack, which does not have anymore space for the volume.  There is no message I can't insert the Duffelbag anymore and the Duffelbag disappears even when empty.

I've tested that with also quarterstaff - and that one disappears too, so there is no relevance what is the inserted item.

**Comment by KorGgenT** [comment] 2020-05-04 13:21
Duplicate of #40115

**Closed by KorGgenT** 2020-05-04 13:21 UTC
