### ISSUE TITLE
You can not sit comfortable in a pristine bucket seat, while beeing naked and only 175cm tall (standart heigh)

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#74825] opened 2024-06-28 21:13 UTC
### Describe the bug

You can not sit comfortable in a pristine bucket seat, while beeing naked and only 175cm tall (standart heigh).

### Attach save file

[Vampire-trimmed.tar.gz](https://github.com/user-attachments/files/16036776/Vampire-trimmed.tar.gz)

### Steps to reproduce

-find the scrapper in the junkyard
-use the fridge to not be seen, while stealing all the missing verhicel parts then install them
-then go into the pristine bucket seat completely naked, while beeing also only 175cm tall
- see that you are in a cramped space now

### Expected behavior

not beeing in a cramped space, while beeing completely naked, 175cm tall on a pristine bucket seat. ^-^

### Screenshots

![Screenshot 2024-06-28 225530](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/b24d6a70-882d-439c-889f-8ed85773234b)
![Screenshot 2024-06-28 225614](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/e5efeb0b-72bc-4f28-a94f-d61410198871)
![Screenshot 2024-06-28 225640](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/a23ca2bf-58fd-4d4e-839a-3b7181c2f001)
![Screenshot 2024-06-28 225712](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/f48a3dae-3cf1-4eb2-9f24-e4bb413c5809)

### Versions and configuration

WIndows 11, 64bit
Game version: Experimental Build 2024-06-26-1623
mods; Xedra evolved, Dark days ahead

**Comment by PatrikLundell** [comment] 2024-06-29 07:29
Yes, the functionality doesn't work in any useful way.
This is just a less severe case than #74560 and others.

Note that it seems the functionality doesn't only depend on the tile you're in, but also what's on the surrounding tiles. I suspect your bucket seat might not be cramped on a bike.

**Comment by fairyarmadillo** [comment] 2024-06-29 22:58
Unless Renech changed something, the seat looks for a single unroofed adjacent accessible tile, and if it finds one, gives a small bonus to capacity.

The system originally didn't try to calculate volume by height or worn equipment, it just went by creature size. That was working fine for months. The recent changes to calculate volume made everyone functionally way bigger without increasing vehicle part capacity. Bumping everything up by 10 or 20 liters across the board will probably be enough to make it work properly again.

**Comment by PatrikLundell** [comment] 2024-06-30 10:50
It makes little sense that the middle seat in a row of three would be more cramped than the ones to either side when the seats are identical (in real life, some cars have a smaller space in the middle of the back seat, and the legs may have to deal with a tunnel, but the game does not model these things, and larger vehicles may not have either of those issues at all. The idea that you'd somehow get more space if the door doesn't have a roof is just plain silly.

In order to model room based on available headroom you'd have to have the game model headroom, so a prison bus (that's inoperable by standard size completely naked people) should have enough head room to stand in the aisle (and the same headroom over the driver's seat), while an original VW beetle would not provide much wriggle room, but there's nothing in the game providing that kind of information. The only information you have is the kind of seat (and they're not really a size selection), the dimensions of the vehicle, and whether it has a roof over the driver's seat or not.

And note that this report is a duplicate.

**Comment by fairyarmadillo** [comment] 2024-06-30 14:03
> It makes little sense that the middle seat in a row of three would be more cramped than the ones to either side when the seats are identical 

It isn't. There's only more room in the driver's seat if the adjacent door is open, as the character can stick their head out that way. Clearly this is too confusing and should be axed.

As for headroom in the tile itself, a "high roof" vehicle part has been proposed many times, for vehicles like buses, semi trailers, and others, and could count as being unroofed for capacity's sake. IMO the high roof should weigh more and require a standard or heavy duty frame, so that people aren't just slapping it on every vehicle for convenience's sake.

**Comment by KeremBabaG** [comment] 2024-06-30 15:37
is it absolutely imperative that we keep this stupid vehicle volume mechanic in the game
it worked perfectly when it considered just the creature size

**Comment by fairyarmadillo** [comment] 2024-06-30 17:20
Calling somebody's hard work stupid isn't going to motivate anyone to fix it, and it's always better to have a better simulation.

That said I think it should go back to the old method if #74348 isn't going to get merged.

**Comment by NetSysFire** [comment] 2024-06-30 19:12
Closing as duplicate of #74560.

**Closed by NetSysFire** 2024-06-30 19:12 UTC
Labels: (S1 - Need confirmation)
