### ISSUE TITLE
 Mind splicer kit fails to copy data into data card

### ISSUE THREAD

**Issue by ConnorMartin** [CleverRaven/Cataclysm-DDA#41879] opened 2020-07-05 22:34 UTC
# Describe the bug

Mind splicer kit fails to copy data into data card

# Steps To Reproduce

Use mind splicer kit on desiccated corpse, selecting a data card as the recipient.
Check inventory for data card (with memory data)

# Expected behavior

The mind splicer kit should correctly copy data into the data card.

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

# Additional context

I grabbed the dessicated corpse and moved it to a safer place before using the kit.

**Comment by hexagonrecursion** [comment] 2020-07-06 04:33
Duplicate of #41226

**Closed** 2020-07-06 05:17 UTC
