### ISSUE TITLE
Unloaded wielded minireactor for ~500 fuel cells

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#46103] opened 2020-12-17 19:09 UTC
# Describe the bug
Wanted to install minireactor on a car. It was impossible, figured out I need to unload it even more (used 'd' previously on the car that contained it).
After wielding minirector, entering its view and using U, it dropped 462 plutonium fuel cells.

# Steps To Reproduce

Have minireactor with less than 500 charges, wield it, enter it, use `U`nload.

# Expected behavior

a) install items with pockets/magazines without losing their content.
b) option to somehow get rid of remnants of charges in minireactor.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/102531881-63043880-40a3-11eb-9539-04fe4edec8a4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8193-g93bf48b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by anothersimulacrum** [comment] 2020-12-17 19:22
Duplicate of #44150

**Closed by anothersimulacrum** 2020-12-17 19:22 UTC
Labels: (S3 - Duplicate)
