### ISSUE TITLE
Unable to trade with NPCs (imaginary debt?)

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18893] opened 2016-10-18 23:33 UTC
Tested in Windows graphical build 4656. It seems the trade window is not functioning. I marked items for trading, both mine and the NPC's, but instead attempting to trade generates this message:

![trade fail](https://cloud.githubusercontent.com/assets/22048567/19500274/373cfe7c-9561-11e6-8a23-71d54e9fa1a0.png)

In this example I am outright attempting to give the NPC a cash card that is well over the claimed debt. This behavior occurred both before and after recruiting them as a companion.

Edit, testing with a fresh starter NPC worked without issue. Some part of taking on a mission causes this. I can confirm that asking for an item reward is not the cause, as I asked for trading. My next test will be whether asking for a reward at all is the cause.

Edit, asked for an item reward and it did not seem to cause it. I am unsure of the cause now.

**Comment by Nernums** [comment] 2016-10-21 00:06
had you asked for an item for free? sorry wish I could be of more help, i've had odd issues before too with npc trading but no idea the cause.

**Comment by DangerNoodle** [comment] 2016-10-21 02:40
I have tried both asking for an item as a reward, and during the mission acceptance. I am uncertain yet where the problem starts. Recruitment might also be a factor.

**Comment by Ads333** [comment] 2016-10-28 22:32
I'm having this issue too

**Comment by DangerNoodle** [comment] 2016-10-28 23:10
So other interactions that affect NPC debt can eventually normalize this. Maybe some element of "indebted to NPC" interferes with the trade screen?

**Comment by Leland** [comment] 2017-08-24 03:21
This was experienced with the Refugee Center merchant in #20849

**Comment by pjf** [comment] 2019-08-11 15:31
The trade code has had a lot of changes since this bug was reported, and in particular the debt handling is refactored in #33137 to be more visible to the player, so I think we might be able to close this one.

**Comment by Night-Pryanik** [comment] 2019-08-18 20:41
Ok, closing until confirmed.

**Closed** 2019-08-18 20:41 UTC
Labels: (S2 - Confirmed), <Bug>, Missions, NPC / Factions
