### ISSUE TITLE
refugee center outpost mission to collect 25 blankets does not accept variations (ex floral blanket)

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#77907] opened 2024-11-16 10:39 UTC
### Describe the bug

refugee center outpost mission to collect 25 blankets does not accept variations (ex floral blanket)

### Attach save file

[Anion Bridge-trimmed.tar.gz](https://github.com/user-attachments/files/17784292/Anion.Bridge-trimmed.tar.gz)

### Steps to reproduce

try to turn in 25 floral blankets, be refused.

### Expected behavior

the mission accepting any blanket. (except emergency blankets?)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: cdda-experimental-2024-11-15-0512 0f2c155 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Bionic Professions [package_bionic_professions]
]

**Comment by ampersand55** [comment] 2024-11-16 13:26
Wasn't this fixed by #75631?

**Comment by xcdxbaxa9** [comment] 2024-11-16 13:47
Seems to work fine. You have to actually have items in your inventory.
However not all types of blankets are being checked in the condition.

**Comment by xcdxbaxa9** [comment] 2024-11-16 13:59
The problem is that you can't actually take that many blankets in your inventory and condition seems to check only items in it.
Also not all types of blankets are being checked in the condition, for example emergency blankets and grass blankets would not work.
If you enable debug and take blankets in your inventory then mission passes.

**Comment by xcdxbaxa9** [comment] 2024-11-24 12:32
This issue has been resolved by #77791

**Closed** 2024-11-24 12:33 UTC
Labels: <Bug>, (S1 - Need confirmation), [JSON], Missions
