### ISSUE TITLE
Missing definitions of Power Armor helmets

### ISSUE THREAD

**Issue by NoddingCrow** [CleverRaven/Cataclysm-DDA#49895] opened 2021-07-12 21:18 UTC
### Describe the bug

When attempting to pick up, look-at, or highlight in any menu (including debug) a power armor helmet, the following error is thrown:

> DEBUG    : Missing item definition: power_armor_helmet_light_on
> 
>  FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
>  FILE     : src/item_factory.cpp
>  LINE     : 1571
>  VERSION  : fec9886

with corresponding definitions for helmet / helmet_heavy as expected. 
In the debug menu, the same error is thrown hovering over any of the 'on' state power armor pieces too, hilariously including lines like:

> DEBUG    : Missing item definition: power_armor_light_on_on

It would seem the relevant code is simply tacking '_on' to the string in question without any safeties for catching items like helmets that do not have an on state, or are already on.

This error can be safely ignored with no further issues presenting, but has been raised to my attention on the discord by a couple new players now.

### Steps To Reproduce

Using the debug spawn menu, hover over any power armor helmet. 
Spawn in said helmet, then try to pick it up.
Look at said helmet in the shift-V items panel. 

### Expected behavior

Attempting to look at helmets does not throw errors that confuse new players.

### Screenshots

![image](https://user-images.githubusercontent.com/77363578/125355356-d382e780-e35c-11eb-9e3a-a51eda91f026.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: fec9886 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by anothersimulacrum** [comment] 2021-07-12 21:29
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/49894

**Comment by anothersimulacrum** [comment] 2021-07-12 21:30
(I know it's helmets and not power armor, but I would be shocked if it's a different bug)

**Closed by anothersimulacrum** 2021-07-12 21:29 UTC
Labels: (S3 - Duplicate)
