### ISSUE TITLE
won't let me start the game

### ISSUE THREAD

**Issue by evilhlib** [CleverRaven/Cataclysm-DDA#71516] opened 2024-02-05 01:58 UTC
### Describe the bug

game displays an error message upon me starting the game, hitting space bar to continue sends me back to the main menu

### Attach save file

can't provide a save file since i didnt start playing

### Steps to reproduce

1. start the game
2. hit "tutorial"

### Expected behavior

i expected my game to launch

### Versions and configuration

version 0.G gaiman

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14159522/debug.log)

**Comment by RenechCDDA** [comment] 2024-02-05 02:02
Duplicate of #61095

Windows 7 is end-of-life and has been for four full years at this point. The MSVC version should still work for you, but for a lot of reasons I would recommend you upgrade to a modern OS.

**Closed by RenechCDDA** 2024-02-05 02:02 UTC
Labels: (S1 - Need confirmation)
