### ISSUE TITLE
When changing the game language, only some lines change

### ISSUE THREAD

**Issue by TheLightTwist** [CleverRaven/Cataclysm-DDA#45238] opened 2020-11-04 10:01 UTC
Game version: 0.E-2

Operating system: Win 10 ver. 2004

Tiles or curses: Tiles

Mods active: none

### Expected behavior
Almost the entire text (at least for the Russian language) should become translated
### Actual behavior
![image](https://user-images.githubusercontent.com/63810245/98096919-f804f680-1e94-11eb-93e5-89771689cdf5.png)
![image](https://user-images.githubusercontent.com/63810245/98096985-09e69980-1e95-11eb-8a95-fb05fcb646a1.png)

When selecting any language (including the system language) other than English, not the entire text changes, but only some parts.
MOTD and Title change.
Also, when you create a character, in the last menu (where you enter a name), when you press a button for random generation, the generated names also come out translated.
All other text is NOT changed, i.e. the text in the main menu, in the settings, during the game in all windows.
Also, when the \lang directory is completely deleted, the language is still English, but the language of the randomly generated character names remains according to the settings (i.e. the names are generated translated). MOTD and Title also remain translated.

### Steps to reproduce the behavior

1. Install any Russian language with variation for the country in Windows language settings (i.e. there is "Russian", "Russian (Ukraine)", "Russian (Kazakhstan)" - install any Russian with text in brackets);
2. Make this installed "Russian (anything)" your system language (or move to the top of the list if you have more than one language installed);
3. After starting the game, you will get a similar problem.

Accordingly, to solve the problem, it is necessary that your system language is ordinary Russian (WITHOUT brackets text).
The problem is NOT affected by:

- the number of installed languages;
- presence/absence of ordinary Russian in the system if this language is not selected as the system language;
- the country of the language you have chosen as the system language (i.e., the problem will be with both the system language "Russian (Ukraine)" and "Russian (Kazakhstan/Belarus, etc.)")

The problem arises on both a stable release and an experimental one (both x86 and x64)

**Comment by ZhilkinSerg** [comment] 2020-11-04 12:57
Do not delete lang subdir - translations are there.

**Comment by TheLightTwist** [comment] 2020-11-04 15:41
> Do not delete lang subdir - translations are there.

I am aware of this, I deleted this section to check the reaction of the game.
Ideally, the game when you delete the section \lang should become fully English, but for some reason the character names continue to be generated in Russian (if you choose Russian in the settings), perhaps because the name lines are in a different place.

**Comment by TheLightTwist** [comment] 2020-11-04 16:20
By the way, I found a person with the same problem. He did, however, have it under Linux.
https://www.linux.org.ru/forum/games/12726445

**Comment by TheLightTwist** [comment] 2020-11-04 18:41
The problem was solved and a way of its reproduction was found (however, testing was conducted only with Russian and English languages):

1) Install any Russian language with variation for the country in Windows language settings (i.e. there is "Russian", "Russian (Ukraine)", "Russian (Kazakhstan)" - install any Russian with text in brackets);
2) Make this installed "Russian (anything)" your system language (or move to the top of the list if you have more than one language installed);
3) After starting the game, you will get a similar problem.

Accordingly, to solve the problem, it is necessary that your system language is ordinary Russian (WITHOUT brackets text).
The problem is NOT affected by:
the number of installed languages;
presence/absence of ordinary Russian in the system if this language is not selected as the system language;
the country of the language you have chosen as the system language (i.e., the problem will be with both the system language "Russian (Ukraine)" and "Russian (Kazakhstan/Belarus, etc.)")

Soon, I will have access to another device on Windows 10, as well as on Windows 7, and I will try to reproduce the problem on them.

Two images showing the correct and wrong order:

Correct
![Верно](https://user-images.githubusercontent.com/63810245/98154709-d9771d80-1edd-11eb-8552-a2e086a412b8.jpg)

Wrong:
![Неверно](https://user-images.githubusercontent.com/63810245/98154812-01ff1780-1ede-11eb-868e-5a84c6f805da.jpg)

**Comment by TheLightTwist** [comment] 2020-11-04 18:42
It is better to wait for a response from the developers, and then close.

**Comment by ZhilkinSerg** [comment] 2020-11-04 18:54
Select translation language explicitly in game settings instead of using "System" language.

![image](https://user-images.githubusercontent.com/16213433/98155921-16481200-1ee8-11eb-8da9-9a4f751677cf.png)

![image](https://user-images.githubusercontent.com/16213433/98156041-47c0dd80-1ee8-11eb-8064-365ecc311715.png)

Obviously if you are using "Russian (Ukraine)" language - translation for it won't be found as there is only "Russian" translation.

**Comment by TheLightTwist** [comment] 2020-11-04 21:13
@ZhilkinSerg It seems that you have misunderstood me.
I already tried to change the language settings in the game, but no matter which language I chose, only the MOTD and Title languages changed. That is, the localization did not work for all languages at all, not just for Russian. After changing the system language, strange as it may seem, the localization changed not only for Russian, but for all languages as well.

**Comment by Aivean** [comment] 2020-11-05 16:47
Can you please try to reproduce this in the latest experimental build?

**Comment by TheLightTwist** [comment] 2020-11-05 19:18
@Aivean
Yes, the problem is also present in the experimental build (0.E-7347-g20d1078)
All languages have a problem, Chinese is selected in the screenshot:
![image](https://user-images.githubusercontent.com/63810245/98286110-29bcb100-1fac-11eb-9429-77493ba53c63.png)

**Comment by Aivean** [comment] 2020-11-05 19:40
Weird, seems to be platform-specific issue, I cannot reproduce it on mac:
![language](https://user-images.githubusercontent.com/2865203/98288361-978cbc80-1f5b-11eb-856b-d63b845315d4.gif)

**Comment by jbytheway** [comment] 2020-11-21 15:59
@TheLightTwist can you please post the contents of your `debug.log` when launching the game in one language setting that works and another that doesn't?  Some of the things that might go wrong here would lead to error messages in the log.

**Comment by TheLightTwist** [comment] 2020-11-21 17:17
@jbytheway 
Sure!
Here they are
[fine.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5578051/fine.log)
[error.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5578052/error.log)

**Comment by jbytheway** [comment] 2020-11-21 20:30
That's odd.  Your logs don't have a `[translations] C locale set to ` message, which should come right after the `Language is set to: ` message.  I can't see how you could get one without the other...

**Comment by Aivean** [comment] 2020-11-21 23:32
> That's odd. Your logs don't have a `[translations] C locale set to ` message, which should come right after the `Language is set to: ` message. I can't see how you could get one without the other...

Perhaps `_WIN32` is not defined for some reason?

**Comment by jbytheway** [comment] 2020-11-22 14:53
@TheLightTwist did you compile the code yourself, or use the Windows release binaries?  If the former, what environment did you use?

**Comment by TheLightTwist** [comment] 2020-11-23 12:38
@jbytheway 

> Windows release binaries

**Comment by int-ua** [comment] 2021-01-14 02:29
Not all translations are stored in the `lang` folder, look at `data/names` for example. Also I have this [slightly outdated] script that I usually run after downloading a new version, it might help:

```sh
#TODO! tar exclude

rm -r cataclysmdda-0.E/lang/
rm -r cataclysmdda-0.E/data/title/
rm -r cataclysmdda-0.E/data/sound/
rm -r cataclysmdda-0.E/data/motd/
rm -r cataclysmdda-0.E/data/xdg/
# No_NPC_Food, No_Fungi, dda, Only_Wildlife
find cataclysmdda-0.E/data/mods/ -maxdepth 1 -type d ! -name "mods" ! -name "dda" ! -name "No_NPC_Food" ! -name "No_Fungi" ! -name "Only_Wildlife" -exec rm -r "{}" \;

find cataclysmdda-0.E/gfx/ -maxdepth 1 -type d ! -name "gfx" -exec rm -r "{}" \;

rm -r cataclysmdda-0.E/doc/
rm cataclysmdda-0.E/cataclysm-launcher
rm cataclysmdda-0.E/README.md
rm cataclysmdda-0.E/data/*.txt
rm cataclysmdda-0.E/*.txt
rm cataclysmdda-0.E/*.cgi
rm cataclysmdda-0.E/data/cataicon.ico

shopt -s extglob
rm cataclysmdda-0.E/data/names/!(en.*)
rm cataclysmdda-0.E/data/credits/!(en.*)
# rm -r cataclysmdda-0.E/gfx/!(ChestHole*)Tileset*
shopt -u extglob

mkdir cataclysmdda-0.E/config
ln -s /dev/null cataclysmdda-0.E/config/debug.log
ln -s /dev/null cataclysmdda-0.E/config/crash.log
```

**Comment by int-ua** [comment] 2021-01-14 02:35
Please update the main description to better reflect current status.

**Comment by TheLightTwist** [comment] 2021-01-14 21:10
> Please update the main description to better reflect current status.

Updated as much as I could and understood

**Comment by int-ua** [comment] 2021-01-14 22:53
I've just unpacked latest experimental and not all folders from the` lang` directory are available for selection in the game. And I don't see a pattern yet.

**Comment by BrettDong** [comment] 2021-01-18 07:00
Don't know if this is related but I want to post it there: I was reading _Microsoft Windows Language Code Identifier Reference_, and found that **Russian (Russia)** has LCID `0x0x419`, but other variants like **Russian (Belarus)**, **Russian (Kazakhstan)**, **Russian (Kyrgyzstan)**, **Russian (Ukraine)** are recently added in Windows 10 and they do not have a valid LCID, i.e. they are assigned to a dummy LCID `0x1000`.

**Comment by zimojiang-qitian** [comment] 2021-02-20 11:21
> 很奇怪，似乎是特定于平台的问题，我无法在Mac上重现它：
> ![语言](https://user-images.githubusercontent.com/2865203/98288361-978cbc80-1f5b-11eb-856b-d63b845315d4.gif)
> 
> 必须是Windows并不完全正确的[东西`set_language`](https://github.com/CleverRaven/Cataclysm-DDA/blob/79e2b72820e84a1ee89ca4d4b750a84718afd8bb/src/translations.cpp#L171)。
> 
> 我想知道arch linux上的人实际上是否遇到了相同的问题，或者只是出现了相同的症状。似乎他们的问题出在本地化文件夹路径，而不是系统语言。

我使用Arch Linux，将游戏中的语言切换为中文（天朝）发现除了标题和MODI,其他部分依然是英文。

**Comment by BrettDong** [comment] 2021-02-20 16:04
> 我使用Arch Linux，将游戏中的语言切换为中文（天朝）发现除了标题和MODI,其他部分依然是英文。

1. 你有没有运行`lang/compile_mo.sh all`编译翻译文件？

2. 用`LANG=zh_CN ./cataclysm`运行游戏能否正常显示汉化？

**Comment by BrettDong** [comment] 2021-03-21 03:04
Another player reported the exact same problem where `gettext` seems to have completely failed to work when their Windows region is set to Hong Kong. However I cannot reproduce the bug on Windows 10 20H2 following the steps provided by the player.

**Closed** 2021-03-21 23:22 UTC
Labels: <Bug>, Info / User Interface, OS: Windows, Translation
