### ISSUE TITLE
Batch-cooking sweetbreads results in 0 calories product, that turns into 1000%+ nominal calories product after a reload.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#52429] opened 2021-10-24 20:22 UTC
### Describe the bug

See attached screenshot, compare:
1) food values predicted in crafting menu
2) food values after being cooked
3) food values after saving and reloading on the spot 

### Steps To Reproduce

1. Cook all 8 sweetbreads at once.
2. Check the values.
3. Save, reload, check again.

### Expected behavior

Get the product that crafting menu predicts. 

### Screenshots

![sweetbread](https://user-images.githubusercontent.com/61312205/138611304-04675e17-321e-4a89-961d-015f0551aa26.png)

### Save game:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7406195/save.zip)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 25ec152 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    Rural-Only Mapgen [ruralbiome]
]

### Additional context

I've seen similar thing happen to other food, practically guarantee the issue is not isolated to sweetbread. I also suspect the problem has something to do with batch cooking several "different" pieces of food.

**Comment by hexagonrecursion** [comment] 2022-01-04 20:37
This issue appears to be a duplicate of #52676

**Closed** 2022-02-03 23:25 UTC
Labels: <Bug>, Items: Food / Vitamins, Crafting / Construction / Recipes
