### ISSUE TITLE
Greatly increased yield from butchery

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#50821] opened 2021-08-15 23:37 UTC
### Describe the bug

Butchering (at the very least human) corpses yields far more resources, to the point of exceeding the volume of the original corpse.  Two human corpses gave me over four hundred flesh, over three hundred fat, over five hundred bones, nearly eighty hides, and sixty litres of blood.

Edit:
As of hacking up a dinosaur, my survival skill is at eighty-five

### Steps To Reproduce

1.  Find/make a corpse
2.  Butcher it

### Expected behavior

Butchering corpses should give resources more in line with the volume of the original corpse.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 Home Premium 64-bit (6.1, build 7601)
- Game Version: 2f6beb7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    MST Extra [MST_Extra],
    Space Heater [space_heater],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    NPC Recruitment Options [recruitment_options],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Monsters [No_Fungi],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Queju Motor [queju_motor],
    DinoMod [DinoMod],
    Dorf Life [Dorf_Life],
    Useful Helicopters [useful_helicopters]
]

**Comment by anothersimulacrum** [comment] 2021-08-15 23:50
The getting to skill 85 should be fixed https://github.com/CleverRaven/Cataclysm-DDA/issues/50713, but it is still an issue that butchering can violate conservation of mass, imo.

**Comment by Saicchi** [comment] 2021-08-16 01:05
> to the point of exceeding the volume of the original corpse. 
What about the corpse weight? That is the more important part since the volume can change as they're folded/squished when inside the body.

**Comment by anothersimulacrum** [comment] 2021-08-16 01:52
It,s about 2.5x that.

**Comment by Marrim** [comment] 2021-08-17 07:37
Does it reproduce with the skill being within the game's skill cap of 10?

**Comment by SilverTemper** [comment] 2021-08-17 17:55
It does not.

**Closed** 2021-08-20 18:30 UTC
Labels: <Bug>
