### ISSUE TITLE
Z Level Mapgen and Houses

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#13639] opened 2015-09-23 17:23 UTC
Right now, houses with basements are implemented by spawning house_base, which causes any basement spawn underneath.  Also right now, z level transitions are applied by searching for stairs at the lower level and spawning the player there.  When +Z levels get implemented, these stairs need to line up, which means that pre-defined mapgens need some way to associate with their counterparts on different z levels, and randomly generated mapgens need to access the layout on different levels to know where to place stairs.

JSON Changes:
- Add ID field to mapgen, along with an up_mapgen and down_mapgen if necessary, to associate with what to spawn on the +1 and -1 z levels.

Mapgen.cpp Changes:
- Track the ID of a mapgen spawned in a given location
- Use the mapgen ID of adjacent locations along with oter info to decide how to generate a given area
- If the mapgen ID indicates it is randomly generated, access the up/down levels to determine stair locations.  This may be doable with the transition from "reality bubble" to "reality column".

Overmap.cpp Changes:
- This is probably where the mapgen ID needs to be tracked.

Generation order is important for a system like this to work though.  Starting at z=0 and then moving up/down as necessary would work for the majority of mapgen, but in a situation where you have a randomly generated house with a json defined basement, the basement would need to be generated first and the house would need to generate last to line the stairs up.  It could be enforced that if the z=0 mapgen is randomly generated, then so are the rest, but I've only been considering house generation, not the implications it could have on labs or mines.
##

**Comment by kevingranade** [comment] 2015-09-23 20:19
One possibility is for random and/or predefined mapgen to specify a list of
valid stair locations instead of explicitly specifying the stairs, if the
second tile to be generated doesn't match, it would need to re-randomize
the tile being generated to try and get a match.

**Comment by Leland** [comment] 2017-05-04 03:26
Duplicate of #15914 but I've copied your issue description to it because it's so detailed.

**Closed by Leland** 2017-05-04 03:26 UTC
Labels: Enhancement, Long-term, Mapgen, Mechanics Change, Suggestion (Discuss), Z-levels
