### ISSUE TITLE
Error and Crash on loading Character Creation

### ISSUE THREAD

**Issue by Krylia** [CleverRaven/Cataclysm-DDA#31537] opened 2019-06-16 22:01 UTC
# Describe the bug
Error and/or crash occurs when loading up character creation, but _does not_ occur on first load of character creation menu.
# Steps To Reproduce
2. Go into character creation. Abort character creation.
3. Repeat above. Error and/or crash occurs while loading character creation.
# Expected behavior
Loading into character creation without error and/or crash.
# Versions and configuration
- OS: Windows
    - OS Version: Windows 7 Professional 64bit SP1
- Game Version: 0.D-4522-g4d34142 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [dda]
# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3294675/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3294676/debug.log)

**Comment by ipcyborg** [comment] 2019-08-01 15:11
Can't reproduce on 0.D-6063-gee64205.
Tried this cycle many times: 
New game -> Custom character -> Escape -> Yes -> ...

**Comment by Night-Pryanik** [comment] 2019-10-12 14:42
Closing for now, ping me if this is still an issue.

**Closed by Night-Pryanik** 2019-10-12 14:42 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Character / World Generation
