### ISSUE TITLE
Map extras spawning on roofs results in buggy behavior

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#52345] opened 2021-10-18 09:37 UTC
### Describe the bug

Such as corpses spawning in the air.

### Steps To Reproduce

1. Find e.g some silos.
2. Use the debug menu to spawn `mx_science` on it.
3. Observe corpses, loot, blood and scraps of flesh spawning in the air. Any enemies that are spawned will fall though.

### Expected behavior

The corpses and blood and everything should fall to the ground when being on a ledge. This actually happened to me without the debug menu but I can imagine this is incredibly rare, but fortunately it is trivial to reproduce this via the debug menu.
Alternatively, stuff should spawn on non-air tiles only.

### Screenshots

![image](https://user-images.githubusercontent.com/59517351/137706036-3b471b82-97dd-44b6-adb7-f1f15a83a73b.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

A crater randomly spawned underground a few times, too. Observable when mindlessly exploring tunnels. This should not happen either I think since a small nuclear explosion may also take the ceiling with it.

**Comment by l29ah** [comment] 2021-11-24 13:05
Got a crater in a basement with intact surface structure on todays master.

**Comment by NetSysFire** [comment] 2021-11-29 08:09
I can confirm this, as I saw a few of those along subway tunnels or even basements. A possible solution for this would be restricting specific map extras to a range of Z-levels (e.g craters only on 0, but e.g a drug deal can still spawn underground in e.g subway tunnels).
This also needs some "physics", so upon spawning a map extra and placing items in open air, they need to fall.

**Comment by I-am-Erk** [comment] 2021-12-14 02:24
What we could probably do is add some sort of rule to map extras to not spawn things in t_open_air for now.

**Comment by I-am-Erk** [comment] 2021-12-17 00:09
So, this seems to have interacted with #53189 in a fun way, producing errors quite often when the new mapgen test found that map extras are very often trying to drop stuff in open air. Looks like we need a solution more than initially thought.

**Comment by jbytheway** [comment] 2021-12-19 23:43
I re-enabled the #53189 test locally to explore this issue and I think there's a separate (but maybe related?) issue with that test.  The first failure I hit (which I'm investigating) relates to `mx_portal` placing a portal on open air, but there is already code in `mx_portal` to prevent exactly that from happening.  So somehow that code is not doing the right thing.

**Comment by Night-Pryanik** [comment] 2022-02-28 17:40
Duplicate of #38066.

**Closed by Night-Pryanik** 2022-02-28 17:40 UTC
Labels: <Bug>, (S2 - Confirmed), Map / Mapgen, Z-levels, Spawn, [C++], (P3 - Medium)
