### ISSUE TITLE
MAX_HP enchantment doesnt work

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#61902] opened 2022-10-24 19:00 UTC
### Describe the bug

MAX_HP enchantment doesnt work as intended

### Steps to reproduce

get a artifact or a custom trait that adds MAX_HP
game will display that you will have more hp but it wont affect anything
it will display you as hurt but wont regenarate and stay at base health

### Expected behavior

your max hp should increase and allows to regain health

### Screenshots

![Ekran Görüntüsü (74)](https://user-images.githubusercontent.com/82234624/197604338-6d104043-1689-4578-b9b5-48adc9e8d297.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 1f5acd1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    MST Extra [MST_Extra],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    alpermodd [alpermm]
]

### Additional context

game should use MAX_HP for every mutations and traits as if two different trait has either hp_modifier_secondary or hp_modifier they will conflict and only one will apply

**Comment by KymasTuran** [comment] 2022-10-25 01:34
https://github.com/CleverRaven/Cataclysm-DDA/issues/61701

**Comment by ZhilkinSerg** [comment] 2022-10-25 09:12
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/61701

**Closed by ZhilkinSerg** 2022-10-25 09:12 UTC
Labels: (S1 - Need confirmation)
