### ISSUE TITLE
Dissassembling crafted items may result in items other than those used to craft it

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18153] opened 2016-08-29 17:50 UTC
Assemble rope using the 5 tanning hides recipe. Then disassemble that one and suddenly the 5 hides (or 30 rags, or 30 leather patches, etc) turn into 6 long strings. All for 1 and half hour of work. Which seems to be an easy way to convert hides, rags, leathers etc into long strings, which can be made into short strings which can be made into thread.

So no reason to ever disassemble a rag into thread.

**Comment by Labtop-215** [comment] 2016-09-02 02:35
Except to raise your tailoring in the first place to be able to make the rope recipe.  It's also more efficient, item wise, to disassemble rags than it is to make rope and then turn it into thread since you lose 1,200 thread in the process of turning rags into rope and then into thread.

But yea, it's basically a faster way to gain thread.

**Comment by keyspace** [comment] 2017-01-29 01:24
Possible cause described [in #18632](https://github.com/CleverRaven/Cataclysm-DDA/issues/18632#issuecomment-251256169), an issue that involved ropes, too.

That issue was reported later than this one, and a fix for it has been merged. Tested on current git master (`0.C-20882-g68523bfd0e`) - this issue still present.

**Comment by keyspace** [comment] 2017-02-02 16:41
`player::disassemble()` doesn't check for item's `components`, and always uses the generic recipe.

**Comment by keyspace** [comment] 2017-02-02 17:14
Seems true for all items with `components`, not just rope. E.g., `spear_copper`.

Don't know if regression.

**Comment by Leland** [comment] 2018-01-23 15:25
Combining @l29ah's #22305 here:

> Disassembling sling made from 3 long strings yields leather and thread

From @Coolthulhu:

> Confirmed.

Seems that the game has no means of telling which recipe produced a given result and it doesn't respect the `components` field if it differs from the ones specified in recipe.
> `player::complete_disassemble` specifically searches for components from the recipe. If it fails, it defaults to ones in the recipe rather than ones in the item.

**Closed** 2018-02-20 03:35 UTC
Labels: Bug, Confirmed, Crafting / Construction
