### ISSUE TITLE
Vegetarian / Meat Intolerance stops vitamin absorbtion.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18069] opened 2016-08-17 05:37 UTC
Via: http://smf.cataclysmdda.com/index.php?topic=13082.0

Pantalion: "Behaviour: Meat Intolerance trait prevents the player from obtaining vitamins from meat sources, as well as meals which include eggs, such as deluxe beans and rice made with eggs.

Expected behaviour: Meat intolerance should solely impact morale gained from these sources, as the player remains biologically omnivorous; meals made without flesh ingredients should use the Egg tag, rather than the Flesh tag when they contain no flesh."

He is correct, as the mutations.json file says:
`"//" : "Intolerances are presumed a psychological issue unless stated otherwise, and cancelled by digestive mutations, which force the issue.",`

**Comment by Coolthulhu** [comment] 2016-11-28 22:41
Removing the "Bug" label - it is intended behavior as far as I recall (should be documented somewhere in the comments or the PR).

Pinging @mugling to comment on the issue.

**Comment by mugling** [comment] 2016-11-28 22:44
Meat intolerance **should** stop absorption of vitamins from meat (I've not checked if that is as-yet actually the case). Now would be a good time to consider what else it should actually do. Our whole morale system is such a mess I wonder if 'can eat but for 30% nutrition and no vitamins with a 10% chance of vomitting' is actually a better penalty.

**Comment by Leland** [comment] 2017-05-26 17:58
Marking as easy fix as this simply warrants an update of documentation.

**Closed** 2019-07-27 06:03 UTC
Labels: <Documentation>, Food / Vitamins, Good First Issue, Info / User Interface
