### ISSUE TITLE
Some cloth cannot be disassembled and cannot be cut

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#64213] opened 2023-03-13 00:46 UTC
### Describe the bug

I have some cloth loot from zobies. They cannot be disassembled and cannot be cut.

### Attach save file

[巴里.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10952555/default.zip)

### Steps to reproduce

1. Open inventory
2. Select butchering kit
3. Active butchering kit
4. Cut up item
5. Motorcycle armor, motorcycle jeans does not appear.

### Expected behavior

I should be able to cut them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills],
    Sky Island [skyisland],
    Magiclysm No Class Limit [magiclysm_no_class_limit]
]

**Comment by anothersimulacrum** [comment] 2023-03-13 01:36
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/47140

**Closed by anothersimulacrum** 2023-03-13 01:36 UTC
Labels: Good First Issue, (S1 - Need confirmation), [JSON]
