### ISSUE TITLE
Weird visual glitch with missing bridge textures and item textures. (latest stable release)

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#12458] opened 2015-05-24 18:35 UTC
While crossing a bridge (see: the bit with all the missing textures icons), items have a tendency to stretch likea buggy Windows XP window. This is particularly noticeable with cars. I have been able to reproduce this across several worlds and characters.

![image](https://cloud.githubusercontent.com/assets/12587061/7789086/6467af88-0254-11e5-92da-c2ab8e9fb6fa.png)
##

**Comment by Dalenacio** [comment] 2015-05-24 18:42
Here's another image, but with a car this time. VERY trippy.
![image](https://cloud.githubusercontent.com/assets/12587061/7789107/71450f06-0255-11e5-80fe-88bfe2851042.png)

**Comment by BevapDin** [comment] 2015-05-24 18:52
Bridge rails are of the (relatively new) terrain `t_guardrail_bg_dp`, which apparently is only supported by ChestHoleTileset_iso, ChestHoleTileset, MShock24TilesetModded, MShock24Tileset, MShock32Tileset, RetroDaysTileset10, RetroDaysTileset20_iso and RetroDaysTileset20.

This issue seems to be nearly the same to #12393 only with a different tile missing.

**Comment by drbig** [comment] 2015-05-24 18:54
A general call to tile artists to update their sets for post 0.C changes?

**Comment by illi-kun** [comment] 2016-04-19 11:03
Still exists in the latest experimental build, some tilesets aren't updated.

**Comment by Night-Pryanik** [comment] 2017-05-05 19:29
There will probably always some tilesets that ain't updated, therefore I think it's not a bug.

**Comment by Leland** [comment] 2017-05-05 21:43
@Night-Pryanik you nailed it about tilesets not being updated. However, this is an issue relating to what _happens_ when tilesets aren't updated – the placeholder textures cause some seriously weird visual errors. Cars can stretch across the entire screen.

**Comment by Night-Pryanik** [comment] 2017-05-06 05:11
I just wonder if stretching cars are happening exactly _because_ of not updated tilesets, or is it just a side effect.
I'll reopen it. 
Can anyone confirm this issue now?

**Comment by Leland** [comment] 2017-05-26 00:48
Can't reproduce. Closing.

For reference, Hoder's is the only one with that crazy missing texture icon shown in screenshots above. However, even using Hoder's, I don't get any screen tearing.

If someone encounters this issue again, I recommend they create a new issue for visibility purposes and link this one in it.

**Closed by Leland** 2017-05-26 00:48 UTC
Labels: Bug, Information / Interface, Tiles, Validated
