### ISSUE TITLE
Null Mission

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#21097] opened 2017-05-23 05:31 UTC
As I get to the end of quest chains, I am getting null missions. So far it has happened with the Old Guard rep after killing the bandit camp, and the relic/religious quest line after returning the etched skull.

Missions show up in quest log as "Null Mission" and talking to NPCs about it, gives some kind of null mission placeholder

**Comment by PlasmaChroma** [comment] 2017-05-26 11:38
Had this happen on a random NPC that I have as a follower.  His first mission was to find a weather log which I did.  When asking him for the another one, and he did claim to have a job to do, I got the Null mission placed in my log.

**Comment by PlasmaChroma** [comment] 2017-05-29 13:52
![dialogue](https://cloud.githubusercontent.com/assets/7933452/26552267/73d51cfa-4454-11e7-9d8d-4921bd7553b1.png)

![missions](https://cloud.githubusercontent.com/assets/7933452/26552277/79de367c-4454-11e7-8eca-ef3598490885.png)

**Comment by tinukedaya** [comment] 2017-07-15 18:40
Got exactly the same after finishing the "retrieve software" mission right now.

**Comment by angoddu** [comment] 2017-08-09 13:37
I constantly get this with my NPC followers. I usually can get one mission out of them then they null out

**Comment by AlecWhite** [comment] 2017-09-13 13:13
Now that I have a computer and internet again I can post the small analysis just for fun I did on discord and that no one paste it here after @kevingranade asked, so I'm doing it with a hell of lot of delay.

All seems to be in npctalk.cpp.
It seems like `talk_topic dialogue::opt calls dynamic_line()` which calls `dialog_for_topic()`. 
And it is `dialog_for_topic()` the one that throws that error message, when it doesn't a suitable next mission/map.

Which could be fixed in a lot of ways; like adding a check in `dynamic_line()` before the `if( mission_topics.count( topic ) > 0 ){...}` check, that calls a function that does the checks like `dialog_for_topic()` does, and instead of the error messages add an else that returns something like "I have no more missions for you" or something like that.

But then I don't play with NPCs currently, and dunno an easy way to test this, so I'm also writing this here to encourage certain other people that plays with NPCs to fix it.

Also I was away for 2 weeks in which almost 200 things happened, and haven't checked them all, so if anyone has fixed it, just disregard this and carry on.

**Comment by sxmichaels** [comment] 2017-11-29 22:19
Found the cause. At [`string_id_null_ids.cpp:43`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/string_id_null_ids.cpp#L43), the null ID for `mission_type` was defined as `"mission_type"` when it should be `"MISSION_NULL"`.

```
MAKE_NULL_ID2( mission_type, "mission_type" );
```

At `clear_mission()` in [`npctalk.cpp`:2845](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npctalk.cpp#L2845), this resulted in the calls to `miss->has_follow_up()` and `miss->get_follow_up()` to return `true` and `MISSION_NULL` mission respectively — because the null mission ID was not being recognized as being null.

**Closed** 2017-11-30 05:22 UTC
Labels: Bug, Confirmed, Mission, NPC
