### ISSUE TITLE
Game crash upon examine (V or e) some guns

### ISSUE THREAD

**Issue by OmegakillRimworld** [CleverRaven/Cataclysm-DDA#40806] opened 2020-05-24 21:06 UTC
# Describe the bug

When examining some weapons such as the FN-57 or Remington 1100 Compition as well as some other firearms causes a SIGSEGV: Segmentation Fault 100% of the time.

# Steps To Reproduce

1. Load up the save provided or start your own game, teleport to a gun store
2. Either use V to look around and find a shotgun or certain pistols or "e"xamine a container or even the floor that contains one of the buggy guns to replicate the crash.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2421-g8fc0363 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Save file: [Navesink.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4674405/Navesink.zip)
Debug:[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4674409/debug.zip)

**Comment by olanti-p** [comment] 2020-05-24 21:20
Looks like a duplicate of #40779. Should be fixed in the next build

**Comment by KorGgenT** [comment] 2020-05-24 21:20
![image](https://user-images.githubusercontent.com/30208401/82765198-7dfb1c80-9de2-11ea-94f9-0484b3add78e.png)
![image](https://user-images.githubusercontent.com/30208401/82765204-90755600-9de2-11ea-8804-39c760deb6a7.png)
this is what i get before downloading the save.

![image](https://user-images.githubusercontent.com/30208401/82765229-d0d4d400-9de2-11ea-8c4b-a608811775bf.png)
![image](https://user-images.githubusercontent.com/30208401/82765233-d9c5a580-9de2-11ea-9e95-767f59f6ae48.png)
This is what i get after loading the save.
Compiled from master

**Comment by KorGgenT** [comment] 2020-05-24 21:21
Duplicate of #40779

**Closed by KorGgenT** 2020-05-24 21:21 UTC
Labels: (S3 - Duplicate)
