### ISSUE TITLE
You pour water (frozen) into the || plastic canteen.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28882] opened 2019-03-21 15:06 UTC
**To Reproduce**  
Dunno, after saving and re-loading i get `The toilet water is frozen solid!`

**Versions and configuration(please complete the following information):**
0.D-760-g45d0f89a1d-dirty

**Comment by alanbrady** [comment] 2019-03-21 21:36
More information is required.  A save game or something might be nice too.

**Comment by l29ah** [comment] 2019-03-21 21:39
I've just reached a town, found a place to sleep, slept, woke up and went to a toilet.
[2019.03.20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2994069/2019.03.20.zip)

**Comment by alanbrady** [comment] 2019-03-21 22:12
So I'm guessing the bug being reported here is the fact you were able to reload your canteen with frozen water?

What I'm guessing happened is it started to freeze after you started to reload it which is kind of an ugly corner case that if it were fixed would be more of nuisance to the player if it backed out of the refill if it started to freeze in the middle of it.

Again just guessing since it's not what clear what issue is being reported here given the barest of details.  I tried playing with your save game and couldn't reproduce anything peculiar with the canteen or toilet.  Not sure where to go from here.

**Comment by l29ah** [comment] 2019-03-21 22:24
No, the toilet told me it was frozen when it asked me whether i want to fill/use it.

**Comment by l29ah** [comment] 2019-03-21 22:25
And it was this way until i saved the game and reloaded it.

**Comment by alanbrady** [comment] 2019-03-21 22:30
What sequence of commands allowed you to fill it whilst frozen?

**Comment by l29ah** [comment] 2019-03-21 22:44
`e`, direction key.

**Comment by alanbrady** [comment] 2019-03-21 23:21
It seems like some detail is still missing because I am unable to reproduce the issue as described.

1. Using provided save game, spawn a plastic canteen
2. Press e, up, toward toilet
3. Nothing happens, as expected

![image](https://user-images.githubusercontent.com/60370/54791001-5e240380-4bf5-11e9-8483-c9f31eb26809.png)

**Comment by l29ah** [comment] 2019-03-21 23:39
As i've said, i cannot reproduce it as well.
No modifications that i've done, the source is built with https://github.com/leycec/raiagent/blob/master/games-roguelike/cataclysm-dda/cataclysm-dda-9999-r7.ebuild

**Comment by Night-Pryanik** [comment] 2019-03-22 05:35
Closing until confirmed then.

**Comment by TheMurderUnicorn** [comment] 2019-03-22 09:27
I don't know how to reopen an issue, but this also happened to me.  I was recording at the time, so here's some screen shots.  I was loading water from a pump into a gallon jug. 

Here's the message displayed:

![001](https://user-images.githubusercontent.com/41651793/54813082-1936b600-4c63-11e9-8496-8cc4acd03030.png)

And here's a shot of my inventory a few seconds later:

![002](https://user-images.githubusercontent.com/41651793/54813083-1936b600-4c63-11e9-999f-2f3a3fbb7e49.png)

**Comment by TheMurderUnicorn** [comment] 2019-03-22 10:29
https://drive.google.com/open?id=1jInEXE7ytplHxRtOkAl49OFzPwtl4JDT

That's the save, never pulled a save before, I hope it's right. Should be right next to the pump and 'e'xamining it to put the water in the jug will produce frozen water.  Also worth noting that you can 'u'nload the frozen water from the jug, but I imagine that probably holds for most frozen liquids.

**Comment by Hirmuolio** [comment] 2019-03-22 19:13
Taking water from a pump/water tile has some odd interaction.

An item (liquid) is created and set to enviroment temperature.  
After this the item (liquid) is placed inside the container.

If enviroment is below freezing temperature then the result is frozen liquid being placed in a container.

Two possible solutions: 
* Do not allow taking water if enviroment is below freezing temperature (would be odd since map water can not freeze currently)
* have a floor temperature of maybe 4 C so that the result can't be set colder than this.

I don't think the result frozen water from this should behave any different from normal frozen water in containers.

AFAIK water in toilets does not behave like this. This is unique to water pumps and water tiles.

**Comment by kevingranade** [comment] 2019-03-22 19:14
It's because theres no water item on the map initially, right?

**Comment by Hirmuolio** [comment] 2019-03-22 19:15
Yeah. The items are created on the fly.

**Comment by l29ah** [comment] 2019-03-24 19:17
Reproduced it again when i woke up in a mansion and rushed to a toilet for water.

**Closed** 2019-03-25 21:30 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
