### ISSUE TITLE
Selecting a Magiclysm Character hangs

### ISSUE THREAD

**Issue by FlaKougar** [CleverRaven/Cataclysm-DDA#53841] opened 2021-12-28 18:38 UTC
### Describe the bug

Game hangs creating a new magiclysm based character

### Steps to reproduce

Make a world with Magiclysm included,
Create a new character.  
Select The Wizard's Apprentice Scenario.
Select Novice Stormshaper class.

Cataclysm hangs

### Expected behavior

Next step in character creation is available.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d239083 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

### Additional context

Windows 10 using Launcher
Works in 2021-12-26-1058
Fails in 2012-12-28-1625
Fails in 2012-12-28-1306
Fails in 2012-12-28-0235

**Comment by NetSysFire** [comment] 2021-12-28 23:43
Potential duplicate of #53825. Please make sure to use the very latest experimental.

**Comment by BrettDong** [comment] 2021-12-29 03:38
![image](https://user-images.githubusercontent.com/21075502/147625159-955146c3-8b24-4a7f-b6b3-02c85d175585.png)

Cannot reproduce using 2012-12-28-1625 Windows Tiles x64 on Windows 8.1 x64.

**Comment by Maleclypse** [comment] 2021-12-29 04:01
Please let me know to reopen if bug occurs on most recent experimental.

**Closed** 2021-12-29 04:01 UTC
Labels: (S1 - Need confirmation)

**Comment by FlaKougar** [comment] 2021-12-29 04:40
Latest experimental fixes for me as well
