### ISSUE TITLE
Map memory that should be visible is invisible

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#36367] opened 2019-12-23 02:10 UTC
# Describe the bug

Map memory that should be visible is invisible. I didnt have this issue 48 hours ago.

# Steps To Reproduce

1. Turn on map memory
2. Walk around some structures and observe walls are not visible when they should.

# Expected behavior

To have all map memory visible

# Screenshots
![Imgur](https://i.imgur.com/BivKkJS.gif)

Whilst sleeping:
![image](https://user-images.githubusercontent.com/50166150/71331917-6cac9c00-2534-11ea-8efc-9bb91dd98804.png)

Here are some more images:
![Imgur](https://i.imgur.com/4TwAJd5.gif)
[Imgur](https://i.imgur.com/6ykKg2U.gifv)

Also have the issue with retrodays tileset:

![image](https://user-images.githubusercontent.com/50166150/71330308-92ce3e00-252c-11ea-8c27-96a191d3c50c.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10619-g46c0151 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

Tileset: Chesthole_iso

# Additional context

- I have the forgetful trait.
- Maybe #36338 has something to do with this

**Comment by Zupercharged** [comment] 2019-12-23 05:05
Can confirm this is an issue I and others have been having, pull https://github.com/CleverRaven/Cataclysm-DDA/pull/36338 which was merged in build 10052 is almost definitely  the cause as reverting to build 10051 fixes the problem.

**Comment by l29ah** [comment] 2019-12-23 07:58
May be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/31994

**Comment by TheMurderUnicorn** [comment] 2019-12-23 10:10
Someone pointed out to me tonight that furniture also is disappearing from map memory.  I see it's also happening in the gif you made, I assume their connected.  It started somewhere in the last day or two, didn't feel like making a new issue because it's likely connected to this one.

**Closed** 2019-12-24 19:24 UTC
