### ISSUE TITLE
Vehicle-mounted turrets shoot vehicle interior

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#39445] opened 2020-04-10 15:40 UTC
# Describe the bug

Mounting a turret anywhere within the "Interior" of a vehicle will cause the mounted gun to shoot at the interior of the vehicle instead of from the roof to the area around the vehicle. This is most apparent with the Mark 19 Grenade Launcher. However, if a door is open, and a shot is fired out that door, then it will explode outside.

# Steps To Reproduce

1. Spawn a Mechanized Infantry Carrier (aapc-gl)
2. Close the door behind you
3. Load the gun, and attempt to fire it anywhere
4. Get a face-full of shrapnel

5. Reinstall the grenade launcher (and turret mount) on the outer Boards of the vehicle
6. Fire the weapon away from the vehicle (and the turret's mounting point) to find it fires normally
7. Attempt to fire to the opposite side of the vehicle
8. Get more shrapnel

# Expected behavior

It is supposed to be a roof-mounted weapon, so the interior of the vehicle shouldn't come into play. This was _previously_ functional. Not sure what changed.

# Screenshots

![image](https://user-images.githubusercontent.com/17204395/79002614-d3bf8200-7b1e-11ea-8c7c-80fab8711da6.png)
A Mark 19 Grenade Launcher firing from a Mechanized Infantry Carrier's default installation point

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-482-g40a256e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional Info

This might be related to the other vehicle bugs like #39338 ?

**Comment by Mekhasheyfe** [comment] 2020-04-11 02:41
Having the same issue. Have tested with my current vehicle, and several newly spawned vehicles.

**Comment by Sumguy62** [comment] 2020-04-13 02:37
probably broken by #39364, going by the history of src/turret.cpp

**Comment by Berkyjay** [comment] 2020-04-16 06:23
I'm having an issue where when I fire my mounted gun nothing happens.  Mine doesn't seem to be hitting the vehicle instead.  So I'm unsure if this is a different issue or the same one.

**Comment by ZhamelSeh** [comment] 2020-04-16 15:58
I am having the same issue. I have a Humvee, install an A7 laser rifle set to auto, and any shots fired are stopped at the outer boundary of the vehicle, or stopped by the windshield. Unable to target anything outside of the vehicle.

**Comment by ampersand55** [comment] 2020-04-17 08:19
Vehicle rams block fire too, I just found out.

**Comment by olanti-p** [comment] 2020-04-17 19:29
For me, turrets work fine in df00ef1ba6ffd23f0840dbd421366d2595fcddf7 but not in c663dfdc523e56ae1d522f7585de616c02c09631 introduced with #37329

**Comment by anothersimulacrum** [comment] 2020-04-17 19:50
This issues is likely a duplicate of #39521 then

**Closed** 2020-04-18 09:35 UTC
Labels: <Bug>, Vehicles
