### ISSUE TITLE
Game crashes at start | Segmentation fault with fresh download

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#76011] opened 2024-08-28 12:47 UTC
### Describe the bug

~i got the following error while trying to start the game, if i ignore it it propagates and causes a segmentation fault~

 ~DEBUG    : Tried to process terrain at (5,0) of submap of (101,84,-2) but the submap is not loaded.  my_MAPSIZE: 11~

 ~FUNCTION : ter_id map::ter(const tripoint_bub_ms&) const
 FILE     : src/map.cpp
 LINE     : 2016
 VERSION  : cdda-experimental-2024-08-14-0103 45f35ec~

UPDATE: downloaded a newer version to try to solve the issue and before i could transfer the savefile to the newer version got the following error while opening the game for the first time (with no modifications):

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: cdda-experimental-2024-08-28-2010 4696f0d
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    0x62e.7d0.230.e05    src/debug.cpp:967    bt_full
    0x62e.7d0.230.e05    src/debug.cpp:1.232    debug_write_backtrace(std::ostream&)
    0x62e.7d0.208.032    src/crash.cpp:89    log_crash
    0x62e.7d0.208.37f    src/crash.cpp:146    signal_handler
    0x73c.8b0.c42.51f    ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0    [unknown func]
    0x62e.7d0.d1e.5c4    src/third-party/imgui/imgui_draw.cpp:3.487    ImFont::CalcTextSizeA(float, float, float, char const*, char const*, char const**) const
    0x62e.7d0.ce1.c6e    src/third-party/imgui/imgui.cpp:5.099    ImGui::CalcTextSize(char const*, char const*, bool, float)
    0x62e.7d0.d8a.3ce    src/ui.cpp:567    calc_size
    0x62e.7d0.d8d.abc    src/ui.cpp:617    uilist::calc_data()
    0x62e.7d0.d8d.fa9    src/ui.cpp:685    uilist::setup()
    0x62e.7d0.d8e.e6e    src/ui.cpp:788    uilist::create_or_get_ui()
    0x62e.7d0.d8e.f64    src/ui.cpp:872    uilist::query(bool, int, bool)
    0x62e.7d0.d70.b11    src/translations.cpp:40    select_language[abi:cxx11]()
    0x62e.7cf.d91.cda    src/main.cpp:854    main
    0x73c.8b0.c29.d8f    ../sysdeps/nptl/libc_start_call_main.h:58    __libc_start_call_main
    0x73c.8b0.c29.e3f    ../csu/libc-start.c:392    __libc_start_main_impl
    0x62e.7cf.eed.cfd    [unknown src]:0    [unknown func]
    0xf.fff.fff.fff.fff.fff    [unknown src]:0    [unknown func]

### Attach save file

there is no savefile, the game wounldt even open the homepage

### Steps to reproduce

donwloaded newest version 

open the executable or run the launcher

the window crashes

### Expected behavior

to be able to open the game

### Versions and configuration

- OS ubuntu 22
- cdda-experimental-2024-08-28-2010 4696f0d
- 
### Additional context

[logs.zip](https://github.com/user-attachments/files/16789279/logs.zip)

**Comment by PatrikLundell** [comment] 2024-08-28 13:05
Hard to do much without a save...
The crash log indicates it's happening during the unpacking of an item_location of the item_on_map type.
However, we can't know if it's a failure to access a legal location or if garbage coordinates have been saved.

In principle it should be possible to rescue the save by locating the item_location in it and erase it or change it to a "nowhere" useless fallback item_location. However, that would require knowledge of which file item_locations are stored in and how to find and manipulate them, neither of which I have.

**Comment by yamil-90** [comment] 2024-08-28 15:35
@PatrikLundell 
[Howe_3.zip](https://github.com/user-attachments/files/16785648/Howe_3.zip)

managed to delete some map files and reduce the savefile size while not changing the error im getting

**Comment by PatrikLundell** [comment] 2024-08-28 16:25
I might have good news for you: I managed to load the save without crashing, although it did issue a few error reports. I believe it's another instance of an issue that was fixed recently, #75819, so updating ought to allow you to continue.

**Comment by yamil-90** [comment] 2024-08-28 20:45
tried to download the latest release and i get a segfault from the start, do i need to open a separate issue for this? T_T

debug:
    `The program has crashed.
    See the log file for a stack trace.
    CRASH LOG FILE: ./config/crash.log
    VERSION: cdda-experimental-2024-08-28-1747 9744b0a
    TYPE: Signal
    MESSAGE: SIGSEGV: Segmentation fault
    STACK TRACE:

    libbacktrace error 0: unrecognized DWARF version in .debug_info at 6
    libbacktrace error 0: unrecognized DWARF version in .debug_info at 6
    libbacktrace error 0: unrecognized DWARF version in .debug_info at 6
    0x5c0.21d.e71.2c1    src/debug.cpp:967    bt_full
    0x5c0.21d.e71.2c1    src/debug.cpp:1.232    debug_write_backtrace(std::ostream&)
    0x5c0.21d.e49.76d    src/crash.cpp:89    log_crash
    0x5c0.21d.e49.ac3    src/crash.cpp:146    signal_handler
    0x7ed.782.a42.51f    [unknown src]:0    [unknown func]
    0x5c0.21e.93f.28c    src/third-party/imgui/imgui_draw.cpp:3.487    ImFont::CalcTextSizeA(float, float, float, char const*, char const*, char const**) const
    0x5c0.21e.902.936    src/third-party/imgui/imgui.cpp:5.099    ImGui::CalcTextSize(char const*, char const*, bool, float)
    0x5c0.21e.9ab.462    src/ui.cpp:567    calc_size
    0x5c0.21e.9ae.b34    src/ui.cpp:617    uilist::calc_data()
    0x5c0.21e.9af.021    src/ui.cpp:685    uilist::setup()
    0x5c0.21e.9af.ee6    src/ui.cpp:788    uilist::create_or_get_ui()
    0x5c0.21e.9af.fdc    src/ui.cpp:872    uilist::query(bool, int, bool)
    0x5c0.21e.991.ba3    src/translations.cpp:40    select_language[abi:cxx11]()
    0x5c0.21d.a12.7e4    src/main.cpp:854    main
    0x7ed.782.a29.d8f    [unknown src]:0    [unknown func]
    0x7ed.782.a29.e3f    [unknown src]:0    [unknown func]
    0x5c0.21d.b52.1dd    [unknown src]:0    [unknown func]
    0xf.fff.fff.fff.fff.fff    [unknown src]:0    [unknown func]`

**Comment by PatrikLundell** [comment] 2024-08-28 21:33
I'm not sure what the recommended method is, but I'd rename the bug report to reflect the new error and update the body of the report to match that.

It's a different error (in the UI handling) in code that's rough at the moment, due to recent changes and actions to address errors uncovered. It may or may not be OS related.

**Comment by yamil-90** [comment] 2024-08-28 21:52
thanks, i updated the fields

**Comment by db48x** [comment] 2024-08-29 21:47
Thanks for the report, but it’s a duplicate of #75818.

**Comment by RenechCDDA** [comment] 2024-08-30 14:05
Indeed, duplicate.

Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.

**Closed by RenechCDDA** 2024-08-30 14:05 UTC
Labels: (S1 - Need confirmation)
