### ISSUE TITLE
Crash when trying to learn spell in camp/near npc/i dunno (bug with starting fires with firewood source?)

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#31660] opened 2019-06-20 15:46 UTC
How to reproduce-
1-spawn magic book
2-go to fireplace
3-try to learn spell
4-crashu

**Comment by adamkad1** [comment] 2019-06-20 15:47
[Minneapolis_copy_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3311152/Minneapolis_copy_copy.zip)

**Comment by adamkad1** [comment] 2019-06-20 15:58
however moving away from camp and learning a spell makes it not crash next time you do it

**Comment by MatthewGP** [comment] 2019-06-20 16:00
Could this actually be related to: https://github.com/CleverRaven/Cataclysm-DDA/issues/31656

**Comment by adamkad1** [comment] 2019-06-20 16:11
yes maybe.... maybe my character tried to refill the fire to keep the light. but retry option didnt work for me

**Comment by adamkad1** [comment] 2019-06-20 16:43
likely the same issue as https://github.com/CleverRaven/Cataclysm-DDA/issues/31656

**Comment by ifreund** [comment] 2019-06-20 18:31
Closing as a duplicate of #31656

**Closed by ifreund** 2019-06-20 18:31 UTC
Labels: <Crash / Freeze>, Items / Item Actions / Item Qualities, Mods
