### ISSUE TITLE
Optical cloak (or everything else?) consumes power from both physical UPS and UPS CBM equally if both are available

### ISSUE THREAD

**Issue by EditorRUS** [CleverRaven/Cataclysm-DDA#15873] opened 2016-03-23 09:50 UTC
Before: I have 252 power in CBM storage and 200 power in physical UPS (regular).
After one turn: I have 248 power in CBM storage and 160 power in physical UPS.

If I turn off my UPS interface, it will consume 40 power from physical UPS anyway.

Version: g5c30dca (few days old)

**Comment by Leland** [comment] 2017-05-25 03:27
Cannot reproduce. Am using the Optical cloak, have a UPS (200) in my inventory and an Internal Unified Power System with 500 power.

With the cloak active, the CBM's power will first be used and then the held UPS. Am not experiencing any instances of both being used.

**Comment by Leland** [comment] 2017-05-25 16:42
@Toothspit I tried to reproduce this one for a while last night and wasn't able to. I know you were working on that PR and mentioned you were attempting to reproduce as well. I'm closing this issue right now, but if you _do_ wind up being able to recreate the issue, ping me here and we'll reopen.

Likewise, @EditorRUS if you encounter this issue again, please do the same. Providing a savefile would be very helpful as well.

**Closed by Leland** 2017-05-25 16:42 UTC
Labels: Bionics, Bug, Confirmation Needed
