### ISSUE TITLE
Player is asked to handle someone else spilled liquid.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#41054] opened 2020-06-03 19:10 UTC
# Describe the bug

Player is asked to handle someone else spilled liquid. I.e. you get a choice to put it into container, or to spill it on the ground.

# Steps To Reproduce

1. Approach a refuge center until you see the fence that surrounds it. Save the game.
2. Go inside refuge center building.
3. If bug did not happen reload your save game and try again. Bug happens more than 50% of the time in my testing.

# Expected behavior

NPC should handle that by themselves.

# Screenshots

![image](https://user-images.githubusercontent.com/430076/83678086-ac3fdf80-a5cc-11ea-892c-f648cc27a73d.png)

![image](https://user-images.githubusercontent.com/430076/83678458-4ef85e00-a5cd-11ea-97c0-98ab6e45e2fe.png)

# Versions and configuration

Manjaro Linux.
Latest git pull on master branch at the time of writing this.

# Additional context

Probably caused by this line here:
```
void item_pocket::handle_liquid_or_spill( Character &guy )
{
    for( auto iter = contents.begin(); iter != contents.end(); ) {
        if( iter->made_of( phase_id::LIQUID ) ) {
            item liquid( *iter );
            iter = contents.erase( iter );
            liquid_handler::handle_all_liquid( liquid, 1 );    <------ this line here
        } else {
            item i_copy( *iter );
            iter = contents.erase( iter );
            guy.i_add_or_drop( i_copy );
        }
    }
}
```
I don't see how this function will know that it should ask the `guy` to handle the liquid, instead of defaulting to asking player.

**Comment by anothersimulacrum** [comment] 2020-06-03 19:29
Duplicate of #40658 - NPCs are spawning with cans in their inventory that should be sealed, but are not. Fixing that issue will fix this too.

**Closed by anothersimulacrum** 2020-06-03 19:29 UTC

**Comment by EvgenijM86** [comment] 2020-06-03 20:32
Can NPC raft liquids themselves though? I assume that this would happen if they did.

**Comment by anothersimulacrum** [comment] 2020-06-03 21:02
NPCs cannot craft.
