### ISSUE TITLE
Crash during saving game while wearing specific rucksack

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#57886] opened 2022-05-24 09:24 UTC
### Describe the bug

Game crashes during saving. Problem started happening in a lab during a portal storm. Managed to pin it down to wearing a certain rucksack during saving.

The thing is - I have been wearing that thing for a long time. Don't know what has changed recently for the problem to occur.

### Steps to reproduce

1. Load attached save
2. Wear MOLLE large rucksack next to character
3. Try to save game
4. Crash

Note that saving without wearing that rucksack works just fine.

### Expected behavior

Saving game without crashing. :)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8435-g681c2a46f4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Crash and debug: [crashdebug.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8761234/crashdebug.tar.gz)
Savegame: [Cyberworld.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8761236/Cyberworld.tar.gz)

Note that there are six versions of the same character in that world, I suppose that is a result of the crashes during saving.

On a personal note, I'd like to add that I really appreciate the work you people put into developing this game. Thank you! :D

**Comment by Inglonias** [comment] 2022-05-24 17:22
Checking with the debugger, I see a read access violation on [line 1216 of item_contents.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_contents.cpp#L1216). That's all I got from the release build. Recompiling with the debug build now.

**Comment by Inglonias** [comment] 2022-05-24 17:50
...It turns out I don't understand how to interpret what's going on. All I know is that a bad pointer is being passed into the code that serializes things for the save file. I'm not sure what's doing that or why.

**Comment by Inglonias** [comment] 2022-05-24 17:59
I do have a workaround if you still need it. It looks like the issue is with that specific rucksack. If you spawn in a new one to replace it, you can save your game and continue playing.

**Comment by BaumgeistOne** [comment] 2022-05-24 18:02
Thanks. :)

I modified that rucksack with MOLLE pockets, maybe that has something to do with it?

**Comment by Inglonias** [comment] 2022-05-24 18:04
Removing the pouches also allowed saving to work, so I suspect you're right on that one.

**Comment by RoyBerube** [comment] 2022-05-24 22:48
This might be the same problem as in #57733. An `item_location::in_container` is the problem in that issue - same as this one.

Seems that an expired smart pointer for the backpack is the problem.

**Comment by RoyBerube** [comment] 2022-05-25 06:13
Closing in on the cause: it seems the activity backlog containing 8 instances of ACT_CONSUME_MEDS_MENU is pointing to the adhesive bandages in the backpack. That is why the item_location is not deleting properly.

Making some progress at least.

**Comment by BaumgeistOne** [comment] 2022-05-25 07:24
Yes, I have been carrying adhesive bandages in there, and been using the consume menu for using them. Noticed that after a recent update I had to open up the menu again every time after consuming a bandage, unlike before, when the menu would open up again by itself.

**Comment by BaumgeistOne** [comment] 2022-05-25 19:53
Thank you very much! :)

**Closed** 2022-05-26 01:12 UTC
Labels: (S1 - Need confirmation)
