### ISSUE TITLE
Screen/Game Freeze, Mr Lapin Warrener

### ISSUE THREAD

**Issue by Wudez** [CleverRaven/Cataclysm-DDA#71648] opened 2024-02-09 23:08 UTC
### Describe the bug

During the "Visit Trading Farmers" (dont know the actual mission name) quest from Mr. Lapin Warrener, the game consistently freezes upon accepting the quest, halting any progress. 

### Attach save file

[Water Valley-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14226942/Water.Valley-trimmed.tar.gz)

### Steps to reproduce

1. Talk with Mr. Lapin Warrener
2. Ask : "Heard anything about the outside world?"
3. Ask: "Anyone nearby I should meet?"
4. Answere: "Seems like a deal to me!"

### Expected behavior

Expected behavior: Receiving the mission along with the location.

Result: The application freezes completely, requiring the user to force quit in order to exit the application.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: VOG-L29; Release: 10; Incremental: 10.1.0.150C431; 
- Game Version: b1b50ff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Megafauna [megafauna],
    Mythos Mod - Mythos Creatures Only [Mythos-Creatures],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by MrHrulgin** [comment] 2024-02-10 01:20
Yeah, this is a known bug with trying to spawn the Isherwood Farm. Duplicate of #47220, #47225, #61171, #47595.

**Comment by Wudez** [comment] 2024-02-10 05:45
Known bug

**Closed** 2024-02-10 05:45 UTC
Labels: (S1 - Need confirmation)
