### ISSUE TITLE
segfault: handle_gun_damage

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#45325] opened 2020-11-09 20:05 UTC
# Describe the bug

While driving a car, the following segfault happens:
```
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    player::handle_gun_damage(item&)
    ??:?
    player::fire_gun(tripoint const&, int, item&)
    ??:?
    gun_actor::shoot(monster&, Creature&, string_id<gun_mode> const&) const
    ??:?
    gun_actor::call(monster&) const
    ??:?
    monster::move()
    ??:?
    game::monmove()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    ??
    ??:0
    _start
    ??:?
```

# Steps To Reproduce

1. drive a bit backwards
2. after a few turns the crash happens

# Expected behavior

Happy non-segfaulting :)

# Versions and configuration

 - OS: Debian testing
 - Game Version: 0.E-7472-g7f7deed
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context
* [segfault-handle_gun_damage-log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5512985/segfault-handle_gun_damage-log.zip)
* [segfault-handle_gun_damage-savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5512986/segfault-handle_gun_damage-savegame.zip)

**Comment by andrei8l** [comment] 2020-11-09 22:05
Looks like a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45323

**Closed** 2020-11-09 22:33 UTC
