### ISSUE TITLE
Failed to place monster

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#43349] opened 2020-08-31 03:36 UTC
# Describe the bug

When traveling on map, I see the debug message "failed to place monster"

# Steps To Reproduce

Load save
Move right for a while, or move back left.
Reload if it doesn't trigger exactly.  Happens 2/3 loads.

# Expected behavior

Probably expect either:
A monster loads
No message

# Versions and configuration

VERSION: 0.E-5518-g9dbd68a
Also previous versions

# Additional context

[New Hartford - 10FailedToPlaceMonster.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5148189/New.Hartford.-.10FailedToPlaceMonster.zip)

**Comment by danielkwinsor** [comment] 2020-08-31 03:56
It happens more the closer you get to the water

**Comment by TealcOneill** [comment] 2024-06-10 08:35
/Duplicate of #54544. This one came first but the other one has significantly more detail regarding the error.

**Comment by Night-Pryanik** [comment] 2024-11-23 04:35
Closing in favor of #54544.

**Closed by Night-Pryanik** 2024-11-23 04:35 UTC
Labels: <Bug>, (S3 - Duplicate), Spawn, Monsters
