### ISSUE TITLE
Wearyness did not go away and is twice in my char sheet

### ISSUE THREAD

**Issue by Erozaxx** [CleverRaven/Cataclysm-DDA#44347] opened 2020-09-22 20:48 UTC
# Describe the bug
My character is Modeartely Weary **and** Lightly Weary at the same time. It is like that already a second day where I did not do anything else, than eating, drinking and playing games on my game watches.
Also after full night sleep log says: "*You feel well rested.*", but the weariness is still there.

# Steps To Reproduce
1. I don't really know how to reproduce, its there.

# Expected behavior
After some time of playing games the log message displayed, that weariness is lower level than before.
After some time of slacking the weariness should go away, as it happened several times before.
Never have **two lines** with weariness 

# Screenshots
[Screenshot_On_Imgur](https://i.imgur.com/xABPMA0.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6152-g89c9b44 [64-bit]
- Graphics Version: Tiles - UndeadPeople [NEW VERSION]
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

# Additional context
Adding save
[Chesuncook.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5263909/Chesuncook.zip)

**Comment by anothersimulacrum** [comment] 2020-09-22 21:06
Thanks for the report!
Duplicate of  #44299

**Closed by anothersimulacrum** 2020-09-22 21:06 UTC

**Comment by lcy03406** [comment] 2020-09-22 21:07
I've seen the same. chance to 'combine' to one when the two effects are same level.

**Comment by Erozaxx** [comment] 2020-09-22 21:19
> Thanks for the report!
> Duplicate of #44299

Ah ok, thanks for pointing to the duplicate. I did search "wearyness" but probably made a typo, did not find anything (I am lame in fast reading).

Happy bug-hunting.
