### ISSUE TITLE
Missing roof in Hazardous Waste Sarcophagus

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#21942] opened 2017-09-20 19:03 UTC
Game version:
0.C-23961-ge6cbb86 (tiles)

Operating system:
Win10

Mods active:
none

Not sure if intended: The tiles next to the vehicle are unroofed (note the rain drops and falling temperature)
![image](https://user-images.githubusercontent.com/11627131/30662326-f8b64876-9e46-11e7-9ae8-0c80ed9d383c.png)

**Comment by gcaliber** [comment] 2017-10-05 15:44
I believe its always been this way so I've never though much about it, but since it was never completed who knows if that was intended.

**Comment by rm-code** [comment] 2017-10-05 15:59
Intended or not, if the HW-Sarcophagus is supposed to be something like [this](https://en.wikipedia.org/wiki/Chernobyl_Nuclear_Power_Plant_sarcophagus), missing roof tiles don't make much sense though.

**Comment by Coolthulhu** [comment] 2017-10-05 17:23
The roof system is a bit unfinished in general. At the moment it is kinda hacked-in.
Currently we handle most of those by creating a special terrain type for roofed terrain (or unroofed). That is, floor with a roof above is a completely different terrain from one without.

Might be a good idea to have some better system to scan for holes than just looking for the rain.

**Comment by ZhilkinSerg** [comment] 2017-10-05 18:01
The issue is due to `t_pavement` terrain is used during the mapgen. This terrain type doesn't have "INDOORS" flag.

**Comment by ZhilkinSerg** [comment] 2017-10-05 18:04
Just realized sarcophagus has tiles on -2 level without connection to ground level. Should it be moved to -1 and connected via stairs?

![default](https://user-images.githubusercontent.com/16213433/31242687-739d308e-aa10-11e7-8488-0e188cac7ebc.png)

**Comment by Coolthulhu** [comment] 2017-10-05 18:06
> Just realized sarcophagus has tiles on -2 level without connection to ground level. Should it be moved to -1 and connected via stairs?

No, the elevator moves things 2 z-levels for some reason.

**Comment by ZhilkinSerg** [comment] 2017-10-05 18:09
> No, the elevator moves things 2 z-levels for some reason.

Thanks. Didn't know that. Maybe -1 level is reserved for canalization pipes etc?

**Comment by kevingranade** [comment] 2017-10-05 22:13
> Thanks. Didn't know that. Maybe -1 level is reserved for canalization
pipes etc?

It's actually because sewers and subways are present on lvl -1 in towns.
When elevators were added they skipped past the "sewer level" to get to the
"basement level".  Once we have a need for it this should be fixed to make
elevators more flexible.

**Closed** 2017-10-06 06:54 UTC
Labels: Mapgen
