### ISSUE TITLE
Seg fault when trying to put a longarm bag into another longarm bag

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55588] opened 2022-02-22 08:12 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/7064677/155089569-b552fd8a-cece-4fe0-a51c-ffde77d82adb.png)

I wielded one longarm bag(empty) and had another equipped(with 12 items inside).
I tried wielding a bandage that was stored in my equipped longbag and ... I think at that point it crashed.

### Steps to reproduce

Not sure if it will work, but my best guess would be:

1. Get 2 longarm bags
2. Equip one of them and wield the other one.
3. Store an item in the equipped longarm bag.
4. Wield that same item from (3).

### Expected behavior

No crash, of course.

### Versions and configuration

Win 8.1 x64, tiles, English, default dda mod + soundpack "@"

**Comment by martosss** [comment] 2022-02-22 08:18
Hm, That's not it, I just managed to store that bag in the other bag ...
![image](https://user-images.githubusercontent.com/7064677/155090866-c6b0ed52-2e8c-4db2-8342-db2c17a6ec8b.png)

**Comment by martosss** [comment] 2022-02-22 08:22
I actually had 2 bandages, one was added to favorites.
I unfavored it and tried to wield it so that I can stack the two together, maybe something went wrong at that point? I think they were both stored in the longarm bag.

**Comment by martosss** [comment] 2022-02-22 08:33
There is the debug info:

-----------------------------------------
09:12:40.936 : Starting log.
09:12:40.936 INFO : Cataclysm DDA version 0.F-3
09:12:40.944 INFO : [main] C locale set to C
09:12:40.944 INFO : [main] C++ locale set to C
09:12:40.944 INFO : SDL version used during compile is 2.0.9
09:12:40.944 INFO : SDL version used during linking and in runtime is 2.0.9
09:12:41.059 INFO : Number of render drivers on your system: 5
09:12:41.059 INFO : Render driver: 0/direct3d
09:12:41.059 INFO : Render driver: 1/direct3d11
09:12:41.059 INFO : Render driver: 2/opengl
09:12:41.059 INFO : Render driver: 3/opengles2
09:12:41.059 INFO : Render driver: 4/software
09:12:41.062 INFO : [options] C locale set to C
09:12:41.062 INFO : [options] C++ locale set to C
09:12:41.062 INFO : Setting language to: 'en'
09:12:41.063 INFO : Language is set to: 'en'
09:12:41.063 INFO : [translations] C locale set to English_United States.1252
09:12:41.063 INFO : [translations] C++ locale set to C
09:12:41.330 INFO : Active renderer: 1/direct3d11
09:12:41.385 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
09:12:41.622 INFO : Setting language to: 'en'
09:12:41.622 INFO : Language is set to: 'en'
09:12:41.622 INFO : [translations] C locale set to English_United States.1252
09:12:41.622 INFO : [translations] C++ locale set to C
09:12:41.763 ERROR SDL : (error message will follow backtrace)
  #0
    (dbghelp: @0x6b8e06[cataclysm-tiles.exe+0x2b8e06]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x56@0x6b8e06),
    (libbacktrace: 0x6b8e06    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6b9c76[cataclysm-tiles.exe+0x2b9c76]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x2d6@0x6b9c76),
    (libbacktrace: 0x6b9c76    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x105e557[cataclysm-tiles.exe+0xc5e557]), 
    (libbacktrace: play_music_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x297@0x105e557),
    (libbacktrace: 0x105e557    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x105fc38[cataclysm-tiles.exe+0xc5fc38]), 
    (libbacktrace: play_music(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x258@0x105fc38),
    (libbacktrace: 0x105fc38    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x105fea4[cataclysm-tiles.exe+0xc5fea4]), 
    (libbacktrace: update_music_volume()+0x174@0x105fea4),
    (libbacktrace: 0x105fea4    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0xe3e0f1[cataclysm-tiles.exe+0xa3e0f1]), 
    (libbacktrace: options_manager::save()+0x21@0xe3e0f1),
    (libbacktrace: 0xe3e0f1    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7b4259[cataclysm-tiles.exe+0x3b4259]), 
    (libbacktrace: game_ui::init_ui()+0x139@0x7b4259),
    (libbacktrace: 0x7b4259    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: FT_Set_Named_Instance+0x73a88a@0x1c632fa[cataclysm-tiles.exe+0x18632fa]), 
    (libbacktrace: main+0x105a@0x1c632fa),
    (libbacktrace: 0x1c632fa    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x4013bd[cataclysm-tiles.exe+0x13bd]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013bd),
    (libbacktrace: 0x4013bd    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:341    __tmainCRTStartup),
  #9
    (dbghelp: @0x4014cb[cataclysm-tiles.exe+0x14cb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014cb),
    (libbacktrace: 0x4014cb    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:197    WinMainCRTStartup),
  #10
    (dbghelp: BaseThreadInitThunk+0x22@0x7ffdd9eb13f2[KERNEL32.DLL+0x13f2]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #11
    (dbghelp: RtlUserThreadStart+0x34@0x7ffddc6e54f4[ntdll.dll+0x154f4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) **ERROR : src/sdlsound.cpp:156: Failed to load audio file ./sound//damalsksoundpack-0.2/music/Dreaming with Great Old One (Arkham Radio Podcast).mp3: Unrecognized audio format**
09:12:42.161 WARNING : opendir [./mods/] failed with "No such file or directory".
09:12:49.090 WARNING : opendir [./save/Rogers City/mods] failed with "No such file or directory".


It seems the problem is ... the music?

**Comment by martosss** [comment] 2022-02-22 08:35
And there's the crash log:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.F-3
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x6b8e06[cataclysm-tiles.exe+0x2b8e06]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x56@0x6b8e06),
    (libbacktrace: 0x6b8e06    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x693336[cataclysm-tiles.exe+0x293336]), 
    (libbacktrace: log_crash+0x526@0x693336),
    (libbacktrace: 0x693336    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x694652[cataclysm-tiles.exe+0x294652]), 
    (libbacktrace: signal_handler+0x32@0x694652),
    (libbacktrace: 0x694652    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: Mix_EachSoundFont+0x604e0@0x12c4a70[cataclysm-tiles.exe+0xec4a70]), 
    (libbacktrace: gnu_exception_handler+0x70@0x12c4a70),
    (libbacktrace: 0x12c4a70    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x96@0x7ffddc751dd6[ntdll.dll+0x81dd6]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x9d@0x7ffddc76345d[ntdll.dll+0x9345d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0xf67@0x7ffddc724937[ntdll.dll+0x54937]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x3a@0x7ffddc7625ea[ntdll.dll+0x925ea]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x91e4a6[cataclysm-tiles.exe+0x51e4a6]), 
    (libbacktrace: item::is_null() const+0x6@0x91e4a6),
    (libbacktrace: 0x91e4a6    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x91e540[cataclysm-tiles.exe+0x51e540]), 
    (libbacktrace: item::made_of_from_type(phase_id) const+0x10@0x91e540),
    (libbacktrace: 0x91e540    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x5ddc8c[cataclysm-tiles.exe+0x1ddc8c]), 
    (libbacktrace: Character::can_wield(item const&) const+0x4c@0x5ddc8c),
    (libbacktrace: 0x5ddc8c    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x812091[cataclysm-tiles.exe+0x412091]), 
    (libbacktrace: game::wield(item_location)+0x131@0x812091),
    (libbacktrace: 0x812091    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x81465b[cataclysm-tiles.exe+0x41465b]), 
    (libbacktrace: game::inventory_item_menu(item_location, std::function<int ()> const&, std::function<int ()> const&, game::inventory_item_menu_position)+0x1d8b@0x81465b),
    (libbacktrace: 0x81465b    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x828fcb[cataclysm-tiles.exe+0x428fcb]), 
    (libbacktrace: game_menus::inv::common(avatar&)+0x64b@0x828fcb),
    (libbacktrace: 0x828fcb    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x855141[cataclysm-tiles.exe+0x455141]), 
    (libbacktrace: game::handle_action()+0x1811@0x855141),
    (libbacktrace: 0x855141    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x8053eb[cataclysm-tiles.exe+0x4053eb]), 
    (libbacktrace: game::do_turn()+0x100b@0x8053eb),
    (libbacktrace: 0x8053eb    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: FT_Set_Named_Instance+0x73a9f9@0x1c63469[cataclysm-tiles.exe+0x1863469]), 
    (libbacktrace: main+0x11c9@0x1c63469),
    (libbacktrace: 0x1c63469    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x4013bd[cataclysm-tiles.exe+0x13bd]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013bd),
    (libbacktrace: 0x4013bd    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:341    __tmainCRTStartup),
  #18
    (dbghelp: @0x4014cb[cataclysm-tiles.exe+0x14cb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014cb),
    (libbacktrace: 0x4014cb    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:197    WinMainCRTStartup),
  #19
    (dbghelp: BaseThreadInitThunk+0x22@0x7ffdd9eb13f2[KERNEL32.DLL+0x13f2]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #20
    (dbghelp: RtlUserThreadStart+0x34@0x7ffddc6e54f4[ntdll.dll+0x154f4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by LeahLuong** [comment] 2022-02-22 17:16
I believe this is a dupe of #55227 which was fixed by #55477. Testing on a newer release should prove it.

**Closed** 2022-02-23 14:25 UTC

**Comment by NetSysFire** [comment] 2022-02-23 14:29
This is why you should *always* insert the generated game report which usually includes the exact version, making debugging waaay easier for us.
