### ISSUE TITLE
Constructed charcoal kiln have infinite charges (same for other constructed crafting spots).

### ISSUE THREAD

**Issue by insidio118** [CleverRaven/Cataclysm-DDA#43263] opened 2020-08-27 18:28 UTC
# Describe the bug
Constructed charcoal kiln have infinite charges. This can be abused for making infinite clear water and whatever crafts you want without wasting a single charcoal.

# Steps To Reproduce

construct stone furnace/charcoal kiln/clay furnace etc.

# Expected behavior

fueled kilns and furnaces should use fuel when used for crafting

# Versions and configuration

Win 10

 - Experimental 10952
 - Tiles
 - Ingame language: Russian
 - Mods loaded: dda, and 2 mods that give stats lvling through exp or skills.

# Additional context

```
 DEBUG    : can't set ammo null in коптильня as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 601
```

Only working thing is a construction that makes smoked meat. If placed inside via interaction. 
BUT, if its used as a tool (fire) to craft something - it still popups error and if you ignore it - you have infinite charges.

**Comment by starytroll** [comment] 2020-08-27 19:45
Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/43098 and https://github.com/CleverRaven/Cataclysm-DDA/issues/42033

**Comment by insidio118** [comment] 2020-08-27 19:51
sry, tried to search but found nothing. Seems like bug is abandoned?

**Comment by KorGgenT** [comment] 2020-08-28 22:13
Marking as a duplicate of #42033 and adding that to 0.F blockers

**Closed by KorGgenT** 2020-08-28 22:13 UTC
Labels: (S3 - Duplicate)
