### ISSUE TITLE
Snap-to-target through vehicle or partial barriers

### ISSUE THREAD

**Issue by brandonevenson** [CleverRaven/Cataclysm-DDA#38974] opened 2020-03-23 17:41 UTC
Game version:
    0.D-13361-g6fc9301 (tiles)
Operating system:
    Windows 10
Tiles or curses:
    MSX++DEAD_PEOPLE
Mods active:
    None - Only DDA
### Expected behavior
    Press f to fire, should snap-to-target when enemy is behind a window, a sandbag, or while firing turret manually
### Actual behavior
    Forced to manually move my crosshairs to engage such targets
### Steps to reproduce the behavior
    Loaded a world with multiple different settings - no changes. Seems static in all of my plays.

**Comment by AMurkin** [comment] 2020-03-24 04:22
The same as #38285.

**Comment by buildfailedforallplatforms** [comment] 2020-03-25 00:24
Any chance of this being fixed soon?
It's game breaking for me

**Comment by Dacendeth** [comment] 2020-03-25 17:01
I think #37983 caused it.

**Comment by JeanLucVanDamme** [comment] 2020-03-26 05:37
Game breaking for me as well.

**Comment by mlangsdorf** [comment] 2020-03-27 15:41
Closing as duplicate of #38285.

Also, get a grip - this is annoying but not a game breaker.

**Closed by mlangsdorf** 2020-03-27 15:41 UTC
Labels: <Bug>
