### ISSUE TITLE
Using control laptop to override IFF crashes the game

### ISSUE THREAD

**Issue by ackron99** [CleverRaven/Cataclysm-DDA#30470] opened 2019-05-13 04:40 UTC
Game version: Experimental build 8949 

Operating system: Widows 10

Tiles or curses: tiles

Filthy clothing, disable NPC needs, simplified nutrition, Medieval and Historic Content, More Survival tools, NPC triats, Mutant NPCs, Boats, Classes and Scenarios Mod, Disable Religious Texts

### Expected behavior 

Activate control laptop, select Override IFF, select a target, and then turn it friendly (or not)

### Actual behavior

I chose "override IFF protocols" from the list, selected the turret, and then the game crashed

### Steps to reproduce the behavior

Use a control laptop (So far it's crashed on 3 different turrets, all in the same ice lab)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3171140/crash.log)

**Comment by AMurkin** [comment] 2019-05-13 06:10
Cannot confirm.
Can you provide a save file before the crash happens?

**Comment by ackron99** [comment] 2019-05-13 06:50
Here you go
[Redwood.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3171442/Redwood.zip)

**Comment by AMurkin** [comment] 2019-05-13 11:50
Unable to reproduce. (Ignored errors related to unofficial mod Hairs)
Tested in Linux curses and Windows x86 tiles.
Latest version 0f8bf29.

**Comment by 81Denton** [comment] 2019-05-16 11:45
The same thing happened to me on an older build three days ago; this has stopped happening since I updated to build 8985 (Win 10 x64 Tiles). Are you still experiencing this issue?

**Comment by AMurkin** [comment] 2019-05-26 04:43
Should be closed as unconfirmed, probably.

**Closed** 2019-05-26 06:36 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Items / Item Actions / Item Qualities, Monsters

**Comment by drachs** [comment] 2019-06-01 01:03
Build 8944, Updating did fix it.

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2832-g38838dc
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x565E95[cataclysm-tiles.exe+0x165E95]
    @0x566962[cataclysm-tiles.exe+0x166962]
    SMPEG_error+0x4B034@0xE69390[cataclysm-tiles.exe+0xA69390]
    _C_specific_handler+0x96@0x7FFBF0DA1E26[ntdll.dll+0x81E26]
    _chkstk+0x9D@0x7FFBF0DB349D[ntdll.dll+0x9349D]
    RtlRaiseException+0xF67@0x7FFBF0D748D7[ntdll.dll+0x548D7]
    KiUserExceptionDispatcher+0x3A@0x7FFBF0DB262A[ntdll.dll+0x9262A]
    @0x9C02A0[cataclysm-tiles.exe+0x5C02A0]
    @0x9B5462[cataclysm-tiles.exe+0x5B5462]
    @0x68CC2B[cataclysm-tiles.exe+0x28CC2B]
    @0x68F724[cataclysm-tiles.exe+0x28F724]
    IMG_LoadWEBP_RW+0x50B718@0x1466918[cataclysm-tiles.exe+0x1066918]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x22@0x7FFBF09513F2[KERNEL32.DLL+0x13F2]
    RtlUserThreadStart+0x34@0x7FFBF0D354F4[ntdll.dll+0x154F4]
