### ISSUE TITLE
Refugee Center Spawn Crash

### ISSUE THREAD

**Issue by Vicbrtson** [CleverRaven/Cataclysm-DDA#40066] opened 2020-05-02 01:32 UTC
# Describe the bug

When accessing the Evac Shelter Terminal, then selecting "Contact Us," there is a small hanging period and a debug error displays

# Steps To Reproduce

1. Evacuee scenario
2. Access terminal and select "Contact Us"
3. Error displays

# Expected behavior

The location of the refugee center is revealed and a relevant mission assigned

# Screenshots

# Versions and configuration

 - OS: Windows 7 Ultimate SP1
 - Game Version: 0.E 10478
 - Graphics version: TILES
 - Ingame language: English
 - Mods loaded: C.R.I.T Expansion Mod, Alternative Map Key, No Rail Stations, Dark Days Of The Dead, Fuji's Military Profession Pack, StatsThroughSkills

# Additional context

Debug message:

 DEBUG    : Unable to find and assign mission target refctr_S3e.

 FUNCTION : cata::optional<tripoint> find_or_create_om_terrain(const tripoint&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 240

**Comment by Vicbrtson** [comment] 2020-05-02 01:43
After further testing, I believe this error only happens when Dark Days Of The Dead is enabled, no other mod recreates this issue.

**Comment by ZhilkinSerg** [comment] 2020-05-02 06:26
Duplicate of #38993

**Closed by ZhilkinSerg** 2020-05-02 06:26 UTC
