### ISSUE TITLE
Game frequently crashes when I'm near or in my vehicle - no consistent pattern

### ISSUE THREAD

**Issue by Kitaragna** [CleverRaven/Cataclysm-DDA#29978] opened 2019-04-27 07:54 UTC
**Describe the bug**  
Game likes to crash - a lot when I'm near my vehicle. I could be doing anything - driving, crafting an item on a nearby bench, fighting a monster, anything.

**To Reproduce**  
Not really possible. I would say just drive around a lot and see what happens

**Expected behavior**  
I expect it... not to crash.

**Screenshots**  
https://i.imgur.com/0bfhqSM.png
Right when it happened. I was about to attack an acidic ant.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2224-gde41139
 - Graphics version: Tiles
 - Mods loaded: Garden Pots

**Additional context**  
Crash file log says this

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2224-gde41139
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x4EA2EE[cataclysm-tiles.exe+0xEA2EE]
    @0x4EA566[cataclysm-tiles.exe+0xEA566]
    SMPEG_error+0x3DAF3@0xB611E5[cataclysm-tiles.exe+0x7611E5]
    UnhandledExceptionFilter+0x1CB@0x7674A76B[KERNELBASE.dll+0x1AA76B]
    RtlCaptureStackContext+0x1DC4F@0x771D2FFF[ntdll.dll+0xA2FFF]
    RtlGetAppContainerNamedObjectPath+0xBD@0x771965FD[ntdll.dll+0x665FD]

[Tanglewood Forest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3123640/Tanglewood.Forest.zip)

**Comment by ipcyborg** [comment] 2019-08-02 08:43
Can't reproduce on 0.D-6072-g4add125.
Possibly related to #30141.

**Comment by Night-Pryanik** [comment] 2019-10-08 11:38
No confirmation in over half a year, closing for now. Ping me if this is still an issue.

**Closed by Night-Pryanik** 2019-10-08 11:38 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Vehicles
