### ISSUE TITLE
There is no option in the % menu to use the integrated toolset for item repairs.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19943] opened 2017-01-03 19:08 UTC

**Comment by natsirt721** [comment] 2017-01-03 21:36
Probably because it's a bionic and not a tool per se.

**Comment by sethsimon** [comment] 2017-01-03 22:19
Related: #18703.

**Comment by Regularitee** [comment] 2017-01-04 01:58
Also may be a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/19489

**Comment by Asmageddon** [comment] 2017-01-04 07:33
It does let you pry manholes, so I think being able to repair metal items would make sense.

**Comment by Coolthulhu** [comment] 2017-01-04 07:51
Two problems:

First, toolset does not provide an item. An item is necessary for item repair code to work, to use the repair actor.
I a hacky solution for vehicle-mounted welders. This could be adapted relatively easily to toolset.

Second, that's a bit of an UI problem. You can't force the % menu to use a particular tool and you can't access toolset's tools in any other way (except for crafting).
If toolset had preference over tools, you'd need to turn it off or use the tools manually when trying to preserve bionic charges. If tools had preference, you'd need to drop them before using the toolset.
Still, at the moment bionic charges are very cheap, so toolset over tools would suffice.

**Comment by Asmageddon** [comment] 2017-01-04 08:07
What if it was indicated when more than one tool is available and you could press one button or the other to reorder precedence?

**Comment by Coolthulhu** [comment] 2017-01-04 08:16
That would require addressing individual items, which in turn would require item IDs, as in #19437
Or addressing the items by itemtype ID, though this one wouldn't tell apart UPS soldering iron from regular one.

In either case, also a way to preserve the state of the item action menu.

**Comment by Leland** [comment] 2017-05-08 18:19
Merging with #19489

**Closed by Leland** 2017-05-08 18:19 UTC
Labels: Information / Interface, Long-term, Suggestion (Discuss)
