### ISSUE TITLE
Impossible to stop washing stuff on the washboard

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21047] opened 2017-05-18 16:12 UTC
I was standing and washing my rucksack on a washing board. A zombie came to me and almost killed me and destroyed my rucksack while i was washing it, and i was unable to stop washing it.

**Comment by Leland** [comment] 2017-05-18 16:18
Duplicate of #21047 – agreed, this needs to change.

**Comment by l29ah** [comment] 2017-05-18 16:19
Yay a duplicate of itself!

**Closed by Leland** 2017-05-18 16:18 UTC

**Comment by Leland** [comment] 2017-05-18 16:22
@l29ah ugh, fixed. Haha
