### ISSUE TITLE
Still encountering spawn scaling factor resets

### ISSUE THREAD

**Issue by GradusNL** [CleverRaven/Cataclysm-DDA#19784] opened 2016-12-16 15:57 UTC
Supposed to be fixed a couple updates ago but even after a reinstall of the CDDA experimental launcher and the game with the new update still enounctering the resetting of all the spawn factors to either 0 or 1.
This includes inbetween setting the default world settings and generating a new world, loading that world and reloading that world after fixing it.

P.S. Anyone have a guide to correctly doing this whole issue thing?

**Comment by Aivean** [comment] 2016-12-16 18:56
[Guide to whole issue thing](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md).

**Comment by illi-kun** [comment] 2016-12-17 13:50
Duplicate of #19576.

**Closed by illi-kun** 2016-12-17 13:50 UTC
Labels: Bug
