### ISSUE TITLE
Dragging a shopping cart leaves a trail of shopping carts behind

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28512] opened 2019-03-06 07:32 UTC
**Describe the bug**  
Dragging "G" a shopping cart behind you in night time while the character can only see one tile in each direction causes a visual bug where you can see multiple shopping carts left where the actual shopping cart was in the previous tile

**To Reproduce**  
Drag a shopping cart behind you at nighttime while using a view restrictive item like a motorbike helmet

**Expected behavior**  
I expect my character to "remember" that the shopping cart he saw in the shadows is the one he got his hands on

**Screenshots**  
![shopping cart bug](https://user-images.githubusercontent.com/21698008/53863101-90284980-3fe9-11e9-9a50-caac726e687f.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37599-gd5cafd3
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Filthy clothing, Disable NPC needs, Simplified Nutrition, Generic Guns, More locations, Fuji's More Buildings, Disable Religious Texts, No Fungal Monsters, Manual Bionic Installation, Safe autodoc, StatsThroughSkills

**Additional context**  
[manual_backup3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2934976/manual_backup3.zip)
This is a link to a savegame that allows the issue to be reproduced.

**Comment by Bulletfang** [comment] 2019-03-06 11:53
It's not technically a bug, more of a fallacy that comes from how memory works in this game. I doubt there's an easy way to fix this, you'd have to make every object one can drag be an exception from memory while visual range is equal or less than 1.

**Comment by kevingranade** [comment] 2019-03-06 17:09
That's not unreasonable to do though, we already do it for driving.

**Comment by CoroNaut** [comment] 2019-03-08 04:07
Perhaps a simple fix is to not allow memory to save any vehicles you are driving or dragging? So if you let go of the cart, and grab it again, it would be in map memory as single tile, and not produce a line afterwards. Similarly with a vehicle, you would hop in and drive somewhere without memory saving any part of the vehicle behind you until you stop controlling, then it will be saved.

**Comment by junkyjb** [comment] 2019-03-12 16:11
I have a very similar issue, which I assume is caused by the same thing.

My character is spider mutated, and so has night vision.
When he's pulling one-tile vehicles at night normally this issue doesn't occur, but when he activates a reading light his night-vision reduces to one tile range - resulting in the same ghost traces above.

Though it was worth mentioning, as this wasn't caused by head gear restricting vision, since his Furred Plate mutation prevents him wearing any.

**Comment by snipercup** [comment] 2019-10-04 10:49
> Perhaps a simple fix is to not allow memory to save any vehicles you are driving or dragging? So if you let go of the cart, and grab it again, it would be in map memory as single tile, and not produce a line afterwards. Similarly with a vehicle, you would hop in and drive somewhere without memory saving any part of the vehicle behind you until you stop controlling, then it will be saved.

I like this idea but what happens when you jump out of a moving vehicle?

**Comment by MattD94** [comment] 2020-01-18 21:11
I wanted to add that not only is a trail being created, but it persists even after player can see that the trailed tiles have no vehicle on them - i.e. drag vehicle while crouched, create trail behind, stand-up and see there is no vehicle on those tiles, crouch again and trail reappears. This is on linux64 ncurses build 0.D-11440-g82a2eb2.

> > Perhaps a simple fix is to not allow memory to save any vehicles you are driving or dragging? So if you let go of the cart, and grab it again, it would be in map memory as single tile, and not produce a line afterwards. Similarly with a vehicle, you would hop in and drive somewhere without memory saving any part of the vehicle behind you until you stop controlling, then it will be saved.
>
> I like this idea but what happens when you jump out of a moving vehicle?

I would think that instead of exempting vehicles/objects from memorization only while driving/grabbing, continue to exempt it if it is still in motion after done driving/grabbing until it comes to a stop or passes completely out of visibility.
Or to state it another way: furniture and vehicles would only be memorized when they are not being grabbed or known to be stationary, respectively.

**Comment by wapcaplet** [comment] 2020-02-24 02:02
I am seeing the same behavior - the cart's full location history appears to be remembered, except on pavement tiles:

![image](https://user-images.githubusercontent.com/238395/75124844-0268c280-566f-11ea-8407-9a36f384131b.png)

**Comment by wapcaplet** [comment] 2020-09-26 00:38
Cannot reproduce in 0.E-6177-g 9f4a1b841d with UltiCa, RetroDays, or BrownLikeBears tilesets - likely was fixed by #38706. Closing issue.

**Closed by wapcaplet** 2020-09-26 00:38 UTC
Labels: (S2 - Confirmed), <Bug>, Mechanics: Map Memory, Vehicles
