### ISSUE TITLE
Reloading Glass Jars of Sugar

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#37874] opened 2020-02-10 00:46 UTC
# Describe the bug

Using the (R)eload screen displays glass jars containing sugar as valid targets. Despite the presence of other jars or loose sugar, attempting to select one results in a message about not having any sugar and the glass jar is moved to your inventory. This movement appears to be able to cause you to drop other items.

# Steps To Reproduce

1. Obtain two glass jars partially full of sugar.
2. Attempt to reload one of them.

# Expected behavior
a - No ability to attempt to reload when reloading is not possible.
b - Reloading succeeds when executed.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-11543-g3e11834
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by jkraybill** [comment] 2020-02-10 06:42
Trying to repro this. How did you obtain the partially filled jars of sugar? They are not craftable or debug-spawnable as far as I can tell.

**Comment by Drack820** [comment] 2020-02-10 13:11
> Trying to repro this. How did you obtain the partially filled jars of sugar? They are not craftable or debug-spawnable as far as I can tell.


You can find them in houses, or you can use some sugar from a full jar of sugar.

I reproduced this in my current game and I wasn't able to reload any of the types of powder that I tested (lye powder, zinc powder, sugar, acrylamide, sulfur).

**Comment by jkraybill** [comment] 2020-02-10 13:57
@Drack820 thanks -- I found an itemgroup that explicitly can spawn in sugar in glass jars, which seems to be the source of these found jars of sugar. The other powders you mentioned are defined as living in glass or plastic bottles.

I see in the code that the "reload" logic appears to never allow non-liquids to be transferred between bottles. While it would be ideal to fix that logic, one quick workaround would be to remove the itemgroup definition that can spawn sugar in glass bottles, and also to re-define these powders (lye powder, zinc powder, acrylamide, sulfur, I guess there are probably more) as existing in cardboard boxs.

**Comment by jkraybill** [comment] 2020-02-10 14:34
Also found an instance in data/json/itemgroups/SUS/domestic.json of powdered milk spawning in glass jars.

I think the right solution is to allow the refill/reload logic to treat powders like liquids, where it currently appears to treat them as non-refillable solids. Failing that, an alternative (easier?) solution would be to never spawn powders in plastic or glass bottles and re-define the substance containers as bags or boxes or large tin cans.

**Comment by TechyBen** [comment] 2020-02-10 18:31
I think jars and bottles might be part of the inventory refactor/changes. So this might get amended soon.

**Comment by Karthas077** [comment] 2020-02-10 18:54
It will probably be fixed by the container changes that are coming, but I thought it would be worth noting that this is a current problem to make sure that it's taken into account.

**Comment by wapcaplet** [comment] 2021-02-19 23:27
I could not reproduce this in 0.E-9737-g511ddcb179. Since the nested containers overhaul, solids like sugar cannot be `r`eloaded into a glass jar, but they can be `i`nserted. Liquids such as water can be `r`eloaded into a glass jar.

**Closed by wapcaplet** 2021-02-19 23:27 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
