### ISSUE TITLE
bad optional access when trying to learn a spell from a book that contain spells from mutually exclusive schools of magic

### ISSUE THREAD

**Issue by HadeanLake** [CleverRaven/Cataclysm-DDA#76118] opened 2024-09-01 17:38 UTC
### Describe the bug

Game crashes with `bad optional access` message when player tries to read again from the book that contains spells from mutually exclusive schools of magic if the character already knows spells from one of those schools. 
`The Home Mage's Healthcare Manual` is an example of such book

### Attach save file

saved with `The Home Mage's Healthcare Manual` in inventory
[toomanymagics-bad_optional_access-trimmed.tar.gz](https://github.com/user-attachments/files/16829929/toomanymagics-bad_optional_access-trimmed.tar.gz)

### Steps to reproduce

1. Learn a spell from `The Home Mage's Healthcare Manual`
2. Agree to become biomancer or druid and be locked out of the other school
3. Try to read `The Home Mage's Healthcare Manual` again

### Expected behavior

no crash

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-01-1411 746a170 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by RenechCDDA** [comment] 2024-09-01 18:00
Duplicate of #76110

**Closed by RenechCDDA** 2024-09-01 18:00 UTC
Labels: (S1 - Need confirmation)
