### ISSUE TITLE
Tools broken

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10888] opened 2015-01-15 17:24 UTC
Knives in boots don't count as 'tools' anymore. Welders also do nothing when attempting to build vehicles. Both Acetylene torches and battery powered welders, as well as vehicle mounted welders.

**Comment by DavidKeaton** [comment] 2015-01-15 21:15
Anyone else able to confirm?

**Comment by KA101** [comment] 2015-01-16 00:40
Was working fine last night, hang on.

**Comment by DavidKeaton** [comment] 2015-01-16 01:58
So unable to reproduce? What system and build OP?

**Comment by EkarusRyndren** [comment] 2015-01-16 05:11
0.B-2636

**Comment by DavidKeaton** [comment] 2015-01-16 06:56
Right on. Thanks matey. As a side note tested on latest git, seems fine? But I'm on Linux...

**Comment by KA101** [comment] 2015-01-16 07:13
Yeah, that's 10 builds old ATM.  Possible it was when we had the broken JSON parser--that knocked out a LOT.  Gonna recommend updating: if that doesn't cure the problem, let us know

**Comment by DavidKeaton** [comment] 2015-01-16 11:52
The windows build numbers _may or may not_ completely confuse me. Where are they derived from?

**Comment by Zireael07** [comment] 2015-01-16 12:23
Take a look at dev.narc.ro site where the builds are hosted.

**Comment by narc0tiq** [comment] 2015-01-16 12:49
The build numbers are sequentially assigned by the Jenkins process. See
http://ci.narc.ro/job/Cataclysm-Matrix/

Alternately, there are the `git describe` version numbers, consisting of
0.x-1234-g123af4, where the first part is the nearest tag, the second is
how many commits after the tag we are, and the "g123af4" part is the
leading part of the commit hash. Jenkins builds don't get a full describe
output, but only the "g123af4" part, because they don't have a complete
history of the repo.

Entertainingly, "0.B-2636" could almost be read as either one. We're
assuming it means "Jenkins build 2636" (here:
http://ci.narc.ro/job/Cataclysm-Matrix/2636/), which would make it version
"g701fd7" (commit 701fd7010c30620e313ad32754c5259f2dbfba33). Goodness only
knows if that's true.

**Comment by DavidKeaton** [comment] 2015-01-16 13:32
Thanks guys: -)

**Comment by codrus** [comment] 2015-03-26 16:46
Confirming welder isn't working. I have a makeshift welder (full of batteries) and when I try to put a tire on my vehicle it says I need a "powered welder".

I'm running windows console 1cb6e13 version.

**Comment by BevapDin** [comment] 2015-03-26 16:51
Welding goggles in reach?

**Comment by codrus** [comment] 2015-03-26 17:09
My issue was goggles in trunk of car not reaching front of vehicle. Thanks. Removed my post.

**Comment by KA101** [comment] 2015-03-27 03:55
Pretty confident we can close this.

**Closed by KA101** 2015-03-27 03:55 UTC
Labels: Confirmation Needed
