### ISSUE TITLE
Nested containers mutate contents when unloading parent container

### ISSUE THREAD

**Issue by mioxyz** [CleverRaven/Cataclysm-DDA#40711] opened 2020-05-19 23:10 UTC
# Description
If a nested container contains something which can have an amount, such as batteries, lighters, fluid containers, etc., and one unloads said container, then the amount of all unloaded items are set to »1 of n«.
# Steps To Reproduce
1. spawn a backpack
2. spawn a lighter
3. wear backpack
4. place lighter into backpack
5. unload backpack
# Expected behavior
The amount of charges of the lighter should've stayed the same.
# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-2281-g5ec198f192 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by mioxyz** [comment] 2020-05-19 23:44
I just looked at the `bool player::unload( item_location &loc )` method in player.cpp, what I find weird is that the item is removed from the set, but it isn't being moved to the overlying container (or maybe it is being emitted upwards, somehow). I have the feeling like the item is being destroyed and then recreated instead of moved one level up in the container tree, which might be the problem

**Comment by KorGgenT** [comment] 2020-05-24 02:42
i can't reproduce this because lighters changed. i tried unloading a large plastic bottle of salt water, and it didn't mutate.

**Comment by KorGgenT** [comment] 2020-05-24 02:42
![image](https://user-images.githubusercontent.com/30208401/82744441-a46b7a00-9d46-11ea-8ced-75993800f7a9.png)

**Comment by wapcaplet** [comment] 2020-09-26 03:02
Cannot reproduce in 0.E-6177-g 9f4a1b841d

Backpack with flare, water bottles, lighter, inhaler, and battery:

![image](https://user-images.githubusercontent.com/238395/94328738-24faeb00-ff72-11ea-8372-e9777130dde3.png)

After `U`nloading the backpack, all items retain their charges/contents:

![image](https://user-images.githubusercontent.com/238395/94328765-64293c00-ff72-11ea-8df3-66beae11497d.png)

Closing issue.

**Closed by wapcaplet** 2020-09-26 03:02 UTC
Labels: (S1 - Need confirmation), <Bug>, Items: Containers
