### ISSUE TITLE
"Made from" components are not taken into account when grouping/stacking certain items

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20148] opened 2017-01-29 01:13 UTC
Dropping item X made of MAT1 onto X made of MAT2 results in two Xs made of MAT2.

Tried with ropes and blindfolds. Possibly affects all items where recipe allows multiple components, item can be disassembled, and no "deconstruction" (disassembly, uncraft) recipe is provided.

**To reproduce:**

* cheat-wish short rope, 30 rags and 30 leather patches;
* drop the rope;
* craft short rope from rags, drop it somewhere else;
* craft short rope from leather;
* drop the last rope onto either of the other two.

It will lose its "Made from" (`components`) and acquire those of the item being dropped on.

Same with picking up to inventory.

Not sure if regression. Found when testing for #18153.

EDIT2: Checked on fc7b3ba (Nov 30, 2016) - present.

Arch Linux 64-bit, current git master (`0.C-20882-g68523bfd0e`), self-built, curses.

-----

EDIT: Tried searching if already reported, either it wasn't or my terms were too specific.

**Comment by Asmageddon** [comment] 2017-01-29 23:38
Somewhat to the contrary, I had hotplates(made a bunch to get around the charges limitation of vehicle chemlab) made from different materials simply refuse to stack, and not sure if it didn't take something like component HP or idk into account, since I tried to craft more with same material set and it failed to stack as well.

**Comment by keyspace** [comment] 2017-01-30 12:34
> not sure if it didn't take something like component HP or idk

Need to check separately, maybe due to hotplates having charges.

**Comment by Asmageddon** [comment] 2017-02-05 12:49
They were all UPS-modded and fully charged, I really do not know what was to blame, there.

**Comment by Qrox** [comment] 2017-05-14 11:32
Another similar issue: tanning pelts with different finish time also stack, and `a`ctivating the stack will not unroll pelts which are already done.

**Comment by illi-kun** [comment] 2018-02-21 22:12
I'm not able to reproduce this bug.

Stacked short ropes from rags and from leather patches presented in inventory as
```2 short ropes, made of 30 x leather patch``` (which is minor incorrectness for me) but when you drop them one by one to the floor you see the correct materials:
```short rope, made of 30 x leather patch```
```short rope, made of 30 x rag```

**Comment by OliveChukar** [comment] 2021-01-21 19:16
Tested in ver 0.E-9072-g1bb53ba-dirty with core content pack dark days ahead only. Crafted short strings from all materials they can use.  They all went into the same stack and did not show what they were made from. When I disassembled the entire stack they did give back the correct materials.

**Comment by anothersimulacrum** [comment] 2021-01-22 03:34
Closing as fixed, then. If anyone objects, please let me know and I can reopen it.

**Closed by anothersimulacrum** 2021-01-22 03:34 UTC
Labels: (S1 - Need confirmation), Info / User Interface

**Comment by Asmageddon** [comment] 2021-02-03 11:33
@OliveChukar @anothersimulacrum What about hotplates refusing to stack due to charges or something as per my comment? (not really the same issue, but)

**Comment by anothersimulacrum** [comment] 2021-02-03 16:38
If you can reproduce it, please let me know.

**Comment by Asmageddon** [comment] 2021-02-09 20:13
I don't really play CDDA nowadays. I will, again, but not soon.
