### ISSUE TITLE
When trying to make a map with the mod "Medieval and Historic Content" enabled it gives me a error.

### ISSUE THREAD

**Issue by alexantosk** [CleverRaven/Cataclysm-DDA#27057] opened 2018-12-10 16:57 UTC
**Describe the bug**  
When trying to make a map with the mod "Medieval and Historic Content" enabled it gives me a error.

**To Reproduce**  
1. Make a map with the Medieval and Historic Content enabled

**Expected behavior**  
No Error

**Screenshots**  
https://imgur.com/a/r4wPXKw

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version [0.C-35104-g2efbc37]
 - Graphics version [Tiles]
 - Mods loaded [Medieval and Historic Content]

**Additional context**  
I'm useing the CDDA launcher found here https://github.com/remyroy/CDDA-Game-Launcher/releases

**Comment by Ker-Nes** [comment] 2018-12-10 17:10
I think it's the same issue as #27048 ? Good news is that it should be fixed soon with once PR #27045 gets merged, assuming it is.

**Comment by Leland** [comment] 2018-12-10 17:21
Duplicate of #27048

**Closed by Leland** 2018-12-10 17:21 UTC
