### ISSUE TITLE
Ranch camp quests - broken generation

### ISSUE THREAD

**Issue by Soviet-Russia** [CleverRaven/Cataclysm-DDA#32819] opened 2019-08-01 17:04 UTC
Game version: 0.D-6072-g4add125 Build 9408

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: None, any mods.

There is a ranch camp quest going after the Free mercants. If we wind a clock back to some time, there is foreman and a carpenter spawning inside a garage, but there is where buggy crap begins - they are spawning on a backyard. After some quests gone there is doors and walls spawning, as you can guess, totaly NOT on their sites. After finishing another quests foreman, carpenter and some another NPCs teleporting away to realy random part of a ranch. This how barn looks like after every foreman quests finished.

![unknown](https://user-images.githubusercontent.com/38297410/62312609-08673e00-b4a8-11e9-99cc-e3b701a04afa.png)

**Comment by ZhilkinSerg** [comment] 2019-08-01 18:12
Possible duplicate of #32424

**Closed** 2019-08-07 05:10 UTC
Labels: (S1 - Need confirmation), <Bug>, Missions
