### ISSUE TITLE
Bug with quests regarding Lapin warrener

### ISSUE THREAD

**Issue by coolmanabdul** [CleverRaven/Cataclysm-DDA#49480] opened 2021-06-27 21:07 UTC
# Describe the bug
You cannot turn in the quest required by Lapin warrener which requires 5 logs. For context I could not carry the logs so I dragged them to him and he refused to take them or take each log individually.

# Steps To Reproduce
head to lapin warrener either spawn or get 5 logs and attempt to give it to him

# Expected behavior
It should allow you to turn the logs in but due to a bug it will not allow you or even turn them in individually.

# Screenshots
![image](https://user-images.githubusercontent.com/68766211/123559311-3bd0a700-d769-11eb-8bfb-f4f7d82926ea.png)
![image](https://user-images.githubusercontent.com/68766211/123559318-425f1e80-d769-11eb-92ff-c1e1188c5bbf.png)
![image](https://user-images.githubusercontent.com/68766211/123559357-83efc980-d769-11eb-8474-961ee0c761b7.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a0a4318 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by Maleclypse** [comment] 2021-06-28 00:28
Quest is working fine on 
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: af4b28f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Aftershock Magiclysm requirements fix [afs_magiclysm_requirements],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
 Are you on the stable version?

**Comment by Maleclypse** [comment] 2021-06-28 01:18
Can you upload a save where this isn't working?   I downloaded the most recent release and it worked fine with five logs next to him and speaking to him.

**Comment by Founded1992** [comment] 2021-06-28 21:27
I'm not able to confirm the issue directly, but accepting both of Lapin's quests - the Log retrieval and meeting the Isherwoods - prevents you from completing the log quest until having completed the Isherwood quest. The mission dialogue upon initial interaction refers to the Isherwoods, and Lapin doesn't have any dialogue options to discuss the log quest in the interim.

This was tested on the most recent experimental (Windows Tiles 2cc3f48) with a vanilla world.

**Comment by Maleclypse** [comment] 2021-06-28 22:39
@John-Candlebury I thought you had a similar issue with Hub01 quests, were you able to resolve it in a way I'd be able to copy?

**Comment by Ochrad** [comment] 2021-09-29 19:02
I encountered this recently. The issue is replicated by taking both missions from Lapin at the same time (Visit Isherwoods and Collecting Logs), the conversation options is getting locked on Isherwoods mission ("Have you checked on them?") got it fixed by modifying the mission condition tag in the savegame file.

**Comment by John-Candlebury** [comment] 2021-09-30 02:01
Oh yeah then you need to add a dialogue option that covers you having more than a single mission. The intercom has one, you can copy it from there,

**Closed** 2021-12-17 15:09 UTC
Labels: NPC / Factions, (S2 - Confirmed), Missions
