### ISSUE TITLE
Lit fires do not continue burning, even with sufficient fuel.

### ISSUE THREAD

**Issue by JeremiasB** [CleverRaven/Cataclysm-DDA#45456] opened 2020-11-16 17:25 UTC
# Describe the bug

Lit fires die out in a few turns even if there is enough fuel for them to continue burning.
The lit fire does sometimes turns a single item of the stack into a burnt version but it never last longer than a few turns.
This behaviour happens in and outside a container for the fire and it also happens inside so it's not rain extinguishing the fire.

# Steps To Reproduce
1. Try to light a plank on fire. 
2. Watch as the fire dies in a few turns without consuming the plank.

# Expected behavior

The fire continues to burn until all available fuel is consumed or it is extinguished.

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7569-g532b9fe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
This bug seems to have been introduced with  [Build 1152](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/11152/changes).
In older builds fire behaves as expected.

**Comment by anothersimulacrum** [comment] 2020-11-16 17:26
Thank you for the report!
Duplicate of #45318
There's a fix underway at #45431

**Comment by JeremiasB** [comment] 2020-11-16 17:27
Yeah, just saw that. 
My bad.

**Closed** 2020-11-16 17:26 UTC
