### ISSUE TITLE
How can we fix vehicle tile teleporation but keep vehicle rotation pretty?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11857] opened 2015-03-30 19:31 UTC
I'm having little luck over in #11690 with my idea for rotating vehicles more smoothly. I am creating this new issue to seek alternate solutions to the problem.

Here's an illustration of the problem. We have a bus made of Xs (and ABCDF), heading just south of southeast, headed for a collision with the T:

```
...t...........
...............
.XXXAB.........
..XXXCD........
...XXXXX.......
....XXXXX......
.....XXXXX.....
......XXXXX....
.......XXXXX...
........XXFXX..
...............
...............
............T..
```

Attempting to turn left, to point just east of southeast and drive around the T, leads to the B corner of the bus jumping two squares and coinciding with the t:

```
...t...........
...AD..........
...XCX.........
...XXXX........
...XXXXX.......
....XXXXX......
.....XXXXX.....
......XXXXX....
.......XXXX....
........XXF....
.........XX....
..........X....
............T..
```

Because the vehicle is 5 tiles wide, its corners teleport two whole tiles when transitioning across any diagonal heading (44 to 46 degrees, 134 to 136, etc). A 6 tile wide vehicle (like the luxury RV with mirrors) might have two of its corners teleport three tiles.

How can we fix this without making vehicle interiors an ugly mess of shuffled tiles?
##

**Comment by Coolthulhu** [comment] 2015-03-31 02:07
This doesn't really sound doable. It's either aesthetics (and more importantly - information availability) or functionality.
With tilesets it could be doable by allowing rotated tiles, but ASCII is limited to at most 8 directions (and not for all parts).

**Comment by sparr** [comment] 2015-03-31 02:12
@Coolthulhu 8-way rotation in tilesets is something I do want to support, especially when isometric/zelda perspectives are happening.

**Comment by facepalm** [comment] 2015-03-31 02:25
Aren't slanted vehicle interiors _already_ ugly messes of shifted tiles?  Half the time I can walk right out between the walls of my car, no door necessary.  Ugly it up, let's see what happens.

The only thing I think will be necessary to add is to make sure that when something is hit by a car, it takes damage from the best tile orthogonal to it (which will always be a front-bumper tile), but receives an impulse in the direction of the car's motion.  So if a car is moving leftwards and up at a 30-degree angle, the zed will get "hit" by the tile to its left, but go flying backwards left-and-up at 30 degrees.

**Comment by sparr** [comment] 2015-03-31 02:56
@facepalm vehicles aren't always traveling in the direction that their bumper points. and monsters can walk into the side of a moving vehicle. so it's definitely not certain that only the front of the vehicle will incur impact.

**Comment by facepalm** [comment] 2015-03-31 04:13
You're right.  It would be better to have non-vehicle things be "hit" by _all_ adjacent tiles, falling back to orthogonal-only if at least one such surface exists (otherwise zombie gunk would slip through and damage "interior" tiles if the car was at an angle).  Then calculate impact from each tile based on vehicle motion, capping at 0 the influence of tiles which aren't moving towards from the thing.

**Comment by sparr** [comment] 2015-04-03 16:40
@facepalm also, re "ugly it up", I already did that over in #11690

**Comment by sparr** [comment] 2015-04-12 01:32
What about this?

    aaaaa
    bbbbb
    ccccc
    ddddd
    eeeee
    fffff

    aaaaa
    bbbbb
     ccccc
     ddddd
      eeeee
      fffff

      a
     aab
    aabbc
     bbccd
      ccdde
       ddeef
        eeff
         ff

    ab
    abcd
    abcdef
    abcdef
    abcdef
      cdef
        ef

    abcdef
    abcdef
    abcdef
    abcdef
    abcdef

This doesn't eliminate the tile teleportation problem, but it does reduce it, while keeping diagonal vehicles prettier than in my smooth skew PR.

**Comment by kevingranade** [comment] 2015-04-25 16:32
That's a good compromise, just invoke the worse-looking skew code on 45 degree angles.   The teleportation thing is definitely a problem.

**Comment by Asmageddon** [comment] 2016-05-14 02:22
Related: Is being able to walk through walls in rotated vehicles fixed yet? I was going to fix that back when I tried contributing, but I gave up after my crafting refactoring and fixes were rejected.

**Comment by illi-kun** [comment] 2016-11-06 19:09
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-06 19:09 UTC
Labels: Suggestion (Discuss)

**Comment by Asmageddon** [comment] 2016-11-07 08:27
Oh. I forgot to ever post my solution concept, which I think isn't that complex:

 - First, compute pathability for the 8 directions possible, storing them in a bitmask.

 - Since completely encased blocks are impossible to path anyway, 255 could be used as a "don't check the mask" flag for non-vehicle bits of terrain, so as to impact less of a performance cost.

 - Certain diagonal directions could become unpathable in rotated vehicles, the two options are to accept that limitation and design vehicles around it(IMO should be acceptable), or restrict this to being done only for inside-outside boundary... but deciding what that is can be a problem.

 - After that, modifying the LoS/pathing code shouldn't be too huge of an issue, I think I remember looking at it and it wasn't as impossible of a mess as it could be.
