### ISSUE TITLE
Dropping action from wielding needs to account for volume of wielded item leaving inventory

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16637] opened 2016-05-11 22:26 UTC
After wielding an item, the action menu that pops up for dealing with the item no longer being wielded doesn't account for the volume of the new item to being wielded (provided it's from your inventory) for placing it in your inventory. That is to say, if I take two items of identical volume, item a I am wielding and item b which I have in my inventory, both have identical volume and my inventory is maxed. Wielding item b will give me an action menu with only the option to drop item a. Is this functionality intentional or could something be added to check for the volume of items being wielded to determine if the inventory would still be full after being wielded?

**Comment by Labtop-215** [comment] 2016-05-12 06:12
It sounds like you need to free you hands first, and then pick up the item from your inventory.

**Comment by Hague** [comment] 2016-05-12 14:15
I'm already freeing my hands by wielding the other object. It's also possible to carry more than one object in a single hand and this occurs even with another free hand so that point doesn't make much sense. The game doesn't track what your other hand does (yet) so that implies that most weapons allow a free hand regardless. Just a step to reduce tedious micromanagement.

**Comment by nanovad** [comment] 2016-05-12 21:39
~Duplicate of #16629, though this is better describes the issue. (both were posted at the same time, it seems?)

**Comment by wapcaplet** [comment] 2021-02-16 03:39
Tested in 0.E-9681-g2cca4d658c. I believe this is working correctly.

Because wielding does not simulate the use of two hands, when the "inventory volume" (total worn container volume) is full, and an item is currently being wielded, if you want to wield a different item from your inventory, you will need to drop the item you are wielding first.

For example here I have three porkpie hats labeled A, B, and C. They are 1.25 liters each. Porkpie A is currently wielded, while B and C are in my 2.5-liter fanny pack:

![image](https://user-images.githubusercontent.com/238395/108015211-efac7380-6fcc-11eb-9f8e-eba704b3f2ce.png)

In order to wield Porkpie hat B, I must first decide what to do with hat A being wielded:

![image](https://user-images.githubusercontent.com/238395/108015426-78c3aa80-6fcd-11eb-9473-735fba3ad8ee.png)

This is because I have no room left in my inventory to put away hat A before wielding hat B. By dropping hat A first, I can wield B, then pick up A to put back in my fanny pack (thus filling my inventory to maximum again):

![image](https://user-images.githubusercontent.com/238395/108015554-b9bbbf00-6fcd-11eb-9d67-4ba7c1bb1f8d.png)

This appears to be working as intended.

**Closed by wapcaplet** 2021-02-16 03:39 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface, Inventory / AIM / Zones
