### ISSUE TITLE
Item conflict when crafting using UPS welder tool in a recipe requiring welders

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23730] opened 2018-05-14 17:55 UTC
Game version: Currently 0.C-27777

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior 
Given I have everything required, I can craft the object I want to make (details below).

### Actual behavior and steps/circumstances to reproduce it
Recipe is as follows:
![uhoh](https://user-images.githubusercontent.com/38487938/40014201-2e2970be-57b0-11e8-9bfc-80cf484e40cb.png)
I currently have all the skills required and ingredients, however the game becomes dumbstruck as I have three makeshift welders in my inventory - one charged and UPS-modified and two uncharged ones. It presumably makes the game confused which welder is meant for what so it just flags them all as unsuitable.

Dropping the UPS welder elsewhere while still holding two "empty" ones so the game will default to acetylene torch I have nearby to be used as a crafting tool fixes the problem.

**Comment by l29ah** [comment] 2018-05-16 08:15
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/19461

**Closed** 2018-05-16 08:59 UTC
