### ISSUE TITLE
crafting water with water purifier causes ERROR: item_contents::only_item called with 0 items contained

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#61907] opened 2022-10-25 02:14 UTC
### Describe the bug

 Get this error when crafting clean water using nearby water purifier.

```
DEBUG    : ERROR: item_contents::only_item called with 0 items contained

 FUNCTION : const item& item_contents::only_item() const
 FILE     : src/item_contents.cpp
 LINE     : 1400
 VERSION  : c75285b

```

### Steps to reproduce

1. Loan my save.
2. Try to craft purified water using water purifier method.
3. Get error.
[Framingham.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9856583/Framingham.zip)

### Expected behavior

No error.

### Versions and configuration

- OS: Win10x64
- Version: c75285b
- Graphics: Tiles
- Language: Eng
- Mods: none

**Comment by EIIKaO** [comment] 2022-10-29 04:38
This seems to be caused by the existence of the **multi cooker with the battery installed**( will not occur if the battery is removed ).
However, I could not understand how to solve the problem better.

**Comment by RenechCDDA** [comment] 2022-11-05 04:06
Thank you, that made it easy to track down. I can confirm the above - the multi cooker is causing it, and removing the battery prevents the error from occurring. 

I also found that removing the multi-cooker's second pocket (of type `CONTAINER`) prevents the error from occurring. Changing the order of the pockets so that the `CONTAINER` pocket is first also prevents the error from occurring.

The occurrence of this bug is directly related to the crafting function `Character::check_eligible_containers_for_crafting` which checks `item_ptr_compare_by_charges` which calls `item_contents::only_item`, which is what's spitting out the error.

The below seems to work after testing but I'm wary of touching the crafting code. 

```diff --git a/src/crafting.cpp b/src/crafting.cpp
index 216f2a4e90..b413daff52 100644
--- a/src/crafting.cpp
+++ b/src/crafting.cpp
@@ -461,9 +461,11 @@ bool Character::check_eligible_containers_for_crafting( const recipe &rec, int b

 static bool is_container_eligible_for_crafting( const item &cont, bool allow_bucket )
 {
-    if( cont.is_watertight_container() && cont.num_item_stacks() <= 1 && ( allow_bucket ||
-            !cont.will_spill() ) ) {
-        return !cont.is_container_full( allow_bucket );
+    for( const item *it : cont.all_items_top( item_pocket::pocket_type::CONTAINER ) ) {
+        if( cont.is_watertight_container() && cont.num_item_stacks() <= 1 && ( allow_bucket ||
+                !cont.will_spill() ) ) {
+            return !cont.is_container_full( allow_bucket );
+        }
     }
     return false;
 }

**Comment by snipercup** [comment] 2023-07-23 17:48
I have this issue too

``` DEBUG    : ERROR: item_contents::only_item called with 0 items contained

 FUNCTION : only_item
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_contents.cpp
 LINE     : 1543
 VERSION  : f43a3a8
```
I have it with this crecipe
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/90e3baed-7b2e-4659-a69c-4d903ac359c1)

It's using the food processor, not the multicooker but when I remove the battery from the food processor, I can't make the recipe.

You can repreduce the issue by loading this save:

[Rainsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12139572/Rainsville.zip)

**Comment by Night-Pryanik** [comment] 2024-10-18 12:07
Since neither water purifier, nor multi-cooker, nor food processor don't operate on batteries anymore, I guess the issue is gone?
I tested with water purifier connected to my car, while I have multi-cooker in my inventory. Got no errors. Closing until reconfirmed.

**Closed by Night-Pryanik** 2024-10-18 12:07 UTC
Labels: (S2 - Confirmed)
