### ISSUE TITLE
objects in hand weigh nothing

### ISSUE THREAD

**Issue by W5Rusk** [CleverRaven/Cataclysm-DDA#43459] opened 2020-09-04 15:56 UTC
![изображение](https://user-images.githubusercontent.com/39480430/92259604-fb552380-eedf-11ea-9510-0480d3d04c36.png)
some objects, if you take them in hand, do not count their weight and volume. If they hit something, they usually begin to read it. The latest version of the game.

**Comment by eilaattwood** [comment] 2020-09-04 16:48
Duplicate of #43328  ?

**Comment by wapcaplet** [comment] 2020-10-22 02:58
Indeed, appears to be a duplicate - and resolved already by #44661. The item wielded in the screenshot, ядерная мини-бомба (yadernaya mini-bomba, "nuclear mini-bomb"), appears to be a mininuke; I could not reproduce the issue while wielding a mininuke in 0.E-7041-gdb7d1378fa - the weight is correctly reflected in my total capacity. Closing issue.

**Closed by wapcaplet** 2020-10-22 02:58 UTC
Labels: <Bug>
