### ISSUE TITLE
Copying from martial arts for editing with mods creates duplicate entry

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#19128] opened 2016-11-03 18:25 UTC
I had intended to use the older 'edit-mode' system to streamline the martial arts edits in the Arcana and Magic Items mod.

````
  {
    "type": "martial_art",
    "id": "style_niten",
    "edit-mode": "modify",
    "add:weapons" : ["bloodscourge", "scourge_staff"]
  }
````

I discovered this example did not correctly override the martial art in question, instead creating a duplicate in the martial arts list.

**Comment by mugling** [comment] 2016-11-03 19:26
This requires updating of the martial art types to use the `assign` functions. That's definitely on the list but at present `MONSTER`, `furniture` and `terrain` are higher priority.

Closing not because it's not an issue but because there's no need to track the progress for each type independently.

**Closed by mugling** 2016-11-03 19:26 UTC

**Comment by DangerNoodle** [comment] 2016-11-03 19:28
Is there a present issue listing all features yet to be updated to permit copy-from?

Apologies for that.

**Comment by mugling** [comment] 2016-11-03 19:31
* You can `copy-from` everything that was originally supported via `edit-mode`
* You can `extend`/`delete` from most simple arrays
* For anything else only `MONSTER` has support (approx 50% and increasing)

**Comment by DangerNoodle** [comment] 2016-11-03 19:38
> You can copy-from everything that was originally supported via edit-mode

Incorrect. I was able to edit martial arts using edit-mode previously, but could not implement it in my prior pull request due to merge conflicts.

**Comment by mugling** [comment] 2016-11-03 19:41
> You can copy-from everything that was originally supported via edit-mode

Your confusing the ability to `copy-from` and the ability to use the `extend`, `delete`, `relative` and `proportional` operators.

**Comment by DangerNoodle** [comment] 2016-11-03 19:58
I see. I am guessing that you mean you can use copy-from to make derivatives of anything previously supported by edit-mode, but your options are limited and it does not support recursive copying?

**Comment by mugling** [comment] 2016-11-03 20:02
Recursive means something slightly different. Sequential inheritance is supported

**Comment by DangerNoodle** [comment] 2016-11-03 20:04
Ah, I meant overriding the base via making the ID and the copy-from entries identical. Like what was demonstrated in 'realguns' and in the original post here. I am unsure what the term is.

**Comment by mugling** [comment] 2016-11-03 20:07
That should be supported fine. What you can't do is redefine some fields yet in your copy.

**Comment by DangerNoodle** [comment] 2016-11-03 20:08
Except it created a duplicate, which sounds like behavior indicative of not being supported.

**Comment by mugling** [comment] 2016-11-03 20:11
What created a duplicate? Can you post example JSON?

**Comment by DangerNoodle** [comment] 2016-11-03 20:12
Read the description of the first post on this issue. I posted an example that, when used in place of the current method of overriding the martial art (in arcana/martialarts.json) creates a duplicate.

It is also stated overtly in the issue title.

**Comment by mugling** [comment] 2016-11-03 20:16
What creates a duplicate of what though?

**Comment by DangerNoodle** [comment] 2016-11-03 20:18
Using that method of editing the martial art makes two versions of the same style show up on the martial arts list, when pressing '_'.

**Comment by DangerNoodle** [comment] 2016-11-03 20:19
Let me procure a screenshot.

**Comment by mugling** [comment] 2016-11-03 20:21
Please post your JSON

**Comment by DangerNoodle** [comment] 2016-11-03 20:26
My apologies, I just realixed what I originally pasted was the older use of edit-mode, not copy-from. One moment.

**Comment by DangerNoodle** [comment] 2016-11-03 20:40
There we go. JSON is:

````
  {
    "id": "style_silat",
    "copy-from": "style_silat",
    "type": "martial_art",
    "name": "Silat",
    "extend": { "weapons": ["bloodscourge", "scourge_staff", "spear_pestilence"] }
  },
  {
    "id": "style_fencing",
    "copy-from": "style_fencing",
    "type": "martial_art",
    "name": "Fencing",
    "extend": { "weapons": ["sun_sword", "sun_sword_on"] }
  },
  {
    "id": "style_niten",
    "copy-from": "style_niten",
    "type": "martial_art",
    "name": "Niten Ichi-Ryu",
    "extend": { "weapons": ["bloodscourge", "scourge_staff"] }
  }
````

Strangely, I discovered that the anomaly showed up only when debugging for all styles. It did not generate any duplicates in the "pick style after character creation" screen, nor did it create any anomalies on the martial arts selection screen.

**Comment by DangerNoodle** [comment] 2016-11-03 20:41
This seems to be a debug-only error, if that is the case. My apologies.

**Comment by DangerNoodle** [comment] 2016-11-04 18:49
I just realized another potential failure of copy-from. If multiple mods attempt to use "ID copies from source of same ID" to expand properties, how is this parsed?

With edit mode, multiple mods could add things, for example adding mod-only weapons to the list of options in a martial art. But if both use this method of copy-from, will both succeed in placing their desired additions in the object being modified?
