### ISSUE TITLE
Unequipping NPC Clothing Causes a Crash To Desktop

### ISSUE THREAD

**Issue by ChronicDankDisasterAlgorithm** [CleverRaven/Cataclysm-DDA#23394] opened 2018-04-06 20:14 UTC
Game version:
0.C-27229-gae5bdc0 Build 7286
Operating system:
Win 10 Home 64-bit
Tiles or curses:
Tiles
Mods active:
Mining Mod, More Survival Tools, StatsThroughSkills, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Folding Parts Pack, Necromancy, Disable NPC Needs, Extended Realistic Guns
### Expected behavior
(u)nequiping NPC clothing should take off the clothing item
### Actual behavior
(u)nequipping NPC clothing causes a Crash To Desktop
### Steps to reproduce the behavior
Examine an NPC then select (r) 'sort armor'  and then press (u) on a piece of clothing

When I do it to safety glasses it correctly unequipped them, but cowboy hat and leather pants did cause the crash. I haven't tried other articles of clothing besides the ones mentioned.

**Comment by KongMD-Steam** [comment] 2018-04-06 22:11
I can reproduce the issue on build 7285. This is the last output in my debug.log file. The same message repeats over more lines that what I've posted here.
```
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
18:7:59.601 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
```

**Comment by ChronicDankDisasterAlgorithm** [comment] 2018-04-06 22:43
After I gave them some different clothing through the dialogue screen (I want you to use this item)  I was then able to unequip the clothes that previously had caused the crash. So I dunno what was going on.

**Comment by KongMD-Steam** [comment] 2018-04-07 11:47
There's a race condition in the remove armor code. I fired up the same save 10 times and removed all armor from the NPC, starting from the top. The only crashes I got were when removing pants and removing military rucksack. 2/10 attempts crashed.

Mods: Base game only.

In a different save, I got this error when removing boots:
![remove_armor_bug1](https://user-images.githubusercontent.com/36478131/38454577-cd8fc4e6-3a37-11e8-89f3-9f135597df57.jpg)

**Comment by ChronicDankDisasterAlgorithm** [comment] 2018-04-07 16:05
Yeah I think it dupes the item you take off as well.

**Comment by SolsticeTheTechMarine** [comment] 2018-04-10 04:53
Can confirm that attempting to remove clothing from an npc causes a crash. Appears to also happen when applying clothing to npc, though this could also be the npc removing clothing and thus causing a crash.

**Comment by Lamandus** [comment] 2018-04-10 09:07
It may be happening when the amount of possible volume he can carry of the rest he wears exceeds the amount already in his inventory. Especally removing rucksacks (for me) causes this crash (when the NPC is transporting stuff, of course).

**Comment by Maeyanie** [comment] 2018-05-26 20:45
I did some debugging on this as part of issue #23799 (without realizing it was a duplicate), but this thread seems more complete so I'll summarize it here. Backtraces and other long stuff can be found there.

Basically the problem seems to be that when an NPC tries to [takeoff()](https://github.com/CleverRaven/Cataclysm-DDA/blob/e8166a043b48036fe3fcffc616cae64b2d04a9fd/src/player.cpp#L7934) an item, which would put it over its capacity, it [drop()](https://github.com/CleverRaven/Cataclysm-DDA/blob/e8166a043b48036fe3fcffc616cae64b2d04a9fd/src/player.cpp#L7949)s it. However, within drop(), it [tells the NPC to process the activity](https://github.com/CleverRaven/Cataclysm-DDA/blob/e8166a043b48036fe3fcffc616cae64b2d04a9fd/src/player.cpp#L8013).
This causes the NPC to call takeoff() again, while still in the middle of the first call. That one succeeds (because it's called with res != null), modifies the equipment list, and invalidates the iterator in the outer call, causing a crash [when it is then used](https://github.com/CleverRaven/Cataclysm-DDA/blob/e8166a043b48036fe3fcffc616cae64b2d04a9fd/src/player.cpp#L7954).

Commenting out the [section doing that](https://github.com/CleverRaven/Cataclysm-DDA/blob/e8166a043b48036fe3fcffc616cae64b2d04a9fd/src/player.cpp#L8012-L8014) did solve the crash and NPCs dropping items seemed to work, but I don't know if it causes any other problems.

**Comment by ifreund** [comment] 2019-01-24 12:46
I can't seem reproduce this crash on the latest build.  It's been over half a year, maybe this got fixed somewhere down the line.  Can someone else reproduce? If so I will try to fix it.

**Comment by Night-Pryanik** [comment] 2019-01-25 17:58
Can't confirm either on latest experimental. Closing for now, if the issue still exists, ping me.

**Closed by Night-Pryanik** 2019-01-25 17:58 UTC
Labels: (S2 - Confirmed), <Crash / Freeze>, Inventory / AIM / Zones, NPC

**Comment by kevingranade** [comment] 2019-01-25 18:13
It looks like #23663 fixed this, or at least applied a workaround of having the outer takeoff() exit after calling drop() to avoid dereferencing the invalidated iterator.
