### ISSUE TITLE
Crash when trying to filter by full description.

### ISSUE THREAD

**Issue by 0x9conc1** [CleverRaven/Cataclysm-DDA#62187] opened 2022-11-12 16:46 UTC
### Describe the bug

When in craft menu ("**&**" key) and trying to filter by full description by "_d:hammering qua_" the game freezes and crashes.

### Steps to reproduce

Start the game --> press the "**&**" --> press the "**f**" --> type "_d:hammering qua_" --> press the "**Enter**" (return) key --> get a crash.

### Expected behavior

Do not crash.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

P.S. : linux515: 5.15.76-1
CPU  : i3-4150
RAM  : 16 GB 1333 MT/s
GPU  : Intel® HD Graphics 4400 (iGPU, comsumes about 512 MB from RAM)
MB   : Z97-D3H by Gigabyte Technology Co., Ltd.

### Additional context

Some combinations of 2 words are findable, as a "piece of", but "with soap", "weight is", and many others - cause crash.

[SaveFile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9995429/SaveFile.zip)

**Comment by Inglonias** [comment] 2022-11-12 19:21
I could not reproduce this in the latest experimental. Note that the user who reported this is running 0.F stable. Not sure if that makes this bug less valid, though.

**Comment by Night-Pryanik** [comment] 2022-11-13 13:21
Dupe of #58407.

**Closed by Night-Pryanik** 2022-11-13 13:21 UTC
Labels: (S1 - Need confirmation)
