### ISSUE TITLE
Spider mutants can't make webs to sleep in vehicles

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#34781] opened 2019-10-15 16:17 UTC
# Describe the bug

What it says on the tin, a post-threshold spider mutant cannot sleep inside a vehicle because of the "web field" doesn't get detected from inside the vehicle.

# Steps To Reproduce

1. Become spider-y
2. Attempt to make your bed

# Expected behavior

I can't think of a reason mechanically why a spider wouldn't be able to spin a web inside of a car, seen a few in my own vehicle. May be prudent to make a custom part if a mobile field isn't feasible.

# Versions and configuration

Running 0.D-8469 on Windows 10.

**Comment by Night-Pryanik** [comment] 2019-10-15 16:19
Duplicate of #30916.

**Closed by Night-Pryanik** 2019-10-15 16:19 UTC
