### ISSUE TITLE
Crash in nenu "Select zone type:"

### ISSUE THREAD

**Issue by svakob** [CleverRaven/Cataclysm-DDA#76121] opened 2024-09-01 19:08 UTC
### Describe the bug

The game crashes when scrolling through the menu to add a zone.

### Attach save file

[0-trimmed.tar.gz](https://github.com/user-attachments/files/16830182/0-trimmed.tar.gz)

### Steps to reproduce

Open zones manager -> Add new zone -> scroll down untie "Loot: Perishable Food" OR scroll up.

### Expected behavior

The game should not crash.

### Screenshots

![image](https://github.com/user-attachments/assets/01fae6ce-5309-4f41-b455-012003b4a77d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 746a170 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/16830199/debug.log)
[crash.log](https://github.com/user-attachments/files/16830200/crash.log)

**Comment by harakka** [comment] 2024-09-01 19:42
Duplicate of #76110

**Closed** 2024-09-01 19:43 UTC
Labels: (S1 - Need confirmation)
