### ISSUE TITLE
Dramatic slow down on sleeping, slow framerate/ticks on reading

### ISSUE THREAD

**Issue by derektumolo** [CleverRaven/Cataclysm-DDA#26522] opened 2018-11-04 05:48 UTC
**Describe the bug**  
When I sleep, after "save first", and after alarm setting (doesn't matter what I pick), i see "comfortable place to sleep" and "start trying to fall asleep", as well as the "wait til you wake up" prompt at the top of the screen. At the next 30min interval the screen locks up, and task manager indicates "not responding".

**To Reproduce**  
1. Load attached save game.
2. Sleep.
3. Observe increase resource utilization - up to 30% of cpu on my machine, up from 4%. 
4. Wait several minutes. 
5. If it doesn't crash, screen will go black itself for character vision - no sidebar

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

1. No or minimal slowdown, no crashes

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version :
 - Graphics version - terminal
 - Mods loaded - none

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.
[Gray Mountain - Copy - Copy - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2545600/Gray.Mountain.-.Copy.-.Copy.-.Copy.zip)

**Comment by derektumolo** [comment] 2018-11-04 19:20
I use the launcher, latest. Its cleared up somewhat but there’s def a frame
rate drop during sleep.

**Comment by kevingranade** [comment] 2018-11-04 21:19
I strongly suspect that map memorization is triggering during sleep.

The real answer is to gather performance profiles while sleeping and see what happens.

**Comment by jbytheway** [comment] 2018-11-04 22:04
I feel like there are two issues here: the slowness, and also the fact that the game is triggering the 'not responding' message in task manager, which I believe happens when you spend too much time without allowing the Windows message loop to process messages.  That should probably be fixed independently of the slowness.

**Comment by kevingranade** [comment] 2018-11-05 17:38
You can sprinkle calls to the event loop through the code, but the problem remains that the program is unresponsive because it is spending too long in between calls to retrieve input.

Fixing the cause of the slowdown returns the system to the correct state of responsiveness, and is something we must do anyway.

**Comment by kevingranade** [comment] 2019-01-24 18:20
I can't reproduce this, I very strongly suspect that it was caused by the known issues around map memory, which are resolved by #27457

**Closed by kevingranade** 2019-01-24 18:20 UTC
Labels: Code: Performance
