### ISSUE TITLE
Equipping a weapon: what to do with current weapon bug

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16629] opened 2016-05-11 17:14 UTC
When switching between my pistol and my wooden spear the first option to place the item in my inventory was greyed out. They both have the same volume and put me at 58/58, which should be a safe and viable option. The second option to drop on the ground worked normally.

**Comment by nanovad** [comment] 2016-05-12 21:21
Effectively, you cannot "swap" items, by wielding a new item and placing the previously wielded one in inventory, without having enough inventory space for both items. Perhaps some misplaced volume checks?

**Comment by illi-kun** [comment] 2016-05-14 10:07
A dupe of #16637.

**Closed by illi-kun** 2016-05-14 10:07 UTC
