### ISSUE TITLE
The ranged aim confidence bar is not accurate

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#16980] opened 2016-05-31 23:12 UTC
Windows 10
Tiles
Version 0.#-14379-ga3bc3ca

The aim confidence bar has a linear distribution. Since the actual ranged accuracy does not (unless there is only a single source of dispersion, e.g. 10 gun skill, 10 marksmanship, no eye or arm encumbrance, 12+ dexterity and perception, dispersion only from ammo), the two will not match.

Actually even then they use a different threshold for grazing hits.
In `Creature::deal_projectile_attack` in creature.cpp:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/creature.cpp#L525

```
    } else if( goodhit < 0.8 ) {
        message = _("Grazing hit.");
```

compared to in `print_aim_bars` in ranged.cpp
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L902

```
        std::make_pair( 0.6, '|' ) }};
```

```
    mvwprintw( w, line_number++, 1, _( "Symbols: * = Headshot + = Hit | = Graze" ) );
```

**Comment by kevingranade** [comment] 2016-06-01 00:22
That is by design, as I believe is noted in comments around it. Your
character does not have perfect knowledge of their hit chance. If anything
it's still too accurate.

**Comment by Crispy6** [comment] 2016-06-01 00:26
Vague is different from incorrect.

**Comment by kevingranade** [comment] 2016-06-01 00:28
It should be both inaccurate and imprecise, and it is both, by design.
Arguably it should be inaccurate in a more random way, but having it
dancing around at random seems likely to cause a lot of confusion.

**Comment by Crispy6** [comment] 2016-06-01 00:30
Please mark it as wontfix or invalid or something and close this, then.

**Comment by Coolthulhu** [comment] 2016-06-01 22:35
If inaccuracy of the display is an intended thing, then it should probably scale with something (perception and possibly skills).

**Closed** 2017-03-25 18:15 UTC
Labels: Information / Interface
