### ISSUE TITLE
'Car crash' scenario often places you inside a building

### ISSUE THREAD

**Issue by dkristoffersson** [CleverRaven/Cataclysm-DDA#61617] opened 2022-10-11 18:39 UTC
### Describe the bug

I fired up 6 separate starts in the car crash scenario, and only in 2 of them were my character placed in a car with a few dead bodies strewn around. In the other 4, my character started inside a house, with no cars in sight, inside or outside.

### Steps to reproduce

1. Make a new character in the car crash scenario, and start the game.
2. Repeat 1 until you get a car crash scenario without a car crash.

### Expected behavior

If you start a character in the car crash scenario, you should always start in or near a crashed car.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: f11519b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment] 2022-10-13 01:04
I think this problem isn't unique to this situation. the issue seems to be that the player spawner seems to like to place the player under a roof. sometimes it can fail to put the player in the correct place and instead places the player under some random roofed tile nearby that was in the reality bubble at start. it seems to be much more likely when the number of correct tiles that have a roof is very small like the lmoe start, and there needs to be a house or something nearby for this failure to occur.

**Comment by Night-Pryanik** [comment] 2022-10-26 17:07
Duplicate of #53258.

**Closed by Night-Pryanik** 2022-10-26 17:07 UTC
Labels: (S1 - Need confirmation), Scenarios

**Comment by Night-Pryanik** [comment] 2022-10-26 17:24
Sorry, fixed.

**Comment by dkristoffersson** [comment] 2022-10-26 18:33
> Sorry, fixed.

Ok! It's still closed though.

**Comment by NetSysFire** [comment] 2022-10-26 18:52
Yes, because it is still a duplicate. They accidentally pasted the wrong issue number, now it is correct after they edited their comment.
