### ISSUE TITLE
Labs contain fungal furniture and terrain in worlds with No_Fungi mod active

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#37985] opened 2020-02-13 04:44 UTC
# Describe the bug

The no_fungi mod is not preventing labs from spawning with fungal furniture & terrain, in the attached screenshot you can see fungal floors, walls, flowers, and clumps.

# Steps To Reproduce

1. Generate world with no_fungi mod active (can be the only mod or not, doesn't matter)
2. Select scenario starting in lab or find a lab in game (may take a few tries but after generating about a dozen worlds I only got one lab that didn't have any fungus) 
3. Search lab until fungus is found

# Expected behavior

Obviously for there to be no fungus because it seems to work everywhere else

# Screenshots

![Kenneth Arthur __04-13-10_Mountain Standard Time](https://user-images.githubusercontent.com/22780388/74401546-d7fd4680-4dde-11ea-8ed7-f9d7463cca4d.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-12218-g0ec17df
 - Graphics version: Tiles
 - Mods loaded: dda, No_Fungi

**Comment by Funguss** [comment] 2020-02-13 06:17
Oh yeah, I remember seeing that. Have you tried bashing them to see if they release spores? I believe they shouldn't and so are perfectly safe. It _is_ disconcerting. I feel like I'm doing a disservice to the community by using No Fungi but I find them an absolute pain.

**Comment by randomTechneck** [comment] 2020-02-13 08:52
Bashing them does causes spores to be released giving the spore dusted status.

**Comment by GGgatherer** [comment] 2020-02-13 13:50
Well TBF NoFungi doesn't stop fungal infection from flaming eyes either, so the question is, is this even a bug?

**Comment by shadowsapex** [comment] 2020-02-13 15:13
no_fungi is no fungal monsters. As you can see there are no fungal monsters

**Comment by randomTechneck** [comment] 2020-02-13 15:29
No_fungi is no fungal monsters and regions. Regardless, if you look at the No_Fungi json's you'll see that fungus furniture and terrain are supposed to be removed too. So there's no question about this being a bug; the question is, is it a bug anyone want to do something about. I personally don't mind since it seems unlikely to spread enough to affect performance (which is the only reason I use the mod it in the first place) but the mod isn't working as intended so I figured I'd raise the issue anyways especially since it was thought to be fixed already.

**Comment by I-am-Erk** [comment] 2020-02-13 15:54
The internet: "but blacklist mods are just a single line, they don't require upkeep!"

It's probably reasonable to get this out with the blacklist mod. It's a product of the portal_in map extra, perhaps we can jsonize that and thereby flag the offending subtype for blacklisting.

**Comment by Night-Pryanik** [comment] 2022-08-27 12:06
No_Fungi mod is obsolete, should we close this issue?

**Comment by anothersimulacrum** [comment] 2022-08-27 13:52
I think so.

**Closed by anothersimulacrum** 2022-08-27 13:52 UTC
Labels: <Bug>, Mods, Fields / Furniture / Terrain / Traps
