### ISSUE TITLE
NPC Arsonist burns down refuge center

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20256] opened 2017-02-10 22:10 UTC
If the arsonist sees a zombie they burn the place down trying to attack it.

Any way to maybe get him to spawn outside or to keep him from burning the place down?

**Comment by pisskop** [comment] 2017-02-11 19:40
feature

**Comment by Taberone** [comment] 2017-02-11 21:22
NPCs with flamethrowers or molotovs in general will burn down anything inbetween them and the zombie, not just Makayla Sanchez (The static-spawned NPC mutant arsonist at the refugee center). They're incapable of recognizing what collateral damage is. Could be worse, though. IIRC, Makayla and dynamic spawn NPC arsonists used to spawn with actual flamethrowers, but now they only spawn with molotovs.

**Comment by pisskop** [comment] 2017-02-11 21:38
the problem is. npc not recognising the need to preserve their home.  its okayish for a random npc to burn it all down, but a static one?

other issues with npcs exist.


- npcs have no concept of the level of threat they face
- npcs have no concept of 'home base'
- they dont _need_ to eat or drink, and thus dont need items
- they have no concept of friendly fire other than 'dont hit pc' and 'dont directly kill allies'
- the shelter is poorly defended and zeds spawn literally inside it

**Comment by WizardOfOoo** [comment] 2017-02-12 01:22
What if we gave Makayla Sanchez a nice sub-machine gun instead?  Arsonist /= pyrophiliac.  They are someone who burns down houses and harvests nails to sell.  The would need a gun to defend themselves beyond Molotov's.  Can we make a NPC prefer a weapon type?

**Comment by Leland** [comment] 2017-02-12 15:52
There is a low-level (and oooold, #120) implementation of a "base" through a bulletin board.

It's only used right now to define an area to tell friendly NPC to go back to, but it might be a good launching-off point for the issues described here.

**Comment by pisskop** [comment] 2017-02-12 17:18
ive always felt like the bulletin board also reduces monster spawns in the immediate area

**Comment by WizardOfOoo** [comment] 2017-02-13 01:32
`If (standing on floor tile) do not (throw Molotov)`

**Comment by DangerNoodle** [comment] 2017-02-13 19:09
At least you are well warned with the arsonist being named as such, unlike random companion NPCs or dynamic ones.

**Comment by Leland** [comment] 2017-08-24 04:11
Closing due to lack of recent discussion. Feel free to ping me to reopen if there's interest in discussion/development on this.

**Closed by Leland** 2017-08-24 04:11 UTC
Labels: NPC, Suggestion (Discuss)

**Comment by WizardOfOoo** [comment] 2017-08-25 02:12
I don't think this is the intended behavior.

This is a bug.
