### ISSUE TITLE
bottom of the mine: Could not find a good starting place for character

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#53583] opened 2021-12-19 08:45 UTC
### Describe the bug

When starting a new game as a miner in the "bottom of the mine" scenario the following error is shown:

```
 DEBUG    : Could not find a good starting place for character

 FUNCTION : void start_location::place_player(avatar &, const tripoint_abs_omt &) const
 FILE     : src/start_location.cpp
 LINE     : 358
 VERSION  : 0.F-4465-gef6206f0f7
```

Despite the message the game does start normally

### Steps to reproduce

1. Start a new game as a miner in the "bottom of the mine" scenario

### Expected behavior

No error message

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4465-gef6206f0f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Note I have already opened an issue about the "Failed to play sound effect: Tried to play a chunk with a bad frame" message: https://github.com/Fris0uman/CDDA-Soundpacks/issues/22

```c++
-----------------------------------------
11:31:26.207 : Starting log.
11:31:26.207 INFO : Cataclysm DDA version 0.F-4465-gef6206f0f7
11:31:26.208 INFO : [main] C locale set to C.UTF-8
11:31:26.208 INFO : [main] C++ locale set to C.UTF-8
11:31:26.208 INFO : SDL version used during compile is 2.0.18
11:31:26.209 INFO : SDL version used during linking and in runtime is 2.0.18
11:31:27.224 WARNING : opendir [lang/mo/] failed with "No such file or directory".
11:31:27.233 INFO : Number of render drivers on your system: 4
11:31:27.233 INFO : Render driver: 0/opengl
11:31:27.233 INFO : Render driver: 1/opengles2
11:31:27.233 INFO : Render driver: 2/opengles
11:31:27.233 INFO : Render driver: 3/software
11:31:27.255 INFO : [options] C locale set to en_US.UTF-8
11:31:27.255 INFO : [options] C++ locale set to en_US.UTF-8
11:31:27.255 INFO : Setting language to: 'en'
11:31:27.255 INFO : [i18n] Scanning core translations from lang/mo/
11:31:27.255 INFO : [i18n] Scanning mod translations from ./mods/
11:31:27.257 WARNING : opendir [lang/mo/] failed with "No such file or directory".
11:31:27.257 WARNING : opendir [./mods/] failed with "No such file or directory".
11:31:27.369 INFO : Active renderer: 3/software
11:31:27.411 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
11:31:27.702 INFO : Setting language to: 'en'
11:31:27.702 INFO : [i18n] Scanning core translations from lang/mo/
11:31:27.702 INFO : [i18n] Scanning mod translations from ./mods/
11:31:27.702 WARNING : opendir [lang/mo/] failed with "No such file or directory".
11:31:27.702 WARNING : opendir [./mods/] failed with "No such file or directory".
11:31:27.905 WARNING : opendir [./mods/] failed with "No such file or directory".
11:31:40.982 WARNING : opendir [./save/Flanders/mods] failed with "No such file or directory".
11:32:08.195 INFO : Loaded tileset: UltimateCataclysm
11:32:08.829 INFO : Loaded tileset: UltimateCataclysm
11:32:26.946 ERROR SDL : (error message will follow backtrace)
    ./with-debug-symbols-cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x23) [0x2936973]
    ./with-debug-symbols-cataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x166) [0x2936146]
    ./with-debug-symbols-cataclysm-tiles(sfx::play_variant_sound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x187) [0x36c9177]
    ./with-debug-symbols-cataclysm-tiles(sounds::process_sound_markers(Character*)+0x9df) [0x371877f]
    ./with-debug-symbols-cataclysm-tiles(do_turn()+0x47a) [0x29c994a]
    ./with-debug-symbols-cataclysm-tiles(main+0x515) [0x2f3dc35]
    /lib64/libc.so.6(__libc_start_main+0xd5) [0x75a7f0e3eb75]
    ./with-debug-symbols-cataclysm-tiles(_start+0x2e) [0x247673e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:1104
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1331
    sfx::play_variant_sound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
    …/src/sdlsound.cpp:510
    sounds::process_sound_markers(Character*)
    …/src/sounds.cpp:681
    do_turn()
    …/src/do_turn.cpp:668
    main
    …/src/main.cpp:711
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 16 seconds.
(continued from above) ERROR : src/sdlsound.cpp:510: Failed to play sound effect: Tried to play a chunk with a bad frame
11:32:42.759 ERROR SDL : src/sdlsound.cpp:510: Failed to play sound effect: Tried to play a chunk with a bad frame
11:32:45.942 ERROR SDL : src/sdlsound.cpp:510: Failed to play sound effect: Tried to play a chunk with a bad frame
11:32:47.366 ERROR SDL : src/sdlsound.cpp:510: Failed to play sound effect: Tried to play a chunk with a bad frame
11:32:48.211 ERROR SDL : src/sdlsound.cpp:510: Failed to play sound effect: Tried to play a chunk with a bad frame
11:34:03.534 WARNING : opendir [./save/Flanders/mods] failed with "No such file or directory".
11:34:30.545 INFO : Loaded tileset: UltimateCataclysm
11:34:30.545 INFO : Loaded tileset: UltimateCataclysm
11:35:09.878 ERROR : (error message will follow backtrace)
    ./with-debug-symbols-cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x23) [0x2936973]
    ./with-debug-symbols-cataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x166) [0x2936146]
    ./with-debug-symbols-cataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xa5) [0x2935be5]
    ./with-debug-symbols-cataclysm-tiles(void realDebugmsg<>(char const*, char const*, char const*, char const*)+0x35) [0x247b075]
    ./with-debug-symbols-cataclysm-tiles(start_location::place_player(avatar&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&) const+0x275) [0x3731285]
    ./with-debug-symbols-cataclysm-tiles(game::start_game()+0x2d2) [0x2af8ce2]
    ./with-debug-symbols-cataclysm-tiles(main_menu::new_character_tab()+0x789) [0x2f46f19]
    ./with-debug-symbols-cataclysm-tiles(main_menu::opening_screen()+0xcce) [0x2f4607e]
    ./with-debug-symbols-cataclysm-tiles(main+0x4bc) [0x2f3dbdc]
    /lib64/libc.so.6(__libc_start_main+0xd5) [0x75a7f0e3eb75]
    ./with-debug-symbols-cataclysm-tiles(_start+0x2e) [0x247673e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:1104
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1331
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:443
    addr2line: DWARF error: could not find variable specification at offset 13327c
    addr2line: DWARF error: could not find variable specification at offset 1475c8
    void realDebugmsg<>(char const*, char const*, char const*, char const*)
    …/src/debug.h:?
    start_location::place_player(avatar&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&) const
    …/src/start_location.cpp:360
    game::start_game()
    …/src/game.cpp:795
    main_menu::new_character_tab()
    …/src/main_menu.cpp:808
    main_menu::opening_screen()
    ??:?
    main
    …/src/main.cpp:?
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 44 seconds.
(continued from above) ERROR : src/start_location.cpp:358 [void start_location::place_player(avatar &, const tripoint_abs_omt &) const] Could not find a good starting place for character
```

**Comment by NetSysFire** [comment] 2021-12-19 10:45
Duplicate of #53331

**Closed by NetSysFire** 2021-12-19 10:45 UTC
