### ISSUE TITLE
Untranslated string: Inscribing item

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28417] opened 2019-02-28 02:06 UTC
**Describe the bug**
The message for failing to carve an item is partially untranslatable:

    You can't %1$s %2$s because of the material it is made of.

The `%1$s` is untranslatable. It's something like e.g. “carve”.

**Steps to reproduce**

* Use German (which is at 100% now)
* Try to carve/inscribe something with a knife to a newspaper page
* Check out msg

**Expected behavior**
Whole string is translated.

**Versions and configuration**

    OS: GNU/Linux
    Game Version: 0.C-37544-gc172ff663e
    Graphics version: Terminal
    Mods loaded: DDA, disable NPC needs, filthy clothing, simplified nutrients

**Additional context**
For a proper (!) fix, I recommend to drop the `%1$s` entirely and instead replace it with a hardcoded word and just repeat the string for each possible action. You might say this is slightly more redundant but it will be infinitely more accessible for translators as the verb is now in context, grammar rules can be properly taken into account, etc.

Examples:

* You can't carve %2$s because of the material it is made of.
* You can't cut %2$s because of the material it is made of.
* You can't inscribe %2$s because of the material it is made of.

**Comment by kevingranade** [comment] 2019-02-28 03:47
It seems the only string this is ever populated with is "Write", which should be translated, but is also rather awkward.
It looks like the other cases of inscription may have been moves elsewhere.

**Comment by Wuzzy2** [comment] 2019-03-01 22:58
Doesn't work. The word “carve” is still used untranslated. The word “carve” doesn't appear in the POT file anyway.

Did you actually follow the steps to reproduce to test this?

Looks like this is unfixable without violating string freeze. :(

**Comment by kevingranade** [comment] 2019-03-02 01:37
I lost have latched onto the wrongvstringbinstance somehow.

**Comment by Fris0uman** [comment] 2020-01-14 18:27
Can't reproduce the error
![image](https://user-images.githubusercontent.com/41293484/72371029-c8b5ab00-3703-11ea-86f1-c5172569a8ea.png)
google trad tels me that ` eingravieren` means engrave so it seems to be the right message and it's translated

**Comment by I-am-Erk** [comment] 2020-01-17 19:54
Based on frisoman's results I am closing this, unless there's any additional concerns? Those are both correctly translated, so the concern that the phrase isn't being put to translation seems to be outdated.

**Closed by I-am-Erk** 2020-01-17 19:54 UTC
Labels: Translation
