### ISSUE TITLE
zombie burner bug

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#59130] opened 2022-07-10 10:04 UTC
### Describe the bug

zombie burner explosion has an error, but the fire spawns just fine

### Steps to reproduce

spawn zombie burners
kill them untill one explodes
look at the error, fire will spawn

### Expected behavior

no error when they explode

### Screenshots

![image](https://user-images.githubusercontent.com/42104923/178140181-10858956-581c-43bc-afd8-d1ec81deea02.png)

### Versions and configuration

Win 10
build 2022-07-10-0511
tiles
english
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "speedydex",
  "stats_through_kills",
  "blazeindustries",
  "translate_dialogue",
  "MMA",
  "No_Rail_Stations"

**Comment by Night-Pryanik** [comment] 2022-07-10 10:19
Duplicate of #59054.

**Closed by Night-Pryanik** 2022-07-10 10:19 UTC
Labels: (S1 - Need confirmation)
