### ISSUE TITLE
Heating large amounts of liquids couses the game to freeze

### ISSUE THREAD

**Issue by gustavoghe** [CleverRaven/Cataclysm-DDA#31166] opened 2019-06-05 23:40 UTC
# Describe the bug

When I try to heat up a 60 L metal tank filled with clean water (frozen), using a vehicle kitchen unit hotplate, the game freezes for at least 2 minutes, then comes back on.

# Steps To Reproduce

Follow detailed description above.

# Expected behavior

I would expect the game no to freeze, and have a normal time passing.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-3936-g9f52909
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: "dda",
  "no_npc_food",
  "realguns",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "hydroponics",
  "more_locations",
  "FujiStruct",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Battery_Overhaul_Legacy_Mode",
  "more_classes_scenarios",
  "no_reviving_zombies",
  "novitamins",
  "StatsThroughSkills"

**Comment by anothersimulacrum** [comment] 2019-06-05 23:45
This is happening because in `src/iuse.cpp` (lines 5246 & 5229 ), heating simply subtracts moves based on the weight of the item being heated up in grams. 

So heating up very heavy things causes move starvation, and the game to freeze.

**Comment by kevingranade** [comment] 2019-06-06 02:39
That logic sounds right, but the game shouldn't apparently freeze just because the player has a move deficit.
Is this any different from when you do some other long action like crafting?

**Comment by anothersimulacrum** [comment] 2019-06-06 03:11
This is similar to #23440 - You can't interrupt the task, which I believe causes this problem.

**Comment by ZhilkinSerg** [comment] 2019-08-09 09:29
I cannot reproduce the issue now, so I will close it, but feel free to report here (or open new issue) if you still experience same issue.

**Closed by ZhilkinSerg** 2019-08-09 09:29 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
