### ISSUE TITLE
Can't consume batteries with Battery System CBM

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#19369] opened 2016-11-20 13:41 UTC
The Battery System CBM description states that batteries must be 'E'aten. This doesn't seem to be true in the latest experimental. 

Started with Construction Cyborg profession and activated the CBM. The batteries don't show in the 'E'at menu. Also can't activate them from inventory. "You can't eat your battery".

![capture](https://cloud.githubusercontent.com/assets/7687709/20463214/096773bc-af40-11e6-9348-c59f09f323c7.PNG)

**Comment by flitvious** [comment] 2016-11-20 13:44
Other players on the forum seem to have the same problem:
http://smf.cataclysmdda.com/index.php?topic=13479.0

**Comment by illi-kun** [comment] 2016-11-20 13:50
Duplicate of #19191. Please try to find existing reports before creating new one.

**Closed by illi-kun** 2016-11-20 13:50 UTC

**Comment by ZenZen2** [comment] 2016-11-20 13:58
Duplicate of #19191 and #18908
Its possible this also related to #18907 because it has somthing to do with charges?

Please do not delete this issue, i think this bug got somehow forgotten and in my opinion a priority.

**Comment by illi-kun** [comment] 2016-11-20 14:28
@ZenZen2 thanks for info. Yes, this is pretty important issue, that's why it's 0.D release blocker. BTW, we're not deleting issues in case of duplication, we just closing them so they are still available.
