### ISSUE TITLE
Make diagonal gaps in vehicles impassable/non-see-through

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#47661] opened 2021-02-22 06:24 UTC
# Is your feature request related to a problem? Please describe.
It's always annoying when you make a turn and then a zombie, or worse, a migo somehow squeezes through the gap created by turning diagonally. It's also unrealistic and a quirk of how vehicles are implemented.

# Describe the solution you'd like
As stated in the title, make it so that you can't pass through a diagonal gap between vehicle walls, and also make it impossible to see through those gaps for consistency.

# Describe alternatives you've considered
None.

# Additional context
N/A

**Comment by anothersimulacrum** [comment] 2021-02-22 06:26
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/5684

**Comment by anothersimulacrum** [comment] 2021-02-22 06:27
(Sidenote, check out https://github.com/CleverRaven/Cataclysm-DDA/pull/42462)

**Closed by anothersimulacrum** 2021-02-22 06:26 UTC
Labels: (S3 - Duplicate)
