### ISSUE TITLE
Air around hot springs is well above boiling point of water

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53688] opened 2021-12-22 19:07 UTC
### Describe the bug

The air and terrain in a hot spring exceeds the boiling point of water. I feel that this defies the laws of physics as I understand them, since how can that water be there if the air around it is hot enough to boil it off?

### Steps to reproduce

1. Go to a hot spring
2. Enable debug temperature overlay

### Expected behavior

Hot springs have always been weird to me. I get that they're intended to be too hot to swim in (the terrain description says that much), but I have trouble understanding how they can exist at these temperatures at all. The highest air temps should be below 100C, right?

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/147142680-65517e46-4974-42ef-86b1-6307ddbe1503.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 630da64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Fewer Soldier Extras [Fewer_Soldiers]
]

**Comment by Photoloss** [comment] 2021-12-22 19:55
Potential duplicate of #53276?

**Comment by NetSysFire** [comment] 2021-12-22 21:01
Duplicate of #53276.

**Closed by NetSysFire** 2021-12-22 21:01 UTC
