### ISSUE TITLE
Xedra Evolved Gracken class generates no body heat.

### ISSUE THREAD

**Issue by Cddasurvivor** [CleverRaven/Cataclysm-DDA#76421] opened 2024-09-14 05:19 UTC
### Describe the bug

Gracken class generates no body heat leading to warmth being extremely low.

With no clothing with 46F Weather your body temperature will be -54 ~ -57 where a normal character will have body temperatures of -22 ~ -25.

It doesn't appear to be a feature of the Gracken class and I assume it has to do with the changes to how it processes calories.

### Attach save file

n/a

### Steps to reproduce

1) Make a character and choose the Gracken background.
2)When world generates move a few steps and check temperature and it will be extremely low.
3)Remove all mutations move a few steps and see temperature went up 20-25 points.

### Expected behavior

Normal warmth or addition of description that they prefer much warmer temperatures.

### Screenshots

n/a

### Versions and configuration

Experimental 2024-9-14-0259

**Comment by RenechCDDA** [comment] 2024-09-14 06:16
Duplicate of #73389

**Closed by RenechCDDA** 2024-09-14 06:16 UTC
Labels: (S1 - Need confirmation)
