### ISSUE TITLE
Light level/vision range math oddity

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17968] opened 2016-08-08 22:41 UTC
`Character::get_vision_threshold` sometimes gets `game::light_level` (an `int`) as an argument, but most of the time it gets `map_cache::lm[x][y]` (a `float`).

`light_level` ignores x/y position.

One easily visible result is the discrepancy between overmap vision and regular vision ranges. Could be just that, could be more.

Additionally, the light math is spread all over the place, meaning it is very fragile and can easily get worse. There are no good functions for calculating, for example, light threshold required to see something at given range, at given light level and given transparency.

**Comment by mugling** [comment] 2016-08-08 22:50
By any chance are you working on adding a bonus for `PER` stat?

**Comment by Coolthulhu** [comment] 2016-08-08 22:55
Yeah, but the math discrepancy is making it harder than it needs to be.

**Comment by kevingranade** [comment] 2017-06-11 23:21
Not a bug, this is a tech debit issue. We can't afford to accumulate misc tech debit issues, so closing.  Feel free to take action or reopen with a specific fix.

**Closed by kevingranade** 2017-06-11 23:21 UTC
