### ISSUE TITLE
Vehicles are able to be 'e'xamined while moving in some cases

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11037] opened 2015-01-29 07:37 UTC
http://smf.cataclysmdda.com/index.php?topic=9436.0

Specifically: 'e' on the tile with controls shows "Examine Vehicle" both while controlling and just sitting in a moving vehicle (when controlling, 'e'xamine only shows that menu, no option to select direction), 'e' on any other tile while _not_ controlling displays "You can't do that on a moving vehicle", as it should be.

Choosing "Examine Vehicle" or examining allows to attempt refilling, which fails due to vehicle moving.
##

**Comment by kevingranade** [comment] 2015-01-29 16:40
We should disable parts of the menu when the vehicle is in motion, but
don't disable examining it, there's all kinds of information there you
might want to check while driving.

**Comment by pabrams** [comment] 2017-07-01 14:46
Reading the title and discussion, it's not clear to me what the issue is.  Should we be able to 'e'xamine  a moving vehicle, or not?  I agree with @kevingranade that there is information (such as fuel and battery levels) that should be available to the player while driving, but currently are not (as far as I know).  In that case, shouldn't the issue be "Vehicles **cannot** be 'e'xamined while driving/(moving)"?  Or am I misunderstanding the issue?  If we allow player to 'e'xamine while driving, won't that also allow them to repair/install/remove while driving?  That part should be disabled.

**Comment by I-am-Erk** [comment] 2019-02-19 00:56
Feel free to correct me if I'm wrong, but I believe this is intended behaviour currently? Closing until contradicted.

**Closed by I-am-Erk** 2019-02-19 00:56 UTC
Labels: <Bug>, Info / User Interface, Vehicles
