### ISSUE TITLE
Was able to reinforce a Molotov cocktail with a Tailor's Kit.

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#15262] opened 2016-02-05 22:38 UTC
Version 0.c-10271-g8627981, Build 4337.

I am able to reinforce Molotov Cocktails with a Tailors Kit because of the cotton component of the item.

**Comment by BevapDin** [comment] 2016-02-05 22:46
Duplicate of #7761

**Comment by elricsfate** [comment] 2016-02-06 08:03
If this is a dupe, please close @Nymall

**Closed** 2016-02-08 04:01 UTC
Labels: Duplicate
