### ISSUE TITLE
Cart appearing in memory when player could clearly see cart moved away from tiles

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#38056] opened 2020-02-16 02:18 UTC
# Describe the bug

When a cart is dragged through an area of bright light, and then the player steps such that something obstructs their view of the terrain they just passed through, their map memory shows the cart in every space they dragged it through. 

# Steps To Reproduce

1. Grab cart
2. drag through some tiles
3. move so view of tiles is obstructed
4. see cart in memory in multiple tiles

# Expected behavior

Cart will not appear in memory of tiles that the player could clearly see it was not in.

# Screenshots

![cdda_cart_memory](https://user-images.githubusercontent.com/15205060/74598071-7df7bd80-5038-11ea-80df-ee93273586ec.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-12289-g26b2614 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    SpeedyDex [speedydex]
]

# Additional context

Is appears that the "ghost carts" in map memory are reset when loading a save.

May or may not be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/28512. I am unsure.

**Comment by DavisBroda** [comment] 2020-02-17 20:49
After a bit more fiddling, it looks like this memory issue only appears when the cart is dragged over certain tiles. It appears in memory when dragged over grass tiles, but not pavement tiles.

**Comment by wapcaplet** [comment] 2020-02-24 02:04
Confirmed - map memory remembers a full history of shopping cart position, except on pavement tiles:

![image](https://user-images.githubusercontent.com/238395/75124867-44920400-566f-11ea-9b9c-cda44d4a747f.png)

**Comment by Night-Pryanik** [comment] 2020-02-25 06:01
Duplicate of #28512.

**Closed by Night-Pryanik** 2020-02-25 06:01 UTC
Labels: <Bug>, Info / User Interface, Mechanics: Map Memory

**Comment by DavisBroda** [comment] 2020-02-25 16:01
@Night-Pryanik I don't think this is quite a duplicate, though it may be related. The linked issue seems to be occurring due to the vision radius of the player being 1, so the player moves away and remembers what was last in the now not-visible tile. Whereas this one happens with arbitrarily large vision radius, so it is not just because the last time the player saw the tile it contained a cart. The most recent version of the tile the player sees didn't have the cart, yet this appears anyways. Seems different enough to keep open as a seperate ticket.

**Comment by sharkfinsouperman** [comment] 2020-03-09 01:45
@Night-Pryanik , I agree with DavisBroda. This is not a duplicate issue and should be re-opened.

Issue #28512 can be duplicated with any furniture that blocks sight or by dragging something at night over any surface.  It also corrects itself and permanently disappears when you look at the path in full light.

On the other hand, this issue persists even after looking at the tiles in full light and over long distances (kilometers), and does not happen over paved ground. The only way to remove the afterimage is to save and exit the game.

Here I dragged a frame with handles through my home, out the door to the south and through the yard. Note the time of day. It is light outside. This did not leave a visible trail *until* I shut the curtains and hid in the closet.
![image](https://user-images.githubusercontent.com/61106669/76176115-d9275680-6185-11ea-8478-02ee9261d036.png)
