### ISSUE TITLE
Crash to desktop - Assertion `full' failed. - Reproducible

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#49059] opened 2021-05-28 22:38 UTC
# Describe the bug
Game crashes to desktop when dropping a gun.

# Steps To Reproduce
Load save
drop the HK417
type `<d> <left-arrow> <right-arrow> <enter>`
the game crashes to desktop without the usual crash window

# Expected behavior
no crash

# Additional context
- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch; Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 099e4a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi]
]

[bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6563561/bug.zip)

Cannot post my save file here for some reason :( maybe too big? 26.5 MB
I keep the save file, let me know if I can post it somewhere

**Comment by matt32106** [comment] 2021-05-28 22:51
Could be a dup of  #49050

**Comment by ZhilkinSerg** [comment] 2021-05-28 23:05
Duplicate of #49050

**Closed by ZhilkinSerg** 2021-05-28 23:05 UTC
