### ISSUE TITLE
Cooked Foods Have No Caloric Value

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54469] opened 2022-01-16 03:38 UTC
### Describe the bug

Ran into this once the other day and again tonight cooking two times in succession - sometimes I'll cook something and it has nothing at all in the Calories column. Had this happen with a good-sized pile of jerky the other day, and tonight a starving new character made 40 boiled fiddleheads and can't get sustenance from them. No idea what causes it or why, it's very rare and there doesn't seem to be anything in the log about a cooking failure etc, and the recipe in & menu does show the items as having calories.

With the jerky I made the other day, I left the reality bubble for a while and when I came back it was fine. I drove about 10 squares away from the boiled fiddleheads this time and came back right away and there was no change, so it may take a overnight stay or something, to make it work I'm wondering? Weird bug, hard to reproduce, I've cooked hundreds of items across a few characters and only seen this happen twice.

I was cooking stacks, FWIW.

### Steps to reproduce

1. Cook some food.
2. Hit E to eat.
3. Notice that sometimes the calories column is empty for an item.

### Expected behavior

Expect successfully cooked foods to give calories, or at least show a fail message if not.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149646194-77833096-dc8e-4ca5-a1f4-6aaa849e5d3d.png)
![image](https://user-images.githubusercontent.com/80022377/149646515-9981a40a-33e6-4589-80eb-5a77c9968d31.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment] 2022-01-16 05:23
Possible duplicate of or related to #51361 #52429 #52676 #52628

**Closed** 2022-02-03 23:25 UTC
Labels: <Bug>, (S3 - Duplicate)
