### ISSUE TITLE
Windmill causes game crash

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#44208] opened 2020-09-16 15:37 UTC
# Describe the bug

Windmill when grinding endochitin causes a game crash. 

# Steps To Reproduce

Using provided save game add endochitin to the windmill and it will crash.
(too big for github, external)

http://www.filedropper.com/omfg

# Expected behavior

# Versions and configuration

build 11005  on windows 10

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5233203/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5233206/debug.log)

**Comment by ZhilkinSerg** [comment] 2020-09-16 18:29
Duplicate of #43090

**Closed by ZhilkinSerg** 2020-09-16 18:29 UTC

**Comment by Profit0004** [comment] 2020-09-16 21:37
Ahh I see they used "Wind mill" rather than windmill so it didnt come up in the search.
