### ISSUE TITLE
Unload can accidently stun lock the player when unloading too many rounds.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#26938] opened 2018-12-04 08:48 UTC
**Describe the bug**  
Ammo unload currently is a short activity, which means that it cant get interrupted.

When accidently unloading too many rounds, the player will get stun locked.
**To Reproduce**  
1. Make a player with a machine gun with 500 ammo.
2. Try to unload that 500 rounds.
3. There's no way to interrupt the unload.

**Expected behavior**  

Player can interrupt the unload, seeing hostile monster should notify the player to interrupt the unload.

**Screenshots**  
Video description of the bug: http://youtube.com/watch?v=sg37Kimcsyw

**Versions and configuration(please complete the following information):**
 - OS: Any
 - Game Version: Current master
 - Graphics version: Any
 - Mods loaded: Any

**Additional context**  
game::unload() should get refactored into a long action.

**Comment by AMurkin** [comment] 2018-12-04 09:50
Duplicate of #23440

**Closed** 2018-12-04 18:10 UTC
Labels: (S3 - Duplicate), <Bug>, Magazines
