### ISSUE TITLE
Identical items making different stacks

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7090] opened 2014-04-08 11:54 UTC
There are some items that do not have any reason to be different (they do not spoil, etc), but still they prefer to create their own stacks instead of joining in. You can call this charisma effect or rebel youth, but it is still an unintended behaviour, if I am not mistaken.
Most often this happens with stacks of bones. Towels that have been used and then dried completely also do not restack. There were others, but I can't remember which ones exactly now - if I notice more, I'll add it here if it helps.

**Comment by mugling** [comment] 2016-03-13 10:02
The bug part was fixed in #7632. The other part is presently intended behavior. Whether bones should differ is really a separate issue so if anyone feels strongly about that please re-open and adjust the title or alternatively open a new issue.

**Closed by mugling** 2016-03-13 10:02 UTC
Labels: Enhancement
