### ISSUE TITLE
Minor 5.56x45mm ammo belt [U]nload bug

### ISSUE THREAD

**Issue by thepotate0** [CleverRaven/Cataclysm-DDA#36769] opened 2020-01-07 06:29 UTC
# Describe the bug
When [U]nloading a 5.56x45mm ammo belt, an error relating to removing an item from something that does not have the item is produced.

# Steps To Reproduce

1. Create an ammo belt with ammunition loaded
2. Use [U] to unload things on the ground, and select the belt
3. Error is shown, however you still receive appropriate linkages and rounds

# Expected behavior
The belt should be unloading into linkages and rounds without producing the error.

# Screenshots
![image](https://user-images.githubusercontent.com/59595780/71873111-5d108400-30ec-11ea-9496-e071ad133be5.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10.0 1903
- Game Version: 0.D-11044-g605409a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod]
]
# Additional context
N/A

**Comment by Night-Pryanik** [comment] 2020-01-07 07:27
Duplicate of #35368.

**Closed by Night-Pryanik** 2020-01-07 07:27 UTC
