### ISSUE TITLE
Segfault crash while examining a pine tree

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41228] opened 2020-06-11 10:20 UTC
# Describe the bug

as title says

# Steps To Reproduce

I examined a pine tree in order to get some stuff from it, it could work with other trees too
EDIT: it crashes with every tree that can examined

# Expected behavior

it shouldn't crash!

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3101-g483a50f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

# Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-3101-g483a50f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x659716[cataclysm-tiles.exe+0x259716]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x659716),
    (libbacktrace: 0x659716    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x63ad6f[cataclysm-tiles.exe+0x23ad6f]), 
    (libbacktrace: log_crash+0x4af@0x63ad6f),
    (libbacktrace: 0x63ad6f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x63ba42[cataclysm-tiles.exe+0x23ba42]), 
    (libbacktrace: signal_handler+0x32@0x63ba42),
    (libbacktrace: 0x63ba42    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x10db2a0[cataclysm-tiles.exe+0xcdb2a0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x10db2a0),
    (libbacktrace: 0x10db2a0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffdeaae8048[msvcrt.dll+0x28048]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffdeace11cf[ntdll.dll+0xa11cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x399@0x7ffdeacaa209[ntdll.dll+0x6a209]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffdeacdfe3e[ntdll.dll+0x9fe3e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x8553a9[cataclysm-tiles.exe+0x4553a9]), 
    (libbacktrace: ZNK4item16get_freeze_pointEv+0x99@0x8553a9),
    (libbacktrace: 0x8553a9    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x865c04[cataclysm-tiles.exe+0x465c04]), 
    (libbacktrace: ZN4item20set_item_temperatureEf+0x34@0x865c04),
    (libbacktrace: 0x865c04    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7e4572[cataclysm-tiles.exe+0x3e4572]), 
    (libbacktrace: ZL14handle_harvestR6playerRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb.constprop.2472+0xc2@0x7e4572),
    (libbacktrace: 0x7e4572    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7e54eb[cataclysm-tiles.exe+0x3e54eb]), 
    (libbacktrace: ZL14harvest_commonR6playerRK8tripointbbb.constprop.2471+0x2cb@0x7e54eb),
    (libbacktrace: 0x7e54eb    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7e583a[cataclysm-tiles.exe+0x3e583a]), 
    (libbacktrace: ZN8iexamine11harvest_terER6playerRK8tripoint+0x7a@0x7e583a),
    (libbacktrace: 0x7e583a    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7875e1[cataclysm-tiles.exe+0x3875e1]), 
    (libbacktrace: ZN4game7examineERK8tripoint+0x6c1@0x7875e1),
    (libbacktrace: 0x7875e1    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x787ad7[cataclysm-tiles.exe+0x387ad7]), 
    (libbacktrace: ZN4game7examineEv+0xf7@0x787ad7),
    (libbacktrace: 0x787ad7    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7b9c04[cataclysm-tiles.exe+0x3b9c04]), 
    (libbacktrace: ZN4game13handle_actionEv+0x5cc4@0x7b9c04),
    (libbacktrace: 0x7b9c04    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x77e71f[cataclysm-tiles.exe+0x37e71f]), 
    (libbacktrace: ZN4game7do_turnEv+0xccf@0x77e71f),
    (libbacktrace: 0x77e71f    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: IMG_LoadWEBP_RW+0x6e40a8@0x18b11b8[cataclysm-tiles.exe+0x14b11b8]), 
    (libbacktrace: main+0x11a8@0x18b11b8),
    (libbacktrace: 0x18b11b8    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #19
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #20
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffde9d07bd4[KERNEL32.DLL+0x17bd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #21
    (dbghelp: RtlUserThreadStart+0x21@0x7ffdeacace51[ntdll.dll+0x6ce51]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by anothersimulacrum** [comment] 2020-06-11 13:30
Duplicate of #41227
Thanks for the report!

**Closed by anothersimulacrum** 2020-06-11 13:30 UTC
