### ISSUE TITLE
Glitched worldgen

### ISSUE THREAD

**Issue by fiel0003** [CleverRaven/Cataclysm-DDA#38691] opened 2020-03-10 19:59 UTC
# Describe the bug
Dirtroad to rural property is bugged, playing rural mod.
# Steps To Reproduce
Go to rural property demonstrated below.
# Expected behavior
Dirt roads are not detected or present.

# Screenshots
![Ben Jones __19-46-17_Central Standard Time](https://user-images.githubusercontent.com/49604264/76353477-cc6a4600-62de-11ea-831c-359eb27eac18.png)

# Versions and configuration
[#QmVuIEpvbmVz.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4314487/QmVuIEpvbmVz.log)
 - OS: Windows 10
 - Game Version: 0.D-13003-gd59d380 (tiles)
 - Graphics version: UndeadPeople Tileset
 - Ingame language: English
 - Mods loaded: Rural Mod, Classic Undead

**Comment by ZhilkinSerg** [comment] 2020-03-10 20:23
What exactly is wrong?

**Comment by Dacendeth** [comment] 2020-03-10 21:00
there's a black void where dirt should be

**Comment by ZhilkinSerg** [comment] 2020-03-10 21:02
That black void could be anything. For all we know from a screenshot it could be a tileset glitch.

**Comment by wapcaplet** [comment] 2020-03-12 00:57
This looks very much like #38709 - also with the Rural-Only Mapgen mod.

@fiel0003 If you use the `x` (lowercase) to examine the black square terrain, do you see a message like this? 

![image](https://user-images.githubusercontent.com/238395/76477180-2136bb00-63ca-11ea-9901-f5ff154d5056.png)

If so, I think this is a duplicate of #38709 .

**Comment by Night-Pryanik** [comment] 2020-03-13 04:58
Closing as duplicate.

**Closed by Night-Pryanik** 2020-03-13 04:58 UTC
