### ISSUE TITLE
Cruise control is on  without any incar electronics.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#24609] opened 2018-08-03 13:52 UTC
Game version: 7643

Operating system: Win 10 x64

Tiles or curses: tiles

Mods active: none

### Expected behavior
Cruise control on vehicles can be active only if the vehicle has working dashboard or other drive-assistant electronics. 

### Actual behavior
Cruise control is active by default on new vehicles and can not be switched off without control board.

### Steps to reproduce the behavior
Drive quad bike or hippie van.

It was introdused by #24594

**Comment by MT-Arnoldussen** [comment] 2018-08-03 13:56
I disagree with the "expected behavior". Cruise control is a great QoL feature, and you can argue that it's your character trying to match the speed, and not the vehicle.

Of course, at the moment the game heavily implies it's the vehicle due to the name and it being tied to a particular vehicle.

A possible solution would be to make cruise control in vehicles with no in-car electronics to be dependent on your Driving skill.

**Comment by Vasyan2006** [comment] 2018-08-03 14:06
> dependent on your Driving skill.

This. Character with 0 driving skill will mischange throttle/brake or left/right.

But if you cannot disable a feature - it is not a feature but a bug.

**Comment by mlangsdorf** [comment] 2018-08-04 23:28
I would be happy to move cruise control out of the electronics control menu and back into the general vehicle control menu.

**Comment by kevingranade** [comment] 2018-08-05 02:40
It's not intended to be a feature of the car, just an option for the ui, so moving it back to the general car control menu works.

**Comment by mlangsdorf** [comment] 2018-08-06 00:03
I'm going to move reactors into the electronics control menu at the same time.

**Closed** 2018-08-06 23:48 UTC
Labels: <Bug>, Vehicles
