### ISSUE TITLE
Seg Fault on picking up more than one unit of Brazing Rod at a time

### ISSUE THREAD

**Issue by cerix2077** [CleverRaven/Cataclysm-DDA#65453] opened 2023-05-03 14:40 UTC
### Describe the bug

Seg Fault occurs when you pick up more than one unit of the brazing rods on the shelves directly west and southwest of the Player Character
 
- Picking up one unit at a time returns the expected result but picking up two or more will cause the seg fault to occur
- there was one occurrence early on in testing this bug where after grabbing a few other unit based items in the building (to see if other items could cause a seg fault) I came back to the brazing rod and picked up the full stack without crashing. however I could not reproduce it

### Attach save file

[New Eden-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11383590/New.Eden-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached save file
2. pick up (g) from the left or bottom left utility shelves directly beside player
3. select the full stack of brazing rod or any amount over 1
4. hit enter to pick them up then crash to desktop 

### Expected behavior

Upon picking up more then one unit of brazing rod it will not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: d71b577 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Bionic Professions [package_bionic_professions],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11383571/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11383602/debug.log)

**Comment by Brambor** [comment] 2023-05-04 14:11
I am on Windows 10, extracting save file with WinRar, it says "the archive is damaged"
Not sure why, It seems to extract the file alright.

I will try to reproduce your bug once my game compiles...

**Comment by Brambor** [comment] 2023-05-04 17:55
I couldn't reproduce it on 7c613dd5ea (master),
So I rebased on d71b577, compiled and couldn't reproduce it either

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 0.G-1691-gd71b577f6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Bionic Professions [package_bionic_professions],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex]
]

**Comment by Brambor** [comment] 2023-05-06 00:30
I did compile from source, maybe it will be different with downloaded version...

**Comment by RenechCDDA** [comment] 2023-05-06 07:11
Duplicate of #65166

**Closed by RenechCDDA** 2023-05-06 07:11 UTC
Labels: (S1 - Need confirmation)
