### ISSUE TITLE
Map memory - homemade cart staying when I've moved it away

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#37882] opened 2020-02-10 08:03 UTC
Game version: 0.D-12155-gb7876ca

Operating system: Ubuntu 19.10

Tiles or curses: Tiles

Mods active: Disable NPC Needs

### Expected behavior

When I drag my wooden box around I expect my character to know it isn't where it used to be anymore.

### Actual behavior

![2020-02-10_18:49:48_+1100_screencut](https://user-images.githubusercontent.com/26471575/74130798-0b04d600-4c37-11ea-8e13-3cc18e8561a6.png)

You can see in the screenshot I've dragged my cart from the kitchen of this house to the garage, leaving a line of ghost carts in my map memory. Exploring the map and seeing that the cart isn't there anymore doesn't fix it. Closing and reopening the game, then exploring the map, does fix it.

### Steps to reproduce the behavior

I guess try spawning in a wooden frame and making it into a vehicle, then drag it around a bit at night

**Comment by ZhilkinSerg** [comment] 2020-02-10 11:11
Duplicate of #28512

**Closed by ZhilkinSerg** 2020-02-10 11:11 UTC
