### ISSUE TITLE
Solar Panels Not Working On Building Roofs

### ISSUE THREAD

**Issue by Koningkrush** [CleverRaven/Cataclysm-DDA#49013] opened 2021-05-24 11:38 UTC
# Describe the bug

Solar panels do not charge batteries on Z Level 1 on a house.

# Steps To Reproduce

1. Construct a vehicle on Z level 1 of a house (the terrain is: floor (t_floor) wooden roof tiles).
2. Attach a storage battery, solar panel, vehicle controls, an engine, seat.
3. The solar panels will not charge the batteries as if they have no access to sunlight.

# Expected behavior

Solar panels should charge batteries if they have access to direct sunlight, regardless of elevation.

# Screenshots

![SolarBug1](https://user-images.githubusercontent.com/84711715/119335196-0b718680-bc5a-11eb-9c11-a65c2b43ba6b.PNG)
![SolarBug2](https://user-images.githubusercontent.com/84711715/119335209-11676780-bc5a-11eb-8f52-52571b4e4ecd.PNG)

# Versions and configuration

    - OS: Windows
    - OS Version: 10.0 2009
    - Game Version: b6c4ce5 [64-bit]
    - Graphics Version: Tiles
    - Game Language: System language [English]
    - Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mining Mod [Mining_Mod],
    Cataclysm++ [Cata++],
    DinoMod [DinoMod],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    SpeedyDex [speedydex],
    Useful Helicopters [useful_helicopters],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Cataclysm++ [Graphical_Overmap_SDG_Cata++],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG]

# Additional context

I placed a Solar Panel on a motorcyle and drove it up a ramp to an bridge overpass on Z level 1. In this case, the solar panel continued to work on Z level 1 unlike the solar grid I have built on the roof of my house.
**Save File Added**
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6533977/save.zip)

**Comment by Inglonias** [comment] 2021-05-24 14:16
A save file would be hugely useful in reproducing this issue, since you mentioned that in some cases, things work as expected, but not in other cases.

**Comment by Koningkrush** [comment] 2021-05-24 17:27
> A save file would be hugely useful in reproducing this issue, since you mentioned that in some cases, things work as expected, but not in other cases.

I have added the save. I also tried disabling all mods except base game as a test and the issue persisted for the vehicle.

**Comment by Zireael07** [comment] 2021-05-24 17:31
I wonder - has the vehicle been built on Z level 1 and never "visited" Z 0? This might play a role... just wondering...

**Comment by Koningkrush** [comment] 2021-05-24 17:50
So I figured out what the problem was. For every roof tile I built, the game automatically built a "flat roof (t_flat_roof) 499" floor directly above it. I tried removing these floating roofs by turning them into open air with map editor, but reloading the game causes them to come back automatically.
![roofbug1](https://user-images.githubusercontent.com/84711715/119387507-0a127f00-bc97-11eb-8eb3-50a5ab815205.PNG)
![roofbug2](https://user-images.githubusercontent.com/84711715/119387517-0ed73300-bc97-11eb-98bd-67a0ad4dae7f.PNG)

**Comment by Koningkrush** [comment] 2021-05-24 18:07
I changed all the "floor (t_floor)" into "wooden floor (t_floor_noroof)" and turned the above "flat roof (t_flat_roof)" into open air. The solar panels now work.
The issue was that I didn't know "floor (t_floor)" always creates "flat roof (t_flat_roof)" above it.

**Comment by actual-nh** [comment] 2021-05-24 18:28
I'm closing this issue; feel free to add one regarding the difficulty of knowing whether a roof is present over your position! (The still-experimental 3d vision option may help.)

**Closed by actual-nh** 2021-05-24 18:28 UTC
Labels: (S4 - Invalid), Vehicles, Z-levels
