### ISSUE TITLE
Eating corn cobs has unexpected behaviour(s)

### ISSUE THREAD

**Issue by Antrollian** [CleverRaven/Cataclysm-DDA#55431] opened 2022-02-16 05:58 UTC
### Describe the bug

When eating a corn cob from a stack, all the corn cobs are deleted and converted to empty corn cobs. In addition, no message appeared saying you ate something. No calories seem to be consumed either. 

### Steps to reproduce

1. Spawn a stack of multiple corns
2. Eat a single one

### Expected behavior

Expectation is that one corn cob is consumed and an empty corn cob spawns, leaving all other corn cobs untouched. Calories should be consumed, and there should be a chat message stating "you eat x".

### Screenshots

<img width="763" alt="Cron" src="https://user-images.githubusercontent.com/99733182/154205112-f2ebbe21-deb4-4e81-a40f-4c0631281ab6.PNG">

<img width="608" alt="cron2" src="https://user-images.githubusercontent.com/99733182/154205108-e750601e-9b5f-4edb-9cb8-af106b5c58d6.PNG">

<img width="695" alt="cron3" src="https://user-images.githubusercontent.com/99733182/154205114-e4935c85-5241-461b-a9a8-c9a686599fa8.PNG">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 55900e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Tested this in a blank world with no mods, and in a heavily modded world with same behaviours. Cooking with said corn and empty corn cobs also seems bugged (not shown).

**Comment by dseguin** [comment] 2022-02-16 06:00
Looks like a duplicate of #50002

**Closed** 2022-02-16 06:41 UTC
