### ISSUE TITLE
Bug: examine of tree_maple not show expected messages

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20475] opened 2017-03-07 09:34 UTC
These:
You need a tool to drill the crust to tap this maple tree.
You need a tool to hammer the spile into the crust to tap this maple tree.
And not showing them as long as i play 0.C.
win x64 tiles

**Comment by remyroy** [comment] 2017-03-14 21:13
You cannot tap a maple tree in 0.C. This is not a bug.

**Comment by AMurkin** [comment] 2017-03-15 12:33
Fine (actually sad), but message displayed on examine does not helps to figure that out.
Maybe that is a bug?

**Comment by remyroy** [comment] 2017-03-15 15:56
No, it's not a bug. Please close this issue.

**Comment by kevingranade** [comment] 2017-03-15 16:24
This feature was not written yet when 0.C was released.

**Closed by kevingranade** 2017-03-15 16:24 UTC
