### ISSUE TITLE
Computer skill training should work in the dark

### ISSUE THREAD

**Issue by Igryn** [CleverRaven/Cataclysm-DDA#56185] opened 2022-03-18 13:57 UTC
### Is your feature request related to a problem? Please describe.

You cant train computer skill using a training recipe 

### Solution you would like.

Computer or smartphone is used to practice so the screen should provide some of the needed light. It could be less effective but should still work

### Describe alternatives you have considered.

Leave it as is

### Additional context

Also could be nice if it provided some amount of actual light while in process

**Comment by TheShadowFerret** [comment] 2022-03-18 22:56
Duplicate of #51412

**Closed** 2022-03-19 11:20 UTC
