### ISSUE TITLE
u_val("vitamin") fails to return vitamin value

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#67104] opened 2023-07-22 20:15 UTC
### Describe the bug

u_val("vitamin") fails to return the vitamin value

It means that enchantments cannot be influenced by vitamins as they currently don't work as a variable despite being a variable that can be called and that exists in the documentation

### Attach save file

N/A

### Steps to reproduce

1. Add the code below in your effect file or create an effect trying to use the character's vitamin values
 
[ { "type": "effect_type",
    "id": "iron_accumulation",
    "name": [ "Iron accumulation" ],
    "desc": [ "You grow in power the more iron you consume" ],
    "apply_message": "You feel a deep energy in your body, exuberant and coiled.",
    "remove_message": "The energy in your body fades away.",
    "rating": "good",
    "show_intensity": true,
    "//": "boosts many stats based on the player's iron level",
    "enchantments": [ { "values": [
          { "value": "BONUS_BLOCK", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "BONUS_DODGE", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "CLIMATE_CONTROL_HEAT", "add": { "math": [ "u_val('vitamin', 'name: iron') / 10" ] } },
          { "value": "CLIMATE_CONTROL_CHILL", "add": { "math": [ "u_val('vitamin', 'name: iron') / 10" ] } },
          { "value": "DEXTERITY", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "INTELLIGENCE", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "PERCEPTION", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "STRENGTH", "add": { "math": [ "u_val('vitamin', 'name: iron') / 100" ] } },
          { "value": "SPEED", "add": { "math": [ "u_val('vitamin', 'name: iron') / 5" ] } },
          { "value": "FALL_DAMAGE", "add": { "math": [ "u_val('vitamin', 'name: iron') / -10" ] } },
          { "value": "FATIGUE", "add": { "math": [ "u_val('vitamin', 'name: iron') / -10" ] } },
          { "value": "MAX_STAMINA", "add": { "math": [ "u_val('vitamin', 'name: iron') / 1" ] } },
          { "value": "MOD_HEALTH", "add": { "math": [ "u_val('vitamin', 'name: iron') / 5" ] } },
          { "value": "REGEN_HP", "add": { "math": [ "u_val('vitamin', 'name: iron') / 10" ] } },
          { "value": "REGEN_MANA", "add": { "math": [ "u_val('vitamin', 'name: iron') / 10" ] } },
          { "value": "REGEN_STAMINA", "add": { "math": [ "u_val('vitamin', 'name: iron') / 1" ] } } ] } ] } ]

2. Give yourself said effect and increase your iron levels
3. Notice how you do not get any boosts nor errors from it

### Expected behavior

Vitamin levels being able to be used in a math function

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 375f7b6 [64-bit]
- Graphics Version: Tiles
- Game Language: Langue du système []
- Mods loaded: 
    Dark Days Ahead [dda],
    Désactiver les besoins des PNJ [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Pas de Gares [No_Rail_Stations]

### Additional context

Pinging @andrei8l since they requested me to open this issue

**Comment by andrei8l** [comment] 2023-07-22 20:18
/confirmed This is an issue with talkers constructed from const Creature

I posted this quick fix on discord, but I hate it and I'll try to figure out something better

```diff
diff --git a/src/condition.cpp b/src/condition.cpp
index 0eb202c529..ff816f0ffd 100644
--- a/src/condition.cpp
+++ b/src/condition.cpp
@@ -1963,7 +1963,7 @@ std::function<double( dialogue & )> conditional_t::get_get_dbl( J const &jo )
         } else if( checked_value == "vitamin" ) {
             std::string vitamin_name = jo.get_string( "name" );
             return [is_npc, vitamin_name]( dialogue const & d ) {
-                Character *you = d.actor( is_npc )->get_character();
+                Character const *you = static_cast<talker const *>( d.actor( is_npc ) )->get_character();
                 if( you ) {
                     return you->vitamin_get( vitamin_id( vitamin_name ) );
                 } else {
diff --git a/src/talker_character.h b/src/talker_character.h
index 284a523530..68c602f5c1 100644
--- a/src/talker_character.h
+++ b/src/talker_character.h
@@ -32,6 +32,14 @@ class talker_character_const: public talker_cloner<talker_character_const>
         }
         ~talker_character_const() override = default;
 
+        const Character *get_character() const override {
+            return me_chr_const;
+        }
+
+        Character *get_character() override {
+            return nullptr;
+        }
+
         // identity and location
         std::string disp_name() const override;
         character_id getID() const override;
```

Also pinging @Ramza13 in case they have a better idea.

**Comment by GuardianDll** [comment] 2023-12-23 21:10
Tested in recent exp, now everything works (also iron is a bad vitamin to test since it's default state is 0, and it only decreases afterwards)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/156bcb44-8e91-4dfc-8c10-fced4300f981)

**Comment by NetSysFire** [comment] 2023-12-23 21:14
Closing as fixed.

**Closed by NetSysFire** 2023-12-23 21:14 UTC
Labels: (S2 - Confirmed), EOC: Effects On Condition
