### ISSUE TITLE
Can't use nearby water for crafting, unless there is water in inventory.

### ISSUE THREAD

**Issue by Cat09** [CleverRaven/Cataclysm-DDA#18241] opened 2016-09-09 17:20 UTC
To reproduce, get:
1 bottle of water
1 pot or other 
inside an LMOE, next to the water pools.
drop the water bottle in range.
light up the stove, and try to craft clean water.
pick up the bottle, and try again, should be able to not only craft, but use the nearby water now.
you can see the result at least for making oatmeal as well.

**Comment by Xpyder** [comment] 2016-09-29 20:33
I'm having a similar issue.  Using build 5581
previously i was able to craft clean water just fine, but now it says water isn't available, even though I'm holding a full small waterskin in my hand, wearing one, and have a jug of water next to me.

I do have a follower who has broken arms and is low on food, water, and sleep.


![image](https://cloud.githubusercontent.com/assets/12039454/18971184/f5978d74-8648-11e6-92da-03c163cba9fe.png)

![image](https://cloud.githubusercontent.com/assets/12039454/18971193/fd6725d2-8648-11e6-8945-521cc30a44e2.png)

**Comment by Coolthulhu** [comment] 2016-10-25 09:03
I think I have an explanation:
The counting function does `min` at the end, after adding counts. The problem is, individual counts can be huge enough that their sum goes over maximum value of `long`, causing an overflow.

**Comment by mugling** [comment] 2016-11-27 16:25
Duplicate of #18709

**Closed by mugling** 2016-11-27 16:25 UTC
Labels: Bug
