### ISSUE TITLE
Cant cancel Auto mining

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#44878] opened 2020-10-15 17:06 UTC
# Describe the bug

Wielding a pickaxe and going on a road tile starts auto mining that cant be canceled.

# Steps To Reproduce

1. Wield a pickaxe
2.Turn on autominer
3. Try to go on a road tile
4. Press num5/"." to stop

# Expected behavior

After pressing num5/"." mining action should stop.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6888-gd880db2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots]
]

**Comment by ZhilkinSerg** [comment] 2020-10-15 18:47
Duplicate of #40289

**Closed** 2020-11-24 20:35 UTC
Labels: (S3 - Duplicate)
