### ISSUE TITLE
Acetylene torch not recognized when removing vehicle parts

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#16352] opened 2016-04-23 16:35 UTC
As of experimental 4742, the vehicle 'e' menu does not recognize the presence of acetylene torches for the purpose of removing parts. Repair and installation works as normal.

**Comment by mugling** [comment] 2016-04-23 16:39
Regression from #16061

**Comment by mugling** [comment] 2016-07-16 17:38
Supporting `hacksaw` OR `welder + goggles` requires non-trivial changes to the `requirement` data. Specifically we have to extend support to include both tools and qualities within the same set of alternatives.

Does anyone have an alternative suggestion or can this become long term issue?

**Comment by Coolthulhu** [comment] 2016-09-29 14:53
Having AND/ORs in requirements would be really useful - much more than just for a minor detail like making acetylene torch work as an overly expensive hacksaw.

**Comment by mugling** [comment] 2016-09-29 15:06
Yes, it's on my list for further refactoring of crafting

**Comment by mugling** [comment] 2016-10-07 19:38
This cannot be resolved without reworking of the crafting system as above. I'm not sure if this issue is sufficiently serious to warrant delaying `0.D` whilst that occurs. Does anyone disagree with re-tagging as long-term?

**Comment by Autastic** [comment] 2016-10-07 23:14
not that it matters much, as i'm just a user rather than a developer, but i think that i, along with other users, have been waiting for this to be fixed for quite some time. I for instance have been unable to play the game because of this for almost half a year now. not trying to pressure anyone, but i do think its a pretty important issue that should be solved.

**Comment by mugling** [comment] 2016-10-08 08:45
> for instance have been unable to play the game because of this for almost half a year now

Erm hacksaw?

**Comment by Autastic** [comment] 2016-10-08 18:01
for building new vehicles and repairing parts.

**Comment by mugling** [comment] 2016-10-08 19:16
This is issue is about **removing** parts

**Comment by Autastic** [comment] 2016-10-08 19:31
it doesnt seem to work when doing either of those things. i've tried periodically for the past few months to spawn one and a vehicle and test it out, but i haven't been successful.

**Comment by mugling** [comment] 2016-10-08 19:38
Install/repair with acetylene torch definitely works

**Closed** 2016-10-31 12:37 UTC
Labels: Bug
