### ISSUE TITLE
Zui Quan reports unusable with unarmed weapons (text only bug)

### ISSUE THREAD

**Issue by araneyl** [CleverRaven/Cataclysm-DDA#35249] opened 2019-11-02 04:04 UTC
# Describe the bug

When wielding an unarmed weapon Zui Quan reports that it does not work with the weapon despite actually working correctly.

# Steps To Reproduce

1. Activate Zui Quan
2. Equip any unarmed weapon (nail fists/cetus/etc)
3. Message will appear that Zui Quan can not be used with weapons.

# Expected behavior

Zui Quan lists all its skills as working with unarmed weapons, despite the warning when equipping one.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9040-g859e7e9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]

# Additional context

Adding the following text to martialarts.json at line 1502 will fix the issue, though there may be a better fix I am unaware of.

"weapons": [ "bagh_nakha", "bio_claws_weapon", "cestus", "knuckle_brass", "knuckle_nail", "knuckle_steel" ]

**Comment by Lamandus** [comment] 2019-11-03 09:27
Related #35111

**Comment by Lamandus** [comment] 2019-11-03 09:28
@araneyl what is the system language of your pc?

**Comment by araneyl** [comment] 2019-11-03 14:43
@Lamandus english

**Comment by Lamandus** [comment] 2019-11-03 14:52
> 
> 
> @Lamandus english

ok, because I have German, and I thought some weird error of an translation string may cause the issue... But that is not the case then. @Hymore246 to the rescue!

**Comment by Hymore246** [comment] 2019-11-03 22:11
I can confirm that this PR and #35111 occur in the game when you download it using the launcher. However, I cannot get either bug to appear when I compile the code on my own. According to the devs I talked to on Discord, this is probably because I am building the code on Windows using Visual Studio while almost everyone else is using Linux and gcc. Switching to Linux isn't an easy task for me, so I might not be able to help.

That said, I DO need to rewrite the method that produces these messages for a few other reasons. So I'm going to make a PR to do that and it MIGHT fix this. If it doesn't, someone else will have to field the bug because I wouldn't be able to troubleshoot it correctly.

**Comment by araneyl** [comment] 2019-11-06 01:12
As of #9868 (when @Hymore246 's #35299 fix went in) I can confirm the issue here is now fixed, at least for me. I'm prepared to close this issue but its my first on github and I don't know the etiquette. 
If someone with the authority wants to close this or let me know its ok to do it myself I will be happy to.

**Comment by anothersimulacrum** [comment] 2019-11-06 01:14
If you can't reproduce it anymore, close it.

**Closed** 2019-11-06 01:31 UTC
