### ISSUE TITLE
Hostile NPCs have free access to your vehicles

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19439] opened 2016-11-24 12:42 UTC
Recently did one of the storyline missions involving hunting down bandits, and found to my surprise they could just walk up, open the door to my APC, and go inside. Unlike zombie mobs they don't have to bash their way in.

Seems like a bug if all the armor in the world can be thwarted by doorhandle technology.

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-26 15:52
Player-locked safes and doors would be useful as well.

**Comment by saneman226** [comment] 2016-11-26 16:00
Just use a security system. I have no idea if they are implemented to stop other npcs when the player installs them rather than mapgen.

**Comment by Regularitee** [comment] 2016-11-27 00:07
I had a security system at the time. They don't lock doors on vehicles (which is why you never need to lockpick open cars doors).

**Comment by saneman226** [comment] 2016-11-27 04:02
I am surprised that the security does functionally nothing when installed by the player. Perhaps this could be an easy-pass to get this issue fixed? As for the locking doors, we could have a craftable key and lock that is able to be attached to any door.

**Comment by l29ah** [comment] 2017-05-16 21:14
YES THIS SUCKS
I HAVE TO KILL EVERY NPC BECAUSE THEY'RE ALWAYS STEALING MY STUFF

**Comment by angoddu** [comment] 2017-08-10 18:10
Player-locked doors would be amazing it would solve so many problems I have been having with NPCs. Is anyone currently working on this? I have some C++ experience so if I can figure out how to follow this code I would be more than happy to give it a shot

**Comment by angoddu** [comment] 2017-08-10 19:05
I'll give it a shot. haven't used C++ in a year or two. I usually have to code in java for work

**Comment by Night-Pryanik** [comment] 2018-02-24 15:38
Closed by #22144.

**Comment by l29ah** [comment] 2018-02-24 16:16
I cannot avoid NPCs stealing stuff from my doors and seats this way, even if they are outside, can i?

**Comment by Night-Pryanik** [comment] 2018-02-24 16:17
No, you can't. You have to put your stuff in a lockable and locked container to prevent stealing it.

**Comment by l29ah** [comment] 2018-02-24 16:23
Then the issue is still there, as it talks about the vehicle access being unhindered by doors.

**Comment by kevingranade** [comment] 2018-02-24 19:10
Lockable doors should be very similar to lockable containers.

**Comment by mlangsdorf** [comment] 2018-07-11 16:49
So it looks to me like there's two separate but related issues:
in src/npcmove.cpp lines 1925:1942 in npc::find_items, NPCs can't pick up items from LOCKED locations, but no vehicle part has the LOCKED flag. The CARGO_LOCKING flag protects some cargo locations, but again can't be applied to (most) doors or seats.
Proposed solution: give all vehicle doors and hatches the LOCKED flag. Survivors have to pick the locks of vehicles (or break into them).
Also add a PLAYER_LOCKED flag, which replaces LOCKED on the doors and hatches of a vehicle when the PC takes a to be determined vehicle repair/installation action.
PLAYER_LOCKED could also be an option to add to constructed doors and windows.

in src/pathfinding.cpp:327-358 in map::route, non-friendly NPCs can open car doors and then move to seats to pick up stuff. Since seats can't be locked, you can't stop that from happening. 
Suggested solution: add a check to the OPENCLOSE_INSIDE || statement, that if the door is PLAYER_LOCKED, they can't open it (but might still bash it or find another way into the vehicle).

Fundamentally, I don't think either of those are really hard changes. But they're tricky enough that I don't want to try implementing them unless the mods think that is a good approach to take.

**Comment by Night-Pryanik** [comment] 2018-07-11 17:48
> PLAYER_LOCKED could also be an option to add to constructed doors and windows.

That would great and solve a lot of issues. Too bad there is no way for now to add flags to furniture or terrain during runtime.

**Comment by kevingranade** [comment] 2018-07-11 18:23
Please consider if this is worth the effort considering the npc will just bash a window instead.
There are also a number of weird corner cases around this, like the fact that the player would either need to break or repeatedly pick the locks on the car, since they don't have a key

**Comment by mlangsdorf** [comment] 2018-07-11 18:32
At a minimum, having an NPC start bashing on my (hopefully reinforced) windows takes some time and makes noise, which means I have more time to get close to the NPC and engage them in conversation.

Alternately, if the NPC encounters PLAYER_LOCKED on a vehicle, he might decide not to get stuff from inside it at all.

My initial idea for setting PLAYER_LOCKED was PC remembers the vehicle location and has turned on or off the engine. I didn't initially propose it because I figured you thought it would be too easy, but honestly, PLAYER_LOCKED should be something easy to set. And once PLAYER_LOCKED is set, the PC doesn't have to break in anymore because PLAYER_LOCKED has no effect on the PC and their allies.

**Comment by kevingranade** [comment] 2018-07-11 18:54
> At a minimum, having an NPC start bashing on my (hopefully reinforced) windows takes some time

If you think it's worth the effort, feel free to implement locking and bashing.

> Alternately, if the NPC encounters PLAYER_LOCKED on a vehicle, he might decide not to get stuff from inside it at all.

How does a NPC tell a player locked vehicle from a vehicle locked by the original (presumably dead) owner? Also, why would they care?

> a to be determined vehicle repair/installation action.

You need to be more specific about this, the original door lock is inoperable (no key), so what is the player replacing it with?

**Comment by Epictyphlosion** [comment] 2019-01-10 17:03
Has adding the ability to lock car doors been suggested already?

**Comment by mlangsdorf** [comment] 2019-01-10 20:05
Yes.

**Comment by GearheadLydia** [comment] 2019-01-14 12:38
I have an idea that might be useful: add a property of some sort to the security system item, like an "owner tag", that is set to some random value that is NOT the player's name when the vehicle is initialized. When the player installs a security system into a vehicle, or hacks an existing security system, the new security system's "owner tag" is the name or ID of the player, which means that the player has access.

Granting access to friendly NPCs is a more difficult question, but I'm wondering if that could be integrated into another idea I had: creating wearable IFF transmitters for each of the NPCs, so that player-owned turrets wouldn't shoot them (#22801). Maybe the IFF transmitters could also serve as car keys for each of the vehicles "owned" by the player.

**Comment by Zireael07** [comment] 2019-01-14 12:48
Alternately, null owner tag when vehicle is initialized, and check if tag exists and is player's tag... less spurious data to keep.

**Comment by GearheadLydia** [comment] 2019-01-14 12:50
That's true. It wouldn't really matter whether the deceased owner of a vehicle is Fgsfds or a blank string.

**Comment by kevingranade** [comment] 2019-01-14 17:24
IFF transmitters and receivers are a *bit* out of scope for player craftability.

**Comment by GearheadLydia** [comment] 2019-01-15 00:19
Hmm. Fair. Maybe that should be restricted to car keys.

(Also, I still feel that the problem of turrets shooting friendly NPCs should have some work-around -- unless turrets are explicitly being balanced against by the fact that they force you to be a solo act, which is completely reasonable.)

**Closed** 2019-05-24 15:29 UTC
Labels: <Enhancement / Feature>, NPC / Factions
