### ISSUE TITLE
Using overmap auto-travel with high speed can cause you to not record map memory properly

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#74864] opened 2024-07-01 23:56 UTC
### Describe the bug

A character with high speed can cause gaps in map memory to appear using overmap auto-travel. This can be most easily seen with a character at full health, and the "Quick" and "Fleet-footed" traits. This results in the player kind of skipping/teleporting forward. This is most easily seen at night for obvious reasons. A character with a larger sight range will also not be as affected by this bug. As such, the save file character has the fast traits and 2-tile square sight range to make this bug obvious to see. 

A player with 3-tile sight range can still see this issue, but its less obvious. The first picture in the bottom-left shows my character going north, and it skipped memorizing 2 tiles halfway through the walk.

A character that is slow will not have this issue since there are more opportunities to record the players surroundings before they actually move forward.

Edit: my character is grabbing a trash can when the game loads, the trash can doesn't affect this bug, and can be let go for testing.

### Attach save file

[beepbeepbeep-trimmed.tar.gz](https://github.com/user-attachments/files/16059845/beepbeepbeep-trimmed.tar.gz)

### Steps to reproduce

1. load save file
2. open overmap view
3. use auto-move to travel 2 overmap tiles north
4. notice gaps in map memory from movement (the 2nd -> 3rd screenshot show before and after moving north 2 overmap tiles on my system)

### Expected behavior

I expect every movement of the player to be modelled and update the map memory properly such that there are no gaps.

### Screenshots

Before the save file:
![Cora _2024-07-01T19-36-12EDIT](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/7d99b63c-ce89-456f-b618-aeceb1af1efa)
![Cora _2024-07-01T19-37-50EDIT](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/6cd24565-70cc-4aea-b4a8-bf848cc642ca)

After loading save file and using overmap auto-move to move north 2 overmap tiles:
![Cora _2024-07-01T19-43-43](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/957d3f05-cf97-435a-9fa6-4a90617254d2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-25-2220 fe69e07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment] 2024-07-02 08:36
This is a re-report of #37968.

**Comment by CoroNaut** [comment] 2024-07-02 23:45
Ah, very old known issue. I like that we prioritized performance over this edge case though. Unless someone has a well-performing idea for a fix, I'm all for just closing these issues as "wontfix" or "not planned". I'll leave it to whoever wants to tag the issue.

**Comment by ZhilkinSerg** [comment] 2024-07-06 11:03
Duplicate of #37968

**Closed by ZhilkinSerg** 2024-07-06 11:03 UTC
Labels: (S1 - Need confirmation)
