### ISSUE TITLE
Wielding an item from a belt unequips the belt

### ISSUE THREAD

**Issue by KongMD-Steam** [CleverRaven/Cataclysm-DDA#28332] opened 2019-02-23 13:10 UTC
**Describe the bug**  
When wielding an item from a belt, that belt is unequipped.

**To Reproduce**  
1. Make a new character with the firefighter profession
2. Wield the Halligan Bar
3. Observe that the belt is unequipped

**Expected behavior**  
The belt stays equipped when wielding an item.

**Versions and configuration(please complete the following information):**
 - OS: Windows 8
 - Game Version: Build 8538
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by keyspace** [comment] 2019-02-23 17:09
Cannot reproduce on on Linux using 60ad4a4a0e4140b0329e53c65d1e7309cb991a15 (today; corresponds to build 8538?..) or eef02eec8c2814c5dd7617ce0b081ba006621907 (~2 weeks ago), using a regular-game character with belt and slingshot, or firefighter belt and halligan bar; through `a`ction menu.

**Comment by ifreund** [comment] 2019-02-23 17:17
The issue is with `w`ielding not `a`ctivating

**Comment by keyspace** [comment] 2019-02-23 17:33
Ah, my bad. (I `a`ctivate it to avoid the "Draw Halligan bar?" dialog.)

**Comment by kevingranade** [comment] 2019-02-24 07:47
Fixed by #28335

**Closed by kevingranade** 2019-02-24 07:47 UTC
Labels: (S2 - Confirmed), <Bug>, Character / Player, Items / Item Actions / Item Qualities
