### ISSUE TITLE
Unable to remove bionics using the autodoc.

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#44953] opened 2020-10-19 16:05 UTC
# Describe the bug
I've tried to use the autodoc to remove a bionic but instead it falls to a debug error, ignoring it result in a message "You don't have any bionics to install."

# Steps To Reproduce
1. Make a prototype cyborg.
2. Interact with the autodoc.
3. Get error and later unable to remove any bionics.

# Expected behavior
Being able to use the autodoc.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7008-gf8d184a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Bionic Professions [package_bionic_professions], Stats Through Skills [StatsThroughSkills]]

# Additional context
the log.
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5403157/debug.log.zip)

**Comment by Fris0uman** [comment] 2020-10-19 16:15
duplicate of #44156

**Closed** 2020-10-19 18:07 UTC

**Comment by Xindage** [comment] 2020-10-20 14:42
well i cant really tell it to be exactly same bug, as mentioned in #44156 it was not causing any major issue, it was just a DEBUG error but i was able to proceed with the removal regardless of the debug error, now I'm unable completely to remove any cbm.

Like if the bug got worse with the updates.
