### ISSUE TITLE
Codeblocks compile issue nanosleep

### ISSUE THREAD

**Issue by ModDownloading** [CleverRaven/Cataclysm-DDA#44387] opened 2020-09-24 13:43 UTC
When you download the source code and try to compile it with Codeblocks, an error appears saying that on line 71 of the animations.cpp at this part of the code the nanosleep function is not declared for this scope:

        void progress() const {
            draw();

            if( delay.tv_nsec > 0 ) {
                nanosleep( &delay, nullptr );     << THIS LINE
            }
        }

# Steps To Reproduce

Download source code
Open it with Codeblocks and try to build it

# Versions and configuration

Windows 7, 64x

**Comment by ZhilkinSerg** [comment] 2020-09-24 14:21
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/27799

**Comment by ModDownloading** [comment] 2020-09-24 14:41
I saw that one already, but I thought that issue was fixed even though I am still getting the error here. In addition, the error from that issue was on a different line and in a different file than my issue, even if they both reference nanosleep.

**Comment by Qrox** [comment] 2020-09-24 16:41
Probably something wrong with the macro guards in `posix_time.h`. What value does Codeblocks have for `__CYGWIN__` and `WINPTHREAD_API`?

**Closed** 2020-09-25 06:28 UTC
Labels: Code: Build, OS: Windows
