### ISSUE TITLE
npc_class text missing in experimental 0.C-7929-gb807576

### ISSUE THREAD

**Issue by Chicken12341** [CleverRaven/Cataclysm-DDA#14302] opened 2015-12-04 08:06 UTC
https://gyazo.com/b5cdcb0f94367637f5a087b1bb76d370

OS: Windows 8.1
VER: Tiles

When asking an npc what they are doing I'm given an Error about a missing npc_class text. This is only one case, however I've seen in happen a few times in NPC dialogues. If it helps, I have wandering npcs and static npcs both enabled.

I've encountered this a few times (3-4) in the past 2 days, one on the Exp branch listed and another on a slightly earlier one. The last time this error was reported was in Jun and it was on 0.C Stable so I figured I'd create another issue.

**Comment by remyroy** [comment] 2015-12-08 05:36
Do you have a reliable and easy way to reproduce this or a save file that would always reproduce it?

**Comment by mugling** [comment] 2016-06-04 22:24
Closing due to lack of confirmation at 6 months with no obvious further actions

**Closed by mugling** 2016-06-04 22:24 UTC
Labels: Bug, Confirmation Needed
