### ISSUE TITLE
Integrated AR Bionic doesn't store books

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#78615] opened 2024-12-17 00:11 UTC
### Describe the bug

Normally, it's possible to scan books into the AR mod and then read them later. However, trying to read what was scanned won't work as it will say that there isn't anything to read when there should be. 

### Attach save file

[Integrated AR Test-trimmed.tar.gz](https://github.com/user-attachments/files/18158372/Integrated.AR.Test-trimmed.tar.gz)

### Steps to reproduce

1. Scan the book in inventory (or spawn one to scan) with the AR mod.
2. Attempt to read the book.

### Expected behavior

The books I scanned should be available to read.

### Screenshots

![Screenshot (178)](https://github.com/user-attachments/assets/67388ac6-fa61-4c0d-b93d-f1cbd137a124)
![Screenshot (179)](https://github.com/user-attachments/assets/07dbc212-fa17-443e-a93d-442e5cac3aee)
![Screenshot (180)](https://github.com/user-attachments/assets/75e5695e-eb13-41be-9017-f9566d561828)
![Screenshot (181)](https://github.com/user-attachments/assets/3f89b1d9-7ad9-4afd-b29c-a82a1bf00d90)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 61f58dc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Mind Over Matter [mindovermatter],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter: <color_magenta>Remove Calorie Cost from Psionics</color> [mom_no_calorie_cost],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    Mind Over Matter: <color_magenta>Remove Pain Disables Powers</color> [mom_remove_pain_disables_psi_limit],
    Mind Over Matter: <color_magenta>Remove Random Delay Before Gaining Power Insight</color> [mom_no_power_path_check_learn_delay],
    Mind Over Matter: <color_magenta>No Nether Attunement Effects</color> [mom_no_nether_attunement],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by ave-** [comment] 2024-12-17 06:55
Possible duplicate of #78245

**Comment by terribleperson** [comment] 2024-12-19 09:22
Noticed this issue in my latest game. Downloaded latest experimental (438b5e4), created a new world and random character, debug installed the AR system, scanned a book, confirmed the issue is still present.
/confirm

**Comment by jwgrawe** [comment] 2024-12-28 14:33
Probably related to #78184

**Closed** 2024-12-30 16:12 UTC
Labels: (S2 - Confirmed)
