### ISSUE TITLE
Rigid integrated armor (Chitin Carapace, Patchwork Skin) prevents wearing splints, healing broken limbs

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60726] opened 2022-09-03 18:38 UTC
### Describe the bug

If you have rigid integrated armor, you can't wear a splint, because splints are also rigid. As far as I know, this renders those mutant incapable of healing broken limbs.. The same would be true of any future mutations or CBMs that grant rigid armor.

### Steps to reproduce

1. Mutate chitin carapace
2. Break arm or leg
3. Attempt to wear appropriate splint

### Expected behavior

There should be some way for mutants to heal broken limbs. You could make an exception to the rigidity rules specifically for splints and integrated armor. But since it does make some sense for thick, bony plates and the like to get in the way of a rigid, wooden splint, another option would be to introduce plaster casts or those nice semi-soft modern splints and give them some sort of exception.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: d9451f8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Amoebka** [comment] 2022-09-04 03:14
If your exoskeleton is so rigid you can't splint over it, what do you even need internal bones for at that point? It keeps everything in place by itself. IMO, instead of being compatible with splints, rigid exoskeletons _should count as splints themselves_ for the purpose of limb healing.

**Comment by PatrikLundell** [comment] 2022-09-04 08:45
I disagree because if the bones are broken, the exoskeleton probably is as well, so you'd need to keep it lined up properly to heal, at which point you could assume the bones are lined up as well. Thus, splinting or casting would probably be needed.

Also, a stiff outer shell isn't guaranteed to be a proper exoskeleton. The hide of a crocodile is rather stiff, but not completely inflexible.

Note that the issue isn't that the exoskeleton is too stiff to support splints, but rather that the game treats anything that's stiff as if this was the case. Introduction of a cast of a "compatible with other rigid items" flag might work.

**Comment by Terrorforge** [comment] 2022-09-04 17:41
> Introduction of a cast of a "compatible with other rigid items" flag might work.

Yeah, but then you're looking at a situation where you can wear a splint over plate armor or riot gear, and that seems a bit weird.

But yes, regardless of how we handle exoskeletons, there needs to be a general solution as well. Otherwise this problem is going to keep popping up every time we introduce a new rigid integrated armor.

**Comment by Night-Pryanik** [comment] 2022-11-27 04:28
Fixed by #62357.

**Closed by Night-Pryanik** 2022-11-27 04:28 UTC
Labels: (S1 - Need confirmation)
