### ISSUE TITLE
Ninjutsu not displaying as active when used with any weapon.

### ISSUE THREAD

**Issue by dreyskiy** [CleverRaven/Cataclysm-DDA#15847] opened 2016-03-21 02:57 UTC
Ninjutsu is not being displayed as the active martial art when used with weapons.  It works fine empty-handed.  

After some testing I see momentum shift going off normally, but am not getting any damage or technique bonuses.  Damage is the same regardless of what I select in the martial arts menu _.

![ninjutsuwestoc](https://cloud.githubusercontent.com/assets/17808285/13909668/5d72bae8-eed4-11e5-8778-8ee23f439516.png)

![ninjutsuwkatana](https://cloud.githubusercontent.com/assets/17808285/13909660/33652042-eed4-11e5-933d-71013172526c.png)

**Comment by dreyskiy** [comment] 2016-03-21 08:36
On further analysis I may have had incorrect expectations for ninjutsu.  I was expecting a permanent bonus to melee skills to the tune of 2x cut 1.4x bash, but based on the code it looks like that only happens when the 'surprise attack' technique triggers.  I am indeed seeing the surprise attach technique triggering every so often to this is working fine.  The only issue here is that it doesnt explicitly state that ninjutsu is enabled.

**Comment by JasonNAwesome** [comment] 2016-03-22 00:39
The issue is not limited to ninjustu when armed with a weapon, regardless of the style the UI does not display the current style selected. I don't know if this is intended or a bug.

**Comment by Shadefang** [comment] 2016-03-22 00:54
Martial art styles _do_ affect combat with weapons, if they are defined to do so in json. Hence the surprise attacks proccing, and niten/eskirima/silat working at all. While it's possible I missed something, everything except for the display seems to be working correctly.

**Comment by Oskar636** [comment] 2016-11-09 20:09
Is this martial art supposed to work with weapons?

**Comment by Leland** [comment] 2017-05-04 21:13
Near as I can tell, this isn't a bug. Closing.

**Closed by Leland** 2017-05-04 21:13 UTC
Labels: Bug, Information / Interface
