### ISSUE TITLE
Unable to learn skills from books

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#46936] opened 2021-01-22 03:32 UTC
# Describe the bug

When reading any books the log will repeatedly say "You learn a little bit about {skill}! (0%)" with no skill gain no matter how long you read.

# Steps To Reproduce

1. Load attached save.
2. Read any book on bookshelf
3. Observe the character staring at the pages and learning nothing like an exhausted student the night before finals.

# Expected behavior

To be able to learn from reading books.

# Screenshots

![image](https://user-images.githubusercontent.com/50811445/105442721-d879a080-5c2f-11eb-8d7f-35643ab08574.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9072-g1bb53ba-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Aftershock [aftershock]
]

# Additional context

I hadn't played for a while so I did a fresh reinstall right before this. I have modified nothing from base except for a few settings and soundpack/tileset. This is also a brand new world.
[World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5853419/World.zip)

**Comment by Fosheze** [comment] 2021-01-22 03:38
Just tested and I get the same results on an only base game world with a no trait all 8 stat survivor. This is not mod related.

**Comment by actual-nh** [comment] 2021-01-22 03:39
See #46908.

**Comment by anothersimulacrum** [comment] 2021-01-22 03:39
Duplicate of #46902
The fix has been merged, but no build with it is out yet.

**Closed by anothersimulacrum** 2021-01-22 03:39 UTC
