### ISSUE TITLE
Auto-move does not work well if mounted on an animal

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37808] opened 2020-02-07 17:56 UTC
# Describe the bug

Using the automove function while mounted will attempt to path you through obstacles you cannot pass while mounted.

# Steps To Reproduce

Mount an animal, and try to use automove through most terrain types. forests are almost certain to trigger this

# Expected behavior
Automove pathing while mounted avoids obstacles it cannot pass.

# Screenshots

![image](https://user-images.githubusercontent.com/47374323/74053126-7b172000-49db-11ea-991d-3faed61dfd87.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12029-g29de372 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by ymber** [comment] 2020-02-07 19:35
Duplicate of #36313.

**Closed by ymber** 2020-02-07 19:35 UTC
