### ISSUE TITLE
Wind turbines as appliances

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58353] opened 2022-06-11 19:06 UTC
### Is your feature request related to a problem? Please describe.

I constructed a (large) wind turbine and hauled it up to the roof of my base camp expansion to make it part of a power generation structure there, but found that it couldn't be placed.

### Solution you would like.

Allow wind turbines placed as appliances.

### Describe alternatives you have considered.

Use the old vehicle construction method. It worked before, and probably isn't broken.
Figure out how to do turn water wheels into appliances as well. However, these have to be constructed above the water, and so logically require a frame over the water as well as some kind of anchor on the ground, which vehicles can provide, but not appliances. For water wheels to become appliances we'd probably need some special kind of constructed terrain that acts as a frame.

### Additional context

The main purpose of this feature request is to ask whether there is some reason for these power generators to be unsuitable for appliance support, either because of some real world consideration (realism) or because of some known problem that causes support not to work.

Note: This feature request originally included water wheels as well as wind turbines, but has since been changed to only cover wind turbines as the problems with water wheels were discovered.

**Comment by GuardianDll** [comment] 2022-06-11 19:35
there was a pr for makeshift wind turbine as appliance [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/e434e5083960788c33526b775ec9dfeafb3dce4c), but due the drama in discord author decided to close and wipe them

**Comment by PatrikLundell** [comment] 2022-06-11 19:48
Thanks. I thought I'd seem them, and so was a bit surprised when they weren't there. I don't do anti-social media, so I don't know why things were suddenly just closed.

However, it looks like that could be used as a basis for appliancification of the existing turbines.

**Comment by TheShadowFerret** [comment] 2022-06-13 05:13
>Edit: It turns out water wheels can't be turned into appliances easily as the wheels have to be constructed "on" water, and so logically require a frame to sit in

Does ``"pre_terrain"`` to require water not work with appliances since they're pseudo-vehicles?

**Comment by PatrikLundell** [comment] 2022-06-13 05:50
I did briefly consider trying that, but decided that it's silly to have the appliance hover above the water without any support whatsoever even if it would work, so no, I didn't try that.

**Comment by FayFlightee** [comment] 2022-07-22 03:51
Isn't this duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56780#issue-1203136812 ?

**Comment by PatrikLundell** [comment] 2022-07-22 06:29
Yes. It turns out it's been requested before.

**Closed** 2022-08-05 11:38 UTC
Labels: Good First Issue, <Suggestion / Discussion>, [JSON], Crafting / Construction / Recipes, Appliance/Power Grid
