### ISSUE TITLE
Damage animation off center in ASCII

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#29212] opened 2019-04-01 23:42 UTC
**Describe the bug**  
Damage animations and enemy hp are way off to the side when using no tileset on the tiles version. May be related to #29186? Looks kinda similar and also is unaffected when using a tileset.

**Screenshots**  
Here I'm meleeing an enemy right below me but the animation is all the way to the right.
![Screenshot 2019-04-01 at 16 35 30](https://user-images.githubusercontent.com/12606597/55366254-ba601080-549c-11e9-8aad-3cf308b268fb.png)

**Versions and configuration(please complete the following information):**
 - OS: Chrome OS 72 running Crostini
 - Game Version: 0.D-1217-g2120ee5
 - Graphics version: Tiles
 - Mods loaded: defaults

**Comment by KorGgenT** [comment] 2019-04-02 01:41
duplicate of  #29098

**Closed by KorGgenT** 2019-04-02 01:41 UTC
