### ISSUE TITLE
Eating corn cobs consume the entire stack and doesn't grant satiety

### ISSUE THREAD

**Issue by nullinsky** [CleverRaven/Cataclysm-DDA#52529] opened 2021-10-29 17:02 UTC
### Describe the bug

Playing on 0ad2fdd, eating corn cobs from a stack does not seem to complete the action correctly, and simply turns the entire stack into empty cobs.

### Steps To Reproduce

1. Go to a field with corn cobs.
2. Harvest a plant.
3. Eat from a stack.

### Expected behavior

Should consume 1 piece at a time and grant 1 empty cob.

### Screenshots

![corn cob 1](https://user-images.githubusercontent.com/45400571/139474481-e6a42799-58c4-42c2-8bea-5c7c7b4c0678.png)
![corn cob 2](https://user-images.githubusercontent.com/45400571/139474483-ed7396c1-e8f4-4484-b282-12a4b94598c6.png)
![corn cob 3](https://user-images.githubusercontent.com/45400571/139474493-0ddca53f-22bb-46b4-90c7-3d7e0bac512a.png)

### Versions and configuration

OS: Windows 10
Game Version: 2021-10-29-0833
Graphics Version: Tiles
Mods:

[
"dda",
"no_npc_food",
"no_fungal_growth",
"package_bionic_professions",
"aftershock",
"blazeindustries",
"DinoMod",
"extra_mut_scens",
"Mining_Mod",
"Rummaging",
"cbm_slots",
"fuji_mpp"
]

**Comment by TealcOneill** [comment] 2021-10-29 21:36
Duplicate of #50002

**Comment by wapcaplet** [comment] 2021-10-30 03:08
Confirmed, I had the same thing happen recently in experimental. Thanks for reporting, but indeed this appears to be a duplicate of 50002. Closing.

**Closed by wapcaplet** 2021-10-30 03:08 UTC
Labels: (S3 - Duplicate)
