### ISSUE TITLE
Item/zone sorting starts an infinite loop of moving between 2 to 3 tiles.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#33623] opened 2019-08-28 17:11 UTC
# Describe the bug
Item/zone sorting either sorts items in visible zones and then goes in an infinite loop of moving between 2 to 3 tiles or skips sorting any items and goes into an infinite loop.
The only way to stop the loop is to kill/terminate the game process.

# Steps To Reproduce
1. Have at least one unsorted zone with items on it and one loot zone for said items.
2. Begin autosorting "shift - o"

# Expected behavior
Autosorting should not go in an infinite loop and you should be able to stop it by pressing 5 on the numpad.

# Screenshots
N/A

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 18.0.4; Codename: Illyria; 
- Game Version: 0.D-7032-gdfe287eddf-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Garden Pots [growable-pots],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Save game 
[West Jefferson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3552050/West.Jefferson.zip)

**Comment by davidpwbrown** [comment] 2019-08-28 17:32
duplicate of #33581 , same cause.

**Closed by davidpwbrown** 2019-08-28 17:32 UTC
Labels: (P1 - Critical), <Bug>, <Crash / Freeze>, Inventory / AIM / Zones
