### ISSUE TITLE
Some 0.F stable saves crash in 0.F experimental

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#51127] opened 2021-08-27 15:33 UTC
### Describe the bug

It's been discovered that 0.F stable saves supplied with bug reports crash when loaded in 0.F experimental (after ignoring reports about PARKOUR and items being too large) as soon as the next action is taken.

This report contains some info, as well as a save https://github.com/CleverRaven/Cataclysm-DDA/issues/50596

### Steps To Reproduce

1. Load the save in #50596 
2. Do something (probably anything advancing time)
3. Crash to desktop

### Expected behavior

Migrated saves should migrate.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

My best guess is that the activity of one of the companions may have been modified in such a way that the migration fails to handle it properly, but that's just a wild guess.

**Comment by dseguin** [comment] 2021-08-28 02:36
With the current master branch, I tried loading a save from 0.F (not 0.F-1). It seemed to work. [Here's a link the save file.](https://github.com/CleverRaven/Cataclysm-DDA/files/7070035/TestWorld.zip)

**Comment by eltank** [comment] 2021-08-28 02:55
I'd advise changing the title to "Some 0.F stable saves crash in 0.F experimental" for clarity.

**Comment by dseguin** [comment] 2021-08-28 02:57
Sorry, I didn't realize it was a limited issue.

**Comment by eltank** [comment] 2021-08-28 03:05
No worries, your save may still be helpful.

**Comment by hexagonrecursion** [comment] 2021-08-28 06:06
I did compile with `-g -Og`. I'll see if allows me to generate a good backtrace. There is a possibility that this is the same as  #50669

**Comment by eltank** [comment] 2021-08-28 06:31
Going to copy my comments from #50596 because I should have been commenting on this bug instead.

Minimal save file to reproduce the bug: [PLSave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7070261/PLSave.zip)

Relevant JSON data for the 2 NPCs performing activities:

```
"current_activity_id":"ACT_VEHICLE"
"activity":{"type":"ACT_VEHICLE","actor":null,"moves_left":34962,"index":111,"position":-2147483648,"coords":[],"coord_set":[[10521,3443,0],[10521,3442,0],[10518,3440,0],[10521,3441,0],[10516,3443,0],[10518,3439,0],[10518,3442,0],[10520,3439,0],[10517,3443,0],[10518,3443,0],[10517,3439,0],[10520,3443,0],[10519,3440,0],[10518,3441,0],[10517,3442,0],[10519,3439,0],[10520,3440,0],[10519,3441,0],[10519,3442,0],[10521,3439,0],[10519,3443,0],[10515,3443,0],[10521,3440,0],[10520,3441,0],[10520,3442,0]],"name":"","targets":[{"type":"null"}],"placement":[10518,3440,0],"values":[10518,3440,0,0,0,0,18],"str_values":["hdframe"],"auto_resume":false,"monsters":[]}

"current_activity_id":"ACT_READ"
"activity":{"type":"ACT_READ","actor":null,"moves_left":66200,"index":0,"position":109,"coords":[],"coord_set":[],"name":"","targets":[{"type":"character","character":109,"idx":9}],"placement":[-2147483648,-2147483648,-2147483648],"values":[],"str_values":["1,000000"],"auto_resume":false,"monsters":[]}
```

Crash source is in player_activity.cpp:
```
    if( type == activity_id( "ACT_MIGRATION_CANCEL" ) ) {
        actor->do_turn( *this, you );
        return;
    }
```
The save migration code creates a ACT_MIGRATION_CANCEL activity with actor set to null. Can be fixed by null guard.

**Closed** 2021-08-29 02:15 UTC
Labels: <Bug>, <Crash / Freeze>, (P2 - High)
