### ISSUE TITLE
Many dropped cash cards are (0).

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19140] opened 2016-11-03 21:27 UTC
I've just started to notice this in the latest builds, whereas before, I never saw this.. but, when picking up cash cards, many of the cards are zero (0).  I might have seen 1 in 100 cards before set to zero, but now, it's more common than seeing cards with value.

Also, I've noticed that most Zombie soldiers are dropping the max cash card, 20000000, which seems odd, since before, I would never see a max card, or maybe one in 1000.

**Comment by Lazasar** [comment] 2016-11-03 21:33
Cops are also dropping the 20000000

**Comment by mugling** [comment] 2016-11-03 23:34
seen both

**Comment by ArikVhedrovix** [comment] 2016-11-03 23:36
Yup. Z Scientists seem to only drop cash cards with 0. Z soldier just dropped max 20000000 card.

**Comment by illi-kun** [comment] 2016-11-04 10:55
Duplicate of #16885.

**Closed by illi-kun** 2016-11-04 10:55 UTC
Labels: Bug, Duplicate, validated
