### ISSUE TITLE
map::get_nonant Crash

### ISSUE THREAD

**Issue by HarleyLorenzo** [CleverRaven/Cataclysm-DDA#36208] opened 2019-12-18 03:37 UTC
# Describe the bug

In a very specific position in the game world, my game will crash consistently upon crossing. In addition, the game would crash with the same error inconsistently in various other parts in the game world, however, this one is consistent and I was able to save right before the crash and replicate it.

# Steps To Reproduce

1. Load the save
2. Walk left
3. Crash with a map::get_nonant error

# Expected behavior

Not crashing when moving across the street.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.D-10426-ge93e21d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Crazy Cataclysm [crazy_cataclysm],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Stats Through Skills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff]
]

# Additional context

[crash_and_debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3976534/crash_and_debug.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3976537/Save.zip)

**Comment by ymber** [comment] 2019-12-18 07:11
Duplicate of #36138.

**Closed by ymber** 2019-12-18 07:11 UTC
