### ISSUE TITLE
'Start Vehicle Construction' errors if only one frame present, works (somewhat) if two are present

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#18701] opened 2016-10-09 13:45 UTC
Encountered on experimental version 5662, may have manifested previously. This is the one I updated to this morning.

Whenever you try to use the construction 'Start Vehicle Construction' with a single frame, a debug message appears and the frame you are trying to use is deleted:

![debug message](http://puu.sh/rCXBN/085db83ff9.png)

However, if you have **two** frames present (doesn't matter what kind), the vehicle construction succeeds, albeit destroying one of the frames in the process. If using two different types of frames, you must **not** select the intended material as the frame used in the construction.

Example: You have a steel frame and a light wooden frame. You want to have a vehicle made with the light wooden frame. Select the steel frame when it asks which frame to use; the steel frame will be lost and the vehicle will be made with the light wooden frame.

**Comment by illi-kun** [comment] 2016-10-09 14:25
Duplicate of #18372.

**Closed by illi-kun** 2016-10-09 14:25 UTC
