### ISSUE TITLE
deploying reinforced items cancels their reinforcement

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18116] opened 2016-08-24 20:38 UTC
reinforce a rollmat, turret, tent, anything that can be deployed
deploy it
pick it back up
the reinforcement is gone

**Comment by BevapDin** [comment] 2016-08-31 23:43
Closing as it's a duplicate of #7112. That issue uses a technical description: "damage -1" is how the game stores the reinforced status.

**Closed by BevapDin** 2016-08-31 23:43 UTC
