### ISSUE TITLE
Horses loudly pace back and forth when not paid attention to

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32746] opened 2019-07-30 00:29 UTC
# Describe the bug

It's fine that horses make noise, but they never stop making noise unless you tie them down. Here's me fitting a tank to a vehicle while a horse is nearby:

![noisy-horse](https://user-images.githubusercontent.com/12072/62091480-7e0ab880-b2b4-11e9-81f6-c167a57a28c2.png)

# Steps To Reproduce

1. Make friends with a horse
1. Do literally anything near the horse
1. Observe the horse stomping around you like a four-legged child throwing a tantrum until you pay attention to it.

# Expected behavior

Horses are quiet and less needy.

# Versions and configuration

- Ubuntu 16.04 LTS
- Version: 03c92080c77055ddd22223c1b122ce41291de856
- Graphics: Tiles

**Comment by brannamm** [comment] 2019-07-30 04:49
Could you expand on the expected behavior?

**Comment by pjf** [comment] 2019-07-30 05:18
> Could you expand on the expected behavior?

Horses make footstep sounds with the same frequency as other similarly sized animals, rather than 3,000+ times per minute. :)

**Comment by pjf** [comment] 2019-07-30 05:20
Currently horses be like...

[![horse](https://user-images.githubusercontent.com/12072/62102757-74497b00-b2dd-11e9-8443-4530a28f4f52.png)](https://hyperboleandahalf.blogspot.com/2010/03/animals.html)

**Comment by l29ah** [comment] 2019-07-30 16:37
Probably a dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/31961

**Closed** 2019-07-31 05:42 UTC
Labels: (S2 - Confirmed), (S3 - Duplicate), <Bug>, Code: Performance, Monsters, Sound Events
