### ISSUE TITLE
Dropping items inside helicopter wreckage makes them permanently dissapear

### ISSUE THREAD

**Issue by atazs** [CleverRaven/Cataclysm-DDA#41859] opened 2020-07-05 09:29 UTC
# Describe the bug

I dropped items into a helicopter wreckage and could not pick them up afterwards, there were no items on the ground. They were gone. 

# Steps To Reproduce

Start as crashed helicopter pilot
Drop items inside the wreckage you start at
Watch them dissapear

# Expected behavior

You should be able to pick up dropped items inside wreckages

# Versions and configuration

CDDA version 0.E-3725-g69cf449 (tiles)
Build: 10808

**Comment by EvgenijM86** [comment] 2020-07-05 09:48
Maybe you need to clear the wreckage with a shovel first?

**Comment by atazs** [comment] 2020-07-05 10:19
> Maybe you need to clear the wreckage with a shovel first?

You don't understand. I was inside the vehicle itself, standing on a seat when i dropped an item which dissapeared permanently. 
On any other vehicle, when you stand on a seat or whatever, and drop something that can't fit, it drops on the ground and i have the option to pick up said items from the ground.

**Comment by EvgenijM86** [comment] 2020-07-05 10:35
Helicopter crash generates with metallic wreckage under the vehicle. You can clear it with a shovel, but you need to activate the shovel and select "clear" option, instead of just pressing 'e' (otherwise you would select a vehicle instead).

**Comment by jtgibson01** [comment] 2020-07-06 11:34
EvgenijM86 (not tagging with @ as he doesn't need to be paged =)) is correct as to the cause -- items stored in a wreckage terrain tile are hidden.  However, this is almost certainly unintuitive behaviour all the same; it should not be possible to put items into a wreckage tile to bury them (and even if intentional, especially not as a zero-turn action!).  Since it is far less likely that a player wants to bury the item in the tile rather than drop the item for later retrieval, attempting to drop an item on a wreckage tile should be blocked with a specific warning message.  Something like "There is no room to drop the item on the \s."  It might be possible to set the f_wreckage to have a volume capacity of zero to handle it entirely in soft code, but that might break too much spawning.

**Comment by EvgenijM86** [comment] 2020-07-06 11:49
That would create another issue of not being able to drop items in a wreckage as not realistic. If I see a pile of thrash I can certainly throw an item inside it in real life, even if it means that I will have trouble finding that item later.

**Comment by jtgibson01** [comment] 2020-07-06 11:49
Tried to ninja this in, but you're up and about!  I'll do a full post. =)

Thinking more on this, maybe an alternative: `BURIES_ITEMS`.  Attempting to drop an item into a buries-items tile will give a y/n prompt: "Bury the \s in the \s? (Y)es/(N)o", and there may be an optional roundtime.  This would allow the original behaviour while also making it intuitive that dropping the item there will hide it and effectively remove it from play.

**Comment by KorGgenT** [comment] 2020-07-11 08:32
I'm marking this as a bug because the player didn't know what was going on - i think a reasonable fix for this is a message in the log, something like "your item has fallen into the wreckage and has been covered" hopefully slightly better worded

**Comment by Night-Pryanik** [comment] 2021-04-12 16:37
This is just another variation of #8979.

**Closed by Night-Pryanik** 2021-04-12 16:37 UTC
Labels: <Bug>, Info / User Interface
