### ISSUE TITLE
Segmentation fault when moving southeast

### ISSUE THREAD

**Issue by TheMasterGear** [CleverRaven/Cataclysm-DDA#41868] opened 2020-07-05 17:32 UTC
# Describe the bug

The game crashed when exploring the forest

# Steps To Reproduce

1. Load this save
(https://github.com/CleverRaven/Cataclysm-DDA/files/4875308/Vida.zip)

2. Go southeast for a few moments.

3. The game will crash.

# Expected behavior

Continued movement without crashing

# Screenshots

![Segmentation fault](https://user-images.githubusercontent.com/60374171/86538223-b3575780-bec2-11ea-91c5-4fa18dcf94a7.png)

![map](https://user-images.githubusercontent.com/60374171/86538340-7a6bb280-bec3-11ea-9f13-75b14261821c.png)

# Versions and configuration
13:24:18.742 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Ricky's Future Armory [futurearmory],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Alternate ear graphics [alt_ear_gfx],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4875316/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4875313/debug.log)
[Vida.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4875308/Vida.zip)

**Comment by olanti-p** [comment] 2020-07-05 18:02
Duplicate of #41804

**Closed** 2020-07-05 18:04 UTC
Labels: (S3 - Duplicate)
