### ISSUE TITLE
Multi-cooker draws huge power, can't unload battery

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#58641] opened 2022-06-23 01:02 UTC
### Describe the bug

Multicooker draws huge amounts of power.
Cooking a single scrap of meat costs 185 charges from its medium battery, of 500. 
The same job costs 1 charge on a hotplate. 
Most jobs are not possible due to power demands. 

Maybe 2 or 3 times the draw would make sense. 
Suspect this line is involved: 
CDDA\data\json\items\tool\cooking.json

    "power_draw": 1500000,

Also, it doesn't seem possible to unload the battery from the cooker. 
The attempt dump whatever contents were in it. 
Trying from the pocket organizing interface shows the battery in pocket one, but no interface options. 

### Steps to reproduce

Spawn in a multi-cooker. 
Load it with a battery if needed. 
Cook a scrap of meat. 
Note the remaining battery charge. 
Try to reload the battery. 

### Expected behavior

The same job costs 1 charge on a hotplate. 
Most jobs are not possible due to power demands. 

Maybe 2 or 3 times the draw would make sense. 
It is doing all the work, after all. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.239 (1903)
- Game Version: 03f4e32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Cataclysm++ [Cata++],
    Xedra Evolved [xedra_evolved],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by Inglonias** [comment] 2022-06-23 21:31
I can't speak to power consumption, but the battery unloading issue was fixed in #58315 . That got merged into the very next version of the game after yours. Update your experimental.

**Comment by vlad1492** [comment] 2022-06-23 21:46
Thanks, will update. Got to remember to check that before posting bugs. 

Hmm, I think I get your point. If we are calling 1 battery unit 1kJ. 
That would mean 500,000 watt-seconds for a medium, 139wh or so. 
Enough to run an 1500w teakettle for 6 minutes maybe. So, two pots of tea?

**Comment by hexagonrecursion** [comment] 2022-06-29 05:27
/confirmed

Wow! Why, CDD:A? Why?! Why go through all the trouble to implement a separate "cooking with a multicooker"  mechanic when we already have a perfectly serviceable general purpose crafting mechanic?

1. [a]ctivate
2. multicooker (cook)
3. select the recipe
4. notice inconsistencies

Note: a multicooker can also be used as a tool in regular crafting with power draw comparable to other tools

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment] 2022-06-29 06:32
>Why go through all the trouble to implement a separate "cooking with a multicooker" mechanic

Probably all ancient stuff, I have not looked at the blame yet but I bet 10 merch that this was done when the mechanics were not in place.

Also, do not forget that there is an evil multicooker for a reason <sup>/s, unrelated</sup>

**Comment by hexagonrecursion** [comment] 2022-06-30 04:24
> > Why go through all the trouble to implement a separate "cooking with a multicooker" mechanic
> 
> Probably all ancient stuff, I have not looked at the blame yet but I bet 10 merch that this was done when the mechanics were not in place.
> 
> Also, do not forget that there is an evil multicooker for a reason /s, unrelated

origin of the multicooker: https://github.com/CleverRaven/Cataclysm-DDA/pull/8339

P.S. Git pickaxe feature is amazing
```
git log -S MULTICOOKER -- data/json/
```

**Comment by RenechCDDA** [comment] 2022-11-12 04:57
After lots of kicking around and chasing the history of energy units, I'd say that the power usage appears.... correct? If you google for multicookers you'll get something in the 1000-watt range - aka 1kJ. Our battery units are 1kJ 'per charge' (a heavy battery with 500 charge = 500kJ). The multicooker draws about 1.5kJ (that is, per second). That's... normal. It's a ton of power, but it's normal. The only issue is in perception, as almost all crafting in the game (especially cooking) uses arbitrary made up energy requirements which are much lower than reality. The multicooker does not, therefore it *appears* to draw far too much power.

**Comment by NetSysFire** [comment] 2022-11-12 09:02
@anoobindisguise do you think you can make #62180 close this?

**Comment by anoobindisguise** [comment] 2022-11-12 19:58
> @anoobindisguise do you think you can make #62180 close this?

I'll have to figure out exactly how the multicooker works. right now it is priced, efficiency-wise, as a hotplate. the issue is that it's somewhat dependent on multi-mag unless it gets turned into an appliance, but it is a a web of complicated hardcode that I'll need to untangle and understand. Looks like it consumes a very high power draw (1.5kW?) for the duration of the cook time, so a chunk of meat is taking 1.5kW for the whole time it is cooking - but I don't know if it also charges for the price of the meat itself. I'll test it some.

**Comment by Night-Pryanik** [comment] 2022-12-03 19:20
> Why go through all the trouble to implement a separate "cooking with a multicooker" mechanic when we already have a perfectly serviceable general purpose crafting mechanic?

Because cooking with multicooker allows you to attend to any other activity during the process. Using general purpose crafting mechanic for cooking food, on the other side, takes all your attention and doesn't allow you to do anything else in the process, even for the most basic recipes like boiling water.

**Closed** 2022-12-05 12:03 UTC
Labels: Game: Balance, (S2 - Confirmed), Items: Battery / UPS
