### ISSUE TITLE
All wildlife are cats

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#59215] opened 2022-07-13 00:46 UTC
### Describe the bug

Every random creature I've seen in the wilderness is a cat. There might be exceptions but it seems like there are a TON of cats recently and not much anything else.

### Steps to reproduce

1. wander around wilderness in a new world.
2. observe cats.

### Expected behavior

Cats shouldn't be the only remaining species on the planet.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: 0.F-9865-gca3ce7db91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ReynTheLord** [comment] 2022-07-13 01:44
Happened to me too.

**Comment by pjf** [comment] 2022-07-13 04:22
I also seem to have found the game is putting the 'cat' back in 'cataclysm'.

**Comment by nik-ovchin** [comment] 2022-07-13 13:21
Yeap, confirm. I seen couple deer, but all small creatures is cats.

**Comment by Merikona** [comment] 2022-07-13 17:32
Must be a result of a recent update? My experimental dates back to late June and I feel like I'm missing out on cats. Haven't seen a single one yet.

**Comment by PatrikLundell** [comment] 2022-07-13 18:16
Yes, the addition of a whole bunch of new wildlife killer variants is only a few days or so old.

**Comment by KHeket** [comment] 2022-07-13 19:19
> Must be a result of a recent update? My experimental dates back to late June and I feel like I'm missing out. Haven't seen a single one yet, unless a bobcat counts.

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-11-0524 update
and pr with adding cats is:
https://github.com/CleverRaven/Cataclysm-DDA/pull/59154
https://github.com/CleverRaven/Cataclysm-DDA/pull/59104

@NetSysFire need you help, becouse we have catapocalypsys cataclysm here

**Comment by ReynTheLord** [comment] 2022-07-13 19:24
THE CURSE OF BAST IS UPON US.

**Comment by NetSysFire** [comment] 2022-07-13 19:37
wontfix: it is **cat**aclysm. Deal with your new feline overlords now.

Just kidding. I'll take a look.

**Comment by Maleclypse** [comment] 2022-07-13 23:52
I think we should leave this issue open after the fix is merged because I can’t see any reason why this is causing the behavior we are seeing.

**Comment by TheShadowFerret** [comment] 2022-07-13 23:53
~~This wasn't a Dwarf Fortress reference?~~

**Comment by NetSysFire** [comment] 2022-07-14 00:24
This is a dwarf fortress-style issue for sure.

@Maleclypse I am understanding it currently works like this:

```json
{ "monster": "mon_cat", "weight": 5 },
{ "monster": "mon_something else", "weight": 5 },
```

The above works as expected but however this does not:

```json
{ "group": "GROUP_STRAY_CATS", "weight": 5 },
{ "monster": "mon_something_else", "weight": 5 },
```

Beucase it basically turns into:

```json
{ "monster": "mon_cat", "weight": 50 },
{ "monster": "mon_cat_kitten", "weight": 5 },
{ "monster": "mon_cat_calico", "weight": 50 },
{ "monster": "mon_cat_calico_kitten", "weight": 5 },
...
{ "monster": "mon_something else", "weight": 5 },
```

This is my guess at least, seeing at how the spawns reacted to me fiddling with the `GROUP_FOREST` spawn locally to resolve the feline world domination problem. Currently it looks like it includes the group as is, inserting all the entries of the group with their original weights intact instead of considering the group as a whole. So in our example, there is a 50/50 chance of the monster being a cat (like intended), but with the `group` being used, the chance of a monster being any cat is nigh 99% since all the entries are inserted into the array.

The intended behavior is that the chance the monster is any cat is still 50/50 and the chance of said cat being e.g a calico kitten is a different, irrelevant chance which is internal to said monstergroup. The monstergroups weights should affect only itself.

I hope I explained that right since I am a total noob.

**Closed** 2022-07-14 00:57 UTC
Labels: <Bug>, (S2 - Confirmed), Spawn, Monsters

**Comment by PatrikLundell** [comment] 2022-07-14 09:49
I disagree with @Maleclypse's comment. Rather than keeping this issue open (it's closed as of this writing), a new issue on the group misbehavior should be opened for the underlying issue (written by someone with at least some understanding of the issue).

**Comment by pjf** [comment] 2022-07-14 11:02
I do feel this bug is somewhat ameliorated by the fact that you can [carry an infinite number of cats](https://github.com/CleverRaven/Cataclysm-DDA/issues/34069), a feature which Dwarf Fortress lacks.

**Comment by PatrikLundell** [comment] 2022-07-14 11:08
Dwarf Fortress has drawbridges to deal with the problem, though.
