### ISSUE TITLE
Crash when choosing preset character

### ISSUE THREAD

**Issue by CodedSquid** [CleverRaven/Cataclysm-DDA#13620] opened 2015-09-21 04:25 UTC
OS: Windows 7 64-bit
Type: Curses
Version: 0.C-3703-b47752d

If you have created multiple templates in the latest version, you will be stuck using only one. When trying to select a different preset using the arrow keys or vi keys, it will crash to 'cataclysm.exe has stopped working' leaving you to have to go through and re-create all but one template, over and over. It's a small issue, but a minor annoyance is still annoying.

**Comment by drbig** [comment] 2015-09-21 06:37
Looks like a duplicate of #13600.

**Comment by BevapDin** [comment] 2015-09-29 11:26
Fixed by #13668.

**Closed by BevapDin** 2015-09-29 11:26 UTC
Labels: Duplicate
