### ISSUE TITLE
Game crashes when trying to start a new game

### ISSUE THREAD

**Issue by UriyaBA** [CleverRaven/Cataclysm-DDA#52000] opened 2021-09-30 15:27 UTC
### Describe the bug

Upon launching the game and selecting "New Game", then any of the options in the sub-menu which appears afterwards, the game crashes during loading "Dark Days Ahead" files.

### Steps To Reproduce

1. Launch the game.
2. In the main menu, select "New Game", then select any of the options in the sub-menu which appears afterwards ("Custom Character", "Fixed Scenario", "Play Now" etc.)

### Expected behavior

I expected the character creation screen to appear after the short file loading which usually occurs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 76635e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The world I'm trying to create a new character in, was created a few experimental versions before 76635e3, I don't remember exactly which. Not too many versions ago, though.

**Comment by Zeilos** [comment] 2021-09-30 15:35
Okay, I can confirm the same issue on a fresh copy. I'm guessing this was an issue in the last build.
Ver: 766535e3

**Comment by BrettDong** [comment] 2021-09-30 15:35
Duplicate of #51991

**Closed by BrettDong** 2021-09-30 15:35 UTC
