### ISSUE TITLE
Game Crashes after selecting what to butcher

### ISSUE THREAD

**Issue by Binary-2** [CleverRaven/Cataclysm-DDA#43164] opened 2020-08-23 22:26 UTC
![image](https://user-images.githubusercontent.com/38906390/90990268-ed54e980-e554-11ea-8252-08a4f5097459.png)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5115124/debug.log)

As the title says, the game immediately crashes after selecting something to butcher.

**Comment by Binary-2** [comment] 2020-08-23 22:29
Already reported issue, fix was PR'd

**Comment by Binary-2** [comment] 2020-08-24 21:55
Game still crashes for older characters, it might be an issue with legacy code but here's my logs.

![image](https://user-images.githubusercontent.com/38906390/91100282-c01e3f00-e619-11ea-8f81-2e23c9ceae66.png)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5120411/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5120412/debug.log)

**Comment by DoctorVanGogh** [comment] 2020-08-25 00:02
Duplicate of #43125

Should be fixed in build 10949 onward.

**Comment by anothersimulacrum** [comment] 2020-08-25 00:03
Yep, from a build before the fix.

**Closed by anothersimulacrum** 2020-08-25 00:03 UTC
