### ISSUE TITLE
evac shelter faction camp has a buggy upgrade option

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#39113] opened 2020-03-29 20:03 UTC
# Describe the bug

One of the option to furniture SW bedroom seems broken. It costs nothing and makes it unable for NPC to come back.

# Steps To Reproduce

Not sure here, but I was just 
1. building my base up to a point where I could furniture SW bedroom.
2. Then just pick an option to use makeshift beds, which costs nothing and 
3. try to recall NPC after finishing the job (instantly).
4. observe the weird message and your NPC not returning.

# Expected behavior

Everything to work in the usual fashion. You pay for furniture and NPC builds it for you.

# Screenshots

![obraz](https://user-images.githubusercontent.com/54743246/77859302-e07fd400-7208-11ea-9966-a15f4decc72f.png)

![obraz](https://user-images.githubusercontent.com/54743246/77859316-f1304a00-7208-11ea-8017-04bcccd4d695.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-13486-g5a52d64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I have two farm fields expansions, not finished. Do not think that matters though.

Additionally, it seems that after emergency recall, I cant furnish the bedroom - the option is no longer available (possibly it is the same for other upgrades?)

**Comment by Feuerhai** [comment] 2020-04-10 11:18
Duplicate of #36594, but this one has pictures

**Comment by RenechCDDA** [comment] 2023-07-01 14:40
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/36594

**Closed by RenechCDDA** 2023-07-01 14:40 UTC
Labels: <Bug>, Player Faction Base / Camp
