### ISSUE TITLE
Cyrillic is not supported 

### ISSUE THREAD

**Issue by Ryazhenka0** [CleverRaven/Cataclysm-DDA#64826] opened 2023-04-04 18:19 UTC
### Describe the bug

When trying to load a character template, I got this error:
DEBUG    : Ошибка чтения из «C:/Users/User/Desktop/CDDA/dda/userdata/templates/РџРѕСЃР»РµРґРЅРёР№ РїРµСЂСЃРѕРЅР°Р¶.template»: C:/Users/User/Desktop/CDDA/dda/userdata/templates/РџРѕСЃР»РµРґРЅРёР№ РїРµСЂСЃРѕРЅР°Р¶.template does not exist.

 FUNCTION : read_from_file_json
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\cata_utility.cpp
 LINE     : 540
 VERSION  : e084982

### Attach save file

N/A

### Steps to reproduce

1.Create a world template and name them using Cyrillic alphabet.
2.Try downloading this.

### Expected behavior

Waiting for the template to load.

### Versions and configuration

-OS: Windows 
 -OS Version:10.0.17763.2565(1809)
-Game Version: e084982 [64-bit]
-Graphic Version: Tiles
-Game Language: Русский [ru]
-Mods loaded:[
 Тёмные Дни Впереди [dda],
 Бионические профессии [package_bionic_professions],
Сценарии с допмутациями [extra_mat_scens],
Перевод сложных диалогов [translate_dialogue],
Приручаемая живность [Tamable_Wildlife],
Массачусетс [MA],
Характеристики за навыки [StatsThroughSkills],
Blaze Industries [blaze Industries]
]

**Comment by Vaskritaya** [comment] 2023-04-04 19:50
same problem as https://github.com/CleverRaven/Cataclysm-DDA/issues/64328, maybe?

**Comment by Cenness** [comment] 2023-04-04 20:04
Probably not. This issue is about character template named `Last character` in russian which is auto created.  
I've tried both - world and template with cyrillic names - they all load.

**Comment by Ryazhenka0** [comment] 2023-04-07 16:50
> Can't reproduce. Tried naming template as `например так`, `Последний персонаж` and `РџРѕСЃР»РµРґРЅРёР№ РїРµСЂСЃРѕРЅР°Р¶` - all loaded successfully. Please attach the template.
> 
> And write your windows username, maybe problem is there. Or just move game folder to C:\cdda\

Username - User. The steps to complete are already listed, when I follow them the game catches an error

**Comment by anothersimulacrum** [comment] 2023-04-07 17:04
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64328

Try using the MSVC version.

**Closed by anothersimulacrum** 2023-04-07 17:04 UTC
Labels: (S3 - Duplicate)
