### ISSUE TITLE
Camp make crash.

### ISSUE THREAD

**Issue by GodPhase777** [CleverRaven/Cataclysm-DDA#43465] opened 2020-09-04 22:39 UTC
# Describe the bug

Game crashes when I try to remake a camp. I'm pretty sure this starts when you die in a world you have set to keep and respawn with an already made camp, glitching it to not exist but still have all the camp stuff there, dialogue and bulletin.

# Steps To Reproduce

1. I don't know how to trigger this glitch, i believe it happens when you die, and respawn in the same world with a camp set up.
2. Talk to npc near bulletin board..
3. Press k and ask what to do for camp
4. Try naming the camp.

# Expected behavior

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    DinoMod [DinoMod]
]

# Additional context

[Bayport.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5177202/Bayport.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5177203/crash.log)

**Comment by mlangsdorf** [comment] 2020-10-17 12:19
Could you please reproduce this on the latest experimental?  Because I can't.

**Comment by GodPhase777** [comment] 2020-10-18 10:06
I don't know how it happened, it may have just been random chance.

**Comment by mlangsdorf** [comment] 2020-10-30 20:05
Can't reproduce, closing.

**Closed by mlangsdorf** 2020-10-30 20:05 UTC
Labels: <Crash / Freeze>, Player Faction Base / Camp
