### ISSUE TITLE
Highscore

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23436] opened 2018-04-09 12:59 UTC
### Suggestion

How about adding a highscore list showing the best players?
It doesn't need to be fancy, a simple ranking based on the time you survived would be a good start.
Just show rank, player name and survival time in the list.

But to be fair, there need to be some rules:

 * There is no highscore for the freeform pool as this is just a sandbox
 * As soon you use ANYTHING in the debug menu (e.g. spawn item), you're disqualified from a highscore (well, for the current character, at least). This has to persist in the savegame, obviously
 * If any gameplay-related setting in the debug settings has a non-default value (e.g. maximum character points = 1000), you're disqualified, too

To avoid main menu clutter, the highscore list could go into the “Specials” menu.

There's just a “little” problem. The highscores are not really comparable because there is a ton of other things you can change. Mods may change gameplay considerably and also the world settings may make a game much easier.

One partial solution to this would be only worlds with default mods and world settings are eligible. I don't have a better idea right now.

If you have your own ideas, please share them!

**Comment by Leland** [comment] 2018-04-09 13:30
Duplicate of #4173. Please review that issue and add your notes there :)

**Closed by Leland** 2018-04-09 13:31 UTC
