### ISSUE TITLE
0.1x as long as normal crafting from mitigated proficiency

### ISSUE THREAD

**Issue by Cyprex** [CleverRaven/Cataclysm-DDA#46662] opened 2021-01-10 18:50 UTC
# Describe the bug

![Screenshot_20210110_004309](https://user-images.githubusercontent.com/35031555/104132043-18609e00-537b-11eb-8aeb-5b03da226b12.png)
Note how it claims this recipe will take 0.1x as long as normal. The unmodified time would be 30 minutes as per http://cdda-trunk.chezzo.com/pistol_stock/craft (bottom recipe) so it appears the proficiency requirement is not actually being mitigated.

# Steps To Reproduce

I don't know, I've been unable to reproduce it in a debug world where I spawned the book, set skills to 10 and had no NPC assisting me.

# Expected behavior

If the lack of proficiency is supposed to be mitigated here: 30m craft time and 1x modifiers.
If not: proper proficiency modifers being displayed.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-8687-ged7efb8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Note that this is with an NPC assisting me, though I'm not sure it's necessary to reproduce the bug.
I have 19% plastic working profiency, my NPC has 4%.
[Exprito.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5793138/Exprito.zip)

**Comment by Cyprex** [comment] 2021-01-11 13:38
Also happens on b11350

**Comment by chrispikula** [comment] 2021-02-26 03:34
I'm trying to make a simple new recipe, and I noticed this is a thing even when crafting on your own.  I think the 0.1x and 0.5x values seen above are just straight up divided by ten, as when I made a recipe with 5.0x and 20.0x values, it displayed .5x and 2.0x.  Possibly a display bug?  I was also requiring a Plastic Working proficiency, strangely enough.

Still no idea what is causing the mitigation in the first place.  I will note that it can show up with just dda enabled, as of 0.E-9855-gfa9b27e , build 11497

I will try spawning a few more random chars, but I overwrote the one it showed up on when running tests.

**Comment by Cyprex** [comment] 2021-03-01 11:27
Very possible, I haven't had time to debug it yet but the code looks correct to me, though from what I recall I couldn't tell if multiple copies of the same stack.

**Comment by eltank** [comment] 2021-04-26 06:47
To reproduce the situation described in the bug report, simply spawn in the "Boston AnimeCon magazine" on a freshly-minted debug character with the necessary skills and either a spawned copy of the recipe book "101 Crafts for Beginners" or learning all recipes via debug menu.

![pistol-stock-before](https://user-images.githubusercontent.com/8000047/116039924-36979480-a620-11eb-92ac-d904ec21c5c1.png)

This will be fixed by #48658
![pistol-stock-after](https://user-images.githubusercontent.com/8000047/116040103-6e9ed780-a620-11eb-8bed-ffae05bcd645.png)

**Comment by Evrze** [comment] 2021-05-20 22:35
I partially think this is intentional, done this way, the values should be pulled from base (1) rate of incurring failure, which should be the normal rate of success if you have the proficiencies and whatever the game pulls.

For some reason the time multiplier is removing a value of 1 from its display if it's simply just a multiplier, I'm not sure if it's trying to add this to the base time (1) of a craft to be a 1.1 value or 10% longer to craft. This could be because 1.1 means base time (1+1.1). 

This means it should be corrected as " x longer than normal".

The base rate to craft is base 1 of everything with no modifiers, so it is also your base success rate and such.

A ".5x more likely to incur failure" just means it's adding to the base rate of incurring failure to be base (1.5) to do calculations after being mitigated, or essentially making it 50% more difficult from the base recipe.

**Closed** 2021-05-30 04:33 UTC
Labels: Crafting / Construction / Recipes, Info / User Interface
