### ISSUE TITLE
Side bar redrawing issues

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21978] opened 2017-09-24 00:01 UTC
Game version: 6785

Operating system: windows

Tiles or curses:Tiles

Mods active:
  "dda",
  "no_npc_food",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "DinoMod",
  "crazy_cataclysm",
  "national_guard_camp",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "blazemod",
  "Tanks",
  "jury_rigged_robots",
  "nm_wpns",
  "No_Acid_Zombies",
  "more_classes_scenarios",
  "StatsThroughSkills"

### Expected behavior
![image](https://user-images.githubusercontent.com/15700895/30778050-a46eebb4-a090-11e7-95a6-f374c4a97857.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/15700895/30778047-832877a4-a090-11e7-9c84-85ed7f776618.png)

I have to change the side bar style and then change it back to refresh it.
### Steps to reproduce the behavior
Usually happens when I switch to a different program and come back. Not consistent though.

![image](https://user-images.githubusercontent.com/15700895/30778073-88d096d6-a091-11e7-989e-d596f0e13c3a.png)

**Comment by Theundyingcode** [comment] 2017-09-24 23:40
After further playing, the cause seems to be related to exiting vehicles or other things that remove or alter the sidebar.  Again, I haven't figured out how to do it consistently yet.

My guess is this is somehow cause by it missing the call to redraw the stats in the sidebar.  Switching the side bar style calls the redraw methods and fixing the problem.

Will update if I get it narrowed down farther.

**Comment by Leland** [comment] 2018-02-19 17:48
@Theundyingcode I'm closing this due to a lack of steps to reliably reproduce. If you _do_ manage to come up with those at any point, please do note them here and reopen.

**Closed by Leland** 2018-02-19 17:48 UTC
Labels: Bug, Confirmation Needed, Information / Interface
