### ISSUE TITLE
Game freezing (non-responsive) every time I load this save and walk towards this hunting lodge

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#59740] opened 2022-07-29 19:58 UTC
### Describe the bug

Pretty much the title. Walk east then north and you'll find a hunting lodge. But the CDDA becomes "not responding" before it fully comes into view. No error messages. 

### Steps to reproduce

1. Load the included save file. 
2. Walk a bit east then north, towards the L on the map for hunting lodge. 
3. Game freezes. 
4. ???
5. Profit!

### Expected behavior

It shouldn't freeze!

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: fac3512 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
[Silica.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9222877/Silica.zip)

**Comment by PatrikLundell** [comment] 2022-07-30 06:20
/confirmed

Ineptly trying to use the debugger, I get the impressing the code is stuck trying to spawn monsters. Someone competent is needed to figure out what's wrong.

**Comment by GoLoT** [comment] 2022-07-30 17:45
Seems to be related to #59281 
The update to the quantity after spawning from a nested group seems to be missing:

```diff
diff --git a/src/mongroup.cpp b/src/mongroup.cpp
index 575b3035df..3cd85d799a 100644
--- a/src/mongroup.cpp
+++ b/src/mongroup.cpp
@@ -209,6 +209,9 @@ std::vector<MonsterGroupResult> MonsterGroupManager::GetResultFromGroup(
                 if( found_in_subgroup ) {
                     //If spawned from a subgroup, we've already obtained that data
                     spawn_details = tmp_grp_list;
+                    if ( quantity ) {
+                        *quantity = tmp_qty;
+                    }
                 } else {
                     spawn_details.emplace_back( MonsterGroupResult( it->name, pack_size, it->data ) );
                     //And if a quantity pointer with remaining value was passed, will modify the external value as a si
```
The fix worked in my local tests but pinging @dseguin in case I'm missing something.

**Comment by dseguin** [comment] 2022-07-30 17:52
> The update to the quantity after spawning from a nested group seems to be missing: [...]

This might have been fixed with #59724

**Comment by GoLoT** [comment] 2022-07-30 18:01
You are totally right. Somehow I missed the related issue.

**Comment by Inglonias** [comment] 2022-07-31 15:27
Does that mean we can close this?

**Comment by ZhilkinSerg** [comment] 2022-08-22 11:01
Not reproducible anymore on latest game version using provided save.

**Closed by ZhilkinSerg** 2022-08-22 11:01 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), Monsters
