### ISSUE TITLE
Tank drone ignoring reprogramming

### ISSUE THREAD

**Issue by ArcanErasmus** [CleverRaven/Cataclysm-DDA#9338] opened 2014-09-30 14:54 UTC
When my character used a control laptop on a tank drone, it started attacking nearby zombies/wildlife, as expected. But, once it finished off those targets, it turned on me. But, it only used its flamethrower/taser, as if it only checks for player-friendliness on its long range weapons, but not on the close-range ones.

 I had backed up my save before doing this, so I can confirm that it was successfully reprogrammed. I also tried setting it on passive mode, but this just made it ignore other enemies and immediately pursue my character.

**Comment by kevingranade** [comment] 2015-01-06 06:10
Has this been addressed by the recent monster AI work?

**Comment by AlexTes** [comment] 2015-01-23 11:47
I take it thats work that hasn't been put into the latest experimental though?
I just nearly got flamed to death.

**Comment by KA101** [comment] 2015-01-23 23:13
Should have been in.  Anyone else?

**Comment by drbig** [comment] 2015-01-23 23:22
https://github.com/CleverRaven/Cataclysm-DDA/pull/9373 - my first contrib. At least *shouldn't* taze/*fry* the operator. What has happened?

**Comment by KA101** [comment] 2015-01-23 23:36
I don't know, but wil see if I can verify shortly.

**Comment by AlexTes** [comment] 2015-01-26 21:29
I just did some testing. Everything is fine. I thought short circuiting the drone without converting the drone made the laptop say there were no enemy drones in range, but it seems I was plain wrong, as I can't reproduce. I can retry to convert it just fine. So it was a combination of the drone being out of range of my laptop (range is extremely short for any wireless technology), me reading about the tazer/flame bug, and the drone being out of ammo / not firing for whatever reason for a bit, but frying me still.

Sorry guys!

**Closed** 2015-01-26 23:46 UTC
Labels: Bug, Confirmation Needed, Easy-fix
