### ISSUE TITLE
Crash：segmentation fault 0.D-10106

### ISSUE THREAD

**Issue by chushoubaobao** [CleverRaven/Cataclysm-DDA#36706] opened 2020-01-04 22:29 UTC
Game version:0.D-10106

Operating system: win10-64

Tiles or curses: tiles

Mods active: 

### Steps to reproduce the behavior： drop some items (I've tried rags and leathers) on a place  which already exist the same items

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4022585/crash.log)
CRASH LOG FILE: config/crash.log
VERSION: 0.D-10969-g202f0b8
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5DC235[cataclysm-tiles.exe+0x1DC235]
    @0x5DCD02[cataclysm-tiles.exe+0x1DCD02]
    SMPEG_error+0x4B034@0xFE91D0[cataclysm-tiles.exe+0xBE91D0]
    _C_specific_handler+0x98@0x7FFCDE7C8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFCE0FB477F[ntdll.dll+0xA477F]
    RtlWalkFrameChain+0x14BF@0x7FFCE0F14BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFCE0FB34EE[ntdll.dll+0xA34EE]
    @0x7CCEF0[cataclysm-tiles.exe+0x3CCEF0]
    @0x4483F0[cataclysm-tiles.exe+0x483F0]
    @0x44AB85[cataclysm-tiles.exe+0x4AB85]
    @0x45362C[cataclysm-tiles.exe+0x5362C]
    @0xCEB438[cataclysm-tiles.exe+0x8EB438]
    @0x6C451A[cataclysm-tiles.exe+0x2C451A]
    @0x70C7EC[cataclysm-tiles.exe+0x30C7EC]
    IMG_LoadWEBP_RW+0x64E46C@0x17294AC[cataclysm-tiles.exe+0x13294AC]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFCDE8B7974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFCE0F7A271[ntdll.dll+0x6A271]

**Comment by anothersimulacrum** [comment] 2020-01-04 22:53
Duplicate of #36666, this has already been fixed, please update.

**Comment by nullptr98** [comment] 2020-01-04 22:53
same as #36666 I think, should be fixed now, update ur game

**Closed** 2020-01-05 00:18 UTC
