### ISSUE TITLE
Segfault and strange, gamebreaking behavior from messing with outdated solar panels(?)

### ISSUE THREAD

**Issue by Dandy1096** [CleverRaven/Cataclysm-DDA#70287] opened 2023-12-18 19:03 UTC
### Describe the bug

I must have installed these solar panels atop on an old version, likely from July 2023. I don't update often. I have since tried to install some new ones, reposition some old ones, etc.
The game segmentation faults when attempting to uninstall a solar panel that, when examined, is labeled "power grid". Sometimes it lets me, sometimes it doesn't, but it's pretty consistent. Nothing interesting happens, just instantly throws an error and crashes.
Messing with the solar panels further, I found that sometimes the tiles get... moved in strange ways, pictured below.

### Attach save file

[Centertown - Pruned-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13707592/Centertown.-.Pruned-trimmed.tar.gz)

### Steps to reproduce

Segmentation Fault:
1. Load into save
2. Disconnect power connections from any solar panel which, when examined, is labeled "power grid" instead of "solar panel". There should be one immediately to the west when you load in.
3. Usually, messing with the power connections or uninstalling unrelated solar panels fixes the segfault.

Strange behavior:
1. If you do manage to uninstall the solar panel to the west, reinstall it. It moves the tiles around as pictured below.

### Expected behavior

I expect that installing or uninstalling solar panels wouldn't segfault or move tiles around strangely.

### Screenshots

These are screenshots of the "strange tile behavior"
![before](https://github.com/CleverRaven/Cataclysm-DDA/assets/87585076/5161b60b-579c-4ed2-a9d0-849f80455caf)
Reinstalling the solar panel... moves the tiles.
![after](https://github.com/CleverRaven/Cataclysm-DDA/assets/87585076/247153fe-f078-4537-bdb6-8cb48a07bc09)
The segfault is not very interesting, visually.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b37cb38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]
Worth noting is that a lot of these solar panels were **installed on a much earlier version. Some as early as 2023-07-20-0251 ( 520db0c).**
I believe I installed StatsThroughSkills after world creation.

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13707541/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13707542/debug.log)

**Comment by Kamayana** [comment] 2023-12-18 19:49
Duplicate of #67971, but it's always good to have more saves for it, this bug has been around a little while.

**Comment by Dandy1096** [comment] 2023-12-18 20:42
Good to know, though I'm sure the strange non-segfault behavior is worth investigating as well.
Is there a way I can fix the panels in my save?

**Comment by Kamayana** [comment] 2023-12-18 20:57
I don't know of a bandaid fix, unfortunately, I haven't been able to really dig down into the issue.

**Comment by Dandy1096** [comment] 2023-12-19 21:03
Two more things have cropped up:
Mucking about with the power connections allows me to disconnect the solar panels, smashing the affected panels causes strange disappearing behavior in nearby tiles, and apparently I managed to `G`rab drag some of them. I wish I had a save or video file to demonstrate this.

**Closed** 2024-03-26 08:45 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Appliance/Power Grid
