### ISSUE TITLE
Buying container with content is cheaper than buying only the content 

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#49160] opened 2021-06-03 15:45 UTC
# Describe the bug

In the trade menu, items in containers are listed twice. Once themselves, once as the content of the container. Buying container is cheaper than buying items alone.

# Steps To Reproduce

Find NPC who sells items in a container (spawn and sell packaged jerky?)
Observe the bugged price

# Expected behavior

Buying items with container cost more than buying only the items

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/120672652-ca1b7b00-c492-11eb-94e4-255c16684776.png)
![image](https://user-images.githubusercontent.com/26396019/120672658-cb4ca800-c492-11eb-828b-f4f4cb201250.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 418b45d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Already reported once in #46626 but was closed by @BrettDong, I guess they misread the issue since their comment was unrelated to what was written but I didn't particularly care to reopen this again until today saw this bug again.

**Comment by Psiclops** [comment] 2021-06-04 05:42
Your screenshots do not support your theory. In both of those cases, the container plus the contents costs more than just the contents. 
cheese (8) $1.03
plastic bag with cheese  $7.40

3L jar with tomatos $10.67
tomatoes $0.94

**Comment by Salty-Panda** [comment] 2021-06-04 07:15
You forgot to multiply the values

**Comment by big-smitty** [comment] 2021-06-07 15:29
Yeah on the first screenshot its $1.03 for one cheese, so should be $8.24 for 8 cheeses. 
But the whole container and all the cheese is $7.40, so I think salty-panda is right

**Comment by actual-nh** [comment] 2021-06-07 17:52
@emomicrowave: Would #48922 help with this?

**Comment by big-smitty** [comment] 2021-06-07 18:33
> @emomicrowave: Would #48922 help with this?

No that was pushed on the 18th, problem is persistent on experimental 38074ba, released the 25th

**Comment by emomicrowave** [comment] 2021-06-07 20:32
> No that was pushed on the 18th, problem is persistent on experimental 38074ba, released the 25th

Do experimentals include umerged pull requests? I don't think so.

But anyway, you're right that it doesn't work. My code just adds a check to disallow selling items out of sealed containers. Did some testing and when you examine the items in your inventory, the price is calculated correctly:

- `canned tomato (11)` - Barter value **$0.50** each = **$5.50**
- `3L glass jar` - Barter value **$0.10**
- `3L glass jar > canned tomatoes` - Barter value **$5.60**

So it seems the problem is when the trading value is calculated when you start the trade. So probably incorrectly modifying price based on reputation or something. I will check it out.

**Comment by kierandavidmccormick** [comment] 2022-07-07 07:44
Could not reproduce in the latest experimental [`6502158`](https://github.com/CleverRaven/Cataclysm-DDA/commit/6502158053ce194bde1bd8a4889538e316e13d17). Testing with a variety of items (expensive, cheap, food, non-food) at both high and low skill levels at both the refugee center and exodii, I could not reproduce a discrepancy in price greater than one cent per item. This may have been fixed in [#57660](https://github.com/CleverRaven/Cataclysm-DDA/pull/57660), or some other fix to trading between when this was opened and now.

**Comment by anothersimulacrum** [comment] 2022-07-07 14:09
If someone can reproduce, comment and I will reopen.

**Closed by anothersimulacrum** 2022-07-07 14:09 UTC
Labels: <Bug>, NPC / Factions, <Exploit>, Items / Item Actions / Item Qualities, Items: Containers
