### ISSUE TITLE
3D vision lets you see unseen tiles below

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#66040] opened 2023-06-06 17:50 UTC
### Describe the bug

It seems the newly added 3D vision (#65738) does not take the visibility of tiles below into account, letting you see what is below even if the tiles cannot be seen from the player character's position.

Pinging @Rewryte as the author of the change.

### Attach save file

N/A

### Steps to reproduce

1. Turn 3D fov on
2. Go into look around mode and look from z-levels above
3. Notice that the tiles not seen on the current z-level can be seen from above

### Expected behavior

Unseen tiles are hidden and map memory is displayed instead if available

### Screenshots

Unseen tiles in the current z-level:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/11890223/b5da3a40-cf24-422b-bd18-704f92cefe4b)

The tiles are visible from two z-levels above:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/11890223/4f2ecd68-d6b6-416f-b4df-01f13d874e07)

### Versions and configuration

bd8b8abd02b4d4d0022dd048e706344e884e4789

**Comment by Rewryte** [comment] 2023-06-06 18:33
Thanks, I'll take a look.

**Comment by SurFlurer** [comment] 2023-06-07 00:33
It's the problem that you cannot see the terrain below a furniture, which will be addressed by #65794

**Comment by Qrox** [comment] 2023-06-07 02:28
> It's the problem that you cannot see the terrain below a furniture, which will be addressed by https://github.com/CleverRaven/Cataclysm-DDA/pull/65954

Oh, I was not talking about that tile though, but the entire memorized but unseen area around it being visible from above.

**Comment by SurFlurer** [comment] 2023-06-07 02:40
Oh,sorry, I misunderstood.

**Comment by Rewryte** [comment] 2023-06-07 07:03
Looks like "looking around" gives players better visibility on higher z-levels.  3D vision inherits this when drawing lower z-levels.  We could calculate visibility for every z-level, but that might be computationally expensive and should have minimal benefit outside of "looking around".  I'll try to think an alternative.

**Comment by Qrox** [comment] 2023-06-07 12:29
The same happens when you are on a roof two z-levels above ground where you can see the unseen ground tiles near the walls even outside of look around mode.

**Comment by SurFlurer** [comment] 2023-06-08 13:28
Is #65205 related?

**Comment by NetSysFire** [comment] 2023-08-07 16:06
@Qrox Can you still reproduce? This looks like the kind of issue that might still be valid.

**Comment by Qrox** [comment] 2023-08-08 01:36
I haven't seen any PR that may fix this issue. Since the fix is likely non-trivial it's unlikely I missed it either.

**Comment by Rewryte** [comment] 2023-09-01 17:28
Made some progress on this by modifying how the visibility cache is updated and retrieved.  Just a rough sketch at the moment but results are promising so far.  I'll likely have a fix ready soon.  Will still have to see about the performance impact though.

**Closed** 2023-09-13 03:07 UTC
Labels: <Bug>, Z-levels, [C++], Help Wanted
