### ISSUE TITLE
diagonal vehicle tile isn't impassable

### ISSUE THREAD

**Issue by JaxMutt** [CleverRaven/Cataclysm-DDA#70049] opened 2023-12-07 16:20 UTC
### Describe the bug

When driving diagonal and the new feature that an extra vehicle tile is added to prevent entering or leaving the vehicle isn't working, and the extra tile doesn't have the flag "impassable"

### Attach save file

[Hope Mills - Copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13602485/Hope.Mills.-.Copy-trimmed.tar.gz)

### Steps to reproduce

2. Get in the vehicle and face a diagonal direction to create the extra vehicle tile
3. Step into the extra tile that was created (will not have "impassable" flag when inspected)

### Expected behavior

Extra tile should have the flag "impassable" to prevent anyone from walking through it.

### Screenshots

![Screenshot (2)](https://github.com/CleverRaven/Cataclysm-DDA/assets/74649816/8d973ecf-c831-4e87-84e4-97ecdefde22c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 456f0f1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment] 2023-12-08 10:04
/confirmed The (aisle) curtain breaks the logic and I haven't tried to debug it

**Comment by Voideka** [comment] 2023-12-09 08:45
Curtains in general seem to do it. I don't have any aisle curtains but all my windshields/doors have curtains and I have the problem.

**Comment by irwiss** [comment] 2024-05-13 10:48
Seems to be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/73574
You will now open the door before being able to step on the fake door tile

**Closed** 2024-05-13 11:57 UTC
Labels: (S2 - Confirmed), Vehicles, [C++]
