### ISSUE TITLE
Creating world using Chinese character failed

### ISSUE THREAD

**Issue by CKRainbow** [CleverRaven/Cataclysm-DDA#51239] opened 2021-08-30 14:22 UTC
### Describe the bug

When I try to create a world named by chinese, it show a error message "Failed to write world data to .save/(garbled characters)/worldoptions.json": opfile failed
And the previous save using chinese will be turn into garbled characters too.
Also saving a template character using Chinese will throw errors.

### Steps To Reproduce

just create a world using a Chinese name

### Expected behavior

Can use Chinese normally

### Versions and configuration

-----------------------------------------
22:12:52.506 : Starting log.
22:12:52.506 INFO : Cataclysm DDA version 5aff6c2
22:12:52.522 INFO : [main] C locale set to C
22:12:52.523 INFO : [main] C++ locale set to C
22:12:52.523 INFO : SDL version used during compile is 2.0.14
22:12:52.523 INFO : SDL version used during linking and in runtime is 2.0.14
22:12:52.620 WARNING : opendir [./sound/] failed with "No such process".
22:12:52.629 INFO : Number of render drivers on your system: 5
22:12:52.629 INFO : Render driver: 0/direct3d
22:12:52.629 INFO : Render driver: 1/direct3d11
22:12:52.629 INFO : Render driver: 2/opengl
22:12:52.629 INFO : Render driver: 3/opengles2
22:12:52.629 INFO : Render driver: 4/software
22:12:52.764 INFO : [options] C locale set to C
22:12:52.764 INFO : [options] C++ locale set to C
22:12:52.764 INFO : Setting language to: 'zh_CN'
22:12:52.765 INFO : Language is set to: 'zh_CN'
22:12:52.765 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:12:52.765 INFO : [translations] C++ locale set to C
22:12:52.936 INFO : Active renderer: 1/direct3d11
22:12:53.812 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
22:12:53.826 INFO : Setting language to: 'zh_CN'
22:12:53.826 INFO : Language is set to: 'zh_CN'
22:12:53.826 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:12:53.826 INFO : [translations] C++ locale set to C
22:13:25.708 INFO : [options] C locale set to C
22:13:25.708 INFO : [options] C++ locale set to C
22:13:25.708 INFO : Setting language to: 'en'
22:13:25.708 INFO : Language is set to: 'en'
22:13:25.708 INFO : [translations] C locale set to Chinese (Simplified)_China.1252
22:13:25.708 INFO : [translations] C++ locale set to C
22:13:51.516 WARNING : opendir [./save/000/mods] failed with "No such process".
22:20:10.473 WARNING : opendir [./save/111/mods] failed with "No such process".

**Comment by ZhilkinSerg** [comment] 2021-08-30 15:33
Duplicate of #51204

**Closed** 2021-09-03 05:35 UTC
Labels: <Bug>, Translation, OS: Windows
