### ISSUE TITLE
Error popup when opening Hands category in armor crafting

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42912] opened 2020-08-14 08:33 UTC
# Describe the bug
Game throws error popup on Hands category in armor crafting.

# Steps To Reproduce
Open craft window, select armor and hands category, get error.

# Expected behavior
No error.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 
- Game Version: 0.E-4997-gaf19ae1 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Mutation Changes [Mutation_Changes],
    Blaze Industries [blazeindustries],
    Расширение К.Р.И.Т. [crt_expansion],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Без ж/д станций [No_Rail_Stations],
    Графическая карта [Graphical_Overmap]
]

# Additional context
 DEBUG    : invalid body part id "HANDS"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 408

**Comment by Fris0uman** [comment] 2020-08-14 09:02
Will probably  be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/42876 , that or it's caused by the Mutation_Changes mod, which is thrid party and we have no control over it.

**Comment by casswedson** [comment] 2020-08-14 15:52
`more_survivor_stuff` is the cause of the error, most third party mods that add mutations and/or clothing are not compatible with recent builds.

**Comment by anothersimulacrum** [comment] 2020-08-14 16:13
Closing as due to a third party mod issue.

**Closed by anothersimulacrum** 2020-08-14 16:13 UTC
Labels: (S4 - Invalid)
