### ISSUE TITLE
Bridge (re)generation is bugged

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#42037] opened 2020-07-11 17:31 UTC
# Describe the bug

When you find bridges that were made in previous version (when bridges were single-level), they sometimes are bugged. In short, something is not generated - either some ramps or parts of z+1 level of a bridge. See screenshots.

# Steps To Reproduce

load [save](https://drive.google.com/file/d/1uGiuaZmYRcz3Qci0dbY9n-9NYZ_5-t77/view?usp=sharing), look at the bridge. Try crossing it, preferably on vehicle. Fail horribly.

# Expected behavior

Well, if there is a migration for old saves, it should make traversable bridges. That's the whole point of it, right?

# Screenshots

![cataclysm-tiles_2020_07_11_11_02_42_785](https://user-images.githubusercontent.com/56833396/87229927-7adddf00-c3d6-11ea-88d9-291e1018af5c.png)
![cataclysm-tiles_2020_07_11_11_02_15_355](https://user-images.githubusercontent.com/56833396/87229931-7f09fc80-c3d6-11ea-925c-ffff07cb7b36.png)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3964-g237b16e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ZhilkinSerg** [comment] 2020-07-11 18:54
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/41987

**Closed by ZhilkinSerg** 2020-07-11 18:54 UTC
