### ISSUE TITLE
The android build of `cdda-experimental-2024-08-25-0446` can't start

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#75935] opened 2024-08-25 08:53 UTC
### Describe the bug

The android build in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-08-25-0446 cannot run.

### Attach save file

N/A

### Steps to reproduce

1. Install the android build of https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-08-25-0446
2. run the android build
3. crash

### Expected behavior

It not crashing

### Versions and configuration

- OS: Android 13
- Game Version: 5237214

### Additional context

[crash.log](https://github.com/user-attachments/files/16739547/crash.log)
[debug.log](https://github.com/user-attachments/files/16739548/debug.log)

**Comment by harakka** [comment] 2024-08-25 08:57
Likely the same issue as underlying #75818

**Comment by harakka** [comment] 2024-08-25 09:02
This seems like a regression caused by #75920

**Comment by alef** [comment] 2024-08-25 10:07
Try #75937 for invalid fonts. Not sure it is related to #75818 for the language selector.

**Comment by gettingusedto** [comment] 2024-08-26 06:49
Updated my android build to the current experimental that has #75937, the game did infact stops crashing on game start.

**Comment by harakka** [comment] 2024-08-26 07:45
Fixed by #75937

**Closed by harakka** 2024-08-26 07:45 UTC
Labels: (S1 - Need confirmation)
