### ISSUE TITLE
Vehicle Welding bug - Oxy not allowed in menu, is allowed in actual action

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16723] opened 2016-05-16 23:57 UTC
If you try to add a weldable vehicle part holding the oxy_torch but not a welder it says you don't have a welder

But if you are holding a welder and an oxy torch on the following menu the oxy_torch is a valid welding tool to use charges from.

I tried to track it down but I'm not sure where the bugs are.  If you can tell me the files and give an example of how it should be I'm willing to go though and build the PR for this.

**Comment by Xpyder** [comment] 2016-05-16 23:58
note: I'm using a build from 4/26, so if this has already been fixed feel free to disregard.

**Comment by Shudokai** [comment] 2016-05-17 04:16
The same happens in the experimental of 5/17. Welders, Makeshift Welders and the Ace Torches dont work at all unless there is some duct tape nearby or in your inventory, ace torches also will not work for cutting metal doors if the welding goggles are in your inventory, they will work if the goggles are on the floor.

**Comment by illi-kun** [comment] 2016-05-17 07:12
A duplicate of #16651.

**Closed by illi-kun** 2016-05-17 07:12 UTC
Labels: Bug
