### ISSUE TITLE
Aiming With Light Amplification Error

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13681] opened 2015-09-29 11:40 UTC
From 4b8c3de

In total darkness, while wearing Light Amplification Goggles and using a ranged weapon to aim at monsters through "f", using "." to increase steadiness for long enough for the monster to move a tile (I suspect) causes the increased vision field provided by the goggles to reduce to normal 3x3 in-the-dark vision, thus no longer allowing you to see the monster or surroundings, and canceling the aim process.
##

**Comment by Midaychi** [comment] 2015-09-29 22:46
Are you using tiles mode? This might be more due to lighting in tiles mode being super wonky.

**Comment by Headjack** [comment] 2015-09-30 04:53
I'm in regular ASCII mode. It's probably related to how you need to take a step after activating the goggles for the graphics to change into visibility.

**Comment by Oskar636** [comment] 2016-11-10 20:24
Cannot reproduce in build 5864 windows 64bit tiles. But I don't quite understand what this issue states.

**Comment by kolsurma** [comment] 2017-03-20 16:31
Could not reproduce:
v 0.C.21751
Windows 10
Tiles / ASCII

**Comment by Coolthulhu** [comment] 2017-04-14 04:16
Should be fixed now as visual code changed a lot since the bug was last reproduced.

**Closed by Coolthulhu** 2017-04-14 04:16 UTC
Labels: Bug, Confirmation Needed, Information / Interface
