### ISSUE TITLE
Any kind of creature is able to block a vehicle no matter vehicle's power

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23578] opened 2018-04-23 10:00 UTC
Game version: 0.C in general

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
A vehicle surrounded by creatures is able to push back and possibly ride over them depending on its power, mass and when measured against mass and strength of opposing creatures.

### Actual behavior
Most if not all vehicles, including heavy, relatively powerful and sizeable military ones can easily be stopped even by small animals and zombie children if vehicle speed is low. The power to bump and push creatures back is dependant merely on vehicle speed, not the mass nor engine power (nor player character strength for muscle-powered vehicles).

### Steps to reproduce the behavior
Let group of animals/weaker zombies surround stationary vehicle with the player character in. Activate the vehicle and attempt to push the creatures back. Fail miserably.

**Comment by FulcrumA** [comment] 2018-04-23 10:35
Referencing #19854 as it's related, although not taking certain things into account for this particular problem.

**Comment by Isaacssv552** [comment] 2018-04-23 23:07
This could probably be fixed in the short term by auto-smashing creatures if the vehicle's mass is >100x the creature's mass. Just add a special case with "The <creature_name> is crushed beneath your <vehicle_name>."

**Comment by CoroNaut** [comment] 2018-05-03 04:32
The large engine and vehicle overhaul that mugling did a while ago fixed this but it was reverted because it wasnt fully completed when it was merged, is it possible to fix the problems with it and remerge it?

**Comment by kevingranade** [comment] 2018-05-03 16:26
No, it broke fundamental things about the vehicle system like the fact that
fuel consumption is based on engine work, not vehicle speed.

If you can find out what it specifically did to address the problem we can
look into applying just that.

**Comment by Epictyphlosion** [comment] 2019-01-10 17:08
I believe I've had this happen to me before when messing around with the debug menu. This definitely needs to be fixed

**Comment by NetSysFire** [comment] 2021-11-19 02:00
I believe this might be fixed already, can anyone of you confirm? I spawned a military cargo truck and surrounded it with zombie children and I can move forward and crush them at just 6 km/h.

**Comment by NetSysFire** [comment] 2022-01-05 10:43
Closing this because it appears to be fixed. Reopen if you can still reproduce the issue.

**Closed by NetSysFire** 2022-01-05 10:43 UTC
Labels: Game: Balance, Vehicles, Monsters
