### ISSUE TITLE
SCAR-H/8x40 stick magazines don't accept charges

### ISSUE THREAD

**Issue by Ikmachek** [CleverRaven/Cataclysm-DDA#41245] opened 2020-06-12 13:53 UTC
# Describe the bug
Trying to load a game where the player's reality bubble has a loaded SCAR-H or 8x40 10-round Rivitech mag returns an error about it having charges but not accepting any. Additionally any guns within that reality bubble will lose their attachments.

# Steps To Reproduce
>Make a new world
>Wish yourself a SCAR-H Magazine and SCAR-H, along with maybe a forward grip or something
>Attach the forward grip, load the gun, hit Shift-S
>Reload save, get loading error about the scarhmag not being able to accept charges
>Ignore or move past the error, your SCAR now lost it's forward grip, along with any other guns in your reality bubble.

# Expected behavior
The game to load without an error report and your guns to remain modded.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.E-3104-g67830ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Additional context
I made my own crack at trying to solve this looking at the .308 magazine Json file, nothing stands out that makes me think why this is a thing, I'm baffled.

**Comment by anothersimulacrum** [comment] 2020-06-12 19:28
Seems to be a duplicate of #41084

**Closed by anothersimulacrum** 2020-06-12 19:28 UTC
Labels: (S3 - Duplicate)
