### ISSUE TITLE
Reloading bug regarding shotguns

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#30684] opened 2019-05-20 10:04 UTC
# Describe the bug

When reloading a shotgun with a single shot and unloading it, the display on the shotgun shows [shotgun name]\(2) instead of [shotgun]0. The shotgun acts as if it has no ammo and requires reloading, but the ammo disappears in the process. This occurs even if the shotgun is not being wielded. In addition, reloading the shotgun bypasses the "r"eload menu even when another item in the inventory (I tested a battery cell with a cell phone) is able to be reloaded.

# Steps To Reproduce

1. Spawn a Remington 870 and 00 shot.
2. Reload the shotgun and then unload it.
2a. Unload a cell phone first, spawn a fresh shotgun and some 00 shot, and press "r" for reload.

# Expected behavior

That reloading shotguns isn't screwed up.

# Screenshots

![image](https://user-images.githubusercontent.com/42950339/58013043-a69f5680-7aaa-11e9-814e-2ccf2da6363b.png)

# Versions and configuration

OS: Windows 10
Game version: 0.D-3181-g339945f
Graphics version: Tiles
Mods loaded: probably irrelevant.

**Comment by dom4op** [comment] 2019-05-20 12:59
Same here. The issue appeared somewhere around build 9000.

**Comment by dom4op** [comment] 2019-05-21 08:38
Shotgun issue wasn't fixed by #30696. Can we re-open this? Or should I post a new issue?

**Comment by dom4op** [comment] 2019-05-21 18:20
Thank you. I'll drop my savegame here, hope it helps.
In my inventory you can see 2 shotguns, both of which are bugged.
![Sprite-0002](https://user-images.githubusercontent.com/49651777/58120350-bd11f300-7c0d-11e9-82fd-6fe1f7a147a2.jpg)
It's stated they have 8 shots (not 8/8, mind you - just 8, which is a bug in its own right). In fact they are empty. Loading/unloading shotgun doesn't help. It just shows random number (not always 8) and it's always wrong.

DIfficult to explain... I just want my emty shotgun to show "0/8" like it used to.
[Highgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3203908/Highgate.zip)

I play with a personal mini-mod, but the game should load without it just fine. Dropping in case you really need it:
[Grimwulf_mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3203913/Grimwulf_mod.zip)

**Comment by dom4op** [comment] 2019-05-25 07:53
Apparently, this bug was fixed after all. Found some new shotguns, all of them work as intended. 

Got rid of the bugged shotguns. My guess that items that were already broken in previous version won't be fixed, but freshly obtained ones won't be broken. We can close the issue now.

**Closed** 2019-05-25 17:10 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
