### ISSUE TITLE
"Contact Us" Option on Evac Computer causes game to hang

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#44224] opened 2020-09-17 11:39 UTC
# Describe the bug

Using option 3 "Contact Us" on the evac shelter computer often causes the game to lockup entirely until the task is ended manually.

# Steps To Reproduce

1.Load attached save.
2. Interact with adjacent computer.
3. Select option 3.
4. Observe hang.

# Expected behavior

It should show the path to the refugee center or just the refugee center location if a path can't be found without the game freezing up.

# Screenshots

# Versions and configuration

[Spring Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5238811/Spring.Creek.zip)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5988-gb8bbd5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-09-17 12:07
Duplicate of #43457

**Closed by ZhilkinSerg** 2020-09-17 12:07 UTC
