### ISSUE TITLE
Cyrillic symbols are not supported in fixedsys.ttf

### ISSUE THREAD

**Issue by poxu** [CleverRaven/Cataclysm-DDA#14814] opened 2016-01-12 14:12 UTC
And in other out of the box fonts maybe. That makes it impossible to play the game without messing with technical stuff.

**Comment by SeanMirrsen** [comment] 2016-01-12 18:07
It may be a good idea to make some kind of launcher app for Cata, which would allow setting the font and - most importantly - previewing the way the game looks and reads via using the same glyph rendering method to quickly alternate through available system fonts.

On Russian OSes, the Russian language is selected by default, but the provided terminus and fixedsys fonts do not have support for cyrillics. Likewise on Korean OSes the fonts can't display the hieroglyphics or whatever the korean language symbols are properly called. However, *built-in system fonts* do have that support.

In that regard... I'm thinking.
How about a "system first" load order for fonts? You can always name a font something new and put it into the fonts folder if you want an override, but, say, the Arial font on any Windows OS is probably going to have support for the language that OS is in.
What if we set the default font to something that is common in various OS versions, and comes with language support for those versions? Probably not Arial, definitely not Comic Sans, but even Terminal or System could work well. And, if the system does not have those fonts? (Say, it's Linux) - Well in that case, there will be a copy in the game's own Fonts folder. So that **if** the system has its own locale-appropriate copy of the font the game will use it, but **if it** ***doesn't***, the game will use the one in its directory - *or* a "failsafe default" if even that is not there.

**Comment by Zireael07** [comment] 2016-01-12 19:12
@SeanMirrsen, have you seen the Windows launcher that @remyroy made?

**Comment by remyroy** [comment] 2016-01-12 19:15
> It may be a good idea to make some kind of launcher app for Cata, which would allow setting the font and - most importantly - previewing the way the game looks and reads via using the same glyph rendering method to quickly alternate through available system fonts.

I have plan to include something like that in my launcher.

**Comment by illi-kun** [comment] 2016-01-12 22:59
That's probably a duplicate of #10155.

**Comment by poxu** [comment] 2016-01-13 08:32
@illi-kun 
Yes, that sure is

**Comment by SeanMirrsen** [comment] 2016-01-13 08:43
I am vaguely aware of there being a launcher, but seeing as it's not part of the game distribution I hardly ever come into contact with it.

That aside, how about that "system first" load order for fonts? Surely it would fix the problem handily?

**Comment by poxu** [comment] 2016-01-13 09:06
@SeanMirrsen Maybe adding a font, which supports cyrillic symbols to the distribution is easier from end-user point of view? No need to think which font the game actually uses, no need to read manuals on changing font to non-system.

**Comment by SeanMirrsen** [comment] 2016-01-13 09:25
It would be easier if it were only the cyrillic fonts. Korean users have the same problem. We see them pop into IRC for help periodically. And Korean and Cyrillic script support both in one font could be rather hard to find.

**Comment by poxu** [comment] 2016-01-13 09:36
@SeanMirrsen I mean maybe several fonts could be added and then some code could be written to select the appropriate font, depending on the locale.

**Comment by SeanMirrsen** [comment] 2016-01-13 09:46
It would probably be easier to just change load order. I mean, it'd require no work for the end-user at all. The game would try to pull a specified system font, and would use the game's own fallback font if it didn't find it.

**Comment by poxu** [comment] 2016-01-13 17:34
@SeanMirrsen Yes, that's true. I just think, that distribution can provide fonts better suited for gameplay.

**Comment by BrettDong** [comment] 2017-01-06 15:35
One option is to include a font for each supported language in the game distribution package, and the program loads that font according to the language of the OS. And then we make the font an option, and if the player dislikes the provided font, he/she may change the font according to his/her preference. IIRC there's no Chinese TTF font in Linux(some available Chinese fonts in Linux are all in OTF format), so the player must manually copy a TTF font from Windows and edit `config/fonts.json` to load it, which is pretty difficult for a common player without much technical knowledge.

**Comment by patternoia** [comment] 2017-01-06 16:22
GNU Unifont (https://en.m.wikipedia.org/wiki/GNU_Unifont) covers the whole UTF-16 table afaik and supports all the scripts we have in the project. It has a TTF variant as well available at http://unifoundry.com/unifont.html. 
In my opinion it is a good candidate for inclusion into the project and I use it in my WIP iOS port.

**Comment by BrettDong** [comment] 2017-01-07 02:21
Unifont is a nice solution. English, French, German, Italian, Spanish, Simplified/Traditional Chinese, Korean, Japanese and Russian works fine. But Unifont is a GPLv3 project, do we have to follow GPLv3?

**Comment by kevingranade** [comment] 2017-01-07 04:59
Simply distributing gpl3 works along with differently licensed works is
fine.

**Comment by AMurkin** [comment] 2017-04-11 07:20
Unifond is added and its support cyrillic symbols.

**Comment by Leland** [comment] 2017-05-04 03:44
Should be fixed by #19965

**Closed by Leland** 2017-05-04 03:44 UTC
Labels: Other, Translation
