### ISSUE TITLE
Boil anyways

### ISSUE THREAD

**Issue by Cool3303** [CleverRaven/Cataclysm-DDA#26457] opened 2018-10-30 19:51 UTC
**Describe the bug** 
Boiling water requires 
1. A tool able to boil water
2.An item with containing quality and liquid storage (a mess kit for example only has containing)
3.A container that has water
4.Another (empty) container that can hold water.

Effectively this forces a player to carry atleast one superfluous container. 
A simple fix would be to enable an option to skip the check as the player is able to drink the boiling hot water or dump it on the ground instantly anyways.

**Comment by kevingranade** [comment] 2018-10-30 20:23
Duplicate of #171

**Closed by kevingranade** 2018-10-30 20:23 UTC
Labels: (S3 - Duplicate), <Enhancement / Feature>, Crafting / Construction / Recipes, Food / Vitamins, Game: Mechanics Change, [C++]
