### ISSUE TITLE
Item that have a charge does duplicated by pickup action.

### ISSUE THREAD

**Issue by Ezsk** [CleverRaven/Cataclysm-DDA#34302] opened 2019-09-28 14:46 UTC
# Describe the bug
Item duplicate by pickup menu.
This will not happen in advanced inventory management.

# Steps To Reproduce
1. Drop 1000 amount charcoal on the floor.
2. use (e) key and examine the floor.
3. use (m) key and pickup only 500 of charcoals.
    system notification says "Not enough capacity to stash charcoal (500)"
    then choose "w wield charcoal (500)"
4. Check your inventory and see 1000 of charcoal in the weapon held slot. not 500.
5. There are 500 charcoal remaining on the floor.
6. drop 1000 charcoals from your hands.
7. Charcoal has increased to 1500 overall.

# Expected behavior
I am not sure what cause those results but, The pickup amount need to be correct.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8007-g5915b0e (#9685)
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by ipcyborg** [comment] 2019-09-28 18:46
Looks like a duplicate of #33646.
Should be fixed by #34297.

**Closed** 2019-11-07 06:24 UTC
Labels: (S2 - Confirmed), <Bug>
