### ISSUE TITLE
Talon UGVs shooting though reinforced glass w/o breaking it

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#42985] opened 2020-08-17 10:31 UTC
# Describe the bug

Subj. Shots go through the glass as if it wasn't there.

# Steps To Reproduce

Spawn r-glass barrier, survivor on one side and talon ugv on the other, let it shoot at you, see what happens.

# Expected behavior

Either it should stop bullets or it should break. Maybe stop a number of bullets before breaking?

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-5059-g10b2315 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Bulletfang** [comment] 2020-08-17 13:56
The player can also shoot through these glasses, the damage dealt from both, player and turrets, is severely reduced though. And 2 reinforced glasses will stop bullets completely. I thought this was intended since reinforced glass isn't bulletproof glass, but it won't shatter easily even if you punch holes through it.

**Comment by anothersimulacrum** [comment] 2020-08-17 15:08
Duplicate of #33374

**Closed by anothersimulacrum** 2020-08-17 15:08 UTC
Labels: (S3 - Duplicate)
