### ISSUE TITLE
Butchering / Dissection error

### ISSUE THREAD

**Issue by 7illian** [CleverRaven/Cataclysm-DDA#31914] opened 2019-06-27 11:00 UTC
# Describe the bug

Butchering / Dissecting a corpse sometimes does not 'complete' after the time for the task has passed. A message appears that reads "There is no corpse to butcher'', while the corpse or dissection the butchery was attempted on remains intact.

# Steps To Reproduce

Simply butcher or dissect a corpse. It is unclear what causes it fail sometimes. 

# Expected behavior

For it to work. 

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-5018-gb8698af [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    Magiclysm [magiclysm]
]

**Comment by roaringjohn** [comment] 2019-06-27 11:07
Build #9229 is going to fix this.

**Comment by eilaattwood** [comment] 2019-06-27 11:23
Duplicate of #31840

**Comment by ifreund** [comment] 2019-06-27 11:27
Dupe and already fixed by 31873

**Closed by ifreund** 2019-06-27 11:27 UTC
