### ISSUE TITLE
Horses follow down stairs and can't get back up

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36371] opened 2019-12-23 08:46 UTC
# Describe the bug
Horses will follow you down stairs and get stuck there when they won't follow you back up.

# Steps To Reproduce
1. Spawn a horse and tame it
2. While it's following you walk down the stairs into an LMOE shelter
3. Go back up the stairs

# Expected behavior
Horses can go both ways on stairs or neither but not only one.

# Versions and configuration
- OS: Linux
    - OS Version: Kernel 5.4.5-arch1-1
- Game Version: 0.D-10619-g46c0151 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons]
]

**Comment by Zourin2** [comment] 2019-12-24 06:38
This is true of most tamed animals. I've had dogs get stuck in basements quite often and I have to keep my critters clear of any stairwells

**Comment by Ramza13** [comment] 2020-02-05 17:19
This looks like a duplicate of #35665

**Closed** 2020-02-09 06:22 UTC
Labels: (P3 - Medium), (S2 - Confirmed), <Bug>, Monsters
