### ISSUE TITLE
Autopickup doesn't pick up from inside corpse pockets

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#54124] opened 2022-01-07 02:46 UTC
### Describe the bug

Autopickup doesn't pick up from inside corpse pockets

### Steps to reproduce

Set autopickup rules
Turn autopickup on
Murder zombies 
Note that you don't pickup the items on the corpse 

### Expected behavior

Autopickup to automatically pickup

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment] 2022-01-07 05:17
Seems like a dupe of #53425.

**Closed** 2022-01-07 15:55 UTC
Labels: (S1 - Need confirmation), Mechanics: Character / Player, Items: Containers
