### ISSUE TITLE
Moving item causes intermittent error message

### ISSUE THREAD

**Issue by Tatterdemalian** [CleverRaven/Cataclysm-DDA#28293] opened 2019-02-20 23:07 UTC
**Describe the bug**  
Occasionally, when transferring items using either the basic or advanced inventory screens, an error will pop up:

src/item_location.cpp:601 [void item_location::remove_item()] item location does not point to valid item

**To Reproduce**  
No reliable way to reproduce, it occurs infrequently when transferring any item, and there doesn't seem to be any pattern regarding exactly which item. Has occured while wielding a rock, a makeshift crowbar, and fists/nothing at all.

**Expected behavior**  
Item moves to designated target location EDIT: without an error message.

**Versions and configuration:**
 - OS: Linux 4.13 Gentoo
 - Game Version: 0.C-37533-g66698e5054
 - Graphics version: Tiles
 - Mods loaded: Defaults only: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Additional context**  
Debug.log attached.
[CDDADebug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2886846/CDDADebug.log)
EDIT: Note that, although game::wield() shows up in the log, I was not attempting to wield or drop any wielded item when the errors occurred. Something in the inventory management code may be calling game::wield() with an invalid pointer.
EDIT: Also worth mentioning, the bug does not seem to clone or destroy any items, being either wielded or transferred. Its only effect on gameplay so far seems to be the error message.

**Comment by Trokinos** [comment] 2019-02-20 23:36
I got the same error with an expendable baton on everytime i try to wield it actually 

src/item_location.cpp:601 [void item_location::remove_item()] item location does not point to valid item

I can wield it after pressing space on the error message though, but it happens all the time with this baton.

**Comment by Tatterdemalian** [comment] 2019-02-20 23:57
> I got the same error with an expendable baton on everytime i try to wield it actually on 0.c 37535 g409acf7
> 
> src/item_location.cpp:601 [void item_location::remove_item()] item location does not point to valid item
> 
> I can wield it after pressing space on the error message though, but it happens all the time with this baton.

There was another issue that mentioned this error, where I actually originally posted this issue, thinking it may be related: #28281 
It's related to wielding, while mine is simply inventory movement, but they may all be part of something in item management that broke in a really odd way.

**Comment by ifreund** [comment] 2019-02-21 00:41
From the debug log it looks like this *is* caused by the changes I made to `game::wield()`. In that case this should be fixed by #28276 as well.

**Comment by Tatterdemalian** [comment] 2019-02-21 05:12
As of build 0.C-37535-g409acf797d, the error is no longer intermittent. It now happens consistently whenever I attempt to wield anything from my inventory.

*Steps to reproduce*
1. Open wield menu.
2. Select item from first column in menu (player inventory).
3. If an item is already being wielded, select what to do with it from the dialog that appears.

Tested several times with various combinations of wielding. The error seems to occur when an item is moved to or from the player inventory by the wield action. It does NOT occur when:

- An item is wielded from the floor when the player is not wielding any item.
- The item selected for the wield command is the item currently being wielded, AND the option to drop the item or wear it is selected from the "Stop wielding {item}" dialog. Selecting the "Store in inventory" option DOES cause the error.
- An item is wielded from the floor, when another item is being wielded, and the "Drop item" or "Wear item" options are chosen from the "Stop wielding {item}" dialog.

It does occur when an item is wielded directly from the worn inventory, but not when an item being wielded is worn, which seems to indicate that there is a step where an item being wielded is moved from the worn inventory to the carried inventory when it's wielded, but moved directly to the worn inventory when it's un-wielded.

**Comment by kevingranade** [comment] 2019-02-21 08:28
Fixed by #28276

**Closed by kevingranade** 2019-02-21 08:28 UTC
Labels: <Bug>, Inventory / AIM / Zones
