### ISSUE TITLE
player_morale::stylish is inconsistent

### ISSUE THREAD

**Issue by githubuser343** [CleverRaven/Cataclysm-DDA#38951] opened 2020-03-22 20:05 UTC
# Describe the bug

Load game, receive the following error message

DEBUG    : player_morale::stylish is inconsistent.

 FUNCTION : bool player_morale::consistent_with(const player_morale&) const
 FILE     : src/morale.cpp
 LINE     : 643

# Steps To Reproduce

1. Start a new game with a "ball dancer" profession character with stylish trait
2. Save and load the game
3. Pass time and receive this error

# Expected behavior

Not receive an error every time I load a game.

# Versions and configuration

Latest experimental as of this post with no mods.

# Additional context

Error only occurs once, immediately after passing time after game loads. Ignoring it doesn't seem to cause any problems, everything behaves as it should to my knowledge.

**Comment by wapcaplet** [comment] 2020-03-22 23:00
Confirmed, I can reproduce this by creating a new character with the "Stylish" trait, and nothing else special. Save, load, get error message. Here is my save game:

[StylishSave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4366508/StylishSave.zip)

This came up in #38611 as well but I couldn't reproduce it until I followed your steps - thanks for reporting it. This issue might be considered a duplicate of that one (since several possibly "inconsistent" traits are handled in the same way).


- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-13345-g3b74c13638 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Closed** 2020-03-26 07:09 UTC
Labels: <Bug>
