### ISSUE TITLE
Game crashed when trying to reload tileset by button

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#53360] opened 2021-12-11 11:09 UTC
### Describe the bug

Game crashed when trying to reload tileset by button.

### Steps to reproduce

1. Bind a button to 'reload tileset' function (F12 in my case)
2. Press button in game

### Expected behavior

I expected that current tilesets will be reloaded.

### Screenshots

![image](https://user-images.githubusercontent.com/6676374/145674281-f7570adf-fbac-4301-9fa6-d5b839962519.png)

### Versions and configuration

OS: Windows 10 x64
Game Version: 57f6550
Graphics version: tiles (Ultica + Smap)
Ingame languge: English
Mods: none

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7696855/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7696856/debug.log)

**Comment by ZhilkinSerg** [comment] 2021-12-11 13:56
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/53138

**Closed** 2021-12-11 13:56 UTC
