### ISSUE TITLE
jacqueshammer in en-us

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15981] opened 2016-03-29 22:30 UTC
Found a jacqueshammer next to other jackhammers in megastore. Assuming this isn't a family guy reference since the description is also french.

![before](https://cloud.githubusercontent.com/assets/646121/14125952/cb71ac1c-f5c2-11e5-97dc-03b303ec365f.png)

**Comment by illi-kun** [comment] 2016-03-29 23:17
You got reference correctly.

**Comment by illi-kun** [comment] 2016-03-29 23:21
Duplicate of #988, #1811, #13241...

**Comment by codemime** [comment] 2016-03-29 23:47
I dug the repository a bit. The jacqueshammer is a fossil which was hard-coded a long time ago (before the JSON era). May be it was here from the very beginning (I dunno, it's too deep) and it's The Family Guy referencing it, not vice versa. Therefore it's under the Protection of UNESCO.

**Comment by lucianposton** [comment] 2016-03-29 23:58
May I suggest changing the description to the local language, and insert into the description a subtle reference. Otherwise it just looks like a i18n error.

**Comment by lucianposton** [comment] 2016-03-30 00:01
For example,

> At first glance, this appears to be a jackhammer, but it is in fact a jacqueshammer. oh-hoh-hoh-hoh-hoh-hoh!

**Comment by codemime** [comment] 2016-03-30 00:19
I agree. It doesn't seem to be a very funny joke. If it was reported so many times, then probably something has to be done about that. But it's not my call.

**Comment by Rivet-the-Zombie** [comment] 2016-03-30 01:06
[Line 2273 of ````tools.json````](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tools.json#L2273) - ````"id": "jacqueshammer", "//": "All of this is SUPPOSED to be in French.",````

**Comment by kevingranade** [comment] 2016-03-30 01:28
Just because people report something a large number of times doesn't make
it a bug.  I'd be behind moving a number of "silly" items like this (and
the granade, some monsters, etc) to a "crazy cataclysm" mod, but I'm
against removing it.

**Closed** 2016-03-30 06:10 UTC

**Comment by Cyrano7** [comment] 2016-03-30 18:20
Well if there was a poll i'd vote for it being removed. I like having some jokes and things but this is quite silly.

**Comment by illi-kun** [comment] 2016-03-30 18:51
> Well if there was a poll i'd vote for it being removed

Ha, that's not how project managment works.

The only way you can affect the decision is to show really strong arguments, not simple voting.

**Comment by Cyrano7** [comment] 2016-03-30 19:09
@illi-kun Its move about stating my opinion and showing that there is support for others arguments. It's just an American way of speaking i'm not actually asking for a poll. I'm not insisting that it be removed i'm stating that its quite silly and i'm fine with removing it.

**Comment by illi-kun** [comment] 2016-03-30 19:30
@Cyrano7 I just trying to say that simple statement "I think it should be done in this way" is not good argument (no offense).

**Comment by kevingranade** [comment] 2016-03-31 16:01
Agreed, it doesn't matter whether you call it a vote or not, simply stating
your support for a change is irrelevant.

**Comment by chaosvolt** [comment] 2016-04-02 19:09
Giving feedback and popular support for a proposed change is irrelevant. Certainly explains a lot.

I only poked my head back on Github due to asking something of MShock, and I'm rather amused to see the exact same recurring "herpderp is this a bug?" issues occur yet again. And seeing the same attitudes as usual.

**Comment by lucianposton** [comment] 2016-04-02 19:13
We don't do customer-obession around these here parts!

**Comment by kevingranade** [comment] 2016-04-03 08:57
Customer obsession means understanding the customer and giving them what
they need, which isn't necessarily what they ask for, especially based on a
vote by an arbitrary subset of them.

**Comment by lucianposton** [comment] 2016-04-03 10:42
It's more about a dedication to exceeding customer expectations than meeting needs. But my comment was in jest, hence the wording, if that wasn't clear. :)
