### ISSUE TITLE
windows key crashes game

### ISSUE THREAD

**Issue by KalleSteinbach** [CleverRaven/Cataclysm-DDA#36749] opened 2020-01-06 12:54 UTC
# Describe the bug

if you are in the game and press the windows key (in fullscreen mode) the game will crash if you re enter. sometimes only the map or everything flickers.

# Steps To Reproduce

1. enter fullscreen mode
2. press the windows key and go out of the game
3. click on the game and wait for the game to crash/bug out

# Expected behavior

don't crash when I want to use my browser or media player in between

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11046-gb0160b4 (tiles)
 - Graphics version: Tiles
 - Mods loaded: disable npc needs, simplified nutrition

[Grayville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4026058/Grayville.zip)
[config_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4026055/config_2.zip)

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-01-06 15:28
Duplicate of #24528

**Closed by ZhilkinSerg** 2020-01-06 15:28 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Controls / Input

**Comment by ZhilkinSerg** [comment] 2020-01-06 15:31
Try using a different renderer and/or non-fullscreen mode (window borderless/maximed window) until the issue is resolved.
