### ISSUE TITLE
Error messages while reloading liquid containers.

### ISSUE THREAD

**Issue by ZehCastro** [CleverRaven/Cataclysm-DDA#37296] opened 2020-01-22 03:44 UTC
# Describe the bug

Two error messages when trying to "reload" a hydration pack. See Images 1 and 2 further below.
 ```
DEBUG    : cannot determine reload cost as antibiotic is neither ammo or magazine
 
 FUNCTION : int player::item_reload_cost(const item&, const item&, long int) const
 FILE     : src/player.cpp
 LINE     : 8221
```
And:

```
 DEBUG    : Tried to reload liquid container with non-liquid.
 
 FUNCTION : bool item::reload(player&, item_location, long int)
 FILE     : src/item.cpp
 LINE     : 5758
```

# Steps To Reproduce

Steps to reproduce the behavior in the attached save:
1. Try to " reload" the hydration pack being worn, either thru the 'r'eload or 'i'nventory examine and 'r'eload.

# Expected behavior

A refill screen for me to select available liquids or some sort of message explaining why I can't do that and no error messages. That is expected because it is usually how this system works as seem in "Image 3" below.

# Screenshots
Image 1:
![image](https://user-images.githubusercontent.com/1457644/72862300-73513f00-3cab-11ea-8cdf-95ceee849016.png)

Image 2:
![image](https://user-images.githubusercontent.com/1457644/72862487-17d38100-3cac-11ea-9d46-3fbdfc8ebcb1.png)

Image 3:
![image](https://user-images.githubusercontent.com/1457644/72862964-b2808f80-3cad-11ea-98a1-be3c634066da.png)

# Versions and configuration

The info menu described below was not present:
"Main menu (ESC) > Debug Menu > Info > Generate game report"

 - OS: Windows 10
 - Game Version: 0.D-8574-Win64-Tiles from the [releases](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/0.D/cataclysmdda-0.D-8574-Win64-Tiles.zip)
 - Graphics version: Tiles
 - Mods loaded: Default mods

# Additional context

Image 3, showing the menu working, was taken after dropping every worn or carried items but keeping the hydration pack.

Zipped save:
[Post Falls.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4095159/Post.Falls.zip)

**Comment by ZehCastro** [comment] 2020-01-22 03:48
In the attached save, if you try the other liquid containers, you get the same error.

**Comment by wapcaplet** [comment] 2021-02-19 23:21
Cannot reproduce in 0.E-9737-g511ddcb179 with the save attached to the original report. I can select several available liquids when `r`eloading the hydration pack:

![image](https://user-images.githubusercontent.com/238395/108571829-41574580-72ce-11eb-9b2b-35c315bedd01.png)

Also works in a new game:

![image](https://user-images.githubusercontent.com/238395/108571731-140a9780-72ce-11eb-9614-fe5e9fd93f3a.png)

Guessing this was resolved by nested container changes since the bug was opened.

**Closed by wapcaplet** 2021-02-19 23:21 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
