### ISSUE TITLE
Rural Gas Station (Last Delivery) spawns 00 shot with Generic Guns on.

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#40408] opened 2020-05-10 05:10 UTC
# Describe the bug

The rural Gas Station from Generic Guns spawns 00 shot even when Generic Guns is on.
# Steps To Reproduce

1.Create a new world with Generic Guns.
2.Start with the Last Delivery scenario.
3.Go into the gas station back room.
4.Pick up shotgun and shotgun ammo.
5.Miserably fail at loading shotgun shells into the shotgun.
6.(optional) Debug in the correct shells and burn the 00 shot.

# Expected behavior

The 00 shot shells are replaced with the generic "shotshell, buckshot", and they load properly into the shotgun, as does every piece of ammo spawned when Generic Guns is on.
# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10614
 - Graphics version: Terminal
 -Ingame language: English
- Mods loaded: [e.g.dda, generic_guns, no_fungals, No Rail Stations]
# Additional context

**Comment by tenmillimaster** [comment] 2020-07-03 16:45
Confirmed. 
![image](https://user-images.githubusercontent.com/7764202/86487010-9126d380-bd22-11ea-8d8c-15583e66d061.png)

This should have been fixed in #37803; it is happening because migrations aren't applying to these mapgen spawns again.

If you save and reload, migrations should handle it, but this is rather annoying.

**Comment by mqrause** [comment] 2020-09-02 22:51
The migration seems to be applied only to "place_loot", not to "place_item" or "place_items".

**Closed** 2020-11-15 08:07 UTC
Labels: <Bug>, Items: Ammo, Mods: Generic Guns, Spawn, [C++]
