### ISSUE TITLE
Sealed containers found only partially full

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#45650] opened 2020-11-26 19:02 UTC
# Describe the bug

Several of the `(sealed)` containers found in houses are only partially full.

# Steps To Reproduce

1. Loot the refrigerator and cabinets of a house
2. Look for "sealed" containers that aren't full

# Expected behavior

Being `(sealed)` implies the container is unopened from the factory, and thus full. Any partly-empty container should not be `(sealed)`.

# Screenshots

Ammonia (gallon jug), 0.88 of 3.75 L:
![image](https://user-images.githubusercontent.com/238395/100385035-cc31e800-2fde-11eb-985e-17f2eaea49b6.png)

Bleach (gallon jug), 1.63 of 3.75 L:
![image](https://user-images.githubusercontent.com/238395/100385140-0ac7a280-2fdf-11eb-9735-f08acba8c57f.png)

Horseradish (glass jar), 0.2 of 0.5 L:
![image](https://user-images.githubusercontent.com/238395/100385050-d18f3280-2fde-11eb-96c4-02af9dbefdfb.png)

Fruit jam (3L glass jar), 0.6 of 3.0 L:
![image](https://user-images.githubusercontent.com/238395/100385055-d358f600-2fde-11eb-947b-bab97d1d9ba9.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7871-gdf17a62d10 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by aoae23** [comment] 2020-11-27 08:16
I've noticed this before in earlier versions. I had thought it was intended since people rarely keep full containers of food in their fridges without eating some of the contents.

**Comment by thomasrwisneski** [comment] 2020-11-28 01:01
It appears any items spawned in a container that has a "sealed_data" value will default to being sealed unless explicitly unsealed. For instance, here is an entry for milk within a fridge item-group:
`{ "item": "milk", "charges-min": 1, "prob": 94, "container-item": "jug_plastic", "sealed": false }`
Since it has the "sealed": false attribute, milk within fridges does not suffer from this issue. On the other hand, we have bleach within a under-sink item-group:
`{ "item": "bleach", "prob": 75, "charges-min": 1 }`
It does suffer from this issue, defaulting to being sealed, even though like milk it is contained in a gallon jug.

The obvious fix would be adding the unsealed attributes for all items like this. However, this still leaves us with a problem. What if we want to have a full, sealed gallon of milk? It looks like somebody tried to solve this problem for ketchup and mustard. Within the fridge item group, we see:
`{ "group": "ketchup_sealed_rng", "prob": 20 }`
Here is the definition of the "ketchup_sealed_rng" item-group:
'''
"entries": [
      { "item": "ketchup", "prob": 6, "charges-min": 1 },
      { "item": "ketchup", "prob": 1, "charges": 32, "container-item": "condiment_bottle_sealed" }
    ]
'''
It appears that somebody wanted to solve this issue by defining a chance to have a full, sealed ketchup bottle when this group is used. Unfortunately it suffers from the same lack of the unsealed attribute discussed above,  so it will be sealed regardless. We could easily fix the code to:
'''"entries": [
      { "item": "ketchup", "prob": 6, "charges-min": 1, "container-item": "jug_plastic", "sealed": false },
      { "item": "ketchup", "prob": 1, "charges": 32, "container-item": "condiment_bottle_sealed" }
    ]
'''
which should result in expected behavior.

Ultimately this brings about the question of how we should be handling these potentially full/sealed or partially-full/unsealed items... going through and adding a group equivalent to "ketchup_sealed_rng" for every kind of these items seems like a poor solution. I'll keep looking into this and thinking about what might be a better way (or maybe this has already been discussed!)

**Comment by Raikiri** [comment] 2020-12-09 06:51
It's also annoying that you can't immediately see how much liquid there is in a sealed container when looking at it.

**Comment by wapcaplet** [comment] 2020-12-26 00:40
Still occurring in 0.E-8388-gb85c4a930b

**Comment by actual-nh** [comment] 2020-12-26 01:08
Should sealed default to "true" if the container is full, and "false" otherwise?

**Comment by wapcaplet** [comment] 2020-12-26 04:04
> Should sealed default to "true" if the container is full, and "false" otherwise?

That makes sense to me and would be a good solution.

**Comment by RoyBerube** [comment] 2020-12-27 01:58
I think I have a fix for this with some caveats. It works by disallowing sealing a container on spawn if it could hold any more contents. Testing in previously unexplored areas looks promising with only full containers spawning sealed.

The drawback is that any existing items spawned with a seal when they should be unsealed are not fixed by this. It would be nice to fix a save on loading but I'm not sure how to do it, or if it is even possible.

**Comment by RoyBerube** [comment] 2020-12-27 08:04
I'm working on a fix for this. It simply disallows sealing a container if it is not full when spawned. Will do more testing to make sure it is not too blunt of an application of the rule.

The drawback is that it does not fix items that are already spawned and so does not fix them on load either. Is this acceptable?

**Comment by RoyBerube** [comment] 2020-12-27 15:52
I'll answer my own question after sleeping on it - we can't alter existing sealed items because some of them may have been crafted. Crafting allows sealing without being a full container.

**Closed** 2020-12-27 22:06 UTC
Labels: <Bug>, Items: Containers, Spawn
