### ISSUE TITLE
can not remove Bionic installed

### ISSUE THREAD

**Issue by afeizh** [CleverRaven/Cataclysm-DDA#44948] opened 2020-10-19 09:30 UTC
in the Cataclysm DDA version 0.E-7006-gf322301，when i tried to remove Bionic installed via autodoc, Bionic installed drops, and i'm told "invalid json_flags  id 'IN_CBM'"

![error_msg](https://user-images.githubusercontent.com/22028805/96428755-b89e9f00-1232-11eb-8539-3337228373f7.JPG)

![error_msg2](https://user-images.githubusercontent.com/22028805/96429929-18e21080-1234-11eb-8772-10f7f42602fd.JPG)

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5400663/debug.zip)

**Comment by Fris0uman** [comment] 2020-10-19 12:21
duplicate of #44156

**Closed** 2020-10-19 13:13 UTC
