### ISSUE TITLE
CDDA minimizes in Windows even though in borderless window

### ISSUE THREAD

**Issue by VictoriaStudios** [CleverRaven/Cataclysm-DDA#62573] opened 2022-12-04 23:49 UTC
### Is your feature request related to a problem? Please describe.

CDDA is definitely a game where I have the wiki and the item browser open on my second monitor at all times. Usually, running a game in borderless window mode makes it NOT minimize when you click outside of the program... however, this is not the case with CDDA. Because a normal window totally breaks any sort of immersion, I'd like the windows build to work as a borderless window should.

### Solution you would like.

A borderless window mode that deserves the name and does not minimize when focus switches from the application.

**Comment by andrei8l** [comment] 2022-12-05 04:46
That was done on purpose to fix some Windows-specific issues: #50360.

**Comment by Qrox** [comment] 2022-12-05 04:51
I would say even in fullscreen mode the game window should not minimize when clicking in a second monitor, so this is probably more of a multi-monitor issue than a window mode issue.

**Comment by ZhilkinSerg** [comment] 2022-12-05 11:26
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56484

**Closed by ZhilkinSerg** 2022-12-05 11:26 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>
