### ISSUE TITLE
Solar Suitcase bugs on deploy und duplicates on take down

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#74444] opened 2024-06-11 01:37 UTC
### Describe the bug

The solar suitcase item produces this error when you activate and place it.

The resulting panel seems to be working just fine though.

However, when you take down the array, you get back not only a solar suitcase item, but also a deployed solar suitcase item, both which you can then again deploy, so this dupes the solar arrays. 

### Attach save file

[Mason County-trimmed.tar.gz](https://github.com/user-attachments/files/15780880/Mason.County-trimmed.tar.gz)

### Steps to reproduce

In the provided save I am standing on a roof next to some deployed arrays, some of them are from the solar suitcase (the 2 righternmost ones). 

### Expected behavior

They should not generate errors and should not duplicate.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1060874/20035412-8a54-4267-a0e8-f536272f29a1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-06-2047 daea5c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

**Comment by Brambor** [comment] 2024-06-11 07:57
This is probably duplicate of
 - #73976

**Closed** 2024-06-11 09:58 UTC
Labels: (S1 - Need confirmation)
