### ISSUE TITLE
Funnel does not refill vehicle tanks with water

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#19667] opened 2016-12-07 06:03 UTC
using version 6021, and it does not work. in middle of rain, on a vehicle with funnel, and on same time is a 20l tank that is empty, and it does not fill at all, with funnel also constructed on same tile as tank, the tanks that can hold any kind of liquid, and i tried filling it with some water too see if the funnel will add to tanks already with some water, but still it does not work. it is water from pond, and is not clean, so it should "merge" with rain water, which is same type of liquid, right? but it does not work. any file i can put up to help fix , please let me know.

**Comment by Tharn** [comment] 2016-12-07 06:26
It works for me, using a metal funnel and a 60L tank on the same vehicle tile.

**Comment by keyspace** [comment] 2016-12-07 09:33
There is a PR in the works that _might_ be relevant: #19629 

@321nick Does the vehicle also have solar panels?..

**Comment by articulateSPLINE** [comment] 2016-12-08 02:51
Doesn't seem to be present in 6024.

Created a new world with no mods on Win 8.1, spawned in a car chassis and all the funnels/tanks I could find. Forced rain. Tested each tank (2, 10, 20 and 60L) individually with a regular funnel, all work as expected. Installed a solar panel, tanks still filled... though I'm not sure why that's a question as solar panels and funnels can't be installed on the same tile. Emptied the 60L and seeded it with some spawned dirty water, again, tanks fill.

My only guess is that you weren't waiting long enough - a regular funnel took a few hours of waiting to fill 2% of a 60L tank.

**Comment by 321nick** [comment] 2016-12-08 03:52
alright, maybe it is just me. i am using blazes vehicle mod, and i do have solar panels, maybe its something im doing wrong.

**Comment by keyspace** [comment] 2016-12-11 11:20
Can't reproduce with 0.C-20191-g21cd417 (21cd417, latest ATM).

Tested with only `blazemod` enabled, otherwise defaults. 60L vehicle tank fills with water when `funnel` is installed over it. (No difference if vehicle also has solar panels.)

**Comment by codemime** [comment] 2016-12-11 11:47
Closed as unconfirmed. Thanks, @keyspace.

If this bug nonetheless occurs, please report it here.

**Closed by codemime** 2016-12-11 11:47 UTC
Labels: Bug, Confirmation Needed, Vehicle
