### ISSUE TITLE
Crash when interacting with dead zombie

### ISSUE THREAD

**Issue by levstk** [CleverRaven/Cataclysm-DDA#34404] opened 2019-10-02 19:42 UTC
# Describe the bug

When I smash, try to butcher or even just enter the same tile as a zombie corpse the game crashes. Sometimes it doesn't fail on the first interaction.

# Steps To Reproduce

1. Kill a zombie.
2. Attempt to smash, butcher, walk into the same space as the corpse, etc.
3. Segfault.

# Expected behavior

The game shouldn't crash when performing routine tasks.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8159-g6363709 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [ Dark Days Ahead [dda] ]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3683051/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3683052/debug.log)

[North Salem.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3683058/North.Salem.zip)

**Comment by scanevaro** [comment] 2019-10-02 20:07
It happens when stepping on blood too.
Build 9702

**Comment by ZhilkinSerg** [comment] 2019-10-02 20:29
Duplicate of #34397

**Closed by ZhilkinSerg** 2019-10-02 20:29 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
