### ISSUE TITLE
Starting a camp places the bulletin board in random spot

### ISSUE THREAD

**Issue by davidpwbrown** [CleverRaven/Cataclysm-DDA#29211] opened 2019-04-01 23:02 UTC
**Describe the bug**  
After the recent UI updates, the terrain that is drawn is wider as it is drawn under the removable sidebar.
This has the knock-on effect of changing how the editmap() functions work.
editmap() required a padding based on terrain window widths/height.
creating a camp calls editmap() to place the bulletin board, and it now places it in some weird places, sometimes.

**To Reproduce**  
1. start a camp.
2. observe where the bulletin board is placed, sometimes nearby, sometimes off-screen.

**Expected behavior**  
Bulletin board is placed adjacent to player, or very near.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: latest master
 - Graphics version: Either
 - Mods loaded: dda

**Additional context**  
N/A

**Comment by mlangsdorf** [comment] 2019-09-06 12:42
Is this still a bug, @davidpwbrown?  Camp bulletin boards are place via mapgen_update functions.

**Comment by mlangsdorf** [comment] 2019-09-14 02:36
Closing, I can't reproduce and we don't use editmap in faction camps anymore anyway.

**Closed by mlangsdorf** 2019-09-14 02:36 UTC
Labels: <Bug>, Fields / Furniture / Terrain / Traps, Info / User Interface
