### ISSUE TITLE
Unable to generate a valid starting location in a radius of 3 overmaps.

### ISSUE THREAD

**Issue by Drafting-Goblin** [CleverRaven/Cataclysm-DDA#45218] opened 2020-11-03 05:20 UTC
# Describe the bug

I'm playing the latest experimental build with the 'The Last Delivery' scenario and the Survivor profession. I chose the Gas Station starting location.

# Steps To Reproduce

1. Make a world with these settings (please see attached screen shot).
2. Pick the same scenario as I did (The Last Deliver).
3. Pick Gas Station as starting area.

# Expected behavior

I expected the game to generate a map.

# Screenshots

![cdda](https://user-images.githubusercontent.com/73050654/97951750-39988300-1d69-11eb-8f1c-be4c07c3ef3a.PNG)
![cdda 2](https://user-images.githubusercontent.com/73050654/97951763-44531800-1d69-11eb-986c-dca926c7679e.PNG)

[Mount Croghan.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5479375/Mount.Croghan.zip)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
 -->

# Additional context

This is kind of a weird thing. The game didn't crash, it just wouldn't let me start and displayed the message asking me to report this. As such, I cannot provide a crashlog or anything. If there is any additional information I can provide just let me know. I've attached my world save incase that is helpful.

**Comment by Night-Pryanik** [comment] 2020-11-03 05:56
Duplicate of #35376.

**Closed by Night-Pryanik** 2020-11-03 05:56 UTC
