### ISSUE TITLE
Aluminum cans not filling with water

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42298] opened 2020-07-20 10:21 UTC
Empty Aluminum cans do not register as a container for pouring water into. Ones with contents already in them then drank from till empty will register as a valid container, but upon selecting it when trying to fill a container an error message is received.

 DEBUG    : tried to put an item (water) in a container (can_drink) that cannot contain it

 FUNCTION : int item::fill_with(const itype&, int)
 FILE     : src/item.cpp
 LINE     : 8486

# Steps To Reproduce

1.Find an empty aluminum can and try to fill it with water
2.Find an aluminum can that is full, drink the contents, then repeat step 1

Aluminum Cans should be able to hold water? Even if we have to set them down after filling multiple since they can't be resealed.

Build 10854
No mods

**Comment by KorGgenT** [comment] 2020-07-21 05:10
cans spill when opened, so i suppose the bug is that it lets you try and spits out a debug message.

**Comment by NotHereCDDA** [comment] 2020-07-21 05:30
The water also vanishes after the error message. I don't see why an open can can't hold water?

**Comment by DialoMalison** [comment] 2020-07-21 06:38
According to JSON_INFO.MD open containers are supposed to spill when placed inside another item. This makes sense. However, if the container is wielded or sitting on a flat surface (like a table or counter), they should be able to hold liquids.

**Comment by NotHereCDDA** [comment] 2020-07-21 06:42
That was essentialy what i was saying. Thankyou for putting it in such terms.

**Comment by KorGgenT** [comment] 2020-08-11 05:06
I am closing this as "not a bug" at least related to the title.

**Comment by NotHereCDDA** [comment] 2020-08-11 16:24
> I am closing this as "not a bug" at least related to the title.

How should i title it then? Because i can't use aluminum cans to pour water into at all without the error and that seems buggy plus the water vanishing isn't normal. (At time of reporting. Unsure if any changes fixed it.)

**Comment by KorGgenT** [comment] 2020-08-11 23:45
I'm human so i could totally be wrong. all i did was read the PR to the best of my ability because i didn't have an hour to compile and try to reproduce exactly what was going on, and i noticed that the comments didn't really line up very well with the issue body. I've been going through issues and adding them to release blockers and i didn't think "you can't put water in an aluminum can in your backpack" sounded like a bug. please let me know if i interpreted this incorrectly.

**Comment by NotHereCDDA** [comment] 2020-08-11 23:54
Yea no this just won't let me try to put the water into the can at all. I FULLY agree that it should spill in bags. I didn't think it would take a compile just to test?

**Comment by mqrause** [comment] 2020-08-18 23:30
Is this still a thing? I can't reproduce it in current master. Aluminum cans inside a container can't be selected to be filled and wielded cans or cans on the ground can be filled.

**Comment by wapcaplet** [comment] 2020-08-23 20:53
Tested in master 2d68329042 from August 22, and the behavior of aluminum cans is as I would expect.

In my inventory are 2 aluminum cans - one is wielded, one is not:
![image](https://user-images.githubusercontent.com/238395/90988443-05763a00-e550-11ea-95bc-1077ac413790.png)

I also have an aluminum can on the floor at my feet:

![image](https://user-images.githubusercontent.com/238395/90988474-3b1b2300-e550-11ea-9dd9-1dd8f6a8788f.png)

When I `e`xamine a toilet, I can use the water to fill the can I am wielding, or the can on the floor, but *not* the can in my inventory:

![image](https://user-images.githubusercontent.com/238395/90988485-525a1080-e550-11ea-99a9-0501ced879b4.png)

**Closed** 2020-08-26 05:04 UTC
Labels: <Bug>
