### ISSUE TITLE
Making the throwing skill more useful.

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#24444] opened 2018-07-23 15:09 UTC
Most combat skills seem to have their endgame weapons (nodachi, warhammer, etc.). The best throwing weapon I can think of is the throwing axe which doesn't quite measure up to those.

Are there any plans to make the skill more useful?

**Comment by Nerezza** [comment] 2018-07-23 15:52
Ironically there's also an issue still open about throwing being _too_ good (https://github.com/CleverRaven/Cataclysm-DDA/issues/20414).

The skill is already plenty useful (and actually overpowered) if you can figure out how to level it up, but there's good reason that archery overtook it in history.

**Comment by DracoGriffin** [comment] 2018-07-23 19:10
I believe you can diamondize throwing axes / knives. I'd have to double-check on how it works again with stacks, but at least that's something to consider.

**Comment by Shodan14** [comment] 2018-07-23 19:44
> I believe you can diamondize throwing axes / knives. I'd have to double-check on how it works again with stacks, but at least that's something to consider.

That would be good to know. You could add wooden and metal boomerangs, with a chance to return when you miss. Not sure if we're missing any other practical thrown weapons.

**Comment by kevingranade** [comment] 2018-07-23 21:10
Pretty sure the highest damage throwing weapons are going to be.... well hand grenades actually, but if its passive/reusable throwing weapons I'm pretty sure it's going to be some kind of spear.

If you have suggestions we can consider them, but otherwise I'm going to close this since were not going to make up weapons to use.

**Comment by Shodan14** [comment] 2018-07-23 21:20
No suggestions stats-wise, but good to hear that it's still in the cards.

**Comment by Lorith** [comment] 2018-07-25 19:03
Currently throwing is in the odd position of both being overpowered and underpowered at the same time -- throwing weapons tend to be incredibly weak, while throwing lumps of metal is insanely powerful.  I haven't looked at the code, but from what I have seen ingame, it appears the weight, volume, and maybe bash damage are all that count for throwing, as knives seem no better than sticks.

My suggestion would be to tie throwing to stamina with larger and heavier items costing more to throw, then have some kind of check of volume vs throwing skill to apply melee weapon strike damage plus a bonus, perhaps giving a higher chance for something like a spear, aiming to make throwing knives fairly easy but throwing axes or swords difficult to land a solid hit with.  The combination of the two should lead to higher damage with actual throwing weapons, and make throwing chunks of metal too tiring to use as a primary weapon like currently.

Not sure what kind of numbers would be good to balance it with, but it is an idea I've been thinking might work for a while.

**Comment by kevingranade** [comment] 2018-07-27 17:06
Throwing is OP in early game (has it's own issue) and tapers off in utility in late game (which is working as intended).

**Closed by kevingranade** 2018-07-27 17:06 UTC
Labels: Effects / Skills / Stats, Game: Balance, Ranged
