### ISSUE TITLE
Change to MRE display was ill-considered

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#52722] opened 2021-11-09 12:19 UTC
### Describe the bug

The "new" way MREs are displayed in the game world is not very conducive to play, and presents a significant amount of information overload. I put "new" in quotation marks because I cannot remember when this change was introduced. See the screenshot section for specifics.

### Steps To Reproduce

1. Acquire an MRE, by whichever means necessary. (Starting with the National Guard profession is a good way.)
2. Open your inventory.

### Expected behavior

I really don't like the new item definition for the MRE, and I think that going back to the old way would be better from an information-load perspective.

### Screenshots

MRE display in-game in version db097c5 as reported by the debug log. ![image](https://user-images.githubusercontent.com/13796683/140918755-852c3802-bef8-4364-b95a-824b081ca1c0.png)

Compare to the MRE display in-game in version 3b51b62, likewise as reported by the debug log.
![image](https://user-images.githubusercontent.com/13796683/140918995-72331c65-a04c-4a18-9586-79a8253a8595.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment] 2021-11-09 12:36
Which one is your preferred? It's not clear...

**Comment by ToxiClay** [comment] 2021-11-09 15:14
> Which one is your preferred? It's not clear...

The older one, of course; the one where it's just listed as "MRE - Ravioli" in the inventory until you specifically crack it open.

**Comment by ToxiClay** [comment] 2021-11-09 15:15
Though, it's _possible_ that the output is something specific to the National Guard starting profession; I wanted to create a military base in the new version to check how it's displayed in a real environment, but the game kept crashing for some reason when I went to spawn one.

**Comment by MarlossCDDA** [comment] 2021-11-09 16:04
Sort of related, I find the whole nested item situation with MRE packages and bags pretty confusing. I've eaten a lot of MREs and I still don't know whether a package contains bags or a bag contains packages, and it seems like it adds a whole lot of inventory management complexity for a small amount of RP. My personal preference would be to just abstract that all away and make the entire MRE a single big food, rather than a package containing a bunch of small foods - barring that I'd like to at least see it involve less nested packaging and things to worry about unsealing.

**Comment by LeahLuong** [comment] 2021-11-09 17:04
I don't even touch MRE's for these reasons. They're so fiddly & half the things like the junk food, utensils, & drink packets I don't even want. Food is so easy to come by otherwise I just can't be bothered.

**Comment by ToxiClay** [comment] 2021-11-09 17:09
> barring that I'd like to at least see it involve less nested packaging and things to worry about unsealing.

That's essentially what the old MRE handling system was. I'd paste screenshots, but going back to my old save, the MRE package is failing a check (Something changed between 0.F and 0.F-2 and I don't know what or when. I'll have to try to track it down) and I'm told I can't disassemble it for some reason. It's *certainly* much neater than the system we have now.

Going back to baseline 0.F lets me disassemble the MRE, and this is what you got after opening it. Definitely a lot better than having to deal with literally all of it before you even open it, neh? 

![image](https://user-images.githubusercontent.com/13796683/140970880-4c437ec7-b42f-4322-96dc-17bb28152b98.png)

**Comment by MarlossCDDA** [comment] 2021-11-09 17:17
Well, I think I like having it as food in a container more than as an object that you have to disassemble - it took me a long time to figure out that they're disassembleable, and it doesn't play nicely with the `E`at menu. The thing that really bugs me is what you can see in that old screenshot as well - the fact that the accessories and desserts are within a second set of containers, so fully eating an MRE involves an annoying amount of inventory management and you end up with 50 separate "Cracker (2)" items on your eat menu rather than one big "Cracker (100)" stack, etc. Given that all the accessories together are like 150 calories, I'd rather just treat the entire MRE as a single food item, like how TV dinners are treated.

**Comment by andrei8l** [comment] 2021-11-09 17:33
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/52699. The nested items are supposed to be hidden but they are not at the moment

**Comment by wapcaplet** [comment] 2021-11-10 02:40
While I continue to strongly agree with the title of this issue (I avoid MREs like the plague now), it is indeed a duplicate. Closing now.

**Closed by wapcaplet** 2021-11-10 02:40 UTC
