### ISSUE TITLE
Vehicle fuel bug or not?

### ISSUE THREAD

**Issue by Dantheman1337** [CleverRaven/Cataclysm-DDA#19681] opened 2016-12-08 10:01 UTC
You cant drive any long distances without refueling. Fuel goes down very fast even with fuel efficient engines... This by design or are you supposed to use reactor/solar instead?

**Comment by mugling** [comment] 2016-12-08 12:15
Duplicate of #19348

**Closed by mugling** 2016-12-08 12:15 UTC
