### ISSUE TITLE
[Aftershock] Unloading uninstalled minireactor yields too much plutonium

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#47772] opened 2021-02-27 15:26 UTC
# Describe the bug

Unloading aftershock Minireactor yields stupid amount of plutonium cells.

# Steps To Reproduce

> Be me
> Use aftershock mod
> See atomic SUV
> Intact minireactor(275)
> Remove minireactor.
> 'U'nload minireactor.
> Get 275 plutonium cells.
> mfw 

# Expected behavior

Not getting 275 plutonium cells but only plutonium slurry. Which I pour out somewhere. 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9815-ge819fbb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP]
]

# Additional context

> mfw no additioal context

**Comment by Mom-Bun** [comment] 2021-02-27 16:04
Duplicate of ##44150

**Closed by Mom-Bun** 2021-02-27 16:04 UTC
Labels: (S3 - Duplicate)
