### ISSUE TITLE
Duplicate Isherwoods?

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74153] opened 2024-05-28 15:55 UTC
### Describe the bug

I was loading overmaps for https://github.com/CleverRaven/Cataclysm-DDA/issues/74151, when I found 2 Isherwoods families? Was using City size 10 & spacing at 8

### Attach save file

Can't, I tried to go over & check out one of the farms, Immediate segmentation fault. So yeah

### Steps to reproduce

Try revealing overmaps

### Expected behavior

There can be only one

### Versions and configuration

OS: Windows
OS Version: 10.0.22631.3447 (23H2)
Game Version: cdda-experimental-2024-05-27-0550 https://github.com/CleverRaven/Cataclysm-DDA/commit/459ec63e90a900c9062068092cfd0ae427181a64 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth]

**Comment by ZhilkinSerg** [comment] 2024-05-28 19:21
Isherwood is not marked as `GLOBALLY_UNIQUE`

**Comment by TealcOneill** [comment] 2024-05-29 07:37
This is intended behavior. 
Making it globally unique has been discussed several times but currently the AI isn't smart enough to keep itself alive and it's not uncommon to find some of the Isherwoods dead when you get there. Such as in #73493 
#61257 has a lot of discussion and links to previous issues talking about this.

**Comment by RenechCDDA** [comment] 2024-05-30 02:18
As mentioned, not globally unique at this time and thus not a bug. Thank you for your report.

**Closed by RenechCDDA** 2024-05-30 02:18 UTC
Labels: (S1 - Need confirmation)
