### ISSUE TITLE
Multi cookers self-delete when recipe is finished cooking

### ISSUE THREAD

**Issue by tranxendance** [CleverRaven/Cataclysm-DDA#44274] opened 2020-09-19 23:57 UTC
# Describe the bug
Title of the pr should describe it sufficiently. Sometimes it causes a full crash of the game.

# Steps To Reproduce
1.Find inworld or debug in a multicooker and battery, potentially mod it with vehicle battery because each recipe takes an enormous amount of charges.
2. Set to make any recipe. Summon raw ingredients via debug menu if necessary.
3. wait until complete
4. Multi-cooker implodes in a cloud of error, sometimes throws an error message, sometimes crashes the client.

Sometimes step 3 is not needed and you get the immediate crash

# Expected behavior

The meal to cook while I was working on something else

# Screenshots
![image](https://user-images.githubusercontent.com/70401955/93691302-49a61d00-fab1-11ea-8154-d38da2029ef6.png)

![image](https://user-images.githubusercontent.com/70401955/93691307-57f43900-fab1-11ea-92b8-91a758fc4746.png)

![image](https://user-images.githubusercontent.com/70401955/93691308-62163780-fab1-11ea-92b2-b3e931406505.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1709
- Game Version: 0.E-6052-gfacb03d [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

New account, so technically my 'first issue' although i'm pretty sure i've done one of these before in the distant days of yore

Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5250906/config.zip)
[Testworld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5250908/Testworld.zip)

**Comment by ZhilkinSerg** [comment] 2020-09-19 23:59
Duplicate of #37167

**Comment by wapcaplet** [comment] 2020-09-20 03:00
Tested in 0.E-6063-gd7d885f047 with a multi-cooker loaded with medium plutonium battery. Near the end of cooking time, I am getting an error like these:

```
 DEBUG    : tried to put an item (meat_cooked) count (1) in a container (multi_cooker_filled) that cannot contain it: pocket with type (CONTAINER) not found
 FUNCTION : ret_val<bool> item::put_in(const item &, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102

 DEBUG    : tried to put an item (broth) count (2) in a container (multi_cooker_filled) that cannot contain it: pocket with type (CONTAINER) not found
 FUNCTION : ret_val<bool> item::put_in(const item &, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102
```

The multi-cooker does not vanish, but it does remain stuck in "cooking" status, even though it is not on:

![image](https://user-images.githubusercontent.com/238395/93693243-95a98f80-faba-11ea-8fa4-88b482e480f0.png)

After this, I cannot cook anything with it, and my crafting menu does not indicate I have a multi-cooker available anymore:

![image](https://user-images.githubusercontent.com/238395/93693264-dacdc180-faba-11ea-8fed-a9d8f02666e2.png)

I got the same result with a cooker in my inventory, and one sitting on the ground.

**Closed** 2021-03-05 04:13 UTC
Labels: <Bug>, Crafting / Construction / Recipes
