### ISSUE TITLE
I can't fit through a broken car door

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#70502] opened 2023-12-29 00:09 UTC
### Describe the bug

I cannot traverse a broken car door.

### Attach save file

Save file: [Apollo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13790161/Apollo-trimmed.tar.gz)

Non standard mods:
[mods.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13790164/mods.tar.gz)

### Steps to reproduce

1. Load attached save file
2. Try to go through the door due south of you
3. There's not enough room for you to fit there.

### Expected behavior

I can travel through a broken door as I can other broken vehicle parts.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 2a65f10 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

**Comment by kasanryukin** [comment] 2023-12-29 00:11
Confirmed on latest experimental. You have to bash the door apart.  Several other broken tiles are also preventing traversal.  I didn't see a PR adding that as in intended features, so I'm pretty sure it's a valid bug.

**Comment by Inglonias** [comment] 2023-12-29 00:12
It appears that attempting to traverse spaces that have zero storage space due to being broken will fail.

Pinging @fairyarmadillo as it's their feature.

**Comment by fairyarmadillo** [comment] 2023-12-29 00:29
Whoops, I'll put in a fix for this tonight. Thank you for the heads up.

**Closed** 2023-12-30 23:53 UTC
Labels: (S1 - Need confirmation)
