### ISSUE TITLE
AIM messages usually aren't printed to sidebar until it's closed

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#63368] opened 2023-01-31 06:54 UTC
### Describe the bug

When moving individual items around using the AIM, messages are printed in the message box at the top of the AIM but not printed in the sidebar. When the AIM is closed, the sidebar is suddenly filled with all those messages at once. This does not occur when using Move All or when moving to All Surrounding Squares. It also doesn't occur if there's a nearby interruption, like an enemy, which thankfully makes this bug pretty minor.

This looks to be an unintended consequence of #62400 - it doesn't show up in the release immediately before that PR was merged.

### Steps to reproduce

1. Start default scenario.
2. Go next to some items and open the AIM. Make one pane the items' tile and the other either another tile or the inventory.
3. Move things around. Note that the AIM message box updates but the sidebar does not.
4. Close the AIM. The sidebar should suddenly update with all of the messages.
5. Open the AIM again and press ',' to move all items from one pane to another. Both the sidebar and the AIM messages should update properly without needing to close the AIM.
6. Press 'a' to make one pane All Locations. Move items from the other pane to a tile and it should update both places.
7. Debug spawn a zombie near the shelter NPC and move individual items. The sidebar should occasionally update as the zombie and the NPC fight, without needing to close the AIM.

### Expected behavior

I'd expect the sidebar to always update as things are moved.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 59f5604 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ChromePoptart** [comment] 2023-01-31 17:23
I had noticed this, too.  The messages not showing up at time of transfer makes it difficult to track what you have already transferred -- I can't think of any specific examples off of the top of my head of when this has mattered, but I know I have noticed this issue and have in the moment wished that it would be reverted to the old, correct behavior.  So, thanks for the write-up, @Kamayana!

**Comment by andrei8l** [comment] 2023-01-31 18:10
I can't reproduce but it's probably related to screen size/overlap between the AIM and side panel. Can you try this change?
```diff
diff --git a/src/advanced_inv.cpp b/src/advanced_inv.cpp
index a8e0b7bd7c..37af774f30 100644
--- a/src/advanced_inv.cpp
+++ b/src/advanced_inv.cpp
@@ -1635,6 +1635,7 @@ void advanced_inventory::display()
 
         if( ui ) {
             ui->invalidate_ui();
+            g->invalidate_main_ui_adaptor();
             ui_manager::redraw_invalidated();
         }
 
```

**Comment by Kamayana** [comment] 2023-02-01 05:20
> I can't reproduce but it's probably related to screen size/overlap between the AIM and side panel. Can you try this change?
> 
> ```diff
> diff --git a/src/advanced_inv.cpp b/src/advanced_inv.cpp
> index a8e0b7bd7c..37af774f30 100644
> --- a/src/advanced_inv.cpp
> +++ b/src/advanced_inv.cpp
> @@ -1635,6 +1635,7 @@ void advanced_inventory::display()
>  
>          if( ui ) {
>              ui->invalidate_ui();
> +            g->invalidate_main_ui_adaptor();
>              ui_manager::redraw_invalidated();
>          }
>  
> ```

That worked! I'll make a PR for it, thanks!

**Comment by cake-pie** [comment] 2023-02-12 04:53
@Kamayana PR in wrong repo

**Comment by Kamayana** [comment] 2023-02-12 16:41
> @Kamayana PR in wrong repo

Is it? The PR message looks correct to me:

> [Kamayana](https://github.com/Kamayana) wants to merge 1 commit into [master](https://github.com/Kamayana/Cataclysm-DDA) from [aim_keep_updating_sidebar](https://github.com/Kamayana/Cataclysm-DDA/tree/aim_keep_updating_sidebar)

Am I missing something?

**Comment by cake-pie** [comment] 2023-02-13 00:56
You made the PR in your own fork (Kamayana/Cataclysm-DDA) and not the upstream here (CleverRaven/Cataclysm-DDA)

**Closed** 2023-02-15 06:19 UTC
Labels: (S1 - Need confirmation)
