### ISSUE TITLE
Minor storage clothing  into vehicle part conversion bug

### ISSUE THREAD

**Issue by RegisteredJustToVoteOnCataclysmFeatures** [CleverRaven/Cataclysm-DDA#64836] opened 2023-04-04 21:25 UTC
### Describe the bug

If storage clothing (eg a short rope) is worn by the player to hold an item (eg a makeshift crowbar) along with others of the same type (eg another short rope in a worn backpack) and the player install parts in a vehicle (eg adding a seatbelt to a driver seat) the player has the option to select which is consumed during installation. So far so good.

However, if a player by mistake selects the "short rope -> makeshift crowbar" one, the item will be consumed, and the makeshift crowbar will vanish completely instead of being dropped at the players feet.

I describe the bug as minor because if that same vehicle part is uninstalled, the stored item will be still once converted back into an ordinary item with storage capacity.

### Attach save file

N/A

### Steps to reproduce

1. Debug in a player, backpack, 2 short ropes, one makeshift crowbar, screwdriver, a car.
2. Mutate to add skills (mechanics 1 needed to install/uninstall seatbelt)
3. Wear 1 short rope, select that short rope in inventory, insert the makeshift crowbar
4. Wear the backpack, insert the other short rope
5. Remove a seatbelt from the car as usual.
6. Install a seatbelt. As the removed seatbelt will be lying around a menu will ask whether to use a short rope that is "nearby" or on person. Select "on person". A second menu will ask whether or not to use the short belt that is just taking up space in the backpack, or the one that is used as storage for a makeshift crowbar.
7. Pretend you're as clumsy as the guy writing up this bug report and accidentally select the "short rope -> makeshift crowbar" one.
8. On installation, use the V key to see if there's a makeshift crowbar lying anywhere nearby, or i to see if it is in inventory. There won't be one. (This is the unexpected behaviour/bug)
9. Uninstall the same seatbelt that was a short rope holding the makeshift crowbar.
10. Use V to inspect the uninstalled short rope at the player character's feet. The makeshift crowbar is in the short rope.

### Expected behavior

I'd expect any items stored in the soon-to-be-vehicle-part to be dropped at the player character's feet (as per 8 above) after the part is installed, instead of vanishing temporarily like a cow assisting Magical Trevor in a magic act.

### Versions and configuration

OS: Windows
OS Version: 6.1 7601
Game Version: 65407fa [64-bit]
Graphics Version: Tiles
Game Language: System Language []
Mods loaded: [
Dark Days Ahead [dda]
Portal Storms Ignore NPCs [personal portal storms]
No Fungal Growth
Bionic Professions
SpeedyDex
Stats Through Kills
Stats Through Skills

**Comment by irwiss** [comment] 2023-04-04 21:29
seems a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/54235

**Closed** 2023-04-05 06:04 UTC
Labels: (S1 - Need confirmation)
