### ISSUE TITLE
Natural water sources within crafting range prevent use of water on crafting screen.

### ISSUE THREAD

**Issue by Soralin** [CleverRaven/Cataclysm-DDA#19397] opened 2016-11-21 20:50 UTC
Tested with versions 5881 and 5924

Discovered this trying to use water from a swamp, and later, also from a river.  If you gather water from a swamp, and then go to your crafting screen to use it, it's marked in red, and the recipe can't be attempted.

However, if you leave the swamp with the water, then it suddenly becomes available for use in crafting.  And specifically, it happens whenever you're within crafting range of one of the pools of water.  Not only is it not allowing use of the ground water directly in recipes, it's also preventing use of water from your inventory as long as you're within range of it.

**Comment by codemime** [comment] 2016-11-21 21:08
Dupe of #18241.

**Closed** 2016-11-21 21:11 UTC
Labels: Duplicate
