### ISSUE TITLE
DEBUG: No TURRET

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17931] opened 2016-08-05 14:05 UTC
Happened twice now, i  think ammo spawning code is trying to find a turret to fill but since its busted it breaks.

![2016-08-01-213100_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/17439028/38c0e652-5b26-11e6-9a56-b90c7c028494.png)
![2016-08-01-213512_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/17439033/4178ff1e-5b26-11e6-8271-7e3e0294b764.png)
![2016-08-05-155012_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/17439039/47209652-5b26-11e6-8bc1-3b75069fd245.png)
![2016-08-05-155555_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/17439050/4d977546-5b26-11e6-957b-1c549105c165.png)

(No blazemod involved ;))

**Comment by DLaboratory** [comment] 2016-08-05 15:28
Confirmed. Met this also in my save in recent days, when traveling to a new city, this could happen occasionally.

**Comment by mugling** [comment] 2016-08-05 19:52
Potentially relatedly I'm also struggling to start engines a `global_pos3` returns an incorrect location. @Coolthulhu any recent updates to vehicle that could have affected this?

**Comment by DangerNoodle** [comment] 2016-10-10 08:14
It seems I have stumbled on the same bug. I am disappointed that no discussion or useful info has developed since the date this was opened.

![anomaly](https://cloud.githubusercontent.com/assets/22048567/19229874/724b1246-8e96-11e6-963d-990f468bcbb2.png)

It would be reasonable to assume that turrets now needing to be explicitly reloaded, and/or the vehicle definitions now defining a random chance of it spawning loaded, are the cause here.

Apologies for my initial post regarding this error being in my report of checking for errors after https://github.com/CleverRaven/Cataclysm-DDA/pull/18566. That said, it might be good to check whether or not generic tanks are subject to the same potential "error on first encounter" issue, since fuel tanks are now also set to randomly spawn with fuel in the tank.

**Comment by hmstanley** [comment] 2016-10-21 04:19
I actually think this is related to the fact that these weapons have modifications on them, - bipod, and I suspect that's the bug. Since you can't mount these on turrets after you remove them from the turret. Only unloaded non modified weapons can exist on turrets.

**Comment by DangerNoodle** [comment] 2016-10-21 05:00
But do these mods show up on a weapon by default? As far as i can tell, this is about a debug error occurring when a vehicle first spawns in the reality bubble, so it should have a mounted weapon in default configuration.

**Comment by hmstanley** [comment] 2016-10-23 04:39
Right.  But, for some reason, the fact that these weapons have integrated bipods screws up the mounting logic methinks. That said, the same doesn't happen for vehicles with .50 or 120mm guns etc. only with 240/249/ m60 all of which have an integrated bipod.

**Comment by hmstanley** [comment] 2016-10-23 04:42
I did this experiment. I removed the m249 on the Humvee and then tried to remount it. I couldn't. For any weapon with the bipod. I could do it for weapons without bipods.

**Comment by DangerNoodle** [comment] 2016-10-23 16:00
Incorrect. This bug also seems to occur with the tank cannons in Tanks and Other Vehicles mod, which do not come with any gunmods installed.

Bipod anomalies are likely a separate bug.

**Comment by hmstanley** [comment] 2016-10-23 16:11
You mean the turret issue. Ok. I didn't test this. But, the fact that the M249 exists on the Humvee and then removing it and trying to add it back results in no joy. It appears that blazemod is not related to this issue tho. I'm gonna test this a little further.

**Comment by DangerNoodle** [comment] 2016-10-23 16:26
The issue that is being reported here has been linked to the "define turret as loaded in vehicle definition" changes, as far as can be determined. It only seems to create an error when the vehicle is generated with ammo loaded into it, *and* with the turret part itself generating broken. The exact cause is likely related to whatever code generates ammo for turrets that spawn loaded, but no one with adequate code experience has put effort into confirming and reporting their findings.

Whatever code that creates this failure is likely unrelated to https://github.com/CleverRaven/Cataclysm-DDA/issues/18886, this is off-topic.

**Comment by hmstanley** [comment] 2016-10-23 16:49
Sorry man. Just thought they were connected. Guess not.

**Comment by DangerNoodle** [comment] 2016-10-23 17:22
If a specific pull request changed both sections of code, it is possible. But not likely.

No worries though.

**Comment by DangerNoodle** [comment] 2017-03-26 04:08
Is this actually fixed? Can you confirm this?

**Comment by kevingranade** [comment] 2017-04-05 01:23
Report on forums that t his continues to occur: http://smf.cataclysmdda.com/index.php?topic=14316

**Comment by DangerNoodle** [comment] 2017-04-05 01:53
Peculiar. I will obtain the latest build to further attempt to encounter this error as well.

**Comment by DangerNoodle** [comment] 2017-04-05 02:04
Is there any way to force a certain level of vehicle damage when placing a vehicle using mapgen entries? This would permit easier testing, as otherwise occurrence of this error is purely dependent upon random generation. Failing that, increasing the weight of armed vehicles in vehicle groups would work as a way to expedite testing.

**Comment by DangerNoodle** [comment] 2017-04-05 02:15
Confirming occurrence of this issue in latest build at time of posting, 0.C-21985-g2ccdd6eefa, or build number 6377.

![confirmation](https://cloud.githubusercontent.com/assets/22048567/24686790/9ac45e24-197b-11e7-97ab-775d648b67da.png)

As I stated in prior post, testing was expedited via increasing the weight of vehicles possessing turrets, then simply wandering through town until an error occurred. World was purely default settings, with only the default mods.

**Comment by Coolthulhu** [comment] 2017-04-05 07:55
I closed it because an instance of this bug has been fixed and stopped happening.
The debug message is the same as earlier, but the bug most likely has a different source.

**Comment by DangerNoodle** [comment] 2017-04-05 08:15
> At least I haven't seen it in a long time, while earlier versions had it happen a lot.

As this bug can only develop under specific random circumstances, the only way to actually confirm if the bug is resolved is to force a given vehicle to spawn with turrets loaded one hundred percent of the time.

Having done so, forcing large numbers to appear in cities will eventually confirm it to be fixed in the event you find one that has generated with a destroyed turret, without having provoked a debug error.

**Comment by DangerNoodle** [comment] 2017-04-05 08:19
Additionally, a question. What pull request do you suspect had fixed an earlier instance of this bug? Because no pull request appears to have linked to this issue. And given the nature of this bug, without knowing what attempted to resolve the issue, it remains possible that it was only a gap in confirmation, not a gap in occurrences.

**Comment by Coolthulhu** [comment] 2017-04-05 08:37
> Because no pull request appears to have linked to this issue.

One of the ranged reworks changed a large part of turret.cpp. Many PRs do not link to relevant issues because digging through 900+ issues with github's wonderful search engine can't be treated as a mandatory requirement.

Many bugs die "on their own", with no explicit fix. If it's hard to reproduce, it usually dies that way.

**Comment by DangerNoodle** [comment] 2017-04-05 14:37
That would explain it then. My apologies for that.

**Comment by chrBrd** [comment] 2017-06-07 23:56
I've just come across this bug on a self-compiled build of the master branch. It's showing up exactly as it is for DangerNoodle, but the line no. is 4938.

**Closed** 2017-09-04 18:54 UTC
Labels: Bug, Vehicle
