### ISSUE TITLE
Gun glitch with magazines

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#44247] opened 2020-09-18 18:03 UTC
Checking guns that hold magazines even if they're on the ground or in racks causes this glitch

` DEBUG    : tried to put an item (ump45mag) count (1) in a container (hk_ump45) that cannot contain it: pocket unacceptable because holster already contains an item

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1102
`
Platform     : Windows_x64
Graphics     : Tiles
Build number : #11009
Build version: 0.E-6018-g1371f96
Major version: 0.E

**Comment by wapcaplet** [comment] 2020-09-18 19:54
Duplicate of #44158

**Closed** 2020-09-18 19:56 UTC
