### ISSUE TITLE
A7 Laser Rifle Vehicle Turret (Blaze Industries) bug.

### ISSUE THREAD

**Issue by Westbend** [CleverRaven/Cataclysm-DDA#68669] opened 2023-10-15 14:13 UTC
### Describe the bug

The A7 Laser Rifle when mounted as a vehicle turret (with the Blaze Industries mod I am assuming) will only fire a few shots before ceasing to fire completely. At first I assumed this was the new overheat mechanic, but the A7 turret will never fire again, regardless of wait time. 

Removing and remounting the A7 Laser Rifle into the turret will enable fire for a few shots again. 

I am assuming the new overheat mechanic is not playing nice with the Blaze Industries mod and a bug occurs when the gun goes into overheat mode as a turret?

### Attach save file

N/A

### Steps to reproduce

1. Mount A7 Laser rifle into a vehicle turret with fully loaded storage batteries and automatic turret fire capabilities.
2. Drive into some enemies.
3. Some pew pew laser fire occurs.
4. Laser fire stops.
5. Laser Turret never functions again until removed and remounted.

### Expected behavior

Continual laser pew pew, with short pauses for cooling down overheating, and storage battery power draw.

### Versions and configuration

cdda-windows-tiles-x64-2023-10-14-0631

**Comment by DeCEll-1** [comment] 2023-10-15 14:17
It's a known bug and afaik so far no way to solve it (and shouldn't be related to any mod).
If you want to have the gun working you can edit the `heat_per_shot` value of A7 to 0.00001 at line 142 in the ups.json (0 gave an error last time i tried)
its at data>json>items>gun>ups.json

**Comment by Westbend** [comment] 2023-10-15 18:41
> It's a known bug and afaik so far no way to solve it (and shouldn't be related to any mod). If you want to have the gun working you can edit the `heat_per_shot` value of A7 to 0.00001 at line 142 in the ups.json (0 gave an error last time i tried) The file is at data>json>items>gun>ups.json

I mention Blaze Industries mod because im assuming you cant mount a A7 Laser Rifle as a vehicle turret without it. Also, thank you for the tip. Ill try it out.

**Comment by RenechCDDA** [comment] 2023-10-17 10:40
Duplicate of #68011

**Closed by RenechCDDA** 2023-10-17 10:40 UTC
Labels: (S1 - Need confirmation)
