### ISSUE TITLE
Oversized flag naming change in description

### ISSUE THREAD

**Issue by Leosky** [CleverRaven/Cataclysm-DDA#30788] opened 2019-05-23 20:29 UTC
**Is your feature request related to a problem? Please describe.**  
Currently the red 'too big' in item description is confusing lots of player accounting this as an issue and not a feature.

**Describe the solution you'd like**  
A description change for the oversize flag might be useful to change from red 'too big' to a blue 'larger' (or 'wider') in its description to correlate more that its a feature and note a issue.

**Comment by Feuerhai** [comment] 2019-05-24 02:05
duplicate of: #30410

**Comment by ifreund** [comment] 2019-05-24 10:12
Closing as Duplicate of #30410

**Closed by ifreund** 2019-05-24 10:12 UTC
