### ISSUE TITLE
Cannot fill ammo racks with ammo, only liquids

### ISSUE THREAD

**Issue by EyesNoEyes** [CleverRaven/Cataclysm-DDA#20253] opened 2017-02-10 21:25 UTC
https://cdn.discordapp.com/attachments/252368987210514433/279723307333451789/unknown.png

Truly a bizarre error. This might be a tanks or vehicle additions mod error however. It doesn't work with belts or loose ammo.

Windows 10, build 6227.

**Comment by pisskop** [comment] 2017-02-11 19:41
You arent supposed to be filling them with anything, iirc.

you used to be able steal from them with an npcs help. or even advanced inventory

**Comment by Reclusive-reptile** [comment] 2017-02-12 04:34
@pisskop he means the ammo rack vehicle part added by blaze mod. They can not be filled with ammo that the turrets can then use as they were intended. Blaze was in the process of migrating his turrets to use magazines last I checked on the forums, but then the VPO was reverted and the in game mod error checking functions broke.

**Comment by codemime** [comment] 2017-02-12 14:15
Dupe of #19675.

**Closed by codemime** 2017-02-12 14:15 UTC
