### ISSUE TITLE
Description is unclear that Battery Compartment Mod intentionally doesn't accept Swappable Storage Battery

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21059] opened 2017-05-20 00:18 UTC
the Battery Compartment Mod says it will accept vehicle batteries, but doesn't seem to accept a storage battery.

Initially I thought this might be for balance, until I realized swapping out motorbike batteries just takes a wrench and mechanics 2

**Comment by Xpyder** [comment] 2017-05-20 00:21
Assuming this is an oversight, it should probably accept medium and small storage batteries too (the things you get from disassembling a big storage battery)

**Comment by 1skandar** [comment] 2017-05-20 10:37
It should be noted that a storage battery is several hundred pounds, it kinda makes sense if you think about it.

**Comment by spacenookie** [comment] 2017-05-21 04:08
maybe a description string change in data/json/items/toolmod.json

currently, 


`"description": "A battery compartment mod that allows using high-density, rechargeable vehicle batteries in regular tools.",`
 `"magazine_adaptor": [ [ "battery", [ "small_storage_battery", "medium_storage_battery", "battery_motorbike", "battery_car" ] ] ]`


could be
`"description":"A battery compartment mod that allows using small storage, medium storage, motorbike, and car batteries in regular tools.",`

**Comment by Solusphere** [comment] 2017-05-21 06:36
Given the weight, I assume the large storage battery refers to one of these: https://www.nrel.gov/transportation/assets/images/01_rotator_ee.jpg

So yeah, I'm not surprised that a battery system designed for portable tools isn't compatible with them.

**Comment by ZenZen2** [comment] 2017-05-22 11:19
Looks like this is intended. Please start a new issue with a proper title and a suggestion how the description should be changed. And then this can be closed. Else theres a high risk this wont be changed.

**Comment by Zireael07** [comment] 2017-05-22 11:42
I see no reason to create a new issue just to discuss a description change. Let's keep issue spam to minimum

**Comment by Xpyder** [comment] 2017-05-23 18:02
You're not going to fit a car battery into a hand held tool either.

The impression I got is that it was more like the alligator clips you get on a jumper cable that you connect to the battery, tied to a voltage regulator so it doesn't blow out the tool.

That said you can get medium batteries by disassembling the  storage battery so I'm more interested in getting a clearer description than I am in changing it to support storage batteries

**Comment by Toothspit** [comment] 2017-05-24 16:46
The battery's weight is (currently, pre-that-PR) added to the tool when reloading it. This implies:

- The battery is directly attached to the tool. There are no cables and the battery is not sitting on the floor or anything.
- The player can make a decision as to whether they can pick up the tool with the battery's additional weight.
- If the player attaches a battery too heavy for them to carry, they will not be able to carry it (duh), and can decide to replace the battery with a lighter one.

This seems like an issue that solves itself. If anything, absurdly-high-STR players *should* be allowed to use the big fellas, why not?

**Comment by Treah** [comment] 2017-05-24 16:50
I can always change the PR to allow all of the storage batteries. I did not change any of the weight behavior in the PR.

**Comment by 1skandar** [comment] 2017-05-24 17:26
The only question then, really, is balance. The amount of portable charge you already get from mediums is kinda insane, something on the order of 7000. I think a regular storage battery is something on the order of 40,000.

**Comment by Toothspit** [comment] 2017-05-24 18:19
I don't even think there's a balance problem. You can get a flashlight with 40,000 charges of battery, sure, but you're still shlepping around a 200kg 10L flashlight.
![screenshot_2017-05-24_13-17-33](https://cloud.githubusercontent.com/assets/18541270/26418874/70bc84ce-4083-11e7-9518-82973b676729.png)

**Comment by 1skandar** [comment] 2017-05-24 18:33
Aye, the problem is with things like a welder, where you slap a mod on it and a storage battery and pretty much bypass the need for vehicle rigs. 

I don't necessarily have a problem with it, just I'm not completely convinced there isn't a balance issue or two that may crop up.

**Comment by Xpyder** [comment] 2017-05-24 20:03
> the problem is with things like a welder, where you slap a mod on it and a storage battery and pretty much bypass the need for vehicle rigs.

This issue is already circumvented with small storage batteries (require no tools to install or remove from a vehicle) and the battery compartment mod.  You can just stick a couple on any vehicle frame and get free power from running the engine giving unlimited welder charges.  The only thing restricting this is that it's a little fiddly, which is already circumvented by using medium storage batteries (only require basic tools to install), or car/truck batteries.

I do agree that it might be making free power too easy (which might eventually get patched by changing how battery charges work), prior to getting access to the UPS system; but that's a problem innate to this mod, not something that would be introduced by allowing full storage batteries to be loaded into it.

If we don't want people doing this we should either remove the mod, or replace it with something like the jumper cables that attaches the tool to a vehicle, but would break if you don't remove it before driving.  You'd get the same benefit but in a more restricted setup, basically tying it to a static framework like I assume most people build near their base (a few wooden frames with a tank, funnel, solar panels, swappable storage batteries, and possibly an engine to act as a generator)

**Comment by Xpyder** [comment] 2017-05-24 20:10
That said, while I think replacing the mod (as I mentioned just previous) would be a better solution, that's a larger project.

Because of how easy small storage batteries are to install and remove from vehicle frames, allowing you to load [large] storage batteries into a tool with the Battery Compartment Mod doesn't introduce any new issues (since those issues already exist innately to the mod) and not being able to do so is confusing without a description making it clear it's only the big one you can't load.

**Comment by AMurkin** [comment] 2017-05-24 20:26
> but would break if you don't remove it before driving

For me it's too unclear.

What it divide batteries in vehicle in two categories:
- primary - for starting engine and limited in count in one vehicle
- secondary - passive - has low charge rate, not counts for starting engine

**Comment by Xpyder** [comment] 2017-05-24 21:15
> secondary - passive - has low charge rate, not counts for starting engine
If you were going to do this I would say the secondaries should be able to be used for starting an engine, but should charge slow, have a low total charges, and be the only ones usable in tools.

But unless you have a simple way to convey this, and have it be reasonably close enough to IRL to maintain suspension of disbelief I think it's going to end up being a more complex workaround that's more confusing, all to avoid allowing it to connect to large storage batteries because of an issue that already exists without this functionality.

> The battery's weight is (currently, pre-that-PR) added to the tool when reloading it. This implies...
It also adds the batteries volume which implies it's not going inside the tool, but being connected externally

**Comment by Night-Pryanik** [comment] 2017-05-25 07:35
Resolved by #21106.

**Closed by Night-Pryanik** 2017-05-25 07:35 UTC
Labels: Other
