### ISSUE TITLE
Reproducible Crash Bug/ Save Invalidation (ver 5200e4b)

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13048] opened 2015-07-24 20:37 UTC
Okay, edit: the fourth time I went back in it did not reproduce. I'm going to try to find out why.
The error message was something like 'cannot find monster with id:32' or along those lines.
Got it again: "Tried to find monster with invalid index -1 Monster num: 42" . It seems to happen after safe mode is triggered. I don't know why it didn't happen that fourth time, maybe because of the direction I went?

Install folder zip: http://s000.tinyupload.com/index.php?file_id=61092167698249086683
Just the save zip: http://s000.tinyupload.com/index.php?file_id=79881219496349241542

Move <s>two</s> several tiles in <s>any</s> most directions, game crashes.

Also, is there any chance of getting a save folder rotation in place? Like, when it saves it'd use one folder first, then a second, then alternate back to the first. So that in these situations where a save breaks itself you can get back to a relatively recent point.

**Comment by karlnp** [comment] 2015-07-24 22:15
That's a good idea. I'll look at the feasibility of doing that.

**Comment by drbig** [comment] 2015-07-25 07:53
Hmm, saves shouldn't break nor the game should crash... Save rotation sounds like adding complexity just to cure a (rare) symptom.

Also there are [tools](https://github.com/drbig/saver) for 'save backups'.

**Comment by drbig** [comment] 2015-07-25 07:55
Also this looks like duplicate of #12996.

**Comment by hustergeyser** [comment] 2015-07-25 13:13
Something happened between releases this didn't delete the save as it crashed in the previous post, but as of a441f82 it does.  So it seems as though it's getting worse.

**Comment by Headjack** [comment] 2015-07-25 17:51
@hustergeyser does it? I had only meant that the file in question was repeatedly trapped in the error.

Also, I'm not sure if it's indicative of how the bug works, but there seemed to be an association between safe mode noticing a zombie and the error, so it might have something to do with the mob coming into view?

**Comment by DanmakuDan** [comment] 2015-07-27 01:17
The debugger shows the crash happened at monster::group_bash_skill, which appears to be handled by  #13052 already.

**Comment by drbig** [comment] 2015-07-27 07:30
Indeed, closing by #13052.

**Closed by drbig** 2015-07-27 07:30 UTC
Labels: Duplicate
