### ISSUE TITLE
Taekwondo kick attacks damage hand armor

### ISSUE THREAD

**Issue by Numbuh474** [CleverRaven/Cataclysm-DDA#54698] opened 2022-01-23 13:49 UTC
### Describe the bug

When using taekwondo special attacks, armor in the hand slot is damaged when performing strong hits.

### Steps to reproduce

1. Learn Taekwondo and train unarmed combat to at least 2 to enable special attacks.
2. Equip a pair of gloves.
3. Enter combat wielding nothing and using Taekwondo style.
4. Attack until your glove durability decreases.

### Expected behavior

I expected that gloves would not lose durability while kicking, because kicks are done with the feet and not with hands.

### Screenshots

![image](https://user-images.githubusercontent.com/35499003/150681489-9c38894c-9653-4148-aa1a-06d4386d70ae.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: dc02e84 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment] 2022-01-23 21:44
@NetSysFire This was remarked upon in #52001 & it looks like a fix is underway in #53954. Does that warrant closure of this thread??

**Comment by NetSysFire** [comment] 2022-01-23 22:50
Good catch. Duplicate of #52001.

**Closed by NetSysFire** 2022-01-23 22:50 UTC
Labels: <Bug>, (S3 - Duplicate), Melee, Items: Armor / Clothing
