### ISSUE TITLE
Proposal: laptop keyboard setup

### ISSUE THREAD

**Issue by Parahacker** [CleverRaven/Cataclysm-DDA#12040] opened 2015-04-16 15:13 UTC
Hi! First time commenter, be gentle.

I use a laptop with no numpad; thus, all the movement keys needed to be reset. I use 'u' (northwest) through '.' (southeast) , which works out -- especially with the j key having a touch-prompt on it for touch typists (the little plastic tab thing, don't know if I'm describing it well). 

The problem is that this is a LOT of reconfiguration, and I still occasionally run into situations where a key I've reconfigured bumps into a submenu that used to use it; example, in the mechanics/vehicle window, the 'o' was used for remove; it took me a while to remember why it wasn't working. Also, resetting the key did not change the 'o' from being highlighted light green in the word 'remove' in the menu. (Or was that the m key? Working off dim memory, here. Either way, I fudged it up the same.)

Is it possible to add a standardized 'laptop' keyboard configuration that folks like me can use out of the box? And have it set up so that a noob like me doesn't accidentally delete interface options in submenus, trying to be able to move around? 

I've got my setup working mostly right, but I figure I'm not the only one who's had this problem. Especially for someone new to the game, it can be really daunting to try to overhaul.
##

**Comment by facepalm** [comment] 2015-04-16 15:27
The game implements the vi system of movement, which has been around in one form or another for nearly 40 years:

`yku`
`h.l`
`bjn`

You may be of the opinion that it's not a _good_ standard, but it is an established one.

**Comment by Parahacker** [comment] 2015-04-16 16:04
Good? It's horrible. It makes no sense at all. 

I originally thought that was set up for a different type of keyboard - a dvorak or similar. On a qwerty keyboard, it's like using your elbows to move around - possible, but you look funny and you hurt your elbows. 

Now I understand the historical connections to vi, and I looked up the cursor movements. Everything is on the same line of keys, in vi; h,j,k,and l. Ok, great, I now have learned some vi arcana. If that's the purpose of that keyboard layout, then purpose served. But if the purpose is to move a character, it's... awful.

There is no northwest and southwest in vi. I suggest that the use environment for navigating a cursor through lines of code, versus moving a player character - even an ascii character - is a far different thing with different requirements. There's no *need* to have keys representing cardinal directions be scattered all over the (physical) keyboard. Is my request so crazy?

People with numpads don't have this problem; non-vi programmers have no use for such muscle memory. Unless you're suggesting the userbase all learn vi, I don't think that's a good argument. Maybe I'm overstepping myself here, it's up to you guys. I've got my layout working ok. I'm just suggesting the stock layout is unapproachable by a lot of your potential players.

**Comment by DavidKeaton** [comment] 2015-04-16 17:32
Trust me, vi keys on Dvorak look like even more of a mess than qwerty (Dvorak user here). It may look like it's bonkers, but it makes sense after a while. Not to mention, a benefit of learning is, it is used all over the place in Linux.
That is, assuming you wish to learn vi keys, and even use Linux. :-)


Albeit I will say, that on Dvorak, it's great being able to dedicate left hand to up and down, and right hand to left and right.
```t v f```
```j e p```
```n c l```

**Comment by facepalm** [comment] 2015-04-16 18:58
>Good? It's horrible. It makes no sense at all. 

Absolutely true.  But it's been horrible and has made no sense at all for _decades_.  

I was curious to find out where the uybn diagonal movement keys entered the picture, and apparently that was [Rogue](http://nethackwiki.com/wiki/Vi).  The game Cataclysm is like.

**Comment by DavidKeaton** [comment] 2015-04-16 20:21
It's the game that all these games are based on in some way or another. :-)

**Comment by Parahacker** [comment] 2015-04-16 23:13
Ok, ok, I hear you guys.

If anyone's interested in the keymapping I use:

Directions:
uio
jkl
m,.

(o)pen is now capital O; (c)lose is capital C for consistency, making (c)hat lowercase c; (m)ap is now F2, with (I)nventory F1 and the character screen F3 (it's nice having the info screens side by side); my action menu is F12. Various other tweaks like v for re(m)ove have been made in submenus.

For what it's worth, I wasn't proposing eliminating the existing setup in favor of mine. Just adding an option (maybe commented out in a config file or something) for novice players who have laptop keyboards to work with, so they don't stumble into the same issues I did. I remember never, ever playing Rogue on a laptop because of the arcane key commands; I had it on my desktop though, because I had a numpad. I didn't realize their wierd layout was from tradition. I was hoping that someone who's more familiar with the game, and the potential pitfalls of remapping such keys, would step in with a better answer.

**Comment by kevingranade** [comment] 2015-04-17 01:31
I have absolutely no problem having an alternate keyboard layout. (For any
reason, dvorak or similar also comes to mind).
I have precisely the same interest in creating and maintaining one though,
but I'd be happy to help with the backend for handling multiple layouts,
it's probably as simple as having an option that tells the keymap loading
code what file to load.

**Comment by Parahacker** [comment] 2015-04-17 02:03
That seems like it'd work. If I could save my keyboard layout as a separate file, I'd work as many bugs out as I could then submit it that way. Someone could just grab it and plug it in.

The only other issue would be the menu suggestions - like how rem(o)ve has the o key highlighted, despite the fact that I changed it. Is there a way to have it pick up on the change, the way the help files already do? I'd add that for keys which don't fit in the word at all (like if I used x for remove) there be a way to see that, maybe have it follow the word, like: install (z), repa(i)r (i), remove (x)....

**Comment by Parahacker** [comment] 2015-04-17 02:04
Also, a way to view all submenus that use a particular key would be just useful as all getout.

**Comment by narc0tiq** [comment] 2015-04-17 12:10
> resetting the key did not change the 'o' from being highlighted light green in the word 'remove' in the menu

I, too, am bothered by this: #9572

**Comment by TranquilMarmot** [comment] 2015-04-18 06:04
I use a pretty funny keyboard setup on my laptop...

For the eight directions, I have

`q w e`
`a _ d`
`z x c`

I like having movement on the left side of the keyboard since it's closer to WASD

I had to remap a few actions, of course...
`Tab - Examine`
`1 - Use`
`2 - Wield`
`3 - Close`
`4 - Smash`
`; - View`

Works REALLY well on a laptop, you can play one-handed pretty well and it's easy to get used to and easy to set up. And it keeps your left hand near the shift key so it's easy to do actions that are assigned to capital letters!

**Comment by Parahacker** [comment] 2015-04-18 17:40
I'd like to give that a try, though I'm pretty happy with a right-hand setup ^_^ I might remap my function key commands to the numbers, though; I don't really use those for anything right now.

**Comment by Parahacker** [comment] 2015-04-18 17:43
@narc0tiq Yeah, I figured that deserved a separate bug ticket. But it's highly relevant to any discussion of remapping keys, I think.

**Comment by narc0tiq** [comment] 2015-04-18 18:59
Oh, yes, very much so.

**Comment by a1studmuffin** [comment] 2016-07-22 11:35
Hi guys, sorry to dig up an old conversation from last year. :) Just thinking, a potential simple workaround for this issue might be to allow the standard cursor keys (up/down/left/right) recognize diagonals as well. You'd need to make the cursor keys respond on key release rather than downpress. If two compatible cursor keys were pressed at the same time (eg. up + right), it'd perform a NE diagonal movement. You'd probably want to make it an Interface option as some players might not like the short delay it introduces, but for laptop players this would be awesome.

**Comment by illi-kun** [comment] 2016-11-06 17:54
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-06 17:54 UTC
Labels: Enhancement, Suggestion (Discuss)
