### ISSUE TITLE
Maps cause lag when there are many of them

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#37554] opened 2020-01-30 13:08 UTC
# Describe the bug

When you access a tile with many trail guides/restaurant guides/whatever other type of maps there are, if there are many of those (dozens), there is a significant lag. I.e. game just hangs. Doesn't respond to any input. Well, you get the idea.
In my case, I store all my used maps in one tile. There are about 70 of them, all used. When I access the tile, either via AIM or just by regular "g"-"pick things up" interface, the game lags (for the first time) for about 15 seconds. Second and further access to the tile is effectively instant.

# Steps To Reproduce

1. load save from [here](https://drive.google.com/open?id=1YplTX7J1GxGrjHPokhhEgzzxE9uGi84c). 
2. Go to the main camp.
3. Maps are on the table to the right of entrance, in the center tile.
3.5 Try opening pick up interface on the tile, or switch to it in AIM.
4. Observe the lag.

# Expected behavior

No lag. I guess maps's used/unused state is not stored in a savefile, and instead it's checked against which overmap tiles are "opened" and which are not when the game accesses the map for the first time? Which would be an okay thing for everyone but some maniacs who, for some reason, love to collect useless items :) Furthermore, as there is no lag with second and later access attempts, I gather their state *is* being cached somewhere, so it probably shouldn't be a big issue to add it to the save.

# Versions and configuration
     OS: Windows 7 x64
     Game Version: 0.D-11601-g30a5718 [64-bit]
     Graphics Version: Tiles
     Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by scorpion451** [comment] 2020-01-30 16:19
Huh, go figure.
On a hunch I just disassembled the large pile of maps I've been packratting at my base, and I'd swear there's a noticeable reduction in lag. Can't rule out placebo effect, but it might be worth looking at whether it's repeatedly running the check for the used state as long as a map is in the reality bubble/in line of sight/something similar.

**Comment by joe9000** [comment] 2020-02-13 00:10
i've got a very similar experience, but it seems to originate with the huge number of items in a particular tile

**Comment by wapcaplet** [comment] 2020-08-31 23:18
I cannot reproduce this issue in master 801b7869, with these steps:

- Debug-spawn one of each kind of map (military operations map, road map, subway maintenance map, survivor's map)
- Drop them on the ground (this is required to bind the maps to the nearest city)
- Pick them up and `a`ctivate them to make them "(used)"
- Debug-teleport to another city, and repeat the process 24 more times to get 100 used maps

Every time, picking up the pile of maps (whether they are used or not) using `g` or `/` is nearly instantaneous, with no slowdown that I am able to notice. After saving and loading the game, trying to grab the pile of maps takes about 0.5 second the first time, then is very fast after that.

Attached savegame with a pile of 100 maps on the tile to the north: [Pile-100-maps.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5153090/Pile-100-maps.zip)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-5499-g801b7869d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by mqrause** [comment] 2020-08-31 23:57
Just tried your save on a mediocre pc and it takes between one and two seconds after loading. I can see it being an issue for bad pcs. Nothing you can't prepare for, though, if you don't have a choice.

**Comment by ZhilkinSerg** [comment] 2020-09-01 14:16
> 
> 
> Just tried your save on a mediocre pc and it takes between one and two seconds after loading. I can see it being an issue for bad pcs. Nothing you can't prepare for, though, if you don't have a choice.

I think there are would be many more other performance related issues if your character managed to gather 100 maps as it should be a pretty big save.

**Comment by ZhilkinSerg** [comment] 2020-09-01 14:16
Closing as non-reproducible anymore.

**Closed** 2020-09-01 14:16 UTC
Labels: <Bug>, Code: Performance, Items / Item Actions / Item Qualities
