### ISSUE TITLE
Filthy leather jacket can be crafted to a clean vest with 5 clean leather patches

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20357] opened 2017-02-23 15:53 UTC

**Comment by Night-Pryanik** [comment] 2017-02-23 16:12
At the moment filthy materials effectively are just clean materials with `(filthy)`suffix.

**Comment by kevingranade** [comment] 2017-04-13 20:31
Duplicate of #20356

**Closed by kevingranade** 2017-04-13 20:31 UTC
