### ISSUE TITLE
Game often crashes when waking up.

### ISSUE THREAD

**Issue by Confusum** [CleverRaven/Cataclysm-DDA#30755] opened 2019-05-22 17:38 UTC
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3208608/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3208609/debug.log)

Game crashes often when waking up from sleeping. This does not always happen, but when it does it always happens about the moment you'd expect your character to wake and appears to be always reproducible when sleeping in the same furniture that causes the crash. My run-ins involve chairs more often than beds but both have caused crashes.
1. Sleep somewhere comfortable (like the bed provided in the RV)
2. Wait for game to crash.
3. Sleep in same place if necessary and get same result.

EDIT: After several hours of play I've begun to notice that crashes cause my character to forget his combat stance (switching to 'no stance
 after a reload) and also 'forget' reading books (that is, they turn back to red). However, he keeps skill gains and martial arts learned from those books. 

# Expected behavior
Expected game to not crash upon waking up.

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3208625/debug.log)

 - OS: Windows 10
 - Game Version: 0.D-3343-g3f52a39
 - Graphics version: Tiles
 - Mods loaded: dda, simplenutrition. MMA. manualbionicinstall,nofilthyclothing, medieval and historic content, disableNPCneeds,brightnights,craftablegunpack,extendedrealisticguns,icecoonsarsenal,crazycataclysm,safeautodoc, StatsThroughSkills]

^Should be in debug folder 
# Additional context
CRASH LOG FILE: config/crash.log
VERSION: 0.D-3304-gc5fd74f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x56EA15[cataclysm-tiles.exe+0x16EA15]
    @0x56F4E2[cataclysm-tiles.exe+0x16F4E2]
    SMPEG_error+0x4B034@0xE8CB20[cataclysm-tiles.exe+0xA8CB20]
    _C_specific_handler+0x98@0x7FFA53478068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFA5362477F[ntdll.dll+0xA477F]
    RtlWalkFrameChain+0x14BF@0x7FFA53584BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFA536234EE[ntdll.dll+0xA34EE]
    @0xBD5140[cataclysm-tiles.exe+0x7D5140]
    @0x570CE5[cataclysm-tiles.exe+0x170CE5]
    @0xBD4930[cataclysm-tiles.exe+0x7D4930]
    @0x6945B5[cataclysm-tiles.exe+0x2945B5]
    IMG_LoadWEBP_RW+0x5221E8@0x14A0B78[cataclysm-tiles.exe+0x10A0B78]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA530B7974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFA535EA271[ntdll.dll+0x6A271]

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3208616/save.zip)

**Comment by neitsa** [comment] 2019-05-23 10:46
I didn't look at your save file yet, but just a few questions:

- Do you have an internal chronometer CBM?
- Does it crash when you set an alarm to wake you up?

**Comment by Confusum** [comment] 2019-05-23 15:45
Yes, I do have an internal chronometer, and yes it does crash when I set an alarm to wake up. I do admit that on previous versions of the experimental build I didn't see this crash, but I also didn't have an Internal Chronometer at the time.

**Comment by neitsa** [comment] 2019-05-23 16:13
Ok, thanks for the feedback!

Duplicate of #30522

**Comment by ifreund** [comment] 2019-05-23 16:41
Closing as a duplicate

**Closed by ifreund** 2019-05-23 16:41 UTC
