### ISSUE TITLE
Game crashes if you try to shoot 

### ISSUE THREAD

**Issue by mlgnestor** [CleverRaven/Cataclysm-DDA#74638] opened 2024-06-17 16:08 UTC
### Describe the bug

Game crashes if you use careful aim, precise aim, and use the period shoot function with firearms

### Attach save file

[Funny Moment 2-trimmed.tar.gz](https://github.com/user-attachments/files/15873875/Funny.Moment.2-trimmed.tar.gz)

### Steps to reproduce

Use the gun, game crashes

### Expected behavior

Not crashing

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: cdda-experimental-2024-06-04-0517 02d16e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/15873902/debug.log)

**Comment by FlyingSpaceRhino** [comment] 2024-06-18 03:30
As the game version is 2024-06-04-0517, possibly a duplicate of #74308 and fixed by #74315 ?

**Comment by RenechCDDA** [comment] 2024-06-21 02:55
Yep, outdated version. You can comment here if you still experience this issue on the latest version, and this can be reopened.

**Closed by RenechCDDA** 2024-06-21 02:55 UTC
Labels: (S1 - Need confirmation)
