### ISSUE TITLE
Refugee Center Merchant quest bugs the trade window balance when he shares equipment with you.

### ISSUE THREAD

**Issue by username-isAlready-taken** [CleverRaven/Cataclysm-DDA#20849] opened 2017-04-15 13:58 UTC
How to reproduce: At the refugee center, when you accept the quest from the merchant to clear the back bay of zombies, convince him to share equipment with you. You will get a random piece of his inventory for free.

The problem: Whenever you open the trade window with the merchant after receiving free equipment, your trade balance will initially be $0 - (value of received item). This leaves you with a cost even though no items have been selected in either panel of the trade window. Selecting items in either panel adjusts the cost/profit appropriately. But the next time you do a trade, the cost will be there again.

[Example from the latest experimental build Win x64: 0.C6394](http://i.imgur.com/1ku767W.png)
* notice how there is an initial cost for the player even though no items were selected. 
* the random item the Merchant shared in the above example was the crowbar. Notice that the item value does not exactly match the balance discrepancy. I have reproduced this bug several times, and more valuable items being shared by the merchant do indeed incur a larger initial cost in future trades.
* I have not found a way to make this initial cost go away. You can't seem to pay your "debt" with other items. The next trade will just start at the same initial cost.
* This bug can become a real issue if the merchant decides to share a very valuable item.

**Comment by Leland** [comment] 2017-08-24 03:19
Duplicate of #18893, combining.

**Closed by Leland** 2017-08-24 03:19 UTC
Labels: Bug, Confirmation Needed, Mission, NPC
