### ISSUE TITLE
Deconstructing wire fences isn't clear; player who expects the Deconstruction menu will be confused.

### ISSUE THREAD

**Issue by ShadowDragon8685** [CleverRaven/Cataclysm-DDA#22545] opened 2017-12-03 04:05 UTC
This isn't a bug, but it's not clear to the player that there is a way to deconstruct a wire fence without resorting to bashing it. The player would tend to expect that it would be done from the deconstruction menu, when in fact you need to [a]ctivate a toolbox or hacksaw.

I would suggest that perhaps "deconstruct metal item" with a requirement of metal cutting be added to the Constructions menu, so a player who has been trained to expect that menu for interacting with world furniture objects will be able to do so.

**Comment by Night-Pryanik** [comment] 2017-12-14 04:10
The same could be suggested for "deconstructing" metal bars or window with bars through your "deconstruct metal item" recipe. But honestly I'm perfectly fine with cutting metal rather than "deconstructing".

**Comment by Night-Pryanik** [comment] 2018-01-11 19:57
The issue is indeed resolved by #22594.

**Closed by Night-Pryanik** 2018-01-11 19:57 UTC
Labels: Crafting / Construction, Information / Interface, Suggestion (Discuss)
