### ISSUE TITLE
NPCs keep causing game errors

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#49830] opened 2021-07-10 23:09 UTC
### Describe the bug

Every time I give my NPCs multiple melee weapons, or virtually any other items, they throw them instead of using the weapon as a melee weapon, causing a game error in the process.

### Steps To Reproduce

Give an NPC multiple melee weapons, such as a combat knifes. Go up to a enemy, cause error.

In vanilla, NPCs still throw their melee weapons away, but hte game doesn't error.

### Expected behavior

The NPC should use melee weapons as melee weapons, even if the damage from throwing the weapon is respectable. Also, I wouldn't expect this to cause an error, but the error will likely be fixed soon.

### Screenshots

![image](https://user-images.githubusercontent.com/6434568/125178319-8e15bd00-e198-11eb-896c-12798de24055.png)
![image](https://user-images.githubusercontent.com/6434568/125178323-92da7100-e198-11eb-9fcb-39980620f412.png)
![image](https://user-images.githubusercontent.com/6434568/125178329-95d56180-e198-11eb-9c88-6f34b570ddd8.png)
Aftermath
![image](https://user-images.githubusercontent.com/6434568/125178332-9ff76000-e198-11eb-8333-a90313610921.png)

### Versions and configuration

- OS: Windows 10
- Game Version: 2021-07-10-1214
- Graphics version: tiles
- Ingame language: American English
- Mods loaded: 
      [
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "secronom",
  "secronom_lore_expansion",
  "realdarkskies",
  "MMA",
  "MMA_Mods_Extension",
  "adv_gear",
  "aftershock",
  "amplified_players_features",
  "Arcana",
  "ArmUpSurvEx",
  "arsenal_breach",
  "Arts' Guns",
  "battle_maid",
  "Bootleg_Walkers",
  "crt_expansion",
  "Cata++",
  "Dorf_Life",
  "dried_fruits",
  "ExArch",
  "growable-pots",
  "Gourmand'sGraces",
  "magiclysm",
  "Medieval_Mod_Reborn",
  "Mining_Mod",
  "MST_Extra",
  "mutant_animals",
  "mutant_insects",
  "Mutation_Changes",
  "sees_player_hitbutton",
  "sierra_madre",
  "Tankmod_Revived",
  "vamp_stuff",
  "WildLiving",
  "sarcophagi_access",
  "vamp_stuff+arcana",
  "recruitment_options",
  "fuji_mpp",
  "More_Military",
  "no_cbm_slots",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "No_Fungi",
  "pneumo_fun",
  "blazemod",
  "Heavy miners",
  "EngineeringEssentials",
  "bow_opness",
  "More_Survivors_Stories",
  "wandering_masters",
  "AAA",
  "fallout",
  "Locked_and_Loaded",
  "demon_spider_a",
  "modern_weapon",
  "crazy_labs",
  "modular_turrets_no_blacklist",
  "Salvaged_Robots",
  "light_weariness",
  "extra_mut_scens",
  "food_irradiator",
  "hydroponics",
  "zets_hair_extensions_undead",
  "more_locations",
  "zets_hair_ext_more_locations",
  "morlock_village",
  "No_Rail_Stations",
  "WHALEYHAIR_UDP",
  "realdarkskies_faction_balance",
  "advtech",
  "bioco"
]

### Additional context

https://www.dropbox.com/s/41mnje817dsbzvk/Piercy.7z?dl=0
Running Kenen's latest modpack with UDP tileset mods.

https://www.dropbox.com/s/ifphqgzmw49yktm/High%20Shoals.7z?dl=0
Vanilla.

**Comment by actual-nh** [comment] 2021-07-11 03:18
#49834 is almost a duplicate of this one - no error mentioned for that one.

**Comment by GoLoT** [comment] 2021-07-11 22:23
FWIW I managed to get similar errors in a refugee center when the barred zombies got out and swarmed the center. NPCs started running around shooting the zombies but acting weird when in close range. Then I started getting the "tried to fire non-gun" error for some of them.

**Closed** 2021-07-26 23:25 UTC
Labels: <Bug>, Melee, NPC / Factions
