### ISSUE TITLE
Survivor Harness  Deleted items inserted into it.

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#40153] opened 2020-05-04 20:27 UTC
# Describe the bug

I tried to put a few items into this and they didn't appear inside or in their old clothing. 

# Steps To Reproduce

1. Put an item like a flashlight in clothing, I had it in my survivor suit.
2. Select the survivor harness, and hit i, to insert the item. Select the item and hit return.
3. Item doesn't appear in harness or suit. I cant find it in the advanced inventory menu either.

# Expected behavior

The harness also acts as a sheath, so I suspect it has something to do with the sheathing interfering with the new nestling mechanics. The harness and other similar items should be able to identify what should go in the sheath/holster vs the pockets. Basically the items should not be deleted, and we should have some differentiation between holsters and pockets.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1737-g11714a3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

**Comment by FuelType-Memes** [comment] 2020-05-04 20:35
Please use the template to file the bug report, it is there for a reason

You bug may be a duplicate of #40115 please use the search function before posting a bug report

**Comment by Orange01gaming** [comment] 2020-05-04 21:18
Oh sorry I thought I did use it. That is so weird, I can see it when I go to edit, but the steps and build etc are not showing up by default...

**Closed** 2020-05-05 18:55 UTC
Labels: (S3 - Duplicate), <Bug>, Items: Containers
