### ISSUE TITLE
Vehicle washing machine has no storage space.

### ISSUE THREAD

**Issue by Omen535** [CleverRaven/Cataclysm-DDA#62720] opened 2022-12-13 01:47 UTC
### Describe the bug

I started to craft the components for the washer starting with the 60L tank and when I thought I had all the parts for the washer it said that I was missing a 60L tank, log said that there was no space on worktable so it put the tank on the ground and after looking by using the advance inventory it was not there, so I made a second 60L tank and made sure to put the tank into a cargo carrier right after crafting it, then I finished crafting the washer and after I installed it into my vehicle I noticed that the storage on it said 0.00/0.00 qt. I get the option to try to start it when on the menu it says that it will take 1.5 hrs but if I click it it will say that it is empty so there is no reason to start it.

### Steps to reproduce

1. crafted 60L tank on worktable that is inside vehicle , game stated there was no room on worktable so the 60L tank was put on the ground.
2. crafted small electric motor was left on worktable.
3. went to craft washing machine, started craft the was told was missing 60L tank
4. Looked at every location in the advance inventory and moved vehicle forward to confirm that 60L tank no longer exists.
5. craft second 60L tank and make sure to grab it off ground an put it into cargo carrier in vehicle.
6. finish crafting washing machine with new 60L tank.
7. grabbed washing machine and scrap metal from worktable.
8. Installed washing machine into available space inside vehicle.
9. notice that washing machine has storage 0.00/0.00 qt.

### Expected behavior

I expected the washing machine to have some sort of storage to put items into.

### Screenshots

![image](https://user-images.githubusercontent.com/120431663/207204721-92effa42-2be5-4c5a-b4a0-9a0b7c591497.png)

### Versions and configuration

OS: windows 10
Game version : b758c62
Graphics version : tiles
Ingame language : English
Mods Loaded : disable npc needs, no fungal growth, bionic professions, make bows great again, aftershock, pixel's various fuckery, alternative map key, easy proficiency, portal storms ignore npcs, speedy dex, stats through kills, stats through skills

**Comment by gettingusedto** [comment] 2022-12-13 01:51
Related to #62668

**Comment by Night-Pryanik** [comment] 2022-12-13 05:45
Duplicate of #62668.

**Closed by Night-Pryanik** 2022-12-13 05:45 UTC
Labels: (S1 - Need confirmation)
