### ISSUE TITLE
Ammo description

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#44160] opened 2020-09-13 21:16 UTC
# Describe the bug
Most ammo in game (9x19, 5.56, .22 etc) have "damage multiplier" line in their description instead of "damage" value.

# Steps To Reproduce
check ammo description.

# Expected behavior
Expected to have "damage" stat shown in description. Not "damage multiplier".

# Screenshots
![wrong](https://user-images.githubusercontent.com/58046029/93028863-7f658480-f61f-11ea-8cf0-1cd23c722c4c.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5882-g98879b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by anothersimulacrum** [comment] 2020-09-13 21:37
Duplicate of #41564

**Closed by anothersimulacrum** 2020-09-13 21:37 UTC
Labels: (S3 - Duplicate)
