### ISSUE TITLE
Should some world objects (like car panels) be edges instead of squares?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45083] opened 2020-10-26 21:00 UTC
# Is your feature request related to a problem? Please describe.
Cars sometimes have odd shapes because side panels take up the same amount of space as everything else.

This also happens with walls and a couple other things, but those are easier to gloss over

# Describe the solution you'd like
I've been thinking about the nature of the odd shape of cars (including how they distort and create impossible openings when at diagonals and I think the issue might be coming from the fact that "walls" are blocks instead of edges between blocks.

If they were edges, then the game might be able to recognize contiguous edges and draw half occupied squares like [/] when a car is at a diagonal

There are a few other places this would have important effects like doors, windows, fences, railings, and a few others but I think cars will be the most obvious

I suspect there may need to be some underlying changes to the mapping engine for this to work, and I'm not 100% sold on this idea but I wanted to pose it for discussion

# Describe alternatives you've considered
not sure

# Additional context
very long term idea, and may need a fair amount of discussion

**Comment by ZhilkinSerg** [comment] 2020-10-27 09:29
```
 ┌-┐
 /#/
└ -┘
```

is not better than

```
  ┌-┐
 |#|
└ -┘
```

**Comment by natsirt721** [comment] 2020-10-27 15:56
I think the idea would be more like:
```
 ┌-┐
 /|#|/
└-┘

**Comment by ZhilkinSerg** [comment] 2020-10-27 16:55
Why would single symbol should be replaced with two symbols?

**Comment by Xpyder** [comment] 2020-10-28 20:36
> ```
>  ┌-┐
>  /#/
> └-┘
> ```
> 
> is not better than
> 
> ```
>   ┌-┐
>  |#|
> └-┘
> ```

It can be if the /#/ version can be enclosed rather than having random magic openings where there shouldn't be

**Comment by ZhilkinSerg** [comment] 2020-10-28 20:44
What do you mean by "enclosed"?

**Comment by Xpyder** [comment] 2020-10-29 00:07
If you take your mini car example:
When vertical or horizontal you can't just walk through the side panel
But if you turn it at an angle, suddenly you can see and walk through the side of the car

By Enclosed I mean the game engine could recognize that panel should be contiguous and prevent the bugged openings

**Comment by ZhilkinSerg** [comment] 2020-10-29 00:28
So, it is not about visuals, but a duplicate of #5684.

**Closed by ZhilkinSerg** 2020-10-29 00:28 UTC
Labels: <Suggestion / Discussion>, Vehicles
