### ISSUE TITLE
Survivor utility belt loses all its qualities when something is in its holster

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#44961] opened 2020-10-19 22:06 UTC
As described in the title, a survival utility belt works fine, but it stops when something is in a holster.

Normal behavior
![image](https://user-images.githubusercontent.com/6452938/96516672-4482ec00-1270-11eb-8d4e-d85c772e69b2.png)
![image](https://user-images.githubusercontent.com/6452938/96516706-4fd61780-1270-11eb-9458-100575fc649f.png)

BUG
![image](https://user-images.githubusercontent.com/6452938/96516775-68dec880-1270-11eb-8c8a-c3175e2e6083.png)
![image](https://user-images.githubusercontent.com/6452938/96516811-72683080-1270-11eb-8180-eeabdeeddbab.png)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7009-g17557d4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment] 2020-10-19 23:05
Duplicate of #42702

**Closed by ZhilkinSerg** 2020-10-19 23:05 UTC
