### ISSUE TITLE
Installing car battery into vehicle unloads and installs from nearby battery compartment tools

### ISSUE THREAD

**Issue by UncleBenis** [CleverRaven/Cataclysm-DDA#24465] opened 2018-07-25 01:17 UTC
Game version: 7604

Operating system: win7

Tiles or curses: curses

Mods active:
More survivor tools (packaged)
Early game progression mod
Expanded archery
Stats through skills
Vehicle additions pack (packaged)
Tanks and other vehicles (packaged)

### Expected behavior
Car Battery A being installed while Tool X with a battery compartment mod containing Car Battery B is left alone.
### Actual behavior
Battery B is being unloaded from Tool X and installed into vehicle while Battery A is either dropped on the ground or disappears.
### Steps to reproduce the behavior
Load a battery compartment modded tool with a car battery and put it in the trunk, hold an identical battery in hand and attempt to install a car battery in the vehicle. With multiple modded tools it then cycles from which tools to unload on subsequent installation attempts.

**Comment by Lasiace** [comment] 2018-07-25 09:52
Can confirm this definitely happens to me as well, will upload screenshots if you guys want.

**Comment by RadHazard** [comment] 2018-07-26 00:44
This is part of a wider issue in that it's impossible to choose specifically which battery (or car part in general) you want to install.  The only way to reliably ensure the exact part you want gets installed is to hold it and drop every other identical part on the ground.

Ideally, the "select part to install" screen should use the same kind of menu as reloading currently does

**Comment by l29ah** [comment] 2019-04-26 20:12
YEAH THIS SUCKS A LOT

**Comment by Night-Pryanik** [comment] 2019-09-29 10:49
Duplicate of #21109.

**Closed by Night-Pryanik** 2019-09-29 10:49 UTC
Labels: (S1 - Need confirmation), <Bug>, Battery / UPS, Crafting / Construction / Recipes, Vehicles
