### ISSUE TITLE
eternal season issues.

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#44366] opened 2020-09-23 10:05 UTC
# Describe the bug
`if you play with eternal season temperatures don't work properly, even at the start of the game with eternal season already on, it'll just pick temperatures from to whichever season length it is set at and current day, its summer in my game, i play with eternal season on but i get summer effects. high temps, fast spoilage. etc.`

`eternal season isn't utilizing the proper temperatures.

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. start a game with eternal season on or off
2. (if you started it with it being off, turn it on and notice temps not going down if you started in winter) temperatures aren't proper to the current season

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5988-gb8bbd5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Safe Autodoc [safe_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP]
]

**Comment by ZhilkinSerg** [comment] 2020-09-23 10:58
Can you elaborate please? You issue description sounds like it is working properly now.

**Comment by ZhilkinSerg** [comment] 2020-09-23 10:59
Are you facing same issue as described in https://github.com/CleverRaven/Cataclysm-DDA/issues/26756?

**Comment by Devengel** [comment] 2020-09-23 11:45
> Are you facing same issue as described in #26756?

Yes.

**Comment by Devengel** [comment] 2020-09-23 11:46
i am trying to play on eternal winter, but the temperatures aren't correct. it's summer temps in what should be winter temps

**Comment by ZhilkinSerg** [comment] 2020-09-23 12:04
Thanks. It is clear now. I will close this ticket then as duplicate and mark #26756 as confirmed.

**Comment by ZhilkinSerg** [comment] 2020-09-23 12:04
Duplicate of #26756

**Closed by ZhilkinSerg** 2020-09-23 12:04 UTC
