### ISSUE TITLE
Crash when alt-tabbing out of fullscreen CDDA

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#22331] opened 2017-11-02 17:04 UTC
Game version:
0.C-24810-g7e56bbe - Build 6905 (tiles)

Operating system:
Windows 10

### Actual behavior
The window flickers for a few moments then the game crashes.

### Steps to reproduce the behavior
1. Start CDDA in fullscreen mode (doesn't seem to happen with a borderless window).
2. Alt-Tab to another application
3. Watch it crash

I looked for a log, but couldn't find one. If someone can point me into the right direction I'm happy to provide it.

**Comment by Treah** [comment] 2017-11-02 19:47
I get this problem too in the linux client from time to time when I close another window on the system oddly..

**Comment by Leland** [comment] 2017-11-02 19:51
Other alt-tab issues (not duplicates): #14729, #14023, #6928

**Comment by Voqar** [comment] 2017-11-06 00:02
I CTD on alt-tab on windows 10 too with full screen.  Full screen windowed mode works fine.

**Comment by Leland** [comment] 2018-02-19 17:40
Closing due to lack of repro and time.

If one comes up with a set of steps to reliably reproduce please either note that here and I will reopen, or just make a new issue and link to this one.

**Closed by Leland** 2018-02-19 17:40 UTC
Labels: Confirmation Needed, Crash / Freeze, Windows
