### ISSUE TITLE
Entrenching tool fill pits for free

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#43062] opened 2020-08-20 09:20 UTC
# Describe the bug

When you "a"ctivate a entrenching tool and choose the "fill pit / tamp ground", you can fill up pits without needing to use anything for this.

Is this intended?

# Steps To Reproduce

1 - find or dig a pit
2 - "a"ctivate an entrenching tool and choose the option "fill pit / tamp ground"
3 - notice that you filled the pit or part of it without needing to use anything

# Expected behavior

As the option to "fill a pit" in the construction menu use some soil to fill a pit, it is supposed that any means to fill it you would need some kind of material for this. It feels really strange to fill a pit for free like this.

# Screenshots

Not applicable.

# Versions and configuration

I am using using the CDDA 0.E-b10900 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

There should be ways to efficiently fill pits with less dirt, like for example using a frame or planks and then covering it with way less dirt.

We also need other ways to deal with pits like just putting some planks over it or using any other form of makeshift bridge. As survivors for sure we could pull some foldable makeshift bridges that we can carry with us and spring it open really fast as need to cross small gaps, and then take it back. Of course we can always use "foldable vehicles" but it would be nice to have a dedicated tool for this, like one that use the extra-light frame or something.

**Comment by BQurious** [comment] 2020-08-20 20:18
> We also need other ways to deal with pits like just putting some planks over it or using any other form of makeshift bridge.
Are you saying you want something, like putting planks, in addition? I'm on 0.E-2 and inspecting a deep pit with planks nearby gives you a prompt to place it as a bridge

**Comment by Duck13Tales** [comment] 2020-08-21 00:31
Didn't know. I will try it! But it would be great if this was an option for any 1 tile gap for example, not only pits. 

If we could take a portable bridge and place and recover from wherever needed and would be really good. I am sure that as a survivor we could build this if we had the need.

**Comment by Night-Pryanik** [comment] 2021-04-15 19:07
Duplicate of #29303.

**Closed by Night-Pryanik** 2021-04-15 19:07 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
