### ISSUE TITLE
Debug warning: Vehicle part cache indicated vehicle not found

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21966] opened 2017-09-22 21:18 UTC
Game version: 8a96896720

Operating system: linux

Tiles or curses: tiles

Mods active:[
  "dda",
  "More_Survival_Tools",
  "realguns",
  "Urban_Development",
  "more_locations",
  "boats",
  "filthy_morale",
  "no_npc_food"
]

### Expected behavior

No debug warning.

### Actual behavior

![](https://i.imgur.com/csdnX4w.png)

### Steps to reproduce the behavior
1. load attached save game, [gore.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1325884/gore.zip)
2. walk back and forth a few squares

**Comment by Firestorm01X2** [comment] 2017-09-30 12:42
Got same message on Windows:
 src/map.cpp:1159 [const vehicle* map::veh_at_internal(const tripoint&, int&) const] vehicle part cache indicated vehicle not found: 0 -1 0

**Comment by goron111** [comment] 2017-10-04 16:52
Had the same problem with 0.C-24247-g7a11edc (tiles) Windows 64-bit
This is probably a duplicate of #20374

**Comment by ZhilkinSerg** [comment] 2018-04-02 18:16
Should be fixed with #22091.

**Closed by ZhilkinSerg** 2018-04-02 18:16 UTC
Labels: CDDA: Vehicle, OS: Linux
