### ISSUE TITLE
Fish fillets sometimes have zero calories.

### ISSUE THREAD

**Issue by Vakaret** [CleverRaven/Cataclysm-DDA#51361] opened 2021-09-04 15:32 UTC
### Describe the bug

As stated, fish fillets sometimes are seemingly made of air, with no calories but their respective quench/joy modifiers, this translates to any food derivating from those fillets being a time waste since they also have no calories, this bug seems to be at random but its significantly more common when doing anything in batch with the fish, like butchering in batch or cooking in batch.

### Steps To Reproduce

1. Make a character with a fishing rod.
2. Start fishing in a river. (Not sure about ponds, maybe it has to do with an especific type of fish found in rivers)
3. Butcher a bunch of the fish and cook them together.
Its probable in not gonna happen the first few times, as I said, it seems like the calories dissapear at random.

### Expected behavior

The fish is supposed to have some sort of caloric value, I dont think its intentional that eating cooked fish is sometimes less nutritious than eating a dandelion.

### Screenshots

![Bug](https://user-images.githubusercontent.com/90102994/132099694-6efc19a5-611e-4424-95c2-ad07ed336c5e.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 8bab31e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex]
]

### Additional context

It seems like if you cook fish with no caloric value together with fish that has calories the calories dissapear from the non-bugged fish, making the entire batch worthless.

**Comment by ghiknt** [comment] 2021-10-14 00:12
In looking at why this happens I also question why after reload it is +520 calories instead of +260.

- .../json/items/comestibles/carnivore.json's definition for ```"id": "fish_cooked"``` does a ```"copy-from": "fish"``` which is ```"calories": 260```
- The crafting page says it should be "Calories (kcal): 0-260"

**Comment by hexagonrecursion** [comment] 2022-01-04 20:38
This issue appears to be a duplicate of #52676

**Closed** 2022-02-03 23:25 UTC
Labels: (S2 - Confirmed), Items: Food / Vitamins, Monsters
