### ISSUE TITLE
Crash when driving through certain area

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#34398] opened 2019-10-02 13:29 UTC
# Describe the bug

Driving my RV down a road then suddenly I crash, and lose a bit of progress. I am back at my house, do the same things I did before, and go back to the road (quicksaving beforehand). It crashes again.

I ended up trying to go up a road I've gone down before, up north, and it crashed again. I think it's a vertical line that, if I cross, the game crashes.

# Steps To Reproduce

1. [Download my save.](https://github.com/CleverRaven/Cataclysm-DDA/files/3681271/Survivorland.zip)
2. Accelerate forward (I did so at 20 mph).

# Expected behavior

Not crash. I expect this to happen, because last time I checked, crashing wasn't a feature.

# Versions and configuration

- OS: Microsoft Windows 10 Home
    - OS Version: 10.0 1903 Build 18362
- Game Version: 0.D-8159-g6363709 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    Jury-Rigged Robots [jury_rigged_robots],
    Mythical Martial Arts [MMA],
    Hydroponics [hydroponics],
    Aftershock [aftershock],
    Classes and Scenarios Mod [more_classes_scenarios]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3681280/config.zip)

**Comment by ZhilkinSerg** [comment] 2019-10-02 20:28
Duplicate of #34397

**Closed by ZhilkinSerg** 2019-10-02 20:28 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>

**Comment by zachary-kaelan** [comment] 2019-10-03 11:38
I didn't see how the two were related. Would it be the zombies attacking objects?

**Comment by ZhilkinSerg** [comment] 2019-10-03 11:50
> 
> 
> I didn't see how the two were related. Would it be the zombies attacking objects?

Creatures going into fields.
