### ISSUE TITLE
Game crashing when repairing an item using a plugged-in tool without batteries

### ISSUE THREAD

**Issue by Numbuh474** [CleverRaven/Cataclysm-DDA#67062] opened 2023-07-21 03:28 UTC
### Describe the bug

When repairing using a tool like a soldering iron or arc welder, the game crashes if the item doesn't have a battery in it and you attempt to repair while it's plugged into the grid.

### Attach save file

N/A, trivially reproducible.

### Steps to reproduce

1. Obtain a tool that can repair stuff and a damaged stuff.
2. Set up a power grid with some power in it.
3. Remove the tool's battery if it has one.
4. Use the tool. The repair menu comes up as though the tool has available charge.
5. Select the item for repair. The game will crash at this point.

### Expected behavior

Tools don't care if they have a battery if they are plugged in.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3116-gf43a3a8a6c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by RenechCDDA** [comment] 2023-07-21 03:29
Duplicate of #66944

**Closed by RenechCDDA** 2023-07-21 03:29 UTC
Labels: (S1 - Need confirmation)
