### ISSUE TITLE
Dandelion greens with water from wooden  keg

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#22603] opened 2017-12-14 07:21 UTC
Game version: (7004)       0.C -25440-g217f504

Operating system: Windows Xp 32

Tiles or curses: Tiles

Mods active: DDA, Filthy clothing, disable NPC needs, simplified nutrition, generic guns,  makeshift items mod, more survival tools,  dinomod, more buildings, urban development, boats.

### Expected behavior 
Clean water from  wooden keg should be used when cooking Dandelion greens.

### Actual behavior 
Clean water was not used

### Steps to reproduce the behavior 
I had 117 clean water in the wooden keg. Stood 5 spaces away in an open door frame, and batch cooked 10x dandelion greens. I used a pot. I did not have any other water nearby. I tried a couple times while working on my cooking level, the first 2 tries I did not make them ,but nothing was lost. The third time, my level cooking level went to 3 and I made the 10x dandelion greens, but no water was used. 

I have tested this a few times afterwards and the same thing happens.

**Comment by kettleswordfang** [comment] 2017-12-20 08:50
i believe this is working as intended.

` Cooked leaves from wild dandelions. Tasty and nutritious.`
it needs a tool with `food cooking quality 2`, not boiling - seem like this is pretty much just dandelions cooked like you would spinach leaves, so not water would be used up

**Comment by ituluwituluwzev** [comment] 2017-12-20 09:42
The recipe requires water, so it should use water.

**Comment by Night-Pryanik** [comment] 2017-12-20 10:31
Duplicate of #19483.

**Closed by Night-Pryanik** 2017-12-20 10:31 UTC
Labels: Bug, Confirmation Needed
