### ISSUE TITLE
Instant crop.  Just add fertilizer.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13628] opened 2015-09-22 16:54 UTC
If you use fertilizer on a crop and then (save&load) or (leave&return so that the crop is outside the reality bubble), then crop will instantly be ready to harvest.  Tested this with both commercial and liquid fertilizer with 3 different crops.  Version 3706

**Comment by BevapDin** [comment] 2015-09-22 18:30
I can't reproduce this here. What's your season length? It might have been caused by the bug fixed with #13607 (if your season length is longer than the default), which is only a day or so newer than your version.

**Comment by DodgingRain** [comment] 2015-09-22 18:58
It was 91.

From your prompting.  I did some variable testing.

Default 14 days.  Default 100 construction speed has no effect.
91 days.  Default construction speed has no effect.
Default 14 days.  1000 construction speed resulted in plant instant growing one stage but not ready to bloom and require another dose of fertilizer.
91 days. 1000 construction speed resulting in instant harvestable plant.

**Comment by wito** [comment] 2015-10-20 12:26
This is likely an artifact of how the plant system works; what's happening is likely that the plant has been growing for some time already, so that it's current growth time is between the time at which it turns over without fertilizer and the time it turns over with fertilizer.

Basically, the plant system (AFAIK still) works like this: Every time plant furniture is loaded, it checks the bday of the seed lying inside the furniture, and if the current time is greater than the birthday + the growth time, it changes the plant furniture to the appropriate stage. If fertilizer is present, this reduces the growth time, irrespective of _when_ it is added. So if the time the seed has been there is greater than the time it would take for the plant to sprout with fertilizer, but less than the time it would take for the plant to sprout without it, fertilizing and reloading does indeed cause the plant to sprout instantly.

Is this happening with a plant that has been growing for some time? Or a plant that is newly planted?

**Comment by DodgingRain** [comment] 2015-10-26 00:44
Completely new plants.

**Comment by mugling** [comment] 2016-09-21 15:55
Closed as unconfirmed

**Closed by mugling** 2016-09-21 15:55 UTC
Labels: Bug, Confirmation Needed
