### ISSUE TITLE
Json errors upon loading character. From #64922 likely

### ISSUE THREAD

**Issue by Rimplestilt** [CleverRaven/Cataclysm-DDA#65162] opened 2023-04-18 13:09 UTC
### Describe the bug

Issue began in 2023-04-09-0816 for me. Likely #64922 specifically. All errors seem to be in flexbuffer_json.cpp

So many errors. A few of the What feels like 100 messages i have to get through each time i load now.  May just be an issue on my end?

![Screenshot_20230418-090643_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/232787138-e23d82b3-d453-4dc1-b0f8-0674049c7b58.jpg)
![Screenshot_20230418-090707_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/232787158-32c84755-5989-4150-a0d1-66d76f09f060.jpg)
![Screenshot_20230418-090713_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/232787188-0bc79dda-0123-4e7e-9ac5-811e5783f36e.jpg)

### Attach save file

N/a? Happens to any character i play or create

### Steps to reproduce

start game

### Expected behavior

No errors

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-S136DL; Release: 12; Incremental: S136DLUDU2BVE8; 
- Game Version: 060fe4f [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm]
]

**Comment by Theawesomeboophis** [comment] 2023-04-23 18:16
/confirmed.

**Comment by Theawesomeboophis** [comment] 2023-04-23 18:17
Confirmed, doesn't occur on windows which is strange.

**Comment by firegaul2077** [comment] 2023-04-25 22:41
yeah, I compiled this on a rpi4 Ubuntu 22.04 64bit with tiles and it worked fine...  but android version keeps popping the same issue.

**Comment by Empyrean-Heaven** [comment] 2023-05-24 10:32
Still a problem, more than a month later. ㅠㅠ

**Comment by mqrause** [comment] 2023-06-03 20:38
Is there some other, different error reported before all these? There was a very similar issue before which supposedly was fixed by #65477. But that requires an actual error to trigger this kind of spam of not actual errors.

**Comment by Ramza13** [comment] 2023-06-03 21:00
So I have this and noticed that it is a result of "//" fields in the data.  Remove those and it goes away.

**Comment by RenechCDDA** [comment] 2023-06-03 21:04
The latest linked issue actually included a debug log and I found an interesting entry after scrolling down for a bit.

```22:45:45.723 ERROR : (error message will follow backtrace)#01: 0xb45a87d6 DebugLog(DebugLevel, DebugClass)
#02: 0xb45a8330 realDebugmsg(char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#03: 0xb4289024 void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
#04: 0xb46e948e JsonObject::error_skipped_members(std::__ndk1::vector<unsigned int, std::__ndk1::allocator<unsigned int> > const&) const
#05: 0xb46e91be JsonObject::report_unvisited() const
#06: 0xb421239a JsonObject::~JsonObject()
#07: 0xb47f6cb6 DynamicDataLoader::load_all_from_json(JsonValue const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, loading_ui&, cata_path const&, cata_path const&)
#08: 0xb47f6af0 DynamicDataLoader::load_data_from_path(cata_path const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, loading_ui&)
#09: 0xb4706006 game::load_packs(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::vector<string_id<MOD_INFORMATION>, std::__ndk1::allocator<string_id<MOD_INFORMATION> > > const&, loading_ui&)
#10: 0xb46f8110 game::load_world_modfiles(loading_ui&)
#11: 0xb46f7c12 game::setup()
#12: 0xb4a2619e main_menu::new_character_tab()
#13: 0xb4a24186 main_menu::opening_screen()
#14: 0xb4a1d8c8 SDL_main
#15: 0xb5e06e2a Java_org_libsdl_app_SDLActivity_nativeRunMain
Backtrace emission took 0 seconds.
```
Of the reported instances that listed mods both seem to have included magiclysm.

(Ramza above also shared some further insights on this happening so I'm going to go ahead and make it confirmed, although hunting down the exact cause is going to take some time)

**Comment by RenechCDDA** [comment] 2023-06-03 21:08
And apparently happens even outside android, so this bug is now very mysterious!

**Comment by Empyrean-Heaven** [comment] 2023-06-04 02:41
Praying for a speedy recovery, as I had been locked out of CDDA for over a month now.

**Comment by Evgehas** [comment] 2023-06-19 10:02
Hi guys. No one knows if work is underway to eliminate this error?

**Comment by akrieger** [comment] 2023-06-25 21:36
One thing standing out to me is repros are on 32 bit, not 64 bit. Possibly I screwed up the math somewhere mixing size_t and uint64_t. I'll go check again.

**Comment by akrieger** [comment] 2023-06-26 04:52
Yep reproduces instantly in a 32 bit build on Windows. I'll try to fix it this week.

**Comment by akrieger** [comment] 2023-06-26 05:32
Nevermind. Found the issue. Not sure why it's not an issue for 64 bit builds, but that's something I'll debug later.

**Comment by Empyrean-Heaven** [comment] 2023-06-26 10:58
Has this been fixed? Or is my good sir akrieger cooking up a patch as we speak?

**Comment by akrieger** [comment] 2023-06-26 13:57
Still debugging why it doesn't cause the same issue on 64 bits. It's maybe a oneline patch but the behavior discrepancy is disturbing so I want to find out what other bug is hiding.

**Comment by RenechCDDA** [comment] 2023-06-26 14:13
Thanks for taking a look!

**Comment by akrieger** [comment] 2023-06-26 16:23
So, ok, my hypothesis right now:

# Primary issue
This boolean check is inverted https://github.com/CleverRaven/Cataclysm-DDA/blob/f13d34ade880ad7b8f291a7e7dbd6103e6b86f4e/src/flexbuffer_json.cpp#L265

It should be `if( !( block & mask ) ) {` like down here https://github.com/CleverRaven/Cataclysm-DDA/blob/f13d34ade880ad7b8f291a7e7dbd6103e6b86f4e/src/flexbuffer_json.cpp#L276

Because it is inverted it will add every visited member to the unvisited members vector. The block bits are 1 if the member was visited, the mask is a single bit set mask to test each in sequence.

# Why does it only happen on 32 bit
Many things must be true to hit the problem code.
1) There must be at least one unvisited member in Json instance. Typically this happens from comment members in objects. Arrays do not have comment members.
2) There must be more than `uintptr_t` bits worth of members in the object. On 32 bit arches that's 32, 64 for 64 bit arches. There are two separate loops for iterating through 'whole blocks' of the bitset and through 'partial blocks' of the bitset. If there's more than 32 or 64 members, then there's going to be more than 1 block in the bitset, so there's at least one whole block. The inverted check is in the 'whole block' loop.
3) Hypothesis: there are no objects with more than 64 members, so the whole block loop is never entered on 64 bit platforms.

# Why does removing comments fix it
If the entire bitset is filled, then the entire function is skipped from this check https://github.com/CleverRaven/Cataclysm-DDA/blob/f13d34ade880ad7b8f291a7e7dbd6103e6b86f4e/src/flexbuffer_json.cpp#L255 where it tests `!visited_fields_bitset_.all()`. Since comment members are typically the only unvisited members in objects, this avoids the bad code.

Once I verify the above I'll put up a fix for the inverted test.

**Comment by akrieger** [comment] 2023-06-26 18:58
Confirmed there are no objects with >64 members *and* that have a comment member. So that clinches it.

**Closed** 2023-06-27 06:24 UTC
Labels: (S2 - Confirmed), Code: Infrastructure / Style / Static Analysis, Help Wanted

**Comment by Empyrean-Heaven** [comment] 2023-06-27 15:27
Yup it works. :D
