### ISSUE TITLE
Bunkers on the overmap the same colour as "already explored" 

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19816] opened 2016-12-20 17:08 UTC
A little nitpick, but it's a bit of a pain you can't effectively mark bunkers -- and I guess to a lesser extent, roads -- as explored using the "[E] - Toggle Explored" option in the overmap, because the explored colour is identical to their unexplored colour.. 

Any chance of getting these recoloured, or is there some game engine limitation that prevents this?

**Comment by Aivean** [comment] 2016-12-20 21:40
I think `dark gray` and `light gray` colors should be only used to mark explored tiles.

Currently there are several things that are confusing:

Military outpost:
![image](https://cloud.githubusercontent.com/assets/2865203/21368717/998df0b2-c6b8-11e6-9176-fa94691afdd6.png)

Parking lot and Mine:
![image](https://cloud.githubusercontent.com/assets/2865203/21368726/a05243a8-c6b8-11e6-8d3c-1c517d00c230.png)

Bunker:
![image](https://cloud.githubusercontent.com/assets/2865203/21368766/c3fce6aa-c6b8-11e6-85ed-c0817413244f.png)


---

Some of the tiles use light gray, which is better, but still kinda confusing:

Office and explored house:
![image](https://cloud.githubusercontent.com/assets/2865203/21368874/370f584e-c6b9-11e6-9b26-59a8436f755d.png)

Radio tower:
![image](https://cloud.githubusercontent.com/assets/2865203/21368883/439968c0-c6b9-11e6-8f69-795d85fc512c.png)

Missile silo:
![image](https://cloud.githubusercontent.com/assets/2865203/21368924/68d53862-c6b9-11e6-8166-9d1190c32561.png)

**Comment by Regularitee** [comment] 2016-12-21 23:15
Well, the simplest solution seems to be to replace all default dark grey map tiles with either light grey or white. Possibly just white, unless it's possible to tweak the colour palette of the existing light grey to make it more distinct from dark grey. (or inversely, make the dark grey darker, to differentiate it).

**Comment by codemime** [comment] 2017-01-08 00:38
Dupe of #11737.

**Closed** 2017-04-08 20:54 UTC
Labels: Duplicate, Easy-fix, Information / Interface, Suggestion (Discuss)
