### ISSUE TITLE
#White wall in the basement of a house

### ISSUE THREAD

**Issue by Nihad2004** [CleverRaven/Cataclysm-DDA#45810] opened 2020-12-04 18:40 UTC
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by Xaleth** [comment] 2020-12-04 18:45
?

**Comment by anothersimulacrum** [comment] 2020-12-04 19:33
Duplicate of #45813

**Closed by anothersimulacrum** 2020-12-04 19:33 UTC
Labels: (S3 - Duplicate), <Bug>, Map / Mapgen
