### ISSUE TITLE
Unable to craft water bug

### ISSUE THREAD

**Issue by sired22** [CleverRaven/Cataclysm-DDA#19760] opened 2016-12-14 11:16 UTC
discovered by GreenZ in chat. it appears that you are unable to craft 'Clean Water' from shallow water if a container of 'water' is in crafting distance.

http://imgur.com/a/YvTQR

the following image shows two shallow waters
the container on the ground has water in it.
i also have an empty container in my inventory.
i also have an integrated tool-set with plenty of power.

as long as that remains in my crafting range 'craft clean water' remains disabled
if i move it away i can once again craft.

**Comment by illi-kun** [comment] 2016-12-14 11:26
Duplicate of known (and I suggested fixed) issue. What version of the game do you use?

**Comment by illi-kun** [comment] 2016-12-14 11:32
PR intended to fix this is #19149.

**Comment by sired22** [comment] 2016-12-14 11:32
currently running
Version: 0.C-20202-g493825f (tiles)
Build: 6040 (3 days ago)

**Comment by mutability** [comment] 2016-12-14 13:48
That build includes 19149 so I am going to guess that the problem I noted with the fix in 19149 (that it doesn't actually avoid the overflow) is a real problem.

**Comment by kevingranade** [comment] 2016-12-17 20:08
I *can* reproduce the issue with 0.C-20224-g404d7152eb on windows built with C::B 16.01 and its bundled mingw.
I *cannot* reproduce with 0.C-20232-g3eb9b17 on linux built with gcc 6.1.1
I wrote a set of unit tests for this, but on linux so they pass, which is less than useful.

**Closed** 2017-03-18 05:11 UTC
Labels: Bug, Confirmation Needed, Crafting
