### ISSUE TITLE
sporadically failing explosive balance test

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#24785] opened 2018-08-11 13:16 UTC
```
grenade_lethal_at_5m
-------------------------------------------------------------------------------
explosion_balance.cpp:72
...............................................................................
explosion_balance.cpp:69: FAILED:
  CHECK( lethality_ratio == Approx( lethality ).epsilon( 0.05 ) )
with expansion:
  0.40667f == Approx( 0.5 )
with messages:
  samples 5
  grenade_act
  range 15
  356 survivors out of 600 targets.
  45,16,0 80, 45,17,0 45, 45,21,0 80, 45,22,0 23, 45,24,0 80, 45,26,0 8, 45,27,
  0 80, 45,29,0 42, 45,32,0 80, 45,33,0 14, 45,36,0 80, 45,37,0 20, 45,38,0 46,
  45,39,0 14, 45,40,0 9, 45,44,0 39, 44,45,0 80, 43,45,0 80, 42,45,0 80, 41,45,
  0 45, 40,45,0 80, 36,45,0 76, 35,45,0 80, 32,45,0 80, 31,45,0 80, 30,45,0 41,
  28,45,0 48, 25,45,0 18, 22,45,0 80, 21,45,0 43, 19,45,0 53, 18,45,0 80, 17,
  45,0 53, 16,45,0 80, 15,44,0 80, 15,43,0 80, 15,40,0 71, 15,38,0 23, 15,36,0
  80, 15,35,0 77, 15,34,0 80, 15,33,0 74, 15,31,0 37, 15,28,0 78, 15,25,0 52,
  15,24,0 16, 15,23,0 2, 15,22,0 80, 15,20,0 26, 15,18,0 80, 15,17,0 33, 15,16,
  0 80, 17,15,0 64, 18,15,0 14, 21,15,0 75, 22,15,0 80, 25,15,0 69, 26,15,0 75,
  28,15,0 45, 30,15,0 80, 31,15,0 26, 33,15,0 15, 35,15,0 49, 37,15,0 43, 38,
  15,0 80, 39,15,0 53, 41,15,0 71, 42,15,0 10, 43,15,0 49, 44,15,0 24, 45,15,0
  44,
  45,16,0 53, 45,18,0 46, 45,20,0 53, 45,22,0 71, 45,23,0 80, 45,28,0 15, 45,
  30,0 11, 45,33,0 80, 45,34,0 80, 45,36,0 80, 45,37,0 37, 45,38,0 80, 45,40,0
  72, 45,41,0 80, 45,43,0 30, 45,45,0 33, 44,45,0 24, 43,45,0 49, 41,45,0 34,
  39,45,0 80, 38,45,0 80, 37,45,0 80, 35,45,0 80, 34,45,0 32, 33,45,0 36, 30,
  45,0 80, 28,45,0 9, 24,45,0 36, 23,45,0 47, 22,45,0 43, 21,45,0 80, 20,45,0
  21, 19,45,0 22, 18,45,0 53, 17,45,0 80, 15,42,0 76, 15,39,0 80, 15,38,0 7,
  15,36,0 80, 15,35,0 6, 15,34,0 11, 15,31,0 27, 15,25,0 24, 15,22,0 80, 15,21,
  0 36, 15,19,0 16, 15,15,0 80, 16,15,0 36, 18,15,0 1, 19,15,0 23, 24,15,0 80,
  26,15,0 80, 28,15,0 13, 29,15,0 69, 30,15,0 80, 31,15,0 51, 32,15,0 76, 35,
  15,0 80, 36,15,0 62, 38,15,0 80, 41,15,0 80, 42,15,0 17, 43,15,0 33, 44,15,0
  37,
  45,18,0 70, 45,19,0 46, 45,20,0 75, 45,21,0 80, 45,25,0 40, 45,26,0 80, 45,
  27,0 80, 45,30,0 20, 45,31,0 78, 45,33,0 80, 45,35,0 22, 45,36,0 80, 45,37,0
  68, 45,38,0 48, 45,39,0 5, 45,40,0 80, 45,41,0 45, 45,42,0 52, 45,44,0 44,
  43,45,0 44, 42,45,0 80, 40,45,0 80, 38,45,0 74, 37,45,0 41, 36,45,0 42, 35,
  45,0 80, 33,45,0 26, 32,45,0 3, 31,45,0 73, 30,45,0 80, 29,45,0 80, 28,45,0
  37, 27,45,0 54, 26,45,0 45, 20,45,0 34, 19,45,0 34, 18,45,0 35, 17,45,0 23,
  16,45,0 16, 15,45,0 18, 15,44,0 38, 15,43,0 25, 15,42,0 8, 15,41,0 17, 15,39,
  0 7, 15,37,0 77, 15,36,0 80, 15,35,0 80, 15,33,0 80, 15,32,0 80, 15,31,0 36,
  15,29,0 80, 15,28,0 31, 15,26,0 80, 15,25,0 55, 15,24,0 80, 15,23,0 1, 15,18,
  0 31, 15,17,0 8, 15,16,0 80, 15,15,0 46, 16,15,0 80, 17,15,0 21, 18,15,0 15,
  19,15,0 32, 23,15,0 80, 25,15,0 28, 26,15,0 46, 28,15,0 22, 29,15,0 16, 30,
  15,0 25, 31,15,0 24, 32,15,0 78, 34,15,0 51, 35,15,0 24, 36,15,0 33, 37,15,0
  77, 38,15,0 79, 43,15,0 42, 45,15,0 19,
  45,16,0 55, 45,17,0 31, 45,20,0 23, 45,21,0 80, 45,23,0 70, 45,24,0 47, 45,
  25,0 27, 45,26,0 80, 45,27,0 72, 45,31,0 20, 45,32,0 10, 45,34,0 50, 45,41,0
  33, 45,45,0 53, 44,45,0 56, 43,45,0 80, 42,45,0 35, 41,45,0 80, 39,45,0 80,
  38,45,0 35, 37,45,0 38, 35,45,0 11, 32,45,0 4, 31,45,0 80, 30,45,0 69, 28,45,
  0 80, 26,45,0 38, 24,45,0 22, 23,45,0 19, 22,45,0 35, 20,45,0 1, 19,45,0 80,
  18,45,0 80, 17,45,0 80, 15,45,0 80, 15,44,0 40, 15,43,0 26, 15,42,0 20, 15,
  41,0 80, 15,40,0 54, 15,39,0 80, 15,38,0 80, 15,36,0 26, 15,35,0 9, 15,33,0
  77, 15,32,0 11, 15,31,0 80, 15,30,0 80, 15,29,0 75, 15,28,0 69, 15,24,0 21,
  15,23,0 13, 15,22,0 80, 15,21,0 80, 15,20,0 54, 15,16,0 16, 15,15,0 80, 16,
  15,0 31, 17,15,0 9, 20,15,0 8, 21,15,0 12, 22,15,0 80, 23,15,0 80, 24,15,0
  42, 27,15,0 33, 28,15,0 15, 33,15,0 80, 36,15,0 76, 37,15,0 80, 38,15,0 34,
  40,15,0 49, 43,15,0 26, 44,15,0 80,
  45,20,0 80, 45,21,0 80, 45,22,0 27, 45,23,0 7, 45,24,0 80, 45,25,0 80, 45,26,
  0 69, 45,27,0 54, 45,28,0 40, 45,29,0 73, 45,31,0 10, 45,32,0 80, 45,33,0 80,
  45,34,0 73, 45,35,0 11, 45,36,0 15, 45,37,0 12, 45,38,0 69, 45,44,0 80, 43,
  45,0 80, 41,45,0 71, 39,45,0 20, 38,45,0 18, 37,45,0 20, 36,45,0 80, 35,45,0
  80, 33,45,0 12, 32,45,0 33, 29,45,0 7, 28,45,0 71, 27,45,0 21, 25,45,0 49,
  24,45,0 80, 23,45,0 33, 22,45,0 23, 15,45,0 12, 15,44,0 18, 15,43,0 71, 15,
  41,0 51, 15,39,0 39, 15,38,0 18, 15,37,0 80, 15,36,0 20, 15,33,0 46, 15,31,0
  69, 15,29,0 80, 15,21,0 44, 15,20,0 3, 15,18,0 73, 15,16,0 47, 15,15,0 10,
  16,15,0 80, 17,15,0 80, 18,15,0 80, 22,15,0 56, 25,15,0 49, 26,15,0 80, 27,
  15,0 35, 28,15,0 80, 29,15,0 80, 31,15,0 32, 32,15,0 80, 33,15,0 51, 35,15,0
  6, 38,15,0 10, 39,15,0 8, 40,15,0 80, 44,15,0 26,
  Wounded survivors: 241
  average hp of survivors: 50
```

grenade_lethal_at_5m fails intermittently. Lethality is under the lower acceptable bound, usually about 4.1 when it fails.

**Comment by Brambor** [comment] 2018-08-25 15:17
Should be closed as #24863 was marked duplicate of this and was closed by #25114

**Closed** 2018-08-25 15:53 UTC
Labels: Code: Tests
