### ISSUE TITLE
Curtains block the line-of-sight of vehicle turrets

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19877] opened 2016-12-28 20:13 UTC
I'm presuming the game intends for curtains to be mounted internally in a vehicle, while turrets are mounted externally, and if this is true, curtains should have no impact on turret line-of-sight.

**Comment by codemime** [comment] 2016-12-28 22:32
Dupe of #19730.

**Closed by codemime** 2016-12-28 22:32 UTC
