### ISSUE TITLE
Barbaran Montante can disarm talons mutation

### ISSUE THREAD

**Issue by Coach-mdl** [CleverRaven/Cataclysm-DDA#71647] opened 2024-02-09 20:07 UTC
### Describe the bug

Barbaran Montante can disarm an opponents talon mutation when Swift Atajo is triggered. Likely happens to other melee based mutations too.

### Attach save file

N/A

### Steps to reproduce

Using a fire axe (other compatible weapons should work too) trigger swift Atajo on an opponent with claws or talons.

### Expected behavior

Melee weapons get disarmed, claw remain.

### Versions and configuration

Windows 10
Tiles-sounds-x64-2024-02-02-0710

**Comment by fairyarmadillo** [comment] 2024-02-10 04:51
Duplicate of #67958

**Closed** 2024-02-13 21:17 UTC
Labels: (S3 - Duplicate), (S1 - Need confirmation)
