### ISSUE TITLE
Unable to use welders and acetylene torches for vehicle repairs without duct tape in line of sight

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16651] opened 2016-05-13 03:37 UTC
In 4851 it is not possible to use any form of welder to repair or install parts on vehicles without enough duct tape in your inventory or within crafting range and line of sight.

This bug is easy to reproduce when you try to repair a part of a vehicle without any duct tape at all, I have been trying this with both the Welder and the Acetylene Torch.

It will also show the red name for a powered welder tool in the part installation requirements but will still allow you to use the welder when you start the actuall installation.

**Comment by pisskop** [comment] 2016-05-18 01:26
Welders are spawning bugged.  Debugging welders in or building makeshift welders avoids this, but the ones that spawn with full batteries seem bugged

**Comment by Coolthulhu** [comment] 2016-05-19 17:51
Most likely caused by same thing as #16751

**Comment by Headjack** [comment] 2016-05-26 02:04
They're also not registering for crafting, such as with the Welding Rig.

**Comment by mugling** [comment] 2016-07-01 13:05
A number of recent PR's have closed related bugs so closing this one also due to probable similar cause and lack of recent reports

**Closed by mugling** 2016-07-01 13:05 UTC
Labels: Bug
