### ISSUE TITLE
Character moves at full speed even if both legs are broken

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16130] opened 2016-04-08 10:12 UTC
currently movement speed depends on stamina and encumberance and not the status of legs this effectively makes you crawl at walking speed

**Comment by Night-Pryanik** [comment] 2016-04-08 13:55
Well, in my testing there was a decrease in speed with both legs broken, but 'twas rather small (from 100 to 88).

**Comment by karols146** [comment] 2016-04-11 18:00
I think that with two legs broken crawling should be only way to move.

**Comment by illi-kun** [comment] 2016-04-11 18:19
It's probably duplicate of #11116.

**Comment by illi-kun** [comment] 2016-04-12 09:56
... and #1941.

**Comment by DLaboratory** [comment] 2016-04-12 14:29
= =
OLD BUG SINCE 2013

**Comment by illi-kun** [comment] 2016-04-13 21:05
Closed as a duplicate.

**Closed by illi-kun** 2016-04-13 21:05 UTC
Labels: Duplicate

**Comment by mugling** [comment] 2016-04-13 21:08
I had a run at closing a lot of open issues a month ago but couldn't get the total open issues below 1000. Further such attempts would be very useful

**Comment by illi-kun** [comment] 2016-04-13 21:38
Yeah, your attempts inspired me to start checking the old issues.
