### ISSUE TITLE
Mutation spells do not work properly

### ISSUE THREAD

**Issue by actually-the-artificer** [CleverRaven/Cataclysm-DDA#63851] opened 2023-03-01 09:00 UTC
### Describe the bug

When using Crushing Leap, the player lands near a monster but does not damage them at all.

### Attach save file

[Honesdale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10858983/Honesdale-trimmed.tar.gz)

### Steps to reproduce

1. Unzip the save file.
2. Load up the post-thresh mutant
3. Use Crushing Leap on the NPC
4. Observe no damage dealt.
5. Spawn a couple zombies
6. Use Crushing Leap again
7. Observe no damage dealt

### Expected behavior

Crushing Leap should do damage.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: d26a0f4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment] 2023-03-01 09:05
Duplicate of #53511

**Closed** 2023-03-01 13:54 UTC
Labels: (S1 - Need confirmation)
