### ISSUE TITLE
Crash (segmentation fault) while trying to disassemble car at player faction camp garage

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#28239] opened 2019-02-17 17:36 UTC
**Describe the bug**  
When trying to assign character to disassemble car at faction camp garage, I always got a crash. Right after mission assigned. Looks like it related to how car is removed from world, and cannot be properly rendered. Here is crash log.

```CRASH LOG FILE: config/crash.log
VERSION: 0.C-37498-ga2fc42c
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D5065[cataclysm-tiles.exe+0x1D5065]
    @0x5D5C12[cataclysm-tiles.exe+0x1D5C12]
    SMPEG_error+0x4B034@0xE8C040[cataclysm-tiles.exe+0xA8C040]
    _C_specific_handler+0x9C@0x778885A8[ntdll.dll+0x185A8]
    RtlDecodePointer+0xBD@0x77899D0D[ntdll.dll+0x29D0D]
    RtlUnwindEx+0xBBF@0x778891AF[ntdll.dll+0x191AF]
    KiUserExceptionDispatcher+0x2E@0x778C1278[ntdll.dll+0x51278]
    @0xD85629[cataclysm-tiles.exe+0x985629]
    @0x4B946A[cataclysm-tiles.exe+0xB946A]
    @0x4C51BC[cataclysm-tiles.exe+0xC51BC]
    @0xCC4AEF[cataclysm-tiles.exe+0x8C4AEF]
    @0x681743[cataclysm-tiles.exe+0x281743]
    @0x9AFF8F[cataclysm-tiles.exe+0x5AFF8F]
    @0xAD5665[cataclysm-tiles.exe+0x6D5665]
    @0xAF24E7[cataclysm-tiles.exe+0x6F24E7]
    @0xAF3182[cataclysm-tiles.exe+0x6F3182]
    @0xAF436E[cataclysm-tiles.exe+0x6F436E]
    @0x71E2C8[cataclysm-tiles.exe+0x31E2C8]
    @0x700A36[cataclysm-tiles.exe+0x300A36]
    IMG_LoadWEBP_RW+0x4E8F39@0x1487679[cataclysm-tiles.exe+0x1087679]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x7730652D[kernel32.dll+0x1652D]
    RtlUserThreadStart+0x21@0x7789C521[ntdll.dll+0x2C521]
```
And debug log (if needed).
```-----------------------------------------
18:04:10.712 : Starting log.
18:04:10.712 INFO : Cataclysm DDA version 0.C-37498-ga2fc42c
18:04:10.757 INFO : Number of render drivers on your system: 4
18:04:10.757 INFO : Render driver: 0/direct3d
18:04:10.757 INFO : Render driver: 1/direct3d11
18:04:10.757 INFO : Render driver: 2/opengl
18:04:10.757 INFO : Render driver: 3/software
18:04:10.759 INFO : Language is set to: 'ru'
18:04:10.952 INFO : SDL version used during compile is 2.0.5
18:04:10.952 INFO : SDL version used during linking and in runtime is 2.0.5
18:04:11.124 INFO : Active renderer: 1/direct3d11
18:04:11.127 ERROR SDL : (error message will follow backtrace)
	(@0x5ea81e[cataclysm-tiles.exe+0x1ea81e]), 
	(@0x5eadfa[cataclysm-tiles.exe+0x1eadfa]), 
	(@0xcb82e1[cataclysm-tiles.exe+0x8b82e1]), 
	(@0xcc7535[cataclysm-tiles.exe+0x8c7535]), 
	(@0xcc81e1[cataclysm-tiles.exe+0x8c81e1]), 
	(IMG_LoadWEBP_RW+0x4e9e5b@0x148859b[cataclysm-tiles.exe+0x108859b]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x7730652d[kernel32.dll+0x1652d]), 
	(RtlUserThreadStart+0x21@0x7789c521[ntdll.dll+0x2c521]), 
Backtrace emission took 0 seconds.
src/sdl_wrappers.cpp:24: Failed to initialize accelerated renderer, falling back to software rendering: __FUNCTION__, CreateDXGIFactory: Интерфейс не поддерживается


18:04:11.262 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
18:04:11.262 INFO : generate_alt_rect_texture() = FAIL. alt_rect_tex_enabled = 1
18:04:11.448 WARNING : opendir [./mods/] failed with "No such file or directory".
18:04:24.273 : Log shutdown.
-----------------------------------------
```

**To Reproduce**  
1. Start a player faction camp (or use your existing one).
2. Build garage to such level, so you are able to disassemble cars (2 or 3 upgrades).
3. Put car in a garage overmap tile.
4. Talk to camp leader and assign NPC to disassemble car.
5. As soon as you got message like `<NPC Name> begins working in the garage...` hit enter and game crashes with segmentation fault native window.

**Expected behavior**  
No crashes using car disassembling.

**Versions and configuration(please complete the following information):**
 - *OS:* Windows 7
 - *Game Version:* 0.C-37498-ga2fc42c
 - *Graphics version:* Tiles
 - *Mods loaded:* dda, no_npc_food, novitamins, More_Survival_Tools, mutant_npcs, national_guard_camp, more_buildings, more_locations, Experimental-Z-Level, Urban_Development, boats, blazemod, Tanks, no_olg_guns, no_religious_Texts, no_reviving_zombies, realguns, growable-pots, modular_turrets, Salvaged_Robots, FujiStruct, oa_additional_buildings_mod

**Comment by ZhilkinSerg** [comment] 2019-02-18 06:34
Do you have a savegame prior to crash?

**Comment by Xelat84** [comment] 2019-02-18 15:16
Yes, made clean one, even almost without mods
[NoMods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2876244/NoMods.zip)

**Comment by ZhilkinSerg** [comment] 2019-02-19 09:16
Cannot reproduce under debugger or pre-compiled version. Can you also please share your `config\options.json`?

**Comment by Xelat84** [comment] 2019-02-19 09:58
Weird, me too cannot reproduce it again on this save. It crashed once when I made this save, and I didn't check it after loading it again. But you can still reproduce on this save as I've done: disassemble car already placed in garage, then skip time, return your companion back, spawn another car (car_mini) in a garage and try disassemble this one, it will crash.

**Comment by Xelat84** [comment] 2019-02-23 08:42
Any luck reproducing this bug? May be need some help with anything?

**Comment by LyleSY** [comment] 2020-04-12 22:33
Looks like this issue was duplicated and then fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/29488
Probably ok to close

**Closed** 2020-04-12 22:58 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Player Faction Base / Camp
