### ISSUE TITLE
Associated hotkey to a item gets lost after being wielded

### ISSUE THREAD

**Issue by OneThousandResets** [CleverRaven/Cataclysm-DDA#50323] opened 2021-07-30 12:14 UTC
### Describe the bug

Self explanatory.

### Steps To Reproduce

If you use (i) Inventory -> (=) reassign to give a letter to an item, (w) wield the item, and put it away (w) back into a storage, the letter assigned gets lost.

### Expected behavior

The assigned key should stick.

### Versions and configuration

Windows 10
Version 64x-tiles  15dd993
mods used: statsThroughkills, speedydex, bionic slots,

**Comment by OneThousandResets** [comment] 2021-07-30 12:19
Just now saw this issue being discussed in merge request #50173.
Godspeed.

**Comment by actual-nh** [comment] 2021-07-30 16:58
Duplicate of #50154.

**Comment by exuvo** [comment] 2021-07-30 19:55
Feel free to test the patches i have in that merge request. Might speed the approval up if more people have tested that my patch does not break anything else.

**Closed** 2021-08-07 06:34 UTC
Labels: <Bug>, (S3 - Duplicate), Info / User Interface, Items / Item Actions / Item Qualities, Controls / Input
