### ISSUE TITLE
Rigid skin mutations such as protective bark and chitin make splints impossible to wear

### ISSUE THREAD

**Issue by Testudo-Cultu** [CleverRaven/Cataclysm-DDA#57480] opened 2022-05-06 14:17 UTC
### Describe the bug

Rigid skin mutations seen in the (W)ear menu make it impossible to use splints, meaning that broken limbs are permanently broken unless you use issue #57479 to destroy the rigid skin.

### Steps to reproduce

1. Get a rigid skin mutation
2. Break a leg
3. Try putting a splint on it

### Expected behavior

It shouldn't be impossible to splint a limb, for obvious reasons. Mutations appearing in the (W)ear menu causes many issues and will most likely take multiple pull requests to make work properly. Ideally, I believe we shouldn't have mutations act as apparel at all.

### Screenshots

![image](https://user-images.githubusercontent.com/65055502/167150270-ba5cadc4-cb09-4dcc-9661-c6a49ea37d3a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1500 (1909)
- Game Version: 4974cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Wyghab** [comment] 2022-05-06 15:13
Tangentally related to #56721. I do think you should be able to wear splints regardless of limb status. The rigid armor portion could maybe be fixed by allowing splints to ignore rigid armors on a layer, such as "skin" or "close to skin".

**Comment by Nerezza** [comment] 2022-05-07 05:46
This was caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/55566 with this block of code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character_attire.cpp#L170-L176

**Comment by I-am-Erk** [comment] 2022-11-23 21:06
Raising priority on this as it is one of the outstanding blockers. If it is revealed to be more complex than it seems for repair, we can defer this to after stable as it is bad but not gamebreaking.

**Closed** 2022-11-24 21:43 UTC
Labels: (P2 - High)
