### ISSUE TITLE
Crafting Vehicle Welding Rig with Integrated Toolset

### ISSUE THREAD

**Issue by RydellV** [CleverRaven/Cataclysm-DDA#13739] opened 2015-10-11 13:30 UTC
On experimentals if you attempt to craft the vehicle welding rig by using the integrated toolset the welder has to have less than 100 charges. Otherwise the game attempts to use the welder to make the item and as a piece of the recipe. 
![welderwithcharge](https://cloud.githubusercontent.com/assets/15075317/10416983/6e0565e4-6ffa-11e5-8b85-81f3920ceedf.png)

Removing the charges from the welder allows the integrated toolset to be used to craft it.
##

**Comment by Headjack** [comment] 2015-10-16 21:42
Confirming, it's done so for a while with the vehicle tools.

**Comment by eliotcougar** [comment] 2016-10-13 23:43
Confirmed... If there are both a charged welder and an integrated toolset, the welder is prioritized as a tool and not as a component... However, if you have two charged welders, then you just get a choice to use either the welder or the integrated toolset, no problem... This is one of those weird crafting recipes where the same item is used both as a tool and as a component... Weird circular dependency occurs... Probably not a bug, but possible improvement...
0.C-19186-g23a9665 (tiles)

**Comment by Oskar636** [comment] 2016-11-10 20:02
I'm really confused but I don't think the integrated toolset is an item anymore ( I see it only in wish mode as a dummy item ) or am I missing something...

**Comment by illi-kun** [comment] 2016-11-11 02:57
It's still a pseudo-item, as before, that's why you see it in wish mode).

**Comment by Leland** [comment] 2017-05-24 18:14
Also see #19461

**Comment by hexagonrecursion** [comment] 2021-08-09 08:45
This has been fixed in a rather genius way:
![welder](https://user-images.githubusercontent.com/52621858/128680313-9c220569-b514-4cbe-b729-597f5c35b7d0.png)

**Closed** 2021-08-10 17:27 UTC
Labels: (S1 - Need confirmation), Vehicles, Crafting / Construction / Recipes
