### ISSUE TITLE
Idea for potentially removing skill grind (from crafting skills)

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#14912] opened 2016-01-19 16:01 UTC
A mechanic I've seen used in other games with crafting is to provide a "First Time" bonus to items that you've crafted for the first time. Usually this is a multiplier on the base exp amount so that you aren't just crafting low skill items all the time.

If this sounds like it might be a reasonable mechanic, I could work on fleshing out the details more.

**Comment by Coolthulhu** [comment] 2016-01-19 16:18
You mean removing it altogether or just a tiny bit of it?
Because a moderate first time bonus certainly won't remove a lot of it.

Changing leveling requirements for crafting skills to require x different recipes to be completed AND disabling the regular skill gain from crafting old stuff would work, but it would be a lot of work to balance such a system.

Crafting distaffs, wooden wheels and carding paddles will always be a better way to level up fabrication than getting a complete forge set and crafting crowbars, simply because it is doable at the relevant levels.

Many skills have only a tiny number of grindable recipes. Fabrication is probably the best example: there are tons of fabrication 2 recipes, but only a handful of them are actually craftable at fabrication 2. A great deal of them requires the complete forge set, which usually is harder to get than a deathmobile.

The idea of a first time bonus is good, but it won't kill grinding, just make it less annoying.

**Comment by macrosblackd** [comment] 2016-01-19 16:29
>The idea of a first time bonus is good, but it won't kill grinding, just make it less annoying.

That's is the general idea with this suggestion.

**Comment by hitbutton** [comment] 2016-01-19 17:05
Or it could make it more annoying, as being 'optimal' would force you to hunt for every recipe you can make, but have not made before, which uses exactly your current level of skill.

**Comment by YeAdventurer** [comment] 2016-01-19 18:11
> Or it could make it more annoying, as being 'optimal' would force you to hunt for every recipe you can make, but have not made before, which uses exactly your current level of skill.

The current way wouldn't be gone though, so people could just do that if they prefer. It would be nice to have a first time bonus, in my opinion. It makes sense too.

Hell, might even be nice to have a second time and third time bonus, just in smaller amounts, and after 'third time's the charm' it returns to normal levels.

**Comment by Zireael07** [comment] 2016-01-19 18:51
Third time's the charm? Please! This is a really nice idea.

**Comment by hitbutton** [comment] 2016-01-19 20:55
Saying that people can choose to play suboptimally doesn't excuse making optimal gameplay more tedious.

**Comment by Coolthulhu** [comment] 2016-01-19 21:17
> Hell, might even be nice to have a second time and third time bonus, just in smaller amounts, and after 'third time's the charm' it returns to normal levels.

Would be cool if the "bonus number" depended somehow on recipe complexity. Though I'm not sure how to approximate that.
Number of components? Number of components+tools?
Components+tools would favor forge crafts, which currently are terribad for leveling, complex foodstuffs (say, pancakes) that are currently ignored except when stacking morale, and survivor gear which currently gets crafted when needed or when it's safe and not for leveling.

Recipe complexity could be a good thing for other purposes too: allowing grinding higher levels of skill with lower levels of recipes, provided they're complex enough. This would remove the reliance on those recipes that you only craft to go from cooking 2 to cooking 3 (to get jerky and acorns) and would make early electronics level faster.

**Comment by YeAdventurer** [comment] 2016-01-19 21:28
> Saying that people can choose to play suboptimally doesn't excuse making optimal gameplay more tedious.

Would it be more tedious though? I mean whether or not it's the optimal approach would just depend on what you've found so far and what you have access to. It seems like it'd just be giving you more options. But, considering how important library raiding is already, maybe you're right.

However, maybe that can be alleviated. In a lot of games these days, it tends to throw free recipes at you the more you craft. Perhaps so you weren't having to constantly hunt down new recipes, simply through the act of crafting a lot you could get a lot of the recipes the books would normally give you.

>Would be cool if the "bonus number" depended somehow on recipe complexity. Though I'm not sure how to approximate that.

Not to mention, this sounds really unintuitive, honestly.

**Comment by Coolthulhu** [comment] 2016-01-19 21:39
> this sounds really unintuitive

Somehow rewarding complex recipes over the simple ones would be good.
Though maybe not that way, yeah.
Still, recipe complexity buffing exp gain on its own would be good.

> Or it could make it more annoying, as being 'optimal' would force you to hunt for every recipe you can make, but have not made before, which uses exactly your current level of skill.

This could be fixed by adding the ability to search for those recipes.
Though it may also require adding the ability to search for more than one criterion. I think the current crafting menu only accepts one.

**Comment by YeAdventurer** [comment] 2016-01-19 21:43
>Still, recipe complexity buffing exp gain on its own would be good.

Oh, I agree. I just didn't like the idea that certain recipes would give more first time bonuses than others. Having it always be the same amount, like 3, +300% +200% +100% is much easier to perceive.

**Comment by Coolthulhu** [comment] 2016-01-19 22:03
> Having it always be the same amount, like 3, +300% +200% +100% is much easier to perceive.

While it would be intuitive, I'm not sure if a constant multiplier of exp would do much good.
The problem with that is that it would be huge at low levels (boil a cup of water - nearly level up), but would quickly lose importance at higher levels.

With current leveling, the number of required crafts per level scales roughly linearly with level.
So if you need 10 crafts to gain level 1, then you will need roughly 20 to gain level 2 and 30 to gain level 3.
With constant multiplier, it would mean 3 crafts to gain level 1, 14 to gain level 2 and 24 to gain level 3.

Tying the multiplier to level would remedy this. It would still be intuitive as the bonus would stay roughly the same amount in level progress - if boiling your first water gave you 10% of level 1, then making your first mutagen would give you something close to 10% of level 9.
Probably less, because higher levels (those above 4) have more recipes available, but still.

**Comment by hitbutton** [comment] 2016-01-19 22:09
This would all make "efficient" grinding a much more complex (and IMO tedious) process.

Its also moving away from the principles behind #11695, which simplified and standardised all crafting xp gain specifically to avoid situations where you had to hunt around for the "best" grinding methods.

**Comment by YeAdventurer** [comment] 2016-01-19 22:09
>While it would be intuitive, I'm not sure if a constant multiplier of exp would do much good.
The problem with that is that it would be huge at low levels (boil a cup of water - nearly level up), but would quickly lose importance at higher levels.

It would be in conjunction with your wish to make higher complexity recipes give more XP by default, so those first time bonuses for those would be significant later on.

**Comment by YeAdventurer** [comment] 2016-01-19 22:12
>This would all make "efficient" grinding a much more complex (and IMO tedious) process.
Complex? It's pretty simple to me:
1. Recipes give bonuses when you make them the first few times, it will tell you as much in the chat when you make something.
2. Recipes that take more skill to craft will give more XP.
3. Recipes will sometimes be given to you at random, so if you were cut off from book learning you could still reasonably progress in a crafting skill.

**Comment by hitbutton** [comment] 2016-01-19 22:13
Recipes that take more skill to craft already give more XP.

Having the most recipes become more or less efficient in terms of XP/Time or XP/Material *every time you craft something* is the problem.

**Comment by YeAdventurer** [comment] 2016-01-19 22:15
I meant more XP than they're giving right now, which is what I assumed Coolthulhu was suggesting. I might have misinterpreted.

**Comment by hitbutton** [comment] 2016-01-19 22:22
Ok, I want to grind up a skill to the next level by crafting. I care about the amount of time spent and the amount of material used up.

Right now, I look through the recipes that use that skill, choose the one that requires my current level that is most efficient for materials and craft it until I hit the next level. If I care about the number of keypresses involved, I might choose a recipe that takes longer to craft.

With the system discussed here, I would look through my recipes that use the skill, choose the one that gives me the most XP (e.g. one I have not crafted before) taking into account materials usage. I craft it once, and it loses some/all of its bonus. Now perhaps another recipe has become the "best" recipe to craft, so I then have to repeat the recipe finding process after every craft.

Or I just ignore the system, repeatedly craft a single thing as before, and I am penalised for avoiding tedious gameplay.

**Comment by YeAdventurer** [comment] 2016-01-19 22:25
Ah. I guess the difference is I would find that gameplay much more interesting than the current system and would enjoy it, while you'd look at it as a means to an end you just want to get through as fast as possible.

**Comment by Coolthulhu** [comment] 2016-01-19 22:30
> Recipes that take more skill to craft already give more XP.

It looks like this on paper, but due to hard cap on leveling, it isn't the case.

For levels 0-4, you have only one possible level from which you can craft.
For levels 5-7, you have two levels, but the difference in leveling speed is minimal: each level gives XP proportional to the difficulty level. As a result, grinding is still about picking the fastest, cheapest craft that still grants XP.
From level 8, you have 3 levels to choose from, but will grind by re-crafting same lvl 8 recipes because the difference is even smaller and because those recipes are safer to craft (you don't lose valuable ingredients).

> Or I just ignore the system, repeatedly craft a single thing as before, and I am penalised for avoiding tedious gameplay.

If you're grinding, you're not avoiding tedious gameplay.
Significant enough bonus for crafting new stuff could make grinding less necessary.
And since you'd have less items to craft, you'd need to grind less ingredients for them.

And finally, it would reward actually going out and getting different ingredients rather than bunkering down and crafting 80 pilot lights.

**Comment by illi-kun** [comment] 2016-11-08 05:37
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-08 05:37 UTC
Labels: Suggestion (Discuss)
