### ISSUE TITLE
Game crashes Segmentation fault

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#52715] opened 2021-11-08 19:21 UTC
### Describe the bug

Games seems to crash sometimes when creating a new character after the previous dies. 

### Steps To Reproduce

1. Create a new character 
2. Kill the character 
3. Create a new character
4. Repeat until the crash

### Expected behavior

Not crash?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 46fe95c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots]
]

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7499536/debug.zip)

**Comment by LeahLuong** [comment] 2021-11-09 17:19
This may be related to #52300 or #52329. It's helpful if you do searches for these things before creating duplicate issues which clutter the board. It's also helpful to mention issues which may be related so the root problem can be triangulated.

**Comment by wapcaplet** [comment] 2021-11-10 02:28
Closing as a duplicate of #52300, since both mention crash after the previous character dies.

**Closed by wapcaplet** 2021-11-10 02:28 UTC
Labels: <Crash / Freeze>
