### ISSUE TITLE
Power Grid Lag

### ISSUE THREAD

**Issue by J4SNT** [CleverRaven/Cataclysm-DDA#55133] opened 2022-02-05 17:45 UTC
### Describe the bug

Significant lag when writing/sleeping/crafting after wiring up what I think is a relatively simple and small network of appliances within a LMOE shelter. 

### Steps to reproduce

1. Spawn in LMOE shelter
2. Use the wait function and note the speed 
3. Build a small generator vehicle in one of the rooms
4. Reveal wires 
5. Attach (in my opinion) a small number of appliances, 7 standing lamps, and a fridge and power on
6. Use the wait function and compare
Save : [POWER GRID TESTING.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8008477/POWER.GRID.TESTING.zip)
 

### Expected behavior

Expected smaller impact on low-end machines, willing to accept "...your computer just can't cope..."

### Versions and configuration

Operating System
			Windows 10 Home 64-bit
		CPU
			Intel Core i5 4460 @ 3.20GHz
		RAM
			8.00GB Dual-Channel DDR3 @ 665MHz

Version: 7efd4f5

**Comment by BrettDong** [comment] 2022-02-06 14:49
Loaded the save, waiting an hour in game takes over two minutes in real life.
![image](https://user-images.githubusercontent.com/21075502/152686450-c23ef01c-06aa-416a-8390-0d9194406ea0.png)

**Comment by Fris0uman** [comment] 2022-04-13 18:46
isn't this fixed by #55218

**Comment by Cenness** [comment] 2022-04-13 20:07
> isn't this fixed by #55218 ?


From notes in that pr:
>Unfortunately as this only gets triggered on a new wire being revealed any old saves with a lot of revealed wires will still suffer from lag

**Comment by ZombieZilla** [comment] 2022-04-30 08:35
Seeing as the cause of this issue has been fixed, shouldn't this be closed? If you really want to fix it on your old save, you can delete all the wall wiring from your savefile and that will resolve the old lag issues.

**Closed** 2022-06-08 00:35 UTC
Labels: Code: Performance, (S2 - Confirmed), Vehicles
