### ISSUE TITLE
Multidrop doesn't show Volume anymore,

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#40517] opened 2020-05-13 10:04 UTC
# Describe the bug
Using the multidropfunction won't show either how much volume you have or how much you drop

# Steps To Reproduce

Use multidrop while wearing/carrying stuff

# Expected behavior
showing volume

# Screenshots

![grafik](https://user-images.githubusercontent.com/33199510/81799614-dfcda380-9511-11ea-9dea-a0b9fd5c3ff3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Fewer Farms [Fewer_Farms]
]

# Additional context

**Comment by wapcaplet** [comment] 2021-02-13 02:32
Cannot reproduce in 0.E-9603-g42468f6cab. Total inventory weight and volume are displayed while multi-dropping items, and their values refresh when items are selected or deselected.

Before selecting anything to drop, I have `3.3 / 45.0 kg` weight and `0.63 / 16.20 L` in my inventory (granted by a messenger bag (15 L ) and pair of jeans (1.2 L):

![image](https://user-images.githubusercontent.com/238395/107839427-06529080-6d69-11eb-9bb6-6927a8db9252.png)


Dropping a messenger bag (15 L capacity) reduces it to `2.1 / 45.0 kg` and `0.12 / 1.20 L` (the stuff in my pants):

![image](https://user-images.githubusercontent.com/238395/107839331-5bda6d80-6d68-11eb-9453-eacb366f11cf.png)

And dropping all my smaller items to free up all my space results in `2.4 / 45.0 kg` and `0.00 / 16.20 L`:

![image](https://user-images.githubusercontent.com/238395/107839392-d4412e80-6d68-11eb-9242-20c1b92d1218.png)

This appears to be fixed. Closing.

**Closed by wapcaplet** 2021-02-13 02:32 UTC
Labels: <Bug>, Info / User Interface, Inventory / AIM / Zones
