### ISSUE TITLE
wield crash bug (m4a1)

### ISSUE THREAD

**Issue by thuglifer3000** [CleverRaven/Cataclysm-DDA#70294] opened 2023-12-19 04:59 UTC
### Describe the bug

when I attempt to wield the m4a1 I instantly crash i spawned in a h&k 5.56 carbine and that worked fine

### Attach save file

[Kisatchie-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13711369/Kisatchie-trimmed.tar.gz)

### Steps to reproduce

go to my gun stockpile (the lockers in the corner of the storeroom) and attempt to wield the favorited m4a1 I've had past issues that were not repeated during debugging (my entire hard drive got fucked) but it didn't crash for whoever tested it
modifications are minimal to the game only vendor's spawn list has been altered if I can recallthe 

### Expected behavior

being able to use the only automatic rifle my dude owns 

### Versions and configuration

04b6be2

**Comment by RenechCDDA** [comment] 2023-12-20 01:54
Duplicate of #70156

**Closed by RenechCDDA** 2023-12-20 01:54 UTC
Labels: (S1 - Need confirmation)
