### ISSUE TITLE
Minireactors duplicating plutonium fuel cells and sinking boats.

### ISSUE THREAD

**Issue by emptytriangle** [CleverRaven/Cataclysm-DDA#45702] opened 2020-11-28 18:31 UTC
# Describe the bug
When you insert a plutonium fuel cell into a minireactor, the minireactor multiplies the amount of fuel cells inserted by 500. This increases the weight of the vehicle proportionally (and can make your boat sink).

If you then uninstall the minireactor from the vehicle and unload it, you get all 500 fuel cells back.

# Steps To Reproduce
1. Spawn Atomic Car.
2. Unload minireactor and throw away all fuel cells except one somewhere far away so they won't confuse the test.
3. Re(f)ill minireactor with one fuel cell.
4. Observe minireactor is charged by 500.
5. Observe vehicle weight has increased by 500 fuel cell's worth of weight instead of 1.
6. Remove minireactor from vehicle without unloading it by uninstalling it from Atomic Car.
7. (U)nload minireactor.
8. Observe 500 fuel cells are barfed out of minireactor.

# Expected behavior
When minireactor is loaded with one fuel cell while installed inside vehicle:
- Charge of reactor is increased by 500.
- Weight of car increases by the weight of exactly 1 fuel cell.

When minireactor is loaded while not installed inside vehicle:
- Who cares, I wouldn't even allow this.

When minireactor with 500 or more charge but less than 1000 charge is unloaded while installed inside vehicle:
- Charge of reactor is reduced by 500.
- Weight of car decreases by the weight of exactly 1 fuel cell.
- One plutonium fuel cell is removed from reactor.

When minireactor with 500 or more charge but less than 1000 charge is unloaded while in inventory or on ground:
- Charge of reactor is reduced by 500.
- Weight of reactor decreases by the weight of exactly 1 fuel cell.
- One plutonium fuel cell is removed from reactor.

# Versions and configuration
Experimental 11199 on Windows.

**Comment by anothersimulacrum** [comment] 2020-12-17 19:22
Duplicate of #44150

**Closed by anothersimulacrum** 2020-12-17 19:22 UTC
Labels: (S3 - Duplicate), <Bug>, Items: Ammo, Vehicles
