### ISSUE TITLE
Rail-Mounted Crossbows Are Not Functional

### ISSUE THREAD

**Issue by Mrchache** [CleverRaven/Cataclysm-DDA#29941] opened 2019-04-26 03:47 UTC
**Describe the bug**  
Rail-Mounted Crossbows only shoot one tile, regardless of distance aimed. While this can hit an enemy (Crawling Zombie in this test) the result was the ammunition always bouncing off the zombies thick hide and doing no damage. Bolts Used: Aluminum Broadhead Bolt, Simple Wooden Small Game Bolt, Wooden Bodkin Bolt, Wooden Broadhead Bolt, Simple Wooden Bolt, and Makeshift Wooden Bolt.

**To Reproduce**  
1. Make a player with a M4A1 and attach the Rail-Mounted Crossbow to the M4.
2. Try to aim a distance greater then one square.
3. The bolt will only travel 1 square.

Also,
1. Make a player with a M4A1 and attach the Rail-Mounted Crossbow to the M4.
2. Aim at an adjacent crawling zombie and fire a bolt.
3. The result is the bolt hitting the target and bouncing off its hide, doing no damage.

**Expected behavior**  
A rail-mounted crossbow on an M4A1 shows that, with a simple wooden bolt, the attachment should fire up to 8 tiles away and a rail-mounted crossbow with an aluminum broadhead arrow should not be defeated by a crawling zombie's armor.

**Screenshots**  
![Rail-mounted Crossbow test 1](https://user-images.githubusercontent.com/49974599/56782194-f4ba8600-679a-11e9-8e10-376a6166cde7.PNG)
![Rail Mounted Crossbow 2](https://user-images.githubusercontent.com/49974599/56782198-f84e0d00-679a-11e9-8a05-1592eb5d50d0.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2215-g6b8c6f2 (tiles) Build: 8838
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Manual Bionic Installation, Safe Autodoc

**Additional context**

**Comment by darktoes** [comment] 2019-04-26 03:57
Yeah so basically there's this really weird thing in the code set so that if a projectile has 0 damage, it just plonks onto the tile in front of the player rather than acting like a real projectile. Why? Hell if I know. In this case, the rail-mounted crossbow has no assigned damage value (0) and the projectile fired has a multiplicative damage value. This means that the fired projectile has a damage value of 0 * 1.25 = 0. 0 damage, so that weird code thing is in effect. Again, no idea why that's a thing. The repeating crossbow has an identical problem because it also has a base damage of 0.

The fix for this is easy. I just need to assign actual damage values to the repeating crossbow and the rail-mounted crossbow. I'll be doing in that in my next PR so it's no biggie. If anyone else finds any other weapons that use bolts/arrows in the base game that have a 0 damage value and do this, please list them here. I don't think there's any others though.

**Comment by Mrchache** [comment] 2019-04-26 04:07
Thanks for taking the time to explain what's going on in the background, I appreciate that. Looking forward to your next PR!

**Comment by HeadstrongCatgirl** [comment] 2019-04-26 07:52
Regular bows also do that sometimes, but I can't determine the circumstances under which that happens.

**Comment by Zireael07** [comment] 2019-04-26 08:16
Probably when they're extremely damaged?

**Comment by darktoes** [comment] 2019-04-26 08:18
Beat me to it.
Some bows have quite a low damage rating. If they're damaged, by being driven over or used as a melee weapon, for example, then their damage will decrease and could easily go down to or below zero.

**Comment by HeadstrongCatgirl** [comment] 2019-04-26 09:42
Not necessarily when damaged and it seems to deserve a separate issue.

**Comment by darktoes** [comment] 2019-04-26 10:09
If you can find a way to reproduce it reliably, go ahead.

**Comment by GreevyGreev** [comment] 2019-04-28 02:24
In addition to the problems already stated, the strange system of multiplying damage sometimes leads to things like metal bolts doing almost no damage, but if I instead use the bone bolts from the more survival tools mod, they do much more damage.

**Comment by darktoes** [comment] 2019-04-28 03:05
The damage multiplication system is going to be the new norm, but existing bows and crossbows haven't been modified to suit it yet. The bone bolts from the survival tools mod are probably redundant now that makeshift bolts can be made with bone tips anyway. I recommend not using them or removing them all together.

**Comment by GreevyGreev** [comment] 2019-04-28 03:08
To be honest I use exclusively bone bolts because the rest do abysmal
damage.

**Comment by Night-Pryanik** [comment] 2024-12-14 14:34
Can't confirm on latest experimental as of 14 December 2024.
Using rail-mounted crossbow on a M16A4, I was able to successfully hit debug monster from 5 tiles away.
![изображение](https://github.com/user-attachments/assets/6c8ffd37-cef7-43c9-bd12-8c5a414e3490)

**Closed by Night-Pryanik** 2024-12-14 14:34 UTC
Labels: <Bug>, [JSON], Items: Gunmod / Toolmod
