### ISSUE TITLE
Monsters attacking from different Z-levels are hard to percieve. (3D FoV)

### ISSUE THREAD

**Issue by ThaniCF** [CleverRaven/Cataclysm-DDA#42845] opened 2020-08-10 11:49 UTC
# Describe the bug

Zombies and feral humans gather in groups where they just seem to stand around while knocking eachother down, doing damage. Feral humans throw rocks but that is the only message that is being shown besides zombies getting back up. They seem to focus on a select few zombies.

_Edit: Real issue being not that they attack eachother but that you can't tell when monsters at different Z-levels are attacking. Check comments._

# Steps To Reproduce

1. Start in town where there are feral humans and zombies.
2. Watch enemies group up around eachother continously getting knocked down and getting up while taking damage.
3. Walk by the groups in broad daylight without any of them paying attention to you.

# Expected behavior

The zombies and feral humans should be on the same team and not be attacking eachother. Enemies should recognize the player as priority threat.

_Edit: There should be indicators that enemies are attacking/being attacked from another Z level._

# Screenshots

[Zombies gathered at a corner ignoring the player](https://i.gyazo.com/2fae3735303dda93e580f7c39508f97f.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4951-g9af1a35 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Redacted Roleplaying [redacted],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Mythical Martial Arts [MMA]
]

# Additional context

Started in town and went outside to find most zombies gathered in different large groups ignoring me. On a restart I could not replicate the bug but found it again on later starts. I have 3d vision enabled if that's somehow related. They also seem to be grouping around buildings even if there's nothing inside the building.

**Comment by LyleSY** [comment] 2020-08-10 15:03
This should have been fixed by #42012 , does updating fix?

**Comment by ThaniCF** [comment] 2020-08-10 15:59
This was all running on what I understand to be the latest build (10909) and from multiple restarts I've only seen this happen a handful of times, with the first standing out since there were multiple groups in town that were just standing around like that. On inspection some zombies seem to be getting injured, getting knocked down and getting back up. The only message I see is when they get back up or when a feral human throws a rock, I suppose if they're attacking eachother no message is shown? If not I have no idea what is causing this since some groups did not seem to have ferals present at all, just zombies getting hurt and knocked down.

**Comment by ThaniCF** [comment] 2020-08-10 16:52
I've once again run intothis bug although I can't make sense of what's going on. Again there are tiles which are unseen for no apparent reason and zombies are falling over and sustaining minor damage. I'm not sure if they're attacking eachother or if there's something else going on.

[Unseen squares and zombies struggling to stand?](https://i.gyazo.com/09dc1e9a0a3b3b84def4ef0648c85a6f.png)

Only when there are ferals nearby can I actually tell that they're attacking  eachother since the feral throwing rocks actually shows in the logs, otherwise it's just zombies taking damage and getting downed from what I can tell. Probably related to whatever is causing those tiles to be unseen even though as far as I can tell there's nothing blocking my sight?

**Comment by ThaniCF** [comment] 2020-08-10 17:05
Okay mystery solved. It appears that using the experimental 3d vision has hornets attack the zombies from above with no real indication from your Z-level. This is what causes they zombies to pile up with only ranged attacks being used to attack the hornets back. The unseen tiles are 'Very dark' because of hornet nests(?) with paper walls spawning on the roof of a nearby building.

Hornets viewed from below.
![image](https://user-images.githubusercontent.com/69439653/89809692-3b70f280-db3c-11ea-891f-ef1379210df8.png)
Hornets viewed from rooftop with hovering paper walls visible.
![image](https://user-images.githubusercontent.com/69439653/89809642-21cfab00-db3c-11ea-86bd-07541a53cc89.png)

Should I close the issue?

**Comment by kevingranade** [comment] 2020-08-10 20:27
I would say keep it open and maybe change the title to "monsters attacking from different Z levels is difficult to perceive"

**Comment by Melodeiro** [comment] 2021-02-16 02:19
I have got a lot of damage from "unknown enemy" or something like that. After couple of minutes with debugger, i realised, it was a hornet from a different z-level. For me it was like bugged invisible enemy, without triggering safe mode, etc. Save was almost ruined, but i managed to save-scum it to find out whats happening. I think, this should be disabled until its will be possible for player to attack through z-levels too, see them on minimap, trigger safe-mode, etc.

**Comment by Melodeiro** [comment] 2021-02-16 14:29
Just tried experimental fov, it works as expected, but minimap is not informative in that case. Maybe it would be nice to show them as triangles to also show if enemy is above or below player z-level

**Comment by wapcaplet** [comment] 2021-03-04 03:17
Confirmed in 0.E-9920-gbf40faac70.

1. Enable "Experimental 3D field of vision" in the "Debug" section of game options
2. Debug invincibility just to be safe
3. Get on the roof
4. Spawn a giant wasp at roof-level
5. Jump off the roof
6. Wait a few turns for the wasp to attack - messages say "The giant wasp attacks" and so on
7. Go to options and disable 3D field of vision
8. Wait a few more turns - messages say "Something hits your torso" or "You dodge an attack from an unseen source"

Message log showing before and after enabling 3D FoV:

![image](https://user-images.githubusercontent.com/238395/109906275-67c99900-7c5d-11eb-8fae-9f30b3a31961.png)

**Comment by actual-nh** [comment] 2021-03-04 03:29
Should this also go into the 0.F project?

**Comment by anothersimulacrum** [comment] 2021-03-04 03:48
I don't have the permissions to put it there.

**Comment by Malorn-Deslor** [comment] 2021-03-11 13:45
Yeah, I've seen this problem show up quite a few times. Death from above is brutal.

**Comment by ZhilkinSerg** [comment] 2021-03-12 16:44
> 
> 
> Confirmed in 0.E-9920-gbf40faac70.
> 
>     1. Enable "Experimental 3D field of vision" in the "Debug" section of game options
> 
>     2. Debug invincibility just to be safe
> 
>     3. Get on the roof
> 
>     4. Spawn a giant wasp at roof-level
> 
>     5. Jump off the roof
> 
>     6. Wait a few turns for the wasp to attack - messages say "The giant wasp attacks" and so on
> 
>     7. Go to options and disable 3D field of vision
> 
>     8. Wait a few more turns - messages say "Something hits your torso" or "You dodge an attack from an unseen source"
> 
> 
> Message log showing before and after enabling 3D FoV:
> 
> ![image](https://user-images.githubusercontent.com/238395/109906275-67c99900-7c5d-11eb-8fae-9f30b3a31961.png)

Does not work like that for me on latest master. What was your OS and build system settings?

**Comment by wapcaplet** [comment] 2021-03-12 19:39
> Does not work like that for me on latest master. What was your OS and build system settings?

I can still reproduce it on 0.E-10010-gd821da4ea4, Linux, using the same steps as before. Here is my build command:

`make -j16 CLANG=1 TILES=1 RELEASE=1 CCACHE=1 DEBUG_SYMBOLS=1 SOUND=1 USE_HOME_DIR=0 PCH=0`

Game info:

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-10010-gd821da4ea4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by MarlossCDDA** [comment] 2021-03-14 16:42
Reposting from Discord: Creature::sees behaves differently in debug mode https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/creature.cpp#L255. I'm not sure if that's intended behavior or if it just got merged by accident.

**Comment by actual-nh** [comment] 2021-03-14 21:18
Proposal:

- Correct `Creature::sees` so it behaves the same way in or out of debug mode.
- Have the monster_attack test run twice - once with fov_3d turned on (and the cross-Z-level attacks should work), once with it turned off (upon which no cross-Z-level attacks should be possible). I expect this to fail initially, but it should be informative and eventually be successful. If #47993 is incorporated, preferably without the exceptions for stairs/ramps that #46370 requires despite the setting of fov_3d, it may well help on this.
- Check whether, in the monster_attack test, the avatar and monster can see each other when they are supposed to be able to attack each other. This may be asymmetric - the test uses the attack_at function and the specified location for the monster, but the melee_attack function for the avatar.

**Comment by actual-nh** [comment] 2021-03-15 00:40
I would appreciate if people (including both @ZhilkinSerg and @wapcaplet) would check #48048 to see if this makes any difference for what results they get.

**Comment by wapcaplet** [comment] 2021-03-15 01:22
> * Check whether, in the monster_attack test, the avatar and monster can see each other when they are supposed to be able to attack each other. This may be asymmetric - the test uses the attack_at function and the specified location for the monster, but the melee_attack function for the avatar.

@actual-nh I put up a draft PR #48051 to cover this. As you have guessed, the attacker cannot actually see what they are attacking, and these checks are failing.

@Jamuro-g Please feel free to add those checks to your fix PR if you find them useful.

**Comment by actual-nh** [comment] 2021-03-18 00:53
The ordering, in terms of sets, that appears to be needed  is [set of things visible with fov_3d] >= ([set of things attackable with fov_3d], [set of things visible without fov_3d]) >= [set of things attackable without fov_3d], with >= meaning "subsumes but may be identical to" and parentheses not specifying an ordering.

**Comment by actual-nh** [comment] 2021-03-24 03:12
I have expanded the testing further with #48202 (which incorporates wapcaplet's draft PR and is likewise meant as tests for Jamuro-g's fix PR).

**Comment by actual-nh** [comment] 2021-03-27 22:38
Well, #48245 seems to fix the problem with monsters attacking, although playtesting of this is still needed. However, expansion of the monster_attack test code has revealed that, even if the avatar can't see the target, melee_attack is still allowing the avatar to attack the (unseen) target... which needs fixing.

**Comment by actual-nh** [comment] 2021-03-28 00:56
We may have a solution - but two things need checking:

- Playtesting (including whether the avatar can hit the monster and vice-versa) for the original bug
- Reach attacks (although this may have to wait until later, as with stretch attacks if different)

**Closed** 2021-04-06 02:12 UTC
Labels: <Bug>, Info / User Interface
