### ISSUE TITLE
Missing item definition: oven_pan_1

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#56444] opened 2022-03-28 22:52 UTC
### Describe the bug

The following message is shown:
```
 DEBUG    : Missing item definition: oven_pan_1

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 2276
 VERSION  : 0.C-69244-g7d8e8cfcd5
```
(Ignore the 0.C in version; it's the version compiled by me to test  #56441

### Steps to reproduce

1. Load a save.
2. Press `NUN 1` to go south-west.
3. The game freezes for a moment.
4. An error gets shown.

### Expected behavior

The game should not freeze and no error should be shown.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.C-69244-g7d8e8cfcd5 [64-bit]
- Graphics Version: Tiles
- Game Language: Polski [pl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Wyłącz potrzeby NPC [no_npc_food],
    Bez wzrostu grzybiczego [no_fungal_growth],
    Profesje bioniczne [package_bionic_professions]
]

### Additional context

[error3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8366820/error3.zip)

Sometimes the game can even crash during that, also it's not a fresh save sadly.

I also had similar errors popping here and there when exploring, probably related.

**Comment by BrettDong** [comment] 2022-03-29 10:07
Duplicate of #55996.

**Closed** 2022-03-29 21:29 UTC
Labels: (S3 - Duplicate)
