### ISSUE TITLE
Deconstructing Rags made from Blood Soaked Rags produces liquid and freezes the game

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#26849] opened 2018-11-26 13:40 UTC
**Describe the bug**  
Try to deconstruct a rag for thread if that rag was made from a blood soaked rag seems to produce very large amounts of liquid as well as a blood soaked rag, and cause the game to freeze, probably due to the liquid production.

Edit for further information: Doesn't seem to actually permanently freeze the game, but it certainly freezes it for several minutes, and do that again every time you try to interact (including moving over it). 

**To Reproduce**  
1. Get blood soaked rag.
2. Use the crafting recipe to clean up the rag that requires water and fire
3. Deconstruct that particular rag.

**Expected behavior**  
Deconstructing rags should give me a bunch of thread and only that.

**Versions and configuration:**
 - Windows 7
 - 0.C-34822-g9d2bf21
 - Tiles
 - "FIC_Weapons",  "Medieval_Stuff",  "Mining_Mod",  "More_Survival_Tools",  "No_Acid_Zombies",  "No_Explosive_Zombies",  "No_Fungi",  "SD_Magcrafting",  "realguns",  "SD_Magcrafting_Realguns_Extension",  "StatsThroughSkills",  "blazemod",  "Tanks",  "boats",  "craftgp",  "deoxymod",  "ew_pack",  "makeshift",  "more_classes_scenarios",  "mutant_npcs",  "no_npc_food",  "novitamins",  "npc_traits",  "safeautodoc",  "filthy_morale",  "manualbionicinstall"

**Comment by PonyNegZero** [comment] 2018-12-14 05:36
I did not run into any issues with lag or game freezing or anything, but I ran into the same issue where deconstructing the now-clean rag would result in the 1 unit of clean water I used and the bloody rag again.  I took screenshots of each step - https://imgur.com/a/NcG7Tzi

Windows 7
0.C Tiles build 8268
Mods: "dda",  "makeshift",  "More_Survival_Tools",  "national_guard_camp",  "more_locations",  "FujiStruct",  "No_Fungi",  "no_npc_food",  "manualbionicinstall",  "safeautodoc",  "StatsThroughSkills",  "alt_map_key"

**Comment by BevapDin** [comment] 2018-12-15 23:59
Seems like a clear duplicate of #24012.

**Closed by BevapDin** 2018-12-15 23:59 UTC
Labels: (S1 - Need confirmation), <Bug>, Crafting / Construction / Recipes
