### ISSUE TITLE
Hordes contain excessive numbers of shocker brutes

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14692] opened 2016-01-03 03:54 UTC
Shocker brutes seem to lack any lower bounds on spawn time and the like. When most zombies aren't even in the "tough" stage, regular shockers and regular brutes are rare, shocker brutes are barely uncommon.

It's not a problem in regular spawn mode, but in wander spawn it becomes obvious how overrepresented they are.

**Comment by Rivet-the-Zombie** [comment] 2016-01-03 04:01
I've also noticed an undue proportion of shady zombies ever since they were introduced.

**Comment by keyspace** [comment] 2016-12-25 16:56
Couldn't reproduce OP, but then it's rather worldgen-dependent. Just `STATIC_SPAWN` and `WANDER_SPAWN` give 4 possible combinations. Then I think there's time-based spawning if `STATIC_SPAWN == false`, meaning 6 world types to test, or even 8 for completeness...

For shady zombies (added in #14322) - agreed, it seems out of proportion, probably because there's a [rather high chance of a "pack" spawn](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monstergroups.json#L451).

-----

Below's the output of my `sortkills.py` (see #19849) for all monsters mentioned here, plus `mon_zombie` for reference.

It's from a save file produced running [this branch](https://github.com/CleverRaven/Cataclysm-DDA/compare/master...keyspace:test-wander-spawnrates) (adds kills to the kill count even if done via debug menu, or by other monsters).

The world is `STATIC_SPAWN == false`, `WANDER_SPAWN == true`. Tested by driving around a largish city on a debug-spawned superbike, debug-killing everything regularly, right after game start (so the non-wanderspawn groups probably didn't start spawning yet).

```
% ./sortkills.py ./wander-killall.0/*.sav | grep -E "(\bmon_zombie\b|brute|shady|shocker|tough)" | column -t
mon_zombie                233  19.15
mon_zombie_shady          123  10.11
mon_zombie_tough          57   4.68
mon_zombie_brute_shocker  5    0.41
mon_zombie_brute          5    0.41
```

**Comment by Leland** [comment] 2017-05-08 14:36
Closing in favor of #13803, which reveals the issue here: wander spawns completely disregard spawn frequencies.

**Closed by Leland** 2017-05-08 14:36 UTC
Labels: Balance
