### ISSUE TITLE
one missing json field leads to endless errors

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11770] opened 2015-03-24 01:01 UTC
#11755 introduced a single json mistake, a missing comestible_type field in a comestible item. This leads to an almost endless stream of json errors when loading a game. That failure mode should probably be a lot less severe.
##

**Comment by keyspace** [comment] 2016-12-23 18:05
`canola` has `comestible_type` in `0.C-20286-g59a30d5` (latest `master` ATM).

OK to close as stale?

**Comment by sparr** [comment] 2016-12-23 22:49
Only if it's stale enough to close on that alone. The fix to the canola json isn't a fix for this bug.

**Comment by kevingranade** [comment] 2016-12-24 02:39
The problem is, once we throw an exception as a result of a parsing issue,
the parser is in a bad state.  We could easily do something like bail out
of the current file, or with a lot more work try and find the next entry
and continue from there. Alternately we can also just halt the program
after the first error, which would be nicer from one point of view and less
nice from another.
Fundamentally though, I'm just not that concerned about making the behavior
of the system when there's a json error nicer, the solution is to fix the
json.

**Comment by sparr** [comment] 2016-12-24 04:36
Just finding the problem in the JSON that needs to be fixed is difficult when it's 30k lines up in your terminal. Bailing out (to whatever degree makes sense) after the first line of parsing failure would greatly help there.

**Comment by kevingranade** [comment] 2016-12-24 06:09
OK cool if that resolves the issue for you it's totally reasonable, and I'm
pretty sure trivial to implement.

**Comment by keyspace** [comment] 2016-12-24 23:59
Just tried removing the `comestible_typle` from `canola`. Result: segfault.

@sparr, there is \~\~strikeout\~\~ when you want to ~~edit~~ clarify your message.

**Comment by sparr** [comment] 2016-12-25 01:03
@keyspace what happened on the console prior to the segfault?

**Comment by keyspace** [comment] 2016-12-25 12:43
Nothing. The terminal was corrupted, requiring a `reset`.

**Comment by kevingranade** [comment] 2017-03-08 03:38
Addressed by #18137

**Closed by kevingranade** 2017-03-08 03:38 UTC
Labels: Enhancement
