### ISSUE TITLE
Bug: Deep Water Lake Tile Produces Unnatural Edges

### ISSUE THREAD

**Issue by helle253** [CleverRaven/Cataclysm-DDA#22907] opened 2018-02-09 03:28 UTC
Game version:0C - 26144 -g4f5a4ba

Operating system:Windows 10

Tiles or curses: Tiles

Mods active:DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, More Survival Tools, Alternative Map Key, More Buildings, Makeshift Items Mod

### Expected behavior

Generated Rivers should have sandy beach areas.

### Actual behavior
A large chunk of this river appears to be just a block of water. It is a deep water overworld tile adjacent to land.
### Steps to reproduce the behavior
Generate a map where deep water is adjacent to land on 2 edges that share a vertex. The 'corner' shape will be extremely obvious and unnatural.
![mapgen error](https://user-images.githubusercontent.com/16829413/36010375-ad60f1a2-0d16-11e8-83f1-97ffa2044c22.PNG)

NOTE: This is either related to or a duplicate of #18583. Please close if needed.

**Comment by Night-Pryanik** [comment] 2018-02-09 06:49
Duplicate of #18583.

**Closed by Night-Pryanik** 2018-02-09 06:49 UTC
