### ISSUE TITLE
Very poor performance (5+ minutes to do a sleep cycle)

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#78208] opened 2024-11-28 12:30 UTC
### Describe the bug

Doing any long duration task the game grinds to a halt i,e sleeping or crafting it was partially resolved a few days ago but has reoccured. 

### Attach save file

[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/17948021/Zakhadia_BigCity-trimmed.tar.gz)

### Steps to reproduce

Load game read a book, craft something, or sleep, and game runs awful. 

### Expected behavior

To not run this bad

### Screenshots

https://github.com/user-attachments/assets/82966366-2da2-4251-8538-7235053b56dd

### Versions and configuration

- OS: Windows
    - OS Version: 7 64bit
- Game Version: d16889e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Waether** [comment] 2024-11-28 15:03
I have the same issue on my side, game is really slow when crafting/sleeping.

[Innawood Duo Survival-trimmed.tar.gz](https://github.com/user-attachments/files/17949621/Innawood.Duo.Survival-trimmed.tar.gz)

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 286cff2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    DinoMod [DinoMod],
    Mind Over Matter [mindovermatter],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by ZhilkinSerg** [comment] 2024-11-28 16:05
Duplicate of #78092

**Comment by zakhad** [comment] 2024-11-30 09:25
@ZhilkinSerg my game is still running absolutely awful why is this a duplicate?

https://github.com/user-attachments/assets/d2e806dd-db21-4c3a-a21f-f3c264883414

**Comment by GuardianDll** [comment] 2024-11-30 10:04
I assume it means the cause of your slowdown is different from original issue

**Comment by GuardianDll** [comment] 2024-11-30 10:24
Perfomance from 10 seconds of waiting in your save file
![image](https://github.com/user-attachments/assets/e4090c53-2981-4428-9918-f6a54604665d)
![image](https://github.com/user-attachments/assets/b2a55e7a-f31a-4ca9-b422-b6a44b77db5e)

**Closed** 2024-12-05 10:56 UTC
Labels: (S1 - Need confirmation)
