### ISSUE TITLE
Don't greatly age finished food products while they're being cooked.

### ISSUE THREAD

**Issue by aawilson** [CleverRaven/Cataclysm-DDA#28930] opened 2019-03-23 05:35 UTC
**Is your feature request related to a problem? Please describe.** 
 
When turning food that spoils very quickly (meat) into food that lasts a long time (sausage, meat jerky, pemmikan), the percentage of spoilage is carried over into the final product. This breaks some verisimilitude on its own, but presumably modeling the different _ways_ thing spoil is a harder problem--the specific focus of this issue is that long cooking times for big batches mean it's incredibly hard to efficiently make said products without it all coming out with something like a week of shelf life, since a big batch eats a large portion of its day-or-so of unspoiled time. Freezers and fridges mitigate, but it would be nice to have innawoods options that reflect the ways we stored meat for millenia before refrigeration, and to make it less frustrating that killing a large animal for its meat is essentially as effective as killing a small one given the eventual amount of waste involved.

**Describe the solution you'd like**  
Pause spoilage while cooking is happening, or calculate end products from total time rather than carrying over percentages (perhaps pinning to "stages" like "old" or "rotten" so you can't just cook rotten milk into tasty hard cheese).

**Describe alternatives you've considered**  
It also might be possible to make cooking products into a "proto-item" that ages on the end result timespan for the length of cooking, but my guess is that the crafting system is not arrange in a way that makes this easy.

**Comment by l29ah** [comment] 2019-03-23 21:17
From the realistic point of view, there are different kinds of cooking: those which halt or reset the ongoing bacterial/mold growth (boiling, frying, dehydrating, pressure cooking, immersing in salt water) and those which don't (making salad, burgers, anything that merely mixes things together w/o heat (that actively destroys most of the living things) or adding preservatives (like salt or alcohol, which make the environment unsuitable for most)). It may make sense to make a flag that reflects the fact in the recipe.

**Comment by kevingranade** [comment] 2019-03-24 02:54
Please provide some numbers for this, e.g. after killing a deer, butchering it, and preparing the yields, how long does each step take, and what are the apparent ages of the resulting items.

This needs tools, skill levels, etc as well so we can reproduce the issue.

**Comment by Tharn** [comment] 2019-03-26 13:29
Definitely agree with OP that this is silly. Putting freshly butchered meat immediately into the smoker produces smoked meat with half its lifetime expired.

Butchery products spoiling in a day or so is perfectly fine. I don't think we actually have to look at the timeframe for field dressing and butchering to tackle the problem. Spoilage counters for these short-lived raw foods should simply not factor into the 'freshness' of a preserved (dehydrated, smoked, dried, salted) food product.

This would be the most painless solution. So why shouldn't it factor into the calculation? Because right now, it's **impossible** to create preserved foodstuffs with low spoilage. This cannot be the intended outcome. We have to assume this is an oversight that has simply not been accounted for.

**Comment by Zombiemanpig** [comment] 2019-03-26 15:48
Yes I also agree, it's weird that it passes on the %. If you buy raw meat and cook it the next day, it lasts just as long as if you cooked the day before (In real life).

**Comment by ifreund** [comment] 2019-03-26 23:58
Like Kevin said, we need sources and numbers.  I’d be happy to fix rot is applied as part of my crafting changes if there is a clearly defined problem and solution.

**Comment by Zombiemanpig** [comment] 2019-03-27 00:31
> Like Kevin said, we need sources and numbers. I’d be happy to fix rot is applied as part of my crafting changes if there is a clearly defined problem and solution.
> […](#)
> On 26. Mar 2019, at 10:48, Zombiemanpig ***@***.***> wrote: Yes I also agree, it's weird that it passes on the %. If you buy raw meat and cook it the next day, it lasts just as long as if you cooked the day before (In real life). — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I +1'ed the OP; I agree with his proposed short term fix of picking the raw time instead of the percentage when it comes to passing on "rot" into cooked items.

I also think segmenting it into parts could work well. When the player cooks something; if it is only 0 - 20% "rotten" then it counts as if it was not rotten at all, 21 - 40% rotten, would count as 20% for the cooked meal to start off as, etc.  The numbers and amount of segments can be figured out for balance as needed but I think 5 would be a good starting point and also being able to get 0 rot on your cooked item would be fantastic and make the game feel less lying to me.

Either one of these would be better than the current system.

**Comment by ifreund** [comment] 2019-04-05 21:41
Changes in #28937 should actually close this issue.  I ended up making in progress crafts rot at the rate of the result.  Percentage of the most rotten component is still carried over at the start for now, though that may change based on discussion in #29210

**Comment by l29ah** [comment] 2019-04-05 21:42
I think this won't affect the charcoal smoker.

**Comment by l29ah** [comment] 2019-04-05 21:43
Er, smoking rack.

**Closed** 2019-04-09 03:04 UTC
Labels: Crafting / Construction / Recipes, Items / Item Actions / Item Qualities
