### ISSUE TITLE
Electric lantern provides light from a distance

### ISSUE THREAD

**Issue by Swootch** [CleverRaven/Cataclysm-DDA#68926] opened 2023-10-26 14:25 UTC
### Describe the bug

Activating an electric lantern, without picking it up, provides the player character with light as if the light source were carried.

### Attach save file

[Maxfield-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13178814/Maxfield-trimmed.tar.gz)

### Steps to reproduce

1. Activate lantern without picking it up (via 'a' menu).
2. Leave the immediate location of the activated light.
3. Observe the player keeping the light of the device, despite not carrying it.

### Expected behavior

No ghost lights.

### Screenshots

![43546787](https://github.com/CleverRaven/Cataclysm-DDA/assets/45204409/da6a2f98-8e24-4bc8-9a92-66872a7e4110)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 446e59e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

- Not tested with other light sources
- Electric lantern having a battery does not matter (plugged into powergrid)
- Works at extreme distances and across Z-levels
- Plugged in or not does not matter
- Turning it on in your inventory and then dropping it does not trigger this bug

**Comment by ZhilkinSerg** [comment] 2023-10-26 15:19
Duplicate of #68435

**Closed by ZhilkinSerg** 2023-10-26 15:19 UTC
Labels: (S1 - Need confirmation)
