### ISSUE TITLE
On spawn, clothing with changable sides have no sides defined

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16558] opened 2016-05-07 08:17 UTC
when you spawn in, if you have a sheathe or similiar as starting item, then it has no side, and it appears too act as if its on both sides.

**Comment by 321nick** [comment] 2016-05-07 08:21
also, i cant find out how too add a label too this, if i can.

**Comment by i2amroy** [comment] 2016-05-07 08:25
>also, i cant find out how too add a label too this, if i can. i want too label it as a bug, but i cant.

Only contributors have the ability to add labels to issues. The most non-contributors can do is add [BUG] at the start of the title or something similar.

**Comment by 321nick** [comment] 2016-05-07 08:26
ok thanks.

**Comment by 321nick** [comment] 2016-05-07 08:40
heres a image of an ingame example of the bug : http://i.imgur.com/yQIXqww.png

**Comment by BevapDin** [comment] 2016-05-07 09:05
This seems to work as intended. Sheaths can be worn on either side. While it's not worn it has no side, when you wear it, it is automatically assigned to a side (and that is shown in the inventory).

In other words: it's not like a glove (*fits* only on one side, chosen when it's produced), but more like a ring (fits on fingers on either side, chosen when it's worn).

**Comment by 321nick** [comment] 2016-05-07 09:07
yeah, but on spawn it doesn't have a side, its in this weird state where its worn on like, both sides, but if you want you can never take it off or adjust it and its in this weird state where both legs are encumbered

**Comment by mugling** [comment] 2016-05-07 09:29
Does this only occur when you chose a starting profession that has such an item. One possible deficiency is that `laterality` is possibly not set in that circumstances?

**Comment by 321nick** [comment] 2016-05-07 09:30
i think so, ive never seen a sheathe worn without a choosen side, besides when starting with it worn .

**Comment by Oskar636** [comment] 2016-11-09 18:56
Doesn't reproduce when spawning in with a proffesion that wears a sheath on start. Build 5862.

**Comment by mugling** [comment] 2016-11-28 22:32
Closed as unconfirmed

**Closed by mugling** 2016-11-28 22:32 UTC
Labels: Bug, Confirmation Needed
