### ISSUE TITLE
Fix description of heavy stick to not include making two by fours.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28359] opened 2019-02-24 16:26 UTC
### Expected behavior

Descriptions should not mention crafting recipes that are impossible

### Actual behavior

Heavy stick --> 2x4 recipes were removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/25735, but heavy sticks still say they can be made into 2x4s

### Steps to reproduce the behavior

Look at a heavy stick.

**Comment by ifreund** [comment] 2019-02-24 16:30
Duplicate of #28354.

**Closed by ifreund** 2019-02-24 16:30 UTC
Labels: <Bug>, Good First Issue, Info / User Interface

**Comment by I-am-Erk** [comment] 2019-02-24 16:38
You're a duplicate
