### ISSUE TITLE
Heavy duty tow cable does not pull the car

### ISSUE THREAD

**Issue by nikow** [CleverRaven/Cataclysm-DDA#52262] opened 2021-10-12 20:26 UTC
### Describe the bug

I attached both sides of heavy duty tow cable to car and my deathmobile, then drove backward. Car didn't moved even when i drove a lot tiles back. I remember before cable was snapping if something was not correct, but now it's not.

### Steps To Reproduce

1. Load a save available here https://www.nikow.pl/~nikow/2021-10-12_Citra.7z (or the uploaded save)
2. 'A'ttach wielded cable to car.
3. 'A'ttach second end to big car.
4. Hop into drivers seat and go in reverse.

### Expected behavior

Car is pulled by my vehicle.

### Screenshots

https://www.nikow.pl/~nikow/Peek%202021-10-12%2022-19.gif (22MB, github allows just 10MB)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-3351-gfb79bab750 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[2021-10-12_Citra.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7332776/2021-10-12_Citra.zip)

**Comment by ProfoundDarkness** [comment] 2021-10-13 04:35
My experience is that reverse does not pull the towed vehicle.  If your vehicle isn't going forward, no pulling happens.

More of an aside but 'interesting' (not buggy IMO) things happen if you attach to say the rear of the towed vehicle instead of the front.

**Comment by hexagonrecursion** [comment] 2021-12-18 06:24
Related: #51202
This issue might be a duplicate of: #48935

**Comment by wapcaplet** [comment] 2022-01-17 03:58
Closing as duplicate of #48935

**Closed by wapcaplet** 2022-01-17 03:58 UTC
Labels: (S3 - Duplicate), (S1 - Need confirmation), Vehicles
