### ISSUE TITLE
You can make food out of rotten ingredients

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#18865] opened 2016-10-16 22:43 UTC
Like fruit leathers or dehydrated fruit out of rotten fruit.

**Comment by Coolthulhu** [comment] 2016-10-16 22:55
Known for years.

Tolerated because of UI and technical issues.

**Comment by illi-kun** [comment] 2016-10-17 08:11
Duplicate of #13144.

**Closed by illi-kun** 2016-10-17 08:11 UTC
