### ISSUE TITLE
Rare ammo types are perhaps too rare

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#18561] opened 2016-09-28 04:19 UTC
In my searches through mapgen both C++ and .JSON I have only found 2 instances of the ammo_*_rare item groups being called. Once in the Home defense gun store (spawn weight of 300 compared to 1000 for the normal gun store), and once as a Lab final (4% of lab will have this final). I don't know if I have missed some spawns but these are so far the only sources of .44 mag cartridges and other such ammunition.

**Comment by DangerNoodle** [comment] 2016-09-28 17:51
Do the "gun factory" and other high-quality gun stores still exist? If so, a section could be set aside to add a low chance of citing the rare ammo item group. This is assuming that rare ammo is mainly obscure calibers, as some stores might carry limited amounts of uncommon chamberings that are still used by reproductions of out-of-production firearms (like for cowboy action shooting).

Gun factory stores also seem the most likely to have the obscure calibers.

This goes out the window if the rare ammo itemgroup is intended to be for military-issue or otherwise restricted ammunition.

**Comment by mugling** [comment] 2016-09-28 17:56
I'll take a look

**Comment by XaoG** [comment] 2016-09-28 21:31
I'm not sure what you mean by "gun factory stores" but the stores with a back room that has electric forges, lead, gunpowder, etc... Still exist, and in the past I've seen them very rarely spawn casings for ammo types such as .44. 

I've also found it in gun basements in the past, but it's been a while since I've seen either. I'm not sure if they're still spawning there, but if I find some I'll mention it. I *think* you used to also be able to get them from gun store vending machines, back when they still had ammo in them.

But yeah, right now it's nigh impossible to find certain calibers of ammo.

**Comment by Zilenan91** [comment] 2016-09-28 22:03
Yeah if by gun factory gun stores he likely means the ones with ammo reloading equipment in the back. Outside of that the only other gun stores I've seen are about 99% the one with a little bit of every type of gun and a few gun books in the front with a firing range in the back, and I've only ever seen a single gun store where there was broken vending machines in the front as well as several guns and a lot of ammo and gun mods in locked cases like you'd find in a museum.

**Comment by DangerNoodle** [comment] 2016-09-28 22:19
Yes. I could have sworn that some comment or other code led me to assign that name to the gunsithing variant of gun stores.

**Comment by Leland** [comment] 2017-08-24 04:27
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.

**Closed by Leland** 2017-08-24 04:27 UTC
Labels: Balance, Spawn
