### ISSUE TITLE
Unexpected behaviour after light map adjustments

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#77521] opened 2024-11-02 03:35 UTC
### Describe the bug

After #77193 , there is something wrong with the light.
Open a frosted glass door will not change your vision, things behind the door remains **_unseen_**, even if you wait for a turn.
Only after moving one tile away, the tiles behind the door will become bright.
In version 2024-10-22-0120, things work as intended.

### Attach save file

[Tagus-trimmed.tar.gz](https://github.com/user-attachments/files/17605405/Tagus-trimmed.tar.gz)

### Steps to reproduce

1. Load the save, open the door, wait a turn, see that things behind the door remains "unseen".
2. Move one tile away and things become "bright".
3. Use a version earlier than 8f226e5345ce58030a6b4e921fdf5a5b8017b925, see how it works.

### Expected behavior

See things correctly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: e854fb95c006ea09de321add15d66a32e210fd8f
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment] 2024-11-02 08:19
/Confirmed

And yes, I'm going to try to look at it.

**Comment by PatrikLundell** [comment] 2024-11-02 11:45
Hm, the TRANSLUCENT handling is a hack. It causes the "transparent" element to be set in the terrain, so additional checks are needed to actually detect the difference where it's needed.

I can improve the situation, but there's still something wrong:
Changing map.cpp operation map::ter_set to this (adding translucent checks)
```
    if( old_t.transparent != new_t.transparent ||
        old_t.has_flag( ter_furn_flag::TFLAG_TRANSLUCENT ) != new_t.has_flag(
            ter_furn_flag::TFLAG_TRANSLUCENT ) ) {
        set_transparency_cache_dirty( p );
        set_seen_cache_dirty( p );
    }
```
causes opening of a frosted door to show the outside immediately, but it lingers for a tick when the door is closed, and I don't know why (probably the same reason a lot of other things seem to take a tick to catch up, whatever that is).
set_ter does invalidate the set_seen_cache correctly (after the code change above), and it is indeed dirty after the caches have been updated, but its effect is delayed for a closing door but not an opening one, and I don't know why.

It can also be noted that we don't actually have to set the dirty flag for translucent terrain in lightmap.cpp operation map::build_vision__transparency_cache, because it's now set properly by set_ter (I commented it out, and it still works), but the actual setting if the terrain is still needed due the light map thinking translucent is identical to transparent (so it would be possible to move that loop after the memcpy and avoid adding to the vector that's still needed for the crouching). It should also be noted that the crouching (etc.) still needs to set the dirty flag, because that's not handled elsewhere.

Hm, map::sees makes use of map::is_transparent, which checks the transparency cache, and thus is oblivious to whether it's TRANSLUCENT. May or may not be relevant, but it seems suspicious.
map_field.cpp operation map::get_applicable_electricity_field makes a similar suspicious check.
monattack.cpp operation mattack:riotbot also checks this without excluding translucent.
However, hacking is_transparent to reject tiles with terrain with the TRANSLUCENT flag didn't have any effect.

I'll need help to find out why opening a translucent door has an immediate effect, while closing it has a delayed one (while it's immediate with a regular door in both cases).

**Closed** 2024-11-15 10:53 UTC
Labels: (S2 - Confirmed)
