### ISSUE TITLE
No longer able to 'c - Fill a container with water' from Kitchen unit in RV

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#33705] opened 2019-08-31 07:03 UTC
When you try to fill a container from the Kitchen unit in the Luxury RV (and reportedly other vehicles) you receive the response "There is not enough clean water left to siphon it". Your container remains empty.

1. Have an empty container
2. Stand next to vehicle Kitchen unit
3. Use 'e'xamine and 'c - Fill a container with water'

Expected result:
- Selection screen for destination container
- Selected container is filled with clean water

Actual result:
- Failure message in log
- No water transferred

Observed in Experimental Build 9562 and later.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1 64 Bit
- Game Version: 0.D-7086-gc8f1da6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    Beta National Guard Camp [national_guard_camp],
    No Fungal Monsters [No_Fungi],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by BlemishedClown** [comment] 2019-08-31 08:47
Can confirm this. It stopped working some time after build 9544 - ish.

**Comment by ZhilkinSerg** [comment] 2019-08-31 10:31
Duplicate of #33648

**Closed by ZhilkinSerg** 2019-08-31 10:31 UTC
Labels: (S2 - Confirmed), <Bug>, Vehicles
