### ISSUE TITLE
Mech Lab Finale: Mech Locker Bugged

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#38234] opened 2020-02-22 15:07 UTC
# Describe the bug

Mech spawned outside of computerized locker.

# Steps To Reproduce

I started a lab start, walked downstairs, stumbled through the finale level in the dark trying to find science ID card without attracting attention, stumbled into Spectre Mech  a few squares outside it's computer locked locker.  I reloaded and debugged in clairvoyance to take a screenshot.

# Expected behavior

Computerized Locker to contain the mech it says it does.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-11170-g64b5e04 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Arcana and Magic Items [Arcana],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
![bug lab finale](https://user-images.githubusercontent.com/54345792/75094630-0efbf680-555b-11ea-9f84-3bb039baa38a.png)

# Additional context

**Comment by l29ah** [comment] 2020-02-23 12:46
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33472

**Comment by KorGgenT** [comment] 2020-03-05 01:38
i think we'll keep this one, as it has screenshots

**Closed** 2022-03-03 18:46 UTC
Labels: <Bug>, Spawn, Monsters
