### ISSUE TITLE
Animals don't follow player up stairs

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#35665] opened 2019-11-23 01:21 UTC
# Describe the bug

I'm not sure if this is due to how AI and RNG works, but animals don't climb up stairs.
Save attached below.

# Steps To Reproduce

1. Create new world and character (evac).
2. Spawn cattle fodder and sheep.
3. Walk down the stairs and around until the sheep follows you down.
4. Go back up the stairs and walk around and try to get the sheep up.

# Expected behavior

Even with RNG and AI, I would expect the animal to follow up the stairs, especially in smaller stairwells (which would presumably increase the chance of the animal following).

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (Win7)
- Game Version: 0.D-9559-gcc3282c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[save_20191122201707.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882029/save_20191122201707.zip)
Save contains example of tamed animal in a house, and a shelter SW of current location.

**Comment by KorGgenT** [comment] 2019-11-23 03:51
are z levels on or off?

**Comment by new02DAY** [comment] 2019-11-23 16:24
> are z levels on or off?
Z levels are on, but align stairs are off.

**Comment by mouseturd** [comment] 2019-11-26 20:27
Confirmed I had this same issue with my pet horse. I don't have a save file to share though

**Comment by yowshi** [comment] 2019-11-30 15:39
yeah it is an issue with slimesprings as well

**Comment by borazan** [comment] 2020-04-02 10:35
I think align stairs might be causing this, haven't tried it myself tho

**Comment by matt32106** [comment] 2020-04-10 10:21
Same problem here, save attached
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4461086/save.zip)
 

- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-238-g6393a6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by DemonPikachu** [comment] 2020-04-28 19:32
In response to borazan, is that with align on or off? I have align stairs off (same as OP i think) and it's happening. Rip the animals stuck in the bottom of evac.

**Comment by matt32106** [comment] 2020-04-29 07:40
Here is a workaround: edit your .sav file (in cdda/save directory) and look for active monsters /pet name, then edit his position to the surface z-level.

**Comment by DemonPikachu** [comment] 2020-04-29 19:08
Sweet. I end up carrying the small ones up but man... turns out cows and stuff don't fit in petcarriers. :D

**Comment by matt32106** [comment] 2020-05-01 00:10
Just a reminder for people wanting to deal with this issue that i have attached a save in my comment from 20200410_1221

**Comment by Night-Pryanik** [comment] 2021-04-12 15:13
Tested right now on latest experimental as of April 12, 2021. Tamed sheep with fodder, and it correctly followed me downstairs in evac shelter.

**Comment by matt32106** [comment] 2021-04-14 21:27
IIRC th eproblem was with animal not following you when you go upstairs, not downstairs. My issue was getting my horse OUT of the underground evac shelter (ie upstairs) where he followed me happily.

**Comment by mouseturd** [comment] 2021-04-14 21:29
I can confirm that was original issue

**Comment by Night-Pryanik** [comment] 2021-04-15 03:00
Oh, sorry.

**Comment by LyleSY** [comment] 2021-12-04 22:24
Was this fixed by #50890 ?

**Comment by new02DAY** [comment] 2021-12-15 14:02
> Was this fixed by #50890 ?

Unfortunately not. "You lose hold of leash" occurs going up.
- Game Version: 373cf4e [64-bit]

**Comment by tinukedaya** [comment] 2022-02-09 21:04
It's not only the stairs. It's bridges as well.  I just started my new K9 officer and my dog is stuck on top of the bridge...

**Comment by LeahLuong** [comment] 2022-02-09 21:57
@tinukedaya You should prob start a new bug report as this would seemingly be an issue related to ramps, not stairs.

As a workaround, find some way of getting your dog into a mobile vehicle. NPC's seem to have no problem w/ traversing ramps while in vehicles.

**Comment by CrackerHax** [comment] 2022-09-09 02:38
This is still a problem

**Comment by Thesweetdragon** [comment] 2022-12-02 23:47
:T rip my dog. Can still confirm that animals refuse to go upstairs and are stuck downstairs.

**Comment by matt32106** [comment] 2023-04-05 16:21
@LyleSY yep came here to say this :)

**Closed** 2023-09-23 12:53 UTC
Labels: <Bug>, (S2 - Confirmed), Z-levels, Monsters, (P3 - Medium)
