### ISSUE TITLE
Possible to learn some recipes twice by disassembling

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#19836] opened 2016-12-23 13:12 UTC
It is possible to learn a recipe for an item you already know by disassembling the item, resulting in two identical recipes in the craft menu. Occurring for me with the fur sleeping bag, but I presume it happens for any recipe that is auto-learned but also learn-able via disassembly.

1) spawn new character with no skills
2) give some skills to learn new recipe (fur sleeping bag is tailoring 5, survival 1)
3) craft an item that can be learned automatically and with disassembly
4) disassemble it. 'You might be able to learn this recipe if you disassemble another"
5) repeat until you learn the recipe a second time

e: oh the second recipe disappears after saving+loading, bug will just repeat itself if you disassemble the item again though

**Comment by codemime** [comment] 2016-12-23 18:52
Dupe of #19061

**Closed by codemime** 2016-12-23 18:52 UTC
