### ISSUE TITLE
Debugmsg on unloading an ammo belt

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18489] opened 2016-09-23 05:23 UTC
Mapgen (the crate drop special) spawned minigun had an ammo belt. I unloaded the minigun and then the ammo belt and got a debugmsg.
The debugmsg was about trying to remove item that isn't there (I skipped it before I realized I should report it), but it should reproduce semi-reliably - it is unlikely that any mapgen generated guns with ammo belts will work fine if this one didn't.

Ammo and linkage were generated correctly.

**Comment by mugling** [comment] 2016-09-23 08:52
Can happen when you drop the item mid-unload due to inventory overflow.

**Comment by mugling** [comment] 2016-09-23 08:53
We should probably log all `debugmsg` to `stderr`

**Comment by mugling** [comment] 2016-11-27 16:22
Would be fixed by global item ID

**Comment by kevingranade** [comment] 2016-12-03 02:16
Is this a dupe or no longer happening? Those are the only valid reasons to close.

**Comment by mugling** [comment] 2016-12-03 11:58
The scope is much wider than the bug title and cannot be resolved without a complete rewrite of the item handling code to use persistent identifiers. That makes it an effective duplicate of #19437

**Comment by kevingranade** [comment] 2016-12-06 03:55
As I have outlined several times, uuids are not the only solution to this kind of thing.
More importantly, this is not a dupe of that issue, that issue is an approach that would potentially lead to resolution of this issue, but you could easily close that issue without resolving this one, or resolve this issue without implementing that one.

**Comment by mugling** [comment] 2016-12-07 01:55
> As I have outlined several times, uuids are not the only solution to this kind of thing.

What other options are there?

**Comment by Night-Pryanik** [comment] 2019-02-03 10:54
Can't confirm on 8496, closing. If this still an issue, ping me.

**Closed by Night-Pryanik** 2019-02-03 10:54 UTC
Labels: (S1 - Need confirmation), <Bug>, Magazines, Mapgen
