### ISSUE TITLE
vehicle collapsed to one tile

### ISSUE THREAD

**Issue by Frigus9085** [CleverRaven/Cataclysm-DDA#23723] opened 2018-05-12 20:39 UTC
Game version :0.C-27769-g382fcfa

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Disable NPC Needs, Simplified Nutrition

### Expected behavior
I would have gotten an error that stopped me from moving into a tile occupied by a vehicle.

### Actual behavior
I moved through/near the Luxury RV(somewhat scavenged) while dragging a double shopping cart and it collapsed into a single tile (a seat).
if you (e)xamine the tile, the vehicle screen still shows the entire vehicle.

Upon save and reload, the RV is back to its previous condition and placement.

### Steps to reproduce the behavior
unknown. 
![shopcart](https://user-images.githubusercontent.com/39224940/39961327-81d5f8c8-5601-11e8-90eb-a2899b1a6845.jpg)
![rv](https://user-images.githubusercontent.com/39224940/39961328-8647de58-5601-11e8-9e41-6a30b1441334.jpg)

.sav file:
https://www.dropbox.com/s/8soe309hnm6or3a/%23RXZlbHlubiBGcm9zdA%3D%3D.sav?dl=0

perhaps try to pull a double shopping cart near/onto a Luxury Rv?

**Comment by LyleSY** [comment] 2018-11-14 15:11
I tried to confirm this, but I couldn't get far enough. A double shopping cart (a standard cart, plus another tile added with identical parts and config) when dragged in any direction throws "The Shopping Cart collides with errors in movement code". I can't get it anywhere near a luxury RV. Running on Mac 10.13.6, Version 0.C-34211-gd10543db95
How out of date is 0.C-27769-g382fcfa ? Any chance this has been fixed already and I'm seeing a new issue?

**Comment by AMurkin** [comment] 2018-11-14 15:46
382fcfa is Thu May 10 07:53:14 2018. That was a pretty long time ago.

**Comment by mlangsdorf** [comment] 2018-11-14 21:54
I can't reproduce this on a current build.

**Comment by kevingranade** [comment] 2018-12-08 04:35
Closing due to lack of ability to reproduce, if you find a way to trigger this, please post it.

**Closed by kevingranade** 2018-12-08 04:35 UTC
Labels: (S1 - Need confirmation), <Bug>, Vehicles
