### ISSUE TITLE
With nutrition in the game, food products need to take the nutrition of their ingredients into account.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#20000] opened 2017-01-10 10:53 UTC
Because unfortunately, right now, if you stick to a vegan/carnivorous diet, you will lack either calcium or vitamin C, unavoidably. The farming system is a great help, as are eggs, but unfortunately, most foods get rid of the properties of the original plants, which means it's impossible to get calcium from gooseberry, soy, almonds, broccoli, avocado, or among stuff already ingame, pumpkin seeds, onion, or dandelion greens.

Additionally, the cooking system, as a whole, is a very big mess, and would probably do much better with genericized recipes, with nutrition and enjoyment based partially off their ingredients, such as "[plant] sauce", "pasta with sauce", "[meat/veggy] lasagna with [sauce]", "meat sandwich", "meat and [plant] sandwich", etc.

If that were going to happen, dehydrated/irradiated products should probably become a "status condition" of the food, akin to (old) or (rotten). Probably a significant undertaking, but I feel like this is more or less what the game needs to sort out the mess that food is in C:DDA. 

Thoughts?

**Comment by CoroNaut** [comment] 2017-01-10 12:39
I take a multivitamin to sort out all of of the vitamin problems, but I do agree that they should take the ingredients into account. The enjoyment you get however would be tricky to implement in this manner considering cooked foods, fried foods, ect. Also, if you change the stats of the product for every combination of good or rotton fruits/vegetable/meats, they won't stack in the inventory. I do like the idea if you can get past these problems.

**Comment by Coolthulhu** [comment] 2017-01-10 13:41
Inherited features are intended to happen some day, but they require a proper UI first.

**Comment by Asmageddon** [comment] 2017-01-10 15:22
Sort alternatives(tools, components) by available-first, and label them with 1,2,3... for tools and a,b,c... for components, to allow toggling/choosing which to use? 

As for the inheriting itself, Lua? I feel like way too many things are hardcoded in the game that could and should be ported to Lua - most item effects, many tags, clothing mods, etc.

**Comment by Zireael07** [comment] 2017-01-10 15:30
The problem is not code, the problem is UI for inherited features. The game already has a problem with displaying some recipes and descriptions which are very long.

**Comment by Coolthulhu** [comment] 2017-01-10 15:51
The code for crafting is quite convoluted and very ID-heavy. As a result, filtering items by something other than location type (on person vs on map vs on vehicle, not "here" or "1 east") and ID is limited.
To fix that, a significant part of component selection code would have to be rewritten.

**Comment by codemime** [comment] 2017-01-10 22:04
:champagne: :champagne: :champagne:    
It's a Jubileeeeee!

**Comment by Asmageddon** [comment] 2017-01-10 22:32
Ah dang :-/

**Comment by ZhilkinSerg** [comment] 2017-01-11 17:52
That's what happen with human beings in real life - vegan/carnivore diets lack nutrients.

**Comment by Asmageddon** [comment] 2017-01-11 20:07
Not with modern plant-based food variety, no. My personal gripe is the reliance on eggs/vitamins, which are more limited than farmable plants/meat for calcium.

**Comment by keyspace** [comment] 2017-01-29 01:29
> Inherited features are intended to happen some day

This is possibly a duplicate of: #19115

**Comment by Leland** [comment] 2017-05-08 17:41
@keyspace indeed.

Closing – feel free to continue discussion in either of the above issues.

**Closed by Leland** 2017-05-08 17:41 UTC
Labels: Suggestion (Discuss), Vitamins
