### ISSUE TITLE
grenade launcher ammo does not use extended effects

### ISSUE THREAD

**Issue by cerix2077** [CleverRaven/Cataclysm-DDA#44198] opened 2020-09-15 18:52 UTC
# Describe the bug
grenade launcher rounds with the exception of gas grenades are not activating their effects such as explosive or incendiary 

# Steps To Reproduce

1. spawn in a 40x46mm or 40mm launcher and various ammo for it
2. fire the rounds and see that only the gas grenades have any unique effect

# Expected behavior
each round should be using its unique effects

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5927-g27d4c34 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

I messed around with 40x46mm.json and found that calling an effect in the abstract works but any effects called with extend eg.( "extend": { "effects": [ "EXPLOSIVE_m433" ] } ) won't activate. This is also why gas grenades are the only ones that work as they work through "drop" and not "extend".

**Comment by ZhilkinSerg** [comment] 2020-09-15 20:39
Yes, extend does not work too well with item definitions as they are not using generic factory.

**Comment by ZhilkinSerg** [comment] 2020-09-17 08:14
Duplicate of #42795

**Closed by ZhilkinSerg** 2020-09-17 08:14 UTC
