### ISSUE TITLE
We can no longer delete auto-notes, they are always re-created

### ISSUE THREAD

**Issue by TheKassaK** [CleverRaven/Cataclysm-DDA#59582] opened 2022-07-25 09:16 UTC
### Describe the bug

I think that was not the case before, but today we can no longer delete an auto-note generated once we visited the place.

I used to delete the auto-note once I visited the place, but now they are automatically re-created when we pass by.

We cant delete/edit auto-notes anymore.

### Steps to reproduce

1. Go close to a place with an auto-note (Supply drop, College Kids, Drug Deal etc...)
2. Delete the auto-note
3. Close the map
4. Re-open the map => the auto-note was re-created

### Expected behavior

I expect the auto-note to be permanently deleted

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: b86bfea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills]
]

**Comment by irwiss** [comment] 2022-07-25 10:25
Tested - it's bugged exactly with the steps to reproduce

**Comment by mlange-42** [comment] 2022-07-25 10:45
Was probably introduced by #59177

**Comment by ZhilkinSerg** [comment] 2022-07-25 11:20
Duplicate of #59393

**Closed** 2022-07-25 12:12 UTC
Labels: (S3 - Duplicate)
