### ISSUE TITLE
Rewarding an item from merchant bug (mission)

### ISSUE THREAD

**Issue by Neversalimus** [CleverRaven/Cataclysm-DDA#19225] opened 2016-11-10 06:45 UTC
Ok, to reproduce issue go to refugee center, take a mission from merchant, complete it, and when i choose an item to reward he opens just a regular trade menu, so i must pay for my reward item (and not for free as intended).

So actually choosing an item reward from merchant is pointless.

**Comment by Leland** [comment] 2017-08-24 03:21
Duplicate of #18893, closing.

**Closed by Leland** 2017-08-24 03:21 UTC
Labels: Bug, Mission
