### ISSUE TITLE
Companion NPCS attack Zlaves

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#21254] opened 2017-06-16 21:15 UTC
<a href="http://imgur.com/R6DziBY"><img src="http://i.imgur.com/R6DziBY.png" title="source: imgur.com" /></a>

0.C-22649-gd13eca7 (tiles)

Enslave a zombie, find a NPC, recruit him or her, and get her within close proximity of the Zlave. The NPC will start attacking the poor, defenseless creature that can't even harm anybody.

**Comment by CoroNaut** [comment] 2017-06-17 02:49
Never in my many years of cata have i ever made a zombie slave, but this is still an outrage! lol.

**Comment by Taberone** [comment] 2017-06-19 20:23
It should be noted that this happens if you play as a different character in the same world. Heres how it went when I played Cataclysm again today:

Survivor A enzlaves a bunch of zombies. Survivor A saves and quits.
Survivor B spawns in the world, makes friends with the starting NPC, finds the zombie Zlaves, and her NPC pal starts attacking the Zlaves. Survivor B saves and quits.
Survivor A comes back with a companion. This companion doesn't attack the Zlaves. Survivor A saves and quits.

**Comment by kevingranade** [comment] 2017-09-19 07:48
I'm not at all sure this is a bug.  Maybe avoid it if the NPC in question is a psychopath, but assuming that all survivors are going to be OK with "tamed" zombies is quite a stretch.

**Comment by kevingranade** [comment] 2018-01-03 16:53
If someone feels like having npcs with certain traits or personalities refrain from attacking zombie slaves, they can feel free, but I'm closing this for now as "working as intended".

**Closed by kevingranade** 2018-01-03 16:53 UTC
Labels: NPC, Suggestion (Discuss)
