### ISSUE TITLE
Crash: Unloading a plastic bag of marshmallows

### ISSUE THREAD

**Issue by micage2** [CleverRaven/Cataclysm-DDA#39377] opened 2020-04-08 19:16 UTC
Unloading a plastic bag of marshmallows (U) lead to a segmentation fault.
Status message indicated that the unloading was successful but my inventory still showed the (loaded) plastic bag of marshmallows. Unloading it a second time lead to the crash.

OS: OS X 10.13.6
Game Version: 0.E-409-gd8ae8da570

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4452356/crash.log)

**Comment by bcronrath** [comment] 2020-04-08 19:49
I think this might be related to #39375, I submitted it for liquids but upon further examination I think *any* container is affected.

**Comment by KorGgenT** [comment] 2020-04-08 20:36
is this fixed with this PR applied? #39354

**Comment by irwiss** [comment] 2020-04-08 21:02
![image](https://user-images.githubusercontent.com/6560075/78833167-171dd180-79f5-11ea-8710-aa4abd37f6f5.png)

Seems unloading random containers causes a crash, that was a bag of tobacco.

Steps to reproduce:
- Create new world with no mods
- Play now (or any other way to get into the game)
- Optional if you don't get one - wish for water in a bottle
- `U` to unload the water bottle

And you get the stack trace above

**Comment by KorGgenT** [comment] 2020-04-09 01:14
I'm fairly sure this bug is fixed with the aforementioned pr, and i'm not sure about the "some items still leave items with 0 charges". i can't reproduce either thing.

**Comment by irwiss** [comment] 2020-04-09 01:32
@KorGgenT the 0 charges things is what I mentioned on discord, steps;
- wish for 2 bottles of water
- drink one,
- reload it from the other

you should have a bottle of water with no charges on it

**Comment by KorGgenT** [comment] 2020-04-10 00:12
i'm gonna close this issue as fixed, a new issue should be made for the 0 charges thing, instead of keeping this issue open for a comment

**Closed by KorGgenT** 2020-04-10 00:12 UTC
