### ISSUE TITLE
Necropolis(?) grocery store's gate or opener has incorrect starting position

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#10957] opened 2015-01-22 02:21 UTC
I'm pretty sure what I found was a necropolis - pretty nice buildings with a bunch of craters, and the grocery store layout didn't match the normal ones, the only other being labeled 'necropolis' in the JSONs.
The grocery store had a garage-type attachment, containing a lot of food crates and a metal gate. The gate started in the closed position, but when I used the gate opener the chat log said I closed the gate (and it did, indeed, remain closed). Using the gate opener again properly opened the gate.

**Comment by DavidKeaton** [comment] 2015-01-23 20:08
I ran into a Necropolis to try this out, couldn't seem to reproduce.

**Comment by mugling** [comment] 2016-06-04 22:23
Much of this mapgen was overhauled by @Mshock777. Closed as no recent reports

**Closed by mugling** 2016-06-04 22:23 UTC
Labels: Bug, Confirmation Needed

**Comment by Mshock777** [comment] 2016-06-05 14:28
My bad: forgot to mention this in my PR. And yes, it seems to be fixed.
