### ISSUE TITLE
Game Crash when switching fire modes with a knife attachment

### ISSUE THREAD

**Issue by Vovkalak** [CleverRaven/Cataclysm-DDA#33585] opened 2019-08-27 14:22 UTC
# Describe the bug

Game crashes when attempting to switch fire mode on AKRO-388 Laser SMG (or any weapon it seems) with a combat knife attached

# Steps To Reproduce

Obtain a firearm with a knife attachment
Switch fire mode a few times

# Expected behavior

Game crashes
likely because it switches to a "knife" fire mode and knife cant shoot(???)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-7009-gd8f806f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Cataclysm++ [Cata++],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mutation Changes [Mutation_Changes],
    Sleep Deprivation [sleepdeprivation],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

It seems to happen with any weapon that has a knife attachment

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3546558/config.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3546559/Save.zip)

**Comment by Zireael07** [comment] 2019-08-27 18:24
Quite a lot of mods you've got here. Since this looks like a reoccurrence of a bug that was already fixed, can you first check if it isn't a mod that's messing things up (by removing them one by one and seeing if situation changes)?

**Comment by ZhilkinSerg** [comment] 2019-08-31 10:27
Duplicate of #30676.

**Closed by ZhilkinSerg** 2019-08-31 10:27 UTC
