### ISSUE TITLE
Pls fix claws/natural weapon mutations

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#57569] opened 2022-05-09 02:42 UTC
### Describe the bug

Pls :(

### Steps to reproduce

1. Make a character with claws
2. Claws don't still work :,(

### Expected behavior

My character isn't causing bleeding pls it's been months my family is starving because I can't hunt mutant bears for them how long must we suffer under this tyranny

### Versions and configuration

build type: windows-tiles-x64
build number: 2022-05-07-2212
commit sha: 0a6883a91aeb2ea93cdcc7d9aa301487c0e8d4ea
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/0a6883a91aeb2ea93cdcc7d9aa301487c0e8d4ea

**Comment by Testudo-Cultu** [comment] 2022-05-09 02:57
The issue with "attack vectors" that causes this also causes Taekwando to scale damage based on your held weapon (#57155) and is why worn items that should affect your unarmed damage don't actually do anything.

**Comment by Termineitor244** [comment] 2022-05-09 03:18
You already reported this issue with #56439, which is probably a duplicate of #56138, the developer working on the PR that would have fixed this problem is still missing after going sick a little more than a month ago, so there is not much one can do until its return, if you want to focus more attention on this issue, you can ask on discord about it.

**Comment by ZhilkinSerg** [comment] 2022-05-09 06:52
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56439

**Closed by ZhilkinSerg** 2022-05-09 06:52 UTC
Labels: (S1 - Need confirmation)
