### ISSUE TITLE
Smartphone (UPS) passive effects (time, calories/vitamins) stop working when put in a Smartphone Case

### ISSUE THREAD

**Issue by SolidMilk19** [CleverRaven/Cataclysm-DDA#69258] opened 2023-11-11 08:44 UTC
### Describe the bug

If you put a Smartphone (UPS) into a Smartphone Case, its passive effects, such as displaying time and calories/vitamins consumed suddenly stop working.

Edit: At some point it started to function again as expected, despite still being in the case.

### Attach save file

N/A

### Steps to reproduce

1. Obtain a Smartphone (UPS)
2. Obtain a Smartphone Case of any kind
3. Drop anything your character is holding or wearing that might display time or tracks calories/vitamins
4. Insert the Smartphone (UPS) into the Smartphone Case
5. Watch as the time display turns into ??? and the calories/vitamins menu turns from numbers to words

### Expected behavior

A regular phone case doesn't make it impossible to still see your phone display, even if fully waterproof, so it should continue to work as if there was no case on the smartphone.

### Screenshots

![ph01](https://github.com/CleverRaven/Cataclysm-DDA/assets/68878873/c4d20ea7-6e26-4aba-903b-c54ec59613fd)
![ph02](https://github.com/CleverRaven/Cataclysm-DDA/assets/68878873/a2f4e9af-ee84-4151-861d-d578d200e7b6)

### Versions and configuration

- OS: Windows 10
- Game Version: f5e7ef4
- Graphics Version: Tiles
- Ingame Language: English
- Mods Loaded: [dda] [no_npc_food] [personal_portal_storms] [no_fungal_growth]

**Comment by JeveGreen** [comment] 2023-11-11 13:14
I think it has something to do with the insert mechanic, as the passive effects will stop working whenever you insert a smartphone into a pocket rather than just picking it up. I've found a workaround that by dropping the case with a smartphone and then picking it back up, the passive effects will start working again. Alternatively, you can save, exit and then reload the game, and the passive effects will start working again.

**Comment by Terrorforge** [comment] 2023-11-11 16:28
I'm having the same problem with (apparently) ALL items. If I manually insert them somewhere, my binoculars don't reveal the map any more, Whistle Multitool stop telling the time and my Smooth Disc artifact stops providing its +16 speed bonus. Here's my save: 
[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325983/Mindssachusetts-trimmed.tar.gz)

**Comment by Kamayana** [comment] 2023-11-11 18:40
Duplicate of #68075. Working on a fix now.

**Closed** 2023-11-12 08:12 UTC
Labels: (S3 - Duplicate)
