### ISSUE TITLE
Tying up horse deletes equipped player bags (along with everything in it) v10819

### ISSUE THREAD

**Issue by VaneFox** [CleverRaven/Cataclysm-DDA#41966] opened 2020-07-09 04:20 UTC
Tested on a few backups, not certain if it's because of mods, however this did occur every time I tried it.

# Describe the bug

Tying a horse (or any animal for that matter (other animals untested)) down will delete the backpack you have equipped that contained the rope (only tested with short cordage rope), along with all the contents.

# Steps To Reproduce

Described as produced from my game.
1. Craft short cordage rope.
2. Make sure it is inside the backpack. (Other bag types untested)
3. Tie the horse up.

# Expected behavior

Bag should have vanished right away.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3894-g4929649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    More City Locations [cityside],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Nechronica Redux [Nechronica_Redux],
    <color_light_red>Secronom</color> [secronom],
    Whaleys Collectables [collectablemod],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Mutation Changes [Mutation_Changes]
]

**Comment by UmbralReaper** [comment] 2020-07-09 11:06
I tested this on core C:DDA (DDA and No NPC Needs) and, regardless of contents of the container, the type of container, or the animal it is used on, if it contains the rope it is deleted completely.

**Comment by hexagonrecursion** [comment] 2020-07-09 12:27
duplicate of #40393

**Closed** 2020-07-09 14:27 UTC
