### ISSUE TITLE
"cannot stash can of X drink while it's not empty"

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41113] opened 2020-06-06 11:53 UTC
# Describe the bug

Trying to pick up can of any drink results in this menu, with options to either spill the drink then stash empty can, or wield the can.

# Steps To Reproduce

Make a player with some storage capacity, find can of drink, try picking it up via either 'g' or AIM. Bonus point for wielding MM blade while doing it.
Note that stepping on the tile with can then using 'i'nsert works fine.

# Expected behavior

Pick it up.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment] 2020-06-06 16:39
Appears to be a duplicate of #40127 and #40658

**Closed** 2020-06-06 17:19 UTC
