### ISSUE TITLE
Go-bags only give non-fitting apparel

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#24060] opened 2018-06-21 06:00 UTC
### Expected behavior
When a go bag is disassembled into the various bits of military apparel there should be the standard chance of having some of it be fitting
### Actual behavior
None of the clothing/armor is fitting
### Steps to reproduce the behavior
Disassemble a go-bag

Something I’ve noticed for a while and keep forgetting to open an issue for. It makes go-bags a lot less useful than they should be and makes the profession that starts with one (National Guard, I think?) handicapped by having most of their starting equipment be ill fitting.

**Comment by Night-Pryanik** [comment] 2018-06-21 06:08
Duplicate of #22622.

**Comment by 1skandar** [comment] 2018-06-21 06:28
No, it’s not. #22622 only discusses go-bags that are filthy disassembling into filthy components. This is NOT that. My issue is that a go-bag only disassembles into components that are not fitting. Separate issue entirely.

**Comment by Night-Pryanik** [comment] 2018-06-21 06:31
Ohh, sorry, had to sleep more often.

**Comment by 1skandar** [comment] 2018-06-21 06:39
Mind you, I would say that issue is related. I’d bet all components from an item that is disassembled inherit the properties of that item. And since a go-bag can’t be fitting all components that come from it won’t be fitting. If so, the solution to that problem, changing the go-bag to an activated item instead of a disassembled one, is likely what we need here as well.

**Comment by Night-Pryanik** [comment] 2018-06-21 06:42
> If so, the solution to that problem, changing the go-bag to an activated item instead of a disassembled one, is likely what we need here as well.

Yes, for go bags and for MREs.

**Comment by BorkBorkGoesTheCode** [comment] 2018-06-21 06:50
The go bag item can be replaced with itemgroup collections and `"custom-flags": [ "no_auto_equip" ]` in professions.

**Comment by 1skandar** [comment] 2018-06-21 07:05
That’ll fix half the issue. And, in fact, is likely the best solution for professions since in that specific case it’d be kinda weird if the go bag didn’t turn into fully fitting gear.

**Closed** 2019-06-26 05:59 UTC
Labels: Items / Item Actions / Item Qualities
