### ISSUE TITLE
Peeking on top level of subway station just moves your character to second set of stairs

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53388] opened 2021-12-12 11:19 UTC
### Describe the bug

Not sure what else to say, every subway station I've tried so far peeking either doesn't do anything at all or just moves (not peeks, but *moves*) character to second set of stairs on same floor.

### Steps to reproduce

1. Visit subway station top/ground level
2. Try to peek

### Expected behavior

Peeking doesn't move character. I understand the technical difficulties of peeking, so just not being able to peek is preferred to moving character to a different position.

### Versions and configuration

These are the outputs for the experimental build of commit 00a0caa

linux tiles build

**Comment by ZhilkinSerg** [comment] 2021-12-12 12:03
You stand on one tile with stairs, peek on a different z-level and find yourself on a different tile with stairs?

**Comment by mkrutov** [comment] 2021-12-12 13:44
@ZhilkinSerg , yes, screenshots are: prepeek
![Screenshot_20211212_144304](https://user-images.githubusercontent.com/48674477/145714788-fb9af027-6d50-4bbc-a3ab-43525fff4a16.png)


post peek:
![Screenshot_20211212_144415](https://user-images.githubusercontent.com/48674477/145714799-059a2ee5-608d-4ac4-90b0-e38bce19cfa1.png)

moving post peek moves me from position in second screenshot. peeking from post-peek position does nothing.
postpeek:

**Comment by PatrikLundell** [comment] 2021-12-12 13:52
My guess (without anything else to back it up with) is that it's caused by the disconnect between the stairs on the different levels, and I would further guess that it behaves the same in other places where movement between levels results in a teleport.

**Comment by mkrutov** [comment] 2021-12-12 13:53
[DEBUG.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7698854/DEBUG.zip)


Peeking from this position moves character 2 tiles right instead of peeking or doing nothing. Also it is annoying that github does not support .tgz archives attachement.

**Comment by mkrutov** [comment] 2021-12-12 13:55
@PatrikLundell , it just does nothing when it can not peek in labs and it also does nothing on some stairs in subway stations. However, it is very common for peeking to teleport you specifically in subways.

**Comment by wapcaplet** [comment] 2021-12-13 03:58
Sounds like an old bug #36833 where you could teleport across a house by peeking downstairs.

**Comment by wapcaplet** [comment] 2022-01-14 13:51
See also #49162

**Comment by Night-Pryanik** [comment] 2022-01-26 17:32
Closing as duplicate.

**Closed by Night-Pryanik** 2022-01-26 17:32 UTC
Labels: <Bug>, (S3 - Duplicate), Map / Mapgen, Z-levels
