### ISSUE TITLE
item suitcase_m does not fit in container suitcase_l when spawning item group hotel_luggage

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#66791] opened 2023-07-10 03:55 UTC
### Describe the bug

 DEBUG    : item suitcase_m does not fit in container suitcase_l when spawning item group hotel_luggage.  This can be resolved either by changing the container or contents to ensure that they fit, or by specifying an overflow behaviour via "on_overflow" on the item group.

 FUNCTION : put_into_container
 FILE     : C:\Users\PC1\Source\Repos\Cataclysm-DDA\src\item_group.cpp
 LINE     : 139
 VERSION  : 0.G-2920-g7d6bf68235

### Attach save file

n/a

### Steps to reproduce

Seems to be chance based, `hotel_luggage` has `suitcase_l` as container, but the group nesting not always results in a spawn of `suitcase_m`.

### Expected behavior

Consistent item groups without errors.

### Versions and configuration

6fac4ab

### Additional context

Related to #62446

**Comment by mqrause** [comment] 2023-07-11 21:03
Well, went digging through the groups now. `suitcase_m` is part of the `costume_accessories` group, which is included in `hotel_luggage` though `accesories_personal_unisex` > `accesories_personal_unisex_child`. If I'm not mistaken the chance for one to spawn is 20% * 1% * 4% = 0.008%. With all the nesting it's also possible other nested groups need to spawn enough items so the suitcase won't fit anymore. I probably won the lottery to even hit it, but the problem is still real.

**Comment by RenechCDDA** [comment] 2023-07-12 22:08
> If I'm not mistaken the chance for one to spawn is 20% * 1% * 4% = 0.008%

Really testing the extent of my love, huh?

>accesories_personal_unisex > accesories_personal_unisex_child

There's a collection with >100 prob of spawning, but that doesn't seem to be directly causing problems. (Testing shows that does not spawn >1 occurrences per spawn regardless of what combination of nests or weird stuff you do)


I was able to reproduce this after modifying the item groups to force spawning all collections(setting prob to 100) and only spawning the suitcase_m in the costume_accessories distribution.

Do you have an opinion on how to resolve this?

**Comment by RenechCDDA** [comment] 2023-07-12 22:41
Yeah, removing the suitcase seems to be the way forward. I tried moving it to being the *group's* container-item in case that would still allow the rest to function, but that just results in it happening *more often*.

**Closed** 2023-07-15 05:05 UTC
Labels: (S2 - Confirmed), Spawn, Items: Containers
