### ISSUE TITLE
Move item stack is muuuuch quicker than move all items with a single item type

### ISSUE THREAD

**Issue by applehoro** [CleverRaven/Cataclysm-DDA#19850] opened 2016-12-26 07:15 UTC
I've searched for this issue and didn't find anything so I post it here.

What happens: I chop down the tree into the logs and then move them all around by advanced inventory management. When I use "move all items", it takes about six in-game minutes, but when I use "move item stack", it takes about ten in-game SECONDS. Looks like bug to me :3 

Also, sorry for my poor english.

Also #2, it happens in the latest build, and I don't know, is it happenning in the stable build.

**Comment by Asmageddon** [comment] 2016-12-27 19:26
I also noticed this, move all causes the game to move every single item individually, taking time, and also slowing down due to the constant screen refreshing caused by the advanced items menu opening/closing, whereas moving an item stack appears to move it whole in one short go. Unless there's something weird going on and causing this difference, it sounds like something that should be an easy fix.

**Comment by gcaliber** [comment] 2016-12-29 04:05
Picking up and dropping items via advanced inventory vs. the drop and pickup commands has the same issue.

**Comment by Leland** [comment] 2017-05-04 21:19
Make sure to see the in-depth discussion that happened over at #9392

**Comment by Coolthulhu** [comment] 2017-07-02 00:00
I'm trying to untangle it and holy fuck advanced inventory menu code is a multi-level spaghetti weave where things are all encapsulated in such a way that you can only access the useless functions.

The problem is caused by the move-one being hardcoded special case as opposed to using the same code as move-all.

**Closed** 2017-07-09 09:28 UTC
Labels: Bug
