### ISSUE TITLE
MA spawning is broken

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70906] opened 2024-01-14 02:05 UTC
### Describe the bug

I keep trying to make a character, but no matter what I put in as the city or location, it can't find one in the radius of 3 overmaps, making it functionally unusable

### Attach save file

N/A

### Steps to reproduce

Just try to make a char w/ MA, & weep

### Expected behavior

For it to work

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2428 (23H2)
- Game Version: cbdb87e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment] 2024-01-14 13:37
Dupe of #70526

**Closed** 2024-01-14 15:09 UTC
Labels: (S1 - Need confirmation)
