### ISSUE TITLE
firearm repair kit does not allow metal sawing without charges

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#46346] opened 2020-12-26 21:44 UTC
# Describe the bug
Firearm repair kit does not allow metal sawing (like to saw through bars) without charges.
# Steps To Reproduce
1. Make a player with a firearm repair kit and no charges.
2. Try to cut through bars.
3. Fail.
# Expected behavior
Firearm repair kit should allow the use of tools presumably within the kit to be used as the tools they were before they were put into the kit. Hacksaw requires no charges to cut through bars, so the firearm repair kit should not require them for this, either.
# Versions and configuration
 - OS: Win7x64
 - Game Version: 0.E-8475-g41708d3
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC needs

**Comment by PaulBlay** [comment] 2021-01-04 16:04
Possibly the Firearm repair kit needs to be treated more like a specialized container? Like the Toolbox. I'm not sure how that would play out with the actions that currently require a Firearm repair kit.

**Comment by misterprimus** [comment] 2021-01-04 22:26
> Possibly the Firearm repair kit needs to be treated more like a specialized container? Like the Toolbox. I'm not sure how that would play out with the actions that currently require a Firearm repair kit.

Yes. The only question would be: how to handle the battery usage? More specifically, what function of the firearm repair kit or gunsmith repair kit even requires battery power IRL?

**Comment by int-ua** [comment] 2021-01-14 14:27
Duplicate of #30137.

**Closed by int-ua** 2021-01-14 14:27 UTC
