### ISSUE TITLE
The vehicle sucked up the sewage from the sewer.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#26336] opened 2018-10-21 13:45 UTC
**Describe the bug**  
The vehicle sucked up the sewage from the sewer.

**To Reproduce**  
1. Entering the sewer.
2. Unfold a folding bike.
3. Ride the bike.
4. It will turn sewage into flat land.

**Expected behavior**  
Nothing happens.

**Screenshots**  

https://discourse.cataclysmdda.org/t/my-bicycle-sucked-up-the-sewage-from-the-sewer/16503

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version: 0.C-31136-g79d9903
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by Zireael07** [comment] 2018-10-21 13:46
It's not sucking up, it's to simulate a vehicle displacing liquids (usually water).

**Comment by ZhilkinSerg** [comment] 2018-10-21 14:13
#25388

**Comment by Night-Pryanik** [comment] 2018-10-21 14:36
Not a bug, closing.

**Closed by Night-Pryanik** 2018-10-21 14:36 UTC

**Comment by Night-Pryanik** [comment] 2018-10-21 16:17
The mechanic could get some love, but in general it's WAI.
