### ISSUE TITLE
Sights with no aim cost have incorrect dispersion

### ISSUE THREAD

**Issue by Cosmitz** [CleverRaven/Cataclysm-DDA#21625] opened 2017-08-14 02:31 UTC
Aim cost 0 or JSON undefined with a sight without `DISABLE_SIGHTS` flag added makes it not grant the sight dispersion. If it has the `DISABLE_SIGHTS` flag and no/aim cost 0, it sets sight dispersion to 600 for a reason I'll not want to get into yet.

I assume just enforcing `mod->aim_cost <= 0` strictly to `mod->aim_cost < 0` will fix this issue but i am not a coder.

----

https://github.com/CleverRaven/Cataclysm-DDA/blob/a580df2285f843adf11219124b69761cff5e8a1f/src/itype.h#L444-L445

and:

https://github.com/CleverRaven/Cataclysm-DDA/blob/bec137ae69c30ebe5241f95abf6e251b694e45a4/src/item.cpp#L3989-L4006

**Comment by Leland** [comment] 2017-08-18 16:43
@Cosmitz marked up your issue slightly for clarity.

**Comment by Cosmitz** [comment] 2017-08-18 16:47
Thanks. Already working on it myself over here with Cool': #21635 
 
But this is a bit deep in code for me. :) Hopefully we'll get it hammered out this week.

**Comment by kevingranade** [comment] 2017-08-30 06:00
What's the issue here?
Guns have a default sight_dispersion of 120, or a sight_disperson set in json, unless they have the default sights disabled via the DISABLE_SIGHTS flag.
Every gunmod with the SIGHT_DISPERSION flag sets sight_dispersion and aim_time.
Gun mods with a negative sight_dispersion or or aim_cost (the default) do't count as sights, so are ignored.

Did you just read the code and open the issue?  You need to reproduce the issue in the game for it to be valid.

**Comment by Cosmitz** [comment] 2017-08-30 10:36
This has been fixed in #21635 and waiting merging.

The core matter was that undeclared aim_cost for a sight would, in-game, either ignore its sight dispersion bonuses altogether or erroneously list a 'buff' of 600 sight dispersion depending if it had DISABLE_SIGHTS or not.

**Comment by kevingranade** [comment] 2017-08-31 01:54
Ignoring the bonus is intended, but listing sight dispersion as 600 in item info is a problem, what gun does this happen with?

**Comment by Cosmitz** [comment] 2017-08-31 08:26
Default game, with no gun mods as they all have a set aim_cost, but i stuck upon the issue while fiddling with bows and the bow sight, since it doesn't have the DISABLE_SIGHTS flag set. Without that and with an unset/0 aim_cost, the game treats/shows it as a 600 sight dispersion. I'm not certain if it's the sight dispersion itself maxing out, or just a flaw in the displayed item info, however, that PR should sidestep this issue.

**Comment by kevingranade** [comment] 2017-08-31 14:58
It's just a display issue, the game will never try to use that sight.

**Comment by Night-Pryanik** [comment] 2017-09-02 04:15
Fixed by #21635.

**Closed by Night-Pryanik** 2017-09-02 04:15 UTC
Labels: Aiming, Balance, Bug, Code
