### ISSUE TITLE
Planters that actually do something

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#19699] opened 2016-12-09 19:54 UTC
A quick search of issues brings up nothing, so I figured I'd make a new one. It occurs to me that while there's both mobile and stationary gameplay styles, farming by its nature excludes the former. Gardening, however, technically shouldn't have to. It feels a bit micromanagement-ish to make dirt a craftable (we already have sand), but what about hydroponics? That would just need a container, water, and fertilizer for the crafting recipe. For the light, it could maybe be an acceptable break from reality to use ambient light. If necessary, though, I don't see why it can't be a light source, too. Especially if you hook it to a vehicle power system. On that note, though, how exactly does the current farming code work? If it uses field effects, I was thinking that making a vehicle part would work, have it be a container, then drop seeds in and wait. If it's easier, the nutrient water solution could be separate, that way generic tanks could be filled. The part could work somewhat like a kitchen unit/minifridge in that it would draw from a tank and power supply to function properly, and pull from the farming code that way? I'd really love to see this implemented. I just have no real idea how feasible it is.

**Comment by Regularitee** [comment] 2016-12-09 20:01
Given the high premium on indoor space in vehicles, and having to contend with lighting issues, wouldn't it be better to make planters a roof-mounted thing? That way they can share most of their behaviour with crops: they'll get sunlight during the day, water when it rains, etc. 

The only issue would be how to reach them. I guess they'd be limited only to roof edge tiles.

Alternatively, what about something algae based? Having a roof-mounted unit that generates algae (like solar panels or funnels do with their respective resources) as a liquid. This would allow it to use the pre-existing liquid tanks rather than having its own new type of storage. That liquid algae can then be used to created nutrient bars or fertiliser or something.

**Comment by railmonkey** [comment] 2016-12-09 20:08
I didn't think about roof mounting. While the thought of speeding around at 80 mph with corn stalks growing on the roof is amusing, it seems like it would be problematic. Valid point about inside space, but then again, this suggestion is made with rolling bases in mind. Most players would have either built their own from scratch or, more likely, tacked on more room to an existing vehicle. And if you already have that mindset, it's not such a stretch to sink time into making further accommodations, right? As for the liquid tanks, they aren't specific anymore. As long as there's an empty tank, it would work.

**Comment by Regularitee** [comment] 2016-12-09 20:41
The thing is, I don't see indoor vehicle farming being viable, rolling bases or no. 

The FAO of the UN estimates the average Western diet and climate means meeting the annual food consumption of one person requires 0.5 hectares (~ an American football field) of farmland. So even the largest vehicles in the game would barely put a dent in any food needs.

Second, there's the issue of light. Either the vehicle will have to have a giant, glass outer shell to provide natural light (with its own, painfully obvious disadvantages), or draw large amounts of power to run solar lamps. The latter effectively prevents the vehicle from ever using hybrid/electric power to move, meaning greatly increased fuel consumption (and kind of defeating the entire point of self-sufficiency that farming aims for).

Third, the opportunity costs of increasing vehicle size. Larger vehicles means worse off-road ability, more maintenance (wider cross-section hitting more objects when travelling), and most importantly, greater weight and therefore fuel consumption. This fuel lost might be otherwise used to travel to new food sources, like stores or fishing locations.

So, yeah, basically many drawbacks for such a tiny amount of food gain. Unless vehicle farming becomes 
The thing is, I don't see indoor vehicle farming being viable, rolling bases or no. That's why I suggested something more space efficient like futuristic algae-protein growth, so we can at least hand-wave away these issues with SCIENCE! (I think it's the year 2040 or something according to the storyline, anyway).

**Comment by railmonkey** [comment] 2016-12-09 20:57
Mn. Okay, fair point about space, but I'managed not talking about completely replacing food sources with farming. Just supplementing what can be gained from city raids. That drastically reduces the space needed, depending on how much variety you want. Remember, too, that I specified gardening. Not major crops like grains, but things like carrots and tomatoes. As far as powering the necessary lights? Dude. Minireactors. And the futuristic handwoven was what I was going for with hydroponics. Pretty sure we're on the same page as far as the nutrient thing goes. Just slightly different approaches, is all.

**Comment by Tharn** [comment] 2016-12-10 08:05
Planters might make sense for greenhouses. Constructions built with plenty of plastic sheets (out of bags?) to trap the heat and keep farming on a small scale viable during winter. Here you want planters so you can get the soil temperature up. Hydroponics would belong there, as well. But that'd be a whole other project.

I don't think plants and vehicles have or should have anything to do with one another. Doesn't make sense.

**Comment by railmonkey** [comment] 2016-12-10 08:46
It's seeing the withered plant planters that got me thinking about it in the first place, but it does seem like hydroponics would be the way to go. I hadn't thought of the uses for the stationary playstyle, but it makes sense, of course. As for plants and vehicles having nothing to do with each other, well, why not? If it's good enough for NASA, I don't see why it shouldn't work for a purely terrestrial conveyance. I'll concede that it sounds like hooking in the farming code would probably be... non-trivial. If that's dealt with, however that would be done, then it just comes down to: 

* A vehicle part with container and light producing flags (possibly also temperature altering flag?)
* Generic installed tanks, probably no larger than 2L, and the part flag to utilize them
* A nutrient broth liquid, or simply the existing liquid fertilizer and water, to fill aforementioned tanks
* Sufficient power supply 
* Seeds

I get the feeling that this is one of those 'simple in theory, mind-numbing in practice' issues, so at the very least it needs a long-term label. Where _is_ the farming code, anyway? I'd like to look it over, but I can't find it.

**Comment by kevingranade** [comment] 2016-12-10 09:32
I doubt implementation would be much of a problem. The problem is the
concept is broken from both a realism and game balance point of view.
The issue with realism was already pointed out,  growing plants for food is
incredibly space intensive and adjusting things enough to make it
worthwhile would be kind of ridiculous.
Balance wise is just as bad,  living in a nomadic vehicle is already so
much better than the alternatives that it's the main feature in the game in
need of nerfing. It definitely doesn't need us adding even more self
sufficiency features into it.

In isolation, would it be reasonable to enable a vehicle mounted vegetable
garden (that doesn't produce enough food to matter)? Yes, but frankly I
don't want to open that can of worms because I guarantee that if it's added
we'll get incessant requests to push it ever closer toward that
self-sufficiency level.

**Comment by Leland** [comment] 2017-05-23 20:53
Closing due to lack of discussion. Feel free to ping me to reopen if there's interest, or make a new issue.

**Closed by Leland** 2017-05-23 20:53 UTC
Labels: Suggestion (Discuss)
