### ISSUE TITLE
Segfault on hitting w key

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70164] opened 2023-12-12 05:56 UTC
### Describe the bug

Segfault occasionally on hitting wield key. Is not consistently doing it, but it doesnt take very long, 2-5min it usually happens

### Attach save file

[Rock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13644228/Rock-trimmed.tar.gz)

### Steps to reproduce

Play game, try to wield something, segfault occasionally

### Expected behavior

No segfaults

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 3d3c5ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13644192/crash.log)

**Comment by GoLoT** [comment] 2023-12-12 06:56
Log suggests it is related to #70156

**Comment by BrettDong** [comment] 2023-12-12 13:07
Yes, duplicate of #70156

**Closed by BrettDong** 2023-12-12 13:07 UTC
Labels: (S1 - Need confirmation)
