### ISSUE TITLE
Expanded Digestive System CBM doesn't actually increase calorie gain

### ISSUE THREAD

**Issue by berangus** [CleverRaven/Cataclysm-DDA#31798] opened 2019-06-24 09:30 UTC
Expanded Digestive System CBM does not increase the calories gained from food, it only increases the listed value in the Consume UI. The UI shows a value 50% higher than the food's default calorie value, but when you eat it, you only get the default amount, same as if you didn't have the CBM.
-----------------------------

**Steps to reproduce the behavior:**

1. Make a player, spawn bratwurst, observe that the Calorie value is listed as 297.
2. Use the debug "Game State" option to view your stomach's calorie content.
3. Eat the bratwurst, check your stomach calories again and observe that they have increased by 297.
4. Make a "Bionic Monster" player to start with the Expanded Digestive System CBM.
5. Spawn a bratwurst and note that the Calorie value is now listed as 445. (50% increase)
6. Use the debug Game State logs to observe that eating the bratwurst only increases your stomach calories by 297.

Note that you could use whatever food you want for this, I tested a couple others, bratwurst was just the first one I noticed and what I did the bulk of my testing with.

**# Expected behavior**

The expected behavior is for the calorie gain to be increased when the player has Expanded Digestive System installed, as the values listed in the UI are increased.

# Versions and configuration

**Game report:**

 - OS: Windows 7 Ultimate 64-bit
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4913-g275d8a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**# Additional context**

The numeric values described in this post are what I got in my followup testing, after noticing this issue on my normal save. Worth noting that, on my normal save, the bratwurst I cooked myself has a listed calorie value of 829. I don't know what is causing that higher value, possibly the ingredients I used to cook it, but when I eat that bratwurst I also receive only 297 calories. That character does have the Gourmand trait, which I originally thought might be related, but in my testing it didn't make a difference.

Thanks for everything you do

**Comment by Lorith** [comment] 2019-06-24 16:22
This has been brought up before, though there seems to be other factors as well, such as cooked vs spawned. https://github.com/CleverRaven/Cataclysm-DDA/issues/30705

**Comment by JeanLucVanDamme** [comment] 2019-06-24 20:02
I figured out the likely cause of this bug in #31193 (see Additional Context), it's just waiting for someone with the C++ knowledge to fix it.

Seems to be caused by the new stomach.cpp using get_calories() rather than kcal_for().

**Comment by KorGgenT** [comment] 2019-06-25 19:30
i'm going to close this PR as a duplicate of #30705 since it has more details.

**Closed** 2019-06-26 08:31 UTC
Labels: <Bug>, Bionics, Food / Vitamins
