### ISSUE TITLE
Crash after getting achievement

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#64593] opened 2023-03-26 13:32 UTC
### Describe the bug

Game Crashes when achievement is met, Confirmed with a Innawoods playthrough on 1st Day Completed after sleeping, and on a Non Innawoods Playthrough with AFS, No-Hope, and Xedra Evolved. 

### Attach save file

[Salted Ground-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071692/Salted.Ground-trimmed.tar.gz)
Innawood File

[Deerton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071695/Deerton-trimmed.tar.gz)
Non-Innawood File

### Steps to reproduce

1. Do achievement 
2. Crash

### Expected behavior

Achievements shouldnt cause the game to crash.  The achievements list should appear as normal

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 4ae79c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Bionic Slots [no_cbm_slots]
]

### Additional context

[Crash And Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11071700/Crash.And.Debug.zip)
[Deerton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071701/Deerton-trimmed.tar.gz)

**Comment by dseguin** [comment] 2023-03-26 14:03
duplicate of #64466

**Closed by dseguin** 2023-03-26 14:03 UTC
Labels: (S1 - Need confirmation)
