### ISSUE TITLE
Segmentation Fault When Asking NPC to Farm

### ISSUE THREAD

**Issue by Voideka** [CleverRaven/Cataclysm-DDA#70371] opened 2023-12-23 01:39 UTC
### Describe the bug

I was trying to get my NPC follower to harvest the corn in a pre-genned farm field. I set up a fairly large farming zone, but was holding no seeds so the zone was set to "No Seed". After making this zone, I saved it and told my NPC to do some farming work. After waiting a couple of turns an error pops up about an invalid recipe, and after telling the game to ignore the error, the client segfaults. The error before the segfault is as follows:

 DEBUG    : invalid recipe id ""

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp
 LINE     : 68
 VERSION  : c6f6397

### Attach save file

[Lilymoor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13757575/Lilymoor-trimmed.tar.gz)

### Steps to reproduce

1. Spawn a player on a Farm Field with harvestable corn.
2. Spawn an NPC follower for the player.
3. Use the Zone Manager to designate an area of corn to be harvested, with No Seed selected.
4. Speak to the NPC, and pick "There's something I want you to do.", then "Let's talk about your current activity.", followed by "Please do some farming work."
5. Wait several turns.
6. When the error report pops up, press "i" to ignore it.

### Expected behavior

The NPC should proceed to harvest the corn instead of crashing the game.

### Screenshots

![cdda farming zone](https://github.com/CleverRaven/Cataclysm-DDA/assets/2141044/2435451c-f16b-42f9-bfc1-9d88ebfd34f3)
It's hard to make out, but you should be able to see the farming zone encompassing the bottom 5 rows of the corn field.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: c6f6397 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Voidmod [VoidMod]
]

### Additional context

[debug - Copy.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13757571/debug.-.Copy.log)
[crash - Copy.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13757572/crash.-.Copy.log)

**Comment by fairyarmadillo** [comment] 2023-12-24 22:54
May be related to some map.cpp changes in #69591 

I can take a look at it once the game is able to be compiled again.

**Comment by fairyarmadillo** [comment] 2023-12-25 18:37
Turns out it's not!

This is a duplicate of #68730 and possibly #68921 

May have been caused by #68664 

It may be segfaulting because line 1315 in activity_item_handling.cpp (where zone-based farming takes place) was changed from
`            } else if( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_PLANTABLE, src_loc ) &&`
to
`            } else if( here.has_flag_ter_or_furn( seed->seed->required_terrain_flag, src_loc ) &&`

The zone activities function is a very long chain of else ifs and the next one below farming is crafting, which may be why we're getting an error related to recipes.

**Comment by Novacat** [comment] 2023-12-26 23:06
I can confirm this, except it seems to be related to using any zone-based farming. The NPC is not required to trigger this crash.

**Closed** 2023-12-31 02:24 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed)
