### ISSUE TITLE
"Ran out of available textures in the pool." error

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#58080] opened 2022-06-01 23:26 UTC
### Describe the bug

I randomly encountered this; I don't remember specifically what I was doing, but I had just dismembered a corpse shortly before. I was either doing that, or walking, or resting. After pressing space to continue playing, it happened a couple more times after walking around a bit, and then stopped.

```
 DEBUG    : Ran out of available textures in the pool.

 FUNCTION : request_tex
 FILE     : C:\git\Cataclysm-DDA\src\pixel_minimap.cpp
 LINE     : 142
 VERSION  : 0.F-8717-g0ac1478845-dirty
```

I was running a MSVC tiles release build that I built myself, in a debugger, and this was the backtrace at the time:

```
cataclysm-tiles.exe!input_manager::get_input_event(keyboard_mode preferred_keyboard_mode) Line 3747
cataclysm-tiles.exe!debug_error_prompt(const char * filename, const char * line, const char * funcname, const char * text, bool force) Line 369
cataclysm-tiles.exe!realDebugmsg(const char * filename, const char * line, const char * funcname, const std::string & text) Line 531
[Inline Frame] cataclysm-tiles.exe!realDebugmsg(const char * const) Line 78
[Inline Frame] cataclysm-tiles.exe!pixel_minimap::shared_texture_pool::request_tex(unsigned __int64 &) Line 142
cataclysm-tiles.exe!pixel_minimap::submap_cache::submap_cache(pixel_minimap::shared_texture_pool & pool) Line 184
cataclysm-tiles.exe!pixel_minimap::get_cache_at(const tripoint & abs_sm_pos) Line 354
cataclysm-tiles.exe!pixel_minimap::update_cache_at(const tripoint & sm_pos) Line 307
cataclysm-tiles.exe!pixel_minimap::process_cache(const tripoint & center) Line 366
cataclysm-tiles.exe!pixel_minimap::draw(const SDL_Rect & screen_rect, const tripoint & center) Line 550
cataclysm-tiles.exe!cata_tiles::draw_minimap(const point & dest, const tripoint & center, int width, int height) Line 1740
cataclysm-tiles.exe!cata_cursesport::curses_drawwindow(const catacurses::window & w) Line 1535
[External Code]
[Inline Frame] cataclysm-tiles.exe!std::_Func_class<int,draw_args const &>::operator()(const draw_args &) Line 880
cataclysm-tiles.exe!game::draw_panels(bool force_draw) Line 3438
cataclysm-tiles.exe!game::draw() Line 3398
[Inline Frame] cataclysm-tiles.exe!std::_Func_class<void,ui_adaptor const &>::operator()(const ui_adaptor &) Line 880
cataclysm-tiles.exe!ui_adaptor::redraw_invalidated() Line 348
cataclysm-tiles.exe!do_turn() Line 699
cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 766
```

### Steps to reproduce

I don't know at this time, sorry.  I don't even know what I was doing.

### Expected behavior

I expect the above error to not happen.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1348 (20H2)
- Game Version: 0.F-8717-g0ac1478845-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8819319/debug.zip)

**Comment by snipercup** [comment] 2022-06-02 04:28
I've had this too. I think it's when there's a lot of zombies. Also had it when I was spawning random raiload tracks using EOCs to test something.

**Comment by PatrikLundell** [comment] 2022-06-02 10:25
/confirmed

I've seen it as well (unspecified version, but probably within the last month or so). I didn't see any ill effects from it, nor anything obvious that might have been the cause.

**Comment by NetSysFire** [comment] 2022-06-03 08:12
Potential duplicate of #54088

**Comment by Night-Pryanik** [comment] 2022-10-26 17:21
Duplicate of #54088.

**Closed by Night-Pryanik** 2022-10-26 17:21 UTC
Labels: (S2 - Confirmed), SDL: Tiles / Sound
