### ISSUE TITLE
Zombie clothing not filthy

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73344] opened 2024-04-27 23:08 UTC
### Describe the bug

I killed a fat zombie and it's clothing wasn't filthy. 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15140233/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

I'm not sure why this happened, but in the attached save:
1. There is an unpulped corpse of a fat zombie six tiles north. 
2. You can see that this zombie's clothing is not filthy, with the view menu or by walking up to it and using grab. 

### Expected behavior

I expected that the zombie's clothing would be filthy, like the other zombies. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/abee4c45-e803-4fa7-a174-d15f264389ab)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 4551df2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash. Not sure if this is relevant, but the fat zombie died by being shot to death.

**Comment by GuardianDll** [comment] 2024-04-27 23:15
duplicate of #73295

**Comment by XygenSS** [comment] 2024-04-28 02:59
caused by a feral evolving into a zed

**Comment by DragonWizard23** [comment] 2024-04-28 03:34
@XygenSS I'm not sure that's the case. As far as I can tell on HHG, neither the feral human, nor any of its evolutions can evolve into a standard or fat zombie. I just found a regular zombie without filthy clothes in the same world. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/ab3cc7ed-1b32-41a0-aecc-f9b437430035)
My guess is that the zombie died are its clothes changed when it revived? It wasn't at full health when I started fighting it.

**Comment by XygenSS** [comment] 2024-04-28 03:35
Possible that it is a panicked civilian type monster that evolved into a zed (they do that).

Alternatively a feral or a civilian died and revived as a zed.

**Comment by natsirt721** [comment] 2024-04-28 15:14
I've seen this a bit too, my assumption was that it was a map-generated human corpse that revived into a zombie.

**Comment by GuardianDll** [comment] 2024-05-08 12:51
so yeah, closing as duplicate of #73295

**Closed** 2024-05-08 12:51 UTC
Labels: (S1 - Need confirmation)
