### ISSUE TITLE
Food cart spawned in the middle of the highway and bridge access

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19533] opened 2016-11-28 19:58 UTC
![damnedfoodcarts](https://cloud.githubusercontent.com/assets/8593513/20683714/4d6b8974-b56a-11e6-808d-0a25b9cf9774.png)

**Comment by codemime** [comment] 2016-11-28 20:13
Dupe of #17476.

**Closed** 2016-11-28 20:17 UTC
