### ISSUE TITLE
Straw Bed not needing materials listed

### ISSUE THREAD

**Issue by LokiScion** [CleverRaven/Cataclysm-DDA#23719] opened 2018-05-12 06:22 UTC
Game version:  0.c-27773-ga61f9b2 (build 7391)

Operating system: Windows 10

Tiles or curses: Chesthole(tiles), not on ascii

Mods active:  Dark Days ahead, Simplified nutrition, Stats through skills, disable NPC needs, makeshift items mod, medieval and historic content, more survival tools, Boats, Folding parts pack, Vehicle additions pack

### Expected behavior 
In order to build a straw bed you need 4 two by fours and 8 piles of straw

### Actual behavior 
You only need a single pile of straw and no two by fours in order to build a straw bed. this allows you to deconstruct the straw bed for the materials "Used" to make it.

### Steps to reproduce the behavior
I'm not sure how to reproduce the problem. I've tried on multiple worlds with the same settings but i cant figure it out. Once i build a bed it wont allow to make another till i move around a lot but i can go do it again later.

**Comment by Night-Pryanik** [comment] 2018-05-21 06:10
Can't reproduce on latest experimental, so closing for now. If you find a reliable way to reproduce, ping me.

**Closed by Night-Pryanik** 2018-05-21 06:10 UTC
Labels: (S1 - Need confirmation), Fields / Furniture / Terrain / Traps
