### ISSUE TITLE
Eating from sealed container placed in vehicle storage spills the test liquid

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#18654] opened 2016-10-05 21:50 UTC
Example: get tin can of meat soup, place in trunk, press E to eat it. 3 meat soup is spilled on the floor, empty tin can placed in trunk

**Comment by busterbogheart** [comment] 2016-10-06 13:59
Possibly related to #18239 #17734

**Comment by eliotcougar** [comment] 2016-10-07 15:45
I confirm that... It is not related to the #17734 which seems to be fixed...

**Comment by AdonaiJr** [comment] 2016-10-10 15:09
I confirm that. Happened  a couple days ago, exactly like Voker57 said.

**Comment by Night-Pryanik** [comment] 2017-04-01 14:24
Dupe of #18168.

**Closed** 2017-05-01 17:29 UTC
Labels: Bug, Duplicate
