### ISSUE TITLE
Cannot use antiseptic on  NPC follower

### ISSUE THREAD

**Issue by HreFanBoy** [CleverRaven/Cataclysm-DDA#76489] opened 2024-09-16 21:01 UTC
### Describe the bug

Attempting to use antiseptic on my NPC follower, but it instead causes the menu for using it on myself to open. This does not apply to bandages, but I am unaware if it applies to other disinfectants.

### Attach save file

N/A

### Steps to reproduce

1. Select "use item on" option with NPC
2. Select antiseptic
3. Message log will display something to the like of "Attempted to consume antiseptic" then open the menu to use on the player instead

### Expected behavior

That I would be able to use antiseptic on my NPC

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Amazon; Model: KFONWI; Release: 9; Incremental: 0029294006404; 
- Game Version: cdda-experimental-2024-09-13-1634 f785f58 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment] 2024-09-17 05:08
Duplicate of #76414

**Closed by RenechCDDA** 2024-09-17 05:08 UTC
Labels: (S1 - Need confirmation)
