### ISSUE TITLE
Research facility/lab surface walls are not visible from far

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#31851] opened 2019-06-25 20:26 UTC
# Describe the bug

The walls on the surface portion of research facility/lab stay "unseen" at distances where they should be visible. They become visible once you get very close to them.

# Steps To Reproduce

Enable z-levels (everything looks normal with z-levels disabled).
Approach a lab (spawn one with debug menu if you can't find one).
The walls don't become visible until you are very close.

# Expected behavior

The walls should become visible at the edge of visibility radius.

# Screenshots

![alt text](https://i.imgur.com/iCKcZpf.png "a")

Seemingly random spots of the wall become visible earlier.
![alt text](https://i.imgur.com/N3oggRw.png "a")

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4964-ga26ac8d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    Mundane Zombies [Mundane_Zombies]
]

# Additional context

**Comment by esotericist** [comment] 2019-06-25 21:11
I experienced something very similar to this with a gas station/garage, where there visibility seems to get squirrelly around some windows.
![Garage lighting](https://cdn.discordapp.com/attachments/511623330227421184/592543728141598721/unknown.png)

I wasn't able to see the garage walls until I got within night vision range, and once inside, I was in a "very dark" area despite sunlight being on the other side of the window

**Comment by l29ah** [comment] 2019-07-13 16:24
Same for `hub 01`.

**Comment by Leland** [comment] 2019-08-21 14:49
Duplicate of #31994

**Closed by Leland** 2019-08-21 14:49 UTC
Labels: <Bug>, Other
