### ISSUE TITLE
Pool water got turned into dirt?

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73517] opened 2024-05-05 02:00 UTC
### Describe the bug

The pool at the private resort which I use for an infinite water source, got turned into dirt somehow during one of the experimental updates. I'm not sure which one, I didn't notice till now.

### Attach save file

NA

### Steps to reproduce

Use a prior build and go to a private resort pool (or possibly other pools) and make sure pool water exists.
Update to a later experimental and check again and see if pool water got turned into dirt.

### Expected behavior

Pool water should not turn into dirt.  Though over time (pre-existing chlorine presence should affect this) it may turn into the stagnant/murky water that I know was being worked on in some other PR (depending on the size of the pool), but not dirt unless it got filled in with soil, which I don't even think is possible at the moment via the construction menu.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/2752dff9-7ca2-46c5-8d18-aa798500a3b7)

### Versions and configuration

Windows 11
build 0a74bb4

**Comment by O1OOO1O** [comment] 2024-05-05 02:06
It is not exclusive to the private resort, regular pool over map structure also got turned into dirt. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/5c9504b5-0b42-497b-a5e7-b20cde84f35d)
So did fishing pond?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/fb6cd9ce-76ff-4761-83e9-717058462cb8)
And lake shore...
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/a0c60c79-090c-4804-9ab7-2df0261cdcf1)
wonder if I can walk to that aircraftcarrier now...

**Comment by fairyarmadillo** [comment] 2024-05-05 02:33
This is related to #73478 but it's possible this has been fixed already.

**Comment by O1OOO1O** [comment] 2024-05-05 02:47
Updating to 19d38b0 did not fix the issue.

**Comment by RenechCDDA** [comment] 2024-05-05 02:50
Duplicate of #73489

**Closed by RenechCDDA** 2024-05-05 02:50 UTC
Labels: (S1 - Need confirmation)
