### ISSUE TITLE
Can't insatll

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#39435] opened 2020-04-10 06:33 UTC
# Describe the bug

I'm trying to install an M2 onto my vehicle but it shows that I don't have an M2 to install despite one being in my inventory.

# Steps To Reproduce

1. Examine vehicle
2. Attempt to install into turret mount spot

# Expected behavior

Option to install the M2 should be available.

# Screenshots

![M2_1](https://user-images.githubusercontent.com/5049386/78968534-bb694c00-7ab9-11ea-8349-0b84c1d70bca.PNG)

![M2_2](https://user-images.githubusercontent.com/5049386/78968541-be643c80-7ab9-11ea-83cf-0622de2c370f.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-468-g9e02bc1 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mutant NPCs [mutant_npcs],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

[Mineral Wells.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4460185/Mineral.Wells.zip)

**Comment by Night-Pryanik** [comment] 2020-04-10 08:38
Duplicate of #39436.

**Closed by Night-Pryanik** 2020-04-10 08:38 UTC
