### ISSUE TITLE
NPC infinite loop reloading Mosin.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#42365] opened 2020-07-22 01:34 UTC
# Description

I'm not entirely sure what's going on, so I apologize if whatever this bug is has already been reported. That said...
When I load up my save in the Refugee Center, one of the NPCs attempts to reload their Mosin-Nagant with a 7.62x54mmR clip. An error message pops stating that it failed, the weapon can't be reloaded with that. Then it tries to reload it again. Keeps doing that until the game detects the infinite loop and turns on debug mode. Here's the save and debug.log:
[Reload Bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4957308/Reload.Bug.zip)

# Steps To Reproduce

Load the save, dismiss all the errors about #41821 and about something not fitting in a holster, then take one step.

# Expected behavior

The gun reloads or the character doesn't try to reload a gun that's not supposed to reload that way. And no errors, that too.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
   - Dark Days Ahead [dda],
   - Disable NPC Needs [no_npc_food]

**Comment by Hulkninja** [comment] 2020-07-22 06:32
The bug is caused by Mosin Nagants, along with many other guns, currently being broken. This issue has been reported several times over the past week or so. Nobody's come up with any solution yet, at least that I know of, so don't expect this to be resolved any time soon.

**Comment by Cynthius** [comment] 2020-07-22 16:20
No worries. Just glad to know it's on the radar, even if there's no solution yet.

**Comment by esavier** [comment] 2020-07-22 21:49
and again, since i am tracking series with mosin nagants
maybe related #42161

**Comment by kevingranade** [comment] 2020-12-17 05:31
Might be fixed by #45705

**Comment by int-ua** [comment] 2021-01-14 05:16
Removing the `Bug` label until a fresh confirmation.

**Comment by hexagonrecursion** [comment] 2021-01-14 09:15
I can confirm that the error is **not reproducible** in 618a3be
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-8740-g618a3be [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```
I can confirm that the error was reproducible in a3e5f32
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Closed** 2021-01-14 13:43 UTC
Labels: <Bug>, Items: Magazines, NPC / Factions
