### ISSUE TITLE
Crafted (cooked) drinks become instafrozen

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41090] opened 2020-06-05 14:00 UTC
# Describe the bug

Drinks made with a fire becomes instafrozen, impossible to assume when they are created, you can only pour them in a container, because they spawn frozen, yeah after boiling some water, wow

not a big deal since you can warm them up with a pot or pan but... kinda annoying

# Steps To Reproduce

Press &
 make some tea, pine needle tea, or other drinks (I assume it works with every drinkable object)
you can't drink them right away because they are frozen
pour them in a container
they appear to be frozen and you have to heat them up

# Expected behavior

In this universe, laws of thermodynamic forbid a liquid to be frozen if is boiled, like some hot tea

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2899-g0ff7d77 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

EDIT: similar to this
https://github.com/CleverRaven/Cataclysm-DDA/issues/40732

but in that report I can see the "consume it" option, and I don't

**Comment by anothersimulacrum** [comment] 2020-06-05 14:28
> EDIT: similar to this
> #40732
> but in that report I can see the "consume it" option, and I don't

You have the same issue, but you're on a later version. I'm going to mark this one as duplicate of that, because that one has information on the causes (though you actually filled out the template, thanks!).

**Closed by anothersimulacrum** 2020-06-05 14:28 UTC
Labels: (S3 - Duplicate), <Bug>, Crafting / Construction / Recipes, Items: Food / Vitamins, Mechanics: Temperature
