### ISSUE TITLE
Show the effect of Weary on move costs and include its current status in the sidebar

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#46027] opened 2020-12-13 12:16 UTC
# Is your feature request related to a problem? Please describe.
Being weary can completely change your ability to take on fights a normally non-weary character can do. Until someone else told me about the mechanic in detail, I had no idea why I was suddenly getting attacked 3-4 times for every attack I was making. The importance of this mechanic is extremely under presented. It's as important as stamina now but has no notifications aside from messages that get drowned in the message log by combat, zoning, and music. 

# Describe the solution you'd like
I'd like for the current "level" of Weary to appear on the sidebar, and for its actual effect on my move costs included in the character menu. It's fairly deceptive to me when I take look at my move cost and see "oh just a little chilly and minor pain, looks good to me!", when in reality, my move costs are MUCH worse.

# Describe alternatives you've considered
I have not considered any alternatives.

# Additional context
I made some quick mockups to show the information I'd like to see.
![image](https://user-images.githubusercontent.com/22645231/102011411-dad40b00-3d11-11eb-98f0-64fddd242bdb.png)
![image](https://user-images.githubusercontent.com/22645231/102011463-4b7b2780-3d12-11eb-9fa7-f317fa6112b3.png)

**Comment by anothersimulacrum** [comment] 2020-12-13 17:40
The effect on move costs depends on the activity, so we cannot show it in the speed UI without it being actively misleading.
Once we have #44428, we'll be displaying information about the activity levels of various activities, then we can show it's exact effect in the effect description.
As such, this is effectively duplicate of #44428

**Closed by anothersimulacrum** 2020-12-13 17:40 UTC
Labels: (S3 - Duplicate)
