### ISSUE TITLE
Cannot reload needles

### ISSUE THREAD

**Issue by warheroz** [CleverRaven/Cataclysm-DDA#40540] opened 2020-05-13 21:30 UTC
Abstract:
When trying to reload wooden, bone needles and sewing kit with string string dissepears, but 0 points of string in needle appears. Massage about successful reload apperas as it was in older patches,
Steps To Reproduce
1) Achieve needle or sewing kit, string
2) Go to inventory, press needle, then "reload" button
3) String dissepears with no effect
Expected behavior:
1) Add more points to needle value

Versions and configuration
- OS: Windows 7 
- Game Version: 0.E-2133-g9bb14f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

**Comment by ZhilkinSerg** [comment] 2020-05-13 21:33
Duplicate of #40125

**Closed by ZhilkinSerg** 2020-05-13 21:33 UTC
