### ISSUE TITLE
Beehives are completely unbalanced!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#65636] opened 2023-05-14 14:40 UTC
### Is your feature request related to a problem? Please describe.

Beehives are currently found everywhere in the Forest. They are very close togheter and do not even need to be harvested. Just by smashing them you get around 10 honey combs for 1 Beehive and in the summer, only 1 is harvestable for around 170 honey combs! Honey combs have a very high calorie value and do not spoil. 
Beehives as they are now, make ANY OTHER Food source obsolete!

### Solution you would like.

The simplest solution would be reducing the amount of Beehives that spawn in the forest very significantly, making them rare.
Beehive are not this common in reality either, which should make this solution reasonable. 
From Venera3;
For reference, wild honeybee hives are about one per square kilometre in temperate NA - see https://resjournals.onlinelibrary.wiley.com/doi/10.1111/een.12715, supplementary table one. That comes out to about four per overmap.

**Comment by fairyarmadillo** [comment] 2023-05-14 15:09
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/9af0a7a6-eeaf-488b-98f1-0e0262cf52d5)

Confirmed. h is for hive, these things are everywhere!

**Comment by Venera3** [comment] 2023-05-14 15:11
For reference, wild honeybee hives are about one per square kilometre in temperate NA - see <https://resjournals.onlinelibrary.wiley.com/doi/10.1111/een.12715>, supplementary table one. That comes out to about four per overmap, even assuming your survivor can find them in the first place.

**Comment by fairyarmadillo** [comment] 2023-05-14 15:27
I'm not totally sure how regional_map_settings works, but maybe it'd be a good idea to have hives spawn as rare map specials instead of just rolling them into the greenery table.

**Comment by Venera3** [comment] 2023-05-14 15:55
Single colony as a map extra could work with a teeeeny spawn chance on forest (slightly less tiny on dense forest).

**Comment by Tharn** [comment] 2023-05-14 16:57
Four per overmap would still come out to a fair amount of hives. maybe 25% of what that screenshot shows? Maybe the unique difficulty of harvesting honey from a hive of angry, possibly slightly mutated bees could be highlighted by actually taking damage and/or morale penalties for doing it without appropriate gear, or reducing the amount of honey gained in the Summer if there's this huge discrepancy. Would be sad to banish bee hives to obscurity.

**Comment by Krieger1999** [comment] 2023-05-15 06:28
Yes apart from reducing the amount of Beehives, they should also only be harvestable with certain gear and if you smash them, you should take damage from the bees or maybe having a speed debuff for beeing distracted by angry bees?

**Comment by Aerin-of-the-Toast** [comment] 2023-05-15 18:58
Can't bee stings be outright lethal with enough of them? Say, in the quantity you'd get if you just took a hammer to a wild hive?

**Comment by Zireael07** [comment] 2023-05-16 07:57
@Aerin-of-the-Toast https://www.ars.usda.gov/pacific-west-area/tucson-az/carl-hayden-bee-research-center/docs/bee-safety/bee-stings-101/#:~:text=The%20average%20person%20can%20safely,withstand%20more%20than%201100%20stings.

"The average person can safely tolerate 10 stings per pound of body weight. This means that although 500 stings can kill a child, the average adult could withstand more than 1100 stings."

I'm assuming they mean a person who is NOT allergic, because in allergic people, even a single sting has been known to kill if the reaction was severe enough or the location was unlucky enough (e.g. the neck/throat)

**Comment by Tharn** [comment] 2023-05-16 09:33
Approaching a bee hive and getting swarmed and stung is difficult not just because of the stings but also psychologically. Since there's currently no way to model "apprehension" in the game before the fact, it would have to be represented by serious morale penalties afterwards. Is there such a thing as "flee when morale is below X?" Could there be?

**Comment by sas1018** [comment] 2023-05-17 01:30
I'd be willing to tackle this one if no one has started work yet, been looking for a simple-ish first issue to dive into

**Comment by Krieger1999** [comment] 2023-05-17 07:34
> I'd be willing to tackle this one if no one has started work yet, been looking for a simple-ish first issue to dive into

Yes you can! Thanks for the help!

**Comment by Krieger1999** [comment] 2023-05-18 07:15
> > I'd be willing to tackle this one if no one has started work yet, been looking for a simple-ish first issue to dive into
> 
> I have got it pretty much done already.

It seems like that your pull request has failed some checks. 😞

**Comment by fairyarmadillo** [comment] 2023-05-18 10:49
A couple of recent merges, namely the grab changes and the monster corpse, have been causing PRs to fail checks all over the place. It's not a concern, they're still getting merged.

**Closed** 2023-05-18 15:07 UTC
Labels: <Bug>, Good First Issue, <Suggestion / Discussion>, Map / Mapgen, Fields / Furniture / Terrain / Traps
