### ISSUE TITLE
"Tried to set invalid ammo none for sauerkraut"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16322] opened 2016-04-21 20:51 UTC
* Pick up sealed sauerkraut
* Wield it
* Activate it
* Debugmsg

The jar actually turned into jar of 'kraut, but the result had only 1 charge. Pickled veggies and meat, opened just after that, didn't bug out.

Could be save related. If it is, it's probably minor enough not to keep it open.

**Comment by mugling** [comment] 2016-04-21 21:58
Can reproduce

**Comment by mugling** [comment] 2016-04-21 22:05
`iuse_actor.cpp:129`

**Comment by BevapDin** [comment] 2016-05-08 22:34
The iuse actor sets the charges of the resulting item to 4, as instructed via the JSON data. But that is supposed to mean 4 portions of sauerkraut and should not call `ammo_set`.

One could for example check whether the target item already has an ammo type or whether the iuse action has an explicit (non-empty) target type. If neither applies (as for the sealed jar of sauerkraut), it should just set `charges` directly without calling `ammo_set`.

**Comment by Coolthulhu** [comment] 2016-05-31 20:48
I think I have found the reason:
Setting ammo requires the item to be charged. Sauerkraut is 1 charge item with no stacksize, meaning it is not charged.

A flag or some other way to force "chargedness" would be useful.

**Comment by BevapDin** [comment] 2016-06-01 03:57
Well, sauerkraut shouldn't be charged at all. It's not a gun or a tool, it's just food.

**Comment by Xpyder** [comment] 2016-06-01 15:47
posting more detailed debugging here, closing #16979 as a duplicate.

Using [ ] cataclysmdda-0.C-4964.zip 2016-05-31 05:14 50M

image

happens when opening these items:
sealed jar of V8
sealed jar of canned fruit
sealed jar of broth
sealed jar of bone broth
sealed jar of human broth
sealed jar of sauerkraut
sealed jar of fish soup
sealed jar of sap soup
sealed jar of meat soup
sealed jar of mushroom soup
sealed jar of vegetable soup
sealed jar of woods soup
sealed jar of canned tomato

does NOT happen with these items:
sealed jar of canned fish
sealed jar of pickled fish
sealed jar of soylent slices
sealed jar of pickled human flesh
sealed jar of canned meat
sealed jar of pickled meat
sealed jar of canned veggy
sealed jar of pickled veggy

**Comment by Xpyder** [comment] 2016-06-01 15:53
@Coolthulhu 

>I think I have found the reason:
>Setting ammo requires the item to be charged. Sauerkraut is 1 charge item with no stacksize, >meaning it is not charged.

The items that don't have the issue lack stack_size or charges > 1 also, but I haven't checked their transforms, so this could still be possible

>A flag or some other way to force "chargedness" would be useful

Agreed, even if it's just a fallback

**Comment by Xpyder** [comment] 2016-06-01 15:57
@BevapDin 

>Well, sauerkraut shouldn't be charged at all. It's not a gun or a tool, it's just food.

It's a debugging thing.  Generally anything that goes into containers is "charged", that is: can have charges.  I think it's because currently containers can only hold 1 item (which you think of as the item type), charges let you store multiple "conceptual items" but it's really just 1 item with multiple charges.  I know it's kind of weird.

**Comment by Xpyder** [comment] 2016-06-01 16:03
@BevapDin 
I see you already know this, rescinding.

**Comment by Xpyder** [comment] 2016-06-01 16:12
I'll add that I tried manually adding stack_size:2 to canned fruit in comestibles.json and I still got this error

**Closed** 2016-06-04 01:05 UTC
Labels: Bug, validated
