### ISSUE TITLE
Crash when starting world

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#53614] opened 2021-12-20 10:41 UTC
### Describe the bug

I made a new character for that world and when I tried to load into the world, the game crashed.
I had already played with a character in the same world, it crashed when I created the same character for the second time (after the first one died).

### Steps to reproduce

Create new character, enter world, crash message.

### Expected behavior

Crash shouldn't happen

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/146753954-9810d58b-2140-47ef-8850-8ab55f3f24d9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 579f907 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7744647/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7744650/save.zip)

**Comment by Inglonias** [comment] 2021-12-20 14:35
Duplicate of #52300.

Yeah, someone's going to have to tackle this one sooner rather than later. I managed to somehow stop this crash from happening on my own computer after a reinstall, but I could not for the life of me tell you how that happened. I don't know how I did it.

**Comment by wapcaplet** [comment] 2022-01-16 15:55
Closing as duplicate of #52300

**Closed by wapcaplet** 2022-01-16 15:55 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
