### ISSUE TITLE
Some mapgen monster spawns scale disproportionately to spawn rate.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#14045] opened 2015-11-15 16:36 UTC
https://www.reddit.com/r/cataclysmdda/comments/3sqn3v/has_anyone_else_been_seeing_unusually_large/

I've noticed before that occasionally, some houses will be literally stuffed with zombies on higher spawn rates. Rarely, a house on regular spawn rates will be full. The probability of spawning monsters in these places is weird, since there are multiple RNG calculations occurring. 

There is a "one out of X" chance of processing spawning, where X is the original chance divided by the spawn rate multiplier. Higher multipliers only guarantee that this portion passes.

The monster density defaults to overmap zombie density, if it's not specified in the JSON. This value varied from .02 to .36 when I checked outside of a town compared to near the center of a town. The density is multiplied by the spawn rate multiplier, then by another RNG value between 10 to 50. The resulting value (spawn count) is the amount of zombies to spawn in an area. Where some mapgens use terrain replacement to place zombies (some glyphs are marked as potential spawn points), any spawn count 1 or more will guarantee a zombie spawn in each glyph that is allowed to spawn a zombie. With default rates and .02 density (standing next to evac shelter and gas station away from town), the spawn count is only equal to 1 when the RNG(10,50) is 50 (1/41 chance). Roughly, one out of 41 tiles that are available for spawning will have a zombie. 

When a larger spawn rate is applied, the density will be multiplied, leading to a better chance of the spawn count being at least 1. In the case of .02 density, a 5x spawn rate setting will have a spawn count of at least 1 (.02 \* 5.0 \* RNG(10,50)). Every glyph marked for spawning a zombie will contain a zombie. In the case of the coffee shop noted in the link, every available space will be filled with a zombie. With a 5x spawn rate, the debug mapgen shows it was trying to spawn 300+ zombies in a coffee shop in the center of town (if the zombie can't find an empty space, it doesn't spawn). 

A partial solution is to apply a low density in the mapgen JSON (where zombies are being used in a general area) to override the default density given by town proximity, but it would be nice if there was a better way to have zombie spawns scale linearly.

**Comment by remyroy** [comment] 2015-11-19 01:17
I think it happened to me in a mil. surplus. Every square of the building was filled with a zombie. I though it was a horde but than I used the 'Show horde' from the debug menu and it was not.

**Comment by Leland** [comment] 2017-05-23 20:02
Closing due to age and lack of reproduction. If anyone can corroborate this and/or provide a savefile (would be super helpful!) please ping me to reopen, or just create a new issue.

**Closed by Leland** 2017-05-23 20:02 UTC
Labels: Balance, Bug, Spawn
