### ISSUE TITLE
Lava does not count as a nearby fire when heating food

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#20044] opened 2017-01-18 06:25 UTC
lava is considered a nearby fire when crafting, but not when heating up food by 'a'ctivating a pot

**Comment by CoroNaut** [comment] 2017-01-18 07:20
Would you really want to walk over to that pit of lava, get 3rd degree burns, and still expect to get a nice warm soup?

**Comment by sick-trigger** [comment] 2017-01-18 07:39
you can cook the soup with the lava just fine. Whether you should be able to is (maybe) worth a discussion, but the point is there's a discrepancy

**Comment by BrettDong** [comment] 2017-01-18 11:05
Yes there's a bit of inconsistency, the game should forbid the use of lava in either food crafting or food heating, or allow both of them.

**Comment by Coolthulhu** [comment] 2017-01-18 11:16
As far as I recall, heating food requires adjacent fire/lava, not just one in craft range.

**Comment by sick-trigger** [comment] 2017-01-19 04:20
yeah that's what's happening, if you stand next to the lava (unviable in normal play, obvs) you can heat up your soup.

this can probably be closed, but being able to cook with a 'nearby fire' but only reheat when next to one is still kind of inconsistent

**Comment by DaliTimelord** [comment] 2017-01-20 03:49
This seems to be a particular issue with reheating, rather than nearby fires.
Change the requirements of reheating to be like that of cooking?
Also, [ here is a video of people cooking with lava. ](https://vimeo.com/104105171)

**Comment by WizardOfOoo** [comment] 2017-01-22 14:53
That's molten metal, not lava.  Notice all the protective gear?  The molten metal radiates heat like a furnace.   Standing close enough to cook will burn you without bunker gear.

Lava is much more dangerous because of its impurities.  It emits large amounts of Co2, several toxic gasses, and is sometimes radioactive and emits radioactive gas which is a real killer.  Any food cooked over it would be risky to eat.

**Comment by kevingranade** [comment] 2017-01-23 03:31
On Jan 22, 2017 6:53 AM, "WizardOfOoo" <notifications@github.com> wrote:

Lava is much more dangerous because of its impurities. It emits large
amounts of Co2, several toxic gasses, and is sometimes radioactive and
emits radioactive gas which is a real killer. Any food cooked over it would
be risky to eat.

Expanding on this, if the underlying issue is, "interacting with lava is
inconsistent", the best solution IMO is to just make lava as dangerous as
it is in reality, then the issue is fairly moot.

**Comment by Leland** [comment] 2017-05-24 16:26
Closing this per the above discussion.

If anyone wants to open a new issue regarding consistency of reheating/cooking, feel free.

**Closed by Leland** 2017-05-24 16:26 UTC
Labels: Crafting, Suggestion (Discuss)
