### ISSUE TITLE
Error thrown when entering Science Lab above Office Tower

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49785] opened 2021-07-09 20:31 UTC
# Describe the bug

When entering the southwestern room of a Science Lab above Office Tower, an error is thrown

# Steps To Reproduce

1. Load attached save
2. Go up stairs into Science Lab
3. Move south into the room with counters and centrifuges

# Expected behavior

Monsters to spawn cleanly

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 98b6dfb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

 DEBUG    : there's already a monster at 26,124,0

 FUNCTION : bool Creature_tracker::add(shared_ptr_fast<monster>&)
 FILE     : src/creature_tracker.cpp
 LINE     : 77
 VERSION  : 98b6dfb

[My savefile](https://www.dropbox.com/s/szj1f32uq791epq/Olex%20-%20Copy.7z?dl=0)

**Comment by wapcaplet** [comment] 2022-01-16 05:42
Closing as a duplicate of #49736

**Closed by wapcaplet** 2022-01-16 05:42 UTC
Labels: <Bug>, (S3 - Duplicate), Spawn, Monsters
