### ISSUE TITLE
Items that are too big to pick up cannot be selected, not even to be examined.

### ISSUE THREAD

**Issue by GuGuyCDDA** [CleverRaven/Cataclysm-DDA#53025] opened 2021-11-25 16:11 UTC
### Describe the bug

In the pickup window for items, items that are too big to pick up cannot be examined,
They also cannot be selected in any way, and cannot be picked up unless the player is not holding anything in its hands.
![image](https://user-images.githubusercontent.com/73619218/143472785-8c1e2c8f-9c50-4cd8-81c2-ac3bf2a2b980.png)

### Steps to reproduce

Make a world
grab an object
try to interact by picking up another object
you will not be able to select it to examine it
you will not be able to pick it up by automatically dropping your current item and wielding the other item instead

### Expected behavior

Like in other versions, i expected to pick up items that cannot fit in my storage by wielding them and dropping the current item that is wielded.
Im wielding a knife, i want to pick up a cardboard box, i sheathe the knife and wield the box.

I should be able to examine items and read their stats even if they are too big to pick up.

### Screenshots

![image](https://user-images.githubusercontent.com/73619218/143473251-4e95cb72-162b-4904-8a61-1a0f01780fb3.png)
![image](https://user-images.githubusercontent.com/73619218/143473781-edc5166e-1cf9-4674-9ab7-e7dabc117f89.png)
ACTIVE WORLD MODS:
![image](https://user-images.githubusercontent.com/73619218/143474049-00127267-6262-4c75-9022-a1327a9f8580.png)

### Versions and configuration

OS: Win 10
Game version: 16a3fb9 (tiles) 
Build: 2021-11-24-0809 (a day ago)
Graphics: Xotto+ tileset and Otopack sound
Language: English
Mods loaded: In screenshot list.

**Comment by wapcaplet** [comment] 2021-11-25 16:55
Confirmed. See also related issue #52675. Unlike that issue, enabling the "Dangerous pickups" General option has no effect, since here "Too big to pick up!" more accurately means "You cannot pick this up while wielding something else."

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3988-g943e476770 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GoodDays13** [comment] 2021-11-25 17:27
Doesn't seem like a bug to me, but it's still annoying how I can't even see how big a thing is when it's "too big"

**Comment by estebandellasilva** [comment] 2021-11-25 17:45
Or if you actually want it ( i know there are differnet ways to get this info but its not great that you have to go to another menu)

**Comment by GoLoT** [comment] 2021-11-26 13:59
This is an even bigger issue with items that stack. Lets say you have a pile of 60 rocks but you can only carry 10. It won't let you take only a few from the pile unless you drop your weapon first, making you needlessly go through multiple keypresses/menus to grab a few rocks.

**Comment by GuGuyCDDA** [comment] 2021-11-28 08:58
god this bug is so terrible, i need to wield a pizza slice to god damn carry it around by going through so many unnecessary steps..

**Comment by gkarfakis19** [comment] 2021-12-03 16:32
This bug is making the game unplayable for me.

**Comment by wapcaplet** [comment] 2021-12-03 23:10
> god this bug is so terrible, i need to wield a pizza slice to god damn carry it around by going through so many unnecessary steps..

> This bug is making the game unplayable for me.

Can someone explain what about this makes the game unplayable? I understand that it makes items impossible to `e`xamine from this screen items that can't be picked up, and I understand that it may sometimes force you to manually un-wield something you are wielding that prevents picking up too-large items, taking a few extra keystrokes. But I don't see what about this is as game-breaking as you have suggested.

**Comment by GoLoT** [comment] 2021-12-03 23:48
There is only one scenario where I think this might be gamebreaking:

If there is a container with items that make it heavy enough that you can't carry/wield it, the container will still be unselectable in the pick up window and you can't press the key to show the items inside, so the contents stay hidden and you can't get them either. I'm not sure it the contents show up in AIM, but if they don't I don't think there is any way to get those items. That's the only scenario I can think of where this is not only an inconvenience, I don't even know if I'm right about AIM not showing the contents and even then, I don't know if there are any containers big enough to hold enough heavy items to cause this problem.

For any other scenarios this is inconvenient but there are easy workarounds like moving items from the stack in AIM. So the game is still perfectly playable.

**Comment by gkarfakis19** [comment] 2021-12-03 23:49
Let's say I drop the M4 I was wearing on the ground to fight a zombie. I kill the zombie, and now I have to go back and drop my knife, grab the m4, wear it manually, and pick the knife up again, where before I could do this by simply grabbing the m4 and choosing to wear it. It's a very annoying change and while not gamebreaking, I hate it.

**Comment by GoLoT** [comment] 2021-12-03 23:51
So not unplayable after all. It's annoying me too, honestly, but that's the risk of playing experimental. QoL changes  (even if this is really a bug introduced by recent changes) can take time sometimes.

**Comment by mqrause** [comment] 2021-12-04 16:11
> Let's say I drop the M4 I was wearing on the ground to fight a zombie. I kill the zombie, and now I have to go back and drop my knife, grab the m4, wear it manually, and pick the knife up again, where before I could do this by simply grabbing the m4 and choosing to wear it. It's a very annoying change and while not gamebreaking, I hate it, as it takes 4 times longer (and going into 3 menus) to do this simple repetitive action. Enabling dangerous drops does not help with this.

Instead of doing all that, you can just wear the m4 from the ground? Using pickup for that is an incredibly specific use case.
Although I'm considering allowing to wield and wear items directly from the pickup menu.

**Comment by gkarfakis19** [comment] 2021-12-04 17:13
> > Let's say I drop the M4 I was wearing on the ground to fight a zombie. I kill the zombie, and now I have to go back and drop my knife, grab the m4, wear it manually, and pick the knife up again, where before I could do this by simply grabbing the m4 and choosing to wear it. It's a very annoying change and while not gamebreaking, I hate it, as it takes 4 times longer (and going into 3 menus) to do this simple repetitive action. Enabling dangerous drops does not help with this.
> 
> Instead of doing all that, you can just wear the m4 from the ground? Using pickup for that is an incredibly specific use case. Although I'm considering allowing to wield and wear items directly from the pickup menu.

Incredibly specific use case perhaps, but this is how I've always played the game and I see no good reason for this to change.

**Comment by mqrause** [comment] 2021-12-04 18:10
It's a use case that can conflict with other use cases where the popup would be annoying because you don't want to wear or wield anything, just pick up items which fit in your inventory. I don't have any data to say which use case is more common. But your use case has an alternative with no additional key presses, menus or popups.

**Comment by gkarfakis19** [comment] 2021-12-04 18:13
No, you don't understand. The popup only appears if the item would not fit in your inventory otherwise, and has to be wielded or worn. CDDA has worked this way for ages and I really don't see why this has to change.

**Comment by mqrause** [comment] 2021-12-04 18:29
The short answer is because I want it to. I want the pickup process to be more streamlined. In my gameplay, I regularly have to escape out of those popups because I don't care about them. This change reduces the number of unnecessary popups in some cases. If use cases like yours become impossible because of this, I don't see an issue, because you can achieve the exact same thing by pressing a different key.

**Comment by gkarfakis19** [comment] 2021-12-04 18:33
Ok, what if you don't know in advance if a specific stack of wearable/wieldable items will fit my inventory? For example, I see 3 shirts on the ground. My backpack can only fit 2. There are two ways of handling this : until these changes, the game picked up the first 2 shirts conventionally, and then gave you a popup, telling you that you could wear, wield or cancel grabbing that last shirt. Would you prefer that the game cancels the grab action instead, and forces you to navigate to a different menu so that you can wear this shirt to transport it somewhere else?
This sounds like a very specific scenario yet it's something I encounter many times every playthrough.

**Comment by mqrause** [comment] 2021-12-04 18:37
That didn't change with the pickup menu changes and doesn't really relate to the issue here.

**Comment by gkarfakis19** [comment] 2021-12-04 18:39
So which unnecessary popups does this change eliminate?

**Comment by mqrause** [comment] 2021-12-28 22:33
> So which unnecessary popups does this change eliminate?

As a late reply to this question, #53793 will completely remove the query.

**Closed** 2022-01-15 03:57 UTC
Labels: <Bug>, Info / User Interface, (S2 - Confirmed), Inventory / AIM / Zones
