### ISSUE TITLE
Circular Saw Activation Destroys Battery Mods

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#42854] opened 2020-08-11 00:48 UTC
# Describe the bug

When you turn on a circular saw that has a battery mod, it loses that battery mod and ejects the battery.

# Steps To Reproduce
Give a circular saw a heavy or light battery mod.

Load in a battery with at least 5 charge

Turn on circular saw

# Expected behavior

Saw should maintain battery mod and function. 
# Screenshots

# Versions and configuration

# Additional context

**Comment by wapcaplet** [comment] 2020-08-11 21:53
Confirmed. Here I have modded a circular saw with a heavy battery mod, and loaded in a new battery: 

![image](https://user-images.githubusercontent.com/238395/89952605-c90b1b80-dbea-11ea-845b-3d1a4bd0e6ef.png)

Turning the saw on makes the battery and the `+1` attribute disappear:

![image](https://user-images.githubusercontent.com/238395/89952501-99f4aa00-dbea-11ea-849f-a8162e034717.png)


- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4984-ga364725156 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment] 2020-08-11 23:04
Running a `git bisect` reveals that this bug was introduced by commit e6db6e29875, the squashed changes from #42442

**Comment by ZhilkinSerg** [comment] 2020-08-12 08:35
> 
> 
> Running a `git bisect` reveals that this bug was introduced by commit [e6db6e2](https://github.com/CleverRaven/Cataclysm-DDA/commit/e6db6e2987540ada966ef7a2efedd8140ee70aaf), the squashed changes from #42442

```
4a92d5862df3948fc933f095d9b26500eb81e1e4 is the first bad commit
commit 4a92d5862df3948fc933f095d9b26500eb81e1e4
Author: Qrox <qrox@sina.com>
Date:   Fri Jul 24 23:56:29 2020 +0800

    Update pocket data during item conversion

 src/item.cpp       | 3 +++
 src/iuse_actor.cpp | 4 +++-
 2 files changed, 6 insertions(+), 1 deletion(-)
```

**Comment by wapcaplet** [comment] 2020-08-15 14:43
This looks very similar and may be a duplicate of #42764

**Closed** 2020-08-17 15:34 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Items: Gunmod / Toolmod
