### ISSUE TITLE
Performing faction camp actions from a vehicle makes it and the contents vanish.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#47950] opened 2021-03-09 00:39 UTC
Release 0.E-3

I have now run into this issue twice on the same save.

The first time it occurred, I drove into camp, pulled up to the billboard and recalled an NPC that had completed the well. As soon as I completed the action, my vehicle vanished and the NPCs in the now missing vehicle began to cause numerous errors relating to a vehicle that should be there but wasn't.

Fearing this may break my save files if I continued, I killed the program and reloaded the save with no issues.

After playing back to the point where I could restart the camp, I drove to the location, stopped and shut off the engine, and spoke to one of my NPCs about faction camps while still in the vehicle. Upon confirming to start a faction camp at that location, the vehicle promptly vanished again, resulting in the same series of errors relating to the now missing vehicle.

I have once again killed the program to preserve the integrity of my save files.

**Comment by actual-nh** [comment] 2021-03-09 01:03
Could you provide said save files (and debug.log)?

**Comment by x7GoSu** [comment] 2021-03-09 04:17
There seems to be some weirdness going on I send NPC build a brazier, wait 5 mins recover NPC, take control of vehicle try to let go of vehicle control only to have a message in log stating there are no controls to be found.
[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6105810/Test.zip)

**Comment by zantanzuken** [comment] 2021-03-10 10:38
tested on latest experimental to see if it still exists or had been fixed by something else: using a normal bike, standing on the bike tile and interacting with the community billboard, nothing happened. tried again with a larger vehicle type, nothin. moved to another spot with larger vehicle, attempted to reproduce original steps: i.e. find a spot, tell follower to build camp while still in vehicle...  vehicle still there, billboard placed relatively significant distance away.

note this is testing the OP's post, not whatever weirdness is goin on with x7GoSu... looks like an issue with the tile set? but that doesn't make much sense. suggest updating it or changing it and seeing if that fixes your problem.

**Comment by x7GoSu** [comment] 2021-03-10 11:12
The problem comes from giving commands from the billboard and recovering NPC. The vehicle is visually still there but inside the file it seems to be sorta gone. I am unable to repair, refill, siphon because because the vehicle is not found.The map changing may be causing the issue. This was done on the latest version

**Comment by OliveChukar** [comment] 2021-03-12 15:57
I think x7GoSu may be seeing issue #46840.

**Closed** 2021-06-24 23:25 UTC
Labels: (S1 - Need confirmation), Player Faction Base / Camp
