### ISSUE TITLE
NPC treats Filter Mask (and possibly other clothing/armor) as weapon when telling them to use item

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#14983] opened 2016-01-24 03:44 UTC
NPC was equipped with Combat Knife. Found filter mask for him, tried to give it to him - said he had a better weapon.

**Comment by StopGamer** [comment] 2016-01-24 09:04
And then he says that it is too encumbr to wear. Usually when they dont want to wear they try to use as weapon. Try Survior Mask(any of),

**Comment by Coolthulhu** [comment] 2016-01-27 20:43
They treat all clothing first as weapon, then as armor. This is to allow using the same command as wield and wear. There are some cases where separate commands would be more useful (wearable weapon), but they're rare.
They won't wield the clothing as weapon, unless their current weapon is worse than the clothing.

Not a bug, closing.

**Closed by Coolthulhu** 2016-01-27 20:43 UTC
