### ISSUE TITLE
Can't see shit a turn after getting out of the large cardboard box

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58386] opened 2022-06-12 22:40 UTC
### Describe the bug

WTF. It wasn't like that some months ago.

### Steps to reproduce

Get into the `large cardboard box` `furniture`. Get out. Note that your sight is impared as if you were still in.

### Expected behavior

No sight impairment.

### Screenshots

https://tinystash.undef.im/il/3jqnmaQAJ5Q1qdc9U9KrnrpQWpCYDsX9gs34ZhVAPzLy6nKqovrqxvwcYC7zQDZEBUUB5VBQAjiqT2oJ817q4mHB.png

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-9084-gab8c2ff4b6-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Golfavel** [comment] 2022-06-12 23:15
Sight gets restored if you move an additional tile (excluding back into the box or another sight impairing tile), correct?

**Comment by l29ah** [comment] 2022-06-12 23:35
On Sun, Jun 12, 2022 at 04:16:04PM -0700, Golfavel wrote:
> Sight gets restored if you move an additional tile (excluding back into the box or another sight impairing tile), correct?

Yes.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by mqrause** [comment] 2022-06-13 03:03
Most likely a duplicate of #57537.

**Comment by l29ah** [comment] 2022-06-13 14:32
262de91aa7e2b06944511e3d3f8e8d65e890ce80 is the first bad commit
commit 262de91aa7e2b06944511e3d3f8e8d65e890ce80
Author: andrei <68240139+andrei8l@users.noreply.github.com>
Date:   Wed May 4 20:45:44 2022 +0300

    Partially revert #56231 (#57235)
    
    This reverts commit 52d991bb445a2dff2d93e24c51130020bcdc9df4.

@andrei8l

**Comment by l29ah** [comment] 2022-06-13 15:07
52d991bb445a2dff2d93e24c51130020bcdc9df4^ isn't buggy, so probably the revert itself is faulty.

**Closed** 2022-06-16 02:05 UTC
Labels: (S1 - Need confirmation)

**Comment by Sathra225** [comment] 2022-06-16 12:36
> Also affects improvised shelters.

That was a bug?

**Comment by NetSysFire** [comment] 2022-06-16 12:51
Yes. It also persists when you are not in the shelter but right beside it.
