### ISSUE TITLE
Make some tools usable while attached to a rope/etc. Make cameras wearable.

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#58673] opened 2022-06-24 10:34 UTC
### Is your feature request related to a problem? Please describe.
Character will continue taking a photo even while a monster strolls up and begins killing you.

EDIT: this is an issue with how i was wearing the camera. Didn't realize you couldn't access a tool attached to a short rope without detaching it (which is uninterruptable).

### Solution you would like.
Cameras should have the neck strap on them and be wearable.

Similar issue with bandages before. was fixed in #57317
I am wondering if a solution like that can be applied to other actions.

**Comment by mkrutov** [comment] 2022-06-24 10:38
Taking photo takes one second with camera, professional camera and smartphone. I don't think actions which take 1 second are supposed to be interruptable. 

Could you provide more information about which monster has attacked you, which device you used, etc?

**Comment by liminalRoar** [comment] 2022-06-24 10:42
It took a solid minute for the photo to take. Zombie wasnt even nearby before, maybe 45 tiles away, managed to run up and hit me half a dozen times while taking a photo of another mob.

It was taken with a professional camera hooked to my person by a short rope. I did have a flail in my hands as a weapon. Tried to take a photo with the camera from the action menu. The (camera) target was decently far away, maybe 35+ tiles.

**Comment by mkrutov** [comment] 2022-06-24 10:44
So the interaction taken there was, removing camera from the rope (which took bulk amount of time), then taking photo, not just taking photo.

**Comment by liminalRoar** [comment] 2022-06-24 10:45
that makes sense then. thanks. If i want start photographing the wildlife i should probably equip the camera lol.

**Comment by mkrutov** [comment] 2022-06-24 10:48
In case of exact described scenario (camera inside a pocket with high access time), I can reproduce originally described problem: the part of "taking camera off rope" doesn't seem to be interruptable, but this would be the case with anything (for example, activating a flashlight hanging on a rope takes 30 seconds which isn't interruptable either). Please don't close the issue just yet, this seems to be a legitimate problem.

**Comment by liminalRoar** [comment] 2022-06-24 10:55
I see. i would think that with any action taking that long, the character should be stoppable if getting attacked at the very least.

So the character actually takes the camera off the rope? i tried that in game because i figured you could easily access and use an item relatively quickly attached to a rope. quicker than digging through a bag for sure.

**Comment by liminalRoar** [comment] 2022-06-24 10:58
I also think that professional cameras will have a neck strap. I was surprised when i couldn't "wear" the camera.

**Comment by DamienRoyan** [comment] 2022-06-24 13:13
> I also think that professional cameras will have a neck strap. I was surprised when i couldn't "wear" the camera.

Yeah. At the very least there should be an option to attack a short rope to the camera to make it a wearable item.

**Comment by descan** [comment] 2022-06-24 22:43
Camera *bags* can be worn, and (most?) professional cameras I've found in game (from corpses spawns) came in a bag. That said, it's weird that the camera itself can't be modified with a rope - even if you don't do that in real life, a zombie apocalypse isn't real life, and someone refusing to just glue/tape/sew a rope onto their camera for ease-of-use because they don't have a bag would be really weird behaviour. 

(normal cameras have spawned without the bags - I don't know if professional cameras in other spawn scenarios, such as at shops or on shelving, would spawn them in the camera bag)

**Comment by liminalRoar** [comment] 2022-06-24 23:10
My favorite solution would be to add an actual camera strap that can be attached and worn around the neck. . A bag is not necassery always but would provide a good way to store a little more. The bad should be worn on the shoulder. (maybe we could actually add slight flexibility where some straps are worn, like wearing something specifically around the neck or shoulder, etc).

IRL - i would take solely the camera if i wanted the least amount of extra weight. that should also make operating the camera nearly as fast as holding it, or at least quite fast.
- i would use a camera bad if i wanted to take along extra batteries, SD card, or slip a phone or take other small gear with me.

**Closed** 2022-06-30 14:44 UTC
Labels: <Suggestion / Discussion>
