### ISSUE TITLE
It's coming! (0.D coordination issue) (for real) DONE

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#27843] opened 2019-01-24 21:59 UTC
It's finally time for 0.D, for real this time.

#### What does this mean?
We're really for real making a real push toward really releasing the real 0.D.
The realease blockers are tracked in the [realease project](https://github.com/CleverRaven/Cataclysm-DDA/projects/2).  Once these are addressed, we can proceed to realease.

#### What does this change?
We are effectively in *Feature Freeze* now.
I've established a release branch https://github.com/CleverRaven/Cataclysm-DDA/tree/0.D-branch
Bugfixes should be merged to the new 0.D-branch branch, and (typically) they should also be merged to the master branch.

* Going forward, any feature PRs should be merged only to the master branch.
* Once we enter *Content Freeze*, PRs that add new items/monsters/terrain/etc should not be merged to the 0.D-branch
* Once we enter *String Freeze*, PRs should not be merged to 0.D-branch if they edit any strings, even if the strings are slightly wrong.

- [x] Feature Freeze
- [x] Content Freeze
- [x] String Freeze
- [x] Blockers cleared
- [x] Publish release candidate
- [x] Completed Changelog
- [x] Merged Translations
- [x] Pick Release Name

#### Can I help?
If you know about any game-breaking bugs that are not listed [here](https://github.com/CleverRaven/Cataclysm-DDA/projects/2), please leave a comment with a link to the issue.

**Comment by DoomAngelBlade** [comment] 2019-01-24 22:18
https://github.com/CleverRaven/Cataclysm-DDA/issues/27758
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by I-am-Erk** [comment] 2019-01-24 23:18
Could we get a tag for PR's like "0.D freeze" so that if PRs are getting skipped due to the current state of the freeze, authors can see why? Otherwise I anticipate a bit of "why has nobody addressed my PR" going on in the next while.

**Comment by darktoes** [comment] 2019-01-24 23:38
I believe it just means that feature PR's will be added to the master branch but not the 0.D branch. So you can still PR features, but they won't be in 0.D.

So 0.C was Cooper, what's the D stand for?

**Comment by kevingranade** [comment] 2019-01-24 23:46
Correct, last time around Freeze meant "everything stalls until it's done", this time it's just that non-bugfix PRs go to the master branch.

> So 0.C was Cooper, what's the D stand for?

Oh right, I'll fix the checklist...

**Comment by BrettDong** [comment] 2019-01-25 02:37
Just curious, should contributors submit one bug fix PR to 0.D-branch, or submit two PRs one for 0.D-branch and another one for master branch?

**Comment by Firestorm01X2** [comment] 2019-01-25 04:12
https://github.com/CleverRaven/Cataclysm-DDA/issues/27731

This woriies me a bit. It is not gamebreaking, but it is noticable graphical bug. If it is affects alot of players - then it is problem

**Comment by Firestorm01X2** [comment] 2019-01-25 04:16
Additionally ingame help is outdated and contains misinformation.

And ingame tutorial should be checked. It nay be broken now.

**Comment by kevingranade** [comment] 2019-01-25 05:59
> Just curious, should contributors submit one bug fix PR to 0.D-branch, or submit two PRs one for 0.D-branch and another one for master branch?

Seperate PRs would make things easier, but it's not necessary.

> Additionally ingame help is outdated and contains misinformation.
> And ingame tutorial should be checked. It may be broken now.

If you have something specific to report, open an issue. I'm not inclined to block the release based on out-of date help, so whatever gets fixed before release will have to do, and I'm not planning on touching the tutorial.

**Comment by a1studmuffin** [comment] 2019-01-25 06:04
Woohoo! You may already be aware of it @kevingranade but I believe the Android build will need 28c87d1 merged from master into the 0.D branch to prevent a crash on startup.

**Comment by Firestorm01X2** [comment] 2019-01-25 09:45
> I'm not planning on touching the tutorial.

We have Tutorial issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/17984
And tutorial redisign issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/23395

Maybe it is better to just disable tutorial for 0.D.

**Comment by Night-Pryanik** [comment] 2019-01-25 11:40
> Pick Release Name

If I get it right, we name our releases after post-apocalyptic writers, right? As a possibility, we could name 0.D after Philip K. Dick.

**Comment by Firestorm01X2** [comment] 2019-01-25 12:18
>If I get it right, we name our releases after post-apocalyptic writers, right? As a possibility, we could name 0.D after Philip K. Dick.

Cataclysm: DDA 0.D "Dick". Perfect!

**Comment by nexusmrsep** [comment] 2019-01-25 17:59
> Could we get a tag for PR's like "0.D freeze"

I've added the label to the set.

**Comment by l29ah** [comment] 2019-01-26 01:30
I'm not sure if https://github.com/CleverRaven/Cataclysm-DDA/issues/26389 is considered game-breaking, but as for me the crafting mechanics is a big part of the game, and being unable to resume crafting annoys a lot and with zombie hordes enabled basically requires one to hide in a basement or at least a tough vehicle without windows for any serious crafting.

**Comment by Firestorm01X2** [comment] 2019-01-26 16:14
I am seeing more reports on this from external source:

https://github.com/CleverRaven/Cataclysm-DDA/issues/27731

It will defenitely hurt game presentation.

**Comment by Inglonias** [comment] 2019-01-26 16:57
#27731 can be worked around by setting the default renderer to something besides software mode, or at least you can set it to direct3D on windows. I don't know if that resolves the issue on OSX or Linux, though.

**Comment by I-am-Erk** [comment] 2019-01-26 17:09
If that's the case then we should at least change the default rendering mode in 0.D, although a better bugfix would be approps

**Comment by Firestorm01X2** [comment] 2019-01-26 17:46
There is no bugfix, but there is workaround that worked for me year ago. Game just should be built using older version of MXE.

**Comment by hyper2snyper** [comment] 2019-01-28 20:21
0.D Decklin

**Comment by RobertoVGoulart** [comment] 2019-01-31 03:17
> 
> 
> 0.D Decklin

We all know it's going to be Dick...

**Comment by Leland** [comment] 2019-01-31 03:47
Awesome. I have a couple things I'll try to get finished for this.

**Comment by hyper2snyper** [comment] 2019-02-01 03:05
> > 0.D Decklin
> 
> We all know it's going to be Dick...

That is true, i feel ashamed for suggesting anything else.

**Comment by Epictyphlosion** [comment] 2019-02-01 20:57
Also, there's #4173 

Free money for anyone that adds it

**Comment by Epictyphlosion** [comment] 2019-02-01 21:00
As well as #7534, #6821, #5684, #3671, and #3342.

These ones are very good issues that are pretty old. I'd love to see some of them addressed if anyone can do so

**Comment by I-am-Erk** [comment] 2019-02-02 02:58
The latter two of those four have solutions underway, although both are presently stalled out

**Comment by kevingranade** [comment] 2019-02-03 06:43
@Epictyphlosion none of those are candidates for release blockers., they're all far too complicatedfor it to be safe to drop in a solution at this point in the release process.

**Comment by kevingranade** [comment] 2019-02-03 23:55
I can see accepting a fix for #8979 if it was straightforward enough, but it's a bit involved to make into a release blocker.

**Comment by Zombiemanpig** [comment] 2019-02-06 12:44
Hey for name, I vote for 0.D Dick, in honor of Philip K. Dick, who wrote one of my favorite books:
Do Androids Dream of Electric Sheep?
Which was adapted as Bladerunner for the movie screens.

He is a legendary author of our time and should be honored.

**Comment by Epictyphlosion** [comment] 2019-02-06 19:06
> 
> 
> Hey for name, I vote for 0.D Dick, in honor of Philip K. Dick, who wrote one of my favorite books:
> Do Androids Dream of Electric Sheep?
> Which was adapted as Bladerunner for the movie screens.
> 
> He is a revolutionary author of our time and should be honored.

Fair enough, lol

**Comment by Wuzzy2** [comment] 2019-02-16 00:25
YES!!! Finally! I'm so proud of you. Pat yourselves on the back, you earned it. I know you worked like absolute madmen on this project.

Again, for this version I will definitely want to work on the German translation. How many strings are missing in German at the moment?
Once the string freeze is in effect, how can/should I contribute *without* using Transifex? The proprietary (and sadly, mandatory) JavaScript used by the Transifex website concerns me (see also: https://www.gnu.org/philosophy/javascript-trap.html).

I like to request to give translators AT LEAST 2 weeks of time. I mean, after string freeze, there must be at least 2 weeks before the release. Otherwise it will almost certainly be impossible to finish all the translations in time, even if you work on them like a madman. Trust me, I speak from experience. :D
Also shout the string freeze over all known possible and activate all translators

Another thing, about the strings: Maybe should run something like `aspell` over all the user-facing strings (if that even works) to find all those spelling mistakes before entering string freeze, what do you think?

---

Final question, off topic (feel free to ignore): Why did you have made this release so gigantic? I believe it's been 2-3 years since 0.C. Will you aim for a faster release cycle in future or do we have to get used to the idea of “1 release every 3 years”? ;-) I want to stress that 2-3 years is *extreme*.
I'm also concerned for practical reasons. Because you made this release so gigantic, you might have shot yourself in the foot because with increased features there is also more ways to screw up, and the pain to do a release increases as well. Maybe for the next time, set a hard time cap (e.g. 1 year without a release) after which a “soft” feature freeze applies automatically. It would stops major complicated features from being merged (minor ones might be fine, needs to be decided on case-to-case basis). It seems for this version you just added stuff and stuff and stuff and never stopped. It's not good when you sit on a huge mountain of unreleased features and that mountain just grows and grows and grows …  It would be a miracle if you could sleep well at night, with all this burden on your shoulders …
Anyway, I'm so glad that you decided to do releases again! :D

**Comment by kevingranade** [comment] 2019-02-16 03:59
I'm fine with string freeze + 2 weeks for translators, that's one of the main reasons to do a formal release after all.

We can probably import the .pot and the German translation file into Launchpad again if you like. Alternately if it's just you, you can translate the .po file with a text editor.

It looks like the German translation has ~30,000 untranslated strings, and ~60,000 more with proposed but unreviewed translations.

A contributor that goes by @pupsi-mupsi seems to be the most recently active translator.

I'll definitely take a look at doing a spellcheck before string freeze.

I plan on doing future releases more frequently, part of the delay was due to spending some time automating parts of the release process to avoid such a huge backlog in the future.  I'm thinking more like several months than a year.

The dominant reason for the delay was the birth of my son.  I tried and failed to complete a release before he was born, and then was totally overwhelmed with caring for him and working for many months.  Once I was able to return to steady contribution, the project was a bit out of control and it took me until now to close in on releasing.

**Comment by Pupsi-Mupsi** [comment] 2019-02-16 16:55
> How many strings are missing in German at the moment?

Real life got in the way (sickness and work...).
1067 strings are untranslated.
I could help if needed.

![grafik](https://user-images.githubusercontent.com/44737997/52902604-8514a180-3213-11e9-9014-041b258dae2d.png)

**Comment by Wuzzy2** [comment] 2019-02-16 19:44
> We can probably import the .pot and the German translation file into Launchpad again if you like. 

No, definitely not Launchpad again. XD The server was just too damn slow, sorry. I initially supported from moving away from Launchpad (actually, I still do) but back then I wasn't as much concerned about Transifex. This has changed now.
I had very good experience with hosted.weblate.org and it does not have problems with proprietary code (Weblate is 100% free software). It's a good replacement. I don't know if Weblate even existed back then.

Anyway, switching the translation platform will not be a minor task and probably needs support from more people. This should probably be discussed in a different issue. Probably it's too late to switch at this stage now, right before release, it might make things too messy for you and others.

> Alternately if it's just you, you can translate the .po file with a text editor.

Well, that was my first thought, too, but this seems a bit dangerous as I might clash with other translators who might work on the same strings simultanously. Or that an automated update screws me over and destroys my work (or messes with it). The problem is not really how I actually translate, but how to avoid conflicts. Should I just send you daily patches or something like that, to minimize the risk of collisions?

On the other hand, we're “only” talking about 1067 strings here. That doesn't sound too bad. :-)

> The dominant reason for the delay was the birth of my son. 

Ohhhhhhhh! That explains a LOT. No further questions, your honour.

**Comment by kevingranade** [comment] 2019-02-17 04:31
We are down to FOUR release blockers, I'm escalating to content freeze, translators start your engines (if they aren't already).
I'm probably going to move to string freeze as soon as #28232 is merged.

**Comment by kevingranade** [comment] 2019-02-18 20:26
Two release blockers remain, one has a candidate fix, and the other is in progress and needs testing before finalization.
We are proceeding to string freeze, bug fixes that do not touch translatable strings can still make it in, but that's it.

**Comment by Throwaway-name** [comment] 2019-02-19 03:46
https://github.com/CleverRaven/Cataclysm-DDA/issues/26364
https://github.com/CleverRaven/Cataclysm-DDA/issues/27974
https://github.com/CleverRaven/Cataclysm-DDA/issues/28203
https://github.com/CleverRaven/Cataclysm-DDA/issues/28243

**Comment by Wuzzy2** [comment] 2019-02-19 16:26
#28264

**Comment by Epictyphlosion** [comment] 2019-02-21 16:42
Damn, I'm too late to commit the newly styled vehicle JSONs. This is what I get for being lazy, lol

**Comment by Zombiemanpig** [comment] 2019-02-24 13:49
I don't have friends who read IRL so I just want to say that Flow My Tears, The Policeman Said, also by Philip K. Dick is also a really good book and I really recommend it even more than do Androids Dream of Electric Sheep.

I just finished it. Really good.

**Comment by kevingranade** [comment] 2019-02-25 00:04
In order to get better testing, I'm going to copy the current master branch to a branch named development, and replace the current master with a copy of the 0.D-branch.
This means that until the release is completed, the Jenkins and travis builds will be exercising 0.D code, and the released versions will also be pure 0.D.

Going forward, we should only merge 0.D changes to master, and any future changes should go to the development branch.

After the release, development will be merged back onto master and continue as usual.

**Comment by a1studmuffin** [comment] 2019-02-25 09:20
As I posted in the Reddit thread, I just tried Android build 8544 and am seeing SDL viewport rendering scale issues with both the hardware and software renderer that makes the game unplayable. The main menu draws at the correct size at first, but draws updates (eg. cycling menu items on the main menu) much smaller in the top left corner. Did someone change some SDL renderer logic for the 0.D release? This is new behaviour in Android build 8544 (0.C-37525-g2a51b1b). Build 8539 (0.C-37569-gbf99f81) and earlier work fine, though I assume based on those version numbers that the 0.D/master branch switchover Kevin mentioned has happened between these two build machine versions.

**Comment by ifreund** [comment] 2019-02-25 10:36
@a1studmuffin yeah, I probably messed that up with #28253.  I don't think I have any way of testing on android unfortunately, but will see if I can figure out a fix from just reading the code

**Comment by aawilson** [comment] 2019-02-25 16:15
https://en.wikipedia.org/wiki/List_of_zombie_films

**Comment by aawilson** [comment] 2019-02-25 16:20
For authors, Denning wrote the original "Dark Sun" stuff.  Dunsany wrote "The King of Elfland's Daughter" and is considered the progenitor of modern SF and Fantasy. There's also Doyle, as in Sir Arthur Conan Doyle.

**Comment by a1studmuffin** [comment] 2019-02-26 00:35
@ifreund No worries, feel free to ping me if you've got a candidate fix - I will test Android to verify before you make the PR.

**Comment by BrettDong** [comment] 2019-02-26 09:27
Translation progress as of Feb 26:

| language  | progress / %  |
|---|---|
| Chinese (Simplified) | 100 |
| Russian | 99.24 |
| Japanese | 99.07 |
| Polish | 99.04 |
| German | 98.51 |
| Spanish (Argentina) | 97.56 |
| Chinese (Traditional) | 80.62 |
| Spanish (Spain) | 70.77 |
| Korean | 64.23 |
| Hungarian | 50.97 |
| French | 41.16 |

**Comment by Epictyphlosion** [comment] 2019-02-26 20:43
@BrettDong Japanese and Chinese is ahead of French and German? 
**Nani?!**

**Comment by Wuzzy2** [comment] 2019-02-27 06:13
> In all seriousness, I could try putting some placeholder translations in for some languages. And by placeholder, I mean using online translators (not specifically Google Translate).

*spits coffee on screen*
*head smashes on table*
Nooooooooooooooooooooooooo …
Never ever do this shit, please. All auto-translators suck, it would just create a huge mess.
German will be finished soon enough, just be patient. Jeez.

**Comment by pingpong2011** [comment] 2019-03-01 01:24
Is it going to work period and look correct?

Nobody had commented on my discourse thread or the github issue with clear examples and reproduction steps:
https://github.com/CleverRaven/Cataclysm-DDA/issues/24844

I try out the "stable" revision, have to close/re-open, and it keeps resizing the window and distorting fonts. I just tried out 0.C-37549-gfaafa3a (8551) and that issues gone, but font rendering is still a little bit off from .C-stable. It doesn't help the "patch" mentioned in my issue above STILL hasn't been addressed, and it would probably take is removing the equals or adding a +1 to the width and height comparisons (line 1955 in the diff) to make font sizes work. If I choose size 18 font I want size 18 font damnit, not get 18 by doing 19, 19, 18 (width, height, size) that still has some errors (single line of pixels missing on one side or the other, distorted letters). An ASCII game that incorrectly renders ASCII. I don't get it.

**Comment by kevingranade** [comment] 2019-03-01 08:34
Sorry I haven't acknowledged your issue, I will be looking into the font
rendering problem very soon, it's the next problem I plan to investigate.

**Comment by RickySandbox** [comment] 2019-03-01 17:48
> I try out the "stable" revision, have to close/re-open, and it keeps resizing the window and distorting fonts. I just tried out 0.C-37549-gfaafa3a (8551) and that issues gone, but font rendering is still a little bit off from .C-stable. It doesn't help the "patch" mentioned in my issue above STILL hasn't been addressed, and it would probably take is removing the equals or adding a +1 to the width and height comparisons (line 1955 in the diff) to make font sizes work. If I choose size 18 font I want size 18 font damnit, not get 18 by doing 19, 19, 18 (width, height, size) that still has some errors (single line of pixels missing on one side or the other, distorted letters). An ASCII game that incorrectly renders ASCII. I don't get it.

A font at 18pt isn't 18 pixels wide. I've played with Bitstream Vera Mono at 18pt. I downloaded VeraMono.ttf into my `Cataclysm-DDA/data/font` directory, then I loaded up `Cataclysm-DDA/config/fonts.json` in my text editor and changed it like this:

> {
>     "fontblending": false,
>     "fontwidth": 11,
>     "fontheight": 22,
>     "fontsize": 18,
>     "typeface": "VeraMono",
>     "map_fontwidth": 22,
>     "map_fontheight": 22,
>     "map_fontsize": 18,
>     "map_typeface": "VeraMono",
>     "overmap_fontwidth": 22,
>     "overmap_fontheight": 22,
>     "overmap_fontsize": 18,
>     "overmap_typeface": "VeraMono"
> }
> 

I played with square tiles on the map & overmap, as my settings reflect, but you could easily change the width to 11 if you wanted a non-square display.

The problem, if anyone is interested, is related to font hinting and has been debated for years. In fact, Macs ignore font hinting by default, whereas Windows does not. If you'd like to know more, then you could start here: https://www.typotheque.com/articles/hinting

**Comment by pingpong2011** [comment] 2019-03-01 17:52
Thank you kevin, I apologize for being a little toxic about it.

Ricky, you made the post as I was making mine! Since you seem knowledgeable, could there be a way to convert a font to a different kind, for separate scaling options / more 1:1 expectations? I'd gladly raster/bake my own font if it wasn't too difficult.

**Comment by Epictyphlosion** [comment] 2019-03-01 20:10
> Never ever do this shit, please. All auto-translators suck, it would just create a huge mess.
> German will be finished soon enough, just be patient. Jeez.

I didn't think that'd be well received, lol
I should probably just learn C++ or something. That way I can make myself useful instead of just reformatting code and simple things like that

**Comment by Wuzzy2** [comment] 2019-03-01 23:52
May I direct the attention to #23484?

**Comment by kevingranade** [comment] 2019-03-03 19:18
Build 8561 is a pretty serious candidate.

**Comment by Throwaway-name** [comment] 2019-03-04 02:07
Tazeell on the discourse reports an issue with the vehicle water faucet: https://discourse.cataclysmdda.org/t/vehicle-water-faucet/19053

**Comment by Night-Pryanik** [comment] 2019-03-04 07:06
> Tazeell on the discourse reports an issue with the vehicle water faucet: https://discourse.cataclysmdda.org/t/vehicle-water-faucet/19053

Making faucets compatible with any liquid in the tank is an enhancement and not a release blocker.

**Comment by Inglonias** [comment] 2019-03-05 12:56
are we done yet?

**Closed** 2019-03-08 03:46 UTC
Labels: Organization

**Comment by Throwaway-name** [comment] 2019-03-08 05:19
Mazel tov!

**Comment by cainiaowu** [comment] 2019-03-08 05:36
Well, somebody forgot to update the translations, but whatever, we finally did it.

**Comment by Leland** [comment] 2019-03-10 23:45
Congrats all!
