### ISSUE TITLE
ATMs spawned en masse

### ISSUE THREAD

**Issue by JohnHenryEton** [CleverRaven/Cataclysm-DDA#76200] opened 2024-09-04 20:03 UTC
### Describe the bug

After downloading a newer version from the experimental branch, ATMs are appearing in unexpected places. Possibly only in previously explored areas. Going through walls, other unoccupied areas, etc. At first I noticed it in a newer area I was looting, but as I was returning home I found a spot where I was sure there weren't loads of ATMs before. I'm guessing it's a bug.

### Attach save file

[test-trimmed.tar.gz](https://github.com/user-attachments/files/16879460/test-trimmed.tar.gz)

### Steps to reproduce

Drive around to previously explored places that spawn ATMs. or teleport to one like gas stations?
Get invaded by the ATM hoard? 

### Expected behavior

Not being invaded by the ATMtide

### Screenshots

![Screenshot 2024-09-04 151048](https://github.com/user-attachments/assets/24c02fb9-5375-4ae6-97ff-f45a04e8fbf6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4112 (23H2)
- Game Version: 9633d7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Bionic Professions [package_bionic_professions],
    Magiclysm Revamp and Additions [magicrevamp],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    <color_cyan>Arcana</color>/DinoMod Patchmod [Arcana_Dinomod_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Crazy Cataclysm [crazy_cataclysm],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Bombastic Perks [bombastic_perks],
    Xedra Evolved [xedra_evolved],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Bionic Slots [no_cbm_slots],
    <color_light_blue>Hamm's teaks for things</color> [HammTweaks]
]

**Comment by GuardianDll** [comment] 2024-09-04 20:24
Can't reproduce on the most recent experimental
i suspect the issue is in some of out of repo mod, please confirm it happens in vanilla
- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 0.G-11844-g 33970f51ee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
![image](https://github.com/user-attachments/assets/aefc282c-cb60-4767-b5a5-114a69d66c73)

**Comment by JohnHenryEton** [comment] 2024-09-04 20:29
I couldn't get it to happen on a new save at all. Either with my current modlist or otherwise. Only happened with an ongoing save.

**Comment by HadeanLake** [comment] 2024-09-04 20:38
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 705ea526-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
![Uploading 2024-09-04-233804_1920x1080_scrot.jpg…]()

**Comment by GuardianDll** [comment] 2024-09-04 20:47
something fishy going on
is it `ter_furn_migration` from #76051 causes some issues on game load?

**Comment by JohnHenryEton** [comment] 2024-09-04 20:49
I was about to comment that I had just replicated the issue by downgrading to a build from the 2nd, finding an atm, upgrading again with a repo only list.

**Comment by HadeanLake** [comment] 2024-09-04 21:59
> is it ter_furn_migration from https://github.com/CleverRaven/Cataclysm-DDA/pull/76051 causes some issues on game load?

Yes. `"to_ter"` is missing in `ter_furn_migration` JSON, and code processing it does not reset furniture after placing it once

Rough and briefly tested in only this one scenario draft patch to fix this:
```patch
--- a/data/json/obsoletion_and_migration_0.I/obsolete_furniture.json
+++ b/data/json/obsoletion_and_migration_0.I/obsolete_furniture.json
@@ -91,6 +91,7 @@
   {
     "type": "ter_furn_migration",
     "from_ter": "t_atm",
+    "to_ter": "t_thconc_floor",
     "to_furn": "f_atm_off"
   }
 ]  

--- a/src/savegame_json.cpp
+++ b/src/savegame_json.cpp
@@ -4912,10 +4912,10 @@ void submap::load( const JsonValue &jv, const std::string &member_name, int vers
             // terrain is encoded using simple RLE
             int remaining = 0;
             int_id<ter_t> iid_ter;
-            int_id<furn_t> iid_furn;
             for( int j = 0; j < SEEY; j++ ) {
                 // NOLINTNEXTLINE(modernize-loop-convert)
                 for( int i = 0; i < SEEX; i++ ) {
+                    int_id<furn_t> iid_furn;
                     if( !remaining ) {
                         JsonValue terrain_entry = terrain_json.next_value();
                         auto migrate_terstr = [&]( ter_str_id terstr ) { 
```

**Comment by JohnHenryEton** [comment] 2024-09-04 23:09
Is there a good way to remove these ATMs from a save when this gets fixed?

**Comment by CoroNaut** [comment] 2024-09-05 02:03
to remove furniture:
1. debug menu 
2. map 
3. map editor (disables achievements)
4. scroll overtop your ATM
5. 'r' furniture
6. '/' filter for 'null' (optional to make it easier to get to the 'nothing' furniture)
7. select "nothing" furniture.
8. repeat for all other ATM's

**Comment by mqrause** [comment] 2024-09-05 06:38
> there is probably a better way to reset iid_furn

To me it looks like both `iid_ter` and `iid_furn` should only be declared inside the loops, so they reset automatically.

**Comment by HadeanLake** [comment] 2024-09-05 09:48
> should only be declared inside the loops,

Their value is used outside of the iteration it was assigned. Game checks if next tiles are same, writes amount of same tiles into `remaining` var and uses it to skip some logic  

checking `!remaining` again before iteration ends and resetting `iid_furn` there (where we had run out of same tiles to assign it to) seems to work, but I still do not like it.
```patch
--- a/src/savegame_json.cpp
+++ b/src/savegame_json.cpp
@@ -4951,6 +4951,9 @@ void submap::load( const JsonValue &jv, const std::string &member_name, int vers
                     if( iid_furn ) {
                         m->frn[i][j] = iid_furn;
                     }
+                    if ( !remaining ) {
+                        iid_furn = furn_str_id::NULL_ID().id();
+                    }
                 }
             }
             if( remaining ) {
```

When testing fix for this, it is important to have multiple ATM's in a row and one on the next line. I tested using this save:
![2024-09-05-124101_1920x1080_scrot](https://github.com/user-attachments/assets/fe9b2f6c-ee5c-46c0-9bec-aa210e3203a5)
[ATM corruption-trimmed.tar.gz](https://github.com/user-attachments/files/16887358/ATM.corruption-trimmed.tar.gz)

**Comment by mqrause** [comment] 2024-09-05 10:51
> Their value is used outside of the iteration it was assigned. Game checks if next tiles are same, writes amount of same tiles into `remaining` var and uses it to skip some logic

Oh, right, I was misreading things. So instead of resetting `iid_furn`, I'd suggest simply always setting it, and not just if it's not the `NULL_ID`. (And maybe also add a check if the furniture id is actually valid.)

**Comment by JohnHenryEton** [comment] 2024-09-05 14:18
> to remove furniture:
> 
>     1. debug menu
> 
>     2. map
> 
>     3. map editor (disables achievements)
> 
>     4. scroll overtop your ATM
> 
>     5. 'r' furniture
> 
>     6. '/' filter for 'null' (optional to make it easier to get to the 'nothing' furniture)
> 
>     7. select "nothing" furniture.
> 
>     8. repeat for all other ATM's
> 
> 
> Alternatively, you can just regenerate the whole overmap chunk.
> 
>     1. debug menu
> 
>     2. map
> 
>     3. map editor
> 
>     4. 'o' overmap/mapgen
> 
>     5. '/' filter for "s_gas_1_north" (im pretty sure this is the exact gas station in your picture)
> 
>     6. '3' Apply

The latter is probably better given the number of spawned ATMs, thanks.

**Closed** 2024-09-17 04:16 UTC
Labels: (S1 - Need confirmation)
