### ISSUE TITLE
Cant change start date (season)

### ISSUE THREAD

**Issue by RobertBoettcherSF** [CleverRaven/Cataclysm-DDA#76720] opened 2024-09-29 10:46 UTC
### Describe the bug

Currently unable to adjust value of season so I can play Eternal Winter. The starting date season wont change.

### Attach save file

N/A

### Steps to reproduce

- Open new world, try to generate new character.
- In scenarion screen, press % to see date change options.
- Select s for season, the value you enter will be added to the y year value.

### Expected behavior

Being able to set the season from 0 Spring to 3 Winter so game can be played with Eternal Season on + Winter Setting for Bordered scenario ala Nightswatch.

### Screenshots

![2024-09-29](https://github.com/user-attachments/assets/3a7a4cac-0ca1-4152-b491-36f42866a13e)

### Versions and configuration

build type: windows-tiles-x64-msvc
build number: 2024-09-29-0806
commit sha: 26de5a1cbe7fafdb72cdff7a03fe5d4f68a7d592
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/26de5a1cbe7fafdb72cdff7a03fe5d4f68a7d592

### Additional context

[crash.log](https://github.com/user-attachments/files/17178940/crash.log)
[debug.log](https://github.com/user-attachments/files/17178941/debug.log)

**Comment by ZhilkinSerg** [comment] 2024-09-29 16:21
Duplicate of #67829

**Closed by ZhilkinSerg** 2024-09-29 16:21 UTC
Labels: <Bug>, (S2 - Confirmed), Character / World Generation
