### ISSUE TITLE
'!' is used as a bionic designation, becomes inaccassable

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#9170] opened 2014-09-22 00:59 UTC
in 'p' to use bionics, '!' is the key to toggle inspecting a bionic rather than using it. However, when you have a crap-ton of bionics and work through the normal alphabetic designations twice, you get one that gets designated '!', but you can never use or inspect it because that key always toggles inspect mode.

**Comment by illi-kun** [comment] 2016-04-14 22:27
Closed as a duplicate of #10563 (which contains more useful info).

**Closed by illi-kun** 2016-04-14 22:27 UTC
Labels: Bug, Information / Interface
