### ISSUE TITLE
Strange: player is already assigned to mission 1 through 10

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#67277] opened 2023-07-29 20:28 UTC
### Describe the bug

 DEBUG    : strange: player is already assigned to mission 1

 FUNCTION : assign
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission.cpp
 LINE     : 300
 VERSION  : 6956921

### Attach save file

N/A

### Steps to reproduce

1. Install the latest experimental as of this issue
2. Go to create a character
3. Encounter the errors shown
4. No further issues?

### Expected behavior

No error messages

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 6956921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Lonely Evac Scenario [Lonely_Evac]
]

**Comment by Inglonias** [comment] 2023-07-29 20:31
It's entirely possible I have some old data somewhere - I'm using the catapult launcher which separates user data out from the game files.

**Comment by MrHrulgin** [comment] 2023-07-29 22:29
I've seen the same thing, using the fork of the CDDA Launcher.

**Comment by NetSysFire** [comment] 2023-07-30 07:36
I can confirm this, although I get mission 1-128.

**Comment by Inglonias** [comment] 2023-08-21 00:06
Error is thrown at L300 of mission.cpp

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mission.cpp#L300

**Comment by Brambor** [comment] 2023-09-01 02:01
Stack trace
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/cd4dc278-b546-44af-8abe-1d2ed22b2e28)

**Comment by Termineitor244** [comment] 2023-10-15 18:38
Happened to me too, in the most recent experimental version, for me the missions are 1 and 2.

 DEBUG    : strange: player is already assigned to mission 2

 FUNCTION : assign
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission.cpp
 LINE     : 300
 VERSION  : 838f893

**Comment by lispcoc** [comment] 2023-11-18 06:30
I think this is probably a problem that occurs with a specific MOD configuration, but the following MOD cannot be found.

Fewer Soldier Extras [Fewer_Soldiers],
Lonely Evac Scenario [Lonely_Evac]

**Comment by Inglonias** [comment] 2023-11-18 11:36
I wrote those mods, so you wouldn't have them. Fewer Soldier Extras does what it says on the tin. Cute the number of soldier extras in half.

Lonely Evac adds a starting scenario that is identical to the standard start minus the NPC.

Other people, presumably with different mod setups, have already reported this issue.

**Comment by lispcoc** [comment] 2023-11-18 14:36
I tried both the latest development version and the version mentioned in the issue, but was unable to reproduce the issue. It seems that no special settings are required, but perhaps the incidence is simply low?

**Comment by NetSysFire** [comment] 2023-11-18 23:40
I can still reproduce. At least on older worlds.

**Comment by Inglonias** [comment] 2023-11-19 14:05
I reinstalled the game and cleared my save files - looks like the issue is gone for me.

If it's still reproducible with older saves, I feel the issue should stay open, but I don't know if it really counts as a release blocker, since it doesn't actually do much to harm things. That said, I'm not the one in charge. It's the core dev team's call.

**Comment by NetSysFire** [comment] 2023-11-19 14:25
Most people will be reusing their old worlds and if these come with persistent errors this is not acceptable.

**Comment by BrettDong** [comment] 2023-11-23 13:21
Just encountered this bug in a freshly created world (created by New Game -> Play Now!)

<img width="1072" alt="" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/21075502/5da2ddb5-4eac-416e-a64e-c1e12c4349dc">

**Comment by Inglonias** [comment] 2023-11-23 15:07
That's actually really good info. So a workaround is just to delete the memorial folder.

**Comment by lispcoc** [comment] 2023-11-23 16:01
Perhaps the cause of this problem lies in `void stats_tracker::deserialize( const JsonObject &jo )` in src\savegame_json.cpp
If there is data before `game_avatar_new` was implemented in memorial, a dummy `game_avatar_new` event will be issued to match the statistical information.
If there is an event that assigns a mission triggered by the issuance of `game_avatar_new`, this will cause mission duplication.
If there is an event that assigns a mission based on the issuance of `game_avatar_new` (specifically "MISSION_CAMP_LEADERSHIP_CHANGE"), there is a possibility that IDs will overlap with characters that already exist in the world.
This is because the avatar's ID is a provisional value at this time.

**Closed** 2024-01-31 03:37 UTC
Labels: (S2 - Confirmed), (P2 - High), Missions, [C++], Character / World Generation, Help Wanted
