### ISSUE TITLE
Item duplication when moving an amount less than all

### ISSUE THREAD

**Issue by Nerdy314159265** [CleverRaven/Cataclysm-DDA#47920] opened 2021-03-07 04:01 UTC
# Describe the bug

Item duplication whenever moving a stack of items less than the all of them in the container

# Steps To Reproduce

1. Spawn 1000 of some ammo
2. Move 500 of ammo to another location using advanced item menu and move amount
3. 500 ammo appear in location without removing 500 from other location.

# Expected behavior

Unless the character is Jesus (new character scenario?), the item should move to the new location instead of duplicating to the new location.

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns]
]

**Comment by wapcaplet** [comment] 2021-03-07 04:20
Thanks for reporting! Looks like a duplicate of #47884

**Closed** 2021-03-07 04:20 UTC
Labels: (S3 - Duplicate)

**Comment by Nerdy314159265** [comment] 2021-03-07 15:41
@wapcaplet Whoops, didn't see it. Sorry for the duplicate!
