### ISSUE TITLE
Ability to assign sleeping location to NPC

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15149] opened 2016-02-01 13:20 UTC
Maybe something like using area to designate npc sleeping area - would only affect NPCs that are following the player, or you could have multiple and tell the NPC which to sleep at. Npc would still look for the most comfortable place to sleep in said area.

Another option is to specify a point where the NPC should sleep.

Also, a way to tell the NPC to GO SLEEP would be nice.

**Comment by Coolthulhu** [comment] 2016-02-01 14:34
I wanted to implement it like 3 times already, but always drop the project when I realize that the only proper way of implementing that involved updating zone code. And I hate zone code.

I do plan to implement it, but it may take a while before it is implementable without hacks.

> Also, a way to tell the NPC to GO SLEEP would be nice.

I'll probably just remove penalties for telling NPC to stay in one area.
Telling NPC to go to sleep wouldn't work too well as the NPCs share sleep rules with player - they can't just drop on the ground and sleep, they need to be tired enough. And if they aren't (for example, because they are in pain or on drugs), a single attempt at sleep will end quickly.

**Comment by macrosblackd** [comment] 2016-02-01 15:26
My thoughts on the usage of telling the NPC to go to sleep would be telling him not to sleep whenever, then when you get back to a safe area, letting npc know he can now go to sleep.

I'm going to take a look at the zone code and see what I can come up with - I'm probably going to refactor it a bit to handle zones with multiple types associated with one. IE: Zone in main storage: No NPC Pickup, No Auto Pickup

**Comment by Coolthulhu** [comment] 2016-02-01 15:37
> I'm going to take a look at the zone code and see what I can come up with - I'm probably going to refactor it a bit to handle zones with multiple types associated with one. IE: Zone in main storage: No NPC Pickup, No Auto Pickup

The problem is not multiple types - the problem is lack of ability to quickly get all the zones of a given type in a given area.
For example, "get all sleep zones in current reality bubble".

**Comment by macrosblackd** [comment] 2016-02-01 17:11
Is there a way to get the bounds of the reality bubble? Determining if a rectangle is inside another rectangle is fairly easy.

**Comment by Coolthulhu** [comment] 2016-02-01 17:40
Yeah, it's easy.
Rectangle clipping itself also is easy.
The problems start when you realize how unfriendly to alterations is the current zone interface.

I guess just going linearly through all zones, checking their types, clipping ones in bubble and returning a vector of the clipped rectangles would be enough, but I always tried to make it a bit more future-proof. That's probably why I dropped it in the end.
But then, stacking hacks and shortcuts on an already hacky implementation could lead to an unmaintainable mess, so be wary of bad practices.

**Comment by Leland** [comment] 2017-05-04 04:38
Discussion's been stalled on this for over a year. Closing.

**Closed by Leland** 2017-05-04 04:38 UTC
Labels: Enhancement, NPC
