### ISSUE TITLE
Melee weapons durability decreases even if attack was a miss

### ISSUE THREAD

**Issue by Demivan** [CleverRaven/Cataclysm-DDA#54477] opened 2022-01-16 12:58 UTC
### Describe the bug

Melee weapons durability decreases even if attack was a miss

### Steps to reproduce

1. Attack with a melee weapon
2. Miss an attack
3. Weapon durability is decreased

### Expected behavior

If attack misses (you did not hit a monster) weapon durability should not degrade.

### Screenshots

![before-fix](https://user-images.githubusercontent.com/2339406/149615305-c0521c4b-9412-436d-ae3e-c0251869311a.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-5237-g18f89b7e67 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I have created a PR to fix this #54439 but it was closed. 
So opening the issue to discuss: maybe it is intended and is not a bug?

**Comment by NetSysFire** [comment] 2022-01-16 13:19
Duplicate of #53527

**Closed** 2022-01-16 13:19 UTC
Labels: (S3 - Duplicate)

**Comment by Demivan** [comment] 2022-01-16 13:22
Sorry, missed that issue somehow
