### ISSUE TITLE
crash while driving a vehicle

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30141] opened 2019-05-01 07:45 UTC
**Describe the bug**  
I got a crash while driving around the map. Not sure what makes it do it, but apparently the gamehad trouble loading the map

**To Reproduce**  
1. Drive around.

**Expected behavior**  
I don't encounter any crashes and i can drive normally

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2318-g1323624
 - Graphics version: Tiles
 - Mods loaded:
[
  "dda",
  "aftershock",
  "Tolerate_This",
  "FIC_Weapons",
  "realguns",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "hydroponics",
  "MMA",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "no_npc_food"
]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.
[Main World_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3133962/Main.World_copy.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3133963/crash.log)

**Comment by ipcyborg** [comment] 2019-08-02 08:30
Can't reproduce on 0.D-6072-g4add125
Crash log isn't really helping either. Could you please provide more info?

**Comment by Night-Pryanik** [comment] 2019-10-08 11:41
No confirmation in over half a year, closing for now. Ping me if this is still an issue.

**Closed by Night-Pryanik** 2019-10-08 11:41 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>, Vehicles
