### ISSUE TITLE
Unable to open nested menus from the crafting search function

### ISSUE THREAD

**Issue by TheDandyGuy** [CleverRaven/Cataclysm-DDA#60603] opened 2022-08-30 19:48 UTC
### Describe the bug

When making a search in the crafting(&) menu, all nested menus aren't able to be opened. 

For example, searching "staff" in the crafting menu brings up the "staffs" nested menu, but trying to select it will not open it.

I am sure it is being worked on, as nested menus are a new feature, but I figured making an issue would bring some attention to it.

### Steps to reproduce

Open crafting menu(&)

Use search function "F" for a nested menu (e.g. "staffs", etc)

Try opening it with "enter"

### Expected behavior

Selecting a nested menu in the search function should open it

### Versions and configuration

Experimental 2022-08-30-1725

**Comment by ANickelN** [comment] 2022-08-30 19:50
/confirmed
Just hasn't been added yet.

**Comment by TheDandyGuy** [comment] 2022-08-30 19:51
> /confirmed Just hasn't been added yet.

Gotcha, sorry for the inconvenience!

**Comment by mlange-42** [comment] 2022-08-30 20:27
Duplicate of #60359

**Comment by bombasticSlacks** [comment] 2022-09-04 19:06
It actually originally worked and I somehow broke it in a further PR anyways I'm currently PRing the fix

**Closed** 2022-09-05 22:32 UTC
Labels: (S2 - Confirmed)
