### ISSUE TITLE
Pressing ^ in driver's seat doesn't bring up car menu

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#22332] opened 2017-11-02 17:53 UTC
Game version:
0.C-24810-g7e56bbe - Build 6905 (tiles)

Operating system:
Windows 10

Mods active:
(Default)

### Expected behavior
Pressing `^` once should bring up the car menu when you are in the driver's seat.

### Actual behavior
Pressing `^` doesn't do anything until another key (e.g. escape) is pressed. Then the driving menu shows up as expected.

### Steps to reproduce the behavior
See above. I'm pretty sure this worked like expected a few versions ago.

**Comment by Coolthulhu** [comment] 2017-11-02 18:39
Most likely related to keyboard layout.

**Comment by Broken-Admin** [comment] 2017-11-02 18:41
You're using the QWERTY layout?

**Comment by rm-code** [comment] 2017-11-02 18:42
> Most likely related to keyboard layout.
Yeah I'm pretty sure it's a problem on my end. Any ideas?

> You're using the QWERTY layout?
QUERTZ (forgot to mention that in the OP).

**Comment by Clyybber** [comment] 2017-11-02 18:54
That's kind of expected when using a layout with deadkeys. You can switch to a nodeadkeys keyboard layout. Not really a bug on CDDA's side. Though it would be nice if CDDA would have an option to directly use the keypresses.

**Comment by rm-code** [comment] 2017-11-02 18:54
The funny thing is that I'm pretty sure it worked fine a few versions ago 😕

**Comment by Lamandus** [comment] 2017-11-02 21:38
rm-code: I am also using the qwertz-keyboard (do any other than german speaking ppl got these?) and I can confirm, it worked with a single click before, now it needs a "double-tab" to function. I changed the button thereafter but it worked some months ago.

**Comment by OzoneH3** [comment] 2017-11-02 21:56
I'm using german quertz as well and it only ever worked for me with double tapping ^.
Dosen't matter what system windows 7, 10, ubuntu, all the same.

**Comment by rm-code** [comment] 2017-11-02 22:07
Are you using tiles?

**Comment by OzoneH3** [comment] 2017-11-02 22:25
No curses only.

**Comment by Lamandus** [comment] 2017-11-02 22:29
I am using tiles, Ozone is right, only double tapping works for me, as well. But it worked some time ago.

**Comment by rm-code** [comment] 2017-11-02 22:31
Using tiles too so maybe something broke in the tiles build.

**Comment by Lamandus** [comment] 2017-11-02 23:05
OzoneH3 has the same problem as we do, so doesn't matter. it is our bêâûtîfûl kêybôârd!

**Comment by DemAvalon** [comment] 2017-11-03 04:48
I think this is a duplicate of this #21604

**Closed** 2017-11-03 10:39 UTC
