### ISSUE TITLE
UPS conversion mod crash

### ISSUE THREAD

**Issue by archigo** [CleverRaven/Cataclysm-DDA#31688] opened 2019-06-21 06:06 UTC
# Describe the bug

Crash when looking at mp3 player with ups conversion mod

# Steps To Reproduce

- apply a ups mod to an mp3 player
- drop it on the ground.
- try to pick it up
- game crashes.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4781-gd2cb0ba [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Necromancy [necromancy],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3313182/save.zip)

CRASH LOG FILE: config/crash.log
VERSION: 0.D-4736-g0f5bd17
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x58FB15[cataclysm-tiles.exe+0x18FB15]
    @0x5905E2[cataclysm-tiles.exe+0x1905E2]
    raise+0x21B@0x7FFA7059AE8B[msvcrt.dll+0x2AE8B]
    IMG_LoadWEBP_RW+0xFDCCB@0x10E774B[cataclysm-tiles.exe+0xCE774B]
    IMG_LoadWEBP_RW+0xFDDA7@0x10E7827[cataclysm-tiles.exe+0xCE7827]
    @0x782036[cataclysm-tiles.exe+0x382036]
    @0x793CCA[cataclysm-tiles.exe+0x393CCA]
    @0xBD2FBB[cataclysm-tiles.exe+0x7D2FBB]
    @0xE18612[cataclysm-tiles.exe+0xA18612]
    @0x6AF6A2[cataclysm-tiles.exe+0x2AF6A2]
    @0x6AFCCE[cataclysm-tiles.exe+0x2AFCCE]
    @0x6D1D12[cataclysm-tiles.exe+0x2D1D12]
    @0x6ADF7A[cataclysm-tiles.exe+0x2ADF7A]
    IMG_LoadWEBP_RW+0x55A848@0x15442C8[cataclysm-tiles.exe+0x11442C8]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA72FC7974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFA7310A271[ntdll.dll+0x6A271]

**Comment by Inglonias** [comment] 2019-06-21 12:52
Possible duplicate of #31633

**Comment by Inglonias** [comment] 2019-06-21 15:01
Worth noting this issue includes a save file for easy reproduction, though.

**Closed** 2019-06-24 18:06 UTC
