### ISSUE TITLE
Solar panels work in the dark

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#33768] opened 2019-09-02 18:06 UTC
# Describe the bug

Solar panels work 24/7, rain or shine, indoors or out. 

# Steps To Reproduce

1. Put solar panels on a vehicle
2. Observe rate of charge at night or indoors

# Expected behavior

Solar panels should work 100% in full sun, much lower in cloudy, 0% in dark

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7053-gdfe287e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Bionic Slots [cbm_slots],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Night-Pryanik** [comment] 2019-09-05 19:23
Though the game version here is notably newer, I'd say this is a duplicate of #29443.

**Closed by Night-Pryanik** 2019-09-05 19:23 UTC
Labels: (S1 - Need confirmation), <Bug>, Vehicles
