### ISSUE TITLE
Asthma Rework

### ISSUE THREAD

**Issue by SolarusRex** [CleverRaven/Cataclysm-DDA#45047] opened 2020-10-24 23:07 UTC
# Is your feature request related to a problem? Please describe.
The asthma system is outdated, attacks happen on average 24 times a day, which is insanely frequent as attacks 4 times a day is a cause to see a doctor in the real world.
# Describe the solution you'd like
I would like a greatly reduced chance of asthma attacks so that they fall into real world statistics, and ideally 'triggers' that increase the chance or cause immediate attacks, such as stepping into cold air, exercise, dust, or allergens. I would also like medications that if taken regularly make the chance of asthma attacks without a trigger near zero, these exist in the real world and are quite common.

# Describe alternatives you've considered
Simply reducing the chance by 100x would be good enough

# Additional context
none

**Comment by ZhilkinSerg** [comment] 2020-10-25 07:32
Related: https://github.com/CleverRaven/Cataclysm-DDA/issues/31343

**Comment by I-am-Erk** [comment] 2020-10-26 21:45
I'd say this is a duplicate of #31343 really

**Closed by I-am-Erk** 2020-10-26 21:45 UTC
Labels: <Suggestion / Discussion>
