### ISSUE TITLE
Segmentation Fault/Crash on Dropping Items

### ISSUE THREAD

**Issue by SirLemmington** [CleverRaven/Cataclysm-DDA#36629] opened 2020-01-02 06:58 UTC
Game version: 0.D-10932-g9eb7975 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles, latest Dead People tileset as of December 31st 2019.

Mods active:

  "dda",
  "no_npc_food",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "P_Caches",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "GOV_BANDITS",
  "NM_wpns",
  "SD_Magcrafting",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "craftgp",
  "FIC_Weapons",
  "More_Survival_Tools",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "secronom",
  "alt_map_key",
  "hydroponics",
  "more_survivor_stuff",
  "mutant_npcs",
  "MMA",
  "makeshift",
  "ew_pack",
  "no_olg_guns",
  "no_pipe_guns",
  "No_Fungi",
  "fuji_mpp",
  "safeautodoc",
  "speedydex",
  "StatsThroughSkills"

### Expected behavior
When dropping more than two items, the items should drop without problem and appear on the ground.

### Actual behavior
When dropping more than two items, in this instance three Long Strings, the game immediately crashes.

### Steps to reproduce the behavior
Acquire a stackable item in three or more. Drop it on the ground. The game immediately crashes.

[Twain Harte.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4015074/Twain.Harte.zip)

**Comment by evanilukhin** [comment] 2020-01-02 07:40
Confirm, I've got the same problem

**Game version:** 0.D-10932-g9eb7975 (curses)

**Operating system:** Ubuntu 18.04

**Tiles or curses:** curses

###Mods active:

  "dda",
  "no_npc_food",
  "aftershock",
  "magiclysm",
  "craftgp",
  "FIC_Weapons",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "fast_healing",
  "my_sweet_cataclysm",
  "MMA",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "no_filthy_clothing",
  "no_reviving_zombies",
  "safeautodoc",
  "novitamins",
  "speedydex"

### Expected behavior:

In advanced inventory pressing "M"(move item stack) or "m"(move an amount of item) move all stack or entered amount of items 

### Actual behavior

Move only 2 or 3 items or crash

[Aptakisic.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4015164/Aptakisic.tar.gz)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4015166/crash.log)

**Comment by Zireael07** [comment] 2020-01-02 07:44
duplicate/related to #36554

**Comment by evanilukhin** [comment] 2020-01-02 07:53
Checked only with default mods ["dda",  "no_npc_food"], problem reproduced too

**Comment by ZhilkinSerg** [comment] 2020-01-02 08:09
Duplicate of #36554

**Closed by ZhilkinSerg** 2020-01-02 08:09 UTC
