### ISSUE TITLE
Failed to visit member overlay_ordering in JsonObject

### ISSUE THREAD

**Issue by linonetwo** [CleverRaven/Cataclysm-DDA#46216] opened 2020-12-21 13:53 UTC
# Describe the bug

```
 DEBUG    : (json-error)
Json error: <unknown source file>:4:24: Failed to visit member overlay_ordering in JsonObject

  {
    "type": "overlay_order",
    "overlay_ordering":
                       ^
                        [
      {
        "id": [


 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120
```

```
 DEBUG    : (json-error)
Json error: <unknown source file>:67:21: Failed to visit member compatibility in JsonObject

  {
    "type": "mod_tileset",
    "compatibility":
                    ^
                     [
      "UltimateCataclysm",
      "UltimateCataclysmDemo"


 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120
```

```
 DEBUG    : (json-error)
Json error: <unknown source file>:71:17: Failed to visit member tiles-new in JsonObject

      "UltimateCataclysmDemo"
    ],
    "tiles-new":
                ^
                 [
      {
        "file": "mod_tileset/arcana_expan_ultica_small.png",


 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 120
```

# Steps To Reproduce

1. Try use Ultica gfx
2. Load the save
3. Error when loading gfx

# Expected behavior

Successfully load the tileset

# Versions and configuration
Android and MacOS on latest 11279 experimental

**Comment by linonetwo** [comment] 2020-12-21 13:58
Oh，I know, it is my translated mod forget to delete the file that has been deleted in arcana.

I have to fix my translation script in https://github.com/linonetwo/cdda-arcana-mod-chinese/blob/master/%E7%BF%BB%E8%AF%91.js#L316

**Comment by linonetwo** [comment] 2020-12-21 14:12
But this seem to caused by json loading process in CDDA's cpp

**Comment by anothersimulacrum** [comment] 2020-12-21 15:42
Where's the save?

**Comment by BrettDong** [comment] 2020-12-21 16:04
Cannot reproduce on my save. Can you upload your save file?

**Comment by linonetwo** [comment] 2020-12-22 02:20
Confirm fixed after https://github.com/CleverRaven/Cataclysm-DDA/issues/46166

**Comment by Kenan2000** [comment] 2020-12-22 05:04
> Seems fixed after #46166 , sorry...
@linonetwo 
It's actually not fixed entirely, the `compatibility` error has been fixed in majority of mods, indeed, thanks to Anothersimulacrum's effort, but on latest experimental I and other players and modders - we are still getting `tiles-new` and `overlay_ordering` bugs for unknown reasons, which is strange

**Comment by Kenan2000** [comment] 2020-12-22 05:17
[TESTING.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5727920/TESTING.zip)

Here is the save file with the aforementioned bug - in this case it's a third party mod - **but it's `mod_tileset.json` format 100% corresponds to the official vanilla format of the `mod_tileset.json`, it simply should not throw any errors** , yet it still throws the same errors for unknown reasons

**Comment by olanti-p** [comment] 2021-06-17 19:24
Possible fix: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/554/commits/65b9ad7c0488839167eb7f2eb1e7aac42c0e062c
It was reported as working after testing in BN.

**Closed** 2021-06-25 00:33 UTC
Labels: (S3 - Duplicate), SDL: Tiles / Sound, [JSON]
