### ISSUE TITLE
Bike Rack(s)

### ISSUE THREAD

**Issue by FaNToMKH** [CleverRaven/Cataclysm-DDA#53066] opened 2021-11-27 17:36 UTC
### Describe the bug

1-tile vehicles carried by bike rack merge to the main carrying vehicle (as the one and same), without means to unload them, other than by removing them from the main vehicle part by part.

### Steps to reproduce

1) have a vehicle with shredders in the  front row of tiles and  with bike racks at the end row of tiles
2) load 3 1-tile vehicles to 3 of those bike racks.
3) drive around,pass over a boulder, stop and try to unload said 1-tile vehicles.

### Expected behavior

I expected to be able to unload-unmount my 1-tile vehicles from the bike rack(s),since there is no damage to any part of said vehicles.

Or carried 1-tile vehicles to brake of the bike racks from the collision. 

### Screenshots

![FaNToM __17-34-16_��������� ��� GTB](https://user-images.githubusercontent.com/65818621/143691194-5d1e2dbe-b260-4c1a-af51-88d0819f9ea8.png)

### Versions and configuration

OS : Windows 7 Professional, Service pack 1
Game Version : Experimental 940c7ae (tiles)
Graphics Version : tiles
Ingame Language : English
Mods Loaded: dda, no npc food, package bionic professions, dinomod, statsthroughskills, stats trough kills,

**Comment by Alex-Folts** [comment] 2021-11-27 18:45
It seems like that 2 one-tile vehicles, which are side by side, just merged together, and game cant detach one from another and from main vehicle at the same time.

**Comment by FaNToMKH** [comment] 2021-11-27 22:03
also happens, when vehicles are loaded and you modify the main vehicle.

**Comment by PatrikLundell** [comment] 2021-11-28 11:23
This is a duplicate of #50215, which is itself a duplicate of older bug reports.
Fusing doesn't happen every time, and seems to happen only when two or more vehicles are loaded, but I wasn't able to figure out a consistent pattern.

My work around is to save before loading more than one vehicle, transport them, and unload at the destination, crashing the game and reverting to the save and make a new attempt (this obviously requires auto save to be disabled).

**Comment by hexagonrecursion** [comment] 2021-12-20 14:19
Please remove (S1 - Need confirmation). Multiple people have opened bugs related to bike rack fusion - there is definitely something broken here.

**Comment by wapcaplet** [comment] 2022-01-16 05:56
Closing as duplicate of #48154, #52005, #50215

**Closed by wapcaplet** 2022-01-16 05:56 UTC
Labels: (S3 - Duplicate), (S2 - Confirmed), Vehicles
