### ISSUE TITLE
SIGSEGV: Segmentation fault

### ISSUE THREAD

**Issue by Vindicatory** [CleverRaven/Cataclysm-DDA#77552] opened 2024-11-03 12:29 UTC
### Describe the bug

A game is crashing when I trying to smoke a joint or press E (consume).

crash log attached.

### Attach save file

[Най-trimmed.tar.gz](https://github.com/user-attachments/files/17610386/-trimmed.tar.gz)

### Steps to reproduce

1. Launch 2024-11-03-0844 and load saved game.
2. Press E and get crash | Or press a (activate) and try to smoke joint (anything else works fine)

### Expected behavior

Game don't crash

### Versions and configuration

- OS: Windows 10
- Game Version: 9f98a02
- Graphic version: tiles
- Ingame language: Russian
- Mods installed: StatsThroughSkills

### Additional context

[crash.log](https://github.com/user-attachments/files/17610399/crash.log)
[debug.log](https://github.com/user-attachments/files/17610400/debug.log)

**Comment by Night-Pryanik** [comment] 2024-11-03 14:05
I guess this is duplicate of #77500.

**Closed by Night-Pryanik** 2024-11-03 14:05 UTC
Labels: (S1 - Need confirmation)
