### ISSUE TITLE
Let the player use ESC key to close NPC dialogs

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38204] opened 2020-02-21 15:40 UTC
# Is your feature request related to a problem? Please describe.
Just a QoL suggestion. It would be nice to being able to use the ESC key to close the NPC dialog menu, like other menus in the game.

# Describe the solution you'd like
Being able to use ESC key to close NPC dialogs.

# Describe alternatives you've considered
Keep using strict key-coded choices.

# Additional context
I understand if this is difficult to implement, since players shouldn't be able to close some dialogs, or not wanting players to accidentally close a dialog, but it would be such a nice QoL addition since most players have muscle memorized ESC as a way to close menus in-game.

**Comment by Ramza13** [comment] 2020-02-21 16:11
This is a duplicate of #31185

**Closed** 2020-02-22 07:05 UTC
