### ISSUE TITLE
Error on opening diary

### ISSUE THREAD

**Issue by terribleperson** [CleverRaven/Cataclysm-DDA#78767] opened 2024-12-25 18:54 UTC
### Describe the bug

Opening the diary throws the error 'invalid monster type id "mon_zpider_mass".

### Attach save file

[Sangerville-trimmed.tar.gz](https://github.com/user-attachments/files/18246954/Sangerville-trimmed.tar.gz)

### Steps to reproduce

1. Have a save from before #78370 with a mass of zombie spiders in the diary.
2. Update to a version after the removal of zombie spiders.
3. Open the diary.

### Expected behavior

I would expect the problematic monster entry to not throw an error. Zombie spiders are present in 0.H, so this will eventually be relevant, though it's not a huge issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: 0f016e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by RenechCDDA** [comment] 2024-12-26 01:09
Duplicate of #77393

**Closed by RenechCDDA** 2024-12-26 01:09 UTC
Labels: (S1 - Need confirmation)
