### ISSUE TITLE
Disassembling menu display error

### ISSUE THREAD

**Issue by Solomonome** [CleverRaven/Cataclysm-DDA#28547] opened 2019-03-08 05:20 UTC
**Describe the bug:**  
I wanted to disassemble an item, and when I opened the disassembling menu, the turban on my head caught my eye :smile:

![turban](https://user-images.githubusercontent.com/47925487/54008955-33539d00-4169-11e9-9daf-7e14b4414423.png)
I'm not sure about the other items right now.

**To Reproduce:**  
1. Wish for a turban
2. Wear it
3. Open the disassembling menu

**Expected behavior:**  
It should display 8 rags in the "YIELD" section.

**Versions and configuration:**
 - OS: GNU/Linux
 - Game Version: 0.C linux64 build 8555
 - Graphics version: tiles
 - Mods loaded: default

**Comment by anothersimulacrum** [comment] 2019-03-08 05:36
duplicate of #28046

**Closed** 2019-03-08 05:37 UTC
Labels: Crafting / Construction / Recipes, Info / User Interface
