### ISSUE TITLE
Sewing kit and wooden needle cant be reloaded and when emptied produce none item

### ISSUE THREAD

**Issue by LordNil1** [CleverRaven/Cataclysm-DDA#40519] opened 2020-05-13 10:40 UTC
Bug

As said sewing kit nad needle cant be reloaded and when emptied produce none item.

# Steps To Reproduce

Have sewing kit or needle and try reloading them or unloading them.Reloading eats thread without change in charges and unloading produce none item.

# Expected behavior

Thread shoudl be reloaded and unloaded correctly

# Versions and configuration
windows 10
vanilla version 10659
have seen this issue for some time,but i cant see m to find it has been reported.If it was pls delete.

**Comment by ZhilkinSerg** [comment] 2020-05-13 10:56
Duplicate of #40125

**Closed by ZhilkinSerg** 2020-05-13 10:56 UTC
