### ISSUE TITLE
Random Crash when looking at my guns

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#41296] opened 2020-06-14 02:32 UTC
# Describe the bug

There is a Segfault crash when examining my stash of guns

# Steps To Reproduce

Press any combination of keys while next to the locker with guns. You will be right next to them when spawning in.

# Expected behavior

I should be able to access my guns

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3198-g4b34eda [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4775781/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4775782/crash.log)
[Grove City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4775783/Grove.City.zip)

**Comment by anothersimulacrum** [comment] 2020-06-15 01:00
Duplicate of #41080

**Closed by anothersimulacrum** 2020-06-15 01:00 UTC
Labels: (S3 - Duplicate)
