### ISSUE TITLE
monster flag: MECH_DEFENSIVE may bugged

### ISSUE THREAD

**Issue by adorableNYNICG** [CleverRaven/Cataclysm-DDA#44831] opened 2020-10-13 10:10 UTC
# Describe the bug
According to json_flags.md, monsters with MECH_DEFENSIVE flag can protect its rider from any attack.
But in gameplay monster with that flag protects its rider only from ranged attack. Rider can easily hurt from melee attack.
Could it be intended?

# Steps To Reproduce
1.Add MECH_DEFENSIVE flag to mechsuits.(by MOD)
2.Start game, aquire military ID card, spawn monster mech(with MECH_DEFENSIVE flag), ride on it using ID card, spawn hostile mob that only deals simple melee attack, watch the player attacked by mobs while riding on mech.

# Expected behavior
With MECH_DEFENSIVE flag, monster mech can protect player from melee attack. Player won't take any damage.

# Screenshots
1.Mech protecting its rider from bullet. (for comparison)

![スクリーンショット 2020-10-13 16 36 58](https://user-images.githubusercontent.com/72785325/95836620-a1ffd000-0d7a-11eb-89bd-3db18be34b3e.png)
This is me: riding on X-02 combat mech(MECH_DEFENSIVE added), facing with monster turret equipped with MP5.

![スクリーンショット 2020-10-13 16 38 12](https://user-images.githubusercontent.com/72785325/95837353-7b8e6480-0d7b-11eb-9439-36dd6dd3f298.png)
...after 5 minutes: i'm still healthy, not injured. all bullets from turret has been deflected by mech armor.
MECH_DEFENSIVE flag works properly for ranged attack.

2.Player getting hurt by monster's melee attack.

![スクリーンショット 2020-10-13 16 39 28](https://user-images.githubusercontent.com/72785325/95840147-c3fb5180-0d7e-11eb-8a49-b0a253968689.png)
This is me: riding on X-02 combat mech(MECH_DEFENSIVE added), surrounded by 8 zombie soldier.

![スクリーンショット 2020-10-13 16 41 01](https://user-images.githubusercontent.com/72785325/95841240-14bf7a00-0d80-11eb-964e-607a7ebaee54.png)
...after 10 seconds: i'm injured. zombies attacked me many times. so painful...

![スクリーンショット 2020-10-13 16 41 47](https://user-images.githubusercontent.com/72785325/95842043-0a51b000-0d81-11eb-8475-aa892713f337.png)
...additional waiting of 5 minutes: now i'm buried in grave...

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G95; 
- Game Version: 0.E-6779-gc3caa74 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en] <<this is for game report. acutual gameplay is in japanese.
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    wander with mountable [WWM] <<this is my MOD: add MECH_DEFENSIVE to mech, add use_action to mech weapon so they can perform multiple attack, add my original monster mech.
]

# Additional context
none

**Comment by ZhilkinSerg** [comment] 2020-10-13 15:53
Melee attack:
https://github.com/CleverRaven/Cataclysm-DDA/blob/181c57ffa20ecdfe2a8cad40a579cf54b5d82384/src/creature.cpp#L529-L540

Projectile attack:
https://github.com/CleverRaven/Cataclysm-DDA/blob/181c57ffa20ecdfe2a8cad40a579cf54b5d82384/src/creature.cpp#L597-L607

**Comment by adorableNYNICG** [comment] 2020-10-19 09:48
First, it's just my opinion and i'm not coder. I don't have any proper C++ knowledge. So, it may completely pointless...

I think these codes doesn't have anything wrong.
Because it says there is no chance the enemy's attack hit rider(player) if the monster(mech) has MECH_DEFENSIVE flag. The problem is, enemy's attack somehow target rider first where it should target mounts first.

I'm not sure whether it is possible(and correct solution) or not, but i think MECH_DEFENSIVE flag can work properly by adding code that contains these capability to functon "creature::deal_melee_hit" ...
1. Check player's status effect to determine wheter he/she is riding on monster(mount).
2. If player is riding on monster, search for MECH_DEFENSIVE flag in the monster's definition.
3. If the monster has MECH_DEFENSIVE flag, execute function "creature::deal_melee_hit" on monster. (like in Cataclysm-DDA/src/creature.cpp line 536)

By this, even if enemy's attack accidentally targeted at player first, game can check monster(mount)'s flag and if it has MECH_DEFNSIVE flag, make enemy's attack to target at mount instead of player......probably...maybe...

**Comment by wapcaplet** [comment] 2020-11-02 22:59
Confirmed in 0.E-7278-g18d62ad2c7. This is a new 0-skill character in an X-02 suit, being attacked by 1 normal zombie. The zombie alternately attacks the suit, and my character:

![image](https://user-images.githubusercontent.com/238395/97928375-257e6280-1d24-11eb-95a0-b899c13fd1a5.png)

The quoted sections of `src/creature.cpp` are not reached and executed at all - those only appear to apply when a creature that is *being ridden* is attacked. I would need to dig further to see where the attacks are taking place - wherever it is, there is no check for `MECH_DEFENSIVE`.

**Comment by Night-Pryanik** [comment] 2022-02-15 18:56
I think the culprit is in monster's eagerness to attack player rather than any other monster.

Act 1: zombie soldier is attacking my mecha
![изображение](https://user-images.githubusercontent.com/11132525/154128245-8e3db36a-d433-42eb-a2de-0e68456d79a8.png)

Act 2: I'm walking south-east
![изображение](https://user-images.githubusercontent.com/11132525/154128376-5d031538-ee9b-46b7-8949-9372261bcf40.png)

Act 3: zombie soldier immediately switches to attack me
![изображение](https://user-images.githubusercontent.com/11132525/154128536-db1c9c24-f5c7-41d9-8bc6-9ab0baa69d9f.png)

So even if I'm sitting in the mecha, monsters trying to _melee_ attack me and not my mecha.

But this is still strange as monster's attack target is still mecha. I added  this code to `Creature::deal_melee_hit`:
```
auto target = source->as_monster()->attack_target()->disp_name();
popup( "target is %s", target );
```
And the in-game result when I'm sitting in my mecha is
![изображение](https://user-images.githubusercontent.com/11132525/154129454-7efd9b5e-0198-429b-b651-0722458790c2.png)

**Comment by LeahLuong** [comment] 2022-02-15 22:54
Why is that 1 dude headstanding??

**Comment by Night-Pryanik** [comment] 2022-02-16 06:37
I don't know. All creatures in my self-compiled version are turning upside down when moving _left_. Moving to the right is ok. So far no one was able to explain that.

**Comment by ZhilkinSerg** [comment] 2022-02-16 06:40
That's the renderer thing - some of them don't have the problem.

**Comment by Night-Pryanik** [comment] 2022-09-01 13:19
Working as intended.

**Closed by Night-Pryanik** 2022-09-01 13:19 UTC
Labels: <Bug>, (S2 - Confirmed), Melee, Ranged
