### ISSUE TITLE
Issue with unlit door frame in ChestHole tileset

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#21941] opened 2017-09-20 17:52 UTC
Game version:
0.C-23961-ge6cbb86 (tiles)

Operating system:
Win10

Mods active:
none

Unlit doorframes are rendered as black tiles in the "ChestHole" texture pack:

![cataclysm_ dark days ahead - 0 c-24990-gc805a7e 16 11 2017 15_01_27](https://user-images.githubusercontent.com/11627131/32895138-5d58d338-cadf-11e7-8ef7-9fcb7a3ac2bc.png)
![cataclysm_ dark days ahead - 0 c-24990-gc805a7e 16 11 2017 15_01_49](https://user-images.githubusercontent.com/11627131/32895139-5d76361c-cadf-11e7-9e06-95eaaef9f68d.png)
![cataclysm_ dark days ahead - 0 c-24990-gc805a7e 16 11 2017 15_02_09](https://user-images.githubusercontent.com/11627131/32895166-702939b2-cadf-11e7-91c5-5e8f19731f99.png)

**Comment by rm-code** [comment] 2017-09-20 18:46
Found another garage with the same issue (that particular door frame is unlit).

**Comment by Leland** [comment] 2017-09-20 21:32
Perhaps duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/13786

**Comment by rm-code** [comment] 2017-09-20 23:51
@Leland I'm not using night vision. This seems to be something odd with the garage template itself as far as I can tell.

**Comment by angoddu** [comment] 2017-09-21 01:09
I have this issue with all door frames

**Comment by rm-code** [comment] 2017-10-06 07:00
@angoddu Might be a different issue since for me it only occurs in the garage

**Comment by rm-code** [comment] 2017-11-16 14:04
This seems to be an issue with the "ChestHole" texture pack only:

![cataclysm_ dark days ahead - 0 c-24990-gc805a7e 16 11 2017 15_01_27](https://user-images.githubusercontent.com/11627131/32895138-5d58d338-cadf-11e7-8ef7-9fcb7a3ac2bc.png)
![cataclysm_ dark days ahead - 0 c-24990-gc805a7e 16 11 2017 15_01_49](https://user-images.githubusercontent.com/11627131/32895139-5d76361c-cadf-11e7-9e06-95eaaef9f68d.png)
![Uploading Cataclysm_ Dark Days Ahead - 0.C-24990-gc805a7e 16.11.2017 15_02_09.png…]()

**Comment by AMurkin** [comment] 2017-11-16 15:46
![image](https://user-images.githubusercontent.com/1931904/32900391-6721bdd4-cafe-11e7-9acf-06cd54046d58.png)
It's just black pixels.

**Comment by Leland** [comment] 2017-11-16 15:48
Nice find. Pinging @Chezzo ^

**Comment by ZenZen2** [comment] 2018-03-15 09:34
With #23203 the frame bug is back.
```
t_door_frame
t_mdoor_frame
t_rdoor_o
```
Those 3 are pointing to the black tile.

**Comment by ZhilkinSerg** [comment] 2018-03-15 10:06
Pinging @Chezzo once again

**Closed** 2018-03-16 06:34 UTC
Labels: Information / Interface, Tiles
