### ISSUE TITLE
Pneumatic bolt driver reload time too short-Bug

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#32720] opened 2019-07-29 04:59 UTC
# Describe the bug
Reload time for pneumataic bolt driver is abotu 10-11 sec while tooltip says 59sec

# Steps To Reproduce

1. Make pnuematic bolt driver
2. Reload it.

# Expected behavior
Reload time shoud match toottip

# Screenshots
befroe reload
http://prntscr.com/olb6mw

after reload
http://prntscr.com/olb6w2

**Comment by brannamm** [comment] 2019-07-29 05:36
Seems to be duplicate of #32403

**Comment by kasanryukin** [comment] 2019-07-29 09:02
> Seems to be duplicate of #32403

It is indeed, but a layman might not understand that.  Reload time is correct (10 seconds), so it's just a case of fixing the code.

**Comment by kevingranade** [comment] 2019-07-29 16:42
Reload time is not correct, this should be about a minute per round.
See https://discourse.cataclysmdda.org/t/balance-pneumatic-weapons/14488/35?u=kevin.granade for rationale.

**Comment by kasanryukin** [comment] 2019-07-29 19:37
Oh I didn't even consider the pneumatic side of the helsing.  I assumed it had a built it pump similar to how the one in Metro did.  If that were the case, reload speed would be affected by the diameter and length of the pump piston.

Wonder if I could design a speed loader that has bolts and an air tank pre-pressurized and just needing to be screwed into the assembly.  Trade weight and volume in the backpack to get the reloading of the actual bolt driver down to 10-15 seconds, and keep the speed loaders with a high reload time.

**Comment by Petethegoat** [comment] 2019-07-29 19:47
@kasanryukin I like that idea a lot. Being able to make the trade-off between reload time and portability is a fun choice to make.

**Closed** 2019-08-13 19:59 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
