### ISSUE TITLE
Broke both legs, one mended, speed at full.

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11116] opened 2015-02-04 00:38 UTC
Broke both legs, one mended, speed went to full. Seems like it should stay down, or be at half possible penalty. Also, one leg brace covers both legs, but that's just the clothing system.

**Comment by drbig** [comment] 2015-03-18 13:01
Leg splints cover both legs, so both should mend at the same time... or rather: are you sure you had one leg at 0 HP and the other at more than 40% of it's maximum health?

From what I've read in the code (`player::run_cost`) movement penalties are indeed applied on per-leg basis, so maybe you getting full speed was due to a combination of factors (any traits like parkour expert, fleet-footed etc.). Or maybe the 'speed' is a completely different thing?

**Comment by Headjack** [comment] 2015-03-28 23:49
I'm gonna try to remember here... I'm sure both the legs HP bars were totally out, and I know one came back before the other, so I don't think they healed at the same rate. Maybe there are separate checks for either leg for if the splint helps? I probably did have parkour expert, but that shouldn't've affected my movement speed. I'm talking about the 'speed points' that let you take actions, which are debuffed with a broken leg.

**Comment by KA101** [comment] 2015-03-30 01:06
>Maybe there are separate checks for either leg for if the splint helps?

Yep, pretty sure it's checked separately for each.  Doesn't answer the underlying problem--perhaps the speed debuff is still tracking Legs as one unit rather than Leg L and Leg R separately.  IIRC we had an issue with missing some of those right as we bifurcated the limb-tracking.

**Comment by illi-kun** [comment] 2016-04-24 12:26
Closing as a duplicate of #1941.

**Closed by illi-kun** 2016-04-24 12:26 UTC
Labels: Balance, Bug
