### ISSUE TITLE
Backpacker's start wearing a blazer

### ISSUE THREAD

**Issue by ThePinkPanzer** [CleverRaven/Cataclysm-DDA#19421] opened 2016-11-23 07:12 UTC
Seems pretty odd some sort of experienced backpacker in the wilderness is rocking a blazer and cargo shorts of all things. Should probably be changed to a jacket (or nothing) since he also has a t-shirt.

**Comment by tswood** [comment] 2016-11-23 13:35
Just created a new character with the backpack profession and did not start with a blazer. Checked the professions.json as well and it isn't listed there either.

What version are you using, and also what mods if any?

**Comment by DangerNoodle** [comment] 2016-11-23 16:37
I thought a blazer was made of wool. Did you select Wool Allergy?

**Comment by ThePinkPanzer** [comment] 2016-11-23 16:54
Odd. I am running the latest update with whatever mods it drops on you as default, I'm too new to have messed with anything, but I've had two characters over two worlds start with the blazer as a backpacker. Both in the wilderness start and in the bunker start.

**Comment by Leland** [comment] 2017-01-23 21:36
Couldn't reproduce at all. Tried multiple starts both in the wilderness and as an evacuee.

However, there _are_ some professions that start with cargo shorts, a t-shirt and a blazer as described. I have a feeling that @ThePinkPanzer meant one of these three:

* Survivalist (most likely)
* Bionic Prepper
* Bionic Survivalist

**Comment by Leland** [comment] 2017-02-10 18:47
Fixed with #20100

**Comment by Leland** [comment] 2017-02-13 22:51
#20100 addressed this, can be closed.

**Comment by Night-Pryanik** [comment] 2017-03-30 06:04
Should be closed.

**Closed** 2017-03-30 16:34 UTC
Labels: Confirmation Needed, Easy-fix, Suggestion (Discuss)
