### ISSUE TITLE
infinite hydrogen

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11200] opened 2015-02-10 23:48 UTC
if you build a hydrogen tank into a car, fill it up, then remove the tank and take the hydrogen out of the metal tank, you get thousands of hydrogen instead of the 25 you start with.

this can be repeated infinitely

**Comment by Midaychi** [comment] 2015-02-11 03:42
It probably has something to do with assumptions made in the code RE: the difference in how much a unit is.  You can put more units of alcohol or gasoline in a plastic bottle than you can water, etc.

**Comment by KA101** [comment] 2015-02-11 03:57
Almost certainly, Midaychi.  We just had a fix for something similar re gasoline last week or so.

**Comment by Griffinhart** [comment] 2015-02-17 21:31
Duplicate of #8206, which was dismissed as essentially "not an issue".

**Comment by KA101** [comment] 2015-02-17 22:38
There, be happy.

**Closed by KA101** 2015-02-17 22:38 UTC
Labels: Duplicate
