### ISSUE TITLE
Crafting algorithm should not select suboptimal components with no option to cancel

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#69893] opened 2023-12-01 05:30 UTC
### Describe the bug

When crafting a metal charcoal kiln, I had

- 4 pipes in inventory
- 4 60L metal tanks two tiles away
- 2 60L metal tanks filled with clean water 6 tiles away

The crafting process (which requires 4 tanks) auto-selected two tanks from one pile and both from another, prompting for disposal of the water. Since I was not adjacent to the empty tanks, and canceling was not an option, I could not do anything but waste the water.

This is bad. It is unclear if it it's a bug or lack of feature though.  Bug report was recommended.

### Attach save file

N/A

Edit: 
[DinoMind-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13521373/DinoMind-trimmed.tar.gz)

### Steps to reproduce

without attached save:
Assemble ingredients to craft a metal charcoal kiln. Fill two component tanks with water in addition, and leave them further away from the intended component base.  Craft. Do so multuple times to assess consistency. 

with attached save:
1.  load game
2. continue to stand next to the construction save directly east of character (south of smoker)
3. hit `shift-O` for zone actions
4. select "construct plots"
5. immediately be prompted to empty water.

### Expected behavior

The craft should either allow canceling at prompt, specify component selection in more cases, or at least do a better job of selecting components on its own. 

### Versions and configuration

- OS: Windows
     - OS Version: 7 SP1
Game Version: [d12347d](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-11-29-0635) [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded:
     - Dark Days Ahead [dda],
     - Disable NPC Needs [no_npc_food],
     - Portal Storms Ignore NPCs [personal_portal_storms],
     - Bionic Professions [package_bionic_professions],
     - Alternative Map Key [alt_map_key],
     - Extra Mutated Scenarios [extra_mut_scens],
     - Blaze Industries [blazeindustries],
     - Mind Over Matter [mindovermatter],
     - Bombastic Perks [bombastic_perks],
     - DinoMod [DinoMod]

### Additional context

modified save and secondary list of reproduction steps edited in by esotericist, with permission from montimorency.

additional version info for reproduction:
- OS: MacOs
    - OS Version: Name: macOS; Version: 14.1; Build: 23B74; 
- Game Version: 0.G-5541-gd1c72bc17c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    DinoMod [DinoMod]
]

**Comment by Montimorency** [comment] 2023-12-01 05:36
Editing in the save didn't seem to work, so here it is. 

[DinoMind-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13521133/DinoMind-trimmed.tar.gz)

**Comment by esotericist** [comment] 2023-12-01 06:05
confirmed locally. getting better reproduction data together.

**Comment by esotericist** [comment] 2023-12-01 06:19
edited initial issue posting with modified save and instructions. this is a pretty gross UX trap imo.

**Comment by esotericist** [comment] 2023-12-01 07:47
> Related to #69504.

that's interesting, but i don't know for sure if it's genuinely related or not (construction is to my occasional dismay frequently using different logic for grabbing objects from recipe crafting).

(also i'm not going to attempt to reproduce that one without a save file with a test rig in place, time and energy are limited)

**Comment by PatrikLundell** [comment] 2023-12-01 10:33
As far as I know companion crafting uses the same code as PC crafting, and that report was for ordering a companion to craft, not base craft bulletin board crafting. The only difference from the situation in this report (apart from a convenient save) is that it was containers using non liquids being grabbed rather than containers containing liquids, so there was no warning about the containers in use being consumed (their content was just showing up dropped on the floor, as non liquids would not require the contents to be moved elsewhere).

Thus, fixing this report should most probably fix #69504 as well, and I still think it's caused by the usage of several iterations over possible components which probably don't use the same criteria (the tallying step probably just tally up everything encountered, keeping track of if sufficient unused containers were available, while the consumption step probably grabs the first items matching the selection description without bothering with whether they're used or not (and without knowing whether there are supposed to be a sufficient number of unused items available, or whether the order went ahead with the knowledge that at least some of them would have to be emptied).

I don't have a problem with investigators skipping investigation of reports without saves (and I can't provide saves, as the compression produces saves that are too large even after an attempt to deal with it was merged, 36 MB just now, although that save compression was just a test to verify that it's still too large).

**Comment by RenechCDDA** [comment] 2023-12-13 17:46
This should be *relatively* simple to resolve by comparing each set of valid components and querying contents, preferring those with no contents or at least fewer. (This is also how it used to work AFAIK, so this might be a regression)

A perhaps simpler and dirtier check is to simply compare the items' weight and pick the ones with the lowest... since items containing other items will have an increased weight! This also avoids the relatively expensive pocket checks.

**Comment by PatrikLundell** [comment] 2023-12-23 14:38
Failed to understand the replication descriptions.
- Continue to stand? east when the smoker is to the SW?
- Construct plots in zone manager doesn't make sense for crafting (and I find no plot zones anyway).
- I find no pipes in the inventory, nor any full tanks.

**Comment by GuardianDll** [comment] 2023-12-25 20:11
just tested it in this way: spawned 4 tanks, fill two of them with water, put on a small distance, and spawned the rest of a tools and ingredients
tried to construct metal charcoal kiln, the game asked me what to do with drum, full of water, i pressed escape, (expecting crafting to be interrupted so i can search where to put my water from tanks), but instead the game continued the recipe, evaporizing my water

**Comment by PatrikLundell** [comment] 2023-12-26 07:47
This is the construction case, which hasn't been touched by the recent modifications to the crafting and base camp crafting cases.
I did indeed manage to spawn materials and repeat the issue:
- Spawn 6 60 L tanks
- Spawn 4(?) pipes
- Spawn 2 bottles of clean water
- "Re"fill two tanks with water from the bottles
- Move 2 empty tanks and one tank with water one tile to the left.
- Use the construction menu to order the construction of the metal charcoal kiln.
- See that you're ordered to deal with water content despite having a sufficient number of empty tanks. At that stage you're screwed, since <ESC> means dump on the ground, not back out.

I did that on my own save as I see no point in using the supplied save that doesn't have the materials prepared anyway.
Also, the game crashed when I tried to wield something (I had intended to carry two tanks to fill them at my pump), and after a second crash (CTD) I gave up on that approach. Cannot write report with save as my compressed saves are too big.

Also tried the different case @GuardianDll mentioned, i.e. 4 tanks, where at least one of them contains something (water). This is a different case as it isn't possible to make the construction without consuming the tank(s) containing stuff. In this case the game warns you (assuming you've figured out the code) that you cannot make the construction without consuming at least one tank containing stuff by coloring the "4 metal tanks (60L) (have 4)" line magenta.
One could desire the game to prompt the player to confirm the usage of containers containing stuff before proceeding after the selection stage as an enhancement of the feedback (which would be at a point at which you can still back out).

**Closed** 2023-12-28 22:30 UTC
Labels: <Bug>, Info / User Interface, (S2 - Confirmed), Crafting / Construction / Recipes
