### ISSUE TITLE
Overmap specials cannot be placed on levels other than the ground level [overmap editor]

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14344] opened 2015-12-08 07:52 UTC
open the map editor. move your view down one layer. use the mapgen function to apply some mapgen underground. exit the mapgen function. move your view up one layer. you will see that the map you applied went on the original layer, not the one you were looking at.

**Comment by Coolthulhu** [comment] 2015-12-08 07:54
This could be hard to fix before 3D mapgen update, marking as long term.

**Comment by sparr** [comment] 2015-12-08 07:58
I suspect the immediate fix isn't too complicated. 2D mapgens already get successfully applied to different Z levels for basements and such. I think the problem here is that the debug map editor doesn't handle Z levels correctly in general.

**Comment by Coolthulhu** [comment] 2015-12-08 08:06
I forgot about the whole map load trick.

**Comment by codemime** [comment] 2018-02-24 10:39
The issue is a bit different nowadays. Specials are placed normally, but previews for them aren't shown on levels other than the ground level.

**Comment by Night-Pryanik** [comment] 2019-09-27 15:33
Cannot confirm on latest experimental as of September 27, 2019. I was able to successfully create new overmap special on -1 z-level. It seems like #33619 fixed the issue.

**Closed by Night-Pryanik** 2019-09-27 15:33 UTC
Labels: <Bug>, Mapgen, Z-levels
