### ISSUE TITLE
Menu UI problems

### ISSUE THREAD

**Issue by TemplarPraisingTheSun** [CleverRaven/Cataclysm-DDA#75880] opened 2024-08-22 14:22 UTC
### Describe the bug

When butchering, you cannot see the entire menu and some writings doesnt fits inside like when checking the proficiency to be gained via dissecting. Also when using debug menu and going in add an affect option, the left side of the menu is partially cutted off.

### Attach save file

N/A

### Steps to reproduce

Looking through the butchering menu and trying to dissect something with a lot of proficiency it can grant and going in the debug menu and the add an effect option.

### Expected behavior

Things to fit in their window

### Versions and configuration

Pre release

**Comment by ZhilkinSerg** [comment] 2024-08-22 14:50
Duplicate of #75765

**Closed by ZhilkinSerg** 2024-08-22 14:50 UTC
Labels: (S1 - Need confirmation)
