### ISSUE TITLE
Incompatible mutations and bionics can be acquired / installed for the same character

### ISSUE THREAD

**Issue by paulenka-aleh** [CleverRaven/Cataclysm-DDA#27663] opened 2019-01-16 13:25 UTC
**Is your feature request related to a problem? Please describe.**  
Incompatible mutations and bionics can be acquired / installed for the same character.

Some combinations make characters realistically impossible which breaks immersion, in addition some combinations make characters overpowered making the rest of the game not challenging including even end-game locations.

**Describe the solution you'd like**
- Audodoc should have higher chances to mess up the installation or even refuse to install if it cannot recognize human organs, e.g. would one be able to configure autodoc embed Terranian Sonar into your Leg Tentacles? How would autodoc cut through your Roomy Shell to install Internal Storage and, moreover, how will you access it?
- Some bionics should break as soon as mutation is acquired in a similar way clothes is pushed off / destroyed, e.g. how reasonably Titanium Skeletal Bracing could continue working inside your Pseudolimbs? Wouldn't Reptilian Healing try to grow back your new Fusion Blaster Arm?
- Some bionics can't or might have no reason to break when mutation is acquired, e.g. getting Bulging Eyes behind your Protective Lenses must be extremely painful and harmful for your vision and Expanded Digestive System is likely  only to mess you up if you're Eater Of The Dead with Hyper-Metabolism.
- Some bionics should refuse to activate due to mutations, e.g. will Blood Filter filter out all the acid from your Acid Blood or will acid burn it? I suppose Repair Nanobots know how to fix your Bark? Will Cloaking System hide you despite Feathers (though I already wonder how it works with clothes)?
- In rare cases when bionic material replaces your body you shouldn't be capable of acquiring mutations on that body part or they should behave differently, e.g. would Telescopic Eyes be capable of mutating further without making your vision only worse? If you replaced your flesh with Kinetic Shock Absorbers and Alloy plating, will it mutate to be Toxic Flesh?
- The list can go on...

Why do I think so?
- **Realism**: as explained above, most of these combinations aren't just realistic;
- **Balance**: currently you don't have to chose between mutations and bionics except for a couple of cases when bionics and mutations can give similar pros;
- **Fun**: in time you're ready to both get and install bionics in bulk and mutate approximately as you want you're already approaching end-game. By installing everything and getting every mutation you want you can get ridiculously overpowered in some areas which makes further gameplay just boring. On the other hand risk of mutating with bionics installed, need to choose your bionics and mutagens more carefully and being not that ridiculously overpowered can keep the game challenging longer.

**Describe alternatives you've considered**
Find fantastically convenient explanations how one could configure autodoc to install bionics into slimes and plants, how bionics where designed in labs to work on mutated bodies and how blob modifies your body during mutations to keep bionics useful to max out your survival.

**Additional context**
I agree that should fix ever be done it should be carefully balanced and probably even put in a mod for a while.
It is also worth mentioning #26982 where this issue was discussed a bit.

**Comment by kevingranade** [comment] 2019-01-17 00:58
Minor correction, this is a feature request not a bug.

**Comment by paulenka-aleh** [comment] 2019-01-17 08:45
Thanks @kevingranade, and sorry. Wasn't sure in which form it's better to submit it.
I edited the description, now it looks like a feature request,

**Comment by Amoebka** [comment] 2019-01-21 12:54
Mutations already feel strictly inferior to bionics (incompatible with fancy armors, random unless going past threshold with every mutation, actually have drawbacks). If you make the two systems incompatible, mutations will become completely outclassed and useless. Personally, I would say bionics need to be powered down quite a bit and made easier to install to make them more in-line with mutations (allowing them to become incompatible but competitive options), but that might be a different discussion alltogether.

**Comment by paulenka-aleh** [comment] 2019-01-21 18:14
Thanks for pointing it out @Amoebka. Work on balancing bionics seem to be in progress: you can no longer install them manually, some bionics are no longer cratfable, some of them were completely removed (both intentionally and probanly unintentionally), some received nerfs. Once bionic slot system is out bionics will receive one more huge nerf to entire system. There were already discussions for further nerfs, e.g. like faults on bionics. #26982 suggests very good ideas too.

What I proposed above doesn't seem to be easy to implement. Hence I don't suppose to see it in game earlier than bionic slots. But it's a huge item which wont take one day to resolve. Hence reporting it now.

**Comment by kevingranade** [comment] 2019-08-09 00:49
Closing as this is a grab-bag of somewhat related ideas, if someone wants to follow up on specific ones that's great, but this isn't a space for brainstorming.

**Closed by kevingranade** 2019-08-09 00:49 UTC
Labels: (S4 - Invalid), <Enhancement / Feature>, <Suggestion / Discussion>, Game: Balance, Game: Mechanics Change, Mutations / Traits / Professions
