### ISSUE TITLE
Error/Crash when using bandages

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#76166] opened 2024-09-03 12:15 UTC
### Describe the bug

Games crashes when trying to apply bandage.

### Attach save file

[Mount Baldy-trimmed.tar.gz](https://github.com/user-attachments/files/16848398/Mount.Baldy-trimmed.tar.gz)

### Steps to reproduce

Apply bandage to wound with Shift + e.

### Expected behavior

No crashes.

### Screenshots

![image](https://github.com/user-attachments/assets/a09984ef-fbd3-4f54-a824-b206b322ed87)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4037 (23H2)
- Game Version: c17fa69 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks],
    <color_light_green>Wing Mirror Durability</color> [DEM_MIRROR_DURABILITY]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: C:/Users/User/Downloads/dda/userdata/config/crash.log
VERSION: c17fa69
TYPE: class std::bad_optional_access
MESSAGE: Bad optional access
STACK TRACE:

  #0
    (dbghelp: debug_write_backtrace+0xb5@0,000,7FF,6F3,BCF,BB5[cataclysm-tiles.exe+0x54f,bb5]), 
  #1
    (dbghelp: log_crash+0x36d@0,000,7FF,6F3,B92,0AD[cataclysm-tiles.exe+0x512,0ad]), 
  #2
    (dbghelp: `crash_terminate_handler'::`1'::catch$5+0x43@0,000,7FF,6F5,421,633[cataclysm-tiles.exe+0x1,da1,633]), 
  #3
    (dbghelp: CallSettingFrame_LookupContinuationIndex+0x20@0,000,7FF,6F5,25C,670[cataclysm-tiles.exe+0x1,bdc,670]), 
  #4
    (dbghelp: __FrameHandler4::CxxCallCatchBlock+0x115@0,000,7FF,6F5,25B,575[cataclysm-tiles.exe+0x1,bdb,575]), 
  #5
    (dbghelp: RtlCaptureContext2+0x4a6@0,000,7FF,A72,BF4,896[ntdll.dll+0xa4,896]), 
  #6
    (dbghelp: crash_terminate_handler+0x44@0,000,7FF,6F3,B91,C54[cataclysm-tiles.exe+0x511,c54]), 
  #7
    (dbghelp: terminate+0x22@0,000,7FF,6F5,27B,492[cataclysm-tiles.exe+0x1,bfb,492]), 
  #8
    (dbghelp: _scrt_unhandled_exception_filter+0x5a@0,000,7FF,6F5,24E,762[cataclysm-tiles.exe+0x1,bce,762]), 
  #9
    (dbghelp: UnhandledExceptionFilter+0x1ec@0,000,7FF,A70,630,BBC[KERNELBASE.dll+0x160,bbc]), 
  #10
    (dbghelp: RtlCopyMemory+0x2,bbd@0,000,7FF,A72,BF9,6BD[ntdll.dll+0xa9,6bd]), 
  #11
    (dbghelp: _C_specific_handler+0x97@0,000,7FF,A72,BDF,667[ntdll.dll+0x8f,667]), 
  #12
    (dbghelp: _chkstk+0x12f@0,000,7FF,A72,BF5,04F[ntdll.dll+0xa5,04f]), 
  #13
    (dbghelp: RtlFindCharInUnicodeString+0xa96@0,000,7FF,A72,B6E,866[ntdll.dll+0x1e,866]), 
  #14
    (dbghelp: RtlRaiseException+0x195@0,000,7FF,A72,BA4,945[ntdll.dll+0x54,945]), 
  #15
    (dbghelp: RaiseException+0x6c@0,000,7FF,A70,52F,ABC[KERNELBASE.dll+0x5f,abc]), 
  #16
    (dbghelp: CxxThrowException+0x90@0,000,7FF,6F5,24E,CE0[cataclysm-tiles.exe+0x1,bce,ce0]), 
  #17
    (dbghelp: std::_Throw_bad_optional_access+0x2e@0,000,7FF,6F3,BA0,0DE[cataclysm-tiles.exe+0x520,0de]), 
  #18
    (dbghelp: uilist_impl::draw_controls+0x7c2@0,000,7FF,6F3,E58,842[cataclysm-tiles.exe+0x7d8,842]), 
  #19
    (dbghelp: cataimgui::window::draw+0x1ed@0,000,7FF,6F3,CC4,C9D[cataclysm-tiles.exe+0x644,c9d]), 
  #20
    (dbghelp: ui_adaptor::redraw_invalidated+0x411@0,000,7FF,6F3,CE9,751[cataclysm-tiles.exe+0x669,751]), 
  #21
    (dbghelp: uilist::query+0x1f3@0,000,7FF,6F3,E59,F43[cataclysm-tiles.exe+0x7d9,f43]), 
  #22
    (dbghelp: Character::body_window+0x2,af9@0,000,7FF,6F4,17B,0E9[cataclysm-tiles.exe+0xafb,0e9]), 
  #23
    (dbghelp: pick_part_to_heal+0x18b@0,000,7FF,6F4,B76,89B[cataclysm-tiles.exe+0x1,4f6,89b]), 
  #24
    (dbghelp: heal_actor::use_healing_item+0x883@0,000,7FF,6F4,B96,973[cataclysm-tiles.exe+0x1,516,973]), 
  #25
    (dbghelp: heal_actor::use+0x285@0,000,7FF,6F4,B81,545[cataclysm-tiles.exe+0x1,501,545]), 
  #26
    (dbghelp: use_function::call+0x1d@0,000,7FF,6F4,ECC,79D[cataclysm-tiles.exe+0x1,84c,79d]), 
  #27
    (dbghelp: itype::invoke+0x159@0,000,7FF,6F4,8F4,7D9[cataclysm-tiles.exe+0x1,274,7d9]), 
  #28
    (dbghelp: Character::invoke_item+0x69d@0,000,7FF,6F3,F56,EED[cataclysm-tiles.exe+0x8d6,eed]), 
  #29
    (dbghelp: Character::use+0xc8b@0,000,7FF,6F3,F85,ACB[cataclysm-tiles.exe+0x905,acb]), 
  #30
    (dbghelp: avatar_action::use_item+0xc91@0,000,7FF,6F4,9AE,CB1[cataclysm-tiles.exe+0x1,32e,cb1]), 
  #31
    (dbghelp: avatar_action::eat_or_use+0x6e@0,000,7FF,6F4,9A6,33E[cataclysm-tiles.exe+0x1,326,33e]), 
  #32
    (dbghelp: game::do_regular_action+0x1,350@0,000,7FF,6F4,28E,DA0[cataclysm-tiles.exe+0xc0e,da0]), 
  #33
    (dbghelp: game::handle_action+0xa37@0,000,7FF,6F4,298,757[cataclysm-tiles.exe+0xc18,757]), 
  #34
    (dbghelp: do_turn+0xf47@0,000,7FF,6F3,BD7,887[cataclysm-tiles.exe+0x557,887]), 
  #35
    (dbghelp: WinMain+0xe95@0,000,7FF,6F3,A5C,655[cataclysm-tiles.exe+0x3dc,655]), 
  #36
    (dbghelp: __scrt_common_main_seh+0x106@0,000,7FF,6F5,24D,DA6[cataclysm-tiles.exe+0x1,bcd,da6]), 
  #37
    (dbghelp: BaseThreadInitThunk+0x1d@0,000,7FF,A71,F92,57D[KERNEL32.DLL+0x12,57d]), 
  #38
    (dbghelp: RtlUserThreadStart+0x28@0,000,7FF,A72,BAA,F28[ntdll.dll+0x5a,f28]),

**Comment by harakka** [comment] 2024-09-03 12:28
Duplicate of #76110

Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.

**Closed by harakka** 2024-09-03 12:28 UTC
Labels: (S1 - Need confirmation)
