### ISSUE TITLE
A lot of errors in name(filename)

### ISSUE THREAD

**Issue by Evgehas** [CleverRaven/Cataclysm-DDA#66261] opened 2023-06-17 19:12 UTC
### Describe the bug

There are many errors that are explained when loading a character. And most of these errors are related to names.

### Attach save file

[Бутжек-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11779797/-trimmed.tar.gz)

### Steps to reproduce

1. Start the game.
2. Create world.
3. Create character

### Expected behavior

A mistake in the name makes half of the game not working. It doesn't have to be.

### Screenshots

N/A

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: MED-LX9N; Release: 10; Incremental: 10.1.0.297C10; 
- Game Version: 38bfec9 [32-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(82.6%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Бионические профессии [package_bionic_professions],
    Перевод сложных диалогов [translate_dialogue],
    Альтернативные символы карты [alt_map_key],
    Развитая XEDRA [xedra_evolved]
]

### Additional context

Debug.log: 
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11779802/debug.log)

**Comment by hansonry** [comment] 2023-06-18 03:00
I think I am also seeing this when loading a saved character:

 DEBUG    : Failed to read from ".save/Hiland Park/#SmFtZWwgJ1R5cmFudCcgQnJ1bm5lcgAAAsav.sav": opening file failed

 FUNCTION : std::unique_ptr<std::basic_istream<char> > read_maybe_compressed_file(const std::filesystem::__cxx11::path&)
 FILE     : src/cata_utility.cpp
 LINE     : 497
 VERSION  : 0.G-2461-gc766859d6b

**Comment by Alm999** [comment] 2023-06-18 09:54
Yeah, the code just tries to append "*A…Asav", replacing the trailing ='s od the Base64 encoding (number of A-s vary, probably depending on how many "=" was in the original Base64 string) to save file names.

**Comment by Evgehas** [comment] 2023-06-18 11:50
How to fix it? I can't play the game. Half of the character's body doesn't work. And before you enter the world, there are so many bugs that you can scroll through them to the music)))

**Comment by hansonry** [comment] 2023-06-18 18:57
Hmm, I think I know what is going on....
Looks like this function: https://github.com/CleverRaven/Cataclysm-DDA/blob/f771f3b5f9e33f54ee0044c8e47bb342a4999c5f/src/worldfactory.cpp#L65
It taking a path including it's extension and `base64_decode`ing it. I think we need to remove the extension before decoding it.

**Comment by hansonry** [comment] 2023-06-18 19:46
Nope, that isn't it. Looks like the real culprit is here 

https://github.com/CleverRaven/Cataclysm-DDA/blob/f771f3b5f9e33f54ee0044c8e47bb342a4999c5f/src/worldfactory.cpp#L355

For some reason the filename starts with `.save` so the way we are detecting extensions would pick up the front of the string, not removing the extension. I saw a PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/66287 That I think will fix the problem.

**Comment by Evgehas** [comment] 2023-06-18 20:36
With the latest fix, there are fewer bugs. However, similar errors remained:
![Screenshot_20230618_233420](https://github.com/CleverRaven/Cataclysm-DDA/assets/73546622/48bdc0de-76e2-45e0-8c8d-a3e7fed53ad6)

**Comment by hansonry** [comment] 2023-06-18 21:30
Yeah, I am guessing my PR wont fix this either. This looks completely different.

**Comment by Evgehas** [comment] 2023-06-18 22:20
Well, I get it. The bad thing is that it can't be fixed due to the fact that only I have this problem.

**Comment by RenechCDDA** [comment] 2023-06-19 06:36
Duplicate of #65162

Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.

**Closed by RenechCDDA** 2023-06-19 06:36 UTC
Labels: (S1 - Need confirmation)

**Comment by akrieger** [comment] 2023-06-25 21:34
This was #66273 actually.
