### ISSUE TITLE
You can't dodge stones thrown by feral humans

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42531] opened 2020-07-29 08:34 UTC
# Describe the bug

I just created a big cage with a lot of feral humans and stayed there receiving their shots for quite some time and wasn't able to dodge a single stone and didn't get a single XP on dodging though I have dodging 3. It should be really impossible or almost impossible to dodge a simple stone throw at you?

Even though I can dodge quite regularly hunters, dogs and zeds in general I can't evade a single stone.

Just tried with dodge 20 and still not a single evade.

# Steps To Reproduce

1 - create a big cage with a lot of feral humans inside.
2 - Have some levels on dodging.
3 - Just stay there taking and notice that you will never dodge their stones or earn a single XP

# Expected behavior

Maybe it should be impossible or near impossible to dodge shots from guns but probably this shouldn't be the case to thrown weapons. Not even arrows from bows as you can even watch some challenge videos from even some people parrying arrows with swords, though it probably would be way harder to parry than just trying to dodge or block in anyway possible.

Then imagine someone with mutations, implants and super-human stats and legendary skills!

# Screenshots

Not needed.

# Versions and configuration

I am using using the CDDA 0.E-b10865 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

# Additional context

**Comment by talesvin** [comment] 2020-07-31 00:22
I feel that not only you should be able to dogde and train dodge this way. Feral humans should be imprecise with their throws.

**Comment by Michael1993** [comment] 2020-07-31 07:37
Wait, I always thought that you can only dodge melee attacks? Aren't projectile attacks "hit-or-miss"? When a turret shoots at you, you don't get notified if it misses, do you?

**Comment by Duck13Tales** [comment] 2020-07-31 14:56
It seems to be the case. We can't dodge projectiles. I am not sure if the enemies can miss as even the feral humans can hit with great accuracy as in my tests I would get hit consistently every other turn.

So I think it would be great if we were able to dodge the ranged attacks too, earn XP and be notified by the way hahaha

**Comment by Marrim** [comment] 2020-07-31 16:41
Isn't the player able to dodge boomer spew? I think it even used to be the go-to dodge training method.

**Comment by Duck13Tales** [comment] 2020-07-31 18:58
No idea. There is quite some time that I don't get hit by the boomer spew or explosion, I supposed it was due the environment protection from my googles. Though the acidic zombies spew usually hits me but I didn't noticed if I earned any XP. They are aggravating enough to just make me want to murder them ASAP.

**Comment by talesvin** [comment] 2020-07-31 19:06
You can still train you dodge the way @Marrim said on the post above but now the boomer will explode after some time. I tested this method by trapping a boomer into a bear trap and staying 2 spaces from the boomer, my character had 8 in all stats and 0 in all skills, after testing it on 2 boomers my dodge skill went from 0% to 30%, so the skill will raise but very slowly and you'll need a bunch of boomers to train it, which i think its fair because the old way to do it was somewhat cheesy. 
Then after the boomer testing i created a new character and i did the same with a feral human, one thing about feral humans is that they are smart enough to not step into a bear trap so i needed to make a circle of bear traps and spawn a feral human in the middle of it, after waiting some time while the feral human as throwing rocks at me i realized that i did not earned any XP on my dodging skill. So maybe the problem is on feral humans not giving the player XP points when they throw rocks at the player.

**Comment by Duck13Tales** [comment] 2020-07-31 19:38
For me the problem is that we should be able to dodge ranged attacks too. At least the feral humans rocks can't be dodged.

**Comment by Michael1993** [comment] 2020-08-01 07:40
But you do dodge attacks (?) - it just does not appear in the message log (I think). When you miss a shot it also does not appear in the message log, so it's consistent. Maybe it should give dodge experience but I'm not sure.

**Comment by Duck13Tales** [comment] 2020-08-01 08:52
But it says when you dodge and when you miss.
![dodge miss](https://user-images.githubusercontent.com/67176313/89098117-13a2c180-d3bb-11ea-94c1-e60214908d46.png)

**Comment by Michael1993** [comment] 2020-08-01 10:35
I meant ranged attacks. There are no messages when you miss ranged attacks and there are no messages when enemies miss ranged attacks. Does not mean they do not miss.
For example: if you throw stones at zombies, you do not get a message if you miss.

**Comment by Duck13Tales** [comment] 2020-08-01 20:25
This don't seem to be the case. It seems that the enemies hit with 100% accuracy and you can't dodge.

Here is a print showing that every 5 seconds he hit me, without ever taking more than 5 seconds to hit for quite a while. It shows that it never misses or you dodge.

You can try how much as you like and you will find the same result.

![ranged](https://user-images.githubusercontent.com/67176313/89109940-04a02b80-d41c-11ea-9571-3bc7246f03a8.png)

**Comment by Hatfish** [comment] 2021-08-24 15:34
Did some testing at dodge 20 and confirmed, feral humans will always hit no matter the player's dodge level, with the sole exception of if an obstacle is in the way.  The attacks also seem to have a weirdly high chance to rip clothing based on observation, but that might just be luck on their part.

**Comment by Night-Pryanik** [comment] 2021-09-13 11:28
Closed by #51465.

**Closed by Night-Pryanik** 2021-09-13 11:28 UTC
Labels: <Bug>, Monsters
