### ISSUE TITLE
X has two definitions from the same source (dda) errors when loading a world

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#55725] opened 2022-02-27 18:10 UTC
### Describe the bug

I'm getting data loading errors when I load a world. anothersimulacrum says this is the result of loading more than one world without closing the game out first.

### Steps to reproduce

> If you close the game between each time you load a world, you will see no errors, and you can ignore it without consequences
- anothersimulacrum in the Discord

### Expected behavior

No errors.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1526 (21H1)
- Game Version: f7c92b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by anothersimulacrum** [comment] 2022-02-27 18:12
I believe data is not being correctly unloaded.
https://github.com/CleverRaven/Cataclysm-DDA/blob/f7c92b9d2f7964295fb4f09b4e5780b2f0c6d469/src/init.cpp#L535

**Comment by LeahLuong** [comment] 2022-02-27 20:56
#55606 may be related, if not a dupe.

**Comment by anothersimulacrum** [comment] 2022-02-27 22:00
Looks like a duplicate

**Comment by Night-Pryanik** [comment] 2022-03-02 10:07
Duplicate of #55606.

**Closed by Night-Pryanik** 2022-03-02 10:07 UTC
Labels: <Bug>, [C++]
