### ISSUE TITLE
Storage batteries with charges don't register when crafting or mounting into the vehicle

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#38148] opened 2020-02-19 07:09 UTC
# Describe the bug

If battery has some charge, it cannot be used as a crafting component and cannot be mounted into the vehicle.

# Steps To Reproduce

1. Spawn a vehicle, small storage battery with charges, and all required tools.
2. Try to attach the battery to the vehicle.

# Expected behavior

Battery can be attached, as before.

# Screenshots
N/A

# Versions and configuration

 - OS: Windows 7 x64
 - Game Version: 0.D-12398-ge9f1cd7
 - Graphics version: Tiles
 - Mods loaded: Aftershock, C.R.I.T.

# Additional context
N/A

**Comment by Funguss** [comment] 2020-02-19 07:51
That's new. Is this all storage batteries, large, regular and small? Does it include car and motorbike?

**Comment by Funguss** [comment] 2020-02-19 08:03
Ah, this is a duplicate of #38132 and fixed by #38146 .

**Closed** 2020-02-19 08:35 UTC
