### ISSUE TITLE
(Multi)drop selection menu doesn't respect reassigned keystrokes

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#28782] opened 2019-03-17 20:10 UTC
**Is your feature request related to a problem? Please describe.**  
In some menus, keypad cursor keys (8,4,6,2) don't work by default. This can be worked around by assigning those via keybindings, but the drop/multidrop selection menu seems to be the only one still ignoring these, and is only interact-able via "normal" cursor keys.

**Describe the solution you'd like**  
Have the said menu respect reassigned keystrokes.

**Describe alternatives you've considered**  
Using an autohotkey script instead of built-in key redefining.

**Additional context**
![image](https://user-images.githubusercontent.com/34726992/54497675-b49bf400-490e-11e9-89c1-d48ad7b5cbe1.png)
From the looks of this (which is what I get by pressing d, then any direction, then ?), the game *should* be using those keys for the drop menu, but actually doesn't.

**Comment by DSeyka** [comment] 2019-03-17 22:49
The only thing that seems off in the code to me, is `ctxt.allow_text_entry = true`; on line 1894 in inventory_ui.cpp. I'm not sure if that applies though, since it's `#ifdef __ANDROID__`, while I'm on Windows.

**Comment by wapcaplet** [comment] 2021-02-16 23:28
Closing as a duplicate of #39709

**Closed by wapcaplet** 2021-02-16 23:28 UTC
Labels: <Bug>, Controls / Input
