### ISSUE TITLE
Failed to write module list when creating a new world

### ISSUE THREAD

**Issue by TheHolyStone** [CleverRaven/Cataclysm-DDA#65180] opened 2023-04-19 04:36 UTC
### Describe the bug

When I create a new world, if the world name contains Chinese, the module list writing fails; If the name of the world is all in English, then creating the world is successful.

### Attach save file

N/A

### Steps to reproduce

1. Creating a world with a name in Chinese, failed to write the module list.
2. Create a world named English and successfully create it.

### Expected behavior

The name of the world containing Chinese can also be created normally.

### Screenshots

![屏幕截图(53)](https://user-images.githubusercontent.com/104404164/232967499-29a0966e-6365-45e2-8490-e466616f3ba5.png)
![屏幕截图(56)](https://user-images.githubusercontent.com/104404164/232967519-4544ef56-a21d-43d2-bb83-a7ffcd40b577.png)

### Versions and configuration

-Operating system: Win10.
-Game version: a3c3959.
-Graphic version: I didn't even enter the game.
-Game language: Chinese.
-Loaded modules: Selecting any module will cause the module list to fail to load.

**Comment by hexagonrecursion** [comment] 2023-04-19 06:25
Works fine on Linux (I named the world "测试"). Can someone test this on Win10?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 37 (Thirty Seven); Release: 37; Codename: ThirtySeven; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment] 2023-04-19 06:47
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64328

**Closed by ZhilkinSerg** 2023-04-19 06:47 UTC
Labels: (S1 - Need confirmation)
