### ISSUE TITLE
Trade screen seems to be broken

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#52981] opened 2021-11-23 21:02 UTC
### Describe the bug

New trade screen cannot be switched between player and NPC windows.

### Steps To Reproduce

Open trade menu, attempt to trade something with a trader NPC.

### Expected behavior

Normal trading

### Versions and configuration

03f9cc1 (tiles)

**Comment by catdach** [comment] 2021-11-23 21:26
duplicate of #52935

**Closed** 2021-11-23 23:51 UTC
Labels: (S3 - Duplicate)
