### ISSUE TITLE
"fake_char_kiln (itype) has two definitions from the same source (dda)"

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#59530] opened 2022-07-23 15:12 UTC
### Describe the bug

After taking a break from CDDA for the last couple of months due to some IRL problems, I decided to get back into it in a "fresh start" sort of way, abandoning my previous installation and saves (though keeping the files for later reference) and jumping in to an entirely new installation to see how the game has changed since I last updated. After some initial confusion with the changed UI, I made a new world, and the world settings were being loaded for me to create a new character... I got the error message in the title of this bug report. I decided to see if a mod was causing it, but nope - after creating a test world with no mods other than the ones that were enabled by default, I got the same error.

### Steps to reproduce

1. Make a new world
2. Try to make a new character
3. See that you cannot

### Expected behavior

I expected to be able to make a character and play the game.

### Versions and configuration

I can't generate a game report without being able to actually make and play a character, but the game version I'm playing as displayed on the main menu is b86bfea.

**Comment by Night-Pryanik** [comment] 2022-07-23 16:14
Duplicate of #59508.

**Closed by Night-Pryanik** 2022-07-23 16:14 UTC
Labels: (S1 - Need confirmation)
