### ISSUE TITLE
Problem with vision peek

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68326] opened 2023-09-25 18:57 UTC
### Describe the bug

i think that vision peek work not correct. If i use peek down i see only thermal silhouette self

I tried different tileset, but the result is the same

### Attach save file

[Magenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12718406/Magenta-trimmed.tar.gz)

### Steps to reproduce

1. under try peek down

1. if i try go into dark or go from dark on the moment get thermal silhouette on self

### Expected behavior

this mechanic work in build version 2023-09-13-0306

build version 2023-09-13-0306
normal level
![ok_normal](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/cf2e0c4a-1128-4aa0-af7a-25823bd55124)
action
![ok_action](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/e935ef09-e311-4d39-b1ef-2eba620f49c6)
peek level down
![ok_vivsion](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/03159848-ba06-4f11-a06a-4daaebc19c0e)

### Screenshots

build version: 2023-09-25-1540
normal level
![normal_level](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/80dd304e-5277-4e1f-bfe8-19e8c8c8e72f)
action
![action](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/2d17c270-00ac-44c4-8310-8af4cb4066b3)
problem
![problem_peek](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/964387e1-75c9-45ca-845f-43e22e32d8a3)

thermal vision moment bug
![moment_error](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/856669a4-37cb-4e4c-9d78-1a25701b1dc9)

### Versions and configuration

os: windows 7
game version: 953603
build version: 2023-09-25-1540
[debug_info.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/12718425/debug_info.txt)

**Comment by GuardianDll** [comment] 2023-09-25 19:01
duplication of #68121

**Comment by RenechCDDA** [comment] 2023-09-25 21:50
Duplicate of #68121

**Closed by RenechCDDA** 2023-09-25 21:50 UTC
Labels: (S1 - Need confirmation)
