### ISSUE TITLE
RM13 Combat Armor Weight Increases on Activation

### ISSUE THREAD

**Issue by KaillSlater** [CleverRaven/Cataclysm-DDA#30644] opened 2019-05-19 05:01 UTC
Game version: 9002

Operating system: Win 10 64

Tiles or curses: Tiles

Mods active: None (DDA Only)

### Expected behavior
Activating RM13 Combat Armor does not change its weight.
### Actual behavior
Activating RM13 Combat Armor increases is weight to over 400 kg.  The weight increase persists even after deactivating it.
### Steps to reproduce the behavior
Start new game.  Spawn RM13 Combat Armor.  Spawn plutonium cells.  Reload suit, wear suit, activate suit.

**Comment by Rivet-the-Zombie** [comment] 2019-05-19 05:09
I can confirm this behavior.

**Comment by esotericist** [comment] 2019-05-19 05:15
Can this be a mod issue? I can't replicate it myself.
![image](https://user-images.githubusercontent.com/1569754/57978075-7e382f00-79ba-11e9-8122-0a5739923c56.png)

**Comment by esotericist** [comment] 2019-05-19 05:16
... ah, I see, it happens a turn later.

**Comment by TechyBen** [comment] 2019-05-20 13:49
Ah! This bug might also be affecting Advanced UPS. Does the RM13 take plutonium? Or just have charges?

**Comment by Fris0uman** [comment] 2019-05-20 15:10
The shift in weight is probably caused by this 
![image](https://user-images.githubusercontent.com/41293484/58032046-0e44b880-7b22-11e9-9680-369022a8053f.png)

Which means it comes from #30255

**Comment by TechyBen** [comment] 2019-05-20 16:53
Yeah, checking files instead of wiki shows 0.08 wieght of the Plut cell. So I've quick fixed in my own game by just making the cell weigh 0.001 for now. :P

**Closed** 2019-05-20 21:17 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
