### ISSUE TITLE
Shooting through bars, fences, etc impossible

### ISSUE THREAD

**Issue by Aluminumfoil** [CleverRaven/Cataclysm-DDA#39532] opened 2020-04-13 16:30 UTC
# Describe the bug

Shooting bullets and arrows through porous barriers is currently impossible, both for players and monsters. The projectile does not hit the barrier. When arrows are used, they appear adjacent to the barrier on the line at which the projectile traveled. In either case, no "you miss" result is displayed, the shot simply fails without comment. 

Shots that path through a target on the near side of the barrier can still hit and damage the unintended target. This is true for both player and monster shots. 

(shooter)-----------(friendly)----------->**projectile stops here**(barrier)-----------(target)

The barriers tested were: sandbag barricade, window frame with metal bars, metal bars, rebar cage, chain-link fence. The player weapons tested were: M16A4, Repeating Crossbow, M110A1. 

The monster tested was an M249 autonomous CROWS II, shooting at the player. 

Throwing through is also impossible, as in previous builds. 

However, stabbing through with a spear is possible. Some attacks hit the barrier and can damage it, while some attacks go through and hit the target behind the barrier. I'm not sure if this is intended behavior or not. IIRC it was not possible in previous builds. 

# Steps To Reproduce

Set up a porous barrier. Attempt to shoot through it in various configurations. Observe that the shot does not hit the barrier. Observe that the shot does not attempt to hit the target. 

Repeat with a Reach melee weapon. Observe that the shot sometimes hits the barrier and sometimes hits the target. 

Spawn a monster on the other side of the porous barrier and observe that its shots do not penetrate the barrier either. 

# Expected behavior

The player can shoot through porous barriers. Monsters can shoot through porous barriers. 

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-635-gef0197a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by anothersimulacrum** [comment] 2020-04-13 17:05
Duplicate of #39521

**Closed** 2020-04-13 17:09 UTC
