### ISSUE TITLE
Consume item menu change

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42113] opened 2020-07-14 05:07 UTC
# Is your feature request related to a problem? Please describe.
The "Consume Item Menu" menu closes after consuming an item.

# Describe the solution you'd like
The window to stay open after you choose a consumable similar to how the "Eat" menu stays open after you choose an item.

# Describe alternatives you've considered
An option to toggle whether or not the menu closes after choosing an item.

**Comment by ZaricaDemoni** [comment] 2020-07-14 05:36
default controls list nothing bound to the consume menu, and I can consume or eat anything through the "E"at menu without it closing (bandages, drugs, food, water, smoking), so I'm a little confused here.

**Comment by NotHereCDDA** [comment] 2020-07-14 07:40
On build 10828  The reason i like the Eat menu more than the default consume item menu is that you can choose between food, water, and medicine to be displayed. makes it so i have to scroll a bit less.

**Comment by NotHereCDDA** [comment] 2020-07-14 07:42
I also may have mixed up the 2 commands since i rebound alot of keys. apologies for the confusion.

**Comment by ZaricaDemoni** [comment] 2020-07-14 10:31
okay with the confusion out of the way I fully agree, having the consume menu stay up like the eat menu is nice. especially since it is organized, I never used the consume menu until now so I'm a little a little impressed with its organization. may need to find a key to bind it too permanently for now so i can stop losing my camomile tea among the literal liters of maple syrup.

**Comment by esotericist** [comment] 2020-10-07 13:40
as far as i'm concerned, this is actually a regression, as before consuming things took time, the menu re-populated correctly.

so in my eyes this is a bug, not a feature request. albeit a minor one.

**Closed** 2020-10-17 02:44 UTC
Labels: <Bug>, Info / User Interface
