### ISSUE TITLE
Skeletons have organs

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16893] opened 2016-05-27 18:05 UTC
Skeletons drop raw offal (the edible kind) when butchered.

**Comment by mugling** [comment] 2016-05-27 20:26
Confirmed, and there are other examples also

**Comment by pisskop** [comment] 2016-05-28 20:50
Maybe bones should imply no meat

**Comment by Rivet-the-Zombie** [comment] 2016-05-28 21:03
This would be easily fixed by something similar to the STOMACH flag, so monsters who aren't opted-in via the flag won't produce offal.

**Comment by 3721assistant** [comment] 2016-05-30 10:13
Triffids also drop organs, and the organs have material of meat, not sure if it is right since they are plant

**Comment by kevingranade** [comment] 2016-05-30 16:11
That is also a bug.

**Comment by i2amroy** [comment] 2016-06-08 01:05
Might be important to note that our skeletons aren't just skeletons, but are more something that looks kinda like this (but with black ooze instead of red, IIRC)
http://img01.deviantart.net/2fd5/i/2012/043/6/1/cancer_by_lordnetsua-d4phl2v.jpg

So the fact that they drop edible offal is almost certainly a bug, but the fact that they necessarily still have internal organs is not necessarily one.

**Comment by pisskop** [comment] 2016-06-08 01:34
tainted soup stock aye

**Closed** 2016-06-22 00:52 UTC
Labels: Bug
