### ISSUE TITLE
when wield a two handed item with broken arm item is lost

### ISSUE THREAD

**Issue by acordado** [CleverRaven/Cataclysm-DDA#44763] opened 2020-10-09 18:45 UTC
# Describe the bug
when wield a two handed item with broken arm item is lost

# Steps To Reproduce

1. make a player with a two handed heavy sledge hammer.
2. broke a arm of player.
3. open inventory.
4. select heavy sledge hammer.
5. try wield item.

# Expected behavior
player not wield heavy sledge hammer.
message: "The heavy sledge hammer can't be wielded with only one arm".

# Screenshots
![Captura de tela_2020-10-09_15-14-07](https://user-images.githubusercontent.com/60556740/95619093-6c8a7800-0a44-11eb-891a-4829dd74db63.png)
![Captura de tela_2020-10-09_15-14-36](https://user-images.githubusercontent.com/60556740/95619090-6bf1e180-0a44-11eb-88b5-3495d2a9dac2.png)
![Captura de tela_2020-10-09_15-14-52](https://user-images.githubusercontent.com/60556740/95619088-6b594b00-0a44-11eb-8b06-6e6f31ade24c.png)
![Captura de tela_2020-10-09_15-15-18](https://user-images.githubusercontent.com/60556740/95619087-6b594b00-0a44-11eb-9826-cb5dc6cad97f.png)
![Captura de tela_2020-10-09_15-15-56](https://user-images.githubusercontent.com/60556740/95619086-6ac0b480-0a44-11eb-9689-9cf94cd3695f.png)
![Captura de tela_2020-10-09_15-16-28](https://user-images.githubusercontent.com/60556740/95619083-698f8780-0a44-11eb-9c24-dcb4a282d0e6.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux
- Game Version: 0.E-6544-gbbf813c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

maybe related to issue [#30912](https://github.com/CleverRaven/Cataclysm-DDA/issues/30912#issue-449050348)

**Comment by Ramza13** [comment] 2020-10-13 16:17
Duplicate of #41244

**Closed** 2020-10-15 07:27 UTC
Labels: (S3 - Duplicate)
