### ISSUE TITLE
Error in Win32 bits

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#61410] opened 2022-10-02 13:11 UTC
### Describe the bug

Because I got tons of silent ctd in 64bits version, (I think is related to hallucination)
Downloaded the 32bit one ("cdda-windows-tiles-x32-2022-10-02-0929"), was using "cdda-windows-tiles-x64-msvc-2022-10-01-0633". And cannot start the game because it mention an error in the file "character_modifiers.json" . Already compare them and are both identical.
No clues here.
Here is the log. There is a lot more stuff than here than the log of 64 bits that just mention some duplicate map in Aftershock.
  #0
    (dbghelp: @0x15db816[cataclysm-tiles.exe+0x2db816]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xe4@0x6db816),
    0x6db816    src/debug.cpp:1119    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x15dcbee[cataclysm-tiles.exe+0x2dcbee]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x2de@0x6dcbee),
    0x6dcbee    /opt/mxe/usr/i686-w64-mingw32.static.gcc11/include/time.h:219    time
    0x6dcbee    src/debug.cpp:1447    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x15de006[cataclysm-tiles.exe+0x2de006]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1dd@0x6de006),
    0x6de006    src/debug.cpp:508    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x24687e9[cataclysm-tiles.exe+0x11687e9]), 
    (libbacktrace: void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)+0xfd@0x15687e9),
    0x15687e9    /opt/mxe/usr/lib/gcc/i686-w64-mingw32.static.gcc11/11.2.0/include/c++/bits/basic_string.h:671    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x15687e9    src/debug.h:78    void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
  #4
    (dbghelp: @0x1a1ec5c[cataclysm-tiles.exe+0x71ec5c]), 
    (libbacktrace: main_menu::new_character_tab()+0xef4@0xb1ec5c),
    0xb1ec5c    src/main_menu.cpp:949    main_menu::new_character_tab()
  #5
    (dbghelp: @0x1a21223[cataclysm-tiles.exe+0x721223]), 
    (libbacktrace: main_menu::opening_screen()+0x1a41@0xb21223),
    0xb21223    src/main_menu.cpp:844    main_menu::opening_screen()
  #6
    (dbghelp: @0x2d510ed[cataclysm-tiles.exe+0x1a510ed]), 
    (libbacktrace: main+0x1fab@0x1e510ed),
    0x1e510ed    src/main.cpp:788    main
  #7
    (dbghelp: @0x1301396[cataclysm-tiles.exe+0x1396]), 
    (libbacktrace: __tmainCRTStartup+0x226@0x401396),
    0x401396    /opt/mxe/tmp-gcc-i686-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #8
    (dbghelp: BaseThreadInitThunk+0x12@0x75d033ca[kernel32.dll+0x133ca]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #9
    (dbghelp: RtlInitializeExceptionChain+0x63@0x76fc9ed2[ntdll.dll+0x39ed2]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #10
    (dbghelp: RtlInitializeExceptionChain+0x36@0x76fc9ea5[ntdll.dll+0x39ea5]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/main_menu.cpp:947 [bool main_menu::new_character_tab()] Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value":
            ^
             {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,

### Steps to reproduce

Try to run 32 bit version I guess.

### Expected behavior

Game start normally. And perhaps stop ctd.

### Versions and configuration

Windows 7
cdda-windows-tiles-x64-msvc-2022-10-01-0633
cdda-windows-tiles-x32-2022-10-02-0929

### Additional context

I dont have girlfriend.

**Comment by anothersimulacrum** [comment] 2022-10-02 14:24
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/61095
I would advise against use of the 32 bit version if your computer is 64 bit.

**Closed by anothersimulacrum** 2022-10-02 14:24 UTC
Labels: (S3 - Duplicate)
