### ISSUE TITLE
Peeking error with MoM

### ISSUE THREAD

**Issue by UltraEarth** [CleverRaven/Cataclysm-DDA#70268] opened 2023-12-17 15:40 UTC
### Describe the bug

Peeking up or down stairs or other form of stairs while having Premonition ON (MoM) will only show the heat mark of your character or other enemies on the upper or lower level of the stairs while everything else is blacked out. 

There is a temporary fix, you have to go up another level while peeking and go down again and then you are able to see the next floor but you have to do this everytime you peek up or down some sort of stairs.

### Attach save file

[Bloomdale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13696680/Bloomdale-trimmed.tar.gz)

### Steps to reproduce

1. Find stairs.
2. Peek up or down while having premonition from MoM turned on previously.
3. You encounter the bug this way.
4. Optional: You can temporary fix it looking another level up and then go down again another level. 
(Note: this happens if you peek in any stair, so you will have to do this temporary fix everytime.

### Expected behavior

To be able to see next floor while having Premonition turned on. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/140266604/991ed9c8-23da-4b2e-8f14-cd8814a979f9)

### Versions and configuration

OS: Windows 10
Game version: 0f8ac41(64-bit)
Ingame language: English
Mods loaded: Aftershock, Magiclysm, Arcana and Magic Items, Mind over Matter, Bionic Professions, Xedra Evolved, Blaze Industries, Dinomod, Lighter Weariness, Mithical Martial Arts/ and mods extension, Bombastic Perks, Zetsukaze's Hair, My Sweet Cataclysm, sees_player_hitbutton, sees_player_retro, Magiclysm Revamp and Additions, disable NPC needs, Portal Storms ignore NPC, Slowdown Fungal Growth, No Bionic Slots, SpeedyDex, Stats Through Skills, Stats Through Kills, Tamable Wildlife.

**Comment by GuardianDll** [comment] 2023-12-17 15:43
not related to MoM, it is same borked in vanilla
Duplicate of #69742

**Closed** 2023-12-17 15:46 UTC
Labels: (S1 - Need confirmation)
