### ISSUE TITLE
Crash upon attempting to repair using high-temperature welding kit

### ISSUE THREAD

**Issue by TrueChevaleresse** [CleverRaven/Cataclysm-DDA#67161] opened 2023-07-25 09:02 UTC
### Describe the bug

Per title. Attempting to repair a | / tempered zweihander using a plugged-in welding kit causes a segmentation fault.

### Attach save file

[Warminster Heights-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12159054/Warminster.Heights-trimmed.tar.gz)

### Steps to reproduce

1. Load save.
2. Plug in welding kit.
3. Attempt to repair welding kit.
4. Observe crash.

### Expected behavior

Not crashing.

### Versions and configuration

OS: Windows 10
Version: 94c0d83
Graphics: Tiles
Language: English
Mods: "dda", "no_npc_food", "personal_portal_storms", "no_fungal_growth", "package_bionic_professions", "blazeindustries", "DinoMod", "extra_mut_scens", "MMA", "speedydex", "stats_through_kills", "StatsThroughSkills"

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12159134/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12159136/crash.log)

**Comment by EternalLaughter** [comment] 2023-07-25 09:32
This happens all the welders you can connect to the grid, so standard Arc Welder, Makeshift Arc Welder and as you said the
high-temperature welding kit. 
With batteries in them and plugged in the crash do not happen, only if they have no battery.

**Comment by RenechCDDA** [comment] 2023-07-25 09:58
Duplicate of #66944

**Closed by RenechCDDA** 2023-07-25 09:58 UTC
Labels: (S1 - Need confirmation)
