### ISSUE TITLE
Talk to people at an other Z-level

### ISSUE THREAD

**Issue by TheMrBakit** [CleverRaven/Cataclysm-DDA#20811] opened 2017-04-08 22:57 UTC
I thought it was a bug because i can talk to someone on an other different z-level. I know in real life you can shout but at this distance it should not be able to  discuss.
![image](https://cloud.githubusercontent.com/assets/18709806/24833082/ad410764-1c8c-11e7-8fc8-93117e5530ee.png)

![image](https://cloud.githubusercontent.com/assets/18709806/24833093/ca37dc76-1c8c-11e7-8416-e666c972b909.png)

Build 6381

**Comment by WizardOfOoo** [comment] 2017-04-10 02:22
Confirmed.

**Comment by Coolthulhu** [comment] 2017-04-16 11:38
So we want a hard restriction on talking to people on other z-levels?
That sounds excessive.

**Comment by kevingranade** [comment] 2017-04-16 18:12
For a quick fix that would be fine, in the long run we want conversational distance to take into account vertical features like floors.

**Comment by Coolthulhu** [comment] 2017-04-16 18:18
It takes distance and vision into account. 24 total distance is the maximum.

**Comment by Rod-Serling** [comment] 2017-04-30 01:25
So long-term, it should take into account walls too? So we'd have to pathfind the conversational distance?

**Comment by halfways** [comment] 2017-06-06 06:01
I think if this really occurs, then it must be fixed in the way Rod-Serling mentioned.
Currently, conversation takes place when npc can be seen, including through the window. But isn't it weird that we can talk through windows, but cannot just because we moved one step back?

**Closed** 2017-07-09 09:40 UTC
Labels: Long-term, Z-levels
