### ISSUE TITLE
Game freeze with 100% CPU when taking certain item from NPC

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#55491] opened 2022-02-19 01:05 UTC
### Describe the bug

It seems when I try to take a pot full of items from my follower, the game is stuck with 100% CPU usage and frozen (music is playing but no input is being accepted and nothing is rendered and the game can't be quit unless forcefully quit.

It seems that the same happens in non-SDL (terminal) version of the game, although here hitting ctrl+c brings the quit menu which can be interacted as well as showing the regular game screen, although other than quitting or not the game, nothing else can be done and CPU is still 100%.

It seems that follow trade window has its own issues, as I often got errors saying so, but this one seems to be more severe.

I added my save file for easy testing.

### Steps to reproduce

1. Load attached save game.
2. `e` → `left` to talk to Riva Funk
3. `b` to initialize trade
4. `b` again to take pot
5. Enter → `y` to confirm trade
6. The game freezes with 100% CPU now

### Expected behavior

Game shouldn't freeze.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-6205-g7fa132e8449 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8101158/crash.zip)

**Comment by andrei8l** [comment] 2022-05-04 21:03
Can't reproduce anymore. Pretty sure it was fixed in #56863

**Comment by Night-Pryanik** [comment] 2022-05-05 08:40
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2022-05-05 08:40 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
