### ISSUE TITLE
Encumberance of containers won't reduce when you drop things from them

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#43078] opened 2020-08-20 18:46 UTC
# Describe the bug

You have a backpack for example with things in it and you have 10 encumberance form it. Now when you drop things from this container your encumberance in the clothing screen won't go down unless you drop the whole backpack and choose to wear it again.

# Steps To Reproduce

1. Make a player with a backpack and some stuff to put in.
2. Drop things out of the backpack with the "d" drop menu
3. Check clothing screen for encumberance

# Expected behavior

Encumberance should go up and down on its own when you drop stuff out of containers.

# Screenshots

No screenshots

# Versions and configuration

 - OS: Win10
 - Game Version: o.E-5236-ge7434cf
 - Graphics version: UltiCa
 - Ingame language: German
 - Mods loaded: StatsThroughSkills

**Comment by Theundyingcode** [comment] 2020-08-20 23:51
Duplicate of #42983

**Closed** 2020-08-21 00:13 UTC
Labels: <Bug>
