### ISSUE TITLE
Fungal infection and antifungal drug effects broken

### ISSUE THREAD

**Issue by 1942rob** [CleverRaven/Cataclysm-DDA#51939] opened 2021-09-28 03:32 UTC
### Describe the bug

The fungus effect does not get worse over time but stays at the coughing / "taste of mushrooms" stage.

Also the antifungal effect (from antifungal drug and fungicide) does not cure the above infection

### Steps To Reproduce

1. Spawn in new world
2. Infect player with fungus effect
3. Wait for several days
-> Condition does not worsen
4. Spawn antifungal drugs and start gobbling down.
-> Condition does not get cured

### Expected behavior

Fungal infection worsen over several days, and is curable with antifungal drugs.

### Versions and configuration

OS: Windows 10
Game Version: 7123d51 (tiles)
Ingame Language: English
Mods loaded:   
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "package_bionic_professions",
  "blazeindustries",
  "crt_expansion",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "sees_player_retro",
  "alt_map_key"

**Comment by Kribylet** [comment] 2021-09-28 21:19
I am able to replicate this behavior on [77b4d5d9a8402233bc0c8d9f5ace9f1c3ec58ea5]. Issue does not occur on PR #51952, which leads me to believe that #51827 is the culprit.

The effect is tracking its duration as a property of the effect instance itself, which is merely a copy of the current state that is then discarded, meaning the state doesn't progress over time as intended.

Multiple PR's are proposed that will revert #51827 and deal with the issues that PR was supposed to fix:
#51947
#51952

**Comment by Maleclypse** [comment] 2021-12-05 06:38
Fix looks to be merged

**Closed by Maleclypse** 2021-12-05 06:38 UTC
Labels: (S1 - Need confirmation), Mechanics: Effects / Skills / Stats
