### ISSUE TITLE
Unable to generate a starting location in Massachusetts on android versions

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#60477] opened 2022-08-27 04:19 UTC
### Describe the bug

Massachusetts doesn't work in every android versions.

### Steps to reproduce

1. Create a world with Massachusetts mod.
2. Make a character.
3. Finish creating a character and join the world.

### Expected behavior

The world generates normally.

### Screenshots

![Screenshot_20220827-003304_Cataclysm_DDA_experimental](https://user-images.githubusercontent.com/52661206/187014049-f0386e4e-2176-42d4-89e3-0fad87ab4ce8.jpg)

### Versions and configuration

- OS: Android 9
- Versions: Every mobile versions
- Ingame language: Korean
- Mods:
Dark Days Ahead [dda]
Massachusetts [MA]

### Additional context
- Tried all the location.
- There was no crash.log or debug.log generated.

**Comment by ZhilkinSerg** [comment] 2022-08-27 11:02
This mod is still WIP. Use a bigger starting town or a different start location for the time being.

**Comment by NotSeawhite** [comment] 2022-08-27 11:26
> This mod is still WIP. Use a bigger starting town or a different start location for the time being.

I tried the max city scale and different locations but it still didn't work.

**Comment by ZhilkinSerg** [comment] 2022-08-27 12:06
City sizes are predetermined and city scale has no effect in MA mod. You can try to select a non-random starting city with bigger population (`C`) and/or select a different starting location (`/`) on the last tab of character selection. Like select Boston and/or Wilderness instead of Road.

![image](https://user-images.githubusercontent.com/16213433/187029418-06676781-9ca1-473a-8c90-b9d284885397.png)

**Comment by NotSeawhite** [comment] 2022-08-27 12:42
Also tried that. It doesn't seems like MA isn't working in android at all. :(

**Comment by ZhilkinSerg** [comment] 2022-08-27 14:27
For some reason omap files are not gzipped in data folder on Android.

**Comment by Zireael07** [comment] 2022-08-27 15:37
If that's the root cause, why is it only affecting the MA mod and not the core game?

**Comment by ZhilkinSerg** [comment] 2022-08-27 15:40
We only store omap files gzipped.

**Comment by Leland** [comment] 2022-10-30 12:52
Confirming fixed by #61601 and #61879

**Closed by Leland** 2022-10-30 12:52 UTC
Labels: (S2 - Confirmed), Code: Build, OS: Android, Mods: MA
