### ISSUE TITLE
Multidrop inventory transparency on 64bit.

### ISSUE THREAD

**Issue by mutt3x** [CleverRaven/Cataclysm-DDA#15487] opened 2016-02-20 00:54 UTC
using 64bit, win7-tiles (no tiles), build 4438 no mods

When you press (D)rop, the multidrop inventory background should be black.
Now I have tested all the latest versions and this only happens on **windows 64 tiles version (the 32 version does not have this bug in any way, i tried)** with **tiles turned off** with **any font** that is set **to be square in the config/fonts.json**
"map_fontwidth" : 14,
    "map_fontheight" : 14,
Font does not matter can be any. Numbers dont matter as long its square. But thats not all if i set the above to the default **w:8 h:16** everything is fine, lol.

Its really odd that this only happens in the multidrop inventory...

Its too specific thus im afraid this might be unique only for my machine :( or might not
Im confused why whould something like this happen, what am i missing?
**Tested the 32bit version on same criteria and everything is working normal.**
The devil is in the details.

**This needs to be confirmed obviously.**

**Dont believe me, Look. Every time you open the multidrop inventory same random transparency:**
![wtf](http://i.imgur.com/poj7PJ3.png)

**Comment by VlasovVitaly** [comment] 2016-03-01 13:24
Can't reproduce on Linux x64

**Comment by mutt3x** [comment] 2016-03-01 15:33
@VlasovVitaly Okey, here is the thing. Did the tests again on the latest win 64 builds and there is **no** bug if i create a new clean world. If i Insert my old save data this happens, hmm probably compatibility save issues, **still makes no sence to me why this happens only on 64bit win version**. I can still play the old save on 32bit with no multidrop screen issues. The save aint that old its from the begining of february or somewhat older. Just dont have the time to continue :(

Since the save is the key here I can give you the save and the config folder, cant say you will have luck reproducing it on linux, maybe.

btw Should this be closed since its probably save related?

**Comment by VlasovVitaly** [comment] 2016-03-01 15:40
Guess this is platform independent bug. Yes this is saved game related bug
and not a big deal. But it' s very interesting since it happens only on
64-builds. If you give your save i will test it.
Perhaps this really can be closed.
1 марта 2016 г. 18:33 пользователь "mutt3x" <notifications@github.com>
написал:

**Comment by mutt3x** [comment] 2016-03-01 15:55
[MEGA Save Files](https://mega.nz/#!egxjxJzZ!HwPUDtxN6dRbAVX76ri9iXcei2iSzB7xRk6cSYJo_ZQ)
Quite insane save... love playing slow, it kinda relaxes me.
i only savescummed once when i accidentally attacked a NPC. it seemed right.

**Comment by VlasovVitaly** [comment] 2016-03-02 10:50
Still can't to reproduse even with your saves on modern builds. May be this is only Windows 64 related bug.
Vote for closing.

**Comment by mutt3x** [comment] 2016-03-06 17:17
Closing...

**Comment by kevingranade** [comment] 2016-03-07 01:59
win64 only isn't grounds for closing, even a bug on a random weird platform like IRIX would be worth investigating, because platform-specific bugs often have undefined behavior at their root.

**Comment by mutt3x** [comment] 2016-03-09 20:18
hmm...
Updated from 4503 in which the bug was/is still present to the latest 4531 64bit
I cant reproduce this anymore.

Something somehow applied a remedy in between those builds. 4512, 4513 and 4514 seem possible...

**Comment by codemime** [comment] 2017-01-06 20:23
Does this still happen?

**Comment by Leland** [comment] 2017-08-24 02:55
Closing due to lack of confirmation, and only a single report (from an OP who appears AWOL). @mutt3x or anyone encountering this issue again, please either ping me here to reopen or simply make a new issue linking to this one.

**Closed by Leland** 2017-08-24 02:55 UTC
Labels: Bug, Confirmation Needed, Information / Interface, Windows
