### ISSUE TITLE
Inhaler has 0 charges when starting with asthma trait.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#40965] opened 2020-05-30 12:55 UTC
Inhaler has 0 charges when starting a new game with asthma trait. It should have 100.

I am using latest git pull on master branch at the time of writing this.

**Comment by anothersimulacrum** [comment] 2020-05-30 16:02
Duplicate of #40819

**Closed by anothersimulacrum** 2020-05-30 16:02 UTC
Labels: (S3 - Duplicate)
