### ISSUE TITLE
When working in more than one vehicle, resume work function behaves incorrectly

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38203] opened 2020-02-21 15:37 UTC
# Describe the bug

If the player is working in a vehicle and interrupts the operation (either by hitting '5' or being interrupted by external factors), then starts working in another nearby vehicle and tries to install a part, the game resumes the former task that was interrupted.

# Steps To Reproduce

1. Start installing a part in a vehicle and interrupt it before finishing.
2. Go to another nearby vehicle (haven't tried going out of range) and try installing a part (doesn't matter which).
3. The former interrupted work is resumed and the part installed in the first vehicle, with the log saying 'You resume your task'.

# Expected behavior

Either the game forgetting the work queue when working in another vehicle, or having the capacity of storing different work states in different vehicles.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12475-g7206b26 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Dacendeth** [comment] 2020-02-22 09:04
Same thing happens even if you work on the same vehicle, try installing a solar panel on one slot but get interrupted, decide to install it on a different slot and it'll put it where you first selected before being interrupted.

**Comment by olanti-p** [comment] 2020-09-07 07:49
Fixed by #43987 ?

**Comment by irwiss** [comment] 2022-09-04 13:28
Can't reproduce on current master

**Closed** 2022-09-09 00:18 UTC
Labels: <Bug>, Vehicles
