### ISSUE TITLE
NPC disappeared after telling them to do construction

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#34402] opened 2019-10-02 19:17 UTC
# Describe the bug

I told an NPC follower I'd just befriended to work on deconstructing the fences around my farmhouse, and when I went back toward him a minute later he had disappeared. Wasn't on the map, wasn't seemingly anywhere. I forgot to give him a toolbox as well. He's still alive, because his quest which I've since completed is still up, but I just can't find him. It's been like two ingame weeks now since I saw him.

# Steps To Reproduce

1. Blueprint fences to be deconstructed.
2. Tell NPC to work on constructions.
3. NPC seemingly disappears after leaving them offscreen.

# Expected behavior

Having some way of tracking NPCs, or for them not to disappear like this?

# Screenshots

![image](https://user-images.githubusercontent.com/35230199/66074459-26592980-e551-11e9-9729-713e9d371ffc.png)
My follower was at the top of my farm (circled) when I told him to work on construction. I went to the bottom of my farm (to set more fence deconstruction blueprints), and when I walked back up, he was gone from my view and not even on the map. There are no enemies nearby.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7542-ga5d33f6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Hair aka Rainbow [Hairs]
]

# Additional context

**Comment by anothersimulacrum** [comment] 2019-10-02 21:39
What does it say for their relative location in the `#` menu?

**Comment by DanteTorn** [comment] 2019-10-02 22:00
Oh! I didn't know this was a thing.
It seems he ran up into the city. It doesn't make sense that he's guarding up there when I told him to deconstruct my fences though.
![image](https://user-images.githubusercontent.com/35230199/66085062-1a2c9680-e568-11e9-9393-1317866f8125.png)
![image](https://user-images.githubusercontent.com/35230199/66085187-768fb600-e568-11e9-8b5d-1cafb95526cd.png)

**Comment by bobchaos** [comment] 2019-10-03 04:36
I dont' suppose you had an unfinished construction in town? Maybe something you got interupted while dismantling?

Also you should go talk to him, he may simply have abandoned you, NPCs can do that if they don't like you

**Comment by DanteTorn** [comment] 2019-10-03 16:17
When I found him, he was just stood in the middle of an alleyway and I'm sure there were no constructions to do in town, besides the fact I'm pretty sure you need to blueprint zone them.
He's dark green, which you can see in the screenshot, so he loves me at this point.

mlangsdorf mentioned this the not-dev Discord. My guess would be that because my NPC didn't have any tools to complete his task, it triggered this bug. I searched for the issue that dorf mentioned and didn't find anything, so whenever it does get made then this issue should probably get linked there.
![image](https://user-images.githubusercontent.com/35230199/66144815-7a234b80-e601-11e9-98a8-e44a753e124f.png)

**Comment by DanteTorn** [comment] 2019-10-03 16:49
Small update: I can't seem to replicate the bug. My follower does the job if I give him tools, and if he doesn't have any tools then he will walk over to the job for a second before seemingly canceling and following me normally.

**Comment by davidpwbrown** [comment] 2019-10-04 09:40
Them not being able to do the construction should just revert them to a normal state.
The bug is caused by them being reintroduced into the reality bubble - there is maybe one turn , when you are walking towards them, where the thing they are working on is not in the reality bubble, but they are, if they are in the middle of an activity on that thing, then it can cause some weirdness.

There are some ideas on how to fix this, perhaps just checking every turn if activity target is inbounds.

Either way - there is a fix for them reverting to dynamic NPC behaviour and running off to the nearest city in #34289 .

That wont fix them stopping the activity or having other weirdess when they re-enter reality bubble, but will fix the worst of the weirdness with them running away randomly.

**Closed** 2019-10-11 07:26 UTC
Labels: (S1 - Need confirmation), <Bug>, NPC / Factions
