### ISSUE TITLE
Unknown Recipient mission spawned two Hub 01 structures

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#50861] opened 2021-08-18 01:21 UTC
### Describe the bug

When I started the Unknown Recipient mission, I was given the coordinates of a location that was very far away from the refugee center, labelled Hub 01. On my way there, I stumbled upon another place, also named Hub 01, where I was able to turn in the FEMA data as if it was the real hub. Turning in the data did not update the quest marker.

### Steps To Reproduce

Not sure; maybe just try starting the quest again?

### Expected behavior

One of those Hub 01s shouldn't exist.

### Screenshots

![fakeHub](https://user-images.githubusercontent.com/51832925/129821222-ac71fbea-33fb-406e-b815-46d8c84658ef.PNG)
The location I was originally told to go to
![realHub](https://user-images.githubusercontent.com/51832925/129821224-9b73c1f1-fec1-44df-8baa-4a599ba70502.PNG)
The closer hub

### Versions and configuration

- OS: Windows 10
- Game Version: 9a10b0c
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Default

**Comment by PatrikLundell** [comment] 2021-08-18 07:12
It's a known artifact of the current system. "Unique" locations aren't (for various reasons), resulting in duplication of people and quests (and possibly some entanglement of these such that one instance partially affects another). The only in game way to resolve the quest is likely to find a duplicate of the refugee camp, get that quest, and turn it in to the hub01 referenced by the first instance, most likely resulting in that refugee center quest to go unfulfilled.
You can debug spawn the quest object to turn it in at the correct hub01 instance, although that will disable achievements (something you may or may not care about).

**Comment by KittyTac** [comment] 2021-08-18 15:56
> 
> 
> It's a known artifact of the current system. "Unique" locations aren't (for various reasons), resulting in duplication of people and quests (and possibly some entanglement of these such that one instance partially affects another). The only in game way to resolve the quest is likely to find a duplicate of the refugee camp, get that quest, and turn it in to the hub01 referenced by the first instance, most likely resulting in that refugee center quest to go unfulfilled.
> You can debug spawn the quest object to turn it in at the correct hub01 instance, although that will disable achievements (something you may or may not care about).

You can re-enable them in the "Game" tag in the debug menu.

**Comment by actual-nh** [comment] 2021-08-18 17:27
Oh. There actually is one possibly-new bug with this - shouldn't the mission have used the existing closer Hub01?

**Closed** 2023-06-15 17:49 UTC
Labels: <Bug>, Missions, Map / Mapgen
