### ISSUE TITLE
game crash when loading save file after updating game version (experimental version)

### ISSUE THREAD

**Issue by Xomikadze** [CleverRaven/Cataclysm-DDA#55120] opened 2022-02-05 07:30 UTC
### Describe the bug

Game crash when loading save file after updating game version. The world was created long ago.

### Steps to reproduce

1. I start the game
2. Trying to load my save file
3. Falling error

### Expected behavior

Error does not fall

### Screenshots

![image](https://user-images.githubusercontent.com/68762218/152632859-58a6f87c-826e-4d3c-915a-053b9fb929d9.png)

### Versions and configuration

OS: Windows 10
Language: ru
Game version: 7efd4f5

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8007586/crash.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8007588/save.zip)

**Comment by NetSysFire** [comment] 2022-02-05 08:29
Might be a duplicate of #55075

**Closed** 2022-02-06 00:10 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
