### ISSUE TITLE
Save can't load build 8932 due to historical content

### ISSUE THREAD

**Issue by aman3600** [CleverRaven/Cataclysm-DDA#30381] opened 2019-05-10 16:07 UTC
**Describe the bug**  
Historical content mod has an issue in martial arts that causes world loading to fail

**To Reproduce**  
Try to load the attached save on build 8932

**Screenshots**  
https://i.imgur.com/5JrZ9om.png

**Additional context**  

[Westland OMEGA.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3167278/Westland.OMEGA.zip)

**Comment by Zireael07** [comment] 2019-05-10 16:19
I believe it's a dupe of a reported issue, and fix incoming in #30376

**Closed by Zireael07** 2019-05-10 16:19 UTC
