### ISSUE TITLE
The bycicle's engine starts up.

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#28079] opened 2019-02-05 19:45 UTC
* Windows 10
*   Build 8502
*   Tiles

**What's wrong ?**  
Bycicle has no engine but a foot_crank and yet : 
![image](https://user-images.githubusercontent.com/41293484/52299262-4534fb00-2985-11e9-9c74-71a653964b4b.png)
Not only it's engine starts up but it's also humming.

**How to reproduce**
* Spawn a bicycle
* Start the bicycle
* Listen to the soft humming of it's engine

**Describe the solution you'd like**  
Well game should tell you something like "You reach for the pedals." or "You start pedaling." and it should either make a clacking noise or no noise.

**Additional context**  

A brief glance at the code showed that `"The %s's engine starts up."` should only be displayed for non muscle engine so I don't know where it's going wrong since foot_crank is define as a muscle engine in the jsons.

**Comment by Fractalyst** [comment] 2019-02-05 22:17
Well stop making them humming sounds and it wont make noise :+1:

**Comment by MyculplantKatze** [comment] 2019-02-06 01:09
you:"vroom vroom"
Zombies: "WTF silly human that is not a car!"

**Comment by GoLoT** [comment] 2019-02-06 07:39
And you can get the `the bycicle's engine fails to start` message sometimes. I didn't try to reproduce but I had it happen when trying to start a dynamo with a motorbike alternator.

**Comment by Zombiemanpig** [comment] 2019-02-06 12:37
> And you can get the `the bycicle's engine fails to start` message sometimes. I didn't try to reproduce but I had it happen when trying to start a dynamo with a motorbike alternator.

Maybe one of the foot pedals is broken and your foot slipped off before you were able to "start" the bike and your character didn't feel right making the noises 😆

**Comment by Epictyphlosion** [comment] 2019-02-06 19:04
Maybe the noises are caused by a card someone stuck in the back wheel? Lol

**Comment by WilliamtheCardboardBox** [comment] 2019-02-07 21:52
Really needs a fix.

**Comment by Treah** [comment] 2019-02-08 21:22
LOL im pretty sure this was done to try and fix the problem with the bike having negitive sound causing a crash. But not sure why it was fixed again...

**Comment by Fris0uman** [comment] 2019-02-10 12:15
So it seems that in Line 1974 of activity_handlers.cpp ` !veh->is_engine_type( e, "muscle" )` actually returns `true` for the bicycle.

**Comment by ifreund** [comment] 2019-02-11 00:28
Caused by #26967 as far as I can tell

**Comment by kevingranade** [comment] 2019-02-17 01:10
Fixed by #28222

**Closed by kevingranade** 2019-02-17 01:10 UTC
Labels: <Bug>, Vehicles
