### ISSUE TITLE
Unable to open keyboard to perform actions

### ISSUE THREAD

**Issue by SortaKindaSnek** [CleverRaven/Cataclysm-DDA#30350] opened 2019-05-09 20:47 UTC
**Describe the bug**  
Hitting the "back" button will not open the virtual keyboard

**To Reproduce**  
Install CleverRaven's version of CDDA on the google play store, hit the back button, and be unable to see the keyboard to perform actions

**Expected behavior**  
I expect the phones keyboard to show up like other versions, so I may perform advanced actions.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Samsung Galaxy J3 Duo
 - Game Version: Whatever the Google play version is
 - Graphics version: Tiles
 - Mods loaded: Any and all, mods loaded do not change the result

**Additional context**  
N/A

**Comment by ZhilkinSerg** [comment] 2019-11-28 21:49
Duplicate of #33781

**Closed by ZhilkinSerg** 2019-11-28 21:49 UTC
Labels: <Bug>, Controls / Input, Info / User Interface, OS: Android, SDL: Tiles / Sound
