### ISSUE TITLE
Segmentation Fault when melee attacked by NPC.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#34450] opened 2019-10-04 07:39 UTC
# Describe the bug
When an NPC attacks the player, the game crashes.
# Steps To Reproduce

Load the save provided, press '!' to disable safe mode, press 5 for seg fault.
You will spawn next to an angry NPC who will proceed to hit you with his crossbow.

# Expected behavior
Fer ta not to.

# Versions and configuration
 - OS: [Windows 10]
 - Game Version: [0.D-8190-gfe5c733]
 - Graphics version: [Tiles]
 - Mods loaded: [disable NPC needs, Modular Turrets]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3689456/config.zip)
[Perley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3689463/Perley.zip)

**Comment by Malkeus** [comment] 2019-10-04 07:40
Check discord #cataclysm-questions around 2:10AM CST for the conversation that sparked this issue.

**Comment by ZhilkinSerg** [comment] 2019-10-04 07:49
Duplicate of #34427

**Closed by ZhilkinSerg** 2019-10-04 07:49 UTC
