### ISSUE TITLE
Unnatural behavior in plant mutations.

### ISSUE THREAD

**Issue by MousePeace** [CleverRaven/Cataclysm-DDA#33375] opened 2019-08-19 21:33 UTC
Google translation is used, so the grammar may be strange.
Sorry if you don't understand.
I will try to communicate accurately.

In the “plant” mutation tree, there are two case.

# Describe the bug

1. I got a ”Plant(and Chloromorphosis)” mutation and consume liquid fertilizer, But amount of liquid fertilizer will not decrease.

2. I got a "Rooter" mutation and take off shoes on dirt,but absorption't nutrition while crafting.
("You sink your roots into the soil."text not outputted.)
*But it was output while reading, wait, etc.
*I'm sorry if it was a game specification. But according to the wiki it seemed possible.

# Steps To Reproduce

1. Got a ”Plant(and Chloromorphosis)” mutation.and drink liquid fertilizer.

2. Got a "Rooter" mutation and take off shoes on dirt,and Crafting action.

# Expected behavior

1. Each time you drink, it should be reduced by 1 quantity.

2.Since it meets the conditions and is still on the same tile, it will be able to root in the soil.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6421-gfd8e664 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    core - Dark Days Ahead [dda]
]

**Comment by alkemann** [comment] 2019-08-22 13:52
I tested and can confirm that drinking liquid fertilizer did quench my thirst but did not consume any liquid from the jug.

**Comment by alkemann** [comment] 2019-08-22 13:57
While unfamiliar with the root functionality, what I observe is while waiting for 5 or 30 minutes I do get the "You sink your roots into the soil", but I did not while doing a long craft. 

In neither case did my Hunger or Thirst actually improve.

Tested on master 2bda93b4da

**Comment by ipcyborg** [comment] 2019-08-24 09:50
For crafting activity ACT_CRAFT the "rooting" is disabled (`player_activities.json`):
```{
    "id": "ACT_CRAFT",
    "type": "activity_type",
    "activity_level": "MODERATE_EXERCISE",
    "verb": "crafting",
    "based_on": "neither",
    "refuel_fires": true
}
```

Probably this is an intended behavior? 
If not, it could be easily fixed by adding `"rooted": true` there.

**Closed** 2019-08-28 06:48 UTC
Labels: (S2 - Confirmed), <Bug>, Mutations / Traits / Professions
