### ISSUE TITLE
0.F is coming

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#42658] opened 2020-08-02 21:25 UTC
It's time for 0.F! This time I've taken it upon myself to get us on the originally proposed 6 month schedule!

#### What does this mean?
The release blockers are tracked in the [release project](https://github.com/CleverRaven/Cataclysm-DDA/projects/37).  Once these are addressed, we can proceed to release.
I've jumped on this to make it official as soon as possible, so there are still a couple features on the release blocker list.

#### What does this change?
We are in *String Freeze* now.
This means that any PRs that change any strings should not be merged, and will need to wait until after release.

* Going forward, only features on the release blockers project should be considered for merge.

- [x] Feature Freeze
- [x] Content Freeze
- [x] check migration of a 0.E save to 0.F and fix migration
- [x] String Freeze
- [x] Blockers cleared
- [x] Publish release candidate
- [x] Completed Changelog
- [x] Merged Translations
- [x] Merge final Ultica update
- [x] Update credits menu
- [x] Pick Release Name
- [x] Draft Press Release
- [x] Tag blessed commit
- [x] Post release announcement

#### Can I help?
If you know about any game-breaking bugs that are not listed [here](https://github.com/CleverRaven/Cataclysm-DDA/projects/37), please leave a comment with a link to the issue.

#### Describe alternatives you've considered
Wait for kevin to do it himself. He's a bit... busy at the moment so he's likely going to be mostly taking oversight duties (and probably the official release announcement) And we typically announce feature freeze rather late into a sort of "soft" feature freeze. This time I wanted to announce the feature freeze at the front, so we'll still have some stuff get merged but we're winding up to a release anyway.

**Comment by Hirmuolio** [comment] 2020-08-02 22:07
#40732 should probably be blocker too.

**Comment by Duck13Tales** [comment] 2020-08-02 22:39
It seems that the food stopped inheriting the nutrition from its components, as stated in #41929.

**Comment by Duck13Tales** [comment] 2020-08-02 22:56
Just tried in the latest experimental but it seems that the problem in #42377 is still a thing. There is a fix for this but this still isn't in the build and we need to apply manually. Just save a game at night, load the game, take a look at your warmth and then take a step, then see that your warmth went to abysmal levels.

**Comment by kevingranade** [comment] 2020-08-02 23:28
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/0-f-is-coming-soon/24344/1

**Comment by BrettKirkconnell** [comment] 2020-08-03 05:50
Using items with the lifting trait doesn't seem to be working correctly when working on vehicles. Even though I'm pulling around a deployed crane, often it will say I don't have the tool. It might be the case the game is looking for line of sight from the crane to the tile having the improvement added or removed.

**Comment by ZhilkinSerg** [comment] 2020-08-03 06:38
#### Useful lists:

- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=is%3Apr+is%3Aopen+no%3Alabel) that need to be triaged before `0.F`;
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3A%220.F+Content+Freeze%22+-label%3A%220.F+Feature+Freeze%22) that still can be merged before `0.F` (also includes untriaged pull requests);
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3A%220.F+Content+Freeze%22) that are in **Content Freeze** state and won't be merged before `0.F`;
- [pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3A%220.F+Feature+Freeze%22) that are in **Feature Freeze** state and won't be merged before `0.F`.

**Comment by ZhilkinSerg** [comment] 2020-08-03 06:41
In order to reduce backlog, we can started merging pull requests affected by feature and content freeze to `dev` branch (https://github.com/CleverRaven/Cataclysm-DDA/tree/dev). We will update this branch with changes from `master` and will merge it to `master` after stable `0.F` is out.

Following PRs were merged so far (list will be updated):

### August 3, 2020

#TBD

**Comment by Hulkninja** [comment] 2020-08-03 12:28
I'm not sure what bugs are considered "game breaking", but these ones sure do make playing gun-wielding ranged characters almost impossible: #42340 #42324 #42332 #42254 #42365 #42161

I've definitely encountered all but one of these bugs personally, most of them during the same run. Still have the save file, with a Marlin, a Mosin, and a couple of Glock 22's in the base, if needed.

**Comment by souricelle** [comment] 2020-08-04 02:54
IDK if it's game breaking but https://github.com/CleverRaven/Cataclysm-DDA/issues/42596 has been an issue since 0.E-2.

**Comment by misterprimus** [comment] 2020-08-04 04:03
> I'm not sure what bugs are considered "game breaking", but these ones sure do make playing gun-wielding ranged characters almost impossible: #42340 #42324 #42332 #42254 #42365 #42161
> 
> I've definitely encountered all but one of these bugs personally, most of them during the same run. Still have the save file, with a Marlin, a Mosin, and a couple of Glock 22's in the base, if needed.

I'm not sure if this is related to those bugs. Sure seems that way, so I didn't want to open a separate issue, but guns that take mags always seem to spawn empty and without mags. Just spawn a few soldier zeds and check their drops (including their holstered firearm): all empty and without mags. Only exception is weapons that take ammo directly like a Mosin, but some of those are bugged too and impossible to reload.

**Comment by qurvax** [comment] 2020-08-04 08:33
I'm very much sure I had looted at least an empty mag from a gun in Zed's holster. So there must be exceptions to this bug with dropped guns.

**Comment by misterprimus** [comment] 2020-08-04 13:07
> I'm very much sure I had looted at least an empty mag from a gun in Zed's holster in a couple of latest experimentals (2-3 days old). So there must be exceptions to this bug with dropped guns.

Have you ever looted a loaded handgun or other mag-accepting gun?

**Comment by Duck13Tales** [comment] 2020-08-04 15:37
The problem with guns spawning without magazines was fixed in some experimental versions ago. Please download the latest experimentals and try again.

**Comment by misterprimus** [comment] 2020-08-04 15:55
> The problem with guns spawning without magazines was fixed in some experimental versions ago. Please download the latest experimentals and try again.

I will, thanks for letting me know.

**Comment by misterprimus** [comment] 2020-08-05 03:39
> The problem with guns spawning without magazines was fixed in some experimental versions ago. Please download the latest experimentals and try again.

Here are my findings with latest experimental:
1. Holstered handguns are still spawning with not even a mag.
2. Non-holstered weapons DO spawn correctly with a mag (if one applies), but there is something wrong with the ammo spawns: ammo either spawns fully loaded (30/30 rounds) or with 0 rounds (nothing inbetween). This happened 3 times in a row so I don't think it's a coincidence.
3. Mosin is still bugged when fired:
![image](https://user-images.githubusercontent.com/45959491/89369210-7510ac00-d6ab-11ea-9c0a-d2651c449106.png)
4. Mosin's "clip" appears to be useless and unusable with the Mosin as it doesn't seem to be compatible with it, but the Mosin does at least take the 54mmR ammo directly.
![image](https://user-images.githubusercontent.com/45959491/89369274-a38e8700-d6ab-11ea-835a-810dfc0874ab.png)
5. Still getting this on-load after killing a bunch of soldier zeds who drop holsters:
![image](https://user-images.githubusercontent.com/45959491/89369316-c620a000-d6ab-11ea-8148-5345a44406a7.png)

**Comment by Duck13Tales** [comment] 2020-08-05 04:24
Cool!

But I think that then it would be better to report this if there is any existing topic about this or then open a new issue about this problem if needed.

Reserve this one only to at most report the bugs.

**Comment by misterprimus** [comment] 2020-08-05 05:05
> Cool!
> 
> But I think that then it would be better to report this if there is any existing topic about this or then open a new issue about this problem if needed.
> 
> Reserve this one only to at most report the bugs.

OK I made two bug reports for those issues.

**Comment by GGgatherer** [comment] 2020-08-10 14:51
Why aren't issues about item duplication on load in the list? It still happens in some cases.

**Comment by KorGgenT** [comment] 2020-08-14 19:56
@GGgatherer can you list the specific issues please

**Comment by Alex-Folts** [comment] 2020-08-28 22:11
This one https://github.com/CleverRaven/Cataclysm-DDA/issues/43263 and all related i guess game breaking too.

**Comment by gc2020x4** [comment] 2020-09-03 18:28
@kevingranade @KorGgenT 
Kevin Grenade must leave the project forever.

**Comment by chace99** [comment] 2020-09-05 06:20
@kevingranade @KorGgenT 

We are the Grey Committee. 

Cataclysm started as great Community Project. But recent events indicate that normal and healthy relationship between Community and Developers are lost and development going nowhere. Main reason of this is Kevin Grenade.

Kevin Grenade, current Project Leader deemed exclusively rights on everything in Cataclysm, violating project license and intellectual honesty. 

He does not respect community opinion and opinion of his own development team alike. Reasoning with him became pointless long time ago. A lot of people suffered or left project because of his attitude and his decision making. This list includes contributors, content makers and players alike.

Worse of all that project development start going with questionable ways at best. Instead of proper and logical decision making changes start becoming more and more chaotic and subjective. Game becoming a mess.

So we are decided that time for compromises has passed. The Grey Committee was created to fight back.

Our Manifesto is simple:
1) Kevin Grenade must leave the project forever.
2) New Development Leader must re-establish normal relationship between Development Team and Community.
3) All bans since beginning Kevin Grenade leadership must be revoked.

This goals are not negotiable and can be considered as our ultimatum.

To achieve our goals, we will engage Kevin Grenade and ones who blindly supports his behavior in a various ways of informational and psychological warfare.

We are not going allow some false dictator to steal our project and reduce it to dust.

«In the struggle you will gain your rights»
Grey Committee.

**Comment by misterprimus** [comment] 2020-09-20 07:05
This is a major reloading bug that makes ammo mags disappear when inventory is full and reloaded gun is being wielded: https://github.com/CleverRaven/Cataclysm-DDA/issues/44110

**Comment by dom4op** [comment] 2020-09-24 11:44
I didn't find the minifreezer bug in the 0.F blockers list. The bug is haunting me even in the current 0.E-2 stable. Are there any plans to solve this issue before the next release?
https://github.com/CleverRaven/Cataclysm-DDA/issues/34316
https://github.com/CleverRaven/Cataclysm-DDA/issues/39051
https://github.com/CleverRaven/Cataclysm-DDA/issues/36401
https://github.com/CleverRaven/Cataclysm-DDA/issues/38353
What makes it even worse is the fact that area coolers are unreliable at best(more details here https://www.reddit.com/r/cataclysmdda/comments/iyv6nc/people_playing_0e2_how_do_you_preserve_your_food/), leaving the player with no way to keep food frozen for extended periods of time.

**Comment by Xpyder** [comment] 2020-10-09 05:46
Wearyness is broken #44662

**Comment by kevingranade** [comment] 2020-11-03 12:27
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/fertilized-unfertilized-egg/25149/2

**Comment by Xpyder** [comment] 2020-11-10 04:48
UPS welder gets infinite battery #45330

**Comment by anothersimulacrum** [comment] 2020-12-04 21:01
For when we get to checking save migration:
Here's someone who knows all recipes, has all items spawned at their feet, and is in a microlab from 0.E
[stable.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5645445/stable.zip)

**Comment by leycec** [comment] 2020-12-09 06:11
[Token Gentoo overlay maintainer here](https://github.com/leycec/raiagent). Nobody rightfully cares, but it should be noted that the most recent stable release (`0.E-2`) fails to compile under `clang`. This has (of course) since been resolved by #39763, but that still leaves `0.E-2` fairly broken with respect to compilation. What I'm saying is... we're all *really* looking forward to `0.F`!

Thanks for the many endless hours of volunteer dev work, all. Everyone here is a mutated zombie-massacring superstar.

**Comment by anothersimulacrum** [comment] 2020-12-09 06:22
If something like that comes up for 0.F, if you're early enough we can probably backport it.
I suspect the same thing would have happened with clang12, but luckily we have people on Mac who have that and fixed it (https://github.com/CleverRaven/Cataclysm-DDA/pull/45657).

**Comment by ZhilkinSerg** [comment] 2020-12-09 08:05
I am still open for `0.E-3` - just didn't have time for that.

**Comment by leycec** [comment] 2020-12-10 00:49
Absolutely no worries. Since `0.E-2` compiles fine under the most prevalent compiler, <sup>...yup, still gcc</sup> most of us would probably rather those precious dev hours focus on the push forward to `0.F`. Time is the scarce volunteer resource that we're all min-maxing here. :clock1130:

**Comment by l29ah** [comment] 2020-12-15 23:36
> If you know about any game-breaking bugs that are not listed here, please leave a comment with a link to the issue.

https://github.com/CleverRaven/Cataclysm-DDA/issues/39495
https://github.com/CleverRaven/Cataclysm-DDA/issues/37747
https://github.com/CleverRaven/Cataclysm-DDA/issues/37102

**Comment by misterprimus** [comment] 2020-12-16 00:42
I don't know if these are "game-breaking" or "bugs" per se, but:

1. Occasionally, after an update, I will go to load the game and I'll get some sort of "too heavy for pocket" or "not enough room" error and the item in question disappears. Not sure if these are bugs or simply changes resulting from JSON audits. However, I think the item should drop, NOT disappear when this happens and shouldn't result in an error.

2. I'm always getting "zombie tried to step here, but already occupied by slime" error around research facilities. Not sure if there are any actual effects from this, but why isn't this being done silently in the background? Should be as simple as doing a check before letting someone step somewhere/appear somewhere, but maybe I'm not understanding something.

**Comment by KorGgenT** [comment] 2020-12-16 01:26
@misterprimus wait a turn and see if the missing item drops to the ground. that is what is supposed to happen.

**Comment by misterprimus** [comment] 2020-12-16 01:28
> @misterprimus wait a turn and see if the missing item drops to the ground. that is what is supposed to happen.

It was a soldering iron with a battery compartment mod and a car battery in it. It was gone. I walked around for an ingame minute looking for it. Looked on floor (V), in inventory, even in nearby car cargo areas. GONE.

**Comment by PatrikLundell** [comment] 2020-12-17 11:18
- If you know about any game-breaking bugs that are not listed here, please leave a comment with a link to the issue.
[Traceback Activity ACT_VEHICLE: vehicle not found #44311](https://github.com/CleverRaven/Cataclysm-DDA/issues/44311) is usually just annoying, but can be fatal (See Edit 2).

**Comment by NoahGoldFox** [comment] 2021-01-16 13:01
Is 0.F near and if not is it a good time to make a PR that just adds some objects?

**Comment by ZhilkinSerg** [comment] 2021-01-16 13:10
You can create PRs regardless if stable release nearness.

**Comment by NoahGoldFox** [comment] 2021-01-16 13:14
But what about content and feature freeze?

**Comment by PatrikLundell** [comment] 2021-01-16 13:41
You can make the PR regardless. Contents freeze hasn't been marked yet, but even if the PR isn't processed in time for inclusion in 0.F, that SHOULD not result in it being ignored completely. It SHOULD be evaluated after 0.F if it didn't make in before 0.F. However, don't be surprised if there is no feedback whatsoever from the core team (the only one I've seen on one of mine is that the assassin bot's stale marker was removed).

I interpret "feature freeze" to mean that larger changes that affect a lot of things won't be processed until after 0.F, while small improvements or additional objects that are just "more of the same" (from a technical perspective, not game play) are still candidates for being considered. I'd expect they won't be when contents freeze happens, though.
Note that this is my interpretation of the meaning of the states: I haven't seen any official definition.

**Comment by actual-nh** [comment] 2021-01-16 14:14
String Freeze: Does this include debug/error strings, or is it only for strings that need translation?

**Comment by ZhilkinSerg** [comment] 2021-01-16 14:19
translations only

**Comment by ifffrt** [comment] 2021-01-22 03:32
https://github.com/CleverRaven/Cataclysm-DDA/issues/460

Can we add this to the tracker? This can be either very annoying or game-breaking depending on your playstyle. I have had a Brigitte LaCroix getting mauled to death by a dog and some normal zeds because I left her outside in a cleared out neighborhood for 30 minutes to do something else I did not want her to get involved in.

**Comment by Night-Pryanik** [comment] 2021-01-30 15:20
Judging by the merging of only (well, mostly) bugfixes, I suppose now we're at content freeze? Or maybe even further?

**Comment by PatrikLundell** [comment] 2021-01-30 15:29
I assume the crucial world here is "mostly". Content freeze should be the boundary into the strict "only" territory, although it can be preceded by a gradually shrinking of the scope of the non bug fixing changes, which seems to have been going on for quite some time.

**Comment by actual-nh** [comment] 2021-02-04 00:18
Critical: #47096 (which fortunately has a PR to correct it)

**Comment by KorGgenT** [comment] 2021-02-07 06:52
Hey everybody it's been quite a long road but we're in single digit blockers so we are officially in a full content freeze! This means that content PRs will mostly be stalled except for mods. Mods will likely accept PRs all the way up to string freeze.

**Comment by KorGgenT** [comment] 2021-02-07 06:54
Speaking of, it would be nice to have a couple nice candidate 0.E stable world saves to check the migration.

**Comment by actual-nh** [comment] 2021-02-07 15:49
> Speaking of, it would be nice to have a couple nice candidate 0.E stable world saves to check the migration.

Long-term, it would be nice to have a collection of such (including 0.E, 0.E2...) to check for changes as in #45326/#47269.

**Comment by actual-nh** [comment] 2021-02-13 15:45
#46364? It is in the 0.F milestone, but not the project, which is confusing.

**Comment by actual-nh** [comment] 2021-02-14 18:56
> Speaking of, it would be nice to have a couple nice candidate 0.E stable world saves to check the migration.

For one, [see above](https://github.com/CleverRaven/Cataclysm-DDA/issues/42658#issuecomment-739017977) - from anothersimulacrum.

**Comment by GGgatherer** [comment] 2021-02-20 13:05
> so we are officially in a full content freeze!

should probably (further)update first post because it still states "We are in Feature Freeze now." despite content freeze checked in checklist

**Comment by kevingranade** [comment] 2021-02-21 20:12
Should have done this sooner, but I was super busy recently, we are in string freeze!
Translators, if you've been holding back (you probably haven't), feel free to barrel ahead into the shining future of 100% translated, we'll stop stepping on your toes now.

**Comment by actual-nh** [comment] 2021-02-21 20:47
Someone might want to update the PR to state that we're in String Freeze, as well as checking off the box.

**Comment by actual-nh** [comment] 2021-02-21 20:52
Question: Are PRs that would "violate" string freeze (ones changing translated strings) going to get marked Content/Feature Freeze, or is there a 0.F String Freeze tag needed? If the latter, altering `.github/stale.yml` is desirable.

**Comment by Tamiore** [comment] 2021-02-23 12:59
Is tailoring overhaul ( https://github.com/CleverRaven/Cataclysm-DDA/projects/25 ) included in 0.F blockers?
As of a couple of days ago it was still stuck in super-awkward state where there was no rime or reason to what can be crafted solely out of 'rags', what solely out of sheets, and required cotton patches or sheets interchangeably, etc.

**Comment by KorGgenT** [comment] 2021-02-24 01:17
> Is tailoring overhaul ( https://github.com/CleverRaven/Cataclysm-DDA/projects/25 ) included in 0.F blockers?
> As of a couple of days ago it was still stuck in super-awkward state where there was no rime or reason to what can be crafted solely out of 'rags', what solely out of 'sheets', and what out of cotton patches or sheets interchangeably, etc.
> 
> P. S. The reason I'm asking is that I'd be willing to do some (.json level) standardization if it's a blocker.

definitely not. afaik the person working on it dropped it halfway through, and anything "overhaul" is 6 months too late to make it into 0.F anyway.

**Comment by Tamiore** [comment] 2021-02-24 03:41
>definitely not. afaik the person working on it dropped it halfway through, and anything "overhaul" is 6 months too late to make it into 0.F anyway.

Understandable.

It just rubs me the wrong way that long underwear top is completely different from long underwear bottom in both  ingredients and crafting time.

**Comment by actual-nh** [comment] 2021-02-24 15:44
BTW, we are now at 25 total non-draft PRs that are none of Feature/Content/String Freeze, some of which may be considered draft even if not labeled as such.

**Comment by actual-nh** [comment] 2021-03-11 14:56
Could #42845 be added to the project?

**Comment by Fosheze** [comment] 2021-03-11 18:19
> Could #42845 be added to the project?

I second this. Considering stable versions are normally played by new players, having a mechanic that kills them without them knowing the cause and having no recourse to stop it is going to be incredibly discouraging.

**Comment by KorGgenT** [comment] 2021-03-11 18:20
We're in string freeze, and it appears to me that this bug will be fixed by adding new strings.

**Comment by Fosheze** [comment] 2021-03-11 18:30
> We're in string freeze, and it appears to me that this bug will be fixed by adding new strings.

Attacking between Z-Levels could be disabled for stable or only enabled when 3D FOV is enabled. After release it could be reenabled so that this issue can be fixed. As it is this is really unintuitive without 3D FOV enabled anyways.

Either that or always show the creature name if it is attacking from a different Z-level regardless of weather it can be seen or not. That way it would at least give the players a clue about what is attacking them.

**Comment by ZhilkinSerg** [comment] 2021-03-11 18:55
Attacks between Z-levels should already be impossible when 3dfov is off.

**Comment by Fosheze** [comment] 2021-03-11 19:28
> Attacks between Z-levels should already be impossible when 3dfov is off.

Apparently this is not the case.

>I have got a lot of damage from "unknown enemy" or something like that. After couple of minutes with debugger, i realised, it was a hornet from a different z-level. For me it was like bugged invisible enemy, without triggering safe mode, etc. Save was almost ruined, but i managed to save-scum it to find out whats happening. I think, this should be disabled until its will be possible for player to attack through z-levels too, see them on minimap, trigger safe-mode, etc.

>Just tried experimental fov, it works as expected, but minimap is not informative in that case. Maybe it would be nice to show them as triangles to also show if enemy is above or below player z-level

Also see wapcaplets testing in that issue where they were still being attacked after disabling experimental 3d fov.

**Comment by actual-nh** [comment] 2021-03-11 19:34
> We're in string freeze, and it appears to me that this bug will be fixed by adding new strings.

How about automatically turning on 3d FOV if an enemy on a different Z-level is about to attack?

**Comment by actual-nh** [comment] 2021-03-11 19:39
> Attacking between Z-Levels could be disabled for stable or only enabled when 3D FOV is enabled. After release it could be reenabled so that this issue can be fixed. As it is this is really unintuitive without 3D FOV enabled anyways.

Aside from minimap problems (see above), what else would be objectionable about enabling 3D FOV by default?

**Comment by Fosheze** [comment] 2021-03-11 19:52
> > Attacking between Z-Levels could be disabled for stable or only enabled when 3D FOV is enabled. After release it could be reenabled so that this issue can be fixed. As it is this is really unintuitive without 3D FOV enabled anyways.
> 
> Aside from minimap problems (see above), what else would be objectionable about enabling 3D FOV by default?

I seem to remember kevin was working on a long term PR to fix a few bugs but I can't find it anymore merged or not. All I can find that's still in progress on 3D FOV are #22620 and #44497which are both pretty minor. I haven't played with it myself so I wasn't aware that it was even out of the early experimental phases. I still don't know that it would be a good idea to make something like that default right before release though.

**Comment by actual-nh** [comment] 2021-03-11 19:54
> I seem to remember kevin was working on a long term PR to fix a few bugs but I can't find it anymore merged or not. All I can find that's still in progress on 3D FOV are #22620 and #44497which are both pretty minor. I haven't played with it myself so I wasn't aware that it was even out of the early experimental phases. I still don't know that it would be a good idea to make something like that default right before release though.

Yes. Sounds more like it would be best to block the attacks for F0, then fix minimap and other bugs before making it default-on for F1.

**Comment by GGgatherer** [comment] 2021-03-12 10:00
> 
> 
> Attacks between Z-levels should already be impossible when 3dfov is off.

#47980 

I'm always playing with 3dfov off and it is happening constantly.

**Comment by actual-nh** [comment] 2021-03-15 00:45
> > Attacks between Z-levels should already be impossible when 3dfov is off.
> 
> #47980
> 
> I'm always playing with 3dfov off and it is happening constantly.

Do you frequently have debug mode on?

**Comment by anothersimulacrum** [comment] 2021-03-15 01:18
I can't imagine anyone does, it's super spammy.

**Comment by actual-nh** [comment] 2021-03-15 02:38
> I can't imagine anyone does, it's super spammy.

Blink. I was just considering doing a PR to turn it on (and the debug menu guilt trip off) depending on the name of the character (containing "Debug" or equivalent). Does it do popups in tiles mode, or what? (I use curses.)

**Comment by PatrikLundell** [comment] 2021-04-18 08:23
As this now is the only remaining "In progress" entry, I suspect this means the "Blockers cleared" checkbox can be filled in.

**Comment by actual-nh** [comment] 2021-04-18 23:53
> As this now is the only remaining "In progress" entry, I suspect this means the "Blockers cleared" checkbox can be filled in.

There are several "Awaiting triage", however; do a search for 0.F as a milestone.

**Comment by actual-nh** [comment] 2021-04-23 23:47
A source for some 0.E saves that seem to be having problems: #48621.

**Comment by actual-nh** [comment] 2021-04-28 01:31
#47887 has resulted in multiple other particular bugs requiring patch-type fixes. It should definitely be a 0.G delayed blocker IMO - if not a blocker for 0.F, which would be reasonable.

**Comment by actual-nh** [comment] 2021-05-04 23:00
#36900 needs moving back to being a 0.G delayed blocker, BTW (currently down as a full blocker due to being "fixed" by mistake and restored as an issue).

**Comment by actual-nh** [comment] 2021-05-06 18:08
#28012 - as at least partially an accessibility issue, at least a 0.G delayed blocker?

**Comment by reinerh** [comment] 2021-05-19 18:29
In case this has been overlooked: #48875

**Comment by Anaglyphic** [comment] 2021-05-19 19:15
Sorry for the book, I can't think of concise way to address them all.

Controls - since I have a captive audience - every keyboard has &GT an &LT, and the variances are maddening anyway! Arrow keys work here but not there, PgUp/PdDn most places but not all, \> and \< are for lateral on this menu but columnar on this other?! I beg you guys for _some_ consistency. For 0.F and any hope of new people once COVID "ends" and life resumes. You know it matters. Can't you make a defacto universal control standard for the non-shell/non-linux players, and then they can map to what they want? Or even a controls choice on the Options menu, set A set B, something. Anything.

re: the crossing z-level attack thing that's supposed to be impossible, yea someone tell the code this because checkouts from experimental-22 and beyond  _(plus a manual edit for the washing that bugged me that Roy fixed_ (#48863) _- all had rear it's headt? That I patched manually since it's one line and I could not figure out cherry-pick (I guess you can't git cherry-pick until it's commited? Maybe I am supposed to pull from his personal clone?)_ Well whatever now I saw his post-experimental-33 9488256452d759094dbf58e259638f4f9a658fd4 over here https://github.com/RoyBerube/Cataclysm-DDA/releases/tag/cdda-experimental-2021-05-17-2350 has both washing and raw-jerky in it, I'm building that right now.

As for leaving debug on for 0.F-dev, meh it's not _that_ spammy. If it'll help I'm glad to.

One thing I needt to ask - feel free to make a WHAT WE NEED thread is this for "us" types or "them" types? There's tons of dumb crap, for example, mapgen stuff "_Bad and_spawn(mon_zombie_type, #, X,Y)"_ and "_Could not find a good starting place for character"_, inventory management like pockets/containers sizing issues _"tried to put an item (some_object, amount 1) in a container (container) that cannot contain it"_, as well as the common-these-days _"volume exceeds capacity (higher > lower)"_ from the _modifier when you manipulate nested items, and the like. The magazine-as-a-pocket thing that bolt-action and direct-load weapons expose like primus said above, etc.

I can't imagine you want to be notified of this junk. You're all quite aware of them. Maybe not everyone everything but the talent in this one thread has probably 99% of them in their mind.

But what about specific weirdnesses? The kind that bring up logistics questions like:  a STR 20 character picking up a v6 car engine manually and then wielding a weapon w/o having to drop it?! And he _has_ the volumetric capacity but of course not the weight capacity to store it. And relative_encumbrance() be damned, but you can see what it throws a pop-up _"volume exceeds capacity (8500ml > 3000ml)"_,  somehow this escaped and had to be caught by the error handler? Woof.

So again, happy to play 0.F-dev with debugging enabled, for now and hope to trigger the z-level thing w/o forcing it w spawns, and I'll do a lot of loading old saves to see if I can re-trigger that one too... that one I'm convinced it a pre-pockets/post-pockets thing.

**Comment by actual-nh** [comment] 2021-05-21 21:58
#36635 for 0.G delayed blockers?

**Comment by kevingranade** [comment] 2021-06-24 00:40
Generated a 0.E save with every item spawned, then loaded it with current experimental.  It generated a handful of load errors, but they were all either debug items, abstracts, or items obsoleted before 0.E, so we're GtG.

**Comment by kevingranade** [comment] 2021-07-03 06:56
IT'S HERE!

**Closed by kevingranade** 2021-07-03 06:56 UTC
Labels: Organization
