### ISSUE TITLE
Yugg shooting at oversized wasp causing crashing EOC mutate

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#78629] opened 2024-12-17 17:16 UTC
### Describe the bug

Yuggs mutation shot on wildlife is triggering something it shouldn't

### Attach save file

[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/18169121/Zakhadia_BigCity-trimmed.tar.gz)

### Steps to reproduce

Load save, walk/run north to so that you don't get killed by the wasp but otherwise wait for yugg to shoot at wasps and it'll crash

### Expected behavior

To not crash

### Screenshots

![image](https://github.com/user-attachments/assets/191c4068-4648-4ff2-a5ef-2c1baf662d24)
![image](https://github.com/user-attachments/assets/0e54cc87-bc04-4e7c-aa17-a96eca2d31e1)
![image](https://github.com/user-attachments/assets/8d3cfe5e-3fde-457c-8ec1-3f7270afa274)

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 32e2b3c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment] 2024-12-17 17:36
Duplicate of #78481

**Closed by Procyonae** 2024-12-17 17:36 UTC
Labels: (S3 - Duplicate)
