### ISSUE TITLE
Weather reader "Feels like temperature" is bugged

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21227] opened 2017-06-12 14:47 UTC
As the title says, while standing still and while on a vehicle going 49mph, the "Feels like" temperature is way out of proportion. Probably a simple equation error. The temperature in the first picture reads -225*F standing still and the second picture going 49mph shows -2985*F lol.

First picture standing still:

![capture](https://user-images.githubusercontent.com/24307650/27039572-48d3034c-4f5c-11e7-96ca-80af1dc40574.PNG)

Second picture going 49mph on bike:

![capture2](https://user-images.githubusercontent.com/24307650/27039574-4b6ff330-4f5c-11e7-9485-ece59da86cf7.PNG)

**Comment by Leland** [comment] 2017-06-12 14:49
Duplicate of #20646, but we needed validation that it still occurred, so marking as such.

**Closed by Leland** 2017-06-12 14:49 UTC
