### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DvergarMrachnoy** [CleverRaven/Cataclysm-DDA#45210] opened 2020-11-02 19:03 UTC
Since I just registered on GitHub, I can't explain it constructively (IMHO). The essence of the problem: an error occurs (stopping the process) when searching for refugees using the terminal in the shelter.

**Comment by wapcaplet** [comment] 2020-11-02 22:38
Duplicate of #45209

**Closed by wapcaplet** 2020-11-02 22:38 UTC
