### ISSUE TITLE
Game freeze when telling NPC to construct woodchip floor in basecamp 

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#41220] opened 2020-06-10 21:02 UTC
# Describe the bug

I ordered my NPC to build a woodchip floor, then the game stalled and froze. No errors, no crashed, just eternal lag. I had some performance issues around my basecamp for some time prior to this due to sheer amounts of loot, but nothing too serious. 

# Steps To Reproduce

1.  [Load the attached save backup.](https://github.com/CleverRaven/Cataclysm-DDA/files/4761172/Huffman_checkpoint7.zip)
2. Tell NPC to make woodchip floor outside 
2.1 Open Zone manager (Y)
2.2 Add new zone (A)
2.3 Choose "Construction: Blueprint" (4)
2.4 Choose"Make Woodchip Floor" (never mind that requirements are red)
2.5 Designate a one tile zone on the snow near the player, save changes 
2.6 Talk to NPC standing next to the player (Leila 'Charm' Weir, prisoner)
2.7 Talk about current activity (i), then do construction work (d) 
3. Wait 5 minutes
4. Game freezes 

# Expected behavior

Game is not freezing and NPC works on woodchip floor if able. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by Aivean** [comment] 2020-11-21 03:57
Can somebody please recheck this issue in latest experimental?

I'm noticing a tiny bit of lag every 5-10 in-game minutes, but not even close to the scale described in the issue. 

The lag comes from `inventory::add_item` I'll look into it anyway, but I'm not sure if I'm missing something.

**Comment by esotericist** [comment] 2020-12-14 04:37
loading this in a recent (as of a couple days ago) debug build, my experience is that during the process of relocating the splintered wood for the construction task, performance plummets viciously.

turns which were going by pretty close to instantly previously (again, actual debug build, not merely with debug symbols) were taking up to three seconds, and it was taking several turns to move each individual splintered wood.

once all the splintered wood was moved and the npc moved on to a different task, things resumed being swiftly responsive.

the impact here is substantial, and i don't experience the same degree of slowdown having the same NPC in the same save moving items around from sorting loot. i think there's definitely an issue in the collecting-stuff-for-construction task.

**Comment by esotericist** [comment] 2020-12-14 04:42
a key factor to the reproduction process here that needs to be noted is: starting a construction for the woodchip floor requires digging a pit first, which the system helpfully automatically handles before moving on to the floor construction. the problematic behavior will not be exhibited until after a pit is made, and the NPC decides to collect the materials to actually construct the floor.

**Comment by Aivean** [comment] 2020-12-19 23:34
Ok, I finally managed to reproduce it:
![image](https://user-images.githubusercontent.com/2865203/102701776-61f01a00-420f-11eb-964e-53ca4ecef6a6.png)

The game indeed becomes frozen. Seems that the issue is with temporary crafting inventory copying items.

**Comment by Aivean** [comment] 2020-12-22 05:29
Ok, so I did a bit of debugging, and there are two problems here.

First, there is an actual freeze (infinite loop) that is caused by `ACT_FETCH_REQUIRED` failing this check:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7cc4088180852b4034ffb6256b1558c75b2103fc/src/activity_item_handling.cpp#L2739-L2749

It's trivial to fix, I'll submit PR soon. 

---

And there is a second issue, the NPC construction AI performance.  The issue lies in `are_requirements_nearby` using `inventory` to validate requirements, which is incredibly slow:
![image](https://user-images.githubusercontent.com/2865203/102852111-5862df80-43d2-11eb-8e23-c45c2c554f4d.png)

I'm evaluating some ideas on how to address this.

**Closed** 2021-01-01 02:44 UTC
Labels: <Bug>, Code: Performance, Crafting / Construction / Recipes, NPC / Factions
