### ISSUE TITLE
Can't reload the Marlin 39A

### ISSUE THREAD

**Issue by thehdmicord** [CleverRaven/Cataclysm-DDA#43395] opened 2020-09-02 06:21 UTC
When I try to reload my Marlin 39A, I get a message saying "Can't reload the Marlin 39A" despite having .22 ammo in my inventory.

# Steps To Reproduce

1. Acquire Marlin 39A and .22 rounds
2. Attempt to reload it
3. You will receive the message "Can't reload the Marlin 39A"

# Expected behavior

The gun should be able to load the .22 ammo, since it is a lever action rifle that accepts .22 and does not use magazines

# Screenshots

![image](https://user-images.githubusercontent.com/69670155/91938826-4b52a100-ecba-11ea-83ff-6ad25c1b3cd3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5366-g7f91078 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bootleg Walkers [Bootleg_Walkers],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    SpeedyDex [speedydex],
    Mutation Changes [Mutation_Changes]
]

# Additional context

N/A

**Comment by ZhilkinSerg** [comment] 2020-09-02 08:18
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/42340

**Closed by ZhilkinSerg** 2020-09-02 08:18 UTC
