### ISSUE TITLE
Faction money.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12539] opened 2015-06-03 05:06 UTC
I brought up in #12462 that we're approaching the point where having factions issue their own money is starting to look like a good idea, and it's probably not too far off that it's a necessity which sparked a bit of discussion so I'd like to open this to avoid flooding acidia's PR thread with discussion about it and to have the discussion and conclusions stick around once that PR is closed.

First, definition, a currency isn't a trade good that holds its value well, like ammunition, medicine, or food, that's a commodity.  If it's universally desirable enough it can become a de-facto currency, but that's not what I'm talking about here.  What I'm talking about is actual money of some kind that has no worth other than the fact that the issuer (faction in this case) says they'll honor it.

In-game rationale:
Factions would want to issue a currency for several reasons.
- It enables trade by letting traders effectively exchange goods even if they don't have anything the other specifically wants.
- Traders also want to be able to buy and sell goods and services without having to match up a specific trade.
- It establishes a sense of normalcy for the survivors, we're used to using money, and I imagine being able to do so after the cataclysm would be comforting.
- It lets the faction control trade, and gives them a means of raising capitol via inflation.  For example, if they can convince their shopkeepers to accept it, they can pay wanderers to do various tasks with it without having to worry about tracking down something the wanderer specifically wants to buy.

Game design rationale:
- It drives home the fact that the old civilization is really gone, the old money is now worthless except as kindling.
- Currency exchange promotes the player becoming invested in a particular faction because it's generally going to be the only place they can spend the faction currency.
- Veracity, this is simply something that would happen as new organizations reassembled themselves, see the in-game rationales.
- Just having a universal currency is lazy, why would random raiders or warring cities take each other's money?  In reality it takes a lot of work to 
- Makes trading more interesting when moving between factions, you do have to switch to barter, possibly liquidating your faction funds in return for things the other factions would want.  If we develop this far enough the player could make a living just trading between settlements, which would be pretty damn cool.

Things faction money needs to be:
- Light and not bulky.  Also stackable (conserving inventory letters).
- Reasonable for the faction to issue (gold-pressed latinum is probably out, more likely pieces of paper with the faction leader's signature or similar).
- Actual items, there's no reason for it not to be something you can interact with normally, you should be able to lose it, hide it, get mugged for it, get so much you can't carry it all...

Nice to haves:
- Flavorful (but not silly, sorry, no bottlecaps).
- Have some story, maybe the player can retrieve a printing press or similar to help combat forgery, maybe the player can be the reason they need to fight forgery...
##

**Comment by jokermatt999** [comment] 2015-06-03 11:52
Very good idea. I think some sort of basic notes or a ledger with the merchant works better than just $. When we get interaction with raiders in, I'm thinking their currency would be a lot less stable, encouraging taking goods rather than an IOU. On the other hand, if the Old Guard and the Free Merchants are working well together, I could see the player brokering a stable exchange rate or trade route.

**Comment by wmafie** [comment] 2015-06-03 12:49
Hi first timer here! ;) [Been playing cataclysm for 2 years++ though]

I agree that warring factions would not want other factions' money. What about factions that are friendly, or trading with each other? I am unsure if this is in the works. If inter faction trading does exist, instead of just liquidating money to barter, maybe it is possible to use another faction's money.

For example Faction A is on good terms with Faction B. You hold currency of Faction A. If you meet Faction B merchant, they MAY be willing to accept the currency of Faction B. This is logical as Faction B may be able to use the currency to trade with Faction A later on. And here's the catch. It may not be a 1:1 conversion. The value of another faction's currency varies according to a combination of follows:

1) Relations between the two trading factions. (Note that even if two factions secretly hate each  other (not at war though), one might need to trade with the other for survival. Example: An agricultural faction may find itself the monopolist of harvests in the region. Another example would be two factions that really like each other, like raiders and junkies, but what really can the raiders get from the junkies (besides crack ^_^). ) My point here is that relations between two factions and trade value between factions may be different from each other and one may be a function of the other.

2) Your relations with Faction B. There are multiple reasons as to why a stranger to Faction B will need to fork out more currency than an ally of Faction B. It may be that they are cautious if you are using counterfeit(?) currency. Or that they may want you to start building relations with them (and hence start using their currency instead. Maybe to promote their own currency?).

3) Bartering and/or Speech skills (self explanatory).

Regarding counterfeit currency:

There may also be security measures in using currencies. For example, (not in general), we have a secretive faction that only trades/deals with people they trust, the player may need to demonstrate that they are indeed genuinely known by some members of the faction, in contrast to having acquired the currency by looting corpses. Further elaborating, when the player asks to trade and upon using the currency, they may ask some questions and the player may be needed to answer correctly, else they will turn hostile (if they suspect you killed someone), or just refuse to trade (if they suspect you just looted some body). Note that maybe the player only need to validate himself once per trader. So in the future, there is no need to re-confirm.

Maybe I went on too much. Or starting speaking nonsense. If so, forgive me.
Just my 2cents.

Cheers!

**Comment by DeNarr** [comment] 2015-06-03 14:17
So, I would like to point out that I believe adding weight to currency is a bad idea. It's one of those "realism getting in the way of the game being fun". Though the only things I ever really use money for is vending machines and gas, and those make sense to keep using the cash cards.

**Comment by jokermatt999** [comment] 2015-06-03 14:19
Nah, that all makes a lot of sense. A science/knowledge faction should be inherently more secretive/suspicious when an outsider shows up with cash and no explanation. 

Do factions weigh needs as well as npcs do? I've been poking around that code, and I really like how the priorities are done. We could do some cool stuff with dynamic/repeatable missions based on needs of factions. But the reason I bring it up here is that if a faction is, say, starving to death, they may vastly devalue trading for their own currency until they have food (which they'd pay a large amount for, or you could sell them cheaply or give them away for a huge reputation boost). That also addresses the "why have currency when we need ammo?" issue.

Ammo is a tricky one, as mentioned in the PR thread. I'd generally skip over that, or have factions generally looking for common calibers, .22, 9mm, .223 and variants. Since we have survivor weapons, maybe they would also accept trades of those + ammo if they need protection?

I'm also for factions have generic "favors owed". It's already in the code, and I can see some small groups just relying on trust.

As for weighting currency, if it's paper money that should be negligible. It'd be cool to have a faction that stamped out its own coinage, but cumbersome.

**Comment by vache** [comment] 2015-06-03 16:15
I would think the large majority of "disorganized" factions like raiders, junkies, outcast mutants, whatever, would work purely on barter/favor system.

Military factions would probably have a quartermaster that would dispense whatever supplies they felt necessary for you to do whatever missions they give you.  Not sure how they would handle any supplies you decided to turn over to them; I think that would probably have to use some sort of scrip and/or a favor system.

As far as civilian trade, I would think the easiest currency to issue would be to take existing currency and modify it in some way.  So, it would be something like "this is a $20 bill modified with the logo of the free merchants."  Issuing any other sort of paper currency would be just as counterfeitable, but involve a lot more work.  Metal coins would be hard to scale, but some factions could use them.

**Comment by tvm1** [comment] 2015-06-03 17:37
Some very interesting ideas here!

We can use X as a currency in CDDA, but beware the day, when my caravan goes around your city. You will want some food and I will tell you that I no longer accept X. Your paper is worthless and you won't be able to buy anything from me. That's the problem with self-issued local currency. The value is not guaranteed.


If I remember right, in original Fallout (TM) lore, it all started with water. Water Merchants would accept caps and sell water. Since water was obviously rare enough and was exchangeable for caps - caps became a hard currency.

That seems like better case to me.

I could imagine some hi-tech faction with meds or whatever scarce commodity doing that thing and de-facto defining the universally valuable currency. Papers with signature could do it.

**Comment by John-Candlebury** [comment] 2015-06-03 18:46
The old guard could probably use ration stamps as money, which would be backed up by clean water and all those tasty Hotdog MREs.

Other settlement traders could also use them,if we assume that the old guard is willing to give out rations to  people who aren't directly affiliated with them.

They would probably devalue depending on the distance between the trader and the closest food distribution center.

**Comment by acidia** [comment] 2015-06-03 19:23
My thoughts were that the Free Merchants are made up of former white collar city workers so they would prioritize a stable currency before anyone else.  The only currency that is available in large quantities, is light weight, and forgery resistant that they would have easy control over is a casino's chips.  Raid one casino and you can have a few truckloads of unique coins that you can use as currency.  Since the free merchants are a local faction, that should be enough coins to handle their (and their outposts such as the farming commune) trade needs.

The Old Guard, being spread all over the east coast, would be one of the few factions that would have the resources to create a fiat currency but they have more pressing matters.  Their currency would probably just be a faction debt.  Swipe your Common Access Card to charge services to your account.  That shouldn't work exactly like the current cash cards but same idea... signing for everything is what the military already does.  The key point is that there is an actual ID verification so you couldn't steal someone's balance.

I mentioned earlier that the Hell's Raiders could simply use heroin as their basic currency... I don't see them bothering to set much else up.

The wasteland scavengers have no central leadership so I'd imagine they would carry bits of everyone else's and trade whatever they could.

I'm indifferent towards what you are going to use for "Your Followers."  Shortly you'll have to keep your faction's coffers full enough to prevent the members from deserting.  Give valuable supplies to your steward and he'll sell it to keep the coffers full.  You'll automatically pay each member from the coffers daily to prevent them from looting everything that isn't nailed down and allow you to pick their gear.  Pay for food if you haven't given the steward enough to distribute.  Finally, some inter-faction actions will require sufficient wealth.  Everything is on a credit system but if someone wants to make suggestions for the future then now would be your chance.

**Comment by jokermatt999** [comment] 2015-06-03 19:50
Sounds solid acidia. I like the flavor of Free Merchants taking over a casino too.

Good flavor/mechanics on the Old Guard. We might want to get a thread on the forums going with the official lore on the factions to help with future design.

While I see the raiders as generally bartering for drugs, I'm sure they'd be more than happy to *pay you* in money if you ask for it...they just might not accept it as payment, so it'd be worthless.

For inter-faction, I'd like to see trade routes based mostly on needs and exchange of goods rather than credit. I'd imagine the factions (largely Old Guard/Free Merchants) would have to be pretty friendly already to accept each others currency. Maybe after a quest line?

Also, are there any plans for tech/maker faction? I see the Old Guard as being geared towards Law and Order, Free Merchants are obviously Trade, and while they both might dabble in manufacture and preserving science, it'd be cool to have a specific sort of technomonk faction preserving what it could of the old world's knowledge and manufacturing, and trading that for protection/sustenance.

**Comment by illi-kun** [comment] 2015-06-03 20:47
>  Metal coins would be hard to scale, but some factions could use them.

Bingo, the elongated coins!! I bet most of non-US players of cdda don't even knows about such cool thing, so we need to mention them in educational purposes, at least (new headache for translators, but who cares? Sorry, Vitaly :)
Of course, each piece of it may cost much more than just a penny, since only the faction leader controls the unique penny press of the faction (and uses it for conversion of blank pennies to unique factional currency wisely).

Also, elongated coins of one faction may be used by another faction as blanks for their own currency.

I see a lot of possible quests related with such kind of currency. For example, do you want to ruin entire payment system of unliked faction?
1) Steal their unique penny press;
2) Take the bag of pennies from the bank safe in random city;
3) ???
4) Profit!

**Comment by vache** [comment] 2015-06-03 20:59
>  The only currency that is available in large quantities, is light weight, and forgery resistant that they would have easy control over is a casino's chips. Raid one casino and you can have a few truckloads of unique coins that you can use as currency.

I kind of disagree with this part.  There are definitely other potential currencies that satisfy those qualities.  Casinos have TONS of chips, and it would take FOREVER to gather them all up, or at least in a reasonable enough quantity to prevent being flooded with chips you didn't know about.  Also, the New England area seems a little sparse on casinos, unless you count Atlantic City.  I would also caution that we should try to avoid the Fallout/NV/Wasteland 2 tropes when possible.  Otherwise, I think it would work just as well as any other system I've seen proposed.

**Comment by tvm1** [comment] 2015-06-03 21:12
Currency is of no good, when your limb is rotting away.

**Comment by i2amroy** [comment] 2015-06-07 15:57
Honestly I think at least a few factions should still be using the old bank systems (probably at significant inflation rates, though if they are rather reclusive they probably won't be diving the city zombies to take their money anyways). It would be pretty awesome to have a handful of different currency systems, with each faction only considering certain ones to be profitable (maybe encourage players to try to spend all their money when they leave, in case they don't come back there again).

**Comment by kevingranade** [comment] 2015-06-07 22:24
The problem with using existing money is that it would be crazy easy to just go around and accumulate thousands of dollars in bills by looting a few small businesses.  Same deal with cash cards, the only reason we're keeping them around is for machines that are too dumb to know the cataclysm happened.  Now it might be an interesting scenario for some isolated person to not know or believe that the cataclysm happened, or understand the implications, and be willing to trade things of worth for paper money or gold, but I'd expect factions to have at least someone who would figure it out, either that or they already got burned by someone buying the faction's entire surplus of medicine and ammo with a suitcase of bills.

**Comment by ArikVhedrovix** [comment] 2015-06-09 00:56
What about an digitally signed currency stored on the ubiquitous thumb drive? Perhaps thumb drives marked with denominations and verifiable. Another form of pseudo-currency that comes to mind is body parts from nearby hostile creatures. If a faction wants to expand its territory and some creature colony interferes, a logical idea would be to assign value to body parts to encourage outsiders to do the risky job of extermination. What about radioactive currencies for mutant factions? This would make them pretty easy to verify as "authentic" with a Geiger counter and would also "encourage" the spread of mutation in general, even to outsiders.

**Comment by kevingranade** [comment] 2015-06-09 23:39
Some techno-faction could implement 1 if they wanted, it's mostly known
technology now, so a pretty good hacker could make one if they have access
to computers.
Body parts wouldn't be currency, they'd have a bounty on them, which is
reasonable, but a totally different thing.
Being radioactive doesn't meet the bar for 'hard to forge', though some
other property of the item might meet it.

**Comment by Rivet-the-Zombie** [comment] 2015-06-10 00:08
What about having the option to take your payment for various tasks in items that you get to choose? Like for example, if I complete a quest for a faction they'd say something like, "we can pay you in first aid kits, 5.56 NATO, or plutonium" and choosing one of the possible rewards nets me a pre-specified quantity of that item.

**Comment by vache** [comment] 2015-06-10 00:12
Task rewards are one thing, medium of trade is another though.  We could force bartering, but that would get tedious in the long run, especially if you're forced to lug heavy things around.

**Comment by ArikVhedrovix** [comment] 2015-06-10 00:58
I don't know about the realism level desired in Cataclysm DDA or if this is covered in lore. IRL I believe that there would be EMP associated with nuclear detonations that would burn out most electronics in large swathes. If that were the case, I would think electrical components would make a pretty universal store of value. Small handfuls of working resistors and capacitors and what not for repairing purposes wouldn't weigh much but could be very valuable if they let people get broken electronics working. They would also be pretty easy to test if they were duds or not with a continuity tester.

**Comment by Eliijahh** [comment] 2015-06-10 02:02
The problem is that if those resistors and capacitors are very useful, they'd be used instead of traded for other stuff. 
Instead we need something without "Real application value" that is not that easy to find, but not too difficult. As much as boring and conventional it may sound, I think a metal would be the best choice.

The metal in question can be decided, but only a metal can be easily made into standard units, it is not very easy to find and it requires a central entity that makes coinage, therefore not allowing everyone to create money, it is fairly resistant, easy to be worked. Also only a metal that is not used for making weapons, buildings or tools is suitable to be a medium of value. 

I'm trying really hard to imagine a creative way to create money, but there is a reason we humans used "precious" metals as medium of value, I guess.

**Comment by kevingranade** [comment] 2015-06-10 07:03
Basic electrical components are fine with EMP, it's fine electronics like
integrated circuits (CPUs, RAM, PC motherboards) that will get wrecked, so
far we've glossed over that concept.

**Comment by mlangsdorf** [comment] 2019-09-04 20:18
We've implemented faction currency and NPCs no longer trade in e-cash.  Closing this issue.

**Closed by mlangsdorf** 2019-09-04 20:18 UTC
Labels: (P5 - Long-term), <Enhancement / Feature>, Game: Mechanics Change, NPC / Factions
