### ISSUE TITLE
The game crashes when changing keybinds, unless you delete the keybinds in the config folder, the game will not open anymore.

### ISSUE THREAD

**Issue by jayWLKRRR** [CleverRaven/Cataclysm-DDA#26495] opened 2018-11-02 11:06 UTC
**Describe the bug**  
At the title

**To Reproduce**  
1. Changing keybinds 
2. When you it say "save settings?" and when you say yes
3. It crashes and it will not open anymore unless you delete the keybinds in the config folder

**Expected behavior**  
I expect to change my keybinds without crashing

**Screenshots**  
Im sorry i dont have that.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: O.C-33896-g41bbd2d
 - Graphics version: Tiles
 - Mods loaded: Disable NPC needs, Filthy Clothing, and Simplified Nutrition

**Additional context**  
I made an Experiment. I think there's a threshold on changing keybinds if you don't reach the threshold it will not crash and the key changes but if you reach the threshold, it will crash.

**Comment by Zetsukaze** [comment] 2018-11-02 11:13
Related to #26494 I think

**Comment by ZhilkinSerg** [comment] 2018-11-02 14:35
Duplicate of #26494.

**Closed by ZhilkinSerg** 2018-11-02 14:35 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Controls / Input, Info / User Interface
