### ISSUE TITLE
Furniture that is being dragged stops after one turn and claims to be destroyed.

### ISSUE THREAD

**Issue by 2storytallskeletonman** [CleverRaven/Cataclysm-DDA#47452] opened 2021-02-12 21:39 UTC
# Describe the bug

When furniture is being dragged, it cancels out after moving one turn and says "The (name of furniture) you were grabbing is destroyed!" Yet I am able to still grab and drag it one time before it repeats the same process.

# Steps To Reproduce
1. Grab draggable furniture.
2. Move said furniture in any direction once.
3. Character drops said furniture because it is apparently destroyed.

# Expected behavior
Not to be rude, but I expect my furniture to be dragged with ease.

# Screenshots
![2021 02 12-16 12](https://user-images.githubusercontent.com/78984273/107823108-34c27280-6d4d-11eb-9fef-fb059742aa7e.png)![2021 02 12-16 21](https://user-images.githubusercontent.com/78984273/107824074-d4cccb80-6d4e-11eb-9934-3142ba30bd37.png)![2021 02 12-16 24](https://user-images.githubusercontent.com/78984273/107824165-fded5c00-6d4e-11eb-9f00-e3a5def6ab32.png)

# Versions and configuration
The version is 1.B and the build is 11458. The mods I am using are from UndeadPeopleTileset and Kenan2000's Modpack respectively.

# Additional context
Now, firstly I apologize if this report isn't great because it's my first time, secondly I am unsure whether this bug is exclusive to me or if other people are experiencing the same problem. I have quite a few mods enabled on my world, but I tested it out on a vanilla world with no mods and I still have the same issue. I can still move the furniture, I just need to grab it again and again if I want to consistently move it.

**Comment by BrettDong** [comment] 2021-02-12 22:09
Thank you for reporting this! Possible a duplicate of #47304.

**Closed** 2021-02-12 22:38 UTC
Labels: (S3 - Duplicate), <Bug>, Fields / Furniture / Terrain / Traps
