### ISSUE TITLE
Segmentation Failure on dropping too many items

### ISSUE THREAD

**Issue by Hisenburg** [CleverRaven/Cataclysm-DDA#36641] opened 2020-01-02 15:17 UTC
# Describe the bug

Segmentation Failure upon dropping too many items

# Steps To Reproduce

Drop/move a large number of items, the cash cards in player inventory work

# Expected behavior

It to not crash.

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-10932-g9eb7975]
 - Graphics version: [Tiles]
 - Mods loaded: [e.g.dda, Disable NPC Needs, Aftershock, Magiclysm, Bens GF Recipes, Craftable Gun Mod, Medival and Historic Classes Mod, More Survival Tools, Mythological Recipes, Modular Turrets, Salvaged Robots, Mutant NPCs, Mythical Martial Arts, More Locations, No Rail Stations, Urban Development, Mapgen Demo, Fuji's More Buildings, Vehicle Additions Pack, Tanks and Other Vehicles, Folding Parts Pack, [DP_MOD]Hide DEBUG, [DP_MOD]Hide Status, Artyom's Gun Emporium - Reloaded, Fuji's Military Profession Pack, Safe Autodoc, Simplified Nutrition, Sleep Deprivition, SpeedyDex. Stats Through Kills, Stats Through Skills, Classes And Scenarios Mod, Classic Roguelike Classes, Graphical Overmap, Graphical Overmap More Locations, Graphical Overmap Urban Development]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4016298/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4016299/debug.log)
(Save is over 10mb, heres a google drive link)
https://drive.google.com/open?id=1m1gwqUGRgGzh-4aGMjHh6upgkUt7LvcN

**Comment by ZhilkinSerg** [comment] 2020-01-02 15:41
Duplicate of #36554

**Closed by ZhilkinSerg** 2020-01-02 15:41 UTC
