### ISSUE TITLE
Skeleton key is out of charges, despite no indication of charge in description

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51380] opened 2021-09-05 01:56 UTC
### Describe the bug

The Magiclysm skeleton key ran out of charges, despite no indication of charges in description.

### Steps To Reproduce

Have skeleton key, use it repeatedly, be told that it's out of charges.

### Expected behavior

I would expect that the description show or mention a number of charges, if there's a limited amount. Hopefully also describe how often they recharge. 1/day? 1/hour? 1/year?

### Screenshots

![image](https://user-images.githubusercontent.com/6834262/132112310-fb7229b6-b6bd-415b-a915-a525ea47c0fd.png)
![image](https://user-images.githubusercontent.com/6834262/132112317-9b231345-f955-45f9-ab07-7b49105887b9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ifffrt** [comment] 2021-09-05 08:44
Ran into this issue pretty frequently. I think it has something with how there's a difference between using it using the 'Examine' key on a door, and using it using the 'Use item' menu. Did you use it using the 'Use item' menu on wooden doors like I did? Wooden doors will default to using pry tools instead of using the skeleton key, but the issue is sometimes you want to leave your crowbar behind for less encumbrance and only take your skeleton key with you, but the game won't ask to use your skeleton key but instead try to use your wimpy hammer on the door instead.

**Comment by MrHrulgin** [comment] 2021-09-05 15:47
That's exactly how I did it. I have an integrated toolset, and the game defaults to telling me that it won't work as opposed to offering other options. I only ever used the key from the Use Item menu.

**Comment by actual-nh** [comment] 2021-09-05 21:12
Ping: @KorGgenT?

**Comment by GuardianDll** [comment] 2022-05-08 22:15
cant reproduce it anymore
is it fixed?

**Comment by Night-Pryanik** [comment] 2024-11-01 14:33
Can't reproduce either. Closing until reconfirmed.

**Closed by Night-Pryanik** 2024-11-01 14:33 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Mods: Magiclysm, Mechanics: Enchantments / Spells
