### ISSUE TITLE
Dissasembling steel frames requires tool with glare protection 2 or more

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#16783] opened 2016-05-20 23:31 UTC
such is the message i get when i forget to bring wielding googles or pba mask in field and i need some lumps of steel to cut with my toolbox from vehicle parts.toolbox or hacksaw as far as i now doesnt include welding.

**Comment by illi-kun** [comment] 2016-06-21 07:09
I've changed the header because this bug is reproducible with a hacksaw too, so all you need to disassemble a frame is a hacksaw and welding goggles (without a welder).

**Comment by pabrams** [comment] 2017-07-01 14:31
@illi-kun Why would you need welding goggles to use a hacksaw on a steel frame?

**Comment by Night-Pryanik** [comment] 2018-03-02 07:44
Closed by #22774.

**Closed by Night-Pryanik** 2018-03-02 07:44 UTC
Labels: Bug, Confirmed, Vehicle
