### ISSUE TITLE
Crowbar got damaged on a miss

### ISSUE THREAD

**Issue by Boonlike** [CleverRaven/Cataclysm-DDA#49121] opened 2021-06-01 02:40 UTC
# Describe the bug

I equipped my new crowbar for the first time, took a swing at a skeleton, missed, and that damaged the crowbar. I was in a grass field away from anything hard like a wall or even a rock for the crowbar to potentially smash and cause damage.

# Steps To Reproduce

1. Equip crowbar
2. Swing at enemy
3. Miss so hard the crowbar feels sympathy pain for you

# Expected behavior

I expect that when I swing a crowbar at empty air, it's generally a non-traumatic experience for the crowbar. 

Alternatively, if my target is blocking the attack and that's what caused damage, that the information is relayed to the player through a message instead of "You miss."

What I'm assuming is happening is that every attack has a tiny chance of damaging your weapon. My suggestion would be to test hit vs miss and then only give a chance of damaging your weapon on a hit. Then of course the % chance to damage your weapon would have to go up because it would only be getting rolled on a successful hit. 

# Screenshots

![image](https://user-images.githubusercontent.com/84247285/120258240-e29b5380-c24e-11eb-8b43-d2c5da291193.png)

^I haven't tried to copy/paste a screenshot in like that before, sorry if it didn't work. It's simply my log showing that my very first attack with my crowbar resulted in both a miss and damage to the crowbar.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a83d0fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

This is super low priority. I'd put this under the category of "immersion breaking bug". I think I've played at least 100h now and only just noticed you could damage weapons on a miss.

**Comment by natsirt721** [comment] 2021-06-02 15:30
Huh - I've never noticed this previously, but not 2 hours after reading this I whiffed an attack that damaged my knife spear. This is on build 2021-06-01-0594. Unfortunately I didn't think to grab a screenshot.

**Comment by Anaglyphic** [comment] 2021-06-02 18:01
Hi.

Wow not sure that's low priority or not, but yes you are correct. Definitely confirmed.

First though? Being a bit nit-picky but those are three separate miss events, the "you miss" ones are not part of the damage to the crowbar. Look closely at your log window output. 

You miss.
-next-
Your crowbar is damaged by the force of the blow!
Your torso encumbrance throws you off-balance.
-next-
You miss.

Anyway yes, good catch, a cursory inspection of melee.cpp shows the nesting of the if elseif else conditionals where handle_melee_wear is called is on the same level as hit or !hit... it appears intentional too. Like, because you still exert stamina and increase weariness if you miss, so you are still exerting force on your weapon whether or not you hit something, I guess? I didn't do it. 

I can only assume it was done for "gameplay" and not "reality"... or else it's just an oversight.

The reason I think it's intentional gameplay is it takes a _lot_ to damage a crowbar or anything with the DURABLE_MELEE flag and you catching that, as you say, was just a bit of lucky? unlucky? timing. And if a weapon never gets worn, you won't fix or replace it until it's so weak against current mobs or you find one that's next-stage better, yea?

Well, hey, since you seem to care, you came to file this - what's your opinion on how, or even _if_, it should be adjusted? As I said, crowbars and other 'tough' weapons have a flag durable_melee, meaning what it sounds like. What if the wear subroutine was changed so that only fragile_melee weapons are damaged simply by swinging them, regular and durable ones have to connect to something to incur a wear n tear calculation? Or just change the display message to something more useful? `add_msg_player_or_npc( m_bad, _( "You squeeze your %s so hard, Lou Ferrigno, that you damage it!" ),`

Sadly, if your crowbar needs therapy, all crowbar cognitive behaviourists are now zombies. The best therapy is bashing on them without missing, but hey, no co-pays.

**Comment by Zireael07** [comment] 2021-06-02 18:37
I'd limit damage on miss to fragile melee, indeed.

**Comment by natsirt721** [comment] 2021-06-03 02:11
I'd just remove the damage chance on miss altogether. Fragile items aren't (usually) fragile to the point where just waving them around is going to cause damage.

**Comment by Boonlike** [comment] 2021-06-03 03:04
I'm not a programmer and don't know exactly how the chance to damage an item is calculated. I'm assuming that every time you attack there's a tiny chance to damage your weapon, and it doesn't check if there's a hit or miss. What makes sense to me is that these items can be damaged, but the chance to damage an item is only rolled on a successful hit. Since this will roll the chance to damage an item less frequently, the chance to damage a fragile item should go up, since it will only be rolled on a successful hit.

As for the nitpickiness, I had the understanding that the "you miss" message came before the results of the attack, which is when my crowbar got damaged. Unless you're telling me that I hit the zombie so hard that I damage my crowbar but it didn't damage the zombie.

**Comment by Boonlike** [comment] 2021-06-03 03:55
Ok Anaglyphic, I've had supper now and re-read your reply. I don't have to be a programmer, you explained it to me in dummied down language for me and I get it now. I'm going to assume that it was programmed that way because it worked more than good enough. It was a simple solution that gives the desired gameplay effect and the odds of someone like me damaging their crowbar on the very first (or second) swing ever is super unlikely. If it did happen on a miss it would be more than likely to happen somewhere in the middle of a fight and not even be noticed.

Now that I've had supper and thought more about it, I still think my logic of only rolling for weapon durability loss on a hit is a good idea, but if it's a lot of work to implement,  meh. You devs are doing a labour of love, but it's still labour, and I'm sure there are far more important things that need attention.

**Comment by NetSysFire** [comment] 2022-01-23 01:31
Closing in favor of #53527

**Closed by NetSysFire** 2022-01-23 01:31 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Melee
