### ISSUE TITLE
add_zombie: there's already a monster

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24206] opened 2018-07-05 14:10 UTC
Game version: O.C-28852

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Bug
Lately, seemingly randomly I get following error. 

![add_zombie](https://user-images.githubusercontent.com/38487938/42328167-ea2a618e-806d-11e8-9b2d-affcc28b846f.png)

Of course, the location coordinates of the monster differ, but the bug is rather common and it's always referencing line 73.
Perhaps connected to recent addition of reproducing fauna and spawning carrion monsters?

**Comment by BevapDin** [comment] 2018-07-05 15:30
Duplicate of #21130.

**Closed by BevapDin** 2018-07-05 15:30 UTC
