### ISSUE TITLE
Overmap Generation issue

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#20636] opened 2017-03-22 17:52 UTC
On the latest experimental overmap generation seems to fail almost every time for my on Cities: 8 with Spacing: 4, and fail every time when spacing is more than 4.
Generation also seems to fail every time when I am trying to use mod like PK's Rebalance.

**Comment by BorkBorkGoesTheCode** [comment] 2017-03-22 17:58
How many mods are installed? There's an issue with mods adding more than a certain number of mandatory locations.

**Comment by Murumuru** [comment] 2017-03-22 18:21
@BorkBorkGoesTheCode 
It happens even without any mods, if I have City Spacing value bigger than default one.
If I turn mod like PK's Rebalance - then generation fails every time, no matter what values I set in Cities and City Spacing.

**Comment by Leland** [comment] 2017-08-19 01:43
A dupe of #8649 and, like that issue, fixed by #21212. Can confirm that with OP's "Cities: 8 with Spacing: 4" I can still start.

Another 0.D issue down @kevingranade 👏

**Closed by Leland** 2017-08-19 01:43 UTC
Labels: Bug, Mapgen
