### ISSUE TITLE
Not all features work on Atomic Smartphone

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#47481] opened 2021-02-13 20:59 UTC
# Describe the bug
When using the Atomic Phone, you cannot use the music (it says the device's batteries are dead) even though you can still use the camera and flashlight app.

# Steps To Reproduce

1. make an atomic pitchman to start with the phone in your inventory or spawn an Atomic Phone.
2. attempt to turn on the music
3. see incorrect message about no batteries left

# Expected behavior

The music should play, as the phone never used batteries before.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9634-gda7c0c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Jamuro-g** [comment] 2021-02-13 21:26
i don't have the mod at hand to test it but #47480 should most likley fix it.

**Comment by actual-nh** [comment] 2021-02-14 00:16
#47480 is now merged; try updating to build 11464 (at least).

**Comment by wapcaplet** [comment] 2021-02-14 06:12
Cannot reproduce in 0.E-9603-g42468f6cab (after the above mentioned PR was merged) using the Aftershock mod. The atomic smartphone can be successfully activated for music/mp3 as well as light or camera now. Closing.

**Closed by wapcaplet** 2021-02-14 06:12 UTC
