### ISSUE TITLE
Military Recruit spawns with half ammo in all magazines.

### ISSUE THREAD

**Issue by Talvan** [CleverRaven/Cataclysm-DDA#39530] opened 2020-04-13 14:45 UTC
# Describe the bug

![cataclysm-tiles_2020-04-13_10-39-28](https://user-images.githubusercontent.com/8293574/79129519-5d678d80-7d73-11ea-865a-e4744fab3a9d.png)

# Steps To Reproduce

1. Start game.
2. Select Military Recruit.
3. Spawn with half ammo in all magazines.

# Expected behavior

![notepad++_2020-04-13_10-40-26](https://user-images.githubusercontent.com/8293574/79129511-580a4300-7d73-11ea-93c8-3f25bcd47ec0.png)

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-635-gef0197a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Aftershock

# Additional context

It's like this with every profession that spawns with an item with charges.

**Comment by LaVeyanFiend** [comment] 2020-04-13 15:18
Duplicate of #39176

**Closed** 2020-04-13 18:47 UTC
