### ISSUE TITLE
Swimming in car

### ISSUE THREAD

**Issue by YukioDjo** [CleverRaven/Cataclysm-DDA#48601] opened 2021-04-21 07:30 UTC
Steps to reproduce: Place car on ground and water and deep water. The player must go through deep water to the driver's seat (which is also in deep water).  Then he be swimming or drown and driving car at the same time.

Expected result: The character must move around the car, regardless of what is under the car.  And do not receive fines from the ground (stones, debris, etc.) under the car.

Actual results: Now the character is walking on a car that is above debris / rubble, etc.  receives a fine from the area, but he is in the car.  (IRL walking on the bus you do not walk on the asphalt).

Game version: d55d4a1
Language: russian
Graphic: Dead People (New version)
Video with attempt to play bug tacked.[Video with bug](https://youtu.be/PNKJg1_u5io)

**Comment by Salty-Panda** [comment] 2021-04-21 09:22
Duplicate of #46488

**Closed** 2021-04-21 13:36 UTC
Labels: (S3 - Duplicate), Vehicles
