### ISSUE TITLE
Can craft military grade ammo with kinetic bullet puller

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#15996] opened 2016-03-31 13:17 UTC
Not sure exactly why, but disassemble recipe is autolearned and can be crafted.

**Comment by mugling** [comment] 2016-04-06 23:48
Can you be more specific and/or give an example?

**Comment by Coolthulhu** [comment] 2016-04-06 23:55
It should be fixed by now. It was caused by autolearn on character creation problem.

**Closed** 2016-04-06 23:55 UTC
Labels: Confirmation Needed
