### ISSUE TITLE
"Add part to vehicle" - add feature select specific item

### ISSUE THREAD

**Issue by SuperDIMMaX** [CleverRaven/Cataclysm-DDA#31369] opened 2019-06-12 18:55 UTC
Example: i have 3 accum 2500
1 - 0/2500
2 - 1999/2500
3 - 150/2500 in vibrator :P
i press add acc to vehicle and i don't know - first or second or 3rd will be installed.
Please add menu to select specific item.
ps: or i have 2 steel frame - one damaged another - full, and installed ...

**Comment by Night-Pryanik** [comment] 2019-06-15 16:35
Duplicate of #11706.

**Closed by Night-Pryanik** 2019-06-15 16:35 UTC
