### ISSUE TITLE
House burning for for a day.

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#32479] opened 2019-07-18 15:31 UTC
# Describe the bug

House has been burning for about a day now. Note character is in the basement of the burning house, z levels are turned on.

Suspect it has something to do with the second floor of the house.

# Steps To Reproduce

1. Set a house on fire
2. Wait.

# Expected behavior

A house burns down in a couple of hours.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5707-g7fa6897 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    No Fungal Monsters [No_Fungi],
    Sleep Deprivation [sleepdeprivation]
]

# Additional context

Save file:

[Morgan Mill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3407244/Morgan.Mill.zip)

**Comment by BevapDin** [comment] 2019-07-18 15:37
Duplicate of #32378.

**Closed by BevapDin** 2019-07-18 15:37 UTC
