### ISSUE TITLE
Excessive bionics cause crash in @ menu

### ISSUE THREAD

**Issue by thor-kiessling** [CleverRaven/Cataclysm-DDA#26436] opened 2018-10-29 06:26 UTC
**Describe the bug**  
I went on an installing spree for bionics and now my @ menu crashes the game.

**To Reproduce**  
Load the attached save. [auto_before_launch82.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2524096/auto_before_launch82.zip)
Hit @ 

**Expected behavior**  
One would expect that portion of the @ menu to start scrolling if you have excessive amounts of bionics. And also to not crash.

**Versions and configuration(please complete the following information):**
 - OS:Win 10
 - Game Version Build 8083
 - Graphics version Tiles
 - Mods loaded "dda",
  "Cata++",
  "FIC_Weapons",
  "StatsThroughSkills",
  "blazemod",
  "Tanks",
  "bio_mod",
  "ew_pack",
  "mutant_npcs",
  "no_npc_food",
  "novitamins",
  "npc_traits",
  "modular_turrets",
  "No_Fungi"

**Comment by thor-kiessling** [comment] 2018-10-30 21:58
Did some more testing, it crashes at exactly 33 bionics installed. 32 does not crash.

**Comment by Theundyingcode** [comment] 2018-10-30 23:42
A similar problem happened earlier it was in the summary 31 file:
In the character creation screen, fix scrolling the skill screen causing a crash when the skill list is smaller than the skill window height.

**Comment by Lorith** [comment] 2018-11-03 12:36
[Several people in the forums](https://discourse.cataclysmdda.org/t/game-crashes-when-checking-status-menu/17291) are also having this occur to them as well.  Apparently it isn't just the bionics, it is the combination of them and mutations/traits, as someone was able to toggle between crashing and not crashing by debugging mutations.

**Comment by ZhilkinSerg** [comment] 2018-11-09 07:55
Duplicate of #25762. Please add any additional information regarding this issue there.

**Closed by ZhilkinSerg** 2018-11-09 07:55 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Info / User Interface
