### ISSUE TITLE
Using AIM can sometimes dupe items if you set the number to move less than the number that you have

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#47958] opened 2021-03-09 20:17 UTC
# Describe the bug

I am not sure what is happening so I will just post this video of what exactly happens. Basically I have 20 biscuits on the workbench and then I put 18 of them into a vehicle fridge from blazemod, but 18 of them are not subtracted from the workbenches number of biscuits so the total is now +18 biscuits. If I put the number 20 then everything is fine.

# Steps To Reproduce

Get some biscuits near you,
Get some more biscuits to a tile that isnt the same as the previous one,
Move a number of  them from one tile to another where the number is less than the total of the inventory.

# Expected behavior

Not to dupe my biscuits.

# Screenshots

video: https://puu.sh/HnE5a/f8ef3bdbd1.mp4

# Versions and configuration

WARNING: GAME IS HEAVILY MODDED WILL TRY TO REPRODUCE IN VANILLA SOON.

 - OS: Win10
 - Game Version: 0.E-9955-g425255a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: A lot

# Additional context

N/A

**Comment by Jamuro-g** [comment] 2021-03-09 20:49
should be fixed in the current experimental version (Build 11516) it was deployed earlier today

**Comment by wapcaplet** [comment] 2021-03-09 22:32
Duplicate of #47884

**Closed by wapcaplet** 2021-03-09 22:32 UTC
