### ISSUE TITLE
Bug when reloading L523-MBR rifle ,got 2 fully loaded magazines

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16771] opened 2016-05-20 08:32 UTC
when i reloaded a L523-mbr rifle with a LW-30 magazine, it became fully loaded ,and i also got a error message, something about trying too take something from my inventory but failing too? im not sure, but i reloaded the rifle, and the clip still stayed there, and the rifle was loaded. what was wierd is that i had like, 4 or 5 fully loaded LW-30 magazines, all with 32 rounds of 5.56 nato, and yet one of them wasnt stacking. when shown in advanced inventory, it would show the 3 or 4 LW-30 magazines with 32 rounds of 5.56 nato in 1 row, with an ammount being shown as 3 or 4, (i may have had 5 or 4 magazines before the bug, im not sure but that shouldnt matter) and then 1 extra LW-30 magazine with 32 rounds of 5.56 nato in another row.

**Comment by 321nick** [comment] 2016-05-20 08:32
oh and this is with build 4883

**Comment by DLaboratory** [comment] 2016-05-29 09:28
Might be a duplicate of #16445?

**Comment by mugling** [comment] 2016-07-01 14:16
Duplicated by #16771

**Closed by mugling** 2016-07-01 14:16 UTC
Labels: Bug, Magazine

**Comment by BorkBorkGoesTheCode** [comment] 2016-07-01 14:38
>Duplicated by #16771 

Circular link. #16445

**Comment by mugling** [comment] 2016-07-01 15:08
No this one was closed and the other was left open
