### ISSUE TITLE
Some locations in "More Locations" mod have no loot

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#20159] opened 2017-01-29 17:20 UTC
What it says on the tin. In old versions, or the most recent one (6183), the locations added in those mods were always empty. Not a single item anywhere.

**Comment by keyspace** [comment] 2017-01-29 20:59
Can't reproduce on latest git master (`0.C-20896-gd22e4ef2e4`) for `Z-Level_Buildings` ("Tall Buildings"), either of the two specials included in it. And haven't experienced this in any game started for the last 3 months at least. Are you sure the locations in question come from this mod?

For `More_Locations`, `grep -R -E "(item|loot)" *json` shows there's none defined - except for components in custom terrain/furniture. So works as specified - i.e. not a bug.

**Comment by keyspace** [comment] 2017-01-29 21:10
BTW, adding loot has become _extremely_ easy recently. One needs only define what is to be spawned. See [this line in a PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/20060/commits/1cbc4a6ee8fcff210ef3e5e034c1a157831d4588#diff-30040570d14f856a03c36dfc7f0e7c0eR58) for an example of adding a single item. Spawning groups (all-of or any-of), including custom-defined ones, is also possible.

**Comment by keyspace** [comment] 2017-01-29 21:16
Note: added in PR #14762.

Ping @SunshineDistillery.

**Comment by TheSadFox** [comment] 2017-01-29 22:08
Yeah 100% positive its mods added in these mods. I've teleported around all locations i haven't seen with them off, none had any loot. All done on a newest experimental.

>It adds three types of multistory houses, a military outpost occupied by bandits, and a factory filled with robots. They don't have items added yet, so they're mainly just to explore or use as bases.

Looking at the quote from the  PR you linked, it does indeed look like not a bug. Still, it would be pretty great if they got proper loot added to them, since locations themselves are intresting and well done.

**Comment by keyspace** [comment] 2017-01-29 22:51
Do provide the [general bug report info](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md#bug-reports), please.

**Comment by TheSadFox** [comment] 2017-02-01 15:22
Game version, although its been the case on a month worth of builds before.
http://prntscr.com/e35tc9

Save of a freshly generated world.
https://www.dropbox.com/s/i0ljvh51rm82qmu/Hoxie.zip?dl=0

**Comment by keyspace** [comment] 2017-02-02 13:22
With provided save - still can't reproduce for Z-Level_Buildings ("Tall Buildings"). Teleported around to check once each of both locations provided in that mod ("office tower" and "two-floor motel") - both had the loot they're supposed to have.

**Comment by keyspace** [comment] 2017-02-02 13:24
Unless it can be shown that loot does not generate when it should, suggest closing this as invalid, and possibly opening a tracking issue specifically for "More Locations", sans all the noise here.

**Comment by 1skandar** [comment] 2017-02-04 04:49
I can verify that the More Locations are loot-less at the very least

**Comment by hurston1** [comment] 2017-02-10 13:55
I've also found no loot in some of the buildings mentioned.
This includes a two (or was it three?) story house and the military base with the basements.
It just looks like the creator of these buildings that keyspace linked to didn't finish the job.

**Comment by DangerNoodle** [comment] 2017-04-12 18:30
Working on partially fleshing out content of houses in More Locations.

**Comment by DangerNoodle** [comment] 2017-05-12 00:59
@kevingranade, I explicitly stated that my pull request is not even remotely adequate to close this, houses in More Locations are still exceedingly threadbare.

**Comment by Leland** [comment] 2017-11-06 15:39
Moved to just More Locations per the discussion above

**Closed** 2017-11-15 06:29 UTC
Labels: Enhancement, Mapgen, Mods, Spawn
