### ISSUE TITLE
Dissaasembling seats,frames and car parts which dont need welder should not require player to have items with glare protection 2

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#22904] opened 2018-02-08 12:32 UTC
Game version:7112

Operating system:windows 2010

Tiles or curses:Xotto

Mods active:pk rebalance,filty clothes,

### Steps to reproduce the behavior
try dissasebling car parts such are seats or frames without items with 2 glare protection

**Comment by Night-Pryanik** [comment] 2018-02-08 14:25
@baraba3 Duplicate of your own issue #16783.

**Closed by Night-Pryanik** 2018-02-08 14:25 UTC
