### ISSUE TITLE
Plutonium Batteries in everything

### ISSUE THREAD

**Issue by ZaricaDemoni** [CleverRaven/Cataclysm-DDA#41911] opened 2020-07-07 00:20 UTC
# Describe the bug
Every item that has a battery in it seems to be preloaded with Plutonium battery cells, though regular batteries can be found in kitchen drawers/

# Steps To Reproduce
Go into any building with electronics
Proceed to notice everything tends to have a charged or near dead plutonium battery.

# Expected behavior
Variety in eletronics with preloaded batteries

# Screenshots
![image](https://user-images.githubusercontent.com/32645137/86672608-ad897100-bfab-11ea-9356-e43872993742.png)
![image](https://user-images.githubusercontent.com/32645137/86673532-a020b680-bfac-11ea-8668-c0c5bbfdfab0.png)
![image](https://user-images.githubusercontent.com/32645137/86673575-aa42b500-bfac-11ea-8bcf-c73ca56d40d2.png)
![image](https://user-images.githubusercontent.com/32645137/86673600-af9fff80-bfac-11ea-8fef-51e30375f2cf.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-3780-g54cde4b
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
All items in the image were collected from town up north in my world, and a prison down south for the flashlights. Everything but the laptop has a light plutonium battery, it instead has a medium plutonium.

**Comment by LaVeyanFiend** [comment] 2020-07-07 15:50
Duplicate of #40800.

**Closed** 2020-07-07 16:03 UTC
