### ISSUE TITLE
Save scumming is possible. It also leads to item duplication.

### ISSUE THREAD

**Issue by alex-gh** [CleverRaven/Cataclysm-DDA#12602] opened 2015-06-09 19:47 UTC
It is possible to save scum by closing the game after dying.
When you reload the save you can find your corpse and get the items you had at the time of death, thus duplicating a part of the inventory.

I was able to reproduce this behavior in experimental build 3258 for windows.

Steps to reproduce: 

* Start a new character
* Play until the first autosave
* Die to something
* Close the game when it is showing the post-mortem stats.
* Open the game and reload the save

If you go to the place of your death you will find your corpse and the items you had when you died.

**Comment by drbig** [comment] 2015-06-09 19:53
That's not a bug. The worlds are persistent, and finding your last character's dead body is a part of it.

**Comment by alex-gh** [comment] 2015-06-09 20:06
> That's not a bug. The worlds are persistent, and finding your last character's dead body is a part of it.

Yes, but if you close the game after dying it is possible to reload the last save, and find the corpse if the same character with all the items they had on death. So you can both continue from the last save and benefit from the items on your corpse.

The game should either prevent save scumming by deleting the last save right after your death or do not place your corpse into the world until you actually go back to the title screen.

**Comment by drbig** [comment] 2015-06-09 20:17
> Yes, but if you close the game after dying it is possible to reload the last save, and find the corpse if the same character with all the items they had on death. So you can both continue from the last save and benefit from the items on your corpse.

Aye. I think this has been a thing here already - I lean towards the 'if you want to do it we wont prevent you' angle, but I don't remember the issue number, nor can find it easily. Let's wait for some more opinions.

**Comment by BevapDin** [comment] 2015-06-09 20:38
> but I don't remember the issue number

#9574, it's indeed not easy to find. Quote from there:

> End of the day, we don't care too much what happens if you circumvent the death processing.

And I think there is at least another issue about that out there.

**Comment by drbig** [comment] 2015-06-09 20:47
Indeed that one. I guess I can thank @narc0tiq for the 'poetic' title :)

I believe a question still remains:
 1. Do we 'fix' it and do the necessary stuff right upon death
 2. We mention it is not a bug somewhere (visible?)

Personally I'm very much impartial to either option, but I believe one has to be chosen (after all we're talking about it *again*).

**Comment by ejseto** [comment] 2015-06-10 00:27
I say just place the corpse after the point of no return. There's no point in trying to prevent cheating in an offline, open-source game. If people want to cheat, they're going to, and there's no way, and no reason, to stop them. Save-scumming is a gray area as well. Not everyone considers it cheating. Duping their items basically forces cheating status on them though (I suppose they could exercise discipline and just burn their old corpse or something, but if they had discipline they wouldn't be scumming in the first place).

**Comment by kevingranade** [comment] 2015-06-10 07:00
If I remember I'll put a entry in the new 'frequently made suggestions'
thread on the forums, but I don't have much hope of that actually resolving
the issue (the issue is people bringing it up, not how the game works).  I
guess item spawn can be moved, that sounds productive, but auto-deleting a
savegame is downright hostile and it's not going to happen.

**Comment by Cat09** [comment] 2015-06-10 22:12
I'm inclined to agree w/ @ejseto In that player corpses should be generated at point of no return .  Not everyone that likes roguelikes necessarily wants permanent death, also, I can see someone just quitting in anger the second they die, and this effect being really weird.

**Closed** 2016-03-10 00:50 UTC
Labels: Bug
