### ISSUE TITLE
Curses closes on minimize

### ISSUE THREAD

**Issue by kungfutreachery** [CleverRaven/Cataclysm-DDA#27394] opened 2019-01-02 01:11 UTC
**Describe the bug**  
When clicking the minimize button, the game closes silently rather than minimizing. The minimize-to-taskbar animation plays correctly before the taskbar icon disappears and cataclysm.exe terminates. There is no error message and the game is not saved.
Closing in this manner causes the game to revert to its default window size on restart.

**To Reproduce**  
Run cataclysm.exe (curses)
Click the minimize button in the top right corner

**Versions and configuration**
 - OS: Windows 7 64-bit; Windows 10 64-bit
 - Game Versions: 8358, 8357 and 8349
 - Graphics version: Console (issue does NOT occur with Tiles)
 - Mods loaded: Issue can be reproduced with any combination of vanilla mods and in main menu prior to world generation

**Additional context**  
I have reproduced this issue on two separate machines (Win7 and 10). It does not happen with tiles, only in the console version. I do not recall this happening prior to today (1/1/2019) on either machine. An example debug log entry is below (3:03.490 is when the game is minimized)

-----------------------------------------
20:02:58.024 : Starting log.
20:02:58.024 INFO : Cataclysm DDA version 0.C-35992-g91756dd
20:02:58.040 INFO : Language is set to: 'en'
20:02:59.062 WARNING : opendir [./mods/] failed with "No such file or directory".
20:03:03.490 : Log shutdown.
-----------------------------------------

**Comment by Night-Pryanik** [comment] 2019-01-02 03:50
Duplicate of #24528.

**Closed by Night-Pryanik** 2019-01-02 03:50 UTC

**Comment by kungfutreachery** [comment] 2019-01-02 03:55
Please note this version of it is silent, it does not throw up a runtime error.
