### ISSUE TITLE
Charcoal kiln picture

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20364] opened 2017-02-24 08:56 UTC
After putting a log into the kiln and lighting it, it shows an orange glow, but even after it's finished, it still shows the orange glow until you remove the charcoal.

 Also, it doesn't show the orange glow if the room is dark.

I was working on other things at the time, while waiting for the kiln to finish, but the orange glow never turned off, so I didn't know when it was done. If I examine it, it shows the time remaining like it supposed to.

**Comment by Eddyskingdom** [comment] 2017-02-24 08:59
can you send a screen shot

**Comment by Coolthulhu** [comment] 2017-02-24 09:07
Marking as long term because fixing this would require adding active furniture/terrain.

**Comment by Grelko** [comment] 2017-02-24 09:36
I placed a log in the kiln and lit it.
http://imgur.com/a/oHhbf "orange glow" 1:28:12 PM

http://imgur.com/a/ALr7m At 9:28:18 Pm "a little over 8 hours later" Charcoal only takes 361 "6 hours 1 minute" to finish. The orange glow is still there.

http://imgur.com/a/qro0M I examine and picked up the charcoal. Orange glow turns off.

http://imgur.com/a/44sAs I placed another log into the kiln and lit it. I turned off my head torch so the room would be dark, and the kiln doesn't have the orange glow.

http://imgur.com/a/7ZVc6 If I light the kiln in a dark room, there is no orange glow, but if you turn on a light, that brightens the spot the kiln is on, then it shows the orange glow.

I'm not sure how it would work if it "naturally" got darker from the sun setting, because I have the kiln too far into the building for the sun to reach it.

**Comment by Night-Pryanik** [comment] 2017-02-24 13:35
Please do not use external picture hosting, use github's internal picture management tool instead.

**Comment by kevingranade** [comment] 2017-02-24 17:14
Why are you asking people to not use external hosting?

**Comment by Night-Pryanik** [comment] 2017-02-24 18:01
Just because it's unconvenient, that's all. (Recently I began receiving errors when trying to enter imgur).

**Comment by int-ua** [comment] 2021-01-26 01:06
Cannot reproduce with Ultica tileset, closing.

**Closed by int-ua** 2021-01-26 01:06 UTC
Labels: (P5 - Long-term), <Bug>, SDL: Tiles / Sound
