### ISSUE TITLE
Constructions: pulley & rope system

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#13562] opened 2015-09-15 20:55 UTC
You're at your dream ranch near the garage, your careless driving made you rip off the lever to open the garage doors... But no problem! You can rebuild it!...

`22:31:36 <        dRbiG> t_barndoor[207] vs t_palisade_pulley[208]`

Nope, it won't work, because you built the latter instead.

A sane 'quick' fix would be to ask what 'type' the player wants to build.

The long-term/better solution is an actual look over the constructions and then figuring out a sane way to handle it (e.g. 'What should this pulley & rope system be connected to?'). I'm quite positive there will be other cases like this one. 'Bob the builder stuff' is obviously one of the least play-tested things.
##

**Comment by vache** [comment] 2015-09-15 21:24
The gate opening system in general is annoying.  There are only a few combinations of wall/floor/door types that work (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/activity_handlers.cpp#L1133).  I understand why this is, but I still feel like there should be a better way.

**Comment by kevingranade** [comment] 2015-09-15 23:55
I agree, I spent hours trying to sort out something better when I extended
it from metal gates to... barn doors I think?  Unfortunately I didn't come
up with anything better.

**Comment by vache** [comment] 2015-09-16 16:07
I was thinking about this a bit more last night, and it seems like the wall_type check could be replaced with something like terrain.has_flag("WALL"), since it doesn't seem like we care exactly what type of wall is there, only that what is there is a wall.  This would get rid of the need for the separate t_gate_controls_concrete.  Next, we could change the controls to furniture instead of terrain, and use floor_type = the terrain under the controls.  This seems like it would get rid of the need for t_gates_control_metal.  To fix the rest, I think we could add a new flag, "GATE".  When you activate gate controls, it checks the diagonals for a terrain with the flag and if it finds it, start setting it to the floor type we determined, or if it finds the floor type (with the correct wall orientation) it tries to close it by setting it back to the terrain, which might have to be defined somewhere in the gate controls JSON as well, just add a "gate_type" field to every gate controls.  Now we can look up that "gate_type" field and say "this gate controls blah blah" in the construction menu.

**Comment by Zireael07** [comment] 2015-09-16 16:23
@vache: +infinity for flag based gates/controls.

**Comment by kevingranade** [comment] 2015-09-17 16:15
Yea, that sounds like it'll work, cool.

**Comment by eliotcougar** [comment] 2016-10-14 00:04
How hard would it be to assign a unique ID to every "toggle-able" terrain and have a list of IDs attached to every "lever-type" furniture?.. Linking existing adjacent levers/doors could be made during mapgen, and when building levers/pulleys there could be a Dwarf Fortress-ish action "attach pulley to..." that would bring the list of available attach points nearby... Different control mechanisms (lever, pulley, terminal) can have different range...
This approach could also allow easier control of doors and possibly other things (turrets/stairs/alarms/elevators) from computer terminals and NPC dialogues...

**Comment by Night-Pryanik** [comment] 2017-02-26 13:03
Will #16368 and #16441 fix this?

**Comment by hexagonrecursion** [comment] 2021-08-09 08:02
This is still reproducible.

Currently barns use t_door_metal_locked for doors. They require t_barndoor to open them. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/9d7ed7d6d918942cf1eedffb40477a3b3b33bf76/data/json/gates.json#L56-L61

Currently t_barndoor **can not** be constructed. t_palisade_pulley can be constructed, but requires the door to be t_palisade_gate.

https://github.com/CleverRaven/Cataclysm-DDA/blob/9d7ed7d6d918942cf1eedffb40477a3b3b33bf76/data/json/gates.json#L71-L75

Both t_barndoor and t_palisade_pulley are displayed as "rope and pulley" in the UI. This causes confusion.

**Comment by I-am-Erk** [comment] 2022-07-21 19:38
If this still exists it can be solved just by calling the barndoor rope and pulley a "barn door opener", or by making these openers into a single pulley system that can open either type of door.

**Closed** 2022-07-23 22:23 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Fields / Furniture / Terrain / Traps, old issue - still valid?
