### ISSUE TITLE
Turrets drop way too much ammo

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#36428] opened 2019-12-25 07:05 UTC
**Is your feature request related to a problem? Please describe.**  
A destroyed CROWS M249 turret (whether killed with EMP or physical damage) drops all of its ammo, which often amounts to 2 full ammo belts. I had an EMP bomb and found a military bunker, so I cut the door open and shoved the EMP bomb inside. 12 free ammo belts of 5.56 NATO.

It kinda makes all other ammo types marginal. Also, there is no incentive to use your military ID card because then the turrets just disappear and leave no ammo.

**Describe the solution you'd like**  
1) Turrets inside the military bunker should have less ammo, but at the same time if you deactivate them using a military ID, you should be able to pillage them for ammunition.
2) Turrets in roadblocks should spawn with less ammo if a lot of time has passed since the cataclysm.

**Describe alternatives you've considered**  
Turrets deactivated via a military ID might slide into the floor, turning into a "furniture" that would take significant skill to take apart and get to the ammo.

**Additional context**  
I noticed that EMP grenades can no longer be crafted, so perhaps this isn't as much of an issue as I think. But it definitely marginalizes most ammunition other than 5.56 NATO.

**Comment by Night-Pryanik** [comment] 2019-12-25 07:19
There is identical, however closed, issue on this matter - #33951.

**Comment by anothersimulacrum** [comment] 2019-12-25 07:23
I think it'd probably be best to just reopen that issue.

**Comment by Night-Pryanik** [comment] 2019-12-25 07:32
If I'm not mistaken, we have a convention that we keep in mind even stale issues closed due to inactivity. So I think, it'd be better to close this one and don't reopen that one unless someone has to say something new on this matter.

**Comment by ymber** [comment] 2019-12-25 08:09
Yeah this is a duplicate of however many other issues there are for this. The proper solutions are knows, someone who's interested just needs to implement them.

**Closed by ymber** 2019-12-25 08:09 UTC
Labels: <Suggestion / Discussion>, Game: Balance, Monsters

**Comment by Marrim** [comment] 2019-12-25 08:13
I skimmed over the other issue and it doesn't seem to mention the problem with the ammo being unavailable when you deactivate the turrets via an ID card.

**Comment by ymber** [comment] 2019-12-25 08:19
The way turret despawning works needs refactoring and some of it moving out to JSON. If we want turrets to stay spawned but deactivated it can be handled as part of this.
