### ISSUE TITLE
excessive zombie numbers in town

### ISSUE THREAD

**Issue by Dlightfull** [CleverRaven/Cataclysm-DDA#67885] opened 2023-08-25 08:23 UTC
### Describe the bug

There's a small town i am trying to clean, but it has an excessive number of zombies. I've already killed several hundred only in the outskirts of the town and there are hundreds more out there.

I haven't even gotten to the first crossroads yet... 

Is this normal, or my save is broken?

### Attach save file

[Menifee-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12437121/Menifee-trimmed.tar.gz)

### Steps to reproduce

don't think you can reproduce that.

### Expected behavior

I expected to find several dozen zombies there, but definitely not in the hundreds.

### Screenshots

![149 zombies in town outskirt](https://github.com/CleverRaven/Cataclysm-DDA/assets/140479772/4041eccf-9f83-4327-b86c-092ec214ea9c)
![map of town](https://github.com/CleverRaven/Cataclysm-DDA/assets/140479772/6c8a7d82-1250-4c69-9595-4e6ba3ff41fc)
![kill count](https://github.com/CleverRaven/Cataclysm-DDA/assets/140479772/5563fecb-27c2-4556-abce-1a85e87cc844)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3324 (21H2)
- Game Version: 155445d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Sly's Skill Antirust [slysskillantirust]
]

### Additional context

At some point i got the impression that zombies were spawning out of thin air, since they appeared in an area that i had previously cleaned. At that point i've seen some messages about zombies falling from a ledge (they were near a regular house) so i assume they somehow appeared on the roof of the house.

**Comment by Zireael07** [comment] 2023-08-25 09:01
Already reported AFAIK?

**Comment by waifusd** [comment] 2023-08-25 09:24
#67837

**Comment by ZhilkinSerg** [comment] 2023-08-25 19:09
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/67837

**Closed by ZhilkinSerg** 2023-08-25 19:09 UTC
Labels: (S1 - Need confirmation)
