### ISSUE TITLE
Russian Corrosive Crash 

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20716] opened 2017-03-28 18:09 UTC
Set language to Russian (can't reproduce with English)
Load world
// fight with glaive against unseen corrosive zombie standing in window frame
hit `F`
hit `left`
hit `up`
hit `up`
hit `F`
(maybe repeat fight once again)
![1](https://cloud.githubusercontent.com/assets/1931904/24419371/94f54c30-13f7-11e7-8c82-36438bcfa7f5.png)

Reproduced dozens of times, but not 100%.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/876542/save.zip)

Also one time crashed immediately after hitting player through the glass.
![2](https://cloud.githubusercontent.com/assets/1931904/24419393/a416642e-13f7-11e7-92cf-b8ca4c27d06f.png)

p.s.: Screens of game window made already under "application crashed"-window.

**Comment by AMurkin** [comment] 2017-03-28 18:36
I think it's special_attacks of mon_zombie_corrosive

**Comment by Toothspit** [comment] 2017-03-28 19:30
Can't reproduce on Linux x64 tiles gcc.

**Comment by Night-Pryanik** [comment] 2017-03-28 20:08
Confirming on 0.C-6365, Win 10 x64, tiles. 
Working fine on English, French, German (didn't test other), only Russian is affected.

**Comment by BrettDong** [comment] 2017-03-31 12:37
It's because of the improper Russian translation of the sentence:

> You avoid an incoming projectile!

It is translated to `Вы уклонились от приближающегося снаряда %s!`, the mistakenly added `%s` causes the crash.

**Comment by Night-Pryanik** [comment] 2017-03-31 13:14
Yeah, it seems that was my fault. 
Fixed it.

**Comment by BrettDong** [comment] 2017-03-31 14:35
The corrected translation will be merge to GitHub in next few days.

**Comment by Night-Pryanik** [comment] 2017-04-06 09:28
Should be closed after #20787.

**Comment by BrettDong** [comment] 2017-04-06 10:02
Can you confirm that the crash is fixed after #20787 got merged?

**Comment by Night-Pryanik** [comment] 2017-04-06 11:48
>Can you confirm that the crash is fixed after #20787 got merged?

Confirming, crash is fixed.

**Closed** 2017-04-06 16:24 UTC
