### ISSUE TITLE
Crashing near refugee center

### ISSUE THREAD

**Issue by dgs6686** [CleverRaven/Cataclysm-DDA#34400] opened 2019-10-02 17:45 UTC
I am encountering a crash after arriving at the refugee center that happens every 10-15 steps after loading my game back in. I am not positive this is caused by the refugee center as I see an error about a robot dispatch center in my logs.

I am not sure this is easily reproducible outside of loading my save file and walking around a little bit.

Expected behavior:
The game should not crash, ideally.

# Versions and configuration
- OS: Windows 10 home 64bit
    - OS Version: 10.0 1809
- Game Version: 0.D-8159-g6363709 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3682500/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3682501/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3682514/save.zip)

**Comment by ZhilkinSerg** [comment] 2019-10-02 20:29
Duplicate of #34397

**Closed by ZhilkinSerg** 2019-10-02 20:29 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
