### ISSUE TITLE
Spoilable Items Clog Inventory Views

### ISSUE THREAD

**Issue by OrenAudeles** [CleverRaven/Cataclysm-DDA#24498] opened 2018-07-27 08:04 UTC
### Issue:
Spoilable items in Cataclysm currently do not stack if they have differing rot timers. This will often lead to situations where batch crafting comestibles such as Pemmican, Fruit Leather, in large amounts will fill the inventory with many stacks that cannot be combined. As time-to-rot extends into the future the player gets progressively less concerned with that value.

### My opinion:

I think that a progressive granularity system would work best. This system would group like items that are unable to be stacked due to differing rot times into more useful sets. I propose the following groupings:

* 1 year +
* 1 season - 1 year
* 1 week - 1 season
* 1 day - 1 week
* 1 turn - 1 day

At less than 1 day until spoilage it might be undesirable to group comestibles

Selecting a comestible for consumption from a granular group should consume an item that will rot at the nearest future point in time.

Implementation of this granular grouping may be done entirely as a UI construction whenever opening a relevant UI. There will be times that finer detail grouping is necessary, and a sorting option/toggle may be desirable. Because grouping is a UI construction it will have no effect on the comestibles directly and allow them to be grouped dynamically as conditions change.

Example Cluttered Inventory: Red boxed comestibles can be compressed (not comprehensive)
![cata_food_stacking](https://user-images.githubusercontent.com/8597997/43309029-2ee617fa-9149-11e8-9996-214c2898036b.png)

Example Grouped Inventory: Red arrowed comestibles have been compressed (not comprehensive)
![cata_food_stacking_compressed](https://user-images.githubusercontent.com/8597997/43309073-54a5d9b2-9149-11e8-9952-55fbd86e2f84.png)

Please share your thoughts, concerns, and ideas so we can find a viable solution to this issue.

**Comment by cainiaowu** [comment] 2018-07-27 08:45
Actually there are already some info about item freshness in the item info already. 
We really need to group items with same freshness into one group for display.

**Comment by FulcrumA** [comment] 2018-07-27 12:12
Stacking in general seems to be requiring some work and is inconsistent on several fronts (#23528, #23946,  #23933).

**Comment by kevingranade** [comment] 2018-07-27 22:02
I prefer your approach of doing the stacking at the UI level, there are all kinds of issues caused by the fact that we try to stack things at the item level.

**Comment by kevingranade** [comment] 2018-07-27 22:15
To be more concrete:
Re: #23528 you want to be able to read the different snippets sometimes, but other times it's clutter.
Menus might want to do grouping differently.

**Comment by kevingranade** [comment] 2019-01-10 00:59
Fixed by #26523

**Closed by kevingranade** 2019-01-10 00:59 UTC
Labels: <Suggestion / Discussion>, Info / User Interface
