### ISSUE TITLE
hand press and die set + firearm repair kit = are not accepted in crafting if with UPS on it.

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20897] opened 2017-04-22 18:18 UTC
hand press and die set / firearm repair kit are not accepted in crafting if they have UPS integrated.
Maybe there are more tools that are not seen in crafting anymore if they have ups on it.

**Comment by ZenZen2** [comment] 2017-04-22 18:26
Additional info: they are seen if the recipe needs charges of them, else they show red.
Best way to test, check ammunition, many recipes need hand press and die set without charges.

**Comment by cdag** [comment] 2017-04-26 13:10
This is also the case if you install a battery compartment mod on it.

**Comment by CoroNaut** [comment] 2017-05-01 18:10
Duplicate of #17932

**Closed** 2017-05-01 18:59 UTC
Labels: Bug, Crafting, Duplicate
