### ISSUE TITLE
False "Does not fit" tag on Survivor Goggles

### ISSUE THREAD

**Issue by DocGhast** [CleverRaven/Cataclysm-DDA#36739] opened 2020-01-05 23:01 UTC
# Describe the bug

Survivor Goggles display the line "This clothing is Oversized and does not fit you" even when it does fit. 

# Steps To Reproduce

Craft a pair of Survivor Goggles and examine them. 

# Expected behavior

Survivor Goggles that fit should not display the line indicating that they do not fit. 

# Screenshots

![Capture](https://user-images.githubusercontent.com/52557988/71787371-a3210580-3062-11ea-8055-b6724744be72.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10803-gfe5ba30 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Doc's Tweaks [Doc_Tweaks],
    Stats Through Skills [StatsThroughSkills],
    Safe Autodoc [safeautodoc]
]

# Additional context

The item is treated as though it does fit, and the encumbrance reflects that, it's just the line of text that suggests otherwise and causes confusion. 
Resizing the item did not remove the warning.

**Comment by Night-Pryanik** [comment] 2020-02-07 15:58
Duplicate of #36180.

**Closed by Night-Pryanik** 2020-02-07 15:58 UTC
Labels: <Bug>, Info / User Interface, Items / Item Actions / Item Qualities
