### ISSUE TITLE
Gibed monster meat breaks things.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#26034] opened 2018-10-03 18:29 UTC
**Describe the bug**  
When monsters gibs upon death the flying meat can break windows, benches, and maybe vehicles.
A [reddit user pointed this out](https://www.reddit.com/r/cataclysmdda/comments/9kohiu/what_is_the_exiting_veolocity_of_giant_cockroach/). I was able to confirm that gibs break windows and benches.
The parts do make a sound indicating that something was hit. 

**To Reproduce**  
1. Debug 50 strength, Krav Maga.
2. Spawn a turkey next to a window and kill it.
3. Repeat until gib meat breaks the window.

**Expected behavior**  
I don't think gibbed monster bits should break anything.
If this is intended behavior, that's fine and I'll delete the issue.

**Screenshots**  
This is my attempt. I tried blowing the turkey up next to the kitchen terrain but moved to the window when that didn't work.  I used a mop to clean up the window so it would be clear that it's broken.
![image](https://user-images.githubusercontent.com/17521661/46430828-c5193300-c70f-11e8-9a38-9ecf63a14a24.png)

Screen shot from a redditor.
![image](https://user-images.githubusercontent.com/17521661/46430889-f42fa480-c70f-11e8-8c92-a8f15b138903.png)

**Versions and configuration(please complete the following information):**
Windows 10x64
Current experimental version via the launcher
Tiles
Default mods.

**Comment by alanbrady** [comment] 2018-10-03 20:49
I'm not sure if this intended or not, but it *is* hilarious.

**Comment by Endovior** [comment] 2018-10-03 20:56
No, that seems reasonable. When you're hitting something hard enough that it explodes into pieces, it's not at all strange that those flying pieces might break fragile things. Put another way, it's expected behaviour that the Hulk can punch a turkey through a plate glass window.

The fact that it's also _hilarious_ is beside the point.

**Comment by justin-carver** [comment] 2018-10-03 20:58
I just feel like no mere mortal can have enough power to smack something so hard, the gibs have enough kinetic energy to blow glass up, but yeah, this is great.

**Comment by rtizzy** [comment] 2018-10-05 07:46
@justin-carver 

No mere mortal has the power to punch anything aside from a bug so hard that it gibs either :P.

**Comment by FulcrumA** [comment] 2018-10-07 03:03
>When you're hitting something hard enough that it explodes into pieces, it's not at all strange that those flying pieces might break fragile things.
The issue here is that the damage causing things to explode is relative. Despite being made of the same material at times, weak enemies are much more prone to exploding than the stronger ones when the unprotected tissue itself should be as easy/hard to explode in both. Aside from that the strength suitable to break things apart upon and make them splash doesn't mean that the pieces will have enough momentum etc themselves to damage anything. Lastly, the issue has things that shouldn't be breakable as easily - break.

Coupled with the fact that when attacking enemies the player cannot really choose strength of the hits of their character (only cripple character's ability by subjecting them to negative effects or using subpar weapons), the effect of dealing the damage to certain creatures may be a bit unfair and the result of such excessive damage considered a punishment for getting powerful, which is a thing that should be avoided.

**Comment by TealcOneill** [comment] 2024-05-23 19:27
@GuardianDll No longer reproducible. I think this was fixed by #46851
- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Closed** 2024-05-23 21:02 UTC
Labels: <Bug>, Game: Balance, Items / Item Actions / Item Qualities

**Comment by casswedson** [comment] 2024-05-23 23:04
here's how to test this bad boy, get bloody mess from bombastic perks and kill something near a car:
![Screenshot_2024-05-23_17-58-32](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/f12c667c-3f1f-4408-a973-566b957dfae3)
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 9640195 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]
