### ISSUE TITLE
Removing a vehicle part with extra install component doesn't return them

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#33281] opened 2019-08-16 18:45 UTC
# Describe the bug

When installing a vehicle part with more than one install component, the subsequent removal does not return the extra component.
 See: wooden frames and parts, the travois, aisle curtains, chitin plating, the new strapped mattress, and probably more.

# Steps To Reproduce
Wish up a couple light wooden frames and a short rope. Start a vehicle construction, then tie a light wooden frame to it, then remove it. Presto, the rope vanishes into thin air!

# Expected behavior

The extra components should be reusable, unless there's a reasonable expectation they'd be destroyed in the process. I could see losing at least some of the nails on the wooden frames/parts, but most should come back out intact, and untying ropes should return them.

# Versions and configuration
Latest experimentals on back to Whales days I believe, all systems.

# Additional context

**Comment by Night-Pryanik** [comment] 2019-08-19 17:01
Duplicate of #22938.

**Closed by Night-Pryanik** 2019-08-19 17:01 UTC
