### ISSUE TITLE
Frying pan, water bug, 15173-gd8ae19c

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#17190] opened 2016-06-15 08:30 UTC
version 0.C-15173-gd8ae19c ,  if you have clean water in a frying pan, then go to pick it up, it gives you 2 choices. Either wield it, or spill the water first. If you wield it, it spills the water on the floor also, but you still have it in the frying pan when it gets wielded, doubling the water, except you can't pick up a liquid.

I haven't tried this with regular water, other liquids, or other "open" containers.

**Comment by BevapDin** [comment] 2016-06-15 08:40
Duplicate of #17041?

**Closed** 2016-06-16 07:49 UTC
