### ISSUE TITLE
Filthy clothing is colored and named even without filthy mod

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20454] opened 2017-03-04 23:09 UTC
When playing without filthy mod, it has no effects and the different color is misleading.
I'd keep the filthiness in the description, but remove the coloring and name when playing without the mod.

**Comment by DangerNoodle** [comment] 2017-03-05 00:17
I would consider it evidence to not trust whether the alleged mod-only effects can not be guaranteed to only show up with the mod. It may be paranoid on my part, but it was been reason enough for me to completely avoid filthy clothing even without the mod. I would hope that I am not the only player to act in the same manner.

**Comment by Night-Pryanik** [comment] 2017-03-05 06:21
Maybe I'm doing something wrong, but there are no option to turn off the filthy clothing even with the mod in latest experimental.
![default](https://cloud.githubusercontent.com/assets/11132525/23585030/01dc5402-018c-11e7-9763-d8859472e34c.PNG)
![1](https://cloud.githubusercontent.com/assets/11132525/23585032/1bd1cdba-018c-11e7-8f09-a0cfbe02a786.PNG)

The same is right for "Disable NPCs needs" mod too.

Removing `COPT_ALWAYS_HIDE` from 
```
add("FILTHY_MORALE", "world_default", _("Morale penalty for filthy clothing."),
_("If true, wearing filthy clothing will cause morale penalties."),
false, COPT_ALWAYS_HIDE
```
gives ability to change this option, and with it turned off, filthy clothing is no longer colored and named.

**Comment by kevingranade** [comment] 2017-03-05 06:26
On Mar 4, 2017 3:09 PM, "Coolthulhu" <notifications@github.com> wrote:

When playing without filthy mod, it has no effects and the different color
is misleading.

The clothing has an undesirable trait, regardless of whether it has an
impact.  This is working as intended.

If you're concerned about it being unclear, we could add a descriotion of
the effects to the attribute description and toggle those with the mod, but
I don't see how "these clothes are filthy" is confusing to anyone, they are.

**Comment by kevingranade** [comment] 2017-03-05 06:41
On Mar 4, 2017 10:21 PM, "Anton Burmistrov" <notifications@github.com>
wrote:

Maybe I'm doing something wrong, but there are no option to turn off the
filthy clothing even with the mod in latest experimental.
[image: default]
<https://cloud.githubusercontent.com/assets/11132525/23585030/01dc5402-018c-11e7-9763-d8859472e34c.PNG>
[image: 1]
<https://cloud.githubusercontent.com/assets/11132525/23585032/1bd1cdba-018c-11e7-8f09-a0cfbe02a786.PNG>

The same is right for "Disable NPCs needs" mod too.



Removing the mods is what turns the feature off, you aren't expected to
also toggle an option.

Removing COPT_ALWAYS_HIDE from

add("FILTHY_MORALE", "world_default", _("Morale penalty for filthy clothing."),
_("If true, wearing filthy clothing will cause morale penalties."),
false, COPT_ALWAYS_HIDE

gives ability to change this option, and with it turned off, filthy
clothing is no longer colored and named.


That shouldn't happen, but you're also making arbitrary changes to the code
so *shrug*, you get to keep the pieces after breaking it.

**Comment by Night-Pryanik** [comment] 2017-03-05 07:03
> That shouldn't happen, but you're also making arbitrary changes to the code so *shrug*, you get to keep the pieces after breaking it.

Could you please clarify what do you mean by "That"?

**Comment by Coolthulhu** [comment] 2017-03-05 10:23
> Maybe I'm doing something wrong, but there are no option to turn off the filthy clothing even with the mod in latest experimental.

The mod sets a given option.
The modoptions.json has an "options" field, which sets all the flags on it to `true`.

So basically, when the mod is in a world, that specific flag is set.

**Comment by Night-Pryanik** [comment] 2017-03-05 11:19
> The mod sets a given option.
The modoptions.json has an "options" field, which sets all the flags on it to true.
So basically, when the mod is in a world, that specific flag is set.

So, if this mod is not selected at the moment of world creation, then the flag to create filthy clothing is `false`, right?

**Comment by Coolthulhu** [comment] 2017-03-05 11:25
> So, if this mod is not selected at the moment of world creation, then the flag to create filthy clothing is false, right?

Yes, assuming everything works correctly.
There are some bugs in options code, but disabling coloring when the option is disabled can only help to find said bugs.

**Comment by Night-Pryanik** [comment] 2017-03-05 11:29
> Yes, assuming everything works correctly.

It seems that at the moment it is not. 
Tested right now, creating world without filthy mod still gives coloring and suffix.

**Comment by Coolthulhu** [comment] 2017-03-05 11:31
Wait, I misread your question.

Setting the flag off will still spawn filthy clothing, it will only prevent it from having morale penalties and infection chance. This is why the coloring and suffix are wrong here.

**Comment by Night-Pryanik** [comment] 2017-03-05 12:09
> Removing COPT_ALWAYS_HIDE from

>add("FILTHY_MORALE", "world_default", _("Morale penalty for filthy clothing."),
_("If true, wearing filthy clothing will cause morale penalties."),
false, COPT_ALWAYS_HIDE

>gives ability to change this option, and with it turned off, filthy clothing is no longer colored and named.

Then why explicitly setting option off prevents coloring and suffix to appear?

**Comment by Coolthulhu** [comment] 2017-03-05 12:17
> Then why explicitly setting option off prevents coloring and suffix to appear?

Does it? I don't see anything in the code doing that.

**Comment by Night-Pryanik** [comment] 2017-03-05 12:29
![111](https://cloud.githubusercontent.com/assets/11132525/23587217/d19e510c-01c0-11e7-82cb-43c0251c51ee.PNG)
![222](https://cloud.githubusercontent.com/assets/11132525/23587218/d8cb86e8-01c0-11e7-9cb2-b2377d4cc816.PNG)
![333](https://cloud.githubusercontent.com/assets/11132525/23587220/dcf1a680-01c0-11e7-92cc-8f5363cdb804.PNG)
![444](https://cloud.githubusercontent.com/assets/11132525/23587223/e0bf5834-01c0-11e7-9e96-2f2d15424bc9.PNG)
![555](https://cloud.githubusercontent.com/assets/11132525/23587224/e3c46b96-01c0-11e7-88ea-1c1d4c05f82c.PNG)
![666](https://cloud.githubusercontent.com/assets/11132525/23587226/e6f37ba4-01c0-11e7-96d7-5608f25cf180.PNG)

**Comment by Night-Pryanik** [comment] 2017-03-05 12:32
That's not the last version, e.g. there is no filthy wounds option, but I don't think it matters.

**Comment by Coolthulhu** [comment] 2017-03-05 12:40
That's really weird considering the filthiness code currently doesn't really care about the flags except when applying the effects.
The monster "filthify drops" function doesn't check any flag, neither does `item::is_filthy()` nor any of the coloring/suffix functions. At least in master.

**Comment by Night-Pryanik** [comment] 2017-03-05 13:21
Oh, I think I got it now. The problem was in `item::is_filthy()` not checking for flag.
Sorry for all my pics and incorrect statements as they were made due to my unclean testing.

**Comment by DangerNoodle** [comment] 2017-03-06 15:35
This is unfortunate.

**Comment by kevingranade** [comment] 2017-03-07 04:13
Repeat for clarity, I merged @Night-Pryanik's PR reversing this.
Ok I'm convinced I'm in the wrong here, sorry for being stubborn about it.

In particular, closing this with "bla is invalid" was rude, my intent was, "discussion should happen over there", but obviously my carelss and abrupt wording didn't get that across.

Thanks for everyone her, on the forums and on discord for setting me straight.

**Closed by kevingranade** 2017-03-07 04:13 UTC
Labels: Bug, Information / Interface
