### ISSUE TITLE
Animal Empathy trait not working as advertized

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#23378] opened 2018-04-05 05:58 UTC
Game version: 0.C-26854-g8d6cdbf

Operating system: Win 7

Tiles or curses: Tiles

Mods active: Default (novitamins, filthy_morale)

### Expected behavior
Small woodland animals (like turkeys and rabbits) not running away from me when I have Animal Empathy trait.
Alternatively: Animal Empathy trait not advertising "Peaceful animals not running away from me"

### Actual behavior
Turkeys run away from me when I have Animal Empathy trait

### Steps to reproduce the behavior
Start a new character with Animal Empathy trait.
Read the description of the trait: "Peaceful animals will not run away from you <...>"
Try to get near small woodland animals.
Observe them "Fleeing!"

**Comment by Night-Pryanik** [comment] 2018-04-05 07:02
That's not a bug IMO. Turkeys are scared too much by everything, even Animal Empathy can't cope with their fear - their morale by default is -8, and Animal Empathy reduces it only to -3.

The formula is

```
if( effective_morale < 0 ) {
        if( effective_morale + effective_anger > 0 && get_hp() > get_hp_max() / 3 ) {
            return MATT_FOLLOW;
        }
        return MATT_FLEE;

```

So after applying Animal Empathy their `effective morale` is -3, `effective morale + effective anger` = -3 + -70 = -73 which of course is lesser than zero, so turkeys WILL flee.

**Comment by moxian** [comment] 2018-04-05 09:44
Here are all the wildlife monsters with negative base morale from monsters.json:
-5: deer jackrabbit
-7: rabbit
-8: chicken crow duck squirrel turkey
-20: groundhog
-50: lemming muskrat
-55: chipmunk

Since the trait only raises morale by 5, it should only ever work against deer and jackrabbits, but the description implies its much wider applicability. I don't know how the numbers were chosen.

I took the trait expecting to be able to specifically hunt those small animals in peace, and not use a bike/car to catch up to them. But given how it's only useful against deer (and I don't think I've seen those ever), that doesn't sound very exciting.

**Comment by Leland** [comment] 2018-04-05 21:12
Could also have animal empathy override animal fear altogether so that future, lower values wouldn't suffer the same issue.

**Comment by kevingranade** [comment] 2018-04-05 22:08
Increasing the number seems fine, as long as it doesn't make them stick
around while being shot at.

**Comment by Wuzzy2** [comment] 2018-04-09 10:13
At the very least the description should be fixed because as of now it is obviously wrong.

**Closed** 2018-04-10 05:05 UTC
Labels: (S2 - Confirmed), <Suggestion / Discussion>, Mutations / Traits
