### ISSUE TITLE
Weapon loss message is very easy to miss

### ISSUE THREAD

**Issue by Skidborg** [CleverRaven/Cataclysm-DDA#14300] opened 2015-12-04 04:57 UTC
I've been playing as a strength 4 characters recently, so I've been encountering this issue a lot.

The single line warning that my weapon has been lost is extremely easy to miss in combat and noise spam. This seems like an event worth of a pop-up warning along the lines of "You have been disarmed. Wield new weapon? Y/N" given the consequences for not reacting immediately, and the lack of visual representation on the playing field.

**Comment by vickio** [comment] 2015-12-04 06:05
Agreed. There's been a few times when I've been like "wait, why has my unarmed combat skill just increased?"

**Comment by Headjack** [comment] 2015-12-04 06:42
I think there should be varied 'weights' to some messages, that cause them to retain color as they rise through the message ticker. Something like that or 'you pull the pin on the grenade' or whatever should stay red longer where other messages go grey, to demand attention.

**Comment by sparr** [comment] 2015-12-04 07:14
I've been wanting to add another column next to the body part health bars for item durability/protection. The entry next to Power would relate to your weapon, and you would always be able to see if your weapon was missing (or empty, or damaged). Would that be helpful to you?

**Comment by Griffinhart** [comment] 2015-12-04 08:32
Another problem is that if you're playing with z-levels on, and are standing over a lab or a vault, and aren't deaf, the message log is filled with `From the [direction] and below you hear [noise]!` every single turn.

**Comment by Skidborg** [comment] 2015-12-04 15:04
Right now the weapon you're wielding already shows up in the hud there and yeah, if you check it, you can see.  I'm not sure adding more info there would help this issue, since it add more information to lose the high priority details in. If you're concentrating on the middle of the screen where the action/damage/stuns are displayed you'll probably miss it for a turn or two at least. 

The bigger problem may be with zombie technicians and their ability to steal a weapon from you in a moving vehicle. The weapon stolen message is exactly the same color as the windchill warnings.  If you pass a zombie horde in the distance there's a fair chance your weapon will get jacked with no effective alert.  Worse, when you notice later you can't go back and get it because the zombie techs will rejoin the horde and wander off to distant lands.  I lost a morningstar and a pneumatic bolt driver that way on separate occasions.

**Comment by mugling** [comment] 2016-08-11 13:58
Duplicate of #1323

**Closed by mugling** 2016-08-11 13:58 UTC
Labels: Information / Interface
