### ISSUE TITLE
Follower wielding two-way radio "doesn't have a radio"

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75458] opened 2024-08-04 20:33 UTC
### Describe the bug

A follower who is wielding a two-way radio is not considered to have a radio for communication purposes

### Attach save file

[New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16488838/New.Mind-trimmed.tar.gz)

### Steps to reproduce

1. Have two-way radio
2. Make follower wield two-way radio
3. Move away a bit and try to contact them via the follower menu

### Expected behavior

Follower who is physically holding a radio is counted as having a radio

### Screenshots

![radio](https://github.com/user-attachments/assets/97d9a5cd-6cb2-4add-a4ae-1169d9ad821f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 09410b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    My personal mod [terror_mod]
]

**Comment by Terrorforge** [comment] 2024-08-04 20:51
![image](https://github.com/user-attachments/assets/080207fa-13b6-4d26-98f5-c287c1e1ffde)
Suddenly she does have a radio again? In the save I have just now ordered her to go to a temporary holding location, so maybe this only happens while they're on the move?

**Comment by Antrocon** [comment] 2024-08-05 14:53
can confirm. had to distribute bayonets to my npcs so they'd stop wielding radios and start to actually use them

**Comment by Brambor** [comment] 2024-08-14 10:25
This could be an easy fix, but I never played with radios. I will look into it now.

**Comment by Brambor** [comment] 2024-08-14 13:33
I cannot reproduce with the save.

**Comment by Terrorforge** [comment] 2024-08-14 14:03
Oh, huh. I removed that from the mod list, but I guess it's baked in there somehow.

Shouldn't be any trouble, though. By the time I removed it, it was just a custom trait I didn't end up using and some .json settings at default values. Just unfortuante it's throwing errors about it.

**Comment by Brambor** [comment] 2024-08-14 14:05
I am closing this then as completed. Feel free to reopen if it happens again and you reproduce it!

**Closed by Brambor** 2024-08-14 14:05 UTC
Labels: NPC / Factions, (S1 - Need confirmation)

**Comment by Terrorforge** [comment] 2024-08-14 14:14
Sure thing.
