### ISSUE TITLE
(Update issue?) Glitches & Crashing with "M"

### ISSUE THREAD

**Issue by Jackhammr** [CleverRaven/Cataclysm-DDA#36553] opened 2019-12-30 10:00 UTC
# Describe the bug
Game crashes when placing plastic chunks into my APC's cargo container while holding M. Might be more general. Related bug is that both me and one other user on Discord have been having problems where M only places 2 objects at a time, so this might be related to a recent update.

# Steps To Reproduce

1. Grab a large number of plastic chunks.
2. Attempt to deposit them into a APC's Cargo Carrier. Have to hold M. You should find that you deposit only 2 at a time, and a crash eventually happens (I got mine at 144 chunks remaining in my inventory.)
Note: I didn't try to reproduce this behavior with anything else. Might not be this exact.

# Expected behavior

Game crashes with popup, Windows notifies that "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

# Screenshots

https://prnt.sc/qhfrnt -- just in case the .txt differs from my pop-up, somehow.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Note from me: I'm on Windows 8.1 Pro, but my computer's slightly corrupted. Not sure why. Tried to solve it for years.]
- Game Version: 0.D-10828-gc532fc4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Garden Pots [growable-pots],
    No Freeze [no_freeze],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Alternative Map Key [alt_map_key],
    More City Locations [cityside],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
When replicating the crash, I tended to deposit chunks into the space to my right (pressed 5). Dunno if that matters at all. Basically, to replicate this exactly, load the save, press /, press 5, go to plastic chunks, hold M.
[Urban Junglish.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4009427/Urban.Junglish.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4009428/config.zip)

<!-- Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.
    - Your save file (zipped)

**Comment by KorGgenT** [comment] 2019-12-30 14:13
#36554 possibly related

**Comment by ZhilkinSerg** [comment] 2020-01-02 15:42
Duplicate of #36554

**Closed by ZhilkinSerg** 2020-01-02 15:42 UTC
