### ISSUE TITLE
Crashed after walking around

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#34410] opened 2019-10-02 23:53 UTC
I'm on a fresh install with a new world and a new character. I was walking about without any issues until my game crashed out of the blue. I'm on build 9702 using the MSX Deadpeople tileset without any mods. The crash log message was about a "SIGSEGV: Segmentation fault" and I'll attach the logs and my save file to this post. 

Sorry that this isn't formatted properly but I honestly don't know why this is happening, much less how to reliably reproduce the issue other than walking about for a while. The first time it happened I reinstalled the game, the tileset, and started over from scratch to try and fix the problem. It didn't do anything so I'm at a loss to what's happening.

Save: [Trees Mills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3683868/Trees.Mills.zip)
Logs: [Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3683865/Logs.zip)

Edit: I was unsure if it was due to using the MSX Deadpeople tileset, so I loaded the Retrodays tileset. The crash still happened. Also, it conveniently crashed soon after I had loaded up a Remington 870 and starting firing off some shots... just throwing that out there.

![Screenshot (128)](https://user-images.githubusercontent.com/44004977/66089814-bf3a7580-e54e-11e9-84f6-45b0e5a09731.png)

**Comment by anothersimulacrum** [comment] 2019-10-03 00:18
Duplicate of #34397

**Comment by Myobu1** [comment] 2019-10-03 00:23
> Duplicate of #34397
In my case I wasn't attacking any zombies. I was walking about firing shots randomly to see if changed anything. Although, I'll take your word for it on it being the same issue as #34397. Far more knowledgeable people than I out there after all.

**Comment by anothersimulacrum** [comment] 2019-10-03 00:57
If you look at the rest of issues referenced in that issue, you'll see we had a spate of issues about this bug - #34409 should fix it though.

**Comment by KorGgenT** [comment] 2019-10-03 01:11
closed because it's a duplicate. if the linked PR above doesn't fix it, please ping me and i'll reopen.

**Closed by KorGgenT** 2019-10-03 01:11 UTC

**Comment by gcmartinelli** [comment] 2019-10-03 03:17
@KorGgenT Just had a fresh intall on arch linux with the latest build. Getting segfault as described by OP.

 Here is the crash log:
```
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-8159-g636370985c
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x43) [0x5593153e5d6b]
	./cataclysm-tiles(+0x56a549) [0x5593153d5549]
	./cataclysm-tiles(+0x56a75f) [0x5593153d575f]
	/usr/lib/libc.so.6(+0x3a7e0) [0x7efdd4e317e0]
	./cataclysm-tiles(_ZN3map17creature_in_fieldER8Creature+0xdc) [0x5593156911c4]
	./cataclysm-tiles(_ZN3map9add_fieldERK8tripoint6int_idI10field_typeEiRK13time_duration+0x19c) [0x55931566097a]
	./cataclysm-tiles(_ZN3map19set_field_intensityERK8tripoint6int_idI10field_typeEib+0x95) [0x559315660f27]
	./cataclysm-tiles(_ZN3map12add_splatterE6int_idI10field_typeERK8tripointi+0xdc) [0x55931566103c]
	./cataclysm-tiles(_ZN3map18add_splatter_trailE6int_idI10field_typeERK8tripointS5_+0x94) [0x559315661108]
	./cataclysm-tiles(_ZN17activity_handlers12pulp_do_turnEP15player_activityP6player+0x35e) [0x55931527a28a]
	./cataclysm-tiles(_ZNKSt8functionIFvP15player_activityP6playerEEclES1_S3_+0x24) [0x5593152b52fe]
	./cataclysm-tiles(_ZN15player_activity7do_turnER6player+0xc0) [0x55931591161a]
	./cataclysm-tiles(_ZN4game16process_activityEv+0x79) [0x55931548029d]
	./cataclysm-tiles(_ZN4game7do_turnEv+0x21a) [0x55931549fdba]
	./cataclysm-tiles(main+0x1248) [0x5593151e80e5]
	/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7efdd4e1dee3]
	./cataclysm-tiles(_start+0x2e) [0x55931526632e]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	??:?
	log_crash
	crash.cpp:?
	signal_handler
	crash.cpp:?
	??
	??:0
	map::creature_in_field(Creature&)
	??:?
	map::add_field(tripoint const&, int_id<field_type>, int, time_duration const&)
	??:?
	map::set_field_intensity(tripoint const&, int_id<field_type>, int, bool)
	??:?
	map::add_splatter(int_id<field_type>, tripoint const&, int)
	??:?
	map::add_splatter_trail(int_id<field_type>, tripoint const&, tripoint const&)
	??:?
	activity_handlers::pulp_do_turn(player_activity*, player*)
	??:?
	std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
	??:?
	player_activity::do_turn(player&)
	??:?
```

**Comment by anothersimulacrum** [comment] 2019-10-03 03:34
That's from the commit before the commit fixing this, try updating.

**Comment by gcmartinelli** [comment] 2019-10-03 05:42
> That's from the commit before the commit fixing this, try updating.

I had pulled the latest commit, but my build must have failed  without me noticing, sorry about that.

Recompiled and it's indeed fine now.
