### ISSUE TITLE
steal a dead man's mind

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#44613] opened 2020-10-04 17:59 UTC
Unable to finish "steal a dead man's mind" mission.  Game not registering player having quest item.

# Steps To Reproduce
1) Accept "steal a dead man's mind" mission at Hub 01
2) Acquire quest item
3) Return to "intercom"
4) Cry

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6496-gef5a06d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by wapcaplet** [comment] 2020-10-04 21:48
Duplicate of #41226

**Closed** 2020-10-04 21:49 UTC
Labels: (S3 - Duplicate)
