### ISSUE TITLE
JSON Interpreter Not Checking Case on Bad JSON Objects

### ISSUE THREAD

**Issue by detahramet** [CleverRaven/Cataclysm-DDA#68249] opened 2023-09-21 21:27 UTC
### Describe the bug

Interpreter does not return an error  for the json object `"eoc_type":`  with the wrong case, E.G. `"EOC_TYPE":` does not return an error despite being non-functional.

### Attach save file

N/A

### Steps to reproduce

1. Create a new json file 
2. Paste . ```	{
    "type": "effect_on_condition",
    "id": "EOC_GRANT_MARLOSS_VECTOR",
    "global": false,
    "eoc_type":"EVENT",
    "required_event": "consumes_marloss_item",
    "effect": { "u_add_trait": "MARLOSS_YELLOW" }
},```
4. Test to confirm function
5. change `"eoc_type":` to `"EOC_TYPE":`
6. Start a new character

### Expected behavior

I expected to receive an error from a bad JSON object as that normally happens with such.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: e0694d0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bongfruit [test]
]

### Additional context

Bongfruit is name of the test mod I made to verify this.

**Comment by ZhilkinSerg** [comment] 2023-09-22 10:15
Are you positive it is about the letter case? Did you try to add some other unsupported JSON node? I could be that game does not report unvisited JSON members at all.

**Comment by detahramet** [comment] 2023-09-24 05:17
After some quick testing, this would appear to be the case.

**Comment by ZhilkinSerg** [comment] 2023-09-25 11:44
> After some quick testing, this would appear to be the case.

Caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/50143

**Comment by ZhilkinSerg** [comment] 2023-09-25 11:45
Should've been fixed by #64922

**Comment by ZhilkinSerg** [comment] 2023-09-25 12:26
Actually it works as expected and I cannot reproduce it. Invalid json nodes are reported.

**Closed by ZhilkinSerg** 2023-09-25 12:26 UTC
Labels: (S1 - Need confirmation), Code: Tests, EOC: Effects On Condition
