### ISSUE TITLE
Bike racks fail to deny use in certain edge cases

### ISSUE THREAD

**Issue by Jamuro-g** [CleverRaven/Cataclysm-DDA#46977] opened 2021-01-23 18:47 UTC
# Describe the bug
It is possible to use a bike rack for multiple vehicles at once 
Upon unracking the parts belonging to that rack are getting permanently merged with the parent vehicle.

# Steps To Reproduce

- Spawn/make a car with bike racks (lets say they are on all bottom tiles of the car)
- Add additional bike racks to one of the sides of the car until they connect in a corner with the bottom ones
- spawn in two vehicles (tested it with two motorcycles) and mount them on each bike rack set
- move to the corner tile where the bike racks connect and (e) activate the unloading process
- check parent vehicle ... parts of the motorcycle that were next to the cornerpiece bike rack are now merged with the parent vehicle

# Expected behavior
Either bike racks that have a carried part in any cardinal direction should not get fetched when the lines of bike racks are generated in the code.
Or if racking multiple vehicles to one rack is desired (or a problem we have to live with due to how the tiles work) a check needs to be made to ensure that already carried parts aren't getting their carry_names changed

# Screenshots

![image](https://user-images.githubusercontent.com/76928284/105611079-86fa1e80-5db3-11eb-8664-35c4d96a5b6e.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: tested on current (11395) & 11381
 - Graphics version: [Tiles]
 - Ingame language: english
 - Mods loaded: dda, npcs no hunger, bionic profs

**Comment by PaulBlay** [comment] 2021-01-23 18:54
ynemo had a crash caused by two messed up (merged) vehicles from (mis)use of bike racks.
https://github.com/CleverRaven/Cataclysm-DDA/issues/46794

**Comment by Jamuro-g** [comment] 2021-01-23 19:40
> ynemo had a crash caused by two messed up (merged) vehicles from (mis)use of bike racks.
> #46794

i am pretty sure that one is a slightly different issue (a combination of two most likley) but i ll look into it.

Some observations that i think play a role:
- neighbouring vehicles merging together when they are unracked is caused by them having the same name and orientation. The string used to identify different carried vehicles just isn't guaranteed to be unique (something that i have a solution for in my vehicle ui pr)
- and any time this happens with activatable parts like a fridge or kitchen unit it most likley causes the same error as in ##46971

**Closed** 2021-02-06 02:42 UTC
Labels: Vehicles, [C++]

**Comment by kevingranade** [comment] 2021-02-09 08:41
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/shopping-cart-merged-to-car-with-bike-rack-after-attaching-two-carts-to-the-same-rack-git-00efc6d7fe/25889/2
