### ISSUE TITLE
Bottom of a mine scenario causes error and trapped spawn.

### ISSUE THREAD

**Issue by Merlin1846** [CleverRaven/Cataclysm-DDA#53331] opened 2021-12-10 03:23 UTC
### Describe the bug

Every time I do the bottom of a mine start the game shows an error, and if I click continue I spawn in a completely enclosed square with random dead bodies in it and no way out.

### Steps to reproduce

1. Chose bottom of a mine scenario, (mods, character choices, etc, do not seem to affect bug).
2. Start the game.
3. An error will appear.
4. Click continue(I) to find yourself permanently trapped.

### Expected behavior

I expected to play the scenario.

### Versions and configuration

- Ubuntu 18
- Mods don't change anything (I've tested multiple configurations)
- Experimental build d85abc7 although I've had this bug in stable too.

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7689899/debug.log)

**Comment by NetSysFire** [comment] 2021-12-10 03:58
Can reproduce. To be more specific, you are not trapped in rock but there is no way up, so you are stuck on that Z-level. You should not be spawned in the `mine_finale` but maybe a level above (`mine_down`).

**Comment by Merlin1846** [comment] 2021-12-10 04:03
I didn't know that, I just knew I couldn't escape.

**Comment by NetSysFire** [comment] 2021-12-10 04:09
If you are not afraid of "cheating" in this specific case, just use the debug menu to teleport one z-level up to continue your run.

**Comment by Night-Pryanik** [comment] 2021-12-10 05:33
Duplicate of #52517.

**Comment by NetSysFire** [comment] 2021-12-10 07:48
This is not a duplicate. The other issue is about a run which is not this scenario and taking an elevator from the surface down into the mine, not about spawning in an area which was deliberately (at least I think so) made one way.

**Closed** 2022-04-22 13:02 UTC
Labels: <Bug>, (S2 - Confirmed), Scenarios, 0.G suggested release blocker
