### ISSUE TITLE
Mounted Electric Oil Press doesn't have enough charges

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#56944] opened 2022-04-20 07:54 UTC
### Describe the bug

When trying to use the mounted vehicle version of an Electric Oil Press to create vegetable cooking oil, the crafting menu shows zero charges for the item even when it has enough power.

### Steps to reproduce

1.Craft a Mounted Electric Oil Press (the debug item is a dummy item)
2.Connect and install into powered source
3.Try to craft Vegetable cooking oil using the press (I used acorns in my tests)
4.It shows not enough charges to craft

### Expected behavior

Make Vegetable oil so I can make biodiesel 

### Screenshots

![image](https://user-images.githubusercontent.com/29996039/164178584-e0504f39-248b-47c2-b09c-22c16fa06dc6.png)
![image](https://user-images.githubusercontent.com/29996039/164178739-d525a725-5509-43da-a6e6-795a1fce6be3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 931ad4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I had this bug in my game save and was able to reproduce in another world
[bugtest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8519451/bugtest.zip)

**Comment by ZeroInternalReflection** [comment] 2022-04-20 11:02
I'm pretty sure this is parallel to #46895 and a couple of related issues others I'm trying to track down.  When handling crafting, vehicle tools are abstracted into pseudo-items.  The forge in that issue ends up with a heavy battery for 1000 charges.  In this case, the pseudo-item for the oil press doesn't have a slot for a battery, so the crafting menu tells you it has no charges.
Adding a battery slot allows for use of the oil press in your save:
![Oil_press_with_battery](https://user-images.githubusercontent.com/89038572/164216491-73ea566e-a903-4853-b6c5-6836fdf9f008.png)
But that produces new complications of its own that I still need to solve.

**Comment by Demator027** [comment] 2022-04-21 03:24
> I'm pretty sure this is parallel to #46895 and a couple of related issues others I'm trying to track down. When handling crafting, vehicle tools are abstracted into pseudo-items. The forge in that issue ends up with a heavy battery for 1000 charges. In this case, the pseudo-item for the oil press doesn't have a slot for a battery, so the crafting menu tells you it has no charges. Adding a battery slot allows for use of the oil press in your save: ![Oil_press_with_battery](https://user-images.githubusercontent.com/89038572/164216491-73ea566e-a903-4853-b6c5-6836fdf9f008.png) But that produces new complications of its own that I still need to solve.

Oddly enough my game save had a slightly different issue with the same item, that I wasn't able to replicate. It let me produce the craft and I tried to do a batch 50 craft and it ran out of charges and stopped at 9% completion. When I try to start the craft again it says I require 625 charges. However it lets me craft the item again and says I do have 500 charges available for that.
I'm just curious how that happened I suppose.
I can provide the save if that would help any, although it is over the 25mb upload limit by a hair even with compression, so I'd have to split it up I guess.

**Comment by Demator027** [comment] 2022-04-21 20:59
So I've figured out what allows me to continue the craft, its my UPS in my inventory, when it has charges I can continue the craft, that's probably reproduceable.
[Teyvat 2-9-22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8535018/Teyvat.2-9-22.zip)
[maps.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8535019/maps.zip)

**Comment by ZeroInternalReflection** [comment] 2022-04-22 00:47
I've successfully finished your giant batch of oil in the updated version.  While the mounted oil press did not have a battery defined in json, it did have the "USE_UPS" flag, which apparently allowed it to remotely grab power from your nearby UPS rather than using the vehicle battery,  I'm pretty sure vehicle-mounted parts should not have that flag, and it does not have it in the updated version.  That may also be the key to some other odd "insufficient charges" bugs.

**Comment by Maleclypse** [comment] 2022-06-04 03:11
should this be closed then?

**Comment by ZeroInternalReflection** [comment] 2022-06-05 03:48
The bugs are still present in the latest experimental.  The vehicle-mounted oil press will not pull power from the vehicle batteries, and can only be powered from a nearby UPS.  The crafting screen is still very confused on this subject.
My proposed fix for this and several related issues (#56991) has been awaiting review since April 26th, though it looks like I need to go fix some new merge conflicts.

**Closed** 2022-08-13 00:32 UTC
Labels: (S2 - Confirmed), Vehicles
