### ISSUE TITLE
0.C-30507 - Emergency Evac too broad in reach

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#24889] opened 2018-08-17 03:19 UTC
There's a computer terminal located in the Lab Autodoc chamber, in the room with the imprisoned broken cyborgs. Using the Emergency Evac command on this computer, which requires no hacking check, is presumably supposed to open the prison cells. It does this, but also opens every sealed metal door nearby, including the autodoc theatre, a nearby barracks, and the armory within said barracks:
![image](https://user-images.githubusercontent.com/19789267/44245940-1e83dc00-a20e-11e8-8563-c0c9d47bc077.png)

**Comment by BrianLefler** [comment] 2018-08-17 03:26
Emergency Evac opening the autodoc theatre is intentional - it's an alternative for people with no hacking.

The other stuff, no such much.  One quick fix would be to limit the unlock commands to operating within the 24x24 map they're part of (at least by default).

**Comment by Solusphere** [comment] 2018-08-17 03:40
Just posting another example screenshot, the console in the northeastern room unlocked the prisoner containment facility to the southwest (this one I could kinda understand, but I assume it's still unintentional):
![image](https://user-images.githubusercontent.com/19789267/44246715-3f4e3080-a212-11e8-9275-d1b5dab88bc5.png)

**Comment by Lorith** [comment] 2018-08-17 09:28
IIRC the way it works is it simply replaces all metal doors within eight tiles of the computer.  I would recommend switching it to take a list of relative locations to change, though I am unsure how to do that.  If the computer lock/unlock/open commands took locations instead of working in a set distance, it would allow much more detailed setups to be created.

**Comment by Night-Pryanik** [comment] 2018-08-17 18:28
I think this is a duplicate of #24701.

**Closed by Night-Pryanik** 2018-08-17 18:28 UTC
