### ISSUE TITLE
Recently updated 0.H candidate overwriting mansion basement with a farm plot

### ISSUE THREAD

**Issue by Gaming-Doggy** [CleverRaven/Cataclysm-DDA#75728] opened 2024-08-15 22:51 UTC
### Describe the bug

A short period of time (under an in game minute i think) there will be an error, and then part of my mansion basement is overwritten with roof tiles and seedlings, as well as wooden fences, and it spawns a zombie. This happens when I turn on my headlamp and walk outside the basement door. This has happened twice in a row, so this is a repeatable error on this save.

### Attach save file

[Keyesport-trimmed.tar.gz](https://github.com/user-attachments/files/16630925/Keyesport-trimmed.tar.gz)

### Steps to reproduce

Spawn in. 
Turn on headlamp (maybe not required). 
Walk outside of door.
Walk towards cardboard boxes to the left.

### Expected behavior

Map tiles are not overwritten.

### Screenshots

![image](https://github.com/user-attachments/assets/785cbd95-d101-4285-ab6c-d2fd5d064ef9)

### Versions and configuration

Old version:

build type: windows-tiles-sounds-x64
build number: 2024-08-01-0852
commit sha: c06f12d7f11e758d52d46f1d9e082db30e16b7b9
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/c06f12d7f11e758d52d46f1d9e082db30e16b7b9

updated version:

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 9883075 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16630959/crash.log)
[debug.log](https://github.com/user-attachments/files/16630960/debug.log)

**Comment by harakka** [comment] 2024-08-16 05:11
@MNG-cataclysm this is caused by #75321, you need to backport #71801 that fixes your original PR.

**Comment by GuardianDll** [comment] 2024-09-05 09:31
Fixed by #75787

**Closed by GuardianDll** 2024-09-05 09:31 UTC
Labels: (S2 - Confirmed), Map / Mapgen, 0.H Backport
