### ISSUE TITLE
Crafting "Heavy rail rifle" takes the ups conversion mod from my mp3 player

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36340] opened 2019-12-22 06:14 UTC
# Describe the bug
As title describes

# Steps To Reproduce

1. Get mp3 player, attach ups conversion mod
2. craft heavy rail rifle, it takes ups conversion mod from mp3 player

# Expected behavior
Crafting doesn't take a permanently installed mod from another tool

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10211-g0bd1ad2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by Night-Pryanik** [comment] 2019-12-22 06:24
I guess this is a duplicate of #21109.

**Closed by Night-Pryanik** 2019-12-22 06:24 UTC
