### ISSUE TITLE
Crash Screen - d98a4cc

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#64620] opened 2023-03-27 18:46 UTC
### Describe the bug

Using current save: attempt to sleep on couch and error crash occurs. 

### Attach save file

[Innawood Tech World-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11081994/Innawood.Tech.World-trimmed.tar.gz)

### Steps to reproduce

Attempt to sleep using save and CTB screen occurs. 

### Expected behavior

Not. 

### Screenshots

![image](https://user-images.githubusercontent.com/43046067/228036689-3914cc1e-c08e-4a9e-ab97-3bd40c5438f5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: d98a4cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    TropiCataclysm [tropicata],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11081991/crash.log)

**Comment by Hirmuolio** [comment] 2023-03-27 19:14
On the log `achievements_tracker::report_achievement(achievement const*, achievement_completion)` seems to have been last thing before crash. Perhaps same/related to the other reported achievement crashes.

**Comment by BrettDong** [comment] 2023-03-28 00:14
Duplicate of #64466.

**Closed** 2023-03-28 00:14 UTC
Labels: (S3 - Duplicate)
