### ISSUE TITLE
Unify Bionics and Mutation menus

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#16643] opened 2016-05-12 19:21 UTC
After using a Bionics a lot i noticed that using the Mutations menu is a mess to use. If it followed how the Bionics menu is being used it would make more sense and be more unified in how you interact with them.
Mutations are practically just biological mods when you think of it :P.

**tl;dr:** Make Mutations menu identical to Bionics menu in appearance and navigation.

**Comment by illi-kun** [comment] 2016-05-13 13:10
As you correctly noted, currently mutations are biological CBMs (or bionics are mechanical mutations, wev), and, BTW mutation UI is a copy-pasted version of bionic UI, but I disagree with your proposition. I think that for adding more depth to the game, bionics and mutations should be more different, not unified. I have nothing against unification of some UI elements, but these features definetely should not be merged.

__tl;dr:__ no.

**Comment by Coolthulhu** [comment] 2016-05-13 13:20
Activation menus could be the same, though.

While internally bionics would have things like slot limits, interactions with other bionics (say, EMP zeroing energy in all batteries mounted in arms) and removal surgery, those do not matter when activating/deactivating/reading description of bionics/mutations.

Having one base activation menu with different population and activation callbacks would not require making bionics and mutations similar internally, only by the fact that they would have activation state and limited numbers.

**Comment by codemime** [comment] 2016-05-13 13:33
@illi-kun @Coolthulhu I'd agree with both of you. CBMs and natural mutations should become more distinctive and of course should never be merged, but since they look alike for now, they probably should be treated similarly in terms of UI.

**Comment by AppleConnoiseur** [comment] 2016-05-13 17:02
You can navigate the Bionics menu using arrow keys but not the Mutation menu. That is what is what weirded me out.
If it work like the Bionics menu it is more intuitive.

**Comment by illi-kun** [comment] 2016-11-21 17:06
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-21 17:06 UTC
Labels: Bionics, Information / Interface, Suggestion (Discuss)
