### ISSUE TITLE
Reloading with liquid from bucket spills liquid, doesn't reload

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17734] opened 2016-07-17 16:56 UTC
- Spawn flamethrower, pot and contained gasoline
- Drop pot
- Fill pot with gasoline
- Reload flamethrower with pot
- Doesn't finish reloading, spills pot's contents on the ground

**Comment by sethsimon** [comment] 2016-07-22 02:00
I can't reproduce this. I believe it was fixed in #17732, which "allows dropping of the patch from #15084, which was intended to fix #15079. From reading #15079, reloading would put the item (a pot of gasoline in this case) into your inventory, but since it's a bucket with liquid in it, the gasoline would spill onto the ground, preventing you from finishing reloading.

**Comment by illi-kun** [comment] 2016-09-18 14:09
I got "invalid direction" message before reloading but then reloading process finalized just fine, with flamethrower reloaded and no gas spilled.

**Comment by eliotcougar** [comment] 2016-10-07 15:43
In version 5640 the reloading from pot of gasoline on the ground completes just fine... Empty pot stays on the ground...
Also, attempting to pick up pot of gasoline says: "Can't stash pot of gasoline (2000) while it's not empty"... It spills gasoline and puts an empty pot in your inventory...

**Comment by kevingranade** [comment] 2017-03-27 03:34
Confirmed, this works fine now.

**Closed** 2017-03-27 03:33 UTC
Labels: Bug, Confirmation Needed
