### ISSUE TITLE
Object is floating in thin air

### ISSUE THREAD

**Issue by bug-sniper** [CleverRaven/Cataclysm-DDA#65044] opened 2023-04-13 04:02 UTC
### Describe the bug

In the attached screenshot, you can see that I was able to make a large tactical backpack float in thin air.

### Attach save file

[Todd Mission.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11218018/Todd.Mission.zip)

### Steps to reproduce

1. Get unlucky enough for an object to spawn above a vehicle
2. Drive away
3. Observe that the gravity no longer applies to that object

### Expected behavior

A large tactical backpack should be on the ground, waiting for my greedy fingers to pick out the best loot.

### Screenshots

![image](https://user-images.githubusercontent.com/6971612/231646945-16774d0d-18a3-497a-ace9-113400859583.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm]
]

**Comment by RenechCDDA** [comment] 2023-04-13 04:08
Do you know how this particular backpack spawned? Or 'spawned'? Did you somehow place it there?

If it was spawned by a map extra, that is a known issue: 
* #36635

**Comment by RenechCDDA** [comment] 2023-04-13 04:13
Confirmed by the reporter on discord, it spawned in the air and was not placed there. Therefore, duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/36635

**Closed** 2023-04-13 04:14 UTC
Labels: (S1 - Need confirmation)
