### ISSUE TITLE
It's possible to exceed maximum allowed head encumbrance by modifying worn headgear

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19939] opened 2017-01-03 19:00 UTC

**Comment by Regularitee** [comment] 2017-01-04 02:03
Well, it doesn't really matter since head encumbrance has no penalty. 

Though that reminds me, https://github.com/CleverRaven/Cataclysm-DDA/issues/18874 still needs to be addressed.

**Comment by Asmageddon** [comment] 2017-01-04 07:47
Ah, crap. Personally I don't really mind there being no penalty that much. I feel like the penalties system right now is a bit wobbly overall. With how hard the stuff you really need to be on lookout against, high torso encumbrance is unavoidable, and the situation is identical with the head.

**Comment by Leland** [comment] 2017-05-04 01:36
Duplicate of #12897

**Closed by Leland** 2017-05-04 01:36 UTC
Labels: Bug
