### ISSUE TITLE
Internal Furnace CBM message log

### ISSUE THREAD

**Issue by Weyrling** [CleverRaven/Cataclysm-DDA#22051] opened 2017-10-01 18:27 UTC
Game version: 6815 experimental (Also tested in 6817)

Operating system: Windows

Tiles or curses: Tiles

Expected behavior: Reliable information in the message log.

Actual behavior: Everything claims to have restored 35123440 points of energy.

Steps to reproduce the behavior: Activate the Internal Furnace CBM and then eat something flammable that is otherwise non-edible.

Note that the amount restored is properly listed in the Consume Item menu, it simply isn't properly recorded into the message log seen in the normal view screen.

Additionally some things seem to give inordinate amounts of power, for example a Television can be eaten to provide 2512 power, which is slightly less than eating 5 entire logs.
Chopping down a tree usually drops 2-4 trunks which can be chopped up into 4-10 logs.

**Comment by Night-Pryanik** [comment] 2019-02-03 06:16
Can't reproduce it on 8495. Debug spawned bokken. Activating `E`at menu said that I'll gain 63 points of energy, and I indeed gained exactly 63 point of energy. Television set is consumable at all. 
Closing for now, if this is still reproducible, ping me.

**Closed by Night-Pryanik** 2019-02-03 06:16 UTC
Labels: Bionics, Info / User Interface
