### ISSUE TITLE
Artifacts don't spawn

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42381] opened 2020-07-22 15:37 UTC
# Describe the bug
Artifacts do not spawn, instead a simple spoon, which is a placeholder item, I assume, spawns in its place. Strange Temples and certain mines only have powerless spoons. They have no properties and spawning an artifact with the debug menu also yields only a spoon.

# Steps To Reproduce

1. Find artifact in current version (0.E-4329-ga3e5f32) or versions with its artifact handling.
2. See that it is only a spoon with no powers.

# Expected behavior

Artifacts exist instead of mundane spoons.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by anothersimulacrum** [comment] 2020-07-22 15:51
Wield the spoon, you'll see it has powers.

**Comment by Bulletfang** [comment] 2020-07-22 16:16
@anothersimulacrum I don't understand, it does nothing. No stats increase or decrease, no random effects, positive or negative, can't activate it? If you have several they stack in your inventory like all identical mundane items. What are they supposed to do, how do I use them?

**Comment by anothersimulacrum** [comment] 2020-07-22 16:21
Here's me wielding a random one
![image](https://user-images.githubusercontent.com/42699974/88201519-68e11500-cbfc-11ea-8f58-575fc50b749e.png)
I think that they stack with other random spoons is an issue though (note that they don't get overwritten, they just stack, and you need to go through all of the stack to find them).

There are no active effects at the moment.

**Comment by KorGgenT** [comment] 2020-07-22 21:15
This is actually a duplicate of #42261, it's not a bug but the fact that noone has completed the json for artifact procgen yet.

**Closed by KorGgenT** 2020-07-22 21:15 UTC
Labels: Artifacts, Info / User Interface, Items / Item Actions / Item Qualities

**Comment by gc2020x3** [comment] 2020-09-03 18:12
@kevingranade @KorGgenT
We are the Grey Committee. 

Cataclysm started as great Community Project. But recent events indicate that normal and healthy relationship between Community and Developers are lost and development going nowhere. Main reason of this is Kevin Grenade.

Kevin Grenade, current Project Leader deemed exclusively rights on everything in Cataclysm, violating project license and intellectual honesty. 

He does not respect community opinion and opinion of his own development team alike. Reasoning with him became pointless long time ago. A lot of people left project because of his attitude and decision making.

Worse of all that project development start going with questionable ways at best. Instead of proper and logical decision making changes start becoming more and more chaotic and subjective. Game becoming a mess.

So we are decided that time for compromises has passed. The Grey Committee was created to fight back.

Our Manifesto is simple:
1) Kevin Grenade must leave the project forever.
2) New Development Leader must re-establish normal relation between Development Team and Community.
3) All bans since beginning Kevin Grenade leadership must be revoked.

This goals are not negotiable and can be considered as our ultimatum.

To achieve our goals, we will engage Kevin Grenade and ones who blindly supports his behavior in various ways of informational and psychological warfare.

We are not going allow some false dictator to steal our project and reduce it to dust.

«In the struggle you will gain your rights»
Grey Committee.



To make our word loud we will repeat this message for ... a couple of times.
