### ISSUE TITLE
Game crash on getting the Disassemble Number Five! achievment

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#64686] opened 2023-03-30 03:27 UTC
### Describe the bug

Killing robot enemies for the first time causes the game to display an error message and crash

### Attach save file

[New Big Pine-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11107399/New.Big.Pine-trimmed.tar.gz)

### Steps to reproduce

1: make player with a gun
2: shoot skitterbot/manhack with gun
3: crash

### Expected behavior

I expect to be able to get achievments without crashing.

### Screenshots

![crashscreen](https://user-images.githubusercontent.com/44286709/228718932-3d5f3c5e-7cb0-4b82-b391-8338838a4826.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: f3e9c4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved]
]

### Additional context

I first thought it was just skitterbots but after testing further I found killing manhacks causes it as well, I then used the debug menu to cheat so I no longer gained achievments and I could then kill the bot like normal.

**Comment by anothersimulacrum** [comment] 2023-03-30 03:34
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed by anothersimulacrum** 2023-03-30 03:34 UTC
Labels: (S3 - Duplicate)
