### ISSUE TITLE
NPCs inhaling some smoke abandon moving vehicles

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23564] opened 2018-04-21 12:59 UTC
Game version: 0.C-27468-g1780644

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
NPCs in a moving vehicle prioritize staying in it, especially if they are sitting strapped to a seat - unless an enemy enters the vehicle. Inhaling a bit of smoke when in open-canopy vehicles (like motorbikes) doesn't bother the NPC unless they inhale said gas for prolonged time.

### Actual behavior
NPCs in a backing up vehicle that inhale a bit of smoke abandon it despite it being dangerous, risking considerable injury or being left behind and then start to chase the vehicle on foot a moment later. Also works with external sources of smoke the vehicle simply moves through for a short time.

### Steps to reproduce the behavior
Enter gasoline/diesel-powered, "open-cabin" vehicle with NPCs, start backing up in a way that makes your vehicle drive into its own exhaust.

**Comment by Night-Pryanik** [comment] 2018-04-21 15:38
Duplicate of #22517.

**Closed by Night-Pryanik** 2018-04-21 15:38 UTC
