### ISSUE TITLE
cataclysm-tiles: src/optional.h:46: Assertion `full' failed.

### ISSUE THREAD

**Issue by pityhero233** [CleverRaven/Cataclysm-DDA#49259] opened 2021-06-11 13:22 UTC
# Describe the bug

when I try to close my inventory, the whole program froze and quit due to the following error
```
libpng warning: iCCP: known incorrect sRGB profile
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp).
cataclysm-tiles: src/optional.h:46: const T& cata::optional<T>::get() const [with T = vpart_reference]: Assertion `full' failed.
[1]    50456 abort (core dumped)  ./cataclysm-tiles
./cataclysm-tiles  104.99s user 11.57s system 13% cpu 14:00.19 total
```

# Steps To Reproduce
not sure if it's easily reproducible, but here's what I have done:
1. download latest experimental build
2. install undeadpeople tileset & mod
3. create world with slightly modified parameters & some of the official mods
4. play
5. open inventory, close inventory

# Versions and configuration

 - OS: Archlinux latest rolling
 - Game Version: 099e4a5
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: [dda, no_npc_food, bionic professions, magiclysm, blazeindustries, MMA, statsthroughskills, speedydex]

# Additional context
savefile:
[dreamland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6638701/dreamland.zip)

**Comment by ZhilkinSerg** [comment] 2021-06-11 15:24
Is it reproducible w/o tileset enabled?

**Comment by anothersimulacrum** [comment] 2021-06-11 15:35
Would it be possible for you to provide your `config/crash.log`?

**Comment by pehamm** [comment] 2021-06-11 16:28
Cannot reproduce on macOS using 0.E-10761-g876e779cbd and tiles using the provided savefile.

The error message reads like SDL does not recognize the key you press to close the inventory.  What did you bind it to?

**Comment by ZhilkinSerg** [comment] 2021-06-11 16:37
> 
> 
> Cannot reproduce on macOS using 0.E-10761-g876e779cbd and tiles using the provided savefile.
> 
> The error message reads like SDL does not recognize the key you press to close the inventory. What did you bind it to?

This is a just red herring.

**Comment by pityhero233** [comment] 2021-06-12 05:15
> Would it be possible for you to provide your `config/crash.log`?

I looked up /config, there is only `debug.log`. 
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6641690/debug.log)
just now during my play with same save, it happened again when I was opening my inventory ...

**Comment by anothersimulacrum** [comment] 2021-06-12 05:18
Without anyone being able to reproduce it, it will be very hard to determine the cause, then.

**Comment by pityhero233** [comment] 2021-06-12 05:21
Here is a screen record, the crash happened when i try to drop my wielding item:



https://user-images.githubusercontent.com/24752033/121765953-21030d80-cb81-11eb-8ba8-47ca453e37f1.mp4

**Comment by anothersimulacrum** [comment] 2021-06-12 05:24
Would you be able to run the game in gdb and provide a stack trace?

**Comment by ZhilkinSerg** [comment] 2021-06-12 05:58
Duplicate of #49050

**Comment by BrettDong** [comment] 2021-06-12 18:06
Could you try the latest experimental version and see if the crash persists?

**Comment by pityhero233** [comment] 2021-06-13 00:20
> Could you try the latest experimental version and see if the crash persists?

dropping worked as expected on a76f7e8

**Closed** 2021-06-13 01:41 UTC
Labels: (S1 - Need confirmation)
