### ISSUE TITLE
New game crash

### ISSUE THREAD

**Issue by Onba2** [CleverRaven/Cataclysm-DDA#53826] opened 2021-12-28 05:57 UTC
### Describe the bug

Every time I create new character and try to enter the world the game stops responding at the "please wait while we build your world" screen. This happens even with no added mods and on newly created worlds. Old games still work but have occasionally crashed with the 'program not responding' message as well. Not sure if that's related.

### Steps to reproduce

1. Start a new character.
2. Go through character creation
3. Hit tab at the end of character creation.

### Expected behavior

I expected to spawn in the world as normal.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fbab99b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Stats Through Skills [StatsThroughSkills],
]

### Additional context

Tested this with 3 characters with each different traits, hobbies, and backgrounds. They shared nothing in common, not even a name.

**Comment by BrettDong** [comment] 2021-12-28 05:58
Probably related to #53103.

**Comment by BrettDong** [comment] 2021-12-28 07:47
Duplicate of #53825.

**Closed by BrettDong** 2021-12-28 07:47 UTC
Labels: <Crash / Freeze>
