### ISSUE TITLE
When I use the 'Feed an animal' action, instead of feeding the dog, I eat the meal myself.

### ISSUE THREAD

**Issue by nikow** [CleverRaven/Cataclysm-DDA#76438] opened 2024-09-14 20:10 UTC
### Describe the bug

Even when action says 'Feed an animal' on 'a'ctivating the wet/dry dog food, the feeded animal is myself.
![image](https://github.com/user-attachments/assets/20da876b-193f-4052-829b-86a25d603668)
![image](https://github.com/user-attachments/assets/e9392325-f73e-4784-ae8e-6e42caf001a3)

### Attach save file

N/A

### Steps to reproduce

1. Spawn a player with dry/wet dog food.
2. Spawn a dog.
3. Activate food.

### Expected behavior

I feed animal or get prompt proposing me to eat it alone.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-5.0-amd64:core-5.0-noarch; Distributor ID: Fedora; Description: Fedora release 39 (Thirty Nine); Release: 39; Codename: ThirtyNine; 
- Game Version: cdda-experimental-2024-09-14-0515 b8b5c5cc52-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm]
]

**Comment by PGR-14** [comment] 2024-09-14 20:13
Potentially related to https://github.com/CleverRaven/Cataclysm-DDA/issues/76414?

**Comment by mqrause** [comment] 2024-09-15 17:20
Yes, this has the same cause, so it's a duplicate.

**Comment by RenechCDDA** [comment] 2024-09-17 05:07
> /confirmed

You need to [add yourself to the confirm permissions list](https://github.com/CleverRaven/Cataclysm-DDA/pull/61755) if you want these commands to work. Also, this is a duplicate.

**Comment by RenechCDDA** [comment] 2024-09-17 05:07
Duplicate of #76414

**Comment by RenechCDDA** [comment] 2024-09-17 05:09
....Right, don't **quote** the bot commands or else the bot will think you're trying to use them.

**Closed by RenechCDDA** 2024-09-17 05:09 UTC
Labels: (S3 - Duplicate), (S2 - Confirmed)

**Comment by chaoticidealism** [comment] 2024-10-09 16:53
Confirmed, happens with cat food too.
