### ISSUE TITLE
Bug: Welders with "battery compartment mod" can't repair.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#18928] opened 2016-10-21 22:11 UTC
Whenever I try to use a welder with the "battery compartment mod" and a charged battery I get "Your tool does not have enough charges to do that."

I can still repair stuff with a stock makeshift welder with plain battery charges.

<a href='https://postimg.org/image/oqk7xut25/' target='_blank'><img src='https://s6.postimg.org/oqk7xut25/Welder_with_battery_compartment_mod_can_t_be_use.jpg' border='0' alt='postimage'/></a>

**Comment by Zireael07** [comment] 2016-10-22 07:43
Duplicate of #18931?

**Comment by illi-kun** [comment] 2016-10-23 13:01
Closed as a duplicate.
Thanks for the report anyway and @Zireael07 thanks for the note.

**Closed by illi-kun** 2016-10-23 13:01 UTC
