### ISSUE TITLE
UI still broken with Butchery

### ISSUE THREAD

**Issue by lethallama** [CleverRaven/Cataclysm-DDA#75765] opened 2024-08-17 06:52 UTC
### Describe the bug

The Dissection page for Butchering still doesn't fit.  You can't see all the possible proficiencies available from a corpse.

### Attach save file

[Eternal Pool-trimmed.tar.gz](https://github.com/user-attachments/files/16643864/Eternal.Pool-trimmed.tar.gz)

### Steps to reproduce

Butcher a corpse, go to Dissection.

### Expected behavior

I expected to be able to read the lower parts of the tooltip.

### Screenshots

![CDDA UI failure](https://github.com/user-attachments/assets/9a8999aa-446d-4388-a94d-c55d33f54011)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: a0bc244 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by GuardianDll** [comment] 2024-09-11 13:48
Closing it as duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/75698, gonna be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/76356

**Closed by GuardianDll** 2024-09-11 13:48 UTC
Labels: Info / User Interface, (S2 - Confirmed)
