### ISSUE TITLE
magazine duplication when loading a gun

### ISSUE THREAD

**Issue by moosestrangler** [CleverRaven/Cataclysm-DDA#16921] opened 2016-05-28 15:50 UTC
https://i.imgur.com/bFeq6M4.png
https://i.imgur.com/9n1gNEq.png

I loaded a modified M9 with a magazine from my inventory. It loaded the gun but I got those debug messages and the magazine I used was still in my inventory as well as the copy in the M9. This has been happening since magazines were implemented but I haven't noticed any patterns in when it happens. I was using the same gun with the same magazines previously and it worked fine then.

**Comment by BorkBorkGoesTheCode** [comment] 2016-05-28 18:50
Is this a new character in a new world?

**Comment by illi-kun** [comment] 2016-05-28 20:52
Duplicate of #16771.

**Closed by illi-kun** 2016-05-28 20:52 UTC
