### ISSUE TITLE
Glass shards and rags take too long to pick up / shift between containers

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#48937] opened 2021-05-19 05:39 UTC
Glass shards and rags take too long to pick up / shift between containers

# Steps To Reproduce

1. Spawn a large number of glass shards / rags.
2. Attempt to pick a large number of them up.
3. An unreasonable amount of in-game time time passes as your character painstakingly picks each splinter of glass out of their backpack one by one.

# Expected behavior

Something closer to how rocks are handled.

# Versions and configuration

OS: Windows
    OS Version: 10.0 2004
Game Version: 12fcd38 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock]
]

**Comment by actual-nh** [comment] 2021-05-19 06:13
If you don't have on thick gloves, that's actually quite correct for glass shards. Rags are another matter.

**Comment by DalenTalas** [comment] 2021-05-19 13:28
The character *was* wearing cut-resistant gloves at the time, so yeah.

In my opinion, this is one of those instances where realism should yield to gameplay smoothness.

**Comment by Salty-Panda** [comment] 2021-05-19 14:05
Every single item is separately wielded, than shifted into target container.
Maybe some time multiplier for moving more items at once?

Rocks are faster probably because they are ammunition. Same case would be with thread.

**Comment by Cenness** [comment] 2021-05-21 09:00
Similar issues - #47007, #35292

**Comment by DalenTalas** [comment] 2021-05-21 13:41
> Similar issues - #47007, #35292

I would say it's an issue with each item in a 200+ stack getting moved individually. In-game time is also, well, excessive.

**Comment by chrispikula** [comment] 2021-05-22 15:28
Bone skewers are the worst item this occurs with.  If you 'cut' up some bones, say when 'cut'ing up a whole pile of stuff you end up with 20 or 40 per bone.  Skeletal zombies drop 40-60 bones.  

Best part?  Bone skewers have no great use case.  Can't burn them easily, can't mill them, etc, etc.  I've legitimately stopped playing saves due to piles of accidentally created bone skewers causing too much lag.

**Comment by leemuar** [comment] 2021-05-23 09:54
Same happens with cash: you drop, pick up and sell each individual banknote which is slow and frustrating

**Comment by DalenTalas** [comment] 2021-06-11 04:26
I would say this is not a performance issue. It's, as @Salty-Panda mentioned above, an issue with moving each item individually instead of handful-sized stacks.

**Comment by actual-nh** [comment] 2021-06-11 17:07
> I would say this is not a performance issue. It's, as @Salty-Panda mentioned above, an issue with moving each item individually instead of handful-sized stacks.

What is meant by "watch time fly out of game"? If there's a RT lag (as well as an in-game-time one?), that's a performance issue.

**Comment by DalenTalas** [comment] 2021-06-11 17:11
Updated the original post to clarify. I was referring to in-game time. Will give the actual numbers once I have a chance to get them.

Though the game does make a noticeable pause of  several seconds of RT.

**Comment by DalenTalas** [comment] 2021-06-11 21:37
Given: Brand new world.
Leather backpack held in hand.
400 glass shards on the ground.

Inserting the shards into the backpack takes 10 in-game minutes, about one RT seconds.
Dropping the shards takes 20 in-game minutes, about 20 RT seconds.

Will try the same with rags later on and compare with my IRL performance.

**Comment by Zireael07** [comment] 2021-07-09 18:30
Seems to affect stacks of anything that's likely to be in mass amounts (rocks, cash, bone, rags) and that's not "charges".

Kevin said in another issue that the problem should be fixed not avoided (as there were PRs making some culprits "charges" )

**Comment by DalenTalas** [comment] 2021-07-09 18:36
How about a new category of items? Something like "pileable". Where they are moved not in singles, but in random "handfuls".

Is this in any way similar how powders are handled?

**Comment by hexagonrecursion** [comment] 2021-08-23 13:17
> Seems to affect stacks of anything that's likely to be in mass amounts (rocks, cash, bone, rags) and that's not "charges".

The timing is also inconsistent: it takes much longer to drop then to pick up.

**Comment by chrispikula** [comment] 2021-08-24 02:51
> > Seems to affect stacks of anything that's likely to be in mass amounts (rocks, cash, bone, rags) and that's not "charges".
> 
> The timing is also inconsistent: it takes much longer to drop then to pick up.

That might be due to pocket access times.  Picking up, it'll put things in the most favorable pocket(s).

**Comment by DalenTalas** [comment] 2021-08-24 03:06
> 
> 
> > > Seems to affect stacks of anything that's likely to be in mass amounts (rocks, cash, bone, rags) and that's not "charges".
> > 
> > 
> > The timing is also inconsistent: it takes much longer to drop then to pick up.
> 
> That might be due to pocket access times. Picking up, it'll put things in the most favorable pocket(s).

That's perfectly legitimate. However, pocket access times should be accounted for during both picking up and dropping. On the third hand, dropping may simply have a lower action cost than picking up.

My concern is that shifting stacks of relatively small, similar items should happen much faster. At least in batches, not singles. Regardless of whether they are ammunition or not.

**Comment by chrispikula** [comment] 2021-08-24 15:40
Ah, I wasn't clear.  When picking up glass shards, they are tiny, so they'll go in whatever pockets have space, after you've put all your other loot in them.  A 'pack every last spot' activity.  Some go in horribly access time pockets.

Here comes the 'drop everything test'.  You drop your non-glass shards, then drop glass shards, and time them.  (Or vice-versa.)  Say, 125 seconds.

Now, with a fully empty backpack, you pick up those glass shards, and since you aren't carrying the other objects, they all go in favorable pockets, and it's only 100 seconds.  

If you drop at this point, it should be 100 seconds as well.

**Comment by RenechCDDA** [comment] 2023-07-01 12:01
This is a feature request for QoL, not a bug. We would be happy to simulate the ability to pick up multiple of small items in one handful, but per the last close wave, "we can not support issues asking for arbitrary content additions in the repo, there are too many issues."

That doesn't mean it can't be added, just that the issue can't sit around stale forever.

**Closed by RenechCDDA** 2023-07-01 12:01 UTC
Labels: <Bug>, Inventory / AIM / Zones, Quality of Life

**Comment by leemuar** [comment] 2023-07-01 12:07
@RenechCDDA could you please add stale label to this issue so it could be found when someone wish to work on it?

**Comment by Zireael07** [comment] 2023-07-01 18:37
not sure whether it's an in-universe problem or a performance problem being reported here, tbh.

Massive stacks of skewers/rags/bones ARE a performance problem, too!

**Comment by RenechCDDA** [comment] 2023-07-01 22:38
> not sure whether it's an in-universe problem or a performance problem being reported here, tbh.
> 
> Massive stacks of skewers/rags/bones ARE a performance problem, too!

This is definitely regarding the pickup time.

#58793 and other issues (many many issues) remain open in regards to the performance

**Comment by Zireael07** [comment] 2023-07-02 15:03
@RenechCDDA thanks for clarifying
