### ISSUE TITLE
Teleportation segfault w/ MOM

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#76523] opened 2024-09-18 15:15 UTC
### Describe the bug

Used gateway to go from Hub 01 to the Exodii, The place I teleported from went grey (Unseen location) & I turned into the sprite that IR goggles uses. Doing anything (I.E. pressing tab, moving etc.) causes it to crash

### Attach save file

Accidentally deleted the world in the menu, sorry.

### Steps to reproduce

I've noticed this happen once or twice while using debug menu to teleport to places

### Expected behavior

For me to teleport successfully

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4037 (23H2)
- Game Version: cdda-experimental-2024-09-16-0019 5e06aad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Mythical Martial Arts [MMA],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Survivor Notes [more_survivor_notes],
    Extra Mutated Scenarios [extra_mut_scens],
    More Professions can start in Extra Mutated Scenarios [more_profession_chooses_extra_mut_scens],
    New start locations for Extra Mutated Scenarios [new_start_locations_for_extra_mutation_scen],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Pain Disables Powers</color> [mom_remove_pain_disables_psi_limit],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Martial Mastery [perk_melee_system],
    Hands [hand],
    Dream of Flight [dream_of_flight],
    Custom Portal Storm Size [custom_size_ps],
    Custom Frequencey For Portal Storms [custom_freq_ps],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Bionic Traits [bionic_traits],
    Alternative Map Key [alt_map_key],
    Targeted Mutagens [targetedmutagens],
    Readd Clothing Customization for TailorKits [TailorKits-Readd-Customization],
    Pixel's Various Fuckery [Pix's Shit],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Jackledead Armory [jackledead_armory],
    Frontier Mods Core [frontier_core],
    Gunsmith [gunsmith],
    Culinary Days Ahead [culinary_days_ahead],
    Xedra Evolved [xedra_evolved],
    Make bows great again [bow_opness],
    Jackledead Armory: Creeps Goons Guns [jackledead_armory_expansion],
    Gunslinger Professions [hyd_gunslinger],
    Bionic Professions [package_bionic_professions],
    Better Arachnids [betterArachnids],
    Aftershock [aftershock],
    <color_light_green>Cataclysm++</color> [Cata++],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Bionic Slots [no_cbm_slots],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Additional backgrounds [Arendeth_Additional_backgrounds]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: cdda-experimental-2024-09-16-0019 5e06aad
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff752453cae), 
    (unable to get module base address),
  #1
    (dbghelp: @0x7ff752432a2c), 
    (unable to get module base address),
  #2
    (dbghelp: @0x7ff752432d29), 
    (unable to get module base address),
  #3
    (dbghelp: @0x7ff752eb2112), 
    (unable to get module base address),
  #4
    (dbghelp: @0x7ff95482b248), 
    (unable to get module base address),
  #5
    (dbghelp: @0x7ff954c1504f), 
    (unable to get module base address),
  #6
    (dbghelp: @0x7ff954b8e866), 
    (unable to get module base address),
  #7
    (dbghelp: @0x7ff954c1403e), 
    (unable to get module base address),
  #8
    (dbghelp: @0x7ff954ba9a19), 
    (unable to get module base address),
  #9
    (dbghelp: @0x7ff954bac324), 
    (unable to get module base address),
  #10
    (dbghelp: @0x7ff954baaff1), 
    (unable to get module base address),
  #11
    (dbghelp: @0x7ff95481cadc), 
    (unable to get module base address),
  #12
    (dbghelp: @0x7ff7523caae5), 
    (unable to get module base address),
  #13
    (dbghelp: @0x7ff7536dd9d8), 
    (unable to get module base address),
  #14
    (dbghelp: @0x7ff753730a92), 
    (unable to get module base address),
  #15
    (dbghelp: @0x7ff7523c7df9), 
    (unable to get module base address),
  #16
    (dbghelp: @0x7ff7536dd9d8), 
    (unable to get module base address),
  #17
    (dbghelp: @0x7ff753730a92), 
    (unable to get module base address),
  #18
    (dbghelp: @0x7ff7523c7d66), 
    (unable to get module base address),
  #19
    (dbghelp: @0x7ff7536dd9d8), 
    (unable to get module base address),
  #20
    (dbghelp: @0x7ff753730a92), 
    (unable to get module base address),
  #21
    (dbghelp: @0x7ff7523c7df9), 
    (unable to get module base address),
  #22
    (dbghelp: @0x7ff7536dd9d8), 
    (unable to get module base address),
  #23
    (dbghelp: @0x7ff7523c58a2), 
    (unable to get module base address),
  #24
    (dbghelp: @0x7ff7536dd9d8), 
    (unable to get module base address),
  #25
    (dbghelp: @0x7ff753335194), 
    (unable to get module base address),
  #26
    (dbghelp: @0x7ff7536c0740), 
    (unable to get module base address),
  #27
    (dbghelp: @0x7ff75336aa94), 
    (unable to get module base address),
  #28
    (dbghelp: @0x7ff95483ddb1), 
    (unable to get module base address),
  #29
    (dbghelp: @0x7ff752c9ce8b), 
    (unable to get module base address),
  #30
    (dbghelp: @0x7ff752c9cf05), 
    (unable to get module base address),
  #31
    (dbghelp: @0x7ff7526380ab), 
    (unable to get module base address),
  #32
    (dbghelp: @0x7ff752578864), 
    (unable to get module base address),
  #33
    (dbghelp: @0x7ff75257900b), 
    (unable to get module base address),
  #34
    (dbghelp: @0x7ff752598b95), 
    (unable to get module base address),
  #35
    (dbghelp: @0x7ff7528108a3), 
    (unable to get module base address),
  #36
    (dbghelp: @0x7ff752813761), 
    (unable to get module base address),
  #37
    (dbghelp: @0x7ff752815058), 
    (unable to get module base address),
  #38
    (dbghelp: @0x7ff753a3bda7), 
    (unable to get module base address),
  #39
    (dbghelp: @0x7ff7521c13ae), 
    (unable to get module base address),
  #40
    (dbghelp: @0x7ff7521c14c6), 
    (unable to get module base address),
  #41
    (dbghelp: @0x7ff9531f257d), 
    (unable to get module base address),
  #42
    (dbghelp: @0x7ff954bcaf28), 
    (unable to get module base address),

_______________

10:31:41.642 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff752453cae[cataclysm-tiles.exe+0x293cae]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x140293cae),
    0x140293cae    src/debug.cpp:1143    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff752454bd7[cataclysm-tiles.exe+0x294bd7]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x211@0x140294bd7),
    0x140294bd7    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/time.h:246    time
    0x140294bd7    src/debug.cpp:1471    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x7ff752455b96[cataclysm-tiles.exe+0x295b96]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x140295b96),
    0x140295b96    src/debug.cpp:519    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x7ff7532999df[cataclysm-tiles.exe+0x10d99df]), 
    (libbacktrace: void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)+0xdf@0x1410d99df),
    0x1410d99df    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/basic_string.h:795    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x1410d99df    src/debug.h:78    void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)
  #4
    (dbghelp: @0x7ff7528d4696[cataclysm-tiles.exe+0x714696]), 
    (libbacktrace: material_type::check() const+0x30e@0x140714696),
    0x140714696    src/material.cpp:189    material_type::check() const
  #5
    (dbghelp: @0x7ff7528d46d7[cataclysm-tiles.exe+0x7146d7]), 
    (libbacktrace: materials::check()+0x28@0x1407146d7),
    0x1407146d7    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_iterator.h:1108    __gnu_cxx::__normal_iterator<material_type const*, std::vector<material_type, std::allocator<material_type> > >::operator++()
    0x1407146d7    src/generic_factory.h:414    generic_factory<material_type>::check() const
    0x1407146d7    src/material.cpp:373    materials::check()
  #6
    (dbghelp: @0x7ff752630c1a[cataclysm-tiles.exe+0x470c1a]), 
    (libbacktrace: DynamicDataLoader::check_consistency()+0x2996@0x140470c1a),
    0x140470c1a    src/init.cpp:877    DynamicDataLoader::check_consistency()
  #7
    (dbghelp: @0x7ff7526334a1[cataclysm-tiles.exe+0x4734a1]), 
    (libbacktrace: DynamicDataLoader::finalize_loaded_data()+0x23bd@0x1404734a1),
    0x1404734a1    src/init.cpp:776    DynamicDataLoader::finalize_loaded_data()
  #8
    (dbghelp: @0x7ff7525790ff[cataclysm-tiles.exe+0x3b90ff]), 
    (libbacktrace: game::load_world_modfiles()+0x419@0x1403b90ff),
    0x1403b90ff    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_set.h:281    ~set
    0x1403b90ff    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_set.h:281    std::set<string_id<MOD_INFORMATION>, std::less<string_id<MOD_INFORMATION> >, std::allocator<string_id<MOD_INFORMATION> > >::~set()
    0x1403b90ff    src/game.cpp:3205    game::load_world_modfiles()
  #9
    (dbghelp: @0x7ff752598b95[cataclysm-tiles.exe+0x3d8b95]), 
    (libbacktrace: game::setup()+0xc9@0x1403d8b95),
    0x1403d8b95    src/game.cpp:792    game::setup()
  #10
    (dbghelp: @0x7ff752812b6e[cataclysm-tiles.exe+0x652b6e]), 
    (libbacktrace: main_menu::new_character_tab()+0xaee@0x140652b6e),
    0x140652b6e    src/main_menu.cpp:1060    main_menu::new_character_tab()
  #11
    (dbghelp: @0x7ff7528150e5[cataclysm-tiles.exe+0x6550e5]), 
    (libbacktrace: main_menu::opening_screen()+0x1147@0x1406550e5),
    0x1406550e5    src/main_menu.cpp:946    main_menu::opening_screen()
  #12
    (dbghelp: @0x7ff753a3bda7[cataclysm-tiles.exe+0x187bda7]), 
    (libbacktrace: main+0x2046@0x14187bda7),
    0x14187bda7    src/main.cpp:867    main
  #13
    (dbghelp: @0x7ff7521c13ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: __tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #14
    (dbghelp: @0x7ff7521c14c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #15
    (dbghelp: BaseThreadInitThunk+0x1d@0x7ff9531f257d[KERNEL32.DLL+0x1257d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #16
    (dbghelp: RtlUserThreadStart+0x28@0x7ff954bcaf28[ntdll.dll+0x5af28]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/material.cpp:189 [void material_type::check() const] material stainless_steel is missing required resistance for "cut"
10:31:42.736 ERROR : src/material.cpp:189 [void material_type::check() const] material stainless_steel is missing required resistance for "bullet"
10:31:42.753 ERROR : src/material.cpp:189 [void material_type::check() const] material stainless_steel is missing required resistance for "acid"
10:31:42.753 ERROR : src/material.cpp:189 [void material_type::check() const] material stainless_steel is missing required resistance for "heat"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_single is missing required resistance for "bash"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_single is missing required resistance for "cut"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_single is missing required resistance for "bullet"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_single is missing required resistance for "acid"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_single is missing required resistance for "heat"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_double is missing required resistance for "bash"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_double is missing required resistance for "cut"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_double is missing required resistance for "bullet"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_double is missing required resistance for "acid"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material powder_smokeless_double is missing required resistance for "heat"
10:31:42.958 ERROR : src/material.cpp:189 [void material_type::check() const] material explosive_primer_lead_styphnate is missing required resistance for "bash"
10:31:42.959 ERROR : src/material.cpp:189 [void material_type::check() const] material explosive_primer_lead_styphnate is missing required resistance for "cut"
10:31:42.959 ERROR : src/material.cpp:189 [void material_type::check() const] material explosive_primer_lead_styphnate is missing required resistance for "bullet"
10:31:42.959 ERROR : src/material.cpp:189 [void material_type::check() const] material explosive_primer_lead_styphnate is missing required resistance for "acid"
10:31:42.959 ERROR : src/material.cpp:189 [void material_type::check() const] material explosive_primer_lead_styphnate is missing required resistance for "heat"
10:32:08.545 ERROR : src/mapdata.cpp:1057 [virtual void ter_t::check() const] ter blob_pit has EASY_DECONSTRUCT flag but cannot be deconstructed
11:00:48.769 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff752453cae[cataclysm-tiles.exe+0x293cae]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x140293cae),
    0x140293cae    src/debug.cpp:1143    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff752454bd7[cataclysm-tiles.exe+0x294bd7]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x211@0x140294bd7),
    0x140294bd7    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/time.h:246    time
    0x140294bd7    src/debug.cpp:1471    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x7ff752455b96[cataclysm-tiles.exe+0x295b96]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x140295b96),
    0x140295b96    src/debug.cpp:519    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x7ff7532999df[cataclysm-tiles.exe+0x10d99df]), 
    (libbacktrace: void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)+0xdf@0x1410d99df),
    0x1410d99df    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/basic_string.h:795    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x1410d99df    src/debug.h:78    void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)
  #4
    (dbghelp: @0x7ff752872419[cataclysm-tiles.exe+0x6b2419]), 
    (libbacktrace: ter_t::check() const+0x529@0x1406b2419),
    0x1406b2419    src/mapdata.cpp:1057    ter_t::check() const
  #5
    (dbghelp: @0x7ff75286bb28[cataclysm-tiles.exe+0x6abb28]), 
    (libbacktrace: check_furniture_and_terrain()+0x29@0x1406abb28),
    0x1406abb28    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_iterator.h:1108    __gnu_cxx::__normal_iterator<ter_t const*, std::vector<ter_t, std::allocator<ter_t> > >::operator++()
    0x1406abb28    src/generic_factory.h:414    generic_factory<ter_t>::check() const
    0x1406abb28    src/mapdata.cpp:1253    check_furniture_and_terrain()
  #6
    (dbghelp: @0x7ff752630c1a[cataclysm-tiles.exe+0x470c1a]), 
    (libbacktrace: DynamicDataLoader::check_consistency()+0x2996@0x140470c1a),
    0x140470c1a    src/init.cpp:877    DynamicDataLoader::check_consistency()
  #7
    (dbghelp: @0x7ff7526334a1[cataclysm-tiles.exe+0x4734a1]), 
    (libbacktrace: DynamicDataLoader::finalize_loaded_data()+0x23bd@0x1404734a1),
    0x1404734a1    src/init.cpp:776    DynamicDataLoader::finalize_loaded_data()
  #8
    (dbghelp: @0x7ff7525790ff[cataclysm-tiles.exe+0x3b90ff]), 
    (libbacktrace: game::load_world_modfiles()+0x419@0x1403b90ff),
    0x1403b90ff    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_set.h:281    ~set
    0x1403b90ff    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_set.h:281    std::set<string_id<MOD_INFORMATION>, std::less<string_id<MOD_INFORMATION> >, std::allocator<string_id<MOD_INFORMATION> > >::~set()
    0x1403b90ff    src/game.cpp:3205    game::load_world_modfiles()
  #9
    (dbghelp: @0x7ff752598b95[cataclysm-tiles.exe+0x3d8b95]), 
    (libbacktrace: game::setup()+0xc9@0x1403d8b95),
    0x1403d8b95    src/game.cpp:792    game::setup()
  #10
    (dbghelp: @0x7ff752812b6e[cataclysm-tiles.exe+0x652b6e]), 
    (libbacktrace: main_menu::new_character_tab()+0xaee@0x140652b6e),
    0x140652b6e    src/main_menu.cpp:1060    main_menu::new_character_tab()
  #11
    (dbghelp: @0x7ff7528150e5[cataclysm-tiles.exe+0x6550e5]), 
    (libbacktrace: main_menu::opening_screen()+0x1147@0x1406550e5),
    0x1406550e5    src/main_menu.cpp:946    main_menu::opening_screen()
  #12
    (dbghelp: @0x7ff753a3bda7[cataclysm-tiles.exe+0x187bda7]), 
    (libbacktrace: main+0x2046@0x14187bda7),
    0x14187bda7    src/main.cpp:867    main
  #13
    (dbghelp: @0x7ff7521c13ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: __tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #14
    (dbghelp: @0x7ff7521c14c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #15
    (dbghelp: BaseThreadInitThunk+0x1d@0x7ff9531f257d[KERNEL32.DLL+0x1257d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #16
    (dbghelp: RtlUserThreadStart+0x28@0x7ff954bcaf28[ntdll.dll+0x5af28]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/mapdata.cpp:1057 [virtual void ter_t::check() const] ter blob_pit_slime has EASY_DECONSTRUCT flag but cannot be deconstructed
11:00:50.604 ERROR : src/mutation_data.cpp:726 [static void mutation_branch::check_consistency()] mutation POISONOUS is in category SLIME but none of its slot 1 prereqs have this category
11:00:52.536 ERROR : src/mutation_data.cpp:726 [static void mutation_branch::check_consistency()] mutation OVERLY_ACID_GUT is in category SLIME but none of its slot 1 prereqs have this category

**Comment by RenechCDDA** [comment] 2024-09-22 15:49
>Used gateway to go from Hub 01 to the Exodii, The place I teleported from went grey (Unseen location) & I turned into the sprite that IR goggles uses. Doing anything (I.E. pressing tab, moving etc.) causes it to crash

Duplicate of #54088

In the future please attach save files as it requires. The debug log you provided was not helpful or relevant.

**Closed by RenechCDDA** 2024-09-22 15:49 UTC
Labels: (S1 - Need confirmation)
