### ISSUE TITLE
Disappearing items.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#10610] opened 2014-12-23 20:17 UTC
From http://smf.cataclysmdda.com/index.php?topic=8998.msg204379#msg204379

>Items which "expire" (marked blue) disappear when dropped from inventory

**Comment by delvr** [comment] 2015-01-02 13:59
I'm surprised to see the no-repro reports here and on the thread, this bug has pretty much stopped me from playing CDDA in the past week or so.

It happened to every game I've played since 2546 or earlier (not sure exactly). Last time was on 2573 when I dropped a "tin can of curry with meat (fresh)" on the floor and it disappeared.

I wish I had a save from before it happened, at least a have one from just after that shows the dropping in the logs and no use of the item since. Would this be useful? What's the best place to post/send it?

**Comment by narc0tiq** [comment] 2015-01-02 15:50
Oh, I bet it's the thing I fixed in #10700. It had this behaviour, together with that of destroying an active item per turn until getting their indices below 64.

If you reproduce it again, reopen this, but otherwise I'm calling it fixed.

**Closed by narc0tiq** 2015-01-02 15:50 UTC
Labels: Bug

**Comment by delvr** [comment] 2015-01-02 17:48
Awesome! Starting a new game right now. Happy new year!
