### ISSUE TITLE
Recipes including candles crash the game

### ISSUE THREAD

**Issue by ShigeoToga** [CleverRaven/Cataclysm-DDA#50455] opened 2021-08-03 09:58 UTC
### Describe the bug

The recipe for candle and recipes with candles such as Jack o' Lantern cause the game to crash when they are highlighted in the crafting menu

### Steps To Reproduce

1. Open up crafting menu
2. Highlight or search the candle recipe or other recipes with candle
3. The game will crash

### Expected behavior

It should let me see the recipe when I highlight it, just like any other recipe

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: a676db7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Rural-Only Mapgen [ruralbiome],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6923185/save.zip)

**Comment by ZhilkinSerg** [comment] 2021-08-03 10:07
Duplicate of #50335

**Closed** 2021-08-03 11:18 UTC
