### ISSUE TITLE
Blank menu characters

### ISSUE THREAD

**Issue by RynhardGrey1** [CleverRaven/Cataclysm-DDA#52070] opened 2021-10-03 08:19 UTC
### Describe the bug

Hi there and thanks for the hard work as always!

Okay, so when I launched the game today with the Game Launcher and updated to the latest experimental version, (2021-10-03-0653) both the main menu and the in-game menu had either blank or black characters making it impossible to see. (Please see attached screenshots) I Rolled back to 2 previous versions (2021-10-03-0220 & 2021-10-02-1521) and the issue persisted, however, when I switch over to Stable 0.F Frank-2 it fixes the problem, but switching back to experimental and the issue will return. 

### Steps To Reproduce

1. Launch game with Game Launcher
2. Stare at blank screen
3. Exit and repeat step 1

### Expected behavior

All in game menu characters either blank or black, only applicable on experimental version. No Idea why. 

### Screenshots

![CDDA blank menu screen](https://user-images.githubusercontent.com/86912861/135745482-255b77eb-5169-4f86-8a9a-d4b456ddd7be.png)
![CDDA in-game blank menu screen](https://user-images.githubusercontent.com/86912861/135745646-801e0f21-ba30-4456-bdbb-a64f069846a9.png)

### Versions and configuration

- Windows 10, 64-bit
- 2021-10-03-0653, 2021-10-03-0220, 2021-10-02-1521 Confirmed so far for me.

**Comment by TealcOneill** [comment] 2021-10-03 08:21
duplicate of #52046

**Comment by BrettDong** [comment] 2021-10-03 08:27
Duplicate of #52046

**Closed** 2021-10-03 08:27 UTC
