### ISSUE TITLE
Crash to Desktop when activating First Aid Kit in crate

### ISSUE THREAD

**Issue by TimothyQuark** [CleverRaven/Cataclysm-DDA#35682] opened 2019-11-23 20:17 UTC
# Describe the bug

When standing next to a crate with a first aid kit in it and activating it (pressing a and selecting it from the drop down), the game crashes and an error message shows.
# Steps To Reproduce

1. Stand next to crate with first aid kit inside
2. Press a to open activation menu, select the first aid kit.
3. Game seg faults, freezes and crashes to desktop.

For the save provided (Stadium World):
1. There is an opened lab crate garage next to the player, one of the boxes has a first aid kit inside.

# Expected behavior

First Aid kit to drop at dissassemble and drop at player's feet. No seg fault. Putting the first aid kit into inventory and then activating it works normal.

# Screenshots
Crate in question is in the top garage bay.
https://imgur.com/a/uHgyZuB

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9619-g1681742 [64-bit] (build 9925)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Link to save file: https://drive.google.com/open?id=15qxr524TeXfnDhilJMUho9dOl_n1CI_a

CRASH LOG FILE: config/crash.log
VERSION: 0.D-9619-g1681742
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D76A5[cataclysm-tiles.exe+0x1D76A5]
    @0x5D8172[cataclysm-tiles.exe+0x1D8172]
    SMPEG_error+0x4B034@0xFCD320[cataclysm-tiles.exe+0xBCD320]
    _C_specific_handler+0x98@0x7FF9400B8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FF941D4477F[ntdll.dll+0xA477F]
    RtlWalkFrameChain+0x14BF@0x7FF941CA4BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FF941D434EE[ntdll.dll+0xA34EE]
    @0x7D0342[cataclysm-tiles.exe+0x3D0342]
    @0xCC71D3[cataclysm-tiles.exe+0x8C71D3]
    @0x4B49F3[cataclysm-tiles.exe+0xB49F3]
    @0x4B4B91[cataclysm-tiles.exe+0xB4B91]
    @0x7372F2[cataclysm-tiles.exe+0x3372F2]
    @0x71289D[cataclysm-tiles.exe+0x31289D]
    IMG_LoadWEBP_RW+0x6360CC@0x16F525C[cataclysm-tiles.exe+0x12F525C]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF93F4E7974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FF941D0A271[ntdll.dll+0x6A271]

**Comment by ZhilkinSerg** [comment] 2019-11-23 20:44
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/35673

**Closed by ZhilkinSerg** 2019-11-23 20:44 UTC
