### ISSUE TITLE
Magiclysm mod is in need of major rework in regards to mechanics, UI and balancing

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38170] opened 2020-02-19 22:37 UTC
Not sure if feature request or bug, but its in my opinion that the Magiclysm mod needs a major rework in regards to several aspects to become "viable".
- Houses with magic-related loot spawn way too rarely (like you maybe 1 in a big city, compared that to several survivor gun cellars).
- The loot you can find is rarely useful (oh look, 12 display cases with a total of 4 EMPTY wands of magic missiles, woooo. Party on)
- Thr magic themselve is in my opinion mostly underwhelming. Low tier spells do like 10 damage at low distance, so they are less impactful than a simple hand gun, while having a fixed maximum amount of ammo (usually ~ 10 - no reload), but also very high miss chances for the most part (unless you figure out the obscure skill system, see below)
- The more you advance in the game, the more magic lags behind. Once you find a shotgun, most attainable (low to mid) level spells are completely underwhelming. Why fire a lightning bolt or a frost spray when you can shotgun a guy for 70 damage and do it 50 times without worrying about mana.
-  As mentioned, its infurating hard to even get the skills / spells you want. It far far far harder to find a given spellbook or scroll than a "rare" propped up specific assault right and said assault rifle is way more useful. Odds are, if you even find anything magic-related, there is a good chance its for a class you locked earlier or it has difficulty 10 and hence you will be able to cast it 1 in 50 tries.
- The spell learning mechanic is obscure and needs more explanation (i.e. explain somewhere that there is spellcraft skill, a skill for every specific skill, how the two are linked, and that you have separate experience points. Explain the impact of leveling spellcraft, explain the impact of leveling up a specific skill more clearly than the current UI "explains")
- The fact that you need very specific gear to cast spells is a huge mess. I want to cast a firebolt and i dont want to drop or holder my damn handgun. If you really want to force 2-handed-spellcasting on the user, instead of forcing irritating micro-managing, just add a more severe cast-timer to "simulate" the encumbrance of the handgun.
- Even if you fully discount all the "damage"-spells and take only a lok at the various interesting buffs, its still confusing because the buff spells dont tell you what exactly they buff. And even then its a big micro-managment mess to buff yourself up for 5 to 10 turns, again dropping weapons, picking weapons up etc.
- When you read a scroll / try to learn a new spell, there is no indication how long it will take. Compare that cooking a meal or leveling a skill where you always have a %-value available somewhere. Transparency = good, random obscure things that noone gets = bad.

In my opinion, i really love the idea of zombies, lovecraft and some magic on top but as is, in my opinion, the magiclysm mod is a mess and would need a concerted effort to bring in it in line.
I would be willing to help bringing it in line as far as balancing / testing goes.

Im interested if other people have other experience with the mod in general.

**Comment by KorGgenT** [comment] 2020-02-19 23:24
OK, let's talk about your bullet points one by one.
1) there's a bit of lore behind houses in particular:
about 20-30% of people at the time of the cataclysm can cast at least one spell. maybe 10% of those we would consider "mages" which have studied magic to some degree and can cast a variety of spells. Only the mages would actually have books, while the others would only be casting the spell as little more than a curiosity, like juggling or the rubik's cube. this sort of dovetails into what i want, which is more areas that are specialized such as magic schools, or what i would consider a "dungeon" that would contain something like this. basically, more maps
2) sounds like an itemgroup issue. this should be an easy fix, as there's several itemgroups that have good items in them. and more magical items would be a good thing.
3) this has a strong lore reason behind it. as stated before, not many people know magic. compare the previous numbers at ~WWI of about 80% of people that can cast at least one spell, with something like 40% that have studied some, knowing two or more. real-world example: the chinese used crossbows instead of bows because it was easier to teach everyone. there's actually a code reason i didn't create a bunch of really powerful spells, because those should definitely exist. see #38112 . to summarize: yeah low tier spells are not going to be good compared to handguns. mid tier spells are not going to be good compared to assault rifles. high tier spells are military secrets.
4) this is just an extension of the previous bullet point
5) this is answered by a combination of 1) and 3)
6) this is definitely a valid concern, and i would like some more details from a player as to how this can be presented better.
7) ok i hear this as "too many button presses to cast a spell" am i correct? how about a query when you try to cast a spell with something in your hand you can't cast with to put it away? i suppose i can also get you to take it back out at the end too.
8) this isn't very clear what the issue is. maybe a combination of 6) and 7)?
9) this is also a valid concern.

So. this issue is pretty unfocused and i'd like separate issues for each of the following concerns:
- i want more map locations and itemgroups! this should not be an issue. it's an ongoing thing and i would _love_ for people to contribute stuff like this. itemgroups specifically i'd like to discuss on discord.
- the lore needs to be put into the mod better! this is another thing that i don't think should have an issue per se, but it's also weird because i've got all the lore in my head. wrestling with json is not a very happy thing for me so it's very slow for me to add such things... not only that, but i'm not experienced in putting lore in the game in a dynamic format
- information needs to be better! i'd like an issue written up for this one, because depending on where the information should be displayed it'd be a C++ thing. generally i'm the guy that does that, though i'm not exactly exclusive about it.
- too many button presses! this should be separate from the previous point as it's a different area of code, and i try to keep PRs as small as possible. discussion about exactly how it would be presented would also be welcome to present itself.

**Comment by Funguss** [comment] 2020-02-20 00:01
Regarding the lore... Could you maybe write it up and put it in a doc on Github? You could direct any contributors to that so they can get a sense of what to include, then discuss the new content with yourself.

**Comment by KorGgenT** [comment] 2020-02-20 00:32
i'll write up some stuff. maybe i'll stick it in a text file in the mod folder. if i could have like a Q&A with a few people on discord about lore it might be a bit more exhaustive

**Comment by KorGgenT** [comment] 2020-02-20 02:50
some lore questions should be answered in #38174. please ask in there if there are any more questions regarding lore. if there is no discussion in a day or two, i will close this PR and open an issue regarding the last bullet point in my comment. I don't really have a clear enough idea of what's missing from the UI to open an issue for bullet point 3 in my summary bullets.

**Comment by AncientSion** [comment] 2020-02-20 12:11
Im going to talk about your arguments for a bit.

You say you consider 20-30 % of the ppl magic-able and maybe 10 % of these could be considered "studied" in at least one area.

From what i can tell, the game experience at this point largely does not fall in line with your above lore.
I have raided 3 cities and found 1 magic shop. And i have scoured maybe 50 ? normal houses and none had any magic gear in them.
So, given your above numbers of 20-30 % magic users and 10 % proficient users, the loot tables (in normal houses) and the spawn rate of "special" houses would need to have very severe adjustments to span. At least double to triple of what i am experiencing ATM.

If the spawn rate of lesser magic items is increased (so they are (rarely) findable in common houses), then i really suggest that you add "lore" items to these spawns.
Im thinking newspapers or flyers that advertise magic, or tell magic-related stories.
Bookstores and libraries could have lore-books. There is as far as i am concerned absolutely no lore whatsoever to be found, except from stock core in regards to "lovecraft" elements.

In regards to the UI im really not a fan of the "spell overview" UI, the one that tells you the effect of the spell and the effects of leveling it further. I would wish to make it a bit larger in size and separate the columns more clearly. Also, as mentioned, clearly write the effects. For example if you check Bless or Cat of Bags you have to admit there is really very little information to find out wtf is actually happening.


Would you consider making 1 handed spell casting possible ?

Do you intend for spellcasting to be a somewhat "useful" either early, mid or lategame or is intended to be so much of a niche as to basically being unviable due to power levels as well as scarcity ?
Im going to be very blunt here: If im playing with Magicclysm but as a matter of fact the mod has absolutely no actual gameplay-influence, then im wondering why i should bother enabling it in the first place.

As mentioned, im a huge fan of adding magic but i wish it would actually add to the already extensive gameplay / variety options that CDDA offers.
Maybe im wrong, but im imagining Magic as something along the lines of CBMs and Mutations. A major feature with the exception that Magic, unlike CBMs and Mutations, already come into the gameplay early to mid opposed to lategame.
This vision of mine is bolstered by the fact that in your lore above you state 10 to 30 % of humans know or use magic, unlike mutations and CBMs ;)

**Comment by KorGgenT** [comment] 2020-02-20 14:27
i will review the rest of your questions later, but i feel like i had to nip this in the bud: we had a slight miscommunication. I don't mean 10% of the population, i mean 10% of the 20%. which is like 2% of the total, or thereabouts. so 50 houses with nothing in them and one magic shop in a city that's smaller than half a kilometer across sounds perfectly fine to me.

**Comment by KorGgenT** [comment] 2020-02-20 14:37
https://discord.gg/jFEc7Yp

As for one-handed casting: no. You either have an item that is a focus, or you need your hands free, or the spell doesn't need hands.

**Comment by Shibimon** [comment] 2020-02-20 15:31
I think magic should be even more rare, a bit more powerful and a lot more obscure, like being hid behind bookcases in basements, on buried treasure chests that have to be dug out, or just hidden out of normal sight.
Right now we have a bit of everything in the magic department, but i think somthing more like the Call of Cthulhu tabletop game magic system would be more related to the lovecraftian feel of cata dda, along the line of being decremental to your own sanity, that need sacrifices to be able to use.
I love the mod, even if i dont use lots magic knowing that is there and can be dabbled on its great.
I have this link, but im not sure if its ok to post it here on github, that explain almost perfectly all magic related to CoC and just by looking the spell names in the index (page 194) it feels much more close to dda game core.
https://thetrove.net/Books/Call%20of%20Cthulhu/Cthulhu%201920s/Call%20of%20Cthulhu%20-%20The%20Grand%20Grimoire%20of%20Cthulhu%20Mythos%20Magic.pdf

**Comment by KorGgenT** [comment] 2020-02-22 16:46
So barring #38238, and maybe some UI tweaks, there's not really much else actionable in this issue other than brainstorming. Which isn't really a bad thing, but Discord's a much better place for coming up with ideas to see what stick. The issue in general is quite unfocused, so i'm not going to leave it open any longer because i think I've extracted the valuable points out of it.

**Closed by KorGgenT** 2020-02-22 16:46 UTC
Labels: <Suggestion / Discussion>, Mods: Magiclysm
