### ISSUE TITLE
Turn off the wet towel before sleep?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73198] opened 2024-04-22 14:25 UTC
### Describe the bug

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f0012f8f-7fc8-425f-a636-2e1a28a2fe41)

### Attach save file

n/a

### Steps to reproduce

1. Use a towel
2. Go to bed

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-21-0738 0a3e18c [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90,0%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by NetSysFire** [comment] 2024-04-23 23:28
Duplicate of #59809

**Closed by NetSysFire** 2024-04-23 23:28 UTC
Labels: (S1 - Need confirmation)
