### ISSUE TITLE
Using a smartphone case disables automatic functionality (time and calorie tracker)

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68292] opened 2023-09-24 11:53 UTC
### Describe the bug

When carrying a smartphone some of it's functionality is automatically activated - you can see the time on the main screen, and you can see calorie information on the eat screen.

However once the smartphone is inserted into a case this functionality is disabled. 

### Attach save file

N/A

### Steps to reproduce

Should be trivially reproducible. Make sure there are no watches or other phones in inventory that can confound the test.

### Expected behavior

The time and calorie information should be available even if the phone is in a case. 

If we want to be hyper-realistic then disable ability to use sdcards until phone is removed from case :)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/72a24970-553d-401e-a21b-6acd297d24a5)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 83978be [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by ZhilkinSerg** [comment] 2023-09-24 17:02
Duplicate of #68075

**Closed by ZhilkinSerg** 2023-09-24 17:02 UTC
Labels: (S1 - Need confirmation)
