### ISSUE TITLE
Pseudo Terrain appearing in No_Hope mod.

### ISSUE THREAD

**Issue by moeydea** [CleverRaven/Cataclysm-DDA#78164] opened 2024-11-26 08:27 UTC
### With the No_Hope mod, pseudo terrain appear in batches in open terrain, forest trails, near/in swamps, or sporadically in meadows.
![Screenshot_5](https://github.com/user-attachments/assets/d371b4a3-557a-41b6-874d-05a03bd60c07)
### Another example of pseudo terrain with no_hope mod.
![Screenshot_6](https://github.com/user-attachments/assets/c9601d13-bd7b-4f52-9e48-4bbf2060e70f)

### All the saves provided have the same mods and build.

- Near a swamp
[Negra-trimmed.tar.gz](https://github.com/user-attachments/files/17914936/Negra-trimmed.tar.gz)
- In a forest trail
[Inland-trimmed.tar.gz](https://github.com/user-attachments/files/17915004/Inland-trimmed.tar.gz)
- In the meadow.
[Fruit Hill-trimmed.tar.gz](https://github.com/user-attachments/files/17915045/Fruit.Hill-trimmed.tar.gz)

### Steps to reproduce

1: Create a world with the No_Hope mod.
2: Walk through an open field, a forest trail, in or near a swamp, or walk in a meadow. You will eventually find pseudo terrain.

### Expected behavior

There should not be any instance of pseudo terrain appearing in batches.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 703746d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope]
]

### Additional context

Edit: Playing around with the map-editor, the tile code for the pseudo terrain is:
![Screenshot_7](https://github.com/user-attachments/assets/de2aaa45-1cd2-4bae-a41c-8e84e369368c)

**Comment by ZhilkinSerg** [comment] 2024-11-26 11:01
Duplicate of #78158

**Closed** 2024-11-26 11:01 UTC
Labels: (S3 - Duplicate)
