### ISSUE TITLE
Dino Dave castle cardboard roof was created on ground floor. 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#70927] opened 2024-01-14 10:03 UTC
### Describe the bug

Dino Dave castle cardboard roof was created on ground floor instead of refugee center roof. 
Refugee center entrance is  North oriented. 

### Attach save file

[Leonard-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13930999/Leonard-trimmed.tar.gz)

### Steps to reproduce

1. Complite Dino Dave quests.
2. Let him build castle.
3. Castle cardboard roof is created on ground floor. 

### Expected behavior

Castle cardboard roof should be created on the roof of refugee center. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/d16725af-a81e-48ef-b1db-02a4ef2bf1f3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: cc78dc5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment] 2024-01-14 11:12
Duplicate of #69193

**Closed by RenechCDDA** 2024-01-14 11:12 UTC
Labels: (S1 - Need confirmation)
