### ISSUE TITLE
Attempting to build metal charcoal kiln crashes game

### ISSUE THREAD

**Issue by yizow** [CleverRaven/Cataclysm-DDA#66435] opened 2023-06-24 23:18 UTC
### Describe the bug

Attempting to build metal charcoal kiln from construction menu causes game to freeze and hang between 5-10%. Forced to alt-f4 to quit

### Attach save file

[Morovis-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11858376/Morovis-trimmed.tar.gz)

### Steps to reproduce

1) Load save
2) Construct metal charcoal kiln to east of existing charcoal kiln
3) Game will crash

### Expected behavior

Game does not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 720adec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Attached logs, but they don't seem relevant. This bug causes an entire system hang that doesn't seem to cleanly exit and generate these logs.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11858377/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11858378/crash.log)

**Comment by yizow** [comment] 2023-06-24 23:20
seems to not be tied to the kiln itself; just waiting for 5 minutes also causes a crash.

I see that my follower is attempting to do _some_ task but unable to find a proper tool

**Comment by RenechCDDA** [comment] 2023-06-28 00:07
Duplicate of #64799

**Closed by RenechCDDA** 2023-06-28 00:07 UTC
Labels: (S1 - Need confirmation)
