### ISSUE TITLE
Screen not redrawing after quicksave/autosave and other menus.

### ISSUE THREAD

**Issue by Brian361** [CleverRaven/Cataclysm-DDA#16993] opened 2016-06-01 19:48 UTC
Latest few builds. Save menu remains onscreen after completion and a few screens leave the entire screen black until portions of it are redrawn.

**Comment by kevingranade** [comment] 2016-06-01 20:00
I think this is a side effect of the character creation crash fix, a screen
refresh was removed.

**Comment by Fallingferret** [comment] 2016-06-01 21:04
It's a problem only on the SDL/Tiles build when using ASCII(or looking at the map if using a tileset): #16934 and it seems to be a byproduct of #16692

**Comment by Podesta** [comment] 2016-06-02 00:26
It's not really a side effect of the fix. Even with the merge of #16692 , and before the character creation crash fix was merged, the issue remained. What caused this is a bit earlier, but despite some recent attempts by @DanmakuDan which fixed a lot of the problems, some still remain.

**Comment by illi-kun** [comment] 2016-06-02 08:41
Agree, this is a duplicate of issue pointed by @Podesta.

**Closed by illi-kun** 2016-06-02 08:41 UTC
