### ISSUE TITLE
Peeking down stairs sometimes peeks to a different room than the stairs

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#49162] opened 2021-06-03 17:44 UTC
The problem: When peeking downstairs, you can sometimes view a different room than the one the stairs are actually in. 
I've had this problem occur mostly in science labs.

When it occurs, it is repeatable multiple times 100%. Climb down and you go to the actual stairs, climb back up and peek and you look at a different room entirely. Try it on both stairs in a two stair set, both peeks lead to the same spot in a different room. Climbing down both stairs leads correctly to the actual stairs on the lower floor.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: fe42098 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]
]

**Comment by Psiclops** [comment] 2021-06-03 20:43
I've also just had the same problem occur peeking UP stairs. Peek goes to a specific point in the room that is not near the stairs, and in this case is physically not observable from the square the real stairs are on. Same general room, different location.

**Comment by natsirt721** [comment] 2021-06-03 21:57
In the early days of Z-levels, the mapgen code didn't require to you place staircases in the exact same spot on both floors. Going up or down stairs could translate you slightly within the tile. There was a worldgen option to force staircase alignment but it was pretty janky and would sometimes put staircases in the middle of walls or other nonsensical places. Anyway, not sure if that is still a thing or not, but it sounds similar to what you're experiencing. I'm guessing that if it _is_ still a thing, then you're actually being translated slightly when you go up or down stairs still, but the peek down command just moves your cursor down one z level - hence the offset.

**Comment by mft-dev** [comment] 2021-06-05 08:46
I've seen this happen in lab starts quite a bit the last few days.

**Comment by OliveChukar** [comment] 2021-06-05 17:24
I have seen this most often with places that have multiple sets of stairs on one overmap tile.  In subway stations I will often end up looking down a stairway on the opposite side of the building from where I am standing.  When I stop peaking I am transported instantly to a different stairway.

**Comment by Psiclops** [comment] 2021-06-05 17:52
That may be a different issue. In these cases, there was just one set of stairs in the map tile, and the peek was going to a spot with no stairs.

**Comment by esotericist** [comment] 2021-06-06 14:51
the old labs are slated for replacement for this and other reasons

this isn't a "bug" in the usual sense. it's old dated content, and there are already plans and preliminary effort to replace it

at some point, possibly around the time #41758 is happening, possibly some other time, we can get rid of the teleporting stair logic entirely and start erroring on content that has stairs defined misaligned.

**Comment by esotericist** [comment] 2021-06-06 15:01
I wanted to close this in favor of the older issue I was certain we have, but it doesn't seem to exist.

**Comment by lfaga** [comment] 2021-06-14 10:35
This is still broken at this time (build 2021-06-14-0542) and its not only broken at the "old labs", research facilities, prisons,  ALL labs are broken. This bug makes it almost unplayable 'cos you cant see where are you going when taking a stair (peeking shows you the wrong room or nothing at all), probably entering a room that will kill you. I love lab starts and this bug is game breaking for me.

**Comment by Zeropol** [comment] 2021-06-14 11:29
Does this happen before #49014 ? It may need to be reverted if it introduced this bug.

**Comment by lfaga** [comment] 2021-06-14 23:49
I had to revert to build 11581 to avoid this bug.

**Comment by actual-nh** [comment] 2021-06-14 23:57
Long-term removed because, if you can fix it via reverting to a prior build, and the content in question hasn't been touched, it's not a content problem.

**Comment by anothersimulacrum** [comment] 2021-06-15 00:04
I think long-term is still valid because the fundamental issue is that stairs do not align, and in the long term, that shouldn't happen. So while we can apply a patch in the short term to fix a visible symptom of that behavior, it does not fix the behavior.

**Comment by GGgatherer** [comment] 2021-06-15 13:23
> This is still broken at this time (build 2021-06-14-0542) and its not only broken at the "old labs", research facilities, prisons, ALL labs are broken.
Even lab towers are broken ,just had this happen yesterday on multiple floors of the same tower.

**Comment by dranitski** [comment] 2021-09-12 22:13
I have another case for that issue - once Ive faced a military bunker but lacked tools to hack the front door. I have constructed a downstair (with pickaxe) to visit the bunker and when I was peeking down my self-built downstairs, the game showed me like I was peeking from the main bunker downstairs. Also the game did not allowed me to go up through the main bunker underground upstairs, always throwing me out of the bunker like if I was traveled up via my upstairs. So that issue is not about peeking, but about moving via stairs down and up as well

**Comment by wapcaplet** [comment] 2022-01-16 16:10
This issue has come up so many times in the form of duplicates, I just wanted to link all the ones I know of here, since this issue was the first.

#52379 - Peeking up/down stairs is having weird effects
#53388 - Peeking on top level of subway station just moves your character to second set of stairs
#54076 - Peeking down stairs teleports me to the middle of the room
#54357 - Peeking in a particular basement is not working as intended
#36833 - Going up stairs from a basement teleport to a different set of stairs

**Comment by sulyi** [comment] 2022-03-17 17:04
This also effects path finding, light, etc. which still remain.

There's a consequence solving this long term is by reworking map generation.

**Closed** 2022-06-19 23:47 UTC
Labels: <Bug>, (S2 - Confirmed), (P2 - High), (P5 - Long-term), Map / Mapgen, Z-levels
