### ISSUE TITLE
Washing stacks of rags and similars doesn't work properly

### ISSUE THREAD

**Issue by bloodraven983** [CleverRaven/Cataclysm-DDA#41610] opened 2020-06-26 17:25 UTC
# Describe the bug

I cut out some armor and clothing took from an unfriendly zombie cop and I went washing it

stacks of rags and layered kevlar appear to be washed one at a time and every time it consumes one unit of detergent which is very slow, cumbersome and material costly (one rag = one unit of detergent)

# Steps To Reproduce

cut out some filthy clothing and try washing it with a washing kit to an infinite water source

# Expected behavior
it should wash it in one go and calculate the amount of detergent required

# Screenshots

before
![image](https://user-images.githubusercontent.com/66170818/85884239-99db4f00-b7e2-11ea-8cef-1b22c870dbc7.png)

next washing session
![image](https://user-images.githubusercontent.com/66170818/85884281-ab245b80-b7e2-11ea-9fb0-deeef9e2343a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3489-g6e97042 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

**Comment by anothersimulacrum** [comment] 2020-06-26 22:20
Duplicate of #40404

**Closed by anothersimulacrum** 2020-06-26 22:20 UTC
