### ISSUE TITLE
No NPC needs: NPCs have needs

### ISSUE THREAD

**Issue by Funguss** [CleverRaven/Cataclysm-DDA#35609] opened 2019-11-20 00:28 UTC
# Describe the bug

Ironically enough, NPCs still have needs when No NPC Needs is enabled. Also still have needs with Debug Life Support mutation. This bug has existed for over a week or so, not sure what caused it. I'm actually happy to discover that many of the previous issues that caused me to turn them off have been fixed so it's no longer frustrating to keep them happy.

# Steps To Reproduce

Well... Turn it on and chill with an NPC. Watch them complain about needing a drink and wanting to sleep. It does seem that they don't get hungry, though.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9499-gd0db81d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

**Comment by ZhilkinSerg** [comment] 2019-11-20 00:32
Duplicate of #30501

**Closed by ZhilkinSerg** 2019-11-20 00:32 UTC

**Comment by Funguss** [comment] 2019-11-20 01:20
Wow, sorry for the dupe. I had NPCs with no needs up until fairly recently so I thought this was new.
