### ISSUE TITLE
Picture based beastiary

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#51685] opened 2021-09-18 04:15 UTC
# Is your feature request related to a problem? Please describe.

Upon taking a picture of a monster/etc, it would be an interesting and immersive way to have an in-game wiki
# Describe the solution you'd like

Upon taking a picture of a monster, you get a data entry in the device used to take the picture, which details some of the stats for the particular monster you had taken a picture of, as well as the sprite for the monster in the used tileset. Stats such as speed, hp, armor, regeneration, and strength would be useful metrics, and would be a more immersive way of getting specific information without having to visit the wiki or go code browsing; not to mention, it would be a great goal for players, to fill out their beastiary. 
# Describe alternatives you've considered

While this could be considered a bit gamey, I think it's within reason to have a way for survivors to keep notes on monsters they encounter, however, perhaps taking the picture only allows you to start recording data, and then you must kill the monster to learn its hp, regen, and armor; attempt to run away to learn its speed, and so on. However, I believe that would overly complicate things.
# Additional context

Although I can't seem to find it at this present moment, there was an artist that drew a smol slime blob compiled with its stats, which would be a good format for how to display an entry in the bestiary.
The pokedex from pokemon may be a good format to display the full list, before you open individual entries.
![image](https://user-images.githubusercontent.com/43324177/133872108-39d7786b-a6b5-4e6c-ade4-77a4896f0fa3.png)

**Comment by ZhilkinSerg** [comment] 2021-09-18 06:02
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/36479

**Comment by Night-Pryanik** [comment] 2021-10-09 12:59
Closing as duplicate.

**Closed by Night-Pryanik** 2021-10-09 12:59 UTC
Labels: <Enhancement / Feature>, Info / User Interface, Monsters, Game: Achievements / Conducts / Scores
