### ISSUE TITLE
Can't use vehicle welding rig to repair items

### ISSUE THREAD

**Issue by enaantd** [CleverRaven/Cataclysm-DDA#41167] opened 2020-06-08 12:58 UTC
# Describe the bug

Repairing an item with a vehicle welding rig doesn't work anymore. This message shows up: "Your arc welder has 0 charges but needs 5", even though the vehicle has batteries.

# Steps To Reproduce

1. Install a vehicle welding rig in a vehicle
2. Get a damaged item (e.g. an aluminum bat)
3. Try to activate the welding rig

# Expected behavior

We should be able to use the welding rig to repair items.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-3038-g507d4d21f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by GGgatherer** [comment] 2020-06-08 14:46
Probably same cause as #41018

**Comment by anothersimulacrum** [comment] 2020-06-08 15:07
Yeah, appears to be a duplicate of #41018.

**Closed by anothersimulacrum** 2020-06-08 15:07 UTC
Labels: (S3 - Duplicate)
