### ISSUE TITLE
Sling-throwing makes 60-volume bang noises [More Survival Stuff's ammo lacks loudness value]

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#18025] opened 2016-08-14 05:03 UTC
>You hit the blob for 6 damage.  
>You hear bang!

I mean, it's a sling. Throwing clay pebbles. I can expect "swish" for it moving, "thump"/"bwong"/"tink" for projectile impact, but not "bang". My character isn't stupid or silly to actually be making "bang" noises with their mouth, either.

**Comment by DaliTimelord** [comment] 2016-08-14 06:05
Even if your character was making a "bang" noise from their mouth, the best my character can manage is Sound 3 when yelling. I'm assuming Sound directly scales with Decibels. [Since a child screaming is about 80 decibels](http://4.bp.blogspot.com/-bW7YrrOIF9U/TpG_jvGze5I/AAAAAAAAAMg/2bETm7xhrAA/s1600/db+levels.jpg), _I'm assuming the noise your singshot makes is about 1600 decibels._

**Comment by Barhandar** [comment] 2016-08-14 07:38
Actually, the sound system in general is borked, and has been for quite a while (before build 4307 at least - that build is a bit louder but there's still no pain and hearing loss clears up extremely fast). Slings being unreasonably loud is just a side effect.

[According to this table](http://www.gcaudio.com/resources/howtos/loudness.html), pain begins at 125 dB, and shotgun blast makes 165 dB, with most gunfire being 140 dB and above according to other sources.   
Currently, firing a shotgun makes 160 Sound with no hearing changes.  It should be immediately painful and result in temporarily reduced hearing, but it does not. Pain has _a chance_ to be increased by 1 at same event that prints "Your ears ring!", which is not guaranteed to happen either.

**Comment by Xnfinity** [comment] 2016-08-14 22:48
The problem is that the ammo form the "more survival tools" mod do not have a loudness value so it uses the default

**Comment by Barhandar** [comment] 2016-08-15 00:13
>The problem is that the ammo form the "more survival tools" mod do not have a loudness value so it uses the default

It's an easy-fix issue, then. I think if ammo types'd have their own loudness value that specific ammo items adjust/override, the mods extending existing ammo'd not have this issue altogether.

**Comment by BorkBorkGoesTheCode** [comment] 2016-08-15 03:20
You could set the loudness level of the slingshot.

**Comment by Barhandar** [comment] 2016-08-15 05:58
How does that interact with ammo's loudness?

**Comment by Teacher-Tim** [comment] 2016-08-15 08:27
This gave me an idea. How about a sling that throws grenades?

**Comment by Barhandar** [comment] 2016-08-15 09:18
IRL, perfectly possible. Maybe a "large sling" kinda thing that can throw anything of volume 1 - pebbles, marbles and bearings are very small, after all. Real slings throw children-fist-sized rocks and other similarly-sized projectiles, after all.

Just don't forget to pull the pin and don't be too slow at loading and throwing.

**Comment by chaosvolt** [comment] 2016-08-28 08:58
That would be a failure on my part. Fix it yourself.

**Comment by chaosvolt** [comment] 2016-09-02 04:46
Clay pebbles, lead ball bearings, and bone crossbow bolts all need a loudness assigned to them.

**Closed** 2016-09-08 05:55 UTC
