### ISSUE TITLE
Cannot read recreational books

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#27496] opened 2019-01-08 10:25 UTC
**Describe the bug**  
I read a novel or religious text if I have the spiritual trait, I the time for a chapter passes, yet the chapter is not read, no morale gain whatsoever and no messages in the log other than to press 5 or . to stop reading.

Behavior does not change with bookworm or fast reader other than less time passed with fast reader.

**To Reproduce**  
1:create any new character
2:wish in a novel
3:read novel

**Expected behavior**  
Read recreational book: successfully read a chapter, gain morale

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: Self-compiled 8/01/2019 (D/MM/YYYY)
 - Graphics version: Tiles
 - Mods loaded: default, also occurs with PK rebalance and Arcana, mods do not affect it.

**Comment by swofle** [comment] 2019-01-08 17:15
I suspect this is caused by #27345.
A quick comparison against the old code suggests that the second argument for morale should not be zero, though I am not sure what is the correct value. 
@Inglonias Could you look into this?

> https://github.com/CleverRaven/Cataclysm-DDA/blob/4a1ab3493046cf682c929ea2933708c007a4fddd/src/player.cpp#L9541-L9544

**Comment by Inglonias** [comment] 2019-01-08 19:02
I'll look into this as soon as I can. Thanks for tagging me.

**Comment by Inglonias** [comment] 2019-01-08 21:23
Alright. I'm back at home and my first step is to reproduce the issue. Lets get to it!

**Comment by Inglonias** [comment] 2019-01-08 21:31
Alright, assuming the only problem is the one being reported here, this should be fixed on my end. Now, of course, I need to test it. No code is above testing.

**Comment by dissociativity** [comment] 2019-01-08 21:52
It seems that books do not give joy at all, regardless of recreational use

**Closed** 2019-01-09 04:37 UTC
Labels: <Bug>, Character / Player, Items / Item Actions / Item Qualities
