### ISSUE TITLE
M79 Launcher doesn't produce any 40x46mm casings after being fired.

### ISSUE THREAD

**Issue by jacobmwood** [CleverRaven/Cataclysm-DDA#42723] opened 2020-08-05 04:02 UTC
# Describe the bug

When a M79 launcher is fired, it doesn't produce any 40x46mm casing when using any of the 40x46mm shells.

# Steps To Reproduce

1. Make a player with a M79 launcher, and use any type of 40x46mm round.
2. Reload the round.
3. Fire the weapon at anything.
4. Reload the M79 launcher.

# Expected behavior

When you reload/fire the M79 launcher you should eject a a 40x46mm casing.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4795-g20b4523 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    No Fungal Monsters [No_Fungi],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

As a test I tried a RM802 Grenade launcher, and it was producing 40x46mm casings regardless of which round was used. This looks like it may be isolated to just the M79 Launcher.

**Comment by wapcaplet** [comment] 2020-09-18 00:22
Duplicate of #42941 / #44090

**Closed** 2020-09-18 00:23 UTC
Labels: (S3 - Duplicate), <Bug>
