### ISSUE TITLE
Unable to craft vehicle welding rig

### ISSUE THREAD

**Issue by Wad67** [CleverRaven/Cataclysm-DDA#29870] opened 2019-04-23 18:29 UTC
**Describe the bug**  
Attempting to craft a welding rig using a modified makeshift welder will not progress, despite requirements being fulfilled. 

**To Reproduce**  
Attempt to craft a welding rig using two makeshift welders as ingredients and one modded (vehicle battery compartment) makeshift welder as a tool. 

**Expected behavior**  
Should be able to produce a vehicle welding rig.

**Screenshots**  
![image](https://user-images.githubusercontent.com/991507/56606222-17d52080-6649-11e9-9fe0-94364bd4b432.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2092-gdf6c61e
 - Graphics version: Tiles
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/991507/56606342-5a96f880-6649-11e9-9eb7-d5db3ae47041.png)

**Additional context**

**Comment by curstwist** [comment] 2019-04-23 18:31
It won't recognize modded welders as a valid tool or component type.  Unmod the welder and it'll work (it would be nice to get this fixed though).

**Comment by Luiizz** [comment] 2019-04-23 18:43
Also you can't craft the welding rig with 2 makeshift welder, you'll actually need 3, 2 for the rig and one you'll actually use to weld them, that's why the makeshift welder name is brown.

**Comment by l29ah** [comment] 2019-04-23 19:10
Must be a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/19461

**Comment by Digi1980s** [comment] 2019-04-23 19:23
I have managed to reproduce it by using debug menu, it is indeed a bug.

**Comment by adamkad1** [comment] 2019-04-23 19:23
According to your description, you have 3 welders right? also, is one of welders filthy or something?

**Comment by evankimori** [comment] 2019-04-23 20:29
I'm having the same issue here. Crafted 3x Makeshift Welders. All normal, non dirty etc. 

Modded one with Battery Compartment to do ACTUAL welding. Other 2 x Makeshift Welders are in inventory and items nearby to craft the welding rig. Same issue as OP.

**Comment by kwl01skz** [comment] 2019-04-23 23:26
It is a very old bug.

**Comment by evankimori** [comment] 2019-04-24 03:10
I'm not coder but is there a way to set the coding yo detect (filter?) and use only 'empty and unmodded' items so that it does not cause a collision that enables the error? Just trying to think of ways we can approach this issue.

**Closed** 2019-04-30 03:07 UTC
Labels: <Bug>, Crafting / Construction / Recipes
