### ISSUE TITLE
Disconsolate Merc crashes game.

### ISSUE THREAD

**Issue by LadyCatnip** [CleverRaven/Cataclysm-DDA#60938] opened 2022-09-12 05:09 UTC
### Describe the bug

The game Crashes when purchasing the 5-Point-Anchor from the disconsolate Merc.

### Steps to reproduce

1. Advance the game far enough along that the terminal bar will populate near the hub.
2. Speak to the Disconsolate Merc and accept the offer to purchase the 5-Point-Anchor.
3. Game will crash the next time you pass a turn in game.

### Expected behavior

I expect the game to not crash when speaking to NPC's.

### Versions and configuration

OS: Windows 10
build type: windows-tiles-sounds-x64-msvc
build number: 2022-09-05-2002
Ingame Language: English
Mods Loaded: dda, xedra_evolved, No_Rail_Stations, no_npc_food, no_fungal_growth, StatsThroughSkills, speedydex.

### Additional context

I can't fit the save here but I still have it and am able to send it over discord. I'm Catnip#6227.

**Comment by Maleclypse** [comment] 2022-09-17 04:58
Will the save not fit when zipped?

**Comment by LadyCatnip** [comment] 2022-09-18 11:59
The save won't fit even when I zip it at maximum compression using 7zip. But I feel like it should be able to be recreated by someone else if they wait until the mercenaries start spawning in the 'Terminal Bar', and speak to the Disconsolate Merc.

**Comment by John-Candlebury** [comment] 2022-09-21 05:07
Cant reproduce this with the steps provided in the newest experimental.

So I'd appreciate it if you can send me the save file through discord. Im also candlebury over there

**Comment by LadyCatnip** [comment] 2022-09-21 19:00
[Pine Ridge 1-3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9619611/Pine.Ridge.1-3.zip)
[Pine Ridge 2-3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9619612/Pine.Ridge.2-3.zip)
[Pine Ridge 3-3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9619614/Pine.Ridge.3-3.zip)


That's the save file, extract them and put them together in the same folder.

**Comment by LadyCatnip** [comment] 2022-09-21 19:57
I was able to recreate this crash on the most recent experimental https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-21-1531 using the same mods that I was using. I used debug to advance the ingame time and retrieve the items for the Hub quests I had completed by that point in time and I managed to get that particular save file to fit in a much smaller package. Just speak to the disconsolate merc, buy the five point anchor and when you exit the conversation the game will crash.

[Winsted.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9619977/Winsted.zip)

**Comment by thomashodgkinson1987** [comment] 2022-11-12 23:33
I'm also having this same problem - once I have finished the conversation with him and I receive the anchor I cannot do the following without the game crashing:

Drop, throw, wear or weild the anchor
Moving a step

I'm not sure if he is meant to disappear after receiving the item (from the conversation/chat window I'm sure it states that he disappears quickly as soon as you get the anchor?), but he stays there. I can't find any crash log to look in to this. I've had a quick look at the JSON file "BEM_anchor_seller.json" but to be honest I haven't look at any of the games code so I wouldn't know where to start.

**Comment by mqrause** [comment] 2022-11-24 17:13
I can't reproduce this using the Winsted save from above on f6e4f2feed5ac31e40378553de800e606debc186.

**Comment by RenechCDDA** [comment] 2022-11-24 17:19
I also cannot reproduce this, compiled with VS from 43dbd7a5b220f5c68254d29fb13695fffb4fc165 and a downloaded copy at 25a0ca0 

(This issue was mentioned in the development discord, which is why it's receiving so much attention all at once, if you are curious!)

**Comment by I-am-Erk** [comment] 2022-11-24 20:54
I'm gonna close this specific issue when 62362 merges, but I would love someone to post an issue with the stuff discussed on reddit about the underlying bug. This was hard to identify and I don't want to lose that information when it comes up again.

**Closed** 2022-11-24 21:15 UTC
Labels: NPC / Factions, <Crash / Freeze>, (S1 - Need confirmation)
