### ISSUE TITLE
Default font in SDL build should support UTF8

### ISSUE THREAD

**Issue by Nullsrc** [CleverRaven/Cataclysm-DDA#16254] opened 2016-04-18 03:44 UTC
One of the string handling methods provided by catacharset.cpp is the utf8_wrapper::shorten() method, which can take a string, be fed a given length, and truncate the string down to that length, with the last character of the new string being an ellipsis, `\u2026`.

However, in SDL builds of the game, the font used for the interface does not contain this character and instead displays a tofu box. Whether a given ncurses build will support this character is also spotty, due to its dependency on the font settings of the console in which it is run.

Not quite sure what should be done about it, although the most generic solution is to simply make the method replace the last three characters of the shortened string with `...` instead of an ellipsis.

**Comment by Zireael07** [comment] 2016-04-18 17:28
I thought the tofu box was a feature lol

Good to know!

**Comment by Nullsrc** [comment] 2016-04-18 19:03
Well, we can _call_ it a feature, but in that case, whoever made it needs to seriously question their implementation.

In addition, aside from my work in #16253 , I'm not seeing anywhere in the source where that method is used, so it can hopefully be changed with little consequence.

**Comment by kevingranade** [comment] 2016-04-18 21:09
I'd much rather try and get utf8 working consistently than try and avoid
using it. We might want to ship a default font to make this work.

**Comment by nanovad** [comment] 2016-04-19 15:52
Ellipsizing with 3 periods also shortens the length of the actual string, does it not? The math would then have to be adjusted. I'm with @kevingranade on this - UTF8 should be supported rather than worked-around.

**Comment by Nullsrc** [comment] 2016-04-19 16:11
I agree. The shortening part of the three periods was implied, but irrelevant anyway.

**Comment by lucianposton** [comment] 2016-04-24 11:52
This issue also affects the more widely used trim_and_print(). See https://github.com/CleverRaven/Cataclysm-DDA/blob/654efd529f1650528e18d70d54b784e9f07f7c64/src/output.cpp#L177

**Comment by illi-kun** [comment] 2016-04-24 12:17
Similar issue was discussed here: #11501.

**Comment by lucianposton** [comment] 2016-04-24 13:42
#11501 is a dupe of this issue

Also see https://github.com/CleverRaven/Cataclysm-DDA/issues/12474

**Comment by codemime** [comment] 2017-01-15 10:42
Resolved in #19965.

**Closed by codemime** 2017-01-15 10:42 UTC
Labels: Organization, Other
