### ISSUE TITLE
Crash when entering town.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#26781] opened 2018-11-20 15:18 UTC
**Describe the bug**  
Game crashes when entering town.

**To Reproduce**  
Loading the linked savefile is most likely necessary to reproduce this issue.
1. Load savefile.
2. Go south and enter town.
3. Game crashes.

**Expected behavior**  
No crash.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 Professional
 - Game Version: 0.C-34714-g771c9e4
 - Graphics version: Tiles (MSX++Live_People)
 - Mods loaded: Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Makeshift Item Mods, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, StatsThroughSkills

**Additional context**  
I got an error message ingame one single time, something about 'Out of bounds add_vehicle', something like that. Don't remember the whole message.
Link to savefile:
https://www.dropbox.com/sh/br3h4hms0hy2kdf/AADP_SZGqa3H4W1VY-CSEqL7a?dl=0

**Comment by GoLoT** [comment] 2018-11-20 16:11
Likely related to #26777
Try downgrading to version 8194.

**Comment by Bulletfang** [comment] 2018-11-21 08:03
Downgraded to 8194 and the game is no longer crashing, definitely related.

**Comment by ZhilkinSerg** [comment] 2018-11-21 16:31
Closing as duplicate of #26777.

**Closed by ZhilkinSerg** 2018-11-21 16:31 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
