### ISSUE TITLE
Taking limb damage every 10 turns

### ISSUE THREAD

**Issue by Firons2** [CleverRaven/Cataclysm-DDA#28680] opened 2019-03-13 17:36 UTC
Game version: 
8608 experimental, updated via launcher

Operating system: 
Windows 10

Tiles or curses: 
Tiles

Mods active:
Dark Days Ahead, Disable NPC Needs, Filthy Clothing and StatsThroughSkills

### Expected behavior
Normal game play, without taking damage every 10 turns.

### Actual behavior
Damage every 10 turns, to all extremities and the torso, except the legs, until death.

### Steps to reproduce the behavior
Create a new world, with StatsThroughSkills, begin playing with any character, wait or move around, have arms, head and torso reach the breaking threshold.

**Comment by AndrXi** [comment] 2019-03-13 17:45
I experienced it just moments ago as well , the StatsThroughSkills seems to also be missing the "main.lua" file. I'm not sure there is something to do with that.

**Comment by Dwaggy** [comment] 2019-03-13 18:10
This is happening for me too, Though its happening every turn for me. 1hp of damage to all limbs except legs, for every single move/wait/action, until the char dies from 0hp on head/chest and limb breaks.. Also have STS enabled.
Doesn't happen in 8607 or earlier. This is using a character/world saved in 8607

8608 turns STS in to a Json override, rather than lua. but somehow the calculations are done differently? or something is going on that is causing health degradation.

Also just did a quick test:
**This also happens to a new save on a new world**.. the moment they gain enough skill to bump a strength stat up, they begin to lose health at a steady rate till death.

**Comment by Tharn** [comment] 2019-03-13 18:43
Yep. Loaded game where I should be fully healthy and saw 102/148 health on torso, head, arms. Not legs.
Went to sleep, health crept up to 110/148 slowly.
Repair nanobots have no effect.

![Untitled](https://user-images.githubusercontent.com/13466852/54305785-454d9980-45c8-11e9-8f69-62c7122905db.png)

**Comment by anothersimulacrum** [comment] 2019-03-13 19:35
@AndrXi that's because STS is a json & C++ mod now, not a lua one.

**Comment by Tharn** [comment] 2019-03-13 20:54
This is not fixed in 8609.

**Comment by Dwaggy** [comment] 2019-03-13 21:25
Confirmed here too, This has not been fixed in 8609.
Char continues to take 1hp/turn damage on both arms, chest, and head. both new and old chars.

**Comment by Ilysen** [comment] 2019-03-13 22:20
[Pain is weakness leaving the body!](https://wiki.teamfortress.com/w/images/b/b3/Soldier_jeers07.wav)

**Comment by Little-119** [comment] 2019-03-14 00:04
This seems to happen (for me) when I make a new world with just Dark Days Ahead and make a default (evacuee, survivor, no traits, 8/8/8/8 stats, no skills) character. I die after 8 in-game minutes.

**Comment by anothersimulacrum** [comment] 2019-03-14 00:46
Have you updated?

**Comment by MisterWytt** [comment] 2019-03-16 13:17
Sorry to bring this up, but STS is still broken, albeit in a less noticeable way. HP still degenerates at a much slower pace, but enough to notice. You just have to wait awhile and see that all of your limbs slowly take 1 HP damage. Just found this out when my 5 HP'd Head kept going down and down while trying to recover it.

**Comment by Tharn** [comment] 2019-03-17 04:22
I'd rather nothing was removed and the calculation just be fixed. It worked fine before, so the issue is that it wasn't transferred to the new format properly.

**Comment by wapcaplet** [comment] 2020-09-26 00:35
Could not reproduce in 0.E-6177-g 9f4a1b841d with Stats Through Skills enabled. Waited 24 hours with no damage to any body part. Same effect with skills leveled up and all stats at +4 from their base values. Closing issue.

**Closed by wapcaplet** 2020-09-26 00:35 UTC
Labels: <Bug>, Mods
