### ISSUE TITLE
Vehicle cannot be seen on the screen while driving with new sidebar

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#29181] opened 2019-04-01 00:06 UTC
**Describe the bug**  
When I'm driving to east/west, the camera focus shifts too much so the vehicle cannot be seen on the screen. Driving north/south - the vehicle moves to the top/bottom of the screen, so I can still see it.

**To Reproduce**  
1. In settings enable camera focus shifting while driving
2. Start driving a vehicle really fast to east or west.
3. Vehicle disappears from the screen.

**Expected behavior**  
Vehicle should be seen at the edge of the screen.

**Screenshots**  
![cdda](https://user-images.githubusercontent.com/8035743/55297075-d925bf00-542a-11e9-807e-04554e548a5c.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.D-1194-gb45c3cb
 - Graphics version: Tiles

**Comment by golankra123** [comment] 2019-04-02 06:21
I think it might be intended so you will be able to see ahead due to speed.

Still it's sometimes quite annoying. 
And I rather turn that off and zoom out when driving and zoom in when on foot

**Comment by echomirage1** [comment] 2019-04-13 08:57
Before the sidebar overhaul the "shift view while driving" option positioned the vehicle on the edge of the screen. Now the vehicle gets positioned under the sidebar.
If you turn it off, the vehicle will be positioned to the center, Even zoomed out on the fourth zoom setting, you can't see much ahead and have to use the minimap for driving, which is very hit and miss for precise navigation.

**Comment by rumly111** [comment] 2019-04-13 09:51
If the sidebar overlaps the car, you can occasionally bump into bushes and rocks.

**Comment by wapcaplet** [comment] 2021-02-14 03:11
Could not reproduce in 0.E-9603-g42468f6cab. I drove an electric sports car at 132 mph to the east and west with "Auto-shift the view while driving" option enabled. The car remained visible in the main game screen and was not obscured by the sidebar. I tried several screen sizes, and found that when shrinking the screen, the vehicle was automatically re-centered when it otherwise would not fit:

![image](https://user-images.githubusercontent.com/238395/107867378-b8588e00-6e37-11eb-8237-f761c79b335a.png)

This appears to be fixed now.

**Closed by wapcaplet** 2021-02-14 03:11 UTC
Labels: (P5 - Long-term), <Bug>, Info / User Interface
