### ISSUE TITLE
Spoilers - Mine Pedestal thing

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13771] opened 2015-10-17 04:53 UTC
f8ccdfb

In the lowest level of a mine I found, I found a pedestal with a petrified eye on it. I picked it up, and as scripted, the eye screams and dark wyrms everywhere, yadda, but with a problem: Either my samurai butterfly is 2 spooky for them or dark wyrm ai has gone screwy. Is it the Insect pheromones or Terrifying? I mean if I get right next to them, they take a swipe at me before wandering off.

The worms just kinda fiddle around a while and then start digging off to nowhere land. I suppose it's neat I could just follow them and let them dig me a super tunnel, but I'm pretty sure they're supposed to attack me. I was even following them around and yelling and making a bunch of noise.

Edit: Whoops. You might not be able to load my save properly because I've got  Noctifer's bioweapons and survivor mod, and artyom's gun mod, and also a modified stats through skills. I'll link the mod folders in a separate zip in-case it gets in the way of loading.

https://dl.dropbox.com/s/chrj6ib6112rgyz/Pond%20Creek%20Save.zip
https://dl.dropbox.com/s/9ifhkqqsg84a1gp/3rdprtymods.zip

![2spooky](https://cloud.githubusercontent.com/assets/1968809/10557054/0307a6e4-7450-11e5-96d4-8cf445409169.png)

**Comment by Midaychi** [comment] 2015-10-17 17:08
If this is intended behaviour, can you at least set it up so the intended behaviour is ignored during this event? Its a lot harder to kill them when they're going *AWAY*.

**Comment by Midaychi** [comment] 2015-10-31 22:36
I ran into this on another character and yeah it probably has something to do with the mutation traits, cause those wyrms do attack to some degree. HOWEVER, their morale and aggressiveness still seems a bit, low. You can easily wander away from them and watch them forget about you like a toddler.

Also, you can examine the pedestal and take the eye without setting off the event. You have to examine it a second time to trigger the event.

**Comment by illi-kun** [comment] 2016-10-01 11:39
Closing as a dupe of #13310.

**Closed by illi-kun** 2016-10-01 11:39 UTC
Labels: Question
