### ISSUE TITLE
long item descriptions does not show fully

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#20929] opened 2017-05-02 07:35 UTC
an item with an extensive description (i.e., a weapon with several mods) seems to cut off.

example:
http://i.imgur.com/pT70HVX.png

**Comment by somot** [comment] 2017-05-02 07:36
Use Page Up/Down to scroll.

**Comment by Toothspit** [comment] 2017-05-02 07:37
The mod description is cut off, only 3 lines are shown, scrolling won't reveal the rest.

**Comment by Tsunder** [comment] 2017-05-02 07:41
example: 
![image](https://cloud.githubusercontent.com/assets/5103517/25608536/37eb33f8-2ee9-11e7-9075-0b6848f7ae5b.png)

world: [Ravenden.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/969726/Ravenden.zip)

**Comment by Leland** [comment] 2017-05-04 12:44
Duplicate of #19622

**Closed by Leland** 2017-05-04 12:44 UTC
Labels: Information / Interface
