### ISSUE TITLE
Compile Error Cygwin

### ISSUE THREAD

**Issue by karols146** [CleverRaven/Cataclysm-DDA#19283] opened 2016-11-14 09:41 UTC
[error](http://image.prntscr.com/image/458915c62edb4918acb35156ac05b7b7.png)
gg++ 5.4.0
It's something with accumulate is not a member std

**Comment by ChucklesTheBeard** [comment] 2016-11-14 16:28
duplicate of #19278

**Comment by codemime** [comment] 2016-11-15 00:04
Needs to be closed.

**Closed** 2016-11-15 08:57 UTC
