### ISSUE TITLE
A lot of critical errors.

### ISSUE THREAD

**Issue by Evgehas** [CleverRaven/Cataclysm-DDA#65991] opened 2023-06-03 19:59 UTC
### Describe the bug

When starting the game, there are a lot of errors. The report indicates that the error is in the limb code and what else (debug.log I'll attach)

### Attach save file

The file is attached below

### Steps to reproduce

1.Start game
2. Create a world and go to the character

### Expected behavior

This bug prevents the game from loading.

### Screenshots

N/A

### Versions and configuration

OS: Android (huawei y6p)

Game version: cdda-experimental-2023-06-03-0523 [x32] (https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2023-06-03-0523/cdda-android-x32-2023-06-03-0523.apk)

Graphics Version: Tiles

Game Language: English [en]

Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Portal Storms Ignore NPCs [personal_portal_storms],
Magiclysm [magiclysm],
Xedra Evolved [xedra_evolved],
Aftershock [aftershock]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11644121/config.zip)

**Comment by RenechCDDA** [comment] 2023-06-03 20:01
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/65162

**Closed by RenechCDDA** 2023-06-03 20:01 UTC
Labels: (S1 - Need confirmation)
