### ISSUE TITLE
Crash when trying to start game

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14408] opened 2015-12-12 22:22 UTC
Latest experimental version (4029)

Starting the game in any way causes CTD. Hard to not be able to replicate. : P

**Comment by sparr** [comment] 2015-12-12 22:25
duplicate of #14399 #14406

**Closed by sparr** 2015-12-12 22:25 UTC

**Comment by harald921** [comment] 2015-12-12 22:29
@sparr Thought that was smth different since it was from 11h ago, sorry
