### ISSUE TITLE
Foldable vehicles cant be dragged/moved

### ISSUE THREAD

**Issue by systemfelet** [CleverRaven/Cataclysm-DDA#43067] opened 2020-08-20 12:50 UTC
Can't move my foldable shopping cart vehicle, only get "The foldable cart collides with errors in the movement code".
Tried unfolding/folding, loading/emptying even remade one from scratch, nothing works.

# Steps To Reproduce
Make a foldable vehicle out of  2x foldable light frame, folding shopping cart basket and casters , try to drag it.

# Expected behavior
It should be dragable as it was before. Stopped working last night, didnt patch in between, have updated since that to the latest experimental and still not working.

# Screenshots
![CDDA bug](https://user-images.githubusercontent.com/68592466/90760257-e5d9da00-e2e1-11ea-8883-73b7e87cbf6e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5228-g8731f05 [64-bit]
- Graphics Version: Tiles
- Game Language: Deutsch [de]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]

Well, that's a bit wierd that the game language says deutch through the generated game report becuase it's in English o.O

Otherwise, thanks for the wonderfull game, keep the good work up!

**Comment by anothersimulacrum** [comment] 2020-08-20 13:27
Can you upload the save?

**Comment by systemfelet** [comment] 2020-08-20 13:41
> 
> 
> Can you upload the save?

yes ofc, forgot that. 
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5103435/save.zip)

**Comment by wapcaplet** [comment] 2022-01-11 04:05
I could not reproduce this with a folding bicycle or folding shopping cart.

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5147-ge23fd18712 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment] 2022-01-11 19:54
I thought foldable vehicles were restricted to 1 frame; the pic shows sys trying to pull a 2x cart. Did something change betw/ 0.E & now??

I know hexagon did some work w/ folding bikes, maybe he knows something about this.

**Comment by wapcaplet** [comment] 2022-01-11 21:50
3x1 folding bicycles have been in the game for as long as I can remember. I recall 2-3 years ago seeing them collide with "errors in movement code", but have no idea if it's really been fixed or it's just hard to reproduce.

**Comment by hexagonrecursion** [comment] 2022-01-16 16:38
> I know hexagon did some work w/ folding bikes, maybe he knows something about this.

I started it, but then abandoned. AFAIK it never got merged. I might return to it someday.

**Comment by irwiss** [comment] 2022-09-01 00:14
Can't reproduce on e6abe25, after doing the fixes in #60639 moving with the arrows drags the vehicle

**Closed** 2022-09-01 06:12 UTC
Labels: <Bug>, (S1 - Need confirmation), Vehicles
