### ISSUE TITLE
Mag error (pockets)

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#44091] opened 2020-09-10 03:28 UTC
# Describe the bug
Happens with different type of weapon (AR-15, coilgun etc)

 DEBUG    : tried to put an item (mp5mag) count (1) in a container (hk_mp5) that cannot contain it: pocket unacceptable because holster already contains an item

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)
 FILE     : src/item.cpp
 LINE     : 1103

# Steps To Reproduce

attempt to pick up a gun OR attempt to highlight a gun in 'V'iew menu

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5833-g13fd30e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Survivor harness may (or may not) be related to that

**Comment by wapcaplet** [comment] 2020-09-18 19:54
Duplicate of #44158

**Closed** 2020-09-18 19:56 UTC
Labels: (S3 - Duplicate)
