### ISSUE TITLE
Bionic armor useless?

### ISSUE THREAD

**Issue by cellxiecao** [CleverRaven/Cataclysm-DDA#10827] opened 2015-01-11 09:03 UTC
Currently I'm playing 0.B and I find that installing Alloy Plating CBMs doesn't reduce damage received by player at all.
Is this a bug?

**Comment by BevapDin** [comment] 2015-01-11 16:15
Maybe a duplicate of #10297?

**Closed** 2015-01-11 22:12 UTC
Labels: Duplicate
