### ISSUE TITLE
The current health system is unreasonably volatile

### ISSUE THREAD

**Issue by overlord624** [CleverRaven/Cataclysm-DDA#30586] opened 2019-05-17 21:34 UTC
**Is your feature request related to a problem? Please describe.**  
It's harder to eat healthy in Cataclysm than in real life. Unless you eat on a diet suitable for a professional athlete, you will tend to end up somewhat unhealthy rather quickly.

Realistically, an unbalanced diet can take years to take effect, and even in the most extreme cases, it takes at least several months until health issues begin to emerge since the body can synthesize most of the things it needs to sustain itself in the short term.

In contrast, Cataclysm health can be tanked until you start getting warning messages in mere days and recovered just as quickly. 

We are expected to use real-world knowledge of "unhealthy" food, but many of the foods the game considers unhealthy are realistically not inherently bad for one's health if supplemented with adequate nutrients, where as others legitimately impact body biochemistry but only in the very long term. Very few foods will result in observable health effects in days if over-consumed.

For example, most sugary foods are not bad by themselves. They lead to obesity because of their extreme energy density and because most people who have access to them are at risk of obesity due to sedentary lifestyle, but that is the only real downside. If you watch your calorie and nutrient intake, you can stay healthy even if chocolate is your primary source of calories.

On the other extreme, fatty meats such as pork are bad for the blood vessels and can lead to heart problems, but the effect takes decades to manifest without compounding factors such as old age.

**Describe the solution you'd like**  
Health should normally change very slowly due to diet alone and tend to gravitate towards "above average". Most cataclysm characters lead a very active healthy lifestyle which would result in great physical health IRL.

Drastic changes should be reserved for impactful factors such as toxins, radiation, organ damage and diseases. Diet should be far more impactful on characters recovering from low health, but have marginal effects beyond a certain point.

**Describe alternatives you've considered**  
Feedback for which foods the game considers unhealthy would be a reasonable and easily implementable alternative to alleviate the discrepancies between developer and user expectations.

An extra line in the examine menu that says "This food is (great/good/bad/terrible) for your health" would be a welcome addition.

**Comment by kevingranade** [comment] 2019-05-17 22:17
Please outline the diet your character is following and the symptoms caused by it that are unreasonable.

**Comment by Dacendeth** [comment] 2019-05-18 02:01
It would be cool if with high enough cooking and/or survival it let you identify the healthiness of food.

**Comment by Rail-Runner** [comment] 2019-05-18 03:53
Maybe it'd be best to make healthiness use vitamins system, with there being "sugars" that can lead to obesity/other health problems if over-consumed, and whatever other things junk food often has? Healthy food would have some kind of vitamin named as "others" or similar, to reflect all the other stuff that results in better health if consumed, including dietary fibers or whatever.

**Comment by kevingranade** [comment] 2019-05-18 04:07
Random observations and suggestions about the health system are off topic and will be ignored.
If you have a suggestion, write it up in an issue, but I'm going to be asking the same question there, which is what is the specific scenario and what is the specific bad outcome.

**Comment by overlord624** [comment] 2019-05-22 12:25
@kevingranade 
I believe I've managed to isolate the circumstances I'm experiencing and it seem to be partially related to a bug.

But to answer your questions first, I've noticed this with a wide number of characters. I don't maintain a specific diet per say, but early game I tend to eat long-lasting food that's commonly found in houses, as well as meat from non-zombified animals. I avoid really unhealthy food (eg cracklings), excessive alcohol (never seen alcohol addiction status), recreational drugs, unclean water and other obviously unhealthy stuff.

The messages I'm referring to are low health warnings you get when your character wakes up. I don't exactly remember the exact text since I haven't played recently, but usually it's something along the lines of "you need to eat better" or "it's hard to get out of bed".

In order to try to replicate this issue, I tried creating a test character that has a similar diet as a character I've had before. I started lab challenge character with 8 in all stats, maxed skills, the "no monsters" mod and only the self-ware trait.

I then used a gamma globulin shot on the first day, scrounged around until I found a bunch of food (mostly from emptying a couple vending machines) and spend the next few days skipping time eating/drinking/sleeping when hungry/thirsty/tired respectively. Most of the quench the character got was from various soft drinks and most of the calories were random candies and such (I basically ate the first thing on the list until reaching about 600-800 calories per meal)

At midnight each day, I recorded their health values (from the debug menu) and the results are as follows:

day/health/health modifier
1/79/49
2/10/10
3/5/5
4/4/4
5/-10/-10
6/-7/-7

On day 7, at 22:18 the character woke with the message "You feel cruddy. Maybe you should consider eating a bit healthier" and had a health value of -10 right after waking up.

It seems that the game tends to aggressively clamp health values to the [-10,10] range and being at -10 is enough for the game to start complaining about bad health.

Note that I'm running a somewhat outdated version of the experimental branch the title screen says 0.D-2935-g4da9158 but that doesn't seem to be accurate because I downloaded the latest experimental about 2 weeks ago.

**Comment by kevingranade** [comment] 2019-05-22 15:44
That sounds like it's working precisely as intended, what do you expect to happen in that scenario?

**Comment by I-am-Erk** [comment] 2019-05-22 16:14
I think I'll step in and say from a medical perspective: if you spend a week eating candy and drinking soft drinks as your main way to get calories, you're going to feel cruddy. If anything that's not volatile *enough*.

Imma go ahead and close this, I have no objection if someone decides to overrule that.

**Closed by I-am-Erk** 2019-05-22 16:14 UTC
Labels: (S1 - Need confirmation), Game: Balance

**Comment by overlord624** [comment] 2019-05-23 02:58
That's not how health works IRL. Physical health is largely measure of organ health (cardiovascular system, lungs, kidneys, etc) and physical robustness (bone density, muscularity and such). A reasonably healthy person will not end up identical to someone who has lived as a total slob their entire life from 7 days of bad diet (and vice-versa).

You might "feel" slightly worse for wear, but the actual effect of a poor lifestyle in a week would be marginal at best. From a "medical perspective" what exactly would change to have such dramatic effects? Muscle mass will barely shift, bone density will remain, the overall heart rate will still be the same... all physical indicators of physical health will remain identical and testing physical performance will indicate as much.

**Comment by I-am-Erk** [comment] 2019-05-23 05:37
What dramatic effects do you think result from having a slightly lower health stat in game?

**Comment by overlord624** [comment] 2019-05-23 13:33
@I-am-Erk The dramatic change I am referring to is the shift in health. Physical health is neither easy to gain, nor easy to lose (baring disease or other drastic circumstances). In the current system it's stupidly easy to lose as demonstrated. You cannot go form very healthy to slightly unhealthy be eating poorly for 5 days.

The game seems to just subtract "health" from you when you consume "bad" foods, which is absolutely not how it works in reality. The reason sugary foods are bad for example is because they displace healthy nutrients and are easy to over-consume. Missing most nutrients in the short term is not fantastic for your health, but it's hardly a big deal either. As the game is right now, it's literally harder to eat healthy than it is IRL.

**Comment by I-am-Erk** [comment] 2019-05-23 13:38
The game system is working as intended. If you eat junky food you feel crappy. Having a low health stat doesn't mean you're obese and have diabetes, it means you feel kinda crappy and have a slightly elevated chance of minor bad things happening because you're not eating well. Your misinterpretation of what the word means, especially given that the word isn't even displayed to the player, is pretty irrelevant.

**Comment by overlord624** [comment] 2019-05-23 14:55
> Your misinterpretation of what the word means, especially given that the word isn't even displayed to the player, is pretty irrelevant.

It is displayed in the game, the Self-Aware trait will report the exact value and it explicitly calls it "health".

Anyway, it's abundantly clear that this is unproductive, so I'm going to drop the issue. Thank you for your time.

**Comment by Night-Pryanik** [comment] 2019-05-23 15:03
> It is displayed in the game, the Self-Aware trait will report the exact value and it explicitly calls it "health".

It's not. The numbers displayed by Self-Aware trait are "Health Points", not "Health". The description of the trait is confusing though. You can't see exact _health_ value anywhere in normal game except for debug menu.

**Comment by overlord624** [comment] 2019-05-23 15:06
@Night-Pryanik Self-Aware can be activated from the mutations menu and it will display the same health value you see in the debug screen.

**Comment by Night-Pryanik** [comment] 2019-05-23 15:57
Ok, I was wrong.
