### ISSUE TITLE
Attempting to travel to a place on the map that doesn't have an already-explored route freezes the game

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61991] opened 2022-10-29 05:10 UTC
### Describe the bug

When you have a revealed location on a map that is surrounded by black tiles (such as if you read a map that gave you a location without a road leading to it) and attempt to [w] autotravel to it the game will lock up for as much as multiple minutes. It doesn't appear to crash.

### Steps to reproduce

1. Spawn in an "urban explorer's map" on a fresh world.
2. attempt to autotravel to a derelict property on the map.
3. observe the lockup.

### Expected behavior

The game shouldn't lock up when doing this.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: deff4fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by AcidAntOnAMinefield** [comment] 2022-10-29 06:22
The game randomly locks up in other occasions. 

I've had said lockups happen during crafting, sometimes "dragging"/moving items along the floor, interacting with furniture, even during reading sessions.

**Comment by alef** [comment] 2022-11-19 17:31
Can't reproduce with 25a0ca0fa7b495f1bdbffd5ac15e172b03b92128 , here is my save:
[DebugWorld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10047605/DebugWorld.zip)

First, this shows it can plan to a nearby road end:
![choose destination](https://user-images.githubusercontent.com/3899581/202863794-a8f0d2fd-72f5-4877-8d95-89c31f26f8a9.png)

Second, this screenshot shows it can not plan to the derelict property:
![derelict property](https://user-images.githubusercontent.com/3899581/202863812-8770ed22-6312-427f-936d-d6c43230dbc2.png)
There is no lockup. It has removed the planned travel an I can scroll the map around.

**Closed** 2023-08-19 16:38 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
