### ISSUE TITLE
Zombie burner explouding. Bug or feature?

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59054] opened 2022-07-08 02:10 UTC
### Describe the bug

 After [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139)
Killing zombie burner cause them to exlpode

I think, problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/58980 
But I didnt find anything in this pr about adding to zombie burner explouding effects
And now its very hard to loot military objects, becouse of exlouding zombie burners, which will burn all there and nearby loot into ash
And I am playing without magiclysm

Text of crash. I will also add crash and debug log

DEBUG    : ERROR: Fireball Death has invalid spell effect.

 FUNCTION : void spell_effect::none(const spell&, Creature&, const tripoint&)
 FILE     : src/magic_spell_effect.cpp
 LINE     : 1249
 VERSION  : 4608ba2

### Steps to reproduce

Update game to [Cataclysm-DDA experimental build 2022-07-07-0033](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0033)
Spawn zombie burner
Kill him
See him unexplouding
Update game to [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139)
Spawn zombie burner
Kill him
See crash text and explouding of the zombie

### Expected behavior

If its not new feature - I wanted to see zombie burner without explouding
If it is new feature - I dont want to see crash text, and its needed related pr

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 4608ba2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9068339/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9068341/debug.log)

**Comment by sonphantrung** [comment] 2022-07-08 03:08
Yes, zombie burners exploding is, in fact, intended

**Comment by Maleclypse** [comment] 2022-07-08 03:15
My biggest question is what could possibly make you think the PR you linked was the cause?

**Comment by hexagonrecursion** [comment] 2022-07-08 03:34
/confirmed zombie burner dying triggers an error:

 DEBUG    : ERROR: Fireball Death has invalid spell effect.

 FUNCTION : `void spell_effect::none(const spell&, Creature&, const tripoint&)`
 FILE     : src/magic_spell_effect.cpp
 LINE     : 1249
 VERSION  : 6502158

Note: just lure the zombies away from the valuable loot before killing them. They are slower than you and have no ranged attacks.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by KHeket** [comment] 2022-07-08 03:50
> My biggest question is what could possibly make you think the PR you linked was the cause?

Becouse of the text of crash and description of https://github.com/CleverRaven/Cataclysm-DDA/pull/58980 pr

> Yes, zombie burners exploding is, in fact, intended

But they didnt ever exploding before [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139)
And the https://github.com/CleverRaven/Cataclysm-DDA/pull/58980 pr in only about magiclysm. And I found info in https://github.com/CleverRaven/Cataclysm-DDA/pull/23729 that they have 10% to explode, but it looks like, there is 50% or 100%, bit I cant check, is percent right or not. But if it is ok, ok

**Comment by Night-Pryanik** [comment] 2022-07-08 03:53
Zombie burners were exploding more than 4 years already, since #23729. And yes, their explosions are intended.

**Comment by KHeket** [comment] 2022-07-08 03:59
> Zombie burners were exploding more than 4 years already, since #23729. And yes, their explosions are intended.

I am lucky as hell, becouse I didnt saw them explouding for 1+ year 😎

**Comment by Maleclypse** [comment] 2022-07-08 04:00
> > My biggest question is what could possibly make you think the PR you linked was the cause?
> 
> Becouse of the text of crash and description of #58980 pr
> 
> > Yes, zombie burners exploding is, in fact, intended
> 
> But they didnt ever exploding before [Cataclysm-DDA experimental build 2022-07-07-0139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-07-0139) And the #58980 pr in only about magiclysm. And I found info in #23729 that they have 10% to explode, but it looks like, there is 50% or 100%, bit I cant check, is percent right or not. But if it is ok, ok

Are you intending to link to a different PR?  Because the PR you are linking is titled "magiclysm: fix everburning torch flags" and there is nothing in it remotely touch zombie burners.

**Comment by KHeket** [comment] 2022-07-08 04:06
> Are you intending to link to a different PR? Because the PR you are linking is titled "magiclysm: fix everburning torch flags" and there is nothing in it remotely touching zombie burners.

In https://github.com/CleverRaven/Cataclysm-DDA/issues/59054#issuecomment-1178519841 in the beging is text

> it has a 10 percent chance to explode in a fireball on its death;

So I think, zombie burners casts fireball on death, and thats causing this crash related to linked pr, or I am wrong?

**Comment by Maleclypse** [comment] 2022-07-08 04:10
> > Are you intending to link to a different PR? Because the PR you are linking is titled "magiclysm: fix everburning torch flags" and there is nothing in it remotely touching zombie burners.
> 
> In [#59054 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/issues/59054#issuecomment-1178519841) in the beging is text
> 
> > it has a 10 percent chance to explode in a fireball on its death;
> 
> So I think, zombie burners casts fireball on death, and thats causing this crash related to linked pr, or am I wrong?

You are wrong. There is absolutely nothing related to your bug in the linked PR.

**Comment by Maleclypse** [comment] 2022-07-08 04:11
The zombie burner does cast a spell on death though because almost all vanilla death effects and many monster attacks are using the spell infrastructure but hidden so it’s only clear they are using spells when an error message happens.

**Comment by hexagonrecursion** [comment] 2022-07-08 06:02
There is still a debug assertion. It should be fixed.

**Comment by Night-Pryanik** [comment] 2022-07-09 08:42
This debug message is called because zombie burner has `death_fireball` effect on death. `death_fireball` has `effect`: `none`. `none` effect prints debug message: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/b3c3acda8dbcb5c0bb482ab1c7ed6f3af2da97f1/src/magic_spell_effect.cpp#L1247-L1250

We can easily resolve this bug by changing effect to something safe, like `noise`. No debug message, death effect works almost like it should. However, there are a bunch of other bugs with this:
- instead of exploding with 10% chance, zombie burner explodes every time;
![изображение](https://user-images.githubusercontent.com/11132525/178098585-cff21220-28af-481d-badd-19d01a4255d0.png)
![изображение](https://user-images.githubusercontent.com/11132525/178098610-b4968f86-d5e8-43bd-93e5-d52f4302388a.png)

- zombie burner dies twice for some reason. Short testing show that removing `death_function` makes him die once.
![изображение](https://user-images.githubusercontent.com/11132525/178098479-cb379eb3-c497-4e3b-bdaf-0c5ffed81186.png)

- Not directly related with zombie burner, but I was somehow able to hit it in `test weakpoint 1`.
![изображение](https://user-images.githubusercontent.com/11132525/178098503-d31e59ad-10f3-43e0-9717-afa732ba519d.png)

**Comment by KHeket** [comment] 2022-07-15 15:01
Zomborgs exploding with this crash text too, and I dont know, should they explode every time or not

**Comment by Inglonias** [comment] 2022-07-17 14:13
Somehow, the wonder flag is setting off all of the spell's effects, rather than just one like it's supposed to. Even when I set the damage fields correctly, this spell is still misbehaving. I'm compiling as we speak to try to diagnose what's going wrong here.

There's only one other artifact that exists with the WONDER flag right now, and its in a legacy file so I don't think we use it, so this bug got missed.

**Closed** 2022-07-19 02:34 UTC
Labels: <Bug>, (S2 - Confirmed), Monsters, Mechanics: Enchantments / Spells
