### ISSUE TITLE
Dropping golf bag on a pile of items made me crash over 5 times

### ISSUE THREAD

**Issue by kainvastro** [CleverRaven/Cataclysm-DDA#50516] opened 2021-08-06 05:02 UTC
### Describe the bug

Sorry this is my first ever bug report, i never found any actual crashes on the game but many red messages
Im not sure if i lost items but i was somehow kind able to replicate my problem, dropping the empty golf bag in a pile of items kept making me crash over and over.

(my separate pile of items had only metal arrows after the problem was gone, i suspect something vanished..)

### Steps To Reproduce

(sorry if its not accurate i wasnt able to get the details of the crash)
1:coming back to 2nd floor base
2: unloading golf bag (saving was still ok until here)
3:drop golf bag on pile of items 
4:try to save i was crashing

### Expected behavior

i expected to drop my bags into a pile of items and be able to get lighter weight with my runner pack, but i kept crashing every time i dumped the golf bag (and maybe duffel bag) into the pile of items

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: c850e91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

OH YEAH i found the one crash after i was dropping things around and reloading
until i stopped getting the red message and the game was ok-ish?
i didnt know how i made the red message stop on loading :/ but i found it at least!
the last two lines is specifically it. 

01:43:52.033 : Starting log.
01:43:52.033 INFO : Cataclysm DDA version c850e91
01:43:52.037 INFO : [main] C locale set to C
01:43:52.037 INFO : [main] C++ locale set to C
01:43:52.037 INFO : SDL version used during compile is 2.0.14
01:43:52.037 INFO : SDL version used during linking and in runtime is 2.0.14
01:43:52.094 INFO : Number of render drivers on your system: 5
01:43:52.094 INFO : Render driver: 0/direct3d
01:43:52.094 INFO : Render driver: 1/direct3d11
01:43:52.094 INFO : Render driver: 2/opengl
01:43:52.094 INFO : Render driver: 3/opengles2
01:43:52.094 INFO : Render driver: 4/software
01:43:52.096 INFO : [options] C locale set to C
01:43:52.096 INFO : [options] C++ locale set to C
01:43:52.096 INFO : Setting language to: 'en'
01:43:52.097 INFO : Language is set to: 'en'
01:43:52.097 INFO : [translations] C locale set to Portuguese_Brazil.1252
01:43:52.097 INFO : [translations] C++ locale set to C
01:43:52.185 INFO : Active renderer: 1/direct3d11
01:43:52.280 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
01:43:53.213 INFO : Setting language to: 'en'
01:43:53.213 INFO : Language is set to: 'en'
01:43:53.213 INFO : [translations] C locale set to Portuguese_Brazil.1252
01:43:53.213 INFO : [translations] C++ locale set to C
01:43:53.358 WARNING : opendir [./mods/] failed with "No such file or directory".
01:43:57.349 WARNING : opendir [./save/Manor Creek/mods] failed with "No such file or directory".
01:44:02.603 INFO : Loaded tileset: UltimateCataclysm
01:44:05.191 ERROR : src/item_location.cpp:794 [void item_location::deserialize(JsonIn&)] contents index greater than contents size
01:44:26.231 : Log shutdown.

**Comment by kainvastro** [comment] 2021-08-06 05:03
I am sorry i couldnt replicate perfectly the problem but at least i could find the red message.

**Comment by ToxiClay** [comment] 2021-08-06 06:51
Could you compress your save directory into a ZIP file and attach it?

**Comment by satheon49** [comment] 2021-08-06 20:04
Do you by any chance use a bow, crossbow or sling and have arrows/bolts/rocks in your golf bag?

**Comment by kainvastro** [comment] 2021-08-07 12:13
> 
> 
> Do you by any chance use a bow, crossbow or sling and have arrows/bolts/rocks in your golf bag?

yes i do, that golf bag was supposed to hold many arrows and some 3 tools
i also had a quiver with arrows. metal arrows and metal bolts



> 
> 
> Could you compress your save directory into a ZIP file and attach it?
(this reply is not letting me upload it huh, weird)
yes , by the way i wanted to point out, if i dropped out all my armor on the floor and pressed to quick save, it would also crash as well!!!
i was extremely hot so i had to just put-off to my inventory and bear with the weight :/
I was able to drop that pile of warm clothes on the car's trunk and there was no problem, but this makes the pile of items even more suspicious

**Comment by satheon49** [comment] 2021-08-07 12:23
I am confident that #50525 fixes your issue. I am not sure it is already contained in the newest experimental but the PR was merged about 5 hours ago.

**Comment by kainvastro** [comment] 2021-08-07 12:27
Yeap i tried to send a zip of a old file here, it works (3mb compressed zip)
but when i send the one save that had the glitch it just says "is not included in the list" but its 30mb compressed :(
![image](https://user-images.githubusercontent.com/88525396/128600083-11c4d554-80e0-4b3c-b128-743847d3b752.png)

**Comment by RenechCDDA** [comment] 2023-07-01 13:15
Can't reproduce on https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

Please feel free to comment here or open a new issue if this continues to be a problem.

**Closed by RenechCDDA** 2023-07-01 13:15 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation), Inventory / AIM / Zones, Items: Containers
