### ISSUE TITLE
Zombie spawn/teleport in the basement.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#35274] opened 2019-11-03 02:54 UTC
I was running away from zombies, got in the basement in one of the houses and decided to get some sleep. The weird thing that I noticed is that occasionally a zombie would appear near me, even without breaking any doors.

![zombies](https://user-images.githubusercontent.com/430076/68079697-338a6200-fdf6-11e9-9ff1-d47799af56e3.png)

And this happens even without sleeping, just waiting. Seems like a bug, because zombie should not just appear out of thin air near player in a locked room without breaking doors.

I am playing the latest git pull at the time of writing this, with the following changes: I reverted the the patch that removed the tileset, I reverted the "sepia tint" patch, that makes unseeable tiles look brighter.

**Comment by EvgenijM86** [comment] 2019-11-03 03:10
When sleeping in upper-left room near stairs no zombie is spawned.

**Comment by anothersimulacrum** [comment] 2019-11-03 03:14
This is occurring because on the map above, the stairs are above the room you were trying to sleep in.

**Comment by EvgenijM86** [comment] 2019-11-03 03:19
Seems like it. It is as if zombies are using some invisible stairs that leads to my room, instead of using the stairs that I see in the house.

**Comment by anothersimulacrum** [comment] 2019-11-03 03:24
It's a known bug. This issue is very likely duplicate of another issue that has already been filed.
Basically, what happens is that when the player goes down the stairs, the game searches the level below for stairs, then places the player on those. But this does not occur for zombies, for whatever reason.

**Comment by KorGgenT** [comment] 2019-11-03 12:58
see #31955

**Comment by KorGgenT** [comment] 2019-11-09 15:39
this should be fixed now. please repoen if the bug still exists.

**Closed by KorGgenT** 2019-11-09 15:39 UTC
Labels: <Bug>, Monsters, Z-levels
