### ISSUE TITLE
Crash when setting an option with query in MSYS2 builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20624] opened 2017-03-22 09:14 UTC
* Load a game
* Open world options
* Select NPC spawn rate
* Type in `100`
* Confirm with enter
* Crash

**Comment by AMurkin** [comment] 2017-03-22 13:44
Can't reproduce. win x64 build 6347

**Comment by Toothspit** [comment] 2017-03-22 16:13
Can't reproduce on Linux x64 tiles 0.C-21756-gc7f65b7532, either.

**Comment by Coolthulhu** [comment] 2017-03-22 17:43
Could be compiler dependent then. I'll change the description.

**Comment by Leland** [comment] 2018-02-20 21:26
Seems to be a duplicate of #20927, which was fixed by #21742

Closing, but @Coolthulhu obviously feel free to reopen if this is still an issue on your env

**Closed by Leland** 2018-02-20 21:26 UTC
Labels: Build, Crash / Freeze
