### ISSUE TITLE
mini reactors

### ISSUE THREAD

**Issue by kingcet** [CleverRaven/Cataclysm-DDA#40199] opened 2020-05-05 17:46 UTC
# Describe the bug
i removed a mini reactor from a car and this happened
![Capture](https://user-images.githubusercontent.com/54482501/81097667-3580cb00-8ed6-11ea-9cb5-3f0a87e04399.PNG)

it created the above item and dropped it, it also had a same or similar amount of cells inside the reactor. i was also un able to put the minireactor into a different car

# Steps To Reproduce
1. take a reactor out of a car
2. walk around
3. this happened

# Screenshots
![Capture](https://user-images.githubusercontent.com/54482501/81097894-84c6fb80-8ed6-11ea-9270-64a4d39b8d5a.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-1783-g3ba1852 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    More Survivor Stuff [more_survivor_stuff],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

**Comment by int-ua** [comment] 2021-01-15 01:13
Title suggestion: 
Removing mini-reactor from a car creates plutonium cell item with negative charges.

**Comment by int-ua** [comment] 2021-01-15 01:15
Cannot reproduce on latest experimental.

**Comment by OliveChukar** [comment] 2021-01-23 18:54
Tested in 0.E-9140-gedd42fc-dirty with mods shown in report except for more_survivor_stuff. Spawned every type of vehicle with "atomic" in the name.  Removed mini-reactors from all of them and had no problems. Test included both perfect condition reactors and damaged ones that were leaking plutonium slurry. Was also able to reinstall reactors.

**Comment by anothersimulacrum** [comment] 2021-01-23 19:01
Closing as not reproducible.

**Closed by anothersimulacrum** 2021-01-23 19:01 UTC
Labels: (S1 - Need confirmation), Vehicles
