### ISSUE TITLE
Tentacle mutation description discrepancy

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#31876] opened 2019-06-26 13:14 UTC
# Describe the bug
With all those Yuggs around with the little older builds my current character got some mutations. I noticed, that while the Tentacle Arms mutations says I'll have permanent hand encumberance of 30, I actually have 0.

# Steps To Reproduce
Get the mutation and look at @ 

# Expected behavior
My stats should match with the description.

# Screenshots
![image](https://user-images.githubusercontent.com/19891532/60182625-f2b98580-9824-11e9-907f-f4f57515b14a.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4976-ge986eb2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Aftershock [aftershock],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Filthy Clothing [filthy_morale],
    StatsThroughSkills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Sleep Deprivation [sleepdeprivation],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS]
]

**Comment by anothersimulacrum** [comment] 2019-06-26 16:07
Duplicate of #23928

**Closed** 2019-06-26 16:11 UTC
Labels: (S3 - Duplicate)
