### ISSUE TITLE
Disassembling ammo in bulk doesn't yield all of its components

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#55970] opened 2022-03-09 17:16 UTC
### Describe the bug

it's inconsistent with the quantities that are supposed to disassemble

### Steps to reproduce

Deconstruct more than 50 or more units of ammo

check the product

### Expected behavior

To make the correct quantities of components.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1499 (21H2)
- Game Version: 48260d3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    MST Extra [MST_Extra],
    Crazy Cataclysm [crazy_cataclysm],
    Deadly Zombie Virus [deadly_bites],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Caches [P_Caches],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment] 2022-03-10 00:49
Prob a dupe of #53955.

**Comment by haveric** [comment] 2022-03-10 04:52
Can you specify what ammos you have seen this with?

**Comment by Aeiouuu01234** [comment] 2022-03-10 05:33
9x19, 223, 45, 44, 308, all the common I think, except 22 if I remember correctly

**Comment by oosyrag** [comment] 2022-03-10 08:45
Closing as dupe.

**Closed by oosyrag** 2022-03-10 08:45 UTC
Labels: (S3 - Duplicate)
