### ISSUE TITLE
Refugee center need improvement

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20880] opened 2017-04-21 13:31 UTC
1. They have survived this long. so should be smart enough that they should all be using silenced weapons and not weapons that bring a zombie horde to the shelter.

2. They should all have at least the equivalent of leather body armor, if not better.

3. They should have built some pits, and other traps near the windows.

4. etc ...

**Comment by AMurkin** [comment] 2017-04-21 13:45
+3 and minefields )

**Comment by Night-Pryanik** [comment] 2017-04-22 04:35
IIRC it's just 5 days after the Cataclysm by default, according to the lore.

**Comment by DangerNoodle** [comment] 2017-04-22 06:10
Deep pits in appropriate places might be an adequate improvement and add to the rudimentary fortifications already present, but more extensive changes would be more for balance purposes.

**Comment by pisskop** [comment] 2017-04-22 15:57
tried this after a fashion.  was rejected.

mayhap youll have more success

**Comment by kevingranade** [comment] 2017-04-22 17:03
@Night-Pryanik hit the nail on the head here.  The problem is these centers need to be consistent at day one and also at day 100.
What I'd like to target right now is the amount of defenses an average group of people would come up with in a week, and then assume they lead a somewhat blessed existence where they aren't fighting off hordes because they're quiet and out of the way.
If/when we have a system in place for the settlement developing over time, we can have them start out naive, but put better defensive measures in place over time.

Point for point:
Silenced weapons are out of the question, they're not exactly common (vanishingly rare in fact), and the whole point of the shelter is they're on the defensive and mostly reliant on rare roaming survivors for scavenged goods.
Likewise armor, the guards would prioritize decent armor, but the rest would essentially wear street clothes.
More traps are totally justified, feel free to add those.

Please keep in mind, there's a difference between what is desireable for a player and what is justified by the scenario.

**Comment by Lazasar** [comment] 2017-04-22 17:39
Ok, when I said "silenced weapons" I meant "Silent weapons" like crossbows and bows, and in rare situations, pneumatic rifles like what the player can create.

**Comment by DangerNoodle** [comment] 2017-04-22 17:54
> What I'd like to target right now is the amount of defenses an average group of people would come up with in a week, and then assume they lead a somewhat blessed existence where they aren't fighting off hordes because they're quiet and out of the way.

I would reason that, given those constraints, pits around the windows might be the only major undertaking they could implement in a reasonable timeframe, along with boarding up windows as they already do. A player can manage around four or five deep pits in a day of work if they have supplies and no other tasks to deal with. So with more manpower, and the stated assumption that they only have a week, a few carefully placed pits to augment weak spots like windows might be doable, at least in game terms.

In real life terms, I would have to consult military engineering field manuals to see what their stated man-hour estimates are for basic defensive fighting positions and other earthworks.

**Comment by Zireael07** [comment] 2017-04-22 18:22
Crossbows and bows (handmade) are reasonable additions to whatever non-silenced guns the New England residents had on hand when disaster hit. Pneumatic rifle is less so, if we assume they had a week.

Pits in front of doors/windows are reasonable too.

Can we have a base for day 1 and then a base for, let's say day 100? (Take day 1 version and add better guns and more traps?)

**Comment by DangerNoodle** [comment] 2017-04-22 18:29
Self bows and basic spears might work as well. Or a larger usage of pipe rifles.

**Comment by pisskop** [comment] 2017-04-22 18:50
homemade guns would be practical for a few at best.

most would simply be better if they were coded to use melee if the threat was under a certain level.  be it xnumbernof critters or a combined difficulty of x or if melee*skillinmeleeaverage < monsterpresence.


pneumatic rifles?  1, sure.  all of them? no

**Comment by BorkBorkGoesTheCode** [comment] 2017-04-23 00:17
Would a few national guardsmen be plausible as guards?

**Comment by kevingranade** [comment] 2017-04-23 01:04
National guardsmen with depleted ammo, sure, with full kit, nope.

**Comment by Leland** [comment] 2018-02-19 23:50
No discussion in about a year, closing. If there's still interest in discussion/providing a fix, please ping me and will reopen. Alternatively, feel free to make a new issue to help resuscitate discussion.

**Closed by Leland** 2018-02-19 23:50 UTC
Labels: Easy-fix, Enhancement, JSON, NPC
