### ISSUE TITLE
Crafting with UPS soldering iron errors out but still works

### ISSUE THREAD

**Issue by saneman226** [CleverRaven/Cataclysm-DDA#19491] opened 2016-11-27 04:46 UTC
I have a UPS powered soldering iron and when I go to craft with it in my inventory, it does create the item and it does use the power required from the soldering iron, but just points out a senseless error even though everything worked:
![capture](https://cloud.githubusercontent.com/assets/12336871/20645651/7273096a-b432-11e6-8f1e-0d07b84a587e.PNG)

Edit: Literally everything I have crafted or disassembled so far using the UPS soldering iron has given this message but still properly took the power correctly and yielded the end product just fine.
Build 5941

**Comment by BrettDong** [comment] 2016-11-27 05:10
Also encounters this when installing a new light frame on a vehicle with UPS welder.

**Comment by saneman226** [comment] 2016-11-27 06:35
Could perhaps be related to the UPS makeshift welder issue #19461

**Comment by BrettDong** [comment] 2016-12-02 13:19
@illi-kun This is in fact a duplicate of an issue reported earlier #17932 .

**Closed** 2016-12-02 13:38 UTC
