### ISSUE TITLE
Boats don't exist when docked

### ISSUE THREAD

**Issue by agatharchides** [CleverRaven/Cataclysm-DDA#49983] opened 2021-07-16 17:46 UTC
### Describe the bug

When a boat the player is not driving covers shallow water tiles the game thinks you are walking on the underlying tile, not the boat. If you step onto deep water covered by your boat, you will sink. If you step in the shallow water, you get wet. This does not occur if the whole boat is over deep water, where you can walk anywhere on the boat, not on the deep water tiles. 

This is particularly problematic if you park the boat with the captain's chair over deep water as you end up having to swim through your own boat. #

### Steps To Reproduce

1. Make a boat. 
2. Sail it so it is over deep and shallow water. 
3. Try to walk onto a part of the boat covered by deep water. 

### Expected behavior

When walking in a boat, one should walk on the boat, not the underlying water. A small wetness penalty in a kayak or bare boat hull is maybe fine, I've spent time in them to know it is hard to stay totally dry in one. Having to swim out to the captain's chair through my own motorboat is a bit much though. 

### Screenshots

![image](https://user-images.githubusercontent.com/36541964/125988342-bf34d020-5d50-4556-a02c-dfc65b92a280.png)

### Versions and configuration

- OS: Windows 10
- Game Version: fff825c (tiles)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA

**Comment by actual-nh** [comment] 2021-07-16 19:10
This appears to be a duplicate of #48834 and/or #48011.

**Comment by wapcaplet** [comment] 2022-01-16 05:43
Agreed, closing as duplicate.

**Closed by wapcaplet** 2022-01-16 05:43 UTC
Labels: <Bug>, (S3 - Duplicate), Z-levels, Vehicles
