### ISSUE TITLE
Huge Slow Down :(

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#14068] opened 2015-11-17 16:58 UTC
Been playing this game for a while best I have ever done so far.

its realy slow now when i press move it takes ages to react :(

version 3915 tryed both 32 and 64 (normaly use 64bit)
I use mods probably best for me to upload my whole CDDa folder.
I have tryed lots of things 

Killing blobs but its still slow so cant be that.
Funny thing is if I try to use the remove all monsters near the ranch the game crashes so might be some thing up near there causing issue.

It did seem to start after I choppped a tree down and placed the 2x4`s near that bloke in the ranch (mission)

I would love to hear back about this issue

https://www.sendspace.com/file/8frtjm

**Comment by stk2008** [comment] 2015-11-17 18:29
Hmmm ok 

http://i.imgur.com/y3eu3aA.png

if I go to this location in the reality bubble there is a crap ton of blobs.

If I use the remove monster command game crashes EVERY time :( Nooooooo so this save is now unplayable :(.

help please :)

**Comment by Zireael07** [comment] 2015-11-17 18:40
Do you have z-levels on? Any slime pits nearby? 
Did you play this save before @Coolthulhu fixed that bug with relocation placing monsters on wrong z-level?

**Comment by stk2008** [comment] 2015-11-17 18:42
yep Z levels are on
yes slime pits are near by
this save was from today I have been playing it ffom about 9am this morning till about 2:30pm today (IRL)

**Comment by stk2008** [comment] 2015-11-17 18:44
My full CDDA folder is inc in original post its tiles version for windows.

It has every thing setup basicaly ready to go.

I was going to upload just the save but that alone is 200MB and I use mods etc so thought it would just be easyer to upload my whole CDDA folder :)

**Comment by DanmakuDan** [comment] 2015-11-17 20:03
Ha, when the remove monster command kills the blobs, it's triggering their split-on-death function also. There's about 14000 blobs underground currently in your local area, potentially inflating to a count of 50000+ or so when they're done dying from the debug command. I think the `monattack::formblob` special isn't checking for valid locations.

![wat](https://cloud.githubusercontent.com/assets/9610892/11223082/ae240ef4-8d33-11e5-8aef-602e3c0483e9.png)

**Comment by stk2008** [comment] 2015-11-17 20:05
Hi thanks for taking the time to look at this :).

When ever I did remove monsters it killed the game and crashed.

Yeah there is about 11 z levels on one slime pit.

**Comment by stk2008** [comment] 2015-11-17 20:06
I thought there was a hard coded max amount of blobs to spawn or was that
only applied to the fungal things?

**Comment by Coolthulhu** [comment] 2015-11-17 20:07
You could try removing monsters from only a part of the area at a time. Teleporting to the area where lag is very slight, removing monsters, teleporting a bit further (one map tile), removing monsters, repeat.
This would allow killing all monsters in the end without killing thousands of them at a time.

The `formblob` attack doesn't work well with z-levels. It isn't really liked in 2D mode either.
I'd say it should be changed or even removed for now.

**Comment by stk2008** [comment] 2015-11-17 20:12
OK I shall try that tomorrow it just feels a bit cheaty is all.

This is the first game I've ever played that I have lived this long etc.

My car is actually further down the road packed with guns.ammo and I mean a
lot of stuff ;).

I just ended up backing up my save and teleporting and trying to debug my
self but I'm a noob at that stuff.

If I can't save my save then so be it lol but would be cool to.
Worst case though would be start again and spend 8hrs on it for it to
happen again lol.

Any ways thanks for helping I hope it's also helped crush one more bug in
this awesome game.

**Comment by ejseto** [comment] 2015-11-18 11:07
Just remove the death function from the monster json definition. Replace all "BLOBSPLIT" with "NORMAL" and then remove the monsters.

**Comment by stk2008** [comment] 2015-11-18 12:59
WOW you are awesome

I did that to all the split on death commands on all the blob entries and
wooooot smooth as silk and no crash when i use the remove monster function
:)

THANK YOU WOOOOOOOOOT :)

**Comment by chaosvolt** [comment] 2015-11-18 15:52
> The formblob attack doesn't work well with z-levels. It isn't really liked in 2D mode either.
I'd say it should be changed or even removed for now.

Since that's what allows blobs to swamp an area unless the player is exceedingly vigilant, I'm tempted to agree with that suggestion solely because it's caused a fair bit of annoyance.

Though a reasonable alternative would be to shift the split ability one more step up the hierarchy. Basically make it so regular blobs can't multiply, but large blobs (and brain blobs, and amoebic molds) can. This would also make their proliferation resemble that of single-celled organisms, mimicked at the macroscopic level.

If we added some sane mechanism (definitely not the evolution mechanic) for them to grow, possibly tied in with some way for them to feed on stuff, this would allow blob reproduction to be more dynamic and less "oops, you spent the night within a mile of a slime pit, I hope you like swimming in goop" like it tends to become. ._.

**Comment by stk2008** [comment] 2015-11-18 15:55
I see so I am not the first to end up having nearly half a million blobs near me LOL

**Comment by chaosvolt** [comment] 2015-11-18 16:00
Hell, it happened to me in my very first adventure back when I was using 0.B stable, in the second town I encountered.

Granted, since this was a "set starting points to 1000 just for the hell of it" game, it ended in a couple days of pure machete mayhem. o3o

**Comment by stk2008** [comment] 2015-11-18 16:03
LOL oh dea

Is there no way to set a hard amount on how many can spawn?.
Then after that it stops spawning blobs?.
Or would that not realy fix the real issue here.

Any way the above suggestion worked so I am well happy.

Just feels a bit cheaty tbh using that command but tbh its also unfair waiting 2secs for my character to actually move LOL

**Comment by chaosvolt** [comment] 2015-11-18 16:09
I'm not quite sure how that would work out, hmm.

**Comment by pouar** [comment] 2015-11-18 16:15
https://imgflip.com/i/uc670

**Comment by stk2008** [comment] 2015-11-18 16:22
LOL pouar

**Comment by Zireael07** [comment] 2015-11-18 16:47
Shifting the blobbing ability one step up the hierarchy sounds like an excellent idea - preserving the signature ability without bogging (or is it blobbing :P) down the game.

**Comment by chaosvolt** [comment] 2015-11-18 17:01
Hell, maybe I should PR that, but I don't know what the official opinion on that idea is yet. >w>

**Comment by kevingranade** [comment] 2015-11-19 00:43
It's definitely problematic that they're multiplying by that much, I'm a
little concerned that having only large blobs split will end up with almost
no splitting, but we can see what it looks like if someone wants to try
that.  Another option is simply having the HP threshold that prevents
splitting be higher (I think I remember there being something like that).

Another direction is just to come up with an entirely new splitting/joining
mechanic, the existing one isn't really amazing enough that it needs to be
preserved, and I don't feel like this sort of thing is hard enough to code
that we'd be at risk of introducing new bugs.

**Comment by chaosvolt** [comment] 2015-11-19 01:02
Hmm. Well, like I said, if we had some alternate way for smaller blobs to grow, it would make blob reproduction slowed but not halted.

So, unsure which of the various options would be best. ^^"

**Comment by CIB** [comment] 2015-11-19 01:13
if(monsters.size() > 1000) { don't spawn freaking blobs }

**Comment by chaosvolt** [comment] 2015-11-19 02:14
Huh. Why didn't I think of that? ;A;

**Comment by stk2008** [comment] 2015-11-19 09:08
I agree keep it how it is but as Christian said and me in my previus posts
just limit how many can spawn full stop.

TBH i think we should do some testing though on different computers to see
how many we can get away with before huge slow down.

**Comment by kevingranade** [comment] 2015-11-19 22:33
A flat limit makes things inconsistent and should be a sanity check at
best. Blob A shouldn't be checking the entire nearby blob, or worse
monster, population to see if it is allowed to split.

**Comment by stk2008** [comment] 2015-11-19 22:37
Ah i dont mean limit themsplitting of blobs i mean limit the amount of
normal blobs.

Takeing the initial amount of normal blobs into consideration for when they
split meaning it will double the amount but never go above.

Im probably talking rubbish lol.

Any who thanks for taking the time to read me issue

**Comment by chaosvolt** [comment] 2015-11-19 22:50
Hmm. More reason for me to be unsure of the ideal solution.

Shifting the split ability up a level would only be feasible if blobs had a sane way to grow depending on conditions.

**Comment by stk2008** [comment] 2015-11-19 22:55
Fair enough im not 100% sure how blobs...well pretty much how any thing
technical works in cdda :p.

I shall leave the solution to u code wizards lol :).

Any way for now i disabled the split on drath as suggested and used the
remove monster command and jy game is now smooth.

Actually i say that i still havento keep using that command as the blobs
keep coming back and slowing the game down again.

Damn ranch is right next the the bloody slim pits etc :(

**Comment by chaosvolt** [comment] 2015-11-19 23:07
Always bring bacon when encounter slim pits. o3o

Anyway, I tend to consider the "split on death" less annoying than their dividing as a special attack. It's when they split on their own that you get renewed lag any time you leave them alone long enough to repopulate.

**Comment by stk2008** [comment] 2015-11-19 23:15
Oh so they split eventually any way?

Well i shall have to keep using the remove monster till some thimg else
comes up other wise its unplayable :(

**Comment by chaosvolt** [comment] 2015-11-19 23:17
It's their special attack. >.>

**Comment by DanmakuDan** [comment] 2015-11-19 23:42
You can also remove the `"special_attacks":[["FORMBLOB", 30]],` found in monsters.json for each of the blob monsters to disable the special ability.

**Comment by stk2008** [comment] 2015-11-19 23:46
Thanks for the tip.

Tbh i feel kind of cheaty doing that and having to use the remove monster
command but i have no choice really so i suppose i should not lol.

It will be interesting to see how or if this can be fixed but still keep
the intended original blob function etc

**Comment by chaosvolt** [comment] 2015-11-19 23:58
Was gonna say, removing the special attack will do more to prevent the slowdown that changing their death function, yeah. ^^"

**Comment by stk2008** [comment] 2015-11-20 00:01
Oh i see ok thanks i shall do that instead then

Thanks :)

**Comment by DanmakuDan** [comment] 2015-11-20 00:22
Maybe, the blob generation could check the 8 surrounding tiles and only generate a new blob if x/8 are not occupied by something already.

**Comment by chaosvolt** [comment] 2015-11-20 00:31
That might cause more complexity and unintended consequences than a simple "check how many blobs exist on overmap" function though.

Still, game-of-life style rules for blob division sounds hilarious.

**Comment by CIB** [comment] 2015-11-20 15:37
I think the lag issue is not so much from blobs themselves replicating, but from 10 levels deep 5x5 slime pits with slime everywhere spawning blobs.

**Comment by chaosvolt** [comment] 2015-11-20 15:37
Ah right. The Z-Level Bandits strike again?

**Comment by mugling** [comment] 2016-03-13 09:53
One of a series of PR's that likely relate to blob division so closing these and tagging #14308 as performance concern

**Closed by mugling** 2016-03-13 09:53 UTC
Labels: Balance, Bug, Mechanics Change
