### ISSUE TITLE
UnicodeEncodeError when executing table.py

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#55114] opened 2022-02-04 23:49 UTC
### Describe the bug

An error occurs when trying to export all item ids to a csv file using `table.py` script with the following command:

```
$ python tools/json_tools/table.py -f csv --nonestring ""  --tileset type id name description color looks_like "copy-from" longest_side > all_game_ids.csv
```

### Steps to reproduce

1. Run `table.py` with the arguments provided above.
2. Wait for the script to throw the error.
3. Observe that output file is incomplete.

### Expected behavior

I expected the script to run without throwing any errors.

### Versions and configuration

- OS: Windows 10

### Additional context

```
Traceback (most recent call last):
  File "D:\Projects\CDDA\local\tools\json_tools\table.py", line 235, in <module>
    worker.print_table(
  File "D:\Projects\CDDA\local\tools\json_tools\table.py", line 223, in print_table
    self.output.row(item_values(item, columns, none_string))
  File "D:\Projects\CDDA\local\tools\json_tools\table.py", line 204, in row
    self.writer.writerow(values)
  File "C:\Users\yooks\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0438' in position 233: character maps to <undefined>
```

**Comment by martosss** [comment] 2022-02-04 23:56
Did you read the last line of that error :
`UnicodeEncodeError: 'charmap' codec can't encode character '\u0438' in position 233: character maps to <undefined>`

This sounds like an encoding error, as in your windows/python library is using a funky encoding table and something there goes wrong.
A possible solution would be to google how to change your default character encoding, in case it's ... say German... to ... say ... English US ... and maybe that will solve the problem?

**Comment by mqrause** [comment] 2022-02-05 00:03
Duplicate of #54631

**Comment by Fris0uman** [comment] 2022-02-05 00:03
duplicate of #54631

**Closed by Fris0uman** 2022-02-05 00:03 UTC
