### ISSUE TITLE
internal chronometer CBM alarm crashes game, build 9027

### ISSUE THREAD

**Issue by Ignaramico** [CleverRaven/Cataclysm-DDA#30771] opened 2019-05-23 04:11 UTC
# If you have installed the internal chronometer CMB, setting the alarm to wake up, makes a game crash. (only for the alarm to wake up)

# Steps To Reproduce

1. Install Internal chronometer CMB
2. Press $ (default key to sleep) and set the time for the alarm (time doesnt matter)
3. sleep, and when the alarm is supposed to set off, the game crashes

# Expected behavior

The wake up alarm setting off and the game not crashing.

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3344-gf3049e5
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Arcana and Magic Items [Arcana],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    No Fungal Monsters [No_Fungi],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    Expanded Archery [ExArch],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Compatible Ninja MOD [Ninja]
]

# Additional context
[crash save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3210207/crash.save.zip)
[crash debug report.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3210208/crash.debug.report.zip)

**Comment by neitsa** [comment] 2019-05-23 10:45
Thank you for your bug report!

Duplicate of #30522

**Comment by ifreund** [comment] 2019-05-23 16:41
Closing as a duplicate

**Closed by ifreund** 2019-05-23 16:41 UTC
