### ISSUE TITLE
Segmentation fault when loading

### ISSUE THREAD

**Issue by SyaoranFox** [CleverRaven/Cataclysm-DDA#55112] opened 2022-02-04 23:10 UTC
### Describe the bug

When I load my game it crashed after all the mods are loaded, throwing a segmentation fault. I have attached all the most relevant files here, however I have been trying to attach my entire game folder here to no avail.

[Lautz.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8006726/Lautz.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8006727/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8006728/crash.log)

### Steps to reproduce

Try and load Lautz to play the game.

### Expected behavior

Game should load with the character standing at their base

### Versions and configuration

I can't load my current game to generate the requested report. According to the launcher I am running the latest experimental build 2022-02-04-2151. Tileset is UltimateCataclysm.

**Comment by wapcaplet** [comment] 2022-02-05 01:07
Confirmed. Plain vanilla, no extra mods, started a new game with the default evac shelter scenario. Save, then load - game crash.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8007052/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8007053/debug.log)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-5847-gfe15810f2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Braian226** [comment] 2022-02-05 01:21
confirmed x2, exact same error

**Comment by dseguin** [comment] 2022-02-05 01:21
Seems to be a duplicate of #55075.

They both crash on `four_quadrants::max()` where `four_quadrants::values` has 4 null pairs

**Comment by Braian226** [comment] 2022-02-05 01:22
> Seems to be a duplicate of #55075.
> 
> They both crash on `four_quadrants::max()` where `four_quadrants::values` has 4 null pairs

Is this fixed with a game update or by fixing my save?

**Comment by dseguin** [comment] 2022-02-05 01:28
I guess you could fix it in the save, but realistically this would require a coded fix. You could try rolling back to an older version in the meantime.

**Comment by wapcaplet** [comment] 2022-02-05 01:36
Thanks for reporting, it always helps to have more info for such problems. I am closing this as a duplicate of #55075.

**Closed by wapcaplet** 2022-02-05 01:36 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), (P2 - High)
