### ISSUE TITLE
Bug report on new game

### ISSUE THREAD

**Issue by RafaelLVX** [CleverRaven/Cataclysm-DDA#51455] opened 2021-09-07 18:10 UTC
### Describe the bug

On Android, on 0.F2, my second playthrough in a world, I got a preset character. World has some of the mods that come with the game. On loading up the game, I got this message.

 DEBUG    : Nonexistent vehicle type: ""

 FUNCTION : vehicle *map::add_vehicle(const vproto_id &, const tripoint &, const units::angle &, const int, const int, const bool)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/mapgen.cpp
 LINE     : 5397
 VERSION  : 0.F-2

### Steps To Reproduce

I'm not sure, I just started a game with a preset character. 

### Expected behavior

No errors. 

### Screenshots

![Screenshot_20210907-150002](https://user-images.githubusercontent.com/909214/132391122-d0fb818e-6137-42db-bb3b-47a931759944.jpg)

### Versions and configuration

 DEBUG    : Nonexistent vehicle type: ""

 FUNCTION : vehicle *map::add_vehicle(const vproto_id &, const tripoint &, const units::angle &, const int, const int, const bool)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/mapgen.cpp
 LINE     : 5397
 VERSION  : 0.F-2

**Comment by RafaelLVX** [comment] 2021-09-07 18:16
If I close app, reset world, start over with new preset character, it repeats this behavior.

**Comment by RafaelLVX** [comment] 2021-09-07 18:19
If instead of using the saved preset character I use "last character", it works no problem. Both last and the saved preset character were built identical.

**Comment by ZhilkinSerg** [comment] 2021-09-07 18:32
Attach your preset please.

**Comment by RafaelLVX** [comment] 2021-09-07 19:42
How can I do that?

Em ter., 7 de set. de 2021 15:32, Zhilkin Serg ***@***.***>
escreveu:

**Comment by Zeropol** [comment] 2021-09-07 21:26
You can find the related preset ( aka template ) file in `/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/templates/`

**Comment by hexagonrecursion** [comment] 2022-01-06 08:25
I can confirm that creating a character with the above preset causes the above assertion. The game does eventually start (if you tell it to [i]gnore the error). One possible cause of this is that the preset was generated by an older version of the game. Another potential source of the error is that the preset was generated with a different set of mods.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7820388/debug.log)

**Comment by ZhilkinSerg** [comment] 2022-01-06 08:40
Should be fixed easily with one line:

![image](https://user-images.githubusercontent.com/16213433/148354394-50992fb3-6a5a-4b80-b66a-e97dca4140be.png)

**Comment by hexagonrecursion** [comment] 2022-02-04 13:43
Possible duplicate of #43217

**Closed** 2022-10-07 01:19 UTC
Labels: Good First Issue, (S2 - Confirmed), Map / Mapgen, Vehicles, Character / World Generation, OS: Android
