### ISSUE TITLE
Crafted boiled eggs from duck, goose, etc. do not properly inherit values from components (e.g., calories) in the stomach after eating, despite showing correct values beforehand in inventory

### ISSUE THREAD

**Issue by JeanLucVanDamme** [CleverRaven/Cataclysm-DDA#31193] opened 2019-06-07 00:26 UTC
# Describe the bug

Crafted food is supposed to inherit properties from the specific components that comprise it. For example, boiled eggs should have different calories if they are made of generic bird eggs (80 cal.) vs turkey eggs (135 cal.) vs duck eggs (130 cal.)

In the inventory, this inheritance seems to be working properly - boiled eggs made from turkey vs duck display correct calorie values, and list the correct components.

However, immediately after eating either boiled duck eggs (130 cal.) or boiled turkey eggs (135 cal.), the stomach contents show as 80 calories. 

This bug extends to nutrition-centered traits and CBMS - see Additional Context.

# Steps To Reproduce

1. Spawn non-standard eggs and the necessary cooking tools.
2. Make boiled eggs.
3. In inventory, boiled eggs will correctly inherit calories and other properties from original eggs.
4. Eat boiled eggs.
5. In stomach (debug menu), eggs will have 80 calories (and presumably, incorrect vitamins, etc.)

# Expected behavior

Stomach contents should match inventory descriptions of food.

# Screenshots
![image](https://user-images.githubusercontent.com/50250164/59074301-67d21480-8890-11e9-8f33-46e33ef93931.png)
_Boiled duck egg, inventory, with correct inherited values_

![image](https://user-images.githubusercontent.com/50250164/59074326-89330080-8890-11e9-9e86-f3346eafcce4.png)
_Before and after eating boiled duck egg. Stomach registers 80 extra calories instead of expected 130._

# Versions and configuration
- OS: Windows [64-bit]
    - OS Version: 10.0 1709
- Game Version: 0.D-3387-ged96404
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Boats [boats],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, -attitude [sees_player_less_attitude],
    Disable Religious Texts [no_religious_Texts],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

No mutations or CBMs on this character.

I think I found the responsible code, but am too amateur in C++ to actually fix it.

Here is the first half of the function that handles food property inheritance. It's in consumption.cpp.

```
// TODO: Move pizza scraping here.
// Same for other kinds of nutrition alterations
// This is used by item display, making actual nutrition available to player.
int player::kcal_for( const item &comest ) const
{
    static const trait_id trait_CARNIVORE( "CARNIVORE" );
    static const trait_id trait_GIZZARD( "GIZZARD" );
    static const trait_id trait_SAPROPHAGE( "SAPROPHAGE" );
    static const std::string flag_CARNIVORE_OK( "CARNIVORE_OK" );
    if( !comest.is_comestible() ) {
        return 0;
    }

    // As float to avoid rounding too many times
    float kcal = 0;

    // if item has components, will derive calories from that instead.
    if( !comest.components.empty() && !comest.has_flag( "NUTRIENT_OVERRIDE" ) ) {
        int byproduct_multiplier;
        for( const item &component : comest.components ) {
            component.has_flag( "BYPRODUCT" ) ? byproduct_multiplier = -1 : byproduct_multiplier = 1;
            kcal += this->kcal_for( component ) * component.charges * byproduct_multiplier;
        }
        kcal /= comest.recipe_charges;
    } else {
        kcal = comest.get_comestible()->get_calories();
    }

    if( has_trait( trait_GIZZARD ) ) {
        kcal *= 0.6f;
    }
```

Note that kcal_for() either calculates inherited food values OR instead allows get_calories() to retrieve default values.

However, the stomach code seems to directly call get_calories() in several places. I assume the stomach code should be modified to call kcal_for() instead, so it doesn't bypass the important rest of this function.

P.S.
This bug also extends to the Expanded Digestion bionic, the GIZZARD trait, etc., all of which are handled in kcal_for(). Adjusted calorie values do display properly in inventory, but are not reflected in stomach contents. (I tested this with other characters with relevant traits.)

The boiled egg entry in eggs.json does copy-from "egg_bird" which has 80 calories - but this is supposed to be only a default and be overridden by inheritance.

**Comment by anothersimulacrum** [comment] 2019-06-07 00:29
Duplicate of #30705

**Comment by JeanLucVanDamme** [comment] 2019-06-07 00:32
Yep, appears to be the same bug -- but this post adds more info and a potential solution :)

@KorGgenT I think this is stomach-relevant

**Closed** 2019-06-26 08:31 UTC
Labels: <Bug>, Food / Vitamins
