### ISSUE TITLE
Game crashes during fabrication of a Survivor Sleeveless Duster. Specifically when achievement "Tailor" is earned

### ISSUE THREAD

**Issue by BillCRobinsonJr** [CleverRaven/Cataclysm-DDA#64958] opened 2023-04-09 16:48 UTC
### Describe the bug

In the attached save I am in the process of fabricating a Survivor Sleeveless Duster. When I reach 12% complete and at the same time earn the achievement of "Tailor" the game crashes with the crash log attached. I have tried stopping the fabrication before reaching 12% and then starting again and the same result happens when 12%  is reached.

### Attach save file

[Bar Mills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11185904/Bar.Mills-trimmed.tar.gz)

### Steps to reproduce

Load the supplied save file and let the fabrication continue until you reach 12%

### Expected behavior

I would not expect a crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: d0e1db5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11185905/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11185906/debug.log)

**Comment by Zireael07** [comment] 2023-04-09 16:49
Did you try disabling achievement popups?

**Comment by BillCRobinsonJr** [comment] 2023-04-09 16:49
> Did you try disabling achievement popups?

I have not.  I will do so.

**Comment by BillCRobinsonJr** [comment] 2023-04-09 16:53
> > Did you try disabling achievement popups?
> 
> I have not. I will do so.

I just disabled the achievement pop-up and the crash did NOT occur.

**Comment by GuardianDll** [comment] 2023-04-09 16:56
Duplication of #64466

**Comment by Zireael07** [comment] 2023-04-09 16:56
In that case duplicate of the pinned issue #64466

**Comment by BillCRobinsonJr** [comment] 2023-04-09 17:00
One, perhaps slight, difference.  In my instance I did not get a pop-up, just a message in the right hand panel message log.

**Closed** 2023-04-11 21:05 UTC
Labels: (S3 - Duplicate)
