### ISSUE TITLE
minireactor BUG v11203

### ISSUE THREAD

**Issue by TaTalia** [CleverRaven/Cataclysm-DDA#45747] opened 2020-12-01 03:36 UTC
# Describe the bug
if minireactor is reloaded  with 10 charges of plutonium,
minireactor will have 5000 charges of plutonium!!!
I can get **5000 charges of plutonium** if unload minireactor!!!!!!!!!!!!!!!
It's big bug!!!  

# Steps To Reproduce

<!-- Steps to reproduce the behavior:
1. prepare 10 charges plutonium and 1 minireactor(no plutonium).
2. reload minireactor with 10 charges plutonium.
3. unload minireactor.
4. get 5000 charges plutonium.

**Comment by emptytriangle** [comment] 2020-12-01 06:41
more info in #45702

**Comment by anothersimulacrum** [comment] 2020-12-01 15:48
Duplicate of #45702

**Closed by anothersimulacrum** 2020-12-01 15:48 UTC
Labels: (S1 - Need confirmation), (S3 - Duplicate), Items: Ammo, Vehicles
