### ISSUE TITLE
Police officer starts without a gun

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#41039] opened 2020-06-02 18:52 UTC
**Describe the bug**
Police officer starts without a gun, but two magazines of .45 ammo.

I used debug to spawn it and discovered another one - USP .45 cannot be stored in a holster. 

It may be related to the holster issue - I guess that the pistol is supposed to spawn in it, and if it can’t, it stays empty.

**To Reproduce**
1. Create a new character. 
2. Police officer doesn't have a gun.
3. Spawn it.
4. Try to put it in the holster. 

**Desktop (please complete the following information):**
Windows 10, latest version.

**Comment by ymber** [comment] 2020-06-02 20:18
Closing as duplicate of #40456.

**Closed by ymber** 2020-06-02 20:18 UTC
Labels: <Bug>, Mutations / Traits / Professions
