### ISSUE TITLE
clean water crafting times

### ISSUE THREAD

**Issue by Junkinmytruck69** [CleverRaven/Cataclysm-DDA#75606] opened 2024-08-11 23:40 UTC
### Describe the bug

making 50x clean water takes 3 hours 
making 50x boiled bandages takes 20min 
Both results provide 50x clean water

### Attach save file

N/A

### Steps to reproduce

1. get a brazier next to water
2. set on fire
3. check crafting time for boiling water
4. check crafting time for making boiled bandages

### Expected behavior

expect craft times to be similar or result in different quantities of clean water

### Screenshots

![image](https://github.com/user-attachments/assets/c2bd1aa3-e786-4713-b133-f33c18b1c97b)
![image](https://github.com/user-attachments/assets/74f33751-52b5-447b-964c-bd7559a2591d)

### Versions and configuration

2024-08-03-1813

**Comment by Brambor** [comment] 2024-08-12 11:43
Duplicate of #73333.

**Closed** 2024-08-12 11:45 UTC
Labels: (S3 - Duplicate)
