### ISSUE TITLE
non-perishable food that is (fresh) can't be crafted with

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#19707] opened 2016-12-10 04:13 UTC
Stumbled on this today. Have a can of tuna fish (fresh) that won't work in any recipe it is supposed to, where as a my canned fruit that isn't does.

**Comment by ZhilkinSerg** [comment] 2016-12-10 09:18
I believe only food from opened cans can be used in crafting, so you'll need to [U]nload tuna from the can before stewing your fish soup.

**Comment by codemime** [comment] 2016-12-10 11:06
Dupe of #17401.

**Closed by codemime** 2016-12-10 11:06 UTC
Labels: Duplicate
