### ISSUE TITLE
Hunting lodges are unfinished

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#50255] opened 2021-07-27 11:35 UTC
### Describe the bug

Hunting lodges are missing a basement, a second floor, and the roof.

### Steps To Reproduce

1. Make a world.
2. Debug reveal overmap.
3. Find a hunting lodge and teleport to it.
4. Look around and see only the ground level is finished.

### Expected behavior

For the lodge to not have half of it get sucked away into another dimension.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: f40b533 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Kittymod [kittymod],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    No Fungal Monsters [No_Fungi]
]

### Additional context

Kittymod is my personal mod, it doesn't alter hunting lodges.

**Comment by Maleclypse** [comment] 2021-07-27 13:58
That's weird,  so when I debuged the lodge in as I couldn't find it on twelve overmaps the basement worked fine.   Second floor was definitely having some issues in that it was the roof for the floor below.

**Comment by KittyTac** [comment] 2021-07-27 14:14
The basement in mine was blocked off by walls. Maybe the mapgen is weird with it, dunno.

**Comment by GoLoT** [comment] 2021-07-29 07:02
I had this happen too. In my case the second floor was missing completely (no floor) and the closed off room (with barred windows) was missing the outer wall (not the windows though) with items spawning where the wall should be instead of on the shelves inside the room.

**Comment by Maleclypse** [comment] 2021-07-29 15:42
> I had this happen too. In my case the second floor was missing completely (no floor) and the closed off room (with barred windows) was missing the outer wall (not the windows though) with items spawning where the wall should be instead of on the shelves inside the room.

I think that is from the version where nested mapgen was deleting any pre-existing terrain.   Which should be fixed if you update.

**Comment by hexagonrecursion** [comment] 2021-08-10 12:37
Either hunting lodges are very rare or they don't spawn at all. Removing existing: true allows a couple of them to spawn per overmap.
https://github.com/CleverRaven/Cataclysm-DDA/blob/ed2f630d83ecdf6033cb457ac9525759b7c91dc3/data/json/overmap/overmap_special/specials.json#L263

**Comment by hexagonrecursion** [comment] 2021-08-10 12:38
So far can not reproduce: I have explored half a dozen of naturally spawned hunting lodges and they all had a basement and a second floor.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: ed2f630 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by KittyTac** [comment] 2021-09-18 06:23
> 
> 
> > I had this happen too. In my case the second floor was missing completely (no floor) and the closed off room (with barred windows) was missing the outer wall (not the windows though) with items spawning where the wall should be instead of on the shelves inside the room.
> 
> I think that is from the version where nested mapgen was deleting any pre-existing terrain. Which should be fixed if you update.

Late, but I just found one in a recent experimental, still no roof. None of my mods affect generation of those structures either.

**Comment by Night-Pryanik** [comment] 2022-02-06 17:12
Can't reproduce this either. Closing as unconfirmed. If this is still an issue, ping me, and I'll reopen.

**Closed by Night-Pryanik** 2022-02-06 17:12 UTC
Labels: (S1 - Need confirmation), Map / Mapgen
