### ISSUE TITLE
More coffee.

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#36856] opened 2020-01-09 23:23 UTC
**Is your feature request related to a problem? Please describe.**  
Been playing for a while and I noticed that coffee powder and coffee beans have such a low chance to spawn. This is odd because coffee is really common in US households. 

**Describe the solution you'd like**  
If somebody could up the spawns of coffee beans, powder, and coffee syrup maybe even add a grinder item to turn beans into powder. Would be nice if there was some extra coffee flavors that could give more joy (vanilla, cinnamon, chocolate, ect) and maybe add instant coffee.

**Describe alternatives you've considered**  
Doing nothing

**Additional context**  
For instant coffee it seems to last 2-20 years depending on the packaging
https://www.stilltasty.com/fooditems/index/16939
Here is some info for whole bean and ground coffee as well
https://www.eatbydate.com/drinks/coffee-tea-shelf-life/coffee-shelf-life-expiration-date/
Here is some coffee consumption data
https://www.hsph.harvard.edu/news/multimedia-article/facts/
https://disturbmenot.co/coffee-statistics/

**Comment by Brian-Otten** [comment] 2020-01-10 00:07
I would love for this to be added, and would go great with a new "coffee addiction". people with coffee addiction would get morale boosts for drinking coffee and morale penalties for withdrawal. caffeine pills could stave off withdrawal but give no morale.

**Comment by I-am-Erk** [comment] 2020-01-10 00:48
Much of this falls into https://github.com/CleverRaven/Cataclysm-DDA/issues/34432 and is already largely being resolved by SUS kitchen groups (coffee cabinets are a very common spawn). However it would be fine to add more coffee materials and clutter items, for sure

**Comment by KorGgenT** [comment] 2020-01-11 05:44
as erk says this falls under that issue quite well. i'm going to close this as a Duplicate of #34432

**Closed by KorGgenT** 2020-01-11 05:44 UTC
Labels: (S3 - Duplicate)
