### ISSUE TITLE
Labs cut into vaults.

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14136] opened 2015-11-22 21:24 UTC
Screenshot: https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/VaultLab.PNG

Pretty self-explanatory - there's a direct passage between the vault and the lab. Seems odd, given that they're supposedly built by the same people - you'd think they'd want to avoid the vaults being anywhere even close to the labs (and even if you say they're nearby for convenience, you'd want them to not be connected :P)

**Comment by sparr** [comment] 2015-11-27 10:01
If you still have this save, could you get a screenshot in debug mode so we can see the whole map around this? would be helpful to see how all the nearby rooms line up.

**Comment by etmoonshade** [comment] 2015-11-28 05:35
Not in debug mode, but a decent amount of everything explored. Map is centered on the lab:
https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab1.png
https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab2.png
https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab3.png

**Comment by sparr** [comment] 2015-11-28 05:50
the normal view, not the map, would be more useful. showing the connection in as much detail as possible. what I want to do is figure out which specific 24x24 mapgen function led to the connection.

**Comment by etmoonshade** [comment] 2015-11-28 06:05
This seems like it should cover you. First picture is from Level -2, second picture is from level -3.

https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab4.png
https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab5.png

Bonus picture: Same lab cuts into the sewers one level above. Not sure if it's as undesirable as the initial example:
https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/Lab6.png

**Comment by BevapDin** [comment] 2015-11-29 15:47
> the normal view, not the map, would be more useful. showing the connection in as much detail as possible. what I want to do is figure out which specific 24x24 mapgen function led to the connection.

This isn't really a problem of the 24x24 mapgen, but of the overmap. The 24x24 mapgen for the lab assumes that each lab is surrounded by either more labs or rock. For this it only generates walls one two sides of the map. The walls on the other two sides come from the neighboring mapgen. (You can sometimes find a lab that has a rock wall on some side.)

Similar, the vault does not care care about the neighborhood.

This is pretty much the same problem as with ant tunnels vs labs. One of the overmap specials (lab, ants, vault) is placed first, and the other is placed later on top of it and overrides it.

This simple solution could be to check the location being empty (rock) before making it a lab.

**Comment by Oskar636** [comment] 2016-11-10 17:50
I cannot get this bug to reproduce but since it doesn't really matter that much, I would like for anyone to report it here if they find another instance of the labs doing weird stuff.

**Comment by etmoonshade** [comment] 2016-11-10 20:20
It's been a while since I reported this bug - I'll bet that it would happen more often with a higher city density, since that's what I was playing with at the time.

It's been a while since I played DDA - I can have a shot at reproducing it again if I've got the time though.

**Comment by Leland** [comment] 2017-05-04 03:36
@etmoonshade this has been sitting around for a while and hasn't been reproducible. I'm closing this for now – if you do manage to reproduce it, let us know here and include a savefile and we'll reopen it.

Do note that the science labs are a bit dodgy – see #10958

**Closed by Leland** 2017-05-04 03:36 UTC
Labels: Bug, Confirmation Needed, Mapgen
