### ISSUE TITLE
Zombies had clean clothing after I killed them

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71510] opened 2024-02-04 23:16 UTC
### Describe the bug

I killed a pair of zombies (one regular, one fat) and they had clean clothes on. 

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14158833/Earth-trimmed.tar.gz)

### Steps to reproduce

I haven't seen this before, but in the attached save, there is an unexplored garage to the northeast (~20 tiles or so). Inside that garage are two zombies, and upon killing them (I've done it with a fire axe), they drop clean clothing. (To be clear, the clothing isn't dropped on the ground, its still on the zombies.)

### Expected behavior

I expected the zombies to have filthy clothing instead. 

### Screenshots

_Figure 1. The clean clothing on the freshly killed zombies. (If you know how to center this, please let me know.)_ 
![Screenshot (339)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/56bac207-c06c-4352-9897-eae762975aec)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This is the same save as the crash reported in issue #71508.

**Comment by PatrikLundell** [comment] 2024-02-05 08:40
/confirmed

Not entirely sure it's suitable to claim it to be confirmed, but I've seen it occasionally for quite some time. Thus, it's not caused by a recent change. I haven't seen it recently simply because I haven't been playing recently.

**Comment by Night-Pryanik** [comment] 2024-10-06 05:51
Can't confirm on 0.G-12522. Closing until reconfirmed.

**Closed by Night-Pryanik** 2024-10-06 05:51 UTC
Labels: (S2 - Confirmed)
