### ISSUE TITLE
Bows show ammo selection dialog when you have multiple stacks of the same ammo

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15230] opened 2016-02-04 12:39 UTC
If I'm not mistaken, bows used to auto pick ammo when there was one type, and preferred arrows in the quiver over others. Now it is showing me the ammo selection dialog even when I only have one type of ammo, some in the quiver, some not.

**Comment by mugling** [comment] 2016-02-04 15:43
By design.

From the quiver is much faster than from the inventory.

**Comment by macrosblackd** [comment] 2016-02-04 16:03
If the arrows from the quiver and the arrows in the inventory are the same, I would expect it to automatically choose the arrows in the quiver.

**Comment by macrosblackd** [comment] 2016-02-04 16:08
It might not be a bad idea to have a fire mode for the bow to automatically pull _only_ from the quiver even if there are different arrows in the players inventory.

**Comment by mugling** [comment] 2016-02-04 16:09
In **absolutely** all circumstances? Perhaps you want to use arrows from the inventory for dealing with softer targets and keep the quiver for quicker shooting when dealing with a hulk?

It's not that your idea is inherently bad, just that if we are to automate reloading we need to get it absolutely perfect to avoid such corner cases.

If you can clearly define such an automated behavior and there is broad consensus I'll look into it, but for now the above behavior is by design and so I don't consider this a bug.

**Comment by mugling** [comment] 2016-02-04 16:12
> > If you can clearly define such an automated behavior

> It might not be a bad idea to have a fire mode for the bow to automatically pull only from the quiver

This is closer but still not completely defined. What is this mode called and what happens when there is ammo in the inventory but not the quiver. Such behavior needs ideally to be generically applicable to all ranged weapons otherwise we'll litter the code with such special cases.

**Comment by macrosblackd** [comment] 2016-02-04 19:19
So, for ranged weapons that utilize a quiver (bows, xbows, not sure about sling/slingshot) the automated behavior should be:
- Select ammo from quiver
- If quiver is empty and the player has arrows in the inventory:
  - If only one type of arrow, select that
  - Prompt user if multiple types of arrows

**Comment by karlnp** [comment] 2016-02-04 19:39
This happens with multiple battery stacks as well.

**Comment by mugling** [comment] 2016-02-04 20:06
> This happens with multiple battery stacks as well.

How are you getting multiple battery stacks in the first place?

**Comment by Coolthulhu** [comment] 2016-02-04 20:14
I assume when you damage one stack somehow.

**Comment by mugling** [comment] 2016-02-04 20:25
@Coolthulhu That was the only way I could think of. The same thing can occur with ammo. Come to think of it is having various degrees of damaged ammo actually useful (as we currently do nothing with that data)?

@macrosblackd but what if the player actually wants to use arrows from the inventory?

**Comment by macrosblackd** [comment] 2016-02-05 00:16
@mugling that goes back to the idea of a psuedo 'fire mode' for bows : one for how it currently works, another to choose best using the logic I described earlier.

**Comment by NickGrease** [comment] 2016-02-06 15:25
@mugling  This relates to the original post, with the same ammo in quiver and inventory, the selection screen always seems to default to using inventory arrows, even after I select quiver. So instead of the sequence of keys to fire after the first shot: 'f, enter, enter', I have to use the combination 'f,up,enter,enter' to get back to quiver ammo each shot. What I mean is, the selection screen doesn't seem to remember the last used ammo, and always starts the selection off with using ammo from the inventory. Hope that makes sense. It's a small issue, but if you use bows a lot, the keypresses add up.

**Comment by mugling** [comment] 2016-02-06 15:27
@NickGrease Probably relates to #15271

**Comment by NickGrease** [comment] 2016-02-06 16:11
@mugling My bad, sorry, thought I had the latest build - seems I didn't. Selection menu seems to remember last selection. It also lists the same quiver twice, once for worn, and I guess once for being a  container. So the selection list has 3 options instead of the expected 2 (quiver,inventory). But I expect that is by design since you could have more then one quiver/container with arrows. Either way I like the changes - thanks!

**Comment by mugling** [comment] 2016-02-06 16:15
No, the multiple listings is #15271 and I have a fix for that shortly

**Comment by mugling** [comment] 2016-02-15 12:08
Needs closing

**Comment by kevingranade** [comment] 2016-03-07 02:23
And whatever we *can* do about it is going to be handled by #15566

**Closed by kevingranade** 2016-03-07 02:23 UTC
