### ISSUE TITLE
Error when try to get Teamster Mission

### ISSUE THREAD

**Issue by GordanGeeko** [CleverRaven/Cataclysm-DDA#54654] opened 2022-01-22 02:05 UTC
### Describe the bug

I get an error when I try to activate the Teamster mission. Though the mission is exists, there is no marker on the map.

### Steps to reproduce

1. Load up my version and mods.
2. Create world.
3. Teleport to Refugee Center and talk to Teamster
4. Try get mission
5. See error.

### Expected behavior

I should get the map market to the location the Teamster indicates.

### Versions and configuration

-Windows 10
-build 2021-01-17-1621.
-Tileset

### Additional context

**Error:**
DEBUG    : Unable to find and assign mission target robofac_hq_surface_freemerchant_camp.

 FUNCTION : cata::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 251
 VERSION  : dc02e84

**Mods:**

  "no_npc_food",
  "cargoportal",
  "crt_expansion",
  "No_Fungi",
  "aftershock",
  "No_Rail_Stations",
  "light_weariness",
  "pneumo_fun",
  "blazemod",
  "AftershockUDP",
  "crt_expansionUDP"

**Comment by LeahLuong** [comment] 2022-01-22 03:27
Dupe of #53058 & you have ignored the stalebot advisory by both commenting in that thread & bumping the issue by making this 1. That said, prob worth it.

**Comment by GordanGeeko** [comment] 2022-01-22 04:41
> Dupe of #53058 & you have ignored the stalebot advisory by both commenting in that thread & bumping the issue by making this 1. That said, prob worth it.

Sorry, I saw another comment with the same issue from December that went unnoticed.

**Closed** 2022-01-24 15:38 UTC
