### ISSUE TITLE
Error: there is already a monster at 100,83,0

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#31281] opened 2019-06-09 17:38 UTC
# Describe the bug

While my character was walking inside a pawn shop, an error appeared: "there is already a monster at 100,83,0").

# Steps To Reproduce

I have saved the game a few turns before the bug appeared, but did not manage to reproduce the bug on reloading the save. I reloaded might be 5 times. It could be of relevance that, after the error message, I got a message "An eyebot swoops nearby". However, this didn't happen when I reloaded the save, so might be the bug was caused by an eyebot appearing on a tile that was targeted by another monster?

# Expected behavior

No error should appear.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster);
- Game Version: 0.D-4123-g37a61677a2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionics Systems Mod [bio_mod],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    NPC traits [npc_traits],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3269779/debug.log)
[Costa Mesa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3269784/Costa.Mesa.zip)

**Comment by neitsa** [comment] 2019-06-10 08:29
Duplicate of #29146

**Comment by ifreund** [comment] 2019-06-10 09:28
Closing as a duplicate

**Closed by ifreund** 2019-06-10 09:28 UTC
