### ISSUE TITLE
dupe ammo magazine

### ISSUE THREAD

**Issue by DeCrap** [CleverRaven/Cataclysm-DDA#17912] opened 2016-08-04 06:26 UTC
100% work on bild 5322:

1 - get clean glock19 ([U]nload, if not clean)
In inventar: 1 clean glock19(0)

2 - get 2 any glock magazine (original or extended magazine)
In inventar: 1 clean glock19(0) and 2 clean(0) glock magazine

3 - full loads this 2 glock magazine ([r] for all this magazine)
In inventar: **1 clean glock19(0) and 2 fully loaded(15) glock magazine**

4 - [r]eload glock19, and select first glock magazine (only magazine!)
In inventar: 1 loaded glock19(15) and 1 fully loaded(15) glock magazine

5 - [r]eload glock19, and select next glock magazine (only magazine!)
select "put in inventar"
glock not change magazine, and game write to log:
`9:13:8.197 : src/item_location.cpp:546 [void item_location::remove_item()] item location does not point to valid item`
![screenshot 1470288288](https://cloud.githubusercontent.com/assets/20589687/17391716/07715e84-5a21-11e6-8766-c0aa0ec633a1.png)
press space
In inventar: 1 loaded glock19(15) and 1 fully loaded(15) glock magazine
what? magazine not loading in glock!

6 - If after log messages, [U]nload glock19 - magazine unloading, but... glock19 fully loaded!
In inventar: 1 loaded glock19(15) and 2 fully loaded(15) glock magazine

7 - [U]nload glock19
In inventar: **1 lclean glock19(0) and 3 fully loaded(15) glock magazine**

Repeat steps 5..6, and get INFINITY ammo.

Mods enabled:
    "FIC_Weapons",
    "More_Survival_Tools",
    "Medieval_Stuff",
    "nw_pack",
    "craftgp",
    "ew_pack",
    "more_locations",
    "Experimental-Z-Level",
    "boats",
    "blazemod",
    "deoxymod",
    "Tanks",
    "necromancy",
    "Slow_Zombies",
    "survivorweaps",
    "StatsThroughSkills"

If need: [save](https://mega.nz/#!D8FRwZyK!FeYWvHsuv2WAlmUDtfDBrIfaePxPt2xQ2HmdK5zp8Rw), and [config&logs](https://mega.nz/#!TsEjVBwQ!udQ0ah8cGyj1CFRFa3u7wmetbWfGCd5NE-6vBenYwek)

**Comment by Lord-Helmchen** [comment] 2016-08-04 08:17
duplicate of #17869

**Comment by mugling** [comment] 2016-08-04 09:43
Probable duplicate but see the comments in #17879 as I suspect we have two similar bugs so please reopen if you can reproduce in `master`

**Closed by mugling** 2016-08-04 09:43 UTC

**Comment by DeCrap** [comment] 2016-08-04 21:57
ok, reopen.
Get build 5331, create world, settings default (all mod off).
Get in debug menu 1 glock19 and 2 glock magazines
Press [w], select glock19, and inject one magazines (press [r])
And repeats: [r], enter, enter, space, [r], enter, enter, space...
In log writes this errors:
`0:37:30.438 : src/visitable.cpp:428 [item visitable<T>::remove_item(item&) [with T = Character]] Tried removing item from object which did not contain it`
![screenshot 1470344583](https://cloud.githubusercontent.com/assets/20589687/17418867/53db546e-5aa3-11e6-9c2c-672b848e3555.png)
And glock magazines more and more.

Dupe 100% work, but another error string.

[save](https://mega.nz/#!D99HjQ7A!BApzEYFhc4RdCjZXu5sq2bgh2AzArwGS1VQKJjbSO6I) and [config&logs](https://mega.nz/#!L8lHHCZY!NT73pjtni02_lIxFgpVL_KGnGF5yocTAVuAXBTuB-eo)

**Comment by mugling** [comment] 2016-08-04 21:59
Are you sure you have enough inventory space after debugging in the items? After spawning the items walk one tile north and then try the test.

**Comment by DeCrap** [comment] 2016-08-05 06:23
Yep, inventory free.
I record duplicate process, can [see](https://youtu.be/IAMET7S6qcI) it.
