### ISSUE TITLE
I have been receiving an error screen on loading a save, ever since ammonia changed to liquid ammonia

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#58644] opened 2022-06-23 05:57 UTC
### Describe the bug

The error message keeps popping up. It's becoming annoying.

### Steps to reproduce

1. Open the game
2. Error should come

If there is no error, then it seems the already existing ammonia or something depending on it is causing this error

### Expected behavior

No error. Should recognize the new ID of Liquid Ammonia

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/175224163-2de642e6-42f4-4ee3-9d2b-d8cc6f936a18.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: bcd8b3b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

 DEBUG    : Missing item definition: ammonia

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 2327
 VERSION  : bcd8b3b

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8964387/debug.log)

Save file was 37 MB after zip, so I could not upload....

**Comment by aMegaSloth** [comment] 2022-06-23 08:38
The root case is: #58545

the keyword ammonia was deleted and something new was replaced in it. The problem is now with any world generated pre-#58545 will have errors.

**Comment by anothersimulacrum** [comment] 2022-06-23 16:46
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/58586

Yes, that is the way to solve it, it's outlined in the above issue.

**Closed by anothersimulacrum** 2022-06-23 16:46 UTC
Labels: (S3 - Duplicate)
