### ISSUE TITLE
Crafting issue with water

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19301] opened 2016-11-15 15:08 UTC
Version: Exp 5881

When 
1. water tiles nearby

and

2. water items in inventory

exist at the same time, the crafting menu doesn't think the player has water available.

**Comment by Zireael07** [comment] 2016-11-15 19:07
I believe this is a duplicate and that the problem is due to an overflow... @mugling? @codemime? Can you find the original issue?

**Comment by ZenZen2** [comment] 2016-11-15 19:35
looks like duplicate of #18709

(how do i link?)

**Comment by ZenZen2** [comment] 2016-11-15 19:35
oh it does it automaticly :D

**Comment by Coolthulhu** [comment] 2016-11-15 19:38
My attempt at fix: #19149

**Comment by ZenZen2** [comment] 2016-11-15 19:56
i wish i would have your magic skills to help with the bug hunting

**Closed** 2016-11-16 11:41 UTC
Labels: Bug, Duplicate

**Comment by BrettDong** [comment] 2016-11-16 13:51
Oops, sorry for duplication. I typed wrong search query before I submitted this new issue.
