### ISSUE TITLE
Creating a new PC in the same world overwrites existing save file if the name of PC is the same as the name of PC of affected savefile

### ISSUE THREAD

**Issue by EditorRUS** [CleverRaven/Cataclysm-DDA#19539] opened 2016-11-29 00:31 UTC
Exactly what it says on the tin

http://i67.tinypic.com/sqjb4y.png
->
http://i64.tinypic.com/4v0aah.png
->
http://i66.tinypic.com/b5im29.png
->
http://i68.tinypic.com/2hhdekm.png
->
http://i67.tinypic.com/34fikcx.png

**Comment by EditorRUS** [comment] 2016-11-29 00:59
Testing the issue a little bit more.

1. Created a world named "Test World"
2. Created a character named "Test Character 1" [with 8 points in strength]
3. Created a character named "Test Character 2"
-- Two characters created: http://i67.tinypic.com/mls5jm.png --
-- Two .sav files in world's directory: http://i65.tinypic.com/15etkw9.png --
4. Created a character named "Test Character 1" [with 4 points in strength]
5. Loaded the world with "Test Character 1" again.
6. Confirmed that this is the new character. Old character is irretrievably lost (no graveyard backup).
-- http://i63.tinypic.com/292w8aw.png --

**Comment by codemime** [comment] 2016-11-29 01:05
Please upload pictures directly. Otherwise they sometimes aren't displayed properly (that's the case for me now).

**Comment by codemime** [comment] 2016-11-29 01:05
Dupe of #16419.

**Closed** 2016-11-29 08:36 UTC
