### ISSUE TITLE
Crash on earning any achievement

### ISSUE THREAD

**Issue by shell1610** [CleverRaven/Cataclysm-DDA#64601] opened 2023-03-26 18:51 UTC
### Describe the bug

I crash every on any earned achievement. 

### Attach save file

[Andrix-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11072683/Andrix-trimmed.tar.gz)

### Steps to reproduce

1. Melee around 10 zombies until you get brawler achievement and game crash. (Last time I slept I earned an achievement too, so you may try that instead)

### Expected behavior

To play with achievements enabled

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0bba914 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries]
]

**Comment by anothersimulacrum** [comment] 2023-03-26 19:59
Duplicate of #64466

**Closed by anothersimulacrum** 2023-03-26 19:59 UTC
Labels: (S3 - Duplicate)
