### ISSUE TITLE
Bordered challenge causes crashes

### ISSUE THREAD

**Issue by coolmanabdul** [CleverRaven/Cataclysm-DDA#49621] opened 2021-07-06 08:56 UTC
# Describe the bug
if you attempt to use bordered gamemode it immediately crashes any version will cause it crash mods or no mods.

# Steps To Reproduce
open CDDA
make a 100% vanilla world or any world for that matter as it seems no alterations mods or otherwise effect it
choose bordered start and attempt to play the game
it should immediately crash upon game start

# Expected behavior
immediate crash not even enough time to alert you of anything and game doesn't save or do anything other than shutdown.
What it should do at least from what I've seen from its description is a scenario with large wall surrounding you.

# Screenshots
I cannot get screenshots as it immediately crashes.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 21H1 19043.1052
- Game Version: d98fcf0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
# Additional context
I hate no idea to get crash log file as its immediate and I cannot input any commands or get any files of it.

**Comment by ZhilkinSerg** [comment] 2021-07-06 09:07
Duplicate of #49620

**Closed by ZhilkinSerg** 2021-07-06 09:07 UTC
