### ISSUE TITLE
Items still show as (on) after they run out of charges

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#47765] opened 2021-02-27 03:02 UTC
# Describe the bug

Items that run out of charges, like flashlights or candles, continue showing in inventory screens as (on) despite having run out of charges.

e.g. `candle (lit) (0/100 wax)`

# Steps To Reproduce

1. Spawn a candle.
2. Light the candle.
3. Wait until the candle runs out of wax.
4. Open the inventory screen.

# Expected behavior

Once an item runs out of charges it should automatically switch to its "off" state. In the case of a candle, perhaps the entire item should disappear.

# Versions and configuration

Game Version: 0.E-9399-gb4ab3df

**Comment by wapcaplet** [comment] 2021-02-27 04:09
Confirmed on 0.E-9857-gf77f179d0c - when a candle or cell phone battery reaches 0, the item remains highlighted in yellow and "lit" or "on" for some time afterwards (I checked in 30-minute intervals).

This sounds very much like #39155 and I believe is a rounding error, where the actual amount remaining is still non-zero for a while after the indicator shows 0.

Candle showing "lit" at 0/100:

![image](https://user-images.githubusercontent.com/238395/109375045-d205c680-7876-11eb-8726-496a7074e5e6.png)


Cellphone flashlight active with 0/100:

![image](https://user-images.githubusercontent.com/238395/109375024-abe02680-7876-11eb-88fa-7f9719c7337a.png)

40 minutes later, it has turned off (possibly sooner):

![image](https://user-images.githubusercontent.com/238395/109375040-c61a0480-7876-11eb-8d0e-6c8abf9819a4.png)

**Comment by nornagon** [comment] 2021-02-27 04:35
Ah, yes #39155 sounds very similar, I'd be surprised if this and that aren't the same bug.

**Comment by actual-nh** [comment] 2021-02-28 00:16
Evidently, if 0 < abs(value) < 1, it shouldn't round to an integer for display. (This does not say anything about the other bugs that may be still involved, as in not being able to turn things off, etc.)

**Comment by anothersimulacrum** [comment] 2021-02-28 01:21
I don't think it's a rounding thing, I think it's just the way that our power draw is implemented is randomness (when it's < 1 charge per turn), because we only integer precision (single charge).

**Comment by PaulBlay** [comment] 2021-03-04 11:59
You see this a lot with flashlights. When everything goes dark and you stop crafting, the flashlight is still shown as ON and if you are quick enough you can put a fresh battery in it and the light comes back - without having to turn it back on (because it never went off). If you walk a few tiles the last gasp of the battery runs out and it turns off for real.

**Comment by anothersimulacrum** [comment] 2021-03-04 15:59
Here's the relevant bit of code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/c6eec92c2e08b05eb53fb09e50adeb7c7bfb40e5/src/item.cpp#L10128-L10159

You can see that energy draw is based on randomness, and things only revert to an off state if they try to draw power, and fail.
So they can draw power, be at 0 charges, then it'll take them another while for them to roll correctly to draw more power and turn off.

**Comment by actual-nh** [comment] 2021-03-04 16:13
I have a suggestion (derived from grading experience 🙃 ): Assuming the item is still on and running off of internal power, A is the charges left, and B is the total number of charges, display as (pseudocode): `round_up(B*((A+1)/(B+1)))` over B - this will go from 100/100 to 1/100 as the underlying value goes from 100 to 0.

**Closed** 2022-08-09 14:22 UTC
Labels: <Bug>, (S2 - Confirmed), Items / Item Actions / Item Qualities
