### ISSUE TITLE
Moving diagonally around a dragged vehicle should not bring the player on top of the vehicle

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#19770] opened 2016-12-15 18:25 UTC
If you grab a vehicle like a cart and you move diagonally around it, it will bring the player on top of the vehicle. Here are a few examples where `.` is an empty tile, `P` is the player, `=` is the vehicle and `₱` is the player on the vehicle.

If you start from this position (player is down from the vehicle), you have the player dragging the vehicle
```
...
.=.
.P.
```
and you move up-left you will end up like
```
...
₱..
...
```
The expected behavior is that the player just move around the vehicle and end up like
```
...
P=.
...
```

The other diagonal directions have similar behaviors. If you move up-right from the same original position (player is down from the vehicle), you will end up like
```
...
..₱
...
```
while the expected end result should be like
```
...
.=P
...
```

This issue also has the unintended consequence of adding a message like `Moving onto this dirt is slow` when performing those diagonal moves. This is most likely due to the fact that the player moves on the vehicle (which is slow) but the vehicle is not already on the tile at that point when displaying the message (empty tile with dirt is the tile in this example).

This has been the behavior in the latest experimental version (0.C-20238-g71a073f).

**Comment by CoroNaut** [comment] 2016-12-15 21:33
Why was this made a new issue? I feel like you could've fixed this bug along with the crashes that go along with it all in one.

**Comment by remyroy** [comment] 2016-12-15 21:40
If you feel like this is a duplicate of an issue, let me know which one and I'll close this one.

**Comment by CoroNaut** [comment] 2016-12-15 21:55
The one you fixed recently was caused by this problem in the first place.

**Comment by remyroy** [comment] 2016-12-15 21:59
If you are referring to #19769 and #19168 then I would disagree but I might be wrong. Can you share your knowledge with me?

**Comment by CoroNaut** [comment] 2016-12-15 22:56
It really isn't that big of a deal, but the way I think of it is that the crash was caused by the diagonal movement in the first place. The first bug was the diagonal movement, and further bugs discovered because of this bug was just stuff that shouldn't have been there in the first place. In other words, fixing the first bug would solve the rest that were caused by it. You really didn't need to fix the crashing portion if you could've fixed the diagonal movement and been done with the whole thing.

**Comment by remyroy** [comment] 2016-12-15 23:05
How do you know that the crash was caused by the diagonal issue?

**Comment by CoroNaut** [comment] 2016-12-15 23:15
Because you can only receive the crash when stepping onto a vehicle while doing this exact movement. If you can get the crash through other means, then it hasn't shown up yet and I don't think it ever would have because this is the only way it was caused. The other issues popped up solely because of this diagonal movement bug.

**Comment by remyroy** [comment] 2016-12-15 23:26
While testing for #19168, I was able to cause the crash without doing any diagonal movements just like it is shown on the screenshot. If you load that save game, you go to that cart, you grab it from the right side, you go right a few tiles and than up a few tiles, that will cause the crash without using any diagonals.

**Comment by CoroNaut** [comment] 2016-12-15 23:59
I was thinking more along the lines of: #19676, sorry it looks like i was talking about a different issue than what you were trying to fix.

**Comment by sethsimon** [comment] 2016-12-20 21:45
This is a duplicate of #18093.

**Comment by illi-kun** [comment] 2016-12-20 23:34
Thanks for the note. I've closed referenced issue since it seems thst current issue contains more info.

**Comment by kolsurma** [comment] 2017-03-06 06:23
This appears to no longer be applicable.

Can anyone else confirm the bug still exists?

**Comment by kevingranade** [comment] 2017-03-06 06:43
It's not, Coolthulu fixed it.

**Closed by kevingranade** 2017-03-06 06:43 UTC
Labels: Bug, Vehicle
