### ISSUE TITLE
Game crash upon bacth menu open

### ISSUE THREAD

**Issue by Jninja1** [CleverRaven/Cataclysm-DDA#60882] opened 2022-09-09 15:32 UTC
### Describe the bug

When I press the key to open batch crafting the game crashes. I have tested this in my current world and a brand new world with just the default mods (attached) and it still happens. It happened after the builds on 9-7. I don't know which version exactly, but it was with that day's builds.

### Steps to reproduce

1) Open craft menu
2) Press the key bound to batch crafting
3) Crash 

### Expected behavior

I expected the batch craft menu to open ,when I hit the key binding for it, and let me craft items in bulk.
I expected this because it has been a feature in the game for ages now and I rely on batch crafting for a decent amount of recipes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: 5986364 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Crash log added below. Zipped save file will be below the log:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 5986364
TYPE: St12length_error
MESSAGE: basic_string::_M_create
STACK TRACE:

  #0
    (dbghelp: @0x7ff767f6c83a[cataclysm-tiles.exe+0x22c83a]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x14022c83a),
    0x14022c83a    src/debug.cpp:1118    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff767f55e31[cataclysm-tiles.exe+0x215e31]), 
    (libbacktrace: log_crash+0x1d2@0x140215e31),
    0x140215e31    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc11/11.2.0/include/c++/sstream:917    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x140215e31    src/crash.cpp:85    log_crash
  #2
    (dbghelp: @0x7ff767f55fce[cataclysm-tiles.exe+0x215fce]), 
    (libbacktrace: crash_terminate_handler()+0xad@0x140215fce),
    0x140215fce    src/crash.cpp:164    crash_terminate_handler
  #3
    (dbghelp: @0x7ff768beeb16[cataclysm-tiles.exe+0xeaeb16]), 
    (libbacktrace: __cxxabiv1::__terminate(void (*)())+0x6@0x140eaeb16),
    0x140eaeb16    [unknown src]:0    [unknown func]
  #4
    (dbghelp: @0x7ff7691145d3[cataclysm-tiles.exe+0x13d45d3]), 
    (libbacktrace: std::terminate()+0x13@0x1413d45d3),
    0x1413d45d3    [unknown src]:0    [unknown func]
  #5
    (dbghelp: @0x7ff769127f08[cataclysm-tiles.exe+0x13e7f08]), 
    (libbacktrace: _cxa_throw+0x48@0x1413e7f08),
    0x1413e7f08    [unknown src]:0    [unknown func]
  #6
    (dbghelp: @0x7ff7694a4449[cataclysm-tiles.exe+0x1764449]), 
    (libbacktrace: std::__throw_length_error(char const*)+0x39@0x141764449),
    0x141764449    [unknown src]:0    [unknown func]
  #7
    (dbghelp: @0x7ff769093dda[cataclysm-tiles.exe+0x1353dda]), 
    (libbacktrace: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long long, char)+0x7a@0x141353dda),
    0x141353dda    [unknown src]:0    [unknown func]
  #8
    (dbghelp: @0x7ff767f4ec5c[cataclysm-tiles.exe+0x20ec5c]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)::{lambda(ui_adaptor&)#3}::operator()(ui_adaptor&) const+0x170a@0x14020ec5c),
    0x14020ec5c    src/crafting_gui.cpp:1244    operator()
  #9
    (dbghelp: @0x7ff7686eed92[cataclysm-tiles.exe+0x9aed92]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x1f4@0x1409aed92),
    0x1409aed92    src/ui_manager.cpp:411    ui_adaptor::redraw_invalidated()
  #10
    (dbghelp: @0x7ff767f52b7f[cataclysm-tiles.exe+0x212b7f]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)+0x2d71@0x140212b7f),
    0x140212b7f    src/crafting_gui.cpp:1501    select_crafting_recipe(int&, string_id<recipe>)
  #11
    (dbghelp: @0x7ff767f37534[cataclysm-tiles.exe+0x1f7534]), 
    (libbacktrace: Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)+0x2e@0x1401f7534),
    0x1401f7534    src/crafting.cpp:332    Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)
  #12
    (dbghelp: @0x7ff7680bf793[cataclysm-tiles.exe+0x37f793]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x2871@0x14037f793),
    0x14037f793    src/optional.h:108    ~optional
    0x14037f793    src/optional.h:109    cata::optional<tripoint>::~optional()
    0x14037f793    src/handle_action.cpp:2350    game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
  #13
    (dbghelp: @0x7ff7680c308d[cataclysm-tiles.exe+0x38308d]), 
    (libbacktrace: game::handle_action()+0xb49@0x14038308d),
    0x14038308d    src/handle_action.cpp:2966    game::handle_action()
  #14
    (dbghelp: @0x7ff767fba548[cataclysm-tiles.exe+0x27a548]), 
    (libbacktrace: do_turn()+0x540@0x14027a548),
    0x14027a548    src/do_turn.cpp:708    do_turn()
  #15
    (dbghelp: @0x7ff7692cef7d[cataclysm-tiles.exe+0x158ef7d]), 
    (libbacktrace: main+0x1cb8@0x14158ef7d),
    0x14158ef7d    src/main.cpp:784    main
  #16
    (dbghelp: @0x7ff767d413c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #17
    (dbghelp: @0x7ff767d414d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #18
    (dbghelp: BaseThreadInitThunk+0x10@0x7ff9c14b54e0[KERNEL32.DLL+0x154e0]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #19
    (dbghelp: RtlUserThreadStart+0x2b@0x7ff9c250485b[ntdll.dll+0x485b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

This is a clean world and the bug happens here too, break the wold. I don't care lol 

[Pikeview.zip.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9536739/Pikeview.zip.zip)

**Comment by Zireael07** [comment] 2022-09-09 15:42
dupe of #60878  which is likely a dupe of another issue

**Comment by Maleclypse** [comment] 2022-09-09 22:06
Closed as dupe

**Closed by Maleclypse** 2022-09-09 22:06 UTC
Labels: (S1 - Need confirmation)
