### ISSUE TITLE
Near-Sighted mutation overrides Telescopic Eyes CBM

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#23354] opened 2018-04-02 21:00 UTC
I installed the CBM a while ago.  I drank some mutagen and gained near-sighted as a result.  This probably shouldn't happen, since my eyes are bionic now.

**Comment by Night-Pryanik** [comment] 2018-04-03 02:47
Dupe of #21407.

**Closed by Night-Pryanik** 2018-04-03 02:47 UTC
Labels: Mutations, S3 - Duplicate
