### ISSUE TITLE
crash on successful recruitment of npcs

### ISSUE THREAD

**Issue by cerix2077** [CleverRaven/Cataclysm-DDA#30675] opened 2019-05-19 23:58 UTC
# Describe the bug

Game gives the error "Requested non-existing faction 'your_followers'" upon successful recruitment of an npc

# Steps To Reproduce

1. Speak with an NPC (one is nearby in the save file below)
2. Ask them to join you
3. if you succeed in persuading them you will get an error report then crash after continuing

# Expected behavior

Persuading an npc to follow you should not cause the game to crash

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3241-g5372d73
- Graphics Version: Tiles
- Mods loaded: [Dark Days Ahead [dda]]

# Additional context

Both devices i have the game installed on have experienced this crash, when i originally found the bug i tried doing a fresh install of the game however the bug persisted even when only using the base game with no mods whatsoever. The save below has a starting npc nearby that has the option to ask them to follow however spawning in an npc and asking them also causes the crash.

[CrashDebug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3195760/CrashDebug.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3195761/Save.zip)

**Comment by esotericist** [comment] 2019-05-20 00:05
Duplicate of #30674

**Closed** 2019-05-20 06:39 UTC
