### ISSUE TITLE
Unable to place Refugee Center on map

### ISSUE THREAD

**Issue by rishu73** [CleverRaven/Cataclysm-DDA#43457] opened 2020-09-04 14:49 UTC
Game version:
0.E-2 Stable
Operating system:
Windows 10 Professional
Tiles or curses:
Tiles
Mods active:
Dark Days Ahead
Disable NPC Needs
Crazy Cataclysm
Stats Through Kills
Dark Days of the Dead

### Expected behavior
When selecting the "Contact Us" option from the beginning Evac Center terminal, I expect the refugee center to be placed on the overland map.

### Actual behavior
On selecting "Contact Us", the game becomes inactive (not responding to Windows) for about 30 seconds, then this error message:
DEBUG    : Unable to find and assign mission target refctr_S3e.

 FUNCTION : cata::optional<tripoint> find_or_create_om_terrain(const tripoint&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 240

The terminal reports that the location of the refugee center is "96 UP_SE" and that the player log reports "Unable to add the address to your map" (I think).

The mission to find the refugee center is added, but in the save for the mission, the co-ordinates appear to be MAX_INT numbers.

This has happened for two characters in this specific world.

### Steps to reproduce the behavior
Create a new Evacuee character, access terminal, select "Contact Us".

**Comment by rishu73** [comment] 2020-09-04 14:50
Debug.log info:
-----------------------------------------
17:18:54.127 : Starting log.
17:18:54.127 INFO : Cataclysm DDA version 0.E-2
17:18:54.135 INFO : SDL version used during compile is 2.0.5
17:18:54.135 INFO : SDL version used during linking and in runtime is 2.0.5
17:18:54.354 INFO : Number of render drivers on your system: 4
17:18:54.354 INFO : Render driver: 0/direct3d
17:18:54.354 INFO : Render driver: 1/direct3d11
17:18:54.354 INFO : Render driver: 2/opengl
17:18:54.354 INFO : Render driver: 3/software
17:18:54.402 INFO : Active renderer: 0/direct3d
17:18:55.028 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
17:18:55.236 INFO : Language is set to: 'en'
17:18:56.366 WARNING : opendir [./mods/] failed with "No such file or directory".
17:19:07.016 WARNING : opendir [./save/Mount Bethel/mods] failed with "No such file or directory".
17:19:15.360 INFO : Loaded tileset: UNDEAD_PEOPLE
10:23:57.607 WARNING : opendir [./save/Mount Bethel/mods] failed with "No such file or directory".
10:23:59.625 INFO : Loaded tileset: UNDEAD_PEOPLE
10:27:42.544 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x620c16[cataclysm-tiles.exe+0x220c16]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x620c16),
    (libbacktrace: 0x620c16    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x6216aa[cataclysm-tiles.exe+0x2216aa]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x34a@0x6216aa),
    (libbacktrace: 0x6216aa    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x6245f6[cataclysm-tiles.exe+0x2245f6]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x76@0x6245f6),
    (libbacktrace: 0x6245f6    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0xad743c[cataclysm-tiles.exe+0x6d743c]), 
    (libbacktrace: ZL25find_or_create_om_terrainRK8tripointRK21mission_target_params+0x31c@0xad743c),
    (libbacktrace: 0xad743c    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0xad7606[cataclysm-tiles.exe+0x6d7606]), 
    (libbacktrace: ZN12mission_util21assign_mission_targetERK21mission_target_params+0x76@0xad7606),
    (libbacktrace: 0xad7606    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0xacac3f[cataclysm-tiles.exe+0x6cac3f]), 
    (libbacktrace: ZN13mission_start21reveal_refugee_centerEP7mission+0x1af@0xacac3f),
    (libbacktrace: 0xacac3f    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0xaaaef9[cataclysm-tiles.exe+0x6aaef9]), 
    (libbacktrace: ZN7mission6assignER6avatar+0x2a9@0xaaaef9),
    (libbacktrace: 0xaaaef9    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x5ac789[cataclysm-tiles.exe+0x1ac789]), 
    (libbacktrace: ZN16computer_session23action_emerg_ref_centerEv+0x469@0x5ac789),
    (libbacktrace: 0x5ac789    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x5aebaf[cataclysm-tiles.exe+0x1aebaf]), 
    (libbacktrace: ZN16computer_session3useEv+0x50f@0x5aebaf),
    (libbacktrace: 0x5aebaf    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x70a546[cataclysm-tiles.exe+0x30a546]), 
    (libbacktrace: ZN4game12use_computerERK8tripoint+0x126@0x70a546),
    (libbacktrace: 0x70a546    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x72c5b9[cataclysm-tiles.exe+0x32c5b9]), 
    (libbacktrace: ZN4game7examineERK8tripoint+0x1c9@0x72c5b9),
    (libbacktrace: 0x72c5b9    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x72d015[cataclysm-tiles.exe+0x32d015]), 
    (libbacktrace: ZN4game7examineEv+0x145@0x72d015),
    (libbacktrace: 0x72d015    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x772de6[cataclysm-tiles.exe+0x372de6]), 
    (libbacktrace: ZN4game13handle_actionEv+0x5b46@0x772de6),
    (libbacktrace: 0x772de6    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x74115f[cataclysm-tiles.exe+0x34115f]), 
    (libbacktrace: ZN4game7do_turnEv+0xb9f@0x74115f),
    (libbacktrace: 0x74115f    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: IMG_LoadWEBP_RW+0x67a6b8@0x17be938[cataclysm-tiles.exe+0x13be938]), 
    (libbacktrace: main+0x10e8@0x17be938),
    (libbacktrace: 0x17be938    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #16
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #17
    (dbghelp: BaseThreadInitThunk+0x14@0x7fff15ff6fd4[KERNEL32.DLL+0x16fd4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #18
    (dbghelp: RtlUserThreadStart+0x21@0x7fff1705cec1[ntdll.dll+0x4cec1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
src/mission_util.cpp:240 [cata::optional<tripoint> find_or_create_om_terrain(const tripoint&, const mission_target_params&)] Unable to find and assign mission target refctr_S3e.

**Comment by wapcaplet** [comment] 2020-09-24 21:22
Confirmed in 0.E-6177-g 9f4a1b841d using the save game attached to #44224

**Comment by rishu73** [comment] 2020-09-24 22:15
As glad I am to find I'm not crazy, the json reference doesn't make sense- I'm not using magiclysm, so I don't see what the black dragon lair has to do with it. Then again, I haven't gotten CDDA building locally, so what do I know....

**Comment by wapcaplet** [comment] 2020-09-24 22:21
> As glad I am to find I'm not crazy, the json reference doesn't make sense- I'm not using magiclysm, so I don't see what the black dragon lair has to do with it. Then again, I haven't gotten CDDA building locally, so what do I know....

Sorry for the confusion - the commit SHA 9f4a1b8 is just the latest commit on the master branch where I reproduced the bug (it's part of the experimental version number). The bug doesn't have anything to do with that commit, I just included it as a point of reference for others to reproduce it.

**Comment by rishu73** [comment] 2020-09-24 22:40
Yeah, I figured that and removed my kvetch, thanks for the explanation though. I'll try to get to making my system build a debut version and see if I can track it. FWIW my first character did a lot of far ranging to find "96_UP_SE" so maybe I used up all the space? I can post my save if that will help.

**Comment by Night-Pryanik** [comment] 2021-04-15 19:28
Closing as duplicate of #38993.

**Closed by Night-Pryanik** 2021-04-15 19:28 UTC
Labels: (S2 - Confirmed), <Bug>, Map / Mapgen
