### ISSUE TITLE
Advanced Invetory manager freak out when attempting to move liquids on ground

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40618] opened 2020-05-16 10:41 UTC
# Describe the bug

The game angrily throws up an error promo when you work up the nerve to make the insane attempt to scoop up some dirty water off the ground to move it somewhere else.

HOW DARE DO YOU NOT USE A MOP!?

Luckily, if you click on the ignore button that you can see in the screenshot, the game doesn't crash!

This might be fixed when the clean-up for #40607 is finished. I'm guessing that it's related to the dirty frozen water's weight and volume, which both is at zero. Before nested, you could hit frozen liquids with hammer and collect the pieces. 

# Steps To Reproduce

1. Pour a bottle out for the homies
2. Open advanced inventory manager 
3. Attempt to move dirty liquid from one square to another square
4. :thonk:

# Expected behavior

If I remember right, before the nested containers, dirty liquids on the ground wouldn't show up in the advanced inventory manager. 

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/82117532-70c89880-9725-11ea-91d7-16a7e0f05dff.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2191-g152f402 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

**Comment by wapcaplet** [comment] 2021-02-20 01:39
Appears to be fixed now - I cannot reproduce this in 0.E-9737-g511ddcb179. Instead, trying to move spilt liquids from AIM gives a popup "Spilt liquid cannot be picked back up.  Try mopping it instead."

![image](https://user-images.githubusercontent.com/238395/108578898-a7999380-72e1-11eb-97d2-35c39be3ce6c.png)

**Closed by wapcaplet** 2021-02-20 01:39 UTC
Labels: <Bug>, Inventory / AIM / Zones
