### ISSUE TITLE
Personal unload zone pulls ammo out of ammo belt without disassembling, effectively deleting linkages

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60835] opened 2022-09-07 20:39 UTC
### Describe the bug

A personal unload zone just pulls the cartridges out of a 5.56 ammo belt, leaving you with the cartridges and an empty, ammo belt item. The linkage items you would need to reload it effectively get removed from the game.

### Steps to reproduce

Unload ammo belt with personal sorting zone.

### Expected behavior

The belt gets disassembled into cartridges and linkages, like when you unload it manually.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: e2e7914 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by GuardianDll** [comment] 2022-09-07 21:02
Think duplication, but im too lazy to find an original one
/confirmed

**Comment by esotericist** [comment] 2022-12-01 01:29
duplicate of #60310

**Closed by esotericist** 2022-12-01 01:29 UTC
Labels: (S2 - Confirmed)
