### ISSUE TITLE
NPCs responding to sounds.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22710] opened 2018-01-07 23:25 UTC
Currently NPCs are effectively deaf, they only respond to visible threats ( see npc::assess_danger() ).

### Expected behavior
NPCs respond to sounds, generally treating them as unknown threats.  In particular, a large number of unknown sounds should result in the NPC fleeing.
### Actual behavior
NPCs are totally unaware of sounds.
### Steps to reproduce the behavior
(for convinience consider making player undetectable with debug menu).
Spawn a NPC near a wall.
Spawn one or more hostile zombies on the other side of the wall.
Observe the NPC not reacting to the zombies unless they break through the wall.

This is spawned from #21282, which raises valid issues, but is a bit too broad.  It was also derailed by an argument about implementation details.

**Comment by mlangsdorf** [comment] 2018-12-19 14:03
Current proposal:
All sounds get a description.  All sounds get a category which doubles as a priority, in increasing order:
0 - ambient/mood-setting/background noises like crickets chirping
1 - normal weather like wind and rain
2 - music 
3 - non-violent activity, like tuning up weapons
4 - movement like footsteps or vehicle noise
5 - alarm
6 - combat and violent activity, including most construction that involves hammering
7 - speech

Each turn, each NPC within MAPSIZE tiles of the player hears sounds via sounds::process_sound_markers() and npc::hear_sound().  They respond to the highest priority sound they heard, on the following criteria:
1. speech always merits a response
2. highest category sound from a position the NPC can't see
3. loudest sound in category
4. if the NPC can't respond to a sound, because they've got an unexpired complain_about timer or something, that sound is skipped

### Examples
NPC Joe hears NPC Jane talking to the PC in front of them, a dog fighting a zombie in front of him, a mi-go fighting a zombie around the corner, a car alarm from a car he can see, and the rain.
Joe checks to see if he can respond to the conservation and but has nothing to say, so he moves to the next sound.  He can see the zombie-dog fight and ignores it.  He says something about the zombie mi-go fight and sets an effect timer so he doesn't keep babbling about it.

On the next turn, the situation is the same.  This time, one of the words in the conversation triggered a phrase from Joe, so he says something and stops processing sounds.

On the third turn, the situation is the same.  Joe again checks the speech and has nothing.  He ignores the zombie-dog fight.  He already said something about the zombie-mi-go fight and skips that.  He can see the alarm.  He says something about the weather and sets an effect time.

On the fourth turn, the situation is the same.  Joe again checks the speech and has nothing.  He ignores the zombie-dog fight.  He already said something about the zombie-mi-go fight and skips that.  He can see the alarm.  He already said something about the weather, so he has nothing to say.

## Embellishments
This is mostly future work, but:
sounds get 2 descriptions, a generic one and a distinct one.  Each character individually hears sounds and divides them among silent, generic, or distinct based on volume, distance, and hearing abilities (Perceptions, traits, CBMs).  Generic sounds get generic descriptions.  Distinct sounds get specific descriptions, and the player can use Intelligence/traits to make educated guesses about the sources of distinct sounds they cannot see which might sometimes be wrong.

### Examples
Goofy D'Acute (Intelligence 4, Perception 16) and Smarty McDeaf (Intelligence 16, Perception 4) are in a lab, next to each other, and 25 tiles away from a shocker brute that is pacing behind a door.  At this distance, Goofy can only hear footsteps and Smarty can't hear anything, so Goofy might say "Hey, I hear footsteps."

Goofy and Smarty advance to 10 tiles away.  Now Smarty can hear the footsteps, but indistinctly, while Goofy can distinctly hear "heavy steps and an odd humming."  Goofy might say, "I hear a securibot over there" because Goofy guessed wrong about the meaning of the noise.

They continue advancing until they're next to the door.  Smarty can hear the footsteps distinctly and says "I hear a shocker brute."  The player, with Intelligence 10, Perception 10, can hear the distinct footsteps but has no guess as to the cause, so he'll have to decide whether to open the door or break out the control laptop.

**Comment by mlangsdorf** [comment] 2019-03-28 18:49
Closed by #28746 - there is still more to do, but NPCs in general respond to sounds and guards in particular will investigate combat noises.

**Closed** 2019-03-28 18:53 UTC
Labels: <Enhancement / Feature>, <Suggestion / Discussion>, NPC / Factions
