### ISSUE TITLE
Dragged bike at night, made a 'trail' of baskets as I walked.

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#34441] opened 2019-10-03 23:19 UTC
I was dragging a motorcycle I found into my residence. However, upon releasing the vehicle I noticed there were... after-images of the vehicle left behind. Not _all_ of the vehicle, but there were a trail of baskets where I had dragged the bike previously.

1. Drag vehicle at night (or drive one).
2. The vehicle makes a 'trail' of itself presumably due to map memory.

Expected behavior:

For a 'trail' to not appear when driving or dragging a vehicle. When driving a vehicle IRL you _know_ where your vehicle is on the road (spacial awareness). I know when I'm on the road I'm not struck with the notion that part of my car is left behind a ways back out of my immediate 'memory' as it were. Or what about dragging a bike? Even at night, someone rolling a bike alongside them for whatever reason wouldn't picture their bike making a 'trail' of bike parts as they walked. They would know the bike was whole and that they were dragging the _entire_ bike. The baskets were the prettier examples that remained after I had finished my task. The trail looked far more hideous earlier.

OS: Windows 10 Professional
Game Version: 0.D-8185-g1011e58
Graphics Version: Tiles
Mods loaded: No Flaming Weapons, No Survivor Armor, Disable NPC Needs

Screenshot: 
![Screenshot (134)](https://user-images.githubusercontent.com/44004977/66170329-d726fd80-e611-11e9-8a3d-fa4c46a6d4f2.png)

**Comment by ZhilkinSerg** [comment] 2019-10-04 07:50
Duplicate of #33545

**Closed by ZhilkinSerg** 2019-10-04 07:50 UTC
