### ISSUE TITLE
can't load the save file

### ISSUE THREAD

**Issue by terminaldweller** [CleverRaven/Cataclysm-DDA#61407] opened 2022-10-02 06:26 UTC
### Describe the bug

I cannot load my save anymore. I get this error message:
```
 An error has occurred!  Written below is the error report:
 -----------------------------------------------------------
 DEBUG    : Failed to read from "./save/somewhere2/#VHJleSAnUm9ndWUnIFNjaG5laWRlcg==.sav": Json index out of range of uint16_t

 FUNCTION : bool read_from_file(const ghc::filesystem::path&, const std::function<void(std::basic_istream<char>&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 433
 VERSION  : 5a82316
 -----------------------------------------------------------
 Press space bar to continue the game.
 Press I (or i) to also ignore this particular message in the future.
```
I either get this message or the game just terminates to the terminal without any messages.

### Steps to reproduce

I realize this is unhelpful but the steps involved are:
1. try to load this specific save
2. it wont load either with a crash to the terminal or the error message provided above

### Expected behavior

The game should load normally

### Versions and configuration

- OS: linux
- Game Version: 5a82316, experimental x64-2022-09-23-0555
- Graphics version: terminal
- Ingame langauge: english
- Mods loaded: 
```json
[
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "blazeindustries",
  "DinoMod",
  "megafauna",
  "deadly_bites",
  "extra_mut_scens",
  "cbm_slots",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "Tamable_Wildlife"
]
```

**Comment by akrieger** [comment] 2022-10-02 15:29
Sonuvagun.

**Comment by akrieger** [comment] 2022-10-02 15:47
I would still like to have the save game in hand so I can understand what array in it is getting so big but that PR should fix this.

**Comment by terminaldweller** [comment] 2022-10-02 15:50
I can't upload the save in its entirety since my internet connection can't really handle it but if you want specific files I could put them up somewhere.

**Comment by Zireael07** [comment] 2022-10-02 15:53
@terminaldweller: Can't you zip or tar the save?

**Comment by akrieger** [comment] 2022-10-02 15:58
Dropbox or Google drive possibly have better upload performance for slower connections.

**Comment by terminaldweller** [comment] 2022-10-02 15:59
The directory is  5.1GB.  Even when compressed this is still beyond anything my current internet connection can handle.

**Comment by akrieger** [comment] 2022-10-02 16:59
The saves/<your world name>/ directory is over 5GB large? Damn. Even when compressed to zip? Damn!

**Comment by terminaldweller** [comment] 2022-10-02 17:59
no, the gzipped version is 460MB. the not-compressed size of the save dir is 5GB. anyhow. I cant upload it right now. I'll keep trying. If I manage to upload it I'll post a link.

**Comment by terminaldweller** [comment] 2022-10-02 21:18
https://cargo.terminaldweller.com/somewhere.tar.gz

**Comment by ZhilkinSerg** [comment] 2022-10-03 12:40
Just the mentioned file VHJleSAnUm9ndWUnIFNjaG5laWRlcg==.sav could be enough for debugging.

**Comment by akrieger** [comment] 2022-10-03 14:16
Is it enough to load a save with just the .sav file? I didn't know. Regardless, there's two candidates for whats overflowing here.
1) known_traps seems to have just about 65k items. Seems it's just shy of 65536 though at 65289 by my math.
2) stats tracker event_counts avatar_enters_omt has 66,727 entries in it which seems to be the winner.

Both seems plausible to increase linearly with game size and the game has 3gb of map files in it (!). I have no idea if that's expected with a large or long game, but it is what it is.

**Comment by akrieger** [comment] 2022-10-03 14:48
Confirmed with my fix I can load the savegame.

**Comment by anothersimulacrum** [comment] 2022-10-03 18:09
Yoi could potentially swap it into an existing savegame, but that may not play too well.

**Comment by DeeUnderscore** [comment] 2022-10-03 20:14
I've also been experiencing this issue with a world. Mine's 4.9 GiB, and the `known_traps` array for the character in question has 65646 objects in it. I've also built the PR, and I can load the save with it fine.

**Comment by akrieger** [comment] 2022-10-03 21:42
Uhh forgot to put "Fixes 61407" in the PR, but it was just merged so we can close this.

**Closed** 2022-10-03 21:58 UTC
Labels: (S1 - Need confirmation)
