### ISSUE TITLE
Page Up/Down doesn't work at some places!

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14257] opened 2015-11-30 20:35 UTC
^As the title say - The places I have discovered so far:

* Crafting menu
* Third tab of character creation

**Comment by remyroy** [comment] 2015-11-30 20:48
This is probably partially a duplicate of #14209.

**Comment by drbig** [comment] 2015-12-01 17:41
It is. Also the last effort of making the UI consistent died of natural causes.

**Comment by OzoneH3** [comment] 2015-12-03 10:38
Fixed with #14256

**Closed by OzoneH3** 2015-12-03 10:38 UTC
Labels: Duplicate

**Comment by harald921** [comment] 2015-12-05 04:16
@OzoneH3 How is removing something "fixing"? That's like shooting your sick pet with a rifle and saying you cured it..
