### ISSUE TITLE
`<npc_name>` is shown instead of actual NPC name where inspecting stats of a follower

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#77170] opened 2024-10-19 19:48 UTC
### Describe the bug

When inspecting the stats of a follower, in an equivalent of `@` window, <npc_name> is shown instead of actual NPC name

### Attach save file

[Faalsville-trimmed.tar.gz](https://github.com/user-attachments/files/17447110/Faalsville-trimmed.tar.gz)

### Steps to reproduce

1. `C`hat with an NPC
2. `t`alk with Genia McGill
3. Press `b` to see her abilities
4. Press `t` to go to her traits
5. Observe `<npc_name>` instead of an actual NPC name in the description of the trait.

### Expected behavior

Show actual NPC name.

### Screenshots

![screenshot_2024-10-19-214031](https://github.com/user-attachments/assets/e930340a-ec2f-44ae-8eb5-462d232ed394)
![screenshot_2024-10-19-214026](https://github.com/user-attachments/assets/17015f5c-b2c1-4f08-9f8e-f62cec2f6631)
![screenshot_2024-10-19-214021](https://github.com/user-attachments/assets/796b8a53-6324-45f0-a1a3-31f51f84de95)
![screenshot_2024-10-19-214014](https://github.com/user-attachments/assets/05478925-417f-43d0-9537-c2f97a2e0895)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: f2a0326119f [64-bit]
- Graphics Version: Tiles
- Game Language: Polski <color_dark_gray>(52,3%)</color> [pl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Night-Pryanik** [comment] 2024-10-20 05:42
Duplicate of #69769.

**Closed by Night-Pryanik** 2024-10-20 05:42 UTC
Labels: (S1 - Need confirmation)
