### ISSUE TITLE
Crash on character creation

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31425] opened 2019-06-14 15:12 UTC
# Describe the bug

The character was random so no idea what it was. The core dump is truncated also (cata process has grown to 1,5GB).
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/l29ah/.config/cataclysm-dda/crash.log
VERSION: 0.D-4304-ge7ca42c3ce-dirty
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55f9790dbbfa]
	cataclysm(+0x634202) [0x55f9790c4202]
	cataclysm(+0x634668) [0x55f9790c4668]
	/lib64/libc.so.6(+0x396b0) [0x7f39b968d6b0]
	cataclysm(_ZNKSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE4findERKS5_+0x39) [0x55f978fb88a9]
	cataclysm(_ZNK4item8has_flagERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xd5) [0x55f9793037f5]
	cataclysm(_ZNK4item8goes_badEv+0x44) [0x55f979303ac4]
	cataclysm(_ZNK3map15has_rotten_awayER4itemRK8tripoint+0x3b) [0x55f9794a83fb]
	cataclysm(_ZN3map9actualizeEiii+0x337) [0x55f9794c4117]
	cataclysm(_ZN3map5loadnEiiib+0x4c9) [0x55f9794c4949]
	cataclysm(_ZN3map4loadEiiib+0xb8) [0x55f9794c59a8]
	cataclysm(_Z27get_changed_ids_from_updateRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x10f) [0x55f97952f97f]
	cataclysm(_ZN6recipe28add_bp_autocalc_requirementsEv+0xc9) [0x55f979995579]
	cataclysm(_ZN6recipe8finalizeEv+0x1ed) [0x55f97999606d]
	cataclysm(_ZN17recipe_dictionary17finalize_internalERSt3mapI9string_idI6recipeES2_St4lessIS3_ESaISt4pairIKS3_S2_EEE+0x31) [0x55f97999d891]
	cataclysm(_ZN17recipe_dictionary8finalizeEv+0xaa) [0x55f97999fcea]
	cataclysm(_ZN17DynamicDataLoader20finalize_loaded_dataER10loading_ui+0xcde) [0x55f9792bb25e]
	cataclysm(_ZN4game19load_world_modfilesER10loading_ui+0x52c) [0x55f9791ee31c]
	cataclysm(_ZN4game5setupEv+0xac) [0x55f979215d1c]
	cataclysm(_ZN9main_menu17new_character_tabEv+0xb9d) [0x55f97949d9cd]

	Attempting to repeat stack trace using debug symbols...
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(addr2line) failed
```

# Versions and configuration

 - OS: Gentoo
 - Graphics version: Terminal
 - Mods loaded: alternative map key

**Comment by Night-Pryanik** [comment] 2019-06-14 17:39
Seems like a duplicate of #31152.

**Comment by l29ah** [comment] 2019-06-14 20:49
Doesn't seem like a duplicate of #31152 to me as the backtrace is completely different.

**Comment by anothersimulacrum** [comment] 2019-06-14 20:54
That's probably because they're on Windows, which doesn't give readable backtraces.

**Closed** 2019-06-15 18:34 UTC
