### ISSUE TITLE
NPC "remembers" being asked to travel with a new player character

### ISSUE THREAD

**Issue by skybluecat** [CleverRaven/Cataclysm-DDA#35846] opened 2019-12-04 00:34 UTC
# Describe the bug

After a player character asked an NPC to travel together and is rejected, if a new character is created after the first one died and happens to spawn in the same shelter, the NPC will refuse when asked to travel together because "You asked me recently".

# Steps To Reproduce

Make a world that's kept after the player character dies. Spawn in a shelter and ask the NPC to travel with you and be refused. Get killed and create a new character. If the new character is spawned in the same shelter, ask the NPC again, and he/she will refuse because "You asked me recently".

# Expected behavior

The NPC should not care whether another dead PC wanted to travel together, when invited by a new PC.

Alternatively, the NPC can show he knows the new PC is a different person, but still refuse because he's annoyed by being invited too frequently by different people.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9802-gfadcffd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
[Millvale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3919351/Millvale.zip)

I attached a save file of a world where you seem to always spawn in the same shelter if you choose the default options (Evacuee and Survivor).

**Comment by Saint-of-Grey** [comment] 2019-12-04 00:41
Hard to say this is a bug, since keeping worlds after death isn't really fully supported. Or logical. There's all sorts of odd behavior involved when you do that.

**Comment by ZhilkinSerg** [comment] 2019-12-04 07:15
This is something we want to get fixed one way or another.

Duplicate of #26126

**Closed by ZhilkinSerg** 2019-12-04 07:15 UTC
