### ISSUE TITLE
Impossible to filter containers for liquids in AIM

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33079] opened 2019-08-09 14:21 UTC
`q:containing` works but doesn't include some containers like bottles and thermoses, `q:resealed` or `q:watertight` produce no results.

0.D-6273-g40119a34d4-dirty

**Comment by jeremyshannon** [comment] 2019-08-09 16:42
Looks like a dupe of  #28102

**Closed** 2019-08-09 16:54 UTC
Labels: <Bug>, Info / User Interface, Inventory / AIM / Zones
