### ISSUE TITLE
Map not remembering

### ISSUE THREAD

**Issue by xMyrkin** [CleverRaven/Cataclysm-DDA#31433] opened 2019-06-14 20:48 UTC
# Describe the bug

After load a save - visible world map not remembered. Except generated rivers.

# Steps To Reproduce

Create new world, run any way, save\load

# Screenshots

![2019-06-15 (1)](https://user-images.githubusercontent.com/51837242/59537301-3ea42a80-8f07-11e9-8857-fa628975fe70.png)

# Versions and configuration

Experimental build 9155
mods:
```
  "dda",
  "no_npc_food",
  "no_filthy_clothing",
  "magiclysm",
  "crt_expansion",
  "ew_pack",
  "FIC_Weapons",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "nw_pack",
  "makeshift",
  "craftgp",
  "DracoDogMod",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "Nechronica_Redux",
  "alt_map_key",
  "MMA",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "blazemod",
  "deoxymod",
  "Tanks",
  "Arcana",
  "necromancy",
  "sees_player",
  "No_Fungi",
  "Mutation_Changes",
  "safeautodoc",
  "speedydex",
  "Battery_Overhaul_Legacy_Mode",
  "more_classes_scenarios",
  "manualbionicinstall",
  "StatsThroughSkills"

**Comment by neitsa** [comment] 2019-06-14 20:53
Thanks for your bug report. It's probably a duplicate of #31391.

**Comment by ZhilkinSerg** [comment] 2019-06-14 23:27
Duplicate of #31391.

**Closed by ZhilkinSerg** 2019-06-14 23:27 UTC
Labels: (S3 - Duplicate)
