### ISSUE TITLE
Decrypting Science SD-Memory cards gives DEBUG items

### ISSUE THREAD

**Issue by kuhnchris** [CleverRaven/Cataclysm-DDA#36480] opened 2019-12-27 01:00 UTC
# Describe the bug
Decrypting contents of Science SD-Memory Cards found in underground science-labs contain uncraftable items

# Steps To Reproduce
(not sure, spawn in Science SD-Memory Cards and an e-ink tablet and decrypt them until you receive a DEBUG item)

# Expected behavior
Receive only craftable items

# Screenshots
![grafik](https://user-images.githubusercontent.com/761911/71495126-8576c380-284c-11ea-9fdf-a76f5cd14149.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10709-gd18fc5d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
-

**Comment by ZhilkinSerg** [comment] 2019-12-27 14:30
Duplicate of #33349

**Closed by ZhilkinSerg** 2019-12-27 14:30 UTC
