### ISSUE TITLE
Toggling map memory off doesn't work

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#27028] opened 2018-12-09 15:18 UTC
**Describe the bug**  
Map memory can't be turned off with { or any other key (if changed in the keybindings settings)

**To Reproduce**  
1. Press {
2. Nothing happens

**Expected behavior**  
Map memory is supposed to turn off (well the display anyway).

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-35090-g9d693be
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Filthy Clothing, Makeshift Items Mod, More Survival Tools, Urban Development, Boats, More Buildings, More Locations, Tall Buildings, StatsThroughSkills

**Additional context**  
The game does seem to react to the key being pressed as the colour of the last action in the log changes. The display for map memory just simply doesn't turn off as it should.
[Broken map memory.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2660655/Broken.map.memory.zip)

**Comment by woutershep** [comment] 2018-12-09 20:58
I mentioned the same in https://github.com/CleverRaven/Cataclysm-DDA/issues/26956

**Comment by Leland** [comment] 2018-12-09 21:57
Duplicate of #26956

**Closed by Leland** 2018-12-09 21:57 UTC
Labels: (S1 - Need confirmation), <Bug>, Map Memory
