### ISSUE TITLE
"could not find target vehicle for liquid transfer" on refilling thru siphoning

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32589] opened 2019-07-24 10:15 UTC
# Describe the bug

```
13:12:41.544 INFO : Cataclysm DDA version 0.D-5812-g4ea9105c26-dirty
13:12:41.804 WARNING : opendir [/home/l29ah/.local/share/cataclysm-dda/mods/] failed with "No such file or directory".
13:12:44.177 WARNING : opendir [/home/l29ah/.local/share/cataclysm-dda/save/2019.07.20/mods] failed with "No such file or directory".
13:12:48.944 ERROR : (error message will follow backtrace)
	cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55e347d7bf8a]
	cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x260) [0x55e347d7d900]
	cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6f) [0x55e347d7f89f]
	cataclysm(_Z12realDebugmsgIJPKcEEvS1_S1_S1_S1_DpOT_+0x32e) [0x55e347b934fe]
	cataclysm(+0x261a8a) [0x55e347954a8a]
	cataclysm(_ZNK13activity_type12call_do_turnEP15player_activityP6player+0x6b) [0x55e347badd7b]
	cataclysm(_ZN15player_activity7do_turnER6player+0xa2) [0x55e3486228e2]
	cataclysm(_ZN4game16process_activityEv+0xc0) [0x55e347e6fa50]
	cataclysm(_ZN4game7do_turnEv+0x551) [0x55e347eb9d11]
	cataclysm(main+0xcf9) [0x55e347af8119]
	/lib64/libc.so.6(__libc_start_main+0xeb) [0x7fcddf810ecb]
	cataclysm(_start+0x2a) [0x55e347b4be7a]

	Attempting to repeat stack trace using debug symbols...
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(addr2line) failed
Backtrace emission took 0 seconds.
src/activity_handlers.cpp:1432 [void activity_handlers::fill_liquid_do_turn(player_activity*, player*)] error in activity data: "could not find target vehicle for liquid transfer"
```

# Steps To Reproduce

1. Load the game.
2. Try siphoning fuel from the truck to the humvee.

# Additional context

[2019.07.20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3426184/2019.07.20.zip)

**Comment by Night-Pryanik** [comment] 2019-07-24 15:10
Duplicate of #28214.

**Closed by Night-Pryanik** 2019-07-24 15:10 UTC
