### ISSUE TITLE
The memorial file with Chinese character names prevents the game from creating new characters

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#65025] opened 2023-04-12 11:10 UTC
### Describe the bug

In the \memorial\{world name}\ folder of the game, if there is a json file with a Chinese file name (maybe the text in some other countries or regions will have the same effect),
It will cause the game to crash when creating a new character and entering the scene selection

### Attach save file

[安吉莉娜·哈里斯-2023-04-12-18-33-07.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11210557/-2023-04-12-18-33-07.zip)

### Steps to reproduce

1. Choose Chinese as the game language
2. Create a new character and randomly generate a name, which will result in a Chinese name
3. Death from some cause
4. New Game > New Character > Scene
5. Game crashes

### Expected behavior

The memorial file can be read normally and a new game can be played

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2364 (21H1)
- Game Version: c772e58 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    XEDRA 超进化 [xedra_evolved],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    更多变异场景 [extra_mut_scens],
    神话武术 [MMA],
    技能提升属性 [StatsThroughSkills],
    杀怪提升属性 [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11210629/crash.log)

**Comment by RenechCDDA** [comment] 2023-04-12 11:12
Duplicate of #64328

**Closed** 2023-04-12 13:42 UTC
Labels: (S3 - Duplicate)
