### ISSUE TITLE
cataclysm consumes 13% cpu doing nothing

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22375] opened 2017-11-07 03:35 UTC
Game version: master 
Operating system: gentoo linux
Tiles or curses: curses
Mods active: filthy clothes, disable npc needs, craftable gun pack, bright nights

No, there's no rain or snow, i don't provide any input, and don't see any animations anywhere, so i expect it to idle, but it actively eats my battery even more than a web browser (sic!) instead.

![screenshot](https://a.pomf.space/trsqcprubbkq.png)

**Comment by Treah** [comment] 2017-11-07 16:49
On my system it uses about 3.4 to 4.4 percent of the CPU when sitting idle. This system is a dual core system with hyper-threading. Its pretty modest for modern systems and is from 2013

**Comment by atealein** [comment] 2017-11-07 17:01
I'm OSX, curses version, currently idling on a raining screen (drizzle to be precise) and it takes between 2.8-3.7% CPU @ macbook pro early 2015.

**Comment by Coolthulhu** [comment] 2017-11-07 19:22
*nix curses versions have comparatively cheap redraw. It's tiles and win-anything versions that are slow.

**Comment by Coolthulhu** [comment] 2017-11-07 19:26
It seems that the game forces redraw if animations are enabled, even if there is nothing to redraw.

**Comment by Treah** [comment] 2017-11-08 22:52
@Coolthulhu 
Yep thats it game drops to 0% when I disable animations and nothing is going on.

**Comment by Broken-Admin** [comment] 2017-11-12 02:05
Close?

**Comment by kevingranade** [comment] 2017-11-12 05:06
This:
> It seems that the game forces redraw if animations are enabled, even if
there is nothing to redraw

Is a valid issue, can stay open to cover that.

**Comment by Broken-Admin** [comment] 2017-12-13 01:45
Issue is not animations? Is the game always redrawing? Is there a way we can check for snowing or smoke?

**Comment by mark7** [comment] 2019-02-01 20:32
I looked into this a while back (the idle CPU usage has been driving me up a wall), and IIRC there are really multiple issues here:

* First, the game redraws even when there are no animations present onscreen and even if animations are disabled.  The game should probably be completely asleep unless the kernel tells it that it actually needs to do something.  Right now it's got timeouts various places and is waking up to Do Things.  If playing audio, IIRC it needs to do some realtime work with sound, but Cataclysm appears to have multiple threads today, and even if not, my understanding from @kevingranade's comment in #16258 is that it *should* have a sound thread to permit to make blocking calls without preventing the audio system from working.

* Second, the game performs expensive redraws.  That is, it recomputes world state, lighting, etc, even when the only thing it is doing is drawing rain/snow, though it is impossible for any world states to change unless the player presses a key -- Cataclysm is entirely turn-based.  Now, there's something to be said for simplicity, and *maybe* the right fix here is really to make the world state computation cheaper and it's nice not to "mask" the costs there, but as a turn-based game, most frames drawn are really not going to be the result of the user hitting a key.  It'd be possible, at the cost of a some complexity for the very few animations that exist today, to just "register" that an animation is occurring and have a very lightweight redraw that just draws animated rain/snow, cosmetic stuff that has nothing to do with the world state, and to never run the world state recomputation then.

* Third, there's a surprisingly high amount of cost involved in the redraws themselves.  This happens even out of the game world; sitting on the title screen, for example, Cataclysm uses a surprising amount of CPU time, and I was idly poking at that today (lots of string allocations/deallocations in code related to terminal display that wind up adding up to a surprising amount of CPU time).

* Fourth, it might be possible to make the game world state computation cheaper.  Hypothetically, if it were so cheap to compute world state that the cost was simply irrelevant, it wouldn't matter if it were happening every game frame while the game is idle.  I'm less-interested in banging on this, because while it'd always be great to have fixes here, this is always a moving target; if someone adds a new feature, costs maybe show up, and it's hard to have one-off fixes "resolve" this easily.  Plus, @kevingranade seems to already be pretty active on this front; I see work on stuff like caching various things.

Reducing CPU usage is desirable even if a computer can "handle" the CPU hit, as for battery-powered devices (laptops, especially users running the Android build on mobile devices, where battery is always at a premium), CPU usage is equivalent to battery usage.  As a turn-based game, Cataclysm can have really low potential power consumption, and be really well-suited to those platforms, but as of today, some technical limitations.

**Comment by l29ah** [comment] 2019-05-19 13:55
The cycling occurs in `game::get_player_input` that uses quite a lot of various timeouts.

**Comment by esotericist** [comment] 2019-05-21 05:35
As a side note, with Mouse Edge Scroll enabled, the timeouts for `get_player_input()` can be *much* shorter than than the usual 300ms under some circumstances. Since that setting currently defaults to enabled, it's probably going to exacerbate any of the problems here.

**Comment by l29ah** [comment] 2019-08-30 12:25
It still does something, but much less than before.

**Comment by l29ah** [comment] 2020-10-23 03:31
Curiously, cataclysm stops its mindless CPU hogging routine if you `Esc`ape into the menu, open an `i`nventory, `/`AIM or otherwise make it wait for your input at anything but the main game screen.

**Comment by mark7** [comment] 2020-10-23 15:38
@l29ah Yeah, that's because when it's showing the game screen, it's constantly drawing N FPS.  While those menus are up, it doesn't.  What's worse, each time it draws a frame, it recomputes the game state -- lighting and so forth.

It'd be possible to change it to only redraw when a resize/repaint/keypress happens (plus a few cases where multiple redraws happen without keypress, like crafting), as long as animations aren't happening.  It'd also be possible, at the cost of some complexity, to do the world state computation and record that, and just figure out where an animation needs to happen and then just have a lightweight loop that draws the animations.

I talk about that in #22375.

**Comment by BrettDong** [comment] 2021-01-10 02:26
Does CPU usage improve if you turn off SCT animation?

**Comment by Night-Pryanik** [comment] 2022-08-13 15:38
I'm closing this for now, on 0.F-10563 on my rig in idle mode the game consumes ~1.5% of CPU. If this is still an issue, ping me to reopen.

**Closed by Night-Pryanik** 2022-08-13 15:38 UTC
Labels: Code: Performance, (P5 - Long-term), old issue - still valid?

**Comment by mark7** [comment] 2023-05-28 04:38
>on my rig in idle mode the game consumes ~1.5% of CPU.

In HEAD on current master, for a non-RELEASE build, it's keeping about a third of one of my desktop's cores hot while idle using opengl.

I took another look.

According to a quick profile generated while walking around, the largest single thing being done during idle is regeneration of the sunlight cache.  This should really require the game world to change to need regeneration rather than need to be done each redraw.   This is presently being done every frame due to what claims to be a temporary hack in `game::draw()`:

     //temporary fix for updating visibility for minimap
     ter_view_p.z = ( u.pos() + u.view_offset ).z;
     m.build_map_cache( ter_view_p.z );
     m.update_visibility_cache( ter_view_p.z );

The description for 976ec586292, which added this regeneration back in 2016, makes it sound like the problem was that the visibility data needed to be regenerated prior to drawing the minimap:

    Add a cache refresh before drawing pixel minimap, draw_ter reordering
    removed an implicit refresh.

...but when I remove the above code, so that the map caches are not regenerated every redraw, the minimap appears to work without problems on current master, at least for the cases I tested (loading a new game, moving and having visibility reflect current position, including across z-levels), using animations both on and off.  The minimap doesn't appear to be drawn by the game when peeking, so it's not that.  Might be that the bug that this was intended to work around was subsequently fixed.

With those lines of code removed, the sunlight cache only gets regenerated when I'm walking around and new map areas are being loaded, which is the behavior that I'd expect.  I see about a 17% reduction in CPU usage while idle.
