### ISSUE TITLE
Android contextual tab key missing in trade dialogue

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#62757] opened 2022-12-17 01:23 UTC
### Describe the bug

Without a tab key to swap panes in Android, I can't give an npc any items.

### Steps to reproduce

Open trade with friendly npc.
No tab key available.

### Expected behavior

Tab key shows up in quickbar, as Android soft keyboards don't have a tab key either.

### Screenshots

![Screenshot_20221216-102141_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/26992604/208216204-e300eb67-8489-46db-aec6-b8e86c9012bc.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 11; Incremental: 2202112156; 
- Game Version: 45e6e56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment] 2022-12-17 02:29
Duplicate of #56885

**Closed** 2022-12-17 02:34 UTC
Labels: (S1 - Need confirmation), OS: Android
