### ISSUE TITLE
NPC and UPS weapons don't interact well

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#19545] opened 2016-11-29 19:11 UTC
trying to trade with an NPC while holding a UPS powered weapon in your inventory generates the following error:
> none is defaul ammo for `weaponname`, but lacks ammo data
> FUNCTION: double player:gun_value(const item&, long int) const
> FILE: src/ranged.cpp
> LINE: 1892

moreover, even if one shares them a ups wepon such as a V29 laser pistol and fully charged ups, produces the same error and the weapon will never be wielded ( i guess lack of value doesn't allow it to be included in priority selection choice to wield )

**Comment by saneman226** [comment] 2016-11-30 01:03
There are several problems with UPS technologies, such as crafting with a UPS soldering iron, or the problem where UPS makeshift welders are counted as an ingredient when it shouldnt be. Quite a few UPS modded tools and weapons have bugs at the moment. #19491 . It seems the number is growing with recent patches.

**Comment by mugling** [comment] 2016-11-30 01:04
Duplicate of #19507

**Closed by mugling** 2016-11-30 01:04 UTC
Labels: Duplicate, NPC
