### ISSUE TITLE
Allow the player to choose which vehicle battery to install

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19860] opened 2016-12-27 03:35 UTC
At present, the player cannot choose between different car batteries of different charge levels when installing a battery into a vehicle. It would be less annoying to swap batteries if they could be swapped using a UI similar to the gun magazine screen.

**Comment by 1skandar** [comment] 2016-12-27 09:32
This is true of any part you install on a vehicle. Say I am carrying 4 solar panels and 2 are damaged and 2 are not it may as well be random which is installed.

More amusingly, if I have a welder with a battery compartment mod using a medium storage battery it is entirely possible to install that medium storage battery rather than the one in my inventory.

In general, a workaround is to take several steps away from the vehicle and drop all the duplicates, leaving only the one you want to install. It's clumsy and frustrating, but it works.

**Comment by keyspace** [comment] 2016-12-27 17:06
Duplicate of:  #11706

**Closed** 2016-12-27 21:15 UTC
