### ISSUE TITLE
Crafting any object results in a "not edible" message and 0% progress.  Gamebreaking

### ISSUE THREAD

**Issue by Rayeneth** [CleverRaven/Cataclysm-DDA#41192] opened 2020-06-09 14:38 UTC
Game version:
0.E-3074-gd071e91
Operating system:
Win10
Tiles or curses:
None
Mods active:
Default
### Expected behavior
Crafting results in object crafting
### Actual behavior
Crafting is interrupted immediately and a message "not edible" appears. 
### Steps to reproduce the behavior
Have something non edible or non existent in  auto drink/eat pile.

**Comment by hexagonrecursion** [comment] 2020-06-23 14:13
Duplicate of: #41141? Fixed in #41316

**Closed** 2020-06-23 16:45 UTC
Labels: <Bug>, Crafting / Construction / Recipes
