### ISSUE TITLE
load vehicle part as terrain

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#40411] opened 2020-05-10 09:22 UTC
# Describe the bug

load vehicle part as terrain
# Steps To Reproduce

1. find or debug a vehicle
2. move into the vehicle and walk around
3. it happened at every step

# Screenshots

![2020-05-10 165546](https://user-images.githubusercontent.com/22638873/81495245-8c750e80-92e1-11ea-94b0-0c6da80bb738.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1970-g3278b58 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-05-10 10:39
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40385

**Closed by ZhilkinSerg** 2020-05-10 10:39 UTC
