### ISSUE TITLE
Crash to Desktop when crafting any canned food

### ISSUE THREAD

**Issue by BloodyDaft** [CleverRaven/Cataclysm-DDA#28791] opened 2019-03-18 04:23 UTC
**Describe the bug**  
Crafting any soup that ends in a sealed glass jar of [soup name] or a canned tin of [soup name] results in a crash to destkop.

**To Reproduce**  
1. Obtain the materials to make yummy woods soup in a jar or tin (not the recipe that prompts a menu with consume, pour into a container, or dump on ground).
2. Craft the soup with the recipe that cans it (or jars it)
3. Watch as the fabric of reality comes crashing down around you.

**Expected behavior**  
A sealed glass jar or tin of [any soup] to appear in my inventory or be dropped b/c I carry too much weight.

**Screenshots**  
Copy/Pasta of the Crash.Log is attached.

**Versions and configuration(please complete the following information):**
 - OS: Lubuntu 18.04
 - Game Version: 0.D-576-g6d4a4baff1
 - Graphics version: Tiles (I think. it's got pictures not ASCII)
 - Mods loaded: from my "mods.json" - More_Survival_Tools; Medieval_Stuff; more_locations; deoxymod; blazemod; Tanks; novitamins; Slow_Zombies; StatsThroughSkills

**Additional context**  
I compiled about 24 hours ago and then maybe 8 hours ago (to the version listed above) to try to resolve the issue. I'm wondering if it's related to the empty canister issue someone else mentioned, but I'm NOT reloading the cannister or jars. I'm crafting into a full tin or jar and getting a crash to desktop, not an ignorable error/bug.

This is an OLD save that's made it through MANY code changes. I'm in a relatively new Overmap area.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2976357/crash.log)

**Comment by anothersimulacrum** [comment] 2019-03-18 04:30
Duplicate of #28739

**Closed** 2019-03-18 04:38 UTC
