### ISSUE TITLE
Mention capacity limits on holsters/harnesses etc.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18142] opened 2016-08-28 22:26 UTC
As mentioned by Pantalion on the forums, it would be nice if holsters and harnesses such as for example the survivor harness mention what kind of weapons of what exact size they can use. Right now it is a bit annoying.

**Comment by Coolthulhu** [comment] 2016-08-29 00:53
Size is easy, kind of weapon isn't, since they're checked by flags.

**Comment by Soyweiser** [comment] 2016-08-29 13:04
Hmm, so there isn't an easy way to convert those flags to text. Damn.

**Comment by Coolthulhu** [comment] 2016-08-29 13:22
The easiest, non-hardcoded but still "proper" way would be to pair flags to descriptions somewhere.
Something like a simple json-loaded structure with flag id as id, item description field and a holster description field.

This would have one big advantage: it could be used to add jsonized descriptions for many item flags from that gigantic `if( has_flag( x ) )` in `item.cpp`. For example, flags like "FIT", "VARSIZE", "BELTED", "POCKETS", "FANCY", "DOUBLE_AMMO" (ones with no conditions).

**Comment by Treah** [comment] 2016-10-12 19:20
Is this why I cant holster a revolver for some reason? I mean the gun is only 250ml and the holster is 500ml so im confused as to why i get "no item on hand" message when attempting to do this? This seams like a bug not an interface issue.

**Comment by Zireael07** [comment] 2016-10-13 07:34
@Treah: Holsters/harnesses work by flags not by volume.

**Comment by Maleclypse** [comment] 2020-07-16 04:26
Is this resolved by player visible pocket data or are these details hidden in the json?

**Comment by wapcaplet** [comment] 2021-02-16 03:49
Not reproducible in 0.E-9681-g2cca4d658c. All containers now indicate their total volume, weight, and length capacity. For example here is the survivor harness, indicating 12.50 L total capacity in 4 pockets:

![image](https://user-images.githubusercontent.com/238395/108015970-ad843180-6fce-11eb-8757-e4979e2cc4e3.png)

Restrictions such as belt clips are also indicated; here is a firefighter belt, which can hold tools as long as they can clip onto a belt loop:

![image](https://user-images.githubusercontent.com/238395/108016239-45821b00-6fcf-11eb-8675-703808d326a2.png)

Containers with item restrictions (such as gun magazines) indicate what kind of ammo they can contain:

![image](https://user-images.githubusercontent.com/238395/108016098-f936db00-6fce-11eb-966e-370b462157ab.png)

This appears to be resolved now. Closing.

**Closed by wapcaplet** 2021-02-16 03:49 UTC
Labels: (P5 - Long-term), Info / User Interface
