### ISSUE TITLE
Can not remove vehicle engine

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#55469] opened 2022-02-17 21:22 UTC
### Describe the bug

My character has strength 13 but cannot remove enhanced electric motor which needs strength 10

### Steps to reproduce

1. Make character with wrench, strength > 10 and mechanic skill 2
2. Find vehicle with enhanced electric motor (for example electric sports car)
3. Try to remove engine

### Expected behavior

I expected vehicle part to be removed

### Screenshots

![Screenshot_20220217_225359](https://user-images.githubusercontent.com/2695146/154572281-058deea3-a91f-4a6d-94fe-7ae9677a50e5.png)
![Screenshot_20220217_225421](https://user-images.githubusercontent.com/2695146/154572311-aa7b8476-e9e5-4a22-b957-edf1b5371ebf.png)

### Versions and configuration

- OS: Ubuntu 20.04
- Game Version: Cataclysm-DDA experimental build 2022-02-17-0641
- Graphics version: Tiles
- Ingame language: Russian
- Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "blazeindustries",
  "package_bionic_professions",
  "magiclysm",
  "crt_expansion",
  "crazy_cataclysm",
  "MMA",
  "extra_mut_scens",
  "No_Rail_Stations",
  "no_fungal_growth",
  "speedydex",
  "StatsThroughSkills"
]

**Comment by haveric** [comment] 2022-02-17 21:25
This looks to be a duplicate of #54383 

What's strange is that I tried testing this issue last night and could not replicate it, so there must be something specific triggering it.

**Comment by stasalcatraz** [comment] 2022-02-18 06:34
Here is my saves if you need tests
[Вадо.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8094682/default.zip)

**Closed** 2022-03-10 17:22 UTC
Labels: Vehicles, Crafting / Construction / Recipes
