### ISSUE TITLE
Strange Helmet Liner issue

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#17753] opened 2016-07-20 06:05 UTC
If you have a Helmet liner on, you can't put an army helmet on on top of it.

However, if you take the Helmet Liner off then put the army helmet on, you can then put the helmet liner on.

This might work for other headgear.

**Comment by flitvious** [comment] 2016-07-20 13:09
Encountered this one with army helmet and survivor hood. 

This "head encumbrance adds nothing, but limits how much you can stack" mechanic is strange. In my opinion, dodge, perception or move cost penalty would be better. It would also put a stop to this head gear combination game: "balaclava first, then survivor hood, then army helmet... yeah, it worked!". And another variant of it: "Helmet and hood can't stack. Maybe I'll try to combine helmet with cowboy hat".

**Comment by illi-kun** [comment] 2016-11-11 03:10
Closing as duplicate of #12897 since current issue has the same reason - inconsistent checking of cap.

**Closed by illi-kun** 2016-11-11 03:10 UTC
Labels: Bug, Duplicate
