### ISSUE TITLE
Insane mob spawning

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#26683] opened 2018-11-14 12:22 UTC
**Describe the bug**  
In the area of apartment towers, an area that was clear previously, there are huge mob groups appearing

**To Reproduce**  
Not sure how to reproduce this, I just wandered off, and when I came back the screenshots happened.

**Expected behavior**  
Not to have huge groups of mobs appearing from thin air. The screenshots are all of areas that were very empty of mobs previously.

**Screenshots**  
![image](https://user-images.githubusercontent.com/1698993/48482240-1e19d200-e84b-11e8-8144-14b6dd3a53fb.png)

![image](https://user-images.githubusercontent.com/1698993/48482144-dbf09080-e84a-11e8-9f1e-4499fa40af0e.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Build 8167

**Additional context**  
I have spawn density set to 5, no wander spawns

**Comment by Zireael07** [comment] 2018-11-14 12:30
Default spawn density is 1 IIRC so if you have it set to 5 expect more spawns...

**Comment by Chazoshtare** [comment] 2018-11-14 12:42
No, there is definitely something wrong with spawns currently. My spawn density is set to 1 and I got 5 mi-gos next to each other, around 60 Firefighter Zombies next to a Fire station and 10 eyebots appearing from a single alarm.

**Comment by Zetsukaze** [comment] 2018-11-14 12:55
Yes, I do expect more spawns, obviously. I have been playing with that setting for quite some time, so I do know what happens usually. I don't expect to see 30+ of weasels, ants and zombies each to appear out from nowhere in an area I just walked away from less than 5 minutes ago.

**Comment by Trokinos** [comment] 2018-11-14 13:06
It seems very similar to my problem with today's build with huge hordes (i have hordes disabled and no zombie revival) suddenly spawning all over a city that has been cleared from the undead threat for month.

**Comment by UNOwenWasMe** [comment] 2018-11-14 14:59
Having the same issue, when I go back to a build from a day ago, the insane mob spawning stops. The bug is for both zombies respawning and animals, huge hordes of dogs and turkeys.

**Comment by l29ah** [comment] 2018-11-14 15:50
![woof](https://dump.bitcheese.net/files/zyhecyn/screenshot-pitbull.png)

**Comment by Josephos** [comment] 2018-11-14 17:31
Can confirm this issue.
Might be related to: #26106

**Comment by boydkr** [comment] 2018-11-14 18:46
Confirmed, a few more grackens than I would have expected from a Mi-go / Gracken spawn point:

![too_many_gracken](https://user-images.githubusercontent.com/5815066/48504849-57325200-e80b-11e8-8e01-bf5c83ef5751.PNG)

**Comment by kevingranade** [comment] 2018-11-14 22:21
I strongly suspect the cause of this is the refactoring of Creature tracker, specifically I suspect there is a workflow that is calling creature_tracker::remove() or creaure_tracker::update_pos() with shifted coordinates, meaning it fails, then a duplicate of the creature is added at the new position.

**Comment by kevingranade** [comment] 2018-11-14 23:18
Looks like the change to remove_monster() is the cause, it looks up monsters by coordinates instead of speed because it's faster, but that makes it fail when the monster coordinates have been shifted before calling it, which happens when game::shift_monsters() -> game::despawn_monster() is triggered.

**Comment by kevingranade** [comment] 2018-11-15 02:20
Should be fixed by the revert (though theres no way to delete the monster clones automatically).

**Closed by kevingranade** 2018-11-15 02:20 UTC
Labels: (P2 - High), (S2 - Confirmed), Monsters, Spawn

**Comment by Orange01gaming** [comment] 2018-11-15 03:30
I am seeing the same thing.
