### ISSUE TITLE
Invalid effect, ID: stim_overdose

### ISSUE THREAD

**Issue by Xindii** [CleverRaven/Cataclysm-DDA#32692] opened 2019-07-28 13:14 UTC
# Describe the bug

After accidentally taking two hits of cocaine, I'm harassed endlessly by the console with the error message 'invalid effec, ID: stim_overdose

Of course, none of the symptoms of stim overdose happens either. I get the +speed and perception, but no drawbacks like it used to have, mainly dying of overdose.

# Steps To Reproduce

1. Make a player.
2. Spawn shedloads of cocaine, cola, or other stims, then consume them.
3. Enjoy the spam.

![stim bug](https://user-images.githubusercontent.com/1896299/62007152-01f06380-b142-11e9-8288-2c398daff843.png)

Alternatively, load up the included save file below!

# Expected behavior

I expected my character to suffer the effects of, you know, lethal dosages of stims.

# Versions and configuration

Running win 7 on latest build.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    EXTENDED_BUILDINGS [ext],
    Urban Development [Urban_Development],
    Stats Through Kills [stats_through_kills],
    Safe Autodoc [safeautodoc]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3439195/debug.log)

Save File: 
[CDDA stim save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3439196/CDDA.stim.save.zip)

**Comment by anothersimulacrum** [comment] 2019-07-28 14:47
Duplicate of #32590

**Closed** 2019-07-28 16:16 UTC
