### ISSUE TITLE
'Spear Proficiency' proficiency is unobtainable despite having a practice recipe for it.

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#69354] opened 2023-11-13 20:56 UTC
### Describe the bug

'Spear Proficiency' is currently unobtainable. The practice recipe doesn't advance it even if you have the 'Spear Familiarity' proficiency. In addition, in the proficiency screens, 'Spear Familiarity' doesn't list any other proficiencies it 'leads to'.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a long stick and a training dummy, place it somewhere. 
2. Learn the 'Spear Familiarity' proficiency by doing the 'Spears (beginner)' practice recipe (or debug-learn it).
3. Do the 'Spears (intermediate)' practice recipe for a few hours. Check the proficiency tab. Note that no progress was made in 'Spear Proficiency'. 

### Expected behavior

After earning 'Spear Familiarity', you are able to earning 'Spear Proficiency', both manually and with the practice recipe specifically for that purpose.

### Screenshots

The practice screen lists 'Spear Proficiency' as red, despite having 'Spear Familiarity', making the practice do nothing.
<img width="698" alt="Screenshot_1" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/f5fba28a-dbb9-446f-9da1-576bbe962fa1">

In the proficiency screen, Spear Proficiency does not advance no matter how much you practice or melee with a spear. In addition, Spear Familiarity doesn't have a 'leads to' entry like the other proficiencies that lead to each other do. This is probably why this issue exists.
<img width="1066" alt="Screenshot_2" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/4de3937d-8eca-486d-93cb-44422c0ef19f">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d39ddd6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

Weapon proficiencies and their recipes seem to have a bunch of bugs when used in practice.

**Comment by Termineitor244** [comment] 2023-11-14 01:31
I just checked in [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/3afb7dfaaeed7f7c3dd16fe9a78597efedc1d61f/data/json/proficiencies/melee_weapons.json#L478) and the problem seems to be from a typo (**spear** rather than _spears_), easy fix. /confirmed, I will try and fix it.

**Closed** 2023-11-14 04:10 UTC
Labels: (S2 - Confirmed)
