### ISSUE TITLE
Ridiculus Log sizes

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#19456] opened 2016-11-25 14:04 UTC
My log files are blowing up like no tomorrow. They are growing with about 160000 (YES REALLY) lines per SECOND. All with this message: 
`16:46:16.791 SDL : src/cata_tiles.cpp:1803: SDL_RenderCopyEx() failed: SetTexture(): INVALIDCALL`

I'm  running build 5885 with win x64 SDL tiles. 
Downloaded from here: http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/

This is causing real issues for me since I run it on a USB drive to keep my cata playing portable. I can only play for an hour or so before I run out of space. My last play was about half an hour and that made a log file of 5.2GB

**Comment by DanmakuDan** [comment] 2016-11-25 15:22
Are you running in fullscreen or borderless? Also, have you tried turning on software rendering, and checking if the logs are still increasing?

**Comment by mutability** [comment] 2016-11-25 17:01
This is SDL reporting an underlying direct3d error. Software rendering will likely stop it (and go slow..)

**Comment by DanmakuDan** [comment] 2016-11-25 17:47
I remember one of these errors happens when a Windows version of the game is alt-tabbed from fullscreen mode, the renderer (DirectX) can lose control of the screen until the window is active again.

**Comment by mutability** [comment] 2016-11-25 18:18
It would probably make sense for debuglog to deduplicated repeated messages a la syslog

**Comment by illi-kun** [comment] 2016-11-27 08:55
This issue is labeled as a ```bug``` due to SDL issue and as an ```enhancement``` due to request of debug log improvements.

**Comment by DeadLeaves** [comment] 2016-11-30 01:26
A temporary fix I figured out is to make the log file read only and it will remain empty. At least this works in windows.

**Comment by Leland** [comment] 2017-05-02 20:44
Can anyone reliably reproduce this?

**Comment by Leland** [comment] 2017-05-24 18:58
Closing due to lack of reproduction – if this is still an issue for anyone, please make a _new_ issue for visibility. Log files growing that quickly is definitely a concern.

**Closed by Leland** 2017-05-24 18:58 UTC
Labels: Bug, Enhancement
