### ISSUE TITLE
Tossing bullets in a fire

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#11532] opened 2015-03-11 03:45 UTC
I had this thought while using rat shot as sharpnel mines:
Shouldn't throwing bullets in a campfire actually produce two pieces of shrapnel (the projectile and the casing) instead of just one. I mean, without a chamber to hold the casing shouldnt it just go flying away on a random direction as well? Physics' laws and that.

Pretty unimportant, but would make a decent "the devs thought of everything" moment.

**Comment by aierce** [comment] 2015-03-11 09:49
actually no, only the casing flies away (at non-lethal speed that can still bruise)

mythbusters did an episode on this

**Comment by KA101** [comment] 2015-03-12 00:58
So the problem is that bullet shrapnel is too lethal, I take it?

**Comment by John-Candlebury** [comment] 2015-03-12 02:48
Well I woulnt say that, burning ammo in a fire is already a pretty high level desperation attack. No real need to nerf it from my point of view.

I was just wondering if (bigger) bullets exploding should make two units of shrapnel instead of one

**Comment by maxmurder** [comment] 2015-03-12 17:40
The reason only the casing flies away is because it has significantly less mass than the bullet. I would assume that higher caliber ammunition would have less chance of launching the bullet, as the bullet has even more mass relative to the casing. I could see shotgun shells possibly firing their ordinance when heated/burned, but IRL they would likely melt before going off or just blow apart when thrown in a fire.

**Comment by Rivet-the-Zombie** [comment] 2015-03-12 17:43
>I could see shotgun shells possibly firing their ordinance when heated/burned, but IRL they would likely melt before going off or just blow apart when thrown in a fire.

From RL experience I can tell you that they go **pop** really loud and the halfway-melted case flies out of the fire.

**Comment by mugling** [comment] 2016-03-10 14:42
How and when ammo should apply `COOKOFF` will be addressed in #15239

**Closed by mugling** 2016-03-10 14:42 UTC
Labels: Balance
