### ISSUE TITLE
Zombie slaves (zlaves) don't follow across z-levels

### ISSUE THREAD

**Issue by TimeIsEndless** [CleverRaven/Cataclysm-DDA#26328] opened 2018-10-20 09:40 UTC
**Description**
Zombie slaves can't go up or down Z-levels

**To Reproduce**  

1. Create a zombie slave in a basement or near stairs.
2. Wait for it to revive and go upstairs.
3. The zombie will be stuck on the Z-Level it was originally created on.

**Expected behavior**  
I kinda expected them to follow you over Z-Levels since they follow you and normal zombies also follow you up and downstairs.

**Screenshots**  
1. https://i.imgur.com/09nno0w.png
Heres a screenshot but it should be kinda self explanatory. Im just disappointed that this zombie i carried to my basement and chopped up 3 times now will be forever stuck in it.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-33446-g3bd799b
 - Graphics version Tiles
 - Mods loaded: Probably not relevant.

**Comment by Night-Pryanik** [comment] 2018-10-20 10:12
Rope not saving their condition issue is a duplicate of #25748.

**Comment by TimeIsEndless** [comment] 2018-10-20 10:15
Alright thanks I didn't even know you could tie animals down so I only searched for bugs related to zombie slaves

**Comment by Leland** [comment] 2018-12-04 18:16
@TimeIsEndless updated your issue description to remove the other issue mentioned. If you need to find the previous text, it's saved as an edit.

<img width="281" alt="screen shot 2018-12-04 at 1 15 51 pm" src="https://user-images.githubusercontent.com/714017/49463574-cb3a9700-f7c6-11e8-9197-06282a3ce1f5.png">

**Comment by Yunatan** [comment] 2019-05-07 20:32
> (S1 - Need confirmation)

I confirm that this bug reproduces and needs fixing, today I was forced to leave my zlave to forever rot in a DnD basement.

**Closed** 2019-05-10 07:36 UTC
Labels: (S2 - Confirmed), <Bug>, Monsters, Z-levels
