### ISSUE TITLE
Getting blinded by boomer booms when I wasn't before

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60229] opened 2022-08-17 01:01 UTC
### Describe the bug

I've killed tons of boomers in melee before usually while wearing safety glasses or better. However very recently I've found that doing so makes me blind every time, and currently I am wearing a firefighter PBA mask on top of the Protective Lenses CBM. That's a ton of environmental protection for the eyes which I assumed was what protected you from being blinded. Is this not the case, am I misunderstanding something? Or did something go awry?

### Steps to reproduce

1. Punch boomer till it explodes.
2. Observe blindness no matter how much eye protection you have.

### Expected behavior

I don't know exactly how this mechanic is supposed to work but it seemed to suddenly change very recently as I never was blinded before.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: 07d8e66 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Night-Pryanik** [comment] 2022-08-17 02:48
Duplicate of #56148.

**Closed by Night-Pryanik** 2022-08-17 02:48 UTC
Labels: (S1 - Need confirmation)
