### ISSUE TITLE
Kevlar dog harness cannot be butchered or disassembled

### ISSUE THREAD

**Issue by 10asd28** [CleverRaven/Cataclysm-DDA#47447] opened 2021-02-12 13:07 UTC
This item that is typically dropped from K-9s cannot be broken down to its base components.

**Comment by merrygin** [comment] 2021-05-22 13:43
This (and other items) is flagged with NO_SALVAGE, i suspect because former contributors intended to add specific uncraft recipes but didn't end up creating some, see #29134. They described problems with removing NO_SALVAGE:
_"NO_SALVAGE applied to leather harness (gave back way too much rags and leather patches for some reason) and rainsuit (yielded neoprene sheets)"_
So this issue would probably need a specific uncraft recipe.

**Comment by leemuar** [comment] 2021-05-31 11:12
> NO_SALVAGE applied to leather harness (gave back way too much rags and leather patches for some reason) and rainsuit (yielded neoprene sheets)

As far as I remember "gave back way more rags and leather" is a bug and it applies to many other items. I think we should fix the bug and remove the NO_SALVAGE flag from items.

**Comment by merrygin** [comment] 2021-06-01 14:34
That would be ideal of course! I don't see an open issue for that, though, and have no idea how difficult the problem actually is. 
If its a big problem that requires a lot of time, it would still be sensible to get some easy recipe working in the meantime, i think.

**Comment by leemuar** [comment] 2021-06-01 22:06
> 
> 
> That would be ideal of course! I don't see an open issue for that, though, and have no idea how difficult the problem actually is.
> If its a big problem that requires a lot of time, it would still be sensible to get some easy recipe working in the meantime, i think.

#45063 and #42375. The bug was actually fixed and merged. We can now review and probably remove NO_SALVAGE flag from dog's armor

**Comment by leemuar** [comment] 2021-06-02 13:57
I did some test and it seems there is a new bug that still increases amount of materials on salvaging (more details here: https://github.com/CleverRaven/Cataclysm-DDA/pull/45779#issuecomment-852992394)

On current stable Ellison version disassembling Kevlar dog harness gives 6 layered kevlar plates
On the most current version of the game (tested on cb88af73) - 50+ layered kevlar plates

Im not very experienced with the game, but that amount (50+) looks kinda wrong.

The "bug" (huge amount of materials out of cutting\disassembling items) comes from algo that tries it's best to calculate materials based on item's mass. If the item is heavy - it will generate much more materials out of it.

Figuring out the correct algo will be tricky and requires time. A quicker solution would be to add uncraft recipes manually as @merrygin suggested.

**Comment by actual-nh** [comment] 2021-06-02 14:33
I suspect part of the problem is that the only material listed is kevlar_layered, when in actuality there would be other materials involved. Admittedly, given how armor works, adding an extra material (nylon, I suspect) will require increasing the thickness **_if_** the current level of armoring is realistic - I don't know if it is (might be too protective for reality).

**Comment by leemuar** [comment] 2021-06-02 18:07
@ZhilkinSerg mentioned [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/45779#issuecomment-853166330) that this might be OK behavior. Increased material yield might be a new norm and the "old" yield was actually incorrect and too low

Im too new to the gameto judge, but if it is true - than we can just remove NO_SALVAGE flag without making new uncraft recipe for this issue. Could someone please confirm that this new increased amout of materials is correct?

**Comment by actual-nh** [comment] 2021-06-02 18:36
> Im too new to the game to judge, but if it is true - than we can just remove NO_SALVAGE flag without making new uncraft recipe for this issue. Could someone please confirm that this new increased amout of materials is correct?

I suggest creating a pull request and seeing what people think. (Put '[CR]' in the tile to request further comment, and I can request ZhilkinSerg as a reviewer.)

**Comment by leemuar** [comment] 2021-06-03 07:10
What also bothers me: Kevlar dog harness yields almost twice as much kevlar plates (50+) than Kevlar vest (30+). Is dog's vest really twice as heavy as human's?

**Comment by Alienmen1** [comment] 2021-06-19 00:55
With the current experimental version. Kevlar Dog Harness cannot be disassembled or butchered.
Also what leemuar said is right, the kevlar dog harness shouldn't give more plate than an actual human kevlar vest

**Comment by leemuar** [comment] 2021-06-21 13:40
Ill make another issue for auditing kevlar armor yield

**Comment by leemuar** [comment] 2021-07-17 20:29
The correct way to solve this is to add uncraft recipes for all dog's armor. See https://github.com/CleverRaven/Cataclysm-DDA/pull/50007#issuecomment-881955693 for the details why removing NO_SALVAGE flag is not enough

**Comment by captainego** [comment] 2022-09-26 02:09
After reviewing the dog harnesses there were only two that did not have uncraft recipes.  I have added uncraft recipes for leather_harness_dog (leather dog harness) and rubber_harness_dog (rubber dog rainsuit) .  leather_harness_dog returns up to 3 leather patches and rubber_harness_dog returns up to 8 cotton sheets and 8 plastic sheets.

Both require a cutting tool of 2

**Closed** 2022-09-28 14:55 UTC
Labels: <Bug>, Good First Issue, [JSON], Crafting / Construction / Recipes, Items / Item Actions / Item Qualities
