### ISSUE TITLE
Floating corpses

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#55752] opened 2022-02-28 17:03 UTC
### Describe the bug

I found this getting on roofs for exploration and i thought i overlooked some loot, then going up and down all over the 3 zlvls to get there and i realized the corpses, the loot, and even the lots of blood of this pre-generated set of corpses were floating right there in the middle of the air.
I probably will construct some kind of vehicle to get there for science but for now i wrote this bug report.

### Steps to reproduce

Not sure, it was on the top of a riverside potter's cottage if it's worth something.

### Expected behavior

Generating corpses not in the air / falling from open space / have a reason to be floating there.

### Screenshots

![floating corpses](https://user-images.githubusercontent.com/43771067/156025863-a77d6354-a83b-44f7-890e-f3b2079ee7aa.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 582984d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit]
]

**Comment by Night-Pryanik** [comment] 2022-02-28 17:40
Duplicate of #38066.

**Closed by Night-Pryanik** 2022-02-28 17:40 UTC
