### ISSUE TITLE
Game watch and game console 

### ISSUE THREAD

**Issue by septicass** [CleverRaven/Cataclysm-DDA#49434] opened 2021-06-24 14:09 UTC
# Describe the bug

Game watch and game console not consuming battery charges when choosing the option play anything for a while

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration
- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 5; Release: 8.1.0; Incremental: V11.0.4.0.ODACNXM; 
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 5; Release: 8.1.0; Incremental: V11.0.4.0.ODACNXM; 
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Additional context

**Comment by septicass** [comment] 2021-06-24 14:11
My first bug report so i am pretty lost

**Comment by casswedson** [comment] 2021-06-24 14:27
![games](https://user-images.githubusercontent.com/58050969/123279967-fc3a5e80-d4cd-11eb-9b8c-302fb7b6c6d8.png)

On:
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-10704-gd3b1ed2cb6-dirty [64-bit] d3b1ed2cb6
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by actual-nh** [comment] 2021-06-24 16:21
I believe this may have been fixed in experimental versions (and thus very soon in 0.F).

**Comment by ZhilkinSerg** [comment] 2021-06-24 17:18
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40148

**Comment by actual-nh** [comment] 2021-06-24 19:25
@septicass: I am closing this; if after updating you continue to have this problem, please open an issue again.

**Closed by actual-nh** 2021-06-24 19:25 UTC
Labels: (S1 - Need confirmation), Items: Battery / UPS
