### ISSUE TITLE
Thread only available for crafting if not loaded in needle (exp 0.C-6488)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#21276] opened 2017-06-19 02:23 UTC

**Comment by DangerNoodle** [comment] 2017-06-19 06:01
See pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/20569, pinging @ZhilkinSerg due to yet another issue opened concerning the problem they have been unable to fix for roughly four months.

Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/20983

**Closed** 2017-06-19 08:01 UTC
Labels: Duplicate
