### ISSUE TITLE
Volume-changing objects can exceed volume limit of the pocket they are in

### ISSUE THREAD

**Issue by BreBat** [CleverRaven/Cataclysm-DDA#44615] opened 2020-10-04 18:30 UTC
# Describe the bug
Volume-changing objects can be placed into a pocket in their smaller form and then be activated to their larger form without leaving the (now undersized) pocket

# Steps To Reproduce

1. Wear an item with a small pocket (holster in my case)
2. Pick up the small form of an object that can change between two differently large forms (rolled sleeping bag)
3. Ensure the object is in the pocket
4. Activate the object to change its form
5. Object is now oversized for its containing pocket, but remains in pocket and can trigger an error screen if selected (volume exceeds capacity, item_contents.cpp:1434) 

# Expected behavior

Expected the game to either deny the form change, or cause the object to be dropped

# Versions and configuration

-OS: Win10 Education, x64
-Version: [Tiles] 0.E-6496-gef5a06d
-Mods: no_npc_food

**Comment by fizzle7** [comment] 2020-11-18 20:36
Duplicate of #40775

**Comment by AnonimusC** [comment] 2020-11-27 15:43
A condom tried to fill up more than it could hold (water). Volume exceeds capacity.
>  DEBUG    : volume exceeds capacity (1396ml > 1000ml)
>  FUNCTION : float item_contents::relative_encumbrance() const
>  FILE     : src/item_contents.cpp
>  LINE     : 1478
1. Load the [save](https://github.com/CleverRaven/Cataclysm-DDA/files/5608543/save.zip
).
2. Try to collect water in the condom to your right, from the lake.

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5608454/debug.zip)

**Comment by Night-Pryanik** [comment] 2021-04-16 15:39
This should be closed by #45873.

**Closed by Night-Pryanik** 2021-04-16 15:39 UTC
Labels: (S3 - Duplicate), <Bug>, Items: Containers
