### ISSUE TITLE
NPC's in camp all want to stand on the same spot and are very vocal about it.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51395] opened 2021-09-05 16:37 UTC
### Describe the bug

If you have multiple NPCs in camp, sometimes they want to stand in the same location for some reason. This will lead to endless chatter spam as they ask to get past each other.

### Steps To Reproduce

Have multiple NPCs who want to stand in the same place. (From having the same specialty? Same priorities? I don't know.)
Watch the spam happen.

### Expected behavior

I'd expect that they'd have multiple spots to stand, or at least would shut up about wanting to all huddle together.

### Screenshots

![image](https://user-images.githubusercontent.com/6834262/132134459-c09d5f99-88e6-435c-922b-18f9981e4bb9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment] 2021-09-05 17:08
NPCs play King of the Hill when not currently engaged in fighting zombies.  Working as intended.  ;)   Joking.

**Comment by RenechCDDA** [comment] 2021-09-05 18:56
See also #47976

I can definitely confirm this is an ongoing issue, just.... very unclear what the cause is. 47976 posits that it's due to bed assignment but not all NPCs will idle at a bed when assigned to the camp. Add in a room with a window (that they will *gladly* open and shut and open and shut and open and shut.......) and you get not only sound spam, but also immense slowdown when performing tasks in the reality bubble of the camp.

There's also a few reddit threads on the issue, such as the one linked in that github issue.

**Comment by MrHrulgin** [comment] 2021-09-05 20:08
For me, they all cluster around a single spot in the fabrication workshop instead of a bed, but it's definitely that same issue.

**Comment by anothersimulacrum** [comment] 2021-09-11 15:32
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/51448
If this is incorrect, comment here and I can reopen it.

**Closed by anothersimulacrum** 2021-09-11 15:32 UTC
Labels: <Bug>, (S3 - Duplicate), NPC / Factions
