### ISSUE TITLE
Brass catcher disintegrates casings and hulls instead of catching them.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#44052] opened 2020-09-08 15:51 UTC
# Brass catcher disintegrates casings and hulls instead of catching them.

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Attach brass catcher onto the gun.
3. Fire.
4. Check your inventory.

Replicated with M1 Garand and Remington 870 express shotgun.

# Expected behavior

Brass catcher inserts casings and hulls into player's inventory.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5407-g8b385a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    Aftershock [aftershock],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex]
]

**Comment by LaVeyanFiend** [comment] 2020-09-08 15:52
Duplicate of #42313.

**Closed** 2020-09-08 16:32 UTC
