### ISSUE TITLE
Storage batteries unrepairable

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21060] opened 2017-05-20 00:25 UTC
I have  a damage storage battery that I want to repair.

I can't pick it up because it weighs 500lbs
When activating a soldering iron it doesn't show as a repairable item (no nearby items show)
When activating a makeshift welder it doesn't show as a repairable item (no nearby items show)
When installed in a swappable storage battery case I can't repair it ("There are no damaged parts on this vehicle")

![image](https://cloud.githubusercontent.com/assets/12039454/26271221/e9db3f50-3cb7-11e7-959d-721788514aff.png)

**Comment by Zilenan91** [comment] 2017-05-20 02:16
It says "Most damaged (can't repair): swappable storage battery" in the vehicle menu but one should probably be able to repair something as important as a battery.

**Comment by Leland** [comment] 2017-05-20 04:51
Duplicate of #19451

**Closed by Leland** 2017-05-20 04:51 UTC
