### ISSUE TITLE
Sleeping with a lit latern causes lag spike before sleep menu appears.

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#29514] opened 2019-04-13 06:00 UTC
**Describe the bug**  

When sleeping with a lit (oil, petrol, electric) lantern, the game hangs for about 30 seconds before presenting the sleep menu (along with a reminder that your lantern is lit).

**To Reproduce**  

1. Carry a lantern
2. Turn it on.
3. Hit the sleep button (`$` by default)
4. Wait...
5. Eventually the sleep menu will appear.

**Expected behavior**  

Activating sleep with a lit lantern takes just as long to get to the menu as without.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 16.04 x86
 - Game Version: 0.D-1718-g1f89a2dc6d
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  

May be related to #29509.

**Comment by ifreund** [comment] 2019-04-13 08:32
Duplicate of #29451

**Closed by ifreund** 2019-04-13 08:32 UTC

**Comment by pjf** [comment] 2019-04-13 09:00
@ifreund : D'oh, I don't know how I missed that. Thank you so much for spotting it!
