### ISSUE TITLE
selecting "gills" mutation in character creation screen doesnt work

### ISSUE THREAD

**Issue by yam1917** [CleverRaven/Cataclysm-DDA#58848] opened 2022-06-30 16:11 UTC
### Describe the bug

selecting "gills" mutation in character creation traits screen doesnt work, it does add 2 points to the positive trait limit, but gills mutation doesnt turn "green", selecting it again (and again) just adds another 2 points to the trait limit, switching tabs resets the limit.

### Steps to reproduce

1.new character
2.experiment
3.unwilling mutant
4. trait doesnt work

### Expected behavior

it should let me select the trait

### Versions and configuration

OS: windows 10

game version: f385f24 and version 92acd0c

**Comment by NetSysFire** [comment] 2022-06-30 19:11
Duplicate of #57748.

**Closed by NetSysFire** 2022-06-30 19:11 UTC
Labels: (S1 - Need confirmation)
