### ISSUE TITLE
Game crashes when detaching vehicle from bike rack

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#33609] opened 2019-08-28 07:44 UTC
# Describe the bug

When attempting to detach a bike from a SUV, the game immediately crashes.

# Steps To Reproduce

1. Download [attached map file](https://github.com/CleverRaven/Cataclysm-DDA/files/3549560/Everfall.Meadows.zip) and load it in.

2. Move towards the left side of the vehicle and attempt to detach bike from bike rack.

# Expected behavior

Bike is detached as a seperate vehicle.

# Screenshots

<img width="289" alt="Screen Shot 2019-08-28 at 4 24 24 PM" src="https://user-images.githubusercontent.com/27952407/63835648-db2c8380-c9b2-11e9-9b24-fdb50f4bb068.png">

# Versions and configuration

<img width="698" alt="Screen Shot 2019-08-28 at 4 38 55 PM" src="https://user-images.githubusercontent.com/27952407/63835542-9f91b980-c9b2-11e9-828e-275d90fdbc0a.png">

 - Game Version: 0.D Stable
 - Graphics version: Tiles

 - Mods loaded:
[
  "dda",
  "realguns",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "space_heater",
  "modular_turrets",
  "Salvaged_Robots",
  "Cata++",
  "hydroponics",
  "mutant_npcs",
  "npc_traits",
  "zets_hair_extensions",
  "more_locations",
  "zets_hair_ext_more_locations",
  "FujiStruct",
  "randomized_mall",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "filthy_morale",
  "sleepdeprivation",
  "zets_tweaks",
  "DP_REMIX_INDICATORS"
]

# Additional context

[Crash log](https://github.com/CleverRaven/Cataclysm-DDA/files/3549566/crash.log)

**Comment by AMurkin** [comment] 2019-08-28 07:48
Duplicate of #28712.

**Comment by XygenSS** [comment] 2019-08-29 04:46
Found the cause of the problem. If you modify the attached vehicle, it will produce a crash when you attempt to detach it.

**Closed** 2019-08-29 04:45 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Vehicles
