### ISSUE TITLE
Damage threshold for terrain and furniture - chance of shooting through it

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#41128] opened 2020-06-06 23:27 UTC
# Is your feature request related to a problem? Please describe.
Currently terrain and furniture in cataclysm works like this: _you shoot the wooden wall, you damage the wooden wall, the wooden wall is either destroyed or you're out of ammo_ , which is clearly unrealistic when we take into consideration the terrain or furniture made out of materials that can be **easily penetrated** by many calibers such as low quality wood, glass, plastic, etc

In real life a wide range of different caliber guns are capable of penetrating weaker types of terrain and furniture that is not made out of overly durable materials, the bullets may **change the direction** upon passing through the terrain or furniture, **change the momentum** entirely, have the projectile velocity reduced but **not entirely nullified**, thus still being able to deal some damage if it manages to reach the target that may be not too far away from the penetrated terrain/furniture

# Describe the solution you'd like
Make the damage inflicted by **ranged** projectiles apply a flag to some types of furniture or terrain that, **depending on damage dealt** to the furniture/terrain with **ranged** projectiles only, will give the ranged projectile a chance of "passing through" the terrain albeit with a reduced momentum thus dealing less damage than when being directly shot without passing through any obstacle

# Describe alternatives you've considered
None that i could think of for now

# Additional context
None

**Comment by anothersimulacrum** [comment] 2020-06-07 00:46
It's actually more complicated, things like glass allow bullets through, but reduce their damage. This whole system needs some more nuance - right now things that can be shot over (e.g.) dressers are treated the same as as things that can shot through (e.g. glass). IIRC there's a big hardcoded thing somewhere that determines that, and definitely needs some cleaning up, and to make more sense.

**Comment by ymber** [comment] 2020-06-07 05:01
Closing as duplicate of #36633.

**Closed by ymber** 2020-06-07 05:02 UTC
Labels: <Suggestion / Discussion>, [C++]
