### ISSUE TITLE
Zombie vision indicator bugged

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#51185] opened 2021-08-29 03:23 UTC
### Describe the bug

At the time of night/day transition, zombies can see the player, but there's no "!" indicator

### Steps To Reproduce

1-wait till night with wait command, on the earliest stages of day/night transition.
2-spawn clairvoyance artifact.
3-teleport randomly untill some zombies follow you without "!" vision indicator

### Expected behavior

zombies that see me should have the "!" indicator

### Screenshots

![unknown](https://user-images.githubusercontent.com/82523535/131236957-2ba19839-03c9-4533-b538-5c956ed50ca7.png)
![unknown (1)](https://user-images.githubusercontent.com/82523535/131236958-c3cd8a5f-cb93-49ef-82e5-64bf85486208.png)

### Versions and configuration

-W10
-build number: 2021-08-17-2240
-tiles version
-english language

### Additional context

Maybe it only happens in the very first few minutes of the night,

also, I'm using the surrounded starting scenario

**Comment by Pooshmeu** [comment] 2021-08-29 03:25
Note: in the screenshots, all I did was: I teleported somewhere randomly and started passing turns, I hadn't passed near the zombies and I hadn't made noise

**Comment by actual-nh** [comment] 2021-08-29 04:42
Please contribute the screenshots, etc to #50497.

**Comment by Menschheit** [comment] 2021-08-29 09:19
#50833 maybe related.

**Comment by Menschheit** [comment] 2021-08-29 20:33
Actually the problem is clear: lightmap is not updated if there are no other light sources except moon/sun and the player passed turns without movement (or wait). The game compares light cache with the current sun/moon light to determine whether you are "illuminated", which is absurd: in this case all monsters can see you as if you are in day light (day vision range is applied ).

Moreover comparing with sun/moon light level is also problematic: So if you are indoors with all windows closed. No matter it is day or night it is the same dark in the big room.
Now lets say you are under a weak light source, if it is day time you will be ok, the monsters will have normal vision range according to light level since day light > this weak light source. 
But at night,  the weak light source > night light level, then you are suddenly "illuminated" and all monsters can see you with day vision range. 

The cache issue can be easily fixed by using cache vs cache, but this mechanism is hard to implement:
Third case: you are underground, no narual light, but the whole room are filled with weak light sources... So are you "illuminated"? Actually you shouldn't be since the whole room has the same light level. But what is the "natural" light level now? the game still thinks it's as dark as a cave...

**Closed** 2021-09-23 22:28 UTC
Labels: <Bug>, (S3 - Duplicate), Info / User Interface, Monsters
