### ISSUE TITLE
Windows 64 build failure

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19169] opened 2016-11-05 08:16 UTC
`make: /home/narc/mxe/usr/bin/x86_64-w64-mingw32.static-ccache: Command not found
make: *** [cataclysm.exe] Error 127
Build step 'Execute shell' marked build as failure
Recording fingerprints
IRC notifier plugin: Sending notification to: #CDDA-dev
SSH: Current build result is [FAILURE], not going to run.
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] Skipped based on build state FAILURE
Finished: FAILURE
`

**Comment by illi-kun** [comment] 2016-11-05 08:38
Duplicate of #19027.

**Closed by illi-kun** 2016-11-05 08:38 UTC
Labels: Build
