### ISSUE TITLE
Killing a hostile bandit that didn't see you gives you the "killed innocent" morale debuff

### ISSUE THREAD

**Issue by geskeca** [CleverRaven/Cataclysm-DDA#58552] opened 2022-06-19 15:58 UTC
### Describe the bug

While going on mission where I was told to eliminate a bandit camp (specifically the "Missing Caravan" mission), I used my sniper rifle to kill off the bandits from far away before they could notice me. However this caused me to get the "killed an innocent person" morale debuff of -100.

### Steps to reproduce

1. Get a rifle with like 60 range and shoot bandits without them noticing you
2. Check morale menu

### Expected behavior

It seems ridiculous considering I was on a mission to kill bandits that had robbed and killed a caravan so they aren't innocent, and the bandits were always listed as hostile, even without seeing me.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: cc694a8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment] 2022-06-19 16:23
It might be cleanest to handle this via a Trait Flag for NPCs that are never innocent.

**Comment by descan** [comment] 2022-06-19 16:49
> It might be cleanest to handle this via a Trait Flag for NPCs that are never innocent.

That does sound like a good fix for the specific bug, although if in the future (or maybe at present! I haven't done these missions yet) if you can talk to the bandits and, with really high social-related skills/traits, somehow persuade them to reform, then affixing them with a flag like that, indicating they're always fair game, might be too harsh.

Unless said reformation removes that flag and adds a reformed bandit flag, for whatever purposes those might serve (vindictive/revenge seeking victims? A lower innocent-killed malus of "well he was a bit of a dick before but he was getting better..."?)

**Comment by Maleclypse** [comment] 2022-06-19 17:12
Currently bandits are unrecoverably hostile.

**Comment by Night-Pryanik** [comment] 2022-07-09 12:35
Can't confirm on 0.F-9789.

Got that `Missing Caravan` mission. Got Barrett. Went to bandits camp. One-shot killed one of the bandits without him noticing me. Got no morale penalty.
![изображение](https://user-images.githubusercontent.com/11132525/178105953-99b2082c-4dab-4d3f-a892-21c4cc31c67c.png)
![изображение](https://user-images.githubusercontent.com/11132525/178106010-37b8ee46-f4c9-4387-92eb-f14f3d220e24.png)

**Comment by Perset** [comment] 2022-09-18 02:14
This is still happening. My guy is D8'ing ring now at -141 from this mission, I drove out to them at night and shot from the shadows while they were lit up by my headlights. Suicide impending.

**Comment by Night-Pryanik** [comment] 2022-11-18 15:17
Duplicate of #30124.

**Closed by Night-Pryanik** 2022-11-18 15:17 UTC
Labels: NPC / Factions, (S2 - Confirmed)

**Comment by VenomousInc** [comment] 2022-12-03 14:21
I just got this issue during the `Missing Caravan` Quest, they're not innocent so it doesn't make sense; especially after one of shot at me first.
