### ISSUE TITLE
craft menu search broken (exp 5612)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#18623] opened 2016-10-02 18:49 UTC
No searches using colon prefixes seem to return anything.  The two searches here returned zero results.

![2016-10-02 14_44_30-greenshot](https://cloud.githubusercontent.com/assets/19196781/19022858/510d83a8-88af-11e6-8125-10eeec897d2d.jpg)
![2016-10-02 14_43_14-greenshot](https://cloud.githubusercontent.com/assets/19196781/19022859/510ef440-88af-11e6-9a62-a5b4c5691978.jpg)

**Comment by illi-kun** [comment] 2016-10-02 19:17
Dupe of #18753.

**Closed** 2016-10-02 19:19 UTC
