### ISSUE TITLE
Small Item negative duplication glitch

### ISSUE THREAD

**Issue by Kurrisum** [CleverRaven/Cataclysm-DDA#40821] opened 2020-05-25 06:05 UTC
# Describe the bug

Canceling out of wielding a small item with a negative value will duplicate the stack until you successfully pick it up

# Steps To Reproduce
1. Fine a negative value small item that you have to wield (Wild veggies seem the fastest to find and seeds)
2. Pick up item
3. Get "not enough capacity to wield Item(-x)"
4.  Escape cancel prompt
5. Repeat 2-4 until item is picked up 
6. The increasing negative value becomes the value of the item stack when successfully picked up 
# Expected behavior

Pick up light items normally

# Screenshots
![image](https://user-images.githubusercontent.com/16447312/82783084-64c69000-9e23-11ea-9954-5996f79d3ac5.png)
![image](https://user-images.githubusercontent.com/16447312/82783109-790a8d00-9e23-11ea-8646-3719a1c9b285.png)
![image](https://user-images.githubusercontent.com/16447312/82783150-8c1d5d00-9e23-11ea-8414-32d21f585c08.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by peperov** [comment] 2020-05-26 10:54
Duplicate of #40502

**Closed** 2020-05-28 04:14 UTC
