### ISSUE TITLE
[MoM] failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0.75" to a number

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#74903] opened 2024-07-04 16:34 UTC
### Describe the bug

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0.75" to a number

 FUNCTION : eval
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\math_parser.cpp
 LINE     : 241
 VERSION  : 7f60041

### Attach save file

[Badlands-trimmed.tar.gz](https://github.com/user-attachments/files/16101280/Badlands-trimmed.tar.gz)

### Steps to reproduce

1. Load the game or try to do some activity like storing or reading a book.

### Expected behavior

No error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: 7f60041 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills]
]

**Comment by Standing-Storm** [comment] 2024-07-04 19:38
Duplicate of #71635

**Comment by RDru** [comment] 2024-07-04 20:30
> Duplicate of #71635

It only started with latest version. I can still play fine on build 2024-07-03-0229

**Comment by RDru** [comment] 2024-07-04 20:39
Yesterday I saved my game on build 2024-07-03-0458. 
Today I made a backup of the save and updated the game to the latest version.
Got the error. 
Reverted to build 2024-07-03-0458, restored the save but still got the error.
Reverted to build 2024-07-03-0229, no error. Game works fine.

Hope this helps.

**Closed** 2024-07-08 16:42 UTC
Labels: (S1 - Need confirmation)
