### ISSUE TITLE
Vehicles get split in multiple parts if using bike racks

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#49184] opened 2021-06-05 05:59 UTC
# Describe the bug
If you attach multiple vehicles to one vehicle, they can get split into multiple pieces if you try to detach the.

# Steps To Reproduce

1) Assume I want to attach shredders to this vehicle:
![image](https://user-images.githubusercontent.com/1657728/120881682-fec03b80-c626-11eb-874b-0dba88081c23.png)

2) So left and right shredders are each a 2-tile vehicle. Then I attach bike racks to the central vehicle in marked squares:
![image](https://user-images.githubusercontent.com/1657728/120881692-26170880-c627-11eb-8762-8f3f9630b762.png)

3) Then I use these racks to attach shredders, obtaining a single vehicle like this:
![image](https://user-images.githubusercontent.com/1657728/120881701-3a5b0580-c627-11eb-94f5-0e85244af017.png)

4) So far so good, everything works. However, when I try to detach one of them, this happens:
![image](https://user-images.githubusercontent.com/1657728/120881709-4a72e500-c627-11eb-9e98-d50dd700123e.png)

As in, only one tile of the right shredder gets detached, and the other one still stays, effectively splitting the right shredder vehicle in two. 

Here's what the central vehicle looks like after this, note the missing shredder frame on the right:
![image](https://user-images.githubusercontent.com/1657728/120881758-9160da80-c627-11eb-98b9-88e444ef16a1.png)

# Expected behavior

Ideally I expect the shredder vehicles to have the same number of tiles after I detach them. As in, I don't want them to be split.

# Screenshots

I attached screenshots to the repro steps.
# Versions and configuration

This happens in a little bit stale experimental that I don't want to update because I have an ongoing playthrough and I'd rather not update in the middle of it. Let me know if you need more information or if you can't repro it in the current experimental.

**Comment by Raikiri** [comment] 2021-06-05 16:25
Upd: I forgot to mention, but this is just one of many cases when vehicle tiles can get separeted. There are other manifestations of this bug when vehicle tiles disappear or get stuck inside of each other. One can repro them many of them by randomly attaching, detaching and dragging those two shredders around.

**Comment by hexagonrecursion** [comment] 2021-08-24 07:36
Could not reproduce this. If you can reproduce this please post a save file.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Raikiri** [comment] 2021-08-24 07:47
@hexagonrecursion are you saying you can consistently attach and detach those shredders without them getting split? It's not very consistent, but for me it fails almost always on the first attempt. If it does work, can you try attaching them, maybe driving around a little and then detaching again?

**Comment by hexagonrecursion** [comment] 2021-08-24 08:53
I do not have your save file. I tried attaching and detaching two vehicles in mine a couple of times today without surprises.

Also please load your save file, select Main menu (ESC) > Debug Menu > Info > Generate game report and post the result here.

**Comment by Raikiri** [comment] 2021-08-24 09:36
Well actually I reported this problem on 0.E experimental build from 3 months ago. Now I have updated to the recent one and one of my racks was not functioning (did not attach any vehicles next to it). So I had to reattach it, and after that I could no longer repro the problem.

Was it (accidentally?) fixed recently in some unrelated commit?

**Comment by wapcaplet** [comment] 2022-01-16 17:22
Closing as fixed / unreproducible per the above comments. If anyone can still reproduce it reliably, ping me and I will reopen.

**Closed by wapcaplet** 2022-01-16 17:22 UTC
Labels: (S1 - Need confirmation), Vehicles
