### ISSUE TITLE
drinking mana potion when dissasembling coat rack, i think

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#51240] opened 2021-08-30 17:35 UTC
### Describe the bug

for some reason, when dissasembling coating rack with auto drink in tile, instead of finishing the construction, character drinks mana potion

### Steps To Reproduce

activate auto drink in tile
spawn lesser mana potion, put in auto drink tile
spawn coat rack
try to dissasemble
im unclelar if is just lesser mana potions or any other will make the bug work too

### Expected behavior

to dissasemble

### Screenshots

![Captura de pantalla (34)](https://user-images.githubusercontent.com/52901609/131380673-1fd214d0-a3fb-48d5-bd77-de4b17bda228.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7495101 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

### Additional context

if this is a fluke is very wierd

**Comment by actual-nh** [comment] 2021-08-31 01:39
That the character is drinking something from an auto-drink zone is normal; that it's a mana potion may indicate a need to distinguish a bit better what should and shouldn't be drunk (or at least ask about first).

**Comment by hexagonrecursion** [comment] 2022-01-04 15:34
Please change the title to: "auto-drink" drinks a mana potion.

I am sorry, but I could not reproduce this bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

**Comment by LeahLuong** [comment] 2022-01-04 17:32
Phew! & here I was thinking I'm the only person who gets thirsty for mana when moving coat racks. I was too embarassed to bring it up in polite discussion but now I know I'm not alone.

Jokes aside, this is likely related to #53997.

**Comment by wapcaplet** [comment] 2022-01-17 03:51
Fixed by #54065

**Closed by wapcaplet** 2022-01-17 03:51 UTC
Labels: (S1 - Need confirmation), Items: Food / Vitamins, Crafting / Construction / Recipes, Inventory / AIM / Zones, Mods: Magiclysm
