### ISSUE TITLE
Ammo belt issues

### ISSUE THREAD

**Issue by NeevAsteria** [CleverRaven/Cataclysm-DDA#36756] opened 2020-01-06 18:14 UTC
# Describe the bug

Found 2 issues relating to ammo belts:
1. Ammo belts gets an error (refer to screenshot below) when unloading it while its not inside your inventory (e.g. on the ground, inside a vehicle cargo). It then leaves an empty ammo/grenade belt that can be reloaded.
2. When activating linkages to make ammo belts and you get interrupted (via forced interruption e.g. falling asleep), it still produces an empty ammo belt.

# Steps To Reproduce

1. Find/Spawn a ammo belt
2. Drop it on the ground
3. Unload it without picking it up

# Expected behavior

The ammo belt itself should disappear when unloading it if it is on the ground, similar to when unloading ammo belts if it is on your inventory

# Screenshots
Error:
![image](https://user-images.githubusercontent.com/58652206/71818524-36d6ee00-30c4-11ea-8106-4c607d761836.png)
Belts:
![image](https://user-images.githubusercontent.com/58652206/71838048-ec209a80-30f2-11ea-8cc9-47c8a43452dc.png)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-11046-gb0160b4
 - Graphics version: Tiles
 - Mods loaded: 
![modlist](https://user-images.githubusercontent.com/58652206/71838100-0e1a1d00-30f3-11ea-9570-e241e60c814f.PNG)

# Additional context

Reloading the bugged-spawned ammo belt still requires its respective ammo type and linkages.

**Comment by Night-Pryanik** [comment] 2020-01-07 05:22
Duplicate of #35368.

**Closed by Night-Pryanik** 2020-01-07 05:22 UTC
