### ISSUE TITLE
Consistent game crash a few turns after loading a particular save.

### ISSUE THREAD

**Issue by HeadstrongCatgirl** [CleverRaven/Cataclysm-DDA#29797] opened 2019-04-21 17:32 UTC
**Describe the bug**  
The game crashes with SIGFPE.

Steps to reproduce the behaviour:
1. Load the save.
2. Wait for a few minutes of in-game time.

Expected behaviour:
No crash.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Debian stable
 - Game Version: 0.D-2076-gc71b04bbf5

 - Graphics version: Curses
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "generic_guns",
  "makeshift",
  "More_Survival_Tools",
  "crazy_cataclysm"
]

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3101432/crash.log)
[core dump](https://drive.google.com/open?id=1-elDG_WGzdWNX2bDbgzpY1X2qoXQqx2d)
[world folder](https://drive.google.com/open?id=1dQc8kX5Y5yQEd-yhXyGf3X2Rvv9DkDgA)

**Comment by AMurkin** [comment] 2019-04-21 17:42
Must be a duplicate of the #29778.

**Comment by ifreund** [comment] 2019-04-21 17:45
Closing as a duplicate. If you can reproduce this on a build with  #29796 merged please reopen

**Closed by ifreund** 2019-04-21 17:45 UTC
