### ISSUE TITLE
Pickled veggie recipe will include identified poisonous mushrooms without warning or required confirmation.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70796] opened 2024-01-09 07:24 UTC
### Describe the bug

If you have regular and poisonous mushrooms nearby, you can make pickled veggy (poisonous) even if you didn't want to. The poisonous nature of the mushrooms doesn't stop them from being lumped together as mushrooms when being cooked.

### Attach save file

N/A

### Steps to reproduce

Have regular and poisonous mushrooms, try cooking a mushroom dish. 

### Expected behavior

I'd expect them to be separated out, so that the poisonous ones either weren't an option for cooking at all, or you were warned in advance of the poison inherent in the dish.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment] 2024-01-09 09:08
This is a situation similar to the one where containers are used for crafting:

The UI gives a subtle warning that containers in use have to be consumed by coloring the corresponding component entry. Until recently, the consumption step didn't actually care about usage, and just consumed the first containers found until a sufficient number had been consumed. That was fixed by running the consumption step twice, with the first one avoiding used containers, and the second one consuming the remaining required containers (if any) from containers in use.

It ought to be possible to update the filter used in the first consumption pass to skip over poisonous food items and only grab those of the non poisonous ones weren't sufficient. However, there's the issue of determining whether the crafter knows if they are poisonous or not, as that's something I don't think you realize unless you have a sufficient Survival skill (note that at least may apples also come in a poisonous version, so the issue is not limited to one single type of food item). There's also the issue of the case of a player who actually wants to use hallucinogenic mushrooms, which doesn't have an easy solution (apart from a separate bloating set of recipes).

Furthermore, the UI selection screen should probably color code poisonous food selections similar to how used containers are indicated, which isn't the same code as the one used for component consumption.

I drop all poisonous and hallucinogenic shrooms out in the forest because I don't want to haul back stuff I'm going to leave to rot anyway, but that's a work around for the issue, not a solution.

**Closed** 2024-01-14 05:04 UTC
Labels: (S1 - Need confirmation)
