### ISSUE TITLE
Epicuticle causes too much hand encumbrance to staunch blood loss.

### ISSUE THREAD

**Issue by rty275** [CleverRaven/Cataclysm-DDA#60336] opened 2022-08-20 18:19 UTC
### Describe the bug

The epicuticle item causes too much encumbrance on your hands to make bare-handed attempts to put pressure on a bleeding wound. Given that it is "a thin, flexible layer of chitin", I'm unsure if this is intended or not. If it's purposeful, then that's good to know and definitely unexpected, but I'm not an entomologist, I wouldn't know one way or the other really.

### Steps to reproduce

1. Acquire Epicuticle mutation and remove all other hand coverings.
2. Receive bleeding wound.
3. Wait a turn with hands empty, receive "Your hands are too encumbered to effectively put pressure on the bleeding wound!" message.

### Expected behavior

I would expect to be able to put pressure on wounds, but I fully admit I am not an entomologist, and what's more, I'm not totally sure there *is* any information available about putting pressure on wounds in chitin. I would think based on the "thin, flexible" part, that it would be receptive to pressure, or perhaps a hand on either side of the breach in chitin holding it closed, something along those lines. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 5235d18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

I generated a test world free of the admittedly pretty extensive list of mods the world I discovered this on had, and reproduced it successfully.

**Comment by fungamer2-2** [comment] 2022-08-20 18:41
Seems like a duplicate of #60100

**Closed** 2022-08-20 18:42 UTC
Labels: (S1 - Need confirmation)
