### ISSUE TITLE
Bunkers, helicopter crashes spawning single/no items.

### ISSUE THREAD

**Issue by NotChrysalis** [CleverRaven/Cataclysm-DDA#23191] opened 2018-03-13 07:31 UTC
Game version: 7190-7200

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Any, multiple combinations tested and does not seem to affect this

### Expected behavior

Military bunkers and helicopter crashes should spawn multiple pieces of loot with a possibility of no items, as they have in the past.

### Actual behavior

Both helicopter crashes and military bunkers spawn either a single item(per room, in the bunker) or no items at all with no exception.

### Steps to reproduce the behavior

Inspect military bunkers or helicopter wreckages/crashes on recent experimental builds. More locations _may_ be affected, possibly military outposts.

**Comment by ZhilkinSerg** [comment] 2018-03-13 13:07
Which game versions do you compare?

These (military bunkers and helicopter wreckages) are two different entities - overmap terrain and map extra. Both were not changed recently:

- `bunker` was moved to json more than a year ago in #20308;
- `mx_helicopter` is still harcoded, but was changed only slightly for more than 3 years.

### `mapgen.cpp` in 2018:

https://github.com/CleverRaven/Cataclysm-DDA/blob/004e9e6b06a00856c53463e7fdde077c6eb0a499/src/mapgen.cpp#L8029-L8066

### `mapgen.cpp` in 2015:

https://github.com/CleverRaven/Cataclysm-DDA/blob/409fd31b37d95c4753273c5885cfe8b40fc46f94/src/mapgen.cpp#L12961-L12998

**Comment by boydkr** [comment] 2018-03-13 21:01
Both use `place_items()` with similar parameters. Maybe the problem lies there.

**Comment by ZhilkinSerg** [comment] 2018-03-13 21:16
#20773 could be related then

**Comment by NotChrysalis** [comment] 2018-03-13 21:20
I'm comparing build 4564(because its the only old version I have installed) against 7190, 7193, and 7200.

I haven't followed development much for around a year, and don't have a precise time or build that this started happening. However, build 4564 does not exhibit this behavior in either situation. I think that build was after the helicopter changes but before the bunker changes. I recall that item spawning worked properly well beyond that, but I don't have any builds between 4564 and 7190 to test anymore. 

Correct me if i'm wrong, but I think that changes were made to the loot spawning system more recently-could explain why largely unrelated things are being equally affected. Maybe that could be connected. 

I honestly know very little about the project at the code level, and I have no real programming or debugging skill, I'm sorry if I can't be of much help here.

##  Examples:
### Bunkers:
Build 4564, expected behavior:
![intended 4564](https://user-images.githubusercontent.com/37324048/37367540-e3bc6a6a-26c0-11e8-8eaf-6d5f46c40e0e.png)

Build 7200, unexpected behavior:
![unexpected 7200](https://user-images.githubusercontent.com/37324048/37367539-e3a548e4-26c0-11e8-86f8-dc09cc02b92c.png)

### Heli crashes:
Build 4564, expected behavior:
![heli intended 4564](https://user-images.githubusercontent.com/37324048/37369368-2ba66dee-26c6-11e8-8d91-8d8923dc1ee2.png)

Build 7200, unexpected behavior:
![heli unexpected 7200](https://user-images.githubusercontent.com/37324048/37369494-7bdfadb6-26c6-11e8-8ab5-45323000e8b8.png)

**Comment by WhiteRavenPL** [comment] 2018-03-20 22:58
For bunkers, I think the problem is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/39600bc352d4a229a6bcf561bf2a5c13ca0a8998/data/json/mapgen/bunker.json#L101-L128

In each room, there is an 80% chance that an item will be placed, **but** each item has a very low probability e.g. `grenades` have `prob: 1` (out of a 100%, i.e. 1% !!). 

How about we multiply each probability by 10?

**Comment by illi-kun** [comment] 2018-03-25 13:41
Fixed by #23264 and #23266.

**Closed by illi-kun** 2018-03-25 13:41 UTC
Labels: Bug, Confirmation Needed, Mapgen
