### ISSUE TITLE
Vehicle in the lab Segmentation error on examination

### ISSUE THREAD

**Issue by cthae** [CleverRaven/Cataclysm-DDA#41063] opened 2020-06-03 23:34 UTC
# Describe the bug

Found a vehicle in a lab. Tried examining it hoping to find a rare electric engine there. Got an error.

# Screenshots

https://i.imgur.com/km3Gitj.png

# Versions and configuration

I'm on 10725
Windows 10
Tiles

I have a bunch of mods loaded, but I think the only one that's not in repo is Cata++, which I doubt is a reason here.

# Additional context

I'm adding the crash log and the save right near the car in question.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4726675/crash.log)
[Earth2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4726676/Earth2.zip)

**Comment by anothersimulacrum** [comment] 2020-06-03 23:39
Thanks for the report! Duplicate of #40843

**Closed by anothersimulacrum** 2020-06-03 23:39 UTC
Labels: (S3 - Duplicate)
