### ISSUE TITLE
Treat followers as containers when using AIM

### ISSUE THREAD

**Issue by AideeAmei** [CleverRaven/Cataclysm-DDA#78504] opened 2024-12-11 21:25 UTC
### Is your feature request related to a problem? Please describe.

When inserting items into followers' armor, one has to take the armor, insert the item, return the armor. Giving multiple items to the follower, assessing their capacity, taking some items from them, then giving them back more, this all can be a slow process in the current UI.

### Solution you would like.

It'd be much easier equipping followers using advanced inventory manager. They could have two sub-containers, wearing and inventory. Should they move during the interaction, they'd be treated the same as a container that gets out of reach during items exchange currently are. I can only assume that possibility is taken into account, I didn't try inserting items into container that was soon to be out of my reach for any reason.

### Describe alternatives you have considered.

Thinking any trade through thoroughly, if not possible due to change in circumstances, repeat trade twice or even more times depending on what changes in their equipment are required.

**Comment by Brambor** [comment] 2024-12-13 18:47
- Duplicate of #68034

**Comment by AideeAmei** [comment] 2024-12-14 15:26
Ok, but that's it? Duplicate to stale equals no go? At least the stale one could get reopened, right?

**Comment by Brambor** [comment] 2024-12-14 16:38
I am just writing it was already reported/suggested. Somebody has to pick this up, an enthusiastic developer.

It is a duplicate of my issue. I clearly want it implemented too.

I am not closing this as a duplicate nor marking my issue not stale. I am not sure what the protocol is. Just referencing the issues to each other.

**Comment by Night-Pryanik** [comment] 2024-12-30 16:57
I guess this is also a duplicate of #78308?

**Comment by Brambor** [comment] 2024-12-30 17:03
I guess I will mark them as duplicates then.

Note: Closed doesn't mean we don't want it!

**Closed** 2024-12-30 17:05 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>
