### ISSUE TITLE
Overmap craters (Red O) cause an item spawning error message when approached.

### ISSUE THREAD

**Issue by Vostokapollo** [CleverRaven/Cataclysm-DDA#58716] opened 2022-06-25 17:37 UTC
### Describe the bug

Title specifies the exact situation. There are two error messages that always display:

 DEBUG    : Setting terrain t_open_air at (88,117,0) where furniture is f_rubble_rock.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : ter_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 1783
 VERSION  : e34eeaa

 DEBUG    : Setting furniture f_null at (88,117,0) where terrain is t_open_air (which is_open_air)
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : furn_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 1443
 VERSION  : e34eeaa

### Steps to reproduce

Approach any crater. Error message is 100% persistent in my tests.

### Expected behavior

No error message lol

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Inglonias** [comment] 2022-06-25 17:45
Duplicate of #54092.

What's happening here is that craters spawn with one or more bombs set to go off as soon as you enter the reality bubble. The large explosion is creating open air tiles, which is causing weirdness.

**Comment by Vostokapollo** [comment] 2022-06-25 17:49
I suppose I should have done a more thorough search! I was doing due diligence because someone on the dev discord requested I report the experience here. My answer was "Isn't that just what happens when open space stuff happens?" and I guess I was right!

**Comment by PatrikLundell** [comment] 2022-06-25 18:07
Duplicates happen from time to time. It's no big deal, although it isn't an excuse for being sloppy, of course (and I'm definitely not implying you were).

**Comment by Inglonias** [comment] 2022-06-25 18:23
For people like me, duplicates like this serve as a good reminder that yes, the bug still exists. Sometimes, these things get fixed and nobody notices.

**Comment by NetSysFire** [comment] 2022-06-25 21:03
Closing as duplicate.

**Closed by NetSysFire** 2022-06-25 21:03 UTC
Labels: (S1 - Need confirmation)
