### ISSUE TITLE
Give stumbling a speed of 100

### ISSUE THREAD

**Issue by mm04926412** [CleverRaven/Cataclysm-DDA#62124] opened 2022-11-07 18:31 UTC
### Is your feature request related to a problem? Please describe.

Zombies teleport for free when they stumble, this makes reach weapons something that work most of the time but there is always a small chance a zombie will stumble towards you and get a free grapple after you attack. This on its own is enough to make reach weapons unviable for horde clearing since one of them will eventually get a free grapple in and then you're potentially dead.

### Solution you would like.

If stumbling cost zombies a move, then it would be an actual disadvantage rather than a 3/8 chance of getting a free turn like it currently is.

### Describe alternatives you have considered.

Make stumbling always take the enemy in a direction orthogonal to, or the reverse of, its current pathing.

### Additional context

I play on 0.F-3, my apologies if this is already something that has been changed.

**Comment by NetSysFire** [comment] 2022-11-07 20:05
Duplicate of #60861

**Closed by NetSysFire** 2022-11-07 20:05 UTC
Labels: <Suggestion / Discussion>
