### ISSUE TITLE
Crash while examining a aluminum can with alcohol in it

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#35181] opened 2019-10-31 06:20 UTC
# Describe the bug

While examining alcohol in a aluminum can the game will crash.

# Steps To Reproduce

1. Find aluminum can with alcohol in it
2. Examine it

# Expected behavior

Game shouldn't crash while examining a can full of alcohol.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.C-8957g1cac03e
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

When I tested this with the two types of pale ale it was a 50/50 in whether the game would crash.

[CDDACrashLog.ZIP](https://github.com/CleverRaven/Cataclysm-DDA/files/3792380/CDDACrashLog.ZIP)

**Comment by Nerezza** [comment] 2019-10-31 09:29
This is probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/35171
I've crashed about 5 times in the past couple of hours interacting with different canned beverages, I'll add more details in the other issue

**Closed** 2019-10-31 10:06 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Items / Item Actions / Item Qualities
