### ISSUE TITLE
(MoM) batch-crafting centering meditation does not increases its effects

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#67311] opened 2023-07-30 18:05 UTC
### Describe the bug

Successfully crafting a centering meditation will reduce psy-drain by 1

Successfully batch-crafting multiple centering meditation will only reduce psy-drain by 1, no matter how many were crafted at once

I didn't checked but it might also affect non-MoM EoC-using recipes

### Attach save file

N/A

### Steps to reproduce

1. Get lots of psydrain and note the value
2. Craft one meditation, notice how the value went down by one
3. Batch-craft multiple meditations at once, notice how the value only went down by one despite taking way more time and weariness

### Expected behavior

Being able to batch-craft meditations instead of needing to start each one manually

### Screenshots

![PsyBug1](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/a5842b0d-bf10-4e4d-9af7-7b7abdf5eb80)
Starting value

![PsyBug2](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/19ed9737-196b-41de-92b4-87a8017d10d9)
After crafting one meditation

![PsyBug3](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/63354f24-e43f-4ca0-81bf-67fa6df298e7)
After batch-crafting five more meditations at once

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: d48e1a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

**Comment by mqrause** [comment] 2023-07-30 19:19
Duplicate of #66671

**Closed** 2023-07-30 20:58 UTC
Labels: (S1 - Need confirmation)
