### ISSUE TITLE
`D`ropping all non-favorite items results in spilled liquids

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#41724] opened 2020-07-01 12:23 UTC
# Describe the bug

# Steps To Reproduce

load the game
`D`
any direction button
`,` to select non-favorite items
`Enter`
observe puddles and empty containers on the target tile

# Expected behavior

Liquids staying in the containers.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3643-ga1e694840a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.06.30-41706.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4857780/2020.06.30-41706.zip)

**Comment by anothersimulacrum** [comment] 2020-07-02 02:49
Duplicate of #41126

**Closed by anothersimulacrum** 2020-07-02 02:49 UTC
Labels: (S3 - Duplicate)
