### ISSUE TITLE
Unarmed attacks with the Claw mutation not causing any damage or bleeding

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#56439] opened 2022-03-28 19:14 UTC
### Describe the bug

After mutating the Claw trait through any of the necessary mutation branches, it will not actually cause you to do any extra damage in melee unarmed combat. It will not cause bleeding, it will not cause slashing bonuses - the trait simply does not trigger.

### Steps to reproduce

1. Either spawn with the Claw trait, or mutate it (I did so by using a Rat primer + mutagenic cataclyst)
2. Attack any flesh enemy with unarmed attacks

### Expected behavior

Claws should improve your unarmed damage + inflict bleeding on enemies made of flesh.

### Versions and configuration

build type: windows-tiles-x64
build number: 2022-03-22-1513
commit sha: 8d98924ce1c4f01d96ce3a7aeba856b874296b4d
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/8d98924ce1c4f01d96ce3a7aeba856b874296b4d

**Comment by Heitomos** [comment] 2022-03-29 13:45
Probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56138

Being fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/56325

**Closed** 2022-05-17 23:10 UTC
Labels: (S2 - Confirmed), Mutations / Traits / Professions/ Hobbies
