### ISSUE TITLE
Unable to destroy/crack open weapon safe with jackhammer

### ISSUE THREAD

**Issue by bsarkisov** [CleverRaven/Cataclysm-DDA#58963] opened 2022-07-04 11:47 UTC
### Describe the bug

There is no way to crack open weapon safe with jackhammer

### Steps to reproduce

1. Grab a gasoline-powered jackhammer
2. 'a'ctivate it
3. Choose tile with safe
4. Get `You can't drill there.` message

### Expected behavior

I expected (as per confirmad by people on CDDA Discord) that jackhammer would be able to crack safe open.

### Screenshots

<img width="119" alt="Screenshot 2022-07-04 at 14 47 18" src="https://user-images.githubusercontent.com/18114161/177148661-7b582994-5015-4ece-b27e-453968398f46.png">

### Versions and configuration

MacOS X Monterrey 12.4
0.F-9481-g80d1beea36 - via `brew install cataclysm --HEAD`
Tiles
Engish
No changes to mods configuration - installed and played right away

**Comment by bsarkisov** [comment] 2022-07-04 13:38
Confirmed on latest experimantal build.

**Comment by RelMayers** [comment] 2022-07-08 21:46
Jackhammer to open safe? From what I understand jackhammer is better suited to break stone rather than steel.

**Comment by bsarkisov** [comment] 2022-07-09 15:58
I had the same understanding until googleing and asking in CDDA Comminuty discord proved it should be usable to break safes.

**Comment by raeflondon** [comment] 2022-08-30 02:33
Looks intentional per #50436.

**Comment by Night-Pryanik** [comment] 2022-11-16 05:32
Closing as it's working as intended.

**Closed by Night-Pryanik** 2022-11-16 05:32 UTC
Labels: (S1 - Need confirmation)
