### ISSUE TITLE
Cash card has high volume

### ISSUE THREAD

**Issue by maxime1147** [CleverRaven/Cataclysm-DDA#40918] opened 2020-05-28 11:51 UTC
# Describe the bug

Cash card is really big, wouldn't fit in a normal ATM machine...

# Steps To Reproduce

Find cash card on zombie corpse.

# Expected behavior

Well, I believe it should be smaller.

# Screenshots

![image](https://user-images.githubusercontent.com/12605195/83137736-a96a5980-a0b7-11ea-9449-5f7f736b8793.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2572-gb7cd69d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    Graphical Overmap [Graphical_Overmap],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I don't know if all cash card would spawn this big, but that specific one was 42.17 L.

**Comment by ZhilkinSerg** [comment] 2020-05-28 14:31
Duplicate of #40902

**Closed by ZhilkinSerg** 2020-05-28 14:31 UTC
