### ISSUE TITLE
Ring of speed +3, +5, +7 +, and +10 are adding to much speed

### ISSUE THREAD

**Issue by CrowbarZef** [CleverRaven/Cataclysm-DDA#50092] opened 2021-07-20 19:45 UTC
### Describe the bug

Each ring is adding 300. 500. 700. 1000 speed respectively.

### Steps To Reproduce

1.Create any character
2.Put on ring of speed
3.Zoom zoom

### Expected behavior

Expected behavior is adding either a percentage or a flat amount of speed that doesn't trivialize the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 42aef0c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex]
]

**Comment by casswedson** [comment] 2021-07-20 19:47
Duplicate of  #49891

**Comment by actual-nh** [comment] 2021-07-20 19:56
Noted in #49891.

**Closed by actual-nh** 2021-07-20 19:56 UTC
Labels: (S3 - Duplicate), <Bug>, Game: Balance, Mechanics: Enchantments / Spells, Mods: Magiclysm
