### ISSUE TITLE
Traditional Chinese translation broken after build 10317

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#38072] opened 2020-02-16 18:12 UTC
As title
build 10316
![image](https://user-images.githubusercontent.com/6245453/74610013-6993ed80-512a-11ea-9a45-b921c514572c.png)
build 10317
![image](https://user-images.githubusercontent.com/6245453/74610055-c7283a00-512a-11ea-9a04-5c76c33a1920.png)

My guessing is it's causing by the "Allow user font dir" feature
![image](https://user-images.githubusercontent.com/6245453/74610043-9ba54f80-512a-11ea-8594-b8562117c0e1.png)

It will be appritiated if one can provide a guide about this feature.

**Comment by Drakasin** [comment] 2020-02-16 20:32
Every time I update I have to copy the "font" folder from the CataclysmDDA\data folder to just root CataclysmDDA\ font folder otherwise the font in-game is all wonky and unreadable on windows.

**Comment by jkraybill** [comment] 2020-02-16 20:57
This should be fixed by #37919, but that hasn't been merged yet. In the meantime, the workaround that @Drakasin mentions has been working for people.

**Comment by ZhilkinSerg** [comment] 2020-02-16 22:29
Duplicate of #37916

**Closed by ZhilkinSerg** 2020-02-16 22:29 UTC

**Comment by vivi00790** [comment] 2020-02-17 02:43
> Every time I update I have to copy the "font" folder from the CataclysmDDA\data folder to just root CataclysmDDA\ folder otherwise the font in-game is all wonky and unreadable on windows. I'd try that.

Thanks for the workaround. Works like a charm. 😄
