### ISSUE TITLE
Game crashes due to SegFault error when reloading mounted weapon

### ISSUE THREAD

**Issue by borzykin** [CleverRaven/Cataclysm-DDA#61077] opened 2022-09-17 17:22 UTC
### Describe the bug

Game crashes due to SegFault error when reloading mounted weapon

### Steps to reproduce

1. Unload M240 on armored vehicle from save
2. Try to reload M240 on armored vehicle
3. Observe the result

### Expected behavior

M240 should be reloaded with provided ammo strip

### Screenshots

![image](https://user-images.githubusercontent.com/46842710/190868928-6d61cd73-0d33-4671-a318-c54afa709365.png)

### Versions and configuration

OS: Win 10 x64
Game version: cdcb071 (tiles)
Build: 2022-09-17-0626

### Additional context

Logs: https://www.dropbox.com/s/7oe378p7hgzovuv/config.7z?dl=0
Savegame: https://www.dropbox.com/s/acdpr3pnzmcq2ch/Kekston_copy1.7z?dl=0

**Comment by actually-a-cat** [comment] 2022-09-17 17:48
Duplicate of #61031, to be fixed by #61046.

**Comment by ZhilkinSerg** [comment] 2022-09-17 18:08
Duplicate of #61031

**Closed by ZhilkinSerg** 2022-09-17 18:08 UTC
Labels: (S3 - Duplicate)
