### ISSUE TITLE
`(I)gnore further distractions and finish` doesn't work when reading martial art training manual until exhaustion

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38460] opened 2020-02-29 16:36 UTC
# Describe the bug

# Steps To Reproduce

Load the game and read the available manual.

# Expected behavior

Ignoring the noises ignoring them for good.

# Screenshots

![](https://tinystash.undef.im/il/4AUmtN7hULyYnHgi45VhLr9nuEbbviwVYmMNJdgDsffVARrbr6H18faWAqXw6w7QmJ8iiWeMP1RckP3drRVbNoHp)

# Versions and configuration
Today's master.

# Additional context
[2020.02.22-1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4270582/2020.02.22-1.zip)

**Comment by Night-Pryanik** [comment] 2022-08-28 16:13
Tested right now on 0.F-10914. Started to read martial art training manual (`Beautiful Springtime`) and when I was interrupted by giant ants' footsteps, I selected `Ignore further distractions and continue`. I was able to continue reading and training without any future interruptions due to noise.

I'm closing this right now, if this issue is still valid and reproducible, ping to reopen.

**Closed by Night-Pryanik** 2022-08-28 16:13 UTC
Labels: <Bug>, Controls / Input
