### ISSUE TITLE
Crash bug in smart inventory - with steps to replicate

### ISSUE THREAD

**Issue by dkalnins** [CleverRaven/Cataclysm-DDA#22765] opened 2018-01-15 05:40 UTC
Game version: Cataclysm-0.C-7052.dmg

Operating system: OSX 10.11.6 El Capitain

### Expected behaviour
Contents of two side by side inventory panels to be swapped.

### Actual behaviour
Immediate crash to desktop - no exception caught.

### Steps to reproduce the behaviour
1. Open up smart inventory with the "/" key on a character that has items in their inventory.

2. Select the left hand inventory panel using tab, unless its already selected / in focus.

3. Add a filter using "/" so that the inventory now appears empty (eg. search for XXX) and accept it using return.

4. Exit the smart inventory screen using ESC

5. open the smart inventory screen again. On the left hand panel the Inventory "I" should be selected, the filter for XXX is still displayed at the bottom and the inventory panel shows no items (because there are no matches).

6. Press "I" when the focus is in the left hand panel, and the game crashes

Its feels like the code assumes that there will be a structure to hold the contents of the inventory and it just swaps it. However the code to load the up the panel in the case where there is a filter with no content has not "built" the structure / class.

**Comment by AMurkin** [comment] 2018-01-15 06:14
What is your interface option "Open default advanced inventory layout" value?

**Comment by dkalnins** [comment] 2018-01-15 06:27
It is set to false

**Comment by Night-Pryanik** [comment] 2018-02-21 17:02
Can't confirm. Anyone else tested this issue?

**Comment by Night-Pryanik** [comment] 2018-02-23 06:31
Tested on 0.C-7143, Windows XP SP3 x86, can't reproduce. Closing for now. If this still an issue, ping me.

**Closed by Night-Pryanik** 2018-02-23 06:31 UTC
Labels: Confirmation Needed, Crash / Freeze, Inventory / AIM
