### ISSUE TITLE
Can do some activities while riding a mount that should be impossible

### ISSUE THREAD

**Issue by Rail-Runner** [CleverRaven/Cataclysm-DDA#31284] opened 2019-06-09 18:20 UTC
# Describe the bug

While player is riding a mount, they can do any of the following:
1. Examine an adjacent tile to pick up items from there (but they can't do the same if they stand on the tile and try to use grab command)
2. Dig a pit (and do any other shovel-related actions) via activating a shovel or other digging tool.
3. Use Burrow mutation to dig pits, burrow into walls, and do other things that it normally allows to do.
4. Dig through walls via activating a jackhammer or a pickaxe.
5. Try to sleep via "sleep" command.
6. Access use actions of nearby items on the ground.
7. Use Probability Travel CBM to tunnel through walls. Also notice that the mount doesn't move along with you until you move somewhere, staying in the old place until then. Monsters can attack the mount while it stays there. If killed, mount loot is dropped on its old place, and player is downed on new location.
8. Use teeth and horn mutations to attack.
9. Use martial arts with no restrictions. (I don't think that all martial arts should be unavailable, but moves that depend a lot on posture shouldn't be available.)
10. Place traps by activating them.
11. Pick locks by activating a lockpicking tool.
12. Pry open doors or windows by activating a prying tool like a crowbar.
13. Step into a web field, and notice that the mount gets webbed effect, but isn't immobilized. Player isn't affected either.
14. Move into acid field and get leg damage (mount gets hurt too, though)
15. Move into a pool of sap field, and get coated in sap instead of the mount.
16. Move into a "goo pit" trap, get your mount transformed into a blob, fall off of it, notice that it is friendly (though it doesn't follow you around anymore). After this happens, bag (if any was attached) stays attached to the blob (but can be detached), and the saddle (if mount had any) just disappears. Also monster transformed into a blob inherits the monster's name, if any was given by player. More generally, the same thing seems to happen to all friendly monsters transformed into a blob this way.
17. Use a teleporter and notice that the mount doesn't teleport along with you until you move somewhere, staying in the old place until then. Monsters can attack the mount while it stays there. If killed, mount loot is dropped on its old place, and player is downed on new location.
18. Use a teleporter item near deep water, get teleported into deep water, try to move anywhere and find out that you can't move; the only option is to dismount, after that the mount drowns and the player starts swimming.
19. Get Urticating Hairs mutation and get hit by another monster; notice that despite the mount being hit, the mutation's on-hit effect still triggers against that monster. Probably works the same way for Quills and similar mutations.

# Steps To Reproduce

1. Get a friendly monster which can be mounted, and mount it.
2. Try to do something from the list above.

# Expected behavior

1-12: Not being able to do so.
13. Not being able to move around while the mount is webbed; perhaps player getting webbed too.
14. Player not suffering leg damage (only mount should get hurt)
15. Mount getting coated in sap, instead of player.
16. Spawned blob not being friendly to the player, dropping bag and the bag's contents, dropping the saddle, and not inheriting the transformed monster's name.
17. Either player dismounting the mount, or mount teleporting along with the player immediately. 
18. Player dismounting automatically if this happens.
19. Those mutation effects not triggering when the mount is hit.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-4118-ga74f0c6
 - Graphics version: Tiles
 - Mods loaded: DDA only.

# Additional context

Tested all edge cases related to riding a mount that I could think of, posted all found bugs here. I didn't test animals pulling vehicles yet, though.

**Comment by davidpwbrown** [comment] 2019-08-11 11:20
oops didnt see this before.

Thanks for listing stuff, I will get around to this next, as im working on riding now, and re-familiarising myself with what I did before.

**Comment by davidpwbrown** [comment] 2019-08-12 15:27
sap and web affect monsters and players differently for some reason, it appears.

when monster is in sap field, it loses moves, but when player is in sap field, they get sapped effect.

Horse goes into those fields, and gets the effects, but player does not, not sure if this is working as intended or not.
Will look into that further, and the melee changes are a bit complicated.

But the disallowing certain iuse and iexamine actions ive got a fix coming for.

**Comment by anothersimulacrum** [comment] 2021-09-15 20:14
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/33165

**Closed by anothersimulacrum** 2021-09-15 20:14 UTC
Labels: <Bug>, Monsters, Items / Item Actions / Item Qualities, Mechanics: Character / Player
