### ISSUE TITLE
Lighting issues while driving.

### ISSUE THREAD

**Issue by VladTechGames** [CleverRaven/Cataclysm-DDA#68310] opened 2023-09-25 02:21 UTC
### Describe the bug

Within the last 3 days of updates a flashing icon on the player and seemingly slow to update lighting have started happening

Reinstalled the game to make sure, still occurred. Checked other tile sets as well to no avail. 

### Attach save file

N/A

### Steps to reproduce

Drive a vehicle.

### Expected behavior

I expected the lighting to behave normally, it is not.

### Screenshots

![Capture](https://github.com/CleverRaven/Cataclysm-DDA/assets/144631237/c128d37b-ce26-416f-99d7-ec06055bdcc5)

https://github.com/CleverRaven/Cataclysm-DDA/assets/144631237/304040f6-68f9-4560-9191-a1392d681903

### Versions and configuration

Windows 10
Version 46822d6
Tiles: UltiCa
English
DDA, Disable NPC need, Portal storms ignore NPCs, Slowdown Fungal Growth.

**Comment by RenechCDDA** [comment] 2023-09-25 02:24
Duplicate of #68121

**Closed by RenechCDDA** 2023-09-25 02:24 UTC
Labels: (S1 - Need confirmation)
