### ISSUE TITLE
duplicated save and saving crashes

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#33141] opened 2019-08-11 13:30 UTC
[<!--]
![errormessage](https://user-images.githubusercontent.com/44286709/62834440-9fde4500-bc8f-11e9-8e7b-283547f6abfe.png)

While driving through a city I saved and got an error message, when I tryed loading back into the world I noticed I had two saves under the same name but they seemsed to both access the same file, after that whenever I tried saving while driving a similar error would come up and crash the game, saving my character's positon but not the car's. After a while of this it started effecting me even when I got out of the car so I have no idea what to do. I'm using a few mods like blazemod, more survival tools, extended guns and the like.

**Comment by anothersimulacrum** [comment] 2019-08-11 14:21
I got these symptoms as a result of #33051, it's possible this is a duplicate of that.

**Comment by ampersand55** [comment] 2019-08-11 15:52
Same here. Annoyingly my vehicle I was riding also disappeared. 

You can probably fix the two saves under the same name thing by removing .temp files in your save directory.

**Comment by Mister-Cultist** [comment] 2019-08-12 05:26
> 
> 
> Same here. Annoyingly my vehicle I was riding also disappeared.
> 
> You can probably fix the two saves under the same name thing by removing .temp files in your save directory.

deleting the temp files fixed the duplicate saves. But I'm still crashing on save.

**Comment by EkarusRyndren** [comment] 2019-08-12 06:18
> Same here. Annoyingly my vehicle I was riding also disappeared.
> 
> You can probably fix the two saves under the same name thing by removing .temp files in your save directory.

You'll find your vehicle wherever it was when you saved last. I'm also encountering this issue.

**Comment by Mister-Cultist** [comment] 2019-08-12 10:19
I figured that out so now the problem is that I just can't move my car and still crash all the time

**Closed** 2019-08-12 17:25 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
