### ISSUE TITLE
Steadying aim with finger-mounted laser CBM causes segmentation fault

### ISSUE THREAD

**Issue by hagamablabla** [CleverRaven/Cataclysm-DDA#59226] opened 2022-07-13 11:54 UTC
### Describe the bug

When aiming with the finger-mounted laser, steadying aim will crash the game. When firing another gun, specifically an M1 Garand, no crashes occur.

I do have one custom mod activated, which I have included below. It creates a container with infinite carrying capacity. The same bug occurs on a fresh world without the mod, however.

### Steps to reproduce

1. Install and activate the finger-mounted laser CBM.
2. '.' to steady aim.

Alternatively,

1. Install and activate the finger-mounted laser CBM.
2. 's' to switch to an aiming mode other than 'immediate'.
3. 'f' to fire.

### Expected behavior

The laser should not crash the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 704a963 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bag of Holding [bag_of_holding]
]

### Additional context

[Logs](https://github.com/CleverRaven/Cataclysm-DDA/files/9101778/logs.zip)
[Save file](https://github.com/CleverRaven/Cataclysm-DDA/files/9101785/Islamorada.zip)
[Custom mod](https://github.com/CleverRaven/Cataclysm-DDA/files/9101787/bag_of_holding.zip)

**Comment by mqrause** [comment] 2022-07-13 12:36
I might have accidently fixed this already in #58625. At least I can't reproduce it with that, but it crashes in current experimental. I can't test it more thoroughly right now.

**Comment by mqrause** [comment] 2022-07-13 20:34
/confirmed

Nope, not fixed by the other one, it happens when you don't wield anything because `avatar::rebuild_aim_cache` expects you to wield the thing you're aiming with. But pseudo items from bionics aren't wielded because they don't exist. Preventing the crash is easy, but I'm not sure how to deal with the aim cache using the wrong weapon when shooting with fake items.

**Closed** 2022-07-14 00:58 UTC
Labels: (S2 - Confirmed)
