### ISSUE TITLE
Unable to generate a valid starting location Desert Island

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54600] opened 2022-01-20 05:45 UTC
### Describe the bug

Started a new game in Helicopter Crash scenario. Got the error (see below). After pressing a button, got shoved back into main menu.

```
Unable to generate a valid starting location Desert Island
[sloc_desert_island] in a radius of 3 overmaps, please report this failure.
```

![20220120-053837-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150280072-623ff802-9aae-40d7-8624-c0699927605e.png)

<details>
<summary>Nothing of interest in the debug.log</summary>

```


-----------------------------------------
05:30:38.687 : Starting log.
05:30:38.687 INFO : Cataclysm DDA version 56ae13e
05:30:38.688 INFO : [main] C locale set to C
05:30:38.688 INFO : [main] C++ locale set to C
05:30:38.688 INFO : SDL version used during compile is 2.0.14
05:30:38.688 INFO : SDL version used during linking and in runtime is 2.0.14
05:30:38.711 INFO : Number of render drivers on your system: 5
05:30:38.711 INFO : Render driver: 0/direct3d
05:30:38.711 INFO : Render driver: 1/direct3d11
05:30:38.711 INFO : Render driver: 2/opengl
05:30:38.711 INFO : Render driver: 3/opengles2
05:30:38.711 INFO : Render driver: 4/software
05:30:38.718 INFO : [options] C locale set to C
05:30:38.718 INFO : [options] C++ locale set to C
05:30:38.718 INFO : Setting language to: 'en'
05:30:38.718 INFO : [i18n] Scanning core translations from lang/mo/
05:30:38.718 INFO : [i18n] Scanning mod translations from ./mods/
05:30:38.720 WARNING : opendir [./mods/] failed with "No such process".
05:30:38.970 INFO : Active renderer: 1/direct3d11
05:30:39.104 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
05:30:39.131 INFO : Setting language to: 'en'
05:30:39.394 WARNING : opendir [./mods/] failed with "No such process".
05:30:45.256 WARNING : opendir [./save/Maynard/mods] failed with "No such process".
05:30:55.664 INFO : Loaded tileset: UltimateCataclysm
```

</details>

Not sure how this report is useful to whoever put that error handling in place.

Probably unsurprisingly, the world did get created, but not the character. Attaching just in case that's useful.

Trying to start new helicopter crash scenario after the error worked just fine (both with random location, and also specifically with desert island one
[Maynard.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7902619/Maynard.zip)

### Steps to reproduce

idk.

### Expected behavior

game worky

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LeahLuong** [comment] 2022-01-20 06:22
Dupe of #35376.

Desert islands are rare. World gen settings can make them practically non-existent. That bug is there to prevent endless searches, among other things.

**Closed** 2022-01-20 06:35 UTC
