### ISSUE TITLE
Mouse input not working in the escape menu

### ISSUE THREAD

**Issue by Keltas** [CleverRaven/Cataclysm-DDA#75900] opened 2024-08-23 13:36 UTC
### Describe the bug

In the escape menu when using LMB, the option highlighted by the mouse is not respected. Rather it selects the top option (view help) or the option highlighted by the keyboard beforehand. I believe this issue is likely since #74341 .

### Attach save file

N/A

### Steps to reproduce

1. While in game press escape to open the menu.
2. Mouse over an option that is not the top one.
3. Use LMB (or enter) to choose the highlighted option.
4. Observe as the Help window opens instead.

### Expected behavior

I expect the chosen option to be opened instead.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 6848495 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    <color_cyan>Arcana</color>/DinoMod Patchmod [Arcana_Dinomod_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Bombastic Perks [bombastic_perks],
    Keltas Mod [kelmod],
    Xedra Class Unrestriction [xedra_unrestriction],
    Useful Helicopters Experimental [useful_helicopters],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Aftershock [aftershock]
]

**Comment by db48x** [comment] 2024-09-03 10:42
Duplicate of #76033

**Closed** 2024-12-31 15:54 UTC
Labels: (S1 - Need confirmation)

**Comment by Brambor** [comment] 2024-12-31 15:57
> It also doesn't work right in zone creation menu when you choose a category..

If it is this one:
![image](https://github.com/user-attachments/assets/f6396992-bba9-4f65-bfe8-2b296729e027)

it works now.

However, visually, there is some cursed double selection...
