### ISSUE TITLE
"Junk food" tag applied too liberally?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19810] opened 2016-12-19 13:37 UTC
Having recently pickled up the Junkfood Intolerance mutation, I'm a bit surprised at how many items the game classifies as junk food.

For example, mustard, ketchup, popcorn (unsalted, unbuttered), pretzels (plain), chewing gum, graham crackers, and cheese spreads.  Some things are more ambiguous like maple syrup, coffee syrup, and condensed milk, since those are more high calorie concentrated foods rather than junk foods per se, (which a lot of military MREs also are; concentrating as many calories and nutrients in as small packages as possible).

So what are your thoughts on what exactly the definition of junk food should be? And should we trim back what's categorised as a junk food, or is it fine as it is?

**Comment by Coolthulhu** [comment] 2016-12-19 14:07
Junk food has no concrete, measurable definition.
It's better to apply it too liberally than too strictly, because it doesn't have enough worthwhile entries.

Generally, if it tastes good and isn't very nutritious, it's junk. Or if it is very processed and not nutritious. In some rare cases (corn stuff) if it is just not very nutritious and doesn't fit any other category.

For example:
* MREs are processed and calorie dense, but they're designed to be complete meals. Could count as junk if we decide that they're only complete with the multivitamin
* Mustard is an allergen
* Ketchup usually contains multiple allergens and chemical additives meant to enhance the taste and shelf life. Also lots of salt.
* Corn is rather low in most nutrients. Having all mostly-pure corn products count as junk would be fine
* Pretzels are salty
* Jerky/salted fish is arbitrarily not junk despite being salty. But could be junk - this would make the intolerance matter a fair bit more and be more consistent.

There will always be arguments about healthy vs unhealthy. The only option to stop them all is to remove the labels (and the trait) altogether. Until that happens, it's all arbitrary to an extent.

When applying arbitrarily, the most important factor in deciding where to put the line should be game balance.
At the moment junkfood intolerance only really matters for stacking morale effects. Other than that, junk food items are mostly subpar to alternatives.

**Comment by Zireael07** [comment] 2016-12-19 14:25
Pretzels are VERY salty and heavily processed, much more so on both counts than the fish.

Are there highly processed fish postproducts in the US that could go into junk food as the game understands it, without touching salted fish as such?

**Comment by keyspace** [comment] 2016-12-19 15:14
> At the moment junkfood intolerance only really matters for stacking morale effects. Other than that, junk food items are mostly subpar to alternatives.

It also seems that [allergies prevent vitamin absorption](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/consumption.cpp#L78).

**Comment by Regularitee** [comment] 2016-12-19 23:51
While sweet, condensed milk probably shouldn't be considered a junkfood if it's watered down derivative -- milk -- is considered healthy. 

I'm not sure I follow the logic behind allergens (ketchup, mustard) making them qualify as junk food. Could you elaborate on that?

**Comment by Coolthulhu** [comment] 2016-12-20 02:46
> I'm not sure I follow the logic behind the idea that allergens (ketchup, mustard) automatically qualify as junk food.

Not automatically. The whole junk food brand is arbitrary - things are "junk enough" if they are "unhealthy enough".
For ketchup and mustard, allergens are just a part of the equation. Other than that, it's salt, sugar, tomatoes being concentrated and general association of those spices with fast food.

I'm sure many people would qualify bacon and beer as junk food.

Unless someone can provide a less arbitrary definition that can be applied to a sufficiently large group of items, we're stuck with the vague one.

> It also seems that allergies prevent vitamin absorption.

Doesn't matter for junk food, which only gets any of them when mixed with other types.

**Comment by AMurkin** [comment] 2016-12-20 11:41
Beer as junk food? No way! :)
Vote for less strict rules if i could.

**Comment by BurgerFan45** [comment] 2016-12-21 03:43
Honestly there is no problem with excessive labeling, as it makes your character your typical health drone who thinks almost everything not "natural" is bad for them.

The problem is that all of the foods labeled as junk food actually reduces your hidden health stat.
Which perpetuates that certain foods are healthy and others are unhealthy. Which currently has no grounding in reality.

> if it tastes good and isn't very nutritious

Then it is food that tastes good that will require you to eat more nutritional food (which in game is currently in terms of vitamins) later on to make up for it.

> if it is very processed and not nutritious

Then it is food that is easier to digest and less likely to make you sick but will also require you to consume more nutritious food down the line (again, you might need to just take vitamin supplements to make up for it).

Of course binge eating candy is going to make you sick. But it shouldn't make you automatically catch influenza all of the sudden.

**Comment by Coolthulhu** [comment] 2016-12-21 08:27
> The problem is that all of the foods labeled as junk food actually reduces your hidden health stat.

Health stat is from before vitamins existed. Vitamins were supposed to replace it, though they weren't received too well so they're in a kind of limbo.

> Of course binge eating candy is going to make you sick. But it shouldn't make you automatically catch influenza all of the sudden.

Neither it does in the game. It just increases your chance of catching it.

**Comment by Barhandar** [comment] 2016-12-21 17:10
@Coolthulhu 
>though they weren't received too well  

Because they were mainlined in an awkward, you-cannot-survive-on-food-alone-and-must-consume-multivitamin state, mostly caused by automatically generating them for foods.
>I'm sure many people would qualify bacon and beer as junk food.  

I'm definitely qualifying most brands of bacon and beer as junk food. I've tasted microbrewed beer and bacon made by actual people from their own pigs.
@Regularitee 
>For example, mustard, ketchup, popcorn (unsalted, unbuttered), pretzels (plain), chewing gum, graham crackers, and cheese spreads.  
>I'm not sure I follow the logic behind the idea that allergens (ketchup, mustard) automatically qualify as junk food. 

Storebought mustard is definitely junk food - it's conservant-laden. Ditto ketchup, ditto chewing gum, ditto cheese spreads. It's "junk" in the sense that it can easily be bad for you, and it's "junk" in the sense that it's low quality.
@BurgerFan45 
>Then it is food that is easier to digest and less likely to make you sick

Not necessarily so on both counts. Less likely to contain living things that make you sick yes, it's the whole point, but you could have problems digesting whatever additives are used to preserve it, or even allergies. We're not to the point of Good Omens's Famine Foods, but pretty close.

**Comment by BurgerFan45** [comment] 2016-12-22 00:27
> But you could have problems digesting whatever additives are used to preserve it(processed foods), or even allergies.

Quite the contrary.
Here's an open access paper titled "Effects of food processing on food allergens"
https://www.ncbi.nlm.nih.gov/pubmed/19603400
And not all additives are bad. In order to tell if they are bad you have to have clinical studies performed with them, on each and every one separately.
monosodium glutamate is one of the best examples of a good additive, no downsides when used at regulatory levels.
And just because additives that are bad for you exist. Does not mean that they are being used in foods.

**Comment by Asmageddon** [comment] 2016-12-27 19:43
I think the junk food tag should be kept to snacks and stuff like burgers, etc. Either that, or increase the Junkfood Intolerance value to 2, because right now it excludes more foods than anything bar meat intolerance, which I do not think is a good idea, because at some point in the game, you're going to switch to obtaining and cooking meat(or farming), anyway.

**Comment by Coolthulhu** [comment] 2016-12-27 20:20
Junkfood intolerance isn't overly broad for that 1 point. Food it bans is only really useful for morale stacking (toastems).
It looks much harsher than lactose intolerance, but that's because lactose intolerance is barely more than a free point.

**Comment by didemaGibson** [comment] 2017-02-17 00:21
Maybe switch

**Comment by didemaGibson** [comment] 2017-02-17 00:23
Maybe switch out junkfood intolerance for a disease causing it irl like crohns or ibs?

**Comment by kevingranade** [comment] 2017-02-17 02:17
My main problem with calling it celiac disease or ibs or cronhs is that I
know those are actually a lot more nuanced than what we're doing, and I
don't want to claim to depict a real condition and then do a bad job of it.

**Comment by kevingranade** [comment] 2017-02-17 02:19
Actually this issue isn't going anywhere, closing.

**Closed by kevingranade** 2017-02-17 02:19 UTC
