### ISSUE TITLE
LIXA lab EOC activation fail to teleport player to site

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#78492] opened 2024-12-11 15:06 UTC
### Describe the bug

LIXA location EOC event active failed
In LIXA lab and already actived LIXA_unfold_setup 
But i'm not sent to that "unfold location" but stayed in the place.
Only on the right showing Place is "anywhere",but actually im actually still in that lab.

### Attach save file

[mor-trimmed.tar.gz](https://github.com/user-attachments/files/18097537/mor-trimmed.tar.gz)

### Steps to reproduce

ignore those errors.These are irrelavant entertainmant and beautify mods.
As you enter the save,you can see im in LIXA lab and already actived LIXA eoc
But i'm not sent to that "unfold" location but stayed in the place,only on the right showing Place is "anywhere" 

### Expected behavior

EOC activate failed and you cannot go to LIXA "unfold location" that infinite gallery room.

### Versions and configuration

-OS windows11
-language en(English)
-version 09f30df
-mod loaded:[
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "ProjectKawaii",
  "MST_Extra",
  "perk_melee_system",
  "stats_through_kills",
  "Tamable_Wildlife",
  "cbm_slots",
  "speedydex",
  "culinary_days_ahead"
]

### Additional context

I tried to move my save and test on newer version,but for "this" save it's still not working.

**Comment by ShuCuoMao** [comment] 2024-12-11 15:18
re-explain for issue 78216

**Comment by molkemon** [comment] 2024-12-11 19:53
This is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/76479

The error is not in the LIXA EOC, it works exactly as intended, the error is in mapgen. Mapgen is supposed to place teleport points as global variables, but fails to do so for unknown reasons.

I have made a workaround explained in the other issue which will set the missing teleport points via the EOC, this will allow progression on your save, see here: https://github.com/CleverRaven/Cataclysm-DDA/issues/76479#issuecomment-2526653579

**Closed** 2024-12-12 01:55 UTC
Labels: (S1 - Need confirmation)
