### ISSUE TITLE
NPCs throw weapons

### ISSUE THREAD

**Issue by Xomikadze** [CleverRaven/Cataclysm-DDA#49882] opened 2021-07-12 08:24 UTC
### Describe the bug

Good day. I have such a problem, all the companions who go with me throw their weapons instead of using them correctly. For example, I give a pistol crossbow and bolts. He takes and throws a crossbow at the enemy and bolts on the ceiling. It's the same with regular melee weapons. And when they run out of ammunition, they begin to throw out the armor. It only seems to work fine with firearms.

### Steps To Reproduce

1. Create the world
2. I choose the scenario in the shelter with a companion (evacuee)
3. If you enter into a fight with him, he will throw a weapon at you.

### Expected behavior

NPC will beat me with it.

### Versions and configuration

- OS: Windows 10
- Game Version: 259b56c (Experimental version)
- Graphics version: Chibi_Ultica
- Ingame language: Russian
- Mods loaded: -

### Additional context

I'm not sure which version it came from, but now the problem is urgent.

**Comment by Xomikadze** [comment] 2021-07-12 08:40
It looks like this is the same problem as [https://github.com/CleverRaven/Cataclysm-DDA/issues/49834](url)

**Comment by Resok** [comment] 2021-07-12 08:42
Yup - dupe of #49834

**Closed** 2021-07-12 11:37 UTC
Labels: (S3 - Duplicate), NPC / Factions
