### ISSUE TITLE
Items can be duplicated by exchanging with companions.

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#50454] opened 2021-08-03 07:53 UTC
### Describe the bug

Any item may be duplicated if it can fit into a companion's inventory.

### Steps To Reproduce

1. Equip a companion with clothing with pockets and a pack.
2. Give them items to hold.
3. Open the trade screen and select both the item or items to be duplicated and the clothing items that contain those same items and complete the exchange.
4. You're survivor will now have the container with the item inside and an duplicate item.

### Expected behavior

I would expect the marked item would be unmarked when the container is also marked for trade because one item cannot be traded in two separate instances.

### Versions and configuration

- Win7
- Frank (0.F Stable)

**Comment by GoLoT** [comment] 2021-08-03 13:13
Duplicate of #46874

**Comment by RoyBerube** [comment] 2021-09-06 20:17
I expect a solution can be similar to PR #46486

**Closed** 2021-09-28 16:15 UTC
Labels: <Bug>, NPC / Factions, <Exploit>
