### ISSUE TITLE
Animal Foods No Longer Work

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#76531] opened 2024-09-18 18:41 UTC
### Describe the bug

When trying to use animal food, the player automatically tries to eat it, regardless of what the action menu says. I've seen it on both bird and dog food now.

Apologies if this is a duplicate - I did my best searching for it.

### Attach save file

[New Magic-trimmed.tar.gz](https://github.com/user-attachments/files/17048796/New.Magic-trimmed.tar.gz)

### Steps to reproduce

1. Acquire food
2. Approach appropriate un-tamed animal
3. (A)ctivate food
4. Observe as player tries to eat food

### Expected behavior

Food used to tame animal

### Screenshots

![image](https://github.com/user-attachments/assets/bfdf13aa-3a12-47a8-bdfa-78ebe223a9f3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: abbb6ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Maybe related to built in tameable wildlife mod? Or combination with MoM?

![image](https://github.com/user-attachments/assets/2b21c62f-64d9-4dba-bcd2-288e4815d1e4)

**Comment by DeftGrain** [comment] 2024-09-18 22:31
It is a duplicate, it's due to the new purifying water.

**Comment by RenechCDDA** [comment] 2024-09-19 00:51
Duplicate of #76414

**Closed by RenechCDDA** 2024-09-19 00:51 UTC
Labels: (S1 - Need confirmation)
