### ISSUE TITLE
Destroying a helicopter while directly above an enemy results in player hovering in mid-air 

### ISSUE THREAD

**Issue by Widdershin** [CleverRaven/Cataclysm-DDA#49044] opened 2021-05-27 14:16 UTC
# Describe the bug

If the player's helicopter is destroyed while flying (for example, through a flying enemy contacting the rotors), and that player is above an enemy, the player will end up at Z+1, with the option to then climb down. While in this position, the play can not be attacked by grounded enemies.

# Steps To Reproduce

1. Start a new game
2. Give yourself helicopter piloting proficiency and spawn a helicopter, or obtain one naturally (undamaged 2seater2 used for this test)
3. Begin flying, ascend to Z+1
4. Spawn or find a crowd of zombies, and position yourself above it so that they cluster below you
5. Cause the helicopter to be destroyed (spawn a giant mosquito, wait till it's beside you, and then descend a single level to hit it with the rotors)

# Expected behavior

The player falls to the ground after the helicopter is destroyed. Ideally we'd take some damage in the process, but that's probably a separate issue.

# Actual behaviour

The player will stop falling if there is an enemy below them, and will remain at rest at Z+1 until deciding to climb down. Time can be passed while standing on top of said enemy.

# Screenshots

Helicopter at Z+1, with multiple zombies below
<img width="1440" alt="Screen Shot 2021-05-28 at 2 07 06 AM" src="https://user-images.githubusercontent.com/398365/119841122-a9ff2f80-bf59-11eb-96a4-0b604f059209.png">

Helicopter at Z+2, with a mosquito by the rotors
<img width="1440" alt="Screen Shot 2021-05-28 at 2 07 22 AM" src="https://user-images.githubusercontent.com/398365/119841134-acfa2000-bf59-11eb-9c21-25c8f628a7d3.png">

Immediately after descending and hitting mosquito
<img width="1440" alt="Screen Shot 2021-05-28 at 2 07 31 AM" src="https://user-images.githubusercontent.com/398365/119841144-ae2b4d00-bf59-11eb-8588-7a2549befc73.png">

Several turns later, still standing in the air above the zombies
<img width="1423" alt="Screen Shot 2021-05-28 at 2 07 42 AM" src="https://user-images.githubusercontent.com/398365/119841150-aec3e380-bf59-11eb-94cb-2031846012c9.png">

# Versions and configuration
- OS: MacOs
    - OS Version: Name: macOS; Version: 11.2.3; Build: 20D91; 
- Game Version: 901e4d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

    
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6554665/save.zip)

Save from just after last screenshot was taken.

Please note this was tested on the latest version of master at the time of writing, built locally but with no changes to the code or build process. I have not tested this on a nightly build, but I expect similar results.

**Comment by pehamm** [comment] 2021-05-27 17:51
Probably a duplicate of #47951, just executed a bit differently.

**Comment by actual-nh** [comment] 2021-05-27 22:03
Not completely sure - the asking you to climb down is an additional aspect, I think.

**Comment by Widdershin** [comment] 2021-05-28 02:00
Does seem like a duplicate to me, feel free to close out and I’ll retest
after the other issue is fixed

**Closed** 2021-05-28 15:36 UTC
Labels: (S3 - Duplicate), <Bug>, Z-levels
