### ISSUE TITLE
Small ammo box is larger than ammo box

### ISSUE THREAD

**Issue by Comrade-Soupbeans** [CleverRaven/Cataclysm-DDA#74875] opened 2024-07-03 03:40 UTC
### Describe the bug

As title

### Attach save file

N/A

### Steps to reproduce

look up items (in game or on hitchhiker's guide) and observe size and capacity of each

### Expected behavior

Item with "small" in the name would be smaller than the one without

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/26364270/6807a0db-7bab-46de-8438-85d7b0905492)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/26364270/6dcc88af-c753-4239-be11-178b2bb943e7)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: 9819962 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by CoroNaut** [comment] 2024-07-03 04:13
Another instance of an extremely simple issue becoming stale and being auto-closed by stale bot. #69697

**Comment by harakka** [comment] 2024-07-04 12:16
Duplicate of #69697

**Closed by harakka** 2024-07-04 12:16 UTC
Labels: (S1 - Need confirmation)

**Comment by GuardianDll** [comment] 2024-07-04 12:18
do we even track closed issues as favorable comparing to a new one?
