### ISSUE TITLE
Can't fire weapons into tiles that I can't see directly

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#45923] opened 2020-12-09 03:33 UTC
# Describe the bug
Currently if I press "fire" button while not aiming at any particular directly seen creature, the character aims instead by passing time and not actually shooting. I'm not sure if it's a bug or a feature, but often there are indirect ways when I know which direction I want to shoot: infravision, sound and electric receptors can all point to a creature and I want to be able to shoot it at, but I can't. 

# Steps To Reproduce

1. Go into a dark area
2. Get electroreceptors
3. Put a turret outside of night vision radius
4. Try shooting a rifle or a bow at its electrorecepted position

# Expected behavior

I expect to be able to shoot at any position regardless whether it's inside of my direct vision radius or outside of it.

# Screenshots

# Versions and configuration

Happens both in experimental and in stable.

# Additional context

**Comment by olanti-p** [comment] 2020-12-09 10:08
Duplicate of #39136

> Can't fire weapons into tiles that I can't see directly

You can't _aim_ there, but can still _fire_. It's likely you are using the "aim and fire" shortcut (Aimed shot, Precise shot, etc.), and that sometimes fails with unseen creatures / empty tiles ever since #38263.

**Comment by Raikiri** [comment] 2020-12-09 10:22
@olanti-p
> looks like you are using the "aim and fire" shortcut (Aimed shot, Precise shot, etc.), and that sometimes fails with unseen creatures / empty tiles ever since #38263.
this is exactly what I'm doing. and how come it fails "sometimes"? i expect it to either always work or never work, why does it shoot every 10th time I try to shoot?

I'm very confused that it's a feature and not a bug

**Comment by olanti-p** [comment] 2020-12-09 12:10
> how come it fails "sometimes"? i expect it to either always work or never work, why does it shoot every 10th time I try to shoot?

The calculations for aim thresholds are very complex, and depend on
 * gun
 * stats
 * skills
 * target (size, position, visibility)
 * selected aim mode
 * current aim level

Then there is also "aim maximum", which is very high for visible creatures, but pretty low for empty tiles / unseen creatures (see that PR I linked), up to the point where it can be lower then the "aim threshold".

So, after you start "aim and fire", one of the following will happen:
 * "aim maximum" for the target tile is reached, and aiming is stopped
 * "aim threshold" for desired aiming mode is reached, and trigger is pulled

You can use "fire with current accuracy" (or whatever it's called now, by default `f`) - this skips the "aim to desired threshold" part and goes straight to "pull the trigger" action. Then there is also the manual aiming via `.`, but it should cap at the "maximum".

> I'm very confused that it's a feature and not a bug

IMO, this is a bug that came out of a feature being implemented for an already overcomplicated system. It should either not allow "aim and fire" if aim maximum is lower than the aim mode's threshold, or simply fire as soon as the aim maximum was reached.

**Comment by Raikiri** [comment] 2020-12-09 17:03
Ah, now I understand what the problem actually was. I actually had a default firing mode set to something that's not "immediate". This way all 3 buttons: `f`, `a`, `c` and `p` correspond to some amount of aiming and there's simply no button that just fires immediately. In other words, if the default fire mode is set to anything but "immediate", you can't fire at what you don't see directly. Most of the time. Sometimes it just does (apparently after reaching a certain aim threshold).

**Comment by meelock** [comment] 2020-12-10 04:12
I gotta confirm this, 
![cataclysm-tiles_FTWRsOQJA2](https://user-images.githubusercontent.com/6434568/101720582-da5e1a80-3a5a-11eb-80c4-4e8fb5b64f09.jpg)
![cataclysm-tiles_oCT3FeJq9D](https://user-images.githubusercontent.com/6434568/101720585-db8f4780-3a5a-11eb-8848-2a2fbd539622.jpg)
![cataclysm-tiles_3pFmyLxzLv](https://user-images.githubusercontent.com/6434568/101720576-d7632a00-3a5a-11eb-8bd2-432945967e07.jpg)

**Comment by satheon49** [comment] 2020-12-10 08:25
That is a different problem, see  #45910

**Comment by olanti-p** [comment] 2020-12-12 16:02
I've rooted around in the code, and it seems the thresholds have been already fixed. I've found a few other problems with aim-and-fire though, including why it doesn't target tiles (it was counted as an edge case for "creature died during aim-and-fire, abort aiming"), or why it treats tiles with creatures sensed via electroreceptors as empty tiles (the check was missing).
Anyway, this bug _should_ be fixed by `#46008`

**Closed** 2020-12-18 05:35 UTC
Labels: (S1 - Need confirmation), <Bug>, Mechanics: Aiming
