### ISSUE TITLE
Segmention Fault | When opening pressing "Alt Gr" + 2 (should trigger @ )

### ISSUE THREAD

**Issue by Jerakin** [CleverRaven/Cataclysm-DDA#32832] opened 2019-08-01 23:32 UTC
# Describe the bug
Simply pressing the mentioned hotkey gives a CTD.

# Steps To Reproduce

1. Create world
2. Create character
3. Load
4. Press hotkey

# Versions and configuration
(Couldn't find the generate game info command)

 - OS: Windows 10
 - Game Version: cataclysmdda-0.D-8574-Win64-Tiles
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Simplified Nutrition

# Additional context
## Crash Log
```
CRASH LOG FILE: config/crash.log
VERSION: 0.D
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D5705[cataclysm-tiles.exe+0x1D5705]
    @0x5D62B2[cataclysm-tiles.exe+0x1D62B2]
    SMPEG_error+0x4B034@0xE8DD90[cataclysm-tiles.exe+0xA8DD90]
    _C_specific_handler+0x98@0x7FF94FDB7C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FF950C1F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FF950B8D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FF950C1E70E[ntdll.dll+0x9E70E]
    IMG_LoadWEBP_RW+0x3F2C15@0x13930A5[cataclysm-tiles.exe+0xF930A5]
    @0xCC277A[cataclysm-tiles.exe+0x8C277A]
    @0xCC6728[cataclysm-tiles.exe+0x8C6728]
    @0xC0243E[cataclysm-tiles.exe+0x80243E]
    @0x71DEFD[cataclysm-tiles.exe+0x31DEFD]
    @0x7015B6[cataclysm-tiles.exe+0x3015B6]
    IMG_LoadWEBP_RW+0x4EA079@0x148A509[cataclysm-tiles.exe+0x108A509]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF950914034[KERNEL32.DLL+0x14034]
    RtlUserThreadStart+0x21@0x7FF950BF3691[ntdll.dll+0x73691]


```
### Save Data
[Fosters.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3459035/Fosters.zip)

**Comment by eskoONE** [comment] 2019-08-02 05:45
i have a similar problem which seems to be only happening on the 64bit version of the game. does the game work for you with the 32bit version? have you played around with visual studio 2017/19 and uninstalled it?

i have a different message on the error but ntdll.dll msvcrt.dll seem to be the cause for my error too.

**Comment by ZhilkinSerg** [comment] 2019-08-02 07:01
Probably duplicate of #32767.

**Closed by ZhilkinSerg** 2019-08-02 07:01 UTC

**Comment by Jerakin** [comment] 2019-08-02 07:50
I tried this on my mac at work and it crashed there too.
![Screen Shot 2019-08-02 at 09 48 49](https://user-images.githubusercontent.com/5273682/62353358-c4f1eb80-b50a-11e9-8a88-649b29cf5707.png)

Here's the crash.
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /Users/mattias.hedberg/Library/Application Support/Cataclysm/config/crash.log
VERSION: 0.D
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	0   cataclysm-tiles                     0x000000010408f1f6 _Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 38
	1   cataclysm-tiles                     0x0000000104030e38 _Z9log_crashPKcS0_ + 2040
	2   cataclysm-tiles                     0x000000010403049a _Z14signal_handleri + 154
	3   libsystem_platform.dylib            0x00007fff702b6f5a _sigtramp + 26
	4   ???                                 0x0000001b6f635f5f 0x0 + 117832900447
	5   libc++.1.dylib                      0x00007fff6e09ff9b _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_ + 51
	6   cataclysm-tiles                     0x0000000104077e8f _ZN15cata_cursesport9cursecellaSERKS0_ + 47
	7   cataclysm-tiles                     0x0000000105c49c6a _ZN4Font11draw_windowERKN10catacurses6windowEii + 3274
	8   cataclysm-tiles                     0x0000000105c48f88 _ZN4Font11draw_windowERKN10catacurses6windowE + 88
	9   cataclysm-tiles                     0x0000000105c48e8d _ZN15cata_cursesport17curses_drawwindowERKN10catacurses6windowE + 6749
	10  cataclysm-tiles                     0x000000010407163b _ZN10catacurses8wrefreshERKNS_6windowE + 59
	11  cataclysm-tiles                     0x000000010592f711 _ZN6player9disp_infoEv + 27633
	12  cataclysm-tiles                     0x0000000104540440 _ZN4game13handle_actionEv + 23328
	13  cataclysm-tiles                     0x000000010435fdd9 _ZN4game7do_turnEv + 2297
	14  cataclysm-tiles                     0x0000000104b51e74 main + 11620
	15  cataclysm-tiles                     0x0000000103835244 start + 52

	Attempting to repeat stack trace using debug symbols...
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
 name from line
	backtrace: Could not extract binary name from line
	backtrace: Could not extract binary name from line
```

> does the game work for you with the 32bit version?
Thanks will try that tonight

> have you played around with visual studio 2017/19 and uninstalled it?
For the windows I am not sure, but it is highly likely. I do have Visual Studio Community 2017 install on the mac.
