### ISSUE TITLE
Lab crash.

### ISSUE THREAD

**Issue by BlackthornTemple** [CleverRaven/Cataclysm-DDA#55172] opened 2022-02-06 22:56 UTC
### Describe the bug

game crashes and asks me to report.

### Steps to reproduce

start a senario as a lab escape

### Expected behavior

for it to load into the senario. 

### Screenshots

![image](https://user-images.githubusercontent.com/99149003/152704851-be3ff075-c38f-4159-aac6-a5312e0371de.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No name () [],
    No name () [],
    Secronom - UndeadPeople Tileset [secronom_UDP],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Blaze Industries [blazeindustries],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm [magiclysm],
    More Survivor Stuff [more_survivor_stuff],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    Generic Guns [generic_guns],
    Generic Guns - UndeadPeople Tileset [Generic_GunsUDP]
]

### Additional context

was unable to get specific versions and configurations so had to load a save thast worked. only differenbce was it was a new character and the lab escape senario.

**Comment by LeahLuong** [comment] 2022-02-07 01:38
Dupe of #35376. This has been made more user-friendly w/ #55025 for the latest releases.

Update your game or keep trying to make the scenario start until it works.

**Comment by Night-Pryanik** [comment] 2022-02-26 14:06
Closing as duplicate.

**Closed by Night-Pryanik** 2022-02-26 14:06 UTC
Labels: Map / Mapgen
