### ISSUE TITLE
Being near a pool prevents water-based recipes

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#18969] opened 2016-10-25 08:47 UTC
I am in a mansion, have a brazier next to the pool, and can't produce clean water (or any other recipe that needs water). I even have water in bottles in my inventory.

If I set up my brazier in another room, with the bottles of water, I can craft water

(and, yes, I made sure I have the pot with me in both cases)

**Comment by illi-kun** [comment] 2016-10-25 08:58
Duplicate of #18241.

**Closed** 2016-10-25 08:59 UTC
