### ISSUE TITLE
No broken limb status effect

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17552] opened 2016-07-05 21:18 UTC
Currently when a limb break there is no status effect showing up on the character page (default `@`) when a limb is broken. Nor is there any message when you get hit that your arm/leg is now broken.

Also, a monster can hit your broken hit location for seemingly no effect. (I'm assuming it still causes pain).

All of which are a bit strange, and makes the broken limb system feel unintuitive.

So, I suggest we add:
*  A status effect for each broken limb (and perhaps a combined one for both legs being broken) describing what is wrong, and what the effects are.
* A message shown when a limb reaches zero hp.
* Something that happens when a zero hp limb gets damaged again. (might already be in there, or just pain might be enough).

**Comment by illi-kun** [comment] 2016-07-09 07:09
Closing as a duplicate of #16764.

**Closed by illi-kun** 2016-07-09 07:09 UTC
Labels: Information / Interface
