### ISSUE TITLE
Tourist Guides give "Too dark" error in broad daylight

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28377] opened 2019-02-25 09:47 UTC
**Describe the bug**  
Attempting to read a Tourist Guide during the day (out in the open) or with a flashlight, will result in a too dark to read message

**To Reproduce**  
1. Find a Light source
2. Attempt to read the map
3. Fail to read it

**Expected behavior**  
I would expect it to mark places on my map. 

**Screenshots**  
![image](https://user-images.githubusercontent.com/38237593/53328613-36b07400-389f-11e9-87eb-e47ae350bd7c.png)
![image](https://user-images.githubusercontent.com/38237593/53328660-50ea5200-389f-11e9-8ea1-704178a8f162.png)

**Comment by ifreund** [comment] 2019-02-25 09:59
Duplicate of #28339.

**Closed by ifreund** 2019-02-25 09:59 UTC
