### ISSUE TITLE
RM13 combat armor dupe

### ISSUE THREAD

**Issue by POEMisaMisa** [CleverRaven/Cataclysm-DDA#22446] opened 2017-11-18 15:38 UTC
Game version: 0.C-24993-gb09c5bd, build #6935 (17.11.2017 8:48:47)
Operating system: W7
Tiles or curses: tiles
Mods active: https://i.imgur.com/WGkNNUW.png
### Expected behavior
Not a dupe while sorting armor
### Actual behavior
Dupe while sorting armor
### Steps to reproduce the behavior
1. Equip RM13 combat armor, backpack, any type of leg/arm guards 
Screenshot: https://i.imgur.com/GMTPCAL.png
2. Open sort armor panel, select Torso
Screenshot: https://i.imgur.com/xrfNw1v.png
3. Select RM13 combat armor and press Down few times. Arm, leg guards will disappear and another RM13 combat armor will appear. It's possible to unequip it, unload plutonium cells, etc.
Screenshot: https://i.imgur.com/4wNRUP5.png

No sure if activating or deacivating it will affect anything.

**Comment by Night-Pryanik** [comment] 2017-11-18 19:11
Duplicate of  #22327 (closed btw)?

**Comment by jeremyshannon** [comment] 2017-11-18 21:26
Yeah, this was apparently fixed last night. I just tested it in current experimental (#6939, 0.c-25055-gb94c476f73) and it doesn't seem to do that anymore. The armor just rotates through the layers without anything being duplicated.

**Closed** 2017-11-18 21:27 UTC
Labels: Bug, Confirmation Needed, Exploit

**Comment by POEMisaMisa** [comment] 2017-11-19 07:38
Tested in #6940, it's fixed, thank you.
