### ISSUE TITLE
Magiclysm spells crash game

### ISSUE THREAD

**Issue by Anko072** [CleverRaven/Cataclysm-DDA#66577] opened 2023-07-01 10:30 UTC
### Describe the bug

Synaptic Stimulaton, Visceral Projection, Grotesque enchancement crash game on use.

Also Jury Rig activates uncanny dodge from biotek attunement and it seems like impossible to heal myself unless I have no stamina to make dodge impossible.

### Attach save file

[Lavon-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11925516/Lavon-trimmed.tar.gz)

### Steps to reproduce

Use Synaptic Stimulaton/Visceral Projection/Grotesque enchancement,
game crashes.

use jury rig,
instinctively dodge,
get message "wounds are closing up!",
get exp from using spell,
don't get any health healed.

### Expected behavior

I expected spells to do what their description says.
Get healing spell from biotek attunement and evade it with trait from the same attunement is illogical.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17763.4499 (1809)
- Game Version: c94dc03 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11925575/crash.log)

**Comment by Anko072** [comment] 2023-07-02 08:49
Could not reproduce it in a new world. I guess it is something I got from playing for a long time or updating the game. Maybe someone can tell what is wrong and if it is possible to fix.

**Comment by Anko072** [comment] 2023-07-02 09:45
After playing more I get crashes from haste too and when killing boomer with melee.

**Comment by Maleclypse** [comment] 2023-07-04 01:10
If you turn achievements off does all this keep happening?

**Comment by Anko072** [comment] 2023-07-05 08:03
> If you turn achievements off does all this keep happening?

Turned off achievements, stuff which put effects on character still crash the game(tested boomer, visc.projection, haste)
If npc kills boomer in melee its ok.
Posessed npc and I can now kill boomer safely, cast buffs on myself too. Visceral projection from possesed NPC that hits my original character still crashes the game. Original character under control of AI killed boomer in melee and it cause crash too.

So it is something about this exact being broken

**Comment by Anko072** [comment] 2023-07-06 03:51
Found out I can use all of listed while I control vehicle.
Also updated to latest(47f8c63)

**Comment by Maleclypse** [comment] 2023-07-06 04:35
You should use the debug create bug report save file/archive and upload a copy of it to this issue

**Comment by Anko072** [comment] 2023-07-06 04:52
> You should use the debug create bug report save file/archive and upload a copy of it to this issue

Isn't save file already attached? "[Lavon-trimmed.tar.gz]"

**Comment by RenechCDDA** [comment] 2023-07-06 05:15
Duplicate of #66100

**Closed by RenechCDDA** 2023-07-06 05:15 UTC
Labels: (S1 - Need confirmation)

**Comment by Anko072** [comment] 2023-07-06 05:34
> Duplicate of #66100
> Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.

You sure it is the same? I can cast everything when I stay above vehicle control in my exact car, any other car not working

**Comment by Anko072** [comment] 2023-07-06 05:42
Any other car works when I stay above working control panel, not just my car*
