### ISSUE TITLE
Game crashes when trying to light a fire/log in a stove.

### ISSUE THREAD

**Issue by Madrawn** [CleverRaven/Cataclysm-DDA#26796] opened 2018-11-21 21:36 UTC
**Describe the bug**  
Game crashes when trying to light a fire/log in a stove.
 

**To Reproduce**  
1. Load the only character in the attached world
2. Try to light log directly NE of you with the fire drill in your inventory.
3. It'll say "bla bla 8 minutes with your skill", "you feel your body getting warm"
4. Crash happens before you can act again.

**Expected behavior**  
Don't crash without error msg. Even Debug.log doesn't say anything special as far as i can tell.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-34719-ga00b61e
 - Graphics version Tiles 64-bit
 - Mods loaded a bunch of the default ones:
[
  "dda",
  "no_npc_food",
  "craftgp",
  "safeautodoc",
  "national_guard_camp",
  "more_buildings",
  "more_locations",
  "Urban_Development",
  "blazemod",
  "Tanks",
  "necromancy",
  "more_classes_scenarios",
  "brightnights",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "mutant_npcs",
  "npc_traits",
  "boats",
  "deoxymod",
  "filthy_morale",
  "sleepdeprivation"
]
**Additional context**  
Save file is in attachments as well as the debug.log

[North Providence.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2605829/North.Providence.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2605832/debug.log)

**Comment by ZhilkinSerg** [comment] 2018-11-22 00:15
Duplicate of #26777.

**Closed by ZhilkinSerg** 2018-11-22 00:15 UTC
