### ISSUE TITLE
Better visibility for enemies above you

### ISSUE THREAD

**Issue by Haranador** [CleverRaven/Cataclysm-DDA#50026] opened 2021-07-18 13:28 UTC
# Is your feature request related to a problem? Please describe.
With the addition of the new wasp hives, survivors deal increasingly often with enemies attacking from above. Currently, the game has no clear way of indicating to you if something above you is moving in to attack you. 
Even worse if you holding down the movement key since they will get a few hits in before you even notice.

# Describe the solution you'd like
Something similar to the sound indicator or some sort of "shadow" to let you know "hey there is something x z-levels above"
Anything really that lets you see the location of possible hostiles in a single view, without having to use X/V every couple of steps. 

# Describe alternatives you've considered
Extending the functionality of the compass UI element to include yellow/red exclamation marks before enemies' names or directions to indicate tracking/attacking.

# Additional context
none

**Comment by ZhilkinSerg** [comment] 2021-07-18 14:31
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/48322

**Comment by Night-Pryanik** [comment] 2022-02-06 18:32
Closing as duplicate.

**Closed by Night-Pryanik** 2022-02-06 18:32 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>, Info / User Interface, Z-levels
