### ISSUE TITLE
Better tradeing menu.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#48024] opened 2021-03-14 06:15 UTC
You know, so far, many things has been changed after version and version, but there's one things are still the same, the tradeing menu, I have to say, the tradeing became more and more important one the game, 

but there's one thing that make player uncomfortable, is the tradeing menu are still can't getting select items by simply press direction keys or something like that, you have to press each hotkey that belongs to the items in order to select which one to trade,

I'm not complain about the game design, but I think mabye, just mabye we need to make tradeing much easier, so we can just simply pick the item without press almost the whole keyboard in order to buy or sell anything.

**Comment by akirashirosawa** [comment] 2021-03-14 06:25
I also agree that the trade menu needs to be unified. Make it possible to select with arrows, add ability to SEARCH. Like everywhere else on other menus.

**Comment by ZhilkinSerg** [comment] 2021-03-14 10:45
Duplicate of #42363

**Closed by ZhilkinSerg** 2021-03-14 10:45 UTC
Labels: <Suggestion / Discussion>, Info / User Interface, NPC / Factions
