### ISSUE TITLE
Unable to Repair an Engine with Immobiliser to Usable

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54846] opened 2022-01-27 20:02 UTC
### Describe the bug

Came across this the other day after spending literally hours searching for a specific type of vehicle, ended up gaining a few points in mechanics and fab while trying to trick it out, and then when I started it up, I got a "BEEP!" no matter how many times I tried, and after searching online I found some code which seemed to indicate that this is a factor of a "immobilizer", which seems to be able to crop up on any engine, even if it's green || status and (faulty)?

After spending a couple in-game days in a parking lot trying to make the darned thing work, I eventually crafted up a frame and a pallet jack and forklift and was able to remove the engine, and then go off and drag back another engine and replace it, which worked.

What is the story with these immobilizer things? There is almost no warning that they're installed on a vehicle's engine unless you understand the specific type of response one gets in-game from trying to start up a vehicle, and there does not seem any way to "repair" them away.

FWIW I did search for this issue and see cases of it at least as far back as 6 years ago, but it's still in the game and still there doesn't seem to be any way to remove or otherwise resolve them, and I legit had no clue what was occurring until I did a bunch of googling and decided to just completely swap the damned engine out of the vehicle. Character learned a ton of skills, I learned what "BEEP" means, neither were super happy with the outcome of spending a week in-game trying to get a van to move after I'd moved all my mods into it and then realized I couldn't put them back into my old car without even higher mechanics skill and a metric truckload of welding rig charges and bars - which I'd just used up!

From https://gitcode.net/mirrors/CleverRaven/Cataclysm-DDA/-/blob/cdda-experimental-2021-09-03-2334/doc/JSON_FLAGS.md 
*Vehicle fault flags:
IMMOBILIZER Prevents engine from starting and makes it beep.*

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle.cpp
*   // Immobilizers need removing before the vehicle can be started
    if( eng.has_fault_flag( "IMMOBILIZER" ) ) {
        sounds::sound( pos, 5, sounds::sound_t::alarm,
                       string_format( _( "the %s making a long beep." ), eng.name() ), true, "vehicle",
                       "fault_immobiliser_beep" );
        return false;
    }*

### Steps to reproduce

1. Find vehicle with immobilizer on engine.
2. Try and fix it without replacing the entire engine.

### Expected behavior

Expected that with enough time, experience and./or skills, I could remove a vehicle immobilizer or "repair" it away from an engine. Expect to be able to repair a (faulty) engine with high enough skill, regardless of the reason why it's faulty (which is usually obscure).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8f56778 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by jworkman01** [comment] 2022-01-27 21:27
I am l looking to contribute to this open source project for my software development methodology class. Is this issue still available?

**Comment by coyo7e** [comment] 2022-01-27 21:40
> I am l looking to contribute to this open source project for my software development methodology class. Is this issue still available?

As far as I understand the way open source projects work, this is totally open for someone to muss with and submit!

*(my main concern is that I am not enough of a skilled player to find some "obvious" fix to this faulty engine thing which someone else has logged years ago and been forgotten about, I kind of feel like I might be missing some already-existed way to fix this item's issue, especially since it has seemed to last for over 6 years already)*

**Comment by Boonlike** [comment] 2022-01-27 22:13
Unless something has changed, you can remove an immobilizer by examining the car, and pressing "m" to mend the faulty engine. It takes some tools and skill in electronics and mechanics. I'll play around a bit in the newest experimental and see if I can't find a vehicle with an immobilizer on it.

**Comment by jworkman01** [comment] 2022-01-28 00:13
I will look into another issue. Thanks for the advice @coyo7e !

**Comment by coyo7e** [comment] 2022-01-28 00:25
> Unless something has changed, you can remove an immobilizer by examining the car, and pressing "m" to mend the faulty engine. It takes some tools and skill in electronics and mechanics. I'll play around a bit in the newest experimental and see if I can't find a vehicle with an immobilizer on it.

The "mend" actually has a use?! Crazy, I've been playing for over ten years, regularly tried using "mend" on scores of items, and now I find out it's the only way to fix an engine that can otherwise be fixed vie "r"epairing it..?

**Comment by Boonlike** [comment] 2022-01-28 00:39
Yep. It's main use is for fixing faulty engines. Mend is also used to reset deployed CBMs. I haven't discovered any uses for it besides that.

**Comment by coyo7e** [comment] 2022-01-28 00:41
Perhaps its a "feature" which should simply be bundled into the repair feature, rather than assuming players will try a command that doesn't work on anything else

**Comment by LeahLuong** [comment] 2022-01-28 01:02
Mending is also used to clean guns. There are plans underway to make mending a bigger thing in the future. See #53500.

**Comment by coyo7e** [comment] 2022-01-28 02:11
Ahh that's the one outlier case I was trying to remember. Generally though I jus throw away guns that get fouled because they're more common than ammo.

**Comment by PatrikLundell** [comment] 2022-01-28 08:59
You'll also need to use mend on engines to repair other specific faults, which typically require a spare part.

Another thing to take away from the experience is to verify that you can actually start the engine before investing in modifying the vehicle. Sometimes you're told you can't find the key and have to hot wire the vehicle, and you may not have the skill to do that, or may not be willing to risk it failing (setting off an alarm that presumably would attract attention from the undead).

**Comment by LeahLuong** [comment] 2022-01-28 18:54
This issue should be closed as it's not a bug & OP has resolved the problem they posted about.

**Closed** 2022-02-01 19:45 UTC
