### ISSUE TITLE
You can walk on water by (G)rabbing a vehicle and pushing it in front of you.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#50123] opened 2021-07-21 21:48 UTC
### Describe the bug

When you push a (G)rabbed vehicle onto water (including deep water) in front of you, you can walk on water as if it was dry land.

Works even with a single steel frame being "the vehicle".

### Steps To Reproduce

1. Go to a river (or lake, etc)
2. Place a vehicle in front of you
3. (G)rab it
4. Make sure you are pushing it __in front__ of you, and not dragging it behind
5. Push it onto water
6. Walk on water 

### Expected behavior

As soon as you step on a deep water tile, you start swimming (or sinking).

### Screenshots

![John _walking on water](https://user-images.githubusercontent.com/61312205/126564107-818adc1c-c119-4416-a6eb-201ee7857195.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d0fb1f3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Rural-Only Mapgen [ruralbiome],
    Bionic Slots [cbm_slots]
]

### Additional context

This behavior can _maybe_ be seen as somewhat intended if the vehicle in question could float.
But as of right now even a steel frame would work.

**Comment by Night-Pryanik** [comment] 2021-07-22 04:01
Duplicate of #19226.

**Closed by Night-Pryanik** 2021-07-22 04:01 UTC
Labels: (S1 - Need confirmation), <Exploit>, Fields / Furniture / Terrain / Traps, Vehicles
