### ISSUE TITLE
Fire goes out independent of fuel on time compression. For example: crafting, reading, waiting. [OS:Android]

### ISSUE THREAD

**Issue by cargo94** [CleverRaven/Cataclysm-DDA#33935] opened 2019-09-10 08:35 UTC
# Describe the bug

On time compression from reading, crafting, or waiting fires in ovens and braziers go out, leaving the unburnt fuel in the fireplace itself. 

# Steps To Reproduce

1. put planks in an oven
2. set them on fire.
3. Attempt to  [b]atch craft something that takes longer than five minutes.
4. Fire goes out, despite the fireplace still having fuel.

# Expected behavior

The fire keeps going until it consumes all fuel in the fireplace. Also, at that point, the character grabs another plank from the adjacent firewood source and refuels the fire.

# Versions and configuration

- OS: Android
- OS Version: Manufacturer: Xiaomi; Model: Redmi Note 7; Release: 9; Incremental: V10.3.6.0.PFGEUXM; (it's a version of Android 9)
- Game Version: Build 9610 (0.D-7431-g0d20828 [32-bit])
- Graphics Version: Tiles
- Mods loaded: [
Dark Days Ahead [dda],
 C.R.I.T Expansion Mod [crt_expansion],
 Aftershock [aftershock],
 Craftable Gun Pack [craftgp],
 DeadLeaves' Fictional Guns [FIC_Weapons],
 Garden Pots [growable-pots], Icecoon's Arsenal [ew_pack],
 Makeshift Items Mod [makeshift], Medieval and Historic Classes and Shields [Medieval_Stuff], More Survival Tools [More_Survival_Tools],
 Mythological Replicas [nw_pack], DinoMod [DinoMod],
 Modular Turrets [modular_turrets],
 Salvaged Robots [Salvaged_Robots],
 Hydroponics [hydroponics], Mutant NPCs [mutant_npcs], Mythical Martial Arts [MMA],
 Beta National Guard Camp [national_guard_camp], More Locations [more_locations], Fuji's More Buildings [FujiStruct],
 Mapgen Demo [mapgen_demo], Urban Development [Urban_Development], Folding Parts pack [deoxymod], Vehicle Additions Pack [blazemod],
 Tanks and Other Vehicles [Tanks],
 Necromancy [necromancy],
 Classes and Scenarios Mod [more_classes_scenarios],
 Classic Roguelike Classes [RL_Classes], Stats Through Skills [StatsThroughSkills]]

# Additional context

Also happens with versions 9591, 9607, and a version from the 16th of august the number of which i've lost.

**Comment by ZhilkinSerg** [comment] 2019-09-10 09:37
Duplicate of #33130

**Closed** 2019-09-10 09:38 UTC
Labels: (S3 - Duplicate), <Bug>, Fields / Furniture / Terrain / Traps
