### ISSUE TITLE
cutting log into planks consumes time in a strange way

### ISSUE THREAD

**Issue by 8ctopus** [CleverRaven/Cataclysm-DDA#32665] opened 2019-07-27 13:39 UTC
# Describe the bug

Cutting a log into planks takes 0 seconds then the game time moves forward second by second for 18 minutes.

# Steps To Reproduce

1. Take a log and cut it into planks with wood axe or chainsaw.
2. Game log immediately says "You produce 10 planks."
3. Then game loops second by second for 18 minutes without possibility to do anything in the game. It takes about a minute or 2 of real time to get back to a game accepting user input.

Bug was probably introduced in this pull [https://github.com/CleverRaven/Cataclysm-DDA/pull/32558](https://github.com/CleverRaven/Cataclysm-DDA/pull/32558)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-5912-g6bf0f29 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Zireael07** [comment] 2019-07-27 13:54
Duplicate of #32587, which even has the word planks in title.

**Closed by Zireael07** 2019-07-27 13:54 UTC

**Comment by 8ctopus** [comment] 2019-07-27 16:45
yeah you're right.
