### ISSUE TITLE
Zone Sorting Loop

### ISSUE THREAD

**Issue by NayrbEroom** [CleverRaven/Cataclysm-DDA#31895] opened 2019-06-27 00:12 UTC
# Describe the bug

While attempting to sort items into assigned zones the player goes into infinite loop.  

# Steps To Reproduce

Difficult to continuously reproduce. I have attached my save file and a (albeit slightly useless) gif of the error.  If you go from where the character is in my save file and immediately hit Shift+O itll happen consistently

Edit: It seems to be closely related to the gun sorting in this situation, but i have had it before where it was different items. For reference their are bows/slingshots etc in this save-file. They are currently placed at the door but the sort location is at the bottom left on the tables.  

# Expected behavior

Sorting should not get stuck in an infinite loop.

# Screenshots
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9480761/60222901-b007a580-9844-11e9-9eaa-92578949c6fb.gif)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5005-gc88b7db [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Arcana and Magic Items [Arcana],
    Draco's Dog Mod [DracoDogMod]
]

[Weedsport.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3332351/Weedsport.zip)

**Comment by mrkybe** [comment] 2019-06-27 03:36
Do your zones overlap in some way?

**Comment by davidpwbrown** [comment] 2019-06-27 10:21
Could be related to #31839 
sorting loot, calls ACT_MOVE_ITEMS, and if an item goes missing constnatly then it might cause a loop.
this was fixed in #31873 which was merged a few hours ago.
Could be that this fixes it, with latest master.

**Comment by ProfoundDarkness** [comment] 2019-06-27 14:41
Just tried the included save with build 9229 and it seems to get into an infinite loop still...  At least until a zombie appears though it doesn't always meaning I have to end task.

I find it interesting that while there are usually log events about items being set down and that's not happening with this save.  For example I'm NOT seeing (and am expecting to see) things like "You drop your (item name) on the floor."  I am seeing other messages such as those due to cold exposure.

Also interestingly when I'm sorting gear I can normally hit numpad 5 to interrupt and that doesn't work on this save.

I also got an error while loading the save on "Items":
Debug: Item id 270 is unknown
Function: virtual void Single_item_creator::check_consistency() const
file: src/item_group.cpp
line:123

I did try to make sure to have all the mods you have on save load so not sure what that consistency error is about.  I seem to recall in my own game when some stuff got shifted from more survival tools to mainline and then deleted getting some item errors but it specified what the item id (string) was (things like makeshift_shovel).

I haven't personally encountered this in my own current game and as it turns out I just got back from a trip AND I re-arranged where things go as well as having overlapped unsorted and sorted piles.  That doesn't mean I won't encounter this just haven't.  I also don't play normally with the same set of mods.

**Comment by NayrbEroom** [comment] 2019-06-27 17:48
> 
> 
> Do your zones overlap in some way?

Yes, every one overlaps with an Unsorted Zone. This has worked before as an easier way to organize an entirely new building. But specific zones dont overlap I.e. guns is separate from ammo, etc.

**Comment by NayrbEroom** [comment] 2019-06-27 17:50
@ProfoundDarkness 
> I haven't personally encountered this in my own current game and as it turns out I just got back from a trip AND I re-arranged where things go as well as having overlapped unsorted and sorted piles. That doesn't mean I won't encounter this just haven't. I also don't play normally with the same set of mods.

I did have another world going where this issue happened consistently. I have since deleted this one due to memory issue from before. I assumed it was related to that.

**Comment by ZhilkinSerg** [comment] 2019-06-28 13:24
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/29573.

**Closed by ZhilkinSerg** 2019-06-28 13:24 UTC
