### ISSUE TITLE
No longer being able to mix liquids of same type/calories in the same container

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#52020] opened 2021-10-01 11:41 UTC
### Describe the bug

I got a small herd of cows. Previously, I could visit them with a 60L liquid tank, obtain 10L of raw milk from each cow until I fill the tank and then process it all together.. like it happens in the real life.

Current version no longer allows that. Something from about a week prior to it broke something and made raw milk from different cows act as if they are different liquids (even if they have exact same calories), my bet is it is the "life" left in the milk between the milking of the two cows. But the problem goes even further. If I take these 20 Liters of milk from 2 different cows to my kitchen and I boil it up, the 50x maximum batch for the milk recipe is only for 12.5L of it. I immediately do the rest 7.5L of the milk, but the newly created liquids are once again not mixable (probably again because of lifetime issues?). This make no sense and will enforce a weird ingame behavior because of coding choices.

### Steps To Reproduce

1. Get two cows and 1 steel jerrycan
2. Milk the first cow, place the milk in the container
3. Milk the secon cow, try to place the milk in a container and observe that the first one is not available. 

### Expected behavior

I expect that liquids of same type will be able to be stored in the same container even if they are not produced in the exact same second as each other (because that is not a scenario that can happen in the game reality of a single player doing tasks). 

If someone decides to mix liquid with less life left with other that is fresh, make the mixture have the lesser lifetime left. It is a better and more realistic solution than what we have now.

### Versions and configuration

a1b1b9d , experimental, curses, Linux

### Additional context

Furthermore, not allowing to mix liquids of same type with different calories is also weird. Make the game recalculate quickly the calories per portion from the total calories of the two mixes and go with that for the new mixture.

**Comment by ZhilkinSerg** [comment] 2021-10-02 08:26
Duplicate of #47148
Duplicate of #51198
Related to #48233
Related to #48120
Related to #48459
Related to #36960
Related to #46470

**Comment by hexagonrecursion** [comment] 2022-01-04 09:46
I could not reproduce this bug

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment] 2022-01-16 15:50
Closing as duplicate of above issues.

**Closed by wapcaplet** 2022-01-16 15:50 UTC
Labels: (S1 - Need confirmation), Items: Food / Vitamins
