### ISSUE TITLE
Survivor tries to eat favorited items

### ISSUE THREAD

**Issue by carlom5** [CleverRaven/Cataclysm-DDA#45526] opened 2020-11-20 08:58 UTC
Using the consume menu defoult keybinding ''E'' resoults in my character automatically trying to eat all the favorited items in his inventory, weapons, ammo, tools etc etc. I don't have any mutation nor bionics. After denying all the ''do you want to eat your favorite axe?'' etc the game crashes to the desktop

# Steps To Reproduce
1) open the consume menu
2) deny all the eating prompts

# Expected behavior
The cosume menu should display all the food and medical items in my inventory and let me pick the ones i want to actually eat

# Screenshots
![immagine](https://user-images.githubusercontent.com/54553388/99779196-ff730380-2b14-11eb-8a86-6bcfb5eba59b.png)
![immagine](https://user-images.githubusercontent.com/54553388/99779246-1154a680-2b15-11eb-85e8-81c385cab6d8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7642-gac49e40 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

# Additional context
upon crashing the game fails to generate any crash log so i think the following reports are non accurate 
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5572385/config.zip)

    
[SAVE.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5572370/SAVE.zip)

**Comment by Fris0uman** [comment] 2020-11-20 08:59
duplicate of #45509

**Comment by Jamuro-g** [comment] 2021-02-28 16:00
seems to be fixed already

**Comment by hexagonrecursion** [comment] 2021-08-29 07:50
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Closed** 2021-09-11 14:05 UTC
Labels: <Bug>, <Crash / Freeze>, Info / User Interface, (S2 - Confirmed), Items: Food / Vitamins
