### ISSUE TITLE
Cant Move On To Boat Sections While Touching Land

### ISSUE THREAD

**Issue by KingCam77** [CleverRaven/Cataclysm-DDA#48612] opened 2021-04-22 01:59 UTC
# Describe the bug

Unable to access parts of a boat that are above deep water while its touching the land.

# Steps To Reproduce

1. Create a boat with aisles.
2. Park the boat with one side touching the land.
3. Try to walk onto an aisle that's in deep water.

# Expected behavior

I should be able to walk on the boat instead of being forced into the water.

# Screenshots

![image](https://user-images.githubusercontent.com/43072336/115644265-23f52680-a2d3-11eb-8bb8-97c2bca00877.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10377-g3860b0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

[North Vacherie - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6354960/North.Vacherie.-.Copy.zip)
Head south from rural house to reach boat if using file for replication.

**Comment by actual-nh** [comment] 2021-04-22 02:05
Related to (or a duplicate of) #48011?

**Comment by Salty-Panda** [comment] 2021-04-22 08:52
Sounds like ##46488

**Closed** 2021-04-22 15:44 UTC
Labels: (S3 - Duplicate), Vehicles, Z-levels
