### ISSUE TITLE
Aiming problem with fusion blaster rifle

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#27321] opened 2018-12-26 16:40 UTC
**Describe the bug**  
Firing in any direction at nothing in particular will set the aiming time to 30 for the east direction always

**To Reproduce**  
1. Fire any direction (at any degree) other than exactly east with precise aim.
2. Game will set aiming time to aim exactly east to 30 and act as if you had fired exactly east.

**Expected behavior**  
Game acts as though you fired in the direction you actually fired, not east every time.

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version 0.C-35549-g07569da
 - Graphics version Tiles
 - Mods loaded None

**Comment by kevingranade** [comment] 2019-01-11 07:34
Can't reproduce.

**Comment by Night-Pryanik** [comment] 2019-01-12 07:43
Guess this was fixed not so long ago. Closing for now, ping me if this is still an issue.

**Comment by CoroNaut** [comment] 2019-03-03 15:24
@Night-Pryanik The version during this test is 0.C-37575-gf07c447
I ran through my steps and found this is still an issue.
This test is done using the _fusion blaster rifle_ (accurized with gunsmith repair kit) with "lightweight replacement furniture" and "Red Dot Sight" attachments, You can probably get same results without attachments. Also my marksmanship is 13 and rifles at 12. (I don't know if any other skills would affect the accuracy here)

Picture Showing aim specifically to the east before firing
![beforefireaimeast](https://user-images.githubusercontent.com/24307650/53697138-38e16980-3d9c-11e9-975e-2e7b1255c2ea.PNG)

Picture Showing aim in random direction (not east) before firing
![beforefireaimanydirection](https://user-images.githubusercontent.com/24307650/53697144-4b5ba300-3d9c-11e9-9a0e-25b6a5818184.PNG)

Picture Showing me get the aim down all the way to 30 (the lowest)
![beforefirefullyaimedanydirection](https://user-images.githubusercontent.com/24307650/53697150-5f9fa000-3d9c-11e9-88ca-3863b00c3362.PNG)

Picture Showing the aiming time for firing exactly east after already firing NW (without steading aim at all)
![afterfireshowingeastaim](https://user-images.githubusercontent.com/24307650/53697153-780fba80-3d9c-11e9-9539-bb2fb98d1447.PNG)

Picture Showing the aiming time for firing NW (without steading aim at all)
![afterfireshowingfiringaim](https://user-images.githubusercontent.com/24307650/53697169-94abf280-3d9c-11e9-9cf9-924b4f30789d.PNG)

Note that If I want to continue firing at the same location (NW) with any more than crappy aim, I have to re-steady the weapon at the same location. If I want to do practice shots, then I would want to do them all to the east so that I don't have to spend in-game time re-aiming to the east.

**Comment by CoroNaut** [comment] 2020-01-10 18:51
This issue still persists as of
- Game Version: 0.D-10922-gb1541cd [32-bit]

**Comment by CoroNaut** [comment] 2020-02-22 08:33
@Night-Pryanik 
This issue still persists as of
- Game Version: 0.D-12476-gfef327b [64-bit]

The pictures provided should give every frame-by-frame step to be reproduced, if there is confusion still, please elaborate.

**Comment by kevingranade** [comment] 2020-03-08 18:26
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/so-how-does-firearm-aiming-work-internally/22959/1

**Closed** 2020-03-14 07:41 UTC
Labels: <Bug>, Mechanics: Aiming
