### ISSUE TITLE
Segfault when sleeping (hallucinations involved)

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#70654] opened 2024-01-04 19:34 UTC
### Describe the bug

When I sleep, the game crashes. Sometimes after a second, sometimes after 10 seconds. The game has crashed numerous times when hallucinations were involved earlier in the day but I managed to get to night time by saving every 30 seconds and reloading after a crash.

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13834674/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Press $ to sleep
3. Submit 'yes' when prompted
4. Wait and observe the crash to desktop

### Expected behavior

Not crash during sleep

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 1ec6b8c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

See also #69849 that suggest hallucinations should not spawn when the player sleeps

**Comment by RenechCDDA** [comment] 2024-01-05 05:33
Duplicate of #70649

**Closed by RenechCDDA** 2024-01-05 05:33 UTC
Labels: (S1 - Need confirmation)
