### ISSUE TITLE
DEBUG: Item mask_bunker was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#41907] opened 2020-07-06 22:38 UTC
# Describe the bug
 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2390

# Steps To Reproduce
Unknown occurred while autosaving.

# Expected behavior
?

# Screenshots
N/R

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 18.04.4 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-3780-g54cde4b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
debug.log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4881526/debug.log)

Save file
[Bull Shoals.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4881518/Bull.Shoals.zip)

**Comment by hexagonrecursion** [comment] 2020-07-07 05:07
Duplicate of #41821

**Closed** 2020-07-07 06:26 UTC
