### ISSUE TITLE
Loose gaseous items will sit on the ground until you bottle them up with an airtight container

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#61605] opened 2022-10-10 23:15 UTC
### Describe the bug

Gas items sit on the ground, I would expect them to disperse or at least not be recapturable after they spill out.

### Steps to reproduce

Load the game
Spawn nitrox
See nitrox unpickable on the ground 
spawn plastic bottle
catpure nitrox in your handy plastic bottle

### Expected behavior

Gas to vanish once it spills out of it's container.

### Screenshots

![pickup gasses into plastic bottles](https://user-images.githubusercontent.com/54345792/194965934-c2a594a1-877d-409f-bb3e-0fbe8baae2ca.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: b1fb6f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RenechCDDA** [comment] 2022-10-21 10:49
/confirmed

So there's three issues here.

1) Lots of things (NOT nitrox) are still counted as liquids, either because of holdovers or because gas handling isn't 100%, or because *people just didn't know you could define items as gasses*. This is tangential and can be resolved with some json drudgery.

2) Nitrox, while a gas, does not have a `NO_DROP` flag which would prevent it from being taken out of containers. Scuba tanks (their only container) *do* have `NO_UNLOAD` so it shouldn't ever be outside of a container regardless - the ability to be outside of the container is only brought about by debug spawning. Still it should get `NO_DROP` to force it to remain in a container.

3) Gasses do not have the same handling as liquids for picking up spilt items, and need a check not to be able to be picked up as well as a default NO_DROP (imo).

**Closed** 2022-10-25 07:23 UTC
Labels: (S2 - Confirmed), Items / Item Actions / Item Qualities
