### ISSUE TITLE
Comfort item message spam trying to and during sleep

### ISSUE THREAD

**Issue by Illgowiththisname** [CleverRaven/Cataclysm-DDA#37495] opened 2020-01-29 07:37 UTC
# Describe the bug

You get messaged every 5 minutes that you are using a comfort item for sleep such as a pillow

# Steps To Reproduce

1. Find some kind of comfort item for sleeping like the pillow.
2. place pillow or other comfort item where you want to sleep.
3. try to go to sleep (you don't have to as the message will also spam while trying).
4. shift + p to check message log after sleep or long enough time trying.

# Expected behavior

The message should only come up once when you start trying to go to sleep like the way using items for warmth when trying to go to sleep does.

# Screenshots

![sleep comfort message spam](https://user-images.githubusercontent.com/60259456/73335963-7d8bc280-42d5-11ea-83ec-4f3db63b927b.png)

# Versions and configuration

 - OS: Windows
    - OS Version: Windows 7 Ultimate
- Game Version: 0.D-11709-g9d46c12 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]

# Additional context
think that's it and here's the save before he went to sleep so you don't have to wait it out yourself.
[testing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4126696/testing.zip)

**Comment by jkraybill** [comment] 2020-01-29 08:20
I *think* this will be fixed when #37404 is merged?

**Comment by Illgowiththisname** [comment] 2020-01-29 08:45
with the problem already being looked should i close this or keep it as it is?

**Comment by jkraybill** [comment] 2020-01-29 09:14
Based on the description of that PR, it looks like it fully fixes this issue. Not sure what the norm is here but my default approach would be to close this issue when the PR is merged (and tested if so desired).

**Comment by Fris0uman** [comment] 2020-01-29 09:39
This is a duplicate of #37121

**Comment by davidpwbrown** [comment] 2020-01-29 19:07
closing in favour of 37121

**Closed by davidpwbrown** 2020-01-29 19:07 UTC
