### ISSUE TITLE
Cannot attach gun modifications anymore

### ISSUE THREAD

**Issue by Chevarie** [CleverRaven/Cataclysm-DDA#38702] opened 2020-03-11 07:51 UTC
# Describe the bug

Gun modifications such as Shoulder Strap, Suppressor, laser Dot and Holosights (only 4 tested, but assumed to be all mods), cannot be attached to any applicable weapon both in and out of inventory. Even weapons with previous mods on them can't have their mods reinstalled once removed. Instead, a window states that there is no available choices when prompted to choose on which weapon to attach the mod, despite appropriate skills, tools and weapons being available. See screenshots for further details. 

# Steps To Reproduce

1. Make a player with a gun that has mods already present on it and high weapon skill level.
2. Remove the modification ( "a" on the weapon and select for instance the "shoulder strap")
3. Try reinstalling the modification ( "a" on the modification and see if you can select the weapon it was previously on)

# Expected behavior

Any weapon in the inventory or in the vicinity should be selectable to attach a mod on, especially if it was just removed from it. 

# Screenshots

![1](https://user-images.githubusercontent.com/62050219/76393318-51864700-6341-11ea-95d4-3870684bd36a.png)
![2](https://user-images.githubusercontent.com/62050219/76393338-5814be80-6341-11ea-8885-ae6c3dbaddf3.png)
![3](https://user-images.githubusercontent.com/62050219/76393341-5a771880-6341-11ea-9c2a-0b31ce4118a3.png)

# Versions and configuration

 - OS:  Windows 10 
 - Game Version: 0.D- 13003-gd59d380
 - Graphics version: Tiles
 - Ingame language:  English
 - Mods loaded:
 --> Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Crazy Cataclysm [crazy_cataclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Fuji's Military Profession Pack [fuji_mpp],
    Draco's Pig Mod [DracoPigMod],
    Draco's Dog Mod [DracoDogMod],
    Dorf Life [Dorf_Life],
    More Locations [more_locations],
    Mutant NPCs [mutant_npcs],
    Classes and Scenarios Mod [more_classes_scenarios],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc]

# Additional context
Could provide savefile if need be

**Comment by jkraybill** [comment] 2020-03-11 09:54
Ugh, no savefile necessary, confirmed and very easy to reproduce on master :(

**Comment by jkraybill** [comment] 2020-03-11 10:13
Can you please double-check this? At first I thought it was reproducible, but:

- your MP7A2 is loaded. That will make mods not installable in general. There is an annoyance/bug where if you have one installable gun and one uninstallable, you get feedback:
![image](https://user-images.githubusercontent.com/1361701/76405617-82678a00-63dc-11ea-82e1-2d7302592a21.png)

but if you only hold the uninstallable weapon, you don't get feedback:
![image](https://user-images.githubusercontent.com/1361701/76405666-957a5a00-63dc-11ea-9716-60548ffd6730.png)

There's definitely an argument for that being a bug worth fixing!

- holosight needs marksmanship 3 and weapon 2. The MP7A2 is an SMG, and you only have 1 in SMG. Below I have marksmanship 3, rifles 2, and SMG 1:
![image](https://user-images.githubusercontent.com/1361701/76405770-c064ae00-63dc-11ea-97f6-ce834aea5048.png)

Again, when only holding the MP7A2, I don't get feedback, just the empty list.

So I think in your case, the sights may be lacking skills and the strap/suppressor may be due to the weapon being loaded.

If this is the case (try unloading the weapon, and debugging your SMG skill to a higher number), I would suggest closing this issue.

I'll open a new issue about gunmod feedback.

**Closed** 2020-03-14 07:48 UTC
