### ISSUE TITLE
Crash due to 'Arithmetical Error' drinking Moonshine from Hip Flask

### ISSUE THREAD

**Issue by Plaidstone** [CleverRaven/Cataclysm-DDA#41967] opened 2020-07-09 05:22 UTC
# Describe the bug
As stated in title. Took my last two drinks of Moonshine from an equipped hip flask, saw there was still an (unquantified) entry for Moonshine in the consume list and assumed I must've had more than I thought. I was wrong, and on attempting to consume it the game immediately crashed.

# Steps To Reproduce
Unsure if it's reproducible.

# Expected behavior

# Screenshots

# Versions and configuration
Windows 10
0.E-3894-g4929649
Tiles
English
Aftershock, Blaze Industries, Magiclysm, No Fungal Monsters, Disable NPC Needs, Nonperishable Overhaul, SpeedyDex, Stats Through Skills

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4894679/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4894680/debug.log)
Don't know how to save things as a .zip, making a copy of the save as is though. Worth noting that the last save was at least a few hours in game-time prior to the crash. Maybe days. Can figure out how to convert and provide it if needed.

**Comment by hexagonrecursion** [comment] 2020-07-09 12:41
Duplicate of #40968

**Closed** 2020-07-09 14:27 UTC
