### ISSUE TITLE
Survivor map and note are craftable

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17843] opened 2016-07-29 22:55 UTC
EDIT: They don't show up in the crafting menu by default, but searching for "survivor" will find them.

**Comment by mugling** [comment] 2016-07-30 09:28
Uncrafting bug?

**Comment by pisskop** [comment] 2016-07-30 19:05
Now hang up, a custom made note isnt a bad idea.

And being able to leave survivor notes around the city also sounds like it has some modest value

**Comment by mugling** [comment] 2016-07-30 19:08
Quite obviously a bug and not one we want to convert into a misfeature

**Comment by mugling** [comment] 2016-08-11 12:09
Duplicate of #17876

**Closed by mugling** 2016-08-11 12:09 UTC
Labels: Bug, Duplicate, JSON
