### ISSUE TITLE
designating a firewood source should not require light

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#32979] opened 2019-08-06 21:47 UTC
currently, "constructing" a firewood source can't be done in the dark, which seems weird. suggest removing the requirement for lighting.

**Comment by ZhilkinSerg** [comment] 2019-08-07 05:21
I would say this should be moved to zone management instead.

**Comment by joe9000** [comment] 2019-08-07 13:18
i agree as a long term solution that adding a Loot: Usable Wood zone type and potentially a Loot: Usable Batteries and a Loot: Usable Liquid Fuels would be a great idea, replacing firewood source under construction.

not sure how much dev time would be needed for that solution, so i think removing the darkness requirement would be an adequate near term fix.

**Comment by wapcaplet** [comment] 2021-02-12 02:33
Cannot reproduce in 0.E-9572-g483cd09a89 - it is possible to construct a firewood source in complete darkness. Appears to have been fixed by #33372

**Closed by wapcaplet** 2021-02-12 02:33 UTC
Labels: (S2 - Confirmed), <Bug>, Crafting / Construction / Recipes
