### ISSUE TITLE
Failure to detect appropriate fire source when continuing craft

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#32050] opened 2019-07-02 01:34 UTC
Pausing a craft that requires fire, or being stopped by the fire going out, and then attempting to continue the craft causes a choice menu to open which lists all potential fire sources as available nearby, despite none actually being available, and with the exception of actual "Nearby Fire".

# Steps To Reproduce

1. Begin crafting "Clean water" next to fire.
2. Pause craft or cause fire to go out.
2b. Light fire again.
3. Activate clean water in progress item.

# Expected behavior

A menu listing the actual available fire sources, including "Nearby fire", akin to the menu shown when a craft fails and progress is lost.

# Screenshots

<img width="1128" alt="Capture" src="https://user-images.githubusercontent.com/7095289/60475920-71039680-9c2e-11e9-93b0-ae3d0886eabc.PNG">

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5165-g5122325 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

I found the bug after updating from 9249 to 9255, so it MAY be related to the fix added in 9250. This is just speculation, however, as this particular situation had never happened to me before and I did not verify if the bug is present in earlier builds.

To clarify, **none** of the fire sources listed on the screenshot is actually available to me at that point. There is, however, an actual fire going on behind the menu screen, one step from where my character is standing.

**Comment by ipcyborg** [comment] 2019-10-06 11:27
Can't reproduce in 0.D-8234-gfd911084b2
Continue crafting on step 3 (after step 2b), no menu appeared.

**Comment by ifreund** [comment] 2019-10-12 12:29
Can't reproduce either on 4939b354ca8ab9ca47dd3c797cda446b3510bfcf.

**Comment by davidpwbrown** [comment] 2019-10-26 12:18
This is similar to #33746 which cant be reproduced either on latest master- therefore closing due to this and the previous two comments, and I cant reproduce either.

**Closed by davidpwbrown** 2019-10-26 12:18 UTC
Labels: (S1 - Need confirmation), <Bug>, Crafting / Construction / Recipes
