### ISSUE TITLE
can't start cataclysm on ubuntu14

### ISSUE THREAD

**Issue by hejian1639** [CleverRaven/Cataclysm-DDA#28348] opened 2019-02-24 09:35 UTC
I'm new here, when I run ./cataclysm, I got below error, can anyone help me?

> -bash: ./cataclysm: No such file or directory

my compute is ubuntu 14, game version is cataclysmdda-0.B.

**Comment by ifreund** [comment] 2019-02-24 09:53
Sounds like you're running the command in the wrong directory, this is not a bug or feature request so I'm closing the issue.  If you need help I'd suggest asking on on the forums or in the discord server.

Side note, 0.B is very old at this point, I think you'd enjoy the latest experimental more.  0.D should also be out in less than 2 weeks if you'd prefer a stable.

**Closed by ifreund** 2019-02-24 09:53 UTC
