### ISSUE TITLE
Makeshift welder "duplicate" allowing for infinite car repairs

### ISSUE THREAD

**Issue by xeonicus** [CleverRaven/Cataclysm-DDA#22881] opened 2018-02-04 23:01 UTC
Game version: 0.C-26156-g4daf02e (Build 7102, 64-bit, Linux, Graphical)

Operating system: Ubuntu 15.04 (Zorin OS 10 64-bit)

Tiles or curses: Tiles

Mods active: Filthy Clothing, Disable NPC Needs, Simplified Nutrition, Icecoon's Arsenal, Medieval and Historic Content, More Survival Tools, Makeshift Items Mod, Mutant NPCs, NPC traits, Beta National Guard Camp, More Buildings, More Locations, Tall Buildings, Boats, Folding Parts pack, Vehicle Additions Pack, Tanks and other Vehicles, StatsThroughSkills

### Expected behavior
When repairing the vehicle with a makeshift welder in my inventory, it correctly consumes the batteries in the welder and completes the repairs.

### Actual behavior
When repairing the vehicle with a makeshift welder in my inventory, a duplicate makeshift welder is showing up nearby and I am prompted to choose between the two.  I can use the nearby one to complete repairs, although it never consumes batteries or affects the original in the inventory.

### Steps to reproduce the behavior
1) Here is the save game: 
[Deadlands.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/1693401/Deadlands.tar.gz)

2) Locate the vehicle just outside the Evac shelter to the east.  Equip the crowbar and smash the vehicle until it requires repairs.
3) Examine the vehicle, try to repair the damage using the makeshift welder in your inventory.
4) You will receive the prompt "Use which tool?"  Select the "nearby" makeshift welder.  (Note: There doesn't appear to be a nearby makeshift welder)
5) You can rinse and repeat and the welder in your inventory will never run out of batteries. 

### Additional Notes
I've disassembled the makeshift welder and re-crafted it and the same thing occurs.  I've debugged in a normal welder and the same thing occurs.  I have tried doing repairs on other cars, and the same thing occurs.

**Comment by xeonicus** [comment] 2018-02-04 23:22
On further investigation, any vehicle repairs that require some kind of consumable resource (i.e. superglue, duct tape, etc) seem to be exhibiting this behavior.  For further clarification, when the prompt "Use which tool" appears I can always choose what's in my inventory and it does correctly consume it.

**Comment by Night-Pryanik** [comment] 2018-02-05 05:51
Duplicate of #22789.

**Closed by Night-Pryanik** 2018-02-05 05:51 UTC
Labels: Duplicate
