### ISSUE TITLE
Crashed when interacted with tile that hold broken? item ( Superior potion starter from Magiclysm in this case).

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#78508] opened 2024-12-12 04:04 UTC
### Describe the bug

~~So, I crafted some superior potion starters from Magiclysm mod. Then I put it in an empty glass flask inside my food truck freezer in my vehicle. Now, any interaction with the food truck freezer crash my game, whenever it is crafting involved the superior potion starter, or pick up item menu, eating menu, advanced inventory ....~~

After updating the game to the experimental-2024-12-11-2206 to salvage my save, the crash is gone. I don't know if I should close the issue...

### Attach save file

[Palm Beach Shores-trimmed.tar.gz](https://github.com/user-attachments/files/18105273/Palm.Beach.Shores-trimmed.tar.gz)

### Steps to reproduce

1. Load save.
2. Interact with food truck freezer tile.

### Expected behavior

Not crashing me precious game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: cdda-experimental-2024-11-03-2221 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/18105306/crash.log)
[debug.log](https://github.com/user-attachments/files/18105309/debug.log)

**Comment by RenechCDDA** [comment] 2024-12-12 04:41
Was fixed by #77551

Since you've updated to a newer version and confirmed you're no longer experiencing the crash, we can indeed close this. :)

**Closed by RenechCDDA** 2024-12-12 04:41 UTC
Labels: (S1 - Need confirmation)
