### ISSUE TITLE
Plant serum is a vehicle part.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17933] opened 2016-08-05 14:19 UTC
![2016-07-28-115713_236x140_scrot](https://cloud.githubusercontent.com/assets/11578180/17439417/448b07c2-5b28-11e6-9536-3ec7167515a2.png)
![2016-08-05-161807_960x109_scrot](https://cloud.githubusercontent.com/assets/11578180/17439419/4b40be0e-5b28-11e6-8031-cdc2ef6513c0.png)

**Comment by woutershep** [comment] 2016-08-05 14:19
As is all the other serum with the exception of mutagenic serum and purifier serum.

**Comment by DLaboratory** [comment] 2016-08-09 14:56
But no problem here. Built from commit `3a38fd5`.

![plant serum](https://cloud.githubusercontent.com/assets/5671495/17521005/4d315886-5e84-11e6-9c16-5b10877307a4.png)

**Comment by Soyweiser** [comment] 2016-08-11 02:58
Also can't confirm. Wouter, which version are you using?

**Comment by woutershep** [comment] 2016-08-11 16:03
Can't reproduce it either anymore on the 1a74cd590dd88977cd589ad51e5fbd2f8d70c2bf that i have now. Assuming one of the commits meanwhile fixed it. Might bisect it later out of curiosity because it all feels a bit strange, but for now im closing this.

**Comment by woutershep** [comment] 2016-08-16 13:47
Reopening, happened again, after some fidgeting i can reliably reproduce on todays 817d3a5.

1. start cataclysm up freshly, do nothing else with it other than these steps.
2. make new world.
3. make a new random character in this new world.
4. look at serum in debug wish menu, it is correctly MUTAGEN.
5. save and quit to main menu. do not exit cataclysm fully.
6. load the random character back up.
7. look at serum in debug wish menu. its now wrongly VEHICLE PARTS.

Since it might be some undefined behavior using old memory weirdness or something it might be important to note that i am on 64bit linux and compiled it with gcc 5.4.

**Comment by illi-kun** [comment] 2016-09-13 16:26
In my case, it's "MUTAGEN" before save & load, and no category or crash after.
Win10, today's exp build.

**Comment by illi-kun** [comment] 2016-09-15 19:24
Closing as a duplicate of #17949.

**Closed by illi-kun** 2016-09-15 19:24 UTC
Labels: Bug, Crash

**Comment by codemime** [comment] 2016-09-20 01:34
@woutershep Could reproduce and got the same behavior.
