### ISSUE TITLE
Jack is Unusable if Stored in the Vehicle

### ISSUE THREAD

**Issue by Rod995** [CleverRaven/Cataclysm-DDA#26335] opened 2018-10-21 05:49 UTC
**Describe the bug**  
Jack doesn't work if in vehicle cargo, regardless of distance.
But the jack works if it's on the ground or in the inventory.

**To Reproduce**  
1. Put a bottle jack in a vehicle.
2. Try to jack a wheel.
3. Ha! No wheel coming off today!

**Expected behavior**  
I wanna take a wheel off.

**Screenshots**  

![](https://cdn.discordapp.com/attachments/365907426270117888/503311187400851457/unknown.png)
![](https://cdn.discordapp.com/attachments/365907426270117888/503311366518734879/unknown.png)
![](https://cdn.discordapp.com/attachments/365907426270117888/503311647289376778/unknown.png)

**Versions and configuration(please complete the following information):**
 - OS: ``Windows 10``
 - Game Version: ``0.C-33432-gef7bf77``
 - Graphics version: ``Tiles``
 - Mods loaded `` "dda",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "Tolerate_This",
  "realguns",
  "More_Survival_Tools",
  "boats",
  "MST_Extra",
  "Medieval_Stuff",
  "Youkai_Disco",
  "alt_map_key",
  "Cata++",
  "Mining_Mod",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "FujiStruct",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Arcana",
  "makemegamangreatagain",
  "No_Fungi",
  "Nonperishable_Overhaul",
  "no_reviving_zombies",
  "StatsThroughSkills",
  "no_freeze"``

**Comment by Zireael07** [comment] 2018-10-21 08:30
I believe jack usability is determined via line-of-sight, and vehicle cargo iirc blocks los.

**Comment by Rod995** [comment] 2018-10-21 22:08
It's odd mainly as almost all other tools work if stored, under the expectation that physically moving around and grabbing tools is abstracted away any time crafting/tool radius is used.

**Comment by Night-Pryanik** [comment] 2019-01-31 06:52
Duplicate of  #17953.

**Closed by Night-Pryanik** 2019-01-31 06:52 UTC
Labels: Items / Item Actions / Item Qualities, Vehicles
