### ISSUE TITLE
AK rarity

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15878] opened 2016-03-23 15:28 UTC
Currently, AKs and ammo for them (7.62x39 and 5.45x39) are both very, very rare (only really appearing in gun basement safes) compared to 5.56 weapons. As such, it's always a better option to use 5.56 weaponry, as it's generally better and more plentiful.
Of course, IRL even in New England it's easy to get your hands on some manner of AK, as it's probably the most common gun on earth. Any ideas for correcting this? Maybe new rare and common AK derivatives? Simply amping up commonality? Adding a lategame improvised AK to be craftable?

**Comment by mugling** [comment] 2016-03-23 15:38
> only really appearing in gun basement safes

This isn't the case. There are a **lot** more sources of `guns_rifle_rare` as well as the superset `guns_rare`. Have a look around `data/json` if you're curious.

> As such, it's always a better option to use 5.56 weaponry, as it's generally better and more plentiful.

One of the balance points was that `22`, `9mm` and `223` ammo should be plentiful and everything else less common. Other ammo types have their own advantages to offset that, the plan for 7.62x39 being durability/reliability.

> Any ideas for correcting this?

This is intentional. Rare guns should be just that. If you explore more you'll find there are additional sources and this continues to be worked upon.

**Comment by kevingranade** [comment] 2016-03-23 16:16
Also if you're asserting relative rarity of items, please provide IRL
sources. I haven't been able to find anything, so if you provide a credible
source that agrees with you, you pretty much win. Unless we have those
sources, we'll stick with game balance rationales for frequency.

**Comment by martin509** [comment] 2016-03-23 16:26
I'm totally fine with AKs being rarer than 223 weapons and ammo, but right now it's very impractical to use 7.62x39 in comparison to .223. One can have several hundred rounds of .223 or 5.56 by the midgame, but only 2-3 magazines worth of 7.62x39 at the same time.
I did think it was common knowledge that AKs are a common weapon type IRL, my apologies.

**Comment by Chezzo** [comment] 2016-03-23 16:34
Here's the New Atlantic Monthly, a technology journal's article called, "The World's Most Popular Gun."

http://www.thenewatlantis.com/publications/the-worlds-most-popular-gun

**Comment by mugling** [comment] 2016-03-23 16:53
> One can have several hundred rounds of .223 or 5.56 by the midgame, but only 2-3 magazines worth of 7.62x39 at the same time.

Taking several hundred as 300-600 rounds and 2-3 magazines as 60-90 thats a ratio of about 1:5 which would seem about right. You can of course handload further rounds as necessary.

> I did think it was common knowledge that AKs are a common weapon type IRL, my apologies

No need to appologise. I've no objection to moving AK to be a common weapon if that's deemed appropriate, only to making the rare guns less rare

**Comment by martin509** [comment] 2016-03-23 17:52
Perhaps adding some rare imported AKs, then? Stuff in the same league as the AN-94, ie imported russian army equipment.

**Comment by mugling** [comment] 2016-03-23 18:05
> Perhaps adding some rare imported AKs while making basic ones common, then?

We already have too many almost-identical items so adding more isn't likely to be helpful.

We should aim addressing the balance of the existing items which in this case is deciding if the AK belongs in `guns_rifle_common` or `guns_rifle_rare` and how it should be weighted relative to other members of each group.

This is of course a can of worms in that `7.62x39` ammo should definitely not be common compared to `223` so you might end up with a common gun with uncommon ammo (which is definitely not useful).

It would be better to try and differentiate the AK from other rifles rather than make it a commonly available duplicate of the other 223 rifles. When I get round to reworking gun and magazine reliability this is one of the items I want to look at further.

**Comment by kevingranade** [comment] 2016-03-23 20:38
I understand where you're coming from, but
> AKs are a common weapon type IRL

Doesn't translate into, "make AKs 3x more common". I need some measure of
*how* common they are, otherwise I can't do anything sensible about it.

**Comment by Rivet-the-Zombie** [comment] 2016-03-23 23:33
7.62x39mm isn't particularly difficult to come by; around here you can find it in any store that sells ammunition.

**Comment by mugling** [comment] 2016-03-23 23:35
@Rivet-the-Zombie how common compared to `223` as if that can be defined we could move it to `ammo_rifle_common`

**Comment by martin509** [comment] 2016-03-24 01:00
My view on the ammo types could be that 7.62x39 could be more damaging, less armour-piercing, less accurate and with a lower range than .223, and.. I'd say somewhat less common? This is all relatively inline with my understanding of it IRL.
As for 5.45? The 7N10 and 7N22 armour-piercing types of it could be rather interesting to differentiate it from .223.

**Comment by Rivet-the-Zombie** [comment] 2016-03-24 01:45
@mugling, maybe a bit less common than 5.56, but still certainly common enough that you can easily pick up a few hundred rounds in a given place.

**Comment by kevingranade** [comment] 2016-03-24 08:12
I was able to find some sales figures from last year indicating 5.56 is
sold 3x as much as 7.62.

**Comment by martin509** [comment] 2016-03-25 03:33
From some quick google research, it seems that prices in the US for .223 likely go about maybe 25% more expensive than 7.62x39 ($0.25 per round vs. $0.30+).

**Comment by kevingranade** [comment] 2016-03-25 03:40
Unfortunately it looks like it's going to be really hard to find good numbers, especially for AK vs other stuff, because most of the half-devent stats are from domestic production, so there are no numbers for imports :/

**Comment by martin509** [comment] 2016-03-25 03:47
https://www.ammograb.com/762x39mm/ and https://www.ammograb.com/556x45mm-nato/ seem to be good sources, I'd say.

**Closed** 2016-03-26 05:21 UTC
