### ISSUE TITLE
Can't eat 'in progress black coffee (50%) (frozen)'

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76423] opened 2024-09-14 11:13 UTC
### Describe the bug

I interrupted in-progress black coffee to eat some vitamins, now when I want to continue cr'a'fting it, I suddenly attempt to eat it, and fail... :(

### Attach save file

[Nairn-trimmed.tar.gz](https://github.com/user-attachments/files/17002083/Nairn-trimmed.tar.gz)

### Steps to reproduce

1. Start brewing coffee
2. Pause for some other chores (5)
3. Return to your cooking (a)
4. You can't do anything but attempt to eat it :(

### Expected behavior

Obviously I'd like to finish brewing my coffee instead of eating it semi-raw!

### Screenshots

![image](https://github.com/user-attachments/assets/2a1aef09-1d66-4eaf-8d53-9b2719d33821)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-12-1816 2473620 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by harakka** [comment] 2024-09-14 11:36
Duplicate of #76414

**Closed by harakka** 2024-09-14 11:36 UTC
Labels: (S1 - Need confirmation)
