### ISSUE TITLE
CTD when accepting the first HUB mission twice.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#41899] opened 2020-07-06 15:48 UTC
# Describe the bug

I talked to the person in the intercom and accepted their first mission. If you do anything else other than saying goodbye after accepting the mission you are asked again if you would like to hear about the same mission. Accepting the mission a second time causes a CTD.

# Steps To Reproduce

1. Talk to the intercom and accept the mission.
2. Talk about something else.
3. Agree to hear about the mission again.
4. Accept the mission.

# Expected behavior

After accepting the mission you shouldn't be asked to hear about the same mission again.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.D-11004-g9fe2e72d43-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Roadheader and other mining vehicles [Heavy miners],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]

# Additional context
[crashANDdebugLOG.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4879957/crashANDdebugLOG.zip)
[Abo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4879958/Abo.zip)

**Comment by John-Candlebury** [comment] 2020-07-08 05:04
Appears to be a duplicate of #37056.
Please update to 0.E or later version and verify if the bug still happens.

**Comment by Quintovir** [comment] 2020-07-08 16:46
My usual methods of installing/updating the game have caused mods and tilesets to go missing.
Let me know if this is the wrong place to ask for troubleshooting tips.
I deleted the Cataclysm-DDA folder and made a fresh install with:

```
#!/bin/bash

repo=("/home/satjwu/Cataclysm-DDA")

git clone --depth 1 git://github.com/CleverRaven/Cataclysm-DDA.git
cd "${repo}"
make -j8 RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_XDG_DIR=1
./cataclysm-tiles
```
This is the new debug.log
```
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 4929649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]
```

A lot of mods are missing:
```
Mods loaded: [
Makeshift Items Mod [makeshift],
Medieval and Historic Classes and Shields [Medieval_Stuff],
More Survival Tools [More_Survival_Tools],
Garden Pots [growable-pots],
Modular Turrets [modular_turrets],
Salvaged Robots [Salvaged_Robots],
Hydroponics [hydroponics],
Fuji's More Buildings [FujiStruct],
Vehicle Additions Pack [blazemod],
Tanks and Other Vehicles [Tanks],
Folding Parts pack [deoxymod],
Roadheader and other mining vehicles [Heavy miners],
No Fictional Guns [no_rivtech_guns],
No Flaming Weapons [no_flaming_weapons],
Classes and Scenarios Mod [more_classes_scenarios],
]
```
Have these mods been cancelled? If not has someone made instructions on how to get them installed and automatically updated? If I manage to find the UNDEAD_PEOPLE tileset will it work with 0.E?

This is what I usually do to update the game:
```
#!/bin/bash

repo=("/home/satjwu/Cataclysm-DDA")

cd "${repo}"
git pull
make clean
make -j8 RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_XDG_DIR=1
./cataclysm-tiles
```

**Closed** 2020-07-08 17:15 UTC
