### ISSUE TITLE
Musical instrument messages are broken

### ISSUE THREAD

**Issue by shedya** [CleverRaven/Cataclysm-DDA#18030] opened 2016-08-14 14:09 UTC
redundant "You hear" in every message
![screen shot 2016-08-14 at 5 08 31 pm](https://cloud.githubusercontent.com/assets/17379794/17649587/c514dbaa-6241-11e6-9a99-f2ece2b49ce7.png)
![screen shot 2016-08-14 at 4 59 12 pm](https://cloud.githubusercontent.com/assets/17379794/17649588/c51676fe-6241-11e6-92a8-112a5b8bf2b2.png)
![screen shot 2016-08-14 at 4 50 59 pm](https://cloud.githubusercontent.com/assets/17379794/17649488/517f0f5a-623f-11e6-85ca-add8865f1c08.png)

**Comment by shedya** [comment] 2016-08-14 14:15
Also, playing musical instruments allows you to do anything else in the meanwhile. To read, for example.
![screen shot 2016-08-14 at 5 15 21 pm](https://cloud.githubusercontent.com/assets/17379794/17649638/b9e4391e-6242-11e6-849c-0f1754eddbd6.png)

**Comment by shedya** [comment] 2016-08-14 14:17
Or to craft.
![screen shot 2016-08-14 at 5 16 50 pm](https://cloud.githubusercontent.com/assets/17379794/17649647/ec00df24-6242-11e6-8b80-c7fad47d733e.png)

**Comment by DaliTimelord** [comment] 2016-08-15 15:18
A duplicate of #17820 . The reason is that the message you get when hearing and when you specifically play a music instrument use "You hear..." and "You play...".

Think the messages for musical instruments will need to be worked on.

**Comment by shedya** [comment] 2016-08-15 15:28
Oh I see. But what about the possibility to read/craft while playing? That clearly shouldn't be happening

**Comment by DaliTimelord** [comment] 2016-08-15 15:46
As hilarious as it sounds, playing musical instruments only decreases your speed by 10. Also, there isn't a very elegant way of preventing people from playing instruments and crafting at the same time without having to specifically check for this scenario. You can't say that because your arms are full you can't craft for example.

**Comment by Barhandar** [comment] 2016-08-16 04:00
I'd argue that trying to play and do something else at the same time should reduce speed of both, based on intelligence. IRL you have to be really good at multitasking to be able to do two things that take your attention at same time, or be good enough at one of them for it to not take your attention.

Crafting's sillier, but reading while playing is what everyone in orchestra does all the time - you just need somewhere to put your book on.

**Comment by shedya** [comment] 2016-08-16 12:49
Yet musicians in an orchestra read note sheets, which are directly related to what they're doing right now, not anything from articles with basic sewing tips to detailed information about assembling an atomic lamp

**Comment by illi-kun** [comment] 2016-09-13 15:42
Closing as a dupe.

**Closed by illi-kun** 2016-09-13 15:42 UTC
