### ISSUE TITLE
Installing CBMs is instant

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20884] opened 2017-04-21 21:22 UTC
I'm not sure if it varies from one type to another, but installing some CBMs (like power storage ones) take literally 0 seconds of in-game time. It's a little easy to abuse as a way to shed a lot of weight instantly if you're ambushed by zombies, since even dropping items takes up a small amount of time.

**Comment by DangerNoodle** [comment] 2017-04-21 22:06
That would be a heavy risk to take in combat, unless the install rate is fairly low. But if that is the case, the player has few valid reasons to delay installation.

**Comment by Regularitee** [comment] 2017-04-22 03:47
It depends on the character build, I suppose. But some of the easier mods to install (e.g., power capacity cbms) can get pushed down to a <3% failure rate -- so the chance of rolling a critical fail (and not just a fail) can be minuscule. 

Regardless, if an action as simple as reloading a gun can have a time cost, something as complex as performing self-surgery or installing a program shouldn't be instant.

**Comment by Night-Pryanik** [comment] 2017-04-22 04:29
Duplicate of #17698.

**Closed** 2017-04-22 05:45 UTC
Labels: Duplicate
