### ISSUE TITLE
Lighting a fire causes hot air tiles to show

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#44042] opened 2020-09-08 08:28 UTC
# Describe the bug

While lighting a stove I started to see tiles for hot air.

# Steps To Reproduce

1. Light a fire in a enclose space

# Expected behavior

I shouldn't be seeing a tile for hot air when I light a fire.

# Screenshots

![Screenshot (3157)](https://user-images.githubusercontent.com/56947231/92451823-36b16400-f1f8-11ea-876f-02c8be251d86.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: [from the main menu, e.g. 0.E-5791-gc9d731b
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

# Additional context

**Comment by wapcaplet** [comment] 2020-09-08 20:59
Confirmed 0.E-5799-gd2843c7920 [64-bit]

In most tilesets, the hot air sprite is a translucent overlay, but in UltiCa and ASCIItiles, the `&` character is used:

![image](https://user-images.githubusercontent.com/238395/92527054-a5d08d80-f1e3-11ea-981c-de0c54747beb.png)

**Comment by I-am-Erk** [comment] 2020-09-08 23:48
Although we can remove them in ultica, it should be fixed in the game code as well.

**Comment by Aivean** [comment] 2020-09-09 01:54
This is caused by my PR #44013 and it's (somewhat) intentional.

In the [field_type.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/e1277a9f38ead8f78845205ff22bb209f69963bc/data/json/field_type.json#L1278) there are two properties, `priority` and `display_field`. Before my change, if `priority` was < 0, field was not displayed. I figured this behavior duplicates the semantics of `display_field` property unnecessarily.

So, to revert fields visibility to the old state, we need to set `display_field` to `false` for the fields that have `priority<0` in `field_type.json`.  I think it's an easy fix and might be labeled as "Good first issue".

However, I kinda like the hot air display in tilesets that support it:
![fire](https://user-images.githubusercontent.com/2865203/92545251-97469e00-f204-11ea-86b8-1e504f40d38d.gif)

**Comment by I-am-Erk** [comment] 2020-09-09 04:05
Although it's kinda neat to see temperature fields, it shouldn't be something visualised like that.

**Comment by int-ua** [comment] 2020-09-09 06:47
What other fields are affected? `fd_hot_air_sauna`? `fd_migo_atmosphere`?

**Closed** 2020-09-09 10:28 UTC
Labels: (S2 - Confirmed), <Bug>, SDL: Tiles / Sound

**Comment by DoctorVanGogh** [comment] 2020-09-12 21:40
I don't know if this is the right place, but I think this deserves a reopen and a revert of #44079.

Very hot or cold air is **not** invisible. I mean, yes, that air itself *is* invisible, but you will have a heat haze on hot air and condensation on very cold air. 
This change makes little sense from a reality perspective, so it makes even _less_ sense to intentionally remove visual cues for the players.


Hot air *not* invisible:
https://pbs.twimg.com/media/Ehr1rH_UwAAcnz2?format=jpg&name=4096x4096
(The heat haze *below* the smoke)

Cold air *not* invisible:
https://www.nasa.gov/image-feature/falcon-9-fueling-underway-0
(This is *supercold* oxygen causing condensation in the air)

**Comment by Aivean** [comment] 2020-09-12 21:52
> Very hot or cold air is **not** invisible. I mean, yes, that air itself _is_ invisible, but you will have a heat haze on hot air and condensation on very cold air.

Maybe the best solution is a compromise. We can leave hot/cold air of low intensity invisible, but make it visible on intensity 3 (and maybe 2 also).

I don't think that PR revert is necessary, you can fine-tune `"display_field": true` in a separate PR.

**Comment by I-am-Erk** [comment] 2020-09-13 05:47
Both heat waves and condensation are only visible at interfaces, and even then aren't all that easy to spot. That's a much more complex request that would need to be considered as a separate feature.

**Comment by ZhilkinSerg** [comment] 2020-09-13 06:44
Think curses.
