### ISSUE TITLE
Crash when walking toward refugee center (see save file)

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#40865] opened 2020-05-26 16:56 UTC
# Describe the bug

Game crashes when trying to walk toward the refugee center to the north of the character. Sometimes I'm randomly asked what to do with random liquids I don't carry.

# Steps To Reproduce

1. Open save file
2. Walk north
3. Game crashes

# Expected behavior

Game doesn't crash or asks me what to do with drinks I don't carry.

# Additional context

[savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4683730/savegame.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4683733/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4683735/crash.log)

**Comment by DonHinJJ** [comment] 2020-05-30 03:11
This is the exact same issue I have, It'll start dropping liquids and then crash.

**Comment by anothersimulacrum** [comment] 2020-05-30 06:03
Judging by the backtrace, this is probably a duplicate of #40921 (both crash in `npc::find_reloadable`)

But I'm not sure, so let's see when the fix for that/this pops up if it fixes both.

**Comment by mlangsdorf** [comment] 2020-08-17 12:56
Can't reproduce on the latest experimental with the included save game.  If @RafeHaab doesn't comment in a week or so, I'll go ahead and close this.

**Comment by mlangsdorf** [comment] 2020-10-09 14:11
Can't reproduce, and initial reporter didn't respond.  Closing as resolved by some other fix.

**Closed by mlangsdorf** 2020-10-09 14:11 UTC
Labels: <Bug>, Items: Containers
