### ISSUE TITLE
NPC teaching glitch

### ISSUE THREAD

**Issue by FractalWire** [CleverRaven/Cataclysm-DDA#21410] opened 2017-07-11 12:05 UTC
When I ask a NPC to teach me something, there is always an error that pop, but I still learn the skill I ask for.

However, after successfully  learning mechanic from a NPC, I try again to learn brawling.
The NPC didn't taught me brawling, instead he taught me a new level of mechanic.

Which is interesting, because he actually didn't gave me the option to learn mechanic again (he is lvl 1 mech and taught me lvl 2). Which make me think I now have an infinite source of mechanic from him.

Here is the debug :

![learning](https://user-images.githubusercontent.com/16882885/28067474-c46d13a2-6641-11e7-87cd-ec4a0715f40e.png)

I'm using 0.C-6562 from july 6th

**Comment by chaos-dev** [comment] 2017-07-11 16:30
I've had this exact same error.  I also had the "brawling" error, except the NPC kept teaching me healing above and beyond his normal level.

**Comment by ituluwituluwzev** [comment] 2017-07-12 02:09
Duplicate of #18642

**Closed** 2017-07-12 03:00 UTC
Labels: Bug, Duplicate, NPC
