### ISSUE TITLE
Zombie soldier drops loot three times instead of one

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#15636] opened 2016-03-02 12:48 UTC
Too much loot for one creature.

**Comment by mugling** [comment] 2016-03-02 13:06
Can you be more specific?

**Comment by OsobistSCP** [comment] 2016-03-02 13:15
When you kill zombie soldier it drops three kits of it's lootdrop: three packs of cigarettes, three cash cards, three pairs of boots et cetera. A screenshot for example: http://cs631625.vk.me/v631625369/16d4b/BZIluOerL0M.jpg

**Comment by WizardOfOoo** [comment] 2016-03-07 03:43
I see your screenshot and I know it happened.

I killed 30 of them, spawned from the debug menu, and I did not get that bug.
I think this is the relevant code:   https://github.com/CleverRaven/Cataclysm-DDA/blob/ad34e0d96942c57c0d0ab6991c8c9a747922e3f8/data/json/monsterdrops/zombie_soldier.json

With my, admittedly, limited understanding I don't see a way to get two cash card drops.

Anybody have an idea what could cause a monster to drop loot twice?

**Comment by mugling** [comment] 2016-03-07 23:28
I'm not able to reproduce this. Anyone else?

**Comment by Night-Pryanik** [comment] 2016-03-08 05:54
I was able to reproduce on 0.C-4517, win 10, tiles.
![default](https://cloud.githubusercontent.com/assets/11132525/13593335/540f6370-e50b-11e5-83b9-8a1e130ecab6.png)

**Comment by mugling** [comment] 2016-03-08 13:47
@Night-Pryanik consistent or intermittently?

**Comment by Night-Pryanik** [comment] 2016-03-08 17:14
@mugling all the time I spawned zombie solder and killed it, I got this big loot.

**Comment by mugling** [comment] 2016-03-08 17:18
I'll have another look into this

**Comment by mugling** [comment] 2016-03-25 01:37
I'm fairly sure this was fixed by #15729 which effectively rewrote ` data/json/monsterdrops/zombie_soldier.json`

**Comment by OsobistSCP** [comment] 2016-03-26 16:33
I'm afraid it is still present.

**Comment by mugling** [comment] 2016-03-26 16:38
@OsobistSCP `master` or experimental build. Consistent or inconsistent?

**Comment by mugling** [comment] 2016-03-26 16:38
MingGW?

**Comment by OsobistSCP** [comment] 2016-03-26 18:32
Experimental, consistent. No mods were used while testing.

**Comment by mugling** [comment] 2016-03-26 18:39
I'll take another look

**Comment by OsobistSCP** [comment] 2016-04-04 06:21
Any luck with fixing?

**Comment by mugling** [comment] 2016-04-04 10:24
Sorry, not had chance to look into that

**Comment by Mshock777** [comment] 2016-04-16 16:35
Can't reproduce on build 4702.

**Comment by illi-kun** [comment] 2016-04-17 09:39
@Mshock777 It seems to be system/compiler specific, so for closing this we need to get confirmation of the fixed state from anyone who was able to reproduce it previously.

**Comment by Night-Pryanik** [comment] 2016-04-17 09:54
Well, I can't reproduce it either on 4695.

**Comment by OsobistSCP** [comment] 2016-04-17 11:40
Reason found, issue could be closed. The problem was on my side. Due to recent item groupes changes some death drops item groups were duplicated as files that contain them. Deleting obsolete files solved the problem. That's possible when you installing the new experimental version by overwriting the old one.

Sorry for troubles.

**Comment by illi-kun** [comment] 2016-04-17 11:49
Nice to hear that.

**Closed by illi-kun** 2016-04-17 11:49 UTC
Labels: Bug
