### ISSUE TITLE
Radio Activated Explosives don't go off in Animal's/NPC's Bag

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#36039] opened 2019-12-12 02:40 UTC
# Describe the bug

I just get the "click message" and no explosion. 

# Steps To Reproduce

1.Get a pet Chihuahua with a military rucksack(r other bag) strapped to it.
2. Put a radio activation mod on a stick of dynamite, I used the red button label
3. Use RC Control to set off explosive, but nothing happens besides the click sound.

# Expected behavior

Explosives should go off when in their inventory. I also confirmed that this is the case for NPC's.

# Screenshots

# Versions and configuration

<!-- Please complete the following information; you can now go to:
   - OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9770-g79d9ff5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

# Additional context

I feel so dirty coming up with this idea but I'm RPing a prison break death row inmate and would love to make improvised grenade hacks.

**Comment by Night-Pryanik** [comment] 2019-12-12 06:14
What are you trying to do with this poor little mutt, you flayer? 😈

**Comment by Orange01gaming** [comment] 2019-12-12 14:41
It was for science I swear! 

In all honesty I could achieve a similar goal with a radio activated noise maker and dynamite, but I thought it would be cool to send in home made "grenade hacks" into zombie hoards. Chihuahua are perfect for this since they never stop barking in game (at least mine doesn't).

**Comment by davidpwbrown** [comment] 2019-12-12 16:35
This is a cursed issue.

**Comment by Orange01gaming** [comment] 2019-12-12 18:22
> This is a cursed issue.

Not sure what you mean. I've heard something about "curse" when people are talked about development. Or do you mean its evil. Cuz yeah its totally evil. I feel bad I even came up with the idea. But now it seems like something we should be able to do. I mean we can turn our friends into monsters, do drugs and even use vibrators in game. If you can do it in real life you should be able to do it in CDDA right?

**Comment by Nerdy314159265** [comment] 2021-02-10 22:13
When this is patched I'd like to suggest adding a similar morale debuff similar to killing children zombies or butchering a human corpse if done without a trait to offset it.

**Comment by Orange01gaming** [comment] 2021-02-11 14:30
That would be awesome! I doubt think anyone wants to code it in from what
I've seen. Understanding it was a rather messed up thing to do in a game. I
still stand by that it could be a viable strategy in game.

**Comment by Nerdy314159265** [comment] 2021-02-13 22:18
@Orange01gaming I agree that it could be viable even if messed up.

It makes me wonder how the system works as is, I'd expect that a remote explosive would activate in whatever inventory it is in NPC or otherwise. Could there be other inventories that it won't explode in or is it specifically deactivated for NPCs?

**Comment by Night-Pryanik** [comment] 2021-09-12 14:41
Duplicate of #29859.

**Closed by Night-Pryanik** 2021-09-12 14:41 UTC
Labels: <Bug>, NPC / Factions, Monsters, Items / Item Actions / Item Qualities
