### ISSUE TITLE
Slimesprings don't follow you up stairs.

### ISSUE THREAD

**Issue by yowshi** [CleverRaven/Cataclysm-DDA#35779] opened 2019-11-29 21:36 UTC
# Describe the bug

Slimesprings spawned by omnicellular will not follow you upstairs.

# Steps To Reproduce

1. Start a game and debug yourself Omnicellular.
2. Go down a set of stairs with only one set of upstairs. Like a self-dug basement.
3. Spawn a slimespring.
4. Go upstairs and then walk around a bit. 

# Expected behavior

Slimesprings should follow you when you go upstairs like they do when you go downstairs. This also has the effect of making you unable to go back downstairs since the slimespring will be in your way.

# Versions and configuration

 - OS: Windows.
    -OS Version: Windows 10.0
 - Game Version: 0.D-9747-g5d65f8a
 - Graphics version: Tiles
 - Mods loaded: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]

**Comment by Night-Pryanik** [comment] 2019-11-30 04:59
Duplicate of #35665.

**Closed by Night-Pryanik** 2019-11-30 04:59 UTC
Labels: Monsters, Z-levels
