### ISSUE TITLE
Picking up specific number from stack duplicates items from stack, leaving original number still present on tile

### ISSUE THREAD

**Issue by fallout2077** [CleverRaven/Cataclysm-DDA#34341] opened 2019-09-30 08:11 UTC
Description:
When attempting to take only a certain number of chunks of meat (80, in this case, from a pile of 360), I instead wield all meat in the stack, while the game leaves the original number of meat behind, effectively multiplying meat every time I only take a certain amount.
Edit: I just noticed that this bug affects charcoal, too, so I'm going to assume that any stack is going to be touched by the bug.

1. Press 'e' to examine a tile that contains (e.g.) 360 chunks of meat.
2. Highlight the chunks in the following list, type '80' to only take 80, press right and then enter.
3. Check inventory, character now wielding 360 meat.
4. Check meat stack tile, meat hasn't been removed from tile, 360 still remain.

Expected behavior:
When taking 80 meat from a stack of 360, 280 should be remaining in meat stack.

Edit: I just discovered upon a Google search that this issue has already been addressed. Here is the reference: #33646 & here #34297 

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8048-g7488d08 [64-bit] Experimental build 9692
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Gun Cotton [guncotton],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Classic Roguelike Classes [RL_Classes],
    SpeedyDex [speedydex]
]

**Comment by starytroll** [comment] 2019-09-30 18:41
Looks like a duplicate of [#33646](https://github.com/CleverRaven/Cataclysm-DDA/issues/33646)

**Comment by anothersimulacrum** [comment] 2019-10-01 01:16
Similar to #34302

**Comment by fallout2077** [comment] 2019-10-01 05:10
After downloading and running the latest experimental (9695), the issue appears to be corrected. I'm not sure what may have changed since last night, but whatever was causing the issue seems to have subsided.

**Closed** 2019-11-07 06:24 UTC
Labels: <Bug>, <Exploit>, Items / Item Actions / Item Qualities
