### ISSUE TITLE
Charges not consumed when repairing (possibly other applications) using a welding device equipped with a battery compartment mod

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#23389] opened 2018-04-06 13:32 UTC
Game version:

0.C-27229-gae5bdc0 (Experimental build 7286)

Operating system:

Windows 10 64-bit

Tiles or curses:

Curses

Mods active:

Dark Days Ahead
Medieval and Historic Content
More Survival Tools
StatsThroughSkills
Vehicle Additions Pack
Tanks and Other Vehicles
Bionics Systems Mod
Boats
Folding Parts Pack
Filthy Clothing
Makeshift Items Mod
More Buildings
Disable NPC Needs
Simplified Nutrition
Mythological Replicas

### Expected behavior

(Note that this may apply to other applications, but so far I have only encountered it while repairing a vehicle.)

When choosing to repair a vehicle using a welding device held in inventory modified with a battery compartment mod, charges are consumed.

### Actual behavior

When choosing to repair a vehicle using a welding device held in inventory modified with a battery compartment mod, you are presented with two options:

1. Welding device (nearby)
2. Welding device (on person)

If you choose the 'nearby' device, charges are not consumed. Charges are consumed normally if the 'on person' device is chosen. This welding was performed in a situation where there was only one welding device present, held in my inventory.

### Steps to reproduce the behavior

For the **exact** conditions that I ran into this bug:

1. Acquire a makeshift welder, a battery compartment mod, and a small storage battery with enough charge to repair with
2. Attach the battery compartment mod to the makeshift welder and reload the small storage battery into it
3. Go to a vehicle and attempt to repair a damaged part
4. When choosing what to repair, you are prompted to select a makeshift welder 'nearby' and 'on person' -- choosing 'nearby' does not consume welding charges

**Comment by Night-Pryanik** [comment] 2018-04-06 13:43
Duplicate of #22789.

**Closed by Night-Pryanik** 2018-04-06 13:43 UTC
