### ISSUE TITLE
Character creation crash

### ISSUE THREAD

**Issue by harwoodr** [CleverRaven/Cataclysm-DDA#31399] opened 2019-06-13 19:26 UTC
# Describe the bug

Game gives an error during character creation and then aborts character creation.

# Steps To Reproduce

Steps to reproduce the behaviour:
1. Select Dark Days Ahead and Aftershock Mods (seems to only be with Aftershock)
2. Try to create a character

# Expected behaviour

To create a new character and play with Aftershock Mod loaded

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-4255-gc42e417478 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

This report was generated with default mods... for obvious reasons.

# Additional context

 DEBUG    : Error: basic_string::_M_construct null not valid
 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 709

**Comment by scalpelenema** [comment] 2019-06-13 19:36
same here. linux, default mods, crash when loading & creating new character

**Comment by harwoodr** [comment] 2019-06-13 19:45
Just tried 9148 and 9147 experimental builds and got same results...

**Comment by scalpelenema** [comment] 2019-06-13 19:50
the latest build which worked fine is 9139 I think

**Comment by Lucewithnootherideas** [comment] 2019-06-13 23:11
still happening on 9151

**Comment by Night-Pryanik** [comment] 2019-06-14 17:39
Seems like a duplicate of #31152.

**Comment by harwoodr** [comment] 2019-06-14 17:53
> Seems like a duplicate of #31152.

That one has a segfault... and I don't experience this problem with that build.

**Comment by mark7** [comment] 2019-06-14 20:53
git-bisect shows the first bad commit to be 64516a6b95b32e522ed6732b740a5cf178664d57

**Comment by mark7** [comment] 2019-06-14 21:24
@ymber and @kevingranade, 64516a6b95b32e522ed6732b740a5cf178664d57 was your patch and commit, respectively, as a heads-up.

**Comment by mark7** [comment] 2019-06-15 01:13
If the laser_rifle part on car_atomic_flame is removed from afs_vehicles.json, the bug also goes away.  Note that CrazyCataclysm also has this vehicle.

**Comment by mark7** [comment] 2019-06-15 01:44
If the second line in veh_type.cpp modified in 64516a6b95b32e522ed6732b740a5cf178664d57 is commented out, the bug is also not exhibited:

```
                 if( pt.ammo_types.empty() ) {
-                    pt.ammo_types.insert( base->gun->ammo->default_ammotype() );
+                    pt.ammo_types.insert( ammotype( *base->gun->ammo.begin() )->default_ammotype() );
                 }
```

**Closed** 2019-06-15 07:46 UTC
Labels: <Crash / Freeze>, Character / World Generation
