### ISSUE TITLE
My Very Bad Day starting towel is still wet (1 year +).

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#14437] opened 2015-12-15 11:36 UTC
Pretty much as the title says. Thing won't dry. 

Also can anyone explain how wetness works now? Because I'm pretty much wearing only water proof and friendly stuff and I still get massive -wet penalty, it seems quite nonsensical and I can't figure out why.

**Comment by illi-kun** [comment] 2015-12-15 11:42
Duplicate of #12146.

**Comment by illi-kun** [comment] 2015-12-15 12:46
If you're looking for more details about wetness, see #12256, #3909, or use searching via issues using keywords like "wet", "wetness", etc.

**Comment by chaosvolt** [comment] 2015-12-15 16:26
It's a bad sign when an issue goes so long without getting fixed ( https://github.com/CleverRaven/Cataclysm-DDA/issues/12146 was opened way back in April ) that duplicates start showing up. :V

**Comment by Coolthulhu** [comment] 2015-12-15 16:44
It doesn't dry retroactively.
Same for hot/cold food - it is only processed in the bubble.

As for wetness - water proof items aren't water friendly (except when they explicitly are). When they don't protect from wetness, they count as regular items. They protect from wetness when they're on the top of the given body part.
There is a bug with the processing - a single uncovered body part negates all water proofing (but not friendliness) if wetness source covers said body part.
For example, rain covers torso, head and arms. If your head "leaks", then torso and arms lose waterproofing (but not water friendliness) against rain.

**Comment by scorpion451** [comment] 2015-12-17 17:38
The "leaking" thing actually makes sense to me; having been caught in a downpour in a jacket without a hood: if your head isn't covered, water tends to run down the back of your neck and shoulders and soak you anyway.

**Comment by I-am-Erk** [comment] 2019-02-19 03:59
This doesn't appear to still be an issue. Closing until contradicted.

**Comment by Night-Pryanik** [comment] 2019-02-19 04:50
Tested on latest experimental as of 19th February, 2019. Created a shower victim with a wet towel, run around the shelter for a whole day, the towel is still wet.
And it won't get dry until somehow become `(active)` on game start.

**Comment by I-am-Erk** [comment] 2019-02-19 05:56
Ah, I misunderstood that it was unique to the scenario

**Comment by ZhilkinSerg** [comment] 2019-03-19 15:50
Non-wearable wet items already become active and get dried, but armor items as towel don't because they just get worn immediately.

https://github.com/CleverRaven/Cataclysm-DDA/blob/a159ebb18e21370aad786426f65e8ac06cae1ae9/src/newcharacter.cpp#L570-L588

**Closed** 2019-03-22 03:26 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
