### ISSUE TITLE
Attaching toolmods to tools inside a container will make the mod disappear

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#22057] opened 2017-10-02 03:42 UTC
Game version: 0.C-23665-g8805243

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Default

### Expected behavior
Attaching toolmods should always succeed, no matter where the tools are.
### Actual behavior
Attaching toolmods to tools inside a container will give the message "You successfully attached the toolmod to your none." and the tool remains unmodified
### Steps to reproduce the behavior
- put a tool inside a container
- attach a toolmod to the tool

**Comment by Night-Pryanik** [comment] 2017-10-02 08:56
Duplicate of #21859.

**Closed by Night-Pryanik** 2017-10-02 08:56 UTC
