### ISSUE TITLE
Some items in vending machines have $0.00 cost.

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#19600] opened 2016-12-02 23:54 UTC
Win10 x64 0.C-20040-g20172c1 (#5995)(tiles)

All items that are in aluminum cans cost nothing, and in a previous game I noticed other items that had zero cost as well - pretty sure those were also drink type items.

**Comment by codemime** [comment] 2016-12-03 00:55
It's a dupe of #17440.

**Closed** 2016-12-03 00:55 UTC
