### ISSUE TITLE
Brass not being stores in inventory.

### ISSUE THREAD

**Issue by Dantheman1337** [CleverRaven/Cataclysm-DDA#19680] opened 2016-12-08 09:59 UTC
When you use brass catcher it doesn't give you the brass back.

**Comment by BorkBorkGoesTheCode** [comment] 2016-12-08 14:55
@Dantheman1337 what experimental are you using?

**Comment by mugling** [comment] 2016-12-08 15:31
Fairly confident that was fixed in `master`. Are you sure you're unloading to return the brass?

**Comment by codemime** [comment] 2016-12-08 15:37
Is this a variation of #17588?

**Comment by articulateSPLINE** [comment] 2016-12-09 08:01
After a quick test in an unmodded 6031 world, it seems spent casings aren't ejected until the weapon is reloaded. Easiest to test on weapons with internal magazines (ie Remington 870 or Mossberg 500), simply load a few shells, fire them off and reload.

Weapons with detachable magazines behave a little differently: they only dump spent casings into the inventory if the weapon is reloaded with a different magazine, and reloading the already inserted magazine from a stack of ammo (from inventory or nearby tile, doesn't matter) sees the casings seemingly destroyed.

**Comment by mugling** [comment] 2016-12-09 19:58
> and reloading the already inserted magazine from a stack of ammo (from inventory or nearby tile, doesn't matter) sees the casings seemingly destroyed.

Everything apart from this is intended behavior

**Comment by saneman226** [comment] 2016-12-10 19:00
The brass catcher is attached when he reloads, isn't it supposed to return casings instead of destroying them? @mugling

**Comment by articulateSPLINE** [comment] 2016-12-12 04:00
@saneman226 I think that's why he said everything BUT that was intended ;)

**Comment by Night-Pryanik** [comment] 2019-02-03 09:17
Tested right now on 8496 with M14 with attached brass catcher - casings are correctly given to the player after removing the catcher from the weapon.

**Closed by Night-Pryanik** 2019-02-03 09:17 UTC
Labels: <Bug>, Gunmod / Toolmod, Inventory / AIM / Zones
