### ISSUE TITLE
Fire duration with cooking.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#31809] opened 2019-06-24 18:45 UTC
I am not really sure if its a bug or a feature, but when you are cooking it does not matter how much fuel you throw in your fireplace. You can fire 1 splintered wood and do a recipe requiring a fire that takes several hours - it will complete even if fire goes out.

**Comment by ifreund** [comment] 2019-06-24 19:52
Duplicate of #7126.

Anyhow, I have a fix for this in progress, just need to work out a few kinks when I have the time before I open a PR.

**Closed by ifreund** 2019-06-24 19:52 UTC
