### ISSUE TITLE
Segmentation Fault when trying to reload a mounted turret with ammunition

### ISSUE THREAD

**Issue by JeremiasB** [CleverRaven/Cataclysm-DDA#45559] opened 2020-11-21 21:25 UTC
# Describe the bug
Trying to reload a mounted turret causes a segmentation fault. 

# Steps To Reproduce

1. Attach a gun to a turret mount on a vehicle
2. Try to reload it with a compatible magazine
3. The game dies with a segmentation fault

# Expected behavior

A segmentation fault does not occur

# Screenshots

![Unbenannt](https://user-images.githubusercontent.com/33179984/99887799-ddc66900-2c47-11eb-931a-abd76d690e52.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7759-gf3a1933 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Here is the crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5578401/crash.log)

Here is the debug log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5578403/debug.log)

And finally here is a safe file with a vehicle with 2 turrets installed and ammunation nearby and on player:
[Sloan.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5578408/Sloan.zip)

**Comment by CAHEK7** [comment] 2020-11-21 22:01
Duplicate of #45545

**Closed** 2020-11-21 22:10 UTC
Labels: (S3 - Duplicate)
