### ISSUE TITLE
Crash after Killing Fat Prisoner Zombie

### ISSUE THREAD

**Issue by TheCourier6** [CleverRaven/Cataclysm-DDA#64486] opened 2023-03-23 04:02 UTC
### Describe the bug

I am in the Prison Start and every time I kill this Fat Prisoner Zombie it has caused my game to crash. I believe it may be due to the achievement Decamate being achieved after the death, but I'm uncertain regarding that possibility. As I had been quite fine acquiring the achievements: Rude Awakening, Teacher! Leave them Kids Alone, One Down Billions to Go.

However as I tested to see if I could do this by killing a Tough Zombie instead, I was given the Decamate achievement without issue. It's only when I kill a Fat Prison Zombie that I am given the crash.

### Attach save file

[Wolfforth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11046733/Wolfforth-trimmed.tar.gz)

### Steps to reproduce

Start in Prison Escape
Make Political Prisoner
Bring Boxing Martial Art
Kill 10 Zombies - MAKE SURE THE LAST ONE IS A FAT PRISONER ZOMBIE

### Expected behavior

I expect to not have my game crash from an achievement considering I was capable of acquiring multiple other achievements in this run so far without a crash.

### Screenshots

![6a0d1a41488ee8919123c5f692af3e58](https://user-images.githubusercontent.com/59447981/227098559-e57f7c1c-0e9d-4fdb-b6ab-043661515c8f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: d2ccb85 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Blaze Industries [blazeindustries],
    Gun Cotton [guncotton],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Original Drug Names [OG_Drugs],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Xedra Evolved [xedra_evolved],
    Useful Helicopters Experimental [useful_helicopters],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by irwiss** [comment] 2023-03-23 04:39
```c++
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: d2ccb85
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x7ff78fe080e0[cataclysm-tiles.exe+0x2380e0]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x1402380e0),
    0x1402380e0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:1121    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff78fdf0a43[cataclysm-tiles.exe+0x220a43]), 
    (libbacktrace: log_crash+0x1de@0x140220a43),
    0x140220a43    src/crash.cpp:918    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x140220a43    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:85    log_crash
  #2
    (dbghelp: @0x7ff78fdf0c6b[cataclysm-tiles.exe+0x220c6b]), 
    (libbacktrace: signal_handler+0x52@0x140220c6b),
    0x140220c6b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:137    signal_handler
  #3
    (dbghelp: raise+0x22c@0x7ffed9d3e0ac[msvcrt.dll+0x2e0ac]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ffed9d4255b[msvcrt.dll+0x3255b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x7ff78fbd447a[cataclysm-tiles.exe+0x447a]), 
    (libbacktrace: achievements_tracker::report_achievement(achievement const*, achievement_completion)+0xa8@0x14000447a),
    0x14000447a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:1648    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(string_id<achievement> const&)
    0x14000447a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:1640    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(string_id<achievement> const&)
    0x14000447a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:869    std::unordered_map<string_id<achievement>, achievement_tracker, std::hash<string_id<achievement> >, std::equal_to<string_id<achievement> >, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> > >::find(string_id<achievement> const&)
    0x14000447a    src/string_formatter.h:792    achievements_tracker::report_achievement(achievement const*, achievement_completion)
  #6
    (dbghelp: @0x7ff78fbd4d4b[cataclysm-tiles.exe+0x4d4b]), 
    (libbacktrace: achievement_tracker::set_requirement(requirement_watcher*, bool)+0x2d5@0x140004d4b),
    0x140004d4b    src/string_formatter.h:686    achievement_tracker::set_requirement(requirement_watcher*, bool)
  #7
    (dbghelp: @0x7ff79054ffeb[cataclysm-tiles.exe+0x97ffeb]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14097ffeb),
    0x14097ffeb    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14097ffeb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #8
    (dbghelp: @0x7ff790550280[cataclysm-tiles.exe+0x980280]), 
    (libbacktrace: stats_tracker::transformed_set_changed(string_id<event_transformation> const&, event_multiset const&)+0x50@0x140980280),
    0x140980280    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, event_multiset const&, stats_tracker&, event_multiset const&, stats_tracker&>(void (event_multiset_watcher::*)(event_multiset const&, stats_tracker&), event_multiset const&, stats_tracker&) const
    0x140980280    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:313    stats_tracker::transformed_set_changed(string_id<event_transformation> const&, event_multiset const&)
  #9
    (dbghelp: @0x7ff79054ffeb[cataclysm-tiles.exe+0x97ffeb]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14097ffeb),
    0x14097ffeb    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14097ffeb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #10
    (dbghelp: @0x7ff790d1b4c3[cataclysm-tiles.exe+0x114b4c3]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114b4c3),
    0x14114b4c3    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #11
    (dbghelp: @0x7ff7905509d6[cataclysm-tiles.exe+0x9809d6]), 
    (libbacktrace: stats_tracker::notify(cata::event const&)+0x90@0x1409809d6),
    0x1409809d6    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:370    stats_tracker::notify(cata::event const&)
  #12
    (dbghelp: @0x7ff78fe86512[cataclysm-tiles.exe+0x2b6512]), 
    (libbacktrace: event_bus::send(cata::event const&) const+0x26@0x1402b6512),
    0x1402b6512    src/event_bus.cpp:1108    __gnu_cxx::__normal_iterator<event_subscriber* const*, std::vector<event_subscriber*, std::allocator<event_subscriber*> > >::operator++()
    0x1402b6512    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:58    event_bus::send(cata::event const&) const
  #13
    (dbghelp: @0x7ff7904f507c[cataclysm-tiles.exe+0x92507c]), 
    (libbacktrace: stats_tracker::deserialize(JsonObject const&)+0xc12@0x14092507c),
    0x14092507c    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:312    ~map
    0x14092507c    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:312    std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cata_variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cata_variant> > >::~map()
    0x14092507c    src/monster.h:787    ~event
    0x14092507c    src/monster.h:787    cata::event::~event()
    0x14092507c    src/enum_conversions.h:4699    stats_tracker::deserialize(JsonObject const&)
  #14
    (dbghelp: @0x7ff790421250[cataclysm-tiles.exe+0x851250]), 
    (libbacktrace: past_game_info::past_game_info(JsonObject const&)+0x3ca@0x140851250),
    0x140851250    src/third-party/flatbuffers/base.h:317    decltype ((({parm#1}.deserialize)(*this)),(true)) JsonValue::read<stats_tracker>(stats_tracker&, bool) const
    0x140851250    src/third-party/flatbuffers/base.h:1143    bool JsonObject::read<stats_tracker>(char const*, stats_tracker&, bool) const
    0x140851250    src/past_games_info.cpp:41    past_game_info::past_game_info(JsonObject const&)
  #15
    (dbghelp: @0x7ff790ede74b[cataclysm-tiles.exe+0x130e74b]), 
    (libbacktrace: void std::vector<past_game_info, std::allocator<past_game_info> >::_M_realloc_insert<JsonObject>(__gnu_cxx::__normal_iterator<past_game_info*, std::vector<past_game_info, std::allocator<past_game_info> > >, JsonObject&&)+0xab@0x14130e74b),
    0x14130e74b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_vector.h:175    void std::__new_allocator<past_game_info>::construct<past_game_info, JsonObject>(past_game_info*, JsonObject&&)
    0x14130e74b    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/process.h:516    void std::allocator_traits<std::allocator<past_game_info> >::construct<past_game_info, JsonObject>(std::allocator<past_game_info>&, past_game_info*, JsonObject&&)
    0x14130e74b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_uninitialized.h:462    void std::vector<past_game_info, std::allocator<past_game_info> >::_M_realloc_insert<JsonObject>(__gnu_cxx::__normal_iterator<past_game_info*, std::vector<past_game_info, std::allocator<past_game_info> > >, JsonObject&&)
  #16
    (dbghelp: @0x7ff790422089[cataclysm-tiles.exe+0x852089]), 
    (libbacktrace: past_games_info::ensure_loaded()+0x5b3@0x140852089),
    0x140852089    src/past_games_info.cpp:145    past_games_info::ensure_loaded()
  #17
    (dbghelp: @0x7ff7904223f1[cataclysm-tiles.exe+0x8523f1]), 
    (libbacktrace: get_past_games()+0x14@0x1408523f1),
    0x1408523f1    src/past_games_info.cpp:179    get_past_games()
  #18
    (dbghelp: @0x7ff78ff19888[cataclysm-tiles.exe+0x349888]), 
    (libbacktrace: achievement_attained(achievement const*, bool)+0x12d@0x140349888),
    0x140349888    src/cata_utility.h:361    achievement_attained
  #19
    (dbghelp: @0x7ff790df5ae7[cataclysm-tiles.exe+0x1225ae7]), 
    (libbacktrace: std::function<void (achievement const*, bool)>::operator()(achievement const*, bool) const+0x27@0x141225ae7),
    0x141225ae7    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:591    std::function<void (achievement const*, bool)>::operator()(achievement const*, bool) const
  #20
    (dbghelp: @0x7ff78fbd45f0[cataclysm-tiles.exe+0x45f0]), 
    (libbacktrace: achievements_tracker::report_achievement(achievement const*, achievement_completion)+0x21e@0x1400045f0),
    0x1400045f0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:794    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index(std::__detail::_Hash_node_value<std::pair<string_id<achievement> const, achievement_tracker>, false> const&) const
    0x1400045f0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:2298    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase(std::__detail::_Node_const_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x1400045f0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:969    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase(std::__detail::_Node_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x1400045f0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:746    std::unordered_map<string_id<achievement>, achievement_tracker, std::hash<string_id<achievement> >, std::equal_to<string_id<achievement> >, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> > >::erase(std::__detail::_Node_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x1400045f0    src/string_formatter.h:806    achievements_tracker::report_achievement(achievement const*, achievement_completion)
  #21
    (dbghelp: @0x7ff78fbd4d4b[cataclysm-tiles.exe+0x4d4b]), 
    (libbacktrace: achievement_tracker::set_requirement(requirement_watcher*, bool)+0x2d5@0x140004d4b),
    0x140004d4b    src/string_formatter.h:686    achievement_tracker::set_requirement(requirement_watcher*, bool)
  #22
    (dbghelp: @0x7ff79054ffeb[cataclysm-tiles.exe+0x97ffeb]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14097ffeb),
    0x14097ffeb    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14097ffeb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #23
    (dbghelp: @0x7ff790d1b4c3[cataclysm-tiles.exe+0x114b4c3]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114b4c3),
    0x14114b4c3    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #24
    (dbghelp: @0x7ff79055022a[cataclysm-tiles.exe+0x98022a]), 
    (libbacktrace: stats_tracker::transformed_set_changed(string_id<event_transformation> const&, cata::event const&)+0x4a@0x14098022a),
    0x14098022a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:304    stats_tracker::transformed_set_changed(string_id<event_transformation> const&, cata::event const&)
  #25
    (dbghelp: @0x7ff790bd4eea[cataclysm-tiles.exe+0x1004eea]), 
    (libbacktrace: event_transformation_impl::state::event_added(cata::event const&, stats_tracker&)+0x8a@0x141004eea),
    0x141004eea    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:312    ~map
    0x141004eea    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:312    std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cata_variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cata_variant> > >::~map()
    0x141004eea    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:787    ~event
    0x141004eea    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:787    cata::event::~event()
    0x141004eea    src/third-party/flatbuffers/flexbuffers.h:589    event_transformation_impl::state::event_added(cata::event const&, stats_tracker&)
  #26
    (dbghelp: @0x7ff790d1b4c3[cataclysm-tiles.exe+0x114b4c3]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114b4c3),
    0x14114b4c3    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #27
    (dbghelp: @0x7ff7905509d6[cataclysm-tiles.exe+0x9809d6]), 
    (libbacktrace: stats_tracker::notify(cata::event const&)+0x90@0x1409809d6),
    0x1409809d6    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:370    stats_tracker::notify(cata::event const&)
  #28
    (dbghelp: @0x7ff78fe86512[cataclysm-tiles.exe+0x2b6512]), 
    (libbacktrace: event_bus::send(cata::event const&) const+0x26@0x1402b6512),
    0x1402b6512    src/event_bus.cpp:1108    __gnu_cxx::__normal_iterator<event_subscriber* const*, std::vector<event_subscriber*, std::allocator<event_subscriber*> > >::operator++()
    0x1402b6512    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:58    event_bus::send(cata::event const&) const
  #29
    (dbghelp: @0x7ff7902c9c53[cataclysm-tiles.exe+0x6f9c53]), 
    (libbacktrace: monster::die(Creature*)+0x3bf@0x1406f9c53),
    0x1406f9c53    src/event.h:25    void event_bus::send<(event_type)19, character_id, string_id<mtype> const&>(character_id&&, string_id<mtype> const&) const
    0x1406f9c53    src/monster.h:2566    monster::die(Creature*)
  #30
    (dbghelp: @0x7ff790230900[cataclysm-tiles.exe+0x660900]), 
    (libbacktrace: Character::melee_attack_abstract(Creature&, bool, string_id<ma_technique> const&, bool)+0x2ff0@0x140660900),
    0x140660900    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:891    Character::melee_attack_abstract(Creature&, bool, string_id<ma_technique> const&, bool)
  #31
    (dbghelp: @0x7ff790230f77[cataclysm-tiles.exe+0x660f77]), 
    (libbacktrace: Character::melee_attack(Creature&, bool)+0xb7@0x140660f77),
    0x140660f77    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:469    Character::melee_attack(Creature&, bool)
  #32
    (dbghelp: @0x7ff78fc8a317[cataclysm-tiles.exe+0xba317]), 
    (libbacktrace: avatar_action::move(avatar&, map&, tripoint const&)+0xc86@0x1400ba317),
    0x1400ba317    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/unique_ptr.h:355    avatar_action::move(avatar&, map&, tripoint const&)
  #33
    (dbghelp: @0x7ff78ff5f374[cataclysm-tiles.exe+0x38f374]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, std::optional<tripoint> const&)+0x58a@0x14038f374),
    0x14038f374    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/unique_ptr.h:2068    game::do_regular_action(action_id&, avatar&, std::optional<tripoint> const&)
  #34
    (dbghelp: @0x7ff78ff63454[cataclysm-tiles.exe+0x393454]), 
    (libbacktrace: game::handle_action()+0xa10@0x140393454),
    0x140393454    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/unique_ptr.h:2988    game::handle_action()
  #35
    (dbghelp: @0x7ff78fe578a1[cataclysm-tiles.exe+0x2878a1]), 
    (libbacktrace: do_turn()+0x608@0x1402878a1),
    0x1402878a1    src/string_formatter.h:543    do_turn()
  #36
    (dbghelp: @0x7ff791206621[cataclysm-tiles.exe+0x1636621]), 
    (libbacktrace: main+0x1f90@0x141636621),
    0x141636621    src/main.cpp:816    main
  #37
    (dbghelp: @0x7ff78fbd13ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: _tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #38
    (dbghelp: @0x7ff78fbd14c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #39
    (dbghelp: BaseThreadInitThunk+0x1d@0x7ffeda6726bd[KERNEL32.DLL+0x126bd]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #40
    (dbghelp: RtlUserThreadStart+0x28@0x7ffedb80a9f8[ntdll.dll+0x5a9f8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
```

**Comment by TheCourier6** [comment] 2023-03-23 04:48
Memorial Folder as requested.
[memorial.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11047058/memorial.zip)

**Comment by pjf** [comment] 2023-03-23 09:10
Potentially related to?:

- #64466

**Comment by Scrivener07** [comment] 2023-03-23 10:48
I have the same crash after killing a fat zombie on a new game.
![Untitled](https://user-images.githubusercontent.com/1912967/227180080-dd8cad0f-e56e-49f8-96bf-2685811bf77f.png)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11049847/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11049848/debug.log)
[America 2023.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11049862/America.2023.zip)

**Comment by Setmaster** [comment] 2023-03-23 12:23
> I have the same crash after killing a fat zombie on a new game. ![Untitled](https://user-images.githubusercontent.com/1912967/227180080-dd8cad0f-e56e-49f8-96bf-2685811bf77f.png) [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11049847/crash.log) [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11049848/debug.log) [America 2023.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11049862/America.2023.zip) [memorial.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11049885/memorial.zip)

Probably the same as CleverRaven/Cataclysm-DDA/issues/64466, isn't there an achievement for killing your first zombie?

**Comment by Wyghab** [comment] 2023-03-23 19:53
My game also crashes after gaining an achievment, in my case it is level 7 piercing. However I was able to circumvent the crash by first opening the achievment menu to allow past data to load, after that I could gain the achievement without crashing.

**Comment by anothersimulacrum** [comment] 2023-03-25 01:18
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed by anothersimulacrum** 2023-03-25 01:18 UTC
Labels: <Crash / Freeze>, (S4 - Invalid)
