### ISSUE TITLE
Installing a battery in any vehicle causes the charge to dissappear.

### ISSUE THREAD

**Issue by aapocalypseAArisen** [CleverRaven/Cataclysm-DDA#73868] opened 2024-05-17 03:46 UTC
### Describe the bug

Installing a car battery in vehicles cause the battery to be 0% charge upon installation. Even full condition batteries with no draining status.

### Attach save file

N/A

### Steps to reproduce

Loaded a new world. Used the debug menu to teleport to multiple cars and installed full condition, full charge car batteries in them. Upon installation the car batteries charge was 0%.

### Expected behavior

For batteries to maintain their charge upon installation.

### Screenshots

N/A

### Versions and configuration

2024-05-16-2203 build. Only added mod is stats through kills.

### Additional context

N/A

**Comment by IdleSol** [comment] 2024-05-17 08:43
Confirmed. The error is reproduced since game version [2024-05-16-1817](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-05-16-1817)

**Comment by osuphobia** [comment] 2024-05-17 10:22
Caused by #73805 
Should be fixed by #73860

**Comment by aapocalypseAArisen** [comment] 2024-05-17 15:07
Updated to latest experimental. Successfully installed a battery and maintained its charge.

**Closed** 2024-05-17 15:06 UTC
Labels: (S1 - Need confirmation)
