### ISSUE TITLE
Can't continue working on foodstuff project with 'use item/activate'.

### ISSUE THREAD

**Issue by Aism4n** [CleverRaven/Cataclysm-DDA#76654] opened 2024-09-25 05:42 UTC
### Describe the bug

If your cooking project stops for whatever reason, instead of continuing working on it using "use item/activate" character will try to eat it and fail it becouse its unedible yet. Have to put it on table/crafting spot to actually resume working on it.

### Attach save file

[Leto-trimmed.tar.gz](https://github.com/user-attachments/files/17125591/Leto-trimmed.tar.gz)

### Steps to reproduce

1. Start cooking project.
2. Stop cooking project before its finished.
3. 'Use item' and select cooking project item.
4. Character tries to bite it but refuses becouse its not finished yet.

### Expected behavior

My character continue working on project by using item in hands.

### Versions and configuration

Win 10
Tiles
Russian/English
Experimental: 78ebcd0

### Additional context

![image](https://github.com/user-attachments/assets/355de738-05e6-4ad9-9c4d-ec5ce55b2b54)

**Comment by RenechCDDA** [comment] 2024-09-25 05:45
Duplicate of #76414

**Closed by RenechCDDA** 2024-09-25 05:45 UTC
Labels: (S1 - Need confirmation)
