### ISSUE TITLE
Segfault on reloading sewing kit from ground

### ISSUE THREAD

**Issue by placeybordeaux** [CleverRaven/Cataclysm-DDA#42170] opened 2020-07-15 21:03 UTC
On commit 9f82fd3034cbbc4d4ce37ac934b9b984de99c4f2 I am seeing reliable seg faults if I try to reload a sewing kit from thread that is on the ground.

# Steps To Reproduce

1. Spawn a sewing kit
2. Unload sewing kit
3. Drop thread on ground
4. Reload sewing kit

# Expected behavior

The sewing kit is reloaded and game doesn't crash.

# Versions and configuration

```
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-4155-g9f82fd3034 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills]
]
```

# Additional context

crash.log
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-4155-g9f82fd3034
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x39) [0xe2ddf1]
    ./cataclysm-tiles() [0xe15873]
    ./cataclysm-tiles() [0xe1552c]
    /nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib/libc.so.6(+0x381c0) [0x7f877b5461c0]
    ./cataclysm-tiles(_ZNK4item8has_flagERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x31) [0x10255dd]
    ./cataclysm-tiles(_ZN17activity_handlers13reload_finishEP15player_activityP6player+0x120) [0xbdef1d]
    ./cataclysm-tiles(_ZNK13activity_type11call_finishEP15player_activityP6player+0x60) [0xc1857a]
    ./cataclysm-tiles(_ZN15player_activity7do_turnER6player+0x728) [0x15839aa]
    ./cataclysm-tiles(_ZN4game16process_activityEv+0x57) [0xf1afd5]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x297) [0xf19601]
    ./cataclysm-tiles(main+0x1058) [0x11dd058]
    /nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib/libc.so.6(__libc_start_main+0xeb) [0x7f877b531d8b]
    ./cataclysm-tiles(_start+0x2a) [0xb91d2a]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash(char const*, char const*)
    crash.cpp:?
    signal_handler(int)
    crash.cpp:?
    ??
    ??:0
    item::has_flag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    ??:?
    activity_handlers::reload_finish(player_activity*, player*)
    ??:?
    activity_type::call_finish(player_activity*, player*) const
    ??:?
    player_activity::do_turn(player&)
    ??:?
    game::process_activity()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    /build/glibc-2.30/csu/../sysdeps/x86_64/start.S:122
```

**Comment by anothersimulacrum** [comment] 2020-07-15 21:33
Duplicate of #42089

**Closed by anothersimulacrum** 2020-07-15 21:33 UTC
