### ISSUE TITLE
[0.H] dino dave questline finale error, his cardboard castle has no roof

### ISSUE THREAD

**Issue by LarnellThePureDangerous** [CleverRaven/Cataclysm-DDA#76521] opened 2024-09-18 14:40 UTC
### Describe the bug

in the end of the dino dave's questline, he went to the top floor of the evac center, built there his cardboard castle and started living in there as a lookout. but because of a bug (lacking overmap data), the finale process gave me an error message and his castle has no roof.

### Attach save file

[[0.H][debug]dave_s_castle.zip](https://github.com/user-attachments/files/17045723/0.H.debug.dave_s_castle.zip)

### Steps to reproduce

1. give everything dave wants to finish his questline
2. talk to smokes to get a permission to make dave's cardboard castle on the evac center
3. talk to dave about the permission

### Expected behavior

dave's castle should have a nice cardboard roof. i can't leave this guy under the rainy skies. you also can't, can you?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: 293c761 [64-bit]
- Graphics Version: Tiles
- Game Language: Japanese
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

actually, in json (data\jason\npcs\refugee_center\beggars\BEGGAR_2_Dino_Dave/json), there's
        { "mapgen_update": "cardboard_castle_1_roof", "om_terrain": "evac_center_13_z2" },
and its mapgen data. only "evac_center_13_z2" is missing. thining by its name, it should be Z2 level, "a roof" of the topfloor of the center. the topfloor itself already has a roof technically by floor tiles with roof, but there's no overmap tile "evac_center_13_z2".
and as far as i know, in 0.G there's no this bug. in 0.G, there's "evac_center_13_z2", surely. somehow it has been deleted from 0.H.

here's the error log:
 DEBUG    : Unable to find and assign mission target evac_center_13_z2.

 FUNCTION : std::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&, dialogue&)
 FILE     : src/mission_util.cpp
 LINE     : 258
 VERSION  : 293c761

**Comment by harakka** [comment] 2024-09-18 15:25
Duplicate of #69193

**Closed by harakka** 2024-09-18 15:25 UTC
Labels: (S1 - Need confirmation)
