### ISSUE TITLE
[Android(Experimental)] the joystick gets stuck on one direction and you will lose control of the characters direction

### ISSUE THREAD

**Issue by Mybachhertz** [CleverRaven/Cataclysm-DDA#41678] opened 2020-06-29 15:43 UTC
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-06-29 20:41
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/41557

**Closed by ZhilkinSerg** 2020-06-29 20:41 UTC
