### ISSUE TITLE
Generating map without cities bugged

### ISSUE THREAD

**Issue by ZemZamano** [CleverRaven/Cataclysm-DDA#22990] opened 2018-02-19 13:26 UTC
Game version:
0.C-26299-g50f4a11
Operating system:
win7
Tiles or curses:

Mods active:
default mods only
### Expected behavior
when city size is set to zero, the mapgen should create a map without roads and cities
### Actual behavior
when city size is set to zero, all buildings and sites are disabled. this includes POIs that should be able to spawn like caves, anthills, triffid groves etc.
### Steps to reproduce the behavior
create a new world and set city size to 0. use debug to reveal map

**Comment by Leland** [comment] 2018-02-19 16:06
Duplicate of #22827

**Closed by Leland** 2018-02-19 16:06 UTC
