### ISSUE TITLE
Segmentation Fault on Item Filter Screen v. 0.D-4913-g275d8a7

### ISSUE THREAD

**Issue by Voideka** [CleverRaven/Cataclysm-DDA#31790] opened 2019-06-24 03:26 UTC
# Describe the bug

Pressing 'Enter' on the item filter screen with no results causes a segmentation fault.

# Steps To Reproduce

1. Open a filterable list such as the (R)ead screen.
2. Press '/' to open the filter dialog.
3. Input a string that will return 0 results, such as 'asdasdas'.
4. Press 'Enter' to submit.
5. On the resultant screen (see attached screenshot) press 'Enter' again.

# Expected behavior

Nothing should happen, and game should not crash

# Screenshots

![catafilter](https://user-images.githubusercontent.com/2141044/59989546-aea06800-960d-11e9-80c2-b779a083772f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4913-g275d8a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod]
]

# Additional context

Initial error dialog:
---------------------------
MinGW Runtime Assertion
---------------------------
Assertion failed!

Program: C:\Games\cataclysmdda\cataclysm-tiles.exe
File: src/inventory_ui.h, Line 101

Expression: !locations.empty()
---------------------------
Abort   Retry   Ignore   
---------------------------

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3319090/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3319091/debug.log)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3319092/save.zip)

Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/issues/31771

**Comment by AMurkin** [comment] 2019-07-14 18:34
Cannot reproduce. Should be fixed by #32324.

**Comment by ifreund** [comment] 2019-07-17 11:40
Closing as it seems this has been fixed.  If you can reproduces this feel free to ping me to reopen.

**Closed by ifreund** 2019-07-17 11:40 UTC
Labels: (S2 - Confirmed), <Crash / Freeze>
