### ISSUE TITLE
NPC training Brawling trains previous skill trained

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20566] opened 2017-03-16 15:31 UTC
If an NPC offers Brawling as training, and the Player takes something else, then the next time training is offered, if Brawling is chosen, it doesn't train brawling, it trains the previous skill requested, even if it goes beyond the NPC's knowledge.

**Comment by codemime** [comment] 2017-03-17 19:16
Dupe of #18642.

**Closed by codemime** 2017-03-17 19:16 UTC
