### ISSUE TITLE
Json errors no longer being displayed (curses)

### ISSUE THREAD

**Issue by Wad67** [CleverRaven/Cataclysm-DDA#20678] opened 2017-03-26 17:39 UTC
Forgive me if this is a duplicate issue, or is already known in some way.

To reproduce, write a json mod that is bugged in some way.
Expected behavior: error message pertaining to bugged json file
Actual behavior: game hangs for a moment, then returns to title screen

This may be related to #20649

**Comment by codemime** [comment] 2017-03-26 17:41
Could you write an example?

**Comment by Wad67** [comment] 2017-03-26 17:44
Fairly sure this is the bugged piece of code, although I have no way of telling due to aforementioned issue. 


[ 
 {
    "id": "tank_500ml",
    "type": "vehicle_part",
    "name": "vehicle tank (500ml)",
    "item": "bottle_plastic",
    "location": "fuel_source",
    "symbol": "O",
    "broken_color": "red",
    "difficulty": 1,
    "durability": 75,
    "size": 500,
    "damage_modifier": 80,
    "breaks_into": [
      { "item": "plastic_chunk", "count": [ 2, 5 ] }
    ],
	"extend": { "flags": [ "FOLDABLE", "TOOL_SCREWDRIVER" ] }
  },
  ]

**Comment by codemime** [comment] 2017-03-26 17:53
It worked as expected for me (I got the error). What's your OS?

**Comment by Wad67** [comment] 2017-03-26 17:57
Windows 7 Ultimate x64.

**Comment by Wad67** [comment] 2017-03-26 17:58
It may be that I'm compiling with codeblocks, and there is a flag that needs to be changed.

**Comment by Wad67** [comment] 2017-03-26 18:04
http://imgur.com/a/CD1HR

**Comment by BorkBorkGoesTheCode** [comment] 2017-03-27 05:01
#20061 and #20107 probably share the same cause.

**Comment by pisskop** [comment] 2017-03-27 11:13
They definitely show up in my linux builds for mods.

**Comment by Wad67** [comment] 2017-03-27 21:10
Just took the time to test this in linux also, both SDL and CURSES render the debugmsg just fine. 

So that narrows the problem down to something related to the windows CURSES build.

**Comment by Leland** [comment] 2017-05-08 03:40
Duplicate of #20061. Thanks for taking the time to test this out, copying over your notes to the main thread.

**Closed by Leland** 2017-05-08 03:40 UTC
Labels: Bug, Confirmation Needed, JSON, Windows
