### ISSUE TITLE
Repeatedly talking to an aggressive NPC and dropping weapon can help with negotiations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17681] opened 2016-07-14 08:45 UTC
- Spawn an aggressive, non-hostile NPC (kinda hard to force without an opinion editor). Can be a mugger
- Wield an item
- Talk to NPC
- Drop the weapon
- Keep talking and dropping
- Notice persuasion chance increasing due to NPC fearing you less every time you agree to drop the weapon

**Comment by Maleclypse** [comment] 2021-06-30 16:04
@Night-Pryanik I think I remember you fixing this in a PR that isn't linked to this issue?   I apologize if I'm remembering incorrectly.

**Comment by Maleclypse** [comment] 2021-12-12 20:04
@wapcaplet I'm pretty certain this bug doesn't exist anymore.   I tested by spawning in npcs and dropping weapons.  I didn't see any increase in my chance to persuade after dropping weapon any time I tried and if I picked up my weapon after dropping it they instantly went hostile.  If you have a moment to check this as well I think we can close it.

**Comment by wapcaplet** [comment] 2021-12-12 21:03
@Maleclypse Agreed, I can't reproduce this either. My wielded weapon does influence my chance of intimidation, as expected, but dropping and re-wielding it doesn't accumulate influence or anything.

Wielding an M4 (and with no other qualifications), my intimidation factor is 25% / 15%:

![image](https://user-images.githubusercontent.com/238395/145729368-e8933cba-2185-4332-bf13-6a9cb99ed174.png)

Wielding only a combat knife, it is 15% / 5%:

![image](https://user-images.githubusercontent.com/238395/145729394-1f797ec1-da03-4aac-8d7f-c32ca6dae166.png)

And wielding nothing, it drops to 10% / 0%:

![image](https://user-images.githubusercontent.com/238395/145729414-970341d8-699a-4af4-8d0a-01c9d5948a27.png)

If I get completely naked, I manage to somehow retain enough dignity to be 5% intimidating:

![image](https://user-images.githubusercontent.com/238395/145729441-b26a804a-57a2-4a09-bd8b-ff913db8d4f7.png)

I think this is working as intended. Closing issue.

**Closed** 2021-12-12 21:05 UTC
Labels: NPC / Factions, <Exploit>
