### ISSUE TITLE
'Bright' level of lighting everywhere, even during the night.

### ISSUE THREAD

**Issue by RosieMcCattail** [CleverRaven/Cataclysm-DDA#30732] opened 2019-05-21 19:10 UTC
During the night the ground level of the world has 'bright' lighting everywhere, regardless of conditions. Closed rooms, insides of houses, vehicles - doesn't matter. You can read, craft, etc.

The dungeons are very dark, as expected.

1. ????
2. No idea. Can send you the world if needed.

_Important notice_: After reloading the save made during the night, light levels are reset to normal. Maybe the light somehow sticks and doesn't refresh itself?

Expected behavior

Cloudy or such during the full moon, very dark during new moon, and so on. You know how it works IRL, come on.

![2760](https://user-images.githubusercontent.com/43783725/58123631-8f787a00-7c0c-11e9-87df-5fdbf6723c85.png)

- OS: Windows [32-bit] ## No idea why it says so - my Windows 7 is certainly 64 bit.
- Game Version: 0.D-3258-ge89a6cc
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by RosieMcCattail** [comment] 2019-05-21 19:19
This also happens during the day, and yes, all the other tiles are also marked as bright.

![2761](https://user-images.githubusercontent.com/43783725/58124231-082c0600-7c0e-11e9-898a-dfdec7dd5c6a.png)
![2762](https://user-images.githubusercontent.com/43783725/58124237-0b26f680-7c0e-11e9-84c5-d4d3a8487bb4.png)

**Comment by neitsa** [comment] 2019-05-22 16:02
> Windows [32-bit] ## No idea why it says so - my Windows 7 is certainly 64 bit.

Actually you're running the game on the WOW64 subsystem of Windows (which is technically the 32-bit layer of the 64-bit OS). Put simply, you're running the 32-bit version of the game (hence 32-bit).

**Comment by RosieMcCattail** [comment] 2019-05-22 17:30
Is this the reason for this bug? How do I fix it anyway?

**Comment by JIGorki** [comment] 2019-05-23 15:49
I have expirienced similar issue. From what I have observed, all lilnoleum tiles are fully bright - even in rooms that are half liloleum half wooden linoleum part likes to be fully bright during the day (all windows, doors and other sources of light closed)

**Comment by molkero** [comment] 2019-05-24 08:41
Came back to my sealed base mid-day, every tile is bright. After save & reload lighting seems to work.

**Comment by kevingranade** [comment] 2019-05-25 00:31
Thanks for that detail, that makes me think it needs handling in the map shift code.

**Comment by molkero** [comment] 2019-05-25 01:22
Tested a bit more, seems like the lighting works in the reality bubble you start in, once you leave it you have to save & reload to fix it again. Haven't tested z-levels yet, gonna find a lab next.

**Comment by molkero** [comment] 2019-05-25 03:59
Not sure about z-levels, felt like without the save & reload zombies could see too well, no change in visible light though.

**Comment by Zombiemanpig** [comment] 2019-06-01 16:32
I am having the same issue happening, when I quit and reload it was fixed but it seems to happen when you move a long distance away from the spot you started in when you first loaded in.

**Comment by SleeperJack** [comment] 2019-06-26 22:06
Reporting similar issue with night time brightness. I had a lightning storm which caused bright lighting during the entire night the day before, but it happened again during a snowstorm the next day. Not sure if weather related. It was very dark before I moved to a trailer park then turned to bright. Additionally, I am having opaque issues on walls (first with a science lab facility now with more buildings as well).

**Comment by anothersimulacrum** [comment] 2019-09-15 00:55
I cannot reproduce this, is this still an issue?
![image](https://user-images.githubusercontent.com/42699974/64915313-83806d00-d753-11e9-8d42-07f899ff8583.png)

**Comment by ZhilkinSerg** [comment] 2019-10-08 09:03
Possibly duplicate of #34451

**Closed by ZhilkinSerg** 2019-10-08 09:03 UTC
Labels: (S2 - Confirmed), <Bug>
