### ISSUE TITLE
crash: viewing ; far away objects

### ISSUE THREAD

**Issue by FONZACUS** [CleverRaven/Cataclysm-DDA#28410] opened 2019-02-27 20:40 UTC
**Describe the bug**  
theres a crash when viewing very far away objects

**To Reproduce**  
1. semicolon far away beyond the greyed area.

**Expected behavior**  
not crashing, my archive version 8530 didnt crash when scanning the area.

**Screenshots**  
none

**Versions and configuration(please complete the following information):**
 - OS: win10 x64 playing on tiles x32
 - Game Version: 8549
 - Graphics version: tiles
 - Mods loaded: default

**Additional context**  
.core file in root cdda directory.
https://gist.github.com/FONZACUS/0743de83dc2da578ba521ae6ea20bcc3
crash.log file.
```
CRASH LOG FILE: config/crash.log
VERSION: 0.C-37537-g712d7b0
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x54BEF0[cataclysm-tiles.exe+0x14BEF0]
    @0x54C291[cataclysm-tiles.exe+0x14C291]
    SMPEG_error+0x3DAF3@0xB9E095[cataclysm-tiles.exe+0x79E095]
    UnhandledExceptionFilter+0x1A0@0x74E15F10[KERNELBASE.dll+0x195F10]
    RtlCaptureStackContext+0x1E521@0x77E3DA71[ntdll.dll+0x9DA71]
    RtlAreBitsSet+0x58@0x77E04198[ntdll.dll+0x64198]
```

**Comment by DSeyka** [comment] 2019-02-27 22:12
Same here. Steps to reproduce: start playing, press ; or x, then just keep pressing any single direction key for a while. It then crashes within few seconds.
![image](https://user-images.githubusercontent.com/34726992/53526294-dadf2880-3af4-11e9-9ed5-9dd0119f13fe.png)

**Comment by kevingranade** [comment] 2019-02-28 03:31
Couldn't reproduce on curses, I'll see if I can reproduce on tiles.

**Comment by SwagNaut** [comment] 2019-02-28 04:01
I can't reproduce this, not even with the steps @DSeyka provided. However, a friend of mine is experiencing it aswell. The bug may only appear under certain conditions.

**Comment by kevingranade** [comment] 2019-02-28 04:19
I did notice while scrolling around the lighting indicator occasionally changed, suggesting that the menu code is reading something it shouldn't.

**Comment by kevingranade** [comment] 2019-02-28 05:29
game::print_all_tile_info seems like q solid candidate for accessing memory without proper bounds checking.

**Comment by DSeyka** [comment] 2019-02-28 05:34
Could reproduce it on curses as well, no error message, just crashes silently.  
Here's a savefile. Load it up, press x, then hold down left. It SHOULD crash at ~67 tiles from initial position.  
https://ufile.io/3hx1r

**Comment by kevingranade** [comment] 2019-03-01 07:30
Can't reproduce here, but I have something to try, I'll post a PR.

**Comment by DSeyka** [comment] 2019-03-01 15:15
Thanks. Since I'm not seeing the lighting indicator bugging out, it's a good chance that's when it crashes for me. Dunno why it doesn't for you, might be platform specific (I'm on Win10). Will check out your fix as soon as it's merged.

**Closed** 2019-03-02 21:58 UTC
Labels: <Crash / Freeze>

**Comment by DSeyka** [comment] 2019-03-03 01:20
Can confirm it's fixed in 8556.

**Comment by ZhilkinSerg** [comment] 2019-03-03 07:30
Good to know. Thanks for confirmation.

**Comment by FONZACUS** [comment] 2019-03-03 15:49
thanks as well, works just fine running 8559. must be another wandows thing.
