### ISSUE TITLE
keybind keeps resetting

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#58402] opened 2022-06-13 16:21 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/71761521/173398095-141810e1-1fc7-429d-aeee-18ee7f5025da.png)
the examine  nearby terrain or furniture keeps resetting itself every launch, overriding the other keybind in the picture and effectively disabling it 

### Steps to reproduce

open game 
change the examine terrain or furniture keybind, save, reopen game and see that it is the same as before you changed it

### Expected behavior

to not override player's choice of keybinds

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 07ed0a7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

### Additional context

i couldnt provide a zip of my game, github says its too big, even though i excluded gfx, sound, and save

**Comment by ZeroInternalReflection** [comment] 2022-06-13 16:33
I have not been able to reproduce this on:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 51e8603 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

Typically, when there is a request for an upload, what would be of interest is the particular save where it occurs, rather than a zip of your entire game folder.  So if you have cataclysmdda-0.F/save/[World name], a zip file of the [World name] folder would be what to upload.  However, I believe custom keybindings are only stored in config/keybindings.json, so the save file probably isn't relevant here.
If you set a custom keybinding and then save, does config/keybindings.json change?

**Comment by Devengel** [comment] 2022-06-13 17:10
"If you set a custom keybinding and then save, does config/keybindings.json change?"
yeah

**Comment by NetSysFire** [comment] 2022-06-13 17:36
There are global and local keybindings. How do you test? If you create a new world to test, it will reset when you use a local keybinding. Use global ones to make them persist.

**Comment by ZeroInternalReflection** [comment] 2022-06-13 18:01
> "If you set a custom keybinding and then save, does config/keybindings.json change?" yeah

Could you upload your config/keybindings.json?  There might be some quirk there that's corrupting things, causing the game to reset to default keybindings.

> There are global and local keybindings. How do you test? If you create a new world to test, it will reset when you use a local keybinding. Use global ones to make them persist.

This is getting outside of my knowledge of the codebase, but my understanding is that that:
1. A 'local' keybinding is set for that input context (typically that UI screen, but there are some quirks)
2. A 'global' keybinding is set for all input contexts
3. Neither type is save-specific
When I set a local keybinding in one world, then open a save on a different world, that same custom keybinding is still in place.

**Comment by NetSysFire** [comment] 2022-06-13 18:08
>Neither type is save-specific

Huh? I might be wrong. Forget I said anything. Sorry for confusing everyone.

>There might be some quirk there that's corrupting things,

No idea how it works on windows, but I would potentially clear out the entire configuration directory, back it up before you do that of course, and try again. If it starts to work correctly, the issue is somewhere in there and you can start restoring file by file. But a good start is to upload your keybind config, yeah.

**Comment by Devengel** [comment] 2022-06-14 00:25
[keybindings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8895282/keybindings.zip)

**Comment by Devengel** [comment] 2022-06-14 13:12
it appears the issue is with game launchers, specifically catapult, i use remroy's (maintained version) launcher now and the issue no longer happens

**Comment by anothersimulacrum** [comment] 2022-06-14 15:16
Closing, then.

**Closed by anothersimulacrum** 2022-06-14 15:16 UTC
Labels: (S1 - Need confirmation)
