### ISSUE TITLE
NPC gave quest twice, crashed game

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28660] opened 2019-03-12 12:28 UTC
**Describe the bug**  
Infected starting NPC. Said I would help him. Asked for stuff, pressed Shift S, rest can be seen in picture.

**To Reproduce**  
I guess start games till you find an infected starting static NPC and then do the same order of things I did.
https://i.imgur.com/LREOQMa.png

**Expected behavior**  
To not crash to desktop.

**Screenshots**  
https://i.imgur.com/LREOQMa.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 3601
 - Graphics version: Tiles
 - Mods loaded: dda, mutant NPCs is the only  NPC mod I am running

P.S, why was the comments that were the most upvoted comments in the release for 0.D get deleted? What release is even considered the stable release? I go to the site and there is still Cooper to download and no Dick. There is this Danny changelog but it is no Dick Stable Release.

**Comment by int-ua** [comment] 2019-03-12 13:14
Duplicate of #28622 ?

**Closed** 2019-03-12 13:58 UTC
