### ISSUE TITLE
Portal Storm Teleports Player Ahead of Moving Vehicle Without Warning Prompt or Any Messaging

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54465] opened 2022-01-16 00:10 UTC
### Describe the bug

Never saw this before today however, while driving I've repeatedly had my character thrown about 10-15 squares in front of my vehicle while driving in a portal storm. There is no prompt or warning (unlike the time-reverse one, which can also throw player out of vehicle) however this could potentially kill a player almost instantly, because the car is still moving and will hit them, without much time to dodge.

In the screenshots provided, I was thrown out of my car and re-entered it, then 3-4 minutes later in-game I was teleported forward again and then hit by the car, then tried to move out of the way and was hit again before being pushed aside. Full health to having every limb nearly broken, as well as a number of pieces of armor and weapon which were destroyed.

The fact that there's no warning or any message at all in the log means that a player who's driving in a line hitting Num5 repeatedly, may likely end up badly injured and breaking a bunch of gear before they could react. FWIW, I haven't seen the time-reverse happen since this began occurring.

### Steps to reproduce

1. Start portal storm.
2. Drive around.
3. Observe character moved ahead of moving car with no prompt.
4. Try to dodge away in time.

### Expected behavior

Expected some kind of warning prompt, and possibly not moving the  character ahead in path of vehicle every time.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149642062-79b2bb13-19f7-4344-a737-d87c2ec52ea4.png)
![image](https://user-images.githubusercontent.com/80022377/149642121-b21513e6-b356-4709-89f6-652e5c1f6831.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LeahLuong** [comment] 2022-01-16 02:37
I believe portal storms have a random blink effect that can happen from time to time. This has been mentioned before (in #52475) & it sounds like it's being worked on. There's also a random incorporeality effect; imagine dropping out of your vehicle to watch it crash itself to a stop!

Remember, kids: don't portal storm & drive! @ least for now.

**Comment by NetSysFire** [comment] 2022-01-16 02:49
They have, but it should have already been fixed by #54121

**Comment by LeahLuong** [comment] 2022-01-16 02:52
You going to @ or should I??

**Comment by coyo7e** [comment] 2022-01-16 05:24
Could have been intensely bad luck however I didn't make it entirely clear that both times I was thrown in a line directly in front of my position. The first time I was moving a little slowly because I'd been luring some zeds into a bee, the second time I was doing 25mph or 30mph. Having it blink me in the same position twice was the weirdest thing - also all the doors and stuff were closed so technically I was indoors and shoulda been immune as I understand yeah. ;)

**Comment by hexagonrecursion** [comment] 2022-01-16 06:53
I can't find any mention of a random blink effect in [portal_storm_effect_on_condition.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/c4641916f549a59a4e237423929819aef7d6b8e8/data/json/portal_storm_effect_on_condition.json). EOC_PORTAL_TELEPORT_STUCK_START always prints "This moment feels thick as if its not quite over" and EOC_PORTAL_TELEPORT_STUCK always prints "You feel as if you just rewound a few seconds"

I do not know what happened to you.

Note: you can get portal storm effects while inside a car if the roof of the car is destroyed.

**Comment by coyo7e** [comment] 2022-01-16 08:42
I know about the busted roof thing. The roof was not busted check screenshot.

**Comment by hexagonrecursion** [comment] 2022-01-16 08:49
> check screenshot

It is not actually possible to tell visually - you have to [e]xamine the car. This car has no roof above the driver's seat.

![DeepinScreenshot_select-area_20220116114728](https://user-images.githubusercontent.com/52621858/149653309-d818a2a8-b86b-482e-8cea-70c67f261b01.png)

**Comment by hexagonrecursion** [comment] 2022-01-16 08:50
I wonder: could the portal storm be a coincidence? I would be very surprised if this was the only mechanic in the game that can cause you to teleport. Can artifacts teleport the player?

**Comment by coyo7e** [comment] 2022-01-19 06:19
It looks like a message was added to the teleport effect during portal storm however it's still occurring while in a closed vehicle with no broken roof or panels/doors. It now says "For a moment a hole in reality opens and you can see your own back."

There's also a new teleport where it throws you a ways and then spawns in enemies at the same time.. In the second screenshot I was picking up items from a crate and teleported with enemies spawning in at the same time, but continued the pickup action and got hit a couple times before I could do anything so they had plenty of time to move up to me and hit me more than once.

![image](https://user-images.githubusercontent.com/80022377/150074941-b9b64402-43b5-4402-9e39-f945406b7f79.png)

![image](https://user-images.githubusercontent.com/80022377/150074988-79499c5a-70a2-46a9-b519-79a19eb64902.png)

**Comment by Ramza13** [comment] 2022-01-19 07:29
> It looks like a message was added to the teleport effect during portal storm however it's still occurring while in a closed vehicle with no broken roof or panels/doors - I was sitting in a stationary vehicle eating and suddenly bamf, I'm 15 or so squares away and then finished eating. It said "For a moment a hole in reality opens and you can see your own back."
> 
> ![image](https://user-images.githubusercontent.com/80022377/150074941-b9b64402-43b5-4402-9e39-f945406b7f79.png)

Actually that message is unrelated to the teleport, which seems to be a bug as its not a known portal storm effect.  

Hmmmm did you see any patches of alien grass?  I have a hunch its related to undoing those based on some code I wrote to preform long distance modifications.  Will investigate.

**Comment by coyo7e** [comment] 2022-01-19 09:07
Nope I don't recall any alien grass nearby, but I had just drove over a bridge and then stopped driving to eat when it happened, so maybe there wasn't anywhere for the grass to spawn if it had tried.

**Comment by Ramza13** [comment] 2022-01-19 20:24
> Nope I don't recall any alien grass nearby, but I had just drove over a bridge and then stopped driving to eat when it happened, so maybe there wasn't anywhere for the grass to spawn if it had tried.
> 
> Sorry to be a pest about this stuff, I'm not like, upset or anything, just trying to bring up stuff when I notice it. ;)

You aren't a pest at all.  This is vital info that I am pretty sure has helped me start tracking down an issue I had a vague idea might exist and which probably will appear in more than just this location.

**Comment by coyo7e** [comment] 2022-01-20 16:40
I don't see any eye, no idea what you're talking about tbh. It's a log pull.

And no, I haven't seen a flaming eye in this entire run, nor gone into any labs.

**Comment by AcidAntOnAMinefield** [comment] 2022-01-20 16:43
> I don't see any eye, no idea what you're talking about tbh. It's a log pull. There are no status effects visible.
> 
> And no, I haven't seen a flaming eye in this entire run, nor gone into any labs.

https://user-images.githubusercontent.com/80022377/149642121-b21513e6-b356-4709-89f6-652e5c1f6831.png
Was referring to this one, but upon using a better monitor i see that's the blinker, not an icon as it first seemed to be, so disregard that.

**Comment by Ramza13** [comment] 2022-01-20 16:44
So this is caused by the game undoing the alien grass and in the process accidently moving you.  I've got a fix submitted.

**Closed** 2022-01-20 18:26 UTC
Labels: Info / User Interface, (S1 - Need confirmation), Mechanics: Weather

**Comment by kevingranade** [comment] 2022-03-11 00:54
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/portal-storms-tweaks-for-early-vs-late-game/27671/3
