### ISSUE TITLE
Ability to jump off of roof without adjacent roof 1 tile away

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42401] opened 2020-07-23 07:22 UTC
# Is your feature request related to a problem? Please describe.
Wanted to jump off the prison roof into deep water. the deep water was 1 tile away from the roof. The current jump only lets you try if there's something else to jump onto 1 tile away. 

# Describe the solution you'd like
The ability to make my own mistakes if i want :P If I can jump 1 tile length onto another stable footing, i feel like i should also be able to jump 1 tile away and fall at my own peril (idk if anything breaks fall damage yet) 

# Describe alternatives you've considered
None. I'm open to suggestions and discussion about it though.

**Comment by Hulkninja** [comment] 2020-07-23 12:00
I think the whole system of "jumping" eventually needs to be expanded upon.
Weight carried as well as dexterity and move speed should factor into maximum jump distance.

This is probably a pretty complicated thing to implement properly.

**Comment by ZhilkinSerg** [comment] 2020-07-23 17:19
Just move into open air.

**Comment by Hulkninja** [comment] 2020-07-23 17:55
> Just move into open air.

I think they means there's a 1 tile gap between the roof and the water, so they wants to jump OVER that gap, into water. I could be wrong.

**Comment by NotHereCDDA** [comment] 2020-07-23 19:33
Yes Hulkninja, you are correct.

**Comment by ZhilkinSerg** [comment] 2020-07-23 20:12
Existing command is specifically for jumping over ledges, not jumping down the roof. It should be expanded to allow free jumps. You can add more thoughts here - #28564

**Comment by ZhilkinSerg** [comment] 2020-07-23 20:12
Duplicate of #28564

**Closed by ZhilkinSerg** 2020-07-23 20:12 UTC
Labels: <Suggestion / Discussion>
