### ISSUE TITLE
When log is prompting that Player finds themselves no longer grabbed, an NPC companion is named instead

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#59440] opened 2022-07-20 10:07 UTC
### Describe the bug

While fighting a zombie and tough zombie two in different fights, I got grabbed in both. 

When the message which is supposed to say "You find yourself no longer grabbed" was printed in the log, it instead said "Gene Fernandez finds themselves no longer grabbed", I immediately ran to my npc thinking that my car got broken into and that they were fighting the offender.

However on reaching them, I found that there was no zombie to be seen and my car is doing just fine, I checked the logs and found the bug.

When near an NPC, the message claims that they were instead freed from a grab.

Also in the 2nd screenshot, you will see that the last message "You break out of the grab!" is printed just fine.

### Steps to reproduce

1. Have a recruited NPC follower. Set them to not attack unless you do and to not use ranged weapons (probably not related by these are the only settings I changed for combat)
2. Have this NPC on guard.
3. Fight a zombie and tough zombie
4. The game should claim the NPC finds themselves no longer grabbed.

### Expected behavior

I'm the one doing the fighting, why are they getting the credit lol

### Screenshots

For the normal zombie
![image](https://user-images.githubusercontent.com/88375697/179952462-92bd232c-cda3-4d24-b05e-105186011cf9.png)

For the tough zombie as well
![image](https://user-images.githubusercontent.com/88375697/179952664-1025fc5e-ba47-4782-9818-f8a52cfa7fd2.png)

My NPC and 2 pet ravens just chilling. Don't mind that one dead zombie, it was there before the fights where this bug happened.
![image](https://user-images.githubusercontent.com/88375697/179954375-4fe75352-38e4-4d1e-a870-3215d8389698.png)

Probably overdoing it but here is a screenshot of the zombies I fought and I've drawn a double arrow on the minimap to show how far away I was from the NPC who got named
![image](https://user-images.githubusercontent.com/88375697/179955429-f45b80ed-ce17-4fad-b640-c993046fa926.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: ae2ff5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Save file:
[Parthenon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9148711/Parthenon.zip)

**Comment by Cimanyd0** [comment] 2022-07-20 16:56
I've been seeing this bug for a while too.

It's not supposed to be "You find yourself no longer grabbed."  In both my case and your screenshots, the message appears when you are first grabbed, and the zombie is still grabbing you. It's like the game is telling you that you have been grabbed but your NPC hasn't.

My NPC is not on guard.

**Comment by hexagonrecursion** [comment] 2022-07-21 05:16
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 75e3982 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment] 2022-07-30 14:47
In this code snippet https://github.com/CleverRaven/Cataclysm-DDA/blob/3b41d64d2ff6b7add5c85abf314002fb0434f366/src/character.cpp#L11445-L11448
I temporarily commented out `try_remove_grab` part. And I found out that when zombie grabs me, `grabbed` effect for some weird reason is applied not only to me, but to my NPC follower too:
![4334634636](https://user-images.githubusercontent.com/11132525/181919354-30939cd7-e37d-40f0-8cb2-62d68520f7db.png)

And game says `NPC finds themselves no longer grabbed.` because after this remote grabbing NPC executes `try_remove_grab`, and since there is no grabbing monsters next to him, `grabbed` effect is automatically removed.

**Comment by Night-Pryanik** [comment] 2022-10-28 20:20
I guess this is the same as #54608.

**Comment by Night-Pryanik** [comment] 2024-10-21 16:53
Closing as duplicate.

**Closed by Night-Pryanik** 2024-10-21 16:53 UTC
Labels: (S2 - Confirmed)
