### ISSUE TITLE
Unable to create new vehicle construction

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#18900] opened 2016-10-19 17:44 UTC
Build: 5731

//////////////////////////////////////////////////////////////////////////
Error Debug message: "Attempted a recipte with no available components!"

Function: "comp_selection<item_comp> player::select_item_component(const std::vector<item_comp>&, int, inventory&, bool)"

File: "src/crafting.cpp"

Line: "825"
//////////////////////////////////////////////////////////////////////////

When does this issue occur? Whenever I try and create a new vehicle with either light or normal wooden frames. (Only ones I've tested so far)

**Comment by illi-kun** [comment] 2016-10-19 17:53
Try it again with two identical frames in inventory.

**Comment by harald921** [comment] 2016-10-19 18:02
That worked, but used up both frames. Miscalulated vector iteration?

**Comment by illi-kun** [comment] 2016-10-19 18:03
I dunno, but that's duplicate of  #18372.

**Closed** 2016-10-19 18:24 UTC
Labels: Bug, Duplicate
