### ISSUE TITLE
Old saves removed and can't start new games. Game crashes.

### ISSUE THREAD

**Issue by systemfelet** [CleverRaven/Cataclysm-DDA#42336] opened 2020-07-21 11:10 UTC
After updating to build #10858 I couldn't load my old saves, so I tried to force update the game from the launcher. The update then crashed and upon starting the launcher again I had to install the game from scratch (all files where still there in the folder though). Before doing so I copied the save folder just in case. 

After the new "install" the saves are no longer there nor can I create a new character. I'll post the error message here:

11:47:03.658 ERROR : src/main_menu.cpp:1159 [bool main_menu::load_character_tab(bool)] Error: data/mods//dda/../../json/mapgen_palettes/house_general_palette.json: line 73:13: duplicate entry in json object

      "Ø": "f_pinball_machine",
      "Æ": "f_arcade_machine",
      "∞":
            ^
             "f_foot_locker",
      "≠": "f_chest",
      "ʭ": "f_ladder"

And for new char it's pretty much the same:

src/main_menu.cpp:874 [bool main_menu::new_character_tab()] Error: data/mods//dda/../../json/mapgen_palettes/house_general_palette.json: line 73:13: duplicate entry in json object

      "Ø": "f_pinball_machine",
      "Æ": "f_arcade_machine",
      "∞":
            ^
             "f_foot_locker",
      "≠": "f_chest",
      "ʭ": "f_ladder"

I've uploaded the crash and debug files + save file.

Have a friend who's way better in programming and we did try to alter the json file "house_general_palette" and removing the lines which caused the errors thinking it could be something to do with Swedish letters (å, ä, ö) or such but that didn't solve anything =/.

We copied the lines from his file and replaced mine with them but it didn't work either.

# Versions and configuration
Can't generate a game report since I can't load into the game sadly.

 - OS:  Windows 10 
 - Game Version: 0.E-4328-g42ca94c
 - Graphics version: Tiles (MSX++UnDeadPeopleEdition)
 - Ingame language: English
 - Mods loaded: dda, StatsThroughSkills, No Rail Stations, Disable NPC Needs, SpeedyDex, Alternative Map Key

And my files I've uploaded:

[Systemerror.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4953069/Systemerror.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4953060/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4953061/debug.log)

Edit: Reinstalled the game launcher and updated to the  later Build #10859 but get the same errors still.

**Comment by esavier** [comment] 2020-07-21 12:05
linux (terminal) build from versioned 0.E-4303-g213691562c already allows to start new game, but i am not sure you will be able to recover the save

**Comment by AMurkin** [comment] 2020-07-21 12:15
0.E-4328-g42ca94c is a build #10859.
It's the first affected build.

**Comment by ZhilkinSerg** [comment] 2020-07-21 12:59
Duplicate of #42334

**Closed by ZhilkinSerg** 2020-07-21 12:59 UTC
