### ISSUE TITLE
Activating any item not in inventory may crash the game

### ISSUE THREAD

**Issue by kuhnchris** [CleverRaven/Cataclysm-DDA#35683] opened 2019-11-23 20:51 UTC
# Describe the bug
Using any item dropped on the groud previously in player inventory will crash the game, rendering any items on the ground useless.

# Steps To Reproduce
Spawn character
pick up any (a)ctivatable item (for example a mop or bandages)
drop item
move beside item
try to (a)ctivate it
receive crash

# Expected behavior
no crash

# Versions and configuration

 - OS: Win 10
 - Game Version: 0.D-9619-g1681742
 - Graphics version: tiles
 - Mods loaded: -

# Additional context

To reproduce the crash, load up the save, walk up to the pile in the top right of the screen, activate the mop.

![grafik](https://user-images.githubusercontent.com/761911/69485106-2a137900-0e3b-11ea-81d3-bd4439405c5c.png)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3882910/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3882911/crash.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882916/save.zip)

**Comment by ZhilkinSerg** [comment] 2019-11-23 21:00
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/35673

**Closed by ZhilkinSerg** 2019-11-23 21:00 UTC
