### ISSUE TITLE
CROWS Turret can fire through reinforced glass

### ISSUE THREAD

**Issue by Zethnet** [CleverRaven/Cataclysm-DDA#36518] opened 2019-12-28 23:37 UTC
# Describe the bug

M249 Autonomous CROWS II turret can fire through the reinforced glass in the complex under gas station, causing damage to limbs and clothes (though the damage seems to be significantly reduced).

# Steps To Reproduce

1. Load the provided save file.
2. Step forward twice.

# Expected behavior

The turret shouldn't fire until line of sight is unobstructed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903 (Windows 10, 64 Bit Build 18362)
[Canton Grove.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4007564/Canton.Grove.zip)

- Game Version: 0.D-10749-gc886711 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, retrodays [sees_player_retro],
    No Filthy Clothing [no_filthy_clothing],
    Stats Through Skills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    Alternative Map Key [alt_map_key],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall]
]

**Comment by anothersimulacrum** [comment] 2019-12-28 23:41
Duplicate of #33374?

**Closed** 2019-12-29 07:27 UTC
