### ISSUE TITLE
house mapgen occasionally overlaps table and wall

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11632] opened 2015-03-17 06:06 UTC
While working on #11631 I found one glitch that I couldn't fix. The generic "house" sometimes spawns a table and some other furniture in a room that's too small for them, so the table intersects a wall.
##

**Comment by narc0tiq** [comment] 2015-03-17 06:16
Would forcing the room to be bigger help?

**Comment by sparr** [comment] 2015-03-17 06:22
maybe. the house generation code is the most twisted of any of the dynamic-room functions I've touched yet.

**Comment by Leland** [comment] 2017-08-17 03:12
Have never seen this – can anyone confirm that this still happens?

**Comment by Leland** [comment] 2017-08-30 02:48
Closing due to lack of reproducibility; feel free to either ping me here to reopen or just create a new issue.

**Comment by FulcrumA** [comment] 2019-06-25 08:09
@Leland 
Pinging as this thing happened just now to me:
![table](https://user-images.githubusercontent.com/38487938/60080694-b6a4f880-9730-11e9-870e-1bef515695cd.png)

 - OS: Win7
 - Game Version: 0.D-4931-g7eb2ac0 ((build 9218)
 - Graphics version: Tiles
 - Mods loaded: "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

It does seem that the very narrow room may be the cause or at least a circumstance conductive to the issue here.

**Comment by sparr** [comment] 2019-06-25 08:45
I would reopen and flag as confirmed but someone revoked my dev/collaborator status :(

**Comment by Night-Pryanik** [comment] 2019-06-26 20:07
As we have lots of variations of manually-drawn houses in json, I wonder whether we still need these procedurally-generated full-of-bugs houses at all.

**Comment by sparr** [comment] 2019-06-26 20:18
I would not be happy removing the procedurally generated houses before having at least 500 unique static houses drawn.

**Comment by kevingranade** [comment] 2019-06-27 01:10
It's much more likely that we'd swap in a new procedurally generated house
method.

**Closed** 2019-12-17 05:27 UTC
Labels: (S2 - Confirmed), <Bug>, Mapgen
