### ISSUE TITLE
"Item spawn rate" keeps resetting to "1.00"

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#20179] opened 2017-02-01 22:49 UTC
0.C-20969-ge0e67bd517, Windows, tiles.

In "World defaults" set "Item spawn scaling factor" to anything but the default value, create a new world and, after starting the game, check the value again - it would be "1.00". Change it, save the game, load - the value would reset to "1.00" again.

**Comment by keyspace** [comment] 2017-02-02 13:40
Duplicate of: #19720

**Closed** 2017-02-02 17:48 UTC
Labels: Duplicate
