### ISSUE TITLE
Error on world load, mentions basements and bionic basements

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70048] opened 2023-12-07 15:40 UTC
### Describe the bug

On loading the world, there is an error mentioning "copy-from" regarding basements and bionic basements

### Attach save file

[Rock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13602056/Rock-trimmed.tar.gz)

### Steps to reproduce

Start game, load world

### Expected behavior

No error window

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/5cae57bb-2112-4553-ac7f-ed1e8fef6047)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 1e7d45b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

**Comment by Termineitor244** [comment] 2023-12-07 23:32
Is this an old save? Because the bionic basement files were moved to the bionic professions mods some time ago, but I see you don't have it active.

**Comment by Consoleable** [comment] 2023-12-08 01:07
> Is this an old save? Because the bionic basement files were moved to the bionic professions mods some time ago, but I see you don't have it active.

No, this save was made within the last day in the latest experimental

**Comment by Night-Pryanik** [comment] 2024-10-06 19:02
Can't confirm on 0.G-12522. Closing until reconfirmed.

**Closed by Night-Pryanik** 2024-10-06 19:02 UTC
Labels: (S2 - Confirmed)
