### ISSUE TITLE
Crafting Canned Food makes the game crash

### ISSUE THREAD

**Issue by StelkWasTaken** [CleverRaven/Cataclysm-DDA#77589] opened 2024-11-04 19:05 UTC
### Describe the bug

Crafting most Canned Food (no matter the type) makes the game crash. Sometimes it works well by using 0.5L Glass Jars but all other containers (all sizes of tin cans and 3L Glass Jars) are no good.

### Attach save file

[Bowie-trimmed.tar.gz](https://github.com/user-attachments/files/17622589/Bowie-trimmed.tar.gz)

### Steps to reproduce

1. Open crafting menu and search "Canned"
2. Craft any of the available non-0.5L glass Jar recipes, either single craft or batch.
3. Use any type of water.
4. Wait until crafting is done.
5. Crash.

### Expected behavior

Craft is finished and canned food is created without issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA]
]

### Additional context

[Save File.zip](https://github.com/user-attachments/files/17622690/Save.File.zip)
[Crash_debug.zip](https://github.com/user-attachments/files/17622709/Crash_debug.zip)

Most tin cans were crafted by an NPC if that helps

**Comment by RenechCDDA** [comment] 2024-11-04 23:42
Duplicate of #77500

**Closed by RenechCDDA** 2024-11-04 23:42 UTC
Labels: (S1 - Need confirmation)
