### ISSUE TITLE
Kaluptic psychosis illusion NPCs dropped weapons do not disapper with them

### ISSUE THREAD

**Issue by Maduscientistu** [CleverRaven/Cataclysm-DDA#58640] opened 2022-06-23 00:31 UTC
### Describe the bug

Now that we can talk with the NPCs we can tell them to drop their weapons. A weapon dropped this way remains in the game after the NPC disappears and the hallucinations status effect passes. I had an NPC drop a sickle that persisted this way. I also got a beebot to drop honeycomb when they disappear. I found a honeycomb on the ground randomly where i think i hit a beebot but was not sure, later another beebot showed up and when i made it disappear there was another honeycomb on the ground. This is a easily ignored thing but here it is anyways thanks for the great game guys.

### Steps to reproduce

1. Have Kaluptic Psychosis
2. Hallucinate
3. Talk to an illusional NPC
4. Tell them to drop their weapons
5. Sleep until the hallucinations stops
6. The weapon remains

### Expected behavior

No weapons dropped. Maybe this can be fixed by only spawning illusion NPCs with nothing on their hands?

### Screenshots

Sorry character already dead but here is the sickle when i got a new character to the base.
![image](https://user-images.githubusercontent.com/9773031/175182319-143dd12b-b9f2-43ba-9c1c-a5a334b9a96d.png)

### Versions and configuration

Experimental 20/06/2022

**Comment by NetSysFire** [comment] 2022-06-30 20:50
@dseguin since you did #54307, could you take a look at this, too?

**Comment by Night-Pryanik** [comment] 2022-07-09 11:56
Can't confirm on 0.F-9789.

This guy with the exclamation mark is a hallucination
![изображение](https://user-images.githubusercontent.com/11132525/178104436-58361d25-98a9-4093-8dac-ae8c5e8130b7.png)

The game says that he drops his weapon
![изображение](https://user-images.githubusercontent.com/11132525/178104476-470ab0a9-143c-436c-a7dd-33da49f1e5b9.png)

But actually he still wields it
![изображение](https://user-images.githubusercontent.com/11132525/178104554-c220373b-129c-4df0-8d3e-408b22ba666b.png)

Game explicitly states that if NPC is a hallucination, then actual dropping should fail silently.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b3c3acda8dbcb5c0bb482ab1c7ed6f3af2da97f1/src/npctalk_funcs.cpp#L959-L963

**Comment by Night-Pryanik** [comment] 2022-10-01 12:55
@NetSysFire why is this issue has "confirmed" tag? I tested the issue, and my tests demonstrated that hallucination NPC don't drop their weapons.

NPC saying he drops his weapon while actually he doesn't looks more like a feature of hallucination rather than a game bug IMO.

**Comment by NetSysFire** [comment] 2022-10-01 13:21
Unsure. Might have fat-fingered the label.

**Comment by Night-Pryanik** [comment] 2022-11-13 20:11
Closing as unconfirmed. If it's still reproducible somehow, ping me to reopen.

**Closed by Night-Pryanik** 2022-11-13 20:11 UTC
Labels: <Bug>, NPC / Factions, (S1 - Need confirmation)
