### ISSUE TITLE
Game freezes/stuck, cannot close or end task

### ISSUE THREAD

**Issue by Parahacker** [CleverRaven/Cataclysm-DDA#23850] opened 2018-05-26 06:08 UTC
Game version: experimental 7426

Operating system: Win 10

Tiles or curses: Tiles

Mods active: All of them that are bundled; except Dino mod, generic guns, and the balancing mods except for the default (filthy clothes etc.)

### Expected behavior
Does not freeze

### Actual behavior
Freezes and unable to close from task manager; game locks up.

### Steps to reproduce the behavior
Not sure if this helps but I usually start with bad day/House on fire scenario. Usually happens within first 2-300 turns. Fullscreen setting

**Comment by ZhilkinSerg** [comment] 2018-05-26 07:57
Possible duplicate of #23770.

**Comment by BevapDin** [comment] 2018-05-28 10:54
Going to close this as duplicate of the mentioned issue. @Parahacker If you think this is a separate issue, please explain why/how it is different.

**Closed by BevapDin** 2018-05-28 10:54 UTC
Labels: <Crash / Freeze>
