### ISSUE TITLE
Seg Fault Crash in Bandit Camp

### ISSUE THREAD

**Issue by Grotato** [CleverRaven/Cataclysm-DDA#75365] opened 2024-08-01 07:41 UTC
### Describe the bug

Game crashes during combat in a bandit camp. The first three crashes occurred while fighting the first bandit, at seemingly no certain point, but then it crashed while engaging a second bandit after killing the first. 

### Attach save file

[Roggen-trimmed.tar.gz](https://github.com/user-attachments/files/16451770/Roggen-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached save.
2. Start a fight with the bandits in the camp south of the refugee center.
3. At some point, likely while fighting the first bandit, the crash will occur.

### Expected behavior

I expected the game to not crash while fighting the bandits. My save isn't very old, and I've only fought zombies thus far. The bandits are the first NPC's I've fought in this save, so the issue might not be specific to them.

### Versions and configuration

- Windows 10
- 348ab84 
- Tiles
- English
- Mods:
![Cdda-mods](https://github.com/user-attachments/assets/780824d1-850f-4b28-abe1-25a617f9fb8e)

### Additional context

[crash.zip](https://github.com/user-attachments/files/16451896/crash.zip)

**Comment by darkgrifter** [comment] 2024-08-01 13:56
[BombMagicMind-trimmed.tar.gz](https://github.com/user-attachments/files/16457438/BombMagicMind-trimmed.tar.gz)
![Mods](https://github.com/user-attachments/assets/fd25b74a-7201-4b15-a6c4-554fdba3b9c1)
[crash.log](https://github.com/user-attachments/files/16457482/crash.log)


I have a similar segmentation fault, 
Steps to reproduce.
1: Spawn in 
2: Hold the down arrow
3: ???
4: Crash

**Comment by PatrikLundell** [comment] 2024-08-02 13:15
Failed to reproduce, because bringing a mace to a gunfight results in death. A large number of mods weren't available on my machine, and have no idea how magic is supposed to work, so maybe magic might actually have given the bugger a chance? Anyway, managed to whack a bandit to death on the second attempt, but no crash before the death in either attempt.

**Comment by Cddaplayer** [comment] 2024-08-03 05:14
Same bug here, when get close to some bandit, game crashed.
[crash.log](https://github.com/user-attachments/files/16478178/crash.log)

**Comment by PatrikLundell** [comment] 2024-08-03 11:07
@darkgrifter's save is actually useful, as it provides a repeatable crash.
So far I've seen it crash due to something throwing "The Historical Weaponsmith" (a book) and the code then trying to find the ammo in its magazine, which doesn't exist. This seems to be caused by the throw action bizarrely checking if friendly critters would be hit and stating that the ranged attack is not throwing. Hacking the code to flip that boolean to "true" causes the book to be thrown successfully.
Even better, there was a swap_critters crash immediately after the successful book throw when testing that correction, so I've had a chance to attack that one too (but not test it, as I've failed to have it repeated).

**Comment by RenechCDDA** [comment] 2024-08-14 18:43
Fixed by #75418, looks like

**Closed by RenechCDDA** 2024-08-14 18:43 UTC
Labels: (S1 - Need confirmation)
