### ISSUE TITLE
New character has a non-functional gun

### ISSUE THREAD

**Issue by ScionOfEris** [CleverRaven/Cataclysm-DDA#78456] opened 2024-12-10 02:05 UTC
### Describe the bug

I started up a random run, and got a Mob Boss.

She's carrying a Desert Eagle pistol, with a full clip of .44 Magnum FMJ.   (along with 2 spare clips of the same)

However, if I attempt to fire the gun I get the error:
The Desert Eagle Pistol can't e fired while loaded with incompatible ammunition .44 Magnum FMJ

The gun has no mods at all, although the text of the gun does mention it can use a variety of rounds depending on the conversion kit.  My guess is there needs to be a default conversion kit mod that is missing. 

### Attach save file

[Randonia-trimmed.tar.gz](https://github.com/user-attachments/files/18070452/Randonia-trimmed.tar.gz)

### Steps to reproduce

hit 'f', see error

### Expected behavior

the aim menu to appear

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 78fd6e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope]
]

**Comment by ScionOfEris** [comment] 2024-12-10 02:06
Forgot to mention, this is .H Stable.

**Comment by osuphobia** [comment] 2024-12-10 02:48
Duplicate of #78343

**Closed** 2024-12-10 06:31 UTC
Labels: (S1 - Need confirmation)
