### ISSUE TITLE
NPC trading doesn't show multiple items

### ISSUE THREAD

**Issue by MattD94** [CleverRaven/Cataclysm-DDA#22937] opened 2018-02-14 19:19 UTC
Game version:  0.C-26193-g452db2d

Operating system: Ubuntu 16.04.3 Via WSL on Windows 10

Tiles or curses: Curses

Mods active: DDA, Disable NPC Needs, Simplified Nutrition

### Expected behavior
When trading with an NPC who is following me (via the "Let's trade items" option), I should be able to see if I or they have more than one of a specific item. 

For example, if they have 2 pairs of light gloves in their inventory (that they are not wearing) the gloves should show up twice on their trading screen or be prefixed by the amount as the regular inventory does. 

When trading I should also be able to somehow select how many of an item to give/take.

### Actual behavior
Multiple instances of items in the player's or NPC's inventory are not shown on the trading screen when accessed via "Let's trade items" (may extend to trading with NPCs who are not following the player)

For example, if I have 7 leather patches in my inventory, only a single leather patch will be shown on my half of the trading menu when I select the "Let's trade items" options.

Consequently, to give or take more than one of these items to/from the NPC, you must make multiple trades, which can be tedious if the NPC has picked up multiples of an item you want/need to remove from their inventory.

### Steps to reproduce the behavior
1. Get an NPC to follow you
2. Make sure you have multiple non-unique items in your/their inventory (it doesn't matter if you give them the items through "Let's trade items" or "Hold onto this item")
3. Trade with them using "Let's trade items"

**Comment by pjf** [comment] 2019-08-11 15:23
At least in my recent experience with the trade code, showing item stacks should now be working as intended, so I think we can close this one! :tada:

**Closed** 2019-08-12 04:05 UTC
Labels: NPC / Factions
