### ISSUE TITLE
No warning while moving furniture near unseen zombies

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45682] opened 2020-11-28 09:41 UTC
# Describe the bug
When grabbing/moving a heavy object, many turns are passed without any warning notification zombies are in sight.
They then appear and proceed to welcome you the current turn.

# Steps To Reproduce
Place zombies out of sight and nearby.
Push heavy furniture of your choice.
Get attacked several times.

# Expected behavior
While turns are passing during an grabbed furniture move/drag, if a new zombie appears in vision you should be warned that a zombie has appeared and asked if you want to continue your action. Like what occurs with most other actions. Although I don't expect to be warned while dragging a shopping cart around, so I'm hopeful those can be 2 separate behaviors. 

# Screenshots
Video of the issue.
https://clips.twitch.tv/BigHyperNigiriPMSTwin

# Versions and configuration
 - OS: Windows 7
 - Game Version: 0.E-7886-g76fd581
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA, Disable NPC Needs, Bionic Professions, Magiclysm

# Additional context
After looking again, I think the combination of me moving off a chair AND moving the object created a huge turn skip. Technically a bad choice, but ideally I would want to stop my action midway.

**Comment by anothersimulacrum** [comment] 2020-11-28 16:41
Thanks for the report!
Duplicate of #45010

**Closed by anothersimulacrum** 2020-11-28 16:41 UTC
Labels: (S3 - Duplicate)
