### ISSUE TITLE
Bug with starting location

### ISSUE THREAD

**Issue by DmitriyAAA** [CleverRaven/Cataclysm-DDA#40051] opened 2020-05-01 13:27 UTC
The bug with starting location "Refugee Center" is still relevant. It is unable to generate it.

**Comment by ZhilkinSerg** [comment] 2020-05-01 16:52
Please do not ignore issue template. At a bare minimum report game version and reproduce steps.

**Comment by DmitriyAAA** [comment] 2020-05-02 11:31
Version 0.E-1426-g0d2a3d9(tiles). I tried to generate world with scenario Safe Place and starting location Refugee Center. And it didn't work. The map settings are standart.

**Comment by Night-Pryanik** [comment] 2020-05-15 07:55
Closing as a duplicate of #35376.

**Closed by Night-Pryanik** 2020-05-15 07:55 UTC
Labels: (S1 - Need confirmation), <Bug>, Scenarios
