### ISSUE TITLE
Keybinding window missing redraw

### ISSUE THREAD

**Issue by lekto** [CleverRaven/Cataclysm-DDA#14270] opened 2015-12-01 14:24 UTC
1. Press '@'
2. Press '?'
3. Press 'Esc'
4. Now you have black square in the middle of the screen.

**Comment by drbig** [comment] 2015-12-01 17:32
I assume it disappears the moment you move?

**Comment by lekto** [comment] 2015-12-01 17:41
It disappears when I get out of player info (press 'Esc' again).

**Comment by drbig** [comment] 2015-12-01 17:52
Hmm, curses. I'd say it's a bug then.

**Comment by lekto** [comment] 2015-12-01 17:54
It happens in ncurses (bash) and also SDL2.

**Comment by drbig** [comment] 2015-12-01 18:18
Then it might be also that long-term topic about sdl/ncurses, *-buffering and redraws.

**Comment by Sir-Kernicus** [comment] 2016-01-14 17:41
If you press esc it goes away then you can press @ again

**Comment by mugling** [comment] 2016-09-21 16:14
Have seen in recent `master`

**Comment by Leland** [comment] 2017-05-08 04:33
#19233 notes that the <kbd>V</kbd> keybinding window has the same issue.

To replicate, press V, then press ?, then press Esc.

Can confirm both that and the issue here still exist.

**Comment by Leland** [comment] 2017-05-24 20:14
Duplicate of #8514

**Closed by Leland** 2017-05-24 20:14 UTC
Labels: Bug, Information / Interface, Validated
