### ISSUE TITLE
[Feature Request] Ability to transport zombie slaves with vehicles

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#20162] opened 2017-01-29 22:29 UTC
Currently, slaves, or any mob that isn't an NPC or PC, when inside a car, when player tries to drive it, will start crashing into the plating and eventually die, along with causing major damage to the vehicle. It would be pretty nice and make slaves more useful if one was able to say, tie them up to a seat and safely transport them.

**Comment by BevapDin** [comment] 2017-04-29 17:28
Duplicate of #11381.

**Closed by BevapDin** 2017-04-29 17:28 UTC
