### ISSUE TITLE
Iron solder with UPS mod can't be used to dismantle robots

### ISSUE THREAD

**Issue by Leosky** [CleverRaven/Cataclysm-DDA#31815] opened 2019-06-24 21:17 UTC
# Describe the bug
Iron solder with UPS mod can't be used to dismantle robots

# Steps To Reproduce
Mod a soldering iron with UPS convertion and try to dissmantle a robot. It shouldn't be possible.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-4929-gdd1dfac [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Larger Vehicules Containers [LargerVehiculesContainers],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    sees-player icon, +attitude [sees_player],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    Disable NPC Needs [no_npc_food]
]

**Comment by Kmsxkuse** [comment] 2019-06-25 06:11
Sounds like #29961 which still hasnt been fixed.

**Comment by Inglonias** [comment] 2019-06-25 13:09
Yeah, my fix for UPS modded itms mainly worked with iuse, which isn't the whole story. This is something that cannot be fixed all at once without serious refactoring. Nevertheless, we know the general cure now (find whatever is calling `ammo_remaining` or `ammo_sufficient` regarding the tool and replace that call with `units_remaining` or `units_sufficient`)

**Comment by ifreund** [comment] 2019-06-26 19:50
Closing as a duplicate of #29961

**Closed by ifreund** 2019-06-26 19:50 UTC
