### ISSUE TITLE
Wrong ilumination level inside vehicle

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#44693] opened 2020-10-07 13:29 UTC
# Describe the bug

There are very dark tiles where there should not be any, or at least they should be cloudy (except south one - it should just be bright, no questions about it), considering all tiles adjacent to them are bright.

# Steps To Reproduce

Load [save](https://drive.google.com/file/d/163Aki9b0dVyJwLW-PLA0rdba6fnfwTSg/view?usp=sharing) and see for yourself.

# Expected behavior

Lighting making sense.

# Screenshots

Closed rear door. Seems legit, more or less (lighting around the NPC is from the lamp on her seat).
![cataclysm-tiles_2020_10_07_20_09_33_474](https://user-images.githubusercontent.com/56833396/95336401-d6870e00-08da-11eb-8d94-b122946e106b.png)

Open rear door. Tiles to W,S and E of the character are "very dark" while all other tiles are "bright".
![cataclysm-tiles_2020_10_07_20_05_51_763](https://user-images.githubusercontent.com/56833396/95336392-d4bd4a80-08da-11eb-8c04-b2bc128daa3d.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-6546-g51130a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Aivean** [comment] 2020-10-13 20:35
I can confirm the bug. 
What's more weird that upon opening/closing the door lighting is correct. Bug appears when character moves around the vehicle (some tiles become dark).
![light-bug](https://user-images.githubusercontent.com/2865203/95913304-df536600-0d58-11eb-9d9b-005d08938627.gif)

**Comment by Aivean** [comment] 2020-10-13 22:28
Ok, so the issue is with the `outside_cache` and current hack for indoor lighting (when light shines from "outside" tiles into "inside" tiles). Here I've marked "outside" tiles with "1" and "inside" tiles with "0":
![image](https://user-images.githubusercontent.com/2865203/95922695-b5a23b00-0d68-11eb-90d8-65dfd4a65766.png)

**Closed** 2020-10-15 02:16 UTC
