### ISSUE TITLE
Segfault on NPC death

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#45566] opened 2020-11-22 05:23 UTC
# Describe the bug

segfault when the NPC gets mauled to death.

# Steps To Reproduce

[Protean6.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5578989/Protean6.zip)
Load the save, either character (not sure why there's two?  I have done some save game editing but I don't think that's whats causing the segfault)

# Expected behavior

No segfault.

**Comment by andrei8l** [comment] 2020-11-22 10:01
I only get a segfault on reload with is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45545
I don't get a segfault if I stop the reloading action and let the NPC die.

**Comment by hexagonrecursion** [comment] 2021-08-29 07:19
Could not reproduce

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations]
]

**Comment by anothersimulacrum** [comment] 2021-09-11 14:05
It's been many months - if this still persists, let me know and we can reopen it, but I'm closing this as resolved for now.

**Closed by anothersimulacrum** 2021-09-11 14:05 UTC
Labels: <Bug>, <Crash / Freeze>
