### ISSUE TITLE
Seg fault when comparing items using the filter

### ISSUE THREAD

**Issue by ZoolookCDDA** [CleverRaven/Cataclysm-DDA#35763] opened 2019-11-28 18:08 UTC
# Describe the bug

Segmentation fault occurs consistently in the latest experimental version when comparing certain pairs of items using the filter option.

# Steps To Reproduce

1. In the attached save file, use 'I' and compare the cellphone with the bra, selecting the latter using the filter (i.e., type /bra).
2. The game crashes with a segmentation fault.

# Expected behavior

The game should not crash.

# Versions and configuration

-----------------------------------------
18:45:43.638 : Starting log.
18:45:43.638 INFO : Cataclysm DDA version 0.D-9735-gc3982c9
18:45:43.639 INFO : Number of render drivers on your system: 3
18:45:43.639 INFO : Render driver: 0/opengl
18:45:43.639 INFO : Render driver: 1/opengles2
18:45:43.639 INFO : Render driver: 2/software
18:45:43.783 INFO : SDL version used during compile is 2.0.4
18:45:43.783 INFO : SDL version used during linking and in runtime is 2.0.8
18:45:43.854 INFO : Active renderer: 2/software
18:45:43.928 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
18:45:43.949 WARNING : opendir [./mods/] failed with "Ingen sådan fil eller filkatalog".
18:46:09.628 WARNING : opendir [./save/Birdseye/mods] failed with "Ingen sådan fil eller filkatalog".
18:46:12.367 INFO : Loaded tileset: retrodays
18:46:35.625 :  GAME REPORT:
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-9735-gc3982c9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

18:46:42.092 : Log shutdown.
-----------------------------------------

# Additional context

The crash does not occur for all combinations of items. For some combinations, there is no crash but the items are still not being compared.

[Files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3902744/Files.zip)

**Comment by ZhilkinSerg** [comment] 2019-11-28 21:41
Duplicate of #34046

**Closed by ZhilkinSerg** 2019-11-28 21:41 UTC
