### ISSUE TITLE
Firearm repair kit requires charges to use its non-powered tools.

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36193] opened 2019-12-17 17:04 UTC
# Describe the bug
Firearm repair kit requires charges to use it's hacksaw. Attempting to cut metal with the firearm repair kit results in refusal to give any options unless battery has 100 charges. Cutting the metal then uses those 100 charges. Same for prying nails if used via the activate menu.

# Steps To Reproduce
Attempt to cut metal or pry objects with the firearm repair kit.

# Expected behavior
Only the gun related actions should require charges.

**Comment by Night-Pryanik** [comment] 2019-12-19 18:28
Duplicate of #30137.

**Closed by Night-Pryanik** 2019-12-19 18:28 UTC
