### ISSUE TITLE
Motorboats are not boardable when part of the boat is over shallow water.

### ISSUE THREAD

**Issue by Miloch** [CleverRaven/Cataclysm-DDA#48834] opened 2021-05-11 16:13 UTC
# Describe the bug

When you park a motorboat over shallow water and try to step on a part of the boat over deep water, you get asked if you want to dive into the deep water.  If you say yes it moves you underwater.  If you say no it doesn't move you.  NOTE: (I tried again with the canoe and was able to replicate it with the canoe too.)  I tested both with the debug tool.

# Steps To Reproduce

1. Create a world and move to a body of water.
2. Spawn a motorboat.
3. Move the motorboat until part is over shallow water and part is over deep water.
4. Try to walk on part of the boat over deep water.

# Expected behavior

You should be able to walk on the boat without diving into the water.

# Screenshots

![Dive Into Boat](https://user-images.githubusercontent.com/4497993/117849154-a07f8300-b249-11eb-9df6-3532723d99e0.PNG)

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 07c58d9 [64-bit]
- Graphics Version: Tiles (No it's ASCII)
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm] (NOTE: I tried without magiclism too)
]

# Additional context

**Comment by molkero** [comment] 2021-05-11 16:37
Any cattails under the boat? I recall having this issue, but only with cattails.

**Comment by Miloch** [comment] 2021-05-11 17:34
> Any cattails under the boat? I recall having this issue, but only with cattails.

I tried with and without.  It made no difference.

**Comment by Maleclypse** [comment] 2021-05-13 15:59
Confirmed

**Comment by Miloch** [comment] 2021-05-15 00:03
I tried with a Canoe again and was able to replicate it with a canoe also.

**Comment by gisaku33** [comment] 2021-05-20 22:15
I tested it out and as far as I can tell, the bug happens any time the boat's oars/engine is above walkable ground. If you're using an amphibious vehicle, it won't happen if any of your wheels are over the water.

**Comment by int-ua** [comment] 2021-06-17 20:16
#48011 ?

**Comment by Malorn-Deslor** [comment] 2021-09-27 02:12
Very confirmed, this is still happening.

Oddly enough, it does not appear fully consistant. This happened with a cabin cruiser, but not with my own homemade boat.

**Comment by wapcaplet** [comment] 2022-01-16 05:48
Closing as duplicate of #48011 and possibly #46488

**Closed by wapcaplet** 2022-01-16 05:48 UTC
Labels: Info / User Interface, (S2 - Confirmed), Map / Mapgen, Mechanics: Character / Player
