### ISSUE TITLE
NPCs requiring food/water despite having the Disable NPC Needs mod active

### ISSUE THREAD

**Issue by WormGrill** [CleverRaven/Cataclysm-DDA#34870] opened 2019-10-19 16:49 UTC
# Describe the bug
The starting npc in my save has started complaining about needing food/water. Sizing up their stats (Shift+S) shows they're getting hungry, and she won't teach because she's thirsty. Also they may be stealing/eating food, as I find paper wrappers and plastic bags in their inventory even though they're not set to pick up items nor did I give them those items

# Steps To Reproduce
1. Start a world with the Disable NPC Needs mod active
2. Recruit the starting NPC
3. Wait a while for their stats to go down, they should start complaining about getting hungry/thirsty and/or start eating food.

# Expected behavior
With the Disable NPC Needs mod active NPCs shouldn't have any food/drink requirements.

# Screenshots

[https://i.imgur.com/1AGT0Cm.png](url)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8646-g556b355 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation]
]

**Comment by Night-Pryanik** [comment] 2019-10-19 17:30
Duplicate of #30501.

**Closed by Night-Pryanik** 2019-10-19 17:30 UTC
