### ISSUE TITLE
Food in stomach has x5 times volume in inventory

### ISSUE THREAD

**Issue by Heikelol** [CleverRaven/Cataclysm-DDA#41326] opened 2020-06-15 13:27 UTC
# Describe the bug

When you eat any food, like butter, your stomach gets filled 5 times the volume expected. If butter in inventory has 0.02Liters, when you eat it, it has 0.1Liters (5 times more).

# Steps To Reproduce

1. Check volume in stomach
2. Eat butter
3. Check volume in stomach

# Expected behavior

Food in stomach should have similar volume that in inventory. Given the limited space of stomach, reducing the caloric density of food by 5 times, result in a constant grinding for calories every 2 hours.

A full stomach of dense caloric food (2.5Liters) should give enought calories for a couple of days (expected caloric density of fatty foods is 500-600kcal/0.1L, which results in more than 12500kcal for a full stomach).

# Screenshots

Butter:
https://i.gyazo.com/d6a61c86b39fe731e1a3572e582b522d.png

Torrezno:
https://i.gyazo.com/e182802681e38191ee33473433668fb2.png
https://i.gyazo.com/fb27515f58e01b88eddc16905a0ae685.png
https://i.gyazo.com/24c1c24ff30a4165b455f2d94abfc129.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3208-gbd9759e [64-bit]
- Graphics Version: Tiles
- Game Language: Idioma del sistema []
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Aftershock [aftershock],
    Dark Skies Above [darkskies],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Mythical Martial Arts [MMA]
]

# Additional context

**Comment by Ramza13** [comment] 2020-06-15 15:26
This is intentional and caused by #40402.  It's basically a shortcut to make certain food more filling without having to a huge and unclear rewrite.

**Comment by anothersimulacrum** [comment] 2020-06-15 15:35
Okay, I'm closing this as an intentional feature then.

**Closed by anothersimulacrum** 2020-06-15 15:35 UTC
Labels: (S4 - Invalid)

**Comment by derektumolo** [comment] 2020-06-15 15:48
I think a solution for butter and other dense foods should be made. The behavior seems illogical.

**Comment by Ramza13** [comment] 2020-06-15 15:58
You are probably right so give me some more details as to what should change.  Eating butter seems pretty weird and if that's the only issue in my opinion the risk of further changes out ways the annoyance but that's not set in stone

Is the problem that you can't just eat butter all the time anymore?  Or what real life style scenarios is this impacting?

**Comment by anothersimulacrum** [comment] 2020-06-15 16:08
Could you give an example of how it's confusing outside of scenarios when you have information shouldn't have access to? Yes, it's confusing if you're eating something then inspecting the volume filled in your stomach, but that's not information you should have access to.

**Comment by Heikelol** [comment] 2020-06-15 18:12
I've been trying eating only rendered fat for a week, and the game keeps telling me I need to eat more calorie-dense food. You cannot space your foods because limited volume intake of 500 grams (including water).

It's not logical to eat 500gr of food (including water) and retching to the limit of vomiting.

**Comment by Ramza13** [comment] 2020-06-15 18:23
So several thoughts, first on the vomiting stuff #41316 should hopefully help with that.  

My approach to this is to try and consider the real world case that's not working right and try to replicate the real world. In that sense eating only rendered fat or butter is weird and if that's not quite working ok I consider that a low priority bug because it's not a common thing people do and I suspect would make you quite sick.  But I'm not sure that's your real problem.

It sounds like the real issue is with trying to get as much nutrition as possible and running into limits regardless of what you eat?  Like if you replace rendered fat with a cheeseburger are you having the same issues or is it really just that eating butter/chunks of fat is acting weird?

**Comment by Heikelol** [comment] 2020-06-15 18:35
I don't know the exact maths but I keep reading the status "very hungry" and messages of losing weight while grinding some books.

What I expect is to eat 1-2 big meals per day to maximice time studying, like people do IRL.

In game, I can only eat limited food per meal. If I skip some meals, the game tells that you need to eat more caloric-dense food since you are losing weight. I try to maximice calories per ration, and I go direct to high fat things.

But I can only eat a little and drink a little. I keep myself losing weight and being thirsty even if I have bull belly, because I cannot drink or eat more, and I vomit if a force it. And after 2 hours I'm again very hungry. So I have to eat every 2 hours to gain weigth, since I cannot take a really big caloric meal.

That's really annoying if you want to spend a lot of time doing a labour, like reading, repairing or crafting. 

Nutrition should work in a way that allows you to eat a big lunch (or a caloric one), and keep working for 10-12 hours. And you still should have a superavit in caloric balance if you eat a lot of calories and do passive work like reading.

**Comment by Zireael07** [comment] 2020-06-15 18:39
> What I expect is to eat 1-2 big meals per day to maximice time studying, like people do IRL.

People IRL have less calorie intake requirements because they mostly sit on their collective *sses. The survivor in CDDA does a lot of energy intensive, physical stuff, so the average calories needed per day is much higher than what a student needs.

**Comment by Ramza13** [comment] 2020-06-15 18:43
So another thing to consider is auto eat/drink zones.  At the moment they are broken but #41316 will fix that and then you can have your character automatically pause reading to eat or drink as needed.

**Comment by Heikelol** [comment] 2020-06-15 18:47
Well, if you want players to take 4000 calories a day like a soldier in an active patrol duty, you are forcing them to make big and fatty meals. I'm not against that (however I find very unrealistic to spend 4000 calories while sitting on my car reading books).

What I'm saying is that the game forces you to make continous meal intakes of caloric dense food to gain weight. You cannot gain weight by overeating or by having very high caloric intakes in one meal, because the nutrition mechanics forbid it.

**Comment by KorGgenT** [comment] 2020-06-15 20:09
> > What I expect is to eat 1-2 big meals per day to maximice time studying, like people do IRL.
> 
> People IRL have less calorie intake requirements because they mostly sit on their collective *sses. The survivor in CDDA does a lot of energy intensive, physical stuff, so the average calories needed per day is much higher than what a student needs. Compare to a modern soldier instead (IIRC), not a student.

The CDDA survivor's calorie requirements are calculated by activity levels, so if he's just book grinding as he says, his requirements are probable just the baseline of 2500 kcal anyway.

**Comment by I-am-Erk** [comment] 2020-06-23 22:41
Just to clarify a bit, regarding fats in specific the increase in volume is intentional - it's to stop you from eating a litre of butter, that should make you throw up.

However there was a glitch in how food 'fillingness' was being calculated, some foods (generally foods with a high quench and low weight) were getting multiplied way too much. This has now been fixed, please let me know if things are still behaving illogically. There are some food elements that still need tweaking.
