### ISSUE TITLE
Alarm Function doesn't work as advertised.

### ISSUE THREAD

**Issue by erendor** [CleverRaven/Cataclysm-DDA#8330] opened 2014-07-25 15:20 UTC
As title, the alarm function for clocks/watches/PDA/etc doesn't seem to work like it should - setting an alarm for 8 hours, for example, at 12am midnight, will cause the alarm to go off at 5am.

This is in version 1d2f15a or 0.A-1813, but it's been around for a while now.
##

**Comment by Dracace** [comment] 2017-05-15 16:40
> Has it been fixed? I was unable to reproduce this.

+1

**Comment by AlecWhite** [comment] 2017-05-15 16:49
I couldn't reproduce it with 0.C-22337-g54e8448fc8.

**Comment by Dracace** [comment] 2017-05-15 16:53
v 6426

The alarm is working fine

**Comment by Leland** [comment] 2017-05-15 16:58
Closing due to lack of confirmation. If any _can_ confirm this behavior, feel free to ping me here to reopen... or just create a new issue 😁

**Closed by Leland** 2017-05-15 16:58 UTC
Labels: Bug, Confirmation Needed
