### ISSUE TITLE
Recraft and "craft as long as possible" broken

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#28698] opened 2019-03-14 08:17 UTC
**Describe the bug**  
Recrafting doesn't work, attempting to do so gives the message "Craft something first". "Craft as long as possible" gives the following error:

![DDA error](https://user-images.githubusercontent.com/4408382/54340449-9bd0cd00-45f4-11e9-9750-f36c628ba1ec.png)

**To Reproduce**  
1. Create character, wish a rock, some pipes, and skills to create makeshift crowbar
2. Craft a makeshift crowbar
3. Attempt to recraft another makeshift crowbar
4. Attempt to "craft as long as possible" makeshift crowbars

**Expected behavior**  
Recrafting crafts another item. "Craft as long as possible" crafts items until it is no longer possible.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: commit 5b6a0554eb750faf7c0d53c7675af51a538a84d8
 - Graphics version: Terminal
 - Mods loaded: base/default

**Additional context**  
Savegame: 
[Martin Bluff.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2965291/Martin.Bluff.zip)

**Comment by Zombiemanpig** [comment] 2019-03-14 15:34
Can confirm

**Comment by dcaprilfool** [comment] 2019-03-14 16:58
i just tested it and it works just fine.

**Comment by Zombiemanpig** [comment] 2019-03-14 17:56
> i just tested it and it works just fine.

on 8613?

I just updated again and tried it again and again I got this:
![image](https://user-images.githubusercontent.com/47362783/54380051-fd2e8580-4660-11e9-9694-9316772f4704.png)

**Comment by zakhad** [comment] 2019-03-14 19:56
I can confirm that it doesn't work either for me, i keep getting the craft something first popup.

**Comment by cafeoh** [comment] 2019-03-14 23:51
The recraft bug should be fixed in [#28719](https://github.com/CleverRaven/Cataclysm-DDA/pull/28719) but I couldn't reproduce the "Craft as long as possible" issue. To be honest I couldn't get it to work at all, it would only just craft one, but I didn't get any error message.

**Comment by Zombiemanpig** [comment] 2019-03-15 00:10
> The recraft bug should be fixed in [#28719](https://github.com/CleverRaven/Cataclysm-DDA/pull/28719) but I couldn't reproduce the "Craft as long as possible" issue. To be honest I couldn't get it to work at all, it would only just craft one, but I didn't get any error message.

I have it working in 8611 as intended.

**Closed** 2019-04-09 03:04 UTC
Labels: <Bug>, Crafting / Construction / Recipes
