### ISSUE TITLE
Rubiks will sell you faulty bionics

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54257] opened 2022-01-10 18:52 UTC
### Describe the bug

It turns out Rubiks will occasionally generate faulty bionics in his inventory. Voice remodulators are by far the most common but I've also managed to get him to generate bionic nostrils.

### Steps to reproduce

Outside of using another bug to get him to keep rerolling his inventory, I guess just 'keep checking his wares until he gets a faulty bionic in'.

### Expected behavior

He really shouldn't be trying to sell you faulty bionics. Voice remodulator at least has some feasible use since it gives a bonus to lying and intimidation, but bionic nostril suggests this may not be intended behaviour.

### Screenshots

![image](https://user-images.githubusercontent.com/45110965/148822332-85b87a68-f495-478d-a3c1-67f9217a619e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7ddf235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment] 2022-01-14 11:05
Confirmed

![DeepinScreenshot_select-area_20220114135737](https://user-images.githubusercontent.com/52621858/149504654-4e74a42e-8cc9-42c2-9d5a-c99ee9b584be.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by Nerezza** [comment] 2022-02-04 23:43
I've been poking around Rubik's files fixing bugs with his shop and I wanted to confirm that this is in fact intentional:

```
  {
    "type": "item_group",
    "id": "EXODII_CBM_tier1_fun",
    "items": [ [ "bio_tattoo_led", 10 ], [ "bio_nostril", 1 ], [ "bio_voice", 10 ] ]
  },
```

**Comment by wapcaplet** [comment] 2022-02-05 00:21
Indeed, looks like this was added by Erk himself in #52380. I believe this is working as intended. Closing issue.

**Closed by wapcaplet** 2022-02-05 00:21 UTC
Labels: <Bug>, NPC / Factions, (S2 - Confirmed), Bionics
