### ISSUE TITLE
Burned down items while picking up gives error message

### ISSUE THREAD

**Issue by Aerotinge** [CleverRaven/Cataclysm-DDA#49323] opened 2021-06-16 06:33 UTC
# Describe the bug

When trying to pick up items from a tile on fire, I am given the following error message:
```
 DEBUG    : lost target item of ACT_PICKUP

 FUNCTION : bool Pickup::do_pickup(std::vector<item_location>&, std::vector<int>&, bool)
 FILE     : src/pickup.cpp
 LINE     : 422
```

# Steps To Reproduce

1. Drop some flammable on a tile nearby, set fire on it.
2. Spawn a monster that drop small pieces loots(e.g. ammo/rags), for example kevlar zombie.
3. Kill it, it drops item.
4. Pick up all of them at one action.

# Expected behavior

An item burned that disappearing is expectable, but it should be handled by a message "Fail to pick up %s, it's burning down."

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: Both 0.E-3 [64-bit] and #17c44e4
- Graphics Version: Tiles
- Mods loaded: [
  "dda",
  "no_npc_food",
  "cbm_slots",
  "sees_player_retro"
]

# Additional context

**Comment by Night-Pryanik** [comment] 2021-06-16 06:46
Duplicate of #46593.

**Closed by Night-Pryanik** 2021-06-16 06:46 UTC
