### ISSUE TITLE
How is it I'm able to tell time with no watch?

### ISSUE THREAD

**Issue by qtquazar** [CleverRaven/Cataclysm-DDA#28837] opened 2019-03-20 01:48 UTC
**Describe the bug**  
Couldn't find this elsewhere, but my apologies if someone has flagged.

Seems like you can tell time accurately in 0.D without actually possessing a watch. Other hidden attributes like temperature only show up (properly) with the right equipment.

**To Reproduce**  
1. Happens from game start

**Expected behavior**  
Time does not appear or approximates in ASCII against the sun. I forget... haven't played since late in experimental 0.C cycle.

**Versions and configuration(please complete the following information):**
0.D

**Additional context**  
Using tiles version.

**Comment by NotFuji** [comment] 2019-03-20 01:50
Inventory would be helpful, several non-watch items give time displays

**Comment by KorGgenT** [comment] 2019-03-20 02:30
is this 0.D stable, or experimental?

**Comment by qtquazar** [comment] 2019-03-20 02:38
@NotFuji. No inventory, starting from RBD. Pretty sure my towel doesn't have a digital display. :)  Should be easy to confirm.

KorGgenT: 0.D stable. Can't get the launcher to work, so I've been consistently on that.

No mods of note either.

**Comment by Night-Pryanik** [comment] 2019-03-20 05:40
Could you please update to latest experimental and check if this is still an issue?

**Comment by qtquazar** [comment] 2019-03-21 01:25
Huh... no, seems ok on start of RBD on latest experimental (8637). Weird. Haven't replicated all settings from my 0.D setup (launcher crashes and I'd have to do a point-by-point) but maybe something was tweaked?

**Comment by KorGgenT** [comment] 2019-03-21 02:36
> Huh... no, seems ok on start of RBD on latest experimental (8637). Weird. Haven't replicated all settings from my 0.D setup (launcher crashes and I'd have to do a point-by-point) but maybe something was tweaked?

not weird, the sidebar was totally changed very recently.

**Comment by Night-Pryanik** [comment] 2019-03-21 03:09
Can't reproduce on latest experimental, closing until confirmed.

**Closed by Night-Pryanik** 2019-03-21 03:09 UTC
Labels: (S1 - Need confirmation), <Bug>, Info / User Interface
