### ISSUE TITLE
Occasional Segmentation Faults when attempting to trade with an NPC follower

### ISSUE THREAD

**Issue by Voideka** [CleverRaven/Cataclysm-DDA#70374] opened 2023-12-23 03:50 UTC
### Describe the bug

On multiple occasions now, within the last few days, I have had the game segfault when attempting to trade with my NPC follower. I do not know what is causing the issue and I cannot reliably reproduce it. It happened when I had the NPC set to pick up nothing, and it continues to happen now that I have enabled their ability to pick things up. After loading the game back up following the segfault, I can access the NPC's inventory normally.

I have attached a screenshot of the trade screen in case an item in there is causing the issue.

### Attach save file

[Lilymoor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13757860/Lilymoor-trimmed.tar.gz)

### Steps to reproduce

1. Make character.
2. Recruit NPC follower for player character.
3. (e)xamine NPC, and choose (b)trade from the menu.

### Expected behavior

I expect the game to show the NPC inventory/trade screen and not segfault

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/2141044/a031f148-fd9e-4889-a842-40e88d95a78d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: c6f6397 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Voidmod [VoidMod]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13757855/crash.log)

**Comment by BrettDong** [comment] 2023-12-23 06:11
Duplicate of #70156

**Closed by BrettDong** 2023-12-23 06:11 UTC
Labels: (S1 - Need confirmation)
