### ISSUE TITLE
Inflatable boat volume and weight change when unused vs folded

### ISSUE THREAD

**Issue by PLUUZ** [CleverRaven/Cataclysm-DDA#48113] opened 2021-03-18 10:31 UTC
OS Version: OSX 10.11.6
CDDA version: E-3 OSX Curses stable and experimental  0.E-10027-g45f883c OSX curses

**Expected behavior:**
The inflatable boat can be folded and returned to the original size/volume of the item.

**Actual behavior:**
The inflatable boat item is one weight/volume when it has never been used, but if you inflate it, then fold it, the volume/weight is very different. I suppose this is due to the components of the vehicle having certain folded volumes specified.

E-3 Stable never used inflatable boat
![stable_unused](https://user-images.githubusercontent.com/30785198/111610214-006e2600-87d3-11eb-9f9e-b7e28c54d20e.png)

E-3 Stable used then folded inflatable boat
![stable_folded](https://user-images.githubusercontent.com/30785198/111610253-0d8b1500-87d3-11eb-912d-d65c34527530.png)

Experimental build never used inflatable boat
![exp_unused](https://user-images.githubusercontent.com/30785198/111610344-298eb680-87d3-11eb-85c3-4316b1e46c22.png)

Experimental build used then folded inflatable boat
![exp_folded](https://user-images.githubusercontent.com/30785198/111610460-4925df00-87d3-11eb-8b99-2d61e517342c.png)

**For reference, here are actual folded volumes and weights for a couple inflatable boat**
2 person, including oars and  hand pump
https://intexcorp.com/products/sporting-goods/sport-series-boats/seahawk-2-boat-set/
20.14 LBS = 9.14 kg
package size- 16.25in x 21.38in x 6.75in  = 2084.55 inch^3 = 34.16 Litre volume
![intexseahawk2](https://user-images.githubusercontent.com/30785198/111610670-84281280-87d3-11eb-8660-c2c4dd668ec9.png)

4 person boat including oars and pump.
 I guess the CDDA inflatable boat is 4 person becuase it's 4 tiles?
https://intexcorp.com/products/sporting-goods/sport-series-boats/seahawk-4-boat-set/
47.43 LBS = 21.5 kg
16.25in x 13.50in x 24.00in  =5265 inches^3 = 86.28 liters
![intexseahawk4_boat](https://user-images.githubusercontent.com/30785198/111611398-5099b800-87d4-11eb-930a-f908adf0ae31.png)

**Comment by jtgibson01** [comment] 2021-03-18 15:48
Yep, you've nailed the cause: the inflatable version is a vehicle-spawning item that is completely agnostic to that vehicle's stats, whereas the folded version is based on the vehicle folding code and directly derived from that vehicle's stats.

Since vehicles are modifiable and there's no way to go back to the item from the vehicle state (not without a lot of sloppy hard-coded behaviour), unfortunately, the only correct "fix" would be to redefine the inflatable version to the folded vehicle's stats, until such time as all of the vehicle parts could be carefully tuned and tweaked to have stats that are more correct.

**Comment by Fosheze** [comment] 2021-03-18 16:24
> Yep, you've nailed the cause: the inflatable version is a vehicle-spawning item that is completely agnostic to that vehicle's stats, whereas the folded version is based on the vehicle folding code and directly derived from that vehicle's stats.
> 
> Since vehicles are modifiable and there's no way to go back to the item from the vehicle state (not without a lot of sloppy hard-coded behaviour), unfortunately, the only correct "fix" would be to redefine the inflatable version to the folded vehicle's stats, until such time as all of the vehicle parts could be carefully tuned and tweaked to have stats that are more correct.

I haven't looked into vehicle code it's self at all yet but is it possible to just directly spawn the folded vehicle it's self on initial item generation rather than spawning the weird the vehicle spawning item?

**Comment by PLUUZ** [comment] 2021-03-18 17:31
Yes, the item's mass/volume could be changed to match the folded version. However, seeing that a real life inflatable boat's mass/volume is quite different than the CDDA version, it might be best to tweak the folded volumes and weights of these vehicle parts. The item length should also be updated for exp build.

There are only four parts to the inflatable boat -- inflatable section, inflatable airbag, oars, and foldable seat. The foldable seat could be left unchanged. The inflatable section/airbag only seem to be used in this particular vehicle so they could be changed without messing up much else.

Current parts (excluding foldable seat)
4x Inflatable section weight 3kg volume 0.75 L
4x Inflatable airbag weight 3kg volume 0.75 L
Oars 8kg volume 0.50 L

The inflatable section and inflatable airbags could have lower mass, and much more volume. maybe 2kg each, and folded volume of about 8 liter each.

These kits don't use normal wooden oars but flimsy telescoping aluminium/plastic ones This might warrent the introduction of an additional item/vehicle part - aluminium/plastic oars.  The foldable volume for these oars could be about 8 liter, and the weight about 1 kg.
https://intexcorp.com/products/sporting-goods/parts-accessories/48in-deluxe-aluminum-oars/

This would give you 17kg and 72L + the foldable seat (which is small) which is fairly close to the real life example of a 4 person plastic inflatable boat, especially since the CDDA version doesn't come with a pump.

**Comment by jtgibson01** [comment] 2021-03-18 21:14
@PLUUZ Oh, ha, I didn't actually look at the inflatable boat vehicle definition to see how complex it was.  I was figuring it was using xlframes and some form of boat hull -- balancing that sort of thing for mass is always sketchy because of how much it affects.  Since it's specific to the boat itself, your proposed modifications to the vehicle parts themselves definitely get my vote, with a final tweak to the inflatable boat tool to reflect the result.  A comment should probably be stuck into both JSON files to hint that they should always be verified against each other (since a unit test in the code itself would probably be overkill for such a specific scenario).

@Fosheze That'd actually have to be a new option in the itemgroup/spawning code, although I'm not sure what exactly it would entail.  Certainly seems doable on the face of it, though!

**Comment by PatrikLundell** [comment] 2021-03-19 09:03
You can't put comments in JSON files because the creator tossed out the baby with the bath water in annoyance over someone "abusing" comments for machine readable instructions (You can, however, clutter the memory with "data" fields actually containing what should have been comments. I think "//" is the typical work around)...

**Comment by jtgibson01** [comment] 2021-03-19 15:58
`"//": "blah"` style comments are already routinely used in DDA source data.  I'm quite aware of this. ;-)

**Comment by PLUUZ** [comment] 2021-03-22 09:03
Er, just to followup since I'm not too clear on the expectations and procedures of the repo. I  assumed I should just wait for whoever is in charge of boats and boat related matters to take a look at this and decide what, if anything, they choose to do about it, since they might have other plans for the items and vehicle parts.  Or am I expected to make these changes myself to the vehicle_parts.json and deployable.json becuase I suggested them? Thanks in either case.

**Comment by jtgibson01** [comment] 2021-03-23 00:18
@PLUUZ Your initial assumption was right!  It's up for grabs to anyone who wants to do it; you can do it if you like, or anyone with an interest can jump in and create a fork, commit, and PR -- or mlangsdorf or I-Am-Erk (the de facto fellows in charge of vehicle stuff) might get around to it when looking for quick and easy fixes in the final run up to 0.F.  It's just one of those things that's so easy to do that the Github UI kludge is overpowered for and works against anyone that doesn't have a synched fork already open.  If you're willing to put in the three minutes, it'd definitely be happily merged in.  (I've probably spent more time chatting about this than it would have taken to fork/commit the tweaks myself... which goes to show how much I hate forking, committing, and deleting repositories, I guess. ;-))

**Closed** 2022-08-17 09:38 UTC
Labels: <Bug>, Vehicles, Items / Item Actions / Item Qualities
