### ISSUE TITLE
Character's limbs spawning almost broken

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#41609] opened 2020-06-26 17:18 UTC
# Describe the bug

After choosing making a character I start with several limbs about to break.

# Steps To Reproduce

1. Make a character with the exact perks in the screenshot
2. Spawn into a world

# Expected behavior

My head, torso, left arm, and left leg shouldn't be close to breaking on a new character.

# Screenshots

![Screenshot (1777)](https://user-images.githubusercontent.com/56947231/85883296-b778da80-b81b-11ea-9424-894a563b702f.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-3531-gff1ff7e
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Magiclysm

# Additional context

I also lose my quarterstaff when starting as a wizard for some reason.

**Comment by anothersimulacrum** [comment] 2020-06-26 22:25
Cannot reproduce. Can yo give more information?

**Comment by UndeadMoose** [comment] 2020-06-26 22:50
> Cannot reproduce. Can yo give more information?

Sure

I tested it further and I'm doubting it is Magiclysm causing it

![Screenshot (1806)](https://user-images.githubusercontent.com/56947231/85906630-d68e6100-b849-11ea-9462-89e54e67a9d5.png)

These combination of perks seems to be causing it and I can't tell which one is causing the problem.

[Aripine.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4839491/Aripine.zip) 

I included a save.

**Comment by wapcaplet** [comment] 2020-06-26 23:45
I saw this occur earlier today, and can still reproduce it in 0.E-3531. It happens when I use a character template saved in an earlier version of the game, but not when I create a new character from scratch (or from a template saved in the same version).

My character template called "The Dude" has this problem. Zip file: [dude-templates.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4839642/dude-templates.zip)

When starting a new world (no mods) with a new character from "The Dude" template (simple Backpacker profession with "Self Aware" trait), the left arm and leg, head and torso have almost no health after spawning in the evac shelter:

![image](https://user-images.githubusercontent.com/238395/85908772-c9cf2600-b7d3-11ea-9493-395d3a790fcc.png)

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3531-gff1ff7ea9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by anothersimulacrum** [comment] 2020-06-27 00:05
Ah, that would explain it, character templates.

**Comment by ZhilkinSerg** [comment] 2020-06-27 06:13
Quarterstaff should be marked as autowield as it is too long to fit in any of the pockets.

**Comment by EvgenijM86** [comment] 2020-06-27 08:13
This happened to me by just starting the game with default mods and latest git pull. In a mi-go camp starts mi-go will kill you in 2-3 hits with this bug, even with a tough trait and full health bars.

**Comment by Fris0uman** [comment] 2020-06-27 08:22
It's a side effect of #41194 When the template is loaded it loads its hp which was 1 because the template is saved before calling relac_hp and it's not affecting all limbs because the part that loads legacy save was missing some limbs.

**Comment by ZhilkinSerg** [comment] 2020-06-27 08:22
> This happened to me by just starting the game with default mods and latest git pull. In a mi-go camp starts mi-go will kill you in 2-3 hits with this bug, even with a tough trait and full health bars.

If you started game using template it is the same bug.

**Comment by EvgenijM86** [comment] 2020-06-27 08:41
Yes, it was template that I created some time (3+ month ago). Should I re-create it to avoid reporting bugs from old-format templates? Or do you want those reported? (if any exists)

**Closed** 2020-06-27 08:44 UTC
Labels: (S2 - Confirmed), <Bug>, Character / World Generation

**Comment by ZhilkinSerg** [comment] 2020-06-27 08:54
We will support older templates (at least until next stable). Try upcoming build.
