### ISSUE TITLE
River banks are not generated in some cases

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#42190] opened 2020-07-16 14:55 UTC
# Describe the bug
River banks are not generated in some cases.

# Steps To Reproduce
Generate a world that has river across different overmap segments, like in the screenshot bellow.

# Expected behavior
River across overmap segments to be generated correctly.

# Screenshots
![image](https://user-images.githubusercontent.com/430076/87686378-f42d5700-c773-11ea-99f8-e12ba303522c.png)

# Versions and configuration
Manjaro Linux. Latest git pull at the time of writing this & mods that are enabled by default.

# Additional context
Save File:
[Vortex2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4932228/Vortex2.zip)

**Comment by ZhilkinSerg** [comment] 2020-07-16 16:58
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/36630

Maybe someone would eventually resurrect https://github.com/CleverRaven/Cataclysm-DDA/pull/38894 or start from scratch.

**Closed by ZhilkinSerg** 2020-07-16 16:58 UTC
