### ISSUE TITLE
Crash on sleeping after updating to 11022

### ISSUE THREAD

**Issue by Sylirae** [CleverRaven/Cataclysm-DDA#44312] opened 2020-09-21 12:38 UTC
# Describe the bug

Consistent crash when attempting to sleep in survivor's militarized RV after updating to experimental 11022.

# Steps To Reproduce

1. Load provided save
2. Attempt to sleep in vehicle bed.
3. Crash

# Expected behavior

Successful sleep, no crash.

# Screenshots

No screenshots.

# Versions and configuration

GAME REPORT:
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6130-gb825e3a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Tankmod: Revived [Tankmod_Revived],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[sleep crash logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5255348/sleep.crash.logs.zip)
[Selbyville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5255358/Selbyville.zip)

**Comment by Sylirae** [comment] 2020-09-21 12:48
Adding specific versions of tankmod and cata++ for ease of testing. Crash does not occur when sleeping on second floor of nearby military helipad.

[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5255410/mods.zip)

**Comment by ZhilkinSerg** [comment] 2020-09-21 12:49
Attached savegame archive is broken and need to be reuploaded.

**Comment by Sylirae** [comment] 2020-09-21 12:51
Reupload.
[Selbyville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5255420/Selbyville.zip)

**Comment by ZhilkinSerg** [comment] 2020-09-21 13:26
The crash is related to NPC attempt to wield a better weapon and can be more easily reproduced by waiting in a place with multple NPC around (like refugee center).

**Comment by anothersimulacrum** [comment] 2020-09-21 14:37
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/44196?

**Comment by linonetwo** [comment] 2020-09-22 05:13
How can you use 11022? Seems its build is broken https://ci.narc.ro/job/Cataclysm-Matrix/11023/Graphics=Tiles,Platform=OSX/console

**Comment by ZhilkinSerg** [comment] 2020-09-22 06:02
> How can you use 11022? Seems its build is broken https://ci.narc.ro/job/Cataclysm-Matrix/11023/Graphics=Tiles,Platform=OSX/console

They are on Windows.

**Comment by hexagonrecursion** [comment] 2021-08-29 14:54
> Duplicate of #44196?

Looking at the backtraces: seems completely unrelated.

**Comment by hexagonrecursion** [comment] 2021-08-29 15:55
Could not reproduce with clang address and undefined behavior sanitizers. Note: the mods posted above are unfortunately incompatible with ada3852d39
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No name () [],
    No name () [],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Closed** 2021-09-11 14:10 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed)
