### ISSUE TITLE
NPC allies should help fight off hostile NPC's

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#14054] opened 2015-11-16 07:00 UTC
Currently, even if they are your followers, NPC's will not attack another NPC, even if it is hostile and attacking you. Even if you get the hostile NPC to attack your followers by taking cover behind them, they will not engage.

This would be an important part of NPC interactions as building a small group of survivors should grant you some degree of protection against hostile scavengers.

**Comment by OzoneH3** [comment] 2015-11-17 13:28
Duplication of #14054

**Comment by narc0tiq** [comment] 2015-11-17 16:26
Think you meant dupe of #13689 or #12506. Given the two of those, we can certainly close this one.

**Closed by narc0tiq** 2015-11-17 16:26 UTC
Labels: Duplicate
