### ISSUE TITLE
Circular Saw Battery Consumption

### ISSUE THREAD

**Issue by Nierfenhimer** [CleverRaven/Cataclysm-DDA#50023] opened 2021-07-18 12:23 UTC
### Describe the bug

When utilising a circular saw, no matter what the charge of a current battery, if above 0 the saw will produce the same results when cutting logs into planks and consume the entire battery while only cutting one log. Waiting for 5 minutes with it in the (on) state will nearly full-deplete a single medium battery, making this power tool either virtually useless or broken in its current state, as a battery with 1 charge will produce the same results with it as a battery with 1000 charge.

### Steps To Reproduce

1. Obtain logs, a circular saw, and multiple medium batteries for it with different levels of charge between 1 and maximum.
2. Turn circular saw on with a maximum charge battery loaded.
3. [A/a]ctivate the saw and select [2 Cut a log into planks].
4. Observe fully-depleted battery.
5. Switch depleted battery with one of less charge.
6. Repeat steps 3-4.
7. Switch depleted battery with one more at full charge.
8. Wait for 5 in-game minutes.
9. Observe rapid battery depletion.

### Expected behavior

A circular saw, being a power tool, would be expected to be immensely more practical than sawing logs by hand, and with a battery used in certain welders - tools which have, one could expect, a much more powerful output - to repair multiple components of a vehicle before needing a new battery (and being based on charge rather than merely checking if there is charge at all and letting time do its thing instead) used to power the tool, it would be expected to last either more than one use or none at all unless at full charge.

### Versions and configuration

- OS: Windows 10 Pro V20H2 OS Build 19042.1110 Feature Pack 120.2212.3530.0
- Game Version: 9f0d77d
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA

**Comment by RoyBerube** [comment] 2021-07-18 14:32
The code for cutting lumber versus chopping down a tree is inconsistent. Chopping down a tree takes the tool quality and assistants into account to adjust the time spent. This makes sense. Cutting lumber is a flat 20 minutes with no adjustments for tool quality or assistants.

I think if we adjust the cutting time by tool quality it will make a big difference. Circular saw quality should also get bumped up from 2.

Another irregularity is if the charge runs out before the activity is finished, the activity still succeeds.

**Comment by wapcaplet** [comment] 2022-01-16 05:50
Possible duplicate of #48089

**Comment by RenechCDDA** [comment] 2023-07-01 11:12
Duplicate as noted above

**Closed by RenechCDDA** 2023-07-01 11:12 UTC
Labels: <Bug>, (S3 - Duplicate), Items: Battery / UPS
