### ISSUE TITLE
In-progress food crafts disappear when there is a dog nearby

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#49558] opened 2021-07-04 01:24 UTC
On several occasions when I have been crafting food items while there is a friendly dog nearby (leashed or not), while in the middle of crafting, I get the message that I'm no longer holding the in-progress item and I should reactivate it. The item no longer exists anywhere though.

To replicate it I've included my save file where after the save I started craft 5x meat jerky as normal while there is a friendly dog nearby, see for yourself. Doesn't happen 100% of the time with short crafts but at least these kind of long crafts seem to always trigger this bug.

Mind you this never happens when I tie the dog away (at least when out of sight further away) so it's somehow tied to the dog.
Is my dog just that hungry that he eats whatever I'm cooking? :p

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5187-gb60a422 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]

[Willowgrove.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6759238/Willowgrove.zip)

**Comment by anothersimulacrum** [comment] 2021-07-04 01:47
Looks like a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45343. Can you reproduce this with more recent versions of the game?

**Comment by RosaEscura** [comment] 2021-07-04 02:04
Yeah seems to be the same issue, my report adds a save file where it can be replicated easily but if you think it's irrelevant you can close this issue.
I'm not looking to update my game until I start a new run.

**Comment by hexagonrecursion** [comment] 2021-08-17 18:23
Could not reproduce
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: b34a0f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Closed** 2021-08-17 20:28 UTC
Labels: (S1 - Need confirmation)
