### ISSUE TITLE
Stabbing followers with spears

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#36514] opened 2019-12-28 16:17 UTC
# Describe the bug

If you press TAB while welding a reach weapon, you will attack non-adjacent allies within reach.

# Steps To Reproduce

1. Make a spear
2. Make a friend
3. Keep your friend at arms-length
4. Press tab to stab (your friend)

# Expected behavior

Don't stab your friends, no matter how much they may deserve it.

**Comment by EirenexTheDragon** [comment] 2019-12-28 17:21
it will target the ally only when there is no other enemy to target instead. though it shouldnt ever target the ally, (which it still does when rangeattacking past him with a pike)

**Comment by Zourin2** [comment] 2019-12-29 06:31
This is a problem, since you can "OOPS" a companion to death a very small number of turns if you are in the middle of a zombie-trash swarm and just hold down the tab key to clear things out.

**Comment by Night-Pryanik** [comment] 2020-01-05 06:39
Duplicate of #36375.

**Closed by Night-Pryanik** 2020-01-05 06:39 UTC
