### ISSUE TITLE
Collision(you hear smash!) spam in hospital basement.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#45306] opened 2020-11-08 18:22 UTC
# Describe the bug
Massive slowdown due to unexpected collision of pre-generated objects

Upon entering hospital area, half of 1 tile bed appeared inside the metal wall while spamming 'you hear smash' event in log, slowing down game to a crawl. It didnt stop once i moved the bed via Grab, so it may be another issue in the same area.
# Steps To Reproduce

Unsure if can reproduce, savegame attached.

[Northern Tyris.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5506939/Northern.Tyris.zip)

# Expected behavior
No smashes.

# Screenshots

![smash](https://user-images.githubusercontent.com/25095102/98478748-03934d00-2208-11eb-867c-a23c09f05cea.jpg)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.E-7353-g967d80c]
 - Graphics version: [Tiles]
 - Ingame language: [English]
 - Mods loaded: 
![mods](https://user-images.githubusercontent.com/25095102/98478020-c8911980-2207-11eb-9a6f-8bfdaa02df83.jpg)

# Additional context
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5506940/debug.zip)

**Comment by ZhilkinSerg** [comment] 2020-11-08 18:56
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/44265

**Closed by ZhilkinSerg** 2020-11-08 18:56 UTC
