### ISSUE TITLE
Collapsed tower quest object destroyed

### ISSUE THREAD

**Issue by JantDarvus** [CleverRaven/Cataclysm-DDA#54252] opened 2022-01-10 17:14 UTC
### Describe the bug

On clearing the collapsed tower dungeon, I found (and confirmed with a debugged in clairvoyance artifact) that the quest item was gone. As far as I can tell, the Talon robot in the room - despite seemingly being alone - had decided to smash up the entire place and destroyed everything in sight, including said quest item. Whatever the cause, I'm guessing that the quest item just being gone, making the quest unwinnable, is unintended.

### Steps to reproduce

I'm not sure if this is necessarily reproducible since I don't know if the robot does this every time or just went berserk in my game. Nonetheless, I suppose just go to the collapsed tower dungeon and wait around in the lower floor for a bit before checking to see if the robot has wrecked the place or, possibly, if the quest item was just missing to begin with.

### Expected behavior

For the quest item to not be destroyed?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GoLoT** [comment] 2022-01-10 18:04
Duplicate of #54239

**Comment by leemuar** [comment] 2022-01-10 19:35
yep, experienced it too

**Comment by coyo7e** [comment] 2022-01-10 22:12
I've run into this with "open air" spaces a lot recently, which seem to instantly kill enemies that walk into them, eat items, etc.. I even reloaded while standing near a "open air" space the other day and for some reason the game covered the entire area in dirt squares! I climbed down into an open air area and it seemed to be an unlimited space and I quickly drowned since I was standing near water.

Poissibly related, I also started as "helicopter crash" scenario yesterday and was attacked by 5 or 6 zombies which were standing on a damaged (NOT open air) section, and after defeating them, I went to loot and there was only a single, empty corpse there.

**Comment by LeahLuong** [comment] 2022-01-11 02:34
@coyo7e I think you meant to post in #53549 . . .

**Comment by PatrikLundell** [comment] 2022-01-11 08:05
I've had the complete absence of the quest object in 0.E2 stable, but don't remember any Talon at that time. Verified the absence both by digging up the place and by scouring the save file. Ended up debug spawning the item.

**Comment by wapcaplet** [comment] 2022-01-16 15:58
Closing as duplicate of #54239

**Closed by wapcaplet** 2022-01-16 15:58 UTC
Labels: <Bug>, (S3 - Duplicate), Missions
