### ISSUE TITLE
Error in mission 'Find Source of Robots' and NPCs placed at wrong Z levels.

### ISSUE THREAD

**Issue by MikasaTanikawa** [CleverRaven/Cataclysm-DDA#75424] opened 2024-08-03 19:31 UTC
### Describe the bug

Attempt to start 'Find Source of Robots' mission gives this error:
```
DEBUG    : Unable to find and assign mission target exodii_base_x0y3z0.

 FUNCTION : std::optional<coords::coord_point_ob<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&, dialogue&)
 FILE     : src/mission_util.cpp
 LINE     : 258
 VERSION  : cdda-experimental-2024-08-03-0533 1c140ab

```
Exodii castle wasn't visited before but it's position revealed after starting 'Check out that scrap metal castle'.

Also Rubik spawns outside his room in castle.

### Attach save file

[Exodii_World-trimmed.tar.gz](https://github.com/user-attachments/files/16482615/Exodii_World-trimmed.tar.gz)

### Steps to reproduce

1. Load save, talk with Representative.
2. Take new job and get error.
3. Reach Exodii castle, see Rubik outside his room.

### Expected behavior

Rubik inside, error outside.

### Screenshots

![Mikasa Tanikawa _2024-08-03T22-22-14](https://github.com/user-attachments/assets/b3137821-976c-4549-b690-cee3a3d468c4)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: cdda-experimental-2024-08-03-0533 1c140ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/16482604/debug.zip)

**Comment by MikasaTanikawa** [comment] 2024-08-04 10:18
Oh, and Luliya spawns at ground level too, so it probably related to #75428 and #75244.

**Comment by MikasaTanikawa** [comment] 2024-08-04 13:23
Tried different builds and last time NPCs spawned at correct Z levels was before #74169
@PatrikLundell

**Comment by PatrikLundell** [comment] 2024-08-04 15:51
I can verify the error message is produced, but not the rest.

Teleporting to the location given by the scrap metal fortress quest landed me in the middle of a race track on the first attempt (still fulfilling the quest), after having talked to the representative, and in a forest (again fulfilling that quest) without talking to the representative on the second attempt.

I've teleported to the Exodii castle (seen in the distance, but verified not to have been inside the reality bubble by checking the exclusion regions shown when trying to debug place special terrain), and walked to Rubik's office, where he was present. I didn't search out Luliya.

It can be noted that #74169 had some serious bugs which have since been fixed and merged (at least those identified).

Without the ability to get to the castle in your save I'm unable to investigate anything. Note that #74169 deals with the generation of actual terrain (typically as it comes into the reality bubble, but there are a few other cases as well), so the placement of the castle in general is unrelated (the placement info is what the reality bubble generation uses as input.

If you're able to get a save where you can see the castle on the overmap but at a distance too large to have been touched by the reality bubble (basically more than 3 overmap tiles away) it would provide a starting point for an investigation (assuming, of course, characters end up in the wrong place at that time as well).

**Comment by MikasaTanikawa** [comment] 2024-08-04 18:21
Oh, it was too far away and trimmed from save.
Here castle on the south: [Exodii_Castle2-trimmed.tar.gz](https://github.com/user-attachments/files/16488561/Exodii_Castle2-trimmed.tar.gz)

**Comment by PatrikLundell** [comment] 2024-08-04 20:41
/Confirmed

Thanks!
This allowed me to track down the bug.

**Closed** 2024-08-05 03:46 UTC
Labels: (S2 - Confirmed)
