### ISSUE TITLE
Crash when attempting to access achievements

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71508] opened 2024-02-04 22:41 UTC
### Describe the bug

My game crashed when I tried to view my achievement page. 

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14158755/Earth-trimmed.tar.gz)

### Steps to reproduce

I'm not sure why it crashed because I've been able to access my achievements without issue previously on the same save. However, I've been able to reproduce it with the attached save file. 
1. Press `enter`
2. Press `6`
3. Press `1` Here some error is thrown, but it doesn't crash. 
4. Press `v` At this point, you should see a broken achievement page, with 28 days later in the middle and no other achievements shown. 
5. Press `esc` and the game should crash

### Expected behavior

I did not expect the game to crash. My ultimate goal was to check my kill count, if there is a shortcut for that while this is being patched, please let me know. 

### Screenshots

Here is the broken screen at step 4. 
![Screenshot (338)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/9c974a16-f8e5-439e-9ef8-269ae306c8ca)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash&debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14158744/crash.debug.zip)

**Comment by Qrox** [comment] 2024-02-05 03:33
Probably related to #71327?

**Comment by ZeroInternalReflection** [comment] 2024-02-05 03:41
I've had no luck reproducing the crash.  The debug message on opening the diary is about mission tracking, which while not _good_, does not appear to be causing the crash.  In my testing, the "28 days later" achievement was already completed, and the other screens were accessible (screenshots included mostly because @DragonWizard23 mentioned wanting to see)
![Achievements_UI](https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/4358539d-e8cc-4247-b644-25f69957b945)
![Scores_UI](https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/62d3e7fe-c67f-45e3-a0d2-5cca3b761adf)


>Probably related to https://github.com/CleverRaven/Cataclysm-DDA/pull/71327?

Isn't the OP's version from before this PR was merged?  Who knows, we might have gotten lucky and it's already fixed.

**Comment by DragonWizard23** [comment] 2024-02-05 05:32
@ZeroInternalReflection Thanks for trying to replicate it. My save is from before that version, ~~perhaps it is already fixed~~. 
I've updated to the latest experimental and was able to replicate the crash. I tried saving the game, then reopening it (in case #71327 needs a save on the latest version to work) but still got the crash. (Intriguingly, it appears the hotkey for info is now 8 instead of 6.)

Here is the crash message I'm getting, should I post a new crash and debug log?
![Screenshot (341)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/c5714249-2adf-4357-8f69-83a2bc81c8dc)

**Closed** 2024-02-07 03:39 UTC
Labels: (S1 - Need confirmation)
