### ISSUE TITLE
Various small Commune bugs

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#20862] opened 2017-04-18 03:50 UTC
* [x] The Commune does not spawn a bartender, even when the respective mission is completed. (Fixed by #29473)
* [ ] The Commune "missions" (in which you send people on them) displays archery and piercing randomly while nothing is happening (for example, the message box will spam the words "archery" or "piercing" each tick, until combat happens, in which the message will play normally.
* [x] You are unable to invest in the commune farms 

I'm fairly confident the first two are bugs, and the third issue, i'm not sure It got implemented, or if any of this was implemented at all, so please somebody correct me if I got something wrong

Edit by @Leland: moved to checklist

**Comment by Lord-Helmchen** [comment] 2017-05-18 20:37
Finally my Survivor made the trip back to the Commune, so I have a save, right in front of the Crop Overseer.
(on a sidenote: I seem to remember that there were multiple jobs for your followers available from the foreman, but nowadays there's only the caravan to the refugee center. Am I misremembering, or have the other missions been cut (temporarily) ?

Alas, somehow github says "something went really wrong, and we can't process that file" ... any advice? filesize is 7.1 MB, z7 compressed *and then renamed to .zip) ... can and should the save be stripped down to only the essential parts?

**Comment by Leland** [comment] 2017-05-18 20:41
@Lord-Helmchen if you can't upload to GitHub, http://ge.tt/ is a good, free alternative.

**Comment by Lord-Helmchen** [comment] 2017-05-18 22:15
ok, there it is (for the next 30 days, that is)
hope it helps :)

**Comment by Lord-Helmchen** [comment] 2017-05-18 22:46
oh my... *headdesk* I probably should have pasted the link X-P
http://ge.tt/44Dwo9k2

**Comment by Leland** [comment] 2017-05-23 20:16
RE: the bartender, #18679 said:

> After today mission tests I've ended up with the Ranch missing the Bartender NPC, so I can't really test brewery missions correctly... The code is in ranch_construct_16 and there are some weird checks for the case if Bartender is already there (what? how?)
>
> And the Barber NPC that should appear in the barn appeared in the barn on the other ranch in the adjacent region of the map to the north... That region of the map was not even revealed before... The code is in `ranch_construct_13`
>
> (I agree, mission/NPC code is a mess)
>
> I forgot to note that it happens in version 5640, 0.C-18991-g142f3fd (tiles) after commit "Fix NPCs spawning in wrong places"...

So, looks like it might be related to #18576

**Comment by int-ua** [comment] 2021-01-14 03:12
Please update the description to reflect current status.

**Comment by hexagonrecursion** [comment] 2021-08-11 09:58
> The Commune does not spawn a bartender, even when the respective mission is completed.

This part of the issue is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/27738. Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/29473 please update the description - two bugs down, one to go.

**Comment by hexagonrecursion** [comment] 2021-08-11 15:53
I can not reproduce the last of the three bugs
I tested the following missions
* Caravan Commune-Refugee Center
* Scavenging Patrol
* Scavenging Raid
* Forage for Food
As far as I can tell this four are the only ones with combat

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by I-am-Erk** [comment] 2021-12-15 16:22
Closing as stale given changes in this code since this time

**Closed by I-am-Erk** 2021-12-15 16:22 UTC
Labels: NPC / Factions, (S1 - Need confirmation), Missions
