### ISSUE TITLE
don't treat tables as crafting tables unless the user designates the table as such

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#30226] opened 2019-05-04 07:34 UTC
**Is your feature request related to a problem? Please describe.**  

Current behavior is that [e]xamining a table shows the "What to do at the table" menu that includes "Get items." When you're looting a building, each table you [e]xamine for loot requires an additional menu selection before you can select items to pick up. This extra step is not optimal. 

**Describe the solution you'd like**  

1. Introduce a "mark crafting location" command to the construction menu that lets the user set a flag on a particular square.

2. If the user [e]xamines a table located in a square marked as a crafting location, display the crafting menu. The crafting menu includes a "remove crafting location" choice that causes the crafting location flag to be removed from the square.

3. If the user [e]xamines a table not marked as a crafting location, display the list of items on the table.

**Comment by kevingranade** [comment] 2019-05-04 07:52
Duplicate of #30217

**Closed by kevingranade** 2019-05-04 07:52 UTC
