### ISSUE TITLE
Reloading partially loaded tools not working correctly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14454] opened 2015-12-16 22:10 UTC
Not sure what does it depend on.
It seems not to understand held ammo (for example, large stack of batteries in hand).
Sewing kit isn't accepting sinew and plant fiber, but accepts thread.

**Comment by Coolthulhu** [comment] 2015-12-19 20:44
Update: partially loaded tools seem to be handled all wrong.
* Spawn a welder
* Spawn battery
* Load welder partially
* Spawn more batteries
* Try loading welder

Result: "Out of batteries"
Unloading the welder will allow loading it.

**Comment by mugling** [comment] 2015-12-19 23:28
I can't reproduce this on FreeBSD using ba984ee

**Comment by mugling** [comment] 2015-12-20 00:27
> It all seems to be related to item detection. Possibly something like mismatched ids like ammo type ids vs item type ids.

Possibly somewhere in `item::pick_reload_ammo`?

**Comment by mugling** [comment] 2015-12-20 00:58
It's difficult to test an issue that I can't reproduce.

Within `item::reload` remove the conditional so that:

`if( target->is_gun() || target->is_gunmod() ) { target->set_curammo( *ammo ); }`

becomes:

`target->set_curammo( *ammo )`

**Comment by rluddy** [comment] 2015-12-20 01:14
This may only be the case on tools from old saves. Newly-spawned ones work fine for me.

Fully unloading them allows them to be reloaded normally, but they cannot be reloaded further unless they are empty. It gives the "Out of thread!" message on a tailor's kit when this occurs, for example when trying to reload 100 into a tailor's kit that had 6 in it. The same issue with duct tape and basic repair kits.

Some quick checking in the debugger looks like something to do with curammo being incorrect on legacy tools in a way that doesn't get fixed by unloading them, but I'm not familiar enough with the system to be sure exactly what way.

**Comment by rluddy** [comment] 2015-12-20 01:58
I tried making a new save from a week-old build and then testing that save in latest, but didn't encounter the issue. That's about when I started my current game so my assumption it was related to legacy saves may not be correct.

Afterwards, after backing up my main game (which is seeing the issue) I tried the suggestion of removing the conditional within item::reload. While it still had the issue initially, after unloading and reloading the tool once it was then possible to reload the partially-full normally.

It may be that the issue only applies to tools created within a certain narrow range of builds and possibly with something additional done to them during them, but the workaround seems to work.

**Comment by rluddy** [comment] 2015-12-20 03:36
Something continues to go bad on tools after a while. I haven't come upon consistent repro steps yet, but I think it has something to do with leaving the map or save/load.

With the item::reload change mentioned above, the tailor kit that works fine with any number of partial reloads after first fully unloading it, but that same tailor kit gets the same issue with "Out of thread!" on partial loads a while later after I've done a lot of things (including traveling a good distance away from the tailor kit left in my base).

**Comment by kevingranade** [comment] 2015-12-20 16:32
Need confirmation that these changes did the trick.

**Comment by rluddy** [comment] 2015-12-20 20:13
I've since played through a full season doing all kinds of stuff with legacy tools and only had that one incident of an already-fixed legacy tool going bad again, so it's starting to feel like that one time might have been user error - me not realizing I was using a different tool or unintentionally playing on the wrong build.

**Comment by Night-Pryanik** [comment] 2016-02-27 19:00
Seems like reloading partially loaded tools is working ok, at least on win 10, tiles and curses, 0.C-4481.

**Comment by mugling** [comment] 2016-02-27 19:08
Consider closed?

**Comment by Night-Pryanik** [comment] 2016-02-27 19:09
Yeah, I think it should be.

**Comment by mugling** [comment] 2016-03-07 10:27
@Coolthulhu suspect this is resolved by now. I'm going to extend the unit tests to cover the scenario at at the start of this issue.

**Closed** 2016-04-23 20:23 UTC
