### ISSUE TITLE
When I attempt to heat solids using the kitchen, the game crashes.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#74310] opened 2024-06-04 13:35 UTC
### Describe the bug

The game crashes when I attempt to heat frozen bread from my backpack using the kitchen connected to the power grid.

### Attach save file

[Uploading DDA-trimmed.tar.gz…]()

### Steps to reproduce

1Select the kitchen, then choose and use any of its integrated components capable of heating solid foods.
2.Click to Heat Solid.
3.The game crashes.

### Expected behavior

"I wish to be able to heat food normally using the kitchen.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 459ec63 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    <color_cyan>奥术与魔法物品</color> [Arcana],
    <color_light_blue>BL9-100%-怪物耐性版</color> [BL9_100monres],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ 传说扩展包</color> [secronom_lore_expansion],
    大魔法 [magiclysm],
    萌化计划 [ProjectKawaii],
    热带大灾变 [tropicata],
    生化职业 [package_bionic_professions],
    心胜于物 [mindovermatter],
    更多幸存者工具补充包 [MST_Extra],
    烹饪余生 [culinary_days_ahead],
    皮克索的各种操蛋玩意 [Pix's Shit],
    中世纪扩展 重生 [Medieval_Mod_Reborn],
    <color_cyan>奥术</color>/<color_light_green>Cata++</color> 兼容补丁 [Arcana_Cata++_Patch],
    <color_cyan>奥术</color>/大魔法 兼容补丁 [Arcana_Magiclysm_Patch],
    <color_light_blue>减轻疲惫程度</color> [light_weariness],
    神话武术 [MMA],
    <color_yellow>神话武术扩展</color> [MMA_Mods_Extension],
    疯狂大灾变 [crazy_cataclysm],
    更多变异场景 [extra_mut_scens],
    矿物勘探 [Mining_Mod],
    特色升级能力 [bombastic_perks],
    替换小地图图标 [alt_map_key],
    甜蜜大灾变 [my_sweet_cataclysm],
    吸血鬼 [vamp_stuff],
    吸血鬼+奥术扩展 [vamp_stuff+arcana],
    地下世界 [Dorf_Life],
    铁路 [railroads],
    坦克扩展 重生 [Tankmod_Revived],
    载具增强包 [blazemod],
    大魔法数值翻倍 [magicrevamp],
    翻译晦涩对话 [translate_dialogue],
    状态图标，retrodays版 [sees_player_retro],
    鲸鱼发型与纹身店 - 0.G [WHALEYHAIR1],
    发现玩家图标，HitButton_iso版 [sees_player_hitbutton],
    <color_pink>追加 - ボイロ</color> [VOICEROID_mod],
    东方职业模组 [Touhou],
    东方职业模组扩展包 [Touhou_expansion],
    <color_pink>召唤 - ボイロNPC</color> [NPC_kiritan],
    技能提升属性 [StatsThroughSkills],
    耐贮品检修 [Nonperishable_Overhaul],
    杀怪提升属性 [stats_through_kills],
    驯服野兽 [Tamable_Wildlife],
    移除生化槽位 [no_cbm_slots],
    XEDRA 超进化 [xedra_evolved],
    余波未尽 [aftershock],
    <color_cyan>奥术</color>/余波未尽 兼容补丁 [Arcana_aftershock_Patch]
]

**Comment by IoIqq** [comment] 2024-06-04 13:37
[Uploading DDA-trimmed.tar.gz…]()

**Comment by IoIqq** [comment] 2024-06-04 13:40
[Uploading DDA-trimmed.tar.gz…]()

**Comment by IoIqq** [comment] 2024-06-04 13:43
[DDA-trimmed.tar.gz](https://github.com/user-attachments/files/15552352/DDA-trimmed.tar.gz)

**Comment by harakka** [comment] 2024-06-04 16:48
Closed as duplicate of #73657

**Closed by harakka** 2024-06-04 16:48 UTC
Labels: (S1 - Need confirmation)
