### ISSUE TITLE
Game will crash (Abnormal Termination) when tabbing to the "BACKGROUNDS" section of character creation

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#53430] opened 2021-12-13 20:12 UTC
### Describe the bug

I am unable to create a new character because my game crashes each time i reach the "BACKGROUNDS" section of character creation

### Steps to reproduce

1. Enter the Character Creation Menu
2. Tab to the "BACKGROUNDS" section 

### Expected behavior

I expected to open up the backgrounds section. instead my game crashed.

### Versions and configuration

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 8b7a449
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x7ff7256ee36f[cataclysm-tiles.exe+0x1de36f]), 
    (libbacktrace: register_frame_ctor+0x7ff5e4181e1f@0x7ff7256ee36f),
    (libbacktrace: 0x7ff7256ee36f    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7256d7f81[cataclysm-tiles.exe+0x1c7f81]), 
    (libbacktrace: register_frame_ctor+0x7ff5e416ba31@0x7ff7256d7f81),
    (libbacktrace: 0x7ff7256d7f81    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7256d81af[cataclysm-tiles.exe+0x1c81af]), 
    (libbacktrace: register_frame_ctor+0x7ff5e416bc5f@0x7ff7256d81af),
    (libbacktrace: 0x7ff7256d81af    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x21b@0x7ffb484badfb[msvcrt.dll+0x2adfb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ffb484bf1fb[msvcrt.dll+0x2f1fb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x7ff725c30630[cataclysm-tiles.exe+0x720630]), 
    (libbacktrace: register_frame_ctor+0x7ff5e46c40e0@0x7ff725c30630),
    (libbacktrace: 0x7ff725c30630    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: @0x7ff725b807cf[cataclysm-tiles.exe+0x6707cf]), 
    (libbacktrace: register_frame_ctor+0x7ff5e461427f@0x7ff725b807cf),
    (libbacktrace: 0x7ff725b807cf    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x7ff725b8cfeb[cataclysm-tiles.exe+0x67cfeb]), 
    (libbacktrace: register_frame_ctor+0x7ff5e4620a9b@0x7ff725b8cfeb),
    (libbacktrace: 0x7ff725b8cfeb    [unknown src]:0    [unknown func]),
  #8
    (dbghelp: @0x7ff725df4ef9[cataclysm-tiles.exe+0x8e4ef9]), 
    (libbacktrace: register_frame_ctor+0x7ff5e48889a9@0x7ff725df4ef9),
    (libbacktrace: 0x7ff725df4ef9    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff725b9529d[cataclysm-tiles.exe+0x68529d]), 
    (libbacktrace: register_frame_ctor+0x7ff5e4628d4d@0x7ff725b9529d),
    (libbacktrace: 0x7ff725b9529d    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff725b9b2a0[cataclysm-tiles.exe+0x68b2a0]), 
    (libbacktrace: register_frame_ctor+0x7ff5e462ed50@0x7ff725b9b2a0),
    (libbacktrace: 0x7ff725b9b2a0    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff7259e073b[cataclysm-tiles.exe+0x4d073b]), 
    (libbacktrace: register_frame_ctor+0x7ff5e44741eb@0x7ff7259e073b),
    (libbacktrace: 0x7ff7259e073b    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff7259e2f03[cataclysm-tiles.exe+0x4d2f03]), 
    (libbacktrace: register_frame_ctor+0x7ff5e44769b3@0x7ff7259e2f03),
    (libbacktrace: 0x7ff7259e2f03    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff7268e928c[cataclysm-tiles.exe+0x13d928c]), 
    (libbacktrace: register_frame_ctor+0x7ff5e537cd3c@0x7ff7268e928c),
    (libbacktrace: 0x7ff7268e928c    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff7255113c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff5e3fa4e71@0x7ff7255113c1),
    (libbacktrace: 0x7ff7255113c1    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff7255114d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff5e3fa4f86@0x7ff7255114d6),
    (libbacktrace: 0x7ff7255114d6    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffb49f77034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #17
    (dbghelp: RtlUserThreadStart+0x21@0x7ffb4a162651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by catdach** [comment] 2021-12-13 20:23
duplicate of #53415

**Closed** 2021-12-14 02:19 UTC
Labels: <Bug>, <Crash / Freeze>, (S2 - Confirmed), Character / World Generation
