### ISSUE TITLE
Marked firewood source is not used for oven fire

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31277] opened 2019-06-09 15:55 UTC
# Steps To Reproduce

1. Load the saved game.
2. Start a fire in the oven.
3. Wait 2h.
4. Observe the fire going out.

# Expected behavior

Fire being supplied with splintered wood from the marked firewood source.

# Versions and configuration

0.D-4123-g37a61677a2-dirty

```
[
  "dda",
  "no_npc_food",
  "aftershock",
  "alt_map_key"
]
```

# Additional context

[2019.06.04.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3269709/2019.06.04.zip)

**Comment by Randonx** [comment] 2019-06-11 02:09
https://github.com/CleverRaven/Cataclysm-DDA/issues/31056

**Comment by Randonx** [comment] 2019-06-11 02:10
It's fixed.  Working for me as of that update.

**Comment by Night-Pryanik** [comment] 2019-06-11 04:57
Closing until confirmed to still exist.

**Comment by l29ah** [comment] 2019-06-11 09:25
The version I tested it with is after the commit that's supposed to fix https://github.com/CleverRaven/Cataclysm-DDA/issues/31056, if you haven't noticed.

**Comment by l29ah** [comment] 2019-06-11 09:26
The confirming save file is up there (and always was). Reopen plz.

**Comment by AnthonBerg** [comment] 2019-06-12 14:58
I believe the issue is specific to *waiting*. I am running a very recent master branch. The game people move wood into fires e.g. when starting a fire or reading – but not when *waiting*.

**Comment by ifreund** [comment] 2019-06-12 15:05
>I believe the issue is specific to waiting. I am  running a very recent master branch. The game people move wood into  fires e.g. when starting a fire or reading – but not when waiting.

Well, that would be because `ACT_WAIT` doesn't have
```json
"refuel_fires": true
```
in the json.  It's a simple fix.

**Closed** 2019-06-12 16:42 UTC
Labels: <Bug>, Fields / Furniture / Terrain / Traps
