### ISSUE TITLE
When player with a Hate Vegetables trait eats something made of Vegetable Matter, "Ate meat" debuff shows up.

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#59194] opened 2022-07-12 10:13 UTC
### Describe the bug

When player with a Hate Vegetables trait eats something made of Vegetable Matter, "Ate meat" de-buff shows up.

### Steps to reproduce

1. Have a Hate Vegetables trait
2. Eat something made of Vegetable matter
3. Check Morale

### Expected behavior

I expected to "Ate vegetable" de-buff  to show up/

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: ec37cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZeroInternalReflection** [comment] 2022-07-12 12:48
This looks to be the same issue as #58264.

**Comment by anothersimulacrum** [comment] 2022-07-12 15:57
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/58264

**Closed by anothersimulacrum** 2022-07-12 15:57 UTC
Labels: (S3 - Duplicate)
