### ISSUE TITLE
Infinite loop due to EXTREME move cost

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#37138] opened 2020-01-17 04:15 UTC
# Describe the bug

After being mutated at the rat king cave I decided to leave and that's when an extreme move debuf hit me. I will load the world again and it won't happen other times it will. So it is totally random.

# Steps To Reproduce

1. Go into rat king cave
2. Wait an 10 hours (in game time) getting mutated
3. Try to leave

# Expected behavior

My move cost should never be that high (or low it was in the negative range)

# Screenshots

![Screenshot (630)](https://user-images.githubusercontent.com/56947231/72583610-43f8a600-392a-11ea-9f9a-a1f124747d6b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-11393-g704f045
 - Graphics version: Tiles
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "aftershock",
  "Tolerate_This",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "hydroponics",
  "mutant_npcs",
  "MMA",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "necromancy",
  "speedydex",
  "sleepdeprivation",
  "amplified_players_features"

# Additional context

I debugged in serums to pass the threshold but it shouldn't put me anywhere near that negative value of moves after using them. It didn't crash the game but it did put the game into a permanent loop.
[Coketon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4075006/Coketon.zip)

**Comment by SirClarke** [comment] 2020-01-17 04:24
I think I'm getting something like this as well Try changing (Aim window display style Under the Interface option) from Numbers to Bar and reload the game that seems to be what works for me No idea why

**Comment by sztosz** [comment] 2020-01-17 08:39
To add to what @SirClarke wrote. For me changing from Bars to Numbers and then again from Bars to Numbers fixed it. 

To add some context. I saved game yesterday with a game compiled from master with tag `cdda-jenkins-b10205` and it was I believe this commit: 704f045a5296ff097a7c864327d98d55437bff95 Today I checked out current master, commit fbaae7206762dba2c90ddcf436c3f7cb409a3442 I made `make clean` and `make -j16 RELEASE=1 TILES=1 SOUND=1 CCACHE=1 LTO=1 ZLEVELS=1 LOCALIZE=0 ASTYLE=1 RUNTESTS=0` And when loading save got a bunch (close to 20K) of errors like this: 
```
09:19:34.870 ERROR : src/options.cpp:588 [T options_manager::cOpt::value_as() const [with T = bool]]  tried to get boolean value from option of type VOID
09:19:34.870 ERROR : src/options.cpp:606 [T options_manager::cOpt::value_as() const [with T = int]]  tried to get integer value from option of type VOID
09:19:34.870 ERROR : src/options.cpp:606 [T options_manager::cOpt::value_as() const [with T = int]]  tried to get integer value from option of type VOID
09:19:34.870 ERROR : src/options.cpp:597 [T options_manager::cOpt::value_as() const [with T = float]]  tried to get float value from option of type VOID
09:19:34.871 ERROR : src/options.cpp:606 [T options_manager::cOpt::value_as() const [with T = int]]  tried to get integer value from option of type VOID
09:19:34.871 ERROR : src/options.cpp:597 [T options_manager::cOpt::value_as() const [with T = float]]  tried to get float value from option of type VOID
```
Stamina after load was not existing. Wasn't able to wait to catch a break, so I waited 5 min, it did not help. I play with `Simplified Nutrition` but after the load got vitamin deficiency, scurvy etc. When I moved I got the -MAX_INT move cost like you see on screen from OP, and ingame time started to pass without me being able to interact with the game.

I force quitted game, in options changed aim window display from bars to numbers and loaded save again. Thing does not work, save loads with errors. Changed again from numbers to bars, and it works.

Link to save: https://drive.google.com/file/d/1pOXcCUU2ic_8Ytf38cSoLPhPHfNnXHIq/view?usp=sharing

Game report

```
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Antergos; Description: Antergos Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-11421-g5c93d6fa93 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts],
    No Flaming Weapons [no_flaming_weapons],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Graphical Overmap [Graphical_Overmap]
]
```

**Comment by davidpwbrown** [comment] 2020-01-17 11:51
Can confirm, just got this, also options file was corrupted during load.

**Comment by ZhilkinSerg** [comment] 2020-01-17 12:31
It has something to do with hidden mod options, which came out as not hidden:

![image](https://user-images.githubusercontent.com/16213433/72612515-0e5db800-393e-11ea-884d-57fce741e431.png)

To reproduce - open options menu in a world "Escape" menu.

**Comment by DatMeg** [comment] 2020-01-17 15:19
Still occurring as of 10211.

I should also add, that loading a pre-'change' save (with Simplified Nutrition) results in Vitamin levels set between -7201 and -5600, on top of the Stamina _problems_.

**Comment by Ker-Nes** [comment] 2020-01-17 15:44
It's definitely something to do with the options file. Just reverting to a previous version still has it happening. Deleting options.json solved the issue. Going to test if deleting it in new version also solves the issue.

**Comment by kevingranade** [comment] 2020-01-17 16:06
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/anyonee-know-what-this-means/22502/2

**Comment by Ker-Nes** [comment] 2020-01-17 16:14
Ok, tested it, even with 10211, just deleting options.json solves the problem at least until the options get corrupted again. Until what's causing this is identified, I recommend keeping a backup of a options.json file that's working fine, so you don't have to set everything back to the way you like whenever this bugs pops up.

**Comment by davidpwbrown** [comment] 2020-01-17 16:27
The PR I linked above is likely the cause.

Rolling back to a version before it was merged will fix it for the time being.

**Comment by scorpion451** [comment] 2020-01-17 20:04
Have a workaround: 
Closing the program after the error message appears and reloading does not trigger the error.

**Comment by kuhnchris** [comment] 2020-01-17 20:54
Confirming, opened 10210+ with old save file, received the "from type VOID" error, walked 2 steps, endless loop, force-closed app, opened again, error is gone.

**Closed** 2020-01-18 05:14 UTC
Labels: (P2 - High), (S2 - Confirmed), <Bug>
