### ISSUE TITLE
Finishing a book breaks freshly mended arm.

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#24823] opened 2018-08-13 22:01 UTC
Game version:
Windows_x64 tiles 7587

Operating system:
W7

Mods:
  "dda",
  "blazemod",
  "Tanks",
  "deoxymod",
  "boats",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "ew_pack",
  "craftgp",
  "makeshift",
  "realguns",
  "No_Fungi",
  "no_religious_Texts",
  "StatsThroughSkills",
  "filthy_morale",
  "no_npc_food",
  "Urban_Development",
  "Experimental-Z-Level",
  "more_locations",
  "national_guard_camp",
  "more_buildings",
  "mutant_npcs",
  "npc_traits"

### Expected behavior
When my bones mend, finishing a book should not break them.

### Actual behavior
So... I got into this little incident with some acidic zombies and Hulk, which I survived but both my legs and arm was broken. Spend last few days parked outside the city, reading some books and cooking, while I was waiting for them to mend. Finally while reading this interesting PE023 Medical article I felt it's time to start moving again. But when I dropped down the book, my arm just snapped again! 

When I stop reading before the book finishes it does not happen. Only, when I read it till level gain... Can be another book as well... 

see attached save if it would help. Just start reading a book till level gain.

![image](https://user-images.githubusercontent.com/19891532/44059912-29b739fe-9f53-11e8-95cc-90b00a1c43d7.png)

[Lake Andes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2284864/Lake.Andes.zip)

**Comment by Epictyphlosion** [comment] 2018-08-14 00:52
That doesn't make any sense whatsoever. The code for reading books should have no interference with completely different codes like the player's limb health. Do you have a log of some sort?

**Comment by CoroNaut** [comment] 2018-08-14 04:11
That is absolutely hilarious.

**Comment by Nymall** [comment] 2018-08-14 07:56
This actually looks like a side effect of statsthroughskills recalculating the limb HP and the limb not having enough HP. If we instead wait for the limb to heal and try reading again, it'll be fine. The player does not have Schizo so is not affected by the hallucinations. This also does not seem to be an interaction with the vehicle itself, as it happens regardless. Interestingly, if you read "how to succeed in business" the same thing happens.

**Comment by fungusakafungus** [comment] 2018-08-15 11:29
Tried to reproduce with newly introduced "Break a Leg!" book, no luck.

**Comment by tinukedaya** [comment] 2018-08-15 20:48
> Tried to reproduce with newly introduced "Break a Leg!" book, no luck.

Yeah.. you need to read "Break an Arm!" to reproduce this... ;) 

@Nymall ... the statsthroughskills seems reasonable and the only plausible explanation for what was happening. Although there was not skill change, so I'm not sure why would the arm break because of HP recalculation?

**Comment by FulcrumA** [comment] 2018-08-23 13:43
@Nymall 
@tinukedaya 
Yeah, I doubt it's StatsThroughSkill. Quite a few random actions not affecting stat calculation at all interfere with healing process, including picking up mutated poppy buds which also can break not healed limbs.

**Comment by Night-Pryanik** [comment] 2019-02-07 05:29
Not confirmed in over half a year, closing.

**Closed by Night-Pryanik** 2019-02-07 05:29 UTC
Labels: (S1 - Need confirmation), <Bug>
