### ISSUE TITLE
NPCs refuse to wield a weapon even when they are empty-handed

### ISSUE THREAD

**Issue by zt1415926** [CleverRaven/Cataclysm-DDA#32990] opened 2019-08-07 06:32 UTC
# Describe the bug:

If an NPC is given a high-value weapon to wield before, it will refuse to wield any weapon with lower value even when they are empty-handed. It seems that the NPC considers the previous weapon is still in hand although it has already been removed. 

# Steps To Reproduce

1. Give a friendly NPC a high-value weapon, a shotgun for example, to wield.
2. Interact with the NPC and remove the weapon by trade. Now the NPC becomes empty-handed.
3. Give the NPC another weapon with lower value. For example, a wooden stick.

# Expected behavior
The NPC is expected to wield this wooden stick because it has no weapn now. However, because of a bug, the NPC refuses to wield it and claims that the weapon in its hand is better than the given one. Although there is actually nothing in its hand.

# Versions and configuration
 Game Version: 0.D-6239-ga1ada1a

**Comment by ZhilkinSerg** [comment] 2019-08-07 06:38
Probably something related to missing cache invalidation when npcs are unwielding items.

**Comment by l29ah** [comment] 2019-08-07 15:33
Looks like a dupe of #32613

**Closed** 2019-08-22 18:01 UTC
Labels: (S1 - Need confirmation), (S3 - Duplicate), <Bug>, Melee, NPC / Factions
