### ISSUE TITLE
atomic mp3 players need a max charges of plutonium

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#12059] opened 2015-04-18 17:11 UTC
Right now, when you mod an mp3 player into an atomic mp3 player, it doesn't gain a max charges o plutonium limit.  So you can put any amount of plutonium cells in it.

The downside is it's easy to put your entire precious hoard of p. cells in and then are unable to unload them and get them back out.

**Comment by mugling** [comment] 2016-08-11 13:35
Duplicate of the other plutonium bugs

**Closed by mugling** 2016-08-11 13:35 UTC
Labels: Balance, Bug
