### ISSUE TITLE
Possible conflict with mod cause issue with world loading.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#20329] opened 2017-02-19 19:20 UTC
As stated here: [http://smf.cataclysmdda.com/index.php?topic=12051.msg295795#msg295795 date=1487480175](url), When loading the two mods together (Cataclysm++ and PK's Rebalance) it cause issues on the loading screen. 

The possible issue was thought to be a conflict with the version of PK's Rebalance that comes with the mod because to use both mods requires a patch mot that includes a combined monster list.

The reason I post this is because there is no error message indicated, it simply gets stuck, meaning that if the issue is with both mods, one of them, or the game is unknown.

To reproduce: 
-Download Cataclysm++ mod: [https://1drv.ms/u/s!Ajb7I9_jqo4TgUv0lDQfCskI_C0K](url)
-Download PK's Rebalancing: [https://www.dropbox.com/s/il87ysjl85to0dc/PKs_Rebalancing.zip?dl=0](url)
-Download the patch mod: [https://www.dropbox.com/s/a454aavsf0idq01/noct-pk%20Patch.zip?dl=0](url)
-Create new world with the three mods loading the patch mod last.
-Try to generate world.

**Comment by kevingranade** [comment] 2017-04-12 17:03
Duplicate of #20107

**Closed by kevingranade** 2017-04-12 17:03 UTC
