### ISSUE TITLE
Monsters are teleporting randomly when nowhere to go

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22989] opened 2018-02-19 12:02 UTC
Game version: 0.C-7128

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Monster should stay on the tile it is already standing on when there is no possible way to go.
### Actual behavior
Monster (namely `zombie master` with `PATH_AVOID_DANGER_2` flag which I think is the culprit) is randomly teleporting when there is no possible way to go.
### Steps to reproduce the behavior
Using debug menu, create a room with metal walls, fill all its interior with fire, place zombie master inside the room. Wait a turn. Zombie master will teleport out of the room.
![default](https://user-images.githubusercontent.com/11132525/36376840-bec67346-1585-11e8-88eb-aaadb7c468db.PNG)
![2](https://user-images.githubusercontent.com/11132525/36376842-c1fef290-1585-11e8-97c8-794bde33b114.PNG)

**Comment by Leland** [comment] 2018-02-19 16:08
Duplicate of #11859

**Closed by Leland** 2018-02-19 16:08 UTC
Labels: Bug, Monsters
