### ISSUE TITLE
Milling output differs from item desc., seems to exponentially increase with amount of items put inside mill.

### ISSUE THREAD

**Issue by Bobtron** [CleverRaven/Cataclysm-DDA#68917] opened 2023-10-26 04:03 UTC
### Describe the bug

Actual output of mill seems to exponentially increase compared to expected output

### Attach save file

[Debug Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13172771/Debug.Testing-trimmed.tar.gz)

### Steps to reproduce

1. Obtain dry wild rice. (Note that milling conversion rate mentions 1 dry wild rice is converted to 2 wheat-free flour)
2. Put dry wild rice in mill
3. Actual output is much larger than expected output

- From my testing, 10 dry wild rice -> 110 wheat-free flour
- 20 dry wild rice -> 420 wheat-free flour
- 30 dry wild rice -> 930 wheat-free flour
- 100 dry wild rice -> way too much wheat-free flour, spills over into several tiles
- 240 dry wild rice (max amt mill can hold) -> no more world hunger

### Expected behavior

Expected out behavior is 

- 10 dry wild rice -> 20 wheat-free flour
- 20 dry wild rice -> 40 wheat-free flour
- 30 dry wild rice -> 60 wheat-free flour

etc etc 

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 12.6.3; Build: 21G419; 
- Game Version: aed22a9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    DinoMod [DinoMod]
]

### Additional context

Found this while looking at #68724
Also #68676 seems to be a recent change with the milling amount, perhaps related?

**Comment by RenechCDDA** [comment] 2023-10-27 02:39
Duplicate of #68701

**Closed by RenechCDDA** 2023-10-27 02:39 UTC
Labels: (S1 - Need confirmation)
