### ISSUE TITLE
Game couldn't generate a starting location

### ISSUE THREAD

**Issue by Aoi-the-Hert** [CleverRaven/Cataclysm-DDA#37168] opened 2020-01-18 04:56 UTC
Game version: 0.D-11430-g66807fe

Operating system: Win 10 Pro 64 bit

Tiles or curses: Undead People

Mods active: 
"dda", 
"crt_expansion", 
"fast_healing", 
"Cata++", 
"crazy_cataclysm",
 "More_Survival_Tools", 
"Medieval_Stuff", 
"makeshift",
"no_npc_food", 
"more_classes_scenarios", 
"RL_Classes", 
"safeautodoc", 
"novitamins", 
"speedydex",
"no_filthy_clothing", 
"no_reviving_zombies", 
"fuji_mpp"

### Expected behavior
To generate the High Tech, Low Life scenario as a used car salesman

### Actual behavior
It didnt start the game and told me to report it

### Steps to reproduce the behavior
Starting with this character setup makes it crash
![image](https://user-images.githubusercontent.com/12159393/72658842-5d2a4280-397c-11ea-8ac7-9996945bee21.png)

**Comment by Foxtrot-Uniform42** [comment] 2020-01-18 09:10
Can confirm same behavior occurs in island prison scenario

**Comment by Night-Pryanik** [comment] 2020-01-18 10:42
Duplicate of #35376.

**Closed by Night-Pryanik** 2020-01-18 10:42 UTC
