### ISSUE TITLE
'Plant Fields' does not sonsume seeds

### ISSUE THREAD

**Issue by Polubing** [CleverRaven/Cataclysm-DDA#38076] opened 2020-02-16 21:35 UTC
# Describe the bug

When selecting 'Plant Fields' faction camp farm expansion npc activity, npc takes the seeds selected in the previous menu, and at the end of the activity, brings them all back instead of using them up. The plots have been planted, effectively duplicating the seeds.

# Steps To Reproduce

1. build faction camp at shelter.
2. build farm expansion when shelter is upgraded enough (?)
3. upgrade farm expansion to have farm plots
4. plow way more farm plots on the same map tile (this might be the important part!!!)
5. have seeds and send NPC to Plant Seeds
6. note at end of activity when Recovering npc companion, the seeds he throws on the floor at your feet.

# Expected behavior

I expect an NPC to not bring back the seeds he was told to put in the ground.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-12173-g61272b3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    sees-player icon, retrodays [sees_player_retro]
]

# Additional context

I did not notice until the second time I sent my npc to plant seeds, so I do not know if the seeds were only consumed planting the original plowed ground that came with the farm upgrade versus what i plowed manually afterwards.

**Comment by TechyBen** [comment] 2020-02-17 19:58
Can confirm a long standing bug. I was getting the same (I was not sure if it was just me imagining it) :p

**Comment by Funguss** [comment] 2020-03-06 01:35
This is interesting. I never could get them to work...

Oh wait. Do you actually need to set up farm zones in order to have the task show up?

**Comment by starytroll** [comment] 2020-03-28 21:44
I can confirm this bug (actually was preparing another bug report but found this one in "similar"). I can give some more details that I observed:

- To be precise, I used the option of bulletin interface to "Plant Fields";
- I did not plow anything more, just used the standard 108 tiles;
- The seeds did not disappear from the storage area at all;
- Tried both all 108 seeds, and less on the other field tile, but always more than one type, don't know if this is of any importance; 

Version info:
- OS: Windows
    - OS Version: 8.1
- Game Version: 0.D-13466-g49145ee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by pjf** [comment] 2021-06-30 09:57
This may be a duplicate of #47672, which has seeds erroneously removed from the player's inventory, not basecamp storage.

**Comment by LeahLuong** [comment] 2022-01-30 22:07
It's more the case that #47672 is a dupe of this since this report was created 1st. Regardless, both threads contain relevant info pertaining to this bug which is still happening in 0.F-3.

Of note, not having seeds in your basecamp storage prints a message implying you need to have the seeds in your inv when you use the option to plant them using the bulletin board.

**Closed** 2022-04-14 20:30 UTC
Labels: <Bug>, <Exploit>, Player Faction Base / Camp
