### ISSUE TITLE
Crash in character creation menu

### ISSUE THREAD

**Issue by FishSticksandMayo** [CleverRaven/Cataclysm-DDA#64749] opened 2023-04-01 05:33 UTC
### Describe the bug

Game crashes and pop shows up that forcefully closes the game. Not able to play the game cause can't get in world.

### Attach save file

](url)[
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11128502/crash.log)

### Steps to reproduce

1. Launch experimental with CDDA game launcher (2023-04-01-0137)
2. New game->Custom character, Preset character or Random character (all these crashes the same)->
3. When character creation menu opens up crash occurs

### Expected behavior

I expected game not to crash and tweak character

### Screenshots

![image](https://user-images.githubusercontent.com/129575798/229267174-0f03fb04-7361-4e74-90e4-c829f621ba0f.png)
![image](https://user-images.githubusercontent.com/129575798/229267179-f720941d-ddea-48a1-9fde-66641499faaf.png)

### Versions and configuration

Can't get in the game to open debug menu or atleast not aware how to do it otherwise.

### Additional context

Can't get in the game to open debug menu or atleast not aware how to do it otherwise.

**Comment by RenechCDDA** [comment] 2023-04-13 03:59
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64328

I recommend you try the MSVC version. That was reported to avoid the crash/loading issues encountered in the other thread.

**Closed** 2023-04-13 04:01 UTC
Labels: (S1 - Need confirmation)
