### ISSUE TITLE
Petrified eye spawn_wyrms event not triggering properly.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#49393] opened 2021-06-21 09:37 UTC
When examining the pedestal containing the Petrified Eye found at the bottom of some mines, an event is supposed to fire where the pedestal lets out a scream, sinks into the ground, and dark wyrms start periodically spawning around you until you either drop the eye or escape the mines.

As it stands, this event only fires if you specifically examine the pedestal while no items are present on it, largely negating it's purpose.

# Steps To Reproduce

1: Examine pedestal with eye
2: Freely take eye without the event triggering.
3: Examine pedestal with no items on tile
4: Event triggers.

# Expected behavior

The pedestal should sink into the ground and the spawn_wyrms event should activate immediately upon the petrified eye being removed from it's original position.

# Screenshots
Examining the pedestal with eye, and taking the eye without consequence.
![image](https://user-images.githubusercontent.com/19789267/122740781-e6068580-d2b6-11eb-984f-9b2853d9dbf9.png)
![image](https://user-images.githubusercontent.com/19789267/122740955-0fbfac80-d2b7-11eb-8a39-47d7e2b15a44.png)
![image](https://user-images.githubusercontent.com/19789267/122740996-19e1ab00-d2b7-11eb-9d37-573feb117200.png)

Examining the pedestal sans-eye directly, triggering the event:
![image](https://user-images.githubusercontent.com/19789267/122741209-501f2a80-d2b7-11eb-812d-63cfd3c61fb5.png)

# Versions and configuration

**Comment by actual-nh** [comment] 2021-06-21 20:11
Ping: @Night-Pryanik?

**Comment by ZhilkinSerg** [comment] 2021-06-21 22:05
Duplicate of #13310

**Closed** 2021-06-22 02:42 UTC
Labels: Items / Item Actions / Item Qualities, Monsters, Spawn
