### ISSUE TITLE
Relative and proportional ammo's properties seems to be applied anymore.

### ISSUE THREAD

**Issue by jeremieroy** [CleverRaven/Cataclysm-DDA#43330] opened 2020-08-30 14:02 UTC
# Describe the bug
Ammunition derived from a base type with relative or proportional modifications in the json dont exhibits these modifications in the game.

Example: 

**9x19mm JHP**
Has:
```
"range": 14,
"damage": { "damage_type": "bullet", "amount": 26 },
...
```

**9x19mm +P+**
Has 
```
"copy-from": "9mm",
"relative": { "damage": { "damage_type": "bullet", "amount": 4, "armor_penetration": 4 }, "dispersion": -30 },
 "proportional": { "recoil": 1.2 }
...
```
But in game they appear to have no modification at all, same case for other derived ammo.

# Screenshots
![9mmjhp](https://user-images.githubusercontent.com/3527910/91660669-88ab0900-ead7-11ea-8fde-6137d4f5b601.PNG)
![9mmp+p](https://user-images.githubusercontent.com/3527910/91660671-89439f80-ead7-11ea-9efc-a9133b9b2b4c.png)
![9mmfmj](https://user-images.githubusercontent.com/3527910/91660952-4256a980-ead9-11ea-9012-9ccc30ac8833.PNG)
![9mmjhp_black](https://user-images.githubusercontent.com/3527910/91660959-4682c700-ead9-11ea-96f4-b6a0a5e7be9b.PNG)

# Steps To Reproduce

1. Found, craft or spawn various ammo kind from the same family   
2. Look at the ammo properties

# Expected behavior
Derived ammo should have the modifier applied and it should be visible in game.
Example:
**9x19mm +P+**
Should have damage of 26 **+ 4**   vs 26 right now.
And armor penetration of **4**  vs 0 right now.

# Remark

Ammo with explicit override do work properly. Only proportional and relative seems wrong.

# Versions and configuration

- OS: Windows 10
- Game Version: 0.E-5503-g8d8fcd0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
]

**Comment by anothersimulacrum** [comment] 2020-08-30 14:08
It does work, it just doesn't display correctly. (Try setting the relative damage for the +P variant to 2000 damage)
Duplicate of #41564

**Closed by anothersimulacrum** 2020-08-30 14:08 UTC
Labels: (S3 - Duplicate)
