### ISSUE TITLE
game freezing for moment first action after item is removed from autopickup 

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#19716] opened 2016-12-10 20:58 UTC
been experiencing this few last version never happend before -first step after removing item from autopickup  game freze for moment-(just tested it several times with splintered wood it constantly repeat).need more confirmation if this is maybe my pc or game.

ps-autopickup is meant as from item meny not specific autopickup meny

**Comment by Regularitee** [comment] 2016-12-10 21:14
Another possibly directly-related bug:

After loading a save, the first time you come within adjacency of any pickup-able item on the ground, there is a very similar "lag spike" where the game stops responding for a period. 

I think they're related because both increase in severity the longer the game is (which I'm assuming -- correctly or not -- has to do with how many items are on the item auto-pickup list)

**Comment by codemime** [comment] 2016-12-13 09:26
This may be related to #19240.

**Comment by CoroNaut** [comment] 2016-12-13 10:14
I have NPC's turned off and get the same lag spikes, perhaps it is just a raw bug with auto pickup all together?

**Comment by Night-Pryanik** [comment] 2019-11-17 16:03
Can't confirm on 0.D-9346. This issue is almost 3 years old, I guess we can safely close it.

**Comment by ThomasLinkin** [comment] 2020-01-02 06:46
This is an 3 years-old post,anyone mind checking out?

**Comment by Night-Pryanik** [comment] 2020-01-02 08:01
Ok, closing until re-confirmed.

**Closed by Night-Pryanik** 2020-01-02 08:01 UTC
Labels: Code: Performance
