### ISSUE TITLE
Lemonade Powder causing game to hang on loading

### ISSUE THREAD

**Issue by LordMadness** [CleverRaven/Cataclysm-DDA#45251] opened 2020-11-05 09:05 UTC
# Describe the bug

Lemonade Powder is causing my game to hang for a long time.

 DEBUG    : error: item lemonade_powder cannot fit into pocket while loading: item too big

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 325

# Steps To Reproduce

I'm unsure how to reproduce. I would upload my save, but it's a 600mb file.
My last location was inside a lab Weapon Testing room, where some MREs were on the racks.

# Expected behavior

lemonade_powder fit the bottle_plastic_small it's trying to.

# Versions and configuration

OS: Windows
OS Version: 10.0 1909
Game Version: 0.E-7347-g20d1078 [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Graphical Overmap [Graphical_Overmap],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions],
Aftershock [aftershock],
Aftershock - UndeadPeople Tileset [AftershockUDP],
Stats Through Kills [stats_through_kills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5493100/debug.log)

Edit: I thought it was MRE's, but I noticed MREs aren't pockets types.

**Comment by hexagonrecursion** [comment] 2021-01-13 15:01
This seems to be the same as https://github.com/CleverRaven/Cataclysm-DDA/issues/41776 which was fixed a while ago

**Comment by Saicchi** [comment] 2021-02-03 22:00
Can't replicate this issue in 0.E-9355-g203e8c942c.

If this is still happening for you could you please upload a zip of your save file? A 600MB world would be reduced to around 40mb when zipped.

I assume your error was caused by either lemonade powder getting its weight/volume changed or the small plastic bottle it was on had its pocket size reduced when you updated your game.

**Comment by hexagonrecursion** [comment] 2021-02-04 07:46
> I assume your error was caused by either lemonade powder getting its weight/volume changed or the small plastic bottle it was on had its pocket size reduced when you updated your game.

I think it might have been e419782c530bce29cf3b87930f254c0b15f6d561

**Comment by esotericist** [comment] 2021-02-04 13:31
given it doesn't seem to be reproducible by others, the original submitter wasn't able to submit a save, and evidence that all the relevant parts have had changes, closing this.

if @LordMadness (or anyone else, for that matter) is still able to reproduce this, and can give us more to work with, the issue can be re-opened.

**Closed by esotericist** 2021-02-04 13:31 UTC
Labels: <Bug>, Items: Containers
