### ISSUE TITLE
Refilling containers with water from vehicle tanks crashes the game

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#54378] opened 2022-01-13 20:54 UTC
### Describe the bug

Trying to refill a container from a vehicle tank at the first attempt crashes the game, then just does not work. 

### Steps to reproduce

1. Examine a vehicle part with a faucet
2. Select "fill a container with water"
2. Select a vehicle tank
3. Select a container
3. At first game crashes, then just throws up an error, the container does not refill

### Expected behavior

It's possible to refill a canteen with water without unscrewing a 60l vehicle tank.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9f2940a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7865908/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7865919/debug.log)

might me related to #54341 ?

**Comment by NetSysFire** [comment] 2022-01-13 20:58
Potential duplicate of #51582?

**Comment by ektoplazm** [comment] 2022-01-13 20:59
> Potential duplicate of #51582?

siphoning works just fine, it looks like only refilling with faucets broke

**Comment by NetSysFire** [comment] 2022-01-13 22:13
Can you provide a save where you can reproduce this reliably?

**Comment by ektoplazm** [comment] 2022-01-16 23:37
> Can you provide a save where you can reproduce this reliably?
[Dateland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7878180/Dateland.zip)

**Closed** 2022-01-19 21:17 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), Vehicles
