### ISSUE TITLE
Functional car becomes too heavy after parked and coming back. (now with save!)

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#19201] opened 2016-11-06 22:14 UTC
I've seen this happen a few times now.  Previously I thought this bug was related to a car too heavy message being given instead of a dead battery, since that first one had a damaged battery.  But this is now the 2nd car that has had this bug that should be perfectly functional.

Attaching a screenshot of the car's status screen which should indicate no problems.  Not only is the car running a stronger engine than it came with, it has been stripped down and lightened.  Fuel and battery are both plenty full.  This bug occured in 0.C 5764, and again in 0.C 5814.  I loaded the save in 0.C 5849 and the car still claims to be too heavy.

Each time this happened I had parked a car near a large heavy vehicle of some kind. So I think that may be related, but I do not know enough code to search for the cause myself.

![cataclysm stalled car](https://cloud.githubusercontent.com/assets/6796376/20042189/732003ee-a42a-11e6-8280-f66652283ef1.png)

**Comment by Greiger** [comment] 2016-11-06 22:39
Just an info update while I was poking around trying to get the car functioning again. (I customized that quite a bit, and really don't want to abandon a second car to this bug)
When I'm outside the car, Acceleration is 16 mph/t and mass is 2568 lbs.  When my character enters the car mass changes to 2747 (acceleration stays the same).  But when I start the car acceleration immediately drops to 0.  And stays there until the character exits the car.

**Comment by illi-kun** [comment] 2016-11-10 17:03
Can this be duplicate of #18983?

**Comment by Greiger** [comment] 2016-11-11 02:16
I think it's a seperate issue.  I had this issue once before but since I was not sure of that car's battery status at that time, I figured it was that issue and did not report it.
This time it happened on a battery that I know is 100% full.  So it seems to me to be something different.

**Comment by mugling** [comment] 2016-11-27 00:24
Suspect resolved in `master` along with #18983

**Closed by mugling** 2016-11-27 00:24 UTC
Labels: Bug, Confirmation Needed, Vehicle
