### ISSUE TITLE
New Characters Begin Starving

### ISSUE THREAD

**Issue by eddj93** [CleverRaven/Cataclysm-DDA#46995] opened 2021-01-24 13:05 UTC
# Describe the bug

New player characters spawn as starving, dehydrated and skeletal when beginning a new game

# Steps To Reproduce

1. Start a new game
2. Starve

# Expected behavior

1. Start a new game
2. Don't starve
3. Be Overweight as in previous builds

# Screenshots

![cdda](https://user-images.githubusercontent.com/77923585/105630987-e4d64700-5e43-11eb-97be-e0ea5f69245e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9181-g308bec1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by anothersimulacrum** [comment] 2021-01-24 14:40
Cannot reproduce on `0.E-9181-g308bec1612`

**Comment by BrettDong** [comment] 2021-01-24 15:59
Which starting scenario, profession and traits did you choose?

**Comment by wapcaplet** [comment] 2021-01-24 16:21
> Which starting scenario, profession and traits did you choose?

It appears to be the "Overrun" scenario using the "Combat Medic" profession, with the "No NPC Needs" and "Bionic Professions" mods disabled. Starting traits are indicated in the OP screenshot.

I tried several times in 0.E-9181-g308bec1612 to reproduce the issue with the same parameters, but always began in "Overweight" rather than "Skeletal" status.

**Comment by Reknot** [comment] 2021-01-24 16:21
Can confirm. 
Occurs on build >11367
11366 works fine.
Using Operator Recon class from Fuji's Military Profession Pack
![unknown](https://user-images.githubusercontent.com/11231726/105636287-02b5a300-5e68-11eb-9dd7-442b2f21b09c.png)

Using this mod setup

![image](https://user-images.githubusercontent.com/11231726/105636374-68a22a80-5e68-11eb-9708-68dba6662be9.png)

Doesn't matter how you restore\reset\juggle things. Always starts as starving.

**Comment by wapcaplet** [comment] 2021-01-24 21:05
Reported by user Kasper on Discord as well:

> Each new game I start, I spawn skeletal and starving - which results in instant death. I've tried rollbacks and recreating the world, but it keeps happening.
> I've tried several different scenarios and professions, and it even worked fine earlier today on the same patch, but suddenly it started happening

I still cannot reproduce it myself.

**Comment by actual-nh** [comment] 2021-01-24 21:22
Does it happen in builds prior to 11398?

**Comment by Reknot** [comment] 2021-01-24 21:26
> Does it happen in builds prior to 11398?

I tested it trough the CDDA Game Launcher, any build above and including 11396 it happens to any character-
I can provide world and template for character.

**Comment by BrettDong** [comment] 2021-01-24 21:30
What is the value of stored calories in debug menu -> player -> edit player -> you -> set needs?

**Comment by Reknot** [comment] 2021-01-24 21:33
![image](https://user-images.githubusercontent.com/11231726/105644114-1971ef00-5e94-11eb-8030-7940179b3a7a.png)
On borken @BrettDong

**Comment by Reknot** [comment] 2021-01-24 21:35
> Does it happen in builds prior to 11400-11398?

[Template_And_WorldGenFiles_OHGODZIPPLZ.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5863232/Template_And_WorldGenFiles_OHGODZIPPLZ.zip)

**Comment by actual-nh** [comment] 2021-01-24 21:40
> > Does it happen in builds prior to 11398?
> 
> I tested it trough the CDDA Game Launcher, any build above and including 11396 it happens to any character-

Huh. The first thing I thought of was a metabolism refinement @anothersimulacrum and I (or, if it is indeed the culprit, I rephrase that to myself and anothersimulacrum) did... but it didn't go in until 11398.

> I can provide world and template for character.

What OS are you using? (And wapcaplet - what OS are you using?)

**Comment by BrettDong** [comment] 2021-01-24 21:43
Confirmed with world file and character templated provided by @Reknot on macOS on 0.E-9182 85a23edc64

**Comment by Reknot** [comment] 2021-01-24 21:44
> What OS are you using? (And wapcaplet - what OS are you using?)

Win10 

I jump back and fourth between 11396 and 11398 (11397 is "unavailable") to make the screenshot and test stuff you request. =) 
Resetting world and starting new toon each time I go to 11398
.
![image](https://user-images.githubusercontent.com/11231726/105644383-918ce480-5e95-11eb-8a62-e18258f913ce.png)

**Comment by Proxiehunter** [comment] 2021-01-24 21:57
Are you using preset characters? Someone on Reddit said once they deleted their presets and remade them the problem ceased.

**Comment by Reknot** [comment] 2021-01-24 22:02
> Are you using preset characters? Someone on Reddit said once they deleted their presets and remade them the problem ceased.

Well, I suppose Yes. Mine are made prior 11397. 
Soo, I guess the new calorie system doesn't take that into account making any old Template broken?

**Comment by actual-nh** [comment] 2021-01-24 22:04
Actually, it does. It multiples the old kcal by 1000. Savegame_version went from 31 to 32. Perhaps something went wrong with the versioning?

**Comment by Proxiehunter** [comment] 2021-01-24 22:04
Not sure of the why but I was having this problem a few minutes ago and I can confirm that deleting your presets and remaking them fixed the issue, just did it now. Kind of annoying to have to do that but at least there's an interim fix.

**Comment by actual-nh** [comment] 2021-01-24 22:05
What does it say at the start of the file - the number after '# Version"?

**Comment by BrettDong** [comment] 2021-01-24 22:05
> I guess the new calorie system doesn't take that into account making any old Template broken?

You are right. Multiplying stored calories in your character template by 1000 solves the issue.

**Comment by actual-nh** [comment] 2021-01-24 22:08
src/savegame_json.cpp - line 565-566 should be multiplying anything with a version of 31 or before by a 1000. So what's going wrong with that?

**Comment by BrettDong** [comment] 2021-01-24 22:08
Migration fails because there is no version information in character templates.

**Comment by actual-nh** [comment] 2021-01-24 22:09
Facepalm. No version information in character templates? Joyful.

**Comment by actual-nh** [comment] 2021-01-24 22:10
Umm... possibly version information should be put into them, and no version treated as 31?

**Comment by actual-nh** [comment] 2021-01-24 22:12
And why is it happening with 11396?

**Comment by wapcaplet** [comment] 2021-01-24 22:14
> (And wapcaplet - what OS are you using?)

Linux (PopOS! / Ubuntu)

**Comment by PaulBlay** [comment] 2021-01-24 22:20
> Umm... possibly version information should be put into them, and no version treated as 31?

The only problem with that is that a select few preset character templates will be so fat they explode. Those that were created after the x1000 change but before the version number was added. That's a pretty unlikely scenario, though.

**Comment by Reknot** [comment] 2021-01-24 22:24
> And why is it happening with 11396?

Holy shit! My bad. I typed it >11396. But wanted to be more specific in text and FORGOT to change to 11397 when typing 
"any build above and including _11396_" <-- This is my mistake, should be
"any build above and including **11397**" 

Just wanted to clarify this, incase of confusion.

**Comment by actual-nh** [comment] 2021-01-24 22:54
> > Umm... possibly version information should be put into them, and no version treated as 31?
> 
> The only problem with that is that a select few preset character templates will be so fat they explode. Those that were created after the x1000 change but before the version number was added. That's a pretty unlikely scenario, though.

If the stored calories are already greater than (14/25)*55,000,000 - admittedly, the relationship between stored calories and weight is more complex than that, so that might need some tweaking - don't multiply them by 1000.

**Comment by actual-nh** [comment] 2021-01-24 22:59
I am not up to the needed C++ coding, at least not without considerable trial and error (and thus time).

**Comment by anothersimulacrum** [comment] 2021-01-24 23:13
Templates appear to be saving an entire character, I am not sure they need to be doing that at all, there's all sort of data that is really not needed there, and it would avoid bugs like this.

This doesn't fix the current issue, but would prevent it from occurring in large part in the future.

**Comment by actual-nh** [comment] 2021-01-24 23:15
> Templates appear to be saving an entire character, I am not sure they need to be doing that at all, there's all sort of data that is really not needed there, and it would avoid bugs like this.

There is information that can be reconstructed instead (given that they are otherwise a default starting character)?

**Comment by anothersimulacrum** [comment] 2021-01-24 23:26
The only data that needs to be saved is that which can be selected through character creation: scenario, profession, stats, skills, traits, gender, name, height, age, blood type, and starting location selection. Start with a default character, then apply all those, and we're back to the character we made.
It's a little more of a burden, because new things added to character creation must be added to it, but it prevents the need to do much of any migration.

**Comment by K7ATR** [comment] 2021-02-01 02:43
> Are you using preset characters? Someone on Reddit said once they deleted their presets and remade them the problem ceased.

This fixes the issue for me.

**Comment by wapcaplet** [comment] 2021-02-13 04:03
I have added and self-assigned a new feature request to implement the solution @anothersimulacrum described above. That won't really fix this bug - nothing can truly fix it now, since we don't have game version in the template - but it will prevent similar issues in the future.

Since it took so long for the above discussion to even arrive at what the problem was, and is not even particularly interesting to read, I am closing this dark rabbit hole in lieu of #47462. Thanks everyone for participating!

**Closed by wapcaplet** 2021-02-13 04:03 UTC
Labels: (S2 - Confirmed), <Bug>, Character / World Generation

**Comment by BrettDong** [comment] 2021-02-13 04:06
How about adding a band-aid hack for 0.F migration? Say automagically multiply by 1000 if the value read from JSON is below some threshold.

**Comment by actual-nh** [comment] 2021-02-13 04:10
> How about adding a band-aid hack for 0.F migration? Say automagically multiply by 1000 if the value read from JSON is below some threshold.

Suggested threshold: 55,000/sqrt(1,000).
