### ISSUE TITLE
vehicle position can still be outside vehicle sometimes, possible pivot code problem

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14420] opened 2015-12-13 23:28 UTC
This was reported by molkemon on IRC

save: https://www.dropbox.com/s/f8587duj25e3mp7/Coldspring.7z?dl=0

Attempting to drive this vehicle will "take control" instead of starting the engines. This is because `activity_handlers::start_engines_finish` attempt to look up `g->m.veh_at(pos)` can't find the vehicle.

I believe this can be traced back to `vehicle::start_engines` trying to do `g->u.activity.placement = global_pos3() - g->u.pos();` which leads to the activity possibly being placed outside of the vehicle, as is demonstrated in the linked save.

I got lost trying to go further than this, looking at all the code that sets `posx`/`posy` for a `vehicle`.

**Comment by mutability** [comment] 2015-12-14 00:20
This will be related to the vehicle rotation changes. Previously there was always a vehicle tile at vehicle::global_pos3(). Now, the pivot point is always at vehicle::global_pos3() but there is no guarantee that there is actually a vehicle tile there.

**Comment by Oskar636** [comment] 2016-11-10 14:53
Since this is an old bug and the save file doesn't exist anymore and it doesn't seem like there are similiar issues to this, I would like to ask if this issue could still exist or did the vehicle code got some rework that makes this impossible to reproduce.

**Comment by I-am-Erk** [comment] 2019-02-19 04:00
I'm going to assume this is no longer an issue considering the number of vehicle reworks. Closing until contradicted.

**Closed by I-am-Erk** 2019-02-19 04:00 UTC
Labels: <Bug>, Vehicles
