### ISSUE TITLE
The game crashes when learn a Xedra evolved artifact on linux

### ISSUE THREAD

**Issue by usrmoon** [CleverRaven/Cataclysm-DDA#78488] opened 2024-12-11 10:06 UTC
### Describe the bug

game crashes when trying to learn a spell for Xedra evolved mod on any world. i tried on a fresh  installation but the same issue. however it worked on windows 11.

### Attach save file

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: cdda-experimental-2024-12-11-0835 653a131
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
Error creating SDL message box: zenity reported error or failed to launch: 129
STACK TRACE:

    0x5761add985e5    src/debug.cpp:979    bt_full
    0x5761add985e5    src/debug.cpp:1244    debug_write_backtrace(std::ostream&)
    0x5761add71638    src/crash.cpp:89    log_crash
    0x5761add71985    src/crash.cpp:146    signal_handler
    0x77635ee4c1cf    [unknown src]:0    [unknown func]
    0x77635eea53f4    [unknown src]:0    [unknown func]
    0x77635ee4c11f    [unknown src]:0    [unknown func]
    0x77635ee334c2    [unknown src]:0    [unknown func]
    0x77635ee333de    [unknown src]:0    [unknown func]
    0x77635ee44176    [unknown src]:0    [unknown func]
    0x5761ae861020    src/third-party/imgui/imgui.cpp:5955    ImGui::BeginChildEx(char const*, unsigned int, ImVec2 const&, int, int)
    0x5761ae1ca0b9    src/magic.cpp:3197    spellbook_callback::refresh(uilist*)
    0x5761ae902a4e    src/ui.cpp:198    uilist_impl::draw_controls()
    0x5761adbef734    src/cata_imgui.cpp:934    cataimgui::window::draw()
    0x5761adbef734    src/cata_imgui.cpp:903    cataimgui::window::draw()
    0x5761ae909602    src/ui_manager.cpp:448    ui_adaptor::redraw_invalidated()
    0x5761ae903a1a    src/ui.cpp:942    uilist::query(bool, int, bool)
    0x5761ae17cbd1    src/iuse_actor.cpp:2445    learn_spell_actor::use(Character*, item&, coords::coord_point_ob<tripoint, (coords::origin)5, (coords::scale)0> const&) const
    0x5761adf71064    src/handle_action.cpp:1718    read
    0x5761adf7363e    src/handle_action.cpp:2582    game::do_regular_action(action_id&, avatar&, std::optional<tripoint> const&)
    0x5761adf76656    src/handle_action.cpp:3279    game::handle_action()
    0x5761addfcdb1    src/do_turn.cpp:581    do_turn()
    0x5761ad8ff4b2    src/main.cpp:863    main
    0x77635ee34e07    [unknown src]:0    [unknown func]
    0x77635ee34ecb    [unknown src]:0    [unknown func]
    0x5761ada6022d    [unknown src]:0    [unknown func]
    0xffffffffffffffff    [unknown src]:0    [unknown func]

### Steps to reproduce

learn Xedra evolved spell from any artifact in any condition

### Expected behavior

learn the spell

### Versions and configuration

OS: Arch Linux x86_64
Game version:
build type: linux-with-graphics-and-sounds-x64
build number: 2024-12-11-0835
commit sha: 653a13141aa475069bbbe58b76785e80c21014a3
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/653a13141aa475069bbbe58b76785e80c21014a3

**Comment by usrmoon** [comment] 2024-12-11 10:17
Additional mods:
Dark Days Ahead [dda]
Disable NPC Needs [no_npc_food]
Portal Storms Ignore NPCs [personal_portal_storms]
Slowdown Fungal Growth [no_fungal_growth]

**Comment by moxian** [comment] 2024-12-11 10:47
This should be fixed by #78487 
Can you please re-check that does not reoccur in the absolute freshest build? (<https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-12-11-0835>)

**Comment by usrmoon** [comment] 2024-12-11 11:10
> This should be fixed by #78487 Can you please re-check that does not reoccur in the absolute freshest build? (https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-12-11-0835)

The Issue is not fixed in the latest version

**Comment by Procyonae** [comment] 2024-12-12 15:33
This is a duplicate of #78476, please post any additional stuff there instead (Idk why Zhilkin marked this as a dupe without specifying what it's a dupe of lol)

**Closed by Procyonae** 2024-12-12 15:33 UTC
Labels: (S3 - Duplicate)
