### ISSUE TITLE
'Move all' button in advanced inventory management fails with no notice of the cause

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31805] opened 2019-06-24 17:56 UTC
# Describe the bug

Seemingly at random (with no information about anything happening in the message log) advanced inventory's 'move all' key (default ',') at times act like 'move stack' key. I am yet to find the exact cause of this and will update it if I will (assuming no one else will find it before me), but it seems to be more frequent in areas with other moving creatures.

# Steps To Reproduce

So far I've managed to trigger it again under such circumstances:
1. No-debug, regular character moved to city and cleaned out just some of the monsters
2. On one end of the street, standing among piles of items ('All 9 squares direction') and pressing 'move' with destination being another regular ground tile moved the items without an issue
3. On the other end of the street, similar situation forced 'move all' to move only a single stack

# Expected behavior

'Move all' works in the same manner under all circumstances.

# Versions and configuration

 - OS: Win7
 - Game Version: 0.D-4923-gf26f75a (experimental build 9214)
 - Graphics version: Tiles
 - Mods loaded: "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

**Comment by ifreund** [comment] 2019-06-26 19:49
Closing as a duplicate of #31677

**Closed by ifreund** 2019-06-26 19:49 UTC
