### ISSUE TITLE
Zombies won't follow player up/down stairs.

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#34164] opened 2019-09-22 01:05 UTC
# Describe the bug

I'm currently using build 9651 with experimental Z-levels enabled. I've had zombies in hot pursuit a mere step away only to get to complete safety the moment I use some stairs. They do not come into the basement, nor will any creatures in the basement venture above ground.

# Steps To Reproduce

1. Have a zombie(s) stand on/close to some stairs ready to maul you to death.
2. Go up/down some stairs.
3. Enjoy complete safety and escape from your pursuers.

# Expected behavior

Previously, zombies/creatures used to follow the player into a basement. Now they do not. Zombies should follow the player down/up stairs, especially if the zombies saw the player go into a basement.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-7798-g2da3f5e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    [DP_MOD] No Highlight [DP_No_Highlight],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    [DP_MOD] Hide STATUS [DP_No_Status_Tiles],
    No Flaming Weapons [no_flaming_weapons]
]

# Additional context

I'll post my save file just in case it's needed. I've positioned my character to be standing on some stairs with a murderous horde of zombies on every side. 

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3639217/save.zip)

**Comment by KorGgenT** [comment] 2019-09-22 01:25
this is known, and partially due to the fact that stairs do not align. I don't know if there's a copy of this issue anywhere, though.

**Comment by stk2008** [comment] 2019-09-22 11:17
the main issue I would say is monsters teleporting down stairs even though they never used the stairs :(.

**Comment by DanteTorn** [comment] 2019-09-27 03:15
This has been pretty annoying for me in conjunction with experimental Z-levels causing creatures to block stairwells but never moving off of them to allow you to pass. Turning off experimental Z-levels, reloading, and then moving through the stairwell "fixes" this though.

**Comment by Aloxaf** [comment] 2019-09-27 03:25
@DanteTorn Another solution: #34005 - Beat the bug with another bug

**Comment by gcaliber** [comment] 2020-08-09 17:40
This is also a problem with ramps now. You can avoid hordes of zombies just by going up a ramp from 1 tile away and you are perfectly safe there.

**Comment by Night-Pryanik** [comment] 2021-04-11 03:20
Tested on latest experimental as of April 11, 2021. Zombies followed me both downstairs and up on the ramp. 
Closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-11 03:20 UTC
Labels: <Bug>, Monsters, Z-levels

**Comment by eulex** [comment] 2023-03-03 22:54
On latest experimental as of today, zombies won't follow me down stairs in a subway, even with experimental z-vision turned on.

**Comment by eulex** [comment] 2023-03-03 23:01
Maybe it's related to alignment of stairs? If I stand on the stairs and peek up, I see the right tile with the stairs on the level above. However if I the press > to look down at the tile I'm standing on, another tile than the one I'm looking at will be highlighted.
