### ISSUE TITLE
Segfault crash to desktop

### ISSUE THREAD

**Issue by Yinyang107** [CleverRaven/Cataclysm-DDA#55450] opened 2022-02-16 20:49 UTC
### Describe the bug

Game crashed to desktop when trying to insert things into a first aid kit.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8083442/crash.log)

### Steps to reproduce

1. Use "insert" menu to put several medical supplies (bandages, antiseptic, gauze) into a First Aid Kit's pocket
2. Select all the items
3. Game crashed upon pressing Enter

### Expected behavior

I expected the game to not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1d9e012 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8083476/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8083477/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8083479/Save.zip)

**Comment by LeahLuong** [comment] 2022-02-16 23:46
It's possible #54941 broke something when it comes to cases like this. My guess is the game's trying fit something into the antiseptic bottle but can't because the space already has a liquid in it.

**Comment by ymber** [comment] 2022-03-05 08:34
I've reproduced this on current experimental.

**Comment by sulyi** [comment] 2022-03-08 16:21
This occurs when trying to insert item inside nested (rigid) container into parent otherwise full.
E.g.:
- start as a  **Nursing Assistant**
- drop 9 **adhesive bandages**, **pants** and **lab coat**
- insert **painkiller bottle** into **dress shirt**
- drop 1 **aspirin** pill

At this point the **dress shirt** is full, but the **painkiller bottle** inside it has enough space for a single pill.
Therefore it is possible to try inserting 1 **aspirin** pill into **dress shirt**, resulting an error.

**Comment by LeahLuong** [comment] 2022-03-09 04:35
It appears #55944 will fix this once merged. Please test on a version after that & close this issue if no longer reproducible.

**Comment by sulyi** [comment] 2022-03-09 15:09
Quick update:
It still exists on: 0.F-6668-gabad5882e2.
[bactrack.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8215458/bactrack.log)

**Comment by LeahLuong** [comment] 2022-03-10 00:35
@sulyi Ákos, #55944 merged 4 hrs after your last comment. Methinks you jumped the gun on this 1.

**Comment by sulyi** [comment] 2022-03-10 02:28
> Methinks you jumped the gun on this 1.

PR didn't have conflicts. I've compiled it locally from abad5882e2 as version number indicates.
So, I don't understand why would you do that.

**Comment by sulyi** [comment] 2022-03-10 04:52
Anyway, on cdda-experimental-2022-03-10-0222-1-g82d6010f97 I couldn't reproduce it.

**Comment by ymber** [comment] 2022-03-10 10:41
I wouldn't expect #55944 to fix this. It will make the problem rarer to find by accident but you can still manually insert things in a way that will trigger the crash.

**Comment by mqrause** [comment] 2022-10-02 00:38
> This occurs when trying to insert item inside nested (rigid) container into parent otherwise full. E.g.:
> 
>     * start as a  **Nursing Assistant**
> 
>     * drop 9 **adhesive bandages**, ~**pants** and **lab coat**~
> 
>     * insert **painkiller bottle** into **dress shirt**
> 
>     * drop 1 **aspirin** pill
> 
> 
> At this point the **dress shirt** is full, but the **painkiller bottle** inside it has enough space for a single pill. Therefore it is possible to try inserting 1 **aspirin** pill into **dress shirt**, resulting an error.

I can't reproduce this with these steps. When inserting the dropped pill into the shirt, it gets put into the bottle as expected. The only error is the message "You put your aspirin (1) into the dress shirt.", but that probably doesn't qualify as a blocker.

**Closed** 2022-10-02 02:38 UTC
Labels: <Crash / Freeze>, (S2 - Confirmed), Items: Containers
