### ISSUE TITLE
"Unable to find and assign mission target cabin" ("Recruit Tracker" mission, the one after the "Kill Horde Leader")

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47368] opened 2021-02-09 08:25 UTC
# Describe the bug
When accepting the "Recruit Tracker" mission, the game fails to place the npc to search (I think), and leaves you without a place (or way) to complete the mission.

# Steps To Reproduce

1. Load the attached save (same as the one in #47366)
2. Accept the mission to kill the Horde Leader (And wait 30 seconds for the game to respond)
3. Lie about completing it
4. Ask for new mission, accept it
5. See the bugs

# Expected behavior

To place the npc I need to search, to know where it is, and be able to complete the mission.

# Screenshots

![bug](https://user-images.githubusercontent.com/53200489/107335207-440b9c80-6a7d-11eb-86bb-77cbe778322e.png)

No coordinates shown.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9532-g57d594e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    Estadísticas a través de las muertes [stats_through_kills],
    SpeedyDex [speedydex]
]

# Additional context

 DEBUG    : Unable to find and assign mission target cabin.

 FUNCTION : cata::optional<coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 252

 DEBUG    : Mapgen update function called with overmap::invalid_tripoint

 FUNCTION : bool update_mapgen_function_json::update_map(const tripoint_abs_omt&, const point&, mission*, bool) const
 FILE     : src/mapgen.cpp
 LINE     : 6532

[Spartanburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5949848/Spartanburg.zip)

Edit: Sorry for any bad english, I corrected some of it, and added the info about versions and configuration (2 AM in my country, I need to sleep)

**Comment by Venera3** [comment] 2021-02-09 20:32
Confirmed. The quest has a relatively low search range, that part should be easy to fix. Another common thread to these issues ( ex. #47225 ) is the huge range map reveal (and consequently generate) overmaps, that might need some adjustment as well.

In the meantime, if you don't want to manually edit the value and get spoiled by the mission details, you can paste this in \data\json\npcs\, and try again.
[missiondef.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5954085/missiondef.zip)

**Comment by Termineitor244** [comment] 2021-02-09 21:50
Done, the mission generated the npc in a cabin, the cabin is excessively far away so maybe I will just create one in a not so distant forest and see if the mission chooses it instead... The Horde leader was a single city away, but this cabin... Well, whatever, thank you!! 
And, in your opinion, should I rather not have read those road maps? If these are more problems than anything, I will just ignore them until I really need them.

**Comment by actual-nh** [comment] 2021-02-09 21:58
> Confirmed. The quest has a relatively low search range, that part should be easy to fix. Another common thread to these issues ( ex. #47225 ) is the huge range road maps reveal (and consequently generate) overmaps, that might need some adjustment as well.

Where is the area centered for road maps? Ideally, they should generate a row/column or two of overmaps that's close by where they were found, but otherwise overlap as much as possible with already-generated overmaps.

**Comment by Venera3** [comment] 2021-02-10 08:35
The thing is that near as I can tell the normal mission infrastructure can only place mission objectives on overmaps that are being generated for it, not on those already set in stone. Since the maps can't generate only the roads they have to do the whole overmapgen, essentially locking that 180x180 square down for the rest of the game. Not rolling a cabin (a specific variation, in fact) is bad luck but it can happen.

I'll need to dig in the map action to be sure, but I think they're centered around the city assigned to them on spawn to prevent cheesing extra map drops.

**Comment by Zireael07** [comment] 2021-02-10 09:24
@Venera3: Looks like the game needs a way to generate just part of an overmap for mission purposes. In theory, should be doable since all mapgen is basically seeded noise...

**Comment by Venera3** [comment] 2021-02-10 10:10
After some searching, I found that there's actually a way to specify a fallback tile, which os practically unused at the moment, meaning my previous fix was more annoying than I'd like. I'll have to go over each mission and edit a sensible fallback tile/distance, so it will take a few days, but it should be way more elegant. For the big stuff (Finding Hub01 or Isherwood, for example) I don't hate the idea of sending the players on a long trek, but such generic missions should not be morr trouble that they're worth.

**Comment by Termineitor244** [comment] 2021-02-10 17:50
@Venera3 Thank you!!! That would be greatly appreciated, it makes no sense at all to travel 4 cities to reach a random guy or to complete a random mission that should be about something nearby.

And I noticed something weird in the mission, even when creating another 2 cabins nearby, the game sometimes assigned the objective to the far far away cabin, in place of the 2 nearby, any idea why? The 2 nearby cabins are valid options, I know because 50% of the time one of those 2 was chosen.

**Comment by Venera3** [comment] 2021-02-11 01:56
The mission chooses a random goal from the available ones in range, which makes simply raising the search range...a bit problematic.

**Comment by actual-nh** [comment] 2021-02-11 15:44
> The mission chooses a random goal from the available ones in range, which makes simply raising the search range...a bit problematic.

Perhaps relatively minor missions should have `"random": false`?

**Closed** 2021-02-22 07:28 UTC
Labels: Missions
