### ISSUE TITLE
Translocation gate missing - game crashes (magiclysm)

### ISSUE THREAD

**Issue by Draconus-1993** [CleverRaven/Cataclysm-DDA#63813] opened 2023-02-26 19:16 UTC
### Describe the bug

A translocation gate disappeared and now the game crashes everytime i try to teleport there

### Attach save file

[Quakertown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10834532/Quakertown-trimmed.tar.gz)

### Steps to reproduce

1 - cast the translocate self spell
2 - select albion 1
3 - crash

### Expected behavior

If the translocation point is missing the game should auto-purge it and continue as usual

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: c571723 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Arcana and Magic Items [Arcana],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Owlfren's Map Additions [owlfren_mapping],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment] 2023-02-26 19:25
Need an untrimmed save file for this one since the translocation targets are way out of the reality bubble.

**Comment by Draconus-1993** [comment] 2023-02-26 19:39
the save is too big for the upload, it's 47 mb even when zipped

**Comment by andrei8l** [comment] 2023-02-26 19:45
Use https://send.vis.ee/

**Comment by Draconus-1993** [comment] 2023-02-27 09:08
https://send.vis.ee/download/35ea123fdc20458b/#ons9Cw2sIlTlVfU79vR3FA here we are

**Comment by andrei8l** [comment] 2023-02-27 09:41
Can't reproduce. From the provided save I can translocate to all targets without issue. Using the [2023-02-27-0627 release ](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-02-27-0627)  and Arcana https://github.com/chaosvolt/cdda-arcana-mod/commit/9d96cae0c58f1bf94937454b306b302e2a8e995f. I've tried the mingw and msvc builds as well.

I don't have the `owlfren_mapping` mod as I can't find it anywhere, in case it makes a difference.

**Comment by anothersimulacrum** [comment] 2023-02-27 12:47
Since nobody can reproduce this, I'm going to close it. If someone can (or thinks it should stay open), comment and it can be reopened.

**Closed by anothersimulacrum** 2023-02-27 12:47 UTC
Labels: (S1 - Need confirmation)
