### ISSUE TITLE
Segfault Crash upon interacting with specific NPC

### ISSUE THREAD

**Issue by Fitzolir** [CleverRaven/Cataclysm-DDA#68385] opened 2023-09-28 22:20 UTC
### Describe the bug

When you interact with the Chemist NPC and ask if they've "Brewed anything new recently", the game crashes due to a Segmentation Fault.

### Attach save file

Save file attached here --> [Delco-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12754265/Delco-trimmed.tar.gz)
(This is also a really nice start if you'd like to play it; the player spawns ~42 tiles from Refugee Center)

### Steps to reproduce

1. Speak with the NPC present (Marie Puckett, chemist)
2. Navigate through the menu and ask her if she's Brewed anything new lately
3. Crash ensues

### Expected behavior

I was expecting this interaction to prompt her to tell me when she would restock her store, because many of the other vendor NPCs have a dialogue option to do so.

### Versions and configuration

**OS:** Tiny11
**Game Version:**
**Graphics Version:** Tiles, specifically UltiCa
**Ingame Language:** English
**Mods Loaded:** Dark Days Ahead, Disable NPC Needs, Portal Storms ignore NPCs (cont.)
Slowdown Fungal Growth, Blaze Industries, & Translate Complex Dialogue.

### Additional context

Crash & Debug logs: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12754290/crash.log) [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12754291/debug.log)

**Comment by gettingusedto** [comment] 2023-09-28 22:29
Duplicate of #68346

**Comment by RenechCDDA** [comment] 2023-09-29 15:44
Duplicate of #68346

**Closed by RenechCDDA** 2023-09-29 15:44 UTC
Labels: (S1 - Need confirmation)
