### ISSUE TITLE
Filter search bar is behind other menus

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#77418] opened 2024-10-29 00:11 UTC
### Describe the bug

When you try to filter in a imGui menu, the search bar is behind other elements.

This includes action menu `[Enter]` and its sub menus, execute action menu `[%]`, Butcher/disassemble menu `[B]` and debug spawn item and probably some others.

### Attach save file

N/A

### Steps to reproduce

Press `[Enter]` for action menu, then `[/]` to filter.

### Expected behavior

Expect search bar to be in front of other elements.

### Screenshots

![image](https://github.com/user-attachments/assets/ccc0e348-b9fe-4d4b-8f34-1d3f8573ec91)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.7428 (1607)
- Game Version: ad8047d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Nebnis** [comment] 2024-10-29 01:54
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/75676

**Comment by ampersand55** [comment] 2024-10-29 02:06
Ah, didn't look that far back.

**Closed** 2024-10-29 02:06 UTC
Labels: (S1 - Need confirmation)
