### ISSUE TITLE
Skylights don't allow light or sight through them

### ISSUE THREAD

**Issue by SamGondra** [CleverRaven/Cataclysm-DDA#57513] opened 2022-05-07 13:41 UTC
### Describe the bug

Skylights seem broken, as in they don't allow light through them, if you are on a roof you can also not look through them (regardless of experimental Z-vision or not).

### Steps to reproduce

1.Climb on a subway station
2.See that there are skylights installed in large portions of the roof
![SubwaystationRoof](https://user-images.githubusercontent.com/101570967/167256629-a3f9309c-b797-4557-98b9-d788808d2f63.png)
3.Climb down and enter the ground floor of the Subway Station
4.Notice it is very dark in most of the room even if you stand directly below where there should be a skylight
![SubwaystationGroundFloor](https://user-images.githubusercontent.com/101570967/167256633-6735c1c8-77ae-4ae5-8d0d-69e87b0c6c47.png)

### Expected behavior

Some amount of Light reaching down, since skylights should work like windows.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 46d0df6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Problem is also noticeable with muli Z-Level rooms in Mansions which occasionally have Glass walls that should illuminate rooms even if you close all the groundfloor curtains.
![MansionMultiZLevelRoom](https://user-images.githubusercontent.com/101570967/167256918-729819bf-3934-4b8b-b3f4-30de114b58b6.png)

**Comment by Maleclypse** [comment] 2022-05-08 04:42
Duplicate of #56901

**Comment by RoyBerube** [comment] 2022-05-08 08:19
Oops, I caused this with PR #56514. Taking a look at a way to fix this without reverting to the NO_FLOOR flag.

**Closed** 2022-05-10 20:31 UTC
Labels: (S3 - Duplicate), (S2 - Confirmed), Z-levels
