### ISSUE TITLE
Batteries' weight dependant on charge bug?

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20419] opened 2017-03-01 19:30 UTC
Version: 0.C-21449-g57cb74aaca (tiles)
Build: 6286
OS: Windows 7 Professional x64 SP1

I noticed this within the last 15 builds and I just got around to search if indeed a battery's weight does change depending on its charge.

<a href='https://postimg.org/image/wptegco0t/' target='_blank'><img src='https://s6.postimg.org/wptegco0t/Battery_weight_changes.jpg' border='0' alt='postimage'/></a>

From what I've read the weight doesn't change (what I had assumed) or it changes by a hair.
"To give you an idea, consider my laptop battery, which produces a potential difference of about 12V and can supply about 4 amp-hours of current. This battery contains about 172,800 joules of energy when charged. The equivalent mass of that energy, however, is tiny: only about 2 billionths of a gram:"
https://www.physicsforums.com/threads/weight-of-a-battery.105483/#post-870321

Is this a bug or a gameplay feature?

**Comment by Coolthulhu** [comment] 2017-03-01 19:34
A bug. We fixed it at least once.
The problem here is that batteries do not contain electricity but... more batteries. So it needs a special case. This special case breaks sometimes, causing the internal batteries to retain their weight.

**Comment by Nhatorama** [comment] 2017-03-01 19:38
Good to know. Thanks.

**Comment by ZenZen2** [comment] 2017-05-03 18:35
I see this as a duplicate of #12764
This issue is a part of the talk in there.

**Closed by ZenZen2** 2017-05-03 18:35 UTC
Labels: Battery, Bug
