### ISSUE TITLE
Cancelling the character creation menu makes newly saved presets disappear

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23895] opened 2018-05-29 18:09 UTC
Game version: 0.C-27990-g91a1db0

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
Any saved character preset should be immediately available in the New Game/Preset menu.

### Actual behavior
When saving a preset and returning to main menu instead of starting the game, the new preset isn't visible in the Preset menu until loading any savegame or relaunching the entire game.

### Steps to reproduce the behavior
- choose Custom Character
- save any preset
- exit back to menu, not starting the game
- choose New Game/Preset Character and try to find the preset you just saved
- try loading a savegame or relaunching Cataclysm, the game will display it properly this time

**Comment by BevapDin** [comment] 2018-05-29 18:54
Duplicate of #23867.

**Closed by BevapDin** 2018-05-29 18:54 UTC
