### ISSUE TITLE
Sheathing a knife in the survivor utility belt prevents you from using all its tools when doing crafting/construction/vehicle_work with the exception of screw driving.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#42448] opened 2020-07-25 18:40 UTC
# Describe the bug
Holstering a knife (a activate > 8 Use holster) or inserting a knife (i insert) in the survivor utility belt prevents you from using all its tools except screw driving.

# Steps To Reproduce
Holster a knife (a activate > 8 Use holster) or insert a knife (i insert) that will fit inside the survivor utility belt.
Attempt to use any of the belt's tools in the crafting screen, construction, or vehicle work with the exception of screw driving.

# Expected behavior
Having a knife inside the survivor utility belt should let you use the belt's tools when crafting.

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.E-4405-ge092a04d93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
I'm not sure if using the (8 Use holster) option makes unsheathing a knife quicker compared to a knife that was (i insert) in it instead.
(% Item Action Menu) actions for the survivor utility belt work as expected.

**Comment by wapcaplet** [comment] 2020-12-17 21:30
Duplicate of #40973

**Closed** 2020-12-17 21:30 UTC
Labels: (S3 - Duplicate), <Bug>, Items / Item Actions / Item Qualities
