### ISSUE TITLE
Reading while holding a lit candle makes the candle dissapear or the game to crash

### ISSUE THREAD

**Issue by GreatLurdo** [CleverRaven/Cataclysm-DDA#41286] opened 2020-06-13 16:45 UTC
# Describe the bug

When holding a lit candle and reading a book, the game prompts for a place to lit a fire. 
- If Esc is pressed or there is nothing lightable on the tile, the candle dissapears. 
- If there is something (like a sofa) on the tile, the game crashes.

# Steps To Reproduce

1. Make a player with a candle, a tool for lighting it, and a book.
2. Light the candle.
3. Read the book "until you gain a level".
4. When some reading time passes, the game prompts for a directon "Light where?"
5. If Esc is pressed, or there is nothing to lit a fire in that direction, the candle just disappears. If there is an object there (like a sofa), the game crashes. 

# Expected behavior

The game should not prompt for a direction to light whem reading a book. 
The candle should not disappear, nor the game crash.

# Screenshots

![Screen 2](https://user-images.githubusercontent.com/66877699/84574110-cb94f480-ada4-11ea-8c55-620c41c3c3d0.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3159-g3f48507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Atteched logs of the crash outcome:

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4774999/debug.log)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4774998/crash.log)

**Comment by Jerimee** [comment] 2020-06-21 22:17
Experienced similar issue when placing lit candle on table and then attempting to read - causes game to crash consistently.

**Comment by hexagonrecursion** [comment] 2020-06-23 13:43
Duplicate of: #41286?

**Comment by Night-Pryanik** [comment] 2020-06-23 14:55
@hexagonrecursion you're linking to this very PR.

**Comment by hexagonrecursion** [comment] 2020-06-23 15:45
Sorry. I meant to say duplicate of: https://github.com/CleverRaven/Cataclysm-DDA/issues/40858

**Comment by anothersimulacrum** [comment] 2020-06-23 16:16
That doesn't mention a crash, like this does.

**Comment by hexagonrecursion** [comment] 2020-06-23 16:48
This also mentions a crash https://github.com/CleverRaven/Cataclysm-DDA/issues/41051#issuecomment-642367635

**Comment by Ramza13** [comment] 2020-10-19 23:31
Could not reproduce

**Comment by anothersimulacrum** [comment] 2020-11-08 07:16
No news in close to 3 weeks? Probably resolved.

**Closed by anothersimulacrum** 2020-11-08 07:16 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
