### ISSUE TITLE
Rags balance

### ISSUE THREAD

**Issue by GOTTADOFAST** [CleverRaven/Cataclysm-DDA#12562] opened 2015-06-06 08:15 UTC
Hey! Hoodie gives too many rags. Too make hoodie you need 12 rags and 14 threads. So, if you butch it, you gain 17 rags (in average). 
Same situation with cargo pants. Sometimes you get more rags, than to create it.
0.C 3258
##

**Comment by FireCrow1973** [comment] 2015-06-06 10:00
this kinds of issues are all over the place.

so i was wondering, if we should use this thread as a list, where people can add these inconsistencies as they happen!

cause we need some place where these things can go, there not getting fixed by us wanting them to all show up in one place.
there getting fixed, by us putting them in one place.

**Comment by Coolthulhu** [comment] 2015-06-06 12:21
I ran a script to check all recipes made only of cotton, leather, plastic, kevlar and wool for cost lower than volume:
* Western boots: 10/9 volume/material cost
* Cargo pants: 9/8
* Sleeveless leather duster: 28/24
* Denim shorts: 5/4
* Jeans: 8/6
* Hoodie: 17/12
* Wool hoodie: 18/12
* Sleeveless duster: 18/12
* Duster: 23/15

**Comment by FireCrow1973** [comment] 2015-06-06 14:41
Holy cow, you can do that!
He can do that?

can we do that for all crafting recipes?

**Comment by DavidKeaton** [comment] 2015-06-06 16:26
Yeah, he wrote a script to parse the json. May not be a bad script to upload to the repo @Coolthulu.

**Comment by Coolthulhu** [comment] 2015-06-06 19:49
It's a relatively simple (70 lines total) Python script. Not sure where would it "fit" in repo, though.

**Comment by DavidKeaton** [comment] 2015-06-06 20:37
`tools/json_tools` would be a good spot. If it can help it's worth an upload, and it'd make a good "conservation of mass" tool.

**Comment by PropaneSoup** [comment] 2015-06-06 21:52
Well this is all easy to fix though, right? Just increase the cost of the recipe to be a few more than its volume.

**Comment by Rivet-the-Zombie** [comment] 2015-06-06 22:11
>Just increase the cost of the recipe to be a few more than its volume.

Somebody PR this and I'll merge it post-haste.

**Comment by FireCrow1973** [comment] 2015-06-06 22:33
I think the point here is not, can we fix these issues listed above.
but rather can we detect(find and fix) the rest of the discrepancies.

cause if we had a automatic way of finding and fixing all the stuff, well that would be pretty sweet.

**Comment by DavidKeaton** [comment] 2015-06-06 23:12
Oh @Coolthulhu ... ;-)

**Comment by Coolthulhu** [comment] 2015-06-06 23:44
OK, I checked out the tools and it looks like they're more of a local thing than a verifier. What we need is something that will make Jenkins complain whenever any of the recipes has volume > cost.

@narc0tiq handles Jenkins, right?

**Comment by DavidKeaton** [comment] 2015-06-07 00:43
you could always make a new folder, but I digress. A failed build order like that may make PR for items a bit harder to the public.

**Comment by Coolthulhu** [comment] 2015-06-07 01:09
Correction: it could make PRs with incorrect volume/cost harder, proper PRs would work just fine.

Though I'm not sure if it's worth the effort. Only the 9 items have wrong volume/cost ratios. Just fixing this once would be enough.

I could also run a script to get all the items with improper materials to prevent plastic from rags and that probably wouldn't be worth a dedicated script either.

**Comment by DavidKeaton** [comment] 2015-06-07 02:29
No, but I was merely suggesting it'd be a nice tool for others.

**Comment by kevingranade** [comment] 2015-06-07 02:48
I agree it'd be nice to have the script in the repo as a checker, even if
it doesn't get run automatically.
Medium-term I'd like to sort out something for automatically running unit
tests and data checkers on pull requests, hopefully jenkins and/or jently
has something that will work for that, but regardless we'll sort something
out.
The issue is it allows arbitrary people to run code on the jenkins server,
not sure offhand how to make that safe.

**Comment by DavidKeaton** [comment] 2015-06-07 02:58
I wouldn't be too keen allowing it at all, IMHO.

**Comment by Coolthulhu** [comment] 2015-06-07 04:17
I didn't mean running an arbitrary script on Jenkins/Jently, just adding another one to the list of the executed ones. The bot checks for json sanity, so it could also check for "json interpretation" sanity.

Having a local set of verification scripts, executable with something like "make verify" would easily be enough. For this particular issue, even this would be an overkill, though.

On a side note: I modified the script to test for items crafted from rags, leather etc. and having more materials than just those. Didn't find anything. This means that the duffels and backpacks were the last single-step cotton->plastic converters.
There are still some methods of making cotton into plastic, but they're more complicated. For example, XL jumpsuit is made from rags, cargo pants and a t-shirt (all cotton and made from rags), but has a plastic material.

**Comment by narc0tiq** [comment] 2015-06-07 13:57
@kevingranade 
> The issue is it allows arbitrary people to run code on the jenkins server, not sure offhand how to make that safe.

The way we fix that for chkjson is to have the pull-request checker bail early if `chkjson.cpp` or its dependencies are different from the version in the blessed master. It's relatively easy to add more files to the same check, and it's more a tripwire than true protection (limited access and twice-daily backups are in place for that).

@Coolthulhu 
> I didn't mean running an arbitrary script on Jenkins/Jently, just adding another one to the list of the executed ones.

These are equivalent for Jently because a PR could contain any change whatsoever, including changes to the makefile (e.g., `make json-check` changed to include a step to `rm -rf --no-preserve-root /`) or changes to the code that is about to be (compiled and) executed (e.g., `src/chkjson/chkjson.cpp` could include a call to `unlink("/etc/passwd")` or something similarly stupid).

As stated above, we prevent this by having a check in the build script (intentionally not part of the repo!) which fails the PR build (suggesting to maintainers that they be careful when merging) if the PR changes sensitive code. The check currently reads:

```sh
for i in Makefile src/json.{h,cpp} src/chkjson/chkjson.cpp; do
    diff -q ~/cataclysm-reference-repo/${i} ${i}
done
```

It would be trivial to add `json_tools/some_sanity_checker.py` to the list.

**Comment by Zireael07** [comment] 2015-06-07 14:29
+1 to adding a sanity checker to Jenkins.

**Comment by FireCrow1973** [comment] 2015-06-07 16:38
There was this problem with the bow taking thread and giving long string.
(Its fixed now)
Will this script discover that to, even when it doesn't contain fabric?

**Comment by Zireael07** [comment] 2015-06-07 16:41
@FireCrow1973: Created items now remember what they were created from, so the problem doesn't exist.

**Comment by FireCrow1973** [comment] 2015-06-07 16:46
Yes, and thanks for that!
But i'm sure we will add more crafting recipes in the future.
Will this script check for known clothing related recipes?

**Comment by DavidKeaton** [comment] 2015-06-07 17:05
Known in what sense?

**Comment by FireCrow1973** [comment] 2015-06-07 17:12
Non clothing related recipes.
I do apologize for that!
:-)

**Comment by DavidKeaton** [comment] 2015-06-07 17:55
All good. :-) I'm sure it can be extended, python is a p relaxed language.

**Comment by Leland** [comment] 2017-05-04 00:28
Very old issue and no recent discussion – closing. Feel free to let me know if you want it reopened.

**Closed by Leland** 2017-05-04 00:28 UTC
Labels: Balance
