### ISSUE TITLE
Alcohol Metabolism Alcoholic

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#16706] opened 2016-05-16 10:45 UTC
With a character i play now that started out with the Alcohol Metabolism mutation i notice she never become an alcoholic with all hard alcohol and cheap wine she consumes :P.
I personally think there should be SOME downside to drinking a crapton of alcohol without getting drunk or worse.

Obviously she doesn't get the vitamins she needs by doing that.

**Comment by player0981234** [comment] 2016-05-16 11:31
does that impact her health

**Comment by Coolthulhu** [comment] 2016-05-16 15:15
Alcohol diet is only really worth it for carnivores. It kills your health when you consume enough of it to matter.

**Comment by Hague** [comment] 2016-05-16 23:07
Bloody Mary time! Speaking of which, there ought to be a recipe for those... Can of v8, some vodka, a veggie garnish and some pepper or season salt.

**Comment by AppleConnoiseur** [comment] 2016-05-18 13:12
Hehe, more alcoholic drinks could be nice. Even have stuff like [Underberg](https://en.wikipedia.org/wiki/Underberg). Maybe even make it healthy if you can handle the alcohol by making a alcohol drink with vodka, carrot juice and multivitamins mixed in for good measure.

The Witcher approach on potions were interesting in that they were alcohol based so if you drank enough you fought like crap. But then this is not even that low fantasy as The Witcher.

I wonder, wouldn't the **Ethanol Burner CBM** and **Alcohol Metabolism mutation** **_compete_** for the alcohol you consume? Like one cancelling out the other depending on who got their hands on the alcohol first. Just a thought.

**Comment by Coolthulhu** [comment] 2016-05-18 13:23
> I wonder, wouldn't the Ethanol Burner CBM and Alcohol Metabolism mutation compete for the alcohol you consume?

They probably should. The problem is, they're handled in two different places.

**Comment by illi-kun** [comment] 2016-05-18 13:50
> Maybe even make it healthy

AFAIK, ethanol is a bad helper for vitamin absorbability.

Random article describes a bad long-term effects of alcohol as follows:
> People who abuse alcohol daily often develop vitamin and mineral deficiencies because alcohol interferes with the body's ability to absorb nutrients.

**Comment by AppleConnoiseur** [comment] 2016-05-18 16:35
Interesting. Maybe it could apply a hidden debuff that makes vitamin intake worse? So not even munching a multivitamin after will fix it.

**Comment by Coolthulhu** [comment] 2016-05-18 16:42
No need for that. Nerfs should hit things that are too strong and alcohol consumption is nowhere near that.

**Comment by kevingranade** [comment] 2016-05-21 18:31
A way around this is to have alcohol consumption apply a condition
indicating the level of inebriation (effectively BAC). Then anything
consuming alcohol could reduce this effect.
Alternately ethanol burner could/should make the ethanol bypass inebriating
the player entirely, it never enters the bloodstream, right?

**Comment by Coolthulhu** [comment] 2016-05-21 18:38
> A way around this is to have alcohol consumption apply a condition indicating the level of inebriation (effectively BAC). Then anything consuming alcohol could reduce this effect.

This would get rid of alcmet binges though. And those are pretty convenient.
Current functionality allows downing a bottle of vodka using just alcmet, without having to wait it out. If it was done using effect+consumption, it would make it possible to get drunk enough to vomit out the alcohol, which would mean having to dose drinks.

Unless alcmet also prevented vomiting (and possibly other penalties) from drunkeness, which would make sense since vomiting is there to remove poisons from organism.

**Comment by kevingranade** [comment] 2016-05-23 08:06
Obviously various mutations could change how it works, by "effect" I simply
mean something to track intensity, it doesn't necessarily mean the side
effects of drunkenness have to be applied with the same mechanism.

**Comment by Leland** [comment] 2017-05-03 23:59
Old suggestion and no recent discussion here. Closing.

**Closed by Leland** 2017-05-03 23:59 UTC
Labels: Balance, Suggestion (Discuss)
