### ISSUE TITLE
Canned Goods are bugged

### ISSUE THREAD

**Issue by supaFool** [CleverRaven/Cataclysm-DDA#40872] opened 2020-05-26 22:15 UTC
Can no longer put any type of canned good in inventory.

# Steps To Reproduce
Start world, try to place any type of canned good into inventory

# Build
Build 10695

**Comment by KorGgenT** [comment] 2020-05-27 00:20
![image](https://user-images.githubusercontent.com/30208401/82962479-5943a800-9f8e-11ea-80e3-0f9a258b371e.png)
this issue is not specific enough to debug.

**Comment by supaFool** [comment] 2020-05-27 00:29
Any canned good you find and try to put in Invo it says "You can't put this in a backpack while there is still liquid in it" 
![Capture](https://user-images.githubusercontent.com/5287812/82962931-98bec400-9f8f-11ea-9379-5f1f1a921ede.PNG)

**Comment by KorGgenT** [comment] 2020-05-27 00:30
Duplicate of #40127

**Closed by KorGgenT** 2020-05-27 00:30 UTC
