### ISSUE TITLE
Antiseptic disappears when used more than once.

### ISSUE THREAD

**Issue by DeclanFrost** [CleverRaven/Cataclysm-DDA#40370] opened 2020-05-09 01:41 UTC
# Describe the bug
Antiseptic, applied once, disappears when applied again.

# Steps To Reproduce
1. Pick up small bottle of antiseptic.
2. "A"pply antiseptic to injury.
3. "A"pply again.
4. Mourn

# Expected behavior
Should get more than one use out of a bottle of 10 units antiseptic.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1933-gdba5bd1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

# Additional context
[auto_before_launch110.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4602438/auto_before_launch110.zip)

**Comment by mrkybe** [comment] 2020-05-09 02:43
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40228

**Closed** 2020-05-10 13:39 UTC
