### ISSUE TITLE
Debug Dialog box behind imgui interface

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76207] opened 2024-09-05 08:10 UTC
### Describe the bug

If you want to enter a value in a popup dialog box, it appears below the imgui and makes it really hard to use debug tool.
1st image is trying to change bday of an item
2nd image is trying to use the '/' filter on the spawn item interface. if you look REAAAALLY close, you'll see the filter dialog box behind the transparent item spawn menu

### Attach save file

N/A

### Steps to reproduce

1. try to change bday value on an item using the debug menu
2. notice value dialog box pops up underneath the imgui

### Expected behavior

dialog box is above imgui interface

### Screenshots

![image](https://github.com/user-attachments/assets/4b8c36ea-a5ce-41ef-b834-856649a0a525)
![image](https://github.com/user-attachments/assets/c6af63ef-afd8-4bf5-be9d-de29578ea7e6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-04-0626 0c909b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment] 2024-09-05 12:00
Duplicate of #75676

**Closed by NetSysFire** 2024-09-05 12:00 UTC
Labels: (S1 - Need confirmation)
