### ISSUE TITLE
Crash or multiple save files when game saves

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33169] opened 2019-08-12 16:42 UTC
# Describe the bug

After Quicksave the game crashed and the old save file got another copy.

# Steps To Reproduce

1. Create a new world and a player and start the game.
2. Select Quicksave in the Esc menu.
3. Game crashed and a new copy of the save file is created.

# Expected behavior

A normal saving experience.

# Screenshots
(failed to upload it & don't know why)

# Versions and configuration

 - OS: [Android]
 - Game Version: [0.d-6462-g599fa7-blabla(cataclysmdda-0.d-9475.apk)]
 - Graphics version: [Tiles]
 - Mods loaded: [dda]

# Additional context

**Comment by anothersimulacrum** [comment] 2019-08-12 17:16
Duplicate of #33051

**Comment by ZhilkinSerg** [comment] 2019-08-12 17:27
Should be fixed in upcoming build 9477.

**Closed** 2019-08-12 17:26 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
