### ISSUE TITLE
Segfault when firing bionic ranged weapon

### ISSUE THREAD

**Issue by swwu** [CleverRaven/Cataclysm-DDA#45344] opened 2020-11-11 04:09 UTC
# Describe the bug

A segmentation fault occurs when attempting to fire some bionic ranged weapons (e.g. `bio_laser`).

# Steps To Reproduce

1. Make a player with the `bio_laser` bionic and sufficient power to fire it.
2. Find or spawn something to shoot at.
3. Activate the bionic and fire at the target from step 2.

# Expected behavior

The bionic should fire without causing a segmentation fault.

# Screenshots

# Versions and configuration

This issue occurs on current `master` 4c8241733b07924a8a97e89148bb96c33d3ac677 compiled with flags `CLANG=1 TILES=1 LOCALIZE=0` 
It probably occurs with other flags too, but it takes literally an hour to compile and it seems unlikely to be specific to these compile flags so I haven't investigated exhaustively.

# Additional context

**Comment by swwu** [comment] 2020-11-11 04:19
Made a fix for it in #45345. Let me know if this cross-cuts or interferes with behavior that I'm not aware of.

**Comment by x7GoSu** [comment] 2020-11-11 04:53
The crash seems to be happening with all monsters that shoot as well. Should I make a separate bug reports?

**Comment by anothersimulacrum** [comment] 2020-11-11 04:56
Duplicate of #45323

**Closed by anothersimulacrum** 2020-11-11 04:56 UTC
Labels: (S3 - Duplicate)
