### ISSUE TITLE
Tone Down the Hub01 Spybot spawn

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#53358] opened 2021-12-11 09:05 UTC
### Describe the bug

Can the Hub01 Spybot spawn be toned down a lot? I get the idea behind them but they are litterly a reason as to why not do the hub 01 quests because they trash your whole gameworld.
+ If you go to an empty space to craft and sleep they spawning can draw enemies to you and slow down the game.

I included a picture for reference. 

### Steps to reproduce

Do the Hub01 Quests
Get overwhelmed with the hub01 spybot spawn

### Expected behavior

Maybe limit spawning them to only when you do have a quest for hub01 running? because spawning them forever even if you arent doing quests for them seems annoying especially since they can draw aggro from zombies and lead them to you.

if you still gotta spawn them limit them to like max 1 per 2 days.

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/145670672-14af616f-995c-4c06-90ce-3b08c7ec4ec4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: c6f4ab5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I dont think they are generally a bad idea, but they are too many, like insane amounts of them and they are annoying as hell the more you play.

**Comment by Proxima-b** [comment] 2021-12-15 02:27
WIll the destruction of hub01 resolve this issue ?

**Comment by estebandellasilva** [comment] 2021-12-15 15:37
> WIll the destruction of hub01 resolve this issue ?

I only do that to hotels or Forests, but i never checked

**Comment by catdach** [comment] 2021-12-17 04:19
From digging through the spawn conditions for the bot, it looks like it's supposed to spawn one about 7-14 days after you talk to the terminal. so talking to the terminal basically gives you a debuff that pawns the thing. My guess is that it doesn't have a cap for how often it spawns in the 7-14 day window. Or there isn't a cap on how many times you can be given the debuff, so if you talk to the terminal a lot(even just to trade), you get another debuff. You might even get the debuff more than once per conversation with the terminal. It could even be a combination of all these things, I'm not sure, I honestly don't understand the code very well. Regardless its going to take a long time to trouble shoot.

**Comment by John-Candlebury** [comment] 2021-12-17 05:08
Yeah unless theres some weirdness going on with stacking effects/EOCs the robots should only spawn for 14 days after interacting with the intercom, a camspy has a chance to spawn every two days, and at least one should spawn every seven days. 

If you have more than one spawning in the same day, theres definitely some weirdness going on.

**Comment by estebandellasilva** [comment] 2021-12-18 16:05
Whenever i visited i was trading with the intercom - often times multiple times as i could not carry all the loot and had to look up how much money they have so this could be a possible reason.

And as i said often times 2 or 3 Spybots would spawn very fast after each other

**Comment by Ilysen** [comment] 2022-04-19 13:47
This happens because the surveillance EOC is run every time you open the services menu via `[Identify yourself before the intercom.]`. It functions by immediately spawning a camspy drone, then queueing itself to run again between 1 to 7 days from now, with the valid conditions either having the ancillary trait or having the surveillance effect itself (which is 14 days long when it's given to the player).

Since the EOC is run again each time you open the services menu, it'll spawn a camspy every time you do so. You can reproduce this by opening it a bunch of times on a debug world with no camspies visible, and rapidly accrue a bunch of the little buggers. A fix for this might be to use the `recurring` framework that now exists for EOCs, keep the existing activation conditions, and removing the self-queueing part entirely. Not sure if this is bad code smell, though.

**Closed** 2022-04-21 20:32 UTC
Labels: Missions, Spawn
