### ISSUE TITLE
The Unseen Hunter is cheating

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69382] opened 2023-11-14 13:49 UTC
### Describe the bug

The Unseen Hunter "uses the darkness to regenerate" while lit up both by my character's flashlight and my bikes MC headlight.

### Attach save file

N/A

### Steps to reproduce

1. Try to get anywhere in unexplored subway tunnels using a vehicle with a headlight, such as a foldable vehicle with battery, headlight, and electronics control unit.
2. Get attacked by an Unseen Hunter (there seems to be one every 5 tiles or so...
3. Damage the critter.
4. See it sitting in the splendid glory of both the inner flashlight circle and the vehicle headlights and still Regenerate In The Darkness (of its mind?).

### Expected behavior

It should only regenerate when not lit.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-5165-g433658ce70 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms.

### Additional context

There's a silly amount of high level monster in the subway tunnels even with a reduced monster density. Bring lots of spare mags for your elephant guns.

**Comment by fairyarmadillo** [comment] 2023-11-14 14:54
For some reason the flag is set to work at anything less than 10000 illumination, the brightness of a floodlight. I believe its regeneration scales inversely proportional to the light, but the messaging never changes and the difference in brightness is not information that the player can see or even discover without looking at the code.

**Comment by RenechCDDA** [comment] 2023-11-15 11:18
Duplicate of #67027

**Closed by RenechCDDA** 2023-11-15 11:18 UTC
Labels: (S1 - Need confirmation)
