### ISSUE TITLE
Remington 700 .30-06 does not reload properly

### ISSUE THREAD

**Issue by MarceloLaser** [CleverRaven/Cataclysm-DDA#41999] opened 2020-07-10 05:23 UTC
# Describe the bug

Gun reloads are unreliable. Not even sure what's causing it, but most of the time it does not reload, and then once in a while it reloads properly. Still consumes ammo every time. Attaching a save game at the exact situation where I found reloading not to work, in hopes that it will help pinpoint the issue.

# Steps To Reproduce

1. Load provided save game
2. Reload Remington 700 .30-06, which is in inventory
3. Cry as the ammo is sucked into the void
3a. Stare in deep vexation if/when the ammo is not, in fact, sucked into the void

# Expected behavior

Gun reloads properly, rather than devouring ammo.

# Versions and configuration

10820

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3911-g312db57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

[Prathersville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4901113/Prathersville.zip)

**Comment by Muffindrake** [comment] 2020-07-10 12:52
![1594384341](https://user-images.githubusercontent.com/19580030/87154853-39581180-c2ba-11ea-86ad-876ab6db31f5.png)

There appear to be issues with reloading guns if some ammunition is `f`avourited while the rest is not. The ammo doesn't disappear, it's just 'loaded' into the gun. In fact, when you `w`ield the rifle in the inventory when first loading the save file, 6 .30-06 appear on the floor.

It seems this issue occurs only with guns that are reloaded one cartridge at a time, was unable to reproduce it with a gun that uses magazines such as the Barrett.

I was able to somehow duplicate ammo this way, but I'm not sure how exactly.

I get a warning about Arcana not existing while loading this. No idea whether any of those mods can cause issues.

(tested in 0.E-3923-g7063a531e9)

**Comment by kevingranade** [comment] 2020-12-17 05:39
Fixed by #46000

**Closed** 2020-12-17 11:33 UTC
Labels: (S2 - Confirmed), <Bug>, Items: Ammo
