### ISSUE TITLE
More Locations mapgen error

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15049] opened 2016-01-27 21:24 UTC
https://i.imgur.com/ex1PkH8.png

omtype 3storyA_roof_west, "house roof" (id_mapgen 3storyA_roof) seems to be missing?
This happens fairly regularly as I enter a new city.

In 0.C-9701-g3e9dc60

**Comment by DeadLeaves** [comment] 2016-01-27 22:36
I get the same in build 4231

**Comment by Leland** [comment] 2017-05-04 03:48
We haven't seen any more tickets regarding this, and I can't find anything about it on the forums. I also have been unable to reproduce this. Closing for now – if you still encounter it, let me know here and I'll reopen the issue.

**Closed by Leland** 2017-05-04 03:48 UTC
Labels: Bug, Mapgen, Mods
