### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by greatjailb8** [CleverRaven/Cataclysm-DDA#45340] opened 2020-11-10 20:42 UTC
# Describe the bug
I crash after moving two tiles. 

# Steps To Reproduce
1. Size of cities 13
2. City spacing 2
3. Initial day 45
4. Spawn delay 9999  

# Expected behavior
Once you're in the game to 30+ minutes in-game, the game just crashes. 

# Screenshots                    
I move two tiles to the left and I crash :(
![Screenshot (9)](https://user-images.githubusercontent.com/74266779/98729641-10bb5380-2350-11eb-80ae-c98a1b116e4c.png)
                     

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.E-7486-g34527a6
 - Graphics version: Tiles
 - Ingame language: English

# Additional context                              
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5520010/crash.log)                              
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5520012/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5520014/Save.zip)
Hurray I know how to make a bug report now 👯‍♂️

**Comment by andrei8l** [comment] 2020-11-10 20:48
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45323. There is a fix pending already

**Comment by greatjailb8** [comment] 2020-11-10 21:25
Thanks

**Closed** 2020-11-10 21:25 UTC
