### ISSUE TITLE
Flammable arrows cannot be loaded and stored in quiver

### ISSUE THREAD

**Issue by tianjiuyihu** [CleverRaven/Cataclysm-DDA#63234] opened 2023-01-22 10:15 UTC
### Describe the bug

Flammable arrows that are not ignited cannot be fired as ammunition and cannot be stored in quiver

### Steps to reproduce

1. wield your bow, and press "f" to fire
2. Flammable arrows don't appear in the options.
3. put on the quiver, and press "i" to insert arrows
4. Flammable arrows don't appear in the options.

p.s. flaming arrow(active) can be chosen

### Expected behavior

Flammable arrows can be fired or stored in the quiver like an ordinary arrow.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: bb53c11 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝) [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    余波未尽 [aftershock],
    翻译晦涩对话 [translate_dialogue],
    杀怪提升属性 [stats_through_kills],
    驯服野兽 [Tamable_Wildlife]
]

**Comment by cake-pie** [comment] 2023-01-24 17:24
Duplicate of #59365

**Closed** 2023-01-25 02:36 UTC
Labels: (S1 - Need confirmation)
