### ISSUE TITLE
Escaping from Wear and throw menus shows misleading message

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18704] opened 2016-10-09 17:41 UTC
Hitting ESC in the Wear and in the throw menus displays "You don't have that item." message in the log whereas other menus show more appropriate "Never mind." message.
IMO, there should be no message at all when you just leave the menu... This is how the drop menu behaves right now...

Small addition to that: Escaping back from the "Escape menu" shows an erroneous "Unknown command: ' '" message in the log.

**Comment by Leland** [comment] 2017-05-25 01:43
<kbd>esc</kbd> from the Wear menu shows the appropriate log now. Throw and escaping from the Escape menu both still exhibit the issue described, however.

**Comment by Qrox** [comment] 2017-05-25 03:34
Another similar issue: escaping from the wield/wear popup when the player has no available inventory space when picking up a power armor from the ground will display "You can't wear power armor over other gear!"

**Comment by Ramza13** [comment] 2020-01-03 00:44
Just tested and could not reproduce the issues described.

**Comment by Night-Pryanik** [comment] 2020-01-03 05:07
Both Wear and Throw menus show "Never mind" message when escaping, closing.

**Closed by Night-Pryanik** 2020-01-03 05:07 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface
