### ISSUE TITLE
Segmentation fault on comparing items

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#34919] opened 2019-10-21 14:34 UTC
# Describe the bug
Trying to compare items while applying different filters to select them results in segfault crash.

While trying to compare items from compare interface, selecting second item to compare results in segfault. Works for some items, others compare without error. When selecting same items that resulted in an error manually, i.e. without using filters, compare works without errors.

# Steps To Reproduce

0. Load the only character from River Pines world.
1. Open Compare Items screen by pressing I;
2. press "/", type "mono", press Enter;
3. select monocle by pressing right arrow;
4. press "/", type "pair of ballistic", press Enter;
5. pressing right arrow to select pair of ballistic gloves always results in segfault crash. Plus sign doesn't even appear near them, game crashes before actually selecting them. Or, at least, before interface showing it.

# Expected behavior
Items comparing as usual, without game crashing.

# Screenshots

# Versions and configuration

21:16:44.298 :  GAME REPORT:
- OS: Windows 7 max(v6.1 b7601 sp2)
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8700-g7787bc0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3751308/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3751309/debug.log)
[River Pines.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3751315/River.Pines.zip)

**Comment by ZhilkinSerg** [comment] 2019-10-21 15:01
Duplicate of #34046

**Closed by ZhilkinSerg** 2019-10-21 15:01 UTC
