### ISSUE TITLE
Game freeze/hang on load, debug log being spammed

### ISSUE THREAD

**Issue by BrokenPaw-0-1** [CleverRaven/Cataclysm-DDA#41834] opened 2020-07-04 15:36 UTC
**Describe the bug.**

I went to sleep after saving my game last night. Woke up today and tried to load my last saved game. The game refuses to load and hangs/freezes as the debug log is spammed with error messages. Trying to "i" or "I" the error does nothing to stop the hanging/debug spam.

**Steps To Reproduce.**

1.) Start up game.
2.) Load the world and save game.
3.) Wait for eventual hang/freeze as the game is unable to launch the save.

**Expected behavior.**

The game to load so I can continue my adventure. Not sure why this error message is being looped like it is.

**Screenshots.**

N/A

**Versions and configuration.**

I cannot generate a game report as the world will not load and hangs/freezes on load.

 - OS: Win10
 - Game Version: 0.E-3725-g69cf449
 - Graphics version: Uh, Tiles.
 - Ingame language: English
 - Mods loaded: d.d.a, alt map key, stats thru skills

**Additional context.**

**Add any other context about the problem here.**

-Save
-Debug log
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873079/save.zip)
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873080/debug.log.zip) (52mb file)

Any insight as to what's happening or how I can fix this (I hopefully can, else this character and world is donezo).

**Comment by anothersimulacrum** [comment] 2020-07-04 16:47
Duplicate of #41648
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873260/save.zip)
One of your maps contained a leg rig with ~200k crowbars in it. The save above has that fixed.

**Closed by anothersimulacrum** 2020-07-04 16:47 UTC
Labels: (S3 - Duplicate)

**Comment by johnrdconnolly** [comment] 2020-07-14 13:40
> Duplicate of #41648
> [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873260/save.zip)
> One of your maps contained a leg rig with ~200k crowbars in it. The save above has that fixed.

Wondering your process for sifting through the o.x.x files to find the offending containers? I definitely have the same problem and am having a hard time locating the problem on my own.

**Comment by anothersimulacrum** [comment] 2020-07-14 14:26
I use a debugger to find the id of the affected item/map files.
