### ISSUE TITLE
Craters are flammable

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11012] opened 2015-01-27 10:23 UTC
The rocky rubble in the craters can be lit on fire and the fire will spread to nearby rubbles, resulting in a HUGE inferno spanning several map tiles that killed my computer with lag.

Interestingly lighting it with lighter only produce local fire that doesn't spread, but shooting it with flamethrower and the fire will spread.

Can't we just remove flaming weapons from NPCs?

**Comment by Barhandar** [comment] 2015-01-27 11:41
>Can't we just remove flaming weapons from NPCs?

But that would just be not **!!FUN!!**.

**Comment by aierce** [comment] 2015-01-27 11:50
rocky rubble don't have the flammable flag, don't see how they are spreading the fire

**Comment by Esavier** [comment] 2015-01-27 12:01
maybe terrain have some kind of flags like nearby fungal towers (yeah ground there is also flamable)

**Comment by Barhandar** [comment] 2015-01-27 12:02
Lemme make a not-completely-educated-and-likely-wrong guess: something in the fire code assumes all rubble (or furniture!) is flammable using a wildcard matching, rocky rubble hits the wildcard, but that code doesn't handle the furniture actually _burning down_, and rocky rubble has no code to "burn down", resulting in undying raging fire.

**Comment by aierce** [comment] 2015-01-27 12:03
metal wreckage is also furniture and that doesn't spread fire (both flamethrower and lighter)

**Comment by Barhandar** [comment] 2015-01-27 12:05
>maybe terrain have some kind of flags like nearby fungal towers (yeah ground there is also flamable)

Terrain there is named "dirt", and only "dirt" that is flammable (but would likely burn down just fine) is open palisade gate.

>metal wreckage is also furniture and that doesn't spread fire (both flamethrower and lighter)

Then it's not blanketing furniture.

**Comment by BevapDin** [comment] 2015-01-27 14:08
I'm unable to reproduce this, @aierce did you check there are no flammable items under the rubble (you can use the debug map editor to inspect items on a map square without any restrictions).

A lighter produces a fire with density 1,  flame thrower can produce them with higher density. Fire with density 1 does not spread (or at least it's very unlikely). If there are no items / terrain / furniture that fuel the fire to a higher density, it won't be able to spread.

**Comment by aierce** [comment] 2015-01-27 14:17
The fire only spreat with a flamethrower, not a lighter, use it on a rocky rubble spawned with the crater. playing with experimental build 2679.

I just reproduced this again, the fire quickly spreat to all the rocky rubble tiles, but no further. It worked with simple flamethrower, flamethrower, and the rm451 flamethrower. I checked with the map editor. Nothing under the rubble except dirt.

**Comment by Barhandar** [comment] 2015-01-27 14:36
I'm on 2657 and incendiary grenade ignited a raging fire, which spread over an entire crater just fine.

**Comment by KA101** [comment] 2015-01-27 22:19
Raging fires in particular specifically spread/increase fire density in other tiles: that's one of the major dangers of 'em.

**Comment by aierce** [comment] 2015-01-27 22:59
Yeah I know, but the point is the rocky rubble shouldn't be flammable. Flamethrowers don't have the same effects on other similiar terrain/furniture.

**Comment by Barhandar** [comment] 2015-01-28 01:34
>Raging fires in particular specifically spread/increase fire density in other tiles: that's one of the major dangers of 'em.

Raging fires in craters, besides the obvious "unless it's made out of anthracite, it won't burn" bit, are infinitely self-sustainable and will never burn out because raging fire going out is replaced by raging fire "spreading" from adjacent tile, and there's nothing to consume.

**Comment by BevapDin** [comment] 2015-04-04 15:00
As @aierce figured out in https://github.com/CleverRaven/Cataclysm-DDA/issues/11520#issuecomment-78143431, this is caused by using the Vehicle Additions Pack (which was *not* noted in this issue at all), which makes rock into an ammo type, which in turn makes it flammable. This is also the reason it can not be reproduced in a default game (without the mod).

This is a duplicate of #11520 and as such should be closed. Fixing #11520 will also fix this.

**Closed** 2015-04-04 16:41 UTC
Labels: Balance, Duplicate, NPC, Performance
