### ISSUE TITLE
Many ncurses menus are broken

### ISSUE THREAD

**Issue by SandwichPie** [CleverRaven/Cataclysm-DDA#75897] opened 2024-08-23 12:19 UTC
### Describe the bug

Since I posted #75802 many more menus than just the y/n promps have stopped rendering properly rendering the curses version of the game unplayable.

I believe the issue has extended to at least any menu that displays a list of items that can be scrolled though, see the attached segment of the inventory screen.

When loading a game, the loading status where giving information on what is being loaded doesn't render at all and is just a black screen.

### Attach save file

N/A

### Steps to reproduce

Just flick through menus. It really won't take long to see the problem. Make a world and try to reset it, or load into a game and use the inventory menu to check what you can do with an item.

### Expected behavior

Menus should have text, or have borders.

### Screenshots

![2024-08-23-131134_589x338_scrot](https://github.com/user-attachments/assets/1d90a5dd-1197-4de7-a75e-19da41a7bf3f)

### Versions and configuration

Version: cdda-linux-curses-x64-2024-08-22-2346

**Comment by ZhilkinSerg** [comment] 2024-08-23 12:27
Duplicate of #75362

**Closed by ZhilkinSerg** 2024-08-23 12:27 UTC
Labels: (S1 - Need confirmation)
