### ISSUE TITLE
"too heavy to pick up" and "too big to pick up" messages should never happen, need to become DEBUG messages

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#52769] opened 2021-11-11 21:56 UTC
The [g]et (Pickup) command has been changed to a better GUI, but for low strength characters, it becomes entirely grayed out with "too heavy to pick up" and "too big to pick up" messages, even though I have plenty of space in my large tactical backpack, AND I have hands, so I can wield it even if I don't have room in my pack.  I have so far seen no valid reason why those "too heavy/big to pick up messages should exist in production code.

This is true of all places where those (should-be) placeholder messages exist, such as the new [g]et (Pickup) interface, the [a]pply interface, and the [R]ead interface.

If something will fit in inventory, then put it there.  If it will overburden then provide the usual "you are overburdened" message.  

If something will not fit in inventory, then use the already existing code to handle that.  I used to be able to just pick things up with the [g]et command, and if the thing wouldn't fit in inventory, then I would be asked where I wanted to put it, and if I said wield it, I would be asked where I wanted to put the previously wielded item.  This code should be used whenever a person tries to pick up something that won't fit into any inventory containers.

If you have a way to wield an item, then the [g]et (Pickup) command, the [a]pply command, and the [R]ead command should only ever show a "too heavy to pick up" or "too big to pick up" message in a DEBUG alert.

It's gotten to the point where the only way for me to interact with my inventory is through the advanced inventory interface or the [w]ield command.  I have to specifically [w]ield a book to read it.  I have to specifically [w]ield an item to apply it.  Now I have to specifically [w]ield an item to just pick it up (advanced inventory still works, mostly).  A lot of work is being done on inventory management right now, and eventually someone will look into the problem of the [/]advanced inventory and [i]nventory interfaces not showing the same items, and I'm concerned that, if we don't get rid of these spurious messages now, we may end up with a situation where advanced inventory will fill with them as well, and a low strength character will have to find a torturous workaround just to pick something up.  (e.g. [d]rop their backpack, [w]ield the item, [i]nsert it into the backpack, and then [W]ear the backpack).

Overburdening is a valid part of the game.  If I'm OK with overburdening myself, temporarily or not, then there is no reason to make it so complicated to do so.  I am playing a strength 5 character, which quickly reduces to 4, 3, or less with pain, etc, so I am almost never NOT overburdened.  

I am using:
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-3790-g38b23292bd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment] 2021-11-12 03:34
Duplicate of #52675.

> Overburdening is a valid part of the game. If I'm OK with overburdening myself, temporarily or not, then there is no reason to make it so complicated to do so.

This is exactly why the option `dangerous pickups` exists. But there are still lots of things to improve.

**Comment by epsimpson** [comment] 2021-11-12 05:22
I had wondered what `dangerous pickups` referred to - I thought maybe auto-pickup with nearby hostiles.

I'm embarrassed about missing the duplicate - and only 5 days old. What's the protocol, should I close this or leave it open?

**Comment by wapcaplet** [comment] 2021-11-12 21:21
It can often be hard to tell whether something is a duplicate, even when you *can* find the related issue, so don't sweat it too much.

The protocol for duplicates is that someone identifies it, and then someone like me tags and closes it, which I shall do now. Thanks anyway for reporting!

**Closed by wapcaplet** 2021-11-12 21:21 UTC
