### ISSUE TITLE
OSX colours appear broken

### ISSUE THREAD

**Issue by str99** [CleverRaven/Cataclysm-DDA#25841] opened 2018-09-26 05:19 UTC
**Describe the bug**  
using brew install "cataclysm --HEAD" i get an error when creating a character, ignoring it sends me back to the menu. settings work and i can create a world. but i cant play.

whatever has changed the colours recently has broken the game for _me_

**To Reproduce**  
use homebrew compile on osx and create a character
**Expected behavior**  
game wont allow character creation

**Screenshots**  

the error represented
<img width="803" alt="screen shot 2018-09-26 at 2 44 57 pm" src="https://user-images.githubusercontent.com/43596108/46116016-4585f280-c23d-11e8-9b33-67b007bbab1d.png">

**Versions and configuration(please complete the following information):**
 - OS: macOS High Sierra 10.13.4
 - Game Version 0.C-32540-gcc9d67185d
 - Graphics version: tiles
 - Mods loaded: NA

**Additional context**  
The game is unplayable on mac right now

EDIT: removed additional issue involving pre-compiled versions not working, as its been resolved in a previous issue.

**Comment by ZhilkinSerg** [comment] 2018-09-28 14:09
Hmm... I cannot reproduce this issue on VM with High Sierra - `brew install cataclysm --HEAD`  gives perfectly working version now.

Application header differs from what is shown on your screenshot though:

![image](https://user-images.githubusercontent.com/16213433/46213333-f628ea80-c340-11e8-855b-be61700bd72f.png)

Can you please try building again with `brew reinstall cataclysm --HEAD` and paste terminal output here?

**Comment by str99** [comment] 2018-09-28 22:28
@ZhilkinSerg 
I reinstalled it, here were the results:
<img width="564" alt="screen shot 2018-09-29 at 8 24 11 am" src="https://user-images.githubusercontent.com/43596108/46236287-6aa36e00-c3c1-11e8-8272-b4692b4679b4.png">
<img width="279" alt="screen shot 2018-09-29 at 8 24 36 am" src="https://user-images.githubusercontent.com/43596108/46236289-7000b880-c3c1-11e8-9c7c-f9f27c578f1f.png">
 aaaannnnnddd
<img width="787" alt="screen shot 2018-09-29 at 8 24 47 am" src="https://user-images.githubusercontent.com/43596108/46236296-7727c680-c3c1-11e8-88d3-6467f3eb01a0.png">

**Comment by ralreegorganon** [comment] 2018-09-29 00:32
Please provide the output of the following:
`brew info --json=v1 --installed | jq "map(select(.keg_only == true and .linked_keg != null) | .name)"`

If you don't have jq installed, you can install it with `brew install jq`.

**Comment by str99** [comment] 2018-09-29 01:49
I installed jq.

did i do something wrong here?
<img width="567" alt="screen shot 2018-09-29 at 11 48 36 am" src="https://user-images.githubusercontent.com/43596108/46239580-a3514080-c3dd-11e8-86c8-310d26f7e19a.png">

**Comment by ralreegorganon** [comment] 2018-09-29 04:14
> did i do something wrong here?
Nope, looks correct. You just don't have any linked keg-only formulae, which is good.

Have you already tried running `brew doctor` and making sure there aren't any other issues?

I build the game from source on macOS both in 10.13 and now 10.14 without issue, so I'm positive that there's a configuration error here, I'm just not sure what exactly it might be.

**Comment by ralreegorganon** [comment] 2018-09-30 21:14
> if theres anywhere that can educate me on the process

The section [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#advanced-info-for-developers) is pretty accurate.

Basically, you need to install the dependencies with something like 
`brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer libvorbis libogg gettext ncurses ccache`
and then you may need to link gettext like
`brew link --force gettext`
and finally you cd into the source directory and build it with something like the following (look at the docs linked above for more details)
`make NATIVE=osx OSX_MIN=10.13 CCACHE=1 CLANG=1 LUA=1 TILES=1 RELEASE=1 USE_HOME_DIR=1 -j4`
and launch the resulting binary with `./cataclysm-tiles`

Additionally, the error you have above about `libmodplug` being built with a different version of the standard library implies that you may want to do a `brew reinstall libmodplug` and possible brew reinstall all of the dependencies for the game (which you can get from my list above) and then try the homebrew version of the game again.

**Comment by kevingranade** [comment] 2019-02-01 19:06
No update after four months, closing.

**Closed by kevingranade** 2019-02-01 19:06 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, OS: macOS
