### ISSUE TITLE
Wasp nest floating mid air

### ISSUE THREAD

**Issue by Vidali225** [CleverRaven/Cataclysm-DDA#62453] opened 2022-11-28 21:31 UTC
### Describe the bug

A wasp nest spawned on z-level 2. Chunks of it is floating mid air, without support. 

I am playing with 3d z levels and noticed that all the zombies were being killed by wasp guards. The guards were one z level above and out of reach. They were protecting the nest that had spawned inside a house also on z level 2. Queen was on z level 3.

### Steps to reproduce

Don't know enough about how the location spawn works. I saw a post from 2021 that discussed the wasps killing from above. That is happening here too but couldn't find anything about the nest. 

### Expected behavior

I don't think the 3d z level setting should mess with enemy moves or map spawns. Being able to look down from a roof top is essential 

### Screenshots

Wasp nest inside building. Parts of it are floating mid air.
![Screenshot (2)](https://user-images.githubusercontent.com/96297342/204381677-dc08ef0d-dddb-4e42-988e-2db18f3cde72.png)
Below the nest. Shadow is cast on ground level.
![Screenshot (3)](https://user-images.githubusercontent.com/96297342/204381667-92e4fd19-06d0-41bd-a28d-3c198308ee64.png)
Location on world map.
![Screenshot (4)](https://user-images.githubusercontent.com/96297342/204385085-c5da0a28-26e0-4ca3-a18e-100ae0f56d2c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1219 (21H2)
- Game Version: 82ee3c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[MAP-SAVE.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10107683/MAP-SAVE.zip)

**Comment by Night-Pryanik** [comment] 2022-11-29 02:51
Duplicate of #58219.

**Closed by Night-Pryanik** 2022-11-29 02:51 UTC
Labels: (S1 - Need confirmation)
