### ISSUE TITLE
Homemade corndog crashes the game (Segmentation fault) when inspected

### ISSUE THREAD

**Issue by Tammatoes** [CleverRaven/Cataclysm-DDA#77858] opened 2024-11-14 22:34 UTC
### Describe the bug

The game is fine until I decided to make a homemade corndog. If I make it and then look at it through the menus (pickup menu, eat menu, advanced inventory manager etc) the game crashes 100% of the time

### Attach save file

[Chaparral-trimmed.tar.gz](https://github.com/user-attachments/files/17758632/Chaparral-trimmed.tar.gz)

### Steps to reproduce

1. Make a [homemade corndog](https://cdda-guide.nornagon.net/item/corndogs_homemade)
2. Look a it through any menu, like the pickup menu.

### Expected behavior

I am able to see the items without issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: cdda-experimental-2024-11-03-2221 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment] 2024-11-14 22:40
Update your experimental. This is a duplicate of #77500.

**Closed by NetSysFire** 2024-11-14 22:40 UTC
Labels: (S1 - Need confirmation)
