### ISSUE TITLE
Boiling water in a pot containing it

### ISSUE THREAD

**Issue by Profitablius** [CleverRaven/Cataclysm-DDA#27326] opened 2018-12-26 18:30 UTC
Take a pot, wield it, fill it with water, stand next to your fire without another container/pot nearby, and try crafting clean water. Doesn't work.

A minor problem with an easy and obvious workaround, but it'd convenient and immersive if it worked.

**Comment by kevingranade** [comment] 2018-12-27 01:37
Duplicate of #171

**Closed by kevingranade** 2018-12-27 01:37 UTC
Labels: <Suggestion / Discussion>, Items / Item Actions / Item Qualities
