### ISSUE TITLE
Game restart errors

### ISSUE THREAD

**Issue by gr0mazeka** [CleverRaven/Cataclysm-DDA#55762] opened 2022-03-01 04:08 UTC
### Describe the bug

 DEBUG    : default (butchery_requirements) has two definitions from the same source (dda)!

 FUNCTION : static void mod_tracker::check_duplicate_entries(const T&, const T&) [with T = butchery_requirements; std::enable_if_t<mod_tracker::has_src_member<T>::value>* <anonymous> = 0]
 FILE     : src/mod_tracker.h
 LINE     : 75
 VERSION  : bedfc51

and others.....

### Steps to reproduce

Create the world=>create a character=>play. Save and exit the menu. Play again. A lot of mistakes.

### Expected behavior

launching the game without errors

### Versions and configuration

Windows 8, 10
latest game version

**Comment by LeahLuong** [comment] 2022-03-01 04:11
Looks like a dupe of #55725 which is likely a dupe of #55606.

**Comment by gr0mazeka** [comment] 2022-03-01 04:24
This looks like bug #55725

**Comment by LeahLuong** [comment] 2022-03-01 04:37
Yeah, I just said that. Please refrain from posting dupe issues. You can do this by doing basic searches of this repo before posting your issue.

**Closed** 2022-03-01 04:58 UTC
