### ISSUE TITLE
Construction will stop at 0% and says "that doesn't look edible"

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#40708] opened 2020-05-19 19:08 UTC
# Describe the bug

When trying to cut long grass (for example with machete) it will start it and stop at 0%. You can't advance it, because it says "that doesn't look edible".

# Steps To Reproduce

1. Constructmenu -> Cut grass

# Expected behavior

Let me cut the grass

# Screenshots

![grafik](https://user-images.githubusercontent.com/33199510/82367825-b7174380-9a14-11ea-8f2b-c1e444d04b51.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2278-gf8f9f52 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Fewer Farms [Fewer_Farms]
]

# Additional context
Save attached
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4652617/save.zip)

**Comment by Lamandus** [comment] 2020-05-20 08:20
Update: it is affecting all kinds of constructions. 10680 was still alright.
Maybe caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/40660 ?

**Comment by Resok** [comment] 2020-05-29 22:07
I'm also hitting this when trying to craft food with mutant meat.

**Comment by hexagonrecursion** [comment] 2020-06-23 15:22
Possibly duplicate of #41192

**Comment by Lamandus** [comment] 2020-06-23 15:32
> 
> 
> Possibly duplicate of #41192

wouldn't it be the other way around? Mine is over one month old. The other 14 days.

**Comment by anothersimulacrum** [comment] 2020-06-23 16:46
Fixed in #41316

**Closed by anothersimulacrum** 2020-06-23 16:46 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Info / User Interface
