### ISSUE TITLE
opening reload menu and then closing it wastes moves

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#27895] opened 2019-01-26 11:00 UTC
**Describe the bug**  
using reload verb without reloading a gun takes moves

**To Reproduce**  
1. get a gun and different ammo/mags
2. press reload and close the menu
3. notice that you wasted 164 moves for that

**Expected behavior**  
no moves were withdrawn

**Comment by Night-Pryanik** [comment] 2019-01-26 12:31
Duplicate of #23516.

**Closed by Night-Pryanik** 2019-01-26 12:31 UTC
