### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by bullkang** [CleverRaven/Cataclysm-DDA#78294] opened 2024-12-02 07:23 UTC
### Describe the bug

Unexpected game crash. I was simply driving near fungaloids, arrived at a mansion and ...
game crashed.

### Attach save file

[Larchwood-trimmed.tar.gz](https://github.com/user-attachments/files/17974067/Larchwood-trimmed.tar.gz)

### Steps to reproduce

Continue driving closer towards the mansion.

### Expected behavior

Game not crashing.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 78fd6e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17974133/crash.log)
[debug.log](https://github.com/user-attachments/files/17974134/debug.log)

**Comment by RenechCDDA** [comment] 2024-12-02 14:05
Duplicate of #76742

**Closed by RenechCDDA** 2024-12-02 14:05 UTC
Labels: (S1 - Need confirmation)
