### ISSUE TITLE
UI awkwardness during hallucinations when passing the time using '|'

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12121] opened 2015-04-22 15:48 UTC
I like hallucination as a game mechanic, although its effects are in my opinion much too severe in ASCII mode, and are nearly negligible in the tiles mode, which I've already mentioned.  However, there is another purely UI problem with hallucination: it's very input-intensive to pass time when hallucinating.  I don't think it needs to be that way.

As I've said before, it's fine for the game to _penalize the player in terms of stats_, but it's not fine to penalize by requiring unnecessarily tortured keyboard input.  So let's say if I am hallucinating, I see animals and monsters and this confuses and tortures my character.  But why ask the player if I want to attack these hallucinations?  As a player I know they're hallucinations and I will probably answer 'n'o every time.  And why should I hit 'n' or 'enter' about 100 times just to pass a few hours during hallucinations?

Instead, why not punish the player's character instead of punishing the player.  So if I hit '|' to spend 5 hours, just let me spend that time without any further keyboard input, but **summarize** the nastiness that happened to the character when all is done, such as, for example: "During waiting, you've fought imaginary monsters, and therefore had hit the ground and the walls around you, hurting yourself."  Or, "During your hallucination episode, while passing time, you were so absorbed fighting imaginary monsters, that you've destroyed some items in your inventory due to negligence and recklessness of your attacks."  That's just one possibility.  I'm not saying it has to be like that.  But whatever the penalty is, please let it not be having to hit 'enter' 100 times to pass time.  Just take it from the player character's stats and let the game flow smoothly for the player.

Hallucination right now is so disruptive to the gameplay in terms of UI, that even though its in-game effects are something I can completely manage and cope with, it's the UI input, having to hit 'enter' 100's of times, that's what's annoying about it, and prevents me from selecting anything with hallucination background these days.

To make hallucinations more fun for the player, please punish the character and not the human in the chair playing that character.  So apply HP damage to limbs, destroy items, do whatever you think is logical.  But please don't make people hit 'enter' 100 times.

This situation would be different if as a player I didn't know I was hallucinating.  But I do, because it's mentioned under the '@' screen's list of status effects.  And I know because hallucinations create very distinctive and recognizable visual artifacts.  So I know it's fake, and I will hit 'enter' to ignore it, therefore requiring me to hit 'enter' many times for 'y/n' prompts only adds tedium and doesn't constitute an interesting choice for me.

Also 'tweaker' background only granting 2 points is way too low for what you have to put up with at least in ASCII mode.  I think 'tweaker' should be 4 or 5 points in ASCII mode to make it worth the insane suffering for the player.  However, should hallucinations be fixed to be UI-light as I suggest and only penalize the character and not the person in the chair, 2 points would be plenty then.
##

**Comment by Coolthulhu** [comment] 2015-04-22 16:00
I totally agree about the hallucination part, though it is actually just an extension of the bigger problem: lack of "Ignore all further alerts of this kind" option.
Hallucinations are a bit of a half-implemented relic, which is why they are badly designed, grant you clairvoyance, don't work on tiles etc.

I disagree about the tweaker. The problem is UI related and should not be balanced by rewarding patience (mashing enter, "tanking" visual clutter). 2 points are for the hard start - occasional huge speed/stat debuffs, and not for annoyance.

**Comment by BevapDin** [comment] 2015-04-22 16:00
> As a player I know they're hallucinations

Do you? Maybe currently and with dynamic spawn off, but technically you don't. Maybe some extreme and *usually* rare monster are most likely hallucinations, but they don't have to be.

What if you start hallucinating during a battle, already surrounded by *real* monsters?

> So apply HP damage to limbs, destroy items, do whatever you think is logical. But please don't make people hit 'enter' 100 times.

Yeah, I'm sure people will love it when "creatures that are though to be hallucinations" destroy their stuff. I'll probably be like "Hihi, that fungal zombie kicks my booze stack, hihi, the imaginary glass shattering sounds nearly realistic ... actually, it sounds very realists. WAIT A MINUTE!" Some reaction for damaging the character.

**Comment by Coolthulhu** [comment] 2015-04-22 16:04
> Some reaction for damaging the character.

Damaging the character sounds good to me here. The character thinks everything is a hallucination and so stands still. Or automatically swings at all hallucinations in melee range and lands an actual hit.

Some automatic way of waiting out the hallucinations should be available.

**Comment by BevapDin** [comment] 2015-04-22 16:05
Another example: if my character is currently surrounded by goodies (on the floor), I definitely want to be warned when a spitter zombie approaches, because I'm going to lead it away and/or use a dedicated ranged attack to fight it. I definitely don't want to take the risk that it is real (maybe from a horde) and spits acid on my stuff.

**Comment by graysage1** [comment] 2015-04-22 16:43
@BevapDin 

>Maybe currently and with dynamic spawn off, but technically you don't. Maybe some extreme and usually rare monster are most likely hallucinations, but they don't have to be.

This is incorrect.  You should try hallucinations in ASCII mode.  Its effect is not just to draw non-existent monsters.  It also has a very unique animation it plays in the shadows, the unseen parts of the game map.  It's highly distinct and there is no way you'll ever misconstrue it as a player.

Also, like I said before, it tells you straight up in the character info screen '@' that you're hallucinating.  There is no possibility of a mistake.  It also I believe tells you you're starting to hallucinating in the message 'L'og as well.  In other words, there is zero percent chance to not be confused about it.

>Yeah, I'm sure people will love it when "creatures that are though to be hallucinations" destroy their stuff. I'll probably be like "Hihi, that fungal zombie kicks my booze stack, hihi, the imaginary glass shattering sounds nearly realistic ... actually, it sounds very realists. WAIT A MINUTE!" Same reaction for damaging the character.

It's as though you didn't bother understanding what I meant.  The illusory monsters don't destroy anything.  You "potentially" act self-destructively when you respond to hallucinations.  I'm not even saying that needs to be the price to pay.  My only point is, whatever price you think is reasonable, it shouldn't be tedious keyboard input.  Make the game stats reflect the price, but allow the gameplay experience itself to be smooth for the player.

CDDA should offer a cerebral challenge of making the right decisions.  It's a turn-based game.  There is no hurry.  There is no need for twitch response.  So the game doesn't test you as a person, it tests your analytical ability.  It should stay that way.  When you begin sending me hundreds of spurious 'y/n' prompts what you're testing is my patience and not my analytical ability.  And this is just sad.

Not all challenges are fun.  Challenging me to see if I can hit 'enter' key 100 times is not an interesting challenge for me as a player.

**Comment by BevapDin** [comment] 2015-04-22 17:00
Yes, you known when your character hallucinates, but you don't known which monsters are really and which aren't. That's the whole point. See the shocker over there approach? Do you get your gun read or do you await it's paralyzing attack? When I'm hallucinating, every monster I see is real until *proven* otherwise. And with many monster it's vital that I have the first attack, to stun them and to prevent their attack (e.g. prevent that hulk from smashing me).

----

> My only point is, whatever price you think is reasonable

Reasonable is careful behavior on the side of the player. If they choose to carefully inspect/attack every monster to check whether it's real or not, they should be rewarded for that.

How about this: you can deactivate the safemode while you hallucinate, therefor avoid most of the queries.

**Comment by Coolthulhu** [comment] 2015-04-22 17:04
> How about this: you can deactivate the safemode while you hallucinate, therefor avoid most of the queries.

Doesn't stop the ones during crafting/reading/etc.
When in a fully cleared area, there is no way to just ignore the obviously fake hallucinations other than mashing enter.

**Comment by graysage1** [comment] 2015-04-22 17:09
>Yes, you known when your character hallucinates, but you don't known which monsters are really and which aren't.

You can make a very reasonable guess in most cases, I think.

I think the main end result of hallucinations is that they keep you up and don't allow you to fall asleep.  Confusing a hallucinated monster with the real one hasn't been a major problem in my games, but I play static spawn without hordes enabled.

So maybe: if the player plays static spawn without hordes, let us skip the tedious rigmarole.  And if the hordes are enabled and/or the dynamic spawn is enabled, then fine, maybe you have a legitimate reason to test the player, but even then, maybe change this to say 3 tests for every 8 hour period to make it manageable.

In other words, I suggest, if you really want to keep the player guessing what's real and what's not, make for few but very consequential challenges.  So maybe do it just 2 times in an 8 hour window, but maybe it really matters a lot what you decide.  My point is, can we keep the legitimate analytical challenge but discard as much tedium as possible?

So to my mind, in static mode without roving hordes, the y/n prompt is completely spurious and is useless.  All it does is create irritation.  I don't even care if there is a real monster in there.  I just want to see how it all ends.  If there is a real monster in there, let it attack.  I don't care.  I just want to get to the end of a time period no matter what it takes.  If it spews acid and burns items, fine, good, let it do that.  I should have a choice to ignore everything, because I made an analytical decision that my chances are very good, and then take that chance.

So I still think there are lots of possible changes that can improve the game experience while still keeping hallucination something that creates interesting consequences for the player.  I just don't think tedium is an interesting consequence.

**Comment by graysage1** [comment] 2015-04-22 17:24
@BevapDin 

I think you'd have a better point if:

1. The player actually never knew from meta-information (like the '@' screen or the message log or special animations) whether they were in a hallucination episode or not.  This means you now don't inform the player at all, period.  Ever.  Once you have a bionic that hallucinates or you start with the schizo trait, that's all you know.  From then on no special animations or messages from the game should be telling you what's up.

2. Hallucinated monsters were rare and about as common as any other monster.  So for example, let's say you have roving hordes enabled, and lets say this results in a random spawn about once every 3 in-game hours (I haven't tried this game mode, so can't speak from experience).  So then hallucinations should closely mirror this pattern and spawn a fake about once every 3 in-game hours, thus giving you a 50/50 chance.  When you have a 50/50 chance, it really matters a lot what you decide.  If you think there is a 95% chance it's a hallucination and only 5% chance it's real, it's not worth your time to try to respond to every encounter.  It's tedious.  And it's boring.  It's boring because you know most of the time it will be a fake.  But if it's 50/50, holy cow, I am on the edge of my seat, because things can be nothing or very bad, 50/50.


3. Hallucinated monsters tended to "blend in" meaning, if this area has lots of 'z'ombie children, you have a high percent chance to hallucinate children.  If you're in a lab, then maybe you have a high percent chance to hallucinate scientists.  In other words, hallucinations are deliberately hard to distinguish from what would happen without them.

Incidentally, if you follow this logic, you'll need to remove the funny hallucination animation that plays in the ASCII mode, and you won't have to implement it in tiles, thus making it way easier to bring ASCII and tiles much closer together.  This can kill two birds with one stone: better, more meaningful hallucination choices, and better ASCII - tiles parity.  Good all around.

**Comment by graysage1** [comment] 2015-04-22 17:33
I also think it's possible to challenge the player by interspersing fake monsters together with the real ones, so that it's not a choice of either/or, but it's always **both** when a group appears.  Think of it as "hallucinatory adds" if you like.  So when there is a real monster spawned, hallucination trait creates from 0 to 3 adds, for example.  That way hallucinations create difficulty because you may waste ammo shooting someone 3 tiles to the left of you when someone 3 tiles to the right present much more danger and is now gaining rapidly on you while you're busy being distracted by a fake.

But this kind of challenge wouldn't throw up more y/n prompts than ordinary spawn code itself would.  It would be nothing special.

So then my question is, can people easily pass time with static spawns + hordes?  If yes, the same should be true for hallucinating characters.

Being interrupted every other rest or every other night is much better than being interrupted with fake notifications many many times *every* time you rest.  So I say 'yes' to the challenge, but keep it relevant and meaningful and don't spam. :)

**Comment by i2amroy** [comment] 2015-04-23 07:31
So let me sum up what seems to be the actual solutions to the essays here:
1) Make hallucinating less obvious/more real.
2) Add an "ignore all further interruptions" button to more stuff.
That's basically what I'm getting out of this.

**Comment by graysage1** [comment] 2015-04-23 13:34
@i2amroy 

Yea, I think that's a fair summary.

>1) Make hallucinating less obvious/more real.

The whole point behind 1 is that incidentally such hallucinations will be less keystroke-demanding to handle.  I believe the challenge should be analytical.  It should make me think "What to do?  What to do?"  The challenge should be where I think the solution is blatantly obvious, I just need to keep jamming enter for about 1 minutes in real time.  So the game is testing to see if I don't mind holding down a single key for a minute?  That's not a fun challenge.

So making things more real, if it doesn't fix the non-analytical y/n confirmation dialog spam, is not the point at all.

**Comment by graysage1** [comment] 2015-04-23 13:47
Also, I think it may be fine to give an ever-so-slight hint to the player like this "You feel funny."  I'd print this into the message log once every 8-24 hours, randomly, so long as the player has a "hallucinating" property.  So in-game time intervals for the "You feel funny" message can be something like 8hrs, 12hrs, 20hrs, 15hrs, 21hrs, 9hrs, etc.  So it would vary randomly but it would be a rare message.

Then when you take antipsychotic meds, it would say "You feel less funny now."  Or, "You feel funny, but in a different way now."  Take your pick.   Then once the meds wear off, don't tell the player, because there should be no obvious boundary.  The meds wear off gradually.  But once they wear off, the randomized rare hints can resume.  This would make hallucination similar to other diseased conditions in the game which don't inform you about themselves.  Like for example "Your veins are itching."  This doesn't tell you what it is.  So hallucinations can be similar to that as far as meta-info goes. However, when you remove a faulty bionic that causes hallucinations, I think the game should be honest and tell the player only something like "Your vision feels better now."  That's because the meds only suppress the condition to some extent.  They don't eliminate it.  Whereas removing a faulty hallucination-inducing bionic is an indefinite cure, as it were.

**Comment by Zireael07** [comment] 2015-04-23 14:48
'You feel funny' while hallucinating is a good idea

**Comment by graysage1** [comment] 2015-04-23 15:38
Also, since halluciations are meant to be very challenging, it may be a good idea to start all hallucinating backgrounds with a limited supply of anti-psychotic meds.  Even just 1 pill would make a difference in some game starts.

I don't know if antipsychotics can suppress faulty bionics or not.  Maybe if one starts with a bad bionic, nothing can be done to help.  But if antipsychotics suppress hallucinations induced by bad bionics, maybe those backgrounds should also start with 1 or a few pills.

It all depends on whether or not they were diagnosed pre-apocalypse.  Asthmatics start with an inhaler.  Near and far sighted people start with the glasses.  Albinos start with umbrellas.  It's a common theme.

The two glaring backgrounds that deviate from this are hallucinatory ones, and tweakers who don't start with a shot of speed/meth or whatever it is they need to take.

Maybe there should be something like "undiagnosed schizo" who doesn't start with any meds.  But I can already see the pitchforks in the distance because I just suggested adding a new background, lol.  I love different backgrounds, sorry.

**Comment by Leland** [comment] 2017-05-25 20:30
This hasn't seen a discussion in over 2 years – closing. If anyone wants this kept open for purposes of furthered discussion or development, ping me here to reopen or feel free to make a new issue so that it's visible at the front of the queue.

**Closed by Leland** 2017-05-25 20:30 UTC
Labels: Enhancement, Information / Interface, Suggestion (Discuss)
