### ISSUE TITLE
problem with wind mill

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68595] opened 2023-10-10 19:38 UTC
### Describe the bug

If you put a product like wheat (buckwheat or rice) in a windmill, after processing you will get flour with zero nutritional value

![flour](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/3dd8e46c-438a-4bb0-bf3f-824a44c2f179)

all the following products made from this flour are calculated based on the fact that the nutritional value of the flour is zero

![product](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/7758a62c-d59f-43a4-8338-7d41217ca42f)

### Attach save file

None

### Steps to reproduce

1. take the wheat and put into wind mill
3. start grinding
4. wait end
5. get result

### Expected behavior

calorie content is more than zero

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: ab63507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by watcherPlayer** [comment] 2023-10-10 20:13
**note**

wheat was collected from the field by the planted map generation, dried and threshed
![wharf](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/058af74b-54e7-4732-b9bc-121771b0d3fc)

buckwheat and wild rice were collected by quests from the plant extraction camp

**Comment by RenechCDDA** [comment] 2023-10-11 05:17
The problem is basically that comestibles used to have charges and now they don't.

https://github.com/CleverRaven/Cataclysm-DDA/blob/274d806173256850af22503b22ceda7125ab9963/src/iexamine.cpp#L5761
(That used to work, but now doesn't because item::count() always returns 1 for non-charge items)

Here's s a commit which resolves it for initial processing: https://github.com/CleverRaven/Cataclysm-DDA/commit/5f69e173fbf6791e74082eb61c2bae43e9ee5c18

But any `conversion_ratio` that isn't 1.0 isn't working, that needs to be resolved in iexamine::mill_finalize

**Closed** 2023-10-16 02:15 UTC
Labels: (S2 - Confirmed), Items: Food / Vitamins, [C++], Fields / Furniture / Terrain / Traps
