### ISSUE TITLE
Error when saving game and exiting to main menu with Magiclysm installed.

### ISSUE THREAD

**Issue by Vulp0d** [CleverRaven/Cataclysm-DDA#69180] opened 2023-11-08 10:47 UTC
### Describe the bug

Exiting to main menu while having Magiclysm installed causes an error to appear.

### Attach save file

N/A

### Steps to reproduce

1. Create a new world with Magiclysm installed.
2. Load a new character into this world.
3. Save and exit to main menu.
4. The error appears.

### Expected behavior

No error on exiting the save.

### Screenshots

N/A

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.2; Release: 21.2; Codename: victoria; 
- Game Version: 17c23c2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13295583/debug.log)
[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13295592/Test.zip)

My game does not create crash.log, even when prompted from debug menu. Seems to be a linux bug from quick search, which can be a separate issue by itself. I hope debug.log provides enough information, along with the provided save.

**Comment by ZhilkinSerg** [comment] 2023-11-08 18:11
Duplicate of #68205

**Closed by ZhilkinSerg** 2023-11-08 18:11 UTC
Labels: (S1 - Need confirmation)
