### ISSUE TITLE
Template doesn't store a pool type

### ISSUE THREAD

**Issue by Maykeye** [CleverRaven/Cataclysm-DDA#21726] opened 2017-08-27 04:29 UTC
### Expected Behavior
If I save a template with single pool for points, I expect I can load it and immediately tweak a few settings in the character using the same pool type I created it with originally.

### Actual behavior
If I load a template, game resets pool type to Multiple pools, so I can't start the game with the changes unless I change pool type.

### Steps to reproduce the behavior

1) Create a template: Single Pool,  scenario Evacuee, profession: black belt(spending all points), reduce strength to 7, spend the point you got strength on archery skill.

2) save template, quit game, reload game, select new game->preset character, choose created template. 

3) Remove a point from archery, add 1 to strength. At this point the says `Points left: -1+0+1=0` and the game will not start with "Too many trait points allocated, change some traits or lower some stats and try again." message because pool type is no longer "single pool", it's switched to "multiple pools"

**Comment by Leland** [comment] 2017-08-27 18:01
Possible dupe of #15748

**Comment by BrokenAdmin** [comment] 2017-08-28 21:16
@Leland "Pools" I don't think it's a dupe

**Comment by angoddu** [comment] 2017-08-31 08:24
I can confirm this. I use multi pool and when I load a preset all the values are 0+0+0 so when I change my stats I get that exact error

**Comment by BrokenAdmin** [comment] 2017-08-31 11:32
It's not made for unfinished character creation. A preset character is supposed to be FINISHED

**Comment by Clyybber** [comment] 2017-08-31 20:10
@BrokenAdmin I dont think a preset character has to be finished. Changing aspects of a preset afterwards should be possible, and this bug hinders that slightly.

**Comment by Broken-Admin** [comment] 2017-09-04 06:44
Well, I mean, this should be closed because it's not a bug, it's a feature.

**Closed** 2018-09-19 09:44 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface
