### ISSUE TITLE
Edibles exceed their container's limit

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#30129] opened 2019-04-30 20:28 UTC
**Describe the bug**  
One has some chance to find edibles generated as random loot at various places. I found some with number of portions exceeding maximum limit implied by their packaging.

**Expected behavior**  
Number of portions/units of anything never exceeds maximum container capacity.

**Screenshots**  
![toastem](https://user-images.githubusercontent.com/38487938/56990952-c66fe880-6b96-11e9-803b-2d638261e4da.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2460-gc0cef43 (experimental build 8868)
 - Graphics version: Tiles
 - Mods loaded:   "dda",  "ew_pack",  "boats",  "blazemod",  "Tanks",  "No_Fungi", "no_flaming_weapons",  "StatsThroughSkills"

**Comment by KorGgenT** [comment] 2019-04-30 22:29
this is a duplicate of #27863

**Closed by KorGgenT** 2019-04-30 22:29 UTC
