### ISSUE TITLE
Food perish times are weirdly inaccurate

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#32520] opened 2019-07-20 21:15 UTC
# Describe the bug

In one way or another food perish times are weirdly inaccurate.  Playing a new game with an initial start day of 91 for a summer start had me finding fresh unspoiled milk on Day 12.  Many other food items were also unspoiled.  The bread I found in the first day or two that should last a a week was still fresh with a week of time left.

I first noticed this bug after the 1 second change.  Although due to time being dialled back (I reset it back to what it was with debug mode) I initially thought it was simply my save.  Having started a new game recently I found the issue is still occurring.

Edit: Day 65 and a research facility has fresh unspoiled meat in a 21C room.

![Fresh Meat](https://user-images.githubusercontent.com/44048645/61836986-1de7d100-aec6-11e9-8e1d-87bcb1e317a7.jpg)

# Steps To Reproduce

1. Move the initial day to 91 for a summer start for best results.
2. Spawn in or find some fresh perishable food.
3. Play the game or advance time.

# Expected behavior

I would expect the food to perish within the time specified on the food if its in a normal warm environment.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-5723-g6790e59 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex]
]

# Additional context

I posted about the issue on reddit to see if anyone else had noticed the issue.  You can [read the thread here.](https://www.reddit.com/r/cataclysmdda/comments/cf53z5/has_anyone_noticed_food_perish_times_acting_weird/) Several people mentioned noticing some sort of oddity with food perish times.

**Comment by kevingranade** [comment] 2019-08-13 22:18
This has likely been adressed by #32603 or the follow up #32948

**Comment by Leland** [comment] 2019-08-19 21:17
Duplicate of #33338

**Closed by Leland** 2019-08-19 21:17 UTC
Labels: (S1 - Need confirmation), Food / Vitamins, Temperature, Time / Turns / Duration / Date
