### ISSUE TITLE
8105c2c [64-bit] Segmentation crash, terrain errors.

### ISSUE THREAD

**Issue by PerfectDeath4** [CleverRaven/Cataclysm-DDA#59631] opened 2022-07-26 08:18 UTC
### Describe the bug

Game crashes while doing stuff.  Does not seem to matter if its vehicle driving or just standing around.
Invalid terrain and furniture debug errors are often followed by segmentation crash.
The errors and crash don't always happen right away, but after a bit of time passes.
Generating new character will result in many terrain errors followed by an eventual segmentation crash.
EDIT:
For new worlds, I don't receive the many debug errors for terrain, just the segmentation crash.

### Steps to reproduce

1. Make a character
2. pass through multiple debug errors for terrain
3. play for a bit
4. crash

### Expected behavior

No terrain errors and crashes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 8105c2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Logs for my current character
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9187707/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9187719/debug.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9187829/debug.log)

below is are log for the new character
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9187936/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9187940/debug.log)

**Comment by Zireael07** [comment] 2022-07-26 09:04
related/dupe of #59629?

**Comment by PerfectDeath4** [comment] 2022-07-26 09:36
> 

I was able to get the seg crash from just walking around/passing time as well as using / inventory management and weilding items.  Not exactly sure what's triggering it.

**Comment by irwiss** [comment] 2022-09-02 22:07
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/59648

**Closed** 2022-09-02 22:20 UTC
Labels: (S1 - Need confirmation)
