### ISSUE TITLE
Error when trying to acces cargo space.

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#40804] opened 2020-05-24 16:58 UTC
# Describe the bug

When I try to get things from one of the cargo spaces in my van, the game crashes

# Steps To Reproduce

1. Get in the van (sorry, I had to)
2. press g and point to the upper left cargo space
3. watch the game crash

# Expected behavior

I expected to be able to grab my items.

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" 

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.E-2411-g7fcce2ctiles[Tiles or Terminal]
 - Ingame language: english
 - Mods loaded: dda, alt map key, sees player icon retrodays, stats through skills, speedydex, no fungal monsters

 # Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4673997/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4673998/crash.log)
[savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4673999/savegame.zip)

**Comment by olanti-p** [comment] 2020-05-24 22:15
Judging by 
```
  #8
    (dbghelp: @0x87ed65[cataclysm-tiles.exe+0x47ed65]), 
    (libbacktrace: ZNK4item8gun_infoEPKS_RSt6vectorI8iteminfoSaIS3_EEPK14iteminfo_queryib+0x235@0x87ed65),
    (libbacktrace: 0x87ed65    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x88f968[cataclysm-tiles.exe+0x48f968]), 
    (libbacktrace: ZNK4item4infoB5cxx11ERSt6vectorI8iteminfoSaIS1_EEPK14iteminfo_queryi+0x278@0x88f968),
    (libbacktrace: 0x88f968    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x88fcfa[cataclysm-tiles.exe+0x48fcfa]), 
    (libbacktrace: ZNK4item4infoB5cxx11EbRSt6vectorI8iteminfoSaIS1_EE+0x2a@0x88fcfa),
    (libbacktrace: 0x88fcfa    [unknown src]:0    [unknown func]),
```
may be a duplicate of #40779 and should be fixed in the next build

**Comment by RafeHaab** [comment] 2020-05-24 23:06
It makes sense, that space is where I was hoarding the tools and the guns.

**Closed** 2020-05-26 16:57 UTC
