### ISSUE TITLE
Migration issues in 6bccfc7

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#50847] opened 2021-08-17 10:04 UTC
### Describe the bug

1. NATO assault rifles were incorrectly migrated after updating from 3 week old experimental version. 
There has been an error during savegame load, after load all NATO assault rifle guns were named 'IF YOU SEE THIS IT IS A BUG'.
2. Invalid trait id 'PARKOUR' - was it removed?

### Steps To Reproduce

Update the game with save where NATO Assault guns are present, start the save.

### Expected behavior

Proper migration of inventory.

### Screenshots

Error during migration of savegame:
![изображение](https://user-images.githubusercontent.com/25095102/129706294-cc60d7b5-c3f1-4958-8177-011c29b55a25.png)

### Versions and configuration

- OS: Win10
- Game Version: 6bccfc7
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Magiclysm

**Comment by Pseudogeist** [comment] 2021-08-17 10:11
Duplicate of #50656. Parkour is not selectable as a trait, it's gained via hobby.

**Comment by hexagonrecursion** [comment] 2022-01-17 06:03
@wapcaplet Why did you remove Duplicate and add Need confirmation? I can confirm this is still happening see https://github.com/CleverRaven/Cataclysm-DDA/issues/50656#issuecomment-1014167833

**Comment by wapcaplet** [comment] 2022-01-17 14:29
I got confused by the issue description. I agree, this issue (except the Parkour part) looks like a duplicate of #50656

**Closed** 2022-01-17 14:29 UTC
Labels: (S3 - Duplicate), (S2 - Confirmed), Mutations / Traits / Professions/ Hobbies, Mechanics: Effects / Skills / Stats, Mechanics: Character / Player
