### ISSUE TITLE
Game Crashes when hostile NPC comes in contact with PC or party NPC.

### ISSUE THREAD

**Issue by LyuKalev** [CleverRaven/Cataclysm-DDA#34474] opened 2019-10-05 09:05 UTC
Game Crashes when hostile NPC comes in contact with PC or party NPC.

1. Approach hostile NPC.
2. Let it reach you.

Save file:
https://drive.google.com/file/d/1eXzmLsbUJllUhkUwg936oiytHO-yO31E/view?usp=sharing

Versions and configuration:

Build 9715
Version 0.D-8206-gedf3542

Modlist:

[
  "dda",
  "crt_expansion",
  "craftgp",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "hydroponics",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "Battery_Overhaul_Legacy_Mode",
  "cbm_slots",
  "more_classes_scenarios",
  "no_npc_food",
  "manualbionicinstall",
  "sleepdeprivation",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"
]

**Comment by ZhilkinSerg** [comment] 2019-10-05 12:35
Duplicate of #34427

**Closed by ZhilkinSerg** 2019-10-05 12:35 UTC
