### ISSUE TITLE
Plastic canteen holding my two-way radio?

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#40174] opened 2020-05-05 03:54 UTC
# Describe the bug

Plastic canteen holding my two-way radio?

# Steps To Reproduce

1. Pickup and wear a plastic canteen (or any similar item that can fit a similarly implausible item within it).
2. Pickup a two-way radio

# Expected behavior

Two-way radio should not be able to fit inside a plastic canteen.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81033603-0d975600-8e49-11ea-9ee4-f5d2b8d6f462.png)

![image](https://user-images.githubusercontent.com/5217673/81034241-56e8a500-8e4b-11ea-9c66-bfea392fc80d.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1758-g7161a41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation]
]

**Comment by RoyBerube** [comment] 2020-05-05 04:51
There are two issues here: the first is that it is not possible yet to prioritize where picked up loot is placed, and the other is about items and containers not yet having dimensional restrictions other than total volume.

The first problem should be somewhat easy to implement.

The second with the dimension requirements would be a lot more work as every item and container in the game would need the dimension data added. Not to mention the code. I've seen some discussion about this but would be a big undertaking to do properly.

**Comment by Resok** [comment] 2020-05-05 17:25
In theory it looks like this should fix this -

https://github.com/CleverRaven/Cataclysm-DDA/pull/40186

**Comment by KorGgenT** [comment] 2020-05-05 18:00
possibly, but it could be a different pr that fixes this. there are 2 separate features i'm adding to pockets: max length, and max size.

**Comment by KorGgenT** [comment] 2020-05-05 23:11
duplicate of #40130

**Closed** 2020-05-05 23:11 UTC
Labels: (S3 - Duplicate), <Enhancement / Feature>, Items: Containers
