### ISSUE TITLE
Lab finale can spawn in unreachable position

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#3437] opened 2013-10-04 00:42 UTC
![screen shot 2013-10-03 at 8 37 05 pm](https://f.cloud.github.com/assets/4412171/1266597/4082df50-2c8d-11e3-801d-3959139597ee.png)

The only two rooms on this level were the finale room, which has no stairs, and a room with the only pair of stairs on the level. The lab finale spawned on a diagonal to the other room, rendering it unreachable except by jacqueshammer. I took the picture with the clairvoyance cube to better display the issue.

**Comment by qbradq** [comment] 2015-05-19 20:03
Please close as duplicate of #9726 which has more complete information (but less pretty pictures).

**Closed** 2015-05-19 23:36 UTC
Labels: Bug
