### ISSUE TITLE
Recon Mech integrated laser weapon unusable

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#56132] opened 2022-03-16 11:36 UTC
### Describe the bug

When entering a "Spectre" Recon Mech, it's integrated "recon_mech_laser" weapon isn't created, and your hands are left empty. Hitting f while piloting the mech results in a prompt to choose a weapon to draw, which then fails because I'm riding a mech and cannot wield normal weapons.

### Steps to reproduce

1. Find a recon mech (or spawn one with debug)
2. Unlock it with a military ID card
3. Enter the mech
4. Stare confusedly at your empty hands when attempting to attack with the mech

### Expected behavior

The integrated laser sniper weapon for the mech should be usable while piloting it.

### Screenshots

![image](https://user-images.githubusercontent.com/19789267/158581166-0948af25-51f3-4b84-8cfb-41ed165d7100.png)
What happens when I hit the f key while piloting the mech

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: ef1e34c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ERRORCODE509** [comment] 2022-03-16 16:00
Duplicate of #54238

**Closed** 2022-03-17 12:19 UTC
