### ISSUE TITLE
Crash after loading

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#19669] opened 2016-12-07 14:01 UTC
Just playing build (g22cda4f) on windows and the game crashed after crafting. Fortunately, the game auto-saved, But I can't load the game back. As soon as it loads, it crashes again. The latest build also crashes.

Save file included.
http://s000.tinyupload.com/index.php?file_id=11732168255261938701

Debug log:
http://pastebin.com/Ancz768E

**Comment by codemime** [comment] 2016-12-07 14:28
Iterator invalidation in `bool npc::adjust_worn()`:
```

#0 0x7ffff68b4267	__GI_raise(sig=sig@entry=6) (../sysdeps/unix/sysv/linux/raise.c:55)
#1 0x7ffff68b5eca	__GI_abort() (abort.c:89)
#2 0x7ffff721f845	__gnu_debug::_Error_formatter::_M_error() const() (/usr/lib/x86_64-linux-gnu/libstdc++.so.6:??)
#3 0x4650f2	__gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >::operator++(this=0x7fffffffcc40) (/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/debug/safe_iterator.h:287)
#4 0x4c2fe8	npc::adjust_worn(this=0xc655ae0) (src/npcmove.cpp:3278)
#5 0x4c1cc7	npc::address_needs(this=0xc655ae0, danger=0) (src/npcmove.cpp:1111)
#6 0x4b5d5d	npc::address_needs(this=0xc655ae0) (src/npcmove.cpp:986)
#7 0x4b32a3	npc::move(this=0xc655ae0) (src/npcmove.cpp:310)
#8 0x84c8a2	game::monmove(this=0x7ae6800) (src/game.cpp:6006)
#9 0x840b22	game::do_turn(this=0x7ae6800) (src/game.cpp:1539)
#10 0xd9ed17	main(argc=0, argv=0x7fffffffe4e0) (src/main.cpp:491)

```

**Comment by lucasmr** [comment] 2016-12-07 14:30
I gave the NPC a leg splint earlier, so maybe the wound healed and he removed it.

**Comment by codemime** [comment] 2016-12-07 14:39
Thanks for the hint. It's actually a dupe of  #18281, so I have to close this.

**Comment by lucasmr** [comment] 2016-12-07 14:42
OK, can you validate the older issue?

**Comment by codemime** [comment] 2016-12-07 14:46
Done. BTW Thank for the file as well. Now the issue is easily reproducible.

**Closed by codemime** 2016-12-07 14:46 UTC
Labels: Crash, Duplicate, NPC, validated

**Comment by lucasmr** [comment] 2016-12-08 15:58
Thanks.
