### ISSUE TITLE
"Auto inventory letters" feature does not working.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#45625] opened 2020-11-25 14:15 UTC
# Describe the bug
When an item is set to favorited, no hotkey is assigned to the item.

# Steps To Reproduce
1. Set "Auto inventory letters" in Option > Interface, to "Favorites".
2. Open inventory and highlight any item in inventory.
3. Use hot key "*" to assign that item as favorited.

# Expected behavior
When assign an item as favorited, a hotkey in alphabet order should automatic be assigned to the favorited item.

# Versions and configuration
 - OS: Windows 7
 - Game Version: 0.E-7497-g48b6f14 [64-bit]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, no_npc_food, package_bionic_professions, magiclysm, crazy_cataclysm, my_sweet_cataclysm, Graphical_Overmap, Graphical_Overmap_Magiclysm, speedydex, stats_through_kills, StatsThroughSkills.

**Comment by wapcaplet** [comment] 2020-11-25 16:07
Confirmed. When "Auto inventory letters" (line 46 of the options "Interface" tab) is set to "Enabled" or "Favorites", letters are only assigned to items when they are *worn* or *wielded*, not to any other items that are picked up and stored in container pockets. When set to "Favorites", enabling the "favorite" option for any item does not cause it to get an automatically assigned letter, except when using the `w`ield or `W`ear action.

**Comment by TheEskir** [comment] 2021-06-05 18:27
Any updates on this? Same thing in latest experimental.
I'm used to using the auto-hotkey feature, but it doesn't work. I have 2 items with auto-hotkeys assigned, but they're both "c" and they were both assigned because I wielded them for a short while.

![image](https://user-images.githubusercontent.com/26084686/120901624-63d25c00-c63c-11eb-8732-14fd8c3ee25d.png)

**Comment by KurzedMetal** [comment] 2021-07-06 14:13
"Auto inventory letters" is not just only bugged for favorites, it's broken for "Enabled" (all items) too and it has been like this for quite a while.

The only one that seems that is consistently assigned a letter is the weapon.
And many times I noticed the letter on the weapon is many times using an already used letter (two items same letter!). 
This issue is described in #43254

**Comment by exuvo** [comment] 2021-07-13 02:18
None of my picked up items are being assigned letters on "Enabled", how did they not fix this for the release of 0.F ??

**Comment by exuvo** [comment] 2021-07-13 17:54
As i hate playing without this feature and seeing that it is not completely broken i'll download the code and see if i can fix it.

I assume the nested inventory is the problem as "Item hotkeys assigned" only counts top-level items (held and worn).
Given that assignment works on worn held/items it might just be that someone forgot to call assign_empty_invlet somewhere.

**Comment by exuvo** [comment] 2021-07-13 19:50
Well i got it to stop duplicating names at least. And i am right in that it is not calling the assign function when items go into a container. No clue where in the code that is though.

**Comment by actual-nh** [comment] 2021-07-13 20:46
If you could do your current patch as a PR, it would be a lot easier for other people to help with it (as well as contributing to the game).

**Comment by exuvo** [comment] 2021-07-13 23:32
I already got a fork up, but was planning to fix the assignment bug too before making a PR.

**Comment by exuvo** [comment] 2021-07-14 00:22
Well i got it working for the most part, i had one time during multi pickup where one item was not assigned not sure why. But it is working for most things. Might have bugged because i those items had the same letter before as i had those wielded before my fixes and they were assigned the same letter.

**Closed** 2021-07-21 06:18 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface, Inventory / AIM / Zones
