### ISSUE TITLE
Discrepancy in morale boosts promised and attained when reading some books

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12233] opened 2015-04-28 23:59 UTC
Build 350c5fe.

'Rural Digest-Examiner' promises a morale boost of 1 per read, but when viewed in 'v' after having read it once, it's listed as 5.

'comic book' promises +2 morale per read, but viewed in 'V' it's 10.

If it's important, I have "Fast Reader" trait and int 12 on this character.  I think whatever the book descriptions say and what the game later says happened should be consistent.
##

**Comment by tyrael93** [comment] 2015-04-29 09:35
I've noticed you've started a lot of issues in the last week. An ungodly number of them. That's not too bad, some of those were actually useful and quick fixes too, while others, like the meat pie one just off the top of my head, are due to the fact that you do not really know too much about the game yet. This might be the case again.

Any +1 modifier on a book gives you 5 points of morale every time you read it. 5 is the standard unit. A comic book gives you +10 because it has a +2 modifier, up to a +30 morale for reading it thrice. Same goes for every other book with maluses (-1/2 up to -5 of to serve amn as a non-cannibal, which get a whopping +75 morale from reading it twice).

So in conclusion it's not a bug. That's just how the game works. Next time please refrain from starting an issue only because of this.
Going back to my opening statement, why not start threads in the forum instead of issues in github? There is a whole section of the forum for resolving problems and pointing out bugs. Not the issues category in git. I suggest you look at the problem from different perpectives and if it's a simple thing like the #12215 then it's a great use of the issue module, but if it turns out to be something like this or #12194, it's a bad idea to start an issue and you should instead make a thread on the forums, (or first search it in the forum instead and only later make a thread about it).
Got it? Great. You have a nice day now.

**Comment by Coolthulhu** [comment] 2015-04-29 10:00
In this case it is a misrepresentation, which while may not technically be a bug, is still an issue. A very small issue, but an issue nonetheless.

Reporting tiny issues is fine (the issue list doesn't scroll all that fast), though I agree that a forum thread would be good. A big list of unfixed minor issues with OP updated to keep the track of the ones actually unfixed would help to quickly gauge how broken tiny things are.

**Comment by kevingranade** [comment] 2015-04-29 18:45
If there is a misunderstanding (which this one is not, the interface is
unclear), we can just as easily clear it up here and close the issue as we
could do so on the forums.  It's also OK to put them on the forums, but for
very specific issues like this, either is fine.  The kind of issue we
prefer to have on the forums are vague issues or lists of them such that it
becomes difficult to track progress in closing them.
@greysage1, your issues are appreciated, thanks.

**Comment by graysage1** [comment] 2015-04-29 22:38
@kevingranade Thank you for the kind words.

**Comment by DavidKeaton** [comment] 2015-04-29 22:56
agreed, you've helped me find some bugs in AIM, which is great! thanks man! :-)

**Comment by Leland** [comment] 2017-05-04 12:58
Closing as this isn't a bug, and has had stalled conversation for a couple years now. If anyone wants this open still, let me know – or feel free to open up a new issue.

**Closed by Leland** 2017-05-04 12:58 UTC
Labels: Information / Interface
