### ISSUE TITLE
I dread looking into the armor tab of the crafting menu because of lag

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#57988] opened 2022-05-29 02:36 UTC
### Describe the bug

When your survivor takes a few levels in fabrication, stockpiles materials and a few books, you get a lot of recipes in your brain.
The issue is that there are SO many recipes that it actually lags my game between 5 and 15 seconds, roughly. 
This is a large issue which will only get worse as more items are added in.

### Steps to reproduce

1. Get high fabrication and tailor skills.
2. Get tailoring books and armor making books.
3. Open armor tab.
4. Watch as Windows tells you this program is frozen.

### Expected behavior

I would like the experience of looking into tabs to be fluid.

A possible bandaid could be that players navigate top level categories, then narrower ones, before the game loads the items.
Another would be to keep it all into memory, all the time. But that all depends on how the game actually does things. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 9129922 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment] 2022-05-29 02:40
Duplicate of #57975

**Comment by Maleclypse** [comment] 2022-05-29 04:26
Closed in favor of the earlier issue that has profiling on it already.

**Closed** 2022-05-29 04:25 UTC
Labels: (S1 - Need confirmation)
