### ISSUE TITLE
Using Atomic lamp or any other lamp with the "Covered" and "Uncovered" feature causes the light to follow you

### ISSUE THREAD

**Issue by KestasV** [CleverRaven/Cataclysm-DDA#69163] opened 2023-11-07 14:02 UTC
### Describe the bug

Using Atomic lamp or any other lamp with the "Covered" and "Uncovered" feature causes the light to follow you, regardless if you have the lamp or in inventory or not.

### Attach save file

It's trivially reproducable
Add an atomic lamp (covered)
Put it in a cargo space
Uncover it, and voila - walk around with your infinite light while your lamp stays in the car.

### Steps to reproduce

Put an atomic lamp (covered) in your car in a cargo space
Use or "uncover" it
Go walking around without the lamp, but the light following wherever you go

### Expected behavior

Expecting the light to STAY where the lamp is.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/37342061/076e44dc-13c3-4fdd-a89e-1490f660b5e0)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/37342061/0f8f2295-404a-474f-8b0f-ddc71a097bce)

### Versions and configuration

Experimental Build 2023-11-07-0434 and every previous version

**Comment by gettingusedto** [comment] 2023-11-07 14:04
duplicate of #68435

**Closed** 2023-11-09 18:00 UTC
Labels: (S1 - Need confirmation)
