### ISSUE TITLE
Corpses generated on building roofs create items floating in midair.

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70783] opened 2024-01-08 22:45 UTC
### Describe the bug

Found a gun floating in midair on a tile where "military corpses" generated on a roof.

### Attach save file

[Rock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13866885/Rock-trimmed.tar.gz)

### Steps to reproduce

generate "military corpses" on a building tile

### Expected behavior

generated items and corpses on roofs should fall to the ground if they generate in midair

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/d232efea-fd93-4127-92af-02d5119db601)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: a2b8c9a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment] 2024-01-08 22:48
Duplicate of #36635

**Closed by RenechCDDA** 2024-01-08 22:48 UTC
Labels: (S1 - Need confirmation)
