### ISSUE TITLE
Fullscreen mode causes crash on linux mint

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#27953] opened 2019-01-28 21:28 UTC
Attempting to start the game in fullscreen mode causes a crash

1. Change the game to full screen mode in the options
2. Save the options and quit the game
3. Attempt to run the game again

The game should not crash. The game works in windowedbl mode

 - OS: Linux Mint 19 Tara x64
 - Game Version: 0.C-37135-g8efc667
 - Graphics version: Tiles
 - Mods loaded: none

Error:
TYPE: St12length_error
MESSAGE: vector::_M_default_append

Let me know if you want the stack trace or any debugging tests done

**Comment by Dunkhan** [comment] 2019-01-28 23:38
Forgot to mention: I am using two monitors with different resolutions on extended desktop mode. This could be part of the cause.

**Comment by ZhilkinSerg** [comment] 2019-01-29 07:49
Yes, stacktrace would help probably.

**Comment by Dunkhan** [comment] 2019-01-29 19:16
https://pastebin.com/D2U9rc7Z
The weird thing is when I went to reproduce this again today I couldn't. I reproduced it 3 times in a row (not three crashes, three times setting it to fullscreen mode) and it happened every time. Now it does not.

I don't know if you want to close this or leave it up as a low priority in case others have the issue, but the fact that I cant reproduce it anymore means it would probably be a waste of time for a developer to try.

**Comment by Night-Pryanik** [comment] 2019-01-29 20:53
We'll wait some more time. Maybe you or someone else will confirm this later.

**Comment by mark7** [comment] 2019-02-01 18:18
Happens during memory allocation, so could be memory corruption earlier in the startup process blowing up now.

@Dunkhan: Would you attach your options.json to the issue, please?

**Comment by mark7** [comment] 2019-02-01 20:47
FWIW, digging into possible memory corruption: building that hashref, I didn't see anything suspicious under valgrind memcheck other than a use of uninitialized memory that looks to be internal to llvm that comes up with hardware rendering enabled.  I doubt that that's the problem, but was the reason that I wanted the options.json with the problematic settings.

**Comment by Dunkhan** [comment] 2019-02-02 10:40
https://pastebin.com/BdefSv1X <-options.json

**Comment by Night-Pryanik** [comment] 2020-04-13 17:54
Closing as non-confirmed for more than a year.

**Closed by Night-Pryanik** 2020-04-13 17:54 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, OS: Linux
