### ISSUE TITLE
Lit charcoal kiln will be ready in 1 year

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#12648] opened 2015-06-13 11:30 UTC
I lived for several year, filled and lit a kiln, died, started a new character and found my way back to my base. The charcoal kiln I left burning now says "will be ready in 1 year" and can't be disassembled.

**Comment by BevapDin** [comment] 2015-06-13 12:24
Duplicate of #11700, tanning hides use the same mechanics that is used by the kiln.

**Comment by mikegogulski** [comment] 2015-06-14 21:01
Thanks.

**Closed** 2016-08-11 13:28 UTC
Labels: Bug, Duplicate
