### ISSUE TITLE
Evac shelter computer strings are not collected for translation

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23555] opened 2018-04-20 22:08 UTC
Game version: dbf2bebfd42f1184f899310aedc2bd0dba02d621

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Missing strings

The following strings from the evac shelter computer do not get collected for translation:

* `Evac shelter computer`
* `Emergency Message`
* `Contact Us`

### How to reproduce
* Look into `lang/po/cataclysm-dda.pot` and search for the strings above

**Comment by AMurkin** [comment] 2018-04-21 06:33
Duplicate of the #20829

**Comment by illi-kun** [comment] 2018-04-21 08:04
The mentioned report contains two unrelated issues, so I'd prefer to update it for keeping only 'major' issue.

**Comment by illi-kun** [comment] 2018-04-21 08:07
Oh, I see my previous statement is incorrect. It seems that the mentioned issue (if the real issue is strings not extracted for translation) should lost only this part:

> Another example as in evac shelter computer menu.

**Comment by Wuzzy2** [comment] 2018-04-21 13:40
I suggest to rip out the “minor” part out of #20829, as these are two unrelated issues.

**Closed** 2018-07-15 08:29 UTC
Labels: Translation
