### ISSUE TITLE
NPC training Brawling keeps increasing Melee skill

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16361] opened 2016-04-24 04:28 UTC
I have this NPC following me around. Every time I ask him to training me in Brawling (which has no skill level, it seems), I just raise another level of Melee

**Comment by BevapDin** [comment] 2016-04-28 10:09
The NPC might teach the Brawling *martial art style*. How much did the NC charge for it? And did you gain that style? The style is automatically learned upon level 2 of unarmed combat skill, so what was your current level of that skill?

**Comment by Coolthulhu** [comment] 2016-05-05 00:12
Can't reproduce

**Comment by mugling** [comment] 2016-11-28 22:30
Closed as unconfirmed

**Closed by mugling** 2016-11-28 22:30 UTC
Labels: Confirmation Needed, NPC
