### ISSUE TITLE
Crash loading save

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#58817] opened 2022-06-29 10:36 UTC
### Describe the bug

Game crashes when loading character.
Note: Savegame is underground in a subway and only there crashes before it was all ok.

### Steps to reproduce

1. Try loading save

### Expected behavior

Should load the saved game.
Something with subway is messing the game.

### Versions and configuration

OS: Windows 10
Version: 9ab7cf1
Tiles: Undead
Mods: 
DDA
Disable NPC Needs
No fungal growth
Bionic professions
Blaze industries
Xedra Evolved
Alt Map Key
Extra mutated scenarios
Speedy dex
Bionic slots

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9009634/crash.zip)

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9009637/debug.zip)

[Marlow Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9009639/Marlow.Heights.zip)

**Comment by andrei8l** [comment] 2022-06-29 11:00
/confirmed ACT_HACK was not serialized properly. In fact, `hacking_activity_actor::serialize()` is a dummy function!! It should at least write a dummy object like this:
```diff
diff --git a/src/activity_actor.cpp b/src/activity_actor.cpp
index b0ab82ccb5..dd8bf57005 100644
--- a/src/activity_actor.cpp
+++ b/src/activity_actor.cpp
@@ -781,7 +781,10 @@ void hacking_activity_actor::finish( player_activity &act, Character &who )
     act.set_to_null();
 }
 
-void hacking_activity_actor::serialize( JsonOut & ) const {}
+void hacking_activity_actor::serialize( JsonOut &jsout ) const
+{
+    jsout.write_null();
+}
 
 std::unique_ptr<activity_actor> hacking_activity_actor::deserialize( JsonValue & )
 {
```

Since your save is borked and it can't be easily post-fixed in code, I've manually fixed it for you: [Marlow Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9009839/Marlow.Heights.zip)

**Comment by StefanMiletic994** [comment] 2022-06-29 11:14
Thanks!

**Comment by Maleclypse** [comment] 2022-09-11 15:13
> /confirmed ACT_HACK was not serialized properly. In fact, `hacking_activity_actor::serialize()` is a dummy function!! It should at least write a dummy object like this:
> 
> ```diff
> diff --git a/src/activity_actor.cpp b/src/activity_actor.cpp
> index b0ab82ccb5..dd8bf57005 100644
> --- a/src/activity_actor.cpp
> +++ b/src/activity_actor.cpp
> @@ -781,7 +781,10 @@ void hacking_activity_actor::finish( player_activity &act, Character &who )
>      act.set_to_null();
>  }
>  
> -void hacking_activity_actor::serialize( JsonOut & ) const {}
> +void hacking_activity_actor::serialize( JsonOut &jsout ) const
> +{
> +    jsout.write_null();
> +}
>  
>  std::unique_ptr<activity_actor> hacking_activity_actor::deserialize( JsonValue & )
>  {
> ```
> 
> Since your save is borked and it can't be easily post-fixed in code, I've manually fixed it for you: [Marlow Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9009839/Marlow.Heights.zip)

Can this be closed or should I mark this as a stable blocker?

**Comment by andrei8l** [comment] 2022-09-12 03:36
IIRC that small diff was the only change needed, but I don't have the time/interest to investigate atm; sorry.

**Closed** 2022-10-07 01:19 UTC
Labels: <Bug>, <Crash / Freeze>, (S2 - Confirmed)
