### ISSUE TITLE
Unable to enter any vehicle due to "not enough room" 

### ISSUE THREAD

**Issue by UltraEarth** [CleverRaven/Cataclysm-DDA#74601] opened 2024-06-16 17:00 UTC
### Describe the bug

Can't enter any vehicle unless naked and even that way i get the message of being in a cramped space, sometimes i can enter other seats while being clothed and then enter the conductor seat but if i move i can't enter it again.
Left any bag with weight aside and tried again but the bug persists.

### Attach save file

[Chibitown-trimmed.tar.gz](https://github.com/user-attachments/files/15859103/Chibitown-trimmed.tar.gz)

### Steps to reproduce

1. Approach the conductor seat of a vehicle.
2. Try to enter the vehicle.
3. Can't enter it.

### Expected behavior

To being able to enter the seat and use the vehicle.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-16-1205 a9d18c8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Battle Maid Redux (ReMaidster edition) [battle_maid],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Easy Proficiency [sch_easy_proficiency],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    DinoMod [DinoMod],
    World on Fire [World_on_fire],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Extra Mutated Scenarios [extra_mut_scens],
    Blazemod - Vehicle Additions Pack [blazemod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Pixel's Various Fuckery [Pix's Shit]
]

**Comment by ZhilkinSerg** [comment] 2024-06-16 18:49
Probably a duplicate of #74560

**Comment by Maleclypse** [comment] 2024-06-18 04:34
Closing as duplicate issue.

**Closed by Maleclypse** 2024-06-18 04:34 UTC
Labels: (S1 - Need confirmation)
