### ISSUE TITLE
Driving over kill-mission NPC: "overmapbuffer::remove_npc: NPC (163) not found."

### ISSUE THREAD

**Issue by Dekker3D** [CleverRaven/Cataclysm-DDA#30295] opened 2019-05-07 15:20 UTC
**Describe the bug**  
I have a savegame where I'm about to ram three bandits to death for a refugee center quest (the merchant faction). When I ram them to death, I often (very repeatably, but not 100%) get an error saying remove_npc failed because the NPC does not exist. After the error, I do see a corpse for the NPC I just killed. I savescummed to see whether it's repeatable, and it is.

**To Reproduce**  
1. Load the attached savegame.
2. Ram the 3 bandits to death, about a screen's distance to the northwest.
3. Get the error about 50% of the time for each kill.

**Expected behavior**  
No errors when I go Mad Max on someone's poor bandit arse.

**Screenshots**  
https://puu.sh/Dp51i/5b71fc7b65.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: 0.D-2638-gd09a0d2
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, More Locations, Fuji's More Buildings, No Explosive Zombies, StatsThroughSkills, Prevent Zombie Revivification. That last one was added after I started the world via savegame editing, but this seems unrelated to the error.

**Additional context**  
[Celada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3153332/Celada.zip)

**Comment by codemime** [comment] 2019-05-07 15:24
Dupe of #25329.

**Comment by esotericist** [comment] 2019-05-07 15:25
This, at least, has a reproducer case that wasn't in the other issue.

**Closed by codemime** 2019-05-07 15:24 UTC
Labels: (S3 - Duplicate), <Bug>, NPC / Factions, Vehicles

**Comment by codemime** [comment] 2019-05-07 15:59
It's appreciated and not lost (the issues are now linked), but there's no point keeping both open.
