### ISSUE TITLE
Car spawn bug

### ISSUE THREAD

**Issue by kydsh** [CleverRaven/Cataclysm-DDA#54861] opened 2022-01-28 09:40 UTC
### Describe the bug

Cars spawn in each other

### Steps to reproduce

1. go to non-generated area
2. get byg

### Expected behavior

spawn car alone

### Screenshots

![dasdadsadasd](https://user-images.githubusercontent.com/81353669/151522883-1c4f024f-99da-412f-9415-207ecc872a9f.png)
![dasda](https://user-images.githubusercontent.com/81353669/151522889-3f9fdc0b-d178-431a-8889-dae326728d75.png)
![assss](https://user-images.githubusercontent.com/81353669/151524205-84e69cde-b3d2-4045-b930-eba78e324ea1.png)

### Versions and configuration

windows 10

2022-01-28-0753

russian language

MODS

  "dda",
  "aftershock",
  "crt_expansion",
  "blazeindustries",
  "no_hope",
  "StatsThroughSkills",
  "stats_through_kills",
  "speedydex",
  "stamina_regen_buff",
  "crazy_cataclysm",
  "Graphical_Overmap",
  "WHALEYHAIR1",
  "DinoMod"

**Comment by BrettDong** [comment] 2022-01-28 11:46
Possibly related to #49105.

**Comment by LeahLuong** [comment] 2022-01-28 19:04
IDK, this looks like normal spawn behavior. Screenshots are in Cyrillic so it's hard to tell but those appear to be ordinary wreckages. Even if not, this is likely a dupe of #53862 based on the highlighted tile in 3rd pic.

**Comment by waxcatape** [comment] 2022-01-28 20:24
@LeahLuong those aren't wreckages, at least in name. From top to bottom it says "Police Car", "Mobile Meth Lab" and "Heavy-Duty Cargo Truck".

**Comment by morthein** [comment] 2022-01-29 17:24
I always thought this was normal. It's happened for a long time.  I assumed it was simulating a multiple car pileup.

**Closed** 2022-01-30 20:12 UTC
Labels: (S1 - Need confirmation), Map / Mapgen, Vehicles
