### ISSUE TITLE
10922 version breaks unofficial soundpacks walking sounds

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#43064] opened 2020-08-20 11:29 UTC
# Describe the bug
As of **experimental version 10922** while using @'s, 2ch, Otopack, my personal updated Otopack, CO.AG soundpacks - the sounds of **walking barefoot, walking on dirt, metal, tarmac** are missing even though all the soundpacks code is intact and fine and **it worked perfectly fine in 10921 and ANY version BEFORE 10922**

# Steps To Reproduce

1.  Update from any older version to 10922 or higher having installed AND enabled via the settings either @'s, 2ch, Otopack, my personal updated Otopack, CO.AG soundpack
2. Play the game and walk on the dirt OR spawn metal/concrete/asphalt floors via debug menu and walk on them - **no sounds are emitted while walking on these floors as of 10922**

# Expected behavior

Walking on dirt, metal/concrete/asphalt floors emits sounds properly just like on versions before 10922

# Versions and configuration

 - OS: Windows 10 64 bit
 - Game Version: **0.E-5173-g7d18521**
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda

# Additional context

I am well aware that these soundpacks are unofficial but since one of these is being used by all players by default **and the fact that there were NO soundpacks code changes, the bug is caused by the game itself**, it would be nice if developers might help out with fixing it or finding a way to do that, since - once again - as I repeat - the problem is not with the soundpacks - that was tested by me and numerous players a multiple amount of times, the bug is caused by 10922 experimental version and above

**Comment by Fris0uman** [comment] 2020-08-20 11:35
> breaks unofficial soundpacks

There is no official soundpacks, you can just say that there's a bug with sound

**Comment by anothersimulacrum** [comment] 2020-08-20 13:25
There is one, but it's just menu beeps.
Duplicate of #43057

**Closed by anothersimulacrum** 2020-08-20 13:25 UTC
Labels: (S3 - Duplicate)
