### ISSUE TITLE
Item Duplicated when Drawed from a container.

### ISSUE THREAD

**Issue by ClOxIon** [CleverRaven/Cataclysm-DDA#44758] opened 2020-10-09 08:16 UTC
# Describe the bug

When you have a wearable container A and try to "wear" container A, a prompt asking "draw from A?" pops up. When you select yes and draw any item from A, you obtain a copy of that item.

# Steps To Reproduce

Put a tool belt inside a hiking backpack. Try to wear the backpack. Before you wear the backpack, a prompt pops up asking whether you want to draw from the backpack. Press yes and draw the belt from the backpack. At this point, you have your belt duplicated. After that, the prompt pops up again, but whatever you choose it doesn't matter.

# Expected behavior

When you draw B from A, B should not be in A anymore.

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: [from the main menu, e.g. 0.E-6535-geec6301]
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DDA

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-10-09 09:01
Duplicate of #43174

**Closed** 2020-10-24 01:51 UTC
Labels: (S3 - Duplicate)
