### ISSUE TITLE
Statsthroughkills usually crashes to desktop upon killing enemies

### ISSUE THREAD

**Issue by Gourmand-is-OP** [CleverRaven/Cataclysm-DDA#65007] opened 2023-04-11 19:27 UTC
### Describe the bug

Stats through kills has a tendency to crash the game when killing enemies, occurring most, but not all of the time.

### Attach save file

[I'm Still Fine-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11204095/I.m.Still.Fine-trimmed.tar.gz)
[Velma-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11204179/Velma-trimmed.tar.gz)

### Steps to reproduce

1. Load save or create new save
2. Kill enemies

### Expected behavior

The game would allocate points towards a new stat point, and not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 41d1f50 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    <color_light_green>Cataclysm++</color> [Cata++],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

2nd world for consistency
- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 41d1f50 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11204131/crash.log)
The problem does not occur on every single kill, but does on most of them.
Crash has been replicated on both worlds.

**Comment by andrei8l** [comment] 2023-04-11 19:31
This is the pinned achievement bug and it was fixed today. Try again with the latest build.

**Comment by anothersimulacrum** [comment] 2023-04-11 20:58
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed** 2023-04-11 20:58 UTC
Labels: (S4 - Invalid)
