### ISSUE TITLE
Vandalized libraries have open air spaces leading down a z-level that turn into dirt on a save-load

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#62692] opened 2022-12-11 13:08 UTC
### Describe the bug

See title - the vandalized variants of libraries, as well as the collapsed tower, spawn riddled with holes leading down a z-level. These holes can lead to solid dirt tiles, or down a z-level into stuff like sewers. Once you save and load the game, the open spaces will be replaced by dirt. These can take the place of both floors as well as walls.

### Steps to reproduce

1. Find or spawn in a vandalized library.
2. Approach the library naturally - **do not teleport, as this will spawn dirt tiles straight away instead of open air. No idea why, it just does!**
3. Observe many holes bashed into the ground and walls.
4. Save and reload; note how the holes disappear.

### Expected behavior

The terrain shouldn't be destroyed at all! If it *is*, however, it should at least leave foundations and not open space, and at bare minimum should not change upon a save-load.

### Screenshots

Here's a looted library shown before and after a save-load.

![](https://media.discordapp.net/attachments/969328938167971940/1048568564782739486/cataclysm-tiles_99GYUGUPtF.png)

![](https://cdn.discordapp.com/attachments/969328938167971940/1048568565181206568/cataclysm-tiles_DWvrny9VCY.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 0.F-12756-g67c5c2ff8b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

This appears to be a consequence of the `bash` def in the library's mapgen. The relevant code uses a bash strength of `9999` as well as providing no options or logic to let it skip terrain, meaning that both terrain and furniture are treated equally - with max-strength bashes. This could potentially be fixed by using the `destroyed_furniture` nested mapgen ID, but it wouldn't fix the overall problem caused by the map extra.

**Comment by andrei8l** [comment] 2022-12-11 13:19
Some previous related issues #54237 #61552. 

The holes are caused by `bash` mapgen function bashing the terrain as you've noted, and the holes are filled up by auto-roofing which runs at the wrong time (on `map::load()`, but not on `map::shift()`).

Fixing the first issue probably only requires wrangling the decade-old `map::bash_ter_furn()`. Fixing the second one properly is quite complicated.

**Comment by Ilysen** [comment] 2022-12-11 13:23
Oh yeah hrm, I guess this *is* a duplicate. I dug around in the issue tracker beforehand, but I probably missed it. Not sure if I should close this or not, as this one has a lot more information? I guess I'll leave it up to the triage folks

**Comment by Night-Pryanik** [comment] 2022-12-11 13:41
Closing as duplicated.

**Closed by Night-Pryanik** 2022-12-11 13:41 UTC
Labels: (S1 - Need confirmation)
