### ISSUE TITLE
error when searching for a refugee camp

### ISSUE THREAD

**Issue by Kekeksksj** [CleverRaven/Cataclysm-DDA#49285] opened 2021-06-13 14:52 UTC
Hello, I found a bug in the latest experimental version for android, when in the shelter in the terminal you click to find a refugee camp, the game freezes and after a while gives an error, fix it you are welcome

**Comment by ZhilkinSerg** [comment] 2021-06-13 20:45
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/38993

**Comment by actual-nh** [comment] 2021-06-13 21:58
@Kekeksksj: Could you report in a bit more detail what mods you are using, and show a copy of the error?

**Comment by PatrikLundell** [comment] 2021-06-14 07:41
It can also be noted that "latest" is a next to worthless specification of version. A new version may have been released while you wrote the report, and even if it wasn't, any investigator would have to try to find out what the "latest" version was at the point in time in the past the report was made.

**Comment by Kekeksksj** [comment] 2021-06-14 07:53
@actual-nh 
- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi 7A; Release: 10; Incremental: V12.0.2.0.QCMRUXM; 
- Game Version: fa0b7d6 [32-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Бионические профессии [package_bionic_professions],
    Расширение К.Р.И.Т. [crt_expansion],
    Темные Дни Мертвых [classic_zombies],
    Характеристики за убийства [stats_through_kills]
]
12:49:00.849 ERROR : (error message will follow backtrace)#01: 0x87ff86d8 DebugLog(DebugLevel, DebugClass)
#02: 0x87ff8284 realDebugmsg(char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#03: 0x87dcadc0 void realDebugmsg<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&>(char const*, char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#05: 0x8842ef8e mission_util::assign_mission_target(mission_target_params const&)
#06: 0x8842c00e mission_start::reveal_refugee_center(mission*)
#07: 0x88411c8e mission::assign(avatar&)
#08: 0x87f75e5c computer_session::action_emerg_ref_center()
#09: 0x87f713aa computer_session::use()
#10: 0x880cbb4a game::use_computer(tripoint const&)
#11: 0x880d31da game::examine(tripoint const&)
#12: 0x880d2e46 game::examine()
#13: 0x88136a8e game::handle_action()
#14: 0x880b9158 game::do_turn()
#15: 0x883270a4 SDL_main
#16: 0x896d3e2a Java_org_libsdl_app_SDLActivity_nativeRunMain
Backtrace emission took 0 seconds.
(continued from above) ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/mission_util.cpp:252 [cata::optional<tripoint_abs_omt> find_or_create_om_terrain(const tripoint_abs_omt &, const mission_target_params &)] Unable to find and assign mission target refctr_S3e.
![Screenshot_2021-06-14-12-40-49-281_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/76586736/121857928-87b63180-cd0f-11eb-941b-00a816e9ef54.jpg)

**Comment by Kekeksksj** [comment] 2021-06-14 08:02
@PatrikLundell i provided version and list of mods as well as error

**Comment by eltank** [comment] 2021-06-20 23:31
This is caused by the `classic_zombies` mod, which disables the Refugee Center, probably because of the quest that spawns a shocker zombie in there.

**Comment by actual-nh** [comment] 2021-06-21 02:49
> This is caused by the `classic_zombies` mod, which disables the Refugee Center, probably because of the quest that spawns a shocker zombie in there.

Sounds like it needs to also disable scenarios involving the Refugee Center (possible with 0.F-dev IIRC) or quests that spawn blacklisted monsters need to be disabled. Ping: @I-am-Erk?

**Comment by eltank** [comment] 2021-06-21 05:17
Actually, I see that the quest that spawns the non-classic zombie in the Refugee Center is JSON-ified. I'll make a PR changing the classic_zombies mod to override that quest to spawn a tough zombie instead, then allow the Refugee Center in classic mode.

**Comment by I-am-Erk** [comment] 2021-06-22 03:09
For the moment I wonder if we can remove the console entirely in classic zombies mode.

**Comment by eltank** [comment] 2021-06-22 05:26
> For the moment I wonder if we can remove the console entirely in classic zombies mode.

The console definition is duplicated in 2 mapgens and 6 nested chunks. It's not that easy to get rid of it unless you just get rid of all evac shelters.
Probably easier to modify the `emerg_ref_center` action to do nothing. One hacky way to do it would be to check the `DISABLE_ROBOT_RESPONSE` option (which the mod sets to true) in `computer_session::action_emerg_ref_center()`. How does that sound?

**Comment by I-am-Erk** [comment] 2021-06-22 06:21
What I'm thinking of is more infrastructural, I think we may want to talk to folks about a way to allow mods to overwrite existing maps. So, like, we'd make a new evac shelter for ddotd, without the console and with some other features. However, I'd also be open to removing it in favour of an alternate default start location... Ddotd is meant to be a Romero movie, the whole evac shelter thing doesn't really work.

**Comment by eltank** [comment] 2021-06-22 20:52
It's good to have a long term solution, but we still need something for the short term.
I did some more digging and found that it's possible to simply override the mission MISSION_REACH_REFUGEE_CENTER to do nothing, using just a few lines of JSON. I'll send a PR later today.

**Closed** 2021-06-23 01:56 UTC
Labels: 0.F Content Freeze, Fields / Furniture / Terrain / Traps, Map / Mapgen, Mods: Dark Days of the Dead
