### ISSUE TITLE
Item `medium_disposable_cell` was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#32583] opened 2019-07-24 02:09 UTC
# Describe the bug

After the changes from build 9363, I'm getting this message
``` 
DEBUG    : Item medium_disposable_cell was loaded with charges, but can not have any!
 
 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2142
```
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5809-g3549e18 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    No Fungal Monsters [No_Fungi],
    No Filthy Clothing [no_filthy_clothing]
]

**Comment by ZhilkinSerg** [comment] 2019-07-24 05:40
Probably duplicate of #32569

**Closed by ZhilkinSerg** 2019-07-24 05:40 UTC
Labels: (S3 - Duplicate), <Bug>, Ammo, Battery / UPS
