### ISSUE TITLE
Blazemod turrets are awkward to reload

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#17883] opened 2016-08-01 14:48 UTC
In the newest version, the only way to reload a mounted turret is to examine that tile, then a menu pops up, query the player what to do. The old approach to drop the ammo into turrets no longer works. Two options are _reload turret_ and _unload turret_. Unloading turrets is weird. It took hours in game to unload about 400 rounds. And reloading turrets is also terrible. I had hundreds of rounds of 8x40 ammo for a RM298 HMG turret, but it reloads only one round each time. I have to repeat 500 times to fill all them in? So if unloading 500 rounds takes 10 hours in the game, reloading 500 rounds takes me 10 hours IRL...

**Comment by mugling** [comment] 2016-08-01 21:49
You can stand over the turret and press `r` to reload.

> I had hundreds of rounds of 8x40 ammo for a RM298 HMG turret, but it reloads only one round each time

That sounds broken

**Comment by mugling** [comment] 2016-08-01 21:54
> Unloading turrets is weird. It took hours in game to unload about 400 rounds.

The entire magazine is removed in under a minute?

> I had hundreds of rounds of 8x40 ammo for a RM298 HMG turret, but it reloads only one round each time.

Cannot reproduce

> reloading 500 rounds takes me 10 hours IRL...

Timed as 30 minutes.

Marked as needing confirmation to see if anyone else can reproduce the above

**Comment by Lord-Helmchen** [comment] 2016-08-02 08:55
old save, using the mainline blazemod, have an M2 turret that also took hours of ingame time to unload ~200 rounds, and on reload takes a single bullet at a time.
As I didn't want to sacrifice CARGO space inside my milspec RV, it's mounted above the windshield, so I get the added fun of not being able to stand over the turret, which means two additional keypresses (examine, direction) for each bullet...

**Comment by Zireael07** [comment] 2016-08-02 09:34
@DLaboratory is yours an old save too?

**Comment by DLaboratory** [comment] 2016-08-02 10:39
@Zireael07 Yes, an old save played for near a month.

**Comment by Lord-Helmchen** [comment] 2016-08-02 10:55
5313, new world  Folding Parts, Vehicle Additions.
spawn car, M2 turret, turret frame, .50 ammo, toolbox, welder, batteries.
mount turret frame and M2 on car. load 200 bullets, one bullet at a time, which takes ~3 hours ingame.
unload turret, which takes ~90 ingame minutes (so, admittedly, not exaxtly "hours").
spawn .50 ammo belt. reload prompt still only recognizes single bullets.
both (d)umping and advanced inventory store belt and single bullets in drivers seat instead of reloading the turret above it.

**Comment by Zireael07** [comment] 2016-08-02 12:50
I thought there was a (time) problem with old saves migration, but now that @Lord-Helmchen says it wasn't "hours" but 90 minutes and a fresh world, it looks like a problem with the code in general.

@Lord-Helmchen if you try without the mods, do you get the same problem (single bullets)?

**Comment by mugling** [comment] 2016-08-02 17:30
> As I didn't want to sacrifice CARGO space inside my milspec RV, it's mounted above the windshield

Turret + seat is now permitted (actually turret plus any `CARGO` space). Turret + windscreen isn't especially sensible.

I'm reluctant to continue patching blazemod considering we are now reasonably close to merging  #17456 (waiting on #17746)

**Comment by Blaze-whatdoyoumeanitsalreadytaken** [comment] 2016-08-03 00:36
The issue with most turrets is that they have a clip size of 1. So you load a single bullet at a time with the new changes.

Originally, this was 0 so as to stop players from firing it by hand (mounted gun only flags didn't exist). It was changed to 1 when there was a change that broke this with burst firing weapons.

**Comment by Izicata** [comment] 2016-08-03 04:35
Probably related: my Laser cannon turrets aren't able to draw power from vehicle batteries anymore. I can only load them with batteries, one at a time.

**Comment by mugling** [comment] 2016-08-03 08:59
@Blaze-whatdoyoumeanitsalreadytaken you can apply `NO_RELOAD` to the base items and `USE_TANKS` to some of the other turrets. There are examples of both in `core`.

**Comment by Blaze-whatdoyoumeanitsalreadytaken** [comment] 2016-08-04 09:16
@mugling Well I know those exist now, but I don't plan on making any changes as I only have the originally uploaded version. Pushing that would just undo a month of changes.

@Izitaca That's the old VAP that currently comes with the game; laser cannon turrets still use the old "Battery" ammunition setting instead of the current "ups_charge" setting. That's why you're having that issue.

**Comment by Coolthulhu** [comment] 2016-08-04 09:44
A giant improvement that would be relatively easy to add would be to capture drop action when dropping exactly one ammo or magazine item on a compatible turret type, then attempt reload instead of dropping, only dropping if reload fails.

**Comment by mugling** [comment] 2016-08-04 09:49
> Well I know those exist now, but I don't plan on making any changes as I only have the originally uploaded version.

We are waiting on  #17746 and I think otherwise we are ready to merge the new blazemod? Any other requirements @Coolthulhu?

**Comment by Coolthulhu** [comment] 2016-08-04 15:55
> We are waiting on #17746 and I think otherwise we are ready to merge the new blazemod?

Once we have the unit test mod support, I'll only need to verify that the turret test is working and it should be good to go after that.

**Comment by mlangsdorf** [comment] 2018-08-12 03:40
Is this still an issue? I think the latest round of blazemod fixes resolves this.

**Closed** 2018-08-12 06:13 UTC
Labels: Mods, Vehicles
