### ISSUE TITLE
Let the player choose which items to use when installing a part in a vehicle

### ISSUE THREAD

**Issue by TaxyTails** [CleverRaven/Cataclysm-DDA#55350] opened 2022-02-13 20:41 UTC
### Is your feature request related to a problem? Please describe.

When I install a part in a vehicle I sometimes find that the worst part was installed instead of a brand new one. The only way to make the game differentiate is to wield the item and select that when it prompts which item to install

### Solution you would like.

Display a list of items with their location and condition

**Comment by TealcOneill** [comment] 2022-02-13 20:54
Duplicate of #11706

**Closed** 2022-02-13 20:56 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>, Vehicles, Quality of Life
