### ISSUE TITLE
crash and issues when using the spawn item debug menu

### ISSUE THREAD

**Issue by alien10000** [CleverRaven/Cataclysm-DDA#77763] opened 2024-11-11 19:38 UTC
### Describe the bug

i get a crash when scrolling trough the spawn item debug menu around the letter s. you can get around it to a limited extent by using the mouse. this problem wouldn't be so bad if it weren't for the fact that the transparency is set to high on the search bars

### Attach save file

N/A

### Steps to reproduce

1 open spawn item debug menu 
2 keep scrolling untill crash is encounted 

### Expected behavior

that the spawn item debug menu wouldn't crash 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 5497025 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens]
]
it did not occur when i removed 
    Bionic Professions [package_bionic_professions]
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens]

### Additional context

 DEBUG    : invalid recipe id "meal_bone_mill_2_1"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp
 LINE     : 66
 VERSION  : 5497025

 DEBUG    : Failed to find milling recipe for skunk skull.

 FUNCTION : final_info
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 5840
 VERSION  : 5497025

![bug report](https://github.com/user-attachments/assets/046e05f9-dffe-4922-96af-2e8607025156)

**Comment by RenechCDDA** [comment] 2024-11-11 19:46
Duplicate of #76334

**Closed by RenechCDDA** 2024-11-11 19:46 UTC
Labels: (S1 - Need confirmation)
