### ISSUE TITLE
NPCs spawn without weapons

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#20442] opened 2017-03-04 05:42 UTC
I've been spawning lots of NPCs recently and I've noticed NPCs with the NC_SOLDIER spawn without weapons (or ammo)  about one in five times.  I think it's the RNG assigning them an unarmed skill higher than their rifle skill so the game equips them with no weapon. They just need their unarmed skill lowered or removed to make that impossible.  The same probably goes for bandits and maybe other classes.

**Comment by SunshineDistillery** [comment] 2017-03-05 20:15
I was wrong. It doesn't have to do with the unarmed skill. So there's some other reason they are spawning empty handed.

**Comment by Coolthulhu** [comment] 2017-03-07 22:46
NPCs get items based on highest combat skills. Next time you see a weapon-less NPC, check the skills.

For some reason, throwing and archery don't have fallbacks, so NPCs with those skills as their highest are likely to spawn with nothing.

**Comment by SunshineDistillery** [comment] 2017-03-08 03:55
After seeing more examples, it looks like it might be from having melee or marksmanship higher than or equal to the highest combat skill.  Maybe the game sees those as normal combat skills and then can't find an item group.

**Comment by BorkBorkGoesTheCode** [comment] 2017-12-30 01:51
Here are some NPC itemgroups for marksmanship and melee, in case they're needed:

```
  {
    "type" : "item_group",
    "id" : "npc_melee",
    "items": [
      ["cudgel", 100]
    ]
  },
  {
    "type" : "item_group",
    "id" : "npc_gun",
    "items":[
      ["bbgun", 100]
    ]
}
```
BTW, melee and marksmanship skills are marked as combat skills in json.

**Comment by mqrause** [comment] 2022-07-21 20:00
Oh, #58648 is a duplicate of this (with a little bit more detail). Yes, this is still an issue.

**Comment by I-am-Erk** [comment] 2022-07-21 20:09
Closing this as the newer issue post has more information.

**Closed by I-am-Erk** 2022-07-21 20:09 UTC
Labels: <Bug>, NPC / Factions, Spawn, old issue - still valid?
