### ISSUE TITLE
Picking liquids up from the ground.

### ISSUE THREAD

**Issue by Medecube** [CleverRaven/Cataclysm-DDA#40897] opened 2020-05-27 17:38 UTC
# Describe the bug

Unloading a container and pouring the liquid on the ground. It becomes dirty. Trying to pick it up, getting the expected message. The liquid shows up in inventory, ~~identical copy of the one on the grounds.~~

# Steps To Reproduce

1. Wield a container filled with liquid.
2. Unload it on the ground.
3. Pick up the liquid.
~~4. The liquid duplicates: the same quantity remains on the ground, a copy of it appearing in the container.~~

# Expected behavior

Not being able to pick/~~duplicate the liquid~~.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2532-gf4bb830 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cube's_Extra_Things [Cube_ID]
]
(The last mod is a wip of mine, it only has one item added at the moment, however the bug happens even without it)

# Additional context

Screenshots with every steep I took.
https://imgur.com/a/i8oBECn

Edit: The duplication bug is solved, only picking up the liquid remained.

**Comment by anothersimulacrum** [comment] 2020-05-29 17:32
Cannot reproduce - filling a steel jerrycan with gasoline, unloading it, and pickup up the item from the ground results in no duplication. However, you shouldn't be able to pick up the gasoline you unload from the ground.

**Comment by Medecube** [comment] 2020-05-30 08:47
[save_file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4705366/save_file.zip)
Here is a save file in which I am able to pick up the water (dirty) from the ground. Just wielding a container and trying to pick it up works. On this version (10710) it doesn't actually duplicate it on the ground anymore in my tests.

**Comment by TheMasterGear** [comment] 2020-06-06 20:03
I can confirm this bug by dropping a heartburn liquid with multidrop, and then trying to pick up the liquid. It then clones the liquid at my character's feet.

![bug 3](https://user-images.githubusercontent.com/60374171/83953570-2eb7e180-a80f-11ea-96e1-0176b6ed35bc.png)
![bug 4](https://user-images.githubusercontent.com/60374171/83953572-337c9580-a80f-11ea-9fba-02ebc40f974c.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2919-g000ecc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Pixel's Various Fuckery [Pix's Shit],
    Pneumatic Guns [pneumatic],
    Ricky's Future Armory [futurearmory],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex]
]

**Comment by Valares** [comment] 2020-06-07 04:37
I can also confirm this bug, including the duplication...:
If you try to pick up some liquids (from a broken bottle/glass or anything spilled) by hand it will duplicate the liquid and drop it at your feet (it does not do that with toilet water*, but it does so with Belgian ale). If you have Auto-Pickup (and pickup from adjacent tiles) on, it can and will flood your base or the place you're looting within a few turns...
*While it does not duplicate the water, it will still move it to your feet. You can move it easily over to an other toilet to fill it into a container from there.

Windows 7 64-Bit,
Build 0.E-10733 Tiles for Windows 64-Bit,
No mods (other than the default "Disable NPC Needs").

**Comment by int-ua** [comment] 2021-01-14 23:44
This looks suspiciously similar to #40978

And it should've been fixed by #41042

Please comment if it's still an issue.

**Closed by int-ua** 2021-01-14 23:44 UTC
Labels: (S2 - Confirmed), <Bug>
