### ISSUE TITLE
Can't sheath hunting knife in survival utility belt

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#19641] opened 2016-12-05 03:56 UTC
What the title says. Almost every other knife I've tried (butcher, survival, etc) works just fine but hunting knives are seen as invalid subjects for the 'holster' action despite their description. The attempt results in a message stating "you don't have the necessary item at hand"

Win 10
0.C-20128-gbcb7a7b (tiles)

**Comment by Cyrano7** [comment] 2016-12-05 08:22
Can confirm. Survivor belt has the same problem. Knives that can be put in sheaths but not survivor belt or utility belt are the hunting knife, steak knife, butter knife, copper knife, stone knife. Butcher knife, survival knife, combat knife work fine though.

**Comment by CoroNaut** [comment] 2016-12-05 21:34
This has been around for at least 50 builds now, I thought it was already posted so said nothing about it :(

**Comment by hmstanley** [comment] 2016-12-07 00:45
I am no able to put survival knifes/hunting knifes in sheaths/ankle or otherwise, so is this expected behavior?

**Comment by kevingranade** [comment] 2016-12-07 07:37
Not sure, but it might be too big to fit.

**Comment by Regularitee** [comment] 2016-12-08 04:43
Also to add onto this bug, the same applies with guns. The pistol stock mod, for example, can increase a pistol's volume to the point it no longer fits in pistol holders. Despite that, you can't put them in rifle-sized holders either.

**Comment by jeremieroy** [comment] 2016-12-15 14:21
There is an issue with the min volume of holsters.
If an item is referenced to have a volume of 1 in the json definitions, (0.25 l) like most of the knife do.
They cannot fit in any holster  with a max_size >= 4. (which is the case for the survivor belt)
Previously they could fit any holster with a max_volume of 5 due to rounding. 
Since the min volume when not explicitly defined is max volume/3.
4/3 ==1 due to rounding.

There are 2 simple way to fix this.
Restore "old" rounding behavior (see my PR above)
Or explicitly set a min_value in the json file for all holsters  with small capacity.
If you set a min_volume of 1 for the survivor belt in the json file it works.

**Comment by codemime** [comment] 2016-12-19 23:52
Fixed with #19765.

**Closed by codemime** 2016-12-19 23:52 UTC
Labels: Bug, validated
