### ISSUE TITLE
Game Crash On Refilling Container With Liquids

### ISSUE THREAD

**Issue by DocEternal** [CleverRaven/Cataclysm-DDA#25076] opened 2018-08-23 08:30 UTC
Any time I attempt to refill a canteen/waterskin/anything that holds liquid the game gives an error stating that it attempted to refill the container with a non-liquid. Sometimes this causes the game to crash. Other times it will refill the container with a random liquid. This only happens when specifically trying to refill a container with liquids. Refilling a quiver with bolts causes no issue; neither does crafting a liquid and then selecting a container to store it in.

This issue has been happening for several days and I have tried it on a brand new character as well to ensure it wasn't limited to a single bad save.

**To Reproduce**  
1: Have a character with a container such as a waterskin or canteen that is empty.
2: Press "r" to open the refill options. 
3: Select a liquid to refill your container with.
4: Error pops up

**Expected behavior**  
Ideally, you would expect this action to refill your container with the liquid you selected.

**Screenshots**  
Here is a link to the error on the brand new character: [Error](https://i.imgur.com/9D21LTa.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-30793-gc876057
 - Graphics version: Tiles

**Additional context**  
Here is a link to the saves with both the original character and the new one that was made to test the issue. Roland is the original character, Noise is the second one who is standing right next to liquids that should be able to be used to reproduce the issue. 
[Saves](https://drive.google.com/drive/folders/1qyl4RtN_8UrYAnBIxMClktQXGKc_6D89?usp=sharing)

If there is any additional info or files I can provide, please let me know.
Thanks.

**Comment by alanbrady** [comment] 2018-08-24 05:38
I'm fairly certain this is a duplicate of #23552 and has already been fixed by #25075

Please retest with a new build.  The problem happens when close to overencumbered.

For reference why I'm pretty sure it's the same issue is because refilling a canteen or waterskin increases volume and can cause an 'inventory overflow' where the game forces you to drop items because you're carrying too much.  If this happens in the middle of an activity it breaks the location references in activity.targets.

**Comment by alanbrady** [comment] 2018-08-24 06:04
I could be mistaken, I just tried playing with refilling a waterskin and noticed some odd behavior.  I haven't pinned down something reproducible yet, but there is something wrong.

**Comment by DocEternal** [comment] 2018-08-24 23:08
The person who was working on [#25075](https://github.com/CleverRaven/Cataclysm-DDA/pull/25075) and I were talking before I posted this here. The issue definitely isn't encumbrance as it was tested when I have over 100lbs and 30L of inventory room available and was only refilling a small container (.5L-2L in size).

**Comment by alanbrady** [comment] 2018-08-25 07:43
I at least addressed the segfault so it shouldn't be crashing the game anymore, but the root cause of the issue is still not resolved.

**Comment by alanbrady** [comment] 2018-08-26 23:58
I think what is happening is active items go through a process_items sequence which copies the item, temporarily removes it in case processing deletes the item, and then puts it back, which kills the item_location reference we made before doing our activity.  Or something like that.  I'm still trying to figure out how the active item processing works, but that seems to be my intuition for the problem.

**Comment by alanbrady** [comment] 2018-08-27 04:32
So I'm 100% certain it's the active item processing that's causing it.  I talked with @kevingranade about it and there's not really an easy solution here.

The real root cause is that using item_location for activity.targets is bad, but there's no real other good way to reference items between turns without hacking stuff together.  Kevin tossed up the idea of UUIDs and I really like that idea, but the last discussion here about UUIDs was... difficult.

I think it can be done in a manageable way that doesn't break existing use cases, but it will require a good chunk of code to do and probably lots of testing to make sure we don't break anything.

What I would like to do is try to come up with some kind of workaround here in the interim to solve the problem now, but then refactor it later with the superior solution.

**Closed** 2018-08-28 06:45 UTC
Labels: (S2 - Confirmed), <Crash / Freeze>, Items / Item Actions
