### ISSUE TITLE
Item windows are not wide enough. Or line break is not working

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#77698] opened 2024-11-09 14:20 UTC
### Describe the bug

Item windows are not wide enough. Or line break is not working

![Long](https://github.com/user-attachments/assets/4acdd2bd-d8a3-4e66-b2bb-921f45a1e533)

### Attach save file

[West Branch-trimmed.tar.gz](https://github.com/user-attachments/files/17687903/West.Branch-trimmed.tar.gz)

### Steps to reproduce

Open any examine screen with any item.

### Expected behavior

Like in old versions, there was a working line break. The text didn't hide behind the borders of the window.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5073 (22H2)
- Game Version: 09f30df [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Kamejeir** [comment] 2024-11-09 14:23
Scroll to the side by also holding the shift key.

**Comment by BjoHart** [comment] 2024-11-09 14:26
> Scroll to the side by also holding the shift key.

Thank you for the workaroud.

But i think it shoud be possible to get a line break for the windows?
It looks kinda akward when you scroll the right:::

**Comment by Procyonae** [comment] 2024-11-09 14:51
Dupe of #77297, PR to fix it should hopefully be merged soon

**Closed by Procyonae** 2024-11-09 14:51 UTC
Labels: (S1 - Need confirmation)
