### ISSUE TITLE
Batch craft can't place liquids in nearby containers

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#17001] opened 2016-06-02 02:49 UTC
Exempli gratia;
I have a full plastic bottle of unclean water (2/2) and a half-full bottle of clean water (1/2).  On the ground 1 NW is an empty plastic canteen (0/6).  With a fire and pot nearby, batch craft 1x or crafting with ENTER succeeds and asks to choose between the half-full bottle and the canteen.  Batch craft 2x fails due to insufficient space, even though a 1x craft shows the empty canteen as valid fill target.

Has not been tested for other liquids but I suspect that any craft item which requires a container will suffer the same issue.

**Comment by Oskar636** [comment] 2016-11-09 04:33
Repeated exactly the same and the plastic canteen is a viable target. Replaced the pot with a diffrent boiling tool ( without volume for liquids ) and the canteen is still a viable target. Build 5861.

**Comment by Leland** [comment] 2017-05-24 20:26
Closing due to lack of reproduction. If anyone encounters the same, please ping me and I'll reopen, or you can just create a new issue.

**Closed by Leland** 2017-05-24 20:26 UTC
Labels: Bug, Confirmation Needed, Crafting
