### ISSUE TITLE
Milspec spotlights can shine their lights thru walls

### ISSUE THREAD

**Issue by mikt4743thesecond** [CleverRaven/Cataclysm-DDA#47341] opened 2021-02-08 17:53 UTC
# Describe the bug

Milspec spotlight creatures shine light through walls

# Steps To Reproduce

Be in a building near milspec spotlights, that has a roof

# Expected behavior

They would only be able to shine into areas they can see

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9526-g599c1ea-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Makeshift Items Mod [makeshift],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

**Comment by PaulBlay** [comment] 2021-02-08 20:31
This is true, I've seen the shine around corners into military bases myself. But does shutting the doors keep them out? I have the feeling it did but I don't remember for sure.

**Comment by ZhilkinSerg** [comment] 2021-02-08 21:34
Duplicate of #42454

**Closed** 2021-02-09 03:52 UTC
Labels: <Bug>, Fields / Furniture / Terrain / Traps, Monsters
