### ISSUE TITLE
Item description doesn't scroll down all the way

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19622] opened 2016-12-04 03:38 UTC
This screenshot is from a newly created police sniper's Remington 700++. I examined the item by going to the inventory and typing its hotkey. I've scrolled down all the way via"page down", but the last line, "improves accuracy greatly." is missing.
![noscroll](https://cloud.githubusercontent.com/assets/16765166/20863872/05647f08-b9a9-11e6-8fa8-55e42fde7ff2.png)

**Comment by ZenZen2** [comment] 2016-12-04 11:44
The Problem is also on monster description.

**Comment by NickGrease** [comment] 2016-12-04 17:01
Which font/size is that? Looks pretty good.

**Comment by sethsimon** [comment] 2016-12-06 03:14
@ZenZen2 It sounds like you should open a new issue for that. A screenshot and how you got there (`x` to examine things? `V` to list monsters?) would be great too.

@NickGrease It's from the virtual console in Debian. Among other things, my `/etc/default/console-setup` has
```
CHARMAP="UTF-8"
CODESET="guess"
FONTFACE="Fixed"
FONTSIZE="8x16"
```

**Comment by Qrox** [comment] 2017-05-05 01:22
This seems to be caused by the inconsistent width used for string folding on two consecutive calls. I am working on a fix for this.

**Closed** 2017-05-15 00:27 UTC
Labels: Bug, Information / Interface, Validated
