### ISSUE TITLE
[Bug] UPS modded electric forge doesn't work when it should

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#17068] opened 2016-06-06 06:44 UTC
Windows 0.C-14978-ge4b8e8f (tiles)
I have an electric forge with a UPS conversion mod applied and a character with 500 power and an Internal Unified Power System Bionic, which I have activated.
When I try to make anything that can use the electric forge, e.g. hard plating (100 forge charges), the forge is not given as an option to use.

**Comment by Coolthulhu** [comment] 2016-06-18 17:27
Sounds like an instance of the "seeing this is a bug" null item problem.
Needs a save or info on how to reproduce.

**Comment by hurston1** [comment] 2016-06-19 13:41
I upgraded to the latest experimental, still an issue I'm afraid.
Apply a 'UPS conversion mod' to an 'electric forge (500)', you get 'electric forge (UPS) (0)'
Make sure the character has the 'Internal Unified Power System' cbm and has enough power to cover the number of charges of what you are crafting.
Try to craft something that requires an electric forge, e.g. 'sledge hammer'
The 'electric forge' option in the crafting will be marked in red and the item cannot be crafted.

**Comment by Coolthulhu** [comment] 2016-06-19 13:51
Wait for it to charge, then try again.

**Comment by hurston1** [comment] 2016-06-19 14:40
I may be misunderstanding how this all works now. I know that originally, UPS modded items could be charged using a UPS-compatible charging station, but then those became unusable and UPS items would only work with the CBM. Have they now reverted again? If so, what does the CBM do, as it doesn't seem to charge items?

**Comment by Izicata** [comment] 2016-08-26 01:28
>I upgraded to the latest experimental, still an issue I'm afraid.
>Apply a 'UPS conversion mod' to an 'electric forge (500)', you get 'electric forge (UPS) (0)'
>Make sure the character has the 'Internal Unified Power System' cbm and has enough power to cover the number of charges of what you are crafting.

You have to carry the UPS-converted item in your inventory and wait for the charges to transfer from the UPS to the internal battery of the UPS-converted item. UPS-converted items charge at about 1 power per turn. If you try to craft immediately after applying the UPS conversion mod, it doesn't work because the battery isn't charged; that's what the (0) after the name means.

Unless UPS-converted items aren't rechargeable, and as far as I can tell they are rechargeable, I think this bug is a misunderstanding.

**Comment by Coolthulhu** [comment] 2016-10-06 13:44
Closing as old and unconfirmed.

**Closed by Coolthulhu** 2016-10-06 13:44 UTC
Labels: Bug, Confirmation Needed
