### ISSUE TITLE
Came across a couple small oversights that should fix easily.

### ISSUE THREAD

**Issue by Totentag** [CleverRaven/Cataclysm-DDA#20920] opened 2017-04-30 18:13 UTC
Gluten is fun, right? Well, two problems with gluten showed up in conversation recently and seem like they would be easy fixes for you magnificent wizards:

- [x] ~~The first is quite an easy one: oat seeds affect wheat allergies in-game, while IRL they do not. At least, IRL they do not contain gluten which is what it is typically assumed the "Wheat Allergy" trait is referring to.~~ Fixed in #22744

- [x] ~~Second is probably a bit less cut-and-dry, but @knocktwice mentioned in IRC that his Wheat Allergic character can eat cornbread with no issue, but upon making a meat sandwich out of cornbread, it magically contains wheat after the fact.~~ Duplicate of #21872

Finally, what I can only assume will be the easiest fix, there's a couple clothing items that seem to have swapped coverage percentages. 

- [ ] Namely, the Tank Top (60%) and Undershirt (40%). Given that the Tank Top specifically mentions being sleeveless, while the Undershirt does not, I would assume Undershirt is in reference to a T-shirt one might wear under more professional attire.

**Comment by GeoffWyche** [comment] 2017-04-30 18:19
@knocktwice is me.

I also noticed that oat seeds are marked as bad for wheat allergy.  To my knowledge, oats do not contain gluten.  However, during harvest/processing, they often become contaminated with wheat, meaning most oat-based products are unsafe for Celiacs, etc.

**Comment by pisskop** [comment] 2017-04-30 18:55
My presumption is that while most people find oatmeal rather than make it, you can make your own and be assured it wont set off any allergies.

**Comment by Rivet-the-Zombie** [comment] 2017-04-30 21:19
The root of your first issue is that we're using 'wheat' to cover all grains. We could make a generic 'grain' material for those sort of foods. The cornbread sandwich thing could be solved with a material inheritance system, but that's a far more complex fix.

The undershirt is probably supposed to be like one of those lightweight A frame shirts, rather than being an overshirt like the tank top.

**Comment by GeoffWyche** [comment] 2017-04-30 21:32
As an aside, my particular dietary problems include most grains, except rice.  So that's not a terrible assumption.  Even corn gives me problems.  Perhaps wheat (gluten) could be made into a type of contaminant that most people are immune to?

**Comment by GeoffWyche** [comment] 2017-05-01 02:24
Another, similar issue: made johnnycake from cornbread, but it "turned wheat" and I couldn't eat it.

**Comment by kevingranade** [comment] 2017-05-01 16:55
This is mostly an oversight when naming, the trait should be, "grain
intolerance", because we specifically did not want to get into all kinds of
details about, "you can actually eat gluten, but it has side effects", and
"This thing does have gluten but that other thing doesn't".

If someone wants to take responsibility for coding something that really
resembles gluten intolerance, they can, but it's a lot more complicated
than you'd think.

Also, please don't post issues that are, "a few issues", generally theyre
going to get closed without action.  Post multiple issues, each of which
has a descriptive title.

**Comment by Night-Pryanik** [comment] 2018-01-13 08:45
Converted to checklist.

**Comment by Leland** [comment] 2018-02-19 18:05
Second item ("Wheat Allergic character can eat cornbread with no issue, but upon making a meat sandwich out of cornbread, it magically contains wheat after the fact.") is a dupe of #21872

**Closed** 2018-02-20 03:35 UTC
Labels: Easy-fix, Items, JSON
