### ISSUE TITLE
Hope can add "dig" into player’s "construct terrain" panel

### ISSUE THREAD

**Issue by DIBAOS** [CleverRaven/Cataclysm-DDA#56135] opened 2022-03-16 14:59 UTC
### Is your feature request related to a problem? Please describe.

Every time I try to use my digging stick to make a shallow pit, I almost exhausted to death, because I must complete this work at one time or I will restart from zero again. So I hope add dig action to construct terrain(*) so I can suspend it and take a breath : )

### Solution you would like.

Add "dig" into player’s "construct terrain" panel

**Comment by Inglonias** [comment] 2022-03-18 13:27
Similar request for knocking down walls with a pickaxe or jackhammer.

**Comment by FayFlightee** [comment] 2022-05-02 13:27
Duplicate of #54511. But I'm working on it.

**Comment by NetSysFire** [comment] 2022-05-02 14:49
Duplicate of #54511.

**Closed by NetSysFire** 2022-05-02 14:49 UTC
Labels: Good First Issue, <Suggestion / Discussion>, Crafting / Construction / Recipes, Items / Item Actions / Item Qualities
