### ISSUE TITLE
Sudden slow down, delay or laggyness

### ISSUE THREAD

**Issue by jayWLKRRR** [CleverRaven/Cataclysm-DDA#26503] opened 2018-11-03 09:19 UTC
**Describe the bug**  
When I move (slightly fast tap) like 5-8 squares, I noticed some kind of delay or laggyness

**To Reproduce**  
I don't know how to reproduce this but this is how I did it

1. I install previous build 8075 (O.C 35562-gf1bad0e) or , and its not lagging or having some delay
2. To compare the two I install the latest build 8110 (0.C-33929-g268e51c)
3. Its seems the latest build are slower even in the loading screen, than the previous build.

**Expected behavior**  
I expected to run smoothly like the other previous builds

**Screenshots**  
None

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-33929-g268e51c
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Simplified Nutrition, Disable NPC Needs

**Additional context**  
It's just slow in general

PS: By the way i when I compare them they are all the same mods and settings.

**Comment by derektumolo** [comment] 2018-11-04 04:51
Not sure if mine is precisely related, but maybe? I've got a save with reproducible crash/hang (attached).
I noticed earlier that crafting was ponderously slow, in terms of speed of updates to the screen, like it was really thinking. 
Possibly related? Like something in the simulation is hogging?
[Gray Mountain - Copy - Copy - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2545577/Gray.Mountain.-.Copy.-.Copy.-.Copy.zip)

**Comment by hansonry** [comment] 2018-11-04 20:05
Not sure it's related but I see a slow down when I pull the latest. My issue seems to be related to the number of tiles lit. So not really a big deal at night or when in a forest. I have 1920x1080 screen and I almost use all of it. When I recently pulled down, I deleted my directory to get a clean checkout.  The issue also happens when I press x and look around. Seems to buffer commands. So sometimes I can't stop walking or driving.

To Reproduce:
Set Screen resolution close to 1920x1080 windowed. Go to a open area in daytime. Try to walk around, or hit x and look around.

**Comment by mechkit** [comment] 2018-12-05 14:37
I have same problem, it is unplayable outside the evac shelter, taking 3-5 seconds per move.

It has been like that for weeks when building the current version. Even on a new computer, fresh Ubuntu install, new world, new character. It is slow on a a i7 laptop that is a few years old, and an 8th gen i5 NUC. 

In the past I have occasionally had this lag when driving vehicles, but until recently I never noticed a delay in movement on foot.

Zooming in all the way helps, as well as being inside.

**Comment by SeelenJaegerTee** [comment] 2018-12-05 15:24
I also experience this Problem.
This seems to be tied to CPU load. When I move along a road exploring new territory I move about one tile per second, when I look at CPU load one CPU is always at 100% during this, when I stop moving CPU load goes back down. When I backtrack the way I came CPU load stays low and I experience no lag.
In the Screenshot when CPU4 load goes down and CPU2 load goes up I believe i let go of the movement key and pressed it again immedieatly after.

![screenshot](https://user-images.githubusercontent.com/39884350/49523438-14afe280-f8aa-11e8-9cbd-fee83d7c2f2f.png)

**Comment by mechkit** [comment] 2018-12-05 19:41
I just needed to RTFM. Based on this [Reddit post](https://www.reddit.com/r/cataclysmdda/comments/9vp8jl/movement_lag_on_latest_linux_versions/e9ezmq4), I used this make command and it fixed the problem.

    make -j4 CCACHE=1 NATIVE=linux64 RELEASE=1 TILES=1 LUA=1 SOUND=1 USE_HOME_DIR=1 LTO=1 ASTYLE=0

The key change being the "RELEASE=1".

**Comment by kevingranade** [comment] 2019-01-24 18:19
This is definitely related to map memory slowdown, and should have been addressed by #27457

**Closed by kevingranade** 2019-01-24 18:19 UTC
Labels: (S1 - Need confirmation), Code: Performance
