### ISSUE TITLE
Lifting quailty not working

### ISSUE THREAD

**Issue by Denniz-Dal** [CleverRaven/Cataclysm-DDA#25630] opened 2018-09-15 18:24 UTC
Trying to remove a storage battery from a bubble car. Shows lift of 1 required despite telescopic crane next to both me and vehicle. (toolbox in inventory if that matters)

1. Telescopic crane next to you and vehicle
2. examine vehicle
3. select and remove storage battery

Should see crane and remove battery

**Versions and configuration(please complete the following information):**
 -Windows 10 
 - Game Version 0.C-32110-g9b133d9 (tiles) 7917
 - Mods loaded: "dda","Medieval_Stuff","More_Survival_Tools","No_Fungi","No_Recreationals","StatsThroughSkillsFour", "blazemod", "Tanks", "alt_map_key", "deoxymod", "filthy_morale", "makeshift", "more_classes_scenarios", "no_npc_food", "no_olg_guns", "no_religious_Texts", "novitamins", "npc_traits", "safeautodoc"

**Comment by Zireael07** [comment] 2018-09-15 18:53
I believe the crane has to be on THE vehicle you're trying to use it on.

**Comment by Denniz-Dal** [comment] 2018-09-15 19:58
is that a recent change? I also tried an fork lift arm on the crane's vehicle. it didn't work, either.

**Comment by Denniz-Dal** [comment] 2018-09-15 20:05
Nope. I tried installing the telescopic crane on the bubble car.  No difference.

Note: the crane is on a foldable cart like I have been doing forever. (yes, it is unfolded. ;) )

**Comment by Regularitee** [comment] 2018-09-15 21:01
As I understand it, the current restrictions are:
1) It cannot be on the vehicle you're want to work on.
2) You (and possibly the vehicle?) must be within two tiles of said crane.

**Comment by Denniz-Dal** [comment] 2018-09-15 22:17
hmm, this is a little crazy. I went to a different vehicle to try. I found an electric car. I was able to remove the storage battery from the far side but not the near side. When I went to the other side I could then remove the other one. There seems to be an issue with being TOO CLOSE to the battery. I was able to get the one from the bubble car by doing it from the extreme end of the vehicle.

**Comment by mrkybe** [comment] 2018-09-16 00:56
@Denniz-Dal Might help in the mean time.
https://github.com/CleverRaven/Cataclysm-DDA/issues/25639#issuecomment-421661777

**Comment by hameleona** [comment] 2018-09-16 21:17
So your problem is probably the quaterpanell or something similar, since:  

> Cranes now provide LIFT to every point they can reach within 4 tiles, though are blocked by obstacles like boards or quarter panels.   

Don't know why I have to  remove the front of the car to remove the engine, but apparently - that's realistic.

**Comment by mrkybe** [comment] 2018-09-16 22:07
@hameleona Fair enough. https://github.com/CleverRaven/Cataclysm-DDA/pull/25662

**Comment by mlangsdorf** [comment] 2018-10-15 14:21
@Denniz-Dal is this issue resolved?

**Comment by rubenpd** [comment] 2018-10-15 18:03
the tile with the battery must be in unobstructed line of sight max 2 tiles far from the lifting tool

**Comment by Siersha** [comment] 2018-12-25 04:04
This issue should be closed as the issue has since been resolved/the issue doesn't exist since the required 2 tile distance for a lift to work properly is working as intended.

**Comment by Night-Pryanik** [comment] 2018-12-25 10:46
Closing. If this is still an issue, ping me.

**Closed by Night-Pryanik** 2018-12-25 10:46 UTC
Labels: <Bug>, Vehicles
