### ISSUE TITLE
Player character occasionally see through walls and reveal the stuff behind it

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68121] opened 2023-09-13 10:23 UTC
### Describe the bug

For some reason, player can seem to reveal stuff behind wall and get the map memory from it. It can happen by just walking beside the walls.

### Attach save file

[Bates-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12596220/Bates-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save
2. walk beside the wall for a bit
3. see that it reveals some part of the dirt wall beyond the concrete walls

### Expected behavior

Player not having a crappy version of clairvoyance by default.

### Screenshots

Before (world used here is the one i attached to this bug report
![Screenshot_2023-09-13_17-03-57](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/8c94a82a-dccd-4879-aaed-125872e2f6a6)

After
![Screenshot_2023-09-13_17-05-17](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/b89af7b1-a0bf-44f8-bdff-e721aeb44e12)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: f12487c [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Custom Frequencey For Portal Storms [custom_freq_ps],
    Custom Portal Storm Size [custom_size_ps]
]

### Additional context

Also in my current run, i noticed that the line of sight when autowalking looks quite weird. This could be related to this issue, though i cant replicate it in the new fresh world somehow.
![Screenshot_2023-09-13_17-20-34](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/9501588e-1a45-4f47-a3d0-46229441195d)

My current run
[Cowell-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12596314/Cowell-trimmed.tar.gz)

**Comment by KHeket** [comment] 2023-09-13 13:06
Its happend to me with 3d fild of view on, mostly I meet it at fema camps. At some distance you can see the corners inside the rooms

**Comment by casswedson** [comment] 2023-09-13 15:12
can /confirm on 
```
- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 398e915 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]
```
I can see a couple corners I should not be able to
![Screenshot from 2023-09-13 10-09-44](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/86c95178-cc95-4c49-ae96-961930d5cd51)

**Comment by Cormac1991** [comment] 2023-09-14 13:02
Same issue on Windows 11. tried all graphics options, nothing seems to fix it. everything is very jittery also, (graphics wise I mean)

**Comment by Brambor** [comment] 2023-09-14 13:26
Possibly related to @Rewryte PR #67997.

**Comment by Rewryte** [comment] 2023-09-14 19:09
Issue appears to be an outdated visibility cache, most likely caused by game attempting to `draw` before `map::update_visibility_cache` is called.  Fix incoming.

**Comment by Ivan-Shestakov** [comment] 2023-09-21 16:05
Happens to me too, on MacOS 13.5.2, built from latest master d7bcff2c2fcd22581273eb8b2f4e1caa61e60199
waiting for #68138 to be merged.

**Comment by huix11** [comment] 2023-09-22 03:01
good

**Closed** 2023-09-26 02:23 UTC
Labels: (S2 - Confirmed), Mechanics: Map Memory
