### ISSUE TITLE
Atomic Smartphone cannot be used as light.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#40936] opened 2020-05-29 02:02 UTC
# Describe the bug

Using an Atomic Smartphone's light app (Option 3 of "what to do with your atomic smartphone?") crashes the game.

# Steps To Reproduce

1. Make a player with the atomic Pitchman profession or spawn an atomic Smartphone on any other character.
2. use the smartphone and choose option 3 (turn on) as if you needed the light.
3. Crash Should happen now.

# Expected behavior

The light should show. 

# Screenshots

![Untitled](https://user-images.githubusercontent.com/50846380/83212420-9003f480-a12d-11ea-88cd-f13ea18ccc0f.jpg)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2587-gee563dc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I noticed #40888 recently and the other Atomic Items *DO* work correctly.

**Comment by hexagonrecursion** [comment] 2020-05-29 05:49
duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40906

**Closed** 2020-05-29 12:42 UTC
