### ISSUE TITLE
Reoccuring Crash related to vehicles and mapgen

### ISSUE THREAD

**Issue by CypherHyena** [CleverRaven/Cataclysm-DDA#35276] opened 2019-11-03 03:58 UTC
# Describe the bug
While exploring/moving around a part of the map, I have gotten the following crash twice. First the error message pops up, and if I try to ignore it, I get a SegFault Crash.

Error: DEBUG: Out of bounds add_vehicle t=none d=0 p=136,72,0
Function: vehicle* map::add_vehicle(const vproto_id&, const tripoint&, int, int, int, bool)
File: src/mapgen.cpp
Line: 7070

# Steps To Reproduce

1. Reload my Game
2. Move around in a certain part of my map. Move a bit West along the road from the save point.
[Crocuta.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3801221/Crocuta.zip)

# Expected behavior

Move without crashing...

# Screenshots
![image](https://user-images.githubusercontent.com/53030348/68080118-877b5380-fdc2-11e9-93e5-8696347c64c6.png)

# Versions and configuration

 - OS: Windows 10 64b
 - Game Version: 0.D Stable (From Launcher)
 - Graphics version: Tiles
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
DDA, Disable NPC Needs, Generic Guns, Makeshift Items Mod, Modular Turrets, Alternative Map Key, More Locations, Fuji's More Buildings, Vehicle Additions Pack, Disable Religious Texts, No Antique Firearms, Bionic Slots, Classes & Scenarios Mod, Stats Through Kills, Stats Through Skills, Mutant NPCs, Tanks and Other Vehicles, Filthy Clothing, No Fungal Monsters

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801219/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801220/crash.log)

**Comment by ZhilkinSerg** [comment] 2019-11-03 10:43
We do not backport bugfixes to old stable versions. Please try reproducing the issue on latest experimental version and report if there is still an issue.

**Comment by esotericist** [comment] 2019-11-03 10:54
To be clear, this is effectively a duplicate of #28156, and was fixed in #30362.

**Comment by BevapDin** [comment] 2019-12-28 12:07
Closing as duplicate.

**Closed by BevapDin** 2019-12-28 12:07 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Vehicles
