### ISSUE TITLE
Segfault/Crash in fullscreen on alt-tab

### ISSUE THREAD

**Issue by ContemporaryArtwork** [CleverRaven/Cataclysm-DDA#29670] opened 2019-04-17 17:18 UTC
**Describe the bug**  
Segfault/Crash on alt-tab while in fullscreen.

**To Reproduce**  
1. Start playing while in fullscreen mode.
2. Alt-tab

**Expected behavior**  
The game should allow the player to tab in and out without crashing. 

**Screenshots**  
http://prntscr.com/ndbawq - crash message
https://pastebin.com/zytUL7E0 - crash log

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1878-g5819d39
 - Graphics version: Tiles
 - Mods loaded: ["dda", "no_npc_food", "alt_map_key", "nw_pack", "More_Survival_Tools", "Medieval_Stuff", "makeshift", "national_guard_camp", "more_locations", "FujiStruct", "boats", "deoxymod", "blazemod", "Tanks", "sleepdeprivation", "StatsThroughSkills", "safeautodoc"]

**Additional context**  
I switched to windowed borderless and it works fine now.

**Comment by neitsa** [comment] 2019-04-20 06:34
Thanks for your bug report!

Duplicate of #24528.

**Closed** 2019-04-20 06:35 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
