### ISSUE TITLE
Road maps are not saving the location they were picked up

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#63361] opened 2023-01-31 00:13 UTC
### Describe the bug

If I pick up a road map and then move, the road map will change name to the nearest city.

### Steps to reproduce

1. Find or spawn a road map.
2. Go to another city
3. Observe that the road map changes its name to the new city you are closest to.

### Expected behavior

This is a regression - Maps are supposed to save the area they were picked up

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: daf8acf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Vault [No_Vault],
    No Fungal Growth [no_fungal_growth],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by Inglonias** [comment] 2023-01-31 00:18
I can also tell you that maps are behaving as though the location they are used is the location they were picked up.

**Comment by ZhilkinSerg** [comment] 2023-01-31 05:25
Duplicate of #61214

**Closed** 2023-01-31 06:15 UTC
Labels: (S3 - Duplicate), Items / Item Actions / Item Qualities
