### ISSUE TITLE
Crash when comparing items while abusing search filter

### ISSUE THREAD

**Issue by ArcanErasmus** [CleverRaven/Cataclysm-DDA#35809] opened 2019-12-01 23:51 UTC
# Describe the bug

This is a duplicate of #34046, but I couldn't figure out how to upload a save file in the comments. I'm hoping this provides some help for those trying to figure out the problem.

It seems that the crash happens when I compare items A and B, then unmark A, and try comparing items B and C. In what is likely related, if you try to compare items through searching, you will not compare what you are looking for. For example, search up one item, mark it, then search another item and mark that one. When you mark the second, it will compare the second item against something that appeared in the search list for the second item, rather than whatever you had selected first.

# Steps To Reproduce

1. Load the save file, press `iiiii` to ignore the 5 json errors.
2. Press `I` to compare
3. search `hood` and mark the hoodie (`0`)
4. search `la` and mark the headlamp (`u`)
5. press `esc` and search `hood` again, unmarking the hoodie (`0`)
6. search `la` again and mark the headlamp (`u`)
7. search `ja` and mark the bottle jack (`1`)
8. segfault!

# Expected behavior

The search window should at least not segfault, even if it is displaying the wrong items when double-searching for comparisons (though I suspect those issues are intertwined).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-9787-g847e182 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    CGPersonal [cgpersonal],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Roadheader and other mining vehicles [Heavy miners],
    Disable Religious Texts [no_religious_Texts],
    No Flaming Weapons [no_flaming_weapons],
    No Antique Firearms [no_olg_guns],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    sees-player icon, -attitude [sees_player_less_attitude],
    DinoMod [DinoMod],
    No Ants [No_Anthills]
]

# Additional context
[item compare segfault.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3908897/item.compare.segfault.zip)

**Comment by ArcanErasmus** [comment] 2019-12-01 23:52
As an additional note, when double-searching to compare items, the comparison will happen between the item selected second, and the item *in the same search result position* as the item selected first.

**Comment by ArcanErasmus** [comment] 2019-12-01 23:55
Search 1, note the position of `bottle jack` in the list:
![image](https://user-images.githubusercontent.com/8963206/69922624-e25ca500-146b-11ea-89d5-0ff621994b7e.png)

Search 2, note the position of `angular grinder` in the list:
![image](https://user-images.githubusercontent.com/8963206/69922634-07511800-146c-11ea-89ec-a5fd5dacd367.png)

Comparison result (`headlamp` was selected in the second search):
![image](https://user-images.githubusercontent.com/8963206/69922642-1637ca80-146c-11ea-9772-e86ddd370d88.png)

**Comment by ZhilkinSerg** [comment] 2019-12-02 07:54
Duplicate of #34046

> but I couldn't figure out how to upload a save file in the comments.

See message on bottom of comment window:

![image](https://user-images.githubusercontent.com/16213433/69939956-1e3a4d80-14f2-11ea-990f-56d2407c3bce.png)

**Closed** 2019-12-08 12:46 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Inventory / AIM / Zones, Items / Item Actions / Item Qualities
