### ISSUE TITLE
Crossing bridges kicks the junkie drivers out of the car

### ISSUE THREAD

**Issue by neutonm** [CleverRaven/Cataclysm-DDA#49773] opened 2021-07-09 09:53 UTC
# Describe the bug

Knocked out characters caused by drug withdrawal are being kicked out of vehicle when ascending/descending bridges. 

# Steps To Reproduce

1) Start as a tweaker (with amphetamine withdrawal)
2) Fool around for couple of hours, wait for withdrawal to start. The character will start feeling dizzy and will constantly stumble and fall over when moving.
3) Find a vehicle, drive to a bridge. 
4) Try to ascend/descend the bridge when the character is knocked out. The game will drop character on the ground. The car continues to drive :)

The bug occurs exactly when player collides with the "bridge ramp" tiles with the "knocked out" status effect. 

# Versions and configuration

Experimental (tiles), built on Linux Manjaro on 28 of June, 2021.

**Comment by pehamm** [comment] 2021-07-09 13:38
Can repliate, driving up or down a ramp while downed moves the vehicle but not the player up or down a z-level, thile the player moves continues to move on the same z-level for a tile until they are outside the vehicle. Movement outside the vehicle throws a `map::unboard_vehicle: vehicle not found` error, and entering the vehicle again throws `map::board_vehicle: passenger (playername) is already there`. It is also possible to fall down the "ledge" that consitutes the lower ramp part for the higher z-level.

Screenshot of standing of the ledge which should have moved the player while the car keeps moving for a map tile:
<img width="1440" alt="Screen Shot 2021-07-09 at 3 30 07 PM" src="https://user-images.githubusercontent.com/76401419/125085626-1463cd80-e0cb-11eb-8a31-0a04ab3f4f58.png">

**Comment by pehamm** [comment] 2021-07-09 13:51
ping @mlangsdorf

**Comment by Zeropol** [comment] 2021-07-11 15:51
Look similar to #48874 ?

**Comment by pehamm** [comment] 2021-07-11 16:01
Yep, same bug. The linked issue only talks about driving up bridges rather than down, but otherwise this seems to be a duplicate. Thanks for highlighting!

**Comment by wapcaplet** [comment] 2022-01-16 05:41
Closing as duplicate of #48874

**Closed by wapcaplet** 2022-01-16 05:41 UTC
Labels: <Bug>, (S3 - Duplicate), Z-levels, Vehicles, Mechanics: Effects / Skills / Stats
