### ISSUE TITLE
Hallucination Giant Web Spider leaves real web

### ISSUE THREAD

**Issue by RalphRoberts** [CleverRaven/Cataclysm-DDA#19246] opened 2016-11-11 21:16 UTC
Hallucinated Giant Web Spiders will leave actual webs, which stay after the hallucination is gone and can snare player.

![hallucinationbug](https://cloud.githubusercontent.com/assets/23408530/20230445/dbefe18e-a810-11e6-8c73-4791a2342d8a.PNG)

**Comment by Oskar636** [comment] 2016-11-11 23:44
I cannot get even the real giant web spiders to spawn web, what am I missing? ( Also noticed some weird sucidal tendentions when you spawn a lot of spiders and start a fire ).
Buld 5868 windows 64bit console

**Comment by Coolthulhu** [comment] 2016-11-11 23:49
Spiders don't spawn web in unmodded game. It's a duplicate of the issue where hallucinations emit fields. In unmodded game, the bug affects hallucinated smokers and bloated zombies.

**Comment by pisskop** [comment] 2016-11-12 01:56
Aye, its a bug of the code but spiders making webs is my mod

**Closed** 2016-11-15 19:21 UTC
Labels: Bug, Duplicate
