### ISSUE TITLE
problem crafting recipies that use water

### ISSUE THREAD

**Issue by yowshi** [CleverRaven/Cataclysm-DDA#18734] opened 2016-10-11 19:24 UTC
if you have normal (non boiled) in a container in your inventory or nearby and you are near a water source you wont be able to craft using uncleaned water.

the bug goes back as far as windows 0.C-5663

**Comment by illi-kun** [comment] 2016-10-11 19:42
I think this is a duplicate of  #18709.

**Closed** 2016-10-12 03:57 UTC
Labels: Bug, Duplicate
