### ISSUE TITLE
Crash in build 8195 activating cranial headlamp

### ISSUE THREAD

**Issue by mdlman** [CleverRaven/Cataclysm-DDA#26779] opened 2018-11-20 13:06 UTC
**Describe the bug**  
Reliable game crash activating cranial headlamp

**To Reproduce**  
1. Make a player with a cranial headlamp
2. Activate cranial headlamp
3. crash

**Expected behavior**  
The expected behavior is to be bathed in glorious illumination rather than being consigned to oblivion for attempting to chase away the darkness.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Win10 64-bit
 - Game Version: 0.C-34714-g771c9e4 
 - Graphics version: Tiles 
 - Mods loaded:  "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "makeshift", "More_Survival_Tools",  "alt_map_key",  "more_locations",  "Experimental-Z-Level",  Urban_Development", 
"boats",  "deoxymod",  "blazemod",  "Tanks",  "more_classes_scenarios",  "StatsThroughSkills"

**Additional context**  
Don't know if it is related to #26488 /  #26777 - I do have Z-levels on, which was a question in that issue.
[Meadow Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2599810/Meadow.Creek.zip)

**Comment by ZhilkinSerg** [comment] 2018-11-20 13:51
Yeah. It is the same issue.

**Comment by ZhilkinSerg** [comment] 2018-11-20 13:56
Actually you can activate any item which gives light to cause crash.

**Comment by ZhilkinSerg** [comment] 2018-11-21 16:30
Closing as duplicate of #26777.

**Closed by ZhilkinSerg** 2018-11-21 16:30 UTC
Labels: (P1 - Critical), (S3 - Duplicate), <Crash / Freeze>
