### ISSUE TITLE
Crash on wakeup

### ISSUE THREAD

**Issue by RoachLoach** [CleverRaven/Cataclysm-DDA#64518] opened 2023-03-24 13:27 UTC
### Describe the bug

For some reason my game keeps crashing on wakeup when I sleep in my chair on my vehicle, not particularly knowledgeable about programming so I can't interpret anything more than that.

### Attach save file

[Comfort Way-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11062499/Comfort.Way-trimmed.tar.gz)

### Steps to reproduce

1. Go to sleep without moving from the chair I'm in after loading the save
2. Crash on wakeup

### Expected behavior

Game not crashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 206b28e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
    Dark Days Ahead 
    Portal Storms Ignore NPCs 
    No Fungal Growth
    Bionic Professions 

### Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11062525/crash.log)
Edit: I think this might have something to do with another issue I saw was open after posting this, as i also have a line on the crash log about achievements, and it crashes right after I get a message for the "thank god its friday" achievement"

**Comment by irwiss** [comment] 2023-03-24 13:32
Seems another instance of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466 - there's workaround in a comment there so you can continue playing

**Comment by anothersimulacrum** [comment] 2023-03-25 01:17
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed by anothersimulacrum** 2023-03-25 01:17 UTC
Labels: (S4 - Invalid)
