### ISSUE TITLE
Game Crashes When Creating New Character

### ISSUE THREAD

**Issue by Yarkar-Edetar** [CleverRaven/Cataclysm-DDA#29568] opened 2019-04-14 14:20 UTC
Game version: 0-D.8783

Operating system: Windows Vista

Tiles or curses: Tiles

Mods active: Disable NPC Needs, Extended Realistic Guns, Garden Pots, Icecoon's Arsenal, Makeshift Items Mod, Medieval and Historical Content, Modular Turrets, Salvaged Robots, Alternative Map Key, Mutant NPCs, Boats, Folding Parts pack, (DP-RP) REMIX Indicators, Simplified Nutrition

### Expected behavior
Open the custom character creator

### Actual behavior
Loads everything up to the tileset, then gives the following error message:
"Assertion Failed! Program: [Hidden for privacy]\cataclysmdda-0.D-8783\cataclysm-tiles.exe File: src/cata-tiles.cpp, Line 385 Expression: texture_ptr"
-When I abort or retry-
"CRASH LOG FILE: config/crash.log
VERSION: 0.D-1789-gc0d27c5
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x4E5918[cataclysm-tiles.exe+0xE5918]
    @0x4E5CB9[cataclysm-tiles.exe+0xE5CB9]
    raise+0x191@0x764D384A[msvcrt.dll+0x6384A]"
When I use ignore, the original message just repeats.

### Steps to reproduce the behavior
Create world
Try to create custom character
Crash message

**Comment by ifreund** [comment] 2019-04-14 18:54
Do you use any third party tilesets?

**Comment by Yarkar-Edetar** [comment] 2019-04-14 19:05
Not to my knowledge, I downloaded it straight from the site today because I've forgotten to update since a few months ago. Unless third party tilesets come with it, like some of the mods, I don't have any.

**Comment by neitsa** [comment] 2019-05-06 02:04
The `debug.log` file would have been very important in this case, since a good deal of the necessary information would have been logged.

Are you still experiencing this crash? If yes, could you please upload you `debug.log` file? If not I guess you can just close the issue as we won't be able to reproduce it as it is deeply tied to the state of the current renderer when it happens. 

The assert is here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/b8cebc710e49ed37f36ec87a332ff819a03ca1d1/src/cata_tiles.cpp#L384-L392

The code for the `CreateTextureFromSurface` function:

https://github.com/CleverRaven/Cataclysm-DDA/blob/b8cebc710e49ed37f36ec87a332ff819a03ca1d1/src/sdl_wrappers.cpp#L54-L68

So either the `renderer` was null (probably not otherwise the whole game screen would have gone wrong), the `surface` was null or `SDL_CreateTextureFromSurface` failed ( but without the log we don't know what was the possible returned code from this function)...

**Comment by Yarkar-Edetar** [comment] 2019-05-06 22:41
I have updated since the opening of this issue, but am still having the same problem. I'm going to quickly recap what is happening to make sure that there is no lack of communication anywhere. When creating a new character, without any mods this time (Version 0.D Windows Tiles 8897), it will load everything fine up until the textures once again. The debug file should be attached to this reply.

Thanks for helping me out, even if nothing comes of this.

**Comment by Yarkar-Edetar** [comment] 2019-05-06 22:45
I have updated since the opening of this issue, but am still having the same problem. I'm going to quickly recap what is happening to make sure that there is no lack of communication anywhere. When creating a new character, without any mods this time (Version 0.D Windows Tiles 8897), it will load everything fine up until the textures once again. I cannot seem to get the debug file to actually show up when it supposedly uploads, so I'm just going to paste the document here.

Thanks for helping me out, even if nothing comes of this.

-----------------------------------------
18:25:45.057 : Starting log.
18:25:45.061 INFO : Cataclysm DDA version 0.D-2518-g65a0502
18:25:45.130 INFO : Number of render drivers on your system: 4
18:25:45.130 INFO : Render driver: 0/direct3d
18:25:45.130 INFO : Render driver: 1/direct3d11
18:25:45.130 INFO : Render driver: 2/opengl
18:25:45.130 INFO : Render driver: 3/software
18:25:45.132 INFO : Language is set to: 'en'
18:25:47.183 INFO : SDL version used during compile is 2.0.5
18:25:47.183 INFO : SDL version used during linking and in runtime is 2.0.5
18:25:47.415 INFO : Active renderer: 0/direct3d
18:25:47.973 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
18:25:48.922 WARNING : opendir [./mods/] failed with "No such file or directory".
18:29:36.093 WARNING : opendir [./save/Saint Clair Haven/mods] failed with "No such file or directory".
18:29:50.562 ERROR SDL : (error message will follow backtrace)
	(@0x4f62ba[cataclysm-tiles.exe+0xf62ba]), 
	(@0x4f6626[cataclysm-tiles.exe+0xf6626]), 
	(@0xa1788c[cataclysm-tiles.exe+0x61788c]), 
	(@0xa17d00[cataclysm-tiles.exe+0x617d00]), 
	(@0x477e8a[cataclysm-tiles.exe+0x77e8a]), 
	(@0x478298[cataclysm-tiles.exe+0x78298]), 
	(@0x47e99a[cataclysm-tiles.exe+0x7e99a]), 
	(@0x486735[cataclysm-tiles.exe+0x86735]), 
	(@0x487fa2[cataclysm-tiles.exe+0x87fa2]), 
	(@0x4887e6[cataclysm-tiles.exe+0x887e6]), 
	(@0xa1d77d[cataclysm-tiles.exe+0x61d77d]), 
	(IMG_LoadWEBP_RW+0x30d773@0xf532c3[cataclysm-tiles.exe+0xb532c3]), 
	(@0x6074c7[cataclysm-tiles.exe+0x2074c7]), 
	(@0x58ef48[cataclysm-tiles.exe+0x18ef48]), 
	(@0x5b93bd[cataclysm-tiles.exe+0x1b93bd]), 
	(@0x706e29[cataclysm-tiles.exe+0x306e29]), 
	(@0x70abc9[cataclysm-tiles.exe+0x30abc9]), 
	(IMG_LoadWEBP_RW+0x4a5e4a@0x10eb99a[cataclysm-tiles.exe+0xceb99a]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x12@0x7779d4d1[kernel32.dll+0x4d4d1]), 
	(RtlInitializeExceptionChain+0x63@0x77d31593[ntdll.dll+0x41593]), 
	(RtlInitializeExceptionChain+0x36@0x77d31566[ntdll.dll+0x41566]), 
Backtrace emission took 0 seconds.

**Comment by sourcehobo** [comment] 2019-07-12 23:52
I do not know if it is the same problem, but I suspect that its very closely related since it crashes at the same time, pops up the same error dialogue, and has a similar looking backtrace.

For me it happened with an existing world when creating a new character (not custom, just the last character). It stopped occurring after I cleared the world. The first time it occurred it changed my display resolution to 800x600.

This is a clean install from the website with no mods beyond what is installed and loaded by default.

(OS: windows 10)

```
18:07:23.142 : Starting log.
18:07:23.142 INFO : Cataclysm DDA version 0.D
18:07:23.190 INFO : Number of render drivers on your system: 4
18:07:23.190 INFO : Render driver: 0/direct3d
18:07:23.190 INFO : Render driver: 1/direct3d11
18:07:23.190 INFO : Render driver: 2/opengl
18:07:23.190 INFO : Render driver: 3/software
18:07:23.199 INFO : Language is set to: 'en'
18:07:24.552 INFO : SDL version used during compile is 2.0.5
18:07:24.552 INFO : SDL version used during linking and in runtime is 2.0.5
18:07:24.791 INFO : Active renderer: 0/direct3d
18:07:25.320 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
18:07:25.745 WARNING : opendir [./mods/] failed with "No such file or directory".
18:09:35.223 WARNING : opendir [./save/Saint Andrews/mods] failed with "No such file or directory".
18:09:45.938 ERROR SDL : (error message will follow backtrace)
	(@0x5eaebe[cataclysm-tiles.exe+0x1eaebe]), 
	(@0x5eb49a[cataclysm-tiles.exe+0x1eb49a]), 
	(@0xcb9811[cataclysm-tiles.exe+0x8b9811]), 
	(@0xcb9b3e[cataclysm-tiles.exe+0x8b9b3e]), 
	(@0x4b2524[cataclysm-tiles.exe+0xb2524]), 
	(@0x4b2e26[cataclysm-tiles.exe+0xb2e26]), 
	(@0x4b4390[cataclysm-tiles.exe+0xb4390]), 
	(@0x4c0c69[cataclysm-tiles.exe+0xc0c69]), 
	(@0x4c1a3f[cataclysm-tiles.exe+0xc1a3f]), 
	(@0x4c2e9a[cataclysm-tiles.exe+0xc2e9a]), 
	(@0xcc37aa[cataclysm-tiles.exe+0x8c37aa]), 
	(@0x75c0e6[cataclysm-tiles.exe+0x35c0e6]), 
	(@0x6d0c06[cataclysm-tiles.exe+0x2d0c06]), 
	(@0x6fbce4[cataclysm-tiles.exe+0x2fbce4]), 
	(@0x8ab239[cataclysm-tiles.exe+0x4ab239]), 
	(@0x8adad0[cataclysm-tiles.exe+0x4adad0]), 
	(IMG_LoadWEBP_RW+0x4ea480@0x148a910[cataclysm-tiles.exe+0x108a910]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ffdddf77bd4[KERNEL32.DLL+0x17bd4]), 
	(RtlUserThreadStart+0x21@0x7ffdde7cce71[ntdll.dll+0x6ce71]), 
Backtrace emission took 0 seconds.
```

**Comment by DaviBones** [comment] 2019-08-23 21:48
Had this exact issue when installing on someone else's Windows 7 x64 laptop. Switching from Direct3D to OpenGL fixed it.

**Comment by LyleSY** [comment] 2020-04-14 15:54
Can't replicate on Linux or Mac in a current experimental. This may be a Vista-specific issue. Vista support was ended in 2017.

**Comment by Yarkar-Edetar** [comment] 2020-04-14 16:07
Yeah, I kinda figured at this point. Everything has kind of been chugging to Vista's endlife. First I couldn't run the launcher so I had to update manually with the zip files, and now I guess it's broken entirely on my PC. I have switched to mobile and it's worked fine so far. Thanks so much for trying to help though!

**Comment by ZhilkinSerg** [comment] 2020-08-20 15:34
Closing it - it is not really wise for us to try to support Vista.

**Closed by ZhilkinSerg** 2020-08-20 15:34 UTC
Labels: <Crash / Freeze>, Character / World Generation, OS: Windows, SDL: Tiles / Sound
