### ISSUE TITLE
Stats Through Skills inflicts damage to Head, Torso and Arms

### ISSUE THREAD

**Issue by sverinn** [CleverRaven/Cataclysm-DDA#28690] opened 2019-03-13 22:14 UTC
Game version:
0.D-484-g7fcdb58 (build 8609)

Operating system:
Windows 10

Tiles or curses:
Tiles

Mods active:
StatsThroughSkills (assumed)

### Expected behavior
No HP Damage

### Actual behavior
When Strength is low on start (tested 8) Head, Torso, R. Arm and L. Arm get 1 damage every turn. Raising Strength to 10 or greater (tested via debug menu) stops the damage.

### Steps to reproduce the behavior
Create a character with 8 strength.

**Comment by Tharn** [comment] 2019-03-13 22:14
Duplicate of #28680

**Closed** 2019-03-13 22:16 UTC
Labels: (S3 - Duplicate)
