### ISSUE TITLE
Power Armor and wearing other gear are inconsistent

### ISSUE THREAD

**Issue by ZombiesAreUs** [CleverRaven/Cataclysm-DDA#18052] opened 2016-08-16 19:00 UTC
If you're not wearing a power armor helmet you can wear anything else together with your power armor.

Steps to reproduce: spawn a power armor, and any other article of clothing, like a duffel bag or heavy survivor suit. Put the power armor on first, then the suit, works fine. Take off the suit, then put on power armor helmet on. Can't put on anything new anymore (although any worn items will remain).

**Comment by l29ah** [comment] 2016-11-02 16:46
I wonder why am i not supposed to wear a backpack with a power armor.

**Comment by illi-kun** [comment] 2016-11-02 17:15
I guess this is a duplicate of #8473.

**Closed** 2016-11-04 08:53 UTC
Labels: Balance, Duplicate
