### ISSUE TITLE
Advanced inventory gets volume sum wrong with vehicle cargo.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17935] opened 2016-08-05 14:40 UTC
1. spawn shopping cart
2. spawn 1 rock
3. spawn 1 sharp rock
4. put the rocks in the shopping cart
5. stand south of the shopping cart
6. open the advanced inventory
7. put left pane on 8 (Shopping cart).
8. put right pane on 8 (North, grass).
   ![2016-08-05-163804_731x106_scrot](https://cloud.githubusercontent.com/assets/11578180/17440013/06dc4974-5b2b-11e6-89b5-1b349f717930.png)
9. move back to left pane, suddenly volume is wrongly 0 instead of the correct 2 it was at step 8.
   ![2016-08-05-163813_725x113_scrot](https://cloud.githubusercontent.com/assets/11578180/17440021/11c553c6-5b2b-11e6-9e56-cde76363b374.png)

**Comment by mugling** [comment] 2016-09-21 15:46
Code handling AIM was recently updated. Needs confirmation bug still exists

**Comment by sethsimon** [comment] 2016-10-28 00:00
> Code handling AIM was recently updated. Needs confirmation bug still exists

This is still an issue.

**Comment by KurzedMetal** [comment] 2020-03-24 11:57
I was about to open a bug about this, but saw this.

It's still an issue in experimental build #10440, I noticed that pressing Tab to switch sides is the one doing the wrong update to weight / volume.

If I do a "Sort by...", even if I don't change sorting, it updates weight and volume correctly, and if I Tab again, it updates to Zero.

**Comment by wapcaplet** [comment] 2021-02-14 03:18
Cannot reproduce in 0.E-9603-g42468f6cab following the OP steps. Moving items to and from the vehicle, switching panes, and moving items to and from the ground under the vehicle all reflect correct volume totals for both AIM panes:

![image](https://user-images.githubusercontent.com/238395/107867475-619f8400-6e38-11eb-86ca-4e420c420a3a.png)

**Closed by wapcaplet** 2021-02-14 03:18 UTC
Labels: (S2 - Confirmed), <Bug>, Info / User Interface, Vehicles
