### ISSUE TITLE
Wacko Fire Time

### ISSUE THREAD

**Issue by DarianLStephens** [CleverRaven/Cataclysm-DDA#31212] opened 2019-06-07 15:23 UTC
# Describe the bug

I lit a fire before going to sleep in a tent, and even though it said ~20 minutes left, it was still burning when I woke up.
I went to examine it, and the numbers were going absolutely mental.

# Steps To Reproduce

I don't know if this is easily reproducible or a one-time thing, but I:
Lit the fire using pieces from a smashed camp table.
Used it to cook food, make some bread, and boil a lot of water over several trips.
Left the fire going as I slept.

# Expected behavior

I thought the fire would be out before I woke up, not burning... forever? I don't know what implications this has.

# Screenshots

Gif of the crazy fire that should have gone out last night:
https://imgur.com/a/uPzAr4t

# Versions and configuration
- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.D-4030-gedfd28b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Bionic Slots [cbm_slots],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

I just figured out that I can make stone pots to solve my dehydration? I don't know. I'd love to be able to just warm things over a fire without anything to hold it. Not boil, just unfreeze.

**Comment by Feuerhai** [comment] 2019-06-09 16:17
Duplicate of #31068

**Closed** 2019-06-09 16:40 UTC
Labels: Fields / Furniture / Terrain / Traps, Time / Turns / Duration / Date
