### ISSUE TITLE
crash when switching to RetroDays20px tileset

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19661] opened 2016-12-06 22:22 UTC
Config change seems to work and the tileset loads when you actually load a character, but the game barfs when saving the initial change.

![image](https://cloud.githubusercontent.com/assets/12039454/20946369/46ad3a50-bbbf-11e6-867d-7d78bb5080a4.png)

**Comment by Xpyder** [comment] 2016-12-06 22:26
using build 6021 windows tile
0.c-20142-geb1e883

**Comment by Xpyder** [comment] 2016-12-07 19:21
To be clear, this isn't gamebreaking at the moment, the change is a one time thing and it saves fine.  But it's likely a symptom of an underlying issue

**Comment by codemime** [comment] 2016-12-07 19:33
> But it's likely a symptom of an underlying issue

The issue is pretty clear to me: `cata_tiles::do_tile_loading_report()` calls `item_controller->all()` which isn't yet finalized at that moment. The underlying issue is that we couldn't tell whether the core data is loaded, or it's not. Now we can.

We arguably should unload all data when closing the world and returning to the main menu, but we can really benefit from loading immutable core data only one. This way reloading could be really quick.

**Closed** 2017-01-02 06:43 UTC
Labels: Crash
