### ISSUE TITLE
Segfault when looking at shoulder strap recipe

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#56440] opened 2022-03-28 20:08 UTC
### Describe the bug

Game crashes when attempting to select shoulder strap recipe, either by scrolling through the mods list or by searching specifically for shoulder strap.

### Steps to reproduce

Unzip folder, create new world with no mods (not even the auto-selected ones), start a character with at least Fab 1, check recipe list.

### Expected behavior

No segfault.

### Screenshots

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: e0dc297
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff76c1c77f0[cataclysm-tiles.exe+0x1f77f0]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x1401f77f0),
    (libbacktrace: 0x1401f77f0    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff76c1b0e01[cataclysm-tiles.exe+0x1e0e01]), 
    (libbacktrace: log_crash+0x1d2@0x1401e0e01),
    (libbacktrace: 0x1401e0e01    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff76c1b102f[cataclysm-tiles.exe+0x1e102f]), 
    (libbacktrace: signal_handler+0x52@0x1401e102f),
    (libbacktrace: 0x1401e102f    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff76ca7cd42[cataclysm-tiles.exe+0xaacd42]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140aacd42),
    (libbacktrace: 0x140aacd42    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffbba637ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffbbaeb20cf[ntdll.dll+0xa20cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffbbae61454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffbbaeb0bfe[ntdll.dll+0xa0bfe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff76c3a84d7[cataclysm-tiles.exe+0x3d84d7]), 
    (libbacktrace: item::armor_info(std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int, bool) const+0x1487@0x1403d84d7),
    (libbacktrace: 0x1403d84d7    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff76c3c635f[cataclysm-tiles.exe+0x3f635f]), 
    (libbacktrace: item::info[abi:cxx11](std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int) const+0x4b9@0x1403f635f),
    (libbacktrace: 0x1403f635f    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff76c3c669b[cataclysm-tiles.exe+0x3f669b]), 
    (libbacktrace: item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&, int) const+0x31@0x1403f669b),
    (libbacktrace: 0x1403f669b    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff76c1a99d8[cataclysm-tiles.exe+0x1d99d8]), 
    (libbacktrace: item_info_data_from_recipe(item_info_cache&, int*, int*, recipe const*, int, int&)+0xda@0x1401d99d8),
    (libbacktrace: 0x1401d99d8    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff76c1ab946[cataclysm-tiles.exe+0x1db946]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)::{lambda(ui_adaptor const&)#3}::operator()(ui_adaptor const&) const [clone .constprop.0]+0x1e6e@0x1401db946),
    (libbacktrace: 0x1401db946    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff76c914d79[cataclysm-tiles.exe+0x944d79]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x16d@0x140944d79),
    (libbacktrace: 0x140944d79    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff76c1adb9d[cataclysm-tiles.exe+0x1ddb9d]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)+0x2135@0x1401ddb9d),
    (libbacktrace: 0x1401ddb9d    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff76c194fda[cataclysm-tiles.exe+0x1c4fda]), 
    (libbacktrace: Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)+0x2e@0x1401c4fda),
    (libbacktrace: 0x1401c4fda    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff76c308efd[cataclysm-tiles.exe+0x338efd]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x2e45@0x140338efd),
    (libbacktrace: 0x140338efd    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff76c30c8a6[cataclysm-tiles.exe+0x33c8a6]), 
    (libbacktrace: game::handle_action()+0xafa@0x14033c8a6),
    (libbacktrace: 0x14033c8a6    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff76c20e6b0[cataclysm-tiles.exe+0x23e6b0]), 
    (libbacktrace: do_turn()+0x546@0x14023e6b0),
    (libbacktrace: 0x14023e6b0    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff76d443fe6[cataclysm-tiles.exe+0x1473fe6]), 
    (libbacktrace: main+0x18f6@0x141473fe6),
    (libbacktrace: 0x141473fe6    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff76bfd13c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
  #21
    (dbghelp: @0x7ff76bfd14d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
  #22
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffbb8e87034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #23
    (dbghelp: RtlUserThreadStart+0x21@0x7ffbbae62651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### Versions and configuration

OS: Windows 10
Version: cdda-windows-tiles-x64-2022-03-28-0537
Language: English
Mods: absolutely none

**Comment by NetSysFire** [comment] 2022-03-28 20:18
Duplicate of #56382

**Closed by NetSysFire** 2022-03-28 20:18 UTC
