### ISSUE TITLE
Debug message: add_zombie: there's already a monster

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#22029] opened 2017-09-30 00:43 UTC
Game version: a866f7a6d5

Tiles or curses: tiles

Mods active:[
  "dda",
  "More_Survival_Tools",
  "realguns",
  "Urban_Development",
  "more_locations",
  "boats",
  "filthy_morale",
  "no_npc_food"
]

### Expected behavior

Expected uninterrupted gameplay

### Actual behavior

![lol2](https://user-images.githubusercontent.com/646121/31040550-6e5246d2-a53d-11e7-9fdd-a577c8b5510d.png)

### Steps to reproduce the behavior
1. Load save game [Gore.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1345961/Gore.zip)
2. Run south to gunstore

---
```
Thread 1 "cataclysm-tiles" received signal SIGINT, Interrupt.
0x00007ffff768165d in nanosleep () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff768165d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007ffff794cfa5 in SDL_Delay_REAL () from /usr/lib64/libSDL2-2.0.so.0
#2  0x00000000011eea6c in input_manager::get_input_event (this=0x1812780 <inp_mngr>, win=<optimized out>, win@entry=0x0) at src/sdltiles.cpp:1649
#3  0x000000000072eb00 in input_manager::get_input_event (this=<optimized out>) at src/input.cpp:1117
#4  0x0000000000fd6c10 in realDebugmsg (filename=<optimized out>, filename@entry=0x13840ca "src/creature_tracker.cpp", line=<optimized out>, line@entry=0x13bcd8f "63", 
    funcname=<optimized out>, funcname@entry=0x13842e0 <Creature_tracker::add(monster&)::__PRETTY_FUNCTION__> "bool Creature_tracker::add(monster&)", 
    mes=mes@entry=0x1384098 "add_zombie: there's already a monster at %d,%d,%d") at src/debug.cpp:93
#5  0x0000000000d9887e in Creature_tracker::add (this=<optimized out>, critter=...) at src/creature_tracker.cpp:63
#6  0x0000000000b29308 in game::add_zombie (this=0xcfe5140, critter=..., pin_upgrade=pin_upgrade@entry=false) at src/game.cpp:6620
#7  0x0000000000b2935c in game::add_zombie (this=<optimized out>, critter=...) at src/game.cpp:6603
#8  0x0000000000cd389b in overmapbuffer::<lambda(std::pair<const tripoint, monster>&)>::operator() (monster_entry=..., __closure=0x7fffffff9d50) at src/overmapbuffer.cpp:968
#9  std::for_each<__gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<const tripoint, monster>, false, true>, std::__debug::unordered_multimap<tripoint, monster> >, overmapbuffer::spawn_monster(int, int, int)::<lambda(std::pair<const tripoint, monster>&)> >(__gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<tripoint const, monster>, false, true>, std::__debug::unordered_multimap<tripoint, monster, std::hash<tripoint>, std::equal_to<tripoint>, std::allocator<std::pair<tripoint const, monster> > > >, __gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<tripoint const, monster>, false, true>, std::__debug::unordered_multimap<tripoint, monster, std::hash<tripoint>, std::equal_to<tripoint>, std::allocator<std::pair<tripoint const, monster> > > >, overmapbuffer::<lambda(std::pair<const tripoint, monster>&)>) (__first=..., __last=..., __f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/stl_algo.h:3767
#10 0x0000000000cdb6b3 in overmapbuffer::spawn_monster (this=<optimized out>, x=343, y=198, z=0) at src/overmapbuffer.cpp:969
#11 0x00000000008f32eb in map::spawn_monsters_submap (this=this@entry=0xcfe55c0, gp=..., ignore_sight=ignore_sight@entry=false) at src/map.cpp:7330
#12 0x00000000008f343b in map::spawn_monsters (this=0xcfe55c0, ignore_sight=ignore_sight@entry=false) at src/map.cpp:7344
#13 0x0000000000b5039a in game::update_map (this=this@entry=0xcfe5140, x=@0x7fffffffaac0: 71, y=@0x7fffffffaac4: 70) at src/game.cpp:12875
#14 0x0000000000b504e7 in game::update_map (this=this@entry=0xcfe5140, p=...) at src/game.cpp:12820
#15 0x0000000000b790bf in game::place_player (this=this@entry=0xcfe5140, dest_loc=...) at src/game.cpp:11710
#16 0x0000000000b99176 in game::walk_move (this=this@entry=0xcfe5140, dest_loc=...) at src/game.cpp:11625
#17 0x0000000000b9a2f9 in game::plmove (this=this@entry=0xcfe5140, dx=dx@entry=-1, dy=dy@entry=0, dz=dz@entry=0) at src/game.cpp:11376
#18 0x0000000000b9c4ef in game::handle_action (this=this@entry=0xcfe5140) at src/game.cpp:2763
#19 0x0000000000ba0889 in game::do_turn (this=0xcfe5140) at src/game.cpp:1465
#20 0x00000000009d11f0 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:486
```

**Comment by AMurkin** [comment] 2017-09-30 13:00
Duplicate of #21130.

**Closed** 2017-09-30 14:24 UTC
Labels: Duplicate
