### ISSUE TITLE
cant order new NPCs to go away

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20778] opened 2017-04-02 17:14 UTC
In latest exp i cant "ask" npc's to go away if they have a quest for me. 
They come, take my items.. and i have to kill them without warnings. 
End then i get "killed innocent" penalty for killing thieves

**Comment by Taberone** [comment] 2017-04-03 01:04
It's always been like this, with "Questgiver" NPCs having no options for telling them to shove off and quit whining about their zombie mothers, and even being immune to mugging via dialogue. #19318 is similar to this.

**Comment by ZenZen2** [comment] 2017-05-05 16:43
duplicate of #19318

**Closed by ZenZen2** 2017-05-05 16:43 UTC
Labels: NPC
