### ISSUE TITLE
Crash when saving a game

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33085] opened 2019-08-09 18:42 UTC
```
VERSION: 0.D-6341-g96cbea7e87-dirty
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55fa7cf7128a]
	cataclysm(+0x6c6532) [0x55fa7cf5a532]
	cataclysm(+0x6c6998) [0x55fa7cf5a998]
	/lib64/libc.so.6(+0x396b0) [0x7f8b208196b0]
	cataclysm(_ZNK6player5getIDEv+0) [0x55fa7d7b7fa0]
	cataclysm(_ZNK7monster5storeER7JsonOut+0xb3c) [0x55fa7d8e7cbc]
	cataclysm(_ZNK7monster9serializeER7JsonOut+0x21) [0x55fa7d8e7f91]
	cataclysm(_ZN8mongroup2ioIN2io23JsonObjectOutputArchiveEEEvRT_+0x40b) [0x55fa7d8d7ebb]
	cataclysm(_ZNK8mongroup9serializeER7JsonOut+0x31) [0x55fa7d8c6e61]
	cataclysm(_ZNK7overmap19save_monster_groupsER7JsonOut+0x76e) [0x55fa7d8d05ae]
	cataclysm(_ZNK7overmap9serializeERSo+0x299) [0x55fa7d8d09d9]
	cataclysm(_Z13write_to_fileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRSoEE+0x42) [0x55fa7ce6d492]
	cataclysm(_ZNK7overmap4saveEv+0xbb) [0x55fa7d6fdf4b]
	cataclysm(_ZN13overmapbuffer4saveEv+0x19) [0x55fa7d76b259]
	cataclysm(_ZN4game9save_mapsEv+0x2b) [0x55fa7d06be5b]
	cataclysm(_ZN4game4saveEv+0x78) [0x55fa7d06bf18]
	cataclysm(+0x7d8137) [0x55fa7d06c137]
	cataclysm(+0x86979c) [0x55fa7d0fd79c]
	cataclysm(_ZN4game13handle_actionEv+0x3c97) [0x55fa7d101877]
	cataclysm(_ZN4game7do_turnEv+0x5b1) [0x55fa7d0ac371]

	Attempting to repeat stack trace using debug symbols...
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(addr2line) failed
```

**Comment by AMurkin** [comment] 2019-08-09 19:03
Duplicate of #33051.

**Closed** 2019-08-09 19:05 UTC
