### ISSUE TITLE
Error when trying to pour liquid inside a vehicle tank that has the same liquid type but frozen

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#63536] opened 2023-02-11 09:48 UTC
### Describe the bug

If unloading a liquid that has the same type as a liquid in a vehicle tank, the game allows you to choose said tank as the destination even if the liquid in that vehicle tank is frozen. This produces an error.

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10713083/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

If reproducing it on the attached save:
1. Obtain any liquid that's in the vehicle's tanks but frozen (glycerol is a great example)
2. Unload the item with glycerol you have in your inventory and select the vehicle tank with frozen glycerol as the destination
3. Behold the error screen

### Expected behavior

Probably not even being allowed to choose that tank as a destination.

### Screenshots

![obraz](https://user-images.githubusercontent.com/68503002/218251475-00c59578-1c6b-44f9-b3fa-cb8c471d5621.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 2ee4928 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mqrause** [comment] 2023-02-11 11:50
Sounds like a duplicate of #63237, but I didn't confirm it.

**Comment by Karol1223** [comment] 2023-02-11 11:55
> Sounds like a duplicate of #63237, but I didn't confirm it.

It's not. This one is about vehicle tanks as opposed to item tanks.

It's also a given to not work since the vehicle tank in question has frozen contents - you can't add more if the contents are frozen

The only issue is that the option to try to add there is still possible and results in an error

**Comment by mqrause** [comment] 2023-02-11 12:03
I'll have to check it later, but I suspect the underlying issue is also that flag that prevents stacking here.

**Comment by Karol1223** [comment] 2023-02-11 12:12
> I'll have to check it later, but I suspect the underlying issue is also that flag that prevents stacking here.

Checking won't hurt but I do believe it's the fact that one is frozen rather than the flag. I'll see when the contents of the tank thaw out if they can be mixed.

**Comment by mqrause** [comment] 2023-02-11 23:05
You're right, it's in fact an issue with the liquid in the tank being frozen. (Although you still might run into the other bug once it thaws, but probably not, since it's not on the map.)
Putting a frozen liquid into a container with a non-frozen liquid should work (`can_combine` explicitly allows mixing items with different temperatures), but the other way around isn't allowed. I assume that's just an oversight from #60325.

https://github.com/CleverRaven/Cataclysm-DDA/blob/7216560e9acd3cbe7d2976a3489965fb3f481ada/src/item_pocket.cpp#L1393-L1405

**Closed** 2023-02-13 01:13 UTC
Labels: (S1 - Need confirmation)
