### ISSUE TITLE
"this is full of dirt after being on the ground" when 'applying' bottled antisceptic / saline solution

### ISSUE THREAD

**Issue by ProfessorRich** [CleverRaven/Cataclysm-DDA#46480] opened 2021-01-02 09:24 UTC
Find bottled antisceptic or saline.

Press 'a'. Try to apply. Message = "this is full of dirt after being on the ground"

Instead, press E to 'eat'... choose antisceptic... now the game lets you apply it as normal!

**Expected behaviour**

1. Bottled liquids shouldn't be dirty.
2. If they ARE dirty, presumeably it shouldn't make a difference if you try to 'a' them or 'E' them. 

**Version**
0.E-8640-gf8cbc0c

**Comment by PaulBlay** [comment] 2021-01-02 09:59
Just checked and can confirm this bug. It must be a new one. (Guess I won't be updating till it's fixed)

- OS: Windows x64 8.1
- Game Version: 0.E-8640-gf8cbc0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by BrettDong** [comment] 2021-01-02 11:30
Duplicate of #46468.

**Closed by BrettDong** 2021-01-02 11:30 UTC
