### ISSUE TITLE
Crash when butchering Razorclaw

### ISSUE THREAD

**Issue by Warlander** [CleverRaven/Cataclysm-DDA#28715] opened 2019-03-14 21:28 UTC
**Describe the bug**  
When you try to buther the razorclaw, game crashes with arithmetic error.

**To Reproduce**  
1. Spawn razorclaw, any weapon to kill him and buthering tool (in my case I tried with a pocket knife)
2. Kill razorclaw
2. Try to buther razorclaw
3. Game crashes

**Expected behavior**  
Razorclaw is buthered, no crash occurs.

**Versions and configuration:**
 - OS: Windows 7
 - Game Version: 0.D-498-g5b6a055
 - Graphics version: Tiles
 - Mods loaded: dda, boats, more survival tools, folding parts pack, vehicle extensions, PK rebalancing

**Comment by KorGgenT** [comment] 2019-03-14 21:48
a save file would make this easier to debug.

**Comment by ZhilkinSerg** [comment] 2019-03-15 06:51
Deathclaw is monster from some mod, not from mainline, so you better address the issue for mod author. It is probably missing some nodes in monster definition in json.

**Comment by Warlander** [comment] 2019-03-15 09:17
I'm sorry, I meant Razorclaw ( https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Razorclaw ) and not deathclaw. :)

**Comment by ZhilkinSerg** [comment] 2019-03-15 09:56
Thanks, I see, but I guess it is still mod error as I cannot reproduce crash in a no-mods game. Guess it is a PKs fault - it changes this monster (see https://github.com/pisskop/PKs_Rebalancing/blob/3c28b017202df1e52cba6afe41a7b66a9ca21316/monsters/mutant.json#L3), so you can try edit modded version with original definition:

```JSON
  {
    "id": "mon_razorclaw",
    "type": "MONSTER",
    "name": "razorclaw",
    "description": "A man-sized crustacean clad in an iron-like chitin, capable of emitting the most horrible of shrieks.  Often spotted near shipwrecks or other dark damp places, which it uses as nesting grounds.",
    "default_faction": "razorclaw",
    "species": [ "MUTANT" ],
    "volume": "62500 ml",
    "weight": 81500,
    "hp": 80,
    "speed": 85,
    "material": [ "flesh" ],
    "symbol": "Y",
    "color": "magenta",
    "aggression": 4,
    "morale": 100,
    "melee_skill": 6,
    "melee_dice": 4,
    "melee_dice_sides": 6,
    "melee_cut": 7,
    "dodge": 2,
    "armor_bash": 10,
    "armor_cut": 18,
    "vision_day": 30,
    "vision_night": 15,
    "harvest": "shellfish",
    "path_settings": { "max_dist": 50 },
    "special_attacks": [ [ "SHRIEK_ALERT", 6 ], [ "SHRIEK_STUN", 1 ] ],
    "anger_triggers": [ "PLAYER_CLOSE", "FRIEND_DIED", "FRIEND_ATTACKED", "HURT" ],
    "fear_triggers": [ "FIRE" ],
    "death_function": [ "NORMAL" ],
    "flags": [ "SMELLS", "HEARS", "SEES", "SWIMS", "GRABS", "ARTHROPOD_BLOOD", "PATH_AVOID_DANGER_2" ]
  },
```

**Comment by dissociativity** [comment] 2019-03-16 08:26
This is the entry for my fork of PK Rebalance:
  {
    "id": "mon_razorclaw",
    "type": "MONSTER",
    "name": "razorclaw",
    "copy-from": "mon_razorclaw",
    "path_settings": { "max_dist": 12 },
    "attack_effs": [ { "id": "rad_tenths", "duration": 10 }, { "id": "flu_zed", "duration": 14400, "chance": 5 } ],
    "special_attacks": [ [ "SHRIEK_ALERT", 6 ], [ "SHRIEK_STUN", 1 ], [ "scratch", 20 ], [ "wound_minor", 15 ] ]
  },

**Comment by ZhilkinSerg** [comment] 2019-03-16 09:35
It is possible that harvest entries are not being copied. Add harvest entries to mod version of monster and check if error is resolved.

**Comment by ZhilkinSerg** [comment] 2019-03-30 08:59
Error should be fixed by third-party mod author.

**Closed by ZhilkinSerg** 2019-03-30 08:59 UTC
Labels: (S4 - Invalid), <Crash / Freeze>, Items / Item Actions / Item Qualities, Mods
