### ISSUE TITLE
Crash - related to NPC Farmhouse mission completion?

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#15872] opened 2016-03-23 09:45 UTC
I have a repeatable crash to desktop.
Linux, tiles, g6908e18

Save file is at:
https://www.sendspace.com/file/qxau5i

Probably related to the NPC you can see on the map. To cause crash, head north-east along the road. It will crash when you approach the NPC.

This NPC just assigned the "Reach Farm House" mission, when we were already inside a farm house. I indicated completion of the mission, and she said thanks and then disappeared down the road (it was dark, but I could still see her on the map). I then slept in the farm house, cooked some food, and headed out down the road.

**Comment by romkuma** [comment] 2016-04-20 10:23
Haven't played for a while, but just checked and this is still occurring in g750a589.

**Comment by Leland** [comment] 2017-08-24 03:28
Cannot reproduce. Closing due to the fact that the savefile 404s now and owner (pinging @romkuma) is AWOL. Crash could be due to any number of variables uneasily duplicated w/o save.

**Closed by Leland** 2017-08-24 03:28 UTC
Labels: Bug, Confirmation Needed, Crash / Freeze, Mission
