### ISSUE TITLE
Give walls and doors health points.

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#45598] opened 2020-11-23 22:35 UTC
Give walls and doors health points, so when we are striking the wall and it is at 99% we get interrupted the wall wont magically regenerate, the hp of the wall is going to get stored.

 Obviously we would need a repair wall/door option and a way to see the hp.

**Comment by CoroNaut** [comment] 2020-11-23 23:37
Every wall or door already has many states indicating the level of damage they've sustained. You have an unbroken wall/door which works as intended. A wall/door with holes means you and zombies can see through it enough to identify things outside/inside effectively. Then the next damage state is an empty frame where the wall or door used to be and you can move through without any difficulty. 

It isn't that the walls regenerate, its that you have for instance, a 20 sided dice, and if you roll an 18-20, that will count as a successful roll on the dice and apply damage to change its state. If you roll 1-17, then nothing will happen to the wall. These values are for example. Increasing the stats of your character that you think will affect bashing damage like strength or melee combat perhaps will give you an advantage in this dice roll making it easier to hit a successful check.

If there were values for the hp of everything in the game, it would bloat the save file size which would slowly increase load times and of course, use more hard drive space.

**Comment by Rivet-the-Zombie** [comment] 2020-11-24 06:34
>If there were values for the hp of everything in the game, it would bloat the save file size which would slowly increase load times and of course, use more hard drive space.

That and cause that weird phenomenon you see in some games where a zombie can gradually erode away a concrete block wall with nothing but its fingers by doing a single point of damage to it per turn for days on end.

**Comment by Qrox** [comment] 2020-11-24 08:01
> That and cause that weird phenomenon you see in some games where a zombie can gradually erode away a concrete block wall with nothing but its fingers by doing a single point of damage to it per turn for days on end.

We can prevent this by having the wall erode away the zombie's fingers first. (actually might be a good thing to have even if we do not add health points to walls)

**Comment by Night-Pryanik** [comment] 2020-11-24 08:13
> zombie can gradually erode away a concrete block wall with nothing but its fingers by doing a single point of damage to it per turn for days on end.

Zombies (at least ordinary ones) shouldn't be able do deal _any_ damage to concrete walls in the first place.

**Comment by Kelenius** [comment] 2020-11-24 10:15
Having hitpoints doesn't mean the wall has to take damage from EVERY attack. It can have hitpoints and armor. Why is that even an argument?

**Comment by rafaelkb** [comment] 2020-11-24 12:04
> Every wall or door already has many states indicating the level of damage they've sustained. 

Thats not what happens when you use a pickaxe to take down a wall or a door.
As i said before, if you get interrupted at 99% at destroying the door/wall the door/wall is going to regenerate.

**Comment by rafaelkb** [comment] 2020-11-24 12:05
> Having hitpoints doesn't mean the wall has to take damage from EVERY attack. It can have hitpoints and armor. Why is that even an argument?

I agree. The wall could get one hitpoint only with attacks above 20 or 17, or some mechanic like that.

**Comment by rafaelkb** [comment] 2020-11-24 12:09
> If there were values for the hp of everything in the game, it would bloat the save file size which would slowly increase load times and of course, use more hard drive space.

Use more hard drive space is not a good excuse. How much memory it consume? Ten megabytes? It is pretty low to be honest.

**Comment by anothersimulacrum** [comment] 2020-11-24 15:37
Relevant https://github.com/CleverRaven/Cataclysm-DDA/issues/33374#issuecomment-542913726

Also, rafaelkb, please fill out the template when you file an issue. You've filed several issues, and as far as I have seen, you have never filled them out following the template.

**Comment by rafaelkb** [comment] 2020-11-24 16:17
> Relevant https://github.com/CleverRaven/Cataclysm-DDA/issues/33374#issuecomment-542913726
> 
> Also, rafaelkb, please fill out the template when you file an issue. You've filed several issues, and as far as I have seen, you have never filled them out following the template.

Sure

**Comment by Night-Pryanik** [comment] 2021-09-17 07:36
No discussion in a long time, closing.

**Closed by Night-Pryanik** 2021-09-17 07:36 UTC
Labels: <Suggestion / Discussion>
