### ISSUE TITLE
Rotten meat, offal, stomach is available for recipes.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24906] opened 2018-08-17 18:58 UTC
It is bad when you notice after 20x cooked meat cooked, that the ingredient was rotten and therefore the result is rotten. That can be bad because the time and recources can be lost and difficult to recover.

Please change that so that rotten meat, etc gets flagged to another category. Tainted meat for example is in the category OTHER, not FOOD.

There might be a reason that rotten ingredients are still be available for recipes. Right know I dont know any.

**Comment by Night-Pryanik** [comment] 2018-08-17 19:04
Duplicate of #22129.

**Closed by Night-Pryanik** 2018-08-17 19:04 UTC
