### ISSUE TITLE
Charging batteries with water purifier

### ISSUE THREAD

**Issue by lech14** [CleverRaven/Cataclysm-DDA#64069] opened 2023-03-08 21:35 UTC
### Describe the bug

When using stationary water purifier it charges power grid batteries to maximum

### Attach save file

[Hawk Inlet-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10925416/Hawk.Inlet-trimmed.tar.gz)

### Steps to reproduce

connect stationary water purifier to a power grid

use it with or without the water

power grid batteries are now fully charged

### Expected behavior

I expect that using water purifier should drain power from grid

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by aahue1889** [comment] 2023-03-08 21:41
Checking

**Comment by RenechCDDA** [comment] 2023-03-08 21:44
/confirmed. Regression of #63649?

I smashed the solar panel on the roof to be sure (didn't see any other power generation and grid reports no charging), then hooked up a new car battery and activated the empty purifier, which jumped to 2711/3000 charge.

@irwiss You might want to see this.

**Comment by RenechCDDA** [comment] 2023-03-08 21:51
Whoops... too quick on the confirmed label there. It did not in fact recharge either battery, it just.... shifted the charge from one battery to another? I tried setting up a blank new instance as well as tracking the total charge after resetting the save file, neither produced charge when activating the water purifier.

**Comment by irwiss** [comment] 2023-03-08 22:10
Not strictly a regression - I couldn't replicate this part of the bug in that PR that's why i put `Fi*es`, but this save can be used to replicate it nicely with a couple extra steps:
* Load the save, debug teleport on top of the battery, debug menu -> vehicle menu -> change battery charge, put -2500, this should leave battery at 500/3000
* Teleport near purifier (save here for convenience) and examine water purifier and use it with `a`

The battery will be at 3000/3000

**Comment by irwiss** [comment] 2023-03-09 00:24
Damn this was annoying to trace as bfs and visitor lambdas were jumping all over the place.

The root cause and the reason andrei8l and I couldn't reproduce it in #63649 (instead andrei8l reproduced a different bug) is the missing secret sauce: a jumper cable (or any cable with POWER_TRANSFER and non-zero power loss)

![image](https://user-images.githubusercontent.com/6560075/223871465-923e0029-5f47-4543-b80b-dd9b1299051c.png)

The whole discharge sequence runs in a BFS where nodes are vehicles and power cables are edges.

Purifier requests a discharge of 1,000,000kJ for pseudo battery, successfully traversing/draining 500kJ from the car battery on ground level via appliance `power_cord`s which have 0% loss.
This leaves 999,500kJ to discharge from the solar panel appliance on the roof, but `long_extension_cable`(outdoor extension cord) has 1% loss which results in 9995kJ "loss" regardless of how much charge is actually drained from it (or if it has any battery to begin with), without checking if there actually is 9995kJ in the source that's drained.

From there it goes downhill:
discharge_battery(...) returns it's "missing" 1,009,495kJ ( 1000000 wanted + 9995 "loss" - 500 battery charges )
item::ammo_set( itype_battery, qty ) is called with qty = (1000000 - 1,009,495) = -9495, the negative amount is apparently encoding for "make it full"
At this point pseudo battery is at 1,000,000 charge, having no water in my test the purifier fails (fail irrelevant to the bug).
charge_battery() is then called with remaining charge in pseudo battery (the 1000000kJ created by ammo_set) fully charging the real batteries

Can't think of a trivial/easy fix for this (well, besides just axing the power "loss" to wires), there's 2 problems:
* The loss calculation is wrong - "vehicles"(/appliances) which transfer 0 charge still contribute the entire "loss" of the requested amount
* Even fixing the first problem the way pseudo tools work will first discharge (incurring loss) to charge pseudo battery, invoke the tool functions, and then charge the pseudo battery's remaining charge back to the vehicle (again incurring loss)

May be the "right" fix would be to rewrite the temporary-permanent hack for pseudo tools to prevent the discharge/charge cycle

**Closed** 2023-03-20 03:33 UTC
Labels: (S2 - Confirmed)
