### ISSUE TITLE
Welding Overhaul: A discussion on realism vs. gamism and what should change or keep

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [CleverRaven/Cataclysm-DDA#42832] opened 2020-08-09 22:51 UTC
# Is your feature request related to a problem? Please describe.
Welding is currently over-used as part of vehicle projects and under-used as part of construction. And there are problems with expendables.

# Describe the solution you'd like
This FR is a split from #23094 

I am a ship engineer (a maintainer of ship's systems) and auto mechanic, and also a welder. I almost never break out the welder for mechanical tasks. Almost everything is bolt-on. That said, after the cataclysm, finding OEM parts for your vehicle is going to be challenging. Even figuring out which parts are usable on which vehicle, without an appropriate database, will be challenging. It makes sense that many components will end up being cobbled together with welding technologies for as long as the expendables remain viable, which is not forever, and available.

There is a needful trade-off between realism and game play. This is understood. The question is how much realism to inject without significantly affecting play possibilities. I propose our current system has the following problems:

1. Welding is over-used in vehicle mechanics.
2. Welding is under-used in (large) construction mechanics.
3. There is no distinction between welding technologies except electric-arc and oxyacetylene but IRL, there are sub-classifications of electric-arc welding and each has limitations on its capability and applicability to any given task. Additionally, explosion-welding (yes, literally with explosives), chemical welding, forge welding, induction welding, and other methods exist and are not modeled.
4. Welding currently uses, effectively, no expendables while IRL welding extensively uses difficult-to-manufacture, limited-shelf-life expendable materials.
5. ... others I'm not willing to expand on because I don't want to bother taking the time in this FR and also because I believe they would adversely affect playability.

# Describe alternatives you've considered
## Welding uses
A broad discussion on where welding is useful and where it is not is needed. I can say, though, that I rarely get out a welder in my IRL mechanic tasks. When possible, I almost always prefer metal-glues or drill-n-bolt when I am fabbing up something which is not OEM-designed to be compatible.

## Welders and welding items
In my opinion, the best balance of realism vs. gamism is the following:

### Add expendables for welding
Welding requires an additional input of metal to form the bead. In oxy-acet and TIG welding, this is little more than a rod of appropriate metal while MIG welding uses wire on a spool feed and "stick" welders utilize a chemical-coated rod. The current existing "wire" item should suffice.

Additionally, MIG and TIG welding requires the use of an oxygen-shielding gas. For game play reasons, this is probably best ignored and we should assume all electric welders are "stick" welders using chemical-coated rod. Again for game play reasons, it should be simplified to just using the "wire" item.

### Significantly increase power requirement for electric welding
Welding needs power! Modern production electric-arc welding machines come in two types: those you plug into a mains socket, and those powered by an integrated engine-driven electrical generator. In terms of the US power grid, the most widely-useful electric arc welder will require a 30+A, single-phase, 240V power supply. That equates to around a 3kW generator. A more common mains-powered welder needs a 20A, 120V socket but cannot weld thicker material. It is, however, sufficient for most vehicle-mechanic needs. Yes, you can power a welder from car batteries, but welding will drain a _pair_ of automotive starter batteries to uselessness-for-welding in less than 30 minutes.

Power requirement, in C:DDA, should be adjusted accordingly. Lore notes big leaps in battery technology, so it would not destroy believability that welders can be battery powered. At the very least, however, require a heavy battery or car battery or storage battery and triple, or more, the required number of "charges" for any given task. I mean, why does a hotplate need a heavy battery and a welder only a medium?

Remove the welding ability from the Integrated Toolset CBM unless it somehow is connected to an external power source (UPS-mod as a CBM?.) I get it, CBMs are a "fantasy" item for C:DDA but bionic-powered welding stretches believably far too much.

# Additional context
I mean, we could really get into the weeds on welding. Electric-arc welding is one of the 20th century's most advanced technological leaps, so advanced it was considered a wartime secret in the first half of the century. I see no real need to model more exotic or less-used welding methods (explosion, chemical, induction) in the game and forge welding is already well modeled in the forge-n-anvil gear and associate tasks.

Again, this issue is opened as a discussion prompt. Maybe the forums would be a better place to discuss it, but I already have an account here at GitHub and I don't want to create a forum account which would see limited use and present a threat to my internet security for years to come.

I think the current welding system is functional but would benefit from some small changes.

What are you thoughts?

**Comment by kevingranade** [comment] 2020-08-09 22:54
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/need-help-developing-ideas-to-improve-welding-mechanics/19401/11

**Comment by anothersimulacrum** [comment] 2020-08-09 23:59
So, here's a list of parts that require welding to install:
<details>
<summary>Install</summary>
folding_frame,
frame,
hdframe,
xlframe,
forklift_fork,
rockwheel,
air_jack,
motorcycle_kickstand,
lit_aisle_horizontal,
external_tank_small,
tank_30gal_drum,
fuel_bunker,
hatch_abstract,
hatch_opaque_abstract,
hdhatch_abstract,
hdhatch_opaque_abstract,
welding_rig_abstract,
welding_rig,
storage_battery,
rebar_plate,
spring_plate,
wheel_mount_light,
wheel_mount_medium,
wheel_mount_heavy,
generator_7500w,
windshield_abstract,
reinforced_windshield_abstract,
board,
stowboard,
hdboard,
xlhalfboard,
basketlg_abstract,
basketlg_external,
basketlg_folding,
basketsm_external,
cargo_space_external,
cart_handle,
bed,
frame_handle,
aisle_horizontal,
aisle_vertical,
trunk_floor,
roof,
hdroof,
blade_horizontal,
blade_vertical,
spike,
storage_battery_mount,
minireactor,
trunk,
plastic_boat_hull,
metal_boat_hull,
carbonfiber_boat_hull,
inflatable_section,
inflatable_airbag,
controls,
muffler,
plating_steel,
plating_superalloy,
plating_spiked,
plating_hard,
plating_military,
cargo_space,
livestock_stall,
drive_by_wire_controls,
robot_controls,
metal_funnel,
vehicle_scoop,
plow,
seed_drill,
seed_drill_advanced,
reaper,
reaper_advanced,
turret_mount,
ram_blaze,
ram_alloy,
ram_hardsteel,
ram_military_horizontal,
ram_spiked,
tearer,
</details>
And here's a list of things that require welding to repair:
<details>
<summary>Repair</summary>
metal_wheel,
folding_frame,
frame,
hdframe,
xlframe,
crane_medium,
crane_small,
crane_tiny,
forklift_fork,
rockwheel,
air_jack,
motorcycle_kickstand,
lit_aisle_horizontal,
diesel_engine_i6,
diesel_engine_v6,
diesel_engine_v8,
engine_1cyl,
engine_1cyl_large,
engine_1cyl_small,
engine_aero_light,
engine_inline4,
engine_v12,
diesel_engine_v12,
engine_v6,
engine_v8,
engine_vtwin,
engine_steam_makeshift,
engine_steam_small,
engine_steam_medium,
engine_turbine_small,
engine_turbine_medium,
engine_turbine_large,
tank_little,
tank_medium,
tank,
fridgetank,
external_tank_small,
tank_30gal_drum,
fuel_bunker,
door_abstract,
door_opaque_abstract,
hddoor_abstract,
hddoor_opaque_abstract,
door_internal_abstract,
hatch_abstract,
hatch_opaque_abstract,
hdhatch_abstract,
hdhatch_opaque_abstract,
seat_abstract,
reclining_seat_abstract,
saddle_abstract,
folding_seat_abstract,
kitchen_unit_abstract,
welding_rig_abstract,
craft_rig_abstract,
chemlab_abstract,
veh_forge_abstract,
veh_kiln_abstract,
welding_rig,
battery_car,
rebar_plate,
spring_plate,
wheel_mount_light,
wheel_mount_medium,
wheel_mount_heavy,
rail_wheel,
roller_drum,
wheel_caster,
wheel_10,
alternator_car,
alternator_truck,
generator_7500w,
windshield_abstract,
reinforced_windshield_abstract,
board,
stowboard,
hdboard,
xlhalfboard,
basketlg_abstract,
basketlg_external,
basketlg_folding,
basketsm_abstract,
basketsm_external,
cargo_space_external,
bike_rack,
mounted_spare_tire,
engine_electric,
engine_electric_large,
engine_electric_enhanced,
engine_electric_super,
foot_pedals,
hand_rims,
seat,
reclining_seat,
cart_handle,
bed,
frame_handle,
aisle_horizontal,
aisle_vertical,
trunk_floor,
roof,
hdroof,
blade_horizontal,
blade_vertical,
spike,
storage_battery_mount,
minireactor,
minifridge,
minifreezer,
washing_machine,
dishwasher,
autoclave,
trunk,
veh_table,
veh_table_wood,
workbench,
plastic_boat_hull,
metal_boat_hull,
carbonfiber_boat_hull,
inflatable_section,
inflatable_airbag,
controls,
muffler,
wind_turbine,
xl_wind_turbine,
reinforced_solar_panel,
reinforced_solar_panel_v2,
water_faucet,
towel_hanger,
plating_steel,
plating_superalloy,
plating_spiked,
plating_hard,
plating_military,
door_trunk,
hddoor_trunk,
door_shutter,
door_sliding,
cargo_space,
livestock_stall,
drive_by_wire_controls,
robot_controls,
metal_funnel,
vehicle_scoop,
plow,
seed_drill,
seed_drill_advanced,
reaper,
reaper_advanced,
turret_mount,
ram_blaze,
ram_alloy,
ram_hardsteel,
ram_military_horizontal,
ram_spiked,
tearer,
</details>

If you have time, could you say which of those are inappropriate or should be using something else?

**Comment by ParaplegicRacehorse** [comment] 2020-08-10 00:32
Wow! Uh... okay. Almost none of it **needs** welding to install. Most could be installed with the right adhesive or are bolt-on components. That said, most it **can** be installed by welding.

The repair list is more tricky.

And this is only the vehicle parts and doesn't including crafting recipes and construction. I pulled the list into a text file where I can more easily work on it. I will edit this post when I have something more.

**Comment by ParaplegicRacehorse** [comment] 2020-08-10 02:29
> I have a degree in engineering science but my focus was primarily EE and I am not a welder. However, I do maintain the vehicle code so I have oversight over a lot of these potential changes.

I do a lot of remove-n-replace as well as install and repair (ships). I get trained in pretty much every field you can think of: electrical, engines, wood/composite/metal fabrication and machining, welding, plumbing, refrigeration and HVAC, hydraulics (pneumatics, too!), rigging, and more. Ship engineers are perhaps the most broadly trained technicians in the world.

Anyway,

In addition to the vehicle stuffs, welders are heavily used in crafting and not-so-heavily used in construction. I don't have a list of items, but I've even seen welder as an option in food recipes (which is absolutely ridiculous but, I suppose, possible.)

I guess while we're at it, welders can be used to cut metal, too, which provides some interesting game play options when trying to break into banks and labs.

> Your suggested changes are entirely reasonable and I've suggested making them before but haven't had the time to do it myself. Electric welding should consume around 80 battery charges/minute (which is 1 car battery per 30 minutes - I guess it depends on the efficiency of the welder or something? we can argue about the appropriate value but 150 charges/minute isn't crazy),

Given the short length of a year/season/whatever, it's not terrible to compress project times and consumable ... consumption. I will bow to your 80 charges per minute and be happy. I would be happier at 100-120 charges per minute.

> flux rods should be added as an item (not just wire for the chemically coated rod), and vehicle repair should require wrench and ratchet sets, not just wrenches.

I agree with both assertions: 
* flux rod would be better than just using wire, but wire is expedient and much better than currently implemented. However, since the topic is all about overhauling welding in general, yes, flux-coated welding rod should be added.
* I think the current wrench, described as an adjustable, should be reduced to bolt_turning 2 (or 1 if pliers lose their bolt_turning), and `wrench_set` and `socket_set` should both be introduced with bolt_turning 3 or 4. I often spend whole days without touching a socket set. My goto tool for all things mechanics is a set of wrenches and nut drivers. Ratchets are nice, but finicky and time consuming. Mostly I only use them when my nut/bolt is deep in a hole where a wrench can't reach, or when I'm going to hook up the air tools. But this point is off-topic.

**Comment by ParaplegicRacehorse** [comment] 2020-08-10 02:35
Also, it would not be unreasonable to consume one welding rod (or wire for oxy-acet) per minute of welding work. I would be okay at 1 per 2 minutes, though.

**Comment by Alex-Folts** [comment] 2020-08-10 14:02
> | \*_engine_\*             | yes *    | Engines are tricky and need more extensive discussion.                         |

Staring from the fact that engines and other complex mechanisms can have mechanic damages or wear, and for maintenance need spare parts and complex machinery. I mean when you find parked car on side of the road, it is not crashed, but engine in very bad condition, we assume that engine is weared and require maintenance(and it is not about filters and timing belt, those covered with defects system, i'm talking about elipse and scratches on cylinders surfaces, weared working surfaces on crankshaft - it require resurfacing of cylinders and crankshaft, set of repair size pistons and journal bearings...).

**Comment by LordKaaven** [comment] 2020-08-10 23:40
+1 for the idea of welding rods as an extra resource. Just have to make sure there's enough of them lying around to actually make welding possible.

One thing that I feel could be expanded upon (tho I have no idea about implementation) is the "low-tech" alternative to welding - riveting. Trains, tanks and planes were once made that way and there isn't even a mention of it in the game. There could possibly be the entire divide between "high-tech fast and easy, but requiring power and rods" welding and "low-tech dirty and slow but entire charcoal-powered" riveting. Small crafts could even be possible with pressure-powered rivet guns. Or is it too much/not doable by single person kinda deal?

**Comment by RoyBerube** [comment] 2020-08-11 07:10
A while ago I tested welding rods by adding wire as a component for welding_standard in toolsets.json. I didn't notice any issues; it just added wire the same way that solder is used for soldering. A PR to add them would be as simple as can be.

**Comment by ParaplegicRacehorse** [comment] 2020-08-16 22:16
Is there a quick-n-easy way to search through the various crafting recipes to highlight those with welding (option) requirement? Many of them are inappropriate, IMO. Vehicle interaction was not my primary motivation for starting this issue.

**Comment by anothersimulacrum** [comment] 2020-08-16 22:19
`tools/json_tools/table.py --type=recipe result id_suffix using -f=csv | grep weld`
```revolver_shotgun,None,"['welding_standard', 3]"
surv_six_shooter,None,"['welding_standard', 3]"
surv_hand_cannon,None,"['welding_standard', 3]"
triple_launcher_simple,None,"['welding_standard', 20]"
combatsaw_off,None,"['welding_standard', 10]"
e_combatsaw_off,None,"['welding_standard', 10]"
adjustable_stock,None,"['welding_standard', 1]"
folding_stock,None,"['welding_standard', 1]"
bipod,None,"['welding_standard', 1]"
pistol_stock,None,"['welding_standard', 1]"
recoil_stock,None,"['welding_standard', 1]"
dias,None,"['welding_standard', 2]"
bigun,None,"['soldering_standard', 10] / ['welding_standard', 25]"
ashot,None,"['welding_standard', 10]"
m2browning_sawn,None,"['welding_standard', 3]"
surv_rocket_launcher,None,"['welding_standard', 3]"
steam_watts_small,None,"['welding_standard', 10]"
fuel_bunker,None,"['welding_standard', 10]"
hd_tow_cable,None,"['welding_standard', 8]"
bike_rack,None,"['welding_standard', 2]"
rebar_plate,None,"['welding_standard', 10]"
spring_plate,None,"['welding_standard', 10]"
tearer,None,"['welding_standard', 10]"
minifreezer,None,"['welding_standard', 50]"
mountable_heater,None,"['welding_standard', 5]"
mountable_cooler,None,"['welding_standard', 20]"
washing_machine,None,"['welding_standard', 5]"
dishwasher,None,"['welding_standard', 5]"
wheel_caster,None,"['welding_standard', 4] / ['steel_tiny', 4]"
cargo_aisle,None,"['welding_standard', 5]"
wheel_mount_light,None,"['welding_standard', 1]"
turret_mount,None,"['welding_standard', 3] / ['steel_standard', 2] / ['soldering_standard', 10]"
basket,None,"['welding_standard', 5] / ['cutting_wire_standard', 1]"
folding_basket,None,"['welding_standard', 5] / ['cutting_wire_standard', 1]"
bike_basket,None,"['welding_standard', 2] / ['cutting_wire_standard', 1]"
foldframe,None,"['welding_standard', 6]"
wheel_wheelchair,None,"['welding_standard', 4]"
hand_rims,None,"['welding_standard', 2]"
reinforced_glass_sheet,None,"['welding_standard', 10]"
chainsaw_off,None,"['welding_standard', 10]"
small_space_heater,None,"['welding_standard', 5] / ['steel_standard', 2]"
large_space_heater,None,"['welding_standard', 10] / ['steel_standard', 4]"
reinforced_glass_pane,None,"['welding_standard', 4]"
headlight_reinforced,None,"['welding_standard', 2]"
wide_headlight_reinforced,None,"['welding_standard', 2]"
reinforced_solar_panel,None,"['welding_standard', 4]"
reinforced_solar_panel_v2,None,"['welding_standard', 5]"
cargo_rack,None,"['rope_natural', 4] / ['welding_standard', 10]"
workbench,None,"['welding_standard', 5]"
muffler,None,"['welding_standard', 5]"
seat,None,"['sewing_standard', 50] / ['welding_standard', 5]"
seat_leather,None,"['sewing_standard', 50] / ['welding_standard', 5]"
vehicle_controls,None,"['welding_standard', 5]"
folding_bicycle,None,"['welding_standard', 30]"
metal_tank,None,"['welding_standard', 5]"
metal_tank_little,None,"['welding_standard', 2]"
jerrycan_big,welder,"['welding_standard', 5]"
welder_crude,None,None
jackhammer,None,"['welding_standard', 10]"
brick_kiln,None,"['welding_standard', 15] / ['steel_standard', 6]"
kiln,None,"['welding_standard', 15] / ['steel_standard', 6]"
con_mix,None,"['soldering_standard', 25] / ['welding_standard', 20]"
55gal_drum,welded,"['welding_standard', 15]"
30gal_drum,welded,"['welding_standard', 10]"
bucket,None,"['welding_standard', 3]"
metal_funnel,None,"['welding_standard', 3]"
v_scoop_item,None,"['welding_standard', 5]"
v_planter_item,None,"['welding_standard', 5]"
v_reaper_item,None,"['welding_standard', 5]"
v_plow_item,None,"['welding_standard', 5]"
pot_canning,None,"['welding_standard', 30]"
solarpack,None,"['soldering_standard', 35] / ['welding_standard', 20]"
xl_wind_turbine,None,"['welding_standard', 10] / ['soldering_standard', 35]"
kitchen_unit,None,"['welding_standard', 10]"
weldrig,None,"['welding_standard', 10]"
craftrig,None,"['welding_standard', 10]"
chemlab,None,"['welding_standard', 10]"
bot_turret,None,"['steel_standard', 1] / ['welding_standard', 20] / ['soldering_standard', 14]"
bot_nursebot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_grocerybot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_dispatch,None,"['steel_standard', 1] / ['soldering_standard', 20] / ['welding_standard', 5]"
bot_dispatch_military,None,"['steel_standard', 1] / ['soldering_standard', 20] / ['welding_standard', 5]"
bot_hazmatbot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_copbot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_eyebot,None,"['soldering_standard', 3] / ['welding_standard', 3]"
bot_molebot,None,"['soldering_standard', 10] / ['welding_standard', 6]"
bot_riotbot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_secubot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_talon_m202a1,None,"['soldering_standard', 20] / ['welding_standard', 5]"
elec_jackhammer,None,"['welding_standard', 10]"
elec_chainsaw_off,None,"['welding_standard', 10]"
drive_by_wire_controls,None,"['soldering_standard', 30] / ['welding_standard', 5]"
broken_copbot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_robofac_prototype,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_molebot,None,"['welding_standard', 6]"
broken_riotbot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_secubot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_talon_m202a1,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_mech_recon,None,"['soldering_standard', 30] / ['welding_standard', 20]"
broken_mech_lifter,None,"['soldering_standard', 30] / ['welding_standard', 20]"
broken_mech_combat,None,"['soldering_standard', 30] / ['welding_standard', 20]"
broken_nursebot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_nursebot_defective,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_grocerybot,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_grocerybot_busted,None,"['soldering_standard', 20] / ['welding_standard', 5]"
bot_grocerybot_busted,None,"['soldering_standard', 20] / ['welding_standard', 5]"
broken_exodii_worker,None,"['soldering_standard', 30] / ['welding_standard', 20]"
broken_exodii_quad,None,"['soldering_standard', 60] / ['welding_standard', 30]"
broken_exodii_turret,None,"['soldering_standard', 60] / ['welding_standard', 30]"
broken_exodii_sniper_drone,None,"['soldering_standard', 50] / ['welding_standard', 20]"
mininuke,None,"['soldering_standard', 150] / ['welding_standard', 6]"
motor,None,"['soldering_standard', 40] / ['welding_standard', 3]"
motor_large,None,"['soldering_standard', 50] / ['welding_standard', 5]"
solarpack,None,"['soldering_standard', 35] / ['welding_standard', 20]"
solarpack_on,None,"['soldering_standard', 35] / ['welding_standard', 20]"
sheet_metal,welding,"['welding_standard', 10]"
xlframe,None,"['welding_standard', 6]"
cantilever_medium,None,"['welding_standard', 10] / ['steel_standard', 2]"
cantilever_small,None,"['welding_standard', 5] / ['steel_tiny', 2]"
pallet_lifter,None,"['welding_standard', 5] / ['steel_tiny', 2]"
livestock_carrier,None,"['rope_natural', 4] / ['welding_standard', 12] / ['steel_standard', 2]"
livestock_carrier,repurpose_cargo_rack,"['welding_standard', 2] / ['steel_standard', 1]"
animal_locker,None,"['rope_natural', 2] / ['welding_standard', 6]"
animal_locker,repurpose_wire_basket,"['welding_standard', 2]"
hand_pump,None,"['welding_standard', 1]"
jack_small,None,"['welding_standard', 5]"
can_sealer,None,"['welding_standard', 1] / ['forging_standard', 1]"
closed_loop_extractor_small,None,"['welding_standard', 5] / ['blacksmithing_standard', 2] / ['steel_standard', 5]"
closed_loop_extractor_large,None,"['welding_standard', 10] / ['blacksmithing_standard', 5] / ['steel_standard', 10]"
vac_pump,None,"['welding_standard', 10] / ['blacksmithing_standard', 5]"
recovery_pump,None,"['welding_standard', 10] / ['blacksmithing_standard', 5]"
vac_oven_small,None,"['welding_standard', 5] / ['blacksmithing_standard', 2] / ['steel_standard', 5]"
goggles_welding,None,None
welding_mask_crude,None,"['blacksmithing_standard', 16] / ['steel_standard', 4]"
tinyweldtank,None,None
weldtank,None,None
spear_pipe,None,"['welding_standard', 2] / ['steel_tiny', 1]"
grip_hook,None,"['welding_standard', 2] / ['steel_tiny', 1]"
pistol_stock,None,"['welding_standard', 15]"
chemical_thrower,None,"['welding_standard', 40]"
slamfire_shotgun,without_welding,None
slamfire_shotgun_d,welded_together,None
slamfire_shotgun_d,bolted_and_welded,None
pressurized_tank_chem,None,"['welding_standard', 2]"
aux_pressurized_tank,None,"['welding_standard', 2]"
alternator_car,None,"['soldering_standard', 40] / ['welding_standard', 10]"
alternator_motorbike,None,"['soldering_standard', 20] / ['welding_standard', 5]"
alternator_truck,None,"['soldering_standard', 40] / ['welding_standard', 10]"
stereo,None,"['soldering_standard', 10] / ['welding_standard', 10]"
chimes,None,"['soldering_standard', 10] / ['welding_standard', 10]"
```

**Comment by I-am-Erk** [comment] 2020-09-17 18:16
I missed this when it came up. Commenting to follow. I am soon going to add proficiencies related to welding, and this gives me some ideas where to start.

**Comment by TieSKey** [comment] 2020-11-29 22:06
Not sure about the state of this issue, just wanted to chip in that the "poncho" asks for a soldering iron to repair (a poncho is made of wool)

**Comment by Zireael07** [comment] 2020-11-30 11:04
IIRC poncho has more than one material in game, and that other material is one that a soldering iron repairs. Multiple material items are kinda wonky atm when it comes to repair.

**Comment by TieSKey** [comment] 2020-11-30 15:23
> IIRC poncho has more than one material in game, and that other material is one that a soldering iron repairs. Multiple material items are kinda wonky atm when it comes to repair.

Ok, then the problem is in the materials, a poncho doesn't have any metal. Maybe a couple bone adornments but that's all. 
Source: https://en.wikipedia.org/wiki/Poncho and well, while I'm descendant of italian immigrants, I do live in south america.

**Comment by actual-nh** [comment] 2020-12-20 01:17
@TieSKey: I suspect it is assuming a plastic poncho.

**Comment by TieSKey** [comment] 2020-12-20 01:54
Oh, plastic is fixed with a solder, right. 
I have never ever heard of a plastic poncho, as for us changing the material makes it not a poncho anymore. But it might be different in other neighboring countries so I guess its ok.

**Comment by actual-nh** [comment] 2020-12-20 02:12
Understand. (The wikipedia page appears to have a plastic poncho in the picture, BTW.)

**Comment by TieSKey** [comment] 2020-12-20 13:50
> Understand. (The wikipedia page appears to have a plastic poncho in the picture, BTW... unless it's a raincoat.)

Haha, yeah to be fair, that image makes little sense. Not only that's clearly a raincoat but it also says it's in China, while "poncho" is a south american garment.

**Comment by anothersimulacrum** [comment] 2020-12-20 17:14
The poncho in game refers to a rain garment of similar construction to the South American garment. Using poncho can refer to either in English, though it may be more likely to refer to the rain garment than the original as that is probably more familiar to most English-speakers.

**Comment by kevingranade** [comment] 2021-12-27 22:11
Idle for well over a year, can be used for reference.

**Closed by kevingranade** 2021-12-27 22:11 UTC
Labels: <Enhancement / Feature>, <Suggestion / Discussion>, (P5 - Long-term), Vehicles
