### ISSUE TITLE
Necromancer is able to raise a corpse pulped by weapon damage

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33303] opened 2019-08-17 15:43 UTC
# Describe the bug

A necromancer is able to raise the corpse of a zombie that was overkilled by a weapon (corpse received "pulped"-status).

# Steps To Reproduce

1. Start a new game, raise all skills to 5, spawn a steel spear and wield it.
2. Spawn a group of howling waifs and a necromancer in the back.
3. Kill the waifs with your spear. The corpses should all have "pulped"-status.
4. Observe the necromancer raising some of the corpses.

# Expected behavior

Corpses marked as "pulped" should not rise again.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6613-ge23659d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

#21554 and #30772 might be related.

**Comment by Night-Pryanik** [comment] 2019-08-18 17:43
I guess this can be marked as duplicate of #30772.

**Closed by Night-Pryanik** 2019-08-18 17:43 UTC
