### ISSUE TITLE
Turret Control Unit Bug

### ISSUE THREAD

**Issue by procrustesmethod** [CleverRaven/Cataclysm-DDA#35321] opened 2019-11-05 01:18 UTC
# Describe the bug
With a gun installed on a turret mount and a turret control unit on the same tile, switching "turret targeting mode" results in a segmentation fault. 
I have experienced this after uninstalling and reinstalling the turret mount, turret and turret control unit, using both the A7 laser rifle and a minigun. (To make sure it wasn't gun specific, or related to any updates.)

# Steps To Reproduce

1. Reload my game.
2. Go to control vehicle, select turret targeting mode.
3. Switch targeting mode of mounted A7 laser rifle from manual to auto.

# Expected behavior

I expected the turret to switch from manual targeting to automatic targeting.

# Screenshots
N/A

# Versions and configuration

 - OS: Linux Mint 19 Cinnamon
 - Game Version: 0.D-9090-gd1961e6
 - Graphics version: Tiles
 - Mods loaded:
Disable NPC Needs, Aftershock, Makeshift Items Mod, More Survival Tools, MST Extra, Generic Guns, Modular Turrets, Salvaged Robots, Alternative Map Key, Mining Mod, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, Beta National Guard Camp, Folding Parts Pack, Faster Stamina Regen, Prevent Zombie Revivication, Safe Autodoc, Simplified Nutrition, SpeedyDex, Stats Through Kills

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3806734/config.zip)
[save as mega file, since it is larger than 10MB](https://mega.nz/#!YBwUnQRC!qykew27IBlULEn7heAIM6C9plHDp_fL9O72DKa7C8DA)

**Comment by Night-Pryanik** [comment] 2019-11-05 05:58
Duplicate of #34831.

**Closed by Night-Pryanik** 2019-11-05 05:58 UTC
