### ISSUE TITLE
Vending machines need a bit of a nerf

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20031] opened 2017-01-15 07:34 UTC
It's not unusual to find up to a quarter-ton of foodstuffs and drinks in a vending machine. I've occasionally even seen 200+ individual packages of food in some machines. These machines can sometimes yield more food than all the grocery stories in a city -- and compounding this issue further is that vending machines often come in sets of two or three, depending on the type of building.

Vending machines really need some sort of cap on their maximum yields.

**Comment by codemime** [comment] 2017-01-15 08:18
Dupe of #15458.

**Closed by codemime** 2017-01-15 08:18 UTC
