### ISSUE TITLE
Headlamp Does Not Hold Batteries

### ISSUE THREAD

**Issue by CamIce2002** [CleverRaven/Cataclysm-DDA#40426] opened 2020-05-11 00:31 UTC
Game version: Build #10646

Operating system: Windows

Tiles or curses: Tiles

Mods active: none

### Expected behavior
Headlamps should hold light batteries and be able to be reloaded with them.

### Actual behavior
The reload option is greyed out even if a light battery is in inventory and so it cannot be turned on.

### Steps to reproduce the behavior
Create a world with just DDA, spawn in a headlamp, the reload option is greyed out.

**Comment by CamIce2002** [comment] 2020-05-11 02:53
This also happens with the food person mask.

**Comment by homebass** [comment] 2020-05-11 12:02
Also happens with light amp goggles. Very annoying!

**Comment by KorGgenT** [comment] 2020-05-12 19:27
#40399 should do a lot toward this, but the json will need to be updated still, after the pr is merged.

**Comment by ThePotatomancer** [comment] 2020-06-08 19:11
cannot reproduce in current build (#41172) for any of the mentioned items. I suggest to close the issue unless someone manages to reproduce it still

**Comment by anothersimulacrum** [comment] 2020-06-08 19:39
Closing then, let me know if

**Closed by anothersimulacrum** 2020-06-08 19:39 UTC
Labels: <Bug>, Good First Issue, [JSON]
