### ISSUE TITLE
Turning off TALON UGV Liberty Edition produces regular TALON UGV

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#65260] opened 2023-04-23 05:51 UTC
### Describe the bug

Using HM12 to turn off TALON UGV Liberty Edition, produces regular TALON UGV that's with M16A4 rifle.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11302913/test-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Turn off the TALON UGV Liberty Edition.
3. Find that it turned into regular TALON UGV.

### Expected behavior

There should be a TALON UGV liberty edition in item form.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 0.G-1503-ge8a1eafffb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by TealcOneill** [comment] 2024-05-16 00:58
/confirm
I think this was intended but I'm working on a small fix that will close this.

**Closed** 2024-05-16 14:53 UTC
Labels: <Bug>, (S2 - Confirmed)
