### ISSUE TITLE
Scenario description is truncated

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#59084] opened 2022-07-08 22:35 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/59517351/178078267-b8ee81cf-81ef-494c-8777-5ee9867d1da6.png)

### Steps to reproduce

1. Create a new character.
2. Go into the scenario selection.
3. Notice the truncated text.

Only the scenario tab is affected.

### Expected behavior

The text does not get truncated and looks like in every other tab.
I have a feeling this *might* have been caused by either #58804 or the main menu overhaul.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-9626-g5d5d5bd53b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment] 2022-07-08 23:31
https://github.com/CleverRaven/Cataclysm-DDA/issues/59080

**Comment by Night-Pryanik** [comment] 2022-07-09 07:24
Duplicate of #59080.

**Closed by Night-Pryanik** 2022-07-09 07:24 UTC
Labels: Info / User Interface, (S1 - Need confirmation), Character / World Generation
