### ISSUE TITLE
Container contents are put onto ground when eating from the trunk

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20491] opened 2017-03-08 17:24 UTC
Reproduce steps:

1. Put tin can of meat soup into vehicle trunk.
2. Eat it.
3. Any remaining portions will appear on the ground of the trunk tile

**Comment by spacenookie** [comment] 2017-03-09 04:30
if you have a can of meat soup in inventory, open it (and eat one serving), when you try to drop it game warns you that it that it will spill, but warning does not occur if your 'E'at from adjacent square, spill just happens

**Comment by Night-Pryanik** [comment] 2017-04-01 05:38
Dupe of #18168.

**Closed** 2017-04-14 00:53 UTC
