### ISSUE TITLE
Feathers burn with extreme intensity

### ISSUE THREAD

**Issue by LexLonbray** [CleverRaven/Cataclysm-DDA#49181] opened 2021-06-04 21:24 UTC
# Describe the bug

If you ignite even a single bird feather, it will produce instant raging fire, pretty sure it's not intended.

# Steps To Reproduce

1. Spawn a feather
2. Light it on fire
3. Skip a few turns

# Expected behavior

Feather should not burn like napalm, it should produce a small fire like other small and light flammable items.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 597492c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Salty-Panda** [comment] 2021-06-04 22:25
Looking at materials, they are made of `cotton`, which does get burned very fast, but it shouldn't produce `raging` fire.

I tested with a feather, down feather, and thread (similar volume, same material). After dropping one item and setting it on fire an ordinary `fire` was created, in a few turns it has grown into `raging fire`.

Probably caused by the high value of `volume_per_turn` property of `cotton`.

**Comment by NetSysFire** [comment] 2022-01-23 01:21
This still happens and I dropped one feather and one down feather each and ignited them with an ordinary lighter, they burned four hours. I only got a raging fire with the down feather but this still seems pretty wrong.

**Comment by Fris0uman** [comment] 2023-10-04 07:36
closed in #65536

**Closed by Fris0uman** 2023-10-04 07:36 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Fields / Furniture / Terrain / Traps, Mechanics: Temperature
