### ISSUE TITLE
Incorrect field of view computation when using light amp goggles inside a house

### ISSUE THREAD

**Issue by gvlasov** [CleverRaven/Cataclysm-DDA#16434] opened 2016-04-29 00:56 UTC
Inside: ![](https://i.gyazo.com/bf3dd09bf86e090068d4999be5a185f5.png)

Outside: ![](https://gyazo.com/4407bc7f9316f32dd6ccbe4635f2a58d.png)

When you are outside a house, the field of view is noticeably smaller.

Version: experimental at 1cb0ee3af2034f880cdd72cd2acc265f54c88ea3

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/241656/save.zip)

**Comment by Coolthulhu** [comment] 2016-04-29 01:02
Affects night vision too. I assume the calculation was supposed to equalize boosted and un-boosted vision ranges, but it looks like it shortens the night vision ranges when there is some light but not enough for the regular vision to properly kick in.

With night vision, the vision range isn't monotonous, it has a big dip in the middle.

**Comment by kevingranade** [comment] 2016-04-29 16:02
It's working as intended, you can easily have enough ambient light to spoil
your night vision without having enough light to properly see by.

I wouldn't object to the function being adjusted so that the dip isn't
quite so big.

This particular case is tricky, because stepping through that threshold
makes the light level change a great deal. Options:
Print a message if the light level changes a lot from one turn to the next.
Use the average light level of adjacent/nearby squares for the light level
scaling instead of just the square the player is on.
Use the light level of the seen share instead of light level at player
location (possibly expensive/invasive).

**Comment by Leland** [comment] 2017-05-24 00:23
Closing due to lack of active discussion.

**Closed by Leland** 2017-05-24 00:23 UTC
Labels: Enhancement
