### ISSUE TITLE
Cannot place a rollmat inside a tent

### ISSUE THREAD

**Issue by nopenoperson** [CleverRaven/Cataclysm-DDA#62852] opened 2022-12-24 09:03 UTC
### Describe the bug

i get a "cant place rollmat there" message when i try it  inside a tent.

### Steps to reproduce

bionic sniper start, set up tent, try  the use action on rollmat.

### Expected behavior

i expect to be able to place an unrolled rollmat inside of a tent

### Screenshots

![tenting](https://user-images.githubusercontent.com/75625092/209428347-68496e0a-6b6e-4a01-b0d8-8e4e4fe8b953.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.1256 (1903)
- Game Version: 622e847 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by nopenoperson** [comment] 2022-12-24 09:06
this is really wierd because i tried it somewhere else and it worked fine
![works now](https://user-images.githubusercontent.com/75625092/209428824-9751ead1-26fa-4bb5-86c4-5981ad168515.png)

**Comment by Night-Pryanik** [comment] 2022-12-24 09:28
Duplicate of #26638.

**Closed by Night-Pryanik** 2022-12-24 09:28 UTC
Labels: (S1 - Need confirmation)
