### ISSUE TITLE
Recharging station keeps recharging batteries even when turned off

### ISSUE THREAD

**Issue by GadekMaciej** [CleverRaven/Cataclysm-DDA#50980] opened 2021-08-22 07:50 UTC
### Describe the bug

Currently recharging station that is attached to a vechicle keeps using its power source to recharge batteries even if player turns it off.

### Steps To Reproduce

1.Spawn a vechicle;
2.attach recharging station;
3.put empty battery on the same tile as recharging station (just if you wanted to charge it in game)
4.check if the charger is turned off (you want it turned off to replicate the bug)
5.watch batteries being charged and car battery being drained despite recharging station being offline

### Expected behavior

When recharging station is turned off, it doesn't recharge batteries and it doesn't drain car's power source (car battery).

### Versions and configuration

- OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
- Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
- Graphics version: [Tiles or Terminal]
- Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
- Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by ferociousdork** [comment] 2021-08-22 09:09
Confirmed. This check is the problem:
https://github.com/CleverRaven/Cataclysm-DDA/blob/8051d7d8ca05fd1b2ace9ca695f6ef04c476fcf7/src/map.cpp#L4576

Since the recharging station does not have this flag, it does not need to be enabled to work.

I'll create a fix for this.

**Closed** 2021-08-27 23:29 UTC
Labels: <Bug>, Vehicles, Items: Battery / UPS
