### ISSUE TITLE
Game crahses when I try to start a fire

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#30650] opened 2019-05-19 10:56 UTC
# Describe the bug
I start a fire. Game crashes.

# Steps To Reproduce
1. Load attached save.
2. Start a fire in a braizer next to you.

# Expected behavior
I expect the game not to crash.

# Versions and configuration
 - OS: Windows 10
 - Game Version: build 9004
 - Graphics version: Tiles
 - Mods loaded: just my personal mini-mod that never caused any problems

# Additional context
I had the exact same issue back when wood ash weight was rebalanced. But it was fixed later on. I have no idea why is the game crashing now.

[Highgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194996/Highgate.zip)

[Grimwulf_mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194995/Grimwulf_mod.zip)

**Comment by neitsa** [comment] 2019-05-19 12:23
I can't reproduce with or without the mod.

* Load save
* Player <kbd>i</kbd>nventory.
* Pick lighter (<kbd>P</kbd>).
* <kbd>a</kbd>ctivate lighter
* Choose brazier (right, next to player)

![image](https://user-images.githubusercontent.com/4538670/57982135-7ec7d880-7a41-11e9-9504-4637c35353c9.png)

![image](https://user-images.githubusercontent.com/4538670/57982142-943d0280-7a41-11e9-9348-2b92fa561080.png)

**Comment by halfahermit** [comment] 2019-05-19 13:01
I can reproduce this crash by starting the fire with 'e'xamine

**Comment by ZhilkinSerg** [comment] 2019-05-19 13:19
Shoudl be fixed in #30648.

**Closed by ZhilkinSerg** 2019-05-19 13:19 UTC

**Comment by dom4op** [comment] 2019-05-19 14:34
Updating to 9006 helped, thank you
