### ISSUE TITLE
Segmentation fault on digging up half burnt hickory tree

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#32846] opened 2019-08-02 12:33 UTC
# Describe the bug
Segmentation fault appears when digging up half burnt hickory tree.

# Steps To Reproduce
1. Light up a hickory tree.
2. Wait until the fire is extinguished by rain.
3. (e)xamine the tree
4. (e)xamine the hickory root produced

# Expected behavior
Hickory root is either produced or not produced, without segmentation fault.

# Screenshots
Screenshots will be provided on demand.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6097-gdbd440d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    sees-player icon, +attitude [sees_player],
    Mutant NPCs [mutant_npcs]

# Additional context
- crash log
    CRASH LOG FILE: config/crash.log
    VERSION: 0.D-6097-gdbd440d
    TYPE: Signal
    MESSAGE: SIGSEGV: Segmentation fault
    STACK TRACE:
        @0x59B845[cataclysm-tiles.exe+0x19B845]
        @0x59C312[cataclysm-tiles.exe+0x19C312]
        SMPEG_error+0x4B034@0xF333A0[cataclysm-tiles.exe+0xB333A0]
        _C_specific_handler+0x98@0x7FF94EC98048[msvcrt.dll+0x28048]
        _chkstk+0x11F@0x7FF950AA119F[ntdll.dll+0xA119F]
        RtlRaiseException+0x399@0x7FF950A6A229[ntdll.dll+0x6A229]
        KiUserExceptionDispatcher+0x2E@0x7FF950A9FE0E[ntdll.dll+0x9FE0E]
        @0x6BE8E8[cataclysm-tiles.exe+0x2BE8E8]
        @0x6BF38E[cataclysm-tiles.exe+0x2BF38E]
        @0x6E49E0[cataclysm-tiles.exe+0x2E49E0]
        @0x6BD3F7[cataclysm-tiles.exe+0x2BD3F7]
        IMG_LoadWEBP_RW+0x57A9F8@0x159FC08[cataclysm-tiles.exe+0x119FC08]
        @0x4013ED[cataclysm-tiles.exe+0x13ED]
        @0x4014FB[cataclysm-tiles.exe+0x14FB]
        BaseThreadInitThunk+0x14@0x7FF94F217BD4[KERNEL32.DLL+0x17BD4]
        RtlUserThreadStart+0x21@0x7FF950A6CE71[ntdll.dll+0x6CE71]

- Crash log & debug log:
    [crash_and_debug_log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3461191/crash_and_debug_log.zip)

- Save game file:
    [Blackops.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3461194/Blackops.zip)

- Apologies
    I have not test the case of extinguishing the fire by fire extinguisher, therefore whether fire extinguisher causes the bug is unknown. Also, my native language is not English, please forgive any language mistake I have made.

**Comment by perryprog** [comment] 2019-08-02 17:35
I can not reproduce this, although I am testing it after the merge of #32851. My guess is that fixed it, unless I'm interpreting your STR incorrectly.

**Comment by NEONZARIN** [comment] 2019-08-02 19:32
![image](https://user-images.githubusercontent.com/16442992/62394175-1afb7900-b575-11e9-8050-d6e3c02d40ee.png)

When trying to sell NPC items
```CRASH LOG FILE: config/crash.log
VERSION: 0.D-6102-g0ebbba3
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x59B845[cataclysm-tiles.exe+0x19B845]
    @0x59C312[cataclysm-tiles.exe+0x19C312]
    SMPEG_error+0x4B034@0xF320C0[cataclysm-tiles.exe+0xB320C0]
    _C_specific_handler+0x9C@0x76D77B58[ntdll.dll+0x17B58]
    RtlDecodePointer+0xAD@0x76D88BBD[ntdll.dll+0x28BBD]
    RtlUnwindEx+0xBBF@0x76D7875F[ntdll.dll+0x1875F]
    KiUserExceptionDispatcher+0x2E@0x76DAD348[ntdll.dll+0x4D348]
    IMG_LoadWEBP_RW+0x299943@0x12BD873[cataclysm-tiles.exe+0xEBD873]
    @0xB5A73E[cataclysm-tiles.exe+0x75A73E]
    @0xB5F24D[cataclysm-tiles.exe+0x75F24D]
    @0xB50217[cataclysm-tiles.exe+0x750217]
    @0xB2F945[cataclysm-tiles.exe+0x72F945]
    @0xB4B01A[cataclysm-tiles.exe+0x74B01A]
    @0xB4BCD6[cataclysm-tiles.exe+0x74BCD6]
    @0xB4E0C8[cataclysm-tiles.exe+0x74E0C8]
    @0x6E1E36[cataclysm-tiles.exe+0x2E1E36]
    @0x6BD3F7[cataclysm-tiles.exe+0x2BD3F7]
    IMG_LoadWEBP_RW+0x57AAE8@0x159EA18[cataclysm-tiles.exe+0x119EA18]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x76B559ED[kernel32.dll+0x159ED]
    RtlUserThreadStart+0x21@0x76D8B371[ntdll.dll+0x2B371]
```

**Comment by cozardi** [comment] 2019-08-02 20:39
Not sure if related, also a segfault crash when talking to an NPC using the examine function or trying to open the vehicle menu (while driving it), also using the [e]xamine key. Uploading the save and crash&debug logs from both crashes along with the save file, to get the car crash (no pun intended) simply press e as soon as the save loads. To get the NPC crash, use ^ to stop driving and talk to the NPC using the examine function. 

If not related I can open a different issue.

Save file: 
[East Blythe.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3462842/East.Blythe.zip)

Crash and debug logs: 
[auxfiles.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3462840/auxfiles.zip)

**Comment by perryprog** [comment] 2019-08-02 21:10
I can't reproduce what either of you describe (@NEONZARIN and @cozardi). You are on the latest master commit, correct?

**Comment by cozardi** [comment] 2019-08-02 23:42
Yeah, latest update, just tested it on version 0.D-6102-g0ebbba3

**Comment by perryprog** [comment] 2019-08-03 00:35
I must be missing something. On [`0b8fac6`](https://github.com/CleverRaven/Cataclysm-DDA/commit/0b8fac644c3f80d411a2acf93221e51adf6f40a2) I get the version `0.D-6116-g0b8fac644c`.

**Comment by ZhilkinSerg** [comment] 2019-08-09 09:40
Original issue should be fixed now.

For any issue in the comments please open a separate issue if you still experience them.

**Closed by ZhilkinSerg** 2019-08-09 09:40 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Fields / Furniture / Terrain / Traps
