### ISSUE TITLE
Drop in a large amount

### ISSUE THREAD

**Issue by kr33man** [CleverRaven/Cataclysm-DDA#36642] opened 2020-01-02 15:47 UTC
When drop a large number of items through the advanced inventory, the game crashes with an error.

In my case, the departure was in the following steps:
1. 28 Kevlar plates in inventory
2. Open advanced inventory manager
3. Move the plates to any tile with the key combination SIFT + M

Further, instead of move, the game freezes and crashes.
P.S. The same plates, when drop through a simple inventory, only 2 units are drop out per once.

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10968-gfe0e3de [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Icecoon's Arsenal [ew_pack],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Makeshift Items Mod [makeshift],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    No name () [],
    Arcana and Magic Items [Arcana],
    No name () [],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    EZ-Mode Medical [fast_healing],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No name () [],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Prevent Zombie Revivication [no_reviving_zombies],
    Classic Roguelike Classes [RL_Classes],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Bionic Slots [cbm_slots],
    Simplified Nutrition [novitamins],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4016363/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4016365/debug.log)
Save game: 
[Iggdrasil.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4016400/Iggdrasil.zip)
Old save game:
[manual_backup.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4016410/manual_backup.zip)

**Comment by Zireael07** [comment] 2020-01-02 15:53
duplicate of #36554

**Closed** 2020-01-02 16:01 UTC
Labels: (S3 - Duplicate), <Bug>, <Crash / Freeze>
