### ISSUE TITLE
Starting date test failure, at random.

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#67629] opened 2023-08-13 00:37 UTC
### Describe the bug

```
Random_scenario_dates
(~[slow] ~[.],starting_items)=>   Random year
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/start_date_test.cpp:169
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/start_date_test.cpp:181: FAILED:
(~[slow] ~[.],starting_items)=>   CHECK( calendar::start_of_game <= calendar::turn_zero + first_day_of_summer + calendar::year_length() * 10 + default_start_hour )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   time_point( 32757[120](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5843807567/job/15846265697?pr=67626#step:16:121)0 ) [Year 11, Summer, day 61 8:00:00 AM]
(~[slow] ~[.],starting_items)=>   <=
(~[slow] ~[.],starting_items)=>   time_point( 322387200 ) [Year 11, Summer, day 1 8:00:00 AM]
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   Game started on turn 327571200
(~[slow] ~[.],starting_items)=>
```

### Attach save file

NA

### Steps to reproduce

Run CI sometimes this will happen

### Expected behavior

This looks like it might be a random failure that could be pruned back.  Could be wrong though.

### Versions and configuration

NA

**Comment by ZhilkinSerg** [comment] 2023-08-13 08:05
Duplicate of #67596

**Closed** 2023-08-13 10:19 UTC
Labels: (S2 - Confirmed), Code: Tests
