### ISSUE TITLE
Crash after loading screen

### ISSUE THREAD

**Issue by cirops** [CleverRaven/Cataclysm-DDA#40910] opened 2020-05-28 05:00 UTC
# Describe the bug

After downloading the latest build (10702), the game crashes after loading stuff and right before jumping you into the game.

# Steps To Reproduce

1. Create default world.
2. Start as a problematic Scenario/Profession (E.g hospital start).
3. Start game and observe crash.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2570-gb8bc6f1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

First I've created the world with Aftershock, Blaze and DinoMod, started as a foodperson and the game went normally. (I alt+f4'd of that game, not sure if relevant). 
Then, I've decided to give a Hospital start a go, started as Bionic Patient and got a crash after loading screen. Tried this a few more times without any mods, with different hospital starts and with the infected scenario and they all crashed.
Then, tried with evacuee start and helicopter crash and they worked normally.

Seems to be something related to towns. 

Attached are logs, and a save with a working helicopter start. You can just try to create a new character on that world with a hospital start to observe the crash.

[bug-save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4693346/bug-save.zip)

**Comment by anothersimulacrum** [comment] 2020-05-28 05:05
Thanks for the bug report! Judging by the crash log, this is a duplicate of #40899

**Closed** 2020-05-29 17:29 UTC
Labels: (S3 - Duplicate)
