### ISSUE TITLE
Attempting to activate e-ink reader crashes the game

### ISSUE THREAD

**Issue by mongeaujeremy2** [CleverRaven/Cataclysm-DDA#76131] opened 2024-09-02 00:47 UTC
### Describe the bug

Following the update that changes e-ink reader to utilize an internal battery instead of replaceable batteries, attempting to activate my old e-ink reader causes the game to crash. Picking up and wielding the object have no issue, however when you activate the item the game then crashes with error message "Bad optional access".

### Attach save file

[Possum Hills-trimmed.tar.gz](https://github.com/user-attachments/files/16831072/Possum.Hills-trimmed.tar.gz)

### Steps to reproduce

1. Pick up or be near the e-ink reader (on save the e-ink reader is in the passenger seat)
2. Activate the e-ink reader
3. The game will crash

### Expected behavior

I expected to be able to activate the e-ink reader in order to plug it in to charge. Before the update this was how it worked, however I think the change caused an issue as the e-ink reader was used prior with a dead battery contained inside of it (which falls out when picked up).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 9dfbd30 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[config.zip](https://github.com/user-attachments/files/16831118/config.zip)
Save is attached in "attach save file" section

**Comment by RenechCDDA** [comment] 2024-09-02 02:03
Duplicate of #76110

**Closed by RenechCDDA** 2024-09-02 02:03 UTC
Labels: (S1 - Need confirmation)
