### ISSUE TITLE
Constantly crashing, cannot progress

### ISSUE THREAD

**Issue by AkdoolTheSlimy** [CleverRaven/Cataclysm-DDA#69407] opened 2023-11-15 08:53 UTC
### Describe the bug

It started with crashing while inserting items, so the problem might've existed for a while, but it was playable. Now, I have reached a point where I cannot progress without crashing and losing progress after anywhere between a few seconds and a couple minutes of IG time. I noticed it while I was trying to drive around. Traveling to the northeast crashed me, and then driving south crashed me too. Then, I went to test if it'll crash while I'm traveling on foot, and I didn't get that far, because after I accidentally dropped my gun into the car seat, I crashed while picking it up. I don't know what the issue is, but something definitely broke in my save.

### Attach save file

[The Pale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13362309/The.Pale-trimmed.tar.gz)

### Steps to reproduce

Just load my save and try driving somewhere. It may (or may not) take a minute, but it should consistently crash.

### Expected behavior

I expect that the game would be playable without crash-locking me.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: b525b7a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13362335/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13362336/debug.log)

**Comment by RenechCDDA** [comment] 2023-11-15 09:12
Duplicate of #69396

**Closed by RenechCDDA** 2023-11-15 09:12 UTC
Labels: (S1 - Need confirmation)
