### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Chrono12777** [CleverRaven/Cataclysm-DDA#65674] opened 2023-05-16 10:10 UTC
### Describe the bug

I try to start game one way or another even disabling all mods,minus the base and it gives a .json error on body parts 

### Attach save file

 DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/json/body_parts.json:374:18: Invalid or misplaced field name "accusative" in JSON data

    "name": "left arm",
    "name_multiple": "arms",
    "accusative":
                 ^
                  { "ctxt": "bodypart_accusative", "str": "left arm" },
    "accusative_multiple": { "ctxt": "bodypart_accusative", "str": "arms" },
    "heading": "l. arm",

 FUNCTION : void JsonObject::error_skipped_members(const std::vector<size_t> &) const
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/flexbuffer_json.cpp
 LINE     : 333
 VERSION  : a5245ca

### Steps to reproduce

1.try to start any game 
2.create your world 
3.and just when starting it will give you the error .json 

### Expected behavior

ideally i just hoped i could create my world and play 

### Screenshots

![Screenshot_20230516-052410_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/130151690/54c61766-3ed5-473e-9234-b5372e93130d)

### Versions and configuration

-OS (Galaxy A30 SM-A305GT)
-Game version (a5245ca)
-Graphics Version (Retrodays)
-Ingame Languaje (Spanish)

### Additional context

crash: the error seems to be reproduced by the fola json bodies always giving error when starting any game with several different configurations, the experimental version worked before trying to update it to the most recent

**Comment by RenechCDDA** [comment] 2023-05-16 10:17
Duplicate of #65162

**Closed by RenechCDDA** 2023-05-16 10:17 UTC
Labels: (S1 - Need confirmation)
