### ISSUE TITLE
Reach attacks don't work with martial arts techniques

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#62622] opened 2022-12-08 04:25 UTC
### Describe the bug

If you use any style that's intended for reach attacks (let's use Sōjutsu for example), then apparently its normal techniques don't trigger if you attack things with the "f" key at point blank range or over 1 square. Techniques do seem to trigger if you attack by bump attacking though, but then the benefit of having a reach weapon is lost.

### Steps to reproduce

1. Make a player with 4/4 melee, Sōjutsu and any spear (say, wooden spear).
2. Attack an enemy with "f" and observe that neither of the on-hit techniques ever trigger in melee range or over a square.
3. Attack an enemy by bump attacking and observe that techniques do trigger then, but you're restricted to attacking in melee range.

### Expected behavior

Techniques should probably trigger for reach weapons when you attack over a square. If this is considered to be too powerful, then it needs to be stated somewhere. Regardless I still expect techniques to trigger if I attack with f in melee range.

### Versions and configuration

- Current experimental

**Comment by Night-Pryanik** [comment] 2022-12-09 05:11
Duplicate of #59585.

**Closed by Night-Pryanik** 2022-12-09 05:11 UTC
Labels: (S1 - Need confirmation)
