### ISSUE TITLE
Golden Years, failure to generate a starting location

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62508] opened 2022-12-01 03:44 UTC
### Describe the bug

City size 12, spacing 6. Successfully generated on third attempt.

### Steps to reproduce

play now *shrug*

### Expected behavior

users to report failures and their world settings? 

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12607-ge1d367543b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Night-Pryanik** [comment] 2022-12-01 07:48
Duplicate of #35376.

**Closed by Night-Pryanik** 2022-12-01 07:48 UTC
Labels: (S1 - Need confirmation)
