### ISSUE TITLE
NPC crash

### ISSUE THREAD

**Issue by DarthbobIII** [CleverRaven/Cataclysm-DDA#30674] opened 2019-05-19 23:23 UTC
# Describe the bug

DEBUG    : Requested non-existing faction 'your_followers'
 
 FUNCTION : faction* faction_manager::get(const faction_id&)
 FILE     : src/faction.cpp
 LINE     : 310

# Steps To Reproduce

1. Successfully recruit the starting NPC

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3230-g145b0b6
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Fosheze** [comment] 2019-05-19 23:29
Can confirm. Loading any faction seems to cause a crash. I attempted to start a refugee center save and it immediately crashed with the following message. This also happened with a bandit faction in a city an the faction in the new hubs.

 DEBUG    : Requested non-existing faction 'free_merchants'
 
 FUNCTION : faction* faction_manager::get(const faction_id&)
 FILE     : src/faction.cpp
 LINE     : 310

**Comment by DarthbobIII** [comment] 2019-05-19 23:30
Yes. I also had a crash with "hells_raiders" or something similar.

**Comment by Fosheze** [comment] 2019-05-19 23:54
I just did a quick check and everything seems to work fine in Tiles x64 version 9004. Any version after that I haven't been able to load the refugee center.

**Comment by DarthbobIII** [comment] 2019-05-20 00:19
Can confirm. Build 9004 allows for recruitment without crashing.

**Comment by Night-Pryanik** [comment] 2019-05-20 06:28
It's a _crash_ with exiting to desktop or it still allows you to continue playing after pressing space?

**Comment by DarthbobIII** [comment] 2019-05-20 07:08
crash with exit to desktop.

**Comment by alexanderbk1** [comment] 2019-05-20 20:23
This is happening to me too, I am using build 9006

I noticed this problem because I wanted to reproduce another issue related to NPCs, so i created a new world and character and gave myself all the debug mutations, then I tried to "OBEY ME!" command a fresh NPC and the game crashed, I have repeated this process 3 times and it cosistently crashes.

**Comment by Throwaway-name** [comment] 2019-05-21 03:51
Intermittent crash after trading with the refugee center merchant in build 9002.

**Comment by mlangsdorf** [comment] 2019-05-21 14:10
does #30865 fix this?

**Comment by DarthbobIII** [comment] 2019-05-21 18:47
Successfully recruited initial NPC  without crash in build 9020. It must be fixed?

**Comment by ZhilkinSerg** [comment] 2019-05-21 19:12
It was fixed in #30685

**Closed by ZhilkinSerg** 2019-05-21 19:12 UTC
Labels: <Crash / Freeze>, NPC / Factions
