### ISSUE TITLE
Trait "Rigid Table Manners" gives debuff when using table+seat in RV

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#47949] opened 2021-03-09 00:26 UTC
Trait "Rigid Table Manners" gave a debuff after the player ate sitting in luxury RV "Leather Seat" located in front of the "Table", both furniture pieces are attached to the luxury RV frame, the RV is unaltered by me, spawned undamaged. I ate roasted acorns, eating them in other chair+table set up worked as expected (mood buff for eating at the table).

I think that the seat is not considered to be a chair, and I suggest that it should be considered a chair, so the setup "seat+table" should work the same as "chair+table". Since "seat+table" setup spawns in luxury RV, I expect it to be as comfortable or even better than the "chair+table" setup.

# Steps To Reproduce

1. Give the player a "Rigid Table Manners" trait.
2. Find / construct a vehicle with a table and a leather seat adjacent to each other.
3. Sit on the chair, eat food.
4. Debuff "Ate like an animal" appears.

# Expected behavior

"table + any_seat" mounted on a vehicle frame should work the same as "table + chair" for eating, giving a positive debuff for a player with a "Rigid Table Manners" trait.

# Screenshots

https://i.imgur.com/s0HvMM0.png

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-9970-g6425fc431b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by wapcaplet** [comment] 2021-03-09 03:05
Thanks for reporting. This looks like a duplicate of issue #45240

**Closed by wapcaplet** 2021-03-09 03:05 UTC
