### ISSUE TITLE
Cars with leaky tanks spawn with gas/diesel, lose it instantly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16326] opened 2016-04-21 22:22 UTC
Leaking speed is quite high, meaning that any car with a tank damaged enough to leak should no longer have any fuel in it.

**Comment by Labtop-215** [comment] 2016-04-22 22:01
It generally dosn't anyway by the time you get too it if the tank is leaky enough.  I think it's a rather interesting side effect, that there is a pool of gasoline on the ground beside the vehicle.

Like the vehicle was stopped, then it's tank was damaged some way.

**Comment by kevingranade** [comment] 2017-03-26 21:02
Issue is a little unclear, is the problem that you can come upon a car with a leak n days after the cataclysm and it still has fuel in it?

**Comment by Leland** [comment] 2017-05-08 14:25
Closing this – we're a year out at this point, and if I'm reading this right, the issue is regarding the fact that leaky tanks on spawn no longer have fuel in them by the time the player reaches them. Not an issue in my opinion. If anyone feels differently, feel free to leave a comment and I can reopen, or just create a new issue.

**Closed by Leland** 2017-05-08 14:25 UTC
Labels: Balance, Suggestion (Discuss), Vehicle
