### ISSUE TITLE
Segfault while walking around the Refugee Center

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#44410] opened 2020-09-25 05:45 UTC
# Describe the bug

I was just walking around, not very close to any NPCs, but the stack trace suggests the crash happened during an NPC action somewhere.

# Steps To Reproduce

Unknown. Walk around the Refugee Center?

# Expected behavior

Game doesn't crash

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

    debug_write_backtrace(std::ostream&)
    ??:?
    init_crash_handlers()
    ??:?
    init_crash_handlers()
    ??:?
    ??
    ??:0
    item::damage_resist(damage_type, bool) const
    ??:?
    item::item(item const&)
    ??:?
    std::__cxx11::list<item, std::allocator<item> >::list(std::__cxx11::list<item, std::allocator<item> > const&)
    ??:?
    item::damage_resist(damage_type, bool) const
    ??:?
    item::use_amount(string_id<itype> const&, int&, std::__cxx11::list<item, std::allocator<item> >&, std::function<bool (item const&)> const&)
    ??:?
    item::operator=(item const&)
    ??:?
    npc::wield(item&)
    ??:?
    npc::wield_better_weapon()
    ??:?
    npc::move_pause()
    ??:?
    npc::execute_action(npc_action)
    ??:?
    npc::move()
    ??:?
    game::monmove()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?

**Comment by ZhilkinSerg** [comment] 2020-09-25 07:51
Duplicate of #44196

**Closed by ZhilkinSerg** 2020-09-25 07:51 UTC

**Comment by sparr** [comment] 2020-09-28 19:49
Truncated more verbose stack trace:

```
#0  0x00007fb8cb91d615 in raise () from /usr/lib/libc.so.6
#1  0x00007fb8cb906862 in abort () from /usr/lib/libc.so.6
#2  0x00005636deb00129 in signal_handler (sig=<optimized out>) at src/crash.cpp:119
#3  <signal handler called>
#4  item_pocket::favorite_settings::favorite_settings (this=0x563705e4e540) at src/item_pocket.h:75
#5  0x00005636dee5f13f in item_pocket::item_pocket (this=0x563705e4e540) at src/item_pocket.h:38
#6  0x00005636dee5f127 in __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&> (
    this=<optimized out>, __p=0x563705e4e540, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/ext/new_allocator.h:150
#7  0x00005636dee5f060 in std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&> (
    __a=..., __p=0x563705e60, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/alloc_traits.h:512
#8  0x00005636dee5efa1 in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&> (
    this=<optimized out>, __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:637
#9  0x00005636dee5eecd in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&> (this=0x5636ff270268, 
    __position=
    {settings = {priority_rating = 1, item_whitelist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1974879353528, <No data fields>}, item_blacklist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>}, category_whitelist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1974879353528, <No data fields>}, category_blacklist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}}, _saved_type = -13673952, _saved_sealed = 54, data = 0x5636ff2f5a10, contents = std::__cxx11::list = {[0] = <error reading variable>, __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1911
#10 0x00005636dee5ee89 in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&> (this=0x5636ff270268, 
    __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1227
#11 0x00005636dee5ed33 in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> > (this=0x5636ff270268, __first=<error reading variable: Cannot access memory at address 0x563705e50>, __last=
    {settings = {priority_rating = 3, item_whitelist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1974881423834, <No data fields>}, item_blacklist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>}, category_whitelist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1974881423834, <No data fields>}, category_blacklist = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}}, _saved_type = -13624880, _saved_sealed = 54, data = 0x5636ff3019c0, contents = std::__cxx11::list = {[0] = <error reading variable>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:1840
#12 0x00005636dee5ec47 in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::list (this=0x5636ff270268, 
    __x=std::__cxx11::list = {...}) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/stl_list.h:738
```
