### ISSUE TITLE
Water freezes over by the time I am done thawing it

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25129] opened 2018-08-25 14:29 UTC
**Describe the bug**  
I have a jerry can of clean water (35 units to be exact), and it takes a very long time to thaw it. By the time it is done it is already frozen again, meaning I cant thaw it at all during night. 

**To Reproduce**  
1 Fill up jerry can,
2 have it freeze 
3 try to heat it up with a hotplate(Im using a kitchen unit)

**Expected behavior**  
The water should be at least cold when done, if not hot.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [from the main menu, e.g. 0.C-31017-gac3885]
 - Graphics version [Tiles]
 - Mods loaded [filthy clothes, NPC traits, PK Rebalanced]

**Additional context**

**Comment by ymber** [comment] 2018-08-25 14:35
Duplicate of #24914

**Comment by Orange01gaming** [comment] 2018-08-25 14:47
It is not 5-10 minutes after heating, it is instantaneous, I don't even have time to take one sip.

**Comment by Night-Pryanik** [comment] 2018-08-25 15:05
I think the culprit is the same in both issues. The fix is almost there.

**Closed by Night-Pryanik** 2018-08-25 15:05 UTC
