### ISSUE TITLE
 maximum weariness?

### ISSUE THREAD

**Issue by Zigoos** [CleverRaven/Cataclysm-DDA#46323] opened 2020-12-25 20:34 UTC
**# Is your feature request related to a problem? Please describe.**
Our favorite "weariness" is still very annoying in endgame.

**# Describe the solution you'd like**
Add modifiers for maximum weariness. Bind it to athletic skill and add a small amount of EXP for athletics every time the character gets weariness. This skill can reflect the overall training of the character. And this will remove questions about why strength and agility do not increase over time.

**# Describe alternatives you've considered**
Create a formula for calculating the maximum weariness from several skills "dodge","melee","athletics","strength", "dexterity". Something like
maxWeariness=athletics+(Strength+Dexterity)/2+(dodge+melee)/2
I don't know, I think you'll do better.

**Comment by Maddremor** [comment] 2020-12-25 20:38
One problem is that a skill does not decrease over time, which would be the case for physical conditioning without the exercise to maintain it.

**Comment by anothersimulacrum** [comment] 2020-12-25 20:39
Duplicate of #44370

This doesn't really add anything new from that.

**Closed by anothersimulacrum** 2020-12-25 20:39 UTC
