### ISSUE TITLE
Game won't run

### ISSUE THREAD

**Issue by dodzy** [CleverRaven/Cataclysm-DDA#14291] opened 2015-12-03 15:50 UTC
Starting with release 3989 ( http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/ ) the game won't run, in Windows Task manager i see 3 executables running (despite only starting one) and no window opens up.

I'm using Windows 7 64 bit

**Comment by dodzy** [comment] 2015-12-03 16:12
figured it out, the problem was Avast.

adding cataclysm folder to avast exclusion list did the trick for me, also avast had update pending which may possibly have solved this issue anyway according to the forum thread below:

http://smf.cataclysmdda.com/index.php?topic=11634.0

Related issue: #14018

**Comment by remyroy** [comment] 2015-12-03 19:08
This is a duplicate of #14018 and can be closed.

**Closed** 2015-12-03 19:26 UTC
