### ISSUE TITLE
Bottles of disinfectant being an edible

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23531] opened 2018-04-18 07:21 UTC
Game version: 0.C-27399-ga98c6b1
Also confirmed to happen in: 0.C-27468-g1780644

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

Also confirmed to happen in a fresh world with only CDDA core active in the modlist.

### Expected behavior
One can 'a'ctivate bottles of disinfectant straight from activation menu. Additionally, one cannot 'E'at/drink the disinfectant to have it work (though maybe it should be possible to drink it with a warning, like how it is with bleach).

### Actual behavior
One has to open the inventory, scroll to find bottle of disinfectant, choose it and then activate it from its examination window. Bottle of disinfectant isn't shown in 'a'ctivation menu. To activate bottle of disinfectant quickly, player is expected to 'E'at it, which opens wound treatment menu.

### Steps to reproduce the behavior
Get hurt, attempt to use a bottle of disinfectant.

**Comment by gastamper** [comment] 2018-04-18 23:28
I am able to 'a'ctivate and then select bottles of disinfectant without issue; the screenshot below is the result of my pressing the 'a' key, and the bottle of disinfectant in my inventory is the first option presented.  Can you replicate this without mods?  It doesn't seem to be an issue in the base game.
![x](https://user-images.githubusercontent.com/20960555/38963179-9f42ecf2-433e-11e8-9052-586354d7ae96.png)

**Comment by Night-Pryanik** [comment] 2018-04-20 10:41
This also happens with hydrogen peroxide because they both are liquid meds stored in some container, and `firstaid_finish` activity only checks for non-contained items.

**Comment by Leland** [comment] 2018-04-20 14:32
Duplicate of #23014.

@FulcrumA please add all new, relevant info from this thread to that issue, please!

**Closed by Leland** 2018-04-20 14:32 UTC
Labels: <Enhancement / Feature>, Items / Item Actions
