### ISSUE TITLE
Turret mount can't find limb

### ISSUE THREAD

**Issue by FlyingVolvo** [CleverRaven/Cataclysm-DDA#42352] opened 2020-07-21 20:58 UTC
# Describe the bug

When firing anything attached to a turret mount an error message occurs.

# Steps To Reproduce
1. Spawn a vehicle with a turret mount.

2. Reload the turret, if applicable,

3. Attempt to fire the turret from the driver seat.

# Expected behavior
The weapon to fire and not produce a error.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-4309-gb81636e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]

# Additional context

N/A

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4956181/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4956182/crash.log)
Save file can be provided upon request as it's >700 megabytes and well over the size limit of <10 megabytes on Github.

**Comment by Fris0uman** [comment] 2020-07-21 21:00
"Solution" Is to find where in the code the fake turret NPC is made and use `set_body()` to give it a body, with at least an arm in it, but a full body would do.

**Comment by Night-Pryanik** [comment] 2020-07-22 03:02
Duplicate of 42325.

**Closed by Night-Pryanik** 2020-07-22 03:02 UTC
