### ISSUE TITLE
Segfault when attempting to construct the saltwater pipe expansion for the fabrication workshop

### ISSUE THREAD

**Issue by Grace-system** [CleverRaven/Cataclysm-DDA#68556] opened 2023-10-08 07:11 UTC
### Describe the bug

When attempting to construct the saltwater pipe expansion for the fabrication workshop, the screen saying how many additional sessions are required (9, in this case) appears. If the "yes" option is selected, the game segfaults.

### Attach save file

[Amherstdale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12839982/Amherstdale.zip)

### Steps to reproduce

1. Interact with bulletin board
2. Select the salt water pipe expansion under the fabrication workshop
3. Select "yes" when the dialogue appears 

### Expected behavior

I would expect the game to not crash, and for the project to behave as other faction camp projects do.

### Screenshots

N/A (I think?)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: fed583f [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Generic Guns [generic_guns],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12839997/config.zip)

**Comment by PatrikLundell** [comment] 2023-10-08 10:31
Duplicate of #66318).

At some time somebody change the interface and didn't verify that it didn't break anything.

**Comment by Maleclypse** [comment] 2023-10-22 17:16
Duplicate and fixed

**Closed by Maleclypse** 2023-10-22 17:16 UTC
Labels: (S1 - Need confirmation)
