### ISSUE TITLE
Vehicle not found

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#17583] opened 2016-07-07 08:33 UTC
get this message when install storage battery in the car for the first time, installation fails. Second attempt was successful, no debug messages get.
![2016-07-07 11-27-15](https://cloud.githubusercontent.com/assets/6452938/16647080/850c1044-443e-11e6-9886-0b0c052d9293.png)
![2016-07-07 11-30-55](https://cloud.githubusercontent.com/assets/6452938/16647182/0d44b1be-443f-11e6-867e-d34c51a91717.png)

**Comment by pisskop** [comment] 2016-07-07 15:47
Not sure if related, but after saving for a night a tractor I was riding refused to turn its engine on, although it still allowed me to steer.

**Comment by keyspace** [comment] 2016-12-09 12:15
Can't reproduce OP on dcafffb (latest ATM).

Tested installing storage battery into storage battery case or "just welded in", on vehicle with and without existing batteries.

OK to close?

**Comment by codemime** [comment] 2016-12-09 12:29
Closing in accordance with @keyspace's report. The related code has been changed, and the issue is probably fixed. If it's not, feel free to reopen it.

**Closed by codemime** 2016-12-09 12:29 UTC
Labels: Bug, Vehicle
