### ISSUE TITLE
Getting "Excessive error repetition detected." all the time 

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#65362] opened 2023-04-28 23:00 UTC
### Describe the bug

Whatever im doing in the save im getting the error message:
DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            Tried to use an invalid beta talker.

 FUNCTION : talker* dialogue::actor(bool) const
 FILE     : src/npctalk.cpp
 LINE     : 1799
 VERSION  : 0b9b1fa

This happens whatever I do, as long as I am near NPCs.

### Attach save file

[Dassel-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11357728/Dassel-trimmed.tar.gz)

### Steps to reproduce

1.	Load in save and character
2.	Do anything close to NPC (don’t need to be in visual range). Waiting for 2 hours as an example
3.	Get error massage

### Expected behavior

No error message

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 0b9b1fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11357747/debug.log)

**Comment by BrettDong** [comment] 2023-04-29 00:15
Duplicate of #65313.

**Closed by BrettDong** 2023-04-29 00:15 UTC
Labels: (S1 - Need confirmation)
