### ISSUE TITLE
CC BY-SA is NOT suitable for codes

### ISSUE THREAD

**Issue by Screwland** [CleverRaven/Cataclysm-DDA#18095] opened 2016-08-20 08:45 UTC
Dear all,

I found this game today, and looked source codes.

This project is licensed under a CC BY-SA 3.0.

However, All of Creative Commons licenses(except. CC0 Public Domain Dedication) are not suitable for Software(i.e. codes).
https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

This project's license text was inherited from original project, the Cataclysm https://github.com/Whales/Cataclysm 

I think that this project should change the code's license to another famous FLOSS license such as GPL, MIT or BSD,
but it's difficult Since there are a lot of authors and contibuters for this project.

I am thinking an idea, Using a later version clause[4-b (ii)] and Creative Commons Compatible License clause[4-b (iv)], 
because CC BY-SA 4.0 has one-way compatiblity with GNU GPLv3.
https://creativecommons.org/licenses/by-sa/3.0/legalcode
https://www.fsf.org/blogs/licensing/creative-commons-by-sa-4-0-declared-one-way-compatible-with-gnu-gpl-version-3

```
CC BY-SA 3.0       ->               CC BY-SA 4.0      ->     GNU GPLv3
  [Change by using later-version clause]          [Change by using Compatible License clause]
```

Is someone interested in this problem?

**Comment by illusionofchaos** [comment] 2016-08-20 17:44
There were some discussions about licensing on the forums and I can quote @kevingranade :

> [GPL is your best option for limiting the ability of people to take it proprietary.](http://smf.cataclysmdda.com/index.php?topic=3875.msg56193#msg56193)

> [NC would render the whole project NC [Non-commercial], which is unacceptable](http://smf.cataclysmdda.com/index.php?topic=10390.msg264501#msg264501)

There are also a lot of problems with GPL, such as uploading to Apple App Store and the requirement to license all derivative works under the same license. 

CC BY-SA in this case seems appropriate because it ensures attribution while allowing creation of derivative works mixed with differently-licensed code.

**Comment by WizardOfOoo** [comment] 2016-08-28 06:02
The application we are using has never been tested in court.  Nobody really knows, but Kevin is right that this is the best license for us.

**Comment by kevingranade** [comment] 2016-09-21 17:14
(Historical information) It's less that it's the best, and more that it's
the one that whales picked when we originally forked the project (
previously it was under an informal "feel free to modify" license). At that
point there were about 80 contributors and I'm confident we did a good job
of getting sign-off from them to use the license.

At this point there have been over 400 contributors to the codebase under
the current license, many of which are not reachable, including the
original developer whales, it simply does not seem feasible to perform a
relicensing campaign now.

If someone does want to try, I'd be happy to reliscense my contributions
under GPL v3 or later, and several others if there were some consensus
about it.

**Comment by mugling** [comment] 2016-09-21 17:26
> and several others if there were some consensus about it.

Has anyone tried running `git-blame * | cut -d: -f1 | sort |uniq -c` or something to that effect? Not perfect but may be indicative.

**Comment by BrettDong** [comment] 2016-12-11 14:08
Running `git ls-tree -r -z --name-only HEAD -- *.cpp *.h | xargs -0 -n1 git blame --line-porcelain HEAD | grep  "^author " | sort | uniq -c | sort -nr` works for me, and got the following result:
```
45864 author Coolthulhu
27724 author Kevin Granade
19696 author Thomas Kirsten
15861 author BevapDin
12549 author Mugling
11486 author mugling
11351 author Tommy
9940 author codemime
8835 author illi-kun
8351 author Christian Buskirk
8053 author fnord
6411 author OzoneH3
5680 author acidia
5184 author Whales
3232 author Brandon Kentel
3205 author sethsimon
2605 author GalenEvil
2368 author Clarence Risher
2102 author huxtus
2033 author KA101
1651 author DLaboratory
1571 author cib
1521 author DanmakuDan
1351 author Valuial
1350 author Vlasov Vitaly
1226 author utunnels
1174 author DavidKeaton
1165 author Ian Strachan
1113 author trinsic
1058 author Steven Wu
 966 author Lucian Poston
 922 author Oliver Jowett
 906 author Brandon Bergren
 884 author Quietust
 833 author JornVernee
 772 author WillyGalleta
 755 author Robert Sørlie
 672 author Dmitry Serov
 617 author Piotr S. Staszewski
 574 author Octav Sandulescu
 496 author Shoes01
 478 author Chris Vickio
 476 author Rémy Roy
 473 author Anuradha Dissanayake
 464 author hitbutton
 442 author ethankaminski
 427 author Robik81
 426 author GlyphGryph
 412 author Moises Sanchez
 401 author Soyweiser
 396 author PropaneSoup
 394 author Clarence "sparr" Risher
 375 author Wuzzy
 339 author BeigeSand
 323 author Ethan "Soron" Kaminski
 303 author malhawee
 302 author Erik Abair
 291 author patternoia
 291 author Jeremy Osborne
 290 author vache
 279 author OvenBaker
 278 author Angela Graves
 276 author Christian Bielert
 263 author Alexander White
 261 author StrangerState
 253 author origamiwolf
 243 author hbnix
 242 author Rivet-the-Zombie
 241 author Daniel Beck
 238 author C0DEHERO
 237 author Matt Ammann
 225 author Pierre-David Bélanger
 224 author Frost-wood
 223 author Alexander Schnaidt
 221 author EpicOrange
 213 author ClockworkZombie
 212 author Williham Totland
 212 author Peter Lacey-Bordeaux
 201 author Kodi Arfer
 200 author Anton Burmistrov
 199 author Brett Dong
 190 author jaked122
 190 author TheDarklingWolf
 182 author HuXTUS
 175 author jcd000
 163 author Herbert Jones
 159 author Vidar Engh Skaugen
 159 author Mshock777
 157 author Maykeye
 156 author Zach Morgan
 155 author Gabriel-SE
 153 author whales
 150 author Heruedhel
 148 author 9600bauds
 146 author benjamg
 139 author John-Candlebury
 137 author gmcnew
 137 author TranquilMarmot
 135 author SeanMirrsen
 125 author hesu
 123 author Tomas Volka
 121 author Fergus Dall
 119 author Vollch
 116 author desrik
 114 author Soy
 112 author Brian Lefler
 109 author chaosvolt
 105 author zfullmer9@hotmail.com
 102 author jason.gilbert@nbed.nb.ca
 101 author Rick Luddy
 101 author NaturesWitness
  99 author Wouter van Kesteren
  97 author BrianLefler
  96 author cSep
  95 author Lorith
  94 author Charlie Nolan (FunnyMan3595)
  93 author Greg McNew
  93 author Denis Volk
  92 author Tivec
  91 author KrazyTheFox
  90 author D Anzorge
  88 author MacrosBlackD
  88 author Eric Nguyen
  84 author FunnyMan3595 (Charlie Nolan)
  84 author Benjamin Holder
  83 author macrosblackd
  82 author Chase
  80 author freezerbunny
  76 author TireExaminer
  75 author belenos-
  73 author Tyler Merta
  73 author Eric
  72 author Jeremy Apthorp
  69 author Matias Oksa
  69 author Lukasz Dobrogowski
  68 author Lap
  68 author Alex Parent
  67 author c0
  67 author Chaosvolt
  67 author Axujen
  65 author tasetase
  65 author jokermatt999
  61 author skYYman
  58 author Lain-
  57 author Stéphane Travostino
  57 author Izicata
  57 author Chris Hunt
  55 author mafagafogigante
  54 author Serhiy Zahoriya
  51 author Asmageddon
  50 author alexander white
  48 author Tom Richardson
  46 author Graywolfe813
  45 author mightyagrippa
  45 author joshuagiles
  45 author Oddbjørn Olsen
  42 author Anrock
  40 author mafagafo
  39 author Night-Pryanik
  39 author Brad Busse
  38 author Philipp Grosenick
  37 author maseck
  37 author Firestorm01X2
  37 author Cyrano7
  36 author veryinky
  36 author Voker57
  35 author Zero
  35 author Ben Gray
  34 author Matthew Pfeiffer
  33 author root
  29 author hurcan solter
  29 author Nicholas De Nova
  29 author DeadLeaves
  29 author Darkyhard
  27 author Steven Noonan
  25 author user
  24 author arcke
  23 author Rabbit
  22 author pisskop
  22 author Ozone
  22 author BurnZeZ
  21 author Livingstone
  20 author Samir Benmendil
  20 author Dustin Lacewell
  19 author falconne
  19 author Reaper
  18 author tvm
  18 author delebota
  18 author DZiral
  18 author Alex Casey
  17 author nrfowler
  17 author maltouzes
  16 author ubuntu
  16 author Vladimir Kovalenko
  16 author Snaaty
  16 author Isk1n
  16 author Daniel
  16 author Caden Depatie
  15 author orzogc
  15 author Wishbringer
  15 author Savidiy
  15 author Nick Taylor
  14 author uzername
  14 author fuchs87
  13 author abaire
  13 author Leonid Vasilev
  13 author Goron
  13 author Eric Ng(ZwodahS)
  13 author D Laboratory
  13 author Aapo Rantalainen
  12 author jc6036
  12 author Skyyrunner
  12 author Owen Diamond
  12 author Malkeus
  12 author Dylan Greer
  12 author D Lue Choy
  11 author maxmurder
  11 author Pierre-David Bélanger
  11 author Julian Snitow
  11 author Crispy6
  10 author niglow
  10 author Nick Greazaro
  10 author Karl Parakenings
  10 author JedrekD
   9 author thunderwarrior
   9 author daftfad
   9 author carnie
   9 author aspolito
   9 author PiCroft
   9 author John Candlebury
   9 author Fitz Elliott
   9 author Chezzo
   8 author ThinkInvisible
   8 author Griffinhart
   8 author DangerNoodle
   7 author unknown
   7 author oldlaptop
   7 author cryptonaut
   7 author Xantrim
   7 author Trapper John
   7 author Spencer Michaels
   7 author Siwen Yu
   7 author GiM
   7 author David Holmes
   7 author ChunkOfMeat
   6 author feo111
   6 author Raphael Sofaer
   6 author JoeKlesczewski
   6 author Joakim Kuxe Thorén
   6 author Dimensiomancer
   6 author Ben Fox-Moore
   6 author Alex Unigovsky
   5 author somerandomlogin
   5 author brezerk
   5 author alex-gh
   5 author ValidAQ
   5 author Stevensonz
   5 author NANOsoldierEnke
   5 author Hourousha
   5 author Cliffs Dover
   5 author Angular-Angel
   5 author Alice Morgan
   5 author Alexander Voikov
   4 author werty1124
   4 author Yclept Nemo
   4 author Waladil
   4 author Sven-Hendrik Haase
   4 author Nymall
   4 author Lucas A. Rosevear
   4 author Levi Kendall
   4 author Josh Richey
   4 author Greg Beck
   4 author Dave Apgar
   4 author Costin Olteanu
   4 author Adam Long
   4 author 790
   3 author beefoni
   3 author VampyreLord
   3 author Tyler Reisinger
   3 author Ted Wright
   3 author Sergio Duran
   3 author Noodle
   3 author Nasuga
   3 author Madnus
   3 author Justin Drury
   3 author Eric Seto
   3 author Ekarus Ryndren
   3 author Daniel Rempel
   3 author BorkBorkGoesTheCode
   3 author Barhandar
   3 author Andrey Egoshin
   2 author v-tl
   2 author tivec
   2 author TheFlame52
   2 author The Stick
   2 author Skyrunner
   2 author ProfoundDarkness
   2 author Matthew Heine
   2 author Mathieu Quinette
   2 author JasonNAwesome
   2 author HiggsF
   2 author Henrik Bergvin
   2 author FryCarson
   2 author FlorinTeal
   2 author Desrik
   1 author zwparchman
   1 author pipehat
   1 author keyspace
   1 author jwo7777777
   1 author jbfink
   1 author indigochill
   1 author graszka22
   1 author dlaboratory
   1 author bdragon28
   1 author antonshevyrin
   1 author aierce
   1 author admin
   1 author Zachary
   1 author TheGrifter
   1 author StraySilverFox
   1 author Reclusive-reptile
   1 author Nullsrc
   1 author Nick Owens
   1 author Nandorianen
   1 author Mitsuhiro Nakamura
   1 author KittyTristy
   1 author Karol Sobo
   1 author Jazz
   1 author Jason Gilbert
   1 author Heema
   1 author Christian Henz
   1 author Catacstone
   1 author Brandon Kime
   1 author Barry Peddycord III
   1 author Alpha16
   1 author Alexander Tesfamichael
   1 author Alex
```

(after ten minutes of CPU boiling)

**Comment by BrettDong** [comment] 2016-12-11 14:10
Note: the list above is generated within `src/` subfolder and concerns only with C/C++ source file located in `src/` subfolder.

**Comment by kevingranade** [comment] 2019-03-15 21:29
I MASSIVELY misunderstood the proposal presented in this PR.  Now that I understand it, I absolutely want to do it.

Specifically, adjust https://github.com/CleverRaven/Cataclysm-DDA/blob/master/LICENSE.txt to specify that all files under src/ and tests/ (other than Catch2) are hereby considered licensed under GPLv3 as per the CC-BY-SA license compatibility clause, and designate the creative commons foundation as the proxy for future licence compatibility issues as outlined at https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3

**Comment by mlangsdorf** [comment] 2019-03-16 00:14
I don't particularly like GPLv3, but I prefer a source license to a non-source license, so if this is the pass that gets us to a source license, let's do this.

**Comment by actual-nh** [comment] 2021-02-25 04:47
> Specifically, adjust https://github.com/CleverRaven/Cataclysm-DDA/blob/master/LICENSE.txt to specify that all files under src/ and tests/ (other than Catch2)

Others (at least for most of the files under them):

- android/
- build-scripts/
- msvc*/
- object_creator/
- pch/
- tools/
- utilities/

Possibly CMakeModules/, possibly all Makefiles, possibly all CMakeLists.txt.

> are hereby considered licensed under GPLv3 as per the CC-BY-SA license compatibility clause, and designate the creative commons foundation as the proxy for future licence compatibility issues as outlined at https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3

Strongly agreed. (Is it GPLv3, or GPLv3 or any later version?)

**Comment by hexagonrecursion** [comment] 2021-02-25 07:05
Disclaimer: I'm not a lawyer
Disclaimer: this whole license compatibility thing is completely beyond me

> CC BY-SA 3.0       ->               CC BY-SA 4.0      ->     GNU GPLv3
>   [Change by using later-version clause]          [Change by using Compatible License clause]

I'm not sure this is allowed
1. [The wiki](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3) is very specific: "This compatibility determination only applies to BY-SA 4.0 and GPLv3". Surely if there existed an escape hatch of upgrading CC BY-SA 3.0 to CC BY-SA 4.0 in order to then use the GPL compatibility they would have worded this differently.
2. [The wiki](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3) warns: "This one-way compatibility mechanism with GPLv3 is not for general use. It was designed to help solve a specific problem for those working in niche areas where content is adapted and melded with code"

**Comment by anothersimulacrum** [comment] 2021-02-25 07:34
Same disclaimers here.

The [upgrade guidelines](https://wiki.creativecommons.org/wiki/4.0_upgrade_guidelines) lay out that there may be some complications in changing license (specifically, that only some parts may be licensed under 4.0):

> Existing content:
> - Who owns the rights?
> - - If the publisher, then can relicense under 4.0 as specified above.
> - - If the contributors, then need permission to relicense. Without permission (via terms of use or otherwise), then that content remains under prior version. [If this is the case, see the section below about dealing with mixed-version content.]
> - - - A couple of options for obtaining permission to relicense:
> - - - upon upload by contributors, have a prompt box to obtain agreement to relicense previous uploads;
> - - - general outreach to contributors seeking agreement to upgrade. [Note that this is easier to do with discrete artifacts (an article, a photo) as opposed to other contributions such as comments on wikis and similar, where one person's contribution is intermixed with others.]
>
> Adaptations of existing content:
> - Who owns the rights to the original?
> - - If the publisher, then can license all rights to an adaptation under 4.0.
> - - If the contributor, then can license new contributions to an adaptation under 4.0 but original contributions remain under prior version unless express permission to upgrade is obtained.
> - - - An example of how to obtain permission to upgrade via TOU:
> - - - From CC’s own Terms of Use, Section 8(b): You hereby agree that all Content you own and voluntarily provide to CC on or through any Website or Service may be used under the terms of a Creative Commons Attribution 4.0 International license or any later version of a Creative Commons Attribution International License, is not copyrightable, or is in the public domain (such as Content you make available under CC0).

That may be why it is not mentioned there. Though I think that if a move from 3.0 to 4.0 is legal, and a move from 4.0 to GPLv3 is legal, then it is fine to do both, and the article is just trying to be extra sure there is no confusion with regards to e.g. moving directly from 3.0 to GPLv3, though the move from 3.0 to GPL is illegal.

**Comment by hexagonrecursion** [comment] 2021-02-25 08:00
> if a move from 3.0 to 4.0 is legal

Is it?

> Existing content: [...]
> If the contributors, then **need permission to relicense**. Without permission (via terms of use or otherwise), then that content remains under prior version.

**Comment by anothersimulacrum** [comment] 2021-02-25 16:31
> > if a move from 3.0 to 4.0 is legal
> 
> Is it?

Well, that's the question, isn't it.

**Comment by Fosheze** [comment] 2021-02-25 21:31
>In version 4.0, CC added a provision in the ShareAlike licenses that enables downstream licensees to refer only to the adapter’s license when using adapted material that contains the copyrightable contributions of multiple authors. This feature is designed to minimize complexity for reusers where they are using a later version of the ShareAlike license or a compatible license as their adapter's license. In 4.0, users need only refer to a single set of conditions contained in the last license applied to reuse adapted material, rather than parsing the conditions of the original and other adapter's licenses (to the extent the licenses differ).

>**In all cases, the licenses stack (the later license does not supplant all previously-applied licenses)** when adapted material is created. In particular, the license originally applied to the material being remixed continues to apply once remixed, however permission is given in 4.0 for licensees to meet the conditions of the 4.0 license with reference to those in the adapter's license.

>**Prior to the 4.0 versioning process, CC had not always been clear that the ShareAlike licenses stacked** just as they stack for the BY and BY-NC licenses, and reasonable minds do differ on this point. **CC believes, however, that this is the best reading of its all of its licenses that permit adaptations prior to 4.0 and, now, has made that explicit in version 4.0**.

[Source](https://wiki.creativecommons.org/wiki/License_Versions#Compatibility_mechanism_in_BY-SA_licenses)

>Currently, no non-CC licenses have been designated as compatible with BY-SA 3.0.

[Source](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses)

Licensing under CC 4.0 does not remove the CC 3.0 license they just stack. Because CC 3.0 is not compatible that means that content that was ever licensed under it can not be licensed under GPLv3 unless CC adds it to the list of compatible licenses.

I'm definitely not a lawyer but I really can't see any way around that. There's an excellent conversation on the exact thing on [stack exchange](https://opensource.stackexchange.com/questions/2212/is-stack-exchanges-cc-by-sa-v3-0-content-compatible-with-the-gpl).

**Comment by kevingranade** [comment] 2021-03-21 02:07
> Licensing under CC 4.0 does not remove the CC 3.0 license they just stack.

None of your sources say this, they say that CC thinks it does, *but* CC recognizes it is not explicitly stated and *it's reasonable to believe otherwise*.  Clearly they want it to since they made it explicit with 4.0, but if it doesn't say it in the license itself, it doesn't exist.

The question basically boils down to whether modified releses constitute "contributions" to the work (which would be odd considering that term doesn't appear in the license text, and section 1a defining "Adaptation" explicitly says otherwise) or "adaptations" of the *whole* work, meaning it falls under section 4b of the license:
```You may Distribute or Publicly Perform an Adaptation only under the terms of: (i) this License; (ii) a later version of this License with the same License Elements as this License; (iii) a Creative Commons jurisdiction license (either this or a later license version) that contains the same License Elements as this License (e.g., Attribution-ShareAlike 3.0 US)); (iv) a Creative Commons Compatible License.```

There is no plain reading of the license that says anything about stacking.  Section 4a is redistribute *the Original work* under the same license.  Section 4b is distribute *an Adaptation of the work* under *one* of several alternative licenses, one of which is "a later version of this (3.0) license with the same License Elements as this License", i.e. CC-BY-SA 4.0.

Relative to the upgrade guidelines linked by @anothersimulacrum , the issue is the same, are we dealing with a bundle of different works with potentially different licenses, or are we dealing with a single large work that has a continuous stream of derivative works published for it?  The "mixed license" scenario there references things like, "an essay released under 3.0 and a translation of that essay released under 4.0", but that's not the case here, DDA isn't a bundle of different works, it's one monolithic work that is distributed as a bundle of files.  However, even if a single work is smaller in scope, such as a file or even a function, then *that* piece could be distributed under CC 4.0, and then later modifications to it can be released under GPL 3.0, so potentially you have islands of CC 4.0 and GPL 3.0 in a sea of CC 3.0, see below for the ramifications of this.

One further wrinkle is that you can publish an Adaptation under 4.0, and then publish an Adaptation of *that* version under GPL 3.0.  Due to the stacking concept being explicit in 4.0, you then definitely have a "CC 4.0 and GPL 3.0 licensed work", but the catch there is that the feature we *want* from GPL makes the CC 4.0 part of the license non-functional.  In other words, the "Corresponding Source" clause: ```The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities.``` would cover the entire project, and that requirement must be satisfied in addition to the requirements of CC 4.0.

So in practice, we could have a patchwork of CC 3.0 and CC 4.0 and GPL 3.0 code, but due to the viral nature of the "Corresponding Source" clause, distributing a modified executable requires the distributor to make available the corresponding source used to build that whole executable.  In theory that might leave most of the JSON content out since most of it isn't corresponding source code, but that doesn't much matter since it's distributed as plain text in the distributable bundle.

**Comment by kevingranade** [comment] 2021-05-23 11:01
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/steam-dark-days-ahead/26348/26

**Comment by licaon-kter** [comment] 2021-06-24 14:54
Not being actually FOSS is an odd thing in the end, hope this is cleared up so we can add it to F-Droid :)

**Comment by Inglonias** [comment] 2021-11-02 13:51
I just discovered this issue and, frankly, it's scary. I was not aware that the license in use is not valid for software. Oi...

**Comment by I-am-Erk** [comment] 2022-07-21 19:44
Closing this as I do not believe the original claim was correct, and changing the license is not practically possible.

**Closed by I-am-Erk** 2022-07-21 19:44 UTC
Labels: Organization
