### ISSUE TITLE
Rotten food should not be used for crafting

### ISSUE THREAD

**Issue by xjosephx** [CleverRaven/Cataclysm-DDA#25382] opened 2018-09-05 20:54 UTC
If there is a rotten and non rotten variant the non rotten version should be used. If there is only rotten it should ask the player if they wish to create a recipe using rotten food. It's really annoying wasting food and/or hours of time on food just to see it come out rotten. Should preferably also check if the food will rot during the period of crafting (if that is a possibility)

**Comment by Zireael07** [comment] 2018-09-06 06:53
Using rotten components is a long preexisting issue, but I'm not sure if it was ever officially reported.

**Comment by ifreund** [comment] 2019-02-19 09:37
Duplicate of #22129.

**Closed** 2019-02-19 12:48 UTC
Labels: <Suggestion / Discussion>, Crafting / Construction / Recipes
