### ISSUE TITLE
Cataclysm version .9 unexpected close

### ISSUE THREAD

**Issue by Solarshot43** [CleverRaven/Cataclysm-DDA#4656] opened 2013-11-24 22:21 UTC
while I was playing Cataclysm version .9 stable my game closed unexpectedly with out any notification. I was playing with an unemployed character with 16 strength, 8 dexterity, 4 intelligence, and 4 perception. He had martial arts training, and I gave him the trait quick. his bad traits were addictive personality, asthmatic, ugly, truth teller, and trigger happy. He had 1 point put into dodgeing and 9 in unarmed combat. I had just started and left the safe house that was a little while away from the town, and I started to walk to a public works. when I arrived I killed a single zombie, and found a pair of boots that fitted. I had gone into the public works and I was looking for things. while I was moving toward a truck the game suddenly closed, and that is pretty much every last detail. I hope this can help you, and im sorry to have written such a lengthy and detailed bug report.

**Comment by illi-kun** [comment] 2015-06-10 09:54
For which purpose we're keeping this issue open? IMO, It doesn't contain any kind of useful info, and we are not able to track its status since the root of the issue is not actually described.

**Comment by narc0tiq** [comment] 2015-06-10 10:37
> For which purpose we're keeping this issue open?

Because nobody who could close it had seen it. I imagine whatever the underlying cause here, it has probably been resolved several time over.

**Closed by narc0tiq** 2015-06-10 10:37 UTC
