### ISSUE TITLE
Using mods to only modify existing attributes

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#17230] opened 2016-06-17 23:31 UTC
I think the generic gun mod (issue #17157 ) could be simplified if attributes of items could be changed without rewriting the whole object. Testing with a weapon, the game looks for all attributes of an item even when an ID already exists. If one wanted to only change an attribute like volume, recoil, etc, you have to re-define the whole item, which is problematic as versions may change flags or attributes over time.

Glancing through some normal json, the "generic.json" has the corpse entry:         "//": "most of the properties depend on the monster type and are created at runtime!". This seems to imply there's already at mechanism for modifying only some properties of a pre-existing object, and even creating additional objects on-the-fly (perhaps there could be a "prototype" field for mods that have redundancy).

**Comment by mugling** [comment] 2016-06-18 19:29
Duplicate of #14250. See also comments in #17157

**Closed by mugling** 2016-06-18 19:29 UTC
Labels: Duplicate
