### ISSUE TITLE
DEBUG: zombie at xyz not found in the tracker

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#13160] opened 2015-08-02 22:53 UTC
0a526bf

A zombie came up from a basement. Zombies previously came up from the basement without issue. There was smoke, I don't know if that'd have anything to do with it.

"The zombie comes up the stairs!"
"The zombie is almost at the top of the stairs!"

Edit: Now it's not letting me play, because as soon as I do anything, the screen fails to update (mostly) and it says the zombie is not in the tracker... and it has moved.

Edit2: It seems the issue is resolved by saving and reloading a few times, because now three zombies came up the stairs (despite only 1 being within 1-square of the stairs when I went up).

**Comment by HeadWar** [comment] 2015-08-02 23:19
I got similar errors when there were multiple zombies coming down stairs, and it sometimes started acting rather wonkily, with a single zombie being shown in three different tiles (attackable in all of them), and not moving.

**Comment by drbig** [comment] 2015-08-03 07:44
Duplicate of #13011. Please read [ISSUES.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md).

**Comment by mugling** [comment] 2016-03-10 00:45
Closed as duplicate

**Closed by mugling** 2016-03-10 00:45 UTC
Labels: Duplicate
