### ISSUE TITLE
Game hangs when trying to get/accept an USB quest from a starting npc in the mine start

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22235] opened 2017-10-23 16:00 UTC
Game version: 0.C-24621-gba4030b6d7

Operating system: Linux

Tiles or curses: curses

Mods active: bright nights

**Comment by lucianposton** [comment] 2017-10-26 03:07
Might be duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/21950 . If it is, it will resume after some amount of time. The longest I've seen it hang is 60-90 seconds.

Did you increase the size of city or city spacing world gen parameters?

**Comment by l29ah** [comment] 2017-10-26 04:13
On Thu, Oct 26, 2017 at 03:07:53AM +0000, lucianposton wrote:
> Might be duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/21950 . If it is, it will resume after some amount of time. The longest I've seen it hang is 60-90 seconds.

I've waited for about 30s, let's see.

> Did you increase the size of city or city spacing world gen parameters?

No, it's default.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by cainiaowu** [comment] 2017-10-26 04:33
I think the mission generation logic might need a simple tweak, it should first search for a nearby location that can use as mission start regardless of mission type then assign a corresponding mission to it.
Though it may require to add some flags when you finish X number similar missions recently to avoid repeated same mission but it might be better than what we have now.

**Comment by Broken-Admin** [comment] 2017-12-13 01:46
NPCs have been a long running problem as they are improperly working and need a revision. We still have a NULL MISSION floating around that I could probably help fix.

**Comment by AMurkin** [comment] 2017-12-13 05:06
NULL MISSION were fixed by #22516, probably.

**Comment by Leland** [comment] 2018-02-19 17:51
Closing in favor of #21950

**Closed by Leland** 2018-02-19 17:51 UTC
Labels: Confirmation Needed, Crash / Freeze, Mission
