### ISSUE TITLE
Unexpected Termination Segmentation Fault crashes

### ISSUE THREAD

**Issue by scrubs2009** [CleverRaven/Cataclysm-DDA#29681] opened 2019-04-18 16:16 UTC
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3095599/crash.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3095600/crash.log)

Viewing certain tiles will cause the game to crash. This happens on multiple builds, in multiple locations, in multiple worlds. The worlds will be fine for a few hours and then a certain tile will just crash the game when viewed. 

**To Reproduce**  
1. Start world
2. Go about making a nice base
3. Play for a few hours
4. Now every time you enter the south corner of the second floor of your base (just an example) the game crashes. It doesn't matter if you teleport there, go up or down stairs, or walk there.

**Expected behavior**  
You enter the area, the game crashes and throws up these 2 messages.

[
![image](https://user-images.githubusercontent.com/24904657/56375003-0794ef80-61ca-11e9-9b0c-567692c110dd.png)
](url)

[
![image](https://user-images.githubusercontent.com/24904657/56375028-17accf00-61ca-11e9-9564-7dd68acdeee1.png)
](url)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 professional
 - Game Version: 0.D-1921-gbe0d520
 - Graphics version: Tiles
 - Mods loaded: Extended realistic guns, Makeshift items, More survival tools, Modular turrets, Salvaged robots, Crazy cataclysm, Beta camp, More locations, Fuji's buildings, More city locations, urban development, Boats, folding parts, vehicle additions, tanks, magic items, necromancy, Jury-rigged robots, classes and scenarios.

I doubt it's any of these mods as I have the problem without them.

**Additional context**  
Save file (To get the crash go down the stairs nearby)
[Big Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3095239/Big.Springs.zip)

UPDATE: They're getting worse. Don't even need to enter a new area anymore. Just going to sleep is causing them. 

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3095601/crash.log)

**Comment by neitsa** [comment] 2019-04-27 12:47
Thank you @scrubs2009 for your bug report! I can confirm it's a duplicate of #28679. I got exactly the same stack trace.

Side note: This save file is small and seems to trigger the bug nearly each time.

Once again a problem with a `_purecall() in `monster::rate_target`... 

```
 	ucrtbased.dll!issue_debug_notification(const wchar_t * const message) Line 28	C++
 	ucrtbased.dll!__acrt_report_runtime_error(const wchar_t * message) Line 154	C++
 	ucrtbased.dll!abort() Line 61	C++
>	vcruntime140d.dll!_purecall() Line 30	C++
 	Cataclysm.exe!monster::rate_target(Creature & c, float best, bool smart) Line 177	C++
 	Cataclysm.exe!monster::plan(const std::map<int_id<monfaction>,std::set<monster *,std::less<monster *>,std::allocator<monster *> >,std::less<int_id<monfaction> >,std::allocator<std::pair<int_id<monfaction> const ,std::set<monster *,std::less<monster *>,std::allocator<monster *> > > > > & factions) Line 336	C++
 	Cataclysm.exe!game::monmove() Line 4648	C++
 	Cataclysm.exe!game::do_turn() Line 1498	C++
 	Cataclysm.exe!SDL_main(int argc, char * * argv) Line 689	C++
 	Cataclysm.exe!main_getcmdline(...) Line 177	C
 	[External Code]	
```

**Closed** 2019-04-30 03:09 UTC
Labels: (S1 - Need confirmation), <Bug>, <Crash / Freeze>
