### ISSUE TITLE
Fishing hooks not stacking

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#27839] opened 2019-01-24 18:21 UTC
**Describe the bug**  
Fishing hooks don't stack in inventory or in piles.

**To Reproduce**  
1. craft some fishing hooks
2. Check stacking

**Expected behavior**  
They used to stack.

**Screenshots**  
![image](https://user-images.githubusercontent.com/39442864/51699540-fa0d0680-1fda-11e9-80e3-090d8163df1e.png)

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version 0.C-37037-g096dabd
 - Graphics version Tiles
 - Mods loaded 
  "dda",
  "filthy_morale",
  "no_npc_food",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "mutant_npcs",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Arcana",
  "No_Fungi",
  "Dorf_Life"

**Comment by GoLoT** [comment] 2019-01-24 18:39
Most likely related to #27828 and should be fixed in the next build.

**Comment by GoLoT** [comment] 2019-01-25 04:54
![image](https://user-images.githubusercontent.com/1606943/51726027-8f54dd00-2065-11e9-91b5-5df852203461.png)

Can't reproduce in 8469. It seems the fix is working.

**Comment by Night-Pryanik** [comment] 2019-01-25 07:30
Closing. If the issue still exists, ping me.

**Closed by Night-Pryanik** 2019-01-25 07:30 UTC
