### ISSUE TITLE
Training w/NPC in moving car causes car to continue going forward

### ISSUE THREAD

**Issue by PlasmaChroma** [CleverRaven/Cataclysm-DDA#21982] opened 2017-09-24 18:41 UTC
### Expected behavior
Maybe have the car stop during training?

### Actual behavior
Car continues to move forward for the duration of training.

### Steps to reproduce the behavior
Completed a mission from NPC, and then chatted with them without getting out of car in motion.  Got training as reward, car moved forward A LOT until crashing into a forest.

**Comment by awesine** [comment] 2017-09-24 19:20
"Wow, i'm going to stop controlling the wheel and not stop the car while I learn some skills! What? The car continued moving due to basic laws of acceleration and motion? Nerf!"

stop the car before you train

**Comment by AncientSion** [comment] 2017-09-24 19:40
lol this issue is awesome.

@awesine made a good point here.

**Comment by BevapDin** [comment] 2017-09-24 20:18
Duplicate of #21712.

**Closed by BevapDin** 2017-09-24 20:18 UTC
Labels: Suggestion (Discuss), Vehicle
