### ISSUE TITLE
Removing keybindings from move commands prevents you from navigating in look around command even after rebinding

### ISSUE THREAD

**Issue by Keltas** [CleverRaven/Cataclysm-DDA#53396] opened 2021-12-12 16:38 UTC
### Describe the bug

After removing keybinding from Move North/South/etc. and applying a new keybinding (even the same as previous), the new keybinding does not work when using "Look Around" command. I.E. if you remove "Move North" and bind it to "8", you can walk north using "8" but if you use the "Look Around" command, you can no longer move the cursor north.

This issue may be related to "Arrow Keys and NumPad Keys don't work on the main menu after rebinding #44346", as the menu navigation is also impaired, however I decided to report it as this is a separate functionality that is affected.

### Steps to reproduce

1. go into Settings->Keybindings.
2. Press "-".
3. Press "a" to select "Move North".
4. Select "Yes".
5. Press "+".
6. Press "a" to select "Move North".
7. Press "8" to bind "8" to "Move North".
8. Go into game and press ";" to look around.
9. Press "8". The cursor is not moving up. All the other directions such as "2" still work properly.

### Expected behavior

I expected the look around command to be navigable using the move keybindings even after rebinding them. If not, then to have a keybinding that I can set for it.

### Versions and configuration

OS: Windows 10,
Game Version: stable 0.F-3 as well as the latest experimental build "2021-12-12-0853" version in game:"cf9e61e",
Graphics Version: Tiles,
Ingame Language: System Default (English)
Mods Loaded: Default (dda, no_npc_food, no_fungal_growth, package_bionic_professions)

**Comment by hexagonrecursion** [comment] 2021-12-17 15:19
Confirmed. What happened:
1. - removed the global keybinding
2. + added a local keybinding, but the global keybinding remained unbound

Further testing confirmed that the look around menu uses the global keybinding instead of the local one.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment] 2022-01-18 21:42
@wapcaplet Confirmed

**Comment by Brambor** [comment] 2024-02-24 12:32
This is not a bug, but intended behavior.*

What you did is remove global keybinding `-` and add a local keybinding `+`, had you added global keybinding `=` this wouldn't have happened.

The problem is: You added the local keybinding to the "DEFAULT" context and then expected it to work in the "LOOK_AROUND" context.

The settings in the main menu can access only the "DEFAULT" context. *This is potentially confusing.

1. In `step 1.` if you access keybindings in the game with `?` it starts to make sense.
2. Then, you can access keybindings with `?` again in step 8.
3. There you can see, that `Pan up` (LOOK AROUND name for Move North) is unbound globally, as you removed it in `step 2`.

**Comment by Night-Pryanik** [comment] 2024-10-28 10:34
Closing as working as intended.

**Closed by Night-Pryanik** 2024-10-28 10:34 UTC
Labels: <Bug>, (S2 - Confirmed), Controls / Input
