### ISSUE TITLE
Coal doesn't work in rock forge

### ISSUE THREAD

**Issue by Jninja1** [CleverRaven/Cataclysm-DDA#69239] opened 2023-11-10 16:34 UTC
### Describe the bug

I found that the rock forge accepts both coal and charcoal; however, it doesn't seem to count coal as a fuel source. I have put in around 10,000 coal, stopping due to boredom, and any recipe that used the rock forge did not recognize the "fuel". For example trying to make a steel spear with a forge loaded with coal I would not have the choice to use the forge. When I loaded the forge with charcoal it loaded with a max of 2,000 and the previous coal would be gone, but I can now use the forge.

I am unsure if only being able to use coal is the intended behavior. Coal can, and is, used in forging applications. If it's supposed to be only charcoal perhaps that should be made more clear

### Attach save file

N/A

### Steps to reproduce

Have access to a rock forge.
Load with an ungodly amount of coal.
Unable to use forge.

Load forge with charcoal instead.
Able to use the forge.
Previous coal disappears into the ether.

### Expected behavior

I am expecting to be able to use the forge with either coal or is charcoal.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: aaec442 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex]
]

**Comment by KeremBabaG** [comment] 2023-11-11 17:06
Huh. It seems like it outright eats the coal, no unloading either. Looking into it

**Comment by RenechCDDA** [comment] 2023-12-09 12:49
Duplicate of #68371

**Closed by RenechCDDA** 2023-12-09 12:49 UTC
Labels: (S1 - Need confirmation)
