### ISSUE TITLE
brazier bug

### ISSUE THREAD

**Issue by Edreym11** [CleverRaven/Cataclysm-DDA#35703] opened 2019-11-24 19:30 UTC
# Describe the bug

Tried to deploy a brazier that was droped on the ground and the game crashed

# Steps To Reproduce

1. Drop brazier on the ground
2. Deploy blazier

# Expected behavior

Blazier it's deployed to use

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9634-g962e122
 - Graphics version: Tiles
 - Mods loaded: dda,Magiclysm,modular turrets, salvaged robots, vehicle additions pack, tanks and other vehicles,mutants npcs,roadheaders and other mining vehicles

# Additional contents

[Dellview.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3884023/Dellview.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3884025/config.zip)

**Comment by Funguss** [comment] 2019-11-24 19:42
Duplicate of 35673. Also, there's a fix waiting to be merged.

**Comment by ZhilkinSerg** [comment] 2019-11-24 20:05
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/35673

**Closed by ZhilkinSerg** 2019-11-24 20:05 UTC
