### ISSUE TITLE
Volume not displayed correctly in multidrop (top right corner).

### ISSUE THREAD

**Issue by gonarr** [CleverRaven/Cataclysm-DDA#40489] opened 2020-05-12 17:01 UTC
# Describe the bug
As the title says: During a multidrop (hotkey: d) the volume at the top right corner is not displayed correctly. I believe this is due to the current changes on how items are now stored in containers. The normal Inventory view shows this value correctly.

# Steps To Reproduce

Press d and look at the top right corner, the volume is not what it is in the normal inventory view.

# Expected behavior

The Volume should be displayed (top right corner) as well as taking into account and subtracting the Volume for Items I am about to drop.

# Screenshots
Multidrop Window with no Volume
https://cdn.discordapp.com/attachments/598523535169945607/709809640363262152/unknown.png

Inventory displaying the correct Volume:
https://cdn.discordapp.com/attachments/598523535169945607/709809609187262484/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2083-g702b0b4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Gun Cotton [guncotton],
    Mining Mod [Mining_Mod],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Thank you for your hard work.

**Comment by KorGgenT** [comment] 2020-05-12 20:32
Duplicate of #40265

**Closed by KorGgenT** 2020-05-12 20:32 UTC
Labels: <Bug>, Info / User Interface
