### ISSUE TITLE
CDDA freeze. Suspect repeating pocket error?

### ISSUE THREAD

**Issue by MrSamsa** [CleverRaven/Cataclysm-DDA#41839] opened 2020-07-04 21:42 UTC
# Describe the bug

The game will freeze and become unresponsive. The save game will load and movement is possible but taking any other actions causes a hard freeze with no error message.

A new error had appeared along with this problem and seems to repeat itself after verify and finalize of the save game load.

ERROR : src/item_contents.cpp:283 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: item is too long

# Steps To Reproduce

Not sure how..

# Expected behavior

Normal gameplay.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3725-g69cf449 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I suspect it has something to do with the change in the pocket system recently where items were made so they could not contain themselves such as 100L barrel inside another 100L barrel. Perhaps a item in the save had something inside its pocket that isnt allowed anymore and its causing the issue?

Logs are contained in the .zip
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4873952/save.zip)

**Comment by Duck13Tales** [comment] 2020-07-04 22:51
I think that if you press "i" you are able to keep playing. My game sometimes get so many of this message that I would need to press "space" a lot of times so it works again but "i" ignores all those problems.

**Comment by MrSamsa** [comment] 2020-07-05 04:05
Yeah I have used the "i" option. Its the only way to make it past the initial loading of the save. The problem happens after the save loads and the errors are ignored however it looks like the error I mentioned above is constantly repeating, which may explain the freeze?

**Comment by GGgatherer** [comment] 2020-07-05 17:07
Looks like same issue as [mine](https://github.com/CleverRaven/Cataclysm-DDA/issues/41648), and the more times you save+load, the bigger the save will become because items are duplicating. I advice finding the offending container - should be in the biggest o.X.Y file - and cutting all contents from it.

**Comment by hexagonrecursion** [comment] 2021-01-13 15:01
This seems to be the same as https://github.com/CleverRaven/Cataclysm-DDA/issues/41776 which was fixed a while ago

**Comment by Saicchi** [comment] 2021-02-03 22:50
Can't reproduce this on `0.E-9283-g885f91c3c2`.
I didn't load the mods `Cata++`, `more_survivor_stuff` and `cityside` because I didn't have them.

Apart from the usual errors of trying to load a really old save file on the newest versions I did not get the freeze like it was described. Crafting, reading, eating and other activities played at a normal time.

**Comment by KorGgenT** [comment] 2021-02-04 23:24
closing as it cannot be reproduced and there's not much extra information...

**Closed by KorGgenT** 2021-02-04 23:24 UTC
Labels: <Crash / Freeze>
