### ISSUE TITLE
Item details' interaction menu broken

### ISSUE THREAD

**Issue by mongeaujeremy2** [CleverRaven/Cataclysm-DDA#77213] opened 2024-10-21 02:20 UTC
### Describe the bug

When you expand an item's details and display the interactions (such as w to wield, W to wear etc.), the window for interactions is shrunk down to be smaller than even one entry on the list, and constantly scrolls through the list of possible interactions. The hot keys still work despite this, however.

### Attach save file

[Possum Hills-trimmed.tar.gz](https://github.com/user-attachments/files/17453171/Possum.Hills-trimmed.tar.gz)

### Steps to reproduce

1. Go to any item in your inventory
2. Expand details (Enter on item in inventory by default) to see the interactions list
3. View the bugged interactions list 

### Expected behavior

I expected to see the full list of interactions, in order to view what could be done and remind myself of hotkeys for certain actions. This is normally standard, however the bug makes this list practically unviewable.

### Screenshots

![Screenshot 2024-10-20 221314](https://github.com/user-attachments/assets/f637b0bf-7552-4f4d-b031-7e4d52bd8990)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: fb7fcae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

To my memory, this bug did not exist in the experimental build from four days ago (October 16th, 2024). Unsure of what version introduced this, as I updated from that build to the build on this save file.

**Comment by Vaskritaya** [comment] 2024-10-21 02:31
probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/77191

**Comment by Brambor** [comment] 2024-10-21 03:04
Closing as duplicate.

**Closed by Brambor** 2024-10-21 03:04 UTC
Labels: (S3 - Duplicate)
