### ISSUE TITLE
"couldn't find cached components" error when trying to craft using components about to get burnt

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#26287] opened 2018-10-17 03:56 UTC
**Describe the bug**  
Error when trying to craft a quarterstaff: "Aborting craft: couldn't find cached components"

**To Reproduce**  
I think I understand what happened:
1. Moved a splintered wood and some two by fours to an Oven
2. Set them on fire
3. Tried to craft a quarterstaff.
4. It failed with the error "Aborting craft: couldn't find cached components"

The two by fours in the Oven where the only ones I had around.
I guess the code tried to use those to craft the quarterstaff but either in the middle or at the end of the crafting time the two by fours got burned and I lost the component.

**Expected behavior**  
Don't let the player craft from items getting burned.
And avoid generating an error.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-33156-gd0fe67e
 - Graphics version: Tiles

**Comment by kevingranade** [comment] 2018-10-17 16:09
It sounds like we should just print an in-game notification instead of an error message, "some crafting materials were destroyed before you could use them".

**Comment by Night-Pryanik** [comment] 2018-10-18 19:11
Dupe of #26264.

**Closed by Night-Pryanik** 2018-10-18 19:11 UTC
Labels: Crafting / Construction / Recipes, Info / User Interface
