### ISSUE TITLE
ImgUI on Android Mobile and Go to Destination map function issue

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#72689] opened 2024-03-29 12:49 UTC
### Describe the bug

When you enable ImgUI on Android Mobile, when using the Go to destination function on the map, the game frame freezes while it's walking/driving towards your destination until you manually stop and/or reached your destination.

### Attach save file

N/A

### Steps to reproduce

1. Use Map's go to destination function
2. See if the screen animates
3. Enable ImgUI
4. Use Map's go to destination function
5. See if the screen animates

### Expected behavior

It should not freeze

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/95905384/4fa205dc-7399-4128-9cd6-8233a4cce423

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: cdda-experimental-2024-03-29-0523 cba18c3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved]
]

**Comment by NetSysFire** [comment] 2024-03-29 13:07
CC @katemonster33

**Comment by katemonster33** [comment] 2024-04-04 22:08
I actually tested this with #72689 and I think that fixed this. Can someone re-test?

**Comment by XygenSS** [comment] 2024-04-10 06:36
@katemonster33 
Cannot reproduce on latest experimental, seems to be fixed

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 14; Incremental: V816.0.4.0.UMYCNXM; 
- Game Version: cdda-experimental-2024-04-10-0131 fd489a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]


https://github.com/CleverRaven/Cataclysm-DDA/assets/27952407/2b9d2294-1659-4882-94f3-efd55ce4d27a

**Comment by NetSysFire** [comment] 2024-04-10 06:48
Closing as fixed then.

**Closed by NetSysFire** 2024-04-10 06:48 UTC
Labels: (S1 - Need confirmation), OS: Android, ImGui
