### ISSUE TITLE
STANAG drum magazine don't fit in M4 and other STANAG accepting rifles

### ISSUE THREAD

**Issue by zapa1928** [CleverRaven/Cataclysm-DDA#18497] opened 2016-09-23 13:26 UTC
M4A1, HK416, Styer Aug and other rifles, lack "stanag50" flag.

**Comment by mugling** [comment] 2016-09-23 13:47
This has come up previously - the answer was gameplay/balance. If you want to submit a 'hyper-realistic gun stats' mod that would probably be reasonable but making an already set of homogenous items even less interesting isn't a good idea.

**Comment by zapa1928** [comment] 2016-09-23 14:41
ok, closing.

**Comment by Rivet-the-Zombie** [comment] 2016-09-23 17:56
So we're taking real-world firearms that actually use standardized magazines and screwing around with that in the name of 'gameplay/balance'?

I'm one hundred percent in favor of granting those guns the proper magazine compatibility. Being STANAG compatible is pretty much the entire point of those firearms - it's the only thing that makes them particularly interesting in the first place.

**Comment by mugling** [comment] 2016-09-23 18:23
Yes, gameplay is king. All other concerns are secondary. After all it's a game.

There isn't much to differentiate them apart from the magazines. A lot of our items have this problem - they are clones with different names. Outside our immediate circle the project get panned for this as being painfully boring to play.

A good example would be the `308` guns. I gave one a 20-round magazine and one a larger 30-round that didn't fit in standard ammo pouches. Someone helpfully corrected that so the items were identical.

We are writing a game, not a gun encyclopaedia. A mod with all the realistic details would keep everyone happy.

**Comment by Griffinhart** [comment] 2016-09-24 00:42
If you want to make a game that ignores realism in favor of gameplay, then maybe don't incorporate real-world elements; make up fictional guns instead of using real-world guns with real-world metrics and expectations of behaving like their real-world counterparts.

**Comment by BorkBorkGoesTheCode** [comment] 2016-09-24 01:17
> If you want to make a game that ignores realism in favor of gameplay, then maybe don't incorporate real-world elements; make up fictional guns instead of using real-world guns with real-world metrics and expectations of behaving like their real-world counterparts.

I think Generic Guns is supposed to do that.

**Comment by Griffinhart** [comment] 2016-09-24 02:51
If that's the case, and "gameplay is king", why is Generic Guns a mod, instead of being core, with a "hyper-realistic gun stats" mod instead?

**Comment by moosestrangler** [comment] 2016-09-24 05:58
STANAG compatible assault rifles absolutely should take any STANAG mag. Making stuff up to differentiate weapons belongs in generic guns.

Having a load of rifles and magazines marked as STANAG that don't work properly together is two steps from breaking the interface.

**Comment by Zilenan91** [comment] 2016-09-24 17:23
I don't really think gun magazines are that inherently interesting anyways, especially STANAG guns. You get what you expect, a gun magazine.

**Comment by mugling** [comment] 2016-09-24 17:50
By the same logic we need a different air and fuel filter for each engine. That's certainly in compliance with strict realism but it wouldn't be much fun though would it? Games are supposed to some extent to be an escape from reality.

> is two steps from

No more prophecies of doom please.

> If that's the case, and "gameplay is king

Does anyone actually want to argue that gameplay isn't the most important factor? This is a far more important issue to be discussed. I'm only really interested in working on an implementation designed to improve gameplay.

I wrote the magazine code, then the holster code, then the aiming code and finally the burst code to make the game more enjoyable to play. The player now has more meaningful choices to make. This issue is open precisely because there is now a choice.

Larger magazines are a significant advantage (especially following burst fire) so the fact that different combos are possible makes selection of the base gun much more of an issue. I didn't write all the code supporting this so we could make every item the same or have one good item and a dozen never utilised inferior variants.

In the future I'd like to work on multiple ammo types (nails plus compressed air for nail rifle), alternative ammo types (.357 instead of .38) and other changes because I think they'd add to depth. I've considered changeable barrels as well but I'm not sure if that would actually be fun to play with.

Reality can inspire the design but I don't think it should suppress the idea a game is made to be fun.

**Comment by moosestrangler** [comment] 2016-09-24 18:49
Meaningful differentiation between similar guns should come from factors other than magazines. Barrel length affects accuracy, damage, and manoeuvrability. Weight affects recoil. Fire rate affects burst size. Sights affect accuracy, effective range, and aiming speed. Bullpup rifles are more compact for the same barrel length.

If magazine compatibility is the only thing differentiating STANAG compatible rifles they need major changes. Even with the way gun stats are currently handled there should be notable differences between them.

**Comment by zapa1928** [comment] 2016-09-24 20:55
I think the problem is, for different people, gameplay means different thing. 
From what i understand you @mugling, in this case are more focused on balancing and having meaningful differentiation between guns, and thats one way of looking at this. But as for me and for many i think the more important aspect of gameplay is immersability. 

For many things i think CDDA is great of delivering that because you can translate meaningful behavior from real world into the game. It's great at that, because you guys code this game with regard of physics, chemistry and basically common sense.

But when something doesn`t make sense, because in real life it works completely different, it breaks immersion. Hence gameplay is broken.

From my experience, people mostly doesn`t care that this and that gun is basically the same, (If you have seen that as a problem you shouldn't have add that many guns, mods would be fine for that), or have one point of that more or less, because it a Role Playing Game. You role play. I as a player, want to have choice of so many guns, not from gameplay mechanic standpoint, but from sentiment, and/or character creation point of view which for me is a founding block for immersion in RPGs.

**Comment by mugling** [comment] 2016-09-24 22:14
> Even with the way gun stats are currently handled there should be notable differences between them.

There isn't any meaningful difference - without magazine differences there is one clear winner and all the other items become meaningless.

> If you have seen that as a problem you shouldn't have add that many guns, mods would be fine for that

I inherited the mess and had to clean it up - I would happily drop items but that was rejected earlier on.

> But when something doesn`t make sense, because in real life it works completely different, it breaks immersion

Type 5B air filter ,Type KC9 air filter, Type KN15 filter...

> because it a Role Playing Game

No it's a rogue-like. The core requirement of the genre is challenge.

> From my experience, people mostly doesn`t care that this and that gun is basically the same

What experience? Your earlier comments suggest that you are a little in the dark about how we came to have magazines. They were an add-on to existing definitinos and I did a lengthy rewrite of a huge amount of the codebase to support them. So believe me when I say I speak from experience.

Further work on the gun code becomes a time sink and something I'm discouraged to work on if it is to lead to these issues. They are always subjective an opinionated and given I'm putting in the work I really do expect to be able to reach a decision. Some changes for realism are acceptable - I didn't like the change from AK-47 to AKM because many players couldn't find the item, but it didn't harm gameplay but this change does.

**Comment by Griffinhart** [comment] 2016-09-24 23:48
>Does anyone actually want to argue that gameplay isn't the most important factor?

I'm not arguing this. I am saying, however, that if this statement is true, then Generic Guns should be core, and a "hyper-realistic gun stats mod" should be the alternative, since that gives developers more leeway in making up weapons for the sake of gameplay balance, instead of having people like myself nitpick over realism.

You'll note, for example, that there are comparatively fewer issues regarding how the Rivtech guns don't match to their real-life counterparts, what with them not having real-life counterparts, allowing their designer to assign stats within the bounds of "gameplay balance" instead of "reality".

**Comment by Coolthulhu** [comment] 2016-09-25 01:47
I'm with @mugling on the design, but if most of everyone else wants realistic guns, we could consider some other disadvantage for the guns that currently don't accept drums.

Anything that looks realistic on the outside but produces unrealistic behavior isn't actually realistic.
All those tacticool additions on the guns, for example.
Drum magazines being almost a strict upgrade from regular ones is just a symptom of the problem, the cause being lack of penalties for baroque abominations with more mods than bullets.
And no, reload speed isn't a good penalty.

I'd allow the change here, but also nerf the drum mag to apply a dispersion penalty. Something a bit above symbolic, but not heavy - 30 points?
Doesn't matter that arbitrary penalties like that aren't realistic - neither is having soldiers running around with christmas tree guns.

**Comment by Rivet-the-Zombie** [comment] 2016-09-25 04:18
>I'd allow the change here, but also nerf the drum mag to apply a dispersion penalty. Something a bit above symbolic, but not heavy - 30 points?

Using a larger magazine doesn't make a firearm less accurate. If anything the extra weight helps to dampen recoil a bit, but that's all.

>Doesn't matter that arbitrary penalties like that aren't realistic - neither is having soldiers running around with christmas tree guns.

Like [these guys](https://upload.wikimedia.org/wikipedia/commons/b/b4/US_Navy_070605-N-3642E-586_U.S._Navy_SEALs_(Sea,_Air,_Land)_perform_a_live_fire_exercise_for_the_Secretary_of_the_Navy_(SECNAV)_The_Honorable_Dr._Donald_C._Winter.jpg) are unrealistic?

We've never made a policy of introducing arbitrary penalties because of vague objections to things like customized gear in the past, and I see no reason to start now.

**Comment by Griffinhart** [comment] 2016-09-25 04:20
Weight needs to be a more meaningful factor, I think. IRL operators don't operate operationally with operator guns because shit's heavy, yo. Right now weight doesn't actually *do* anything except penalize your movespeed once you go over a threshold value (and increase stamina loss while moving, but even that doesn't seem to be particularly noticeable).

**Comment by Coolthulhu** [comment] 2016-09-25 05:04
> Using a larger magazine doesn't make a firearm less accurate.

But for some reason regular magazines are more popular than overhuge ones.

> Like these guys are unrealistic?

Pretty operator, but they need more extended mags, laser sights, bayonets, custom grips, shoulder straps, bipods and tracer ammo to reach DDA quality.

**Comment by Griffinhart** [comment] 2016-09-25 06:07
>But for some reason regular magazines are more popular than overhuge ones.

Cost and reliability, both of which are nonfactors in CDDA. Also, practical
carry volume, which CDDA doesn't have (due to the way it models carry
volume).

>extended mags

Already covered above, and also extended mags aren't nearly as prevalent in
CDDA as you seem to be making them out to be (especially since there's no
way to mail-order them).

>laser sights

Already on the top rail of the guns in the picture.

>bayonets

CDDA only allows 1 underbarrel mount, and these guys have forward grips.

>custom grips

The grips on the guns in the picture are obscured by the shooters' hands,
though I suspect they're probably not custom.

>shoulder straps

How do you think soldiers tend to carry in the field when they're not
shooting?

>bipods

Again, CDDA only supports 1 underbarrel mount.

**Comment by zapa1928** [comment] 2016-09-25 06:31
@mugling 

> No it's a rogue-like.

_Rogue (also known as Rogue: Exploring the Dungeons of Doom) is a dungeon crawling video game_  [https://en.wikipedia.org/wiki/Rogue_%28video_game%29](url)

_A dungeon crawl is a type of scenario in fantasy role-playing games_ [https://en.wikipedia.org/wiki/Dungeon_crawl](url)

and from other side

_A role-playing game (RPG and sometimes roleplaying game) is a game in which players assume the roles of characters in a fictional setting..._ [https://en.wikipedia.org/wiki/Role-playing_game](url)

And yes i don`t have experience in writing/coding this game but as you said it's pretty obvious. I was talking about experience of playing other RPG as player and GM.

I do understand the argument it's not worth coding every little aspect into the game (and its a hassle and its discouraging that people complain about such and such), but the argument it's bad for the gameplay is little weak.

And mechanic punishing using oversize mags is already implemented. I don't use drum mags because they don't fit into ammo pouches, and cost of having to spend additional movement points to "take out big bulky mag from backpack" (as far as now abstracted as additional movement points for size or weight (? i don't know exactly i've just starting looking at code in general)) is keeping me from using them now. With nesting inventory (as i see it's coming) that kind of penalty could be more in line with reason i believe operators and regular riflemen don't use drum mags. The speed of use. Reloading them is not something you want to do in stressful situation. But they are useful for supporting role soldiers, it's faster than reloading belt.

**Comment by mugling** [comment] 2016-09-25 17:00
I spent a lot of time working on the gun code and I'm confident almost everyone feels it is a significant  improvement from `0.C`. It's not possible to keep everyone happy with every last detail.

This issue has all the hallmarks of a holy war:

* Entirely subjective issue (gameplay)
* Lack of proportionality (comments like *"is two steps from"*)
* Entirely different rules (why aren't vehicle filters the same?)
* New contributors unaware of previous discussions or context
* Deliberate [aggitation](http://smf.cataclysmdda.com/index.php?topic=13234.165)

I'm still working on the underlying code and want to add more features. These are always aimed at adding new options and tactics - not repetition of the same.

Coolthulhu has the correct idea. If you want to change this you need to add meaningful distinguishing features. Extended magazines not fitting in pouches differentiates the magazines (not the guns).

Holy wars only end in phyrric victory. Discussion should focus on alternative distinguishing features and/or replacing some items - are there 223 rifles that don't accept STANAG magazines? If anyone want's to do a roleplay/hyper-realism mod that's also fine. But ripping apart something I've put a lot of work in because you feel your subjective opinion is better - that's entirely unreasonable.

**Comment by Zilenan91** [comment] 2016-09-25 18:04
So why should drum magazines not fit in STANAG rifles? That doesn't answer the question

It's fine if they're heavier or don't fit in pouches, that's great, you get extra magazine capacity but less utility. But why can they not be loaded into the rifles at all?

**Comment by mugling** [comment] 2016-09-25 18:17
> So why should drum magazines not fit in STANAG rifles? That doesn't answer the question

Yes it has and other posters make reference in either agreement or disagreement. That you don't agree with it doesn't mean it hasn't been given.

> By the same logic we need a different air and fuel filter for each engine

The above though hasn't been answered. It would be an entirely realistic (but awful) change.

**Comment by Zilenan91** [comment] 2016-09-25 18:25
You haven't actually given an answer though, you've been very vague. Your answer was gameplay/balance so what exactly do you think the issue would be?

**Comment by mugling** [comment] 2016-09-25 18:27
> By the same logic we need a different air and fuel filter for each engine
> 
> The above though hasn't been answered. It would be an entirely realistic (but awful) change.

Why though?

**Comment by Rivet-the-Zombie** [comment] 2016-09-25 23:22
>By the same logic we need a different air and fuel filter for each engine

That's a false equivalency: air filters are a simple 'find the foozle to fix the engine' lock-and-key system, while firearm magazines are a modifier on a weapon's utility. If we were comparing air filters to something like 'this gun is missing an important piece that you must find and install before it can be used' or extended magazines to something like 'you can find a high-performance air filter that improves your engine's power' then it would be a fair comparison. It's just an intrinsic property of the entire family of STANAG firearms and magazines; they're all manufactured according to specs laid out in STANAG draft 4179 specifically so that they can all share magazines.

It's not even an issue of adding new items, just making it so that those firearms that are compliant in the real world are also compliant in ours. We could even use `copy-from` to save on JSON lines.

>are there 223 rifles that don't accept STANAG magazines?

There are lots of different civilian-market .223 rifles out there that use proprietary magazines.

**Comment by mugling** [comment] 2016-09-26 00:00
No, vehicle filters aren't interchangeable - IRL there are hundreds of incompatible variants and you wouldn't get far without a fuel filter. Our lack of different types is entirely unrealistic.

If you're going to argue realism is paramount then by the same logic we need at least one filter per engine. The vehicle spares system deliberately ignores reality because it wouldn't be fun to play. The same logic cannot be selectively applied to guns.

> specs laid out in STANAG draft 4179

Excessive detail. We can't possibly hope to support every last feature to this detail without being endlessly embroiled in dispute. Whilst I was writing the original implementation people regularly disputed the intensely technical minutiae - not one bit of which actually made a difference to how fun it was to play.

These discussions gain us nothing except reinforce my concerns that if I was to go and write some of the features discussed earlier they would likely be hijacked by similar discussions.

**Comment by mugling** [comment] 2016-09-26 00:13
> edit: There are some STANAG rifles that we could still block drums and such on simply due to ergonomics...

Then work on this.

> are there 223 rifles that don't accept STANAG magazines?

And on this.

That would make the game both more realistic and more playable. You can use item migrations to adjust existing items.

**Comment by Rivet-the-Zombie** [comment] 2016-09-26 02:41
That likely means adding some .223 hunting rifles or something of the sort, since the only non-military .223 rifles we appear to have at the moment are the survivor-crafted one and the Ruger Mini-14 - also on the proprietary magazines front the Mini-14, Heckler and Koch G36, and Steyr AUG are all using STANAG magazines right now, which they can't actually do in real life without special conversions, so that's another step in the right direction.

**Comment by Zireael07** [comment] 2016-09-26 07:06
>the Mini-14, Heckler and Koch G36, and Steyr AUG magazines right now, which they can't actually do in real life without special conversions, 

the PR suggests giving Steyr the stanag flag. so does it use the STANAG magazine IRL or not?

**Comment by zapa1928** [comment] 2016-09-26 10:21
Standard Styer Aug uses dedicated 30 and 42 polymer magazines. It can be adapted to use STANAG mags through a conversion. 
Styer Aug A3 can come produced as either, accepting polymer propitiatory or stang mag

> The AUG A3 M1 stock, cocking piece and forward grip are made of highly durable synthetic and are available in Black, Green, Mud and White colors. The rifle is available in either the standard version that accepts genuine Steyr AUG magazines or as a NATO version that accepts standard STANAG (AR) magazines.
- [https://steyrarms.com/steyr-aug-a3-m1.html](url)

I assumed, as i saw in json file that Steyr had `stanag30` flag, that we are talking about converted or NATO version rifle.

**Comment by illi-kun** [comment] 2016-09-26 10:38
So, for game play reason, we need to switch it to 
> the standard version that accepts genuine Steyr AUG magazines

**Comment by mugling** [comment] 2016-09-26 13:05
> Mini-14, Heckler and Koch G36, and Steyr AUG are all using STANAG magazines right now

Mini-14 only accepts the 10-round proprietary magazine so this isn't a problem.

The G36 could have it's own magazine but I'd prefer if we could somehow offset that disadvantage via item stats. Suggestions?

Steyr Aug should gain two new polymer magazines. The gun already has lower `volume` so this does provide a difference in aim speed to offset the fact you cannot add a stock mod. The polymer magazines should exclude the `BULKY` for the 42-round variant offset their rarity.

> which they can't actually do in real life without special conversions

This can be modeled as well - a magazine conversion mod allowing use of the more plentiful STANG-30 magazines.

> are the survivor-crafted one

This is a near-useless item. If anyone has any suggestions for improving? I'd rather replace it with a decent semi-auto alternative to the Mini-14 otherwise.

**Comment by thethunderhawk** [comment] 2016-09-28 23:22
"Whilst I was writing the original implementation people regularly disputed the intensely technical minutiae - not one bit of which actually made a difference to how fun it was to play"

Made a github account to say this, which I'm sure undermines my credibility somewhat, but I love this game and this problem just significantly affected my enjoyment of the game. Just the other day I put my character at tremendous risk to acquire a STANAG drum mag for my M4, and it turns out I did it all for nothing. Needless to say, I was incredibly dissapointed and pissed off. This (the STANAG drum mag not being compatable with my M4) makes absolutely no sense and definitely ruined my immersion.

**Comment by mugling** [comment] 2016-09-28 23:23
> and it turns out I did it all for nothing

You do know that the item info display lists the compatible magazines?

**Comment by BorkBorkGoesTheCode** [comment] 2016-09-29 00:23
>The G36 could have it's own magazine but I'd prefer if we could somehow offset that disadvantage via item stats. Suggestions?

We could add the C-Mag 100-round drum.

**Comment by Rivet-the-Zombie** [comment] 2016-09-29 00:38
We can change the AUG's slots and such at the same time we change its magazines.

**Comment by mugling** [comment] 2016-09-29 00:40
Those changes do sound like they would make it a much more interesting item

**Comment by BorkBorkGoesTheCode** [comment] 2016-09-29 00:55
The AUG also has backup iron sights.

**Comment by thethunderhawk** [comment] 2016-10-01 17:22
> You do know that the item info display lists the compatible magazines?

Yeah, but it's an M4. Didn't think to check something so obvious, I just naturally assumed it would be compatible since I had no reason to think otherwise.

**Comment by Kole6738** [comment] 2017-10-19 00:38
I don't know what the proper etiquette for resurrecting an issue is but as it's still open I assume that means it's still open for discussion. I actually came across this in-game and was wondering what was up with the STANAG magazine compatibility nerf, and was about to open a new issue on this with a quick PR when I noticed that this was already open. After reading through the comments, I believe the discussion was whether "balanced gameplay" or "realism" should take priority. My thoughts on the matter are that having based the guns off of real-world weapons, people should be able to apply their previous experiences against the guns. This isn't an issue for weapons with no real-world counterpart, but saying that it isn't an issue because it has to be nerfed somehow seems a touch silly to me; a slight exaggeration would be if you couldn't drive a car without racing gloves because cars had to be nerfed - nobody entering the game would even think to consider that, because cars driving without racing gloves is something we carry over from our notions of the real world. I'm not saying we should start adding separate filters to cars or anything, but I do feel we should be looking at this again. In support of my argument, I cite a section of the C:DDA design outline:
"Reality-based: At its core, DDA is based in the real world.  One that has been changed in extreme ways, but still very much the real world as we know it.  The things in the game that exist in the real world should act like their real-world counterparts; things that are extrapolated from real-world things should hold true to the real-world principles involved, and things that do not exist in the real world are free to act in whatever internally consistent way they want.  This includes things like population density, item stats, item spawn frequencies.  It’s a simulation, so there are of course limits to the verisimilitude, and in fact it’s generally not a very good simulation at all, but the *goal* is to depict reality."
My opinion of this is that STANAG magazines will work in any STANAG weapon in the real world, and that interchangeability is an important facet of the STANAG magazine system. In conclusion/tl;dr I feel stanag weapons should be able to take STANAG magazines unless there is a critical lore or code reason this shouldn't be done, which after (an admittedly cursory) glance doesn't seem to be the case.

**Comment by kevingranade** [comment] 2017-10-19 06:41
OMFG, what a dumpster fire.  Please ignore everything mugling said here,  he does not speak for the project and should not have been given any credence here.
Please feel free to open that PR, the *only* reason to disallow a magazine type is because it is incompatible IRL.  Your application of the design outline is spot-on.

**Comment by kevingranade** [comment] 2017-10-19 19:07
BTW, let's not lose the productive suggestions that also surfaced here:
> e: Also, isn't there some kind of misfire mechanic? High capacity magazines tend to have feed issues or something

> 223 rifles that don't accept STANAG magazines

> There are some STANAG rifles that we could still block drums and such on simply due to ergonomics

> Standard Styer Aug uses dedicated 30 and 42 polymer magazines.

> The G36 could have it's own magazine
> We could add the C-Mag 100-round drum.

**Closed** 2017-10-20 02:32 UTC
Labels: Magazine, Suggestion (Discuss)
