### ISSUE TITLE
Varying wheel quality of "wild" vehicles

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14758] opened 2016-01-08 13:30 UTC
This might be more work than it's worth: Instead of pre-spawned vehicles having either all wheels broken or pristine, perhaps make their durability status random? Or are there any problems with this?

**Comment by kevingranade** [comment] 2016-01-08 17:13
There's nothing wrong with adding it, but the main driver of having broken
tires is making the vehicles undriveable, so replacing sometimea-broken
tires with damaged tires isn't the same thing.

**Comment by SeanMirrsen** [comment] 2016-01-09 09:27
I think the crux of the suggestion is making the cause of the car not being driveable more random. Right now a car you find on the road can be broadly split into: 
* Completely destroyed.
* Destroyed engine.
* Destroyed controls.
* Destroyed seats.
* Destroyed wheels.
* Destroyed gas tank/battery.
* Empty gas tank/battery.
* Fully functional.

While nominally that's enough variety in itself, each category is clear-cut and definite, you only have random damage applied on top of the defining "missing piece". For me, personally, it has to do with immersion. I can imagine what happened to the car that has a wrecked engine, why a car might have an empty or damaged gas tank, even why it might have damaged controls or seats (though perhaps those should be merged, as one does not make much sense without the other). But why would a car have a full set of attached, but destroyed wheels? It would have stopped driving long before all four wheels were destroyed. If it was scavenged for wheels, it just wouldn't have any more wheels, and it'd just be a matter of attaching new ones (and would generate no scrap metal on replacement).

I can see also, why it is so confusing. Wheels attach directly to the frame, they can't be missing or they would take a welder to attach. There is no hub, no axle to attach them to. A limitation of the current system of simplified vehicles.

As far as the current suggestion, perhaps just have a more random amount of wheels destroyed? As in, any number so long as the result is "not enough wheels to drive car". The car will have been abandoned if it lost two wheels, and it's quite plausible to lose two wheels (say, two front wheels) in one accident. For lack of a better representation, the all-destroyed-wheels case we'll just have to pretend as having been scavenged.

**Comment by Coolthulhu** [comment] 2016-01-09 09:42
> As far as the current suggestion, perhaps just have a more random amount of wheels destroyed? As in, any number so long as the result is "not enough wheels to drive car".

That's doable, but needs to be done pretty strictly: currently a wheel with two wheels can drive just fine, as long as they're on the opposite sides of its center of weight.

**Comment by illi-kun** [comment] 2016-11-20 16:56
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-20 16:56 UTC
Labels: Suggestion (Discuss), Vehicle
