### ISSUE TITLE
Basic Power Armor being turned on does not reduce encumbrance

### ISSUE THREAD

**Issue by Sharkey-Ward** [CleverRaven/Cataclysm-DDA#32600] opened 2019-07-24 23:48 UTC
# Describe the bug

Upon turning a suit of basic power armor on, its encumbrance remains as if it was turned off.

# Steps To Reproduce

1. Put power armor on
2. turn it on
3. realize you're still encased in a steel coffin

# Expected behavior

Turning it on should reduce the encumbrance penalty, since the servomotors on the armor would engage and grant higher mobility than if you were manually trying to work the servos.

# Screenshots
![image](https://user-images.githubusercontent.com/53281045/61835844-eb9d8b80-ae53-11e9-9e3a-624945ad5ce1.png)
![image](https://user-images.githubusercontent.com/53281045/61835852-f22c0300-ae53-11e9-8956-cd53edc3aae3.png)

# Versions and configuration

 - OS:  Windows 10 
 - Game Version: 0.D-5805-g50eb478
 - Graphics version: Tiles
 - Mods loaded: Disable NPC needs, Modular Turrets, Salvaged Robots, Urban Development, Vehicle Additions Pack, Tanks and Other Vehicles.

**Comment by Petethegoat** [comment] 2019-07-24 23:50
Fixed in #32586, and sort of a duplicate of #32459

**Closed** 2019-09-06 05:49 UTC
Labels: (S1 - Need confirmation), <Bug>, Character / Player, Items / Item Actions / Item Qualities
