### ISSUE TITLE
Belts & harnesses eliminate volume of contents even while stored in inventory

### ISSUE THREAD

**Issue by DexterBobo** [CleverRaven/Cataclysm-DDA#29263] opened 2019-04-04 01:46 UTC
An item in a belt or harness (say a crowbar stored in a firefighter belt) adds no volume beyond that of the belt while stored in inventory (as opposed to being worn). So basically a crowbar "inside" of a firefighter belt stored in inventory takes up less volume than the crowbar alone. This seems... fairly illogical. Shouldn't the ability of a belt/harness to "disappear" the volume of an item stored in it not apply when the belt/harness is stored in your inventory?

**Comment by Photoloss** [comment] 2019-04-04 15:56
Are there any hard boxes where the disappearing volume *would* make sense? A scabbard takes in more than half of the total physical volume for most swords and the "bulk" is basically the same except maybe with rapiers and broadswords.

The distinction between "bulk" and physical volume is **very** important because like many weapons the crowbar has a ridiculously high volume of 1l while the 500g of steel it is supposedly made of have a volume of 0.0625l. Or the other way around a 1l crowbar would weigh a whopping 8kg, and those [do exist](https://www.amazon.com/dp/B00004S1WV).

If the "volume" is intended to include a kind of "bulkiness" penalty because a long rod is much harder to fit in your pocket than a 4cm cube then one could argue that the less "bulky" item is absorbed, or else recalculate the combined "bulk factor" of the belt/harness wrapped around the crowbar.

**Comment by wapcaplet** [comment] 2021-02-12 03:14
Cannot reproduce in 0.E-9572-g483cd09a89.

Tested with a fire axe (2 L) inside a firefighter belt (0.5 L), totaling 2.5 L. The total volume is the same whether worn, or inside a body bag.

![image](https://user-images.githubusercontent.com/238395/107726219-7d265580-6ca5-11eb-91e2-36677bc886ad.png)

Tested also with a tool belt containing a hammer, wrench, and screwdriver (totaling 3.06 L), and the whole kit inside a backpack. It has the same total volume as it does when worn.

![image](https://user-images.githubusercontent.com/238395/107726311-bbbc1000-6ca5-11eb-855e-49e0493668bd.png)

Looks fixed now.

**Closed by wapcaplet** 2021-02-12 03:14 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
