### ISSUE TITLE
Crash when hit by enemy

### ISSUE THREAD

**Issue by jonokrukov** [CleverRaven/Cataclysm-DDA#59110] opened 2022-07-09 16:04 UTC
### Describe the bug

A crash keeps occurring when I get hit by an enemy, but not every time.  It happened for a few zombies and an Exodii quadruped, so far.  It only started happening today, after I updated to the new experimental.  

### Steps to reproduce

1. Get hit

### Expected behavior

I expected to receive a hit and not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9077477/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9077478/debug.log)

**Comment by mqrause** [comment] 2022-07-09 16:11
Duplicate of #59105

**Closed** 2022-07-09 16:17 UTC
Labels: (S1 - Need confirmation)
