### ISSUE TITLE
Reload bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40788] opened 2020-05-24 03:22 UTC
Game spawns gun with no mag. Relaoding gun with mag crashes game

1. Spawn a gun from debug (it has no mag)
2. Spawn a mag in debug
3. Reload gun with mag, it is able to shoot.
4. View gun with mag in 'i'nventory
5. Game crashes

**Comment by anothersimulacrum** [comment] 2020-05-24 03:23
Please follow the template, it's there for a reason.
Duplicate of #40779

**Closed** 2020-05-24 06:58 UTC
