### ISSUE TITLE
field campsite tents drop large tent instead of tent.

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#16972] opened 2016-05-31 16:23 UTC
The tents at the field campsite are clearly small tents (3x3, 1x1 inside) but when prompted to take them down they drop the large tent item (5x5, 3x3 inside).

**Comment by Fallingferret** [comment] 2016-05-31 16:36
Yeah, it's a pretty old issue. It's probably pretty low on the list of things to fix since it's just tents. - #15569

**Comment by illi-kun** [comment] 2016-05-31 19:56
Closed as a duplicate of mentioned issue.

**Closed by illi-kun** 2016-05-31 19:56 UTC
