### ISSUE TITLE
Can use tool to craft something that consumes it

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18710] opened 2016-10-10 00:19 UTC
Crafting system regression:
- Spawn 2 rocks
- Craft batch size 2 of pebbles
- Both rocks consumed

Same thing probably affects the welding rig.

**Comment by keyspace** [comment] 2016-12-09 18:13
Can still reproduce on 6be479a (latest ATM) with rocks. This is after #19683

Can't reproduce for vehicle welding rig, tested having makeshift welders on hand.

* Having two makeshift welders leaves the component yellowed-out as expected (both in the general crafting and batch crafting menus).
* Having four makeshift welders doesn't allow making a batch of two welding rigs, but also doesn't yellow-out the component (it's green).

**Comment by Ramza13** [comment] 2019-11-03 01:39
Just tried to reproduce this and couldn't.  Spawned 2 rocks and a batch of 2 pebbles was unable to be selected.

**Comment by Night-Pryanik** [comment] 2020-04-13 16:50
Closing as non-confirmed for half a year.

**Closed by Night-Pryanik** 2020-04-13 16:50 UTC
Labels: (S1 - Need confirmation), <Bug>, Crafting / Construction / Recipes
