### ISSUE TITLE
Unable to escape from Mutation menu

### ISSUE THREAD

**Issue by greatjailb8** [CleverRaven/Cataclysm-DDA#54279] opened 2022-01-11 05:05 UTC
### Describe the bug

I can't exit the mutation menu if I pressed esc
![Screenshot (47)](https://user-images.githubusercontent.com/74266779/148883534-f9cbe830-c227-4f33-bd8f-c1a1cf66722c.png)

![Screenshot (48)](https://user-images.githubusercontent.com/74266779/148883551-57f01c55-72dc-49bc-83dd-45ec56aadeaf.png)

### Steps to reproduce

Press [ to pull up the Mutations menu, then press esc and see if you can get out of the mutations menu.

### Expected behavior

I expected the mutations menu to go away if I pressed esc.

### Versions and configuration

OS: Windows 10
Game Version: e23fd18
Graphics version: Tiles 
Ingame language: English
Mods loaded: Dark Days Ahead, Crazy Cataclysm
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7843849/debug.log)
m

**Comment by new02DAY** [comment] 2022-01-11 05:41
See #54279 and #54204.

**Comment by LeahLuong** [comment] 2022-01-11 20:19
#54279 is this issue . . .

**Comment by GuardianDll** [comment] 2022-01-11 23:32
Think new02DAY wanted to post #54039
So its duplication, and also was fixed in latest branch

**Comment by NetSysFire** [comment] 2022-01-13 10:28
Can not reproduce.

**Comment by hexagonrecursion** [comment] 2022-01-13 19:13
> Can not reproduce.

I could not reproduce this bug either

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: c8a49e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No name () []
]

**Comment by NetSysFire** [comment] 2022-01-13 19:15
Duplicate of #54039

**Closed by NetSysFire** 2022-01-13 19:15 UTC
Labels: (S3 - Duplicate), Info / User Interface, Mutations / Traits / Professions/ Hobbies
