### ISSUE TITLE
Bandits floating above ground level.

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#46876] opened 2021-01-19 10:17 UTC
# Describe the bug

Found a couple of bandits standing in few z levels above ground. Zombies trying to get to them below.

# Steps To Reproduce
I don't know.

# Expected behavior
Bandits standing on the ground level.

# Screenshots

![Screenshot 2021-01-19 120351](https://user-images.githubusercontent.com/26538192/105020128-972a9a80-5a4f-11eb-8a3a-f522927c6d2a.png)

![image](https://user-images.githubusercontent.com/26538192/105020645-3d76a000-5a50-11eb-9f6b-9eae80636b74.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9024-g785f240-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots]
]

# Additional context
Save file:
[Medon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5835167/Medon.zip)

**Comment by PaulBlay** [comment] 2021-01-19 12:13
Well they're there alright.  I loaded the save and teleported onto the roof. They don't fall down, but they can't move. I guess the code checks for valid spaces they can step to, but doesn't check that they are on a valid space in the first place when they spawn.

- OS: Windows x64 8.1
- Game Version: 0.E-9000-g8f6b461-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots]
]

**Comment by wapcaplet** [comment] 2021-02-19 23:08
Possibly a duplicate of #36635

**Comment by actual-nh** [comment] 2021-02-20 00:39
> Possibly a duplicate of #36635

It would appear it is confirmed.

**Comment by Night-Pryanik** [comment] 2021-04-04 09:08
Closing as duplicate of #36635.

**Closed by Night-Pryanik** 2021-04-04 09:08 UTC
Labels: (S2 - Confirmed), NPC / Factions, Spawn
