### ISSUE TITLE
Save spontaneously corrupted

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#8922] opened 2014-09-10 16:02 UTC
For whatever reason, a bunch of files are now full of NULL; artifacts, uistate and #WW~~~~~ included.

save at https://anonfiles.com/file/f9596fd0428e89ec9e4f4a79d99dc6ef

**Comment by illi-kun** [comment] 2016-04-14 22:18
I see no way to reproduce/test this bug. We didn't receive any similar reports for 1+ year, so I'm going to close this.

Feel free to re-open (with more specific details) if it still happens.

**Closed by illi-kun** 2016-04-14 22:18 UTC
Labels: Bug

**Comment by Vzor-** [comment] 2016-09-21 07:35
I have been a similar issue for dozens of builds over the course of a year or so. It is how I lose every character who lives long enough (uaually 1/2 a year to a year and a half). I don't mod, I have no hdd issues and my system is a clean windows 10 box. It's just windows with some IDEs and gimp. This time it failed, it gives me failed to read errors then loads a world, the map looks right, but my car is gone and walking around brings more errors. The save files mentioned usually go something like this "(normal map file so far) ..."t_grass","t_tree_blackjack","t_tree_young","t_gra<NULL><NULL><NULL><NULL>... (rest of file is thousands of null characters.)" The last time I closed the game everything was fine, I opened my laptop and went to continue and the save was corrupted. It was suggested to me that I mention this here but I can't think of a way to make it reproducible, so I can't imagine you could do anything more than shooting in the dark.

**Comment by narc0tiq** [comment] 2016-09-21 08:03
Since this issue was opened, I've seen (and heard of) this happening in an entirely unrelated context: app.config files edited using [the .Net framework's ConfigurationManager](https://msdn.microsoft.com/en-us/library/system.configuration.configurationmanager(v=vs.110).aspx) sometimes end up partially or completely overwritten by zeroes (NUL characters) with no rhyme or reason. It is not reliably reproducible, though I have an unconfirmed suspicion that it happens only on some machines (suggesting hardware failure or partly corrupted OS on those machines). (Counter-point: it seems to only happen to some files; is it about how the files are accessed? That might make it about a specific Windows API.)

Regardless, the only way to fully resolve this is to observe it happening (watching system calls, the contents of the file on disk, and any other pertinent data), so as you said, I can offer no more than shots in the dark. Maybe leave the machine running for a few minutes after closing Cataclysm, if you're in a habit of shutting it down immediately thereafter. Maybe launch a memory-hogging process after Cataclysm (Firefox/Chrome are good candidates) in hopes of forcing leftover caches to be written to disk before anything zeroes them (this may alternately make the problem more common). Maybe run the game on a different machine (a virtual machine, possibly). Maybe update or reinstall your OS or try a different OS.

Either way, it's really weird.

**Comment by TimMBlyth** [comment] 2017-08-31 06:41
Sorry for the necro, but I am also facing this issue.
However in reading your replies I believe I understand what the issue is.
I run ubuntu linux on an old laptop and often shut down my computer straight after closing C:DDA.
So as you said I suspect caching to be the culprit.

Cannot speak for other users problems however.

**Comment by kevingranade** [comment] 2017-08-31 14:56
There are a few measures we can take to try to avoid short reads and short
writes.

Add some flush calls when exiting a game (A game session, flushing when
exiting the program is likely too late).

Use a copy-and-move scheme for file writes.  In situations that result in a
corrupt file now, it would instead result in an old file, and it would also
be detectable.

On the mitigation front, we could write a checksum or hash along with the
with files.  With map files at least we can regenerate a similar file
instead of killing the game.

There are likely others, but those are the highest chance of making it work.
