### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by TheGrimMeeper** [CleverRaven/Cataclysm-DDA#38566] opened 2020-03-04 22:19 UTC
# Describe the bug
I'm down in some lab and consistently getting a segfault.
(Oh, also some weird tiles by the elevator that act impassible and unseen, but if you light a fire next to them it seems to fix it.)

# Steps To Reproduce
1. Load up attached savegame
2. Go around the passage to the southeast to fight that corrosive zombie
3. Get segfault

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12846-gd972c1c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4289918/Save.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4289911/config.zip)

**Comment by Funguss** [comment] 2020-03-04 22:35
Duplicate of #38556 and potentially fixed by #38555.

**Closed** 2020-03-05 01:12 UTC
Labels: (S3 - Duplicate)
