### ISSUE TITLE
Crash during save

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#59668] opened 2022-07-27 17:13 UTC
### Describe the bug

I just try to save and the game CTDs 

### Steps to reproduce

Save and get a crash

### Expected behavior

Not a crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 776aa63 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 776aa63
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff6a0211184[cataclysm-tiles.exe+0x221184]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x140221184),
    0x140221184    src/debug.cpp:1114    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff6a01fa941[cataclysm-tiles.exe+0x20a941]), 
    (libbacktrace: log_crash+0x1d2@0x14020a941),
    0x14020a941    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc11/11.2.0/include/c++/sstream:917    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x14020a941    src/crash.cpp:85    log_crash
  #2
    (dbghelp: @0x7ff6a01fab6f[cataclysm-tiles.exe+0x20ab6f]), 
    (libbacktrace: signal_handler+0x52@0x14020ab6f),
    0x14020ab6f    src/crash.cpp:137    signal_handler
  #3
    (dbghelp: @0x7ff6a0af6ed2[cataclysm-tiles.exe+0xb06ed2]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140b06ed2),
    0x140b06ed2    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffbe10b7ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffbe121229f[ntdll.dll+0xa229f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffbe11c1454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffbe1210dce[ntdll.dll+0xa0dce]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff6a050ee60[cataclysm-tiles.exe+0x51ee60]), 
    (libbacktrace: map::generate_lightmap(int)+0x398@0x14051ee60),
    0x14051ee60    src/lightmap.cpp:460    map::generate_lightmap(int)
  #9
    (dbghelp: @0x7ff6a055fb82[cataclysm-tiles.exe+0x56fb82]), 
    (libbacktrace: map::build_map_cache(int, bool)+0x136@0x14056fb82),
    0x14056fb82    src/map.cpp:8687    map::build_map_cache(int, bool)
  #10
    (dbghelp: @0x7ff6a02f9024[cataclysm-tiles.exe+0x309024]), 
    (libbacktrace: game::draw(ui_adaptor&)+0x78@0x140309024),
    0x140309024    src/game.cpp:3404    game::draw(ui_adaptor&)
  #11
    (dbghelp: @0x7ff6a0982572[cataclysm-tiles.exe+0x992572]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x1f4@0x140992572),
    0x140992572    src/ui_manager.cpp:411    ui_adaptor::redraw_invalidated()
  #12
    (dbghelp: @0x7ff6a025e502[cataclysm-tiles.exe+0x26e502]), 
    (libbacktrace: do_turn()+0x61a@0x14026e502),
    0x14026e502    src/do_turn.cpp:700    do_turn()
  #13
    (dbghelp: @0x7ff6a15465ed[cataclysm-tiles.exe+0x15565ed]), 
    (libbacktrace: main+0x16e8@0x1415565ed),
    0x1415565ed    src/main.cpp:789    main
  #14
    (dbghelp: @0x7ff69fff13c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #15
    (dbghelp: @0x7ff69fff14d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #16
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffbe0d67034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #17
    (dbghelp: RtlUserThreadStart+0x21@0x7ffbe11c2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by Zireael07** [comment] 2022-07-27 17:17
likely dupe of #59632 ?

**Comment by irwiss** [comment] 2022-09-02 22:12
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/59648

**Closed** 2022-09-02 22:20 UTC
Labels: (S1 - Need confirmation)
