### ISSUE TITLE
Attempting to reload any non-magazine-using ranged weapon causes crash

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#15462] opened 2016-02-18 20:19 UTC
![bork](https://cloud.githubusercontent.com/assets/11582235/13164345/25f2bb94-d67a-11e5-8334-65e7e1936718.png)

Tested so far in builds 4422, 4428, 4433, 4435, and 4436. ASCII, Windows.

As far as I can tell, if a ranged weapon does not have a magazine definition, attempting to reload it will crash the game. Have been testing as many permutations of ranged weapons as I can think of to determine if there are any likely exceptions.

Tested:
* Attempting to reload a crossbow causes crash.
* Attempting to reload symbol of judgement (Arcana mod) causes crash.
* Attempting to reload single-barrel shotgun causes crash.
* Attempting to reload Ruger LCR .22 causes crash.
* Attempting to reload a PPSh-41 (first example of a gun that has yet to be magazine-ified I could find) causes crash.

**Comment by mugling** [comment] 2016-02-18 22:35
Likely duplicate of #15450

**Comment by chaosvolt** [comment] 2016-02-18 22:36
Or in other words, the issue is even broader than that issue suggests.

**Comment by chaosvolt** [comment] 2016-02-19 02:07
Re-opened due to https://github.com/CleverRaven/Cataclysm-DDA/issues/15465 having not fixed this.

**Closed** 2016-02-19 02:12 UTC
