### ISSUE TITLE
crash when examining tile under character

### ISSUE THREAD

**Issue by Greysa** [CleverRaven/Cataclysm-DDA#32849] opened 2019-08-02 12:49 UTC
Describe the bug

Game crashes when examining a tile directly underneath character, regardless of what tile is or contains

Steps To Reproduce

Examine tile under character. (e, then 5)

Versions and configuration

- OS: Windows
    - OS Version: 10.0 1511
- Game Version: 0.D-6094-g668be41 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Survival Tools [More_Survival_Tools],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Mining Mod [Mining_Mod],
    Hydroponics [hydroponics],
    Simplified Nutrition [novitamins]
]

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3461241/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3461243/debug.log)

[Ellisport.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3461249/Ellisport.zip)

**Comment by DeadLeaves** [comment] 2019-08-02 14:05
got the same issue. Something beteween Build #9395  and #9416 (current as of writing) caused it.

**Comment by anothersimulacrum** [comment] 2019-08-02 14:22
Duplicate of #32848

**Comment by DeadLeaves** [comment] 2019-08-02 14:50
That one makes it sound like it only happens in vehicles, which is not the case.

**Comment by anothersimulacrum** [comment] 2019-08-02 15:07
You're right, I misread the post. It probably has the same cause though.

**Comment by sztosz** [comment] 2019-08-02 15:59
It may be same bug, It simply didn't occur to me, to check if game crashes outside of vehicle :scream:

**Comment by EvgenijM86** [comment] 2019-08-02 16:06
I can confirm this with latest git pull that I did ~20 minutes ago.

**Closed** 2019-08-02 16:51 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
