### ISSUE TITLE
Ability to load data from user directory

### ISSUE THREAD

**Issue by TingPing** [CleverRaven/Cataclysm-DDA#13826] opened 2015-10-26 02:46 UTC
Users should be able to install mods without having write permissions to the system (notably on linux). So it would be nice if data was also loadable from the users data dir.

From a glance this doesn't seem too complex since you already have modular `load_x_from_dir()` functions but I am not very familiar with how this all interacts.

**Comment by Midaychi** [comment] 2015-10-26 04:15
I do know the game will try to load from a mods directory if it exists within a map's save folder, but it generally crashes or errors out for me if said folder exists. I noticed this functionality when I was messing with the ambient sound mod and noticed a weird error about the game not being able to access the mods folder from the map in the saves folder.

**Comment by drbig** [comment] 2015-10-27 22:06
> since you already have

@TingPing I'd prefer that 'you' to be **we** ;)

I think there's a bunch of issues like that that boil down to the unfortunately vast difference between 'we contribute' and 'we just play'. Mods should work per user.

**Comment by TingPing** [comment] 2015-10-27 23:16
> I think there's a bunch of issues like that that boil down to the unfortunately vast difference between 'we contribute' and 'we just play'.

Of course, that line was all about me looking at the codebase to see how easy it would be to do; I am just not very familiar with the game or its code yet.

**Comment by kevingranade** [comment] 2015-10-28 01:54
I think it would be fairly easy to do, probably by adding a second mods
directory that is loaded along with the system mod directory.  While users
should be able to add mods, they shouldn't have write permissions to
whatever directory of mods is installed with the game.

**Comment by Leland** [comment] 2016-11-19 01:29
#16023 is a duplicate of this but has much more recent activity seen on it. This issue can probably be closed.

**Closed** 2016-11-19 19:32 UTC
Labels: Enhancement, Suggestion (Discuss)
