### ISSUE TITLE
Crash during character creaation.

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#31412] opened 2019-06-14 06:35 UTC
# Describe the bug

Crash during character creation, not always but frequently.

# Steps To Reproduce

1. New Game > Preset Character > Last Character 
2. Loading reaches Crafting Recipes 
3. Crash.

# Expected behavior

After selecting preset character, load into last stem of character creation and start a new game.

# Screenshots

![crash](https://user-images.githubusercontent.com/26538192/59488019-0a892500-8e87-11e9-82e2-33a8d3ea212f.PNG)

# Versions and configuration

 - OS: Windows 10 x64
 - Game Version: 0.D-4267-g74f7d04 (tiles)
 - Build: 9152
 - Graphics version: Tiles
 - Mods loaded: 
    Dark Days Ahead,
    Disable npc needs,
    (DP_Mod)Indicators: REMIX,
    Vehicle Addition pack,Tanks and Other Vehicles, Folding parts Pack,
    Urban Development,More Locations,Fuji's More Buildings,
    Mutant NPCs,Alternate Map key,
    More Survival Tools, Makeshift items mod,
    No Fungal Monsters,
    Sleep deprivation

# Additional context

[debug&crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3289308/debug.crash.zip)

**Comment by Night-Pryanik** [comment] 2019-06-14 07:34
I guess it's a dupe of #31399.

**Closed by Night-Pryanik** 2019-06-14 07:34 UTC
