### ISSUE TITLE
[Suggestion] Season-aware starting clothes

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#20168] opened 2017-01-31 05:53 UTC
Current clothes sets only make sense for starting in the cold spring, and not even for all of the professions. Having some clothes be season-aware would allow having appropriate attire for starting in any season, such as heavy jackets and coats for winter, and summer clothes for summer.

**Comment by sethsimon** [comment] 2017-02-01 21:27
Good idea, but this is a duplicate of #18647.

**Closed** 2017-02-02 17:47 UTC
Labels: Duplicate
