### ISSUE TITLE
Quarterstaff crafting gives no quarterstaff

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42704] opened 2020-08-04 11:59 UTC
# Describe the bug
Finishing crafting of quarterstaff saying that character lay out it on ground, but there is no staff
Maybe related to [42192](https://github.com/CleverRaven/Cataclysm-DDA/issues/42192).

# Steps To Reproduce
Get 2 lvl of fabrication and materials needed to craft quarterstaff
Craft it
Try to search for it

# Expected behavior
Get quarterstaff

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4811-g90e0c8b [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Графическая карта [Graphical_Overmap]
]

**Comment by ZhilkinSerg** [comment] 2020-08-07 00:07
Duplicate of #42192

**Closed by ZhilkinSerg** 2020-08-07 00:07 UTC
Labels: (S3 - Duplicate)
