### ISSUE TITLE
Sub-tabs in the crafting UI wrap the screen

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#16747] opened 2016-05-19 00:45 UTC
... and appears on the next line (breaking the borders):
![many_sub-tabs](https://cloud.githubusercontent.com/assets/5421954/15379240/3ff2b096-1d7c-11e6-9ff5-1caafa0c6475.png)

**Comment by Leland** [comment] 2017-05-04 13:27
#20706 is a duplicate of this but has more recent discussion going on. Closing.

**Closed by Leland** 2017-05-04 13:27 UTC
Labels: Bug, Crafting, Information / Interface, Validated
