### ISSUE TITLE
pebble uncraftable with couple of rocks

### ISSUE THREAD

**Issue by dodzy** [CleverRaven/Cataclysm-DDA#18687] opened 2016-10-08 09:22 UTC
start new game, get couple of rocks, can't craft pebble.
cataclysmdda-0.C-5647

EDIT:
same with stone hammer, stone knife etc

**Comment by Mecares** [comment] 2016-10-08 11:29
Still works fine on 5640.

**Comment by jim-huynh** [comment] 2016-10-08 12:03
I have the same problem with 0.C-18999-g8622a43 (5646).

It's so odd, if I have a chunk of metal AND a hammer in a toolbelt, I can craft it.  If the hammer is just in my inventory or on the ground, it doesn't work.

**Comment by codemime** [comment] 2016-10-08 12:10
I'll fix this one. Thank you for reporting.

**Comment by codemime** [comment] 2016-10-08 13:10
It appears my recent PR has nothing to do with this bug, it existed earlier. Haven't found the cause yet.

**Comment by mugling** [comment] 2016-10-08 13:12
Probably a duplicate of that earlier deconstruction bug. OP please update to master and report back

**Comment by jim-huynh** [comment] 2016-10-08 13:59
The bug starts with version 0.C-18999-g8622a43 (5646).  I opened up the same save game with version 0.C-18998-g4e1666c (5645) and crafting pebbles with just other rocks works.

**Comment by Coolthulhu** [comment] 2016-10-08 18:30
Only rocks?
Could be related to blazemod making rocks count_by_charges.
Last time I tested, the count_by_charges items seemed to work, but they weren't explicitly clamped to proper values.

**Comment by jim-huynh** [comment] 2016-10-08 19:28
In 0.C-18998-g4e1666c (5645), just having rocks within range/on me would allow pebbles crafting.  In 0.C-18999-g8622a43 (5646), even with a hammer (in a toolbelt), I couldn't craft pebbles unless I had a chunk of steel on me.

**Closed** 2016-10-09 09:10 UTC
Labels: Bug
