### ISSUE TITLE
Game slows to a crawl after batch boiling water

### ISSUE THREAD

**Issue by cjuicy12** [CleverRaven/Cataclysm-DDA#29650] opened 2019-04-16 22:12 UTC
**Describe the bug**  
My first run on the most recent experimental build (8794 in the Launcher) encountered a problem after beginning a batch craft for clean water from a large tank. After selecting the max quantity the game slowed down substantially. Upon completion, the game further slowed. Movement in any direction took about 2 to 3 seconds when it is normally near-instant. Attempting to navigate menus led to a full minute of load time, and sleeping caused the game to become completely unresponsive, with windows asking to kill the process.

**To Reproduce**  
1. Make a character and obtain the tools and materials needed to batch craft clean water. 
2. Proceed to batch craft clean water.
3. Attempt to move or perform actions afterward. 

**Expected behavior**  
The player should be able to batch boil water and not have the game slow to 1 frame every two or three seconds.

Save Download: [https://drive.google.com/file/d/1yKc6Wy4aqF-lKorSuxQ1zTvgzjXrkUIk](https://drive.google.com/file/d/1yKc6Wy4aqF-lKorSuxQ1zTvgzjXrkUIk/view?usp=sharing)

Version/Config
 - OS: Windows 10 Home (1803)
 - Game Version: 0.D-1855-gifff1726
 - Graphics version: Tiles
 - Mods loaded:   
  {
  "dda",
  "Tolerate_This",
  "SD_Magcrafting",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "craftgp",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "Mining_Mod",
  "mutant_npcs",
  "BIGRIVER",
  "mapgen_demo",
  "cityside",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "StatsThroughSkills",
  "safeautodoc",
  "manualbionicinstall",
  "RL_Classes",
  "aftershock",
  "No_Big_Zombies",
  "more_classes_scenarios",
  "Arcana",
  "novitamins",
  "DinoMod",
  "MMA"
   }

**Comment by ZhilkinSerg** [comment] 2019-08-09 08:56
I cannot reproduce the issue on current master - probably because we already made performance multiple optimizations since April.

I will close the issue, but feel free to report here (or open a new issue) if you still experience lag opn current version.

**Closed by ZhilkinSerg** 2019-08-09 08:56 UTC
Labels: (S1 - Need confirmation), <Bug>, Code: Performance, Crafting / Construction / Recipes, Items / Item Actions / Item Qualities
