### ISSUE TITLE
Gunmod cannot be reloaded

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#51667] opened 2021-09-17 04:30 UTC
### Describe the bug

On gunmod, such as rail-mounted crossbow or m203, those CANNOT be reloaded when added onto a rifle, even if the rifle is unloaded. It'll just say "Can't reload the M4A1+2"

### Steps To Reproduce

1. Get a rifle, in my case M4A1 (this is on stable by the way)
2. Get rail-mounted crossbow and/or m203, then add it to the rifle
3. Shoot the gunmod, those two should be immediately empty
4. Try to reload the gunmod, with bolts and 40x46mm HEDP in my case
5. You should get "Can't reload the M4A1+(insert mod amount here)"

### Expected behavior

Expected the gunmod to be properly reloaded. While the gunmod can be reloaded when NOT added to a gun, the moment it's an attachment on a gun, it stopped being able to be reloaded.

### Screenshots

![image](https://user-images.githubusercontent.com/71143790/133724668-3792cd2d-2e3f-4026-8774-709396075dce.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PLUUZ** [comment] 2021-12-13 22:18
I can confirm this on 0.F-3, OSX Curses, still a problem.

Rail-mounted crossbow is totally broken when mounted to a 9x19mmm pipe rifle with a rail slot added. It fires normally, but cannot ever seem to be reloaded while attached to the gun, either through the (r)eload command or from the (o) command in the firing menu. I presume other rail mounted weapons also don't work

Anyone familiar with the gun mod code know why this is?

**Comment by wapcaplet** [comment] 2021-12-14 02:15
May have been fixed by #53102, can anyone confirm on experimental?

**Comment by hexagonrecursion** [comment] 2022-01-04 07:56
Note: as far as I know 40x46mm M433 HEDP (id: 40x46mm_m433) referenced in the steps to reproduce is not suitable ammunition for a crossbow.

I can *not* reproduce the bug with an m4 carbine (id: m4_carbine), a rail-mounted crossbow (id: gun_crossbow) and an aluminum broadhead bolt (id: bolt_steel).

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Related https://github.com/CleverRaven/Cataclysm-DDA/issues/53367 https://github.com/CleverRaven/Cataclysm-DDA/issues/53365 https://github.com/CleverRaven/Cataclysm-DDA/issues/50031

**Comment by wapcaplet** [comment] 2022-01-04 12:43
> I can _not_ reproduce the bug with an m4 carbine (id: m4_carbine), a rail-mounted crossbow (id: gun_crossbow) and an aluminum broadhead bolt (id: bolt_steel).

Thank you for checking. I'm calling this one resolved/closed.

**Closed by wapcaplet** 2022-01-04 12:43 UTC
Labels: <Bug>, (S1 - Need confirmation), Items: Gunmod / Toolmod

**Comment by PLUUZ** [comment] 2022-03-14 13:04
Sorry to revive this, but since this bug exists in the last stable version is there any plan to backport the changes in pull #53102 to a new stable F release? Since being able to reload weapons mods is a pretty fundamental feature.

**Comment by Night-Pryanik** [comment] 2022-03-14 14:55
> Sorry to revive this, but since this bug exists in the last stable version is there any plan to backport the changes in pull https://github.com/CleverRaven/Cataclysm-DDA/pull/53102 to a new stable F release?

I'm not sure if this makes sense when we're already started the process of making a new stable.

**Comment by PLUUZ** [comment] 2022-03-14 16:54
Ah, ok. I thougth the new stable is still months and months away
