### ISSUE TITLE
Labor cost for 'Sifting through wreckage' should use 'Stamina/Time' rather than 'Hunger + Thirst'

### ISSUE THREAD

**Issue by subhazard** [CleverRaven/Cataclysm-DDA#19114] opened 2016-11-02 22:46 UTC
As most people don't do this, this probably got forgotten about, causing it to miss an update.

Almost all labor costs Stamina and Time, versus calories and thirst.

You can go from Full and Slaked to Dehydrated and Starving in about 10 tiles of wreckage.

As a reminder, it takes 30 minutes of constant sprinting to burn 500 calories, which is the equivalent of 4 slices of bacon.

This is also the most calorie expensive exercise out there, so anything else is going to be less than that.

Your stamina and glycogen stores will deplete FAR BEFORE you starve to death from working.

Thirst on the other hand, that's fine, but it's still way too high for the task.  Shoveling 1 square meter of metal bits and pieces shouldn't dry my tongue out immediately.

**Comment by MisterFox** [comment] 2016-11-02 23:11
Definitely an oversight -- if you have a tool with Digging 3 (entrenching tool off the top of my head), then it takes no time or hunger at all, but that doesn't mean it's working as intended with Digging 2 or less.

**Comment by bdragon28** [comment] 2016-11-02 23:32
The problem is when you are at the digging 1 point. You totally lose out on the two times it squares the number (once in iuse::dig and once in activity_handlers::clear_rubble_finish) and you're paying the full 10 hunger and thirst cost.

**Comment by bdragon28** [comment] 2016-11-02 23:38
Hmm, personally I would rip out the direct thirst and hunger mods and just add a do_turn handler to mod_stat the stamina similar to the way butcher_do_turn does it.

**Comment by subhazard** [comment] 2016-11-02 23:59
Well yeah, that's _precisely what I'm saying_

**Comment by pisskop** [comment] 2016-11-09 20:24
Wreckage costing food makes sense to me.  its hard grueling work, and stamina is an immediate resource.  I dont think that its fair to sift through wreckage to get the goodies and not pay a resource cost.

**Comment by MisterFox** [comment] 2016-11-10 03:36
I disagree -- your argument can also be applied to butchering/smashing zombies, which is also free to do if you're safe, so therefore should cost significant hunger/thirst to perform.

Additionally, if you use a tool with Digging 3, the hunger/thirst cost is either minimal or eliminated entirely. I agree that it would be difficult to clear rubble with a stone on a stick, but not that it should be such an extremely taxing action as to go from full/slaked to famished/dehydrated in two hours of work.

**Comment by Coolthulhu** [comment] 2016-11-10 11:15
Stamina doesn't make sense since you're not going to need to run away fast.

**Comment by MisterFox** [comment] 2016-11-10 16:32
You don't need to run away fast when all the zombies are dead and you're just finishing then off

**Comment by pisskop** [comment] 2016-11-10 17:37
You do if hordes are on

**Comment by MisterFox** [comment] 2016-11-10 17:45
Repeatedly, doesn't low stamina already drain hunger and thirst? I recall getting very hungry from trying to ride a bicycle on a low strength character. If that's not just a special case, then adding stamina drain to digging would at least make it calculate properly.

**Comment by pisskop** [comment] 2016-11-10 18:16
I think the hunger/thirst from a bike comes from the power generated by the foot pedals (an engine that is fueled by you) rather then the low stamina.

**Comment by cdag** [comment] 2016-11-11 23:04
Just tried to dig up some wreckage with fast metabolism and a makeshift shovel with level 2 digging. 4 hours passed in game... 1 MRE, 50 units of jerky and 10 bottles of water later I realized I was only half way through digging all this up and just totally gave up on it. This needs to be balanced better... this isn't based in realism or fun in the game. I can understand it costing thirst, I just don't understand the insane hunger cost.

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-11 23:12
Repeated digging could cause pain instead of hunger.

**Comment by cdag** [comment] 2016-11-11 23:15
That would make more sense... I'm not saying this should be removed entirely, just balanced... If anyone here has ever worked a labor type of job in their lives they would understand its exhausting and will make you thirsty but the affect on hunger would be minimal. Is it possible to have it cost pain & thirst?

**Comment by Treah** [comment] 2016-12-15 17:33
I agree this is not a suggestion but a bug. There is no reason digging though rubble should cost as much hunger as it does. You can be full / slacked and dig up 3 tiles and be at hungry thirsty. To dig up any reasonable amount of space you need a shopping cart full of water and food to even make it feasable. Dowing an entire thanksgiving meal ( no not a plate like all the food ) is not realistic in anyway whatsoever  to clear 2 square meters of rubble. The main issue here is that normally you will not have a tool with 3 digging as you would be using a stone tool to obtain rocks to make a forge and then can proceed to make something that has reasonable digging. By the time you get a tool to digging 3 it becomes irrelevant. 
1. its not realistic 
2. Its tedious to keep stopping after 2 digs to eat and drink
3. it makes no sense in game mechanics either with the rest of the game. 

I agree with cdag it needs balanced better but not removed entirely. I think the thirst is right on par ( you drink alot of water when doing this type of work ) but the hunger is just insane.

**Comment by DaviBones** [comment] 2017-08-01 01:37
Taking into account the discussion above, and my own experience, I propose the following:

1. Shoveling wreckage time is lengthened: currently it seems a bit short. Lengthening it to (30 minutes/shovel quality) seems reasonable. This way, it is a day-long project (or perhaps two if you have a poor quality tool).
2. While shoveling, you accumulate hunger at +25% the rate (IRL this would mean that a full day spent shoveling costs about 500 extra calories, seems reasonable) and accumulate thirst at +100% rate. This increase is uniform across all tool quality, although the additional time requirement means you will still consume more water and food when using lower quality tools.

I am experienced with C++ and would be happy to make a pull request myself, if someone can point me in the direction of where to find the relevant code.

**Comment by Night-Pryanik** [comment] 2017-08-01 16:25
@DaviBones, `dig` in iuse.cpp and `clear_rubble_finish` in activity_handlers.cpp.

**Comment by DaviBones** [comment] 2017-08-26 14:13
This issue can probably be closed now that #21537 has been merged.

**Closed** 2017-08-26 15:23 UTC
Labels: Suggestion (Discuss)
