### ISSUE TITLE
Hospital wheelchairs produce a lot of noise/lag

### ISSUE THREAD

**Issue by Unfortun3** [CleverRaven/Cataclysm-DDA#44265] opened 2020-09-19 16:05 UTC
# Describe the bug
Random wheelchairs in a hospital for some reason produce a lot of noise which causes game to lag. I've encountered this bug twice. First one was like 1.5 to 2  weeks ago another time today. I'm always using latest experimental version btw. It might be something to do with vehicle collision but I'm not sure.

# Steps To Reproduce
Well just find a hospital and check your log for these message
![image](https://user-images.githubusercontent.com/67174940/93671258-29bf2b00-faaa-11ea-8a9f-012292bdc297.png)

### **Versions and configuration**
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6052-gfacb03d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by wapcaplet** [comment] 2020-09-24 03:36
Confirmed in 0.E-6177-g 9f4a1b841d

1. Find a hospital
2. Go to the 2nd floor
3. Find an elevator shaft
4. Push one (1) foldable wheelchair into the elevator shaft
5. Hear hundreds of crashes and watch the game slow to a crawl

![image](https://user-images.githubusercontent.com/238395/94097934-bc323800-fde4-11ea-8207-8203235c8fbb.png)

**Comment by wapcaplet** [comment] 2020-11-22 17:09
This appears to have been fixed by #45515 - I cannot reproduce the multiple smashing and lag issue any more. When pushing a wheelchair down an elevator shaft, it simply crashes once at the bottom, and the game continues as normal. Closing.

**Closed by wapcaplet** 2020-11-22 17:09 UTC
Labels: (S2 - Confirmed), <Bug>, Vehicles
