### ISSUE TITLE
can of soup goes from fresh to rotten immediately after opening

### ISSUE THREAD

**Issue by MT-Arnoldussen** [CleverRaven/Cataclysm-DDA#25314] opened 2018-09-02 13:39 UTC
**Describe the bug**  
Can of soup goes from fresh to rotten immediately after opening

**To Reproduce**  
1. Find old can of soup.
2. Eat it from it and put it down.
3. It's rotten.

**Expected behavior**  
It should not immediately rot.

**Screenshots**  
![capture](https://user-images.githubusercontent.com/3521568/44956543-e2b36c80-aec5-11e8-9f54-8a673573f331.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Build 7820
 - Graphics version: Tiles
 - Mods loaded: [  "dda",  "no_npc_food",  "more_classes_scenarios",  "filthy_morale",  "Nonperishable_Overhaul",  "speedydex",  "StatsThroughKills",  "makeshift",  "More_Survival_Tools",  "alt_map_key",  "mutant_npcs",  "npc_traits",  "boats",  "deoxymod",  "blazemod",  "Tanks"]

**Additional context**  
These issues are related, but are all old and closed, so I made this new one:
#8089, #8040, #7049

**Comment by nexusmrsep** [comment] 2018-09-02 16:49
Whatever causes that, it cannot be simply reproduced by spawning said soup in a can, progressing time and opening it:
![image](https://user-images.githubusercontent.com/39925111/44958456-cec93400-aee0-11e8-9940-51c27b6ba518.png)

**Comment by MT-Arnoldussen** [comment] 2018-09-02 17:39
It was spawned by the map. By the time the house it was in was in my reality bubble, it was already day 40 or so.

**Comment by nexusmrsep** [comment] 2018-09-02 20:47
I wonder if #24209 could be the culprit here. There must be a way to reproduce it.

**Comment by Night-Pryanik** [comment] 2018-10-11 16:35
Duplicate of #25001.

**Closed by Night-Pryanik** 2018-10-11 16:35 UTC
Labels: (S2 - Confirmed), <Bug>, Food / Vitamins
