### ISSUE TITLE
Items put in a sheath attached to MOLLE webbing belt could disappear from inventory

### ISSUE THREAD

**Issue by Syler1984** [CleverRaven/Cataclysm-DDA#71488] opened 2024-02-04 04:42 UTC
### Describe the bug

Certain actions can cause attached sheath to not register its contents properly. Putting anything inside will not add to its volume capacity and will disappear from inventory screen while still adding to inventory weight. Sometimes contents will spill on the ground.

### Attach save file

[Landa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14155511/Landa.zip)

This save features a dude with sheath full of knives. Sometimes they just randomly spill.

### Steps to reproduce

Have MOLLE webbing belt, sheath, couple of knives.

1. Wear a webbing belt.
2. Attach a sheath to the webbing belt.
3. Set priority 10 for sheath in webbing belt pocket manager.
4. Weild a knife.
5. Put the knife in the webbing belt ('w' -> knife -> webbing belt) [not sheath, in the belt]
Now in pocket manager knife should be displayed as being inside a sheath.
6. Wield the same knife again.
7. Put the knife in the sheath ('w' -> knife -> sheath (which should be inside webbing belt)).
8. Aaaaaand its gone!
You can now put infinite amount of knives in that sheath and they all will dissapear also. Any 'a' action on webbing belt, like removing the sheath will cause all knives to drop on the ground.
Also, knives still contribute to carry weight, you just can't see them anywhere and sheath now functions like a magic pocket.

### Expected behavior

Sheath should properly register its contents in any circumstances.

### Screenshots

This is me putting 10 (or 12?) knives in a webbing belt infinite sheath:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/12933526/b3700200-c1f2-4ead-ad84-a1c3ac65a851)

All pockets appear empty:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/12933526/26db27b8-3070-414f-b281-e687de56f6bc)

### Versions and configuration

Version: 4aee1f3
OS: Windows 11

**Comment by ANickelN** [comment] 2024-02-04 04:50
/confirmed
This can be reproduced with any attached MOLLE pouch and any item that would fit within.

**Comment by Vaskritaya** [comment] 2024-02-04 09:15
dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/70561

Feel like this bug should be a .H release blocker, considering how easy it is to encounter through standard gameplay and how disruptive it is.

**Comment by Kamayana** [comment] 2024-02-04 11:51
Looks like extra migration pockets are getting added to the belt somewhere, which is throwing things off. Right on load, you can sheathe it properly. Looking inside of `item_contents::get_added_pocket`, the iterator starts at the end and goes back one to get the added CONTAINER at index 4. Works correctly. Details:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/178f5ab5-15ba-4296-851a-c9ec199aa62d)

Afterward interacting with either the belt or the holster though, an extra MIGRATION pocket is getting added on, so the function returns a MIGRATION pocket at index 5. Incorrect, items falls out. Details:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/b502240a-41d4-445b-82eb-786416f0d4bc)

**Closed** 2024-02-11 04:06 UTC
Labels: <Bug>, (S2 - Confirmed), Mechanic: Pockets
