### ISSUE TITLE
Game no longer warns me about approaching enemies when using bandage

### ISSUE THREAD

**Issue by ReynTheLord** [CleverRaven/Cataclysm-DDA#53703] opened 2021-12-23 07:11 UTC
### Describe the bug

As in the title. I try to use a bandage or a recovery item, and the game doesn't warn me about incoming danger, resulting in my death

### Steps to reproduce

1. Use bandage or other healing item when enemies might wander in
2. Get killed by a fucking raccoon 

### Expected behaviour

I expect to get warned when danger approaches when I use bandages so I don't get murdered.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 275dd79 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Zireael07** [comment] 2021-12-23 09:36
dupe of #53658 ?

**Comment by morthein** [comment] 2021-12-23 15:12
I wonder if #53644 applies to you.  

Are you using (e) or (a) to use bandages?  

(e) gives prompts (a) doesn't.  I put in this bug report a bit ago.

**Comment by ReynTheLord** [comment] 2021-12-23 22:05
> I wonder if #53644 applies to you.
> 
> Are you using (e) or (a) to use bandages?
> 
> (e) gives prompts (a) doesn't. I put in this bug report a bit ago.

Thats likely the case

**Comment by RoyBerube** [comment] 2021-12-24 12:56
A clue to why eat and activate behave a little different:
https://github.com/CleverRaven/Cataclysm-DDA/blob/83b08cc9b683b176bf4d1bfdc2a8fd0cde752dfe/src/game_inventory.cpp#L1086-L1090

'E'at creates a menu activity so that when the eat activity is done it comes back to the eat menu again. Activate does not do that.

I think this explains why 'E'ating gets more interrupt messages. I'm seeing some odd behaviour in where saying yes to cancel still allows the bandage activity to finish.

**Comment by pjf** [comment] 2021-12-25 10:48
I just lost a character while "eating" a bandage. I got the interrupt message, and selected to stop, but my character kept on bandaging even while being pummelled anyway. ;(

Given we're seeing multiple reports of this in #53644 and #53658, as well as here, I think this definitely counts as a confirmed bug.

**Comment by mkrutov** [comment] 2021-12-27 02:17
I'd just like to highlight that this and #53658 are different bugs - one doesn't prompt you for interruption, second one progresses time forward despite agreeing to interruption prompt.

**Comment by hexagonrecursion** [comment] 2022-02-04 09:13
@wapcaplet. IMHO this is either a duplicate of  #54672 (if OP used [E]at *and* the prompt did not interrupt the activity) or of #53644 (if OP used [a]pply and got no prompt at all). Either way it should be closed as a duplicate.

**Closed** 2022-02-04 12:36 UTC
Labels: (S2 - Confirmed), Monsters, Quality of Life, 0.G suggested release blocker
