### ISSUE TITLE
Confusing message while attempting to load guns

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#50260] opened 2021-07-27 18:15 UTC
### Describe the bug

`player::list_ammo` lists available "ammos" for both the gun and the magazine in that gun(and magazines in added mods too). 
So for normal guns(with a magazin in it), both bullets and magazines are considered as available "ammo", but actually only magazines can be accepted, since the function `item::is_reloadable_helper` will return `magazine_compatible().count( ammo )` which is obviously 0 if bullets are selected. 
Hence, the message "can't reload the %s" is showed while trying to load the gun with bullets which is confusing for the player.

### Steps To Reproduce

1. Make a player with a gun with a magazine, get some (actual) ammos.
2. Reload the gun using the bullets.
3. Operation failed, get the message "can't reload the %s" and move points are wasted(which can be lethal).

### Expected behavior

The actual ammo should be accepted, although it seems weird to directly reload a magazine in a gun with bullets.
Or disallow bullets to be listed as available ammo unless the gun has integrated magazine.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cd73ed4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by LaVeyanFiend** [comment] 2021-07-27 18:15
Duplicate of #49989

**Comment by actual-nh** [comment] 2021-07-27 22:03
I have no idea how I didn't see your message, LaVeyanFiend. Sorry! @Menschheit, please report any pertinent details on #49989.

**Closed by actual-nh** 2021-07-27 22:03 UTC
Labels: (S3 - Duplicate), Info / User Interface, Items: Ammo, Items: Magazines
