### ISSUE TITLE
Crash on loading NPC at Evac Center

### ISSUE THREAD

**Issue by KevlarNet** [CleverRaven/Cataclysm-DDA#30634] opened 2019-05-18 23:32 UTC
When approaching an Evac Center for a mission. The game throws an Error when loading in NPC's.

# Steps To Reproduce

1. Load attached saved game.
2. Drive towards Evac Center.
3. Crash so hard you fly through your windscreen and land on your desktop.

# Expected behavior

Not to CTD.

# Screenshots

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3178-g258b2e8
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194603/config.zip)
[Hamilton City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194604/Hamilton.City.zip)

**Comment by KorGgenT** [comment] 2019-05-18 23:35
duplicate of #30525

**Closed by KorGgenT** 2019-05-18 23:35 UTC
