### ISSUE TITLE
failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0,75" to a number 

### ISSUE THREAD

**Issue by MoonlitRiverlight** [CleverRaven/Cataclysm-DDA#73790] opened 2024-05-14 22:10 UTC
### Describe the bug

5 minutes into the playthrough. Fought a couple boatmen, came back to camp bleeding, Liam ran over to patch MC up, segfault moments later. Error below happens when reloading after a few turns and freezes the application.

"
 DEBUG    : failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0,75" to a number

 FUNCTION : double var::eval(dialogue&) const
 FILE     : src/math_parser.cpp
 LINE     : 241
 VERSION  : cdda-experimental-2024-05-14-1902 c7d88dc
"

### Attach save file

[Annona-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15314226/Annona-trimmed.tar.gz)

### Steps to reproduce

1.Load the character.
2.Let a couple minutes pass.

### Expected behavior

No crashes when lazing around the house at first minutes of game.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.4 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-05-14-1902 c7d88dc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15314251/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15314252/debug.log)

**Comment by Standing-Storm** [comment] 2024-05-15 01:32
Probably related to #71635

**Comment by RenechCDDA** [comment] 2024-05-15 12:15
Duplicate of #71635

**Closed by RenechCDDA** 2024-05-15 12:15 UTC
Labels: (S1 - Need confirmation)
