### ISSUE TITLE
[BUG] Wooden needle can't be reloaded

### ISSUE THREAD

**Issue by AGasCanister** [CleverRaven/Cataclysm-DDA#40297] opened 2020-05-07 16:51 UTC
# Describe the bug
When you try to reload a wooden needle with thread, it will get used but the charges won't get added

# Steps To Reproduce
1. Have a wooden needle and thread
2. Try to reload the wooden needle
3. The thread will get consumed but the wooden needle won't get any charges, will stay at 0/200

# Expected behavior
If you reload a wooden needle with 80 of thread, the needle should have 80/200 instead of 0/200

# Screenshots
![image](https://user-images.githubusercontent.com/55928412/81321598-14190e00-9093-11ea-9d0d-2f3c923b14a8.png) 
![image](https://user-images.githubusercontent.com/55928412/81321615-1aa78580-9093-11ea-9195-1ef7ad51bcba.png)
![image](https://user-images.githubusercontent.com/55928412/81321658-2b57fb80-9093-11ea-9b06-c95ee676bc1d.png)
![image](https://user-images.githubusercontent.com/55928412/81321699-3743bd80-9093-11ea-925f-60dac8961665.png)
(It's also not a visual bug, I can't even use it)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-05-07 16:58
Duplicate of #40125

**Closed by ZhilkinSerg** 2020-05-07 16:58 UTC
Labels: (S3 - Duplicate)
