### ISSUE TITLE
Power Armor UPS bug 

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16160] opened 2016-04-11 15:58 UTC
version: 0.C-12802-g1f2abca (tiles).

Put on Power Armor, picked up a full UPS. Activate power armor, walk in any direction, get an error message:
Tried to set ammo of none for UPS

in file item.cpp
line: 245
function ammo_set

But it does decrement the UPS charge.

If I turn on my bionic UPS, it works fine

**Comment by DanmakuDan** [comment] 2016-04-13 02:24
I wasn't able to repeat the issue with 12802 or the latest at 0.C-12833. Maybe there is a mod interfering with the UPS usage?

**Comment by Lazasar** [comment] 2016-04-13 08:30
Could be, I am only using some mods that come with the game, not separately downloaded.

**Comment by DanmakuDan** [comment] 2016-04-13 19:35
If possible, could you upload a copy of your save file?

**Comment by Lazasar** [comment] 2016-04-14 06:13
Sure. DO you need more than just the one I attached?

[#TW9yZ2Fu.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/218498/TW9yZ2Fu.zip)

**Comment by mugling** [comment] 2016-04-14 07:34
I suspect this was resolved by recent changes to `ammo_set`. Can you check against `master`?

**Comment by Lazasar** [comment] 2016-04-14 09:26
Nope, still happening,

**Comment by mugling** [comment] 2016-04-14 09:39
What is the exact debugmsg?

**Comment by mugling** [comment] 2016-04-14 09:40
Also which mods

**Comment by Lazasar** [comment] 2016-04-14 10:31
Debug message is exactly as I listed above:
Message: Tried to set ammo of none for UPS
file: item.cpp
line: 245
function ammo_set

Mods: 
Folding Parts Pack
Mideavil and Historic Content
More Survival Tools
No Triffids
No Fungal Monsters
Prevent Zombie revivification
Vehicle Additions Pack

**Comment by mugling** [comment] 2016-04-14 10:48
> Debug message is exactly as I listed above:

And you're using either `master` or the latest experimental build. That `debugmsg` doesn't appear in the source but a similar one does following some changes to that function

**Comment by Lazasar** [comment] 2016-04-14 11:12
latest experimental, and it has persisted through 4 or 5 updates over the last few days

**Comment by mugling** [comment] 2016-04-14 11:23
That's a slightly different message than your original post but does now match `master`. I'll look into it

**Comment by Lazasar** [comment] 2016-04-14 12:37
Yeah, I realized that when I took the screenshot. I thought I had copied it down exactly. Apologies

**Comment by mugling** [comment] 2016-04-14 12:47
No worries - the specific version is just very relevant to this bug

**Comment by mugling** [comment] 2016-04-17 11:32
Cannot reproduce in `master`. Anyone else confirm?

**Comment by DanmakuDan** [comment] 2016-04-17 19:18
@Lazasar, could you upload the whole world save folder? I am also unable to reproduce the problem.

**Comment by Lazasar** [comment] 2016-04-18 09:00
Here ya go. Have my guy wearing the armor, with a UPS in his inventory for your convenience
[Gibsonia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/223372/Gibsonia.zip)
.

**Comment by DanmakuDan** [comment] 2016-04-18 16:47
@mugling:
At some point in debugging, the visitor interface is processing charges for a fake `UPS` in addition to a `UPS_off`.

In
```
template <>
VisitResponse visitable<inventory>::visit_items(
    const std::function<VisitResponse( item *, item * )> &func )
```
in visitable.cpp, line 175:
The `stack` referenced by `inv->items` contains the fake `UPS` item when it is visiting through the item stacks in inventory. 


Also a stacktrace:
```
[debug]#0  item::ammo_set (this=0xfc7de80, ammo="null", qty=4) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:245
[debug]#1  0x00000000006a0aef in item::<lambda(item*)>::operator()(item *) const (__closure=0x47e0a2b0, e=0x480d0540) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:4910
[debug]#2  0x00000000006a7538 in std::_Function_handler<VisitResponse(item*), item::use_charges(const itype_id&, long int&, std::__cxx11::list<item>&, const tripoint&)::<lambda(item*)> >::_M_invoke(const std::_Any_data &, <unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0x45c269a, DIE 0x48a0af2>) (__functor=..., __args#0=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0x45c269a, DIE 0x48a0af2>) at C:/msys64/mingw64/include/c++/5.2.0/functional:1857
[debug]#3  0x0000000000d8c9f0 in std::function<VisitResponse (item*)>::operator()(item*) const (this=0xfc7e2f0, __args#0=0x480d0540) at C:/msys64/mingw64/include/c++/5.2.0/functional:2271
[debug]#4  0x00000000010fe25c in visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (__closure=0xfc7e220, it=0x480d0540) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:134
[debug]#5  0x0000000000ea4c40 in std::_Function_handler<VisitResponse (item*, item*), visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (__functor=..., __args#0=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0xc2fee77, DIE 0xc4a9cec>, __args#1=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0xc2fee77, DIE 0xc4a9cf1>) at C:/msys64/mingw64/include/c++/5.2.0/functional:1857
[debug]#6  0x0000000000d8ca62 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=0xfc7e220, __args#0=0x480d0540, __args#1=0x0) at C:/msys64/mingw64/include/c++/5.2.0/functional:2271
[debug]#7  0x0000000000b87bb0 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x480d0540, parent=0x0) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:142
[debug]#8  0x0000000000b87cd5 in visitable<item>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=0x480d0540, func=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:172
[debug]#9  0x0000000000cd5d9b in visitable<item>::visit_items(std::function<VisitResponse (item*)> const&) (this=0x480d0540, func=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:134
[debug]#10 0x00000000006a0ddd in item::use_charges (this=0x480d0540, what="UPS_off", qty=@0xfc7ebf8: 0, used=..., pos=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:4936
[debug]#11 0x0000000000a8ce0e in player::<lambda(item*)>::operator()(item *) const (__closure=0x47e12c00, e=0x480d0540) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\player.cpp:9095
[debug]#12 0x0000000000ab088e in std::_Function_handler<VisitResponse(item*), player::use_charges(const itype_id&, long int)::<lambda(item*)> >::_M_invoke(const std::_Any_data &, <unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0x9c426ee, DIE 0xa0f2004>) (__functor=..., __args#0=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0x9c426ee, DIE 0xa0f2004>) at C:/msys64/mingw64/include/c++/5.2.0/functional:1857
[debug]#13 0x0000000000d8c9f0 in std::function<VisitResponse (item*)>::operator()(item*) const (this=0xfc7e9f0, __args#0=0x480d0540) at C:/msys64/mingw64/include/c++/5.2.0/functional:2271
[debug]#14 0x00000000010fe35c in visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (__closure=0xfc7e7b0, it=0x480d0540) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:134
[debug]#15 0x0000000000ea4a00 in std::_Function_handler<VisitResponse (item*, item*), visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (__functor=..., __args#0=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0xc2fee77, DIE 0xc4ac264>, __args#1=<unknown type in C:\Base\Dev\CataDev\Cataclysm-DDA\Cataclysm-TilesDebug.exe, CU 0xc2fee77, DIE 0xc4ac269>) at C:/msys64/mingw64/include/c++/5.2.0/functional:1857
[debug]#16 0x0000000000d8ca62 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=0xfc7e7b0, __args#0=0x480d0540, __args#1=0x0) at C:/msys64/mingw64/include/c++/5.2.0/functional:2271
[debug]#17 0x0000000000b87bb0 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x480d0540, parent=0x0) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:142
[debug]#18 0x0000000000b87db1 in visitable<inventory>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=0x38b6fa70, func=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:182
[debug]#19 0x0000000000b87efa in visitable<Character>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=0x38b6f900, func=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:207
[debug]#20 0x0000000000cd610b in visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&) (this=0x38b6f900, func=...) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\visitable.cpp:134
[debug]#21 0x0000000000a8d43b in player::use_charges (this=0x38b6f900, what="UPS_off", qty=0) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\player.cpp:9099
[debug]#22 0x0000000000a8d2f7 in player::use_charges (this=0x38b6f900, what="UPS", qty=4) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\player.cpp:9086
[debug]#23 0x0000000000a896ed in player::process_active_items (this=0x38b6f900) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\player.cpp:8778
[debug]#24 0x00000000005ab3d4 in game::do_turn (this=0x423455c0) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\game.cpp:1454
[debug]#25 0x0000000000765df6 in main (argc=0, argv=0xfe2b4a8) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\main.cpp:451
```

Longer stacktrace: http://pastebin.com/wX1Qi3L8

**Comment by mugling** [comment] 2016-04-18 16:54
How did a `fake_UPS` make it into the inventory? They're normally used by vehicle turrets...

**Comment by DanmakuDan** [comment] 2016-04-18 17:20
It's a `UPS`, not a `fake_UPS`, some logic could have inserted the name `UPS` when trying to process for the generic `UPS` check somewhere.

**Comment by Lazasar** [comment] 2016-04-18 17:42
if it helps, it is a UPS I crafted myself, not one I found ...

**Comment by AppleConnoiseur** [comment] 2016-05-02 04:24
This bug has happened for a lot of UPS items i used when i had the UPS CBM installed.

**Closed** 2016-05-10 05:42 UTC
Labels: Bug
