### ISSUE TITLE
Game crashes when examining a cabinet of weapons

### ISSUE THREAD

**Issue by Rat69** [CleverRaven/Cataclysm-DDA#40773] opened 2020-05-23 13:34 UTC
# Describe the bug

Examining a cabinet of weapons to pick them up causes the game to crash, does the same with a crossbow i crafted

# Steps To Reproduce

Examine makeshift weapons to try to pick them up?

# Expected behavior

Game should not crash from picking up weapons

# Screenshots

https://puu.sh/FNRH4/ae97efba10.jpg

# Versions and configuration

 - OS: Windows 8
 - Game Version: 0.E-2411-g7fcce2c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: https://puu.sh/FNRLo/e312f24261.png
 -->

# Additional context

[Skidaway Island.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4671834/Skidaway.Island.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4671830/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4671831/debug.log)

**Comment by anothersimulacrum** [comment] 2020-05-23 16:53
Duplicate of #40779

**Closed** 2020-05-24 06:58 UTC
