### ISSUE TITLE
lamp oil having separated code name or something

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#48459] opened 2021-04-10 07:46 UTC
# Describe the bug

tried to refill lamp oil tank with lamp oil, got an error that said "cannot contain it"

# Steps To Reproduce

1. Make lamp oil out of demihuman tallow
2. Make lamp oil out of tainted tallow
3. the created lamp oil CANNOT be mixed in same container.

# Expected behavior

The lamp oil probably should've been able to be mixed in same container, since they have the same use anyways.

# Screenshots

![image](https://user-images.githubusercontent.com/71143790/114262659-5d907c80-9a0b-11eb-9c0a-c410ce4d3905.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10239-gdc8bba6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment] 2021-04-10 08:12
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/46786
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/47148
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/46470

**Comment by actual-nh** [comment] 2021-04-10 13:51
All these should probably be, at minimum, put in as a delayed/0.G blocker...

**Comment by Night-Pryanik** [comment] 2022-02-10 12:40
Closing as duplicate.

**Closed by Night-Pryanik** 2022-02-10 12:40 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, Items: Containers
