### ISSUE TITLE
Random Segfault while boating (currently unknown cause)

### ISSUE THREAD

**Issue by Fosheze** [CleverRaven/Cataclysm-DDA#47954] opened 2021-03-09 03:20 UTC
# Describe the bug

While boating home in an area which I had already thoroughly explored and had already been to previously during the same session I experienced a segfault and my character was duplicated in the save. 

# Steps To Reproduce

Unknown at this time. Currently trying to reproduce. I wanted to get this and the save posted before I altered the save during testing. I was approaching the shore at 0'144, 1'53 when the segfault occurred.

# Expected behavior

Not to segfault

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9956-gf6f104a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP]
]

# Additional context

The only things I am seeing in the debug are errors due to the game trying to place a couple of zombies in solid rock. Upon loading back into the save I received a bunch of the following error
`21:05:59.877 ERROR : src/item_location.cpp:114 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
21:06:00.282 ERROR : src/item_location.cpp:782 [void item_location::deserialize(JsonIn&)] parent location does not point to valid item`

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6105639/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6105640/crash.log)
[World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6105661/World.zip)

Edit: Upon further testing I can return to the location perfectly fine. The only interesting thing I have found is that both of the characters listed under load game are actually the same character listed twice. When I loaded up one and killed them then the other one disappeared. I haven't found any items missing in particular and I can't make heads or tails of crash.log. If anyone has any idea what else I should try please let me know.

**Comment by Fosheze** [comment] 2021-03-09 18:02
This may be a duplicate of #38455. I have been receiving the same errors after the segfault and it duplicated my character's name in the save just like it did in that issue. However I explored around the area, including Z-Levels with clairvoyance active and I couldn't find anything besides fish and birds in the area. No one in that other issue seemed to encounter a segfault either so I'm leaving this open on the off chance that it is a different issue.

**Comment by RenechCDDA** [comment] 2023-10-20 10:39
Should be resolved by #62960, unable to reproduce any crashing on 078a7b43be36c11f2431bf52f5f00d2d41c9a53a but the provided save looks to be kinda wrecked, even after doing a 0.F->0.G->latest series of load and saves, so I'm not 100% on that. Still, the description and crash log matches so I'm closing this.

**Closed by RenechCDDA** 2023-10-20 10:39 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation)
