### ISSUE TITLE
Canned meat/veggy recipe use

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11136] opened 2015-02-05 12:02 UTC
Canning (and pickling) meat/veggy results in 1 portion of food with roughly same nutrition as cooked meat/veggy. However, every recipe capable of using meat uses 2 portions, same as dehydrated/rehydrated meat, despite the difference in nutrition. Which results in jar-level inefficiency.

I suggest making canning recipes take 2 units of resource, uncanning produce 2 units/charges as well, and increase the volume of specific canned items to 2 (since jars are 0.5l, 2 units of volume). Optionally also halve the requirement on recipes that take canned/pickled resources, to match their nutrition. I'd do that, but my internet is currently glacially slow due to unknown issues on ISP's side, and using web interface for that is clunky.
##

**Comment by KA101** [comment] 2015-02-06 00:48
Sounds good, except for the ISP issue.  Sorry yours is On Break.

**Comment by Barhandar** [comment] 2016-08-16 08:04
This has not been fixed when containers were updated to be able to protect from food rot.

**Comment by illi-kun** [comment] 2016-11-06 19:02
Duplicate of a few similar reports.

**Closed by illi-kun** 2016-11-06 19:02 UTC
Labels: Balance, Bug
