### ISSUE TITLE
Segmentation Fault when moving into wreckage

### ISSUE THREAD

**Issue by JeanMertz** [CleverRaven/Cataclysm-DDA#27030] opened 2018-12-09 16:59 UTC
**Describe the bug**  

When I move onto a specific wreckage on the map, the game segfaults.

**To Reproduce**  
1. Load attached save game
2. Move to the right
3. Segfault occurs

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-35088-g211350d
 - Graphics version: Tiles
 - Mods:

```
[
  "dda",
  "Tolerate_This",
  "realguns",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "mutant_npcs",
  "npc_traits",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "cars_to_wrecks",
  "deoxymod",
  "blazemod",
  "Tanks",
  "DP_XOTTO_INDICATORS",
  "SEEDYSPOT",
  "BIGOLBUILDING",
  "ENTERTAINMENTBUILD",
  "filthy_morale",
  "StatsThroughSkillsR",
  "sleepdeprivation",
  "No_Fungi"
]
```

**Additional context**  

[save game](https://github.com/CleverRaven/Cataclysm-DDA/files/2660763/The.Forest.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2660764/crash.log)

**Comment by AMurkin** [comment] 2018-12-09 17:02
Duplicate of #27024

**Closed** 2018-12-09 17:12 UTC
