### ISSUE TITLE
Vehicle Protrusions Stop Projectiles (4b8c3de)

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13651] opened 2015-09-24 23:36 UTC
From experimental 4b8c3de. Search for 'projectiles' returned no relevant, recent issues, except #13392

In this particular case, firing a crossbow through a tile with a vehicle's wing mirror or spike stops the bolt every time. Such tiles, the sort that can pass over bushes, should probably allow projectiles past, since if I'm in my driver's seat, I can aim past one, and if I'm distant, it's unlikely to provide any real cover.

**Comment by ejseto** [comment] 2015-09-25 00:44
I believe it's the same as #13392. Vehicle parts absorb projectile damage and if the damage reaches 0, the projectile is stopped. But one of the functions misinterpreted the return value and got it backwards, so parts that should allow 100% of the damage through, like an empty vehicle frame or a mirror in your case, instead absorb 100% of the damage.

**Comment by Headjack** [comment] 2015-09-25 15:51
Yeah it's probably related, but I figure that in these cases it's acceptable to just let projectiles ignore them, because of the size.

**Comment by BevapDin** [comment] 2015-10-05 00:25
This is designated to be a duplicate of #13392, which has been closed by #13710. Therefor, this shall be closed as well.

**Closed by BevapDin** 2015-10-05 00:25 UTC
Labels: Duplicate
