### ISSUE TITLE
Game crashes in quest "Analyze Zombie Blood"

### ISSUE THREAD

**Issue by Arytian** [CleverRaven/Cataclysm-DDA#39475] opened 2020-04-11 14:23 UTC
# Describe the bug
Game crashes in quest "Analyze Zombie Blood" from doctor in refugee center when bringing him back USB with infection data. 

# Steps To Reproduce
Talk to doctor and give him USB with infection data.

# Versions and configuration
- OS: Windows
- Game Version: 0.E-580-gf594632 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]

# Additional context
[log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4464737/log.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4464745/save.zip)
In build 10508 it was segmentation fault, in 10516 its become St12lengthError.

**Comment by OliveChukar** [comment] 2021-01-21 19:55
Tested in ver 0.E-9072-g1bb53ba-dirty with core content pack dark days ahead only as well as with mods shown in report. Giving the usb with infection data to the quest giving NPC did not cause a crash in either case. Need someone who has seen the issue to retest and confirm that it still exists.

**Comment by anothersimulacrum** [comment] 2021-01-22 03:42
Closing as fixed, I cannot reproduce it with the provided save either.

**Closed by anothersimulacrum** 2021-01-22 03:42 UTC
Labels: (S1 - Need confirmation), Missions
