### ISSUE TITLE
Segfault due to undefined firing mode

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#38853] opened 2020-03-17 18:16 UTC
# Describe the bug

I'm not sure how it happened, but the .50 cal turret on my vehicle got set to an invalid firing mode, and this causes a segfault when attempting to fire it.

# Steps To Reproduce

Try to fire the central M2HB HMG turret on the vehicle. Alternately, take the gun off the turret and try to fire it.
 Switching its firing mode before attempting to shoot will fix the weapon.

# Expected behavior

Give an error message, or set the gun to a valid firing mode, rather than just crashing out.

# Screenshots

# Versions and configuration

Version 0.D-13155-gb5bc0a6654 on Linux, 64 bit
Mods loaded: DDA, Disable NPC Needs, Magiclysm, More Survival Tools, Mythological Replicas, DinoMod, Crazy Cataclysm, Mutant NPCs, Mythical Martial Arts, No Fungal Monsters, various blacklists, Stats Through Kills

# Additional context

https://anonfiles.com/l5McW0h8o4/FableValley-Mar17.tar_gz

**Comment by kevingranade** [comment] 2020-04-18 05:02
What the heck stalebot?

**Comment by Saicchi** [comment] 2021-04-03 03:41
Could not reproduce on `0.E-10134-g9b256f63cd [64-bit]` on a new save using the same turret and weapon.
Could not get the invalid firing mode no matter the firing mode the gun was using, using manual aim or automatic aim.

**Comment by Night-Pryanik** [comment] 2021-04-03 03:43
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-03 03:43 UTC
Labels: <Bug>, <Crash / Freeze>
