### ISSUE TITLE
Building Wall over Seeded Farm Tile causes problems

### ISSUE THREAD

**Issue by DexterBobo** [CleverRaven/Cataclysm-DDA#28203] opened 2019-02-15 00:31 UTC
I upturned earth and then sowed a seed resulting in a ^ farm tile. Later I wanted to run a metal wall through this tile so I dug a pit on it. I was allowed to dig a pit as normal, but the tile remained a ^. I then constructed the first stage of the metal wall, again the tile remained a ^. After this I am not allowed to construct stage 2 of the metal wall, instead getting the "You cannot build there!" message. Curiously I can't fertilize the seed either, although it gives me the option to do so. After attempted to fertilize, a unit of fertilizer appears in the adjacent tile and the seed remains unfertilized. So basically the tile is stuck in a weird hybrid unfinished metal wall/seed mound state and I can't figure out how to get it to be one or the other or neither. Using the look command on the tile yields "(house) simple metal wall; seed (garlic); Impassable"

Using the 0.C-8479 version on mac OSX 10.13

**Comment by dseguin** [comment] 2022-02-11 02:58
Seems to be fixed as of 03e7363df0835ec1b39da973ea29f26f27833b38:
- Unable to dig a pit on a seeded farm tile.
- Unable to construct anything (including a metal wall) on the seeded farm tile.

**Comment by Night-Pryanik** [comment] 2022-12-22 13:51
Closing until reconfirmed then.

**Closed by Night-Pryanik** 2022-12-22 13:51 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Items / Item Actions / Item Qualities, Fields / Furniture / Terrain / Traps
