### ISSUE TITLE
Crashes to desktop

### ISSUE THREAD

**Issue by denemcam** [CleverRaven/Cataclysm-DDA#26342] opened 2018-10-21 19:52 UTC
Hi!  
Game crashes often when exploring undiscovered city areas. That happened in latest right now exp. build, and happened on versions before. Reproducing it is quite difficult, because it could not happen in a while and sometimes - several times in a row. As i believe the only step to reproduce this bug - is to run around a city streets, generating new tiles.

Versions and configuration:
 - OS: Windows 7;
 - Game Version: [0.C-33469-g72b502c];
 - Graphics version: [Tiles]
 - Mods loaded: ["dda",
                          "no_npc_food",
                          "filthy_morale",
                          "novitamins",
                          "Tolerate_This",
                          "craftgp",
                          "FIC_Weapons",
                          "realguns",
                          "ew_pack",
                          "makeshift",
                          "Medieval_Stuff",
                          "More_Survival_Tools",
                          "nw_pack",
                          "DinoMod",
                          "modular_turrets",
                          "Salvaged_Robots",
                          "alt_map_key",
                          "crazy_cataclysm",
                          "mutant_npcs",
                          "npc_traits",
                          "national_guard_camp",
                          "more_locations",
                          "FujiStruct",
                          "mapgen_demo",
                          "Experimental-Z-Level",
                          "Urban_Development",
                          "boats",
                          "deoxymod",
                          "blazemod",
                          "Tanks",
                          "necromancy",
                          "RL_Classes",
                          "manualbionicinstall",
                          "safeautodoc",
                          "more_classes_scenarios"];

Savefile, but it happens every game. Btw it started to lag a bit, maybe a bit too big city?
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2499552/save.zip)
Config folder. 
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2499555/config.zip)

Thanks!

**Comment by Drakasin** [comment] 2018-10-21 19:59
Same, since updating to 8067 it keeps crashing after a minute or two in-game. CTD, no errors thrown.

**Comment by Soyweiser** [comment] 2018-10-23 12:55
Related to #26340?

**Comment by denemcam** [comment] 2018-10-23 17:38
No idea, but as i believe this is something with sewers system, their placement or may be a mob underground placement. The debug log only shows multiple issues with sewers.

**Comment by Trokinos** [comment] 2018-10-23 18:06
On recent experimental (though as i took a break since summer out of CDDA i can't pinpoint when it started as i only played with experimental again since a month) i have played, when creating a new world and just doing my usual "running into town in order to lead bunch of zombies elsewhere like in a minefield" , most of thetime CDDA crashed to desktop when i was progressing inside of the town.
Something i didn't had before.

with the "cataclysm-tiles.exe encountered a problem/stopped working" type of generic window error , but without any actual error message in the cdda debug.log unfortunately to make a report useful.

And worse, it does not seem i can make a reproduce case as trying the exact same "tactic" in the same new world from start again sometime it works without issue.

**Comment by jbytheway** [comment] 2018-10-24 07:32
Possibly related to the vehicle-related crashes here: #26291, #26297, #26315.

**Comment by ZhilkinSerg** [comment] 2018-10-28 10:16
Closed in #26414.

**Closed by ZhilkinSerg** 2018-10-28 10:16 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
