### ISSUE TITLE
Nearly indestructible (?) paper arm guards

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16101] opened 2016-04-07 08:51 UTC
![3333](https://cloud.githubusercontent.com/assets/11132525/14345545/828fd868-fcbe-11e5-96ea-f3c7b027c8cd.png)
The UI says that my arm guards were destroyed by the blow three times, yet they are still exist on my arms and I even can block damage with them.

I tested it furthermore. My nearly indestructible arm guards were able to withstand 18 times of destruction before I got message "Your paper arm guards is completely destroyed" and got them actually destroyed.

Win 10 x64, 0.C-4656, tiles.

**Comment by mugling** [comment] 2016-07-01 13:26
Closed as unconfirmed

**Comment by Night-Pryanik** [comment] 2016-07-02 05:53
I still can reproduce this on win 10 x64, 0.C-5174, tiles.
![111111111111](https://cloud.githubusercontent.com/assets/11132525/16538612/b9cab680-403a-11e6-8f2d-547b0eacf142.png)

**Comment by Coolthulhu** [comment] 2016-07-02 05:58
Looks like melee wear code currently doesn't understand non-wielded items at all.

**Comment by Oskar636** [comment] 2016-11-09 19:49
Can't reproduce in build 5862.

**Closed** 2017-03-25 18:12 UTC
Labels: Bug, Confirmation Needed
