### ISSUE TITLE
Unable to reload underballed mods

### ISSUE THREAD

**Issue by NOCH2004** [CleverRaven/Cataclysm-DDA#53367] opened 2021-12-11 14:17 UTC
### Describe the bug

There is no way to reload an underbarrel gun attachment, doesn't work with an underslung shotgun (https://nornagon.github.io/cdda-guide/?v=0.F-3#/item/u_shotgun) nor the second magazine tube of a Kel-Tec KSG (https://nornagon.github.io/cdda-guide/?v=0.F-3#/item/ksg).

Furthermore, when selecting to reload the underslung shotgun while having shotgun ammo in your inventory will show the shotgun shells in the reload menu but upon selecting them it will say the message "you can't reload *gun name*"

Moreover, if the gun has a full magazine of ammo in it will not even show the reload menu but instead says "you can't reload *gun name*"

### Steps to reproduce

1. make a player with a gun, an underslung shotgun, a magazine for the main gun, ammo for the main gun, shotgun shell compatible with the underslung shotgun
2. install the underslung shotgun on the gun
3. reload the main gun with a full magazine
4. `r`eload and select main gun
5. the game doesn't open reload menu and says "you can't reload *gun name*"
6. `U`nload main gun
7. `r`eload and select main gun
8. when reload menu is presented select *shotgun shell compatible with the underslung shotgun*
9. the game says "you can't reload *gun name*"

### Expected behavior

i expect the when i select *shotgun shell compatible with the underslung shotgun* when choosing to reload my gun the underslung shotgun will be reloaded. i also expect that when the underslung shotgun doesn't have ammo that the reload menu will come up anyway even though the main gun is full.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by wapcaplet** [comment] 2021-12-11 14:38
Sounds similar/related to #53281 and #53365

**Comment by catdach** [comment] 2021-12-11 16:28
This needs confirmation, I'm unable to reproduce this bug **at all**. Both the Kel-Tec KSG's second magazine and underslung shotgun can be reloaded fine in my testing.

**Comment by wapcaplet** [comment] 2021-12-13 12:33
@NOCH2004 This issue may have been fixed by #53102 - can you confirm whether this resolved the problem for you?

**Comment by NOCH2004** [comment] 2021-12-13 17:49
> @NOCH2004 This issue may have been fixed by #53102 - can you confirm whether this resolved the problem for you?

i am currently playing on stable, so if it has been fixed by #53102 in experimental I cant confirm

**Comment by PLUUZ** [comment] 2021-12-13 22:33
@NOCH2004 can you edit the subject so it's spelled correctly. "underballed" will stop a lot of people from being able to find it in searches.

Also impacts rail mounted weapons such as the rail mounted crossbow. See #51667

**Comment by hexagonrecursion** [comment] 2021-12-17 15:53
I could not reproduce this bug

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 9473cf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by catdach** [comment] 2021-12-17 17:03
@hexagonrecursion have you tried reproducing it on stable 0.F-2?

**Comment by wapcaplet** [comment] 2021-12-17 18:28
Whether it’s reproducible on 0.F-2 or another stable version doesn’t matter as much as whether it’s reproducible in experimental. But it would be nice to have positive confirmation from anyone who *can* reproduce this on 0.F-2, but *cannot* reproduce it in experimental.

**Comment by hexagonrecursion** [comment] 2021-12-18 04:22
I was able to reproduce this in 0.F-2

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment] 2021-12-18 04:45
> I could not reproduce this bug ((in [9473cf6](https://github.com/CleverRaven/Cataclysm-DDA/commit/9473cf65dc479e0a5dcf4906872534addf9d4c73) experimental))
> I was able to reproduce this in 0.F-2

Thanks for confirming, I believe we can call this fixed now.

**Closed by wapcaplet** 2021-12-18 04:45 UTC
Labels: <Bug>, (S1 - Need confirmation), Items: Gunmod / Toolmod, Items: Ammo / Guns
