### ISSUE TITLE
Advanced UPS is absurdly large and heavy

### ISSUE THREAD

**Issue by petervanblerkom** [CleverRaven/Cataclysm-DDA#41480] opened 2020-06-20 21:09 UTC
# Describe the bug

When spawned, the advanced UPS weighs 441.92 lbs and takes up 127.00 L of volume, but shows normal weight and volume in spawning menu.

# Steps To Reproduce

Create new world
Create character
Spawn advanced UPS

# Expected behavior

UPS should weigh and take up the volume indicated in the electronics.json file and the spawning menu (2.00 L, 1.00 lbs)

# Screenshots
![heavy_UPS](https://user-images.githubusercontent.com/46461939/85211558-a86bc700-b307-11ea-91e2-39d2327739ff.png)
![light_UPS](https://user-images.githubusercontent.com/46461939/85211561-aace2100-b307-11ea-884a-72244fed3394.png)

# Versions and configuration

OS: Windows 10
Game Version: 0.E-3388-gc2cd66c (tiles)
Mods loaded: Dark Days Ahead

# Additional context

**Comment by dsmky117** [comment] 2020-06-21 04:24
https://github.com/CleverRaven/Cataclysm-DDA/issues/40860

**Comment by anothersimulacrum** [comment] 2020-06-21 16:13
Duplicate of #40860

**Closed by anothersimulacrum** 2020-06-21 16:13 UTC
