### ISSUE TITLE
Creature Duplication

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#26708] opened 2018-11-16 01:23 UTC
**Describe the bug**  
Creatures are duplicated as I move through the map

**To Reproduce**  
It seems to be related to rendering an creature that I can see from outside my view area.  My save is very very old (world generated Dec 2016), so it could simply be backwards compatibility issues.  I last launched the game 2 days ago after updating to the latest release, and didn't notice anything until trying to play again today.  As I lost and regained view of some spiders, they became duplicated until there were 30+ spiders chilling in a field.  Hopping on my motorcycle, I noticed the same pattern of entities spawning as I drove down the road.  TBH I have no idea how to reproduce this bug, but I feel like it should be reported.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: Seen when loading a game in build 8168, as well as 8175
 - Graphics version: Tiles
 - Mods loaded
    Extended Realistic Guns,
    More Survival Tools,
    Tall Buildings,
    Boats,
    Vehicle Additions Pack,
    Tanks and Other Vehicles

**Additional context**  
The world save is very old, but I have been playing recently and regularly updating the game.  I suspect this has something to do with the new creature tracker changes.

**Comment by l29ah** [comment] 2018-11-16 01:54
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/26683

**Comment by kevingranade** [comment] 2018-11-16 03:41
Should be fixed now.

**Closed by kevingranade** 2018-11-16 03:41 UTC
