### ISSUE TITLE
Firing indicator invisible

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#45968] opened 2020-12-10 19:45 UTC
# Describe the bug

Targeting indicator does not show up when [f]iring or [t]hrowing items.

# Steps To Reproduce

Attempt to throw something, or fire a wielded ranged weapon.

# Expected behavior

I remember the last time I played CDDA (quite a while ago, and I unfortunately do not remember the build), you would see a targeting indicator and a line-of-flight indicator when attempting to fire a weapon.

# Screenshots

In this screenshot, note my character in the lower left. The firing indicator should be positioned one tile west of the wrapper on the ground. As you can see, it is invisible.

![Screenshot 2020-12-10 144133](https://user-images.githubusercontent.com/13796683/101821453-f6fb6080-3af5-11eb-8dcc-84248d7d37d4.png)

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- C.R.I.T Expansion Mod [crt_expansion]

# Additional context

This isn't a tile set problem; I tried in Undead People, Chesthole16, and Chibi_Ultica.

**Comment by anothersimulacrum** [comment] 2020-12-10 19:49
Thanks for the report!
Duplicate of #45910

> This isn't a tile set problem; I tried in Undead People, Chesthole16, and Chibi_Ultica.

It technically is, in that it's triggered by having a tileset enabled. (So no, it's not a tileset issue).

**Closed** 2020-12-10 19:50 UTC
Labels: (S3 - Duplicate)

**Comment by ToxiClay** [comment] 2020-12-10 19:51
> It technically is, in that it's triggered by having a tileset enabled. (So no, it's not a tileset issue).

Well, dammit. In the linked issue, you propose a modification to game code that restores the reticule functionality. Is that something I can do with the copy of CDDA I've downloaded? What should I do?

**Comment by anothersimulacrum** [comment] 2020-12-10 19:54
The issue that this is a duplicate of is closed because that has been merged into the base game.
So you can wait till the next build (apparently the SDL builds with the fix failed), or manually compile the game from source.

**Comment by ToxiClay** [comment] 2020-12-10 19:57
Ah, so it's been fixed but something went haywire with the build; got it.

CDDA Launcher says that build 11242 fixes the issue but failed to build on Windows. Do you have an idea of an ETA?

Also, I apologize for duping an issue.

**Comment by anothersimulacrum** [comment] 2020-12-10 20:08
> CDDA Launcher says that build 11242 fixes the issue but failed to build on Windows. Do you have an idea of an ETA?

Closest I have is whenever the next PR is merged plus a few hours (and the build might fail then too).
So within the next 24 hours?
I believe the issue this is a duplicate of mentions the build before this happens if you want to revert to that.

> Also, I apologize for duping an issue.
Don't worry, it's no big deal.

**Comment by ToxiClay** [comment] 2020-12-10 20:34
Oh, I found something that might be useful information for the next guy.

The change in 11233 also appears to block the blinking overlay when you use the Zone Manager [Y] function. Reverting to 11232 gave me my zone display back.
