### ISSUE TITLE
Stacks of items don't fluidly split to fill prioritized pockets properly

### ISSUE THREAD

**Issue by GrandpuhTy** [CleverRaven/Cataclysm-DDA#60846] opened 2022-09-08 04:54 UTC
### Describe the bug

Picking up stacks of items wont fill whitelisted or prioritized pockets if the stack can't all fit into that pocket in one go, instead going to the next best pocket.

### Steps to reproduce

1. Create new world.
2. Spawn random character
3. Wish for a survivor belt
4. Set pocket 2-7 to priority 100
5. Set all other belt pockets to priority 75
6. Set all other pockets to priority -1
7. Wish for 20 boiled makeshift bandages
8. Pickup all 20 bandages
9. All 20 bandages go into pocket 8 instead of 2-7

### Expected behavior

I would think the expected behavior would be that the stack would fill as many of the smaller priority 100 pockets as it could, splitting the stack neatly to maximize the amount going into that pocket, before filling tertiary pockets intuitively.

### Versions and configuration

- OS: Windows 8.1
- Game Version: b50c979 & 6968cf1 
- Graphics version: Tiles
- Ingame language: English

**Comment by Terrorforge** [comment] 2022-09-10 09:08
Duplicate of #58306, but I guess this counts as confirming it.

**Closed** 2022-09-16 03:54 UTC
Labels: (S1 - Need confirmation)
