### ISSUE TITLE
Uninterrupted Sleep on Death

### ISSUE THREAD

**Issue by Willenbrink** [CleverRaven/Cataclysm-DDA#37977] opened 2020-02-12 21:11 UTC
# Describe the bug

Freezing to death does not interrupt sleep.
When sleeping the game will display "Wait till you wake up...". This message is displayed even after the death of the character (i.e. by freezing to death). In the log the last few displayed messages are:
```
...
Your head hurts!
Your head hurts!
Your head hurts!
Your limb breaks!
```
At this point the game continues simulating the environment but does not allow the player to interrupt this process forcing them to kill the process with SIGINT/SIGKILL (SIGTERM is ignored).

# Steps To Reproduce

1. Create new character.
2. Take off all clothing
3. Sleep
4. Freeze to death and watch the simulation

# Expected behavior

After dying the usual prompt "Watch your last moments etc." should be displayed.

# Screenshots

![ss](https://user-images.githubusercontent.com/32180120/74377123-9f13a080-4de3-11ea-8325-9ab169e82891.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.0; Distributor ID: VoidLinux; Description: Void Linux; Release: rolling; Codename: void; 
- Game Version: 0.D-12149-g7a3893221e-dirty [64-bit] (unrelated changes)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
When catching the common cold while sleeping the player wakes up due to coughing and does not die. Possibly ~a bug~ unexpected behaviour?

**Comment by Fris0uman** [comment] 2020-03-06 09:15
Can't reproduce the bug
Set season to winter
Drop cloth
Set fatigue to 999
Eat two codein for the pain
Go to sleep
Freeze to death
![image](https://user-images.githubusercontent.com/41293484/76069542-5048c900-5f93-11ea-8b14-5538874298ed.png)

**Comment by Ramza13** [comment] 2020-03-07 21:38
Also could not reproduce.  Created winter character waited till tired removed clothes slept, died and saw prompt.

**Comment by jkraybill** [comment] 2020-03-09 04:43
OK, so I can reproduce the exact scenario described here, IF Deathcam option is set to "Always". I apparently die in my sleep (I don't get a log message for that but can see head HP go to zero), and then the game keeps spinning indefinitely. @Willenbrink can you let us know if perhaps the Deathcam option had been inadvertently set to "Always"?

**Comment by jkraybill** [comment] 2020-03-09 05:06
Further repro: this also happens when manually entering deathcam. The issue is that the player never gets the below "Press ESC..." message when you die while asleep and then go to deathcam. I'll look and fix that issue if it's within my abilities.

![image](https://user-images.githubusercontent.com/1361701/76184392-df6a1100-621f-11ea-92ca-49734e8ca3e9.png)

**Comment by Willenbrink** [comment] 2020-03-13 17:11
The Deathcam option has been set to "Always" and I can not reproduce the bug when it's set to "Ask".

**Comment by jkraybill** [comment] 2020-03-13 21:33
@Willenbrink thanks for the confirmation -- the linked PR will definitely fix this when merged!

**Closed** 2020-03-14 00:02 UTC
Labels: (S1 - Need confirmation), <Bug>
