### ISSUE TITLE
Segfault on pickup

### ISSUE THREAD

**Issue by armok** [CleverRaven/Cataclysm-DDA#69516] opened 2023-11-18 18:33 UTC
### Describe the bug

I started from the aircraft carrier scenario and cleared the CVN. When picking up a stack of crafting mats the game crashed with a segmentation fault. Picking the items up one-by-one works OK as does inserting them in a body bag.

Windows 8.1, CDDA version "cdda-windows-tiles-x64-2023-11-18-0058"

### Attach save file

[Raviolistan-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13401169/Raviolistan-trimmed.tar.gz)

### Steps to reproduce

1. 'g' for get
2. Keypad 5 for center tile
3. Select everything under spare parts (t, space)
4. Press enter to finalize
<kaboom>

### Expected behavior

Should just pick stuff up.

### Screenshots

![press_enter_to_crash](https://github.com/CleverRaven/Cataclysm-DDA/assets/29342999/bdca778f-7ab7-4db3-9fc4-aae5946f22f1)

### Versions and configuration

Using version cdda-windows-tiles-x64-2023-11-18-0058
(The same thing happened in cdda-windows-tiles-x64-2023-11-09-0717 as well)

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: b2b7cac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13401198/core.zip)

**Comment by RenechCDDA** [comment] 2023-11-18 22:18
Duplicate of #65166

**Closed by RenechCDDA** 2023-11-18 22:18 UTC
Labels: (S1 - Need confirmation)
