### ISSUE TITLE
Multidrop of too many items freezes the game

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#36666] opened 2020-01-03 11:26 UTC
follow up to https://github.com/CleverRaven/Cataclysm-DDA/issues/36554

# Describe the bug

When multidropping different items, game freezes and crashes.

# Steps To Reproduce

1. Have mulitple items ready to drop
2. Drop the bass
3. Freeze the game.

# Expected behavior

Non Freezing.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10976-ga39fc83 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    0Graphical Overmap [0Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

**Comment by ZhilkinSerg** [comment] 2020-01-03 12:46
Please follow issue template. Game version information is CRUCIAL.

**Comment by Lamandus** [comment] 2020-01-03 12:58
> 
> 
> Please follow issue template. Game version information is CRUCIAL.

aye, updated!

**Comment by HudsonMC16** [comment] 2020-01-03 13:00
I can confirm this. Playing 10110, Android 64-bit on a pixel 3xl. Happens when using the "/" menu and I press ",".

**Comment by Kelenius** [comment] 2020-01-03 13:00
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10976-ga39fc83 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

[Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4019151/Debug.zip)

It's not just the dropping of large amount of items that triggers the issue, it's dropping several stacks that have multiple items. In this safe you can reproduce the bug by dropping the entire inventory.

It looks like the game is not actually frozen, per se, because dropping 5 stacks causes a massive slowdown but eventually resolves.

**Comment by Kelenius** [comment] 2020-01-03 13:05
And in this save, dropping the entire inventory happens without an issue, because every stack only has one item.

[Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4019162/Debug.zip)

**Comment by 1n17** [comment] 2020-01-03 13:17
Can confirm, dropping eg. 50 cash cards and 5 glass bottles caps out one core and allocates all available memory.

**Comment by Unrepentant-Atheist** [comment] 2020-01-03 14:11
Yeah, that fix made the game kaput.

**Comment by Alapaga** [comment] 2020-01-03 14:16
I tried to drop items on the latest experimental build and i use windows 10, but it only dropped one at a time for me. it was not a huge stack of items, but for some reason dropping my stack of 3 rags on the floor resulted in only one being dropped at a time

**Comment by KorGgenT** [comment] 2020-01-03 15:09
I am unable to reproduce this crash on my dev environment; windows 10, VS2019, static executable

**Comment by jlon125** [comment] 2020-01-03 15:12
> I am unable to reproduce this crash on my dev environment; windows 10, VS2019, static executable

You have to try to drop multiple stacks of items.

**Comment by KorGgenT** [comment] 2020-01-03 15:14
> > I am unable to reproduce this crash on my dev environment; windows 10, VS2019, static executable
> 
> You have to try to drop multiple stacks of items.

tried kelenius's save, dropped everything in my inventory including my clothing. this was the third test, after dropping 300 plastic chunks and 100 mutant meat in addition to all of my clothing

**Comment by jlon125** [comment] 2020-01-03 15:16
> > > I am unable to reproduce this crash on my dev environment; windows 10, VS2019, static executable
> > 
> > 
> > You have to try to drop multiple stacks of items.
> 
> tried kelenius's save, dropped everything in my inventory including my clothing. this was the third test, after dropping 300 plastic chunks and 100 mutant meat in addition to all of my clothing

Well that's odd, but it's happening on all three computers I've tried.

**Comment by davidpwbrown** [comment] 2020-01-03 15:20
confirmed on my machine - Linux - lubuntu with Kelenius save.

**Comment by Ker-Nes** [comment] 2020-01-03 16:47
In the issue for the "can only drop 2 at a time", they hypothesized that it was #36205 that caused the issue. At this point, even if the new method is theoretically better from an optimization standpoint, might it not be better to just revert that one back until we identify the issue it's causing and manage to find a good fix for it?

**Comment by TechyBen** [comment] 2020-01-03 17:24
> * OS: Windows
>   
>   * OS Version: 10.0 1903
> * Game Version: 0.D-10976-ga39fc83 [64-bit]
> * Graphics Version: Tiles
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food]
>   ]
> 
> [Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4019151/Debug.zip)
> 
> It's not just the dropping of large amount of items that triggers the issue, it's dropping several stacks that have multiple items. In this save you can reproduce the bug by dropping the entire inventory.
> 
> It looks like the game is not actually frozen, per se, because dropping 5 stacks causes a massive slowdown but eventually resolves.

Ah. Good to know, I don't need to save scum/force quit then. Getting the same. More items dropped more chance, but does happen when just a few items dropped. Specifically for me dropped in a vehicle, but not dropped much on the floor to know if that is a candidate too.

**Comment by NyarlathotepZERO** [comment] 2020-01-03 20:08
I have this issue as well when dropping a stack of 32 threads onto tile #6. If I drop then one by one, they can be moved without a crash, only the 'M'ove all command will crash it.

Have tried numerous scenario's (eg: dropping on bench, ground, travois, different squares etc) all with same result.

Interesting to note that it only crashes when moving items FROM inventory.

**Comment by MaksOta** [comment] 2020-01-04 16:50
v: 0.D-10977-g4a734f0
I had this problem while playing yesterday but not today. The difference is that yesterday i had autoloot (loot all) turned on because i was foraging the forest. Today i remembered to turn it off.

**Closed** 2020-01-04 20:06 UTC
Labels: (P2 - High), (S2 - Confirmed), Code: Performance, Inventory / AIM / Zones, Items / Item Actions / Item Qualities
