### ISSUE TITLE
"Move all" from AIM_ALL moves from dragged destination vehicle

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13132] opened 2015-07-30 08:36 UTC
Move all from AIM_ALL doesn't seem to understand dragged vehicle as destination and tries to take item from it to put it back where it got it from.

It doesn't result in an infinite loop because items are only restacked once, but it goes through each item.
##

**Comment by DavidKeaton** [comment] 2015-07-30 19:59
I see, I can put in a fix. Thanks mate.

**Comment by Oskar636** [comment] 2016-11-11 00:06
Cannot reproduce in build 5864 windows 64 bit console. Unless I misunderstood and this is about how the code handles it's stuff.

**Comment by Leland** [comment] 2018-02-20 22:52
Closing due to lack of repro above

**Closed** 2018-02-21 03:49 UTC
Labels: Bug, Confirmation Needed, Information / Interface, Items
