### ISSUE TITLE
NPCs (Hostile or otherwise) only shoots at point blank range

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21362] opened 2017-07-05 13:23 UTC
Version: 0.C-22779-g3510ea2 (tiles) Build:6560 
### Expected Behavior
NPCs use their guns and/or bows at range relative to their skill and the weapons ideal range
### Actual behavior
NPCs only use their ranged weapons when close enough to shake hands
### Steps to reproduce the behavior
Get some companions (optional) give them guns go to a bandit camp, watch as no one shoots anybody until they are in hugging distance

**Comment by Leland** [comment] 2017-07-05 14:58
Closing, duplicate of #19798. @DemAvalon if you can confirm in that thread that this issue only rears its head when NPCs attack other NPCs that would be very helpful.

**Closed by Leland** 2017-07-05 14:58 UTC

**Comment by DemAvalon** [comment] 2017-07-05 21:58
@Leland I would like to clarify that in https://github.com/CleverRaven/Cataclysm-DDA/issues/19798 the hostile NPC seems to shoot at the player from range, in my issue NPCs shot at **NO ONE** not other NPCs, not monsters, not the player unless they are at point blank range.

**Comment by Leland** [comment] 2017-07-05 22:27
@DemAvalon great info. I'd bet the two have the same underlying cause. I'll combine the two – you're cited over on the other issue.
