### ISSUE TITLE
Some of my characters default to "Force Unarmed" for a martial arts style

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#68792] opened 2023-10-21 18:54 UTC
### Describe the bug

Some of my characters are starting off with the martial arts style "Force Unarmed" selected. This is not ideal.

### Attach save file

[Apollo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13061540/Apollo-trimmed.tar.gz)

### Steps to reproduce

This is my best guess and it doesn't always work.
1. Create a character with melee 1 (?)
2. They start with "Force Unarmed" selected as a style? Sometimes.

### Expected behavior

I never want this style to be used if I can help it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d97b31e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Lonely Evac Scenario [Lonely_Evac]
]

### Additional context

I'm not sure why this is happening. I _think_ this is due to having a melee of 1 starting out - the game may be trying to swap to Brawling. But I can't say for sure.

**Comment by gettingusedto** [comment] 2023-10-21 18:55
#68789 might fix the issue

**Comment by RenechCDDA** [comment] 2023-10-21 18:57
Duplicate of #68722

**Closed by RenechCDDA** 2023-10-21 18:57 UTC
Labels: (S1 - Need confirmation)
