### ISSUE TITLE
Destroyed roof doesn't drop the player

### ISSUE THREAD

**Issue by Sofistico** [CleverRaven/Cataclysm-DDA#47951] opened 2021-03-09 01:16 UTC
# Describe the bug

If the player is standing on a roof tile and a monster or something else destroys that tile, the player stays levitating in the air.

# Steps To Reproduce

1. Add experimental z level settings;
2. Go one z up from a building;
3. Spawn an hulk in the ground level and have him smash that building;
4. Play a game in the game watch.

# Expected behavior

The player falls down and takes damage.

# Screenshots

![image](https://user-images.githubusercontent.com/59299346/110403114-51577f00-805b-11eb-994e-c567f750d071.png)
![image](https://user-images.githubusercontent.com/59299346/110403251-8c59b280-805b-11eb-8c9e-13603101462d.png)

# Versions and configuration

Latest experimental.

 - OS: Windows 10

**Comment by wapcaplet** [comment] 2021-03-09 03:18
May be peripherally related to #19226 and #47305 (not sinking into water) and #47598 (levitating in air after teleporting) - seems like a general problem of gravity-detection or "Wile E. Coyote" syndrome.

**Comment by PaulBlay** [comment] 2021-03-09 08:26
I think there are two separate things that could be done. 
1. Things that change tiles from 'you can stand here' to 'you can't stand here' should prompt a refresh of whatever is standing on them. 
2. When a player / NPC / monster checks to see if it can/should move it should possibly also check to see if it can continue to be where it is.

The problem with 1. is that it's easy to miss a case and you have to check everywhere it could possibly apply.
The problem with 2. is that it adds to the game processing load - possibly quite significantly - because you'd be checking all the time.

Here's another somewhat related case, btw. https://github.com/CleverRaven/Cataclysm-DDA/issues/46876

**Comment by actual-nh** [comment] 2021-03-09 18:16
All of these seem to be with either the player or with NPCs (bandits). Any with monsters?

**Comment by actual-nh** [comment] 2021-05-24 17:30
#49017 is a duplicate of this one, BTW, albeit with some added amusing description parts... BTW, @Sofistico, could you remove "watch" (or "when playing in the game watch") from the description? It makes me think you're talking about a game-playing watch in the game...

**Comment by Zireael07** [comment] 2021-05-24 17:32
@actual-nh: Most likely they are - IIRC Cata had an item you could play some simple games on? I am not 100% certain if the item was named a 'watch', though.

**Comment by SariusSkelrets** [comment] 2021-05-24 19:29
There’s the handheld console and the game watch

**Comment by Sofistico** [comment] 2021-05-25 01:22
My issue happened in fact when i was using the game watch item: https://cdda-trunk.chezzo.com/game_watch

I will change the title to be more general.

**Comment by actual-nh** [comment] 2021-05-27 22:01
> My issue happened in fact when i was using the game watch item: https://cdda-trunk.chezzo.com/game_watch
> 
> I will change the title to be more general.

Thank you; I was more meaning that it sounded like you were playing a game on the game watch and in _that_ game your character didn't fall...

**Comment by actual-nh** [comment] 2021-05-27 22:04
Does the character in these get asked if they want to climb down? This happened with #49044.

**Comment by SariusSkelrets** [comment] 2021-05-28 18:01
You’re only asked if you try to walk in another empty tile

It happened to me as I was luring zombies from one side of the tower to escape it

They destroyed the tile I was standing on but I just walked to the next tile to avoid the fall

**Comment by Sofistico** [comment] 2021-05-28 20:02
Sadly 

> Does the character in these get asked if they want to climb down? This happened with #49044.

Yeah it happened when i tried moving, it opened the prompt asking about moving down

**Closed** 2022-02-12 06:44 UTC
Labels: <Bug>, (S2 - Confirmed), Z-levels, <Exploit>
