### ISSUE TITLE
Crash: Segmentation Fault when Driving a Vehicle (^) and Pressing E

### ISSUE THREAD

**Issue by starstilanx** [CleverRaven/Cataclysm-DDA#32892] opened 2019-08-04 02:01 UTC
# Describe the bug
Pressing E whilst driving a vehicle results in a segmentation fault.

# Steps To Reproduce
1. Start the vehicle
2. Press E

# Expected behavior
Either examination of the vehicle or nothing at all. (Might need a reference to a prior build to reproduce the stable result interaction of pressing E whilst driving)

# Screenshots
<img width="1920" alt="Screenshot 2019-08-03 18 33 05" src="https://user-images.githubusercontent.com/13081626/62418491-83eafb80-b61e-11e9-800b-a2f16186833f.png">
<img width="1919" alt="Screenshot 2019-08-03 18 33 20" src="https://user-images.githubusercontent.com/13081626/62418607-e396d600-b621-11e9-92b7-23927d2544b9.png">
<img width="1920" alt="Screenshot 2019-08-03 18 34 35" src="https://user-images.githubusercontent.com/13081626/62418496-8cdbcd00-b61e-11e9-936f-daa49010f6b8.png">

# Crash Log

CRASH LOG FILE: config/crash.log
VERSION: 0.D-6097-gdbd440d
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x59B845[cataclysm-tiles.exe+0x19B845]
    @0x59C312[cataclysm-tiles.exe+0x19C312]
    SMPEG_error+0x4B034@0xF333A0[cataclysm-tiles.exe+0xB333A0]
    _C_specific_handler+0x96@0x7FFD68EB1146[ntdll.dll+0x91146]
    _chkstk+0x11D@0x7FFD68EC4E6D[ntdll.dll+0xA4E6D]
    RtlWalkFrameChain+0x1518@0x7FFD68E46058[ntdll.dll+0x26058]
    KiUserExceptionDispatcher+0x2E@0x7FFD68EC3D9E[ntdll.dll+0xA3D9E]
    @0x6BE8E8[cataclysm-tiles.exe+0x2BE8E8]
    @0x6BF2D9[cataclysm-tiles.exe+0x2BF2D9]
    @0x6E49E0[cataclysm-tiles.exe+0x2E49E0]
    @0x6BD3F7[cataclysm-tiles.exe+0x2BD3F7]
    IMG_LoadWEBP_RW+0x57A9F8@0x159FC08[cataclysm-tiles.exe+0x119FC08]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFD67CD1FE4[KERNEL32.DLL+0x11FE4]
    RtlUserThreadStart+0x21@0x7FFD68E8CB31[ntdll.dll+0x6CB31]

# Versions and configuration

 - OS: Windows 10 x64 Version 1709 (OS Build 16299.492)
 - Game Version: 0.D-6097-gdbd440d [64-bit]
 - Graphics version: Tiles
 - Mods loaded:    
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Mundane Zombies [Mundane_Zombies],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Bionic Slots [cbm_slots],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]

# Additional context

Occurs on modded vehicles, vanilla, and in-game customized vehicles.

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3464492/config.zip)
[Lake Elmo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3464494/Lake.Elmo.zip)

**Comment by perryprog** [comment] 2019-08-04 02:27
Duplicate of #32484.

**Comment by esotericist** [comment] 2019-08-04 03:21
> Duplicate of #32484.

Pardon, but how is a crash report while driving a duplicate of a report about an inability to reload a weapon?

**Comment by anothersimulacrum** [comment] 2019-08-04 04:04
They probably mean #32848

**Comment by esotericist** [comment] 2019-08-04 04:18
Ahh.

Well, it looks like this report is from two builds prior to the fix. So unless they can reproduce it on a new build, I'm going to assume this is fixed since it does appear to be the same issue.

**Closed by esotericist** 2019-08-04 04:18 UTC
Labels: (S3 - Duplicate), <Bug>, <Crash / Freeze>, Vehicles

**Comment by perryprog** [comment] 2019-08-04 12:07
I did mean that, thank you.
