### ISSUE TITLE
Dark Skies Above:Husks Are Humans(Massive Morale Loss)

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#40593] opened 2020-05-15 17:41 UTC
# Describe the bug

When butchering Husks, a -50 Morale penalty is caused, as though you were butchering a ordinary human corpse. Additionally, after killing a bunch, a Guilty About Killing morale penalty occurs to non-pacifistic characters, causing in my case a total of -82 morale after clearing a house of Husks.

# Steps To Reproduce
Load up Dark Skies Above, attack, and butcher husks.
# Expected behavior

Zombies and husks should be identical in this particular regard.

**Comment by anothersimulacrum** [comment] 2020-05-15 17:44
@ephemeralstoryteller

**Comment by ephemeralstoryteller** [comment] 2020-05-17 17:58
This will be fixed in a pretty big update coming either today or tomorrow that includes better drop tables and more Stray variety. Initial intended behavior was indeed that Strays are human enough (they are living and breathing, if not at all in their right mind) to make you feel icky about killing them, but I've had enough complaints about this behavior that I get the impression that people don't find it very compelling. 

I will close this as soon as that update is live. ^^

**Comment by Grubleafeater** [comment] 2020-05-17 23:39
It's one thing to feel mildly guilty, it's another to go into SUICIDAL FUNK over killing a few dozen of them... at that low of a morale you'll just not attack occasionally...

**Comment by ephemeralstoryteller** [comment] 2020-05-18 01:55
Unfortunately, morale loss is still hardcoded. If we ever get finer jsonized control over it then it might see a reappearance. I do agree though.

**Closed** 2020-05-27 00:00 UTC
Labels: Mods, Mods: Dark Skies
