### ISSUE TITLE
Game crashes when approaching quest location

### ISSUE THREAD

**Issue by rockygr** [CleverRaven/Cataclysm-DDA#45051] opened 2020-10-25 01:56 UTC
Game version: O,E-7041-gdb7d137

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: dda - no_npc_food - aftershock - magiclysm - No_Fungi - stats_through_kills

### Expected behavior
Being able to approach the LMOE shelter and accessing the NPCs related to the quest there.

### Actual behavior
When approaching the shelter surface, the game freezes. This happens regardless if you teleport there by debug, walk, or teleport to the underground shelter.

### Steps to reproduce the behavior
Load the save;
Approach the marked quest location;
Getting near the shelter should make your game freeze.
Otherwise, try teleporting to it directly, and it should freeze anyway.

Additional info:
The quest is from Aftershock: it's called "Find my great uncle Cyrus Whately for Millyficent Whately, Xenobiologist, madwoman".
 I've included my save file and crash.log/debug.log.
(Since I can't upload files bigger than 10mb, and couldn't compress it enough, I've uploaded it here: https://files.catbox.moe/hccwuk.zip)
Edited to change file link

**Comment by John-Candlebury** [comment] 2020-12-09 03:24
I cant reproduce this crash in current experimental versions, either with your save or with new characters. 

It might have been unrelated to the actual piece of aftershock content and been fixed independently.

**Comment by Mom-Bun** [comment] 2020-12-09 04:54
I cannot replicate this, but by loading the save, my game does lock up for a few minutes when I approach, and start to slow down significantly once I approach
I suspect this is related to the problem.

**Closed** 2020-12-24 02:58 UTC
Labels: <Bug>, Mods: Aftershock, NPC / Factions
