### ISSUE TITLE
Guns with Interchangeable Barrel-Assemblies don't correctly spawn, s_gun_1 ammo vending machines selling snacks/drinks, stop adding/removing guns based heavily off Gunbroker results.

### ISSUE THREAD

**Issue by KrunkySmokin** [CleverRaven/Cataclysm-DDA#74735] opened 2024-06-23 14:30 UTC
### Describe the bug
The bugs:
-Bug 1            
Guns that spawn in Gun Stores that _in the description of said gun_ say that come with interchangeable barrel-assemblies do not spawn correctly.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49448025/2c305f9a-4fb9-4763-95d1-2315b3f78fa5)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49448025/83511e81-e42f-45fd-9e85-ca55ae3b8003)
They are entirely broken, and other guns with similar 'swappable' assemblies are broken in a similar way. The CZ Trail Carbine, the Accuracy International AXMC, and MDRX rifles are all broken and have been for weeks.
-Bug 2
s_gun_1 gun store vending machines spawn food and drinks instead of ammunition.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49448025/a8b5c50f-a9b9-4b19-82a8-1b190af7a6cf)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49448025/bbb104f2-87c9-44ce-92e5-155e7a303608)

--assorted related to third part of title--
> _Originally posted by @Maleclypse in [#74636 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/74636#issuecomment-2183588582)_ Instead of getting angry at me and telling me to redirect conversation when no one directed it at me or told me before and threaten to remove my ability to comment on a repository, fix the gun bugs your supported Pull Requests create that fester and sit around for months instead of removing guns where a perfectly viable spawn for them exists.

Not angry, just letting you know that you need to read the comments directed at you.
https://github.com/CleverRaven/Cataclysm-DDA/pull/74636#issuecomment-2182955186

_Originally posted by @Maleclypse in https://github.com/CleverRaven/Cataclysm-DDA/issues/74720#issuecomment-2184044288_

It wasn't directed at me as it was said to someone else but alright, because you said someone else replying to someone else saying _maybe_ PRs aren't the best place to bring up grievances was directed at me, it was directed at me and I should take their passive aggressive _maybe_ replying to someone that wasn't me as a warning to myself.
            
 https://github.com/CleverRaven/Cataclysm-DDA/issues/74720#issuecomment-2184085127
            
 Gun Broker isn't the only determinate factor as to whether or not a gun is popular in New England and should be used in conjunction with multiple other factors such as if the firearm is still currently in production or being imported for sale by a big name company, like Beretta does the MR73. Just because Gun Broker says 15-30 results for _you_ doesn't mean that the gun wouldn't show up in a private gun safe collection or among collectors at a gun show.
 The gun show as a spawnable exists and it has over time spawned the more _rare_ guns, and sure one _unique/rare_ gun for a quest might've made it's way there but that's the problem if you're going to claim _other_ rare guns wouldn't be able to be found there. Collectors go around to gun shows, they don't have to be specifically local. There's already a Generic Guns mod and if you want to genericize all the firearms, just take up stewardship of that instead of removing collector firearms from the game.
            -----

### Attach save file

n/a

### Steps to reproduce

Bug 1
1. Enter gun store and find MDRX, CZ Trail Carbine, or find an AXMC Rifle
2. Guns do not spawn correctly and cannot retain attachments or magazines

Bug 2
1. Enter s_gun_1
2. Use vending machines in back room
3. Food and drinks for sale instead of ammunition.

### Expected behavior

CZ Trail Rifle, Accuracy International AXMC, and MDRX rifles do not spawn correctly, cannot accept attachments, or magazines.
s_gun_1 vending machines don't sell ammunition, only snacks/drinks.

### Versions and configuration

OS: Windows 10
Game Version: cdda-experimental-2024-06-23-1253
graphics version: tiles
Language: English
Mods loaded: Dark Days Ahead

**Comment by XygenSS** [comment] 2024-06-23 14:32
Please make a seperate issue per each bug so that they can be individually addressed, discussed and closed/resolved when fixed

**Comment by XygenSS** [comment] 2024-06-23 14:35
The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.

**Comment by KrunkySmokin** [comment] 2024-06-23 14:36
> The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.

Remove the vending machines from that s_gun_1 then because they make no sense being where they are locked away from the public that would be using them.

**Comment by XygenSS** [comment] 2024-06-23 14:38
> > The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.
> 
> Remove the vending machines from that s_gun_1 then because they make no sense being where they are locked away from the public that would be using them.

Please comment this on the linked issue as this issue is effectively a duplicate concerning this "bug."

**Comment by KrunkySmokin** [comment] 2024-06-23 14:39
> > > The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.
> > 
> > 
> > Remove the vending machines from that s_gun_1 then because they make no sense being where they are locked away from the public that would be using them.
> 
> Please comment this on the linked issue as this issue is effectively a duplicate concerning this "bug."

yeah I was told above that already completed pull requests are _not_ the place to be talking about the issues so this is a bug.

**Comment by XygenSS** [comment] 2024-06-23 14:44
> > > > The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.
> > > 
> > > 
> > > Remove the vending machines from that s_gun_1 then because they make no sense being where they are locked away from the public that would be using them.
> > 
> > 
> > Please comment this on the linked issue as this issue is effectively a duplicate concerning this "bug."
> 
> yeah I was told above that already completed pull requests are _not_ the place to be talking about the issues so this is a new bug/outstanding issue.

Not the PR, the issue. #74420. Which is open

**Comment by KrunkySmokin** [comment] 2024-06-23 14:48
> > > > > The second "bug" is intended behavior as per PR #72597. The fact that it removed ammo from vending machine gun stores is discussed at Issue #74420.
> > > > 
> > > > 
> > > > Remove the vending machines from that s_gun_1 then because they make no sense being where they are locked away from the public that would be using them.
> > > 
> > > 
> > > Please comment this on the linked issue as this issue is effectively a duplicate concerning this "bug."
> > 
> > 
> > yeah I was told above that already completed pull requests are _not_ the place to be talking about the issues so this is a new bug/outstanding issue.
> 
> Not the PR, the issue. #74420. Which is open

Instead of commenting on that issue you've known about longer than me and bringing it to the attention of the devs so they can close an issue they already addressed, you instead try to get me to comment on it for you?
Comment yourself, if it's a duplicate of an already existing issue 2 weeks later no one has addressed and it's still open.

**Comment by XygenSS** [comment] 2024-06-23 14:55
Because I have no particular investment in the issue and I'm not gonna pretend to know what you wish to be addressed by commenting in behalf of you?
Issues being open for a long time isn't indicative of anything in particular, everyone working on the game are volunteers who work on whatever they want to work on.

**Comment by kevingranade** [comment] 2024-06-23 19:25
Again, one topic per issue, issues with multiple topics will be closed because there is no good way to manage them. 

Regarding the gun broker criticisms specifically. We have evaluated a number of options and a threshold of completed sales on gunbroker is the **least bad** option that has come up.  If you do not have a better **objective** threshold,  please do not bring it up again,  if you aren't providing a viable alternative you're just heckling.

**Closed by kevingranade** 2024-06-23 19:25 UTC
Labels: (S1 - Need confirmation)
