### ISSUE TITLE
mod breaking copy-from?

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#68362] opened 2023-09-27 12:50 UTC
### Describe the bug

Something in the mod gives an error, which is acceptable, but that causes copy-from to break on subsequent attempts to load the world

### Attach save file

N/A

### Steps to reproduce

Create a world with the mod active.
Try creating a character, get a normal error
Do that again without altering the mod, get a different error

### Expected behavior

The game displaying what is broken each time the save is loaded, not displaying an unrelated copy-from error.

### Screenshots

error log after trying to load into the world after launching the game
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77662682/2dcc136a-5883-40d0-b616-ab81f808630f)
error log trying to load into the same world afterwards, with nothing changed in the files
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77662682/1f569811-bd78-4b16-a39f-d7250ec2ba97)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.985 (20H2)
- Game Version: 7ea6e22 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Officium Mundi [TDG_mod]
]

### Additional context

I made the game report by removing everything except modinfo from the mod folder.
Mod causing the issue.
[cdda-TDG-mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12738718/cdda-TDG-mod.zip)
Mod was developed for 0.G, was trying to update it to latest experimental.
EDIT: seems to also happen with defense mode mod

**Comment by ZhilkinSerg** [comment] 2023-09-28 06:51
Duplicate of #68205

**Closed by ZhilkinSerg** 2023-09-28 06:51 UTC
Labels: (S1 - Need confirmation)
