### ISSUE TITLE
Trying to pick up item too small for the pockets fails silently.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#54725] opened 2022-01-24 03:18 UTC
### Describe the bug

There are some wool socks next to me that i can't pick up despite having a half-empty duffel bag on me, and more than enough spare carry capacity.

### Steps to reproduce

- Load the save
[Port Mayaca-no-socks.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7922363/Port.Mayaca-no-socks.zip)
- `g` -> `<Right arrow>` -> `<Enter>` to pick up the socks
- Observe that no messages are produced, and the socks have their location unchanged.

### Expected behavior

Socks get picked up.

### Screenshots

The socks can quite clearly fit into my bags:
![20220124-031704-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150716507-416657c2-4a07-4cbe-a811-f6cd2bf6405f.png)
![20220124-031724-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/150716534-7cc097ca-912d-4313-9f5b-e42d04ff29a3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5ac1a12 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by moxian** [comment] 2022-01-24 03:26
Ah, wait, i see now, the "spare" capacity is only in the pockets that have min volume restrictions (e.g.
![20220124-032535](https://user-images.githubusercontent.com/7831163/150717165-a53b621c-e428-4fb3-9cc6-0ab79b1d25bc.png))

, and socks are too small to fit there. So the behavior is expected, and the only problem is the lack of error messages describing the issue.

**Comment by moxian** [comment] 2022-01-24 04:02
Oh, and this is a duplicate of #54703 ..

**Comment by LeahLuong** [comment] 2022-01-24 15:47
Not sure this is a dupe because they _**are**_ getting an error message in the other thread & its unknown what sort of carrying capacity they have.

Not sure you should close this issue because the player prob _**should**_ get a message when failing to pick up.

**Comment by matshou** [comment] 2022-01-25 11:33
After investigating the situation it seems there is an additional bug revealed here.

Unless this is intended behavior the pair of socks you are trying to pick up should automatically go into the *plastic jerrycan*. 
That item has no pocket restrictions and in fact does allow the socks to go inside it's main pocket both by manually placing them inside as well as automatically when being wielded. For some reason this doesn't happen when the item is in the backpack.

**Comment by matshou** [comment] 2022-01-25 12:01
The bug mentioned above has been reported in #53807

**Closed** 2022-02-05 00:00 UTC
Labels: (S2 - Confirmed), Items: Containers, 0.G suggested release blocker
