### ISSUE TITLE
Autofire killing targets with no remaining target switches to friendlies for remaining shots

### ISSUE THREAD

**Issue by sbombay** [CleverRaven/Cataclysm-DDA#21243] opened 2017-06-14 17:09 UTC
0.C-6399 64 bit

I am firing a rifle in auto at an enemy or multiple enemies.  Upon killing the last enemy I automatically switch my fire to any friendly (NPC or my turrets) even if they are far behind me in the exact opposite direction I was firing.

GIF of example
http://recordit.co/iTPJNFPReH#
The last 15 seconds shows the problem.  The rest is just demonstrating normal behavior.

**Comment by Noctifer-de-Mortem** [comment] 2017-06-16 05:20
I had this issue a while back but I though it had been fixed.

**Comment by Leland** [comment] 2017-08-19 03:15
Duplicate of #21158. Adding your description there, however - thanks for recording the GIF, it helps developers out a lot.

**Closed by Leland** 2017-08-19 03:15 UTC
Labels: Aiming, Bug, Confirmation Needed
