### ISSUE TITLE
Transfering gasoline from some sources to vehicle tanks isn't working

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#46483] opened 2021-01-02 10:01 UTC
# Describe the bug

When attempting to siphon gas, or refilling a container from a vehicle from a gas pump, you get the following error:

 DEBUG    : tried to put an item (gasoline, amount 1) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int)
 FILE     : src/item.cpp
 LINE     : 8874

# Steps To Reproduce

Try syphoning the gas in the ambulance to adjacent vehicle (attached save)

# Aditional context

I noticed in another car that if I left the engine running until it ran out, the offending tanks were left with 0,0 gas instead of becoming an empty tank. It may be related.
[syphoning.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5760078/syphoning.zip)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8638-g8e4e267 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm]
]

**Comment by PaulBlay** [comment] 2021-01-02 10:35
In the latest build some liquids are being generated with 
"item_tags":["DIRTY"],

(See https://github.com/CleverRaven/Cataclysm-DDA/issues/46480 )

I removed the DIRTY tag from the save  (file 83.-18.0.map ) and reloaded - it now can be siphoned in either direction no problem.

**Comment by BrettDong** [comment] 2021-01-02 15:51
Seems like a duplicate of #45191.

**Comment by Svankensen** [comment] 2021-01-02 16:57
> Seems like a duplicate of #45191.

Interesting. This save is new tho, must have a couple days, and I'm never more than a week behind in the experimental.

**Comment by BrettDong** [comment] 2021-01-02 16:57
This bug has been existing for a while

**Comment by BrettDong** [comment] 2021-01-02 17:29
This is probably because an old bug that gasoline from gas stations erroneously carry `DIRTY` flag, and checks introduced in #44539 refuses to mix liquids carrying different flags. The `DIRTY` gasoline bug has been fixed in #44689, but unfortunately old saves created before that all carry the defect. I created a new world, spawned two vehicles and tried to siphon gasoline between them and it works fine.

**Comment by Svankensen** [comment] 2021-01-02 17:40
> This is probably because an old bug that gasoline from gas stations erroneously carry `DIRTY` flag, and checks introduced in #44539 refuses to mix liquids carrying different flags. The `DIRTY` gasoline bug has been fixed in #44689, but unfortunately old saves created before that all carry the defect. I created a new world, spawned two vehicles and tried to siphon gasoline between them and it works fine.

Yeah, but I created this world yesterday, and wasn't more than a week behind in the experimental.

**Comment by BrettDong** [comment] 2021-01-02 17:42
Where did these two vehicles (and their gasoline) come from? I found that gasoline from one vehicle carries `DIRTY` flag and gasoline from the other does not, and that is the reason why they refuse to mix together.

**Comment by Svankensen** [comment] 2021-01-02 17:43
> Where did these two vehicles (and their gasoline) come from? I found that gasoline from one vehicle carries `DIRTY` flag and gasoline from the other does not, and that is the reason why they refuse to mix together.

Damn, you asked before my edit got through. I believe most of the gas came from a pump in the lumbermill (not the lumberyard in the city).

**Comment by Svankensen** [comment] 2021-01-02 17:46
The rest came from a flatbed I found in the northern research facility and that is now in the road outside the prison.

**Comment by Svankensen** [comment] 2021-01-02 17:52
There should be a steel jerrycan full of gas that I got from the pump there somewhere in the RV (already moving cars, can't point you exactly where), that one shouldn't have any confounding factors.

**Comment by BrettDong** [comment] 2021-01-02 21:10
Gasoline from lumber mills is dirty. I made a bug fix but it is only effective for new lumber mills spawned in new experimental versions after the fix is merged. For old saves you will have to manually edit the save file to drop `DIRTY` flag.

**Comment by Svankensen** [comment] 2021-01-02 21:24
> Gasoline from lumber mills is dirty. I made a bug fix but it is only effective for new lumber mills spawned in new experimental versions after the fix is merged. For old saves you will have to manually edit the save file to drop `DIRTY` flag.

Thanks a bunch! People like you are who makes CDDA so dynamic. 11 hours for a fix. Thanks for your time!

**Closed** 2021-01-03 01:28 UTC
Labels: (S2 - Confirmed), <Bug>, Items: Containers, Vehicles
