### ISSUE TITLE
Failed when I use cattle fodder to tame a cattle, Shows attempting to eat cattle fodder bundle"

### ISSUE THREAD

**Issue by keys-string** [CleverRaven/Cataclysm-DDA#76653] opened 2024-09-25 02:20 UTC
### Describe the bug

I am not tying to eat the fodder, i active "use item" and hope to tame a cattle, but it shows attempting to eat cattle fodder bundle.

### Attach save file

[梅里登-trimmed.tar.gz](https://github.com/user-attachments/files/17123414/-trimmed.tar.gz)

### Steps to reproduce

1.close to a cattle. 2. use item "cattle fodder" 3. Shows "attempting to eat cattle fodder bundle" 

### Expected behavior

I expected that I can use fodder to tamp a cattle 

### Screenshots

![image](https://github.com/user-attachments/assets/6c2f17d4-8c43-43f8-aef9-05a1666c02da)

### Versions and configuration

27992ec

### Additional context

I love the game.

**Comment by RenechCDDA** [comment] 2024-09-25 02:25
Duplicate of #76414

**Closed by RenechCDDA** 2024-09-25 02:25 UTC
Labels: (S1 - Need confirmation)
