### ISSUE TITLE
Clean water is lost if you cook all the water from a container

### ISSUE THREAD

**Issue by LisacPisac** [CleverRaven/Cataclysm-DDA#18190] opened 2016-09-02 16:12 UTC
When there is, for example, 9 water left in a toilet and I cook all of it, I get no prompt on what to do with that water and it simply disappears.

**Comment by Night-Pryanik** [comment] 2017-05-06 07:30
Confirming on 0.C-6421, Windows XP SP3 x86, curses.

**Comment by lancewf** [comment] 2018-09-12 14:09
I could not reproduce the bug on 0.C-31950-gd1b91f3-dirty.

**Comment by Night-Pryanik** [comment] 2018-09-13 08:50
Closing then. If someone manage to reproduce, ping me.

**Closed by Night-Pryanik** 2018-09-13 08:50 UTC
Labels: (S2 - Confirmed), <Bug>, Crafting / Construction / Recipes
