### ISSUE TITLE
The Internal Furnace can burn cotton, iron, plastic... but not leather?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20026] opened 2017-01-13 18:46 UTC
To clarify, items made solely of iron, or solely of plastic can be consumed. But not those solely of leather.

**Comment by codemime** [comment] 2017-01-13 19:07
To clarify, leather items can be consumed, but provide significantly less energy (1/4 of "normal" amount).
You can't burn radioactive stuff, you can't burn corpses. Everything else is burnable.

**Comment by Regularitee** [comment] 2017-01-14 00:09
Items made solely of leather cannot be consumed -- or at least I can't consume them. It could be a mod is interfering with it, but in my own game I am unable to consume all-leather items, such as "leather pants" or a "purse". Many partially-leather items are okay, I suspect because they also contain at least one furnace-compatible material.

Can someone else confirm or deny whether the items specifically mentioned ("leather pants" and "purse") are consumable or not with the furnace bionic?

**Comment by keyspace** [comment] 2017-01-14 00:25
Tried it on no-mod save - can't consume leather pants, cheat-wished or crafted.

Burning leather patches is OK, both via [e]at menu and via [i]nventory.

**Comment by Coolthulhu** [comment] 2017-01-14 00:33
Furnace allows consuming only items that burn well - they need to be able to fuel size 1 fire. Leather requires size 2.

**Comment by kevingranade** [comment] 2017-01-14 02:35
I suspect what's happening here is leather items are a lot more likely to
be composed of only leather, iron and plastic are red herrings in that they
aren't actually contributing to burn ability.
Do you have any sources indicating that leather goods are particularly
flammable? I was under the impression that leathet burns poorly.

**Comment by CoroNaut** [comment] 2017-01-14 03:49
Leather burns hot usually, but it can be slowly burned.

**Comment by WizardOfOoo** [comment] 2017-01-14 09:56
This is a video of someone taking a blowtorch to various clothing materials.
https://www.youtube.com/watch?v=Vio4kleGxhM


This link skips to leather.
http://youtu.be/Vio4kleGxhM?t=3m8s

**Comment by codemime** [comment] 2017-01-14 10:01
Doesn't catch fire, barely chars.

**Comment by kevingranade** [comment] 2017-01-14 18:01
Unless someone can provide some evidence for leather burning well, I'm closing this as working as intended.

**Closed by kevingranade** 2017-01-14 18:01 UTC
Labels: Question, Suggestion (Discuss)

**Comment by Regularitee** [comment] 2017-01-15 01:20
The issue wasn't whether leather should burn well or not, it was the fact that leather items of sufficiently small size cannot be burned at all because they don't reach the "minimum" fuel value. That struck me as a bug.

**Comment by keyspace** [comment] 2017-01-15 03:01
To clarify: iron/steel can't be burned (check with pliers, say).

Currently, leather items have to be cut up into patches. Those can be burned individually.
