### ISSUE TITLE
Upon loading into a save, upgrading from stable to recent experimental 

### ISSUE THREAD

**Issue by portajohn** [CleverRaven/Cataclysm-DDA#66066] opened 2023-06-08 05:29 UTC
### Describe the bug

Several items 'Alcohol wipes', 'medical gauze', and 'bandages' all have a massage reading 'Your x falls into your molle assault pack' counting each individual unit of bandages, wipes, or gauze.

### Attach save file

[Chloride (1)-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11684281/Chloride.1.-trimmed.tar.gz)

### Steps to reproduce

1.make a player with bandages, gauze, or alcohol wipes in inventory (with a backpack) in O.G stable
2. Upgrade to recent experimental.
3.Spammed messages appear.

### Expected behavior

I expected no spam from every unit of the three items getting a message

### Screenshots

![Screenshot_20230608_001010](https://github.com/CleverRaven/Cataclysm-DDA/assets/72037738/54b47cbe-b117-40fa-b760-2c0c2e063494)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G975U; Release: 12; Incremental: G975USQS8IWC1; 
- Game Version: ec7537a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Tankmod: Revived [Tankmod_Revived]
]

### Additional context

I did have several problems upgrading my save due to an outdated mod, and this has been manually updated several times, so user error may account for the problem.

**Comment by mqrause** [comment] 2023-06-08 06:00
/confirmed

> user error may account for the problem

No, it's not your fault, it's a result of #65518, I think the issue here is that the message can't be combined into a message stack because the number of content items changes. It would _probably_ be less spammy if the message was just "Your bandage falls into your MOLLE assault pack." Or maybe just skip the message for items from MIGRATION pockets, because they (should) just end up where they were before anyway.

That definitely needs to be fixed for #60885 because there will be a lot of that when it gets merged.

**Closed** 2023-07-26 22:53 UTC
Labels: Info / User Interface, (S2 - Confirmed), [C++], Code: Infrastructure / Style / Static Analysis
