### ISSUE TITLE
[XEDRA Evolved] Essence Drain-ing a gracken crashes the game

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#78116] opened 2024-11-24 15:47 UTC
### Describe the bug

When i was playing as a lilin character, i tried to Essence Drain a gracken, only to be met with a crash. I figured it might happened to other creatures, but i havent checked.

### Attach save file

[Wood-trimmed.tar.gz](https://github.com/user-attachments/files/17893874/Wood-trimmed.tar.gz)

### Steps to reproduce

1. Open attached save
2. go to the nearby gracken and cast the Essence Drain spell on them
3. crash

### Expected behavior

Not crash

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE 8050; Release: 13; Incremental: 20240523.205226; 
- Game Version: cdda-experimental-2024-11-23-0704 8ff5859 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    Xedra Evolved [xedra_evolved],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    GUT's Xedra Evolved Compendium [gut_xedra_compendium],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    horde tweaks [horde_tweaks],
    Funni Loading Screens [loading_screen_funni]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17893877/crash.log)
[debug.log](https://github.com/user-attachments/files/17893878/debug.log)

**Comment by NetSysFire** [comment] 2024-11-24 15:56
I think this is a duplicate of #78069 but unsure if essence drain == ruach.

**Comment by gettingusedto** [comment] 2024-11-24 15:58
Think so, it gives me ruach when i drain someone with the spell. So this is a duplicate then?

**Comment by NetSysFire** [comment] 2024-11-24 16:01
I'd say yes.

**Closed by NetSysFire** 2024-11-24 16:01 UTC
Labels: (S1 - Need confirmation)
