### ISSUE TITLE
Game always crashes within a few turns, after updating to 0.E-10149-g894002b

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#48195] opened 2021-03-23 15:44 UTC
# Describe the bug

After updating the game to the most recent version as of 3/23/21, my game freezes then silently crashes out within 5-15 turns. This occurs when loading a pre-existing game as well as when creating a new character - either way the game freezes and crashes almost immediately after a few turns.

# Steps To Reproduce

1. load or start new character.
2. move a little ways or perform other actions
3. game freezes, then pops up microsoft "loading" pinwheel for cursor, and then silently crashes

# Expected behavior

1. expect to be able to play the game.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10149-g894002b [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp],
    Blaze Industries [blazeindustries]
]

# Additional context

[Childersbury.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6190858/Childersbury.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6190754/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6190755/debug.log)

***I've also been receiving an error for a week or so on every character file or new character or reload, about an M1911 that can't fit into a holster - this even occurs during character creation but hasn't been an issue even though I play daily, so I assume it's unrelated..***

 DEBUG    : tried to put an item (m1911_MEU) count (1) in a container (holster) that cannot contain it: pocket unacceptable because item is too long

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1115

**Comment by anothersimulacrum** [comment] 2021-03-23 15:50
Probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/48192

**Comment by Ketzenberg** [comment] 2021-03-23 18:51
having the same problem here as well

**Comment by actual-nh** [comment] 2021-03-23 19:06
> having the same problem here as well

Are you using a soundpack? If so, #48192 is the one you should take a look at.

**Comment by ZhilkinSerg** [comment] 2021-03-25 08:25
Duplicate of #48192

**Closed by ZhilkinSerg** 2021-03-25 08:25 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
