### ISSUE TITLE
Bug with Map generation?

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#27659] opened 2019-01-16 05:17 UTC
**Describe the bug**  

**To Reproduce**  
1. Load save
2. get in kart, travel west and then south toward unexplored area
3. game crashes after reaching first turn east

**Expected behavior**  
I would continually driving normally.

**Screenshots**  
![image](https://user-images.githubusercontent.com/7266560/51227746-4db48b80-191b-11e9-83bf-921eb53c4a13.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version [ 0.C-36428-g9802051]
 - Graphics version [Tiles]
 - Mods loaded [  "dda",   "no_npc_food",   "filthy_morale",   "Tolerate_This",   "craftgp",   "FIC_Weapons",  "realguns",   "ew_pack",    "makeshift",   "Medieval_Stuff",   "More_Survival_Tools",  "nw_pack",  "modular_turrets",  "Salvaged_Robots",  "national_guard_camp",  "more_locations",  "FujiStruct",
  "mapgen_demo",  "oa_additional_buildings_mod",  "Urban_Development",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "No_Big_Zombies",  "No_Explosive_Zombies",  "No_Acid_Zombies",  "more_classes_scenarios",  "manualbionicinstall",  "no_reviving_zombies",  "safeautodoc",  "StatsThroughSkills"]

**Additional context**  
CRASH LOG FILE: config/crash.log
VERSION: 0.C-36428-g9802051
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CD6A5[cataclysm-tiles.exe+0x1CD6A5]
    @0x5CE252[cataclysm-tiles.exe+0x1CE252]
    SMPEG_error+0x4B034@0xE666D0[cataclysm-tiles.exe+0xA666D0]
    _C_specific_handler+0x98@0x7FFF89167C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFF8B59F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFF8B50D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFF8B59E70E[ntdll.dll+0x9E70E]
    @0xD6E56B[cataclysm-tiles.exe+0x96E56B]
    @0xD6F9AE[cataclysm-tiles.exe+0x96F9AE]
    @0x8B49BE[cataclysm-tiles.exe+0x4B49BE]
    @0x6F4668[cataclysm-tiles.exe+0x2F4668]
    IMG_LoadWEBP_RW+0x4CC7C9@0x1445599[cataclysm-tiles.exe+0x1045599]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFF88A23034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFF8B573691[ntdll.dll+0x73691]

**Comment by jasonmbrown** [comment] 2019-01-16 06:01
Try using build 8416 or later then 8421 and see if the crash still occurs.
#27600 #27604
Guessing that its related to those.

**Comment by ZhilkinSerg** [comment] 2019-01-16 06:14
Update to latest version.

Duplicate of #27600.

**Closed by ZhilkinSerg** 2019-01-16 06:14 UTC
