### ISSUE TITLE
Stone axe can't chop tree trunks into logs or planks

### ISSUE THREAD

**Issue by TerraSleet** [CleverRaven/Cataclysm-DDA#22931] opened 2018-02-12 21:53 UTC
Game version:
Build 7116

Operating system:
Windows 10

Tiles or curses:
Tiles

Mods active:
Default

### Expected behavior
Be able to use the primitive stone axe to chop tree trunks into logs and planks.

### Actual behavior
Unable to do so, the construction action requires a level 2 tree cutting or level 2 wood sawing item. Stone axe is level 1 tree cutting. It used to be level 2 but was changed (nerfed?) at some point making it unable to create logs or planks. Possibly the same problem with stone adze as it's currently level 1 wood sawing but the action requires level 2.

### Steps to reproduce the behavior
Spawn stone axe, go to forest, chop down a tree, attempt to cut down resulting tree trunks using the Construction menu

### Suggested fix
Change stone axe to level 2 tree cutting OR change the "Chop Tree Trunk Into Logs" and/or "Chop Tree Trunk Into Planks" constructions to require level 1 tree cutting so the stone axe can be used to make logs and/or planks.

**Comment by smolbird** [comment] 2018-02-13 01:09
It used to be able to, but was broken by https://github.com/CleverRaven/Cataclysm-DDA/pull/22730.

**Comment by smolbird** [comment] 2018-02-13 01:16
Chopping down trees in a wilderness setting is your ONLY source of logs for construction in this instance, your main source of charcoal, etc. Stone axes are the only axes available in a wilderness scenario.

Being unable to cut down a tree with a stone axe is both unrealistic and detrimental to gameplay: https://www.youtube.com/watch?v=ppwShDKF-4k

**Comment by smolbird** [comment] 2018-02-13 01:27
Worse, if you can fell a tree in the first place, it makes no bloody sense that you can't chop them into shorter sections. Do you magically forget how to repeat the action you just took now that the tree is on the ground?

**Comment by kevingranade** [comment] 2018-02-13 02:58
What else has tree cutting or wood sawing 1? Perhaps we can allow very slow
progress at plank splitting with stone tools.

Treating stone tools as being the same as metal tools is clearly
inappropriate, that YouTube video suggests that felling a tree is a
multi-hour exercise with a stone axe, splitting would be similarly terrible.

**Comment by smolbird** [comment] 2018-02-13 03:01
Watch the actual video, or read the tl;dr I posted above: they said "about an hour" not "multi-hour exercise"

That might warrant a 4th axe quality, but either way this is a fundamental crippling of game mechanics that should be fixed.

**Comment by Night-Pryanik** [comment] 2018-02-13 17:47
You are blaming me as if I made cutting trunks impossible with wilderness-available axes on purpose. You are utterly wrong (and rude by the way). That was just unintended consequence.

**Comment by smolbird** [comment] 2018-02-13 18:30
Not intentional yes, but negligent. It's something that should've been caught during playtesting. Sorry I was a bit abrasive in the process. Admittedly it's more frustration that absolutely nobody caught that during the PR.

**Comment by Lamandus** [comment] 2018-02-13 21:06
@Night-Pryanik if it was just an unintended consequence. Why didn't you playtest it before? I am with smolbird on this one, why nobody saw the problem is also something I don't understand.

**Comment by kevingranade** [comment] 2018-02-14 01:51
We make no representation that we are not going to break any given feature
at any given time, and we do not have time to test every scenario.

You might be extremely concerned about pure wilderness starts, but that is
not the default way to play the game, and it does not get tested as much as
starts with cities.

You did find it and reported it, and it is going to be fixed, that is
working exactly as intended.  The workaround is to continue playing an
older version of the game until the issue is resolved (which should be
soon).

**Comment by smolbird** [comment] 2018-02-14 02:03
Part of it is also that the relevant section was directly underneath the removed construction entry. It should've actually been noticed during file editing, not even playtesting was really required. Measure once, cut twice. Wait, that's not how it goes...

Regardless, I'm working on it, but I'd like your feedback on my questions about how best to handle the code changes.

**Comment by Night-Pryanik** [comment] 2018-02-14 08:24
@Lamandus I didn't tested chopping _trunks_ because I was focused on testing chopping _trees_ (hence the name of my PR). That's why it is called unintended consequences.

**Comment by Lamandus** [comment] 2018-02-14 11:19
@Night-Pryanik . But it is like "trying to drive without checking the gear". You can either go forwarts (intended direction), backwards (breaking of other mechanisms) or just roar the engine (nothing is gained). Just testing the gas-pedal isn't enough, ya know.

**Comment by Night-Pryanik** [comment] 2018-02-14 11:55
> But it is like "trying to drive without checking the gear"

No, it's not. Chopping trees is not directly related to chopping trunks, while driving is directly related to shifting gears. I'm not perfect (I guess no one either) so I couldn't test my change in every possible situation. I tested my change on chopping trees, it seems to work fine.
As I said earlier, effect of my changes on chopping trunks was a side effect and unintentional. After all, this is what community feedback needed for - to catch sight of what's eluded the author's sight.

**Comment by Lamandus** [comment] 2018-02-14 13:11
it is directly related. What do you do with those trunks if you can't chop them up? This is the direct product of chopping something down.

**Comment by Night-Pryanik** [comment] 2018-02-14 14:21
>it is directly related. What do you do with those trunks if you can't chop them up? This is the direct product of chopping something down.

It is gameplay-related, not game-mechanics-related.

You can think whatever you like, but as I've said earlier, this was unintentional, and I'm not interested in continuing this futile argument.

**Closed** 2018-02-16 06:31 UTC
Labels: Balance, Easy-fix, JSON
