### ISSUE TITLE
Oops! All Nemesis! (Multiple Relentless Zombie Hulks)

### ISSUE THREAD

**Issue by 1rebis1** [CleverRaven/Cataclysm-DDA#74621] opened 2024-06-17 02:13 UTC
### Describe the bug

Character begins with "Hunted" Scenario, eventually kills the relentless zombie hulk, but more spawn en masse.

### Attach save file

[Extension-trimmed.tar.gz](https://github.com/user-attachments/files/15860665/Extension-trimmed.tar.gz)

### Steps to reproduce

1. Make character with "Hunted" scenario
2. Play until relentless zombie hulk is encountered
3. Kill relentless zombie hulk
4. "Hunted" trait is not dropped, nor is there any indication of the defeated enemy (mission, achievement, etc)
5. Inevitably encounter another, or even multiple others, especially around other monsters

### Expected behavior

The "Hunted" scenario is supposed to end when the relentless zombie hulk is killed. Then, the "Hunted" trait should resolve, and the mission be completed successfully.

### Versions and configuration

- OS: Windows 11
- Game Version: fcbf5b6 (64-bit) (Launched via Catapult)
- Graphics Version: Tiles
- Ingame Language: English
- Mods Loaded: dda, no_npcs_food, personal_portal_storms, no_fungal_growth

### Additional context

I use the Catapult launcher to launch CDDA. I have used the debug menu before, but not to alter or edit missions/monsters. I sometimes quit with Alt-4. I killed the first nemesis I found with a grenade.

**Comment by SkuliAdams** [comment] 2024-06-17 17:53
The hunter coming back is intentional, as per #73227. The problem is encountering multiple hunters simultaneously.

**Comment by 1rebis1** [comment] 2024-06-17 18:58
I'm doing the "Hunted" scenario, not "Hunted Forever". The flavor text for "Hunted" implies you can escape by killing the nemesis. Is that being changed? If so, should I close this and resubmit the bug?

**Comment by SkuliAdams** [comment] 2024-06-17 20:29
No, my bad. I believe that pr just added the "Hunted Forever" scenario, the "Hunted" scenario is supposed to work as you think.

I tried to replicate this in the most recent experimental by debug spawning a relentless hulk and killing it with a grenade, but found that the trait and mission cleared as expected. 
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.4 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-06-17-1821 88bfd69 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Swootch** [comment] 2024-06-21 15:25
Might be related to #74703, quitting with Alt+F4 is also know to cause strange behavior.

**Comment by PatrikLundell** [comment] 2024-06-22 17:53
I don't think #74703 is responsible, because I don't think this monster is part of a mapgen location (but rather is controlled by EoC magic. However, I failed to find out how it's spawned (the functionality seems to be hard coded, but I still failed to find the spawning code).

Testing it with both the #74703 code and the master code (as of this morning, my time) shows no difference: I get new hulks spawning in front of me on new terrain that hasn't been generated previously,

I can't ruling out the PR introducing #74169 being responsible, but I don't know how. It would have to call whatever is generating new hulks without properly checking whether it should (i.e. one still being active).
Debugging with a break point in that code and then head into uncharted terrain should find the call chain and find the point where the erroneous extra copies are generated.

**Comment by Brambor** [comment] 2024-06-22 18:50
I am not sure if you looked at the PRs and their code. If not there they are:

 - #42669
 - #73227

If you did look at the PRs and the code is just too convoluted, then ignore this.

**Comment by PatrikLundell** [comment] 2024-06-22 20:17
Thanks for the references.
As far as I can tell, there isn't anything specific for Nemesis when it comes to actually materializing, but it's created as a horde and then the horde logic takes care of the spawning into the reality bubble (and back to a horde when kicked out of it, I assume).
Furthermore, I can't see that hordes are involved in the code changed, as it seems to consist of only map extras and static spawns tied to the overmap terrain type (assuming terrain_type->get static_spawns() isn't a misleading name).

Unfortunately, it doesn't seem the game is particularly consistent in showing where nemesis hordes are. Sometimes I've had the character pursued by a couple of hulks, with a horde symbol a number of OMTs off (with another hunter showing up when reaching that area), and I've had a case where I dislodged the pursuing hulks by getting them to hunt aphids instead and then saw a small triple Z horde symbol where I left them, and found them still hunting aphids when returning, but most of the time there's no horde symbols, so it's hard to guess if spawns come from hordes that the game think are there or they come from somehow spawning the horde you can see.

**Comment by Brambor** [comment] 2024-06-22 21:20
> it doesn't seem the game is particularly consistent in showing where nemesis hordes are.

Reading the code, it assumes there is only one nemesis and then breaks the loop. So maybe it would work well if there was only one nemesis.

Also, I only looked at the references I provided. I didn't look at the current code.

**Comment by PatrikLundell** [comment] 2024-06-22 21:28
Unfortunately, code that works well when the rest is working correctly isn't that helpful in tracking down what's gone wrong...

**Comment by PatrikLundell** [comment] 2024-06-23 10:58
I still haven't found where hordes are introduced into the reality bubble in the code. However, I have two pieces of news:
- I've found where you display hordes: debug, info, display hordes (second entry in that long list, unless there's sorting involved). That shows there are hulk hordes all over the place, so wherever you go you'd run into them.
- In light of the above, I teleported one section south and walked around for a fair while, including advancing time by two days at one point. I didn't encounter any new hulks, nor did the horde horde make appreciable progress towards the PC. If only one is updated by the logic, it would be difficult to see movement unless you identified it so you could concentrate on its movements. This seems to indicate that whatever screwed up the game with hordes of hordes appears to have stopped. This experiment was done on a master downloaded a few hours ago.

And finally at @1rebis1: Looking at the mission screen, the text says you can't really kill your pursuer and that it won't end until you die. This indicates the scenario is really the Hunted Forever version, unless the text is misleading.

**Comment by Maleclypse** [comment] 2024-08-02 15:43
> I still haven't found where hordes are introduced into the reality bubble in the code. However, I have two pieces of news:
> 
> * I've found where you display hordes: debug, info, display hordes (second entry in that long list, unless there's sorting involved). That shows there are hulk hordes all over the place, so wherever you go you'd run into them.
> * In light of the above, I teleported one section south and walked around for a fair while, including advancing time by two days at one point. I didn't encounter any new hulks, nor did the horde horde make appreciable progress towards the PC. If only one is updated by the logic, it would be difficult to see movement unless you identified it so you could concentrate on its movements. This seems to indicate that whatever screwed up the game with hordes of hordes appears to have stopped. This experiment was done on a master downloaded a few hours ago.
> 
> And finally at @1rebis1: Looking at the mission screen, the text says you can't really kill your pursuer and that it won't end until you die. This indicates the scenario is really the Hunted Forever version, unless the text is misleading.

Hi Patrick, 
Do you have /confirm role on the repo or triage abilities?  I'm finding several S1 ones that from reading the comments you've confirmed but no one has changed the label to S2.   I realized it would be easier to make sure that you had the ability to add confirm label yourself but figured I'd check in on that in case you either already have it and don't feel comfortable using it for some reason or you plain don't want it.  Either is fine but please let me know if you do want it.

**Comment by PatrikLundell** [comment] 2024-08-02 16:06
I do have the ability, and I've used it (and seen it take effect). However, I'll only mark it as confirmed when I consider it to be a proper confirmation, rather than vague indications. Thus, me having seen it in the past would generally not be sufficient, as I consider that to be an indication.

The reason this particular issue wasn't confirmed was probably because I did not agree with the assumption that my referenced PRs were responsible.

Someone later provided me with the references I needed in one of the other reports, and once a bug has been fixed there's not much point in confirming it.
Anyway, this problem should have been fixed by #75083, but there's the wider issue of multiple bug reports for the same problem, and that PR only listed one of them. There was also some confusion about which scenario reporters were actually playing, since the PR only fixes the respawning case. However, I don't think any of the cases were the non respawning one (even though this report claimed it was, but the quest log didn't support that, as it had the wording of the repeating one.

**Closed** 2024-08-02 16:23 UTC
Labels: (S2 - Confirmed), Spawn
