### ISSUE TITLE
Gaining extra limbs crashes game

### ISSUE THREAD

**Issue by Enderlordalatreon** [CleverRaven/Cataclysm-DDA#42793] opened 2020-08-08 05:59 UTC
Gaining extra limbs, such as Arachnid arms, crashes the game, getting this message.
![Annotation 2020-08-08 015357](https://user-images.githubusercontent.com/66154890/89703581-17ce6200-d91a-11ea-9d55-374b18b29068.jpg)

# Steps To Reproduce

Spawn npc (I used different npcs), mutate them with spider mutagen (or debug the Arachnid arms mutation), game crashes with above error message. This also crashes with the player.

# Expected behavior
Arachnid arms (as well as every other limb growing mutation like tentacle legs) works as intended and doesn't produce the above error.

Logs:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5044730/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5044731/debug.log)
Mod list:
[mods.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5044734/mods.txt)

**Comment by mqrause** [comment] 2020-08-08 11:37
This should be fixed in experimental build 10904. (#42762)

**Comment by Qrox** [comment] 2020-08-08 12:53
The crash might have been fixed, but the debug message probably has not. There's something wrong elsewhere if `bp_null` is passed as an id to `get_part`.

**Comment by mqrause** [comment] 2020-08-08 13:22
Yeah, that does seem like a weird call. I just tested it though, and it doesn't produce a debug message.

**Comment by Enderlordalatreon** [comment] 2020-08-08 23:25
Let me update and do a few tests.

**Comment by Fris0uman** [comment] 2020-08-09 07:45
I can't reproduce it, gaining the mutation both through serums and debug does not cause any error for me.

**Comment by KorGgenT** [comment] 2020-08-24 06:25
closing as fixed. please reopen if the bug still exists.

**Closed by KorGgenT** 2020-08-24 06:25 UTC
Labels: Mutations / Traits / Professions
