### ISSUE TITLE
Crash when trying to kill or after killing a hostile military deserter near his outpost in the city. ​

### ISSUE THREAD

**Issue by Oeuueeieiw** [CleverRaven/Cataclysm-DDA#70649] opened 2024-01-04 17:23 UTC
### Describe the bug

This is the first time I encountered such a strange error. Each time, after killing any of these deserters, the game would crash during the next turn. It didn’t matter who killed them and how, the game still crashed after that.

### Attach save file

[Новая-Aнглия.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833482/-A.zip)

### Steps to reproduce

1. I aim my ranged weapon at the deserter.
2. I fire a shot and kill him.
3. I'm trying to wait for a new move

### Expected behavior

The turn after killing the deserter NPC must be completed successfully.

### Screenshots

![Screenshot_2024-01-04-23-00-59-330_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/100699298/656ba086-80d2-45b3-9108-69d66e4cfb37)
![Screenshot_2024-01-04-23-00-55-422_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/100699298/13f71b61-42f2-4902-81ea-2aba583f3018)

### Versions and configuration

- OC: [Android 8]
- Game version: [1ec6b8c (64-bit)]
- Tileset: [Ultica]
- Language: [System (Russian)]
- Loaded mods mods: [dda], [translate_dialogue], [package_bionic_professions], [personal_portal_storm], [alt_map_key], [minimod_no_rust], [stamina_pool_buff]

### Additional context

[crash.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833529/crash.log.zip)
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833536/debug.log.zip)
[Новая-Aнглия.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13833541/-A.zip)

**Comment by RenechCDDA** [comment] 2024-01-05 05:30
@prharvey Looks like this (a bad reference?) is probably caused by #69574, do you mind taking a look?

**Comment by RenechCDDA** [comment] 2024-01-05 05:34
Possibly resolved by #70660

**Comment by Oeuueeieiw** [comment] 2024-01-05 08:34
When my character was near his outpost, a message constantly popped up in the notification log that some creature was howling underground. I think your assumptions on this matter are absolutely correct.

**Comment by prharvey** [comment] 2024-01-05 21:13
I know what is causing this and what to fix. Just need to run some errands IRL then can put out a PR.

**Closed** 2024-01-06 21:21 UTC
Labels: <Crash / Freeze>, (S1 - Need confirmation), Monsters
