### ISSUE TITLE
Lappin, Warrener dialog choice (accepting quest) leads to game hanging

### ISSUE THREAD

**Issue by morikal** [CleverRaven/Cataclysm-DDA#47595] opened 2021-02-19 04:41 UTC
Crash when accepting a quest to go check on his farmer neighbors.

# Steps To Reproduce

In the attached save, talk to Lappin Warrener right next to where you load.
Select option c, "Heard anything about the outside world?"
Then select option b, "Anyone nearby I should meet?"
Then select option a, "Sounds like a deal to me."

Game hangs.

# Expected behavior

No hang/crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9737-g511ddcb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

No crash log--the executable hangs and windows eventually asks if I want to close it.

Save: [BugReproduceFarmerHang.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6007697/BugReproduceFarmerHang.zip)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6007696/debug.log)

**Comment by Maleclypse** [comment] 2021-02-19 05:47
Duplicate of #47225.

**Comment by Maleclypse** [comment] 2021-02-19 05:48
Should be fixed by #47510

**Closed** 2021-02-19 05:54 UTC
Labels: (S3 - Duplicate)
