### ISSUE TITLE
Cannot dig a shallow pit if there is one nearby

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#63810] opened 2023-02-26 16:58 UTC
### Describe the bug

You cannot dig a new shallow pit when (a)ctivating a digging tool if there is at least one adjacent to the player; it will only allow you to make the existing pits deeper

### Attach save file

N/A

### Steps to reproduce

 1. Get a digging tool (e.g., entrenching tool)
 2. Dig a shallow pit
 3. Attempt to dig another shallow pit
 4. Notice that only the shallow pit(s) are highlighted
 5. Be prompted that you cannot build a shallow pit where the ground is flat

### Expected behavior

You can always dig a shallow pit regardless of other nearby pits.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 95b8cca [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

Removing the ability to dig pits via (a)ctivating digging tools may be easier, as using the (*)construction menu works as expected.

**Comment by andrei8l** [comment] 2023-02-26 17:59
Duplicate of #59232

**Closed** 2023-02-26 20:17 UTC
Labels: (S1 - Need confirmation)
