### ISSUE TITLE
NPC training offers training in bartering

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#47444] opened 2021-02-12 07:10 UTC
They offer training and the game tracks the improvement. 

1. Can't tell if it actually affects anything
2. If there is a Barter proficiency, it isnt being displayed

**Comment by PaulBlay** [comment] 2021-02-12 09:17
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/46364

**Comment by actual-nh** [comment] 2021-02-12 14:34
> Duplicate of #46364

The information that the game appears to be "tracking" the improvement (how?) may be new.

**Comment by PaulBlay** [comment] 2021-02-12 14:59
> The information that the game appears to be "tracking" the improvement (how?) may be new.

When you select a skill to train it shows what your current skill level is and what percentage progress you have made on that level. Presumably if you train twice in the same skill it will show that your skill is no longer at level 0, 0%. 

I don't think anything has changed, I just think nobody bothered to get trained twice in the same obsolete skill.

As to how it is tracking the changes, I guess the obsolete skills are still in the system somewhat to avoid errors when loading old saves?

**Closed** 2021-02-12 15:29 UTC
Labels: (S3 - Duplicate)
