### ISSUE TITLE
Spawn inside a stone

### ISSUE THREAD

**Issue by stelscarrot** [CleverRaven/Cataclysm-DDA#52742] opened 2021-11-10 14:47 UTC
### Describe the bug

Spawned into solid stone wall, surrounded with other stone walls.
Save attached.

### Steps To Reproduce

1. Start a lab run
2. Suffer

### Expected behavior

Not requiring to restart game multiple times to play it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 6db9695 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Eagledale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7513542/Eagledale.zip)

**Comment by Termineitor244** [comment] 2021-11-11 03:35
Confirmed in a version from 2 weeks ago, I was trying to start a lab start (old lab) and I had to make multiples tries since I spawned in stone several times.

**Comment by jbytheway** [comment] 2021-11-14 21:09
This turned out to be a bug where the game was checking the wrong z-level's terrain to determine start point suitability.  Fixed in #52823.

**Comment by stelscarrot** [comment] 2021-11-15 07:08
> This turned out to be a bug where the game was checking the wrong z-level's terrain to determine start point suitability. Fixed in #52823.

But there was also no lab rooms on other z-level. Or it checked above the ground?

**Closed** 2021-11-17 06:31 UTC
Labels: (S1 - Need confirmation), Spawn, Character / World Generation
