### ISSUE TITLE
Adding in Door Locks

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#55014] opened 2022-02-02 10:50 UTC
### Is your feature request related to a problem? Please describe.

My NPCs love to sit in the driver seat every time I touch a vehicle. They also love to leave doors open, and often I don't want to have to toggle the "close opened doors" ability through the conversation options all the darned time, it's just unnecessary complexity to the point that I often remove most of the doors on my vehicle because of this (and because solid panels are burlier than doors obviously.)

We already have door controllers that allow you to toggle your vehicle doors open and closed and even control them individually but they're a bit cumbersome to use in terms of keypresses. 

### Solution you would like.

I'd love to be able to lock some doors or build and install a lockable car/building door that my NPCs cannot go through, or which only allow opening from one side even by the player character. These type of doors could also be added to some buildings - like a reinforced deadbolted door that you have to break down or go around, or talk to a NPC through to get it opened as an example.

We already have locked cargo compartments and the description says it prevents items from being "stolen" but I honestly have no idea how or if they can prevent friendly PCs from grabbing loot out of them, and it seems like a locking car door is not too far fetched but it might help reduce the need to perform some types of manual NPC/door control while driving or in vehicles etc. 

Lockable building doors could also be cool - maybe a deadbolt or drop-bar lock that's only openable from one side, or the ability to lock a building door so NPCs cannot go through them unless you open them yourself _(and yes I know NPCs often get stymied by closed windows next to an open window, but still it seems like a cool and possibly useful feature.)_

### Describe alternatives you have considered.

Leave things the way it is, or maybe tweak keybinds for door controllers etc to require less keypresses.

### Additional context

This could also make some vehicles like minivans that have already-installed door controllers a little more desirable if you're driving around with a crew of NPCs and you can toggle door locks (child safety lock, lol!) so they don't open a door and ride on the sideboard _(this is an issue with some quest NPCs like the angry pizzaiolo guy, who you cannot "control" but he insists on coming with you and he tries to attack everything you drive past while he's riding in the car)._ You could also use locked doors to force NPCs to remain in place despite/in addition to setting them to "guard" which doesn't always work, since some NPCs just flip out and act really bizarrely when they hear threats nearby etc, despite turning off the ability to investigate noises, attack enemies etc they will sometimes just start running in circles and hollering about some nearby noise or threat that's well outside of their range.

**Comment by ZhilkinSerg** [comment] 2022-02-02 11:05
Duplicate of #46160

**Closed by ZhilkinSerg** 2022-02-02 11:05 UTC

**Comment by coyo7e** [comment] 2022-02-02 11:11
I'm sorry - if I find a closed issue am I supposed to just not talk about it ever again? It's confusing that you aren't supposed to comment etc on closed issues, but something that's well over a year old with no comments may still be a good idea and there's no way to tell if anyone is talking or thinking about it or if it's just been turned down.

**Comment by ZhilkinSerg** [comment] 2022-02-02 11:59
What exactly do you mean? #46160 is not closed.

**Comment by coyo7e** [comment] 2022-02-02 12:09
> What exactly do you mean? #46160 is not closed.

_>stale bot commented on Jan 20, 2021
Please do not 'bump' or comment on this issue unless you are actively working on it. Stale issues, and stale issues that are closed are still considered._

**Comment by ZhilkinSerg** [comment] 2022-02-02 20:09
So, what exactly the problem here? If you have to add some meaningful comment to `Stale` issue - go ahead. If you just wanna bump the issue with something like "me want it too" - don't do that as `Stale` issue is still considered.

**Comment by coyo7e** [comment] 2022-02-02 22:33
Your words do match up with what sale-bot said. It says to actively never comment on that post unless you're legit working on a related tweak. And your tone of voice is super-rude, my dude.

**Comment by ZhilkinSerg** [comment] 2022-02-08 14:38
> As my grandma used to say, "if you got nothing nice to say, then don't.

Have you ever followed her advice?

**Comment by LeahLuong** [comment] 2022-02-08 17:31
You 2 really need to come together & hug this out. Although neither of you is totally wrong, you've both spent time wrestling in the mud & gotten dirty.

Zhilk, recontextualizing coy's quote & dropping a "last word" like that seems in bad faith on a thread that was likely going to spin off into nothingness. Not only that, it's likely to spawn another bout of word diarrhea from him.

coy, you need to pay closer attention to what Zhilk & stalebot have said previously. #46160 is _**not**_ closed for good reason. NetSysFire removed the stale tag from that issue prior to this pissing contest I'm witnessing. Zhilk can be terse in his comments but I seldom think there is ill intent behind them; I don't feel the same about your comments which contain sarcastic apologies & name-calling.

Now, shake hands, slap each other's backs, & be done w/ it.
