### ISSUE TITLE
Curtains can be torn down and closed from the outside

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29081] opened 2019-03-28 16:13 UTC
You can tear down and close curtains from the outside of the building.

**To Reproduce**  
Go to a building on the outside that has curtains and tear them down or close them.

**Expected behavior**  
Inability to interact with curtains from the outside.

**Versions and configuration**
0.D-1062-g14a0cbf

**Comment by Night-Pryanik** [comment] 2019-03-28 17:02
What sort of window you're trying to interact with?

Tested right now - the only way to tear down curtains from outside of the building is to interact with open window with curtains, and this is intended behavior, as you can reach the curtains through the open window.

**Comment by Phenomphear** [comment] 2019-03-28 21:54
It was a window next to a front door on a house, but I tried to do it again and it doesn't happen anymore. Maybe I made a mistake.

**Comment by Night-Pryanik** [comment] 2019-03-29 03:49
Ok, then closing until confirmed.

**Closed by Night-Pryanik** 2019-03-29 03:49 UTC
Labels: (S1 - Need confirmation), Fields / Furniture / Terrain / Traps
