### ISSUE TITLE
Chesthole32 tileset lacks art for Tear in Reality

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#18953] opened 2016-10-23 09:02 UTC
So after spending a good while fending off dozens of assorted sub-prime abominations, I finally figured out where they're coming from.

There's a tear in reality, which is completely invisible while using the chesthole32 tileset. I only managed to find it by accidentally attempting to walk through it, whereupon the game asked me if I was sure I wanted to do so.

Screenshot attached
![error 5](https://cloud.githubusercontent.com/assets/19789267/19625130/636a0f8c-9942-11e6-855e-e6276c1b5674.png)

**Comment by DangerNoodle** [comment] 2016-10-23 16:16
Same occurs in the M Shock series.

This is likely deliberate though, but it depends on whether they are depicted as invisible in ASCII mode. If they are, then this is consistent and not a bug.

**Comment by MisterFox** [comment] 2016-10-23 16:43
In ASCII, they are depicted as a purple zero.

**Comment by Solusphere** [comment] 2016-10-24 00:50
Yeah, they're perfectly visible in ASCII, so this does need to be addressed. Imagine if I'd driven my vehicle into it....*shudder*

**Comment by Solusphere** [comment] 2016-10-24 01:04
Just double checked, they actually look like a yellow 0,&,8 or + symbol, shifting between characters whenever the screen is redrawn. Screenshot attached.
![image](https://cloud.githubusercontent.com/assets/19789267/19631021/96eb3148-99c8-11e6-831b-f3df83196967.png)

**Comment by DangerNoodle** [comment] 2016-10-24 18:05
Are there any existing sprites in the MShock series that would fit that? For the Chesthole series, @Chezzo could presumably handle the change themselves if desired, but MShock is not active much, and Chaosvolt is not an option either.

I have a small degree of competence with sprite editing, but I would rather avoid adding new ones to a tileset that is not mine. Additionally, I would have to find somewhere to place them. Placing them in the logical order on the sprite sheet would require the tedium of changing the tile_config numbers.

This leaves the alternatives of placing them at the bottom of the sheet (which makes for poor organization), or adding them in a separate image file (assuming that the tile configuration supports this).

**Comment by Chezzo** [comment] 2016-10-24 22:04
I think this is a code issue where the tile does not show in tiles mode.

**Comment by DangerNoodle** [comment] 2016-10-24 22:38
Odd. You did not assign it a transparent space as its sprite?

**Comment by Chezzo** [comment] 2016-10-24 22:48
Nope, I did not assign it as a transparent space as a sprite.

**Comment by BorkBorkGoesTheCode** [comment] 2016-10-24 23:49
>I have a small degree of competence with sprite editing, but I would rather avoid adding new ones to a tileset that is not mine.

Use an editor that respects PNG transparency if you try it.

**Comment by DangerNoodle** [comment] 2016-10-25 00:01
> Nope, I did not assign it as a transparent space as a sprite.

Strange. What about other invisible traps, like the anomalies? Are they visible in tiles mode?

> Use an editor that respects PNG transparency if you try it.

I am aware of that, yes.

**Comment by Chezzo** [comment] 2016-10-25 12:17
I think it is the only one that does not work, possibly because of the ascii "animation". Things like tr_temple_flood don't show, but they don't show in ascii either.

**Comment by kevingranade** [comment] 2017-03-29 04:42
The animation feture isn't necessary, but it needs to t least draw a fallback tile.

**Comment by Chezzo** [comment] 2017-06-01 13:23
I can not duplicate this issue.

From the tests I did, portals show the same for both ascii and tiles. If you spawn a portal (using a portal generator or lab finale computer) in either version, it appears the turn AFTER you spawn it. 

So activate the portal generator or use the lab finale computer, then hit 5, and there it is. This happens whether you use a tileset or not.

If you spawn a portal with the debug map spawn, it shows the ascii fallback % in tiles mode.

**Comment by DangerNoodle** [comment] 2017-06-01 15:41
Portal is not the same as tear in reality.

**Comment by Chezzo** [comment] 2017-06-01 17:25
Oh. Can you generate a tear in reality? It doesn't show in the debug map generation of traps, furniture, field, or in my missing tiles checker.

**Comment by Leland** [comment] 2017-06-01 17:30
@Chezzo yeah! It's a [3rd level "fd_fatigue" field. ](https://github.com/CleverRaven/Cataclysm-DDA/blob/4bcc67a9d0b5dc3d2b8844fb3705e4b524fdcb23/src/field.cpp#L231)

**Comment by Chezzo** [comment] 2017-06-01 18:29
Awesome, yeah it shows when I set something to fd_fatigue.

![image](https://cloud.githubusercontent.com/assets/2432177/26694816/bd770790-46d6-11e7-8d93-3dca9f282f1e.png)

**Comment by LyleSY** [comment] 2017-06-24 21:41
I just reproduced on a recent Mac build:
![screen shot 2017-06-24 at 5 38 16 pm](https://user-images.githubusercontent.com/26608431/27512115-44012932-5904-11e7-8866-e46f8700c53a.png)

**Comment by LyleSY** [comment] 2017-06-24 21:44
Ahem, reproduced with Chesthole32. Last screenshot was Chesthole original flavor:
![screen shot 2017-06-24 at 5 43 38 pm](https://user-images.githubusercontent.com/26608431/27512138-d1015e74-5904-11e7-841f-e4ae1b4999f9.png)

**Comment by Leland** [comment] 2017-12-05 19:10
Pinging @Chezzo if you have anything in mind for the tear! Maybe just that portal you have in your screenshot above?

This is probably the easiest remaining [0.D issue](https://github.com/CleverRaven/Cataclysm-DDA/milestone/10).

**Comment by BorkBorkGoesTheCode** [comment] 2018-02-04 04:23
@Chezzo ?

**Comment by Chezzo** [comment] 2018-02-04 12:20
@BorkBorkGoesTheCode ?

**Comment by BorkBorkGoesTheCode** [comment] 2018-02-04 17:00
@Chezzo 

>if you have anything in mind for the tear! Maybe just that portal you have in your screenshot above?

Can this be closed now?

**Comment by ZenZen2** [comment] 2018-03-14 09:21
fd_fatigue is not missing a tile, it uses a transparent tile ``` "fg": 643, ```
changing it to ``` "fg": 2600, ``` should turn it into the portal that is visible on chezzo's picture.

**Closed** 2018-03-14 20:59 UTC
Labels: Bug, Confirmed, Easy-fix, Tiles
