### ISSUE TITLE
Getting pulled out by zombies while driving car

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#44310] opened 2020-09-21 08:26 UTC
I was driving car with 5 point safety belt installed and got pulled out by some grabbing zombies.

# Steps To Reproduce
1. Get car with safety belt
2. Find grabbing zombie
3. Drive near him at low/medium speed
4. Get pulled out

# Expected behavior
Get zombie dragged by car or deal damage to belt.

**Comment by Night-Pryanik** [comment] 2020-09-22 11:49
Duplicate of #22764.

**Closed by Night-Pryanik** 2020-09-22 11:49 UTC
