### ISSUE TITLE
Inventory Sorting Crash

### ISSUE THREAD

**Issue by figment** [CleverRaven/Cataclysm-DDA#17949] opened 2016-08-06 20:12 UTC
I've encountered a semi-repeatable crash involving inventory category sorting using recent code from master.  The crash most frequently occurs with specialized mutagen vials (spider, lizard, ...) in the inventory area being looked at with category sorting enabled.

The bug seems to be related to how categories are loaded for specialized mutagen vials.  And specifically that "mutagen" appears after "iv_mutagen" and related children.  The copy-from tag is likely loading category out of order.

I would guess that when iv_mutagen is loaded the copy-from will reference old copies of mutagen and copy the old category pointer.  The old pointer will cause the crash later when its used as part of the sort.

To semi-reproduce:
1. Put lizard/spider/... vial in inventory.
2. Look at inventory with "/" (enable sort by Category)
3. Save and Quit to main menu (do not exit to desktop)
4. Immediately Reload
5. Open Inventory with "/"
-> crash

I'm not sure its 100% reproducible with these steps but that was basically working for me most of the time on Windows VC2015 x64 locally built exe.  

Temporary Fix:
1. Reorder mutagen.json so that "mutagen" and "mutagen_flavor" are at the top of the file.

Have not encountered this bug since the reorder but occurred frequently after picking up mutagen and moving between levels in the Lab and looking at inventory.

**Comment by codemime** [comment] 2016-09-20 01:36
Tried all that listed above several times, but couldn't make the game crash. #17933 reliably reproduces.

**Comment by illi-kun** [comment] 2016-09-20 07:25
@codemime do you have anything else in inventory? I got crash with no other items in inventory.

**Comment by codemime** [comment] 2016-09-20 12:22
@illi-kun Neither with nor without. I can't reproduce the crash (Linux x64). Maybe its platform specific or caused by undefined behavior and happens only occasionally.

**Comment by illi-kun** [comment] 2016-10-01 22:17
@codemime it's 100% reproducible for me on Windows, and I also checked this on Linux Mint (x64) and got this:
![cat](https://cloud.githubusercontent.com/assets/5421954/19017309/e871b79a-883d-11e6-9bc4-0d07d99aef49.png)

**Comment by codemime** [comment] 2016-12-04 20:51
Can anybody (whose game crashes) post a stack trace?

**Comment by BrettDong** [comment] 2017-01-16 11:34
Unable to reproduce the crash on the latest master branch, MSVC 2015 with Update 3, x64, Release. Tried tens of times. It's just showing up fine.

**Comment by Coolthulhu** [comment] 2017-02-18 02:09
Wasn't confirmed for a while, closing as no longer able to reproduce.
Could be something that was refactored since then.

**Closed by Coolthulhu** 2017-02-18 02:09 UTC
Labels: Confirmation Needed, Crash, Priority
