### ISSUE TITLE
Segfault while using items with charges in the environment

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35701] opened 2019-11-24 18:41 UTC
# Describe the bug

Game segfaults when an item (with charges, like oxygen tank) is used while on the floor, outside of the inventory with inventory capacity maxed out and hands full.

# Steps To Reproduce

1. Fill backpack with junk, wield a nailbat
2. Use oxygen tank dropped at feet
3. Segfault crash

# Expected behavior

It should work without crashing

# Versions and configuration

 - OS:  Windows 10
 - Game Version: 0.D-9634-g962e122 (tiles)
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, tattos, hairstyles

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3883993/crash.log)

**Comment by anothersimulacrum** [comment] 2019-11-24 18:54
Duplicate of  #35673

**Closed** 2019-11-24 19:08 UTC
Labels: (S3 - Duplicate), <Bug>, <Crash / Freeze>
