### ISSUE TITLE
crafting still continues even if requirements are no longer met

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16775] opened 2016-05-20 13:01 UTC
when crafting using nearby fire crafting continues even if the fire goes out

**Comment by BevapDin** [comment] 2016-05-25 12:06
Nearly a duplicate of #7126, but there might be more issues about this issue (that particular game mechanic is old and the problem exists since forever). The same problem exists about items that are used for crafting, but vanish while doing so (e.g. burn in the fire).

**Comment by illi-kun** [comment] 2016-11-09 19:17
Closing as a duplicate.

**Closed by illi-kun** 2016-11-09 19:17 UTC
