### ISSUE TITLE
Crash when crafting food

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#43214] opened 2020-08-25 13:28 UTC
# Describe the bug

The game crashes when I try to craft food.

# Steps To Reproduce

Open the crafting menu
Try to craft something in the Food category
It doesn't happen when I craft something else

# Expected behavior

I expect food to be crafted and the game to go on

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5366-g7f91078 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5123959/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5123961/debug.log)
[New England.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5123970/New.England.zip)

World and save files included

**Comment by ashGlaw** [comment] 2020-08-25 19:40
Update:

I had recently tamed a chihuahua, and it seems related to the crash. I put it in a pet carrier, and now I can craft food again. Weird

**Comment by whatdice** [comment] 2020-08-25 23:06
I'm experiencing the same bug, on 10946 Win 64. The attached save contains a character that is currently crafting salt, continuing to craft it will quickly show you the SegFault.
Related: I do not have any pets, chihuahua or otherwise.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5126682/crash.log)
[Deloit.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5126686/Deloit.zip)

**Comment by ZhilkinSerg** [comment] 2020-08-27 16:13
Duplicate of #41828

**Comment by Profit0004** [comment] 2020-08-29 08:39
I am also experiencing this crash.. I am not sure but I believe it may be due to crafting in my hands while I have the mutant shakes.  I think it is "dropping the weapon" which would be the items I am crafting and segfaulting, but I obviously cannot be sure.

**Closed** 2020-10-25 08:15 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
