### ISSUE TITLE
(Massachussets mod) mapgen issues

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#60079] opened 2022-08-11 12:40 UTC
### Describe the bug

mapgen of MA mod creates random patches of "lake shore" in the overmap, without a lake
those patches do not make much sense, i was told to make an issue about it

### Steps to reproduce

1 create character ina MA world (i had standard city size and spacing)
2 debug overmap reveal and observe

### Expected behavior

lake shore map tiles are expected to spawn around lakes, not in random patches near forest/swamps

### Screenshots

![image](https://user-images.githubusercontent.com/42104923/184134689-a420b2d9-5c90-41b6-a912-afe2ef2947a7.png)
![image](https://user-images.githubusercontent.com/42104923/184134743-68a194b0-b427-4cf7-87fb-e0883e6f9ec7.png)
![image](https://user-images.githubusercontent.com/42104923/184134848-05c29f41-52f8-4757-944f-3b49573740ec.png)
![image](https://user-images.githubusercontent.com/42104923/184148530-6b642d7b-3d3c-4177-8874-5b5376406816.png)
![image](https://user-images.githubusercontent.com/42104923/184148705-2e15e9d2-8a9c-45a0-a51f-a0a035a4581c.png)

### Versions and configuration

Windows 10
Build 2022-08-11-0602
Tiles
English
mods:
  "dda",
  "blazeindustries",
  "MA",
  "no_npc_food",
  "no_fungal_growth",
  "speedydex",
  "stats_through_kills",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"

**Comment by GuardianDll** [comment] 2022-08-11 13:46
Guess we need some tiles wirh water, but not lakes or rivers
/confirmed

**Comment by NetSysFire** [comment] 2022-08-11 16:55
Duplicate of #58118.

**Closed by NetSysFire** 2022-08-11 16:55 UTC
Labels: (S2 - Confirmed)
