### ISSUE TITLE
When in [X]Peek//E[x]amine mode, Shift + Direction to jump cursor a set number tiles

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23847] opened 2018-05-25 23:06 UTC
Game version: 0.C-27943-g56bbaf0 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: (Default) 

### Expected/Suggested behavior: 
To save key presses. When in peek/examine mode it would be nice to have an option to jump (Similar to Dwarf Fortress) a set number of tiles (Set in options, Default: 10?) distance by holding shift while hitting a direction key.

### Actual behavior
A single press of the direction key only moves the cursor one tile.

**Comment by BevapDin** [comment] 2018-05-25 23:51
Duplicate of #7100.

**Closed by BevapDin** 2018-05-25 23:51 UTC
