### ISSUE TITLE
soda can stove reloading buggy ver:0.C-10085-g6b59b99

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#15224] opened 2016-02-03 19:44 UTC
Current play through I'm using soda can stove for the first time and noticed some bugs.
Reloading from a full bottle removes ethanol from bottle and puts it into inventory as a liquid.
Reloading with no ethanol in inventory caused a crash, but I couldn't replicate it when I tried.

**Comment by sctjkc01** [comment] 2016-02-03 19:48
...potential dupe of #15200.

**Comment by nonymous** [comment] 2016-02-03 19:57
replicated "DEBUG:Tried to get an item from a character who doesn't have it" 
Then something about reloading with bad ammo, then items tumble to the ground. When I looked it was an oil lamp fell out of my inventory.

This time though there was no core dump.

**Comment by mugling** [comment] 2016-02-03 22:05
Yes, duplicate of #15200. Please test the fix in #15206

**Comment by mugling** [comment] 2016-03-07 10:24
Was fixed by #15206

**Closed by mugling** 2016-03-07 10:24 UTC
