### ISSUE TITLE
[ImGui] Color and font customisation

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#75774] opened 2024-08-17 15:20 UTC
### Is your feature request related to a problem? Please describe.

First of all, many thanks to @katemonster33 and everyone else implementing ImGui in CDDA.

The current ImGui style is very nice and a great step forward from pure ASCII. However, the default style of ImGui can be very different from the style players might apply to other game interface objects.

### Solution you would like.

I’d like to change the default settings of ImGui. According to the ImGui demo screen, there are some possibilities to do so for colors and font. However, I’m almost 100% sure that they can’t be done in the current state. If there could be some sort of ImGui config file that players can change to apply new styles, that would be great.

It would be a great bonus if we could provide different presets to the repository so players can choose whichever they want, similar to the current color schemes for the classic interface.

### Describe alternatives you have considered.

Leave as is.

### Additional context

![image](https://github.com/user-attachments/assets/27892a8e-ac67-44d7-9b3d-d5f164383ee0)
![image](https://github.com/user-attachments/assets/14deb1d7-a97a-4629-a421-7ab9c8bc773e)
As you can see I use `dark` color scheme and bold Terminus font instead of Unifont.

**Comment by GuardianDll** [comment] 2024-08-17 15:23
I close it as duplicate of #75699, it is a long desired feature indeed

**Closed by GuardianDll** 2024-08-17 15:23 UTC
Labels: <Suggestion / Discussion>
