### ISSUE TITLE
[Suggestion] Add the ability to disassemble the heavy flashlight

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14649] opened 2015-12-28 15:58 UTC
As the title states - Make it possible to disassemble to heavy flashlight, make it yield little more components than the normal one.

**Comment by sparr** [comment] 2015-12-28 16:26
I always though that part of what made the heavy duty flashlight special is that it's not disassemble-able.

**Comment by Coolthulhu** [comment] 2015-12-28 16:35
Uncraftable part is fine, but a dedicated survivor should be able to disassemble everything, even if only into regular crappy parts.

**Comment by Skidborg** [comment] 2015-12-29 00:24
Given the the other high-tier electronics recipes, one for "a brighter flashlight with more batteries" probably wouldn't be above level 4.

**Comment by sparr** [comment] 2015-12-29 00:35
Part of the "heavy duty" in my mind is a cast steel case, not held together by screws/etc. A dedicated survivor can *smash* everything for misc components, but there are definitely things that can't be disassembled into the parts required to rebuild the thing.

**Comment by Malkeus** [comment] 2015-12-29 02:47
Heavy duty flashlights -> small metal tanks conversion recipe, secondary
products are scrap electronics and some L.E.D.s

**Comment by Skidborg** [comment] 2015-12-29 03:45
If I can forge armor for a car, I can probably also weld a bulletproof casing for a flashlight.

**Comment by sparr** [comment] 2015-12-29 03:51
Of course you can. That doesn't mean you can do it with just the parts you get taking one apart.

**Comment by Skidborg** [comment] 2015-12-29 06:19
That's probably true of any of the electronics in CDDA, but that's how the crafting system works.  I see no reason a heavy flashlight should be a special exception.

**Comment by sparr** [comment] 2015-12-29 06:23
Any weatherproof impactproof bludgeoning-capable electronics should be an exception.

If it's held together with screws and plastic tabs, you can take one apart, mix and match the parts, and put one back together.

If it's welded together, you don't get a flashlight case when you open it, you get scrap metal.

**Comment by Skidborg** [comment] 2015-12-29 06:30
But real flashlight batons are /not/ welded together.  You essentially take a section of pipe, stick a cap and a spring at the bottom, throw batteries into it, and screw a basic LED assembly onto the other end.  It's waterproof, bludgeon-capable, and completely possibly to take apart and put back together in two minutes.

**Comment by sparr** [comment] 2015-12-29 06:43
You're describing a maglite. I'm describing the kind of flashlight that takes a 6V lantern battery, many of which have welded plastic bodies.

**Comment by Skidborg** [comment] 2015-12-29 06:54
Which isn't the kind of flashlight described by the "heavy duty flashlight" flavor text.

> This is a heavy duty tubular aluminium LED flashlight as often used by security guards. Makes for a passable melee weapon.

**Comment by harald921** [comment] 2015-12-29 12:51
I am imagining one of these (http://stormprepare.com/images/floating_flashlight.JPG) flashlights when thinking about the heavy flashlight, however I assume that it isn't really what it is. Either way, it should be possible to at least get some basic components out of it. Not necessarily some super advanced stuff, but it just felt a bit unfinished how it is the only thing of its kind I've found that I cannot disassameble. Why not just the same yields as a normal flashlight, perhaps even a lens or more plastic?

**Comment by narc0tiq** [comment] 2015-12-29 14:44
How about if it drops flashlight components and a "heavy duty flashlight
body" that can be salvaged for some scrap metal, or used to recreate the
original flashlight? That's the best way I can imagine it, as the "reason"
we "can't" disassemble it is because of that tough body there.

**Comment by harald921** [comment] 2015-12-29 16:27
We can disassemble tanks and nuclear powered electronics devices, I don't think a heavy duty flashlight is going to be much trouble to actually disassemble.

**Comment by Shadefang** [comment] 2015-12-31 23:15
Given the description, and how many of the other recipes work, the overall form of a heavy duty flashlight (heavy duty tubular aluminium LED flashlight) essentially boils down to flashlight components in a pipe.

**Comment by mugling** [comment] 2016-01-02 22:22
>  take a section of pipe, stick a cap and a spring at the bottom, throw batteries into it, and screw a basic LED assembly onto the other end. It's waterproof, bludgeon-capable, and completely possibly to take apart and put back together in two minutes.

This is the type I had in mind when adding the item.

I was hoping to get some time to look at balancing the various light sources but have got delayed with other tasks.  I wanted to add the requirement to wear or wield some before usage (see #14151 and #14151) so this item was intended to be a bright light and passable melee weapon to balance the less powerful head torch which allowed you to keep your hands free.

> Uncraftable part is fine, but a dedicated survivor should be able to disassemble everything

Unless anyone wants to try another approach shall I PR a disassembly recipe yielding one `flashlight (off)`, one `pipe` and one `spring`?

**Comment by ValidAQ** [comment] 2016-01-02 22:31
Don't pipe and heavy duty flashlight differ in materials? As in, flashlight made from aluminum, pipe from steel?
Or is it not really important enough detail to be concerned with?

**Comment by mugling** [comment] 2016-01-02 22:44
> Don't pipe and heavy duty flashlight differ in materials?

Yes

> Or is it not really important enough detail to be concerned with?

No it's a good argument against allowing reassembly.

**Comment by ValidAQ** [comment] 2016-01-02 22:56
It looks more like a problem with accurately representing parts of the flashlight with already existing items.
Especially with pipe and spring having the weight of five flashlights combined.

**Comment by harald921** [comment] 2016-01-02 23:15
I fully agree with @ValidAQ. We don't need to do something super fancy, just add a basic recipe to the flashlight? We can change our eyes for cameras we found in some radioactive waste facility while overdosing on cocaine, why not just let us disassemble and reassemble heavy flashlights?

**Comment by Skidborg** [comment] 2016-01-03 06:19
> No, it is in fact a good argument against allowing reassembly.
Aluminum tongs are also crafted with steel. Maybe this just means it's time to add a proper aluminum crafting material.

**Comment by ValidAQ** [comment] 2016-01-03 08:03
Well, we already have aluminum ingots. They just aren't used anywhere except for crafting aluminum powder.

**Comment by Rivet-the-Zombie** [comment] 2016-01-03 10:25
Those tongs weren't originally aluminum either. I'm not sure when that was changed.

**Comment by harald921** [comment] 2016-01-03 22:24
Why are they made out of aluminum anyway? Wouldn't that just make them worthless for what they are currently used for? (Smithing)

**Comment by mugling** [comment] 2016-03-09 17:25
Was fixed in #15662

**Closed by mugling** 2016-03-09 17:25 UTC
