### ISSUE TITLE
Some kind of loading error.

### ISSUE THREAD

**Issue by TheGoldenStarOfVerity** [CleverRaven/Cataclysm-DDA#27779] opened 2019-01-22 17:15 UTC
**Describe the bug**  
An error occurs during the save loading process.

**To Reproduce**  
Honestly I'm not sure, Sorry.

**Expected behavior**  
No error.

**Screenshots**  
![the error](https://user-images.githubusercontent.com/37771504/51552122-8aa9e200-1e35-11e9-8991-f86ea09f6c9f.PNG)

**Versions and configuration(please complete the following information):**
 - OS:Windows 10
 - Game Version [0.C-36923-g1bb3b27]
 - Graphics version [Tiles]

Mods loaded -

Dark Days Ahead
Classes and Scenarios Mod
Filthy Clothing 
Manual Bionic Installation
StatsThroughSkills
StatsThoughSkills IV
Vehicle Additions Pack
Tanks and Other Vehicles
Folding parts pack
Boats
DinoMod 
Modular Turrets
Salvaged Robots
Bens GF recipes
Bootleg Walkers
Craft Ammo Mags & Belt Links 
Extended Realistic Guns
Craft Ammo Mags - Erg
Craftable Gun Pack
DeadLeaves' Fictional Guns
Icecoon's Arsenal
Makeshift Items Mod
Medieval and Historic Content
More Survival Tools 
Mythological Replicas
Packaging
Mining Mod
Mutant NPCs
Arcana and Magic Items
Necromancy
More Locations
Fuji's More Buildings
Oa's Additional Buildings Mod
Urban Development

**Comment by Night-Pryanik** [comment] 2019-01-22 17:24
Duplicate of #27730.

**Closed by Night-Pryanik** 2019-01-22 17:24 UTC
