### ISSUE TITLE
Hard lock in progressing Innawood electronic tech tree 2024-04-11-1603

### ISSUE THREAD

**Issue by crzywulf** [CleverRaven/Cataclysm-DDA#72989] opened 2024-04-13 01:35 UTC
### Describe the bug

There is a lock in the innawood tech tree in current experimental. In order to craft electronics, you need at least a soldering iron which is craftable, however, you cannot reload the soldering iron with dry batteries. Without at least a working soldering iron, you cannot build makeshift welding equipment. This does not enable you to progress further into the tech tree, even into building a battery array and wind turbine to charge said soldering iron. You'd need a portable soldering iron, which is impossible to craft and find in innawood.

### Attach save file

[Knife River-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14964812/Knife.River-trimmed.tar.gz)

### Steps to reproduce

1. Make an innawood character with electronics knowledge.
2. Find all the materials to craft soldering iron.
3. Find out that you cannot use dry batteries with soldering iron and instead need a charged clay battery which is impossible to make and charge because you need a charged soldering iron to make the clay battery and turbine to charge the soldering iron. It's a loop.
4. Locked from progressing further into tech tree because you need the portable soldering iron which accepts dry batteries, but impossible to find and craft in innawood.

### Expected behavior

I should be able to craft a soldering iron version that takes dry batteries to progress down the innawood tech tree.

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14964837/debug.log)

**Comment by RenechCDDA** [comment] 2024-04-14 06:23
Duplicate of #70179

**Closed by RenechCDDA** 2024-04-14 06:23 UTC
Labels: (S1 - Need confirmation)

**Comment by RenechCDDA** [comment] 2024-04-14 06:40
Also it looks like you can just place the basic battery.
