### ISSUE TITLE
Building something from build menu that includes a roof doesn't actually include a roof

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#78151] opened 2024-11-25 21:22 UTC
### Describe the bug

When I built a stage 3 wooden wall It's expected to be a complete wall with a singular roof tile, but that is not the case, I also built a standard floor which includes 
a roof tile above the tile and it doesn't come with a roof either.

I have built a cabin this exact same way and roof support for both wood walls and standard floor come with roof support.

### Attach save file

[New World-trimmed.tar.gz](https://github.com/user-attachments/files/17909077/New.World-trimmed.tar.gz)

### Steps to reproduce

1. debug in stuff to make wood wall (stage 3 variant) and standard floor
2. build them
3. they don't come with roof

### Expected behavior

to have roof support

### Screenshots

![bug1](https://github.com/user-attachments/assets/eeb6aae0-28a2-473e-80be-88fbb4dd78ea)
![bug2](https://github.com/user-attachments/assets/c0123adc-d422-44f1-922c-7f6ab4e06e73)

This cabin has stage 3 wood wall variant, standard floor, window and door, all do not give roof support.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: bbc0d00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Triffid, Fungus and Ant Remover [myf_monsters_removal],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

It's probably not just wood wall, window, standard floor, door that don't come with roof support at the moment, it's probably all that include roof support.

**Comment by NetSysFire** [comment] 2024-11-25 22:09
CC @PatrikLundell. I feel like that might be related to #77873.

**Comment by PatrikLundell** [comment] 2024-11-25 22:29
That is intended behavior (assuming roof SUPPORT isn't missing: in the game's logic it means a roof won't fall down if it can be constructed (and the collapse logic can cause it to collapse anyway, once something causes it to be invoked, such as the destruction of a nearby wall)).

It used to be that construction of walls etc. automagically resulted in the spawning of a roof above it. That magic code led to a number of weird behaviors, such as holes dug through floors automatically closing again the next time the area was loaded (and the same oddity when some monster was smashing walls at lower levels). It's also odd that the roof you make is tied to what's below it.

The walls SUPPORT a roof (assuming the walls are finished: half walls do not support roofs as they don't reach that high), but you now have to construct it separately, and that means getting up to the next level to allow you to build it. This can be done by building scaffolding and stairs (again, both the lower and the upper section), and probably also by building ramps (I haven't tried that).

It can be noted that the construction costs of various constructions were adjusted when the roofs were removed (which doesn't mean they are anywhere near perfect, but a lot of cases didn't account for any extra materials for the roofs at all).

The up side of this is that you can now select what kind of roof you want on your buildings.

It can also be noted the base camp construction DOES include roofs where they logically should be, but the time and materials are automatically adjusted to account for it (and the need for getting up to the roof level to build it is waived, as are other aspects of this abstracted construction).

**Closed** 2024-11-25 22:40 UTC
Labels: (S1 - Need confirmation)

**Comment by Myfharad** [comment] 2024-11-25 22:42
I built wood roof as well and no roof was placed on the z-level above
![Untitled2](https://github.com/user-attachments/assets/3ae5c3cd-ae59-4cc9-bf76-e512f9756a19)
the wood roof tile being the square with the shadow outline in the cabin

**Comment by NetSysFire** [comment] 2024-11-25 22:44
Yes and that is expected. You must build a roof for yourself as you have only built the wall. To get up there you need to build stairs or a ramp.

**Comment by Myfharad** [comment] 2024-11-25 22:47
![eeeeeeeeeee](https://github.com/user-attachments/assets/77c8caad-8129-44e1-affd-12a9d6eab190)
Tried it, but cant go up cause no roof support

**Comment by PatrikLundell** [comment] 2024-11-25 22:52
Yes, the logic for constructing a roof allows you to replace a roof with another one. This includes "replacing" the ground. It could be improved if the logic for construction allowed you to list all "terrain" you could build on, but that logic only works for decoration work.

Are you sure you actually build complete stairs, not only the bottom half? You need both to be able to get up.

I don't know what "wall variant 3" is, so I can't comment on that.

**Comment by NetSysFire** [comment] 2024-11-25 22:52
You built the stairs/ramp wrong. Please go an appropriate player support venue, they are described in the readme. Cluttering the feed with support questions is unfortunately not the way to go here as this already drags on.

**Comment by Myfharad** [comment] 2024-11-25 23:06
Okay so what I'm trying to say, before I had updated the game I built a cabin, now the cabin's completed walls had a platform to stand on.
![Cabin2](https://github.com/user-attachments/assets/fff2017b-6ef4-49fd-a93d-0fb422358bba)
This was the 6x6 cabin I built, when I completed the wall, on it's third stage (which is it's completed variant) It had a wooden platform directly above the completed wall, allowing me to stand on it.

This is what I mean when I say variant 3, it's the walls completed stage:
![Variant](https://github.com/user-attachments/assets/ab7cca9d-431b-4743-a115-f3d37bf57c23)

Now, I understand if maybe roofing was changed in a patch, but I don't see anything in the changelogs.

There are many different buildings in CDDA that do not have direct roof access, so now if we are speaking logically all of them should have a stairway up to build a roof on.

I built my original cabin with just a ladder, since the stage 3 completed wood wall had a wooden tile above it to stand on, and after an update I cannot do that anymore.

I do not mean to be cluttering the feed, but I had a contributor on the community discord say it's a bug, and was encouraged to report it. so that is why I came here.

**Comment by NetSysFire** [comment] 2024-11-25 23:12
Most other buildings irl (and thus also in the game) were built using cranes, scaffolding (also available in the construction menu) and similar advanced techniques with an entire crew of skilled construction workers. You are usually a lone survivor.

>but I don't see anything in the changelogs.

You are right, this should not have been omitted from the changelog. People tend to overuse "None" as the changelog description for their PRs.
