### ISSUE TITLE
Found flares have zero charges

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#42692] opened 2020-08-04 00:21 UTC
# Describe the bug
All the flares I find have zero out of 300 charges.

# Steps To Reproduce
1. Make a player using the Kitted Survivor profession
2. Disassemble the survival kit.
3. The flares are all duds.

# Expected behavior
The flares in the survival kit (and elsewhere) should not be duds.

# Screenshots

A screenshot showing the results of a freshly disassembled survival kit.
![image](https://user-images.githubusercontent.com/2125926/89239314-d27efd00-d5c6-11ea-800c-313826c373d1.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4796-gda25633 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I believe that this bug affects not just flares, but many other items that should have charges.

**Comment by wapcaplet** [comment] 2020-08-26 04:14
Confirmed in 0.E-5371-g2ea5e2e970 using the Kitted Survivor profession. Flares from the disassembled survival kit have 0/300 charges.

Curiously, flares spawned from the debug menu have full 300/300 charges.

**Comment by Inglonias** [comment] 2020-09-22 19:37
Still an issue as of build 11026

**Comment by Inglonias** [comment] 2020-09-22 20:46
The bug inexplicably started between build 10688 and 10689.

**Comment by Inglonias** [comment] 2020-09-22 20:53
The bug was in a commit before 7fcce2c but after c23b55c

**Comment by wapcaplet** [comment] 2020-09-22 21:21
Continuing a `git bisect` between those two commits, it appears that 1e7f5c922a is where it started going wrong, but that version will not compile for me.

**Comment by Inglonias** [comment] 2020-09-22 22:18
welp.

**Comment by LaVeyanFiend** [comment] 2020-09-27 02:10
With #44427 merged, this issue can now be narrowed down to "flares shot by the flaregun or obtained from disassembly are empty."

**Comment by Fris0uman** [comment] 2020-11-14 09:45
Funny thing: activating survival_kit that uses "use_action": [ "DISASSEMBLE" ] gives empty flares, but activating premium_survival_kit that uses "use_action": { "type": "unpack", "group": "premium_contents", "items_fit": true, "filthy_volume_threshold": "10 L" }, gives full flares 
Oh it's probably because the disassembly is bugged but not spawning items from an item group.

**Comment by Fris0uman** [comment] 2020-11-14 09:49
Adding `"FULL_MAGAZINE"` to the disassembly recipe of survival_kit does solve the issue. Is that the fix we want or should we migrate those kit to be box with stuff in them instead?

**Closed** 2020-11-15 08:09 UTC
Labels: (S2 - Confirmed), <Bug>, Spawn
