### ISSUE TITLE
[0.F stable] Shouldn't Armored Car use JP8?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#50252] opened 2021-07-27 08:47 UTC
### Describe the bug

I've encountered an Armored Car and noted that it uses Diesel as fuel. Given that military vehicles seem to have been converted to use JP8, shouldn't this vehicle be converted as well?

### Steps To Reproduce

1. Find an Armored Car
2. Note the fuel the engine is marked as using when examining the vehicle, and, if possible, the fuel present in the tank(s) as well as any spare fuel present (I've been able to see the first two, and they're both listed as diesel).

### Expected behavior

All military vehicles using JP8 consistently.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Obviously a very minor issue, which has very little effect on the game (slightly less JP8 available).

**Comment by ZhilkinSerg** [comment] 2021-07-27 13:25
Duplicate of #50008. Fix #50032 is already marked as `0.F Backport Candidate`.

**Comment by actual-nh** [comment] 2021-07-27 14:45
It's mounted with machine guns (m249), so it isn't a private armored car (cash-carrying). However, it may be meant as a SWAT vehicle. @Night-Pryanik, any idea?

**Comment by PatrikLundell** [comment] 2021-07-27 15:02
There is a separate SWAT vehicle (which doesn't have mounted weapons), and given the machine guns, it definitely looks like a military vehicle to me.

**Closed** 2021-08-02 08:49 UTC
Labels: <Bug>, Good First Issue, Vehicles, [JSON]
