### ISSUE TITLE
Shotguns spawned in world have generic names

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#49936] opened 2021-07-14 12:35 UTC
### Describe the bug

All shotguns have names like 7-round shotgun, instead of Remington 870 express, for instance

### Steps To Reproduce

1. Create default world and a character
2. Reveal map & Long teleport until you find gun spawn point or just open a debug item spawn menu and search for "shotgun"
3. Take note of an item name

### Expected behavior

Guns to have specific model name and description

### Screenshots

![image](https://user-images.githubusercontent.com/9906246/125622452-ed701f22-cde3-480e-8be8-ef04ecb84e1e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e021315 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [    Dark Days Ahead [dda]]

### Additional context

Probably this PR is the cause - https://github.com/CleverRaven/Cataclysm-DDA/pull/49732
Save - [Kipp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6816006/Kipp.zip)

**Comment by anothersimulacrum** [comment] 2021-07-14 14:30
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/49573

**Closed by anothersimulacrum** 2021-07-14 14:30 UTC
Labels: (S3 - Duplicate)
