### ISSUE TITLE
'E'at menu doesn't stay open on last item

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#38014] opened 2020-02-14 12:53 UTC
# Describe the bug
The feature introduced in #29148 it's not working for me anymore. I came back to playing the game after a few months so I can't pinpoint when it stopped working.

# Steps To Reproduce

1. Eat something.
2. Cursor position goes back to the top.

# Expected behavior

As described in #29148

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12235-g3a8c5fb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by jkraybill** [comment] 2020-02-14 13:35
This is probably a duplicate of #36884 -- the menu resets in multi-location scenarios, and possibly multi-page scenarios, but not all scenarios. Please try to replicate some of the scenarios in #36884 and provide some more detail on what you're seeing if it's different.

**Comment by Break-Off** [comment] 2020-02-14 13:56
I am not using any filtering, just scrolling to a bunch of items on a counter and pressing enter. When consuming items in my inventory it works as expected.

**Comment by jkraybill** [comment] 2020-02-14 22:10
@Break-Off when this occurs for you, are the items you can choose from in more than one location  (e.g on a counter and in your inventory), or in more than one state of edibility (e.g. some items not currently edible, and/or some items rotten)? A screenshot or greater description would help in reproducing and fixing this -- it doesn't happen all the time in the current build but I'm still trying to get it down to the most basic reproduction scenarios.

**Comment by Break-Off** [comment] 2020-02-15 03:14
Here's the gameplay situation. Consumables are 1 space NE of player in a refrigerator (when issue was opened they were on a counter). 

![image](https://user-images.githubusercontent.com/5843433/74580880-d7181080-4fa8-11ea-8829-6b2d4b8f47e7.png)

Here's the 'E'at menu at the same position. Consumables on the inventory are exclusively drugs and all favorited. Refrigerator consumables consist of a stack of perishable and non-perishable food. When consuming items from inventory last choice is saved, which does not happen when consuming items from the refrigerator (it resets to the top).

![image](https://user-images.githubusercontent.com/5843433/74580884-e8611d00-4fa8-11ea-85a4-4a28fe886b18.png)

**Comment by jkraybill** [comment] 2020-02-15 07:14
Yeah thanks for the details! This is helpful. Pretty sure this wouldn't reproduce in your scenario if you had no consumables in inventory. If you'd like to try that and report it would be appreciated but I think there's probably enough info now to confirm that this is the same bug documented in #36884 (whose title is now inaccurate but the body includes this type of scenario).

**Comment by Break-Off** [comment] 2020-02-15 11:42
You are right. With no consumables it's not reproducible and works as expected.

**Closed** 2020-02-26 16:47 UTC
