### ISSUE TITLE
Head torch disappearing on activation

### ISSUE THREAD

**Issue by Priapism** [CleverRaven/Cataclysm-DDA#15292] opened 2016-02-07 20:15 UTC
I turned on my head torch. I received the message about the head torch being on. The surrounding area isn't lit up, nor is the head torch anywhere to be found. It's not on my character, in the inventory, or on the ground. I wished for 2 more head torches and it happened again both times. I turned the game off and back on and tried again. Same results.

**Comment by mugling** [comment] 2016-02-07 20:22
Probable duplicate of #15283 fixed by #15290

**Comment by Priapism** [comment] 2016-02-07 20:30
I should mention I'm using the current build 4355.

**Comment by mugling** [comment] 2016-02-15 00:10
Needs closing?

**Closed** 2016-02-15 00:15 UTC
