### ISSUE TITLE
Shivering doesn't check blankets

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47784] opened 2021-02-28 00:37 UTC
# Describe the bug

There is a new system that makes you shiver too much to sleep if you're underdressed. It does not appear to be checking for blankets on the ground (or even possibly your bed) until after you fall asleep, so you can't fall asleep even if you have blankets. It also prevents you from falling asleep forever no matter how tired you get.

# Steps To Reproduce

1. Make a naked character
2. Put some blankets on the ground
3. Try to sleep on them in the cold
4. You should get a message about shivering preventing you from sleeping
5. You can wear the blankets to circumvent this but blankets don't cover your mouth so you can freeze to death in your sleep

# Expected behavior

The game should check for blankets/clothes on the ground before it checks for shivering. You probably ought to eventually be able to pass out regardless if you get too tired.

# Versions and configuration

OS: Windows
OS Version: 10.0 2004
Game Version: 0.E-9855-gfa9b27e [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment] 2021-02-28 00:41
May be related to #39827 making potentially fatal shivering interrupt sleep.

**Comment by anothersimulacrum** [comment] 2021-02-28 01:19
Duplicate of #47671

**Closed by anothersimulacrum** 2021-02-28 01:19 UTC
Labels: (S3 - Duplicate), Mechanics: Character / Player, Mechanics: Temperature
