### ISSUE TITLE
Make jumper cables attach to vehicles instead of ground.

### ISSUE THREAD

**Issue by Pakislav2** [CleverRaven/Cataclysm-DDA#22529] opened 2017-12-01 18:48 UTC
Game version: Build 6933 (no commits addressing this since afaik)

Operating system: Win 7.

Tiles or curses:

Mods active:

### Expected behavior

Player is 'on' the vehicle. The player attaches the jumper cable to the vehicle. The player drives the vehicle. The cable stays attached to the vehicle tile.

### Actual behavior

Player is 'on' the vehicle. Player attaches the jumper cable. Player drives away. The jumper cable breaks off after driving 3 tiles as if it was attached to the ground instead of the vehicle.

###

Main purpose is to allow for CBM battery recharging via jumper cables and appropriate CBM while driving around.

**Comment by Aivean** [comment] 2017-12-16 01:37
Duplicate of #17772

**Closed** 2018-11-02 02:59 UTC
Labels: <Enhancement / Feature>, Bionics, Vehicles
