### ISSUE TITLE
Pocket presets

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60073] opened 2022-08-11 06:24 UTC
### Is your feature request related to a problem? Please describe.

I feel there is a lot of micromanagement for pocket priority setting, and especially much if you change your clothes for too much

### Solution you would like.

The idea is simple: instead of lefting the player manually change each pocket individually, the player (or the developer) can make a pocket preset, that contain all information from picked pocket, and can copy-paste his values to different pockets
From the json side it may look like a new `type` with similar info, so we can make some presets for the most common cases - ammo, medicine, food, weapon, "backpack" etc.
Also a good idea for me is to make some "default preset", that can be applied to the character itself, and will overwrite the default "no blacklist, no whitelist, 0 priority" settings to player one. In theory this will allow user, for example, make the default pockets prioritize the ammo, mags and weapons (making your character a bit smartet, cause he store the mag in his pants or jacket instead of dropping it inside the "slow" backpack), and left all another loot to drop in your backpack.
And the last, the most debatable(and need to be discussed before) change is to make some clothes with different by-default presets - if you wear the sheath/holster/rifle case, the probability you want to store a knife/handgun/rifle is pretty high, and you don't really want to put your "computer for dummies" manual here

### Describe alternatives you have considered.

:shrug:

**Comment by jagoly** [comment] 2022-08-11 12:59
As someone who uses pocket settings extensively, I think being able to transfer setting between pockets would be fantastic.

I definitely don't think default settings for pockets is a good idea though. IMO that sounds like it'd just be more annoying than anything else. Not being able to pick up items despite having space for them (without being the one who intentionally created your own pocket settings) would just be frustrating. There's no way to "prioritise" items, only whitelist/blacklist them, and I think having priorities for individual items is far too much work.

As for having built in presets, I don't think that'd be particularly useful. Pockets aren't like stockpile zones, the list of items you want to explicitly have in certain pockets is usually pretty small and varies greatly by player and over time.

**Comment by ANickelN** [comment] 2022-08-11 15:57
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/59580

**Comment by GuardianDll** [comment] 2022-08-11 15:59
Glad I'm not the only person that think about it

**Comment by anothersimulacrum** [comment] 2023-03-09 06:58
Added in https://github.com/CleverRaven/Cataclysm-DDA/pull/63390

**Closed by anothersimulacrum** 2023-03-09 06:58 UTC
Labels: <Suggestion / Discussion>
