### ISSUE TITLE
Phantom images trail behind character when Grabbing and Pulling

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46042] opened 2020-12-14 05:15 UTC
# Describe the bug

When grabbing and pulling items, sometimes phantom images trail behind the character. They disappear if the character moves vertically.

# Steps To Reproduce

1. Find an entertainment center.
2. Grab it.
3. Pull it.

# Expected behavior

I expected to not see phantom images.

# Screenshots
![GhostEntertainment](https://user-images.githubusercontent.com/13796683/102042967-2c77a680-3da1-11eb-9a24-9d3f5259fba9.png)

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8128-gc363e33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

**Comment by Night-Pryanik** [comment] 2020-12-14 05:21
Duplicate of #45517.

**Closed by Night-Pryanik** 2020-12-14 05:21 UTC
