### ISSUE TITLE
NPC throw a ranged weapons

### ISSUE THREAD

**Issue by IvanGovnov** [CleverRaven/Cataclysm-DDA#51378] opened 2021-09-04 23:35 UTC
### Describe the bug

NPCs throw a loaded ranged weapon after a few shots, so they make it easy to
kill them even by unarmed player

### Steps To Reproduce

1.find hostile NPC with ranged weapon
2.come to the shooting distance
3.NPC fires a few shots and throws a weapon at you

### Expected behavior

NPC continues shooting his target untill it die or out of ammo

### Screenshots

![Uploading Screenshot_20210905-014022_Cataclysm DDA (experimental).jpg…]()
![Uploading Screenshot_20210905-014047_Cataclysm DDA (experimental).jpg…]()
![Uploading Screenshot_20210905-014113_Cataclysm DDA (experimental).jpg…]()

### Versions and configuration

android-x64-2021-09-04-2115

**Comment by fairyarmadillo** [comment] 2021-11-16 00:51
Friendly NPCs are also still doing this. I just watched one of mine throw their shoes at a zombie on the experimental from November 5th. I stopped it by giving them a melee weapon and telling them not to use ranged weapons anymore, but obviously that's not an option for hostile NPCs.

**Comment by Leland** [comment] 2022-01-24 01:53
Duplicate of #38609

**Closed by Leland** 2022-01-24 01:53 UTC
Labels: <Bug>, NPC / Factions
