### ISSUE TITLE
Vehicles are made out rubber

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#36272] opened 2019-12-19 19:56 UTC
# Describe the bug

Get in a car, any vehicle. Go full speed. Ram a Z. Observe one or both behavior:

Vehicle goes from max. speed to 0 in an instant

and/or

Vehicle's speed is reversed to the max.

# Expected behavior

Vehicular MANSLAUGTHER! Sure, maybe not on a bicycle, but on a 6 ton, Z-steamroller????

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10522-g86e5cc1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Anti-fungal tower [aft],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Nechronica Redux [Nechronica_Redux],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Advanced Gear [adv_gear],
    Advanced Technologies [advtech],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Animal Summoner Item [Summons_animals],
    Battletech [battletech],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Bootleg Walkers [Bootleg_Walkers],
    Broken Admin's Gel Walls [bsa_gel_wall],
    Broken Admin's Makeshift Items [bsam],
    CBM Equipment [CBM_Arms],
    Camping tools [camping_tools],
    Climate Defying Farming [climate_defying_farming],
    ClothRollmat [ClothMat],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Dried Fruits [dried_fruits],
    Dual Wield .22s [dual_wield_22],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Dumb Sabaton Memes Mod [Sabaton_memes],
    Expanded Archery [ExArch],
    Explosive agent preparation [Alchemic_Bomb_ALC],
    Fallout New England [fallout],
    Garden Pots [growable-pots],
    Generic Guns [generic_guns],
    Hybrid Crossbow [pistol_cross],
    Icecoon's Arsenal [ew_pack],
    Lighting Ammo [light_ammo],
    More Survival Tools [More_Survival_Tools],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift],
    MakeshiftCanteen [MSCanteen],
    Misc Gear [extgear],
    Modern Weapon Pack Expanded [modern_weapon],
    More Armors [More_Armors],
    More Survivor Notes [more_survive_notes],
    More Vehicles [mo_veh],
    Mythological Replicas [nw_pack],
    Pipe Revolver Rifles [pipe_revolver_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Pizza Delivery [pizza_delivery],
    Pora's Complilation [porawep],
    Power_Armor_Additions [Power_Armor_Additions],
    Pressure Weapons [pressure_weapon],
    RF food keeper [rf_food_keeper],
    Space Heater [space_heater],
    Survivor's Lost item [Survivors_Lost_item],
    The Cool Mod [cool_mod],
    The Vermilion Mod [VermilionMod],
    With Extra Mushrooms [with_extra_mushrooms],
    You're gonna get canned! [can_mod],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Modular Turrets [modular_turrets],
    More Insects [mo_insects],
    More Monsters [mo_monsters],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Secronom [secronom],
    Youkai Enemies [Youkai_Disco],
    CDDA Variety Pack [ks_variety_pack],
    Cataclysm++ [Cata++],
    Convenient Constructions [convenientconstructions],
    Crazy Cataclysm [crazy_cataclysm],
    Even More Mutations [even_more_mutations],
    Food Irradiator [food_irradiator],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    NPC Recruitment Options [recruitment_options],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Alternative Basement Layouts [basement_extension],
    Beta National Guard Camp, Aggregate's edit [national_guard_camp_edit],
    Caches [P_Caches],
    Dorf Life [Dorf_Life],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Randomized Mall [randomized_mall],
    Trailer Parks [trailerpark],
    Urban Development [Urban_Development],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Shrub it off [shrub_mod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Graphical Overmap [Graphical_Overmap],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Compatible Add Bandits [GOV_BANDITS],
    Compatible Jury-Rigged Robots [jury_rigged_robots],
    Compatible Nimian Manufacture Guns [M_NM_wpns],
    Crazy Pets! [crazypets],
    EXTENDED_BUILDINGS [ext],
    Food preservation via ionizing radiation [irradiate-food],
    Gunslinger of Eld [gunslingermod],
    Incinerator [incinerator],
    Mad Cyber Science [mad_cyber],
    MaddreMod [maddremod],
    Make a Lot of Items [Make_a_Lot_of_Items_Mod],
    Nimian Manufacture Guns [NM_wpns],
    Red's Odd Additions [Red's Odd Additions],
    Sarcophagi Access [sarcophagi_access],
    Shard's Extra Additions [shardsOtherStuff],
    Survivor crowbar [surv_crowbar],
    THRESHOLD [add_mutant],
    Tekitou Map [tekitoumap],
    Touyou [Touyou],
    Touhou [Touhou],
    Window Door Frame [windoor],
    Xeno's SAS4 weapons pack [Xeno's SAS4],
    Xtals [xtal],
    machine [machine],
    mori Mod [mori],
    Boats [boats],
    vorpal weapons [vorpal_weapons],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Engineering essentials [EngineeringEssentials],
    Fuji's Military Profession Pack [fuji_mpp],
    Gunslinger Mod [MkMaxxi's Gunslinger Mod],
    Manual Bionic Installation [manualbionicinstall],
    Military Professions Mod [More_Military],
    More Character Creation Choice [more_char_creation],
    Mutation Changes [Mutation_Changes],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Odds N. Ends [Odds_N_Ends],
    Road Warrior Mod [madmax],
    Safe Autodoc [safeautodoc],
    Shinigami [shinigamimod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tame Bugs [tamebugs],
    Vehicle Additions Additions [blaze_extension_M],
    Wild Living [WildLiving],
    Wintertime Classes [SD_Winterclothes],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp]
]

**Comment by I-am-Erk** [comment] 2019-12-19 20:20
You should install some more mods.

**Comment by Szara-ManOfHonor** [comment] 2019-12-19 20:34
Unfortunately a bug report with so many mods included is unlikely to be taken seriously. You should reproduce the issue without third party mods first.

**Comment by Amoebka** [comment] 2019-12-19 20:37
This does happen without any mods at all. It is easily reproducible, too.

**Comment by kevingranade** [comment] 2019-12-19 20:37
Fixed by #36266

**Closed** 2019-12-19 20:37 UTC

**Comment by Unrepentant-Atheist** [comment] 2019-12-19 21:05
> 
> 
> You should install some more mods.

You know some more ?

**Comment by I-am-Erk** [comment] 2019-12-19 21:07
Seriously though, if you're playing with this many mods we actually can't test your bug for reproducibility because we won't be able to open your save game.
