### ISSUE TITLE
Weapon mods in inventory disappear on save/load

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#41947] opened 2020-07-08 17:23 UTC
# Describe the bug
when you have a weapon mod (combat knives included) in your inventory, it will be gone when you load your save. Wielded mods, mods attached to weapons and mods on the ground seem to be fine, but combat knives in sheathes on the ground (e.g. from dead soldier zombies) also disappear.

# Steps To Reproduce
1. new world, spawn a weapon mod (and maybe a backpack to store it in)
2. save and quit to menu, then load the save
3. mod is gone

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3894-g4929649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
maybe related to #41084 but i couldn't reproduce attached mods disappearing

**Comment by wapcaplet** [comment] 2020-07-11 18:03
Possible duplicate of #42002

**Comment by wapcaplet** [comment] 2020-07-11 18:14
This is fixed by #41917 - these use cases tested OK in that PR branch:

- sheath with combat knife on the ground
- backpack with combat knife, RM42 fighting knife, and sword bayonet

All knives were preserved on save/load.

**Closed** 2020-07-12 23:52 UTC
Labels: <Bug>, Items: Gunmod / Toolmod
