### ISSUE TITLE
Unable to craft clean water from a wooden keg

### ISSUE THREAD

**Issue by Chryseus** [CleverRaven/Cataclysm-DDA#23138] opened 2018-03-06 16:00 UTC
I've noticed this in the last few commits, when trying to craft clean water with a keg of water as the only source nothing happens, I've tried recreate this problem in a clean world with no luck so I've included my world.

**Active mods**
- Defaults
- Extended realistic guns
- Icecoon's arsenal
- Makeshift items mod
- More survival tools
- More buildings
- Tall buildings
- Urban development
- Boats
- Folding parts pack
- Vehicle additions pack
- Tanks and other vehicles
- Prevent zombie revivication
- Stats through skills

**World**
[Morrisonville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1785649/Morrisonville.zip)

**Comment by Leland** [comment] 2018-03-06 16:05
Ah, yes. This is a long-standing bug. Duplicate of #19483

**Closed by Leland** 2018-03-06 16:05 UTC
