### ISSUE TITLE
All vehicles in view suddenly vanish

### ISSUE THREAD

**Issue by MoocowTG** [CleverRaven/Cataclysm-DDA#58615] opened 2022-06-22 07:20 UTC
### Describe the bug

For no reason that I can discern, all vehicles around me suddenly vanished whilst reading a book

### Steps to reproduce

1. Load attached save 
2. Walk inside luxury car above the police car to the north east
3. Craft a pipe cleaner
4. Kill the zombie that revives if he doesn't die to a mine
5. Read The Black Freighter twice in the car
6. All cars in view will dissapear

### Expected behavior

Cars don't typically dissapear

### Versions and configuration

Win10 Tiles, latest nightly on June 22, 2022

Using Aftershock

### Additional context

[Vinita.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8955284/Vinita.zip)

**Comment by mkrutov** [comment] 2022-06-22 08:02
https://github.com/CleverRaven/Cataclysm-DDA/pull/58546

dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/58285, see #58285 commemnts for workaround

**Closed** 2022-06-22 08:16 UTC
Labels: (S1 - Need confirmation)
