### ISSUE TITLE
Android version virtual keyboard problems

### ISSUE THREAD

**Issue by EhNuhc** [CleverRaven/Cataclysm-DDA#34746] opened 2019-10-14 15:29 UTC
# Describe the bug

When press back button to active virtual keyboard the third times,game exit to menu just like a crash happened.

# Steps To Reproduce

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

# Versions and configuration

 - OS: Android 9.0.0
 - Game Version: 0.D-8494-gc95073
 - Graphics version: Tiles
 - Mods loaded: None.

# Additional context

**Comment by ZhilkinSerg** [comment] 2019-10-14 15:37
Duplicate of #33781

**Closed by ZhilkinSerg** 2019-10-14 15:37 UTC
