### ISSUE TITLE
Sewing related items voids charges reloaded and unloaded from them

### ISSUE THREAD

**Issue by pepesito1122** [CleverRaven/Cataclysm-DDA#40246] opened 2020-05-06 07:51 UTC
# Describe the bug

Items I've used with the sewing quality has a nasty bug that completely removes thread put into them for repairing items. And with the Sewing Kits I spawn in with their stock 50 thread, it gives me a 'none' item, effectively voiding the charges pulled out of them.

# Steps To Reproduce

1. Spawn in items with sewing quality (Wooden Needle, Sewing Kit, Tailoring Kit, etc,) and thread.

[Reloading charges]
2a. Reload the sewing tool with thread.
3a. See that the value is left unchanged, totally destroys your thread.

[Unloading charges]
2b. Attempt unload the stock charges of a Sewing Kit/Tailor's Kit.
3b. Sewing tool does not return thread, instead gives a 'None' item that is absolutely nothing, voiding charges again. 

# Expected behavior

I'm not sure. It probably has something to do with nested inventory, but that's the first thing that comes to mind.

# Versions and configuration
 
- OS: Windows 10
- Game Version: 0.E-1811-gafd8407
- Graphics Version: Tiles
- Ingame Language: System Language
- Mods Loaded: ["dda", "no_npc_food"]

# Additional context

This is the log the game gave me with I tried to unload thread from a Tailor's Kit.

 DEBUG    : cannot determine reload cost as none is neither ammo or magazine

 FUNCTION : int player::item_reload_cost(const item&, const item&, int) const
 FILE     : src/player.cpp
 LINE     : 2894

**Comment by Reango** [comment] 2020-05-06 19:32
I've had the same issue in its entirety.

**Comment by ZhilkinSerg** [comment] 2020-05-07 16:58
Duplicate of #40125

**Closed by ZhilkinSerg** 2020-05-07 16:58 UTC
Labels: (S3 - Duplicate), <Bug>, Items: Magazines
