### ISSUE TITLE
You can duplicate solar briefcases

### ISSUE THREAD

**Issue by Gramba** [CleverRaven/Cataclysm-DDA#75209] opened 2024-07-24 13:07 UTC
### Describe the bug

If you have a solar briefcase, you can deploy it into an existent grid to get an error message. The briefcase deploys correctly however, but if you take it down you get both the briefcase and a deployed briefcase. You can then deploy the briefcase again to get infinite solar panels.

### Attach save file

[Kendleton-trimmed.tar.gz](https://github.com/user-attachments/files/16362472/Kendleton-trimmed.tar.gz)

### Steps to reproduce

1. Get a solar briefcase
2. Get a grid going
3. deploy briefcase into grid
4. Get error
5. Continue and then take down the deployed briefcase
6. You just got duplicates

### Expected behavior

I expected to have only one briefcase and to not duplicate them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-07-21-0801 ecea7b5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment] 2024-07-24 14:03
Looks like a duplicate of #75179.

**Comment by Alm999** [comment] 2024-07-25 13:17
More precisely it is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/73976

**Comment by SurFlurer** [comment] 2024-08-29 12:46
Fixed by  #75397

**Closed** 2024-09-01 08:46 UTC
Labels: (S1 - Need confirmation)
