### ISSUE TITLE
Cannot see weather when looking at sky

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#43030] opened 2020-08-19 04:23 UTC
# Describe the bug

Cannot see weather when looking at sky

# Steps To Reproduce

Look at sky

# Expected behavior

See Weather like was possible under old versions

# Screenshots

<img width="1920" alt="Annotation 2020-08-18 212124" src="https://user-images.githubusercontent.com/2822992/90591877-08aca700-e199-11ea-85e4-6418649b936c.png">

**Comment by ZhilkinSerg** [comment] 2020-08-19 07:17
Duplicate of #42050

**Closed by ZhilkinSerg** 2020-08-19 07:17 UTC
Labels: (S1 - Need confirmation), Info / User Interface, Mechanics: Weather
