### ISSUE TITLE
Can't reload misc repair kit

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#72603] opened 2024-03-25 00:57 UTC
### Describe the bug

If you debug in duct tape it works, but if you've got a cardboard roll of it, then it doesn't reload.

### Attach save file

n/a

### Steps to reproduce

get misc repair kit, unload, find duct tape (In roll), & try to reload

### Expected behavior

To reload even when in the roll

### Versions and configuration

Windows 11, Latest experimental

**Comment by oosyrag** [comment] 2024-03-25 00:59
Duplicate of #71090, thanks for your confirmation!

**Closed by oosyrag** 2024-03-25 00:59 UTC
Labels: (S1 - Need confirmation)

**Comment by PGR-14** [comment] 2024-03-25 11:26
Thank you!
