### ISSUE TITLE
Survivor utility belt loses tool quality when containing trench kinfe.

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#46149] opened 2020-12-19 16:08 UTC
# Describe the bug

Survivor utility belt loses tool quality when containing trench kinfe. (maybe other items trigger this bug too)

# Steps To Reproduce

1 Have survivor utility belt equipped, and have it contain a trench knife.
2 Observe that removing a mounted electric forge has unmet dependency of "bolt turning 2 or more"
3 Unload trench knife from survivor utility belt.
4 Mounted electric forge can now be removed.

# Expected behavior

Survivor utility belt keeps tool quality when containing item.

# Versions and configuration

E-8292-g00db780
Disable NPC Needs,
Bionic professions.

**Comment by wapcaplet** [comment] 2020-12-19 16:19
Thanks for reporting! Appears to be a duplicate of #40973

**Closed** 2020-12-19 16:19 UTC
Labels: (S3 - Duplicate)
