### ISSUE TITLE
Makefile does not match build options used in Jenkins

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14283] opened 2015-12-02 04:30 UTC
I've submitted PRs that compiled just fine for me then failed to compile for testing.

One such failure was due to `error: enumeration value 'FOO' not handled in switch [-Werror,-Wswitch]`. Another was due to trying to implicitly cast between `int` and `size_t`.

It seems like the compiler and options, including default options, being used on Jenkins aren't all explicitly set in the distributed Makefile.

It would be helpful if these were more in sync.

**Comment by vickio** [comment] 2015-12-02 06:02
Yeah, sign comparison errors causing Jenkins to fail have gotten me a couple times recently too.

**Comment by narc0tiq** [comment] 2015-12-02 06:04
Uh, here's the Jenkins build script: <http://dev.narc.ro/cataclysm/mainline-build.zsh>. The only thing it does is set the compiler and linker, and set `TILES=1`, `SOUND=1`, `RELEASE=1` as needed (the latter is always true for Jenkins builds -- I have an override available for when I use the same script on manual builds). You will note the only instance of `CXXFLAGS` fuckery is to force the `g++-4.7` for the Linux_x64 builds to include `-m64`. I should really be setting `NATIVE=linux64` there, but it didn't exist when I was making the build script.

I don't understand what you could possibly mean about the compiler being set in the Makefile. Every machine is different, so it's up to you to pick the right compiler for your build if the one normally found by `make` isn't right.

At a guess, you might be running into several interesting facts:
- clang is somewhat more sensitive about most things than gcc (though there have been occasios when the latter caught things the former doesn't).
- different compilers (or even the same compiler on different platforms) may have different default behaviours for things like what `int` means -- this is expected and codified in the C++ standard.
- building without `RELEASE=1` will omit `-Werror` from `CXXFLAGS`, meaning the warnings you get in compiling won't _stop_ the build (but you do still get them, modulo the previous two points; it's up to you to review and correct them).

**Comment by FunnyMan3595** [comment] 2015-12-02 06:19
All three of those issues are caused by `-Werror`, which `RELEASE=1` sets.  They will trigger warnings no matter what (because we set `-Wall` all the time), but with `-Werror`, they will break your build.  This is intentional, and the exact purpose of `-Werror`.

Without `RELEASE=1`, you're allowed to build a version with warnings, so that you can have a faster (write code -> run -> write more code) loop.  But you should always, always, always fix your warnings before submitting a pull request.  And that's not a C-DDA thing, you should do it for *any* project you submit code to.

Warnings are there to make it harder to shoot yourself in the foot.  Pay attention to them, and fix them, so that other people don't get distracted by irrelevant warnings.

**Comment by narc0tiq** [comment] 2015-12-02 06:23
Closing as invalid -- this is not a bug in the Cataclysm: DDA source code.

**Comment by vickio** [comment] 2015-12-02 06:26
I don't see any sign comparison warnings when compiling because the Makefile is explicitly setting `-Wno-sign-compare` when compiling with clang on OS X, which Jenkins does not do. Maybe this isn't a bug in CDDA, but it does require change in the Makefile to make it possible for developers to submit PRs that won't be failed by Jenkins.

**Comment by sparr** [comment] 2015-12-02 06:38
Thanks for the insight @vickio. That's definitely part of the problem. I suspect the other warnings being disabled with clang might also have tripped me up in the past.

Why are we explicitly disabling warnings in the Makefile that are not disabled during testing builds?

**Comment by vickio** [comment] 2015-12-02 06:39
Here's the line from the Makefile when compiling with `CLANG=1`:
`WARNINGS = -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-missing-braces -Wno-type-limits -Wno-narrowing`
But it looks like the Jenkins script is not setting `CLANG=1` even though it's using clang?

**Comment by FunnyMan3595** [comment] 2015-12-02 06:39
Looking at the code history, that looks like that's a case of copy/paste getting out of sync.  The release branch was originally given special handling in 2db2b4 because there was a lot of legacy code that threw warnings.  Six months later, the code had been fixed, so 72b08f finally removed the -Wno-* options from RELEASE_FLAGS, but neglected to remove them from the CLANG branch of the code.

**Comment by narc0tiq** [comment] 2015-12-02 08:07
I see! Thank you, that's a very good summary, and likely very correct with regards to the cause.

I'm reopening this, and will be taking a look at reorganizing the Makefile such that common things are common. For the short term, expect a fix resolving this specific desynchronization of CXXFLAGS between branches of the Makefile. Notable addition: the Code::Blocks project apparently also includes instructions to disable some warnings; what a horrible mess.

**Closed** 2015-12-02 09:13 UTC
Labels: Bug, Build
