### ISSUE TITLE
Metal Smoking Rack and Metal Butchering Rack require absurd amounts of Pipe Fittings

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#63136] opened 2023-01-16 21:30 UTC
### Describe the bug

Pipe fittings are not that common. No other recipe requires more than 4-6 pipe fittings, including the folding table.  Manufacturing the combined 54 pipe fittings for one of each would take more than 8 straight days of crafting.

### Steps to reproduce

Metal Smoking Rack recipe requires 30 sets of pipe fittings with no alternative
Metal Butcher Rack recipe requires 24 sets of pipe fittings with no alternative

### Expected behavior

These recipes should be reduced by a factor of 5-6, requiring 4-6 pipe fittings each to craft or an acceptable alternative should be added.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1105 (22H2)
- Game Version: 10bcab1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by NetSysFire** [comment] 2023-01-16 21:50
Actually a duplicate of #52624 but that one was closed as stale.

**Comment by flybye3o6** [comment] 2023-01-16 22:19
i was looking into this because the weight and volume of both racks are very off compared to the resources that go into making them, the pipes and pipe fittings will have to be reduced and the racks have more weight added to them 
i wasnt able to find reference so its kinda guess work

**Comment by Vaskritaya** [comment] 2023-01-16 22:34
the weight could be all over the place, due to being able to use either copper tubing or pipes which have drastically different weights. That being said, youd need to use a certain amount of pipes to make a functional frame regardless of material. 

It's a bit of a tricky situation, but either way the fittings requirement is insane and the whopping 15 pipes needed for a smoking rack are nearly 4 times the weight of the finished product all on their own!

**Comment by flybye3o6** [comment] 2023-01-16 23:15
the fittings say its a loose assortment of things, so dont know exactly how much that is but fair to say 1 unit of fittings can do more then 1 joint, it is 0.5kg so idk about 4 or more joints, idk what the nails and wire are for
if i can find a reference to a 15L smoking rack and how many shelves it uses i could tell you about how many 60cm pipes it would need, 4 for the vertical frame then about 2 per shelve if you cut them in half and in half again so they make C shape, or even in half again to make a smaller c, could make it 60cm high 30cm wide 4 shelves about 10 pipes and 10 fittings, would make it 17.5kg just from that but not all of it would be used, the volume can be reduced because it can be packed up into a flatpack
for the butchering rack it needs to be big and carry weight of a carcass, triangular prism shaped one seems to fit but would require more pipes about 15-18 from 12, to be collapsible it would ether be telescopic pipes or all the pipes come apart and packed into a bag like a tent kit
or it could be more like a frame that you hang a punching bag from

**Comment by Maleclypse** [comment] 2023-01-17 01:18
https://www.amazon.com/Smokehouse-Products-Chief-Replacement-Carton/dp/B001Y9R7SY/ref=asc_df_B001Y9R7SY/?tag=hyprod-20&linkCode=df0&hvadid=198072135009&hvpos=&hvnetw=g&hvrand=2001670089926920774&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9013478&hvtargid=pla-318465480173&psc=1  
So I think you are looking at building somethign similar to this plus the 5 or six racks that the meat rest on.

**Comment by Zourin2** [comment] 2023-01-17 22:36
Which requires zero fittings or pipes, just a welder and wire

**Comment by flybye3o6** [comment] 2023-01-17 23:14
i was considering reducing it down to 1 steel frame and have pipes and rebar as alt set to the similar material cost and have scrap metal as a byproduct
keep the wire and maybe like 2 pipe fittings
base the items weight and volume around the steel frame's stats
just to make it simple

**Comment by ADekema** [comment] 2023-01-21 23:53
Before pipe fittings where added you only needed ropes to craft the metal butchering and smoking rack. The rational was that you would simply tie all of the pipes together. 
The rediculous number of pipe fittings seems to have just been added into the recipy when pipe fittings where added without much thought.
Pipe fittings and ropes should probably be substitude parts as they seem to have the exact same function in the recipy.

**Comment by NetSysFire** [comment] 2023-01-22 00:03
One, out of scope though, problem is that disassembling the rack will yield either pipe fittings or rope. Does not depend on what you initially built it with.

**Comment by flybye3o6** [comment] 2023-01-22 00:58
disassemble is not set, and reverse craft dosent seem acceptable because their is metal cutting involved, looking into making a disassemble rn and dont know how to handle the ropes and other alt components

**Comment by flybye3o6** [comment] 2023-01-22 01:51
question i have is how do people see these items? are they hacky made with salvaged parts or more high quality purpose built made to last and be packed up for transport
because if its made as a "make what i can from what iv got" the wood versions have them beat in every way but deploy/pack up speeds
i think they should be more high quality and made to spawn in butcher shops, replace the wood ones there
(1min deploy vs 45mins build for butcher, 1sec deploy vs 1h 30mins build for smoker, 0sec packup time vs 10mins deconstruct)(deploy for metal smoker and packup for both needs to be set to 1min)(the wood butcher deconstruct needs fixing only gives back 6 long sticks, loses rope and sharp sticks/spikes)

**Comment by Zourin2** [comment] 2023-01-22 23:19
Minum effort and material that gets the job done. A bitcher rack can be
slapped together with enough structural pipe to hold weight, but I think
someone thought of hanging a moose using 36 4"  long pipe segments and not
4 36" long segments

**Comment by HeliusNine** [comment] 2023-01-28 22:30
Would the recipes still make sense if it just didn't use any pipe fittings?

I'm very tempted to just edit it that way in my own game.

**Comment by flybye3o6** [comment] 2023-01-28 23:08
if its minimum effort and slapped together then it doesn't need any pipe fittings at all
but i think it should lose its ability to be packed up because its held together with nails and wire/string

**Comment by HeliusNine** [comment] 2023-01-29 00:41
I think we should remember that a 800L fridge can be taken down and hauled around in this game, so unless the construction is much bigger than that, or is stuck into the ground and generally flimsy (like the wooden primitive smoker) there is no reason why you cannot just take down a metal smoker, assuming such a smoker is sturdily built.

Incidentally, it seems to me that the intent of the current recipe is suggesting a metal version of the primitive smoker, which means "basically the wooden version but metal." And while i cannot think of any reason why that cannot be done, the recipe also calls for the following tool qualities: anvil lv1, hammering lv3, metal sawing lv1, drilling lv1, and screw driving lv1. And if you have access to those tools you probably would just pick a better design instead.

I've tried to search for instances of people making their own DIY primitive smoker out of metal with no luck at all. From the cases i've seen so far people are fashioning smokers from metal would just do a offset smoker or upright drum/box smoker instead.

In fact maybe we should just replace this mystifying recipe with one of those instead. the recipe for an upright drum smoker would probably be the easiest to figure out. the 200L steel drum is already in the game. https://www.youtube.com/watch?v=aIden_pLMzg

The item's gameplay-mechanical role would be to reward the player that secured all these tools a larger volume smoker, so you don't have to mass build wooden smokers just to be able to smoke all the meat you've gotten from hunting in time before they all go stale or rotten.

**Comment by flybye3o6** [comment] 2023-01-29 05:21
i was thinking of replacing this recipe with a professional version and adding them to the butcher shops with the aim that they fold up and have greater smoking volume, and making metal versions of the wood ones in construction with far less tools and items needed and functions the same way, or could do a drum smoker instead for that

one thing i know about DIY smokers is that you shouldnt have the smoking meat directly over the fire and you should have the hot air run though a pipe/channel to cool off slightly so the toxic heavy gases separate or use an air filter

i was looking at seeing if using the primitive smokers could add toxins to the meat only small amounts but it would add up over time, with needing to build a better version on top of the base version to remove that effect, and with the professional metal version also wont build up toxins

**Comment by Maleclypse** [comment] 2023-05-16 05:07
Closed by #63890

**Closed by Maleclypse** 2023-05-16 05:07 UTC
Labels: Good First Issue, (S2 - Confirmed), [JSON], Fields / Furniture / Terrain / Traps
