### ISSUE TITLE
Disassembly of a felt patch gives wrong components

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#24639] opened 2018-08-05 02:30 UTC
Game version: 0.C-29661-g765578face-dirty

Operating system: Debian Linux 64 bit

Tiles or curses: Curses

Mods active:
 More Survival Tools
 Boats
 No Flaming Weapons
 No Survivor Armor
 Classes and Scenarios mod

### Expected behavior

Disassembly of a felt patch should yield 50 yarn.

### Actual behavior

Instead it yields 1 wool staple, 5 soap bars, and 3 clean water, the ingredients for crafting a felt patch.

### Steps to reproduce the behavior
Get a felt patch, disassemble it.
It doesn't seem to matter if I crafted the felt patch or got it by disassembling something.

**Comment by jeremyshannon** [comment] 2018-08-05 03:59
Checked with latest experimental, and a different save, and disassembly works correclty with wished up felt patches, but crafted ones give you the wrong materials. It seems the ones I had stored away in the other save were self crafted. (I was pretty sure I got them from cutting stuff up, but I guess not. Or maybe I just got one of the new ones mixed up)

**Comment by jeremyshannon** [comment] 2018-08-07 05:55
Yeah, in both cases it should be discarding the actual components used to craft the item and using the default ones, but it's not, which basically lets you just reverse entropy. (Lisa! In this deathmobile we obey the laws of thermodynamics!)

**Comment by BevapDin** [comment] 2018-11-25 09:36
Duplicate of #24012.

**Closed by BevapDin** 2018-11-25 09:36 UTC
Labels: (S2 - Confirmed), <Bug>, Crafting / Construction / Recipes, Items / Item Actions
