### ISSUE TITLE
Assigned inventory keys can change after holstering and drawing an item

### ISSUE THREAD

**Issue by mauledbybears** [CleverRaven/Cataclysm-DDA#14187] opened 2015-11-26 16:35 UTC
The key you assign to an item can change when you draw it from a holster/sheath. Sometimes it takes the key already assigned to another item.

**Comment by mugling** [comment] 2015-11-30 23:03
I'm struggling to reproduce this. Can you give me the sequence of steps to demonstrate the behavior?

**Comment by sick-trigger** [comment] 2015-12-21 23:21
it seems to alternate between remembering the assigned hotkey and assigning it a new letter. Pretty easy to reproduce:
1. Assign a small enough knife a custom/reserved hotkey letter
2. Put it into a sheath or boot
3. Take it out and check hotkey
4. Do it again and check hotkey

Happens with swords and scabbards too.
It worked correctly in 0.C

**Comment by Shadefang** [comment] 2015-12-22 17:49
I've had a similar issue (possibly intended?) where if you reassign a key currently assigned to something you have sheathed, the key gets assigned to the sword again.
1: assign key to sword
2: sheath sword
3: assign same key to another item
4: draw sword
5: key is now assigned to sword

**Comment by mugling** [comment] 2016-03-09 18:25
These are two separate issues, the one reported by @sick-trigger I still can't reproduce and the one reported by @Shadefang is addressed has the same cause as #15455

**Closed by mugling** 2016-03-09 18:25 UTC
