### ISSUE TITLE
No vision when Peeking

### ISSUE THREAD

**Issue by CayoDaves** [CleverRaven/Cataclysm-DDA#68134] opened 2023-09-14 14:22 UTC
### Describe the bug

when "peeking" to check around corners or up/down elevations, the player's vision does not update, effectively breaking the feature.

### Attach save file

[Ropesville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12609927/Ropesville-trimmed.tar.gz)

### Steps to reproduce

1.spawn into the world
2. find a wall to peek around or stairs to peek down/up where vision is blocked by the object in front of the player
3. press 'X' to peek and pick a direction that would remove the obstruction

### Expected behavior

When peeking around corners and up/down elevation, the player should be able to see in that direction.

### Screenshots

![peeking](https://github.com/CleverRaven/Cataclysm-DDA/assets/92031130/390da3bc-f9e4-46b6-a540-ca7813b1f7f8)
![not peeking](https://github.com/CleverRaven/Cataclysm-DDA/assets/92031130/53f3c534-0a44-4faa-993c-eb7de0573877)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: e8a6beb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

probably related to issue https://github.com/CleverRaven/Cataclysm-DDA/issues/68121 and could be caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/67997

**Comment by Optimism333** [comment] 2023-09-14 16:12
### Addendum ###
I have the same version and have also encountered this issue.

**Example (Looking around a corner vs peeking around the same corner):**
![Screenshot (59)](https://github.com/CleverRaven/Cataclysm-DDA/assets/81007356/b6a6effe-998c-4939-8d73-a4a6935c8d29)
- Can see a rock on the ground around the corner when looking

![Screenshot (58)](https://github.com/CleverRaven/Cataclysm-DDA/assets/81007356/775f3234-8efe-481b-b22e-a67277f527d3)
- Cannot see the same rock when peeking. Tiles do not update to reflect new sightline

**Example (Trying to peek down into an unexplored basement):**
![Screenshot (60)](https://github.com/CleverRaven/Cataclysm-DDA/assets/81007356/1a6ac565-04de-421e-9710-4f0df9c51cc6)
-Vision does not update to reveal any of the basement. Peeking character seems to turn into some kind of flame?

**Comment by kydsh** [comment] 2023-09-14 17:24
same here
![bug](https://github.com/CleverRaven/Cataclysm-DDA/assets/81353669/c5de2442-cc01-43bb-82ae-30343163433a)
![bug2](https://github.com/CleverRaven/Cataclysm-DDA/assets/81353669/328b9905-0872-4331-8d00-4ce6a4569f7c)

**Comment by Glovedude** [comment] 2023-09-14 17:51
I'm also having this issue. Let me add on some more examples.

Some other instances where I personally have seen vision break since the experimental update from 9/12 (by my reckoning). 

1: Driving.

- While driving the vision only updates every 5-10 tiles. During that time, the vision clips as if you are standing outside of the vehicle, and it provides the infrared vision (IR) marker on your character. I can't actually screenshot this as it occurs between turns.

2: Auto-move. 

- While traversing the subway tunnels via auto-move your character walks along the center of the tunnel. However, the camera locks to the bottom of the tunnel so you can barely even see your character. Again, can't screen cap.

3: Unintentional Clairvoyance.

- The vision updates allowing the character to partially see objects and terrain through walls.

**Comment by KHeket** [comment] 2023-09-14 19:06
It all caused by #67997 [Cataclysm-DDA experimental build 2023-09-13-0419](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-09-13-0419)
Because when I updated back to https://github.com/CleverRaven/Cataclysm-DDA/pull/68116 [Cataclysm-DDA experimental build 2023-09-13-0306](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-09-13-0306) - no problem occured
@Rewryte we need you help here

**Comment by Rewryte** [comment] 2023-09-14 20:12
> Some other instances where I personally have seen vision break since the experimental update from 9/12 (by my reckoning).

Unintentional clairvoyance is fixed in the same PR.  Will look into driving / auto-move tomorrow.

**Comment by Headjack** [comment] 2023-09-23 19:11
Confirming this, it does not have vision when peeking with X or during the new 'peek down' from an elevated z level

**Closed** 2023-09-26 02:23 UTC
Labels: (S1 - Need confirmation)
