### ISSUE TITLE
Adjustment to vehicle cameras and turrets blocked by roofs

### ISSUE THREAD

**Issue by CptBrogan** [CleverRaven/Cataclysm-DDA#13354] opened 2015-08-20 15:46 UTC
In regards to camera/turret LoS/range, could on roof mounting be adjusted to allow close tile blocking but distant viewable? Maybe two tiles blocked for every one vehicle roof tile away from edge? For example, if a camera is mounted on the center of a completely roofed three by three tile vehicle, you'd have visibility starting at a 9x9. 
I'm thinking this also might synchronize well with dynamics of multi z buildings if the reality bubble stays active on 0 and you're up a level shooting down from behind the window frame or whatnot.

**Comment by kevingranade** [comment] 2015-08-20 16:52
This might be possible, but oh boy is it going to be involved.
Terrain, items, fields and monsters will need a height property.
When generating the player's field of view and calculating monster LoS,
we'll decide where the player or monster's vision is originating, and check
for both horizontal and vertical blockage of sight, fairly simple for
creatures, but for the player it means making the already very expensive
and complicated shadow casting function truly 3D and have it iterate
vertically as well as horizontally.  I'm not actually sure if this is
feasible.

**Comment by CptBrogan** [comment] 2015-08-21 08:19
Good reply. I totally get you on the whole picture deal with z lvls, and over complicated it with that second paragraph. I just meant simple and now. My thought on just those two items was until after the real cataclysm (when all these mechanics are worked through) just giving them LoS minus 2 tiles per distance from edge would simulate their height and perspective well without changing any other dynamics.

**Comment by Coolthulhu** [comment] 2015-08-21 08:58
I think we could get it mostly for free when (if?) 3D shadowcasting vision is in.
Then we could pretend the camera is on the tile above vehicle when it would be safe to do so (no floors). Alternatively, the ray casting function would get a different offset/bresenham/etc.

> just giving them LoS minus 2 tiles per distance from edge

It's not half as simple as it sounds. For one, current system doesn't understand "non-monotonous" vision. You either see a line up to point `p`, or you see it only up to a closer point `p0`. So having it skip a bunch of tiles would require storing extra data.
This data would depend on direction of each ray and a big deal of it would have to be cached (too expensive to calculate per-tile). This cache would be the size of current sight cache.
And all of this would have to be scrapped when (if) 3D vision gets in.

**Comment by CptBrogan** [comment] 2015-08-22 03:21
Gotcha. I didn't think a second vision set on one entity would be as resource intensive as all that. Bummer, thx for the explanation anyways.

**Comment by kevingranade** [comment] 2015-08-27 16:05
Closing due to the approach being unworkable.
We might get the feature requested as part of a larger rework, but we'll do that whether the issue is open or not.

**Closed by kevingranade** 2015-08-27 16:05 UTC
Labels: Long-term, Mechanics Change, Suggestion (Discuss)
