### ISSUE TITLE
Drinking from Water Pump Causes Error

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#76527] opened 2024-09-18 17:45 UTC
### Describe the bug

Drinking from a water pump causes the following error:

 DEBUG    : Item location/name to be consumed should not be null.

 FUNCTION : finish
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\activity_actor.cpp
 LINE     : 3247
 VERSION  : abbb6ce

Issue doesn't exist when filling a container and drinking from it.

### Attach save file

[New Magic-trimmed.tar.gz](https://github.com/user-attachments/files/17048176/New.Magic-trimmed.tar.gz)

### Steps to reproduce

1. Approach and interact with water pump
2. Select (e) Consume It
3. Error

### Expected behavior

Water from the hose

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: abbb6ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by CoroNaut** [comment] 2024-09-18 18:07
Can confirm it gives error

[debug.zip](https://github.com/user-attachments/files/17048426/debug.zip)
[TESTINGFOUR-trimmed.tar.gz](https://github.com/user-attachments/files/17048410/TESTINGFOUR-trimmed.tar.gz)

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-18-0513 7b773c1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment] 2024-09-18 18:29
Duplicate of #76425

**Closed by RenechCDDA** 2024-09-18 18:29 UTC
Labels: (S1 - Need confirmation)
