### ISSUE TITLE
Error message interrupts gameplay even after choosing to ignore

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#65328] opened 2023-04-27 01:01 UTC
### Describe the bug

While trying to craft, wait or do anything that causes time to pass in my camp, I am constantly interrupted by an error message. If I choose to ignore this message with the I button the message comes back repeatedly regardless of this choice.

### Attach save file

[Cottonwood Point-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11338504/Cottonwood.Point-trimmed.tar.gz)

### Steps to reproduce

1. Perform wait action for 30 minutes
2. Get error message, press I to ignore
3. Wait for 30 minutes again
4. Error message comes back even when opting to ignore

### Expected behavior

I expect this error message not to pop up again after I choose to ignore future prompts.

### Screenshots

![image](https://user-images.githubusercontent.com/65632694/234728246-2a3a7927-f709-4f43-8198-e7fd3c8ef811.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 01203da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11338452/debug.log)

**Comment by ynemo** [comment] 2023-04-27 02:51
I have this error on last releases. 
2023-04-24-1251 works fine.

**Comment by RenechCDDA** [comment] 2023-04-27 08:06
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/65313

**Closed by RenechCDDA** 2023-04-27 08:06 UTC
Labels: (S1 - Need confirmation)
