### ISSUE TITLE
Bullet casing map extra can spawn in the air

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#62611] opened 2022-12-07 03:25 UTC
### Describe the bug

Bullet casings can spawn in the air, and they don't fall down.

### Steps to reproduce

This is a map generation issue, reproduction is likely based on chance only. It maybe(?) can only occur on tiles that are not "open air".

### Expected behavior

Casings will fall to the ground/don't spawn in the air

### Screenshots

![airbullets](https://user-images.githubusercontent.com/32048635/206080494-7585f336-6fc1-4825-9077-4d051ec69fd5.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: c58154a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Night-Pryanik** [comment] 2022-12-07 12:48
Duplicate of #56682.

**Closed by Night-Pryanik** 2022-12-07 12:48 UTC
Labels: (S2 - Confirmed)
