### ISSUE TITLE
Can not wear a power armor helmet

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#41330] opened 2020-06-15 17:09 UTC
# Describe the bug

Even if you have power armor on the game still does not allow you to wear a power armor helmet.

# Steps To Reproduce

1. Wish for a combat exoskeleton
2. Wish for an environmental combat helmet
2. Take everything off
2. Try wearing the helmet
3. This fails with the message "You can only wear power armor components with power armor"
4. Put on the combat exoskeleton
2. Try wearing the helmet
5. This fails with the message "can't wear power armor over other gear"

# Expected behavior

It should be possible to put on the helmet.

# Screenshots

none

# Versions and configuration

    OS: Linux
        OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo;
    Game Version: 0.E-3208-gbd9759e [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
    ]

# Additional context

none

**Comment by anothersimulacrum** [comment] 2020-06-15 17:39
Duplicate of #41103

**Closed by anothersimulacrum** 2020-06-15 17:39 UTC
