### ISSUE TITLE
Crash Upon Reloading Thread-tool

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#64691] opened 2023-03-30 10:28 UTC
### Describe the bug

Trying to reload any tool that takes thread where there are multiple options for types of thread causes the game to crash.

### Attach save file

[Cascade-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11110406/Cascade-trimmed.tar.gz)

### Steps to reproduce

1. Generate any needle tool, such as wooden/bone needle.
2. Generate multiple types of thread, such as thread and plant fiber.
3. Attempt to reload the tool with thread where multiple types of thread are directly accessible.
4. Game crashes upon reload attempt.

### Expected behavior

I expected to be able to be presented with a choice for which type of thread to reload the tool with.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: dd52426 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[Crash and Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11110459/Crash.and.Debug.zip)

**Comment by andrei8l** [comment] 2023-03-30 10:29
Duplicate of #64552

**Closed** 2023-03-30 12:45 UTC
Labels: (S3 - Duplicate)
