### ISSUE TITLE
The games stops running. It´s in a city/village. I asume it is because of a minefield.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24861] opened 2018-08-16 00:03 UTC
**Describe the bug**  
At the first crashes it came back after some time. Now after maybe 20 crashes it does not come back. At first it occured when zombies exploded a mine in a minefield. Now I  cant tell, because I dont have sound.

**To Reproduce**  
1. Walk to the East-South-East (ESE) or ENE from the saved position to fight and explore. 

**Versions and configuration(please complete the following information):**
 - OS: WIN 7 64bit
 - Game Version [from the main menu, e.g. 0.C-30488-ge0c26b1
 - Graphics version [chesthole]
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2292041/save.zip)

**Comment by Inglonias** [comment] 2018-08-16 12:09
This looks to be a duplicate of #24748 . If it is, it's a known issue, but it's nice to have another test case.

**Comment by Androwski3000** [comment] 2018-08-18 17:55
I had the next occurance of a freeze. The last log message was: The zombie child misses the riot control bot.
20 seconds long nothing happened. I went to the kitchen for a snack. After some minutes when I returned, the game was working again.

**Comment by KurzedMetal** [comment] 2018-08-25 14:17
I've had landmines freeze my game too.

If there's any particular reason for this to happen, I don't know it. 

But most of the time I hear a landmine, the game takes a high amount of time to process the explosion (windows reports "has stopped running" and wants to kill the process).

**Closed** 2018-08-28 01:51 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
