### ISSUE TITLE
More people with merge rights

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19291] opened 2016-11-15 00:51 UTC
We usually have more PRs than reviews. In those cases, I usually pick some of the most important ones and test only those, or mass-merge the minor ones (which means lower review quality).

Would be good if we had more people to review and merge things, especially the minor PRs that only need confirmation that they work and the code quality is good.

We have some great active contributors, but I don't want to "name volunteers", because in the end mergetesting is a pretty boring job.

**Comment by mugling** [comment] 2016-11-15 01:10
> because in the end mergetesting is a pretty boring job.

Before we get a deluge of requests what is needed is more developers writing and reviewing C++. Familiarity with the codebase is a prerequisite.

> We have some great active contributors, but I don't want to "name volunteers"

The above is a sufficiently narrow set that it's fairly apparent who is being named here.

> or mass-merge the minor ones (which means lower review quality).

We need to define a better approach to testing and releasing code. The current model is actively hostile to small bugfixes.

**Comment by DangerNoodle** [comment] 2016-11-15 06:14
I am uncertain who would be available for such things at present. It might be desirable if any new mergetesters were to primarily focus on mod maintenance and JSON-based alterations, allowing the remaining more experienced developers to prioritize source alterations. This would also reduce pressure to auto-cannibalize mod maintenance if new mergers were assigned to the easier to test, abundant pull requests of that sort.

**Comment by Cyrano7** [comment] 2016-11-15 10:00
@Coolthulhu I know you said you didn't what to name volunteers but this might not go anywhere if you don't at least name some candidates.

@DangerNoodle Even if we had someone who focused on json based changes I still think we should be dropping some of the mod content that is shipped with the game. Some of these mods are already supported outside this repository. Some have been completely abandoned like more survival tools which has had most of its worthy content mainlined. How many games do you know that ship with unofficial content?

Even out of the people who have a high number of commits that are still active there are not many who I would trust with merge rights.

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-15 10:19
>How many games do you know that ship with unofficial content?

Is uniqueness a vice?

>Even out of the people who have a high number of commits that are still active there are not many who I would trust with merge rights.

Due to competence or malice?

**Comment by Cyrano7** [comment] 2016-11-15 10:42
Mostly competence but also we are trusting someone with the lore and direction of the game. Once something is in it is had to take it out. People freak out even if its and broken or half baked mechanic or piece of content.

**Comment by Cyrano7** [comment] 2016-11-15 10:57
There are not many people who have a decent number of commits with a high percentage of merged out of total closed PRs, have been active for a while, and have a good amount of source commits like @codemime for example.

**Comment by pisskop** [comment] 2016-11-15 12:05
dont soft-talk

name names or trust the devs to figure themselves out.  there is a reason no names were spoken here

**Comment by pisskop** [comment] 2016-11-15 12:06
ise thinkse theyse cannotse understandse mese nowse. : roll:

**Comment by illi-kun** [comment] 2016-11-15 12:31
@codemime and @remyroy are good candidates for this, IMO, of the will to do that, of course.

**Comment by codemime** [comment] 2016-11-15 12:35
> because in the end mergetesting is a pretty boring job.

> @codemime and @remyroy are good candidates for this, IMO, of the will to do that, of course.

Like I said, I'd be glad to help.

**Comment by DangerNoodle** [comment] 2016-11-15 17:00
> Even if we had someone who focused on json based changes I still think we should be dropping some of the mod content that is shipped with the game. Some of these mods are already supported outside this repository. Some have been completely abandoned like more survival tools which has had most of its worthy content mainlined. How many games do you know that ship with unofficial content?

I would still consider these mods a major part of the game. They should either be mainlined or retained. Note that I have been adding intermittent maintenance for some of the abandoned mods, such as More Survival Tools, due to the mod author no longer being available.

The unofficial content is unofficial because they do not fit the vision of how mainline gameplay or lore should be. Think mutators, not mods.

**Comment by remyroy** [comment] 2016-11-15 17:14
I appreciate your consideration for adding more people with merge rights. I do not currently have the time to get more involved with the project. If that ever changes and I see the need to get that right, I will ask for it.

**Comment by Coolthulhu** [comment] 2016-11-15 17:48
> I know you said you didn't what to name volunteers but this might not go anywhere if you don't at least name some candidates.

* @codemime is around most of the time and meets all the requirements
* @sethsimon has been with us for half a year and has a good track record

There are some people who would be good candidates if they had the time and wanted to stay with us for a while:
* @BrettDong is pretty new, but has a lot of commits already
* @mutability is also rather new, but has the skills and good standards of code

Then people who might be good, but I'm not sure about setup and skill in C++ (working building environment - at least for console builds - is a must, as is properly set up local git repo):
* @Cyrano7 has been with us for a long time without too much absence and has a lot of commits. I don't recall any C++ PRs, though.
* @DangerNoodle Relatively new, but has a lot of commits. All json, I think. I recall some badly tested commits here and there. I don't recall any C++.
* @BorkBorkGoesTheCode has a lot of json commits. As above: I think I recall some errors and don't recall any C++.
* @pisskop lots of contributions, is around a lot. I recall one or two C++ PRs. Problems with testing.

I don't have good memory for nicknames so I might have missed some good candidate.

I'm not listing old timers who aren't around much or look like they don't have much time. Most of the testing is more about consistency than skill.
People who don't test their PRs can still be good testers if they don't apply the same standards to others. My early PRs were often quite bugged and yet when testing big PRs I usually have a long list of errors and complaints.

Who does have the rights to add people to CleverRaven? We'll probably need @kevingranade or @GlyphGryph here.

**Comment by pisskop** [comment] 2016-11-15 18:13
I would have recommended cyrano, seth, or mutability myself

**Comment by DangerNoodle** [comment] 2016-11-15 18:41
> @DangerNoodle Relatively new, but has a lot of commits. All json, I think. I recall some badly tested commits here and there. I don't recall any C++.

My apologies, as I do not have experience with C++. More used to JSON work.

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-15 18:50
Same here. I have a Code::Blocks partially set up, but I don't know if it works.

**Comment by DangerNoodle** [comment] 2016-11-15 19:02
I have been able to merge with Code::Blocks, but it is extremely time-consuming, and only permits tiles-only test builds in my configuration.

Relying on a single compiler might also cause problems if an issue causes compiler-specific failures, but I have no experience with successfully setting up any other compiler.

**Comment by Cyrano7** [comment] 2016-11-15 20:03
I'm willing to help out. I can compile and have a basic knowledge of C++ (I took some classes at my local CC a few years ago). It's defiantly been a long time since my last source commit though and I'm still stumped by a large portion of the codebase. I'm defiantly comfortable using git now, It was a little rocky at first of course. I would mostly be limited to testing on the weekend with the occasional weekday merge because of work.
So if I was helping out I'd probably stick with JSON based changes or the most basic of compiled PRs.

**Comment by mugling** [comment] 2016-11-15 22:59
We are on course to exceed half a million lines of JSON in the near future (currently 400k+ lines). The priority is to accelerate the rate of development (in particular bugfixes) and not further speed the addition of content.

As a result we need developers that understand C++ and git as opposed to JSON. That does narrow the list down a lot - probably to @codemime and @sethsimon initially and then potentially @mutability in the near future. All have shown reasonable understanding of sane software development practices, in particular documentation and unit tests.

The other obvious candidate is @remyroy who already has a significant role in the projects infrastructure and would be an obvious choice as we proceed to factor mods out into third-party repos.

JSON PR's aren't currently a problem in my opinion. If others disagree then the next obvious candidate is @Cyrano7 who has a good understanding of sane JSON syntax and whose presence and contributions haven't resulted in any unnecessary drama. More recent contributors often struggle with syntax errors or produce unmergeable requests - whilst their contributions are welcomed they would not be suitably equipped for merge testing at this time,

**Comment by DangerNoodle** [comment] 2016-11-15 23:14
Understood. Even if I had greater experience, I am afraid I might not be able to participate regularly due to various real-life distractions as of late.

**Comment by mutability** [comment] 2016-11-15 23:18
I already have a few too many projects on the boil unfortunately, I don't think I could find the extra spare time.

**Comment by pisskop** [comment] 2016-11-15 23:22
Well there we go.  We seem to have a consensus.  Can this one line of C++ of my PR be merged now?  Its kind of holding up my own work

**Comment by mugling** [comment] 2016-11-15 23:32
> Can this one line of C++ of my PR be merged now?

Which PR?

**Comment by pisskop** [comment] 2016-11-15 23:51
adding swamps #19289

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-15 23:51
@mugling  pisskp refers to his #19289

**Comment by BrettDong** [comment] 2016-11-16 13:49
Thanks for recommendation. I have the time, I love this game, and I wish to help the development!

**Comment by sethsimon** [comment] 2016-11-18 00:03
I'd be happy to contribute. Even without write privileges, I can help with reviews, as codemime has done.

Also, perhaps testing PRs could be mentioned in `CONTRIBUTING.md`. For example, mnacamura helped me out by testing #19218 and finding a bug that I missed. If more people test a PR, fewer bugs will slip through the cracks and it lightens other testers' workloads.

**Comment by Cyrano7** [comment] 2016-11-18 09:39
Well @codemime and @sethsimon have both said they have the time. @remyroy and @mutability have said they are currently too busy. The only active dev we have not heard from is @Rivet-the-Zombie .

**Comment by Rivet-the-Zombie** [comment] 2016-11-18 23:20
Many hands make light work. I'd love to have some more folks helping to merge stuff!

**Comment by Chezzo** [comment] 2016-11-21 08:52
@DanmakuDan's repository is like a library of Cataclysm DDA through the ages, because he has been with us for that long. He does C++, he does tiles, he compiles, he is on the IRC, and he is a great guy.

**Comment by BorkBorkGoesTheCode** [comment] 2016-11-21 17:37
Could I get Wiki edit rights?

**Comment by mugling** [comment] 2016-11-21 19:53
> Could I get Wiki edit rights?

It cannot be set separately to merge rights

> Well @codemime and @sethsimon have both said they have the time. @remyroy and @mutability have said they are currently too busy

The above appears a consensus amongst developers having posted so far

**Comment by remyroy** [comment] 2016-11-21 20:12
@BorkBorkGoesTheCode Everyone has wiki edit rights. That's mostly how wikis work. All you need to do is create an account first. We have a special role for trusted wiki editors that removes the CAPTCHA for them. I try to see which users are the most active and I give them this role when I notice their implication on the wiki. If you believe you need more rights on the wiki, let me know.

**Comment by mugling** [comment] 2016-11-21 20:14
@remyroy I suspect the GH wiki is being referred to?

**Comment by remyroy** [comment] 2016-11-21 20:15
I was talking about the game wiki on http://www.wiki.cataclysmdda.com/index.php?title=Main_Page . My bad.

**Comment by chaosvolt** [comment] 2016-11-25 06:03
There's a problem with handling all these PRs though, and why there's the dev crisis that provoked this idea to begin with.

It's currently in a cycle of problems. Lack of manpower means you can barely focus on fixing problems, let alone ensuring new ones don't develop. Which leads to issues exploding with each merge. Which strains the available contributors and developers further, and back to square one.

Part of is lack of people to do work, but even that might not be enough to correct things at this point, as a lot of causes are likely behind development reaching this point.

**Comment by mutability** [comment] 2016-11-25 12:48
I know I am "part of the problem" here (in that I'm adding to the number of PRs but not helping merge them) but it is quite frustrating to do the work to get a PR to finished state and then have.. nothing happen, sometimes for weeks. I don't have a particularly good solution to that. If the problem is that it's timeconsuming to do the final merge decision, so it doesn't get done, then I think the merge step needs to be less about review and more of just a final gatekeeping step so that terrible stuff doesn't end up in the code. If a PR looks basically sensible and has had some review (by whoever), merge it! If it breaks stuff terribly, it can be reverted.

**Comment by Coolthulhu** [comment] 2016-11-25 13:05
> If a PR looks basically sensible and has had some review (by whoever), merge it! If it breaks stuff terribly, it can be reverted.

The problem with merge and revert is that we don't have regular stable versions out. Or even pseudo-stable versions regularly released with no verification of stability.
This results in highly pathological situations of players having to ask "is version x stable?".

And without enough testers, even heavily broken versions stay that way for a longer while, because there's a rather heavy bystander effects going on with the bug reporting, meaning that only the particularly annoying, recurrent bugs are likely to be reported.

Then there's the issue of reverting big PRs causing conflicts with all work in progress targeting affected code.

So I'd rather not rush it and instead insist on more people helping with testing.

Can we get @kevingranade or @GlyphGryph here to add @codemime and @sethsimon to @CleverRaven or at least to comment on the whole deal?

**Comment by patternoia** [comment] 2016-11-25 14:10
One more option to speed up merge testing might be to extend our Jently bot to produce binaries available for everyone for quick download and test, since I doubt that a majority of our testing community having a build environment set up.
Say it should be only Windows and only Tiles. Though this is a subject to debate, I picked this as most downloaded version.

**Comment by chaosvolt** [comment] 2016-11-25 17:56
More mergers might help, yes. But I'm uncertain if it'll fix the problem. There are a lot of general practices that are responsible for generating unnecessary work, and more mergers only

Take the recent idea of booting official mods to their own repos, maintained by mod authors. @mugling advocated this idea because mod maintenance is yet another thing that has to be juggled alongside fixing bugs. I'm not the only one that's said it basically amounts to developer laziness, but I also know the reasoning behind it, lack of manpower.

The problem is this increases the TOTAL amount of work involved, and only reduces the amount of work the devs have to put up with. You get desync between the game version (if present) and the new official version, further hinders efficient reporting of issues, and generates complaints that further bog down actually getting to real, higher-priority issues.

While this is a cross-repo problem (and can therefore be excused with the "someone else's problem" excuse), it remains an example of a potentially hazardous development attitude: if it creates more work for everyone while reducing the amount of work for the developers, it is not an efficient solution.

**Comment by pisskop** [comment] 2016-11-25 18:46
mod authors shy away because if the open hostility of using git

**Comment by illi-kun** [comment] 2016-11-25 18:48
@chaosvolt you are not person who can make any decisions about project flow. I've deleted your comment. If you want to do some thing with cdda - works on your mod.

**Comment by DangerNoodle** [comment] 2016-11-25 18:53
What did they say?

**Comment by Zireael07** [comment] 2016-11-25 19:04
He basically said that the recent change re: mod support wasn't going to ease the burden on the merge devs.

**Comment by DangerNoodle** [comment] 2016-11-25 19:12
Depending on how they meant that, that seems sensible. It is off-topic though.

**Comment by chaosvolt** [comment] 2016-11-25 19:14
The mod support remark was used as an example of a problematic approach. And yes, off-topic, but this issue does not address the actual cause of the dev crisis, only alleviates the symptoms. ಠ_ಠ

**Comment by DangerNoodle** [comment] 2016-11-25 19:16
I see. If you deem it important, open a separate issue.

**Comment by mugling** [comment] 2016-11-25 19:26
@mutability what you are proposing is commit-then-review, which I would support

@Coolthulhu weekly public builds would ease the pain considerably for little cost

**Comment by pisskop** [comment] 2016-11-25 19:30
weekly supported builds sounds nice.

An alarming number of people both want 'stable' builds and are afraid of the absolute newest hourly build

**Comment by mugling** [comment] 2016-11-26 18:37
Can @codemime or @sethsimon help with review of any of the currently open PR's? I think contributors can add a code review (affirmative or requesting changes). I'd like to tame the PR queue and in particular get some of the outstanding bugs closed.

**Comment by kevingranade** [comment] 2016-12-01 17:46
I don't have time for a longer response at the moment, but I'd like to
second that suggestion, if you're willing to do review and testing, start
doing it and post either bug reports against the pr or a statement of what
you reviewed and tested, and that it looks good to you.

This immediately lightens the mergers workload, is the best possible way to
demonstrate your abilities in this area.  Everyone who can pull and build a
PR can do the testing part, even if you aren't confident enough of your
coding abilities to review the code.

Having said that, I've invited codemime to join.

Please don't take this as a slight sethsimon, I just can't remember enough
history to make the call. That's Coolthulu's problem, as I'm giving him
permissions to manage team membership.

**Comment by codemime** [comment] 2016-12-01 21:00
Thanks so much for the invitation to join the core team (and for the nomination, of course). I'm grateful for the trust and I will strive to justify it.

**Comment by sethsimon** [comment] 2016-12-02 00:36
>Please don't take this as a slight sethsimon, I just can't remember enough history to make the call. That's Coolthulu's problem, as I'm giving him permissions to manage team membership.

@kevingranade Don't worry, I'm not miffed at all and I have no reason to be. Codemime is probably more qualified since he's been contributing for almost twice as long and has over twice as many contributions as me (according to the profile pages). Plus he's been doing reviews since before I even learned C++.

@codemime Congratulations!

**Comment by DangerNoodle** [comment] 2016-12-02 00:58
Hope things go well for it, @codemime.

**Closed** 2016-12-02 12:44 UTC
Labels: Organization, Suggestion (Discuss)

**Comment by codemime** [comment] 2016-12-04 10:03
Thanks.
@sethsimon I hope you'll join us before long.

**Comment by Cyrano7** [comment] 2018-01-15 07:57
@kevingranade Should we reopen this? 86 open PRs at once is the most I've seen that I recall. Some people with rights are not so active anymore. Maybe it's time for another round of this?

**Comment by BorkBorkGoesTheCode** [comment] 2018-01-15 08:35
I'd volunteer if I wasn't C++ illiterate.

**Comment by Cyrano7** [comment] 2018-01-15 21:21
Out of the old list of the most qualified candidates it looks like only @BrettDong is active. Although it looks like it's mostly translation updates lately.

Another choice is @Night-Pryanik who has a good open to merged ratio on PRs, understanding of C++, been contributing for a long time, has diverse PR content.

Anyone else?

**Comment by Cyrano7** [comment] 2018-01-16 06:21
Any other active core devs have an opinion? @Rivet-the-Zombie @codemime @BevapDin 

Unfortunately we don't have such a large active candidate base right now. But we are getting lots of submissions and I'd hate to see people get discouraged from contributing. Especially newer people doing good work like @sxmichaels

**Comment by ZhilkinSerg** [comment] 2018-02-11 20:50
Are we stalled badly?
