### ISSUE TITLE
NPC bug

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#40921] opened 2020-05-28 16:12 UTC
# Describe the bug

 After i complete the mission for NPC "Find inhaler" and try to continue (move) game crashes, --

# Steps To Reproduce

1. Give NPC item(inhaler) for mission.
2.  Says Mission successful "Find inhaler"  .
3. Try to continue game(move) game crashes. 

# Expected behavior

After i give inhaler to the NPC i should be able to continue game(move) normally. But the game instantly crashes when i try to step away from NPC.

Note# : I already have 1 NPC with me(game start scenario) and he didnt crash when i started the game tho he didnt ask me for any kind of mission if i remember correctly he just accepted to be follower.

# Screenshots

 
![Screenshot_1](https://user-images.githubusercontent.com/49565306/83165773-4a83ff00-a10e-11ea-899a-e33de5cc3399.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/49565306/83165788-4d7eef80-a10e-11ea-9dac-445995c37f72.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/49565306/83165799-4f48b300-a10e-11ea-927b-241bc76b5332.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/49565306/83165803-51127680-a10e-11ea-9528-1fad6a414475.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/49565306/83165810-52dc3a00-a10e-11ea-9e5c-f8cbff945d33.jpg)

# Versions and configuration

 
![System](https://user-images.githubusercontent.com/49565306/83163905-dfd1c400-a10b-11ea-8c59-edf072df32da.jpg)

 - OS: [Windows 10]
 - Game Version: [0.E-2475-g8640704]
 - Graphics version: [Undead People Tiles]
 - Ingame language: [System language(English)]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Aftershock, Blaze Industries, C.R.I.T Expansion Mod, Alternative Map Key, Mining Mod, More City Locations, Jury-Rigged Robots, Speedy Dex, Bionic Slots.]
 

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4696718/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4697717/debug.zip)

[Bannerland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4696771/Bannerland.zip)

- note#1 : I also saw that when i try to turn off MP3 player i still have Wearing Earphones status and wont go away(i cant crack safes) i dont know if i should post here or make another Issue, just wanted to share the bug.

- note#2 : I apologize if there is something missing i am noobie as far as GitHub goes, you can contact me on reddit Radicle_mind if you need anything, thanks and cheers.

**Comment by hexagonrecursion** [comment] 2020-05-28 17:09
@StefanMiletic994 A dog ate your bug report. Please fix it by editing it.

**Comment by StefanMiletic994** [comment] 2020-05-28 19:14
Now ok?

**Comment by anothersimulacrum** [comment] 2020-05-28 19:16
Nope, nothing's there still.
Anything between `<!--` and `-->` will be hidden, so if there are those, try removing them.

**Comment by StefanMiletic994** [comment] 2020-05-28 19:20
Oh, sorry didnt know that.

**Comment by mlangsdorf** [comment] 2020-08-17 12:51
I can't reproduce this on the latest experimental, either from the save file or from setting up a similar environment.  Something else may have fixed this.

If I don't get a response from @StefanMiletic994 in a week or so, I will go ahead and close this.

**Comment by mlangsdorf** [comment] 2020-10-09 14:09
I can't reproduce from the save file, initial reporter didn't respond.  I'm closing this.

**Closed by mlangsdorf** 2020-10-09 14:09 UTC
Labels: <Bug>, <Crash / Freeze>
