### ISSUE TITLE
The The

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#59275] opened 2022-07-14 22:59 UTC
### Describe the bug

![the the](https://user-images.githubusercontent.com/56016372/179110565-869c4c90-3cd2-4d3c-b548-0e765a835936.png)

### Steps to reproduce

1. Monster attacks you
2. The the

### Expected behavior

The

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: 354eb98 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Cimanyd0** [comment] 2022-07-14 23:34
Confirmed; I've seen this too.

**Comment by descan** [comment] 2022-07-14 23:35
The The giant dragonfly naiad and his mouthparts for me. Seems to be monster agnostic?

**Comment by ANickelN** [comment] 2022-07-14 23:42
I saw this with "The The Swat Zombie ..." so this is definitely occurring still as of release 07-14-1732.

**Comment by dseguin** [comment] 2022-07-15 04:58
Looks like a side effect of #58939.

`disp_name()` tacks on a leading "The", but all JSON attack messages include "The" already. That could be fixed by using `name()` instead:

```diff
diff --git a/src/mattack_actors.cpp b/src/mattack_actors.cpp
index 3f4a7f2568..5171e80969 100644
--- a/src/mattack_actors.cpp
+++ b/src/mattack_actors.cpp
@@ -335,21 +335,21 @@ void melee_actor::load_internal( const JsonObject &obj, const std::string & )
     optional( obj, was_loaded, "attack_upper", attack_upper, true );
 
     optional( obj, was_loaded, "miss_msg_u", miss_msg_u,
-              to_translation( "%s lunges at you, but you dodge!" ) );
+              to_translation( "The %s lunges at you, but you dodge!" ) );
     optional( obj, was_loaded, "no_dmg_msg_u", no_dmg_msg_u,
-              to_translation( "%1$s bites your %2$s, but fails to penetrate armor!" ) );
+              to_translation( "The %1$s bites your %2$s, but fails to penetrate armor!" ) );
     optional( obj, was_loaded, "hit_dmg_u", hit_dmg_u,
-              to_translation( "%1$s bites your %2$s!" ) );
+              to_translation( "The %1$s bites your %2$s!" ) );
     optional( obj, was_loaded, "miss_msg_npc", miss_msg_npc,
-              to_translation( "%s lunges at <npcname>, but they dodge!" ) );
+              to_translation( "The %s lunges at <npcname>, but they dodge!" ) );
     optional( obj, was_loaded, "no_dmg_msg_npc", no_dmg_msg_npc,
-              to_translation( "%1$s bites <npcname>'s %2$s, but fails to penetrate armor!" ) );
+              to_translation( "The %1$s bites <npcname>'s %2$s, but fails to penetrate armor!" ) );
     optional( obj, was_loaded, "hit_dmg_npc", hit_dmg_npc,
-              to_translation( "%1$s bites <npcname>'s %2$s!" ) );
+              to_translation( "The %1$s bites <npcname>'s %2$s!" ) );
     optional( obj, was_loaded, "throw_msg_u", throw_msg_u,
-              to_translation( "%s hits you with such a force that it sends you flying!" ) );
+              to_translation( "The %s hits you with such a force that it sends you flying!" ) );
     optional( obj, was_loaded, "throw_msg_npc", throw_msg_npc,
-              to_translation( "%s hits <npcname> with such a force that it sends them flying!" ) );
+              to_translation( "The %s hits <npcname> with such a force that it sends them flying!" ) );
 
     if( obj.has_array( "body_parts" ) ) {
         for( JsonArray sub : obj.get_array( "body_parts" ) ) {
@@ -474,7 +474,7 @@ bool melee_actor::call( monster &z ) const
                    target->disp_name() );
 
     const std::string mon_name = get_player_character().sees( z.pos() ) ?
-                                 z.disp_name( false, true ) : _( "Something" );
+                                 z.name() : _( "Something" );
 
     // Add always-applied self effects
     for( const mon_effect_data &eff : self_effects_always ) {
```

**Comment by dseguin** [comment] 2022-07-15 14:27
> The OP's screenshot displays "_claws_ at you", but there's nothing in #58939 about "claws at you".

The non-default hit messages are defined in the monster attack objects:

https://github.com/CleverRaven/Cataclysm-DDA/blob/93a5ad96cecda625e95b5a1f2d7c381f2ef8771c/data/json/monster_special_attacks/monster_attacks.json#L205

These messages are loaded instead of the default hardcoded ones if they're defined. In your PR, only the default hardcoded messages were updated, but all other hit messages still contain the leading "The".

**Closed** 2022-07-22 01:05 UTC
Labels: <Bug>, Info / User Interface
