### ISSUE TITLE
Mind over Matter error while save-quitting

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#68367] opened 2023-09-27 23:38 UTC
### Describe the bug

While saving and exiting from a world using Mind Over Matter, errors are shown on screen before returning to the main menu. There seem to be 4 in total but they look like this:

>  DEBUG    : (json-error)
> Json error: data/mods/MindOverMatter/modinteractions/Defense_Mode/scenarios.json:5:14: <color_white><color_cyan>Invalid or misplaced field name "extend" in JSON data</color>
> 
>     "copy-from": "defense_mode_fortified",
>     "type": "scenario",
> <color_light_red>    "extend": { "allowed_locs": [ "sloc_phavian_office" ] },
> </color>
>             <color_cyan>▲▲▲</color>
>     "id": "defense_mode_fortified"
>   },
> </color>
> 
> 
>  FUNCTION : error_skipped_members
>  FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
>  LINE     : 341
>  VERSION  : 0cf6cb3

This looks to be similar to issue 68365

### Attach save file

[Brookfield Center-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12744076/Brookfield.Center-trimmed.tar.gz)

### Steps to reproduce

Create a new world using Mind over Matter
Create a random character
Quicksave
Save and Quit

### Expected behavior

No errors should show while returning to the menu

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 0cf6cb3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12744078/debug.log)

**Comment by ZhilkinSerg** [comment] 2023-09-28 06:50
Duplicate of #68362

**Closed by ZhilkinSerg** 2023-09-28 06:50 UTC
Labels: (S1 - Need confirmation)
