### ISSUE TITLE
Flagpole generated inside of a laundromat door

### ISSUE THREAD

**Issue by skane10634** [CleverRaven/Cataclysm-DDA#66500] opened 2023-06-27 22:35 UTC
### Describe the bug

See title; screenshot of flagpole.

### Attach save file

[Page Park-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11887846/Page.Park-trimmed.tar.gz)

### Steps to reproduce

Map-gen

### Expected behavior

I would expect a flag-pole to not be inside a doorway.

### Screenshots

[https://gyazo.com/03e2dbc3cf5ea59faad7bb2434f041d5](url)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 0.G Stable STEAM [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by skane10634** [comment] 2023-06-27 22:38
[https://gyazo.com/919727a5a9afba0efe5fec23f8b584c4](url)
More flag poles.

**Comment by RenechCDDA** [comment] 2023-06-27 22:42
There is in fact flagpoles on all the doors. I bet this is a palette issue.

**Comment by RenechCDDA** [comment] 2023-06-27 22:45
https://github.com/CleverRaven/Cataclysm-DDA/blob/83a92bd1711f103970a4ba424d5f92fd794c2073/data/json/mapgen/mobile_home_park/mobile_home_park.json#L256-L308

Here's the mapgen, but I'm not immediately seeing the cause.

**Comment by RenechCDDA** [comment] 2023-06-27 23:12
Should be fixed on experimental by #64906

**Closed by RenechCDDA** 2023-06-27 23:12 UTC
Labels: (S2 - Confirmed), [JSON], Map / Mapgen
