### ISSUE TITLE
Lab finale does not connect to rest of the lab.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20813] opened 2017-04-09 04:55 UTC
If I did not think to debug, I would have never found it.
I have a jackhammer, so it's not a big deal for this PC.  But I don't think that is the way it's supposed to be.

![image](https://cloud.githubusercontent.com/assets/17521661/24834864/70c34c00-1cb6-11e7-8726-3071304e914f.png)

**Comment by WizardOfOoo** [comment] 2017-04-09 04:56
Latest jenkins build, 6384
Win x64 0.C-22030-g1217df8288 (tiles)

**Comment by WizardOfOoo** [comment] 2017-04-09 04:56
However, the map is several weeks or more old.

**Comment by ZenZen2** [comment] 2017-05-03 17:51
Duplicate of #9726

**Closed by ZenZen2** 2017-05-03 17:51 UTC
Labels: Mapgen
