### ISSUE TITLE
Turret target acquisition is wrong. 

### ISSUE THREAD

**Issue by TheMrMomo** [CleverRaven/Cataclysm-DDA#36412] opened 2019-12-24 18:35 UTC
# Describe the bug

Turrets don't target correctly. They can see through solid walls under the correct circumstances and are blind to people in clear line of site in other circumstances. 

# Steps To Reproduce

1. Go into a Lab. 
2. Find Turret in Rooms where the walls are partially Glass.
3. Slowly approach turret while lit-up. Turret will acquire the character as target through a solid wall and proceed to open fire . 

or 

1. Open door to room with turret. 
2. Turret has clear line of sight to player and is within 4 squares but doesn't see player and can be shot at with any weapon. 

# Expected behavior

Turrets don't have clairvoyance and shouldn't be able to acquire a target when a wall of solid concrete is in the way. This allows the turret to target the player before Safemode can activate causing the player to be shot if they continue to move one square to be behind the glass wall. 

If the turret doesn't target players with a clear line of sight it trivializes the threat of turrets. 

# Screenshots

![Screenshot (5)](https://user-images.githubusercontent.com/43098058/71422550-3a5d8480-2683-11ea-8037-3668c87e8687.png)

![Screenshot (6)](https://user-images.githubusercontent.com/43098058/71422560-52cd9f00-2683-11ea-842d-579e4c7062fe.png)

![Turret Sniper](https://user-images.githubusercontent.com/43098058/71423161-9b875700-2687-11ea-84ed-f254f1440f67.gif)

![Project 1](https://user-images.githubusercontent.com/43098058/71422987-5878b400-2686-11ea-88c6-fac2c0e9710a.gif)

# Versions and configuration

 - - OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10610-g8761541 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills]
]

Bug persists in Version: 
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10661-g0ab5f48 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
This nearly killed me.

**Comment by DatMeg** [comment] 2020-01-01 03:36
This may also work through z-levels as I repeatedly find turrets in labs who've expended their ammo, but there is nothing in the room, nor the doors open.

**Comment by DatMeg** [comment] 2020-01-04 21:02
I also want to add that this is a problem with automatic vehicle turrets as well.

**Comment by Saicchi** [comment] 2021-04-03 03:22
Can not reproduce on `0.E-10134-g9b256f63cd [64-bit]`. Played around a turret, using debug clairvoyance, the turret could not see me or monsters through the concrete walls.
 This seems like a duplicate of #34506.
Both should be fixed when #38730 got merged.

**Comment by Night-Pryanik** [comment] 2021-04-03 03:25
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-03 03:25 UTC
Labels: <Bug>, Monsters, Ranged
