### ISSUE TITLE
Killing bandits giving you innocent dismorale

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#62278] opened 2022-11-18 11:33 UTC
### Describe the bug

If you are killing bandits right after they saw you - you will get dismoral. But if you are wating for few seconds - no debuff. Thats happend while killing bandits in "Kill bandits" the old guard quest and "deal with informant". I will also attach videos

### Steps to reproduce

1) Make character with 10+ skills. Take gun
2) Find bandits. Just teleport to refuge center, take quest and teleport to banidts
3) I will show at video, how I kill them. I am standing behind the wall, crying, then killing them and got morale penalty. Or shoot informant right after he became hostile. And also when you try to walk on them, until they became fully hostile, there is opening a menu like when you are trying to walk on regular friendly npc

### Expected behavior

I want morale buff after killing badass punks, not penalty. May be our character is proud duelist, who is giving a few seconds to his opponents to be ready to the battle, but I didnt see such trait in my list

### Videos

<details>
  <summary>Penalty for killing informant</summary>

https://user-images.githubusercontent.com/102726167/202695759-6a9a1390-3f50-4fde-bf29-4e7606928f7e.mp4

</details>

<details>
  <summary>No penalty for killing informant</summary>

https://user-images.githubusercontent.com/102726167/202695829-76ed6275-4547-48fb-bcb3-f6541711703d.mp4

</details>

<details>
  <summary>Penalty for killing first bandit in bandit cabing and no penalty for other two</summary>

https://user-images.githubusercontent.com/102726167/202695884-d2d6d3dd-e368-45bb-b2ec-47a4fd608edc.mp4

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 90c0612 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment] 2022-11-18 14:05
Duplicate of #58552.

**Closed by Night-Pryanik** 2022-11-18 14:05 UTC
Labels: (S1 - Need confirmation)

**Comment by KHeket** [comment] 2022-11-18 14:13
> Duplicate of #58552.

But they see me. Check video, all of them see me. I killed guys at close range, like in 1 tile away or closer. Maybe the cause of the problem is the same, I dont know, but situations in this two issues are different. Should I close this issue or leave this ussie opened as

**Comment by Night-Pryanik** [comment] 2022-11-18 14:39
The issue in these situations are basically the same - player gets a morale debuff after killing NPC who are guaranteed hostile to player.
