### ISSUE TITLE
Movement through vehicle's tiles

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#21701] opened 2017-08-23 10:11 UTC
_Sorry for my poor English._

While the creature or player is on the tiles of the vehicle, he is in the vehicle's coordinate system. Which, when angled, for display on the screen in tiles, is artificially skewed.

So, in a skewed vehicle, moving along one of the diagonal directions corresponds to the movements on one tile, and on the other - more than one tile, in a non-skewed vehicle.

As a consequence, it is possible to pass through the walls or panels of the angled vehicle (#5684).

**_Suggestion_**
When moving, take into account the difference in the skew of the source and target tiles relative to the original position. Prohibit some movements - in which the increment of x or y is greater than 1, taking this difference into account. And, of course, gently inform about the reason.

I do not know how the pathing system works. Perhaps this requires very large-scale changes.

**_Examples_**
1, 2 and 3: non-skewed vehicle and skewed vehicle
4: a vehicle skewed in x coordinate, oriented to SSE
5: a vehicle skewed in y coordinate, oriented to SE
![image](https://user-images.githubusercontent.com/1931904/29610266-5cdcbde0-8802-11e7-836e-c24f4e0e5fb8.png)

Legend:
![image](https://user-images.githubusercontent.com/1931904/29610302-7cf0e070-8802-11e7-896d-bcd8a8f1677a.png)

Side note: in such cases, when 3 rows or columns have equal skewness, pseudographic rotation in the middle column or row are pointless.

**Comment by Coolthulhu** [comment] 2017-08-23 13:30
Movement from vehicle to vehicle is easy, although it would be very tedious to have to mentally transform things just to move around the vehicle.

The problem with wall phasing is movement to vehicle from outside, which is rather complex to handle.

**Comment by AMurkin** [comment] 2017-08-23 13:55
Red tile at second example is from vehicle to outside. Only diagonal movements should be special cased i think.

**Comment by Coolthulhu** [comment] 2017-08-23 14:54
The problem is, for it to really work, it has to be handled pretty much everywhere:
* Player movement
* Monster movement (most important, but easy)
* Monster vision (possibly hardest, but most performance-critical in some cases)
* Vision calculations (possibly hardest, but most performance-critical in the most common case)
* Monster attacks (melee would be covered by movement, though)
* Ranged attacks
* Pathfinding (probably easiest, provided monster movement is done right and not with hacks)

It must handle monster and player vision, meaning it needs some cache. Then also, it need some nice way to build and read this cache: cache building is relatively slow already.

The worst problems are:
* Monster vision would have to check vehicle transition every single tile. Monster vision can be very expensive already.
* Player vision checks a lot of tiles already. Having it also check and "decode" a new cache could slow it down hard

**Comment by kevingranade** [comment] 2017-08-23 15:49
What concerns me about this kind of limitation is that the only problematic
movement is the skewed version of #2, but a LOT of other movement is also
prohibited.  It's going to be very confusing to navigate in a vehicle using
these rules, especially since skewiness already makes some tiles
inaccessible by moving them away from the player.

Basically this prevents you from using the same logic to navigate inside
vehicles as you do normally, which is IMO worse than the discrepancies
caused by applying skew on top of the map system.

**Comment by AMurkin** [comment] 2017-08-23 16:47
I did not think that it would have to be applied not only to movements. Indeed all positional actions would be confusing for player.
But doubt that in tile system win-win solution could be found.
For fun imagine whan player steps on vehicle all the world is skewed and everything are translated to that skewed coordinates.

**Comment by kevingranade** [comment] 2017-08-24 06:11
I thought of one possibility for making in-vehicle navigation clearer.  We
could draw an inset vehicle map facing north the player can use to orient
themselves.
I'm not sure it's actually a good idea, but it does address that problem.

**Comment by CoroNaut** [comment] 2017-08-25 02:56
Could we have an invisible barrier sorround any vehicle the player steps into? For any tiles on the edge of the vehicle, the invisible barrier can be removed so that the player can easily go into and out of the vehicle from any tile that the player can move over. If the vehicle has walls, then these invisible barriers will be placed outside of those walls and attached to the vehicle so that if it is indeed skewed, the player character cant go through the wall to the outside, they would be blocked by the invisible barrier.

**Comment by KurzedMetal** [comment] 2018-08-25 22:42
I just got a single Grappler pull me out of my own Vehicle and made it roll over me.
My vehicle had doors closed, no other enemy was close and I was in the middle of plains close to a road.

![20180825_193350](https://user-images.githubusercontent.com/1426680/44623192-f4ca5500-a89e-11e8-931b-f9437a41444c.png)

![20180825_192454](https://user-images.githubusercontent.com/1426680/44623193-f7c54580-a89e-11e8-9e7e-ec4b981ba5a0.png)

**Comment by mlangsdorf** [comment] 2019-05-14 20:51
Closing.  We might do sentinel parts some day but we're not going to do weird movement variants inside of the vehicle code.

**Closed by mlangsdorf** 2019-05-14 20:51 UTC
Labels: Vehicles
