### ISSUE TITLE
When set too underslung shotgun firemode, gun becomes unwearable

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16609] opened 2016-05-10 09:44 UTC
i have a marlin .22 rifle with a shoulder strap, underslung shotgun, and some other generic mods, and wheneiver i have the fire mode set too use the underslung shotgun, i cant wear it.

**Comment by illi-kun** [comment] 2016-05-10 15:58
Why do you close the issue?

**Comment by codemime** [comment] 2016-05-10 20:14
Confirmed. Please reopen the issue. A rifle that has a shoulder strap, but uses an underslung shotgun to fire, returns `false` for `item::is_armor()` (normally it should return `true` regardless of the shotgun).

**Comment by 321nick** [comment] 2016-05-13 14:14
oh sorry, i..... forgot why i did close it. maybe its just that the fix is very easy- just switch too normal fire mode and u can wear it normally, but idk.

**Comment by codemime** [comment] 2016-05-13 14:53
I'd say that even minor bugs shouldn't be ignored because they may be symptoms of more serious issues (and I suppose it's the case).

**Comment by mugling** [comment] 2016-07-01 13:15
Likely fixed in #16488 and not since reported. Please reopen if reproducible in any recent version of `master`

**Closed by mugling** 2016-07-01 13:15 UTC
