### ISSUE TITLE
crafting bug: can't use more than 200 coal charges with smoking rack 

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20693] opened 2017-03-27 06:28 UTC
it happen when crafting dehydrated meat ,veggies and smoked meat

**Comment by spacenookie** [comment] 2017-03-27 19:21
limited to 200 charges (x8 batch) when using FOODCO to dehydrate tainted meat as well

**Comment by WizardOfOoo** [comment] 2017-03-30 17:52
Duplicate of #20049

**Comment by WizardOfOoo** [comment] 2017-04-10 03:38
Closed via 20746

**Closed** 2017-04-10 04:25 UTC
