### ISSUE TITLE
[sky island] [uilist] dialog menu bug

### ISSUE THREAD

**Issue by Asterix199** [CleverRaven/Cataclysm-DDA#75922] opened 2024-08-24 14:45 UTC
### Describe the bug

the text does not fit into the dialog box (in the English version) or is displayed outside the frame and is not erased (Russian(91,7%), Chinese (94,7%) and Japanese(99,1%) versions). When switching dialog items, the height of the frame changes and sometimes the dialog title disappears. the dialog box changes its size only when scrolling down. when scrolling up, the dialog box is static.

### Attach save file

[SkyIsland TEST-trimmed.tar.gz](https://github.com/user-attachments/files/16736979/SkyIsland.TEST-trimmed.tar.gz)

### Steps to reproduce

1. Start a new game with the Sky Island mod.
2. Go to the "Island`s Heart" statue and start a dialogue with it.
3. Select the line "d: I need your services"
4. Select the line "f: Change mydifficulty setting"
5. move down the rows.

### Expected behavior

it is necessary that the title of the dialog does not disappear and the text is readable and in translated version. 

### Screenshots

![image](https://github.com/user-attachments/assets/c55d40d9-d8c8-4e69-ac77-5d0dfe2e5cf1)
![image](https://github.com/user-attachments/assets/dddbc7ab-80b7-42fe-8bd0-fd2c8621f1ce)
![image](https://github.com/user-attachments/assets/48a78b36-d530-4ebd-8bc7-3beed38598bf)
![image](https://github.com/user-attachments/assets/ff3649af-2ba5-4855-9407-b9dcffa26e76)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.4780 (21H2)
- Game Version: cdda-experimental-2024-08-24-0612 ae2b99e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en] or Russian or Chinese or Japanese
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland]
]

**Comment by db48x** [comment] 2024-09-03 10:40
Duplicate of #75698

**Comment by Night-Pryanik** [comment] 2024-09-25 16:48
Closing as duplicate.

**Closed by Night-Pryanik** 2024-09-25 16:48 UTC
Labels: (S1 - Need confirmation)
