### ISSUE TITLE
Cannot craft molotov cocktail with glass bottle of gasoline

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#41585] opened 2020-06-25 15:48 UTC
# Describe the bug

The crafting recipe for molotov cocktails does not recognise the glass bottle as existing if it was already filled with gasoline before trying to craft.

# Steps To Reproduce

1. Get a rag.
2. Fill a glass bottle with 750ml gasoline.
2.1 Optionally take a small plastic bottle or similar container to unload 250ml of the gasoline into so it's consistent with the recipe which asks for 500ml.
3. Make sure you have no other glass bottles in crafting range.
4. Check the craft menu: cannot craft molotov cocktail because it doesn't see the bottle due to it being filled.

# Expected behavior

Being able to craft it because the glass bottle with gasoline and the rag are both in my inventory. Alternatively, being able to craft it after doing step 2.1.
This would be in line with reality, and the item's description also states "A bottle of flammable liquid with a rag inserted." which made filling it before crafting a logical choice for me.

# Screenshots

![Screenshot (9516)](https://user-images.githubusercontent.com/67428677/85752433-b6f11e80-b70b-11ea-8cbb-c807be14f48d.png)
![Screenshot (9517)](https://user-images.githubusercontent.com/67428677/85752438-b789b500-b70b-11ea-8c27-54a070355a23.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3489-g6e97042 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Dark Skies Above [darkskies]
]

# Additional context

**Comment by GGgatherer** [comment] 2020-06-26 15:31
You know that joke about the difference between physicists and mathematicians? Well, that recipe was definitely written/coded by mathematician - you need to reduce the task to already solved one, i.e. pour the gasoline somewhere else so you have an *empty* glass bottle, *then* do the recipe.

**Comment by kevingranade** [comment] 2020-06-28 16:58
Duplicate of #171

**Closed by kevingranade** 2020-06-28 16:58 UTC
Labels: Crafting / Construction / Recipes
