### ISSUE TITLE
Bash and Deconstruct return different terrain

### ISSUE THREAD

**Issue by lanelor** [CleverRaven/Cataclysm-DDA#55523] opened 2022-02-20 09:01 UTC
### Describe the bug

When I deconstruct a fence the ground reverts to dirt, but when someone/something bashes it, the ground becomes stone floor and rebuilding is impossible. This is caused by the 't_null' terrain set which is used in many places:

  {
    "type": "terrain",
    "id": "t_fence_post",
    "name": "fence post",
    "description": "A couple of posts that support the fence.  They look alone without the fence.",
    "symbol": "#",
    "color": "brown",
    "move_cost": 2,
    "flags": [ "TRANSPARENT", "THIN_OBSTACLE", "SHORT" ],
    **_"deconstruct": { "ter_set": "t_dirt"_**, "items": [ { "item": "pointy_stick", "count": 2 } ] },
    **"bash": {**
      "str_min": 8,
      "str_max": 20,
      "sound": "crack.",
      "sound_fail": "whump.",
      _**"ter_set": "t_null",**_
      "items": [ { "item": "pointy_stick", "count": [ 0, 2 ] } ]
    }
  },

### Steps to reproduce

1. Go near a fence
2. Bash it with a sledgehammer 
3. The grassy surface turns into rock floor

### Expected behavior

1. Go near a fence
2. Bash it with a sledgehammer 
3. The original surface remains

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Magiclysm No Class Limit [magiclysm_no_class_limit]
]

### Additional context

Going to mass-replace all the terrain jsons with dirt - it can be re-used unlike the rock floor tile :)

**Comment by NetSysFire** [comment] 2022-02-20 13:33
Can not reproduce. It reverted to t_dirt for me. I even went around and smashed different types of fence posts and constructed one myself, but none of that yielded stone floor.

**Comment by lanelor** [comment] 2022-02-20 20:18
I can recreate it this way:
1. started a new character and spawned a shovel from debug, plus enabled hammer mode
3. made three shallow pits > fence posts > barbed wire fence
4. the first picture shows the three fences and the second shows the effect of deconstruct and smash
- first fence after double deconstruct reverts to grass
- second fence is  deconstructed once and also showing gras beneath the post
- the third fence is smashed with the shovel and the ground below is rock instead of grass

Added two screenshots:
![BabrbedWire_on_grass](https://user-images.githubusercontent.com/98890690/154862359-66e12443-27ba-4957-8b56-e25b32b25b11.PNG)
![Smashed=Rock_floor](https://user-images.githubusercontent.com/98890690/154862369-9b437dcb-c020-463a-a8d3-318b6b1543d9.PNG)

**Comment by NetSysFire** [comment] 2022-02-20 22:03
I still can not reproduce this. Can you try using no mods?

**Comment by LeahLuong** [comment] 2022-02-21 03:30
This issue pretty much seems like a dupe of #48452. I believe it's been fixed for recent builds but I was unable to locate the PR.

**Comment by lanelor** [comment] 2022-02-21 07:11
@NetSysFire @LeahLuong
Thank you, for looking into this! [#48452](https://github.com/CleverRaven/Cataclysm-DDA/issues/48452) is the exact same issue I have. 

Since @NetSysFire is having trouble reproducing, maybe this is changed in more recent versions - I use the latest stable 0F2. The easiest way to know for sure is to open `gamefolder\data\json\furniture_and_terrain\terrain-fences-gates.json` and look up `"id": "t_fence_post"`. In the original version of the file when bashing I have `"ter_set": "t_null"` which changes the terrain to rock floor. I "fixed" the problem in my game by changing t_null into t_dirt where I though it is appropriately.

Reading the discussion about the other ticket, I understand the developer's concern about Z-levels, but not being able to repair smashed fences around my farm fields and damage to my base in general is important to me as a player.

**Closed** 2022-02-21 07:11 UTC
Labels: (S1 - Need confirmation), Fields / Furniture / Terrain / Traps
