### ISSUE TITLE
Revolver shooting error

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50311] opened 2021-07-29 22:29 UTC
### Describe the bug

Shooting a (burnt)10mm/.40 revolver is causing some issues:

- The ammo counter does not decrement after shooting
- after firing a few shots, the aiming cursor gets locked to 0 range (ammo display still shows 6/6) and throws an error when trying to move the cursor
- at this point, trying to open 'i'nventory and examining the pistol crashes the game

### Steps To Reproduce

1. Load [Pickett.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6903942/Pickett.zip)
2. Fire the wielded gun until it stops working correctly
3. Try to examine it

### Expected behavior

Ammo counter to display accurate count and for weapon to be partially reloadable etc.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

### Additional context

No crash.log was generated.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6903962/debug.log)

**Comment by actual-nh** [comment] 2021-07-29 22:31
Duplicate of #50299; that one currently has a PR to fix it.

**Closed by actual-nh** 2021-07-29 22:31 UTC
