### ISSUE TITLE
Catharsis morale boost

### ISSUE THREAD

**Issue by Altreus** [CleverRaven/Cataclysm-DDA#23969] opened 2018-06-08 09:09 UTC
I just found a working semi truck tractor unit behind the mall I started in. It was working and had a jerrycan of diesel nearby.

So I got in it and ploughed through about fifty zombies and it was the most satisfying experience this game has ever provided me.

My character didn't think so, though. After this many hand-to-hand kills and this long surviving alone in the world, seems like she'd have been pretty gleeful to have taken this opportunity.

She was already kind of happy though (`:)`). Maybe there could be a catharsis morale boost for performing various acts if your morale is low? Running a baddie over, smashing a fence, that sort of thing.

**Comment by nexusmrsep** [comment] 2018-06-08 14:32
Small stacking morale bonus for killing monsters sounds good at first, but i can easily imagine feeling different, either engrossed by all the gore, or fearful due to near death experience. Its fun when you sit in an APC plowing throu a horde, but much less fun when you chop yourself a way out from a "dead end" while bloodied and nearly broken. Then all you feel is fear and maybe relief, not extatic at all. I don't believe there is a way you can identify both contextual situations code-wise.

**Comment by thethunderhawk** [comment] 2018-06-08 17:54
I could see it as a character gen trait worth a couple points. Certainly not everyone would be stoked to damage a perfectly good semi truck by liquefying the corpses of half a hundred innocent people who succumbed to the extermination of humanity.
Some folks might really enjoy that though.

**Comment by kevingranade** [comment] 2018-07-05 23:08
The thing about morale boosts is they need to be something that improves your mood over and over again.  Reading fits, eating fits, even drinking and drugs fits (various side effects aside), but killing things? I'm not sure about that unless you're, for lack of a better word, a psychopath, and even then you aren't necessarily going to derive lasting pleasure from killing random enemies, *especially* if it's particularly easy.

From a game design point of view, it might be reasonable to do something like this to encourage some action the player isn't going to bother with otherwise, but that's not the case with killing in dda, the game wants you to do it as necessary and refrains from rewarding you for it other than the fact that the enemy is no longer a threat.  In particular, once the enemy isn't a threat, we don't want to reward wiping them out, because there's no point and no challenge, so it only kicks in when it's not necessary.

I like @thethunderhawk's angle of "adrenaline junkie" or "berserker", but that takes it in an entirely different direction.  Are you addicted to danger?  Then it has to be dangerous, maybe it only happens if you're wounded, which doesn't reward pure aggression, instead it rewards thrill-seeking and possibly even self-destructive play.  Then the bonus is balanced out by the risk you're taking.  We might have a heuristic for whether it's possible for an enemy to damage you (i.e. compare its attack stats to your armor, dodge, etc and whether it's in range to attack).  That might be tricky to code in, but if we don't cut it too close it might work as intended by rewarding a play style where you have a decent change of taking damage.

**Comment by Night-Pryanik** [comment] 2019-02-02 18:36
No discussion in over half a year, closing.

**Closed by Night-Pryanik** 2019-02-02 18:36 UTC
Labels: <Suggestion / Discussion>
