### ISSUE TITLE
Read dialog allows picking up items without triggering stealing check

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61370] opened 2022-09-30 21:24 UTC
### Describe the bug

When [R]eading a book from a bookshelf or elsewhere you will pick up the book, even if picking it up directly would have been theft.

### Steps to reproduce

1. Stand next to a book owned by an NPC, such as on a bookshelf in the Old Guard office
2. [R] then choose the book
3. After reading the book, see it in your inventory, not stolen

### Expected behavior

Same "that would be stealing, continue?" prompt as when trying to pick the container up, or the book ends up back on the shelf instead of in your inventory.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.C-73717-gcaf20a88a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Could probably have one consolidated fix with #61296 and #61294. Unlike those other cases, in this one you'll be interrupted if an NPC is watching.

**Comment by Night-Pryanik** [comment] 2022-10-01 06:21
Duplicate of #37181.

**Closed by Night-Pryanik** 2022-10-01 06:21 UTC
Labels: (S1 - Need confirmation)
