### ISSUE TITLE
Friendly NPC not able to wear your full-body armors

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17549] opened 2016-07-05 17:04 UTC
If I ask NPC to wear full-body armor, like power armor by option `I want you to use this item`, he says he cannot wear it or use it as weapon. I think it's because he already wearing some boots, which is incompatible with power armor, because using same feet slot. So probably there need to be a check if NPC should take off his boots, if stats of new armor is higher.

P.S. Hope you understand what I'm explaining.

**Comment by pisskop** [comment] 2016-07-05 18:12
NPCs will also refuse to wear armor that is to encumbering.  So after the check for encumbrance theyd check for weapon use.

**Comment by Xelat84** [comment] 2016-07-05 18:20
So then it's not clear enough what exactly happening. Just there should be a way to find out which armor I should propose to NPC so he will wear it. I can't try to give him all possible combinations of armor, especially as I cannot take off his armor back. Maybe there should be some numbers, like when he reject wearing armor, he explain which body part exceed his limitation of encumbering and what amount.

**Comment by Vollinger** [comment] 2016-07-05 19:01
used to be able to strip em, have them follow you, examine the tile they're on, sort armor & unequip it from there

**Comment by Xelat84** [comment] 2016-07-05 19:20
@Vollinger oh, interesting workaround! Will try, thanks!

**Comment by Labtop-215** [comment] 2016-07-06 17:56
Why are you giving an NPC power armor?  Wont the armor just get lost when the NPC's inventory is changed?

**Comment by Xelat84** [comment] 2016-07-06 18:06
@Labtop-215 I'm giving it to Friendly NPC just to not get his ass kicked by a moose. What do you mean by **inventory is changed**?

**Comment by pisskop** [comment] 2016-07-06 18:35
Shopkeeper class npcs will refresh their inventory every few days

**Comment by Xelat84** [comment] 2016-07-06 18:53
@pisskop didn't know that. But why they update items they are wearing? And where they get those new items, if they always following you or sitting on your base?

**Comment by Labtop-215** [comment] 2016-07-06 18:56
It seems to me that all NPC's refresh their inventory, weather they are with me or not.  I'm also not sure if they refresh what they are wearing, but I would count on it happening.

**Comment by Coolthulhu** [comment] 2016-07-06 19:17
NPC inventory refresh thing is caused by shopkeeper restock, which will be fixed once #17444 is merged.

**Comment by Ramza13** [comment] 2020-02-16 01:44
Pretty sure that #37654 takes care of this.

**Closed** 2020-10-19 04:01 UTC
Labels: (S1 - Need confirmation), <Bug>, NPC / Factions
