### ISSUE TITLE
Mobile joystick gets stuck

### ISSUE THREAD

**Issue by mrduck-ux** [CleverRaven/Cataclysm-DDA#41557] opened 2020-06-24 08:21 UTC
L

Sometimes when I use the joystick on mobile it sticks and makes the game crash

If I use the joystick there is a chance it will stay in the position I pulled it and stick. After a while it crashed the game

# Steps To Reproduce

# Versions and configuration

 - OS: Android
 - Game Version: 0.E_3407_g845884a
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: not applicable due to it happening in the menu
 -->

**Comment by ZhilkinSerg** [comment] 2020-06-24 15:27
Possibly a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33936

**Comment by notazed** [comment] 2020-07-19 03:31
Can confirm still having this issue. But I think I found a quick fix by slightly increasing the Virtual Joystick Repeat Rate (Deflected) value from 100 to 150.

**Comment by RustyBrute** [comment] 2020-07-20 04:47
> Can confirm still having this issue. But I think I found a quick fix by slightly increasing the Virtual Joystick Repeat Rate (Deflected) value from 100 to 150.

I tried this, sadly it did not worked for me.

**Comment by Maryionet** [comment] 2020-08-15 13:31
> > Can confirm still having this issue. But I think I found a quick fix by slightly increasing the Virtual Joystick Repeat Rate (Deflected) value from 100 to 150.
> 
> I tried this, sadly it did not worked for me.

Try using b10738

**Closed** 2020-08-17 15:28 UTC
Labels: Controls / Input, OS: Android, SDL: Tiles / Sound
