### ISSUE TITLE
Overhaul of RELOAD_AND_SHOOT weapons?

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#72359] opened 2024-03-13 04:45 UTC
### Is your feature request related to a problem? Please describe.

RAS weapons bugged for years, making it an annoyance using bows and slingshots, especially when compared to guns and crossbows without this FLAG.

RAS weapons waste moves in a particular way. Ammos are not kept in the "magzine" of RAS weapons, every time you try to shoot by entering `f`ire menu, you load an ammo first. If you change your mind and quit the menu, you unload your weapon, keeping it empty as intended. 
The problem is, the moves of taking ammo out and reloading your RAS weapon is cost even if you quit the menu immediately. What's worse, RAS weapons do not display the move cost of loading them with ammo in the `f`ire menu, thus it can lead to unwilling situations.
Furthermore, an improvement was made to aim UI, allowing auto re-entering of aim UI immediately after firing, and due to the bug above, RAS weapons have been forbidden to do so by a workaround in activity_actor.cpp.
```
    if( weapon && weapon->gun_current_mode()->has_flag( flag_RELOAD_AND_SHOOT ) ) {
        // RAS weapons are currently bugged, this is a workaround so bug impact
        // isn't amplified, once #54997 and #50571 are fixed this can be removed.
        restore_view();
        return;
    }
```
BTW, there is a condition that the move cost of taking ammo out of your pockect and loading it will be refunded. If you aim at adjacent tile and press `.`, since that you can not make your aim steadier, you simply wait for 1 turn. At this point, quiting `f`ire menu costs 0 point. All points are refunded and treated as if the ammo was never loaded in the first place.

### Solution you would like.

After further investigation, I found out that all that issues were solved perfectly in CBN.

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1660
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1815
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1857
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2468

In CBN, if you quit the fire menu without shooting, the move cost of taking ammo out of your pockect and loading it will be refunded. The actual move cost, including those of taking ammo out of your pockect and loading it, is displayed in aimming UI. Moves are not cost unless you actually fire your RAS weapon. 
There are other improvements to ranged weapon system also.

Can we port over and update those codes?

### Describe alternatives you have considered.

I came up with a workaround, making it possible to store an arrow on a bow's drawstring, using NO_UNLOAD FLAG and use_action transform. There's no need to do this if we can totally solve the issues.

**Comment by RenechCDDA** [comment] 2024-03-13 04:49
Duplicate of #71819

**Closed by RenechCDDA** 2024-03-13 04:49 UTC
Labels: <Suggestion / Discussion>
