### ISSUE TITLE
character has ceased to be healed

### ISSUE THREAD

**Issue by yaunut** [CleverRaven/Cataclysm-DDA#31654] opened 2019-06-20 12:31 UTC
character has ceased to be healed  <Bug>
in the same version was healed, suddenly stopped
already a few game shows days
[seave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310354/seave.zip)

**Comment by TechyBen** [comment] 2019-06-20 13:21
What version are you playing?

**Comment by yaunut** [comment] 2019-06-20 14:35
version 9189

**Comment by TechyBen** [comment] 2019-06-20 17:01
I was healing fine in this build (but my own save). Did you use bandages? Wounds heal very slow without them now.

**Comment by yaunut** [comment] 2019-06-20 17:18
I used bandages several times a day
but the wounds do not change around five play days
too long..

**Comment by adamkad1** [comment] 2019-06-20 18:10
you dont happen to have any mutations that would stop it?

**Comment by yaunut** [comment] 2019-06-20 18:37
i only have perk "slow recovery" (10% from the usual)
but all the time before the character recovered
though a flaming eye attacked me recently and after that the treatment stopped despite regular dressings

**Comment by Zireael07** [comment] 2019-06-20 18:54
Aha, flaming eyes have all sorts of weird effects. I don't know the details, though, but it's highly likely it's relevant.

**Comment by yaunut** [comment] 2019-06-20 19:09
yes, but what exactly?
nothing in status
and the effects should pass with time, but I have not had a week to go

**Comment by adamkad1** [comment] 2019-06-20 21:32
some statuses are hidden? also, perhaps your hidden health stat is low, that can disable healing

**Comment by yaunut** [comment] 2019-06-21 06:03
is there a way to view hidden health and statuses? can in what the ini file?

**Comment by Inglonias** [comment] 2019-06-21 12:54
You can debug mutate yourself to have the Self-Aware trait, which, when activated, just shows you your health stat.

**Comment by yaunut** [comment] 2019-06-21 13:21
how can I debug a mutation of myself? got a program? or in the file need to be rewritten? maybe there is a link to the manual?

**Comment by KorGgenT** [comment] 2019-06-21 13:22
you are actually healing, but it is at a very slow rate. (probably 3-5 hp per day, with an hp of ~84)

**Comment by KorGgenT** [comment] 2019-06-21 13:23
i am closing this because it is not a bug.

**Closed by KorGgenT** 2019-06-21 13:23 UTC
