### ISSUE TITLE
Items vanish when dropped on rubble

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26624] opened 2018-11-10 14:29 UTC
**To Reproduce**  
1. Take an artifact located in the center of a huge pile of rubble.
2. Drop it into one of the pile tiles.
3. Clear rubble with your spade.

**Expected behavior**  
I should've been able to find it underneath!

**Versions and configuration(please complete the following information):**
0.C-34224-g7b0e7c29cf-dirty

**Comment by ZhilkinSerg** [comment] 2018-11-10 15:52
Duplicate of #8979.

**Closed by ZhilkinSerg** 2018-11-10 15:52 UTC
Labels: (S3 - Duplicate), <Bug>
