### ISSUE TITLE
Kaluptic Psychosis hallucinations can throw vehicles around

### ISSUE THREAD

**Issue by Eetu13** [CleverRaven/Cataclysm-DDA#53067] opened 2021-11-27 19:41 UTC
### Describe the bug

Kaluptic Psychosis hallucinations can interact with vehicles and throw them around (damaging it) and hurt you with them. 

### Steps to reproduce

1. Hallucinate and be near a vehicle 
2. Wait until hallucination spawns behind the vehicle 
3. Hallucination tries to move towards you and throws the vehicle in your face

### Expected behavior

It's a hallucination, so it shouldn't be able to throw vehicles towards me and break environment with vehicles.

### Screenshots

![image](https://user-images.githubusercontent.com/25620187/143719500-a7033706-073a-433a-9be2-f70bbd9ccd29.png)
![image](https://user-images.githubusercontent.com/25620187/143719525-a9116bbf-1a7d-4931-bc1e-286fa8a6a723.png)

### Versions and configuration

OS: Windows 10
Game Version: Experimental: 2021-11-25-0832 
Graphics Version: Tiles
Ingame language: English
Mods: [dda, Disable NPC Needs, SpeedyDex]

**Comment by wapcaplet** [comment] 2021-11-27 19:54
Duplicate of #52808

**Closed** 2021-11-27 19:59 UTC
Labels: (S3 - Duplicate)
