### ISSUE TITLE
Error on 9153 version while loading world

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#31418] opened 2019-06-14 08:37 UTC
I updated cdda to the 9153. And when I try to play, my world starts loading, but stops on Vehicle prototypes and gives me this:

DEBUG    : Error: basic_string::_M_construct null not valid
 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 709

**Comment by BugBurgA** [comment] 2019-06-14 09:18
This occurs to me on build 9153, 2 and 1 as well.

**Comment by Joanakor** [comment] 2019-06-14 09:27
I also checked on this versions and it happens.

**Comment by Zrashin** [comment] 2019-06-14 10:44
I had this issue when I updated to 9152, it only happens when I add Aftershock, or a vehicle mod, but I haven't checked the rest, it may be for all mods.

**Comment by neitsa** [comment] 2019-06-14 10:45
Probably a duplicate of #31399.

**Comment by lmirk509** [comment] 2019-06-14 17:28
Same, but without Aftershock mod. A lot of other mods, though. Tried copying worlds, removing mods one by one, got through by excluding Crazy Cataclysm. Tried to removed it from original world, but still got the same error.

**Comment by OptimisticNihlist** [comment] 2019-06-14 19:33
Same here, this is the relevant entry from my debug.log @I-am-Erk 

14:24:55.027 : Starting log.
14:24:55.027 INFO : Cataclysm DDA version 0.D-4304-ge7ca42c
14:24:55.036 INFO : Number of render drivers on your system: 4
14:24:55.036 INFO : Render driver: 0/direct3d
14:24:55.036 INFO : Render driver: 1/direct3d11
14:24:55.036 INFO : Render driver: 2/opengl
14:24:55.036 INFO : Render driver: 3/software
14:24:55.039 INFO : Language is set to: 'en'
14:24:55.352 INFO : SDL version used during compile is 2.0.5
14:24:55.352 INFO : SDL version used during linking and in runtime is 2.0.5
14:24:55.463 INFO : Active renderer: 0/direct3d
14:24:55.620 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
14:24:56.099 WARNING : opendir [./mods/] failed with "No such file or directory".
14:25:38.956 WARNING : Deprecated foreground color suffix was used: (lt) in (ltred).  Please update mod that uses that.
14:25:38.972 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.284 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.284 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.285 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.287 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.394 ERROR : (error message will follow backtrace)
	(@0x59f01e[cataclysm-tiles.exe+0x19f01e]), 
	(@0x59f64a[cataclysm-tiles.exe+0x19f64a]), 
	(@0x521859[cataclysm-tiles.exe+0x121859]), 
	(@0x529914[cataclysm-tiles.exe+0x129914]), 
	(IMG_LoadWEBP_RW+0x13f92f@0x10fa2af[cataclysm-tiles.exe+0xcfa2af]), 
	(@0x8ead42[cataclysm-tiles.exe+0x4ead42]), 
	(@0x8ef286[cataclysm-tiles.exe+0x4ef286]), 
	(IMG_LoadWEBP_RW+0x1d0cde@0x118b65e[cataclysm-tiles.exe+0xd8b65e]), 
	(@0x8f0ff2[cataclysm-tiles.exe+0x4f0ff2]), 
	(@0x710211[cataclysm-tiles.exe+0x310211]), 
	(@0x712cc2[cataclysm-tiles.exe+0x312cc2]), 
	(@0x7132db[cataclysm-tiles.exe+0x3132db]), 
	(@0x67d335[cataclysm-tiles.exe+0x27d335]), 
	(@0x67f5a6[cataclysm-tiles.exe+0x27f5a6]), 
	(@0x6a4965[cataclysm-tiles.exe+0x2a4965]), 
	(@0x888687[cataclysm-tiles.exe+0x488687]), 
	(@0x889c7a[cataclysm-tiles.exe+0x489c7a]), 
	(IMG_LoadWEBP_RW+0x546f4f@0x15018cf[cataclysm-tiles.exe+0x11018cf]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x76ce59cd[kernel32.dll+0x159cd]), 
	(RtlUserThreadStart+0x21@0x76e1a2e1[ntdll.dll+0x2a2e1]), 
Backtrace emission took 0 seconds.
couldn't parse color: c_tan
14:25:39.420 ERROR : couldn't parse color: c_dark_green
14:25:39.432 ERROR : couldn't parse color: c_gray
14:25:39.432 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.432 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.433 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.434 ERROR : couldn't parse color: c_dark_blue
14:25:39.434 ERROR : couldn't parse color: c_dark_green
14:25:39.451 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.452 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.453 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.482 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.483 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.671 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:39.674 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:25:40.507 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
14:25:40.508 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
14:25:49.701 WARNING : opendir [./save/Mount Carroll/mods] failed with "No such file or directory".
14:25:50.040 ERROR : src/main_menu.cpp:977 [bool main_menu::load_character_tab()] Error: basic_string::_M_construct null not valid
14:29:48.768 WARNING : Deprecated foreground color suffix was used: (lt) in (ltred).  Please update mod that uses that.
14:29:48.769 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.783 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.783 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.784 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.784 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.791 ERROR : (error message will follow backtrace)
	(@0x59f01e[cataclysm-tiles.exe+0x19f01e]), 
	(@0x59f64a[cataclysm-tiles.exe+0x19f64a]), 
	(@0x521859[cataclysm-tiles.exe+0x121859]), 
	(@0x529914[cataclysm-tiles.exe+0x129914]), 
	(IMG_LoadWEBP_RW+0x13f92f@0x10fa2af[cataclysm-tiles.exe+0xcfa2af]), 
	(@0x8ead42[cataclysm-tiles.exe+0x4ead42]), 
	(@0x8ef286[cataclysm-tiles.exe+0x4ef286]), 
	(IMG_LoadWEBP_RW+0x1d0cde@0x118b65e[cataclysm-tiles.exe+0xd8b65e]), 
	(@0x8f0ff2[cataclysm-tiles.exe+0x4f0ff2]), 
	(@0x710211[cataclysm-tiles.exe+0x310211]), 
	(@0x712cc2[cataclysm-tiles.exe+0x312cc2]), 
	(@0x7132db[cataclysm-tiles.exe+0x3132db]), 
	(@0x67d335[cataclysm-tiles.exe+0x27d335]), 
	(@0x67f5a6[cataclysm-tiles.exe+0x27f5a6]), 
	(@0x6a4965[cataclysm-tiles.exe+0x2a4965]), 
	(@0x885df7[cataclysm-tiles.exe+0x485df7]), 
	(@0x889680[cataclysm-tiles.exe+0x489680]), 
	(IMG_LoadWEBP_RW+0x546f4f@0x15018cf[cataclysm-tiles.exe+0x11018cf]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x76ce59cd[kernel32.dll+0x159cd]), 
	(RtlUserThreadStart+0x21@0x76e1a2e1[ntdll.dll+0x2a2e1]), 
Backtrace emission took 0 seconds.
couldn't parse color: c_tan
14:29:48.794 ERROR : couldn't parse color: c_dark_green
14:29:48.795 ERROR : couldn't parse color: c_gray
14:29:48.795 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.796 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.796 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.796 ERROR : couldn't parse color: c_dark_blue
14:29:48.796 ERROR : couldn't parse color: c_dark_green
14:29:48.798 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.798 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.798 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.801 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.801 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.822 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:48.822 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:49.048 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
14:29:49.048 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
14:29:49.827 ERROR : couldn't parse color: c_light_grey
14:29:49.861 WARNING : opendir [./save/McNeal/mods] failed with "No such file or directory".
14:29:50.188 ERROR : src/main_menu.cpp:709 [bool main_menu::new_character_tab()] Error: basic_string::_M_construct null not valid
14:29:58.159 WARNING : Deprecated foreground color suffix was used: (lt) in (ltred).  Please update mod that uses that.
14:29:58.160 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.174 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.174 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.174 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.174 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.180 ERROR : couldn't parse color: c_tan
14:29:58.183 ERROR : couldn't parse color: c_dark_green
14:29:58.184 ERROR : couldn't parse color: c_gray
14:29:58.184 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.184 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.184 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.185 ERROR : couldn't parse color: c_dark_blue
14:29:58.185 ERROR : couldn't parse color: c_dark_green
14:29:58.186 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.186 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.187 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.190 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.190 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.210 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.211 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
14:29:58.421 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
14:29:58.421 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
14:29:58.923 ERROR : couldn't parse color: c_light_grey
14:29:58.951 WARNING : opendir [./save/McNeal/mods] failed with "No such file or directory".
14:29:59.291 ERROR : src/main_menu.cpp:709 [bool main_menu::new_character_tab()] Error: basic_string::_M_construct null not valid
14:30:05.014 : Log shutdown.

**Comment by hexob** [comment] 2019-06-14 19:42
i have this exact error and i fixed it by disabling aftershock and cata++

hope this helps

**Comment by Randonx** [comment] 2019-06-15 01:45
It's Cata++ that does it.  Will continue to do so until it's updated.

**Comment by BugBurgA** [comment] 2019-06-15 01:47
I don't use Cata++, it's probably a combination of mods

**Comment by I-am-Erk** [comment] 2019-06-15 01:55
@OptimisticNihlist Not sure why you tagged me there

**Comment by anothersimulacrum** [comment] 2019-06-15 03:23
They probably meant to tag lmirk509, who has a vaguely similar name.

**Comment by Orinyau** [comment] 2019-06-15 07:39
Getting this crash as well, Aftershock seems to be the culprit. I believe the tanks mod also gets an invalid ammo type error. 

Probably related to the fact that people are having trouble getting weapons to (f)ire, anything that adds ammo types, vehicle or otherwise seems broken.

**Comment by l29ah** [comment] 2019-06-15 08:46
Should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/31442.

**Closed** 2019-06-15 14:45 UTC
Labels: <Crash / Freeze>, Vehicles
