### ISSUE TITLE
Update_zombie_pos "location already has the raccoon"

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35560] opened 2019-11-16 19:32 UTC
Got this while sleeping. No obvious reasons. 

DEBUG    : update_zombie_pos: wanted to move the raccoon to 72,71,-1, but new location already has the raccoon

 FUNCTION : bool Creature_tracker::update_pos(const monster&, const tripoint&)
 FILE     : src/creature_tracker.cpp
 LINE     : 127

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9369-ge612365 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

**Comment by ifreund** [comment] 2020-02-13 10:06
Closing this as a duplicate of #37683 since there is more info there

**Closed by ifreund** 2020-02-13 10:06 UTC
Labels: <Bug>, Monsters, Spawn
