### ISSUE TITLE
CBM Installation Crash: Autosaved during installation process.

### ISSUE THREAD

**Issue by Rofltauren** [CleverRaven/Cataclysm-DDA#65387] opened 2023-04-30 11:43 UTC
### Describe the bug

Installed Throwing Assist CBM through Rubik after installing several CBM's with no issue. Game autosaved whilst CBM was being installed and upon waking the game crashed, directing to the error logs. Upon reloading, game continues to run until CBM installation completes and then crashes again. Debug menu cannot be opened and fresh game install changed nothing.

### Attach save file

[#U3ZlbiBCZXJnYW1vbnQ=.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11361172/U3ZlbiBCZXJnYW1vbnQ.log)
[#U3ZlbiBCZXJnYW1vbnQ=.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/11361183/U3ZlbiBCZXJnYW1vbnQ.txt)

### Steps to reproduce

Install Throw Assist CBM through Rubik
Wake
Crash

### Expected behavior

Ideally wake up and continue on with the game.

Possible fix could involve a method to force wake/abort the installation, but debug console will not open and as far as I can tell, there is no method to allow this.

### Screenshots

![image](https://user-images.githubusercontent.com/132199593/235350991-d8871ee7-3497-4dbe-bf84-131d7bb30b41.png)

### Versions and configuration

Windows 10
af4a7b3 Tiles
English
No Mods

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11361193/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11361194/debug.log)

All other CBM's installed without issue, game operates "As expected" during installation process, time advances etc.

**Comment by andrei8l** [comment] 2023-04-30 12:19
Looks like a duplicate of #64036

**Comment by Rofltauren** [comment] 2023-04-30 13:13
> Looks like a duplicate of #64036

Ah yeah seems to be similar, Would you be able to help me apply that Patch? I'm pretty tech illiterate

**Closed** 2023-05-12 22:45 UTC
Labels: (S1 - Need confirmation)
