### ISSUE TITLE
Since I just registered on GitHub, I can't explain it constructively (IMHO). The essence of the problem: an error occurs (stopping the process) when searching for refugees using the terminal in the shelter.

### ISSUE THREAD

**Issue by DvergarMrachnoy** [CleverRaven/Cataclysm-DDA#45209] opened 2020-11-02 19:02 UTC
# Describe the bug

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-11-02 23:30
Duplicate of #43457

**Closed by ZhilkinSerg** 2020-11-02 23:30 UTC
Labels: (S3 - Duplicate)
