### ISSUE TITLE
Repairing broken car battery destroys charges

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12289] opened 2015-05-03 23:49 UTC
If you replace a gray/destroyed battery with a charged battery, the new battery will have 0% charge rather than whatever the replacement had prior.

**Comment by DeNarr** [comment] 2015-05-04 13:56
Well, repairing suggest that you are using the new battery for parts in order to fix the old battery. If you want to keep your charge, you should remove the broken battery, and install the new one.

**Comment by ejseto** [comment] 2015-05-04 23:41
I don't see how that's implied at all. Normal repairs don't take any parts outside of tool charges. The implication is absolutely that you're replacing something that cannot be repaired.

**Comment by DeNarr** [comment] 2015-05-04 23:44
Well, as another example, look at tires. You can repair a tire of one size with a tire of another size. It is not replacing it with the different sized tire, but using the extra that you have in order to repair the size you already have on there. Also, repairing is often more difficult that replacing, as you would expect.

**Comment by ejseto** [comment] 2015-05-04 23:45
If the repaired tire has the same diameter as the old one instead of the one you used to repair it, that doesn't make any sense either.

**Comment by DeNarr** [comment] 2015-05-04 23:47
Yes it does, because you are "repairing" the old one, not "replacing" it with the new one. That means you are using the new one as parts in order the repair the old one. If you want to have the diameter of the new one, just remove the broken one, and replace it with the new one. The functionality for both is currently enabled, you just have to choose the correct option for what you want.

**Comment by ejseto** [comment] 2015-05-05 01:22
I don't agree with that.

**Comment by BevapDin** [comment] 2015-05-05 11:54
A grayed vehicle part is completely broken, it stops being an obstruction and it looses basically all its functions.

The vehicle information even says so when you try to repair a broken part: "You also need a wrench and \<vehicle-part-item\> to replace broken one."

Additionally you get items from the broken vehicle part when you "repair" it with a new item (e.g. you get metal scraps and the like when repairing a broken frame using a new frame item).

**Comment by Sirbab** [comment] 2015-05-11 04:46
Yeah, i agree, this is intended, not a bug. you are physically replacing the battery with a new one, no need to retain the charge. And transferring charge from a broken battery sounds very infeasible if not impossible.

**Comment by narc0tiq** [comment] 2015-05-11 05:01
Uh, this is about retaining the charge of the replacement battery item,
used for repair. Repairing a gray (destroyed) battery vpart with a battery
item that has 3,000 charges should set the repaired battery vpart to 3,000
charges.

**Comment by Sirbab** [comment] 2015-05-11 05:03
Ohh, my bad. then yeah, it totally should retain it's charge, disregard what i said before.

**Closed** 2015-06-19 18:02 UTC
