### ISSUE TITLE
arc welder crashes when used plugged without battery

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#67109] opened 2023-07-23 03:33 UTC
### Describe the bug

Using an arc welder or makeshift arc welder plugged to a furniture or vehicle without a battery inside crashes on segmentation fault

### Attach save file

[Woodacre-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12137944/Woodacre-trimmed.tar.gz)

### Steps to reproduce

1- Have an arc welder
2- Plug into a vehicle 
3- Activate without battery

### Expected behavior

to be usable with the battery of the system is connected to

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 624dc0f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment] 2023-07-23 03:38
Duplicate of #66944

**Closed by RenechCDDA** 2023-07-23 03:38 UTC
Labels: (S1 - Need confirmation)
