### ISSUE TITLE
🍅🥫 Canning tomatoes yields sealed glass jar of canned tomatoes (2/4) 🥫🍅

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38201] opened 2020-02-21 13:05 UTC
# Describe the bug

Canning tomatoes in a jar results in the jar only being half full (2/4)

# Steps To Reproduce

1. Find some tomatoes, canning pot, and a regular glass jar.
2. Can the tomatoes.
3. Observe your `sealed glass jar of canned tomatoes (2/4)`

# Expected behavior

Survivors fill jars before canning.

# Versions and configuration

7206b26ce310486e06f7a12f1e43c46289911655, Linux

**Comment by jkraybill** [comment] 2020-02-21 23:07
This is a duplicate of #37504. I decided to hold off on fixing that one until after the current release, at it will be done as a side effect of fixing canning ratios on a larger scale.

**Closed** 2020-02-22 09:37 UTC
