### ISSUE TITLE
Feature request: Option for "store current wielded item in inventory" if you are attempting to wield an item larger than your inventory

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#15769] opened 2016-03-13 02:37 UTC
This is a little hard to explain, but I'll do my best.
Here's an example. I was in a mobile meth lab, wielding my Halligan bar. I picked up the chemistry set - but it was too big to fit in my inventory. The game asked if I wanted to drop my Halligan bar, but the bar would have fit just fine in my inventory (provided I wielded the chemistry set instead).
I was able to drop the Halligan bar and pick it back up immediately after wielding the chemistry set.

**Proposal:**
Maybe something like a holster activation's "store in inventory, drop, holster" menu when attempting to wield an item that you cannot fit in your inventory.

**Comment by BevapDin** [comment] 2016-04-24 11:35
This seems to be resolved already. Testing it gives two menus: first one allows to wield the item (or wear, if armor). If you choose to wield it, the next menu queries what to do with the currently wielded item, which allows storing in inventory, dropping or wearing.

Btw. there is a certain inconsistency: the second menu shows all three options, even if some of them are not available (can't wear a non-armor item). The first only shows those options if they are available.

**Comment by illi-kun** [comment] 2016-11-08 18:01
It seems to be a duplicate of #16637.

**Closed by illi-kun** 2016-11-08 18:01 UTC
Labels: Suggestion (Discuss)
