### ISSUE TITLE
Megastore errors on save load

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#34877] opened 2019-10-19 23:26 UTC
# Describe the bug

Updating from 9777 to 9778 or later, loading a save causes this errors:

```
DEBUG    : JSON contains circular dependency. Discarded 2 objects:
{
    "type": "overmap_terrain",
    "id": "megastore_entrance",
    "copy-from": "megastore_entrance",
    "name": "megastore",
    "sym": "M",
    "color": "i_magenta"
  },{
    "type": "overmap_terrain",
    "id": "megastore",
    "copy-from": "megastore",
    "name": "megastore",
    "sym": "m",
    "color": "i_magenta"
  },

 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 133
```

```

DEBUG    : Loaded bad ter! ter megastore

 FUNCTION : void overmap::unserialize(std::istream&)
 FILE     : src/savegame.cpp
 LINE     : 873

```

**Also the megastore on map becomes abandoned drive through.**

# Steps To Reproduce

1. load a save from 9775 or before on 9778 or later with megastore on map.

# Expected behavior

Stuff works.

# Screenshots

# Versions and configuration

# Additional context

[My save](https://mega.nz/#!0980kIYb!yJZbecsEYcr3wt8KDXRZt8Sq8IKzLEUXJlSJ7M8SfaM)

**Comment by ZhilkinSerg** [comment] 2019-10-19 23:36
Duplicate of #34860

**Closed by ZhilkinSerg** 2019-10-19 23:36 UTC
