### ISSUE TITLE
Massachusetts Mod Broken

### ISSUE THREAD

**Issue by ZerElRojo** [CleverRaven/Cataclysm-DDA#61870] opened 2022-10-22 21:17 UTC
### Describe the bug

This has been a problem for over two weeks and even after two updates, the mod isn't working still. It's one of my favorites and I'm disappointed that I and many people are unable to play this. The point of this mod is try to make Massachusetts a thing in CDDA and make more immersive in the lore, since some of us do roleplay in the game. 

I kept getting this error and even after today, after trying, it won't work. It's been two weeks. Please fix this ASAP.

### Steps to reproduce

1. Make a world with the Massachusetts Mod
2. Go through character creation
3. Choose a starting city.
4. Attempt to play

### Expected behavior

I would spawn in the desired city, in the desired location.

### Screenshots

![image](https://user-images.githubusercontent.com/116464332/197362663-3fcf727b-967c-4ee9-a46a-aa80f2dbf71d.png)

### Versions and configuration

n/a

**Comment by Leland** [comment] 2022-10-27 01:55
<img width="793" alt="image" src="https://user-images.githubusercontent.com/714017/198172731-92e565da-5771-48fe-9038-6f8c853ea2bb.png">

Can confirm. Ping @ZhilkinSerg – I get a bunch of JSON errors and then notices around no suitable locations.

**Comment by sonphantrung** [comment] 2022-10-30 09:41
Duplicate of #60477, fixed by #61601.

**Closed** 2022-10-30 12:49 UTC
Labels: <Bug>, (S2 - Confirmed), Mods, Character / World Generation

**Comment by Raiph-Benesz** [comment] 2022-12-17 04:27
I want to tackle this issue just to not just try out the Massachusetts mod, but offer my snobbery to whip you all into historical, architectural, geological, oceanographic, and cultural and social accuracy and plausibility for the US state known as Massachusetts.

I just want to turn Faneuil Hall into my own post-apocalypse palace already! Aye...
