### ISSUE TITLE
Game crash after killing enemy.

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#69408] opened 2023-11-15 11:11 UTC
### Describe the bug

Anytime I kill a zombie the game crashes the next move.

### Attach save file

n\a

### Steps to reproduce

kill zombie
pass or use a turn
crash

### Expected behavior

not crashing

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: b525b7a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: C:/Users/User/Downloads/cdda/config/crash.log
VERSION: b525b7a
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: debug_write_backtrace+0xb5@0,000,7FF,7A3,317,265[cataclysm-tiles.exe+0x557,265]), 
  #1
    (dbghelp: log_crash+0x377@0,000,7FF,7A3,2D9,487[cataclysm-tiles.exe+0x519,487]), 
  #2
    (dbghelp: signal_handler+0x57@0,000,7FF,7A3,2D9,A17[cataclysm-tiles.exe+0x519,a17]), 
  #3
    (dbghelp: raise+0x23e@0,000,7FF,7A4,82F,896[cataclysm-tiles.exe+0x1,a6f,896]), 
  #4
    (dbghelp: abort+0x18@0,000,7FF,7A4,81E,64C[cataclysm-tiles.exe+0x1,a5e,64c]), 
  #5
    (dbghelp: purecall+0x19@0,000,7FF,7A4,809,215[cataclysm-tiles.exe+0x1,a49,215]), 
  #6
    (dbghelp: map::visit_reachable_creatures<<lambda_10ea266d938d139fc2273e0ad46043a4> >+0x1f3@0,000,7FF,7A3,919,5E3[cataclysm-tiles.exe+0xb59,5e3]), 
  #7
    (dbghelp: monster::plan+0x96b@0,000,7FF,7A3,922,47B[cataclysm-tiles.exe+0xb62,47b]), 
  #8
    (dbghelp: `anonymous namespace'::monmove+0x6e0@0,000,7FF,7A3,320,640[cataclysm-tiles.exe+0x560,640]), 
  #9
    (dbghelp: do_turn+0x1,085@0,000,7FF,7A3,31E,D95[cataclysm-tiles.exe+0x55e,d95]), 
  #10
    (dbghelp: WinMain+0xc85@0,000,7FF,7A3,1A4,B75[cataclysm-tiles.exe+0x3e4,b75]), 
  #11
    (dbghelp: __scrt_common_main_seh+0x106@0,000,7FF,7A4,808,6CA[cataclysm-tiles.exe+0x1,a48,6ca]), 
  #12
    (dbghelp: BaseThreadInitThunk+0x14@0,000,7FF,B98,F57,344[KERNEL32.DLL+0x17,344]), 
  #13
    (dbghelp: RtlUserThreadStart+0x21@0,000,7FF,B99,262,6B1[ntdll.dll+0x52,6b1]),

**Comment by RenechCDDA** [comment] 2023-11-15 11:11
Duplicate of #69396

**Closed by RenechCDDA** 2023-11-15 11:11 UTC
Labels: (S1 - Need confirmation)
