### ISSUE TITLE
Regular but not guaranteeed segemetation fault with guns

### ISSUE THREAD

**Issue by Saaghh** [CleverRaven/Cataclysm-DDA#70245] opened 2023-12-16 12:51 UTC
### Describe the bug

Occasional segmentation faults.
My guess is that it's because of my weapon.
Sometimes all works fine, sometimes its guaranteed to crash. 
I think it's weapon becuse of crash log, i've tried throwing away gun and everything was fine without it.
But then I was playing with it again and it was fine.
And now its crashing again. So Im not sure what's the actual reason

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53139277/bab9f5eb-8328-4eb8-b8f6-f20b736d941d)

### Attach save file

[Austinville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13692598/Austinville-trimmed.tar.gz)

### Steps to reproduce

1. Load game
2. Press "w" to wield something or try to inspect held weapon "i"->"E"
3. Sometimes it happens when trying to shoot "f"

### Expected behavior

Game dont crush

### Screenshots

This weapon is causing crahses
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53139277/009def6a-916b-4ae8-bcc6-a3bfa87563e5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 067f6ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Hydroponics [hydroponics],
    Mind Over Matter [mindovermatter]
]

### Additional context

Crash log attached

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13692613/crash.log)

**Comment by GuardianDll** [comment] 2023-12-16 13:23
Duplicate of #70156

**Closed** 2023-12-16 13:29 UTC
Labels: (S3 - Duplicate)
