### ISSUE TITLE
Monster duplication when dropping corpses over a roof ledge

### ISSUE THREAD

**Issue by VincentRoyceMorgan** [CleverRaven/Cataclysm-DDA#49517] opened 2021-07-01 11:39 UTC
Description

I've been keeping a bunch of corpses for dissection in my truck cargo spaces for a while, since they don't rise up again. The thing is, once they've sat there for a while they reanimate the moment you take them out of the cargo space (As in, having the corpse be on a tile that's not storage. They won't reanimate if you wield them.)
Wanting to have the procedure be as safe as possible, I decided to take them up to the roof and drop them over the ledge. That way I could climb down on the other side of the structure and approach them as I would naturally spawning zombies.
What happened instead was the corpse would reanimate and float in midair, being fully functional except unable to walk. After killing it and climbing down the ledge to get to the corpse, I was met with another two copies of the same enemy (In that case a zombie technician. Was also tested with Shocker Zombies so I assume this happens for all enemies that reanimate.) One being immediately back up on their feet and the second copy rising up a couple of rounds later.

Steps To Reproduce:
1. Kill an enemy that reanimates. Normal, unpulped zombies are the most obvious example.
2. Store in any container for a while. Perhaps this in itself is unintended behavior, so consider this a mini bug report if you want.
3. Once the corpse has "broiled" for a while, wield it and take it up to a second storey floor or a roof with an available ledge.
4. Drop corpse over ledge using directional drop.
5. Become master of undeath and break the law of conservation of mass

Expected behavior:

To be fair, this works as intended if the corpse is pulped or freshly killed. As in, corpses fall to the ground as they should. It just so happens that if a corpse reanimated the moment it is dropped, it reanimates while still dropping a corpse down, which then reanimates as well. I don't know where the third enemy comes from, I'm guessing the game things the enemy fell down as well.

Versions and configuration:

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5861984 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap]

Additional context:

I understand that this has a lot to do with the fact that storing corpses in storage containers prevents them from reanimating as they should. Which in turn leads to their reanimate timer tick down to zero but unable to fire, so you basically prime the corpses for reanimation the moment they're on a free tile. I'm not sure if this is intended.
During the process of testing this before posting, I did find out that if you drop a primed corpse under your feet it doesn't stand up until you move out of the tile it's on. I guess that means that standing on top of an unpulped corspe is a viable way of preventing it from rising up again. I haven't tried doing this with other things like vehicles. I'm assuming items won't work.

**Comment by Saicchi** [comment] 2021-07-01 14:52
Most likely a duplicate of #48001

**Comment by VincentRoyceMorgan** [comment] 2021-07-01 15:04
> Most likely a duplicate of #48001

Pretty close, but I haven't had bodies getting duplicated when moving from vehicle storage to world tiles with advanced inventory. In this case vehicle storage is only used to tick down the revive timer without allowing the zombies to get back up. The duplication itself happens when I drop them from a ledge by using (D)irectional drop, not advanced inventory.

**Closed** 2021-07-19 05:21 UTC
Labels: <Bug>, <Exploit>, Monsters
