### ISSUE TITLE
Interaction menu with cows has duplicated shortcut letters assigned

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#51772] opened 2021-09-21 16:44 UTC
### Describe the bug

If you have attached a leash to a cow, the interaction menu has few items that have duplicated letters assigned to them, namely:

p is both for "Push cow" and "Lead cow by leash"
t is both for "Tie cow" and "Remove leash from cow"

### Steps To Reproduce

1. Have a cow, feed it cattle fodder so it is tamed
2. Attach a leash to it
3. Examine the menu

### Expected behavior

I expect the different options in this quite limited menu to have unique symbols that don't allow accidental duplication or leave question at what action was requested.

### Screenshots

![Screenshot from 2021-09-21 18-40-31](https://user-images.githubusercontent.com/25322782/134211824-6947cc16-8721-4592-ab40-2cd2385a9d50.png)

### Versions and configuration

Curses, experimental on Linux

**Comment by dseguin** [comment] 2021-09-21 19:55
This can be fixed with something along the lines of:
```diff
diff --git a/src/monexamine.cpp b/src/monexamine.cpp
index 364ce0b605..cac6993436 100644
--- a/src/monexamine.cpp
+++ b/src/monexamine.cpp
@@ -583,9 +583,9 @@ bool monexamine::pet_menu( monster &z )
     amenu.addentry( push_monster, true, 'p', _( "Push %s" ), pet_name );
     if( z.has_effect( effect_leashed ) ) {
         if( z.has_effect( effect_led_by_leash ) ) {
-            amenu.addentry( stop_lead, true, 'p', _( "Stop leading %s" ), pet_name );
+            amenu.addentry( stop_lead, true, 'P', _( "Stop leading %s" ), pet_name );
         } else {
-            amenu.addentry( lead, true, 'p', _( "Lead %s by the leash" ), pet_name );
+            amenu.addentry( lead, true, 'P', _( "Lead %s by the leash" ), pet_name );
         }
     }
     amenu.addentry( rename, true, 'e', _( "Rename" ) );
@@ -613,7 +613,7 @@ bool monexamine::pet_menu( monster &z )
     }
     if( z.has_effect( effect_leashed ) && !z.has_effect( effect_tied ) ) {
         amenu.addentry( tie, true, 't', _( "Tie" ) );
-        amenu.addentry( unleash, true, 't', _( "Remove leash from %s" ), pet_name );
+        amenu.addentry( unleash, true, 'T', _( "Remove leash from %s" ), pet_name );
     }
     if( !z.has_effect( effect_leashed ) && !z.has_flag( MF_RIDEABLE_MECH ) ) {
         std::vector<item *> rope_inv = player_character.items_with( []( const item & itm ) {
```

**Comment by UmbralReaper** [comment] 2021-09-22 06:32
Duplicate of #51290

**Closed** 2021-09-23 17:52 UTC
Labels: <Bug>, Good First Issue, Info / User Interface
