### ISSUE TITLE
Crash when firing turreted laser weapon.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#14528] opened 2015-12-20 16:43 UTC
Have a turret chassis mounted on car, with a Laser Cannon mounted on it. Manually fired it at a (normal) zombie, game crashed. Dump file attached.

Version: 4072 Windows-Tiles, with updated version of Blaze Vechile mod from forum.

[Crash-mdmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/67867/Crash-mdmp.zip)

**Comment by drayath** [comment] 2015-12-20 18:17
Fixed in 4075 (I presume by  'Change order of events in player::fire_gun #14525')

**Comment by mugling** [comment] 2015-12-20 21:25
Duplicate of #14524

**Closed** 2015-12-21 09:11 UTC
