### ISSUE TITLE
Character Point Pool Balance

### ISSUE THREAD

**Issue by Name1essLord** [CleverRaven/Cataclysm-DDA#74125] opened 2024-05-26 21:21 UTC
### Is your feature request related to a problem? Please describe.

I decided to tell this because the character's points are not balanced so far, I ask you to balance them.

### Solution you would like.

I'm asking you to balance your character's points because this is a pretty important part for fair play in Cataclysm DDA, and they're still not balanced!!

**Comment by NetSysFire** [comment] 2024-05-26 21:34
Duplicate of #70031. And lacks vital details.

**Closed by NetSysFire** 2024-05-26 21:34 UTC
Labels: <Suggestion / Discussion>
