### ISSUE TITLE
Flesh Out Factions

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#45148] opened 2020-10-29 22:10 UTC
Building Your own faction in Cataclysm is not currently fleshed out, (Note: this might not be possible with current resources, but probably will be by 0.G or even 0.H)

# Describe the solution you'd like
Faction Wars- In game factions can go to war with each other
Different Economies for NPC cities- certain factions will value certain objects over others
Faction-Based Items- Factions will have their own weapons and life styles, including cult shrines
Reputation- Joining one Faction will lower your reputation with other opposing factions

# Describe alternatives you've considered
Creating a mod or Fork with the above features( although I'm not good at programming and also I'm not even sure this is possible currently)

**Comment by Theawesomeboophis** [comment] 2020-10-29 22:12
Probably not possible currently, but would be awesome to see I think.

**Comment by dissociativity** [comment] 2020-10-30 04:48
the issue is, framework for NPCs doing anything beyond walk around the map and give you quests, grab loot and be incompetent in combat doesn't really exist beyond the needs framework kevin is developing.
Lots of optimisations have been merged and are coming, so there's at least leftover cpu headroom for such features, but until someone actually codes these things, they won't exist.

As of right now I believe you could entirely in json, create static locations that one of exist like the refugee shelter, have quests that affect faction relations, ect, have fairly complex dialogue trees and reasonably complex quests, with no programming knowledge.

If you wish to contribute to this, I'm confident you could make some NPCs and a basic faction base with quests that have political consequences currently, just the other things are currently out of scope.

**Comment by Theawesomeboophis** [comment] 2020-10-30 11:00
That's why I said this probably isn't possible in the current version.

**Comment by Theawesomeboophis** [comment] 2020-10-30 14:45
I created my own fork if anyone wants to contribute to the above features.

**Comment by I-am-Erk** [comment] 2020-10-31 01:32
I would say the overall issue here, "flesh out factions" is too vague and huge for a single issue. Take a look at https://github.com/CleverRaven/Cataclysm-DDA/projects/21 and https://github.com/CleverRaven/Cataclysm-DDA/projects/20 for a lot of the details involved in the shorter term though.

If you'd like you could generate an issue with some suggestions for near term faction camp improvements, such as other expansions we could add

**Closed by I-am-Erk** 2020-10-31 01:32 UTC
