### ISSUE TITLE
desert_test loading broken again

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20252] opened 2017-02-10 19:41 UTC
`desert_test` overmap type ("biome") isn't loaded until a game is loaded and as such it isn't accessible in main menu.
Additionally it seems that even after it is loaded, the world option settings sometimes (context-dependent? main menu only? not-main-menu only?) doesn't allow switching to it.

Do we even want desert test map working for 0.D? It is clearly bugged at the moment and it is not possible to neatly fix #16390 on a desert map without wrapping the whole thing into a mod (thus making it much harder to actually load this type of overmap).

**Comment by WizardOfOoo** [comment] 2017-02-10 20:34
I thought it was disabled?

**Comment by kevingranade** [comment] 2017-02-11 02:16
> Do we even want desert test map working for 0.D?

Not really, it doesn't accomplish anything and probably should have been
developed on a feature branch.

**Comment by WizardOfOoo** [comment] 2017-02-11 02:28
I'd much prefer asphalt world.  I want to ride forever, shiny and chrome.

**Comment by Coolthulhu** [comment] 2017-02-13 02:15
> How about it gets moved to a mod

Nope - I said in first post why not.

**Comment by WizardOfOoo** [comment] 2017-02-13 02:43
> Nope - I said in first post why not.

I'm sorry, I didn't read the OP. You are correct.

**Comment by DangerNoodle** [comment] 2017-02-25 01:34
It appears that it has been removed entirely since this issue was opened, as I am unable to find desert_test in the JSON files.

**Comment by Leland** [comment] 2018-02-21 02:27
Closing per above

**Comment by Leland** [comment] 2018-03-29 03:20
JSON is in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/test_regions.json

And can reproduce: `desert_test` is only an option in world gen if one selects it as the default in settings.

**Comment by Night-Pryanik** [comment] 2019-11-17 16:19
`desert_test` default region type can be selected - both in game settings and while creating a new world. Worlds with this region type are perfectly playable and are created without any errors.

Should be closed?

**Closed** 2019-11-18 06:50 UTC
Labels: (S2 - Confirmed), <Bug>, Mapgen
