### ISSUE TITLE
Crash while trying to set amount of ammo reloaded

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#22276] opened 2017-10-27 18:42 UTC
Game version: 6891

Operating system: Win 7 X64
Tiles or curses: Tiles

Mods active: Default mods

There option to reload weapon not with full ammo but with part of it. But it cause hard crash if you even try to press cursos left or right on releoad source selection screen.

### Expected behavior
Amount ammo to reload changed.

### Actual behavior
Game crashed.

### Steps to reproduce the behavior
1) Get loaded glock with loaded magazine and one extra magazine.
2)  Do shot with glock for few times.
3) Try to reload it. You will see defaul reload screen which allow you to select ammo source and reload quantity.
4) Press Cursor left or Cursors right to change reload quantity.
5) You got crash immdietelly.

**Comment by Night-Pryanik** [comment] 2017-10-28 04:46
Dupe of #20843.

**Closed by Night-Pryanik** 2017-10-28 04:46 UTC
