### ISSUE TITLE
Hunting Lodge Generation Failure

### ISSUE THREAD

**Issue by EmpressWynnter** [CleverRaven/Cataclysm-DDA#50578] opened 2021-08-07 22:07 UTC
### Describe the bug

Hunting Lodge location fails to properly generate, throwing an error when coming within several overmap tiles, and leading to awkward/missing terrain generation. Basement is slightly mangled, and 2nd floor is missing in the example below.

### Steps To Reproduce

1. Use overmap editor to generate the various parts of a hunting lodge outside the explored region.
2. Teleport nearby hunting lodge.
3. Explore Lodge.

### Expected behavior

Expecting second floor to generate, and basement to be as navigable as similar structures are.

### Screenshots

![huntinglodge_2f](https://user-images.githubusercontent.com/86111552/128614819-e1f00946-9630-4c84-a477-6766fd95b88b.PNG)
![huntinglodge_bf](https://user-images.githubusercontent.com/86111552/128614934-fba1fd85-4ae8-49f4-ab43-5a28729604b5.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: bcb8e7f
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, package_bionic_professions, Graphical_Overmap, extra_mut_scens, crt_expansion, blazeindustries, cbm_slots

### Additional context

 DEBUG    : place_items: invalid item group 'straw_doll', om_terrain = 'lodge_basement_residential1_west' (lodge_basement_residential1)

 FUNCTION : std::vector<item*> map::place_items(const item_group_id&, int, const tripoint&, const tripoint&, bool, const time_point&, int, int)
 FILE     : src/mapgen.cpp
 LINE     : 5254
 VERSION  : bcb8e7f

**Comment by actual-nh** [comment] 2021-08-07 22:16
Ping: @Maleclypse?

**Comment by actual-nh** [comment] 2021-08-07 22:27
BTW, `straw_doll` and `straw_pile` appear to need their material entry fixed - currently `paper`, should be `dry_plant`. (Almost identical - except you can use paper to repair, well, paper.)

**Comment by Maleclypse** [comment] 2021-08-09 23:03
I thought I fixed this.  I wonder if I didn't copy over all the fixes into my PR...

**Comment by hexagonrecursion** [comment] 2021-08-19 14:43
* Missing 2nd floor: duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50255
* invalid item group 'straw_doll': duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50647 fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/50684

**Closed** 2021-08-19 15:13 UTC
Labels: <Bug>, [JSON], Map / Mapgen
