### ISSUE TITLE
Can't start vehicle construction, no more option in construction menu

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17443] opened 2016-07-01 01:49 UTC
Have vehicle with welding rig, always used it to weld, also cart nearby with steel frames. When opening construction menu by pressing `*` there is no option `Start Vehicle Construction` at all.

Build 5165

**Comment by Soyweiser** [comment] 2016-07-01 02:20
Was still working in 5163 for me.

**Comment by mugling** [comment] 2016-07-01 11:08
Can reproduce

**Comment by BevapDin** [comment] 2016-07-01 11:11
If you onto this, I assume it's because the requirement is initially empty and is therefor removed by the blacklisted-item-removal code. The actual requirement is added later based on a vehicle part flag.

**Comment by mugling** [comment] 2016-07-01 11:14
Yes I'm on it and just found the problem described above in `finalize_constructions()`

**Comment by mugling** [comment] 2016-07-02 20:21
Fixed by #17451 and #17487

**Closed by mugling** 2016-07-02 20:21 UTC
Labels: Bug, Priority, validated
