### ISSUE TITLE
Incorrect Sight POV

### ISSUE THREAD

**Issue by Velreena** [CleverRaven/Cataclysm-DDA#68304] opened 2023-09-24 23:13 UTC
### Describe the bug

Didn't have this issue a couple months ago but now (at random) the sight that would be my character's pov becomes randomly positioned somewhere further ahead which is annoying for one but also gives me vision inside or outside buildings which is just unplayable. I tried different recent builds over the past 2 weeks but only from about the builds made a month ago is this bug not present. Tried new saves with no mods and even changing up the tileset to see if that would help but yeah it did not. Even ascii is bugged with it.

### Attach save file

[Discovery Bay-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12709843/Discovery.Bay-trimmed.tar.gz)

### Steps to reproduce

Literally just walk until it happens. Touching the mouse or making any action while the bug is in effect fixes it for that turn until it comes back.

### Expected behavior

To have the sight pov of my character as it's been forever

### Screenshots

First pic is when my pov is normal and the 2 others are the bug
<img width="504" alt="image" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/145940539/66cfa415-4177-4b70-a919-610b252bc9c4">
<img width="830" alt="Screenshot 2023-09-24 155948" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/145940539/bd8e6979-9563-4ccc-ab4d-92f2f3b38179">
<img width="744" alt="image" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/145940539/1f2d7b2a-912a-45ea-bc48-7a5530803e5d">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 97d2682 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by RenechCDDA** [comment] 2023-09-24 23:19
Duplicate of #68121

**Closed by RenechCDDA** 2023-09-24 23:19 UTC
Labels: (S1 - Need confirmation)
