### ISSUE TITLE
Unable to reload anesthetic kit with anesthetic.

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40522] opened 2020-05-13 12:43 UTC
# Describe the bug

You can craft [anesthetic](http://cdda.chezzo.com/anesthetic/craft), but you won't be able to put them into anesthetic kits. If you unload anesthetic kits, you get `none` instead of anesthetic.

Likely related to #40399.

# Steps To Reproduce

1. Make a player with a full gallon jug of anesthetic, and an empty anesthetic kit.
2. `r`eload, select anesthetic kit, `enter`
3. :thonk:

# Expected behavior

Anesthetic is taken out of the gallon jug and put into the kit.

# Screenshots

Unable to the reload anesthetic kit despite wielding a gallon jug of anesthetic!

![image](https://user-images.githubusercontent.com/21962421/81813306-26081000-94dc-11ea-825c-71d7573b9559.png)

The jug contains 1080 charges of anesthetic.
![image](https://user-images.githubusercontent.com/21962421/81813405-4637cf00-94dc-11ea-88de-52cc8c4815d2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

**Comment by KorGgenT** [comment] 2020-05-13 15:16
yeah this might be a duplicate of at least one of the issues that PR fixes

**Comment by Eminence120** [comment] 2020-05-13 15:59
I have seen this behavior with other loadable items as well including but not limited to:

Misc Repair Kit
Wooden Sewing Needle
Charcoal Smoker

In every case I have the item either wielded or on the ground. I have disabled all mods and created a fresh character to reproduce the issue on build .E ellison 10478

**Closed** 2020-05-25 07:49 UTC
Labels: (S3 - Duplicate)
