### ISSUE TITLE
Examining NPC's dropped weapon after killing them gives error

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#38225] opened 2020-02-22 07:55 UTC
# Describe the bug

Get error when picking up a dropped npcs weapon after killing them

# Steps To Reproduce

1. Spawn npcand immediately chat with them and get them to drop their weapon immediately
2. Kill said npc
3. Try to pick up the dropped weapon
4. Error

# Expected behavior

No error

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12476-gfef327b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]
Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by wapcaplet** [comment] 2020-02-22 16:30
Duplicate of #37339

**Comment by davidpwbrown** [comment] 2020-02-25 14:54
Different issue, this one is still valid, the other isnt.
When an NPC drops a weapon, it retains their ownership, and when they die, it only removes the ownership on the items they have on their inventory.

The fix for this would be to either just silently remove ownership on examine when the faction is discovered to be nonvalid.

**Closed** 2020-02-26 08:33 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities, NPC / Factions
