### ISSUE TITLE
Mission Download Encryption Codes console spawning

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48306] opened 2021-04-01 13:35 UTC
# Describe the bug

Refugee center mission "Download Encryption Codes" spawned 2 computer consoles in front of refugee center after accepting the mission. These could then be used to complete the mission without finding a lab.

# Steps To Reproduce

1. Accept "Download Encryption Codes" mission.
2. Look for nearby spawned computer consoles.

# Expected behavior

Computer consoles in a lab, not in front of refugee center doors.

# Screenshots

![consoles](https://user-images.githubusercontent.com/81636323/113301969-e3237680-92ff-11eb-8035-6616d0831de1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

**Comment by PatrikLundell** [comment] 2021-04-02 08:14
Happened to me as well in 0.E2 stable. I used the terminals after having verified that no terminals were spawned in the lab indicated (I've reported this in an older thread).

**Comment by Night-Pryanik** [comment] 2021-04-04 13:44
Duplicate of #27618.

**Closed by Night-Pryanik** 2021-04-04 13:44 UTC
Labels: <Bug>, Map / Mapgen, Missions
