### ISSUE TITLE
crash and unabel to load in saves

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#29746] opened 2019-04-19 21:24 UTC
**Describe the bug**  
i update my game to the newest version 0.D-1990-g73d8779 (tiles) to prevent bug with water that got fixt. After i lanch the game i wanted to load in one of my 6 games (this game i was realy far in) i tryd and the save won't load do to a error and after 5 times trying the game just crashed out of no where.

**To Reproduce**  
1. Have a world and a charctor saved bevoor the newist update .
2. Try to load in the save file.
3. try to load if 5 times and then quit
[The real world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3099341/The.real.world.zip)

 (the crash may or may not happen i don't know what was the real trigger).

**Expected behavior**  
i expected to lanche the game load in save file and just keep going 

**Screenshots**  
![bug_CDDA](https://user-images.githubusercontent.com/25956554/56444226-27c2cc80-62f8-11e9-9fa1-907dc6c9082a.png)
![crash_CDDA](https://user-images.githubusercontent.com/25956554/56444243-36a97f00-62f8-11e9-9549-ca79537a6240.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1990-g73d8779 
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Bens GF recipes,Craft Ammo mags & belt links, Extended realistic guns, Craft ammo mags - ERG, Deadleaves' Fictional guns, Garden Pots, Icecoon's Arsenal, Makeshift items mod, Medieval and Historic Content, Draco's Dog Mod, Modular turrets, Pks rebalancing, salvagd robots, mining mod, mutant NPCs, Mythical Martial arts, More locations, Fuji's more buildings, More city locations, Urban development, Boats, Folding parts pack, Vehicle additions pack, Tank and other vehicles, Artyoms' gun emporium - reloaded, EXTENDED_BUILDINGS, Whaleys Big ol' building pack, No ants, No bees, No fungal monsters, Classes and scenarios mod, Classic roguelike classes, Manual bionic installation, sleep deprivation, StatsThroughSkills

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by ifreund** [comment] 2019-04-19 22:54
duplicate of #29732

**Closed by ifreund** 2019-04-19 22:54 UTC
