### ISSUE TITLE
Cats die when player lights stove

### ISSUE THREAD

**Issue by failboat78** [CleverRaven/Cataclysm-DDA#75796] opened 2024-08-18 14:05 UTC
### Describe the bug

After lighting the stove I notice a strange red patch. It seems all the cats have managed to somehow "die in a fire". 

Also - should things really leave a puddle of blood when "dying in a fire"?

### Attach save file

[Coachella-trimmed.tar.gz](https://github.com/user-attachments/files/16648952/Coachella-trimmed.tar.gz)

### Steps to reproduce

Light the stove.
Wander around a bit. 
See what happens to cats.

### Expected behavior

Not dead cats?

Cats enjoying the warmth from safe distance? 

### Screenshots

![image](https://github.com/user-attachments/assets/f3773bce-bfa0-4915-aca4-c102905fbb91)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-08-17-2035 760786a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]

**Comment by Karol1223** [comment] 2024-08-19 11:09
Duplicate of #73674

**Closed** 2024-08-19 11:10 UTC
Labels: (S3 - Duplicate), Monsters
