### ISSUE TITLE
Crashing near buildings

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#34403] opened 2019-10-02 19:22 UTC
# Describe the bug
Game reliably crashes when approaching, or exiting buildings. However, some 'buildings' aren't effected by this crash (ie: Campsites, Motels, and Mines)

# Steps To Reproduce

1. Make a player.
2. Approach, or attempt to exit a building (Tested Prison, House, Grocery Store, and Evac Shelter).
3. Game will crash.

# Expected behavior
Game shouldn't crash.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-8159-g6363709 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8159-g6363709
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5B3385[cataclysm-tiles.exe+0x1B3385]
    @0x5B3E52[cataclysm-tiles.exe+0x1B3E52]
    SMPEG_error+0x4B034@0xF866F0[cataclysm-tiles.exe+0xB866F0]
    _C_specific_handler+0x98@0x7FFF8D9F7C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFF905BF7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFF9052D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFF905BE70E[ntdll.dll+0x9E70E]
    @0x95654D[cataclysm-tiles.exe+0x55654D]
    @0x6E22EC[cataclysm-tiles.exe+0x2E22EC]
    @0x6E4E34[cataclysm-tiles.exe+0x2E4E34]
    IMG_LoadWEBP_RW+0x61A528@0x1692A88[cataclysm-tiles.exe+0x1292A88]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFF90104034[KERNEL32.DLL+0x14034]
    RtlUserThreadStart+0x21@0x7FFF90593691[ntdll.dll+0x73691]

**Comment by Proxiehunter** [comment] 2019-10-02 19:38
I had a segfault error when moving during a start at the top of a building.

**Comment by Muffindrake** [comment] 2019-10-02 19:46
0.D-8159-g636370985c ncurses - crashes instantly if I attempt to move in an existing save. That particular save was me currently situated in the garage of a survivor house (the one with the mines).

**Comment by ZhilkinSerg** [comment] 2019-10-02 20:29
Duplicate of #34397

**Closed by ZhilkinSerg** 2019-10-02 20:29 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>
