### ISSUE TITLE
Advanced Inventory item duplication

### ISSUE THREAD

**Issue by xyder** [CleverRaven/Cataclysm-DDA#11999] opened 2015-04-12 22:52 UTC
The way this could be replicated is by having a tab set to [A]ll and moving items from a vehicle (source is VH). If the specific tile is selected instead of [A]ll then it behaves normally.
The other tab doesn't seem to matter.

**Comment by Oskar636** [comment] 2015-04-14 20:03
I just had sort of the same issue, except it's easier to reproduce. Just open the AIM tab, have any item next to you, then have one tab set to the tile with the item, and one on the "items worn' tab. Try to move it. There you go, thousands of wheels in your backpack xD

**Comment by nonymous** [comment] 2015-04-17 17:33
I just upgraded to linux curses 3010 and I'm seeing item dupe, loss, and re-organization in AIM.  The last one is the most annoying because I keep accidentally picking up tainted meat or other stuff I don't want in my inventory.  AIM no longer remembers my last pane selection settings too which makes filling this shopping cart a chore.

**Comment by xyder** [comment] 2015-04-17 19:00
I've noticed the re-organization as well. Whenever I move items one at a time from one pane to the other it changes the order of the item I have selected to next one I think.

**Comment by TranquilMarmot** [comment] 2015-04-18 06:09
You also can't move things from one vehicle spot to another (they are both `VH`).

It's also really irritating that it defaults to looking at what's on the ground when I almost always want to be looking at what's in the vehicle.

**Comment by dvolk** [comment] 2015-04-22 06:55
This isn't fixed in #11998

**Comment by Coolthulhu** [comment] 2015-04-22 07:13
I did update #11998 a bit before merging it.
I can't replicate the bug in the newest binary, though I may be doing something wrong.

Here's what I did:
* Put item in vehicle part
* Change tabs so that one is [A]ll, the other is anything but the vehicle
* Try to move the item
* Item is moved as expected

**Comment by dvolk** [comment] 2015-04-22 08:18
I can reproduce it consistently:

- new game
- spawn vehicle
- put any item in vehicle
- open AIM (the panes should be All and Inventory)
- move item with 'm'

It seems that changing panes sometimes fixes it (something isn't initialized?), but the above always reproduces the cloning.

**Closed** 2015-04-22 23:03 UTC
Labels: Bug
