### ISSUE TITLE
Mines occasionally spawn hordes of miner zs across several map tiles

### ISSUE THREAD

**Issue by garnetgw** [CleverRaven/Cataclysm-DDA#74715] opened 2024-06-22 08:44 UTC
### Describe the bug

Sometimes, mines will spawn with a very large number of zombie miners stretching across the map away from the mine as many as 15 tiles.

### Attach save file

[Ipava-trimmed.tar.gz](https://github.com/user-attachments/files/15935851/Ipava-trimmed.tar.gz)

### Steps to reproduce

1. Create a default setting world and load a character.
2. Debug reveal map and teleport to mines until you find one surrounded by a horde of zombie miners

### Expected behavior

Surface level mines spawn a reasonable amount of zombie miners within the fenceline.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/58456510/028ffb24-94c0-46ad-8b04-a9082497ecdb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-06-21-0140 d1fe2af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment] 2024-06-22 13:38
This may be caused by the same bugs as #74697, in which case it should be fixed by #74703. However, I should try to test that.

**Comment by PatrikLundell** [comment] 2024-06-22 14:50
/Confirmed

The hordes at the surface is a separate problem from that #74703 addressed, as it appears with that code as well.

What I think is happening is that the miners that should be in the tunnels end up on the surface, which is basically the opposite of the problem that PR addressed. Oddly enough, a small number of zombies are still found in the tunnels.

**Closed** 2024-06-23 03:03 UTC
Labels: (S2 - Confirmed)
