### ISSUE TITLE
Everyone but the player can make diagonal reach attacks

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65699] opened 2023-05-17 19:03 UTC
### Describe the bug

So the player's reach attack space looks like this:
X 0 0 0 X
0 0 0 0 0
0 0 @ 0 0
0 0 0 0 0
X 0 0 0 X
The player cannot reach diagonally and hit the corners.
However every other thing in the game, including other NPCs, can.

### Attach save file

n/a

### Steps to reproduce

1a. Spawn a cunning feral.
2a. Kite it diagonally.
3a. Watch it make a reach attack while diagonally two spaces away from you.

1b. Spawn an npc with a spear (or use refugee center guards)
2b. Spawn enemies for them to fight.
3b. watch them make diagonal reach attacks.

### Expected behavior

Reach attacks should be consistent for the player and for non-player entities.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: a4f928b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by RenechCDDA** [comment] 2023-05-17 20:49
Duplicate of #65266

**Closed** 2023-05-17 20:50 UTC
Labels: (S1 - Need confirmation)
