### ISSUE TITLE
The effect of bodytemp_modifiers does not match the doc description

### ISSUE THREAD

**Issue by zwa73** [CleverRaven/Cataclysm-DDA#52940] opened 2021-11-21 08:17 UTC
https://github.com/CleverRaven/Cataclysm-DDA/issues/46999
Not just the documentation, all mutations seem to adopt this design  [low,high]

file search with 0F-2 version
  F:\CDDA\cataclysmdda-0.F-Windows_x64-Tiles-0.F-2\data\json\mutations\mutations.json (20 hits)
	Line 2082:     "bodytemp_modifiers": [ 50, 100 ],
	Line 2102:     "bodytemp_modifiers": [ 300, 800 ],
	Line 2117:     "bodytemp_modifiers": [ 250, 500 ],
	Line 2132:     "bodytemp_modifiers": [ 750, 1500 ],
	Line 2153:     "bodytemp_modifiers": [ 750, 1500 ],
	Line 2174:     "bodytemp_modifiers": [ 750, 1500 ],
	Line 2194:     "bodytemp_modifiers": [ 500, 1000 ],
	Line 2222:     "bodytemp_modifiers": [ 125, 250 ],
	Line 2256:     "bodytemp_modifiers": [ 250, 500 ],
	Line 2404:     "bodytemp_modifiers": [ 100, 150 ],
	Line 2426:     "bodytemp_modifiers": [ 150, 250 ],
	Line 2448:     "bodytemp_modifiers": [ 150, 250 ],
	Line 4232:     "bodytemp_modifiers": [ 200, 200 ],
	Line 5193:     "bodytemp_modifiers": [ -250, -250 ],
	Line 5206:     "bodytemp_modifiers": [ -750, -750 ],
	Line 5219:     "bodytemp_modifiers": [ -1500, -1500 ],
	Line 5435:     "bodytemp_modifiers": [ 250, 250 ],
	Line 5445:     "bodytemp_modifiers": [ 750, 750 ],
	Line 5456:     "bodytemp_modifiers": [ 1500, 1500 ],
	Line 6119:     "bodytemp_modifiers": [ 500, 750 ],

我确定这些是正面效果
但现在因为程序原因显然这只会让你在过热时更热
--------------- Google Translate  --------------------
I'm sure these are positive effects
But now because of the program, obviously this will only make you hotter when overheating

default mutation
{
    "type": "mutation",
    "id": "FEATHERS",
    "name": { "str": "Feathers" },
    "points": 2,
    "visibility": 10,
    "ugliness": 3,
    "bodytemp_modifiers": [ 50, 100 ],
    "description": "Iridescent feathers have grown to cover your entire body, providing a marginal protection against attacks and minor protection from cold.  They also provide a natural waterproofing.",
    "types": [ "SKIN" ],
    "leads_to": [ "DOWN" ],
    "prereqs": [ "SKIN_ROUGH" ],
    "category": [ "BIRD" ],
    "armor": [
      {
        "parts": [ "torso", "head", "arm_l", "arm_r", "hand_l", "hand_r", "leg_l", "leg_r", "foot_l", "foot_r", "mouth" ],
        "bash": 1
      }
    ]
  },
and third party mod 'arcana'
(i used https://cdda.aloxaf.cn/mutation/ARCANA_INNERFIRE data)
{
    "type": "mutation",
    "id": "ARCANA_INNERFIRE",
    "name": {
        "str": "内火"
    },
    "points": 2,
    "mixed_effect": true,
    "bodytemp_modifiers": [
        250,
        1000
    ],
    "bodytemp_sleep": 250,
    "description": "你身体深处那股奇怪的温暖变得更加强烈，它的影响也变得更加明显。当你还需要多吃多喝的时候，你的耐力和治疗能力已经适应了。一种奇怪的光芒也可以在你的喉咙后面隐约可见，给你的每一句话都带来一种不自然的威胁。",
    "valid": false,
    "purifiable": false,
    "prereqs": [
        "ARCANA_INNERHEAT"
    ],
    "changes_to": [
        "ARCANA_DRAGONFIRE"
    ],
    "leads_to": [
        "ARCANA_FIREAFFINITY",
        "ARCANA_TOXINIMMUNE"
    ],
    "category": [
        "DRAGONBLOOD"
    ],
    "types": [
        "METABOLISM"
    ],
    "metabolism_modifier": 0.5,
    "stomach_size_multiplier": 2,
    "thirst_modifier": 0.5,
    "healing_awake": 1,
    "healing_resting": 0.5,
    "mending_modifier": 2,
    "stamina_regen_modifier": 0.666,
    "social_modifiers": {
        "persuade": -25,
        "intimidate": 25
    },
    "vitamin_rates": [
        [
            "blood",
            2
        ],
        [
            "redcells",
            2
        ]
    ],
    "repo_id": 23034,
    "original_id": "ARCANA_INNERFIRE",
    "modname": "arcana"
}

**Comment by ZhilkinSerg** [comment] 2021-11-21 10:33
No need to open a new issue in case you already have one opened previously for the same bug/problem - you can just update the previously opened issue with additional details.

As for any third party mods - obviously we do not support them here.

**Comment by wapcaplet** [comment] 2021-11-21 13:45
Closing as a duplicate of #46999 and referenced there.

**Closed by wapcaplet** 2021-11-21 13:45 UTC
