### ISSUE TITLE
Focus drops to 1 while crafting and reading.

### ISSUE THREAD

**Issue by cobianic** [CleverRaven/Cataclysm-DDA#47228] opened 2021-02-04 15:23 UTC
# Describe the bug

Focus drops to 1 when: 
- crafting item every 40 minutes
- trying to terminate craft by pressing "." (only happens in Main_save)
- after finishing studying a spell from the book from Magiclysm (30 minutes/hour/2 hours etc)

# Steps To Reproduce

- Continue craft an item from any save
- Study a spell the Magiclysm book from save with Magiclysm
- Terminate craft

# Expected behavior

No focus drops

# Screenshots

# Versions and configuration

Test_world:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9372-gf2bb834-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

Test_world_with_Magyclism:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9372-gf2bb834-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

Main_save:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9372-gf2bb834-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Wandering Masters [wandering_masters],
    Bionic Space Expander [Bionic_Space_Expander],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Cataclysm++ [Cata++],
    Mutant NPCs [mutant_npcs_new],
    Crazy Cataclysm [crazy_cataclysm_alt],
    Blazemod - Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Arcana - UndeadPeople Tileset [ArcanaUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Medieval Mod Reborn - UndeadPeople Tileset [Medieval_Mod_RebornUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Secronom - UndeadPeople Tileset [secronom_UDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Before I was at build 11423 or 11424, same error there

[Test_world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5926113/Test_world.zip)

[Test_world_with_Magyclism.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5926622/Test_world_with_Magyclism.zip)

[Main_save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5926627/Main_save.zip)

**Comment by BrettDong** [comment] 2021-02-04 15:51
Should be fixed by #47186

**Comment by Zireael07** [comment] 2021-02-04 15:52
EDIT: Ninja'd!

**Comment by anothersimulacrum** [comment] 2021-02-04 17:14
Duplicate of #47006

**Closed by anothersimulacrum** 2021-02-04 17:14 UTC
