### ISSUE TITLE
Items inside containers are in the category "container" instead of their category

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#41509] opened 2020-06-22 14:03 UTC
# Describe the bug
Items within bags/jugs etc. will not be classified as the item in question but as "category: container". Which leads to problems with sorting. If you want to sort food into a fridge you can't do it, while it is in a jug or bottle or bag, because it will sort it to the container stuff.

# Steps To Reproduce
1. Have an item inside a container.
2. Check its category

# Expected behavior
pack of cigarettes should be a "drug" not container.

# Screenshots

![grafik](https://user-images.githubusercontent.com/33199510/85296550-dedd4980-b4a1-11ea-864c-72f3c02ecc77.png)
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3407-g845884a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Fewer Farms [Fewer_Farms],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Alternative Map Key [alt_map_key]
]

# Additional context

**Comment by GGgatherer** [comment] 2020-06-22 14:12
Bag **is** a container. In category view or AIM you should see both your food (cracklins in this case) under "food" category, and container with it under "containers" category. So you can decide if you want to put just the food or the bag with food into a fridge.
The only problem I see with this system is that it also applies to liquids. Noone in their right mind would want to spill a drink into food storage zone, which could be easily done by "putting" it there (instead of a container with that liquid).

**Comment by Lamandus** [comment] 2020-06-22 14:18
It should still be in the category of the item inside. Else you have to unpack it all to put it in the right stash (or fridge). Because now, I need to manually put the full bottles of drinks into the fridge myself instead of it automatically doing it. The way it is now, the sorting is now more or less semi useless for food and drinks, because it won't get into the place it is supposed to.

**Comment by bloodraven983** [comment] 2020-06-22 14:48
annoying thing because instead of tab select the whole food category I have to carefully select every food item in the container category

**Comment by KorGgenT** [comment] 2020-06-22 15:09
which item that's inside the container should get the priority for the category
if you have a backpack with all of your stuff, what's its category

This is the reason it is how it is. It is because i do not have an answer and i don't think "just make the bag the category of the item inside" is the correct answer

**Comment by KorGgenT** [comment] 2020-06-22 15:55
Also this is a duplicate of #41388
So additional discussion should go there

**Closed by KorGgenT** 2020-06-22 15:55 UTC

**Comment by Lamandus** [comment] 2020-06-22 16:33
> 
> 
> Also this is a duplicate of #41388
> So additional discussion should go there

actually no. but okey... they talk about the problem of container and contaiment being in different categories. I am talking about the sorting issue, because the container is the category and not its content...

**Comment by KorGgenT** [comment] 2020-06-22 16:41
at its core they are the same issue: containers do not share the category of their contents

**Comment by wapcaplet** [comment] 2020-06-23 04:49
I don't understand why this issue was closed. It looks like a very distinct issue from #41388 - the bug there had to do with multi-drop. The bug in this issue has to do with sorting items, specifically (as I interpret it), auto-sorting loot piles.

To reproduce:

1. Using zone manager, add zones for containers, food, and drink (and unsorted)
2. Drop a pile of food and drink in containers onto the unsorted zone
3. Use `O`, `o` to auto-sort - all food and drink goes into the "containers" zone

Zones after sorting - food and drink did not go into the appropriate zones:

![image](https://user-images.githubusercontent.com/238395/85361971-8e361280-b4da-11ea-9bc6-b5a4b4dd1ee8.png)

![image](https://user-images.githubusercontent.com/238395/85361999-9d1cc500-b4da-11ea-8dfb-1b3a90d76bb1.png)




- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-3463-gae2aa534a6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
