### ISSUE TITLE
Subway stairwells not linked correctly

### ISSUE THREAD

**Issue by failboat78** [CleverRaven/Cataclysm-DDA#76450] opened 2024-09-15 10:09 UTC
### Describe the bug

The upstairs/downstairs of the stairwell in this subway station are not linked correctly. 

### Attach save file

[Sunnydale-trimmed.tar.gz](https://github.com/user-attachments/files/17005341/Sunnydale-trimmed.tar.gz)

### Steps to reproduce

Test each of the stairwells here by going up/down - only one of them works as expected. 

### Expected behavior

Player going up/down a stairwell should appear in the appropriate stairwell of the other level.

### Screenshots

![image](https://github.com/user-attachments/assets/307ca6ad-1ad3-4d9c-b541-fa063ff73eca)
![image](https://github.com/user-attachments/assets/e9838c92-35bf-42be-ba3e-ca64ee371747)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-09-15-0626 1925be0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]

**Comment by Procyonae** [comment] 2024-09-15 13:51
Duplicate of #68957

**Closed by Procyonae** 2024-09-15 13:51 UTC
Labels: (S3 - Duplicate)
