### ISSUE TITLE
smoke forever

### ISSUE THREAD

**Issue by KIDO13** [CleverRaven/Cataclysm-DDA#47600] opened 2021-02-19 07:10 UTC
When i smoked indoor, the smoke wont dissipate. i think it has something to do with how it spreads faster than it dissapears because it wasnt a problem when i was walking around

1. Smoke indoors(needs a very large area)
2. Don't move

The smoke should dissapear in like a few minutes or so, just not forever

# Screenshots

![smokingbug](https://user-images.githubusercontent.com/47026590/108470063-529b5480-72c4-11eb-9ba7-03e09605856e.jpg)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9666-gecae002 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    My Sweet Cataclysm [my_sweet_cataclysm],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by Zireael07** [comment] 2021-02-19 08:18
Dupe of #47479, which you would have seen if you tried searching for "smoke"

**Closed** 2021-02-19 15:26 UTC
