### ISSUE TITLE
Wielding items sometimes causes currently wielded item to disappear

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21963] opened 2017-09-22 19:33 UTC
Game version: 6790

Operating system: Win 7

Tiles or curses: Tile

Mods active: [
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "StatsThroughSkills",
  "blazemod",
  "boats",
  "deoxymod",
  "makeshift",
  "more_classes_scenarios",
  "more_locations",
  "no_npc_food",
  "no_religious_Texts",
  "no_reviving_zombies",
  "novitamins",
  "No_Fungi"
]

### Expected behavior
Wielded item will prompt where to relocate

### Actual behavior
Wielded item sometimes disappears

### Steps to reproduce the behavior
I don't know how this is reproduced. I was wielding a machete and activated my back holster coilgun and my machete vanished

**Comment by AMurkin** [comment] 2017-09-22 19:46
Dupe of #21959

**Closed** 2017-09-22 19:53 UTC
Labels: Duplicate
