### ISSUE TITLE
Crash on eating from warehouse shelf with too many items in it

### ISSUE THREAD

**Issue by pontim** [CleverRaven/Cataclysm-DDA#77489] opened 2024-10-31 20:41 UTC
### Describe the bug

Trying to eat from a warehouse shelf with 16 pages of items causes my game in Experimental to crash with a segfault

### Attach save file

[save.zip](https://github.com/user-attachments/files/17593163/save.zip)

### Steps to reproduce

Put a ton of food in containers on a warehouse shelf along with other items
Try to eat
game crashes with a segfault

### Expected behavior

I expected I could eat without crashing

### Versions and configuration

Microsoft windows 10 Pro version 10.0.19045. Cdda version 6d904d9

**Comment by pontim** [comment] 2024-10-31 20:42
[crash.log](https://github.com/user-attachments/files/17593195/crash.log)

**Comment by JeveGreen** [comment] 2024-10-31 23:58
[crash.log](https://github.com/user-attachments/files/17594292/crash.log)

The crash happens even if you access it from advanced inventory, or even try using [g]rab.

**Comment by Standing-Storm** [comment] 2024-11-01 06:12
This and #77500 may be related

**Comment by RadioAndrea** [comment] 2024-11-03 04:46
Crash also occurs when using the "nearby items" menu!

**Comment by RenechCDDA** [comment] 2024-11-03 20:33
Duplicate of #77500

**Closed by RenechCDDA** 2024-11-03 20:33 UTC
Labels: (S1 - Need confirmation)
