### ISSUE TITLE
miscellaneous repair kit uses duct tape for non-repair tasks

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67389] opened 2023-08-02 21:17 UTC
### Describe the bug

A miscellaneous repair kit contains a wood saw, and as such has the tree cutting 1 quality. But using it for that purpose consumes 5 duct tape, which is weird.

### Attach save file

N/A

### Steps to reproduce

Have a fully charged miscellaneous repair kit, cut down a tree.

### Expected behavior

I would expect that only repair actions would cost duct tape, and all of the actions based on the qualities of the tools wouldn't require duct tape.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 0cc8ad5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment] 2024-10-10 08:53
Duplicate of #55158.

**Closed by Night-Pryanik** 2024-10-10 08:53 UTC
Labels: (S2 - Confirmed)
