### ISSUE TITLE
Build 6764, froze my computer and won't let CDDA run again.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#21866] opened 2017-09-12 11:56 UTC
Game version:
0.C-23898-g0839890 (tiles)
Operating system:
Windows 7 Professional x64 SP1
Tiles or curses:
Tiles
Mods active:
{
  "type": "MOD_INFO",
  "ident": "user:default",
  "dependencies": [
    "dda",
    "Experimental-Z-Level",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "No_Fungi",
    "StatsThroughSkills",
    "blazemod",
    "Tanks",
    "boats",
    "deoxymod",
    "filthy_morale",
    "makeshift",
    "more_classes_scenarios",
    "more_locations",
    "national_guard_camp",
    "no_npc_food",
    "no_rivtech_guns",
    "novitamins",
    "realguns"
  ]
}
### Expected behavior
Successfully run CDDA with launcher.
### Actual behavior
CDDA doesn't run
<a href='https://postimg.org/image/loozkog4d/' target='_blank'><img src='https://s6.postimg.org/jww0prwrl/Crash_and_freeze_and_then_if_trying_to_run_the_g.jpg' border='0' alt='Crash_and_freeze_and_then_if_trying_to_run_the_g'/></a>

This happened after making a new world and character with the above latest version.

Reverting to build 6736 or 6735 gives me the same error. Do I need to re-install the CDDA Game Launcher? I am using the latest CDDA Game Launcher version.
### Steps to reproduce the behavior

**Comment by Nhatorama** [comment] 2017-09-12 13:58
Deleting the options.json file in the Config folder let's me run the game. Should I close the issue?

**Comment by kevingranade** [comment] 2017-09-12 16:31
Since there's no way to reproduce or investigate 5he issue, yes.  I'll just close it for you.

**Closed by kevingranade** 2017-09-12 16:31 UTC
Labels: Confirmation Needed, Crash / Freeze
