### ISSUE TITLE
Mapgen error for mine

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#57369] opened 2022-05-02 17:15 UTC
### Describe the bug

 DEBUG    : mapgen params expected but no overmap special found for terrain mine_shaft_lower_east_east

 FUNCTION : mapgendata
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgendata.cpp
 LINE     : 86
 VERSION  : d6087a2

### Steps to reproduce

1.Travel on a road on the surface.
2.Happen to encounter the message above.

### Expected behavior

No report

### Screenshots

![Screenshot (240)](https://user-images.githubusercontent.com/22739822/166293581-2f39c413-3e9e-4cc1-b31e-a09008c206bb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: d6087a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON hack to disable portal storms as the mod for it was rejected.
+ JSON addition of 4 welding wire/rod recipes to workshop expansion 2.

**Comment by haveric** [comment] 2022-05-07 01:45
/confirmed 
I'm able to replicate this on a random naturally spawning mine. I'm going to do some more testing on a clean new world to see if I can replicate it there as well and will upload a save soon.

**Comment by haveric** [comment] 2022-05-07 02:09
I haven't been able to replicate this with a fresh world, which leads me to believe this is happening on existing saves with the old mines. I'm assuming this means that some porting of the mine locations will need to be done for 0.G, but I'm unfamiliar with the process. With that said, the fact that this mine is two overmaps over feels like it should be spawning new terrain, but I'm not sure.

To replicate: [Tacoma Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8644258/Tacoma.Test.zip)
1. Debug teleport adjacent overmaps down twice.
2. Debug teleport to the nearest mine.
3. See errors similar to the original about: `road_new`, `s_lot_west`, `mine_shaft_lower_east_west`, `mine_shaft_middle_east_west`, etc.

Two other notable possible bugs while teleporting around to multiple mines:
- Roads are only connected about half the time. I'm not sure if this is intentional or not.
- An occasional error message pops up about placing traps where traps already exist.

**Comment by Night-Pryanik** [comment] 2022-05-07 03:25
> Roads are only connected about half the time. I'm not sure if this is intentional or not.

Mine connected to road network is a fixed, static overmap special. Mine without connection is a mutable overmap special; due to limitations there is currently no way to connect mutable specials to road network.

**Comment by Night-Pryanik** [comment] 2022-08-02 12:24
@PatrikLundell have you encountered this issue since May?

**Comment by PatrikLundell** [comment] 2022-08-02 12:34
I don't think I've seen it for some time, although I can't say when I ceased to get it.

**Comment by NetSysFire** [comment] 2022-09-10 11:30
I can not reproduce this either. I'll close this for now as it looks fixed.

**Closed by NetSysFire** 2022-09-10 11:30 UTC
Labels: <Bug>, (S2 - Confirmed), Map / Mapgen
