### ISSUE TITLE
Cannot drag furniture over gravel floor

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#44678] opened 2020-10-06 22:42 UTC
# Describe the bug
Furniture cannot be dragged over 'gravel' as found at the 4x4 farm with the barn and chicken coop.

# Steps To Reproduce
1. Find some gravel
2. Spawn or find some furniture (tested with table and armchair)
3. (G)rab the furniture and attempt to move it onto the gravel floor

"The <furniture> collides with something"

# Expected behavior
Gravel, being small rocks on the ground, should not impede the dragging progress of furniture.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6527-g83721c4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Beta National Guard Camp [national_guard_camp],
    More City Locations [cityside],
    More Locations [more_locations]
]

# Additional context
May be mod related, not sure if one of those adds the gravel floor or a their own version of it.

**Comment by wapcaplet** [comment] 2020-10-07 03:01
Thanks for reporting. Confirmed, and looks like a duplicate of #32308.

**Closed by wapcaplet** 2020-10-07 03:01 UTC
