### ISSUE TITLE
Suspect vehicle wreck generation

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#67842] opened 2023-08-23 18:17 UTC
### Describe the bug

There is something suspect with all these wrecks, with at least 4 vehicles stacked on top of each other in some places.

Everything else looked normal until I started to try to clear out this settlement of zombies and both encounter incessant hordes of them (20 or so was cleared out from just above the screen shot, and the game was generated with about 50% spawn rate). It can be noted that the parts of the settlement that I'd already seen from the previous experimental (about a week ago) looked fairly normal.

The second screen shot was taken when speeding past the mess and reaching the next town. Again a mess of vehicles stacked layers upon layers.

### Attach save file

N/A

### Steps to reproduce

1. Take an existing game (probably get the same result with a new one).
2. Travel to a town part of the map you haven't encountered before.
3. Find a mess of vehicles stacked multiple vehicles deep mostly covering the road.

### Expected behavior

As it used to be, i.e. damaged and broken down cars with a smattering of wrecks rather than wreck mats. The huge number of zombies is also off.

### Screenshots

![Screenshot (279)](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/13f85817-8e68-40ab-9116-34d82836e621)
![Screenshot (280)](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/07e33d24-6811-4319-9860-b22eff6589e6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 5ebd5af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ modded out portal storms

**Comment by waifusd** [comment] 2023-08-23 18:30
#67837

**Comment by ZhilkinSerg** [comment] 2023-08-23 18:45
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/67837

**Closed by ZhilkinSerg** 2023-08-23 18:45 UTC
Labels: (S3 - Duplicate)
