### ISSUE TITLE
Hallucinations should not wake up a sleeping character

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20076] opened 2017-01-22 18:16 UTC
Perhaps they should merely prevent a character from sleeping, but once asleep it becomes, mechanically, a pain in the sides to have to keep an eye on the game and try to re-sleep 5 or 6 times in an 8 hour period.

**Comment by Zireael07** [comment] 2017-01-22 19:45
Speaking from experience, hallucinations (auditory not visual) DO can wake you up. 

(I am hearing impaired and one of the downsides includes tinnitus, which is sometimes more of a hallucinated voice or other household sound rather than ringing. Cue me waking in the middle of the night because I thought I heard someone call me or that a bookshelf came crashing down or something. Key word being 'thought', obviously)

**Comment by CoroNaut** [comment] 2017-01-24 08:46
This could be similar to night terrors, a psychological reaction leads you to believe a nightmare you had is much worse (you think it is real) and therefore you jump out of bed. Night terrors could be caused by the effects of the hallucinations.

**Comment by Coolthulhu** [comment] 2017-01-24 08:58
We could just have all hallucinations disappear when the player is asleep.

Though honestly I'd just get rid of the hallucination mechanic. It causes much more trouble than anything else.

**Comment by Headjack** [comment] 2017-02-06 22:52
Well, it's a detriment, right?

**Comment by kevingranade** [comment] 2017-04-25 02:06
Another solution for this is to adjust the sleep menu to resemble the wait menu, then you can, "try to sleep until foo".  Non-dangerous interruptions would cause the player to automatically go back to sleep, so the cost would just be in sleep quality rather than annoyance.

**Comment by Mooses2k** [comment] 2019-05-27 19:01
I vote for no-change. Let hallucinations wake the player. It's a nightmare that persists upon waking.

**Comment by korvyr** [comment] 2019-10-25 17:01
Seems simple enough on the surface to fix. I'll take a wack at this this weekend, along with the horses climbing through windows issue.

**Comment by korvyr** [comment] 2019-10-26 17:53
This is no longer an issue. Hallucinations from datura no longer wake you up. Recommend closing the issue.

**Comment by Night-Pryanik** [comment] 2019-10-26 18:28
Ok, closing until re-confirmed.

**Closed by Night-Pryanik** 2019-10-26 18:28 UTC
Labels: <Bug>, <Enhancement / Feature>, Good First Issue, Info / User Interface

**Comment by Destragon** [comment] 2019-10-26 21:27
@korvyr If you still want to work on it, I believe prototype cyborg has basically the same annoyance issue with faulty bionics that constantly wake you up.
