### ISSUE TITLE
accessing keyboard on android resets game

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#36585] opened 2019-12-31 02:19 UTC
When pressing the < touchscreen button on the right to bring up the keyboard on the android version the game is minimized and reset/restarted. This happens after the keyboard has already been opened and closed once and can be fixed temporarily by minimizing the game and bringing it up, allowing you to access the keyboard one time before the bug happens again. This bug was not present on the non-experimental android version.

1. create/load a save on android(optional, main menu works too)
2. access keyboard
3. close keyboard
4. press button to access keyboard
5. game minimizes and if you bring it back up it's relaunched back to the main menu

# Expected behavior

ideally the keyboard would actually come up normally each time without minimizing and resetting the game, losing all progress since last save.

# Versions and configuration

 - OS: android 9 on Samsung Galaxy S8
 - Game Version: 0.D-107993-gf10295a
 - Graphics version: tiles
 - Mods loaded: mods don't affect it

# Additional context

I just recently started trying to play on android, this issue wasn't present on the stable android app, only ran into the issue when I tried the experimental app once I found out it existed.

**Comment by ZhilkinSerg** [comment] 2019-12-31 05:46
Thanks for bug report. We are aware of this issue for Android 9.

You can manually install APKs from https://github.com/CleverRaven/Cataclysm-DDA/releases as a workaround until the issue is resolved.

Duplicate of #35758

**Closed by ZhilkinSerg** 2019-12-31 05:46 UTC
Labels: (S3 - Duplicate), <Bug>, OS: Android
