### ISSUE TITLE
Improvement to construction menu sorting

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#12099] opened 2015-04-21 20:33 UTC
So, Whales posted this screenshot of his construction menu a few days ago on his tumblr:

![image](https://cloud.githubusercontent.com/assets/5290912/7261877/cb4de048-e83a-11e4-96bf-ef235d34816b.png)

And, being specific, the part in which you first choose the structure type and then the material seems like it would be a pretty good improvement over our current cluttered list.
##

**Comment by Oskar636** [comment] 2015-04-21 20:43
This looks so.... lovely xD

**Comment by i2amroy** [comment] 2015-04-21 21:10
We'd need to delink furniture type and material type before you could even begin to do something like this. That would also involve rewriting every single construction recipe to include what material would be created in the end construction, and ideally would also include the ability to define multiple different material recipes in one place, since elsewise every different material for a piece of furniture would require its own recipe. To put it bluntly, this is a system that would be rather easy to code with a fixed set of terrain and furniture types, and a fixed set of materials to make them out of. The complexity explodes if you try to allow the addition of removal of things on the fly.

It's something you could hypothetically do, but it would definitely need some get inventive JSON simplifiers or something like "add a new piece of furniture" is going to involve the creation of 18 different recipes and an 8 page long furniture type definition.

**Comment by sparr** [comment] 2015-04-21 21:30
This is the first I've heard that Whales is working on Cataclysm 2. I am sad to hear that there is such parallel development going on :(

**Comment by John-Candlebury** [comment] 2015-04-21 21:44
>We'd need to delink furniture type and material type before you could even begin to do something like this. That would also involve rewriting every single construction recipe to include what material would be created in the end construction, and ideally would also include the ability to define multiple different material recipes in one place, since elsewise every different material for a piece of furniture would require its own recipe. To put it bluntly, this is a system that would be rather easy to code with a fixed set of terrain and furniture types, and a fixed set of materials to make them out of. The complexity explodes if you try to allow the addition of removal of things on the fly.

>It's something you could hypothetically do, but it would definitely need some get inventive JSON simplifiers or something like "add a new piece of furniture" is going to involve the creation of 18 different recipes and an 8 page long furniture type definition.

--

Well I was thinking more along the lines of faking it by sorting all the walls, doors etch; together in that style (code wise they would all be separate objects).

**Comment by macrosblackd** [comment] 2015-04-21 22:50
It wouldn't be as difficult as you think. Instead of tying materials to recipes you would have something like this:
```
Material
  Flamability
  Durability
  [Something to represent a modifier to build/construction time]
```
Then for constructions:
```
Construction
  Modifiers (How does this terrain affect flamability, durability, etc)
  BaseBuildTime
```
Then you could simply tie things together on the fly. You would probably want to make a 'static' cache of terrain/material combinations (adding something in the middle of material or recipe list wouldn't alter it's identifier) to speed things up.

**Comment by Coolthulhu** [comment] 2015-04-21 23:00
The biggest problem would probably be recipes.
Someone would have to invent a generic system that generates a recipe for a pair of proto-recipe<->material. This system would have to generate both construction recipes, deconstruction drops (when requested) and smash drops.

**Comment by i2amroy** [comment] 2015-04-22 00:30
>The biggest problem would probably be recipes.
Someone would have to invent a generic system that generates a recipe for a pair of proto-recipe<->material. This system would have to generate both construction recipes, deconstruction drops (when requested) and smash drops.

We'd also need to be able to generate bashing resistance and a handful of other material-dependent stats on the fly as well. A metal chair is going to be more resistant to bashing than a wooden one after all. :P

That said really it *would* be nice to get some UI improvements in the construction menu, and I've got nothing against that.

**Comment by Coolthulhu** [comment] 2015-04-22 00:33
Resistances would probably be the easiest part. Just multiply material resistance and recipe resistance.

Having an automatic system for generation would have one significant advantage: we could easily make it generate partially constructed and partially destroyed tiles.

**Comment by Frost-wood** [comment] 2015-04-22 02:00
I'd use the current materials json-maybe have a construction multiplier, on strength and speed.  I would use the tool qualities system, as it would allow multiple tools without having to define them individually.

As Coolthulhu suggested I would move the terrain to the 'item' damage system

roughly: 
"id" : "t_wall",
"name" : "wall",
"symbol" : "LINE_OXOX"
"base_time" : 10(minutes),
"base_skill" : 2,
"density_multiplier" : 1, (wood has a bash resist of 3, and density of 4= 12 base strength)
"material_multiplier" : 12,
"bash_range" = 5 (so if you have a bash_min of 20, then the bash_max would be 40)
materials":[
  {"material" : "wood", "adj" : "wooden", "learn" : "auto" },
  {"material" : "stone", "adj" : "stone", "learn" : "auto" },
  {"material" : "concrete", "adj" : "concrete", "learn" : ["Engineering_301", "DIY"] },
  {"material" : "fungus", "adj" : "fungal", "learn" : "NULL" },
]
"move_cost" = 0,
"flags" : [standard flags],
"additional items" : {
               //this would be null for a wall, but for say a pump or charcoal klin you might need additional items to construct.  You would define at the same time whether it is recoverable by deconstruct by "deconstruct_recover" : true, and "bash_recover_chance" , 0.5
}


in materials you would probably define additional flags like:

"construction_time_multi" : 1,
"skill_multi" : 1,
"time_multi" : 1,
"tool_qualities_required" : [
          { "id" : "hammer", "level" : 1},
          { "id" : "wood_sawing", "level", 2}
]
"base_construction_materials" : [ 
           {"id": "two_by_four", "construct_multi" : 1, "deconstruct_multi", 0.5, "bash_multi": 0.2},
           {"id": "nails", "construct_multi" : 2  "deconstruct_multi", 1.5, "bash_multi": 0.5},
           {"id": "splinter", "construct_multi" : 0, "deconstruct_multi" , 0, "bash_multi" : 0.5}
] 

Roughly speaking of course.

**Comment by graysage1** [comment] 2015-04-22 11:13
>That said really it would be nice to get some UI improvements in the construction menu, and I've got nothing against that.

The construction menu is too long with too many things in it.  They're all necessary things, don't get me wrong.  The problem is information overload.

Right now if I want to look for a construction that requires construction level 4 skill (so that I can work on my construction skill, which is a common use case I imagine) how do I do so?  Well, right now I am forced to start at the top, and scroll one item at a time toward the bottom, while reading their skill descriptions to see if any of those require level 4 construction.  What a tedious process.

Why can't I instantly see all the skills that will train up my level?

Also, without going too clever about it with the construction materials, we can just split the construction menu into categories: a) land improvement (digging pits, tilling, flattnening out land, cutting grass all go here), b) permanent structures c) temporary structures (this will be all the stuff you can "place" like anvils), d) furniture, e) emergency survival (makeshift bed, lean-to, temporary shelter, all the emergency survivalist stuff should go here).  Not necessarily in this order.  The most commonly needed items should be at the top or the bottom (because it's fast to jump to the bottom).  The least often used items should be in the middle.

**Comment by sparr** [comment] 2015-04-22 14:35
I disagree with everything on the construction menu being necessary.

As someone who had trouble discovering it... chopping down a tree should not be on the construction menu. Move it to 'a'pplying a saw/axe, or 'e'xamining the tree.

On that same note, a lot of other constructions could be moved to applying tools or examining existing constructions.

**Comment by graysage1** [comment] 2015-04-22 15:00
@sparr, here's the problem as I see it.

If you continue overloading 'a'pplying and 'e'xamining, you'll burden the UI.  Right now if I want to 'a'apply my knife to skin something, I need to first use '=' to assign the knife to a stable inventory letter, and I need to remember it.  The I have to make sure that knife is not in the boot.  If it's in the boot, too bad so sad, I can't 'a'apply it anymore.  So creates a special condition.  Construction menu doesn't have this problem.

Also, what if you want to build a wall?  I imagine you'd have to examine an empty tile?  Or maybe you think you need to 'a'apply your axe?  But why axe?  Maybe wood saw.  Or why wood saw?  Maybe you need to apply your shovel.  Do you see my point?  Many construction projects use many tools, and so why should a specific one of them be 'a'pplied to begin the project?  Or worse, why should huge menu lists be attacked to 'a'apply actions?  So if I 'a'pply wood saw, do I want to build a wall?  Do I want to saw a log into planks?  Do you see how this can get out of hand?

This is why construction is a nice abstraction.  Maybe construction and fabrication should be merged?  I am not convinced, but maybe?

I think the construction menu is fine.  Contextual menus are nice only when they're specific.  For a multi-purpose tool each context menu will end up as unwieldy and stupid as the construction menu itself, and having many such menus be duplicated across many tools, that's unwelcome.

**Comment by Coolthulhu** [comment] 2015-04-22 15:04
> Right now if I want to 'a'pply my knife to skin something, I need to first use '=' to assign the knife to a stable inventory letter, and I need to remember it.

Item action menu is bound under `%` by default and does pretty much what you'd want here.
Kinda hidden, but I didn't have good keybinds left.

**Comment by graysage1** [comment] 2015-04-22 15:07
@Coolthulhu I agree 100%.  I edited my post probably after you've read it, but in my latest edit I even mention the action menu as a good direction to go toward and why so.

Even better than the action menu would be a generic macro menu, if you ask me. :)  It'd be rough the same thing, but it would be configurable by the player.  Although in this case, the player would need to be able to specify things like "best available tool" instead of just a specific keystroke when creating the macros.

**Comment by illi-kun** [comment] 2016-11-10 08:15
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Closed by illi-kun** 2016-11-10 08:15 UTC
Labels: Enhancement
