### ISSUE TITLE
Parsing error- "Fontblending"?

### ISSUE THREAD

**Issue by xanderrootslayer** [CleverRaven/Cataclysm-DDA#58044] opened 2022-05-31 03:55 UTC
### Describe the bug

 DEBUG    : (json-error)
Json error: <unknown source file>:2:18: Invalid or misplaced field name "fontblending" in JSON data, or value in unexpected format.

{
  "fontblending":
                 ^
                  false,
  "fontwidth": 8,
  "fontheight": 16,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 125
 VERSION  : c355923

### Steps to reproduce

Literally it told me this on boot. 

### Expected behavior

It's an experimental version, bug hunting is part of the experience. 

### Screenshots

![Screen Shot 2022-05-30 at 11 30 46 PM](https://user-images.githubusercontent.com/46512498/171089447-a4388bc4-75ae-4eb1-a543-0c07eedc833a.png)

### Versions and configuration

I cannot enter debug to generate a report because the game didn't start yet.

**Comment by Night-Pryanik** [comment] 2022-05-31 03:59
Duplicate of #55533.

**Closed by Night-Pryanik** 2022-05-31 03:59 UTC
Labels: (S1 - Need confirmation)
