### ISSUE TITLE
Putting items into backpacks without changing the inventory screen.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16650] opened 2016-05-13 02:05 UTC
I would like to suggest (and I ran it past Kevin on IRC) that backpacks, duffle bags, suitcases, MOLLE packs, etc, turn into furniture when they are dropped, so you can fill them up, and grab them and drag them around. 

Also, it would be cool, if it was made to just cost how much time it takes to put on the backpack, instead of picking all the items up individually.

Same with multi dropping it and other items, it could say, "Do you want to keep the additional items in the bag? Y/N/Q" even if the items weren't in the bag to begin with.

This idea need not, in any way, change the inventory screen as it is currently. 

More than one bag a tile, only the top bag should be fillable. Or maybe bags should slip off other bags, like if the tile is full?

**Comment by Coolthulhu** [comment] 2016-05-13 02:12
> turn into furniture

This would be pretty much unmaintainable, a total hack that would break more often than not.

**Comment by Chezzo** [comment] 2016-05-13 02:21
I realize that it would need special coding to be made to act like furniture, I didn't mean to just turn it straight up into furniture. Doing that would make it so that you couldn't pick it up anyways, right?

**Comment by Coolthulhu** [comment] 2016-05-13 02:41
> I realize that it would need special coding to be made to act like furniture, trash can was just a good example of what it would act like. I didn't mean to just turn it straight up into furniture. Doing that would make it so that you couldn't pick it up anyways, right?

A map tile can contain pretty much only items and one piece of each of: terrain, furniture, trap.
It can also contain a vehicle, but that wouldn't be usable here.
So we're left with one choice: leaving items as items, no tricks here.

> And don't we have most of those properties in foldable carts already?

No, foldable carts are just vehicles that can become items when interacted with, then turned back into vehicles when used as items. This wouldn't be usable with bags due to number of keypresses to do anything.

The problem here is the UI. There is a lot to be done to make it usable and so far no one did it.

The bags on the ground would have to stay items. Not furniture or hacks like that.
But then there would need to be the UI to assign items to individual bags. This UI would have to be USABLE to be accepted, nothing as crude as having to manually pick bags for each item and manual inventory tetris. Automatic repacking is pretty much a must - doesn't need to be perfect, but needs to be there and be sane.

**Comment by Chezzo** [comment] 2016-05-13 02:47
Why wouldn't just dropping them into the top most bag work? Then if the bag gets filled it drops off onto other adjacent tiles, like if the tile was full? Then there wouldn't need to be a UI.

What do you mean by automatic repacking?

**Comment by Coolthulhu** [comment] 2016-05-13 02:56
> What do you mean by automatic repacking?

One of the primary reasons to have items in bags is dropping a worn bag with all its contents to fight easier, then picking it back up all at once. This requires tracking which items are in which bag.

It wouldn't be acceptable to require the player to manually pick which items are in which bag.
Then there would be situations like this:
* You have 20 inventory volume in 2 bags, 10 each
* You have 8 volume of flour in one bag, 8 of sugar in the other
* You pick up a 5 volume item (say, a mace)
* The mace will fit in a bag, but you have two bags with 4 free volume each
* The player must not be required to manually move 1 volume of sugar to the bag with flour, there must be an option to have this done automatically, just "repack the inventory so that the new item fits"

**Comment by Coolthulhu** [comment] 2016-05-13 03:00
Duplicate of #3671

**Comment by Chezzo** [comment] 2016-05-13 03:02
See, I was thinking there would need to be no changes at all to the inventory screen. So when you pick a bag up, all you get is the benefit of not picking the bag and all the stuff up all one at a time.

And when you drop a bag and other stuff, all you get is the benefit of not having to spend the time dropping the bag and all the other stuff.

That is how it is not a duplicate of anything, and why Kevin agreed that it was a good idea on IRC.

**Comment by Coolthulhu** [comment] 2016-05-13 03:23
Well, the issue name clearly implies a duplicate. At least change that.

**Comment by Chezzo** [comment] 2016-05-13 03:27
Awesome, thanks Coolthulu.

**Comment by Coolthulhu** [comment] 2016-05-13 03:52
This still isn't a good description.
I'd change it to something like "'g'rabbing and dragging items"

Though it would be better if you split it into 2 separate issues:
* Dragging items
* Quick pickup and drop when also picking up or dropping containers.

**Comment by Chezzo** [comment] 2016-05-13 04:15
Okay. Would the filling the bags up go in the second issue, do you think?

**Comment by Coolthulhu** [comment] 2016-05-13 04:23
The first. The second one wouldn't really touch the mechanics at all, only the time to pickup and time to drop.
Notice that that way they would both work fine without each other, that's why they would be better off as separate issues.

**Closed** 2016-05-13 04:36 UTC

**Comment by Chezzo** [comment] 2016-05-13 04:38
Thanks so much, Coolthulhu. I really appreciate your time and expertise on this.

**Comment by kevingranade** [comment] 2016-05-17 07:33
The way this could work is if containers dropped along with other items had
the other items added to their internal contents.  Drop code would need to
make this change, pickup code would need to reverse it, and look around
code would need to describe it differently.

**Comment by codemime** [comment] 2016-05-17 08:03
I'm currently working on the drop code (will PR a WIP soon), but my current intention is simplifying it gradually, so that adding new features (and fixing bugs like #14035) would become easier. Adding something to its original (non-refactored) implementation would be pretty much a hack.
