### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by StefanMiletic994** [CleverRaven/Cataclysm-DDA#41073] opened 2020-06-04 15:16 UTC
# Describe the bug

When trying to repair something with soldering iron(glasses, other clothing) game instantly crashes.

# Steps To Reproduce

1. Use soldering iron(repair).
2. Pick glasses or other stuff repairable with soldering iron.
3. Game crashes. 

# Expected behavior

Should repair or destroy the item tried to repair.

# Screenshots

![Repair1](https://user-images.githubusercontent.com/49565306/83774239-bb369880-a685-11ea-8850-b6f2c1a3b8dc.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/49565306/83774257-bf62b600-a685-11ea-8205-7eca423d5de2.jpg)

# Versions and configuration

![Spec](https://user-images.githubusercontent.com/49565306/83774812-7ceda900-a686-11ea-8d33-a201307118ff.jpg)

 - OS: [Windows 10 ]
 - Game Version: [0.E-2844-gede5ff2]
 - Graphics version: [Undead People Tileset]
 - Ingame language: [System Language(English)]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Aftershock, Blaze Industries, C.R.I.T Expansion Mod, Alternative Map Key, Mining Mod, More City Locations, Jury- Rigged Robots, Speedy Dex, Bionic Slots]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4730911/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4730912/debug.zip)
[Bannerland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4730923/Bannerland.zip)

**Comment by anothersimulacrum** [comment] 2020-06-04 15:17
Thanks for the report! This is a duplicate of #40842.

**Closed by anothersimulacrum** 2020-06-04 15:17 UTC
