### ISSUE TITLE
Reloading a Tailor's Kit causes a Segmentation fault

### ISSUE THREAD

**Issue by Karllawrenz** [CleverRaven/Cataclysm-DDA#42111] opened 2020-07-14 03:58 UTC
# Describe the bug

Reloading a Tailor's kit caused a Segmentation Fault

# Steps To Reproduce

1.Bring up the Reload menu
2.Reload the Tailor's kit
3.Crash

# Expected behavior

# Screenshots

# Versions and configuration
OS:Windows 10
Game Version:0.E-4044-g05093fa
Graphics Version:Tiles
Ingame Language:English
Mods loaded:

  "dda",
  "no_npc_food",
  "Arcana",
  "magiclysm",
  "MST_Extra",
  "Pix's Shit",
  "more_survivor_stuff",
  "DinoMod",
  "crazy_cataclysm",
  "my_sweet_cataclysm",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "zets_hair_extensions_undead",
  "Dorf_Life",
  "fuji_mpp",
  "manualbionicinstall",
  "speedydex",
  "stats_through_kills"

# Additional context

crash.log and debug.log included
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4916449/save.zip)

**Comment by ZaricaDemoni** [comment] 2020-07-14 04:13
Most likely related to #42089 as so far any item that can be reloaded causes segment fault crash.

**Comment by ZhilkinSerg** [comment] 2020-07-14 05:53
Duplicate of #42089

**Closed by ZhilkinSerg** 2020-07-14 05:53 UTC
Labels: (S3 - Duplicate)
