### ISSUE TITLE
Using a 3L jar of Gasoline to refill a 60L Gasoline tank is impossible

### ISSUE THREAD

**Issue by DougStep** [CleverRaven/Cataclysm-DDA#44045] opened 2020-09-08 12:07 UTC
# Describe the bug

Using a 3L jar of Gasoline to refill a 60L Gasoline tank causes this

DEBUG    : tried to put an item (gasoline) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int)
 FILE     : src/item.cpp
 LINE     : 8663

The side chat will say the tank is full and there is leftover. The tank however will not gain any gasoline

# Steps To Reproduce

Try to fill a 60L tank with a 3L jar

# Expected behavior

The tank (depending on how full the jar is) gains x quantity of gasoline

# Screenshots

https://www.youtube.com/watch?v=oT9v5UXuFAI&feature=youtu.be

# Versions and configuration
- OS: Windows 10 pro
    - OS Version: 10.0 1909
- Game Version: 0.E-5791-gc9d731b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key]
]

 -->

# Additional context

Restarting the game had no effect nor did the car being off or on at the time

**Comment by wapcaplet** [comment] 2020-09-08 22:41
I could not reproduce this issue in the same version 0.E-5791-gc9d731b on Linux. Siphoning gasoline into 3L jars, then refilling the tank from the jars, works as expected with no errors. Just to be sure, I also tried both with and without Magiclysm.

@DougStep Does the error persist after saving and loading? There is a chance, if the vehicle was from an older save game (previous version of the game), that whatever bad data caused it has been fixed in newer versions. If you still have a save game where the error can be reproduced, please zip and attach it here - that will help us figure things out. Thanks!

**Comment by DougStep** [comment] 2020-09-09 01:23
0, 0'105, 0' 102 car just south of luxury car is the specific car I was trying to fill, specifically my 3L jar was not entirely full as I spilt some of the gas  
Here's a backup of the save, you'll have to teleport to the coordinates above

[Troubleshooting backup.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5192048/Troubleshooting.backup.zip)

**Closed** 2020-10-08 11:16 UTC
Labels: (S1 - Need confirmation), Items: Containers
