### ISSUE TITLE
All battery-powered items spawning wth plutonium batteries

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#41507] opened 2020-06-22 02:22 UTC
# Describe the bug

Any items that spawn with a full battery are spawning with plutonium batteries. These batteries should not appear outside of labs.

# Steps To Reproduce
Teleport to an electronics store. Observe that all items that spawn with batteries spawn with plutonium batteries.

# Expected behavior
Items spawn with LITERALLY ANY OTHER KIND of battery

# Screenshots
![image](https://user-images.githubusercontent.com/2125926/85242650-9ecc8700-b40d-11ea-8d0c-bdcf325243cf.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3407-g845884a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]
# Additional context

**Comment by LaVeyanFiend** [comment] 2020-06-22 02:23
Duplicate of #40800.

**Comment by Inglonias** [comment] 2020-06-22 02:25
that bug is a month old and nobody has fixed it?!

**Comment by anothersimulacrum** [comment] 2020-06-22 03:33
Duplicate of #40800.

**Closed by anothersimulacrum** 2020-06-22 03:33 UTC
