### ISSUE TITLE
Mulitple Items have 0.000 L Volume Capacity

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#40518] opened 2020-05-13 10:14 UTC
# Describe the bug
Multiple (craftable) Items have a volume capacity of 0.

# Steps To Reproduce

Know all reciepes.
search: d: 0.000 L
See all Items with no VC.

# Expected behavior
Them having VC. Or other info about storable Ammo.

# Screenshots
![grafik](https://user-images.githubusercontent.com/33199510/81800534-42736f00-9513-11ea-87e4-efebc64b7ac8.png)
![grafik](https://user-images.githubusercontent.com/33199510/81800546-48695000-9513-11ea-8d5e-7ad509aebd52.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    Fewer Farms [Fewer_Farms]
]

# Additional context

**Comment by KorGgenT** [comment] 2020-05-13 15:21
Duplicate of #40521

**Closed by KorGgenT** 2020-05-13 15:21 UTC

**Comment by Lamandus** [comment] 2020-05-13 20:18
@KorGgenT : I don't want to be too picky. But isn't my topic younger than the one you marked? As in the other one is the dublicate of mine?

**Comment by KorGgenT** [comment] 2020-05-14 01:03
sorry, i was just triaging them and marked it duplicate in the order i saw them.
