### ISSUE TITLE
Vehicles roofs no longer block daylight

### ISSUE THREAD

**Issue by Koalabog** [CleverRaven/Cataclysm-DDA#30509] opened 2019-05-14 13:41 UTC
# Describe the bug
Vehicle lighting no longer allows for a vehicle to be dark while it is bright outside

# Steps To Reproduce

1.Be in an APC with curtain on its window or any other vehicle that should be dark during the day
2.It is not dark
Apparently only occurs with experimental Z-Levels on according to some quick testing on discord

# Expected behavior
that a fully enclosed vehicle roofed and with no external lighting possible to be dark, assuming no internal light sources of course.

# Screenshots
No internal light sources and there is a closed curtain on the window
![image](https://user-images.githubusercontent.com/41955378/57702305-156d5180-765e-11e9-9846-446fdcce7af2.png)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-2912-g2ad83e9
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Weapon fixes [variousweaponfixes],(This is a small mod i made for personal use that just adds a burst fire option to UMP and makes the Mp5SD somewhat useable)
    Boats [boats]
]

**Comment by esotericist** [comment] 2019-05-14 13:57
This and some related effects (try heading into a procedurally generated house in the middle of the day) are due to the new raytracing light code (which allows light to pass through holes into deeper z-levels).

Hopefully it will be fixed soon.

**Comment by kevingranade** [comment] 2019-05-15 00:38
Yep my bad, this should be a bit easier to fix than the other issue at least, I just forgot to apply vehicles at all.

**Comment by anothersimulacrum** [comment] 2019-09-15 00:51
I cannot reproduce this - is this still an issue?

**Comment by ZhilkinSerg** [comment] 2019-10-08 09:00
Possibly duplicate of #34451

**Closed by ZhilkinSerg** 2019-10-08 09:00 UTC
Labels: (S2 - Confirmed), <Bug>, Vehicles, Z-levels
