### ISSUE TITLE
Smashed chickenwire fences leave the wrong fence-posts

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38987] opened 2020-03-24 06:37 UTC
# Describe the bug

When zombies or survivors smash chickenwire fences, they leave behind regular fence posts. However to build a chickenwire fence, a special "chickenwire fence post" is required.

# Steps To Reproduce

1. Find some chicken wire.
1. Smash it, or have a zombie smash it for you.
1. Observe the fence-post is not a chickenwire fence post.

# Expected behavior

Chickenwire fences should deconstruct to use the same type of posts as their construction.

# Versions and configuration

6fc9301c2239e6a4da9c8751162dc92cc03dcc1a with custom patches applied.

**Comment by natsirt721** [comment] 2020-03-24 21:54
related - when they smash a split-rail fence, they also leave fence posts, despite the split-rail fence construction option not having that as a stage

**Comment by wapcaplet** [comment] 2020-03-25 02:52
Looking at the JSON for this and similar terrains, I think this may be by design, since smashing always yields inferior components to a proper deconstruction. If you deconstruct such a fence, you should get back the original terrain (I didn't test with chickenwire particularly, but with a barbed wire fence that works similarly):

https://github.com/CleverRaven/Cataclysm-DDA/blob/5a950e81ccb5ac72575d045eefc8d86657dc735e/data/json/furniture_and_terrain/terrain-fences-gates.json#L418-L429

**Comment by pjf** [comment] 2020-03-25 05:06
The chicken-wire fence does give back inferior materials when smashed, you
lose some of the wires.

The chicken-wire posts require planks and nails to build. Regular posts
require pointy sticks and a shovel.

Having the posts transform does not seem like a feature.

**Comment by Night-Pryanik** [comment] 2021-04-14 18:11
Closed by #42776.

**Closed by Night-Pryanik** 2021-04-14 18:11 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Fields / Furniture / Terrain / Traps
