### ISSUE TITLE
Dragging a safe results in the safe dropping it's items

### ISSUE THREAD

**Issue by AdeenDragon** [CleverRaven/Cataclysm-DDA#46509] opened 2021-01-03 06:27 UTC
# Describe the bug

When 'G'rabbing a safe and dragging it over a pile of items, the safe exchanges its contents with the stuff on the ground.

# Steps To Reproduce

1. Go to a bank or other location with a safe
2. Next to the safe, drop an item you don't care about
3. 'G'rab the safe and drag it over the item you don't care about
4. Enjoy the contents of the safe

# Expected behavior

I'd expect that similar to dragging a bookcase, the safe would collide with the items and not allow you to further drag the safe.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8524-g3961bcd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Bootleg Walkers [Bootleg_Walkers],
    Gun Cotton [guncotton],
    sees-player icon, retrodays [sees_player_retro],
    Alternative Map Key [alt_map_key],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I've attached my save, the character Test McTest is in a bank vault, ready to demonstrate the bug.
[auto_after_end199.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5761278/auto_after_end199.zip)

**Comment by wapcaplet** [comment] 2021-01-03 14:45
Looks like a duplicate of bug #35374

**Closed** 2021-01-03 14:46 UTC
Labels: (S3 - Duplicate), <Bug>, <Exploit>
