### ISSUE TITLE
Menu Description in Zone Activity Manager (O) cut off

### ISSUE THREAD

**Issue by RobertBoettcherSF** [CleverRaven/Cataclysm-DDA#76282] opened 2024-09-08 10:15 UTC
### Describe the bug

Open Zone Manager (Shortkey O) and you have 3 options to sort. But cant read well what the options are about.

### Attach save file

[Massachusets - Dawn of the Dead-trimmed.tar.gz](https://github.com/user-attachments/files/16921794/Massachusets.-.Dawn.of.the.Dead-trimmed.tar.gz)

### Steps to reproduce

1. After designating Zones, open Zone Manager (0)
2. Cant read descriptions.

### Expected behavior

Being able to read descriptions.

### Screenshots

![2024-09-08](https://github.com/user-attachments/assets/8700d40a-4891-422e-9587-269810342877)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 6dc777e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife],
    Dark Days of the Dead [classic_zombies],
    Massachusetts [MA],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Generic Guns [generic_guns]
]

**Comment by CoroNaut** [comment] 2024-09-08 10:49
There is quite a few menu descriptions on quite a few imgui interfaces that are cut off. There are more than just your and my examples too. its just in the integration hell phase. Best of luck to them to get the kinks buffed out.
Workout menu:
![Untitled](https://github.com/user-attachments/assets/9dc455e4-f9a2-4835-ab07-04d653a21011)
Execute action menu:
![Untitled](https://github.com/user-attachments/assets/0946194b-5a9a-4a45-b838-54fc5d36e4f3)
Even the examine window has the scrollbar cutting off the letters on the right side a bit:
![Untitled](https://github.com/user-attachments/assets/45b2ac67-ed79-4b81-b49f-2d1834e120bb)

**Comment by Meadevil** [comment] 2024-09-09 03:02
Not only are the descriptions cut off on the bottom of the imgui window,  also it is too wide with lots of empty space on the right side. In my case it pushes the menu beyond the app window. 
![Screenshot_20240909_115944](https://github.com/user-attachments/assets/14f02ec7-15f1-45e1-a0dd-190e06703382)

**Comment by GuardianDll** [comment] 2024-09-11 13:19
Closing it as duplicate of #75698, gonna be fixed by #76356

**Closed by GuardianDll** 2024-09-11 13:19 UTC
Labels: (S1 - Need confirmation)
