### ISSUE TITLE
Luggage Cart falling down a ledge

### ISSUE THREAD

**Issue by Elitrom** [CleverRaven/Cataclysm-DDA#57542] opened 2022-05-08 09:53 UTC
### Describe the bug

In a hotel in a city called Woodstock, there was something that generated 100 to 500 "smash!" sounds each turn which attracted a lot of zombies. On the first floor they were luggage carts that had fallen down a hole in the ceiling (a 3x3 ledge) but they still appeared on the first floor as if their floating or falling down a hole a 100 to 500 times a turn (which created a lot of lag). 

Once the carts were removed from the ledge, the sounds and lag stopped. I dropped the luggage cart on the side of the building roof instead of the hole in the center but this time it fell down a level normally (last 2 images).

### Steps to reproduce

1. Have a luggage and a hole in the middle of a ceiling of a building.
2. Drag the luggage crat by pressing G.
3. Drop the luggage cart down the hole in the middle of a ceiling of a building.

### Expected behavior

The luggage cart should have fell down a level and make a single loud sound.

### Screenshots

![Capture d’écran (530)](https://user-images.githubusercontent.com/103608705/167290156-44ee606f-7ec3-4898-8363-944bb6550f1c.png)
![Capture d’écran (531)](https://user-images.githubusercontent.com/103608705/167290157-1ea0523c-d18f-4c6e-8df9-5ae621bb6dfb.png)
![Capture d’écran (532)](https://user-images.githubusercontent.com/103608705/167290159-23c9f042-6b54-476e-b2a1-e28258e14b2d.png)
![Capture d’écran (533)](https://user-images.githubusercontent.com/103608705/167290160-1fd1a974-161d-43a5-800f-9598b35b828b.png)
![Capture d’écran (534)](https://user-images.githubusercontent.com/103608705/167290161-08a94a23-ba23-486d-85e9-db0e31ce5531.png)
![Capture d’écran (535)](https://user-images.githubusercontent.com/103608705/167290162-33e74c71-f60d-4f84-a87b-29f54679cffb.png)
![Capture d’écran (536)](https://user-images.githubusercontent.com/103608705/167290163-b3cf134e-362d-43b0-a2ec-21f474956672.png)
![Capture d’écran (537)](https://user-images.githubusercontent.com/103608705/167290164-d1162731-306a-4fc6-8edf-24e8feb08b5f.png)
![image_2022-05-08_114116404](https://user-images.githubusercontent.com/103608705/167290527-8e66fa6f-c9a2-4d8a-9935-1f95c049334f.png)
![image_2022-05-08_114552859](https://user-images.githubusercontent.com/103608705/167290701-1949c427-2dd2-4229-b2d8-c927f341187c.png)

### Versions and configuration

- Windows 10
-  I'm using 0.F-2 Frank-2 version
- MSXotto+ tileset
- English language
- No mods

**Comment by ZhilkinSerg** [comment] 2022-05-08 10:37
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/56477

**Closed by ZhilkinSerg** 2022-05-08 10:37 UTC
Labels: (S1 - Need confirmation)
