### ISSUE TITLE
Crash while driving

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41867] opened 2020-07-05 17:00 UTC
# Describe the bug

Game crashes while driving in the middle of nowhere.

# Steps To Reproduce

[save here](https://drive.google.com/file/d/1qbWjan_Pwlyr89QYfibHDmSNeabfFJ2I/view?usp=sharing[)
Load and drive the road east then south then east. Couple of screens later it will crash.

# Expected behavior

No crashes.

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-3726-g8aaf68f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4875291/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4875292/debug.log)

**Comment by olanti-p** [comment] 2020-07-05 18:02
Duplicate of #41804

**Closed** 2020-07-05 18:04 UTC
