### ISSUE TITLE
[Sugesstion]Drop the obsolete PK_REBALANCE mod in current master

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#21952] opened 2017-09-21 08:31 UTC
The mod is maintained in another repo.

I sugesst we drop the outdated one in the current master so that cdda-launcher wont try to overwrite the uptodate version with an obsolete one when updating the core game.

See issue https://github.com/pisskop/PKs_Rebalancing/issues/30.

**Comment by ZhilkinSerg** [comment] 2017-09-21 08:45
Pisskop just should've changed `ident` of the mod when it was moved to separate repository.

**Comment by Leland** [comment] 2017-09-21 13:33
Duplicate of #20326

**Closed by Leland** 2017-09-21 13:33 UTC
