### ISSUE TITLE
Allergen flags need to be updated to account for some existent materials

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#66649] opened 2023-07-03 23:21 UTC
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/bf8b27b2-cad5-43c5-bd4a-a13d402f866c)

Carnivore (missing bread, `dried_vegetable`):
https://github.com/CleverRaven/Cataclysm-DDA/blob/19858bf5bd4de6f75df3d96265d578a2b8dd4398/src/consumption.cpp#L155-L158

Vegan (missing cheese):
https://github.com/CleverRaven/Cataclysm-DDA/blob/19858bf5bd4de6f75df3d96265d578a2b8dd4398/src/consumption.cpp#L831-L835

Flags assigned here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/19858bf5bd4de6f75df3d96265d578a2b8dd4398/src/item_factory.cpp#L3470-L3504

Any new allergen flags need to be defined in data/json/flags.json

### Attach save file

N/A

### Steps to reproduce

Debug carnivore and eat these materials ingame:

bread (found on caviar & egg sandwich)
dried_vegetable (not functionally used on any current items but exists so should be classified accordingly)

Debug vegan and eat these materials ingame:

cheese (not functionally used on any current items but exists so should be classified accordingly)

### Expected behavior

Carnivores shouldn't be able to eat non-meat materials

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: c94dc03 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by fyhannes** [comment] 2023-07-04 06:01
<img width="1376" alt="Screenshot 2023-07-03 at 11 01 03 PM" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/29219984/28566892-81e2-48ff-a90a-d79e982d234d">
Could you clarify what the issue is with Vegan and cheese? I spawned a character, debug-added Vegan and tried to eat a spawned Cheese but could not.

**Comment by fyhannes** [comment] 2023-07-07 07:42
Can close, resolved with #66669

**Closed** 2023-07-07 08:17 UTC
Labels: Good First Issue, (S1 - Need confirmation), [JSON], [C++]
