### ISSUE TITLE
cant heat up liquids

### ISSUE THREAD

**Issue by bradspit** [CleverRaven/Cataclysm-DDA#36796] opened 2020-01-07 20:23 UTC
# Describe the bug

I cant heat up liquids in containers !

# Steps To Reproduce

1.put a liquid in a container like tea or water
2. go near a fire source
3. heat it up , wont work

# Expected behavior

some liquids tastes better when hot so better enjoyability, but I cant make them hot

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration
- OS: Windows 10
- Game Version: 0.D-11072-g9ea9f81 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
   No Fungal Monsters [No_Fungi],
   Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

**Comment by ZhilkinSerg** [comment] 2020-01-07 21:12
You did not followed issue template and omitted game version info.

**Comment by ZhilkinSerg** [comment] 2020-01-07 21:18
I cannot reproduce the issue on latest experimental version - it is possible to liquid into container and heat it up. So, please go into more details - which container and liquid did you use, was container in inventory or on the ground, etc.

**Comment by bradspit** [comment] 2020-01-07 21:40
sorry for my laziness , I updated the game version, also I used a stone pot and put a tea in it, and used the use item menu to heat the food in the pot, but my character drink the tea without heating up

**Comment by nullptr98** [comment] 2020-01-07 21:42
this is a duplicate of #36680 which is related to #36597, a fix for both bugs is proposed but hasnt been reviewed yet.

**Comment by bradspit** [comment] 2020-01-07 21:50
Also I was wielding the pot

**Comment by Alapaga** [comment] 2020-01-08 07:15
from what i understand, you wanna heat up tea that's sitting in the pot you wanna use for heating. That never seemed to work that way. The way it seems to work is as follows : you need the liquid that you want to heat up to be in a separate container, and the pot you wanna use for heating to be empty before activating it.

**Comment by ZhilkinSerg** [comment] 2020-01-08 07:17
Duplicate of #36680

**Closed by ZhilkinSerg** 2020-01-08 07:17 UTC
Labels: (S3 - Duplicate), Food / Vitamins
