### ISSUE TITLE
Crash on aftershock bionic install by Rubik

### ISSUE THREAD

**Issue by shell1610** [CleverRaven/Cataclysm-DDA#64917] opened 2023-04-07 20:13 UTC
### Describe the bug

Game crashes when Rubik installs aftershock bionic (gravyfield).

### Attach save file

[Pepeekeo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11181270/Pepeekeo-trimmed.tar.gz)

### Steps to reproduce

1. Talk to Rubik and have him install the CBM in inventory (Gravyfield).

### Expected behavior

Complete install/fail

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: fef3110 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries]
]

### Additional context

All non-aftershock bionics installed fine.

**Comment by SurFlurer** [comment] 2023-04-08 15:10
Seems to be duplicate of #64036.

**Closed** 2023-04-08 17:56 UTC
Labels: (S3 - Duplicate)
