### ISSUE TITLE
Can't disassemble multiple items

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50716] opened 2021-08-12 15:31 UTC
### Describe the bug

"disassemble everything once" no longer works

### Steps To Reproduce

1. Drop multiple items on the ground for disassembly
2. Open 'B'utchery/disassembly context
3. Choose "disassemble everything once"

### Expected behavior

All valid items should be disassembled

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f8bd78 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

**Comment by actual-nh** [comment] 2021-08-12 16:01
Duplicate of #50686.

**Closed** 2021-08-12 16:04 UTC
Labels: <Bug>, (S3 - Duplicate), Crafting / Construction / Recipes
