### ISSUE TITLE
Bows crash when used. (solved.)

### ISSUE THREAD

**Issue by Moonsabrt** [CleverRaven/Cataclysm-DDA#15492] opened 2016-02-20 08:44 UTC
Yoh i am not sure if this is the same bug, but here is what i am saying using the same fix for ranged weapons it seems that it crashes whenever i press the fire button, i have used a shortbow from the ground, from a quiver and from the invontory and even the self bow. They all result in the same crash, they crash when you press the fire button. I have used the size bug fix.
120 55 whatever and using pistols it works fine. It just crashes for bows.

**Comment by chaosvolt** [comment] 2016-02-20 08:55
So the bows crash even if you bump the window size up enough? That would logically be a separate issue then.

**Comment by mugling** [comment] 2016-02-20 20:16
Can you post the version your using, any mods and the exact steps to reproduce

**Comment by mugling** [comment] 2016-02-20 20:41
> even if you bump the window size up enough?

Likely to be this.

@moonsabrt You need a version that includes the fix from #15227

**Comment by Moonsabrt** [comment] 2016-02-21 02:26
Yes, well as i sad, apoligies for the huge delay i was sick. Anyway i used the most recent experimental version and currently updated it using the cdaa launcher. build 4442, and i am currently using the following mods. No acid zombies , and slow zombies. After grabbing a shortbow and modding it with arrow rest it currently crashes the game i have removed the arrow rest and it still crashes the game. Made a seperate folder and changed the size to the following fix of the reload bug and it still crashes.

**Comment by ejseto** [comment] 2016-02-21 04:37
Can't reproduce. Can you post your save or *exact* set of steps to reproduce?

**Comment by Moonsabrt** [comment] 2016-02-21 05:13
Nevermind fixed it myself, just bump the screen size to 140......SOMEONE FIX THAT FREAKING MENU.

**Comment by Malkeus** [comment] 2016-02-21 05:59
#15477 was supposed to fix this, it got merged about 14 hours ago. Do you still have a crash at small screen size after updating?

**Comment by ejseto** [comment] 2016-02-21 06:00
>I have used the size bug fix.

Yeah?

>So the bows crash even if you bump the window size up enough?

Hmm, that does sound like what he said.

>Nevermind fixed it myself, just bump the screen size to 140

Or does it?

>SOMEONE FIX THAT FREAKING MENU.

Can you not demand solutions to problems you misreport, and which have actually already been fixed? Frankly, you should apologize. I wonder how many people were running in circles trying to reproduce your crash.

>#15477

Look what we have here.

**Comment by Malkeus** [comment] 2016-02-21 06:08
Hmm, I just checked Jenkins. #15477 landed in build 4442, which Moonsabrt said he had updated to...so, I'm still not sure what's happening if he had to bump screen size to 140 to avoid the crash. Moonsabrt, can you give a clear concise report on a crash after updating to 4442 or later, minus the demands for fixes and especially the caps, which IS considered rude in every text based communication the human race has created...It's basically like calling someone on the phone and screaming into the receiver.

**Comment by chaosvolt** [comment] 2016-02-21 06:09
It's bad enough that I went and derped about back when it was first discovered that the initial fix for The Bug That Will Not Die left unresolved complications.

**Comment by Moonsabrt** [comment] 2016-02-21 06:51
Apoligies nonetheless, guess in the end it was just increase screen size.Didnt bother to increase the screensize beyond 125 at first but after a inspiration, yeah turned it up to 140.......Works...apoligies nonetheless.

**Comment by mugling** [comment] 2016-02-21 10:22
@Moonsabrt you can close this issue now, it was resolved by #15227 as @Malkeus and @ejseto have confirmed

**Comment by mugling** [comment] 2016-02-27 10:41
Needs closing

**Closed** 2016-02-27 10:53 UTC
