### ISSUE TITLE
Game consistently loads slowly, freezes, and crashes randomly

### ISSUE THREAD

**Issue by Starcluster0** [CleverRaven/Cataclysm-DDA#50880] opened 2021-08-18 22:12 UTC
### Describe the bug

C:DDA at random seems to freeze and then crash, it also appears to load more slowly.

### Steps To Reproduce

I do not understand the necessary steps to reproduce this.

### Expected behavior

I am unable to play the game for extended periods of time, I should however be able to with 32 gigs of 3200 Mhz ram, a RTX 3070, a core i7-10700K and a 500 Gb SSD. I am sorry if I am not providing very good information on the subject, as reporting a problem is relatively new to me. 

### Versions and configuration

- OS: Windows 10
- Game Version: ed2f630
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Stats Through Skills, Aftershock, No NPC Needs, Blaze Industries, Cata ++, Engineering Essentials, CRT Expansion, Speedy Dex, and Package Bionic Professions

### Additional context

Source
cataclysm-tiles.exe

Summary
Stopped responding and was closed

Date
‎8/‎18/‎2021 2:10 PM

Status
Report sent

Description
A problem caused this program to stop interacting with Windows.
Faulting Application Path:	C:\Users\Simon\AppData\Local\CDDA\cataclysm-tiles.exe

Problem signature
Problem Event Name:	AppHangB1
Application Name:	cataclysm-tiles.exe
Application Version:	0.0.0.0
Application Timestamp:	00000000
Hang Signature:	d015
Hang Type:	134217728
OS Version:	10.0.19043.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	d015462d0e5aa7c7ae1a290845bb9010
Additional Hang Signature 2:	0aff
Additional Hang Signature 3:	0aff2ee23ba385ec7b189bb574eb6f51
Additional Hang Signature 4:	d015
Additional Hang Signature 5:	d015462d0e5aa7c7ae1a290845bb9010
Additional Hang Signature 6:	0aff
Additional Hang Signature 7:	0aff2ee23ba385ec7b189bb574eb6f51

Extra information about the problem
Bucket ID:	5fd714dd72dfa46beafdd58d322242e1 (1944945416502133473)

**Comment by hexagonrecursion** [comment] 2021-08-19 14:29
I am sorry, but in its current state this bug report contains no actionable information for the developers.

1. Did an earlier version of cdda work fine on your system?
2. How often does this happen?
3. You are saying that cdda loads slowly. At what point does this happen? Does it take a long time to see the main menu after clicking on the executable? Is loading a save file slow?
1. Reboot the computer. Do the problems persist?
2. Download the latest release from https://github.com/CleverRaven/Cataclysm-DDA/releases and unpack it into a new folder. Do not install any mods. Do not import any settings or saves. Create a new world. Is this fresh install also affected by the issue?
3. When the game freezes how much free memory does your system have? Is one of the CPU cores under 100% load?

**Comment by Zeropol** [comment] 2021-08-19 15:03
It is not a useless bug report.

While my personal bet is the problem is relevant mods ( Maybe "Engineering Essentials" because it is not mainlined ) it can be anything else.
This report could also represent what a sizeable proportion of ( win10, tiles ) people experience, but have not reported because of the process of doing it ( I don't report bugs for every games ).

Thanks for the report. Does `yourCdda\config\debug.log` contain anything related, or does the game freeze to death without any information consistent with the time it froze/crashed ?

**Comment by hexagonrecursion** [comment] 2021-08-29 05:46
Please post the contents of your yourCdda\config\crash.log if it exists

**Comment by wapcaplet** [comment] 2022-01-17 04:00
Closing as unreproducible.

**Closed by wapcaplet** 2022-01-17 04:00 UTC
Labels: (S1 - Need confirmation), OS: Windows
