### ISSUE TITLE
World doesn't start game and stays on Creating World

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#44345] opened 2020-09-22 15:31 UTC
# Describe the bug

When creating a world, the game stays on the Creating World screen, but doesn't go away.

# Steps To Reproduce

Create a world with various mods
start the world and create a character
the world doesn't get played

# Expected behavior

I can play actually play CDDA

# Versions and configuration

 - OS: Windows 10 version 10.0.19041 build 19041
 - Game Version: 0.E-6161-gac84e5c
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, disable NPC needs, Aftershock, Blaze Industries, CRIT, Magiclysm, Magic Martial Arts, SpeedyDex, Bionic slots

# Additional context

[Berrien Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5262466/Berrien.Springs.zip)

**Comment by Fosheze** [comment] 2020-09-22 21:28
I've been on a spree of just running random starts recently and I have been having this issue as well. It seems more common when starting with professions that start with a vehicle but it isn't exclusive to those professions. Only mods I'm currently running are remove rail stations and remove NPC needs.

**Comment by wapcaplet** [comment] 2020-09-25 03:15
Confirmed in version 0.E-6177-g 9f4a1b841d by using your world settings from [Berrien Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5262466/Berrien.Springs.zip), and starting a new character.

**Comment by xrogaan** [comment] 2020-10-01 20:05
I've seen similar results (game stuck on world building) when I tried to generate a world using both Aftershock and Blaze Industry, city size is set to 10 and city spacing to 7.

Running: version 0.E-6414-g994a2c3

[pinetown.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/5314482/pinetown.tar.gz)

**Comment by xrogaan** [comment] 2020-10-01 22:35
May not be the mods and settings combination but rather the randomized start location. I tried a prepper start, as a bionic prepper, with the same settings as attached above minus blaze's mod and got an "infinite" world building. Did it again but selected a location instead and the game put me into the world rather quickly.

**Comment by LyleSY** [comment] 2020-10-02 16:42
Any chance this is just some mandatory specials with very similar criteria in both mods causing trouble? Could one or both mods loosen up that mapgen code or not require them to be mandatory?

**Comment by xrogaan** [comment] 2020-10-02 16:51
As I said earlier, the issue can occur without blaze mod active. It
probably has to do with world generation and finding a good spot and/or
path.

**Comment by LyleSY** [comment] 2020-10-03 11:49
Jumping into Aftershock, I don't see any mandatory specials at all [https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Aftershock/maps/overmap_specials.json](url)
...but the Robot Dispatch was added recently and would spawn with these settings...but it was merged two days after this bug report. Ahem. Digging further back, my best guess is that the mortuary_2story is bugged somewhere, or it's something even older [https://github.com/CleverRaven/Cataclysm-DDA/pull/36908/files#diff-842e1f81e0fa08dcd23c83e67502499d](url)
Thankfully there aren't that many specials in Aftershock to troubleshoot

**Comment by xrogaan** [comment] 2020-10-04 17:30
I misspoke somehow, that's what happens when I don't get enough sleep. My apologies.

I said in a message above could reproduce the infinite "world creation" by trying to spawn an evac shelter, but what I meant was that I used the terminal in a shelter to spawn the *community center*. That behavior was with the same settings and mod list minus blaze industry.

**Comment by xrogaan** [comment] 2020-10-06 02:05
Hello, I retested with the latest experimental (`0.E-6527-g83721c4`) using another scenario (Large Building) and the world generation went smoothly this time.

**Comment by John-Candlebury** [comment] 2020-10-27 21:04
Is this not the same issue as #44736?

**Comment by wapcaplet** [comment] 2020-10-27 22:00
> Is this not the same issue as #44736?

The circumstances are different, but it is possible they have the same cause.

Retesting with my previously failed scenario (Aftershock + Blaze, City size 16, City spacing 8) in the current experimental 1ae4a801, I cannot reproduce this issue any longer.

**Comment by adinsx** [comment] 2020-10-28 02:29
I can still reproduce the issue with Aftershock + City size 16 + City spacing 8 on 1ae4a80. Have tried Evacuee, Wilderness, and Really Bad Day scenarios.

**Comment by kevingranade** [comment] 2020-12-13 23:50
Removing from blocker list as we don't guarantee that all configurations of the game will start successfully.  For stable play use default settings.

We WANT to fix this, but it's not something I can justify holding up a release over.

**Comment by Night-Pryanik** [comment] 2022-09-01 08:02
Tried right now on 0.F-10973: created world with Aftershock, 16 city size, 8 city spacing, default scenario. Started game ~10 times, all successful. It took longer time due to harsh world settings, but in the end game started nevertheless. There was also "Can't find suitable location" error several times, but that's different issue, and after several retries game successfully found starting location.
I'm closing this now. If this issue (eternal creating world window) is still valid, ping to reopen.

**Closed by Night-Pryanik** 2022-09-01 08:02 UTC
Labels: <Bug>, (S2 - Confirmed), Mods: Aftershock
