### ISSUE TITLE
#9925 Attempting to apply bandage (from nearby terrain/furniture) to damaged body part causes crash.

### ISSUE THREAD

**Issue by KrunkySmokin** [CleverRaven/Cataclysm-DDA#35675] opened 2019-11-23 12:34 UTC
Attempting to apply a bandage to a damaged body part from anywhere but the inventory is crashing the game. I ran across this in my main world and thought it might be a mod issue, so I made a quick world with only CDDA and Disable NPC Needs to test this. It occurred in this world just the same as it did in the modded, so it for sure isn't any of the mods I'm running. 

Crash Log at the bottom of the post

# Steps To Reproduce

- Load game
- Damage limb
- Attempt to apply bandage from nearby terrain

# Expected behavior
The game crashes, segmentation fault.

#Additional Info
If you apply the bandage from your inventory, it works like normal and doesn't crash the game.

- Crash log-
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3882427/crash.log)

**Comment by ZhilkinSerg** [comment] 2019-11-23 12:54
Duplicate of #35673

**Closed by ZhilkinSerg** 2019-11-23 12:54 UTC
