### ISSUE TITLE
Interaction with frozen (spilt) liquids is all kinds of borked

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#48806] opened 2021-05-09 05:37 UTC
# Describe the bug

Frozen spilt liquids don't make sense. See next section for examples.

# Steps To Reproduce

Spill the liquid on the ground, wait till it freezes. Then...
- trying to pick it up requires you to crush it (what? why??)
- ...and it warns you about other fragile items on the tile (at least I guess it's on the tile? "nearby" is kinda vague AF. And which items exactly are fragile? is it only clothes with that tag? or something else?)
- after you crushed and picked it up, you cannot interact with it neither via AIM nor can you select it for multidrop(!)
- but there actually *is* a way to drop it - from the item menu
- from that same item menu you can find out that you are not allowed to wield nor throw it because it still counts as "spilt liquid" (despite it being frozen)
- and the cherry on top - imagine you want to pick it up again for some insane reason. Well, you better crush it **again** because if you don't the game will say you cannot pick up spilt liquids...

# Expected behavior

We can pick frozen liquid up as a regular item, if it is not inside a container. We can drop them without going on a quest for interface element allowing us to do so. We can interact with them via AIM and all other interface parts that are supposed to allow us doing that.

# Versions and configuration

 - OS: Windows 7
 - Game Version: github build 15, the one Kevin asked us to playtest. Also happens on b11582.
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock],
Magiclysm [magiclysm],
Alternative Map Key [alt_map_key],
sees-player icon, retrodays [sees_player_retro],
Stats Through Skills [StatsThroughSkills],
Bionic Professions [package_bionic_professions],

**Comment by RoyBerube** [comment] 2021-05-14 02:33
If it is allowed to be picked up outside a container and it melts, then what happens? The container requirement is for that reason.

**Comment by GGgatherer** [comment] 2021-05-14 17:08
it does not require a container. The only thing it requires is for you to "crush" it, for some reason (it doesn't say "crushed" or anytihng like that in description afterwards). After that, you can put it right into your backpack.
And I think if it melts it should just drop on ground as spilt liquid, unless it was in sealed container, but this isn't what this issue is about.

**Comment by GGgatherer** [comment] 2021-05-28 13:24
ROFL. You know what happens if you actually leave that crushed ice in your backpack and move somewhere where the temperature is over 0 Celsius?
[It melts and the resulting liquid stays inside the backpack](https://youtu.be/YB8ZRwcX0Vk?t=2404).

**Comment by hexagonrecursion** [comment] 2021-08-23 11:17
It is easier to keep track of each bug or feature as a separate issue. I can repost this as separate issues. Should I?

**Comment by hexagonrecursion** [comment] 2021-08-25 14:17
> after you crushed and picked it up, you cannot interact with it **via AIM**

Could not reproduce this part: I was successfully able to drop frozen clean water via AIM

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 2970a2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment] 2022-01-16 05:39
Thanks @hexagonrecursion for splitting these up into manageable chunks. With all the parts covered in separate issues, I am closing this one.

**Closed by wapcaplet** 2022-01-16 05:39 UTC
Labels: (S3 - Duplicate), Items / Item Actions / Item Qualities, Mechanics: Temperature, Items: Containers
