### ISSUE TITLE
map::shoot does not handle laminated glass doors

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#47664] opened 2021-02-22 11:24 UTC
# Describe the bug
It is possible to shoot through laminated glass doors with any projectile (for example BBs) and the door will never be destroyed.

# Steps To Reproduce

Find a laminated glass door, get a BB gun, kill unarmoured zombies behind it with BBs.

# Expected behavior

Laminated glass doors should be handled in the same way as laminated glass walls.

# Screenshots

![Screenshot from 2021-02-22 22-16-59](https://user-images.githubusercontent.com/4125929/108701665-5a752600-755c-11eb-9e03-f606505027cf.png)

# Versions and configuration

Recent experimental, no mods.

# Additional context

Fix seems pretty simple, just need to update the function to handle t_laminated_door_glass_c. Although, given that everything is hardcoded, I have a feeling there are probably other types of terrain that don't get handled correctly.

**Comment by anothersimulacrum** [comment] 2021-02-22 15:39
Duplicate of #33374

**Comment by jagoly** [comment] 2021-02-23 03:44
> Duplicate of #33374

Would you mind having another looks at this? It's not a duplicate.

The other issue is about being able to shoot through glass at all, which is in fact an intended feature. This issue is about closed laminated glass doors not being handled by the existing code. CLGDs do not reduce bullet damage, they do not have a chance to shatter. Other glass types do.

In fact, the other issue should probably be closed as not a bug. The problem being discussed there is about terrain not accumulating damage, which already has https://github.com/CleverRaven/Cataclysm-DDA/issues/45598.

**Comment by anothersimulacrum** [comment] 2021-02-23 04:05
> Would you mind having another looks at this? It's not a duplicate.

> The other issue is about being able to shoot through glass at all, which is in fact an intended feature. This issue is about closed laminated glass doors not being handled by the existing code. CLGDs do not reduce bullet damage, they do not have a chance to shatter. Other glass types do.

Okay, so this is about that horrible massive if tree in map::shoot not touching it?
Suggestion then - replace all those terrain id checks with terrain flag checks.

> In fact, the other issue should probably be closed as not a bug. The problem being discussed there is about terrain not accumulating damage, which already has #45598.

I'd rather close the second one - you need to dive in both to find a wanted solution, and the first has it as an actual comment instead of a link.

**Closed** 2021-07-11 01:04 UTC
Labels: Good First Issue, [C++]
