### ISSUE TITLE
Cash Card is not my favorite food.

### ISSUE THREAD

**Issue by Pyritefoolsgold** [CleverRaven/Cataclysm-DDA#45518] opened 2020-11-20 04:51 UTC
# Describe the bug

After the most recent update, If I have any favorited item in my inventory, then any time I attempt to eat anything or examine the favorited item in my inventory, I am prompted with "Do you really want to eat your Slingshot/Nail Bat/Cash Card." This gets in the way of eating stuff and is really annoying. [Also attempting to favorite an actual food item seems to lead to a crash.] Update: this only seems to happen when I try it on the protein ration from the Evacuation Shelter.

# Steps To Reproduce

1: Favorite any non-edible item.
2: Use the (E)at command and see the dialogue box pop up.
3: Unfavorite the first item, and then favorite any edible item other than a protein ration and  notice that the prior behavior does not occur, and that you can use (E)at or inspect the item in your (I)nventory without issues.
4: Unfavorite the second item, and favorite a protien ration. Watch the game crash.

# Expected behavior

Favoriting an item should just highlight it in inventory I guess, I'm not really sure if it does anything else. It should not have anything to do with eating and definitely shouldn't crash the game.

# Screenshots

![Favorite Food](https://user-images.githubusercontent.com/9997796/99754701-d6635c00-2a9d-11eb-8a6e-022bdcb200bd.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7619-g4f7bfb5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I liked to favorite the contents of my wallet to keep it separate from other wallets I pick up, but now I'll have to like, write on them or something.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5571282/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5571283/debug.log)
[Test World Aplha.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5571276/Test.World.Aplha.zip)

**Comment by anothersimulacrum** [comment] 2020-11-20 04:57
Duplicate of #45509

**Closed by anothersimulacrum** 2020-11-20 04:57 UTC
Labels: (S3 - Duplicate)
