### ISSUE TITLE
Powdery items should not be so easily stored without a container

### ISSUE THREAD

**Issue by Sniper27IT** [CleverRaven/Cataclysm-DDA#56481] opened 2022-03-30 21:17 UTC
### Is your feature request related to a problem? Please describe.

At the moment, you can pick up items like flour, salt or other powder items without the need to store them in a container like a plastic bag. This has also the advantage of collecting these items with no volume hassle as storing loose powder takes less space than using a plastic bag.
This is very unrealistic as in real life you can't simply put some loose flour in your pockets and expect to bring out the very same amount

### Solution you would like.

Powder items like these should behave in a similar way to liquids, requiring any sort of container to properly store, and should not be able to be picked up if they are loose (or they could be picked up with some sort of "loss" due to their powdery nature)

### Describe alternatives you have considered.

Another simpler solution would be to just add the "loss" i described above: i store 150 units of loose flour in my backpack, i take out 125 units instead when i handle it the next time because it's loose powder, my pc being able to scoop every single grain of powder is kinda unrealistic.

### Additional context

I didn't check if someone else brought this up, in that case i apologize.

**Comment by NetSysFire** [comment] 2022-03-30 23:07
Duplicate of #55422

**Closed by NetSysFire** 2022-03-30 23:07 UTC
