### ISSUE TITLE
Arithmetical error.

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#29102] opened 2019-03-29 06:21 UTC
**Describe the bug**  
This might be the same crash i [posted before](https://github.com/CleverRaven/Cataclysm-DDA/issues/29043) if so please remove this.

Crashing while exploring/looting town. Seems to be related to car wrecks or player/zombie interaction with them, as it tends to happen near wrecks.

**To Reproduce**  
1. Walk near the car wreck
2.Crash happens.
**Expected behavior**  
When walking near a car wreck the game seems to crash, not always but frequently. 

**Screenshots**  
The error.
![error](https://user-images.githubusercontent.com/26538192/55213229-566aed00-51fb-11e9-8dc9-e15973699de8.PNG)
Screenshot where game crashed.
![screen](https://user-images.githubusercontent.com/26538192/55213260-6c78ad80-51fb-11e9-9348-095970a784f3.png)

**Versions and configuration(please complete the following information):**
    OS: Windows 10 x64
    Game Version: 0.D-1136-g62adf89
    Graphics version: Tiles
    Mods loaded:
    Disable npc needs,Filthy clothing,
    (DP_RP)Remix Indicator,
    Vehicle Addition pack,Tanks and Other Vehicles, Folding parts Pack,
    Urban Development,More Locations,Fuji's More Buildings,
    Mutant NPCs,Alternate Map key,
    More Survival Tools, Medieval and Historic Content, Extended Realistic Guns,
    No Fungal Monsters
**Additional context**  
Save game: [save zip.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3021367/save.zip.zip)

Log:
CRASH LOG FILE: config/crash.log
VERSION: 0.D-1136-g62adf89
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:
    @0x556F05[cataclysm-tiles.exe+0x156F05]
    @0x557AB2[cataclysm-tiles.exe+0x157AB2]
    SMPEG_error+0x4B0B1@0xE2A4DD[cataclysm-tiles.exe+0xA2A4DD]
    _C_specific_handler+0x98@0x7FFAB31E8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFAB47F468F[ntdll.dll+0xA468F]
    RtlWalkFrameChain+0x14BF@0x7FFAB4754BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFAB47F33FE[ntdll.dll+0xA33FE]
    @0x613BDB[cataclysm-tiles.exe+0x213BDB]
    @0x6190A7[cataclysm-tiles.exe+0x2190A7]
    @0x684362[cataclysm-tiles.exe+0x284362]
    IMG_LoadWEBP_RW+0x4DB309@0x13F75D9[cataclysm-tiles.exe+0xFF75D9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFAB1B581F4[KERNEL32.DLL+0x181F4]
    RtlUserThreadStart+0x21@0x7FFAB47BA251[ntdll.dll+0x6A251]

**Comment by RickySandbox** [comment] 2019-03-29 09:26
This error occurred during the latest live stream video of Vormithrax @ 00:44:08, which forced a restart. He was driving away from a fungal tower area that was on fire.

**Comment by neitsa** [comment] 2019-03-29 18:02
For an unknown reason I haven't been able to determine to which build version `0.D-1136-g62adf89` is referring to... Is it `0.D-8680`?

**Comment by Necrosian** [comment] 2019-03-29 18:15
> 
> 
> For an unknown reason I haven't been able to determine to which build version `0.D-1136-g62adf89` is referring to... Is it `0.D-8680`?

Latest that was available at that time, cant tell more update to newest already.

**Comment by AMurkin** [comment] 2019-03-29 19:36
Commit 62adf89 is build 8681.

**Comment by ZhilkinSerg** [comment] 2019-03-30 08:46
Duplicate of #29043

![image](https://user-images.githubusercontent.com/16213433/55273805-2ac23280-52e1-11e9-8b05-e402b74ac6a1.png)

**Closed by ZhilkinSerg** 2019-03-30 08:46 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
