### ISSUE TITLE
Android version have an issue with the keyboard function.

### ISSUE THREAD

**Issue by ThomasLinkin** [CleverRaven/Cataclysm-DDA#34215] opened 2019-09-24 11:56 UTC
# Describe the bug

The game kicked me out every time i tried to turn on the keyboard twice in a few seconds

# Steps To Reproduce

1. Turn on the game
2. Press "Back" button to turn on the keyboard
3.Press "Back" again to turn it off
4. Turn it on again

# Expected behavior

It should be on everytime i press the "back" button. The same issue happen to 3 different keyboard app i used,so i suppose this belongs to the game itself

# Versions and configuration

Experiment version # 9664

**Comment by Night-Pryanik** [comment] 2019-09-24 14:51
I guess that's a duplicate of #33781.

**Closed by Night-Pryanik** 2019-09-24 14:51 UTC
Labels: OS: Android
