### ISSUE TITLE
Crafted candles have 0 charges

### ISSUE THREAD

**Issue by TGWeaver** [CleverRaven/Cataclysm-DDA#44226] opened 2020-09-17 15:33 UTC
# Describe the bug
A freshly-crafted candle starts with no wax/no charges and is thus useless. This seems to be the case regardless of which combination of ingredients is used.

# Steps To Reproduce
1. Start a new player with no mods
2. Spawn or find items to craft a candle (container, heat source, lard/tallow, material for wick)
3. Craft candle
4. Candle is already burnt out and has no wax

# Expected behavior
Candles should probably have wax so they can be lit.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5927-g27d4c34 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [    Dark Days Ahead [dda]     ]

# Additional context
Tangential, but potentially related: under a separate save file, I have added a purely decorative new furniture to the construction menu. One of its ingredients is defined as **[ [ "candle", 1 ] ]** . This construction will take craft candles (even with 0 charges) just fine, but any number of candles (all with different amounts of charges) I've collected from junk drawers in various houses do not seem to count, leaving the option red and saying "you cannot build that".

**Comment by Scorch-Mechanic** [comment] 2020-10-16 12:14
Just had this happen myself. 

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-6889-g0af511e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key]
]

[freshly crafted empty candle.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5391425/freshly.crafted.empty.candle.zip)

**Comment by kevingranade** [comment] 2020-10-28 02:43
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/how-do-candles-work-now/24719/3

**Comment by Mrzjadacz** [comment] 2020-11-15 22:46
Upon disassembling the survival kit you receive a glowstick with no charges. I guess it falls under the same bug.

**Comment by wapcaplet** [comment] 2020-11-15 22:58
This appears to have the same root cause as #31607 - that crafted batteries have no charges.

@Mrzjadacz The lack of charges when *disassembling* is a related but distinct issue - I believe that can be resolved in the same way as #45404, by adding the `FULL_MAGAZINE` flag to the deconstruction recipe.

**Closed** 2020-11-16 08:47 UTC
Labels: <Bug>, Crafting / Construction / Recipes
