### ISSUE TITLE
Crash on loading a savegame

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#37522] opened 2020-01-29 20:29 UTC
# Describe the bug

Crash on savegame loading

# Steps To Reproduce

1. Trying to load a game on 10273

# Expected behavior

game loads successfully 

# Screenshots

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4130531/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4130532/debug.log)

[Gracewood.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4130565/Gracewood.zip)

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-11736-g409d24e
 - Graphics version: tiles
 - Mods loaded: dda, no npc needs

# Additional context

<!-- Crash: if your problem refers to a crash, please add the following files to the "Additional Context" paragraph:
    - From the /config folder (you can zip them both together):
        - crash.log file.
        - debug.log file.

**Comment by ZhilkinSerg** [comment] 2020-01-29 20:37
The issue is fixed in build 10274.

P.S.: You've put game version and build number wrong. It is 10273 (not 10274) and 409d24e (not 409d243). I've edited issue body for you.

If you are using launcher - here where you can get version info (build number is also in `crash.log` and `debug.log`):

![image](https://user-images.githubusercontent.com/16213433/73395258-2b0bcf80-42f0-11ea-8990-5448afd57405.png)

**Closed** 2020-01-29 20:43 UTC
Labels: <Crash / Freeze>

**Comment by ektoplazm** [comment] 2020-01-29 21:21
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4130767/debug2.log)
now I'm getting this crash with similar error after loading a game, should I open another issue?

**Comment by ZhilkinSerg** [comment] 2020-01-29 21:39
That's another one - #37527 will help when merged. No new issue required.
