### ISSUE TITLE
Bug: "Morale "Bad Tempered" is inconsistent."

### ISSUE THREAD

**Issue by Fengren1998** [CleverRaven/Cataclysm-DDA#38641] opened 2020-03-08 13:27 UTC
### THE BUG
 DEBUG    : Morale "Bad Tempered" is inconsistent.

 FUNCTION : player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>
 FILE     : src/morale.cpp
 LINE     : 621

Just got into the world, and suddenly this happened as I pressed the Up Arrow Key. I was with an NPC named "Susy".

### STEPS TO REPRODUCE
1. Made a world
2. Played a character in Prison start, and died
3. Make a new character in Evacuee and Freeform character creation
4. Look at an NPC, then move up.

### VERSION
Build 10404

**Comment by Fris0uman** [comment] 2020-03-08 13:35
Duplicate of #38611

**Closed** 2020-03-08 13:38 UTC
