### ISSUE TITLE
Recruited Dynamic NPCs pick up Items even when told otherwise

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#34086] opened 2019-09-18 10:31 UTC
# Describe the bug

Dynamic NPCs pick up Items even when told otherwise

# Steps To Reproduce

I have included a save file in the bottom portion of this post. When you load up, you should be in a wooden shack next to a mutated NPC. This NPC will proceed to pick things up once you start performing actions. Another side effect of the bug is that when you trade, instead of all items being freely trade-able between yourself and the NPC, it acts as if they aren't in your faction, despite being visible in the faction tab.

# Expected behavior

I would have expected that if the "pick up items" option isn't toggled, the npc wouldn't pick up items. 

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-7694-g1b96c6f]
 - Graphics version: [Tiles]
 - Mods loaded: [
  "dda",  "no_npc_food",
  "aftershock",  "crt_expansion",
  "magiclysm",  "Tolerate_This",
  "craftgp",  "FIC_Weapons",
  "growable-pots",  "ew_pack",
  "makeshift",  "Medieval_Stuff",
  "More_Survival_Tools",  "nw_pack",
  "DinoMod",  "modular_turrets",
  "Salvaged_Robots",  "hydroponics",
  "mutant_npcs",  "MMA",
  "national_guard_camp",  "more_locations",
  "FujiStruct",  "deoxymod",
  "blazemod",  "Tanks",
  "necromancy",  "manualbionicinstall",
  "safeautodoc",  "novitamins",
  "speedydex",  "stats_through_kills",
  "StatsThroughSkills",  "Mining_Mod",
  "alt_map_key"]

# Additional context

[Witching Hour.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3625756/Witching.Hour.zip)

**Comment by BenlyAZ** [comment] 2019-09-18 16:41
They also can't be pushed/swapped, you can't arrange their equipment, and they can't be assigned crew seating in a vehicle, but all dialogue and examine options for followers are present.

**Comment by davidpwbrown** [comment] 2019-09-19 09:41
This is likely fallout from #34084 
If the game was saved again after the factions were messed up, then it is likely not recoverable to the previous state.
#34090 may fix it, depending on if it was saved again afterwards or not.

**Comment by mlangsdorf** [comment] 2019-09-19 11:44
Closing as a duplicate of #34084

**Closed by mlangsdorf** 2019-09-19 11:44 UTC
Labels: (S1 - Need confirmation), <Bug>, Items / Item Actions / Item Qualities, NPC / Factions
