### ISSUE TITLE
About world creation

### ISSUE THREAD

**Issue by vitaminlemonade** [CleverRaven/Cataclysm-DDA#65250] opened 2023-04-22 21:12 UTC
### Describe the bug

This appears every time I create a new world in the world generation, then I can't delete world and yet if i reopen the game all mod in the world will be gone besides DDA.

### Attach save file

N/A

### Steps to reproduce

1. Go to world creation and creation with any mod on

2. Go to the world that just created and try to delete world.

3. Reopen world and check the world mods

### Expected behavior

1. after creating world, the  result should not be same as image on top
2. try to Deleting world should not result crush and pop up as image on bottom
3. reopen the game and check world mods, there should be mods that I select and not only DDA

### Screenshots

![屏幕截图 2023-04-21 224322](https://user-images.githubusercontent.com/76979107/233806592-daaf0299-5c00-4c5c-891c-2e9fd3a27b6a.png)
![屏幕截图 2023-04-21 223829](https://user-images.githubusercontent.com/76979107/233806593-fd6db933-0a75-4bf3-a66a-86809f8bae28.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: af4a7b3 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda]
]

**Comment by RenechCDDA** [comment] 2023-04-23 04:04
Duplicate of #64328

Per the discussion in that thread, I recommend you try using the MSVC build.

**Closed by RenechCDDA** 2023-04-23 04:04 UTC
Labels: (S1 - Need confirmation)
