### ISSUE TITLE
Great Bow (min STR 18) unusable with 19 STR

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#25725] opened 2018-09-20 05:45 UTC
**Describe the bug**  
If your character has 15 base STR and the Very Strong Mutation which gives +4 STR, they still can't use the Great Bow.  

**To Reproduce**  
1. Make a player with a great-bow, less than 18 STR, and a mutation which gives them excess STR.
2. Try to fire the greatbow.
3. You can't.

**Expected behavior**  
Firing the great-bow, because 19 is greater than 18.

**Comment by Muffindrake** [comment] 2018-09-20 10:00
Can't reproduce. (`0.C-32332-g6af0a5cd84`)

Started a character with 17 STR, reduced to 15 STR due to pain. Unable to fire wooden greatbow. Used debug menu to gain Extremely Strong, raising current STR to 19/max to 21, am now able to fire wooden greatbow.

**Comment by mrkybe** [comment] 2018-09-20 14:35
Hmm odd.  I'll update this post with my save later.

**Comment by Night-Pryanik** [comment] 2018-09-26 13:11
Dupe of #25340.

**Closed by Night-Pryanik** 2018-09-26 13:11 UTC
Labels: (S1 - Need confirmation), <Bug>, Ranged
