### ISSUE TITLE
Bionic Sniper profession is missing USP .45

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#40472] opened 2020-05-12 06:51 UTC
# Describe the bug

As the title says on latest build (10652) the bionic sniper class has an empty holster and it's nowhere else on their person despite having mags
# Steps To Reproduce

start a fresh save with default mods, select bionic sniper profession

# Expected behavior

for there to be a gun to go along with the mags

# Screenshots

N/A
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2038-g163e5ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by YourCompanionCube** [comment] 2020-05-12 07:50
actually this seems to be an issue with all professions that start with a pistol in a holster

**Comment by homebass** [comment] 2020-05-12 07:58
for some reason related to nested containers most pistols don't seem to fit into holsters in general, probably related to that.

**Comment by ymber** [comment] 2020-05-12 08:29
Closing as duplicate of #40456. The M2010 mags are spawned with `contents-group` which I confirmed works and the USP is spawned in a holster using `container-item`. `container-item` and `contents-item` are handled by the same hack in `Item_factory::load_sub_ref`.

**Closed by ymber** 2020-05-12 08:29 UTC
