### ISSUE TITLE
Drinking from (infinite?) water source causes error - no water consumed.

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#76592] opened 2024-09-21 18:29 UTC
### Describe the bug

I recently started an Innawoods playthrough and ran into this issue when I couldn't find any way to contain water. I eventually bit the bullet and tried to drink from a small pond (not murky water) and wasn't able to consume any water.

I was able to reproduce this is a regular save as well.

` DEBUG    : Item location/name to be consumed should not be null.

 FUNCTION : finish
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\activity_actor.cpp
 LINE     : 3247
 VERSION  : 6805e26
`

### Attach save file

[Rural Ridge-trimmed.tar.gz](https://github.com/user-attachments/files/17085408/Rural.Ridge-trimmed.tar.gz)

### Steps to reproduce

Examine water tile
Consume water
See error

### Expected behavior

Character should consume the water without issues.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: 6805e26 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    DinoMod [DinoMod]
]

**Comment by RenechCDDA** [comment] 2024-09-21 18:39
Duplicate of #76425

**Closed by RenechCDDA** 2024-09-21 18:39 UTC
Labels: (S1 - Need confirmation)
