### ISSUE TITLE
Error when filling condom that is stored in small container when larger container is available

### ISSUE THREAD

**Issue by BoatNectar** [CleverRaven/Cataclysm-DDA#56183] opened 2022-03-18 10:30 UTC
### Describe the bug

Whenever I go to fill a condom stored in a small container or pocket (eg pants pocket) while carrying a larger container (eg empty duffel bag) I get an error on every turn that the condom remains in an unfit container or pocket.

### Steps to reproduce

1. Get a container or article of clothing with a maximum volume smaller than a filled condom (filled condom is around 5L) but larger than an unused condom
2. Get 1 (or more) condom(s)
3. Get a bag capable of holding your full condoms making sure the unused condoms are kept in the first container
4. Interact with a water source such as a pond or puddle and fill your condom(s) with water an error will occur and will reoccur every turn

### Expected behavior

Ideally the game would move the condom to an appropriate container if available and prompt the player when trying to fill a condom they don't have space to carry and give them the option to drop the filled condom or cancel filling.

### Screenshots

![image](https://user-images.githubusercontent.com/75102677/158986217-070c69d8-9960-41d7-a442-dc798708dcd2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 714f560 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

 DEBUG    : volume exceeds capacity (5610ml > 1600ml)

 FUNCTION : relative_encumbrance
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_contents.cpp
 LINE     : 1872
 VERSION  : 714f560

**Comment by NetSysFire** [comment] 2022-03-25 07:00
Can reproduce, but it may be a semi-duplicate of #47046

In this case I spawned a dress shirt, put the condom in its pocket, wore a duffel bag I spawned and filled the condom with water, then got the errors.

**Closed** 2022-08-10 19:32 UTC
Labels: <Bug>, (S3 - Duplicate), (S2 - Confirmed), [C++], Items: Containers
