### ISSUE TITLE
Fungal Hedgerow hostile to Fungal Tower

### ISSUE THREAD

**Issue by Ioncloud9** [CleverRaven/Cataclysm-DDA#61128] opened 2022-09-19 19:15 UTC
### Describe the bug

Once you reach the point where the tower welcomes you, the hedgerows turn hostile to the tower, if you wait around they will actually kill the towers. I verified this on a brand new game with default mods.

![image](https://user-images.githubusercontent.com/8564227/191096000-855cec6a-a25e-4eb9-afb3-3267d3c37fc6.png)

Before it welcomed me, it seemed to be fine. I'm not sure if the tower turns friendly and then the hedgerow becomes hostile to the tower... but both the hedgerow and the tower show that they are friendly toward me.

### Steps to reproduce

1. Start a new game
2. Spawn and eat berries till you get carrier
3. Spawn and eat seeds till you get vector
4. Warp to a Fungal Tower
5. Wait around and the Hedgerow will start killing the tower

### Expected behavior

Hedgerow should not kill the tower

### Versions and configuration

- Game Version: a410b05

**Comment by Ioncloud9** [comment] 2022-09-19 19:17
Just to add to this, there are 3 fungal towers... not sure if this is intended

![image](https://user-images.githubusercontent.com/8564227/191097706-8ec9f508-1a87-4c68-b535-7bfb52b0c091.png)

**Comment by Night-Pryanik** [comment] 2022-09-24 12:35
Duplicate of #43312.

**Closed by Night-Pryanik** 2022-09-24 12:35 UTC
Labels: (S1 - Need confirmation)
