### ISSUE TITLE
Fish traps don't recognize loaded bait

### ISSUE THREAD

**Issue by jbarnard1** [CleverRaven/Cataclysm-DDA#42276] opened 2020-07-19 18:59 UTC
Plastic fish traps don't work properly, they give the following message:
`Fish are not foolish enough to go in here without bait.`

### Steps to Reproduce
1. Make new world
2. Make new character
3. Spawn a plastic fish trap
4. Activate fish trap
### Expected behavior
Trap is set, 3 hours later, fish trap deactivates and creates a fish
### Actual behavior
Trap does not set because it is unloaded
### Screenshot
![image](https://user-images.githubusercontent.com/55034465/87882670-a4e36280-c9cf-11ea-8bca-d91de27fbd45.png)
### Version information
OS: Windows
Game Version: 0.E-4254-gfea0266 [64-bit]
Graphics Version: Tiles
Game Language: System Language
Mods Loaded: [ Dark Days Ahead [dda], Disable NPC Needs [no_npc_food] ]

**Comment by ZhilkinSerg** [comment] 2020-07-19 20:35
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/41288

**Closed by ZhilkinSerg** 2020-07-19 20:35 UTC
