### ISSUE TITLE
No text appearing on 0.F for macosx 11.5  - Cataclysm TILES

### ISSUE THREAD

**Issue by damarino13** [CleverRaven/Cataclysm-DDA#50181] opened 2021-07-24 01:50 UTC
### Describe the bug

Upon starting Cataclysm DDA stable 0.F on mac os 11.5 since the OS update (11.4 to 11.5) we see ne text in the menus.

I reverted back to 0.E.3 and I can see the text just fine

I do not know if it takes the brew installed libraries but here are the versions of SDL that I use:

sdl2 2.0.14_1
sdl2_image 2.0.5
sdl2_mixer 2.0.4_1
sdl2_ttf 2.0.15

Here is a screenshot:
<img width="1440" alt="Screen Shot 2021-07-23 at 9 44 22 PM" src="https://user-images.githubusercontent.com/44308549/126854063-641f91eb-c3f2-405b-a595-7ad6bcbc2d72.png">

### Steps To Reproduce

Start Cataclysm normally

### Expected behavior

When I run Ellison E-3, I see text again

<img width="1440" alt="Screen Shot 2021-07-23 at 9 48 01 PM" src="https://user-images.githubusercontent.com/44308549/126854135-a17841a8-3ca0-40fc-a4bb-b2070dca6a32.png">

### Versions and configuration

Mac OSX 11.5

sdl2 2.0.14_1
sdl2_image 2.0.5
sdl2_mixer 2.0.4_1
sdl2_ttf 2.0.15

**Comment by anothersimulacrum** [comment] 2021-07-24 01:54
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/50149

**Closed by anothersimulacrum** 2021-07-24 01:54 UTC
Labels: (S3 - Duplicate)
