### ISSUE TITLE
SDL interface ghosting when playing with ASCII

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#16934] opened 2016-05-29 09:34 UTC
The refreshing of the screen bugs still continues on latest SDL (4949). Even after the commits #16416 #16211 #16162.
The issue have been pointed out in #15881 #15983 #16033 #16416 . Many instances of the ghosting have been fixed, but some still persist, as I'll try to show with screenshots. It happens when you are playing with ASCII, apparently while using different fonts for the maps. My fonts.json:

```
    "fontblending" : false,
    "fontwidth" : 8,
    "fontheight" : 16,
    "fontsize" : 16,
    "typeface" : "Terminus",
    "map_fontwidth" : 14,
    "map_fontheight" : 14,
    "map_fontsize" : 12,
    "map_typeface" : "Topaz-8",
    "overmap_fontwidth" : 14,
    "overmap_fontheight" : 14,
    "overmap_fontsize" : 12,
    "overmap_typeface" : "Topaz-8"
```

The first screen shows the ghosting after a save. I moved a couple tiles to make it more evident.
![new cdda bug 01](https://cloud.githubusercontent.com/assets/11512008/15632406/a18a676c-2566-11e6-90cd-7e47f7647555.png)

This one is after a prompt. Don't exactly remember which one.
![new cdda bug 02](https://cloud.githubusercontent.com/assets/11512008/15632408/c2c8074a-2566-11e6-971c-4dba88588ca8.png)

The same as before, after one turn of rain.
![new cdda bug 03](https://cloud.githubusercontent.com/assets/11512008/15632416/e33de13e-2566-11e6-8c6e-11e2d5867b48.png)

One more
![new cdda bug 04](https://cloud.githubusercontent.com/assets/11512008/15632423/f68ab320-2566-11e6-8af0-096b612de858.png)

And to finish, one with all the tiles updated by walking around, except the player one. This one refreshes only if you display a different screen like '?' that forces the refresh. I'm the black space between the bluebell and the bush.
![new cdda bug 05](https://cloud.githubusercontent.com/assets/11512008/15632426/1e9a122a-2567-11e6-85bf-2e885eb1536c.png)

**Comment by Fallingferret** [comment] 2016-05-29 14:09
This happens with default font settings as well. Much more so since the latest attempt.

**Comment by DLaboratory** [comment] 2016-06-01 14:48
![refresh](https://cloud.githubusercontent.com/assets/5671495/15713900/e1a91a78-284a-11e6-8dcb-898bcd5f4e61.png)
Still happens in latest commit.

**Comment by pingpong2011** [comment] 2016-06-06 02:55
I don't know if there was a recent pull that fixed this issue, but using 5003  0.C-14998-g21c8b57 I'm having the same problem, but all my fonts are the same.

![cataclysm drawing error](https://cloud.githubusercontent.com/assets/8422574/15810794/26b4b99c-2b70-11e6-9774-534ecb93ca13.png)

One instance was literally the first item I picked up asked me to wield, and the wield box left residual black squares.

**Comment by pingpong2011** [comment] 2016-06-06 03:03
Haha, actually, yeah, this is ridiculous and makes the game unplayable:

![wearing a hoodie](https://cloud.githubusercontent.com/assets/8422574/15810950/a703ad50-2b71-11e6-9ed0-322baf4dc89f.png)

![moving one space](https://cloud.githubusercontent.com/assets/8422574/15810953/aeae0bfe-2b71-11e6-973d-8fd0f7546f25.png)

@ turns into a black square.

**Comment by Fallingferret** [comment] 2016-06-06 04:52
Yeah, the current framebuffer PR doesn't fix enough problems to be merged? Sure, okay, price of experimental I suppose. 

As a current workaround I use the map screen it refresh, as frustrating as it is it deal with. There's also RetroASCII for a replacement if you don't mind not playing as an @.

**Comment by pingpong2011** [comment] 2016-06-07 01:41
Yeah, it turns out it's only a few of the messages that do it. Not unplayable.

**Comment by DLaboratory** [comment] 2016-06-07 03:19
But the problem is annoying. For example, examine a vehicle, then the entire screen goes messy. Every time I have to press [m] to open the map to manually refresh the screen.

**Comment by Fallingferret** [comment] 2016-06-07 15:06
Yeah, I'd really like to go back to ascii without having to use the console build, as it's much slower than sdl on my machine. Hopefully #17076 will get reviewed and merged sometime this week. (Thanks, Dan)

**Comment by nanovad** [comment] 2016-06-11 17:24
This occurs on builds using tiles, too, if there's an all-text window (only one I can think of right now is the map).

**Comment by Fallingferret** [comment] 2016-06-20 01:43
This issue seems to have been forgotten, while the current proposed fix has been ignored for a week after being finished. I suppose we're a very small majority of players.

**Comment by illi-kun** [comment] 2016-06-20 02:45
I disagree with that conclusion, I guess all contributors are just busy.

**Comment by Fallingferret** [comment] 2016-06-20 04:43
That's probably the truth. I'm just worried it's going to be forgotten in the sea of new features, reworks, bugs, and fixes. Apologies for venting, this isn't the place for it.

**Comment by DLaboratory** [comment] 2016-06-28 14:56
@narc0tiq The problem has been fixed since DanmakuDan's pull request was merged. This issue can be closed.

**Comment by DLaboratory** [comment] 2016-08-03 15:26
@mugling this issue can be closed.

**Comment by BrettDong** [comment] 2016-11-05 12:10
@illi-kun This issue is also solved but not closed.

**Closed** 2016-11-05 13:37 UTC
