### ISSUE TITLE
Can't install experimental version on Mac, both the official link & the terminal ( other players have the same issue )

### ISSUE THREAD

**Issue by FateRiddle** [CleverRaven/Cataclysm-DDA#23044] opened 2018-02-25 03:12 UTC
Operating system:
Mac OS 10.11.5

Tiles or curses:
tiles

1. I tried go to http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Download, and download through "Download OS X (Graphical Experimental)" link. The .dmg installed successfully, but I simply can't open the app (nothing happened). I then tried stable version, it worked.

2. I post on reddit, and 2 replies said they had the same issue, and suggest me to install from github.

3. I tried to install experimental version again:
```
 brew install cataclysm --with-tiles --HEAD
```
result in error:
```
$ brew install cataclysm --with-tiles --HEAD
==> Cloning https://github.com/CleverRaven/Cataclysm-DDA.git
Updating /Users/Riddle/Library/Caches/Homebrew/cataclysm--git
==> Checking out branch master
==> make NATIVE=osx RELEASE=1 OSX_MIN=10.11 TILES=1 CLANG=1
Last 15 lines from /Users/Riddle/Library/Logs/Homebrew/cataclysm/01.make:
src/pimpl.h:23:76: note: in instantiation of template class 'std::__1::is_constructible<effects_map, pimpl<effects_map> >' requested here
        template<typename ...Args, typename = typename std::enable_if<std::is_constructible<T, Args...>::value>::type>
                                                                           ^
src/pimpl.h:24:18: note: in instantiation of default argument for 'pimpl<pimpl<effects_map> >' required here
        explicit pimpl( Args && ... args ) : std::unique_ptr<T>( new T( std::forward<Args>( args )... ) ) { }
                 ^~~~~
src/pimpl.h:20:7: note: while substituting deduced template arguments into function template 'pimpl' [with Args = <pimpl<effects_map>>, $1 = (no value)]
class pimpl : private std::unique_ptr<T>
      ^
src/creature.h:20:7: note: forward declaration of 'effects_map'
class effects_map;
      ^
#define VERSION "7399448"
2 errors generated.
make: *** [obj/tiles/activity_handlers.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

btw, then I tried stable version, and it worked properly.
```
brew install cataclysm --with-tiles
```

So, it seems something is wrong with the experimental version, anyone knows why it happened?

**Comment by Wulfe813** [comment] 2018-02-25 06:09
Mac OSX builds have been broken for awhile(a week or so, I think?)

brew is trying to build it from source, and failing. Not sure why the latest available experimental is broken, but you might try one of the older builds at http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Tiles/ , perhaps build 7112 will work?

**Comment by illi-kun** [comment] 2018-02-25 15:27
@FateRiddle please re-check the issue now.

**Comment by Leland** [comment] 2018-02-26 02:29
Two separate issues, both duplicates:

1. Downloaded app not running, duplicate of #21345. As that issue notes, this is an issue with 10.11.x. High Sierra runs this just fine. Unfortunately we don't have any devs running that version :(
2. App not compiling locally, duplicate of #22970. **This is fixed now.** You should be able to compile.

Closing. If, however, you still aren't able to recompile, do reopen. :)

**Closed by Leland** 2018-02-26 02:29 UTC
Labels: Build, OSX
