### ISSUE TITLE
Improper horizontal scaling of Imgui menus

### ISSUE THREAD

**Issue by bullkang** [CleverRaven/Cataclysm-DDA#76260] opened 2024-09-07 10:12 UTC
### Describe the bug

When opening the Sort dialog window with "Shift + o" not all the text is visible, the menu extends beyond the window size.

### Attach save file

[Ceiba-trimmed.tar.gz](https://github.com/user-attachments/files/16917522/Ceiba-trimmed.tar.gz)

### Steps to reproduce

Open the Sort dialog menu, in my case "Shift + o"

### Expected behavior

I expected to have the menu size equal or less then the width of the screen size.

### Screenshots

![Screenshot_2024-09-07_20-04-01](https://github.com/user-attachments/assets/2cf49726-b672-4a8b-b852-da8daba686cb)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: cdda-experimental-2024-09-07-0110 e398be1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment] 2024-09-07 10:45
It looks like the box is the same on everyone's screen regardless of their terminal width. It looks like its just going to the max width of the description text.

![image](https://github.com/user-attachments/assets/b6ecc920-9f4e-435b-8b08-f39bb6abe4f1)

**Comment by bullkang** [comment] 2024-09-07 10:57
@CoroNaut is there a setting I could change to have it look like your screenshot? I've tried changing the "Terminal Width" in the "Terminal Display Options" from 160 to 120 to 80 and makes no difference. Any tips?

**Comment by CoroNaut** [comment] 2024-09-07 11:20
My monitor is 1680 x 1050 and my CDDA terminal width/height is 210 x 65 which is (1680 x 1040). I chose those terminal numbers just because they closely match my monitor.

**Comment by bullkang** [comment] 2024-09-07 11:35
My monitor is 1600x900, I changed terminal width/height to 210 X 65. Alters nothing, no matter what numbers I place there, nothing changes. Also changed in the Graphical Display Options: Fullscreen, Window Border and Maximized and has had no effect, the display is not changed. I must have something broken...

**Comment by CoroNaut** [comment] 2024-09-07 20:34
I don't think you have something broken, the imgui is definitely in the 'implementation hell' right now and I don't blame it. After it is fully reactive to the terminal width/height, im sure you won't have this problem with it. Also, in the case of your monitor being 1600x900, I'd use terminal 200x56, which is 1600x896 for CDDA. I don't think it'll change anything except make your pixels more crisp and your eyes pleased. :D

Anyways, As for the original issue, it should be fixed eventually, if you don't want to deal with it, you can always take an older version before it was messed up and use that for a while.

**Comment by bullkang** [comment] 2024-09-07 22:29
@CoroNaut Thank you very much for your input, I'll take your advice.

**Comment by GuardianDll** [comment] 2024-09-11 13:19
Closing it as duplicate of #75698, gonna be fixed by #76356

**Comment by db48x** [comment] 2024-09-11 22:20
It’s only this one menu that is out of whack. For now the best fix is to just wrap the text to some sensible length.

**Comment by ZweiFedern** [comment] 2024-09-12 10:09
the build i use is from cdda-linux-tiles-x64-2024-09-10-0532, there are some problems with the resolution

![Bildschirmfoto vom 2024-09-12 10-49-25](https://github.com/user-attachments/assets/df377837-ad03-425e-9867-4a7223f33239)
![Bildschirmfoto vom 2024-09-12 10-43-36](https://github.com/user-attachments/assets/27c8969d-fbf3-4285-a732-9c6ce8ff622c)

the new GUI have some problems with the resolution. i use a small size Notebook, and i see sometimes nothing.

And there is also a bug the the "new" Window do not jump in front of the Frame. It will be pop-up behind.

![Bildschirmfoto vom 2024-09-12 10-48-21](https://github.com/user-attachments/assets/ffe7fb5a-8223-4e67-badf-f9a0969766d0)

if you search a item in the debug menu to spawn, you did not see the imput 

![Bildschirmfoto vom 2024-09-12 10-44-42](https://github.com/user-attachments/assets/b6d9db0f-6481-4168-8b0c-181bf67bc881)

![Bildschirmfoto vom 2024-09-12 11-24-46](https://github.com/user-attachments/assets/6e740224-3230-41b5-9bd6-021a34dfcb75)

if i go to the pocket settings/set priorty or go to the seclet a style window

![Bildschirmfoto vom 2024-09-12 11-32-41](https://github.com/user-attachments/assets/5c3d6aff-8b83-4f00-b78d-76fa8a443ca9)

**Comment by db48x** [comment] 2024-09-12 10:14
This bug is only for discussing a single problem with the zone menu. None of the pictures you have posted have anything to do with the zone menu. Why are you posting them here?

**Comment by ZweiFedern** [comment] 2024-09-12 10:19
unfortuately i have to correct you: the first screenshot is out of the zone manager, the resolution is so, that i did not have anything of the text in the frame/window.

**Comment by db48x** [comment] 2024-09-12 10:22
The other screenshots are not relevant, and therefore not helpful. Each of them is about a different bug that has already been reported. If you want to read the discussions about those other bugs, you can search for them.

Adding another screenshot of the zone menu is not helpful either.

Thank you for trying.

**Closed** 2024-09-12 12:06 UTC
Labels: ImGui
