### ISSUE TITLE
Demon spiders' WEBWALK flag doesn't work

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48639] opened 2021-04-24 19:51 UTC
# Describe the bug

Demon spiders and spiderlings are stopped by webs and trigger "breaks free of web" messages.
They have WEBWALK flag though, so the problem might be somewhere in c++.

# Steps To Reproduce

Spawn special mapgen `demon_spider_lair`, lure spiders outside, watch them break webs

# Expected behavior

WEBWALK flag work properly

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/115971166-2364c600-a547-11eb-8ebf-5e73d87b31d2.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by ferociousdork** [comment] 2021-04-26 22:16
The issue is that monsters with this flag are not immune to the `fd_web` field effects, nor is there an easy way to specify this at the moment. Currently only mutations and specific monster types can be made immune:
https://github.com/CleverRaven/Cataclysm-DDA/blob/16bcba84db28532b7475eca1123d1bf752b88a8c/data/json/field_type.json#L96-L97

Immunity is checked in [monster::is_immune_field](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monmove.cpp#L83). A nice addition could be to add flag-based immunity here and make it configurable as part of the `immunity_data` key in the json.

**Comment by Salty-Panda** [comment] 2021-04-26 22:58
Look for my draft PR "make flying monsters immune to Druid root spells. I
recall it was a working solution.

**Comment by actual-nh** [comment] 2021-04-26 23:00
> make flying monsters immune to Druid root spells

#47090?

**Comment by Salty-Panda** [comment] 2021-04-26 23:06
Yes thanks. It was a good example how to make monster with some
characteristic immune to an effect

**Comment by actual-nh** [comment] 2021-04-27 01:05
> Yes thanks. It was a good example how to make monster with some characteristic immune to an effect

Any luck with the genericized approach using string_to_enum?

**Comment by Salty-Panda** [comment] 2021-04-27 06:58
I didn't pick it up and have no idea if the approach suggested in that PR would work.

**Closed** 2021-08-14 16:19 UTC
Labels: <Bug>, Monsters, Fields / Furniture / Terrain / Traps, Mods: Magiclysm
