### ISSUE TITLE
Access NPC inventory through Advanced Inventory Manager

### ISSUE THREAD

**Issue by svakob** [CleverRaven/Cataclysm-DDA#78308] opened 2024-12-02 19:44 UTC
### Is your feature request related to a problem? Please describe.

Accessing the inventory requires a lot of clicking. It takes a lot of time.

### Solution you would like.

Add ability to access NPC inventory via Advanced Inventory Manager. Namely, equipped items and inventory.

**Comment by Brambor** [comment] 2024-12-30 17:04
- Duplicate of #68034.
 - Note: Closed doesn't mean we don't want it!

**Closed** 2024-12-30 17:05 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>
