### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by VZIKL** [CleverRaven/Cataclysm-DDA#19284] opened 2016-11-14 11:45 UTC
src/overmap.cpp 247:38 error no member named accumulate in namespace std

**Comment by jaked122** [comment] 2016-11-14 15:47
I'm getting this too.

It looks like someone screwed up the includes here.

**Comment by ChucklesTheBeard** [comment] 2016-11-14 15:59
:+1: I'm also getting this.

**Comment by ChucklesTheBeard** [comment] 2016-11-14 16:28
Duplicate of #19278

**Comment by codemime** [comment] 2016-11-15 00:04
Needs to be closed.

**Closed** 2016-11-15 14:38 UTC
