### ISSUE TITLE
Debug Menu skips a number

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20091] opened 2017-01-23 05:44 UTC
<a href="http://imgur.com/gK4Dqae"><img src="http://i.imgur.com/gK4Dqae.png" title="source: imgur.com" /></a>

Build 6185

The debug menu skips straight from "1" to "3", screwing up the order of the keys. This gets quite problematic, especially when I'm used to the way it used to be, and I keep debugging myself to learn all the martial arts by accident.

**Comment by Night-Pryanik** [comment] 2017-01-23 06:53
Not only numbers "2" and "8", but letters "f", "j", "k", "q" are missing too.

**Comment by keyspace** [comment] 2017-01-23 10:42
Duplicate of #20065 and not a bug: those keys are bound (explained in linked issue).

**Comment by kolsurma** [comment] 2017-03-07 18:12
This is fixed now.

**Comment by kevingranade** [comment] 2017-03-08 04:11
One remaining letter being skipped, 'f'.  Fixed by #20489

**Comment by keyspace** [comment] 2017-03-09 14:41
PR #20489 has been merged, this can be closed?..

(Having time shortage lately, can't verify myself - sorry.)

**Closed** 2017-03-09 14:50 UTC
