### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64508] opened 2023-03-23 23:53 UTC
### Describe the bug

Game crashes suddenly when doing stuff in the city, i don't know exactly why it happens, so all i can say is, attack some zombies, walk around the city

### Attach save file

N/A

### Steps to reproduce

Not sure exactly, but i provided the save, To narrow it down, walk around the city, attack zombies. 

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 4ad1388 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context
[Depths Of Jupiter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11057340/Depths.Of.Jupiter.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11057277/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11057278/debug.log)

**Comment by c0bnut** [comment] 2023-03-24 00:07
Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/64466?

**Comment by Wyghab** [comment] 2023-03-24 00:18
This is related to achievements. The crash log mentions it.
#5
    (dbghelp: achievements_tracker::report_achievement+0x281@0,000,7FF,793,51F,561[cataclysm-tiles.exe+0x1,20f,561]), 
Either disable achievement popups or press ')' when in the game to properly load the achievement data in advance, that way the game doesn't crash.

**Comment by MochaModifier** [comment] 2023-03-24 06:02
getting consistent crashing in the city, possibly related to the popup 
![image](https://user-images.githubusercontent.com/38334602/227437615-ca35ccc6-b872-4371-b1cd-78af26d217e8.png)

A crashlog is generated
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11058859/crash.log)

**Comment by anothersimulacrum** [comment] 2023-03-25 01:19
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed by anothersimulacrum** 2023-03-25 01:19 UTC
Labels: (S3 - Duplicate)
