### ISSUE TITLE
Error while generating random scenario

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#55781] opened 2022-03-02 09:47 UTC
### Describe the bug

After starting random scenario i've got error:
 DEBUG    : default (butchery_requirements) has two definitions from the same source (dda)!

 FUNCTION : static void mod_tracker::check_duplicate_entries(const T&, const T&) [with T = butchery_requirements; std::enable_if_t<mod_tracker::has_src_member<T>::value>* <anonymous> = 0]
 FILE     : src/mod_tracker.h
 LINE     : 76
 VERSION  : 2c922b0

### Steps to reproduce

Think it can be reproduced only on some random scenarios

### Expected behavior

Successful character generation

### Screenshots

![изображение](https://user-images.githubusercontent.com/2695146/156336588-3a2c2c76-9571-4e40-b74c-91664dfe9fed.png)

### Versions and configuration

- OS: Ubuntu 20.04
- Game Version: Cataclysm-DDA experimental build 2022-03-01-1530
- Graphics version: Tiles
- Ingame language: Russian
- Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "blazeindustries",
  "package_bionic_professions",
  "magiclysm",
  "crt_expansion",
  "crazy_cataclysm",
  "MMA",
  "extra_mut_scens",
  "No_Rail_Stations",
  "no_fungal_growth",
  "speedydex",
  "StatsThroughSkills"
]

**Comment by stasalcatraz** [comment] 2022-03-02 09:54
After ignoring error and character creation:
![изображение](https://user-images.githubusercontent.com/2695146/156338399-9b5af20a-592f-44ea-8e58-67e4a931d5e2.png)

**Comment by Night-Pryanik** [comment] 2022-03-02 10:06
Duplicate of #55606.

**Closed by Night-Pryanik** 2022-03-02 10:06 UTC
