### ISSUE TITLE
Great helmet equip bug

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#29171] opened 2019-03-31 19:45 UTC
**Describe the bug**  
It is impossible to equip great helmet

**To Reproduce**  
1. Make a wish for great helmet
2. Try to equip
3. It says that "You can't wear that much on your head", even if you naked.

**Expected behavior**  
A helmet should be possible to be worn

**Versions and configuration(please complete the following information):**
 - OS: win10
 - Game Version: 0-D-1214-g5225ecb
 - Graphics version: Tiles
 - Mods loaded: DDA

**Comment by Photoloss** [comment] 2019-03-31 22:35
For context: this is a consequence of adding the `HELMET_COMPAT` flag in PR #28554, potentially a bug/oversight from PR #23089 or an incorrect application thereof. The game strictly enforces an encumbrance limit on non-main helmet items and the great helm either misses the exception flag or there is none.

Historically speaking it should be possible to wear a **fitted** great helm alongside **fitted** chainmail or a [Bascinet](https://en.wikipedia.org/wiki/Bascinet)-style helmet (a slim visorless version) as well as a helmet liner standing in for a [skullcap](https://en.wikipedia.org/wiki/Cervelliere). This was the attire of the crusaders although solutions which preserve the mouth encumbrance should be preferred as they did in fact often elect to raise/remove the great helm for easier breathing during melee combat (same for later visored helmets). **Un**fitted historical helmets should still be wearable if the implication is that merely their fabric padding needs adjustment, and completely unwearable even on their own if the metal shell is too small.

**Comment by TheMurderUnicorn** [comment] 2019-04-11 21:38
So, do we remove the helmet_compat flag or do we adjust the encumbrance on the great helm?  Neither is ideal, but there's no point in it being in the game if it literally can never be worn.

**Comment by wapcaplet** [comment] 2020-09-26 00:42
Cannot reproduce in 0.E-6177-g 9f4a1b841d - I can wear a great helm (poor fit) with no problem:

![image](https://user-images.githubusercontent.com/238395/94325982-83b66980-ff5e-11ea-8d11-c9128e1e2bd3.png)

Might have been fixed by #29475, since that PR increases the encumbrance prohibition from 20 to 40 (the great helm being 40 encumbrance). Closing issue.

**Closed by wapcaplet** 2020-09-26 00:42 UTC
Labels: <Bug>, Items / Item Actions / Item Qualities
