### ISSUE TITLE
Magiclysm error message when quit saving

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#68365] opened 2023-09-27 20:46 UTC
### Describe the bug

Got this error while saving and exiting

 DEBUG    : (json-error)
Json error: data/mods/Magiclysm/mod_interactions/Defense_Mode/scenarios.json:3:17: <color_white><color_cyan>Invalid or misplaced field name "copy-from" in JSON data</color>

[
  {
<color_light_red>    "copy-from": "defense_mode_fortified",
</color>
               <color_cyan>▲▲▲</color>
    "type": "scenario",
    "extend": { "allowed_locs": [ "sloc_lake_retreat" ] },
</color>

 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 341
 VERSION  : ae14681

### Attach save file

[Mundete-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12743173/Mundete-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Save and exit

### Expected behavior

Not much to say other than not getting an error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ae14681 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by snipercup** [comment] 2023-09-27 23:35
Duplicate of #68205

**Comment by ZhilkinSerg** [comment] 2023-09-28 06:51
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/68205

**Closed by ZhilkinSerg** 2023-09-28 06:51 UTC
Labels: (S1 - Need confirmation)
