### ISSUE TITLE
reloading a clip makes a new one

### ISSUE THREAD

**Issue by mischief** [CleverRaven/Cataclysm-DDA#16029] opened 2016-04-02 21:37 UTC
when i press reload and select 'M1 Garand Clip', the game prints:

```
DEBUG: Tried to remove an item from a player that doesn't have it...
```

and it seems that a new M1 Garand Clip is created.

i'm playing with cdda 3da892d768c10229a9262db5dd2695e721af3e77.

**Comment by illi-kun** [comment] 2016-04-18 09:26
I'm not able to reproduce this, reloads just fine.

**Comment by mugling** [comment] 2016-04-18 10:18
I'm going to close this for now due to a number of recent fixes to the reloading code but it can be re-opened if there are any further reports

**Closed by mugling** 2016-04-18 10:18 UTC
Labels: Confirmation Needed, Magazine
