### ISSUE TITLE
generation glitch 

### ISSUE THREAD

**Issue by DifferentParadox** [CleverRaven/Cataclysm-DDA#62976] opened 2023-01-03 07:36 UTC
### Describe the bug

Unable to generate a valid starting location Lighthouse Island Isloc-lighthouse-ground) in a radius of 3 overmaps.

### Steps to reproduce

I did clicked play now.

The map generated was unable to generate a valid starting location

### Expected behavior

Because of maps overlapping with each other

### Screenshots

https://user-images.githubusercontent.com/108210687/210315390-f89d6dc1-2dca-422c-9b23-a09f809a7e8e.png

### Versions and configuration

macbook pro version: 0.F graphics: Tiles language: spanish mods: random

**Comment by GuardianDll** [comment] 2023-01-03 07:39
Versions and configuration is not correct. Please make it like it's intended, by opening debug menu and making bug report

**Comment by Night-Pryanik** [comment] 2023-01-03 07:41
Duplicate of #35376.

**Closed by Night-Pryanik** 2023-01-03 07:41 UTC
Labels: (S1 - Need confirmation)
