### ISSUE TITLE
patches of roads disappearing after resetting world

### ISSUE THREAD

**Issue by garriusdagreat** [CleverRaven/Cataclysm-DDA#23270] opened 2018-03-22 16:25 UTC
Game version: 
0.C-26878-g46b3fa8

Operating system: 
Windows 64-bit

Tiles or curses: 
Tiles

Mods active: 
StatsThroughSkillsIV
Tanks and Other Vehicles
Cataclysm++
Makeshift Items
Filthy Clothing
Folding Parts pack
Boats
Vehicles Additions Pack
Alternative Map Key
Bionics Systems Mod
More Survival Tools

### Expected behavior
Before resetting the world, the roads were still physically there. The player and any other creature that does not fly could still move on that road tile. 
### Actual behavior
1 map tile (as in the small minimap next to the health) of road disappears leaving a massive square hole and anything that walks onto that tile or is currently on it will fall into it as if it were a ledge and die instantly.  I accidentally fell into one these holes while driving at night and found that it leads to the player being stuck in solid rock around them with no way of escaping .
### Steps to reproduce the behavior
1. Create world
2. Play and die
3. Reset the world a few times (not sure which attempt triggered the bug)
4. Find some roads far away from starting point or read a drawn map
5. Roads start disappearing.

- If it helps, I was playing as a tailor with no CBMs installed yet whatsoever.

**Comment by Leland** [comment] 2018-03-22 16:26
Screenshots?

**Comment by garriusdagreat** [comment] 2018-03-22 16:29
I didn't think to take screenshots before deleting the save cause I thought someone else might've posted this bug. Turns out I was wrong. Sorry :(

**Comment by Leland** [comment] 2018-03-22 16:35
@garriusdagreat can you please reproduce using the steps you've listed? Screenshots (and, ideally, a savefile as well!) are necessary to ensure this can be fixed :)

**Comment by garriusdagreat** [comment] 2018-03-22 16:35
I'm an idiot. I clearly posted how to recreate the bug. I'll try to recreate it and post screenshots soon.

**Comment by ZhilkinSerg** [comment] 2018-03-22 17:10
Great idea for map extra - something unnatural pierced world through several z-levels during Cataclysm.

**Comment by garriusdagreat** [comment] 2018-03-23 00:00
UPDATE: After trying dozens of times with 3 separate worlds, I can't seem to recreate the bug. It's probably a rare bug that occurs. But I'm still very certain that it exists.  

@ZhilkinSerg Yeah. It did make sense though, huge holes on the roads. What didn't make sense though, was being trapped in solid walls not being able to move at all.

**Comment by Leland** [comment] 2018-03-23 02:34
@garriusdagreat thanks for giving that a go! I'm closing this for now – unfortunately, without a means to consistently reproduce, devs are left a little high and dry. The ticket will stand as a record for if/when someone once again runs into this and can be reopened.

Similarly, be sure to make a copy of your save file if _you_ run into this again!

**Comment by garriusdagreat** [comment] 2018-07-11 00:22
so after 4 months, I have finally recreated this bug. I am also using a different mod list than before.

Mods:
StatsThroughSkillsIV
Makeshift Items
Tanks and Other Vehicles
Folding Parts pack
Boats
Vehicles Additions Pack
More Survival Tools

Steps to reproduce the behavior:
1. Create world
2. Play and keep dying
3. Reset world. (this time it's after my 7th reset)
4. Random towns around the map will definitely have these huge holes.

Here is the save folder in question. I have also included a screenshot of the game within the folder, but when I alt-tabbed to paste the screenshot, the game crashed. I was playing on fullscreen with mouse cursor hidden.
https://drive.google.com/open?id=1Jza4exTEO0zUSXSbMGu-Ve847FCFR-yc

**Comment by Leland** [comment] 2018-07-11 12:16
For reference, here's that screenshot:

![death-holes](https://user-images.githubusercontent.com/714017/42570702-c0fc45b0-84e2-11e8-92aa-dda142c849ca.png)

**Comment by Night-Pryanik** [comment] 2020-05-15 04:19
Anyone encountered this bug ever since 2018?

**Comment by Leland** [comment] 2020-06-02 01:24
Closing per no reproducibility

**Closed by Leland** 2020-06-02 01:24 UTC
Labels: (S1 - Need confirmation), <Bug>, Map / Mapgen
