### ISSUE TITLE
Professions do not spawn with gunmods

### ISSUE THREAD

**Issue by Orinyau** [CleverRaven/Cataclysm-DDA#42918] opened 2020-08-14 18:49 UTC
# Describe the bug

While attempting to get the rescuer profession to correctly spawn with the M4A1 by replacing the back holster with a sling I discovered that Swat Officer, Swat CQC, Crossbow Hunter, and Bionic Soldier do not spawn with any of the gunmods they are supposed to get. I am willing to try and fix this, if someone can point out what the issue is. 

# Steps To Reproduce

1. Spawn as Swat Officer, Swat CQC, Bionic Soldier, ect
2. See that weapon slings and scopes do not exist.

# Expected behavior

Code says I get gunmod, I get gunmod.

# Screenshots

# Versions and configuration

  - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA]

**Comment by LaVeyanFiend** [comment] 2020-08-14 19:17
Duplicate of #41969.

**Closed** 2020-08-15 23:36 UTC
Labels: <Bug>, Items: Gunmod / Toolmod, Mutations / Traits / Professions
