### ISSUE TITLE
Pushing vehicle off the bridge causes vehicle to go into bugged state of "can't turn on the ramp"

### ISSUE THREAD

**Issue by Wolfvx** [CleverRaven/Cataclysm-DDA#48148] opened 2021-03-20 12:03 UTC
# Describe the bug

Pushing the vehicle off the multi-level bridge ramp to the ground floor and then trying to ride it causes "can't turn while being on the ramp" message to pop-up and vehicle refuses to drive. Said message pops up for every direction changing commands, forward, backwards, left, right. 
This happens regardless whether you drag the vehicle multiple map tiles away from the bridge it or not.

# Steps To Reproduce

1. Spawn scooter or bicycle close to bridge.
2. Drive up said vehicle onto the bridge.
3. Stop and jump off the vehicle.
4. "G" grab the vehicle from the back, because pulling it off doesn't work (you loose grab).
5. Push vehicle back to the ground floor through the ramp and away from the ramp (how ever far away you like)
6. Jump into the vehicle 
7. Profit with "can't change direction while being on ramp" messages

# Expected behavior

Expected to be able to drive the vehicle just as if nothing ever happened.

# Screenshots

N/A, very easily reproducible.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10088-g74e26ac
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Blaze Industries

# Additional context

The bugged state doesn't get saved, so the bug is fixable with saving and reloading the game.

**Comment by slitherrr** [comment] 2021-03-28 21:18
I have found another way to run into this:

1. Drag a bicycle onto the ^^^^^ section on the upper level of the ramp
2. Modify the bicycle (for instance, change out the wire basket for a shopping cart basket)
3. Drag the bicycle off the ramp.

Following the above steps put the bicycle into the state for me.

**Comment by actual-nh** [comment] 2021-03-28 21:25
> I had to completely dismantle the bike and remake it in order to make the parts back into a functional vehicle.

Saving and reloading didn't work?

**Comment by slitherrr** [comment] 2021-03-29 02:03
> Saving and reloading didn't work?

I didn't try that, no. I didn't really have a reason to think it would because I didn't go to github until after I'd remade the bike (which was easy because it was just a bike). I can try to repro to make sure save/reload is an effective workaround for people who run into this later.

**Comment by slitherrr** [comment] 2021-03-29 04:36
Confirming two things:
1. I could reproduce this situation by dragging the bike into the ramp section, removing its wire basket, then dragging it off the ramp. Doing so put it into the "cannot turn on a ramp" state.
2. Saving, quitting, and reloading the game cleared the "cannot turn on a ramp" state without any further effort.

**Comment by actual-nh** [comment] 2021-03-29 13:47
Oh. Ping: @mlangsdorf, @KorGgenT?

**Comment by RoyBerube** [comment] 2021-04-09 04:27
The bool variable `is_on_ramp` is only toggled to false in one place in the code - in `vehicle::gain_moves()`. Moving it by dragging bypasses toggling off the flag.

Finding a way to toggle off the flag when dragging a vehicle would be a good start.

**Comment by actual-nh** [comment] 2021-04-10 02:32
In `displace_vehicle` in map.cpp, where it's turned _on_ when _on_ a ramp... why not turn it _off_ there if it _isn't_? (Alternatively, if `pldrive` checks and thinks the vehicle is on a ramp and someone's trying to turn it, double-check before that it actually is on one, and if it isn't, turn off `is_on_ramp` (and allow the maneuver, of course).)

**Comment by actual-nh** [comment] 2021-04-12 04:24
Despite self-assigning this, I am again quite willing for someone else to create a PR for this - my week is going to be... difficult (see status), so it is likely to take a while (and I will need testers, as mentioned).

**Comment by RoyBerube** [comment] 2021-04-17 14:04
I'm currently testing a fix for this. Testing it at the moment - should have the PR submitted today.

**Closed** 2021-04-19 01:15 UTC
Labels: <Bug>, Vehicles
