### ISSUE TITLE
Fighting hallucinations has real consequences

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13265] opened 2015-08-13 10:27 UTC
![8](https://cloud.githubusercontent.com/assets/11132525/9247719/35bcb076-41be-11e5-990c-cfe43a2e7215.PNG)
1) I block "none" damage from my imaginary wolf.
2) Furthermore, I practiced dodging by this and even leveled up in this skill!

Windows 10, 0.C-3557, tiles.
##

**Comment by drbig** [comment] 2015-08-13 11:59
Actually, maybe this isn't a bug? After all you are exercising.

**Comment by Night-Pryanik** [comment] 2015-08-13 12:09
Then this is the best way to train dodging - and without any danger of being bashed or bitten! 
<Gone away to snort his meth and get his hallu sparring partners>

**Comment by Kodiologist** [comment] 2015-08-13 15:20
I tend to concur that this is not a bug.

**Comment by Coolthulhu** [comment] 2015-08-13 16:25
Dodging a figment of your imagination is probably not a good way to train...

**Comment by drbig** [comment] 2015-08-13 19:22
Why? If it's real enough for you to actually trigger all reflexes... Sure, less exp than a real fight (after all you're fighting only what you can imagine), but still some seems ok.

**Comment by Night-Pryanik** [comment] 2015-08-13 20:15
Nevertheless, maybe remove message about blocking for "none" damage? Or change it to something like "You *think* that you blocked a hit by <smthng>"?

**Comment by 3721assistant** [comment] 2015-09-28 04:06
I think dodging your imagination gives you experience is OK. The problems, if an NPC near you is attacked by your imagination, he/she will also gain exp in dodging, and that's somewhat wield.

**Comment by drbig** [comment] 2015-09-28 06:25
> Nevertheless, maybe remove message about blocking for "none" damage? Or change it to something like "You think that you blocked a hit by "?

Or something more explicit to let the player know he's fighting an illusion (I think there was an issue where someone suggested you "fall through" your opponent).

> The problem is, if an NPC near you is attacked by your hallucination, he/she will also gain exp in dodging, and that's somewhat wield.

If that's a case, that's a bug that could use it's own issue ("NPCs are attacked by player hallucinations", or something like that).

**Comment by Cyrano7** [comment] 2017-05-03 04:31
I believe this was fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/16755

**Closed by Cyrano7** 2017-05-03 04:31 UTC
Labels: Bug
