### ISSUE TITLE
Insta crash on Latest Android x32

### ISSUE THREAD

**Issue by FickDiddler** [CleverRaven/Cataclysm-DDA#65800] opened 2023-05-22 13:54 UTC
### Describe the bug

On the Latest Android x32 version, the app just instantly closes the moment I open it after it's done downloading the files.

### Attach save file

N/A

### Steps to reproduce

1. Download the app.
2. Watch it crash the moment it is done downloading the files.
3. It also crashes if you try opening it again.

### Expected behavior

Playability.

### Versions and configuration

Latest Android x32

**Comment by NetSysFire** [comment] 2023-05-22 17:46
Closing as duplicate of #65792

**Closed by NetSysFire** 2023-05-22 17:46 UTC
Labels: (S1 - Need confirmation)
