### ISSUE TITLE
CTD - SIGSEGV: Segmentation Fault

### ISSUE THREAD

**Issue by sevyns** [CleverRaven/Cataclysm-DDA#59670] opened 2022-07-27 18:01 UTC
### Describe the bug

I've had multiple, repeatable CTDs with recent builds in the experimental branch (releasing on 7/27/2022). Game is installed using the launcher, and I've tried creating new worlds with new characters and this issue will still occur.

Here is the crash.log contents:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 776aa63
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff6b5e31184[cataclysm-tiles.exe+0x221184]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x140221184),
    0x140221184    src/debug.cpp:1114    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff6b5e1a941[cataclysm-tiles.exe+0x20a941]), 
    (libbacktrace: log_crash+0x1d2@0x14020a941),
    0x14020a941    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc11/11.2.0/include/c++/sstream:917    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x14020a941    src/crash.cpp:85    log_crash
  #2
    (dbghelp: @0x7ff6b5e1ab6f[cataclysm-tiles.exe+0x20ab6f]), 
    (libbacktrace: signal_handler+0x52@0x14020ab6f),
    0x14020ab6f    src/crash.cpp:137    signal_handler
  #3
    (dbghelp: @0x7ff6b6716ed2[cataclysm-tiles.exe+0xb06ed2]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140b06ed2),
    0x140b06ed2    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff9c80dad58[msvcrt.dll+0x2ad58]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x12f@0x7ff9c88e8eaf[ntdll.dll+0xa8eaf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRestoreContext+0x8aa@0x7ff9c8875e9a[ntdll.dll+0x35e9a]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff9c88e7ebe[ntdll.dll+0xa7ebe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff6b612ee60[cataclysm-tiles.exe+0x51ee60]), 
    (libbacktrace: map::generate_lightmap(int)+0x398@0x14051ee60),
    0x14051ee60    src/lightmap.cpp:460    map::generate_lightmap(int)
  #9
    (dbghelp: @0x7ff6b617fb82[cataclysm-tiles.exe+0x56fb82]), 
    (libbacktrace: map::build_map_cache(int, bool)+0x136@0x14056fb82),
    0x14056fb82    src/map.cpp:8687    map::build_map_cache(int, bool)
  #10
    (dbghelp: @0x7ff6b5f19024[cataclysm-tiles.exe+0x309024]), 
    (libbacktrace: game::draw(ui_adaptor&)+0x78@0x140309024),
    0x140309024    src/game.cpp:3404    game::draw(ui_adaptor&)
  #11
    (dbghelp: @0x7ff6b65a2572[cataclysm-tiles.exe+0x992572]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x1f4@0x140992572),
    0x140992572    src/ui_manager.cpp:411    ui_adaptor::redraw_invalidated()
  #12
    (dbghelp: @0x7ff6b5e7e502[cataclysm-tiles.exe+0x26e502]), 
    (libbacktrace: do_turn()+0x61a@0x14026e502),
    0x14026e502    src/do_turn.cpp:700    do_turn()
  #13
    (dbghelp: @0x7ff6b71665ed[cataclysm-tiles.exe+0x15565ed]), 
    (libbacktrace: main+0x16e8@0x1415565ed),
    0x1415565ed    src/main.cpp:789    main
  #14
    (dbghelp: @0x7ff6b5c113c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #15
    (dbghelp: @0x7ff6b5c114d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #16
    (dbghelp: BaseThreadInitThunk+0x10@0x7ff9c83954e0[KERNEL32.DLL+0x154e0]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #17
    (dbghelp: RtlUserThreadStart+0x2b@0x7ff9c884485b[ntdll.dll+0x485b]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### Steps to reproduce

1. Simply walk to the south and eventually the crash will occur, please let me know if you'd like me to send my save file(s).

### Expected behavior

I expected the game not to CTD

### Versions and configuration

Build:
2022-07-27-1411

World Mods:
* DDA
* Disable NPC needs
* No Fungal growth
* Bionic professions

**Comment by Zireael07** [comment] 2022-07-27 18:38
Judging by map cache, yet another dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/59632 which has a PR fix pending

**Comment by sevyns** [comment] 2022-07-27 19:15
Thanks @Zireael07 , I did notice at times I'll get a similar error when I save. However, this problem is occurring when moving around the map. Could simply be a symptom of the same underlying issue though.

**Comment by PotentPoizen** [comment] 2022-07-27 19:29
Am having same issue Segmentation Fault, Type:Signal

**Comment by kevingranade** [comment] 2023-03-19 21:48
Presumably fixed by #59648

**Closed by kevingranade** 2023-03-19 21:48 UTC
Labels: (S1 - Need confirmation)
