### ISSUE TITLE
Cannot consume batteries or plutonium for relevant bionics

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19438] opened 2016-11-24 12:29 UTC
For testing purposes, re-downloaded the entire game (latest experimental), started a new game with no mods aside from the base game. It was installed in a new directory so that configuration options were all set to the default.

Used debug to grant an internal reactor and battery system, and the skills necessary to install them, along with plutonium and batteries. When relevant bionics are active, the option to consume batteries or plutonium still does not appear in the [E]at menu. 

Can anyone else verify this bug, or is it just something silly like these items are consumed another way now and no one updated the wiki?

**Comment by codemime** [comment] 2016-11-24 12:35
Dupe of #18908.

**Closed** 2016-11-24 12:59 UTC
