### ISSUE TITLE
Error on completing a partial craft of steel rail

### ISSUE THREAD

**Issue by Runeerle** [CleverRaven/Cataclysm-DDA#32888] opened 2019-08-03 23:37 UTC
When completing an in progress steel rail I get this error:

 DEBUG    : 'scrap metal' is not a craft or has a null recipe
 
 FUNCTION : const recipe& item::get_making() const
 FILE     : src/item.cpp
 LINE     : 8680

# Steps To Reproduce

1. Craft steel rail to near completion.
2. Interupt crafting.
3. Resume crafting of "in progress steel rail (xx%)"

Alternatively use the provided save file:

1. Load player "Hacker"
2. Walk 7 steps north.
3. Select use (a) on the "in progress steel rail (98%)" to complete the crafting. Its on the workbench.
4. The error appers.

# Expected behavior
No error message.

# Versions and configuration
- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6126-g27d66a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

00:29:36.669 ERROR : (error message will follow backtrace)
	(@0x5b3b9e[cataclysm-tiles.exe+0x1b3b9e]), 
	(@0x5b41da[cataclysm-tiles.exe+0x1b41da]), 
	(@0x5b75c6[cataclysm-tiles.exe+0x1b75c6]), 
	(IMG_LoadWEBP_RW+0x111513@0x1136013[cataclysm-tiles.exe+0xd36013]), 
	(@0x7893f2[cataclysm-tiles.exe+0x3893f2]), 
	(@0x809239[cataclysm-tiles.exe+0x409239]), 
	(IMG_LoadWEBP_RW+0x2e4661@0x1309161[cataclysm-tiles.exe+0xf09161]), 
	(@0x7eb256[cataclysm-tiles.exe+0x3eb256]), 
	(@0xc4777d[cataclysm-tiles.exe+0x84777d]), 
	(@0xc5a06e[cataclysm-tiles.exe+0x85a06e]), 
	(@0xc5a32a[cataclysm-tiles.exe+0x85a32a]), 
	(@0xc5a649[cataclysm-tiles.exe+0x85a649]), 
	(@0x67908b[cataclysm-tiles.exe+0x27908b]), 
	(@0x6df06a[cataclysm-tiles.exe+0x2df06a]), 
	(@0x6b9c57[cataclysm-tiles.exe+0x2b9c57]), 
	(IMG_LoadWEBP_RW+0x57a738@0x159f238[cataclysm-tiles.exe+0x119f238]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x7786556d[kernel32.dll+0x1556d]), 
	(RtlUserThreadStart+0x1d@0x779c385d[ntdll.dll+0x5385d]), 
Backtrace emission took 0 seconds.
src/item.cpp:8680 [const recipe& item::get_making() const] 'scrap metal' is not a craft or has a null recipe

Savegame:
[bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3464399/bug.zip)

**Comment by l29ah** [comment] 2019-08-05 01:13
Looks like a dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/32009

**Closed** 2019-08-06 05:03 UTC
Labels: (S1 - Need confirmation), (S3 - Duplicate), <Bug>, Crafting / Construction / Recipes
