### ISSUE TITLE
DEBUG    : tried to set ammo for jumper_cable_heavy which does not have ammo or a magazine

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42319] opened 2020-07-20 21:53 UTC
# Describe the bug

 DEBUG    : tried to set ammo for jumper_cable_heavy which does not have ammo or a magazine

 FUNCTION : void Item_modifier::modify(item&) const
 FILE     : src/item_group.cpp
 LINE     : 324

# Steps To Reproduce
don't know, was doing nothing related

# Versions and configuration
10852

**Comment by KorGgenT** [comment] 2020-08-11 05:07
is this still a bug? how do we reproduce it?

**Comment by Fosheze** [comment] 2020-08-12 03:44
Just had this happen as well on build 10911. Mods are Aftershock and Blaze industries. Unfortunately I don't have a save from before the error to post but it pops up whenever the cables are first generated. In this case the error popped up when I first approached a recycling center that had jumper cables and heavy duty cables in the bins. Both cables spawned normally after the error was ignored.

**Comment by Enrymion** [comment] 2020-08-18 19:02
I got similar errors on starting a new game but for jumper_cable and for spray_can and the line number being [358](https://github.com/CleverRaven/Cataclysm-DDA/blob/5d168d50924133dfc29a47e9b72edb5ade9f3682/src/item_group.cpp#L358)

**Comment by wapcaplet** [comment] 2020-09-17 02:17
I cannot reproduce this error in 0.E-5926-g a883429bdd

Spawned fire lookout towers on the overmap until I found one that had heavy-duty cable (`jumper_cable_heavy`). I was able to `V`iew, `e`xamine, and pick up the cable with no errors.

**Comment by matt32106** [comment] 2020-09-17 12:15
This reminds me what I suggested in issues #42416 and others to automate the reporting of crash debug. It is ridiculous to not know how to reproduce a game related issue in a turn based game.

**Comment by Fosheze** [comment] 2020-09-17 15:13
I haven't seen this error in a long time either and I have played through multiple different runs since I last reported it. I believe it has been fixed. This one was fairly reproducible by simply walking near anywhere that spawned those cables.

**Comment by wapcaplet** [comment] 2020-09-17 21:48
@Fosheze Thank you for confirming. I agree it is probably fixed now. Closing issue.

**Closed by wapcaplet** 2020-09-17 21:48 UTC
Labels: (S1 - Need confirmation)
