### ISSUE TITLE
`uilist` is not the right height

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#76191] opened 2024-09-04 10:04 UTC
### Describe the bug

`uilist` is not the right height:

**Too short**

Examine nearby deployed solar panel
![image](https://github.com/user-attachments/assets/fbc2b6e5-7e58-4538-a00b-e9594f02a5eb)

Smartphone -> Check the system
![image](https://github.com/user-attachments/assets/41e1dfd1-7346-4a95-8b0e-afe47ba4e10a)

**Too long**

Debug menu
![image](https://github.com/user-attachments/assets/78204c8c-fccf-41b3-8486-934236b12034)

### Attach save file

N/A

### Steps to reproduce

Open relevant menus.

### Expected behavior

`uilist` is exactly as tall as it needs to be.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 0.G-11873-g30420a7022-dirty [64-bit] master was 0527e715c1
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by db48x** [comment] 2024-09-05 22:29
Duplicate of #75698

**Comment by db48x** [comment] 2024-09-05 22:30
Oh, and the debug window is #75667

**Closed** 2024-09-06 07:44 UTC
Labels: (S1 - Need confirmation)
