### ISSUE TITLE
Craters are spawning partially

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73950] opened 2024-05-20 00:03 UTC
### Describe the bug

See screenshots.

### Attach save file

N/A

### Steps to reproduce

1. Make a world
2. Run around and find craters.

### Expected behavior

Circular or ellipsoid or some sensibly shaped craters.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/fab581fc-b328-4dd3-b456-8871dd238873)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/37551b60-4b98-4475-b325-454282d1ca87)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9614-gf522d7df2d-dirty [64-bit] - master was 39e2afa80d
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment] 2024-05-20 00:13
This sounds like it is related to #73435 and the PR that fixes it.

**Comment by PatrikLundell** [comment] 2024-05-20 08:00
I don't think it's caused by that PR, because I've seen it in the past.

My guess would be that the explosion that's triggered when the "bomb" enters the reality bubble only affects the part of the OMT that's inside the reality bubble. If so, you should be able to work around it by having the explosion handling load the OMT in a smallmap (you need to affect at least the surface level and the level below that, with deeper craters a possible future enhancement), apply the explosion there, and then proceed. I think this would also have the positive side effect of allowing you to hide the explosion (it's supposed to have happened a long time ago), although you'd still affect local wildlife at the current time.
Note that you'd need to have different handling for the case of crater generation from the one for"real" explosions that happen well within the confines of the reality bubble, as you definitely want your hand grenades to produce effects.

**Comment by GuardianDll** [comment] 2024-05-20 09:11
Duplicate of #59781

> The most easiest solution is to place bomb in the center of OMT. This will work for medium-power bombs (such as on crater map extra), with explosion radius not crossing the boundaries of OMT. Consequently, this solution won't work for high-power bombs, as even one bomb with enough destructive power can have very big explosion radius which will cross the boundaries of OMT.

> The proper solution would be to rework explosion mechanic so it can handle crossing the boundaries of OMT.

**Closed by GuardianDll** 2024-05-20 09:11 UTC
Labels: (S3 - Duplicate), Character / World Generation

**Comment by PatrikLundell** [comment] 2024-05-20 12:24
If explosions are to be able to cross OMT boundaries then I'd suggest the use of a map centered on the center submap in a manner similar to how we use tinymaps (and fakemaps, and smallmaps) to generate stuff. Let the explosion occur on this map as soon as the reality bubble touches the outermost submap of the explosion radius, or the OMT or submap of the explosion center, of dealing with radii is too hard.
Instead of a map you could use something smaller but still large enough, but I suspect a map is good enough.
The side effect of that implementation is that OMTs around the explosion would be generated a little earlier than normal, but that really only affects save scumming for the generation (or non generation) of stuff on those OMTs.
