### ISSUE TITLE
Ammo/Chemical Stuff duplication glitch in experimental

### ISSUE THREAD

**Issue by adamaxis** [CleverRaven/Cataclysm-DDA#47897] opened 2021-03-06 05:57 UTC
# Describe the bug
Item duplication glitch. It seemed to only work when I did it with certain things like Ammo(tested '00 shot' and 'bearings') and Chemical Stuff(tested 'gunpowder').
Basically, on advanced inventory, if you xfer items from one area to another using 'm' or # xfer, if you transfer less than the entire amount (E.G. you have 136 marbles and xfer 135 to the ground) it will duplicate them at the destination without removing from the source. I performed it about 10 times and posted a screenshot on discord.

# Steps To Reproduce
1) Acquire a stack of ammo
2) Open advanced inventory management
3) Set source to wherever ammo is, destination to wherever you want to duplicate to
4) Hit 'm' or # xfer and xfer less than the full amount(E.G: if there's 36, xfer 35)
5) You will end up with duplicated items. In this case, there is now a total of 71 ammo.

# Expected behavior
Self-explanatory, but tldr; duplication = bad.

# Screenshots
(After duplication around 500 '00 shot')
https://ibb.co/NNPBJFh

# Versions and configuration
- OS Version: Windows 10.0 1903
- Game Version: 0.E-9945-g5960368 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro]

**Comment by anothersimulacrum** [comment] 2021-03-06 06:01
Duplicate of #47884

**Closed** 2021-03-06 06:01 UTC
Labels: (S3 - Duplicate)
