### ISSUE TITLE
Using items takes unreasonably long unless activated via "A"

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#19899] opened 2017-01-01 00:29 UTC
Tested in Windows graphical builds 0.C-20286-g7c34c36 (6068) and 0.C-20379-g3b0be33 (6097).

I discovered this while testing a pending pull request to another repository. Activating items causes a considerable delay up as much as a minute if activated from the "use item" menu, regardless of whether the item is in inventory, worn, or wielded. But only a single turn is consumed if a wielded item is activated via the "apply or use item menu" command is used.

Some example tests, all of these being worn due to only discovering later that it was not merely worn items affected:

Mining Helmet
8:03:42
8:04:24

Fedora
8:05:00
8:05:30

Thermal Electric Suit
8:06:06
8:06:36

Gilded Aegis (Arcana Mod)
8:00:24
8:01:12

Revenent Crown (Arcana Mod)
8:02:00
8:03:00

**Comment by DangerNoodle** [comment] 2017-01-01 19:23
@kevingranade, in another repository discussion, @chaosvolt has presented some conjecture as to the what was likely changed. Would I be permitted to summarize what they said? They claimed to be blocked from this repository.

If that claim is true though, I suspect they will be unable to follow https://github.com/CleverRaven/Cataclysm-DDA/issues/19376, which is important as they are maintaining a third-party mod.

**Comment by WizardOfOoo** [comment] 2017-01-02 00:22
They can read it.

**Comment by DangerNoodle** [comment] 2017-01-02 04:09
Understood. To summarize, they theorized that part of cause might be a calculation that uses the weight and/or volume of the item being activated to determine time cost. I am unsure as I do not know when this feature was implemented, so I can not speculate on what determines the new time cost.

They also stated a suspicion that the feature causing this was inadequately play tested, and that it does not take into account how much time the item logically should take to activate. The former I do not know about, whereas the latter I do agree with, as there does not seem to be any sign of time variation in place specific to 'use_action' or item ID.

> That's his problem.

I suspect some mutual hostility?

**Comment by Coolthulhu** [comment] 2017-03-18 05:11
This was caused by item manipulation times being huge. Should be fixed now.

**Closed by Coolthulhu** 2017-03-18 05:11 UTC
Labels: Bug, Confirmation Needed

**Comment by DangerNoodle** [comment] 2017-03-18 05:15
Thank you. However, I do wonder whether the inconsistency involving activating wielded objects has been fixed.
