### ISSUE TITLE
Can't start a game

### ISSUE THREAD

**Issue by kingofthecatsIII** [CleverRaven/Cataclysm-DDA#20472] opened 2017-03-07 02:28 UTC
When creating a world and starting a character I receive an error saying invalid overmap terrain id "field_shallow" and then the game closes.

**Comment by kolsurma** [comment] 2017-03-07 03:43
Just a few questions:
- On what OS did you experience the problem (Windows, Linux, OS X etc.)

- What version were you playing:  
   - Tiles or Curses (text-based)
   - Version string (preferably full version e.g. "0.C-4547-g3f1c109", or Jenkins build number e.g. 3245)

- Description of the problem you've found written in a way that enables anyone to try recreate it

Thanks!

**Comment by kingofthecatsIII** [comment] 2017-03-07 04:00
Windows 64 bit,  version 0.C-21521-g832a687fe5 (tiles).  
While creating a new charater, whether custom, preset,random or play now, the world that i've seleceted will start to generate the debug screen will appear stating error's with the overmap and forest terrain. eg invalid overmap terrain id "forest_vein" and In overmap scecial "vein_forest_shallow"

**Comment by kingofthecatsIII** [comment] 2017-03-07 04:01
Thank you for helping

**Comment by kingofthecatsIII** [comment] 2017-03-07 04:04
After creating the character and trying to load up the world the debug screen will appear and say invalid overmap terrain id "field_shallow" and then the game closes.

**Comment by kingofthecatsIII** [comment] 2017-03-07 04:04
If there is anything that needs clarifying just ask.

**Comment by kolsurma** [comment] 2017-03-07 04:33
Is this a new world or one you've imported from an older version? What mods are enabled?

If possible, could you zip (tar, 7z) the world and upload it?

Thanks!

**Comment by kingofthecatsIII** [comment] 2017-03-07 04:47
The world I used was a new one that was created a few minutes ago. 
Mod list: dda(dark days ahead), Tall buildings, deadleaves fictional guns, Medieval and historic content, mining mod, More survival tools, StatsthroughskillsIV, Vehical additions pack, tanks and other vehicles, boats, craftable gun pack, folding parts pack Icecoon's arsenal, extended buildings,
more craftable, fuel multiplier, more classes, more locations mutation changes, mythological Replicas, and extended realistic guns. I'm not sure how to zip or tar world.

**Comment by kolsurma** [comment] 2017-03-07 07:45
Pinging @DangerNoodle, PR 20295 slightly broke terrain generation in the mining-mod, made comment to the issue on your repo.

**Comment by DangerNoodle** [comment] 2017-03-07 16:43
My apologies, I had forgotten that `NO_ROTATE` was now an important flag.

**Comment by DangerNoodle** [comment] 2017-03-07 17:19
My efforts to fix this appear to work but are now causing unknown issues with More Locations mod, which a "cannot place some specials" error occurring after character creation, but refusing to list the special actually causing the issue. Possible cause is the same reason https://github.com/CleverRaven/Cataclysm-DDA/pull/20445 is occurring in worlds without my mod or @pisskop's mod, due to both rendering cemetaries non-mandatory. In this case the likely cause would be factories.

I will want to use copy-from later on to make this mod more future-proof, but I will have to do this later. I will need to get read to go soon. For now my latest commit should resolve these load errors.

**Comment by DangerNoodle** [comment] 2017-03-07 18:54
I am now further testing whether the More Locations anomaly occurs without the addition of Mining Mod, or it is indeed from mod combining. If factories are causing issues on their own, I could implement a pull request to resolve that, but I need to ensure my own mod is not also being problematic.

**Comment by pisskop** [comment] 2017-03-07 18:58
Ill get that 'cant place unspecified specials' error, but Im assuming its a failure on the games part rather than my own.

**Comment by DangerNoodle** [comment] 2017-03-07 19:01
Given my inexperience with the large number of recent changes to map generation behavior, I am unfortunately not as confident in my 

Religious cemeteries are a confirmed vanilla issue, as there is a pull request reducing their occurrences. My own mod should not have the exact same error as all overmap specials added are 1 by 1, but I do not wish to rule out the potential for problems on my end.

**Comment by DangerNoodle** [comment] 2017-03-07 19:10
Now however I am having an issue of "cannot place specials" even in a vanilla world, after having reduced minimum occurrences of cemeteries to 0.

**Comment by kingofthecatsIII** [comment] 2017-03-07 22:05
Thank you guys for helping 👍

**Comment by Coolthulhu** [comment] 2017-03-25 14:22
I assume this is now fixed

**Closed by Coolthulhu** 2017-03-25 14:22 UTC
Labels: Mods

**Comment by DangerNoodle** [comment] 2017-03-25 15:44
Other than most likely existing issues with overmap placement, it should be fixed. The related issue in my mod repository I have closed for now, with a request to inform me there in the event that it re-occurs.
