### ISSUE TITLE
submit to flathub 

### ISSUE THREAD

**Issue by trkgopher** [CleverRaven/Cataclysm-DDA#60429] opened 2022-08-24 23:55 UTC
### Is your feature request related to a problem? Please describe.

I can't install the raw code without disabling the immutable file system built into my iOS, which means the code gets wiped every time I update the OS. 

### Solution you would like.

Would dearly like to be able to download as a flat pack but needs to be submitted to flat hub. 

### Additional context

Some Linux OS with immutable file systems don't like non-flat pack installations. Specifically in my case the Steam OS factory installed on the steam deck.

**Comment by anothersimulacrum** [comment] 2022-08-25 00:03
https://github.com/CleverRaven/Cataclysm-DDA/issues/33682

**Comment by ZhilkinSerg** [comment] 2022-08-25 07:37
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33682

**Closed** 2022-08-25 16:30 UTC
Labels: <Suggestion / Discussion>
