### ISSUE TITLE
Very frequent "std::bad_aloc" Crash

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#39953] opened 2020-04-27 08:38 UTC
I'm getting a CTD with this error message every few minutes in my game.

![image](https://user-images.githubusercontent.com/19789267/80351174-752b2f80-88a4-11ea-9c94-eb2e479adaea.png)

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1242-gea7d0d3 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Whaleys Hair Mod [WHALEYHAIR1],
    No Fungal Monsters [No_Fungi]
]

I can't find any particular pattern to it. It seems to happen randomly, but it's frequent enough that I can hardly play on this save file anymore despite saving very aggressively.

No guaranteed repro steps, but I'm hoping you'll be able to reproduce it by just hopping on the nearby bike and riding around a bit. I certainly can't get through half an ingame day without it triggering.

Crash log, save file and my only non-mainlined mod (which I doubt is responsible, but you never know) are attached.
[Eveleth.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4538384/Eveleth.zip)
[Whaleys New Hair Mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4538388/Whaleys.New.Hair.Mod.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4538390/crash.log)

**Comment by ZhilkinSerg** [comment] 2020-04-27 09:26
Looks like duplicate of #39914.

**Closed by ZhilkinSerg** 2020-04-27 09:26 UTC
