### ISSUE TITLE
Encumbrance doesn't get updated when cutting up worn clothes

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32529] opened 2019-07-21 11:26 UTC
# Steps To Reproduce

1. Note your encumbrance.
2. Cut up a piece of encumbering clothing you're wearing using `%c`.
3. The encumbrance haven't changed even though the clothes are gone.

0.D-5749-ga24f3b03bf-dirty

**Comment by Petethegoat** [comment] 2019-07-24 04:45
I can reproduce this in 0.D-5777-g74b4a6c, and on the current master which is 0.D-5821-g824ddc5bda, but not on my branch with #32399 
So it's either somehow fixed by those changes, or it was introduced in one of the 255 commits between that branch and the current master.

**Comment by Petethegoat** [comment] 2019-07-24 04:52
Just checked and I can't reproduce it with https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9314

**Comment by Petethegoat** [comment] 2019-07-24 06:05
![image](https://user-images.githubusercontent.com/734762/61769152-f4885180-adae-11e9-8110-795322d3e4cd.png)
#32342

Presumably the change in character.cpp.

**Comment by l29ah** [comment] 2019-07-24 09:21
Looks like it doesn't get updated if you use an item you wear as a component in crafting.

**Comment by Petethegoat** [comment] 2019-07-24 16:47
@l29ah Are you sure? There is code to reset encumbrance during crafting, and in my testing it works.
Worn long sleeved shirt -> T-shirt will correctly update encumbrance

**Comment by l29ah** [comment] 2019-07-24 16:52
Okay, i can't reproduce it now in a test world so ignore it.

**Comment by l29ah** [comment] 2019-08-06 11:02
The encumbrance doesn't get updated when you disassemble worn items. Load and disassemble the worn hand wraps: 
[TESTBED VANILLA.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3471827/TESTBED.VANILLA.zip)

**Closed** 2019-08-15 07:47 UTC
Labels: Character / Player, Info / User Interface, Items / Item Actions / Item Qualities

**Comment by l29ah** [comment] 2019-08-26 22:52
Still an issue when disassembling worn items.

**Comment by l29ah** [comment] 2019-08-26 23:07
As can be seen in a comment before: hand wraps.
