### ISSUE TITLE
Colors Template "no bright backgrounds" causes error on Tutorial load.

### ISSUE THREAD

**Issue by clort81** [CleverRaven/Cataclysm-DDA#54963] opened 2022-01-31 07:38 UTC
### Describe the bug

In Git Master 2022-01-30, Colors Template "no bright backgrounds" causes error on Tutorial load.

```
 DEBUG    : (json-error)
Json error: usr/share/cataclysm-dda/json/overmap/overmap_terrain/overmap_terrain_faction_base.json:120:13: cannot assign explicit value the same as default or inherited value

    "name": "trench",
    "sym": "X",
    "color":
            ^
             "light_gray",
    "extend": { "flags": [ "SHOULD_NOT_SPAWN" ] }
  },


 FUNCTION : void report_strict_violation(const JsonObject&, const string&, const string&)
 FILE     : src/assign.h
 LINE     : 49
 VERSION  : 0.F

```

### Steps to reproduce

1. set color template to the second option - no bright backgrounds
2. load tutorial under 'special' menu
3. see the error.

### Expected behavior

no error

### Versions and configuration

-devuan ceres
- 0.F-5074-g7684355350
- aarch64

### Additional context

No Crash

**Comment by ZhilkinSerg** [comment] 2022-01-31 15:20
Duplicate of #26102

**Closed by ZhilkinSerg** 2022-01-31 15:20 UTC
Labels: <Bug>, (S2 - Confirmed)
