### ISSUE TITLE
Flesh raptor kill causes CTD

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#64770] opened 2023-04-02 02:17 UTC
### Describe the bug

Crash occurs when I kill this flesh raptor.

### Attach save file

[Wilton Manors-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11131021/Wilton.Manors-trimmed.tar.gz)

### Steps to reproduce

Just head south and shoot it to death.

### Expected behavior

No crash.

### Versions and configuration

OS: Win10x64
Game Version: 465fac4 (tiles) 2023-04-01-0023 (a day ago)
Graphics version: Tiles
Ingame language: English

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11131022/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11131023/crash.log)

**Comment by SurFlurer** [comment] 2023-04-02 02:26
Duplicate of #64466

**Closed** 2023-04-02 02:28 UTC
Labels: (S3 - Duplicate)
