### ISSUE TITLE
Cant close a non diagonal vehicle door by standing next to it

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#58303] opened 2022-06-09 14:23 UTC
### Describe the bug

When the car is parked straight (non-diagonal) cant close the door, getting a message "there's some buffoon in the way!" but if i place myself diagonally its ok.
```
Cant open:
 @
=+=

Can open:
@
=+=
```

### Steps to reproduce

Just stand next to any vehicle door and try to open it from various positions

### Expected behavior

I expect to be able to open the vehicle doors when standing next to them

### Screenshots

![image](https://user-images.githubusercontent.com/17822510/172869971-f9638bfd-425b-4150-80ce-7a0abf1c4021.png)

### Versions and configuration

- version f689b47 (tiles)
- build 2022-06-09-1125

**Comment by Ilurker** [comment] 2022-06-09 21:01
I'm also experiencing this. Moving one space to the north or south of the usual space does not solve it, as the character is then out of range of the door and does not have the ability to interact with it at all. Likely caused by #56143 and related to #58287

**Comment by hexagonrecursion** [comment] 2022-06-11 15:05
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Inglonias** [comment] 2022-06-22 22:32
I am also seeing this issue.

**Comment by descan** [comment] 2022-07-10 00:26
This definitely happens to me but I also thought this was WAD - car doors are big, I just assumed it was supposed to be that they were jutting into the tile and you can't close it without really getting out of the way?

**Closed** 2022-07-25 05:53 UTC
Labels: (S2 - Confirmed)
