### ISSUE TITLE
Segfamentation fault on saving (OSX - Mojave)

### ISSUE THREAD

**Issue by garethjax** [CleverRaven/Cataclysm-DDA#33118] opened 2019-08-10 13:52 UTC
# Describe the bug

Just after the game is started, when i try to save (or sometimes when i save and quite) a segmentation fault error is invoked.
Active mods: magyclism.

# Steps To Reproduce

1. Make a player with the scenario "apprentice wizard"
2. Explore the place a bit
3. Quicksave

# Expected behavior

It should not quit with a SEG GFAULT.

# Screenshots

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.5; Build: 18F132; 
- Game Version: 0.D-6405-g3439b4c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

 - OS: Osx Mojave 10.14.5
 - Game Version: experimental build #9467
 - Graphics version: Tiles
 - Mods loaded: Magiclysm

# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3488877/logs.zip)
[Magimondo 2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3488878/Magimondo.2.zip)

**Comment by sztosz** [comment] 2019-08-10 16:29
Probably duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33051

**Comment by ZhilkinSerg** [comment] 2019-08-10 20:35
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33051

**Closed by ZhilkinSerg** 2019-08-10 20:35 UTC
