### ISSUE TITLE
Unable to Reload Certain Tools (Sewing Kits, Shaving Kits, Fish Traps)

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#40666] opened 2020-05-18 05:45 UTC
# Describe the bug
Cannot reload certain items (all sewing tools/kits, shaving kits, and fish traps tested so far all show the issue).  The thread/soap/fish bait is still consumed, but the charges remain the same.

# Steps To Reproduce

1. Load up a game in latest experimental branch (latest tested was 10677)
2. Acquire sewing kit, shaving kit, fish trap, etc with fewer than full charges and its respective "ammo"
3. Reload
4. Observe that ammo count has decreased while loaded charges remain unchanged

# Expected behavior
You are able to reload items normally.

# Versions and configuration

 - OS: Win10
 - Game Version: 0.E 10677
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: dda, disable NPC needs, Blaze Industries, C.R.I.T, Magiclysm, Dino, Altern Map Key, MMA, Zetsukaze's Hair 0.E Edit, Graphical Overmap, Graphical Overmap Magiclysm, sees-player icon retro, Fuji's, SpeedyDex, Stats through Kills, Stats through Skills

# Additional context
Save: [West Lake Hollow.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4642220/West.Lake.Hollow.zip)

**Comment by MechaJeb** [comment] 2020-05-18 05:46
Yes it's been known for a while, it's being worked on in #40399

**Comment by PaulPyl** [comment] 2020-05-18 06:27
Still an issue, I saw it with a hobo stove in 10676 also.

**Comment by ZhilkinSerg** [comment] 2020-05-18 07:10
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/40125

**Closed by ZhilkinSerg** 2020-05-18 07:10 UTC
