### ISSUE TITLE
[DinoMod] Packs of zombified  predatory dinos spawn in the middle of the ocean

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#71220] opened 2024-01-24 13:13 UTC
### Describe the bug

So yeah as described, if you load my save and move around in the boat you'll see there's lots of mid-big sized groups of really heavy and dangerous dinos just spawning in the middle of the ocean, then they proceed to try and kill all local wildlife and you of course

### Attach save file

[Town West-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14038784/Town.West-trimmed.tar.gz)

### Steps to reproduce

1. Load save, there's a group there
2. Sail about for a bit you'll find plenty of other groups

### Expected behavior

Not to find skeletal theropod juggernauts all over the sea/lakes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: de8a47f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by harakka** [comment] 2024-01-24 13:34
Duplicate of #68045 but with newer repro save

**Comment by LyleSY** [comment] 2024-09-24 00:53
Thanks for your patience with this one. Took a long while for the infrastructure to be built to support this, but this is looking great now in testing.

**Closed** 2024-10-01 14:37 UTC
Labels: <Bug>, Mods: Dinomod
