### ISSUE TITLE
Aiming issues - Target resets to default if chosen target moves while character is aiming.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#18032] opened 2016-08-14 17:08 UTC
I'm not sure exactly what is happening just yet but I've observed that recently that aiming with multiple targets is a bit off.  Playing on Windows x64 Tiles 0.C-17592-g570D56b.  I hadn't really been in any significant combat in close to a week in real time; I have an immobile base and dealing with farming and some light forest hunting.

I've noticed (and did a few tests) where if I have more than one target, say on opposite sides of the character, and I choose a different target than the default with either direction keys or <> keys and then begin aiming that should my target move my character switches to the default target.  This is also (more importantly IMO) the case with (p)recise aim.  If the chosen target moves during the aim phase the default target is what is fired at, not the still visible and in range target I chose initially.

Aiming used to stick to whatever target I had chosen, excepting if I lost sight/range, in which case the default would be picked.  My tests were in relatively clear sight/range so I don't think it's sight loss that's causing the default pick.

I'll try to be back with a modless fresh world test since my windows runs quite a few mods but compiling takes quite a while w/o clang so I'm liable to forget with other stuff today.  Edit: OK, so ascii build isn't too bad without clang :) .

**Comment by Zireael07** [comment] 2016-08-14 17:19
Duplicate of #17811?

**Comment by ProfoundDarkness** [comment] 2016-08-14 17:34
Yep... duplicate I think.  My searches failed me, sorry.  Also very unfamiliar with git still so not sure what to do about being duplicated.

Should it help here are the steps I used to reproduce on linux x64 ascii 0.C-17598-gad4425f (pulled from master a short time ago) compiled with flags LUA=1 CCACHE=1 (I had just cleared ccache) on a new no mod world with new fresh character.
- Wished for composite bow and bow sight, bow stabilizer mods.  Applied mods to bow.
- Wished for large quiver and some arrows and put arrows in quiver.
- Modified character's archery stat to level 10 (more likely to hit target and thus see that (p)recise aim fired on wrong target).
- Moved outside of shelter into daylight/clear area.
- Spawned two zombies 8 tiles up and down opposite sides of character (north/south).
- Entered (f)ire mode, default target is north.
- Switched to southern target and started aiming (steady aim, not aim and fire).
- When southern zombie moved (well they both did) northern zombie was re-targeted.  both moved closer to character.
- Moved character (to reset aim steadiness).
- Entered fire mode, default target is northern zombie (now 1 tile closer than southern zombie).
- Targetted southern zombie.
- Used (p)recise firing option, on screen indication that northern zombie was fired on/hit.

**Closed** 2016-08-20 10:31 UTC
