### ISSUE TITLE
JSON Save Corruption

### ISSUE THREAD

**Issue by Belly-Smelly** [CleverRaven/Cataclysm-DDA#74158] opened 2024-05-28 20:40 UTC
### Describe the bug

On the latest Stable Release Candidate, a save corruption occurs after exploring a lab in the Lab Patient Challenge Scenario. I haven't tested every starting location but it happens very consistently with the Experiment Cell location.
Errors happen when loading the save and sometimes while playing, I think during autosaves. The error says something about an "illegal UTF-8 sequence", then a huge text dump from the save files. Sometimes it is possible to load the save despite the errors, eventually it gets to a point where it just boots you back to the main menu after showing the errors.

### Attach save file

[Newbern-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15475688/Newbern-trimmed.tar.gz)

### Steps to reproduce

I have two characters packaged in the above world. 
Simply loading Everett Parnell should throw errors as soon as fully loaded, then boot you back to the main menu immediately.

Test Patient consistently gets the error but lets you get into the game, but to reproduce the error for them you need to
1. Load Test Patient
2. Save and exit
3. Load Test Patient again
Not sure why, but it is consistently necessary to load into the character, save, then load them again to get the error after the world is zipped up- except for characters that "crash" you back to the main screen.

### Expected behavior

I expect a save file to not get corrupted from being in a lab, I guess xD

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fc75aa7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Not strictly speaking a crash so no crash log, but I'll upload the debug.log from trying to load the character that boots you back to the main screen.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15475748/debug.log)

**Comment by AshenColors** [comment] 2024-05-30 18:14
I reproduced the runtime errors from the save archive on Linux, Flatpak build 1666cf2. Slightly more interesting, I also managed to consistently reproduce (three successes in three attempts) what seems like the same issue without the use of the provided save archive, but the behavior is quite different, resulting in a crash instead of runtime errors. I suspect platform differences may be at play.

Steps: 
1. Make a new world with all default settings.
2. Make a new custom character with the Lab Patient scenario and Experiment Cell starting location. (Leave everything else on default.) Finish character creation.
3. Before doing anything else, Save and Quit from the game menu.
4. Load the same character. The crash occurs before the player receives control again.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15504103/crash.log)

- OS: Linux
    - OS Version: <unknown>
- Game Version: 1666cf2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TealcOneill** [comment] 2024-05-31 09:26
/Confirm
I'm seeing this same error while moving around near a trailer park.

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: f8cf42f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

This is the full error I'm getting.
 DEBUG    : Failed to read from "./save/Greer/maps/13.9.0/440.319.0.map": Json error: save/Greer/maps/13.9.0/440.319.0.map:1:10823: <color_white><color_cyan>illegal UTF-8 sequence</color>

sed":true,"disabled":false,"unload":true,"player_edited":false}},{"pocket_type":8,"contents":[],"_sealed":false,"no_rigid":[]}],"additional_pockets":[]}},{"typeid":"bottle_twoliter","owner":"","last_temp_check":0,"contents":{"contents":[{"pocket_type":0,"contents":[{"typeid":"zeromdew","charges":1,"owner":"","active":true}],"_sealed":false,"no_rigid":[],"favorite_settings":{"name":null,"priority":0,"item_whitelist":["zeromdew"],"item_blacklist":[],"category_whitelist":[],"cate<color_light_red>gory_blacklist":[],"collapsed":true,"disabled":false,"unload":true,"player_edited":false}},{"pocket_type":8,"contents":[],"_sealed":false,"no_rigid":[]}],"additional_pockets":[]}}],9,10,[{"typeid":"steel_pan","owner":"","last_temp_check":0},{"typeid":"copper_pan","owner":"","last_temp_check":0}],9,11,[{"typeid":"stock_pot","owner":"","last_temp_check":0}]],"traps":[],"fields":[],"cosmetics":[],"spawns":[["mon_zombie",1,9,10,-1,-1,false,"�fǈ^\u0001\u0000\u0000pfǈ^\u0001\u0000"]],"vehicles":[],"partial_constructions":[]},{"version":33,"coordinates":[880,639,0],"turn_last_touched":5305687,"temperature":0,"terrain":[["t_grass",3],"t_dirt","t_wall_w",["t_linoleum_gray",2],"t_wall_w",["t_floor",2],"t_wall_w","t_concrete",["t_grass",4],"t_wall_w",["t_linoleum_gray",2],"t_door_c",["t_floor",2],"t_door_elocked","t_concrete",["t_grass",4],["t_wall_w",4],["t_floor",2],"t_wall_w","t_concrete",["t_grass",3],"t_grass_dead","t_wall_w",["t_floor",5],"t_wall_w",["t_grass",5],"t_wall_w",["t_floor",5],"t_curtains",["t_grass",5],"t_wall_w",["t_floor",5],"t_wall_w",["t_grass",2],["t_grass_dead",2],"t_grass",["t_wall_w",2],["t_window_domestic",2],"t_window_open",["t_wall_w",2],"t_grass_dead","t_dirt","t_grass","t_grass_dead","t_grass","t_grass_dead","t_grass","t_dirt",["t_grass",7],"t_grass_dead",["t_grass",7],"t_grass_dead",["t_grass",6],"t_grass_dead",["t_grass",3],"t_dirt",["t_grass",3],"t_grass_dead",["t_grass",4],"t_dirt",["t_grass",3],"t_dirt","t_grass","t_grass_dead",["t_grass",5],"t_dirt",["t_grass",5]],"radiation":[0,144],"furniture":[[5,0,"f_sink"],[6,0,"f_toilet"],[9,0,"f_trashcan"],[5,1,"f_shower"],[9,2,"f_rack_coat"],[5,3,"f_sofa"],[7,3,"f_armchair"],[9,3,"f_entertainment_center"],[5,4,"f_sofa"],[6,4,"f_coffee_table"],[9,4,"f_entertainment_center"],[5,5,"f_sofa"],[8,5,"f_indoor_plant_y"],[9,5,"f_entertainment_center"]],"items":[5,0,[{"typeid":"soap","charges":1,"owner":"","last_temp_check":0},{"typeid":"bag_plastic","owner":"","last_temp_check":0,"contents":{"contents":[{"pocket_type":0,"contents":[{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0},{"typeid":"cotton_ball","owner":"","last_temp_check":0}],"_sealed":false,"no_rigid":[],"favorite_settings":{"name":null,"priority":0,"item_whitelist":["cotton_ball"],"item_blacklist":[],"category_whitelist":[],"category_blacklist":[],"collapsed":true,"disabled":false,"unload":true,"player_edited":false}},{"pocket_type":8,"contents":[],"_sealed":false,"no_rigid":[]}],"additional_pockets":[]}},[{"typeid":"toothbrush_plain","snip_id":"tbrush2","owner":"","last_temp_check":0},2]],6,0,[{"typeid":"water","charges":24,"active":true,"last_temp_check":5305687,"specific_energy":"955.967285","temperature":"284.417816"}],6,4,[{"typeid":"sneakers","owner":"","last_temp_check":0}],9,4,[{"typeid":"television","last_temp_check":0}]],"traps":[],"fields":[],"cosmetics":[],"spawns":[],"vehicles":[],"partial_constructions":[]},{"version":33,"coordinates":[881,638,0],"turn_last_touched":5376667,"temperature":0,"terrain":["t_dirt",["t_grass",3],"t_grass_dead",["t_grass",13],"t_grass_dead","t_dirt",["t_grass",3],["t_grass_dead",2],["t_grass",5],"t_grass_dead",["t_grass",4],"t_grass_dead",["t_grass",4],["t_grass_dead",2],["t_grass",11],"t_grass_dead",["t_grass",2],"t_grass_dead",["t_grass",2],"t_grass_dead",["t_grass",2],"t_grass_dead","t_dirt",["t_grass",33],"t_grass_dead",["t_grass",5],"t_grass_dead",["t_grass",5],"t_grass_dead",["t_grass",2],"t_dirt",["t_grass",14],"t_dirt",["t_grass",7],["t_dirt",3],"t_grass",["t_dirt",2],["t_grass",3]],"radiation":[0,144],"furniture":[],"items":[],"traps":[],"fields":[],"cosmetics":[],"spawns":[],"vehicles":[],"partial_constructions":[]},{"version":33,"coordinates":[881,639,0],"turn_last_touched":5376667,"temperature":0,"terrain":["t_concrete",["t_dirt",2],"t_grass","t_railroad_rubble",["t_dirt",2],"t_railroad_rubble","t_dirt","t_grass_dead",["t_grass",2],"t_concrete",["t_dirt",3],"t_railroad_rubble",["t_dirt",3],"t_grass","t_grass_dead",["t_grass",2],"t_concrete",["t_grass",2],"t_dirt","t_railroad_rubble",["t_dirt",2],"t_railroad_rubble","t_dirt",["t_grass",2],"t_grass_dead","t_grass","t_grass_dead","t_grass",["t_dirt",3],"t_grass","t_railroad_rubble","t_dirt",["t_grass",2],"t_dirt",["t_grass",4],"t_railroad_rubble","t_grass",["t_dirt",2],["t_grass",3],"t_grass_dead","t_grass","t_dirt","t_grass",["t_dirt",3],"t_grass","t_railroad_rubble","t_dirt",["t_grass",6],"t_grass_dead","t_grass",["t_dirt",2],"t_railroad_rubble",["t_grass",5],"t_dirt","t_grass_dead","t_grass",["t_dirt",5],["t_grass",6],"t_dirt","t_railroad_rubble","t_grass",["t_dirt",3],["t_grass_dead",2],["t_grass",2],"t_grass_dead","t_grass","t_dirt","t_railroad_rubble","t_grass","t_dirt","t_railroad_rubble",["t_dirt",2],["t_grass",5],"t_dirt","t_railroad_rubble","t_grass_dead","t_dirt","t_railroad_rubble",["t_dirt",2],["t_grass",5],["t_dirt",2],"t_grass","t_grass_dead","t_railroad_rubble",["t_grass",4]],"radiation":[0,144],"furniture":[],"items":[],"traps":[],"fields":[],"cosmetics":[],"spawns":[],"vehicles":[],"partial_constructions":[]}]</color>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <color_cyan>▲▲▲</color></color>


 FUNCTION : bool read_from_file_json(const cata_path&, const std::function<void(const JsonValue&)>&)
 FILE     : src/cata_utility.cpp
 LINE     : 562
 VERSION  : f8cf42f

**Comment by kevingranade** [comment] 2024-06-09 20:59
have a backtrace, still looking into it...
![Screenshot from 2024-06-09 13-58-52](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/cca69f83-99b0-4300-bee4-1fac498e00bd)

**Comment by kevingranade** [comment] 2024-06-09 21:12
Looks like the crash happens when attempting to deserialize this entry?
`"spawns":[["mon_prototype_cyborg",1,6,6,-1,-1,false,null]],`

**Comment by kevingranade** [comment] 2024-06-09 21:21
Basically "name" is "null", it correctly(?) deserializes as a nullptr, then tries to dereference it which fails.  The odd thing is this code is unchanged on tip of mainline? maybe the std::optional deserializer changed?

**Comment by Maleclypse** [comment] 2024-07-08 20:57
closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/74421

**Closed by Maleclypse** 2024-07-08 20:57 UTC
Labels: (S2 - Confirmed), 0.H backport candidate
