### ISSUE TITLE
Crash when pressing Enter when filter returns nothing

### ISSUE THREAD

**Issue by ObsidianBottle** [CleverRaven/Cataclysm-DDA#32302] opened 2019-07-10 19:17 UTC
# Describe the bug

Pressing select in an inventory filter menu that has no available choices crashes the game.

# Steps To Reproduce

1. Open an inventory menu
2. Press / and type gibberish into the filter
3. Press enter

![cataclysm-tiles_ujKlUw289F](https://user-images.githubusercontent.com/39647257/60997759-2b5f7000-a38a-11e9-97fc-42a9034b2b66.png)

# Expected behavior

Nothing to happen.

# Versions and configuration

- OS: Windows
    - OS Version: Windows7
- Game Version: 0.D-5505-g23f24bd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3379033/crash.zip)

**Comment by AMurkin** [comment] 2019-07-10 20:06
Duplicate of #31790.

**Closed** 2019-07-11 05:32 UTC
Labels: (S3 - Duplicate), <Bug>
