### ISSUE TITLE
Head encumbrance should have some penalty

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19739] opened 2016-12-12 14:17 UTC
I'm sure I'm not the only person that abuses the lack of encumbrance penalty on the head by wearing super-heavy helmets modified with as much reinforcement as possible.

I'd propose that head encumbrance maybe reduce perception slightly, my reasoning a very heavy helmet might partially or completely cover the ears (reducing hearing), make noise, and maybe slow down one's ability to turn their head and scan for enemies. Or maybe a reduction to dodge slightly for the same reasons. Thoughts?

**Comment by Tharn** [comment] 2016-12-12 16:03
Sounds good to me. Ideally some of the effects of eye encumbrance could be transferred to the head. If you just add a new source for penalties, that'd make it a straight downgrade. If you gave those two bodyparts 50-75% of the penalty for the former one bodypart that should work out okay. Perception and hearing makes sense.

**Comment by keyspace** [comment] 2016-12-12 16:31
Duplicate of: #18874

**Closed** 2016-12-12 16:33 UTC
