### ISSUE TITLE
Clean Water recipe has changed in crafting menu

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#47908] opened 2021-03-06 17:22 UTC
# Describe the bug

The common recipe "clean water " in the crafting menu has changed. See pic 1.

# Steps To Reproduce

I dont know anything in detail that happened in between using the recipe.
I had 2 gallon jugs for water. And filled them up with the last usage of the recipe.
20x clean water cooking.
Clean water consumtion.
Sleep.
X ammount of water cooked to fill up the 2nd gallon jug + what I needed for consumtion at the point of cooking.

Then I went on doing CDDA things.

As far as I understand, the bug is related to a water heater from a basement. See 1st pic. The recipe requirements say something about a water purifier and not about open fire and a pot i.e..

I wanted to craft the charcoal forge and needed pipe. I went to the closest houses to get pipe. I disassembled two water heaters in two basements to get pipe.

After that some time later I wanted to cook clean water. As the 2 gallon jugs where empty again.

# Expected behavior

Open the crafting menu with "&".
Have the recipe "clean water" working as intended.

# Screenshots
Menu "&"
![CDDA Bug 01](https://user-images.githubusercontent.com/42423698/110214926-380dd180-7ea7-11eb-8a39-20a3c3cd195f.jpg)
Base setup for crafting. brazier, water barrel, tile with all needed items in it. Pot, etc.
![CDDA Bug 02](https://user-images.githubusercontent.com/42423698/110214928-393efe80-7ea7-11eb-85d4-59a8766c81d3.jpg)

# Versions and configuration

OS: Wins 7 64
version: Download of the stable version.  Version 0.E-3
Tiles: Ultica (Beta)
ingame language: english
mods loaded: "no fungal monsters", the rest of the config is as downloaded.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
!!! Win 7 professional 64 bit

- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

**Comment by wapcaplet** [comment] 2021-03-06 18:18
There are two different recipes for clean water. One of them uses a purifier, and the other uses heat and boiling. For some reason your recipe list is only showing one of them.

I cannot reproduce the issue in 0.E-3, nor in experimental 0.E-9945-g5960368a33. Is it possible you accidentally pressed `s` on the other recipe, causing it to be hidden? (check your crafting menu, under "HIDDEN" on the first tab)

![image](https://user-images.githubusercontent.com/238395/110216673-9cac3a80-7e6d-11eb-898f-c8d0988f8925.png)

**Comment by Androwski3000** [comment] 2021-03-06 19:17
Thank you @wapcaplet.
You are right. I must have bumbed the s key while fumbling around.  The recipe was under HIDDEN.
That happened twice to me know that I moved something to HIDDEN. The first time I could find it out. But yesterday I was just to tired.

So this is a feature which can cause alot of frustration. Because of the lack of transparency when the feature is activated by accident.  Imagine you are the guy who is new to the game.

Can be closed.

**Comment by wapcaplet** [comment] 2021-03-06 20:53
I agree it is too easy to hide recipes by accident by bumping `s`; you are certainly not the first to be confused by it. Using "h" would be a better mnemonic shortcut, I think. The lowercase `h` is already used as a directional navigation key, but capital `H` is not currently used by this menu, and would be more difficult to press accidentally.

Anyway thank you for reporting and replying. I will close this, and maybe change the shortcut key after the upcoming 0.F release.

**Closed by wapcaplet** 2021-03-06 20:53 UTC
Labels: Crafting / Construction / Recipes, Info / User Interface
