### ISSUE TITLE
Idea: swappable fluid storage tanks

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11870] opened 2015-03-31 19:11 UTC
Currently when I take a water tank out of a vehicle, I get an empty barrel. I'd like a way to install a mount for a swappable tank and then put tanks in and out without losing their contents. Is this feasible? Would it be useful?
##

**Comment by Rivet-the-Zombie** [comment] 2015-03-31 20:34
>Is this feasible?

Anything is doable with enough elbow grease.

>Would it be useful?

Very useful. I'm pretty sure people would fall all over themselves to get at this.

**Comment by Coolthulhu** [comment] 2015-04-02 02:40
> Currently when I take a water tank out of a vehicle, I get an empty barrel.

You mean you lose the water? That's a bug if that happens

**Comment by Leland** [comment] 2017-05-04 20:37
Closing because this bug was never confirmed. Please reopen if it has.

**Closed by Leland** 2017-05-04 20:37 UTC
Labels: Bug, Confirmation Needed, Vehicle
