### ISSUE TITLE
imgGUI error when hovering over skulls involved in milling recipes in item spawn menu

### ISSUE THREAD

**Issue by AudBobb** [CleverRaven/Cataclysm-DDA#77004] opened 2024-10-13 03:38 UTC
### Describe the bug

When in the item spawn menu, and hovering over skulls that have a milling recipe, the game crashes throwing the following error

![image](https://github.com/user-attachments/assets/7fb4fbd1-4966-41c0-bd11-01af385d6fc0)
![image](https://github.com/user-attachments/assets/7b37ee4e-ac6b-49fc-bc3a-7c494d5a7331)
![image](https://github.com/user-attachments/assets/e1ba54bf-f39e-4a14-b972-1d2fc3899edc)

I discovered this when putting together changes involving these skulls, and it's so incredibly specific, that I was *certain* I had just formatted something wrong somewhere, so I reverted my changes, and kept getting the bug, so I just created an entirely new install of the game, and tried again, and the game still crashed when following the same steps, so I'm 99% sure this isn't related to my changes, although I suppose it could be if the game somehow is seeing my original install? I don't know this seems so incredibly, unbelievably coincidentally specific to what I was working on I have a hard time believing I didn't cause it somehow, except that it still is reproducible on a totally fresh install.

### Attach save file

I would include a save, but I don't have one, as the crash is 100% reproducible within 10 seconds of creating a new character, and the save would literally just be me selecting "play now default scenario" on the main menu, saving, and uploading that. If you really want, I can do that but it just seems moot

### Steps to reproduce

1. Install the game
2. Create a new character
3. Open debug menu, and spawn item
4. Search for "skull"
5. Move selector over 'tiny canine skull', 'rabbit skull', 'racoon skull', or any skull that has a milling recipe.
6. Watch the game crash

### Expected behavior

The game doesn't crash

### Versions and configuration

Latest experimental, 2024-10-13-0040

### Additional context

[crash.log](https://github.com/user-attachments/files/17352953/crash.log)
[debug.log](https://github.com/user-attachments/files/17352954/debug.log)

I would include a save, but I don't have one, as the crash is 100% reproducible within 10 seconds of creating a new character, and the save would literally just be me selecting "play now default scenario" on the main menu, saving, and uploading that.

**Comment by AudBobb** [comment] 2024-10-13 03:46
In the first screenshot, the selector is on the llama skull, which does not cause this crash, the crash happens as the selector moves to one of the suspect skulls, but before the screen draws the new frame. Just wanna mention that so no one tries to reproduce by selecting the llama skull.

**Comment by db48x** [comment] 2024-10-21 09:12
This is really an error caused by a recipe, but then it tries to display the error and that’s when there is an ImGui assertion.

```
invalid recipe id "meal_bone_mill_1_1"
```

**Comment by AudBobb** [comment] 2024-10-21 18:00
Ok, if this is an issue in the json I can have a look at it

**Comment by db48x** [comment] 2024-10-21 18:05
Ok. I have an idea about how to fix the ImGui side of the problem, so I’ll leave the skull problem to you.

**Comment by RenechCDDA** [comment] 2024-11-11 19:46
The skull issue is a duplicate of #76334

**Closed by RenechCDDA** 2024-11-11 19:46 UTC
Labels: (S1 - Need confirmation)
