### ISSUE TITLE
Can't reload miscellaneous repair kit

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#71400] opened 2024-02-01 01:21 UTC
### Describe the bug

Can't reload miscellaneous repair kit with naturally generated cardboard roll with duct tape 

### Attach save file

N/A

### Steps to reproduce

1) Spawn miscellaneous repair kit
2) Unload it
3) Throw out duct tape, which you got by unloading miscellaneous repair kit
4) Find naturally naturally generated cardboard roll with duct tape, you can find it at cities houses
5) Try to reload miscellaneous repair kit
6) See, that you can't do it
7) Hug your remora plushy and cry because you can't repair your "long pouty stick kevlar zombie hulk shoggot killer2000"

### Expected behavior

I want to reload miscellaneous repair kit

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 17c277b [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92,2%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by pjf** [comment] 2024-02-01 04:11
Thanks for the report! This looks like a duplicate of confirmed bug #71090 .

**Closed** 2024-02-01 04:43 UTC
Labels: (S1 - Need confirmation)
