### ISSUE TITLE
8x40 HVP ammo has no AP value

### ISSUE THREAD

**Issue by eirikwang** [CleverRaven/Cataclysm-DDA#44586] opened 2020-10-03 18:44 UTC
8x40 AP ammo shows with 0 AP value, while standard caseless ammo shows as 19. 
I think .50 ammo has the same problem

8x40 HVP ammo has no AP value. 

1. Spawn 8x40 caseless
2. Spawn 8x40 HVP
3. compare

# Expected behavior

HVP ammo should have AP value. 

# Screenshots
Screenshot from ammo loaded in RM88 rifle. 

![8x40HVP](https://user-images.githubusercontent.com/124627/94999337-f0fa7800-05b8-11eb-8ffa-a88ce2545fcb.PNG)
![8x40caseless](https://user-images.githubusercontent.com/124627/94999338-f1930e80-05b8-11eb-9c0f-d3db9a6037b6.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-6459-ge49eaa0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Might be same issue as #44159

**Comment by eirikwang** [comment] 2020-10-03 18:49
Caseless json
```
  {
    "id": "8mm_caseless",
    "type": "AMMO",
    "name": { "str_sp": "8x40mm caseless" },
    "//": "Cased ammo tends to be roughly $1/shot, more or less.  Rivtech ammo, being New and Proprietary and Expensive, $2-2.50 or so.",
    "description": "8x40mm caseless rounds.  Proprietary ammunition for Rivtech firearms.  Being caseless rounds, these cannot be disassembled or reloaded.",
    "weight": "12 g",
    "volume": "230 ml",
    "price": 225,
    "price_postapoc": 8000,
    "flags": [ "IRREPLACEABLE_CONSUMABLE" ],
    "material": [ "plastic", "powder" ],
    "symbol": "=",
    "color": "pink",
    "count": 40,
    "stack_size": 40,
    "ammo_type": "8x40mm",
    "range": 42,
    "damage": { "damage_type": "bullet", "amount": 42, "armor_penetration": 18 },
    "dispersion": 75,
    "recoil": 2200,
    "effects": [ "NEVER_MISFIRES" ]
  },
```
HVP json
``` 
{
    "id": "8mm_hvp",
    "copy-from": "8mm_caseless",
    "type": "AMMO",
    "name": { "str": "8x40mm HVP" },
    "description": "8x40mm caseless rounds, saboted high-velocity penetrator type.  Advanced military grade, armor-piercing ammunition that fires a single depleted uranium flechette.  Being caseless rounds, these cannot be disassembled or reloaded.",
    "price": 2500,
    "price_postapoc": 50000,
    "count": 20,
    "relative": { "damage": { "damage_type": "bullet", "amount": 5, "armor_penetration": 20 } }
  }
```

**Comment by eirikwang** [comment] 2020-10-03 19:20
My guess is that there is something with the "relative" code that is off, but I am not familiar enough with c to figure out how += is implemented for ammo. 
(https://github.com/CleverRaven/Cataclysm-DDA/blob/5be394fab800c3839c019a433e9c95b024b149b1/src/assign.h#L60-L74)

**Comment by Relyksboa** [comment] 2020-10-05 18:36
9mm FMJ (24 dam, 0 pierce) also has this issue. making it worse than 9mm JHP (26 dam, 0 pierce) in every situation.

**Comment by anothersimulacrum** [comment] 2020-11-10 16:25
Duplicate of #41564. This is just a UI issue, the values are loaded correctly.

**Closed by anothersimulacrum** 2020-11-10 16:25 UTC
Labels: (S3 - Duplicate)
