### ISSUE TITLE
Exterior walls of building not visible using night vision

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#21873] opened 2017-09-13 17:04 UTC
Game version: 0.C-23902-g0422836

Operating system: Windows 7

Tiles or curses: Tiles - Chesthole32

Mods active:
Disable NPC Needs
Filthy Clothing
Simplified Nutrition
Classes and Scenarios
Folding Parts Pack

### Expected behavior
Exterior wall of building is visible with night vision

### Actual behavior
Exterior wall of building is black

### Steps to reproduce the behavior
Approach a building outside at night with night vision active

![building_dark](https://user-images.githubusercontent.com/5815066/30390414-a978e79e-987b-11e7-9181-fd3bb54e88ec.png)
![build_dark_2](https://user-images.githubusercontent.com/5815066/30390419-acfcfaae-987b-11e7-8072-f9ead650ad62.png)

**Comment by Zireael07** [comment] 2017-09-13 17:05
Does the same thing happen with tiles off?

**Comment by boydkr** [comment] 2017-09-13 17:17
Yes, same behavior:
![building_dark_3](https://user-images.githubusercontent.com/5815066/30390980-7c544a18-987d-11e7-98eb-58ffa1ae4cc8.png)

**Comment by boydkr** [comment] 2017-09-13 17:28
I think there's currently a full moon in my game, it might have something to do with that

**Comment by Coolthulhu** [comment] 2017-09-13 18:47
It's an old bug, it has nothing to do with tiles or full moon.
I've noticed that it doesn't always trigger when the weather is weird: I had it not-happen when it was raining.

**Comment by ZhilkinSerg** [comment] 2017-09-13 19:16
Probably a duplicate of #13786.

**Comment by Leland** [comment] 2017-09-14 14:44
Closing in favor of #13786. @boydkr see if that issue contains all relevant information and please add anything you feel is relevant and missing from it.

**Closed by Leland** 2017-09-14 14:44 UTC
