### ISSUE TITLE
Fuel spent estimation shows incorrect values

### ISSUE THREAD

**Issue by nikow** [CleverRaven/Cataclysm-DDA#45570] opened 2020-11-22 09:33 UTC
When i checked my 1.0 V-twin Engine fuel consumption it was showing that i have 6 weeks until my tank will be empty. 
![Przechwycenie obrazu ekranu_2020-11-22_10-05-48](https://user-images.githubusercontent.com/4789807/99899894-deddb180-2cac-11eb-9482-b8cb60cb7bd7.png)
After sleeping around 12h ( 11:50:08 ) it used 4.1L of gasoline and says there 3 weeks left.
![Przechwycenie obrazu ekranu_2020-11-22_10-08-01](https://user-images.githubusercontent.com/4789807/99899935-12204080-2cad-11eb-8ea0-f6215b3fd49c.png) 
 
So the bug is, that UI shows me that i have fuel for 6 weeks when i really have just 24 hours of fuel in my generator.

# Steps To Reproduce

1. Spawn Quad Bike with full tank of fuel.
2. Turn engine on.
3. Note fuel level.
4. Wait/sleep 12h (using wait or sleep).
5. Note fuel level.

# Expected behavior

I expect more accurate estimation of used resources. It can be incorrect by hour or two, but when it speaks about weeks when there is fuel for a day is a bit of overestimation.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-7759-gf3a1933ee8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by emptytriangle** [comment] 2020-11-27 16:21
From my extensively undocumented testing it seems to think larger engines (turbines etc) are more efficient than smaller engines when that's not the case. It's like it diverges from truth more the more fuel-hungry the engine is, like there's a backwards operation.

**Comment by irwiss** [comment] 2022-09-16 22:24
Can't reproduce, probably fixed by #59297

**Closed** 2022-09-17 09:39 UTC
Labels: <Bug>, Info / User Interface, Vehicles
