### ISSUE TITLE
DinoMod eggs can't be used in recipes.

### ISSUE THREAD

**Issue by RocketPapaya413** [CleverRaven/Cataclysm-DDA#42054] opened 2020-07-12 07:21 UTC
# Describe the bug

![need my eggs](https://user-images.githubusercontent.com/50273494/87241058-d44d0a80-c3e4-11ea-98b3-b3546e8bcc96.png)

# Expected behavior

Remember the giant dinosaur egg omelette from Neopets? I want that in my tummy.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3964-g237b16e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    Cars to Wrecks [cars_to_wrecks],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

# Additional context

The simplest way to make this an option is to simply make a new "eggs_bird" list in a new cooking_components.json in the dinomod folder, similar to how it's done in Magiclysm. HOWEVER I believe this might lead to a mod conflict and prevent someone from being able to make both and Owlbear AND a Deinonychus omelette in the same game. If possible I would seek to prevent this dark, appalling future from coming to pass. If there's an elegant way to combine the two lists that would work but I don't know the systems at play that well, personally.

**Comment by Maleclypse** [comment] 2020-07-13 05:42
I believe you can extend item groups like "eggs_bird" in mods by simply listing the id and then listing the items being added to the list.

**Comment by LyleSY** [comment] 2020-07-26 13:37
This was one of the early goals of the current epoch of DinoMod and was intended to be resolved by #40141 by adding egg_dino to a bunch of egg recipes, but it may be that that is only working for the generic egg_dinos you gather in the bushes. I believe this can be fixed just in JSON if someone wants to take a more comprehensive approach, I'm guessing a dino egg group that includes all the dino eggs in the mod. Once that list exists it should be easy enough to maintain as we get more dinos.

**Closed** 2020-07-31 06:58 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Good First Issue, Mods: Dinoclysm, [JSON]
