### ISSUE TITLE
segmentation fault in mapgen

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#30347] opened 2019-05-09 17:34 UTC
**Describe the bug**  
Was walking down the street when I got a segmentation fault, seems to be related to a vehicle.json but I didn't review the bug report too intensively.

**To Reproduce**  
Walk around generating new vehicle spawns, one or more cause errors (segmentation fault)

**Expected behavior**  
Unseen vehicles generate in reality bubble normally and do not crash the game.

**Screenshots**  
N/A, this happened when wandering around fairly normal part of city center.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 x64
 - Game Version: 0.D-2721-gdb0746e
 - Graphics version: Tiles
 - Mods loaded:  dda, no_npc_food, aftershock, Tolerate_This, craftgp, FIC_Weapons, realguns, growable-pots, ew_pack, makeshift, Medieval_Stuff, More_Survival_Tools, nw_pack, modular_turrets, Salvaged_Robots, hydroponics, MMA, mapgen_demo, more_locations, deoxymod, blazemod, Tanks, No_Zeds, No_Fungi, No_Explosive_Zombies, No_Big_Zombies, No_Bees, No_Anthills, No_Aftershock_Zeds, No_Acid_Zombies, Mundane_Zombies, more_classes_scenarios, manualbionicinstall, no_reviving_zombies, safeautodoc, StatsThroughSkills

Note: No_zeds and No_aftershock_Zeds are mods I created to remove zeds and aftershock zeds from spawning. (going for NPC and cthulu horror fighting only)

**Additional context**  
here is the debug log file for the aforementioned session:

10:19:26.733 : Starting log.
10:19:26.733 INFO : Cataclysm DDA version 0.D-2721-gdb0746e
10:19:26.742 INFO : Number of render drivers on your system: 4
10:19:26.742 INFO : Render driver: 0/direct3d
10:19:26.742 INFO : Render driver: 1/direct3d11
10:19:26.742 INFO : Render driver: 2/opengl
10:19:26.742 INFO : Render driver: 3/software
10:19:26.745 INFO : Language is set to: 'en'
10:19:27.179 INFO : SDL version used during compile is 2.0.5
10:19:27.179 INFO : SDL version used during linking and in runtime is 2.0.5
10:19:27.224 INFO : Active renderer: 0/direct3d
10:19:27.421 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
10:19:27.566 WARNING : opendir [./mods/] failed with "No such file or directory".
10:20:47.352 ERROR : (error message will follow backtrace)
	(@0x5788de[cataclysm-tiles.exe+0x1788de]), 
	(@0x578eca[cataclysm-tiles.exe+0x178eca]), 
	(@0x4ff219[cataclysm-tiles.exe+0xff219]), 
	(@0x5071b4[cataclysm-tiles.exe+0x1071b4]), 
	(@0x789241[cataclysm-tiles.exe+0x389241]), 
	(@0x78c365[cataclysm-tiles.exe+0x38c365]), 
	(@0x6eab81[cataclysm-tiles.exe+0x2eab81]), 
	(@0x6ed74d[cataclysm-tiles.exe+0x2ed74d]), 
	(@0x6ede16[cataclysm-tiles.exe+0x2ede16]), 
	(@0x65c694[cataclysm-tiles.exe+0x25c694]), 
	(@0x65e956[cataclysm-tiles.exe+0x25e956]), 
	(@0x6867c5[cataclysm-tiles.exe+0x2867c5]), 
	(@0x847ddf[cataclysm-tiles.exe+0x447ddf]), 
	(@0x8493ba[cataclysm-tiles.exe+0x4493ba]), 
	(IMG_LoadWEBP_RW+0x4fce4f@0x144158f[cataclysm-tiles.exe+0x104158f]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x773559cd[kernel32.dll+0x159cd]), 
	(RtlUserThreadStart+0x21@0x7748a2e1[ntdll.dll+0x2a2e1]), 
Backtrace emission took 0 seconds.
couldn't parse color: c_orange
10:20:47.352 ERROR : couldn't parse color: c_orange
10:20:47.353 ERROR : couldn't parse color: c_gray
10:20:47.366 ERROR : couldn't parse color: c_gray
10:20:47.366 ERROR : couldn't parse color: c_gray
10:20:47.367 ERROR : couldn't parse color: c_gray
10:20:47.367 ERROR : couldn't parse color: c_gray
10:20:47.581 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
10:20:47.581 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
10:20:48.026 WARNING : opendir [./save/Unalaska/mods] failed with "No such file or directory".
10:26:00.832 INFO : npc::set_omt_destination - new goal for NPC [Justin 'Hooter' Huston] with [need_none] is [s_grocery] in [54,164,0].
10:58:17.942 INFO : npc::set_omt_destination - new goal for NPC [Gaylord Andersen] with [need_none] is [s_gun] in [87,149,0].
10:58:39.341 INFO : npc::set_omt_destination - new goal for NPC [Matthew 'Shaky' Ladd] with [need_none] is [s_liquor] in [92,149,0].
10:59:21.521 INFO : npc::set_omt_destination - new goal for NPC [John Ennion] with [need_ammo] is [house] in [77,162,0].
12:18:52.560 INFO : npc::set_omt_destination - new goal for NPC [Adelle Mark] with [need_ammo] is [house] in [87,161,0].
12:20:54.075 INFO : npc::set_omt_destination - new goal for NPC [Adelle Mark] with [need_ammo] is [mil_surplus] in [83,158,0].
12:24:15.168 INFO : npc::set_omt_destination - new goal for NPC [Rodger Okeefe] with [need_none] is [s_liquor] in [96,155,0].
12:26:33.330 ERROR : (error message will follow backtrace)
	(@0x5788de[cataclysm-tiles.exe+0x1788de]), 
	(@0x578eca[cataclysm-tiles.exe+0x178eca]), 
	(@0x579b46[cataclysm-tiles.exe+0x179b46]), 
	(@0x8b6d91[cataclysm-tiles.exe+0x4b6d91]), 
	(@0xd35a29[cataclysm-tiles.exe+0x935a29]), 
	(@0xd35dea[cataclysm-tiles.exe+0x935dea]), 
	(@0xd366c0[cataclysm-tiles.exe+0x9366c0]), 
	(@0xd36e23[cataclysm-tiles.exe+0x936e23]), 
	(@0xd3721d[cataclysm-tiles.exe+0x93721d]), 
	(@0xd377eb[cataclysm-tiles.exe+0x9377eb]), 
	(@0x86591c[cataclysm-tiles.exe+0x46591c]), 
	(@0x8737f2[cataclysm-tiles.exe+0x4737f2]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x873802[cataclysm-tiles.exe+0x473802]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8752ce[cataclysm-tiles.exe+0x4752ce]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x873802[cataclysm-tiles.exe+0x473802]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8752ce[cataclysm-tiles.exe+0x4752ce]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x873802[cataclysm-tiles.exe+0x473802]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x873802[cataclysm-tiles.exe+0x473802]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872ab8[cataclysm-tiles.exe+0x472ab8]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8752ce[cataclysm-tiles.exe+0x4752ce]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8752ce[cataclysm-tiles.exe+0x4752ce]), 
	(@0x872a48[cataclysm-tiles.exe+0x472a48]), 
	(@0x8737c7[cataclysm-tiles.exe+0x4737c7]), 
	(@0x874b7f[cataclysm-tiles.exe+0x474b7f]), 
	(@0x8753fd[cataclysm-tiles.exe+0x4753fd]), 
Backtrace emission took 0 seconds.
src/mapgen.cpp:7131 [vehicle* map::add_vehicle(const vproto_id&, const tripoint&, int, int, int, bool)] Out of bounds add_vehicle t=none d=90 p=1882,3689,0

**Comment by OptimisticNihlist** [comment] 2019-05-09 17:35
[World save Unalaska.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3163306/World.save.Unalaska.zip)
I have also added the world save for viewing. I saved a few minutes earlier and then traveled north towards the city center.

**Comment by OptimisticNihlist** [comment] 2019-05-09 17:44
Update: I was able to make this bug happen again when moving north past a minefield towards city center and then west. Reloading the save and then moving west first, then north did not cause a crash.

**Comment by AMurkin** [comment] 2019-05-09 18:12
Duplicate of the #28156.

**Closed** 2019-05-09 18:40 UTC
Labels: (S3 - Duplicate), <Crash / Freeze>, Mapgen, Vehicles
