### ISSUE TITLE
ncurses Y/N prompts not rendering

### ISSUE THREAD

**Issue by SandwichPie** [CleverRaven/Cataclysm-DDA#75802] opened 2024-08-18 16:24 UTC
### Describe the bug

In the curses version of the game, every tested Y/N prompt fails to render any text. The prompt still fuctions as normal besides that. All that is rendered is a single colour gray rectangle where the prompt should be.

### Attach save file

N/A

### Steps to reproduce

The quickest broken prompt to get to is probably trying to cancel creating a new world.

### Expected behavior

The text should be a distinct colour from the background it is printed on.

### Screenshots

![2024-08-18-170950_654x374_scrot](https://github.com/user-attachments/assets/e8dd24da-cba9-4210-aae2-cf132aa7cd20)

### Versions and configuration

Version: cdda-linux-curses-x64-2024-08-17-1809

### Additional context

This bug persists for other people I have asked to check, different machines and terminal emulators suggesting it isn't a problem with the terminal configuration.

**Comment by ZhilkinSerg** [comment] 2024-08-23 12:29
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/75362

**Closed by ZhilkinSerg** 2024-08-23 12:29 UTC
Labels: (S3 - Duplicate), Info / User Interface, ImGui, curses
