### ISSUE TITLE
Search bar/text displays behind debug windows and are thus practically invisible

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#77719] opened 2024-11-10 06:52 UTC
### Describe the bug

Search bars for debug menus are behind the windows for said menus, and thus are practically invisible.

### Attach save file

N/A

### Steps to reproduce

1. Open up a menu for spawning, changing character stuff, etc.
2. Try to use the search function

### Expected behavior

I expect the search function to display properly when used.

### Screenshots

This is a demonstration of the search bar being behind a smaller menu.

![image](https://github.com/user-attachments/assets/a09a54db-60af-44d8-9f5e-7656c425ab6b)

This is what shows when attempting to use the search bar for larger menus, such as the one for spawning items.

![image](https://github.com/user-attachments/assets/4320bd01-11e7-4450-9946-6a04e820f86b)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: cdda-experimental-2024-11-09-2132 af98298 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    Railroads [railroads],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by harakka** [comment] 2024-11-10 08:15
Duplicate of #75676

**Closed by harakka** 2024-11-10 08:15 UTC
Labels: (S1 - Need confirmation)
