### ISSUE TITLE
Be able to workout in the gym equipment to be more healthy.

### ISSUE THREAD

**Issue by rafaelkb** [CleverRaven/Cataclysm-DDA#45375] opened 2020-11-13 00:06 UTC
Obviously the player would need to be extremely tired after the workout.

**Comment by Xaleth** [comment] 2020-11-15 17:28
that should depend on your stamina and strength and how hydrated you are along with many factors. 

Yes if u choose the XXL trait that should make one super tired after working out--that makes sense. Don't know about XXS tho

**Comment by Entity-y** [comment] 2020-11-15 19:32
Over time working out with equipment should increase strength and athletics skill, additionally the workout action that's already in the game should eventually raise stats. Maybe multiple rank proficiency could be dedicated to athletics, when you reach 100% you get a +1 to strength and the next level is unlocked, have it cap out at 5 levels or something for balance.

**Comment by dchieh222** [comment] 2020-11-17 20:23
Related to #44370

**Comment by anothersimulacrum** [comment] 2020-11-17 22:55
This issue offers little enough extra that I'm going to say it's duplicate.
Duplicate of #44370

**Closed by anothersimulacrum** 2020-11-17 22:55 UTC
Labels: (S3 - Duplicate), <Suggestion / Discussion>, Mechanics: Character / Player
