### ISSUE TITLE
"Traces of bionics" in regular zombies during butchering

### ISSUE THREAD

**Issue by Buuua** [CleverRaven/Cataclysm-DDA#30166] opened 2019-05-01 20:25 UTC
**Describe the bug**  
While dismembering any zombie corpses game gives incorrect message about character destroying bionics inside. Dissecting corpses yelds no bionics at all.

**To Reproduce**  
1. Kill a zombie
2. Dismember corpse
3. Get incorrect log message

**Expected behavior**  
No mention of bionics.

**Screenshots**  
https://imgur.com/H411TmT

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: D-2484-g2cac958 (Build #8883 )
 - Graphics version: Cresthole
 - Mods loaded: disable npc needs, makeshift items, medieval items, survival tools, alt map key, Fuji's more buildings, mutant npcs, vehicle additions pack, cresthole indicators, simplified nutrition, stats through skills revised

**Comment by MrHrulgin** [comment] 2019-05-01 21:04
Duplicate of #29936

**Closed** 2019-05-01 21:15 UTC
