### ISSUE TITLE
Segmentation fault;  forbidden map area

### ISSUE THREAD

**Issue by settdigger** [CleverRaven/Cataclysm-DDA#27615] opened 2019-01-14 17:38 UTC
Game version: 0.C-36428-g9802051

Operating system: win10

Tiles or curses: Tiles

Mods active: Modular turrets, boats

### Expected behavior

certain areas of the map become traps that trigger a crash.  Restarting with a new map doesn't seem to help;  a similar crash always re-emerges, choosing some location, 40 tiles wide or so, that you cannot enter. (close to my base, usually)

### Steps to reproduce the behavior

CRASH LOG FILE: config/crash.log
VERSION: 0.C-36428-g9802051
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CD6A5[cataclysm-tiles.exe+0x1CD6A5]
    @0x5CE252[cataclysm-tiles.exe+0x1CE252]
    SMPEG_error+0x4B034@0xE666D0[cataclysm-tiles.exe+0xA666D0]
    _C_specific_handler+0x98@0x7FFD40407C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFD4253F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFD424AD856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFD4253E70E[ntdll.dll+0x9E70E]
    @0xD6E56B[cataclysm-tiles.exe+0x96E56B]
    @0xD6F9AE[cataclysm-tiles.exe+0x96F9AE]
    @0x8B49BE[cataclysm-tiles.exe+0x4B49BE]
    @0x6F4668[cataclysm-tiles.exe+0x2F4668]
    IMG_LoadWEBP_RW+0x4CC7C9@0x1445599[cataclysm-tiles.exe+0x1045599]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFD40E93034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFD42513691[ntdll.dll+0x73691]

**Comment by ZhilkinSerg** [comment] 2019-01-14 17:48
Duplicate of #27600.

**Closed by ZhilkinSerg** 2019-01-14 17:48 UTC
Labels: (S3 - Duplicate)
