### ISSUE TITLE
Pixel minimap ignores config setting, always renders

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#14998] opened 2016-01-24 16:33 UTC

**Comment by chaosvolt** [comment] 2016-01-25 05:05
Derp. Have you tested disabling it, saving the settings, then doing a save/load test?

**Comment by DanmakuDan** [comment] 2016-01-25 16:14
In the meantime, you can use N to toggle the minimap visibility.

**Comment by codemime** [comment] 2016-02-21 18:55
According to the description it's an intended behavior: "If true, shows the pixel-detail minimap in game after the save is loaded. Use the 'Toggle Pixel Minimap' action key to change its visibility during gameplay.". We could either rename it to something like "Start with Pixel Minimap" or change the behavior.

**Comment by Leland** [comment] 2017-05-04 03:45
Discussion's been stalled on this for over a year. Closing.

**Closed by Leland** 2017-05-04 03:45 UTC
Labels: Enhancement
