### ISSUE TITLE
Crash after trying to unload vehicle

### ISSUE THREAD

**Issue by MXSteel** [CleverRaven/Cataclysm-DDA#36468] opened 2019-12-26 15:46 UTC
# Describe the bug

First of all, I think the context is important - I have removed a part and installed a part (storage box) on the attached vehicle WHILE it was attached - so, this might be the reason for the crash.   
The problem is in the title - trying to unload my bike crashes the game.

# Steps To Reproduce

Steps to reproduce the behavior (SPECULATIVE - didn't have time to try):
1. Make a vehicle with a bike rack (5 tiles- to match my conditions)
2. Load bike (5 tile long, too) with a part installed (for example, Box).
3. Uninstall above part, then install it (or, to match my conditions - a new part with the same ID) 
4. Try to unload the vehicle

# Expected behavior
The bike to unload

# Versions and configuration

For some reason I cannot generate those.
**OS**: Windows 7, 
**Main Game Version**: 0.D,

# Crash log

```
CRASH LOG FILE: config/crash.log
VERSION: 0.D
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x54BF20[cataclysm-tiles.exe+0x14BF20]
    @0x54C2C1[cataclysm-tiles.exe+0x14C2C1]
    SMPEG_error+0x3DAF3@0xB9F3F5[cataclysm-tiles.exe+0x79F3F5]
    @0x6FFC9D3
    GetProfileStringW+0x12DDF@0x755C03BB[kernel32.dll+0x503BB]
    RtlKnownExceptionFilter+0xB7@0x773C5B57[ntdll.dll+0x75B57]
    RtlInitializeExceptionChain+0x36@0x773898C5[ntdll.dll+0x398C5]
```

**Comment by MXSteel** [comment] 2019-12-26 23:43
# Solution  

Alright, so after digging in the save JSON, I found that the specific vehicle part was saved as:  

{"id":"box","base":{"typeid":"frame","bday":5132,"invlet":125,"damaged":676,"item_tags":["VEHICLE"]},"mount_dx":-5,"mount_dy":-2,"open":false,"direction":0,"blood":0,"enabled":false,"flags":0,"passenger_id":0,"crew_id":-1,"items":[],"ammo_pref":"null"}

while it should have been saved as 

{"id":"box","base":{"typeid":"frame","bday":5132,"invlet":125,"damaged":676,"item_tags":["VEHICLE"]},"mount_dx":-5,"mount_dy":-2,"open":false,"direction":0,"blood":0,"enabled":false,"flags":4,"carry": ["  -1  0Motorcycle"],"passenger_id":0,"crew_id":-1,"items":[],"ammo_pref":"null"}

Editing it to the 2nd value works.  

I'm leaving this issue open, so whoever handles the code can add a check so that installing a part to an attached vehicle doesn't count as installing it on the main vehicle (which is what causes this problem).  
Once this is fixed, feel free to close this ~~ticket~~ issue.

**Comment by davidpwbrown** [comment] 2019-12-30 12:42
Cannot reproduce on latest master on Linux, I get this message in the message log : 

" "A part of the vehicle ('%s') has no containing vehicle's name.  It will be detached from the %s vehicle.""

But curiously, the box dosnt detach, and the game dosnt crash.  This is related to the fix for https://github.com/CleverRaven/Cataclysm-DDA/issues/28712 

Are you playing latest experimental? or perhaps a version that is older than that issue?

**Comment by esotericist** [comment] 2020-01-03 18:41
@MXSteel 
Given the "For some reason I cannot generate those." comment, were you on 0.D stable instead of experimental?

**Comment by davidpwbrown** [comment] 2020-01-03 20:05
Can reproduce on 0.D stable, but cannot reproduce on current experimental, fixes arent backported, so closing.

**Closed by davidpwbrown** 2020-01-03 20:05 UTC
Labels: <Bug>, Crafting / Construction / Recipes, Vehicles, [C++]

**Comment by davidpwbrown** [comment] 2020-01-03 20:06
@MXSteel  if you can reproduce this on current experimental, feel free to reopen.
