### ISSUE TITLE
"Missing Mandatory Member "initiate" error when loading pre-PR 8973 saves/worlds

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#30516] opened 2019-05-14 18:32 UTC
# Describe the bug
 DEBUG    : Error: data/mods//dda/../../json/obsolete_martial_arts.json: line 6:155: missing mandatory member "initiate"

    "id": "style_centipede",
    "name": "Centipede Kung Fu",
    "description": "One of the Five Deadly Venoms.  Centipede Style uses an onslaught of rapid strikes.  Each attack you land increases your speed by 4.",
                                                                                                                                                          
    "arm_block": 3,
    "leg_block": 99,
    "onhit_buffs": [
 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 708

# Versions and configuration

 - OS: WIn 10-64bit
 - Game Version: 0.D-2935-g4da9158
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "crazy_cataclysm",
  "mutant_npcs",
  "boats",
  "deoxymod",
  "blazemod",
  "DP_XOTTO_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_AMAZING_CHEST_INDICATORS",
  "necromancy",
  "no_religious_Texts",
  "manualbionicinstall",
  "more_classes_scenarios",
  "RL_Classes",
  "sleepdeprivation",
  "StatsThroughSkills"

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3179139/config.zip)
[Mutant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3179141/Mutant.zip)

- note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

**Comment by ejseto** [comment] 2019-05-14 21:15
You have an unofficial file that contains the old "venom" martial arts but hasn't been updated with the new field. There is no "obsolete_martial_arts.json" file in the repo. You can either delete that file or reinstall the game.

**Comment by ifreund** [comment] 2019-05-14 21:24
Closing, as the problem is cause by unofficial modding

**Closed by ifreund** 2019-05-14 21:24 UTC
