### ISSUE TITLE
Hub0 mission 2 - mind splicer not putting neural data on data card

### ISSUE THREAD

**Issue by redwing0** [CleverRaven/Cataclysm-DDA#41613] opened 2020-06-26 20:55 UTC
# Describe the bug

Can't complete Hub0 second mission, because the mind splicer kit isn't putting the neural data from the corpse onto the data card. 

# Steps To Reproduce

Find hub0, complete first mission, receive second mission, debug yourself a desiccated corpse and use the mind splicer on it.
The data card remains a "data card" item after, not "data card with neural data". 

You can't turn in the mission with the unchanged card. 

# Expected behavior

"data card" item becomes "data card with neural data" 

# Screenshots

# Versions and configuration

16:54:00.632 : Starting log.
16:54:00.632 INFO : Cataclysm DDA version 0.E-3531-gff1ff7ea9f
16:54:00.639 INFO : [main] C locale set to en_US.UTF-8
16:54:00.639 INFO : [main] C++ locale set to en_US.UTF-8
16:54:00.642 INFO : [options] C locale set to en_US.UTF-8
16:54:00.642 INFO : [options] C++ locale set to en_US.UTF-8
16:54:00.718 WARNING : opendir [./mods/] failed with "No such file or directory".
16:54:04.026 WARNING : opendir [./save/testworld/mods] failed with "No such file or directory".
16:54:11.814 :  GAME REPORT:
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-3531-gff1ff7ea9f [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

16:54:19.947 : Log shutdown.

**Comment by anothersimulacrum** [comment] 2020-06-26 22:20
Duplicate of #41226

**Closed by anothersimulacrum** 2020-06-26 22:20 UTC
