### ISSUE TITLE
Mansions are too easy to break in 

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#18271] opened 2016-09-11 08:53 UTC
Mansions provide a multitude of very useful loot, including: guns, unperishable food, as many books as you're ever going to need, tools and more. 

Yet, breaking in into a mansion is fairly easy because 
a) it is usually in a really remote spot, so all the enemies you will face are the ones spawned in the mansion which are not that many and no exceptionally dangerous zombies.
b) its large layout and you can simply walk up to the side windows and smash them in without trouble.

Since the remote position is intended there are three solutions that come to mind to fix the effort/reward balance for mansions:
1. Increase monster spawns. Ideally thematically fitting ones, but there are hardly any that are mansion-specific. (Perhaps zombie dogs/rottweilers?)
2. Reduce item spawns (this is a rather clunky way of handling the issue)
3. Add mansion specific security measures, like alarm systems that alerts all zombies nearby, a large fence around the building, perhaps even small "turret" system that fires at unauthorized people. 
   Someone on the forums mentioned robotic butlers, that are still walking around the abandoned mansions, I like that. 

(For now, 1. is probably the easiest to do, although some original features for mansions would be nice, imho)

**Comment by shedya** [comment] 2016-09-11 09:04
I think the third option would be thematically fitting, but turret systems should be uncommon — something like 1/3 chance of them being generated.

**Comment by John-Candlebury** [comment] 2016-09-11 13:43
I dont know if its a big problem. 

I think its alright to keep locations that early survivors and new players can easily loot.

**Comment by Coolthulhu** [comment] 2016-09-11 13:46
It would be cool if mansions were generated partly looted and devastated.
They're currently giant easy mode, with safe access to tons of great books and sometimes medieval weaponry.

**Comment by BorkBorkGoesTheCode** [comment] 2016-09-11 17:34
> It would be cool if mansions were generated partly looted and devastated.
 They're currently giant easy mode, with safe access to tons of great books and sometimes medieval weaponry.


What if the game checked the time elapsed from world gen and spawned damaged buildings as the world grows older?

**Comment by Zireael07** [comment] 2016-09-11 18:41
> What if the game checked the time elapsed from world gen and spawned damaged buildings as the world grows older?

I believe this has been suggested already, but a PR for building/region overlays has fallen through and never gotten completed. I can't even recall the submitter, only that damaged/ruined/overgrown buildings were some of the ideas bandied about.

**Comment by WizardOfOoo** [comment] 2016-09-11 19:18
I agree, mansions should have a little more challenge. I like the dog idea and the 1/3 chance of a turret.

Maybe a chance to spawn a zombie in plate armor?  (the mansion owner)

**Comment by DangerNoodle** [comment] 2016-09-11 19:57
Are you playing without special zombies? I have encountered necromancers and zombie masters in mansions before, when not using the Mundane Zombies blacklist mod. That alone deters me in most early-game attempts to raid a mansion.

**Comment by DaliTimelord** [comment] 2016-09-11 20:23
I've raided mansions before too. They do seriously lack a challenge component relative to the amount of loot you can get.

**Comment by DangerNoodle** [comment] 2016-09-11 21:58
True. While they can be hectic if a master starts upgrading the less hazardous zombies, overall it might be interesting to add some additional threat.

The problem is that robotic defenses would logically be hostile to the zombies, and thus reduce the overall threat level due to infighting. So ideally, we would want an additional threat that would not be negated by infighting, while still being present with mundane zombies on. Otherwise the threat is increased only when special zombies are retained.

**Comment by DangerNoodle** [comment] 2016-09-11 22:02
I had an idea, actually. What about adding rooms for housing exotic animals to the list of rooms generated in a mansion, and adding zombified wildlife to them? The occasional room with a zombie bear, cougar, or wolf would add a new variety of threat, while having a minor impact on overall loot due to introducing a new room type.

**Comment by Snaaty** [comment] 2016-09-12 10:35
I like the idea with the zombified exotic animals. It even is an excuse to add more exotic one like ocelots or elephants :)

Yeah maybe robotic defense isn't the way to go here due to the infighting. 

In my last two mansions I encountered only regular, fat and crawling zombies. Maybe I was exceptionally lucky. That was with monster spawn at 1.3 or so and item spawn reduced to 0.65.

**Comment by DangerNoodle** [comment] 2016-09-12 16:05
Additional zombie animals might be interesting, though even adding suitable existing ones will be interesting. A shark tank or pool (lasers not included) might be an interesting excuse to make use of the otherwise rare zombe shark.

**Comment by Treah** [comment] 2016-09-12 17:38
This could be wrapped into existing issue #18188

**Comment by WizardOfOoo** [comment] 2016-09-12 17:44
We could make mansions like hospitals, spitter zombies.

**Comment by Coolthulhu** [comment] 2016-09-12 17:56
About infighting: we could create a new faction - mansion zombie. Those would be friendly with mansion bots, since bots recognize them.
The problem would be implementing mapgen factions, so that we wouldn't need to add new zed variants.
Alternatively we could just handwave it by saying that all zeds near mansions are known to bots.

It would be thematic to have some guaranteed high level zombies of the leader variety - necros or masters (necros preferred, since masters are broken).

**Comment by Zilenan91** [comment] 2016-09-12 23:47
Masters would be ridiculous in mansions. Mansions are big and on purely static spawns there's many many basic zombies walking through its halls. Masters would make them pretty much impenetrable unless the player is almost at endgame armor and weapons. The best defense for them would likely be barbed wire fences and eyebots loitering outside the perimeter rather than dedicated security bots so that there's a possibility of mansions being approachable to characters not in the endgame.

**Comment by DangerNoodle** [comment] 2016-09-13 00:11
I have seen masters randomly in masters though. They do make the mansion hectic, but not unassailable. Definitely not good for early game.

Some new type of zombie might be fitting, but I think that exotic zombie pets and basic security lke eyebots might be a good combination.

**Comment by Leland** [comment] 2017-05-24 14:37
Discussion's been stalled on this one for 8 months now – closing. If there's still interest, feel free to ping me here to reopen. Or feel free to open a new issue, either way works.

**Closed by Leland** 2017-05-24 14:37 UTC
Labels: Balance, Suggestion (Discuss)
