### ISSUE TITLE
Power Armor Drains UPS while deactivated

### ISSUE THREAD

**Issue by UnmitigatedDisaster** [CleverRaven/Cataclysm-DDA#36114] opened 2019-12-14 20:27 UTC
(First Bug report!  Let me know if I did anything wrong! 😃 )

Game version:  0.D-10195-g72dbda8 (tiles)

Operating system: Windows 10 Pro 10.0.18362

Tiles or curses: Tiles

Mods active:  Dark Days Ahead/ Disable NPC Needs

### Expected behavior 
Equipped Power armor can be activated to eliminate encumbrance and drain UPS charges.  It can also be set to deactivated to restore encumbrance and save UPS battery.  

### Actual behavior
Power Armor drains UPS constantly regardless of whether active or not.   Spammed by 'Your Power Armor disengages." messages whenever set to 'deactivated'.  

### Steps to reproduce the behavior
Create new world with character.  Spawn in Light Power Armor, UPS, heavy disposable battery

Equip Light Power armor, reload UPS with battery and place in inventory.  Attempt to active and deactivate and observe the behavior noted above.

**Comment by arijust** [comment] 2019-12-15 22:25
Duplicate of #35885

**Closed** 2019-12-27 09:01 UTC
