### ISSUE TITLE
Segmentation fault when switching firing modes in a vehicle using multiple turrets

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35434] opened 2019-11-10 00:40 UTC
# Describe the bug

Game crashes when pressing s to switch firing mode (semi-auto to auto) while targeting a turret in a vehicle with multiple turrets

# Steps To Reproduce

1. Load attatched save
2. press e,5,v,T,1,s (in other words, aim the avalange turret and when it targets something, press s to switch firing modes
3. observe crash

# Expected behavior
Switch firing mode of the avalange rifle from semi auto to auto

# Screenshots
![image](https://user-images.githubusercontent.com/50166150/68536905-b7929b80-035a-11ea-883b-fa63d0363e39.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9280-g86b3adc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]
win8.1

# Additional context
[crash-and-debug-log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3827936/crash-and-debug-log.zip)

save file:
https://ufile.io/lrp60s7y

**Comment by joe9000** [comment] 2019-11-10 03:47
i also had this behavior, but after uninstalling all of my turrets, installing one chassis/turret/control unit and switching it to automatic targeting, i was able to install additional turrets and set them to automatic without causing the crash

**Comment by sdp0et** [comment] 2019-11-10 03:50
I've had this problem for a few days and was able to fix it today (so I'm not sure if it's really fixed or just reset things and may happen again).  I have a vehicle with two pulse laser turrets.  When they were installed both could be toggled between manual and automatic targeting.  At some point I noticed one had switched to manual without me doing it.  Trying to change it to automatic causes the crash.  The other can be toggled normally.  

I tried removing both turret control systems and reinstalling, which didn't work.  I then removed the pulse lasers.  The first one I removed was one that had been damaged before and been repaired.  When I repaired it, it didn't go back to the normal display of "|| pulse laser", though.  The health indicator was replaced with the question-mark-in-a-box character.  They were displayed identically when examining the vehicle and in the menu to toggle targeting modes, so I can't be sure if that was the one causing the crash.  But since that happened to be the one I removed first, I reinstalled it and was able to set both to automatic without issue.  I didn't bother with the other since the problem didn't recur. 

I'm not sure if the damage/repair thing had anything to do with causing the issue, but you never know. I'm also not sure if installation order mattered (weapon after turret control unit vs before).  Maybe just uninstalling and reinstalling the weapon reset something. 

![cdda_weapon_health](https://user-images.githubusercontent.com/5922308/68538478-a5086a00-033a-11ea-89a3-18630849d91a.jpg)

**Comment by sdp0et** [comment] 2019-11-10 03:54
I meant to ask: How do you get isometric-ish the view in the screenshot?

**Comment by Night-Pryanik** [comment] 2019-11-10 03:58
I guess this is a duplicate of #34831.

**Comment by snipercup** [comment] 2019-11-10 04:05
> 
> 
> I guess this is a duplicate of #34831.

I'm not sure, my symptom is different. I can set the firing mode to auto or semi-auto using the menus. But if I try to aim and press s to swithch firing modes, it crashes.

**Comment by sdp0et** [comment] 2019-11-10 04:10
Follow up for me: I just had another crash.  I noticed I my turrets weren't firing.  Both had reverted to manual mode.  I was able to change one to automatic again, but crashed on the second.

I also noticed just now that the issue is about firing mode and I've been talking about targeting mode.  Should that be a separate issue?

**Comment by GGgatherer** [comment] 2019-11-13 13:23
I don't event have a TCU, just 2 manually-targeted turrets(M249 and M60) but when I try switching firing mode on any of them I get segfault. It was NOT happening when both my turrets were M249, but I actually used only one of them, another one was not loaded. So not sure if the reason is 2 different turrets or 2 loaded turrets. Maybe will check later.
0.D-9345-g7df9a89

**Comment by yowshi** [comment] 2019-11-19 08:58
turret 4 on this vehicle is experiencing this issue. every time I switch the targeting mode the game crashes
[Equestria.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3862835/Equestria.zip)

**Comment by xrogaan** [comment] 2019-12-11 05:43
I believe I experienced this bug too, trying to switch firing mode manually, but the stacktrace seems different. I only have one turret on the vehicle.  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3948634/crash.log)

**Closed** 2019-12-16 22:26 UTC
Labels: <Crash / Freeze>, Ranged, Vehicles
