### ISSUE TITLE
When cutting down trees, impact may create holes going to lower Z-level

### ISSUE THREAD

**Issue by mkikt4743** [CleverRaven/Cataclysm-DDA#35031] opened 2019-10-26 00:06 UTC
# Describe the bug

When cutting down trees, occasionally holes may form leading to a lower z-level where they land. When the save is reloaded, these holes are replaced by floors of the material below them, and if there was open air below, a flat roof.

# Steps To Reproduce

1. Cut down a few trees (I did so with a wood axe)
2. See holes leading to lower z-level

# Expected behavior

Trees should not be powerful enough to break earth.

# Screenshots

![Tree_digger](https://user-images.githubusercontent.com/56452763/67610732-b0686c80-f762-11e9-8ce6-429a62d80310.PNG)
![underground](https://user-images.githubusercontent.com/56452763/67610736-b6f6e400-f762-11e9-9c14-65b2e892a71c.PNG)

# Versions and configuration

Experimental build #9797

# Additional notes

If at all relevant, I have the Roadheader's Mining Vehicles Mod enabled.

**Comment by int-ua** [comment] 2019-10-26 00:51
Duplicate of #14117 / #34940

**Closed** 2019-10-26 10:55 UTC
