### ISSUE TITLE
Ballistic glass has 0 cover

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#51643] opened 2021-09-15 13:34 UTC
### Describe the bug

Ballistic glass has 0 cover, which allows projectiles to freely pass through. Despite that, it's impassable.

### Steps To Reproduce

1. Approach a robot who's on the other side of ballistic glass.
2. Get shot.

### Expected behavior

Ballistic glass should have high coverage, like other impassable tiles.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f153ada [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Glass walls have 90% cover
Closed frosted glass doors also have 0% cover, and would also probably have this issue
Windows with curtains and without curtains have 60% cover
Windows with closed curtains have 95% cover

**Comment by anothersimulacrum** [comment] 2021-09-15 13:42
Cover has nothing to do with ballistics.
https://github.com/CleverRaven/Cataclysm-DDA/issues/33374

**Comment by Maleclypse** [comment] 2021-09-15 19:30
What kind of bullet was passing through the glass and how much damage did it lose?

**Comment by dranitski** [comment] 2021-09-15 21:43
@Maleclypse this is definitely a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33374

**Comment by Maleclypse** [comment] 2021-09-15 23:00
> @Maleclypse this is definitely a duplicate of #33374

I appreciate that but I’m more interested in the question of if there’s been a regression in ballistic glass since the damage reduction for furniture/terrain was implemented.

**Closed** 2021-12-05 06:41 UTC
Labels: (S1 - Need confirmation), Fields / Furniture / Terrain / Traps
