### ISSUE TITLE
Npcs not moving

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27161] opened 2018-12-18 13:53 UTC
Bandits, Raiders and Thugs inside the Raider Apartment aren't going towards me, or even hitting me when i'm next to them, Random npcs functions as normal.

I'm in build 8308 tiles.

**Comment by Inglonias** [comment] 2018-12-18 17:05
Duplicate of #27016

**Closed** 2018-12-18 17:31 UTC
