### ISSUE TITLE
Custom colors break vehicle screen

### ISSUE THREAD

**Issue by gastamper** [CleverRaven/Cataclysm-DDA#49260] opened 2021-06-11 13:27 UTC
# Describe the bug
Setting custom colors for light_gray, at least, break the vehicle screen.

# Steps To Reproduce
1. Set a custom color for light_gray, such as white.
2. Open the vehicle screen

# Expected behavior
Vehicle screen should respect custom colors rather than showing internals such as color_dark_gray in their place.

# Screenshots
Attached.

# Versions and configuration
Cataclysm-DDA experimental build 2021-06-11-0543
Windows 10
Retro tiles
English
No NPC needs is only mod
![brokencolors](https://user-images.githubusercontent.com/20960555/121693550-41ef3400-ca97-11eb-8ed1-e28af5541c1f.PNG)

**Comment by ZhilkinSerg** [comment] 2021-06-14 19:58
Please send contents of your `config` folder, namely `custom_colors.json` and `options.json`

**Comment by gastamper** [comment] 2021-07-06 13:34
custom_colors.json:
```[{"name":"c_dark_gray","custom":"c_white","invertcustom":""},{"name":"c_blue","custom":"c_cyan","invertcustom":""}]```
options.json
```[
  { "info": "Set a default character name that will be used instead of a random name on character creation.", "default": "Default: ", "name": "DEF_CHAR_NAME", "value": "Hans Luecker" },
  { "info": "Enable item auto pickup.  Change pickup rules with the Auto Pickup Manager.", "default": "Default: False", "name": "AUTO_PICKUP", "value": "false" },
  { "info": "If true, will enable to pickup items one tile around to the player.  You can assign No Auto Pickup zones with the Zones Manager 'Y' key for e.g.  your homebase.", "default": "Default: False", "name": "AUTO_PICKUP_ADJACENT", "value": "true" },
  { "info": "Auto pickup items with weight less than or equal to [option] * 50 grams.  You must also set the small items option.  '0' disables this option", "default": "Default: 0 - Min: 0, Max: 20", "name": "AUTO_PICKUP_WEIGHT_LIMIT", "value": "0" },
  { "info": "Auto pickup items with volume less than or equal to [option] * 50 milliliters.  You must also set the light items option.  '0' disables this option", "default": "Default: 0 - Min: 0, Max: 20", "name": "AUTO_PICKUP_VOL_LIMIT", "value": "0" },
  { "info": "Auto pickup is disabled as long as you can see monsters nearby.  This is affected by 'Safe Mode proximity distance'.", "default": "Default: False", "name": "AUTO_PICKUP_SAFEMODE", "value": "true" },
  { "info": "If false, you will not see messages about items, you step on, within no auto pickup zones.", "default": "Default: True", "name": "NO_AUTO_PICKUP_ZONES_LIST_ITEMS", "value": "true" },
  { "info": "If true, enables configured auto features below.  Disabled as long as any enemy monster is seen.", "default": "Default: False", "name": "AUTO_FEATURES", "value": "true" },
  { "info": "Action to perform when 'Auto pulp or butcher' is enabled.  Pulp: Pulp corpses you stand on.  - Pulp Adjacent: Also pulp corpses adjacent from you.  - Butcher: Butcher corpses you stand on.", "default": "Default: off - Values: off, pulp, pulp_zombie_only, pulp_adjacent, pulp_adjacent_zombie_only, butcher", "name": "AUTO_PULP_BUTCHER", "value": "pulp" },
  { "info": "If true, enables automatic use of wielded pickaxes and jackhammers whenever trying to move into mineable terrain.", "default": "Default: False", "name": "AUTO_MINING", "value": "false" },
  { "info": "Action to perform when 'Auto foraging' is enabled.  Bushes: Only forage bushes.  - Trees: Only forage trees.  - Everything: Forage bushes, trees, and everything else including flowers, cattails etc.", "default": "Default: off - Values: off, bushes, trees, both", "name": "AUTO_FORAGING", "value": "off" },
  { "info": "If false, will cause player to drop new items that cause them to exceed the weight limit.", "default": "Default: False", "name": "DANGEROUS_PICKUPS", "value": "false" },
  { "info": "Always: You will be prompted to move onto dangerous tiles.  Running: You will only be able to move onto dangerous tiles while running and will be prompted.  Crouching: You will only be able to move onto a dangerous tile while crouching and will be prompted.  Never:  You will not be able to move onto a dangerous tile unless running and will not be warned or prompted.", "default": "Default: ALWAYS - Values: ALWAYS, RUNNING, CROUCHING, NEVER", "name": "DANGEROUS_TERRAIN_WARNING_PROMPT", "value": "ALWAYS" },
  { "info": "If true, will hold the game and display a warning if a hostile monster/npc is approaching.", "default": "Default: True", "name": "SAFEMODE", "value": "true" },
  { "info": "If safe mode is enabled, distance to hostiles at which safe mode should show a warning.  0 = Max player view distance.  This option only has effect when no safe mode rule is specified.  Otherwise, edit the default rule in Safe Mode Manager instead of this value.", "default": "Default: 0 - Min: 0, Max: 60", "name": "SAFEMODEPROXIMITY", "value": "0" },
  { "info": "When true, safe mode will alert you of hostiles while you are driving a vehicle.", "default": "Default: False", "name": "SAFEMODEVEH", "value": "false" },
  { "info": "If true, safe mode will automatically reactivate after a certain number of turns.  See option 'Turns to auto reactivate safe mode.'", "default": "Default: False", "name": "AUTOSAFEMODE", "value": "false" },
  { "info": "Number of turns after which safe mode is reactivated.  Will only reactivate if no hostiles are in 'Safe mode proximity distance.'", "default": "Default: 50 - Min: 1, Max: 600", "name": "AUTOSAFEMODETURNS", "value": "50" },
  { "info": "Number of turns an ignored monster stays ignored after it is no longer seen.  0 disables this option and monsters are permanently ignored.", "default": "Default: 200 - Min: 0, Max: 3600", "name": "SAFEMODEIGNORETURNS", "value": "200" },
  { "info": "If enabled, monsters will take periodic gameplay turns.  This value is the delay between each turn, in seconds.  Works best with Safe Mode disabled.  0 = disabled.", "default": "Default: 0.00 - Min: 0.00, Max: 10.00", "name": "TURN_DURATION", "value": "0.00" },
  { "info": "If true, game will periodically save the map.  Autosaves occur based on in-game turns or real-time minutes, whichever is larger.", "default": "Default: True", "name": "AUTOSAVE", "value": "true" },
  { "info": "Number of game turns between autosaves", "default": "Default: 50 - Min: 10, Max: 1000", "name": "AUTOSAVE_TURNS", "value": "50" },
  { "info": "Number of real time minutes between autosaves", "default": "Default: 5 - Min: 0, Max: 127", "name": "AUTOSAVE_MINUTES", "value": "5" },
  { "info": "If true, automatically sets notes", "default": "Default: False", "name": "AUTO_NOTES", "value": "true" },
  { "info": "If true, automatically sets notes on places that have stairs that go up or down", "default": "Default: False", "name": "AUTO_NOTES_STAIRS", "value": "true" },
  { "info": "If true, automatically sets notes on places that contain various map extras", "default": "Default: False", "name": "AUTO_NOTES_MAP_EXTRAS", "value": "false" },
  { "info": "If true, the game will calculate range in a realistic way: light sources will be circles, diagonal movement will cover more ground and take longer.  If disabled, everything is square: moving to the northwest corner of a building takes as long as moving to the north wall.", "default": "Default: True", "name": "CIRCLEDIST", "value": "true" },
  { "info": "Set to drop empty containers after use.  No: Don't drop any.  - Watertight: All except watertight containers.  - All: Drop all containers.", "default": "Default: no - Values: no, watertight, all", "name": "DROP_EMPTY", "value": "no" },
  { "info": "Always: Always start deathcam.  Ask: Query upon death.  Never: Never show deathcam.", "default": "Default: ask - Values: always, ask, never", "name": "DEATHCAM", "value": "ask" },
  { "info": "If true, music and sound are enabled.", "default": "Default: True", "name": "SOUND_ENABLED", "value": "false" },
  { "info": "Choose the soundpack you want to use.  Requires restart.", "default": "Default: basic - Values: basic", "name": "SOUNDPACKS", "value": "basic" },
  { "info": "Adjust the volume of the music being played in the background.", "default": "Default: 100 - Min: 0, Max: 128", "name": "MUSIC_VOLUME", "value": "100" },
  { "info": "Adjust the volume of sound effects being played by the game.", "default": "Default: 100 - Min: 0, Max: 128", "name": "SOUND_EFFECT_VOLUME", "value": "100" },
  { "info": "Adjust the volume of ambient sounds being played by the game.", "default": "Default: 100 - Min: 0, Max: 128", "name": "AMBIENT_SOUND_VOLUME", "value": "100" },
  { "info": "Switch Language.", "default": "Default:  - Values: en, ar, cs, da, de, el, es_AR, es_ES, fr, hu, id, is, it_IT, ja, ko, nb, nl, pl, pt_BR, ru, sr, tr, uk_UA, zh_CN, zh_TW", "name": "USE_LANG", "value": "" },
  { "info": "Switch between Celsius, Fahrenheit and Kelvin.", "default": "Default: fahrenheit - Values: fahrenheit, celsius, kelvin", "name": "USE_CELSIUS", "value": "fahrenheit" },
  { "info": "Switch between mph, km/h and tiles/turn.", "default": "Default: mph - Values: mph, km/h, t/t", "name": "USE_METRIC_SPEEDS", "value": "mph" },
  { "info": "Switch between kg and lbs.", "default": "Default: lbs - Values: lbs, kg", "name": "USE_METRIC_WEIGHTS", "value": "lbs" },
  { "info": "Switch between the Cup ( c ), Liter ( L ) or Quart ( qt ).", "default": "Default: l - Values: c, l, qt", "name": "VOLUME_UNITS", "value": "l" },
  { "info": "Metric or Imperial", "default": "Default: imperial - Values: metric, imperial", "name": "DISTANCE_UNITS", "value": "imperial" },
  { "info": "12h: AM/PM, e.g. 7:31 AM - Military: 24h Military, e.g. 0731 - 24h: Normal 24h, e.g. 7:31", "default": "Default: 12h - Values: 12h, military, 24h", "name": "24_HOUR", "value": "12h" },
  { "info": "Use key code or symbol input on SDL.  Symbol is recommended for non-qwerty layouts since currently the default keybindings for key code mode only supports qwerty.  Key code is currently WIP and bypasses IMEs, caps lock, and num lock.", "default": "Default: keychar - Values: keychar, keycode", "name": "SDL_KEYBOARD_MODE", "value": "keychar" },
  { "info": "If true, prompts such as Y/N queries only accepts capital or modified letters, while lower case and unmodified letters only snap the cursor to the corresponding option.", "default": "Default: True", "name": "FORCE_CAPITAL_YN", "value": "true" },
  { "info": "If true, automatically follow the crosshair when firing/throwing.", "default": "Default: False", "name": "SNAP_TO_TARGET", "value": "false" },
  { "info": "If true, will query before disassembling items while butchering.", "default": "Default: True", "name": "QUERY_DISASSEMBLE", "value": "true" },
  { "info": "If true, will query before removing a keybinding from a hotkey.", "default": "Default: True", "name": "QUERY_KEYBIND_REMOVAL", "value": "true" },
  { "info": "If true, will close the advanced inventory when the move all items command is used.", "default": "Default: False", "name": "CLOSE_ADV_INV", "value": "false" },
  { "info": "Open default advanced inventory layout instead of last opened layout", "default": "Default: False", "name": "OPEN_DEFAULT_ADV_INV", "value": "false" },
  { "info": "If true, actions ( like \"Read\", \"Smoke\", \"Wrap tighter\" ) will be displayed next to the corresponding items.", "default": "Default: True", "name": "INV_USE_ACTION_NAMES", "value": "true" },
  { "info": "If true, directional actions ( like \"Examine\", \"Open\", \"Pickup\" ) will autoselect an adjacent tile if there is exactly one valid target.", "default": "Default: True", "name": "AUTOSELECT_SINGLE_VALID_TARGET", "value": "true" },
  { "info": "Highlight selected item's contents and parent container in inventory screen.  \"Symbol\" shows a highlighted caret and \"Highlight\" uses font highlighting.", "default": "Default: symbol - Values: symbol, highlight, disable", "name": "INVENTORY_HIGHLIGHT", "value": "symbol" },
  { "info": "Allows diagonal movement with cursor keys using CTRL and SHIFT modifiers.  Diagonal movement action keys are taken from keybindings, so you need these to be configured.", "default": "Default: none - Values: none, mode1, mode2, mode3", "name": "DIAG_MOVE_WITH_MODIFIERS_MODE", "value": "none" },
  { "info": "If true, vehicle parts will change color if they are armor plated", "default": "Default: True", "name": "VEHICLE_ARMOR_COLOR", "value": "true" },
  { "info": "If true, view will automatically shift towards the driving direction", "default": "Default: True", "name": "DRIVING_VIEW_OFFSET", "value": "true" },
  { "info": "If true, when controlling a vehicle, a white 'X' ( in curses version ) or a crosshair ( in tiles version ) at distance 10 from the center will display its current facing.", "default": "Default: True", "name": "VEHICLE_DIR_INDICATOR", "value": "true" },
  { "info": "If true, when driving a vehicle in reverse, steering should also reverse like real life.", "default": "Default: False", "name": "REVERSE_STEERING", "value": "false" },
  { "info": "Switch between sidebar on the left or on the right side.  Requires restart.", "default": "Default: right - Values: left, right", "name": "SIDEBAR_POSITION", "value": "right" },
  { "info": "If true, adds an extra space between sidebar panels.", "default": "Default: False", "name": "SIDEBAR_SPACERS", "value": "false" },
  { "info": "Where new log messages should show.", "default": "Default: new_bottom - Values: new_top, new_bottom", "name": "LOG_FLOW", "value": "new_bottom" },
  { "info": "Number of turns after which a message will be removed from the sidebar log.  '0' disables this option.", "default": "Default: 0 - Min: 0, Max: 1000", "name": "MESSAGE_TTL", "value": "0" },
  { "info": "Number of turns during which similar messages are hidden.  '0' disables this option.", "default": "Default: 0 - Min: 0, Max: 1000", "name": "MESSAGE_COOLDOWN", "value": "0" },
  { "info": "Number of messages to preserve in the history, and when saving.", "default": "Default: 255 - Min: 1, Max: 10000", "name": "MESSAGE_LIMIT", "value": "255" },
  { "info": "If true, pressing a key with no set function will not display a notice in the chat log.", "default": "Default: False", "name": "NO_UNKNOWN_COMMAND_MSG", "value": "false" },
  { "info": "Whether to trigger a popup window when completing an achievement.  First: when completing an achievement that has not been completed in a previous game.", "default": "Default: first - Values: never, always, first", "name": "ACHIEVEMENT_COMPLETED_POPUP", "value": "first" },
  { "info": "Switch between look around panel being left or right.", "default": "Default: right - Values: left, right", "name": "LOOKAROUND_POSITION", "value": "right" },
  { "info": "Switch between pickup panel being left, right, or overlapping the sidebar.", "default": "Default: left - Values: left, right, overlapping", "name": "PICKUP_POSITION", "value": "left" },
  { "info": "How should confidence and steadiness be communicated to the player.", "default": "Default: bars - Values: numbers, bars", "name": "ACCURACY_DISPLAY", "value": "bars" },
  { "info": "Morale display style in sidebar.", "default": "Default: vertical - Values: vertical, horizontal", "name": "MORALE_STYLE", "value": "vertical" },
  { "info": "If true, Advanced Inventory Manager menu will fit full screen, otherwise it will leave sidebar visible.", "default": "Default: False", "name": "AIM_WIDTH", "value": "false" },
  { "info": "Move view by how many squares per keypress.", "default": "Default: 1 - Min: 1, Max: 50", "name": "MOVE_VIEW_OFFSET", "value": "1" },
  { "info": "With Fast Scroll option enabled, shift view on the overmap and while looking around by this many squares per keypress.", "default": "Default: 5 - Min: 1, Max: 50", "name": "FAST_SCROLL_OFFSET", "value": "5" },
  { "info": "If true, menus will start scrolling in the center of the list, and keep the list centered.", "default": "Default: True", "name": "MENU_SCROLL", "value": "true" },
  { "info": "Centered or to edge, shift the view toward the selected item if it is outside of your current viewport.", "default": "Default: centered - Values: false, centered, edge", "name": "SHIFT_LIST_ITEM_VIEW", "value": "centered" },
  { "info": "Enabled: automatically assign letters to any carried items that lack them.  Disabled: do not auto-assign letters.  Favorites: only auto-assign letters to favorited items.", "default": "Default: favorites - Values: disabled, enabled, favorites", "name": "AUTO_INV_ASSIGN", "value": "favorites" },
  { "info": "If true, show item health bars instead of reinforced, scratched etc. text.", "default": "Default: True", "name": "ITEM_HEALTH_BAR", "value": "true" },
  { "info": "If true, show item symbols in inventory and pick up menu.", "default": "Default: False", "name": "ITEM_SYMBOLS", "value": "false" },
  { "info": "If true, the default ammo is added to weapon and magazine names.  For example \"Mosin-Nagant M44 (4/5)\" becomes \"Mosin-Nagant M44 (4/5 7.62x54mm)\".", "default": "Default: True", "name": "AMMO_IN_NAMES", "value": "true" },
  { "info": "Enable input from joystick.", "default": "Default: True", "name": "ENABLE_JOYSTICK", "value": "true" },
  { "info": "Show: Cursor is always shown.  Hide: Cursor is hidden.  HideKB: Cursor is hidden on keyboard input and unhidden on mouse movement.", "default": "Default: show - Values: show, hide, hidekb", "name": "HIDE_CURSOR", "value": "show" },
  { "info": "Edge scrolling with the mouse.", "default": "Default: Normal", "name": "EDGE_SCROLL", "value": "30" },
  { "info": "If true, will display enabled animations.", "default": "Default: True", "name": "ANIMATIONS", "value": "true" },
  { "info": "If true, will display weather animations.", "default": "Default: True", "name": "ANIMATION_RAIN", "value": "true" },
  { "info": "If true, will display animations for projectiles like bullets, arrows, and thrown items.", "default": "Default: True", "name": "ANIMATION_PROJECTILES", "value": "true" },
  { "info": "If true, will display scrolling combat text animations.", "default": "Default: True", "name": "ANIMATION_SCT", "value": "true" },
  { "info": "If true, will display scrolling combat text with Unicode font.", "default": "Default: True", "name": "ANIMATION_SCT_USE_FONT", "value": "true" },
  { "info": "The amount of time to pause between animation frames in ms.", "default": "Default: 10 - Min: 0, Max: 100", "name": "ANIMATION_DELAY", "value": "10" },
  { "info": "If true, forces the game to redraw at least once per turn.", "default": "Default: True", "name": "FORCE_REDRAW", "value": "true" },
  { "info": "If true, the title screen will use the art appropriate for the season.", "default": "Default: True", "name": "SEASONAL_TITLE", "value": "true" },
  { "info": "Set the probability of the alternate title screen appearing.", "default": "Default: 10 - Min: 0, Max: 100", "name": "ALT_TITLE", "value": "10" },
  { "info": "Set the size of the terminal along the X axis.", "default": "Default: 80 - Min: 80, Max: 960", "name": "TERMINAL_X", "value": "256" },
  { "info": "Set the size of the terminal along the Y axis.", "default": "Default: 24 - Min: 24, Max: 270", "name": "TERMINAL_Y", "value": "72" },
  { "info": "If true, fonts will look better.", "default": "Default: False", "name": "FONT_BLENDING", "value": "true" },
  { "info": "Set the font width.  Requires restart.", "default": "Default: 8 - Min: 8, Max: 100", "name": "FONT_WIDTH", "value": "8" },
  { "info": "Set the font height.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "FONT_HEIGHT", "value": "16" },
  { "info": "Set the font size.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "FONT_SIZE", "value": "16" },
  { "info": "Set the map font width.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "MAP_FONT_WIDTH", "value": "16" },
  { "info": "Set the map font height.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "MAP_FONT_HEIGHT", "value": "16" },
  { "info": "Set the map font size.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "MAP_FONT_SIZE", "value": "16" },
  { "info": "Set the overmap font width.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "OVERMAP_FONT_WIDTH", "value": "16" },
  { "info": "Set the overmap font height.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "OVERMAP_FONT_HEIGHT", "value": "16" },
  { "info": "Set the overmap font size.  Requires restart.", "default": "Default: 16 - Min: 8, Max: 100", "name": "OVERMAP_FONT_SIZE", "value": "16" },
  { "info": "Use SDL ASCII line drawing routine instead of Unicode Line Drawing characters.  Use this option when your selected font doesn't contain necessary glyphs.", "default": "Default: True", "name": "USE_DRAW_ASCII_LINES_ROUTINE", "value": "true" },
  { "info": "When available item and monster description will show a picture of the object in ascii art.", "default": "Default: True", "name": "ENABLE_ASCII_ART", "value": "true" },
  { "info": "If true, replaces some TTF rendered text with tiles.", "default": "Default: True", "name": "USE_TILES", "value": "true" },
  { "info": "Choose the tileset you want to use.", "default": "Default: UltimateCataclysm - Values: ASCIITiles, brownlikebears, ChestHole16, Chibi_Ultica, Cuteclysm(Alpha), HitButton_iso, hoder, MshockXottoplus, neodays, retrodays, UltimateCataclysm", "name": "TILES", "value": "retrodays" },
  { "info": "Specified the overlay in which the memory map is drawn.  Requires restart.  For custom overlay define gamma and RGB values for dark and light colors.", "default": "Default: color_pixel_sepia_light - Values: color_pixel_darken, color_pixel_sepia_light, color_pixel_sepia_dark, color_pixel_blue_dark, color_pixel_custom", "name": "MEMORY_MAP_MODE", "value": "color_pixel_sepia_light" },
  { "info": "Specify RGB value for color RED for dark color overlay.", "default": "Default: 39 - Min: 0, Max: 255", "name": "MEMORY_RGB_DARK_RED", "value": "39" },
  { "info": "Specify RGB value for color GREEN for dark color overlay.", "default": "Default: 23 - Min: 0, Max: 255", "name": "MEMORY_RGB_DARK_GREEN", "value": "23" },
  { "info": "Specify RGB value for color BLUE for dark color overlay.", "default": "Default: 19 - Min: 0, Max: 255", "name": "MEMORY_RGB_DARK_BLUE", "value": "19" },
  { "info": "Specify RGB value for color RED for bright color overlay.", "default": "Default: 241 - Min: 0, Max: 255", "name": "MEMORY_RGB_BRIGHT_RED", "value": "241" },
  { "info": "Specify RGB value for color GREEN for bright color overlay.", "default": "Default: 220 - Min: 0, Max: 255", "name": "MEMORY_RGB_BRIGHT_GREEN", "value": "220" },
  { "info": "Specify RGB value for color BLUE for bright color overlay.", "default": "Default: 163 - Min: 0, Max: 255", "name": "MEMORY_RGB_BRIGHT_BLUE", "value": "163" },
  { "info": "Specify gamma value for overlay.", "default": "Default: 1.60 - Min: 1.00, Max: 3.00", "name": "MEMORY_GAMMA", "value": "1.60" },
  { "info": "If true, shows the pixel-detail minimap in game after the save is loaded.  Use the 'Toggle Pixel Minimap' action key to change its visibility during gameplay.", "default": "Default: True", "name": "PIXEL_MINIMAP", "value": "true" },
  { "info": "Specified the mode in which the minimap drawn.", "default": "Default: dots - Values: solid, squares, dots", "name": "PIXEL_MINIMAP_MODE", "value": "dots" },
  { "info": "Overall brightness of pixel-detail minimap.", "default": "Default: 100 - Min: 10, Max: 300", "name": "PIXEL_MINIMAP_BRIGHTNESS", "value": "100" },
  { "info": "Height of pixel-detail minimap, measured in terminal rows.  Set to 0 for default spacing.", "default": "Default: 0 - Min: 0, Max: 100", "name": "PIXEL_MINIMAP_HEIGHT", "value": "0" },
  { "info": "Scale pixel minimap to fit its surroundings.  May produce crappy results, especially in modes other than \"Solid\".", "default": "Default: False", "name": "PIXEL_MINIMAP_SCALE_TO_FIT", "value": "false" },
  { "info": "Preserves the square shape of tiles shown on the pixel minimap.", "default": "Default: True", "name": "PIXEL_MINIMAP_RATIO", "value": "true" },
  { "info": "Controls how big the creature beacons are.  Value is in minimap tiles.", "default": "Default: 2 - Min: 1, Max: 4", "name": "PIXEL_MINIMAP_BEACON_SIZE", "value": "2" },
  { "info": "Controls how fast the hostile creature beacons blink on the pixel minimap.  Value is multiplied by 200 ms.  Set to 0 to disable.", "default": "Default: 10 - Min: 0, Max: 50", "name": "PIXEL_MINIMAP_BLINK", "value": "10" },
  { "info": "Sets which video display will be used to show the game.  Requires restart.", "default": "Default: 0 - Values: 0, 1", "name": "DISPLAY", "value": "0" },
  { "info": "Starts Cataclysm in one of the fullscreen modes.  Requires restart.", "default": "Default: windowedbl - Values: no, maximized, fullscreen, windowedbl", "name": "FULLSCREEN", "value": "windowedbl" },
  { "info": "Set which renderer to use.  Requires restart.", "default": "Default: direct3d - Values: direct3d, direct3d11, opengl, opengles2, software", "name": "RENDERER", "value": "direct3d11" },
  { "info": "Use render batching for 2D render API to make it more efficient.  Requires restart.", "default": "Default: True", "name": "RENDER_BATCHING", "value": "true" },
  { "info": "Use hardware acceleration for the framebuffer when using software rendering.  Requires restart.", "default": "Default: False", "name": "FRAMEBUFFER_ACCEL", "value": "false" },
  { "info": "If true, tries to use color modulated textures to speed-up ASCII drawing.  Requires restart.", "default": "Default: False", "name": "USE_COLOR_MODULATED_TEXTURES", "value": "true" },
  { "info": "Sets the scaling mode, 'none' ( default ) displays at the game's native resolution, 'nearest'  uses low-quality but fast scaling, and 'linear' provides high-quality scaling.", "default": "Default: none - Values: none, nearest, linear", "name": "SCALING_MODE", "value": "none" },
  { "info": "Factor by which to scale the display.  Requires restart.", "default": "Default: 1 - Values: 1, 2, 4", "name": "SCALING_FACTOR", "value": "1" },
  { "info": "Handling of game world when last character dies.", "default": "Default: reset - Values: reset, delete, query, keep", "name": "WORLD_END", "value": "reset" },
  { "info": "A number determining how large cities are.  A higher number means larger cities.  0 disables cities, roads and any scenario requiring a city start.", "default": "Default: 8 - Min: 0, Max: 16", "name": "CITY_SIZE", "value": "8" },
  { "info": "A number determining how far apart cities are.  A higher number means cities are further apart.  Warning, small numbers lead to very slow mapgen.", "default": "Default: 4 - Min: 0, Max: 8", "name": "CITY_SPACING", "value": "4" },
  { "info": "A scaling factor that determines density of monster spawns.  A higher number means more monsters.", "default": "Default: 1.00 - Min: 0.00, Max: 50.00", "name": "SPAWN_DENSITY", "value": "1.00" },
  { "info": "A scaling factor that determines density of item spawns.  A higher number means more items.", "default": "Default: 1.00 - Min: 0.01, Max: 10.00", "name": "ITEM_SPAWNRATE", "value": "1.00" },
  { "info": "Baseline average number of days between random NPC spawns.  Average duration goes up with the number of NPCs already spawned.  A higher number means fewer NPCs.  Set to 0 days to disable random NPCs.", "default": "Default: 4.00 - Min: 0.00, Max: 100.00", "name": "NPC_SPAWNTIME", "value": "4.00" },
  { "info": "A scaling factor that determines the time between monster upgrades.  A higher number means slower evolution.  Set to 0.00 to turn off monster upgrades.", "default": "Default: 4.00 - Min: 0.00, Max: 100.00", "name": "MONSTER_UPGRADE_FACTOR", "value": "4.00" },
  { "info": "Determines the movement rate of monsters.  A higher value increases monster speed and a lower reduces it.  Requires world reset.", "default": "Default: 100 - Min: 1, Max: 1000", "name": "MONSTER_SPEED", "value": "100%" },
  { "info": "Determines how much damage monsters can take.  A higher value makes monsters more resilient and a lower makes them more flimsy.  Requires world reset.", "default": "Default: 100 - Min: 1, Max: 1000", "name": "MONSTER_RESILIENCE", "value": "100%" },
  { "info": "( WIP feature ) Determines terrain, shops, plants, and more.", "default": "Default: default - Values: default, desert_test", "name": "DEFAULT_REGION", "value": "default" },
  { "info": "Initial starting time of day on character generation.", "default": "Default: 8 - Min: 0, Max: 23", "name": "INITIAL_TIME", "value": "8" },
  { "info": "How many days into the year the cataclysm occurred.  Day 0 is Spring 1.  Day -1 randomizes the start date.  Can be overridden by scenarios.  This does not advance food rot or monster evolution.", "default": "Default: 60 - Min: -1, Max: 999", "name": "INITIAL_DAY", "value": "60" },
  { "info": "How many days after the cataclysm the player spawns.  Day 0 is the day of the cataclysm.  Can be overridden by scenarios.  Increasing this will cause food rot and monster evolution to advance.", "default": "Default: 0 - Min: 0, Max: 9999", "name": "SPAWN_DELAY", "value": "0" },
  { "info": "Season length, in days.  Warning: Very little other than the duration of seasons scales with this value, so adjusting it may cause nonsensical results.", "default": "Default: 91 - Min: 14, Max: 127", "name": "SEASON_LENGTH", "value": "91" },
  { "info": "Sets the time of construction in percents.  '50' is two times faster than default, '200' is two times longer.  '0' automatically scales construction time to match the world's season length.", "default": "Default: 100 - Min: 0, Max: 1000", "name": "CONSTRUCTION_SCALING", "value": "100" },
  { "info": "Keep the initial season for ever.", "default": "Default: False", "name": "ETERNAL_SEASON", "value": "false" },
  { "info": "Emulation of zombie hordes.  Zombies can group together into hordes, which can wander around cities and will sometimes move towards noise.  Note: the current implementation does not properly respect obstacles, so hordes can appear to walk through walls under some circumstances.  Must reset world directory after changing for it to take effect.", "default": "Default: False", "name": "WANDER_SPAWNS", "value": "false" },
  { "info": "If true, spawn zombies at shelters.  Makes the starting game a lot harder.", "default": "Default: False", "name": "BLACK_ROAD", "value": "false" },
  { "info": "If true, radiation causes the player to mutate.", "default": "Default: True", "name": "RAD_MUTATION", "value": "true" },
  { "info": "Allowed point pools for character generation.", "default": "Default: any - Values: any, multi_pool, no_freeform", "name": "CHARACTER_POINT_POOLS", "value": "any" },
  { "info": "Determines the scope, which is known in the beginning of the game.", "default": "Default: 15 - Min: 3, Max: 20", "name": "DISTANCE_INITIAL_VISIBILITY", "value": "15" },
  { "info": "Initial points available to spend on stats on character generation.", "default": "Default: 6 - Min: 0, Max: 1000", "name": "INITIAL_STAT_POINTS", "value": "6" },
  { "info": "Initial points available to spend on traits on character generation.", "default": "Default: 0 - Min: 0, Max: 1000", "name": "INITIAL_TRAIT_POINTS", "value": "0" },
  { "info": "Initial points available to spend on skills on character generation.", "default": "Default: 2 - Min: 0, Max: 1000", "name": "INITIAL_SKILL_POINTS", "value": "2" },
  { "info": "Maximum trait points available for character generation.", "default": "Default: 12 - Min: 0, Max: 1000", "name": "MAX_TRAIT_POINTS", "value": "12" },
  { "info": "Scales experience gained from practicing skills and reading books.  0.5 is half as fast as default, 2.0 is twice as fast, 0.0 disables skill training except for NPC training.", "default": "Default: 1.00 - Min: 0.00, Max: 100.00", "name": "SKILL_TRAINING_SPEED", "value": "1.00" },
  { "info": "Set the level of skill rust.  Vanilla: Vanilla Cataclysm - Capped: Capped at skill levels 2 - Int: Intelligence dependent - IntCap: Intelligence dependent, capped - Off: None at all.", "default": "Default: off - Values: vanilla, capped, int, intcap, off", "name": "SKILL_RUST", "value": "off" },
  { "info": "If false, vision is limited to current z-level.  If true and the world is in z-level mode, the vision will extend beyond current z-level.  Currently very bugged!", "default": "Default: False", "name": "FOV_3D", "value": "false" },
  { "info": "How many levels up and down the experimental 3D field of vision reaches.  (This many levels up, this many levels down.)  3D vision of the full height of the world can slow the game down a lot.  Seeing fewer Z-levels is faster.", "default": "Default: 4 - Min: 0, Max: 21", "name": "FOV_3D_Z_RANGE", "value": "4" },
  { "info": "If true, file path names are going to be transcoded from system encoding to UTF-8 when reading and will be transcoded back when writing.  Mainly for CJK Windows users.", "default": "Default: True", "name": "ENCODING_CONV", "value": "true" }
]```

**Comment by kevingranade** [comment] 2022-12-06 00:29
Yea this looks like a real problem, looking at this search https://github.com/CleverRaven/Cataclysm-DDA/search?l=C%2B%2B&q=color_light_gray
You can see places that use the raw color string instead of the macro that does color mapping. (E.g. c_light_gray)

**Comment by Night-Pryanik** [comment] 2024-11-10 10:22
Changing both light gray and dark gray to custom colors didn't break anything on vehicle screen on latest experimental as of 10 November 2024.
![изображение](https://github.com/user-attachments/assets/197cd831-5fe1-46c4-9df2-e8c9d95da44f)
Closing until reconfirmed.

**Closed by Night-Pryanik** 2024-11-10 10:22 UTC
Labels: Info / User Interface, (S2 - Confirmed), Vehicles
