### ISSUE TITLE
Case sensitive search for Cyrillic chars

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#32999] opened 2019-08-07 12:05 UTC
# Describe the bug

When search item with latin chars - its case insensitive, but when use Cyrillic chars - its case sensitive. For example for search in '&' or '*' menu: "Katana" == "katana" if 'K' is latin, but "Катана" != "катана" because in this case 'K' is Cyrillic.

# Expected behavior

I think this is bug, because expect same (case insensitive) behavior for Cyrillic (and others) chars as for latin. This is important because often the same objects in different places are called with a capital and with a small letter (maybe due to inconsistent translation).

# Screenshots
Katana == katana
<img width="1280" alt="Katana" src="https://user-images.githubusercontent.com/38557723/62621341-4dfe8d80-b924-11e9-8e8a-7b0f1b865974.png">
Катана != катана
<img width="1280" alt="Катана" src="https://user-images.githubusercontent.com/38557723/62621365-5a82e600-b924-11e9-855c-4da861ffc988.png">

# Versions and configuration
build 9424
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G87; 
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, -attitude [sees_player_less_attitude],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment] 2019-08-07 12:24
Duplicate of #21566.

**Closed by Night-Pryanik** 2019-08-07 12:24 UTC
