### ISSUE TITLE
Windows UI "Yes/No" screens are not activated by default, requiring mouse to be used.

### ISSUE THREAD

**Issue by juur** [CleverRaven/Cataclysm-DDA#78836] opened 2024-12-29 13:58 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/cbf2fa96-8c12-43cc-870a-3a02e7917eba)

Popups such as the above are not activated, so pressing Y or N does nothing, as it does not have focus. This is quite annoying as you then have to use the mouse.

### Attach save file

N/A

### Steps to reproduce

1. Start cdda-windows-with-graphics-and-sounds-x64-2024-12-28-0805
2. Play now with default scenario
3. Find a tree
4. Press e

### Expected behavior

The pop-up window should have focus, such that Y or N works when the keyboard y or n are pressed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: a078529 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    No Monsters [Only_Wildlife]
]

**Comment by juur** [comment] 2024-12-29 13:58
Likely needs ImGui tag adding.

**Comment by RenechCDDA** [comment] 2024-12-29 14:54
Duplicate of #78317

**Closed by RenechCDDA** 2024-12-29 14:54 UTC
Labels: (S1 - Need confirmation)
