### ISSUE TITLE
Unable to reload Misc repair kit

### ISSUE THREAD

**Issue by Pugglee** [CleverRaven/Cataclysm-DDA#71090] opened 2024-01-19 21:07 UTC
### Describe the bug

When I attempt to reload the misc repair kit with a cardboard roll of duct tape the game says I have no items to reload.

### Attach save file

Any save should work but just in case use this one.     
[Duchesne.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13994496/Duchesne.zip)

### Steps to reproduce

1. Make a character with a misc repair kit and find a cardboard roll containing duct tape.  2. attempt to reload the repair kit using the duct tape in the cardboard roll

### Expected behavior

I expected I would be able to reload the misc repair kit using the duct tape in the cardboard roll

### Versions and configuration

- OS: Windows 11.  -Game Version: Experimental Build 2024-1-19-1608.  -Graphics Version: Tiles, Ultica, Larwick Overmap.  -Ingame Language: English.  -Mods Loaded: dda, slowdown fungal growth, disable npc needs, portal storms ignore npcs.

**Comment by Pugglee** [comment] 2024-01-19 21:07
Forgot to say in the report but I am using the catapult launcher

**Comment by KeremBabaG** [comment] 2024-01-19 21:37
> Forgot to say in the report but I am using the catapult launcher

not neccesarily a problem

**Comment by Vulp0d** [comment] 2024-01-20 02:31
Can confirm the same thing happening to me.

**Comment by Procyonae** [comment] 2024-01-20 22:35
/confirm Well that's fun, I can't even find a workaround

**Comment by Jkesler22** [comment] 2024-01-22 16:09
Not sure if this matters, but I am able to insert more duct tape into a cardboard roll that is not yet full, but still not able to unload or move the duct tape from the cardboard roll in any way.

**Comment by DragonWizard23** [comment] 2024-01-24 04:56
I can confirm this issue too.

**Comment by andrei8l** [comment] 2024-01-24 16:29
`cardboard_roll` has the `NO_UNLOAD` so its contents are excluded from all `inventory_selector`s

https://github.com/CleverRaven/Cataclysm-DDA/blob/de8a47fff6b615d3caf911a54b5e801d9c6f5cc9/src/inventory_ui.cpp#L2003

Technically, the behaviour in the old reload UI was a bug, but this can probably be solved with another flag and a preset switch

**Comment by TaiGambol** [comment] 2024-01-24 16:29
Can also confirm; issue exists as of experimental 2024-01-18-0508, @GuardianDll mentioned #70359 may be the specific PR responsible.

**Comment by mike-hoogeveen** [comment] 2024-01-26 16:43
For now as a workaround, you can use the pocket manager/inventory organization to move the duct tape out of the cardboard roll of duct tape, after which you can reload it into the misc repair kit.

**Comment by KittyTac** [comment] 2024-01-27 08:14
> For now as a workaround, you can use the pocket manager/inventory organization to move the duct tape out of the cardboard roll of duct tape, after which you can reload it into the misc repair kit.

Sometimes the pocket manager doesn't work. In which case you should set the rolls on fire (some kind of tinder is required though) and immediately retrieve the loose tape before it burns. Shouldn't result in any loss if you do it right.
![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/52408044/70abe90c-8e14-468b-87c3-37a5e4de3aa8)
![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/52408044/0ff856c9-94ce-49e2-8afc-896b5a133e88)

**Comment by db48x** [comment] 2024-01-29 08:01
Ok, that is a hilariously ridiculous workaround.

**Comment by Jkesler22** [comment] 2024-01-30 03:58
Alternatively, you could put the rolls in something that has multiple pockets, like a backpack, then go into the pocket settings for the backpack, select the roll, then select "move item", it should show you the duct tape only (if not, you selected the wrong thing).  Select the duct tape and then select a different pocket and select "move item" again.  It's complicated and convoluted, but it has worked consistently for me so far.

Of course, if you like to add a little flare to your workarounds, I'm not one to judge!

**Comment by Jkesler22** [comment] 2024-01-30 05:34
Also, I can confirm that removing the "NO_UNLOAD" flag from the cardboard_roll in Cataclysm\data\json\items\containers\containers.json does fix the issue, however I don't know if that is the CORRECT fix.  I'm sort of new to this all.  Holy shit is there a lot to this.

**Comment by GuardianDll** [comment] 2024-01-30 07:33
removing NO_UNLOAD fixes the repair kit, but breaks cardboard roll, since now you can reload it, and you shouldn't

**Comment by Jkesler22** [comment] 2024-01-31 00:20
Ah, got it.  Isn't that what the "NO_RELOAD" flag is for, though?  That is still there.

**Comment by Qrox** [comment] 2024-02-01 09:04
Would it be possible to make misc repair kit use cardboard rolls as a magazine? IRL you probably just put the roll in the kit so that's more realistic than unloading the roll and putting the tape in the kit.

**Comment by GuardianDll** [comment] 2024-02-01 21:03
it would have an unfortunate side effect of using whatever the cardboard can hold, including duct tape, medical tape **and toilet paper**

**Comment by Qrox** [comment] 2024-02-02 14:01
Good point, might need to add support for loading with magazines containing only specific ammo for that to work.

**Comment by GuardianDll** [comment] 2024-02-04 14:23
```diff
diff --git a/data/json/items/tool/workshop.json b/data/json/items/tool/workshop.json
index e73c2c765b..bbe7a3cb9c 100644
--- a/data/json/items/tool/workshop.json
+++ b/data/json/items/tool/workshop.json
@@ -751,7 +751,7 @@
     "symbol": ";",
     "color": "light_gray",
     "ammo": [ "tape" ],
-    "pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "tape": 200 } } ],
+    "pocket_data": [ { "magazine_well": "5000 ml", "pocket_type": "MAGAZINE_WELL", "item_restriction": [ "cardboard_roll" ] } ],
     "charges_per_use": 5,
     "qualities": [ [ "CUT", 2 ], [ "CUT_FINE", 2 ], [ "AXE", 1 ], [ "SAW_W", 2 ], [ "BUTCHER", 7 ], [ "FABRIC_CUT", 1 ] ],
     "use_action": [
```
causes instant segfault with unreadable crash report

<details>
  <summary>crash report</summary>
  
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 1136dab
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0,000,7FF,7AE,FED,EE5[cataclysm-tiles.exe+0x55d,ee5]), 
  #1
    (dbghelp: @0,000,7FF,7AE,FB0,BBD[cataclysm-tiles.exe+0x520,bbd]), 
  #2
    (dbghelp: @0,000,7FF,7AE,FB1,163[cataclysm-tiles.exe+0x521,163]), 
  #3
    (dbghelp: @0,000,7FF,7B0,569,8BC[cataclysm-tiles.exe+0x1,ad9,8bc]), 
  #4
    (dbghelp: @0,000,7FF,7B0,7A0,A1D[cataclysm-tiles.exe+0x1,d10,a1d]), 
  #5
    (dbghelp: @0,000,7FF,7B0,53A,C24[cataclysm-tiles.exe+0x1,aaa,c24]), 
  #6
    (dbghelp: _chkstk+0x11f@0,000,7FF,CCD,112,3AF[ntdll.dll+0xa2,3af]), 
  #7
    (dbghelp: RtlRaiseException+0x484@0,000,7FF,CCD,0C1,4B4[ntdll.dll+0x51,4b4]), 
  #8
    (dbghelp: KiUserExceptionDispatcher+0x2e@0,000,7FF,CCD,110,EBE[ntdll.dll+0xa0,ebe]), 
  #9
    (dbghelp: @0,000,7FF,7AF,F84,6F6[cataclysm-tiles.exe+0x1,4f4,6f6]), 
  #10
    (dbghelp: @0,000,7FF,7AF,F82,390[cataclysm-tiles.exe+0x1,4f2,390]), 
  #11
    (dbghelp: @0,000,7FF,7AF,F81,334[cataclysm-tiles.exe+0x1,4f1,334]), 
  #12
    (dbghelp: @0,000,7FF,7AF,F80,953[cataclysm-tiles.exe+0x1,4f0,953]), 
  #13
    (dbghelp: @0,000,7FF,7AF,F80,619[cataclysm-tiles.exe+0x1,4f0,619]), 
  #14
    (dbghelp: @0,000,7FF,7AF,FCA,ECA[cataclysm-tiles.exe+0x1,53a,eca]), 
  #15
    (dbghelp: @0,000,7FF,7AF,D97,769[cataclysm-tiles.exe+0x1,307,769]), 
  #16
    (dbghelp: @0,000,7FF,7AF,D99,EAC[cataclysm-tiles.exe+0x1,309,eac]), 
  #17
    (dbghelp: @0,000,7FF,7AF,08C,C84[cataclysm-tiles.exe+0x5fc,c84]), 
  #18
    (dbghelp: @0,000,7FF,7AF,0AC,62A[cataclysm-tiles.exe+0x61c,62a]), 
  #19
    (dbghelp: @0,000,7FF,7AF,162,87F[cataclysm-tiles.exe+0x6d2,87f]), 
  #20
    (dbghelp: @0,000,7FF,7AF,162,5EA[cataclysm-tiles.exe+0x6d2,5ea]), 
  #21
    (dbghelp: @0,000,7FF,7AF,166,3DB[cataclysm-tiles.exe+0x6d6,3db]), 
  #22
    (dbghelp: @0,000,7FF,7AE,E7A,F52[cataclysm-tiles.exe+0x3ea,f52]), 
  #23
    (dbghelp: @0,000,7FF,7B0,537,85A[cataclysm-tiles.exe+0x1,aa7,85a]), 
  #24
    (dbghelp: BaseThreadInitThunk+0x14@0,000,7FF,CCB,D97,344[KERNEL32.DLL+0x17,344]), 
  #25
    (dbghelp: RtlUserThreadStart+0x21@0,000,7FF,CCD,0C2,6B1[ntdll.dll+0x52,6b1]), 
```
</details>

**Comment by Jkesler22** [comment] 2024-02-05 23:16
Does it matter that you are specifying the ammo_restriction to be "tape", but in json/items/ammo.json there is no ammo named "tape"?  There is "duct_tape" and "medical_tape".

**Comment by andrei8l** [comment] 2024-02-09 10:43
> ```diff
> diff --git a/data/json/items/tool/workshop.json b/data/json/items/tool/workshop.json
> index e73c2c765b..bbe7a3cb9c 100644
> --- a/data/json/items/tool/workshop.json
> +++ b/data/json/items/tool/workshop.json
> @@ -751,7 +751,7 @@
>      "symbol": ";",
>      "color": "light_gray",
>      "ammo": [ "tape" ],
> -    "pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "tape": 200 } } ],
> +    "pocket_data": [ { "magazine_well": "5000 ml", "pocket_type": "MAGAZINE_WELL", "item_restriction": [ "cardboard_roll" ] } ],
>      "charges_per_use": 5,
>      "qualities": [ [ "CUT", 2 ], [ "CUT_FINE", 2 ], [ "AXE", 1 ], [ "SAW_W", 2 ], [ "BUTCHER", 7 ], [ "FABRIC_CUT", 1 ] ],
>      "use_action": [
> ```

<details>
<summary>This seems to work</summary>

```diff
diff --git a/data/json/items/ammo_types.json b/data/json/items/ammo_types.json
index a016935e3b..59a6d77d5f 100644
--- a/data/json/items/ammo_types.json
+++ b/data/json/items/ammo_types.json
@@ -473,6 +473,12 @@
     "name": "duct tape",
     "default": "duct_tape"
   },
+  {
+    "type": "ammunition_type",
+    "id": "toilet_paper",
+    "name": "ToIlET PaPeR",
+    "default": "toilet_paper"
+  },
   {
     "type": "ammunition_type",
     "id": "battery",
diff --git a/data/json/items/containers/containers.json b/data/json/items/containers/containers.json
index 68c5fda133..16a37b4952 100644
--- a/data/json/items/containers/containers.json
+++ b/data/json/items/containers/containers.json
@@ -4547,7 +4547,7 @@
   },
   {
     "id": "cardboard_roll",
-    "type": "GENERIC",
+    "type": "MAGAZINE",
     "category": "other",
     "name": { "str": "cardboard roll" },
     "description": "A small cardboard roll used to conveniently store materials such as tape or toilet paper.",
@@ -4559,15 +4559,8 @@
     "material": [ "cardboard" ],
     "symbol": "o",
     "color": "dark_gray",
-    "pocket_data": [
-      {
-        "pocket_type": "CONTAINER",
-        "max_contains_volume": "1 L",
-        "max_contains_weight": "1 kg",
-        "item_restriction": [ "duct_tape", "medical_tape", "toilet_paper" ],
-        "volume_multiplier": 0.75
-      }
-    ],
+    "ammo_type": [ "tape", "toilet_paper" ],
+    "pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "tape": 200, "toilet_paper": 200 } } ],
     "flags": [ "NO_UNLOAD", "NO_RELOAD" ]
   },
   {
diff --git a/data/json/items/generic/bathroom_house.json b/data/json/items/generic/bathroom_house.json
index 13c5acdfad..35d71c632d 100644
--- a/data/json/items/generic/bathroom_house.json
+++ b/data/json/items/generic/bathroom_house.json
@@ -261,11 +261,12 @@
   {
     "id": "toilet_paper",
     "name": { "str": "toilet paper", "str_pl": "rolls of toilet paper" },
-    "type": "GENERIC",
+    "type": "AMMO",
+    "ammo_type": "toilet_paper",
     "description": "A luxurious remnant of civilization.",
     "symbol": "~",
     "color": "white",
-    "container": "bag_plastic",
+    "container": "cardboard_roll",
     "price": 89,
     "price_postapoc": 180,
     "volume": "250 ml",
diff --git a/data/json/items/tool/workshop.json b/data/json/items/tool/workshop.json
index e73c2c765b..bbe7a3cb9c 100644
--- a/data/json/items/tool/workshop.json
+++ b/data/json/items/tool/workshop.json
@@ -751,7 +751,7 @@
     "symbol": ";",
     "color": "light_gray",
     "ammo": [ "tape" ],
-    "pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "tape": 200 } } ],
+    "pocket_data": [ { "magazine_well": "5000 ml", "pocket_type": "MAGAZINE_WELL", "item_restriction": [ "cardboard_roll" ] } ],
     "charges_per_use": 5,
     "qualities": [ [ "CUT", 2 ], [ "CUT_FINE", 2 ], [ "AXE", 1 ], [ "SAW_W", 2 ], [ "BUTCHER", 7 ], [ "FABRIC_CUT", 1 ] ],
     "use_action": [
```

</details>

**Comment by NafenX** [comment] 2024-03-08 15:58
Just had this issue and couldn't figure for the life of me how to fix it or even if what I was trying to do was correct. Thankful for the workarounds but do hope this is fixed :D

**Comment by LetterShapedGlyphs** [comment] 2024-03-09 17:45
> This seems to work

This was super helpful thank you. Only had to make a couple of additional changes to get it working fully on my end now. Everything seems to be behaving exactly as it should so just need to do a BUNCH of item group fixes (because apparently duct tape is extremely inconsistent across the board) but I should have a PR up soon barring any unforeseen bugs.

**Comment by NafenX** [comment] 2024-03-20 16:56
I read "duct tape shenanigans" in the changelog and had hoped that it meant this was fixed, but apparently it just means that you can no longer use the pocket manager as a workaround to this being broken 🤔

**Comment by Ivan-Shestakov** [comment] 2024-03-29 23:05
Reproduces for me on MacOS, compiled from source using 08a7eee6413e86e9d69db3e27dcb535e87436d74 (pulled 4 days ago)

**Comment by RenechCDDA** [comment] 2024-03-30 22:05
All the spawns might be screwed up, but this seems to preservs everything: The ability for the misc repair kit to consume duct tape, loading tape rolls into the misc repair kit, crafting using duct tape off the roll.
<https://github.com/CleverRaven/Cataclysm-DDA/compare/master...RenechCDDA:Cataclysm-DDA:duct_tape_fix>

**Comment by oosyrag** [comment] 2024-04-08 03:29
In case anyone is still looking for a temporary workaround to this and missed it in the comments above - Delete "NO_UNLOAD" flag (and the comma) from /data/json/items/containers/containers.json in your game files on line 4655, or search for "cardboard_roll". This will let you get your duct tape off the roll to reload your misc repair kit with. This edit can be applied to existing games safely.

Note that this is not the desired behavior moving forward, so it's not really a solution to the issue.

**Comment by RenechCDDA** [comment] 2024-05-08 10:06
Resolved by the linked issue.

**Closed by RenechCDDA** 2024-05-08 10:06 UTC
Labels: (S2 - Confirmed), Items: Magazines, [C++], Items / Item Actions / Item Qualities, (P3 - Medium), Help Wanted

**Comment by KaleProgram** [comment] 2024-05-08 18:41
Came back to this as several work arounds stopped working correctly. It appears that trying to use the caveman method of lighting your roll of duck tape on fire and collecting the tape now only seems to burn up the whole roll (as it should) and bashing the roll results in the destruction of precious duck tape too. Perhaps a special exception should be made for the miscellaneous repair kit to accept the roll of duck tape as a type of ammo (not just the tape itself) and examine how much tape is left in the roll and replace it with a roll of duck tape minus the tape you used from the roll.

**Comment by TaiGambol** [comment] 2024-05-08 18:50
The issue was literally just closed today as fixed by another PR. Look at #73192.
