### ISSUE TITLE
Segmentation fault when reaching Z level +10 in a helicopter

### ISSUE THREAD

**Issue by neosulc** [CleverRaven/Cataclysm-DDA#60469] opened 2022-08-26 19:25 UTC
### Describe the bug

Game crashes

### Steps to reproduce

1 Start the helicopter.
2 Fly upwards as many times as you can
3 Game crash^segmentation violation

### Expected behavior

Game does not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: 1045fea-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Catasauqua.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9435893/Catasauqua.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9435894/config.zip)

**Comment by BrettDong** [comment] 2022-08-27 04:46
Duplicate of #44503.

**Closed** 2022-08-27 04:46 UTC
Labels: (S3 - Duplicate)
