### ISSUE TITLE
Killing fungaloids spawns multiple fungaloids

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15386] opened 2016-02-14 05:52 UTC
I believe what is happening is killing the fungaloid produces spores which are instantly upgrading into fungaloids since the world is ~2 years in.

**Comment by remyroy** [comment] 2016-04-20 03:15
This is a duplicate of #12909 and it was fixed with #12911. You must be running an old version of the game either stable or an experimental once before July 2015.

**Comment by remyroy** [comment] 2016-04-20 03:19
@ejseto If you are really running an older version of the game and you reported other bugs thinking you are running the latest experimental, could you please [review all your open issues](https://github.com/CleverRaven/Cataclysm-DDA/issues/created_by/ejseto) and close the ones that have been solved already?

**Comment by Coolthulhu** [comment] 2016-04-23 01:10
Can't replicate in current version.

**Comment by i2amroy** [comment] 2016-05-06 20:23
Confirming as no longer occurring in the current experimental version; closing.

**Closed by i2amroy** 2016-05-06 20:23 UTC
Labels: Confirmation Needed, Duplicate
