### ISSUE TITLE
Hitting the Esc key while in the reading menu causes a seg fault

### ISSUE THREAD

**Issue by Severhead** [CleverRaven/Cataclysm-DDA#77230] opened 2024-10-21 12:58 UTC
### Describe the bug

Hitting the Esc key while in the reading menu causes a seg fault.
Hitting R to read then hitting esc causes seg fault 

### Attach save file

[Magiclysm Cataclym Small Cities-trimmed.tar.gz](https://github.com/user-attachments/files/17461094/Magiclysm.Cataclym.Small.Cities-trimmed.tar.gz)

### Steps to reproduce

Create player with book, read book. Open read menu and hit esc.

### Expected behavior

expected game not to crash and return to main play screen

### Screenshots

![Screenshot 2024-10-21 085625](https://github.com/user-attachments/assets/6873f605-33c9-47ff-ad24-78ef0c182f47)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 5762e89 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm Revamp and Additions [magicrevamp],
    Bionic Slots [cbm_slots]
]

**Comment by AudBobb** [comment] 2024-10-21 13:01
duplicate of #77223

**Closed** 2024-10-21 13:31 UTC
Labels: (S1 - Need confirmation)
