### ISSUE TITLE
#11008 Shoulder Strap - Marlin 39A internal magazine removal

### ISSUE THREAD

**Issue by KrunkySmokin** [CleverRaven/Cataclysm-DDA#44228] opened 2020-09-17 18:37 UTC
Applying a shoulder strap to a Marlin 39A removes the internal magazine of the gun.

=-=-=-=-=
1. Load game
2. Give self shoulder strap and Marlin 39A
3. Apply shoulder strap to gun
4. It now has no internal magazine
=-=-=-=-=

Mod list: Cataclysm DDA
               Disable NPC Needs

![issue](https://user-images.githubusercontent.com/49448025/93513038-3b120700-f8f3-11ea-9591-deb4232259c4.png)

**Comment by wapcaplet** [comment] 2020-09-17 22:28
Confirmed in 0.E-5926-g a883429bdd

This appears to be a duplicate of #42340 where other players mentioned their gun not being reloadable after attaching a mod, but I believe you @KrunkySmokin are the first to clearly make the connection between attaching the mod and the internal magazine no longer working. Thanks!

I am adding this info to that ticket and closing this one, since the other has more discussion and is already filed as a blocker for release 0.F.

**Closed** 2020-09-17 22:36 UTC
Labels: (S3 - Duplicate)
