### ISSUE TITLE
Crash on reaching Computers skill level 10

### ISSUE THREAD

**Issue by HeroicMatt** [CleverRaven/Cataclysm-DDA#64606] opened 2023-03-26 21:05 UTC
### Describe the bug

The game crashes when reaching Computers skill level 10.

### Attach save file

[Escobares-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11073048/Escobares-trimmed.tar.gz)

### Steps to reproduce

1. Make a character, advance to near level 10 in the computers skill.
2. (If using included save file) Advance to room on right, hack both terminals and Open Chambers to the CBM containment areas.
3. Advance to level 10 in the computers skill.
4. Observe the crash.

### Expected behavior

I would expect the game to not crash upon reaching skill level 10 in computers, because otherwise I can no longer play the game while utilizing the computers skill.

### Versions and configuration

- OS: Windows 11
- Game Version
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions, StatsThroughSkills

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11073055/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11073066/debug.log)
[Escobares-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11073048/Escobares-trimmed.tar.gz)

**Comment by RenechCDDA** [comment] 2023-03-26 21:09
Yet another duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Comment by NetSysFire** [comment] 2023-03-26 22:18
Duplicate of #64466.

**Closed by NetSysFire** 2023-03-26 22:18 UTC
Labels: (S1 - Need confirmation)
