### ISSUE TITLE
No hope mode-Npcs in refugee center and starting npc dyng  spontaniosly bug

### ISSUE THREAD

**Issue by survivor987** [CleverRaven/Cataclysm-DDA#77306] opened 2024-10-24 21:21 UTC
### Describe the bug

For quite some  time no hope mode with no other mode installed has resuslted in all my game having certain  ncp in refugee center (doctor,mercenary,old guard,arsonist) dying in few days of meeting them.In my test for this report i immidiately teleported to refugeee center they died at day 64 whcih can be seen on screenshots.
Most often npc whcih i start game within dies as well and in my testign after npc in refugeee center  died i teleported back and saw npc alive but after waiting several hours in vicinity he died as well whcih can be seen isn screenshots,.

### Attach save file

[Croton Heights-trimmed.tar.gz](https://github.com/user-attachments/files/17512934/Croton.Heights-trimmed.tar.gz)

### Steps to reproduce

1.Start new game and go to refugeee center

2.Wait for several days

3.Some ncp in refugee center will conistently be dead when you come back to center

### Expected behavior

NPC not spontaniosly dying from passage of time.

### Screenshots

https://prnt.sc/SUTrfYDdLTm5

https://prnt.sc/Bricm1fXFi_i

https://prnt.sc/pAnD__1iG-dU

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: cdda-experimental-2024-10-23-0605 5d32050 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Hope [no_hope]
]

**Comment by RenechCDDA** [comment] 2024-10-24 22:05
Duplicate of #74714

**Closed by RenechCDDA** 2024-10-24 22:05 UTC
Labels: (S1 - Need confirmation)
