### ISSUE TITLE
Can't make vehicle welding rig with three makeshift welders

### ISSUE THREAD

**Issue by Leon9621** [CleverRaven/Cataclysm-DDA#23370] opened 2018-04-04 22:03 UTC
Game version: 0.C-27061-g068b741

Operating system: Windows 8

Tiles or curses: Tiles

Mods active:
Tall Buildings, More Survival Tools, No Fungal Monsters, StatsThroughSkills, Vehicle Additions Pack, Tanks and Other Vehicles, Alternative Map Key, Bionics Systems Mod, EXTENDED_BUILDINGS, Makeshift Items Mod, More Buildings, More Locations, Mutation Changes, Prevent Zombie revivification, Simplified Nutrition 

### Expected behavior

The recipe would use one welder to turn the other two welders, along with the other tools, into a vehicle forge rig.

### Actual behavior

The "makeshift welder" part of the recipe is brown, signifying that I don't have enough welders (3) to weld two into the rig.

### Steps to reproduce the behavior

Get a steel frame, soldering iron, three makeshift welders, and 5 units of copper wire, along with the welding rig recipe, and attempt to make the welding rig. It should tell you that you don't have enough welders.

Pictures for reference: 
https://i.imgur.com/vYRJVQz.png Showing the that I have the necessary ingredients
https://i.imgur.com/XVAO3wE.png What I see in the recipe

**Comment by illi-kun** [comment] 2018-04-04 22:06
Dupe of #19461 I suppose.

**Closed** 2018-04-06 08:09 UTC
Labels: (S3 - Duplicate), <Bug>
