### ISSUE TITLE
Fencing needs some tweaking

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#21096] opened 2017-05-23 05:28 UTC
The stop-thrust thing is cool but leads to some interesting behavior.

Walking into a school and being swarmed by child zombies and regular zombies, I lose control for umpteen moves as I keep riposting attacks, eventually leaving a huge swath of death a round me. Cool beyond belief, but the loss of control is strange.

While butchering a corpse, or any other multi-move activity, I am able to defend and kill anything that attacks due to the automatic stop-thrust

**Comment by DangerNoodle** [comment] 2017-05-23 16:10
There are other martial arts that add more active counter attacks, the riposte could be reworked to behave like that.

**Comment by kevingranade** [comment] 2017-05-24 14:55
Duplicate of #20403 
This is an inherent issue with the way counters are implemented.  Boxing has a counter that is an attempt to implement a system where the defensive ability applies an "opening" effect to the target than be followed up for additional damage.  However there are also reports that it doesn't work #18117

**Closed by kevingranade** 2017-05-24 14:55 UTC
Labels: Balance

**Comment by DangerNoodle** [comment] 2017-05-24 19:40
Strange. There are other styles that do this, right? In fact several styles rely on buff chains. Unless only `on_block` effects are broken, that means martial arts as a whole are defunct, and that would be a priority issue.
