### ISSUE TITLE
Moving any stack size in AIM costs only 1 turn

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13131] opened 2015-07-30 08:05 UTC
Moving, for example, a stack of 300 planks takes just 1 turn.

EDIT: Moving with move all doesn't cause the bug, moving with enter does.
##

**Comment by Barhandar** [comment] 2015-07-30 12:08
How exactly are you moving a stack of 300 _planks_? For me, regardless of the option, nonstacking items (ones that have a number in "amt" column and not brackets after item name) are moved one at a time regardless of whether I use "move item" or "move item stack".

**Comment by Coolthulhu** [comment] 2015-07-30 12:48
Open AIM, set directions, select two by fours, press enter, entire stack gets moved. Time increases by 6 seconds.

**Comment by narc0tiq** [comment] 2015-07-30 13:02
Sourcing the planks from your inventory, I imagine, since otherwise it
should move one item at a time. Are you sure it's not just the over-volume
trigger that's making you drop them?

**Comment by DavidKeaton** [comment] 2015-07-30 19:55
It should only be moving one, that part shouldn't have changed.

**Comment by Oskar636** [comment] 2016-11-10 22:17
The only way to reproduce this exactly is to wish for 300 two by fours, then to drop them using inventory tab in a.i.m but they will only drop onto the tile you are standing on. Even if this isn't the case, this is a duplicate of #9392. 
Build 5864 windows 64bit console

**Closed** 2016-11-11 12:22 UTC
Labels: Bug
