### ISSUE TITLE
Vehicle doors won't close if cardinally adjacent outside

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#59329] opened 2022-07-16 20:42 UTC
### Describe the bug

You cannot close vehicle doors doors when standing directly next to them.

### Steps to reproduce

1. Get a vehicle
2. Open the vehicle's door
3. While standing next outside of the door in a cardinal direction, attempt to close it
4. Watch the message log insult the apparent ghost blocking the door

### Expected behavior

The vehicle door closes.

### Screenshots

![vedoor4](https://user-images.githubusercontent.com/32048635/179371268-af212637-5bf5-4b8b-88b9-d6a9320ea93a.png)
![vedoor3](https://user-images.githubusercontent.com/32048635/179371269-3be7b53d-dc9d-4cd4-a9c3-5b609407bb5c.png)
![vedoor2](https://user-images.githubusercontent.com/32048635/179371271-179eb7f4-8e00-45e4-8087-84720c8086fd.png)
![vedoor1](https://user-images.githubusercontent.com/32048635/179371272-5fb06593-6f53-4cda-b440-2c49ec0e661f.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: de006e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This is likely due to the fake vehicle parts; if the vehicle is correctly askew you can close the door(s) even while directly next to them.

**Comment by Inglonias** [comment] 2022-07-16 22:38
Duplicate of #58303

**Closed** 2022-07-16 22:58 UTC
Labels: (S1 - Need confirmation)
