### ISSUE TITLE
Bug: Bad trait description in character creation

### ISSUE THREAD

**Issue by Carefulrogue** [CleverRaven/Cataclysm-DDA#25925] opened 2018-10-01 15:45 UTC
Multiple descriptions of traits during character creations are printing output that is uninformative to the average player.  E.G.: 
From trait: "Languorous"
Actual Output: "basic_string::substr: __pos (which is 201) > this size() (which is 5)"

Expected Output: "Whether due to lack of exercise and poor diet, or due to a natural disinclination to physical endurance, you tire due to physical exertion much more readily than others.  Your maximum stamina is 25% lower than usual."

Recreation should be as easy as accessing character creation.  

**Screenshots**  
An image of one of the traits as an example of what I'm talking about:
https://imgur.com/pRk0njS

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-32733-g0a83a2b (tiles)
 - Dark Days Ahead
**Additional context**  
Unrelated to mods.  Removing all but the core content files results in the bug persisting.  The output varies from each, but generally follows the same blueprint, with the specific numbers varying.

List of all bad outputs:
Advantages
-  Fleet-Footed
-  Strong Back
-  Packmule
-  Tough
-  Indefatigable
-  Quick

Disadvantages
-  Flimsy
-  Frail
-  Slow-Footed
-  Fragile
-  Pain Sensitivity
-  Languorous
-  Bad Back
-  Disorganized
-  Glass Jaw

**Comment by Zireael07** [comment] 2018-10-01 16:48
duplicate of #25904 which itself is a duplicate of something else

**Closed by Zireael07** 2018-10-01 16:48 UTC
