### ISSUE TITLE
[Magiclysm] Spell level achivements seem to be bugged.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#49289] opened 2021-06-13 18:28 UTC
There seem to be a bug concerning achievements, it shows an incorrect spell level achievement when loading the game.

# Steps To Reproduce

Gain few low level spells, **???**, save game and exit, on loading in you get untrue achievement.

# Expected behavior

Gaining the achievement when fulfilling the requirements.

# Screenshots

Screenshots made upon loading the game:

![Zrzut ekranu (23)](https://user-images.githubusercontent.com/61629226/121818107-7fb1af80-cc85-11eb-8719-1df941a5fd1c.png)

![Zrzut ekranu (22)](https://user-images.githubusercontent.com/61629226/121818111-86402700-cc85-11eb-94f2-0027bd0c8a4f.png)

And the attached save:

[Micaville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6644419/Micaville.zip)

**Comment by Jan-Blasiak** [comment] 2021-06-13 18:28
On second screenshot is my highest level spell.

**Comment by Salty-Panda** [comment] 2021-06-13 19:28
Afaik it's a known bug. Achievement is granted on the use of spells by mobs. Certain special attacks and multiplying of animals use spells under the hood.

**Comment by actual-nh** [comment] 2021-06-13 21:50
> Afaik it's a known bug. Achievement is granted on the use of spells by mobs. Certain special attacks and multiplying of animals use spells under the hood.

#48341 should have fixed that part.

**Comment by actual-nh** [comment] 2021-06-13 21:51
This is actually a duplicate of #47425, which I have marked as confirmed.

**Closed** 2021-06-13 21:51 UTC
Labels: (S3 - Duplicate), <Bug>, Game: Achievements / Conducts / Scores, Mods: Magiclysm
