### ISSUE TITLE
NPCs with guns refuse to shoot outside melee range

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#24125] opened 2018-06-29 16:19 UTC
Game version:
Build 7502
Operating system:
Win7
Tiles or curses:
Tiles
Mods active:
None
### Expected behavior
Hostile NPCs should shoot you from more than one tile away.
### Actual behavior
NPCs will not shoot until you are beside them and will make no attempt to close distance if they have a ranged weapon equipped.
### Steps to reproduce the behavior
Start game, go to refugee center, find guard armed with gun, throw something at them.  All guards with melee weapons will attack as normal, those with ranged weapons will stand there and do nothing until you move beside them, then will shoot you, even if you wait all day long.

**Comment by Night-Pryanik** [comment] 2018-06-30 13:10
Duplicate of #19798.

**Closed by Night-Pryanik** 2018-06-30 13:10 UTC
Labels: <Bug>, NPC, Ranged
