### ISSUE TITLE
Edible jerky from rotten meat

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13144] opened 2015-07-31 12:45 UTC
Foods that don't rot can be created from rotten ingredients without penalty. 
##

**Comment by drbig** [comment] 2015-07-31 17:53
Looks like inverse of #12971.

**Comment by Barhandar** [comment] 2015-07-31 18:01
In practice, yes. In logic, though, it's because crafting doesn't care how rotten a thing is, only that it exists - and items that do not spoil do not care about rotting counter.

**Comment by drbig** [comment] 2015-07-31 18:05
Btw. How does crafting works when using damaged components? Increased chance of failure? Damaged crafted item? No influence?

**Comment by Coolthulhu** [comment] 2015-07-31 18:15
Nothing at all. Components are pretty much just ids.

**Comment by Headjack** [comment] 2015-07-31 18:59
This bug is old as Whales. Super-confirm.

**Comment by greattuna** [comment] 2015-07-31 19:15
Can confirm as a guy who mass-produces dehydrated meat from rotten meat.

**Comment by tyrael93** [comment] 2015-08-04 09:16
#4831
I made an issue about this about two years ago and it's still relevant.

**Comment by pipehat** [comment] 2015-08-06 16:21
How about we get rid of [type] (rotten) and instead, when something rots, turn it into a single new type 'rotten matter'.

That would alleviate inappropriate crafting from rotten items. And recipes that should work with rotten stuff could focus on that single item, e.g.: 
> 1 fertilizer = tool with DIG:1, components: rotten_matter:2

**Comment by Coolthulhu** [comment] 2015-08-06 16:32
Rotten food can be useful for crap that doesn't involve eating it. Tallow for oil etc.
So I'd be against rotten matter.

**Comment by drbig** [comment] 2015-08-06 16:45
> Rotten food can be useful for crap that doesn't involve eating it. Tallow for oil etc.

The point here seems to allow just that but simplifying all "rotten X" into single "rotten matter" ("rotten food"). I like this idea as such, but my concern is this would make fully named and distinct items "disappear" into "rotten matter" - that can be confusing, e.g. "What rotted exactly? Or did I leave that tasty sandwich somewhere else?" (and remember stuff may, from player's perspective, rot while they are not looking).

**Comment by pipehat** [comment] 2015-08-07 10:41
How about:
a) we add an 'allow-rotten' qualifier on recipe components like the fat in the tallow recipe
b) by default, when crafting, disallow rotten components if the recipe doesn't flag the component as  'allow-rotten'

**Comment by drbig** [comment] 2015-08-07 12:19
> letting items specify what, if anything, they turn into when rotten

That certainly sounds like the most flexible way of handling it.

**Comment by BevapDin** [comment] 2015-08-07 12:28
Items changing their type over time has the same problem as items vanishing (e.g. completely rotten items, or items burning in a fire): when the crafting is started, they are there, but when the crafting ends, they have vanished (changed type counts as vanished).

You can already experience that bug:
- choose a recipes that takes a while and consumes a flammable item (wood),
- have exactly the required amount of the flammable items with you (not more!),
- make a large fire and put the item in it,
- start crafting.

The items are there, so it should start just fine. But when you're finished, the items are gone and the game complains about it.

You get the same problem with items that change type. The game checks for an item of type "meat" and when the crafting is finished, it has become "meat_rotten", so the game won't find the required "meat" item and complains.

----

Note that there are other reasons for vanishing items: sludge crawler (or similar monster) consumes items it crawls over it. A spitter spits acid onto the items, they are destroyed. Glass items are bashed. Nearby fire jumps over to a pile of flammable items.

**Comment by pipehat** [comment] 2015-08-07 13:01
So let's consume component items at the instant crafting starts then.

**Comment by kevingranade** [comment] 2015-08-08 04:20
The reason we consume items at the end of crafting is that crafting can be
interrupted, we don't need items to be in some weird limbo state when that
happens.
What we could do is bundle the items up into an explicit 'wip crafting'
item or similar, which will either disappear at the end of crafting, or get
disassembled into it's components if the recipe is cancelled.

**Comment by narc0tiq** [comment] 2015-08-08 07:20
Sort of the way we make dynamic corpses, we'd make a
`[result]_being_crafted` item? Y'know, that could also be used to support
crafting that could be resumed later...

**Comment by Coolthulhu** [comment] 2015-08-08 11:12
> Sort of the way we make dynamic corpses, we'd make a `[result]_being_crafted` item?

Yeah.
I almost started implementing it, but noticed some problems, like having no good way to represent `clean_water_being_crafted`.
For it to work, we'd either need to implement "buckets" (pots/pans/cans as liquid containers, dropping the contents on insertion to inventory) and liquid craft pseudo-items, or have a dual system working as the old one for some items and like the new one for others.

**Comment by narc0tiq** [comment] 2015-08-08 11:50
I think for clean water in particular, we wouldn't want resumable crafting.
Bringing it halfway to boiling once doesn't mean you can just do half of
the heating the second time (we could track water temperature, but let's
not). There are probably other objects for which this is true.

In which case, the clean_water_being_crafted can just sit in the inventory
and be uncrafted if you cancel.

I can't say if that would help the other problems, though.

**Comment by mugling** [comment] 2016-11-30 15:02
Duplicate of #9879

**Closed by mugling** 2016-11-30 15:02 UTC
Labels: Bug
