### ISSUE TITLE
Freshly fed sourdough starters are aging backwards

### ISSUE THREAD

**Issue by DigitalLibrarian** [CleverRaven/Cataclysm-DDA#37535] opened 2020-01-30 01:15 UTC
Freshly fed sourdough starters have a timer before they can be activated for the next stage in sourdough bread production.  In my game, This timer starts at 1 day, then goes to 1 year, then 9 years.

1. Create a freshly fed sourdough starter (it may be necessary to use one that you get as a byproduct of cooking sourdough)
2. Set the starter jar down and notice that its description claims to require 1 day.
3. Let a day pass in game
4. Check the starter jar description and notice that the jar claims to require 1 year.
5. Later the jar will claim to require 9 years.

Sourdough starters are expected to have their timers run down, not up.

**Comment by jkraybill** [comment] 2020-02-10 10:07
I couldn't reproduce this in the latest build. I tried spawning freshly fed starter, as well as creating it as a byproduct of making sourdough, and tried aging it while in the reality bubble and while not in the reality bubble. In all cases, I saw it count down from 2 days to 0 days accurately, and then say "It's done and can be activated".

@DigitalLibrarian could you verify what version you were using, and maybe try reproducing in the current experimental if you can? Also did it definitely say "1 day" as the requirement to transform appears to be 2 days (50 hours) - and was for me - even though the original commit said it should be 3 hours.

**Comment by wapcaplet** [comment] 2020-09-27 03:00
Could not reproduce in 0.E-6285-g 419ee84b88 - both freshly fed and juvenile sourdough starter appear to age correctly. Closing issue.

**Closed by wapcaplet** 2020-09-27 03:00 UTC
Labels: (S1 - Need confirmation), <Bug>, Items: Food / Vitamins
