### ISSUE TITLE
Goofy performace saving techniques

### ISSUE THREAD

**Issue by Coach-mdl** [CleverRaven/Cataclysm-DDA#71839] opened 2024-02-18 22:52 UTC
### Describe the bug

Hiding in a cardboard box can save performance when craft/constructing etc. You may not see much of difference unless you're on a low end system, or spawn and UNGODLY amount of items. 

### Attach save file

[It's all coming together-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14324723/It.s.all.coming.together-trimmed.tar.gz)

### Steps to reproduce

Craft in a situation that usually slows down your system while inside a cardboard box. (Might not help if the lag is NPC related).

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-sounds-x64-2024-02-17-0804
Windows 10
Mods:   "dda",
  "skyisland",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "magiclysm",
  "mindovermatter",
  "DinoMod",
  "bombastic_perks",
  "crazy_cataclysm",
  "extra_mut_scens",
  "MMA",
  "sees_player_retro",
  "StatsThroughSkills",
  "minimod_no_rust",
  "speedydex" 

### Additional context

Minimod no rust is a mod that disables skill rust. If there's a better way to disable skill rust, let me know

Link to mod: [https://github.com/John-Candlebury/CDDA-Minimods/releases/tag/norustV1.1](url)

**Comment by RenechCDDA** [comment] 2024-02-18 22:55
Duplicate of #63586

**Closed by RenechCDDA** 2024-02-18 22:55 UTC
Labels: (S1 - Need confirmation)
