### ISSUE TITLE
Floating NPC Bandit at Grain Silo

### ISSUE THREAD

**Issue by Beneficial-Insurance** [CleverRaven/Cataclysm-DDA#48980] opened 2021-05-21 21:36 UTC
# Describe the bug
There is a floating NPC bandit at the grain silo.

I guess the NPC spawned in the middle of the open air, and not on the ground and for some reason isn't falling down.

# Steps To Reproduce

I do not know how to reproduce. However, I can provide a savegame.

# Expected behavior
NPC is not floating. Either falls to the ground or was spawned on a surface.

# Screenshots
![Screenshot 2021-05-21 22 19 02](https://user-images.githubusercontent.com/57273656/119199982-261ff000-bae0-11eb-9d38-65294f003a27.png)
![Screenshot 2021-05-21 22 23 48](https://user-images.githubusercontent.com/57273656/119200004-31731b80-bae0-11eb-93fd-10e20eee061d.png)

# Versions and configuration
- OS: Linux
    - OS Version: <unknown> Debian
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6525161/save.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6525165/save.zip)

- Game Version: 0.E-10281-ge365124 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by actual-nh** [comment] 2021-05-21 21:52
Duplicate of #36635, which I will "bump".

**Closed** 2021-05-21 21:52 UTC
Labels: (S3 - Duplicate)
