### ISSUE TITLE
Error with reduce_charges allowing infinite first aid kits

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#12991] opened 2015-07-19 05:42 UTC
When using E to use a first aid kit from the floor or from the container of a vehicle, the following error is displayed and no charges are consumed. Healing still occurs. This error does not occur when using bandages, hemostatic powder, or disinfectant from the floor.

DEBUG: invalid item position -2147483648 for reduce_charges

Version is 5a5dfe5.

**Comment by drbig** [comment] 2015-07-19 14:01
Confirmed present at `0.C-4591-g241248d`.

**Comment by drbig** [comment] 2015-07-19 15:25
Ok so with the help of trusty `gdb` I can say this: the eat from ground won't work for anything that uses `assign_activity`, as that whole system operates explicitly on item position in inventory.

So one solution seems like reworking it to use item pointers instead... But I have a bigger problem: eating a first aid kit has only *slightly more* sense than eating a bandage, which has exactly zero sense. I assume the ability to "eat" healing items is either for convenience or has roots in the approach found in other roguelikes (or both, not that it matters much).

Either way this seems like it needs some discussion.

**Comment by mightyagrippa** [comment] 2015-07-19 15:41
Yeah, removing the ability to use first aid kits as a comestible makes sense. It would also reduce some ambiguity regarding the Eat action; pills and food/drink take 250 time units, but the first aid action takes significantly longer. I know I've lost a lot more ground than I expected to approaching enemies by Eating a first aid kit. It might also enable dual uses for certain comestibles. Eat pure ethanol for a buzz, apply as a disinfectant. I'm interested to hear if anyone knows the reasons for having Edible first aid kits.

Would this bug apply to any other assign_activity items?

**Comment by drbig** [comment] 2015-07-19 16:54
> pills and food/drink take 250 time units, but the first aid action takes significantly longer.

Indeed, that's a practical concern.

> It might also enable dual uses for certain comestibles. Eat pure ethanol for a buzz, apply as a disinfectant.

I like this. And your example makes sense! Though eating pure ethanol is less of a 'buzz' and more of 'vomit or fall to the ground', depending on quantity.

> I'm interested to hear if anyone knows the reasons for having Edible first aid kits.

Not practically relevant, but interesting :)

> Would this bug apply to any other assign_activity items?

That's what I (tried?) to say. Any item that uses `assign_activity` that on finish tries to do anything to the assigned item is pretty likely to "blow up" if used "off ground".

**Comment by mightyagrippa** [comment] 2015-07-19 17:10
You said it fine. I probably should have clarified. The "a"pply menu doesn't give an option to use items off ground, that seems to be exclusive to the "E"at menu. I was wondering if there were other assign_activity comestibles or if the first aid kit is a special snowflake.

**Comment by Coolthulhu** [comment] 2015-07-19 17:17
Having "a"pply allow items off the ground was also requested, so it would be the best if the solution handled that case too. That said, for now just not allowing first aid outside inventory would work.

**Comment by drbig** [comment] 2015-07-19 17:39
> That said, for now just not allowing first aid outside inventory would work.

True.

Though given the above discussion any I'd be for any larger changes to mean that "dual uses for certain comestibles".

**Comment by kevingranade** [comment] 2015-07-19 19:58
There's no good reason to keep allowing 'e'ating first aid kits, it kind of
evolved that way over a large number of changes, what is intended is being
able to 'activate most anything and have it do it's default action, but we
can revisit that if it makes sense for dual-(or many-)purpose items.  For
example we could pop up a menu when it's ambiguous how it can be activated.
I know alcohol-as-disinfectant has been oft-requested (though I haven't
looked into that actually being a worthwhile thing to do IRL), and not
having a way to handle both has been a blocker.
I would say the right thing to do this instant is a quick fix to prevent
the crashes, and kick off a discussion about many-use items.

**Closed** 2015-07-22 09:06 UTC
Labels: Bug, Suggestion (Discuss)

**Comment by Barhandar** [comment] 2015-07-26 18:32
>Eat pure ethanol for a buzz, apply as a disinfectant

_Pure_ ethanol (or, for that matter, azeotropic solution - 95.6%) isn't a disinfectant. 70% solution, which you could find in a first aid kit, is. For that matter, so is 40% solution, like in vodka, you just need to apply it for longer.
>(though I haven't looked into that actually being a worthwhile thing to do IRL)

See above. It is a worthwhile disinfectant in case you don't have anything else, like chlorhexidine. The purer the solution, the better it is - medical ethanol being best, followed by (real) vodka, then cognac and whiskey, then other non-liquour alcohols, then beer.
