### ISSUE TITLE
NPC Trader doesn't restock after 3 Days or more. 

### ISSUE THREAD

**Issue by TheMrMomo** [CleverRaven/Cataclysm-DDA#47906] opened 2021-03-06 14:17 UTC
# Describe the bug

The Forge Lord (Magicylsm NPC Trader) doesn't restock his wares. 

# Steps To Reproduce

1. Locate the Forge of wonders and trade with the Forge Lord. 
2. Leave area. 
3. Return after 3 or more days. 
4. Forge Lord still has the same items for sale. 

# Expected behavior

Traders should restock after 3 days. 

# Screenshots

![Screenshot (35)](https://user-images.githubusercontent.com/43098058/110209599-a9408b00-7e8d-11eb-9c64-1bc5533769e8.png)
![Screenshot (36)](https://user-images.githubusercontent.com/43098058/110209601-ac3b7b80-7e8d-11eb-9c40-83bff87677d1.png)
![Screenshot (37)](https://user-images.githubusercontent.com/43098058/110209602-ac3b7b80-7e8d-11eb-86ac-bbee0a1e03e3.png)
![Screenshot (38)](https://user-images.githubusercontent.com/43098058/110209604-ae053f00-7e8d-11eb-904e-69dda113790c.png)
![Screenshot (41)](https://user-images.githubusercontent.com/43098058/110209606-ae9dd580-7e8d-11eb-813a-630cebb289eb.png)
![Screenshot (42)](https://user-images.githubusercontent.com/43098058/110209609-b0679900-7e8d-11eb-8389-56a46d514075.png)
![Screenshot (43)](https://user-images.githubusercontent.com/43098058/110209612-b1002f80-7e8d-11eb-92d5-e913371ef2d5.png)

The first dated item was traded to him long after I first traded with him. After the first dated Item I stayed over 200 overmap tiles away. After trading in the second item I stayed about 60 map tiles away but checked in once. Then I stayed 25 map tiles away before handing in the 3rd Date item. I don't think this has any implication. But wanted to make sure. I'll now test it with keeping him in my reality bubble for 3 days. 

Update: I stayed right next to the forge for over 3 days. Still no restock. So it likely isn't an issue of not being loaded. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9859-g661c627 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm]

Thanks for reading.

**Comment by PaulBlay** [comment] 2021-03-06 14:56
Possible duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/46766

**Closed** 2021-06-24 22:05 UTC
Labels: (S3 - Duplicate), Mods: Magiclysm, NPC / Factions
