### ISSUE TITLE
Position of “Press s to Change” is hardcoded in Scenario new character tab

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23485] opened 2018-04-14 10:55 UTC
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Summary
In the new player menu > Scenario tab, there's this text “Sort by:”.

But it seems the position of “Press s to Change” is hardcoded. This means it'll overwrite the text before, this is especially a problem in translations, like the German one. In German, the sort type (points or alphabtical) is made completely invisible by this!

### How to reproduce

* Select German
* Start a new custom character
* Go to Scenario tab
* Look at “Sortieren nach:” (“Sort by”)

Note the critical text which includes the sorting type has disappeared here

My guess is that it is possibly because of overwriting.

**Comment by Wuzzy2** [comment] 2018-04-14 11:24
This is not an enhancement request. :O
In German, some GUI text may become completely overwritten due to this bug, thus (partially) breaking the GUI just because you use German.

**Comment by illi-kun** [comment] 2018-04-14 12:38
It's not a bug because it works as intended (it just was created without thinking about translation, that's true).

It's either not a "suggestion" because it definitely have to be changed with no discussions.

So, I see only one tag applicable - 'enhancement' (in meaning of 'improvement').

**Comment by illi-kun** [comment] 2018-04-14 22:09
I've tried to run c:dda in German... you have to apply all of your translator's skills to shrink all in a 80x24 form; abbreviations, probably, should be your best friends.

**Comment by Night-Pryanik** [comment] 2018-04-15 03:30
I hope we soon forget about 80x24 as a scary dream and use a modern resolutions.

**Comment by Wuzzy2** [comment] 2018-04-15 14:47
@illi-kun: Yeah, but that's not always possible.
The fact that you can abbreviate words should not be a excuse not to try to improve the interface.

In this case one possible solution would be just to use an extra line. Like so:
```Sort by:
points (Press s to change)
```
(with “Press s to change” being directly appended to the previous strings, not placed at a hardcoded position)

**Comment by Night-Pryanik** [comment] 2020-02-03 09:28
I believe this was resolved by #27431.

**Closed by Night-Pryanik** 2020-02-03 09:28 UTC
Labels: <Bug>, <Enhancement / Feature>, Character / World Generation, Info / User Interface
