### ISSUE TITLE
Stomach and Condoms aren't filled with water

### ISSUE THREAD

**Issue by philipp-gaddi** [CleverRaven/Cataclysm-DDA#61685] opened 2022-10-14 11:36 UTC
### Describe the bug

Sealed Stomach or Condoms don't fill with water, when used as means from the "pour into container" option during examining a water source like the toilet. 

### Steps to reproduce

1. make a survivor in the default scenario with a condom or sealed stomach in his inventory
2. go downstairs to a toilet, examine it with a press on e
3. select pour into a container option
4. select condom or sealed stomach
5. observe log message: "you pour water into the sealed stomach. There's some left over"
6. check inventory and see the condom or sealed stomach is still empty. Check the toilet it still has 24 water.

### Expected behavior

I expect to have some units of water in the condom and those units are removed from the amount of water in the toilet.

### Versions and configuration

OS: Manjaro Linux
Version: 4bf05439a172529647ca4f41fbe7085f74edb6c1 (updated today 14.10.22)
Language: english
Mods: DinoMod, Bionic Profession, No Fungal Growth, Disable NPC needs, Dark Days Ahead
Sound: CC-Sounds
Tiles: Ultica

**Comment by utechenko-v** [comment] 2022-10-14 11:43
Seems to be duplicate of #61661

**Comment by philipp-gaddi** [comment] 2022-10-14 11:54
yes seem that way, should i delete this here? also it seems to works with siphoning gasoline, just not with water.

**Comment by Zireael07** [comment] 2022-10-14 12:05
@philipp-gaddi Issues can't be deleted, only closed

**Comment by philipp-gaddi** [comment] 2022-10-14 12:08
closed, being a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/61661

**Closed** 2022-10-14 12:10 UTC
Labels: (S1 - Need confirmation)
