### ISSUE TITLE
hallucinated npc dropped a real item

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61450] opened 2022-10-04 00:40 UTC
### Describe the bug

after hallucinating in one place for a long time, looking around the immediate surroundings I found a full mp 40 magazine in a strange spot. stranger still trying to take the item gives the "this would be stealing". as my player is above ground in an apartment complex the only logical way this item could have appeared I can think of is if it was dropped by a hallucinated npc.

### Steps to reproduce

hallucinate somewhere safe where npcs can't naturally appear for a very very long time.
look around for owned items that shouldn't exist

### Expected behavior

hallucinationed npc not dropping real items

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/193710003-307b6462-fd78-4f13-bcc9-02675c255705.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: aa80ff7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    No Hope [no_hope]
]

### Additional context

no idea when the magazine appeared. also it showed up on an indoor plant. the owner is:"No faction" apparently

**Comment by Night-Pryanik** [comment] 2022-10-04 05:34
Related to (or even a duplicate of) #58640.

**Comment by robotic-gamer** [comment] 2022-10-04 11:13
this is probably a duplicate then, should I close this then?

**Comment by Night-Pryanik** [comment] 2022-10-04 11:42
Ill close it for you.

**Closed by Night-Pryanik** 2022-10-04 11:42 UTC
Labels: (S1 - Need confirmation)
