### ISSUE TITLE
Wallets on scientists in labs contain ID cards

### ISSUE THREAD

**Issue by sharkfinsouperman** [CleverRaven/Cataclysm-DDA#49015] opened 2021-05-24 15:02 UTC
# Describe the bug

Wallets dropped by zed scientists in labs contain science ID cards. This trivialises the lab start because you no longer need to choose between grabbing the one in the finale room or dealing with a locked door at the exit.

Link to a player confirming the do drop ID cards;

https://www.reddit.com/r/cataclysmdda/comments/njiidc/comment/gz88tc9

# Steps To Reproduce

Kill zombie scientists until you find a wallet containing a science ID card.

# Expected behaviour

Expected behaviour is the player would have only one science ID card by the time they reach the exit.

# Versions and configuration

0.E ~~trunk, current stable build~~ current stable experimental build

**Comment by Zireael07** [comment] 2021-05-24 15:07
If you're on 0.E, try an experimental version. Lots of changes have been made since then and IIRC some involve science ID cards.

**Comment by pehamm** [comment] 2021-05-24 15:08
Not a bug? Where else should you find science ID cards if not in the wallet of scientists. One could fix this by making zombie scientists no longer spawn in labs (say, they evacuated in time), but they are already not guaranteed, I had lab starts in which I did not find scientists.

**Comment by SariusSkelrets** [comment] 2021-05-24 16:16
It doesn’t feel like a bug for me. I mean, they were the authorized personnel. It’s logical that they carry their ID with them

On the other hand, not all cards should have the same authorizations. Since there’s living quarters and a lot of food, we can assume that they were supposed to stay in for a long time.

The best way to keep secrets is to ensure that nobody can get out to tell them so the entrance door could only be opened by a high-ranked card not present on regular scientists. Their cards would open other doors in the lab (the doors next to consoles)

**Comment by Anaglyphic** [comment] 2021-05-24 17:19
Relevance is also given to any changes to loot modifiers in the world generation; since it's spawn is a % chance, if you set lootspawn to something ludicrous like 5.00x, the first scientist you kill will have literally everything, 3 pages of scientist loot, including multiple ID cards...

I get what you're saying sharkfinsouperman, I kind of agree, it's supposed to be difficult and/or suicidal. _(at least the first time, when turning a corner and a turret barks at you, that's an experience I wouldn't want to take away from a new player.)_ 

Not that this is a democracy but I vote for Sarius' solution, What about a simple C&P job on the zed JSON mon_zombie_lead_scientist_death_drops ? Then remove the possibility of an ID on regular scientists? Or perhaps a secondary ID badge. Regular id_science get you in the facility and maybe opens some doors or despawns the front door turrets, but the all-powerful id_science_highsec exists on only 1 or 2 lead scientists per lab?

**Comment by natsirt721** [comment] 2021-05-24 17:52
Currently, zombie scientists have a 5% chance to drop a wallet, and that wallet has a 100% chance to include a card. From a verisimilitude standpoint I agree that it makes sense that scientists ID cards, but I haven't played the lab start and can't speak to the trivialization of that scenario because of it. I would also be in favor of nerfing that 100% inclusion rate, perhaps to 50% or 20%. Remember that zombie scientists also spawn outside of labs and are a good (if not particularly reliable) source of science ID cards - I wouldn't just remove the drop altogether.

**Comment by Xaleth** [comment] 2021-05-24 17:58
This is a great issue for the Lab Rework over at github discussions

**Comment by sharkfinsouperman** [comment] 2021-05-24 18:28
Up until the introduction of wallets, not once did I walk out of a lab with more than the one science ID card found in the finale room.

Whether it's a bug or not, I don't think this issue was an intended change from the previous behaviour.

**Comment by Anaglyphic** [comment] 2021-05-25 01:49
Fair point, but it does present an opportunity to address the problem that, it's not canon with any "laboratory" story. Obviously in a secure lab, everyone has an access badge; security, janitorial staff, and yes scientists. The only people without them, well we won't discuss the victi... _volunteer test subjects_ as they would be "escorted" in.

If we need only 1 uberbadge per lab as part of the reward for survival, I don't think anyone will dispute that is a standard adventure game construct and is fine as-is, unless you want to make it more convoluted where you have to collect partial high-security access badges and assemble yours yourself to enter finale floor/room and leave, or something fun but that doesn't require a lot of retooling to implement and debug.

So it does present itself as a way to not only fix things "to make it like it was" but to fix things "to make it like it should be" I think is why Xaleth invited to jump on the discussion. :-)

**Comment by PatrikLundell** [comment] 2021-05-25 08:28
Whatever you come up with, keep in mind that most players don't play the lab start and the game still has to provide means for those players to get INSIDE labs from the outside (and lab starters may want to visit other labs once they get out, if for no other reason than to hunt down a working centrifuge [required for a quest]).

**Comment by Kelenius** [comment] 2021-05-25 10:16
I'm also pretty sure the scientists used to drop ID cards as a part of their normal drops.

**Comment by SariusSkelrets** [comment] 2021-05-25 16:37
> [...]provide means for those players to get INSIDE labs from the outside

That problem could be solved by adding lead scientist corpses at the surface as some escaped the labs

Lead scientist/hacker/demolition NPC could be a solution too. Willing to open the door/give you the capacity to open it if paid enough. Some might want to follow you to grab some loot and other might just want to make a quick trade and no risking their lives

**Comment by PatrikLundell** [comment] 2021-05-25 16:54
Having a guaranteed card outside every lab has two negative effects:
- It encourages newbies to go in and get killed way too early, as there's no (random chance) effort in getting the card.
- It cheapens the effort to enter science labs into triviality as you don't need to find a card elsewhere in the world, and there's absolutely no point in using demolitions or hacking to get in as all you have to do is take a quick look around the area and pick up the card, although I guess you'll have to do it the hard way if the card reader is broken (but I assume a broken card reader only leaves demolition/digging as entry options, but not hacking)...

**Comment by SariusSkelrets** [comment] 2021-05-25 17:03
I forgot to precise that the card could be anywhere in the world, not mext to the lab

The possibility of someone surviving the lab only to die next to it without even attempting to flee is so small these card-holding corpses could be simply removed from around the labs

Hub 01 have a mission about obtaining data from a dead person. This person could easily be a dead lead scientist, giving you more reasons to deal with the Hub as they’ll tell you where to find such card

**Comment by Kelenius** [comment] 2021-05-25 19:09
Id cards shouldn't be wildly difficult to find, given that electrohack isn't that difficult to make, and welder+grenade also provides an entrance.

**Comment by SariusSkelrets** [comment] 2021-05-25 20:36
This is why I suggested one being guaranteed at a Hub mission

IIRC, there will be a way to get the direction to Hub 01 (I don’t remember if it will be with refugee center or evac shelter) so there would be an easy way: 
get Hub position, reach it, complete the first mission, go to steal a dead man’s mind, take the card near the corpse

The fact that elecrohack is easy to create is another thing and blowing your way in exposes you to the turret (in the lab you can’t enter without card)

**Comment by Termineitor244** [comment] 2021-09-09 01:54
Huh, well, I am truly entering late to the conversation haha, but well...
First of all, the drop chance of a Science ID card was intentional, it was done in #35890 almost 2 years ago, with the rationale that, well, if you want to enter a lab, finding a scientist in the wild and taking its ID should be the way to go, and it was silly that not one of them carried its ID with them, so I gave them the same chance as the zombie soldiers, 5%, the wallets came later.

As I said when I made this change, the difficulty in the lab challenge should not come from having to go to a "Boss room" at the end to find a key to get out, but from something more organic/natural to a situation like that, like dealing with the security of the lab, the dead workers and escaped experiments, I like what curstwist did with the security tiered access for the modular labs, which is something like what @SariusSkelrets suggested in here, so there is that.

**Comment by actual-nh** [comment] 2021-09-09 03:25
Closing as out-of-date.

**Closed by actual-nh** 2021-09-09 03:25 UTC
Labels: <Suggestion / Discussion>, Spawn, (S4 - Invalid), <Exploit>
