### ISSUE TITLE
ALL category mutations chosen at character creation are now purifiable

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#53303] opened 2021-12-09 02:33 UTC
### Describe the bug

As of #53218 you can now purify starting mutations but I assumed that this meant that only "mutagen-exclusive" mutations were being removed, is this intentional? For example I took a starter character and spammed purifier, I lost my tentacle legs, far sighted, indefatigable, junkfood intolerance, fleet footed, etc. All that was left were category-less mutations such as optimist and strong back.

### Steps to reproduce

1. Create a (random) character.
2. Drink purifier.
3. Most starting traits disappear but some remain if they have no "category".

### Expected behavior

I was under the assumption that this behavior was for only mutations that were part of a category and not selectable at character creation, such as the mutations you obtain in the Experiment start. This leads to some weird behavior too, for example if you start with Optimist you cannot lose it to purifier because it belongs to no category but if you take Bad Temper purifier _can_ remove it because it belongs to bear and chimera. Also, Tentacle Arms are NOT purifiable if chosen at character creation because they don't actually belong to a category.

### Screenshots

![test](https://user-images.githubusercontent.com/56016372/145323781-3d1537f0-cab3-4715-8ab6-85fa483fb027.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d85abc7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

### Additional context

According to dseguin this is inentional, that does answer my question - but it still seems like very weird behavior as the line between "category" and "non-category" is extraordinarily arbitrary, see optimist vs bad temper above.

**Comment by dseguin** [comment] 2021-12-09 02:55
It looks like the comment you posted on the PR was removed, so I'll respond here:

> Hey so. This makes ALL "category" mutations removable with purifier. For example I took a starter character and spammed purifier, I lost my tentacle legs, far sighted, indefatigable, junkfood intolerance, fleet footed, etc. All that was left were category-less mutations such as optimist and strong back. Is this intentional behavior?

Yeah basically, anything that contributes towards a threshold is purifiable (except for mutations that are marked with `"purifiable": false`, see #53222)

I also noted this behaviour in the PR description so that whoever merged it was aware. I get the impression that the previous behaviour was unintentional? Hopefully someone who knows the background for this can correct me.

**Comment by anoobindisguise** [comment] 2021-12-09 02:56
Yeah I was just updating my context with that haha. I'm not sure if it's ideal behavior though, besides making dramatic balance changes to purifier and being somewhat arbitrary it seems like I'm not the only one misunderstanding this based on some comments in the discord.

**Comment by PatrikLundell** [comment] 2021-12-09 11:14
"Normal" non mutation traits ought not to be possible to purify away. If you start out near sighted, which is rather common and not considered a mutation in the real world, you shouldn't be able to purify it away, because it's not a mutation. If you mutate in a way that removes the trait (bird eyes, or whatever) and then purify that you should ideally get your starting trait back (as that's presumably what's in your genetic template, unless it was caused by an injury or infection). Obviously, you don't WANT to be near sighted, but you'd probably want to get positive traits back.
This probably means that traits may either need to be capable of being flagged as being a mutation, or have mutations and inherit traits being separate things internally. It might also be possible to store all non mutation traits in a list that's checked on purification so traits knocked out by purified mutations can be restored.
A distinction between a trait and a mutation may want you to assign a lower penalty credit to negative mutations than to the same negative traits, and a higher cost to positive traits than the same positive mutations.

**Closed** 2021-12-13 06:47 UTC
Labels: Mutations / Traits / Professions/ Hobbies
