### ISSUE TITLE
Spiders learned to open and close doors

### ISSUE THREAD

**Issue by Leosky** [CleverRaven/Cataclysm-DDA#31625] opened 2019-06-19 14:47 UTC
# Describe the bug
I entered a giant spiders cellar and left with door closed. Now they are going out of the cellar when i'm butchering the few i killed atop of the stairs. When i go downstair, doors are still intact and closed.

# Expected behavior
Spiders shouldn't be able to open/close door.

# Screenshots
https://i.imgur.com/qxXS5E2.png
https://i.imgur.com/H3zCFSC.png

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-4674-g2e5c67a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    Folding Parts pack [deoxymod],
    Larger Vehicules Containers [LargerVehiculesContainers],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Classic Roguelike Classes [RL_Classes]
]

# Additional context
[spider_bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3306621/spider_bug.zip)

**Comment by coshxx** [comment] 2019-06-19 22:24
Not sure if related but I had a similar experience with giant wasps. I managed to lock one out in a closed bathroom and waited for a while, suddenly it was next to me? The door was still closed tho. Maybe they can pass through obstacles becausw of their high movement speed or something idk.

**Comment by anothersimulacrum** [comment] 2019-06-20 00:06
Your experience may have been the wasp flying over the walls because the building you were in did not have a roof.

**Comment by Amoebka** [comment] 2019-06-20 17:19
Do you have experimental Z-levels enabled? Monsters seem to teleport between Z-levels without using stairs with that setting on. It has been like this for a while and happens with all monsters (including secubots in labs...), it has nothing to do with spiders or doors.

**Comment by Leosky** [comment] 2019-06-20 17:20
Yes, z on, so i guess it's this issue too

**Comment by Saicchi** [comment] 2021-04-03 02:42
Does this still happen? I'm on ` 0.E-10134-g9b256f63cd [64-bit]`. I surronded two spiders with doors and waited an entire day, the doors did not open. It could be something to do with roofs as anothersimulacrum said, or maybe in older versions wandering hordes moved the spiders too.

**Comment by Night-Pryanik** [comment] 2021-04-03 03:15
Ok, closing until reconfirmed.

**Closed by Night-Pryanik** 2021-04-03 03:15 UTC
Labels: <Bug>, Monsters
