### ISSUE TITLE
Foldable solar panel

### ISSUE THREAD

**Issue by CucingGit** [CleverRaven/Cataclysm-DDA#75179] opened 2024-07-23 03:30 UTC
### Describe the bug

Where you place a foldable solar panel, the error massage was seen, after it, when you tried disassemble it - you recieve original foldable solar panel, and addition one.

### Attach save file

N/A

### Steps to reproduce

Place a solar panel case and disassemble it after

### Expected behavior

Error massage, duplicate a solar panels

### Screenshots

![image](https://github.com/user-attachments/assets/834e7831-745f-4863-9465-7dc1701cd32d)
![image](https://github.com/user-attachments/assets/615f0569-4801-4e45-b304-bcb97d8b3b15)

### Versions and configuration

Windows 10, aa5d1b1-tiles (it was in previous version too)

**Comment by Alm999** [comment] 2024-07-23 06:26
Most probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/73976

**Comment by CucingGit** [comment] 2024-07-23 06:30
Yup, it's the same

**Comment by SurFlurer** [comment] 2024-08-29 12:45
Fixed by  #75397

**Comment by Brambor** [comment] 2024-09-01 08:44
Agreed.

It was a `folding solar panel` (not foldable) and `Take down appliance` duplicated the item before the fix.

**Closed by Brambor** 2024-09-01 08:44 UTC
Labels: (S1 - Need confirmation)
