### ISSUE TITLE
Game Crashes on Enemy Death

### ISSUE THREAD

**Issue by Havok91** [CleverRaven/Cataclysm-DDA#64545] opened 2023-03-25 04:05 UTC
### Describe the bug

Any time I kill an enemy, game crashes

VERSION: d98a4cc
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
[crash CDDA.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/11067924/crash.CDDA.txt)

### Attach save file

[Nighthawk-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11067933/Nighthawk-trimmed.tar.gz)

### Steps to reproduce

1. Kill anything

### Expected behavior

I expected enemy to die and not crash game. I believe it may have to do with achievement system however, as that is the only commonality I can find after reproducing the issue multiple times.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 67d9253 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11067934/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11067935/debug.log)

**Comment by Wyghab** [comment] 2023-03-25 05:35
This is also related to achievements, you can workaround this crash by loading achievements by opening the achievement menu, or removing achievement popup in the settings.

**Comment by Havok91** [comment] 2023-03-25 16:09
Thanks for the solutions, I did note that in my expected behavior segment, as it was the only commonality I could find after reproducing the crash several times.

**Comment by anothersimulacrum** [comment] 2023-03-25 17:36
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/64466

**Closed by anothersimulacrum** 2023-03-25 17:36 UTC
Labels: (S3 - Duplicate)
