### ISSUE TITLE
Hitting a turkey with bolas despawns the turkey

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#51213] opened 2021-08-29 20:05 UTC
### Describe the bug

Hitting a turkey with bolas despawns the turkey after several moves.

### Steps To Reproduce

1. Create a character with decent throwing skill.
2. Acquire bolas and spawn a turkey.
3. Throw bolas at turkey.
4. The turkey will either flee (bolas did not engage), or remain in place and disappear after skipping two moves. The bolas will remain in the square.

### Expected behavior

The turkey should remain immobilized. If the impact is enough to kill it, there should be at least a sign of this happening, like a turkey corpse or ludicrous gibs. If the complete and utter annihilation of the turkey is the intended result (e.g., bolas composed of anti-matter), the resulting mass-to-energy conversion should result in a smoking hole in the ground, and, likely, a game over.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 506dd5b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by dseguin** [comment] 2021-08-30 04:50
I can't seem to reproduce this on `0.F-2195-g85a9936e7c` (latest pull from master as of now)

![bolas_hit](https://user-images.githubusercontent.com/12537966/131286637-6b62cbf0-9534-4713-b4f1-785bb7be879e.png)
![turkey](https://user-images.githubusercontent.com/12537966/131286646-2462504b-c71c-459d-8ff1-c84f798acb82.png)

**Comment by DalenTalas** [comment] 2021-08-30 13:49
Fair enough, seeing that I can't recreate this in a test game either.

So, either something is glitchy with my main save. Or, the thrown bolas startle the turkey, and it flees off-screen, or possibly up a Z-level. Problem with that is that I can't locate it again within the range of several screens.

**Comment by Brambor** [comment] 2021-08-30 14:31
> Either way, turkeys apparently do not like birdseed, so my villainous plan of building a turkey farm is now moot.

You can give bird_seeds to turkey chicks thought. I have turkeys tied on the roof because chicks cannot cross my chick_fence, but turkeys fly over it.

**Comment by hexagonrecursion** [comment] 2022-01-04 12:07
> I can't seem to reproduce this on `0.F-2195-g85a9936e7c` (latest pull from master as of now)
> 
> ![bolas_hit](https://user-images.githubusercontent.com/12537966/131286637-6b62cbf0-9534-4713-b4f1-785bb7be879e.png) ![turkey](https://user-images.githubusercontent.com/12537966/131286646-2462504b-c71c-459d-8ff1-c84f798acb82.png)
> 
> As you can see, the turkey is clearly still on this plane of existence.

Same here. This should be closed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by wapcaplet** [comment] 2022-01-17 03:42
Closing per above comments.

**Closed by wapcaplet** 2022-01-17 03:42 UTC
Labels: (S1 - Need confirmation), Monsters, Ranged
