### ISSUE TITLE
"Profession" zombies generally spawn nearly completely nude

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#62670] opened 2022-12-10 16:43 UTC
### Describe the bug

The `professional_zombie_gear` item group, while intended to let zombies spawn with clothing sets specific to certain professions (i.e. a full set of mailman's gear, or a set of work clothes) cites item groups that are distributions, rather than collections, and are specifically written in order to function as such. This means that if the game rolls that group for a zombie, they'll frequently spawn with a single piece of clothing or no clothing at all.

This seems to have been around since #58651.

### Steps to reproduce

1. Skew up the drop rate of `professional_zombie_gear` for reproducing purposes (`zombie_default.json`, line 276).
2. Kill a buncha zombies.
3. See that items spawn nude or close to nude, which is rather silly.

### Expected behavior

"Profession" zombies should spawn with full sets of appropriate clothes and items, instead of just a single piece of relevant clothing.

### Screenshots

![cataclysm-tiles_giemfUEXUz](https://user-images.githubusercontent.com/47678781/206865690-e70b3794-b1f0-4220-bba8-23e0205ebb40.png)
![cataclysm-tiles_yuvFJukKoU](https://user-images.githubusercontent.com/47678781/206865691-487a8dc4-c45c-4092-988f-028198cb5c99.png)
![cataclysm-tiles_rmAoqxlGpQ](https://user-images.githubusercontent.com/47678781/206865692-6b7551e8-0528-4062-9c32-ade0fafac074.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 0.F-12755-gf9cc1b1a43-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

This could likely be fixed by adding purpose-made collection item groups for the relevant clothes and items, instead of using existing item groups that aren't meant to be used in that way.

**Comment by mqrause** [comment] 2022-12-10 16:52
Related to/kind of but not really a duplicate of #59873.

**Comment by Ilysen** [comment] 2022-12-10 16:54
It seems like that error probably shows up because of this error, so they're interlinked. bwuh

**Comment by mqrause** [comment] 2022-12-10 17:31
/confirmed

The thing is, you can fix this issue here, but still have the occasional CI error persist, so while they have a lot of overlap, they're definitely not exactly the same. Though I guess the combination of this and the more general item group distribution issue #62446 cover everything I said in the other issue, so might as well close that one. Apparently the issue exists for more than just `plumbing_clothing` anyway, so it wasn't super accurate in the first place.

**Closed** 2023-01-07 02:40 UTC
Labels: (S2 - Confirmed)
