### ISSUE TITLE
Cannot create world

### ISSUE THREAD

**Issue by rabidradioactiveraccoons** [CleverRaven/Cataclysm-DDA#32405] opened 2019-07-15 12:34 UTC
# Describe the bug

Whenever attempting to create a world, regardless of mods used, upon finalizing world, I receive the messages such as:

Failed to write options to "./config/options.json": moving temporary file "./config/options.json.27840.temp" failed
Failed to write world data to "./save/[world name]/worldoptions.json": moving temporary file "./save/[world name]/worldoptions.json.27480.temp" failed

The world is not created after receiving these messages. This occurs also if I attempt to launch the Defense game mode.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-5672-g4eb9f72
 - Graphics version: Terminal
 - Mods loaded: Problem occurs regardless of whether or not I am attempting to load mods

**Comment by ZhilkinSerg** [comment] 2019-07-15 12:38
Duplicate of #32401

**Closed by ZhilkinSerg** 2019-07-15 12:38 UTC
Labels: (S3 - Duplicate)
