### ISSUE TITLE
Buggy ladder near the pawn shop

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32054] opened 2019-07-02 05:19 UTC
# Describe the bug

You're just slammed against the ground when you try to climb it.

[2019.06.28-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3348412/2019.06.28-2.zip)

0.D-5165-g5122325667

**Comment by Night-Pryanik** [comment] 2019-07-02 06:31
It would help a lot if you provide a screenshot of pawn shop in question, as there are several types of them, you know.

**Comment by l29ah** [comment] 2019-07-02 08:45
![](https://pstbin.ru/f/38768/)

**Comment by Night-Pryanik** [comment] 2019-07-02 09:38
Tested right now on latest experimental - can't confirm. I was able to successfully climb the ladder up and down.
![123456](https://user-images.githubusercontent.com/11132525/60502287-934cf100-9cce-11e9-9648-15b0b7052628.gif)

**Comment by l29ah** [comment] 2019-07-02 09:41
Have you tested my saved game?

**Comment by Night-Pryanik** [comment] 2019-07-02 09:46
No. I've tested it on a brand new world with a brand new character. It looks like the issue is in your world.

**Comment by Night-Pryanik** [comment] 2019-07-02 09:50
Tested your save. The roof of this pawn shop in question isn't generated for some reason.
I found another pawn shop like this in other place (in your world), and it has its roof correctly generated. I guess this issue could be closed.

**Comment by curstwist** [comment] 2019-07-02 12:58
If you revealed this specific pawn shop before the roof was added, but didn't approach it close enough (so the actual building generated) I think the ground floor will generate the new layout but the roof won't be added.  It's more of an issue about how the map generates the levels and when.  Does this fit your scenario?

**Comment by l29ah** [comment] 2019-07-02 13:01
Yes, this sounds very much like what have happened.

**Comment by curstwist** [comment] 2019-07-02 13:37
Fixing that is beyond my capabilities, but at least you can be aware now.  

Best practice is to not update during an in progress game, wait until you start a new game.  Or, generally be aware which roofs are new and beware of ascending them in pre-explored/revealed areas.

**Comment by KorGgenT** [comment] 2019-07-03 14:08
i'm closing this because it sounds like it's not really a bug, as much as it is something that'll happen during the Great Roof Update of 2019

**Closed by KorGgenT** 2019-07-03 14:08 UTC
Labels: (S1 - Need confirmation), <Bug>, Mapgen
