### ISSUE TITLE
Rigid table manners doesn't work in vehicles

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#45440] opened 2020-11-15 18:31 UTC
# Describe the bug

Eating in a car seat next to a workbench still gives the ate like an animal debuff.

# Expected behavior

The workbench says in the description that it would make a nice surface to eat on, a seat in a car is also as good as any to eat at.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-7560-g165a25c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Shard's Additions [shardstuff],
    Gun Cotton [guncotton],
    Graphical Overmap [Graphical_Overmap],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP]
]

**Comment by ZhilkinSerg** [comment] 2020-11-15 19:28
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/45240

**Closed by ZhilkinSerg** 2020-11-15 19:28 UTC
