### ISSUE TITLE
Fencing's Counter Attack Stacks Without Limit

### ISSUE THREAD

**Issue by Substance455** [CleverRaven/Cataclysm-DDA#15475] opened 2016-02-19 08:11 UTC
Credit to Mightyagrippa on IRC for confirming this with me.

Fencing has a counter attack that makes multiple attacks.
This stacks without limit, meaning you could do it for hours.
This locks you in place permanently, till all the adjacent enemies are dead.
And if they don't kill you in this string, there's a possibility you might starve/dehydrate/freeze to death.

**Comment by mightyagrippa** [comment] 2016-02-19 08:16
To replicate,
Turn on debug invincibility or equip any armor set immune to normal zombie attacks,
turn on fencing style,
equip a fencing weapon (rapier or broadsword is the norm),
debug in several hundred zombies around you,
attack and enjoy

Having to counterattack vs 100+ zombies is actually a valid case, the necropolis can get real real wild.

**Comment by Coolthulhu** [comment] 2016-02-19 08:27
Duplicate of #15101

**Comment by BevapDin** [comment] 2016-02-27 22:09
The duplicate was closed as fixed, so shall this.

**Closed by BevapDin** 2016-02-27 22:09 UTC
Labels: Duplicate
