### ISSUE TITLE
Delay when opening Examine Vehicle screen and navigating

### ISSUE THREAD

**Issue by Clast** [CleverRaven/Cataclysm-DDA#75099] opened 2024-07-19 03:19 UTC
### Describe the bug

'Examine Vehicle' screen takes 1-3 seconds to load. Once opened, moving the cursor from one tile to the next takes 1-2 seconds between moves. 

### Attach save file

[Goldsboro-trimmed.tar.gz](https://github.com/user-attachments/files/16301518/Goldsboro-trimmed.tar.gz)

### Steps to reproduce

Player spawns next to a vehicle. 'e'xamine the tile immediately to the west then 'e'xamine the vehicle.

### Expected behavior

Vehicle menu should open instantly and should not have a noticeable delay, should also be no delay when looking at different tiles on the Examine Vehicle screen.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-07-18-1929 83ac2a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter]
]

### Additional context

Loaded the same save with Xedra & Mind Over Matter removed from mods.json - issue persisted.

When loading the same save in 2024-07-18-0220, no delay encountered.

**Comment by harakka** [comment] 2024-07-19 05:57
Duplicate of #75085

**Closed by harakka** 2024-07-19 05:57 UTC
Labels: (S1 - Need confirmation)
