### ISSUE TITLE
Atomic tool mod can't be unloaded or removed

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19534] opened 2016-11-28 21:04 UTC
While unloading could be considered bad (atomic tool stores 1 liter of plutonium cells), it should be possible to at least take the whole mod and put it in different tools while retaining charges.

At the moment it is not possible to remove the atomic battery mod from a tool for as long as it is loaded. Except maybe by breaking the tool.

**Comment by mugling** [comment] 2016-11-28 22:20
Whilst I agree with you this is pretty difficult to implement without a lot of internal refactoring. Once we have tools using actual batteries then atomic battery becomes just another type of battery?

**Comment by saneman226** [comment] 2016-11-30 01:21
I always thought of this problem as more of a safety hazard for the player, removing a fully active plutonium cell from the device. I never really thought of it retaining its charge like this. 

Perhaps the ammo for the mod could simply be battery charges like regular items, but only allow fueling via plutonium cells. It would keep the consistency of power for most items as well as implement the idea of having the mod retain its charge.

**Comment by kevingranade** [comment] 2017-04-02 22:44
It's certainly not a bug, it's working as intended, it's more a feature request, and I'm not sure if what you propose is the behavior we want.

**Comment by Night-Pryanik** [comment] 2019-04-06 13:33
No discussion in a very long time, closing.

**Closed by Night-Pryanik** 2019-04-06 13:33 UTC
Labels: <Enhancement / Feature>, Battery, Gunmod / Toolmod
