### ISSUE TITLE
Crafting certain items with High Quality Lens will infinitely consume material

### ISSUE THREAD

**Issue by chriseich21** [CleverRaven/Cataclysm-DDA#33770] opened 2019-09-02 18:30 UTC
# Describe the bug
Crafting a bow scope or survivor telescope and substituting a regular high quality lens for small one will show prompt that you are missing a material and to use a different material, however once you select the replacement it will continuously popup and every click consumes more. 

# Steps To Reproduce
1. Debug spawn all material for a survivor telescope or bow scope and have extra normal high quality lens. 
2. Be provided with prompt to use replacement material
3. Click to replace, be asked again, and again, and again until you are out of lenses. 

# Expected behavior
The recipe should use the material that is part of the recipe (separated by OR on recipe) correctly. 

# Screenshots
![Screenshot_20190902-112922_Cataclysm DDA](https://user-images.githubusercontent.com/18540501/64130089-f3b2ea00-cd74-11e9-8cef-aba0891a3fa5.jpg)

# Versions and configuration

 - OS: Android 9.0
- Game Version: Build 9577 (version 0.D-7213-ga0159bf)
- Graphics version: Tiles
- Mods loaded: [DDA, CRIT Exp, Garden Pots, Makeshift Items, Medieval and Historic, More Survival Tools, Mythological Replicas, Dinomod, Modular Turrets, Salvaged Robots, Alt Map Key, EZ Medical, Hydroponics, Beta National Guard, More Locations, Fujis More Buildings, Urban Development, Folding Parts, Vehicle Additions, Tanks and Other, Necromancy]

**Comment by chriseich21** [comment] 2019-09-02 18:48
Also, there is no way to cancel a begun construction so you're stuck either replacing your materials with debug or basically cry lol. Would be a nice future feature, could use Disassemble time multiplied by percent compete or something on an "in progress" item

**Comment by ZhilkinSerg** [comment] 2019-09-02 22:12
Duplicate of #32311

**Closed by ZhilkinSerg** 2019-09-02 22:12 UTC
Labels: (S3 - Duplicate), <Bug>, Crafting / Construction / Recipes

**Comment by chriseich21** [comment] 2019-09-03 14:33
> Duplicate of #32311

Damn, my bad! I didn't go that far back and was on mobile, thought it was a new issue.
