### ISSUE TITLE
Mass spawn of aphids near triffids, with innawood?!

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#69678] opened 2023-11-23 15:11 UTC
### Describe the bug

The map is full of aphids.
I can kill them via debug menu, but they respawn the next turn.

![Brian Wesly _2023-11-23T15-52-56](https://github.com/CleverRaven/Cataclysm-DDA/assets/69985946/f05e4b83-d13d-4afd-b846-f75dce4d5696)

### Attach save file

[Wald-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13451446/Wald-trimmed.tar.gz)

### Steps to reproduce

Dont know, if have just seen it in my actual game innawood

### Expected behavior

There cant be so much aphids, they bring my pc to its knees.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: c5b5515 [64-bit]
- Graphics Version: Tiles
- Game Language: Systemsprache []
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by BrettDong** [comment] 2023-11-23 15:13
Duplicate of #69610?

**Comment by BjoHart** [comment] 2023-11-23 15:16
Looks like this

**Comment by RenechCDDA** [comment] 2023-11-23 15:16
Duplicate of #69610

**Closed by RenechCDDA** 2023-11-23 15:16 UTC
Labels: (S1 - Need confirmation)
