### ISSUE TITLE
NPC Stuck in slow loop being unable to find tools

### ISSUE THREAD

**Issue by haveric** [CleverRaven/Cataclysm-DDA#54920] opened 2022-01-29 23:58 UTC
### Describe the bug

I assigned 5 npcs to deconstruction work with a gunsmith repair kit on the ground (under middle guy in white). After deconstructing a couple items, one of the npcs (top right pictured) appears to be getting stuck in a loop of not being able to find the tools 100x per turn, which causes a massive slowdown to the game, causing turns to take 30-40 seconds.

### Steps to reproduce

1. Load save in additional context
2. Try moving
3. Wait for game to respond and note log of Vesta Priest trying to find the items

### Expected behavior

Turns to not crawl to a halt while trying to utilize npcs.

### Screenshots

Deconstructing in a mansion:
![image](https://user-images.githubusercontent.com/985060/151681112-61bd74c8-78ea-41f5-92fb-56fe12ae582b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1bba9b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

[Save file](https://drive.google.com/file/d/1TbC671OQBc6IVaEcXqofjTFCIAGJlTyN/view?usp=sharing)

**Comment by dseguin** [comment] 2022-01-30 00:09
Looks like a duplicate of #52283

**Comment by haveric** [comment] 2022-01-30 00:21
> Looks like a duplicate of #52283

It does look like a similar issue. Is it worth keeping this one because I have a repeatable test case or should I move information over to that one?

**Comment by dseguin** [comment] 2022-01-30 00:31
Mentioning an issue will create a link, so someone browsing issue #52283 will see a link to this one, even if it's closed.

**Closed** 2022-02-04 03:45 UTC
