### ISSUE TITLE
Cant launch game

### ISSUE THREAD

**Issue by AlejandroUriarte** [CleverRaven/Cataclysm-DDA#56831] opened 2022-04-16 00:48 UTC
### Describe the bug

Last week my game was working just fine then after trying to launch today the game automatically closes.

I get returned to the launcher with the notification game process has ended.

Version 84f3a1a
Windows 10

I’ve tried:

-Launching from exe: It just doesn’t start
-Launching the exe as administrator: wont start
-Using launcher with exe set to start as administrator: get an error about anivirus, i only use windows defender.
-Whitelisted exe and folder on defender and it still wont work
-full reinstall
-tried launching to prev version
-changing main file locations

Any thoughts you guys might have would be appreciated.

Like I said earlier, game was working fine a week ago, now it refuses to boot up.

### Steps to reproduce

Everytime i launch

### Expected behavior

Game used to work fine a week ago

### Versions and configuration

Windows 10, updated version of CDDA through Launcher

**Comment by pierredavidbelanger** [comment] 2022-04-16 02:22
I, too, cannot play with my own linux release build of [the latest commit](https://github.com/CleverRaven/Cataclysm-DDA/commit/8af3a1abcd6bf896da5a8a2b2d7adc00ff07aef9).

It runs OK if I build with `RELEASE=0`

But this build will ends with a segfault :

```
make install -j12 \
    PREFIX=/usr/ \
    NATIVE=linux64 \
    RELEASE=1 \
    LTO=1 \
    LOCALIZE=0 \
    USE_HOME_DIR=1 \
    TILES=1 \
    SOUND=1
```

Here is the gdb ouput anyways, hope it makes sense even if in release mode:

```
$ gdb cataclysm-tiles 
GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cataclysm-tiles...
(No debugging symbols found in cataclysm-tiles)
(gdb) start
Temporary breakpoint 1 at 0x22b7ed
Starting program: /usr/bin/cataclysm-tiles 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555f4a480 in Name::get[abi:cxx11](nameFlags) ()
(gdb) bt
#0  0x0000555555f4a480 in Name::get[abi:cxx11](nameFlags) ()
#1  0x0000555555ffcadd in city::city(coords::coord_point<point, (coords::origin)4, (coords::scale)2> const&, int) ()
#2  0x0000555555811ee3 in __static_initialization_and_destruction_0(int, int) [clone .constprop.122] ()
#3  0x000055555594d151 in _sub_I_65535_0.0 ()
#4  0x00007ffff78950fd in call_init (env=<optimized out>, argv=0x7fffffffdf78, argc=1) at ../csu/libc-start.c:145
#5  __libc_start_main_impl (main=
    0x55555577f7e5 <main>, argc=1, argv=0x7fffffffdf78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf68)
    at ../csu/libc-start.c:379
#6  0x000055555594dd05 in _start ()
(gdb) 
```

**Comment by JReese3** [comment] 2022-04-16 02:42
Same Issue, wasn't a problem with 4-15-0500, Can't launch from launcher or fresh unzip of later versions.

**Comment by TheShadowFerret** [comment] 2022-04-16 02:58
Duplicate of #56813?

**Comment by BrettDong** [comment] 2022-04-16 04:11
> Duplicate of #56813?

Exactly.

**Closed** 2022-04-16 04:11 UTC
Labels: (S3 - Duplicate)
