### ISSUE TITLE
Reloading Headlamp Crashes Game [Crash/Freeze]

### ISSUE THREAD

**Issue by BrokenPaw-0-1** [CleverRaven/Cataclysm-DDA#42148] opened 2020-07-15 05:29 UTC
# Describe the bug

Why you attempt to reload a light, disposable battery into a headlamp it causes a SEG FAULT.
Then the game crashes, Thanos snapping your CBMs you just found into dust.

# Steps To Reproduce

1.) Find headlamp inside lab.
2.) Reload battery into headlamp.
3.) Try not to cry, cry a-lot as your game Segfaults.

# Expected behavior

Batteries reloading into a headlamp and not segfaulting.

# Screenshots

n/a

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4112-g5837d3f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Here's the debug log, crash log, and save file.

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4923061/crash.zip)
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4923062/debug.zip)
[Hoskinston1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4923064/Hoskinston1.zip)

**Comment by ZaricaDemoni** [comment] 2020-07-15 06:58
Duplicate of #42089

**Closed** 2020-07-15 08:02 UTC
Labels: (S3 - Duplicate)
