### ISSUE TITLE
Glass jar with unknown charges in tin recipe

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#24685] opened 2018-08-07 19:15 UTC
Windows, tiles, 0.C-29661-g765578f.

Tin recipe requiring glass jar/3l jar with unknown charges which seem to be unobtainable.
![cata_tin](https://user-images.githubusercontent.com/2755776/43796853-f3b4649a-9a74-11e8-9c9d-3fb880857365.png)

https://github.com/CleverRaven/Cataclysm-DDA/blob/d86ae7270b0f92aab8176d15ad9b46283eb27ef5/data/json/recipes/other/materials.json#L42

Charge amount probably should be -1 for jars here?

**Comment by DracoGriffin** [comment] 2018-08-07 19:54
Confirmed bug.

Additionally, changing to -1 as @maniak1349 states is the correct fix.

Since you figured it out the fix maniak, you could make a PR resolving this issue.

**Closed** 2018-08-15 16:56 UTC
Labels: (S2 - Confirmed), <Bug>, Crafting / Construction / Recipes
