### ISSUE TITLE
Steel spear (probably all spears) diagonal attack bug

### ISSUE THREAD

**Issue by Neversalimus** [CleverRaven/Cataclysm-DDA#19258] opened 2016-11-12 20:13 UTC
By pressing F key, you can only attack diagonally adjacent enemy(near you), but pressing Tab you can also attack enemy 1 diagonal tile away, which otherwise is not possible if you press F key.

**Comment by Reclusive-reptile** [comment] 2016-11-13 04:36
Circular distances cause this bug. Every time it's been brought up no one has  one up with a good solution.

**Comment by Neversalimus** [comment] 2016-11-13 07:23
ahh sorry for  duplicating(

**Comment by DangerNoodle** [comment] 2016-11-13 20:42
Does it work as expected if circular distance is disabled? The obvious solution would be for circular distance to explicitly not affect reach attacks.

**Comment by Leland** [comment] 2017-05-24 19:07
Duplicate of #16400

**Closed by Leland** 2017-05-24 19:07 UTC
Labels: Bug
