### ISSUE TITLE
Several issues with new encumbrance system and tailor kit upgrades

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#11890] opened 2015-04-02 18:19 UTC
After upgrading from 0.C to experimental and the immediate shock of having to drop half my armor in order to be able to do anything, I do agree that the changes were needed and seem mostly logical, however, there are a few issues that i stumbled across. 

The biggest one is how "layers easily" behaves. As far as I can tell, if an item has the VARSIZE flag and has a BASE encumbrance 0, it will layer easily.

So let us take socks as an example. The default crafted socks start out with 0 encumbrance and therefore layer easily. Now i make them fit, which brings their actual value to -10 (the game still displays them at 0 though). Now I add some leather padding, which brings the actual value to -3. However, as soon as I do this, the socks will no longer layer easily. The same is true for every item in the game. Even if an item still has negative actual encumbrance, if it is upgraded with leather or kevlar, it will no longer layer easily. Imo, this behavior should be changed so that as long as the actual encumbrance value is below 0, it will layer easily no matter what (as long as the item has a VARSIZE flag of course).

What makes matters even worse is that an item will only layer easily, if BASE encumbrance of the item is at 0 to begin with. The effect of this is that I guess about 70% of all items that layered easily back in 0.C do not do so any longer. 

<strong>tl;dr: an item will only layer easily if these three conditions are met: 1) the item has the VARSIZE flag. 2) the item has 0 BASE encumbrance (fitting is irrelevant). 3) the item must not have been improved by the tailors kit, even if this does not result in encumbrance above 0 (making an item sturdy is ok, but no material upgrades)<strong>

Imo, all this results in a severely more restricted possible loadout for your char, especially compared to the last stable version. The difference in viable armor setup is staggering and should at least be somewhat mitigated by changing layers easily so that it will layer as long as actual encumberance (rather than base enc) is 0. Especially during the winter months, the change since 0.C is very detrimental, as you can no longer easily layer 2 pairs of wool socks, or 2 long underwear sets, as those items no longer layer easily now). 

Also, the tailor kit menu should tell you what each upgrade does in item stats. In fact, at the moment, as long as you don't like write down the exact values of an item and then upgrade it to compare, there is no way to see what just happened (which makes using the tailoring kit both potentially "dangerous" as encumbrance can easily get out of hand, and also makes it feel unrewarding since you can't easily see the benefits). 

At last, tailor kit upgrades should be reversible.

**Comment by kevingranade** [comment] 2015-04-03 01:56
If anything has negative encumbrance, it is a bug.  The behavior you're
describing is the code working as intended, patches on clothes don't
benefit from fitting.

**Comment by KA101** [comment] 2015-04-04 00:56
More bluntly, retrofitting armor/insulation into a garment is gonna make it no longer fit/layer as easily as it did unaltered.  That's realistic and, as Kevin noted, quite intentional.

**Comment by KA101** [comment] 2015-04-04 00:58
I'm gonna close this and ask that you break it up: the need for better winter gear may be worth considering, as are the forecasting/reversibility requests for the tailor kit.

But the bolded tldr portion is working as intended.

**Closed by KA101** 2015-04-04 00:58 UTC
Labels: Balance
