### ISSUE TITLE
Segmentation Fault - Vehicle 

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#30100] opened 2019-04-30 00:07 UTC
Describe the bug
I was just walking into a town after pulping some corpses and it crashed, perhaps a zombie hit a vehicle?
  
See screenshot.

To Reproduce
N/A - unknown.

Expected behavior

N/A - Not to crash?

Screenshots
![image](https://user-images.githubusercontent.com/5264667/56934358-88fe5300-6ae3-11e9-82b0-ba9955df29e9.png)

Versions and configuration(please complete the following information):

OS: Win7 64bit
Game Version: 0.D-2396-g1b60b95
Graphics version: [Tiles chesthole32]
Mods loaded: [ "dda", "Medieval_Stuff", "More_Survival_Tools", "Packaging", "RL_Classes", "SD_Magcrafting", "StatsThroughSkills", "blazemod", "Tanks", "Urban_Development", "ZSFIXED_cddaxp", "boats", "craftgp", "deoxymod", "ew_pack", "filthy_morale", "makeshift", "more_classes_scenarios", "mutant_npcs", "national_guard_camp", "no_npc_food", "npc_traits", "realguns", "Tolerate_This", "modular_turrets", "Salvaged_Robots", "Bootleg_Walkers", "DracoDogMod", "DP_AMAZING_CHEST_INDICATORS", "aftershock", "SD_Magcrafting_Realguns_Extension", "Arcana", "more_locations", "FujiStruct", "Uekibati_mod" ]

Additional context

[Game 53.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3129563/Game.53.zip)

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2396-g1b60b95
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x562825[cataclysm-tiles.exe+0x162825]
    @0x5632F2[cataclysm-tiles.exe+0x1632F2]
    SMPEG_error+0x4B034@0xE4F1D0[cataclysm-tiles.exe+0xA4F1D0]
    _C_specific_handler+0x8C@0x776B7398[ntdll.dll+0x57398]
    _chkstk+0x9D@0x776CBF9D[ntdll.dll+0x6BF9D]
    RtlInitializeResource+0x53A@0x776A04CA[ntdll.dll+0x404CA]
    KiUserExceptionDispatcher+0x2E@0x776CB63E[ntdll.dll+0x6B63E]
    IMG_LoadWEBP_RW+0x4081B5@0x13491F5[cataclysm-tiles.exe+0xF491F5]
    @0xD31FAC[cataclysm-tiles.exe+0x931FAC]
    @0xD3233A[cataclysm-tiles.exe+0x93233A]
    @0xD32C10[cataclysm-tiles.exe+0x932C10]
    @0xD3336D[cataclysm-tiles.exe+0x93336D]
    @0xD3375D[cataclysm-tiles.exe+0x93375D]
    @0xD33D2B[cataclysm-tiles.exe+0x933D2B]
    @0x861FDC[cataclysm-tiles.exe+0x461FDC]
    @0x86FF12[cataclysm-tiles.exe+0x46FF12]
    @0x9AB6DB[cataclysm-tiles.exe+0x5AB6DB]
    @0x9AFC44[cataclysm-tiles.exe+0x5AFC44]
    @0x686C29[cataclysm-tiles.exe+0x286C29]
    @0x688CF7[cataclysm-tiles.exe+0x288CF7]
    IMG_LoadWEBP_RW+0x4FB058@0x143C098[cataclysm-tiles.exe+0x103C098]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x774559CD[kernel32.dll+0x159CD]
    RtlUserThreadStart+0x1D@0x776B383D[ntdll.dll+0x5383D]

**Comment by neitsa** [comment] 2019-05-02 16:31
Duplicate of #28156

**Closed** 2019-05-02 16:49 UTC
Labels: <Bug>, <Crash / Freeze>, Vehicles
