### ISSUE TITLE
Rock Forge does not consume charcoal and gives an error screen every time I want to forge something

### ISSUE THREAD

**Issue by Kordian459** [CleverRaven/Cataclysm-DDA#44021] opened 2020-09-07 10:45 UTC
# Describe the bug
An error screen appears every time I try to craft something with my Rock Forge. After I ignore (I) the error the game proceeds to craft the chosen item anyway but doesn't use any charcoal charge inside my Rock Forge, allowing me to craft without charcoal usage.

# Steps To Reproduce

1. Make a Rock Forge
2. Charge it with Charcoal 
3. Start to craft an item with it
4. error screen will appear
5. (I)gnore it
6. game proceeds to craft anyway
7. check Rock Forge
8. see it used no charcoal, there is the same amount of before

# Expected behavior

Here a copypasta of the error screen:

DEBUG    : can't set ammo null in Rock Forge as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 601

# Screenshots

n/a

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-5735-g0d96da0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    More Survivor Stuff [more_survivor_stuff],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]

# Additional context

n/a

**Comment by ZhilkinSerg** [comment] 2020-09-07 12:41
Duplicate of #42033

**Closed by ZhilkinSerg** 2020-09-07 12:41 UTC
