### ISSUE TITLE
Explosive slugs do shit all

### ISSUE THREAD

**Issue by HardcastFlare** [CleverRaven/Cataclysm-DDA#60437] opened 2022-08-25 13:33 UTC
### Describe the bug

Fired explosive slugs seem to have little to no effect on terrain, target, etc. The damage appears to calculate as ~10 damage rolled against every limb individually, but interacts with armor values and falls off dramatically with distance. The result is a projectile that underperforms severely compared to even 00 shot, which is unusual given the rarity of the explosive slug.

### Steps to reproduce

Load an explosive slug into a Mossberg 500.
Shoot an enemy.
Cry because the explosive slug does hardly anything.

### Expected behavior

Whatever gets hit with the slug is vaporized into a fine mist, along with everything else in a 10-foot radius.

### Screenshots

![image](https://user-images.githubusercontent.com/111714390/186677932-2aba953d-1666-4d5c-b976-7aad85478546.png)
This is a fresh character wearing a set of plate armor with no helmet and shooting the wall directly in front of himself with explosive slugs. You can clearly see that his unprotected head is only taking 5-10 damage per refreshing blast of explosive breeze, while his armored limbs are completely unharmed.

### Versions and configuration

Game version: 0.F-9d29e93-Tiles, Build 2022-08-25-0113
Default mods only

**Comment by Marcos6226** [comment] 2022-08-25 14:42
Well based on it's description this behavior is correct.
```
"A shotgun shell shooting a small explosive.
Banned in several states. 
While an explosive from a shotgun sounds impressive, its practical applications are limited at best.
The loss in mass in order to accommodate an explosive give it much less impact force compared to traditional ammunition.
The relatively small size of the slug can only accommodate a limited amount of explosives, resulting in a fairly underwelming explosion.
These traits make it a utility tool for damaging barriers and disrupting other explosive devices, rather than something for anti-personnel use."
```

**Comment by HardcastFlare** [comment] 2022-08-25 14:51
I find it somewhat hard to believe that this is the intended effect because they don't damage objects much either.
![image](https://user-images.githubusercontent.com/111714390/186697477-c4e33d03-0a05-45ab-b524-b419f62acc4a.png)
They really just don't do anything. The explosion graphic suggests a violent anti-personnel effect - or at least some kind of shock wave - but the actual effect is pretty much nothing. Regardless of the intended effect, they just feel terrible and pointless.

**Comment by catdach** [comment] 2022-08-25 14:53
duplicate of #53179.

**Comment by HardcastFlare** [comment] 2022-08-26 06:51
In digging through the JSONs and trying to creatively adjust the stats and behavior of various explosive ammunition types, I've run into a few roadblocks.

For one, it seems that assigning an explosion effect to an ammo type will override all other flags, effects, and even damage values assigned to that ammo. I can't get the damn things to change their impact damage at all, which I think explains why they can't bust open doors. No matter what I set the damage value to, they always seem to deal around 10 damage on impact.

I also played with giving them the WIDE, SHOT, INCENDIARY and TRAIL effects, but none of them seemed to work. I'm not sure whether WIDE and TRAIL are deprecated at this point, but I know SHOT and INCENDIARY are definitely still in the game, they just don't seem to stack with EXPLOSIVE_HESHOT. I was hoping I could use SHOT to create a second projectile alongside the initial "dummy" projectile with set 10 or so impact damage to help the ammo destroy objects, but alas, it does not seem to work.

Correct me if I'm wrong on any of this, by all means. I have little idea of what I'm doing, just interested in learning how this thing works and playing with it.

**Comment by Marcos6226** [comment] 2022-08-26 16:54
I have taken several tests too. And I have reached the conclusion that ***its capacity to destroy furniture, like doors, is directly linked to its damage.*** 
```
"damage": { "damage_type": "bullet", "amount": 10, "armor_penetration": 0 }
```
I also tested it against **traps**, specifically the **booby-trap and landmines** (buried and non-buried), and **no matter how powerful the explosion is**, it will not set them off, meaning that it's main (or rather, only) purpose **is not working at all.**

Finally, the only use (that I can think) of this thing **currently** is as a novelty item that, in the best situation, **can only cause deafening and annoyance** to its target or just make loud distracting noises like a shotgun fired firework.

In my opinion, we should move this item to `obsolete.json`, as **currently** we can't make it work as it **should**.

**Comment by Terrorforge** [comment] 2022-08-26 17:05
Its original intended purpose was probably to be a cool grenade you shoot out of a shotgun, because they were originally described as "highly damaging". But they seem to come from an era when CDDA was less concerned with realism, and the reality is that a shotgun shell is just too small to contain a meaningful amount of high explosive.
The current line about "damaging barriers" is a description of what the actual real-life version does, not a statement of intent about what the in-game slugs are "supposed" to do. Including it was probably a mistake, because it does suggest functionality that isn't actually in the game.
Either way, I'm inclined to agree they don't really need to be in the game, because they don't really do anything but disappoint.

**Comment by HardcastFlare** [comment] 2022-08-27 00:46
Wouldn't it be better to make them useful or interesting, rather than remove them outright?

**Comment by anothersimulacrum** [comment] 2022-08-27 02:15
Only if the real thing would actually be useful or interesting.

**Comment by HardcastFlare** [comment] 2022-08-27 02:39
I'm sorry, but I don't understand why absolute realism would be a necessity in a game about an extradimensional zombie apocalypse where I can craft catgirl potions in my garage. It doesn't really make sense to me.

**Comment by anothersimulacrum** [comment] 2022-08-27 02:41
Part of that's covered in [the FMS page](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#failed-rationalizations), but it's kinda a defining feature of the game.

**Comment by HardcastFlare** [comment] 2022-08-27 03:37
I have a hard time believing that a shotgun slug that converts part of its stored energy into explosive force is considered "too fantastical" when we already have them in real life, right now. Yes, they are mostly jury-rigged, redneck, disasters-in-a-can, but that's what makes them fun, like potato guns and trebuchets.

https://youtu.be/8Lpx_CQ6kwo
https://youtu.be/idHAdGijzMk

Heck, the concept isn't even that difficult in theory. Fill a hull with magnesium and other fun stuff instead of shot - there's your exploding slug.

**Comment by Terrorforge** [comment] 2022-08-27 12:47
Nobody's saying they don't exist, we're saying they're not very useful. If you check out the previous thread (#53179), there's a lot of discussion, math and comparison with the commercially available Frag-12 trying to figure out exactly how not useful.

I should emphasize that their current state is not a result of that discussion. As far as I can guess, they're piss weak as an unintended consequence of some past explosives rework. But we couldn't get them to exactly where they ought to be, partly because it's really hard to find any hard data on these things, partly because of the technical limitations you yourself have encountered, partly because there seem to be some balance/consistency problems with CDDA explosives in general that make it hard to figure out how powerful any given real-world explosive should be in game terms. Essentially, we couldn't figure out exactly how powerful they should be beyond "idk not very?" so we just left it as it was and changed the description to be less misleading.

So I don't think anyone's wedded to current extremely useless version. But we don't want to buff it based solely on vibes, so it's kind of stuck until someone gets a better idea of what it should look like.

**Comment by kevingranade** [comment] 2022-08-28 01:54
Expected result is incorrect as noted in comments.
If you want to propose a sourced list of what this kind of projectile should and should not accomplish, someone can look into meeting those criteria.

**Closed by kevingranade** 2022-08-28 01:54 UTC
Labels: (S1 - Need confirmation)
