### ISSUE TITLE
Damaging a Limb via Debug menu instantly kills you.

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#56971] opened 2022-04-21 03:15 UTC
### Describe the bug

Any value on any limb set via the Debug menu's "Damage Self" feature will instantly kill the character.

### Steps to reproduce

1. Navigate to "Damage Self" debug menu item
2. Select any limb
3. Input a low, non-zero value
4. Confirm and die

### Expected behavior

The selected limb get damaged and at the input value.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 5fe200b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Jan-Blasiak** [comment] 2022-04-21 17:05
I've had the same issue

**Comment by Inglonias** [comment] 2022-04-21 21:10
I can also confirm this is happening. I suspect this has something to do with the limb changes being made, but can't say for certain.

**Comment by NetSysFire** [comment] 2022-04-21 21:50
I summon thee @Venera3, our resident limb expert

**Comment by dseguin** [comment] 2022-04-22 00:51
Here's a simple fix for this (tested):

```diff
diff --git a/src/debug_menu.cpp b/src/debug_menu.cpp
index 58cb9f58ef..30a8d9eb93 100644
--- a/src/debug_menu.cpp
+++ b/src/debug_menu.cpp
@@ -2722,7 +2722,9 @@ void debug()
             }
             if( query_int( dbg_damage, _( "Damage self for how much?  hp: %s" ), part.id().c_str() ) ) {
                 player_character.apply_damage( nullptr, part, dbg_damage );
-                player_character.die( nullptr );
+                if( player_character.is_dead_state() ) {
+                    player_character.die( nullptr );
+                }
             }
         }
         break;
```

**Comment by Inglonias** [comment] 2022-04-22 00:53
...ok, who did that?

**Comment by dseguin** [comment] 2022-04-22 01:04
> ...ok, who did that?

It was caused by d0a19e4ca838d112daceacc6ad85a3133e445b04

The assumption being that calling `Character::die` should, well, make the character die :P

**Closed** 2022-06-06 08:07 UTC
Labels: (S2 - Confirmed), Code: Debug
