### ISSUE TITLE
When "popup window when achievement complete" is set to first, Game crashes upon first kill.

### ISSUE THREAD

**Issue by Talvara** [CleverRaven/Cataclysm-DDA#64591] opened 2023-03-26 12:24 UTC
### Describe the bug

It looks like getting an achievement will cause the game to crash.
This only seems to happen when the "Popup window when achievement completed" is set to first.

changing the settings by going to "settings->options->interface->line 42" from the startup screen to something other than first avoids the crash.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11071536/crash.log)

### Attach save file

N/A

### Steps to reproduce

1. Ensure that "Popup window when achievement completed" in the games options is set to 'First'
2. Start a new game with a combat ready character.
3. Kill something.
4. Observe Crash.

### Expected behavior

The game shouldn't crash when the player is presented with an achievement.

### Versions and configuration

- OS. Windows 10
- Game Version: 4ae79c2 (tiles)

**Comment by gettingusedto** [comment] 2023-03-26 12:37
duplicate of #64466

**Closed** 2023-03-26 14:02 UTC
Labels: (S1 - Need confirmation)
