### ISSUE TITLE
Inconsistent AIM time costs when moving all items

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13205] opened 2015-08-07 08:48 UTC
(Apologies if this is a known issue or, indeed, intentional; I am not integrated in the CDDA community.)

Moving items using "move all" takes more time than moving each item manually. With a single Long String, this is 6 seconds for manual versus 12 seconds for move all. As a player I would not expect these times to be different.
##

**Comment by BevapDin** [comment] 2015-08-07 09:55
I'm just linking this with similar issues: #9392, #13131

**Comment by drbig** [comment] 2015-08-07 14:57
Given this will be the third issue on the same topic - is anything blocking fixes here?

**Comment by VlasovVitaly** [comment] 2015-09-10 10:43
I tested this on FirstKit
m - 6 sec.
M(any value) - 6 sec.
, - 6 sec.

**Comment by BTAxis** [comment] 2015-09-10 10:55
I can corroborate that, but it still behaves as previously described with the Long String.

**Comment by Oskar636** [comment] 2016-11-10 22:18
This is also a duplicate of #9392.

**Closed** 2016-11-11 12:18 UTC
Labels: Bug
