### ISSUE TITLE
Cdda Android poet no longer playable

### ISSUE THREAD

**Issue by MundaneRaven** [CleverRaven/Cataclysm-DDA#55563] opened 2022-02-21 15:07 UTC
### Describe the bug

When making a character and reaching the screen to finalize it, there are no longer any shortcut keys placed, so its impossible to finish the character.

### Steps to reproduce

Start a mew character on android version and get to the last screen of character creation. After that your screen will be locked on there unless you double tap to go back to the main menu.

### Expected behavior

The game will stay stuck unless you leave the menu manually by double tapping. 

### Versions and configuration

N/A

**Comment by LeahLuong** [comment] 2022-02-21 16:22
Have you tried using '?' to define hotkeys?? I imagine whomever did work on this area of the game recently forgot about the hotbar for android ports.

**Comment by MundaneRaven** [comment] 2022-02-21 18:00
I tried just about everything hut solving the problem myself. I've used the
"?" Thing, tried going into the menus on the screen but the only thing i
managed to do was get the location picking menu to get stuck. (It does
nothing BTW.) And not only that but i recently had to delete my version
because i fudged up my settings in my sleep and thought ot easier to just
restart the game altogether.

**Comment by LeahLuong** [comment] 2022-02-22 03:06
What version of the game are you running BTW?? I assumed it was a recent release because I've not encountered this in 0.F-3. Rolling back to a previous version can prob sort it for you.

**Comment by MundaneRaven** [comment] 2022-02-22 03:24
Its been active since the last 3 ports on experimental, i haven't updated
in about a day if that helps at all.  I also noticed that some of the new
save files(specifically the ones that have you start as a magician
character) lag quite a bit when in the class selection menu, might be a
hardware problem on my end though.

**Comment by LeahLuong** [comment] 2022-02-22 05:56
Thanks for the deets. They might help whenever some1 gets around to fixing this. I wouldn't hold my breath because I'm not sure the Android versions are a high priority around here. I asked what I thought would be a fairly simple question in #55418 but only 1 person has chimed in w/ a question they could have answered by reading the post. That was a week ago.

While you're waiting, you may want to consider changing this thread's title to something more helpful, like: Android Hotbar Unavailable on Final Chargen Screen (Now Unplayable). You may also want to include info in the OP regarding which release seemingly broke this functionality.

**Comment by MundaneRaven** [comment] 2022-02-22 06:12
How do i fix that exactly? Im new to actually using GitHub. By the by, do
you by any chance know how id get started on actually modding on android?
Cuss the app doesn't really work on mobile.

**Comment by LeahLuong** [comment] 2022-02-22 17:06
While signed in, there should be a button up near the top of the thread to change the title. You can edit your posts by pressing the ellipsis points in the upper right of each of your posts.

IDK about modding but you might be able to find something about it by following the "Wiki" link -- you guessed it -- up top.

**Comment by oosyrag** [comment] 2022-02-24 02:16
I'm interested in going over the Android auto add shortcuts, but did not find anything easily accessible at first glance.

If someone could point me in the right direction I wouldn't mind going through them and updating them for new ui changes or looking into fixes for problems like this.

**Comment by Inglonias** [comment] 2022-06-03 01:28
Could not reproduce.

- OS: Android
    - OS Version: Manufacturer: Google; Model: Pixel 5a; Release: 12; Incremental: 8353555; 
- Game Version: c355923 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Inglonias** [comment] 2022-06-03 01:30
@ZhilkinSerg i move we close this bug unless someone else can reproduce with a recent experimental.

**Closed** 2022-06-03 21:39 UTC
Labels: (S2 - Confirmed), OS: Android

**Comment by ZhilkinSerg** [comment] 2022-06-04 08:30
Not reproducible for me.
