### ISSUE TITLE
Duct tape considered as a liquid

### ISSUE THREAD

**Issue by Pippoilpipatur** [CleverRaven/Cataclysm-DDA#72720] opened 2024-03-30 12:27 UTC
### Describe the bug

Duct tape seems to be behaving as a liquid, hence it can't be Unloaded out of its cardboard box

### Attach save file

[Winding Falls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14811966/Winding.Falls-trimmed.tar.gz)

### Steps to reproduce

1. Try and reload a miscellaneous repair kit with duct tape contained in a cardboard box

### Expected behavior

I expected that the miscellaneous repair kit would be reloaded with the duct tape

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/165479882/4e6b6c16-00cf-4d58-84fb-6b63fd821c79)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/165479882/ebf3438c-906e-4e1f-a65f-632b4686a6a0)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/165479882/e4bd5e4b-2360-427f-b2b1-e017522b5154)

### Versions and configuration

windows 10 
italian
version dd4e109 (tiles)

**Comment by XygenSS** [comment] 2024-03-30 12:52
Duplicate of #71090

**Comment by RenechCDDA** [comment] 2024-03-30 17:09
No this is actually a separate UI error.

**Comment by RenechCDDA** [comment] 2024-03-30 17:22
Using the 'unload' command from the inventory calls Character::unload directly which naively assumes anything unloadable is liquid.

I don't think any real work is needed, just a change of the error message to be more generic.
https://github.com/CleverRaven/Cataclysm-DDA/blob/df6c8e39213c2e37bfc20ed023dcc18f3a0c8b3d/src/character.cpp#L11607

**Comment by Levitator0** [comment] 2024-03-31 06:07
Before we process this issue as a bug, can we explore stat gains and status effects from drinking duct tape?

**Closed** 2024-05-16 03:44 UTC
Labels: Info / User Interface, (S2 - Confirmed), [C++]
