### ISSUE TITLE
Segfault after zooming in

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#27881] opened 2019-01-25 23:17 UTC
**Describe the bug**  
Happened when I zoomed in (I think it happened when I was at the lowest level and the game wanted to jump back to the highest zoom level).
```
CRASH LOG FILE: config/crash.log
VERSION: 0.C-37065-g1aeee0e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D1BA5[cataclysm-tiles.exe+0x1D1BA5]
    @0x5D2752[cataclysm-tiles.exe+0x1D2752]
    SMPEG_error+0x4B034@0xE783F0[cataclysm-tiles.exe+0xA783F0]
    _C_specific_handler+0x98@0x7FFB40977C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFB419DF7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFB4194D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFB419DE70E[ntdll.dll+0x9E70E]
    @0xD46B93[cataclysm-tiles.exe+0x946B93]
    @0x4B60C7[cataclysm-tiles.exe+0xB60C7]
    @0x4C3AE2[cataclysm-tiles.exe+0xC3AE2]
    @0x4C41B6[cataclysm-tiles.exe+0xC41B6]
    @0xCB0D0F[cataclysm-tiles.exe+0x8B0D0F]
    @0x6BBCC4[cataclysm-tiles.exe+0x2BBCC4]
    @0x6BC8DA[cataclysm-tiles.exe+0x2BC8DA]
    @0x717324[cataclysm-tiles.exe+0x317324]
    @0x6FA3C2[cataclysm-tiles.exe+0x2FA3C2]
    IMG_LoadWEBP_RW+0x4D5429@0x145FF19[cataclysm-tiles.exe+0x105FF19]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFB41403034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFB419B3691[ntdll.dll+0x73691]
```

**To Reproduce**  
Can't reproduce.

**Expected behavior**  
Self-explanatory.

**Versions and configuration(please complete the following information):**
 - OS: Windows10
 - Game Version: Build 8472
 - Graphics version: Tiles
 - Mods loaded: none besides default ones

**Comment by ifreund** [comment] 2019-01-25 23:22
Duplicate of #27869.

**Comment by GoLoT** [comment] 2019-01-25 23:32
Apparently this and #27869 are related to #27871, same stack traces.

**Closed** 2019-01-25 23:56 UTC
