### ISSUE TITLE
Segfault on open inventory

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70292] opened 2023-12-18 23:42 UTC
### Describe the bug

Was trying to open inventory and got segfault.

### Attach save file

[Rock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13709449/Rock-trimmed.tar.gz)

### Steps to reproduce

doesnt seem to happen on reload? No idea why this keeps happening. 

### Expected behavior

No segfault

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 85926f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: C:/Users/Kenny/Desktop/NEW CDDA/dda/userdata/config/crash.log
VERSION: 85926f2
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: debug_write_backtrace+0xb5@0,000,7FF,6AE,8DC,C15[cataclysm-tiles.exe+0x53c,c15]), 
  #1
    (dbghelp: log_crash+0x377@0,000,7FF,6AE,ED8,D67[cataclysm-tiles.exe+0xb38,d67]), 
  #2
    (dbghelp: signal_handler+0x57@0,000,7FF,6AE,ED9,2F7[cataclysm-tiles.exe+0xb39,2f7]), 
  #3
    (dbghelp: seh_filter_exe+0x178@0,000,7FF,6AF,E4D,748[cataclysm-tiles.exe+0x1,aad,748]), 
  #4
    (dbghelp: `__scrt_common_main_seh'::`1'::filt$0+0x16@0,000,7FF,6B0,083,6A9[cataclysm-tiles.exe+0x1,ce3,6a9]), 
  #5
    (dbghelp: _C_specific_handler+0xa0@0,000,7FF,6AF,E1E,970[cataclysm-tiles.exe+0x1,a7e,970]), 
  #6
    (dbghelp: _chkstk+0x11f@0,000,7FF,B48,1F2,3AF[ntdll.dll+0xa2,3af]), 
  #7
    (dbghelp: RtlRaiseException+0x484@0,000,7FF,B48,1A1,4B4[ntdll.dll+0x51,4b4]), 
  #8
    (dbghelp: KiUserExceptionDispatcher+0x2e@0,000,7FF,B48,1F0,EBE[ntdll.dll+0xa0,ebe]), 
  #9
    (dbghelp: item::barrel_length+0x5b@0,000,7FF,6AE,98F,02B[cataclysm-tiles.exe+0x5ef,02b]), 
  #10
    (dbghelp: item::gun_damage+0x5a@0,000,7FF,6AE,9B8,65A[cataclysm-tiles.exe+0x618,65a]), 
  #11
    (dbghelp: item::gun_info+0x7ad@0,000,7FF,6AE,9B9,77D[cataclysm-tiles.exe+0x619,77d]), 
  #12
    (dbghelp: item::info+0x8df@0,000,7FF,6AE,9C1,C0F[cataclysm-tiles.exe+0x621,c0f]), 
  #13
    (dbghelp: item::info+0x34@0,000,7FF,6AE,9C2,4D4[cataclysm-tiles.exe+0x622,4d4]), 
  #14
    (dbghelp: inventory_selector::action_examine+0x6a@0,000,7FF,6AE,DB7,CAA[cataclysm-tiles.exe+0xa17,caa]), 
  #15
    (dbghelp: inventory_selector::on_input+0x390@0,000,7FF,6AE,DD2,330[cataclysm-tiles.exe+0xa32,330]), 
  #16
    (dbghelp: inventory_pick_selector::execute+0x6e0@0,000,7FF,6AE,DC7,260[cataclysm-tiles.exe+0xa27,260]), 
  #17
    (dbghelp: game_menus::inv::common+0x57e@0,000,7FF,6AF,881,DBE[cataclysm-tiles.exe+0x1,4e1,dbe]), 
  #18
    (dbghelp: game::do_regular_action+0x1,2a4@0,000,7FF,6AF,BF7,464[cataclysm-tiles.exe+0x1,857,464]), 
  #19
    (dbghelp: game::handle_action+0xa68@0,000,7FF,6AF,C00,CE8[cataclysm-tiles.exe+0x1,860,ce8]), 
  #20
    (dbghelp: do_turn+0xefc@0,000,7FF,6AE,EEE,A9C[cataclysm-tiles.exe+0xb4e,a9c]), 
  #21
    (dbghelp: WinMain+0xd45@0,000,7FF,6AE,79C,7E5[cataclysm-tiles.exe+0x3fc,7e5]), 
  #22
    (dbghelp: __scrt_common_main_seh+0x106@0,000,7FF,6AF,E1B,5A2[cataclysm-tiles.exe+0x1,a7b,5a2]), 
  #23
    (dbghelp: BaseThreadInitThunk+0x14@0,000,7FF,B47,667,344[KERNEL32.DLL+0x17,344]), 
  #24
    (dbghelp: RtlUserThreadStart+0x21@0,000,7FF,B48,1A2,6B1[ntdll.dll+0x52,6b1]),

**Comment by BrettDong** [comment] 2023-12-19 03:44
Duplicate of #70156

**Closed by BrettDong** 2023-12-19 03:44 UTC
Labels: (S1 - Need confirmation)
