### ISSUE TITLE
Accepting Ranch Foreman Mission 12 spams debug messages

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14351] opened 2015-12-08 15:36 UTC
Accepting the quest to retrieve car batteries for the Ranch Foreman causes a bunch of debug messages related to `destroy_vehicle`, e.g.

```
DEBUG: destroy_vehicle can't find it! name=Low-End Cube Van, submap:0,0,0
  Press spacebar...
```

So far mostly `Sport Car` and `Low-End Cube Van`. Still haven't gotten to the end of these messages...

e: Version: 0.C-8042-g1cf8251

**Comment by Griffinhart** [comment] 2015-12-08 15:37
The time between each message is getting longer and longer.

**Comment by Griffinhart** [comment] 2015-12-08 15:53
Time between messages was growing to be literal minutes. Sent SIGINT, bt returned nothing useful ("Target is executing").

**Comment by etmoonshade** [comment] 2015-12-08 19:41
I can confirm this problem.

I was going to report it, but I had a "dirty" save that had caused problems before so I wasn't sure if this was another manifestation of that.

**Comment by sparr** [comment] 2015-12-09 09:26
tried to find any calls to destroy_vehicle in mission_start.cpp and came up empty.

if someone can reproduce this, try adding a debug breapoint in destroy_vehicle and running under a debugger, get a backtrace from there?

**Comment by vache** [comment] 2015-12-09 15:32
My guess is it's happening somewhere in mission_start::ranch_construct_11, at section after " //Start adding scrap vehicles", destroy_vehicle is called as part of map::add_vehicle_to_map if it is merging wrecks.

**Comment by sparr** [comment] 2015-12-10 12:10
Could someone post a save to reproduce this? I don't have a lot of experience with NPCs so I'm not sure how to construct the scenario where this bug happens.

**Comment by etmoonshade** [comment] 2015-12-10 15:06
Crap, totally forgot to get that save when I passed it.

Debug menu -> Edit NPC -> Add mission -> Find 12 Car Batteries.

At that point, just follow the standard "gimme mission" stuff.

**Comment by Soyweiser** [comment] 2016-07-01 02:04
This now crashes the game for me.

**Comment by kevingranade** [comment] 2017-03-24 02:54
Looks like it's building a wall of vehicles and they're overlapping, when that happens they end up getting destroyed.  I'm guessing the dimensions of one of the vehicles changed, or the way we determine the center point changed.

**Comment by Toothspit** [comment] 2017-05-25 05:55
Can't repro this one either. `Shift+c` `enter` `a` `a` `c` `a` `a` `d` on the provided save gives no error on Linux x64 gcc 0.C-22449-g15a1935de4 15a1935

**Comment by Leland** [comment] 2017-08-19 02:20
Ditto, this looks fine to me.

**Comment by Leland** [comment] 2017-08-20 16:20
Closing - as far as I can tell this is working now.

<img width="361" alt="screen shot 2017-08-20 at 12 19 19 pm" src="https://user-images.githubusercontent.com/714017/29496503-d8dea56a-85a1-11e7-902a-1ba435b5e78b.png">

If anyone encounters this issue again, either ping me here to reopen or simply make a new issue.

**Closed by Leland** 2017-08-20 16:20 UTC
Labels: Bug, Mission
