### ISSUE TITLE
Basecamp Bulleting Board Crafting Menu doesn't allow NPCs to actually craft

### ISSUE THREAD

**Issue by hacartwright** [CleverRaven/Cataclysm-DDA#78588] opened 2024-12-15 13:55 UTC
### Describe the bug

The crafting menu accessed through the basecamp bulletin board does not allow you to choose NPCs and cannot be used to get them to craft.  NPCs can still be ordered to craft through the regular crafting menu by choosing them as the crafter.  The basecamp menu doesn't allow you to choose the NPC or even appears to detect them at all; it displays no NPCs to choose even if they are assigned to the camp.

### Attach save file

[Cold Brook-trimmed.tar.gz](https://github.com/user-attachments/files/18140629/Cold.Brook-trimmed.tar.gz)

### Steps to reproduce

1. Have NPC start basecamp with bulletin board and make necessary zones
2. Debug in ingredients and tools for a recipe
3. Use debug to make certain NPC has skills needed for recipe
4. Open basecamp menu using bulletin board and open Crafting submenu
5. Highlight recipe and press "c" to choose crafter
6. Have crafting menu display no NPCs to select

### Expected behavior

I expect that the basecamp crafting menu will let me choose NPCs with the necessary tools and skills to craft something.  The regular crafting menu allows you to select which NPC from those that meet the recipe's requirements.

### Screenshots

<img width="952" alt="Screenshot 2024-12-15 054931" src="https://github.com/user-attachments/assets/4445dad8-dcbd-4519-af00-f7b058aeb553" />

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: a1306e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment] 2024-12-16 02:58
You choose the crafter *after* selecting a recipe. It will let you select from anyone who's stationed at the camp and is able to actually do the recipe (not busy/has necessary skills/has necessary proficiencies).

You have no one stationed at the camp so.... it just silently returns. Well, okay, that's clearly not good. But it is working correctly. Nobody to choose, then it just can't proceed. Still ,it should notify you in that case.

After assigning your sole follower to the camp and selecting a recipe, it works as expected.

![image](https://github.com/user-attachments/assets/c6d22570-deb8-4176-989e-f79459c3661b)

**Comment by RenechCDDA** [comment] 2024-12-17 15:01
I'm gonna go ahead and mark this confirmed because the UI is not being clear, although the linked PR should (shortly) close this issue. Just in case.

**Closed** 2024-12-17 16:07 UTC
Labels: (S2 - Confirmed)
