### ISSUE TITLE
Grab-moving furniture ineluctably delays you

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#45799] opened 2020-12-04 02:21 UTC
# Using 'G' to grab a desk with many, many items on it moves the desk and the items, but will not allow the player to interrupt the action with '5' like normal, and gives no prompts to stop when being injured, even when a zombie is chewing on your face.

Move a desk with max number items on it near a zombie

# Expected behavior

regular interruptible long action and prompts

# Screenshots

# Versions and configuration

latest experimental
 -->

# Additional context

**Comment by anothersimulacrum** [comment] 2020-12-04 04:47
Thanks for the report!
Duplicate of #45010

**Closed by anothersimulacrum** 2020-12-04 04:47 UTC
Labels: (S3 - Duplicate)
