### ISSUE TITLE
`ImGui::InputText` broken multiple ways on EndeavourOS, keybinding filter and last words input

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#77001] opened 2024-10-12 23:05 UTC
### Describe the bug

I am seeing two different misbehaviors of `ImGui::InputText`.

In the keybindings filter (`?` then `/`), the display and effective filter are both missing characters. After pressing `?` then `/` (or `f`) to start entering a filter, I can press the following keystrokes and get the results described:
* `n`, the first cell of the green input box changes background from green to light grey, the character below that ("l" in "English" for me) changes background to light grey, and the second cell of the green input box changes background from green to white. The letter "n" does not appear, the input box is still empty other than the background color changes.
* `o`, the two light grey background cells move one to the right, leaving the first cell of the input box green again, replacing the white cell with light grey, and moving the light grey background in the line below to the "i" in "English". Again, no text appears, the input box is still empty.
* `r`, the two light grey background cells move one to the right again, to the third cell of the input box and the "s" in "English", the white background returns in the fourth cell of the input box, and the letter "o" appears in the second cell which is back to a green background. The keybinding list appears to have actually filtered for "o" now as well.
* `t`, the light grey and white backgrounds move one to the right, the text in the input box is now " or", and the list is filtered for "or".
* `h`, light grey backgrounds move one to the right, white background disappears again, input box says " ort", the list is filtered for "ort".
* `backspace`, light grey backgrounds move one to the left, white background reappears, input bot says " or", the list is filtered for "orth"(!?!).
* `backspace`, light grey backgrounds moves one to the left, white background disappears again, input box says " o", the list is filtered for "ort".

Here's a summary of the behaviors:
* The grey background moves where I expect the cursor to be, and also has another grey background cell below it.
* A white background appears to the right of the grey background cursor intermittently.
* The displayed text, is always missing the first and last character.
* The effective filter lags one keystroke behind the entered text (which is different from the display missing the last character in how it behaves when backspacing).

<hr />

I'm putting this other misbehavior in the same bug report because I suspect the cause is related, since it's unlikely a coincidence that the only two uses of `ImGui::InputText` are both broken for me.

When my character dies and I am prompted to enter my last words, I see an "Last words:  " at the bottom of the tombstone dialog, then an input box. The first cell is grey background, the second cell is white background (this feels like the cursor behavior above, minus the misbehavior above), and the next ~20 cells are green background. I haven't exhaustively tried every key, but to a rough approximation... No key other than ENTER has any effect. I cannot type into the box. Nothing at all happens when I press anything, until I press ENTER which gets me the "Watch the last moments" prompt.

I'm going to tag @katemonster33 in the hopes of some imgui insights. I'm open to trying to troubleshoot this, but I'd appreciate some guidance before I just dive in with a debugger.

### Attach save file

N/A, this happens in every game including new "Play Now"s.

### Steps to reproduce

1. `?/north`
2. die
3. try to type anything
4. press ENTER

### Expected behavior

1. "north" appears in the filter input and the keybinding list is filtered by that string

3. typing into the tombstone dialog works

### Screenshots

![image](https://github.com/user-attachments/assets/25ba9c9a-5323-4202-b37d-281551aa9abe)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: 94370789a7 [64-bit]
- Graphics Version: Curses
- Game Language: System language [] (edit: English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

andrei8l on Discord was unable to reproduce the problem (in tiles mode?)

**Comment by NetSysFire** [comment] 2024-10-12 23:10
Duplicate of #76129. But I'll take that as a confirmation for that issue.

**Closed by NetSysFire** 2024-10-12 23:10 UTC
Labels: (S1 - Need confirmation)

**Comment by sparr** [comment] 2024-10-12 23:39
I notice that the actual filter catches up (instead of being one keystroke behind) if I move the mouse!
