### ISSUE TITLE
Selected weapon disappears if player uses escape key to cancel on "Stop Wielding?" menu

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#28281] opened 2019-02-20 02:57 UTC
**Describe the bug**  
When a player opts to wield a new weapon, but then cancels the process on the "Stop Wielding?" menu, the selected weapon disappears from the inventory.

**To Reproduce**  
1. Make a new character with at least two weapons - for demonstration I used the bionic sniper profession.
2. Place both weapons (RM11B rifle and USP .45) in inventory.
3. Wield RM11B rifle.
4. Press "w" and select USP .45.
5. On the "Stop Wielding?" menu, press escape twice [NB: no response to single press]
6. Return to inventory screen and observe that the USP .45 is no longer in inventory.
7. Same process works for any two items - does not seem to be related to mods on the weapons.

**Expected behavior**  
Cancelling from the "Stop Wielding? menu should leave the relevant items in their original locations.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Linux Mint 18.3 Cinnamon
 - Game Version: 0.C-37533-g66698e5
 - Graphics version: Tiles
 - Mods loaded: Defaults only - Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Additional context**  
While attempting to reproduce, also generated this error message when choosing to drop the currently wielded menu:

 DEBUG    : item location does not point to valid item
 
 FUNCTION : void item_location::remove_item()
 FILE     : src/item_location.cpp
 LINE     : 601

**Comment by Tatterdemalian** [comment] 2019-02-20 15:41
There seems to be a general issue with src/item_location.cpp, I have been intermittently getting this same error (exact same, right down to the line number in item_location.cpp) in a brand new world as of version 0.C-37533-g66698e5054. It happens on picking up or dropping certain items, but there seems to be no particular item that causes the error, and there is no sign of item cloning or vanishing caused by it. The error simply pops up on occasion when managing inventory, both by regular drop/get menus and the advanced interface, and ignoring it hasn't caused any issues so far.

**Comment by ifreund** [comment] 2019-02-20 16:11
This issue in particular was caused by #28248. I haven't seen this debug message pop up for any other reason, and haven't read any reports of it until now.

>I have been intermittently getting this same error (exact same, right down to the line number in item_location.cpp) in a brand new world as of version 0.C-37533-g66698e5054.

Unfortunately, the fact that the line number is the same doesn't mean it's the same error, `item_location::remove_item()` is called all over the code.  I'd recommend opening a new issue and including debug.log so we can see the stack trace.

**Comment by Tatterdemalian** [comment] 2019-02-20 19:57
Will do if it happens again. Intermittent bugs are by far the most annoying, because they never happen when you're watching the code.

**Comment by kevingranade** [comment] 2019-02-21 08:28
Fixed by #28276

**Closed by kevingranade** 2019-02-21 08:28 UTC
Labels: <Bug>, Inventory / AIM / Zones
