### ISSUE TITLE
NPC Prisoners and beggars should lose their title upon recruiting

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#72138] opened 2024-03-03 14:18 UTC
### Is your feature request related to a problem? Please describe.

When you recruit the refugee center beggars, or rescue prisoners from a mi-go camp, your new followers are still named "(npcname), beggar" or "(npcname), prisoner" despite the fact that they are no longer that. Currently the only way of ridding them of those titles is to use the debug menu.

### Solution you would like.

NPCs should lose such monikers upon recruitment.

Failing that, you should be able to customize the NPC's name the same way you can do so in your character sheet.

### Describe alternatives you have considered.

Is the fact that they were once a beggar or once a prisoner something to be preserved about their identity? It's hardly relevant after they join your ranks.

**Comment by MrHrulgin** [comment] 2024-03-06 01:04
I'd second the value of custom titles for recruited NPCs. Even better if they could be automatically generated based on the NPCs skills for ease of work assignments.

**Comment by I-am-Erk** [comment] 2024-05-07 16:30
This is something I've wanted for a while too, and should be pretty easy to add.

**Comment by I-am-Erk** [comment] 2024-06-14 22:53
I don't think #74406 fully resolves this; this should be an automatic change caused by an effect to close the issue

**Closed** 2024-10-21 00:58 UTC
Labels: NPC / Factions, <Suggestion / Discussion>, (P4 - Low)
