### ISSUE TITLE
segfault on new map gen

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#31600] opened 2019-06-18 20:47 UTC
# Describe the bug
When nearing the National Guard base, specifically an ungenerated entrance section, the game crashes (segfault)

# Steps To Reproduce
1. drive down the road, turn left towards National Guard Armory
2. drive for 1-2 more turns
3. crash

# Expected behavior
The car would continue moving down the road normally.

# Screenshots
![image](https://user-images.githubusercontent.com/7266560/59718579-11de6480-91e0-11e9-9e65-4ffeea9776f7.png)

the above image shows approximate location crash occurred.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4578-gf477339 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Mundane Zombies [Mundane_Zombies],
    No Acid Zombies [No_Acid_Zombies],
    No Ants [No_Anthills],
    No Big Zombies [No_Big_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[debug and crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3303325/debug.and.crash.zip)

Your save file (zipped)
[Winkelman.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3303327/Winkelman.zip)

**Comment by ZhilkinSerg** [comment] 2019-06-19 09:34
Could be a duplicate of #31530.

Do you see any monsters with guns around there?

**Comment by OptimisticNihlist** [comment] 2019-06-19 14:28
the W2011B would have a gun, right? He's the national guard armory security bot (or one of the several types).

**Comment by TechyBen** [comment] 2019-06-19 15:59
Do securibots count as having "guns"?

**Closed** 2019-06-20 06:46 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>, Vehicles
