### ISSUE TITLE
Invalid Iterator Crash

### ISSUE THREAD

**Issue by Maeyanie** [CleverRaven/Cataclysm-DDA#23992] opened 2018-06-11 08:25 UTC
Game version:
0.C-28152-g5e846a6154

Operating system:
Windows and Linux

Tiles or curses:
Tiles

Mods active:
Most of the ones which ship with the game.
I doubt this is caused by any of them, but I'll type it out if you think it'll be useful.

### Notes
I've hit this crash a couple of times, so isn't completely random, but I haven't found a definite source. I'll keep looking into it though and update this as I find more.

Crash message:
```
/usr/include/c++/8/debug/safe_iterator.h:149:
Error: attempt to copy-construct an iterator from a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x1b256028 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > > (mutable iterator);
      state = singular;
    }
    iterator "other" @ 0x0x1a317938 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > > (mutable iterator);
      state = singular;
      references sequence with type 'std::__debug::list<item, std::allocator<item> >' @ 0x0x1a5a00a0
    }

Thread 1 "cataclysm-tiles" received signal SIGABRT, Aborted.
```
Debugging:
```
(gdb) bt
#0  0x00007ffff612bf4b in raise () from /lib64/libc.so.6
#1  0x00007ffff6116591 in abort () from /lib64/libc.so.6
#2  0x00007ffff6aee991 in ?? () from /lib64/libstdc++.so.6
#3  0x0000000000cc0302 in __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >::_Safe_iterator (__x=invalid iterator, this=0x1b256028) at /usr/include/c++/8/debug/formatter.h:492
#4  item_reference::item_reference (this=0x1b256020) at src/active_item_cache.h:13
#5  __gnu_cxx::new_allocator<std::__cxx1998::_List_node<item_reference> >::construct<item_reference, item_reference const&> (
    __p=0x1b256020, this=0x7fffffffd3b8) at /usr/include/c++/8/ext/new_allocator.h:136
#6  std::allocator_traits<std::allocator<std::__cxx1998::_List_node<item_reference> > >::construct<item_reference, item_reference const&> (__p=0x1b256020, __a=...) at /usr/include/c++/8/bits/alloc_traits.h:475
#7  std::__cxx1998::__cxx11::list<item_reference, std::allocator<item_reference> >::_M_create_node<item_reference const&> (
    this=0x7fffffffd3b8) at /usr/include/c++/8/bits/stl_list.h:644
#8  std::__cxx1998::__cxx11::list<item_reference, std::allocator<item_reference> >::_M_insert<item_reference const&> (
    __position=..., this=0x7fffffffd3b8) at /usr/include/c++/8/bits/stl_list.h:1902
#9  std::__cxx1998::__cxx11::list<item_reference, std::allocator<item_reference> >::push_back (__x=..., this=0x7fffffffd3b8)
    at /usr/include/c++/8/bits/stl_list.h:1219
#10 active_item_cache::get (this=this@entry=0x1ad6def8) at src/active_item_cache.cpp:68
#11 0x00000000013cbdc9 in map::process_items_in_vehicle<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> (this=this@entry=0x1da3e40, cur_veh=..., current_submap=..., 
    processor=processor@entry=0x138a66a <process_map_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, tripoint const&, std::__cxx11::string)>, signal="") at /usr/include/c++/8/debug/safe_base.h:100
#12 0x00000000013cfa30 in map::process_items_in_vehicles<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> (this=this@entry=0x1da3e40, current_submap=..., 
    processor=processor@entry=0x138a66a <process_map_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, tripoint const&, std::__cxx11::string)>, signal="") at /usr/include/c++/8/debug/safe_base.h:100
#13 0x00000000013cfb26 in map::process_items<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, tripoint const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> (this=0x1da3e40, active=active@entry=true, 
    processor=processor@entry=0x138a66a <process_map_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, tripoint const&, std::__cxx11::string)>, signal="") at src/map.cpp:4649
#14 0x00000000013ae272 in map::process_active_items (this=<optimized out>) at /usr/include/c++/8/bits/char_traits.h:285
#15 0x00000000008c8596 in game::do_turn (this=0x2425050) at src/game.cpp:1530
#16 0x0000000000934329 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:523
(gdb) frame 10
#10 active_item_cache::get (this=this@entry=0x1ad6def8) at src/active_item_cache.cpp:68
68	            items_to_process.push_back( an_iter );
(gdb) print an_iter
$1 = (item_reference &) @0x1a317930: {location = {x = -4, y = 0}, item_iterator = invalid iterator, item_id = 0x1ab4d980}
(gdb) print active_item_set
$2 = std::__debug::unordered_map with 1 element = {[0x1ab4d980] = true}
(gdb) print active_items
$3 = std::__debug::unordered_map with 1 element = {[1] = std::__debug::list = {[0] = {location = {x = -4, y = 0}, 
      item_iterator = invalid iterator, item_id = 0x1ab4d980}}}
(gdb) 
```

I did save a coredump, however it's 108 MB compressed. Let me know if that would be useful and I'll upload it somewhere.

**Comment by BrettDong** [comment] 2018-07-05 13:46
Is this issue reproducible with any random generated map?

**Comment by Maeyanie** [comment] 2018-07-05 23:53
I haven't been able to reproduce it reliably. Happened a couple of times in one area of the map, but haven't (yet) seen it elsewhere, or been able to get a save which could reliably get it to occur.

Debugging random crashes is annoying. :/

**Comment by BrettDong** [comment] 2018-07-06 03:46
According to the back trace you provided, the crash seems to be relevant to something on a vehicle.

**Comment by Maeyanie** [comment] 2018-07-08 15:52
Is there any easy way to get an item to rot into nothingness? Tried testing if it's that by leaving a chunk of meat in a trunk, but fast-forwarded almost 2 seasons and it's still there.

**Comment by mlangsdorf** [comment] 2018-10-03 11:54
Closing as a duplicate of #25934 which has a better reproducer.

**Closed by mlangsdorf** 2018-10-03 11:54 UTC
Labels: (S1 - Need confirmation), <Crash / Freeze>
