### ISSUE TITLE
Nether Attunement excessive error repetition

### ISSUE THREAD

**Issue by Seantism** [CleverRaven/Cataclysm-DDA#71873] opened 2024-02-20 16:38 UTC
### Describe the bug

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0.75" to a number

 FUNCTION : eval
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\math_parser.cpp
 LINE     : 241
 VERSION  : 7545d7f

### Attach save file

[Bridgeport-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14348332/Bridgeport-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Wait some amount of time (seems to occur around 08:40:53)
3. Excessive Error repetition

### Expected behavior

I expected that error could be 'i'gnored and that game would be playable after it occured, due to the fact that by some kind of arcane coding magic, most errors encountered do not cause hard crashes or game lock ups.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 7545d7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Custom Content [Custom_Content],
    Mind Over Matter [mindovermatter],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]

### Additional context

[Custom Content.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14348492/Custom.Content.zip)
It's probably not relevant as it only contains a few professions, items and the option to start at hub_01, but I've attached my custom content mod in case it is somehow contributing to the error.

The character in the save is imported.

**Comment by Standing-Storm** [comment] 2024-02-21 02:23
Could not reproduce:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/d975c363-6f95-4859-a8d7-fb3d4f8ede1d)

Were you just waiting? Were you opening your spellbook beforehand (which should trigger setting `nether_attunement_power_scaling`)? I tried doing that as well, activating and deactivating powers, and didn't get any errors.

**Comment by andrei8l** [comment] 2024-02-21 08:12
/duplicate of #71635. AFAICT this can happen if you change locale/language setting after saving a game. From your debug log, it looks like you saved a game with the `C` locale (default/fallback), but are not playing with `English_South Africa.utf8`.

**Comment by Seantism** [comment] 2024-02-21 18:36
> Were you just waiting? Were you opening your spellbook beforehand (which should trigger setting `nether_attunement_power_scaling`)? I tried doing that as well, activating and deactivating powers, and didn't get any errors.

Just waiting yes. Though I guess that's moot in light of the other issue this is a duplicate of.

> /duplicate of #71635. AFAICT this can happen if you change locale/language setting after saving a game. From your debug log, it looks like you saved a game with the `C` locale (default/fallback), but are now playing with `English_South Africa.utf8`.

I haven't actively changed language settings, in CDDA or otherwise, so I'm not sure what caused that.

**Closed** 2024-02-21 18:37 UTC
Labels: (S3 - Duplicate)
