### ISSUE TITLE
Thread duplication

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#48842] opened 2021-05-12 00:35 UTC
# Describe the bug

Trying to (U)nload a partial amount of Thread (and Nomex/Sinew) from a (w)ielded Tailor's Kit with a full inventory gives the error
```
DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable::remove_item(item&)
 FILE     : src/visitable.cpp
 LINE     : 496
```

# Steps To Reproduce

1. Take off all clothing
2. Load ~100 or so thread into a Tailor's Kit
3. (w)ield the Tailor's Kit
4. Attempt to (U)nload the Tailor's Kit

# Expected behavior

Thread is safely removed without any duplication.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10395-g4525b4f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: none.

# Additional context

Brand new debug world in the correct conditions to trigger the duplication.

[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6462656/Test.zip)

This MIGHT have been fixed by #47885 but I'm having some issues updating versions at the moment and this is occurring outside of AIM, and has a debug message not mentioned in the other issues of that type.

**Comment by Saicchi** [comment] 2021-05-12 14:59
Can confirm in `0.E-10474-g1ae66c97a0 [64-bit]`.
This happens when wielding the tailor's kit and being naked or wearing clothing without any storage.  
The tailor's kit need to be filled with 1 ~ 200 thread, 200 and above does not cause the bug.

**Comment by Salty-Panda** [comment] 2021-05-12 15:06
Probably duplicate of #47001

**Comment by RoyBerube** [comment] 2021-05-15 16:17
I can also get it to crash with the tailor's kit. Never could with the magazine.

**Comment by RoyBerube** [comment] 2021-05-15 17:28
I've got a fix working but just want to see if is acceptable. My solution is just to drop the thread being unloaded instead of the kit. The bug can not happen this way.

The other option would be to work with the existing sequence - the thread is wielded and the tailor's kit is dropped. To me this makes less sense than dropping the thread if there is no room.

**Comment by Saicchi** [comment] 2021-05-15 17:29
Do you know why the bug is happening and how your changes affect other places which might have the same issue?

**Comment by RoyBerube** [comment] 2021-05-15 17:32
I know why it is happening. The ammo is created and wielded. The tailor's kit is then dropped and then an unload of it is attempted that fails because it is not where it is expected to be. The result is that the tailor's kit is never unloaded.

I will do some more tests, but don't expect it to impact any other unload scenarios. If inventory has room then it behaves as before - the ammo (thread )is just added to inventory.

**Closed** 2021-05-28 09:51 UTC
Labels: (S2 - Confirmed), Items: Ammo
