### ISSUE TITLE
Segfault when asking John Beiley for his zombie kill count

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#68444] opened 2023-10-01 14:16 UTC
### Describe the bug

The game crashes when asking the NPC called John Bailey for his zombie kill count in the refugee center

### Attach save file

[Achille-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12777345/Achille-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Talk to John Bailey
3. Select option c. You looking for any kind of work?
4. Select option a. What's your zombie kill count
5. Observe crash

### Expected behavior

Show his zombie kill count

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/2ea627b4-a632-4b10-8c1f-45aa6a5af36e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 17a8e99 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

The last time an issue with John Bailey's zombie kill count was fixed was in #65273

**Comment by RenechCDDA** [comment] 2023-10-04 18:56
@lispcoc Could you take a look at this? I think it's related to your PR #68244. It appears to be passing an invalid reference for `me_weapon`. (actually it seems `me_chr` might be the invalid reference?)

https://github.com/CleverRaven/Cataclysm-DDA/blob/5621850411c36baca2978f8779cf4579723cdfd1/src/npctalk.cpp#L2028

**Comment by lispcoc** [comment] 2023-10-04 19:26
I tried the latest build, but could not reproduce it. I'll revert the commit and check

**Comment by RenechCDDA** [comment] 2023-10-04 19:39
Ahh sorry, looks like that might be my fault for not syncing my fork. I can confirm that there is no crash on **latest** experimental (MSVC build or not). (So it was crashing, but it got resolved in one of the bugfixes)

I'm going to close this as resolved. @snipercup if you or anyone else experiences this issue on https://github.com/CleverRaven/Cataclysm-DDA/commit/5621850411c36baca2978f8779cf4579723cdfd1 or later, you can make a comment and I'll reopen it.

**Closed by RenechCDDA** 2023-10-04 19:39 UTC
Labels: NPC / Factions, <Crash / Freeze>, (S2 - Confirmed)
