### ISSUE TITLE
Unloading or Reloading items like (misc repair kit, gas mask, or sewing kit) result in none items and nothing being reloaded Respectively

### ISSUE THREAD

**Issue by DramaticHotDog** [CleverRaven/Cataclysm-DDA#40315] opened 2020-05-07 22:38 UTC
# Describe the bug, Steps To Reproduce, and Screenshots

When you unload an item like (misc repair kit, gas mask, or sewing kit) it will result in an error message. 

 DEBUG    : cannot determine reload cost as none is neither ammo or magazine

 FUNCTION : int player::item_reload_cost(const item&, const item&, int) const
 FILE     : src/player.cpp
 LINE     : 2860

and a none item instead of duct tape, gas mask cartridges, and thread Respectively
**EXAMPLE when unloading:** 
_spawn in a gas mask using the Debug menu_
![Gas 1](https://user-images.githubusercontent.com/39046637/81346309-5efa4c00-90ba-11ea-9e12-2a41a1f64bf3.PNG)
_take the action "Unload"_
![Gas 2](https://user-images.githubusercontent.com/39046637/81346337-6a4d7780-90ba-11ea-9a00-a5c6bb148107.PNG)
_open inventory and verify that the none item is there_
![gas 3](https://user-images.githubusercontent.com/39046637/81346563-c6180080-90ba-11ea-919c-bce76c178b53.PNG)

When you reload an item like (misc repair kit, gas mask, or sewing kit) it will simply say that it was reloaded and do nothing. 
**EXAMPLE when reloading:** 
_spawn in a misc repair kit and duct tape using the Debug menu_
![Tape 1](https://user-images.githubusercontent.com/39046637/81348632-b39fc600-90be-11ea-9b41-d7b2159e214b.PNG)
_take the action Reload_
![Tape 2](https://user-images.githubusercontent.com/39046637/81348685-d631df00-90be-11ea-8427-ae3848e90437.PNG)
![Tape 3](https://user-images.githubusercontent.com/39046637/81348775-0a0d0480-90bf-11ea-80b2-dee54ceb95d1.PNG)
_open inventory and verify that the misc repair kit is still empty_
![Tape 4](https://user-images.githubusercontent.com/39046637/81348848-2446e280-90bf-11ea-8e8d-8b216d8ae37b.PNG)

# Expected behavior
**When unloading**
When I unload a gas mask I expected to get the appropriate gas mask cartridges from it. 
I expected this behavior because that is how it worked before and how I think it should function. 
**When reloading**
When I reload a misc repair kit I expected to fill it with the appropriate item(duct tape). 
I expected this behavior because that is how it worked before and how I think it should function. 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++]
]
using Windows 10

# Additional context

1. I loaded a new save, new world, and a new character for my test. 
2. Both of the **EXAMPLES** have been repeated with the following items: 
- misc repair kit
- gas mask
- filter mask
- firefighter PBA mask
- survivor fire mask
- winter survivor mask
- survivor divemask (tho not unloaded sins it spawns in empty)
- sewing kit
- tailor's kit
3. this bug has also been repeated with a soda can stove kit where unloading it results in a none and same ERROR. Tho I have not tried to reload it sens I do not know how to spawn in concentrated alcohol in a container. 

this is my first time making a Bug report so pleas give me feedback on how I did (aka tell me what I did wrong)

**Comment by ZhilkinSerg** [comment] 2020-05-07 23:36
Duplicate of #40158

**Comment by ZhilkinSerg** [comment] 2020-05-07 23:38
Everything is fine. We already have an issue open about that. However additional info you have provided will help in investigating and fixing.

**Comment by DillonSimeone** [comment] 2020-05-12 05:08
This bug occurred for me when unloading an anesthesia kit too. Wanted to fill a different kit with the tiny bits left in the one I unloaded. All charges disappeared, and a `none` appeared in my inventory instead. (On most current build right now)

**Closed** 2020-05-23 07:50 UTC
Labels: (S3 - Duplicate)
