### ISSUE TITLE
Make Blood and Gore tiles connect with each other

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27497] opened 2019-01-08 14:32 UTC
Right now gore and blood tiles are separate, so when gore starts blood tiles will end, so around the gore you will see empty space which is not that good looking.
I suggest making gore and blood tiles connected like shallow and deep water. When shallow water connects with deep water it do not have borders sepparating them, creating very nice visual effect of watter gradually passing from one phase to another. If we could get this for blood and gore tiles (and other luqids like insect blood and insect guts) it would look much better with tiles enabled.

**Comment by wapcaplet** [comment] 2021-02-16 23:17
Could not reproduce in 0.E-9681-g2cca4d658c nor for quite some time in experimental. Blood splatters are continuous across tiles:

MSXOtto+:

![image](https://user-images.githubusercontent.com/238395/108133603-12dd2e80-7072-11eb-982f-4a283138dc67.png)

Ultica:

![image](https://user-images.githubusercontent.com/238395/108133829-6fd8e480-7072-11eb-8091-c2592f2153c4.png)

**Comment by Night-Pryanik** [comment] 2021-09-15 19:46
No discussion in two years, closing.

**Closed by Night-Pryanik** 2021-09-15 19:46 UTC
Labels: <Suggestion / Discussion>, (P5 - Long-term), SDL: Tiles / Sound
