### ISSUE TITLE
Bugs Relating to the "Mini-Flamethrower CBM"

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#35578] opened 2019-11-18 03:30 UTC
# Describe the bug
Bug 1:
The fire lighter bionic returns the power it draws immediately after starting a fire. 

Bug 2:
It also cannot be activated using the "%" "Start Fire Quickly" action.

Name Issue:
Mini-Flamethrower CBM Installs as the Finger-Lighter. Makes more sense based on what it does to call it the Finger-Lighter However the CBM Item still needs its name changed.

(EG: Install Mini-Flamethrower CBM, And you get the Finger Lighter Bionic)

# Steps To Reproduce
Bug 1 (No Power Usage):
Install the Mini-Flamethrower cbm (and a Power Storage CBM)
Charge Cbm Power to full.
Use Finger Lighter to set something on fire.
Power is used prior to Setting fire, but returned After Fire has been started.

Bug 2 (Cant use it from the Quick Action Menu):
Install the Mini-Flamethrower cbm (and a Power Storage CBM)
Charge Cbm Power to full.
Press % to bring up Quick Actions.
Unable to select Quickly Start Fire.

Issue:
Rename the Mini-Flamethrower CBM to Finger-Lighter CBM,

# Expected behavior
Bug 1:
Don't return the power after starting a fire.

Bug 2:
Allow the quick action menu to recognize the Finger Lighter CBM as a fire starting source.

# Version Info
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9422-g8d5b04e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More City Locations [cityside],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

**Comment by anothersimulacrum** [comment] 2019-11-18 03:54
#1 is because
https://github.com/CleverRaven/Cataclysm-DDA/blob/b653d6b4a2b3eeb17f6807cae670a31d5651d29e/src/bionics.cpp#L534
Should be modding the power level by the negative amount to use, not the positive.
However, this change causes the power to be detracted twice, and I'm not sure why.

**Comment by Night-Pryanik** [comment] 2021-04-11 16:48
Bug №1 still exists in latest experimental as of April 11, 2021 despite #35580.

**Comment by anoobindisguise** [comment] 2023-08-15 18:41
this should be fixed now no? i've never had these issues

**Comment by Night-Pryanik** [comment] 2023-08-16 08:52
I guess we can close this until reconfirmed.

**Closed by Night-Pryanik** 2023-08-16 08:52 UTC
Labels: <Bug>, Bionics
