### ISSUE TITLE
Starter NPC doesn't react to vanilla zombie children.

### ISSUE THREAD

**Issue by CptCodpiece** [CleverRaven/Cataclysm-DDA#28019] opened 2019-02-02 01:06 UTC
**Describe the bug**  
Starter NPC won't react to zombie children.

**To Reproduce**  
Make a new world, find the starter NPC, wish in some zombie children on their head. Watch as they get torn apart and don't fight back.

**Expected behavior**  
Zombie child comes near NPC, NPC fights to defend self.

**Versions and configuration(please complete the following information):**
 - OS: - Windows 10
 - Game Version - 0.c-37210-ge6e1890
 - Graphics version - Tiles
 - Mods loaded -  Core: Dark Days Ahead - PK's Rebalancing, Arcana and Magic Items, Vehicle Additions Pack, Ascension, DinoMod, NPC traits, Mutant NPCs, Beta National Guard Camp, More Buildings, More Locations, Filthy Clothing, Tanks and Other Vehicles, Urban Development, Tall Buildings, StatsThroughSkills,

Side Note:

This seems to only apply to zombie children of the vanilla variety (Standard Non-PK version.) For some reason, PK's variety zombie children get reacted to like a threat over the vanilla zombie children. If you spawn in a bunch of NPCs, sometimes they'll react to vanilla zombie children, sometimes they won't. The ones that don't react to zombie children suddenly wake up if you spawn in a regular zombie near them and will murder the regular zombie, then go back to sleep and let the zombie children beat up on them.  I've done about 20 restarts on both vanilla and PK-enabled worlds and the starter NPC always seems to be a sleeper when it comes to zombie children for some reason.

**Comment by Amneiger** [comment] 2019-02-03 07:31
No, see, some NPCs, like the starter NPC, are so traumatized by even the concept of zombie children that they're psychologically incapable of going out and adventuring.  It's why the starter NPC just stays in the shelter unless something (like you) convinces them to leave.  You're one of the few (maybe non-psychopath) people hard enough to actually go outside and confront the possibility of killing zombie children in order to get that sweet, sweet loot.

...Kidding, kidding.  To make up for that, I decided to test it myself, using a world with only default mods.  The starter NPC shot a wolf and a regular zombie, but did not fight back against two regular zombie children.  They hit an anklebiter once, after it landed a successful hit on their torso (they ignored every other hit the anklebiter had gotten before that), and then after several more attacks from the anklebiter tried a few times to shoot them.  They successfully shot the anklebiter and then did nothing about the other two zombie children until they died.  I see what you mean, and agree that this should be fixed.

**Comment by davidpwbrown** [comment] 2019-02-03 12:38
Related to #27829 
I tried to avoid the root cause of that issue, and just fixed the symptom, 
I knew NPCs were not evaluating threat correctly. But I hoped it was just the cockroach nymph that was a problem.
Evidently not.

**Comment by kevingranade** [comment] 2019-02-14 07:59
Fixed by #28162

**Closed by kevingranade** 2019-02-14 07:59 UTC
Labels: (S1 - Need confirmation), Monsters, NPC / Factions
