### ISSUE TITLE
DEBUG    : Excessive error repetition detected. 

### ISSUE THREAD

**Issue by bullkang** [CleverRaven/Cataclysm-DDA#65357] opened 2023-04-28 11:02 UTC
### Describe the bug

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            Tried to use an invalid beta talker.

 FUNCTION : talker* dialogue::actor(bool) const
 FILE     : src/npctalk.cpp
 LINE     : 1799
 VERSION  : 69c3dbb

### Attach save file

N/A

### Steps to reproduce

Continue getting this error message every few minutes

### Expected behavior

No errors

### Versions and configuration

-OS: Manjaro Linux (Arch based)
-Graphics Version: Tiles MSXotto+
-Mods Loaded: 
   CORE CONTENT PACKS: Dark Days Ahead [dda]
   REBALANCING MODS: Disable NPC Needs
                                            Portal Storms Ignore NPCs
                                            No Fungal Growth
                                            Tamable Wildlife
                                            Stats Through Kills
                                            Stats Through Skills

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11352819/debug.log)

**Comment by BrettDong** [comment] 2023-04-28 11:08
Duplicate of #65313.

**Closed** 2023-04-28 11:09 UTC
Labels: (S1 - Need confirmation)
