### ISSUE TITLE
'E'ating soup from a tin located in a dragged shopping cart dumps the remainder of the soup on the floor.

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#18168] opened 2016-08-31 06:36 UTC
I believe this started happening just recently in one of the recent builds.  I just upgraded to 0.C-5430 (was using 0.C-5427 before) and noticed this started happening.  A typical way for this to happen is I am raiding a home and collect all the unspoiled canned food, then I heat up the can using the hobo stove to make the can 'hot', and 'E'at it straight from the shopping cart, and bam, 3 charges of the soup are gone.  Then I drag the shopping cart a few tiles and notice there is a liquid '~' icon with 3 charges of soup on the floor (or whatever unused charges would be, so maybe sometimes 1).

Edit: since this might not happen with every type of canned liquid, I'll note it was 'meat soup' last time it happened.

**Comment by SeanMirrsen** [comment] 2016-08-31 13:17
I encountered that same phenomenon recently, however I did not think it needed reporting because... well, it's supposed to happen, isn't it? An opened tin is not a resealable container. Soup will not stay inside an opened tin if the tin is moved about in a shopping cart.  
I don't remember if it happens if it's eaten while in the backpack, however. But IIRC, the opened tin is a "bucket" - an open-top container. It needs to be held in hands or standing on a solid surface in order to retain its contents.

**Comment by Coolthulhu** [comment] 2016-08-31 13:24
Should probably be special cased to be wielded if possible, unlisted otherwise.

**Comment by HeadWar** [comment] 2016-08-31 14:06
Just tried it when the can was in inventory, but not wielded, and that did not spill it. Not sure what happens if you try to pick it up into inventory, it used to be that that would spill it.

**Comment by aeoo** [comment] 2016-08-31 16:39
>Soup will not stay inside an opened tin if the tin is moved about in a shopping cart.

The charges spill to the floor when the shopping cart is stationary.  I don't think that should happen.  When the shopping cart is parked/stationary, it should be possible to eat from it without losing food.  It's simply a UI convenience.

I only moved the shopping cart *after* losing my soup charges to see where they charges went.

**Comment by nornagon** [comment] 2016-09-06 02:11
This happened to me while eating soup from a cargo space while the car was stationary. It doesn't make sense to me that having the can in your inventory would stop it from spilling--shoving an open can of mushroom soup into your cargo pants won't keep the soup inside the can. Also, often a single serve of the soup isn't enough to make me full, so I end up eating 1/4 of a can of soup and throwing the rest on the ground, even though I'm still hungry.

I bet IRL I could make a 3/4 full open tin of soup stay mostly full in a moving car or shopping cart with careful placement and use of the tin's lid.

What's the intention behind this mechanic? (or is it just a bug?)

**Comment by SeanMirrsen** [comment] 2016-09-06 10:39
The staying contained in inventory is probably equal parts oversight and intended deviation from design. Making the opened tin spill if put into inventory would require its 'E'at action to be special-cased, or expanded into a general mechanic, where an item has to be wielded before it can be used/interacted with. The problem with that is that as part of anti-frustration features the wielding would have to be automatic, there would have to be dialogs asking the player if they really want to put away what they're holding to eat out of the spill-happy container, as well as further dialogs warning the player that no, they can't put the open can into their inventory when they wield something else, without the contents of the tin being unloaded onto the ground.

It is, all in all, a large amount of work that nobody really wants to do for such a low gain.

**Comment by nornagon** [comment] 2016-09-06 15:16
Seems to me like the easiest option is to just let the tin keep its soup.

**Comment by LyleSY** [comment] 2017-09-13 14:51
How committed are we to realistically modeling incremental soup sipping dynamics in various environmental conditions in this survival horror game? Why not change "soup" to quantity 1 per can and quadruple its effects? I can tell you from vast experience that I have never opened a can of soup I did not intend to destroy utterly, and all at once.

**Comment by nornagon** [comment] 2017-09-14 01:19
> How committed are we to realistically modeling incremental soup sipping dynamics in various environmental conditions in this survival horror game?

You must be new here ;)

**Comment by elricsfate** [comment] 2017-12-15 00:27
It seems like an easier way to handle this would be that a tin cannot be considered usable for storage after opening

After eating the preferred contents of the soup, why not prompt the user to place it in another container? A tupperware, a bottle, a jar, etc.

**Comment by Brambor** [comment] 2018-06-03 14:49
What about if the container is somewhere that will cause spilling (shopping cart, car) then player gets warning before they tries to eat that thing that it will spill?
Seems like easiest fix.
Additionally, not so easy and probably disgusting looking code, a player could be warned and then asked whether they want to continue eating rather than spillin the content?
To add atop it could be calculated whether a player would be able to consume entire _n portion_ meal (only when spillable and in nonreseable container) and when warned it could say:
"You can only eat 3 out of 4 charges, the rest would be spilled proceed unsealing (unreseable container)?" /hit Yes
Folowed by:
"Consume meat soup (x)? Content is in unreseable container and WILL SPILL (will trigger unload dialog) if not consumed at once." /hit Yes
/will repeat 3 times (where x = 4-times repeated)
"You cannot finish meat soup (1) eat anyway?" /hit No
"You are unloading meatsoup (1)" Followed by where to unload including option to eat.
if ESC is pressed ask "Really spill?"
That should be it.

**Comment by LyleSY** [comment] 2018-06-04 13:35
I continue to think that Hungry Hobo is the best fix for now, and if someone wants to code something complicated to give us realistic sipping, that’s a great feature for the next version (though not necessary), but I may be biased as the author.

**Comment by 0be1isk** [comment] 2018-07-18 05:59
This is a hilarious issue, and the fact it hasn't been fixed yet is even funnier

**Comment by sfsworms** [comment] 2018-07-18 07:02
Well, go and fix it if it's that easy. :/ Don't forget to deal with cart collisions, soup in inventory and all the things.

**Comment by 0be1isk** [comment] 2018-07-18 14:48
I don't even think this is a that bug of an issue. I completely agree with @LyleSY, Idk anyone who has opened a van of soup and not finish the entire thing, charges for soup seems more of a convienence to have multiple sources of food (charges) in a small contained item. It doesn't seem like something most people do irl.

**Comment by nornagon** [comment] 2018-07-18 18:27
> van of soup

I'm greatly amused that this is actually something you can currently do in
cdda.

**Comment by Epictyphlosion** [comment] 2018-08-11 11:02
Not sure if this is still being worked on or not, but it shouldn't be that hard to fix. All that needs to be changed is what happens after eating the soup, so the game displays the message "There's still some left over!" and leave the partially eaten tin of soup in the shopping cart

**Comment by Epictyphlosion** [comment] 2018-08-11 11:04
@0be1isk I agree. I think the problem is that there are more people that are making suggestions for the game than people actually contributing to the game. If that doesn't change, who knows how long it will be until 0.D comes to be?

**Closed** 2018-08-23 19:58 UTC
Labels: <Bug>
